var searchData=
[
  ['kepsilon',['kEpsilon',['../a01257.html',1,'Foam::RASModels']]],
  ['keqn',['kEqn',['../a01258.html',1,'Foam::LESModels']]],
  ['keyed',['Keyed',['../a01259.html',1,'Foam']]],
  ['keytype',['keyType',['../a01260.html',1,'Foam']]],
  ['kinematiccloud',['kinematicCloud',['../a01261.html',1,'kinematicCloud'],['../a01262.html',1,'KinematicCloud&lt; CloudType &gt;']]],
  ['kinematiccloud_3c_20cloud_3c_20basickinematiccollidingparcel_20_3e_20_3e',['KinematicCloud&lt; Cloud&lt; basicKinematicCollidingParcel &gt; &gt;',['../a01262.html',1,'Foam']]],
  ['kinematiccloud_3c_20foam_3a_3adsmccloud_20_3e',['KinematicCloud&lt; Foam::DSMCCloud &gt;',['../a01262.html',1,'Foam']]],
  ['kinematiclookuptableinjection',['KinematicLookupTableInjection',['../a01263.html',1,'Foam']]],
  ['kinematicparcel',['KinematicParcel',['../a01264.html',1,'Foam']]],
  ['kinematicparcelinjectiondata',['kinematicParcelInjectionData',['../a01265.html',1,'Foam']]],
  ['kinematicparcelinjectiondataiolist',['kinematicParcelInjectionDataIOList',['../a01266.html',1,'Foam']]],
  ['kinematicsinglelayer',['kinematicSingleLayer',['../a01267.html',1,'Foam']]],
  ['kinematicsinglelayer',['kinematicSingleLayer',['../a01268.html',1,'Foam::regionModels::surfaceFilmModels']]],
  ['kinetictheorymodel',['kineticTheoryModel',['../a01269.html',1,'Foam::RASModels']]],
  ['kinetictheorymodel',['kineticTheoryModel',['../a01270.html',1,'Foam']]],
  ['kklomega',['kkLOmega',['../a01271.html',1,'Foam::incompressible::RASModels']]],
  ['klowrewallfunctionfvpatchscalarfield',['kLowReWallFunctionFvPatchScalarField',['../a01272.html',1,'Foam']]],
  ['kmesh',['Kmesh',['../a01273.html',1,'Foam']]],
  ['komega',['kOmega',['../a01274.html',1,'Foam::RASModels']]],
  ['komegasst',['kOmegaSST',['../a01277.html',1,'Foam::LESModels']]],
  ['komegasst',['kOmegaSST',['../a01276.html',1,'Foam::RASModels']]],
  ['komegasst',['kOmegaSST',['../a01275.html',1,'Foam']]],
  ['komegasstdes',['kOmegaSSTDES',['../a01278.html',1,'Foam::LESModels']]],
  ['komegasstlm',['kOmegaSSTLM',['../a01279.html',1,'Foam::RASModels']]],
  ['komegasstsas',['kOmegaSSTSAS',['../a01280.html',1,'Foam::RASModels']]],
  ['komegasstsato',['kOmegaSSTSato',['../a01281.html',1,'Foam::RASModels']]],
  ['kqrwallfunctionfvpatchfield',['kqRWallFunctionFvPatchField',['../a01282.html',1,'Foam']]],
  ['kts',['KTS',['../a01283.html',1,'Foam::XiGModels']]],
  ['kunz',['Kunz',['../a01284.html',1,'Foam::phaseChangeTwoPhaseMixtures']]]
];
