OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
actuationDiskSource Class Reference
Actuation disk source.
Public Member Functions
TypeName ("actuationDiskSource")
Runtime type information.
actuationDiskSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~actuationDiskSource ()
Destructor.
scalar Cp () const
Return Cp.
scalar Ct () const
Return Ct.
const vector & diskDir () const
Normal disk direction.
scalar diskArea () const
Disk area.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
Source term to momentum equation.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Source term to compressible momentum equation.
virtual bool read (const dictionary &dict)
Read dictionary.
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
Runtime type information.
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~cellSetOption ()
Destructor.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const labelList & cells () const
Return const access to the cell set.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
Switch & active ()
Return access to the source active flag.
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldI)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldI)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldI)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Protected Attributes
vector diskDir_
Disk area normal.
scalar Cp_
Power coefficient.
scalar Ct_
Thrust coefficient.
scalar diskArea_
Disk area.
point upstreamPoint_
Upstream point sample.
label upstreamCellId_
Upstream cell ID.
Protected Attributes inherited from cellSetOption
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType { smPoints, smCellSet, smCellZone, smAll }
Enumeration for selection mode types.
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Static Public Attributes inherited from cellSetOption
static const NamedEnum< selectionModeType, 4 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Detailed Description
Actuation disk source.
Constant values for momentum source for actuation disk
and
where:
= disk area
= upstream velocity
= 1 - Cp/Ct
= velocity at the disk
Source usage
Example usage:
    actuationDiskSourceCoeffs
    {
        fieldNames      (U);        // names of fields to apply source
        diskDir         (-1 0 0);   // disk direction
        Cp              0.1;        // power coefficient
        Ct              0.5;        // thrust coefficient
        diskArea        5.0;        // disk area
        upstreamPoint   (0 0 0);    // upstream point
    }
Source files
actuationDiskSource.H
actuationDiskSource.C
actuationDiskSourceTemplates.C
Definition at line 100 of file actuationDiskSource.H.
Constructor & Destructor Documentation
actuationDiskSource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 83 of file actuationDiskSource.C.
References Foam::endl(), polyMesh::findCell(), Foam::Info, and Foam::name().
virtual ~actuationDiskSource () inline virtual
Destructor.
Definition at line 172 of file actuationDiskSource.H.
Member Function Documentation
TypeName ("actuationDiskSource")
Runtime type information.
scalar Cp () const inline
Return Cp.
Definition at line 181 of file actuationDiskSource.H.
References actuationDiskSource::Cp_.
scalar Ct () const inline
Return Ct.
Definition at line 187 of file actuationDiskSource.H.
References actuationDiskSource::Ct_.
const vector& diskDir () const inline
Normal disk direction.
Definition at line 193 of file actuationDiskSource.H.
References actuationDiskSource::diskDir_.
scalar diskArea () const inline
Disk area.
Definition at line 199 of file actuationDiskSource.H.
References actuationDiskSource::diskArea_.
void addSup (fvMatrix< vector > & eqn, const label fieldI) virtual
Source term to momentum equation.
Reimplemented from option.
Reimplemented in radialActuationDiskSource.
Definition at line 113 of file actuationDiskSource.C.
References fvMatrix< Type >::psi(), fvMatrix< Type >::source(), and U.
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldI) virtual
Source term to compressible momentum equation.
Reimplemented from option.
Reimplemented in radialActuationDiskSource.
Definition at line 137 of file actuationDiskSource.C.
References fvMatrix< Type >::psi(), fvMatrix< Type >::source(), and U.
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from cellSetOption.
Reimplemented in radialActuationDiskSource.
Definition at line 161 of file actuationDiskSource.C.
References cellSetOption::read().
Referenced by radialActuationDiskSource::read().
Member Data Documentation
vector diskDir_ protected
Disk area normal.
Definition at line 110 of file actuationDiskSource.H.
Referenced by actuationDiskSource::diskDir().
scalar Cp_ protected
Power coefficient.
Definition at line 113 of file actuationDiskSource.H.
Referenced by actuationDiskSource::Cp().
scalar Ct_ protected
Thrust coefficient.
Definition at line 116 of file actuationDiskSource.H.
Referenced by actuationDiskSource::Ct().
scalar diskArea_ protected
Disk area.
Definition at line 119 of file actuationDiskSource.H.
Referenced by actuationDiskSource::diskArea().
point upstreamPoint_ protected
Upstream point sample.
Definition at line 122 of file actuationDiskSource.H.
label upstreamCellId_ protected
Upstream cell ID.
Definition at line 125 of file actuationDiskSource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/actuationDiskSource/actuationDiskSource.H
src/fvOptions/sources/derived/actuationDiskSource/actuationDiskSource.C
src/fvOptions/sources/derived/actuationDiskSource/actuationDiskSourceTemplates.C