OpenFOAM: abort Class Reference
abort Class Reference
FunctionObjects » Utility function objects
Watches for presence of the named file in the $FOAM_CASE directory and aborts the calculation if it is present.
Public Types
enum actionType { noWriteNow, writeNow, nextWrite }
Enumeration defining the type of action.
Public Member Functions
TypeName ("abort")
Runtime type information.
abort (const word &name, const Time &runTime, const dictionary &)
Construct from Time and dictionary.
virtual ~abort ()
Destructor.
virtual bool read (const dictionary &)
Read the dictionary settings.
virtual bool execute ()
Execute, check existence of abort file and take action.
virtual bool write ()
Execute, check existence of abort file and take action.
virtual bool end ()
Execute at the final time-loop, used for cleanup.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Watches for presence of the named file in the $FOAM_CASE directory and aborts the calculation if it is present.
Currently the following action types are supported:
noWriteNow
writeNow
nextWrite
Source files
abort.H
abort.C
Definition at line 60 of file abort.H.
Member Enumeration Documentation
enum actionType
Enumeration defining the type of action.
Enumerator
noWriteNow
stop immediately without writing data
writeNow
write data and stop immediately
nextWrite
stop the next time data are written
Definition at line 69 of file abort.H.
Constructor & Destructor Documentation
abort (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 88 of file abort.C.
References Foam::read().
~abort () virtual
Destructor.
Definition at line 109 of file abort.C.
Member Function Documentation
TypeName ("abort")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the dictionary settings.
Reimplemented from functionObject.
Definition at line 115 of file abort.C.
References dictionary::found(), dictionary::lookup(), and dictionary::readIfPresent().
bool execute () virtual
Execute, check existence of abort file and take action.
Implements functionObject.
Definition at line 135 of file abort.C.
References Foam::endl(), Foam::Info, Foam::isFile(), Foam::reduce(), Time::saNextWrite, Time::saNoWriteNow, and Time::saWriteNow.
bool write () virtual
Execute, check existence of abort file and take action.
Implements functionObject.
Definition at line 186 of file abort.C.
bool end () virtual
Execute at the final time-loop, used for cleanup.
Reimplemented from functionObject.
Definition at line 192 of file abort.C.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/abort/abort.H
src/functionObjects/utilities/abort/abort.C