OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
autoPtr< T > Class Template Reference
An auto-pointer similar to the STL auto_ptr but with automatic casting to a reference to the type and with pointer allocation checking on access.
Public Types
typedef T Type
Public Member Functions
autoPtr (T *=0)
Store object pointer.
autoPtr (const autoPtr< T > &)
Construct as copy by transferring pointer to this autoPtr and.
autoPtr (const autoPtr< T > &, const bool reuse)
Construct either by transferring pointer or cloning. Should.
~autoPtr ()
Destructor, delete object if pointer is not NULL.
bool empty () const
Return true if the autoPtr is empty (ie, no pointer set).
bool valid () const
Return true if the autoPtr valid (ie, the pointer is set).
T * ptr ()
Return object pointer for reuse.
void set (T *)
Set pointer to that given.
void reset (T *=0)
If object pointer already set, delete object and set to given.
void clear ()
Delete object (if the pointer is valid) and set pointer to NULL.
T & operator() ()
Return reference to the object data.
const T & operator() () const
Return const reference to the object data.
operator const T & () const
Const cast to the underlying type reference.
T * operator-> ()
Return object pointer.
const T * operator-> () const
Return const object pointer.
void operator= (const autoPtr< T > &)
Take over the object pointer from parameter.
Detailed Description
template<class T>
class Foam::autoPtr< T >
An auto-pointer similar to the STL auto_ptr but with automatic casting to a reference to the type and with pointer allocation checking on access.
Source files
autoPtr.H
autoPtrI.H
Definition at line 53 of file PtrList.H.
Member Typedef Documentation
typedef T Type
Definition at line 60 of file autoPtr.H.
Constructor & Destructor Documentation
autoPtr (T * p = 0) inline explicit
Store object pointer.
Definition at line 32 of file autoPtrI.H.
autoPtr (const autoPtr< T > & ap) inline
Construct as copy by transferring pointer to this autoPtr and.
setting the arguments pointer to NULL
Definition at line 39 of file autoPtrI.H.
autoPtr (const autoPtr< T > & ap, const bool reuse) inline
Construct either by transferring pointer or cloning. Should.
only be called with type that supports cloning.
Definition at line 48 of file autoPtrI.H.
References autoPtr< T >::ptr(), and autoPtr< T >::valid().
~autoPtr () inline
Destructor, delete object if pointer is not NULL.
Definition at line 67 of file autoPtrI.H.
References autoPtr< T >::clear().
Member Function Documentation
bool empty () const inline
Return true if the autoPtr is empty (ie, no pointer set).
Definition at line 76 of file autoPtrI.H.
Referenced by sampledIsoSurfaceCell::faces(), sampledCuttingPlane::faces(), distanceSurface::faces(), and sampledIsoSurface::faces().
bool valid () const inline
Return true if the autoPtr valid (ie, the pointer is set).
Definition at line 83 of file autoPtrI.H.
Referenced by refinementHistoryConstraint::add(), refinementHistoryConstraint::apply(), autoPtr< T >::autoPtr(), decompositionModel::decomposer(), snappySnapDriver::detectNearSurfaces(), meshRefinement::distribute(), snappySnapDriver::doSnap(), mapPolyMesh::hasOldCellVolumes(), listPlusEqOp< T >::operator()(), Foam::operator<<(), GAMGAgglomeration::processorAgglomerate(), radiativeIntensityRay::radiativeIntensityRay(), functionObjectList::read(), rawTopoChangerFvMesh::update(), mixerFvMesh::update(), movingConeTopoFvMesh::update(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), and medialAxisMeshMover::~medialAxisMeshMover().
T * ptr () inline
Return object pointer for reuse.
Definition at line 90 of file autoPtrI.H.
References Foam::T().
Referenced by autoPtr< T >::autoPtr(), rigidBodyModel::join(), autoPtr< T >::operator=(), functionObjectList::read(), PtrListDictionary< T >::set(), triSurfaceMesh::setField(), and regIOobject::store().
void set (T * p) inline
Set pointer to that given.
If object pointer already set issue a FatalError.
Definition at line 99 of file autoPtrI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), p, and Foam::T().
Referenced by searchablePlateFeatures::features(), rigidBodyModel::merge(), and functionObjectList::read().
void reset (T * p = 0) inline
If object pointer already set, delete object and set to given.
pointer
Definition at line 114 of file autoPtrI.H.
References p.
Referenced by refinementHistoryConstraint::add(), polyMeshAdder::add(), refinementHistoryConstraint::apply(), autoPtr< T >::clear(), noPyrolysis::constructThermoChemistry(), snappySnapDriver::detectNearSurfaces(), distributedTriSurfaceMesh::distribute(), sampledIsoSurfaceCell::faces(), sampledCuttingPlane::faces(), distanceSurface::faces(), sampledIsoSurface::faces(), PatchTools::gatherAndMerge(), polyTopoChange::makeMesh(), functionObjectList::New(), listPlusEqOp< T >::operator()(), autoPtr< T >::operator=(), radiativeIntensityRay::radiativeIntensityRay(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), and medialAxisMeshMover::~medialAxisMeshMover().
void clear () inline
Delete object (if the pointer is valid) and set pointer to NULL.
Definition at line 126 of file autoPtrI.H.
References autoPtr< T >::reset().
Referenced by polyMeshAdder::add(), meshRefinement::distribute(), and autoPtr< T >::~autoPtr().
T & operator() () inline
Return reference to the object data.
Definition at line 135 of file autoPtrI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
Referenced by autoPtr< T >::operator const T &().
const T & operator() () const inline
Return const reference to the object data.
Definition at line 150 of file autoPtrI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
operator const T & () const inline
Const cast to the underlying type reference.
Definition at line 165 of file autoPtrI.H.
References autoPtr< T >::operator()().
T * operator-> () inline
Return object pointer.
Definition at line 172 of file autoPtrI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
const T * operator-> () const inline
Return const object pointer.
Definition at line 187 of file autoPtrI.H.
void operator= (const autoPtr< T > & ap) inline
Take over the object pointer from parameter.
Definition at line 194 of file autoPtrI.H.
References autoPtr< T >::ptr(), and autoPtr< T >::reset().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/PtrList/PtrList.H
src/OpenFOAM/memory/autoPtr/autoPtr.H
src/OpenFOAM/memory/autoPtr/autoPtrI.H