OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible Turbulence BCs » Compressible turbulence wall functions
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model for the Eulerian multiphase solvers.
Public Member Functions
TypeName ("compressible::alphatPhaseChangeJayatillekeWallFunction")
Runtime type information.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from alphatPhaseChangeWallFunctionFvPatchScalarField
TypeName ("compressible::alphatPhaseChangeWallFunction")
Runtime type information.
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &)
Construct as copy.
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const scalarField & dmdt () const
Return the rate of phase-change.
const scalarField & mDotL () const
Return the enthelpy source due to phase-change.
Protected Member Functions
void checkType ()
Check the type of the patch.
tmp< scalarField > Psmooth (const scalarField &Prat) const
'P' function
tmp< scalarField > yPlusTherm (const scalarField &P, const scalarField &Prat) const
Calculate y+ at the edge of the thermal laminar sublayer.
tmp< scalarField > calcAlphat (const scalarField &prevAlphat) const
Update turbulent thermal diffusivity.
Protected Attributes
scalar Prt_
Turbulent Prandtl number.
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
Protected Attributes inherited from alphatPhaseChangeWallFunctionFvPatchScalarField
scalarField dmdt_
Rate of phase-change.
scalarField mDotL_
Latent heat of the phase-change.
Static Protected Attributes
static scalar maxExp_
static scalar tolerance_
static label maxIters_
Detailed Description
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model for the Eulerian multiphase solvers.
Patch usage
Property Description Required Default value
Prt Turbulent Prandtl number no 0.85
Cmu Model coefficient no 0.09
kappa von Karman constant no 0.41
E Model coefficient no 9.8
Example of the boundary condition specification:
    myPatch
    {
        type            alphatPhaseChangeJayatillekeWallFunction;
        Prt             0.85;
        kappa           0.41;
        E               9.8;
        value           uniform 0; // optional value entry
    }
See also
Foam::compressible::alphatPhaseChangeWallFunctionFvPatchScalarField
Source files
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.C
Definition at line 105 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
Referenced by alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::clone().
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField onto a new patch
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &)
Construct as copy.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
void checkType () protected
Check the type of the patch.
tmp<scalarField> Psmooth (const scalarField & Prat) const protected
'P' function
tmp<scalarField> yPlusTherm (const scalarField & P, const scalarField & Prat) const protected
Calculate y+ at the edge of the thermal laminar sublayer.
tmp<scalarField> calcAlphat (const scalarField & prevAlphat) const protected
Update turbulent thermal diffusivity.
TypeName ("compressible::alphatPhaseChangeJayatillekeWallFunction")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented in alphatWallBoilingWallFunctionFvPatchScalarField, and alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.
Definition at line 196 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
References alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in alphatWallBoilingWallFunctionFvPatchScalarField, and alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.
Definition at line 216 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
References alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField::alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField().
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Implements alphatPhaseChangeWallFunctionFvPatchScalarField.
Reimplemented in alphatWallBoilingWallFunctionFvPatchScalarField, and alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.
virtual void write (Ostream &) const virtual
Write.
Reimplemented from alphatPhaseChangeWallFunctionFvPatchScalarField.
Reimplemented in alphatWallBoilingWallFunctionFvPatchScalarField, and alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.
Member Data Documentation
scalar Prt_ protected
Turbulent Prandtl number.
Definition at line 115 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
scalar Cmu_ protected
Cmu coefficient.
Definition at line 118 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
scalar kappa_ protected
Von Karman constant.
Definition at line 121 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
scalar E_ protected
E coefficient.
Definition at line 124 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
scalar maxExp_ static protected
Definition at line 128 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
scalar tolerance_ static protected
Definition at line 129 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
label maxIters_ static protected
Definition at line 130 of file alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/derivedFvPatchFields/alphatPhaseChangeJayatillekeWallFunction/alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.H