OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
AtomizationModel< CloudType > Class Template Reference abstract
Templated atomization model class.
Public Member Functions
TypeName ("atomizationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AtomizationModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
AtomizationModel (CloudType &owner)
Construct null from owner.
AtomizationModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
AtomizationModel (const AtomizationModel< CloudType > &am)
Construct copy.
virtual autoPtr< AtomizationModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~AtomizationModel ()
Destructor.
scalar Taverage (const scalar &Tliq, const scalar &Tc) const
Average temperature calculation.
virtual scalar initLiquidCore () const =0
Initial value of liquidCore.
virtual bool calcChi () const =0
Flag to indicate if chi needs to be calculated.
virtual void update (const scalar dt, scalar &d, scalar &liquidCore, scalar &tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector &pos, const vector &injectionPos, const scalar pAmbient, const scalar chi, cachedRandom &rndGen) const =0
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< AtomizationModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::AtomizationModel< CloudType >
Templated atomization model class.
Source files
AtomizationModel.H
AtomizationModel.C
AtomizationModelNew.C
Definition at line 47 of file SprayCloud.H.
Constructor & Destructor Documentation
AtomizationModel (CloudType & owner)
Construct null from owner.
Definition at line 32 of file AtomizationModel.C.
Referenced by AtomizationModel< CloudType >::AtomizationModel().
AtomizationModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from dictionary.
Definition at line 52 of file AtomizationModel.C.
AtomizationModel (const AtomizationModel< CloudType > & am)
Construct copy.
Definition at line 42 of file AtomizationModel.C.
References AtomizationModel< CloudType >::AtomizationModel().
~AtomizationModel () virtual
Destructor.
Definition at line 65 of file AtomizationModel.C.
References AtomizationModel< CloudType >::Taverage().
Member Function Documentation
TypeName ("atomizationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , AtomizationModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
virtual autoPtr<AtomizationModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in LISAAtomization< CloudType >, BlobsSheetAtomization< CloudType >, and NoAtomization< CloudType >.
Foam::autoPtr< Foam::AtomizationModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file AtomizationModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
Foam::scalar Taverage (const scalar & Tliq, const scalar & Tc) const
Average temperature calculation.
Definition at line 73 of file AtomizationModel.C.
Referenced by SprayParcel< ParcelType >::calcAtomization(), and AtomizationModel< CloudType >::~AtomizationModel().
virtual scalar initLiquidCore () const pure virtual
Initial value of liquidCore.
Implemented in LISAAtomization< CloudType >, BlobsSheetAtomization< CloudType >, and NoAtomization< CloudType >.
virtual bool calcChi () const pure virtual
Flag to indicate if chi needs to be calculated.
Implemented in LISAAtomization< CloudType >, BlobsSheetAtomization< CloudType >, and NoAtomization< CloudType >.
Referenced by SprayParcel< ParcelType >::calcAtomization().
virtual void update (const scalar dt, scalar & d, scalar & liquidCore, scalar & tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector & pos, const vector & injectionPos, const scalar pAmbient, const scalar chi, cachedRandom & rndGen) const pure virtual
Implemented in LISAAtomization< CloudType >, BlobsSheetAtomization< CloudType >, and NoAtomization< CloudType >.
Referenced by SprayParcel< ParcelType >::calcAtomization().
The documentation for this class was generated from the following files:
src/lagrangian/spray/clouds/Templates/SprayCloud/SprayCloud.H
src/lagrangian/spray/submodels/AtomizationModel/AtomizationModel/AtomizationModel.H
src/lagrangian/spray/submodels/AtomizationModel/AtomizationModel/AtomizationModel.C
src/lagrangian/spray/submodels/AtomizationModel/AtomizationModel/AtomizationModelNew.C