OpenFOAM: atmBoundaryLayerInletEpsilonFvPatchScalarField Class Reference
atmBoundaryLayerInletEpsilonFvPatchScalarField Class Reference
Turbulence » RAS turbulence » RAS boundary conditionsBoundary Conditions » | Inlet boundary Conditions
This boundary condition specifies an inlet value for the turbulence dissipation, , appropriate for atmospheric boundary layers.
Public Member Functions
TypeName ("atmBoundaryLayerInletEpsilon")
Runtime type information.
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from atmBoundaryLayer
atmBoundaryLayer ()
Construct null.
atmBoundaryLayer (const vectorField &p, const dictionary &)
Construct from the coordinates field and dictionary.
atmBoundaryLayer (const atmBoundaryLayer &, const fvPatchFieldMapper &)
Construct by mapping given.
atmBoundaryLayer (const atmBoundaryLayer &)
Construct as copy.
const vector & flowDir () const
Return flow direction.
const vector & zDir () const
Return z-direction.
const scalarField & Ustar () const
Return friction velocity.
void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
void rmap (const atmBoundaryLayer &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
tmp< vectorField > U (const vectorField &p) const
Return the velocity distribution for the ATM.
tmp< scalarField > k (const vectorField &p) const
Return the turbulent kinetic energy distribution for the ATM.
tmp< scalarField > epsilon (const vectorField &p) const
Return the turbulent dissipation rate distribution for the ATM.
void write (Ostream &) const
Write.
Detailed Description
This boundary condition specifies an inlet value for the turbulence dissipation, , appropriate for atmospheric boundary layers.
See Foam::atmBoundaryLayer for details.
Example of the boundary condition specification:
ground
{
    type            atmBoundaryLayerInletEpsilon;
    z               (0 0 1);
    Uref            10.0;
    Zref            20.0;
    z0              uniform 0.1;
    zGround         uniform 0.0;
}
See also
Foam::atmBoundaryLayer, Foam::atmBoundaryLayerInletVelocityFvPatchVectorField, Foam::atmBoundaryLayerInletKFvPatchScalarField
Source files
atmBoundaryLayerInletEpsilonFvPatchScalarField.H
atmBoundaryLayerInletEpsilonFvPatchScalarField.C
Definition at line 74 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
Constructor & Destructor Documentation
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 41 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
Referenced by atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), and atmBoundaryLayerInletEpsilonFvPatchScalarField::clone().
atmBoundaryLayerInletEpsilonFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 53 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), epsilon, and Field< scalar >::operator=().
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
atmBoundaryLayerInletEpsilonFvPatchScalarField onto a new patch
Definition at line 68 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField().
atmBoundaryLayerInletEpsilonFvPatchScalarField (const atmBoundaryLayerInletEpsilonFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 82 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::autoMap().
Member Function Documentation
TypeName ("atmBoundaryLayerInletEpsilon")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 114 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 131 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.H.
References atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), atmBoundaryLayerInletEpsilonFvPatchScalarField::autoMap(), atmBoundaryLayerInletEpsilonFvPatchScalarField::rmap(), and atmBoundaryLayerInletEpsilonFvPatchScalarField::write().
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 95 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayer::autoMap(), and atmBoundaryLayerInletEpsilonFvPatchScalarField::rmap().
Referenced by atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), and atmBoundaryLayerInletEpsilonFvPatchScalarField::clone().
void rmap (const fvPatchScalarField & psf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 105 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References atmBoundaryLayer::rmap().
Referenced by atmBoundaryLayerInletEpsilonFvPatchScalarField::autoMap(), and atmBoundaryLayerInletEpsilonFvPatchScalarField::clone().
void write (Ostream & os) const virtual
Write.
Definition at line 119 of file atmBoundaryLayerInletEpsilonFvPatchScalarField.C.
References Foam::makePatchTypeField(), atmBoundaryLayer::write(), and fvPatchField< Type >::write().
Referenced by atmBoundaryLayerInletEpsilonFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/atmBoundaryLayerInletEpsilon/atmBoundaryLayerInletEpsilonFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/atmBoundaryLayerInletEpsilon/atmBoundaryLayerInletEpsilonFvPatchScalarField.C