OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
angularOscillatingVelocityPointPatchVectorField Class Reference
Foam::angularOscillatingVelocityPointPatchVectorField.
Public Member Functions
TypeName ("angularOscillatingVelocity")
Runtime type information.
angularOscillatingVelocityPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
Construct from patch and internal field.
angularOscillatingVelocityPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
angularOscillatingVelocityPointPatchVectorField (const angularOscillatingVelocityPointPatchVectorField &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<vector> onto a new patch.
virtual autoPtr< pointPatchField< vector > > clone () const
Construct and return a clone.
angularOscillatingVelocityPointPatchVectorField (const angularOscillatingVelocityPointPatchVectorField &, const DimensionedField< vector, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< vector > > clone (const DimensionedField< vector, pointMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< vector > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from fixedValuePointPatchField< vector >
TypeName ("fixedValue")
Runtime type information.
fixedValuePointPatchField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
Construct from patch and internal field.
fixedValuePointPatchField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &, const bool valueRequired=true)
Construct from patch, internal field and dictionary.
fixedValuePointPatchField (const fixedValuePointPatchField< vector > &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
fixedValuePointPatchField (const fixedValuePointPatchField< vector > &, const DimensionedField< vector, pointMesh > &)
Construct as copy setting internal field reference.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual void operator= (const Field< vector > &)
virtual void operator= (const vector &)
Public Member Functions inherited from valuePointPatchField< vector >
TypeName ("value")
Runtime type information.
valuePointPatchField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
Construct from patch and internal field.
valuePointPatchField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &, const bool valueRequired=true)
Construct from patch, internal field and dictionary.
valuePointPatchField (const valuePointPatchField< vector > &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
valuePointPatchField (const valuePointPatchField< vector > &, const DimensionedField< vector, pointMesh > &)
Construct as copy setting internal field reference.
label size () const
Return size.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
virtual void operator= (const valuePointPatchField< vector > &)
virtual void operator= (const pointPatchField< vector > &)
virtual void operator== (const valuePointPatchField< vector > &)
virtual void operator== (const pointPatchField< vector > &)
virtual void operator== (const Field< vector > &)
virtual void operator== (const vector &)
Public Member Functions inherited from pointPatchField< vector >
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< vector, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< vector > &ptf, const pointPatch &p, const DimensionedField< vector, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< vector, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< vector > &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< vector > &)
Construct as copy.
pointPatchField (const pointPatchField< vector > &, const DimensionedField< vector, pointMesh > &)
Construct as copy setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< vector, pointMesh > & internalField () const
Return dimensioned internal field reference.
const Field< vector > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< vector > > patchInternalField () const
Return field created from appropriate internal field values.
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void operator+= (const pointPatchField< vector > &)
virtual void operator+= (const Field< vector > &)
virtual void operator+= (const vector &)
virtual void operator-= (const pointPatchField< vector > &)
virtual void operator-= (const Field< vector > &)
virtual void operator-= (const vector &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator*= (const scalar)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator/= (const scalar)
Public Member Functions inherited from Field< vector >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const vector &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< vector > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< vector >> &)
Construct by transferring the List contents.
Field (const UList< vector > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< vector > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< vector >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< vector > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< vector > &mapF, const FieldMapper &map, const vector &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< vector > &mapF, const FieldMapper &map, const UList< vector > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const vector &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const UList< vector > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< vector > &)
Construct as copy.
Field (Field< vector > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< vector >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< vector >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< vector > > clone () const
Clone.
void map (const UList< vector > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< vector > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< vector >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< vector > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< vector > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< vector > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
VSForm block (const label start) const
tmp< Field< vector > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< vector > &)
void operator= (const UList< vector > &)
void operator= (const SubField< vector > &)
void operator= (const tmp< Field< vector >> &)
void operator= (const vector &)
void operator= (const zero)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< vector > &)
void operator+= (const tmp< Field< vector >> &)
void operator+= (const vector &)
void operator-= (const UList< vector > &)
void operator-= (const tmp< Field< vector >> &)
void operator-= (const vector &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator*= (const scalar &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< vector >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const vector &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< vector > &)
Copy constructor.
List (const Xfer< List< vector >> &)
Construct by transferring the parameter contents.
List (List< vector > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< vector > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< vector, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< vector > &)
Construct as copy of PtrList<T>
List (const SLList< vector > &)
Construct as copy of SLList<T>
List (const UIndirectList< vector > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< vector > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< vector > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const vector &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const vector &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const vector &)
Append an element at the end of the list.
void append (const UList< vector > &)
Append a List at the end of this list.
void append (const UIndirectList< vector > &)
Append a UIndirectList at the end of this list.
void transfer (List< vector > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< vector, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< vector > &)
Transfer the contents of the argument List into this list.
Xfer< List< vector > > xfer ()
Transfer contents to the Xfer container.
vector & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< vector > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< vector > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< vector > &)
Assignment operator. Takes linear time.
void operator= (const SLList< vector > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< vector > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< vector > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const vector &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Additional Inherited Members
Public Types inherited from pointPatchField< vector >
typedef pointPatch Patch
typedef calculatedPointPatchField< vector > Calculated
Public Types inherited from Field< vector >
typedef pTraits< vector >::cmptType cmptType
Component type.
typedef SubField< vector > subField
Declare type of subField.
Public Types inherited from List< vector >
typedef SubList< vector > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from pointPatchField< vector >
static autoPtr< pointPatchField< vector > > New (const word &, const pointPatch &, const DimensionedField< vector, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< vector > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< vector, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< vector > > New (const pointPatchField< vector > &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr< pointPatchField< vector > > New (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static autoPtr< pointPatchField< vector > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new calculatedPointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Member Functions inherited from Field< vector >
static const Field< vector > & null ()
Return a null field.
static tmp< Field< vector > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< vector >
static const List< vector > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes inherited from pointPatchField< vector >
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Static Public Attributes inherited from Field< vector >
static const char *const typeName
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< vector >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
Foam::angularOscillatingVelocityPointPatchVectorField.
Source files
angularOscillatingVelocityPointPatchVectorField.H
angularOscillatingVelocityPointPatchVectorField.C
Definition at line 48 of file angularOscillatingVelocityPointPatchVectorField.H.
Constructor & Destructor Documentation
angularOscillatingVelocityPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 41 of file angularOscillatingVelocityPointPatchVectorField.C.
Referenced by angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), and angularOscillatingVelocityPointPatchVectorField::clone().
angularOscillatingVelocityPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 58 of file angularOscillatingVelocityPointPatchVectorField.C.
References angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), dictionary::found(), and valuePointPatchField< Type >::size().
angularOscillatingVelocityPointPatchVectorField (const angularOscillatingVelocityPointPatchVectorField & ptf, const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Construct by mapping given patchField<vector> onto a new patch.
Definition at line 89 of file angularOscillatingVelocityPointPatchVectorField.C.
References angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField().
angularOscillatingVelocityPointPatchVectorField (const angularOscillatingVelocityPointPatchVectorField & ptf, const DimensionedField< vector, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 108 of file angularOscillatingVelocityPointPatchVectorField.C.
References angularOscillatingVelocityPointPatchVectorField::autoMap().
Member Function Documentation
TypeName ("angularOscillatingVelocity")
Runtime type information.
virtual autoPtr<pointPatchField<vector> > clone () const inline virtual
Construct and return a clone.
Reimplemented from fixedValuePointPatchField< vector >.
Definition at line 96 of file angularOscillatingVelocityPointPatchVectorField.H.
References angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField().
virtual autoPtr<pointPatchField<vector> > clone (const DimensionedField< vector, pointMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from fixedValuePointPatchField< vector >.
Definition at line 116 of file angularOscillatingVelocityPointPatchVectorField.H.
References angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), angularOscillatingVelocityPointPatchVectorField::autoMap(), angularOscillatingVelocityPointPatchVectorField::rmap(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), and angularOscillatingVelocityPointPatchVectorField::write().
void autoMap (const pointPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented from valuePointPatchField< vector >.
Definition at line 126 of file angularOscillatingVelocityPointPatchVectorField.C.
References valuePointPatchField< Type >::autoMap(), and angularOscillatingVelocityPointPatchVectorField::rmap().
Referenced by angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), and angularOscillatingVelocityPointPatchVectorField::clone().
void rmap (const pointPatchField< vector > & ptf, const labelList & addr) virtual
Reverse map the given pointPatchField onto this pointPatchField.
Reimplemented from valuePointPatchField< vector >.
Definition at line 137 of file angularOscillatingVelocityPointPatchVectorField.C.
References valuePointPatchField< Type >::rmap().
Referenced by angularOscillatingVelocityPointPatchVectorField::autoMap(), and angularOscillatingVelocityPointPatchVectorField::clone().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from valuePointPatchField< vector >.
Definition at line 151 of file angularOscillatingVelocityPointPatchVectorField.C.
References Foam::cos(), TimeState::deltaTValue(), pointPatchField< vector >::internalField(), pointPatch::localPoints(), Foam::mag(), mesh, Field< vector >::operator, pointPatchField< vector >::patch(), Foam::sin(), objectRegistry::time(), valuePointPatchField< Type >::updateCoeffs(), pointPatchField< vector >::updated(), dimensioned< Type >::value(), and angularOscillatingVelocityPointPatchVectorField::write().
Referenced by angularOscillatingVelocityPointPatchVectorField::clone().
void write (Ostream & os) const virtual
Write.
Reimplemented from valuePointPatchField< vector >.
Definition at line 182 of file angularOscillatingVelocityPointPatchVectorField.C.
References token::END_STATEMENT, Foam::makePointPatchTypeField(), Foam::nl, pointPatchField< Type >::write(), Field< vector >::writeEntry(), Field< Type >::writeEntry(), and Ostream::writeKeyword().
Referenced by angularOscillatingVelocityPointPatchVectorField::clone(), and angularOscillatingVelocityPointPatchVectorField::updateCoeffs().
The documentation for this class was generated from the following files:
src/fvMotionSolver/pointPatchFields/derived/angularOscillatingVelocity/angularOscillatingVelocityPointPatchVectorField.H
src/fvMotionSolver/pointPatchFields/derived/angularOscillatingVelocity/angularOscillatingVelocityPointPatchVectorField.C