OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
absorptionCoeffs Class Reference
Public Types
typedef FixedList< scalar, nCoeffs_ > coeffArray
Public Member Functions
absorptionCoeffs (Istream &)
Construct from Istream.
absorptionCoeffs ()
~absorptionCoeffs ()
Destructor.
const coeffArray & coeffs (const scalar T) const
Return the coefficients corresponding to the given temperature.
void initialise (const dictionary &)
void initialise (Istream &)
bool invTemp () const
scalar Tcommon () const
scalar Tlow () const
scalar Thigh () const
const coeffArray & highACoeffs () const
const coeffArray & lowACoeffs () const
Static Public Attributes
static const int nCoeffs_ = 6
Detailed Description
Definition at line 52 of file absorptionCoeffs.H.
Member Typedef Documentation
typedef FixedList<scalar, nCoeffs_> coeffArray
Definition at line 59 of file absorptionCoeffs.H.
Constructor & Destructor Documentation
absorptionCoeffs (Istream & is)
Construct from Istream.
Definition at line 31 of file absorptionCoeffs.C.
References absorptionCoeffs::nCoeffs_.
absorptionCoeffs () inline
Definition at line 96 of file absorptionCoeffs.H.
References absorptionCoeffs::coeffs(), absorptionCoeffs::highACoeffs(), absorptionCoeffs::initialise(), absorptionCoeffs::invTemp(), absorptionCoeffs::lowACoeffs(), Foam::T(), absorptionCoeffs::Tcommon(), absorptionCoeffs::Thigh(), absorptionCoeffs::Tlow(), and absorptionCoeffs::~absorptionCoeffs().
Referenced by absorptionCoeffs::initialise().
~absorptionCoeffs ()
Destructor.
Definition at line 52 of file absorptionCoeffs.C.
References absorptionCoeffs::coeffs(), Foam::endl(), Foam::nl, Foam::T(), and WarningInFunction.
Referenced by absorptionCoeffs::absorptionCoeffs().
Member Function Documentation
const Foam::radiation::absorptionCoeffs::coeffArray & coeffs (const scalar T) const
Return the coefficients corresponding to the given temperature.
Definition at line 72 of file absorptionCoeffs.C.
Referenced by absorptionCoeffs::absorptionCoeffs(), and absorptionCoeffs::~absorptionCoeffs().
void initialise (const dictionary & dict)
Definition at line 95 of file absorptionCoeffs.C.
References dictionary::lookup().
Referenced by absorptionCoeffs::absorptionCoeffs().
void initialise (Istream &)
Definition at line 89 of file absorptionCoeffs.C.
References absorptionCoeffs::absorptionCoeffs().
bool invTemp () const inline
Definition at line 26 of file absorptionCoeffsI.H.
Referenced by absorptionCoeffs::absorptionCoeffs().
Foam::scalar Tcommon () const inline
Definition at line 32 of file absorptionCoeffsI.H.
Referenced by absorptionCoeffs::absorptionCoeffs().
Foam::scalar Tlow () const inline
Definition at line 38 of file absorptionCoeffsI.H.
Referenced by absorptionCoeffs::absorptionCoeffs().
Foam::scalar Thigh () const inline
Definition at line 44 of file absorptionCoeffsI.H.
Referenced by absorptionCoeffs::absorptionCoeffs().
const Foam::radiation::absorptionCoeffs::coeffArray & highACoeffs () const inline
Definition at line 51 of file absorptionCoeffsI.H.
Referenced by absorptionCoeffs::absorptionCoeffs().
const Foam::radiation::absorptionCoeffs::coeffArray & lowACoeffs () const inline
Definition at line 58 of file absorptionCoeffsI.H.
Referenced by absorptionCoeffs::absorptionCoeffs().
Member Data Documentation
const int nCoeffs_ = 6 static
Definition at line 58 of file absorptionCoeffs.H.
Referenced by absorptionCoeffs::absorptionCoeffs().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/radiationModels/fvDOM/absorptionCoeffs/absorptionCoeffs.H
src/thermophysicalModels/radiation/radiationModels/fvDOM/absorptionCoeffs/absorptionCoeffs.C
src/thermophysicalModels/radiation/radiationModels/fvDOM/absorptionCoeffs/absorptionCoeffsI.H