OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
abort Class Reference
FunctionObjects » Utility function objects
Watches for presence of the named file in the $FOAM_CASE directory and aborts the calculation if it is present.
Public Types
enum actionType { noWriteNow, writeNow, nextWrite }
Enumeration defining the type of action.
Public Member Functions
TypeName ("abort")
Runtime type information.
abort (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFilesUnused=false)
Construct for given objectRegistry and dictionary.
virtual ~abort ()
Destructor.
virtual const word & name () const
Return name of the abort file.
virtual void read (const dictionary &)
Read the dictionary settings.
virtual void execute ()
Execute, check existence of abort file and take action.
virtual void end ()
Execute at the final time-loop, used for cleanup.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Execute, check existence of abort file and take action.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh - does nothing.
virtual void movePoints (const polyMesh &)
Update for changes of mesh - does nothing.
Detailed Description
Watches for presence of the named file in the $FOAM_CASE directory and aborts the calculation if it is present.
Currently the following action types are supported:
noWriteNow
writeNow
nextWrite
Source files
abort.H
abort.C
Definition at line 66 of file abort.H.
Member Enumeration Documentation
enum actionType
Enumeration defining the type of action.
Enumerator
noWriteNow
stop immediately without writing data
writeNow
write data and stop immediately
nextWrite
stop the next time data are written
Definition at line 73 of file abort.H.
Constructor & Destructor Documentation
abort (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFilesUnused = false)
Construct for given objectRegistry and dictionary.
Definition at line 80 of file abort.C.
References Foam::read().
~abort () virtual
Destructor.
Definition at line 102 of file abort.C.
Member Function Documentation
TypeName ("abort")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the abort file.
Definition at line 136 of file abort.H.
References abort::end(), abort::execute(), abort::read(), abort::timeSet(), and abort::write().
void read (const dictionary & dict) virtual
Read the dictionary settings.
Definition at line 108 of file abort.C.
References dictionary::found(), dictionary::lookup(), and dictionary::readIfPresent().
Referenced by abort::name().
void execute () virtual
Execute, check existence of abort file and take action.
Definition at line 126 of file abort.C.
References Foam::endl(), Foam::Info, Foam::isFile(), Foam::reduce(), Time::saNextWrite, Time::saNoWriteNow, and Time::saWriteNow.
Referenced by abort::name().
void end () virtual
Execute at the final time-loop, used for cleanup.
Definition at line 175 of file abort.C.
Referenced by abort::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 181 of file abort.C.
Referenced by abort::name().
void write () virtual
Execute, check existence of abort file and take action.
Definition at line 185 of file abort.C.
Referenced by abort::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh - does nothing.
Definition at line 157 of file abort.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh - does nothing.
Definition at line 161 of file abort.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/abort/abort.H
src/postProcessing/functionObjects/utilities/abort/abort.C