OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
backwardDdtScheme< Type > Class Template Reference
Second-order backward-differencing ddt using the current and two previous time-step values.
Public Types
typedef ddtScheme< Type >::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("backward")
Runtime type information.
backwardDdtScheme (const fvMesh &mesh)
Construct from mesh.
backwardDdtScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
Construct from mesh.
ddtScheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~ddtScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new ddtScheme created on freestore.
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)
Disallow copy construct.
void operator= (const ddtScheme &)
Disallow default bitwise assignment.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::backwardDdtScheme< Type >
Second-order backward-differencing ddt using the current and two previous time-step values.
Source files
backwardDdtScheme.H
backwardDdtScheme.C
Definition at line 55 of file backwardDdtScheme.H.
Member Typedef Documentation
typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 161 of file backwardDdtScheme.H.
Constructor & Destructor Documentation
backwardDdtScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 88 of file backwardDdtScheme.H.
backwardDdtScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 94 of file backwardDdtScheme.H.
Member Function Documentation
TypeName ("backward")
Runtime type information.
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 103 of file backwardDdtScheme.H.
References Foam::constant::atomic::alpha, backwardDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvmDdt(), ddtScheme< Type >::mesh(), psi, and rho.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 77 of file backwardDdtScheme.C.
References dimensioned< Type >::dimensions(), Foam::dimTime, mesh, dimensioned< Type >::name(), tmp< T >::ref(), dimensioned< Type >::value(), and Foam::Zero.
Referenced by backwardDdtScheme< Type >::fvcDdt(), and backwardDdtScheme< Type >::mesh().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 145 of file backwardDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), backwardDdtScheme< Type >::fvcDdt(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and dimensioned< Type >::value().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 216 of file backwardDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), backwardDdtScheme< Type >::fvcDdt(), mesh, dimensioned< Type >::name(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and dimensioned< Type >::value().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 288 of file backwardDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), backwardDdtScheme< Type >::fvcDdt(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and dimensioned< Type >::value().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 363 of file backwardDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), backwardDdtScheme< Type >::fvmDdt(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and dimensioned< Type >::value().
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 457 of file backwardDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), tmp< T >::ref(), and fvMatrix< Type >::source().
Referenced by backwardDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvmDdt(), and backwardDdtScheme< Type >::mesh().
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 508 of file backwardDdtScheme.C.
References lduMatrix::diag(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, backwardDdtScheme< Type >::fvmDdt(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), tmp< T >::ref(), fvMatrix< Type >::source(), and dimensioned< Type >::value().
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 559 of file backwardDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, backwardDdtScheme< Type >::fvmDdt(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), tmp< T >::ref(), and fvMatrix< Type >::source().
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 613 of file backwardDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, backwardDdtScheme< Type >::fvcDdtUfCorr(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), tmp< T >::ref(), and fvMatrix< Type >::source().
tmp< typename backwardDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 679 of file backwardDdtScheme.C.
References backwardDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
Referenced by backwardDdtScheme< Type >::fvcDdtPhiCorr(), and backwardDdtScheme< Type >::fvmDdt().
tmp< typename backwardDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 723 of file backwardDdtScheme.C.
References Foam::fvc::dotInterpolate(), backwardDdtScheme< Type >::fvcDdtUfCorr(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
Referenced by backwardDdtScheme< Type >::fvcDdtUfCorr().
tmp< typename backwardDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 765 of file backwardDdtScheme.C.
References Foam::abort(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::FatalError, FatalErrorInFunction, backwardDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< typename backwardDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 841 of file backwardDdtScheme.C.
References Foam::abort(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::fvc::dotInterpolate(), Foam::FatalError, FatalErrorInFunction, mesh, backwardDdtScheme< Type >::meshPhi(), IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 917 of file backwardDdtScheme.C.
References mesh, Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, oldTime(), phi, and timeName.
Referenced by backwardDdtScheme< Type >::fvcDdtPhiCorr().
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/backwardDdtScheme/backwardDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/backwardDdtScheme/backwardDdtScheme.C