OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphatJayatillekeWallFunctionFvPatchScalarField Class Reference
Incompressible turbulence wall functions
This boundary condition provides a kinematic turbulent thermal conductivity for using wall functions, using the Jayatilleke 'P' function.
Public Member Functions
TypeName ("alphatJayatillekeWallFunction")
Runtime type information.
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Member Functions
virtual void checkType ()
Check the type of the patch.
scalar Psmooth (const scalar Prat) const
`P' function
scalar yPlusTherm (const scalar P, const scalar Prat) const
Calculate y+ at the edge of the thermal laminar sublayer.
Protected Attributes
scalar Prt_
Turbulent Prandtl number.
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
Static Protected Attributes
static scalar tolerance_ = 0.01
static label maxIters_ = 10
Detailed Description
This boundary condition provides a kinematic turbulent thermal conductivity for using wall functions, using the Jayatilleke 'P' function.
Patch usage
Property Description Required Default value
Prt turbulent Prandtl number no 0.85
Cmu model coefficient no 0.09
kappa Von Karman constant no 0.41
E model coefficient no 9.8
Example of the boundary condition specification:
    myPatch
    {
        type            alphatJayatillekeWallFunction;
    }
Note
The units of kinematic turbulent thermal conductivity are [m2/s]
See Also
Foam::fixedValueFvPatchField
Source files
alphatJayatillekeWallFunctionFvPatchScalarField.H
alphatJayatillekeWallFunctionFvPatchScalarField.C
Definition at line 103 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 108 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 144 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
alphatJayatillekeWallFunctionFvPatchScalarField onto a new patch
Definition at line 125 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 162 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 178 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
Member Function Documentation
void checkType () protected virtual
Check the type of the patch.
Definition at line 47 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, and Foam::nl.
scalar Psmooth (const scalar Prat) const protected
`P' function
Definition at line 64 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::exp(), and Foam::pow().
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
scalar yPlusTherm (const scalar P, const scalar Prat) const protected
Calculate y+ at the edge of the thermal laminar sublayer.
Definition at line 73 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References f(), i, Foam::log(), and Foam::mag().
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
TypeName ("alphatJayatillekeWallFunction")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 187 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 204 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 195 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), alphatJayatillekeWallFunctionFvPatchScalarField::Cmu_, dimensionedInternalField(), alphatJayatillekeWallFunctionFvPatchScalarField::E_, forAll, Foam::constant::atomic::group, IOobject::groupName(), k, turbulenceModel::k(), alphatJayatillekeWallFunctionFvPatchScalarField::kappa_, Foam::log(), dictionary::lookup(), Foam::max(), TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::nu(), nu, patchi, Foam::pow(), Pr(), turbulenceModel::propertiesName, alphatJayatillekeWallFunctionFvPatchScalarField::Prt_, alphatJayatillekeWallFunctionFvPatchScalarField::Psmooth(), Foam::sqrt(), transportProperties(), fvPatchField< Type >::updateCoeffs(), value(), y, turbulenceModel::y(), yPlus, and alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
void write (Ostream & os) const virtual
Write.
Definition at line 265 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::Cmu_, alphatJayatillekeWallFunctionFvPatchScalarField::E_, token::END_STATEMENT, alphatJayatillekeWallFunctionFvPatchScalarField::kappa_, Foam::nl, alphatJayatillekeWallFunctionFvPatchScalarField::Prt_, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Member Data Documentation
scalar Prt_ protected
Turbulent Prandtl number.
Definition at line 112 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::write().
scalar Cmu_ protected
Cmu coefficient.
Definition at line 115 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::write().
scalar kappa_ protected
Von Karman constant.
Definition at line 118 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::write().
scalar E_ protected
E coefficient.
Definition at line 121 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::write().
scalar tolerance_ = 0.01 static protected
Definition at line 126 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
label maxIters_ = 10 static protected
Definition at line 127 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.H
src/TurbulenceModels/incompressible/turbulentTransportModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.C