OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CaCO3 Class Reference
Calcium carbonate (limestone)
Public Member Functions
TypeName ("CaCO3")
Runtime type information.
CaCO3 ()
Construct null.
CaCO3 (const solidProperties &s)
Construct from solidProperties.
CaCO3 (Istream &is)
Construct from Istream.
CaCO3 (const dictionary &dict)
Construct from dictionary.
CaCO3 (const CaCO3 &s)
Construct copy.
virtual autoPtr< solidProperties > clone () const
Construct and return clone.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from solidProperties
TypeName ("solidProperties")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, solidProperties, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, solidProperties, dictionary,(const dictionary &dict),(dict))
solidProperties (scalar rho, scalar Cp, scalar K, scalar Hf, scalar emissivity)
Construct from components.
solidProperties (Istream &is)
Construct from Istream.
solidProperties (const dictionary &dict)
Construct from dictionary.
solidProperties (const solidProperties &s)
Construct copy.
virtual ~solidProperties ()
Destructor.
scalar rho () const
Density [kg/m3].
scalar Cp () const
Specific heat capacity [J/(kg.K)].
scalar K () const
Thermal conductivity [W/(m.K)].
scalar Hf () const
Heat of formation [J/kg].
scalar Hs (const scalar T) const
Sensible enthalpy - reference to Tstd [J/kg].
scalar emissivity () const
Emissivity [].
Friends
Ostream & operator<< (Ostream &os, const CaCO3 &s)
Additional Inherited Members
Static Public Member Functions inherited from solidProperties
static autoPtr< solidProperties > New (Istream &is)
Return a pointer to a new solidProperties created from input.
static autoPtr< solidProperties > New (const dictionary &dict)
Return a pointer to a new solidProperties created from dictionary.
Detailed Description
Calcium carbonate (limestone)
Source files
CaCO3.H
CaCO3.C
Definition at line 57 of file CaCO3.H.
Constructor & Destructor Documentation
CaCO3 ()
Construct null.
Definition at line 41 of file CaCO3.C.
References Foam::endl(), and WarningInFunction.
Referenced by CaCO3::clone().
CaCO3 (const solidProperties & s)
Construct from solidProperties.
Definition at line 54 of file CaCO3.C.
CaCO3 (Istream & is)
Construct from Istream.
Definition at line 60 of file CaCO3.C.
CaCO3 (const dictionary & dict)
Construct from dictionary.
Definition at line 66 of file CaCO3.C.
CaCO3 (const CaCO3 & s)
Construct copy.
Definition at line 72 of file CaCO3.C.
Member Function Documentation
TypeName ("CaCO3")
Runtime type information.
virtual autoPtr<solidProperties> clone () const inline virtual
Construct and return clone.
Reimplemented from solidProperties.
Definition at line 86 of file CaCO3.H.
References CaCO3::CaCO3(), CaCO3::operator<<, and CaCO3::writeData().
void writeData (Ostream & os) const virtual
Write the function coefficients.
Reimplemented from solidProperties.
Definition at line 80 of file CaCO3.C.
References solidProperties::writeData().
Referenced by CaCO3::clone(), and Foam::operator<<().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const CaCO3 & s) friend
Referenced by CaCO3::clone().
The documentation for this class was generated from the following files:
src/thermophysicalModels/properties/solidProperties/CaCO3/CaCO3.H
src/thermophysicalModels/properties/solidProperties/CaCO3/CaCO3.C