OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
BreakupModel< CloudType > Class Template Reference abstract
Templated break-up model class.
Public Member Functions
TypeName ("breakupModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, BreakupModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
BreakupModel (CloudType &owner)
Construct null from owner.
BreakupModel (const dictionary &dict, CloudType &owner, const word &type, bool solveOscillationEq=false)
Construct from dictionary.
BreakupModel (const BreakupModel< CloudType > &bum)
Construct copy.
virtual autoPtr< BreakupModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~BreakupModel ()
Destructor.
const Switch & solveOscillationEq () const
const scalar & y0 () const
const scalar & yDot0 () const
const scalar & TABComega () const
const scalar & TABCmu () const
const scalar & TABtwoWeCrit () const
virtual bool update (const scalar dt, const vector &g, scalar &d, scalar &tc, scalar &ms, scalar &nParticle, scalar &KHindex, scalar &y, scalar &yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector &U, const scalar rhoc, const scalar muc, const vector &Urel, const scalar Urmag, const scalar tMom, scalar &dChild, scalar &massChild)=0
Update the parcel properties and return true if a child parcel.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< BreakupModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Attributes
Switch solveOscillationEq_
scalar y0_
scalar yDot0_
scalar TABComega_
scalar TABCmu_
scalar TABtwoWeCrit_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Detailed Description
template<class CloudType>
class Foam::BreakupModel< CloudType >
Templated break-up model class.
Source files
BreakupModel.H
BreakupModel.C
BreakupModelNew.C
Definition at line 50 of file SprayCloud.H.
Constructor & Destructor Documentation
BreakupModel (CloudType & owner)
Construct null from owner.
Definition at line 32 of file BreakupModel.C.
Referenced by BreakupModel< CloudType >::BreakupModel().
BreakupModel (const dictionary & dict, CloudType & owner, const word & type, bool solveOscillationEq = false)
Construct from dictionary.
Definition at line 64 of file BreakupModel.C.
References dictionary::lookup(), and readScalar.
BreakupModel (const BreakupModel< CloudType > & bum)
Construct copy.
Definition at line 48 of file BreakupModel.C.
References BreakupModel< CloudType >::BreakupModel().
~BreakupModel () virtual
Destructor.
Definition at line 93 of file BreakupModel.C.
Member Function Documentation
TypeName ("breakupModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , BreakupModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
virtual autoPtr<BreakupModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in SHF< CloudType >, TAB< CloudType >, PilchErdman< CloudType >, ETAB< CloudType >, ReitzDiwakar< CloudType >, ReitzKHRT< CloudType >, and NoBreakup< CloudType >.
Foam::autoPtr< Foam::BreakupModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file BreakupModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
const Switch& solveOscillationEq () const inline
Definition at line 125 of file BreakupModel.H.
const scalar& y0 () const inline
Definition at line 130 of file BreakupModel.H.
const scalar& yDot0 () const inline
Definition at line 135 of file BreakupModel.H.
const scalar& TABComega () const inline
Definition at line 140 of file BreakupModel.H.
const scalar& TABCmu () const inline
Definition at line 145 of file BreakupModel.H.
const scalar& TABtwoWeCrit () const inline
Definition at line 150 of file BreakupModel.H.
virtual bool update (const scalar dt, const vector & g, scalar & d, scalar & tc, scalar & ms, scalar & nParticle, scalar & KHindex, scalar & y, scalar & yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector & U, const scalar rhoc, const scalar muc, const vector & Urel, const scalar Urmag, const scalar tMom, scalar & dChild, scalar & massChild) pure virtual
Update the parcel properties and return true if a child parcel.
should be added
Implemented in SHF< CloudType >, TAB< CloudType >, PilchErdman< CloudType >, ETAB< CloudType >, ReitzDiwakar< CloudType >, ReitzKHRT< CloudType >, and NoBreakup< CloudType >.
Referenced by BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::TABtwoWeCrit().
Member Data Documentation
Switch solveOscillationEq_ protected
Definition at line 61 of file BreakupModel.H.
Referenced by BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::solveOscillationEq().
scalar y0_ protected
Definition at line 63 of file BreakupModel.H.
Referenced by BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::y0().
scalar yDot0_ protected
Definition at line 64 of file BreakupModel.H.
Referenced by BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::yDot0().
scalar TABComega_ protected
Definition at line 66 of file BreakupModel.H.
Referenced by BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::TABComega(), ETAB< CloudType >::update(), and TAB< CloudType >::update().
scalar TABCmu_ protected
Definition at line 67 of file BreakupModel.H.
Referenced by BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::TABCmu(), ETAB< CloudType >::update(), and TAB< CloudType >::update().
scalar TABtwoWeCrit_ protected
Definition at line 68 of file BreakupModel.H.
Referenced by BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::TABtwoWeCrit(), ETAB< CloudType >::update(), and TAB< CloudType >::update().
The documentation for this class was generated from the following files:
src/lagrangian/spray/clouds/Templates/SprayCloud/SprayCloud.H
src/lagrangian/spray/submodels/BreakupModel/BreakupModel/BreakupModel.H
src/lagrangian/spray/submodels/BreakupModel/BreakupModel/BreakupModel.C
src/lagrangian/spray/submodels/BreakupModel/BreakupModel/BreakupModelNew.C