OpenFOAM: basicSpecieMixture Class Reference
basicSpecieMixture Class Reference abstract
Specialization of basicMultiComponentMixture for a mixture consisting of a number for molecular species.
Public Types
typedef basicSpecieMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Member Functions
TypeName ("basicSpecieMixture")
Run time type information.
basicSpecieMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicSpecieMixture ()
Destructor.
virtual scalar nMoles (const label speciei) const =0
Number of moles of the given specie [].
virtual scalar W (const label speciei) const =0
Molecular weight of the given specie [kg/kmol].
tmp< volScalarField > W () const
Molecular weight of the mixture [kg/kmol].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar Hc (const label speciei) const =0
Chemical enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
Density [kg/m3].
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
bool contains (const word &specieName) const
Does the mixture include this specie?
bool active (label speciei) const
Return true for active species.
const List< bool > & active () const
Return the bool list of active species.
void setActive (label speciei)
Set speciei active.
void setInactive (label speciei)
Set speciei inactive.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
Table of specie names.
List< bool > active_
List of specie active flags.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
Specialization of basicMultiComponentMixture for a mixture consisting of a number for molecular species.
Source files
basicSpecieMixture.H
basicSpecieMixture.C
Definition at line 49 of file basicSpecieMixture.H.
Member Typedef Documentation
typedef basicSpecieMixture basicMixtureType
The base class of the mixture.
Definition at line 60 of file basicSpecieMixture.H.
Constructor & Destructor Documentation
basicSpecieMixture (const dictionary & thermoDict, const wordList & specieNames, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, species names, mesh and phase name.
Definition at line 39 of file basicSpecieMixture.C.
virtual ~basicSpecieMixture () inline virtual
Destructor.
Definition at line 76 of file basicSpecieMixture.H.
References basicSpecieMixture::A(), basicSpecieMixture::alphah(), basicSpecieMixture::Cp(), basicSpecieMixture::Cv(), basicSpecieMixture::Es(), basicSpecieMixture::G(), basicSpecieMixture::Ha(), basicSpecieMixture::Hc(), basicSpecieMixture::Hs(), basicSpecieMixture::kappa(), basicSpecieMixture::mu(), basicSpecieMixture::nMoles(), p, basicSpecieMixture::rho(), basicSpecieMixture::S(), Foam::T(), and basicSpecieMixture::W().
Member Function Documentation
TypeName ("basicSpecieMixture")
Run time type information.
virtual scalar nMoles (const label speciei) const pure virtual
Number of moles of the given specie [].
Referenced by basicSpecieMixture::~basicSpecieMixture().
virtual scalar W (const label speciei) const pure virtual
Molecular weight of the given specie [kg/kmol].
Referenced by greyMeanAbsorptionEmission::aCont(), ReactingParcel< ParcelType >::correctSurfaceValues(), and CompositionModel< CloudType >::X().
Foam::tmp< Foam::volScalarField > W () const
Molecular weight of the mixture [kg/kmol].
Definition at line 52 of file basicSpecieMixture.C.
References Foam::dimless, forAll, Foam::constant::atomic::group, IOobject::groupName(), mesh, tmp< T >::ref(), timeName, Y, and basicMultiComponentMixture::Y().
Referenced by basicSpecieMixture::~basicSpecieMixture().
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const pure virtual
Heat capacity at constant pressure [J/(kg K)].
Referenced by ReactingParcel< ParcelType >::correctSurfaceValues(), CompositionModel< CloudType >::Cp(), and basicSpecieMixture::~basicSpecieMixture().
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const pure virtual
Heat capacity at constant volume [J/(kg K)].
Referenced by basicSpecieMixture::~basicSpecieMixture().
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const pure virtual
Absolute enthalpy [J/kg].
Referenced by CompositionModel< CloudType >::H(), and basicSpecieMixture::~basicSpecieMixture().
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const pure virtual
Sensible enthalpy [J/kg].
Referenced by CompositionModel< CloudType >::Hs(), and basicSpecieMixture::~basicSpecieMixture().
virtual scalar Hc (const label speciei) const pure virtual
Chemical enthalpy [J/kg].
Referenced by CompositionModel< CloudType >::Hc(), and basicSpecieMixture::~basicSpecieMixture().
virtual scalar S (const label speciei, const scalar p, const scalar T) const pure virtual
Entropy [J/(kg K)].
Referenced by basicSpecieMixture::~basicSpecieMixture().
virtual scalar Es (const label speciei, const scalar p, const scalar T) const pure virtual
Sensible internal energy [J/kg].
Referenced by basicSpecieMixture::~basicSpecieMixture().
virtual scalar G (const label speciei, const scalar p, const scalar T) const pure virtual
Gibbs free energy [J/kg].
Referenced by basicSpecieMixture::~basicSpecieMixture().
virtual scalar A (const label speciei, const scalar p, const scalar T) const pure virtual
Helmholtz free energy [J/kg].
Referenced by basicSpecieMixture::~basicSpecieMixture().
virtual scalar mu (const label speciei, const scalar p, const scalar T) const pure virtual
Dynamic viscosity [kg/m/s].
Referenced by ReactingParcel< ParcelType >::correctSurfaceValues(), and basicSpecieMixture::~basicSpecieMixture().
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const pure virtual
Thermal conductivity [W/m/K].
Referenced by ReactingParcel< ParcelType >::correctSurfaceValues(), and basicSpecieMixture::~basicSpecieMixture().
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const pure virtual
Thermal diffusivity of enthalpy [kg/m/s].
Referenced by basicSpecieMixture::~basicSpecieMixture().
virtual scalar rho (const label speciei, const scalar p, const scalar T) const pure virtual
Density [kg/m3].
Referenced by basicSpecieMixture::~basicSpecieMixture().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/basicSpecieMixture/basicSpecieMixture.H
src/thermophysicalModels/reactionThermo/mixtures/basicSpecieMixture/basicSpecieMixture.C