OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
basicMultiComponentMixture Class Reference
Multi-component mixture.
Public Types
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Member Functions
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
bool contains (const word &specieName) const
Does the mixture include this specie?
Protected Attributes
speciesTable species_
Table of specie names.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
Multi-component mixture.
Provides a list of mass fraction fields and helper functions to query mixture composition.
Source files
basicMultiComponentMixture.H
basicMultiComponentMixture.C
Definition at line 54 of file basicMultiComponentMixture.H.
Member Typedef Documentation
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Definition at line 75 of file basicMultiComponentMixture.H.
Constructor & Destructor Documentation
basicMultiComponentMixture (const dictionary & thermoDict, const wordList & specieNames, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, species names, mesh and phase name.
Definition at line 39 of file basicMultiComponentMixture.C.
References IOobject::AUTO_WRITE, forAll, IOobject::groupName(), mesh, IOobject::MUST_READ, IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), and Time::timeName().
virtual ~basicMultiComponentMixture () inline virtual
Destructor.
Definition at line 91 of file basicMultiComponentMixture.H.
References basicMultiComponentMixture::contains(), basicMultiComponentMixture::species(), and basicMultiComponentMixture::Y().
Member Function Documentation
TypeName ("basicMultiComponentMixture")
Run time type information.
const Foam::speciesTable & species () const inline
Return the table of species.
Definition at line 27 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::species_.
Referenced by greyMeanAbsorptionEmission::aCont(), SLGThermo::carrierId(), CompositionModel< CloudType >::carrierId(), ReactingParcel< ParcelType >::correctSurfaceValues(), ReactingCloud< CloudType >::ReactingCloud(), SLGThermo::SLGThermo(), thermoSingleLayer::thermoSingleLayer(), and basicMultiComponentMixture::~basicMultiComponentMixture().
Foam::PtrList< Foam::volScalarField > & Y () inline
Return the mass-fraction fields.
Definition at line 34 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y_.
Referenced by greyMeanAbsorptionEmission::aCont(), COxidationDiffusionLimitedRate< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), ReactingParcel< ParcelType >::correctSurfaceValues(), basicSpecieMixture::W(), basicMultiComponentMixture::Y(), and basicMultiComponentMixture::~basicMultiComponentMixture().
const Foam::PtrList< Foam::volScalarField > & Y () const inline
Return the const mass-fraction fields.
Definition at line 41 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y_.
Foam::volScalarField & Y (const label i) inline
Return the mass-fraction field for a specie given by index.
Definition at line 47 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y(), and basicMultiComponentMixture::Y_.
const Foam::volScalarField & Y (const label i) const inline
Return the const mass-fraction field for a specie given by index.
Definition at line 54 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y(), and basicMultiComponentMixture::Y_.
Foam::volScalarField & Y (const word & specieName) inline
Return the mass-fraction field for a specie given by name.
Definition at line 63 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::species_, basicMultiComponentMixture::Y(), and basicMultiComponentMixture::Y_.
const Foam::volScalarField & Y (const word & specieName) const inline
Return the const mass-fraction field for a specie given by name.
Definition at line 72 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::contains(), basicMultiComponentMixture::species_, and basicMultiComponentMixture::Y_.
bool contains (const word & specieName) const inline
Does the mixture include this specie?
Definition at line 81 of file basicMultiComponentMixtureI.H.
References hashedWordList::contains(), and basicMultiComponentMixture::species_.
Referenced by basicMultiComponentMixture::Y(), and basicMultiComponentMixture::~basicMultiComponentMixture().
Member Data Documentation
speciesTable species_ protected
Table of specie names.
Definition at line 62 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::contains(), basicMultiComponentMixture::species(), and basicMultiComponentMixture::Y().
PtrList<volScalarField> Y_ protected
Species mass fractions.
Definition at line 65 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::Y().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.H
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.C
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixtureI.H