OpenFOAM: blended< Type > Class Template Reference
blended< Type > Class Template Reference
linear/upwind blended differencing scheme.
Public Member Functions
TypeName ("blended")
Runtime type information.
blended (const fvMesh &mesh, const surfaceScalarField &faceFlux, const scalar blendingFactor)
Construct from mesh, faceFlux and blendingFactor.
blended (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
blended (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from mesh, faceFlux and Istream.
virtual ~blended ()
Destructor.
virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-based blending factor.
virtual tmp< surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation limiter.
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the interpolation weighting factors.
Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
TypeName ("limitedSurfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
limitedSurfaceInterpolationScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from mesh and faceFlux.
limitedSurfaceInterpolationScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual ~limitedSurfaceInterpolationScheme ()
Destructor.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &, const surfaceScalarField &CDweights, tmp< surfaceScalarField > tLimiter) const
Return the interpolation weighting factors for the given field,.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from blendedSchemeBase< Type >
blendedSchemeBase ()
Constructor.
virtual ~blendedSchemeBase ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes inherited from limitedSurfaceInterpolationScheme< Type >
const surfaceScalarField & faceFlux_
Detailed Description
template<class Type>
class Foam::blended< Type >
linear/upwind blended differencing scheme.
Source files
blended.H
blended.C
Definition at line 50 of file blended.H.
Constructor & Destructor Documentation
blended (const fvMesh & mesh, const surfaceScalarField & faceFlux, const scalar blendingFactor) inline
Construct from mesh, faceFlux and blendingFactor.
Definition at line 79 of file blended.H.
blended (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 93 of file blended.H.
blended (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from mesh, faceFlux and Istream.
Definition at line 104 of file blended.H.
virtual ~blended () inline virtual
Destructor.
Definition at line 116 of file blended.H.
References blended< Type >::blendingFactor().
Member Function Documentation
TypeName ("blended< Type >")
Runtime type information.
virtual tmp<surfaceScalarField> blendingFactor (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the face-based blending factor.
Implements blendedSchemeBase< Type >.
Definition at line 124 of file blended.H.
References Foam::dimless, blended< Type >::limiter(), surfaceInterpolationScheme< Type >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), and Time::timeName().
Referenced by blended< Type >::~blended().
virtual tmp<surfaceScalarField> limiter (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation limiter.
Implements limitedSurfaceInterpolationScheme< Type >.
Definition at line 154 of file blended.H.
References Foam::dimless, surfaceInterpolationScheme< Type >::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, timeName, and blended< Type >::weights().
Referenced by blended< Type >::blendingFactor().
virtual tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the interpolation weighting factors.
Reimplemented from limitedSurfaceInterpolationScheme< Type >.
Definition at line 184 of file blended.H.
References limitedSurfaceInterpolationScheme< Type >::faceFlux_, surfaceInterpolationScheme< Type >::mesh(), and Foam::pos().
Referenced by blended< Type >::limiter().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/blended/blended.H