OpenFOAM: BSplineEdge Class Reference
BSplineEdge Class Reference
A curvedEdge interface for B-splines.
Public Member Functions
TypeName ("BSpline")
Runtime type information.
BSplineEdge (const pointField &, const label start, const label end, const pointField &internalPoints)
Construct from components.
BSplineEdge (const pointField &, Istream &)
Construct from Istream, setting pointsList.
virtual ~BSplineEdge ()
Destructor.
virtual point position (const scalar) const
Return the point position corresponding to the curve parameter.
virtual scalar length () const
Return the length of the spline curve (not implemented)
Public Member Functions inherited from curvedEdge
TypeName ("curvedEdge")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, curvedEdge, Istream,(const pointField &points, Istream &is),(points, is))
curvedEdge (const pointField &points, const label start, const label end)
Construct from components.
curvedEdge (const pointField &, Istream &)
Construct from Istream setting pointsList.
curvedEdge (const curvedEdge &)
Copy construct.
virtual autoPtr< curvedEdge > clone () const
Clone function.
virtual ~curvedEdge ()
Destructor.
label start () const
Return label of start point.
label end () const
Return label of end point.
int compare (const curvedEdge &) const
Compare the given start and end points with this curve.
int compare (const edge &) const
Compare the given start and end points with this curve.
int compare (const label start, const label end) const
Compare the given start and end points with this curve.
void operator= (const curvedEdge &)
Public Member Functions inherited from BSpline
BSpline (const pointField &knots, const bool notImplementedClosed=false)
Construct from components.
point position (const scalar lambda) const
Return the point position corresponding to the curve parameter.
point position (const label segment, const scalar lambda) const
Return the point position corresponding to the local parameter.
scalar length () const
Return the length of the curve.
Public Member Functions inherited from polyLine
polyLine (const pointField &, const bool notImplementedClosed=false)
Construct from components.
const pointField & points () const
Return const-access to the control-points.
label nSegments () const
Return the number of line segments.
point position (const scalar) const
Return the point position corresponding to the curve parameter.
point position (const label segment, const scalar) const
Return the point position corresponding to the local parameter.
scalar length () const
Return the length of the curve.
Additional Inherited Members
Static Public Member Functions inherited from curvedEdge
static autoPtr< curvedEdge > New (const pointField &, Istream &)
New function which constructs and returns pointer to a curvedEdge.
Protected Member Functions inherited from polyLine
void calcParam ()
Precalculate the rational cumulative parameter value.
label localParameter (scalar &lambda) const
Return the line segment and the local parameter [0..1].
Static Protected Member Functions inherited from curvedEdge
static pointField appendEndPoints (const pointField &, const label start, const label end, const pointField &otherKnots)
Return a complete point field by appending the start/end points.
Protected Attributes inherited from curvedEdge
const pointField & points_
const label start_
const label end_
Protected Attributes inherited from polyLine
pointField points_
The control points or ends of each segments.
scalar lineLength_
The real line length.
scalarList param_
The rational (0-1) cumulative parameter value for each point.
Detailed Description
A curvedEdge interface for B-splines.
Source files
BSplineEdge.H
BSplineEdge.C
Definition at line 49 of file BSplineEdge.H.
Constructor & Destructor Documentation
BSplineEdge (const pointField & points, const label start, const label end, const pointField & internalPoints)
Construct from components.
Definition at line 48 of file BSplineEdge.C.
BSplineEdge (const pointField & points, Istream & is)
Construct from Istream, setting pointsList.
Definition at line 60 of file BSplineEdge.C.
References token::BEGIN_LIST, and Istream::putBack().
~BSplineEdge () virtual
Destructor.
Definition at line 79 of file BSplineEdge.C.
Member Function Documentation
TypeName ("BSpline")
Runtime type information.
Foam::point position (const scalar mu) const virtual
Return the point position corresponding to the curve parameter.
0 <= lambda <= 1
Implements curvedEdge.
Definition at line 85 of file BSplineEdge.C.
References BSpline::position().
Foam::scalar length () const virtual
Return the length of the spline curve (not implemented)
Implements curvedEdge.
Definition at line 91 of file BSplineEdge.C.
References BSpline::length().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/curvedEdges/BSplineEdge.H
src/mesh/blockMesh/curvedEdges/BSplineEdge.C