OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
blockDescriptor Class Reference
Takes the description of the block and the list of curved edges and creates a list of points on edges together with the weighting factors.
Public Member Functions
blockDescriptor (const cellShape &, const pointField &blockPointField, const curvedEdgeList &, const Vector< label > &meshDensity, const UList< gradingDescriptors > &expand, const word &zoneName="")
Construct from components. Optional cellSet/zone name.
blockDescriptor (const pointField &blockPointField, const curvedEdgeList &, Istream &)
Construct from Istream.
autoPtr< blockDescriptor > clone () const
Clone.
~blockDescriptor ()
Destructor.
const Vector< label > & density () const
Return the number of cells in the i,j,k directions.
const pointField & blockPointField () const
Reference to point field defining the block mesh.
const cellShape & blockShape () const
Return the block shape.
const List< List< point > > & blockEdgePoints () const
Return the block points along each edge.
const scalarListList & blockEdgeWeights () const
Return the weightings along each edge.
const Vector< label > & meshDensity () const
Return the mesh density (number of cells) in the i,j,k directions.
const word & zoneName () const
Return the (optional) zone name.
label nPoints () const
Return the number of points.
label nCells () const
Return the number of cells.
const point & blockPoint (const label i) const
Return block point at local label i.
Friends
Ostream & operator<< (Ostream &, const blockDescriptor &)
Detailed Description
Takes the description of the block and the list of curved edges and creates a list of points on edges together with the weighting factors.
Source files
blockDescriptor.H
blockDescriptor.C
blockDescriptorEdges.C
Definition at line 61 of file blockDescriptor.H.
Constructor & Destructor Documentation
blockDescriptor (const cellShape & bshape, const pointField & blockPointField, const curvedEdgeList & edges, const Vector< label > & meshDensity, const UList< gradingDescriptors > & expand, const word & zoneName = "")
Construct from components. Optional cellSet/zone name.
Definition at line 32 of file blockDescriptor.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
blockDescriptor (const pointField & blockPointField, const curvedEdgeList & edges, Istream & is)
Construct from Istream.
Definition at line 63 of file blockDescriptor.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInFunction, token::info(), token::isPunctuation(), token::isWord(), token::pToken(), Istream::putBack(), List< T >::size(), and token::wordToken().
~blockDescriptor ()
Destructor.
Definition at line 171 of file blockDescriptor.C.
Referenced by blockDescriptor::clone().
Member Function Documentation
autoPtr<blockDescriptor> clone () const inline
Clone.
Definition at line 129 of file blockDescriptor.H.
References NotImplemented, and blockDescriptor::~blockDescriptor().
const Vector<label>& density () const inline
Return the number of cells in the i,j,k directions.
Definition at line 145 of file blockDescriptor.H.
References blockDescriptor::blockEdgePoints(), blockDescriptor::blockEdgeWeights(), blockDescriptor::blockPoint(), blockDescriptor::blockPointField(), blockDescriptor::blockShape(), blockDescriptor::meshDensity(), blockDescriptor::nCells(), blockDescriptor::nPoints(), blockDescriptor::operator<<, and blockDescriptor::zoneName().
const Foam::pointField & blockPointField () const
Reference to point field defining the block mesh.
Definition at line 177 of file blockDescriptor.C.
Referenced by blockDescriptor::density().
const Foam::cellShape & blockShape () const
Return the block shape.
Definition at line 183 of file blockDescriptor.C.
Referenced by blockDescriptor::density(), and Foam::operator<<().
const Foam::List< Foam::List< Foam::point > > & blockEdgePoints () const
Return the block points along each edge.
Definition at line 190 of file blockDescriptor.C.
Referenced by blockDescriptor::density().
const Foam::scalarListList & blockEdgeWeights () const
Return the weightings along each edge.
Definition at line 196 of file blockDescriptor.C.
Referenced by blockDescriptor::density().
const Foam::Vector< Foam::label > & meshDensity () const
Return the mesh density (number of cells) in the i,j,k directions.
Definition at line 202 of file blockDescriptor.C.
Referenced by blockDescriptor::density(), Foam::faceNij(), Foam::facePoint(), Foam::facePointN(), Foam::operator<<(), and block::vtxLabel().
const Foam::word & zoneName () const
Return the (optional) zone name.
Definition at line 208 of file blockDescriptor.C.
Referenced by blockDescriptor::density(), and Foam::operator<<().
Foam::label nPoints () const
Return the number of points.
Definition at line 214 of file blockDescriptor.C.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by blockDescriptor::density().
Foam::label nCells () const
Return the number of cells.
Definition at line 225 of file blockDescriptor.C.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by blockDescriptor::density().
const Foam::point & blockPoint (const label i) const
Return block point at local label i.
Definition at line 236 of file blockDescriptor.C.
Referenced by blockDescriptor::density().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const blockDescriptor &) friend
Referenced by blockDescriptor::density().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockDescriptor/blockDescriptor.H
src/mesh/blockMesh/blockDescriptor/blockDescriptor.C
src/mesh/blockMesh/blockDescriptor/blockDescriptorEdges.C