OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
calcFvcDiv Class Reference
Finite volume tools function objects
This function object calculates the divergence of a field. The operation is limited to surfaceScalarFields and volumeVector fields, and the output is a volume scalar field.
Public Member Functions
TypeName ("calcFvcDiv")
Runtime type information.
calcFvcDiv (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~calcFvcDiv ()
Destructor.
virtual const word & name () const
Return name of the set of calcFvcDiv.
virtual void read (const dictionary &)
Read the calcFvcDiv data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the calcFvcDiv and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
This function object calculates the divergence of a field. The operation is limited to surfaceScalarFields and volumeVector fields, and the output is a volume scalar field.
Source files
calcFvcDiv.H
calcFvcDiv.C
IOcalcFvcDiv.H
Definition at line 65 of file calcFvcDiv.H.
Constructor & Destructor Documentation
calcFvcDiv (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 80 of file calcFvcDiv.C.
References Foam::endl(), Foam::nl, Foam::read(), and WarningIn.
~calcFvcDiv () virtual
Destructor.
Definition at line 116 of file calcFvcDiv.C.
Member Function Documentation
TypeName ("calcFvcDiv")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the set of calcFvcDiv.
Definition at line 136 of file calcFvcDiv.H.
void read (const dictionary & dict) virtual
Read the calcFvcDiv data.
Definition at line 122 of file calcFvcDiv.C.
References dictionary::lookup().
void execute () virtual
Execute, currently does nothing.
Definition at line 137 of file calcFvcDiv.C.
References Foam::endl(), and WarningIn.
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 155 of file calcFvcDiv.C.
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 164 of file calcFvcDiv.C.
void write () virtual
Calculate the calcFvcDiv and write.
Definition at line 170 of file calcFvcDiv.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 157 of file calcFvcDiv.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 161 of file calcFvcDiv.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/fvTools/calcFvcDiv/calcFvcDiv.H
src/postProcessing/functionObjects/fvTools/calcFvcDiv/calcFvcDiv.C
src/postProcessing/functionObjects/fvTools/calcFvcDiv/calcFvcDivTemplates.C