OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
bC10H7CH3 Class Reference
betaMethylNaphthalene
Public Member Functions
TypeName ("bC11H10")
Runtime type information.
bC10H7CH3 ()
Construct null.
bC10H7CH3 (const liquidProperties &l, const NSRDSfunc5 &density, const NSRDSfunc1 &vapourPressure, const NSRDSfunc6 &heatOfVapourisation, const NSRDSfunc0 &heatCapacity, const NSRDSfunc0 &enthalpy, const NSRDSfunc7 &idealGasHeatCapacity, const NSRDSfunc4 &secondVirialCoeff, const NSRDSfunc1 &dynamicViscosity, const NSRDSfunc2 &vapourDynamicViscosity, const NSRDSfunc0 &thermalConductivity, const NSRDSfunc2 &vapourThermalConductivity, const NSRDSfunc6 &surfaceTension, const APIdiffCoefFunc &vapourDiffussivity)
Construct from components.
bC10H7CH3 (Istream &is)
Construct from Istream.
bC10H7CH3 (const dictionary &dict)
Construct from dictionary.
bC10H7CH3 (const bC10H7CH3 &liq)
Construct copy.
virtual autoPtr< liquidProperties > clone () const
Construct and return clone.
scalar rho (scalar p, scalar T) const
Liquid density [kg/m^3].
scalar pv (scalar p, scalar T) const
Vapour pressure [Pa].
scalar hl (scalar p, scalar T) const
Heat of vapourisation [J/kg].
scalar Cp (scalar p, scalar T) const
Liquid heat capacity [J/(kg K)].
scalar h (scalar p, scalar T) const
Liquid Enthalpy [J/(kg)].
scalar Cpg (scalar p, scalar T) const
Ideal gas heat capacity [J/(kg K)].
scalar B (scalar p, scalar T) const
Second Virial Coefficient [m^3/kg].
scalar mu (scalar p, scalar T) const
Liquid viscosity [Pa s].
scalar mug (scalar p, scalar T) const
Vapour viscosity [Pa s].
scalar K (scalar p, scalar T) const
Liquid thermal conductivity [W/(m K)].
scalar Kg (scalar p, scalar T) const
Vapour thermal conductivity [W/(m K)].
scalar sigma (scalar p, scalar T) const
Surface tension [N/m].
scalar D (scalar p, scalar T) const
Vapour diffussivity [m2/s].
scalar D (scalar p, scalar T, scalar Wb) const
Vapour diffussivity [m2/s] with specified binary pair.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from liquidProperties
TypeName ("liquidProperties")
declareRunTimeSelectionTable (autoPtr, liquidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, liquidProperties, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, liquidProperties, dictionary,(const dictionary &dict),(dict))
liquidProperties (scalar W, scalar Tc, scalar Pc, scalar Vc, scalar Zc, scalar Tt, scalar Pt, scalar Tb, scalar dipm, scalar omega, scalar delta)
Construct from components.
liquidProperties (Istream &is)
Construct from Istream.
liquidProperties (const dictionary &dict)
Construct from dictionary.
liquidProperties (const liquidProperties &liq)
Construct copy.
virtual ~liquidProperties ()
Destructor.
scalar W () const
Molecular weight [kg/kmol].
scalar Tc () const
Critical temperature [K].
scalar Pc () const
Critical pressure [Pa].
scalar Vc () const
Critical volume [m^3/kmol].
scalar Zc () const
Critical compressibilty factor.
scalar Tt () const
Triple point temperature [K].
scalar Pt () const
Triple point pressure [Pa].
scalar Tb () const
Normal boiling temperature [K].
scalar dipm () const
Dipole moment [].
scalar omega () const
Pitzer's ascentric factor [].
scalar delta () const
Solubility parameter [(J/m^3)^(1/2)].
virtual scalar pvInvert (scalar p) const
Invert the vapour pressure relationship to retrieve the.
Friends
Ostream & operator<< (Ostream &os, const bC10H7CH3 &l)
Ostream Operator.
Additional Inherited Members
Static Public Member Functions inherited from liquidProperties
static autoPtr< liquidProperties > New (Istream &is)
Return a pointer to a new liquidProperties created from input.
static autoPtr< liquidProperties > New (const dictionary &dict)
Return a pointer to a new liquidProperties created from dictionary.
Detailed Description
betaMethylNaphthalene
Source files
bC10H7CH3.H
bC10H7CH3.C
Definition at line 58 of file bC10H7CH3.H.
Constructor & Destructor Documentation
bC10H7CH3 ()
Construct null.
Definition at line 41 of file bC10H7CH3.C.
Referenced by bC10H7CH3::clone().
bC10H7CH3 (const liquidProperties & l, const NSRDSfunc5 & density, const NSRDSfunc1 & vapourPressure, const NSRDSfunc6 & heatOfVapourisation, const NSRDSfunc0 & heatCapacity, const NSRDSfunc0 & enthalpy, const NSRDSfunc7 & idealGasHeatCapacity, const NSRDSfunc4 & secondVirialCoeff, const NSRDSfunc1 & dynamicViscosity, const NSRDSfunc2 & vapourDynamicViscosity, const NSRDSfunc0 & thermalConductivity, const NSRDSfunc2 & vapourThermalConductivity, const NSRDSfunc6 & surfaceTension, const APIdiffCoefFunc & vapourDiffussivity)
Construct from components.
Definition at line 89 of file bC10H7CH3.C.
bC10H7CH3 (Istream & is)
Construct from Istream.
Definition at line 123 of file bC10H7CH3.C.
bC10H7CH3 (const dictionary & dict)
Construct from dictionary.
Definition at line 142 of file bC10H7CH3.C.
bC10H7CH3 (const bC10H7CH3 & liq)
Construct copy.
Definition at line 161 of file bC10H7CH3.C.
Member Function Documentation
TypeName ("bC11H10")
Runtime type information.
virtual autoPtr<liquidProperties> clone () const inline virtual
Construct and return clone.
Reimplemented from liquidProperties.
Definition at line 119 of file bC10H7CH3.H.
References bC10H7CH3::B(), bC10H7CH3::bC10H7CH3(), bC10H7CH3::Cp(), bC10H7CH3::Cpg(), bC10H7CH3::D(), bC10H7CH3::h(), bC10H7CH3::hl(), bC10H7CH3::K(), bC10H7CH3::Kg(), bC10H7CH3::mu(), bC10H7CH3::mug(), p, bC10H7CH3::pv(), bC10H7CH3::rho(), bC10H7CH3::sigma(), and Foam::T().
Foam::scalar rho (scalar p, scalar T) const inline virtual
Liquid density [kg/m^3].
Reimplemented from liquidProperties.
Definition at line 26 of file bC10H7CH3I.H.
References NSRDSfunc5::f().
Referenced by bC10H7CH3::clone().
Foam::scalar pv (scalar p, scalar T) const inline virtual
Vapour pressure [Pa].
Reimplemented from liquidProperties.
Definition at line 32 of file bC10H7CH3I.H.
References NSRDSfunc1::f().
Referenced by bC10H7CH3::clone().
Foam::scalar hl (scalar p, scalar T) const inline virtual
Heat of vapourisation [J/kg].
Reimplemented from liquidProperties.
Definition at line 38 of file bC10H7CH3I.H.
References NSRDSfunc6::f().
Referenced by bC10H7CH3::clone().
Foam::scalar Cp (scalar p, scalar T) const inline virtual
Liquid heat capacity [J/(kg K)].
Reimplemented from liquidProperties.
Definition at line 44 of file bC10H7CH3I.H.
References NSRDSfunc0::f().
Referenced by bC10H7CH3::clone().
Foam::scalar h (scalar p, scalar T) const inline virtual
Liquid Enthalpy [J/(kg)].
Reimplemented from liquidProperties.
Definition at line 50 of file bC10H7CH3I.H.
References NSRDSfunc0::f().
Referenced by bC10H7CH3::clone().
Foam::scalar Cpg (scalar p, scalar T) const inline virtual
Ideal gas heat capacity [J/(kg K)].
Reimplemented from liquidProperties.
Definition at line 56 of file bC10H7CH3I.H.
References NSRDSfunc7::f().
Referenced by bC10H7CH3::clone().
Foam::scalar B (scalar p, scalar T) const inline
Second Virial Coefficient [m^3/kg].
Definition at line 62 of file bC10H7CH3I.H.
References NSRDSfunc4::f().
Referenced by bC10H7CH3::clone().
Foam::scalar mu (scalar p, scalar T) const inline virtual
Liquid viscosity [Pa s].
Reimplemented from liquidProperties.
Definition at line 68 of file bC10H7CH3I.H.
References NSRDSfunc1::f().
Referenced by bC10H7CH3::clone().
Foam::scalar mug (scalar p, scalar T) const inline virtual
Vapour viscosity [Pa s].
Reimplemented from liquidProperties.
Definition at line 74 of file bC10H7CH3I.H.
References NSRDSfunc2::f().
Referenced by bC10H7CH3::clone().
Foam::scalar K (scalar p, scalar T) const inline virtual
Liquid thermal conductivity [W/(m K)].
Reimplemented from liquidProperties.
Definition at line 80 of file bC10H7CH3I.H.
References NSRDSfunc0::f().
Referenced by bC10H7CH3::clone().
Foam::scalar Kg (scalar p, scalar T) const inline virtual
Vapour thermal conductivity [W/(m K)].
Reimplemented from liquidProperties.
Definition at line 86 of file bC10H7CH3I.H.
References NSRDSfunc2::f().
Referenced by bC10H7CH3::clone().
Foam::scalar sigma (scalar p, scalar T) const inline virtual
Surface tension [N/m].
Reimplemented from liquidProperties.
Definition at line 92 of file bC10H7CH3I.H.
References NSRDSfunc6::f().
Referenced by bC10H7CH3::clone().
Foam::scalar D (scalar p, scalar T) const inline virtual
Vapour diffussivity [m2/s].
Reimplemented from liquidProperties.
Definition at line 98 of file bC10H7CH3I.H.
References APIdiffCoefFunc::f().
Referenced by bC10H7CH3::clone().
Foam::scalar D (scalar p, scalar T, scalar Wb) const inline virtual
Vapour diffussivity [m2/s] with specified binary pair.
Reimplemented from liquidProperties.
Definition at line 104 of file bC10H7CH3I.H.
References APIdiffCoefFunc::f().
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Reimplemented from liquidProperties.
Definition at line 173 of file bC10H7CH3.H.
References Foam::endl(), Foam::nl, APIdiffCoefFunc::writeData(), NSRDSfunc2::writeData(), NSRDSfunc5::writeData(), NSRDSfunc4::writeData(), NSRDSfunc1::writeData(), NSRDSfunc7::writeData(), NSRDSfunc0::writeData(), NSRDSfunc6::writeData(), and liquidProperties::writeData().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const bC10H7CH3 & l) friend
Ostream Operator.
Definition at line 192 of file bC10H7CH3.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/properties/liquidProperties/bC10H7CH3/bC10H7CH3.H
src/thermophysicalModels/properties/liquidProperties/bC10H7CH3/bC10H7CH3.C
src/thermophysicalModels/properties/liquidProperties/bC10H7CH3/bC10H7CH3I.H