OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart > Class Template Reference
Sub-block type.
Public Member Functions
Block (msType &matrix)
Construct for the given matrix.
template<class Form2 >
void operator= (const MatrixSpace< Form2, Cmpt, SubTensor::nRows, SubTensor::nCols > &matrix)
Assignment to a matrix.
template<class VSForm >
void operator= (const VectorSpace< VSForm, Cmpt, SubTensor::nRows > &v)
Assignment to a column vector.
const Cmpt & operator() (const direction i, const direction j) const
(i, j) const element access operator
Cmpt & operator() (const direction i, const direction j)
(i, j) element access operator
Static Public Member Functions
static direction m ()
Return the number of rows in the block.
static direction n ()
Return the number of columns in the block.
Static Public Attributes
static const direction nRows = SubTensor::nRows
static const direction nCols = SubTensor::nCols
Detailed Description
template<class Form, class Cmpt, direction Nrows, direction Ncols>
template<class SubTensor, direction BRowStart, direction BColStart>
class Foam::MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >
Sub-block type.
Definition at line 135 of file MatrixSpace.H.
Constructor & Destructor Documentation
Block (msType & matrix) inline
Construct for the given matrix.
Definition at line 102 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Nrows, Ncols >::nCols, MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::nCols, MatrixSpace< Form, Cmpt, Nrows, Ncols >::nRows, MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::nRows, and StaticAssert.
Member Function Documentation
static direction m () inline static
Return the number of rows in the block.
Definition at line 146 of file MatrixSpace.H.
References MatrixSpace< Form, Cmpt, Nrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::nRows.
static direction n () inline static
Return the number of columns in the block.
Definition at line 152 of file MatrixSpace.H.
References MatrixSpace< Form, Cmpt, Nrows, Ncols >::block(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::elmt(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::MatrixSpace(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::nCols, VectorSpace< Form, Cmpt, Nrows *Ncols >::operator, MatrixSpace< Form, Cmpt, Nrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::operator()(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::operator=(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::T(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::xx(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::xy(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::xz(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::yx(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::yy(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::yz(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::zx(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::zy(), and MatrixSpace< Form, Cmpt, Nrows, Ncols >::zz().
void operator= (const MatrixSpace< Form2, Cmpt, SubTensor::nRows, SubTensor::nCols > & matrix) inline
Assignment to a matrix.
Definition at line 445 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::nCols, MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::nRows, VectorSpace< Form, Cmpt, Nrows *Ncols >::operator, and MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator()().
void operator= (const VectorSpace< VSForm, Cmpt, SubTensor::nRows > & v) inline
Assignment to a column vector.
Definition at line 466 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::nCols, MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator()(), StaticAssert, and MatrixSpace< Form, Cmpt, Nrows, Ncols >::T().
const Cmpt & operator() (const direction i, const direction j) const inline
(i, j) const element access operator
Definition at line 378 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Nrows, Ncols >::operator()().
Referenced by MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=(), MatrixSpace< Form, Cmpt, Nrows, Ncols >::operator=(), and MatrixSpace< Form, Cmpt, Nrows, Ncols >::T().
Cmpt & operator() (const direction i, const direction j) inline
(i, j) element access operator
Definition at line 389 of file MatrixSpaceI.H.
Member Data Documentation
const direction nRows = SubTensor::nRows static
Definition at line 142 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::Block(), and MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=().
const direction nCols = SubTensor::nCols static
Definition at line 143 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::Block(), and MatrixSpace< Form, Cmpt, Nrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/MatrixSpace/MatrixSpace.H
src/OpenFOAM/primitives/MatrixSpace/MatrixSpaceI.H