OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CatmullRomSpline Class Reference
An implementation of Catmull-Rom splines (sometimes known as Overhauser splines).
Public Member Functions
CatmullRomSpline (const pointField &knots, const bool notImplementedClosed=false)
Construct from components.
point position (const scalar lambda) const
Return the point position corresponding to the curve parameter.
point position (const label segment, const scalar lambda) const
Return the point position corresponding to the local parameter.
scalar length () const
Return the length of the curve.
Public Member Functions inherited from polyLine
polyLine (const pointField &, const bool notImplementedClosed=false)
Construct from components.
const pointField & points () const
Return const-access to the control-points.
label nSegments () const
Return the number of line segments.
point position (const scalar) const
Return the point position corresponding to the curve parameter.
point position (const label segment, const scalar) const
Return the point position corresponding to the local parameter.
scalar length () const
Return the length of the curve.
Additional Inherited Members
Protected Member Functions inherited from polyLine
void calcParam ()
Precalculate the rational cumulative parameter value.
label localParameter (scalar &lambda) const
Return the line segment and the local parameter [0..1].
Protected Attributes inherited from polyLine
pointField points_
The control points or ends of each segments.
scalar lineLength_
The real line length.
scalarList param_
The rational (0-1) cumulative parameter value for each point.
Detailed Description
An implementation of Catmull-Rom splines (sometimes known as Overhauser splines).
In this implementation, the end tangents are created automatically by reflection.
In matrix form, the local interpolation on the interval t=[0..1] is described as follows:
P(t) = 1/2 * [ t^3 t^2 t 1 ] * [ -1  3 -3  1 ] * [ P-1 ]
                               [  2 -5  4 -1 ]   [ P0 ]
                               [ -1  0  1  0 ]   [ P1 ]
                               [  0  2  0  0 ]   [ P2 ]
Where P-1 and P2 represent the neighbouring points or the extrapolated end points. Simple reflection is used to automatically create the end points.
The spline is discretized based on the chord length of the individual segments. In rare cases (sections with very high curvatures), the resulting distribution may be sub-optimal.
A future implementation could also handle closed splines.
See also
http://www.algorithmist.net/catmullrom.html provides a nice introduction
Source files
CatmullRomSpline.H
CatmullRomSpline.C
Definition at line 75 of file CatmullRomSpline.H.
Constructor & Destructor Documentation
CatmullRomSpline (const pointField & knots, const bool notImplementedClosed = false)
Construct from components.
Definition at line 32 of file CatmullRomSpline.C.
Member Function Documentation
Foam::point position (const scalar lambda) const
Return the point position corresponding to the curve parameter.
0 <= lambda <= 1
Definition at line 43 of file CatmullRomSpline.C.
References UList< T >::first(), lambda(), UList< T >::last(), polyLine::localParameter(), Foam::constant::physicoChemical::mu, and polyLine::points().
Referenced by splineEdge::position().
Foam::point position (const label segment, const scalar lambda) const
Return the point position corresponding to the local parameter.
0 <= lambda <= 1 on the given segment
Definition at line 62 of file CatmullRomSpline.C.
References UList< T >::first(), UList< T >::last(), polyLine::nSegments(), and polyLine::points().
Foam::scalar length () const
Return the length of the curve.
Definition at line 133 of file CatmullRomSpline.C.
References NotImplemented.
Referenced by splineEdge::length().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/curvedEdges/CatmullRomSpline.H
src/mesh/blockMesh/curvedEdges/CatmullRomSpline.C