OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Cloud< ParticleType > Class Template Reference
Base cloud calls templated on particle type.
Public Types
typedef ParticleType particleType
typedef IDLList< ParticleType >::iterator iterator
typedef IDLList< ParticleType >::const_iterator const_iterator
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject * >
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Types inherited from UILList< DLListBase, ParticleType >
typedef ParticleType value_type
Type of values the DLList contains.
typedef ParticleType & reference
Type that can be used for storing into DLList::value_type.
typedef const ParticleType & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase::iterator LListBase_iterator
typedef DLListBase::const_iterator LListBase_const_iterator
Public Member Functions
TypeName ("Cloud")
Runtime type information.
Cloud (const polyMesh &mesh, const IDLList< ParticleType > &particles)
Construct from mesh and a list of particles.
Cloud (const polyMesh &mesh, const word &cloudName, const IDLList< ParticleType > &particles)
Construct from mesh, cloud name, and a list of particles.
Cloud (const polyMesh &mesh, const bool checkClass=true)
Construct from mesh by reading from file.
Cloud (const polyMesh &pMesh, const word &cloudName, const bool checkClass=true)
Construct from mesh by reading from file with given cloud instance.
const polyMesh & pMesh () const
Return the polyMesh reference.
label size () const
DynamicList< label > & labels ()
label nTrackingRescues () const
Return nTrackingRescues.
void trackingRescue () const
Increment the nTrackingRescues counter.
const PackedBoolList & cellHasWallFaces () const
Whether each cell has any wall faces (demand driven data)
virtual bool hasWallImpactDistance () const
Switch to specify if particles of the cloud can return.
const const_iterator begin () const
const const_iterator cbegin () const
const const_iterator end () const
const const_iterator cend () const
iterator begin ()
iterator end ()
void clear ()
void addParticle (ParticleType *pPtr)
Transfer particle to cloud.
void deleteParticle (ParticleType &)
Remove particle from cloud and delete.
void cloudReset (const Cloud< ParticleType > &c)
Reset the particles.
template<class TrackData >
void move (TrackData &td, const scalar trackTime)
Move the particles.
template<class TrackData >
void autoMap (TrackData &td, const mapPolyMesh &)
Remap the cells of particles corresponding to the.
IOobject fieldIOobject (const word &fieldName, const IOobject::readOption r) const
Helper to construct IOobject for field and current time.
template<class DataType >
void checkFieldIOobject (const Cloud< ParticleType > &c, const IOField< DataType > &data) const
Check lagrangian data field.
template<class DataType >
void checkFieldFieldIOobject (const Cloud< ParticleType > &c, const CompactIOField< Field< DataType >, DataType > &data) const
Check lagrangian data fieldfield.
virtual void readFields ()
Read the field data for the cloud of particles. Dummy at.
virtual void writeFields () const
Write the field data for the cloud of particles Dummy at.
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write using given format, version and compression.
void writePositions () const
Write positions to <cloudName>_positions.obj file.
Public Member Functions inherited from cloud
TypeName ("cloud")
Runtime type information.
cloud (const objectRegistry &, const word &cloudName="")
Construct for the given objectRegistry and named cloud instance.
virtual ~cloud ()
Destructor.
virtual void autoMap (const mapPolyMesh &)
Remap the cells of particles corresponding to the.
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject * >
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash >> &)
Construct by transferring the parameter contents.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from IDLList< ParticleType >
IDLList ()
Null construct.
IDLList (const ParticleType &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< ParticleType > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, ParticleType >
ILList ()
Null construct.
ILList (ParticleType *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, ParticleType > &)
Construct as copy.
ILList (const ILList< DLListBase, ParticleType > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (ParticleType *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, ParticleType > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, ParticleType > &)
Public Member Functions inherited from UILList< DLListBase, ParticleType >
UILList ()
Null construct.
UILList (ParticleType *a)
Construct given initial T.
UILList (const UILList< DLListBase, ParticleType > &)
Construct as copy.
ParticleType * first ()
Return the first entry.
const ParticleType * first () const
Return the first entry.
ParticleType * last ()
Return the last entry.
const ParticleType * last () const
Return the last entry.
ParticleType * removeHead ()
Remove and return head.
ParticleType * remove (ParticleType *p)
Remove and return element.
ParticleType * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, ParticleType > &)
iterator begin ()
const_iterator begin () const
const iterator & end ()
const const_iterator & end () const
const_iterator cbegin () const
const const_iterator & cend () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< DLListBase, ParticleType > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, ParticleType > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Static Public Attributes
static word cloudPropertiesName
Name of cloud properties dictionary.
Static Public Attributes inherited from cloud
static const word prefix
The prefix to local: lagrangian.
static word defaultName
The default cloud name: defaultCloud.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Friends
class particle
template<class ParticleT >
class IOPosition
Ostream & operator (Ostream &, const Cloud< ParticleType > &)
Additional Inherited Members
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class ParticleType>
class Foam::Cloud< ParticleType >
Base cloud calls templated on particle type.
Source files
Cloud.H
Cloud.C
CloudIO.C
Definition at line 52 of file Cloud.H.
Member Typedef Documentation
typedef ParticleType particleType
Definition at line 114 of file Cloud.H.
typedef IDLList<ParticleType>::iterator iterator
Definition at line 116 of file Cloud.H.
typedef IDLList<ParticleType>::const_iterator const_iterator
Definition at line 117 of file Cloud.H.
Constructor & Destructor Documentation
Cloud (const polyMesh & mesh, const IDLList< ParticleType > & particles)
Construct from mesh and a list of particles.
Definition at line 97 of file Cloud.C.
Referenced by Cloud< ParticleType >::Cloud().
Cloud (const polyMesh & mesh, const word & cloudName, const IDLList< ParticleType > & particles)
Construct from mesh, cloud name, and a list of particles.
Definition at line 122 of file Cloud.C.
Cloud (const polyMesh & mesh, const bool checkClass = true)
Construct from mesh by reading from file.
Optionally disable checking of class name for post-processing
Definition at line 154 of file CloudIO.C.
References Cloud< ParticleType >::Cloud().
Cloud (const polyMesh & pMesh, const word & cloudName, const bool checkClass = true)
Construct from mesh by reading from file with given cloud instance.
Optionally disable checking of class name for post-processing
Definition at line 173 of file CloudIO.C.
References Cloud< ParticleType >::fieldIOobject().
Member Function Documentation
TypeName ("Cloud< ParticleType >")
Runtime type information.
const polyMesh& pMesh () const inline
Return the polyMesh reference.
Definition at line 170 of file Cloud.H.
Referenced by IOPosition< CloudType >::readData().
label size () const inline
Definition at line 175 of file Cloud.H.
Referenced by Cloud< ParticleType >::checkFieldFieldIOobject(), Cloud< ParticleType >::checkFieldIOobject(), wallBoundedStreamLineParticle::readFields(), solidParticle::readFields(), MPPICParcel< ParcelType >::readFields(), streamLineParticle::readFields(), CollidingParcel< ParcelType >::readFields(), wallBoundedParticle::readFields(), molecule::readFields(), ReactingParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readFields(), particle< Type >::readFields(), KinematicParcel< ParcelType >::readFields(), Cloud< streamLineParticle >::trackingRescue(), USERD_get_gold_part_build_info(), IOPosition< CloudType >::write(), IOPosition< CloudType >::writeData(), wallBoundedStreamLineParticle::writeFields(), solidParticle::writeFields(), MPPICParcel< ParcelType >::writeFields(), streamLineParticle::writeFields(), CollidingParcel< ParcelType >::writeFields(), wallBoundedParticle::writeFields(), molecule::writeFields(), ReactingParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::writeFields(), ThermoParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::writeFields(), particle< Type >::writeFields(), and KinematicParcel< ParcelType >::writeFields().
DynamicList<label>& labels () inline
Definition at line 180 of file Cloud.H.
label nTrackingRescues () const inline
Return nTrackingRescues.
Definition at line 186 of file Cloud.H.
void trackingRescue () const inline
Increment the nTrackingRescues counter.
Definition at line 192 of file Cloud.H.
const Foam::PackedBoolList & cellHasWallFaces () const
Whether each cell has any wall faces (demand driven data)
Definition at line 149 of file Cloud.C.
Referenced by particle< Type >::hitWallFaces(), and Cloud< streamLineParticle >::trackingRescue().
virtual bool hasWallImpactDistance () const inline virtual
Switch to specify if particles of the cloud can return.
non-zero wall distance values. By default, assume that they can't (default for wallImpactDistance in particle is 0.0).
Reimplemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, CollidingCloud< CloudType >, CollidingCloud< Foam::DSMCCloud >, and solidParticleCloud.
Definition at line 209 of file Cloud.H.
Referenced by particle< Type >::hitWallFaces(), and Cloud< streamLineParticle >::trackingRescue().
const const_iterator begin () const inline
Definition at line 217 of file Cloud.H.
const const_iterator cbegin () const inline
Definition at line 222 of file Cloud.H.
const const_iterator end () const inline
Definition at line 227 of file Cloud.H.
const const_iterator cend () const inline
Definition at line 232 of file Cloud.H.
iterator begin () inline
Definition at line 237 of file Cloud.H.
iterator end () inline
Definition at line 242 of file Cloud.H.
void clear () inline
Definition at line 250 of file Cloud.H.
void addParticle (ParticleType * pPtr)
Transfer particle to cloud.
Definition at line 162 of file Cloud.C.
Referenced by nearWallFields::calcAddressing(), and Cloud< streamLineParticle >::clear().
void deleteParticle (ParticleType & p)
Remove particle from cloud and delete.
Definition at line 169 of file Cloud.C.
References p.
Referenced by Cloud< streamLineParticle >::clear().
void cloudReset (const Cloud< ParticleType > & c)
Reset the particles.
Definition at line 176 of file Cloud.C.
Referenced by Cloud< streamLineParticle >::clear().
void move (TrackData & td, const scalar trackTime)
Move the particles.
passing the TrackingData to the track function
Definition at line 187 of file Cloud.C.
References List< T >::append(), Cloud< ParticleType >::autoMap(), polyMesh::boundaryMesh(), List< T >::clear(), Foam::endl(), forAll, forAllIter, Foam::Info, n, primitiveMesh::nInternalFaces(), p, patchi, globalMeshData::processorPatches(), globalMeshData::processorPatchIndices(), globalMeshData::processorPatchNeighbours(), Foam::reduce(), UILList< LListBase, T >::remove(), List< T >::size(), and polyBoundaryMesh::whichPatch().
Referenced by nearWallFields::calcAddressing(), Cloud< streamLineParticle >::clear(), moleculeCloud::evolve(), DSMCCloud< ParcelType >::evolve(), and solidParticleCloud::move().
void autoMap (TrackData & td, const mapPolyMesh & mapper)
Remap the cells of particles corresponding to the.
mesh topology change
Definition at line 396 of file Cloud.C.
References List< T >::clear(), Foam::endl(), forAllIter, InfoInFunction, mapPolyMesh::mergedCell(), Foam::name(), p, Foam::pos(), mapPolyMesh::reverseCellMap(), and mapPolyMesh::reverseFaceMap().
Referenced by Cloud< streamLineParticle >::clear(), and Cloud< ParticleType >::move().
Foam::IOobject fieldIOobject (const word & fieldName, const IOobject::readOption r) const
Helper to construct IOobject for field and current time.
Definition at line 195 of file CloudIO.C.
References Cloud< ParticleType >::checkFieldIOobject(), and timeName.
Referenced by Cloud< streamLineParticle >::clear(), Cloud< ParticleType >::Cloud(), wallBoundedStreamLineParticle::readFields(), solidParticle::readFields(), MPPICParcel< ParcelType >::readFields(), streamLineParticle::readFields(), CollidingParcel< ParcelType >::readFields(), wallBoundedParticle::readFields(), molecule::readFields(), ReactingParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readFields(), particle< Type >::readFields(), KinematicParcel< ParcelType >::readFields(), wallBoundedStreamLineParticle::writeFields(), solidParticle::writeFields(), MPPICParcel< ParcelType >::writeFields(), streamLineParticle::writeFields(), CollidingParcel< ParcelType >::writeFields(), wallBoundedParticle::writeFields(), molecule::writeFields(), ReactingParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::writeFields(), ThermoParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::writeFields(), particle< Type >::writeFields(), and KinematicParcel< ParcelType >::writeFields().
void checkFieldIOobject (const Cloud< ParticleType > & c, const IOField< DataType > & data) const
Check lagrangian data field.
Definition at line 215 of file CloudIO.C.
References Foam::abort(), Cloud< ParticleType >::checkFieldFieldIOobject(), Foam::FatalError, FatalErrorInFunction, IOobject::name(), List< Type >::size(), and Cloud< ParticleType >::size().
Referenced by Cloud< streamLineParticle >::clear(), Cloud< ParticleType >::fieldIOobject(), wallBoundedStreamLineParticle::readFields(), solidParticle::readFields(), MPPICParcel< ParcelType >::readFields(), streamLineParticle::readFields(), CollidingParcel< ParcelType >::readFields(), wallBoundedParticle::readFields(), molecule::readFields(), ReactingParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readFields(), particle< Type >::readFields(), and KinematicParcel< ParcelType >::readFields().
void checkFieldFieldIOobject (const Cloud< ParticleType > & c, const CompactIOField< Field< DataType >, DataType > & data) const
Check lagrangian data fieldfield.
Definition at line 234 of file CloudIO.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, IOobject::name(), List< Type >::size(), and Cloud< ParticleType >::size().
Referenced by Cloud< ParticleType >::checkFieldIOobject(), Cloud< streamLineParticle >::clear(), and CollidingParcel< ParcelType >::readFields().
void readFields () virtual
Read the field data for the cloud of particles. Dummy at.
this level.
Definition at line 251 of file CloudIO.C.
Referenced by Cloud< streamLineParticle >::clear().
void writeFields () const virtual
Write the field data for the cloud of particles Dummy at.
this level.
Reimplemented in ReactingCloud< CloudType >, ReactingCloud< Foam::DSMCCloud >, ReactingMultiphaseCloud< CloudType >, and ReactingMultiphaseCloud< Foam::DSMCCloud >.
Definition at line 256 of file CloudIO.C.
References Cloud< ParticleType >::writeObject().
Referenced by Cloud< streamLineParticle >::clear().
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const virtual
Write using given format, version and compression.
Only writes the cloud file if the Cloud isn't empty
Reimplemented from objectRegistry.
Definition at line 267 of file CloudIO.C.
References IOstream::check().
Referenced by Cloud< streamLineParticle >::clear(), and Cloud< ParticleType >::writeFields().
void writePositions () const
Write positions to <cloudName>_positions.obj file.
Definition at line 468 of file Cloud.C.
References OSstream::flush(), forAllConstIter(), Foam::name(), Foam::nl, p, and path().
Referenced by Cloud< streamLineParticle >::clear().
Friends And Related Function Documentation
friend class particle friend
Definition at line 110 of file Cloud.H.
friend class IOPosition friend
Definition at line 112 of file Cloud.H.
Ostream& operator (Ostream & , const Cloud< ParticleType > &) friend
Member Data Documentation
Foam::word cloudPropertiesName static
Name of cloud properties dictionary.
Definition at line 126 of file Cloud.H.
The documentation for this class was generated from the following files:
src/lagrangian/basic/Cloud/Cloud.H
src/lagrangian/basic/Cloud/Cloud.C
src/lagrangian/basic/Cloud/CloudIO.C