OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cell Class Reference
A cell is defined as a list of faces with extra functionality.
Public Member Functions
cell ()
Construct null.
cell (label)
Construct given size.
cell (const labelUList &)
Construct from list of labels.
cell (const Xfer< labelList > &)
Construct by transferring the parameter contents.
cell (Istream &)
Construct from Istream.
label nFaces () const
Return number of faces.
labelList labels (const faceUList &) const
Return labels of cell vertices.
pointField points (const faceUList &, const pointField &) const
Return the cell vertices.
edgeList edges (const faceUList &) const
Return cell edges.
label opposingFaceLabel (const label masterFaceLabel, const faceUList &meshFaces) const
Return index of opposite face.
oppositeFace opposingFace (const label masterFaceLabel, const faceUList &meshFaces) const
Return opposite face oriented the same way as the master face.
point centre (const pointField &, const faceUList &) const
Returns cell centre.
scalar mag (const pointField &, const faceUList &) const
Returns cell volume.
Public Member Functions inherited from List< label >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const label &)
Construct with given size and value for all elements.
List (const List< label > &)
Copy constructor.
List (const Xfer< List< label >> &)
Construct by transferring the parameter contents.
List (List< label > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< label > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< label, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< label > &)
Construct as copy of PtrList<T>
List (const SLList< label > &)
Construct as copy of SLList<T>
List (const UIndirectList< label > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< label > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< label > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const label &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const label &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const label &)
Append an element at the end of the list.
void append (const UList< label > &)
Append a List at the end of this list.
void append (const UIndirectList< label > &)
Append a UIndirectList at the end of this list.
void transfer (List< label > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< label, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< label > &)
Transfer the contents of the argument List into this list.
Xfer< List< label > > xfer ()
Transfer contents to the Xfer container.
label & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< label > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< label > &)
Assignment operator. Takes linear time.
void operator= (const SLList< label > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< label > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< label > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const label &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< T > &)
Assign elements to those from UList.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Attributes
static const char *const typeName = "cell"
Friends
bool operator== (const cell &, const cell &)
bool operator!= (const cell &, const cell &)
Additional Inherited Members
Public Types inherited from List< label >
typedef SubList< label > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from List< label >
static const List< label > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< label >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
A cell is defined as a list of faces with extra functionality.
Source files
cell.H
cellI.H
Definition at line 56 of file cell.H.
Constructor & Destructor Documentation
cell () inline
Construct null.
Definition at line 31 of file cellI.H.
cell (label s) inline explicit
Construct given size.
Definition at line 36 of file cellI.H.
cell (const labelUList & lst) inline explicit
Construct from list of labels.
Definition at line 43 of file cellI.H.
cell (const Xfer< labelList > & lst) inline explicit
Construct by transferring the parameter contents.
Definition at line 49 of file cellI.H.
cell (Istream & is) inline
Construct from Istream.
Definition at line 56 of file cellI.H.
Member Function Documentation
Foam::label nFaces () const inline
Return number of faces.
Definition at line 65 of file cellI.H.
References List< label >::size().
Foam::labelList labels (const faceUList & f) const
Return labels of cell vertices.
Definition at line 35 of file cell.C.
References UList< T >::first(), forAll, found, p, cell::points(), List< T >::setSize(), List< T >::size(), and UList< T >::size().
Referenced by cell::points().
Foam::pointField points (const faceUList & f, const pointField & meshPoints) const
Return the cell vertices.
Definition at line 102 of file cell.C.
References forAll, cell::labels(), p, pointLabels(), and List< T >::size().
Referenced by cell::labels(), and meshToMeshMethod::writeConnectivity().
Foam::edgeList edges (const faceUList & f) const
Return cell edges.
Definition at line 120 of file cell.C.
References cell::centre(), forAll, and List< T >::setSize().
Referenced by layerAdditionRemoval::changeTopology().
Foam::label opposingFaceLabel (const label masterFaceLabel, const faceUList & meshFaces) const
Return index of opposite face.
Definition at line 40 of file oppositeCellFace.C.
References Foam::endl(), forAll, Foam::Info, cell::opposingFace(), and List< T >::size().
Foam::oppositeFace opposingFace (const label masterFaceLabel, const faceUList & meshFaces) const
Return opposite face oriented the same way as the master face.
Definition at line 115 of file oppositeCellFace.C.
References Foam::constant::electromagnetic::e, forAll, and List< T >::size().
Referenced by cell::opposingFaceLabel().
Foam::point centre (const pointField & p, const faceUList & f) const
Returns cell centre.
Definition at line 173 of file cell.C.
References forAll, cell::mag(), and Vector< scalar >::zero.
Referenced by cell::edges().
Foam::scalar mag (const pointField & p, const faceUList & f) const
Returns cell volume.
Definition at line 239 of file cell.C.
References forAll, Foam::mag(), and Vector< scalar >::zero.
Referenced by cell::centre().
Friends And Related Function Documentation
bool operator== (const cell & , const cell &) friend
bool operator!= (const cell & , const cell &) friend
Member Data Documentation
const char *const typeName = "cell" static
Definition at line 65 of file cell.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cell/cell.H
src/OpenFOAM/meshes/meshShapes/cell/cell.C
src/OpenFOAM/meshes/meshShapes/cell/cellI.H
src/OpenFOAM/meshes/meshShapes/cell/oppositeCellFace.C