OpenFOAM: cellToPoint Class Reference
cellToPoint Class Reference
A topoSetSource to select points based on usage in cells.
Public Types
enum cellAction { ALL }
Enumeration defining the valid options.
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Public Member Functions
TypeName ("cellToPoint")
Runtime type information.
cellToPoint (const polyMesh &mesh, const word &setName, const cellAction option)
Construct from components.
cellToPoint (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
cellToPoint (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~cellToPoint ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label celli, const bool) const
Add (if bool) celli to set or delete celli from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = nullptr
A table of usage strings.
Detailed Description
A topoSetSource to select points based on usage in cells.
Source files
cellToPoint.H
cellToPoint.C
Definition at line 49 of file cellToPoint.H.
Member Enumeration Documentation
enum cellAction
Enumeration defining the valid options.
Enumerator
ALL
Definition at line 56 of file cellToPoint.H.
Constructor & Destructor Documentation
cellToPoint (const polyMesh & mesh, const word & setName, const cellAction option)
Construct from components.
Definition at line 93 of file cellToPoint.C.
Referenced by cellToPoint::cellToPoint(), and NamedEnum< Enum, nEnum >::names().
cellToPoint (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 107 of file cellToPoint.C.
References cellToPoint::cellToPoint().
cellToPoint (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 120 of file cellToPoint.C.
~cellToPoint () virtual
Destructor.
Definition at line 133 of file cellToPoint.C.
References cellToPoint::applyToSet().
Member Function Documentation
TypeName ("cellToPoint")
Runtime type information.
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 117 of file cellToPoint.H.
References cellToPoint::applyToSet(), and topoSetSource::POINTSETSOURCE.
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 140 of file cellToPoint.C.
References topoSetSource::ADD, Foam::ListListOps::combine(), topoSetSource::DELETE, Foam::endl(), Foam::Info, and topoSetSource::NEW.
Referenced by cellToPoint::setType(), and cellToPoint::~cellToPoint().
The documentation for this class was generated from the following files:
src/meshTools/sets/pointSources/cellToPoint/cellToPoint.H
src/meshTools/sets/pointSources/cellToPoint/cellToPoint.C