OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellSource Class Reference
Function objects » Field function objects
This function object provides a 'cell source' variant of the fieldValues function object. Given a list of user-specified fields and a selection of mesh cells, a number of operations can be performed, such as sums, averages and integrations.
Public Types
enum sourceType { stCellZone, stAll }
Source type enumeration.
enum operationType {
opNone, opSum, opSumMag, opAverage,
opWeightedAverage, opVolAverage, opWeightedVolAverage, opVolIntegrate,
opMin, opMax, opCoV
}
Operation type enumeration.
Public Member Functions
TypeName ("cellSource")
Run-time type information.
cellSource (const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles=false)
Construct from components.
virtual ~cellSource ()
Destructor.
const sourceType & source () const
Return the source type.
const labelList & cellId () const
Return the local list of cell IDs.
virtual void read (const dictionary &)
Read from dictionary.
virtual void write ()
Calculate and write.
template<class Type >
bool writeValues (const word &fieldName)
Templated helper function to output field values.
template<class Type >
tmp< Field< Type > > filterField (const Field< Type > &field) const
Filter a field according to cellIds.
template<class Type >
Foam::tmp< Foam::Field< Type > > setFieldValues (const word &fieldName, const bool mustGet) const
template<class Type >
Foam::tmp< Foam::Field< Type > > filterField (const Field< Type > &field) const
Public Member Functions inherited from fieldValue
TypeName ("fieldValue")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, fieldValue, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles),(name, obr, dict, loadFromFiles))
fieldValue (const word &name, const objectRegistry &obr, const dictionary &dict, const word &valueType, const bool loadFromFiles=false)
Construct from components.
virtual ~fieldValue ()
Destructor.
const word & name () const
Return the name of the geometric source.
const objectRegistry & obr () const
Return the reference to the object registry.
const dictionary & dict () const
Return the reference to the construction dictionary.
bool active () const
Return the active flag.
const Switch & log () const
Return the switch to send output to Info as well as to file.
const word & sourceName () const
Return the source name.
const wordList & fields () const
Return the list of field names.
const Switch & valueOutput () const
Return the output field values flag.
const fvMesh & mesh () const
Helper function to return the reference to the mesh.
const dictionary & resultDict () const
Return access to the latest set of results.
virtual void execute ()
Execute.
virtual void end ()
Execute the at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void updateMesh (const mapPolyMesh &)
Update mesh.
virtual void movePoints (const polyMesh &)
Move points.
template<class Type >
void combineFields (Field< Type > &field)
Combine fields from all processor domains into single field.
template<class Type >
void combineFields (tmp< Field< Type >> &)
Combine fields from all processor domains into single field.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Attributes
static const NamedEnum< sourceType, 2 > sourceTypeNames_
Source type names.
static const NamedEnum< operationType, 11 > operationTypeNames_
Operation type names.
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions
void initialise (const dictionary &dict)
Initialise, e.g. cell addressing.
template<class Type >
bool validField (const word &fieldName) const
Return true if the field name is valid.
template<class Type >
tmp< Field< Type > > setFieldValues (const word &fieldName, const bool mustGet=false) const
Insert field values into values list.
template<class Type >
Type processValues (const Field< Type > &values, const scalarField &V, const scalarField &weightField) const
Apply the 'operation' to the values.
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes
sourceType source_
Source type.
operationType operation_
Operation to apply to values.
label nCells_
Global number of cells.
labelList cellId_
Local list of cell IDs.
word weightFieldName_
Weight field name - only used for opWeightedAverage mode.
scalar volume_
Volume of the cellSource.
bool writeVolume_
Optionally write the volume of the cellSource.
Protected Attributes inherited from fieldValue
word name_
Name of this fieldValue object.
const objectRegistry & obr_
Database this class is registered to.
dictionary dict_
Construction dictionary.
bool active_
Active flag.
Switch log_
Switch to send output to Info as well as to file.
word sourceName_
Name of source object.
wordList fields_
List of field names to operate on.
Switch valueOutput_
Output field values flag.
dictionary resultDict_
Results dictionary for external access of results.
Additional Inherited Members
Static Public Member Functions inherited from fieldValue
static autoPtr< fieldValue > New (const word &name, const objectRegistry &obr, const dictionary &dict, const bool loadFromFiles=false, const bool output=true)
Return a reference to the selected fieldValue.
Detailed Description
This function object provides a 'cell source' variant of the fieldValues function object. Given a list of user-specified fields and a selection of mesh cells, a number of operations can be performed, such as sums, averages and integrations.
Example of function object specification:
cellSource1
{
    type            cellSource;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    log             true;
    valueOutput     true;
    source          cellZone;
    sourceName      c0;
    operation       volAverage;
    weightField     alpha1;
    fields
    (
        p
        U
    );
}
Function object usage
Property Description Required Default value
type Type name: cellSource yes
log Write data to standard output no no
valueOutput Write the raw output values yes
writeVolume Write the volume of the cellSource no
source cell source: see below yes
sourceName name of cell source if required no
operation operation to perform yes
weightField name of field to apply weighting no
fields list of fields to operate on yes
Where source is defined by
cellZone : requires a 'sourceName' entry to specify the cellZone
all : all cells
The operation is one of:
none : no operation
sum : sum
sumMag : sum of component magnitudes
average : ensemble average
weightedAverage : weighted average
volAverage : volume weighted average
weightedVolAverage : weighted volume average
volIntegrate : volume integral
min : minimum
max : maximum
CoV : coefficient of variation: standard deviation/mean
See also
Foam::fieldValues Foam::functionObject Foam::OutputFilterFunctionObject
Source files
cellSource.H
cellSource.C
Definition at line 225 of file cellSource.H.
Member Enumeration Documentation
enum sourceType
Source type enumeration.
Enumerator
stCellZone
stAll
Definition at line 235 of file cellSource.H.
enum operationType
Operation type enumeration.
Enumerator
opNone
opSum
opSumMag
opAverage
opWeightedAverage
opVolAverage
opWeightedVolAverage
opVolIntegrate
opMin
opMax
opCoV
Definition at line 246 of file cellSource.H.
Constructor & Destructor Documentation
cellSource (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct from components.
Definition at line 190 of file cellSource.C.
References Foam::read().
Referenced by cellSource::writeFileHeader().
~cellSource () virtual
Destructor.
Definition at line 211 of file cellSource.C.
Member Function Documentation
void initialise (const dictionary & dict) protected
Initialise, e.g. cell addressing.
Definition at line 129 of file cellSource.C.
References Foam::endl(), Foam::Info, Foam::nl, dictionary::readIfPresent(), Foam::type(), and WarningInFunction.
bool validField (const word & fieldName) const protected
Return true if the field name is valid.
Definition at line 32 of file cellSourceTemplates.C.
References objectRegistry::foundObject(), fieldValue::obr_, and cellSource::setFieldValues().
tmp<Field<Type> > setFieldValues (const word & fieldName, const bool mustGet = false) const protected
Insert field values into values list.
Referenced by cellSource::validField().
Type processValues (const Field< Type > & values, const scalarField & V, const scalarField & weightField) const protected
Apply the 'operation' to the values.
Definition at line 72 of file cellSourceTemplates.C.
References Foam::cmptMag(), Foam::component(), Field< Type >::component(), Foam::max(), Foam::min(), cellSource::opAverage, cellSource::opCoV, cellSource::operation_, cellSource::opMax, cellSource::opMin, cellSource::opSum, cellSource::opSumMag, cellSource::opVolAverage, cellSource::opVolIntegrate, cellSource::opWeightedAverage, cellSource::opWeightedVolAverage, Foam::setComponent(), List< Type >::size(), Foam::sqr(), Foam::sqrt(), and Foam::sum().
Referenced by cellSource::setFieldValues(), and cellSource::writeValues().
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from functionObjectFile.
Definition at line 161 of file cellSource.C.
References cellSource::cellSource(), Foam::endl(), forAll, and Foam::tab.
TypeName ("cellSource")
Run-time type information.
const Foam::fieldValues::cellSource::sourceType & source () const inline
Return the source type.
Definition at line 31 of file cellSourceI.H.
References cellSource::source_.
const Foam::labelList & cellId () const inline
Return the local list of cell IDs.
Definition at line 38 of file cellSourceI.H.
References cellSource::cellId_.
void read (const dictionary & dict) virtual
Read from dictionary.
Reimplemented from fieldValue.
Definition at line 217 of file cellSource.C.
References fieldValue::read().
void write () virtual
Calculate and write.
Reimplemented from fieldValue.
Definition at line 229 of file cellSource.C.
References Foam::endl(), forAll, Foam::Info, UPstream::master(), Foam::tab, WarningInFunction, and fieldValue::write().
bool writeValues (const word & fieldName)
Templated helper function to output field values.
Definition at line 156 of file cellSourceTemplates.C.
References dictionary::add(), fieldValue::combineFields(), Foam::endl(), functionObjectFile::file(), cellSource::filterField(), Foam::Info, fieldValue::log_, UPstream::master(), fieldValue::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, fieldValue::obr_, cellSource::operation_, cellSource::operationTypeNames_, cellSource::processValues(), fieldValue::resultDict_, List< Type >::size(), cellSource::source_, fieldValue::sourceName_, cellSource::sourceTypeNames_, Foam::tab, objectRegistry::time(), Time::timeName(), fieldValue::valueOutput_, cellSource::weightFieldName_, and regIOobject::write().
tmp<Field<Type> > filterField (const Field< Type > & field) const
Filter a field according to cellIds.
Referenced by cellSource::setFieldValues(), and cellSource::writeValues().
Foam::tmp<Foam::Field<Type> > setFieldValues (const word & fieldName, const bool mustGet) const
Definition at line 47 of file cellSourceTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, cellSource::filterField(), objectRegistry::foundObject(), objectRegistry::lookupObject(), fieldValue::obr_, and cellSource::processValues().
Foam::tmp<Foam::Field<Type> > filterField (const Field< Type > & field) const
Definition at line 215 of file cellSourceTemplates.C.
References cellSource::cellId_.
Member Data Documentation
const Foam::NamedEnum< Foam::fieldValues::cellSource::sourceType, 2 > sourceTypeNames_ static
Source type names.
Definition at line 242 of file cellSource.H.
Referenced by cellSource::writeValues().
const Foam::NamedEnum< Foam::fieldValues::cellSource::operationType, 11 > operationTypeNames_ static
Operation type names.
Definition at line 262 of file cellSource.H.
Referenced by cellSource::writeValues().
sourceType source_ protected
Source type.
Definition at line 284 of file cellSource.H.
Referenced by cellSource::source(), and cellSource::writeValues().
operationType operation_ protected
Operation to apply to values.
Definition at line 287 of file cellSource.H.
Referenced by cellSource::processValues(), and cellSource::writeValues().
label nCells_ protected
Global number of cells.
Definition at line 290 of file cellSource.H.
labelList cellId_ protected
Local list of cell IDs.
Definition at line 293 of file cellSource.H.
Referenced by cellSource::cellId(), and cellSource::filterField().
word weightFieldName_ protected
Weight field name - only used for opWeightedAverage mode.
Definition at line 296 of file cellSource.H.
Referenced by cellSource::writeValues().
scalar volume_ protected
Volume of the cellSource.
Definition at line 299 of file cellSource.H.
bool writeVolume_ protected
Optionally write the volume of the cellSource.
Definition at line 302 of file cellSource.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/fieldValues/cellSource/cellSource.H
src/postProcessing/functionObjects/field/fieldValues/cellSource/cellSource.C
src/postProcessing/functionObjects/field/fieldValues/cellSource/cellSourceI.H
src/postProcessing/functionObjects/field/fieldValues/cellSource/cellSourceTemplates.C