OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellShape Class Reference
An analytical geometric cellShape.
Public Member Functions
cellShape ()
Construct null.
cellShape (const cellModel &, const labelList &, const bool doCollapse=false)
Construct from components.
cellShape (Istream &is)
Construct from Istream.
autoPtr< cellShape > clone () const
Clone.
pointField points (const pointField &meshPoints) const
Return the points corresponding to this cellShape.
const cellModel & model () const
Model reference.
labelList meshFaces (const faceList &allFaces, const cell &) const
Mesh face labels of this cell (in order of model)
labelList meshEdges (const edgeList &allEdges, const labelList &) const
Mesh edge labels of this cell (in order of model)
faceList faces () const
Faces of this cell.
faceList collapsedFaces () const
Collapsed faces of this cell.
label nFaces () const
Number of faces.
edgeList edges () const
Edges of this cellShape.
label nEdges () const
Number of edges.
label nPoints () const
Number of points.
point centre (const pointField &) const
Centroid of the cell.
Foam::InfoProxy< cellShape > info () const
Return info proxy.
scalar mag (const pointField &) const
Scalar magnitude.
void collapse ()
Collapse shape to correct one after removing duplicate vertices.
Public Member Functions inherited from List< label >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const label &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< label > &)
Copy constructor.
List (const Xfer< List< label >> &)
Construct by transferring the parameter contents.
List (List< label > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< label > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< label, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< label > &)
Construct as copy of PtrList<T>
List (const SLList< label > &)
Construct as copy of SLList<T>
List (const UIndirectList< label > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< label > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< label > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const label &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const label &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const label &)
Append an element at the end of the list.
void append (const UList< label > &)
Append a List at the end of this list.
void append (const UIndirectList< label > &)
Append a UIndirectList at the end of this list.
void transfer (List< label > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< label, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< label > &)
Transfer the contents of the argument List into this list.
Xfer< List< label > > xfer ()
Transfer contents to the Xfer container.
label & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< label > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< label > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< label > &)
Assignment operator. Takes linear time.
void operator= (const SLList< label > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< label > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< label > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const label &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Friends
bool operator== (const cellShape &, const cellShape &)
Istream & operator>> (Istream &, cellShape &)
Ostream & operator<< (Ostream &, const cellShape &)
Additional Inherited Members
Public Types inherited from List< label >
typedef SubList< label > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from List< label >
static const List< label > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< label >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
An analytical geometric cellShape.
The optional collapse functionality changes the cellModel to the correct type after removing any duplicate points.
Source files
cellShape.H
cellShapeI.H
cellShape.C
cellShapeIO.C
cellShapeEqual.C
Definition at line 69 of file cellShape.H.
Constructor & Destructor Documentation
cellShape () inline
Construct null.
Definition at line 31 of file cellShapeI.H.
Referenced by cellShape::clone().
cellShape (const cellModel & M, const labelList & l, const bool doCollapse = false) inline
Construct from components.
Definition at line 38 of file cellShapeI.H.
References cellShape::collapse().
cellShape (Istream & is) inline
Construct from Istream.
Definition at line 54 of file cellShapeI.H.
Member Function Documentation
Foam::autoPtr< Foam::cellShape > clone () const inline
Clone.
Definition at line 60 of file cellShapeI.H.
References cellShape::cellShape(), and cellShape::points().
Foam::pointField points (const pointField & meshPoints) const inline
Return the points corresponding to this cellShape.
Definition at line 69 of file cellShapeI.H.
References forAll, UList< T >::operator[](), p, and List< label >::size().
Referenced by cellShape::clone().
const Foam::cellModel & model () const inline
Model reference.
Definition at line 88 of file cellShapeI.H.
References cellShape::meshFaces().
Referenced by Foam::operator<<().
Foam::labelList meshFaces (const faceList & allFaces, const cell & cFaces) const inline
Mesh face labels of this cell (in order of model)
Definition at line 95 of file cellShapeI.H.
References cellShape::faces(), forAll, cellShape::meshEdges(), and List< T >::size().
Referenced by cellShape::model().
Foam::labelList meshEdges (const edgeList & allEdges, const labelList & cEdges) const inline
Mesh edge labels of this cell (in order of model)
Definition at line 129 of file cellShapeI.H.
References Foam::e, cellShape::edges(), forAll, and List< T >::size().
Referenced by cellShape::meshFaces().
Foam::faceList faces () const inline
Faces of this cell.
Definition at line 162 of file cellShapeI.H.
References cellModel::faces().
Referenced by cellShape::collapsedFaces(), and cellShape::meshFaces().
Foam::faceList collapsedFaces () const inline
Collapsed faces of this cell.
Definition at line 168 of file cellShapeI.H.
References f(), cellShape::faces(), forAll, List< T >::setSize(), and List< T >::size().
Referenced by degenerateMatcher::match().
Foam::label nFaces () const inline
Number of faces.
Definition at line 217 of file cellShapeI.H.
References cellModel::nFaces().
Foam::edgeList edges () const inline
Edges of this cellShape.
Definition at line 223 of file cellShapeI.H.
References cellModel::edges().
Referenced by cellShape::meshEdges().
Foam::label nEdges () const inline
Number of edges.
Definition at line 229 of file cellShapeI.H.
References cellModel::nEdges().
Foam::label nPoints () const inline
Number of points.
Definition at line 235 of file cellShapeI.H.
References List< label >::size().
Foam::point centre (const pointField & points) const inline
Centroid of the cell.
Definition at line 241 of file cellShapeI.H.
References cellModel::centre().
Foam::InfoProxy<cellShape> info () const inline
Return info proxy.
Used to print token information to a stream
Definition at line 142 of file cellShape.H.
Foam::scalar mag (const pointField & points) const inline
Scalar magnitude.
Definition at line 247 of file cellShapeI.H.
References cellModel::mag().
void collapse ()
Collapse shape to correct one after removing duplicate vertices.
Definition at line 31 of file cellShape.C.
References List< label >::operator=().
Referenced by cellShape::cellShape().
Friends And Related Function Documentation
bool operator== (const cellShape & , const cellShape &) friend
Istream& operator>> (Istream & , cellShape &) friend
Ostream& operator<< (Ostream & , const cellShape &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellShape/cellShape.H
src/OpenFOAM/meshes/meshShapes/cellShape/cellShape.C
src/OpenFOAM/meshes/meshShapes/cellShape/cellShapeI.H