OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellToFaceStencil Class Reference
Base class for extended cell-to-face stencils (face values from neighbouring cells)
Classes
class unionEqOp
Combine operator for labelLists.
Public Member Functions
cellToFaceStencil (const polyMesh &)
Construct from mesh.
const polyMesh & mesh () const
const globalIndex & globalNumbering () const
Global numbering for cells and boundary faces.
Public Member Functions inherited from List< labelList >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const labelList &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< labelList > &)
Copy constructor.
List (const Xfer< List< labelList >> &)
Construct by transferring the parameter contents.
List (List< labelList > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< labelList > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< labelList, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< labelList > &)
Construct as copy of PtrList<T>
List (const SLList< labelList > &)
Construct as copy of SLList<T>
List (const UIndirectList< labelList > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< labelList > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< labelList > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const labelList &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const labelList &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const labelList &)
Append an element at the end of the list.
void append (const UList< labelList > &)
Append a List at the end of this list.
void append (const UIndirectList< labelList > &)
Append a UIndirectList at the end of this list.
void transfer (List< labelList > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< labelList, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< labelList > &)
Transfer the contents of the argument List into this list.
Xfer< List< labelList > > xfer ()
Transfer contents to the Xfer container.
labelList & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< labelList > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< labelList > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< labelList > &)
Assignment operator. Takes linear time.
void operator= (const SLList< labelList > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< labelList > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< labelList > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const labelList &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Protected Member Functions
void validBoundaryFaces (boolList &isValidBFace) const
Valid boundary faces (not empty and not coupled)
autoPtr< indirectPrimitivePatch > allCoupledFacesPatch () const
Return patch of all coupled faces.
void insertFaceCells (const label exclude0, const label exclude1, const boolList &nonEmptyFace, const labelList &faceLabels, labelHashSet &globals) const
Collect cell neighbours of faces in global numbering.
labelList calcFaceCells (const boolList &nonEmptyFace, const labelList &faceLabels, labelHashSet &globals) const
Collect cell neighbours of faces in global numbering.
void calcFaceStencil (const labelListList &globalCellCells, labelListList &faceStencil) const
Collect cell neighbours into extended stencil.
Protected Member Functions inherited from List< labelList >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Member Functions
static void merge (const label global0, const label global1, const labelList &listA, labelList &listB)
Merge two lists.
static void merge (const label globalI, const labelList &pGlobals, labelList &cCells)
Merge two lists and guarantee globalI is first.
Additional Inherited Members
Public Types inherited from List< labelList >
typedef SubList< labelList > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from List< labelList >
static const List< labelList > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Detailed Description
Base class for extended cell-to-face stencils (face values from neighbouring cells)
Source files
cellToFaceStencil.H
faceStencil.C
Definition at line 54 of file cellToFaceStencil.H.
Constructor & Destructor Documentation
cellToFaceStencil (const polyMesh & mesh) explicit
Construct from mesh.
Definition at line 511 of file cellToFaceStencil.C.
Member Function Documentation
void merge (const label global0, const label global1, const labelList & listA, labelList & listB) static protected
Merge two lists.
Guarantee global0, global1 are first.
Definition at line 35 of file cellToFaceStencil.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::findSortedIndex(), forAll, List< T >::size(), Foam::sort(), and List< T >::transfer().
void merge (const label globalI, const labelList & pGlobals, labelList & cCells) static protected
Merge two lists and guarantee globalI is first.
Definition at line 135 of file cellToFaceStencil.C.
References forAll, forAllConstIter(), n, and List< T >::setSize().
void validBoundaryFaces (boolList & isValidBFace) const protected
Valid boundary faces (not empty and not coupled)
Definition at line 169 of file cellToFaceStencil.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), forAll, cellToFaceStencil::mesh(), primitiveMesh::nInternalFaces(), patches, patchi, List< T >::setSize(), and polyPatch::start().
Foam::autoPtr< Foam::indirectPrimitivePatch > allCoupledFacesPatch () const protected
Return patch of all coupled faces.
Definition at line 192 of file cellToFaceStencil.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), forAll, cellToFaceStencil::mesh(), patches, patchi, points, and polyPatch::start().
void insertFaceCells (const label exclude0, const label exclude1, const boolList & nonEmptyFace, const labelList & faceLabels, labelHashSet & globals) const protected
Collect cell neighbours of faces in global numbering.
Definition at line 266 of file cellToFaceStencil.C.
References cellToFaceStencil::calcFaceCells(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, cellToFaceStencil::globalNumbering(), HashSet< Key, Hash >::insert(), cellToFaceStencil::mesh(), primitiveMesh::nInternalFaces(), and globalIndex::toGlobal().
Referenced by cellToFaceStencil::calcFaceCells(), and cellToFaceStencil::unionEqOp::operator()().
Foam::labelList calcFaceCells (const boolList & nonEmptyFace, const labelList & faceLabels, labelHashSet & globals) const protected
Collect cell neighbours of faces in global numbering.
Definition at line 318 of file cellToFaceStencil.C.
References cellToFaceStencil::calcFaceStencil(), HashTable< T, Key, Hash >::clear(), cellToFaceStencil::insertFaceCells(), and HashTable< T, Key, Hash >::toc().
Referenced by cellToFaceStencil::insertFaceCells().
void calcFaceStencil (const labelListList & globalCellCells, labelListList & faceStencil) const protected
Collect cell neighbours into extended stencil.
Definition at line 340 of file cellToFaceStencil.C.
References polyMesh::boundaryMesh(), HashTable< T, Key, Hash >::clear(), polyPatch::coupled(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, forAllConstIter(), HashSet< Key, Hash >::insert(), n, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patches, patchi, List< T >::setSize(), HashTable< T, Key, Hash >::size(), polyPatch::start(), and syncTools::syncBoundaryFaceList().
Referenced by cellToFaceStencil::calcFaceCells(), CECCellToFaceStencil::CECCellToFaceStencil(), CFCCellToFaceStencil::CFCCellToFaceStencil(), and CPCCellToFaceStencil::CPCCellToFaceStencil().
const polyMesh& mesh () const inline
Definition at line 136 of file cellToFaceStencil.H.
Referenced by cellToFaceStencil::allCoupledFacesPatch(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), cellToFaceStencil::insertFaceCells(), and cellToFaceStencil::validBoundaryFaces().
const globalIndex& globalNumbering () const inline
Global numbering for cells and boundary faces.
Definition at line 142 of file cellToFaceStencil.H.
Referenced by extendedCentredCellToFaceStencil::extendedCentredCellToFaceStencil(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), and cellToFaceStencil::insertFaceCells().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/globalIndexStencils/cellToFaceStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToFace/globalIndexStencils/cellToFaceStencil.C