OpenFOAM: cellMDLimitedGrad< Type > Class Template Reference
cellMDLimitedGrad< Type > Class Template Reference
cellMDLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
Public Member Functions
TypeName ("cellMDLimited")
RunTime type information.
cellMDLimitedGrad (const fvMesh &mesh, Istream &schemeData)
Construct from mesh and schemeData.
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
Return the gradient of the given field to the gradScheme::grad.
template<>
void limitFace (vector &g, const scalar &maxDelta, const scalar &minDelta, const vector &dcf)
template<>
tmp< volVectorField > calcGrad (const volScalarField &vsf, const word &name) const
template<>
tmp< volTensorField > calcGrad (const volVectorField &vsf, const word &name) const
template<>
Foam::tmp< Foam::volTensorField > calcGrad (const volVectorField &vsf, const word &name) const
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static void limitFace (typename outerProduct< vector, Type >::type &g, const Type &maxDelta, const Type &minDelta, const vector &dcf)
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::fv::cellMDLimitedGrad< Type >
cellMDLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
The scalar limiter based on limiting the extrapolated face values between the maximum and minimum cell and cell neighbour values and is applied to the gradient in each face direction separately.
Source files
cellMDLimitedGrad.H
cellMDLimitedGrad.C
Definition at line 59 of file cellMDLimitedGrad.H.
Constructor & Destructor Documentation
cellMDLimitedGrad (const fvMesh & mesh, Istream & schemeData) inline
Construct from mesh and schemeData.
Definition at line 89 of file cellMDLimitedGrad.H.
References cellMDLimitedGrad< Type >::calcGrad(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, g, cellMDLimitedGrad< Type >::limitFace(), and Foam::name().
Member Function Documentation
TypeName ("cellMDLimited")
RunTime type information.
void limitFace (typename outerProduct< vector, Type >::type & g, const Type & maxDelta, const Type & minDelta, const vector & dcf) inline static
Definition at line 157 of file cellMDLimitedGrad.H.
References cellMDLimitedGrad< Type >::calcGrad(), VectorSpace< Form, Cmpt, Ncmpts >::component(), Foam::name(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by cellMDLimitedGrad< Type >::cellMDLimitedGrad(), and cellMDLimitedGrad< Type >::limitFace().
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const virtual
Return the gradient of the given field to the gradScheme::grad.
for optional caching
Implements gradScheme< Type >.
Referenced by cellMDLimitedGrad< Type >::cellMDLimitedGrad(), cellMDLimitedGrad< Type >::limitFace(), and makeFvGradScheme().
void limitFace (vector & g, const scalar & maxDelta, const scalar & minDelta, const vector & dcf) inline
Definition at line 135 of file cellMDLimitedGrad.H.
References g, cellMDLimitedGrad< Type >::limitFace(), and Foam::magSqr().
tmp< volVectorField > calcGrad (const volScalarField & vsf, const word & name) const
tmp< volTensorField > calcGrad (const volVectorField & vsf, const word & name) const
Foam::tmp< Foam::volTensorField > calcGrad (const volVectorField & vsf, const word & name) const
Definition at line 186 of file cellMDLimitedGrads.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvMesh::Cf(), correctBoundaryConditions(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), fvPatchField< Type >::coupled(), forAll, g, Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), fvMesh::neighbour(), fvMesh::owner(), patchi, fvPatchField< Type >::patchNeighbourField(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and tmp< T >::ref().
The documentation for this class was generated from the following file:
src/finiteVolume/finiteVolume/gradSchemes/limitedGradSchemes/cellMDLimitedGrad/cellMDLimitedGrad.H