OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
centredCECCellToFaceStencilObject Class Reference
Public Member Functions
TypeName ("centredCECCellToFaceStencil")
centredCECCellToFaceStencilObject (const fvMesh &mesh)
Construct from uncompacted face stencil.
virtual ~centredCECCellToFaceStencilObject ()
Destructor.
Public Member Functions inherited from extendedCentredCellToFaceStencil
extendedCentredCellToFaceStencil (const cellToFaceStencil &)
Construct from uncompacted face stencil.
const mapDistribute & map () const
Return reference to the parallel distribution map.
const labelListList & stencil () const
Return reference to the stencil.
void compact ()
After removing elements from the stencil adapt the schedule (map).
template<class T >
void collectData (const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T >> &stencilFld) const
Use map to get the data into stencil order.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights) const
Sum vol field contributions to create face values.
Public Member Functions inherited from extendedCellToFaceStencil
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type >> &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedCellToFaceStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T >> &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Sum vol field contributions to create face values.
Static Protected Member Functions inherited from extendedCellToFaceStencil
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Write some statistics about stencil.
Protected Attributes inherited from extendedCellToFaceStencil
const polyMesh & mesh_
Detailed Description
Source files
centredCECCellToFaceStencilObject.H
Definition at line 48 of file centredCECCellToFaceStencilObject.H.
Constructor & Destructor Documentation
centredCECCellToFaceStencilObject (const fvMesh & mesh) inline explicit
Construct from uncompacted face stencil.
Definition at line 67 of file centredCECCellToFaceStencilObject.H.
References Foam::endl(), Foam::Info, extendedCentredCellToFaceStencil::map(), Foam::nl, extendedCentredCellToFaceStencil::stencil(), Foam::type(), and extendedCellToFaceStencil::writeStencilStats().
virtual ~centredCECCellToFaceStencilObject () inline virtual
Destructor.
Definition at line 89 of file centredCECCellToFaceStencilObject.H.
Member Function Documentation
TypeName ("centredCECCellToFaceStencil")
The documentation for this class was generated from the following file:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/MeshObjects/centredCECCellToFaceStencilObject.H