OpenFOAM: CentredFitSnGradScheme< Type, Polynomial, Stencil > Class Template Reference
CentredFitSnGradScheme< Type, Polynomial, Stencil > Class Template Reference
Public Member Functions
TypeName ("CentredFitSnGradScheme")
Runtime type information.
CentredFitSnGradScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from snGradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~snGradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the snGrad of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the snGrad of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from snGradScheme< Type >
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
Return the snGrad of the given cell field with the given deltaCoeffs.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Return the sndGrad of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type, class Polynomial, class Stencil>
class Foam::fv::CentredFitSnGradScheme< Type, Polynomial, Stencil >
Definition at line 53 of file CentredFitSnGradScheme.H.
Constructor & Destructor Documentation
CentredFitSnGradScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 86 of file CentredFitSnGradScheme.H.
References CentredFitSnGradScheme< Type, Polynomial, Stencil >::deltaCoeffs().
Member Function Documentation
TypeName ("CentredFitSnGradScheme< Type, Polynomial, Stencil >")
Runtime type information.
virtual tmp<surfaceScalarField> deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors for the given field.
Implements snGradScheme< Type >.
Definition at line 98 of file CentredFitSnGradScheme.H.
References snGradScheme< Type >::mesh(), and surfaceInterpolation::nonOrthDeltaCoeffs().
Referenced by CentredFitSnGradScheme< Type, Polynomial, Stencil >::CentredFitSnGradScheme().
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from snGradScheme< Type >.
Definition at line 106 of file CentredFitSnGradScheme.H.
References CentredFitSnGradScheme< Type, Polynomial, Stencil >::correction().
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the explicit correction to the face-interpolate.
Reimplemented from snGradScheme< Type >.
Definition at line 114 of file CentredFitSnGradScheme.H.
References CentredFitSnGradData< Polynomial >::coeffs(), Foam::dimLength, snGradScheme< Type >::mesh(), Foam::New(), tmp< T >::ref(), and extendedCentredCellToFaceStencil::weightedSum().
Referenced by CentredFitSnGradScheme< Type, Polynomial, Stencil >::corrected().
The documentation for this class was generated from the following file:
src/finiteVolume/finiteVolume/snGradSchemes/CentredFitSnGrad/CentredFitSnGradScheme.H