OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CloudFunctionObject< CloudType > Class Template Reference
Templated cloud function object base class.
Public Member Functions
TypeName ("cloudFunctionObject")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
Declare runtime constructor selection table.
CloudFunctionObject (CloudType &owner)
Construct null from owner.
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Construct from dictionary.
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
Construct copy.
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
Construct and return a clone.
virtual ~CloudFunctionObject ()
Destructor.
virtual void preEvolve ()
Pre-evolve hook.
virtual void postEvolve ()
Post-evolve hook.
virtual void postMove (typename CloudType::parcelType &p, const label cellI, const scalar dt, const point &position0, bool &keepParticle)
Post-move hook.
virtual void postPatch (const typename CloudType::parcelType &p, const polyPatch &pp, const scalar trackFraction, const tetIndices &testIs, bool &keepParticle)
Post-patch hook.
virtual void postFace (const typename CloudType::parcelType &p, const label faceI, bool &keepParticle)
Post-face hook.
const fileName & outputDir () const
Return the output path.
fileName outputTimeDir () const
Return the output time path.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Selector.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::CloudFunctionObject< CloudType >
Templated cloud function object base class.
Source files
CloudFunctionObject.H
CloudFunctionObject.C
CloudFunctionObjectNew.C
Definition at line 56 of file CloudFunctionObject.H.
Constructor & Destructor Documentation
CloudFunctionObject (CloudType & owner)
Construct null from owner.
Definition at line 40 of file CloudFunctionObject.C.
Referenced by CloudFunctionObject< CloudType >::CloudFunctionObject().
CloudFunctionObject (const dictionary & dict, CloudType & owner, const word & objectType, const word & modelName)
Construct from dictionary.
Definition at line 49 of file CloudFunctionObject.C.
References CloudFunctionObject< CloudType >::CloudFunctionObject(), subModelBase::modelName(), UPstream::parRun(), and cloud::prefix.
CloudFunctionObject (const CloudFunctionObject< CloudType > & ppm)
Construct copy.
Definition at line 78 of file CloudFunctionObject.C.
~CloudFunctionObject () virtual
Destructor.
Definition at line 90 of file CloudFunctionObject.C.
Referenced by CloudFunctionObject< CloudType >::clone().
Member Function Documentation
TypeName ("cloudFunctionObject")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , CloudFunctionObject< CloudType > , dictionary , (const dictionary &dict, CloudType &owner, const word &modelName) , (dict, owner, modelName))
Declare runtime constructor selection table.
virtual autoPtr<CloudFunctionObject<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented in ParticleCollector< CloudType >, FacePostProcessing< CloudType >, ParticleErosion< CloudType >, ParticleTracks< CloudType >, ParticleTrap< CloudType >, PatchPostProcessing< CloudType >, and VoidFraction< CloudType >.
Definition at line 113 of file CloudFunctionObject.H.
References CloudFunctionObject< CloudType >::New(), CloudFunctionObject< CloudType >::outputDir(), CloudFunctionObject< CloudType >::outputTimeDir(), p, CloudFunctionObject< CloudType >::postEvolve(), CloudFunctionObject< CloudType >::postFace(), CloudFunctionObject< CloudType >::postMove(), CloudFunctionObject< CloudType >::postPatch(), CloudFunctionObject< CloudType >::preEvolve(), and CloudFunctionObject< CloudType >::~CloudFunctionObject().
Foam::autoPtr< Foam::CloudFunctionObject< CloudType > > New (const dictionary & dict, CloudType & owner, const word & objectType, const word & modelName) static
Selector.
Definition at line 33 of file CloudFunctionObjectNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, and Foam::nl.
Referenced by CloudFunctionObject< CloudType >::clone().
void preEvolve () virtual
Pre-evolve hook.
Reimplemented in ParticleTracks< CloudType >, ParticleErosion< CloudType >, ParticleTrap< CloudType >, and VoidFraction< CloudType >.
Definition at line 97 of file CloudFunctionObject.C.
Referenced by CloudFunctionObject< CloudType >::clone().
void postEvolve () virtual
Post-evolve hook.
Reimplemented in ParticleTrap< CloudType >, and VoidFraction< CloudType >.
Definition at line 104 of file CloudFunctionObject.C.
References CloudSubModelBase< CloudType >::outputTime(), CloudSubModelBase< CloudType >::owner(), and CloudFunctionObject< CloudType >::postMove().
Referenced by CloudFunctionObject< CloudType >::clone().
void postMove (typename CloudType::parcelType & p, const label cellI, const scalar dt, const point & position0, bool & keepParticle) virtual
Post-move hook.
Reimplemented in ParticleCollector< CloudType >, ParticleTrap< CloudType >, and VoidFraction< CloudType >.
Definition at line 115 of file CloudFunctionObject.C.
References CloudFunctionObject< CloudType >::postPatch().
Referenced by CloudFunctionObject< CloudType >::clone(), and CloudFunctionObject< CloudType >::postEvolve().
void postPatch (const typename CloudType::parcelType & p, const polyPatch & pp, const scalar trackFraction, const tetIndices & testIs, bool & keepParticle) virtual
Post-patch hook.
Definition at line 129 of file CloudFunctionObject.C.
References CloudFunctionObject< CloudType >::postFace().
Referenced by CloudFunctionObject< CloudType >::clone(), and CloudFunctionObject< CloudType >::postMove().
void postFace (const typename CloudType::parcelType & p, const label faceI, bool & keepParticle) virtual
Post-face hook.
Definition at line 143 of file CloudFunctionObject.C.
Referenced by CloudFunctionObject< CloudType >::clone(), and CloudFunctionObject< CloudType >::postPatch().
const Foam::fileName & outputDir () const
Return the output path.
Definition at line 154 of file CloudFunctionObject.C.
Referenced by CloudFunctionObject< CloudType >::clone().
Foam::fileName outputTimeDir () const
Return the output time path.
Definition at line 161 of file CloudFunctionObject.C.
References CloudSubModelBase< CloudType >::owner(), objectRegistry::time(), and Time::timeName().
Referenced by CloudFunctionObject< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObject/CloudFunctionObject.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObject/CloudFunctionObject.C
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObject/CloudFunctionObjectNew.C