OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CloudFunctionObjectList< CloudType > Class Template Reference
List of cloud function objects.
Public Member Functions
CloudFunctionObjectList (CloudType &owner)
Null constructor.
CloudFunctionObjectList (CloudType &owner, const dictionary &dict, const bool readFields)
Construct from mesh.
CloudFunctionObjectList (const CloudFunctionObjectList &ppml)
Construct copy.
virtual ~CloudFunctionObjectList ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const dictionary & dict () const
Return the forces dictionary.
virtual void preEvolve ()
Pre-evolve hook.
virtual void postEvolve ()
Post-evolve hook.
virtual void postMove (typename CloudType::parcelType &p, const label celli, const scalar dt, const point &position0, bool &keepParticle)
Post-move hook.
virtual void postPatch (const typename CloudType::parcelType &p, const polyPatch &pp, const scalar trackFraction, const tetIndices &tetIs, bool &keepParticle)
Post-patch hook.
virtual void postFace (const typename CloudType::parcelType &p, const label facei, bool &keepParticle)
Post-face hook.
Public Member Functions inherited from PtrList< CloudFunctionObject< CloudType > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< CloudFunctionObject< CloudType > > &)
Copy constructor.
PtrList (const PtrList< CloudFunctionObject< CloudType > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< CloudFunctionObject< CloudType > >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< CloudFunctionObject< CloudType > > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< CloudFunctionObject< CloudType > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (CloudFunctionObject< CloudType > *)
Append an element at the end of the list.
void append (const autoPtr< CloudFunctionObject< CloudType > > &)
void append (const tmp< CloudFunctionObject< CloudType > > &)
void transfer (PtrList< CloudFunctionObject< CloudType > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< CloudFunctionObject< CloudType > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< CloudFunctionObject< CloudType > > set (const label, CloudFunctionObject< CloudType > *)
Set element to given T* and return old element (can be NULL)
autoPtr< CloudFunctionObject< CloudType > > set (const label, const autoPtr< CloudFunctionObject< CloudType > > &)
Set element to given autoPtr<T> and return old element.
autoPtr< CloudFunctionObject< CloudType > > set (const label, const tmp< CloudFunctionObject< CloudType > > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< CloudFunctionObject< CloudType > > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Attributes
const CloudType & owner_
Reference to the owner cloud.
const dictionary dict_
Dictionary.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< CloudFunctionObject< CloudType > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
template<class CloudType>
class Foam::CloudFunctionObjectList< CloudType >
List of cloud function objects.
Source files
CloudFunctionObjectList.H
CloudFunctionObjectListI.H
CloudFunctionObjectList.C
Definition at line 51 of file CloudFunctionObjectList.H.
Constructor & Destructor Documentation
CloudFunctionObjectList (CloudType & owner)
Null constructor.
Definition at line 33 of file CloudFunctionObjectList.C.
Referenced by CloudFunctionObjectList< CloudType >::CloudFunctionObjectList().
CloudFunctionObjectList (CloudType & owner, const dictionary & dict, const bool readFields)
Construct from mesh.
Definition at line 45 of file CloudFunctionObjectList.C.
References CloudFunctionObjectList< CloudType >::CloudFunctionObjectList(), Foam::endl(), forAll, Foam::Info, Foam::New(), setSize(), dictionary::subDict(), and dictionary::toc().
CloudFunctionObjectList (const CloudFunctionObjectList< CloudType > & ppml)
Construct copy.
Definition at line 97 of file CloudFunctionObjectList.C.
~CloudFunctionObjectList () virtual
Destructor.
Definition at line 110 of file CloudFunctionObjectList.C.
Member Function Documentation
const CloudType & owner () const inline
Return const access to the cloud owner.
Definition at line 27 of file CloudFunctionObjectListI.H.
CloudType & owner () inline
Return refernce to the cloud owner.
Definition at line 34 of file CloudFunctionObjectListI.H.
const Foam::dictionary & dict () const inline
Return the forces dictionary.
Definition at line 42 of file CloudFunctionObjectListI.H.
void preEvolve () virtual
Pre-evolve hook.
Definition at line 117 of file CloudFunctionObjectList.C.
References forAll.
void postEvolve () virtual
Post-evolve hook.
Definition at line 127 of file CloudFunctionObjectList.C.
References forAll, and CloudFunctionObjectList< CloudType >::postMove().
void postMove (typename CloudType::parcelType & p, const label celli, const scalar dt, const point & position0, bool & keepParticle) virtual
Post-move hook.
Definition at line 138 of file CloudFunctionObjectList.C.
References forAll, and CloudFunctionObjectList< CloudType >::postPatch().
Referenced by CloudFunctionObjectList< CloudType >::postEvolve().
void postPatch (const typename CloudType::parcelType & p, const polyPatch & pp, const scalar trackFraction, const tetIndices & tetIs, bool & keepParticle) virtual
Post-patch hook.
Definition at line 160 of file CloudFunctionObjectList.C.
References forAll, and CloudFunctionObjectList< CloudType >::postFace().
Referenced by CloudFunctionObjectList< CloudType >::postMove().
void postFace (const typename CloudType::parcelType & p, const label facei, bool & keepParticle) virtual
Post-face hook.
Definition at line 189 of file CloudFunctionObjectList.C.
References forAll.
Referenced by CloudFunctionObjectList< CloudType >::postPatch().
Member Data Documentation
const CloudType& owner_ protected
Reference to the owner cloud.
Definition at line 60 of file CloudFunctionObjectList.H.
const dictionary dict_ protected
Dictionary.
Definition at line 63 of file CloudFunctionObjectList.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObjectList/CloudFunctionObjectList.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObjectList/CloudFunctionObjectList.C
src/lagrangian/intermediate/submodels/CloudFunctionObjects/CloudFunctionObjectList/CloudFunctionObjectListI.H