OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellToFace Class Reference
A topoSetSource to select a faceSet from cells.
Public Types
enum cellAction { ALL, BOTH }
Enumeration defining the valid options.
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Public Member Functions
TypeName ("cellToFace")
Runtime type information.
cellToFace (const polyMesh &mesh, const word &setName, const cellAction option)
Construct from components.
cellToFace (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
cellToFace (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~cellToFace ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label celli, const bool) const
Add (if bool) celli to set or delete celli from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = NULL
A table of usage strings.
Detailed Description
A topoSetSource to select a faceSet from cells.
Either all faces of cell or some other criterion. See implementation. Note: when picking up coupled faces uses cells on neighbouring processors.
Source files
cellToFace.H
cellToFace.C
Definition at line 53 of file cellToFace.H.
Member Enumeration Documentation
enum cellAction
Enumeration defining the valid options.
Enumerator
ALL
BOTH
Definition at line 59 of file cellToFace.H.
Constructor & Destructor Documentation
cellToFace (const polyMesh & mesh, const word & setName, const cellAction option)
Construct from components.
Definition at line 159 of file cellToFace.C.
Referenced by cellToFace::cellToFace(), and NamedEnum< Enum, nEnum >::names().
cellToFace (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 173 of file cellToFace.C.
References cellToFace::cellToFace().
cellToFace (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 186 of file cellToFace.C.
~cellToFace () virtual
Destructor.
Definition at line 199 of file cellToFace.C.
References cellToFace::applyToSet().
Member Function Documentation
TypeName ("cellToFace")
Runtime type information.
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 122 of file cellToFace.H.
References cellToFace::applyToSet(), and topoSetSource::FACESETSOURCE.
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 206 of file cellToFace.C.
References topoSetSource::ADD, Foam::ListListOps::combine(), topoSetSource::DELETE, Foam::endl(), Foam::Info, and topoSetSource::NEW.
Referenced by cellToFace::setType(), and cellToFace::~cellToFace().
The documentation for this class was generated from the following files:
src/meshTools/sets/faceSources/cellToFace/cellToFace.H
src/meshTools/sets/faceSources/cellToFace/cellToFace.C