OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
circulator< ContainerType > Class Template Reference
Walks over a container as if it were circular. The container must have the following members defined:
Public Types
typedef ContainerType::value_type value_type
Type of values ContainerType contains.
typedef ContainerType::size_type size_type
The type that can represent the size of ContainerType.
typedef
ContainerType::difference_type difference_type
The type that can represent the difference between any two.
typedef ContainerType::iterator iterator
Random access iterator for traversing ContainerType.
typedef ContainerType::reference reference
Type that can be used for storing into.
Public Types inherited from CirculatorBase
enum direction { NONE, CLOCKWISE, ANTICLOCKWISE }
Direction type enumeration.
Public Member Functions
circulator ()
Construct null.
circulator (ContainerType &container)
Construct from a container.
circulator (const iterator &begin, const iterator &end)
Construct from two iterators.
circulator (const circulator< ContainerType > &)
Construct as copy.
~circulator ()
Destructor.
size_type size () const
Return the range of the iterator.
bool circulate (const CirculatorBase::direction dir=NONE)
Circulate around the list in the given direction.
void setFulcrumToIterator ()
Set the fulcrum to the current position of the iterator.
void setIteratorToFulcrum ()
Set the iterator to the current position of the fulcrum.
difference_type nRotations () const
Return the distance between the iterator and the fulcrum. This is.
reference next () const
Dereference the next iterator and return.
reference prev () const
Dereference the previous iterator and return.
void operator= (const circulator< ContainerType > &)
Assignment operator for circulators that operate on the same.
circulator< ContainerType > & operator++ ()
Prefix increment. Increments the iterator.
circulator< ContainerType > operator++ (int)
Postfix increment. Increments the iterator.
circulator< ContainerType > & operator-- ()
Prefix decrement. Decrements the iterator.
circulator< ContainerType > operator-- (int)
Postfix decrement. Decrements the iterator.
bool operator== (const circulator< ContainerType > &c) const
Check for equality of this iterator with another iterator that.
bool operator!= (const circulator< ContainerType > &c) const
Check for inequality of this iterator with another iterator that.
reference operator* () const
Dereference the iterator and return.
reference operator() () const
Dereference the iterator and return.
difference_type operator- (const circulator< ContainerType > &c) const
Return the difference between this iterator and another iterator.
Public Member Functions inherited from CirculatorBase
CirculatorBase ()
Construct null.
Protected Attributes
ContainerType::iterator begin_
Iterator pointing to the beginning of the container.
ContainerType::iterator end_
Iterator pointing to the end of the container.
ContainerType::iterator iter_
Random access iterator for traversing ContainerType.
ContainerType::iterator fulcrum_
Iterator holding the location of the fulcrum (start and end) of.
Detailed Description
template<class ContainerType>
class Foam::circulator< ContainerType >
Walks over a container as if it were circular. The container must have the following members defined:
- value_type
size_type
difference_type
iterator
reference
Examples
face f(identity(5));
// Construct circulator from the face
circulator<face> circ(f);
// First check that the circulator has a size to iterate over.
// Then circulate around the list starting and finishing at the fulcrum.
if (circ.size()) do
{
    circ() += 1;
    Info<< "Iterate forwards over face : " << circ() << endl;
} while (circ.circulate(CirculatorBase::CLOCKWISE));
Source files
circulator.H
circulatorI.H
Definition at line 75 of file circulator.H.
Member Typedef Documentation
typedef ContainerType::value_type value_type
Type of values ContainerType contains.
Definition at line 104 of file circulator.H.
typedef ContainerType::size_type size_type
The type that can represent the size of ContainerType.
Definition at line 107 of file circulator.H.
typedef ContainerType::difference_type difference_type
The type that can represent the difference between any two.
iterator objects.
Definition at line 111 of file circulator.H.
typedef ContainerType::iterator iterator
Random access iterator for traversing ContainerType.
Definition at line 114 of file circulator.H.
typedef ContainerType::reference reference
Type that can be used for storing into.
ContainerType::value_type objects.
Definition at line 118 of file circulator.H.
Constructor & Destructor Documentation
circulator () inline
Construct null.
Definition at line 29 of file circulatorI.H.
circulator (ContainerType & container) inline explicit
Construct from a container.
Definition at line 40 of file circulatorI.H.
circulator (const iterator & begin, const iterator & end) inline
Construct from two iterators.
Definition at line 52 of file circulatorI.H.
circulator (const circulator< ContainerType > & rhs) inline
Construct as copy.
Definition at line 67 of file circulatorI.H.
~circulator ()
Destructor.
Definition at line 82 of file circulatorI.H.
Member Function Documentation
Foam::circulator< ContainerType >::size_type size () const inline
Return the range of the iterator.
Definition at line 90 of file circulatorI.H.
bool circulate (const CirculatorBase::direction dir = NONE) inline
Circulate around the list in the given direction.
Definition at line 98 of file circulatorI.H.
References CirculatorBase::ANTICLOCKWISE, and CirculatorBase::CLOCKWISE.
void setFulcrumToIterator () inline
Set the fulcrum to the current position of the iterator.
Definition at line 116 of file circulatorI.H.
void setIteratorToFulcrum () inline
Set the iterator to the current position of the fulcrum.
Definition at line 123 of file circulatorI.H.
Foam::circulator< ContainerType >::difference_type nRotations () const inline
Return the distance between the iterator and the fulcrum. This is.
equivalent to the number of rotations of the circulator.
Definition at line 131 of file circulatorI.H.
Foam::circulator< ContainerType >::reference next () const inline
Dereference the next iterator and return.
Definition at line 139 of file circulatorI.H.
Foam::circulator< ContainerType >::reference prev () const inline
Dereference the previous iterator and return.
Definition at line 152 of file circulatorI.H.
void operator= (const circulator< ContainerType > & rhs) inline
Assignment operator for circulators that operate on the same.
container type
Definition at line 167 of file circulatorI.H.
References Foam::abort(), circulator< ContainerType >::begin_, circulator< ContainerType >::end_, Foam::FatalError, FatalErrorIn, circulator< ContainerType >::fulcrum_, and circulator< ContainerType >::iter_.
Foam::circulator< ContainerType > & operator++ () inline
Prefix increment. Increments the iterator.
Sets the iterator to the beginning of the container if it reaches the end
Definition at line 191 of file circulatorI.H.
Foam::circulator< ContainerType > operator++ (int) inline
Postfix increment. Increments the iterator.
Sets the iterator to the beginning of the container if it reaches the end
Definition at line 205 of file circulatorI.H.
Foam::circulator< ContainerType > & operator-- () inline
Prefix decrement. Decrements the iterator.
Sets the iterator to the end of the container if it reaches the beginning
Definition at line 215 of file circulatorI.H.
Foam::circulator< ContainerType > operator-- (int) inline
Postfix decrement. Decrements the iterator.
Sets the iterator to the end of the container if it reaches the beginning
Definition at line 229 of file circulatorI.H.
bool operator== (const circulator< ContainerType > & c) const inline
Check for equality of this iterator with another iterator that.
operate on the same container type
Definition at line 239 of file circulatorI.H.
References c().
bool operator!= (const circulator< ContainerType > & c) const inline
Check for inequality of this iterator with another iterator that.
operate on the same container type
Definition at line 255 of file circulatorI.H.
References c().
Foam::circulator< ContainerType >::reference operator* () const inline
Dereference the iterator and return.
Definition at line 265 of file circulatorI.H.
Foam::circulator< ContainerType >::reference operator() () const inline
Dereference the iterator and return.
Definition at line 273 of file circulatorI.H.
References Foam::operator*().
Foam::circulator< ContainerType >::difference_type operator- (const circulator< ContainerType > & c) const inline
Return the difference between this iterator and another iterator.
that operate on the same container type
Definition at line 282 of file circulatorI.H.
References c().
Member Data Documentation
ContainerType::iterator begin_ protected
Iterator pointing to the beginning of the container.
Definition at line 85 of file circulator.H.
Referenced by circulator< ContainerType >::operator=().
ContainerType::iterator end_ protected
Iterator pointing to the end of the container.
Definition at line 88 of file circulator.H.
Referenced by circulator< ContainerType >::operator=().
ContainerType::iterator iter_ protected
Random access iterator for traversing ContainerType.
Definition at line 91 of file circulator.H.
Referenced by circulator< ContainerType >::operator=().
ContainerType::iterator fulcrum_ protected
Iterator holding the location of the fulcrum (start and end) of.
the container. Used to decide when the iterator should stop circulating over the container
Definition at line 96 of file circulator.H.
Referenced by circulator< ContainerType >::operator=().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Circulators/circulator/circulator.H
src/OpenFOAM/containers/Circulators/circulator/circulatorI.H