OpenFOAM: cellTable Class Reference
cellTable Class Reference
The cellTable persistent data saved as a Map<dictionary>.
Public Member Functions
cellTable ()
Construct null.
cellTable (const objectRegistry &, const word &name="cellTable", const fileName &instance="constant")
Construct read from registry, name. instance.
~cellTable ()
Destructor.
label append (const dictionary &)
Append to the end, return index.
label findIndex (const word &name) const
Return index corresponding to name.
word name (const label id) const
Return the name corresponding to id.
Map< word > names () const
Return a Map of (id => name)
Map< word > names (const UList< wordRe > &patterns) const
Return a Map of (id => names) selected by patterns.
Map< word > selectType (const word &materialType) const
Return a Map of (id => name) for materialType.
Map< word > fluids () const
Return a Map of (id => name) for fluids.
Map< word > shells () const
Return a Map of (id => name) for shells.
Map< word > solids () const
Return a Map of (id => name) for solids.
Map< word > materialTypes () const
Return a Map of (id => fluid|solid|shell)
void setMaterial (const label, const word &)
Assign material Type.
void setName (const label, const word &)
Assign name.
void setName (const label)
Assign default name if not already set.
void readDict (const objectRegistry &, const word &name="cellTable", const fileName &instance="constant")
Read constant/cellTable.
void writeDict (const objectRegistry &, const word &name="cellTable", const fileName &instance="constant") const
Write constant/cellTable for later reuse.
void operator= (const cellTable &)
Assignment.
void operator= (const Map< dictionary > &)
Assign from Map<dictionary>
void operator= (const polyMesh &)
Assign from cellZones.
void addCellZones (polyMesh &, const labelList &tableIds) const
Classify tableIds into cellZones according to the cellTable.
void combine (const dictionary &, labelList &tableIds)
Combine tableIds together.
Public Member Functions inherited from Map< dictionary >
Map (const label size=128)
Construct given initial size.
Map (Istream &is)
Construct from Istream.
Map (const Map< dictionary > &map)
Construct as copy.
Map (const Xfer< Map< dictionary >> &map)
Construct by transferring the parameter contents.
Map (const Xfer< HashTable< dictionary, label, Hash< label >>> &map)
Construct by transferring the parameter contents.
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< T, Key, Hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< T, Key, Hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< Key, T >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const Key &) const
Return true if hashedEntry is found in table.
iterator find (const Key &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const Key &) const
Find and return an const_iterator set at the hashedEntry.
List< Key > toc () const
Return the table of contents.
List< Key > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const Key &, const T &newElmt)
Insert a new hashedEntry.
bool set (const Key &, const T &newElmt)
Assign a new hashedEntry, overwriting existing entries.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const Key &)
Erase a hashedEntry specified by the given key.
label erase (const UList< Key > &)
Remove entries given by the listed keys from this HashTable.
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< T, Key, Hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< T, Key, Hash > > xfer ()
Transfer contents to the Xfer container.
T & operator[] (const Key &)
Find and return a hashedEntry.
const T & operator[] (const Key &) const
Find and return a hashedEntry.
T & operator() (const Key &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< T, Key, Hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< Key, T >>)
Assignment to an initializer list.
bool operator== (const HashTable< T, Key, Hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< T, Key, Hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &rhs)
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Public Types inherited from Map< dictionary >
typedef HashTable< dictionary, label, Hash< label > >::iterator iterator
typedef HashTable< dictionary, label, Hash< label > >::const_iterator const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef T value_type
Type of values the HashTable contains.
typedef T & reference
Type that can be used for storing into HashTable::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Detailed Description
The cellTable persistent data saved as a Map<dictionary>.
The meshReader supports cellTable information.
The constant/cellTable file is an IOMap<dictionary> that is used to save the information persistently. It contains the cellTable information of the following form:
    (
        ID
        {
            Label           WORD;
            MaterialType    WORD;
            MaterialId      INT;
            PorosityId      INT;
            ColorIdx        INT;
            ...
        }
    ...
    )
If the Label is missing, a value cellTable_{ID} will be inferred. If the MaterialType is missing, the value fluid will be inferred.
Source files
cellTable.H
cellTable.C
Definition at line 77 of file cellTable.H.
Constructor & Destructor Documentation
cellTable ()
Construct null.
Definition at line 103 of file cellTable.C.
cellTable (const objectRegistry & registry, const word & name = "cellTable", const fileName & instance = "constant")
Construct read from registry, name. instance.
Definition at line 110 of file cellTable.C.
References cellTable::readDict().
~cellTable ()
Destructor.
Definition at line 124 of file cellTable.C.
Member Function Documentation
Foam::label append (const dictionary & dict)
Append to the end, return index.
Definition at line 130 of file cellTable.C.
References forAllConstIter(), and HashTable< T, Key, Hash >::insert().
Foam::label findIndex (const word & name) const
Return index corresponding to name.
returns -1 if not found
Definition at line 206 of file cellTable.C.
References forAllConstIter(), and word::null.
Referenced by cellTable::combine().
Foam::word name (const label id) const
Return the name corresponding to id.
returns cellTable_ID if not otherwise defined
Definition at line 192 of file cellTable.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::find(), and Foam::name().
Foam::Map< Foam::word > names () const
Return a Map of (id => name)
Definition at line 146 of file cellTable.C.
References forAllConstIter(), HashTable< T, label, Hash< label > >::insert(), lookup(), and Foam::name().
Referenced by cellTable::combine().
Foam::Map< Foam::word > names (const UList< wordRe > & patterns) const
Return a Map of (id => names) selected by patterns.
Definition at line 168 of file cellTable.C.
References Foam::findStrings(), forAllConstIter(), HashTable< T, label, Hash< label > >::insert(), lookup(), and Foam::name().
Foam::Map< Foam::word > selectType (const word & materialType) const
Return a Map of (id => name) for materialType.
(fluid | solid | shell)
Definition at line 242 of file cellTable.C.
References forAllConstIter(), HashTable< T, label, Hash< label > >::insert(), lookup(), and Foam::name().
Referenced by cellTable::fluids(), cellTable::shells(), and cellTable::solids().
Foam::Map< Foam::word > fluids () const
Return a Map of (id => name) for fluids.
Definition at line 270 of file cellTable.C.
References cellTable::selectType().
Foam::Map< Foam::word > shells () const
Return a Map of (id => name) for shells.
Definition at line 282 of file cellTable.C.
References cellTable::selectType().
Foam::Map< Foam::word > solids () const
Return a Map of (id => name) for solids.
Definition at line 276 of file cellTable.C.
References cellTable::selectType().
Foam::Map< Foam::word > materialTypes () const
Return a Map of (id => fluid|solid|shell)
Definition at line 225 of file cellTable.C.
References forAllConstIter(), HashTable< T, label, Hash< label > >::insert(), and lookup().
void setMaterial (const label id, const word & matlType)
Assign material Type.
Definition at line 289 of file cellTable.C.
Referenced by STARCD::readCells().
void setName (const label id, const word & name)
Assign name.
Definition at line 295 of file cellTable.C.
Referenced by STARCD::readCells(), and cellTable::setName().
void setName (const label id)
Assign default name if not already set.
Definition at line 301 of file cellTable.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::find(), HashTable< T, Key, Hash >::found(), Foam::name(), cellTable::readDict(), and cellTable::setName().
void readDict (const objectRegistry & registry, const word & name = "cellTable", const fileName & instance = "constant")
Read constant/cellTable.
Definition at line 313 of file cellTable.C.
References HashTable< T, Key, Hash >::clear(), Foam::endl(), IOobject::headerOk(), Foam::Info, IOobject::NO_WRITE, IOobject::READ_IF_PRESENT, and cellTable::writeDict().
Referenced by cellTable::cellTable(), STARCD::readAux(), cellTable::setName(), and STARCD::STARCD().
void writeDict (const objectRegistry & registry, const word & name = "cellTable", const fileName & instance = "constant") const
Write constant/cellTable for later reuse.
Definition at line 348 of file cellTable.C.
References Foam::endl(), Foam::Info, IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, IOobject::note(), IOobject::objectPath(), and IOobject::writeHeader().
Referenced by cellTable::readDict(), and meshReader::writeAux().
void operator= (const cellTable & rhs)
Assignment.
Definition at line 381 of file cellTable.C.
References HashTable< T, label, Hash< label > >::operator=().
void operator= (const Map< dictionary > & rhs)
Assign from Map<dictionary>
Definition at line 388 of file cellTable.C.
References HashTable< T, label, Hash< label > >::operator=().
void operator= (const polyMesh & mesh)
Assign from cellZones.
Definition at line 395 of file cellTable.C.
References dictionary::add(), cellTable::addCellZones(), polyMesh::cellZones(), HashTable< T, Key, Hash >::clear(), dict, forAll, HashTable< T, Key, Hash >::insert(), ZoneMesh< ZoneType, MeshType >::names(), primitiveMesh::nCells(), HashTable< T, label, Hash< label > >::operator=(), and List< T >::size().
void addCellZones (polyMesh & mesh, const labelList & tableIds) const
Classify tableIds into cellZones according to the cellTable.
Definition at line 441 of file cellTable.C.
References List< T >::append(), IOobject::AUTO_WRITE, polyMesh::cellZones(), ZoneMesh< ZoneType, MeshType >::clear(), HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, Foam::Info, PtrList< T >::set(), PtrList< T >::setSize(), List< T >::setSize(), List< T >::size(), HashTable< T, Key, Hash >::size(), and IOobject::writeOpt().
Referenced by cellTable::operator=().
void combine (const dictionary & mapDict, labelList & tableIds)
Combine tableIds together.
each dictionary entry is a wordList
Definition at line 507 of file cellTable.C.
References Foam::endl(), HashTable< T, label, Hash< label > >::erase(), HashTable< T, Key, Hash >::erase(), cellTable::findIndex(), Foam::findStrings(), forAllConstIter(), Foam::identity(), Foam::Info, Foam::inplaceRenumber(), HashTable< T, label, Hash< label > >::insert(), Foam::max(), Foam::min(), cellTable::names(), HashTable< T, Key, Hash >::operator[](), HashTable< T, label, Hash< label > >::size(), and HashTable< T, label, Hash< label > >::toc().
The documentation for this class was generated from the following files:
src/conversion/meshTables/cellTable.H
src/conversion/meshTables/cellTable.C