OpenFOAM: CloudSubModelBase< CloudType > Class Template Reference
CloudSubModelBase< CloudType > Class Template Reference
Base class for cloud sub-models.
Public Types
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Public Member Functions
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Attributes
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Detailed Description
template<class CloudType>
class Foam::CloudSubModelBase< CloudType >
Base class for cloud sub-models.
Source files
CloudSubModelBase.H
CloudSubModelBase.C
Definition at line 49 of file CloudSubModelBase.H.
Member Typedef Documentation
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Definition at line 96 of file CloudSubModelBase.H.
Constructor & Destructor Documentation
CloudSubModelBase (CloudType & owner)
Construct null from owner cloud.
Definition at line 31 of file CloudSubModelBase.C.
Referenced by CloudSubModelBase< CloudType >::CloudSubModelBase().
CloudSubModelBase (CloudType & owner, const dictionary & dict, const word & baseName, const word & modelType, const word & dictExt = "Coeffs")
Construct from owner cloud without name.
Definition at line 40 of file CloudSubModelBase.C.
References CloudSubModelBase< CloudType >::CloudSubModelBase().
CloudSubModelBase (const word & modelName, CloudType & owner, const dictionary & dict, const word & baseName, const word & modelType)
Construct from owner cloud with name.
Definition at line 62 of file CloudSubModelBase.C.
References CloudSubModelBase< CloudType >::CloudSubModelBase().
CloudSubModelBase (const CloudSubModelBase< CloudType > & smb)
Construct as copy.
Definition at line 84 of file CloudSubModelBase.C.
~CloudSubModelBase () virtual
Destructor.
Definition at line 96 of file CloudSubModelBase.C.
Member Function Documentation
const CloudType & owner () const
Return const access to the owner cloud.
Definition at line 103 of file CloudSubModelBase.C.
References CloudSubModelBase< CloudType >::owner_.
Referenced by InjectionModel< CloudType >::averageParcelMass(), Rebound< CloudType >::correct(), SurfaceFilmModel< CloudType >::inject(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), IsotropyModel< CloudType >::New(), DampingModel< CloudType >::New(), PackingModel< CloudType >::New(), CloudFunctionObject< CloudType >::postEvolve(), ReitzKHRT< CloudType >::update(), TAB< CloudType >::update(), SHF< CloudType >::update(), and CloudFunctionObject< CloudType >::writeTimeDir().
bool writeTime () const virtual
Flag to indicate when to write a property.
Reimplemented from subModelBase.
Definition at line 117 of file CloudSubModelBase.C.
References subModelBase::active(), IOobject::db(), CloudSubModelBase< CloudType >::owner_, objectRegistry::time(), and TimeState::writeTime().
Referenced by SurfaceFilmModel< CloudType >::info(), InjectionModel< CloudType >::info(), and CloudFunctionObject< CloudType >::postEvolve().
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
Definition at line 110 of file CloudSubModelBase.C.
References CloudSubModelBase< CloudType >::owner_.
void write (Ostream & os) const virtual
Write.
Reimplemented from subModelBase.
Reimplemented in DispersionRASModel< CloudType >.
Definition at line 127 of file CloudSubModelBase.C.
References token::END_STATEMENT, IOobject::name(), Foam::nl, CloudSubModelBase< CloudType >::owner_, subModelBase::write(), and Ostream::writeKeyword().
Member Data Documentation
CloudType& owner_ protected
Reference to the cloud.
Definition at line 58 of file CloudSubModelBase.H.
Referenced by CloudSubModelBase< CloudType >::owner(), CloudSubModelBase< CloudType >::write(), and CloudSubModelBase< CloudType >::writeTime().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudSubModelBase.H
src/lagrangian/intermediate/submodels/CloudSubModelBase.C