OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CollisionModel< CloudType > Class Template Reference abstract
Templated collision model class.
Public Member Functions
TypeName ("collisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
CollisionModel (CloudType &owner)
Construct null from owner.
CollisionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
CollisionModel (const CollisionModel< CloudType > &cm)
Construct copy.
virtual autoPtr< CollisionModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~CollisionModel ()
Destructor.
virtual label nSubCycles () const =0
Return the number of times to subcycle the current.
virtual bool controlsWallInteraction () const =0
Indicates whether model determines wall collisions or not,.
virtual void collide ()=0
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< CollisionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::CollisionModel< CloudType >
Templated collision model class.
Source files
CollisionModel.H
CollisionModel.C
CollisionModelNew.C
Definition at line 53 of file CollidingCloud.H.
Constructor & Destructor Documentation
CollisionModel (CloudType & owner)
Construct null from owner.
Definition at line 31 of file CollisionModel.C.
Referenced by CollisionModel< CloudType >::CollisionModel().
CollisionModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from components.
Definition at line 39 of file CollisionModel.C.
References CollisionModel< CloudType >::CollisionModel().
CollisionModel (const CollisionModel< CloudType > & cm)
Construct copy.
Definition at line 51 of file CollisionModel.C.
~CollisionModel () virtual
Destructor.
Definition at line 62 of file CollisionModel.C.
Member Function Documentation
TypeName ("collisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , CollisionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
virtual autoPtr<CollisionModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in PairCollision< CloudType >, and NoCollision< CloudType >.
Foam::autoPtr< Foam::CollisionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file CollisionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
virtual label nSubCycles () const pure virtual
Return the number of times to subcycle the current.
timestep to meet the criteria of the collision model
Implemented in PairCollision< CloudType >, and NoCollision< CloudType >.
virtual bool controlsWallInteraction () const pure virtual
Indicates whether model determines wall collisions or not,.
used to determine what value to use for wallImpactDistance
Implemented in PairCollision< CloudType >, and NoCollision< CloudType >.
virtual void collide () pure virtual
Implemented in PairCollision< CloudType >, and NoCollision< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/CollidingCloud/CollidingCloud.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/CollisionModel/CollisionModel.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/CollisionModel/CollisionModel.C
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/CollisionModel/CollisionModelNew.C