OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CompressibleTurbulenceModel< TransportModel > Class Template Reference
Templated abstract base class for single-phase compressible turbulence models.
Public Types
typedef geometricOneField alphaField
typedef volScalarField rhoField
typedef TransportModel transportModel
Public Member Functions
CompressibleTurbulenceModel (const word &type, const geometricOneField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasport, const word &propertiesName)
Construct.
virtual ~CompressibleTurbulenceModel ()
Destructor.
virtual tmp< volScalarField > mu () const
Return the laminar dynamic viscosity.
virtual tmp< scalarField > mu (const label patchi) const
Return the laminar dynamic viscosity on patch.
virtual tmp< volScalarField > mut () const
Return the turbulence dynamic viscosity.
virtual tmp< scalarField > mut (const label patchi) const
Return the turbulence dynamic viscosity on patch.
virtual tmp< volScalarField > muEff () const
Return the effective dynamic viscosity.
virtual tmp< scalarField > muEff (const label patchi) const
Return the effective dynamic viscosity on patch.
Static Public Member Functions
static autoPtr< CompressibleTurbulenceModel > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const transportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Detailed Description
template<class TransportModel>
class Foam::CompressibleTurbulenceModel< TransportModel >
Templated abstract base class for single-phase compressible turbulence models.
Source files
CompressibleTurbulenceModel.H
CompressibleTurbulenceModel.C
Definition at line 51 of file CompressibleTurbulenceModel.H.
Member Typedef Documentation
typedef geometricOneField alphaField
Definition at line 64 of file CompressibleTurbulenceModel.H.
typedef volScalarField rhoField
Definition at line 65 of file CompressibleTurbulenceModel.H.
typedef TransportModel transportModel
Definition at line 66 of file CompressibleTurbulenceModel.H.
Constructor & Destructor Documentation
CompressibleTurbulenceModel (const word & type, const geometricOneField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & trasport, const word & propertiesName)
Construct.
Definition at line 33 of file CompressibleTurbulenceModel.C.
virtual ~CompressibleTurbulenceModel () inline virtual
Destructor.
Definition at line 99 of file CompressibleTurbulenceModel.H.
Member Function Documentation
Foam::autoPtr< Foam::CompressibleTurbulenceModel< TransportModel > > New (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const transportModel & trasportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Definition at line 68 of file CompressibleTurbulenceModel.C.
References Foam::compressible::New().
virtual tmp<volScalarField> mu () const inline virtual
Return the laminar dynamic viscosity.
Definition at line 106 of file CompressibleTurbulenceModel.H.
Referenced by CompressibleTurbulenceModel< TransportModel >::muEff().
virtual tmp<scalarField> mu (const label patchi) const inline virtual
Return the laminar dynamic viscosity on patch.
Definition at line 112 of file CompressibleTurbulenceModel.H.
virtual tmp<volScalarField> mut () const inline virtual
Return the turbulence dynamic viscosity.
Definition at line 118 of file CompressibleTurbulenceModel.H.
References nut.
Referenced by CompressibleTurbulenceModel< TransportModel >::muEff().
virtual tmp<scalarField> mut (const label patchi) const inline virtual
Return the turbulence dynamic viscosity on patch.
Definition at line 124 of file CompressibleTurbulenceModel.H.
References nut, and patchi.
virtual tmp<volScalarField> muEff () const inline virtual
Return the effective dynamic viscosity.
Definition at line 130 of file CompressibleTurbulenceModel.H.
References CompressibleTurbulenceModel< TransportModel >::mu(), and CompressibleTurbulenceModel< TransportModel >::mut().
virtual tmp<scalarField> muEff (const label patchi) const inline virtual
Return the effective dynamic viscosity on patch.
Definition at line 136 of file CompressibleTurbulenceModel.H.
References CompressibleTurbulenceModel< TransportModel >::mu(), and CompressibleTurbulenceModel< TransportModel >::mut().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/CompressibleTurbulenceModel/CompressibleTurbulenceModel.H
src/TurbulenceModels/compressible/CompressibleTurbulenceModel/CompressibleTurbulenceModel.C