OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CollisionRecordList< PairType, WallType > Class Template Reference
Public Member Functions
CollisionRecordList ()
Construct null.
CollisionRecordList (Istream &)
Construct from Istream.
CollisionRecordList (const labelField &pairAccessed, const labelField &pairOrigProcOfOther, const labelField &pairOrigIdOfOther, const Field< PairType > &pairData, const labelField &wallAccessed, const vectorField &wallPRel, const Field< WallType > &wallData)
Construct from component fields (for IO)
~CollisionRecordList ()
Destructor.
const DynamicList< PairCollisionRecord< PairType > > & pairRecords () const
Return the active pair collisions.
const DynamicList< WallCollisionRecord< WallType > > & wallRecords () const
Return the active wall collisions.
labelField pairAccessed () const
Return field of pair accessed from each record, used for.
labelField pairOrigProcOfOther () const
Return field of pair origProcOfOther from each record,.
labelField pairOrigIdOfOther () const
Return field of pair origIdOfOther from each record, used.
Field< PairType > pairData () const
Return field of pair data from each record, used for field IO.
labelField wallAccessed () const
Return field of wall accessed from each record, used for field IO.
vectorField wallPRel () const
Return field of wall pRel from each record, used for field IO.
Field< WallType > wallData () const
Return field of wall data from each record, used for field IO.
PairCollisionRecord< PairType > & matchPairRecord (label origProcOfOther, label origIdOfOther)
Enquires if the proc and id pair of the other particle are.
bool checkPairRecord (label origProcOfOther, label origIdOfOther)
Enquire if the specified record exists without modifying.
WallCollisionRecord< WallType > & matchWallRecord (const vector &pRel, scalar radius)
Enquires if the position of wall impact relative to the.
bool checkWallRecord (const vector &pRel, scalar radius)
Enquire if the specified record exists without modifying.
void update ()
Update the collision records, deleting any records not.
void operator= (const CollisionRecordList &)
Friends
bool operator== (const CollisionRecordList< PairType, WallType > &, const CollisionRecordList< PairType, WallType > &)
bool operator!= (const CollisionRecordList< PairType, WallType > &, const CollisionRecordList< PairType, WallType > &)
Istream & operator>> (Istream &, CollisionRecordList< PairType, WallType > &)
Ostream & operator (Ostream &, const CollisionRecordList< PairType, WallType > &)
Detailed Description
template<class PairType, class WallType>
class Foam::CollisionRecordList< PairType, WallType >
Source files
CollisionRecordList.H
CollisionRecordListI.H
CollisionRecordList.C
CollisionRecordListIO.C
Definition at line 49 of file CollisionRecordList.H.
Constructor & Destructor Documentation
CollisionRecordList ()
Construct null.
Definition at line 32 of file CollisionRecordList.C.
CollisionRecordList (Istream & is)
Construct from Istream.
Definition at line 40 of file CollisionRecordList.C.
References IOstream::check().
CollisionRecordList (const labelField & pairAccessed, const labelField & pairOrigProcOfOther, const labelField & pairOrigIdOfOther, const Field< PairType > & pairData, const labelField & wallAccessed, const vectorField & wallPRel, const Field< WallType > & wallData)
Construct from component fields (for IO)
Definition at line 56 of file CollisionRecordList.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, Foam::nl, List< T >::size(), and List< Type >::size().
~CollisionRecordList ()
Destructor.
Definition at line 155 of file CollisionRecordList.C.
Member Function Documentation
const Foam::DynamicList< Foam::PairCollisionRecord< PairType > > & pairRecords () const inline
Return the active pair collisions.
Definition at line 32 of file CollisionRecordListI.H.
const Foam::DynamicList< Foam::WallCollisionRecord< WallType > > & wallRecords () const inline
Return the active wall collisions.
Definition at line 40 of file CollisionRecordListI.H.
Foam::labelField pairAccessed () const
Return field of pair accessed from each record, used for.
field IO
Definition at line 163 of file CollisionRecordList.C.
References f(), and forAll.
Foam::labelField pairOrigProcOfOther () const
Return field of pair origProcOfOther from each record,.
used for field IO
Definition at line 178 of file CollisionRecordList.C.
References f(), and forAll.
Foam::labelField pairOrigIdOfOther () const
Return field of pair origIdOfOther from each record, used.
for field IO
Definition at line 193 of file CollisionRecordList.C.
References f(), and forAll.
Foam::Field< PairType > pairData () const
Return field of pair data from each record, used for field IO.
Definition at line 208 of file CollisionRecordList.C.
References f(), and forAll.
Foam::labelField wallAccessed () const
Return field of wall accessed from each record, used for field IO.
Definition at line 223 of file CollisionRecordList.C.
References f(), and forAll.
Foam::vectorField wallPRel () const
Return field of wall pRel from each record, used for field IO.
Definition at line 238 of file CollisionRecordList.C.
References f(), and forAll.
Foam::Field< WallType > wallData () const
Return field of wall data from each record, used for field IO.
Definition at line 253 of file CollisionRecordList.C.
References f(), and forAll.
Foam::PairCollisionRecord< PairType > & matchPairRecord (label origProcOfOther, label origIdOfOther)
Enquires if the proc and id pair of the other particle are.
present in the records. If so, return non-const access to the PairCollisionRecord (hence the data) and mark the PairCollisionRecord as accessed this step, if not, create the record and return access to it.
Definition at line 269 of file CollisionRecordList.C.
References forAll, PairCollisionRecord< Type >::match(), and PairCollisionRecord< Type >::setAccessed().
bool checkPairRecord (label origProcOfOther, label origIdOfOther)
Enquire if the specified record exists without modifying.
its accessed status
Definition at line 305 of file CollisionRecordList.C.
References forAll, and PairCollisionRecord< Type >::match().
Foam::WallCollisionRecord< WallType > & matchWallRecord (const vector & pRel, scalar radius)
Enquires if the position of wall impact relative to the.
particle centre is present in the records. If so, return access to the WallCollisionRecord (hence the data) and mark the WallCollisionRecord as accesses this step, if not, create the record and return access to it.
Definition at line 327 of file CollisionRecordList.C.
References forAll, WallCollisionRecord< Type >::match(), and WallCollisionRecord< Type >::setAccessed().
bool checkWallRecord (const vector & pRel, scalar radius)
Enquire if the specified record exists without modifying.
its accessed status
Definition at line 359 of file CollisionRecordList.C.
References forAll, and WallCollisionRecord< Type >::match().
void update ()
Update the collision records, deleting any records not.
marked as having been accessed, then mark all records as not accessed ready for the next evaluation
Definition at line 379 of file CollisionRecordList.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), and forAll.
void operator= (const CollisionRecordList< PairType, WallType > &)
Definition at line 419 of file CollisionRecordList.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Friends And Related Function Documentation
bool operator== (const CollisionRecordList< PairType, WallType > & , const CollisionRecordList< PairType, WallType > &) friend
bool operator!= (const CollisionRecordList< PairType, WallType > & , const CollisionRecordList< PairType, WallType > &) friend
Istream& operator>> (Istream & , CollisionRecordList< PairType, WallType > &) friend
Ostream& operator (Ostream & , const CollisionRecordList< PairType, WallType > &) friend
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/CollisionRecordList.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/CollisionRecordList.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/CollisionRecordListI.H