OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
token::compound Class Reference abstract
Abstract base class for complex tokens.
Public Member Functions
TypeName ("compound")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, compound, Istream,(Istream &is),(is))
Declare run-time constructor selection table.
compound ()
Construct null.
virtual ~compound ()
Destructor.
bool empty () const
bool & empty ()
virtual label size () const =0
virtual void write (Ostream &) const =0
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static autoPtr< compound > New (const word &type, Istream &)
Select null constructed.
static bool isCompound (const word &name)
Return true if name is a compound type.
Friends
Ostream & operator<< (Ostream &, const compound &)
Detailed Description
Abstract base class for complex tokens.
Definition at line 122 of file token.H.
Constructor & Destructor Documentation
compound () inline
Construct null.
Definition at line 160 of file token.H.
~compound () virtual
Destructor.
Definition at line 53 of file token.C.
Member Function Documentation
TypeName ("compound")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , compound , Istream , (Istream &is) , (is))
Declare run-time constructor selection table.
Foam::autoPtr< Foam::token::compound > New (const word & type, Istream & is) static
Select null constructed.
Definition at line 60 of file token.C.
References Foam::abort(), Foam::endl(), Foam::FatalIOError, FatalIOErrorIn, and Foam::nl.
Referenced by UIPstream::read().
bool isCompound (const word & name) static
Return true if name is a compound type.
Definition at line 83 of file token.C.
Referenced by UIPstream::read().
bool empty () const inline
Definition at line 183 of file token.H.
Referenced by Foam::operator<<().
bool& empty () inline
Definition at line 188 of file token.H.
virtual label size () const pure virtual
Implemented in token::Compound< T >.
virtual void write (Ostream &) const pure virtual
Implemented in token::Compound< T >.
Referenced by Foam::operator<<().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const compound &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/token/token.H
src/OpenFOAM/db/IOstreams/token/token.C