OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
codedFunctionObject Class Reference
FunctionObjects » Utility function objects
This function object provides a general interface to enable dynamic code compilation.
Public Member Functions
TypeName ("coded")
Runtime type information.
codedFunctionObject (const word &name, const Time &time, const dictionary &dict)
Construct from Time and dictionary.
virtual ~codedFunctionObject ()
Destructor.
functionObject & redirectFunctionObject () const
Dynamically compiled functionObject.
virtual bool execute (const bool postProcess=false)
Called at each ++ or += of the time-loop.
virtual bool write (const bool postProcess=false)
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool read (const dictionary &)
Read and set the function object if its data have changed.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from codedBase
ClassName ("codedBase")
Runtime type information.
codedBase ()
Construct null.
virtual ~codedBase ()
Destructor.
Protected Member Functions
virtual dlLibraryTable & libs () const
Get the loaded dynamic libraries.
virtual void prepare (dynamicCode &, const dynamicCodeContext &) const
Adapt the context for the current object.
virtual string description () const
virtual void clearRedirect () const
virtual const dictionary & codeDict () const
Protected Member Functions inherited from codedBase
void updateLibrary (const word &redirectType) const
Update library as required.
Protected Attributes
const Time & time_
Reference to the time database.
dictionary dict_
Input dictionary.
word redirectType_
string codeData_
string codeRead_
string codeExecute_
string codeEnd_
string codeTimeSet_
autoPtr< functionObject > redirectFunctionObjectPtr_
Underlying functionObject.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
This function object provides a general interface to enable dynamic code compilation.
The entries are code : c++; upon functionObject::write() codeInclude : include files codeOptions : include paths; inserted into EXE_INC in Make/options codeLibs : link line; inserted into LIB_LIBS in Make/options
codeExecute : c++;upon functionObject::execute(); codeRead : c++; upon functionObject::read(); codeEnd : c++; upon functionObject::end(); codeData : c++; local member data (null constructed); codeTimeSet : c++; upon functionObject::timeSet(); localCode : c++; local static functions
Example of function object specification:
difference
{
    libs ("libutilityFunctionObjects.so");
    type coded;
    // Name of on-the-fly generated functionObject
    redirectType writeMagU;
    code
    #{
        // Lookup U
        const volVectorField& U = mesh().lookupObject<volVectorField>("U");
        // Write
        mag(U).write();
    }
}
See also
Foam::functionObject Foam::codedBase
Source files
codedFunctionObject.H
codedFunctionObject.C
Definition at line 90 of file codedFunctionObject.H.
Constructor & Destructor Documentation
codedFunctionObject (const word & name, const Time & time, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 121 of file codedFunctionObject.C.
References Foam::read().
~codedFunctionObject () virtual
Destructor.
Definition at line 141 of file codedFunctionObject.C.
Member Function Documentation
Foam::dlLibraryTable & libs () const protected virtual
Get the loaded dynamic libraries.
Implements codedBase.
Definition at line 94 of file codedFunctionObject.C.
void prepare (dynamicCode & dynCode, const dynamicCodeContext & context) const protected virtual
Adapt the context for the current object.
Implements codedBase.
Definition at line 53 of file codedFunctionObject.C.
References dynamicCode::addCompileFile(), dynamicCode::addCopyFile(), dynamicCodeContext::libs(), dynamicCodeContext::options(), dynamicCode::setFilterVariable(), and dynamicCode::setMakeOptions().
Foam::string description () const protected virtual
Implements codedBase.
Definition at line 100 of file codedFunctionObject.C.
References Foam::name().
void clearRedirect () const protected virtual
Implements codedBase.
Definition at line 106 of file codedFunctionObject.C.
const Foam::dictionary & codeDict () const protected virtual
Implements codedBase.
Definition at line 112 of file codedFunctionObject.C.
TypeName ("coded")
Runtime type information.
Foam::functionObject & redirectFunctionObject () const
Dynamically compiled functionObject.
Definition at line 147 of file codedFunctionObject.C.
References functionObject::New(), and dictionary::set().
bool execute (const bool postProcess = false) virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual executeControl behaviour and forces execution (used in post-processing mode)
Implements functionObject.
Definition at line 165 of file codedFunctionObject.C.
bool write (const bool postProcess = false) virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual writeControl behaviour and forces writing always (used in post-processing mode)
Implements functionObject.
Definition at line 172 of file codedFunctionObject.C.
bool end () virtual
Called when Time::run() determines that the time-loop exits.
By default it simply calls execute().
Reimplemented from functionObject.
Definition at line 179 of file codedFunctionObject.C.
bool timeSet () virtual
Called when time was set at the end of the Time::operator++.
Reimplemented from functionObject.
Definition at line 186 of file codedFunctionObject.C.
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Implements functionObject.
Definition at line 193 of file codedFunctionObject.C.
References dynamicCodeContext::addLineDirective(), Foam::stringOps::inplaceExpand(), dictionary::lookup(), dictionary::lookupEntryPtr(), dictionaryName::name(), entry::startLineNumber(), entry::stream(), and Foam::stringOps::trim().
Member Data Documentation
const Time& time_ protected
Reference to the time database.
Definition at line 100 of file codedFunctionObject.H.
dictionary dict_ protected
Input dictionary.
Definition at line 103 of file codedFunctionObject.H.
word redirectType_ protected
Definition at line 105 of file codedFunctionObject.H.
string codeData_ protected
Definition at line 107 of file codedFunctionObject.H.
string codeRead_ protected
Definition at line 108 of file codedFunctionObject.H.
string codeExecute_ protected
Definition at line 109 of file codedFunctionObject.H.
string codeEnd_ protected
Definition at line 110 of file codedFunctionObject.H.
string codeTimeSet_ protected
Definition at line 111 of file codedFunctionObject.H.
autoPtr<functionObject> redirectFunctionObjectPtr_ mutable protected
Underlying functionObject.
Definition at line 114 of file codedFunctionObject.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/codedFunctionObject/codedFunctionObject.H
src/postProcessing/functionObjects/utilities/codedFunctionObject/codedFunctionObject.C