OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
continuousGasKEpsilon< BasicTurbulenceModel > Class Template Reference
RAS turbulence
k-epsilon model for the gas-phase in a two-phase system supporting phase-inversion.
Public Types
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kEpsilon< BasicTurbulenceModel >
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel
< BasicTurbulenceModel >
::alphaField alphaField
typedef RASModel
< BasicTurbulenceModel >
::rhoField rhoField
typedef RASModel
< BasicTurbulenceModel >
::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel
< BasicTurbulenceModel >
::alphaField alphaField
typedef RASModel
< BasicTurbulenceModel >
::rhoField rhoField
typedef RASModel
< BasicTurbulenceModel >
::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("continuousGasKEpsilon")
Runtime type information.
continuousGasKEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~continuousGasKEpsilon ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
const turbulenceModel & liquidTurbulence () const
Return the turbulence model for the liquid phase.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< volScalarField > rhoEff () const
Return the effective density for the stress.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
Public Member Functions inherited from kEpsilon< BasicTurbulenceModel >
TypeName ("kEpsilon")
Runtime type information.
kEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kEpsilon ()
Destructor.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual void correctNut ()
tmp< volScalarField > phaseTransferCoeff () const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar alphaInversion_
Protected Attributes inherited from kEpsilon< BasicTurbulenceModel >
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::continuousGasKEpsilon< BasicTurbulenceModel >
k-epsilon model for the gas-phase in a two-phase system supporting phase-inversion.
In the limit that the gas-phase fraction approaches zero a contribution from the other phase is blended into the k and epsilon equations up to the phase-fraction of alphaInversion at which point phase-inversion is considered to have occurred and the model reverts to the pure single-phase form.
This model is unpublished and is provided as a stable numerical framework on which a more physical model may be built.
The default model coefficients are
    continuousGasKEpsilonCoeffs
    {
        Cmu             0.09;
        C1              1.44;
        C2              1.92;
        C3              -0.33;
        sigmak          1.0;
        sigmaEps        1.3;
        alphaInversion  0.7;
    }
Source files
continuousGasKEpsilon.H
continuousGasKEpsilon.C
Definition at line 78 of file continuousGasKEpsilon.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 115 of file continuousGasKEpsilon.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 116 of file continuousGasKEpsilon.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 117 of file continuousGasKEpsilon.H.
Constructor & Destructor Documentation
continuousGasKEpsilon (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 42 of file continuousGasKEpsilon.C.
References kEpsilon< BasicTurbulenceModel >::correctNut().
virtual ~continuousGasKEpsilon () inline virtual
Destructor.
Definition at line 141 of file continuousGasKEpsilon.H.
Member Function Documentation
void correctNut () protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 117 of file continuousGasKEpsilon.C.
References kEpsilon< BasicTurbulenceModel >::correctNut(), virtualMassModel::Cvm(), turbulenceModel::epsilon(), Foam::exp(), turbulenceModel::k(), Foam::min(), turbulenceModel::nut(), twoPhaseSystem::otherPhase(), Foam::sqr(), and twoPhaseSystem::virtualMass().
tmp< volScalarField > phaseTransferCoeff () const protected
Definition at line 221 of file continuousGasKEpsilon.C.
References TimeState::deltaT(), turbulenceModel::epsilon(), turbulenceModel::k(), Foam::max(), Foam::min(), and IOobject::time().
tmp< fvScalarMatrix > kSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 244 of file continuousGasKEpsilon.C.
References turbulenceModel::k(), and Foam::fvm::Sp().
tmp< fvScalarMatrix > epsilonSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 257 of file continuousGasKEpsilon.C.
References turbulenceModel::epsilon(), and Foam::fvm::Sp().
TypeName ("continuousGasKEpsilon< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Re-read model coefficients if they have changed.
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 101 of file continuousGasKEpsilon.C.
const turbulenceModel & liquidTurbulence () const
Return the turbulence model for the liquid phase.
Definition at line 145 of file continuousGasKEpsilon.C.
References IOobject::db(), IOobject::groupName(), objectRegistry::lookupObject(), twoPhaseSystem::otherPhase(), and turbulenceModel::propertiesName.
tmp< Foam::volScalarField > nuEff () const virtual
Return the effective viscosity.
Reimplemented from RASModel< BasicTurbulenceModel >.
Definition at line 172 of file continuousGasKEpsilon.C.
References IOobject::groupName(), Foam::max(), Foam::min(), and nu.
tmp< Foam::volScalarField > rhoEff () const virtual
Return the effective density for the stress.
Definition at line 202 of file continuousGasKEpsilon.C.
References virtualMassModel::Cvm(), IOobject::groupName(), twoPhaseSystem::otherPhase(), and twoPhaseSystem::virtualMass().
tmp< volSymmTensorField > R () const virtual
Return the Reynolds stress tensor.
Reimplemented from eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 270 of file continuousGasKEpsilon.C.
References Foam::dev(), Foam::fvc::grad(), IOobject::groupName(), Foam::I, k, IOobject::NO_READ, IOobject::NO_WRITE, and Foam::twoSymm().
Member Data Documentation
dimensionedScalar alphaInversion_ protected
Definition at line 102 of file continuousGasKEpsilon.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/RAS/continuousGasKEpsilon/continuousGasKEpsilon.H
src/TurbulenceModels/phaseCompressible/RAS/continuousGasKEpsilon/continuousGasKEpsilon.C