OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
constantFilmThermo Class Reference
Classes
struct thermoData
Public Member Functions
TypeName ("constant")
Runtime type information.
constantFilmThermo (surfaceFilmModel &owner, const dictionary &dict)
Construct from surface film model and dictionary.
virtual ~constantFilmThermo ()
Destructor.
virtual const word & name () const
Return the specie name.
virtual scalar rho (const scalar p, const scalar T) const
Return density [kg/m3].
virtual scalar mu (const scalar p, const scalar T) const
Return dynamic viscosity [Pa.s].
virtual scalar sigma (const scalar p, const scalar T) const
Return surface tension [kg/s2].
virtual scalar Cp (const scalar p, const scalar T) const
Return specific heat capacity [J/kg/K].
virtual scalar kappa (const scalar p, const scalar T) const
Return thermal conductivity [W/m/K].
virtual scalar D (const scalar p, const scalar T) const
Return diffusivity [m2/s].
virtual scalar hl (const scalar p, const scalar T) const
Return latent heat [J/kg].
virtual scalar pv (const scalar p, const scalar T) const
Return vapour pressure [Pa].
virtual scalar W () const
Return molecular weight [kg/kmol].
virtual scalar Tb (const scalar p) const
Return boiling temperature [K].
virtual tmp< volScalarField > rho () const
Return density [kg/m3].
virtual tmp< volScalarField > mu () const
Return dynamic viscosity [Pa.s].
virtual tmp< volScalarField > sigma () const
Return surface tension [kg/s2].
virtual tmp< volScalarField > Cp () const
Return specific heat capacity [J/kg/K].
virtual tmp< volScalarField > kappa () const
Return thermal conductivity [W/m/K].
Public Member Functions inherited from filmThermoModel
TypeName ("filmThermoModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, filmThermoModel, dictionary,(surfaceFilmModel &owner, const dictionary &dict),(owner, dict))
filmThermoModel (surfaceFilmModel &owner)
Construct null.
filmThermoModel (const word &modelType, surfaceFilmModel &owner, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~filmThermoModel ()
Destructor.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool outputTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Additional Inherited Members
Static Public Member Functions inherited from filmThermoModel
static autoPtr< filmThermoModel > New (surfaceFilmModel &owner, const dictionary &dict)
Return a reference to the selected phase change model.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
Definition at line 53 of file constantFilmThermo.H.
Constructor & Destructor Documentation
constantFilmThermo (surfaceFilmModel & owner, const dictionary & dict)
Construct from surface film model and dictionary.
Definition at line 63 of file constantFilmThermo.C.
~constantFilmThermo () virtual
Destructor.
Definition at line 94 of file constantFilmThermo.C.
Referenced by constantFilmThermo::thermoData::thermoData().
Member Function Documentation
TypeName ("constant")
Runtime type information.
Referenced by constantFilmThermo::thermoData::thermoData().
const word & name () const virtual
Return the specie name.
Implements filmThermoModel.
Definition at line 100 of file constantFilmThermo.C.
References constantFilmThermo::rho().
Referenced by constantFilmThermo::thermoData::thermoData().
scalar rho (const scalar p, const scalar T) const virtual
Return density [kg/m3].
Implements filmThermoModel.
Definition at line 107 of file constantFilmThermo.C.
References subModelBase::coeffDict_, dictionary::lookup(), constantFilmThermo::mu(), constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
scalar mu (const scalar p, const scalar T) const virtual
Return dynamic viscosity [Pa.s].
Implements filmThermoModel.
Definition at line 123 of file constantFilmThermo.C.
References subModelBase::coeffDict_, dictionary::lookup(), constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, constantFilmThermo::sigma(), and constantFilmThermo::thermoData::value_.
scalar sigma (const scalar p, const scalar T) const virtual
Return surface tension [kg/s2].
Implements filmThermoModel.
Definition at line 139 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::Cp(), dictionary::lookup(), constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
scalar Cp (const scalar p, const scalar T) const virtual
Return specific heat capacity [J/kg/K].
Implements filmThermoModel.
Definition at line 155 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::kappa(), dictionary::lookup(), constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
scalar kappa (const scalar p, const scalar T) const virtual
Return thermal conductivity [W/m/K].
Implements filmThermoModel.
Definition at line 171 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::D(), dictionary::lookup(), constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
scalar D (const scalar p, const scalar T) const virtual
Return diffusivity [m2/s].
Implements filmThermoModel.
Definition at line 187 of file constantFilmThermo.C.
References subModelBase::coeffDict_, constantFilmThermo::hl(), dictionary::lookup(), constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
Referenced by constantFilmThermo::kappa(), and constantFilmThermo::thermoData::thermoData().
scalar hl (const scalar p, const scalar T) const virtual
Return latent heat [J/kg].
Implements filmThermoModel.
Definition at line 203 of file constantFilmThermo.C.
References subModelBase::coeffDict_, dictionary::lookup(), constantFilmThermo::thermoData::name_, constantFilmThermo::pv(), constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
Referenced by constantFilmThermo::D(), and constantFilmThermo::thermoData::thermoData().
scalar pv (const scalar p, const scalar T) const virtual
Return vapour pressure [Pa].
Implements filmThermoModel.
Definition at line 219 of file constantFilmThermo.C.
References subModelBase::coeffDict_, dictionary::lookup(), constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
Referenced by constantFilmThermo::hl(), and constantFilmThermo::thermoData::thermoData().
scalar W () const virtual
Return molecular weight [kg/kmol].
Implements filmThermoModel.
Definition at line 234 of file constantFilmThermo.C.
References subModelBase::coeffDict_, dictionary::lookup(), constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
Referenced by constantFilmThermo::thermoData::thermoData().
scalar Tb (const scalar p) const virtual
Return boiling temperature [K].
Implements filmThermoModel.
Definition at line 246 of file constantFilmThermo.C.
References subModelBase::coeffDict_, dictionary::lookup(), constantFilmThermo::thermoData::name_, constantFilmThermo::thermoData::set_, and constantFilmThermo::thermoData::value_.
Referenced by constantFilmThermo::thermoData::thermoData().
tmp< volScalarField > rho () const virtual
Return density [kg/m3].
Implements filmThermoModel.
Definition at line 258 of file constantFilmThermo.C.
References Foam::dimDensity, constantFilmThermo::thermoData::name_, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), tmp< T >::ref(), timeName, trho, and Foam::type().
Referenced by constantFilmThermo::name(), and constantFilmThermo::thermoData::thermoData().
tmp< volScalarField > mu () const virtual
Return dynamic viscosity [Pa.s].
Implements filmThermoModel.
Definition at line 285 of file constantFilmThermo.C.
References Foam::dimPressure, Foam::dimTime, constantFilmThermo::thermoData::name_, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), tmp< T >::ref(), timeName, and Foam::type().
Referenced by constantFilmThermo::rho(), and constantFilmThermo::thermoData::thermoData().
tmp< volScalarField > sigma () const virtual
Return surface tension [kg/s2].
Implements filmThermoModel.
Definition at line 312 of file constantFilmThermo.C.
References Foam::dimMass, Foam::dimTime, constantFilmThermo::thermoData::name_, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), tmp< T >::ref(), Foam::sqr(), timeName, and Foam::type().
Referenced by constantFilmThermo::mu(), and constantFilmThermo::thermoData::thermoData().
tmp< volScalarField > Cp () const virtual
Return specific heat capacity [J/kg/K].
Implements filmThermoModel.
Definition at line 339 of file constantFilmThermo.C.
References Foam::dimEnergy, Foam::dimMass, Foam::dimTemperature, constantFilmThermo::thermoData::name_, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), tmp< T >::ref(), timeName, and Foam::type().
Referenced by constantFilmThermo::sigma(), and constantFilmThermo::thermoData::thermoData().
tmp< volScalarField > kappa () const virtual
Return thermal conductivity [W/m/K].
Implements filmThermoModel.
Definition at line 366 of file constantFilmThermo.C.
References Foam::dimLength, Foam::dimPower, Foam::dimTemperature, constantFilmThermo::thermoData::name_, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), tmp< T >::ref(), timeName, and Foam::type().
Referenced by constantFilmThermo::Cp(), and constantFilmThermo::thermoData::thermoData().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/constantFilmThermo/constantFilmThermo.H
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/constantFilmThermo/constantFilmThermo.C