OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
coordinateRotation Class Reference abstract
Abstract base class for coordinate rotation.
Public Member Functions
TypeName ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, coordinateRotation, objectRegistry,(const dictionary &dict, const objectRegistry &obr),(dict, obr))
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()
Destructor.
virtual void clear ()=0
Reset rotation to an identity rotation.
virtual void updateCells (const polyMesh &mesh, const labelList &cells)=0
Update the rotation for a list of cells.
virtual const tensor & R () const =0
Return local-to-global transformation tensor.
virtual const tensor & Rtr () const =0
Return global-to-local transformation tensor.
virtual const vector e1 () const =0
Return local Cartesian x-axis.
virtual const vector e2 () const =0
Return local Cartesian y-axis.
virtual const vector e3 () const =0
Return local Cartesian z-axis.
virtual const tensorField & Tr () const =0
Return local-to-global transformation tensor.
virtual bool uniform () const
Return true if the rotation tensor is uniform.
virtual tmp< vectorField > transform (const vectorField &st) const =0
Transform vectorField using transformation tensor field.
virtual vector transform (const vector &st) const =0
Transform vector using transformation tensor.
virtual tmp< vectorField > invTransform (const vectorField &st) const =0
Inverse transform vectorField using transformation tensor field.
virtual vector invTransform (const vector &st) const =0
Inverse transform vector using transformation tensor.
virtual tmp< tensorField > transformTensor (const tensorField &st) const =0
Transform tensor field using transformation tensorField.
virtual tmp< tensorField > transformTensor (const tensorField &st, const labelList &cellMap) const =0
Transform tensor sub-field using transformation tensorField.
virtual tensor transformTensor (const tensor &st) const =0
Transform tensor using transformation tensorField.
virtual tmp< symmTensorField > transformVector (const vectorField &st) const =0
Transform vectorField using transformation tensorField and return.
virtual symmTensor transformVector (const vector &st) const =0
Transform vector using transformation tensor and return.
virtual void write (Ostream &) const =0
Write.
Static Public Member Functions
static autoPtr
< coordinateRotation > New (const dictionary &dict, const objectRegistry &obr)
Select constructed from dictionary and objectRegistry.
static autoPtr
< coordinateRotation > New (const dictionary &dict)
Select constructed from dictionary.
Protected Member Functions
symmTensor transformPrincipal (const tensor &, const vector &) const
Transform principal.
Detailed Description
Abstract base class for coordinate rotation.
    coordinateRotation
    {
        type        axesRotation
        e1          (1 0 0);
        e2          (0 1 0);
    }
Types of coordinateRotation: 1) axesRotation 2) STARCDRotation 3) localAxesRotation 4) EulerCoordinateRotation
Definition at line 68 of file coordinateRotation.H.
Constructor & Destructor Documentation
virtual ~coordinateRotation () inline virtual
Destructor.
Definition at line 129 of file coordinateRotation.H.
Member Function Documentation
Foam::symmTensor transformPrincipal (const tensor & tt, const vector & st) const protected
Transform principal.
Definition at line 43 of file coordinateRotation.C.
References Vector< Cmpt >::x(), Tensor< Cmpt >::xx(), Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), Vector< Cmpt >::y(), Tensor< Cmpt >::yx(), Tensor< Cmpt >::yy(), Tensor< Cmpt >::yz(), Vector< Cmpt >::z(), Tensor< Cmpt >::zx(), Tensor< Cmpt >::zy(), and Tensor< Cmpt >::zz().
TypeName ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , coordinateRotation , objectRegistry , (const dictionary &dict, const objectRegistry &obr) , (dict, obr))
declareRunTimeSelectionTable (autoPtr , coordinateRotation , dictionary , (const dictionary &dict) , (dict))
Foam::autoPtr< Foam::coordinateRotation > New (const dictionary & dict, const objectRegistry & obr) static
Select constructed from dictionary and objectRegistry.
Definition at line 32 of file coordinateRotationNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookup(), Foam::nl, and Foam::Pout.
Referenced by coordinateSystem::init().
Foam::autoPtr< Foam::coordinateRotation > New (const dictionary & dict) static
Select constructed from dictionary.
Definition at line 71 of file coordinateRotationNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, dictionary::lookup(), Foam::nl, and Foam::Pout.
virtual void clear () pure virtual
Reset rotation to an identity rotation.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual void updateCells (const polyMesh & mesh, const labelList & cells) pure virtual
Update the rotation for a list of cells.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual const tensor& R () const pure virtual
Return local-to-global transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual const tensor& Rtr () const pure virtual
Return global-to-local transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual const vector e1 () const pure virtual
Return local Cartesian x-axis.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual const vector e2 () const pure virtual
Return local Cartesian y-axis.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual const vector e3 () const pure virtual
Return local Cartesian z-axis.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual const tensorField& Tr () const pure virtual
Return local-to-global transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual bool uniform () const inline virtual
Return true if the rotation tensor is uniform.
Reimplemented in localAxesRotation.
Definition at line 164 of file coordinateRotation.H.
virtual tmp<vectorField> transform (const vectorField & st) const pure virtual
Transform vectorField using transformation tensor field.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual vector transform (const vector & st) const pure virtual
Transform vector using transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual tmp<vectorField> invTransform (const vectorField & st) const pure virtual
Inverse transform vectorField using transformation tensor field.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual vector invTransform (const vector & st) const pure virtual
Inverse transform vector using transformation tensor.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual tmp<tensorField> transformTensor (const tensorField & st) const pure virtual
Transform tensor field using transformation tensorField.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
Referenced by fixedCoeff::calcTranformModelData(), and DarcyForchheimer::calcTranformModelData().
virtual tmp<tensorField> transformTensor (const tensorField & st, const labelList & cellMap) const pure virtual
Transform tensor sub-field using transformation tensorField.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual tensor transformTensor (const tensor & st) const pure virtual
Transform tensor using transformation tensorField.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual tmp<symmTensorField> transformVector (const vectorField & st) const pure virtual
Transform vectorField using transformation tensorField and return.
symmetrical tensorField
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual symmTensor transformVector (const vector & st) const pure virtual
Transform vector using transformation tensor and return.
symmetrical tensor
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
virtual void write (Ostream &) const pure virtual
Write.
Implemented in localAxesRotation, axesRotation, EulerCoordinateRotation, and STARCDCoordinateRotation.
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/coordinateRotation/coordinateRotation.H
src/meshTools/coordinateSystems/coordinateRotation/coordinateRotation.C
src/meshTools/coordinateSystems/coordinateRotation/coordinateRotationNew.C