OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ConeNozzleInjection< CloudType > Class Template Reference
Cone injection.
Public Types
enum injectionMethod { imPoint, imDisc }
Injection method enumeration.
enum flowType { ftConstantVelocity, ftPressureDrivenVelocity, ftFlowRateAndDischarge }
Flow type enumeration.
Public Types inherited from InjectionModel< CloudType >
enum parcelBasis { pbNumber, pbMass, pbFixed }
Parcel basis representation options.
typedef CloudType::parcelType parcelType
Convenience typedef for parcelType.
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Public Member Functions
TypeName ("coneNozzleInjection")
Runtime type information.
ConeNozzleInjection (const dictionary &dict, CloudType &owner, const word &modelName)
Construct from dictionary.
ConeNozzleInjection (const ConeNozzleInjection< CloudType > &im)
Construct copy.
virtual autoPtr< InjectionModel< CloudType > > clone () const
Construct and return a clone.
virtual ~ConeNozzleInjection ()
Destructor.
virtual void updateMesh ()
Set injector locations when mesh is updated.
scalar timeEnd () const
Return the end-of-injection time.
virtual label parcelsToInject (const scalar time0, const scalar time1)
Number of parcels to introduce relative to SOI.
virtual scalar volumeToInject (const scalar time0, const scalar time1)
Volume of parcels to introduce relative to SOI.
virtual void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector &position, label &cellOwner, label &tetFacei, label &tetPtI)
Set the injection position and owner cell.
virtual void setProperties (const label parcelI, const label nParcels, const scalar time, typename CloudType::parcelType &parcel)
Set the parcel properties.
virtual bool fullyDescribed () const
Flag to identify whether model fully describes the parcel.
virtual bool validInjection (const label parcelI)
Return flag to identify whether or not injection of parcelI is.
Public Member Functions inherited from InjectionModel< CloudType >
TypeName ("injectionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, InjectionModel, dictionary,(const dictionary &dict, CloudType &owner, const word &modelType),(dict, owner, modelType))
Declare runtime constructor selection table.
InjectionModel (CloudType &owner)
Construct null from owner.
InjectionModel (const dictionary &dict, CloudType &owner, const word &modelName, const word &modelType)
Construct from dictionary.
InjectionModel (const InjectionModel< CloudType > &im)
Construct copy.
virtual ~InjectionModel ()
Destructor.
scalar timeStart () const
Return the start-of-injection time.
scalar volumeTotal () const
Return the total volume to be injected across the event.
scalar massTotal () const
Return mass of particles to introduce.
scalar massInjected () const
Return mass of particles injected (cumulative)
virtual scalar averageParcelMass ()
Return the average parcel mass over the injection period.
label nInjections () const
Return the number of injections.
label parcelsAddedTotal () const
Return the total number parcels added.
template<class TrackData >
void inject (TrackData &td)
Main injection loop.
template<class TrackData >
void injectSteadyState (TrackData &td, const scalar trackTime)
Main injection loop - steady-state.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Static Public Member Functions inherited from InjectionModel< CloudType >
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector with lookup from dictionary.
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, const word &modelName, const word &modelType, CloudType &owner)
Selector with name and type.
Protected Member Functions inherited from InjectionModel< CloudType >
virtual bool prepareForNextTimeStep (const scalar time, label &newParcels, scalar &newVolumeFraction)
Determine properties for next time step/injection interval.
virtual bool findCellAtPosition (label &celli, label &tetFacei, label &tetPtI, vector &position, bool errorOnNotFound=true)
Find the cell that contains the supplied position.
virtual scalar setNumberOfParticles (const label parcels, const scalar volumeFraction, const scalar diameter, const scalar rho)
Set number of particles to inject given parcel properties.
virtual void postInjectCheck (const label parcelsAdded, const scalar massAdded)
Post injection checks.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from InjectionModel< CloudType >
scalar SOI_
Start of injection [s].
scalar volumeTotal_
Total volume of particles introduced by this injector [m^3].
scalar massTotal_
Total mass to inject [kg].
TimeFunction1< scalar > massFlowRate_
Mass flow rate profile for steady calculations.
scalar massInjected_
Total mass injected to date [kg].
label nInjections_
Number of injections counter.
label parcelsAddedTotal_
Running counter of total number of parcels added.
parcelBasis parcelBasis_
Parcel basis enumeration.
scalar nParticleFixed_
nParticle to assign to parcels when the 'fixed' basis
scalar time0_
Continuous phase time at start of injection time step [s].
scalar timeStep0_
Time at start of injection time step [s].
scalar delayedVolume_
Volume that should have been injected, but would lead to.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::ConeNozzleInjection< CloudType >
Cone injection.
User specifies:
time of start of injection
injector position
direction (along injection axis)
parcel flow rate
inner and outer half-cone angles
Parcel diameters obtained by size distribution model
Parcel velocity is calculated as:
Constant velocity:
    U = \<specified by user\>
Pressure driven velocity:
    U = sqrt(2*(Pinj - Pamb)/rho)
Flow rate and discharge:
    U = V_dot/(A*Cd)
Source files
ConeNozzleInjection.H
ConeNozzleInjection.C
Definition at line 81 of file ConeNozzleInjection.H.
Member Enumeration Documentation
enum injectionMethod
Injection method enumeration.
Enumerator
imPoint
imDisc
Definition at line 88 of file ConeNozzleInjection.H.
enum flowType
Flow type enumeration.
Enumerator
ftConstantVelocity
ftPressureDrivenVelocity
ftFlowRateAndDischarge
Definition at line 95 of file ConeNozzleInjection.H.
Constructor & Destructor Documentation
ConeNozzleInjection (const dictionary & dict, CloudType & owner, const word & modelName)
Construct from dictionary.
Definition at line 99 of file ConeNozzleInjection.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), Foam::nl, rndGen(), cachedRandom::sample01(), and Foam::Zero.
ConeNozzleInjection (const ConeNozzleInjection< CloudType > & im)
Construct copy.
Definition at line 205 of file ConeNozzleInjection.C.
~ConeNozzleInjection () virtual
Destructor.
Definition at line 237 of file ConeNozzleInjection.C.
Referenced by ConeNozzleInjection< CloudType >::clone().
Member Function Documentation
TypeName ("coneNozzleInjection")
Runtime type information.
virtual autoPtr<InjectionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements InjectionModel< CloudType >.
Definition at line 206 of file ConeNozzleInjection.H.
References ConeNozzleInjection< CloudType >::fullyDescribed(), ConeNozzleInjection< CloudType >::parcelsToInject(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeNozzleInjection< CloudType >::setProperties(), ConeNozzleInjection< CloudType >::timeEnd(), ConeNozzleInjection< CloudType >::updateMesh(), ConeNozzleInjection< CloudType >::validInjection(), ConeNozzleInjection< CloudType >::volumeToInject(), and ConeNozzleInjection< CloudType >::~ConeNozzleInjection().
void updateMesh () virtual
Set injector locations when mesh is updated.
Reimplemented from InjectionModel< CloudType >.
Definition at line 244 of file ConeNozzleInjection.C.
Referenced by ConeNozzleInjection< CloudType >::clone().
Foam::scalar timeEnd () const virtual
Return the end-of-injection time.
Implements InjectionModel< CloudType >.
Definition at line 268 of file ConeNozzleInjection.C.
References ConeNozzleInjection< CloudType >::parcelsToInject().
Referenced by ConeNozzleInjection< CloudType >::clone().
Foam::label parcelsToInject (const scalar time0, const scalar time1) virtual
Number of parcels to introduce relative to SOI.
Implements InjectionModel< CloudType >.
Definition at line 276 of file ConeNozzleInjection.C.
References ConeNozzleInjection< CloudType >::volumeToInject().
Referenced by ConeNozzleInjection< CloudType >::clone(), and ConeNozzleInjection< CloudType >::timeEnd().
Foam::scalar volumeToInject (const scalar time0, const scalar time1) virtual
Volume of parcels to introduce relative to SOI.
Implements InjectionModel< CloudType >.
Definition at line 294 of file ConeNozzleInjection.C.
References ConeNozzleInjection< CloudType >::setPositionAndCell().
Referenced by ConeNozzleInjection< CloudType >::clone(), and ConeNozzleInjection< CloudType >::parcelsToInject().
void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector & position, label & cellOwner, label & tetFacei, label & tetPtI) virtual
Set the injection position and owner cell.
Implements InjectionModel< CloudType >.
Definition at line 312 of file ConeNozzleInjection.C.
References beta(), Foam::cos(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, rndGen(), cachedRandom::sample01(), ConeNozzleInjection< CloudType >::setProperties(), Foam::sin(), and Foam::constant::mathematical::twoPi().
Referenced by ConeNozzleInjection< CloudType >::clone(), and ConeNozzleInjection< CloudType >::volumeToInject().
void setProperties (const label parcelI, const label nParcels, const scalar time, typename CloudType::parcelType & parcel) virtual
Set the parcel properties.
Implements InjectionModel< CloudType >.
Definition at line 367 of file ConeNozzleInjection.C.
References Foam::constant::atomic::alpha, Foam::cos(), Foam::mag(), Foam::constant::mathematical::pi(), rho, rndGen(), cachedRandom::sample01(), Foam::sin(), and Foam::sqrt().
Referenced by ConeNozzleInjection< CloudType >::clone(), and ConeNozzleInjection< CloudType >::setPositionAndCell().
bool fullyDescribed () const virtual
Flag to identify whether model fully describes the parcel.
Implements InjectionModel< CloudType >.
Definition at line 432 of file ConeNozzleInjection.C.
Referenced by ConeNozzleInjection< CloudType >::clone().
bool validInjection (const label parcelI) virtual
Return flag to identify whether or not injection of parcelI is.
permitted
Implements InjectionModel< CloudType >.
Definition at line 439 of file ConeNozzleInjection.C.
Referenced by ConeNozzleInjection< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/ConeNozzleInjection/ConeNozzleInjection.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/ConeNozzleInjection/ConeNozzleInjection.C