OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
HashTable< T, Key, Hash >::const_iterator Class Reference
An STL-conforming const_iterator.
Public Member Functions
const_iterator ()
Construct null (end iterator)
const_iterator (const iterator &)
Construct from iterator.
const_iterator (const iteratorEnd &unused)
Construct end iterator.
const T & operator* () const
Return referenced hash value.
const T & operator() () const
const_iterator & operator++ ()
const_iterator operator++ (int)
Public Member Functions inherited from HashTable< T, Key, Hash >::iteratorBase
const Key & key () const
Return the Key corresponding to the iterator.
bool operator== (const iteratorBase &) const
Compare hashedEntry element pointers.
bool operator!= (const iteratorBase &) const
bool operator== (const iteratorEnd &unused) const
Compare hashedEntry to iteratorEnd pointers.
bool operator!= (const iteratorEnd &unused) const
Friends
class HashTable
Additional Inherited Members
Protected Member Functions inherited from HashTable< T, Key, Hash >::iteratorBase
iteratorBase ()
Construct null - equivalent to an 'end' position.
iteratorBase (const HashTable< T, Key, Hash > *curHashTable)
Construct from hash table, moving to its 'begin' position.
iteratorBase (const HashTable< T, Key, Hash > *curHashTable, const hashedEntry *elmt, const label hashIndex)
Construct from hash table, element and hash index.
void increment ()
Increment to the next position.
bool erase ()
Erase the HashTable element at the current position.
T & object ()
Return non-const access to referenced object.
const T & cobject () const
Return const access to referenced object.
Detailed Description
template<class T, class Key = word, class Hash = string::hash>
class Foam::HashTable< T, Key, Hash >::const_iterator
An STL-conforming const_iterator.
Definition at line 470 of file HashTable.H.
Constructor & Destructor Documentation
const_iterator () inline
Construct null (end iterator)
Definition at line 426 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::iteratorBase().
Referenced by HashTable< T, Key, Hash >::cbegin(), and HashTable< T, Key, Hash >::const_iterator::const_iterator().
const_iterator (const iterator &) inline
Construct from iterator.
const_iterator (const iteratorEnd & unused) inline
Construct end iterator.
Definition at line 444 of file HashTableI.H.
References HashTable< T, Key, Hash >::const_iterator::const_iterator(), HashTable< T, Key, Hash >::iteratorBase::iteratorBase(), and Foam::T().
Member Function Documentation
const T & operator* () const inline
Return referenced hash value.
Definition at line 476 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::cobject(), and Foam::T().
const T & operator() () const inline
Definition at line 484 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::cobject().
Foam::HashTable< T, Key, Hash >::const_iterator & operator++ () inline
Definition at line 493 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::increment().
Foam::HashTable< T, Key, Hash >::const_iterator operator++ (int) inline
Definition at line 502 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::increment().
Friends And Related Function Documentation
friend class HashTable friend
Definition at line 474 of file HashTable.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/HashTables/HashTable/HashTableI.H