OpenFOAM-dev: cyclicSlipPointPatch Class Reference 2
cyclicSlipPointPatch Class Reference
Cyclic patch with slip constraint.
Public Member Functions
TypeName (cyclicSlipPolyPatch::typeName_())
Runtime type information.
cyclicSlipPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from components.
virtual ~cyclicSlipPointPatch ()
virtual const vectorField & pointNormals () const
Return point unit normals.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Public Member Functions inherited from cyclicPointPatch
TypeName (cyclicPolyPatch::typeName_())
Runtime type information.
cyclicPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from components.
virtual ~cyclicPointPatch ()
Destructor.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
const cyclicPolyPatch & cyclicPatch () const
Return the underlying cyclicPolyPatch.
const cyclicPointPatch & neighbPatch () const
Return neighbour point patch.
bool parallel () const
Are the cyclic planes parallel.
const tensorField & forwardT () const
Return face transformation tensor.
const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const edgeList & transformPairs () const
Return the set of pairs of points that require transformation.
Public Member Functions inherited from coupledFacePointPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFacePointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from components.
virtual ~coupledFacePointPatch ()
Destructor.
Public Member Functions inherited from facePointPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &, const pointBoundaryMesh &)
Construct from polyPatch.
virtual ~facePointPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label size () const
Return size.
virtual label index () const
Return the index of this patch in the pointBoundaryMesh.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const
Return mesh points.
virtual const pointField & localPoints () const
Return pointField of points in patch.
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()
Destructor.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
Public Member Functions inherited from coupledPointPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledPointPatch (const pointBoundaryMesh &bm)
Construct from components.
virtual ~coupledPointPatch ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from facePointPatch
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
Protected Attributes inherited from facePointPatch
const polyPatch & polyPatch_
Reference to the underlying polyPatch.
Detailed Description
Cyclic patch with slip constraint.
Source files
cyclicSlipPointPatch.H
cyclicSlipPointPatch.C
Definition at line 49 of file cyclicSlipPointPatch.H.
Constructor & Destructor Documentation
cyclicSlipPointPatch (const polyPatch & patch, const pointBoundaryMesh & bm) inline
Construct from components.
Definition at line 64 of file cyclicSlipPointPatch.H.
virtual ~cyclicSlipPointPatch () inline virtual
Definition at line 75 of file cyclicSlipPointPatch.H.
References cyclicSlipPointPatch::applyConstraint(), and cyclicSlipPointPatch::pointNormals().
Member Function Documentation
TypeName (cyclicSlipPolyPatch::typeName_())
Runtime type information.
const vectorField & pointNormals () const virtual
Return point unit normals.
Reimplemented from facePointPatch.
Definition at line 49 of file cyclicSlipPointPatch.C.
References cyclicSlipPointPatch::applyConstraint(), and facePointPatch::pointNormals().
Referenced by cyclicSlipPointPatch::applyConstraint(), and cyclicSlipPointPatch::~cyclicSlipPointPatch().
void applyConstraint (const label pointi, pointConstraint & pc) const virtual
Accumulate the effect of constraint direction of this patch.
Reimplemented from pointPatch.
Definition at line 60 of file cyclicSlipPointPatch.C.
References pointConstraint::applyConstraint(), and cyclicSlipPointPatch::pointNormals().
Referenced by cyclicSlipPointPatch::pointNormals(), and cyclicSlipPointPatch::~cyclicSlipPointPatch().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/cyclicSlip/cyclicSlipPointPatch.H
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/cyclicSlip/cyclicSlipPointPatch.C