OpenFOAM: coordinateSystems Class Reference
coordinateSystems Class Reference
Provides a centralized coordinateSystem collection.
Public Member Functions
TypeName ("coordinateSystems")
Runtime type information.
coordinateSystems (const IOobject &)
Read construct from IOobject.
coordinateSystems (const IOobject &, const PtrList< coordinateSystem > &)
Construct from IOobject and a PtrList.
coordinateSystems (const IOobject &, const Xfer< PtrList< coordinateSystem >> &)
Construct from IOobject and transferring the PtrList contents.
labelList findIndices (const keyType &key) const
Find and return indices for all matches.
label findIndex (const keyType &key) const
Find and return index for the first match, return -1 if not found.
bool found (const keyType &key) const
Search for given key.
wordList toc () const
Return the table of contents (list of all keywords)
bool writeData (Ostream &) const
Write data.
Public Member Functions inherited from IOPtrList< coordinateSystem >
TypeName ("PtrList")
Runtime type information.
IOPtrList (const IOobject &, const INew &)
Construct from IOobject using given Istream constructor class.
IOPtrList (const IOobject &)
Construct from IOobject.
IOPtrList (const IOobject &, const label)
Construct from IOobject with given size.
IOPtrList (const IOobject &, const PtrList< coordinateSystem > &)
Construct from IOobject and a PtrList.
IOPtrList (const IOobject &, const Xfer< PtrList< coordinateSystem >> &)
Construct by transferring the PtrList contents.
virtual ~IOPtrList ()
Destructor.
bool writeData (Ostream &) const
Pure virtual writaData function.
void operator= (const IOPtrList< coordinateSystem > &)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from PtrList< coordinateSystem >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< coordinateSystem > &)
Copy constructor.
PtrList (const PtrList< coordinateSystem > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< coordinateSystem >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< coordinateSystem > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< coordinateSystem > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (coordinateSystem *)
Append an element at the end of the list.
void append (const autoPtr< coordinateSystem > &)
void append (const tmp< coordinateSystem > &)
void transfer (PtrList< coordinateSystem > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< coordinateSystem > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< coordinateSystem > set (const label, coordinateSystem *)
Set element to given T* and return old element (can be NULL)
autoPtr< coordinateSystem > set (const label, const autoPtr< coordinateSystem > &)
Set element to given autoPtr<T> and return old element.
autoPtr< coordinateSystem > set (const label, const tmp< coordinateSystem > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< coordinateSystem > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Static Public Member Functions
static const coordinateSystems & New (const objectRegistry &)
Return previously registered or read construct from "constant".
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from PtrList< coordinateSystem >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Provides a centralized coordinateSystem collection.
Note
Mixing normal constructors and the coordinateSystems::New constructor may yield unexpected results.
    1
    (
    cat1
    {
        coordinateSystem  system_10;
        porosity        0.781;
        Darcy
        {
            d   d [0 -2 0 0 0]  (-1000 -1000 0.50753e+08);
            f   f [0 -1 0 0 0]  (-1000 -1000 12.83);
        }
    }
    )
For this to work correctly, the coordinateSystem constructor must be supplied with both a dictionary and an objectRegistry.
Source files
coordinateSystems.H
coordinateSystems.C
Definition at line 71 of file coordinateSystems.H.
Constructor & Destructor Documentation
coordinateSystems (const IOobject & io) explicit
Read construct from IOobject.
Definition at line 41 of file coordinateSystems.C.
coordinateSystems (const IOobject & io, const PtrList< coordinateSystem > & lst)
Construct from IOobject and a PtrList.
Definition at line 48 of file coordinateSystems.C.
coordinateSystems (const IOobject & io, const Xfer< PtrList< coordinateSystem >> & lst)
Construct from IOobject and transferring the PtrList contents.
Definition at line 58 of file coordinateSystems.C.
References coordinateSystems::New().
Member Function Documentation
TypeName ("coordinateSystems")
Runtime type information.
const Foam::coordinateSystems & New (const objectRegistry & obr) static
Return previously registered or read construct from "constant".
Definition at line 71 of file coordinateSystems.C.
References TimePaths::constant(), objectRegistry::foundObject(), objectRegistry::lookupObject(), IOobject::NO_WRITE, IOobject::READ_IF_PRESENT, regIOobject::store(), and objectRegistry::time().
Referenced by coordinateSystem::coordinateSystem(), and coordinateSystems::coordinateSystems().
Foam::labelList findIndices (const keyType & key) const
Find and return indices for all matches.
Definition at line 101 of file coordinateSystems.C.
References Foam::findStrings(), forAll, keyType::isPattern(), IOobject::name(), List< T >::setSize(), UPtrList< T >::size(), and coordinateSystems::toc().
Referenced by coordinateSystems::findIndex().
Foam::label findIndex (const keyType & key) const
Find and return index for the first match, return -1 if not found.
Definition at line 126 of file coordinateSystems.C.
References UList< T >::empty(), coordinateSystems::findIndices(), forAll, keyType::isPattern(), and IOobject::name().
Referenced by coordinateSystems::found().
bool found (const keyType & key) const
Search for given key.
Definition at line 152 of file coordinateSystems.C.
References coordinateSystems::findIndex().
Foam::wordList toc () const
Return the table of contents (list of all keywords)
Definition at line 158 of file coordinateSystems.C.
References forAll, UPtrList< T >::operator[](), and UPtrList< T >::size().
Referenced by coordinateSystems::findIndices().
bool writeData (Ostream & os) const virtual
Write data.
Implements regIOobject.
Definition at line 171 of file coordinateSystems.C.
References token::BEGIN_LIST, token::END_LIST, forAll, IOstream::good(), Foam::nl, UPtrList< T >::operator[](), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/coordinateSystems.H
src/meshTools/coordinateSystems/coordinateSystems.C