OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CrankNicolsonDdtScheme< Type > Class Template Reference
Second-oder Crank-Nicolson implicit ddt using the current and previous time-step fields as well as the previous time-step ddt.
Public Types
typedef ddtScheme< Type >
::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField
< typename flux< Type >::type,
fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("CrankNicolson")
Runtime type information.
CrankNicolsonDdtScheme (const fvMesh &mesh)
Construct from mesh.
CrankNicolsonDdtScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
const fvMesh & mesh () const
Return mesh reference.
scalar ocCoeff () const
Return the off-centreing coefficient.
tmp< GeometricField< Type,
fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
template<class GeoField >
CrankNicolsonDdtScheme< Type >
::DDt0Field< GeoField > & ddt0_ (const word &name, const dimensionSet &dims)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
Construct from mesh.
ddtScheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~ddtScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new ddtScheme created on freestore.
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)
Disallow copy construct.
void operator= (const ddtScheme &)
Disallow default bitwise assignment.
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::CrankNicolsonDdtScheme< Type >
Second-oder Crank-Nicolson implicit ddt using the current and previous time-step fields as well as the previous time-step ddt.
The Crank-Nicolson scheme is often unstable for complex flows in complex geometries and it is necessary to "off-centre" the scheme to stabilize it while retaining greater temporal accuracy than the first-order Euler-implicit scheme. Off-centering is specified via the mandatory coefficient in the range [0,1] following the scheme name e.g.
ddtSchemes
{
    default         CrankNicolson 0.9;
}
With a coefficient of 1 the scheme is fully centred and second-order, with a coefficient of 0 the scheme is equivalent to Euler-implicit. A coefficient of 0.9 has been found to be suitable for a range of cases for which higher-order accuracy in time is needed and provides similar accuracy and stability to the backward scheme. However, the backward scheme has been found to be more robust and provides formal second-order accuracy in time.
The advantage of the Crank-Nicolson scheme over backward is that only the new and old-time values are needed, the additional terms relating to the fluxes and sources are evaluated at the mid-point of the time-step which provides the opportunity to limit the fluxes in such a way as to ensure boundedness while maintaining greater accuracy in time compared to the Euler-implicit scheme. This approach is now used with MULES in the interFoam family of solvers. Boundedness cannot be guaranteed with the backward scheme.
Note
The Crank-Nicolson coefficient for the implicit part of the RHS is related to the off-centering coefficient by
    cnCoeff = 1.0/(1.0 + ocCoeff);
See Also
Foam::Euler Foam::backward
Source files
CrankNicolsonDdtScheme.H
CrankNicolsonDdtScheme.C
Definition at line 94 of file CrankNicolsonDdtScheme.H.
Member Typedef Documentation
typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 288 of file CrankNicolsonDdtScheme.H.
Constructor & Destructor Documentation
CrankNicolsonDdtScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 196 of file CrankNicolsonDdtScheme.H.
CrankNicolsonDdtScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 203 of file CrankNicolsonDdtScheme.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorIn.
Member Function Documentation
TypeName ("CrankNicolson")
Runtime type information.
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 224 of file CrankNicolsonDdtScheme.H.
References ddtScheme< Type >::mesh().
scalar ocCoeff () const inline
Return the off-centreing coefficient.
Definition at line 230 of file CrankNicolsonDdtScheme.H.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 285 of file CrankNicolsonDdtScheme.C.
References dimensioned< Type >::dimensions(), Foam::dimTime, mesh, and dimensioned< Type >::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 347 of file CrankNicolsonDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fv::ff(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 436 of file CrankNicolsonDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fv::ff(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, dimensioned< Type >::name(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and dimensioned< Type >::value().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 526 of file CrankNicolsonDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fv::ff(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 626 of file CrankNicolsonDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fv::ff(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 756 of file CrankNicolsonDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, Foam::fv::ff(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and fvMatrix< Type >::source().
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 838 of file CrankNicolsonDdtScheme.C.
References lduMatrix::diag(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, Foam::fv::ff(), mesh, dimensioned< Type >::name(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), fvMatrix< Type >::source(), and dimensioned< Type >::value().
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 920 of file CrankNicolsonDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, Foam::fv::ff(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and fvMatrix< Type >::source().
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 1010 of file CrankNicolsonDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, Foam::fv::ff(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and fvMatrix< Type >::source().
tmp< typename CrankNicolsonDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 1121 of file CrankNicolsonDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::fvc::interpolate(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< typename CrankNicolsonDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 1182 of file CrankNicolsonDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::fvc::interpolate(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< typename CrankNicolsonDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 1243 of file CrankNicolsonDdtScheme.C.
References Foam::abort(), Foam::fvc::ddtCorr(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::FatalError, FatalErrorIn, Foam::fvc::interpolate(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< typename CrankNicolsonDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 1340 of file CrankNicolsonDdtScheme.C.
References Foam::abort(), Foam::fvc::ddtCorr(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::FatalError, FatalErrorIn, Foam::fvc::interpolate(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 1436 of file CrankNicolsonDdtScheme.C.
References Foam::dimVolume, mesh, Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, phi, and timeName.
CrankNicolsonDdtScheme<Type>::DDt0Field<GeoField>& ddt0_ (const word & name, const dimensionSet & dims)
Definition at line 106 of file CrankNicolsonDdtScheme.C.
References IOobject::AUTO_WRITE, Foam::dimTime, mesh, IOobject::MUST_READ, Foam::name(), IOobject::NO_READ, Time::startTime(), Time::startTimeIndex(), regIOobject::store(), TimeState::timeIndex(), timeName, Time::timeName(), and dimensioned< Type >::value().
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/CrankNicolsonDdtScheme/CrankNicolsonDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/CrankNicolsonDdtScheme/CrankNicolsonDdtScheme.C