OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cyclicSlipPointPatchField< Type > Class Template Reference
Cyclic + slip constraints.
Public Member Functions
TypeName (cyclicSlipPointPatch::typeName_())
Runtime type information.
cyclicSlipPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
cyclicSlipPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
cyclicSlipPointPatchField (const cyclicSlipPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
virtual autoPtr
< pointPatchField< Type > > clone () const
Construct and return a clone.
cyclicSlipPointPatchField (const cyclicSlipPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr
< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
Public Member Functions inherited from cyclicPointPatchField< Type >
TypeName (cyclicPointPatch::typeName_())
Runtime type information.
cyclicPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
cyclicPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
cyclicPointPatchField (const cyclicPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
cyclicPointPatchField (const cyclicPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual const word & constraintType () const
Constraint handling.
virtual bool doTransform () const
Cyclic coupled interface functions.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual void swapAddSeparated (const Pstream::commsTypes commsType, Field< Type > &) const
Complete swap of patch point values and add to local values.
Public Member Functions inherited from coupledPointPatchField< Type >
TypeName (coupledPointPatch::typeName_())
Runtime type information.
coupledPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
coupledPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &dict)
Construct from patch, internal field and dictionary.
coupledPointPatchField (const coupledPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
coupledPointPatchField (const coupledPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual bool coupled () const
Return true if this patch field is derived from.
virtual void initSwapAddSeparated (const Pstream::commsTypes, Field< Type > &) const
Initialise swap of patch point values.
Public Member Functions inherited from pointPatchField< Type >
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type,
pointMesh > & dimensionedInternalField () const
Return dimensioned internal field reference.
const Field< Type > & internalField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void write (Ostream &) const
Write.
virtual void operator= (const pointPatchField< Type > &)
virtual void operator= (const Field< Type > &)
virtual void operator= (const Type &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator+= (const Type &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator-= (const Type &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator*= (const scalar)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
Additional Inherited Members
Public Types inherited from pointPatchField< Type >
typedef pointPatch Patch
Static Public Member Functions inherited from pointPatchField< Type >
static autoPtr
< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr
< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr
< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr
< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static autoPtr
< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new CalculatedpointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Attributes inherited from pointPatchField< Type >
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Detailed Description
template<class Type>
class Foam::cyclicSlipPointPatchField< Type >
Cyclic + slip constraints.
Source files
cyclicSlipPointPatchField.H
cyclicSlipPointPatchField.C
Definition at line 50 of file cyclicSlipPointPatchField.H.
Constructor & Destructor Documentation
cyclicSlipPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file cyclicSlipPointPatchField.C.
cyclicSlipPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 46 of file cyclicSlipPointPatchField.C.
cyclicSlipPointPatchField (const cyclicSlipPointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Construct by mapping given patchField<Type> onto a new patch.
Definition at line 58 of file cyclicSlipPointPatchField.C.
cyclicSlipPointPatchField (const cyclicSlipPointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 71 of file cyclicSlipPointPatchField.C.
Member Function Documentation
TypeName (cyclicSlipPointPatch:: typeName_())
Runtime type information.
virtual autoPtr<pointPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from cyclicPointPatchField< Type >.
Definition at line 88 of file cyclicSlipPointPatchField.H.
virtual autoPtr<pointPatchField<Type> > clone (const DimensionedField< Type, pointMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from cyclicPointPatchField< Type >.
Definition at line 108 of file cyclicSlipPointPatchField.H.
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Evaluate the patch field.
Reimplemented from cyclicPointPatchField< Type >.
Definition at line 83 of file cyclicSlipPointPatchField.C.
References Foam::I, internalField(), Foam::sqr(), and Foam::transform().
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/pointPatchFields/constraint/cyclicSlip/cyclicSlipPointPatchField.H
src/OpenFOAM/fields/pointPatchFields/constraint/cyclicSlip/cyclicSlipPointPatchField.C