OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dampedCoulomb Class Reference
Public Member Functions
TypeName ("dampedCoulomb")
Runtime type information.
dampedCoulomb (const word &name, const dictionary &pairPotentialProperties)
Construct from components.
~dampedCoulomb ()
Destructor.
scalar unscaledEnergy (const scalar r) const
bool read (const dictionary &pairPotentialProperties)
Read dictionary.
Public Member Functions inherited from pairPotential
TypeName ("pairPotential")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pairPotential, dictionary,(const word &name, const dictionary &pairPotentialProperties),(name, pairPotentialProperties))
pairPotential (const word &name, const dictionary &pairPotentialProperties)
Construct from components.
virtual ~pairPotential ()
Destructor.
void setLookupTables ()
scalar rMin () const
scalar dr () const
scalar rCut () const
scalar rCutSqr () const
scalar energy (const scalar r) const
scalar force (const scalar r) const
List< Pair< scalar > > energyTable () const
List< Pair< scalar > > forceTable () const
bool writeTables () const
scalar scaledEnergy (const scalar r) const
scalar energyDerivative (const scalar r, const bool scaledEnergyDerivative=true) const
const dictionary & pairPotentialProperties () const
bool writeEnergyAndForceTables (Ostream &os) const
Static Public Attributes
static scalar oneOverFourPiEps0
Additional Inherited Members
Static Public Member Functions inherited from pairPotential
static autoPtr< pairPotential > New (const word &name, const dictionary &pairPotentialProperties)
Return a reference to the selected viscosity model.
Protected Member Functions inherited from pairPotential
void scaleEnergy (scalar &e, const scalar r) const
pairPotential (const pairPotential &)
Disallow copy construct.
void operator= (const pairPotential &)
Disallow default bitwise assignment.
Protected Attributes inherited from pairPotential
word name_
dictionary pairPotentialProperties_
scalar rCut_
scalar rCutSqr_
scalar rMin_
scalar dr_
List< scalar > forceLookup_
List< scalar > energyLookup_
energyScalingFunction * esfPtr_
bool writeTables_
Detailed Description
Source files
dampedCoulomb.H
dampedCoulomb.C
Definition at line 50 of file dampedCoulomb.H.
Constructor & Destructor Documentation
dampedCoulomb (const word & name, const dictionary & pairPotentialProperties)
Construct from components.
Definition at line 55 of file dampedCoulomb.C.
~dampedCoulomb () inline
Destructor.
Definition at line 83 of file dampedCoulomb.H.
Member Function Documentation
TypeName ("dampedCoulomb")
Runtime type information.
scalar unscaledEnergy (const scalar r) const virtual
Implements pairPotential.
Definition at line 73 of file dampedCoulomb.C.
References Foam::erfc(), and dampedCoulomb::oneOverFourPiEps0.
bool read (const dictionary & pairPotentialProperties) virtual
Read dictionary.
Implements pairPotential.
Definition at line 79 of file dampedCoulomb.C.
References dictionary::lookup(), pairPotential::read(), and dictionary::subDict().
Member Data Documentation
scalar oneOverFourPiEps0 static
Initial value:
=
    1.0/(4.0*constant::mathematical::pi*8.854187817e-12)
Definition at line 69 of file dampedCoulomb.H.
Referenced by dampedCoulomb::unscaledEnergy().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/pairPotential/derived/dampedCoulomb/dampedCoulomb.H
src/lagrangian/molecularDynamics/potential/pairPotential/derived/dampedCoulomb/dampedCoulomb.C