OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cylinderAnnulusToCell Class Reference
A topoSetSource to select cells based on cell centres inside a cylinder annulus.
Public Member Functions
TypeName ("cylinderAnnulusToCell")
Runtime type information.
cylinderAnnulusToCell (const polyMesh &mesh, const vector &p1, const vector &p2, const scalar outerRadius, const scalar innerRadius)
Construct from components.
cylinderAnnulusToCell (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
cylinderAnnulusToCell (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~cylinderAnnulusToCell ()
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label cellI, const bool) const
Add (if bool) cellI to set or delete cellI from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = NULL
A table of usage strings.
Detailed Description
A topoSetSource to select cells based on cell centres inside a cylinder annulus.
Source files
cylinderAnnulusToCell.H
cylinderAnnulusToCell.C
Definition at line 49 of file cylinderAnnulusToCell.H.
Constructor & Destructor Documentation
cylinderAnnulusToCell (const polyMesh & mesh, const vector & p1, const vector & p2, const scalar outerRadius, const scalar innerRadius)
Construct from components.
Definition at line 80 of file cylinderAnnulusToCell.C.
Referenced by cylinderAnnulusToCell::cylinderAnnulusToCell().
cylinderAnnulusToCell (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 97 of file cylinderAnnulusToCell.C.
References cylinderAnnulusToCell::cylinderAnnulusToCell().
cylinderAnnulusToCell (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 112 of file cylinderAnnulusToCell.C.
~cylinderAnnulusToCell () virtual
Definition at line 127 of file cylinderAnnulusToCell.C.
References cylinderAnnulusToCell::applyToSet().
Member Function Documentation
TypeName ("cylinderAnnulusToCell")
Runtime type information.
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 115 of file cylinderAnnulusToCell.H.
References cylinderAnnulusToCell::applyToSet(), and topoSetSource::CELLSETSOURCE.
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 134 of file cylinderAnnulusToCell.C.
References topoSetSource::ADD, Foam::ListListOps::combine(), topoSetSource::DELETE, Foam::endl(), Foam::Info, and topoSetSource::NEW.
Referenced by cylinderAnnulusToCell::setType(), and cylinderAnnulusToCell::~cylinderAnnulusToCell().
The documentation for this class was generated from the following files:
src/meshTools/sets/cellSources/cylinderAnnulusToCell/cylinderAnnulusToCell.H
src/meshTools/sets/cellSources/cylinderAnnulusToCell/cylinderAnnulusToCell.C