OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CSV< Type > Class Template Reference
Templated CSV container data entry. Reference column is always a scalar, e.g. time.
Public Member Functions
TypeName ("csvFile")
Runtime type information.
CSV (const word &entryName, const dictionary &dict, const word &ext="Coeffs")
Construct from entry name and dictionary.
CSV (const CSV< Type > &tbl)
Copy constructor.
virtual tmp< Function1< Type > > clone () const
Construct and return a clone.
virtual ~CSV ()
Destructor.
virtual const fileName & fName () const
Return const access to the file name.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from TableBase< Type >
TableBase (const word &name, const dictionary &dict)
Construct from dictionary - note table is not populated.
TableBase (const TableBase< Type > &tbl)
Copy constructor. Note: steals interpolator, tableSamples.
virtual ~TableBase ()
Destructor.
word boundsHandlingToWord (const boundsHandling &bound) const
Return the out-of-bounds handling as a word.
boundsHandling wordToBoundsHandling (const word &bound) const
Return the out-of-bounds handling as an enumeration.
boundsHandling outOfBounds (const boundsHandling &bound)
Set the out-of-bounds handling from enum, return previous setting.
void check () const
Check the table for size and consistency.
bool checkMinBounds (const scalar x, scalar &xDash) const
Check minimum table bounds.
bool checkMaxBounds (const scalar x, scalar &xDash) const
Check maximum table bounds.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return Table value.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual tmp< scalarField > x () const
Return the reference values.
virtual tmp< Field< Type > > y () const
Return the dependent values.
virtual void writeEntries (Ostream &os) const
Write keywords only in dictionary format. Used for non-inline.
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Runtime type information.
Function1 (const word &entryName)
Construct from entry name.
Function1 (const Function1< Type > &de)
Copy constructor.
virtual ~Function1 ()
Destructor.
const word & name () const
Return the name of the entry.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Public Types inherited from TableBase< Type >
enum boundsHandling { ERROR, WARN, CLAMP, REPEAT }
Enumeration for handling out-of-bound values.
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Member Functions inherited from TableBase< Type >
const interpolationWeights & interpolator () const
Return (demand driven) interpolator.
void operator= (const TableBase< Type > &)
Disallow default bitwise assignment.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes inherited from TableBase< Type >
const word name_
Table name.
const boundsHandling boundsHandling_
Enumeration for handling out-of-bound values.
const word interpolationScheme_
Interpolation type.
List< Tuple2< scalar, Type > > table_
Table data.
autoPtr< scalarField > tableSamplesPtr_
Extracted values.
autoPtr< interpolationWeights > interpolatorPtr_
Interpolator method.
labelList currentIndices_
Cached indices and weights.
scalarField currentWeights_
Protected Attributes inherited from Function1< Type >
const word name_
Name of entry.
Detailed Description
template<class Type>
class Foam::Function1Types::CSV< Type >
Templated CSV container data entry. Reference column is always a scalar, e.g. time.
    <entryName> csvFile;
    <entryName>Coeffs
    {
        nHeaderLine         4;          // number of header lines
        refColumn           0;          // reference column index
        componentColumns    (1 2 3);    // component column indices
        separator           ",";        // optional (defaults to ",")
        mergeSeparators     no;         // merge multiple separators
        fileName            "fileXYZ";  // name of csv data file
        outOfBounds         clamp;      // optional out-of-bounds handling
        interpolationScheme linear;     // optional interpolation scheme
    }
Source files
CSV.H
CSV.C
Definition at line 71 of file CSV.H.
Constructor & Destructor Documentation
CSV (const word & entryName, const dictionary & dict, const word & ext = "Coeffs")
Construct from entry name and dictionary.
Definition at line 204 of file CSV.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::read().
CSV (const CSV< Type > & tbl)
Copy constructor.
Definition at line 234 of file CSV.C.
~CSV () virtual
Destructor.
Definition at line 249 of file CSV.C.
Referenced by CSV< Type >::clone().
Member Function Documentation
TypeName ("csvFile")
Runtime type information.
virtual tmp<Function1<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from Function1< Type >.
Definition at line 131 of file CSV.H.
References CSV< Type >::fName(), CSV< Type >::writeData(), and CSV< Type >::~CSV().
const Foam::fileName & fName () const virtual
Return const access to the file name.
Definition at line 256 of file CSV.C.
Referenced by CSV< Type >::clone().
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented from TableBase< Type >.
Definition at line 263 of file CSV.C.
References IOstream::ASCII, token::BEGIN_BLOCK, IOstream::BINARY, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), IOstream::format(), Foam::incrIndent(), Foam::indent(), Function1< Type >::name(), Foam::nl, Function1< Type >::writeData(), TableBase< Type >::writeEntries(), and Ostream::writeKeyword().
Referenced by CSV< Type >::clone().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/CSV/CSV.H
src/OpenFOAM/primitives/functions/Function1/CSV/CSV.C