OpenFOAM: csvSetWriter< Type > Class Template Reference
csvSetWriter< Type > Class Template Reference
Write set in csv format.
Public Member Functions
TypeName ("csv")
Runtime type information.
csvSetWriter ()
Construct null.
virtual ~csvSetWriter ()
Destructor.
virtual fileName getFileName (const coordSet &, const wordList &) const
Generate file name with correct extension.
virtual void write (const coordSet &, const wordList &, const List< const Field< Type > * > &, Ostream &) const
General entry point for writing.
virtual void write (const bool writeTracks, const PtrList< coordSet > &, const wordList &valueSetNames, const List< List< Field< Type >>> &, Ostream &) const
General entry point for writing of multiple coordSets.
Public Member Functions inherited from writer< Type >
TypeName ("writer")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, writer, word,(),())
writer ()
Construct null.
virtual ~writer ()=0
Destructor.
virtual void write (const coordSet &, const wordList &, const List< Field< Type >> &, Ostream &) const
General entry point for writing.
virtual Ostream & write (const scalar, Ostream &) const
Write scalar as ascii.
template<class VSType >
Ostream & writeVS (const VSType &, Ostream &) const
virtual Ostream & write (const vector &, Ostream &) const
Write vector. Tab separated ascii.
virtual Ostream & write (const sphericalTensor &, Ostream &) const
Write sphericalTensor. Tab separated ascii.
virtual Ostream & write (const symmTensor &, Ostream &) const
Write symmTensor. Tab separated ascii.
virtual Ostream & write (const tensor &, Ostream &) const
Write tensor. Tab separated ascii.
template<class VSType >
Foam::Ostream & writeVS (const VSType &value, Ostream &os) const
Protected Member Functions
virtual void writeSeparator (Ostream &) const
Writes a separator. Used by write functions.
Protected Member Functions inherited from writer< Type >
fileName getBaseName (const coordSet &, const wordList &) const
Generates filename from coordSet and sampled fields.
void writeCoord (const coordSet &, const label sampleI, Ostream &) const
void writeTable (const coordSet &, const List< Type > &, Ostream &) const
Writes single-column ascii write. Column 1 is coordSet coordinate,.
void writeTable (const coordSet &, const List< const List< Type > * > &, Ostream &os) const
Writes multi-column ascii write. Column 1 is coordSet coordinate,.
Additional Inherited Members
Static Public Member Functions inherited from writer< Type >
static autoPtr< writer > New (const word &writeFormat)
Return a reference to the selected writer.
Detailed Description
template<class Type>
class Foam::csvSetWriter< Type >
Write set in csv format.
Source files
csvSetWriter.H
csvSetWriter.C
Definition at line 49 of file csvSetWriter.H.
Constructor & Destructor Documentation
csvSetWriter ()
Construct null.
Definition at line 34 of file csvSetWriter.C.
~csvSetWriter () virtual
Destructor.
Definition at line 43 of file csvSetWriter.C.
References csvSetWriter< Type >::getFileName().
Member Function Documentation
void writeSeparator (Ostream & os) const protected virtual
Writes a separator. Used by write functions.
Reimplemented from writer< Type >.
Definition at line 120 of file csvSetWriter.C.
References coordSet::axis(), token::COMMA, forAll, coordSet::hasVectorAxis(), and Foam::nl.
TypeName ("csv")
Runtime type information.
Foam::fileName getFileName (const coordSet & , const wordList &) const virtual
Generate file name with correct extension.
Implements writer< Type >.
Definition at line 51 of file csvSetWriter.C.
References writer< Type >::getBaseName(), and csvSetWriter< Type >::write().
Referenced by csvSetWriter< Type >::~csvSetWriter().
void write (const coordSet & , const wordList & , const List< const Field< Type > * > & , Ostream &) const virtual
General entry point for writing.
The data is organized in a set of point with one or more values per point
Implements writer< Type >.
Definition at line 62 of file csvSetWriter.C.
References forAll, and writer< Type >::writeTable().
Referenced by csvSetWriter< Type >::getFileName().
void write (const bool writeTracks, const PtrList< coordSet > & , const wordList & valueSetNames, const List< List< Field< Type >>> & , Ostream &) const virtual
General entry point for writing of multiple coordSets.
Each coordSet (track) has same data variables. The data is per variable, per track, per point of track. If writeTracks adds connecting lines (wherever applicable)
Implements writer< Type >.
Definition at line 85 of file csvSetWriter.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, List< T >::size(), and writer< Type >::writeTable().
The documentation for this class was generated from the following files:
src/fileFormats/sampledSetWriters/csv/csvSetWriter.H
src/fileFormats/sampledSetWriters/csv/csvSetWriter.C