OpenFOAM: coordSet Class Reference
coordSet Class Reference
Holds list of sampling positions.
Public Types
enum coordFormat {
XYZ, X, Y, Z,
DISTANCE
}
Enumeration defining the output format for coordinates.
Public Types inherited from Field< vector >
typedef pTraits< vector >::cmptType cmptType
Component type.
typedef SubField< vector > subField
Declare type of subField.
Public Types inherited from List< vector >
typedef SubList< vector > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
coordSet (const word &name, const word &axis)
Construct from components.
coordSet (const word &name, const word &axis, const List< point > &points, const scalarList &curveDist)
Construct from components.
const word & name () const
word axis () const
const scalarList & curveDist () const
Cumulative distance.
bool hasVectorAxis () const
Is axis specification a vector.
scalar scalarCoord (const label index) const
Get coordinate of point according to axis specification.
vector vectorCoord (const label index) const
Get point according to axis="xyz" specification.
Ostream & write (Ostream &os) const
Public Member Functions inherited from Field< vector >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const vector &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< vector > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< vector >> &)
Construct by transferring the List contents.
Field (const UList< vector > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< vector > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< vector >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< vector > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< vector > &mapF, const FieldMapper &map, const vector &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< vector > &mapF, const FieldMapper &map, const UList< vector > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const vector &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const UList< vector > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< vector > &)
Construct as copy.
Field (Field< vector > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< vector >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< vector >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< vector > > clone () const
Clone.
void map (const UList< vector > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< vector > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< vector >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< vector > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< vector > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< vector > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
VSForm block (const label start) const
tmp< Field< vector > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< vector > &)
void operator= (const UList< vector > &)
void operator= (const SubField< vector > &)
void operator= (const tmp< Field< vector >> &)
void operator= (const vector &)
void operator= (const zero)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< vector > &)
void operator+= (const tmp< Field< vector >> &)
void operator+= (const vector &)
void operator-= (const UList< vector > &)
void operator-= (const tmp< Field< vector >> &)
void operator-= (const vector &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator*= (const scalar &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< vector >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const vector &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< vector > &)
Copy constructor.
List (const Xfer< List< vector >> &)
Construct by transferring the parameter contents.
List (List< vector > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< vector > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< vector, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< vector > &)
Construct as copy of PtrList<T>
List (const SLList< vector > &)
Construct as copy of SLList<T>
List (const UIndirectList< vector > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< vector > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< vector > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const vector &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const vector &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const vector &)
Append an element at the end of the list.
void append (const UList< vector > &)
Append a List at the end of this list.
void append (const UIndirectList< vector > &)
Append a UIndirectList at the end of this list.
void transfer (List< vector > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< vector, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< vector > &)
Transfer the contents of the argument List into this list.
Xfer< List< vector > > xfer ()
Transfer contents to the Xfer container.
vector & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< vector > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< vector > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< vector > &)
Assignment operator. Takes linear time.
void operator= (const SLList< vector > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< vector > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< vector > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const vector &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Protected Attributes
const word name_
Name.
const coordFormat axis_
Axis write type.
scalarList curveDist_
Cumulative distance "distance" write specifier.
Additional Inherited Members
Static Public Member Functions inherited from Field< vector >
static const Field< vector > & null ()
Return a null field.
static tmp< Field< vector > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< vector >
static const List< vector > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes inherited from Field< vector >
static const char *const typeName
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< vector >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
Holds list of sampling positions.
Source files
coordSet.H
coordSet.C
Definition at line 49 of file coordSet.H.
Member Enumeration Documentation
enum coordFormat
Enumeration defining the output format for coordinates.
Enumerator
XYZ
X
Y
Z
DISTANCE
Definition at line 59 of file coordSet.H.
Constructor & Destructor Documentation
coordSet (const word & name, const word & axis)
Construct from components.
Definition at line 55 of file coordSet.C.
Referenced by NamedEnum< Enum, nEnum >::names().
coordSet (const word & name, const word & axis, const List< point > & points, const scalarList & curveDist)
Construct from components.
Definition at line 68 of file coordSet.C.
Member Function Documentation
const word& name () const inline
Definition at line 111 of file coordSet.H.
References coordSet::name_.
Referenced by writer< Type >::getBaseName(), sampledSet::iNew::operator()(), xmgraceSetWriter< Type >::write(), gnuplotSetWriter< Type >::write(), vtkSetWriter< Type >::write(), and jplotSetWriter< Type >::write().
word axis () const inline
Definition at line 116 of file coordSet.H.
References coordSet::axis_.
Referenced by sampledSet::iNew::operator()(), xmgraceSetWriter< Type >::write(), and csvSetWriter< Type >::writeSeparator().
const scalarList& curveDist () const inline
Cumulative distance.
Definition at line 122 of file coordSet.H.
References coordSet::curveDist_, coordSet::hasVectorAxis(), coordSet::scalarCoord(), coordSet::vectorCoord(), and coordSet::write().
bool hasVectorAxis () const
Is axis specification a vector.
Definition at line 84 of file coordSet.C.
References coordSet::scalarCoord().
Referenced by coordSet::curveDist(), writer< Type >::writeCoord(), and csvSetWriter< Type >::writeSeparator().
Foam::scalar scalarCoord (const label index) const
Get coordinate of point according to axis specification.
If axis="distance" is the curveDist[index]
Definition at line 91 of file coordSet.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, p, Vector< Cmpt >::x(), Y, Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by coordSet::curveDist(), coordSet::hasVectorAxis(), and writer< Type >::writeCoord().
Foam::point vectorCoord (const label index) const
Get point according to axis="xyz" specification.
Definition at line 126 of file coordSet.C.
References p.
Referenced by coordSet::curveDist(), and writer< Type >::writeCoord().
Foam::Ostream & write (Ostream & os) const
Definition at line 134 of file coordSet.C.
References Foam::endl(), and forAll.
Referenced by coordSet::curveDist(), and sampledSet::write().
Member Data Documentation
const word name_ protected
Name.
Definition at line 78 of file coordSet.H.
Referenced by coordSet::name().
const coordFormat axis_ protected
Axis write type.
Definition at line 81 of file coordSet.H.
Referenced by coordSet::axis().
scalarList curveDist_ protected
Cumulative distance "distance" write specifier.
Definition at line 84 of file coordSet.H.
Referenced by coordSet::curveDist().
The documentation for this class was generated from the following files:
src/fileFormats/coordSet/coordSet.H
src/fileFormats/coordSet/coordSet.C