OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cyclicPointPatch Class Reference
Cyclic patch for post-processing.
Public Member Functions
TypeName (cyclicPolyPatch::typeName_())
Runtime type information.
cyclicPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from components.
virtual ~cyclicPointPatch ()
Destructor.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
const cyclicPolyPatch & cyclicPatch () const
Return the underlying cyclicPolyPatch.
const cyclicPointPatch & neighbPatch () const
Return neighbour point patch.
bool parallel () const
Are the cyclic planes parallel.
const tensorField & forwardT () const
Return face transformation tensor.
const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const edgeList & transformPairs () const
Return the set of pairs of points that require transformation.
Public Member Functions inherited from coupledFacePointPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFacePointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from components.
virtual ~coupledFacePointPatch ()
Destructor.
Public Member Functions inherited from facePointPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &, const pointBoundaryMesh &)
Construct from polyPatch.
virtual ~facePointPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label size () const
Return size.
virtual label index () const
Return the index of this patch in the pointBoundaryMesh.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const
Return mesh points.
virtual const pointField & localPoints () const
Return pointField of points in patch.
virtual const vectorField & pointNormals () const
Return point unit normals.
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()
Destructor.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Public Member Functions inherited from coupledPointPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledPointPatch (const pointBoundaryMesh &bm)
Construct from components.
virtual ~coupledPointPatch ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from facePointPatch
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
Protected Attributes inherited from facePointPatch
const polyPatch & polyPatch_
Reference to the underlying polyPatch.
Detailed Description
Cyclic patch for post-processing.
Source files
cyclicPointPatch.H
cyclicPointPatch.C
Definition at line 50 of file cyclicPointPatch.H.
Constructor & Destructor Documentation
cyclicPointPatch (const polyPatch & patch, const pointBoundaryMesh & bm)
Construct from components.
Definition at line 82 of file cyclicPointPatch.C.
~cyclicPointPatch () virtual
Destructor.
Definition at line 94 of file cyclicPointPatch.C.
Member Function Documentation
TypeName (cyclicPolyPatch:: typeName_())
Runtime type information.
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatch implements.
Reimplemented from pointPatch.
Definition at line 115 of file cyclicPointPatch.H.
References Foam::type().
const cyclicPolyPatch& cyclicPatch () const inline
Return the underlying cyclicPolyPatch.
Definition at line 121 of file cyclicPointPatch.H.
const cyclicPointPatch& neighbPatch () const inline
Return neighbour point patch.
Definition at line 127 of file cyclicPointPatch.H.
References pointPatch::boundaryMesh(), and cyclicPolyPatch::neighbPatchID().
Referenced by cyclicPointPatchField< Type >::swapAddSeparated().
bool parallel () const inline
Are the cyclic planes parallel.
Definition at line 135 of file cyclicPointPatch.H.
References coupledPolyPatch::parallel().
Referenced by cyclicPointPatchField< Type >::doTransform().
const tensorField& forwardT () const inline
Return face transformation tensor.
Definition at line 141 of file cyclicPointPatch.H.
References coupledPolyPatch::forwardT().
Referenced by cyclicPointPatchField< Type >::forwardT().
const tensorField& reverseT () const inline
Return neighbour-cell transformation tensor.
Definition at line 147 of file cyclicPointPatch.H.
References coupledPolyPatch::reverseT().
Referenced by cyclicPointPatchField< Type >::reverseT().
const Foam::edgeList & transformPairs () const virtual
Return the set of pairs of points that require transformation.
and/or mapping. First index is on this patch, second on the neighbour patch.
Definition at line 100 of file cyclicPointPatch.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/cyclic/cyclicPointPatch.H
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/cyclic/cyclicPointPatch.C