OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cyclicACMIPolyPatch Class Reference
Cyclic patch for Arbitrarily Coupled Mesh Interface (ACMI)
Public Member Functions
TypeName ("cyclicACMI")
Runtime type information.
cyclicACMIPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN)
Construct from (base couped patch) components.
cyclicACMIPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
cyclicACMIPolyPatch (const cyclicACMIPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
cyclicACMIPolyPatch (const cyclicACMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &nbrPatchName, const word &nonOverlapPatchName)
Construct given the original patch and resetting the.
cyclicACMIPolyPatch (const cyclicACMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~cyclicACMIPolyPatch ()
Destructor.
void setUpdated (bool flag) const
Reset the updated flag.
bool updated () const
Return access to the updated flag.
const vectorField & faceAreas0 () const
Return access to the original patch face areas.
virtual const cyclicACMIPolyPatch & neighbPatch () const
Return a reference to the neighbour patch.
const word & nonOverlapPatchName () const
Non-overlapping patch name.
virtual label nonOverlapPatchID () const
Non-overlapping patch ID.
const polyPatch & nonOverlapPatch () const
Return a const reference to the non-overlapping patch.
polyPatch & nonOverlapPatch ()
Return a reference to the non-overlapping patch.
const scalarField & mask () const
Mask field where 1 = overlap, 0 = no-overlap.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fldCouple, const Field< Type > &fldNonOverlap) const
Interpolate field.
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type > > &tFldCouple, const tmp< Field< Type > > &tFldNonOverlap) const
Interpolate tmp field.
template<class Type , class CombineOp >
void interpolate (const UList< Type > &fldCouple, const UList< Type > &fldNonOverlap, const CombineOp &cop, List< Type > &result) const
Low-level interpolate List.
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
Calculate the patch geometry.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &fldCouple, const Field< Type > &fldNonOverlap) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type > > &tFldCouple, const tmp< Field< Type > > &tFldNonOverlap) const
Public Member Functions inherited from cyclicAMIPolyPatch
TypeName ("cyclicAMI")
Runtime type information.
cyclicAMIPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN)
Construct from (base couped patch) components.
cyclicAMIPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &nbrPatchName)
Construct given the original patch and resetting the.
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~cyclicAMIPolyPatch ()
Destructor.
virtual bool coupled () const
Is patch 'coupled'. Note that on AMI the geometry is not.
const word & neighbPatchName () const
Neighbour patch name.
virtual label neighbPatchID () const
Neighbour patch ID.
virtual bool owner () const
Does this side own the patch?
const autoPtr< searchableSurface > & surfPtr () const
Return a reference to the projection surface.
const AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
bool applyLowWeightCorrection () const
Return true if applying the low weight correction.
const vector & rotationAxis () const
Axis of rotation for rotational cyclic AMI.
const point & rotationCentre () const
Point on axis of rotation for rotational cyclic AMI.
const vector & separationVector () const
Translation vector for translational cyclic AMI.
virtual void transformPosition (pointField &) const
Transform patch-based positions from nbr side to this side.
virtual void transformPosition (point &l, const label faceI) const
Transform a patch-based position from nbr side to this side.
virtual void reverseTransformPosition (point &l, const label faceI) const
Transform a patch-based position from this side to nbr side.
virtual void reverseTransformDirection (vector &d, const label faceI) const
Transform a patch-based direction from this side to nbr side.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >()) const
Interpolate field.
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues=UList< Type >()) const
Interpolate tmp field.
template<class Type , class CombineOp >
void interpolate (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >()) const
Low-level interpolate List.
label pointFace (const label faceI, const vector &n, point &p) const
Return face index on neighbour patch which shares point p.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type > > &tFld, const UList< Type > &defaultValues) const
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
virtual bool neighbour () const
Does the coupled side own the patch ?
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face > > &faces, const Xfer< List< PointType > > &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reUse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Protected Member Functions
virtual void initPatchFaceAreas () const
Initialise patch face areas.
virtual void resetAMI (const AMIPatchToPatchInterpolation::interpolationMethod &AMIMethod=AMIPatchToPatchInterpolation::imFaceAreaWeight) const
Reset the AMI interpolator.
virtual void setNeighbourFaceAreas () const
Set neighbour ACMI patch areas.
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &pBufs, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &pBufs, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
virtual void clearGeom ()
Clear geometry.
virtual const scalarField & srcMask () const
Return the mask/weighting for the source patch.
virtual const scalarField & tgtMask () const
Return the mask/weighting for the target patch.
Protected Member Functions inherited from cyclicAMIPolyPatch
virtual void calcTransforms ()
Recalculate the transformation tensors.
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
Static Protected Attributes
static const scalar tolerance_ = 1e-6
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes inherited from coupledPolyPatch
static const NamedEnum< transformType, 5 > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Protected Attributes inherited from cyclicAMIPolyPatch
word nbrPatchName_
Name of other half.
const coupleGroupIdentifier coupleGroup_
Optional patchGroup to find neighbPatch.
label nbrPatchID_
Index of other half.
vector rotationAxis_
Axis of rotation for rotational cyclics.
point rotationCentre_
Point on axis of rotation for rotational cyclics.
bool rotationAngleDefined_
Flag to show whether the rotation angle is defined.
scalar rotationAngle_
Rotation angle.
vector separationVector_
Translation vector.
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
AMI interpolation class.
const bool AMIReverse_
Flag to indicate that slave patch should be reversed for AMI.
bool AMIRequireMatch_
Flag to indicate that patches should match/overlap.
const scalar AMILowWeightCorrection_
Low weight correction threshold for AMI.
autoPtr< searchableSurface > surfPtr_
Projection surface.
const dictionary surfDict_
Dictionary used during projection surface construction.
Detailed Description
Cyclic patch for Arbitrarily Coupled Mesh Interface (ACMI)
Source files
cyclicACMIPolyPatch.H
cyclicACMIPolyPatch.C
Definition at line 50 of file cyclicACMIPolyPatch.H.
Constructor & Destructor Documentation
cyclicACMIPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform = UNKNOWN)
Construct from (base couped patch) components.
Definition at line 216 of file cyclicACMIPolyPatch.C.
Referenced by cyclicACMIPolyPatch::clone().
cyclicACMIPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 242 of file cyclicACMIPolyPatch.C.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
cyclicACMIPolyPatch (const cyclicACMIPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 276 of file cyclicACMIPolyPatch.C.
cyclicACMIPolyPatch (const cyclicACMIPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & nbrPatchName, const word & nonOverlapPatchName)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 297 of file cyclicACMIPolyPatch.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::name().
cyclicACMIPolyPatch (const cyclicACMIPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 331 of file cyclicACMIPolyPatch.C.
~cyclicACMIPolyPatch () virtual
Destructor.
Definition at line 353 of file cyclicACMIPolyPatch.C.
Member Function Documentation
void initPatchFaceAreas () const protected virtual
Initialise patch face areas.
Definition at line 45 of file cyclicACMIPolyPatch.C.
References polyPatch::boundaryMesh(), UList< T >::empty(), polyPatch::faceAreas(), cyclicACMIPolyPatch::faceAreas0(), polyBoundaryMesh::mesh(), polyMesh::moving(), and cyclicACMIPolyPatch::neighbPatch().
void resetAMI (const AMIPatchToPatchInterpolation::interpolationMethod & AMIMethod = AMIPatchToPatchInterpolation::imFaceAreaWeight) const protected virtual
Reset the AMI interpolator.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 71 of file cyclicACMIPolyPatch.C.
References polyPatch::faceAreas(), forAll, AMIInterpolation< SourcePatch, TargetPatch >::imPartialFaceAreaWeight, Foam::max(), Foam::min(), and cyclicAMIPolyPatch::resetAMI().
void setNeighbourFaceAreas () const protected virtual
Set neighbour ACMI patch areas.
Definition at line 117 of file cyclicACMIPolyPatch.C.
References Foam::cp(), Foam::endl(), polyPatch::faceAreas(), cyclicACMIPolyPatch::faceAreas0(), forAll, cyclicACMIPolyPatch::nonOverlapPatch(), and WarningInFunction.
void initGeometry (PstreamBuffers & pBufs) protected virtual
Initialise the calculation of the patch geometry.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 145 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::initGeometry().
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Calculate the patch geometry.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 154 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::calcGeometry().
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Initialise the patches for moving points.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 161 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::initMovePoints().
void movePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Correct patches after moving points.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 174 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::movePoints().
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 183 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::initUpdateMesh().
void updateMesh (PstreamBuffers & pBufs) protected virtual
Update of the patch topology.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 189 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::updateMesh().
void clearGeom () protected virtual
Clear geometry.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 195 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::clearGeom().
const Foam::scalarField & srcMask () const protected virtual
Return the mask/weighting for the source patch.
Definition at line 201 of file cyclicACMIPolyPatch.C.
const Foam::scalarField & tgtMask () const protected virtual
Return the mask/weighting for the target patch.
Definition at line 207 of file cyclicACMIPolyPatch.C.
TypeName ("cyclicACMI")
Runtime type information.
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 188 of file cyclicACMIPolyPatch.H.
References cyclicACMIPolyPatch::cyclicACMIPolyPatch().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from cyclicAMIPolyPatch.
Definition at line 196 of file cyclicACMIPolyPatch.H.
References cyclicACMIPolyPatch::cyclicACMIPolyPatch(), and cyclicAMIPolyPatch::neighbPatchName().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from cyclicAMIPolyPatch.
Definition at line 221 of file cyclicACMIPolyPatch.H.
References cyclicACMIPolyPatch::cyclicACMIPolyPatch().
void setUpdated (bool flag) const inline
Reset the updated flag.
Definition at line 28 of file cyclicACMIPolyPatchI.H.
Referenced by cyclicACMIFvPatch::updateAreas().
bool updated () const inline
Return access to the updated flag.
Definition at line 34 of file cyclicACMIPolyPatchI.H.
Referenced by cyclicACMIFvPatch::updateAreas().
const Foam::vectorField & faceAreas0 () const inline
Return access to the original patch face areas.
Definition at line 40 of file cyclicACMIPolyPatchI.H.
Referenced by cyclicACMIPolyPatch::initPatchFaceAreas(), and cyclicACMIPolyPatch::setNeighbourFaceAreas().
const Foam::cyclicACMIPolyPatch & neighbPatch () const virtual
Return a reference to the neighbour patch.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 359 of file cyclicACMIPolyPatch.C.
Referenced by cyclicACMIPolyPatch::initPatchFaceAreas().
const Foam::word & nonOverlapPatchName () const inline
Non-overlapping patch name.
Definition at line 46 of file cyclicACMIPolyPatchI.H.
Foam::label nonOverlapPatchID () const virtual
Non-overlapping patch ID.
Definition at line 366 of file cyclicACMIPolyPatch.C.
References Foam::exit(), polyPatch::faceAreas(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), patchIdentifier::name(), Foam::name(), Foam::nl, and Foam::type().
Referenced by cyclicACMIFvPatch::nonOverlapPatchID().
const Foam::polyPatch & nonOverlapPatch () const inline
Return a const reference to the non-overlapping patch.
Definition at line 52 of file cyclicACMIPolyPatchI.H.
Referenced by cyclicACMIPolyPatch::setNeighbourFaceAreas().
Foam::polyPatch & nonOverlapPatch () inline
Return a reference to the non-overlapping patch.
Definition at line 61 of file cyclicACMIPolyPatchI.H.
const Foam::scalarField & mask () const inline
Mask field where 1 = overlap, 0 = no-overlap.
Definition at line 70 of file cyclicACMIPolyPatchI.H.
tmp<Field<Type> > interpolate (const Field< Type > & fldCouple, const Field< Type > & fldNonOverlap) const
Interpolate field.
Referenced by cyclicACMIFvPatch::interpolate().
tmp<Field<Type> > interpolate (const tmp< Field< Type > > & tFldCouple, const tmp< Field< Type > > & tFldNonOverlap) const
Interpolate tmp field.
void interpolate (const UList< Type > & fldCouple, const UList< Type > & fldNonOverlap, const CombineOp & cop, List< Type > & result) const
Low-level interpolate List.
Definition at line 64 of file cyclicACMIPolyPatchTemplates.C.
void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) virtual
Calculate the patch geometry.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 433 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::calcGeometry().
void initOrder (PstreamBuffers & pBufs, const primitivePatch & pp) const virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Reimplemented from cyclicAMIPolyPatch.
Definition at line 457 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::initOrder().
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 467 of file cyclicACMIPolyPatch.C.
References cyclicAMIPolyPatch::order().
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from cyclicAMIPolyPatch.
Definition at line 478 of file cyclicACMIPolyPatch.C.
References token::END_STATEMENT, Foam::nl, cyclicAMIPolyPatch::write(), and Ostream::writeKeyword().
Foam::tmp<Foam::Field<Type> > interpolate (const Field< Type > & fldCouple, const Field< Type > & fldNonOverlap) const
Definition at line 28 of file cyclicACMIPolyPatchTemplates.C.
Foam::tmp<Foam::Field<Type> > interpolate (const tmp< Field< Type > > & tFldCouple, const tmp< Field< Type > > & tFldNonOverlap) const
Definition at line 53 of file cyclicACMIPolyPatchTemplates.C.
References Foam::MULES::interpolate().
Member Data Documentation
const Foam::scalar tolerance_ = 1e-6 static protected
Definition at line 80 of file cyclicACMIPolyPatch.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPolyPatch/cyclicACMIPolyPatch.H
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPolyPatch/cyclicACMIPolyPatch.C
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPolyPatch/cyclicACMIPolyPatchI.H
src/meshTools/AMIInterpolation/patches/cyclicACMI/cyclicACMIPolyPatch/cyclicACMIPolyPatchTemplates.C