OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cuboid Class Reference
Public Member Functions
TypeName ("cuboid")
Runtime type information.
cuboid (const word &name, const scalar m, const vector &c, const vector &L)
Construct from name, mass, centre of mass and lengths of the sides.
cuboid (const word &name, const dictionary &dict)
Construct from dictionary.
virtual autoPtr< rigidBody > clone () const
Return clone of this cuboid.
virtual ~cuboid ()
Destructor.
const vector & L () const
Return the lengths of the sides of the cuboid.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from rigidBody
TypeName ("rigidBody")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, rigidBody, dictionary,(const word &name, const dictionary &dict),(name, dict))
rigidBody (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
Construct from mass, centre of mass and moment of inertia tensor.
rigidBody (const word &name, const rigidBodyInertia &rbi)
Construct from with the given rigidBodyInertia.
rigidBody (const word &name, const dictionary &dict)
Construct from dictionary.
virtual ~rigidBody ()
Destructor.
const word & name () const
Return name.
virtual bool massless () const
Return false as this body is not massless.
void merge (const subBody &)
Merge a body into this parent body.
Public Member Functions inherited from rigidBodyInertia
rigidBodyInertia ()
Null constructor, initializes to zero.
rigidBodyInertia (const scalar m, const vector &c, const symmTensor &Ic)
Construct from mass, centre of mass and moment of inertia tensor.
rigidBodyInertia (const dictionary &dict)
Construct from dictionary.
rigidBodyInertia (const spatialTensor &st)
Construct from the components of a spatial tensor.
rigidBodyInertia (Istream &is)
Construct from Istream.
scalar m () const
Return the mass of the rigid-body.
const vector & c () const
Return the centre of mass of the rigid-body.
const symmTensor & Ic () const
Return the inertia tensor of the rigid-body about the centre of mass.
symmTensor Ioc () const
Return the difference between the inertia tensor of the rigid-body.
symmTensor Icc (const vector &c) const
Return the difference between the inertia tensor of the rigid-body.
symmTensor Io () const
Return the inertia tensor of the rigid-body about the origin.
scalar kineticEnergy (const spatialVector &v)
Return the kinetic energy of the body with the given velocity.
operator spatialTensor () const
Conversion to spatial tensor.
void operator+= (const rigidBodyInertia &)
Additional Inherited Members
Static Public Member Functions inherited from rigidBody
static autoPtr< rigidBody > New (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
Select constructed from components.
static autoPtr< rigidBody > New (const word &name, const dictionary &dict)
Select constructed from name and dictionary.
Static Public Member Functions inherited from rigidBodyInertia
static symmTensor Ioc (const scalar m, const vector &c)
Return the difference between the inertia tensor of the rigid-body.
Detailed Description
Definition at line 52 of file cuboid.H.
Constructor & Destructor Documentation
cuboid (const word & name, const scalar m, const vector & c, const vector & L) inline
Construct from name, mass, centre of mass and lengths of the sides.
Definition at line 51 of file cuboidI.H.
cuboid (const word & name, const dictionary & dict) inline
Construct from dictionary.
Definition at line 64 of file cuboidI.H.
References rigidBodyInertia::c(), dictionary::lookup(), rigidBodyInertia::m(), Foam::readScalar(), and rigidBodyInertia::rigidBodyInertia().
~cuboid () virtual
Destructor.
Definition at line 57 of file cuboid.C.
Member Function Documentation
TypeName ("cuboid")
Runtime type information.
Foam::autoPtr< Foam::RBD::rigidBody > clone () const virtual
Return clone of this cuboid.
Reimplemented from rigidBody.
Definition at line 49 of file cuboid.C.
const Foam::vector & L () const inline
Return the lengths of the sides of the cuboid.
Definition at line 80 of file cuboidI.H.
void write (Ostream & os) const virtual
Write.
Reimplemented from rigidBody.
Definition at line 63 of file cuboid.C.
References token::END_STATEMENT, Foam::nl, Foam::type(), and Ostream::writeKeyword().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/bodies/cuboid/cuboid.H
src/rigidBodyDynamics/bodies/cuboid/cuboid.C
src/rigidBodyDynamics/bodies/cuboid/cuboidI.H