OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cyclicAMIPointPatchField< Type > Class Template Reference
Cyclic AMI front and back plane patch field.
Public Member Functions
TypeName (cyclicAMIPointPatch::typeName_())
Runtime type information.
cyclicAMIPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
cyclicAMIPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
cyclicAMIPointPatchField (const cyclicAMIPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
virtual autoPtr< pointPatchField< Type > > clone () const
Construct and return a clone.
cyclicAMIPointPatchField (const cyclicAMIPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual bool doTransform () const
Does the patch field perform the transfromation.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
virtual void swapAddSeparated (const Pstream::commsTypes commsType, Field< Type > &) const
Complete swap of patch point values and add to local values.
Public Member Functions inherited from coupledPointPatchField< Type >
TypeName (coupledPointPatch::typeName_())
Runtime type information.
coupledPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
coupledPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &dict)
Construct from patch, internal field and dictionary.
coupledPointPatchField (const coupledPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
coupledPointPatchField (const coupledPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual bool coupled () const
Return true if this patch field is derived from.
virtual void initSwapAddSeparated (const Pstream::commsTypes, Field< Type > &) const
Initialise swap of patch point values.
Public Member Functions inherited from pointPatchField< Type >
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type, pointMesh > & dimensionedInternalField () const
Return dimensioned internal field reference.
const Field< Type > & internalField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void write (Ostream &) const
Write.
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Additional Inherited Members
Public Types inherited from pointPatchField< Type >
typedef pointPatch Patch
Static Public Member Functions inherited from pointPatchField< Type >
static autoPtr< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new CalculatedpointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Attributes inherited from pointPatchField< Type >
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Detailed Description
template<class Type>
class Foam::cyclicAMIPointPatchField< Type >
Cyclic AMI front and back plane patch field.
Source files
cyclicAMIPointPatchField.H
cyclicAMIPointPatchField.C
Definition at line 51 of file cyclicAMIPointPatchField.H.
Constructor & Destructor Documentation
cyclicAMIPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file cyclicAMIPointPatchField.C.
Referenced by cyclicAMIPointPatchField< Type >::clone(), and cyclicAMIPointPatchField< Type >::cyclicAMIPointPatchField().
cyclicAMIPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 49 of file cyclicAMIPointPatchField.C.
References cyclicAMIPointPatchField< Type >::cyclicAMIPointPatchField(), Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
cyclicAMIPointPatchField (const cyclicAMIPointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Construct by mapping given patchField<Type> onto a new patch.
Definition at line 74 of file cyclicAMIPointPatchField.C.
References cyclicAMIPointPatchField< Type >::cyclicAMIPointPatchField(), Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
cyclicAMIPointPatchField (const cyclicAMIPointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 100 of file cyclicAMIPointPatchField.C.
References cyclicAMIPointPatchField< Type >::swapAddSeparated().
Member Function Documentation
TypeName (cyclicAMIPointPatch::typeName_())
Runtime type information.
virtual autoPtr<pointPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Implements coupledPointPatchField< Type >.
Definition at line 138 of file cyclicAMIPointPatchField.H.
References cyclicAMIPointPatchField< Type >::cyclicAMIPointPatchField().
virtual autoPtr<pointPatchField<Type> > clone (const DimensionedField< Type, pointMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Implements coupledPointPatchField< Type >.
Definition at line 158 of file cyclicAMIPointPatchField.H.
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatchField implements.
Reimplemented from pointPatchField< Type >.
Definition at line 177 of file cyclicAMIPointPatchField.H.
virtual bool doTransform () const inline virtual
Does the patch field perform the transfromation.
Definition at line 186 of file cyclicAMIPointPatchField.H.
References cyclicAMIPointPatch::parallel().
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Definition at line 196 of file cyclicAMIPointPatchField.H.
References cyclicAMIPointPatch::forwardT().
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Definition at line 202 of file cyclicAMIPointPatchField.H.
References cyclicAMIPointPatchField< Type >::evaluate(), and cyclicAMIPointPatch::reverseT().
virtual void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) inline virtual
Evaluate the patch field.
Implements coupledPointPatchField< Type >.
Definition at line 212 of file cyclicAMIPointPatchField.H.
References cyclicAMIPointPatchField< Type >::swapAddSeparated().
Referenced by cyclicAMIPointPatchField< Type >::reverseT().
void swapAddSeparated (const Pstream::commsTypes commsType, Field< Type > & pField) const virtual
Complete swap of patch point values and add to local values.
Implements coupledPointPatchField< Type >.
Definition at line 116 of file cyclicAMIPointPatchField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensionedInternalField(), fld(), facePointPatch::index(), cyclicAMIPointPatch::neighbPatch(), and Foam::transform().
Referenced by cyclicAMIPointPatchField< Type >::cyclicAMIPointPatchField(), and cyclicAMIPointPatchField< Type >::evaluate().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatchField/cyclicAMIPointPatchField.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatchField/cyclicAMIPointPatchField.C