OpenFOAM: cyclicACMIGAMGInterfaceField Class Reference
cyclicACMIGAMGInterfaceField Class Reference
GAMG agglomerated cyclic interface for Arbitrarily Coupled Mesh Interface (ACMI) fields.
Public Member Functions
TypeName ("cyclicACMI")
Runtime type information.
cyclicACMIGAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterfaceField)
Construct from GAMG interface and fine level interface field.
cyclicACMIGAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
virtual ~cyclicACMIGAMGInterfaceField ()
Destructor.
label size () const
Return size.
virtual void updateInterfaceMatrix (scalarField &result, const scalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
Update result field based on interface functionality.
virtual bool doTransform () const
Cyclic interface functions.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual int rank () const
Return rank of component for transform.
Public Member Functions inherited from GAMGInterfaceField
TypeName ("GAMGInterfaceField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterfaceField,(const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface),(GAMGCp, fineInterface))
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterface,(const GAMGInterface &GAMGCp, const bool doTransform, const int rank),(GAMGCp, doTransform, rank))
GAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &)
Construct from GAMG interface and fine level interface field.
GAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
const GAMGInterface & interface () const
Return interface.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
Public Member Functions inherited from cyclicACMILduInterfaceField
TypeName ("cyclicACMILduInterfaceField")
Runtime type information.
cyclicACMILduInterfaceField ()
Construct null.
virtual ~cyclicACMILduInterfaceField ()
Destructor.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &psiInternal, const direction cmpt) const
Transform given patch internal field.
Public Member Functions inherited from cyclicAMILduInterfaceField
TypeName ("cyclicAMILduInterfaceField")
Runtime type information.
cyclicAMILduInterfaceField ()
Construct null.
virtual ~cyclicAMILduInterfaceField ()
Destructor.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &psiInternal, const direction cmpt) const
Transform given patch internal field.
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterfaceField
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Return a pointer to a new interface created on freestore given.
Detailed Description
GAMG agglomerated cyclic interface for Arbitrarily Coupled Mesh Interface (ACMI) fields.
Source files
cyclicACMIGAMGInterfaceField.H
cyclicACMIGAMGInterfaceField.C
Definition at line 51 of file cyclicACMIGAMGInterfaceField.H.
Constructor & Destructor Documentation
cyclicACMIGAMGInterfaceField (const GAMGInterface & GAMGCp, const lduInterfaceField & fineInterfaceField)
Construct from GAMG interface and fine level interface field.
Definition at line 53 of file cyclicACMIGAMGInterfaceField.C.
References cyclicAMILduInterfaceField::doTransform(), p, and cyclicAMILduInterfaceField::rank().
cyclicACMIGAMGInterfaceField (const GAMGInterface & GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
Definition at line 72 of file cyclicACMIGAMGInterfaceField.C.
~cyclicACMIGAMGInterfaceField () virtual
Destructor.
Definition at line 87 of file cyclicACMIGAMGInterfaceField.C.
References cyclicACMIGAMGInterfaceField::updateInterfaceMatrix().
Member Function Documentation
TypeName ("cyclicACMI")
Runtime type information.
label size () const inline
Return size.
Definition at line 110 of file cyclicACMIGAMGInterfaceField.H.
References GAMGInterface::size(), and cyclicACMIGAMGInterfaceField::updateInterfaceMatrix().
void updateInterfaceMatrix (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Update result field based on interface functionality.
Implements lduInterfaceField.
Definition at line 94 of file cyclicACMIGAMGInterfaceField.C.
References forAll.
Referenced by cyclicACMIGAMGInterfaceField::size(), and cyclicACMIGAMGInterfaceField::~cyclicACMIGAMGInterfaceField().
virtual bool doTransform () const inline virtual
Cyclic interface functions.
Does the interface field perform the transfromation
Implements cyclicAMILduInterfaceField.
Definition at line 132 of file cyclicACMIGAMGInterfaceField.H.
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements cyclicAMILduInterfaceField.
Definition at line 138 of file cyclicACMIGAMGInterfaceField.H.
References cyclicACMIGAMGInterface::forwardT().
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Implements cyclicAMILduInterfaceField.
Definition at line 144 of file cyclicACMIGAMGInterfaceField.H.
References cyclicACMIGAMGInterface::reverseT().
virtual int rank () const inline virtual
Return rank of component for transform.
Implements cyclicAMILduInterfaceField.
Definition at line 150 of file cyclicACMIGAMGInterfaceField.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/GAMG/interfaceFields/cyclicACMIGAMGInterfaceField/cyclicACMIGAMGInterfaceField.H
src/meshTools/AMIInterpolation/GAMG/interfaceFields/cyclicACMIGAMGInterfaceField/cyclicACMIGAMGInterfaceField.C