OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
CSV< Type > Class Template Reference
Templated CSV container data entry. Reference column is always a scalar, e.g. time.
Public Member Functions
TypeName ("csvFile")
Runtime type information.
CSV (const word &entryName, const dictionary &dict, const word &ext="Coeffs")
Construct from entry name and dictionary.
CSV (const CSV< Type > &tbl)
Copy constructor.
virtual tmp< DataEntry< Type > > clone () const
Construct and return a clone.
virtual ~CSV ()
Destructor.
virtual const fileName & fName () const
Return const access to the file name.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from TableBase< Type >
TableBase (const word &name, const dictionary &dict)
Construct from dictionary - note table is not populated.
TableBase (const TableBase< Type > &tbl)
Copy constructor. Note: steals interpolator, tableSamples.
virtual ~TableBase ()
Destructor.
word boundsHandlingToWord (const boundsHandling &bound) const
Return the out-of-bounds handling as a word.
boundsHandling wordToBoundsHandling (const word &bound) const
Return the out-of-bounds handling as an enumeration.
boundsHandling outOfBounds (const boundsHandling &bound)
Set the out-of-bounds handling from enum, return previous setting.
void check () const
Check the table for size and consistency.
bool checkMinBounds (const scalar x, scalar &xDash) const
Check minimum table bounds.
bool checkMaxBounds (const scalar x, scalar &xDash) const
Check maximum table bounds.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return Table value.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual dimensioned< Type > dimValue (const scalar x) const
Return dimensioned constant value.
virtual dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const
Integrate between two values and return dimensioned type.
virtual tmp< scalarField > x () const
Return the reference values.
virtual tmp< Field< Type > > y () const
Return the dependent values.
virtual void writeEntries (Ostream &os) const
Write keywords only in dictionary format. Used for non-inline.
Public Member Functions inherited from DataEntry< Type >
TypeName ("DataEntry") declareRunTimeSelectionTable(autoPtr
Runtime type information.
DataEntry (const word &entryName)
Construct from entry name.
DataEntry (const DataEntry< Type > &de)
Copy constructor.
virtual ~DataEntry ()
Destructor.
const word & name () const
Return the name of the entry.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
virtual tmp< Field< dimensioned< Type > > > dimValue (const scalarField &x) const
Return dimensioned type as a function of (scalar)
virtual tmp< Field< dimensioned< Type > > > dimIntegrate (const scalarField &x1, const scalarField &x2) const
Integrate between two scalar fields and return a field of.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Friends
Ostream & operator (Ostream &os, const CSV< Type > &cnst)
Ostream Operator.
Additional Inherited Members
Public Types inherited from TableBase< Type >
enum boundsHandling { ERROR, WARN, CLAMP, REPEAT }
Enumeration for handling out-of-bound values.
Static Public Member Functions inherited from DataEntry< Type >
static autoPtr< DataEntry< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from DataEntry< Type >
DataEntry
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Member Functions inherited from TableBase< Type >
const interpolationWeights & interpolator () const
Return (demand driven) interpolator.
void operator= (const TableBase< Type > &)
Disallow default bitwise assignment.
Protected Attributes inherited from TableBase< Type >
const word name_
Table name.
const boundsHandling boundsHandling_
Enumeration for handling out-of-bound values.
const word interpolationScheme_
Interpolation type.
List< Tuple2< scalar, Type > > table_
Table data.
dimensionSet dimensions_
The dimension set.
autoPtr< scalarField > tableSamplesPtr_
Extracted values.
autoPtr< interpolationWeights > interpolatorPtr_
Interpolator method.
labelList currentIndices_
Cached indices and weights.
scalarField currentWeights_
Protected Attributes inherited from DataEntry< Type >
const word name_
Name of entry.
Detailed Description
template<class Type>
class Foam::CSV< Type >
Templated CSV container data entry. Reference column is always a scalar, e.g. time.
    <entryName> csvFile;
    <entryName>Coeffs
    {
        nHeaderLine         4;          // number of header lines
        refColumn           0;          // reference column index
        componentColumns    (1 2 3);    // component column indices
        separator           ",";        // optional (defaults to ",")
        mergeSeparators     no;         // merge multiple separators
        fileName            "fileXYZ";  // name of csv data file
        outOfBounds         clamp;      // optional out-of-bounds handling
        interpolationScheme linear;     // optional interpolation scheme
    }
Source files
CSV.H
CSV.C
Definition at line 65 of file CSV.H.
Constructor & Destructor Documentation
CSV (const word & entryName, const dictionary & dict, const word & ext = "Coeffs")
Construct from entry name and dictionary.
Definition at line 200 of file CSV.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, and Foam::read().
CSV (const CSV< Type > & tbl)
Copy constructor.
Definition at line 230 of file CSV.C.
~CSV () virtual
Destructor.
Definition at line 245 of file CSV.C.
Member Function Documentation
TypeName ("csvFile")
Runtime type information.
virtual tmp<DataEntry<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from DataEntry< Type >.
Definition at line 139 of file CSV.H.
const Foam::fileName & fName () const virtual
Return const access to the file name.
Definition at line 252 of file CSV.C.
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented from TableBase< Type >.
Definition at line 60 of file CSVIO.C.
References Foam::decrIndent(), Foam::endl(), IOstream::format(), Foam::incrIndent(), Foam::indent(), Foam::name(), Foam::nl, writeData(), and Ostream::writeKeyword().
Friends And Related Function Documentation
Ostream& operator (Ostream & os, const CSV< Type > & cnst) friend
Ostream Operator.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/DataEntry/CSV/CSV.H
src/OpenFOAM/primitives/functions/DataEntry/CSV/CSV.C
src/OpenFOAM/primitives/functions/DataEntry/CSV/CSVIO.C