OpenFOAM: Distribution< Type > Class Template Reference
Distribution< Type > Class Template Reference
Accumulating histogram of component values. Specified bin resolution, automatic generation of bins.
Public Types
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from List< List< scalar > >
typedef SubList< List< scalar > > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
Distribution ()
Construct null.
Distribution (const Type &binWidth)
Construct from separate binWidth for each component.
Distribution (const Distribution &d)
Construct as copy.
~Distribution ()
Destructor.
scalar totalWeight (direction cmpt) const
Sum the total weight added to the component in the.
List< label > keys (direction cmpt) const
label index (direction cmpt, label n)
Return the appropriate List index for the given bin index.
Pair< label > validLimits (direction cmpt) const
Returns the indices of the first and last non-zero entries.
Type mean () const
Type median () const
void add (const Type &valueToAdd, const Type &weight=pTraits< Type >::one)
Add a value to the distribution, optionally specifying a weight.
List< List< Pair< scalar > > > normalised () const
Return the normalised distribution (probability density)
List< List< Pair< scalar > > > raw () const
Return the distribution of the total bin weights.
List< List< Pair< scalar > > > cumulativeNormalised () const
Return the cumulative normalised distribution and.
List< List< Pair< scalar > > > cumulativeRaw () const
Return the cumulative total bin weights and integration.
void clear ()
Resets the Distribution by clearing the stored lists.
const Type & binWidth () const
Return the bin width.
const List< label > & listStarts () const
Return the List start bin indices.
void write (const fileName &filePrefix) const
Write the distribution to file: key normalised raw.
void operator= (const Distribution< Type > &)
Public Member Functions inherited from List< List< scalar > >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const List< scalar > &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< List< scalar > > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< List< scalar > >> &)
Construct by transferring the parameter contents.
List (List< List< scalar > > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< List< scalar > > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< List< scalar >, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< List< scalar > > &)
Construct as copy of PtrList<T>
List (const SLList< List< scalar > > &)
Construct as copy of SLList<T>
List (const UIndirectList< List< scalar > > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< List< scalar > > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< List< scalar > >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< List< scalar > > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const List< scalar > &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const List< scalar > &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const List< scalar > &)
Append an element at the end of the list.
void append (const UList< List< scalar > > &)
Append a List at the end of this list.
void append (const UIndirectList< List< scalar > > &)
Append a UIndirectList at the end of this list.
void transfer (List< List< scalar > > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< List< scalar >, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< List< scalar > > &)
Transfer the contents of the argument List into this list.
Xfer< List< List< scalar > > > xfer ()
Transfer contents to the Xfer container.
List< scalar > & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< List< scalar > > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< List< scalar > > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< List< scalar > > &)
Assignment operator. Takes linear time.
void operator= (const SLList< List< scalar > > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< List< scalar > > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< List< scalar > > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< List< scalar > >)
Assignment to an initializer list.
void operator= (const List< scalar > &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Friends
Istream & operator>> (Istream &, Distribution< Type > &)
Ostream & operator (Ostream &, const Distribution< Type > &)
Additional Inherited Members
Static Public Member Functions inherited from List< List< scalar > >
static const List< List< scalar > > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< List< scalar > >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::Distribution< Type >
Accumulating histogram of component values. Specified bin resolution, automatic generation of bins.
Source files
Distribution.H
DistributionI.H
Distribution.C
DistributionIO.C
Definition at line 49 of file Distribution.H.
Member Typedef Documentation
typedef pTraits<Type>::cmptType cmptType
Component type.
Definition at line 78 of file Distribution.H.
Constructor & Destructor Documentation
Distribution ()
Construct null.
Definition at line 33 of file Distribution.C.
Referenced by Distribution< Type >::Distribution().
Distribution (const Type & binWidth)
Construct from separate binWidth for each component.
Definition at line 42 of file Distribution.C.
References Distribution< Type >::binWidth(), Distribution< Type >::Distribution(), and Distribution< Type >::listStarts().
Distribution (const Distribution< Type > & d)
Construct as copy.
~Distribution ()
Destructor.
Definition at line 62 of file Distribution.C.
Member Function Documentation
Foam::scalar totalWeight (direction cmpt) const
Sum the total weight added to the component in the.
argument
Definition at line 69 of file Distribution.C.
References forAll.
Referenced by Distribution< Type >::mean(), and Distribution< Type >::normalised().
Foam::List< Foam::label > keys (direction cmpt) const
Definition at line 85 of file Distribution.C.
References forAll, Foam::identity(), Distribution< Type >::index(), k, and List< List< scalar > >::size().
Referenced by Distribution< Type >::mean(), Distribution< Type >::normalised(), and Distribution< Type >::raw().
Foam::label index (direction cmpt, label n)
Return the appropriate List index for the given bin index.
Resizes the List if required
Definition at line 100 of file Distribution.C.
References UList< T >::empty(), forAll, n, List< T >::setSize(), List< T >::size(), and Distribution< Type >::validLimits().
Referenced by Distribution< Type >::add(), Distribution< Type >::keys(), and Distribution< Type >::operator=().
Foam::Pair< Foam::label > validLimits (direction cmpt) const
Returns the indices of the first and last non-zero entries.
Definition at line 166 of file Distribution.C.
References Pair< Type >::first(), forAll, and Pair< Type >::second().
Referenced by Distribution< Type >::index(), Distribution< Type >::normalised(), and Distribution< Type >::raw().
Type mean () const
Definition at line 197 of file Distribution.C.
References Foam::component(), forAll, k, Distribution< Type >::keys(), Foam::setComponent(), Distribution< Type >::totalWeight(), and Foam::Zero.
Type median () const
Definition at line 226 of file Distribution.C.
References Distribution< Type >::add(), Foam::component(), UList< T >::first(), forAll, Foam::mag(), Distribution< Type >::normalised(), Foam::setComponent(), List< T >::size(), and Foam::Zero.
void add (const Type & valueToAdd, const Type & weight = pTraits<Type>::one)
Add a value to the distribution, optionally specifying a weight.
Definition at line 313 of file Distribution.C.
References Foam::component(), Distribution< Type >::index(), Foam::neg(), and Distribution< Type >::normalised().
Referenced by Distribution< Type >::median().
Foam::List< Foam::List< Foam::Pair< Foam::scalar > > > normalised () const
Return the normalised distribution (probability density)
and bins
Definition at line 335 of file Distribution.C.
References Foam::component(), UList< T >::empty(), Pair< Type >::first(), UList< T >::first(), k, Distribution< Type >::keys(), Distribution< Type >::raw(), Pair< Type >::second(), List< T >::setSize(), Distribution< Type >::totalWeight(), and Distribution< Type >::validLimits().
Referenced by Distribution< Type >::add(), Distribution< Type >::cumulativeNormalised(), Distribution< Type >::median(), and Distribution< Type >::write().
Foam::List< Foam::List< Foam::Pair< Foam::scalar > > > raw () const
Return the distribution of the total bin weights.
Definition at line 383 of file Distribution.C.
References Foam::component(), Distribution< Type >::cumulativeNormalised(), UList< T >::empty(), Pair< Type >::first(), UList< T >::first(), k, Distribution< Type >::keys(), Pair< Type >::second(), List< T >::setSize(), and Distribution< Type >::validLimits().
Referenced by Distribution< Type >::cumulativeRaw(), Distribution< Type >::normalised(), Distribution< Type >::operator=(), and Distribution< Type >::write().
Foam::List< Foam::List< Foam::Pair< Foam::scalar > > > cumulativeNormalised () const
Return the cumulative normalised distribution and.
integration locations (at end of bins)
Definition at line 425 of file Distribution.C.
References Foam::component(), Distribution< Type >::cumulativeRaw(), UList< T >::first(), forAll, Distribution< Type >::normalised(), and Foam::sum().
Referenced by Distribution< Type >::raw(), and Distribution< Type >::write().
Foam::List< Foam::List< Foam::Pair< Foam::scalar > > > cumulativeRaw () const
Return the cumulative total bin weights and integration.
locations (at end of bins)
Definition at line 461 of file Distribution.C.
References Foam::component(), UList< T >::first(), forAll, Distribution< Type >::raw(), and Foam::sum().
Referenced by Distribution< Type >::cumulativeNormalised(), and Distribution< Type >::write().
void clear ()
Resets the Distribution by clearing the stored lists.
Leaves the same number of them and the same binWidth.
Definition at line 492 of file Distribution.C.
const Type & binWidth () const inline
Return the bin width.
Definition at line 30 of file DistributionI.H.
Referenced by Distribution< Type >::Distribution(), and Distribution< Type >::operator=().
const Foam::List< Foam::label > & listStarts () const inline
Return the List start bin indices.
Definition at line 38 of file DistributionI.H.
Referenced by Distribution< Type >::Distribution().
void write (const fileName & filePrefix) const
Write the distribution to file: key normalised raw.
Produces a separate file for each component.
Definition at line 504 of file Distribution.C.
References Distribution< Type >::cumulativeNormalised(), Distribution< Type >::cumulativeRaw(), Foam::endl(), UList< T >::first(), forAll, Foam::nl, Distribution< Type >::normalised(), and Distribution< Type >::raw().
void operator= (const Distribution< Type > & rhs)
Definition at line 561 of file Distribution.C.
References Foam::abort(), Distribution< Type >::binWidth(), Foam::component(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), forAll, Distribution< Type >::index(), Foam::max(), Foam::neg(), Distribution< Type >::operator, Distribution< Type >::raw(), and token::SPACE.
Friends And Related Function Documentation
Istream& operator>> (Istream & , Distribution< Type > &) friend
Ostream& operator (Ostream & , const Distribution< Type > &) friend
Referenced by Distribution< Type >::operator=().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/Distribution/Distribution.H
src/OpenFOAM/containers/Lists/Distribution/Distribution.C
src/OpenFOAM/containers/Lists/Distribution/DistributionI.H