OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dummy Class Reference
Public Member Functions
TypeName ("dummy")
Runtime type information.
dummy (const word &name, const IATE &iate, const dictionary &dict)
virtual ~dummy ()
Destructor.
virtual tmp< volScalarField > R () const
TypeName ("dummy")
Runtime type information.
dummy (const word &name, const IATE &iate, const dictionary &dict)
virtual ~dummy ()
Destructor.
virtual tmp< volScalarField > R () const
Public Member Functions inherited from IATEsource
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
Additional Inherited Members
Static Public Member Functions inherited from IATEsource
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes inherited from IATEsource
const IATE & iate_
Reference to the IATE this source applies to.
Detailed Description
Source files
dummy.H
dummy.C
Source files
dummy.H
dummy.C
Definition at line 51 of file dummy.H.
Constructor & Destructor Documentation
dummy (const word & name, const IATE & iate, const dictionary & dict) inline
Definition at line 64 of file dummy.H.
virtual ~dummy () inline virtual
Destructor.
Definition at line 75 of file dummy.H.
References dummy::R().
dummy (const word & name, const IATE & iate, const dictionary & dict) inline
Definition at line 64 of file dummy.H.
virtual ~dummy () inline virtual
Destructor.
Definition at line 75 of file dummy.H.
References dummy::R().
Member Function Documentation
TypeName ("dummy")
Runtime type information.
virtual tmp<volScalarField> R () const virtual
Implements IATEsource.
Referenced by dummy::~dummy().
TypeName ("dummy")
Runtime type information.
virtual tmp<volScalarField> R () const virtual
Implements IATEsource.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATEsources/dummy/dummy.H