OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DiagTensor< Cmpt > Class Template Reference
Templated 3D DiagTensor derived from VectorSpace.
Public Types
enum { rank = 2 }
enum components { XX, YY, ZZ }
Component labeling enumeration.
Public Types inherited from VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >
enum
typedef Cmpt cmptType
Component type.
Public Member Functions
DiagTensor ()
Construct null.
template<class Cmpt2 >
DiagTensor (const VectorSpace< DiagTensor< Cmpt2 >, Cmpt2, 3 > &)
Construct given VectorSpace.
DiagTensor (const Cmpt &txx, const Cmpt &tyy, const Cmpt &tzz)
Construct given three components.
DiagTensor (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & yy () const
const Cmpt & zz () const
Cmpt & xx ()
Cmpt & yy ()
Cmpt & zz ()
Public Member Functions inherited from VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< DiagTensor< Cmpt >, Cmpt, nCmpt > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< DiagTensor< Cmpt >, Cmpt, nCmpt > &)
void operator+= (const VectorSpace< DiagTensor< Cmpt >, Cmpt, nCmpt > &)
void operator-= (const VectorSpace< DiagTensor< Cmpt >, Cmpt, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName
static const char * componentNames []
static const DiagTensor zero
static const DiagTensor one
static const DiagTensor max
static const DiagTensor min
Additional Inherited Members
Public Attributes inherited from VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >
Cmpt v_ [nCmpt]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::DiagTensor< Cmpt >
Templated 3D DiagTensor derived from VectorSpace.
Adding construction from 3 components, element access using xx(), yy() and zz() member functions and the inner-product (dot-product) and outer-product operators.
Source files
DiagTensor.H
DiagTensorI.H
Definition at line 53 of file DiagTensor.H.
Member Enumeration Documentation
anonymous enum
Enumerator
rank
Definition at line 62 of file DiagTensor.H.
enum components
Component labeling enumeration.
Enumerator
XX
YY
ZZ
Definition at line 79 of file DiagTensor.H.
Constructor & Destructor Documentation
DiagTensor () inline
Construct null.
Definition at line 37 of file DiagTensorI.H.
Referenced by DiagTensor< Cmpt >::DiagTensor().
DiagTensor (const VectorSpace< DiagTensor< Cmpt2 >, Cmpt2, 3 > & vs) inline
Construct given VectorSpace.
Definition at line 44 of file DiagTensorI.H.
References DiagTensor< Cmpt >::DiagTensor().
DiagTensor (const Cmpt & txx, const Cmpt & tyy, const Cmpt & tzz) inline
Construct given three components.
Definition at line 54 of file DiagTensorI.H.
DiagTensor (Istream & is) inline
Construct from Istream.
Definition at line 67 of file DiagTensorI.H.
Member Function Documentation
const Cmpt & xx () const inline
Definition at line 76 of file DiagTensorI.H.
References VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >::v_, and DiagTensor< Cmpt >::XX.
Referenced by Foam::det(), Foam::inv(), molecule::constantProperties::linearMolecule(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::operator/(), wedgeFvPatchField< Type >::snGradTransformDiag(), and Foam::tr().
const Cmpt & yy () const inline
Definition at line 82 of file DiagTensorI.H.
References VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >::v_, and DiagTensor< Cmpt >::YY.
Referenced by molecule::constantProperties::constantProperties(), Foam::det(), Foam::inv(), molecule::constantProperties::linearMolecule(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::operator/(), wedgeFvPatchField< Type >::snGradTransformDiag(), and Foam::tr().
const Cmpt & zz () const inline
Definition at line 88 of file DiagTensorI.H.
References VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >::v_, and DiagTensor< Cmpt >::ZZ.
Referenced by molecule::constantProperties::constantProperties(), Foam::det(), Foam::inv(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::operator/(), molecule::constantProperties::pointMolecule(), wedgeFvPatchField< Type >::snGradTransformDiag(), and Foam::tr().
Cmpt & xx () inline
Definition at line 95 of file DiagTensorI.H.
References VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >::v_, and DiagTensor< Cmpt >::XX.
Cmpt & yy () inline
Definition at line 101 of file DiagTensorI.H.
References VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >::v_, and DiagTensor< Cmpt >::YY.
Cmpt & zz () inline
Definition at line 107 of file DiagTensorI.H.
References VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >::v_, and DiagTensor< Cmpt >::ZZ.
Member Data Documentation
const char* const typeName static
Definition at line 70 of file DiagTensor.H.
const char* componentNames[] static
Definition at line 71 of file DiagTensor.H.
const DiagTensor zero static
Definition at line 72 of file DiagTensor.H.
const DiagTensor one static
Definition at line 73 of file DiagTensor.H.
const DiagTensor max static
Definition at line 74 of file DiagTensor.H.
const DiagTensor min static
Definition at line 75 of file DiagTensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/DiagTensor/DiagTensor.H
src/OpenFOAM/primitives/DiagTensor/DiagTensorI.H