OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
distanceSurface Class Reference
A sampledSurface defined by a distance to a surface.
Public Member Functions
TypeName ("distanceSurface")
Runtime type information.
distanceSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
distanceSurface (const word &name, const polyMesh &mesh, const bool interpolate, const word &surfaceType, const word &surfaceName, const scalar distance, const bool signedDistance, const bool cell, const Switch regularise, const Switch average)
Construct from components.
virtual ~distanceSurface ()
Destructor.
virtual bool needsUpdate () const
Does the surface need an update?
virtual bool expire ()
Mark the surface as needing an update.
virtual bool update ()
Update the surface as required.
virtual const pointField & points () const
Points of surface.
virtual const faceList & faces () const
Faces of surface.
const triSurface & surface () const
virtual tmp< scalarField > sample (const volScalarField &) const
Sample field on surface.
virtual tmp< vectorField > sample (const volVectorField &) const
Sample field on surface.
virtual tmp< sphericalTensorField > sample (const volSphericalTensorField &) const
Sample field on surface.
virtual tmp< symmTensorField > sample (const volSymmTensorField &) const
Sample field on surface.
virtual tmp< tensorField > sample (const volTensorField &) const
Sample field on surface.
virtual tmp< scalarField > interpolate (const interpolation< scalar > &) const
Interpolate field on surface.
virtual tmp< vectorField > interpolate (const interpolation< vector > &) const
Interpolate field on surface.
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &) const
Interpolate field on surface.
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &) const
Interpolate field on surface.
virtual tmp< tensorField > interpolate (const interpolation< tensor > &) const
Interpolate field on surface.
virtual void print (Ostream &) const
Write.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleField (const GeometricField< Type, fvPatchField, volMesh > &vField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateField (const interpolation< Type > &interpolator) const
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &, const dictionary &)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor.
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool interpolate () const
Interpolation requested for surface.
virtual const vectorField & Sf () const
Return face area vectors.
virtual const scalarField & magSf () const
Return face area magnitudes.
virtual const vectorField & Cf () const
Return face centres as vectorField.
scalar area () const
The total surface area.
template<class Type >
Type integrate (const Field< Type > &) const
Integration of a field across the surface.
template<class Type >
Type integrate (const tmp< Field< Type >> &) const
Integration of a field across the surface.
template<class Type >
Type average (const Field< Type > &) const
Area-averaged value of a field across the surface.
template<class Type >
Type average (const tmp< Field< Type >> &) const
Area-averaged value of a field across the surface.
tmp< Field< scalar > > project (const Field< scalar > &) const
Project field onto surface.
tmp< Field< scalar > > project (const Field< vector > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< sphericalTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< symmTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< tensor > &) const
Project field onto surface.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Interpolate from points to cell centre.
virtual tmp< scalarField > sample (const surfaceScalarField &) const
Surface sample field on surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &) const
Surface sample field on surface.
virtual tmp< tensorField > sample (const surfaceTensorField &) const
Surface sample field on surface.
virtual void rename (const word &newName)
Rename.
template<class ReturnType , class Type >
Foam::tmp< Foam::Field< ReturnType > > project (const tmp< Field< Type >> &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Additional Inherited Members
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &, const dictionary &)
Return a reference to the selected surface.
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
Detailed Description
A sampledSurface defined by a distance to a surface.
Uses either isoSurfaceCell or isoSurface.
Source files
distanceSurface.H
distanceSurface.C
Definition at line 53 of file distanceSurface.H.
Constructor & Destructor Documentation
distanceSurface (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 304 of file distanceSurface.C.
distanceSurface (const word & name, const polyMesh & mesh, const bool interpolate, const word & surfaceType, const word & surfaceName, const scalar distance, const bool signedDistance, const bool cell, const Switch regularise, const Switch average)
Construct from components.
Definition at line 351 of file distanceSurface.C.
~distanceSurface () virtual
Destructor.
Definition at line 397 of file distanceSurface.C.
Member Function Documentation
TypeName ("distanceSurface")
Runtime type information.
bool needsUpdate () const virtual
Does the surface need an update?
Implements sampledSurface.
Definition at line 403 of file distanceSurface.C.
bool expire () virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implements sampledSurface.
Definition at line 409 of file distanceSurface.C.
References Foam::endl(), and Foam::Pout.
bool update () virtual
Update the surface as required.
Do nothing (and return false) if no update was needed
Implements sampledSurface.
Definition at line 435 of file distanceSurface.C.
References Foam::endl(), Foam::Pout, and distanceSurface::sample().
virtual const pointField& points () const inline virtual
Points of surface.
Implements sampledSurface.
Definition at line 169 of file distanceSurface.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::points(), and distanceSurface::surface().
virtual const faceList& faces () const inline virtual
Faces of surface.
Implements sampledSurface.
Definition at line 175 of file distanceSurface.H.
References autoPtr< T >::empty(), forAll, autoPtr< T >::reset(), s(), List< T >::size(), and distanceSurface::surface().
const triSurface& surface () const inline
Definition at line 191 of file distanceSurface.H.
References sampledSurface::interpolate(), distanceSurface::print(), and distanceSurface::sample().
Referenced by distanceSurface::faces(), and distanceSurface::points().
Foam::tmp< Foam::scalarField > sample (const volScalarField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 457 of file distanceSurface.C.
Referenced by distanceSurface::sample(), distanceSurface::surface(), and distanceSurface::update().
Foam::tmp< Foam::vectorField > sample (const volVectorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 466 of file distanceSurface.C.
References distanceSurface::sample().
Foam::tmp< Foam::sphericalTensorField > sample (const volSphericalTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 475 of file distanceSurface.C.
References distanceSurface::sample().
Foam::tmp< Foam::symmTensorField > sample (const volSymmTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 484 of file distanceSurface.C.
References distanceSurface::sample().
Foam::tmp< Foam::tensorField > sample (const volTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 493 of file distanceSurface.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 502 of file distanceSurface.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 511 of file distanceSurface.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 519 of file distanceSurface.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 528 of file distanceSurface.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 537 of file distanceSurface.C.
void print (Ostream & os) const virtual
Write.
Reimplemented from sampledSurface.
Definition at line 545 of file distanceSurface.C.
References Foam::name(), points, and List< T >::size().
Referenced by distanceSurface::surface().
Foam::tmp<Foam::Field<Type> > sampleField (const GeometricField< Type, fvPatchField, volMesh > & vField) const
Definition at line 36 of file distanceSurfaceTemplates.C.
Foam::tmp<Foam::Field<Type> > interpolateField (const interpolation< Type > & interpolator) const
Definition at line 60 of file distanceSurfaceTemplates.C.
References Foam::MULES::interpolate(), mesh, Foam::New(), and interpolation< Type >::psi().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/distanceSurface/distanceSurface.H
src/sampling/sampledSurface/distanceSurface/distanceSurface.C
src/sampling/sampledSurface/distanceSurface/distanceSurfaceTemplates.C