OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
DictionaryBase< IDLListType, T > Class Template Reference
Base dictionary class templated on both the form of doubly-linked list it uses as well as the type it holds.
Public Member Functions
DictionaryBase (const label size=128)
Construct given initial table size.
DictionaryBase (const DictionaryBase &)
Copy construct.
template<class INew >
DictionaryBase (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
DictionaryBase (Istream &)
Construct from Istream using default Istream constructor class.
bool found (const word &) const
Search DictionaryBase for given keyword.
const T * lookupPtr (const word &) const
Find and return an entry if present, otherwise return NULL.
T * lookupPtr (const word &)
Find and return an entry if present, otherwise return NULL.
const T * lookup (const word &) const
Find and return entry.
T * lookup (const word &)
Find and return entry.
wordList toc () const
Return the table of contents.
void insert (const word &, T *)
Add at head of dictionary.
void append (const word &, T *)
Add at tail of dictionary.
T * remove (const word &)
Remove and return entry specified by keyword.
void clear ()
Clear the dictionary.
void transfer (DictionaryBase< IDLListType, T > &)
Transfer the contents of the argument into this DictionaryBase.
void operator= (const DictionaryBase &)
const T * operator[] (const word &key) const
Find and return entry.
T * operator[] (const word &key)
Find and return entry.
Protected Member Functions
void addEntries ()
Protected Attributes
HashTable< T * > hashedTs_
HashTable of the entries held on the IDLListType for quick lookup.
Friends
Ostream & operator (Ostream &, const DictionaryBase< IDLListType, T > &)
Detailed Description
template<class IDLListType, class T>
class Foam::DictionaryBase< IDLListType, T >
Base dictionary class templated on both the form of doubly-linked list it uses as well as the type it holds.
The double templating allows for the instantiation of forms with or without storage management.
Note
The IDLListType parameter should itself be a template but this confused gcc 2.95.2 so it has to be instantiated for T when an instantiation of DictionaryBase is requested
See also
Dictionary and UDictionary
Source files
DictionaryBase.H
DictionaryBase.C
DictionaryBaseIO.C
Definition at line 61 of file DictionaryBase.H.
Constructor & Destructor Documentation
DictionaryBase (const label size = 128)
Construct given initial table size.
Definition at line 48 of file DictionaryBase.C.
Referenced by DictionaryBase< IDLListType, T >::DictionaryBase().
DictionaryBase (const DictionaryBase< IDLListType, T > & dict)
Copy construct.
Definition at line 56 of file DictionaryBase.C.
References DictionaryBase< IDLListType, T >::addEntries(), and DictionaryBase< IDLListType, T >::DictionaryBase().
DictionaryBase (Istream & is, const INew & iNew)
Construct from Istream using given Istream constructor class.
Definition at line 69 of file DictionaryBase.C.
References DictionaryBase< IDLListType, T >::addEntries().
DictionaryBase (Istream & is)
Construct from Istream using default Istream constructor class.
Definition at line 81 of file DictionaryBase.C.
References DictionaryBase< IDLListType, T >::addEntries().
Member Function Documentation
void addEntries () protected
Definition at line 31 of file DictionaryBase.C.
Referenced by DictionaryBase< IDLListType, T >::DictionaryBase(), and DictionaryBase< IDLListType, T >::operator=().
bool found (const word & keyword) const
Search DictionaryBase for given keyword.
Definition at line 92 of file DictionaryBase.C.
References HashTable< T, Key, Hash >::found(), DictionaryBase< IDLListType, T >::hashedTs_, DictionaryBase< IDLListType, T >::lookupPtr(), and Foam::T().
const T * lookupPtr (const word & keyword) const
Find and return an entry if present, otherwise return NULL.
Definition at line 100 of file DictionaryBase.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::find(), and DictionaryBase< IDLListType, T >::hashedTs_.
Referenced by Foam::debug::addDebugObject(), Foam::debug::addDimensionedConstantObject(), Foam::debug::addDimensionSetObject(), Foam::debug::addInfoObject(), Foam::debug::addOptimisationObject(), DictionaryBase< IDLListType, T >::found(), and Time::readDict().
T * lookupPtr (const word & keyword)
Find and return an entry if present, otherwise return NULL.
Definition at line 118 of file DictionaryBase.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::find(), and DictionaryBase< IDLListType, T >::hashedTs_.
const T * lookup (const word & keyword) const
Find and return entry.
Definition at line 134 of file DictionaryBase.C.
References HashTableCore::end(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), and DictionaryBase< IDLListType, T >::hashedTs_.
Referenced by DictionaryBase< DLPtrList< T >, T >::operator[]().
T * lookup (const word & keyword)
Find and return entry.
Definition at line 150 of file DictionaryBase.C.
References HashTableCore::end(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), and DictionaryBase< IDLListType, T >::hashedTs_.
Foam::wordList toc () const
Return the table of contents.
Definition at line 166 of file DictionaryBase.C.
void insert (const word & keyword, T * tPtr)
Add at head of dictionary.
Definition at line 186 of file DictionaryBase.C.
References DictionaryBase< IDLListType, T >::hashedTs_, insert(), and HashTable< T, Key, Hash >::insert().
void append (const word & keyword, T * tPtr)
Add at tail of dictionary.
Definition at line 195 of file DictionaryBase.C.
References DictionaryBase< IDLListType, T >::hashedTs_, and HashTable< T, Key, Hash >::insert().
Referenced by Foam::debug::addDebugObject(), Foam::debug::addDimensionedConstantObject(), Foam::debug::addDimensionSetObject(), Foam::debug::addInfoObject(), and Foam::debug::addOptimisationObject().
T * remove (const word & keyword)
Remove and return entry specified by keyword.
Return NULL if the keyword was not found.
Definition at line 204 of file DictionaryBase.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::erase(), HashTable< T, Key, Hash >::find(), DictionaryBase< IDLListType, T >::hashedTs_, and Foam::T().
void clear ()
Clear the dictionary.
Definition at line 222 of file DictionaryBase.C.
References clear(), HashTable< T, Key, Hash >::clear(), DictionaryBase< IDLListType, T >::hashedTs_, and DictionaryBase< IDLListType, T >::transfer().
void transfer (DictionaryBase< IDLListType, T > & dict)
Transfer the contents of the argument into this DictionaryBase.
and annul the argument.
Definition at line 231 of file DictionaryBase.C.
References DictionaryBase< IDLListType, T >::hashedTs_, and HashTable< T, Key, Hash >::transfer().
Referenced by DictionaryBase< IDLListType, T >::clear().
void operator= (const DictionaryBase< IDLListType, T > &)
Definition at line 244 of file DictionaryBase.C.
References Foam::abort(), DictionaryBase< IDLListType, T >::addEntries(), HashTable< T, Key, Hash >::clear(), Foam::FatalError, FatalErrorInFunction, and DictionaryBase< IDLListType, T >::hashedTs_.
const T* operator[] (const word & key) const inline
Find and return entry.
Definition at line 156 of file DictionaryBase.H.
T* operator[] (const word & key) inline
Find and return entry.
Definition at line 162 of file DictionaryBase.H.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const DictionaryBase< IDLListType, T > &) friend
Member Data Documentation
HashTable<T*> hashedTs_ protected
HashTable of the entries held on the IDLListType for quick lookup.
Definition at line 81 of file DictionaryBase.H.
Referenced by DictionaryBase< IDLListType, T >::append(), DictionaryBase< IDLListType, T >::clear(), DictionaryBase< IDLListType, T >::found(), DictionaryBase< IDLListType, T >::insert(), DictionaryBase< IDLListType, T >::lookup(), DictionaryBase< IDLListType, T >::lookupPtr(), DictionaryBase< IDLListType, T >::operator=(), DictionaryBase< IDLListType, T >::remove(), and DictionaryBase< IDLListType, T >::transfer().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Dictionaries/DictionaryBase/DictionaryBase.H
src/OpenFOAM/containers/Dictionaries/DictionaryBase/DictionaryBase.C