OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
eddyDiffusivity< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for single-phase compressible turbulence models.
Public Types
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Member Functions
eddyDiffusivity (const word &type, const geometricOneField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasport, const word &propertiesName)
Construct.
virtual ~eddyDiffusivity ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
virtual tmp< volScalarField > alphat () const
Return the turbulent thermal diffusivity for enthalpy [kg/m/s].
virtual tmp< scalarField > alphat (const label patchi) const
Return the turbulent thermal diffusivity for enthalpy for a patch.
virtual tmp< volScalarField > kappaEff () const
Return the effective turbulent thermal diffusivity for temperature.
virtual tmp< scalarField > kappaEff (const label patchi) const
Return the effective turbulent thermal diffusivity for temperature.
virtual tmp< volScalarField > alphaEff () const
Return the effective turbulent thermal diffusivity for enthalpy.
virtual tmp< scalarField > alphaEff (const label patchi) const
Return the effective turbulent thermal diffusivity for enthalpy.
Static Public Member Functions
static autoPtr< eddyDiffusivity > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const transportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Protected Member Functions
virtual void correctNut ()
Protected Attributes
dimensionedScalar Prt_
volScalarField alphat_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::eddyDiffusivity< BasicTurbulenceModel >
Templated abstract base class for single-phase compressible turbulence models.
Source files
eddyDiffusivity.H
eddyDiffusivity.C
Definition at line 50 of file eddyDiffusivity.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 75 of file eddyDiffusivity.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 76 of file eddyDiffusivity.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 77 of file eddyDiffusivity.H.
Constructor & Destructor Documentation
eddyDiffusivity (const word & type, const geometricOneField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & trasport, const word & propertiesName)
Construct.
Definition at line 42 of file eddyDiffusivity.C.
virtual ~eddyDiffusivity () inline virtual
Destructor.
Definition at line 110 of file eddyDiffusivity.H.
Member Function Documentation
void correctNut () protected virtual
Reimplemented in kEpsilon< eddyDiffusivity< compressible::turbulenceModel > >, and eddyViscosity< RASModel< eddyDiffusivity< compressible::turbulenceModel > > >.
Definition at line 31 of file eddyDiffusivity.C.
References nut.
Foam::autoPtr< Foam::eddyDiffusivity< BasicTurbulenceModel > > New (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const transportModel & trasportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Definition at line 97 of file eddyDiffusivity.C.
bool read () virtual
Re-read model coefficients if they have changed.
Reimplemented in RASModel< eddyDiffusivity< compressible::turbulenceModel > >, kEpsilon< eddyDiffusivity< compressible::turbulenceModel > >, PDRkEpsilon, eddyViscosity< RASModel< eddyDiffusivity< compressible::turbulenceModel > > >, and linearViscousStress< RASModel< eddyDiffusivity< compressible::turbulenceModel > > >.
Definition at line 123 of file eddyDiffusivity.C.
References Foam::read().
virtual tmp<volScalarField> alphat () const inline virtual
Return the turbulent thermal diffusivity for enthalpy [kg/m/s].
Definition at line 120 of file eddyDiffusivity.H.
Referenced by eddyDiffusivity< compressible::turbulenceModel >::alphaEff(), eddyDiffusivity< compressible::turbulenceModel >::alphat(), and eddyDiffusivity< compressible::turbulenceModel >::kappaEff().
virtual tmp<scalarField> alphat (const label patchi) const inline virtual
Return the turbulent thermal diffusivity for enthalpy for a patch.
[kg/m/s]
Definition at line 127 of file eddyDiffusivity.H.
virtual tmp<volScalarField> kappaEff () const inline virtual
Return the effective turbulent thermal diffusivity for temperature.
[J/m/s/K]
Definition at line 134 of file eddyDiffusivity.H.
virtual tmp<scalarField> kappaEff (const label patchi) const inline virtual
Return the effective turbulent thermal diffusivity for temperature.
[J/m/s/K]
Definition at line 141 of file eddyDiffusivity.H.
virtual tmp<volScalarField> alphaEff () const inline virtual
Return the effective turbulent thermal diffusivity for enthalpy.
[kg/m/s]
Definition at line 148 of file eddyDiffusivity.H.
virtual tmp<scalarField> alphaEff (const label patchi) const inline virtual
Return the effective turbulent thermal diffusivity for enthalpy.
for a patch [kg/m/s]
Definition at line 155 of file eddyDiffusivity.H.
Member Data Documentation
dimensionedScalar Prt_ protected
Definition at line 61 of file eddyDiffusivity.H.
volScalarField alphat_ protected
Definition at line 65 of file eddyDiffusivity.H.
Referenced by eddyDiffusivity< compressible::turbulenceModel >::alphat().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/eddyDiffusivity/eddyDiffusivity.H
src/TurbulenceModels/compressible/eddyDiffusivity/eddyDiffusivity.C