OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
div Class Reference
Writes scalar fields corresponding to the divergence of the supplied field (name) for each time.
Public Member Functions
TypeName ("div")
Runtime type information.
div ()
Construct null.
virtual ~div ()
Destructor.
Public Member Functions inherited from calcType
TypeName ("calcType")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, calcType, dictionary,(),())
calcType ()
Construct null.
virtual ~calcType ()
Destructor.
void tryInit ()
Initialise - typically setting static variables,.
void tryPreCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Pre-time loop calculations.
void tryCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Time loop calculations.
void tryPostCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Post-time loop calculations.
Protected Member Functions
virtual void init ()
Initialise - typically setting static variables,.
virtual void preCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Pre-time loop calculations.
virtual void calc (const argList &args, const Time &runTime, const fvMesh &mesh)
Time loop calculations.
template<class Type >
void writeDivField (const IOobject &header, const fvMesh &mesh, bool &processed)
Write div fields.
Protected Member Functions inherited from calcType
virtual void postCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Post-time loop calculations.
Additional Inherited Members
Static Public Member Functions inherited from calcType
static autoPtr< calcType > New (const word &calcTypeName)
Detailed Description
Writes scalar fields corresponding to the divergence of the supplied field (name) for each time.
Source files
div.H
div.C
Definition at line 52 of file div.H.
Constructor & Destructor Documentation
div ()
Construct null.
Definition at line 43 of file div.C.
~div () virtual
Destructor.
Definition at line 51 of file div.C.
Member Function Documentation
void init () protected virtual
Initialise - typically setting static variables,.
e.g. command line arguments
Reimplemented from calcType.
Definition at line 57 of file div.C.
References div::preCalc(), and argList::validArgs.
void preCalc (const argList & args, const Time & runTime, const fvMesh & mesh) protected virtual
Pre-time loop calculations.
Reimplemented from calcType.
Definition at line 65 of file div.C.
References div::calc().
Referenced by div::init().
void calc (const argList & args, const Time & runTime, const fvMesh & mesh) protected virtual
Time loop calculations.
Reimplemented from calcType.
Definition at line 74 of file div.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, Foam::Info, mesh, IOobject::MUST_READ, Foam::nl, and Time::timeName().
Referenced by div::preCalc().
void writeDivField (const IOobject & header, const fvMesh & mesh, bool & processed) protected
Write div fields.
Definition at line 28 of file writeDivField.C.
References Foam::fvc::div(), Foam::endl(), IOobject::headerClassName(), Foam::Info, mesh, IOobject::name(), fvMesh::time(), Time::timeName(), and regIOobject::write().
TypeName ("div")
Runtime type information.
The documentation for this class was generated from the following files:
src/postProcessing/foamCalcFunctions/field/div/div.H
src/postProcessing/foamCalcFunctions/field/div/div.C
src/postProcessing/foamCalcFunctions/field/div/writeDivField.C