OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dimensioned< Type > Class Template Reference
Generic dimensioned Type class.
Public Types
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Member Functions
dimensioned (const word &, const dimensionSet &, const Type)
Construct given a name, a value and its dimensionSet.
dimensioned (const word &, const dimensioned< Type > &)
Construct from a dimensioned<Type> changing the name.
dimensioned (const Type &t)
Construct given a value (creates dimensionless value).
dimensioned (Istream &)
Construct from Istream.
dimensioned (const word &, Istream &)
Construct from an Istream with a given name.
dimensioned (const word &, const dimensionSet &, Istream &)
Construct from an Istream with a given name and dimensions.
dimensioned ()
Null constructor.
const word & name () const
Return const reference to name.
word & name ()
Return non-const reference to name.
const dimensionSet & dimensions () const
Return const reference to dimensions.
dimensionSet & dimensions ()
Return non-const reference to dimensions.
const Type & value () const
Return const reference to value.
Type & value ()
Return non-const reference to value.
dimensioned< cmptType > component (const direction) const
Return a component as a dimensioned<cmptType>
void replace (const direction, const dimensioned< cmptType > &)
Return a component with a dimensioned<cmptType>
dimensioned< Type > T () const
Return transpose.
void read (const dictionary &)
Update the value of dimensioned<Type>
bool readIfPresent (const dictionary &)
Update the value of dimensioned<Type> if found in the dictionary.
Istream & read (Istream &is, const dictionary &)
Read value from stream and units from dictionary.
Istream & read (Istream &is, const HashTable< dimensionedScalar > &)
Read value from stream and units from table.
Istream & read (Istream &is)
Read value from stream and units from system table.
dimensioned< cmptType > operator[] (const direction) const
Return a component as a dimensioned<cmptType>
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Member Functions
static dimensioned< Type > lookupOrDefault (const word &, const dictionary &, const Type &defaultValue=pTraits< Type >::zero, const dimensionSet &dims=dimless)
Construct from dictionary, with default value.
static dimensioned< Type > lookupOrAddToDict (const word &, dictionary &, const Type &defaultValue=pTraits< Type >::zero, const dimensionSet &dims=dimless)
Construct from dictionary, with default value.
Friends
Istream & operator>> (Istream &, dimensioned< Type > &)
Ostream & operator (Ostream &, const dimensioned< Type > &)
Detailed Description
template<class Type>
class Foam::dimensioned< Type >
Generic dimensioned Type class.
Source files
dimensionedType.H
dimensionedType.C
Definition at line 41 of file dimensionedScalarFwd.H.
Member Typedef Documentation
typedef pTraits<Type>::cmptType cmptType
Component type.
Definition at line 81 of file dimensionedType.H.
Constructor & Destructor Documentation
dimensioned (const word & name, const dimensionSet & dimSet, const Type t)
Construct given a name, a value and its dimensionSet.
Definition at line 70 of file dimensionedType.C.
dimensioned (const word & name, const dimensioned< Type > & dt)
Construct from a dimensioned<Type> changing the name.
Definition at line 84 of file dimensionedType.C.
dimensioned (const Type & t) inline
Construct given a value (creates dimensionless value).
Definition at line 93 of file dimensionedType.H.
dimensioned (Istream & is)
Construct from Istream.
Definition at line 97 of file dimensionedType.C.
References Foam::read().
dimensioned (const word & name, Istream & is)
Construct from an Istream with a given name.
Definition at line 109 of file dimensionedType.C.
dimensioned (const word & name, const dimensionSet & dimSet, Istream & is)
Construct from an Istream with a given name and dimensions.
Definition at line 126 of file dimensionedType.C.
References Foam::abort(), Foam::dimless, Foam::FatalIOError, FatalIOErrorIn, token::isWord(), Istream::putBack(), and dimensionSet::read().
dimensioned ()
Null constructor.
Definition at line 177 of file dimensionedType.C.
Member Function Documentation
Foam::dimensioned< Type > lookupOrDefault (const word & name, const dictionary & dict, const Type & defaultValue = pTraits<Type>::zero, const dimensionSet & dims = dimless) static
Construct from dictionary, with default value.
Definition at line 34 of file dimensionedType.C.
References dictionary::found(), dictionary::lookup(), and Foam::name().
Foam::dimensioned< Type > lookupOrAddToDict (const word & name, dictionary & dict, const Type & defaultValue = pTraits<Type>::zero, const dimensionSet & dims = dimless) static
Construct from dictionary, with default value.
If the value is not found, it is added into the dictionary.
Definition at line 54 of file dimensionedType.C.
References dictionary::lookupOrAddDefault(), Foam::name(), and value().
const Foam::word & name () const
Return const reference to name.
Definition at line 188 of file dimensionedType.C.
Referenced by Foam::atan2(), Foam::cbrt(), Foam::checkMethod(), Foam::cof(), Foam::fvm::d2dt2(), Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::det(), Foam::dev(), Foam::dev2(), Foam::eigenValues(), Foam::eigenVectors(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), Foam::hypot(), Foam::innerSqr(), Foam::inv(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), Foam::fvc::meshPhi(), UniformDimensionedField< scalar >::name(), Foam::neg(), Foam::operator*(), Foam::pos(), Foam::pow(), Foam::pow025(), Foam::pow3(), Foam::pow4(), Foam::pow5(), Foam::pow6(), Foam::sign(), Foam::skew(), Foam::sqr(), Foam::sqrt(), Foam::stabilise(), Foam::symm(), dimensioned< Type >::T(), Foam::tr(), Foam::transform(), Foam::twoSymm(), and dimensionSet::write().
Foam::word & name ()
Return non-const reference to name.
Definition at line 194 of file dimensionedType.C.
const Foam::dimensionSet & dimensions () const
Return const reference to dimensions.
Definition at line 201 of file dimensionedType.C.
Referenced by Foam::atan2(), Foam::cbrt(), Foam::checkMethod(), Foam::cof(), Foam::det(), Foam::dev(), Foam::dev2(), dimensionSets::dimensionSets(), Foam::eigenValues(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), steadyStateD2dt2Scheme< Type >::fvmD2dt2(), EulerD2dt2Scheme< Type >::fvmD2dt2(), steadyStateDdtScheme< Type >::fvmDdt(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), Foam::hypot(), Foam::innerSqr(), Foam::inv(), Foam::neg(), Foam::operator*(), DimensionedField< Type, GeoMesh >::operator=(), Foam::pos(), Foam::pow(), Foam::pow025(), Foam::pow3(), Foam::pow4(), Foam::pow5(), Foam::pow6(), dimensionSet::read(), Foam::sign(), Foam::skew(), Foam::sqr(), Foam::sqrt(), Foam::stabilise(), Foam::symm(), dimensioned< Type >::T(), Foam::tr(), and Foam::twoSymm().
Foam::dimensionSet & dimensions ()
Return non-const reference to dimensions.
Definition at line 207 of file dimensionedType.C.
const Type & value () const
Return const reference to value.
Definition at line 214 of file dimensionedType.C.
Referenced by fieldAverage::addMeanFieldType(), interRegionHeatTransferModel::addSup(), porosityModel::adjustNegativeResistance(), Foam::atan2(), Foam::bound(), NonInertialFrameForce< CloudType >::cacheFields(), BrownianMotionForce< CloudType >::calcCoupled(), ThermoParcel< ParcelType >::calcHeatTransfer(), SRFForce< CloudType >::calcNonCoupled(), ParamagneticForce< CloudType >::calcNonCoupled(), wallShearStress::calcShearStress(), viewFactor::calculate(), Foam::cbrt(), Foam::cof(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), curvatureSeparation::curvatureSeparation(), CrankNicolsonDdtScheme< Type >::ddt0_(), Foam::det(), Foam::dev(), Foam::dev2(), blackBodyEmission::EbDeltaLambdaT(), Foam::eigenValues(), Foam::eigenVectors(), engineMesh::engineMesh(), ThermoCloud< CloudType >::Ep(), buoyantKEpsilon< BasicTurbulenceModel >::epsilonSource(), DSMCCloud< ParcelType >::equipartitionInternalEnergy(), basicCombustionMixture::fres(), EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), Foam::hypot(), reactingOneDim::info(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::InjectionModel(), InjectionModel< CloudType >::injectSteadyState(), Foam::innerSqr(), Foam::inv(), buoyantKEpsilon< BasicTurbulenceModel >::kSource(), hexRef8::level0EdgeLength(), MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField(), GeometricField< Type, PatchField, GeoMesh >::max(), GeometricField< Type, PatchField, GeoMesh >::min(), solidParticleCloud::move(), movingConeTopoFvMesh::movingConeTopoFvMesh(), Foam::neg(), Foam::operator*(), Time::operator+=(), Foam::operator<(), Foam::operator<<(), DimensionedField< Type, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator==(), Foam::operator>(), Foam::operator>>(), UniformDimensionedField< scalar >::operator[](), Foam::pos(), Foam::pow(), Foam::pow025(), Foam::pow3(), Foam::pow4(), Foam::pow5(), Foam::pow6(), dimensionSet::read(), GeometricField< Type, PatchField, GeoMesh >::replace(), incompressibleTwoPhaseInteractingMixture::rho(), timeSelector::selectIfPresent(), Time::setDeltaT(), Time::setEndTime(), Time::setTime(), fixedTemperatureConstraint::setValue(), constantRadiation::Shs(), Foam::sign(), simpleControl::simpleControl(), Foam::skew(), sixDoFRigidBodyMotionSolver::solve(), thermalBaffle::solveEnergy(), Foam::sqr(), Foam::sqrt(), Foam::stabilise(), Foam::symm(), dimensioned< Type >::T(), Foam::tr(), Foam::transform(), Foam::twoSymm(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingDisplacementPointPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), alphaFixedPressureFvPatchScalarField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), MarshakRadiationFvPatchScalarField::updateCoeffs(), MarshakRadiationFixedTemperatureFvPatchScalarField::updateCoeffs(), SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), uniformDensityHydrostaticPressureFvPatchScalarField::updateCoeffs(), fvMesh::Vsc(), fvMesh::Vsc0(), wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField(), FacePostProcessing< CloudType >::write(), ParticleCollector< CloudType >::write(), and dimensionSet::write().
Type & value ()
Return non-const reference to value.
Definition at line 220 of file dimensionedType.C.
Foam::dimensioned< typename Foam::dimensioned< Type >::cmptType > component (const direction d) const
Return a component as a dimensioned<cmptType>
Definition at line 229 of file dimensionedType.C.
References Foam::name().
void replace (const direction , const dimensioned< cmptType > &)
Return a component with a dimensioned<cmptType>
Definition at line 244 of file dimensionedType.C.
dimensionedTensor T () const
Return transpose.
Definition at line 36 of file dimensionedSphericalTensor.C.
References dimensioned< Type >::dimensions(), dimensioned< Type >::name(), and dimensioned< Type >::value().
void read (const dictionary & dict)
Update the value of dimensioned<Type>
Definition at line 255 of file dimensionedType.C.
References dictionary::lookup().
Referenced by dimensionSet::read(), and Foam::unitSet().
bool readIfPresent (const dictionary & dict)
Update the value of dimensioned<Type> if found in the dictionary.
Definition at line 262 of file dimensionedType.C.
References dictionary::readIfPresent().
Referenced by engineTime::engineTime(), LamBremhorstKE::read(), ShihQuadraticKE::read(), qZeta::read(), LienLeschziner::read(), LienCubicKE::read(), SpalartAllmaras< BasicTurbulenceModel >::read(), SpalartAllmarasDES< BasicTurbulenceModel >::read(), and kkLOmega::read().
Foam::Istream & read (Istream & is, const dictionary & readSet)
Read value from stream and units from dictionary.
Definition at line 270 of file dimensionedType.C.
References IOstream::check(), and Istream::read().
Foam::Istream & read (Istream & is, const HashTable< dimensionedScalar > & readSet)
Read value from stream and units from table.
Definition at line 295 of file dimensionedType.C.
References IOstream::check(), and Istream::read().
Foam::Istream & read (Istream & is)
Read value from stream and units from system table.
Definition at line 323 of file dimensionedType.C.
References IOstream::check(), and Istream::read().
Foam::dimensioned< typename Foam::dimensioned< Type >::cmptType > operator[] (const direction d) const
Return a component as a dimensioned<cmptType>
Definition at line 351 of file dimensionedType.C.
References Foam::component().
void operator+= (const dimensioned< Type > & dt)
Definition at line 361 of file dimensionedType.C.
void operator-= (const dimensioned< Type > & dt)
Definition at line 372 of file dimensionedType.C.
void operator*= (const scalar s)
Definition at line 383 of file dimensionedType.C.
References s().
void operator/= (const scalar s)
Definition at line 393 of file dimensionedType.C.
References s().
Friends And Related Function Documentation
Istream& operator>> (Istream & , dimensioned< Type > &) friend
Ostream& operator (Ostream & , const dimensioned< Type > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/dimensionedTypes/dimensionedScalar/dimensionedScalarFwd.H
src/OpenFOAM/dimensionedTypes/dimensionedType/dimensionedType.H
src/OpenFOAM/dimensionedTypes/dimensionedSphericalTensor/dimensionedSphericalTensor.C
src/OpenFOAM/dimensionedTypes/dimensionedSymmTensor/dimensionedSymmTensor.C
src/OpenFOAM/dimensionedTypes/dimensionedTensor/dimensionedTensor.C
src/OpenFOAM/dimensionedTypes/dimensionedType/dimensionedType.C