OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
div Class Reference
FunctionObjects » Field function objects
This function object calculates the divergence of a field. The operation is limited to surfaceScalarFields and volumeVector fields, and the output is a volume scalar field.
Public Member Functions
TypeName ("div")
Runtime type information.
div (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~div ()
Destructor.
virtual const word & name () const
Return name of the set of div.
virtual void read (const dictionary &)
Read the div data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the div and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Static Public Member Functions
static bool viable (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Return true if the construction of this functionObject is viable.
Detailed Description
This function object calculates the divergence of a field. The operation is limited to surfaceScalarFields and volumeVector fields, and the output is a volume scalar field.
Source files
div.H
div.C
IOdiv.H
Definition at line 68 of file div.H.
Constructor & Destructor Documentation
div (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 83 of file div.C.
References Foam::read(), and div::viable().
~div () virtual
Destructor.
Definition at line 114 of file div.C.
Member Function Documentation
TypeName ("div")
Runtime type information.
bool viable (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false) static
Return true if the construction of this functionObject is viable.
i.e. the prerequisites for construction are available
Definition at line 100 of file div.C.
Referenced by div::div().
virtual const word& name () const inline virtual
Return name of the set of div.
Definition at line 146 of file div.H.
References div::end(), div::execute(), div::read(), div::timeSet(), and div::write().
void read (const dictionary & dict) virtual
Read the div data.
Definition at line 120 of file div.C.
References dictionary::lookup().
Referenced by div::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 132 of file div.C.
References Foam::endl(), and WarningInFunction.
Referenced by div::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 147 of file div.C.
Referenced by div::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 153 of file div.C.
Referenced by div::name().
void write () virtual
Calculate the div and write.
Definition at line 157 of file div.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by div::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 167 of file div.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 171 of file div.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/div/div.H
src/postProcessing/functionObjects/field/div/div.C
src/postProcessing/functionObjects/field/div/divTemplates.C