OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
diffusion< CombThermoType, ThermoType > Class Template Reference
Simple diffusion-based combustion model based on the principle mixed is burnt. Additional parameter C is used to distribute the heat release rate in time.
Public Member Functions
TypeName ("diffusion")
Runtime type information.
diffusion (const word &modelType, const fvMesh &mesh, const word &phaseName)
Construct from components.
virtual ~diffusion ()
Destructor.
virtual void correct ()
Correct combustion rate.
virtual bool read ()
Update properties.
Public Member Functions inherited from singleStepCombustion< CombThermoType, ThermoType >
singleStepCombustion (const word &modelType, const fvMesh &mesh, const word &phaseName)
Construct from components.
virtual ~singleStepCombustion ()
Destructor.
virtual tmp< fvScalarMatrix > R (volScalarField &Y) const
Fuel consumption rate matrix.
virtual tmp< volScalarField > dQ () const
Heat release rate calculated from fuel consumption rate matrix.
virtual tmp< volScalarField > Sh () const
Sensible enthalpy source term.
Additional Inherited Members
Protected Attributes inherited from singleStepCombustion< CombThermoType, ThermoType >
singleStepReactingMixture< ThermoType > * singleMixturePtr_
Pointer to singleStepReactingMixture mixture.
volScalarField wFuel_
Fuel consumption rate.
bool semiImplicit_
Semi-implicit (true) or explicit (false) treatment.
Detailed Description
template<class CombThermoType, class ThermoType>
class Foam::combustionModels::diffusion< CombThermoType, ThermoType >
Simple diffusion-based combustion model based on the principle mixed is burnt. Additional parameter C is used to distribute the heat release rate in time.
Source files
diffusion.H
diffusion.C
Definition at line 53 of file diffusion.H.
Constructor & Destructor Documentation
diffusion (const word & modelType, const fvMesh & mesh, const word & phaseName)
Construct from components.
Definition at line 38 of file diffusion.C.
~diffusion () virtual
Destructor.
Definition at line 58 of file diffusion.C.
Member Function Documentation
TypeName ("diffusion< CombThermoType, ThermoType >")
Runtime type information.
void correct () virtual
Correct combustion rate.
Definition at line 65 of file diffusion.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, Foam::fvc::grad(), Foam::mag(), Foam::pos(), Foam::pow3(), and turbulence.
bool read () virtual
Update properties.
Reimplemented from singleStepCombustion< CombThermoType, ThermoType >.
Definition at line 94 of file diffusion.C.
The documentation for this class was generated from the following files:
src/combustionModels/diffusion/diffusion.H
src/combustionModels/diffusion/diffusion.C