OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dynamicAlphaContactAngleFvPatchScalarField Class Reference
A dynamic alphaContactAngle scalar boundary condition (alphaContactAngleFvPatchScalarField)
Public Member Functions
TypeName ("dynamicAlphaContactAngle")
Runtime type information.
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const
Evaluate and return dynamic contact-angle.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from alphaContactAngleFvPatchScalarField
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &)
Construct as copy.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
Additional Inherited Members
Public Types inherited from alphaContactAngleFvPatchScalarField
enum limitControls { lcNone, lcGradient, lcZeroGradient, lcAlpha }
Alpha limit options.
typedef HashTable< interfaceThetaProps, multiphaseMixtureThermo::interfacePair, multiphaseMixtureThermo::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseSystem::interfacePair, multiphaseSystem::interfacePair::symmHash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseMixture::interfacePair, multiphaseMixture::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, phasePairKey, phasePairKey::hash > thetaPropsTable
Public Attributes inherited from alphaContactAngleFvPatchScalarField
limitControls limit_
Static Public Attributes inherited from alphaContactAngleFvPatchScalarField
static const NamedEnum< limitControls, 4 > limitControlNames_
Detailed Description
A dynamic alphaContactAngle scalar boundary condition (alphaContactAngleFvPatchScalarField)
Source files
dynamicAlphaContactAngleFvPatchScalarField.H
dynamicAlphaContactAngleFvPatchScalarField.C
Definition at line 49 of file dynamicAlphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file dynamicAlphaContactAngleFvPatchScalarField.C.
Referenced by dynamicAlphaContactAngleFvPatchScalarField::clone(), and dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField().
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 67 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField().
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField & gcpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
dynamicAlphaContactAngleFvPatchScalarField onto a new patch
Definition at line 50 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField().
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField & gcpsf)
Construct as copy.
Definition at line 85 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField().
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField & gcpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 99 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References dynamicAlphaContactAngleFvPatchScalarField::theta().
Member Function Documentation
TypeName ("dynamicAlphaContactAngle")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 109 of file dynamicAlphaContactAngleFvPatchScalarField.H.
References dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 126 of file dynamicAlphaContactAngleFvPatchScalarField.H.
References dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField(), dynamicAlphaContactAngleFvPatchScalarField::theta(), and dynamicAlphaContactAngleFvPatchScalarField::write().
Foam::tmp< Foam::scalarField > theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const virtual
Evaluate and return dynamic contact-angle.
Implements alphaContactAngleFvPatchScalarField.
Definition at line 116 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References Foam::mag(), fvPatchField< Type >::patchInternalField(), scalarField(), and Foam::tanh().
Referenced by dynamicAlphaContactAngleFvPatchScalarField::clone(), and dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField().
void write (Ostream & os) const virtual
Write.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 146 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, alphaContactAngleFvPatchScalarField::write(), and Ostream::writeKeyword().
Referenced by dynamicAlphaContactAngleFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaContactAngle/dynamicAlphaContactAngle/dynamicAlphaContactAngleFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaContactAngle/dynamicAlphaContactAngle/dynamicAlphaContactAngleFvPatchScalarField.C