OpenFOAM: DampingModel< CloudType > Class Template Reference
DampingModel< CloudType > Class Template Reference abstract
Base class for collisional damping models.
Public Member Functions
TypeName ("dampingModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DampingModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
DampingModel (CloudType &owner)
Construct null from owner.
DampingModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
DampingModel (const DampingModel< CloudType > &cm)
Construct copy.
virtual autoPtr< DampingModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~DampingModel ()
Destructor.
virtual vector velocityCorrection (typename CloudType::parcelType &p, const scalar deltaT) const =0
Calculate the velocity correction.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< DampingModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Attributes
autoPtr< TimeScaleModel > timeScaleModel_
Time scale model.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Detailed Description
template<class CloudType>
class Foam::DampingModel< CloudType >
Base class for collisional damping models.
Source files
DampingModel.H
DampingModel.C
DampingModelNew.C
Definition at line 56 of file MPPICCloud.H.
Constructor & Destructor Documentation
DampingModel (CloudType & owner)
Construct null from owner.
Definition at line 32 of file DampingModel.C.
DampingModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from components.
Definition at line 41 of file DampingModel.C.
DampingModel (const DampingModel< CloudType > & cm)
Construct copy.
Definition at line 59 of file DampingModel.C.
~DampingModel () virtual
Destructor.
Definition at line 69 of file DampingModel.C.
References DampingModel< CloudType >::New().
Member Function Documentation
TypeName ("dampingModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , DampingModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
virtual autoPtr<DampingModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in Relaxation< CloudType >, and NoDamping< CloudType >.
Foam::autoPtr< Foam::DampingModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 78 of file DampingModel.C.
References subModelBase::dict(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), subModelBase::modelType(), Foam::nl, and CloudSubModelBase< CloudType >::owner().
Referenced by DampingModel< CloudType >::~DampingModel().
virtual vector velocityCorrection (typename CloudType::parcelType & p, const scalar deltaT) const pure virtual
Calculate the velocity correction.
Implemented in Relaxation< CloudType >, and NoDamping< CloudType >.
Member Data Documentation
autoPtr<TimeScaleModel> timeScaleModel_ protected
Time scale model.
Definition at line 66 of file DampingModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/MPPICCloud/MPPICCloud.H
src/lagrangian/intermediate/submodels/MPPIC/DampingModels/DampingModel/DampingModel.H
src/lagrangian/intermediate/submodels/MPPIC/DampingModels/DampingModel/DampingModel.C