OpenFOAM: Euler< Type > Class Template Reference
Euler< Type > Class Template Reference
Euler-implicit integration.
Public Member Functions
TypeName ("Euler")
Runtime type information.
Euler (const word &phiName, const dictionary &dict)
Construct from components.
Euler (const Euler &is)
Copy constructor.
virtual autoPtr< IntegrationScheme< Type > > clone () const
Construct and return clone.
virtual ~Euler ()
Destructor.
virtual IntegrationScheme< Type >::integrationResult integrate (const Type &phi, const scalar dt, const Type &alphaBeta, const scalar beta) const
Perform the integration.
TypeName ("Euler")
Runtime type information.
Euler (const ODESystem &ode, const dictionary &dict)
Construct from ODESystem.
virtual ~Euler ()
Destructor.
virtual bool resize ()
Resize the ODE solver.
virtual scalar solve (const scalar x0, const scalarField &y0, const scalarField &dydx0, const scalar dx, scalarField &y) const
Solve a single step dx and return the error.
virtual void solve (scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system and the update the state.
Public Member Functions inherited from ODESolver
TypeName ("ODESolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
Construct for given ODESystem.
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
Construct for given ODESystem specifying tolerances.
virtual ~ODESolver ()
Destructor.
label nEqns () const
Return the number of equations to solve.
scalarField & absTol ()
Return access to the absolute tolerance field.
scalarField & relTol ()
Return access to the relative tolerance field.
template<class Type >
void resizeField (UList< Type > &f) const
void resizeMatrix (scalarSquareMatrix &m) const
virtual void solve (scalar &x, scalarField &y, stepState &step) const
Solve the ODE system as far as possible upto dxTry.
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Solve the ODE system from xStart to xEnd, update the state.
Public Member Functions inherited from adaptiveSolver
adaptiveSolver (const ODESystem &ode, const dictionary &dict)
Construct from ODESystem.
virtual ~adaptiveSolver ()
Destructor.
bool resize (const label n)
Resize the ODE solver.
void solve (const ODESystem &ode, scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system and the update the state.
Public Member Functions inherited from IntegrationScheme< Type >
TypeName ("integrationScheme")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IntegrationScheme, dictionary,(const word &phiName, const dictionary &dict),(phiName, dict))
Declare runtime constructor selection table.
IntegrationScheme (const word &phiName, const dictionary &dict)
Construct from components.
IntegrationScheme (const IntegrationScheme &is)
Copy constructor.
virtual ~IntegrationScheme ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from ODESolver
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
Select null constructed.
template<class Type >
static void resizeField (UList< Type > &f, const label n)
Static Public Member Functions inherited from IntegrationScheme< Type >
static autoPtr< IntegrationScheme > New (const word &phiName, const dictionary &dict)
Return a reference to the selected radiation model.
Protected Member Functions inherited from ODESolver
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
Return the nomalized scalar error.
ODESolver (const ODESolver &)
Disallow default bitwise copy construct.
void operator= (const ODESolver &)
Disallow default bitwise assignment.
Protected Attributes inherited from ODESolver
const ODESystem & odes_
Reference to ODESystem.
const label maxN_
Maximum size of the ODESystem.
label n_
Size of the ODESystem (adjustable)
scalarField absTol_
Absolute convergence tolerance per step.
scalarField relTol_
Relative convergence tolerance per step.
label maxSteps_
The maximum number of sub-steps allowed for the integration step.
Detailed Description
template<class Type>
class Foam::Euler< Type >
Euler-implicit integration.
Euler ODE solver of order (0)1.
The method calculates the new state from:
The error is estimated directly from the change in the solution, i.e. the difference between the 0th and 1st order solutions:
Source files
Euler.H
Euler.C
Definition at line 46 of file Euler.H.
Constructor & Destructor Documentation
Euler (const word & phiName, const dictionary & dict)
Construct from components.
Definition at line 32 of file Euler.C.
Euler (const Euler< Type > & is)
Copy constructor.
Definition at line 42 of file Euler.C.
~Euler () virtual
Destructor.
Definition at line 51 of file Euler.C.
References Euler< Type >::integrate().
Referenced by Euler< Type >::clone().
Euler (const ODESystem & ode, const dictionary & dict)
Construct from ODESystem.
Definition at line 40 of file Euler.C.
virtual ~Euler () inline virtual
Destructor.
Definition at line 82 of file Euler.H.
References Euler< Type >::resize(), Euler< Type >::solve(), ODESolver::solve(), x, y, and Foam::y0().
Member Function Documentation
TypeName ("Euler< Type >")
Runtime type information.
virtual autoPtr<IntegrationScheme<Type> > clone () const inline virtual
Construct and return clone.
Implements IntegrationScheme< Type >.
Definition at line 65 of file Euler.H.
References beta(), Euler< Type >::integrate(), phi, and Euler< Type >::~Euler().
Foam::IntegrationScheme< Type >::integrationResult integrate (const Type & phi, const scalar dt, const Type & alphaBeta, const scalar beta) const virtual
Perform the integration.
Implements IntegrationScheme< Type >.
Definition at line 60 of file Euler.C.
References IntegrationScheme< Type >::integrationResult::average(), and IntegrationScheme< Type >::integrationResult::value().
Referenced by Euler< Type >::clone(), and Euler< Type >::~Euler().
TypeName ("Euler< Type >")
Runtime type information.
bool resize () virtual
Resize the ODE solver.
Implements ODESolver.
Definition at line 50 of file Euler.C.
References ODESolver::n_, adaptiveSolver::resize(), ODESolver::resize(), ODESolver::resizeField(), and Euler< Type >::solve().
Referenced by Euler< Type >::~Euler().
Foam::scalar solve (const scalar x0, const scalarField & y0, const scalarField & dydx0, const scalar dx, scalarField & y) const virtual
Solve a single step dx and return the error.
Implements adaptiveSolver.
Definition at line 68 of file Euler.C.
References forAll, and ODESolver::normalizeError().
Referenced by Euler< Type >::resize(), and Euler< Type >::~Euler().
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Solve the ODE system and the update the state.
Reimplemented from ODESolver.
Definition at line 93 of file Euler.C.
References ODESolver::odes_, and adaptiveSolver::solve().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/IntegrationScheme/Euler/Euler.H
src/lagrangian/intermediate/IntegrationScheme/Euler/Euler.C