OpenFOAM: egrMixture< ThermoType > Class Template Reference
egrMixture< ThermoType > Class Template Reference
Foam::egrMixture.
Public Types
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Public Types inherited from basicCombustionMixture
typedef basicCombustionMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicSpecieMixture
typedef basicSpecieMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Member Functions
egrMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phaseName.
virtual ~egrMixture ()
Destructor.
const dimensionedScalar & stoicRatio () const
const ThermoType & mixture (const scalar, const scalar, const scalar) const
const ThermoType & cellMixture (const label celli) const
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
const ThermoType & cellReactants (const label celli) const
const ThermoType & patchFaceReactants (const label patchi, const label facei) const
const ThermoType & cellProducts (const label celli) const
const ThermoType & patchFaceProducts (const label patchi, const label facei) const
void read (const dictionary &)
Read dictionary.
const ThermoType & getLocalThermo (const label speciei) const
Return thermo based on index.
Public Member Functions inherited from basicCombustionMixture
TypeName ("basicCombustionMixture")
Run time type information.
basicCombustionMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, specie names, mesh and phase name.
virtual ~basicCombustionMixture ()
Destructor.
scalar fres (const scalar ft, const scalar stoicRatio) const
tmp< volScalarField > fres (const volScalarField &ft, const dimensionedScalar &stoicRatio) const
Public Member Functions inherited from basicSpecieMixture
TypeName ("basicSpecieMixture")
Run time type information.
basicSpecieMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicSpecieMixture ()
Destructor.
virtual scalar nMoles (const label speciei) const =0
Number of moles of the given specie [].
virtual scalar W (const label speciei) const =0
Molecular weight of the given specie [kg/kmol].
tmp< volScalarField > W () const
Molecular weight of the mixture [kg/kmol].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar Hc (const label speciei) const =0
Chemical enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
Density [kg/m3].
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
bool contains (const word &specieName) const
Does the mixture include this specie?
bool active (label speciei) const
Return true for active species.
const List< bool > & active () const
Return the bool list of active species.
void setActive (label speciei)
Set speciei active.
void setInactive (label speciei)
Set speciei inactive.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
Table of specie names.
List< bool > active_
List of specie active flags.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
template<class ThermoType>
class Foam::egrMixture< ThermoType >
Foam::egrMixture.
Source files
egrMixture.H
egrMixture.C
Definition at line 49 of file egrMixture.H.
Member Typedef Documentation
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Definition at line 82 of file egrMixture.H.
Constructor & Destructor Documentation
egrMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, mesh and phaseName.
Definition at line 39 of file egrMixture.C.
References egrMixture< ThermoType >::mixture().
virtual ~egrMixture () inline virtual
Destructor.
Definition at line 92 of file egrMixture.H.
Member Function Documentation
const dimensionedScalar& stoicRatio () const inline
Definition at line 98 of file egrMixture.H.
References egrMixture< ThermoType >::mixture().
const ThermoType & mixture (const scalar ft, const scalar b, const scalar egr) const
Definition at line 71 of file egrMixture.C.
References Foam::constant::physicoChemical::b.
Referenced by egrMixture< ThermoType >::cellMixture(), egrMixture< ThermoType >::cellProducts(), egrMixture< ThermoType >::cellReactants(), egrMixture< ThermoType >::egrMixture(), egrMixture< ThermoType >::patchFaceMixture(), egrMixture< ThermoType >::patchFaceProducts(), egrMixture< ThermoType >::patchFaceReactants(), and egrMixture< ThermoType >::stoicRatio().
const ThermoType& cellMixture (const label celli) const inline
Definition at line 110 of file egrMixture.H.
References egrMixture< ThermoType >::mixture(), and egrMixture< ThermoType >::patchFaceMixture().
const ThermoType& patchFaceMixture (const label patchi, const label facei) const inline
Definition at line 116 of file egrMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), egrMixture< ThermoType >::mixture(), and patchi.
Referenced by egrMixture< ThermoType >::cellMixture().
const ThermoType& cellReactants (const label celli) const inline
Definition at line 129 of file egrMixture.H.
References egrMixture< ThermoType >::mixture(), and egrMixture< ThermoType >::patchFaceReactants().
const ThermoType& patchFaceReactants (const label patchi, const label facei) const inline
Definition at line 135 of file egrMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), egrMixture< ThermoType >::mixture(), and patchi.
Referenced by egrMixture< ThermoType >::cellReactants().
const ThermoType& cellProducts (const label celli) const inline
Definition at line 148 of file egrMixture.H.
References egrMixture< ThermoType >::mixture(), and egrMixture< ThermoType >::patchFaceProducts().
const ThermoType& patchFaceProducts (const label patchi, const label facei) const inline
Definition at line 154 of file egrMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), egrMixture< ThermoType >::getLocalThermo(), egrMixture< ThermoType >::mixture(), patchi, and egrMixture< ThermoType >::read().
Referenced by egrMixture< ThermoType >::cellProducts().
void read (const dictionary & thermoDict)
Read dictionary.
Definition at line 102 of file egrMixture.C.
References egrMixture< ThermoType >::getLocalThermo(), dictionary::lookup(), and dictionary::subDict().
Referenced by egrMixture< ThermoType >::patchFaceProducts().
const ThermoType & getLocalThermo (const label speciei) const
Return thermo based on index.
Definition at line 114 of file egrMixture.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by egrMixture< ThermoType >::patchFaceProducts(), and egrMixture< ThermoType >::read().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/egrMixture/egrMixture.H
src/thermophysicalModels/reactionThermo/mixtures/egrMixture/egrMixture.C