OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
dynamicIndexedOctree< Type > Class Template Reference
Non-pointer based hierarchical recursive searching. Storage is dynamic, so elements can be deleted.
Classes
class node
Tree node. Has up pointer and down pointers.
Public Member Functions
dynamicIndexedOctree (const Type &shapes, const treeBoundBox &bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
autoPtr< dynamicIndexedOctree< Type > > clone () const
Clone.
const Type & shapes () const
Reference to shape.
const List< node > & nodes () const
List of all nodes.
const contentListList & contents () const
List of all contents (referenced by those nodes that are.
const treeBoundBox & bb () const
Top bounding box.
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
Calculate nearest point on nearest shape.
void findNearest (const label nodeI, const point &, scalar &nearestDistSqr, label &nearestShapeI, point &nearestPoint) const
Low level: calculate nearest starting from subnode.
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
Find nearest to line.
pointIndexHit findLine (const point &start, const point &end) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point &start, const point &end) const
Find any intersection of line between start and end.
labelList findBox (const treeBoundBox &bb) const
Find (in no particular order) indices of all shapes inside or.
labelList findSphere (const point &centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
labelBits findNode (const label nodeI, const point &) const
Find deepest node (as parent+octant) containing point. Starts.
label findInside (const point &) const
Find shape containing point. Only implemented for certain.
const labelList & findIndices (const point &) const
Find the shape indices that occupy the result of findNode.
volumeType getVolumeType (const point &) const
Determine type (inside/outside/mixed) for point. unknown if.
template<class CompareOp >
void findNear (const scalar nearDist, const dynamicIndexedOctree< Type > &tree2, CompareOp &cop) const
Find near pairs and apply CompareOp to them.
bool insert (label startIndex, label endIndex)
Insert a new object into the tree.
bool insertIndex (const label nodIndex, const label index, label &nLevels)
bool remove (const label index)
Remove an object from the tree.
label removeIndex (const label nodIndex, const label index)
void print (prefixOSstream &, const bool printContents, const label) const
Print tree. Either print all indices (printContent = true) or.
bool write (Ostream &os) const
void writeTreeInfo () const
Static Public Member Functions
static scalar & perturbTol ()
Get the perturbation tolerance.
static bool isContent (const labelBits i)
static bool isEmpty (const labelBits i)
static bool isNode (const labelBits i)
static label getContent (const labelBits i)
static label getNode (const labelBits i)
static direction getOctant (const labelBits i)
static volumeType getSide (const vector &outsideNormal, const vector &vec)
Helper function to return the side. Returns outside if.
static bool overlaps (const point &bbMin, const point &bbMax, const scalar nearestDistSqr, const point &sample)
Helper: does bb intersect a sphere around sample? Or is any.
Friends
Ostream & operator (Ostream &, const dynamicIndexedOctree< Type > &)
Detailed Description
template<class Type>
class Foam::dynamicIndexedOctree< Type >
Non-pointer based hierarchical recursive searching. Storage is dynamic, so elements can be deleted.
Source files
dynamicIndexedOctree.H
dynamicIndexedOctree.C
Definition at line 55 of file dynamicIndexedOctree.H.
Constructor & Destructor Documentation
dynamicIndexedOctree (const Type & shapes, const treeBoundBox & bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
Definition at line 2306 of file dynamicIndexedOctree.C.
References insert().
Referenced by dynamicIndexedOctree< Type >::findNearest().
Member Function Documentation
Foam::scalar & perturbTol () static
Get the perturbation tolerance.
Definition at line 2342 of file dynamicIndexedOctree.C.
autoPtr<dynamicIndexedOctree<Type> > clone () const inline
Clone.
Definition at line 437 of file dynamicIndexedOctree.H.
const Type& shapes () const inline
Reference to shape.
Definition at line 451 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Type >::findNearest().
const List<node>& nodes () const inline
List of all nodes.
Definition at line 457 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Type >::findNearest().
const contentListList& contents () const inline
List of all contents (referenced by those nodes that are.
contents)
Definition at line 464 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Type >::findNearest(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::nodes().
const treeBoundBox& bb () const inline
Top bounding box.
Definition at line 470 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Type >::findNear().
static bool isContent (const labelBits i) inline static
Definition at line 483 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Type >::findNearest(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getContent().
static bool isEmpty (const labelBits i) inline static
Definition at line 488 of file dynamicIndexedOctree.H.
static bool isNode (const labelBits i) inline static
Definition at line 493 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Type >::findNearest(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getNode().
static label getContent (const labelBits i) inline static
Definition at line 498 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Type >::findNearest().
static label getNode (const labelBits i) inline static
Definition at line 508 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Type >::findNearest().
static direction getOctant (const labelBits i) inline static
Definition at line 518 of file dynamicIndexedOctree.H.
Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Calculate nearest point on nearest shape.
Returns
bool : any point found nearer than nearestDistSqr
label: index in shapes
point: actual nearest point found
Definition at line 2350 of file dynamicIndexedOctree.C.
void findNearest (const label nodeI, const point & sample, scalar & nearestDistSqr, label & nearestShapeI, point & nearestPoint) const
Low level: calculate nearest starting from subnode.
Definition at line 488 of file dynamicIndexedOctree.C.
References Foam::abort(), dynamicIndexedOctree< Type >::node::bb_, line< Point, PointRef >::centre(), treeBoundBox::contains(), dynamicIndexedOctree< Type >::contents(), dynamicIndexedOctree< Type >::dynamicIndexedOctree(), Foam::constant::electromagnetic::e, Foam::endl(), treeBoundBox::faceBits(), Foam::facePoint(), Foam::FatalError, FatalErrorInFunction, forAll, dynamicIndexedOctree< Type >::getContent(), dynamicIndexedOctree< Type >::getNode(), PointIndexHit< Point >::hit(), HashSet< Key, Hash >::insert(), treeBoundBox::intersects(), dynamicIndexedOctree< Type >::isContent(), dynamicIndexedOctree< Type >::isNode(), Foam::ln(), Foam::mag(), boundBox::max(), boundBox::min(), OFstream::name(), Foam::name(), Foam::nl, dynamicIndexedOctree< Type >::nodes(), boundBox::overlaps(), treeBoundBox::points(), treeBoundBox::posBits(), Foam::Pout, PointIndexHit< Point >::rawPoint(), s(), treeBoundBox::searchOrder(), PointIndexHit< Point >::setHit(), PointIndexHit< Point >::setIndex(), PointIndexHit< Point >::setPoint(), dynamicIndexedOctree< Type >::shapes(), List< T >::size(), boundBox::span(), treeBoundBox::subBbox(), dynamicIndexedOctree< Type >::node::subNodes_, WarningInFunction, Vector< Cmpt >::x(), Y, Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Find nearest to line.
Returns
bool : any point found?
label: index in shapes
point: actual nearest point found sets:
linePoint : corresponding nearest point on line
Definition at line 2378 of file dynamicIndexedOctree.C.
Foam::pointIndexHit findLine (const point & start, const point & end) const
Find nearest intersection of line between start and end.
Definition at line 2412 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::findLineAny().
Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Find any intersection of line between start and end.
Definition at line 2424 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Type >::findLine(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
Foam::labelList findBox (const treeBoundBox & bb) const
Find (in no particular order) indices of all shapes inside or.
overlapping bounding box (i.e. all shapes not outside box)
Definition at line 2435 of file dynamicIndexedOctree.C.
References HashTable< T, Key, Hash >::toc().
Foam::labelList findSphere (const point & centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
overlapping a bounding sphere (i.e. all shapes not outside sphere)
Definition at line 2453 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::findNode(), and HashTable< T, Key, Hash >::toc().
Foam::labelBits findNode (const label nodeI, const point & sample) const
Find deepest node (as parent+octant) containing point. Starts.
off from starting index in nodes_ (use 0 to start from top) Use getNode and getOctant to extract info, or call findIndices.
Definition at line 2473 of file dynamicIndexedOctree.C.
References Foam::abort(), dynamicIndexedOctree< Type >::node::bb_, treeBoundBox::contains(), Foam::FatalError, FatalErrorInFunction, dynamicIndexedOctree< Type >::findInside(), dynamicIndexedOctree< Type >::node::subNodes_, and treeBoundBox::subOctant().
Referenced by dynamicIndexedOctree< Type >::findSphere(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
Foam::label findInside (const point & sample) const
Find shape containing point. Only implemented for certain.
shapes.
Definition at line 2520 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::findIndices(), forAll, and dynamicIndexedOctree< Type >::node::subNodes_.
Referenced by dynamicIndexedOctree< Type >::findNode(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
const Foam::labelList & findIndices (const point & sample) const
Find the shape indices that occupy the result of findNode.
Definition at line 2552 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::node::subNodes_.
Referenced by dynamicIndexedOctree< Type >::findInside(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
Foam::volumeType getVolumeType (const point & sample) const
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Definition at line 2577 of file dynamicIndexedOctree.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, and Foam::type().
Foam::volumeType getSide (const vector & outsideNormal, const vector & vec) static
Helper function to return the side. Returns outside if.
outsideNormal&vec >= 0, inside otherwise
Definition at line 464 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), and dynamicIndexedOctree< Type >::overlaps().
bool overlaps (const point & bbMin, const point & bbMax, const scalar nearestDistSqr, const point & sample) static
Helper: does bb intersect a sphere around sample? Or is any.
corner point of bb closer than nearestDistSqr to sample.
Definition at line 43 of file dynamicIndexedOctree.C.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), dynamicIndexedOctree< Type >::node::bb_, Foam::divide(), Foam::FatalError, FatalErrorInFunction, forAll, dynamicIndexedOctree< Type >::getSide(), Foam::mag(), boundBox::max(), Foam::max(), boundBox::midpoint(), boundBox::min(), Foam::min(), Foam::nl, dynamicIndexedOctree< Type >::node::parent_, List< T >::size(), treeBoundBox::subBbox(), dynamicIndexedOctree< Type >::node::subNodes_, treeBoundBox::subOctant(), Foam::type(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
void findNear (const scalar nearDist, const dynamicIndexedOctree< Type > & tree2, CompareOp & cop) const
Find near pairs and apply CompareOp to them.
tree2 can be *this or different tree.
Definition at line 2647 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::bb().
bool insert (label startIndex, label endIndex)
Insert a new object into the tree.
Definition at line 2669 of file dynamicIndexedOctree.C.
References Foam::divide(), dynamicIndexedOctree< Type >::insertIndex(), Foam::max(), and success.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
bool insertIndex (const label nodIndex, const label index, label & nLevels)
Definition at line 2716 of file dynamicIndexedOctree.C.
References treeBoundBox::subBbox().
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), and dynamicIndexedOctree< Type >::insert().
bool remove (const label index)
Remove an object from the tree.
Definition at line 2792 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::removeIndex().
Foam::label removeIndex (const label nodIndex, const label index)
Definition at line 2807 of file dynamicIndexedOctree.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), forAll, dynamicIndexedOctree< Type >::print(), List< T >::size(), treeBoundBox::subBbox(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer().
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), and dynamicIndexedOctree< Type >::remove().
void print (prefixOSstream & os, const bool printContents, const label nodeI) const
Print tree. Either print all indices (printContent = true) or.
just size of contents nodes.
Definition at line 2891 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::node::bb_, Foam::endl(), forAll, Foam::nl, dynamicIndexedOctree< Type >::node::parent_, prefixOSstream::prefix(), List< T >::size(), treeBoundBox::subBbox(), dynamicIndexedOctree< Type >::node::subNodes_, and Foam::meshTools::writeOBJ().
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), and dynamicIndexedOctree< Type >::removeIndex().
bool write (Ostream & os) const
Definition at line 2990 of file dynamicIndexedOctree.C.
References Foam::endl(), forAll, and IOstream::good().
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
void writeTreeInfo () const
Definition at line 2963 of file dynamicIndexedOctree.C.
References Foam::endl(), forAll, Foam::nl, and Foam::Pout.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant().
Friends And Related Function Documentation
Ostream& operator (Ostream & , const dynamicIndexedOctree< Type > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicIndexedOctree.H
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicIndexedOctree.C