OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
extendedCellToFaceStencil Class Reference
Calculates/constains the extended cell-to-face stencil.
Public Member Functions
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type > > &stencilFld)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Static Public Member Functions
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T > > &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar > > &stencilWeights)
Sum vol field contributions to create face values.
Static Protected Member Functions
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Write some statistics about stencil.
Protected Attributes
const polyMesh & mesh_
Detailed Description
Calculates/constains the extended cell-to-face stencil.
The stencil is a list of indices into either cells or boundary faces in a compact way. (element 0 is owner, 1 is neighbour). The index numbering is
cells first
then all (non-empty patch) boundary faces
When used in evaluation is a two stage process:
collect the data (cell data and non-empty boundaries) into a single field
(parallel) distribute the field
sum the weights*field.
Source files
extendedCellToFaceStencil.H
extendedCellToFaceStencil.C
extendedCellToFaceStencilTemplates.C
Definition at line 65 of file extendedCellToFaceStencil.H.
Constructor & Destructor Documentation
extendedCellToFaceStencil (const polyMesh & mesh) explicit
Construct from mesh.
Definition at line 100 of file extendedCellToFaceStencil.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, patchIdentifier::name(), coupledPolyPatch::parallel(), patches, and coupledPolyPatch::separated().
Member Function Documentation
void writeStencilStats (Ostream & os, const labelListList & stencil, const mapDistribute & map) static protected
Write some statistics about stencil.
Definition at line 42 of file extendedCellToFaceStencil.C.
References Foam::endl(), forAll, i, Foam::labelMax, Foam::labelMin, Foam::max(), Foam::min(), Foam::nl, reduce(), Foam::returnReduce(), List< T >::size(), and mapDistribute::subMap().
Referenced by centredCECCellToFaceStencilObject::centredCECCellToFaceStencilObject(), centredCFCCellToFaceStencilObject::centredCFCCellToFaceStencilObject(), centredCPCCellToFaceStencilObject::centredCPCCellToFaceStencilObject(), centredFECCellToFaceStencilObject::centredFECCellToFaceStencilObject(), pureUpwindCFCCellToFaceStencilObject::pureUpwindCFCCellToFaceStencilObject(), upwindCECCellToFaceStencilObject::upwindCECCellToFaceStencilObject(), upwindCFCCellToFaceStencilObject::upwindCFCCellToFaceStencilObject(), upwindCPCCellToFaceStencilObject::upwindCPCCellToFaceStencilObject(), and upwindFECCellToFaceStencilObject::upwindFECCellToFaceStencilObject().
ClassName ("extendedCellToFaceStencil")
static void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< T, fvPatchField, volMesh > & fld, List< List< T > > & stencilFld) static
Use map to get the data into stencil order.
Referenced by extendedCentredCellToFaceStencil::collectData(), and extendedCentredCellToCellStencil::collectData().
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar > > & stencilWeights) static
Sum vol field contributions to create face values.
Referenced by extendedCentredCellToFaceStencil::weightedSum().
void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, List< List< Type > > & stencilFld)
Definition at line 32 of file extendedCellToFaceStencilTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mapDistribute::constructSize(), mapDistribute::distribute(), forAll, i, DimensionedField< Type, GeoMesh >::mesh(), fvPatchField< Type >::patch(), List< T >::setSize(), and List< T >::size().
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar > > & stencilWeights)
Definition at line 86 of file extendedCellToFaceStencilTemplates.C.
References fvsPatchField< Type >::coupled(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, i, j, mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), primitiveMesh::nInternalFaces(), fvsPatchField< Type >::patch(), patchi, sf(), fvMesh::time(), and Time::timeName().
Member Data Documentation
const polyMesh& mesh_ protected
Definition at line 71 of file extendedCellToFaceStencil.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCellToFaceStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCellToFaceStencil.C
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCellToFaceStencilTemplates.C