OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
effectivenessHeatExchangerSource Class Reference
Heat exchanger source model, in which the heat exchanger is defined as a selection of cells.
Public Member Functions
TypeName ("effectivenessHeatExchangerSource")
Runtime type information.
effectivenessHeatExchangerSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~effectivenessHeatExchangerSource ()
Destructor.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual bool read (const dictionary &dict)
Read dictionary.
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
Runtime type information.
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~cellSetOption ()
Destructor.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const labelList & cells () const
Return const access to the cell set.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
Switch & active ()
Return access to the source active flag.
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldI)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldI)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldI)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Protected Attributes
scalar secondaryMassFlowRate_
Secondary flow mass rate [kg/s].
scalar secondaryInletT_
Inlet secondary temperature [K].
scalar primaryInletT_
Primary air temperature at the heat exchanger inlet [K].
autoPtr< interpolation2DTable< scalar > > eTable_
2D look up table efficiency = function of primary and secondary
word UName_
Name of velocity field; default = U.
word TName_
Name of temperature field; default = T.
word phiName_
Name of the flux.
word faceZoneName_
Name of the faceZone at the heat exchange inlet.
label zoneID_
Id for the face zone.
labelList faceId_
Local list of face IDs.
labelList facePatchId_
Local list of patch ID per face.
labelList faceSign_
List of +1/-1 representing face flip map (1 use as is, -1 negate)
scalar faceZoneArea_
Area of the face zone.
Protected Attributes inherited from cellSetOption
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType { smPoints, smCellSet, smCellZone, smAll }
Enumeration for selection mode types.
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Static Public Attributes inherited from cellSetOption
static const NamedEnum< selectionModeType, 4 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Detailed Description
Heat exchanger source model, in which the heat exchanger is defined as a selection of cells.
The total heat exchange source is given by:
where:
= total heat source
= effectivenes table
= net mass flux entering heat exchanger [kg/s]
= secondary mass flow rate [kg/s]
= primary inlet temperature [K]
= secondary inlet temperature [K]
= specific heat capacity [J/kg/K]
The distribution inside the hear exchanger is given by:
where:
= source for cell
= volume of the cell [m3]
= local cell velocity [m/s]
= local call temperature [K]
= min or max(T) in cell zone depending on the sign of Q_t [K]
Source usage
Example usage:
    effectivenessHeatExchangerSource1
    {
        type            effectivenessHeatExchangerSource;
        active          yes;
        effectivenessHeatExchangerSourceCoeffs
        {
            selectionMode   cellZone;
            cellZone        porosity;
            secondaryMassFlowRate   1.0;
            secondaryInletT         336;
            primaryInletT           293;
            faceZone                facesZoneInletOriented;
            outOfBounds             clamp;
            fileName                "effTable";
        }
    }
The effectiveness table is described in terms of the primary and secondary mass flow rates. For example, the table:
secondary MFR | 0.1 0.2 0.3 —–+—————– 0.02 | A B C primary MFR 0.04 | D E F 0.06 | G H I
Is specified by the following:
(0.02 ((0.1 A) (0.2 B) (0.3 C)), 0.04 ((0.1 D) (0.2 E) (0.3 F)), 0.06 ((0.1 G) (0.2 H) (0.3 I)));
Note
the table with name "fileName" should have the same units as the secondary mass flow rate and kg/s for phi
faceZone is the faces at the inlet of the cellzone, it needs to be created with flip map flags. It is used to integrate the net mass flow rate into the heat exchanger
Source files
effectivenessHeatExchangerSource.H
effectivenessHeatExchangerSource.C
Definition at line 199 of file effectivenessHeatExchangerSource.H.
Constructor & Destructor Documentation
effectivenessHeatExchangerSource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 147 of file effectivenessHeatExchangerSource.C.
References effectivenessHeatExchangerSource::addSup(), dictionaryName::dictName(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, basicThermo::he(), Foam::name(), IOobject::name(), Foam::nl, and Foam::type().
virtual ~effectivenessHeatExchangerSource () inline virtual
Destructor.
Definition at line 289 of file effectivenessHeatExchangerSource.H.
References effectivenessHeatExchangerSource::addSup().
Member Function Documentation
TypeName ("effectivenessHeatExchangerSource")
Runtime type information.
virtual void addSup (fvMatrix< scalar > & eqn, const label fieldI) inline virtual
Scalar.
Reimplemented from option.
Definition at line 299 of file effectivenessHeatExchangerSource.H.
References dict, NotImplemented, effectivenessHeatExchangerSource::read(), and rho.
Referenced by effectivenessHeatExchangerSource::effectivenessHeatExchangerSource(), and effectivenessHeatExchangerSource::~effectivenessHeatExchangerSource().
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldI) virtual
Scalar.
Reimplemented from option.
Definition at line 197 of file effectivenessHeatExchangerSource.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), basicThermo::Cp(), dictionaryName::dictName(), Foam::endl(), forAll, Foam::indent(), Foam::Info, Foam::fvc::interpolate(), Foam::mag(), UPstream::master(), Foam::max(), Foam::min(), Foam::nl, phi, Foam::reduce(), fvMatrix< Type >::source(), Foam::T(), and U.
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from cellSetOption.
Definition at line 297 of file effectivenessHeatExchangerSource.C.
References cellSetOption::read().
Referenced by effectivenessHeatExchangerSource::addSup().
Member Data Documentation
scalar secondaryMassFlowRate_ protected
Secondary flow mass rate [kg/s].
Definition at line 209 of file effectivenessHeatExchangerSource.H.
scalar secondaryInletT_ protected
Inlet secondary temperature [K].
Definition at line 212 of file effectivenessHeatExchangerSource.H.
scalar primaryInletT_ protected
Primary air temperature at the heat exchanger inlet [K].
Definition at line 215 of file effectivenessHeatExchangerSource.H.
autoPtr<interpolation2DTable<scalar> > eTable_ protected
2D look up table efficiency = function of primary and secondary
mass flow rates [kg/s]
Definition at line 219 of file effectivenessHeatExchangerSource.H.
word UName_ protected
Name of velocity field; default = U.
Definition at line 222 of file effectivenessHeatExchangerSource.H.
word TName_ protected
Name of temperature field; default = T.
Definition at line 225 of file effectivenessHeatExchangerSource.H.
word phiName_ protected
Name of the flux.
Definition at line 228 of file effectivenessHeatExchangerSource.H.
word faceZoneName_ protected
Name of the faceZone at the heat exchange inlet.
Definition at line 231 of file effectivenessHeatExchangerSource.H.
label zoneID_ protected
Id for the face zone.
Definition at line 234 of file effectivenessHeatExchangerSource.H.
labelList faceId_ protected
Local list of face IDs.
Definition at line 237 of file effectivenessHeatExchangerSource.H.
labelList facePatchId_ protected
Local list of patch ID per face.
Definition at line 240 of file effectivenessHeatExchangerSource.H.
labelList faceSign_ protected
List of +1/-1 representing face flip map (1 use as is, -1 negate)
Definition at line 243 of file effectivenessHeatExchangerSource.H.
scalar faceZoneArea_ protected
Area of the face zone.
Definition at line 246 of file effectivenessHeatExchangerSource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/effectivenessHeatExchangerSource/effectivenessHeatExchangerSource.H
src/fvOptions/sources/derived/effectivenessHeatExchangerSource/effectivenessHeatExchangerSource.C