OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ensightGeoFile Class Reference
Specialized Ensight output with extra geometry file header.
Public Member Functions
ensightGeoFile (const fileName &pathname, IOstream::streamFormat format=IOstream::BINARY)
Construct from pathname.
~ensightGeoFile ()
Destructor.
virtual Ostream & writeKeyword (const string &key)
Write keyword with trailing newline.
Public Member Functions inherited from ensightFile
ensightFile (const fileName &pathname, IOstream::streamFormat format=IOstream::BINARY)
Construct from pathname.
~ensightFile ()
Destructor.
virtual Ostream & write (const char *buf, std::streamsize count)
Binary write.
Ostream & writeBinaryHeader ()
Write "C Binary" for binary files (eg, geometry/measured)
Ostream & writeUndef ()
Write undef value.
Ostream & write (const char *value)
Write C-string as "%80s" or as binary.
Ostream & write (const string &value)
Write string as "%80s" or as binary.
Ostream & write (const label value)
Write integer as "%10d" or as binary.
Ostream & write (const label value, const label fieldWidth)
Write integer with specified width or as binary.
Ostream & write (const scalar value)
Write float as "%12.5e" or as binary.
void newline ()
Add carriage return to ascii stream.
Public Member Functions inherited from OFstream
ClassName ("OFstream")
OFstream (const fileName &pathname, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct from pathname.
~OFstream ()
Destructor.
const fileName & name () const
Return the name of the stream.
fileName & name ()
Return non-const access to the name of the stream.
virtual ostream & stdStream ()
Access to underlying std::ostream.
virtual const ostream & stdStream () const
Const access to underlying std::ostream.
void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from OSstream
OSstream (ostream &os, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
virtual Ostream & write (const token &)
Write next token to stream.
virtual Ostream & write (const char)
Write character.
virtual Ostream & write (const word &)
Write word.
virtual Ostream & writeQuoted (const std::string &, const bool quoted=true)
Write std::string surrounded by quotes.
virtual Ostream & write (const int32_t)
Write int32_t.
virtual Ostream & write (const int64_t)
Write int64_t.
virtual Ostream & write (const floatScalar)
Write floatScalar.
virtual Ostream & write (const doubleScalar)
Write doubleScalar.
virtual void indent ()
Add indentation characters.
virtual ios_base::fmtflags flags (const ios_base::fmtflags flags)
Set flags of output stream.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual int width () const
Get width of output field.
virtual int width (const int)
Set width of output field (and return old width)
virtual int precision () const
Get precision of output field.
virtual int precision (const int)
Set precision of output field (and return old precision)
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Ostream ()
Destructor.
virtual Ostream & write (const keyType &)
Write keyType.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Incrememt the indent level.
void decrIndent ()
Decrememt the indent level.
Ostream & writeKeyword (const keyType &)
Write the keyword followed by an appropriate indentation.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Member Functions inherited from ensightFile
static bool allowUndef ()
Return setting for whether 'undef' values are allowed in results.
static string mask ()
The '*' mask appropriate for subDir.
static string subDir (const label)
Consistent zero-padded numbers for subdirectories.
static void subDirWidth (const label)
Set width of subDir and mask. Default width is 8 digits.
static label subDirWidth ()
Return current width of subDir and mask.
static bool allowUndef (bool)
static scalar undefValue (const scalar)
Assign the value to represent undef in the results.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from Ostream
unsigned short indentLevel_
Current indent level.
Protected Attributes inherited from IOstream
label lineNumber_
Static Protected Attributes inherited from Ostream
static const unsigned short indentSize_ = 4
Number of spaces per indent level.
static const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Detailed Description
Specialized Ensight output with extra geometry file header.
Definition at line 45 of file ensightGeoFile.H.
Constructor & Destructor Documentation
ensightGeoFile (const fileName & pathname, IOstream::streamFormat format = IOstream::BINARY)
Construct from pathname.
Definition at line 31 of file ensightGeoFile.C.
References write().
~ensightGeoFile ()
Destructor.
Definition at line 47 of file ensightGeoFile.C.
Member Function Documentation
Foam::Ostream & writeKeyword (const string & key) virtual
Write keyword with trailing newline.
Reimplemented from ensightFile.
Definition at line 53 of file ensightGeoFile.C.
References ensightFile::newline(), and ensightFile::write().
Referenced by ensightPartFaces::writeConnectivity(), ensightPart::writeGeometry(), and ensightPartCells::~ensightPartCells().
The documentation for this class was generated from the following files:
src/conversion/ensight/file/ensightGeoFile.H
src/conversion/ensight/file/ensightGeoFile.C