OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
entry Class Reference abstract
A keyword and a list of tokens is an 'entry'.
Public Member Functions
entry (const keyType &)
Construct from keyword.
entry (const entry &)
Construct as copy.
virtual autoPtr< entry > clone (const dictionary &parentDict) const =0
Construct on freestore as copy with reference to the.
virtual autoPtr< entry > clone () const
Construct on freestore as copy.
virtual ~entry ()
Destructor.
const keyType & keyword () const
Return keyword.
keyType & keyword ()
Return non-const access to keyword.
virtual const fileName & name () const =0
Return the dictionary name.
virtual fileName & name ()=0
Return the dictionary name.
virtual label startLineNumber () const =0
Return line number of first token in dictionary.
virtual label endLineNumber () const =0
Return line number of last token in dictionary.
virtual bool isStream () const
Return true if this entry is a stream.
virtual ITstream & stream () const =0
Return token stream if this entry is a primitive entry.
virtual bool isDict () const
Return true if this entry is a dictionary.
virtual const dictionary & dict () const =0
Return dictionary if this entry is a dictionary.
virtual dictionary & dict ()=0
Return non-const access to dictionary if this entry is a dictionary.
virtual void write (Ostream &) const =0
Write.
void operator= (const entry &)
bool operator== (const entry &) const
bool operator!= (const entry &) const
Public Member Functions inherited from DLListBase::link
link ()
Null construct.
bool registered () const
Check if the link is registered with the DLListBase.
void deregister ()
Deregister the link after removal.
Static Public Member Functions
static bool New (dictionary &parentDict, Istream &)
Construct from Istream and insert into dictionary.
static autoPtr< entry > New (Istream &is)
Construct on freestore from Istream and return.
Static Public Attributes
static int disableFunctionEntries
Friends
Ostream & operator<< (Ostream &, const entry &)
Additional Inherited Members
Public Attributes inherited from DLListBase::link
link * prev_
Pointer to next entry in list.
link * next_
Detailed Description
A keyword and a list of tokens is an 'entry'.
An entry can be read, written and printed, and the types and values of its tokens analysed. An entry is a high-level building block for data description. It is a front-end for the token parser. A list of entries can be used as a set of keyword syntax elements, for example.
Source files
entry.H
entry.C
entryIO.C
Definition at line 65 of file entry.H.
Constructor & Destructor Documentation
entry (const keyType & keyword)
Construct from keyword.
Definition at line 40 of file entry.C.
entry (const entry & e)
Construct as copy.
Definition at line 47 of file entry.C.
virtual ~entry () inline virtual
Destructor.
Definition at line 113 of file entry.H.
Member Function Documentation
virtual autoPtr<entry> clone (const dictionary & parentDict) const pure virtual
Construct on freestore as copy with reference to the.
dictionary the copy belongs to
Implemented in primitiveEntry, and dictionaryEntry.
Referenced by dictionary::add(), and dictionary::set().
Foam::autoPtr< Foam::entry > clone () const virtual
Construct on freestore as copy.
Note: the parent directory is set to dictionary::null
Definition at line 54 of file entry.C.
References dictionary::null.
bool New (dictionary & parentDict, Istream & is) static
Construct from Istream and insert into dictionary.
Definition at line 91 of file entryIO.C.
References dictionary::add(), token::BEGIN_BLOCK, dictionary::clear(), entry::dict(), inputModeEntry::error(), functionEntry::execute(), includeEntry::execute(), Foam::exit(), IOstream::fatalCheck(), Foam::FatalIOError, FatalIOErrorIn, Foam::stringOps::inplaceExpand(), entry::isDict(), dictionary::lookupEntryPtr(), dictionary::lookupScopedEntryPtr(), inputModeEntry::merge(), inputModeEntry::overwrite(), inputModeEntry::protect(), Istream::putBack(), s(), and dictionary::substituteScopedKeyword().
Referenced by dictionary::read().
Foam::autoPtr< Foam::entry > New (Istream & is) static
Construct on freestore from Istream and return.
Definition at line 264 of file entryIO.C.
References token::BEGIN_BLOCK, IOstream::fatalCheck(), dictionary::null, and Istream::putBack().
const keyType& keyword () const inline
Return keyword.
Definition at line 120 of file entry.H.
Referenced by dictionary::add(), cellModel::cellModel(), fieldAverageItem::fieldAverageItem(), phase::iNew::operator()(), phaseModel::iNew::operator()(), Foam::operator<<(), Foam::operator>>(), phaseProperties::phaseProperties(), primitiveEntry::primitiveEntry(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), refinementSurfaces::refinementSurfaces(), dictionary::set(), shellSurfaces::shellSurfaces(), and dictionaryEntry::write().
keyType& keyword () inline
Return non-const access to keyword.
Definition at line 126 of file entry.H.
virtual const fileName& name () const pure virtual
Return the dictionary name.
Implemented in primitiveEntry, and dictionaryEntry.
Referenced by dictionary::add().
virtual fileName& name () pure virtual
Return the dictionary name.
Implemented in primitiveEntry, and dictionaryEntry.
virtual label startLineNumber () const pure virtual
Return line number of first token in dictionary.
Implemented in primitiveEntry, and dictionaryEntry.
Referenced by dynamicCodeContext::dynamicCodeContext(), codedFunctionObject::read(), CodedSource< Type >::read(), and dictionaryEntry::startLineNumber().
virtual label endLineNumber () const pure virtual
Return line number of last token in dictionary.
Implemented in primitiveEntry, and dictionaryEntry.
virtual bool isStream () const inline virtual
Return true if this entry is a stream.
Reimplemented in primitiveEntry.
Definition at line 144 of file entry.H.
virtual ITstream& stream () const pure virtual
Return token stream if this entry is a primitive entry.
Implemented in primitiveEntry, and dictionaryEntry.
Referenced by coordinateSystem::coordinateSystem(), dynamicCodeContext::dynamicCodeContext(), lduMatrix::smoother::getName(), lduMatrix::preconditioner::getName(), dictionary::lookupOrAddDefault(), dictionary::lookupOrDefault(), lduMatrix::smoother::New(), lduMatrix::preconditioner::New(), functionObjectList::read(), codedFunctionObject::read(), CodedSource< Type >::read(), dictionary::readIfPresent(), and solution::upgradeSolverDict().
virtual bool isDict () const inline virtual
Return true if this entry is a dictionary.
Reimplemented in dictionaryEntry.
Definition at line 153 of file entry.H.
Referenced by dictionary::add(), coordinateSystem::coordinateSystem(), lduMatrix::smoother::getName(), lduMatrix::preconditioner::getName(), dictionary::isDict(), dictionary::lookupScopedEntryPtr(), entry::New(), lduMatrix::smoother::New(), lduMatrix::preconditioner::New(), functionObjectList::read(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), dictionary::set(), Foam::debug::switchSet(), and solution::upgradeSolverDict().
virtual const dictionary& dict () const pure virtual
Return dictionary if this entry is a dictionary.
Implemented in primitiveEntry, and dictionaryEntry.
Referenced by dictionary::add(), lduMatrix::smoother::getName(), lduMatrix::preconditioner::getName(), dictionary::lookupScopedEntryPtr(), entry::New(), lduMatrix::smoother::New(), lduMatrix::preconditioner::New(), functionObjectList::read(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), refinementSurfaces::refinementSurfaces(), dictionary::set(), shellSurfaces::shellSurfaces(), dictionary::subDict(), dictionary::subDictPtr(), dictionary::subOrEmptyDict(), and Foam::debug::switchSet().
virtual dictionary& dict () pure virtual
Return non-const access to dictionary if this entry is a dictionary.
Implemented in primitiveEntry, and dictionaryEntry.
virtual void write (Ostream &) const pure virtual
Write.
Implemented in primitiveEntry, and dictionaryEntry.
Referenced by Foam::operator<<().
void operator= (const entry & e)
Definition at line 62 of file entry.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
bool operator== (const entry & e) const
Definition at line 76 of file entry.C.
References Foam::e, and OStringStream::str().
bool operator!= (const entry & e) const
Definition at line 95 of file entry.C.
References Foam::operator==().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const entry &) friend
Member Data Documentation
int disableFunctionEntries static
Definition at line 83 of file entry.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/entry/entry.H
src/OpenFOAM/db/dictionary/entry/entry.C
src/OpenFOAM/db/dictionary/entry/entryIO.C