OpenFOAM: edgeMeshFormat Class Reference
edgeMeshFormat Class Reference
Provide a means of reading/writing the single-file OpenFOAM edge format.
Public Member Functions
edgeMeshFormat (const fileName &)
Construct from file name.
virtual ~edgeMeshFormat ()
Destructor.
virtual bool read (const fileName &)
Read from file.
virtual void write (const fileName &name) const
Write object.
Public Member Functions inherited from edgeMesh
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const pointField &, const edgeList &)
Construct from components.
edgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges).
edgeMesh (const edgeMesh &)
Construct as copy.
edgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
edgeMesh (Istream &)
Construct from Istream.
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< edgeMesh > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void clear ()
Clear all storage.
virtual void reset (const Xfer< pointField > &points, const Xfer< edgeList > &edges)
Reset primitive data (points, edges)
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
void mergeEdges ()
Merge similar edges.
virtual void writeStats (Ostream &) const
void operator= (const edgeMesh &)
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Static Public Member Functions
static autoPtr< edgeMesh > New (const fileName &name)
Read file and return edgeMesh.
static bool read (Istream &, pointField &, edgeList &)
Read edgeMesh components from stream.
static Ostream & write (Ostream &, const pointField &, const edgeList &)
Write edgeMesh components to stream.
static void write (const fileName &, const edgeMesh &)
Write edgeMesh with a mimicked IOobject header.
Static Public Member Functions inherited from edgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const edgeMesh &)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Static Protected Member Functions
static void writeHeader (Ostream &, const pointField &, const edgeList &)
Write header information.
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (IFstream &)
Read non-comment line.
Additional Inherited Members
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Detailed Description
Provide a means of reading/writing the single-file OpenFOAM edge format.
Note
This class provides more methods than the regular edge format interface.
Source files
edgeMeshFormat.H
edgeMeshFormat.C
Definition at line 55 of file edgeMeshFormat.H.
Constructor & Destructor Documentation
edgeMeshFormat (const fileName & filename)
Construct from file name.
Definition at line 36 of file edgeMeshFormat.C.
References Foam::read(), and edgeMeshFormat::read().
virtual ~edgeMeshFormat () inline virtual
Destructor.
Definition at line 102 of file edgeMeshFormat.H.
References edgeMeshFormat::read(), and edgeMeshFormat::write().
Member Function Documentation
static void writeHeader (Ostream & , const pointField & , const edgeList &) static protected
Write header information.
static autoPtr<edgeMesh> New (const fileName & name) inline static
Read file and return edgeMesh.
Definition at line 92 of file edgeMeshFormat.H.
bool read (Istream & is, pointField & pointLst, edgeList & edgeLst) static
Read edgeMesh components from stream.
Definition at line 104 of file edgeMeshFormat.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), and edgeMeshFormat::write().
Referenced by edgeMeshFormat::edgeMeshFormat(), Foam::operator>>(), edgeMeshFormat::read(), and edgeMeshFormat::~edgeMeshFormat().
Foam::Ostream & write (Ostream & os, const pointField & pointLst, const edgeList & edgeLst) static
Write edgeMesh components to stream.
Definition at line 128 of file edgeMeshFormat.C.
References IOstream::check(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), IOstream::name(), and Foam::nl.
Referenced by Foam::operator<<(), edgeMeshFormat::read(), edgeMeshFormat::write(), and edgeMeshFormat::~edgeMeshFormat().
void write (const fileName & filename, const edgeMesh & mesh) static
Write edgeMesh with a mimicked IOobject header.
Definition at line 158 of file edgeMeshFormat.C.
References IOstream::check(), edgeMesh::edges(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOobject::note(), edgeMesh::points(), write(), and IOobject::writeHeader().
bool read (const fileName & filename) virtual
Read from file.
Reimplemented from edgeMesh.
Definition at line 47 of file edgeMeshFormat.C.
References clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobject::filePath(), IOobject::headerOk(), fileName::name(), fileName::path(), Foam::read(), edgeMeshFormat::read(), and IOobject::readHeader().
virtual void write (const fileName & name) const inline virtual
Write object.
Reimplemented from edgeMesh.
Definition at line 131 of file edgeMeshFormat.H.
References edgeMeshFormat::write().
The documentation for this class was generated from the following files:
src/edgeMesh/edgeMeshFormats/edgeMesh/edgeMeshFormat.H
src/edgeMesh/edgeMeshFormats/edgeMesh/edgeMeshFormat.C