OpenFOAM: DynamicList< T, SizeInc, SizeMult, SizeDiv > Class Template Reference
DynamicList< T, SizeInc, SizeMult, SizeDiv > Class Template Reference
A 1D vector of objects of type <T> that resizes itself as necessary to accept the new objects.
Public Member Functions
DynamicList ()
Construct null.
DynamicList (const label)
Construct given size.
DynamicList (const label, const T &)
Construct with given size and value for all elements.
DynamicList (const DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Construct copy.
DynamicList (const UList< T > &)
Construct from UList. Size set to UList size.
DynamicList (const UIndirectList< T > &)
Construct from UIndirectList. Size set to UIndirectList size.
DynamicList (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
DynamicList (Istream &)
Construct from Istream. Size set to size of list read.
label capacity () const
Size of the underlying storage.
void setCapacity (const label)
Alter the size of the underlying storage.
void setSize (const label)
Alter the addressed list size.
void setSize (const label, const T &)
Alter the addressed list size and fill new space with a.
void resize (const label)
Alter the addressed list size.
void resize (const label, const T &)
Alter the addressed list size and fill new space with a.
void reserve (const label)
Reserve allocation space for at least this size.
void clear ()
Clear the addressed list, i.e. set the size to zero.
void clearStorage ()
Clear the list and delete storage.
DynamicList< T, SizeInc, SizeMult, SizeDiv > & shrink ()
Shrink the allocated space to the number of elements used.
void transfer (List< T > &)
Transfer contents of the argument List into this.
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer contents of the argument DynamicList into this.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container as a plain List.
DynamicList< T, SizeInc, SizeMult, SizeDiv > & append (const T &)
Append an element at the end of the list.
DynamicList< T, SizeInc, SizeMult, SizeDiv > & append (const UList< T > &)
Append a List at the end of this list.
DynamicList< T, SizeInc, SizeMult, SizeDiv > & append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
T remove ()
Remove and return the top element.
T & operator() (const label)
Return non-const access to an element, resizing list if.
void operator= (const T &)
Assignment of all addressed entries to the given value.
void operator= (const DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Assignment from DynamicList.
void operator= (const UList< T > &)
Assignment from UList.
void operator= (const UIndirectList< T > &)
Assignment from UIndirectList.
UList< T >::iterator erase (typename UList< T >::iterator)
Erase an element, move the remaining elements to fill the gap.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Friends
class List< T >
Declare friendship with the List class.
Ostream & operator (Ostream &, const DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Istream & operator>> (Istream &, DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Read from Istream, discarding contents of existing DynamicList.
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class T, unsigned SizeInc = 0, unsigned SizeMult = 2, unsigned SizeDiv = 1>
class Foam::DynamicList< T, SizeInc, SizeMult, SizeDiv >
A 1D vector of objects of type <T> that resizes itself as necessary to accept the new objects.
Internal storage is a compact array and the list can be shrunk to compact storage. The increase of list size is controlled by three template parameters, which allows the list storage to either increase by the given increment or by the given multiplier and divider (allowing non-integer multiples).
Source files
DynamicList.H
DynamicListI.H
DynamicList.C
Definition at line 56 of file DynamicList.H.
Constructor & Destructor Documentation
DynamicList () inline
Construct null.
Definition at line 29 of file DynamicListI.H.
Referenced by DynamicList< T, SizeInc, SizeMult, SizeDiv >::DynamicList().
DynamicList (const label nElem) inline explicit
Construct given size.
Definition at line 37 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::DynamicList(), and List< T >::size().
DynamicList (const label nElem, const T & a) inline
Construct with given size and value for all elements.
Definition at line 51 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::DynamicList().
DynamicList (const DynamicList< T, SizeInc, SizeMult, SizeDiv > & lst) inline
Construct copy.
Definition at line 63 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::DynamicList().
DynamicList (const UList< T > & lst) inline explicit
Construct from UList. Size set to UList size.
Also constructs from DynamicList with different sizing parameters.
Definition at line 74 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::DynamicList().
DynamicList (const UIndirectList< T > & lst) inline explicit
Construct from UIndirectList. Size set to UIndirectList size.
Definition at line 85 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::DynamicList().
DynamicList (const Xfer< List< T >> & lst) inline explicit
Construct by transferring the parameter contents.
Definition at line 96 of file DynamicListI.H.
DynamicList (Istream & is) explicit
Construct from Istream. Size set to size of list read.
Definition at line 32 of file DynamicList.C.
Member Function Documentation
Foam::label capacity () const inline
Size of the underlying storage.
Definition at line 109 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity().
Referenced by primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), primitiveMesh::faceEdges(), and primitiveMesh::pointPoints().
void setCapacity (const label nElem) inline
Alter the size of the underlying storage.
The addressed size will be truncated if needed to fit, but will remain otherwise untouched. Use this or reserve() in combination with append().
Definition at line 118 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::reserve(), List< T >::setSize(), and List< T >::size().
Referenced by polyTopoChange::addMesh(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::capacity(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), mapDistributeBase::distribute(), mapDistribute::distribute(), primitiveMesh::faceEdges(), fileMonitorWatcher::fileMonitorWatcher(), polyBoundaryMesh::findIndices(), primitiveMesh::pointPoints(), Pstream::Pstream(), snappySnapDriver::repatchToSurface(), surfaceFeatures::selectFeatureEdges(), polyTopoChange::setCapacity(), PatchTools::sortedPointEdges(), extendedEdgeMesh::sortPointsAndEdges(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
void setSize (const label nElem) inline
Alter the addressed list size.
New space will be allocated if required. Use this to resize the list prior to using the operator[] for setting values (as per List usage).
Definition at line 163 of file DynamicListI.H.
References Foam::max(), List< T >::setSize(), and List< T >::size().
Referenced by fileMonitor::addWatch(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::erase(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::operator()(), primitiveMesh::pointCells(), OBJedgeFormat::read(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::reserve(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::resize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), face::triangles(), streamLine::write(), and wallBoundedStreamLine::write().
void setSize (const label nElem, const T & t) inline
Alter the addressed list size and fill new space with a.
constant.
Definition at line 186 of file DynamicListI.H.
References UList< T >::operator[](), DynamicList< T, SizeInc, SizeMult, SizeDiv >::resize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), and List< T >::size().
void resize (const label nElem) inline
Alter the addressed list size.
New space will be allocated if required. Use this to resize the list prior to using the operator[] for setting values (as per List usage).
Definition at line 204 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize().
Referenced by minEqOpFace::operator()(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize().
void resize (const label nElem, const T & t) inline
Alter the addressed list size and fill new space with a.
constant.
Definition at line 214 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize().
void reserve (const label nElem) inline
Reserve allocation space for at least this size.
Never shrinks the allocated size, use setCapacity() for that.
Definition at line 140 of file DynamicListI.H.
References Foam::max(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::setSize(), and List< T >::size().
Referenced by PointEdgeWave< Type, TrackingData >::countPatchType(), STARCDsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity().
void clear () inline
Clear the addressed list, i.e. set the size to zero.
Allocated size does not change
Definition at line 224 of file DynamicListI.H.
References List< T >::size().
Referenced by Foam::bandCompression(), createShellMesh::calcPointRegions(), mapNearestAMI< SourcePatch, TargetPatch >::calculate(), cellVolumeWeightMethod::calculateAddressing(), mapNearestMethod::calculateAddressing(), primitiveMesh::cellCells(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), edgeCollapser::checkMeshQuality(), probes::clearFieldGroups(), PointEdgeWave< Type, TrackingData >::countPatchType(), primitiveMesh::edgeCells(), primitiveMesh::edgeFaces(), primitiveMesh::faceEdges(), triSurfaceSearch::findLineAll(), searchableBox::findLineAll(), particle< Type >::findTris(), isoSurface::generateFaceTriPoints(), indexedOctree< Type >::indexedOctree(), OBJedgeFormat::OBJedgeFormat(), listPlusEqOp< T >::operator()(), primitiveMesh::pointCells(), primitiveMesh::pointPoints(), faceAreaWeightAMI< SourcePatch, TargetPatch >::processSourceFace(), STARCDsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), STARCDCore::readPoints(), snappySnapDriver::repatchToSurface(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), hexRef8::setInstance(), Reaction< ReactionThermo >::setLRhs(), PatchTools::sortedPointEdges(), and patchInjectionBase::updateMesh().
void clearStorage () inline
Clear the list and delete storage.
Definition at line 231 of file DynamicListI.H.
References List< T >::clear().
Referenced by polyTopoChange::changeMesh(), polyTopoChange::clear(), refinementHistory::compact(), polyTopoChange::makeMesh(), Foam::operator>>(), NASedgeFormat::read(), NASsurfaceFormat< Face >::read(), List< T >::transfer(), and UIPstream::~UIPstream().
Foam::DynamicList< T, SizeInc, SizeMult, SizeDiv > & shrink () inline
Shrink the allocated space to the number of elements used.
Returns a reference to the DynamicList.
Definition at line 240 of file DynamicListI.H.
References List< T >::setSize(), and List< T >::size().
Referenced by refinementHistory::clone(), geomCellLooper::cut(), refinementHistory::distribute(), mapDistributeBase::distribute(), mapDistribute::distribute(), isoSurface::generateFaceTriPoints(), boundaryMesh::getNearest(), indexedOctree< Type >::indexedOctree(), meshSearch::intersections(), isoSurfaceCell::isoSurfaceCell(), NamedEnum< Enum, nEnum >::names(), cellCuts::nonAnchorPoints(), Foam::parseNASCoord(), ProcessorTopology< Container, ProcPatch >::ProcessorTopology(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), Foam::readUpto(), searchableSurfaceCollection::regions(), surfaceFeatures::selectFeatureEdges(), dynamicRefineFvMesh::selectRefineCells(), Reaction< ReactionThermo >::setLRhs(), List< T >::transfer(), triSurfaceTools::triangulate(), and triSurfaceTools::triangulateFaceCentre().
void transfer (List< T > & lst) inline
Transfer contents of the argument List into this.
Definition at line 259 of file DynamicListI.H.
References List< T >::size(), and List< T >::transfer().
Referenced by curvatureSeparation::curvatureSeparation(), indexedOctree< Type >::overlaps(), ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel(), ReactingParcel< ParcelType >::ReactingParcel(), OBJsurfaceFormat< Face >::read(), dynamicIndexedOctree< Type >::removeIndex(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), streamLine::write(), and wallBoundedStreamLine::write().
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > & lst) inline
Transfer contents of the argument DynamicList into this.
Definition at line 270 of file DynamicListI.H.
References List< T >::transfer().
Foam::Xfer< Foam::List< T > > xfer () inline
Transfer contents to the Xfer container as a plain List.
Definition at line 283 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append().
Referenced by hexRef8::cellShapes(), polyTopoChange::changeMesh(), fileName::components(), polyTopoChange::makeMesh(), Foam::parseNASCoord(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), and Foam::readUpto().
Foam::DynamicList< T, SizeInc, SizeMult, SizeDiv > & append (const T & t) inline
Append an element at the end of the list.
Definition at line 292 of file DynamicListI.H.
References UList< T >::operator[](), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), and List< T >::size().
Referenced by isoSurface::adaptPatchFields(), polyTopoChange::addCell(), polyTopoChange::addFace(), polyTopoChange::addPoint(), cellZoneSet::addSet(), pointZoneSet::addSet(), faceZoneSet::addSet(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), probes::appendFieldGroup(), meshToMeshMethod::appendNbrCells(), AMIMethod< SourcePatch, TargetPatch >::appendNbrFaces(), directMethod::appendToDirectSeeds(), normalToFace::applyToSet(), setAndNormalToFaceZone::applyToSet(), Foam::bandCompression(), faceAreaWeightAMI< SourcePatch, TargetPatch >::calcAddressing(), mappedPatchBase::calcMapping(), createShellMesh::calcPointRegions(), directAMI< SourcePatch, TargetPatch >::calculate(), mapNearestAMI< SourcePatch, TargetPatch >::calculate(), viewFactor::calculate(), cellVolumeWeightMethod::calculateAddressing(), mapNearestMethod::calculateAddressing(), primitiveMesh::cellCells(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), polyMeshTetDecomposition::cellTetIndices(), edgeCollapser::checkMeshQuality(), refinementHistory::clone(), collectLibsCallback(), fileName::components(), patchPatchDist::correct(), PointEdgeWave< Type, TrackingData >::countPatchType(), forces::createFileNames(), geomCellLooper::cut(), refinementHistory::distribute(), primitiveMesh::edgeCells(), primitiveMesh::edgeFaces(), primitiveMesh::faceEdges(), hexRef8::faceLevel(), FacePostProcessing< CloudType >::FacePostProcessing(), polyBoundaryMesh::findIndices(), triSurfaceSearch::findLineAll(), searchableBox::findLineAll(), mapNearestMethod::findMappedSrcCell(), mapNearestMethod::findNearestCell(), particle< Type >::findTris(), FreeStream< CloudType >::FreeStream(), UPstream::freeTag(), isoSurface::generateFaceTriPoints(), removeCells::getExposedFaces(), boundaryMesh::getNearest(), indexedOctree< Type >::indexedOctree(), meshSearch::intersections(), rigidBodyModel::join_(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), polyBoundaryMesh::matchGroups(), conformalVoronoiMesh::maxSurfaceProtrusion(), meshRefinement::mergeBaffles(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), NamedEnum< Enum, nEnum >::names(), cellCuts::nonAnchorPoints(), OBJedgeFormat::OBJedgeFormat(), listPlusEqOp< T >::operator()(), minEqOp< labelPair >::operator()(), csvTableReader< Type >::operator()(), Foam::operator<<(), dynamicIndexedOctree< Type >::overlaps(), indexedOctree< Type >::overlaps(), Foam::parseNASCoord(), patchInteractionDataList::patchInteractionDataList(), primitiveMesh::pointCells(), primitiveMesh::pointPoints(), ProcessorTopology< Container, ProcPatch >::ProcessorTopology(), faceAreaWeightAMI< SourcePatch, TargetPatch >::processSourceFace(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJedgeFormat::read(), VTKsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), Foam::readUpto(), searchableSurfaceCollection::regions(), dynamicIndexedOctree< Type >::removeIndex(), fileMonitor::removeWatch(), snappySnapDriver::repatchToSurface(), dynamicCode::resolveTemplates(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), scalarRanges::scalarRanges(), surfaceFeatures::selectFeatureEdges(), dynamicRefineFvMesh::selectRefineCells(), boundaryMesh::setFeatureEdges(), surfaceFeatures::setFromStatus(), hexRef8::setInstance(), Reaction< ReactionThermo >::setLRhs(), faceCollapser::setRefinement(), boundaryCutter::setRefinement(), createShellMesh::setRefinement(), hexRef8::setRefinement(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), PatchTools::sortedPointEdges(), extendedEdgeMesh::sortPointsAndEdges(), cellZoneSet::subset(), pointZoneSet::subset(), surfaceIntersection::surfaceIntersection(), CollisionRecordList< PairType, WallType >::update(), probes::updateMesh(), wallLayerCells::wallLayerCells(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::xfer(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
Foam::DynamicList< T, SizeInc, SizeMult, SizeDiv > & append (const UList< T > & lst) inline
Append a List at the end of this list.
Definition at line 307 of file DynamicListI.H.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::FatalError, FatalErrorInFunction, forAll, UList< T >::operator[](), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::size(), and UList< T >::size().
Foam::DynamicList< T, SizeInc, SizeMult, SizeDiv > & append (const UIndirectList< T > & lst) inline
Append a UIndirectList at the end of this list.
Definition at line 331 of file DynamicListI.H.
References forAll, UList< T >::operator[](), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), UIndirectList< T >::size(), and List< T >::size().
T remove () inline
Remove and return the top element.
Definition at line 347 of file DynamicListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, DynamicList< T, SizeInc, SizeMult, SizeDiv >::operator, UList< T >::operator[](), List< T >::size(), and Foam::T().
Referenced by UPstream::allocateTag(), directMethod::appendToDirectSeeds(), mapNearestMethod::findMappedSrcCell(), mapNearestMethod::findNearestCell(), faceAreaWeightAMI< SourcePatch, TargetPatch >::processSourceFace(), and Reaction< ReactionThermo >::setLRhs().
T & operator() (const label elemI) inline
Return non-const access to an element, resizing list if.
necessary
Definition at line 369 of file DynamicListI.H.
References UList< T >::operator[](), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize().
void operator= (const T & t) inline
Assignment of all addressed entries to the given value.
Definition at line 384 of file DynamicListI.H.
void operator= (const DynamicList< T, SizeInc, SizeMult, SizeDiv > & lst) inline
Assignment from DynamicList.
Definition at line 394 of file DynamicListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, List< T >::operator=(), List< T >::size(), and UList< T >::size().
void operator= (const UList< T > & lst) inline
Assignment from UList.
Definition at line 423 of file DynamicListI.H.
References List< T >::operator=(), List< T >::size(), and UList< T >::size().
void operator= (const UIndirectList< T > & lst) inline
Assignment from UIndirectList.
Definition at line 446 of file DynamicListI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::erase(), List< T >::operator=(), List< T >::size(), and UList< T >::size().
Foam::UList< T >::iterator erase (typename UList< T >::iterator curIter)
Erase an element, move the remaining elements to fill the gap.
and resize the List
Definition at line 472 of file DynamicListI.H.
References UList< T >::end(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), and List< T >::size().
Referenced by DynamicList< T, SizeInc, SizeMult, SizeDiv >::operator=().
Friends And Related Function Documentation
friend class List< T > friend
Declare friendship with the List class.
Definition at line 98 of file DynamicList.H.
Ostream& operator (Ostream & , const DynamicList< T, SizeInc, SizeMult, SizeDiv > &) friend
Referenced by DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove().
Istream& operator>> (Istream & , DynamicList< T, SizeInc, SizeMult, SizeDiv > &) friend
Read from Istream, discarding contents of existing DynamicList.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/DynamicList/DynamicList.H
src/OpenFOAM/containers/Lists/DynamicList/DynamicList.C
src/OpenFOAM/containers/Lists/DynamicList/DynamicListI.H