OpenFOAM-dev: epsilonWallFunctionFvPatchScalarField Class Reference 2
epsilonWallFunctionFvPatchScalarField Class Reference
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a turbulence dissipation wall function condition for high Reynolds number, turbulent flow cases.
Public Member Functions
TypeName ("epsilonWallFunction")
Runtime type information.
epsilonWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
epsilonWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
epsilonWallFunctionFvPatchScalarField (const epsilonWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
epsilonWallFunctionFvPatchScalarField (const epsilonWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
epsilonWallFunctionFvPatchScalarField (const epsilonWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual ~epsilonWallFunctionFvPatchScalarField ()
Destructor.
scalarField & G (bool init=false)
Return non-const access to the master's G field.
scalarField & epsilon (bool init=false)
Return non-const access to the master's epsilon field.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void updateWeightedCoeffs (const scalarField &weights)
Update the coefficients associated with the patch field.
virtual void manipulateMatrix (fvMatrix< scalar > &matrix)
Manipulate matrix.
virtual void manipulateMatrix (fvMatrix< scalar > &matrix, const scalarField &weights)
Manipulate matrix with given weights.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from fixedValueFvPatchField< scalar >
TypeName ("fixedValue")
Runtime type information.
fixedValueFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fixedValueFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const scalar &value)
Construct from patch, internal field and value.
fixedValueFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedValueFvPatchField (const fixedValueFvPatchField< scalar > &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fixedValueFvPatchField<Type>
fixedValueFvPatchField (const fixedValueFvPatchField< scalar > &)
Construct as copy.
fixedValueFvPatchField (const fixedValueFvPatchField< scalar > &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool assignable () const
Return false: this patch field is not altered by assignment.
virtual tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< scalar > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< scalar > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the.
virtual void operator= (const UList< scalar > &)
virtual void operator= (const fvPatchField< scalar > &)
virtual void operator= (const scalar &)
virtual void operator+= (const fvPatchField< scalar > &)
virtual void operator+= (const Field< scalar > &)
virtual void operator+= (const scalar &)
virtual void operator-= (const fvPatchField< scalar > &)
virtual void operator-= (const Field< scalar > &)
virtual void operator-= (const scalar &)
virtual void operator*= (const fvPatchField< scalar > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator*= (const scalar)
virtual void operator/= (const fvPatchField< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator/= (const scalar)
Public Member Functions inherited from fvPatchField< Type >
TypeName ("fvPatchField")
Runtime type information.
declareRunTimeSelectionTable (tmp, fvPatchField, patch,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvPatchField, patchMapper,(const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict),(p, iF, dict))
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Type &value)
Construct from patch, internal field and value.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const word &patchType)
Construct from patch and internal field and patch type.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &, const bool valueRequired=false)
Construct from patch, internal field and dictionary.
fvPatchField (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fvPatchField onto a new patch.
fvPatchField (const fvPatchField< Type > &)
Construct as copy.
fvPatchField (const fvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< Type > > clone (const DimensionedField< Type, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual ~fvPatchField ()
Destructor.
virtual bool coupled () const
Return true if this patch field is coupled.
const objectRegistry & db () const
Return local objectRegistry.
const fvPatch & patch () const
Return patch.
const DimensionedField< Type, volMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
bool updated () const
Return true if the boundary condition has already been updated.
bool manipulatedMatrix () const
Return true if the matrix has already been manipulated.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchField< Type > &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual tmp< Field< Type > > snGrad () const
Return patch-normal gradient.
virtual tmp< Field< Type > > snGrad (const scalarField &deltaCoeffs) const
Return patch-normal gradient for coupled-patches.
virtual tmp< Field< Type > > patchInternalField () const
Return internal field next to patch as patch field.
virtual void patchInternalField (Field< Type > &) const
Return internal field next to patch as patch field.
virtual tmp< Field< Type > > patchNeighbourField () const
Return patchField on the opposite patch of a coupled patch.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise the evaluation of the patch field.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field, sets Updated to false.
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< Field< scalar >> &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< Field< scalar >> &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs (const scalarField &deltaCoeffs) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs (const scalarField &deltaCoeffs) const
Return the matrix source coefficients corresponding to the.
virtual void manipulateMatrix (fvMatrix< Type > &matrix)
Manipulate matrix.
virtual void manipulateMatrix (fvMatrix< Type > &matrix, const scalarField &weights)
Manipulate matrix with given weights.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
void check (const fvPatchField< Type > &) const
Check fvPatchField<Type> against given fvPatchField<Type>
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvPatchField< Type > &)
virtual void operator+= (const fvPatchField< Type > &)
virtual void operator-= (const fvPatchField< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator== (const fvPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &pf)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Protected Member Functions
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
virtual void setMaster ()
Set the master patch - master is responsible for updating all.
virtual void createAveragingWeights ()
Create the averaging weights for cells which are bounded by.
virtual epsilonWallFunctionFvPatchScalarField & epsilonPatch (const label patchi)
Helper function to return non-const access to an epsilon patch.
virtual void calculateTurbulenceFields (const turbulenceModel &turbulence, scalarField &G0, scalarField &epsilon0)
Main driver to calculate the turbulence fields.
virtual void calculate (const turbulenceModel &turbulence, const List< scalar > &cornerWeights, const fvPatch &patch, scalarField &G, scalarField &epsilon)
Calculate the epsilon and G.
virtual label & master ()
Return non-const access to the master patch ID.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Attributes
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalarField G_
Local copy of turbulence G field.
scalarField epsilon_
Local copy of turbulence epsilon field.
bool initialised_
Initialised flag.
label master_
Master patch ID.
List< List< scalar > > cornerWeights_
List of averaging corner weights.
Static Protected Attributes
static scalar tolerance_ = 1e-5
Tolerance used in weighted calculations.
Additional Inherited Members
Public Types inherited from fvPatchField< Type >
typedef fvPatch Patch
typedef calculatedFvPatchField< Type > Calculated
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from fvPatchField< Type >
static tmp< fvPatchField< Type > > New (const word &, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const word &, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static tmp< fvPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatch &)
Return a pointer to a new calculatedFvPatchField created on.
template<class Type2 >
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &)
Return a pointer to a new calculatedFvPatchField created on.
static const word & calculatedType ()
Return the type of the calculated for of fvPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes inherited from fvPatchField< Type >
static int disallowGenericFvPatchField
Debug switch to disallow the use of genericFvPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Detailed Description
This boundary condition provides a turbulence dissipation wall function condition for high Reynolds number, turbulent flow cases.
The condition can be applied to wall boundaries, whereby it
calculates epsilon and G
inserts near wall epsilon values directly into the epsilon equation to act as a constraint
where
= turblence dissipation field
= turblence generation field
Usage
Property Description Required Default value
Cmu model coefficient no 0.09
kappa Von Karman constant no 0.41
E model coefficient no 9.8
Example of the boundary condition specification:
    <patchName>
    {
        type            epsilonWallFunction;
    }
See also
Foam::fixedInternalValueFvPatchField
Source files
epsilonWallFunctionFvPatchScalarField.H
epsilonWallFunctionFvPatchScalarField.C
Definition at line 113 of file epsilonWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
epsilonWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 254 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::checkType().
Referenced by epsilonWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::clone(), epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField(), and epsilonWallFunctionFvPatchScalarField::master().
epsilonWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 298 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::checkType(), epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField(), fvPatchField< Type >::operator==(), and fvPatchField< Type >::patchInternalField().
epsilonWallFunctionFvPatchScalarField (const epsilonWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
epsilonWallFunctionFvPatchScalarField onto a new patch
Definition at line 275 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::checkType(), and epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField().
epsilonWallFunctionFvPatchScalarField (const epsilonWallFunctionFvPatchScalarField & ewfpsf)
Construct as copy.
Definition at line 323 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::checkType(), and epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField().
epsilonWallFunctionFvPatchScalarField (const epsilonWallFunctionFvPatchScalarField & ewfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 343 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::checkType().
virtual ~epsilonWallFunctionFvPatchScalarField () inline virtual
Destructor.
Definition at line 265 of file epsilonWallFunctionFvPatchScalarField.H.
References epsilonWallFunctionFvPatchScalarField::epsilon(), epsilonWallFunctionFvPatchScalarField::G(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and epsilonWallFunctionFvPatchScalarField::write().
Member Function Documentation
void checkType () protected virtual
Check the type of the patch.
Definition at line 40 of file epsilonWallFunctionFvPatchScalarField.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, fvPatch::name(), Foam::nl, fvPatchField< Type >::patch(), and epsilonWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField().
void writeLocalEntries (Ostream & os) const protected virtual
Write local wall function variables.
Definition at line 55 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::Cmu_, epsilonWallFunctionFvPatchScalarField::E_, token::END_STATEMENT, epsilonWallFunctionFvPatchScalarField::kappa_, Foam::nl, and Ostream::writeKeyword().
Referenced by epsilonWallFunctionFvPatchScalarField::checkType(), and epsilonWallFunctionFvPatchScalarField::write().
void setMaster () protected virtual
Set the master patch - master is responsible for updating all.
wall function patches
Definition at line 65 of file epsilonWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), epsilonWallFunctionFvPatchScalarField::epsilon(), epsilonWallFunctionFvPatchScalarField::epsilonPatch(), forAll, fvPatchField< Type >::internalField(), epsilonWallFunctionFvPatchScalarField::master(), epsilonWallFunctionFvPatchScalarField::master_, and patchi.
Referenced by epsilonWallFunctionFvPatchScalarField::updateCoeffs(), and epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs().
void createAveragingWeights () protected virtual
Create the averaging weights for cells which are bounded by.
multiple wall function faces
Definition at line 95 of file epsilonWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::changing(), epsilonWallFunctionFvPatchScalarField::cornerWeights_, Foam::dimless, epsilonWallFunctionFvPatchScalarField::epsilon(), epsilonWallFunctionFvPatchScalarField::epsilon_, forAll, epsilonWallFunctionFvPatchScalarField::G_, epsilonWallFunctionFvPatchScalarField::initialised_, fvPatchField< Type >::internalField(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, fvPatchField< Type >::patchInternalField(), List< T >::setSize(), List< Type >::size(), fvMesh::time(), and Time::timeName().
Referenced by epsilonWallFunctionFvPatchScalarField::updateCoeffs(), and epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs().
Foam::epsilonWallFunctionFvPatchScalarField & epsilonPatch (const label patchi) protected virtual
Helper function to return non-const access to an epsilon patch.
Definition at line 155 of file epsilonWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), epsilonWallFunctionFvPatchScalarField::calculateTurbulenceFields(), epsilonWallFunctionFvPatchScalarField::epsilon(), fvPatchField< Type >::internalField(), and patchi.
Referenced by epsilonWallFunctionFvPatchScalarField::calculateTurbulenceFields(), epsilonWallFunctionFvPatchScalarField::epsilon(), epsilonWallFunctionFvPatchScalarField::G(), and epsilonWallFunctionFvPatchScalarField::setMaster().
void calculateTurbulenceFields (const turbulenceModel & turbulence, scalarField & G0, scalarField & epsilon0) protected virtual
Main driver to calculate the turbulence fields.
Definition at line 170 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::calculate(), epsilonWallFunctionFvPatchScalarField::cornerWeights_, UList< Type >::empty(), Foam::constant::electromagnetic::epsilon0, epsilonWallFunctionFvPatchScalarField::epsilonPatch(), fvPatch::faceCells(), forAll, Foam::constant::electromagnetic::G0, fvPatchField< Type >::patch(), and patchi.
Referenced by epsilonWallFunctionFvPatchScalarField::epsilonPatch(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), and epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs().
void calculate (const turbulenceModel & turbulence, const List< scalar > & cornerWeights, const fvPatch & patch, scalarField & G, scalarField & epsilon) protected virtual
Calculate the epsilon and G.
Reimplemented in epsilonLowReWallFunctionFvPatchScalarField.
Definition at line 203 of file epsilonWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), epsilonWallFunctionFvPatchScalarField::Cmu_, epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField(), fvPatch::faceCells(), forAll, fvPatch::index(), k, turbulenceModel::k(), epsilonWallFunctionFvPatchScalarField::kappa_, Foam::mag(), turbulenceModel::nu(), turbulenceModel::nut(), patchi, Foam::pow(), Foam::pow025(), fvPatchField< Type >::snGrad(), Foam::sqrt(), turbulenceModel::U(), y, and turbulenceModel::y().
Referenced by epsilonWallFunctionFvPatchScalarField::calculateTurbulenceFields().
virtual label& master () inline protected virtual
Return non-const access to the master patch ID.
Definition at line 190 of file epsilonWallFunctionFvPatchScalarField.H.
References epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField(), epsilonWallFunctionFvPatchScalarField::master_, and epsilonWallFunctionFvPatchScalarField::TypeName().
Referenced by epsilonWallFunctionFvPatchScalarField::setMaster().
TypeName ("epsilonWallFunction")
Runtime type information.
Referenced by epsilonWallFunctionFvPatchScalarField::master().
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from fixedValueFvPatchField< scalar >.
Reimplemented in epsilonLowReWallFunctionFvPatchScalarField.
Definition at line 237 of file epsilonWallFunctionFvPatchScalarField.H.
References epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from fixedValueFvPatchField< scalar >.
Reimplemented in epsilonLowReWallFunctionFvPatchScalarField.
Definition at line 254 of file epsilonWallFunctionFvPatchScalarField.H.
References epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField().
Foam::scalarField & G (bool init = false)
Return non-const access to the master's G field.
Definition at line 364 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::epsilon(), epsilonWallFunctionFvPatchScalarField::epsilonPatch(), epsilonWallFunctionFvPatchScalarField::G(), epsilonWallFunctionFvPatchScalarField::G_, epsilonWallFunctionFvPatchScalarField::master_, and fvPatchField< Type >::patch().
Referenced by epsilonWallFunctionFvPatchScalarField::G(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and epsilonWallFunctionFvPatchScalarField::~epsilonWallFunctionFvPatchScalarField().
Foam::scalarField & epsilon (bool init = false)
Return non-const access to the master's epsilon field.
Definition at line 381 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::epsilon(), epsilonWallFunctionFvPatchScalarField::epsilon_, epsilonWallFunctionFvPatchScalarField::epsilonPatch(), epsilonWallFunctionFvPatchScalarField::master_, and fvPatchField< Type >::patch().
Referenced by epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), epsilonWallFunctionFvPatchScalarField::epsilon(), epsilonWallFunctionFvPatchScalarField::epsilonPatch(), epsilonWallFunctionFvPatchScalarField::G(), epsilonWallFunctionFvPatchScalarField::setMaster(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and epsilonWallFunctionFvPatchScalarField::~epsilonWallFunctionFvPatchScalarField().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from fvPatchField< Type >.
Definition at line 399 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::calculateTurbulenceFields(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), fvPatchField< Type >::db(), epsilonWallFunctionFvPatchScalarField::epsilon(), fvPatch::faceCells(), forAll, epsilonWallFunctionFvPatchScalarField::G(), turbulenceModel::GName(), Foam::constant::atomic::group, IOobject::groupName(), fvPatchField< Type >::internalField(), objectRegistry::lookupObject(), epsilonWallFunctionFvPatchScalarField::master_, fvPatchField< Type >::patch(), turbulenceModel::propertiesName, epsilonWallFunctionFvPatchScalarField::setMaster(), fvPatchField< Type >::updateCoeffs(), fvPatchField< Type >::updated(), and epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs().
Referenced by epsilonWallFunctionFvPatchScalarField::~epsilonWallFunctionFvPatchScalarField().
void updateWeightedCoeffs (const scalarField & weights) virtual
Update the coefficients associated with the patch field.
Reimplemented from fvPatchField< Type >.
Definition at line 449 of file epsilonWallFunctionFvPatchScalarField.C.
References epsilonWallFunctionFvPatchScalarField::calculateTurbulenceFields(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), fvPatchField< Type >::db(), epsilonWallFunctionFvPatchScalarField::epsilon(), fvPatch::faceCells(), forAll, epsilonWallFunctionFvPatchScalarField::G(), turbulenceModel::GName(), Foam::constant::atomic::group, IOobject::groupName(), fvPatchField< Type >::internalField(), objectRegistry::lookupObject(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), epsilonWallFunctionFvPatchScalarField::master_, fvPatchField< Type >::patch(), turbulenceModel::propertiesName, epsilonWallFunctionFvPatchScalarField::setMaster(), epsilonWallFunctionFvPatchScalarField::tolerance_, fvPatchField< Type >::updateCoeffs(), and fvPatchField< Type >::updated().
Referenced by epsilonWallFunctionFvPatchScalarField::updateCoeffs(), and epsilonWallFunctionFvPatchScalarField::~epsilonWallFunctionFvPatchScalarField().
void manipulateMatrix (fvMatrix< scalar > & matrix) virtual
Manipulate matrix.
Definition at line 510 of file epsilonWallFunctionFvPatchScalarField.C.
References fvPatchField< Type >::manipulatedMatrix(), fvPatchField< Type >::manipulateMatrix(), fvPatchField< Type >::patch(), fvPatchField< Type >::patchInternalField(), and fvMatrix< Type >::setValues().
Referenced by epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and epsilonWallFunctionFvPatchScalarField::~epsilonWallFunctionFvPatchScalarField().
void manipulateMatrix (fvMatrix< scalar > & matrix, const scalarField & weights) virtual
Manipulate matrix with given weights.
Definition at line 526 of file epsilonWallFunctionFvPatchScalarField.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), fvPatch::faceCells(), forAll, fvPatchField< Type >::internalField(), fvPatchField< Type >::manipulatedMatrix(), fvPatchField< Type >::manipulateMatrix(), fvPatch::name(), fvPatchField< Type >::patch(), Foam::Pout, fvMatrix< Type >::setValues(), List< T >::size(), fvPatch::size(), and epsilonWallFunctionFvPatchScalarField::tolerance_.
void write (Ostream & os) const virtual
Write.
Reimplemented from fixedValueFvPatchField< scalar >.
Definition at line 578 of file epsilonWallFunctionFvPatchScalarField.C.
References Foam::makePatchTypeField(), fixedValueFvPatchField< Type >::write(), and epsilonWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by epsilonWallFunctionFvPatchScalarField::~epsilonWallFunctionFvPatchScalarField().
Member Data Documentation
Foam::scalar tolerance_ = 1e-5 static protected
Tolerance used in weighted calculations.
Definition at line 122 of file epsilonWallFunctionFvPatchScalarField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), and epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs().
scalar Cmu_ protected
Cmu coefficient.
Definition at line 125 of file epsilonWallFunctionFvPatchScalarField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::calculate(), and epsilonWallFunctionFvPatchScalarField::writeLocalEntries().
scalar kappa_ protected
Von Karman constant.
Definition at line 128 of file epsilonWallFunctionFvPatchScalarField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::calculate(), and epsilonWallFunctionFvPatchScalarField::writeLocalEntries().
scalar E_ protected
E coefficient.
Definition at line 131 of file epsilonWallFunctionFvPatchScalarField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::writeLocalEntries().
scalarField G_ protected
Local copy of turbulence G field.
Definition at line 134 of file epsilonWallFunctionFvPatchScalarField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), and epsilonWallFunctionFvPatchScalarField::G().
scalarField epsilon_ protected
Local copy of turbulence epsilon field.
Definition at line 137 of file epsilonWallFunctionFvPatchScalarField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), and epsilonWallFunctionFvPatchScalarField::epsilon().
bool initialised_ protected
Initialised flag.
Definition at line 140 of file epsilonWallFunctionFvPatchScalarField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::createAveragingWeights().
label master_ protected
Master patch ID.
Definition at line 143 of file epsilonWallFunctionFvPatchScalarField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::epsilon(), epsilonWallFunctionFvPatchScalarField::G(), epsilonWallFunctionFvPatchScalarField::master(), epsilonWallFunctionFvPatchScalarField::setMaster(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), and epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs().
List<List<scalar> > cornerWeights_ protected
List of averaging corner weights.
Definition at line 146 of file epsilonWallFunctionFvPatchScalarField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::calculateTurbulenceFields(), and epsilonWallFunctionFvPatchScalarField::createAveragingWeights().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/epsilonWallFunctions/epsilonWallFunction/epsilonWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/epsilonWallFunctions/epsilonWallFunction/epsilonWallFunctionFvPatchScalarField.C