OpenFOAM: explicitPorositySource Class Reference
explicitPorositySource Class Reference
Explicit porosity source.
Public Member Functions
TypeName ("explicitPorositySource")
Runtime type information.
explicitPorositySource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~explicitPorositySource ()
Destructor.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
Add implicit contribution to momentum equation.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
Add implicit contribution to compressible momentum equation.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
Add implicit contribution to phase momentum equation.
virtual bool read (const dictionary &dict)
Read dictionary.
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
Runtime type information.
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~cellSetOption ()
Destructor.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const labelList & cells () const
Return const access to the cell set.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldi)
Set the applied flag to true for field index fieldi.
Switch & active ()
Return access to the source active flag.
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Protected Attributes
autoPtr< porosityModel > porosityPtr_
Run-time selectable porosity model.
Protected Attributes inherited from cellSetOption
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType { smPoints, smCellSet, smCellZone, smAll }
Enumeration for selection mode types.
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Static Public Attributes inherited from cellSetOption
static const NamedEnum< selectionModeType, 4 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Detailed Description
Explicit porosity source.
Usage
Example usage, here employing the Darcy-Forchheimer model:
explicitPorositySourceCoeffs
{
    type            DarcyForchheimer;
    DarcyForchheimerCoeffs
    {
        d   d [0 -2 0 0 0 0 0] (5e7 -1000 -1000);
        f   f [0 -1 0 0 0 0 0] (0 0 0);
        coordinateSystem
        {
            type    cartesian;
            origin  (0 0 0);
            coordinateRotation
            {
                type    axesRotation;
                e1  (0.70710678 0.70710678 0);
                e2  (0 0 1);
            }
        }
    }
}
Note: The porous region must be selected as a cellZone.
Source files
explicitPorositySource.H
explicitPorositySource.C
Definition at line 84 of file explicitPorositySource.H.
Constructor & Destructor Documentation
explicitPorositySource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 52 of file explicitPorositySource.C.
References explicitPorositySource::addSup(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, porosityModel::New(), and Foam::read().
virtual ~explicitPorositySource () inline virtual
Destructor.
Definition at line 127 of file explicitPorositySource.H.
References explicitPorositySource::addSup(), Foam::constant::atomic::alpha, dict, explicitPorositySource::read(), and rho.
Member Function Documentation
TypeName ("explicitPorositySource")
Runtime type information.
void addSup (fvMatrix< vector > & eqn, const label fieldi) virtual
Add implicit contribution to momentum equation.
Reimplemented from option.
Definition at line 87 of file explicitPorositySource.C.
References fvMatrix< Type >::dimensions(), and fvMatrix< Type >::psi().
Referenced by explicitPorositySource::addSup(), explicitPorositySource::explicitPorositySource(), and explicitPorositySource::~explicitPorositySource().
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Add implicit contribution to compressible momentum equation.
Reimplemented from option.
Definition at line 99 of file explicitPorositySource.C.
References explicitPorositySource::addSup(), fvMatrix< Type >::dimensions(), and fvMatrix< Type >::psi().
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Add implicit contribution to phase momentum equation.
Reimplemented from option.
Definition at line 112 of file explicitPorositySource.C.
References fvMatrix< Type >::dimensions(), and fvMatrix< Type >::psi().
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from cellSetOption.
Definition at line 125 of file explicitPorositySource.C.
References cellSetOption::read().
Referenced by explicitPorositySource::~explicitPorositySource().
Member Data Documentation
autoPtr<porosityModel> porosityPtr_ protected
Run-time selectable porosity model.
Definition at line 94 of file explicitPorositySource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/explicitPorositySource/explicitPorositySource.H
src/fvOptions/sources/derived/explicitPorositySource/explicitPorositySource.C