OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldCoordinateSystemTransform Class Reference
FunctionObjects » Field function objects
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
Public Member Functions
TypeName ("fieldCoordinateSystemTransform")
Runtime type information.
fieldCoordinateSystemTransform (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~fieldCoordinateSystemTransform ()
Destructor.
virtual const word & name () const
Return name of the fieldCoordinateSystemTransform object.
virtual void read (const dictionary &)
Read the input data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Static Public Member Functions
static bool viable (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Return true if the construction of this functionObject is viable.
Protected Member Functions
template<class Type >
void transform (const word &fieldName) const
template<class Type >
void transformField (const Type &field) const
Protected Attributes
word name_
Name.
const objectRegistry & obr_
wordList fieldSet_
Fields to transform.
coordinateSystem coordSys_
Co-ordinate system to transform to.
Detailed Description
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
Example of function object specification:
fieldCoordinateSystemTransform1
{
    type        fieldCoordinateSystemTransform;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    fields
    (
        U
        UMean
        UPrime2Mean
    );
    coordinateSystem
    {
        origin  (0.001  0       0);
        e1      (1      0.15    0);
        e3      (0      0      -1);
    }
}
Function object usage
Property Description Required Default value
type type name: fieldCoordinateSystemTransform yes
fields list of fields to be transformed yes
coordinateSystem local co-ordinate system yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject Foam::coordinateSystem
Source files
fieldCoordinateSystemTransform.H
fieldCoordinateSystemTransform.C
fieldCoordinateSystemTransformTemplates.C
IOfieldCoordinateSystemTransform.H
Definition at line 122 of file fieldCoordinateSystemTransform.H.
Constructor & Destructor Documentation
fieldCoordinateSystemTransform (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 44 of file fieldCoordinateSystemTransform.C.
References Foam::endl(), Foam::Info, Foam::nl, Foam::read(), Foam::type(), and fieldCoordinateSystemTransform::viable().
~fieldCoordinateSystemTransform () virtual
Destructor.
Definition at line 80 of file fieldCoordinateSystemTransform.C.
References fieldCoordinateSystemTransform::read().
Referenced by fieldCoordinateSystemTransform::viable().
Member Function Documentation
void transform (const word & fieldName) const protected
Definition at line 78 of file fieldCoordinateSystemTransformTemplates.C.
References Foam::endl(), Foam::Info, and Foam::type().
Referenced by fieldCoordinateSystemTransform::transformField().
void transformField (const Type & field) const protected
Definition at line 36 of file fieldCoordinateSystemTransformTemplates.C.
References Foam::endl(), Foam::Info, Foam::nl, R, Foam::transform(), fieldCoordinateSystemTransform::transform(), and Ostream::write().
TypeName ("fieldCoordinateSystemTransform")
Runtime type information.
bool viable (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false) static
Return true if the construction of this functionObject is viable.
i.e. the prerequisites for construction are available
Definition at line 65 of file fieldCoordinateSystemTransform.C.
References fieldCoordinateSystemTransform::~fieldCoordinateSystemTransform().
Referenced by fieldCoordinateSystemTransform::fieldCoordinateSystemTransform().
virtual const word& name () const inline virtual
Return name of the fieldCoordinateSystemTransform object.
Definition at line 196 of file fieldCoordinateSystemTransform.H.
References fieldCoordinateSystemTransform::end(), fieldCoordinateSystemTransform::execute(), fieldCoordinateSystemTransform::name_, fieldCoordinateSystemTransform::read(), fieldCoordinateSystemTransform::timeSet(), and fieldCoordinateSystemTransform::write().
void read (const dictionary & dict) virtual
Read the input data.
Definition at line 87 of file fieldCoordinateSystemTransform.C.
References dictionary::lookup().
Referenced by fieldCoordinateSystemTransform::name(), and fieldCoordinateSystemTransform::~fieldCoordinateSystemTransform().
void execute () virtual
Execute, currently does nothing.
Definition at line 95 of file fieldCoordinateSystemTransform.C.
References forAll, Foam::Info, Foam::nl, and Foam::type().
Referenced by fieldCoordinateSystemTransform::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 111 of file fieldCoordinateSystemTransform.C.
Referenced by fieldCoordinateSystemTransform::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 117 of file fieldCoordinateSystemTransform.C.
Referenced by fieldCoordinateSystemTransform::name().
void write () virtual
Write.
Definition at line 121 of file fieldCoordinateSystemTransform.C.
References Foam::endl(), forAll, Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by fieldCoordinateSystemTransform::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 217 of file fieldCoordinateSystemTransform.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 221 of file fieldCoordinateSystemTransform.H.
Member Data Documentation
word name_ protected
Name.
Definition at line 129 of file fieldCoordinateSystemTransform.H.
Referenced by fieldCoordinateSystemTransform::name().
const objectRegistry& obr_ protected
Definition at line 131 of file fieldCoordinateSystemTransform.H.
wordList fieldSet_ protected
Fields to transform.
Definition at line 134 of file fieldCoordinateSystemTransform.H.
coordinateSystem coordSys_ protected
Co-ordinate system to transform to.
Definition at line 137 of file fieldCoordinateSystemTransform.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransform.H
src/postProcessing/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransform.C
src/postProcessing/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransformTemplates.C