OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldCoordinateSystemTransform Class Reference
FunctionObjects » Field function objects
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
Public Member Functions
TypeName ("fieldCoordinateSystemTransform")
Runtime type information.
fieldCoordinateSystemTransform (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~fieldCoordinateSystemTransform ()
Destructor.
virtual bool read (const dictionary &)
Read the input data.
virtual bool execute ()
Calculate the transformed fields.
virtual bool write ()
Write the transformed fields.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
word transformFieldName (const word &fieldName) const
Return the name of the transformed field.
template<class FieldType >
void transformField (const FieldType &field)
Transform the given field.
template<class Type >
void transform (const word &fieldName)
Transform the given field if has the specified element type.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
wordList fieldSet_
Fields to transform.
coordinateSystem coordSys_
Co-ordinate system to transform to.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
Example of function object specification:
fieldCoordinateSystemTransform1
{
    type        fieldCoordinateSystemTransform;
    libs ("libfieldFunctionObjects.so");
    ...
    fields
    (
        U
        UMean
        UPrime2Mean
    );
    coordinateSystem
    {
        origin  (0.001  0       0);
        e1      (1      0.15    0);
        e3      (0      0      -1);
    }
}
Usage
Property Description Required Default value
type type name: fieldCoordinateSystemTransform yes
fields list of fields to be transformed yes
coordinateSystem local co-ordinate system yes
See also
Foam::functionObjects::fvMeshFunctionObject Foam::coordinateSystem
Source files
fieldCoordinateSystemTransform.H
fieldCoordinateSystemTransform.C
fieldCoordinateSystemTransformTemplates.C
Definition at line 111 of file fieldCoordinateSystemTransform.H.
Constructor & Destructor Documentation
fieldCoordinateSystemTransform (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 51 of file fieldCoordinateSystemTransform.C.
References Foam::endl(), Log, Foam::nl, Foam::read(), Foam::type(), and fieldCoordinateSystemTransform::~fieldCoordinateSystemTransform().
~fieldCoordinateSystemTransform () virtual
Destructor.
Definition at line 72 of file fieldCoordinateSystemTransform.C.
References fieldCoordinateSystemTransform::transformFieldName().
Referenced by fieldCoordinateSystemTransform::fieldCoordinateSystemTransform().
Member Function Documentation
Foam::word transformFieldName (const word & fieldName) const protected
Return the name of the transformed field.
Definition at line 80 of file fieldCoordinateSystemTransform.C.
References fieldCoordinateSystemTransform::read().
Referenced by fieldCoordinateSystemTransform::~fieldCoordinateSystemTransform().
void transformField (const FieldType & field) protected
Transform the given field.
Definition at line 35 of file fieldCoordinateSystemTransformTemplates.C.
References Foam::transform(), and fieldCoordinateSystemTransform::transform().
void transform (const word & fieldName) protected
Transform the given field if has the specified element type.
Definition at line 51 of file fieldCoordinateSystemTransformTemplates.C.
References DebugInfo, Foam::endl(), and Foam::type().
Referenced by fieldCoordinateSystemTransform::transformField().
TypeName ("fieldCoordinateSystemTransform")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the input data.
Reimplemented from regionFunctionObject.
Definition at line 89 of file fieldCoordinateSystemTransform.C.
References dictionary::lookup(), and regionFunctionObject::read().
Referenced by fieldCoordinateSystemTransform::transformFieldName().
bool execute () virtual
Calculate the transformed fields.
Implements functionObject.
Definition at line 101 of file fieldCoordinateSystemTransform.C.
References forAll.
bool write () virtual
Write the transformed fields.
Implements functionObject.
Definition at line 116 of file fieldCoordinateSystemTransform.C.
References forAll.
Member Data Documentation
wordList fieldSet_ protected
Fields to transform.
Definition at line 120 of file fieldCoordinateSystemTransform.H.
coordinateSystem coordSys_ protected
Co-ordinate system to transform to.
Definition at line 123 of file fieldCoordinateSystemTransform.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransform.H
src/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransform.C
src/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransformTemplates.C