OpenFOAM-dev: extendedFeatureEdgeMeshFormat Class Reference 2
extendedFeatureEdgeMeshFormat Class Reference
Provide a means of reading extendedFeatureEdgeMesh as featureEdgeMesh.
Public Member Functions
extendedFeatureEdgeMeshFormat (const fileName &)
Construct from file name.
virtual ~extendedFeatureEdgeMeshFormat ()
Destructor.
virtual bool read (const fileName &)
Read from file.
Public Member Functions inherited from edgeMesh
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const pointField &, const edgeList &)
Construct from components.
edgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges).
edgeMesh (const edgeMesh &)
Construct as copy.
edgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
edgeMesh (Istream &)
Construct from Istream.
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< edgeMesh > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void clear ()
Clear all storage.
virtual void reset (const Xfer< pointField > &points, const Xfer< edgeList > &edges)
Reset primitive data (points, edges)
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
void mergeEdges ()
Merge similar edges.
virtual void writeStats (Ostream &) const
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void operator= (const edgeMesh &)
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Static Public Member Functions
static autoPtr< edgeMesh > New (const fileName &name)
Read file and return surface.
Static Public Member Functions inherited from edgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const edgeMesh &)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Additional Inherited Members
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
Provide a means of reading extendedFeatureEdgeMesh as featureEdgeMesh.
Source files
extendedFeatureEdgeMeshFormat.H
extendedFeatureEdgeMeshFormat.C
Definition at line 50 of file extendedFeatureEdgeMeshFormat.H.
Constructor & Destructor Documentation
extendedFeatureEdgeMeshFormat (const fileName & filename)
Construct from file name.
Definition at line 33 of file extendedFeatureEdgeMeshFormat.C.
References Foam::read(), and extendedFeatureEdgeMeshFormat::read().
virtual ~extendedFeatureEdgeMeshFormat () inline virtual
Destructor.
Definition at line 84 of file extendedFeatureEdgeMeshFormat.H.
References extendedFeatureEdgeMeshFormat::read().
Member Function Documentation
static autoPtr<edgeMesh> New (const fileName & name) inline static
Read file and return surface.
Definition at line 74 of file extendedFeatureEdgeMeshFormat.H.
bool read (const fileName & filename) virtual
Read from file.
Reimplemented from edgeMesh.
Definition at line 44 of file extendedFeatureEdgeMeshFormat.C.
References clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), and Foam::read().
Referenced by extendedFeatureEdgeMeshFormat::extendedFeatureEdgeMeshFormat(), and extendedFeatureEdgeMeshFormat::~extendedFeatureEdgeMeshFormat().
The documentation for this class was generated from the following files:
src/edgeMesh/edgeMeshFormats/extendedFeatureEdgeMesh/extendedFeatureEdgeMeshFormat.H
src/edgeMesh/edgeMeshFormats/extendedFeatureEdgeMesh/extendedFeatureEdgeMeshFormat.C