OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldToCell Class Reference
A topoSetSource to select cells based on field values.
Public Member Functions
TypeName ("fieldToCell")
Runtime type information.
fieldToCell (const polyMesh &mesh, const word &fieldName, const scalar min, const scalar max)
Construct from components.
fieldToCell (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
fieldToCell (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~fieldToCell ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label cellI, const bool) const
Add (if bool) cellI to set or delete cellI from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = NULL
A table of usage strings.
Detailed Description
A topoSetSource to select cells based on field values.
Source files
fieldToCell.H
fieldToCell.C
Definition at line 49 of file fieldToCell.H.
Constructor & Destructor Documentation
fieldToCell (const polyMesh & mesh, const word & fieldName, const scalar min, const scalar max)
Construct from components.
Definition at line 102 of file fieldToCell.C.
Referenced by fieldToCell::fieldToCell().
fieldToCell (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 118 of file fieldToCell.C.
References fieldToCell::fieldToCell().
fieldToCell (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 132 of file fieldToCell.C.
~fieldToCell () virtual
Destructor.
Definition at line 146 of file fieldToCell.C.
Member Function Documentation
TypeName ("fieldToCell")
Runtime type information.
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 117 of file fieldToCell.H.
References topoSetSource::CELLSETSOURCE.
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 153 of file fieldToCell.C.
References IOobject::AUTO_WRITE, Foam::endl(), fieldObject(), IOobject::filePath(), IOobject::headerClassName(), IOobject::headerOk(), Foam::mag(), mesh, IOobject::MUST_READ, fvMesh::time(), timeName, Time::timeName(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/meshTools/sets/cellSources/fieldToCell/fieldToCell.H
src/meshTools/sets/cellSources/fieldToCell/fieldToCell.C