OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Field< Type > Class Template Reference
Pre-declare SubField and related Field type.
Public Types
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes
static const char *const typeName
Friends
Ostream & operator (Ostream &, const Field< Type > &)
Ostream & operator (Ostream &, const tmp< Field< Type >> &)
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::Field< Type >
Pre-declare SubField and related Field type.
Generic templated field type.
Source files
Field.H
FieldFunctions.H
FieldFunctionsM.H
FieldMapper.H
FieldM.H
Field.C
FieldFunctions.C
FieldFunctionsM.C
Definition at line 57 of file Field.H.
Member Typedef Documentation
typedef pTraits<Type>::cmptType cmptType
Component type.
Definition at line 86 of file Field.H.
typedef SubField<Type> subField
Declare type of subField.
Definition at line 89 of file Field.H.
Constructor & Destructor Documentation
Field ()
Construct null.
Used for temporary fields which are initialised after construction
Definition at line 42 of file Field.C.
Referenced by Field< Type >::Field(), and Field< Foam::Vector2D >::null().
Field (const label size) explicit
Construct given size.
Used for temporary fields which are initialised after construction
Definition at line 49 of file Field.C.
Field (const label size, const Type & t)
Construct given size and initial value.
Definition at line 56 of file Field.C.
Field (const label size, const zero)
Construct given size and initialed to zero.
Definition at line 63 of file Field.C.
References Field< Type >::Field().
Field (const UList< Type > & list) explicit
Construct as copy of a UList<Type>
Definition at line 241 of file Field.C.
Field (const Xfer< List< Type >> & f) explicit
Construct by transferring the List contents.
Definition at line 227 of file Field.C.
Field (const UList< Type > & mapF, const labelUList & mapAddressing)
Construct by 1 to 1 mapping from the given field.
Definition at line 71 of file Field.C.
References Field< Type >::Field(), and Field< Type >::map().
Field (const tmp< Field< Type >> & tmapF, const labelUList & mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Definition at line 84 of file Field.C.
References Field< Type >::Field(), and Field< Type >::map().
Field (const UList< Type > & mapF, const labelListList & mapAddressing, const scalarListList & weights)
Construct by interpolative mapping from the given field.
Definition at line 97 of file Field.C.
References Field< Type >::Field(), and Field< Type >::map().
Field (const tmp< Field< Type >> & tmapF, const labelListList & mapAddressing, const scalarListList & weights)
Construct by interpolative mapping from the given tmp field.
Definition at line 111 of file Field.C.
References Field< Type >::Field(), and Field< Type >::map().
Field (const UList< Type > & mapF, const FieldMapper & map, const bool applyFlip = true)
Construct by mapping from the given field.
Definition at line 125 of file Field.C.
References Field< Type >::Field(), and Field< Type >::map().
Field (const UList< Type > & mapF, const FieldMapper & map, const Type & defaultValue, const bool applyFlip = true)
Construct by mapping from the given field.
Definition at line 139 of file Field.C.
References Field< Type >::Field(), and Field< Type >::map().
Field (const UList< Type > & mapF, const FieldMapper & map, const UList< Type > & defaultValues, const bool applyFlip = true)
Construct by mapping from the given field.
Definition at line 154 of file Field.C.
References Field< Type >::Field(), and Field< Type >::map().
Field (const tmp< Field< Type >> & tmapF, const FieldMapper & map, const bool applyFlip = true)
Construct by mapping from the given tmp field.
Definition at line 169 of file Field.C.
References Field< Type >::Field(), and Field< Type >::map().
Field (const tmp< Field< Type >> & tmapF, const FieldMapper & map, const Type & defaultValue, const bool applyFlip = true)
Construct by mapping from the given tmp field. Supplied uniform.
value for unmapped items
Definition at line 183 of file Field.C.
References Field< Type >::Field(), and Field< Type >::map().
Field (const tmp< Field< Type >> & tmapF, const FieldMapper & map, const UList< Type > & defaultValues, const bool applyFlip = true)
Construct by mapping from the given tmp field. Supplied values.
for unmapped items
Definition at line 198 of file Field.C.
References Field< Type >::map().
Field (const Field< Type > & f)
Construct as copy.
Definition at line 212 of file Field.C.
Field (Field< Type > & f, bool reuse)
Construct as copy or re-use as specified.
Definition at line 220 of file Field.C.
Field (const Xfer< Field< Type >> & f)
Construct by transferring the Field contents.
Definition at line 234 of file Field.C.
Field (const tmp< Field< Type >> & tf)
Construct as copy of tmp<Field>
Definition at line 249 of file Field.C.
References tf.
Field (Istream & is)
Construct from Istream.
Definition at line 259 of file Field.C.
References Field< Type >::Field().
Field (const word & keyword, const dictionary & dict, const label size)
Construct from a dictionary entry.
Definition at line 267 of file Field.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, token::info(), IOWarningInFunction, token::isWord(), dictionary::lookup(), Field< Type >::operator=(), Istream::putBack(), s(), List< Type >::setSize(), List< Type >::size(), IOstream::version(), and token::wordToken().
Member Function Documentation
static const Field<Type>& null () inline static
Return a null field.
Definition at line 100 of file Field.H.
Foam::tmp< Foam::Field< Type > > clone () const
Clone.
Definition at line 341 of file Field.C.
References Field< Type >::map().
Referenced by Field< Foam::Vector2D >::null().
static tmp<Field<Type> > NewCalculatedType (const Field< Type2 > & f) inline static
Return a pointer to a new calculatedFvPatchFieldField created on.
freestore without setting patchField values
Definition at line 238 of file Field.H.
void map (const UList< Type > & mapF, const labelUList & mapAddressing)
1 to 1 map from the given field
Definition at line 351 of file Field.C.
References f(), forAll, List< Type >::setSize(), List< Type >::size(), and UList< T >::size().
Referenced by Field< Type >::autoMap(), Field< Type >::clone(), Field< Type >::Field(), Field< Type >::map(), Field< Foam::Vector2D >::NewCalculatedType(), Field< Foam::Vector2D >::null(), and polyMesh::updateMesh().
void map (const tmp< Field< Type >> & tmapF, const labelUList & mapAddressing)
1 to 1 map from the given tmp field
Definition at line 380 of file Field.C.
References Field< Type >::map().
void map (const UList< Type > & mapF, const labelListList & mapAddressing, const scalarListList & weights)
Interpolative map from the given field.
Definition at line 392 of file Field.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Field< Type >::map(), List< Type >::setSize(), List< Type >::size(), List< T >::size(), and Foam::Zero.
void map (const tmp< Field< Type >> & tmapF, const labelListList & mapAddressing, const scalarListList & weights)
Interpolative map from the given tmp field.
Definition at line 429 of file Field.C.
References Field< Type >::map().
void map (const UList< Type > & mapF, const FieldMapper & map, const bool applyFlip = true)
Map from the given field.
Definition at line 442 of file Field.C.
References FieldMapper::addressing(), FieldMapper::direct(), FieldMapper::directAddressing(), mapDistributeBase::distribute(), FieldMapper::distributed(), FieldMapper::distributeMap(), Foam::isNull(), Field< Type >::map(), Foam::notNull(), List< Type >::setSize(), FieldMapper::size(), List< T >::size(), UList< T >::size(), List< Type >::transfer(), and FieldMapper::weights().
void map (const tmp< Field< Type >> & tmapF, const FieldMapper & map, const bool applyFlip = true)
Map from the given tmp field.
Definition at line 501 of file Field.C.
References Field< Type >::autoMap(), and Field< Type >::map().
void autoMap (const FieldMapper & map, const bool applyFlip = true)
Map from self.
Definition at line 514 of file Field.C.
References FieldMapper::addressing(), FieldMapper::direct(), FieldMapper::directAddressing(), mapDistributeBase::distribute(), FieldMapper::distributed(), FieldMapper::distributeMap(), Foam::isNull(), Field< Type >::map(), Foam::notNull(), Field< Type >::rmap(), List< Type >::setSize(), FieldMapper::size(), List< T >::size(), UList< T >::size(), and List< Type >::transfer().
Referenced by nutkRoughWallFunctionFvPatchScalarField::autoMap(), nutkAtmRoughWallFunctionFvPatchScalarField::autoMap(), pressureInletOutletVelocityFvPatchVectorField::autoMap(), atmBoundaryLayer::autoMap(), Field< Type >::map(), Field< Foam::Vector2D >::NewCalculatedType(), MapInternalField< Type, MeshMapper, volMesh >::operator()(), MapInternalField< Type, MeshMapper, surfaceMesh >::operator()(), and MapInternalField< Type, MeshMapper, pointMesh >::operator()().
void rmap (const UList< Type > & mapF, const labelUList & mapAddressing)
1 to 1 reverse-map from the given field
Definition at line 577 of file Field.C.
References f(), and forAll.
Referenced by extendedEdgeMesh::add(), Field< Type >::autoMap(), extendedEdgeMesh::flipNormals(), fvMeshAdder::MapSurfaceFields(), fvMeshAdder::MapVolFields(), Field< Foam::Vector2D >::NewCalculatedType(), fvFieldReconstructor::reconstructFvVolumeField(), fvFieldReconstructor::reconstructFvVolumeInternalField(), nutkRoughWallFunctionFvPatchScalarField::rmap(), nutkAtmRoughWallFunctionFvPatchScalarField::rmap(), pressureInletOutletVelocityFvPatchVectorField::rmap(), atmBoundaryLayer::rmap(), and Field< Type >::rmap().
void rmap (const tmp< Field< Type >> & tmapF, const labelUList & mapAddressing)
1 to 1 reverse-map from the given tmp field
Definition at line 598 of file Field.C.
References Field< Type >::rmap().
void rmap (const UList< Type > & mapF, const labelUList & mapAddressing, const UList< scalar > & weights)
Interpolative reverse map from the given field.
Definition at line 610 of file Field.C.
References f(), forAll, Field< Type >::rmap(), and Foam::Zero.
void rmap (const tmp< Field< Type >> & tmapF, const labelUList & mapAddressing, const UList< scalar > & weights)
Interpolative reverse map from the given tmp field.
Definition at line 629 of file Field.C.
References Field< Type >::rmap().
void negate ()
Negate this field.
Definition at line 641 of file Field.C.
References Field< Type >::component(), and TFOR_ALL_F_OP_OP_F.
Referenced by lduMatrix::negate(), and Field< Foam::Vector2D >::NewCalculatedType().
Foam::tmp< Foam::Field< typename Foam::Field< Type >::cmptType > > component (const direction d) const
Return a component field of the field.
Definition at line 650 of file Field.C.
References Foam::component(), tmp< T >::ref(), Field< Type >::replace(), and List< Type >::size().
Referenced by cylindricalCS::globalToLocal(), cylindricalCS::localToGlobal(), Field< Type >::negate(), Field< Foam::Vector2D >::NewCalculatedType(), faceSource::processSameTypeValues(), cellSource::processValues(), fvMatrix< Type >::residual(), basicSymmetryFvPatchField< Type >::snGradTransformDiag(), fixedNormalSlipFvPatchField< Type >::snGradTransformDiag(), partialSlipFvPatchField< Type >::snGradTransformDiag(), fvMatrix< Type >::solveSegregated(), dynamicInkJetFvMesh::update(), componentDisplacementMotionSolver::updateMesh(), regionSizeDistribution::write(), and ensightPart::writeField().
void replace (const direction d, const UList< cmptType > & sf)
Replace a component field of the field.
Definition at line 662 of file Field.C.
References TFOR_ALL_F_OP_FUNC_S_F.
Referenced by Field< Type >::component(), velocityComponentLaplacianFvMotionSolver::curPoints(), displacementComponentLaplacianFvMotionSolver::curPoints(), fft::forwardTransform(), cylindricalCS::globalToLocal(), cylindricalCS::localToGlobal(), Field< Foam::Vector2D >::NewCalculatedType(), Field< Type >::replace(), fvMatrix< Type >::residual(), fft::reverseTransform(), dynamicInkJetFvMesh::update(), and DimensionedField< Type, GeoMesh >::~DimensionedField().
void replace (const direction d, const tmp< Field< cmptType >> & tsf)
Replace a component field of the field.
Definition at line 674 of file Field.C.
References Field< Type >::replace().
void replace (const direction d, const cmptType & c)
Replace a component field of the field.
Definition at line 686 of file Field.C.
References Field< Type >::replace(), and TFOR_ALL_F_OP_FUNC_S_S.
VSForm block (const label start) const
Definition at line 698 of file Field.C.
References UList< Type >::operator[]().
Referenced by rigidBodyModel::forwardDynamics(), rigidBodyModel::forwardDynamicsCorrection(), Pxyz::jcalc(), Rzyx::jcalc(), Rxyz::jcalc(), Ryxz::jcalc(), Rs::jcalc(), Field< Foam::Vector2D >::NewCalculatedType(), and joint::unitQuaternion().
Foam::tmp< Foam::Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
Definition at line 710 of file Field.C.
References tmp< T >::ref(), List< Type >::size(), and T.
Referenced by Field< Foam::Vector2D >::NewCalculatedType(), cylindrical::transformTensor(), filmPyrolysisTemperatureCoupledFvPatchScalarField::updateCoeffs(), and energyRegionCoupledFvPatchScalarField::updateInterfaceMatrix().
void writeEntry (const word & keyword, Ostream & os) const
Write the field as a dictionary entry.
Definition at line 719 of file Field.C.
References token::END_STATEMENT, Foam::endl(), forAll, UList< Type >::operator[](), List< Type >::size(), UList< T >::writeEntry(), and Ostream::writeKeyword().
Referenced by Field< Foam::Vector2D >::NewCalculatedType(), codedFixedValueFvPatchField< Type >::redirectPatchField(), codedFixedValuePointPatchField< Type >::redirectPatchField(), energyJumpFvPatchScalarField::write(), energyJumpAMIFvPatchScalarField::write(), surfaceSlipDisplacementFvPatchField< Type >::write(), alphatPhaseChangeWallFunctionFvPatchScalarField::write(), oscillatingVelocityPointPatchVectorField::write(), angularOscillatingDisplacementPointPatchVectorField::write(), angularOscillatingVelocityPointPatchVectorField::write(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write(), interstitialInletVelocityFvPatchVectorField::write(), alphaFixedPressureFvPatchScalarField::write(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::write(), sixDoFRigidBodyDisplacementPointPatchVectorField::write(), surfaceNormalFixedValueFvPatchVectorField::write(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::write(), MarshakRadiationFixedTemperatureFvPatchScalarField::write(), wallHeatTransferFvPatchScalarField::write(), nutkRoughWallFunctionFvPatchScalarField::write(), nutkAtmRoughWallFunctionFvPatchScalarField::write(), pressureInletOutletVelocityFvPatchVectorField::write(), totalTemperatureFvPatchScalarField::write(), SRFVelocityFvPatchVectorField::write(), inletOutletTotalTemperatureFvPatchScalarField::write(), pressureDirectedInletVelocityFvPatchVectorField::write(), prghPressureFvPatchScalarField::write(), pressureDirectedInletOutletVelocityFvPatchVectorField::write(), turbulentHeatFluxTemperatureFvPatchScalarField::write(), prghTotalPressureFvPatchScalarField::write(), atmBoundaryLayer::write(), and totalPressureFvPatchScalarField::write().
void operator= (const Field< Type > & rhs)
Definition at line 757 of file Field.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< T >::operator=().
Referenced by CompactIOField< T, BaseType >::CompactIOField(), Field< Type >::Field(), IOField< Type >::IOField(), Field< Foam::Vector2D >::NewCalculatedType(), IOField< Type >::operator=(), CompactIOField< T, BaseType >::operator=(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::operator=(), DimensionedField< Type, GeoMesh >::operator=(), and oscillatingDisplacementPointPatchVectorField::updateCoeffs().
void operator= (const UList< Type > & rhs)
Definition at line 778 of file Field.C.
References List< T >::operator=().
void operator= (const SubField< Type > & rhs)
Definition at line 771 of file Field.C.
References List< T >::operator=().
void operator= (const tmp< Field< Type >> &)
void operator= (const Type & t)
Definition at line 799 of file Field.C.
References List< T >::operator=().
void operator= (const zero)
Definition at line 806 of file Field.C.
References List< T >::operator=(), and Foam::Zero.
void operator= (const VectorSpace< Form, Cmpt, nCmpt > & vs)
Definition at line 814 of file Field.C.
References TFOR_ALL_F_OP_S.
void operator+= (const UList< Type > & f)
Definition at line 841 of file Field.C.
Referenced by Field< Foam::Vector2D >::NewCalculatedType().
void operator+= (const tmp< Field< Type >> & tf)
Definition at line 841 of file Field.C.
void operator-= (const UList< Type > & f)
Definition at line 842 of file Field.C.
Referenced by Field< Foam::Vector2D >::NewCalculatedType().
void operator-= (const tmp< Field< Type >> & tf)
Definition at line 842 of file Field.C.
void operator*= (const UList< scalar > & f)
Definition at line 843 of file Field.C.
Referenced by Field< Foam::Vector2D >::NewCalculatedType().
void operator*= (const tmp< Field< scalar >> & tf)
Definition at line 843 of file Field.C.
void operator/= (const UList< scalar > & f)
Definition at line 844 of file Field.C.
Referenced by Field< Foam::Vector2D >::NewCalculatedType().
void operator/= (const tmp< Field< scalar >> & tf)
Definition at line 844 of file Field.C.
void operator+= (const Type & t)
Definition at line 841 of file Field.C.
void operator-= (const Type & t)
Definition at line 842 of file Field.C.
void operator*= (const scalar & t)
Definition at line 843 of file Field.C.
void operator/= (const scalar & t)
Definition at line 844 of file Field.C.
References f(), and tf.
void operator= (const tmp< Field< Type > > & rhs)
Definition at line 785 of file Field.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< T >::operator=().
Friends And Related Function Documentation
Ostream& operator (Ostream & , const Field< Type > &) friend
Ostream& operator (Ostream & , const tmp< Field< Type >> &) friend
Member Data Documentation
const char *const typeName static
Definition at line 94 of file Field.H.
Referenced by probes::appendFieldGroup(), fvMeshDistribute::distribute(), basicThermo::heBoundaryTypes(), IOField< Type >::IOField(), Foam::MapGeometricFields(), and regionSizeDistribution::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/Fields/Field/Field.H
src/OpenFOAM/fields/Fields/Field/Field.C