OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldCoordinateSystemTransform Class Reference
FunctionObjects » Field function objects
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
Public Member Functions
TypeName ("fieldCoordinateSystemTransform")
Runtime type information.
fieldCoordinateSystemTransform (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~fieldCoordinateSystemTransform ()
Destructor.
virtual bool read (const dictionary &)
Read the input data.
virtual bool execute (const bool postProcess=false)
Execute, currently does nothing.
virtual bool write (const bool postProcess=false)
Write.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
template<class Type >
void transform (const word &fieldName) const
template<class Type >
void transformField (const Type &field) const
Protected Attributes
const objectRegistry & obr_
Reference to the objectRegistry.
wordList fieldSet_
Fields to transform.
coordinateSystem coordSys_
Co-ordinate system to transform to.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
Example of function object specification:
fieldCoordinateSystemTransform1
{
    type        fieldCoordinateSystemTransform;
    libs ("libfieldFunctionObjects.so");
    ...
    fields
    (
        U
        UMean
        UPrime2Mean
    );
    coordinateSystem
    {
        origin  (0.001  0       0);
        e1      (1      0.15    0);
        e3      (0      0      -1);
    }
}
Function object usage
Property Description Required Default value
type type name: fieldCoordinateSystemTransform yes
fields list of fields to be transformed yes
coordinateSystem local co-ordinate system yes
See also
Foam::functionObject Foam::coordinateSystem
Source files
fieldCoordinateSystemTransform.H
fieldCoordinateSystemTransform.C
fieldCoordinateSystemTransformTemplates.C
Definition at line 116 of file fieldCoordinateSystemTransform.H.
Constructor & Destructor Documentation
fieldCoordinateSystemTransform (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 52 of file fieldCoordinateSystemTransform.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::nl, Foam::read(), Foam::type(), and fieldCoordinateSystemTransform::~fieldCoordinateSystemTransform().
~fieldCoordinateSystemTransform () virtual
Destructor.
Definition at line 86 of file fieldCoordinateSystemTransform.C.
References fieldCoordinateSystemTransform::read().
Referenced by fieldCoordinateSystemTransform::fieldCoordinateSystemTransform().
Member Function Documentation
void transform (const word & fieldName) const protected
Definition at line 78 of file fieldCoordinateSystemTransformTemplates.C.
References Foam::endl(), Foam::Info, and Foam::type().
Referenced by fieldCoordinateSystemTransform::transformField().
void transformField (const Type & field) const protected
Definition at line 36 of file fieldCoordinateSystemTransformTemplates.C.
References Foam::endl(), Foam::Info, Foam::nl, R, Foam::transform(), fieldCoordinateSystemTransform::transform(), and Ostream::write().
TypeName ("fieldCoordinateSystemTransform")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the input data.
Implements functionObject.
Definition at line 93 of file fieldCoordinateSystemTransform.C.
References fieldCoordinateSystemTransform::execute(), and dictionary::lookup().
Referenced by fieldCoordinateSystemTransform::~fieldCoordinateSystemTransform().
bool execute (const bool postProcess = false) virtual
Execute, currently does nothing.
Implements functionObject.
Definition at line 104 of file fieldCoordinateSystemTransform.C.
References forAll, Foam::Info, Foam::name(), Foam::nl, Foam::type(), and fieldCoordinateSystemTransform::write().
Referenced by fieldCoordinateSystemTransform::read().
bool write (const bool postProcess = false) virtual
Write.
Implements functionObject.
Definition at line 125 of file fieldCoordinateSystemTransform.C.
References Foam::endl(), forAll, Foam::Info, Foam::name(), IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by fieldCoordinateSystemTransform::execute().
Member Data Documentation
const objectRegistry& obr_ protected
Reference to the objectRegistry.
Definition at line 125 of file fieldCoordinateSystemTransform.H.
wordList fieldSet_ protected
Fields to transform.
Definition at line 128 of file fieldCoordinateSystemTransform.H.
coordinateSystem coordSys_ protected
Co-ordinate system to transform to.
Definition at line 131 of file fieldCoordinateSystemTransform.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransform.H
src/postProcessing/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransform.C
src/postProcessing/functionObjects/field/fieldCoordinateSystemTransform/fieldCoordinateSystemTransformTemplates.C