OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fieldValue Class Reference
Public Member Functions
TypeName ("fieldValue")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, fieldValue, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict),(name, obr, dict))
fieldValue (const word &name, const Time &runTime, const dictionary &dict, const word &valueType)
Construct from Time and dictionary.
fieldValue (const word &name, const objectRegistry &obr, const dictionary &dict, const word &valueType)
Construct from objectRegistry and dictionary.
virtual ~fieldValue ()
Destructor.
const dictionary & dict () const
Return the reference to the construction dictionary.
const word & sourceName () const
Return the source name.
const wordList & fields () const
Return the list of field names.
const Switch & valueOutput () const
Return the output field values flag.
const fvMesh & mesh () const
Helper function to return the reference to the mesh.
const dictionary & resultDict () const
Return access to the latest set of results.
virtual bool read (const dictionary &dict)
Read from dictionary.
virtual bool execute (const bool postProcess=false)
Execute.
virtual bool write (const bool postProcess=false)
Write to screen/file.
Public Member Functions inherited from writeFiles
writeFiles (const word &name, const Time &time, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFiles (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from writeFile
writeFile (const word &name, const Time &t, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFile (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Static Public Member Functions
static autoPtr< fieldValue > New (const word &name, const objectRegistry &obr, const dictionary &dict, const bool output=true)
Return a reference to the selected fieldValue.
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Protected Member Functions
template<class Type >
void combineFields (Field< Type > &field)
Combine fields from all processor domains into single field.
template<class Type >
void combineFields (tmp< Field< Type >> &)
Combine fields from all processor domains into single field.
Protected Member Functions inherited from writeFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
writeFiles (const writeFiles &)
Disallow default bitwise copy construct.
void operator= (const writeFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from writeFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void writeFileHeader (const label i=0)
File header information.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
writeFile (const writeFile &)
Disallow default bitwise copy construct.
void operator= (const writeFile &)
Disallow default bitwise assignment.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
dictionary dict_
Construction dictionary.
word sourceName_
Name of source object.
wordList fields_
List of field names to operate on.
Switch valueOutput_
Output field values flag.
dictionary resultDict_
Results dictionary for external access of results.
Protected Attributes inherited from writeFile
const word prefix_
Prefix.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Public Attributes inherited from regionFunctionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
Definition at line 59 of file fieldValue.H.
Constructor & Destructor Documentation
fieldValue (const word & name, const Time & runTime, const dictionary & dict, const word & valueType)
Construct from Time and dictionary.
Definition at line 45 of file fieldValue.C.
References Foam::read().
fieldValue (const word & name, const objectRegistry & obr, const dictionary & dict, const word & valueType)
Construct from objectRegistry and dictionary.
Definition at line 65 of file fieldValue.C.
References Foam::read().
~fieldValue () virtual
Destructor.
Definition at line 86 of file fieldValue.C.
Member Function Documentation
void combineFields (Field< Type > & field) protected
Combine fields from all processor domains into single field.
Definition at line 33 of file fieldValueTemplates.C.
References Pstream::gatherList(), UPstream::master(), UPstream::myProcNo(), and UPstream::nProcs().
Referenced by fieldValue::combineFields().
void combineFields (tmp< Field< Type >> & field) protected
Combine fields from all processor domains into single field.
Definition at line 54 of file fieldValueTemplates.C.
References fieldValue::combineFields().
TypeName ("fieldValue")
Run-time type information.
declareRunTimeSelectionTable (autoPtr , fieldValue , dictionary , (const word &name, const objectRegistry &obr, const dictionary &dict) , (name, obr, dict))
Foam::autoPtr< Foam::functionObjects::fieldValue > New (const word & name, const objectRegistry & obr, const dictionary & dict, const bool output = true) static
Return a reference to the selected fieldValue.
Definition at line 32 of file fieldValueNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), Foam::name(), and Foam::nl.
Referenced by fieldValueDelta::read().
const Foam::dictionary & dict () const inline
Return the reference to the construction dictionary.
Definition at line 31 of file fieldValueI.H.
References fieldValue::dict_.
const Foam::word & sourceName () const inline
Return the source name.
Definition at line 37 of file fieldValueI.H.
References fieldValue::sourceName_.
const Foam::wordList & fields () const inline
Return the list of field names.
Definition at line 43 of file fieldValueI.H.
References fieldValue::fields_.
const Foam::Switch & valueOutput () const inline
Return the output field values flag.
Definition at line 50 of file fieldValueI.H.
References fieldValue::valueOutput_.
const Foam::fvMesh & mesh () const inline
Helper function to return the reference to the mesh.
Definition at line 56 of file fieldValueI.H.
References regionFunctionObject::obr_.
const Foam::dictionary & resultDict () const inline
Return access to the latest set of results.
Definition at line 63 of file fieldValueI.H.
References fieldValue::resultDict_.
bool read (const dictionary & dict) virtual
Read from dictionary.
Reimplemented from regionFunctionObject.
Reimplemented in faceSource, and cellSource.
Definition at line 92 of file fieldValue.C.
References dict, dictionary::lookup(), and regionFunctionObject::read().
Referenced by cellSource::read(), and faceSource::read().
bool execute (const bool postProcess = false) virtual
Execute.
Implements functionObject.
Definition at line 103 of file fieldValue.C.
bool write (const bool postProcess = false) virtual
Write to screen/file.
Reimplemented from writeFiles.
Reimplemented in faceSource, and cellSource.
Definition at line 109 of file fieldValue.C.
References Log, Foam::name(), Foam::nl, Foam::type(), and writeFiles::write().
Referenced by cellSource::write(), and faceSource::write().
Member Data Documentation
dictionary dict_ protected
Construction dictionary.
Definition at line 69 of file fieldValue.H.
Referenced by fieldValue::dict().
word sourceName_ protected
Name of source object.
Definition at line 72 of file fieldValue.H.
Referenced by fieldValue::sourceName().
wordList fields_ protected
List of field names to operate on.
Definition at line 75 of file fieldValue.H.
Referenced by fieldValue::fields().
Switch valueOutput_ protected
Output field values flag.
Definition at line 78 of file fieldValue.H.
Referenced by fieldValue::valueOutput().
dictionary resultDict_ protected
Results dictionary for external access of results.
Definition at line 81 of file fieldValue.H.
Referenced by fieldValue::resultDict().
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldValues/fieldValue/fieldValue.H
src/functionObjects/field/fieldValues/fieldValue/fieldValue.C
src/functionObjects/field/fieldValues/fieldValue/fieldValueI.H
src/functionObjects/field/fieldValues/fieldValue/fieldValueNew.C
src/functionObjects/field/fieldValues/fieldValue/fieldValueTemplates.C