OpenFOAM: fvMesh Class Reference
fvMesh Class Reference
Mesh data needed to do the Finite Volume discretisation.
Public Types
typedef fvMesh Mesh
typedef fvBoundaryMesh BoundaryMesh
Public Types inherited from polyMesh
enum readUpdateState { UNCHANGED, POINTS_MOVED, TOPO_CHANGE, TOPO_PATCH_CHANGE }
Enumeration defining the state of the mesh after a read update.
enum cellDecomposition { FACE_PLANES, FACE_CENTRE_TRIS, FACE_DIAG_TRIS, CELL_TETS }
Enumeration defining the decomposition of the cell for.
typedef polyMesh Mesh
typedef polyBoundaryMesh BoundaryMesh
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject * >
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase::iterator LListBase_iterator
typedef DLListBase::const_iterator LListBase_const_iterator
Public Member Functions
ClassName ("fvMesh")
fvMesh (const IOobject &io)
Construct from IOobject.
fvMesh (const IOobject &io, const Xfer< pointField > &points, const cellShapeList &shapes, const faceListList &boundaryFaces, const wordList &boundaryPatchNames, const PtrList< dictionary > &boundaryDicts, const word &defaultBoundaryPatchName, const word &defaultBoundaryPatchType, const bool syncPar=true)
Construct from cellShapes with boundary.
fvMesh (const IOobject &io, const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< labelList > &allOwner, const Xfer< labelList > &allNeighbour, const bool syncPar=true)
Construct from components without boundary.
fvMesh (const IOobject &io, const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< cellList > &cells, const bool syncPar=true)
Construct without boundary from cells rather than owner/neighbour.
virtual ~fvMesh ()
Destructor.
void addFvPatches (const List< polyPatch * > &, const bool validBoundary=true)
Add boundary patches. Constructor helper.
virtual readUpdateState readUpdate ()
Update the mesh based on the mesh files saved in time.
const Time & time () const
Return the top-level database.
virtual const objectRegistry & thisDb () const
Return the object registry - resolve conflict polyMesh/lduMesh.
const word & name () const
Return reference to name.
const fvBoundaryMesh & boundary () const
Return reference to boundary mesh.
virtual const lduAddressing & lduAddr () const
Return ldu addressing.
virtual lduInterfacePtrsList interfaces () const
Return a list of pointers for each patch.
virtual label comm () const
Return communicator used for parallel communication.
const labelUList & owner () const
Internal face owner.
const labelUList & neighbour () const
Internal face neighbour.
const DimensionedField< scalar, volMesh > & V () const
Return cell volumes.
const DimensionedField< scalar, volMesh > & V0 () const
Return old-time cell volumes.
const DimensionedField< scalar, volMesh > & V00 () const
Return old-old-time cell volumes.
tmp< DimensionedField< scalar, volMesh > > Vsc () const
Return sub-cycle cell volumes.
tmp< DimensionedField< scalar, volMesh > > Vsc0 () const
Return sub-cycl old-time cell volumes.
const surfaceVectorField & Sf () const
Return cell face area vectors.
const surfaceScalarField & magSf () const
Return cell face area magnitudes.
const surfaceScalarField & phi () const
Return cell face motion fluxes.
const volVectorField & C () const
Return cell centres as volVectorField.
const surfaceVectorField & Cf () const
Return face centres as surfaceVectorField.
tmp< surfaceVectorField > delta () const
Return face deltas as surfaceVectorField.
template<class Type >
pTraits< Type >::labelType validComponents () const
Return a labelType of valid component indicators.
void clearOut ()
Clear all geometry and addressing.
virtual void updateMesh (const mapPolyMesh &mpm)
Update mesh corresponding to the given map.
virtual tmp< scalarField > movePoints (const pointField &)
Move points, returns volumes swept by faces in motion.
virtual void mapFields (const mapPolyMesh &mpm)
Map all fields in time using given map.
void removeFvBoundary ()
Remove boundary patches. Warning: fvPatchFields hold ref to.
surfaceScalarField & setPhi ()
Return cell face motion fluxes.
DimensionedField< scalar, volMesh > & setV0 ()
Return old-time cell volumes.
virtual bool writeObjects (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write the underlying polyMesh and other data.
virtual bool write () const
Write mesh using IO settings from time.
bool operator!= (const fvMesh &) const
bool operator== (const fvMesh &) const
template<>
pTraits< sphericalTensor >::labelType validComponents () const
template<class Type >
Foam::pTraits< Type >::labelType validComponents () const
Public Member Functions inherited from polyMesh
TypeName ("polyMesh")
Runtime type information.
polyMesh (const IOobject &io)
Construct from IOobject.
polyMesh (const IOobject &io, const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< labelList > &owner, const Xfer< labelList > &neighbour, const bool syncPar=true)
Construct from IOobject or from components.
polyMesh (const IOobject &io, const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< cellList > &cells, const bool syncPar=true)
Construct without boundary with cells rather than owner/neighbour.
polyMesh (const IOobject &io, const Xfer< pointField > &points, const cellShapeList &shapes, const faceListList &boundaryFaces, const wordList &boundaryPatchNames, const wordList &boundaryPatchTypes, const word &defaultBoundaryPatchName, const word &defaultBoundaryPatchType, const wordList &boundaryPatchPhysicalTypes, const bool syncPar=true)
Construct from cell shapes.
polyMesh (const IOobject &io, const Xfer< pointField > &points, const cellShapeList &shapes, const faceListList &boundaryFaces, const wordList &boundaryPatchNames, const PtrList< dictionary > &boundaryDicts, const word &defaultBoundaryPatchName, const word &defaultBoundaryPatchType, const bool syncPar=true)
Construct from cell shapes with patch information in dictionary.
virtual ~polyMesh ()
Destructor.
virtual const fileName & dbDir () const
Override the objectRegistry dbDir for a single-region case.
fileName meshDir () const
Return the local mesh directory (dbDir()/meshSubDir)
const fileName & pointsInstance () const
Return the current instance directory for points.
const fileName & facesInstance () const
Return the current instance directory for faces.
void setInstance (const fileName &)
Set the instance for mesh files.
virtual const pointField & points () const
Return raw points.
virtual bool upToDatePoints (const regIOobject &io) const
Return true if io is up-to-date with points.
virtual void setUpToDatePoints (regIOobject &io) const
Set io to be up-to-date with points.
virtual const faceList & faces () const
Return raw faces.
virtual const labelList & faceOwner () const
Return face owner.
virtual const labelList & faceNeighbour () const
Return face neighbour.
virtual const pointField & oldPoints () const
Return old points for mesh motion.
const polyBoundaryMesh & boundaryMesh () const
Return boundary mesh.
const boundBox & bounds () const
Return mesh bounding box.
const Vector< label > & geometricD () const
Return the vector of geometric directions in mesh.
label nGeometricD () const
Return the number of valid geometric dimensions in the mesh.
const Vector< label > & solutionD () const
Return the vector of solved-for directions in mesh.
label nSolutionD () const
Return the number of valid solved-for dimensions in the mesh.
const labelList & tetBasePtIs () const
Return the tetBasePtIs.
const indexedOctree< treeDataCell > & cellTree () const
Return the cell search tree.
const pointZoneMesh & pointZones () const
Return point zone mesh.
const faceZoneMesh & faceZones () const
Return face zone mesh.
const cellZoneMesh & cellZones () const
Return cell zone mesh.
const globalMeshData & globalData () const
Return parallel info.
label comm () const
Return communicator used for parallel communication.
label & comm ()
Return communicator used for parallel communication.
const objectRegistry & thisDb () const
Return the object registry.
bool moving () const
Is mesh moving.
bool moving (const bool m)
Set the mesh to be moving.
bool topoChanging () const
Is mesh topology changing.
bool topoChanging (const bool c)
Set the mesh topology to be changing.
bool changing () const
Is mesh changing (topology changing and/or moving)
void resetMotion () const
Reset motion.
pointZoneMesh & pointZones ()
Return non-const access to the pointZones.
faceZoneMesh & faceZones ()
Return non-const access to the faceZones.
cellZoneMesh & cellZones ()
Return non-const access to the cellZones.
void addPatches (const List< polyPatch * > &, const bool validBoundary=true)
Add boundary patches.
void addZones (const List< pointZone * > &pz, const List< faceZone * > &fz, const List< cellZone * > &cz)
Add mesh zones.
void removeBoundary ()
Remove boundary patches.
void resetPrimitives (const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< labelList > &owner, const Xfer< labelList > &neighbour, const labelList &patchSizes, const labelList &patchStarts, const bool validBoundary=true)
Reset mesh primitive data. Assumes all patch info correct.
void clearGeom ()
Clear geometry.
void clearAddressing (const bool isMeshUpdate=false)
Clear addressing.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
void clearPrimitives ()
Clear primitive data (points, faces and cells)
void clearAdditionalGeom ()
Clear geometry not used for CFD (cellTree, tetBasePtIs)
void clearCellTree ()
Clear cell tree data.
void removeFiles (const fileName &instanceDir) const
Remove all files from mesh instance.
void removeFiles () const
Remove all files from mesh instance()
virtual bool checkFaceOrthogonality (const bool report=false, labelHashSet *setPtr=NULL) const
Check non-orthogonality.
virtual bool checkFaceSkewness (const bool report=false, labelHashSet *setPtr=NULL) const
Check face skewness.
virtual bool checkEdgeAlignment (const bool report, const Vector< label > &directions, labelHashSet *setPtr) const
Check edge alignment for 1D/2D cases.
virtual bool checkCellDeterminant (const bool report, labelHashSet *setPtr) const
virtual bool checkMeshMotion (const pointField &newPoints, const bool report=false, const bool detailedReport=false) const
Check mesh motion for correctness given motion points.
virtual bool checkFaceWeight (const bool report, const scalar minWeight=0.05, labelHashSet *setPtr=NULL) const
Check for face weights.
virtual bool checkVolRatio (const bool report, const scalar minRatio=0.01, labelHashSet *setPtr=NULL) const
Check for neighbouring cell volumes.
void findCellFacePt (const point &p, label &celli, label &tetFacei, label &tetPti) const
Find the cell, tetFacei and tetPti for point p.
void findTetFacePt (const label celli, const point &p, label &tetFacei, label &tetPti) const
Find the tetFacei and tetPti for point p in celli.
bool pointInCell (const point &p, label celli, const cellDecomposition=CELL_TETS) const
Test if point p is in the celli.
label findCell (const point &p, const cellDecomposition=CELL_TETS) const
Find cell enclosing this location and return index.
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write the objects.
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject * >
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash >> &)
Construct by transferring the parameter contents.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from primitiveMesh
ClassName ("primitiveMesh")
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Construct from components.
virtual ~primitiveMesh ()
Destructor.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Reset this primitiveMesh given the primitive array sizes.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList &cells)
Reset this primitiveMesh given the primitive array sizes and cells.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, const Xfer< cellList > &cells)
Reset this primitiveMesh given the primitive array sizes and cells.
label nPoints () const
label nEdges () const
label nInternalFaces () const
label nFaces () const
label nCells () const
label nInternalPoints () const
Points not on boundary.
label nInternal0Edges () const
Internal edges (i.e. not on boundary face) using.
label nInternal1Edges () const
Internal edges using 0 or 1 boundary point.
label nInternalEdges () const
Internal edges using 0,1 or 2 boundary points.
const cellShapeList & cellShapes () const
Return cell shapes.
const edgeList & edges () const
Return mesh edges. Uses calcEdges.
const labelListList & cellCells () const
const labelListList & edgeCells () const
const labelListList & pointCells () const
const cellList & cells () const
const labelListList & edgeFaces () const
const labelListList & pointFaces () const
const labelListList & cellEdges () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointPoints () const
const labelListList & cellPoints () const
const vectorField & cellCentres () const
const vectorField & faceCentres () const
const scalarField & cellVolumes () const
const vectorField & faceAreas () const
tmp< scalarField > movePoints (const pointField &p, const pointField &oldP)
Move points, returns volumes swept by faces in motion.
bool isInternalFace (const label faceIndex) const
Return true if given face label is internal to the mesh.
virtual bool checkUpperTriangular (const bool report=false, labelHashSet *setPtr=NULL) const
Check face ordering.
virtual bool checkCellsZipUp (const bool report=false, labelHashSet *setPtr=NULL) const
Check cell zip-up.
virtual bool checkFaceVertices (const bool report=false, labelHashSet *setPtr=NULL) const
Check uniqueness of face vertices.
virtual bool checkPoints (const bool report=false, labelHashSet *setPtr=NULL) const
Check for unused points.
virtual bool checkFaceFaces (const bool report=false, labelHashSet *setPtr=NULL) const
Check face-face connectivity.
virtual bool checkClosedBoundary (const bool report=false) const
Check boundary for closedness.
virtual bool checkClosedCells (const bool report=false, labelHashSet *setPtr=NULL, labelHashSet *highAspectSetPtr=NULL, const Vector< label > &solutionD=Vector< label >::one) const
Check cells for closedness.
virtual bool checkFaceAreas (const bool report=false, labelHashSet *setPtr=NULL) const
Check for negative face areas.
virtual bool checkCellVolumes (const bool report=false, labelHashSet *setPtr=NULL) const
Check for negative cell volumes.
virtual bool checkFacePyramids (const bool report=false, const scalar minPyrVol=-SMALL, labelHashSet *setPtr=NULL) const
Check face pyramid volume.
virtual bool checkFaceAngles (const bool report=false, const scalar maxSin=10, labelHashSet *setPtr=NULL) const
Check face angles.
virtual bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage: decompose face and check ratio between.
virtual bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet *setPtr=NULL) const
Check for point-point-nearness,.
virtual bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet *setPtr=NULL) const
Check edge length.
virtual bool checkConcaveCells (const bool report=false, labelHashSet *setPtr=NULL) const
Check for concave cells by the planes of faces.
virtual bool checkTopology (const bool report=false) const
Check mesh topology for correctness.
virtual bool checkGeometry (const bool report=false) const
Check mesh geometry (& implicitly topology) for correctness.
virtual bool checkMesh (const bool report=false) const
Check mesh for correctness. Returns false for no error.
bool pointInCellBB (const point &p, label celli, scalar inflationFraction=0) const
Return true if the point in the cell bounding box.
bool pointInCell (const point &p, label celli) const
Return true if the point is in the cell.
label findNearestCell (const point &location) const
Find the cell with the nearest cell centre to location.
label findCell (const point &location) const
Find cell enclosing this location (-1 if not in mesh)
void printAllocated () const
Print a list of all the currently allocated mesh data.
bool hasCellShapes () const
bool hasEdges () const
bool hasCellCells () const
bool hasEdgeCells () const
bool hasPointCells () const
bool hasCells () const
bool hasEdgeFaces () const
bool hasPointFaces () const
bool hasCellEdges () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointPoints () const
bool hasCellPoints () const
bool hasCellCentres () const
bool hasFaceCentres () const
bool hasCellVolumes () const
bool hasFaceAreas () const
const labelList & cellCells (const label celli, DynamicList< label > &) const
cellCells using cells.
const labelList & cellCells (const label celli) const
const labelList & cellPoints (const label celli, DynamicList< label > &) const
cellPoints using cells
const labelList & cellPoints (const label celli) const
const labelList & pointCells (const label pointi, DynamicList< label > &) const
pointCells using pointFaces
const labelList & pointCells (const label pointi) const
const labelList & pointPoints (const label pointi, DynamicList< label > &) const
pointPoints using edges, pointEdges
const labelList & pointPoints (const label pointi) const
const labelList & faceEdges (const label facei, DynamicList< label > &) const
faceEdges using pointFaces, edges, pointEdges
const labelList & faceEdges (const label facei) const
const labelList & edgeFaces (const label edgeI, DynamicList< label > &) const
edgeFaces using pointFaces, edges, pointEdges
const labelList & edgeFaces (const label edgeI) const
const labelList & edgeCells (const label edgeI, DynamicList< label > &) const
edgeCells using pointFaces, edges, pointEdges
const labelList & edgeCells (const label edgeI) const
const labelList & cellEdges (const label celli, DynamicList< label > &) const
cellEdges using cells, pointFaces, edges, pointEdges
const labelList & cellEdges (const label celli) const
void clearGeom ()
Clear geometry.
void clearAddressing ()
Clear topological data.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Public Member Functions inherited from lduMesh
TypeName ("lduMesh")
Runtime type information.
virtual ~lduMesh ()
Destructor.
template<class T , class BinaryOp >
void reduce (T &Value, const BinaryOp &bop) const
Helper: reduce with current communicator.
InfoProxy< lduMesh > info () const
Return info proxy.
Public Member Functions inherited from surfaceInterpolation
ClassName ("surfaceInterpolation")
surfaceInterpolation (const fvMesh &)
Construct given an fvMesh.
~surfaceInterpolation ()
Destructor.
const surfaceScalarField & weights () const
Return reference to linear difference weighting factors.
const surfaceScalarField & deltaCoeffs () const
Return reference to cell-centre difference coefficients.
const surfaceScalarField & nonOrthDeltaCoeffs () const
Return reference to non-orthogonal cell-centre difference.
const surfaceVectorField & nonOrthCorrectionVectors () const
Return reference to non-orthogonality correction vectors.
bool movePoints ()
Do what is neccessary if the mesh has moved.
Public Member Functions inherited from fvSchemes
fvSchemes (const objectRegistry &obr)
Construct for objectRegistry.
const dictionary & schemesDict () const
ITstream & ddtScheme (const word &name) const
ITstream & d2dt2Scheme (const word &name) const
ITstream & interpolationScheme (const word &name) const
ITstream & divScheme (const word &name) const
ITstream & gradScheme (const word &name) const
ITstream & snGradScheme (const word &name) const
ITstream & laplacianScheme (const word &name) const
void setFluxRequired (const word &name) const
bool fluxRequired (const word &name) const
bool steady () const
Return true if the default ddtScheme is steadyState.
bool transient () const
Return true if the default ddtScheme is not steadyState.
bool read ()
Read the fvSchemes.
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
iterator begin ()
const_iterator begin () const
const iterator & end ()
const const_iterator & end () const
const_iterator cbegin () const
const const_iterator & cend () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Public Member Functions inherited from fvSolution
fvSolution (const objectRegistry &obr)
Construct for objectRegistry.
Public Member Functions inherited from solution
solution (const objectRegistry &obr, const fileName &dictName)
Construct for given objectRegistry and dictionary.
bool cache (const word &name) const
Return true if the given field should be cached.
bool relaxField (const word &name) const
Return true if the relaxation factor is given for the field.
bool relaxEquation (const word &name) const
Return true if the relaxation factor is given for the equation.
scalar fieldRelaxationFactor (const word &name) const
Return the relaxation factor for the given field.
scalar equationRelaxationFactor (const word &name) const
Return the relaxation factor for the given eqation.
const dictionary & solutionDict () const
Return the selected sub-dictionary of solvers if the "select".
const dictionary & solverDict (const word &name) const
Return the solver controls dictionary for the given field.
const dictionary & solver (const word &name) const
Return the solver controls dictionary for the given field.
bool read ()
Read the solution dictionary.
Public Member Functions inherited from data
data (const objectRegistry &obr)
Construct for objectRegistry.
const dictionary & solverPerformanceDict () const
Return the dictionary of solver performance data.
template<class Type >
void setSolverPerformance (const word &name, const SolverPerformance< Type > &) const
Add/set the solverPerformance entry for the named field.
template<class Type >
void setSolverPerformance (const SolverPerformance< Type > &) const
Add/set the solverPerformance entry, using its fieldName.
Additional Inherited Members
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Member Functions inherited from primitiveMesh
static void calcCells (cellList &, const labelUList &own, const labelUList &nei, const label nCells=-1)
Helper function to calculate cell-face addressing from.
static bool calcPointOrder (label &nInternalPoints, labelList &pointMap, const faceList &, const label nInternalFaces, const label nPoints)
Helper function to calculate point ordering. Returns true.
static scalar setClosedThreshold (const scalar)
Set the closedness ratio warning threshold.
static scalar setAspectThreshold (const scalar)
Set the aspect ratio warning threshold.
static scalar setNonOrthThreshold (const scalar)
Set the non-orthogonality warning threshold in degrees.
static scalar setSkewThreshold (const scalar)
Set the skewness warning threshold as percentage.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Static Public Member Functions inherited from solution
static label upgradeSolverDict (dictionary &dict, const bool verbose=true)
Update from older solver controls syntax.
template<class FieldType >
static void cachePrintMessage (const char *message, const word &name, const FieldType &vf)
Helper for printing cache message.
Static Public Attributes inherited from polyMesh
static word defaultRegion = "region0"
Return the default region name.
static word meshSubDir = "polyMesh"
Return the mesh sub-directory name (usually "polyMesh")
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Static Public Attributes inherited from primitiveMesh
static const unsigned cellsPerEdge_ = 4
Estimated number of cells per edge.
static const unsigned cellsPerPoint_ = 8
Estimated number of cells per point.
static const unsigned facesPerCell_ = 6
Estimated number of faces per cell.
static const unsigned facesPerEdge_ = 4
Estimated number of faces per edge.
static const unsigned facesPerPoint_ = 12
Estimated number of faces per point.
static const unsigned edgesPerCell_ = 12
Estimated number of edges per cell.
static const unsigned edgesPerFace_ = 4
Estimated number of edges per cell.
static const unsigned edgesPerPoint_ = 6
Estimated number of edges per point.
static const unsigned pointsPerCell_ = 8
Estimated number of points per cell.
static const unsigned pointsPerFace_ = 4
Estimated number of points per face.
Static Public Attributes inherited from fvSchemes
static int debug
Debug switch.
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Static Public Attributes inherited from solution
static int debug
Debug switch.
Static Public Attributes inherited from data
static int debug
Debug switch.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from primitiveMesh
void calcFaceCentresAndAreas () const
Calculate face centres and areas.
void makeFaceCentresAndAreas (const pointField &p, vectorField &fCtrs, vectorField &fAreas) const
void calcCellCentresAndVols () const
Calculate cell centres and volumes.
void makeCellCentresAndVols (const vectorField &fCtrs, const vectorField &fAreas, vectorField &cellCtrs, scalarField &cellVols) const
void calcEdgeVectors () const
Calculate edge vectors.
bool checkDuplicateFaces (const label, const Map< label > &, label &nBaffleFaces, labelHashSet *) const
Check if all points on face are shared with another face.
bool checkCommonOrder (const label, const Map< label > &, labelHashSet *) const
Check that shared points are in consecutive order.
bool checkClosedBoundary (const vectorField &, const bool, const PackedBoolList &) const
Check boundary for closedness.
bool checkClosedCells (const vectorField &faceAreas, const scalarField &cellVolumes, const bool report, labelHashSet *setPtr, labelHashSet *aspectSetPtr, const Vector< label > &meshD) const
Check cells for closedness.
bool checkFaceAreas (const vectorField &faceAreas, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative face areas.
bool checkCellVolumes (const scalarField &vols, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative cell volumes.
bool checkFaceOrthogonality (const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check for non-orthogonality.
bool checkFacePyramids (const pointField &points, const vectorField &ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet *setPtr) const
Check face pyramid volume.
bool checkFaceSkewness (const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check face skewness.
bool checkFaceAngles (const pointField &points, const vectorField &faceAreas, const bool report, const scalar maxDeg, labelHashSet *setPtr) const
Check face angles.
bool checkFaceFlatness (const pointField &points, const vectorField &faceCentres, const vectorField &faceAreas, const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage.
bool checkConcaveCells (const vectorField &fAreas, const pointField &fCentres, const bool report, labelHashSet *setPtr) const
Check for concave cells by the planes of faces.
primitiveMesh ()
Construct null.
Protected Member Functions inherited from surfaceInterpolation
void clearOut ()
Clear all geometry and addressing.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Static Protected Attributes inherited from primitiveMesh
static scalar closedThreshold_ = 1.0e-6
Static data to control mesh checking.
static scalar aspectThreshold_ = 1000
Aspect ratio warning threshold.
static scalar nonOrthThreshold_ = 70
Non-orthogonality warning threshold in deg.
static scalar skewThreshold_ = 4
Skewness warning threshold.
static scalar planarCosAngle_ = 1.0e-6
Threshold where faces are considered coplanar.
Detailed Description
Mesh data needed to do the Finite Volume discretisation.
NOTE ON USAGE: fvMesh contains all the topological and geometric information related to the mesh. It is also responsible for keeping the data up-to-date. This is done by deleting the cell volume, face area, cell/face centre, addressing and other derived information as required and recalculating it as necessary. The fvMesh therefore reserves the right to delete the derived information upon every topological (mesh refinement/morphing) or geometric change (mesh motion). It is therefore unsafe to keep local references to the derived data outside of the time loop.
Source files
fvMesh.H
fvMesh.C
fvMeshGeometry.C
Definition at line 78 of file fvMesh.H.
Member Typedef Documentation
typedef fvMesh Mesh
Definition at line 169 of file fvMesh.H.
typedef fvBoundaryMesh BoundaryMesh
Definition at line 170 of file fvMesh.H.
Constructor & Destructor Documentation
fvMesh (const IOobject & io) explicit
Construct from IOobject.
Definition at line 246 of file fvMesh.C.
References fvSchemes::debug, Foam::endl(), InfoInFunction, IOobject::IOobject(), Foam::isFile(), polyMesh::moving(), IOobject::MUST_READ, IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), timeName, fvMesh::V(), and fvMesh::V00().
fvMesh (const IOobject & io, const Xfer< pointField > & points, const cellShapeList & shapes, const faceListList & boundaryFaces, const wordList & boundaryPatchNames, const PtrList< dictionary > & boundaryDicts, const word & defaultBoundaryPatchName, const word & defaultBoundaryPatchType, const bool syncPar = true)
Construct from cellShapes with boundary.
Definition at line 335 of file fvMesh.C.
References fvSchemes::debug, Foam::endl(), and InfoInFunction.
fvMesh (const IOobject & io, const Xfer< pointField > & points, const Xfer< faceList > & faces, const Xfer< labelList > & allOwner, const Xfer< labelList > & allNeighbour, const bool syncPar = true)
Construct from components without boundary.
Boundary is added using addFvPatches() member function
Definition at line 383 of file fvMesh.C.
References fvSchemes::debug, Foam::endl(), and InfoInFunction.
fvMesh (const IOobject & io, const Xfer< pointField > & points, const Xfer< faceList > & faces, const Xfer< cellList > & cells, const bool syncPar = true)
Construct without boundary from cells rather than owner/neighbour.
Boundary is added using addPatches() member function
Definition at line 417 of file fvMesh.C.
References fvSchemes::debug, Foam::endl(), and InfoInFunction.
~fvMesh () virtual
Destructor.
Definition at line 451 of file fvMesh.C.
References fvMesh::addFvPatches(), and fvMesh::clearOut().
Member Function Documentation
ClassName ("fvMesh")
void addFvPatches (const List< polyPatch * > & p, const bool validBoundary = true)
Add boundary patches. Constructor helper.
Definition at line 460 of file fvMesh.C.
References Foam::abort(), polyMesh::addPatches(), fvMesh::boundary(), polyMesh::boundaryMesh(), Foam::FatalError, FatalErrorInFunction, and HashTable< regIOobject * >::size().
Referenced by extrudePatchMesh::extrudePatchMesh(), polyTopoChange::makeMesh(), fvMeshDistribute::printCoupleInfo(), and fvMesh::~fvMesh().
Foam::polyMesh::readUpdateState readUpdate () virtual
Update the mesh based on the mesh files saved in time.
directories
Reimplemented from polyMesh.
Definition at line 494 of file fvMesh.C.
References polyMesh::boundaryMesh(), fvMesh::clearOut(), fvSchemes::debug, Foam::endl(), Foam::Info, InfoInFunction, polyMesh::POINTS_MOVED, fvBoundaryMesh::readUpdate(), polyMesh::readUpdate(), polyMesh::TOPO_CHANGE, and polyMesh::TOPO_PATCH_CHANGE.
const Time& time () const inline
Return the top-level database.
Definition at line 243 of file fvMesh.H.
References objectRegistry::time().
Referenced by snappyLayerDriver::addLayers(), interRegionExplicitPorositySource::addSup(), interRegionHeatTransferModel::addSup(), fieldToCell::applyToSet(), basicMultiComponentMixture::basicMultiComponentMixture(), blended< Type >::blendingFactor(), CoBlended< Type >::blendingFactor(), cellCoBlended< Type >::blendingFactor(), curvatureSeparation::calcCosAngle(), curvatureSeparation::calcInvR1(), snappySnapDriver::calcNearestSurface(), tabulatedHeatTransfer::calculateHtc(), variableHeatTransfer::calculateHtc(), cloudSolution::canEvolve(), chemistryModel< CompType, ThermoType >::chemistryModel(), probes::classifyFields(), polyMeshFilter::copyMesh(), Foam::MULES::correct(), contactAngleForce::correct(), thixotropicViscosity::correct(), cubic< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), solidification::correctModel(), Foam::CorrectPhi(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::CpByCpv(), heThermo< BasicThermo, MixtureType >::Cpv(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), meshRefinement::createZoneBaffles(), heThermo< BasicThermo, MixtureType >::Cv(), snappySnapDriver::detectNearSurfaces(), fvMeshDistribute::distribute(), snappySnapDriver::doSnap(), extrudePatchMesh::extrudePatchMesh(), CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), fvMesh::fvMesh(), heThermo< BasicThermo, MixtureType >::gamma(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), heThermo< BasicThermo, MixtureType >::hc(), heThermo< BasicThermo, MixtureType >::he(), coalCloudList::hsTrans(), Foam::MULES::implicitSolve(), interRegionExplicitPorositySource::initialise(), SurfaceFilmModel< CloudType >::inject(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), fvMeshSubset::interpolate(), cellSetOption::inTimeLimits(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), Foam::MULES::limitCorr(), PhiScheme< Type, PhiLimiter >::limiter(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), Foam::MULES::limiterCorr(), localEulerDdt::localRDeltaT(), basicThermo::lookupOrConstruct(), simpleControl::loop(), Foam::MapConsistentMesh(), Foam::MapConsistentVolFields(), fvMeshDistribute::mapExposedFaces(), Foam::MapLagrangianFields(), meshToMesh::mapSrcToTgt(), Foam::MapSubMesh(), meshToMesh::mapTgtToSrc(), Foam::MapVolFields(), LocalInteraction< CloudType >::massEscape(), LocalInteraction< CloudType >::massStick(), solidParticleCloud::move(), fvMesh::movePoints(), movingConeTopoFvMesh::movingConeTopoFvMesh(), laminar::mut(), regionCoupledBaseFvPatch::nbrFvMesh(), regionCoupledBaseFvPatch::nbrMesh(), sampledThresholdCellFaces::needsUpdate(), sampledIsoSurfaceCell::needsUpdate(), sampledIsoSurface::needsUpdate(), basicChemistryModel::New(), basicSolidChemistryModel::New(), psiCombustionModel::New(), rhoCombustionModel::New(), surfaceFilmModel::New(), basicThermo::New(), thermalBaffleModel::New(), pyrolysisModel::New(), listPlusEqOp< T >::operator()(), cloudSolution::output(), fvMesh::phi(), sampledSurface::pointAverage(), VoidFraction< CloudType >::postEvolve(), VoidFraction< CloudType >::preEvolve(), ParticleErosion< CloudType >::preEvolve(), snappySnapDriver::preSmoothPatch(), pyrolysisModelCollection::pyrolysisModelCollection(), snappySnapDriver::repatchToSurface(), forces::rho(), coalCloudList::rhoTrans(), noRadiation::Rp(), opaqueSolid::Rp(), P1::Rp(), viewFactor::Rp(), fvDOM::Rp(), noRadiation::Ru(), opaqueSolid::Ru(), viewFactor::Ru(), snappySnapDriver::scaleMesh(), interRegionOption::setMapper(), interRegionHeatTransferModel::setNbrModel(), simpleControl::simpleControl(), skewCorrected< Type >::skewCorrection(), snappySnapDriver::smoothDisplacement(), snappyRefineDriver::snappyRefineDriver(), solidChemistryModel< CompType, SolidThermo >::solidChemistryModel(), sixDoFRigidBodyMotionSolver::solve(), cloudSolution::solveThisStep(), coalCloudList::Srho(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), dynamicInkJetFvMesh::update(), linearValveLayersFvMesh::update(), linearValveFvMesh::update(), movingConeTopoFvMesh::update(), dynamicRefineFvMesh::update(), movingWallVelocityFvPatchVectorField::updateCoeffs(), laminar::Us(), coalCloudList::UTrans(), fvMesh::V(), fvMesh::V00(), fvMesh::Vsc(), fvMesh::Vsc0(), wallShearStress::wallShearStress(), extendedUpwindCellToFaceStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), reverseLinear< Type >::weights(), clippedLinear< Type >::weights(), PatchPostProcessing< CloudType >::write(), FacePostProcessing< CloudType >::write(), wallShearStress::write(), histogram::write(), ParticleCollector< CloudType >::write(), streamLine::write(), regionSizeDistribution::write(), wallBoundedStreamLine::write(), dynamicRefineFvMesh::writeObject(), yPlus::yPlus(), and meshRefinement::zonify().
virtual const objectRegistry& thisDb () const inline virtual
Return the object registry - resolve conflict polyMesh/lduMesh.
Reimplemented from lduMesh.
Definition at line 249 of file fvMesh.H.
References fvMesh::boundary(), fvBoundaryMesh::interfaces(), fvMesh::interfaces(), fvMesh::lduAddr(), fvMesh::name(), IOobject::name(), and polyMesh::thisDb().
Referenced by extrudePatchMesh::extrudePatchMesh(), and options::New().
const word& name () const inline
Return reference to name.
Note: name() is currently ambiguous due to derivation from surfaceInterpolation
Definition at line 257 of file fvMesh.H.
Referenced by snappyLayerDriver::addLayers(), interRegionHeatTransferModel::addSup(), polyMeshFilter::copyMesh(), engineMesh::engineMesh(), reactingOneDim::evolveRegion(), reactingOneDim::info(), temperatureCoupledBase::kappa(), options::New(), interRegionOption::setMapper(), interRegionHeatTransferModel::setNbrModel(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), fvMesh::thisDb(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), thermalBaffleFvPatchScalarField::updateCoeffs(), thermalBaffleFvPatchScalarField::write(), streamLine::write(), and wallBoundedStreamLine::write().
const Foam::fvBoundaryMesh & boundary () const
Return reference to boundary mesh.
Definition at line 545 of file fvMesh.C.
Referenced by isoSurface::adaptPatchFields(), fvMeshAdder::add(), fvMesh::addFvPatches(), fvMeshTools::addPatch(), meshRefinement::addPatch(), meshRefinement::appendPatch(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), meshRefinement::collectAndPrint(), nearWallDistNoSearch::correct(), nearWallDist::correct(), MRFZoneList::correctBoundaryFlux(), pointLinear< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), outletStabilised< Type >::correction(), fvMesh::delta(), engineMesh::engineMesh(), volPointInterpolation::flatBoundaryField(), fvBoundaryMeshMapper::fvBoundaryMeshMapper(), fvFieldDecomposer::fvFieldDecomposer(), fvFieldReconstructor::fvFieldReconstructor(), fvMeshLduAddressing::fvMeshLduAddressing(), thermalBaffle::info(), fvMeshSubset::interpolate(), Foam::MULES::limiterCorr(), Foam::MapConsistentSubMesh(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), fvMotionSolverEngineMesh::move(), surfaceInterpolation::movePoints(), fvMesh::movePoints(), regionCoupledBaseFvPatch::neighbFvPatch(), regionCoupledBaseFvPatch::neighbPatch(), patchDistMethod::patchTypes(), fvMeshDistribute::printMeshInfo(), Foam::fvc::reconstructMag(), fvMeshTools::reorderPatches(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), fvMesh::thisDb(), reverseLinear< Type >::weights(), clippedLinear< Type >::weights(), outletStabilised< Type >::weights(), yPlus::write(), wallShearStress::write(), and fvMeshTools::zeroPatchFields().
const Foam::lduAddressing & lduAddr () const virtual
Return ldu addressing.
Implements lduMesh.
Definition at line 551 of file fvMesh.C.
Referenced by fvMesh::neighbour(), fvMesh::owner(), and fvMesh::thisDb().
virtual lduInterfacePtrsList interfaces () const inline virtual
Return a list of pointers for each patch.
with only those pointing to interfaces being set
Implements lduMesh.
Definition at line 270 of file fvMesh.H.
Referenced by fvMesh::thisDb().
virtual label comm () const inline virtual
Return communicator used for parallel communication.
Implements lduMesh.
Definition at line 276 of file fvMesh.H.
References polyMesh::comm().
const labelUList& owner () const inline
Internal face owner.
Definition at line 282 of file fvMesh.H.
References fvMesh::lduAddr(), and lduAddressing::lowerAddr().
Referenced by curvatureSeparation::calcCosAngle(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), contactAngleForce::correct(), pointLinear< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), fvMesh::delta(), faceCorrectedSnGrad< Type >::fullGradCorrection(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limiterCorr(), surfaceInterpolation::movePoints(), Foam::fvc::reconstructMag(), fvMatrix< Type >::setValuesFromList(), Foam::fvc::smooth(), snGradScheme< Type >::snGrad(), Foam::fvc::spread(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), Foam::fvc::sweep(), leastSquaresVectors::~leastSquaresVectors(), and skewCorrectionVectors::~skewCorrectionVectors().
const labelUList& neighbour () const inline
Internal face neighbour.
Definition at line 288 of file fvMesh.H.
References fvMesh::C(), fvMesh::Cf(), fvMesh::clearOut(), fvMesh::delta(), fvMesh::lduAddr(), fvMesh::magSf(), fvMesh::mapFields(), surfaceInterpolation::movePoints(), fvMesh::operator!=(), fvMesh::operator==(), fvMesh::phi(), fvMesh::removeFvBoundary(), fvMesh::setPhi(), fvMesh::setV0(), fvMesh::Sf(), fvMesh::updateMesh(), lduAddressing::upperAddr(), fvMesh::V(), fvMesh::V0(), fvMesh::V00(), fvMesh::validComponents(), fvMesh::Vsc(), fvMesh::Vsc0(), fvMesh::write(), and fvMesh::writeObjects().
Referenced by curvatureSeparation::calcCosAngle(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), contactAngleForce::correct(), pointLinear< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), fvMesh::delta(), faceCorrectedSnGrad< Type >::fullGradCorrection(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limiterCorr(), surfaceInterpolation::movePoints(), Foam::fvc::reconstructMag(), fvMatrix< Type >::setValuesFromList(), Foam::fvc::smooth(), snGradScheme< Type >::snGrad(), Foam::fvc::spread(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), Foam::fvc::sweep(), leastSquaresVectors::~leastSquaresVectors(), and skewCorrectionVectors::~skewCorrectionVectors().
const Foam::volScalarField::Internal & V () const
Return cell volumes.
Definition at line 186 of file fvMeshGeometry.C.
References primitiveMesh::cellVolumes(), fvSchemes::debug, Foam::dimVolume, Foam::endl(), InfoInFunction, IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), and timeName.
Referenced by anisotropicFilter::anisotropicFilter(), cellCoBlended< Type >::blendingFactor(), inverseVolumeDiffusivity::correct(), nearWallDist::correct(), CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), fvMesh::fvMesh(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), laplaceFilter::laplaceFilter(), fvMesh::movePoints(), fvMesh::neighbour(), VoidFraction< CloudType >::postEvolve(), Foam::fvc::reconstructMag(), reactingOneDim::solveContinuity(), thermoSingleLayer::Srho(), CellZoneInjection< CloudType >::updateMesh(), fvMesh::updateMesh(), reactingOneDim::updatePhiGas(), fvMesh::Vsc(), fvMesh::Vsc0(), histogram::write(), and regionSizeDistribution::write().
const Foam::volScalarField::Internal & V0 () const
Return old-time cell volumes.
Definition at line 217 of file fvMeshGeometry.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), fvMesh::neighbour(), fvMesh::V00(), fvMesh::Vsc(), and fvMesh::Vsc0().
const Foam::volScalarField::Internal & V00 () const
Return old-old-time cell volumes.
Definition at line 243 of file fvMeshGeometry.C.
References IOobject::AUTO_WRITE, fvSchemes::debug, Foam::endl(), InfoInFunction, IOobject::IOobject(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), timeName, and fvMesh::V0().
Referenced by CrankNicolsonDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), fvMesh::fvMesh(), fvMesh::mapFields(), and fvMesh::neighbour().
Foam::tmp< Foam::volScalarField::Internal > Vsc () const
Return sub-cycle cell volumes.
Definition at line 275 of file fvMeshGeometry.C.
References TimeState::deltaTValue(), polyMesh::moving(), Time::prevTimeState(), fvMesh::time(), fvMesh::V(), fvMesh::V0(), and dimensioned< Type >::value().
Referenced by Foam::MULES::limiterCorr(), fvMesh::neighbour(), and Foam::fvc::surfaceIntegrate().
Foam::tmp< Foam::volScalarField::Internal > Vsc0 () const
Return sub-cycl old-time cell volumes.
Definition at line 304 of file fvMeshGeometry.C.
References TimeState::deltaTValue(), polyMesh::moving(), Time::prevTimeState(), fvMesh::time(), fvMesh::V(), fvMesh::V0(), and dimensioned< Type >::value().
Referenced by fvMesh::neighbour().
const Foam::surfaceVectorField & Sf () const
Return cell face area vectors.
Definition at line 333 of file fvMeshGeometry.C.
Referenced by anisotropicFilter::anisotropicFilter(), Implicit< CloudType >::cacheFields(), curvatureSeparation::calcCosAngle(), wallShearStress::calcShearStress(), Foam::constrainPressure(), MRFZoneList::correctBoundaryFlux(), cubic< Type >::correction(), Foam::correctUphiBCs(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), faceCorrectedSnGrad< Type >::fullGradCorrection(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), SurfaceFilmModel< CloudType >::inject(), PhiScheme< Type, PhiLimiter >::limiter(), surfaceInterpolation::movePoints(), fvMesh::neighbour(), Foam::fvc::reconstruct(), Foam::fvc::reconstructMag(), fvPatch::Sf(), rawTopoChangerFvMesh::update(), and skewCorrectionVectors::~skewCorrectionVectors().
const Foam::surfaceScalarField & magSf () const
Return cell face area magnitudes.
Definition at line 344 of file fvMeshGeometry.C.
Referenced by Foam::fvc::average(), CoBlended< Type >::blendingFactor(), curvatureSeparation::calcCosAngle(), wallShearStress::calcShearStress(), viewFactor::calculate(), Foam::constrainPressure(), cubic< Type >::correction(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), faceCorrectedSnGrad< Type >::fullGradCorrection(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), Foam::MULES::implicitSolve(), SurfaceFilmModel< CloudType >::inject(), PhiScheme< Type, PhiLimiter >::limiter(), fvPatch::magSf(), surfaceInterpolation::movePoints(), fvMesh::neighbour(), Foam::fvc::reconstruct(), Foam::fvc::reconstructMag(), kinematicSingleLayer::solveThickness(), and thermoSingleLayer::transferPrimaryRegionSourceFields().
const Foam::surfaceScalarField & phi () const
Return cell face motion fluxes.
Definition at line 425 of file fvMeshGeometry.C.
References Foam::abort(), Foam::dimTime, Foam::dimVolume, Foam::FatalError, FatalErrorInFunction, fvMesh::time(), TimeState::timeIndex(), and GeometricField< Type, PatchField, GeoMesh >::timeIndex().
Referenced by CrankNicolsonDdtScheme< Type >::meshPhi(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), fvMesh::movePoints(), fvMesh::neighbour(), and rawTopoChangerFvMesh::update().
const Foam::volVectorField & C () const
Return cell centres as volVectorField.
Definition at line 355 of file fvMeshGeometry.C.
Referenced by volMesh::C(), CentredFitSnGradData< Polynomial >::calcFit(), forces::calcForcesMoment(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), CentredFitData< Polynomial >::CentredFitData(), pointLinear< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), fvMesh::delta(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), faceCorrectedSnGrad< Type >::fullGradCorrection(), SurfaceFilmModel< CloudType >::inject(), Kmesh::Kmesh(), surfaceInterpolation::movePoints(), fvMesh::neighbour(), Foam::fvc::reconstructMag(), ThermoSurfaceFilm< CloudType >::splashInteraction(), UpwindFitData< Polynomial >::UpwindFitData(), leastSquaresVectors::~leastSquaresVectors(), LeastSquaresVectors< Stencil >::~LeastSquaresVectors(), and skewCorrectionVectors::~skewCorrectionVectors().
const Foam::surfaceVectorField & Cf () const
Return face centres as surfaceVectorField.
Definition at line 366 of file fvMeshGeometry.C.
Referenced by surfaceMesh::C(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), fvPatch::Cf(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), fvMesh::neighbour(), Foam::fvc::reconstructMag(), ThermoSurfaceFilm< CloudType >::splashInteraction(), reactingOneDim::updateQr(), and skewCorrectionVectors::~skewCorrectionVectors().
Foam::tmp< Foam::surfaceVectorField > delta () const
Return face deltas as surfaceVectorField.
Definition at line 377 of file fvMeshGeometry.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), fvMesh::C(), fvSchemes::debug, Foam::dimLength, Foam::endl(), forAll, InfoInFunction, polyMesh::meshSubDir, fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), patchi, polyMesh::pointsInstance(), and tmp< T >::ref().
Referenced by fvMesh::neighbour().
pTraits<Type>::labelType validComponents () const
Return a labelType of valid component indicators.
1 : valid (solved) -1 : invalid (not solved)
Referenced by fvMesh::neighbour().
void clearOut ()
Clear all geometry and addressing.
Definition at line 230 of file fvMesh.C.
References surfaceInterpolation::clearOut(), polyMesh::clearOut(), and Foam::deleteDemandDrivenData().
Referenced by fvMeshAdder::add(), snappyLayerDriver::addLayers(), fvMeshTools::addPatch(), meshRefinement::appendPatch(), meshRefinement::createBaffles(), fvMeshDistribute::distribute(), meshRefinement::dupNonManifoldPoints(), extrudePatchMesh::extrudePatchMesh(), meshRefinement::mergeBaffles(), fvMesh::neighbour(), fvMesh::readUpdate(), fvMesh::removeFvBoundary(), fvMeshTools::zeroPatchFields(), meshRefinement::zonify(), and fvMesh::~fvMesh().
void updateMesh (const mapPolyMesh & mpm) virtual
Update mesh corresponding to the given map.
Reimplemented from polyMesh.
Definition at line 800 of file fvMesh.C.
References primitiveMesh::clearAddressing(), surfaceInterpolation::clearOut(), Foam::deleteDemandDrivenData(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fvMesh::mapFields(), mapPolyMesh::nOldCells(), mapPolyMesh::oldCellVolumes(), HashTable< regIOobject * >::size(), polyMesh::updateMesh(), fvMesh::V(), and fvMesh::writeObjects().
Referenced by snappyLayerDriver::addLayers(), meshRefinement::createBaffles(), meshRefinement::dupNonManifoldPoints(), meshRefinement::mergeBaffles(), fvMesh::neighbour(), linearValveFvMesh::update(), linearValveLayersFvMesh::update(), and meshRefinement::zonify().
Foam::tmp< Foam::scalarField > movePoints (const pointField & p) virtual
Move points, returns volumes swept by faces in motion.
Reimplemented from polyMesh.
Definition at line 721 of file fvMesh.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), TimeState::deltaTValue(), Foam::dimTime, Foam::dimVolume, forAll, fvBoundaryMesh::movePoints(), surfaceInterpolation::movePoints(), polyMesh::movePoints(), primitiveMesh::nInternalFaces(), IOobject::NO_READ, IOobject::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::oldTime(), patches, patchi, fvMesh::phi(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), tmp< T >::ref(), fvMesh::time(), timeIndex, TimeState::timeIndex(), GeometricField< Type, PatchField, GeoMesh >::timeIndex(), timeName, and fvMesh::V().
Referenced by snappyLayerDriver::addLayers(), meshRefinement::createBaffles(), meshRefinement::dupNonManifoldPoints(), meshRefinement::mergeBaffles(), processorMeshes::reconstructPoints(), and meshRefinement::zonify().
void mapFields (const mapPolyMesh & mpm) virtual
Map all fields in time using given map.
Definition at line 562 of file fvMesh.C.
References mapPolyMesh::cellMap(), fvSchemes::debug, Foam::endl(), Foam::exit(), mapPolyMesh::faceMap(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, InfoInFunction, Foam::mapClouds(), primitiveMesh::nCells(), primitiveMesh::nFaces(), mapPolyMesh::nOldCells(), mapPolyMesh::nOldFaces(), mapPolyMesh::reverseCellMap(), List< T >::setSize(), List< T >::size(), and fvMesh::V00().
Referenced by fvMesh::neighbour(), and fvMesh::updateMesh().
void removeFvBoundary ()
Remove boundary patches. Warning: fvPatchFields hold ref to.
these fvPatches.
Definition at line 478 of file fvMesh.C.
References PtrList< T >::clear(), fvMesh::clearOut(), fvSchemes::debug, Foam::endl(), InfoInFunction, polyMesh::removeBoundary(), and PtrList< T >::setSize().
Referenced by extrudePatchMesh::extrudePatchMesh(), and fvMesh::neighbour().
Foam::surfaceScalarField & setPhi ()
Return cell face motion fluxes.
Definition at line 445 of file fvMeshGeometry.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by fvMesh::neighbour().
Foam::volScalarField::Internal & setV0 ()
Return old-time cell volumes.
Definition at line 230 of file fvMeshGeometry.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by fvMesh::neighbour().
bool writeObjects (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const virtual
Write the underlying polyMesh and other data.
Definition at line 860 of file fvMesh.C.
References objectRegistry::writeObject().
Referenced by fvMesh::neighbour(), fvMesh::updateMesh(), and dynamicRefineFvMesh::writeObject().
bool write () const virtual
Write mesh using IO settings from time.
Reimplemented from regIOobject.
Definition at line 870 of file fvMesh.C.
References regIOobject::write().
Referenced by snappyLayerDriver::addLayers(), extrudePatchMesh::extrudePatchMesh(), fvMesh::neighbour(), processorMeshes::reconstructPoints(), and snappySnapDriver::scaleMesh().
bool operator!= (const fvMesh & bm) const
Definition at line 892 of file fvMesh.C.
Referenced by fvMesh::neighbour().
bool operator== (const fvMesh & bm) const
Definition at line 898 of file fvMesh.C.
Referenced by fvMesh::neighbour().
pTraits<sphericalTensor>::labelType validComponents () const
Foam::pTraits<Type>::labelType validComponents () const
Definition at line 31 of file fvMeshTemplates.C.
References Foam::pow(), polyMesh::solutionD(), and Foam::type().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvMesh.H
src/finiteVolume/fvMesh/fvMesh.C
src/finiteVolume/fvMesh/fvMeshGeometry.C
src/finiteVolume/fvMesh/fvMeshTemplates.C