OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
functionObject Class Reference abstract
Abstract base-class for Time/database function objects.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
virtual const word & name () const
Name.
virtual bool start ()=0
Called at the start of the time-loop.
virtual bool execute (const bool forceWrite)=0
Called at each ++ or += of the time-loop. forceWrite overrides the.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool read (const dictionary &)=0
Read and set the function object if its data have changed.
virtual void updateMesh (const mapPolyMesh &mpm)=0
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)=0
Update for changes of mesh.
Static Public Member Functions
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes
static int debug
Detailed Description
Abstract base-class for Time/database function objects.
See also
Foam::OutputFilterFunctionObject
Source files
functionObject.H
functionObject.C
Definition at line 167 of file functionObject.H.
Constructor & Destructor Documentation
functionObject (const word & name)
Construct from components.
Definition at line 42 of file functionObject.C.
References functionObject::New().
~functionObject () virtual
Destructor.
Definition at line 99 of file functionObject.C.
Referenced by functionObject::clone().
Member Function Documentation
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (autoPtr , functionObject , dictionary , (const word &name, const Time &t, const dictionary &dict) , (name, t, dict))
autoPtr<functionObject> clone () const inline
Return clone.
Definition at line 210 of file functionObject.H.
References functionObject::adjustTimeStep(), functionObject::end(), functionObject::execute(), mesh, functionObject::movePoints(), functionObject::name(), functionObject::New(), NotImplemented, functionObject::read(), functionObject::start(), functionObject::timeSet(), functionObject::updateMesh(), and functionObject::~functionObject().
Foam::autoPtr< Foam::functionObject > New (const word & name, const Time & t, const dictionary & functionDict) static
Select from dictionary, based on its "type" entry.
Definition at line 51 of file functionObject.C.
References functionObject::debug, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), functionObject::name(), and Foam::nl.
Referenced by functionObject::clone(), functionObject::functionObject(), functionObjectList::read(), and codedFunctionObject::redirectFunctionObject().
const Foam::word & name () const virtual
Name.
Definition at line 105 of file functionObject.C.
Referenced by functionObject::clone(), and functionObject::New().
virtual bool start () pure virtual
Called at the start of the time-loop.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::clone(), and functionObjectList::read().
virtual bool execute (const bool forceWrite) pure virtual
Called at each ++ or += of the time-loop. forceWrite overrides the.
outputControl behaviour.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::clone(), functionObject::end(), and functionObjectList::execute().
bool end () virtual
Called when Time::run() determines that the time-loop exits.
By default it simply calls execute().
Reimplemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Definition at line 111 of file functionObject.C.
References functionObject::execute().
Referenced by functionObject::clone(), and functionObjectList::end().
bool timeSet () virtual
Called when time was set at the end of the Time::operator++.
Reimplemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Definition at line 117 of file functionObject.C.
Referenced by functionObject::clone(), and functionObjectList::timeSet().
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Reimplemented in OutputFilterFunctionObject< OutputFilter >, and setTimeStepFunctionObject.
Definition at line 123 of file functionObject.C.
Referenced by functionObjectList::adjustTimeStep(), and functionObject::clone().
virtual bool read (const dictionary &) pure virtual
Read and set the function object if its data have changed.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::clone(), and functionObjectList::read().
virtual void updateMesh (const mapPolyMesh & mpm) pure virtual
Update for changes of mesh.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::clone(), and functionObjectList::updateMesh().
virtual void movePoints (const polyMesh & mesh) pure virtual
Update for changes of mesh.
Implemented in OutputFilterFunctionObject< OutputFilter >, codedFunctionObject, and setTimeStepFunctionObject.
Referenced by functionObject::clone(), and functionObjectList::movePoints().
Member Data Documentation
int debug static
Definition at line 189 of file functionObject.H.
Referenced by functionObject::New().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObject/functionObject.H
src/OpenFOAM/db/functionObjects/functionObject/functionObject.C