OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
forces Class Reference
Function objects » Forces function objects
This function object calculates the forces and moments by integrating the pressure and skin-friction forces over a given list of patches.
Public Member Functions
TypeName ("forces")
Runtime type information.
forces (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false, const bool readFields=true)
Construct for given objectRegistry and dictionary.
forces (const word &name, const objectRegistry &, const labelHashSet &patchSet, const word &pName, const word &UName, const word &rhoName, const scalar rhoInf, const scalar pRef, const coordinateSystem &coordSys)
Construct from components.
virtual ~forces ()
Destructor.
virtual const word & name () const
Return name of the set of forces.
virtual void read (const dictionary &)
Read the forces data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write the forces.
virtual void calcForcesMoment ()
Calculate the forces and moments.
virtual vector forceEff () const
Return the total force.
virtual vector momentEff () const
Return the total moment.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFiles
functionObjectFiles (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
functionObjectFiles (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFiles (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
virtual ~functionObjectFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Member Functions
static bool viable (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Return true if the construction of this functionObject is viable.
Protected Member Functions
wordList createFileNames (const dictionary &dict) const
Create file names for forces and bins.
virtual void writeFileHeader (const label i)
Output file header information.
void initialise ()
Initialise the fields.
tmp< volSymmTensorField > devRhoReff () const
Return the effective viscous stress (laminar + turbulent).
tmp< volScalarField > mu () const
Dynamic viscosity field.
tmp< volScalarField > rho () const
Return rho if rhoName is specified otherwise rhoRef.
scalar rho (const volScalarField &p) const
Return rhoRef if the pressure field is dynamic, i.e. p/rho.
void applyBins (const vectorField &Md, const vectorField &fN, const vectorField &fT, const vectorField &fP, const vectorField &d)
Accumulate bin data.
void writeForces ()
Helper function to write force data.
void writeBins ()
Helper function to write bin data.
forces (const forces &)
Disallow default bitwise copy construct.
void operator= (const forces &)
Disallow default bitwise assignment.
Protected Member Functions inherited from functionObjectFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
functionObjectFiles (const functionObjectFiles &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of forces,.
const objectRegistry & obr_
Switch log_
Switch to send output to Info as well as to file.
List< Field< vector > > force_
Pressure, viscous and porous force per bin.
List< Field< vector > > moment_
Pressure, viscous and porous moment per bin.
labelHashSet patchSet_
Patches to integrate forces over.
word pName_
Name of pressure field.
word UName_
Name of velocity field.
word rhoName_
Name of density field (optional)
Switch directForceDensity_
Is the force density being supplied directly?
word fDName_
The name of the force density (fD) field.
scalar rhoRef_
Reference density needed for incompressible calculations.
scalar pRef_
Reference pressure.
coordinateSystem coordSys_
Coordinate system used when evaluting forces/moments.
bool localSystem_
Flag to indicate whether we are using a local co-ordinate sys.
bool porosity_
Flag to include porosity effects.
label nBin_
Number of bins.
vector binDir_
Direction used to determine bin orientation.
scalar binDx_
Distance between bin divisions.
scalar binMin_
Minimum bin bounds.
List< point > binPoints_
Bin positions along binDir.
bool binCumulative_
Should bin data be cumulative?
bool initialised_
Initialised flag.
Protected Attributes inherited from functionObjectFile
const objectRegistry & obr_
Reference to the objectRegistry.
const word prefix_
Prefix.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Detailed Description
This function object calculates the forces and moments by integrating the pressure and skin-friction forces over a given list of patches.
Member function forces::write() calculates the forces/moments and writes the forces/moments into the file <timeDir>/forces.dat and bin data (if selected) to the file <timeDir>/forces_bin.dat
Example of function object specification:
forces1
{
    type        forces;
    functionObjectLibs ("libforces.so");
    ...
    log         yes;
    patches     (walls);
    binData
    {
        nBin        20;
        direction   (1 0 0);
        cumulative  yes;
    }
}
Function object usage
Property Description Required Default value
type type name: forces yes
log write force data to standard output no no
patches patches included in the forces calculation yes
pName pressure field name no p
UName velocity field name no U
rhoName density field name (see below) no rho
CofR centre of rotation (see below) no
directForceDensity force density supplied directly (see below) no no
fDName name of force density field (see below) no fD
Bin data is optional, but if the dictionary is present, the entries must be defined according o
nBin number of data bins yes
direction direction along which bins are defined yes
cumulative bin data accumulated with incresing distance yes
Note
For incompressible cases, set rhoName to rhoInf. You will then be required to provide a rhoInf value corresponding to the free-stream constant density.
If the force density is supplied directly, set the directForceDensity flag to 'yes', and supply the force density field using the fDName entry
The centre of rotation (CofR) for moment calculations can either be specified by an CofR entry, or be taken from origin of the local coordinate system. For example,
    CofR        (0 0 0);
or
    coordinateSystem
    {
        origin  (0 0 0);
        e3      (0 0 1);
        e1      (1 0 0);
    }
See also
Foam::functionObject Foam::OutputFilterFunctionObject Foam::forceCoeffs
Source files
forces.H
forces.C
IOforces.H
Definition at line 209 of file forces.H.
Constructor & Destructor Documentation
forces (const forces &) protected
Disallow default bitwise copy construct.
Referenced by forces::viable(), and forces::writeBins().
forces (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false, const bool readFields = true)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 523 of file forces.C.
References Foam::endl(), Foam::Info, Foam::read(), and forces::viable().
forces (const word & name, const objectRegistry & obr, const labelHashSet & patchSet, const word & pName, const word & UName, const word & rhoName, const scalar rhoInf, const scalar pRef, const coordinateSystem & coordSys)
Construct from components.
Definition at line 578 of file forces.C.
References forAll.
~forces () virtual
Destructor.
Definition at line 625 of file forces.C.
Member Function Documentation
Foam::wordList createFileNames (const dictionary & dict) const protected
Create file names for forces and bins.
Definition at line 50 of file forces.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), dictionary::found(), dictionary::lookup(), Foam::readLabel(), and dictionary::subDict().
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from functionObjectFile.
Reimplemented in forceCoeffs.
Definition at line 74 of file forces.C.
References Foam::abort(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::jn(), Foam::name(), Foam::nl, and Foam::tab.
void initialise () protected
Initialise the fields.
Definition at line 162 of file forces.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, and Foam::nl.
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const protected
Return the effective viscous stress (laminar + turbulent).
Definition at line 209 of file forces.C.
References Foam::dev(), IncompressibleTurbulenceModel< TransportModel >::devReff(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::fvc::grad(), dictionary::lookup(), fluidThermo::mu(), transportModel::nu(), nu, GeometricField< symmTensor, fvPatchField, volMesh >::null(), rho, turb, Foam::twoSymm(), and U.
Foam::tmp< Foam::volScalarField > mu () const protected
Dynamic viscosity field.
Definition at line 271 of file forces.C.
References dictionaryName::dictName(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), fluidThermo::mu(), transportModel::nu(), nu, GeometricField< scalar, fvPatchField, volMesh >::null(), and rho.
Foam::tmp< Foam::volScalarField > rho () const protected
Return rho if rhoName is specified otherwise rhoRef.
Definition at line 310 of file forces.C.
References Foam::dimDensity, mesh, fvMesh::time(), and Time::timeName().
Foam::scalar rho (const volScalarField & p) const protected
Return rhoRef if the pressure field is dynamic, i.e. p/rho.
otherwise return 1
Definition at line 338 of file forces.C.
References forces::applyBins(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimPressure, Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
void applyBins (const vectorField & Md, const vectorField & fN, const vectorField & fT, const vectorField & fP, const vectorField & d) protected
Accumulate bin data.
Definition at line 359 of file forces.C.
References forAll, Foam::max(), Foam::min(), and Foam::sum().
Referenced by forces::rho().
void writeForces () protected
Helper function to write force data.
Definition at line 395 of file forces.C.
References Foam::endl(), Foam::Info, Foam::nl, Foam::setw(), Foam::sum(), Foam::tab, and Foam::type().
void writeBins () protected
Helper function to write bin data.
Definition at line 441 of file forces.C.
References Foam::endl(), f(), forAll, forces::forces(), Foam::setw(), List< T >::size(), and Foam::tab.
void operator= (const forces &) protected
Disallow default bitwise assignment.
TypeName ("forces")
Runtime type information.
bool viable (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false) static
Return true if the construction of this functionObject is viable.
i.e. the prerequisites for construction are available
Definition at line 565 of file forces.C.
References forces::forces().
Referenced by forces::forces().
virtual const word& name () const inline virtual
Return name of the set of forces.
Definition at line 392 of file forces.H.
References forces::calcForcesMoment(), forces::end(), forces::execute(), forces::forceEff(), forces::momentEff(), forces::name_, forces::read(), forces::timeSet(), and forces::write().
void read (const dictionary & dict) virtual
Read the forces data.
Reimplemented in forceCoeffs.
Definition at line 631 of file forces.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), polyPatch::faceCentres(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, forAllConstIter(), dictionary::found(), Foam::Info, dictionary::lookup(), dictionary::lookupOrDefault(), Foam::mag(), Foam::max(), mesh, Foam::min(), Foam::nl, patchi, polyBoundaryMesh::patchSet(), dictionary::readIfPresent(), Foam::readScalar(), Foam::reduce(), dictionary::subDict(), and Foam::type().
Referenced by forces::name(), and forceCoeffs::read().
void execute () virtual
Execute, currently does nothing.
Reimplemented in forceCoeffs.
Definition at line 761 of file forces.C.
Referenced by forces::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Reimplemented in forceCoeffs.
Definition at line 765 of file forces.C.
Referenced by forces::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Reimplemented in forceCoeffs.
Definition at line 769 of file forces.C.
Referenced by forces::name().
void write () virtual
Write the forces.
Reimplemented from functionObjectFiles.
Reimplemented in forceCoeffs.
Definition at line 773 of file forces.C.
References Foam::endl(), Foam::Info, UPstream::master(), and functionObjectFiles::write().
Referenced by forces::name().
void calcForcesMoment () virtual
Calculate the forces and moments.
Porous force
Definition at line 790 of file forces.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), porosityModel::cellZoneIDs(), polyMesh::cellZones(), HashTable< T, Key, Hash >::empty(), Foam::endl(), forAll, forAllConstIter(), porosityModel::force(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Foam::mag(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::constant::physicoChemical::mu, p, patchi, pRef, rho, List< T >::size(), U, WarningInFunction, and Foam::Zero.
Referenced by forces::name(), sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotion::solve(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and forceCoeffs::write().
Foam::vector forceEff () const virtual
Return the total force.
Definition at line 930 of file forces.C.
References Foam::sum().
Referenced by forces::name(), sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotion::solve(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
Foam::vector momentEff () const virtual
Return the total moment.
Definition at line 936 of file forces.C.
References Foam::sum().
Referenced by forces::name(), sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotion::solve(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 422 of file forces.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 426 of file forces.H.
Member Data Documentation
word name_ protected
Name of this set of forces,.
Also used as the name of the probes directory.
Definition at line 219 of file forces.H.
Referenced by forces::name().
const objectRegistry& obr_ protected
Definition at line 221 of file forces.H.
Switch log_ protected
Switch to send output to Info as well as to file.
Definition at line 224 of file forces.H.
List<Field<vector> > force_ protected
Pressure, viscous and porous force per bin.
Definition at line 227 of file forces.H.
List<Field<vector> > moment_ protected
Pressure, viscous and porous moment per bin.
Definition at line 230 of file forces.H.
labelHashSet patchSet_ protected
Patches to integrate forces over.
Definition at line 236 of file forces.H.
word pName_ protected
Name of pressure field.
Definition at line 239 of file forces.H.
word UName_ protected
Name of velocity field.
Definition at line 242 of file forces.H.
word rhoName_ protected
Name of density field (optional)
Definition at line 245 of file forces.H.
Switch directForceDensity_ protected
Is the force density being supplied directly?
Definition at line 248 of file forces.H.
word fDName_ protected
The name of the force density (fD) field.
Definition at line 251 of file forces.H.
scalar rhoRef_ protected
Reference density needed for incompressible calculations.
Definition at line 254 of file forces.H.
scalar pRef_ protected
Reference pressure.
Definition at line 257 of file forces.H.
coordinateSystem coordSys_ protected
Coordinate system used when evaluting forces/moments.
Definition at line 260 of file forces.H.
bool localSystem_ protected
Flag to indicate whether we are using a local co-ordinate sys.
Definition at line 263 of file forces.H.
bool porosity_ protected
Flag to include porosity effects.
Definition at line 266 of file forces.H.
label nBin_ protected
Number of bins.
Definition at line 272 of file forces.H.
vector binDir_ protected
Direction used to determine bin orientation.
Definition at line 275 of file forces.H.
scalar binDx_ protected
Distance between bin divisions.
Definition at line 278 of file forces.H.
scalar binMin_ protected
Minimum bin bounds.
Definition at line 281 of file forces.H.
List<point> binPoints_ protected
Bin positions along binDir.
Definition at line 284 of file forces.H.
bool binCumulative_ protected
Should bin data be cumulative?
Definition at line 287 of file forces.H.
bool initialised_ protected
Initialised flag.
Definition at line 291 of file forces.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/forces/forces/forces.H
src/postProcessing/functionObjects/forces/forces/forces.C