OpenFOAM: filteredLinear2Limiter< LimiterFunc > Class Template Reference
filteredLinear2Limiter< LimiterFunc > Class Template Reference
Class to generate weighting factors for the filteredLinear2 differencing scheme.
Public Member Functions
filteredLinear2Limiter (Istream &is)
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType &phiP, const typename LimiterFunc::phiType &phiN, const typename LimiterFunc::gradPhiType &gradcP, const typename LimiterFunc::gradPhiType &gradcN, const vector &d) const
Detailed Description
template<class LimiterFunc>
class Foam::filteredLinear2Limiter< LimiterFunc >
Class to generate weighting factors for the filteredLinear2 differencing scheme.
The aim is to remove high-frequency modes with "staggering" characteristics by comparing the face gradient with both neighbouring cell gradients and introduce small amounts of upwind in order to damp these modes.
Used in conjunction with the template class LimitedScheme.
Source files
filteredLinear2.H
filteredLinear2.C
Definition at line 57 of file filteredLinear2.H.
Constructor & Destructor Documentation
filteredLinear2Limiter (Istream & is) inline
Definition at line 79 of file filteredLinear2.H.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and filteredLinear2Limiter< LimiterFunc >::limiter().
Member Function Documentation
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType & phiP, const typename LimiterFunc::phiType & phiN, const typename LimiterFunc::gradPhiType & gradcP, const typename LimiterFunc::gradPhiType & gradcN, const vector & d) const inline
Definition at line 104 of file filteredLinear2.H.
References Foam::mag(), Foam::max(), and Foam::min().
Referenced by filteredLinear2Limiter< LimiterFunc >::filteredLinear2Limiter().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/filteredLinear2/filteredLinear2.H