OpenFOAM: fvMeshDistribute Class Reference
fvMeshDistribute Class Reference
Sends/receives parts of mesh+fvfields to neighbouring processors. Used in load balancing.
Public Member Functions
ClassName ("fvMeshDistribute")
fvMeshDistribute (fvMesh &mesh, const scalar mergeTol)
Construct from mesh and absolute merge tolerance.
autoPtr< mapDistributePolyMesh > distribute (const labelList &dist)
Send cells to neighbours according to distribution.
template<class T >
void saveInternalFields (PtrList< Field< T > > &iflds) const
template<class T >
void mapExposedFaces (const mapPolyMesh &map, const PtrList< Field< T > > &oldFlds)
Static Public Member Functions
static labelList countCells (const labelList &)
Helper function: count cells per processor in wanted distribution.
static void printCoupleInfo (const primitiveMesh &, const labelList &, const labelList &, const labelList &, const labelList &)
Print some info on coupling data.
template<class GeoField >
static void printFieldInfo (const fvMesh &)
Print some field info.
static void printMeshInfo (const fvMesh &)
Print some info on mesh.
Detailed Description
Sends/receives parts of mesh+fvfields to neighbouring processors. Used in load balancing.
Input is per local cell the processor it should move to. Moves meshes and volFields/surfaceFields and returns map which can be used to distribute other.
Notes:
does not handle cyclics. Will probably handle separated proc patches.
if all cells move off processor also all its processor patches will get deleted so comms might be screwed up (since e.g. globalMeshData expects procPatches on all)
initial mesh has to have procPatches last and all normal patches common to all processors and in the same order. This is checked.
faces are matched topologically but points on the faces are not. So expect problems -on separated patches (cyclics?) -on zero sized processor edges.
Source files
fvMeshDistribute.H
fvMeshDistribute.C
fvMeshDistributeTemplates.C
Definition at line 70 of file fvMeshDistribute.H.
Constructor & Destructor Documentation
fvMeshDistribute (fvMesh & mesh, const scalar mergeTol)
Construct from mesh and absolute merge tolerance.
Definition at line 1453 of file fvMeshDistribute.C.
References fvMeshDistribute::countCells().
Member Function Documentation
ClassName ("fvMeshDistribute")
Foam::labelList countCells (const labelList & distribution) static
Helper function: count cells per processor in wanted distribution.
Definition at line 1463 of file fvMeshDistribute.C.
References Foam::abort(), fvMeshDistribute::distribute(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, and UPstream::nProcs().
Referenced by meshRefinement::balance(), fvMeshDistribute::distribute(), and fvMeshDistribute::fvMeshDistribute().
Foam::autoPtr< Foam::mapDistributePolyMesh > distribute (const labelList & dist)
Send cells to neighbours according to distribution.
(for every cell the new proc)
Definition at line 1487 of file fvMeshDistribute.C.
References Foam::abort(), fvMeshAdder::add(), polyMesh::boundaryMesh(), fvMeshSubset::cellMap(), polyMesh::cellZones(), polyBoundaryMesh::checkParallelSync(), fvMesh::clearOut(), fvMeshDistribute::countCells(), Foam::endl(), fvMeshSubset::faceFlipMap(), Foam::faceMap(), fvMeshSubset::faceMap(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, PstreamBuffers::finishedSends(), forAll, forAllConstIter(), Pstream::gatherList(), Foam::identity(), Foam::inplaceRenumber(), Foam::inplaceReorder(), HashSet< Key, Hash >::insert(), UPstream::myProcNo(), objectRegistry::names(), ZoneMesh< ZoneType, MeshType >::names(), polyBoundaryMesh::names(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, UPstream::nonBlocking, primitiveMesh::nPoints(), UPstream::nProcs(), UPstream::parRun(), patches, patchi, fvMeshSubset::patchMap(), fvMeshSubset::pointMap(), polyMesh::pointZones(), Foam::Pout, fvMeshDistribute::printMeshInfo(), Foam::renumber(), polyMesh::resetMotion(), HashTable< T, Key, Hash >::resize(), Pstream::scatterList(), polyMesh::setInstance(), fvMeshSubset::setLargeCellSubset(), List< T >::size(), UPtrList< T >::size(), dictionary::subDict(), fvMeshSubset::subMesh(), fvMesh::time(), Time::timeName(), List< T >::transfer(), Field< Type >::typeName, List< T >::xfer(), HashTable< T, Key, Hash >::xfer(), and Foam::Zero.
Referenced by meshRefinement::balance(), and fvMeshDistribute::countCells().
void printCoupleInfo (const primitiveMesh & mesh, const labelList & sourceFace, const labelList & sourceProc, const labelList & sourcePatch, const labelList & sourceNewNbrProc) static
Print some info on coupling data.
Definition at line 300 of file fvMeshDistribute.C.
References Foam::abort(), mapAddedPolyMesh::addedFaceMap(), fvMesh::addFvPatches(), fvMeshTools::addPatch(), polyMesh::addZones(), polyPatch::boundaryMesh(), polyMesh::boundaryMesh(), polyMesh::cellZones(), polyTopoChange::changeMesh(), polyPatch::coupled(), polyMesh::defaultRegion, dict, HashTableCore::end(), Foam::endl(), polyPatch::faceCells(), primitiveMesh::faceCentres(), Foam::faceMap(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), Foam::findIndex(), polyMeshAdder::findSharedPoints(), ZoneMesh< ZoneType, MeshType >::findZoneID(), faceZone::flipMap(), forAll, forAllReverse, found, removeCells::getExposedFaces(), Foam::identity(), lessProcPatches::lessProcPatches(), polyMeshAdder::mergePoints(), UPstream::myProcNo(), patchIdentifier::name(), IOobject::name(), polyBoundaryMesh::names(), primitiveMesh::nCells(), processorPolyPatch::neighbProcNo(), polyPatch::New(), newPointi, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, IOobject::NO_READ, mapAddedPolyMesh::nOldInternalFaces(), primitiveMesh::nPoints(), UPstream::nProcs(), mapAddedPolyMesh::oldFaceMap(), processorPolyPatch::owner(), cyclicPolyPatch::owner(), patches, patchi, polyMesh::points(), polyMesh::pointZones(), Foam::Pout, fvMeshTools::reorderPatches(), Foam::returnReduce(), polyTopoChange::setAction(), removeCells::setRefinement(), CompactListList< T, Container >::setSize(), List< T >::setSize(), List< T >::size(), UPtrList< T >::size(), HashTable< T, Key, Hash >::size(), Foam::sortedOrder(), polyPatch::start(), syncTools::swapBoundaryFaceList(), Time::timeName(), coupledPolyPatch::transform(), faceZone::whichFace(), and Foam::xferMove().
Referenced by fvMeshDistribute::printMeshInfo().
void printFieldInfo (const fvMesh & mesh) static
Print some field info.
Definition at line 31 of file fvMeshDistributeTemplates.C.
References Foam::abort(), Foam::endl(), Foam::faceMap(), mapPolyMesh::faceMap(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, forAllConstIter(), forAllIter, mapPolyMesh::oldPatchStarts(), fvsPatchField< Type >::patch(), patchi, Foam::Pout, and HashTable< T, Key, Hash >::size().
void printMeshInfo (const fvMesh & mesh) static
Print some info on mesh.
Definition at line 240 of file fvMeshDistribute.C.
References fvMesh::boundary(), polyMesh::cellZones(), Foam::endl(), polyMesh::faceZones(), forAll, patchIdentifier::name(), zone::name(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, primitiveMesh::nPoints(), patches, patchi, polyMesh::points(), polyMesh::pointZones(), Foam::Pout, fvMeshDistribute::printCoupleInfo(), List< T >::size(), UPtrList< T >::size(), and polyPatch::start().
Referenced by fvMeshDistribute::distribute().
void saveInternalFields (PtrList< Field< T > > & iflds) const
Definition at line 152 of file fvMeshDistributeTemplates.C.
References fld(), forAllConstIter(), and HashTable< T, Key, Hash >::size().
void mapExposedFaces (const mapPolyMesh & map, const PtrList< Field< T > > & oldFlds)
Definition at line 180 of file fvMeshDistributeTemplates.C.
References Foam::abort(), IOobject::AUTO_WRITE, fvMeshSubset::baseMesh(), token::BEGIN_BLOCK, token::END_BLOCK, Foam::endl(), Foam::faceMap(), mapPolyMesh::faceMap(), Foam::FatalError, FatalErrorIn, fieldNames, fields, fld(), mapPolyMesh::flipFaceFlux(), forAll, forAllIter, HashTable< T, Key, Hash >::found(), fvMeshSubset::interpolate(), objectRegistry::lookupObject(), mesh, token::NL, IOobject::NO_READ, fvsPatchField< Type >::patch(), patchi, Foam::Pout, PtrList< T >::set(), PtrList< T >::setSize(), List< T >::size(), HashTable< T, Key, Hash >::size(), dictionary::subDict(), fvMesh::time(), and Time::timeName().
The documentation for this class was generated from the following files:
src/dynamicMesh/fvMeshDistribute/fvMeshDistribute.H
src/dynamicMesh/fvMeshDistribute/fvMeshDistribute.C
src/dynamicMesh/fvMeshDistribute/fvMeshDistributeTemplates.C