OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
forceCoeffs Class Reference
FunctionObjects » Forces function objects
This function object extends the Foam::forces function object by providing lift, drag and moment coefficients. The data can optionally be output into bins, defined in a given direction.
Public Member Functions
TypeName ("forceCoeffs")
Runtime type information.
forceCoeffs (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~forceCoeffs ()
Destructor.
virtual void read (const dictionary &)
Read the forces data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write the forces.
Public Member Functions inherited from forces
TypeName ("forces")
Runtime type information.
forces (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false, const bool readFields=true)
Construct for given objectRegistry and dictionary.
forces (const word &name, const objectRegistry &, const labelHashSet &patchSet, const word &pName, const word &UName, const word &rhoName, const scalar rhoInf, const scalar pRef, const coordinateSystem &coordSys)
Construct from components.
virtual ~forces ()
Destructor.
virtual const word & name () const
Return name of the set of forces.
virtual void calcForcesMoment ()
Calculate the forces and moments.
virtual vector forceEff () const
Return the total force.
virtual vector momentEff () const
Return the total moment.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFiles
functionObjectFiles (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
functionObjectFiles (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFiles (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
virtual ~functionObjectFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Member Functions
static bool viable (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Return true if the construction of this functionObject is viable.
Static Public Member Functions inherited from forces
static bool viable (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Return true if the construction of this functionObject is viable.
Protected Member Functions
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from forces
wordList createFileNames (const dictionary &dict) const
Create file names for forces and bins.
void initialise ()
Initialise the fields.
tmp< volSymmTensorField > devRhoReff () const
Return the effective viscous stress (laminar + turbulent).
tmp< volScalarField > mu () const
Dynamic viscosity field.
tmp< volScalarField > rho () const
Return rho if rhoName is specified otherwise rhoRef.
scalar rho (const volScalarField &p) const
Return rhoRef if the pressure field is dynamic, i.e. p/rho.
void applyBins (const vectorField &Md, const vectorField &fN, const vectorField &fT, const vectorField &fP, const vectorField &d)
Accumulate bin data.
void writeForces ()
Helper function to write force data.
void writeBins ()
Helper function to write bin data.
forces (const forces &)
Disallow default bitwise copy construct.
void operator= (const forces &)
Disallow default bitwise assignment.
Protected Member Functions inherited from functionObjectFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
functionObjectFiles (const functionObjectFiles &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Attributes inherited from forces
word name_
Name of this set of forces,.
const objectRegistry & obr_
Switch log_
Switch to send output to Info as well as to file.
List< Field< vector > > force_
Pressure, viscous and porous force per bin.
List< Field< vector > > moment_
Pressure, viscous and porous moment per bin.
labelHashSet patchSet_
Patches to integrate forces over.
word pName_
Name of pressure field.
word UName_
Name of velocity field.
word rhoName_
Name of density field (optional)
Switch directForceDensity_
Is the force density being supplied directly?
word fDName_
The name of the force density (fD) field.
scalar rhoRef_
Reference density needed for incompressible calculations.
scalar pRef_
Reference pressure.
coordinateSystem coordSys_
Coordinate system used when evaluting forces/moments.
bool localSystem_
Flag to indicate whether we are using a local co-ordinate sys.
bool porosity_
Flag to include porosity effects.
label nBin_
Number of bins.
vector binDir_
Direction used to determine bin orientation.
scalar binDx_
Distance between bin divisions.
scalar binMin_
Minimum bin bounds.
List< point > binPoints_
Bin positions along binDir.
bool binCumulative_
Should bin data be cumulative?
bool initialised_
Initialised flag.
Protected Attributes inherited from functionObjectFile
const objectRegistry & obr_
Reference to the objectRegistry.
const word prefix_
Prefix.
Detailed Description
This function object extends the Foam::forces function object by providing lift, drag and moment coefficients. The data can optionally be output into bins, defined in a given direction.
Example of function object specification:
forceCoeffs1
{
    type        forceCoeffs;
    functionObjectLibs ("libforces.so");
    ...
    log         yes;
    patches     (walls);
    liftDir     (0 1 0);
    dragDir     (-1 0 0);
    pitchAxis   (0 0 1);
    magUInf     100;
    lRef        3.5;
    Aref        2.2;
    binData
    {
        nBin        20;
        direction   (1 0 0);
        cumulative  yes;
    }
}
Function object usage
Property Description Required Default value
type type name: forces yes
log write force data to standard output no no
patches patches included in the forces calculation yes
liftDir lift direction yes
dragDir drag direction yes
pitchAxis picth axis yes
magUInf free stream velocity magnitude yes
lRef reference length scale for moment calculations yes
Aref reference area yes
Bin data is optional, but if the dictionary is present, the entries must be defined according o
nBin number of data bins yes
direction direction along which bins are defined yes
cumulative bin data accumulated with incresing distance yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject Foam::forces
Source files
forceCoeffs.H
forceCoeffs.C
IOforceCoeffs.H
Definition at line 173 of file forceCoeffs.H.
Constructor & Destructor Documentation
forceCoeffs (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 127 of file forceCoeffs.C.
References Foam::endl(), Foam::Info, Foam::read(), and forceCoeffs::viable().
~forceCoeffs () virtual
Destructor.
Definition at line 162 of file forceCoeffs.C.
Member Function Documentation
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from forces.
Definition at line 46 of file forceCoeffs.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::jn(), Foam::name(), Foam::nl, and Foam::tab.
TypeName ("forceCoeffs")
Runtime type information.
bool viable (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false) static
Return true if the construction of this functionObject is viable.
i.e. the prerequisites for construction are available
Definition at line 148 of file forceCoeffs.C.
Referenced by forceCoeffs::forceCoeffs().
void read (const dictionary & dict) virtual
Read the forces data.
Reimplemented from forces.
Definition at line 168 of file forceCoeffs.C.
References dictionary::lookup(), and forces::read().
void execute () virtual
Execute, currently does nothing.
Reimplemented from forces.
Definition at line 186 of file forceCoeffs.C.
void end () virtual
Execute at the final time-loop, currently does nothing.
Reimplemented from forces.
Definition at line 190 of file forceCoeffs.C.
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Reimplemented from forces.
Definition at line 194 of file forceCoeffs.C.
void write () virtual
Write the forces.
Reimplemented from forces.
Definition at line 198 of file forceCoeffs.C.
References forces::calcForcesMoment(), Foam::endl(), forAll, Foam::Info, UPstream::master(), Foam::nl, pDyn(), List< T >::setSize(), List< T >::size(), Foam::sum(), Foam::tab, Foam::type(), and functionObjectFiles::write().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/forces/forceCoeffs/forceCoeffs.H
src/postProcessing/functionObjects/forces/forceCoeffs/forceCoeffs.C