OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fvMeshAdder Class Reference
Adds two fvMeshes without using any polyMesh morphing. Uses polyMeshAdder.
Public Member Functions
ClassName ("fvMeshAdder")
Static Public Member Functions
static autoPtr< mapAddedPolyMesh > add (fvMesh &mesh0, const fvMesh &mesh1, const faceCoupleInfo &coupleInfo, const bool validBoundary=true)
Inplace add mesh to fvMesh. Maps all stored fields. Returns map.
template<class Type >
static void MapVolFields (const mapAddedPolyMesh &, const fvMesh &mesh, const fvMesh &meshToAdd)
Map all volFields of Type.
template<class Type >
static void MapSurfaceFields (const mapAddedPolyMesh &, const fvMesh &mesh, const fvMesh &meshToAdd)
Map all surfaceFields of Type.
template<class Type >
static void MapDimFields (const mapAddedPolyMesh &, const fvMesh &mesh, const fvMesh &meshToAdd)
Map all DimensionedFields of Type.
Static Public Member Functions inherited from polyMeshAdder
static autoPtr< polyMesh > add (const IOobject &io, const polyMesh &mesh0, const polyMesh &mesh1, const faceCoupleInfo &coupleInfo, autoPtr< mapAddedPolyMesh > &mapPtr)
Add two polyMeshes. Returns new polyMesh and map construct.
static autoPtr< mapAddedPolyMesh > add (polyMesh &mesh0, const polyMesh &mesh1, const faceCoupleInfo &coupleInfo, const bool validBoundary=true)
Inplace add mesh to polyMesh. Returns map construct.
static Map< label > findSharedPoints (const polyMesh &, const scalar mergeTol)
Find topologically and geometrically shared points.
static void mergePoints (const polyMesh &, const Map< label > &pointToMaster, polyTopoChange &meshMod)
Helper: Merge points.
Detailed Description
Adds two fvMeshes without using any polyMesh morphing. Uses polyMeshAdder.
Source files
fvMeshAdder.H
fvMeshAdder.C
fvMeshAdderTemplates.C
Definition at line 64 of file fvMeshAdder.H.
Member Function Documentation
ClassName ("fvMeshAdder")
Foam::autoPtr< Foam::mapAddedPolyMesh > add (fvMesh & mesh0, const fvMesh & mesh1, const faceCoupleInfo & coupleInfo, const bool validBoundary = true) static
Inplace add mesh to fvMesh. Maps all stored fields. Returns map.
Definition at line 71 of file fvMeshAdder.C.
References polyMeshAdder::add(), fvMesh::boundary(), polyMesh::boundaryMesh(), fvMesh::clearOut(), forAll, fvPatch::New(), patches, patchi, PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
Referenced by fvMeshDistribute::distribute().
void MapVolFields (const mapAddedPolyMesh & meshMap, const fvMesh & mesh, const fvMesh & meshToAdd) static
Map all volFields of Type.
Definition at line 250 of file fvMeshAdderTemplates.C.
References mapAddedPolyMesh::addedFaceMap(), mapAddedPolyMesh::addedPatchMap(), HashTable< T, Key, Hash >::begin(), fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), polyMesh::boundaryMesh(), HashTableCore::end(), Foam::endl(), fields, fld(), forAll, HashTable< T, Key, Hash >::found(), fvMeshAdder::MapSurfaceFields(), DimensionedField< Type, GeoMesh >::mesh(), OSstream::name(), IOobject::name(), primitiveMesh::nInternalFaces(), mapAddedPolyMesh::oldFaceMap(), mapAddedPolyMesh::oldPatchMap(), mapAddedPolyMesh::oldPatchSizes(), mapAddedPolyMesh::oldPatchStarts(), patchi, Foam::Pout, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), PtrList< T >::reorder(), Field< Type >::rmap(), PtrList< T >::set(), PtrList< T >::setSize(), List< Type >::setSize(), List< T >::size(), UPtrList< T >::size(), polyPatch::start(), and WarningInFunction.
void MapSurfaceFields (const mapAddedPolyMesh & meshMap, const fvMesh & mesh, const fvMesh & meshToAdd) static
Map all surfaceFields of Type.
Definition at line 569 of file fvMeshAdderTemplates.C.
References mapAddedPolyMesh::addedCellMap(), HashTable< T, Key, Hash >::begin(), HashTableCore::end(), Foam::endl(), fields, fld(), HashTable< T, Key, Hash >::found(), fvMeshAdder::MapDimFields(), DimensionedField< Type, GeoMesh >::mesh(), OSstream::name(), fileName::name(), primitiveMesh::nCells(), mapAddedPolyMesh::oldCellMap(), Foam::Pout, Field< Type >::rmap(), List< Type >::setSize(), and WarningInFunction.
Referenced by fvMeshAdder::MapVolFields().
void MapDimFields (const mapAddedPolyMesh & meshMap, const fvMesh & mesh, const fvMesh & meshToAdd) static
Map all DimensionedFields of Type.
Definition at line 666 of file fvMeshAdderTemplates.C.
References HashTable< T, Key, Hash >::begin(), HashTableCore::end(), Foam::endl(), fields, fld(), HashTable< T, Key, Hash >::found(), OSstream::name(), fileName::name(), Foam::Pout, and WarningIn.
Referenced by fvMeshAdder::MapSurfaceFields().
The documentation for this class was generated from the following files:
src/dynamicMesh/fvMeshAdder/fvMeshAdder.H
src/dynamicMesh/fvMeshAdder/fvMeshAdder.C
src/dynamicMesh/fvMeshAdder/fvMeshAdderTemplates.C