OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
functionObjectFile Class Reference
Base class for output file data handling.
Public Member Functions
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
virtual ~functionObjectFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Attributes
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void writeFileHeader (const label i=0)
File header information.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes
const objectRegistry & obr_
Reference to the objectRegistry.
const word prefix_
Prefix.
Detailed Description
Base class for output file data handling.
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
functionObjectFile.H
functionObjectFile.C
Definition at line 54 of file functionObjectFile.H.
Constructor & Destructor Documentation
functionObjectFile (const functionObjectFile &) protected
Disallow default bitwise copy construct.
Referenced by functionObjectFile::valueWidth().
functionObjectFile (const objectRegistry & obr, const word & prefix)
Construct from objectRegistry.
Definition at line 94 of file functionObjectFile.C.
~functionObjectFile () virtual
Destructor.
Definition at line 106 of file functionObjectFile.C.
Member Function Documentation
void initStream (Ostream & os) const protected virtual
Initialise the output stream for writing.
Definition at line 39 of file functionObjectFile.C.
References functionObjectFile::charWidth(), Foam::scientific(), IOstream::setf(), and Ostream::width().
Referenced by functionObjectFiles::createFiles().
Foam::fileName baseFileDir () const protected virtual
Return the base directory for output.
Definition at line 46 of file functionObjectFile.C.
References polyMesh::defaultRegion, mesh, IOobject::name(), functionObjectFile::obr_, functionObjectFile::outputPrefix, UPstream::parRun(), Time::path(), and objectRegistry::time().
Referenced by functionObjectFile::baseTimeDir(), and functionObjectFiles::createFiles().
Foam::fileName baseTimeDir () const protected virtual
Return the base directory for the current time value.
Definition at line 75 of file functionObjectFile.C.
References functionObjectFile::baseFileDir(), functionObjectFile::obr_, functionObjectFile::prefix_, objectRegistry::time(), and Time::timeName().
void writeFileHeader (const label i = 0) protected virtual
File header information.
Reimplemented in faceSource, cellSource, forces, forceCoeffs, fieldMinMax, fieldValueDelta, wallShearStress, cloudInfo, and residuals.
Definition at line 81 of file functionObjectFile.C.
Referenced by functionObjectFiles::createFiles().
Foam::Omanip< int > valueWidth (const label offset = 0) const protected virtual
Return the value width when writing to stream with optional offset.
Definition at line 85 of file functionObjectFile.C.
References functionObjectFile::addChars, IOstream::defaultPrecision(), functionObjectFile::functionObjectFile(), and Foam::setw().
void operator= (const functionObjectFile &) protected
Disallow default bitwise assignment.
void writeCommented (Ostream & os, const string & str) const
Write a commented string to stream.
Definition at line 119 of file functionObjectFile.C.
References functionObjectFile::charWidth(), Foam::setw(), and functionObjectFile::writeTabbed().
Referenced by functionObjectFile::charWidth().
void writeTabbed (Ostream & os, const string & str) const
Write a tabbed string to stream.
Definition at line 130 of file functionObjectFile.C.
References functionObjectFile::charWidth(), Foam::setw(), Foam::tab, and functionObjectFile::writeHeader().
Referenced by functionObjectFile::writeCommented(), and residuals::writeFileHeader().
void writeHeader (Ostream & os, const string & str) const
Write a commented header to stream.
Definition at line 140 of file functionObjectFile.C.
References functionObjectFile::charWidth(), Foam::nl, Foam::setf(), and Foam::setw().
Referenced by functionObjectFile::writeTabbed().
void writeTime (Ostream & os) const
Write the current time to stream.
Definition at line 150 of file functionObjectFile.C.
References functionObjectFile::charWidth(), functionObjectFile::obr_, Foam::setw(), objectRegistry::time(), and Time::timeName().
void writeHeaderValue (Ostream & os, const string & property, const Type & value) const
Write a (commented) header property and value pair.
Definition at line 30 of file functionObjectFileTemplates.C.
References Foam::nl, Foam::setf(), and Foam::setw().
Foam::label charWidth () const
Return width of character stream output.
Definition at line 112 of file functionObjectFile.C.
References functionObjectFile::addChars, IOstream::defaultPrecision(), and functionObjectFile::writeCommented().
Referenced by functionObjectFile::initStream(), functionObjectFile::writeCommented(), functionObjectFile::writeHeader(), functionObjectFile::writeTabbed(), and functionObjectFile::writeTime().
Member Data Documentation
const objectRegistry& obr_ protected
Reference to the objectRegistry.
Definition at line 62 of file functionObjectFile.H.
Referenced by functionObjectFile::baseFileDir(), functionObjectFile::baseTimeDir(), functionObjectFiles::createFiles(), and functionObjectFile::writeTime().
const word prefix_ protected
Prefix.
Definition at line 65 of file functionObjectFile.H.
Referenced by functionObjectFile::baseTimeDir(), and functionObjectFiles::createFiles().
const Foam::word outputPrefix = "postProcessing" static
Directory prefix.
Definition at line 95 of file functionObjectFile.H.
Referenced by functionObjectFile::baseFileDir().
Foam::label addChars = 7 static
Additional characters for writing.
Definition at line 98 of file functionObjectFile.H.
Referenced by functionObjectFile::charWidth(), and functionObjectFile::valueWidth().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObjectFile/functionObjectFile.H
src/OpenFOAM/db/functionObjects/functionObjectFile/functionObjectFile.C
src/OpenFOAM/db/functionObjects/functionObjectFile/functionObjectFileTemplates.C