OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
functionObjectList Class Reference
List of function objects with start(), execute() and end() functions that is called for each object.
Public Member Functions
functionObjectList (const Time &, const bool execution=true)
Construct from Time and the execution setting.
functionObjectList (const Time &t, const dictionary &parentDict, const bool execution=true)
Construct from Time, a dictionary with "functions" entry.
~functionObjectList ()
Destructor.
void clear ()
Clear the list of function objects.
label findObjectID (const word &name) const
Find the ID of a given function object by name.
void on ()
Switch the function objects on.
void off ()
Switch the function objects off.
bool status () const
Return the execution status (on/off) of the function objects.
bool start ()
Called at the start of the time-loop.
bool execute (const bool forceWrite=false)
Called at each ++ or += of the time-loop. forceWrite overrides.
bool end ()
Called when Time::run() determines that the time-loop exits.
bool timeSet ()
Called when time was set at the end of the Time::operator++.
bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
bool read ()
Read and set the function objects if their data have changed.
void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Static Public Member Functions
static autoPtr< functionObjectList > New (const argList &args, const Time &runTime, dictionary &functionObjectsDict)
Construct and return a functionObjectList for an application.
Detailed Description
List of function objects with start(), execute() and end() functions that is called for each object.
See also
Foam::functionObject and Foam::OutputFilterFunctionObject
Source files
functionObjectList.H
functionObjectList.C
Definition at line 58 of file functionObjectList.H.
Constructor & Destructor Documentation
functionObjectList (const Time & t, const bool execution = true)
Construct from Time and the execution setting.
The functionObject specifications are read from the controlDict
Definition at line 64 of file functionObjectList.C.
functionObjectList (const Time & t, const dictionary & parentDict, const bool execution = true)
Construct from Time, a dictionary with "functions" entry.
and the execution setting.
Parameters
[in] t - the other Time instance to construct from
[in] parentDict - the parent dictionary containing a "functions" entry, which can either be a list or a dictionary of functionObject specifications.
[in] execution - whether the function objects should execute or not. Default: true.
Definition at line 80 of file functionObjectList.C.
References functionObjectList::New().
~functionObjectList ()
Destructor.
Definition at line 134 of file functionObjectList.C.
Member Function Documentation
Foam::autoPtr< Foam::functionObjectList > New (const argList & args, const Time & runTime, dictionary & functionObjectsDict) static
Construct and return a functionObjectList for an application.
If the "dict" argument is specified the functionObjectList is constructed from that dictionary which is returned as functionObjectsDict otherwise the functionObjectList is constructed from the "functions" sub-dictionary of "system/controlDict"
Definition at line 97 of file functionObjectList.C.
References IOobject::MUST_READ_IF_MODIFIED, argList::optionFound(), and autoPtr< T >::reset().
Referenced by functionObjectList::functionObjectList().
void clear ()
Clear the list of function objects.
Definition at line 140 of file functionObjectList.C.
References PtrList< T >::clear(), and HashTable< T, Key, Hash >::clear().
Foam::label findObjectID (const word & name) const
Find the ID of a given function object by name.
Definition at line 149 of file functionObjectList.C.
References forAll, and Foam::name().
void on ()
Switch the function objects on.
Definition at line 163 of file functionObjectList.C.
void off ()
Switch the function objects off.
Definition at line 169 of file functionObjectList.C.
bool status () const
Return the execution status (on/off) of the function objects.
Definition at line 176 of file functionObjectList.C.
bool start ()
Called at the start of the time-loop.
Definition at line 182 of file functionObjectList.C.
References functionObjectList::read().
bool execute (const bool forceWrite = false)
Called at each ++ or += of the time-loop. forceWrite overrides.
the usual outputControl behaviour and forces writing always (used in post-processing mode)
Definition at line 188 of file functionObjectList.C.
References forAll, UPtrList< T >::operator[](), and functionObjectList::read().
bool end ()
Called when Time::run() determines that the time-loop exits.
Definition at line 209 of file functionObjectList.C.
References forAll, UPtrList< T >::operator[](), and functionObjectList::read().
bool timeSet ()
Called when time was set at the end of the Time::operator++.
Definition at line 230 of file functionObjectList.C.
References forAll, UPtrList< T >::operator[](), and functionObjectList::read().
bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Definition at line 251 of file functionObjectList.C.
References forAll, UPtrList< T >::operator[](), and functionObjectList::read().
bool read ()
Read and set the function objects if their data have changed.
Definition at line 272 of file functionObjectList.C.
References PtrList< T >::clear(), HashTable< T, Key, Hash >::clear(), dict, entry::dict(), dictionary::digest(), error::dontThrowExceptions(), Foam::endl(), Foam::exit(), Foam::FatalError, Foam::FatalIOError, FatalIOErrorInFunction, forAllConstIter(), Foam::Info, HashTable< T, Key, Hash >::insert(), IOWarningInFunction, entry::isDict(), dictionary::lookupEntryPtr(), dictionary::lookupOrDefault(), functionObject::New(), Foam::nl, autoPtr< T >::ptr(), functionObject::read(), PtrList< T >::set(), PtrList< T >::setSize(), List< T >::setSize(), DLListBase::size(), error::throwExceptions(), PtrList< T >::transfer(), HashTable< T, Key, Hash >::transfer(), autoPtr< T >::valid(), and WarningInFunction.
Referenced by functionObjectList::adjustTimeStep(), functionObjectList::end(), functionObjectList::execute(), Time::readModifiedObjects(), functionObjectList::start(), and functionObjectList::timeSet().
void updateMesh (const mapPolyMesh & mpm)
Update for changes of mesh.
Definition at line 410 of file functionObjectList.C.
References forAll, and UPtrList< T >::operator[]().
void movePoints (const polyMesh & mesh)
Update for changes of mesh.
Definition at line 422 of file functionObjectList.C.
References forAll, and UPtrList< T >::operator[]().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObjectList/functionObjectList.H
src/OpenFOAM/db/functionObjects/functionObjectList/functionObjectList.C