OpenFOAM: filteredLinear3Limiter< LimiterFunc > Class Template Reference
filteredLinear3Limiter< LimiterFunc > Class Template Reference
Class to generate weighting factors for the filteredLinear differencing scheme.
Public Member Functions
filteredLinear3Limiter (Istream &is)
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType &phiP, const typename LimiterFunc::phiType &phiN, const typename LimiterFunc::gradPhiType &gradcP, const typename LimiterFunc::gradPhiType &gradcN, const vector &d) const
Detailed Description
template<class LimiterFunc>
class Foam::filteredLinear3Limiter< LimiterFunc >
Class to generate weighting factors for the filteredLinear differencing scheme.
The aim is to remove high-frequency modes with "staggering" characteristics by comparing the face gradient with both neighbouring cell gradients and introduce small amounts of upwind in order to damp these modes.
Used in conjunction with the template class LimitedScheme.
Source files
filteredLinear3.H
filteredLinear3.C
Definition at line 57 of file filteredLinear3.H.
Constructor & Destructor Documentation
filteredLinear3Limiter (Istream & is) inline
Definition at line 70 of file filteredLinear3.H.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and filteredLinear3Limiter< LimiterFunc >::limiter().
Member Function Documentation
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType & phiP, const typename LimiterFunc::phiType & phiN, const typename LimiterFunc::gradPhiType & gradcP, const typename LimiterFunc::gradPhiType & gradcN, const vector & d) const inline
Definition at line 84 of file filteredLinear3.H.
References Foam::max(), Foam::min(), and Foam::sqr().
Referenced by filteredLinear3Limiter< LimiterFunc >::filteredLinear3Limiter().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/filteredLinear3/filteredLinear3.H