OpenFOAM: Function1< Type > Class Template Reference
Function1< Type > Class Template Reference
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or table, and provide functions to return the (interpolated) value, and integral between limits.
Public Member Functions
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Runtime type information.
Function1 (const word &entryName)
Construct from entry name.
Function1 (const Function1< Type > &de)
Copy constructor.
virtual tmp< Function1< Type > > clone () const
Construct and return a clone.
virtual ~Function1 ()
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Attributes
const word name_
Name of entry.
Friends
Ostream & operator (Ostream &os, const Function1< Type > &de)
Ostream Operator.
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::Function1< Type >
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or table, and provide functions to return the (interpolated) value, and integral between limits.
Source files
Function1.H
Function1.C
Function1New.C
Definition at line 53 of file Function1.H.
Constructor & Destructor Documentation
Function1 (const word & entryName)
Construct from entry name.
Function1 (const Function1< Type > & de)
Copy constructor.
~Function1 () virtual
Destructor.
Definition at line 49 of file Function1.C.
Referenced by Function1< Foam::Vector >::clone().
Member Function Documentation
TypeName ("Function1< Type >")
Runtime type information.
Declare runtime constructor selection table
virtual tmp<Function1<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented in Square< Type >, Sine< Type >, CSV< Type >, TableFile< Type >, Polynomial< Type >, Constant< Type >, and Table< Type >.
Definition at line 107 of file Function1.H.
Foam::autoPtr< Foam::Function1< Type > > New (const word & entryName, const dictionary & dict) static
Selector.
Definition at line 32 of file Function1New.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), and Foam::nl.
Referenced by Function1< Foam::Vector >::clone(), and setTimeStepFunctionObject::read().
const Foam::word & name () const
Return the name of the entry.
Definition at line 56 of file Function1.C.
References TableBase< Type >::name_.
Referenced by Function1< Foam::Vector >::clone(), TableFile< Type >::writeData(), CSV< Type >::writeData(), Sine< Type >::writeData(), and Square< Type >::writeData().
void convertTimeBase (const Time & t) virtual
Convert time.
Reimplemented in TableBase< Type >, and Polynomial< Type >.
Definition at line 63 of file Function1.C.
Referenced by Function1< Foam::Vector >::clone().
Type value (const scalar x) const virtual
Return value as a function of (scalar) independent variable.
Reimplemented in Square< Type >, Sine< Type >, TableBase< Type >, Polynomial< Type >, and Constant< Type >.
Definition at line 68 of file Function1.C.
References NotImplemented, and Foam::Zero.
Referenced by Function1< Foam::Vector >::clone(), and Function1< Type >::integrate().
Foam::tmp< Foam::Field< Type > > value (const scalarField & x) const virtual
Return value as a function of (scalar) independent variable.
Definition at line 87 of file Function1.C.
References fld(), forAll, Function1< Type >::integrate(), tmp< T >::ref(), List< T >::size(), and TableBase< Type >::value().
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Reimplemented in TableBase< Type >, Polynomial< Type >, and Constant< Type >.
Definition at line 77 of file Function1.C.
References NotImplemented, Function1< Type >::value(), and Foam::Zero.
Referenced by Function1< Foam::Vector >::clone(), and Function1< Type >::value().
Foam::tmp< Foam::Field< Type > > integrate (const scalarField & x1, const scalarField & x2) const virtual
Integrate between two (scalar) values.
Definition at line 104 of file Function1.C.
References fld(), forAll, TableBase< Type >::integrate(), tmp< T >::ref(), and List< T >::size().
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented in Square< Type >, Sine< Type >, TableBase< Type >, CSV< Type >, Polynomial< Type >, TableFile< Type >, and Constant< Type >.
Definition at line 121 of file Function1.C.
References IOstream::check(), f1, TableBase< Type >::name_, Foam::type(), and Ostream::writeKeyword().
Referenced by Function1< Foam::Vector >::clone(), Constant< Type >::writeData(), TableFile< Type >::writeData(), Polynomial< Type >::writeData(), CSV< Type >::writeData(), TableBase< Type >::writeData(), Sine< Type >::writeData(), and Square< Type >::writeData().
Friends And Related Function Documentation
Ostream& operator (Ostream & os, const Function1< Type > & de) friend
Ostream Operator.
Member Data Documentation
const word name_ protected
Name of entry.
Definition at line 76 of file Function1.H.
Function1
Definition at line 88 of file Function1.H.
dictionary
Definition at line 88 of file Function1.H.
const word& entryName
Definition at line 88 of file Function1.H.
Referenced by Function1< Foam::Vector >::clone().
const word const dictionary& dict
Definition at line 88 of file Function1.H.
Referenced by Function1< Foam::Vector >::clone().
const word const dictionary entryName
Definition at line 88 of file Function1.H.
const word const dictionary dict
Definition at line 88 of file Function1.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Function1/Function1.H
src/OpenFOAM/primitives/functions/Function1/Function1/Function1.C
src/OpenFOAM/primitives/functions/Function1/Function1/Function1New.C