OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fvMatrix< Type > Class Template Reference
A special matrix type and solver, designed for finite volume solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Classes
class fvSolver
Solver class returned by the solver function.
Public Types
typedef GeometricField< Type,
fvsPatchField, surfaceMesh > * surfaceTypeFieldPtr
Declare return type of the faceFluxCorrectionPtr() function.
Public Member Functions
ClassName ("fvMatrix")
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > &, const dimensionSet &)
Construct given a field to solve for.
fvMatrix (const fvMatrix< Type > &)
Construct as copy.
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > &, Istream &)
Construct as copy of tmp<fvMatrix<Type> > deleting argument.
virtual ~fvMatrix ()
Destructor.
const GeometricField< Type,
fvPatchField, volMesh > & psi () const
const dimensionSet & dimensions () const
Field< Type > & source ()
const Field< Type > & source () const
FieldField< Field, Type > & internalCoeffs ()
fvBoundary scalar field containing pseudo-matrix coeffs
FieldField< Field, Type > & boundaryCoeffs ()
fvBoundary scalar field containing pseudo-matrix coeffs
surfaceTypeFieldPtr & faceFluxCorrectionPtr ()
Return pointer to face-flux non-orthogonal correction field.
void setValues (const labelUList &cells, const UList< Type > &values)
Set solution in given cells to the specified values.
void setValues (const labelUList &cells, const UIndirectList< Type > &values)
Set solution in given cells to the specified values.
void setReference (const label celli, const Type &value, const bool forceReference=false)
Set reference level for solution.
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Set reference level for a component of the solution.
void relax (const scalar alpha)
Relax matrix (for steady-state solution).
void relax ()
Relax matrix (for steady-state solution).
void boundaryManipulate (typename GeometricField< Type, fvPatchField, volMesh >::GeometricBoundaryField &values)
Manipulate based on a boundary field.
autoPtr< fvSolver > solver (const dictionary &)
Construct and return the solver.
autoPtr< fvSolver > solver ()
Construct and return the solver.
solverPerformance solve (const dictionary &)
Solve segregated or coupled returning the solution statistics.
solverPerformance solveSegregated (const dictionary &)
Solve segregated returning the solution statistics.
solverPerformance solveCoupled (const dictionary &)
Solve coupled returning the solution statistics.
solverPerformance solve ()
Solve returning the solution statistics.
tmp< Field< Type > > residual () const
Return the matrix residual.
tmp< scalarField > D () const
Return the matrix scalar diagonal.
tmp< Field< Type > > DD () const
Return the matrix Type diagonal.
tmp< volScalarField > A () const
Return the central coefficient.
tmp< GeometricField< Type,
fvPatchField, volMesh > > H () const
Return the H operation source.
tmp< volScalarField > H1 () const
Return H(1)
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux () const
Return the face-flux field from the matrix.
void operator= (const fvMatrix< Type > &)
void operator= (const tmp< fvMatrix< Type > > &)
void negate ()
void operator+= (const fvMatrix< Type > &)
void operator+= (const tmp< fvMatrix< Type > > &)
void operator-= (const fvMatrix< Type > &)
void operator-= (const tmp< fvMatrix< Type > > &)
void operator+= (const DimensionedField< Type, volMesh > &)
void operator+= (const tmp< DimensionedField< Type, volMesh > > &)
void operator+= (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
void operator-= (const DimensionedField< Type, volMesh > &)
void operator-= (const tmp< DimensionedField< Type, volMesh > > &)
void operator-= (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator+= (const zero &)
void operator-= (const zero &)
void operator*= (const DimensionedField< scalar, volMesh > &)
void operator*= (const tmp< DimensionedField< scalar, volMesh > > &)
void operator*= (const tmp< volScalarField > &)
void operator*= (const dimensioned< scalar > &)
template<>
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
template<>
Foam::autoPtr< Foam::fvMatrix
< Foam::scalar >::fvSolver > solver (const dictionary &solverControls)
template<>
Foam::solverPerformance solveSegregated (const dictionary &solverControls)
template<>
Foam::tmp< Foam::scalarField > residual () const
template<>
Foam::tmp< Foam::volScalarField > H () const
template<>
Foam::tmp< Foam::volScalarField > H1 () const
template<>
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
template<>
autoPtr< fvMatrix< scalar >
::fvSolver > solver (const dictionary &)
template<>
solverPerformance solveSegregated (const dictionary &)
template<>
tmp< scalarField > residual () const
template<>
tmp< volScalarField > H () const
template<>
tmp< volScalarField > H1 () const
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from lduMatrix
ClassName ("lduMatrix")
lduMatrix (const lduMesh &)
Construct given an LDU addressed mesh.
lduMatrix (const lduMatrix &)
Construct as copy.
lduMatrix (lduMatrix &, bool reUse)
Construct as copy or re-use as specified.
lduMatrix (const lduMesh &, Istream &)
Construct given an LDU addressed mesh and an Istream.
~lduMatrix ()
Destructor.
const lduMesh & mesh () const
Return the LDU mesh from which the addressing is obtained.
const lduAddressing & lduAddr () const
Return the LDU addressing.
const lduSchedule & patchSchedule () const
Return the patch evaluation schedule.
scalarField & lower ()
scalarField & diag ()
scalarField & upper ()
scalarField & lower (const label size)
scalarField & diag (const label nCoeffs)
scalarField & upper (const label nCoeffs)
const scalarField & lower () const
const scalarField & diag () const
const scalarField & upper () const
bool hasDiag () const
bool hasUpper () const
bool hasLower () const
bool diagonal () const
bool symmetric () const
bool asymmetric () const
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (scalarField &sumOff) const
void Amul (scalarField &, const tmp< scalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix multiplication with updated interfaces.
void Tmul (scalarField &, const tmp< scalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix transpose multiplication with updated interfaces.
void sumA (scalarField &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &) const
Sum the coefficients on each row of the matrix.
void residual (scalarField &rA, const scalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
tmp< scalarField > residual (const scalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
void initMatrixInterfaces (const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const scalarField &psiif, scalarField &result, const direction cmpt) const
Initialise the update of interfaced interfaces.
void updateMatrixInterfaces (const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const scalarField &psiif, scalarField &result, const direction cmpt) const
Update interfaced interfaces for matrix operations.
template<class Type >
tmp< Field< Type > > H (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > H (const tmp< Field< Type > > &) const
tmp< scalarField > H1 () const
template<class Type >
tmp< Field< Type > > faceH (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > faceH (const tmp< Field< Type > > &) const
InfoProxy< lduMatrix > info () const
Return info proxy.
void operator= (const lduMatrix &)
void negate ()
void operator+= (const lduMatrix &)
void operator-= (const lduMatrix &)
void operator*= (const scalarField &)
void operator*= (scalar)
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type > > &tpsi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type > > &tpsi) const
Protected Member Functions
template<class Type2 >
void addToInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
Add patch contribution to internal field.
template<class Type2 >
void addToInternalField (const labelUList &addr, const tmp< Field< Type2 > > &tpf, Field< Type2 > &intf) const
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
Subtract patch contribution from internal field.
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const tmp< Field< Type2 > > &tpf, Field< Type2 > &intf) const
void addBoundaryDiag (scalarField &diag, const direction cmpt) const
void addCmptAvBoundaryDiag (scalarField &diag) const
void addBoundarySource (Field< Type > &source, const bool couples=true) const
template<template< class > class ListType>
void setValuesFromList (const labelUList &cells, const ListType< Type > &values)
Set solution in given cells to the specified values.
Friends
class fvSolver
Declare friendship with the fvSolver class.
tmp< GeometricField< Type,
fvPatchField, volMesh > > operator& (const fvMatrix< Type > &, const DimensionedField< Type, volMesh > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > operator& (const fvMatrix< Type > &, const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > operator& (const tmp< fvMatrix< Type > > &, const DimensionedField< Type, volMesh > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > operator& (const tmp< fvMatrix< Type > > &, const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
Ostream & operator (Ostream &, const fvMatrix< Type > &)
Detailed Description
template<class Type>
class Foam::fvMatrix< Type >
A special matrix type and solver, designed for finite volume solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Source files
fvMatrix.H
fvMatrix.C
fvMatrixSolve.C
fvScalarMatrix.C
Definition at line 68 of file fvPatchField.H.
Member Typedef Documentation
typedef GeometricField<Type, fvsPatchField, surfaceMesh>* surfaceTypeFieldPtr
Declare return type of the faceFluxCorrectionPtr() function.
Definition at line 318 of file fvMatrix.H.
Constructor & Destructor Documentation
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > & psi, const dimensionSet & ds)
Construct given a field to solve for.
Definition at line 274 of file fvMatrix.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::endl(), regIOobject::eventNo(), forAll, Foam::Info, and DimensionedField< Type, GeoMesh >::mesh().
fvMatrix (const fvMatrix< Type > & fvm)
Construct as copy.
Definition at line 330 of file fvMatrix.C.
References Foam::endl(), and Foam::Info.
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > & psi, Istream & is)
Construct as copy of tmp<fvMatrix<Type> > deleting argument.
Construct from Istream given field to solve for
Definition at line 419 of file fvMatrix.C.
References Foam::endl(), forAll, Foam::Info, and DimensionedField< Type, GeoMesh >::mesh().
~fvMatrix () virtual
Destructor.
Definition at line 468 of file fvMatrix.C.
References Foam::endl(), and Foam::Info.
Member Function Documentation
void addToInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Add patch contribution to internal field.
Definition at line 38 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, List< Type >::size(), and UList< T >::size().
void addToInternalField (const labelUList & addr, const tmp< Field< Type2 > > & tpf, Field< Type2 > & intf) const protected
Definition at line 64 of file fvMatrix.C.
void subtractFromInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Subtract patch contribution from internal field.
Definition at line 78 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, List< Type >::size(), and UList< T >::size().
void subtractFromInternalField (const labelUList & addr, const tmp< Field< Type2 > > & tpf, Field< Type2 > & intf) const protected
Definition at line 104 of file fvMatrix.C.
void addBoundaryDiag (scalarField & diag, const direction cmpt) const protected
Definition at line 117 of file fvMatrix.C.
References Foam::component(), and forAll.
Referenced by fvMatrix< Type >::residual().
void addCmptAvBoundaryDiag (scalarField & diag) const protected
Definition at line 135 of file fvMatrix.C.
References Foam::cmptAv(), and forAll.
void addBoundarySource (Field< Type > & source, const bool couples = true) const protected
Definition at line 151 of file fvMatrix.C.
References Foam::cmptMultiply(), fvPatchField< Type >::coupled(), forAll, and fvPatchField< Type >::patchNeighbourField().
Referenced by fvMatrix< Type >::residual().
void setValuesFromList (const labelUList & cells, const ListType< Type > & values) protected
Set solution in given cells to the specified values.
Definition at line 184 of file fvMatrix.C.
References polyMesh::boundaryMesh(), c(), cells, primitiveMesh::cells(), Foam::diag(), forAll, i, internalField(), primitiveMesh::isInternalFace(), j, mesh, fvMesh::neighbour(), fvMesh::owner(), patchi, psi, value(), and polyBoundaryMesh::whichPatch().
ClassName ("fvMatrix< Type >")
const GeometricField<Type, fvPatchField, volMesh>& psi () const inline
Definition at line 281 of file fvMatrix.H.
Referenced by MRFZone::addCoriolis(), MRFSource::addSup(), explicitPorositySource::addSup(), interRegionExplicitPorositySource::addSup(), radialActuationDiskSource::addSup(), interRegionHeatTransferModel::addSup(), SemiImplicitSource< Type >::addSup(), actuationDiskSource::addSup(), rotorDiskSource::addSup(), solidificationMeltingSource::addSup(), effectivenessHeatExchangerSource::addSup(), Foam::checkMethod(), optionList::constrain(), fixedCoeff::correct(), powerLaw::correct(), DarcyForchheimer::correct(), and fixedTemperatureConstraint::setValue().
const dimensionSet& dimensions () const inline
Definition at line 286 of file fvMatrix.H.
Referenced by pressureGradientExplicitSource::addSup(), explicitPorositySource::addSup(), interRegionExplicitPorositySource::addSup(), SemiImplicitSource< Type >::addSup(), rotorDiskSource::addSup(), Foam::checkMethod(), fixedCoeff::correct(), powerLaw::correct(), and DarcyForchheimer::correct().
Field<Type>& source () inline
Definition at line 291 of file fvMatrix.H.
Referenced by MRFZone::addCoriolis(), interRegionExplicitPorositySource::addSup(), radialActuationDiskSource::addSup(), actuationDiskSource::addSup(), solidificationMeltingSource::addSup(), effectivenessHeatExchangerSource::addSup(), fixedCoeff::correct(), DarcyForchheimer::correct(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), ThermoCloud< CloudType >::Sh(), ReactingCloud< CloudType >::Srho(), KinematicCloud< CloudType >::SU(), and ReactingCloud< CloudType >::SYi().
const Field<Type>& source () const inline
Definition at line 296 of file fvMatrix.H.
FieldField<Field, Type>& internalCoeffs () inline
fvBoundary scalar field containing pseudo-matrix coeffs
for internal cells
Definition at line 303 of file fvMatrix.H.
Referenced by gaussConvectionScheme< Type >::fvmDiv(), and gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected().
FieldField<Field, Type>& boundaryCoeffs () inline
fvBoundary scalar field containing pseudo-matrix coeffs
for boundary cells
Definition at line 310 of file fvMatrix.H.
Referenced by gaussConvectionScheme< Type >::fvmDiv(), and gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected().
surfaceTypeFieldPtr& faceFluxCorrectionPtr () inline
Return pointer to face-flux non-orthogonal correction field.
Definition at line 321 of file fvMatrix.H.
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacian().
void setValues (const labelUList & cells, const UList< Type > & values)
Set solution in given cells to the specified values.
and eliminate the corresponding equations from the matrix.
Definition at line 488 of file fvMatrix.C.
Referenced by fixedInternalValueFvPatchField< Type >::manipulateMatrix(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), ExplicitSetValue< Type >::setValue(), and fixedTemperatureConstraint::setValue().
void setValues (const labelUList & cells, const UIndirectList< Type > & values)
Set solution in given cells to the specified values.
and eliminate the corresponding equations from the matrix.
Definition at line 499 of file fvMatrix.C.
void setReference (const label celli, const Type & value, const bool forceReference = false)
Set reference level for solution.
Definition at line 510 of file fvMatrix.C.
References Foam::diag(), and value().
Referenced by Foam::CorrectPhi().
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Set reference level for a component of the solution.
on a given patch face
Definition at line 33 of file fvMatrixSolve.C.
References Foam::diag(), patchi, and value().
void relax (const scalar alpha)
Relax matrix (for steady-state solution).
alpha = 1 : diagonally equal alpha < 1 : diagonally dominant alpha = 0 : do nothing Note: Requires positive diagonal.
Definition at line 525 of file fvMatrix.C.
References Foam::constant::atomic::alpha, Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), Foam::component(), fvPatchField< Type >::coupled(), Foam::diag(), Foam::endl(), forAll, InfoIn, Foam::mag(), Foam::max(), UPstream::msgType(), Foam::nl, Foam::reduce(), Foam::returnReduce(), List< Type >::size(), and List< T >::size().
Referenced by dynamicLagrangian< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), scalarTransport::execute(), and thermalBaffle::solveEnergy().
void relax ()
Relax matrix (for steady-state solution).
alpha is read from controlDict
Definition at line 677 of file fvMatrix.C.
References Foam::name(), and relax().
void boundaryManipulate (typename GeometricField< Type, fvPatchField, volMesh >::GeometricBoundaryField & values)
Manipulate based on a boundary field.
Definition at line 694 of file fvMatrix.C.
References forAll.
autoPtr<fvSolver> solver (const dictionary &)
Construct and return the solver.
Use the given solver controls
Foam::autoPtr< typename Foam::fvMatrix< Type >::fvSolver > solver ()
Construct and return the solver.
Solver controls read from fvSolution
Definition at line 285 of file fvMatrixSolve.C.
Foam::solverPerformance solve (const dictionary & solverControls)
Solve segregated or coupled returning the solution statistics.
Use the given solver controls
Definition at line 57 of file fvMatrixSolve.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, Foam::Info, dictionary::lookupOrDefault(), messageStream::masterStream(), mesh, dictionary::readIfPresent(), and Foam::type().
Referenced by Implicit< CloudType >::cacheFields(), dynamicLagrangian< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), Foam::CorrectPhi(), scalarTransport::execute(), thermalBaffle::solveEnergy(), and kinematicSingleLayer::solveThickness().
Foam::solverPerformance solveSegregated (const dictionary & solverControls)
Solve segregated returning the solution statistics.
Use the given solver controls
Definition at line 105 of file fvMatrixSolve.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Field< Type >::component(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::diag(), Foam::endl(), Foam::Info, GeometricField< Type, PatchField, GeoMesh >::internalField(), messageStream::masterStream(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), Foam::pow(), SolverPerformance< Type >::print(), psi, solve(), SolverPerformance< Type >::solverName(), and Foam::type().
Foam::solverPerformance solveCoupled (const dictionary & solverControls)
Solve coupled returning the solution statistics.
Use the given solver controls
Definition at line 225 of file fvMatrixSolve.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::diag(), LduMatrix< Type, DType, LUType >::diag(), Foam::endl(), Foam::Info, messageStream::masterStream(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), SolverPerformance< Type >::print(), and psi.
Foam::solverPerformance solve ()
Solve returning the solution statistics.
Solver controls read from fvSolution
Definition at line 319 of file fvMatrixSolve.C.
Foam::tmp< Foam::Field< Type > > residual () const
Return the matrix residual.
Definition at line 336 of file fvMatrixSolve.C.
References fvMatrix< Type >::addBoundaryDiag(), fvMatrix< Type >::addBoundarySource(), Field< Type >::component(), Field< Type >::replace(), and lduMatrix::residual().
Foam::tmp< Foam::scalarField > D () const
Return the matrix scalar diagonal.
Definition at line 707 of file fvMatrix.C.
References Foam::diag().
Foam::tmp< Foam::Field< Type > > DD () const
Return the matrix Type diagonal.
Definition at line 716 of file fvMatrix.C.
References fvPatchField< Type >::coupled(), Foam::diag(), forAll, and List< Type >::size().
Foam::tmp< Foam::volScalarField > A () const
Return the central coefficient.
Definition at line 740 of file fvMatrix.C.
References Foam::dimVol, IOobject::NO_READ, and IOobject::NO_WRITE.
Referenced by pressureGradientExplicitSource::setValue(), and kinematicSingleLayer::solveThickness().
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > H () const
Return the H operation source.
Definition at line 769 of file fvMatrix.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, lduMatrix::H(), GeometricField< Type, PatchField, GeoMesh >::internalField(), IOobject::NO_READ, IOobject::NO_WRITE, Foam::pow(), GeometricField< Type, PatchField, GeoMesh >::replace(), and Foam::type().
Referenced by kinematicSingleLayer::solveThickness().
Foam::tmp< Foam::volScalarField > H1 () const
Return H(1)
Definition at line 835 of file fvMatrix.C.
References Foam::component(), fvPatchField< Type >::coupled(), Foam::dimVol, forAll, lduMatrix::H1(), IOobject::NO_READ, IOobject::NO_WRITE, and List< Type >::size().
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > flux () const
Return the face-flux field from the matrix.
Definition at line 883 of file fvMatrix.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::cmptMultiply(), lduMatrix::faceH(), Foam::FatalError, FatalErrorIn, forAll, GeometricField< Type, PatchField, GeoMesh >::internalField(), IOobject::NO_READ, and IOobject::NO_WRITE.
Referenced by Implicit< CloudType >::cacheFields(), Foam::CorrectPhi(), Foam::MULES::implicitSolve(), and kinematicSingleLayer::solveThickness().
void operator= (const fvMatrix< Type > & fvmv)
Definition at line 967 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, and lduMatrix::operator=().
void operator= (const tmp< fvMatrix< Type > > & tfvmv)
Definition at line 1003 of file fvMatrix.C.
void negate ()
Definition at line 1011 of file fvMatrix.C.
References lduMatrix::negate().
void operator+= (const fvMatrix< Type > & fvmv)
Definition at line 1026 of file fvMatrix.C.
References Foam::checkMethod(), and lduMatrix::operator+=().
void operator+= (const tmp< fvMatrix< Type > > & tfvmv)
Definition at line 1052 of file fvMatrix.C.
void operator-= (const fvMatrix< Type > & fvmv)
Definition at line 1060 of file fvMatrix.C.
References Foam::checkMethod(), and lduMatrix::operator-=().
void operator-= (const tmp< fvMatrix< Type > > & tfvmv)
Definition at line 1084 of file fvMatrix.C.
void operator+= (const DimensionedField< Type, volMesh > & su)
Definition at line 1093 of file fvMatrix.C.
References Foam::checkMethod().
void operator+= (const tmp< DimensionedField< Type, volMesh > > & tsu)
Definition at line 1104 of file fvMatrix.C.
void operator+= (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tsu)
Definition at line 1115 of file fvMatrix.C.
void operator-= (const DimensionedField< Type, volMesh > & su)
Definition at line 1126 of file fvMatrix.C.
References Foam::checkMethod().
void operator-= (const tmp< DimensionedField< Type, volMesh > > & tsu)
Definition at line 1137 of file fvMatrix.C.
void operator-= (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tsu)
Definition at line 1148 of file fvMatrix.C.
void operator+= (const dimensioned< Type > & su)
Definition at line 1159 of file fvMatrix.C.
References DimensionedField< Type, GeoMesh >::mesh(), and psi.
void operator-= (const dimensioned< Type > & su)
Definition at line 1169 of file fvMatrix.C.
References DimensionedField< Type, GeoMesh >::mesh(), and psi.
void operator+= (const zero &)
Definition at line 1179 of file fvMatrix.C.
void operator-= (const zero &)
Definition at line 1187 of file fvMatrix.C.
void operator*= (const DimensionedField< scalar, volMesh > & dsf)
Definition at line 1195 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, and lduMatrix::operator*=().
void operator*= (const tmp< DimensionedField< scalar, volMesh > > & tdsf)
Definition at line 1228 of file fvMatrix.C.
void operator*= (const tmp< volScalarField > & tvsf)
Definition at line 1239 of file fvMatrix.C.
void operator*= (const dimensioned< scalar > & ds)
Definition at line 1250 of file fvMatrix.C.
References lduMatrix::operator*=().
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
Definition at line 33 of file fvScalarMatrix.C.
References Foam::diag(), patchi, and value().
Foam::autoPtr< Foam::fvMatrix< Foam::scalar >::fvSolver > solver (const dictionary & solverControls)
Definition at line 58 of file fvScalarMatrix.C.
References Foam::diag(), Foam::endl(), Foam::Info, messageStream::masterStream(), and mesh.
Foam::solverPerformance solveSegregated (const dictionary & solverControls)
Definition at line 138 of file fvScalarMatrix.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::diag(), Foam::endl(), Foam::Info, GeometricField< Type, PatchField, GeoMesh >::internalField(), messageStream::masterStream(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), SolverPerformance< Type >::print(), psi, and solve().
Foam::tmp< Foam::scalarField > residual () const
Definition at line 187 of file fvScalarMatrix.C.
Foam::tmp< Foam::volScalarField > H () const
Definition at line 211 of file fvScalarMatrix.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dimVol, and GeometricField< Type, PatchField, GeoMesh >::internalField().
Foam::tmp< Foam::volScalarField > H1 () const
Definition at line 243 of file fvScalarMatrix.C.
References Foam::dimVol.
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
autoPtr< fvMatrix< scalar >::fvSolver > solver (const dictionary &)
solverPerformance solveSegregated (const dictionary &)
tmp< scalarField > residual () const
tmp< volScalarField > H () const
tmp< volScalarField > H1 () const
Friends And Related Function Documentation
friend class fvSolver friend
Declare friendship with the fvSolver class.
Definition at line 148 of file fvMatrix.H.
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const fvMatrix< Type > & , const DimensionedField< Type, volMesh > &) friend
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const fvMatrix< Type > & , const tmp< GeometricField< Type, fvPatchField, volMesh > > &) friend
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const tmp< fvMatrix< Type > > & , const DimensionedField< Type, volMesh > &) friend
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const tmp< fvMatrix< Type > > & , const tmp< GeometricField< Type, fvPatchField, volMesh > > &) friend
Ostream& operator (Ostream & , const fvMatrix< Type > &) friend
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchField.H
src/finiteVolume/fvMatrices/fvMatrix/fvMatrix.H
src/finiteVolume/fvMatrices/fvMatrix/fvMatrix.C
src/finiteVolume/fvMatrices/fvMatrix/fvMatrixSolve.C