OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
functionObjectFiles Class Reference
Base class for output file data handling.
Public Member Functions
functionObjectFiles (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
functionObjectFiles (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFiles (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
virtual ~functionObjectFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Protected Member Functions
virtual void createFiles ()
Create the output file.
virtual void write ()
Write function.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
functionObjectFiles (const functionObjectFiles &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void writeFileHeader (const label i=0)
File header information.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Attributes inherited from functionObjectFile
const objectRegistry & obr_
Reference to the objectRegistry.
const word prefix_
Prefix.
Detailed Description
Base class for output file data handling.
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
functionObjectFiles.H
functionObjectFiles.C
Definition at line 55 of file functionObjectFiles.H.
Constructor & Destructor Documentation
functionObjectFiles (const functionObjectFiles &) protected
Disallow default bitwise copy construct.
Referenced by functionObjectFiles::functionObjectFiles(), and functionObjectFiles::resetName().
functionObjectFiles (const objectRegistry & obr, const word & prefix)
Construct from objectRegistry.
Definition at line 106 of file functionObjectFiles.C.
References functionObjectFiles::functionObjectFiles().
functionObjectFiles (const objectRegistry & obr, const word & prefix, const word & name)
Construct from components.
Definition at line 118 of file functionObjectFiles.C.
References List< T >::append(), List< T >::clear(), functionObjectFiles::functionObjectFiles(), and UPstream::master().
functionObjectFiles (const objectRegistry & obr, const word & prefix, const wordList & names)
Construct from components.
Definition at line 141 of file functionObjectFiles.C.
References List< T >::append(), List< T >::clear(), UPstream::master(), and List< T >::size().
~functionObjectFiles () virtual
Destructor.
Definition at line 165 of file functionObjectFiles.C.
Member Function Documentation
void createFiles () protected virtual
Create the output file.
Definition at line 32 of file functionObjectFiles.C.
References functionObjectFile::baseFileDir(), forAll, IOstream::good(), functionObjectFile::initStream(), UPstream::master(), Foam::mkDir(), functionObjectFile::obr_, functionObjectFile::prefix_, Time::startTime(), objectRegistry::time(), Time::timeName(), dimensioned< Type >::value(), and functionObjectFile::writeFileHeader().
Referenced by functionObjectFiles::resetName(), functionObjectFiles::resetNames(), and functionObjectFiles::write().
void write () protected virtual
Write function.
Reimplemented in faceSource, forces, cellSource, regionSizeDistribution, forceCoeffs, fieldMinMax, fieldValueDelta, wallShearStress, cloudInfo, residuals, fieldValue, yPlus, and moleFractions< ThermoType >.
Definition at line 67 of file functionObjectFiles.C.
References functionObjectFiles::createFiles().
Referenced by yPlus::execute(), wallShearStress::execute(), yPlus::write(), fieldValue::write(), residuals::write(), cloudInfo::write(), wallShearStress::write(), fieldValueDelta::write(), fieldMinMax::write(), forceCoeffs::write(), and forces::write().
void resetNames (const wordList & names) protected virtual
Reset the list of names from a wordList.
Definition at line 73 of file functionObjectFiles.C.
References List< T >::append(), List< T >::clear(), functionObjectFiles::createFiles(), UPstream::master(), and List< T >::size().
Referenced by cloudInfo::read().
void resetName (const word & name) protected virtual
Reset the list of names to a single name entry.
Definition at line 88 of file functionObjectFiles.C.
References List< T >::append(), List< T >::clear(), functionObjectFiles::createFiles(), functionObjectFiles::functionObjectFiles(), and UPstream::master().
void operator= (const functionObjectFiles &) protected
Disallow default bitwise assignment.
const Foam::wordList & names () const
Return const access to the names.
Definition at line 171 of file functionObjectFiles.C.
Foam::OFstream & file ()
Return access to the file (if only 1)
Definition at line 177 of file functionObjectFiles.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, UPstream::master(), and WarningInFunction.
Referenced by residuals::writeFileHeader(), and residuals::writeResidual().
Foam::PtrList< Foam::OFstream > & files ()
Return access to the files.
Definition at line 204 of file functionObjectFiles.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UPstream::master().
Foam::OFstream & file (const label i)
Return file 'i'.
Definition at line 217 of file functionObjectFiles.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UPstream::master().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObjectFiles/functionObjectFiles.H
src/OpenFOAM/db/functionObjects/functionObjectFiles/functionObjectFiles.C