OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fixedTemperatureConstraint Class Reference
Fixed temperature equation constraint.
Public Types
enum temperatureMode { tmUniform, tmLookup }
Temperature mode.
Public Types inherited from cellSetOption
enum selectionModeType { smPoints, smCellSet, smCellZone, smAll }
Enumeration for selection mode types.
Public Member Functions
TypeName ("fixedTemperatureConstraint")
Runtime type information.
fixedTemperatureConstraint (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~fixedTemperatureConstraint ()
Destructor.
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldI)
Constrain energy equation to fix the temperature.
virtual bool read (const dictionary &dict)
Read dictionary.
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
Runtime type information.
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~cellSetOption ()
Destructor.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const labelList & cells () const
Return const access to the cell set.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
Switch & active ()
Return access to the source active flag.
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldI)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldI)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Static Public Attributes
static const NamedEnum< temperatureMode, 2 > temperatureModeNames_
String representation of temperatureMode enums.
Static Public Attributes inherited from cellSetOption
static const NamedEnum< selectionModeType, 4 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Attributes
temperatureMode mode_
Operation mode.
autoPtr< DataEntry< scalar > > Tuniform_
Uniform temperature [K].
word TName_
Temperature field name.
Protected Attributes inherited from cellSetOption
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Detailed Description
Fixed temperature equation constraint.
Sources described by:
fixedTemperatureConstraintCoeffs { mode uniform; // uniform or lookup
uniform option temperature constant 500; // fixed temperature with time [K]
lookup option TName T; // optional temperature field name }
Note: The 'uniform' option allows the use of a time-varying uniform temperature by means of the DataEntry type.
Source files
fixedTemperatureConstraint.H
fvOption.C
Definition at line 69 of file fixedTemperatureConstraint.H.
Member Enumeration Documentation
enum temperatureMode
Temperature mode.
Enumerator
tmUniform
tmLookup
Definition at line 77 of file fixedTemperatureConstraint.H.
Constructor & Destructor Documentation
fixedTemperatureConstraint (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 63 of file fixedTemperatureConstraint.C.
References dictName(), basicThermo::he(), and IOobject::name().
virtual ~fixedTemperatureConstraint () inline virtual
Destructor.
Definition at line 132 of file fixedTemperatureConstraint.H.
Member Function Documentation
TypeName ("fixedTemperatureConstraint")
Runtime type information.
void constrain (fvMatrix< scalar > & eqn, const label fieldI) virtual
Constrain energy equation to fix the temperature.
Reimplemented from option.
Definition at line 112 of file fixedTemperatureConstraint.C.
References dictName(), basicThermo::he(), mesh, basicThermo::p(), fvMatrix< Type >::setValues(), T, IOobject::time(), and dimensioned< Type >::value().
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from cellSetOption.
Definition at line 148 of file fixedTemperatureConstraint.C.
References option::coeffs_, dict, dictionary::found(), cellSetOption::read(), dictionary::readIfPresent(), fixedTemperatureConstraint::TName_, and fixedTemperatureConstraint::Tuniform_.
Member Data Documentation
const Foam::NamedEnum< Foam::fv::fixedTemperatureConstraint::temperatureMode, 2 > temperatureModeNames_ static
String representation of temperatureMode enums.
Definition at line 85 of file fixedTemperatureConstraint.H.
temperatureMode mode_ protected
Operation mode.
Definition at line 93 of file fixedTemperatureConstraint.H.
autoPtr<DataEntry<scalar> > Tuniform_ protected
Uniform temperature [K].
Definition at line 96 of file fixedTemperatureConstraint.H.
Referenced by fixedTemperatureConstraint::read().
word TName_ protected
Temperature field name.
Definition at line 99 of file fixedTemperatureConstraint.H.
Referenced by fixedTemperatureConstraint::read().
The documentation for this class was generated from the following files:
src/fvOptions/constraints/derived/fixedTemperatureConstraint/fixedTemperatureConstraint.H
src/fvOptions/constraints/derived/fixedTemperatureConstraint/fixedTemperatureConstraint.C