OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
forces Class Reference
FunctionObjects » Forces function objects
This function object calculates the forces and moments by integrating the pressure and skin-friction forces over a given list of patches.
Public Member Functions
TypeName ("forces")
Runtime type information.
forces (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
forces (const word &name, const objectRegistry &obr, const dictionary &)
Construct from objectRegistry and dictionary.
virtual ~forces ()
Destructor.
virtual bool read (const dictionary &)
Read the forces data.
virtual void calcForcesMoment ()
Calculate the forces and moments.
virtual vector forceEff () const
Return the total force.
virtual vector momentEff () const
Return the total moment.
virtual bool execute ()
Execute, currently does nothing.
virtual bool write ()
Write the forces.
Public Member Functions inherited from writeFiles
writeFiles (const word &name, const Time &time, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFiles (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from writeFile
writeFile (const word &name, const Time &t, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFile (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
wordList createFileNames (const dictionary &dict) const
Create file names for forces and bins.
virtual void writeFileHeader (const label i)
Output file header information.
void initialise ()
Initialise the fields.
tmp< volSymmTensorField > devRhoReff () const
Return the effective viscous stress (laminar + turbulent).
tmp< volScalarField > mu () const
Dynamic viscosity field.
tmp< volScalarField > rho () const
Return rho if specified otherwise rhoRef.
scalar rho (const volScalarField &p) const
Return rhoRef if the pressure field is dynamic, i.e. p/rho.
void applyBins (const vectorField &Md, const vectorField &fN, const vectorField &fT, const vectorField &fP, const vectorField &d)
Accumulate bin data.
void writeForces ()
Helper function to write force data.
void writeBins ()
Helper function to write bin data.
forces (const forces &)
Disallow default bitwise copy construct.
void operator= (const forces &)
Disallow default bitwise assignment.
Protected Member Functions inherited from writeFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
writeFiles (const writeFiles &)
Disallow default bitwise copy construct.
void operator= (const writeFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from writeFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
writeFile (const writeFile &)
Disallow default bitwise copy construct.
void operator= (const writeFile &)
Disallow default bitwise assignment.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
List< Field< vector > > force_
Pressure, viscous and porous force per bin.
List< Field< vector > > moment_
Pressure, viscous and porous moment per bin.
labelHashSet patchSet_
Patches to integrate forces over.
word pName_
Name of pressure field.
word UName_
Name of velocity field.
word rhoName_
Name of density field (optional)
Switch directForceDensity_
Is the force density being supplied directly?
word fDName_
The name of the force density (fD) field.
scalar rhoRef_
Reference density needed for incompressible calculations.
scalar pRef_
Reference pressure.
coordinateSystem coordSys_
Coordinate system used when evaluting forces/moments.
bool localSystem_
Flag to indicate whether we are using a local co-ordinate sys.
bool porosity_
Flag to include porosity effects.
label nBin_
Number of bins.
vector binDir_
Direction used to determine bin orientation.
scalar binDx_
Distance between bin divisions.
scalar binMin_
Minimum bin bounds.
List< point > binPoints_
Bin positions along binDir.
bool binCumulative_
Should bin data be cumulative?
bool initialised_
Initialised flag.
Protected Attributes inherited from writeFile
const word prefix_
Prefix.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
This function object calculates the forces and moments by integrating the pressure and skin-friction forces over a given list of patches.
Member function forces::write() calculates the forces/moments and writes the forces/moments into the file <timeDir>/forces.dat and bin data (if selected) to the file <timeDir>/forces_bin.dat
Example of function object specification:
forces1
{
    type        forces;
    libs ("libforces.so");
    ...
    log         yes;
    patches     (walls);
    binData
    {
        nBin        20;
        direction   (1 0 0);
        cumulative  yes;
    }
}
Function object usage
Property Description Required Default value
type Type name: forces yes
log Write force data to standard output no no
patches Patches included in the forces calculation yes
p Pressure field name no p
U Velocity field name no U
rho Density field name (see below) no rho
CofR Centre of rotation (see below) no
directForceDensity Force density supplied directly (see below) no no
fD Name of force density field (see below) no fD
Bin data is optional, but if the dictionary is present, the entries must be defined according o
nBin number of data bins yes
direction direction along which bins are defined yes
cumulative bin data accumulated with incresing distance yes
Note
For incompressible cases, set rho to rhoInf. You will then be required to provide a rhoInf value corresponding to the free-stream constant density.
If the force density is supplied directly, set the directForceDensity flag to 'yes', and supply the force density field using the fDName entry
The centre of rotation (CofR) for moment calculations can either be specified by an CofR entry, or be taken from origin of the local coordinate system. For example,
    CofR        (0 0 0);
or
    coordinateSystem
    {
        origin  (0 0 0);
        e3      (0 0 1);
        e1      (1 0 0);
    }
See also
Foam::functionObject Foam::functionObjects::writeFiles Foam::functionObjects::timeControl Foam::forceCoeffs
Source files
forces.H
forces.C
Definition at line 196 of file forces.H.
Constructor & Destructor Documentation
forces (const forces &) protected
Disallow default bitwise copy construct.
Referenced by forces::forces(), and forces::writeBins().
forces (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 521 of file forces.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forces::forces(), and Foam::read().
forces (const word & name, const objectRegistry & obr, const dictionary & dict)
Construct from objectRegistry and dictionary.
Definition at line 561 of file forces.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::read().
~forces () virtual
Destructor.
Definition at line 602 of file forces.C.
Member Function Documentation
Foam::wordList createFileNames (const dictionary & dict) const protected
Create file names for forces and bins.
Definition at line 49 of file forces.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), dictionary::found(), dictionary::lookup(), Foam::readLabel(), and dictionary::subDict().
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from writeFile.
Reimplemented in forceCoeffs.
Definition at line 73 of file forces.C.
References Foam::abort(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::jn(), Foam::name(), Foam::nl, and Foam::tab.
void initialise () protected
Initialise the fields.
Definition at line 161 of file forces.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const protected
Return the effective viscous stress (laminar + turbulent).
Definition at line 208 of file forces.C.
References Foam::dev(), IncompressibleTurbulenceModel< TransportModel >::devReff(), dictionaryName::dictName(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::fvc::grad(), dictionary::lookup(), fluidThermo::mu(), transportModel::nu(), nu, GeometricField< symmTensor, fvPatchField, volMesh >::null(), rho, turb, Foam::twoSymm(), and U.
Foam::tmp< Foam::volScalarField > mu () const protected
Dynamic viscosity field.
Definition at line 270 of file forces.C.
References dictionaryName::dictName(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), fluidThermo::mu(), transportModel::nu(), nu, GeometricField< scalar, fvPatchField, volMesh >::null(), and rho.
Foam::tmp< Foam::volScalarField > rho () const protected
Return rho if specified otherwise rhoRef.
Definition at line 309 of file forces.C.
References Foam::dimDensity, mesh, fvMesh::time(), and Time::timeName().
Foam::scalar rho (const volScalarField & p) const protected
Return rhoRef if the pressure field is dynamic, i.e. p/rho.
otherwise return 1
Definition at line 337 of file forces.C.
References forces::applyBins(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimPressure, Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
void applyBins (const vectorField & Md, const vectorField & fN, const vectorField & fT, const vectorField & fP, const vectorField & d) protected
Accumulate bin data.
Definition at line 358 of file forces.C.
References forAll, Foam::max(), Foam::min(), and Foam::sum().
Referenced by forces::rho().
void writeForces () protected
Helper function to write force data.
Definition at line 394 of file forces.C.
References Foam::endl(), Log, Foam::name(), Foam::nl, Foam::setw(), Foam::sum(), Foam::tab, and Foam::type().
void writeBins () protected
Helper function to write bin data.
Definition at line 439 of file forces.C.
References Foam::endl(), f(), forAll, forces::forces(), Foam::setw(), List< T >::size(), and Foam::tab.
void operator= (const forces &) protected
Disallow default bitwise assignment.
TypeName ("forces")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the forces data.
Reimplemented from regionFunctionObject.
Reimplemented in forceCoeffs.
Definition at line 608 of file forces.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), polyPatch::faceCentres(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, forAllConstIter(), dictionary::found(), Log, dictionary::lookup(), dictionary::lookupOrDefault(), Foam::mag(), Foam::max(), mesh, Foam::min(), Foam::name(), Foam::nl, patchi, polyBoundaryMesh::patchSet(), regionFunctionObject::read(), dictionary::readIfPresent(), Foam::readScalar(), Foam::reduce(), dictionary::subDict(), and Foam::type().
Referenced by forceCoeffs::read().
void calcForcesMoment () virtual
Calculate the forces and moments.
Porous force
Definition at line 743 of file forces.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), porosityModel::cellZoneIDs(), polyMesh::cellZones(), HashTable< T, Key, Hash >::empty(), Foam::endl(), forAll, forAllConstIter(), porosityModel::force(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Foam::mag(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::constant::physicoChemical::mu, p, patchi, pRef, rho, List< T >::size(), U, WarningInFunction, and Foam::Zero.
Referenced by sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotion::solve(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and forceCoeffs::write().
Foam::vector forceEff () const virtual
Return the total force.
Definition at line 883 of file forces.C.
References Foam::sum().
Referenced by sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotion::solve(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
Foam::vector momentEff () const virtual
Return the total moment.
Definition at line 889 of file forces.C.
References Foam::sum().
Referenced by sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotion::solve(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
bool execute () virtual
Execute, currently does nothing.
Implements functionObject.
Reimplemented in forceCoeffs.
Definition at line 895 of file forces.C.
bool write () virtual
Write the forces.
Reimplemented from writeFiles.
Reimplemented in forceCoeffs.
Definition at line 901 of file forces.C.
References Foam::endl(), Log, UPstream::master(), and writeFiles::write().
Member Data Documentation
List<Field<vector> > force_ protected
Pressure, viscous and porous force per bin.
Definition at line 205 of file forces.H.
List<Field<vector> > moment_ protected
Pressure, viscous and porous moment per bin.
Definition at line 208 of file forces.H.
labelHashSet patchSet_ protected
Patches to integrate forces over.
Definition at line 214 of file forces.H.
word pName_ protected
Name of pressure field.
Definition at line 217 of file forces.H.
word UName_ protected
Name of velocity field.
Definition at line 220 of file forces.H.
word rhoName_ protected
Name of density field (optional)
Definition at line 223 of file forces.H.
Switch directForceDensity_ protected
Is the force density being supplied directly?
Definition at line 226 of file forces.H.
word fDName_ protected
The name of the force density (fD) field.
Definition at line 229 of file forces.H.
scalar rhoRef_ protected
Reference density needed for incompressible calculations.
Definition at line 232 of file forces.H.
scalar pRef_ protected
Reference pressure.
Definition at line 235 of file forces.H.
coordinateSystem coordSys_ protected
Coordinate system used when evaluting forces/moments.
Definition at line 238 of file forces.H.
bool localSystem_ protected
Flag to indicate whether we are using a local co-ordinate sys.
Definition at line 241 of file forces.H.
bool porosity_ protected
Flag to include porosity effects.
Definition at line 244 of file forces.H.
label nBin_ protected
Number of bins.
Definition at line 250 of file forces.H.
vector binDir_ protected
Direction used to determine bin orientation.
Definition at line 253 of file forces.H.
scalar binDx_ protected
Distance between bin divisions.
Definition at line 256 of file forces.H.
scalar binMin_ protected
Minimum bin bounds.
Definition at line 259 of file forces.H.
List<point> binPoints_ protected
Bin positions along binDir.
Definition at line 262 of file forces.H.
bool binCumulative_ protected
Should bin data be cumulative?
Definition at line 265 of file forces.H.
bool initialised_ protected
Initialised flag.
Definition at line 269 of file forces.H.
The documentation for this class was generated from the following files:
src/functionObjects/forces/forces/forces.H
src/functionObjects/forces/forces/forces.C