OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
fvFieldReconstructor Class Reference
Finite volume reconstructor for volume and surface fields.
Classes
class fvPatchFieldReconstructor
Mapper for sizing only - does not do any actual mapping.
Public Member Functions
fvFieldReconstructor (fvMesh &mesh, const PtrList< fvMesh > &procMeshes, const PtrList< labelIOList > &faceProcAddressing, const PtrList< labelIOList > &cellProcAddressing, const PtrList< labelIOList > &boundaryProcAddressing)
Construct from components.
label nReconstructed () const
Return number of fields reconstructed.
template<class Type >
tmp< DimensionedField< Type,
volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject, const PtrList< DimensionedField< Type, volMesh > > &procFields) const
Reconstruct volume internal field.
template<class Type >
tmp< DimensionedField< Type,
volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject) const
Read and reconstruct volume internal field.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh > > &) const
Reconstruct volume field.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject) const
Read and reconstruct volume field.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &) const
Reconstruct surface field.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject) const
Read and reconstruct surface field.
template<class Type >
void reconstructFvVolumeInternalFields (const IOobjectList &objects, const HashSet< word > &selectedFields)
Read, reconstruct and write all/selected volume internal fields.
template<class Type >
void reconstructFvVolumeFields (const IOobjectList &objects, const HashSet< word > &selectedFields)
Read, reconstruct and write all/selected volume fields.
template<class Type >
void reconstructFvSurfaceFields (const IOobjectList &objects, const HashSet< word > &selectedFields)
Read, reconstruct and write all/selected surface fields.
template<class Type >
Foam::tmp
< Foam::DimensionedField< Type,
Foam::volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject, const PtrList< DimensionedField< Type, volMesh > > &procFields) const
template<class Type >
Foam::tmp
< Foam::DimensionedField< Type,
Foam::volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh > > &procFields) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &procFields) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject) const
Detailed Description
Finite volume reconstructor for volume and surface fields.
Source files
fvFieldReconstructor.H
fvFieldReconstructor.C
fvFieldReconstructorReconstructFields.C
Definition at line 54 of file fvFieldReconstructor.H.
Constructor & Destructor Documentation
fvFieldReconstructor (fvMesh & mesh, const PtrList< fvMesh > & procMeshes, const PtrList< labelIOList > & faceProcAddressing, const PtrList< labelIOList > & cellProcAddressing, const PtrList< labelIOList > & boundaryProcAddressing)
Construct from components.
Definition at line 31 of file fvFieldReconstructor.C.
References fvMesh::boundary(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, primitiveMesh::nCells(), primitiveMesh::nFaces(), and PtrList< T >::size().
Member Function Documentation
label nReconstructed () const inline
Return number of fields reconstructed.
Definition at line 146 of file fvFieldReconstructor.H.
tmp<DimensionedField<Type, volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject, const PtrList< DimensionedField< Type, volMesh > > & procFields) const
Reconstruct volume internal field.
tmp<DimensionedField<Type, volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject) const
Read and reconstruct volume internal field.
tmp<GeometricField<Type, fvPatchField, volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh > > &) const
Reconstruct volume field.
tmp<GeometricField<Type, fvPatchField, volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject) const
Read and reconstruct volume field.
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > &) const
Reconstruct surface field.
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject) const
Read and reconstruct surface field.
void reconstructFvVolumeInternalFields (const IOobjectList & objects, const HashSet< word > & selectedFields)
Read, reconstruct and write all/selected volume internal fields.
Definition at line 597 of file fvFieldReconstructorReconstructFields.C.
References HashTable< nil, Key, Hash >::empty(), Foam::endl(), fields, forAllConstIter, HashTable< nil, Key, Hash >::found(), Foam::Info, IOobjectList::lookupClass(), Foam::name(), HashTable< T, Key, Hash >::size(), and Ostream::write().
void reconstructFvVolumeFields (const IOobjectList & objects, const HashSet< word > & selectedFields)
Read, reconstruct and write all/selected volume fields.
Definition at line 632 of file fvFieldReconstructorReconstructFields.C.
References HashTable< nil, Key, Hash >::empty(), Foam::endl(), fields, forAllConstIter, HashTable< nil, Key, Hash >::found(), Foam::Info, IOobjectList::lookupClass(), Foam::name(), HashTable< T, Key, Hash >::size(), and Ostream::write().
void reconstructFvSurfaceFields (const IOobjectList & objects, const HashSet< word > & selectedFields)
Read, reconstruct and write all/selected surface fields.
Definition at line 668 of file fvFieldReconstructorReconstructFields.C.
References HashTable< nil, Key, Hash >::empty(), Foam::endl(), fields, forAllConstIter, HashTable< nil, Key, Hash >::found(), Foam::Info, IOobjectList::lookupClass(), Foam::name(), HashTable< T, Key, Hash >::size(), and Ostream::write().
Foam::tmp<Foam::DimensionedField<Type, Foam::volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject, const PtrList< DimensionedField< Type, volMesh > > & procFields) const
Definition at line 39 of file fvFieldReconstructorReconstructFields.C.
References DimensionedField< Type, GeoMesh >::field(), forAll, and internalField().
Foam::tmp<Foam::DimensionedField<Type, Foam::volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject) const
Definition at line 75 of file fvFieldReconstructorReconstructFields.C.
References forAll, and IOobject::name().
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh > > & procFields) const
Definition at line 124 of file fvFieldReconstructorReconstructFields.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cp, Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, internalField(), GeometricField< Type, PatchField, GeoMesh >::internalField(), DimensionedField< Type, GeoMesh >::mesh(), and UList< T >::size().
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject) const
Definition at line 309 of file fvFieldReconstructorReconstructFields.C.
References forAll, and IOobject::name().
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh > > & procFields) const
Definition at line 357 of file fvFieldReconstructorReconstructFields.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cp, forAll, internalField(), GeometricField< Type, PatchField, GeoMesh >::internalField(), Foam::mag(), and UList< T >::size().
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject) const
Definition at line 550 of file fvFieldReconstructorReconstructFields.C.
References forAll, and IOobject::name().
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/fvFieldReconstructor.H
src/parallel/reconstruct/reconstruct/fvFieldReconstructor.C
src/parallel/reconstruct/reconstruct/fvFieldReconstructorReconstructFields.C