OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
hPowerThermo< EquationOfState > Class Template Reference
Power-function based thermodynamics package templated on EquationOfState.
Public Member Functions
hPowerThermo (Istream &)
Construct from Istream.
hPowerThermo (const dictionary &)
Construct from dictionary.
hPowerThermo (const word &, const hPowerThermo &)
Construct as a named copy.
autoPtr< hPowerThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
scalar ha (const scalar p, const scalar T) const
Absolute enthalpy [J/kmol].
scalar hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar hc () const
Chemical enthalpy [J/kg].
scalar s (const scalar p, const scalar T) const
Entropy [J/(kmol K)].
void operator+= (const hPowerThermo &)
void operator-= (const hPowerThermo &)
Static Public Member Functions
static autoPtr< hPowerThermo > New (Istream &is)
Selector from Istream.
static autoPtr< hPowerThermo > New (const dictionary &dict)
Selector from dictionary.
static word typeName ()
Return the instantiated type name.
Friends
hPowerThermo operator+ (const hPowerThermo &, const hPowerThermo &)
hPowerThermo operator- (const hPowerThermo &, const hPowerThermo &)
hPowerThermo operator* (const scalar, const hPowerThermo &)
hPowerThermo operator== (const hPowerThermo &, const hPowerThermo &)
Ostream & operator (Ostream &, const hPowerThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hPowerThermo< EquationOfState >
Power-function based thermodynamics package templated on EquationOfState.
In this thermodynamics package the heat capacity is a simple power of temperature:
Cp(T) = c0*(T/Tref)^n0;
which is particularly suitable for solids.
Source files
hPowerThermo.H
hPowerThermoI.H
hPowerThermo.C
Definition at line 54 of file hPowerThermo.H.
Constructor & Destructor Documentation
hPowerThermo (Istream & is)
Construct from Istream.
Definition at line 32 of file hPowerThermo.C.
References IOstream::check().
hPowerThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 48 of file hPowerThermo.C.
hPowerThermo (const word & name, const hPowerThermo< EquationOfState > & jt) inline
Construct as a named copy.
Definition at line 51 of file hPowerThermoI.H.
Member Function Documentation
Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 86 of file hPowerThermoI.H.
Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > New (Istream & is) inline static
Selector from Istream.
Definition at line 97 of file hPowerThermoI.H.
Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > New (const dictionary & dict) inline static
Selector from dictionary.
Definition at line 108 of file hPowerThermoI.H.
References dict.
static word typeName () inline static
Return the instantiated type name.
Definition at line 157 of file hPowerThermo.H.
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 121 of file hPowerThermoI.H.
References Foam::T().
Foam::scalar cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kg K)].
Definition at line 131 of file hPowerThermoI.H.
References Foam::pow().
Foam::scalar ha (const scalar p, const scalar T) const inline
Absolute enthalpy [J/kmol].
Definition at line 141 of file hPowerThermoI.H.
Foam::scalar hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kg].
Definition at line 151 of file hPowerThermoI.H.
References Foam::pow(), and Foam::constant::standard::Tstd.
Foam::scalar hc () const inline
Chemical enthalpy [J/kg].
Definition at line 161 of file hPowerThermoI.H.
Foam::scalar s (const scalar p, const scalar T) const inline
Entropy [J/(kmol K)].
Definition at line 169 of file hPowerThermoI.H.
References Foam::pow(), s(), and Foam::constant::standard::Tstd.
void operator+= (const hPowerThermo< EquationOfState > &) inline
Definition at line 183 of file hPowerThermoI.H.
void operator-= (const hPowerThermo< EquationOfState > &) inline
Definition at line 202 of file hPowerThermoI.H.
Friends And Related Function Documentation
hPowerThermo operator+ (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
hPowerThermo operator- (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
hPowerThermo operator* (const scalar , const hPowerThermo< EquationOfState > &) friend
hPowerThermo operator== (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
Ostream& operator (Ostream & , const hPowerThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hPower/hPowerThermo.H
src/thermophysicalModels/specie/thermo/hPower/hPowerThermo.C
src/thermophysicalModels/specie/thermo/hPower/hPowerThermoI.H