OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
GeometricField< Type, PatchField, GeoMesh > Class Template Reference
Generic GeometricField class.
Classes
class Boundary
Public Types
typedef GeoMesh::Mesh Mesh
Type of mesh on which this GeometricField is instantiated.
typedef GeoMesh::BoundaryMesh BoundaryMesh
Type of boundary mesh on which this.
typedef DimensionedField< Type, GeoMesh > Internal
Type of the internal field from which this GeometricField is derived.
typedef PatchField< Type > Patch
Type of the patch field of which the.
typedef Field< Type >::cmptType cmptType
Public Types inherited from DimensionedField< Type, GeoMesh >
typedef GeoMesh::Mesh Mesh
Type of mesh on which this DimensionedField is instantiated.
typedef Field< Type > FieldType
Type of the field from which this DimensionedField is derived.
typedef Field< Type >::cmptType cmptType
Component type of the elements of the field.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("GeometricField")
Runtime type information.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const word &patchFieldType=PatchField< Type >::calculatedType())
Constructor given IOobject, mesh, dimensions and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensions and patch types.
GeometricField (const IOobject &, const Mesh &, const dimensioned< Type > &, const word &patchFieldType=PatchField< Type >::calculatedType())
Constructor given IOobject, mesh, dimensioned<Type> and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensioned< Type > &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensioned<Type> and patch types.
GeometricField (const IOobject &, const Internal &, const PtrList< PatchField< Type >> &)
Constructor from components.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const Field< Type > &, const PtrList< PatchField< Type >> &)
Constructor from components.
GeometricField (const IOobject &, const Mesh &)
Construct and read given IOobject.
GeometricField (const IOobject &, const Mesh &, const dictionary &)
Construct from dictionary.
GeometricField (const GeometricField< Type, PatchField, GeoMesh > &)
Construct as copy.
GeometricField (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
Construct as copy of tmp<GeometricField> deleting argument.
GeometricField (const IOobject &, const GeometricField< Type, PatchField, GeoMesh > &)
Construct as copy resetting IO parameters.
GeometricField (const IOobject &, const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
Construct as copy of tmp<GeometricField> resetting IO parameters.
GeometricField (const word &newName, const GeometricField< Type, PatchField, GeoMesh > &)
Construct as copy resetting name.
GeometricField (const word &newName, const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
Construct as copy resetting name.
GeometricField (const IOobject &, const GeometricField< Type, PatchField, GeoMesh > &, const word &patchFieldType)
Construct as copy resetting IO parameters and patch type.
GeometricField (const IOobject &, const GeometricField< Type, PatchField, GeoMesh > &, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
Construct as copy resetting IO parameters and boundary types.
GeometricField (const IOobject &, const tmp< GeometricField< Type, PatchField, GeoMesh >> &, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
Construct as copy resetting IO parameters and boundary types.
virtual ~GeometricField ()
Destructor.
Internal & ref ()
Return a reference to the dimensioned internal field.
const Internal & internalField () const
Return a const-reference to the dimensioned internal field.
const Internal & v () const
Return a const-reference to the dimensioned internal field.
Internal::FieldType & primitiveFieldRef ()
Return a reference to the internal field.
const Internal::FieldType & primitiveField () const
Return a const-reference to the internal field.
Boundary & boundaryFieldRef ()
Return a reference to the boundary field.
const Boundary & boundaryField () const
Return const-reference to the boundary field.
label timeIndex () const
Return the time index of the field.
label & timeIndex ()
Return the time index of the field.
void storeOldTimes () const
Store the old-time fields.
void storeOldTime () const
Store the old-time field.
label nOldTimes () const
Return the number of old time fields stored.
const GeometricField< Type, PatchField, GeoMesh > & oldTime () const
Return old time field.
GeometricField< Type, PatchField, GeoMesh > & oldTime ()
Return non-const old time field.
void storePrevIter () const
Store the field as the previous iteration value.
const GeometricField< Type, PatchField, GeoMesh > & prevIter () const
Return previous iteration field.
void correctBoundaryConditions ()
Correct boundary field.
bool needReference () const
Does the field need a reference level for solution.
tmp< GeometricField< cmptType, PatchField, GeoMesh > > component (const direction) const
Return a component of the field.
bool writeData (Ostream &) const
WriteData member function required by regIOobject.
tmp< GeometricField< Type, PatchField, GeoMesh > > T () const
Return transpose (only if it is a tensor field)
void relax (const scalar alpha)
Relax field (for steady-state solution).
void relax ()
Relax field (for steady-state solution).
word select (bool final) const
Select the final iteration parameters if `final' is true.
void writeMinMax (Ostream &os) const
Helper function to write the min and max to an Ostream.
void negate ()
void replace (const direction, const GeometricField< cmptType, PatchField, GeoMesh > &)
void replace (const direction, const dimensioned< cmptType > &)
void max (const dimensioned< Type > &)
void min (const dimensioned< Type > &)
void max (const GeometricField< Type, PatchField, GeoMesh > &, const dimensioned< Type > &)
void min (const GeometricField< Type, PatchField, GeoMesh > &, const dimensioned< Type > &)
void scale (const GeometricField< Type, PatchField, GeoMesh > &, const GeometricField< Type, PatchField, GeoMesh > &)
void scale (const GeometricField< Type, PatchField, GeoMesh > &, const dimensioned< Type > &)
const Internal & operator() () const
Return a const-reference to the dimensioned internal field.
void operator= (const GeometricField< Type, PatchField, GeoMesh > &)
void operator= (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
void operator= (const dimensioned< Type > &)
void operator== (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
void operator== (const dimensioned< Type > &)
void operator+= (const GeometricField< Type, PatchField, GeoMesh > &)
void operator+= (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
void operator-= (const GeometricField< Type, PatchField, GeoMesh > &)
void operator-= (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
void operator*= (const GeometricField< scalar, PatchField, GeoMesh > &)
void operator*= (const tmp< GeometricField< scalar, PatchField, GeoMesh >> &)
void operator/= (const GeometricField< scalar, PatchField, GeoMesh > &)
void operator/= (const tmp< GeometricField< scalar, PatchField, GeoMesh >> &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const dimensioned< scalar > &)
template<>
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
template<>
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &gsf)
template<>
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
template<>
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &sf)
Public Member Functions inherited from DimensionedField< Type, GeoMesh >
TypeName ("DimensionedField")
Runtime type information.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const Field< Type > &)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensioned< Type > &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const word &fieldDictEntry="value")
Construct from Istream.
DimensionedField (const IOobject &, const Mesh &mesh, const dictionary &fieldDict, const word &fieldDictEntry="value")
Construct from dictionary.
DimensionedField (const DimensionedField< Type, GeoMesh > &)
Construct as copy.
DimensionedField (DimensionedField< Type, GeoMesh > &, bool reuse)
Construct as copy or re-use as specified.
DimensionedField (const Xfer< DimensionedField< Type, GeoMesh >> &)
Construct by transferring the DimensionedField.
DimensionedField (const tmp< DimensionedField< Type, GeoMesh >> &)
Construct as copy of tmp<DimensionedField> deleting argument.
DimensionedField (const IOobject &, const DimensionedField< Type, GeoMesh > &)
Construct as copy resetting IO parameters.
DimensionedField (const IOobject &, DimensionedField< Type, GeoMesh > &, bool reuse)
Construct as copy resetting IO parameters and re-use as specified.
DimensionedField (const word &newName, const DimensionedField< Type, GeoMesh > &)
Construct as copy resetting name.
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &, bool reuse)
Construct as copy resetting name and re-use as specified.
DimensionedField (const word &newName, const Xfer< DimensionedField< Type, GeoMesh >> &)
Construct by transferring the DimensionedField with a new name.
DimensionedField (const word &newName, const tmp< DimensionedField< Type, GeoMesh >> &)
Construct as copy resetting name.
tmp< DimensionedField< Type, GeoMesh > > clone () const
Clone.
virtual ~DimensionedField ()
Destructor.
void readField (const dictionary &fieldDict, const word &fieldDictEntry="value")
const Mesh & mesh () const
Return mesh.
const dimensionSet & dimensions () const
Return dimensions.
dimensionSet & dimensions ()
Return non-const access to dimensions.
const Field< Type > & field () const
Field< Type > & field ()
tmp< DimensionedField< cmptType, GeoMesh > > component (const direction) const
Return a component field of the field.
void replace (const direction, const DimensionedField< cmptType, GeoMesh > &)
Replace a component field of the field.
void replace (const direction, const tmp< DimensionedField< cmptType, GeoMesh >> &)
Replace a component field of the field.
tmp< DimensionedField< Type, GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
dimensioned< Type > average () const
Calculate and return arithmetic average.
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > &) const
Calculate and return weighted average.
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh >> &) const
Calculate and return weighted average.
bool writeData (Ostream &, const word &fieldDictEntry) const
void operator= (const DimensionedField< Type, GeoMesh > &)
void operator= (const tmp< DimensionedField< Type, GeoMesh >> &)
void operator= (const dimensioned< Type > &)
void operator+= (const DimensionedField< Type, GeoMesh > &)
void operator+= (const tmp< DimensionedField< Type, GeoMesh >> &)
void operator-= (const DimensionedField< Type, GeoMesh > &)
void operator-= (const tmp< DimensionedField< Type, GeoMesh >> &)
void operator*= (const DimensionedField< scalar, GeoMesh > &)
void operator*= (const tmp< DimensionedField< scalar, GeoMesh >> &)
void operator/= (const DimensionedField< scalar, GeoMesh > &)
void operator/= (const tmp< DimensionedField< scalar, GeoMesh >> &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const dimensioned< scalar > &)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static const GeometricField< Type, PatchField, GeoMesh > & null ()
Return a null geometric field.
Static Public Member Functions inherited from DimensionedField< Type, GeoMesh >
static const DimensionedField< Type, GeoMesh > & null ()
Return a null DimensionedField.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Friends
Ostream & operator (Ostream &, const GeometricField< Type, PatchField, GeoMesh > &)
Ostream & operator (Ostream &, const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
Additional Inherited Members
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Type, template< class > class PatchField, class GeoMesh>
class Foam::GeometricField< Type, PatchField, GeoMesh >
Generic GeometricField class.
Source files
GeometricField.H
GeometricFieldI.H
GeometricField.C
Boundary.C
GeometricFieldFunctions.H
GeometricFieldFunctions.C
Definition at line 52 of file surfaceFieldsFwd.H.
Member Typedef Documentation
typedef GeoMesh::Mesh Mesh
Type of mesh on which this GeometricField is instantiated.
Definition at line 98 of file GeometricField.H.
typedef GeoMesh::BoundaryMesh BoundaryMesh
Type of boundary mesh on which this.
GeometricField::Boundary is instantiated
Definition at line 102 of file GeometricField.H.
typedef DimensionedField<Type, GeoMesh> Internal
Type of the internal field from which this GeometricField is derived.
Definition at line 105 of file GeometricField.H.
typedef PatchField<Type> Patch
Type of the patch field of which the.
GeometricField::Boundary is composed
Definition at line 109 of file GeometricField.H.
typedef Field<Type>::cmptType cmptType
Definition at line 280 of file GeometricField.H.
Constructor & Destructor Documentation
GeometricField (const IOobject & io, const Mesh & mesh, const dimensionSet & ds, const word & patchFieldType = PatchField<Type>::calculatedType())
Constructor given IOobject, mesh, dimensions and patch type.
This allocates storage for the field but not values. Used only within this class to create TEMPORARY variables
Definition at line 177 of file GeometricField.C.
References Foam::endl(), and InfoInFunction.
Referenced by GeometricField< Type, PatchField, GeoMesh >::GeometricField().
GeometricField (const IOobject & io, const Mesh & mesh, const dimensionSet & ds, const wordList & wantedPatchTypes, const wordList & actualPatchTypes = wordList())
Constructor given IOobject, mesh, dimensions and patch types.
This allocates storage for the field but not values. Used only within this class to create TEMPORARY variables
Definition at line 201 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), and InfoInFunction.
GeometricField (const IOobject & io, const Mesh & mesh, const dimensioned< Type > & dt, const word & patchFieldType = PatchField<Type>::calculatedType())
Constructor given IOobject, mesh, dimensioned<Type> and patch type.
Definition at line 226 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), InfoInFunction, and dimensioned< Type >::value().
GeometricField (const IOobject & io, const Mesh & mesh, const dimensioned< Type > & dt, const wordList & wantedPatchTypes, const wordList & actualPatchTypes = wordList())
Constructor given IOobject, mesh, dimensioned<Type> and patch types.
Definition at line 252 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), InfoInFunction, and dimensioned< Type >::value().
GeometricField (const IOobject & io, const Internal & diField, const PtrList< PatchField< Type >> & ptfl)
Constructor from components.
Definition at line 279 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), and InfoInFunction.
GeometricField (const IOobject & io, const Mesh & mesh, const dimensionSet & ds, const Field< Type > & iField, const PtrList< PatchField< Type >> & ptfl)
Constructor from components.
Definition at line 303 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), and InfoInFunction.
GeometricField (const IOobject & io, const Mesh & mesh)
Construct and read given IOobject.
Definition at line 329 of file GeometricField.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, GeometricField< Type, PatchField, GeoMesh >::GeometricField(), InfoInFunction, mesh, and Foam::readFields().
GeometricField (const IOobject & io, const Mesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 364 of file GeometricField.C.
References Foam::endl(), Foam::exit(), FatalErrorInFunction, Foam::FatalIOError, GeometricField< Type, PatchField, GeoMesh >::GeometricField(), InfoInFunction, mesh, and Foam::readFields().
GeometricField (const GeometricField< Type, PatchField, GeoMesh > & gf)
Construct as copy.
Definition at line 401 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), and InfoInFunction.
GeometricField (const tmp< GeometricField< Type, PatchField, GeoMesh >> & tgf)
Construct as copy of tmp<GeometricField> deleting argument.
Definition at line 432 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), and InfoInFunction.
GeometricField (const IOobject & io, const GeometricField< Type, PatchField, GeoMesh > & gf)
Construct as copy resetting IO parameters.
Definition at line 461 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), InfoInFunction, and IOobject::name().
GeometricField (const IOobject & io, const tmp< GeometricField< Type, PatchField, GeoMesh >> & tgf)
Construct as copy of tmp<GeometricField> resetting IO parameters.
Definition at line 493 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), and InfoInFunction.
GeometricField (const word & newName, const GeometricField< Type, PatchField, GeoMesh > & gf)
Construct as copy resetting name.
Definition at line 525 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), and InfoInFunction.
GeometricField (const word & newName, const tmp< GeometricField< Type, PatchField, GeoMesh >> & tgf)
Construct as copy resetting name.
Definition at line 557 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), and InfoInFunction.
GeometricField (const IOobject & io, const GeometricField< Type, PatchField, GeoMesh > & gf, const word & patchFieldType)
Construct as copy resetting IO parameters and patch type.
Definition at line 587 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), InfoInFunction, and IOobject::name().
GeometricField (const IOobject & io, const GeometricField< Type, PatchField, GeoMesh > & gf, const wordList & patchFieldTypes, const wordList & actualPatchTypes = wordList())
Construct as copy resetting IO parameters and boundary types.
Definition at line 621 of file GeometricField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), InfoInFunction, and IOobject::name().
GeometricField (const IOobject & io, const tmp< GeometricField< Type, PatchField, GeoMesh >> & tgf, const wordList & patchFieldTypes, const wordList & actualPatchTypes = wordList())
Construct as copy resetting IO parameters and boundary types.
Definition at line 664 of file GeometricField.C.
References Foam::endl(), and InfoInFunction.
~GeometricField () virtual
Destructor.
Definition at line 705 of file GeometricField.C.
References Foam::deleteDemandDrivenData().
Member Function Documentation
TypeName ("GeometricField< Type, PatchField, GeoMesh >")
Runtime type information.
const Foam::GeometricField< Type, PatchField, GeoMesh > & null () inline static
Return a null geometric field.
Definition at line 30 of file GeometricFieldI.H.
References GeometricField< Type, PatchField, GeoMesh >::internalField().
Referenced by ddtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), and CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr().
Foam::GeometricField< Type, PatchField, GeoMesh >::Internal & ref ()
Return a reference to the dimensioned internal field.
Note: this increments the event counter and checks the old-time fields; avoid in loops.
Definition at line 717 of file GeometricField.C.
Referenced by interRegionHeatTransferModel::addSup(), Foam::atan2(), motionSmootherAlgo::avg(), Poisson::correct(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), heThermo< BasicThermo, MixtureType >::CpByCpv(), heThermo< BasicThermo, MixtureType >::Cpv(), heThermo< BasicThermo, MixtureType >::Cv(), MRFZoneList::DDt(), fvFieldDecomposer::decomposeField(), singleStepCombustion< CombThermoType, ThermoType >::dQ(), solidChemistryModel< CompType, SolidThermo >::dQ(), chemistryModel< CompType, ThermoType >::dQ(), heThermo< BasicThermo, MixtureType >::gamma(), fvMatrix< Type >::H1(), Foam::interpolate(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), laplaceFilter::laplaceFilter(), PhiScheme< Type, PhiLimiter >::limiter(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), Foam::pow(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), heheuPsiThermo< BasicPsiThermo, MixtureType >::Tb(), SRFModel::Uabs(), reverseLinear< Type >::weights(), clippedLinear< Type >::weights(), and FSD< CombThermoType, ThermoType >::~FSD().
const Foam::GeometricField< Type, PatchField, GeoMesh >::Internal & internalField () const inline
Return a const-reference to the dimensioned internal field.
Definition at line 41 of file GeometricFieldI.H.
Referenced by fvMeshSubset::interpolate(), and GeometricField< Type, PatchField, GeoMesh >::null().
const Foam::GeometricField< Type, PatchField, GeoMesh >::Internal & v () const inline
Return a const-reference to the dimensioned internal field.
of a "vol" field. Useful in the formulation of source-terms for FV equations
Definition at line 31 of file volFieldsI.H.
Referenced by kEpsilon< BasicTurbulenceModel >::correct().
Foam::GeometricField< Type, PatchField, GeoMesh >::Internal::FieldType & primitiveFieldRef ()
Return a reference to the internal field.
Note: this increments the event counter and checks the old-time fields; avoid in loops.
Definition at line 728 of file GeometricField.C.
Referenced by MRFZone::addCoriolis(), interRegionExplicitPorositySource::addSup(), Foam::atan2(), Foam::fvc::average(), Foam::bound(), Implicit< CloudType >::cacheFields(), curvatureSeparation::calcCosAngle(), faceLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), Foam::checkMethod(), pointConstraints::constrain(), pointConstraints::constrainDisplacement(), Foam::MULES::correct(), inverseVolumeDiffusivity::correct(), inverseDistanceDiffusivity::correct(), limitTemperature::correct(), curvatureSeparation::correct(), wideBandAbsorptionEmission::correct(), fvMatrix< Type >::flux(), forAll(), fvMatrix< Type >::H(), heThermo< BasicThermo, MixtureType >::hc(), heThermo< BasicThermo, MixtureType >::he(), surfaceInterpolationScheme< Type >::interpolate(), volPointInterpolation::interpolateBoundaryField(), Foam::mag(), Foam::magSqr(), Foam::MapGeometricFields(), meshToMesh::mapSrcToTgt(), fvMeshAdder::MapVolFields(), surfaceInterpolation::movePoints(), fvMesh::movePoints(), heheuPsiThermo< BasicPsiThermo, MixtureType >::mub(), heheuPsiThermo< BasicPsiThermo, MixtureType >::muu(), VoidFraction< CloudType >::postEvolve(), Foam::pow(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psib(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psiu(), dynamicRefineFvMesh::refine(), rigidBodyMeshMotion::rigidBodyMeshMotion(), standardRadiation::Shs(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveSegregated(), Foam::sqr(), Foam::stabilise(), ReactingCloud< CloudType >::SYi(), Foam::T(), KinematicCloud< CloudType >::theta(), Foam::transform(), KinematicCloud< CloudType >::vDotSweep(), limitedSurfaceInterpolationScheme< Type >::weights(), AveragingMethod< Type >::write(), and Basic< Type >::~Basic().
const Foam::GeometricField< Type, PatchField, GeoMesh >::Internal::FieldType & primitiveField () const inline
Return a const-reference to the internal field.
Definition at line 51 of file GeometricFieldI.H.
Referenced by interRegionExplicitPorositySource::addSup(), Foam::atan2(), Foam::bound(), Implicit< CloudType >::cacheFields(), Foam::calcEk(), faceLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), Foam::cmptAv(), Foam::component(), Foam::MULES::correct(), phaseChangeModel::correct(), limitedSnGrad< Type >::correction(), kinematicSingleLayer::CourantNumber(), motionSmootherAlgo::curPoints(), fvFieldDecomposer::decomposeField(), wideBandAbsorptionEmission::ECont(), reactingOneDim::evolveRegion(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), EulerD2dt2Scheme< Type >::fvcD2dt2(), backwardDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), gaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), rotorDiskSource::inflowVelocity(), kinematicSingleLayer::info(), fvMeshSubset::interpolate(), isoSurface::isoSurface(), Kmesh::Kmesh(), Foam::MULES::limiterCorr(), Foam::mag(), Foam::magSqr(), Foam::makeGraph(), meshToMesh::mapTgtToSrc(), GeometricField< Type, PatchField, GeoMesh >::operator=(), Foam::pow(), pointFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvVolumeField(), rigidBodyMeshMotion::rigidBodyMeshMotion(), sampledPatchInternalField::sampleField(), motionSmootherAlgo::scaleMesh(), sixDoFRigidBodyMotionSolver::sixDoFRigidBodyMotionSolver(), SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::SlicedGeometricField(), reactingOneDim::solidRegionDiffNo(), fvMatrix< Type >::solveSegregated(), Foam::sqr(), Foam::stabilise(), Foam::T(), Foam::transform(), Foam::fvc::volumeIntegrate(), regionSizeDistribution::write(), Foam::writeCellGraph(), and skewCorrectionVectors::~skewCorrectionVectors().
Foam::GeometricField< Type, PatchField, GeoMesh >::Boundary & boundaryFieldRef ()
Return a reference to the boundary field.
Note: this increments the event counter and checks the old-time fields; avoid in loops.
Definition at line 739 of file GeometricField.C.
Referenced by thermoSingleLayer::addSources(), kinematicSingleLayer::addSources(), Foam::adjustPhi(), Foam::atan2(), Foam::fvc::average(), Foam::bound(), wallShearStress::calcShearStress(), P1::calculate(), viewFactor::calculate(), Foam::constrainHbyA(), Foam::constrainPressure(), limitTemperature::correct(), wallDistData< TransferType >::correct(), meshWave::correct(), LamBremhorstKE::correct(), ShihQuadraticKE::correct(), Poisson::correct(), LienLeschziner::correct(), LienCubicKE::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kkLOmega::correct(), motionSmootherAlgo::correct(), motionSmootherAlgo::correctBoundaryConditions(), MRFZoneList::correctBoundaryFlux(), MRFZone::correctBoundaryVelocity(), thermoSingleLayer::correctHsForMappedT(), mixtureKEpsilon< BasicTurbulenceModel >::correctInletOutlet(), cubic< Type >::correction(), Foam::correctUphiBCs(), ReynoldsStress< BasicTurbulenceModel >::correctWallShearStress(), fvMesh::delta(), fvMatrix< Type >::flux(), fvMatrix< Type >::fvMatrix(), SpalartAllmaras< BasicTurbulenceModel >::fw(), heThermo< BasicThermo, MixtureType >::hc(), heThermo< BasicThermo, MixtureType >::he(), heThermo< BasicThermo, MixtureType >::heBoundaryCorrection(), psiuReactionThermo::heuBoundaryCorrection(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), fvMeshSubset::interpolate(), meshToMesh0::interpolate(), Foam::MULES::limiterCorr(), Foam::mag(), Foam::magSqr(), MRFZone::makeAbsolute(), MRFZone::makeRelative(), Foam::MapGeometricFields(), meshToMesh::mapSrcToTgt(), fvMeshAdder::MapVolFields(), fvMotionSolverEngineMesh::move(), surfaceInterpolation::movePoints(), fvMesh::movePoints(), heheuPsiThermo< BasicPsiThermo, MixtureType >::mub(), heheuPsiThermo< BasicPsiThermo, MixtureType >::muu(), consumptionSpeed::omega0Sigma(), Foam::pow(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psib(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psiu(), dynamicRefineFvMesh::refine(), nearWallFields::sampleBoundaryField(), pointConstraints::setPatchFields(), snGradScheme< Type >::snGrad(), fvMatrix< Type >::solveCoupled(), Foam::sqr(), Foam::stabilise(), Foam::T(), thermoSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), Foam::transform(), dynamicRefineFvMesh::unrefine(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), fvDOM::updateG(), reactingOneDim::updatePhiGas(), reactingOneDim::updateQr(), limitedSurfaceInterpolationScheme< Type >::weights(), externalCoupledMixedFvPatchField< Type >::~externalCoupledMixedFvPatchField(), Gulders::~Gulders(), GuldersEGR::~GuldersEGR(), and skewCorrectionVectors::~skewCorrectionVectors().
const Foam::GeometricField< Type, PatchField, GeoMesh >::Boundary & boundaryField () const inline
Return const-reference to the boundary field.
Definition at line 60 of file GeometricFieldI.H.
Referenced by isoSurface::adaptPatchFields(), reactingOneDim::addMassSources(), effectivenessHeatExchangerSource::addSup(), Foam::adjustPhi(), basicThermo::alpha(), Foam::atan2(), Foam::fvc::average(), Foam::bound(), SurfaceFilmModel< CloudType >::cacheFilmFields(), ThermoSurfaceFilm< CloudType >::cacheFilmFields(), curvatureSeparation::calcCosAngle(), CentredFitSnGradData< Polynomial >::calcFit(), forces::calcForcesMoment(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), fieldMinMax::calcMinMaxFields(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), wallShearStress::calcShearStress(), P1::calculate(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), viewFactor::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), reactingOneDim::calculateMassTransfer(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), CentredFitData< Polynomial >::CentredFitData(), fvPatch::Cf(), Foam::cmptAv(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), Foam::component(), Foam::constrainHbyA(), Foam::constrainPressure(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), injectionModelList::correct(), limitTemperature::correct(), contactAngleForce::correct(), gaussGrad< Type >::correctBoundaryConditions(), MRFZoneList::correctBoundaryFlux(), thermoSingleLayer::correctHsForMappedT(), mixtureKEpsilon< BasicTurbulenceModel >::correctInletOutlet(), pointLinear< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), outletStabilised< Type >::correction(), Foam::CorrectPhi(), Foam::correctUphiBCs(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), motionSmootherAlgo::curPoints(), fvFieldDecomposer::decomposeField(), fvPatch::deltaCoeffs(), kOmega< BasicTurbulenceModel >::epsilon(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::epsilon(), mixtureKEpsilon< BasicTurbulenceModel >::epsilonBoundaryTypes(), epsilonWallFunctionFvPatchScalarField::epsilonPatch(), FacePostProcessing< CloudType >::FacePostProcessing(), surfaceRegion::filterField(), volPointInterpolation::flatBoundaryField(), PatchFlowRateInjection< CloudType >::flowRate(), EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), ddtScheme< Type >::fvcDdtPhiCoeff(), CrankNicolsonDdtScheme< Type >::fvmDdt(), gaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), isoSurface::generateFaceTriPoints(), heThermo< BasicThermo, MixtureType >::he(), psiuReactionThermo::heuBoundaryTypes(), thermoSingleLayer::hs(), FreeStream< CloudType >::inflow(), thermalBaffle::info(), mixtureKEpsilon< BasicTurbulenceModel >::initMixtureFields(), SurfaceFilmModel< CloudType >::inject(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), meshToMesh0::interpolate(), kkLOmega::k(), temperatureCoupledBase::kappa(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limiterCorr(), Foam::mag(), fvPatch::magSf(), Foam::magSqr(), patchMeanVelocityForce::magUbarAve(), MRFZone::makeAbsolute(), MRFZone::makeRelative(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), surfaceInterpolation::movePoints(), psiThermo::mu(), rhoThermo::mu(), incompressibleTwoPhaseInteractingMixture::mu(), heheuPsiThermo< BasicPsiThermo, MixtureType >::mub(), cyclicFvPatchField< Type >::neighbourPatchField(), cyclicAMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::nonOverlapPatchField(), Newtonian::nu(), CrossPowerLaw::nu(), powerLaw::nu(), HerschelBulkley::nu(), BirdCarreau::nu(), incompressibleTwoPhaseMixture::nu(), incompressibleTwoPhaseInteractingMixture::nu(), incompressibleThreePhaseMixture::nu(), eddyViscosity< RASModel< BasicTurbulenceModel > >::nut(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut(), consumptionSpeed::omega0Sigma(), omegaWallFunctionFvPatchScalarField::omegaPatch(), GeometricField< Type, PatchField, GeoMesh >::operator/=(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator==(), KinematicCloud< CloudType >::patchData(), homogeneousMixture< ThermoType >::patchFaceMixture(), inhomogeneousMixture< ThermoType >::patchFaceMixture(), egrMixture< ThermoType >::patchFaceMixture(), veryInhomogeneousMixture< ThermoType >::patchFaceMixture(), inhomogeneousMixture< ThermoType >::patchFaceProducts(), veryInhomogeneousMixture< ThermoType >::patchFaceProducts(), egrMixture< ThermoType >::patchFaceProducts(), inhomogeneousMixture< ThermoType >::patchFaceReactants(), veryInhomogeneousMixture< ThermoType >::patchFaceReactants(), egrMixture< ThermoType >::patchFaceReactants(), fvPatch::patchField(), Foam::pow(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psib(), thermoSingleLayer::Qconvp(), thermoSingleLayer::Qconvw(), pointFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvVolumeField(), Foam::fvc::reconstructMag(), dynamicRefineFvMesh::refine(), Foam::reusable(), psiThermo::rho(), rhoThermo::rho(), incompressibleTwoPhaseInteractingMixture::rho(), patchProbes::sample(), sampledPatch::sampleField(), sampledTriSurfaceMesh::sampleField(), epsilonWallFunctionFvPatchScalarField::setMaster(), omegaWallFunctionFvPatchScalarField::setMaster(), fvPatch::Sf(), snGradScheme< Type >::snGrad(), thermalBaffle::solveEnergy(), fvMatrix< Type >::solveSegregated(), ThermoSurfaceFilm< CloudType >::splashInteraction(), Foam::fvc::spread(), Foam::sqr(), thermoSingleLayer::Srho(), Foam::stabilise(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), cyclicPointPatchField< Type >::swapAddSeparated(), cyclicAMIPointPatchField< Type >::swapAddSeparated(), cyclicACMIPointPatchField< Type >::swapAddSeparated(), Foam::fvc::sweep(), Foam::T(), thermoSingleLayer::thermoSingleLayer(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), thermoSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), Foam::transform(), dynamicRefineFvMesh::unrefine(), gradientUnburntEnthalpyFvPatchScalarField::updateCoeffs(), mixedUnburntEnthalpyFvPatchScalarField::updateCoeffs(), fixedUnburntEnthalpyFvPatchScalarField::updateCoeffs(), mixedEnergyFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), energyJumpFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), fixedEnergyFvPatchScalarField::updateCoeffs(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), gradientEnergyFvPatchScalarField::updateCoeffs(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), alphatWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), motionSmootherAlgo::updateMesh(), reactingOneDim::updateQr(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), UpwindFitData< Polynomial >::UpwindFitData(), extendedUpwindCellToFaceStencil::weightedSum(), outletStabilised< Type >::weights(), limitedSurfaceInterpolationScheme< Type >::weights(), fvPatch::weights(), yPlus::write(), wallShearStress::write(), regionSizeDistribution::write(), externalCoupledMixedFvPatchField< Type >::writeData(), ensightParts::writeField(), externalCoupledMixedFvPatchField< Type >::writeGeometry(), Foam::writePatchGraph(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), Gulders::~Gulders(), GuldersEGR::~GuldersEGR(), leastSquaresVectors::~leastSquaresVectors(), skewCorrectionVectors::~skewCorrectionVectors(), and thermalBaffle::~thermalBaffle().
Foam::label timeIndex () const inline
Return the time index of the field.
Definition at line 68 of file GeometricFieldI.H.
Referenced by fvMesh::movePoints(), fvMesh::phi(), and subCycleField< GeometricField >::~subCycleField().
Foam::label & timeIndex () inline
Return the time index of the field.
Definition at line 76 of file GeometricFieldI.H.
References GeometricField< Type, PatchField, GeoMesh >::operator()().
void storeOldTimes () const
Store the old-time fields.
Definition at line 748 of file GeometricField.C.
References Foam::name(), and timeIndex.
Referenced by Foam::MapGeometricFields().
void storeOldTime () const
Store the old-time field.
Definition at line 769 of file GeometricField.C.
References Foam::endl(), and InfoInFunction.
Foam::label nOldTimes () const
Return the number of old time fields stored.
Definition at line 794 of file GeometricField.C.
const Foam::GeometricField< Type, PatchField, GeoMesh > & oldTime () const
Return old time field.
Definition at line 809 of file GeometricField.C.
References Foam::name(), and timeName.
Referenced by EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::meshPhi(), fvMesh::movePoints(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), and advectiveFvPatchField< Type >::updateCoeffs().
Foam::GeometricField< Type, PatchField, GeoMesh > & oldTime ()
Return non-const old time field.
(Not a good idea but it is used for sub-cycling)
Definition at line 838 of file GeometricField.C.
References GeometricField< Type, PatchField, GeoMesh >::oldTime().
void storePrevIter () const
Store the field as the previous iteration value.
Definition at line 848 of file GeometricField.C.
References Foam::endl(), InfoInFunction, and Foam::name().
Referenced by viewFactor::calculate().
const Foam::GeometricField< Type, PatchField, GeoMesh > & prevIter () const
Return previous iteration field.
Definition at line 874 of file GeometricField.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
void correctBoundaryConditions ()
Correct boundary field.
Definition at line 891 of file GeometricField.C.
Referenced by porosityModel::addResistance(), Foam::fvc::average(), Implicit< CloudType >::cacheFields(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), Foam::checkMethod(), pointConstraints::constrain(), pointConstraints::constrainDisplacement(), Foam::MULES::correct(), inverseVolumeDiffusivity::correct(), inverseDistanceDiffusivity::correct(), injectionModelList::correct(), primaryRadiation::correct(), mappedConvectiveHeatTransfer::correct(), standardRadiation::correct(), ArrheniusViscosity::correct(), phaseChangeModel::correct(), thixotropicViscosity::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), qZeta::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kkLOmega::correct(), thermoSingleLayer::correctAlpha(), thermoSingleLayer::correctHsForMappedT(), ShihQuadraticKE::correctNonlinearStress(), LienCubicKE::correctNonlinearStress(), qZeta::correctNut(), LienLeschziner::correctNut(), SpalartAllmaras< BasicTurbulenceModel >::correctNut(), SpalartAllmarasDES< BasicTurbulenceModel >::correctNut(), forAllIter(), fvMatrix< Type >::H(), kkLOmega::kkLOmega(), sampledSurface::pointAverage(), GeometricField< Type, PatchField, GeoMesh >::prevIter(), standardRadiation::Shs(), Foam::fvc::smooth(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), kinematicSingleLayer::solveMomentum(), fvMatrix< Type >::solveSegregated(), kinematicSingleLayer::solveThickness(), Foam::fvc::spread(), Foam::fvc::sweep(), KinematicCloud< CloudType >::theta(), thermoSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), thermoSingleLayer::transferPrimaryRegionThermoFields(), kinematicSingleLayer::transferPrimaryRegionThermoFields(), dynamicMotionSolverFvMesh::update(), dynamicInkJetFvMesh::update(), multiSolidBodyMotionFvMesh::update(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), reactingOneDim::updateQr(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), KinematicCloud< CloudType >::vDotSweep(), and Basic< Type >::~Basic().
bool needReference () const
Does the field need a reference level for solution.
Definition at line 900 of file GeometricField.C.
References forAll, patchi, and Foam::reduce().
Referenced by Foam::adjustPhi(), and Foam::setRefCell().
tmp<GeometricField<cmptType, PatchField, GeoMesh> > component (const direction) const
Return a component of the field.
Referenced by anisotropicFilter::anisotropicFilter(), cubic< Type >::correction(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), Foam::fvc::magSqrGradGrad(), skewCorrected< Type >::skewCorrection(), and GeometricField< Type, PatchField, GeoMesh >::T().
bool writeData (Ostream & os) const virtual
WriteData member function required by regIOobject.
Reimplemented from DimensionedField< Type, GeoMesh >.
Definition at line 991 of file GeometricField.C.
References IOstream::good().
Referenced by GeometricField< Type, PatchField, GeoMesh >::operator/=(), and GeometricField< Type, PatchField, GeoMesh >::writeMinMax().
Foam::tmp< Foam::GeometricField< Type, PatchField, GeoMesh > > T () const
Return transpose (only if it is a tensor field)
Definition at line 1002 of file GeometricField.C.
References Foam::component(), GeometricField< Type, PatchField, GeoMesh >::component(), mesh, Foam::name(), primitiveFieldRef(), tmp< T >::ref(), GeometricField< Type, PatchField, GeoMesh >::replace(), and Foam::T().
Referenced by displacementSBRStressFvMotionSolver::solve().
void relax (const scalar alpha)
Relax field (for steady-state solution).
alpha = 1 : no relaxation alpha < 1 : relaxation alpha = 0 : do nothing
Definition at line 923 of file GeometricField.C.
References Foam::endl(), InfoInFunction, and Foam::operator==().
Referenced by viewFactor::calculate().
void relax ()
Relax field (for steady-state solution).
alpha is read from controlDict
Definition at line 936 of file GeometricField.C.
References mesh, Foam::name(), relax(), and GeometricField< Type, PatchField, GeoMesh >::select().
Foam::word select (bool final) const
Select the final iteration parameters if `final' is true.
by returning the field name + "Final" otherwise the standard parameters by returning the field name
Definition at line 961 of file GeometricField.C.
References Foam::name(), and GeometricField< Type, PatchField, GeoMesh >::writeMinMax().
Referenced by GeometricField< Type, PatchField, GeoMesh >::relax().
void writeMinMax (Ostream & os) const
Helper function to write the min and max to an Ostream.
Definition at line 978 of file GeometricField.C.
References Foam::endl(), Foam::max(), Foam::min(), Foam::name(), and GeometricField< Type, PatchField, GeoMesh >::writeData().
Referenced by GeometricField< Type, PatchField, GeoMesh >::select().
void negate ()
Definition at line 1115 of file GeometricField.C.
References primitiveFieldRef().
void replace (const direction , const GeometricField< cmptType, PatchField, GeoMesh > &)
Referenced by GeometricField< Type, PatchField, GeoMesh >::component(), cubic< Type >::correction(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), fvMatrix< Type >::H(), anisotropicFilter::operator()(), and GeometricField< Type, PatchField, GeoMesh >::T().
void replace (const direction d, const dimensioned< cmptType > & ds)
Definition at line 1082 of file GeometricField.C.
References GeometricField< Type, PatchField, GeoMesh >::max(), primitiveFieldRef(), and dimensioned< Type >::value().
void max (const dimensioned< Type > & dt)
Definition at line 1094 of file GeometricField.C.
References Foam::max(), GeometricField< Type, PatchField, GeoMesh >::min(), primitiveFieldRef(), and dimensioned< Type >::value().
Referenced by ReynoldsStress< BasicTurbulenceModel >::boundNormalStress(), dynamicKEqn< BasicTurbulenceModel >::Ce(), thixotropicViscosity::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), GeometricField< Type, PatchField, GeoMesh >::replace(), reactingOneDim::solveSpeciesMass(), and kinematicSingleLayer::solveThickness().
void min (const dimensioned< Type > & dt)
Definition at line 1105 of file GeometricField.C.
References Foam::min(), primitiveFieldRef(), and dimensioned< Type >::value().
Referenced by thixotropicViscosity::correct(), kinematicSingleLayer::gNormClipped(), GeometricField< Type, PatchField, GeoMesh >::max(), and laminar::Su().
void max (const GeometricField< Type, PatchField, GeoMesh > & , const dimensioned< Type > &)
void min (const GeometricField< Type, PatchField, GeoMesh > & , const dimensioned< Type > &)
void scale (const GeometricField< Type, PatchField, GeoMesh > & , const GeometricField< Type, PatchField, GeoMesh > &)
void scale (const GeometricField< Type, PatchField, GeoMesh > & , const dimensioned< Type > &)
const Foam::GeometricField< Type, PatchField, GeoMesh >::Internal & operator() () const inline
Return a const-reference to the dimensioned internal field.
Useful in the formulation of source-terms for FV equations
Definition at line 89 of file GeometricFieldI.H.
Referenced by GeometricField< Type, PatchField, GeoMesh >::timeIndex().
void operator= (const GeometricField< Type, PatchField, GeoMesh > & gf)
Definition at line 1126 of file GeometricField.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), checkField, Foam::FatalError, FatalErrorInFunction, and ref().
void operator= (const tmp< GeometricField< Type, PatchField, GeoMesh >> & tgf)
Definition at line 1148 of file GeometricField.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), checkField, DimensionedField< Type, GeoMesh >::dimensions(), Foam::FatalError, FatalErrorInFunction, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and primitiveFieldRef().
void operator= (const dimensioned< Type > & dt)
Definition at line 1181 of file GeometricField.C.
References ref(), and dimensioned< Type >::value().
void operator== (const tmp< GeometricField< Type, PatchField, GeoMesh >> & tgf)
Definition at line 1192 of file GeometricField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), checkField, and ref().
void operator== (const dimensioned< Type > & dt)
Definition at line 1211 of file GeometricField.C.
References ref(), and dimensioned< Type >::value().
void operator+= (const GeometricField< Type, PatchField, GeoMesh > & gf)
Definition at line 1254 of file GeometricField.C.
void operator+= (const tmp< GeometricField< Type, PatchField, GeoMesh >> & tgf)
Definition at line 1254 of file GeometricField.C.
void operator-= (const GeometricField< Type, PatchField, GeoMesh > & gf)
Definition at line 1255 of file GeometricField.C.
void operator-= (const tmp< GeometricField< Type, PatchField, GeoMesh >> & tgf)
Definition at line 1255 of file GeometricField.C.
void operator*= (const GeometricField< scalar, PatchField, GeoMesh > & gf)
Definition at line 1256 of file GeometricField.C.
void operator*= (const tmp< GeometricField< scalar, PatchField, GeoMesh >> & tgf)
Definition at line 1256 of file GeometricField.C.
void operator/= (const GeometricField< scalar, PatchField, GeoMesh > & gf)
Definition at line 1257 of file GeometricField.C.
void operator/= (const tmp< GeometricField< scalar, PatchField, GeoMesh >> & tgf)
Definition at line 1257 of file GeometricField.C.
void operator+= (const dimensioned< Type > & dt)
Definition at line 1254 of file GeometricField.C.
void operator-= (const dimensioned< Type > & dt)
Definition at line 1255 of file GeometricField.C.
void operator*= (const dimensioned< scalar > & dt)
Definition at line 1256 of file GeometricField.C.
void operator/= (const dimensioned< scalar > & dt)
Definition at line 1257 of file GeometricField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::nl, and GeometricField< Type, PatchField, GeoMesh >::writeData().
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
Definition at line 62 of file volFields.C.
References GeometricField< Type, PatchField, GeoMesh >::replace().
void replace (const direction , const GeometricField< scalar, fvPatchField, volMesh > & gsf)
Definition at line 73 of file volFields.C.
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
void replace (const direction , const GeometricField< scalar, fvPatchField, volMesh > & sf)
Friends And Related Function Documentation
Ostream& operator (Ostream & , const GeometricField< Type, PatchField, GeoMesh > &) friend
Ostream& operator (Ostream & , const tmp< GeometricField< Type, PatchField, GeoMesh >> &) friend
The documentation for this class was generated from the following files:
src/finiteVolume/fields/surfaceFields/surfaceFieldsFwd.H
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricField.H
src/finiteVolume/fields/volFields/volFieldsI.H
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricField.C
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricFieldI.H