OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
GuldersEGR Class Reference
Laminar flame speed obtained from Gulder's correlation with EGR modelling.
Public Member Functions
TypeName ("GuldersEGR")
Runtime type information.
GuldersEGR (const dictionary &, const psiuReactionThermo &)
Construct from dictionary and psiuReactionThermo.
virtual ~GuldersEGR ()
Destructor.
tmp< volScalarField > operator() () const
Return the laminar flame speed [m/s].
Public Member Functions inherited from laminarFlameSpeed
TypeName ("laminarFlameSpeed")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, laminarFlameSpeed, dictionary,(const dictionary &dict, const psiuReactionThermo &ct),(dict, ct))
laminarFlameSpeed (const dictionary &, const psiuReactionThermo &)
Construct from dictionary and psiuReactionThermo.
virtual ~laminarFlameSpeed ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from laminarFlameSpeed
static autoPtr< laminarFlameSpeed > New (const psiuReactionThermo &)
Protected Attributes inherited from laminarFlameSpeed
const psiuReactionThermo & psiuReactionThermo_
word fuel_
Fuel.
scalar equivalenceRatio_
Equivalence ratio of a homogeneous mixture.
Detailed Description
Laminar flame speed obtained from Gulder's correlation with EGR modelling.
Source files
GuldersEGR.H
GuldersEGR.C
Definition at line 50 of file GuldersEGR.H.
Constructor & Destructor Documentation
GuldersEGR (const dictionary & dict, const psiuReactionThermo & ct)
Construct from dictionary and psiuReactionThermo.
Definition at line 49 of file GuldersEGR.C.
~GuldersEGR () virtual
Destructor.
Definition at line 68 of file GuldersEGR.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), IOobject::db(), Foam::dimVelocity, Foam::exp(), forAll, DimensionedField< Type, GeoMesh >::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, p, patchi, phi, Foam::pow(), pRef, tmp< T >::ref(), Foam::sqr(), IOobject::time(), and Time::timeName().
Member Function Documentation
TypeName ("GuldersEGR")
Runtime type information.
Foam::tmp< Foam::volScalarField > operator() () const virtual
Return the laminar flame speed [m/s].
Implements laminarFlameSpeed.
Definition at line 211 of file GuldersEGR.C.
The documentation for this class was generated from the following files:
src/thermophysicalModels/laminarFlameSpeed/GuldersEGR/GuldersEGR.H
src/thermophysicalModels/laminarFlameSpeed/GuldersEGR/GuldersEGR.C