OpenFOAM: HashSet< Key, Hash > Class Template Reference
HashSet< Key, Hash > Class Template Reference
A HashTable with keys but without contents.
Public Types
typedef HashTable< nil, Key, Hash >::iterator iterator
typedef HashTable< nil, Key, Hash >::const_iterator const_iterator
Public Types inherited from HashTable< nil, Key, Hash >
typedef nil value_type
Type of values the HashTable contains.
typedef nil & reference
Type that can be used for storing into HashTable::value_type.
typedef const nil & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Member Functions
HashSet (const label size=128)
Construct given initial size.
HashSet (Istream &is)
Construct from Istream.
HashSet (const UList< Key > &)
Construct from UList of Key.
HashSet (const HashSet< Key, Hash > &hs)
Construct as copy.
HashSet (const Xfer< HashSet< Key, Hash >> &hs)
Construct by transferring the parameter contents.
HashSet (const Xfer< HashTable< nil, Key, Hash >> &hs)
Construct by transferring the parameter contents.
template<class AnyType , class AnyHash >
HashSet (const HashTable< AnyType, Key, AnyHash > &)
Construct from the keys of another HashTable,.
bool insert (const Key &key)
Insert a new entry.
label insert (const UList< Key > &)
Insert keys from a UList of Key.
bool set (const Key &key)
Same as insert (cannot overwrite nil content)
label set (const UList< Key > &lst)
Same as insert (cannot overwrite nil content)
bool unset (const Key &key)
Unset the specified key - same as erase.
bool operator[] (const Key &) const
Return true if the entry exists, same as found()
bool operator== (const HashSet< Key, Hash > &) const
Equality. Two hashtables are equal when their contents are equal.
bool operator!= (const HashSet< Key, Hash > &) const
The opposite of the equality operation.
void operator|= (const HashSet< Key, Hash > &)
Combine entries from HashSets.
void operator&= (const HashSet< Key, Hash > &)
Only retain entries found in both HashSets.
void operator^= (const HashSet< Key, Hash > &)
Only retain unique entries (xor)
void operator+= (const HashSet< Key, Hash > &rhs)
Add entries listed in the given HashSet to this HashSet.
void operator-= (const HashSet< Key, Hash > &)
Remove entries listed in the given HashSet from this HashSet.
Public Member Functions inherited from HashTable< nil, Key, Hash >
bool set (const Key &, const nil &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< nil, Key, Hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< nil, Key, Hash >> &)
Construct by transferring the parameter contents.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const Key &) const
Return true if hashedEntry is found in table.
iterator find (const Key &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const Key &) const
Find and return an const_iterator set at the hashedEntry.
List< Key > toc () const
Return the table of contents.
List< Key > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const Key &, const nil &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const Key &)
Erase a hashedEntry specified by the given key.
label erase (const UList< Key > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, Key, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< nil, Key, Hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< nil, Key, Hash > > xfer ()
Transfer contents to the Xfer container.
nil & operator[] (const Key &)
Find and return a hashedEntry.
const nil & operator[] (const Key &) const
Find and return a hashedEntry.
nil & operator() (const Key &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< nil, Key, Hash > &)
Assignment.
bool operator== (const HashTable< nil, Key, Hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< nil, Key, Hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Detailed Description
template<class Key = word, class Hash = string::hash>
class Foam::HashSet< Key, Hash >
A HashTable with keys but without contents.
Definition at line 59 of file HashSet.H.
Member Typedef Documentation
typedef HashTable<nil, Key, Hash>::iterator iterator
Definition at line 66 of file HashSet.H.
typedef HashTable<nil, Key, Hash>::const_iterator const_iterator
Definition at line 67 of file HashSet.H.
Constructor & Destructor Documentation
HashSet (const label size = 128) inline
Construct given initial size.
Definition at line 73 of file HashSet.H.
Referenced by HashSet< label, Hash< label > >::HashSet(), and HashSet< Key, Hash >::HashSet().
HashSet (Istream & is) inline
Construct from Istream.
Definition at line 79 of file HashSet.H.
HashSet (const UList< Key > & lst)
Construct from UList of Key.
Definition at line 34 of file HashSet.C.
References forAll, HashSet< Key, Hash >::HashSet(), and HashSet< Key, Hash >::insert().
HashSet (const HashSet< Key, Hash > & hs) inline
Construct as copy.
Definition at line 88 of file HashSet.H.
HashSet (const Xfer< HashSet< Key, Hash >> & hs) inline
Construct by transferring the parameter contents.
Definition at line 94 of file HashSet.H.
HashSet (const Xfer< HashTable< nil, Key, Hash >> & hs) inline
Construct by transferring the parameter contents.
Definition at line 100 of file HashSet.H.
HashSet (const HashTable< AnyType, Key, AnyHash > & h)
Construct from the keys of another HashTable,.
the type of values held is arbitrary.
Definition at line 48 of file HashSet.C.
References HashTable< T, Key, Hash >::cbegin(), HashTableCore::cend(), and HashSet< Key, Hash >::insert().
Member Function Documentation
bool insert (const Key & key) inline
Insert a new entry.
Definition at line 116 of file HashSet.H.
Referenced by snappyLayerDriver::addLayers(), polyTopoChange::addPoint(), polyMeshGeometry::affectedCells(), decompositionMethod::calcCellCells(), cellToFaceStencil::calcFaceStencil(), primitiveMesh::cellEdges(), cellFeatures::cellFeatures(), primitiveMesh::cellPoints(), primitiveMeshGeometry::checkCellDeterminant(), polyMeshGeometry::checkCellDeterminant(), primitiveMesh::checkCellsZipUp(), primitiveMesh::checkCellVolumes(), primitiveMesh::checkClosedCells(), primitiveMesh::checkCommonOrder(), primitiveMesh::checkConcaveCells(), zone::checkDefinition(), polyBoundaryMesh::checkDefinition(), primitiveMesh::checkDuplicateFaces(), primitiveMesh::checkEdgeLength(), primitiveMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceAngles(), primitiveMesh::checkFaceAngles(), primitiveMeshGeometry::checkFaceArea(), polyMeshGeometry::checkFaceArea(), primitiveMesh::checkFaceAreas(), primitiveMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceFlatness(), primitiveMesh::checkFaceFlatness(), primitiveMesh::checkFaceOrthogonality(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFacePyramids(), primitiveMesh::checkFacePyramids(), primitiveMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceSkewness(), primitiveMesh::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), primitiveMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceTwist(), primitiveMesh::checkFaceVertices(), primitiveMeshGeometry::checkFaceWeights(), polyMeshGeometry::checkFaceWeights(), edgeCollapser::checkMeshQuality(), PatchTools::checkOrientation(), PrimitivePatch< Face, FaceList, PointField, PointType >::checkPointManifold(), primitiveMesh::checkPointNearness(), primitiveMesh::checkPoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::checkTopology(), polyMeshGeometry::checkTriangleTwist(), primitiveMesh::checkUpperTriangular(), polyMeshGeometry::checkVolRatio(), meshRefinement::createBaffles(), geomCellLooper::cut(), structuredDecomp::decompose(), fvMeshDistribute::distribute(), dynamicRefineFvMesh::dynamicRefineFvMesh(), polyBoundaryMesh::findIndices(), indexedOctree< Type >::findLine(), dynamicIndexedOctree< Type >::findNearest(), combineFaces::getMergeSets(), Foam::vtkPVReaders::getSelected(), Foam::vtkPV3Readers::getSelected(), surfaceSets::getSurfaceSets(), triSurfaceTools::getVertexVertices(), HashSet< Key, Hash >::HashSet(), HashSet< label, Hash< label > >::insert(), HashSet< Key, Hash >::insert(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), polyTopoChange::modifyPoint(), NamedEnum< Enum, nEnum >::names(), lessProcPatches::operator()(), HashSet< Key, Hash >::operator^=(), HashSet< Key, Hash >::operator|=(), InflationInjection< CloudType >::parcelsToInject(), Foam::parseNASCoord(), ParticleErosion< CloudType >::ParticleErosion(), PatchPostProcessing< CloudType >::PatchPostProcessing(), polyBoundaryMesh::patchSet(), Foam::polyMeshZipUpCells(), probes::prepare(), NASsurfaceFormat< Face >::read(), wallShearStress::read(), functionObjectList::readFunctionObject(), structuredRenumber::renumber(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), motionSmootherAlgo::scaleMesh(), mapDistributeBase::schedule(), HashSet< label, Hash< label > >::set(), cellSetOption::setCellSet(), removePoints::setRefinement(), surfaceIntersection::surfaceIntersection(), pointSet::sync(), and topoSet::updateLabels().
Foam::label insert (const UList< Key > & lst)
Insert keys from a UList of Key.
Return the number of new elements inserted
Definition at line 70 of file HashSet.C.
References forAll, and HashSet< Key, Hash >::insert().
bool set (const Key & key) inline
Same as insert (cannot overwrite nil content)
Definition at line 126 of file HashSet.H.
label set (const UList< Key > & lst) inline
Same as insert (cannot overwrite nil content)
Definition at line 132 of file HashSet.H.
bool unset (const Key & key) inline
Unset the specified key - same as erase.
Definition at line 138 of file HashSet.H.
bool operator[] (const Key & key) const inline
Return true if the entry exists, same as found()
Definition at line 88 of file HashSet.C.
References HashTable< nil, Key, Hash >::found().
Referenced by HashSet< label, Hash< label > >::unset().
bool operator== (const HashSet< Key, Hash > & rhs) const
Equality. Two hashtables are equal when their contents are equal.
Independent of table size or order.
Definition at line 95 of file HashSet.C.
References HashTable< nil, Key, Hash >::cbegin(), HashTableCore::cend(), and HashTable< nil, Key, Hash >::found().
Referenced by HashSet< Key, Hash >::operator!=(), and HashSet< label, Hash< label > >::unset().
bool operator!= (const HashSet< Key, Hash > & rhs) const
The opposite of the equality operation.
Definition at line 120 of file HashSet.C.
References HashSet< Key, Hash >::operator==().
Referenced by HashSet< label, Hash< label > >::unset().
void operator|= (const HashSet< Key, Hash > & rhs)
Combine entries from HashSets.
Definition at line 127 of file HashSet.C.
References HashTable< nil, Key, Hash >::cbegin(), HashTableCore::cend(), and HashSet< Key, Hash >::insert().
Referenced by HashSet< label, Hash< label > >::operator+=(), and HashSet< label, Hash< label > >::unset().
void operator&= (const HashSet< Key, Hash > & rhs)
Only retain entries found in both HashSets.
Definition at line 138 of file HashSet.C.
References HashTable< nil, Key, Hash >::begin(), HashTableCore::end(), HashTable< nil, Key, Hash >::erase(), and HashTable< nil, Key, Hash >::found().
Referenced by HashSet< label, Hash< label > >::unset().
void operator^= (const HashSet< Key, Hash > & rhs)
Only retain unique entries (xor)
Definition at line 152 of file HashSet.C.
References HashTable< nil, Key, Hash >::cbegin(), HashTableCore::cend(), HashTable< nil, Key, Hash >::erase(), HashTable< nil, Key, Hash >::found(), and HashSet< Key, Hash >::insert().
Referenced by HashSet< label, Hash< label > >::unset().
void operator+= (const HashSet< Key, Hash > & rhs) inline
Add entries listed in the given HashSet to this HashSet.
Definition at line 167 of file HashSet.H.
void operator-= (const HashSet< Key, Hash > & rhs)
Remove entries listed in the given HashSet from this HashSet.
Definition at line 170 of file HashSet.C.
References HashTable< nil, Key, Hash >::cbegin(), HashTableCore::cend(), and HashTable< nil, Key, Hash >::erase().
Referenced by HashSet< label, Hash< label > >::operator+=().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashSet/HashSet.H
src/OpenFOAM/containers/HashTables/HashSet/HashSet.C