OpenFOAM: hashedWordList Class Reference
hashedWordList Class Reference
A wordList with hashed indices for faster lookup by name.
Public Member Functions
hashedWordList ()
Construct null.
hashedWordList (const hashedWordList &)
Copy constructor.
hashedWordList (const UList< word > &names)
Construct from list of names.
hashedWordList (const Xfer< List< word >> &names)
Construct by transferring the parameter contents.
hashedWordList (const label nNames, const char **names)
Construct from number and list of names.
hashedWordList (const char **names)
Construct from a NULL-terminated list of names.
hashedWordList (Istream &)
Construct from Istream.
void clear ()
Clear the list, i.e. set size to zero.
void append (const word &)
Append an element at the end of the list.
bool contains (const word &) const
Does the list contain the specified name.
void transfer (List< word > &)
Transfer the contents of the argument List into this list.
void operator= (const UList< word > &names)
Assignment operator from list of names.
void operator= (const hashedWordList &)
Assignment operator.
const word & operator[] (const label index) const
Return name corresponding to specified index.
label operator[] (const word &) const
Return index corresponding to specified name.
Public Member Functions inherited from List< word >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const word &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< word > &)
Copy constructor.
List (const Xfer< List< word >> &)
Construct by transferring the parameter contents.
List (List< word > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< word > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< word, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< word > &)
Construct as copy of PtrList<T>
List (const SLList< word > &)
Construct as copy of SLList<T>
List (const UIndirectList< word > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< word > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< word > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const word &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const word &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const word &)
Append an element at the end of the list.
void append (const UList< word > &)
Append a List at the end of this list.
void append (const UIndirectList< word > &)
Append a UIndirectList at the end of this list.
void transfer (List< word > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< word, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< word > &)
Transfer the contents of the argument List into this list.
Xfer< List< word > > xfer ()
Transfer contents to the Xfer container.
word & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< word > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< word > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< word > &)
Assignment operator. Takes linear time.
void operator= (const SLList< word > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< word > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< word > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const word &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Friends
Istream & operator>> (Istream &, hashedWordList &)
Ostream & operator<< (Ostream &, const hashedWordList &)
Additional Inherited Members
Public Types inherited from List< word >
typedef SubList< word > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from List< word >
static const List< word > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< word >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
A wordList with hashed indices for faster lookup by name.
Source files
hashedWordList.H
hashedWordListI.H
hashedWordList.C
Definition at line 57 of file hashedWordList.H.
Constructor & Destructor Documentation
hashedWordList ()
Construct null.
Definition at line 42 of file hashedWordList.C.
Referenced by hashedWordList::hashedWordList().
hashedWordList (const hashedWordList & names)
Copy constructor.
Definition at line 56 of file hashedWordList.C.
hashedWordList (const UList< word > & names)
Construct from list of names.
Definition at line 48 of file hashedWordList.C.
hashedWordList (const Xfer< List< word >> & names)
Construct by transferring the parameter contents.
Definition at line 64 of file hashedWordList.C.
References hashedWordList::hashedWordList().
hashedWordList (const label nNames, const char ** names)
Construct from number and list of names.
Definition at line 73 of file hashedWordList.C.
References forAll, hashedWordList::hashedWordList(), and UList< T >::operator[]().
hashedWordList (const char ** names)
Construct from a NULL-terminated list of names.
Definition at line 90 of file hashedWordList.C.
References forAll, UList< T >::operator[](), and List< T >::setSize().
hashedWordList (Istream & is)
Construct from Istream.
Definition at line 111 of file hashedWordList.C.
Member Function Documentation
void clear ()
Clear the list, i.e. set size to zero.
Definition at line 119 of file hashedWordList.C.
References List< T >::clear().
void append (const word & name)
Append an element at the end of the list.
Definition at line 126 of file hashedWordList.C.
References List< T >::append(), and List< word >::size().
bool contains (const word & name) const inline
Does the list contain the specified name.
Definition at line 28 of file hashedWordListI.H.
Referenced by basicMultiComponentMixture::contains(), and Reaction< ReactionThermo >::specieCoeffs::specieCoeffs().
void transfer (List< word > & lst)
Transfer the contents of the argument List into this list.
and annul the argument list.
Definition at line 134 of file hashedWordList.C.
References List< T >::transfer().
void operator= (const UList< word > & names) inline
Assignment operator from list of names.
Definition at line 36 of file hashedWordListI.H.
References List< T >::operator=().
Referenced by hashedWordList::operator=().
void operator= (const hashedWordList & lst) inline
Assignment operator.
Definition at line 43 of file hashedWordListI.H.
References UList< T >::operator, and hashedWordList::operator=().
const Foam::word & operator[] (const label index) const inline
Return name corresponding to specified index.
Definition at line 50 of file hashedWordListI.H.
References UList< T >::operator[]().
Foam::label operator[] (const word & name) const inline
Return index corresponding to specified name.
Definition at line 59 of file hashedWordListI.H.
References Foam::name().
Friends And Related Function Documentation
Istream& operator>> (Istream & , hashedWordList &) friend
Ostream& operator<< (Ostream & , const hashedWordList &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/lists/hashedWordList.H
src/OpenFOAM/primitives/strings/lists/hashedWordList.C
src/OpenFOAM/primitives/strings/lists/hashedWordListI.H