OpenFOAM: GaussSeidelSmoother Class Reference
GaussSeidelSmoother Class Reference
A lduMatrix::smoother for Gauss-Seidel.
Public Member Functions
TypeName ("GaussSeidel")
Runtime type information.
GaussSeidelSmoother (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces)
Construct from components.
virtual void smooth (scalarField &psi, const scalarField &Source, const direction cmpt, const label nSweeps) const
Smooth the solution for a given number of sweeps.
Public Member Functions inherited from lduMatrix::smoother
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, smoother, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
declareRunTimeSelectionTable (autoPtr, smoother, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
smoother (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces)
virtual ~smoother ()
Destructor.
const word & fieldName () const
const lduMatrix & matrix () const
const FieldField< Field, scalar > & interfaceBouCoeffs () const
const FieldField< Field, scalar > & interfaceIntCoeffs () const
const lduInterfaceFieldPtrsList & interfaces () const
Static Public Member Functions
static void smooth (const word &fieldName, scalarField &psi, const lduMatrix &matrix, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt, const label nSweeps)
Smooth for the given number of sweeps.
Static Public Member Functions inherited from lduMatrix::smoother
static word getName (const dictionary &)
Find the smoother name (directly or from a sub-dictionary)
static autoPtr< smoother > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Return a new smoother.
Additional Inherited Members
Protected Attributes inherited from lduMatrix::smoother
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
const lduInterfaceFieldPtrsList & interfaces_
Detailed Description
A lduMatrix::smoother for Gauss-Seidel.
Source files
GaussSeidelSmoother.H
GaussSeidelSmoother.C
Definition at line 48 of file GaussSeidelSmoother.H.
Constructor & Destructor Documentation
GaussSeidelSmoother (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces)
Construct from components.
Definition at line 45 of file GaussSeidelSmoother.C.
References GaussSeidelSmoother::smooth().
Member Function Documentation
TypeName ("GaussSeidel")
Runtime type information.
void smooth (const word & fieldName, scalarField & psi, const lduMatrix & matrix, const scalarField & source, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt, const label nSweeps) static
Smooth for the given number of sweeps.
Definition at line 67 of file GaussSeidelSmoother.C.
References UList< T >::begin(), lduMatrix::diag(), forAll, lduMatrix::initMatrixInterfaces(), lduMatrix::lduAddr(), lduMatrix::lower(), FieldField< Field, Type >::negate(), lduAddressing::ownerStartAddr(), patchi, UPtrList< T >::set(), List< T >::size(), Foam::fvc::sweep(), lduMatrix::updateMatrixInterfaces(), lduMatrix::upper(), and lduAddressing::upperAddr().
Referenced by GaussSeidelSmoother::GaussSeidelSmoother().
void smooth (scalarField & psi, const scalarField & Source, const direction cmpt, const label nSweeps) const virtual
Smooth the solution for a given number of sweeps.
Implements lduMatrix::smoother.
Definition at line 191 of file GaussSeidelSmoother.C.
References Foam::fvc::smooth().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/smoothers/GaussSeidel/GaussSeidelSmoother.H
src/OpenFOAM/matrices/lduMatrix/smoothers/GaussSeidel/GaussSeidelSmoother.C