OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
geomCellLooper Class Reference
Implementation of cellLooper. Does pure geometric cut through cell.
Public Member Functions
TypeName ("geomCellLooper")
Runtime type information.
geomCellLooper (const polyMesh &mesh)
Construct from components.
virtual ~geomCellLooper ()
Destructor.
virtual bool cut (const vector &refDir, const label cellI, const boolList &vertIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, labelList &loop, scalarField &loopWeights) const
Create cut along circumference of cellI. Gets current mesh cuts.
virtual bool cut (const plane &cutPlane, const label cellI, const boolList &vertIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, labelList &loop, scalarField &loopWeights) const
Same but now also base point of cut provided (instead of always.
Public Member Functions inherited from cellLooper
TypeName ("cellLooper")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, cellLooper, word,(const polyMesh &mesh),(mesh))
cellLooper (const polyMesh &mesh)
Construct from components.
autoPtr< cellLooper > clone () const
Clone.
virtual ~cellLooper ()
Destructor.
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Static Public Member Functions
static scalar snapTol ()
static void setSnapTol (const scalar tol)
Static Public Member Functions inherited from cellLooper
static autoPtr< cellLooper > New (const word &type, const polyMesh &mesh)
Return a reference to the selected cellLooper.
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
Is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
Convert eVert to edge label.
static label getVertex (const primitiveMesh &mesh, const label eVert)
Convert eVert to vertex label.
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointI to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Additional Inherited Members
Protected Member Functions inherited from cellLooper
labelList getVertFacesNonEdge (const label cellI, const label edgeI, const label vertI) const
Get faces (on cell) connected to vertI which are not using edgeI.
label getFirstVertEdge (const label faceI, const label vertI) const
Get first edge connected to vertI and on faceI.
labelList getVertEdgesNonFace (const label cellI, const label faceI, const label vertI) const
Get edges (on cell) connected to vertI which are not on faceI.
label getMisAlignedEdge (const vector &refDir, const label cellI) const
Return edge from cellEdges that is most perpendicular.
Detailed Description
Implementation of cellLooper. Does pure geometric cut through cell.
Handles all cell shapes in the same way: cut edges with plane through cell centre and normal in direction of provided direction. Snaps cuts close to edge endpoints (close = snapTol * minEdgeLen) to vertices.
Currently determines cuts through edges (and edgeendpoints close to plane) in random order and then sorts them acc. to angle. Could be converted to use walk but problem is that face can be cut multiple times (since does not need to be convex). Another problem is that edges parallel to plane might not be cut. So these are handled by looking at the distance from edge endpoints to the plane.
Source files
geomCellLooper.H
geomCellLooper.C
Definition at line 63 of file geomCellLooper.H.
Constructor & Destructor Documentation
geomCellLooper (const polyMesh & mesh)
Construct from components.
Definition at line 214 of file geomCellLooper.C.
~geomCellLooper () virtual
Destructor.
Definition at line 222 of file geomCellLooper.C.
References geomCellLooper::cut().
Referenced by geomCellLooper::setSnapTol().
Member Function Documentation
TypeName ("geomCellLooper")
Runtime type information.
static scalar snapTol () inline static
Definition at line 129 of file geomCellLooper.H.
Referenced by cellCuts::nonAnchorPoints().
static void setSnapTol (const scalar tol) inline static
Definition at line 134 of file geomCellLooper.H.
References geomCellLooper::cut(), edgeVertex::mesh(), and geomCellLooper::~geomCellLooper().
bool cut (const vector & refDir, const label cellI, const boolList & vertIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, labelList & loop, scalarField & loopWeights) const virtual
Create cut along circumference of cellI. Gets current mesh cuts.
Cut along circumference is expressed as loop of cuts plus weights for cuts along edges (only valid for edge cuts). Return true if successful cut.
Implements cellLooper.
Reimplemented in topoCellLooper, and hexCellLooper.
Definition at line 229 of file geomCellLooper.C.
References edgeVertex::mesh().
Referenced by hexCellLooper::cut(), geomCellLooper::cut(), geomCellLooper::setSnapTol(), and geomCellLooper::~geomCellLooper().
bool cut (const plane & cutPlane, const label cellI, const boolList & vertIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, labelList & loop, scalarField & loopWeights) const virtual
Same but now also base point of cut provided (instead of always.
cell centre)
Implements cellLooper.
Reimplemented in topoCellLooper, and hexCellLooper.
Definition at line 255 of file geomCellLooper.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), primitiveMesh::cellEdges(), primitiveMesh::cells(), edgeVertex::coord(), geomCellLooper::cut(), plane::distance(), primitiveMesh::edges(), edgeVertex::edgeToEVert(), edge::end(), Foam::endl(), Foam::findIndex(), forAll, HashTable< T, Key, Hash >::found(), HashSet< Key, Hash >::insert(), edgeVertex::isEdge(), Foam::mag(), edgeVertex::mesh(), plane::normal(), points, polyMesh::points(), Foam::Pout, Foam::pseudoAngle(), List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), List< T >::size(), edge::start(), List< T >::transfer(), edgeVertex::vertToEVert(), edgeVertex::writeCut(), and Vector< scalar >::zero.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/cellLooper/geomCellLooper.H
src/dynamicMesh/meshCut/cellLooper/geomCellLooper.C