OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
heSolidThermo< BasicSolidThermo, MixtureType > Class Template Reference
Energy for a solid mixture.
Public Member Functions
TypeName ("heSolidThermo")
Runtime type information.
heSolidThermo (const fvMesh &, const word &phaseName)
Construct from mesh and phase name.
heSolidThermo (const fvMesh &, const dictionary &, const word &phaseName)
Construct from mesh, dictionary and phase name.
virtual ~heSolidThermo ()
Destructor.
virtual void correct ()
Update properties.
virtual tmp< volVectorField > Kappa () const
Anisotropic thermal conductivity [W/m/K].
virtual bool isotropic () const
Return true if thermal conductivity is isotropic.
virtual tmp< vectorField > Kappa (const label patchi) const
Anisotropic thermal conductivity [W/m/K].
Public Member Functions inherited from heThermo< BasicSolidThermo, MixtureType >
heThermo (const fvMesh &, const word &phaseName)
Construct from mesh.
heThermo (const fvMesh &, const dictionary &, const word &phaseName)
Construct from mesh and dictionary.
virtual ~heThermo ()
Destructor.
virtual MixtureType::basicMixtureType & composition ()
Return the compostion of the mixture.
virtual const MixtureType::basicMixtureType & composition () const
Return the compostion of the mixture.
virtual bool incompressible () const
Return true if the equation of state is incompressible.
virtual bool isochoric () const
Return true if the equation of state is isochoric.
virtual volScalarField & he ()
Enthalpy/Internal energy [J/kg].
virtual const volScalarField & he () const
Enthalpy/Internal energy [J/kg].
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &T) const
Enthalpy/Internal energy.
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const labelList &cells) const
Enthalpy/Internal energy for cell-set [J/kg].
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const label patchi) const
Enthalpy/Internal energy for patch [J/kg].
virtual tmp< volScalarField > hc () const
Chemical enthalpy [J/kg].
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const labelList &cells) const
Temperature from enthalpy/internal energy for cell-set.
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const label patchi) const
Temperature from enthalpy/internal energy for patch.
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant pressure for patch [J/kg/K].
virtual tmp< volScalarField > Cp () const
Heat capacity at constant pressure [J/kg/K].
virtual tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant volume for patch [J/kg/K].
virtual tmp< volScalarField > Cv () const
Heat capacity at constant volume [J/kg/K].
virtual tmp< volScalarField > gamma () const
Gamma = Cp/Cv [].
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &T, const label patchi) const
Gamma = Cp/Cv for patch [].
virtual tmp< scalarField > Cpv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant pressure/volume for patch [J/kg/K].
virtual tmp< volScalarField > Cpv () const
Heat capacity at constant pressure/volume [J/kg/K].
virtual tmp< volScalarField > CpByCpv () const
Heat capacity ratio [].
virtual tmp< scalarField > CpByCpv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity ratio for patch [].
virtual tmp< volScalarField > kappa () const
Thermal diffusivity for temperature of mixture [J/m/s/K].
virtual tmp< scalarField > kappa (const label patchi) const
Thermal diffusivity for temperature.
virtual tmp< volScalarField > kappaEff (const volScalarField &) const
Effective thermal diffusivity for temperature.
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
Effective thermal diffusivity for temperature.
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
Effective thermal diffusivity of mixture [kg/m/s].
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
Effective thermal diffusivity of mixture for patch [kg/m/s].
virtual bool read ()
Read thermophysical properties dictionary.
Additional Inherited Members
Protected Member Functions inherited from heThermo< BasicSolidThermo, MixtureType >
void heBoundaryCorrection (volScalarField &he)
Correct the enthalpy/internal energy field boundaries.
Protected Attributes inherited from heThermo< BasicSolidThermo, MixtureType >
volScalarField he_
Energy field.
Detailed Description
template<class BasicSolidThermo, class MixtureType>
class Foam::heSolidThermo< BasicSolidThermo, MixtureType >
Energy for a solid mixture.
Source files
heSolidThermo.H
heSolidThermo.C
Definition at line 49 of file heSolidThermo.H.
Constructor & Destructor Documentation
heSolidThermo (const fvMesh & mesh, const word & phaseName)
Construct from mesh and phase name.
Definition at line 145 of file heSolidThermo.C.
heSolidThermo (const fvMesh & mesh, const dictionary & dict, const word & phaseName)
Construct from mesh, dictionary and phase name.
Definition at line 159 of file heSolidThermo.C.
~heSolidThermo () virtual
Destructor.
Definition at line 174 of file heSolidThermo.C.
Member Function Documentation
TypeName ("heSolidThermo< BasicSolidThermo, MixtureType >")
Runtime type information.
void correct () virtual
Update properties.
Definition at line 181 of file heSolidThermo.C.
References Foam::endl(), Foam::Info, and InfoInFunction.
Foam::tmp< Foam::volVectorField > Kappa () const virtual
Anisotropic thermal conductivity [W/m/K].
Definition at line 199 of file heSolidThermo.C.
References Foam::dimEnergy, Foam::dimLength, Foam::dimTemperature, Foam::dimTime, forAll, mesh, patchi, GeometricField< Type, PatchField, GeoMesh >::ref(), fvMesh::time(), and Time::timeName().
Referenced by heSolidThermo< BasicSolidThermo, MixtureType >::isotropic().
virtual bool isotropic () const inline virtual
Return true if thermal conductivity is isotropic.
Definition at line 102 of file heSolidThermo.H.
References heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), and patchi.
Foam::tmp< Foam::vectorField > Kappa (const label patchi) const virtual
Anisotropic thermal conductivity [W/m/K].
Definition at line 264 of file heSolidThermo.C.
References forAll, patchi, tmp< T >::ref(), List< T >::size(), and vectorField().
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidThermo/solidThermo/heSolidThermo.H
src/thermophysicalModels/solidThermo/solidThermo/heSolidThermo.C