OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
homogeneousMixture< ThermoType > Class Template Reference
Foam::homogeneousMixture.
Public Types
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Public Types inherited from basicCombustionMixture
typedef basicCombustionMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicSpecieMixture
typedef basicSpecieMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Member Functions
homogeneousMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
virtual ~homogeneousMixture ()
Destructor.
const ThermoType & mixture (const scalar) const
const ThermoType & cellMixture (const label celli) const
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
const ThermoType & cellReactants (const label) const
const ThermoType & patchFaceReactants (const label, const label) const
const ThermoType & cellProducts (const label) const
const ThermoType & patchFaceProducts (const label, const label) const
void read (const dictionary &)
Read dictionary.
const ThermoType & getLocalThermo (const label speciei) const
Return thermo based on index.
Public Member Functions inherited from basicCombustionMixture
TypeName ("basicCombustionMixture")
Run time type information.
basicCombustionMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, specie names, mesh and phase name.
virtual ~basicCombustionMixture ()
Destructor.
scalar fres (const scalar ft, const scalar stoicRatio) const
tmp< volScalarField > fres (const volScalarField &ft, const dimensionedScalar &stoicRatio) const
Public Member Functions inherited from basicSpecieMixture
TypeName ("basicSpecieMixture")
Run time type information.
basicSpecieMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicSpecieMixture ()
Destructor.
virtual scalar nMoles (const label speciei) const =0
Number of moles of the given specie [].
virtual scalar W (const label speciei) const =0
Molecular weight of the given specie [kg/kmol].
tmp< volScalarField > W () const
Molecular weight of the mixture [kg/kmol].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar Hc (const label speciei) const =0
Chemical enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
Density [kg/m3].
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
bool contains (const word &specieName) const
Does the mixture include this specie?
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
Table of specie names.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
template<class ThermoType>
class Foam::homogeneousMixture< ThermoType >
Foam::homogeneousMixture.
Source files
homogeneousMixture.H
homogeneousMixture.C
Definition at line 49 of file homogeneousMixture.H.
Member Typedef Documentation
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Definition at line 73 of file homogeneousMixture.H.
Constructor & Destructor Documentation
homogeneousMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, mesh and phase name.
Definition at line 39 of file homogeneousMixture.C.
virtual ~homogeneousMixture () inline virtual
Destructor.
Definition at line 83 of file homogeneousMixture.H.
Member Function Documentation
const ThermoType & mixture (const scalar b) const
Definition at line 64 of file homogeneousMixture.C.
References Foam::constant::physicoChemical::b.
Referenced by homogeneousMixture< ThermoType >::cellMixture(), and homogeneousMixture< ThermoType >::patchFaceMixture().
const ThermoType& cellMixture (const label celli) const inline
Definition at line 91 of file homogeneousMixture.H.
References homogeneousMixture< ThermoType >::mixture().
const ThermoType& patchFaceMixture (const label patchi, const label facei) const inline
Definition at line 97 of file homogeneousMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), homogeneousMixture< ThermoType >::mixture(), and patchi.
const ThermoType& cellReactants (const label) const inline
Definition at line 105 of file homogeneousMixture.H.
const ThermoType& patchFaceReactants (const label , const label) const inline
Definition at line 110 of file homogeneousMixture.H.
const ThermoType& cellProducts (const label) const inline
Definition at line 115 of file homogeneousMixture.H.
const ThermoType& patchFaceProducts (const label , const label) const inline
Definition at line 120 of file homogeneousMixture.H.
void read (const dictionary & thermoDict)
Read dictionary.
Definition at line 87 of file homogeneousMixture.C.
References dictionary::subDict().
const ThermoType & getLocalThermo (const label speciei) const
Return thermo based on index.
Definition at line 96 of file homogeneousMixture.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/homogeneousMixture/homogeneousMixture.H
src/thermophysicalModels/reactionThermo/mixtures/homogeneousMixture/homogeneousMixture.C