OpenFOAM: option::iNew Class Reference
option::iNew Class Reference
Return pointer to new fvOption object created.
Public Member Functions
iNew (const fvMesh &mesh, const word &name)
autoPtr< option > operator() (Istream &is) const
Detailed Description
Return pointer to new fvOption object created.
on the freestore from an Istream
Definition at line 140 of file fvOption.H.
Constructor & Destructor Documentation
iNew (const fvMesh & mesh, const word & name) inline
Definition at line 150 of file fvOption.H.
Referenced by option::clone().
Member Function Documentation
autoPtr<option> operator() (Istream & is) const inline
Definition at line 159 of file fvOption.H.
References option::active(), option::addSup(), Foam::constant::atomic::alpha, option::applyToField(), option::checkApplied(), option::coeffs(), option::constrain(), option::correct(), dict, option::isActive(), option::mesh(), option::name(), option::New(), option::read(), rho, option::setApplied(), option::writeData(), option::writeFooter(), option::writeHeader(), and option::~option().
The documentation for this class was generated from the following file:
src/finiteVolume/cfdTools/general/fvOptions/fvOption.H