OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IncompressibleTurbulenceModel< TransportModel > Class Template Reference
Templated abstract base class for single-phase incompressible turbulence models.
Public Types
typedef geometricOneField alphaField
typedef geometricOneField rhoField
typedef TransportModel transportModel
Public Member Functions
IncompressibleTurbulenceModel (const word &type, const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const TransportModel &transport, const word &propertiesName)
Construct.
virtual ~IncompressibleTurbulenceModel ()
Destructor.
virtual tmp< volSymmTensorField > devReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Static Public Member Functions
static autoPtr< IncompressibleTurbulenceModel > New (const volVectorField &U, const surfaceScalarField &phi, const TransportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Detailed Description
template<class TransportModel>
class Foam::IncompressibleTurbulenceModel< TransportModel >
Templated abstract base class for single-phase incompressible turbulence models.
Source files
IncompressibleTurbulenceModel.H
IncompressibleTurbulenceModel.C
Definition at line 52 of file IncompressibleTurbulenceModel.H.
Member Typedef Documentation
typedef geometricOneField alphaField
Definition at line 65 of file IncompressibleTurbulenceModel.H.
typedef geometricOneField rhoField
Definition at line 66 of file IncompressibleTurbulenceModel.H.
typedef TransportModel transportModel
Definition at line 67 of file IncompressibleTurbulenceModel.H.
Constructor & Destructor Documentation
IncompressibleTurbulenceModel (const word & type, const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const TransportModel & transport, const word & propertiesName)
Construct.
Definition at line 33 of file IncompressibleTurbulenceModel.C.
References IncompressibleTurbulenceModel< TransportModel >::New().
virtual ~IncompressibleTurbulenceModel () inline virtual
Destructor.
Definition at line 99 of file IncompressibleTurbulenceModel.H.
References IncompressibleTurbulenceModel< TransportModel >::devReff(), IncompressibleTurbulenceModel< TransportModel >::devRhoReff(), IncompressibleTurbulenceModel< TransportModel >::divDevReff(), IncompressibleTurbulenceModel< TransportModel >::divDevRhoReff(), rho, and U.
Member Function Documentation
Foam::autoPtr< Foam::IncompressibleTurbulenceModel< TransportModel > > New (const volVectorField & U, const surfaceScalarField & phi, const TransportModel & trasportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Definition at line 68 of file IncompressibleTurbulenceModel.C.
References Foam::New().
Referenced by IncompressibleTurbulenceModel< TransportModel >::IncompressibleTurbulenceModel().
Foam::tmp< Foam::volSymmTensorField > devReff () const virtual
Return the effective stress tensor.
Definition at line 102 of file IncompressibleTurbulenceModel.C.
References IncompressibleTurbulenceModel< TransportModel >::divDevReff().
Referenced by forces::devRhoReff(), turbulenceFields::execute(), and IncompressibleTurbulenceModel< TransportModel >::~IncompressibleTurbulenceModel().
Foam::tmp< Foam::fvVectorMatrix > divDevReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 111 of file IncompressibleTurbulenceModel.C.
References IncompressibleTurbulenceModel< TransportModel >::devRhoReff().
Referenced by IncompressibleTurbulenceModel< TransportModel >::devReff(), and IncompressibleTurbulenceModel< TransportModel >::~IncompressibleTurbulenceModel().
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Return the effective stress tensor.
Definition at line 122 of file IncompressibleTurbulenceModel.C.
References IncompressibleTurbulenceModel< TransportModel >::divDevRhoReff(), and NotImplemented.
Referenced by IncompressibleTurbulenceModel< TransportModel >::divDevReff(), and IncompressibleTurbulenceModel< TransportModel >::~IncompressibleTurbulenceModel().
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 134 of file IncompressibleTurbulenceModel.C.
References NotImplemented.
Referenced by IncompressibleTurbulenceModel< TransportModel >::devRhoReff(), and IncompressibleTurbulenceModel< TransportModel >::~IncompressibleTurbulenceModel().
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (const volScalarField & rho, volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 148 of file IncompressibleTurbulenceModel.C.
References NotImplemented.
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/IncompressibleTurbulenceModel/IncompressibleTurbulenceModel.H
src/TurbulenceModels/incompressible/IncompressibleTurbulenceModel/IncompressibleTurbulenceModel.C