OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallBoundedStreamLineParticle::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< wallBoundedStreamLineParticle > operator() (Istream &is) const
Detailed Description
Factory class to read-construct particles used for.
parallel transfer
Definition at line 197 of file wallBoundedStreamLineParticle.H.
Constructor & Destructor Documentation
iNew (const polyMesh & mesh) inline
Definition at line 203 of file wallBoundedStreamLineParticle.H.
Member Function Documentation
autoPtr<wallBoundedStreamLineParticle> operator() (Istream & is) const inline
Definition at line 209 of file wallBoundedStreamLineParticle.H.
References particle< Type >::mesh_, wallBoundedStreamLineParticle::move(), wallBoundedStreamLineParticle::readFields(), wallBoundedStreamLineParticle::wallBoundedStreamLineParticle(), and wallBoundedStreamLineParticle::writeFields().
The documentation for this class was generated from the following file:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLineParticle.H