OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
indexedOctree< Type > Class Template Reference
Non-pointer based hierarchical recursive searching.
Classes
class node
Tree node. Has up pointer and down pointers.
Public Member Functions
indexedOctree (const Type &shapes)
Construct null.
indexedOctree (const Type &shapes, const List< node > &nodes, const labelListList &contents)
Construct from components.
indexedOctree (const Type &shapes, const treeBoundBox &bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
indexedOctree (const Type &shapes, Istream &is)
Construct from Istream.
autoPtr< indexedOctree< Type > > clone () const
Clone.
const Type & shapes () const
Reference to shape.
const List< node > & nodes () const
List of all nodes.
const labelListList & contents () const
List of all contents (referenced by those nodes that are.
const treeBoundBox & bb () const
Top bounding box.
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
template<class FindNearestOp >
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr, const FindNearestOp &fnOp) const
Calculate nearest point on nearest shape.
template<class FindNearestOp >
void findNearest (const label nodeI, const point &, scalar &nearestDistSqr, label &nearestShapeI, point &nearestPoint, const FindNearestOp &fnOp) const
Low level: calculate nearest starting from subnode.
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
Find nearest to line.
template<class FindNearestOp >
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint, const FindNearestOp &fnOp) const
pointIndexHit findLine (const point &start, const point &end) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point &start, const point &end) const
Find any intersection of line between start and end.
template<class FindIntersectOp >
pointIndexHit findLine (const point &start, const point &end, const FindIntersectOp &fiOp) const
Find nearest intersection of line between start and end.
template<class FindIntersectOp >
pointIndexHit findLineAny (const point &start, const point &end, const FindIntersectOp &fiOp) const
Find any intersection of line between start and end.
labelList findBox (const treeBoundBox &bb) const
Find (in no particular order) indices of all shapes inside or.
labelList findSphere (const point &centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
labelBits findNode (const label nodeI, const point &) const
Find deepest node (as parent+octant) containing point. Starts.
label findInside (const point &) const
Find shape containing point. Only implemented for certain.
const labelList & findIndices (const point &) const
Find the shape indices that occupy the result of findNode.
volumeType getVolumeType (const point &) const
Determine type (inside/outside/mixed) for point. unknown if.
template<class CompareOp >
void findNear (const scalar nearDist, const indexedOctree< Type > &tree2, CompareOp &cop) const
Find near pairs and apply CompareOp to them.
void print (prefixOSstream &, const bool printContents, const label) const
Print tree. Either print all indices (printContent = true) or.
bool write (Ostream &os) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const bool findAny, const point &treeStart, const point &treeEnd, const label startNodeI, const direction startOctant, const FindIntersectOp &fiOp, const bool verbose) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const bool findAny, const point &start, const point &end, const FindIntersectOp &fiOp) const
template<class FindNearestOp >
Foam::pointIndexHit findNearest (const point &sample, const scalar startDistSqr, const FindNearestOp &fnOp) const
template<class FindNearestOp >
Foam::pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint, const FindNearestOp &fnOp) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const point &start, const point &end, const FindIntersectOp &fiOp) const
template<class FindIntersectOp >
Foam::pointIndexHit findLineAny (const point &start, const point &end, const FindIntersectOp &fiOp) const
Static Public Member Functions
static scalar & perturbTol ()
Get the perturbation tolerance.
static bool isContent (const labelBits i)
static bool isEmpty (const labelBits i)
static bool isNode (const labelBits i)
static label getContent (const labelBits i)
static label getNode (const labelBits i)
static direction getOctant (const labelBits i)
static volumeType getSide (const vector &outsideNormal, const vector &vec)
Helper function to return the side. Returns outside if.
static bool overlaps (const point &bbMin, const point &bbMax, const scalar nearestDistSqr, const point &sample)
Helper: does bb intersect a sphere around sample? Or is any.
Friends
Ostream & operator (Ostream &, const indexedOctree< Type > &)
Detailed Description
template<class Type>
class Foam::indexedOctree< Type >
Non-pointer based hierarchical recursive searching.
Source files
indexedOctree.H
indexedOctree.C
Definition at line 47 of file treeDataEdge.H.
Constructor & Destructor Documentation
indexedOctree (const Type & shapes)
Construct null.
Definition at line 2348 of file indexedOctree.C.
indexedOctree (const Type & shapes, const List< node > & nodes, const labelListList & contents)
Construct from components.
Definition at line 2359 of file indexedOctree.C.
indexedOctree (const Type & shapes, const treeBoundBox & bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
Definition at line 2374 of file indexedOctree.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), Foam::divide(), Foam::endl(), forAll, Foam::identity(), Foam::nl, Foam::Pout, DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), List< T >::size(), and memInfo::size().
indexedOctree (const Type & shapes, Istream & is)
Construct from Istream.
Definition at line 2538 of file indexedOctree.C.
Member Function Documentation
Foam::scalar & perturbTol () static
Get the perturbation tolerance.
Definition at line 2553 of file indexedOctree.C.
Referenced by triSurfaceMesh::edgeTree(), triSurfaceSearch::findLine(), triSurfaceSearch::findLineAll(), triSurfaceSearch::findLineAny(), triSurfaceSearch::findNearest(), triSurfaceMesh::getVolumeType(), and triSurfaceSearch::tree().
autoPtr<indexedOctree<Type> > clone () const inline
Clone.
Definition at line 436 of file indexedOctree.H.
const Type& shapes () const inline
Reference to shape.
Definition at line 449 of file indexedOctree.H.
Referenced by polyMesh::findCellFacePt(), patchProbes::findElements(), meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), and surfaceFeatures::nearestEdges().
const List<node>& nodes () const inline
List of all nodes.
Definition at line 455 of file indexedOctree.H.
const labelListList& contents () const inline
List of all contents (referenced by those nodes that are.
contents)
Definition at line 462 of file indexedOctree.H.
const treeBoundBox& bb () const inline
Top bounding box.
Definition at line 468 of file indexedOctree.H.
Referenced by patchProbes::findElements(), indexedOctree< Type >::findNear(), meshSearch::findNearestBoundaryFace(), and surfaceFeatures::nearestSamples().
static bool isContent (const labelBits i) inline static
Definition at line 481 of file indexedOctree.H.
Referenced by indexedOctree< Foam::treeDataFace >::getContent().
static bool isEmpty (const labelBits i) inline static
Definition at line 486 of file indexedOctree.H.
static bool isNode (const labelBits i) inline static
Definition at line 491 of file indexedOctree.H.
Referenced by indexedOctree< Foam::treeDataFace >::getNode().
static label getContent (const labelBits i) inline static
Definition at line 496 of file indexedOctree.H.
static label getNode (const labelBits i) inline static
Definition at line 506 of file indexedOctree.H.
static direction getOctant (const labelBits i) inline static
Definition at line 516 of file indexedOctree.H.
Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Definition at line 2582 of file indexedOctree.C.
pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr, const FindNearestOp & fnOp) const
Calculate nearest point on nearest shape.
Returns
bool : any point found nearer than nearestDistSqr
label: index in shapes
point: actual nearest point found
void findNearest (const label nodeI, const point & sample, scalar & nearestDistSqr, label & nearestShapeI, point & nearestPoint, const FindNearestOp & fnOp) const
Low level: calculate nearest starting from subnode.
Definition at line 516 of file indexedOctree.C.
References indexedOctree< Type >::node::bb_, boundBox::max(), boundBox::min(), treeBoundBox::searchOrder(), and indexedOctree< Type >::node::subNodes_.
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Find nearest to line.
Returns
bool : any point found?
label: index in shapes
point: actual nearest point found sets:
linePoint : corresponding nearest point on line
Definition at line 2631 of file indexedOctree.C.
pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint, const FindNearestOp & fnOp) const
Foam::pointIndexHit findLine (const point & start, const point & end) const
Find nearest intersection of line between start and end.
Definition at line 2684 of file indexedOctree.C.
Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Find any intersection of line between start and end.
Definition at line 2702 of file indexedOctree.C.
Referenced by triSurfaceSearch::findLineAny().
pointIndexHit findLine (const point & start, const point & end, const FindIntersectOp & fiOp) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point & start, const point & end, const FindIntersectOp & fiOp) const
Find any intersection of line between start and end.
Foam::labelList findBox (const treeBoundBox & bb) const
Find (in no particular order) indices of all shapes inside or.
overlapping bounding box (i.e. all shapes not outside box)
Definition at line 2747 of file indexedOctree.C.
Foam::labelList findSphere (const point & centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
overlapping a bounding sphere (i.e. all shapes not outside sphere)
Definition at line 2765 of file indexedOctree.C.
Foam::labelBits findNode (const label nodeI, const point & sample) const
Find deepest node (as parent+octant) containing point. Starts.
off from starting index in nodes_ (use 0 to start from top) Use getNode and getOctant to extract info, or call findIndices.
Definition at line 2785 of file indexedOctree.C.
References Foam::abort(), indexedOctree< Type >::node::bb_, treeBoundBox::contains(), Foam::FatalError, FatalErrorIn, indexedOctree< Type >::node::subNodes_, and treeBoundBox::subOctant().
Foam::label findInside (const point & sample) const
Find shape containing point. Only implemented for certain.
shapes.
Definition at line 2831 of file indexedOctree.C.
References forAll, and indexedOctree< Type >::node::subNodes_.
Referenced by mappedPatchBase::findSamples().
const Foam::labelList & findIndices (const point & sample) const
Find the shape indices that occupy the result of findNode.
Definition at line 2861 of file indexedOctree.C.
References indexedOctree< Type >::node::subNodes_.
Referenced by polyMesh::findCellFacePt().
Foam::volumeType getVolumeType (const point & sample) const
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Definition at line 2886 of file indexedOctree.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, volumeType::INSIDE, volumeType::MIXED, volumeType::OUTSIDE, Foam::Pout, Foam::type(), and volumeType::UNKNOWN.
Foam::volumeType getSide (const vector & outsideNormal, const vector & vec) static
Helper function to return the side. Returns outside if.
outsideNormal&vec >= 0, inside otherwise
Definition at line 490 of file indexedOctree.C.
Referenced by treeDataFace::getVolumeType().
bool overlaps (const point & bbMin, const point & bbMax, const scalar nearestDistSqr, const point & sample) static
Helper: does bb intersect a sphere around sample? Or is any.
corner point of bb closer than nearestDistSqr to sample.
Definition at line 44 of file indexedOctree.C.
References boundBox::overlaps().
void findNear (const scalar nearDist, const indexedOctree< Type > & tree2, CompareOp & cop) const
Find near pairs and apply CompareOp to them.
tree2 can be *this or different tree.
Definition at line 2963 of file indexedOctree.C.
References indexedOctree< Type >::bb().
void print (prefixOSstream & os, const bool printContents, const label nodeI) const
Print tree. Either print all indices (printContent = true) or.
just size of contents nodes.
Definition at line 2987 of file indexedOctree.C.
References indexedOctree< Type >::node::bb_, Foam::endl(), forAll, Foam::nl, indexedOctree< Type >::node::parent_, prefixOSstream::prefix(), List< T >::size(), treeBoundBox::subBbox(), indexedOctree< Type >::node::subNodes_, and Foam::meshTools::writeOBJ().
bool write (Ostream & os) const
Definition at line 3060 of file indexedOctree.C.
References IOstream::good().
Foam::pointIndexHit findLine (const bool findAny, const point & treeStart, const point & treeEnd, const label startNodeI, const direction startOctant, const FindIntersectOp & fiOp, const bool verbose) const
Definition at line 1731 of file indexedOctree.C.
References Foam::abort(), Foam::endl(), treeBoundBox::faceBits(), Foam::FatalError, FatalErrorIn, PointIndexHit< Point >::hit(), Foam::nl, Foam::Pout, PointIndexHit< Point >::rawPoint(), and WarningIn.
Foam::pointIndexHit findLine (const bool findAny, const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 1924 of file indexedOctree.C.
References treeBoundBox::intersects(), and treeBoundBox::posBits().
Foam::pointIndexHit findNearest (const point & sample, const scalar startDistSqr, const FindNearestOp & fnOp) const
Definition at line 2599 of file indexedOctree.C.
References Vector< scalar >::zero.
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint, const FindNearestOp & fnOp) const
Definition at line 2650 of file indexedOctree.C.
References Vector< scalar >::zero.
Foam::pointIndexHit findLine (const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 2721 of file indexedOctree.C.
Foam::pointIndexHit findLineAny (const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 2735 of file indexedOctree.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const indexedOctree< Type > &) friend
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataEdge.H
src/OpenFOAM/algorithms/indexedOctree/indexedOctree.H
src/OpenFOAM/algorithms/indexedOctree/indexedOctree.C