OpenFOAM-dev: hierarchGeomDecomp Class Reference 2
hierarchGeomDecomp Class Reference
Does hierarchical decomposition of points. Works by first sorting the points in x direction into equal sized bins, then in y direction and finally in z direction.
Public Member Functions
TypeName ("hierarchical")
Runtime type information.
hierarchGeomDecomp (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~hierarchGeomDecomp ()
Destructor.
virtual bool parallelAware () const
Hierarchgeom is aware of processor boundaries.
virtual labelList decompose (const pointField &, const scalarField &weights)
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &)
Without weights. Code for weighted decomposition is a bit complex.
virtual labelList decompose (const polyMesh &mesh, const pointField &cc, const scalarField &cWeights)
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const polyMesh &mesh, const pointField &cc)
Without weights. Code for weighted decomposition is a bit complex.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)
Return for every coordinate the wanted processor number. Explicitly.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
Public Member Functions inherited from geomDecomp
geomDecomp (const dictionary &decompositionDict, const word &derivedType)
Construct given the decomposition dictionary.
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp)
Helper: apply constraints to a decomposition. This gives.
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Helper: determine (local or global) cellCells and face weights.
Protected Attributes inherited from geomDecomp
const dictionary & geomDecomDict_
Vector< label > n_
scalar delta_
tensor rotDelta_
Protected Attributes inherited from decompositionMethod
const dictionary & decompositionDict_
label nProcessors_
PtrList< decompositionConstraint > constraints_
Optional constraints.
Detailed Description
Does hierarchical decomposition of points. Works by first sorting the points in x direction into equal sized bins, then in y direction and finally in z direction.
Uses single array to hold decomposition which is indexed as if it is a 3 dimensional array:
finalDecomp[i,j,k] is indexed as
i*n[0]*n[1] + j*n[1] + k
E.g. if we're sorting 'xyz': the first sort (over the x-component) determines in which x-domain the point goes. Then for each of the x-domains the points are sorted in y direction and each individual x-domain gets split into three y-domains. And similar for the z-direction.
Since the domains are of equal size the maximum difference in size is n[0]*n[1] (or n[1]*n[2]?) (small anyway)
Source files
hierarchGeomDecomp.H
hierarchGeomDecomp.C
Definition at line 66 of file hierarchGeomDecomp.H.
Constructor & Destructor Documentation
hierarchGeomDecomp (const dictionary & decompositionDict)
Construct given the decomposition dictionary.
Definition at line 762 of file hierarchGeomDecomp.C.
virtual ~hierarchGeomDecomp () inline virtual
Destructor.
Definition at line 174 of file hierarchGeomDecomp.H.
Member Function Documentation
TypeName ("hierarchical")
Runtime type information.
virtual bool parallelAware () const inline virtual
Hierarchgeom is aware of processor boundaries.
Implements decompositionMethod.
Definition at line 181 of file hierarchGeomDecomp.H.
References hierarchGeomDecomp::decompose().
Foam::labelList decompose (const pointField & points, const scalarField & weights) virtual
Return for every coordinate the wanted processor number.
Implements geomDecomp.
Definition at line 718 of file hierarchGeomDecomp.C.
References Foam::e, forAll, Foam::max(), Foam::reduce(), and List< T >::size().
Referenced by hierarchGeomDecomp::decompose(), and hierarchGeomDecomp::parallelAware().
Foam::labelList decompose (const pointField & points) virtual
Without weights. Code for weighted decomposition is a bit complex.
so kept separate for now.
Implements geomDecomp.
Definition at line 678 of file hierarchGeomDecomp.C.
References hierarchGeomDecomp::decompose(), Foam::e, forAll, Foam::max(), Foam::reduce(), and List< T >::size().
virtual labelList decompose (const polyMesh & mesh, const pointField & cc, const scalarField & cWeights) inline virtual
Return for every coordinate the wanted processor number. Use the.
mesh connectivity (if needed)
Implements decompositionMethod.
Definition at line 201 of file hierarchGeomDecomp.H.
References hierarchGeomDecomp::decompose().
virtual labelList decompose (const polyMesh & mesh, const pointField & cc) inline virtual
Without weights. Code for weighted decomposition is a bit complex.
so kept separate for now.
Reimplemented from decompositionMethod.
Definition at line 212 of file hierarchGeomDecomp.H.
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) inline virtual
Return for every coordinate the wanted processor number. Explicitly.
provided connectivity - does not use mesh_. The connectivity is equal to mesh.cellCells() except for
in parallel the cell numbers are global cell numbers (starting from 0 at processor0 and then incrementing all through the processors)
the connections are across coupled patches
Implements decompositionMethod.
Definition at line 225 of file hierarchGeomDecomp.H.
References hierarchGeomDecomp::decompose().
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc) inline virtual
Like decompose but with uniform weights on the cells.
Reimplemented from decompositionMethod.
Definition at line 235 of file hierarchGeomDecomp.H.
References hierarchGeomDecomp::decompose().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/hierarchGeomDecomp/hierarchGeomDecomp.H
src/parallel/decompose/decompositionMethods/hierarchGeomDecomp/hierarchGeomDecomp.C