OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
incompressiblePerfectGas< Specie > Class Template Reference
Incompressible gas equation of state using a constant reference pressure in the perfect gas equation of state rather than the local pressure so that the density only varies with temperature and composition.
Public Member Functions
incompressiblePerfectGas (const Specie &sp, const scalar pRef)
Construct from components.
incompressiblePerfectGas (const incompressiblePerfectGas &sp)
Construct from incompressiblePerfectGas.
incompressiblePerfectGas (Istream &)
Construct from Istream.
incompressiblePerfectGas (const dictionary &dict)
Construct from dictionary.
incompressiblePerfectGas (const word &name, const incompressiblePerfectGas &)
Construct as named copy.
autoPtr< incompressiblePerfectGas > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar s (const scalar p, const scalar T) const
Return entropy [J/(kmol K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
incompressiblePerfectGas & operator= (const incompressiblePerfectGas &)
void operator+= (const incompressiblePerfectGas &)
void operator-= (const incompressiblePerfectGas &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr
< incompressiblePerfectGas > New (Istream &is)
static autoPtr
< incompressiblePerfectGas > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = true
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
incompressiblePerfectGas operator+ (const incompressiblePerfectGas &, const incompressiblePerfectGas &)
incompressiblePerfectGas operator- (const incompressiblePerfectGas &, const incompressiblePerfectGas &)
incompressiblePerfectGas operator* (const scalar s, const incompressiblePerfectGas &)
incompressiblePerfectGas operator== (const incompressiblePerfectGas &, const incompressiblePerfectGas &)
Ostream & operator (Ostream &, const incompressiblePerfectGas &)
Detailed Description
template<class Specie>
class Foam::incompressiblePerfectGas< Specie >
Incompressible gas equation of state using a constant reference pressure in the perfect gas equation of state rather than the local pressure so that the density only varies with temperature and composition.
Source files
incompressiblePerfectGas.H
incompressiblePerfectGasI.H
incompressiblePerfectGas.C
Definition at line 49 of file incompressiblePerfectGas.H.
Constructor & Destructor Documentation
incompressiblePerfectGas (const Specie & sp, const scalar pRef) inline
Construct from components.
Definition at line 33 of file incompressiblePerfectGasI.H.
incompressiblePerfectGas (const incompressiblePerfectGas< Specie > & sp) inline
Construct from incompressiblePerfectGas.
Definition at line 44 of file incompressiblePerfectGasI.H.
incompressiblePerfectGas (Istream & is)
Construct from Istream.
Definition at line 32 of file incompressiblePerfectGas.C.
References IOstream::check().
incompressiblePerfectGas (const dictionary & dict)
Construct from dictionary.
Definition at line 47 of file incompressiblePerfectGas.C.
incompressiblePerfectGas (const word & name, const incompressiblePerfectGas< Specie > &) inline
Construct as named copy.
Member Function Documentation
Foam::autoPtr< Foam::incompressiblePerfectGas< Specie > > clone () const inline
Construct and return a clone.
Definition at line 67 of file incompressiblePerfectGasI.H.
Foam::autoPtr< Foam::incompressiblePerfectGas< Specie > > New (Istream & is) inline static
Definition at line 79 of file incompressiblePerfectGasI.H.
Foam::autoPtr< Foam::incompressiblePerfectGas< Specie > > New (const dictionary & dict) inline static
Definition at line 93 of file incompressiblePerfectGasI.H.
References dict.
static word typeName () inline static
Return the instantiated type name.
Definition at line 141 of file incompressiblePerfectGas.H.
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 108 of file incompressiblePerfectGasI.H.
References R, and Foam::T().
Foam::scalar s (const scalar p, const scalar T) const inline
Return entropy [J/(kmol K)].
Definition at line 119 of file incompressiblePerfectGasI.H.
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 130 of file incompressiblePerfectGasI.H.
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 141 of file incompressiblePerfectGasI.H.
Foam::scalar cpMcv (scalar p, scalar T) const inline
Return (cp - cv) [J/(kmol K].
Definition at line 152 of file incompressiblePerfectGasI.H.
References Foam::constant::thermodynamic::RR.
void write (Ostream & os) const
Write to Ostream.
Definition at line 59 of file incompressiblePerfectGas.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), and write().
Foam::incompressiblePerfectGas< Specie > & operator= (const incompressiblePerfectGas< Specie > &) inline
Definition at line 166 of file incompressiblePerfectGasI.H.
void operator+= (const incompressiblePerfectGas< Specie > &) inline
Definition at line 179 of file incompressiblePerfectGasI.H.
void operator-= (const incompressiblePerfectGas< Specie > &) inline
Definition at line 194 of file incompressiblePerfectGasI.H.
void operator*= (const scalar s) inline
Definition at line 204 of file incompressiblePerfectGasI.H.
Friends And Related Function Documentation
incompressiblePerfectGas operator+ (const incompressiblePerfectGas< Specie > & , const incompressiblePerfectGas< Specie > &) friend
incompressiblePerfectGas operator- (const incompressiblePerfectGas< Specie > & , const incompressiblePerfectGas< Specie > &) friend
incompressiblePerfectGas operator* (const scalar s, const incompressiblePerfectGas< Specie > &) friend
incompressiblePerfectGas operator== (const incompressiblePerfectGas< Specie > & , const incompressiblePerfectGas< Specie > &) friend
Ostream& operator (Ostream & , const incompressiblePerfectGas< Specie > &) friend
Member Data Documentation
const bool incompressible = true static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 152 of file incompressiblePerfectGas.H.
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 155 of file incompressiblePerfectGas.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/incompressiblePerfectGas/incompressiblePerfectGas.H
src/thermophysicalModels/specie/equationOfState/incompressiblePerfectGas/incompressiblePerfectGas.C
src/thermophysicalModels/specie/equationOfState/incompressiblePerfectGas/incompressiblePerfectGasI.H