OpenFOAM: streamLineParticle::iNew Class Reference
streamLineParticle::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< streamLineParticle > operator() (Istream &is) const
Detailed Description
Factory class to read-construct particles used for.
parallel transfer
Definition at line 199 of file streamLineParticle.H.
Constructor & Destructor Documentation
iNew (const polyMesh & mesh) inline
Definition at line 205 of file streamLineParticle.H.
Member Function Documentation
autoPtr<streamLineParticle> operator() (Istream & is) const inline
Definition at line 210 of file streamLineParticle.H.
References streamLineParticle::hitCyclicPatch(), streamLineParticle::hitPatch(), streamLineParticle::hitProcessorPatch(), streamLineParticle::hitSymmetryPatch(), streamLineParticle::hitSymmetryPlanePatch(), streamLineParticle::hitWallPatch(), streamLineParticle::hitWedgePatch(), streamLineParticle::move(), streamLineParticle::operator<<, patchi, streamLineParticle::readFields(), streamLineParticle::streamLineParticle(), and streamLineParticle::writeFields().
The documentation for this class was generated from the following file:
src/functionObjects/field/streamLine/streamLineParticle.H