OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
hRefConstThermo< EquationOfState > Class Template Reference
Constant properties thermodynamics package templated into the EquationOfState.
Public Member Functions
hRefConstThermo (Istream &)
Construct from Istream.
hRefConstThermo (const dictionary &dict)
Construct from dictionary.
hRefConstThermo (const word &, const hRefConstThermo &)
Construct as named copy.
autoPtr< hRefConstThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kmol K)].
scalar ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kmol].
scalar hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kmol].
scalar hc () const
Chemical enthalpy [J/kmol].
scalar s (const scalar p, const scalar T) const
Entropy [J/(kmol K)].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const hRefConstThermo &)
void operator-= (const hRefConstThermo &)
Static Public Member Functions
static autoPtr< hRefConstThermo > New (Istream &is)
Selector from Istream.
static autoPtr< hRefConstThermo > New (const dictionary &dict)
Selector from dictionary.
static word typeName ()
Return the instantiated type name.
Friends
hRefConstThermo operator+ (const hRefConstThermo &, const hRefConstThermo &)
hRefConstThermo operator- (const hRefConstThermo &, const hRefConstThermo &)
hRefConstThermo operator* (const scalar, const hRefConstThermo &)
hRefConstThermo operator== (const hRefConstThermo &, const hRefConstThermo &)
Ostream & operator (Ostream &, const hRefConstThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hRefConstThermo< EquationOfState >
Constant properties thermodynamics package templated into the EquationOfState.
Source files
hRefConstThermo.H
hRefConstThermoI.H
hRefConstThermo.C
Definition at line 46 of file hRefConstThermo.H.
Constructor & Destructor Documentation
hRefConstThermo (Istream & is)
Construct from Istream.
Definition at line 32 of file hRefConstThermo.C.
References IOstream::check().
hRefConstThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 49 of file hRefConstThermo.C.
hRefConstThermo (const word & name, const hRefConstThermo< EquationOfState > & ct) inline
Construct as named copy.
Definition at line 50 of file hRefConstThermoI.H.
Member Function Documentation
Foam::autoPtr< Foam::hRefConstThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 65 of file hRefConstThermoI.H.
Foam::autoPtr< Foam::hRefConstThermo< EquationOfState > > New (Istream & is) inline static
Selector from Istream.
Definition at line 76 of file hRefConstThermoI.H.
Foam::autoPtr< Foam::hRefConstThermo< EquationOfState > > New (const dictionary & dict) inline static
Selector from dictionary.
Definition at line 87 of file hRefConstThermoI.H.
References dict, and hRefConstThermo< EquationOfState >::limit().
static word typeName () inline static
Return the instantiated type name.
Definition at line 140 of file hRefConstThermo.H.
References hRefConstThermo< EquationOfState >::cp(), hRefConstThermo< EquationOfState >::ha(), hRefConstThermo< EquationOfState >::hc(), hRefConstThermo< EquationOfState >::hs(), hRefConstThermo< EquationOfState >::limit(), hRefConstThermo< EquationOfState >::operator+=(), hRefConstThermo< EquationOfState >::operator-=(), p, hRefConstThermo< EquationOfState >::s(), Foam::T(), and hRefConstThermo< EquationOfState >::write().
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 100 of file hRefConstThermoI.H.
References hRefConstThermo< EquationOfState >::cp(), and Foam::T().
Referenced by hRefConstThermo< EquationOfState >::New(), and hRefConstThermo< EquationOfState >::typeName().
Foam::scalar cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kmol K)].
Definition at line 110 of file hRefConstThermoI.H.
References cp, and hRefConstThermo< EquationOfState >::ha().
Referenced by hRefConstThermo< EquationOfState >::limit(), and hRefConstThermo< EquationOfState >::typeName().
Foam::scalar ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kmol].
Definition at line 121 of file hRefConstThermoI.H.
References Foam::constant::universal::h, and hRefConstThermo< EquationOfState >::hs().
Referenced by hRefConstThermo< EquationOfState >::cp(), and hRefConstThermo< EquationOfState >::typeName().
Foam::scalar hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kmol].
Definition at line 131 of file hRefConstThermoI.H.
References Foam::constant::universal::h.
Referenced by hRefConstThermo< EquationOfState >::ha(), and hRefConstThermo< EquationOfState >::typeName().
Foam::scalar hc () const inline
Chemical enthalpy [J/kmol].
Definition at line 140 of file hRefConstThermoI.H.
References hRefConstThermo< EquationOfState >::s().
Referenced by hRefConstThermo< EquationOfState >::typeName().
Foam::scalar s (const scalar p, const scalar T) const inline
Entropy [J/(kmol K)].
Definition at line 148 of file hRefConstThermoI.H.
References Foam::log(), s(), and Foam::constant::standard::Tstd.
Referenced by hRefConstThermo< EquationOfState >::hc(), hRefConstThermo< EquationOfState >::operator-=(), and hRefConstThermo< EquationOfState >::typeName().
void write (Ostream & os) const
Write to Ostream.
Definition at line 66 of file hRefConstThermo.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), Foam::tab, and write().
Referenced by hRefConstThermo< EquationOfState >::typeName().
void operator+= (const hRefConstThermo< EquationOfState > &) inline
Definition at line 160 of file hRefConstThermoI.H.
Referenced by hRefConstThermo< EquationOfState >::typeName().
void operator-= (const hRefConstThermo< EquationOfState > &) inline
Definition at line 178 of file hRefConstThermoI.H.
References hRefConstThermo< EquationOfState >::s().
Referenced by hRefConstThermo< EquationOfState >::typeName().
Friends And Related Function Documentation
hRefConstThermo operator+ (const hRefConstThermo< EquationOfState > & , const hRefConstThermo< EquationOfState > &) friend
hRefConstThermo operator- (const hRefConstThermo< EquationOfState > & , const hRefConstThermo< EquationOfState > &) friend
hRefConstThermo operator* (const scalar , const hRefConstThermo< EquationOfState > &) friend
hRefConstThermo operator== (const hRefConstThermo< EquationOfState > & , const hRefConstThermo< EquationOfState > &) friend
Ostream& operator (Ostream & , const hRefConstThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hRefConst/hRefConstThermo.H
src/thermophysicalModels/specie/thermo/hRefConst/hRefConstThermo.C
src/thermophysicalModels/specie/thermo/hRefConst/hRefConstThermoI.H