OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
histogram Class Reference
Function objects » Field function objects
Write the volume-weighted histogram of a volScalarField.
Public Member Functions
TypeName ("histogram")
Runtime type information.
histogram (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~histogram ()
virtual const word & name () const
Return name of the set of histogram.
virtual void read (const dictionary &)
Read the histogram data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the histogram and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
virtual ~functionObjectFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Member Functions
static bool viable (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Return true if the construction of this functionObject is viable.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void writeFileHeader (const label i=0)
File header information.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes inherited from functionObjectFile
const objectRegistry & obr_
Reference to the objectRegistry.
const word prefix_
Prefix.
Detailed Description
Write the volume-weighted histogram of a volScalarField.
Example:
histogram1
{
    type            histogram;
    functionObjectLibs ("libfieldFunctionObjects.so");
    field           p;
    nBins           100;
    min             -5;
    max             5;
    setFormat       gnuplot;
}
Function object usage
Property Description Required Default value
type type name: histogram yes
field Field to analyse yes
nBins Number of bins for the histogram yes
max Maximum value sampled yes
min minimum value sampled no 0
setFormat Output format yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
histogram.H
histogram.C
Definition at line 127 of file histogram.H.
Constructor & Destructor Documentation
histogram (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 70 of file histogram.C.
References Foam::read(), and histogram::viable().
~histogram () virtual
Definition at line 99 of file histogram.C.
Member Function Documentation
TypeName ("histogram")
Runtime type information.
bool viable (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false) static
Return true if the construction of this functionObject is viable.
i.e. the prerequisites for construction are available
Definition at line 85 of file histogram.C.
Referenced by histogram::histogram().
virtual const word& name () const inline virtual
Return name of the set of histogram.
Definition at line 205 of file histogram.H.
References histogram::end(), histogram::execute(), histogram::read(), histogram::timeSet(), and histogram::write().
void read (const dictionary & dict) virtual
Read the histogram data.
Definition at line 105 of file histogram.C.
References format(), dictionary::lookup(), dictionary::lookupOrDefault(), and writer< Type >::New().
Referenced by histogram::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 117 of file histogram.C.
Referenced by histogram::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 121 of file histogram.C.
Referenced by histogram::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 125 of file histogram.C.
Referenced by histogram::name().
void write () virtual
Calculate the histogram and write.
Definition at line 129 of file histogram.C.
References delta, Foam::endl(), forAll, Foam::Info, Pstream::listCombineGather(), Foam::mag(), UPstream::master(), mesh, IOobject::MUST_READ, IOobject::name(), Foam::nl, IOobject::NO_WRITE, Foam::sum(), fvMesh::time(), Time::timeName(), Foam::type(), fvMesh::V(), and x.
Referenced by histogram::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 226 of file histogram.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 230 of file histogram.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/histogram/histogram.H
src/postProcessing/functionObjects/field/histogram/histogram.C