OpenFOAM: histogram Class Reference
histogram Class Reference
FunctionObjects » Field function objects
Write the volume-weighted histogram of a volScalarField.
Public Member Functions
TypeName ("histogram")
Runtime type information.
histogram (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~histogram ()
virtual bool read (const dictionary &)
Read the histogram data.
virtual bool execute ()
Execute, currently does nothing.
virtual bool write ()
Calculate the histogram and write.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Detailed Description
Write the volume-weighted histogram of a volScalarField.
Example:
histogram1
{
    type            histogram;
    libs            ("libfieldFunctionObjects.so");
    field           p;
    nBins           100;
    min             -5;
    max             5;
    setFormat       gnuplot;
}
Usage
Property Description Required Default value
type type name: histogram yes
field Field to analyse yes
nBins Number of bins for the histogram yes
max Maximum value sampled yes
min minimum value sampled no 0
setFormat Output format yes
See also
Foam::functionObject Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::writeFile
Source files
histogram.H
histogram.C
Definition at line 122 of file histogram.H.
Constructor & Destructor Documentation
histogram (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 72 of file histogram.C.
References Foam::read().
~histogram () virtual
Definition at line 87 of file histogram.C.
Member Function Documentation
TypeName ("histogram")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the histogram data.
Reimplemented from regionFunctionObject.
Definition at line 93 of file histogram.C.
References format(), dictionary::lookup(), dictionary::lookupOrDefault(), and writer< Type >::New().
bool execute () virtual
Execute, currently does nothing.
Implements functionObject.
Definition at line 107 of file histogram.C.
bool write () virtual
Calculate the histogram and write.
postProcess overrides the usual writeControl behaviour and forces writing always (used in post-processing mode)
Implements functionObject.
Definition at line 113 of file histogram.C.
References delta, Foam::endl(), forAll, Pstream::listCombineGather(), Log, Foam::mag(), UPstream::master(), IOobject::MUST_READ, Foam::name(), IOobject::name(), Foam::nl, IOobject::NO_WRITE, autoPtr< T >::reset(), Foam::sum(), Foam::type(), autoPtr< T >::valid(), and x.
The documentation for this class was generated from the following files:
src/functionObjects/field/histogram/histogram.H
src/functionObjects/field/histogram/histogram.C