OpenFOAM: HeatTransferModel< CloudType > Class Template Reference
HeatTransferModel< CloudType > Class Template Reference abstract
Templated heat transfer model class.
Public Member Functions
TypeName ("heatTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, HeatTransferModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
HeatTransferModel (CloudType &owner)
Construct null from owner.
HeatTransferModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
HeatTransferModel (const HeatTransferModel< CloudType > &htm)
Construct copy.
virtual autoPtr< HeatTransferModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~HeatTransferModel ()
Destructor.
const Switch & BirdCorrection () const
Return the Bird htc correction flag.
virtual scalar Nu (const scalar Re, const scalar Pr) const =0
Nusselt number.
virtual scalar htc (const scalar dp, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW) const
Return heat transfer coefficient.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< HeatTransferModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::HeatTransferModel< CloudType >
Templated heat transfer model class.
Source files
HeatTransferModel.H
HeatTransferModel.C
HeatTransferModelNew.C
Definition at line 53 of file ThermoCloud.H.
Constructor & Destructor Documentation
HeatTransferModel (CloudType & owner)
Construct null from owner.
Definition at line 31 of file HeatTransferModel.C.
Referenced by HeatTransferModel< CloudType >::HeatTransferModel().
HeatTransferModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from dictionary.
Definition at line 40 of file HeatTransferModel.C.
References HeatTransferModel< CloudType >::HeatTransferModel().
HeatTransferModel (const HeatTransferModel< CloudType > & htm)
Construct copy.
Definition at line 53 of file HeatTransferModel.C.
~HeatTransferModel () virtual
Destructor.
Definition at line 65 of file HeatTransferModel.C.
Member Function Documentation
TypeName ("heatTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , HeatTransferModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
virtual autoPtr<HeatTransferModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in RanzMarshall< CloudType >, and NoHeatTransfer< CloudType >.
Foam::autoPtr< Foam::HeatTransferModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file HeatTransferModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
const Foam::Switch & BirdCorrection () const
Return the Bird htc correction flag.
Definition at line 72 of file HeatTransferModel.C.
References HeatTransferModel< CloudType >::htc().
virtual scalar Nu (const scalar Re, const scalar Pr) const pure virtual
Nusselt number.
Implemented in NoHeatTransfer< CloudType >, and RanzMarshall< CloudType >.
Referenced by HeatTransferModel< CloudType >::htc().
Foam::scalar htc (const scalar dp, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW) const virtual
Return heat transfer coefficient.
Definition at line 80 of file HeatTransferModel.C.
References Foam::exp(), Foam::mag(), Foam::min(), and HeatTransferModel< CloudType >::Nu().
Referenced by HeatTransferModel< CloudType >::BirdCorrection().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/ThermoCloud/ThermoCloud.H
src/lagrangian/intermediate/submodels/Thermodynamic/HeatTransferModel/HeatTransferModel/HeatTransferModel.H
src/lagrangian/intermediate/submodels/Thermodynamic/HeatTransferModel/HeatTransferModel/HeatTransferModel.C
src/lagrangian/intermediate/submodels/Thermodynamic/HeatTransferModel/HeatTransferModel/HeatTransferModelNew.C