OpenFOAM: icoUncoupledKinematicCloud Class Reference
icoUncoupledKinematicCloud Class Reference
FunctionObjects » Lagrangian function objects
This functionObject tracks a uncoupled kinematic particle cloud in the specified velocity field of an incompressible flow (laminar, RANS or LES).
Public Member Functions
TypeName ("icoUncoupledKinematicCloud")
Runtime type information.
icoUncoupledKinematicCloud (const word &name, const Time &runTime, const dictionary &dict)
Construct for given objectRegistry and dictionary.
virtual ~icoUncoupledKinematicCloud ()
Destructor.
virtual bool read (const dictionary &)
Read the controls.
virtual bool execute ()
Track the cloud.
virtual bool write ()
Write the cloud.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Detailed Description
This functionObject tracks a uncoupled kinematic particle cloud in the specified velocity field of an incompressible flow (laminar, RANS or LES).
It may be used in conjunction with any transient single-phase incompressible flow solver such as pisoFoam or pimpleFoam and tracks the particles or parcels without affecting the the flow-field.
The kinematicCloud requires the the density of the fluid which is looked-up from constant/transportProperties dictionary and the acceleration due to gravity which is read from the constant/g file if present or defaults to zero.
The kinematicCloud properties are read from the constant/kinematicCloudProperties dictionary in the usual manner.
Example of function object specification:
    tracks
    {
        libs        ("liblagrangianFunctionObjects.so");
        type        icoUncoupledKinematicCloud;
    }
Usage
Property Description Required Default value
type Type name: icoUncoupledKinematicCloud yes
U Name of the velocity field no U
kinematicCloud Name of the kinematicCloud no kinematicCloud
See also
Foam::functionObjects::fvMeshFunctionObject
Source files
icoUncoupledKinematicCloud.H
icoUncoupledKinematicCloud.C
Definition at line 112 of file icoUncoupledKinematicCloud.H.
Constructor & Destructor Documentation
icoUncoupledKinematicCloud (const word & name, const Time & runTime, const dictionary & dict)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 50 of file icoUncoupledKinematicCloud.C.
~icoUncoupledKinematicCloud () virtual
Destructor.
Definition at line 112 of file icoUncoupledKinematicCloud.C.
References icoUncoupledKinematicCloud::read().
Member Function Documentation
TypeName ("icoUncoupledKinematicCloud")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the controls.
Reimplemented from regionFunctionObject.
Definition at line 119 of file icoUncoupledKinematicCloud.C.
References regionFunctionObject::read().
Referenced by icoUncoupledKinematicCloud::~icoUncoupledKinematicCloud().
bool execute () virtual
Track the cloud.
Implements functionObject.
Definition at line 129 of file icoUncoupledKinematicCloud.C.
bool write () virtual
Write the cloud.
Implements functionObject.
Definition at line 138 of file icoUncoupledKinematicCloud.C.
The documentation for this class was generated from the following files:
src/functionObjects/lagrangian/icoUncoupledKinematicCloud/icoUncoupledKinematicCloud.H
src/functionObjects/lagrangian/icoUncoupledKinematicCloud/icoUncoupledKinematicCloud.C