OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ifEqEqOp< value > Class Template Reference
Reduction class. If x and y are not equal assign value.
Public Member Functions
void operator() (label &x, const label y) const
Detailed Description
template<label value>
class Foam::ifEqEqOp< value >
Reduction class. If x and y are not equal assign value.
Definition at line 55 of file hexRef8.C.
Member Function Documentation
void operator() (label & x, const label y) const inline
Definition at line 58 of file hexRef8.C.
References Foam::abort(), Foam::e, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), Foam::findIndex(), faceZone::flipMap(), forAll, Foam::gMax(), HashTable< T, Key, Hash >::insert(), Foam::labelMax, Foam::labelMin, Pstream::listCombineGather(), Pstream::listCombineScatter(), Foam::magSqr(), Foam::max(), Foam::min(), OSstream::name(), Foam::name(), Foam::nl, Foam::Perr, Foam::Pout, UList< T >::rcIndex(), face::reverseFace(), polyTopoChange::setAction(), Foam::sqr(), Foam::sqrt(), syncTools::syncEdgeList(), List< T >::transfer(), edge::vec(), faceZone::whichFace(), Foam::meshTools::writeOBJ(), and y.
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8.C