OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ReactingMultiphaseParcel< ParcelType >::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< ReactingMultiphaseParcel< ParcelType > > operator() (Istream &is) const
Detailed Description
template<class ParcelType>
class Foam::ReactingMultiphaseParcel< ParcelType >::iNew
Factory class to read-construct particles used for.
parallel transfer
Definition at line 339 of file ReactingMultiphaseParcel.H.
Constructor & Destructor Documentation
iNew (const polyMesh & mesh) inline
Definition at line 345 of file ReactingMultiphaseParcel.H.
References ReactingMultiphaseParcel< ParcelType >::operator.
Member Function Documentation
autoPtr<ReactingMultiphaseParcel<ParcelType> > operator() (Istream & is) const inline
Definition at line 351 of file ReactingMultiphaseParcel.H.
References Foam::constant::universal::c, ReactingMultiphaseParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::canCombust(), ReactingMultiphaseParcel< ParcelType >::cellValueSourceCorrection(), ReactingMultiphaseParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::setCellValues(), ReactingMultiphaseParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::YGas(), ReactingMultiphaseParcel< ParcelType >::YLiquid(), and ReactingMultiphaseParcel< ParcelType >::YSolid().
The documentation for this class was generated from the following file:
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcel.H