OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
inverseVolumeDiffusivity Class Reference
Inverse cell-volume motion diffusivity.
Public Member Functions
TypeName ("inverseVolume")
Runtime type information.
inverseVolumeDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~inverseVolumeDiffusivity ()
Destructor.
virtual void correct ()
Correct the motion diffusivity.
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
Runtime type information.
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~uniformDiffusivity ()
Destructor.
virtual tmp< surfaceScalarField > operator() () const
Return diffusivity field.
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
Construct for the given fvMesh.
virtual ~motionDiffusivity ()
Destructor.
const fvMesh & mesh () const
Return reference to the mesh.
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Select null constructed.
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
Inverse cell-volume motion diffusivity.
Source files
inverseVolumeDiffusivity.H
inverseVolumeDiffusivity.C
Definition at line 48 of file inverseVolumeDiffusivity.H.
Constructor & Destructor Documentation
inverseVolumeDiffusivity (const fvMesh & mesh, Istream & mdData)
Construct for the given fvMesh and data Istream.
Definition at line 51 of file inverseVolumeDiffusivity.C.
References correct.
~inverseVolumeDiffusivity () virtual
Destructor.
Definition at line 64 of file inverseVolumeDiffusivity.C.
Member Function Documentation
TypeName ("inverseVolume")
Runtime type information.
void correct () virtual
Correct the motion diffusivity.
Reimplemented from uniformDiffusivity.
Definition at line 70 of file inverseVolumeDiffusivity.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dimless, GeometricField< Type, PatchField, GeoMesh >::internalField(), Foam::fvc::interpolate(), mesh, IOobject::NO_READ, IOobject::NO_WRITE, timeName, and fvMesh::V().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/inverseVolume/inverseVolumeDiffusivity.H
src/fvMotionSolver/motionDiffusivity/inverseVolume/inverseVolumeDiffusivity.C