OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
interpolation2DTable< Type > Class Template Reference
2D table interpolation. The data must be in ascending order in both dimensions x and y.
Public Types
enum boundsHandling { ERROR, WARN, CLAMP }
Enumeration for handling out-of-bound values.
typedef List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > table
Cconvenience typedef.
Public Types inherited from List< Tuple2< scalar, List< Tuple2< scalar, Type > > > >
typedef SubList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
interpolation2DTable ()
Construct null.
interpolation2DTable (const List< Tuple2< scalar, List< Tuple2< scalar, Type >>>> &values, const boundsHandling bounds, const fileName &fName)
Construct from components.
interpolation2DTable (const fileName &fName)
Construct given the name of the file containing the table of data.
interpolation2DTable (const dictionary &dict)
Construct by reading the fileName and boundsHandling from dictionary.
interpolation2DTable (const interpolation2DTable &interpTable)
Construct copy.
word boundsHandlingToWord (const boundsHandling &bound) const
Return the out-of-bounds handling as a word.
boundsHandling wordToBoundsHandling (const word &bound) const
Return the out-of-bounds handling as an enumeration.
boundsHandling outOfBounds (const boundsHandling &bound)
Set the out-of-bounds handling from enum, return previous setting.
void checkOrder () const
Check that list is monotonically increasing.
void write (Ostream &os) const
Write.
const List< Tuple2< scalar, Type > > & operator[] (const label) const
Return an element of constant Tuple2<scalar, Type>
Type operator() (const scalar, const scalar) const
Return an interpolated value.
template<class BinaryOp >
Foam::label Xi (const BinaryOp &bop, const scalar valueX, const bool reverse) const
Public Member Functions inherited from List< Tuple2< scalar, List< Tuple2< scalar, Type > > > >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Tuple2< scalar, List< Tuple2< scalar, Type > > > &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Copy constructor.
List (const Xfer< List< Tuple2< scalar, List< Tuple2< scalar, Type > > > >> &)
Construct by transferring the parameter contents.
List (List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< Tuple2< scalar, List< Tuple2< scalar, Type > > >, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Construct as copy of PtrList<T>
List (const SLList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Construct as copy of SLList<T>
List (const UIndirectList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Tuple2< scalar, List< Tuple2< scalar, Type > > > &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Tuple2< scalar, List< Tuple2< scalar, Type > > > &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Tuple2< scalar, List< Tuple2< scalar, Type > > > &)
Append an element at the end of the list.
void append (const UList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Append a List at the end of this list.
void append (const UIndirectList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Append a UIndirectList at the end of this list.
void transfer (List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Tuple2< scalar, List< Tuple2< scalar, Type > > >, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Transfer the contents of the argument List into this list.
Xfer< List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > > xfer ()
Transfer contents to the Xfer container.
Tuple2< scalar, List< Tuple2< scalar, Type > > > & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Tuple2< scalar, List< Tuple2< scalar, Type > > > > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Tuple2< scalar, List< Tuple2< scalar, Type > > > &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Additional Inherited Members
Static Public Member Functions inherited from List< Tuple2< scalar, List< Tuple2< scalar, Type > > > >
static const List< Tuple2< scalar, List< Tuple2< scalar, Type > > > > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< Tuple2< scalar, List< Tuple2< scalar, Type > > > >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::interpolation2DTable< Type >
2D table interpolation. The data must be in ascending order in both dimensions x and y.
Source files
interpolation2DTable.H
interpolation2DTable.C
Definition at line 52 of file interpolation2DTable.H.
Member Typedef Documentation
typedef List<Tuple2<scalar, List<Tuple2<scalar, Type> > > > table
Cconvenience typedef.
Definition at line 69 of file interpolation2DTable.H.
Member Enumeration Documentation
enum boundsHandling
Enumeration for handling out-of-bound values.
Enumerator
ERROR
Exit with a FatalError
WARN
Issue warning and clamp value (default)
CLAMP
Clamp value to the start/end value
Definition at line 61 of file interpolation2DTable.H.
Constructor & Destructor Documentation
interpolation2DTable ()
Construct null.
Definition at line 55 of file interpolation2DTable.C.
Referenced by interpolation2DTable< Type >::interpolation2DTable().
interpolation2DTable (const List< Tuple2< scalar, List< Tuple2< scalar, Type >>>> & values, const boundsHandling bounds, const fileName & fName)
Construct from components.
Definition at line 66 of file interpolation2DTable.C.
interpolation2DTable (const fileName & fName)
Construct given the name of the file containing the table of data.
Definition at line 80 of file interpolation2DTable.C.
interpolation2DTable (const dictionary & dict)
Construct by reading the fileName and boundsHandling from dictionary.
Definition at line 92 of file interpolation2DTable.C.
References interpolation2DTable< Type >::interpolation2DTable().
interpolation2DTable (const interpolation2DTable< Type > & interpTable)
Construct copy.
Definition at line 105 of file interpolation2DTable.C.
References interpolation2DTable< Type >::CLAMP, Foam::endl(), interpolation2DTable< Type >::ERROR, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UILList< LListBase, T >::first(), UList< T >::first(), UILList< LListBase, T >::last(), n, Foam::nl, DLListBase::size(), interpolation2DTable< Type >::WARN, and WarningInFunction.
Member Function Documentation
Foam::word boundsHandlingToWord (const boundsHandling & bound) const
Return the out-of-bounds handling as a word.
Definition at line 349 of file interpolation2DTable.C.
References interpolation2DTable< Type >::CLAMP, interpolation2DTable< Type >::ERROR, interpolation2DTable< Type >::WARN, and interpolation2DTable< Type >::wordToBoundsHandling().
Referenced by interpolation2DTable< Type >::operator()(), and interpolation2DTable< Type >::write().
Foam::interpolation2DTable< Type >::boundsHandling wordToBoundsHandling (const word & bound) const
Return the out-of-bounds handling as an enumeration.
Definition at line 381 of file interpolation2DTable.C.
References interpolation2DTable< Type >::CLAMP, Foam::endl(), interpolation2DTable< Type >::ERROR, interpolation2DTable< Type >::outOfBounds(), interpolation2DTable< Type >::WARN, and WarningInFunction.
Referenced by interpolation2DTable< Type >::boundsHandlingToWord().
Foam::interpolation2DTable< Type >::boundsHandling outOfBounds (const boundsHandling & bound)
Set the out-of-bounds handling from enum, return previous setting.
Definition at line 410 of file interpolation2DTable.C.
References Foam::bound().
Referenced by interpolation2DTable< Type >::wordToBoundsHandling().
void checkOrder () const
Check that list is monotonically increasing.
Exit with a FatalError if there is a problem
Definition at line 421 of file interpolation2DTable.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), n, Foam::nl, and List< Tuple2< scalar, List< Tuple2< scalar, Type > > > >::size().
void write (Ostream & os) const
Write.
Definition at line 446 of file interpolation2DTable.C.
References interpolation2DTable< Type >::boundsHandlingToWord(), token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
const List<Tuple2<scalar, Type> >& operator[] (const label) const
Return an element of constant Tuple2<scalar, Type>
Type operator() (const scalar valueX, const scalar valueY) const
Return an interpolated value.
Definition at line 296 of file interpolation2DTable.C.
References interpolation2DTable< Type >::boundsHandlingToWord(), Foam::endl(), UList< T >::first(), List< Tuple2< scalar, List< Tuple2< scalar, Type > > > >::size(), WarningInFunction, Foam::y0(), Foam::y1(), and Foam::Zero.
Foam::label Xi (const BinaryOp & bop, const scalar valueX, const bool reverse) const
Definition at line 224 of file interpolation2DTable.C.
References Foam::abort(), interpolation2DTable< Type >::CLAMP, Foam::endl(), interpolation2DTable< Type >::ERROR, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), UList< T >::operator, List< T >::size(), interpolation2DTable< Type >::WARN, and WarningInFunction.
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolation2DTable/interpolation2DTable.H
src/OpenFOAM/interpolations/interpolation2DTable/interpolation2DTable.C