OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
interpolationCellPointFace< Type > Class Template Reference
Foam::interpolationCellPointFace.
Public Member Functions
TypeName ("cellPointFace")
Runtime type information.
interpolationCellPointFace (const GeometricField< Type, fvPatchField, volMesh > &psi)
Construct from components.
Type interpolate (const vector &position, const label cellI, const label faceI=-1) const
Interpolate field to the given point in the given cell.
Public Member Functions inherited from interpolation< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interpolation, dictionary,(const GeometricField< Type, fvPatchField, volMesh > &psi),(psi))
interpolation (const GeometricField< Type, fvPatchField, volMesh > &psi)
Construct from components.
virtual ~interpolation ()
Destructor.
const GeometricField< Type, fvPatchField, volMesh > & psi () const
Return the field to be interpolated.
virtual Type interpolate (const vector &position, const tetIndices &tetIs, const label faceI=-1) const
Interpolate field to the given point in the tetrahedron.
Additional Inherited Members
Static Public Member Functions inherited from interpolation< Type >
static autoPtr< interpolation< Type > > New (const word &interpolationType, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the specified interpolation scheme.
static autoPtr< interpolation< Type > > New (const dictionary &interpolationSchemes, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the selected interpolation scheme.
Protected Attributes inherited from interpolation< Type >
const GeometricField< Type, fvPatchField, volMesh > & psi_
const polyMesh & pMesh_
const vectorField & pMeshPoints_
const faceList & pMeshFaces_
const vectorField & pMeshFaceCentres_
const vectorField & pMeshFaceAreas_
Detailed Description
template<class Type>
class Foam::interpolationCellPointFace< Type >
Foam::interpolationCellPointFace.
Definition at line 46 of file interpolationCellPointFace.H.
Constructor & Destructor Documentation
interpolationCellPointFace (const GeometricField< Type, fvPatchField, volMesh > & psi)
Construct from components.
Definition at line 38 of file interpolationCellPointFace.C.
References interpolationCellPointFace< Type >::interpolate().
Member Function Documentation
TypeName ("cellPointFace")
Runtime type information.
Type interpolate (const vector & position, const label cellI, const label faceI = -1) const virtual
Interpolate field to the given point in the given cell.
Implements interpolation< Type >.
Definition at line 60 of file interpolationCellPointFace.C.
References Foam::constant::electromagnetic::e, Foam::endl(), forAll, InfoInFunction, Foam::mag(), Foam::max(), Foam::min(), n, phi, List< T >::size(), Foam::tab, and Foam::Zero.
Referenced by interpolationCellPointFace< Type >::interpolationCellPointFace().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationCellPointFace/interpolationCellPointFace.H
src/finiteVolume/interpolation/interpolation/interpolationCellPointFace/findCellPointFaceTet.H
src/finiteVolume/interpolation/interpolation/interpolationCellPointFace/findCellPointFaceTriangle.H
src/finiteVolume/interpolation/interpolation/interpolationCellPointFace/interpolationCellPointFace.C