OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
inverseFaceDistanceDiffusivity Class Reference
Inverse distance to the given patches motion diffusivity.
Public Member Functions
TypeName ("inverseFaceDistance")
Runtime type information.
inverseFaceDistanceDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~inverseFaceDistanceDiffusivity ()
Destructor.
virtual void correct ()
Correct the motion diffusivity.
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
Runtime type information.
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~uniformDiffusivity ()
Destructor.
virtual tmp< surfaceScalarField > operator() () const
Return diffusivity field.
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
Construct for the given fvMesh.
virtual ~motionDiffusivity ()
Destructor.
const fvMesh & mesh () const
Return reference to the mesh.
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Select null constructed.
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
Inverse distance to the given patches motion diffusivity.
Source files
inverseFaceDistanceDiffusivity.H
inverseFaceDistanceDiffusivity.C
Definition at line 48 of file inverseFaceDistanceDiffusivity.H.
Constructor & Destructor Documentation
inverseFaceDistanceDiffusivity (const fvMesh & mesh, Istream & mdData)
Construct for the given fvMesh and data Istream.
Definition at line 50 of file inverseFaceDistanceDiffusivity.C.
References correct.
~inverseFaceDistanceDiffusivity () virtual
Destructor.
Definition at line 64 of file inverseFaceDistanceDiffusivity.C.
Member Function Documentation
TypeName ("inverseFaceDistance")
Runtime type information.
void correct () virtual
Correct the motion diffusivity.
Reimplemented from uniformDiffusivity.
Definition at line 70 of file inverseFaceDistanceDiffusivity.C.
References MeshWave< Type, TrackingData >::allCellInfo(), MeshWave< Type, TrackingData >::allFaceInfo(), polyMesh::boundaryMesh(), fvPatch::faceCells(), polyPatch::faceCentres(), polyBoundaryMesh::findPatchID(), forAll, forAllConstIter(), mesh, primitiveMesh::nInternalFaces(), fvsPatchField< Type >::patch(), patchi, List< T >::setSize(), UPtrList< T >::size(), Foam::sqrt(), fvPatch::start(), and polyPatch::start().
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/inverseFaceDistance/inverseFaceDistanceDiffusivity.H
src/fvMotionSolver/motionDiffusivity/inverseFaceDistance/inverseFaceDistanceDiffusivity.C