OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
internalWriter Class Reference
Write fields (internal).
Public Member Functions
internalWriter (const vtkMesh &, const bool binary, const fileName &)
Construct from components.
std::ofstream & os ()
void writeCellIDs ()
Write cellIDs.
template<class Type , template< class > class PatchField, class GeoMesh >
void write (const PtrList< GeometricField< Type, PatchField, GeoMesh >> &)
Write generic GeometricFields.
template<class Type >
void write (const volPointInterpolation &, const PtrList< GeometricField< Type, fvPatchField, volMesh >> &)
Interpolate and write volFields.
Detailed Description
Write fields (internal).
Source files
internalWriter.H
internalWriter.C
internalWriterTemplates.C
Definition at line 56 of file internalWriter.H.
Constructor & Destructor Documentation
internalWriter (const vtkMesh & , const bool binary, const fileName &)
Construct from components.
Member Function Documentation
std::ofstream& os () inline
Definition at line 81 of file internalWriter.H.
References internalWriter::write(), and internalWriter::writeCellIDs().
void writeCellIDs ()
Write cellIDs.
Referenced by internalWriter::os().
void write (const PtrList< GeometricField< Type, PatchField, GeoMesh >> &)
Write generic GeometricFields.
Referenced by internalWriter::os().
void write (const volPointInterpolation & , const PtrList< GeometricField< Type, fvPatchField, volMesh >> &)
Interpolate and write volFields.
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToVTK/foamToVTK/internalWriter.H