OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
injectionModelList Class Reference
Public Member Functions
injectionModelList (surfaceFilmModel &owner)
Construct null.
injectionModelList (surfaceFilmModel &owner, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~injectionModelList ()
Destructor.
virtual void correct (scalarField &availableMass, volScalarField &massToInject, volScalarField &diameterToInject)
Correct.
virtual void info (Ostream &os)
Provide some info.
Public Member Functions inherited from PtrList< injectionModel >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< injectionModel > &)
Copy constructor.
PtrList (const PtrList< injectionModel > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< injectionModel >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< injectionModel > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< injectionModel > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (injectionModel *)
Append an element at the end of the list.
void append (const autoPtr< injectionModel > &)
void append (const tmp< injectionModel > &)
void transfer (PtrList< injectionModel > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< injectionModel > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< injectionModel > set (const label, injectionModel *)
Set element to given T* and return old element (can be NULL)
autoPtr< injectionModel > set (const label, const autoPtr< injectionModel > &)
Set element to given autoPtr<T> and return old element.
autoPtr< injectionModel > set (const label, const tmp< injectionModel > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< injectionModel > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool outputTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< injectionModel >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
Definition at line 54 of file injectionModelList.H.
Constructor & Destructor Documentation
injectionModelList (surfaceFilmModel & owner)
Construct null.
Definition at line 39 of file injectionModelList.C.
injectionModelList (surfaceFilmModel & owner, const dictionary & dict)
Construct from type name, dictionary and surface film model.
Definition at line 47 of file injectionModelList.C.
References Foam::endl(), forAll, forAllConstIter(), Foam::Info, dictionary::lookup(), injectionModel::New(), and PtrList< injectionModel >::setSize().
~injectionModelList () virtual
Destructor.
Definition at line 93 of file injectionModelList.C.
References injectionModelList::correct().
Member Function Documentation
void correct (scalarField & availableMass, volScalarField & massToInject, volScalarField & diameterToInject) virtual
Correct.
Definition at line 100 of file injectionModelList.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), injectionModel::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), forAll, regionModel::intCoupledPatchIDs(), UPtrList< T >::operator[](), filmSubModelBase::owner(), patchi, and Foam::sum().
Referenced by kinematicSingleLayer::updateSubmodels(), and injectionModelList::~injectionModelList().
void info (Ostream & os) virtual
Provide some info.
Definition at line 128 of file injectionModelList.C.
References polyMesh::boundaryMesh(), Foam::endl(), forAll, subModelBase::getBaseProperty(), Foam::indent(), Foam::Info, injectionModel::injectedMassTotal(), regionModel::intCoupledPatchIDs(), Pstream::listCombineGather(), Foam::mag(), IOobject::name(), Foam::nl, UPtrList< T >::operator[](), filmSubModelBase::outputTime(), filmSubModelBase::owner(), patchi, injectionModel::patchInjectedMassTotals(), regionModel::regionMesh(), subModelBase::setBaseProperty(), List< T >::size(), and UPtrList< T >::size().
Referenced by kinematicSingleLayer::info().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/injectionModelList/injectionModelList.H
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/injectionModelList/injectionModelList.C