OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IOerror Class Reference
Report an I/O error.
Public Member Functions
IOerror (const string &title)
Construct from title string.
IOerror (const dictionary &)
Construct from dictionary.
virtual ~IOerror () throw ()
Destructor.
const string & ioFileName () const
label ioStartLineNumber () const
label ioEndLineNumber () const
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &)
Convert to OSstream.
operator dictionary () const
Create and return a dictionary.
void exit (const int errNo=1)
Exit : can be called for any error to exit program.
void abort ()
Abort : used to stop code for fatal errors.
Public Member Functions inherited from error
error (const string &title)
Construct from title string.
error (const dictionary &)
Construct from dictionary.
error (const error &)
Construct as copy.
virtual ~error () throw ()
Destructor.
string message () const
const string & functionName () const
const string & sourceFileName () const
label sourceFileLineNumber () const
void throwExceptions ()
void dontThrowExceptions ()
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
operator OSstream & ()
Convert to OSstream.
OSstream & operator() ()
Explicitly convert to OSstream for << operations.
operator dictionary () const
Create and return a dictionary.
void exit (const int errNo=1)
Exit : can be called for any error to exit program.
void abort ()
Abort : used to stop code for fatal errors.
Public Member Functions inherited from messageStream
messageStream (const string &title, errorSeverity, const int maxErrors=0)
Construct from components.
messageStream (const dictionary &)
Construct from dictionary.
const string & title () const
Return the title of this error type.
int maxErrors () const
Return the maximum number of errors before program termination.
int & maxErrors ()
Return non-const access to the maximum number of errors before.
OSstream & masterStream (const label communicator)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &)
Convert to OSstream.
operator OSstream & ()
Convert to OSstream for << operations.
OSstream & operator() ()
Explicitly convert to OSstream for << operations.
Static Public Member Functions
static void SafeFatalIOError (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &, const string &msg)
Print basic message and exit. Uses cerr if streams not constructed.
Static Public Member Functions inherited from error
static void safePrintStack (std::ostream &)
Helper function to print a stack (if OpenFOAM IO not yet.
static void printStack (Ostream &)
Helper function to print a stack.
Friends
Ostream & operator<< (Ostream &, const IOerror &)
Additional Inherited Members
Public Types inherited from messageStream
enum errorSeverity { INFO, WARNING, SERIOUS, FATAL }
Severity flags.
Static Public Attributes inherited from messageStream
static int level
Protected Attributes inherited from error
string functionName_
string sourceFileName_
label sourceFileLineNumber_
bool abort_
bool throwExceptions_
OStringStream * messageStreamPtr_
Protected Attributes inherited from messageStream
string title_
errorSeverity severity_
int maxErrors_
int errorCount_
Detailed Description
Report an I/O error.
Definition at line 196 of file error.H.
Constructor & Destructor Documentation
IOerror (const string & title)
Construct from title string.
Definition at line 36 of file IOerror.C.
IOerror (const dictionary & errDict)
Construct from dictionary.
Definition at line 45 of file IOerror.C.
~IOerror () throw () virtual
Destructor.
Definition at line 54 of file IOerror.C.
Member Function Documentation
const string& ioFileName () const inline
Definition at line 224 of file error.H.
Referenced by IOerror::operator()(), Foam::operator<<(), and IOerror::SafeFatalIOError().
label ioStartLineNumber () const inline
Definition at line 229 of file error.H.
Referenced by IOerror::operator()(), Foam::operator<<(), and IOerror::SafeFatalIOError().
label ioEndLineNumber () const inline
Definition at line 234 of file error.H.
References error::abort(), error::exit(), Foam::FatalError, FatalErrorIn, Foam::FatalIOError, FatalIOErrorIn, FUNCTION_NAME, error::functionName(), notImplemented, NotImplemented, error::operator<<, IOerror::SafeFatalIOError(), SafeFatalIOErrorIn, SafeFatalIOErrorInFunction, error::sourceFileLineNumber(), and error::sourceFileName().
Referenced by IOerror::operator()(), Foam::operator<<(), and IOerror::SafeFatalIOError().
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const string & ioFileName, const label ioStartLineNumber = -1, const label ioEndLineNumber = -1)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 59 of file IOerror.C.
References error::functionName(), IOerror::ioEndLineNumber(), IOerror::ioFileName(), IOerror::ioStartLineNumber(), error::operator()(), error::sourceFileLineNumber(), and error::sourceFileName().
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const IOstream & ioStream)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 78 of file IOerror.C.
References error::functionName(), error::sourceFileLineNumber(), and error::sourceFileName().
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const dictionary & dict)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 98 of file IOerror.C.
References dict, error::functionName(), IOerror::SafeFatalIOError(), error::sourceFileLineNumber(), and error::sourceFileName().
void SafeFatalIOError (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const IOstream & ioStream, const string & msg) static
Print basic message and exit. Uses cerr if streams not constructed.
yet (at startup). Use in startup parsing instead of FatalError.
Definition at line 118 of file IOerror.C.
References dictionary::add(), JobInfo::constructed, Foam::endl(), Foam::exit(), IOerror::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOerror::ioEndLineNumber(), IOerror::ioFileName(), IOerror::ioStartLineNumber(), IOstream::lineNumber(), IOstream::name(), and dictionary::remove().
Referenced by IOerror::ioEndLineNumber(), and IOerror::operator()().
operator dictionary () const
Create and return a dictionary.
void exit (const int errNo = 1)
Exit : can be called for any error to exit program.
Definition at line 168 of file IOerror.C.
References IOerror::abort(), error::abort_, dictionary::add(), JobInfo::constructed, Foam::endl(), JobInfo::exit(), UPstream::exit(), Foam::jobInfo, error::messageStreamPtr_, UPstream::parRun(), Foam::Perr, OStringStream::rewind(), and error::throwExceptions_.
Referenced by Foam::exit(), IFstream::operator()(), Istream::operator()(), and IOerror::SafeFatalIOError().
void abort ()
Abort : used to stop code for fatal errors.
Definition at line 209 of file IOerror.C.
References JobInfo::abort(), UPstream::abort(), error::abort_, dictionary::add(), JobInfo::constructed, Foam::endl(), Foam::jobInfo, error::messageStreamPtr_, UPstream::parRun(), Foam::Perr, error::printStack(), OStringStream::rewind(), and error::throwExceptions_.
Referenced by Foam::abort(), and IOerror::exit().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const IOerror &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/db/error/error.H
src/OpenFOAM/db/error/IOerror.C