OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
interRegionExplicitPorositySource Class Reference
Inter-region explicit porosity source.
Public Member Functions
TypeName ("interRegionExplicitPorositySource")
Runtime type information.
interRegionExplicitPorositySource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~interRegionExplicitPorositySource ()
Destructor.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual bool read (const dictionary &dict)
Read dictionary.
Public Member Functions inherited from interRegionOption
TypeName ("interRegionOption")
Runtime type information.
interRegionOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from dictionary.
virtual ~interRegionOption ()
Destructor.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
Switch & active ()
Return access to the source active flag.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldI)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldI)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldI)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Protected Member Functions
void initialise ()
Initialise.
Protected Member Functions inherited from interRegionOption
void setMapper ()
Set the mesh to mesh interpolation object.
Protected Attributes
autoPtr< porosityModel > porosityPtr_
Run-time selectable porosity model.
bool firstIter_
First iteration.
word UName_
Velocity field name, default = U.
word muName_
Dynamic viscosity field name (compressible case only)
Protected Attributes inherited from interRegionOption
bool master_
Master or slave region.
word nbrRegionName_
Name of the neighbour region to map.
autoPtr< meshToMesh > meshInterpPtr_
Mesh to mesh interpolation object.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Detailed Description
Inter-region explicit porosity source.
Sources described by, for example using the DarcyForchheimer model:
interRegionExplicitPorositySourceCoeffs { type DarcyForchheimer; DarcyForchheimerCoeffs { d d [0 -2 0 0 0 0 0] (5e7 -1000 -1000); f f [0 -1 0 0 0 0 0] (0 0 0);
coordinateSystem { e1 (0.70710678 0.70710678 0); e2 (0 0 1); } } }
Note: The porous region must be selected as a cellZone.
Source files
interRegionExplicitPorositySource.H
interRegionExplicitPorositySource.C
Definition at line 75 of file interRegionExplicitPorositySource.H.
Constructor & Destructor Documentation
interRegionExplicitPorositySource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 114 of file interRegionExplicitPorositySource.C.
virtual ~interRegionExplicitPorositySource () inline virtual
Destructor.
Definition at line 137 of file interRegionExplicitPorositySource.H.
Member Function Documentation
void initialise () protected
Initialise.
Definition at line 50 of file interRegionExplicitPorositySource.C.
References Foam::abort(), polyMesh::cellZones(), ZoneMesh< ZoneType, MeshType >::clearAddressing(), option::coeffs_, polyMesh::faceNeighbour(), Foam::FatalError, FatalErrorIn, ZoneMesh< ZoneType, MeshType >::findZoneID(), interRegionExplicitPorositySource::firstIter_, objectRegistry::lookupObject(), option::mesh_, option::name_, interRegionOption::nbrRegionName_, porosityModel::New(), interRegionExplicitPorositySource::porosityPtr_, PtrList< T >::set(), PtrList< T >::setSize(), PtrList< T >::size(), and fvMesh::time().
TypeName ("interRegionExplicitPorositySource")
Runtime type information.
void addSup (fvMatrix< vector > & eqn, const label fieldI) virtual
Vector.
Reimplemented from option.
Definition at line 138 of file interRegionExplicitPorositySource.C.
References lduMatrix::diag(), fvMatrix< Type >::dimensions(), GeometricField< Type, PatchField, GeoMesh >::internalField(), objectRegistry::lookupObject(), IOobject::NO_READ, IOobject::NO_WRITE, fvMatrix< Type >::psi(), List< T >::setSize(), List< T >::size(), fvMatrix< Type >::source(), fvMesh::time(), Time::timeName(), U, and Vector< scalar >::zero.
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldI) virtual
Vector.
Reimplemented from option.
Definition at line 191 of file interRegionExplicitPorositySource.C.
References lduMatrix::diag(), Foam::dimDensity, fvMatrix< Type >::dimensions(), Foam::dimViscosity, GeometricField< Type, PatchField, GeoMesh >::internalField(), objectRegistry::lookupObject(), Foam::constant::physicoChemical::mu, IOobject::NO_READ, IOobject::NO_WRITE, fvMatrix< Type >::psi(), List< T >::setSize(), List< T >::size(), fvMatrix< Type >::source(), fvMesh::time(), Time::timeName(), U, and Vector< scalar >::zero.
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from interRegionOption.
Definition at line 291 of file interRegionExplicitPorositySource.C.
References interRegionOption::read().
Member Data Documentation
autoPtr<porosityModel> porosityPtr_ protected
Run-time selectable porosity model.
Definition at line 85 of file interRegionExplicitPorositySource.H.
Referenced by interRegionExplicitPorositySource::initialise().
bool firstIter_ protected
First iteration.
Definition at line 88 of file interRegionExplicitPorositySource.H.
Referenced by interRegionExplicitPorositySource::initialise().
word UName_ protected
Velocity field name, default = U.
Definition at line 91 of file interRegionExplicitPorositySource.H.
word muName_ protected
Dynamic viscosity field name (compressible case only)
default = thermo:mu
Definition at line 95 of file interRegionExplicitPorositySource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/interRegion/interRegionExplicitPorositySource/interRegionExplicitPorositySource.H
src/fvOptions/sources/interRegion/interRegionExplicitPorositySource/interRegionExplicitPorositySource.C