OpenFOAM: inverseDistanceDiffusivity Class Reference
inverseDistanceDiffusivity Class Reference
Inverse distance to the given patches motion diffusivity.
Public Member Functions
TypeName ("inverseDistance")
Runtime type information.
inverseDistanceDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~inverseDistanceDiffusivity ()
Destructor.
virtual void correct ()
Correct the motion diffusivity.
Public Member Functions inherited from uniformDiffusivity
TypeName ("uniform")
Runtime type information.
uniformDiffusivity (const fvMesh &mesh, Istream &mdData)
Construct for the given fvMesh and data Istream.
virtual ~uniformDiffusivity ()
Destructor.
virtual tmp< surfaceScalarField > operator() () const
Return diffusivity field.
Public Member Functions inherited from motionDiffusivity
TypeName ("motionDiffusivity")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, motionDiffusivity, Istream,(const fvMesh &mesh, Istream &mdData),(mesh, mdData))
motionDiffusivity (const fvMesh &mesh)
Construct for the given fvMesh.
virtual ~motionDiffusivity ()
Destructor.
const fvMesh & mesh () const
Return reference to the mesh.
Additional Inherited Members
Static Public Member Functions inherited from motionDiffusivity
static autoPtr< motionDiffusivity > New (const fvMesh &mesh, Istream &mdData)
Select null constructed.
Protected Attributes inherited from uniformDiffusivity
surfaceScalarField faceDiffusivity_
Detailed Description
Inverse distance to the given patches motion diffusivity.
Source files
inverseDistanceDiffusivity.H
inverseDistanceDiffusivity.C
Definition at line 49 of file inverseDistanceDiffusivity.H.
Constructor & Destructor Documentation
inverseDistanceDiffusivity (const fvMesh & mesh, Istream & mdData)
Construct for the given fvMesh and data Istream.
Definition at line 51 of file inverseDistanceDiffusivity.C.
References correct.
~inverseDistanceDiffusivity () virtual
Destructor.
Definition at line 65 of file inverseDistanceDiffusivity.C.
References Foam::distance(), mesh, and HashTable< T, Key, Hash >::size().
Member Function Documentation
TypeName ("inverseDistance")
Runtime type information.
void correct () virtual
Correct the motion diffusivity.
Reimplemented from uniformDiffusivity.
Definition at line 89 of file inverseDistanceDiffusivity.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dimless, Foam::fvc::interpolate(), mesh, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), timeName, and y.
The documentation for this class was generated from the following files:
src/fvMotionSolver/motionDiffusivity/inverseDistance/inverseDistanceDiffusivity.H
src/fvMotionSolver/motionDiffusivity/inverseDistance/inverseDistanceDiffusivity.C