OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
streamLineParticle::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< streamLineParticle > operator() (Istream &is) const
Detailed Description
Factory class to read-construct particles used for.
parallel transfer
Definition at line 191 of file streamLineParticle.H.
Constructor & Destructor Documentation
iNew (const polyMesh & mesh) inline
Definition at line 197 of file streamLineParticle.H.
Member Function Documentation
autoPtr<streamLineParticle> operator() (Istream & is) const inline
Definition at line 202 of file streamLineParticle.H.
References streamLineParticle::hitCyclicPatch(), streamLineParticle::hitPatch(), streamLineParticle::hitProcessorPatch(), streamLineParticle::hitSymmetryPatch(), streamLineParticle::hitSymmetryPlanePatch(), streamLineParticle::hitWallPatch(), streamLineParticle::hitWedgePatch(), streamLineParticle::move(), streamLineParticle::operator<<, streamLineParticle::readFields(), streamLineParticle::streamLineParticle(), and streamLineParticle::writeFields().
The documentation for this class was generated from the following file:
src/postProcessing/functionObjects/field/streamLine/streamLineParticle.H