OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IntegrationScheme< Type > Class Template Reference abstract
Top level model for Integration schemes.
Classes
class integrationResult
Helper class to supply results of integration.
Public Member Functions
TypeName ("integrationScheme")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IntegrationScheme, dictionary,(const word &phiName, const dictionary &dict),(phiName, dict))
Declare runtime constructor selection table.
IntegrationScheme (const word &phiName, const dictionary &dict)
Construct from components.
IntegrationScheme (const IntegrationScheme &is)
Copy constructor.
virtual autoPtr
< IntegrationScheme< Type > > clone () const =0
Construct and return clone.
virtual ~IntegrationScheme ()
Destructor.
virtual integrationResult integrate (const Type &phi, const scalar dt, const Type &alphaBeta, const scalar beta) const =0
Perform the Integration.
Static Public Member Functions
static autoPtr< IntegrationScheme > New (const word &phiName, const dictionary &dict)
Return a reference to the selected radiation model.
Detailed Description
template<class Type>
class Foam::IntegrationScheme< Type >
Top level model for Integration schemes.
Source files
IntegrationScheme.H
IntegrationScheme.C
Definition at line 51 of file IntegrationScheme.H.
Constructor & Destructor Documentation
IntegrationScheme (const word & phiName, const dictionary & dict)
Construct from components.
Definition at line 32 of file IntegrationScheme.C.
IntegrationScheme (const IntegrationScheme< Type > & is)
Copy constructor.
Definition at line 43 of file IntegrationScheme.C.
~IntegrationScheme () virtual
Destructor.
Definition at line 53 of file IntegrationScheme.C.
Member Function Documentation
TypeName ("integrationScheme")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , IntegrationScheme< Type > , dictionary , (const word &phiName, const dictionary &dict) , (phiName, dict))
Declare runtime constructor selection table.
virtual autoPtr<IntegrationScheme<Type> > clone () const pure virtual
Construct and return clone.
Implemented in Analytical< Type >, and Euler< Type >.
Foam::autoPtr< Foam::IntegrationScheme< Type > > New (const word & phiName, const dictionary & dict) static
Return a reference to the selected radiation model.
Definition at line 34 of file IntegrationSchemeNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::Info, dictionary::lookup(), and Foam::nl.
virtual integrationResult integrate (const Type & phi, const scalar dt, const Type & alphaBeta, const scalar beta) const pure virtual
Perform the Integration.
Implemented in Analytical< Type >, and Euler< Type >.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/IntegrationScheme/IntegrationScheme/IntegrationScheme.H
src/lagrangian/intermediate/IntegrationScheme/IntegrationScheme/IntegrationScheme.C
src/lagrangian/intermediate/IntegrationScheme/IntegrationScheme/IntegrationSchemeNew.C