OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
InflowBoundaryModel< CloudType > Class Template Reference abstract
Templated inflow boundary model class.
Public Member Functions
TypeName ("InflowBoundaryModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, InflowBoundaryModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
InflowBoundaryModel (CloudType &owner)
Construct null from owner.
InflowBoundaryModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
virtual ~InflowBoundaryModel ()
Destructor.
const CloudType & owner () const
Return const access the owner cloud object.
CloudType & owner ()
Return non-const access the owner cloud object for manipulation.
const dictionary & dict () const
Return the owner cloud dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
virtual void autoMap (const mapPolyMesh &)
Remap the particles to the correct cells following mesh change.
virtual void inflow ()=0
Introduce particles.
Static Public Member Functions
static autoPtr< InflowBoundaryModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::InflowBoundaryModel< CloudType >
Templated inflow boundary model class.
Source files
InflowBoundaryModel.H
InflowBoundaryModel.C
InflowBoundaryModelNew.C
Definition at line 61 of file DSMCCloud.H.
Constructor & Destructor Documentation
InflowBoundaryModel (CloudType & owner)
Construct null from owner.
Definition at line 31 of file InflowBoundaryModel.C.
InflowBoundaryModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from dictionary.
Definition at line 41 of file InflowBoundaryModel.C.
~InflowBoundaryModel () virtual
Destructor.
Definition at line 56 of file InflowBoundaryModel.C.
Member Function Documentation
TypeName ("InflowBoundaryModel< CloudType >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , InflowBoundaryModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::InflowBoundaryModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file InflowBoundaryModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
const CloudType & owner () const inline
Return const access the owner cloud object.
Definition at line 63 of file InflowBoundaryModel.C.
CloudType & owner () inline
Return non-const access the owner cloud object for manipulation.
Definition at line 70 of file InflowBoundaryModel.C.
const Foam::dictionary & dict () const inline
Return the owner cloud dictionary.
Definition at line 77 of file InflowBoundaryModel.C.
const Foam::dictionary & coeffDict () const inline
Return the coefficients dictionary.
Definition at line 84 of file InflowBoundaryModel.C.
virtual void autoMap (const mapPolyMesh &) inline virtual
Remap the particles to the correct cells following mesh change.
Reimplemented in FreeStream< CloudType >.
Definition at line 129 of file InflowBoundaryModel.H.
virtual void inflow () pure virtual
Introduce particles.
Implemented in FreeStream< CloudType >, and NoInflow< CloudType >.
Referenced by InflowBoundaryModel< Foam::DSMCCloud< ParcelType > >::autoMap().
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/clouds/Templates/DSMCCloud/DSMCCloud.H
src/lagrangian/DSMC/submodels/InflowBoundaryModel/InflowBoundaryModel/InflowBoundaryModel.H
src/lagrangian/DSMC/submodels/InflowBoundaryModel/InflowBoundaryModel/InflowBoundaryModel.C
src/lagrangian/DSMC/submodels/InflowBoundaryModel/InflowBoundaryModel/InflowBoundaryModelNew.C