OpenFOAM: InteractionLists< ParticleType > Class Template Reference
InteractionLists< ParticleType > Class Template Reference
Builds direct interaction list, specifying which local (real) cells are potentially in range of each other.
Public Member Functions
InteractionLists (const polyMesh &mesh)
Construct null from mesh.
InteractionLists (const polyMesh &mesh, scalar maxDistance, Switch writeCloud=false, const word &UName="U")
Construct and call function to create all information from.
~InteractionLists ()
void sendReferredData (const List< DynamicList< ParticleType * >> &cellOccupancy, PstreamBuffers &pBufs)
Prepare and send referred particles and wall data,.
void receiveReferredData (PstreamBuffers &pBufs, const label startReq=0)
Receive referred data.
const polyMesh & mesh () const
Return access to the mesh.
const mapDistribute & cellMap () const
Return access to the cellMap.
const mapDistribute & wallFaceMap () const
Return access to the wallFaceMap.
const labelListList & dil () const
Return access to the direct interaction list.
const labelListList & dwfil () const
Return access to the direct wall face interaction list.
const labelListList & ril () const
Return access to the referred interaction list.
const labelListList & rilInverse () const
Return access to the inverse referred interaction list.
const labelListList & rwfil () const
Return access to the referred wall face interaction list.
const labelListList & rwfilInverse () const
Return access to the inverse referred wall face.
const List< labelPair > & cellIndexAndTransformToDistribute () const
Return access to the cellIndexAndTransformToDistribute list.
const List< labelPair > & wallFaceIndexAndTransformToDistribute () const
Return access to the wallFaceIndexAndTransformToDistribute list.
const List< referredWallFace > & referredWallFaces () const
Return access to the referred wall faces.
const word & UName () const
Return the name of the velocity field.
const List< vector > & referredWallData () const
Return access to the referred wall data.
const List< IDLList< ParticleType > > & referredParticles () const
Return access to the referred particle container.
List< IDLList< ParticleType > > & referredParticles ()
Return non-const access to the referred particle container.
Detailed Description
template<class ParticleType>
class Foam::InteractionLists< ParticleType >
Builds direct interaction list, specifying which local (real) cells are potentially in range of each other.
Builds referred interaction list, specifying which cells are required to provide interactions across coupled patches (cyclic or processor). Generates referred cells, and refers particles to the correct processor, applying the appropriate transform.
Simultaneous communication and computation is possible using:
PstreamBuffers pBufs(Pstream::nonBlocking);
label startOfRequests = Pstream::nRequests();
il_.sendReferredData(cellOccupancy_, pBufs);
// Do other things
il_.receiveReferredData(pBufs, startOfRequests);
Requiring data:
List<DynamicList<typename CloudType::parcelType*>> cellOccupancy_;
Source files
InteractionLists.H
InteractionListsI.H
InteractionLists.C
InteractionListsIO.C
Definition at line 79 of file InteractionLists.H.
Constructor & Destructor Documentation
InteractionLists (const polyMesh & mesh)
Construct null from mesh.
Definition at line 1095 of file InteractionLists.C.
InteractionLists (const polyMesh & mesh, scalar maxDistance, Switch writeCloud = false, const word & UName = "U")
Construct and call function to create all information from.
the mesh
Definition at line 1118 of file InteractionLists.C.
~InteractionLists ()
Definition at line 1149 of file InteractionLists.C.
References InteractionLists< ParticleType >::sendReferredData().
Member Function Documentation
void sendReferredData (const List< DynamicList< ParticleType * >> & cellOccupancy, PstreamBuffers & pBufs)
Prepare and send referred particles and wall data,.
nonBlocking communication
Definition at line 1157 of file InteractionLists.C.
References InteractionLists< ParticleType >::cellMap(), cellOccupancy, polyMesh::changing(), Foam::endl(), forAll, UPstream::nProcs(), InteractionLists< ParticleType >::receiveReferredData(), mapDistributeBase::send(), List< T >::size(), mapDistributeBase::subMap(), InteractionLists< ParticleType >::wallFaceMap(), and WarningInFunction.
Referenced by InteractionLists< ParticleType >::~InteractionLists().
void receiveReferredData (PstreamBuffers & pBufs, const label startReq = 0)
Receive referred data.
Definition at line 1205 of file InteractionLists.C.
References InteractionLists< ParticleType >::cellMap(), mapDistributeBase::constructMap(), forAll, UPstream::nProcs(), mapDistributeBase::receive(), List< T >::size(), UPstream::waitRequests(), and InteractionLists< ParticleType >::wallFaceMap().
Referenced by InteractionLists< ParticleType >::sendReferredData().
const Foam::polyMesh & mesh () const inline
Return access to the mesh.
Definition at line 31 of file InteractionListsI.H.
const Foam::mapDistribute & cellMap () const inline
Return access to the cellMap.
Definition at line 39 of file InteractionListsI.H.
Referenced by InteractionLists< ParticleType >::receiveReferredData(), and InteractionLists< ParticleType >::sendReferredData().
const Foam::mapDistribute & wallFaceMap () const inline
Return access to the wallFaceMap.
Definition at line 47 of file InteractionListsI.H.
Referenced by InteractionLists< ParticleType >::receiveReferredData(), and InteractionLists< ParticleType >::sendReferredData().
const Foam::labelListList & dil () const inline
Return access to the direct interaction list.
Definition at line 54 of file InteractionListsI.H.
const Foam::labelListList & dwfil () const inline
Return access to the direct wall face interaction list.
Definition at line 62 of file InteractionListsI.H.
const Foam::labelListList & ril () const inline
Return access to the referred interaction list.
Definition at line 69 of file InteractionListsI.H.
const Foam::labelListList & rilInverse () const inline
Return access to the inverse referred interaction list.
Definition at line 77 of file InteractionListsI.H.
const Foam::labelListList & rwfil () const inline
Return access to the referred wall face interaction list.
Definition at line 84 of file InteractionListsI.H.
const Foam::labelListList & rwfilInverse () const inline
Return access to the inverse referred wall face.
interaction list
Definition at line 92 of file InteractionListsI.H.
const Foam::List< Foam::labelPair > & cellIndexAndTransformToDistribute () const inline
Return access to the cellIndexAndTransformToDistribute list.
Definition at line 100 of file InteractionListsI.H.
References InteractionLists< ParticleType >::wallFaceIndexAndTransformToDistribute().
const Foam::List< Foam::labelPair > & wallFaceIndexAndTransformToDistribute () const inline
Return access to the wallFaceIndexAndTransformToDistribute list.
Definition at line 109 of file InteractionListsI.H.
Referenced by InteractionLists< ParticleType >::cellIndexAndTransformToDistribute().
const Foam::List< Foam::referredWallFace > & referredWallFaces () const inline
Return access to the referred wall faces.
Definition at line 117 of file InteractionListsI.H.
const Foam::word & UName () const inline
Return the name of the velocity field.
Definition at line 124 of file InteractionListsI.H.
const Foam::List< Foam::vector > & referredWallData () const inline
Return access to the referred wall data.
Definition at line 132 of file InteractionListsI.H.
const Foam::List< Foam::IDLList< ParticleType > > & referredParticles () const inline
Return access to the referred particle container.
Definition at line 140 of file InteractionListsI.H.
Foam::List< Foam::IDLList< ParticleType > > & referredParticles () inline
Return non-const access to the referred particle container.
Definition at line 148 of file InteractionListsI.H.
The documentation for this class was generated from the following files:
src/lagrangian/basic/InteractionLists/InteractionLists.H
src/lagrangian/basic/InteractionLists/InteractionLists.C
src/lagrangian/basic/InteractionLists/InteractionListsI.H