OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
interRegionOption Class Reference
Base class for inter-region exchange.
Public Member Functions
TypeName ("interRegionOption")
Runtime type information.
interRegionOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from dictionary.
virtual ~interRegionOption ()
Destructor.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
virtual bool read (const dictionary &dict)
Read dictionary.
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
Switch & active ()
Return access to the source active flag.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldI)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldI)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldI)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Protected Member Functions
void setMapper ()
Set the mesh to mesh interpolation object.
Protected Attributes
bool master_
Master or slave region.
word nbrRegionName_
Name of the neighbour region to map.
autoPtr< meshToMesh > meshInterpPtr_
Mesh to mesh interpolation object.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Detailed Description
Base class for inter-region exchange.
Definition at line 51 of file interRegionOption.H.
Constructor & Destructor Documentation
interRegionOption (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from dictionary.
Definition at line 90 of file interRegionOption.C.
~interRegionOption () virtual
Destructor.
Definition at line 117 of file interRegionOption.C.
Member Function Documentation
void setMapper () protected
Set the mesh to mesh interpolation object.
Definition at line 41 of file interRegionOption.C.
References polyMesh::bounds(), option::coeffs_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::indent(), Foam::Info, meshToMesh::interpolationMethodNames_, dictionary::lookup(), objectRegistry::lookupObject(), interRegionOption::master_, option::mesh_, interRegionOption::meshInterpPtr_, fvMesh::name(), interRegionOption::nbrRegionName_, Foam::nl, boundBox::overlaps(), interRegionOption::read(), and fvMesh::time().
TypeName ("interRegionOption")
Runtime type information.
const Foam::word & nbrRegionName () const inline
Return const access to the neighbour region name.
Definition at line 29 of file interRegionOptionI.H.
References interRegionOption::nbrRegionName_.
const Foam::meshToMesh & meshInterp () const inline
Return const access to the mapToMap pointer.
Definition at line 36 of file interRegionOptionI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from option.
Reimplemented in interRegionHeatTransferModel, interRegionExplicitPorositySource, variableHeatTransfer, tabulatedHeatTransfer, and constantHeatTransfer.
Definition at line 30 of file interRegionOptionIO.C.
References option::read().
Referenced by interRegionExplicitPorositySource::read(), interRegionHeatTransferModel::read(), and interRegionOption::setMapper().
Member Data Documentation
bool master_ protected
Master or slave region.
Definition at line 60 of file interRegionOption.H.
Referenced by interRegionOption::setMapper().
word nbrRegionName_ protected
Name of the neighbour region to map.
Definition at line 63 of file interRegionOption.H.
Referenced by interRegionExplicitPorositySource::initialise(), interRegionOption::nbrRegionName(), interRegionHeatTransferModel::nbrRegionName(), interRegionOption::setMapper(), and interRegionHeatTransferModel::setNbrModel().
autoPtr<meshToMesh> meshInterpPtr_ protected
Mesh to mesh interpolation object.
Definition at line 66 of file interRegionOption.H.
Referenced by interRegionOption::setMapper().
The documentation for this class was generated from the following files:
src/fvOptions/interRegionOption/interRegionOption.H
src/fvOptions/interRegionOption/interRegionOption.C
src/fvOptions/interRegionOption/interRegionOptionI.H
src/fvOptions/interRegionOption/interRegionOptionIO.C