OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
InjectionModelList< CloudType > Class Template Reference
List of injection models.
Public Member Functions
InjectionModelList (CloudType &owner)
Construct null from owner.
InjectionModelList (const dictionary &dict, CloudType &owner)
Construct from dictionary and cloud owner.
InjectionModelList (const InjectionModelList< CloudType > &im)
Construct copy.
virtual autoPtr< InjectionModelList< CloudType > > clone () const
Construct and return a clone.
virtual ~InjectionModelList ()
Destructor.
scalar timeStart () const
Return the minimum start-of-injection time.
scalar timeEnd () const
Return the maximum end-of-injection time.
scalar volumeToInject (const scalar time0, const scalar time1)
Volume of parcels to introduce relative to SOI.
scalar averageParcelMass ()
Return the average parcel mass.
void updateMesh ()
Set injector locations when mesh is updated.
template<class TrackData >
void inject (TrackData &td)
Main injection loop.
template<class TrackData >
void injectSteadyState (TrackData &td, const scalar trackTime)
Main injection loop - steady-state.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from PtrList< InjectionModel< CloudType > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< InjectionModel< CloudType > > &)
Copy constructor.
PtrList (const PtrList< InjectionModel< CloudType > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< InjectionModel< CloudType > >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< InjectionModel< CloudType > > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< InjectionModel< CloudType > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (InjectionModel< CloudType > *)
Append an element at the end of the list.
void append (const autoPtr< InjectionModel< CloudType > > &)
void append (const tmp< InjectionModel< CloudType > > &)
void transfer (PtrList< InjectionModel< CloudType > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< InjectionModel< CloudType > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< InjectionModel< CloudType > > set (const label, InjectionModel< CloudType > *)
Set element to given T* and return old element (can be NULL)
autoPtr< InjectionModel< CloudType > > set (const label, const autoPtr< InjectionModel< CloudType > > &)
Set element to given autoPtr<T> and return old element.
autoPtr< InjectionModel< CloudType > > set (const label, const tmp< InjectionModel< CloudType > > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< InjectionModel< CloudType > > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< InjectionModel< CloudType > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
template<class CloudType>
class Foam::InjectionModelList< CloudType >
List of injection models.
Source files
InjectionModelList.H
InjectionModelListList.C
Definition at line 76 of file KinematicCloud.H.
Constructor & Destructor Documentation
InjectionModelList (CloudType & owner)
Construct null from owner.
Definition at line 31 of file InjectionModelList.C.
Referenced by InjectionModelList< CloudType >::InjectionModelList().
InjectionModelList (const dictionary & dict, CloudType & owner)
Construct from dictionary and cloud owner.
Definition at line 39 of file InjectionModelList.C.
References Foam::endl(), forAllConstIter(), Foam::Info, InjectionModelList< CloudType >::InjectionModelList(), dictionary::lookup(), InjectionModel< CloudType >::New(), PtrList< InjectionModel< CloudType > >::setSize(), and dictionary::toc().
InjectionModelList (const InjectionModelList< CloudType > & im)
Construct copy.
Definition at line 95 of file InjectionModelList.C.
~InjectionModelList () virtual
Destructor.
Definition at line 106 of file InjectionModelList.C.
Referenced by InjectionModelList< Foam::KinematicCloud< CloudType > >::clone().
Member Function Documentation
virtual autoPtr<InjectionModelList<CloudType> > clone () const inline virtual
Construct and return a clone.
Definition at line 68 of file InjectionModelList.H.
Foam::scalar timeStart () const
Return the minimum start-of-injection time.
Definition at line 113 of file InjectionModelList.C.
References forAll, and Foam::min().
Referenced by InjectionModelList< Foam::KinematicCloud< CloudType > >::clone().
Foam::scalar timeEnd () const
Return the maximum end-of-injection time.
Definition at line 126 of file InjectionModelList.C.
References forAll, Foam::max(), and InjectionModelList< CloudType >::volumeToInject().
Referenced by InjectionModelList< Foam::KinematicCloud< CloudType > >::clone().
Foam::scalar volumeToInject (const scalar time0, const scalar time1)
Volume of parcels to introduce relative to SOI.
Definition at line 140 of file InjectionModelList.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by InjectionModelList< Foam::KinematicCloud< CloudType > >::clone(), and InjectionModelList< CloudType >::timeEnd().
Foam::scalar averageParcelMass ()
Return the average parcel mass.
Definition at line 156 of file InjectionModelList.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by InjectionModelList< Foam::KinematicCloud< CloudType > >::clone().
void updateMesh ()
Set injector locations when mesh is updated.
Definition at line 172 of file InjectionModelList.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by InjectionModelList< Foam::KinematicCloud< CloudType > >::clone().
void inject (TrackData & td)
Main injection loop.
Definition at line 183 of file InjectionModelList.C.
References forAll, InjectionModelList< CloudType >::injectSteadyState(), and UPtrList< T >::operator[]().
Referenced by InjectionModelList< Foam::KinematicCloud< CloudType > >::clone().
void injectSteadyState (TrackData & td, const scalar trackTime)
Main injection loop - steady-state.
Definition at line 195 of file InjectionModelList.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by InjectionModelList< Foam::KinematicCloud< CloudType > >::clone(), and InjectionModelList< CloudType >::inject().
void info (Ostream & os) virtual
Write injection info to stream.
Definition at line 208 of file InjectionModelList.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by InjectionModelList< Foam::KinematicCloud< CloudType > >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModelList.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/InjectionModel/InjectionModelList.C