OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
interpolationLookUpTable< Type > Class Template Reference
A list of lists. Interpolates based on the first dimension. The values must be positive and monotonically increasing in each dimension.
Public Member Functions
interpolationLookUpTable ()
Construct null.
interpolationLookUpTable (const fileName &, const word &instance, const objectRegistry &)
Construct given the name of the file containing the table of data.
interpolationLookUpTable (const dictionary &)
Construct from dictionary.
interpolationLookUpTable (const interpolationLookUpTable &)
Construct copy.
bool found (const word &fieldName) const
Return true if the field exists in the table.
const List< scalar > & lookUp (const scalar)
Return the output list given a single input scalar.
void write (Ostream &, const fileName &, const word &instance, const objectRegistry &) const
Write lookup table to filename.
label findFieldIndex (const word &fieldName) const
Return the index of a field by name.
const List< dictionary > & output () const
Return const access to the output dictionaries.
const List< dictionary > & entries () const
Return const access tp the dictionary entries.
const List< scalar > & min () const
Return const access to the list of min dimensions.
const List< label > & dim () const
Return const access to the list of dimensions.
const List< scalar > & delta () const
Return const access to the deltas in each dimension.
const List< scalar > & max () const
Return const access to the list of max dimensions.
word tableName () const
Return const access to the table name.
const scalarField & operator[] (const label) const
Return an element of constant List<scalar, Type>
scalarField & operator[] (const label)
Return an element of List<scalar, Type>
Public Member Functions inherited from List< scalarField >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const scalarField &)
Construct with given size and value for all elements.
List (const List< scalarField > &)
Copy constructor.
List (const Xfer< List< scalarField >> &)
Construct by transferring the parameter contents.
List (List< scalarField > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< scalarField > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< scalarField, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< scalarField > &)
Construct as copy of PtrList<T>
List (const SLList< scalarField > &)
Construct as copy of SLList<T>
List (const UIndirectList< scalarField > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< scalarField > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< scalarField > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const scalarField &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const scalarField &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const scalarField &)
Append an element at the end of the list.
void append (const UList< scalarField > &)
Append a List at the end of this list.
void append (const UIndirectList< scalarField > &)
Append a UIndirectList at the end of this list.
void transfer (List< scalarField > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< scalarField, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< scalarField > &)
Transfer the contents of the argument List into this list.
Xfer< List< scalarField > > xfer ()
Transfer contents to the Xfer container.
scalarField & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< scalarField > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< scalarField > &)
Assignment operator. Takes linear time.
void operator= (const SLList< scalarField > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< scalarField > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< scalarField > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const scalarField &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< T > &)
Assign elements to those from UList.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Additional Inherited Members
Public Types inherited from List< scalarField >
typedef SubList< scalarField > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from List< scalarField >
static const List< scalarField > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< scalarField >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::interpolationLookUpTable< Type >
A list of lists. Interpolates based on the first dimension. The values must be positive and monotonically increasing in each dimension.
Note
Accessing an empty list results in an error.
Accessing a list with a single element always returns the same value.
Source files
interpolationLookUpTable.H
interpolationLookUpTable.C
Definition at line 61 of file interpolationLookUpTable.H.
Constructor & Destructor Documentation
interpolationLookUpTable ()
Construct null.
Definition at line 229 of file interpolationLookUpTable.C.
Referenced by interpolationLookUpTable< Type >::interpolationLookUpTable().
interpolationLookUpTable (const fileName & fn, const word & instance, const objectRegistry & obr)
Construct given the name of the file containing the table of data.
Definition at line 238 of file interpolationLookUpTable.C.
References interpolationLookUpTable< Type >::interpolationLookUpTable().
interpolationLookUpTable (const dictionary & dict)
Construct from dictionary.
Definition at line 282 of file interpolationLookUpTable.C.
References interpolationLookUpTable< Type >::dim(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, UList< T >::operator[](), List< T >::size(), and interpolationLookUpTable< Type >::write().
interpolationLookUpTable (const interpolationLookUpTable< Type > & interpTable)
Construct copy.
Definition at line 262 of file interpolationLookUpTable.C.
References interpolationLookUpTable< Type >::interpolationLookUpTable().
Member Function Documentation
bool found (const word & fieldName) const
Return true if the field exists in the table.
Definition at line 429 of file interpolationLookUpTable.C.
References HashTable< T, Key, Hash >::found().
const Foam::scalarList & lookUp (const scalar retvals)
Return the output list given a single input scalar.
Definition at line 437 of file interpolationLookUpTable.C.
References forAll, Foam::min(), UList< T >::operator[](), and List< scalarField >::size().
void write (Ostream & os, const fileName & fn, const word & instance, const objectRegistry & obr) const
Write lookup table to filename.
Definition at line 336 of file interpolationLookUpTable.C.
References token::END_STATEMENT, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, List< scalarField >::size(), IOobject::writeHeader(), and Ostream::writeKeyword().
Referenced by interpolationLookUpTable< Type >::interpolationLookUpTable().
Foam::label findFieldIndex (const word & fieldName) const inline
Return the index of a field by name.
Definition at line 29 of file interpolationLookUpTableI.H.
const Foam::List< Foam::dictionary > & output () const inline
Return const access to the output dictionaries.
Definition at line 39 of file interpolationLookUpTableI.H.
const Foam::List< Foam::dictionary > & entries () const inline
Return const access tp the dictionary entries.
Definition at line 47 of file interpolationLookUpTableI.H.
const Foam::List< Foam::scalar > & min () const inline
Return const access to the list of min dimensions.
Definition at line 55 of file interpolationLookUpTableI.H.
const Foam::List< Foam::label > & dim () const inline
Return const access to the list of dimensions.
Definition at line 63 of file interpolationLookUpTableI.H.
Referenced by interpolationLookUpTable< Type >::interpolationLookUpTable().
const Foam::List< Foam::scalar > & delta () const inline
Return const access to the deltas in each dimension.
Definition at line 71 of file interpolationLookUpTableI.H.
const Foam::List< Foam::scalar > & max () const inline
Return const access to the list of max dimensions.
Definition at line 79 of file interpolationLookUpTableI.H.
Foam::word tableName () const inline
Return const access to the table name.
Definition at line 86 of file interpolationLookUpTableI.H.
const Foam::scalarField & operator[] (const label i) const
Return an element of constant List<scalar, Type>
Definition at line 403 of file interpolationLookUpTable.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, Foam::nl, UList< T >::operator[](), and List< scalarField >::size().
Foam::scalarField & operator[] (const label i)
Return an element of List<scalar, Type>
Definition at line 377 of file interpolationLookUpTable.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, Foam::nl, UList< T >::operator[](), and List< scalarField >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationLookUpTable/interpolationLookUpTable.H
src/OpenFOAM/interpolations/interpolationLookUpTable/interpolationLookUpTable.C
src/OpenFOAM/interpolations/interpolationLookUpTable/interpolationLookUpTableI.H