OpenFOAM: IOMap< T > Class Template Reference
IOMap< T > Class Template Reference
A Map of objects of type <T> with automated input and output.
Public Member Functions
TypeName ("Map")
Runtime type information.
IOMap (const IOobject &)
Construct from IOobject.
IOMap (const IOobject &, const label)
Construct from IOobject and size of Map.
IOMap (const IOobject &, const Map< T > &)
Construct from IOobject and a Map.
IOMap (const IOobject &, const Xfer< Map< T >> &)
Construct by transferring the Map contents.
virtual ~IOMap ()
Destructor.
bool writeData (Ostream &) const
Pure virtual writaData function.
void operator= (const IOMap< T > &)
Assignment of other IOMap's entries to this IOMap.
void operator= (const Map< T > &)
Assignment of other Map's entries to this IOMap.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from Map< T >
Map (const label size=128)
Construct given initial size.
Map (Istream &is)
Construct from Istream.
Map (const Map< T > &map)
Construct as copy.
Map (const Xfer< Map< T >> &map)
Construct by transferring the parameter contents.
Map (const Xfer< HashTable< T, label, Hash< label >>> &map)
Construct by transferring the parameter contents.
Public Member Functions inherited from HashTable< T, label, Hash< label > >
bool set (const label &, const T &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< T, label, Hash< label > > &)
Construct as copy.
HashTable (const Xfer< HashTable< T, label, Hash< label > >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< label, T >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const label &) const
Return true if hashedEntry is found in table.
iterator find (const label &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const label &) const
Find and return an const_iterator set at the hashedEntry.
List< label > toc () const
Return the table of contents.
List< label > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const label &, const T &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const label &)
Erase a hashedEntry specified by the given key.
label erase (const UList< label > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, label, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< T, label, Hash< label > > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< T, label, Hash< label > > > xfer ()
Transfer contents to the Xfer container.
T & operator[] (const label &)
Find and return a hashedEntry.
const T & operator[] (const label &) const
Find and return a hashedEntry.
T & operator() (const label &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< T, label, Hash< label > > &)
Assignment.
void operator= (std::initializer_list< Tuple2< label, T >>)
Assignment to an initializer list.
bool operator== (const HashTable< T, label, Hash< label > > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< T, label, Hash< label > > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from Map< T >
typedef HashTable< T, label, Hash< label > >::iterator iterator
typedef HashTable< T, label, Hash< label > >::const_iterator const_iterator
Public Types inherited from HashTable< T, label, Hash< label > >
typedef T value_type
Type of values the HashTable contains.
typedef T & reference
Type that can be used for storing into HashTable::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class T>
class Foam::IOMap< T >
A Map of objects of type <T> with automated input and output.
Source files
IOMap.H
IOMap.C
Definition at line 50 of file IOMap.H.
Constructor & Destructor Documentation
IOMap (const IOobject & io)
Construct from IOobject.
Definition at line 31 of file IOMap.C.
References regIOobject::close(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, IOobject::READ_IF_PRESENT, IOobject::readOpt(), and regIOobject::readStream().
IOMap (const IOobject & io, const label size)
Construct from IOobject and size of Map.
Definition at line 50 of file IOMap.C.
References regIOobject::close(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), and setSize().
IOMap (const IOobject & io, const Map< T > & map)
Construct from IOobject and a Map.
Definition at line 74 of file IOMap.C.
References regIOobject::close(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, HashTable< T, label, Hash< label > >::operator=(), IOobject::READ_IF_PRESENT, IOobject::readOpt(), and regIOobject::readStream().
IOMap (const IOobject & io, const Xfer< Map< T >> & map)
Construct by transferring the Map contents.
Definition at line 98 of file IOMap.C.
References regIOobject::close(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), and HashTable< T, label, Hash< label > >::transfer().
~IOMap () virtual
Destructor.
Definition at line 122 of file IOMap.C.
Member Function Documentation
TypeName ("Map")
Runtime type information.
bool writeData (Ostream &) const virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 129 of file IOMap.C.
void operator= (const IOMap< T > & rhs)
Assignment of other IOMap's entries to this IOMap.
Definition at line 138 of file IOMap.C.
References HashTable< T, label, Hash< label > >::operator=().
void operator= (const Map< T > & rhs)
Assignment of other Map's entries to this IOMap.
Definition at line 145 of file IOMap.C.
References HashTable< T, label, Hash< label > >::operator=().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOobjects/IOMap/IOMap.H
src/OpenFOAM/db/IOobjects/IOMap/IOMap.C