OpenFOAM: isoSurface Class Reference
isoSurface Class Reference
A surface formed by the iso value. After "Regularised Marching Tetrahedra: improved iso-surface extraction", G.M. Treece, R.W. Prager and A.H. Gee.
Public Member Functions
TypeName ("isoSurface")
Runtime type information.
isoSurface (const volScalarField &cellIsoVals, const scalarField &pointIsoVals, const scalar iso, const bool regularise, const scalar mergeTol=1e-6)
Construct from cell values and point values. Uses boundaryField.
const labelList & meshCells () const
For every triangle the original cell in mesh.
template<class Type >
tmp< Field< Type > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &cCoords, const Field< Type > &pCoords) const
Interpolates cCoords,pCoords. Uses the references to the original.
template<class Type >
Foam::tmp< Foam::SlicedGeometricField< Type, Foam::fvPatchField, Foam::slicedFvPatchField, Foam::volMesh > > adaptPatchFields (const GeometricField< Type, fvPatchField, volMesh > &fld) const
template<class Type >
Foam::label generateFaceTriPoints (const volScalarField &cVals, const scalarField &pVals, const GeometricField< Type, fvPatchField, volMesh > &cCoords, const Field< Type > &pCoords, const DynamicList< Type > &snappedPoints, const labelList &snappedCc, const labelList &snappedPoint, const label facei, const scalar neiVal, const Type &neiPt, const bool hasNeiSnap, const Type &neiSnapPt, DynamicList< Type > &triPoints, DynamicList< label > &triMeshCells) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const label nPoints, const labelList &triPointMergeMap, const DynamicList< Type > &unmergedValues)
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &cCoords, const Field< Type > &pCoords) const
Public Member Functions inherited from triSurface
ClassName ("triSurface")
Runtime type information.
triSurface ()
Construct null.
triSurface (const List< labelledTri > &, const geometricSurfacePatchList &, const pointField &)
Construct from triangles, patches, points.
triSurface (List< labelledTri > &, const geometricSurfacePatchList &, pointField &, const bool reuse)
Construct from triangles, patches, points. Reuse storage.
triSurface (const Xfer< List< labelledTri >> &, const geometricSurfacePatchList &, const Xfer< List< point >> &)
Construct from triangles, patches, points.
triSurface (const List< labelledTri > &, const pointField &)
Construct from triangles, points. Set patchnames to default.
triSurface (const triFaceList &, const pointField &)
Construct from triangles, points. Set region to 0 and default.
triSurface (const fileName &)
Construct from file name (uses extension to determine type)
triSurface (Istream &)
Construct from Istream.
triSurface (const Time &d)
Construct from objectRegistry.
triSurface (const triSurface &)
Construct as copy.
~triSurface ()
Destructor.
void clearOut ()
void clearTopology ()
void clearPatchMeshAddr ()
const geometricSurfacePatchList & patches () const
geometricSurfacePatchList & patches ()
const labelListList & sortedEdgeFaces () const
Return edge-face addressing sorted (for edges with more than.
const labelList & edgeOwner () const
If 2 face neighbours: label of face where ordering of edge.
virtual void movePoints (const pointField &)
Move points.
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void checkTriangles (const bool verbose)
Check/remove duplicate/degenerate triangles.
void checkEdges (const bool verbose)
Check triply (or more) connected edges.
void cleanup (const bool verbose)
Remove non-valid triangles.
void markZone (const boolList &borderEdge, const label facei, const label currentZone, labelList &faceZone) const
Fill faceZone with currentZone for every face reachable.
label markZones (const boolList &borderEdge, labelList &faceZone) const
(size and) fills faceZone with zone of face. Zone is area
void subsetMeshMap (const boolList &include, labelList &pointMap, labelList &faceMap) const
'Create' sub mesh, including only faces for which
triSurface subsetMesh (const boolList &include, labelList &pointMap, labelList &faceMap) const
Return new surface. Returns pointMap, faceMap from.
void write (Ostream &) const
Write to Ostream in simple FOAM format.
void write (const fileName &, const bool sortByRegion=false) const
Generic write routine. Chooses writer based on extension.
void write (const Time &) const
Write to database.
void writeDX (const scalarField &, Ostream &) const
Write to Ostream in OpenDX format.
void writeDX (const vectorField &, Ostream &) const
void writeStats (Ostream &) const
Write some statistics.
void operator= (const triSurface &)
Public Member Functions inherited from PrimitivePatch< labelledTri,::Foam::List, pointField, point >
PrimitivePatch (const ::Foam::List< labelledTri > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (const Xfer< ::Foam::List< labelledTri >> &faces, const Xfer< List< point >> &points)
Construct from components.
PrimitivePatch (::Foam::List< labelledTri > &faces, Field< point > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< labelledTri,::Foam::List, pointField, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< labelledTri > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceNormals () const
Return face normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< labelledTri,::Foam::List, pointField, point > &)
Assignment.
Public Member Functions inherited from List< labelledTri >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const labelledTri &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< labelledTri > &)
Copy constructor.
List (const Xfer< List< labelledTri >> &)
Construct by transferring the parameter contents.
List (List< labelledTri > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< labelledTri > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< labelledTri, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< labelledTri > &)
Construct as copy of PtrList<T>
List (const SLList< labelledTri > &)
Construct as copy of SLList<T>
List (const UIndirectList< labelledTri > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< labelledTri > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< labelledTri > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const labelledTri &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const labelledTri &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const labelledTri &)
Append an element at the end of the list.
void append (const UList< labelledTri > &)
Append a List at the end of this list.
void append (const UIndirectList< labelledTri > &)
Append a UIndirectList at the end of this list.
void transfer (List< labelledTri > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< labelledTri, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< labelledTri > &)
Transfer the contents of the argument List into this list.
Xfer< List< labelledTri > > xfer ()
Transfer contents to the Xfer container.
labelledTri & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< labelledTri > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< labelledTri > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< labelledTri > &)
Assignment operator. Takes linear time.
void operator= (const SLList< labelledTri > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< labelledTri > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< labelledTri > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const labelledTri &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Friends
class isoSurfaceCell
Declare friendship with isoSurfaceCell to share some functionality.
Additional Inherited Members
Public Types inherited from triSurface
typedef bool BoundaryMesh
Placeholder only, but do not remove - it is needed for GeoMesh.
Public Types inherited from PrimitivePatch< labelledTri,::Foam::List, pointField, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef labelledTri FaceType
typedef ::Foam::List< labelledTri > FaceListType
typedef pointField PointFieldType
Public Types inherited from List< labelledTri >
typedef SubList< labelledTri > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from triSurface
static fileName triSurfInstance (const Time &)
Name of triSurface directory to use.
Static Public Member Functions inherited from List< labelledTri >
static const List< labelledTri > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from triSurface
pointField & storedPoints ()
Non-const access to global points.
List< Face > & storedFaces ()
Non-const access to the faces.
Protected Member Functions inherited from List< labelledTri >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
A surface formed by the iso value. After "Regularised Marching Tetrahedra: improved iso-surface extraction", G.M. Treece, R.W. Prager and A.H. Gee.
Note:
does tets without using cell centres/cell values. Not tested.
regularisation can create duplicate triangles/non-manifold surfaces. Current handling of those is bit ad-hoc for now and not perfect.
regularisation does not do boundary points so as to preserve the boundary perfectly.
uses geometric merge with fraction of bounding box as distance.
triangles can be between two cell centres so constant sampling does not make sense.
on empty patches behaves like zero gradient.
does not do 2D correctly, creates non-flat iso surface.
on processor boundaries might two overlapping (identical) triangles (one from either side)
The handling on coupled patches is a bit complex. All fields (values and coordinates) get rewritten so
empty patches get zerogradient (value) and facecentre (coordinates)
separated processor patch faces get interpolate (value) and facecentre (coordinates). (this is already the default for cyclics)
non-separated processor patch faces keep opposite value and cell centre
Now the triangle generation on non-separated processor patch faces can use the neighbouring value. Any separated processor face or cyclic face gets handled just like any boundary face.
Source files
isoSurface.H
isoSurface.C
Definition at line 83 of file isoSurface.H.
Constructor & Destructor Documentation
isoSurface (const volScalarField & cellIsoVals, const scalarField & pointIsoVals, const scalar iso, const bool regularise, const scalar mergeTol = 1e-6)
Construct from cell values and point values. Uses boundaryField.
for boundary values. Holds reference to cellIsoVals and pointIsoVals.
Definition at line 1167 of file isoSurface.C.
References polyPatch::coupled(), Foam::dimLength, Foam::endl(), forAll, Foam::max(), Foam::min(), IOobject::name(), Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, UList< T >::operator, patchi, polyPatch::patchSlice(), fileName::path(), Foam::Pout, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), PtrList< T >::set(), List< T >::setSize(), List< T >::size(), and polyPatch::start().
Member Function Documentation
TypeName ("isoSurface")
Runtime type information.
const labelList& meshCells () const inline
For every triangle the original cell in mesh.
Definition at line 373 of file isoSurface.H.
References Foam::MULES::interpolate().
tmp<Field<Type> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & cCoords, const Field< Type > & pCoords) const
Interpolates cCoords,pCoords. Uses the references to the original.
fields used to create the iso surface.
Foam::tmp<Foam::SlicedGeometricField< Type, Foam::fvPatchField, Foam::slicedFvPatchField, Foam::volMesh> > adaptPatchFields (const GeometricField< Type, fvPatchField, volMesh > & fld) const
Definition at line 44 of file isoSurfaceTemplates.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), IOobject::db(), f(), forAll, IOobject::instance(), Foam::mag(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), patches, patchi, fvPatchField< Type >::patchInternalField(), fvPatchField< Type >::patchNeighbourField(), PrimitivePatch< labelledTri,::Foam::List, pointField, point >::points(), tmp< T >::ref(), s(), PtrList< T >::set(), List< Type >::setSize(), List< T >::size(), UList< T >::size(), Foam::Swap(), and surfaceInterpolation::weights().
Foam::label generateFaceTriPoints (const volScalarField & cVals, const scalarField & pVals, const GeometricField< Type, fvPatchField, volMesh > & cCoords, const Field< Type > & pCoords, const DynamicList< Type > & snappedPoints, const labelList & snappedCc, const labelList & snappedPoint, const label facei, const scalar neiVal, const Type & neiPt, const bool hasNeiSnap, const Type & neiSnapPt, DynamicList< Type > & triPoints, DynamicList< label > & triMeshCells) const
Definition at line 434 of file isoSurfaceTemplates.C.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), polyPatch::coupled(), Foam::endl(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), forAll, primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), primitiveMesh::nPoints(), triSurface::patches(), patchi, DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), List< T >::size(), List< Type >::size(), polyPatch::start(), syncTools::swapBoundaryFaceList(), and Foam::Zero.
Foam::tmp<Foam::Field<Type> > interpolate (const label nPoints, const labelList & triPointMergeMap, const DynamicList< Type > & unmergedValues)
Definition at line 738 of file isoSurfaceTemplates.C.
References forAll, tmp< T >::ref(), List< Type >::size(), and Foam::Zero.
Foam::tmp<Foam::Field<Type> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & cCoords, const Field< Type > & pCoords) const
Definition at line 775 of file isoSurfaceTemplates.C.
References Foam::constant::physicoChemical::c2, primitiveMesh::nCells(), primitiveMesh::nPoints(), PrimitivePatch< labelledTri,::Foam::List, pointField, point >::points(), and List< labelledTri >::size().
Friends And Related Function Documentation
friend class isoSurfaceCell friend
Declare friendship with isoSurfaceCell to share some functionality.
Definition at line 348 of file isoSurface.H.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/isoSurface/isoSurface.H
src/sampling/sampledSurface/isoSurface/isoSurface.C
src/sampling/sampledSurface/isoSurface/isoSurfaceTemplates.C