OpenFOAM: ISAT< CompType, ThermoType > Class Template Reference
ISAT< CompType, ThermoType > Class Template Reference
Implementation of the ISAT (In-situ adaptive tabulation), for chemistry calculation.
Public Member Functions
TypeName ("ISAT")
Runtime type information.
ISAT (const dictionary &chemistryProperties, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from dictionary.
virtual ~ISAT ()
binaryTree< CompType, ThermoType > & chemisTree ()
const scalarField & scaleFactor () const
virtual label size ()
Return the size of the binary tree.
virtual void writePerformance ()
virtual bool retrieve (const Foam::scalarField &phiq, scalarField &Rphiq)
Find the closest stored leaf of phiQ and store the result in.
virtual bool add (const scalarField &phiq, const scalarField &Rphiq, const scalar rho)
Add information to the tabulation.
virtual bool update ()
Public Member Functions inherited from chemistryTabulationMethod< CompType, ThermoType >
TypeName ("chemistryTabulationMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, chemistryTabulationMethod, dictionary,(const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryTabulationMethod (const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from components.
virtual ~chemistryTabulationMethod ()
Destructor.
bool active ()
bool log ()
scalar tolerance () const
Additional Inherited Members
Static Public Member Functions inherited from chemistryTabulationMethod< CompType, ThermoType >
static autoPtr< chemistryTabulationMethod > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes inherited from chemistryTabulationMethod< CompType, ThermoType >
const dictionary & dict_
const dictionary coeffsDict_
Switch active_
Is tabulation active?
Switch log_
Switch to select performance logging.
TDACChemistryModel< CompType, ThermoType > & chemistry_
scalar tolerance_
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryTabulationMethods::ISAT< CompType, ThermoType >
Implementation of the ISAT (In-situ adaptive tabulation), for chemistry calculation.
Reference:
    Pope, S. B. (1997).
    Computationally efficient implementation of combustion chemistry using
    in situ adaptive tabulation.
    Combustion Theory and Modelling, 1, 41-63.
Definition at line 57 of file ISAT.H.
Constructor & Destructor Documentation
ISAT (const dictionary & chemistryProperties, TDACChemistryModel< CompType, ThermoType > & chemistry)
Construct from dictionary.
Definition at line 33 of file ISAT.C.
References Foam::log(), TDACChemistryModel< CompType, ThermoType >::logFile(), and readScalar.
~ISAT () virtual
Definition at line 122 of file ISAT.C.
References chemPointISAT< CompType, ThermoType >::A(), chemistryTabulationMethod< CompType, ThermoType >::active(), LList< LListBase, T >::begin(), chemPointISAT< CompType, ThermoType >::checkSolution(), chemPointISAT< CompType, ThermoType >::completeToSimplifiedIndex(), LList< LListBase, T >::end(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, LList< LListBase, T >::first(), chemPointISAT< CompType, ThermoType >::grow(), LUscalarMatrix::inv(), LList< LListBase, T >::last(), Foam::log(), Foam::max(), chemPointISAT< CompType, ThermoType >::nActiveSpecies(), chemPointISAT< CompType, ThermoType >::nGrowth(), chemPointISAT< CompType, ThermoType >::phi(), Foam::constant::electromagnetic::phi0, ISAT< CompType, ThermoType >::retrieve(), chemPointISAT< CompType, ThermoType >::Rphi(), List< T >::size(), chemPointISAT< CompType, ThermoType >::timeTag(), chemPointISAT< CompType, ThermoType >::toRemove(), and x.
Member Function Documentation
TypeName ("ISAT< CompType, ThermoType >")
Runtime type information.
binaryTree<CompType, ThermoType>& chemisTree () inline
Definition at line 196 of file ISAT.H.
const scalarField& scaleFactor () const inline
Definition at line 201 of file ISAT.H.
virtual label size () inline virtual
Return the size of the binary tree.
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 207 of file ISAT.H.
References ISAT< CompType, ThermoType >::add(), ISAT< CompType, ThermoType >::retrieve(), binaryTree< CompType, ThermoType >::size(), and ISAT< CompType, ThermoType >::writePerformance().
void writePerformance () virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 600 of file ISAT.C.
References Foam::endl(), and Foam::log().
Referenced by ISAT< CompType, ThermoType >::size().
bool retrieve (const Foam::scalarField & phiq, scalarField & Rphiq) virtual
Find the closest stored leaf of phiQ and store the result in.
RphiQ or return false.
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 413 of file ISAT.C.
References ISAT< CompType, ThermoType >::add(), chemPointISAT< CompType, ThermoType >::inEOA(), Foam::constant::electromagnetic::phi0, chemPointISAT< CompType, ThermoType >::timeTag(), and chemPointISAT< CompType, ThermoType >::toRemove().
Referenced by ISAT< CompType, ThermoType >::size(), and ISAT< CompType, ThermoType >::~ISAT().
bool add (const scalarField & phiq, const scalarField & Rphiq, const scalar rho) virtual
Add information to the tabulation.
This function can grow an existing point or add a new leaf to the binary tree Input : phiq the new composition to store Rphiq the mapping of the new composition point
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 496 of file ISAT.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::deleteDemandDrivenData(), forAll, phi, Matrix< Form, Type >::size(), and Foam::Zero.
Referenced by ISAT< CompType, ThermoType >::retrieve(), and ISAT< CompType, ThermoType >::size().
virtual bool update () inline virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 233 of file ISAT.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/ISAT.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/ISAT.C