OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
keyType Class Reference
A class for handling keywords in dictionaries.
Public Member Functions
keyType ()
Construct null.
keyType (const keyType &)
Construct as copy.
keyType (const word &)
Construct as copy of word. Not treated as a regular expression.
keyType (const string &)
Construct as copy of string. Treat as regular expression.
keyType (const char *)
Construct as copy of character array.
keyType (const std::string &, const bool isPattern)
Construct as copy of std::string with specified treatment.
keyType (Istream &)
Construct from Istream.
bool isPattern () const
Should be treated as a match rather than a literal string.
bool match (const std::string &, bool literalMatch=false) const
Smart match as regular expression or as a string.
void operator= (const keyType &)
Assignment operator.
void operator= (const word &)
Assign as word, not as non regular expression.
void operator= (const string &)
Assign as regular expression.
void operator= (const char *)
Assign as word, not as non regular expression.
Public Member Functions inherited from word
word ()
Construct null.
word (const word &)
Construct as copy.
word (const char *, const bool doStripInvalid=true)
Construct as copy of character array.
word (const char *, const size_type, const bool doStripInvalid)
Construct as copy with a maximum number of characters.
word (const string &, const bool doStripInvalid=true)
Construct as copy of string.
word (const std::string &, const bool doStripInvalid=true)
Construct as copy of std::string.
word (Istream &)
Construct from Istream.
void operator= (const word &)
void operator= (const string &)
void operator= (const std::string &)
void operator= (const char *)
Public Member Functions inherited from string
string ()
Construct null.
string (const std::string &)
Construct from std::string.
string (const char *)
Construct as copy of character array.
string (const char *, const size_type)
Construct as copy of specified number of characters.
string (const char)
Construct from a single character.
string (Istream &)
Construct from Istream.
size_type count (const char) const
Count and return the number of a given character in the string.
bool match (const std::string &) const
True when strings match literally.
string & replace (const string &oldStr, const string &newStr, size_type start=0)
Replace first occurence of sub-string oldStr with newStr.
string & replaceAll (const string &oldStr, const string &newStr, size_type start=0)
Replace all occurences of sub-string oldStr with newStr.
string & expand (const bool allowEmpty=false)
Expand initial tildes and all occurences of environment variables.
bool removeRepeated (const char)
Remove repeated characters returning true if string changed.
string removeRepeated (const char) const
Return string with repeated characters removed.
bool removeTrailing (const char)
Remove trailing character returning true if string changed.
string removeTrailing (const char) const
Return string with trailing character removed.
string operator() (const size_type i, const size_type n) const
Return the sub-string from the i-th character for n characters.
string operator() (const size_type n) const
Return the sub-string from the first character for n characters.
template<class String >
Foam::string quotemeta (const string &str, const char quote)
Static Public Attributes
static const keyType null
An empty keyType.
Static Public Attributes inherited from word
static const char *const typeName = "word"
static int debug
static const word null
An empty word.
Static Public Attributes inherited from string
static const char *const typeName = "string"
static int debug
static const string null
An empty string.
Friends
Istream & operator>> (Istream &, keyType &)
Ostream & operator<< (Ostream &, const keyType &)
Additional Inherited Members
Static Public Member Functions inherited from word
static bool valid (char)
Is this character valid for a word.
Static Public Member Functions inherited from string
template<class String >
static bool valid (const string &)
Is this string type valid?
template<class String >
static bool meta (const string &, const char quote='\\')
Does this string have particular meta-characters?
template<class String >
static bool stripInvalid (string &)
Strip invalid characters from the given string.
template<class String >
static String validate (const string &)
Return a valid String from the given string.
template<class String >
static string quotemeta (const string &, const char quote='\\')
Return a String with quoted meta-characters from the given string.
Detailed Description
A class for handling keywords in dictionaries.
A keyType is the keyword of a dictionary. It differs from word in that it accepts patterns (regular expressions).
Source files
keyType.H
keyType.C
Definition at line 56 of file keyType.H.
Constructor & Destructor Documentation
keyType () inline
Construct null.
Definition at line 28 of file keyTypeI.H.
Referenced by keyType::keyType().
keyType (const keyType & s) inline
Construct as copy.
Definition at line 35 of file keyTypeI.H.
keyType (const word & s) inline
Construct as copy of word. Not treated as a regular expression.
Definition at line 42 of file keyTypeI.H.
keyType (const string & s) inline
Construct as copy of string. Treat as regular expression.
Definition at line 49 of file keyTypeI.H.
keyType (const char * s) inline
Construct as copy of character array.
Not treated as a regular expression
Definition at line 56 of file keyTypeI.H.
References keyType::keyType().
keyType (const std::string & s, const bool isPattern) inline
Construct as copy of std::string with specified treatment.
Definition at line 64 of file keyTypeI.H.
keyType (Istream & is)
Construct from Istream.
Treat as regular expression if surrounded by quotation marks.
Definition at line 40 of file keyType.C.
References keyType::match().
Member Function Documentation
bool isPattern () const inline
Should be treated as a match rather than a literal string.
Definition at line 76 of file keyTypeI.H.
Referenced by dictionary::add(), dictionary::changeKeyword(), coordinateSystems::findIndex(), ZoneMesh< ZoneType, MeshType >::findIndex(), polyBoundaryMesh::findIndex(), coordinateSystems::findIndices(), ZoneMesh< ZoneType, MeshType >::findIndices(), polyBoundaryMesh::findIndices(), wordRe::operator=(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), wordRe::wordRe(), Ostream::write(), and Ostream::writeKeyword().
bool match (const std::string & str, bool literalMatch = false) const
Smart match as regular expression or as a string.
Optionally force a literal match only
Definition at line 52 of file keyType.C.
References IOstream::check(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, token::good(), token::info(), token::isString(), token::isWord(), regExp::match(), Foam::operator<<(), Foam::operator>>(), IOstream::setBad(), token::stringToken(), token::wordToken(), and Ostream::write().
Referenced by keyType::keyType().
void operator= (const keyType & s) inline
Assignment operator.
Definition at line 84 of file keyTypeI.H.
void operator= (const word & s) inline
Assign as word, not as non regular expression.
Definition at line 92 of file keyTypeI.H.
References word::operator=().
void operator= (const string & s) inline
Assign as regular expression.
Definition at line 99 of file keyTypeI.H.
void operator= (const char * s) inline
Assign as word, not as non regular expression.
Definition at line 107 of file keyTypeI.H.
Friends And Related Function Documentation
Istream& operator>> (Istream & , keyType &) friend
Ostream& operator<< (Ostream & , const keyType &) friend
Member Data Documentation
const Foam::keyType null static
An empty keyType.
Definition at line 75 of file keyType.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/keyType/keyType.H
src/OpenFOAM/primitives/strings/keyType/keyType.C
src/OpenFOAM/primitives/strings/keyType/keyTypeI.H