OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
labelBits Class Reference
A 29bits label and 3bits direction packed into single label.
Public Member Functions
labelBits ()
Construct null.
labelBits (const label val, const direction bits)
Construct from components.
labelBits (Istream &is)
Construct from Istream.
label val () const
direction bits () const
void setVal (const label val)
void setBits (const direction bits)
Friends
bool operator== (const labelBits &a, const labelBits &b)
bool operator!= (const labelBits &a, const labelBits &b)
Istream & operator>> (Istream &is, labelBits &lb)
Ostream & operator<< (Ostream &os, const labelBits &lb)
Detailed Description
A 29bits label and 3bits direction packed into single label.
Source files
labelBits.H
Definition at line 51 of file labelBits.H.
Constructor & Destructor Documentation
labelBits () inline
Construct null.
Definition at line 78 of file labelBits.H.
labelBits (const label val, const direction bits) inline
Construct from components.
Definition at line 82 of file labelBits.H.
labelBits (Istream & is) inline
Construct from Istream.
Definition at line 88 of file labelBits.H.
Member Function Documentation
label val () const inline
Definition at line 97 of file labelBits.H.
Referenced by indexedOctree< Foam::treeDataFace >::getContent(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getContent(), indexedOctree< Foam::treeDataFace >::getNode(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getNode(), indexedOctree< Foam::treeDataFace >::isContent(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::isContent(), indexedOctree< Foam::treeDataFace >::isEmpty(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::isEmpty(), indexedOctree< Foam::treeDataFace >::isNode(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::isNode(), and labelBits::setBits().
direction bits () const inline
Definition at line 102 of file labelBits.H.
Referenced by indexedOctree< Foam::treeDataFace >::getOctant(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), and labelBits::setVal().
void setVal (const label val) inline
Definition at line 107 of file labelBits.H.
References labelBits::bits().
void setBits (const direction bits) inline
Definition at line 112 of file labelBits.H.
References labelBits::val().
Friends And Related Function Documentation
bool operator== (const labelBits & a, const labelBits & b) friend
Definition at line 120 of file labelBits.H.
bool operator!= (const labelBits & a, const labelBits & b) friend
Definition at line 125 of file labelBits.H.
Istream& operator>> (Istream & is, labelBits & lb) friend
Definition at line 132 of file labelBits.H.
Ostream& operator<< (Ostream & os, const labelBits & lb) friend
Definition at line 137 of file labelBits.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/algorithms/indexedOctree/labelBits.H