OpenFOAM: kOmegaSST< TurbulenceModel, BasicTurbulenceModel > Class Template Reference
kOmegaSST< TurbulenceModel, BasicTurbulenceModel > Class Template Reference
Turbulence
Implementation of the k-omega-SST turbulence model for incompressible and compressible flows.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >
typedef Alpha alphaField
typedef Rho rhoField
typedef TransportModel transportModel
Public Member Functions
kOmegaSST (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~kOmegaSST ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
tmp< volScalarField > DkEff (const volScalarField &F1) const
Return the effective diffusivity for k.
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
Return the effective diffusivity for omega.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volScalarField > omega () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >
declareRunTimeNewSelectionTable (autoPtr, TurbulenceModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
TurbulenceModel (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct.
virtual ~TurbulenceModel ()
Destructor.
const alphaField & alpha () const
Access function to phase fraction.
const transportModel & transport () const
Access function to incompressible transport model.
tmp< volScalarField > nu () const
Return the laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity on patchi.
Protected Member Functions
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
void correctNut (const volScalarField &S2, const volScalarField &F2)
virtual void correctNut ()
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
Return k production rate.
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal &F1, const volScalarField::Internal &F2) const
Return epsilon/k which for standard RAS is betaStar*omega.
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Attributes
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
const volScalarField & y_
Wall distance.
volScalarField k_
volScalarField omega_
Protected Attributes inherited from TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >
const alphaField & alpha_
const transportModel & transport_
Additional Inherited Members
Static Public Member Functions inherited from TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >
static autoPtr< TurbulenceModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Detailed Description
template<class TurbulenceModel, class BasicTurbulenceModel>
class Foam::kOmegaSST< TurbulenceModel, BasicTurbulenceModel >
Implementation of the k-omega-SST turbulence model for incompressible and compressible flows.
Turbulence model described in:
    Menter, F. R. & Esch, T. (2001).
    Elements of Industrial Heat Transfer Prediction.
    16th Brazilian Congress of Mechanical Engineering (COBEM).
with updated coefficients from
    Menter, F. R., Kuntz, M., and Langtry, R. (2003).
    Ten Years of Industrial Experience with the SST Turbulence Model.
    Turbulence, Heat and Mass Transfer 4, ed: K. Hanjalic, Y. Nagano,
    & M. Tummers, Begell House, Inc., 625 - 632.
but with the consistent production terms from the 2001 paper as form in the 2003 paper is a typo, see
    http://turbmodels.larc.nasa.gov/sst.html
and the addition of the optional F3 term for rough walls from
    Hellsten, A. (1998).
    "Some Improvements in Menters k-omega-SST turbulence model"
    29th AIAA Fluid Dynamics Conference, AIAA-98-2554.
Note that this implementation is written in terms of alpha diffusion coefficients rather than the more traditional sigma (alpha = 1/sigma) so that the blending can be applied to all coefficuients in a consistent manner. The paper suggests that sigma is blended but this would not be consistent with the blending of the k-epsilon and k-omega models.
Also note that the error in the last term of equation (2) relating to sigma has been corrected.
Wall-functions are applied in this implementation by using equations (14) to specify the near-wall omega as appropriate.
The blending functions (15) and (16) are not currently used because of the uncertainty in their origin, range of applicability and that if y+ becomes sufficiently small blending u_tau in this manner clearly becomes nonsense.
The default model coefficients are
    kOmegaSSTCoeffs
    {
        alphaK1     0.85;
        alphaK2     1.0;
        alphaOmega1 0.5;
        alphaOmega2 0.856;
        beta1       0.075;
        beta2       0.0828;
        betaStar    0.09;
        gamma1      5/9;
        gamma2      0.44;
        a1          0.31;
        b1          1.0;
        c1          10.0;
        F3          no;
    }
Source files
kOmegaSSTBase.H
kOmegaSST.C
Definition at line 115 of file kOmegaSSTBase.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 248 of file kOmegaSSTBase.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 249 of file kOmegaSSTBase.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 250 of file kOmegaSSTBase.H.
Constructor & Destructor Documentation
kOmegaSST (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName)
Construct from components.
Definition at line 213 of file kOmegaSSTBase.C.
References Foam::bound().
virtual ~kOmegaSST () inline virtual
Destructor.
Definition at line 270 of file kOmegaSSTBase.H.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::read().
Member Function Documentation
virtual tmp<volScalarField> F1 (const volScalarField & CDkOmega) const protected virtual
virtual tmp<volScalarField> F2 () const protected virtual
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma().
virtual tmp<volScalarField> F3 () const protected virtual
virtual tmp<volScalarField> F23 () const protected virtual
tmp<volScalarField> blend (const volScalarField & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 172 of file kOmegaSSTBase.H.
References psi2.
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::alphaK(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::alphaOmega(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::beta(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma().
tmp<volScalarField::Internal> blend (const volScalarField::Internal & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 182 of file kOmegaSSTBase.H.
References psi2.
tmp<volScalarField> alphaK (const volScalarField & F1) const inline protected
Definition at line 191 of file kOmegaSSTBase.H.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::blend().
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::DkEff().
tmp<volScalarField> alphaOmega (const volScalarField & F1) const inline protected
Definition at line 196 of file kOmegaSSTBase.H.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::beta(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::blend().
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::DomegaEff().
tmp<volScalarField::Internal> beta (const volScalarField::Internal & F1) const inline protected
Definition at line 202 of file kOmegaSSTBase.H.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::blend(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma().
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::alphaOmega(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma().
tmp<volScalarField::Internal> gamma (const volScalarField::Internal & F1) const inline protected
Definition at line 210 of file kOmegaSSTBase.H.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::beta(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::blend(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correctNut(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::epsilonByk(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::F2(), Foam::constant::universal::G, kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::kSource(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::omegaSource(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::Pk(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::Qsas().
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::beta().
void correctNut (const volScalarField & S2, const volScalarField & F2) protected
Definition at line 115 of file kOmegaSSTBase.C.
References optionList::correct(), Foam::max(), options::New(), and Foam::sqrt().
void correctNut () protected virtual
Definition at line 131 of file kOmegaSSTBase.C.
References Foam::fvc::grad(), Foam::magSqr(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::Pk(), and Foam::symm().
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma().
tmp< volScalarField::Internal > Pk (const volScalarField::Internal & G) const protected virtual
Return k production rate.
Definition at line 140 of file kOmegaSSTBase.C.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::epsilonByk(), and Foam::min().
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correctNut(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma(), and kOmegaSSTLM< BasicTurbulenceModel >::Pk().
tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal & F1, const volScalarField::Internal & F2) const protected virtual
Return epsilon/k which for standard RAS is betaStar*omega.
Definition at line 151 of file kOmegaSSTBase.C.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::epsilonByk(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::Pk().
tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 162 of file kOmegaSSTBase.C.
References Foam::dimTime, and Foam::dimVolume.
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma().
tmp< fvScalarMatrix > omegaSource () const protected virtual
Definition at line 177 of file kOmegaSSTBase.C.
References Foam::dimTime, Foam::dimVolume, and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::Qsas().
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma().
tmp< fvScalarMatrix > Qsas (const volScalarField::Internal & S2, const volScalarField::Internal & gamma, const volScalarField::Internal & beta) const protected virtual
Definition at line 192 of file kOmegaSSTBase.C.
References Foam::dimTime, and Foam::dimVolume.
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::gamma(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::omegaSource().
bool read () virtual
Re-read model coefficients if they have changed.
Definition at line 389 of file kOmegaSSTBase.C.
References Foam::read().
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::~kOmegaSST().
tmp<volScalarField> DkEff (const volScalarField & F1) const inline
Return the effective diffusivity for k.
Definition at line 280 of file kOmegaSSTBase.H.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::alphaK(), and TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::nu().
tmp<volScalarField> DomegaEff (const volScalarField & F1) const inline
Return the effective diffusivity for omega.
Definition at line 289 of file kOmegaSSTBase.H.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::alphaOmega(), and TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::nu().
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Definition at line 302 of file kOmegaSSTBase.H.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::k_.
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 308 of file kOmegaSSTBase.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField().
virtual tmp<volScalarField> omega () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 327 of file kOmegaSSTBase.H.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correct(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::omega_.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Definition at line 417 of file kOmegaSSTBase.C.
References Foam::fvc::absolute(), Foam::constant::atomic::alpha, beta(), Foam::bound(), fvMatrix< Type >::boundaryManipulate(), tmp< T >::clear(), optionList::constrain(), correct, optionList::correct(), Foam::fvm::ddt(), Foam::dev(), Foam::fvm::div(), Foam::fvc::div(), divU(), F1, fvOptions, Foam::constant::universal::G, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), Foam::max(), Foam::min(), options::New(), nut, phi, tmp< T >::ref(), fvMatrix< Type >::relax(), rho, Foam::solve(), Foam::fvm::Sp(), Foam::sqrt(), Foam::fvm::SuSp(), Foam::symm(), and Foam::twoSymm().
Referenced by kOmegaSSTSato< BasicTurbulenceModel >::correct(), kOmegaSSTLM< BasicTurbulenceModel >::correct(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::omega().
Member Data Documentation
dimensionedScalar alphaK1_ protected
Definition at line 132 of file kOmegaSSTBase.H.
dimensionedScalar alphaK2_ protected
Definition at line 133 of file kOmegaSSTBase.H.
dimensionedScalar alphaOmega1_ protected
Definition at line 135 of file kOmegaSSTBase.H.
dimensionedScalar alphaOmega2_ protected
Definition at line 136 of file kOmegaSSTBase.H.
dimensionedScalar gamma1_ protected
Definition at line 138 of file kOmegaSSTBase.H.
dimensionedScalar gamma2_ protected
Definition at line 139 of file kOmegaSSTBase.H.
dimensionedScalar beta1_ protected
Definition at line 141 of file kOmegaSSTBase.H.
dimensionedScalar beta2_ protected
Definition at line 142 of file kOmegaSSTBase.H.
dimensionedScalar betaStar_ protected
Definition at line 144 of file kOmegaSSTBase.H.
dimensionedScalar a1_ protected
Definition at line 146 of file kOmegaSSTBase.H.
dimensionedScalar b1_ protected
Definition at line 147 of file kOmegaSSTBase.H.
dimensionedScalar c1_ protected
Definition at line 148 of file kOmegaSSTBase.H.
Switch F3_ protected
Definition at line 150 of file kOmegaSSTBase.H.
const volScalarField& y_ protected
Wall distance.
Note: different to wall distance in parent RASModel which is for near-wall cells only
Definition at line 158 of file kOmegaSSTBase.H.
volScalarField k_ protected
Definition at line 160 of file kOmegaSSTBase.H.
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::k().
volScalarField omega_ protected
Definition at line 161 of file kOmegaSSTBase.H.
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::omega().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/Base/kOmegaSST/kOmegaSSTBase.H
src/TurbulenceModels/turbulenceModels/Base/kOmegaSST/kOmegaSSTBase.C