OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
IOstream Class Reference abstract
An IOstream is an abstract base class for all input/output systems; be they streams, files, token lists etc.
Classes
class versionNumber
Version number type.
Public Types
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Public Member Functions
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
virtual ios_base::fmtflags flags () const =0
Return flags of stream.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)=0
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
virtual void print (Ostream &) const
Print description of IOstream to Ostream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Static Public Member Functions
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes
label lineNumber_
Friends
Ostream & operator<< (Ostream &os, const streamFormat &sf)
Ostream operator.
Detailed Description
An IOstream is an abstract base class for all input/output systems; be they streams, files, token lists etc.
The basic operations are construct, close, read token, read primitive and read binary block. In addition version control and line number counting is incorporated. Usually one would use the read primitive member functions, but if one were reading a stream on unknown data sequence one can read token by token, and then analyse.
Source files
IOstream.H
IOstream.C
Definition at line 71 of file IOstream.H.
Member Enumeration Documentation
enum streamAccess
Enumeration for whether the stream open or closed.
Enumerator
OPENED
CLOSED
Definition at line 79 of file IOstream.H.
enum streamFormat
Enumeration for the format of data in the stream.
Enumerator
ASCII
BINARY
Definition at line 86 of file IOstream.H.
enum compressionType
Enumeration for the format of data in the stream.
Enumerator
UNCOMPRESSED
COMPRESSED
Definition at line 193 of file IOstream.H.
Constructor & Destructor Documentation
IOstream (streamFormat format, versionNumber version, compressionType compression = UNCOMPRESSED) inline
Construct setting format and version.
Definition at line 269 of file IOstream.H.
References IOstream::setBad().
Referenced by IOstream::setGood().
virtual ~IOstream () inline virtual
Destructor.
Definition at line 287 of file IOstream.H.
References IOstream::check(), IOstream::fatalCheck(), and IOstream::name().
Member Function Documentation
void setOpened () inline protected
Set stream opened.
Definition at line 239 of file IOstream.H.
References IOstream::OPENED.
Referenced by ITstream::ITstream(), OFstream::OFstream(), and UOPstream::UOPstream().
void setClosed () inline protected
Set stream closed.
Definition at line 245 of file IOstream.H.
References IOstream::CLOSED.
Referenced by OFstream::OFstream().
void setState (ios_base::iostate state) inline protected
Set stream state.
Definition at line 251 of file IOstream.H.
Referenced by ISstream::get(), ISstream::getLine(), OFstream::OFstream(), ISstream::putback(), ISstream::read(), OSstream::write(), and OSstream::writeQuoted().
void setGood () inline protected
Set stream to be good.
Definition at line 257 of file IOstream.H.
References IOstream::IOstream().
Referenced by ITstream::ITstream(), ITstream::rewind(), and UOPstream::UOPstream().
virtual const fileName& name () const inline virtual
Return the name of the stream.
Useful for Fstream to return the filename
Reimplemented in primitiveEntry, ITstream, OFstream, IFstream, ISstream, and OSstream.
Definition at line 297 of file IOstream.H.
Referenced by mappedPatchBase::calcMapping(), IOstream::check(), hexRef8::checkMesh(), functionEntry::execute(), includeEntry::execute(), IOstream::fatalCheck(), includeEntry::includeFileName(), Foam::operator>>(), IOobject::readHeader(), IOerror::SafeFatalIOError(), triSurface::triSurfInstance(), ensightSetWriter< Type >::write(), gnuplotGraph::write(), xmgrGraph::write(), edgeMeshFormat::write(), restraint::write(), STARCDsurfaceFormatCore::writeCase(), STARCDedgeFormat::writeCase(), fieldValueDelta::writeFileHeader(), and IOstream::~IOstream().
virtual fileName& name () inline virtual
Return non-const access to the name of the stream.
Useful to alter the stream name
Reimplemented in primitiveEntry, ITstream, OFstream, IFstream, ISstream, and OSstream.
Definition at line 304 of file IOstream.H.
bool check (const char * operation) const virtual
Check IOstream status for given operation.
print IOstream state if error has occured
Definition at line 92 of file IOstream.C.
References IOstream::bad(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and IOstream::name().
Referenced by adiabaticPerfectFluid< Specie >::adiabaticPerfectFluid(), Boussinesq< Specie >::Boussinesq(), Foam::checkMethod(), CollidingParcel< ParcelType >::CollidingParcel(), CollisionRecordList< PairType, WallType >::CollisionRecordList(), constTransport< Thermo >::constTransport(), trackedParticle::correctAfterParallelTransfer(), Keyed< T >::createList(), DSMCParcel< ParcelType >::DSMCParcel(), eConstThermo< EquationOfState >::eConstThermo(), directionInfo::edgeToFaceIndex(), fieldAverageItem::fieldAverageItem(), findCellParticle::findCellParticle(), hConstThermo< EquationOfState >::hConstThermo(), findCellParticle::hitPatch(), hPowerThermo< EquationOfState >::hPowerThermo(), hRefConstThermo< EquationOfState >::hRefConstThermo(), ignitionSite::ignitionSite(), incompressiblePerfectGas< Specie >::incompressiblePerfectGas(), coordinateSystem::init(), janafThermo< EquationOfState >::janafThermo(), KinematicParcel< ParcelType >::KinematicParcel(), kinematicParcelInjectionData::kinematicParcelInjectionData(), linear< Type >::linear(), keyType::match(), molecule::molecule(), MPPICParcel< ParcelType >::MPPICParcel(), line< Point, PointRef >::nearestDist(), objectMap::objectMap(), Foam::operator!=(), WallSiteData< Type >::operator!=(), Istream::operator()(), dimensioned< Type >::operator/=(), Foam::RBD::operator<<(), Foam::operator<<(), Foam::functionObjects::operator<<(), distribution::operator=(), surfacePatch::operator==(), fvPatchField< Type >::operator==(), Foam::operator>>(), Foam::RBD::operator>>(), Foam::functionObjects::operator>>(), PairCollisionRecord< Type >::PairCollisionRecord(), particle< Type >::particle(), PengRobinsonGas< Specie >::PengRobinsonGas(), perfectFluid< Specie >::perfectFluid(), perfectGas< Specie >::perfectGas(), phaseProperties::phaseProperties(), polyBoundaryMesh::polyBoundaryMesh(), sampledSurface::print(), pyramid< Point, PointRef, polygonRef >::pyramid(), ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel(), reactingMultiphaseParcelInjectionData::reactingMultiphaseParcelInjectionData(), ReactingParcel< ParcelType >::ReactingParcel(), reactingParcelInjectionData::reactingParcelInjectionData(), dimensioned< Type >::read(), dimensionSet::read(), IOPosition< CloudType >::readData(), ensightPart::reconstruct(), labelledTri::region(), rhoConst< Specie >::rhoConst(), PackedList< nBits >::setPair(), solidParticle::solidParticle(), LduMatrix< Type, DType, LUType >::source(), specie::specie(), SprayParcel< ParcelType >::SprayParcel(), streamLineParticle::streamLineParticle(), surfacePatchIOList::surfacePatchIOList(), surfZoneIOList::surfZoneIOList(), sutherlandTransport< Thermo >::sutherlandTransport(), thermo< Thermo, Type >::thermo(), ThermoParcel< ParcelType >::ThermoParcel(), thermoParcelInjectionData::thermoParcelInjectionData(), lduMesh::thisDb(), polyMeshModifier::topoChanger(), trackedParticle::trackedParticle(), memInfo::valid(), VectorSpace< Form, Cmpt, Ncmpts >::VectorSpace(), wallBoundedParticle::wallBoundedParticle(), wallBoundedStreamLineParticle::wallBoundedStreamLineParticle(), WallCollisionRecord< Type >::WallCollisionRecord(), SHA1Digest::write(), edgeMeshFormat::write(), boundaryPatch::write(), specie::write(), OFSsurfaceFormat< Face >::write(), perfectGas< Specie >::write(), janafThermo< EquationOfState >::write(), dimensionSet::write(), thermo< Thermo, Type >::write(), triSurface::write(), ensightParts::writeData(), Function1< Type >::writeData(), polyBoundaryMesh::writeData(), DimensionedField< Type, GeoMesh >::writeData(), FixedList< T, Size >::writeEntry(), GeometricField< Type, PatchField, GeoMesh >::Boundary::writeEntry(), solidParticle::writeFields(), streamLineParticle::writeFields(), molecule::writeFields(), Cloud< ParticleType >::writeObject(), particle< Type >::writePosition(), IOstream::~IOstream(), and tetIndices::~tetIndices().
void fatalCheck (const char * operation) const
Check IOstream status for given operation.
print IOstream state if error has occured and exit
Definition at line 105 of file IOstream.C.
References IOstream::bad(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and IOstream::name().
Referenced by dictionaryEntry::dictionaryEntry(), functionEntry::execute(), FixedList< T, Size >::FixedList(), List< T >::List(), LList< LListBase, T >::LList(), Matrix< Form, Type >::Matrix(), entry::New(), mapDistribute::operator=(), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< T, Key, Hash >::printInfo(), PtrList< T >::read(), primitiveEntry::read(), PackedList< nBits >::read(), UList< T >::writeEntry(), and IOstream::~IOstream().
bool opened () const inline
Return true if stream has been opened.
Definition at line 321 of file IOstream.H.
References IOstream::OPENED.
Referenced by IOstream::print().
bool closed () const inline
Return true if stream is closed.
Definition at line 327 of file IOstream.H.
References IOstream::CLOSED.
Referenced by IOstream::print().
bool good () const inline
Return true if next operation might succeed.
Definition at line 333 of file IOstream.H.
Referenced by topoSetSource::checkIs(), Foam::debug::controlDict(), dynamicCode::copyAndFilter(), dynamicCode::copyOrCreateFiles(), functionObjectFiles::createFiles(), AC3DsurfaceFormatCore::cueTo(), error::error(), edgeMeshFormatsCore::getLineNoComment(), surfaceFormatsCore::getLineNoComment(), meanVelocityForce::meanVelocityForce(), noiseFFT::noiseFFT(), IOobject::objectStream(), OFstream::OFstream(), csvTableReader< Type >::operator()(), error::operator()(), Istream::operator()(), Foam::operator>>(), argList::parse(), Foam::parseNASCoord(), IOstream::print(), extendedEdgeMeshFormat::read(), extendedFeatureEdgeMeshFormat::read(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJedgeFormat::read(), OFFsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), edgeMeshFormat::read(), AC3DsurfaceFormat< Face >::read(), tabulated6DoFAcceleration::read(), VTKedgeFormat::read(), STARCDsurfaceFormat< Face >::read(), FTRsurfaceFormat< Face >::read(), tabulated6DoFMotion::read(), OFSsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), dictionary::read(), STARCD::readBoundary(), Foam::readCmd(), AC3DsurfaceFormatCore::readCmd(), externalCoupledMixedFvPatchField< Type >::readData(), STARCDCore::readHeader(), STARCD::readHeader(), IOobject::readHeader(), STARCDsurfaceFormatCore::readInpCellTable(), STARCDCore::readPoints(), Foam::readUpto(), scalarRanges::scalarRanges(), Reaction< ReactionThermo >::setLRhs(), topoSet::topoSet(), triSurface::triSurfInstance(), memInfo::update(), vtkUnstructuredReader::vtkUnstructuredReader(), X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), GTSsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OBJedgeFormat::write(), OFFsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), VTKedgeFormat::write(), edgeMeshFormat::write(), OFSsurfaceFormat< Face >::write(), graph::write(), dictionary::write(), dynamicIndexedOctree< Type >::write(), indexedOctree< Type >::write(), STLsurfaceFormat< Face >::writeAscii(), correlationFunction< Type >::writeAveraged(), fieldDictionary::writeData(), featureEdgeMesh::writeData(), IOPosition< CloudType >::writeData(), UniformDimensionedField< Type >::writeData(), surfZoneIOList::writeData(), surfacePatchIOList::writeData(), IOdictionary::writeData(), AverageIOField< Type >::writeData(), porosityModelList::writeData(), coordinateSystems::writeData(), extendedFeatureEdgeMesh::writeData(), polyTopoChanger::writeData(), cellModel::writeData(), AveragingMethod< Type >::writeData(), ZoneMesh< ZoneType, MeshType >::writeData(), MRFZoneList::writeData(), optionList::writeData(), polyBoundaryMesh::writeData(), DimensionedField< Type, GeoMesh >::writeData(), refinementHistory::writeData(), GeometricField< Type, PatchField, GeoMesh >::writeData(), pairPotential::writeEnergyAndForceTables(), IOobject::writeHeader(), regIOobject::writeObject(), JobInfo::~JobInfo(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
bool eof () const inline
Return true if end of input seen.
Definition at line 339 of file IOstream.H.
Referenced by topoSetSource::checkIs(), Time::findTimes(), gaussGrad< Type >::gaussGrad(), gradScheme< Type >::New(), snGradScheme< Type >::New(), surfaceInterpolationScheme< Type >::New(), d2dt2Scheme< Type >::New(), ddtScheme< Type >::New(), divScheme< Type >::New(), convectionScheme< Type >::New(), limitedSurfaceInterpolationScheme< Type >::New(), laplacianScheme< Type, GType >::New(), Reaction< ReactionThermo >::New(), noiseFFT::noiseFFT(), IOstream::print(), PtrList< T >::read(), ITstream::read(), dictionary::read(), solution::upgradeSolverDict(), and UIPstream::~UIPstream().
bool fail () const inline
Return true if next operation will fail.
Definition at line 345 of file IOstream.H.
Referenced by IOstream::operator void *(), IOstream::operator!(), and IOstream::print().
bool bad () const inline
Return true if stream is corrupted.
Definition at line 351 of file IOstream.H.
Referenced by IOstream::check(), IOstream::fatalCheck(), Istream::getBack(), Foam::operator<<(), IOstream::print(), Istream::putBack(), GTSsurfaceFormat< Face >::read(), ISstream::read(), primitiveEntry::read(), dictionary::read(), featureEdgeMesh::readData(), IOdictionary::readData(), extendedFeatureEdgeMesh::readData(), and refinementHistory::readData().
operator void * () const inline
Return non-zero if the stream has not failed.
Definition at line 357 of file IOstream.H.
References IOstream::fail().
bool operator! () const inline
Return true if the stream has failed.
Definition at line 365 of file IOstream.H.
References IOstream::fail(), and IOstream::formatEnum().
Foam::IOstream::streamFormat formatEnum (const word & format) static
Return stream format of given format name.
Definition at line 39 of file IOstream.C.
References IOstream::ASCII, IOstream::BINARY, Foam::endl(), and WarningInFunction.
Referenced by ensightSurfaceWriter::ensightSurfaceWriter(), IOstream::format(), IOstream::operator!(), and Time::readDict().
streamFormat format () const inline
Return current stream format.
Definition at line 377 of file IOstream.H.
Referenced by CollidingParcel< ParcelType >::CollidingParcel(), trackedParticle::correctAfterParallelTransfer(), DSMCParcel< ParcelType >::DSMCParcel(), directionInfo::edgeToFaceIndex(), calcEntry::execute(), codeStream::execute(), fanFvPatchField< Type >::fanFvPatchField(), findCellParticle::findCellParticle(), FixedList< T, Size >::FixedList(), findCellParticle::hitPatch(), KinematicParcel< ParcelType >::KinematicParcel(), List< T >::List(), Matrix< Form, Type >::Matrix(), molecule::molecule(), MPPICParcel< ParcelType >::MPPICParcel(), ensightFile::newline(), Foam::operator<<(), Foam::operator>>(), particle< Type >::particle(), ReactingParcel< ParcelType >::ReactingParcel(), UIPstream::read(), ISstream::read(), PackedList< nBits >::read(), IOobject::readHeader(), refineCell::refineCell(), labelledTri::region(), Foam::setformat(), solidParticle::solidParticle(), SprayParcel< ParcelType >::SprayParcel(), ThermoParcel< ParcelType >::ThermoParcel(), trackedParticle::trackedParticle(), wallBoundedParticle::wallBoundedParticle(), csvTableReader< Type >::write(), ensightFile::write(), OSstream::write(), UOPstream::write(), dimensionSet::write(), PackedList< nBits >::write(), ensightFile::writeBinaryHeader(), CSV< Type >::writeData(), FixedList< T, Size >::writeEntry(), UList< T >::writeEntry(), solidParticle::writeFields(), molecule::writeFields(), IOobject::writeHeader(), and particle< Type >::writePosition().
streamFormat format (const streamFormat fmt) inline
Set the stream format.
Definition at line 383 of file IOstream.H.
streamFormat format (const word & fmt) inline
Set the stream format from word.
Definition at line 391 of file IOstream.H.
References IOstream::formatEnum().
versionNumber version () const inline
Return the stream version.
Definition at line 399 of file IOstream.H.
Referenced by Field< Type >::Field(), Foam::operator>>(), IOobject::readHeader(), mappedPatchBase::readListOrField(), Foam::setversion(), and IOobject::writeHeader().
versionNumber version (const versionNumber ver) inline
Set the stream version.
Definition at line 405 of file IOstream.H.
References IOstream::compressionEnum().
Foam::IOstream::compressionType compressionEnum (const word & compression) static
Return compression of given compression name.
Definition at line 61 of file IOstream.C.
References IOstream::COMPRESSED, Foam::endl(), IOstream::UNCOMPRESSED, Switch::valid(), and WarningInFunction.
Referenced by IOstream::compression(), rawSurfaceWriter::rawSurfaceWriter(), Time::readDict(), and IOstream::version().
compressionType compression () const inline
Return the stream compression.
Definition at line 416 of file IOstream.H.
Referenced by Foam::setcompression().
compressionType compression (const compressionType cmp) inline
Set the stream compression.
Definition at line 422 of file IOstream.H.
compressionType compression (const word & cmp) inline
Set the stream compression from word.
Definition at line 430 of file IOstream.H.
References IOstream::compressionEnum().
label lineNumber () const inline
Return current stream line number.
Definition at line 438 of file IOstream.H.
References IOstream::lineNumber_.
Referenced by functionEntry::execute(), calcEntry::execute(), codeStream::execute(), Foam::parseNASCoord(), ITstream::print(), IOstream::print(), NASedgeFormat::read(), NASsurfaceFormat< Face >::read(), ISstream::read(), UIPstream::read(), ITstream::read(), primitiveEntry::read(), IOobject::readHeader(), IOerror::SafeFatalIOError(), and vtkUnstructuredReader::vtkUnstructuredReader().
label& lineNumber () inline
Return current stream line number.
Definition at line 444 of file IOstream.H.
References IOstream::lineNumber_.
label lineNumber (const label ln) inline
Set the stream line number.
Definition at line 450 of file IOstream.H.
References IOstream::flags(), IOstream::lineNumber_, and Foam::ln().
virtual ios_base::fmtflags flags () const pure virtual
Return flags of stream.
Implemented in ITstream, UIPstream, ISstream, UOPstream, and OSstream.
Referenced by IOstream::lineNumber(), IOstream::setBad(), IOstream::setf(), and IOstream::unsetf().
static unsigned int defaultPrecision () inline static
Return the default precision.
Definition at line 461 of file IOstream.H.
References IOstream::precision_.
Referenced by functionObjectFile::charWidth(), isNotEqOp< T >::operator()(), probes::prepare(), Time::readDict(), and functionObjectFile::valueWidth().
static unsigned int defaultPrecision (unsigned int p) inline static
Reset the default precision (and return old precision)
Definition at line 467 of file IOstream.H.
References p, and IOstream::precision_.
void setEof () inline
Set stream to have reached eof.
Definition at line 475 of file IOstream.H.
Referenced by ITstream::read().
void setFail () inline
Set stream to have failed.
Definition at line 481 of file IOstream.H.
void setBad () inline
Set stream to be bad.
Definition at line 487 of file IOstream.H.
References f(), and IOstream::flags().
Referenced by IOstream::IOstream(), keyType::match(), OFstream::OFstream(), Foam::operator>>(), ISstream::putback(), UIPstream::read(), ITstream::read(), Istream::readBegin(), Istream::readBeginList(), Istream::readEnd(), Istream::readEndList(), and UOPstream::write().
virtual ios_base::fmtflags flags (const ios_base::fmtflags f) pure virtual
Set flags of stream.
Implemented in UOPstream, ITstream, ISstream, UIPstream, and OSstream.
ios_base::fmtflags setf (const ios_base::fmtflags f) inline
Set flags of stream.
Definition at line 496 of file IOstream.H.
References IOstream::flags().
Referenced by Foam::dec(), ensightAsciiStream::ensightAsciiStream(), ensightFile::ensightFile(), Foam::fixed(), Foam::hex(), functionObjectFile::initStream(), NamedEnum< Enum, nEnum >::names(), Foam::oct(), Foam::scientific(), Foam::setf(), ensightSetWriter< Type >::write(), and STARCDCore::writePoints().
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask) inline
Set flags of given field of stream.
Definition at line 503 of file IOstream.H.
References IOstream::flags().
void unsetf (const ios_base::fmtflags uf) inline
Unset flags of stream.
Definition at line 512 of file IOstream.H.
References IOstream::flags(), IOstream::info(), IOstream::versionNumber::operator<<, IOstream::print(), and sf().
Referenced by NamedEnum< Enum, nEnum >::names().
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented in UOPstream, ITstream, ISstream, OSstream, UIPstream, prefixOSstream, OFstream, IFstream, OStringStream, and IStringStream.
Definition at line 126 of file IOstream.C.
References IOstream::ASCII, IOstream::bad(), IOstream::BINARY, IOstream::closed(), Foam::endl(), IOstream::eof(), IOstream::fail(), IOstream::good(), IOstream::lineNumber(), and IOstream::opened().
Referenced by Foam::operator<<(), OSstream::print(), ISstream::print(), ITstream::print(), and IOstream::unsetf().
void print (Ostream & os, const int streamState) const
Check given stream state bits.
Definition at line 177 of file IOstream.C.
References Foam::endl().
InfoProxy<IOstream> info () const inline
Return info proxy.
Used to print IOstream information to a stream
Definition at line 531 of file IOstream.H.
Referenced by OFstream::OFstream(), dimensionSet::read(), IOstream::unsetf(), and IOobject::writeHeader().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const streamFormat & sf) friend
Ostream operator.
Member Data Documentation
const IOstream::versionNumber originalVersion static
Original version number.
Definition at line 203 of file IOstream.H.
Referenced by Foam::operator>>().
const IOstream::versionNumber currentVersion static
Current version number.
Definition at line 206 of file IOstream.H.
Referenced by regionModel::evolve(), meshReader::warnDuplicates(), rawSurfaceWriter::write(), regIOobject::write(), rawSurfaceWriter::writeData(), and meshReader::writeMesh().
unsigned int precision_ static
Default precision.
Definition at line 209 of file IOstream.H.
Referenced by IOstream::defaultPrecision().
label lineNumber_ protected
Definition at line 231 of file IOstream.H.
Referenced by ISstream::get(), ISstream::getLine(), IOstream::lineNumber(), OFstream::OFstream(), ISstream::putback(), ITstream::read(), ITstream::rewind(), OSstream::write(), and OSstream::writeQuoted().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.H
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.C
src/OpenFOAM/db/IOstreams/IOstreams.C