OpenFOAM: kOmegaSSTSAS< BasicTurbulenceModel > Class Template Reference
kOmegaSSTSAS< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
Scale-adaptive URAS model based on the k-omega-SST RAS model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTSAS")
Runtime type information.
kOmegaSSTSAS (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSSTSAS ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
const volScalarField & delta () const
Access function to filter width.
Public Member Functions inherited from kOmegaSST< BasicTurbulenceModel >
TypeName ("kOmegaSST")
Runtime type information.
kOmegaSST (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSST ()
Destructor.
Protected Member Functions
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
SAS omega source.
Protected Attributes
dimensionedScalar Cs_
dimensionedScalar kappa_
dimensionedScalar zeta2_
dimensionedScalar sigmaPhi_
dimensionedScalar C_
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmegaSSTSAS< BasicTurbulenceModel >
Scale-adaptive URAS model based on the k-omega-SST RAS model.
References:
    Egorov, Y., & Menter F.R. (2008).
    Development and Application of SST-SAS Model in the DESIDER Project.
    Advances in Hybrid RANS-LES Modelling,
    Notes on Num. Fluid Mech. And Multidisciplinary Design,
    Volume 97, 261-270.
The model coefficients are
    kOmegaSSTSASCoeffs
    {
        // Default SST coefficients
        alphaK1     0.85;
        alphaK2     1.0;
        alphaOmega1 0.5;
        alphaOmega2 0.856;
        beta1       0.075;
        beta2       0.0828;
        betaStar    0.09;
        gamma1      5/9;
        gamma2      0.44;
        a1          0.31;
        b1          1.0;
        c1          10.0;
        F3          no;
        // Default SAS coefficients
        Cs          0.11;
        kappa       0.41;
        zeta2       3.51;
        sigmaPhi    2.0/3.0;
        C           2;
        // Delta must be specified for SAS e.g.
        delta cubeRootVol;
        cubeRootVolCoeffs
        {}
    }
Source files
kOmegaSSTSAS.H
kOmegaSSTSAS.C
Definition at line 98 of file kOmegaSSTSAS.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 141 of file kOmegaSSTSAS.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 142 of file kOmegaSSTSAS.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 143 of file kOmegaSSTSAS.H.
Constructor & Destructor Documentation
kOmegaSSTSAS (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 97 of file kOmegaSSTSAS.C.
virtual ~kOmegaSSTSAS () inline virtual
Destructor.
Definition at line 167 of file kOmegaSSTSAS.H.
References kOmegaSSTSAS< BasicTurbulenceModel >::read().
Member Function Documentation
tmp< fvScalarMatrix > Qsas (const volScalarField::Internal & S2, const volScalarField::Internal & gamma, const volScalarField::Internal & beta) const protected virtual
SAS omega source.
Definition at line 39 of file kOmegaSSTSAS.C.
References delta, Foam::fvc::grad(), Foam::fvc::laplacian(), Foam::mag(), Foam::magSqr(), Foam::max(), Foam::min(), Foam::pow025(), Foam::sqr(), Foam::sqrt(), and Foam::fvm::Su().
TypeName ("kOmegaSSTSAS< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Re-read model coefficients if they have changed.
Definition at line 180 of file kOmegaSSTSAS.C.
Referenced by kOmegaSSTSAS< BasicTurbulenceModel >::~kOmegaSSTSAS().
const volScalarField& delta () const inline
Access function to filter width.
Definition at line 177 of file kOmegaSSTSAS.H.
References kOmegaSSTSAS< BasicTurbulenceModel >::delta_.
Member Data Documentation
dimensionedScalar Cs_ protected
Definition at line 115 of file kOmegaSSTSAS.H.
dimensionedScalar kappa_ protected
Definition at line 116 of file kOmegaSSTSAS.H.
dimensionedScalar zeta2_ protected
Definition at line 117 of file kOmegaSSTSAS.H.
dimensionedScalar sigmaPhi_ protected
Definition at line 118 of file kOmegaSSTSAS.H.
dimensionedScalar C_ protected
Definition at line 119 of file kOmegaSSTSAS.H.
autoPtr<Foam::LESdelta> delta_ protected
Run-time selectable delta model.
Definition at line 125 of file kOmegaSSTSAS.H.
Referenced by kOmegaSSTSAS< BasicTurbulenceModel >::delta().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTSAS/kOmegaSSTSAS.H
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTSAS/kOmegaSSTSAS.C