OpenFOAM: HashTable< T, Key, Hash >::iterator Class Reference
HashTable< T, Key, Hash >::iterator Class Reference
An STL-conforming iterator.
Public Member Functions
iterator ()
Construct null (end iterator)
iterator (const iteratorEnd &unused)
Construct end iterator.
T & operator* ()
Return referenced hash value.
T & operator() ()
const T & operator* () const
Return referenced hash value.
const T & operator() () const
iterator & operator++ ()
iterator operator++ (int)
Public Member Functions inherited from HashTable< T, Key, Hash >::iteratorBase
const Key & key () const
Return the Key corresponding to the iterator.
bool operator== (const iteratorBase &) const
Compare hashedEntry element pointers.
bool operator!= (const iteratorBase &) const
bool operator== (const iteratorEnd &unused) const
Compare hashedEntry to iteratorEnd pointers.
bool operator!= (const iteratorEnd &unused) const
Friends
class HashTable
Additional Inherited Members
Protected Member Functions inherited from HashTable< T, Key, Hash >::iteratorBase
iteratorBase ()
Construct null - equivalent to an 'end' position.
iteratorBase (const HashTable< T, Key, Hash > *curHashTable)
Construct from hash table, moving to its 'begin' position.
iteratorBase (const HashTable< T, Key, Hash > *curHashTable, const hashedEntry *elmt, const label hashIndex)
Construct from hash table, element and hash index.
void increment ()
Increment to the next position.
bool erase ()
Erase the HashTable element at the current position.
T & object ()
Return non-const access to referenced object.
const T & cobject () const
Return const access to referenced object.
Detailed Description
template<class T, class Key = word, class Hash = string::hash>
class Foam::HashTable< T, Key, Hash >::iterator
An STL-conforming iterator.
Definition at line 415 of file HashTable.H.
Constructor & Destructor Documentation
iterator () inline
Construct null (end iterator)
Definition at line 327 of file HashTableI.H.
Referenced by HashTable< T, Key, Hash >::begin(), and HashTable< T, Key, Hash >::iterator::iterator().
iterator (const iteratorEnd & unused) inline
Construct end iterator.
Definition at line 335 of file HashTableI.H.
References HashTable< T, Key, Hash >::iterator::iterator(), HashTable< T, Key, Hash >::iteratorBase::iteratorBase(), and Foam::T().
Member Function Documentation
T & operator* () inline
Return referenced hash value.
Definition at line 367 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::object(), and Foam::T().
T & operator() () inline
Definition at line 375 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::object(), and Foam::T().
const T & operator* () const inline
Return referenced hash value.
Definition at line 383 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::cobject(), and Foam::T().
const T & operator() () const inline
Definition at line 391 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::cobject().
Foam::HashTable< T, Key, Hash >::iterator & operator++ () inline
Definition at line 400 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::increment().
Foam::HashTable< T, Key, Hash >::iterator operator++ (int) inline
Definition at line 409 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::increment().
Friends And Related Function Documentation
friend class HashTable friend
Definition at line 419 of file HashTable.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/HashTables/HashTable/HashTableI.H