OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
laplacianScheme< Type, GType > Class Template Reference abstract
Abstract base class for laplacian schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, laplacianScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
laplacianScheme (const fvMesh &mesh)
Construct from mesh.
laplacianScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
laplacianScheme (const fvMesh &mesh, const tmp< surfaceInterpolationScheme< GType > > &igs, const tmp< snGradScheme< Type > > &sngs)
Construct from mesh, interpolation and snGradScheme schemes.
virtual ~laplacianScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< laplacianScheme< Type, GType > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new laplacianScheme created on freestore.
Protected Member Functions
laplacianScheme (const laplacianScheme &)
Disallow copy construct.
void operator= (const laplacianScheme &)
Disallow default bitwise assignment.
Protected Attributes
const fvMesh & mesh_
tmp< surfaceInterpolationScheme< GType > > tinterpGammaScheme_
tmp< snGradScheme< Type > > tsnGradScheme_
Detailed Description
template<class Type, class GType>
class Foam::fv::laplacianScheme< Type, GType >
Abstract base class for laplacian schemes.
Source files
laplacianScheme.H
laplacianScheme.C
Definition at line 65 of file laplacianScheme.H.
Constructor & Destructor Documentation
laplacianScheme (const laplacianScheme< Type, GType > &) protected
Disallow copy construct.
laplacianScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 109 of file laplacianScheme.H.
laplacianScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 117 of file laplacianScheme.H.
References snGradScheme< Type >::New(), and surfaceInterpolationScheme< Type >::New().
laplacianScheme (const fvMesh & mesh, const tmp< surfaceInterpolationScheme< GType > > & igs, const tmp< snGradScheme< Type > > & sngs) inline
Construct from mesh, interpolation and snGradScheme schemes.
Definition at line 136 of file laplacianScheme.H.
~laplacianScheme () virtual
Destructor.
Definition at line 93 of file laplacianScheme.C.
Member Function Documentation
void operator= (const laplacianScheme< Type, GType > &) protected
Disallow default bitwise assignment.
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (tmp , laplacianScheme< Type, GType > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
tmp< laplacianScheme< Type, GType > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new laplacianScheme created on freestore.
Definition at line 45 of file laplacianScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, Foam::Info, mesh, and Foam::nl.
Referenced by Foam::fvc::laplacian(), and Foam::fvm::laplacian().
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 165 of file laplacianScheme.H.
References laplacianScheme< Type, GType >::mesh_.
virtual tmp<fvMatrix<Type> > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >.
tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Definition at line 102 of file laplacianScheme.C.
References Foam::interpolate().
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >.
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Definition at line 114 of file laplacianScheme.C.
References Foam::interpolate().
Member Data Documentation
const fvMesh& mesh_ protected
Definition at line 74 of file laplacianScheme.H.
Referenced by laplacianScheme< Type, GType >::mesh().
tmp<surfaceInterpolationScheme<GType> > tinterpGammaScheme_ protected
Definition at line 75 of file laplacianScheme.H.
tmp<snGradScheme<Type> > tsnGradScheme_ protected
Definition at line 76 of file laplacianScheme.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/laplacianSchemes/laplacianScheme/laplacianScheme.H
src/finiteVolume/finiteVolume/laplacianSchemes/laplacianScheme/laplacianScheme.C