OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
KinematicCloud< CloudType > Class Template Reference
Templated base class for kinematic cloud.
Public Types
typedef CloudType cloudType
Type of cloud this cloud was instantiated for.
typedef CloudType::particleType parcelType
Type of parcel the cloud was instantiated for.
typedef KinematicCloud< CloudType > kinematicCloudType
Convenience typedef for this cloud type.
typedef ParticleForceList< KinematicCloud< CloudType > > forceType
Force models type.
typedef CloudFunctionObjectList< KinematicCloud< CloudType > > functionType
Function object type.
Public Types inherited from DSMCCloud< ParcelType >
typedef ParcelType parcelType
Type of parcel the cloud was instantiated for.
Public Types inherited from Cloud< ParcelType >
typedef ParcelType particleType
typedef IDLList< ParcelType >::iterator iterator
typedef IDLList< ParcelType >::const_iterator const_iterator
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject * >
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Types inherited from UILList< DLListBase, ParcelType >
typedef ParcelType value_type
Type of values the DLList contains.
typedef ParcelType & reference
Type that can be used for storing into DLList::value_type.
typedef const ParcelType & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase::iterator LListBase_iterator
typedef DLListBase::const_iterator LListBase_const_iterator
Public Member Functions
KinematicCloud (const word &cloudName, const volScalarField &rho, const volVectorField &U, const volScalarField &mu, const dimensionedVector &g, bool readFields=true)
Construct given carrier gas fields.
KinematicCloud (KinematicCloud< CloudType > &c, const word &name)
Copy constructor with new name.
KinematicCloud (const fvMesh &mesh, const word &name, const KinematicCloud< CloudType > &c)
Copy constructor with new name - creates bare cloud.
virtual autoPtr< Cloud< parcelType > > clone (const word &name)
Construct and return clone based on (this) with new name.
virtual autoPtr< Cloud< parcelType > > cloneBare (const word &name) const
Construct and return bare clone based on (this) with new name.
virtual ~KinematicCloud ()
Destructor.
const KinematicCloud & cloudCopy () const
Return a reference to the cloud copy.
virtual bool hasWallImpactDistance () const
Switch to specify if particles of the cloud can return.
const fvMesh & mesh () const
Return reference to the mesh.
const IOdictionary & particleProperties () const
Return particle properties dictionary.
const IOdictionary & outputProperties () const
Return output properties dictionary.
IOdictionary & outputProperties ()
Return non-const access to the output properties dictionary.
const cloudSolution & solution () const
Return const access to the solution properties.
cloudSolution & solution ()
Return access to the solution properties.
const parcelType::constantProperties & constProps () const
Return the constant properties.
parcelType::constantProperties & constProps ()
Return access to the constant properties.
const dictionary & subModelProperties () const
Return reference to the sub-models dictionary.
cachedRandom & rndGen ()
Return reference to the random object.
List< DynamicList< parcelType * > > & cellOccupancy ()
Return the cell occupancy information for each.
const scalarField & cellLengthScale () const
Return the cell length scale.
const volVectorField & U () const
Return carrier gas velocity.
const volScalarField & rho () const
Return carrier gas density.
const volScalarField & mu () const
Return carrier gas dynamic viscosity.
const dimensionedVector & g () const
Gravity.
scalar pAmbient () const
Return const-access to the ambient pressure.
scalar & pAmbient ()
Return reference to the ambient pressure.
const forceType & forces () const
Optional particle forces.
forceType & forces ()
Return the optional particle forces.
functionType & functions ()
Optional cloud function objects.
const InjectionModelList< KinematicCloud< CloudType > > & injectors () const
Return const access to the injection model.
InjectionModelList< KinematicCloud< CloudType > > & injectors ()
Return reference to the injection model.
const DispersionModel< KinematicCloud< CloudType > > & dispersion () const
Return const-access to the dispersion model.
DispersionModel< KinematicCloud< CloudType > > & dispersion ()
Return reference to the dispersion model.
const PatchInteractionModel< KinematicCloud< CloudType > > & patchInteraction () const
Return const-access to the patch interaction model.
PatchInteractionModel< KinematicCloud< CloudType > > & patchInteraction ()
Return reference to the patch interaction model.
const StochasticCollisionModel< KinematicCloud< CloudType > > & stochasticCollision () const
Return const-access to the stochastic collision model.
StochasticCollisionModel< KinematicCloud< CloudType > > & stochasticCollision ()
Return reference to the stochastic collision model.
const SurfaceFilmModel< KinematicCloud< CloudType > > & surfaceFilm () const
Return const-access to the surface film model.
SurfaceFilmModel< KinematicCloud< CloudType > > & surfaceFilm ()
Return reference to the surface film model.
const vectorIntegrationScheme & UIntegrator () const
Return reference to velocity integration.
DimensionedField< vector, volMesh > & UTrans ()
Return reference to momentum source.
const DimensionedField< vector, volMesh > & UTrans () const
Return const reference to momentum source.
DimensionedField< scalar, volMesh > & UCoeff ()
Return coefficient for carrier phase U equation.
const DimensionedField< scalar, volMesh > & UCoeff () const
Return const coefficient for carrier phase U equation.
tmp< fvVectorMatrix > SU (volVectorField &U) const
Return tmp momentum source term.
label nParcels () const
Total number of parcels.
scalar massInSystem () const
Total mass in system.
vector linearMomentumOfSystem () const
Total linear momentum of the system.
scalar linearKineticEnergyOfSystem () const
Total linear kinetic energy in the system.
scalar rotationalKineticEnergyOfSystem () const
Total rotational kinetic energy in the system.
scalar Dij (const label i, const label j) const
Mean diameter Dij.
scalar Dmax () const
Max diameter.
const tmp< volScalarField > vDotSweep () const
Volume swept rate of parcels per cell.
const tmp< volScalarField > theta () const
Return the particle volume fraction field.
const tmp< volScalarField > alpha () const
Return the particle mass fraction field.
const tmp< volScalarField > rhoEff () const
Return the particle effective density field.
void setParcelThermoProperties (parcelType &parcel, const scalar lagrangianDt)
Set parcel thermo properties.
void checkParcelProperties (parcelType &parcel, const scalar lagrangianDt, const bool fullyDescribed)
Check parcel properties.
void storeState ()
Store the current cloud state.
void restoreState ()
Reset the current cloud to the previously stored state.
void resetSourceTerms ()
Reset the cloud source terms.
template<class Type >
void relax (DimensionedField< Type, volMesh > &field, const DimensionedField< Type, volMesh > &field0, const word &name) const
Relax field.
template<class Type >
void scale (DimensionedField< Type, volMesh > &field, const word &name) const
Scale field.
void relaxSources (const KinematicCloud< CloudType > &cloudOldTime)
Apply relaxation to (steady state) cloud sources.
void scaleSources ()
Apply scaling to (transient) cloud sources.
void preEvolve ()
Pre-evolve.
void evolve ()
Evolve the cloud.
template<class TrackData >
void motion (TrackData &td)
Particle motion.
void patchData (const parcelType &p, const polyPatch &pp, const scalar trackFraction, const tetIndices &tetIs, vector &normal, vector &Up) const
Calculate the patch normal and velocity to interact with,.
void updateMesh ()
Update mesh.
virtual void autoMap (const mapPolyMesh &)
Remap the cells of particles corresponding to the.
void info ()
Print cloud information.
Public Member Functions inherited from DSMCCloud< ParcelType >
DSMCCloud (const word &cloudName, const fvMesh &mesh, bool readFields=true)
Construct given name and mesh, will read Parcels and fields from.
DSMCCloud (const word &cloudName, const fvMesh &mesh, const IOdictionary &dsmcInitialiseDict)
Construct given name, mesh and initialisation dictionary.
virtual ~DSMCCloud ()
Destructor.
const word & cloudName () const
Return the cloud type.
const fvMesh & mesh () const
Return refernce to the mesh.
const IOdictionary & particleProperties () const
Return particle properties dictionary.
const List< word > & typeIdList () const
Return the idList.
scalar nParticle () const
Return the number of real particles represented by one.
const List< DynamicList< ParcelType * > > & cellOccupancy () const
Return the cell occupancy addressing.
volScalarField & sigmaTcRMax ()
Return the sigmaTcRMax field. non-const access to allow.
scalarField & collisionSelectionRemainder ()
Return the collision selection remainder field. non-const.
const List< typename ParcelType::constantProperties > & constProps () const
Return all of the constant properties.
const ParcelType::constantProperties & constProps (label typeId) const
Return the constant properties of the given typeId.
Random & rndGen ()
Return refernce to the random object.
volScalarField::Boundary & qBF ()
Return non-const heat flux boundary field reference.
volVectorField::Boundary & fDBF ()
Return non-const force density at boundary field reference.
volScalarField::Boundary & rhoNBF ()
Return non-const number density boundary field reference.
volScalarField::Boundary & rhoMBF ()
Return non-const mass density boundary field reference.
volScalarField::Boundary & linearKEBF ()
Return non-const linear kinetic energy density boundary.
volScalarField::Boundary & internalEBF ()
Return non-const internal energy density boundary field.
volScalarField::Boundary & iDofBF ()
Return non-const internal degree of freedom density boundary.
volVectorField::Boundary & momentumBF ()
Return non-const momentum density boundary field reference.
const volScalarField & boundaryT () const
Return macroscopic temperature.
const volVectorField & boundaryU () const
Return macroscopic velocity.
const volScalarField & q () const
Return heat flux at surface field.
const volVectorField & fD () const
Return force density at surface field.
const volScalarField & rhoN () const
Return the real particle number density field.
const volScalarField & rhoM () const
Return the particle mass density field.
const volScalarField & dsmcRhoN () const
Return the field of number of DSMC particles.
const volScalarField & linearKE () const
Return the total linear kinetic energy (translational and.
const volScalarField & internalE () const
Return the internal energy density field.
const volScalarField & iDof () const
Return the average internal degrees of freedom field.
const volVectorField & momentum () const
Return the momentum density field.
vector equipartitionLinearVelocity (scalar temperature, scalar mass)
Generate a random velocity sampled from the Maxwellian speed.
scalar equipartitionInternalEnergy (scalar temperature, direction internalDegreesOfFreedom)
Generate a random internal energy, sampled from the.
scalar maxwellianAverageSpeed (scalar temperature, scalar mass) const
Average particle speed.
scalarField maxwellianAverageSpeed (scalarField temperature, scalar mass) const
scalar maxwellianRMSSpeed (scalar temperature, scalar mass) const
RMS particle speed.
scalarField maxwellianRMSSpeed (scalarField temperature, scalar mass) const
scalar maxwellianMostProbableSpeed (scalar temperature, scalar mass) const
Most probable speed.
scalarField maxwellianMostProbableSpeed (scalarField temperature, scalar mass) const
const BinaryCollisionModel< DSMCCloud< ParcelType > > & binaryCollision () const
Return reference to binary elastic collision model.
BinaryCollisionModel< DSMCCloud< ParcelType > > & binaryCollision ()
Return non-const reference to binary elastic collision model.
const WallInteractionModel< DSMCCloud< ParcelType > > & wallInteraction () const
Return reference to wall interaction model.
WallInteractionModel< DSMCCloud< ParcelType > > & wallInteraction ()
Return non-const reference to wall interaction model.
const InflowBoundaryModel< DSMCCloud< ParcelType > > & inflowBoundary () const
Return reference to wall interaction model.
InflowBoundaryModel< DSMCCloud< ParcelType > > & inflowBoundary ()
Return non-const reference to wall interaction model.
scalar massInSystem () const
Total mass in system.
vector linearMomentumOfSystem () const
Total linear momentum of the system.
scalar linearKineticEnergyOfSystem () const
Total linear kinetic energy in the system.
scalar internalEnergyOfSystem () const
Total internal energy in the system.
void info () const
Print cloud information.
void dumpParticlePositions () const
Dump particle positions to .obj file.
void addNewParcel (const vector &position, const vector &U, const scalar Ei, const label celli, const label tetFacei, const label tetPtI, const label typeId)
Add new parcel.
void evolve ()
Evolve the cloud (move, collide)
void clear ()
Clear the Cloud.
Public Member Functions inherited from Cloud< ParcelType >
TypeName ("Cloud")
Runtime type information.
Cloud (const polyMesh &mesh, const IDLList< ParcelType > &particles)
Construct from mesh and a list of particles.
Cloud (const polyMesh &mesh, const word &cloudName, const IDLList< ParcelType > &particles)
Construct from mesh, cloud name, and a list of particles.
Cloud (const polyMesh &mesh, const bool checkClass=true)
Construct from mesh by reading from file.
Cloud (const polyMesh &pMesh, const word &cloudName, const bool checkClass=true)
Construct from mesh by reading from file with given cloud instance.
const polyMesh & pMesh () const
Return the polyMesh reference.
label size () const
DynamicList< label > & labels ()
label nTrackingRescues () const
Return nTrackingRescues.
void trackingRescue () const
Increment the nTrackingRescues counter.
const PackedBoolList & cellHasWallFaces () const
Whether each cell has any wall faces (demand driven data)
const const_iterator begin () const
iterator begin ()
const const_iterator cbegin () const
const const_iterator end () const
iterator end ()
const const_iterator cend () const
void clear ()
void addParticle (ParcelType *pPtr)
Transfer particle to cloud.
void deleteParticle (ParcelType &)
Remove particle from cloud and delete.
void cloudReset (const Cloud< ParcelType > &c)
Reset the particles.
void move (TrackData &td, const scalar trackTime)
Move the particles.
void autoMap (TrackData &td, const mapPolyMesh &)
Remap the cells of particles corresponding to the.
IOobject fieldIOobject (const word &fieldName, const IOobject::readOption r) const
Helper to construct IOobject for field and current time.
void checkFieldIOobject (const Cloud< ParcelType > &c, const IOField< DataType > &data) const
Check lagrangian data field.
void checkFieldFieldIOobject (const Cloud< ParcelType > &c, const CompactIOField< Field< DataType >, DataType > &data) const
Check lagrangian data fieldfield.
virtual void readFields ()
Read the field data for the cloud of particles. Dummy at.
virtual void writeFields () const
Write the field data for the cloud of particles Dummy at.
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write using given format, version and compression.
void writePositions () const
Write positions to <cloudName>_positions.obj file.
Public Member Functions inherited from cloud
TypeName ("cloud")
Runtime type information.
cloud (const objectRegistry &, const word &cloudName="")
Construct for the given objectRegistry and named cloud instance.
virtual ~cloud ()
Destructor.
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject * >
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash >> &)
Construct by transferring the parameter contents.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from IDLList< ParcelType >
IDLList ()
Null construct.
IDLList (const ParcelType &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< ParcelType > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, ParcelType >
ILList ()
Null construct.
ILList (ParcelType *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, ParcelType > &)
Construct as copy.
ILList (const ILList< DLListBase, ParcelType > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (ParcelType *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, ParcelType > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, ParcelType > &)
Public Member Functions inherited from UILList< DLListBase, ParcelType >
UILList ()
Null construct.
UILList (ParcelType *a)
Construct given initial T.
UILList (const UILList< DLListBase, ParcelType > &)
Construct as copy.
ParcelType * first ()
Return the first entry.
const ParcelType * first () const
Return the first entry.
ParcelType * last ()
Return the last entry.
const ParcelType * last () const
Return the last entry.
ParcelType * removeHead ()
Remove and return head.
ParcelType * remove (ParcelType *p)
Remove and return element.
ParcelType * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, ParcelType > &)
iterator begin ()
const_iterator begin () const
const iterator & end ()
const const_iterator & end () const
const_iterator cbegin () const
const const_iterator & cend () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< DLListBase, ParcelType > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, ParcelType > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Public Member Functions inherited from DSMCBaseCloud
TypeName ("DSMCBaseCloud")
Runtime type information.
DSMCBaseCloud ()
Null constructor.
virtual ~DSMCBaseCloud ()
Destructor.
Public Member Functions inherited from kinematicCloud
TypeName ("kinematicCloud")
Runtime type information.
kinematicCloud ()
Null constructor.
virtual ~kinematicCloud ()
Destructor.
Protected Member Functions
void setModels ()
Set cloud sub-models.
template<class TrackData >
void solve (TrackData &td)
Solve the cloud - calls all evolution functions.
void buildCellOccupancy ()
Build the cellOccupancy.
void updateCellOccupancy ()
Update (i.e. build) the cellOccupancy if it has.
template<class TrackData >
void evolveCloud (TrackData &td)
Evolve the cloud.
void postEvolve ()
Post-evolve.
void cloudReset (KinematicCloud< CloudType > &c)
Reset state of cloud.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
const fvMesh & mesh_
References to the mesh and time databases.
IOdictionary particleProperties_
Dictionary of particle properties.
IOdictionary outputProperties_
Dictionary of output properties.
cloudSolution solution_
Solution properties.
parcelType::constantProperties constProps_
Parcel constant properties.
const dictionary subModelProperties_
Sub-models dictionary.
cachedRandom rndGen_
Random number generator - used by some injection routines.
autoPtr< List< DynamicList< parcelType * > > > cellOccupancyPtr_
Cell occupancy information for each parcel, (demand driven)
scalarField cellLengthScale_
Cell length scale.
const volScalarField & rho_
Density [kg/m3].
const volVectorField & U_
Velocity [m/s].
const volScalarField & mu_
Dynamic viscosity [Pa.s].
const dimensionedVector & g_
Gravity.
scalar pAmbient_
Averaged ambient domain pressure.
forceType forces_
Optional particle forces.
functionType functions_
Optional cloud function objects.
InjectionModelList< KinematicCloud< CloudType > > injectors_
Injector models.
autoPtr< DispersionModel< KinematicCloud< CloudType > > > dispersionModel_
Dispersion model.
autoPtr< PatchInteractionModel< KinematicCloud< CloudType > > > patchInteractionModel_
Patch interaction model.
autoPtr< StochasticCollisionModel< KinematicCloud< CloudType > > > stochasticCollisionModel_
Stochastic collision model.
autoPtr< SurfaceFilmModel< KinematicCloud< CloudType > > > surfaceFilmModel_
Surface film model.
autoPtr< vectorIntegrationScheme > UIntegrator_
Velocity integration.
autoPtr< DimensionedField< vector, volMesh > > UTrans_
Momentum.
autoPtr< DimensionedField< scalar, volMesh > > UCoeff_
Coefficient for carrier phase U equation.
Additional Inherited Members
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from Cloud< ParcelType >
static word cloudPropertiesName
Name of cloud properties dictionary.
Static Public Attributes inherited from cloud
static const word prefix
The prefix to local: lagrangian.
static word defaultName
The default cloud name: defaultCloud.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class CloudType>
class Foam::KinematicCloud< CloudType >
Templated base class for kinematic cloud.
- cloud function objects
particle forces, e.g.
buoyancy
drag
pressure gradient
...
sub-models:
dispersion model
injection model
patch interaction model
stochastic collision model
surface film model
Source files
KinematicCloud.H
KinematicCloudI.H
KinematicCloud.C
Definition at line 96 of file KinematicCloud.H.
Member Typedef Documentation
typedef CloudType cloudType
Type of cloud this cloud was instantiated for.
Definition at line 106 of file KinematicCloud.H.
typedef CloudType::particleType parcelType
Type of parcel the cloud was instantiated for.
Definition at line 109 of file KinematicCloud.H.
typedef KinematicCloud<CloudType> kinematicCloudType
Convenience typedef for this cloud type.
Definition at line 112 of file KinematicCloud.H.
typedef ParticleForceList<KinematicCloud<CloudType> > forceType
Force models type.
Definition at line 115 of file KinematicCloud.H.
typedef CloudFunctionObjectList<KinematicCloud<CloudType> > functionType
Function object type.
Definition at line 119 of file KinematicCloud.H.
Constructor & Destructor Documentation
KinematicCloud (const word & cloudName, const volScalarField & rho, const volVectorField & U, const volScalarField & mu, const dimensionedVector & g, bool readFields = true)
Construct given carrier gas fields.
Definition at line 274 of file KinematicCloud.C.
References Foam::readFields().
KinematicCloud (KinematicCloud< CloudType > & c, const word & name)
Copy constructor with new name.
Definition at line 409 of file KinematicCloud.C.
KinematicCloud (const fvMesh & mesh, const word & name, const KinematicCloud< CloudType > & c)
Copy constructor with new name - creates bare cloud.
Definition at line 476 of file KinematicCloud.C.
~KinematicCloud () virtual
Destructor.
Definition at line 538 of file KinematicCloud.C.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Member Function Documentation
void setModels () protected
Set cloud sub-models.
Definition at line 40 of file KinematicCloud.C.
References Foam::New().
void solve (TrackData & td) protected
Solve the cloud - calls all evolution functions.
Definition at line 91 of file KinematicCloud.C.
void buildCellOccupancy () protected
Build the cellOccupancy.
Definition at line 130 of file KinematicCloud.C.
References List< T >::append(), cellOccupancy, List< T >::clear(), forAll, and forAllIter.
void updateCellOccupancy () protected
Update (i.e. build) the cellOccupancy if it has.
already been used
Definition at line 162 of file KinematicCloud.C.
void evolveCloud (TrackData & td) protected
Evolve the cloud.
Definition at line 176 of file KinematicCloud.C.
References surfaceFilm.
void postEvolve () protected
Post-evolve.
Definition at line 219 of file KinematicCloud.C.
References Foam::endl(), and Foam::Info.
void cloudReset (KinematicCloud< CloudType > & c) protected
Reset state of cloud.
Definition at line 249 of file KinematicCloud.C.
References KinematicCloud< CloudType >::dispersionModel_, KinematicCloud< CloudType >::forces_, KinematicCloud< CloudType >::functions_, KinematicCloud< CloudType >::injectors_, KinematicCloud< CloudType >::patchInteractionModel_, KinematicCloud< CloudType >::rndGen_, KinematicCloud< CloudType >::stochasticCollisionModel_, KinematicCloud< CloudType >::surfaceFilmModel_, and KinematicCloud< CloudType >::UIntegrator_.
virtual autoPtr<Cloud<parcelType> > clone (const word & name) inline virtual
Construct and return clone based on (this) with new name.
Reimplemented in CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >.
Definition at line 297 of file KinematicCloud.H.
virtual autoPtr<Cloud<parcelType> > cloneBare (const word & name) const inline virtual
Construct and return bare clone based on (this) with new name.
Reimplemented in CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >.
Definition at line 306 of file KinematicCloud.H.
const Foam::KinematicCloud< CloudType > & cloudCopy () const inline
Return a reference to the cloud copy.
Definition at line 33 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
bool hasWallImpactDistance () const virtual
Switch to specify if particles of the cloud can return.
non-zero wall distance values - true for kinematic parcels
Reimplemented from Cloud< ParcelType >.
Reimplemented in CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >.
Definition at line 545 of file KinematicCloud.C.
References KinematicCloud< CloudType >::setParcelThermoProperties().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::fvMesh & mesh () const inline
Return reference to the mesh.
Definition at line 40 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::IOdictionary & particleProperties () const inline
Return particle properties dictionary.
Definition at line 48 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::IOdictionary & outputProperties () const inline
Return output properties dictionary.
Definition at line 56 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::IOdictionary & outputProperties () inline
Return non-const access to the output properties dictionary.
Definition at line 63 of file KinematicCloudI.H.
const Foam::cloudSolution & solution () const inline
Return const access to the solution properties.
Definition at line 71 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::cloudSolution & solution () inline
Return access to the solution properties.
Definition at line 78 of file KinematicCloudI.H.
const CloudType::particleType::constantProperties & constProps () const inline
Return the constant properties.
Definition at line 86 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
CloudType::particleType::constantProperties & constProps () inline
Return access to the constant properties.
Definition at line 94 of file KinematicCloudI.H.
const Foam::dictionary & subModelProperties () const inline
Return reference to the sub-models dictionary.
Definition at line 102 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::cachedRandom & rndGen () inline
Return reference to the random object.
Definition at line 359 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::List< Foam::DynamicList< typename CloudType::particleType * > > & cellOccupancy () inline
Return the cell occupancy information for each.
parcel, non-const access, the caller is responsible for updating it for its own purposes if particles are removed or created.
Definition at line 367 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::scalarField & cellLengthScale () const inline
Return the cell length scale.
Definition at line 380 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::volVectorField & U () const inline
Return carrier gas velocity.
Definition at line 116 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::volScalarField & rho () const inline
Return carrier gas density.
Definition at line 109 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::volScalarField & mu () const inline
Return carrier gas dynamic viscosity.
Definition at line 123 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::dimensionedVector & g () const inline
Gravity.
Definition at line 130 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::scalar pAmbient () const inline
Return const-access to the ambient pressure.
Definition at line 137 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::scalar & pAmbient () inline
Return reference to the ambient pressure.
Definition at line 144 of file KinematicCloudI.H.
const Foam::KinematicCloud< CloudType >::forceType & forces () const inline
Optional particle forces.
Definition at line 153 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::KinematicCloud< CloudType >::forceType & forces () inline
Return the optional particle forces.
Definition at line 161 of file KinematicCloudI.H.
Foam::KinematicCloud< CloudType >::functionType & functions () inline
Optional cloud function objects.
Definition at line 169 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::InjectionModelList< Foam::KinematicCloud< CloudType > > & injectors () const inline
Return const access to the injection model.
Definition at line 177 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::InjectionModelList< Foam::KinematicCloud< CloudType > > & injectors () inline
Return reference to the injection model.
Definition at line 185 of file KinematicCloudI.H.
const Foam::DispersionModel< Foam::KinematicCloud< CloudType > > & dispersion () const inline
Return const-access to the dispersion model.
Definition at line 193 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::DispersionModel< Foam::KinematicCloud< CloudType > > & dispersion () inline
Return reference to the dispersion model.
Definition at line 201 of file KinematicCloudI.H.
const Foam::PatchInteractionModel< Foam::KinematicCloud< CloudType > > & patchInteraction () const inline
Return const-access to the patch interaction model.
Definition at line 209 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::PatchInteractionModel< Foam::KinematicCloud< CloudType > > & patchInteraction () inline
Return reference to the patch interaction model.
Definition at line 217 of file KinematicCloudI.H.
const Foam::StochasticCollisionModel< Foam::KinematicCloud< CloudType > > & stochasticCollision () const inline
Return const-access to the stochastic collision model.
Definition at line 225 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::StochasticCollisionModel< Foam::KinematicCloud< CloudType > > & stochasticCollision () inline
Return reference to the stochastic collision model.
Definition at line 233 of file KinematicCloudI.H.
const Foam::SurfaceFilmModel< Foam::KinematicCloud< CloudType > > & surfaceFilm () const inline
Return const-access to the surface film model.
Definition at line 241 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::SurfaceFilmModel< Foam::KinematicCloud< CloudType > > & surfaceFilm () inline
Return reference to the surface film model.
Definition at line 249 of file KinematicCloudI.H.
const Foam::vectorIntegrationScheme & UIntegrator () const inline
Return reference to velocity integration.
Definition at line 257 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::DimensionedField< Foam::vector, Foam::volMesh > & UTrans () inline
Return reference to momentum source.
Definition at line 388 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), and KinematicCloud< CloudType >::relaxSources().
const Foam::DimensionedField< Foam::vector, Foam::volMesh > & UTrans () const inline
Return const reference to momentum source.
Definition at line 396 of file KinematicCloudI.H.
Foam::DimensionedField< Foam::scalar, Foam::volMesh > & UCoeff () inline
Return coefficient for carrier phase U equation.
Definition at line 404 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), and KinematicCloud< CloudType >::relaxSources().
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & UCoeff () const inline
Return const coefficient for carrier phase U equation.
Definition at line 412 of file KinematicCloudI.H.
Foam::tmp< Foam::fvVectorMatrix > SU (volVectorField & U) const inline
Return tmp momentum source term.
Definition at line 420 of file KinematicCloudI.H.
References Foam::dimForce, Foam::endl(), Foam::Info, Foam::max(), Foam::min(), Foam::nl, tmp< T >::ref(), fvMatrix< Type >::source(), Foam::fvc::Sp(), and U.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::label nParcels () const inline virtual
Total number of parcels.
Implements kinematicCloud.
Definition at line 264 of file KinematicCloudI.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::scalar massInSystem () const inline virtual
Total mass in system.
Implements kinematicCloud.
Definition at line 271 of file KinematicCloudI.H.
References forAllConstIter(), and p.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::vector linearMomentumOfSystem () const inline virtual
Total linear momentum of the system.
Implements kinematicCloud.
Definition at line 286 of file KinematicCloudI.H.
References forAllConstIter(), p, and Foam::Zero.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::scalar linearKineticEnergyOfSystem () const inline virtual
Total linear kinetic energy in the system.
Implements kinematicCloud.
Definition at line 303 of file KinematicCloudI.H.
References KinematicCloud< CloudType >::Dij(), forAllConstIter(), and p.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
scalar rotationalKineticEnergyOfSystem () const inline
Total rotational kinetic energy in the system.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Foam::scalar Dij (const label i, const label j) const inline virtual
Mean diameter Dij.
Implements kinematicCloud.
Definition at line 320 of file KinematicCloudI.H.
References forAllConstIter(), Foam::max(), p, Foam::pow(), and Foam::reduce().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), and KinematicCloud< CloudType >::linearKineticEnergyOfSystem().
Foam::scalar Dmax () const inline virtual
Max diameter.
Implements kinematicCloud.
Definition at line 343 of file KinematicCloudI.H.
References forAllConstIter(), Foam::max(), p, and Foam::reduce().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::tmp< Foam::volScalarField > vDotSweep () const inline virtual
Volume swept rate of parcels per cell.
Implements kinematicCloud.
Definition at line 456 of file KinematicCloudI.H.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dimless, Foam::dimTime, forAllConstIter(), Foam::mag(), Foam::name(), p, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), tmp< T >::ref(), and timeName.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::tmp< Foam::volScalarField > theta () const inline virtual
Return the particle volume fraction field.
Note: for particles belonging to this cloud only
Implements kinematicCloud.
Definition at line 495 of file KinematicCloudI.H.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dimless, forAllConstIter(), Foam::name(), p, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), tmp< T >::ref(), and timeName.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::tmp< Foam::volScalarField > alpha () const inline virtual
Return the particle mass fraction field.
Note: for particles belonging to this cloud only
Implements kinematicCloud.
Definition at line 534 of file KinematicCloudI.H.
References Foam::constant::atomic::alpha, Foam::dimless, forAllConstIter(), Foam::name(), p, tmp< T >::ref(), and timeName.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
const Foam::tmp< Foam::volScalarField > rhoEff () const inline virtual
Return the particle effective density field.
Note: for particles belonging to this cloud only
Implements kinematicCloud.
Definition at line 571 of file KinematicCloudI.H.
References Foam::dimDensity, forAllConstIter(), Foam::name(), p, tmp< T >::ref(), and timeName.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void setParcelThermoProperties (parcelType & parcel, const scalar lagrangianDt)
Set parcel thermo properties.
Definition at line 553 of file KinematicCloud.C.
References KinematicCloud< CloudType >::checkParcelProperties().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), and KinematicCloud< CloudType >::hasWallImpactDistance().
void checkParcelProperties (parcelType & parcel, const scalar lagrangianDt, const bool fullyDescribed)
Check parcel properties.
Definition at line 564 of file KinematicCloud.C.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), and KinematicCloud< CloudType >::setParcelThermoProperties().
void storeState ()
Store the current cloud state.
Definition at line 581 of file KinematicCloud.C.
References Foam::name().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void restoreState ()
Reset the current cloud to the previously stored state.
Definition at line 594 of file KinematicCloud.C.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void resetSourceTerms ()
Reset the cloud source terms.
Definition at line 602 of file KinematicCloud.C.
References KinematicCloud< CloudType >::relax(), and Foam::Zero.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void relax (DimensionedField< Type, volMesh > & field, const DimensionedField< Type, volMesh > & field0, const word & name) const
Relax field.
Definition at line 612 of file KinematicCloud.C.
References KinematicCloud< CloudType >::scale().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), and KinematicCloud< CloudType >::resetSourceTerms().
void scale (DimensionedField< Type, volMesh > & field, const word & name) const
Scale field.
Definition at line 626 of file KinematicCloud.C.
References KinematicCloud< CloudType >::relaxSources().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), and KinematicCloud< CloudType >::relax().
void relaxSources (const KinematicCloud< CloudType > & cloudOldTime)
Apply relaxation to (steady state) cloud sources.
Definition at line 638 of file KinematicCloud.C.
References relax(), KinematicCloud< CloudType >::UCoeff(), and KinematicCloud< CloudType >::UTrans().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), and KinematicCloud< CloudType >::scale().
void scaleSources ()
Apply scaling to (transient) cloud sources.
Definition at line 648 of file KinematicCloud.C.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void preEvolve ()
Pre-evolve.
Definition at line 656 of file KinematicCloud.C.
References Foam::endl(), Foam::Info, and Foam::name().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void evolve ()
Evolve the cloud.
Definition at line 676 of file KinematicCloud.C.
References solve().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void motion (TrackData & td)
Particle motion.
Definition at line 690 of file KinematicCloud.C.
References KinematicCloud< CloudType >::patchData().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void patchData (const parcelType & p, const polyPatch & pp, const scalar trackFraction, const tetIndices & tetIs, vector & normal, vector & Up) const
Calculate the patch normal and velocity to interact with,.
accounting for patch motion if required.
Definition at line 701 of file KinematicCloud.C.
References Foam::asin(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Vector< Cmpt >::centre(), tetIndices::faceTri(), patchIdentifier::index(), Foam::mag(), n, triangle< Point, PointRef >::normal(), tetIndices::oldFaceTri(), patchi, U, polyPatch::whichFace(), and Foam::Zero.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), and KinematicCloud< CloudType >::motion().
void updateMesh ()
Update mesh.
Definition at line 846 of file KinematicCloud.C.
References Foam::cbrt().
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void autoMap (const mapPolyMesh & mapper) virtual
Remap the cells of particles corresponding to the.
mesh topology change with a default tracking data object
Reimplemented from DSMCCloud< ParcelType >.
Definition at line 855 of file KinematicCloud.C.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
void info ()
Print cloud information.
Definition at line 868 of file KinematicCloud.C.
References Foam::Info, Foam::mag(), Foam::name(), Foam::nl, Foam::reduce(), Foam::returnReduce(), and surfaceFilm.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare().
Member Data Documentation
const fvMesh& mesh_ protected
References to the mesh and time databases.
Definition at line 144 of file KinematicCloud.H.
IOdictionary particleProperties_ protected
Dictionary of particle properties.
Definition at line 147 of file KinematicCloud.H.
IOdictionary outputProperties_ protected
Dictionary of output properties.
Definition at line 150 of file KinematicCloud.H.
cloudSolution solution_ protected
Solution properties.
Definition at line 153 of file KinematicCloud.H.
parcelType::constantProperties constProps_ protected
Parcel constant properties.
Definition at line 156 of file KinematicCloud.H.
const dictionary subModelProperties_ protected
Sub-models dictionary.
Definition at line 159 of file KinematicCloud.H.
cachedRandom rndGen_ protected
Random number generator - used by some injection routines.
Definition at line 162 of file KinematicCloud.H.
Referenced by KinematicCloud< CloudType >::cloudReset().
autoPtr<List<DynamicList<parcelType*> > > cellOccupancyPtr_ protected
Cell occupancy information for each parcel, (demand driven)
Definition at line 165 of file KinematicCloud.H.
scalarField cellLengthScale_ protected
Cell length scale.
Definition at line 168 of file KinematicCloud.H.
const volScalarField& rho_ protected
Density [kg/m3].
Definition at line 174 of file KinematicCloud.H.
const volVectorField& U_ protected
Velocity [m/s].
Definition at line 177 of file KinematicCloud.H.
const volScalarField& mu_ protected
Dynamic viscosity [Pa.s].
Definition at line 180 of file KinematicCloud.H.
const dimensionedVector& g_ protected
Gravity.
Definition at line 186 of file KinematicCloud.H.
scalar pAmbient_ protected
Averaged ambient domain pressure.
Definition at line 189 of file KinematicCloud.H.
forceType forces_ protected
Optional particle forces.
Definition at line 193 of file KinematicCloud.H.
Referenced by KinematicCloud< CloudType >::cloudReset().
functionType functions_ protected
Optional cloud function objects.
Definition at line 196 of file KinematicCloud.H.
Referenced by KinematicCloud< CloudType >::cloudReset().
InjectionModelList<KinematicCloud<CloudType> > injectors_ protected
Injector models.
Definition at line 202 of file KinematicCloud.H.
Referenced by KinematicCloud< CloudType >::cloudReset().
autoPtr<DispersionModel<KinematicCloud<CloudType> > > dispersionModel_ protected
Dispersion model.
Definition at line 206 of file KinematicCloud.H.
Referenced by KinematicCloud< CloudType >::cloudReset().
autoPtr<PatchInteractionModel<KinematicCloud<CloudType> > > patchInteractionModel_ protected
Patch interaction model.
Definition at line 210 of file KinematicCloud.H.
Referenced by KinematicCloud< CloudType >::cloudReset().
autoPtr<StochasticCollisionModel<KinematicCloud<CloudType> > > stochasticCollisionModel_ protected
Stochastic collision model.
Definition at line 214 of file KinematicCloud.H.
Referenced by KinematicCloud< CloudType >::cloudReset().
autoPtr<SurfaceFilmModel<KinematicCloud<CloudType> > > surfaceFilmModel_ protected
Surface film model.
Definition at line 218 of file KinematicCloud.H.
Referenced by KinematicCloud< CloudType >::cloudReset().
autoPtr<vectorIntegrationScheme> UIntegrator_ protected
Velocity integration.
Definition at line 224 of file KinematicCloud.H.
Referenced by KinematicCloud< CloudType >::cloudReset().
autoPtr<DimensionedField<vector, volMesh> > UTrans_ protected
Momentum.
Definition at line 230 of file KinematicCloud.H.
autoPtr<DimensionedField<scalar, volMesh> > UCoeff_ protected
Coefficient for carrier phase U equation.
Definition at line 233 of file KinematicCloud.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.H
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.C
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloudI.H