OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
leastSquaresGrad< Type > Class Template Reference
Second-order gradient scheme using least-squares.
Public Member Functions
TypeName ("leastSquares")
Runtime type information.
leastSquaresGrad (const fvMesh &mesh)
Construct from mesh.
leastSquaresGrad (const fvMesh &mesh, Istream &)
Construct from Istream.
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
Return the gradient of the given field to the gradScheme::grad.
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Detailed Description
template<class Type>
class Foam::fv::leastSquaresGrad< Type >
Second-order gradient scheme using least-squares.
Source files
leastSquaresGrad.H
leastSquaresGrad.C
Definition at line 54 of file leastSquaresGrad.H.
Constructor & Destructor Documentation
leastSquaresGrad (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 76 of file leastSquaresGrad.H.
leastSquaresGrad (const fvMesh & mesh, Istream &) inline
Construct from Istream.
Definition at line 82 of file leastSquaresGrad.H.
References leastSquaresGrad< Type >::calcGrad(), and Foam::name().
Member Function Documentation
TypeName ("leastSquares")
Runtime type information.
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const virtual
Return the gradient of the given field to the gradScheme::grad.
for optional caching
Implements gradScheme< Type >.
Referenced by leastSquaresGrad< Type >::leastSquaresGrad().
The documentation for this class was generated from the following file:
src/finiteVolume/finiteVolume/gradSchemes/leastSquaresGrad/leastSquaresGrad.H