OpenFOAM: kOmegaSSTDES< BasicTurbulenceModel > Class Template Reference
kOmegaSSTDES< BasicTurbulenceModel > Class Template Reference
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTDES")
Runtime type information.
kOmegaSSTDES (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSSTDES ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
Protected Member Functions
tmp< volScalarField > Lt () const
Return the turbulent length-scale.
virtual tmp< volScalarField > FDES (const volScalarField &F1, const volScalarField &F2) const
The DES dissipation-rate multiplier with options zonal filtering.
virtual tmp< volScalarField > epsilonByk (const volScalarField &F1, const volScalarField &F2) const
Return epsilon/k which for standard RAS is betaStar*omega.
Protected Attributes
dimensionedScalar CDES_
DES coefficient.
direction FSST_
Zonal filter choice.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::kOmegaSSTDES< BasicTurbulenceModel >
Definition at line 74 of file kOmegaSSTDES.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 123 of file kOmegaSSTDES.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 124 of file kOmegaSSTDES.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 125 of file kOmegaSSTDES.H.
Constructor & Destructor Documentation
kOmegaSSTDES (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 83 of file kOmegaSSTDES.C.
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::epsilonByk().
virtual ~kOmegaSSTDES () inline virtual
Destructor.
Definition at line 149 of file kOmegaSSTDES.H.
References kOmegaSSTDES< BasicTurbulenceModel >::read().
Member Function Documentation
tmp< volScalarField > Lt () const protected
Return the turbulent length-scale.
Definition at line 38 of file kOmegaSSTDES.C.
References kOmegaSSTDES< BasicTurbulenceModel >::FDES(), and Foam::sqrt().
tmp< volScalarField > FDES (const volScalarField & F1, const volScalarField & F2) const protected virtual
The DES dissipation-rate multiplier with options zonal filtering.
based on either F1 or F2
Definition at line 46 of file kOmegaSSTDES.C.
References delta, kOmegaSSTDES< BasicTurbulenceModel >::epsilonByk(), Foam::exit(), F1, Foam::FatalError, FatalErrorInFunction, and Foam::max().
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::Lt().
tmp< volScalarField > epsilonByk (const volScalarField & F1, const volScalarField & F2) const protected virtual
Return epsilon/k which for standard RAS is betaStar*omega.
Definition at line 70 of file kOmegaSSTDES.C.
References kOmegaSSTDES< BasicTurbulenceModel >::kOmegaSSTDES().
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::FDES().
TypeName ("kOmegaSSTDES< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Read model coefficients if they have changed.
Definition at line 131 of file kOmegaSSTDES.C.
References Foam::read().
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::~kOmegaSSTDES().
Member Data Documentation
dimensionedScalar CDES_ protected
DES coefficient.
Definition at line 90 of file kOmegaSSTDES.H.
direction FSST_ protected
Zonal filter choice.
0: no filtering
1: (1 - F1)
2: (1 - F2)
Definition at line 97 of file kOmegaSSTDES.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/kOmegaSSTDES/kOmegaSSTDES.H
src/TurbulenceModels/turbulenceModels/LES/kOmegaSSTDES/kOmegaSSTDES.C