OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
isNotEqOp< T > Class Template Reference
Public Member Functions
void operator() (T &x, const T &y) const
Detailed Description
template<class T>
class Foam::isNotEqOp< T >
Definition at line 38 of file probesTemplates.C.
Member Function Documentation
void operator() (T & x, const T & y) const inline
Definition at line 42 of file probesTemplates.C.
References HashTable< regIOobject * >::const_iterator, IOstream::defaultPrecision(), HashTableCore::end(), Foam::endl(), fields, forAll, UPstream::master(), IOobject::MUST_READ, IOobject::name(), IOobject::NO_WRITE, probes::sample(), Foam::setw(), Foam::T(), IOobject::time(), Foam::type(), and y.
The documentation for this class was generated from the following file:
src/sampling/probes/probesTemplates.C