OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LienCubicKE Class Reference
Lien cubic non-linear low-Reynolds k-epsilon turbulence models for incompressible flows.
Public Member Functions
TypeName ("LienCubicKE")
Runtime type information.
LienCubicKE (const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~LienCubicKE ()
Destructor.
virtual bool read ()
Read RASProperties dictionary.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from nonlinearEddyViscosity< incompressible::RASModel >
nonlinearEddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~nonlinearEddyViscosity ()
Destructor.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from eddyViscosity< incompressible::RASModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
Public Member Functions inherited from linearViscousStress< incompressible::RASModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
Public Member Functions inherited from SpecificIncompressibleTurbulenceModel< BasicIncompressibleTurbulenceModel >
SpecificIncompressibleTurbulenceModel (const word &type, const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~SpecificIncompressibleTurbulenceModel ()
Destructor.
Protected Member Functions
tmp< volScalarField > fMu () const
tmp< volScalarField > f2 () const
tmp< volScalarField > E (const volScalarField &f2) const
virtual void correctNut ()
virtual void correctNonlinearStress (const volTensorField &gradU)
Protected Attributes
dimensionedScalar Ceps1_
dimensionedScalar Ceps2_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
dimensionedScalar Cmu1_
dimensionedScalar Cmu2_
dimensionedScalar Cbeta_
dimensionedScalar Cbeta1_
dimensionedScalar Cbeta2_
dimensionedScalar Cbeta3_
dimensionedScalar Cgamma1_
dimensionedScalar Cgamma2_
dimensionedScalar Cgamma4_
dimensionedScalar Cmu_
dimensionedScalar kappa_
dimensionedScalar Anu_
dimensionedScalar AE_
volScalarField k_
volScalarField epsilon_
const volScalarField & y_
Wall distance.
Protected Attributes inherited from nonlinearEddyViscosity< incompressible::RASModel >
volSymmTensorField nonlinearStress_
Protected Attributes inherited from eddyViscosity< incompressible::RASModel >
volScalarField nut_
Additional Inherited Members
Public Types inherited from nonlinearEddyViscosity< incompressible::RASModel >
typedef
incompressible::RASModel::alphaField alphaField
typedef
incompressible::RASModel::rhoField rhoField
typedef
incompressible::RASModel::transportModel transportModel
Public Types inherited from eddyViscosity< incompressible::RASModel >
typedef
incompressible::RASModel::alphaField alphaField
typedef
incompressible::RASModel::rhoField rhoField
typedef
incompressible::RASModel::transportModel transportModel
Public Types inherited from linearViscousStress< incompressible::RASModel >
typedef
incompressible::RASModel::alphaField alphaField
typedef
incompressible::RASModel::rhoField rhoField
typedef
incompressible::RASModel::transportModel transportModel
Public Types inherited from SpecificIncompressibleTurbulenceModel< BasicIncompressibleTurbulenceModel >
typedef
BasicIncompressibleTurbulenceModel::transportModel transportModel
Static Public Member Functions inherited from SpecificIncompressibleTurbulenceModel< BasicIncompressibleTurbulenceModel >
static autoPtr
< SpecificIncompressibleTurbulenceModel > New (const volVectorField &U, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
Lien cubic non-linear low-Reynolds k-epsilon turbulence models for incompressible flows.
This turbulence model is described in:
    Lien, F.S., Chen, W.L. & Leschziner, M.A. (1996).
    Low-Reynolds-number eddy-viscosity modeling based on non-linear
    stress-strain/vorticity relations.
    Engineering Turbulence Modelling and Experiments 3, 91-100.
Implemented according to the specification in: Apsley: Turbulence Models 2002
In addition to the low-Reynolds number damping functions support for wall-functions is also included to allow for low- and high-Reynolds number operation.
See Also
Foam::incompressible::RASModels::ShihQuadraticKE
Source files
LienCubicKE.H
LienCubicKE.C
Definition at line 77 of file LienCubicKE.H.
Constructor & Destructor Documentation
LienCubicKE (const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 123 of file LienCubicKE.C.
References Foam::bound().
virtual ~LienCubicKE () inline virtual
Destructor.
Definition at line 152 of file LienCubicKE.H.
Member Function Documentation
tmp< volScalarField > fMu () const protected
Definition at line 47 of file LienCubicKE.C.
References LienCubicKE::Anu_, LienCubicKE::Cmu_, Foam::exp(), LienCubicKE::k_, LienCubicKE::kappa_, nu, Foam::pow(), Foam::sqrt(), and LienCubicKE::y_.
Referenced by LienCubicKE::correctNonlinearStress().
tmp< volScalarField > f2 () const protected
Definition at line 57 of file LienCubicKE.C.
References LienCubicKE::epsilon_, Foam::exp(), LienCubicKE::k_, nu, and Foam::sqr().
Referenced by LienCubicKE::correct().
tmp< volScalarField > E (const volScalarField & f2) const protected
Definition at line 65 of file LienCubicKE.C.
References LienCubicKE::AE_, LienCubicKE::Ceps2_, LienCubicKE::Cmu_, LienCubicKE::epsilon_, Foam::exp(), LienCubicKE::k_, LienCubicKE::kappa_, nu, Foam::pow(), Foam::sqr(), Foam::sqrt(), and LienCubicKE::y_.
Referenced by LienCubicKE::correct().
void correctNut () protected virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 79 of file LienCubicKE.C.
References LienCubicKE::correctNonlinearStress(), and Foam::fvc::grad().
void correctNonlinearStress (const volTensorField & gradU) protected virtual
Implements nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 85 of file LienCubicKE.C.
References LienCubicKE::Cbeta1_, LienCubicKE::Cbeta2_, LienCubicKE::Cbeta3_, LienCubicKE::Cbeta_, LienCubicKE::Cgamma1_, LienCubicKE::Cgamma2_, LienCubicKE::Cgamma4_, LienCubicKE::Cmu1_, LienCubicKE::Cmu2_, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dev(), LienCubicKE::epsilon_, LienCubicKE::fMu(), Foam::innerSqr(), LienCubicKE::k_, Foam::mag(), Foam::magSqr(), nonlinearEddyViscosity< incompressible::RASModel >::nonlinearStress_, eddyViscosity< incompressible::RASModel >::nut_, Foam::pow3(), Foam::skew(), Foam::sqr(), Foam::sqrt(), Foam::symm(), and Foam::twoSymm().
Referenced by LienCubicKE::correct(), and LienCubicKE::correctNut().
TypeName ("LienCubicKE")
Runtime type information.
bool read () virtual
Read RASProperties dictionary.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 341 of file LienCubicKE.C.
References LienCubicKE::AE_, LienCubicKE::Anu_, LienCubicKE::Cbeta1_, LienCubicKE::Cbeta2_, LienCubicKE::Cbeta3_, LienCubicKE::Cbeta_, LienCubicKE::Ceps1_, LienCubicKE::Ceps2_, LienCubicKE::Cgamma1_, LienCubicKE::Cgamma2_, LienCubicKE::Cgamma4_, LienCubicKE::Cmu1_, LienCubicKE::Cmu2_, LienCubicKE::Cmu_, LienCubicKE::kappa_, dimensioned< Type >::readIfPresent(), LienCubicKE::sigmaEps_, and LienCubicKE::sigmak_.
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 162 of file LienCubicKE.H.
References nu, eddyViscosity< incompressible::RASModel >::nut_, and LienCubicKE::sigmak_.
Referenced by LienCubicKE::correct().
tmp<volScalarField> DepsilonEff () const inline
Return the effective diffusivity for epsilon.
Definition at line 171 of file LienCubicKE.H.
References nu, eddyViscosity< incompressible::RASModel >::nut_, and LienCubicKE::sigmaEps_.
Referenced by LienCubicKE::correct().
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 180 of file LienCubicKE.H.
References LienCubicKE::k_.
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 186 of file LienCubicKE.H.
References LienCubicKE::epsilon_.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 372 of file LienCubicKE.C.
References Foam::bound(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), LienCubicKE::Ceps1_, LienCubicKE::Ceps2_, eddyViscosity< BasicTurbulenceModel >::correct(), LienCubicKE::correctNonlinearStress(), Foam::fvm::ddt(), LienCubicKE::DepsilonEff(), Foam::fvm::div(), LienCubicKE::DkEff(), LienCubicKE::E(), LienCubicKE::epsilon_, LienCubicKE::f2(), Foam::constant::universal::G, Foam::fvc::grad(), LienCubicKE::k_, Foam::fvm::laplacian(), nonlinearEddyViscosity< incompressible::RASModel >::nonlinearStress_, eddyViscosity< incompressible::RASModel >::nut_, Foam::solve(), Foam::fvm::Sp(), and Foam::twoSymm().
Member Data Documentation
dimensionedScalar Ceps1_ protected
Definition at line 88 of file LienCubicKE.H.
Referenced by LienCubicKE::correct(), and LienCubicKE::read().
dimensionedScalar Ceps2_ protected
Definition at line 89 of file LienCubicKE.H.
Referenced by LienCubicKE::correct(), LienCubicKE::E(), and LienCubicKE::read().
dimensionedScalar sigmak_ protected
Definition at line 90 of file LienCubicKE.H.
Referenced by LienCubicKE::DkEff(), and LienCubicKE::read().
dimensionedScalar sigmaEps_ protected
Definition at line 91 of file LienCubicKE.H.
Referenced by LienCubicKE::DepsilonEff(), and LienCubicKE::read().
dimensionedScalar Cmu1_ protected
Definition at line 92 of file LienCubicKE.H.
Referenced by LienCubicKE::correctNonlinearStress(), and LienCubicKE::read().
dimensionedScalar Cmu2_ protected
Definition at line 93 of file LienCubicKE.H.
Referenced by LienCubicKE::correctNonlinearStress(), and LienCubicKE::read().
dimensionedScalar Cbeta_ protected
Definition at line 94 of file LienCubicKE.H.
Referenced by LienCubicKE::correctNonlinearStress(), and LienCubicKE::read().
dimensionedScalar Cbeta1_ protected
Definition at line 95 of file LienCubicKE.H.
Referenced by LienCubicKE::correctNonlinearStress(), and LienCubicKE::read().
dimensionedScalar Cbeta2_ protected
Definition at line 96 of file LienCubicKE.H.
Referenced by LienCubicKE::correctNonlinearStress(), and LienCubicKE::read().
dimensionedScalar Cbeta3_ protected
Definition at line 97 of file LienCubicKE.H.
Referenced by LienCubicKE::correctNonlinearStress(), and LienCubicKE::read().
dimensionedScalar Cgamma1_ protected
Definition at line 98 of file LienCubicKE.H.
Referenced by LienCubicKE::correctNonlinearStress(), and LienCubicKE::read().
dimensionedScalar Cgamma2_ protected
Definition at line 99 of file LienCubicKE.H.
Referenced by LienCubicKE::correctNonlinearStress(), and LienCubicKE::read().
dimensionedScalar Cgamma4_ protected
Definition at line 100 of file LienCubicKE.H.
Referenced by LienCubicKE::correctNonlinearStress(), and LienCubicKE::read().
dimensionedScalar Cmu_ protected
Definition at line 102 of file LienCubicKE.H.
Referenced by LienCubicKE::E(), LienCubicKE::fMu(), and LienCubicKE::read().
dimensionedScalar kappa_ protected
Definition at line 103 of file LienCubicKE.H.
Referenced by LienCubicKE::E(), LienCubicKE::fMu(), and LienCubicKE::read().
dimensionedScalar Anu_ protected
Definition at line 105 of file LienCubicKE.H.
Referenced by LienCubicKE::fMu(), and LienCubicKE::read().
dimensionedScalar AE_ protected
Definition at line 106 of file LienCubicKE.H.
Referenced by LienCubicKE::E(), and LienCubicKE::read().
volScalarField k_ protected
Definition at line 111 of file LienCubicKE.H.
Referenced by LienCubicKE::correct(), LienCubicKE::correctNonlinearStress(), LienCubicKE::E(), LienCubicKE::f2(), LienCubicKE::fMu(), and LienCubicKE::k().
volScalarField epsilon_ protected
Definition at line 112 of file LienCubicKE.H.
Referenced by LienCubicKE::correct(), LienCubicKE::correctNonlinearStress(), LienCubicKE::E(), LienCubicKE::epsilon(), and LienCubicKE::f2().
const volScalarField& y_ protected
Wall distance.
Note: different to wall distance in parent RASModel which is for near-wall cells only
Definition at line 117 of file LienCubicKE.H.
Referenced by LienCubicKE::E(), and LienCubicKE::fMu().
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LienCubicKE/LienCubicKE.H
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LienCubicKE/LienCubicKE.C