OpenFOAM: kOmegaSSTLM< BasicTurbulenceModel > Class Template Reference
kOmegaSSTLM< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
Langtry-Menter 4-equation transitional SST model based on the k-omega-SST RAS model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTLM")
Runtime type information.
kOmegaSSTLM (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSSTLM ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
const volScalarField & ReThetat () const
Access function transition onset momentum-thickness Reynolds number.
const volScalarField & gammaInt () const
Access function to intermittency.
tmp< volScalarField > DReThetatEff () const
Return the effective diffusivity for transition onset.
tmp< volScalarField > DgammaIntEff () const
Return the effective diffusivity for intermittency.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from kOmegaSST< BasicTurbulenceModel >
TypeName ("kOmegaSST")
Runtime type information.
kOmegaSST (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSST ()
Destructor.
Protected Member Functions
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
Modified form of the k-omega SST F1 function.
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
Modified form of the k-omega SST k production rate.
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal &F1, const volScalarField::Internal &F2) const
Modified form of the k-omega SST epsilon/k.
tmp< volScalarField::Internal > Fthetat (const volScalarField::Internal &Us, const volScalarField::Internal &Omega, const volScalarField::Internal &nu) const
Freestream blending-function.
tmp< volScalarField::Internal > ReThetac () const
Empirical correlation for critical Reynolds number where the.
tmp< volScalarField::Internal > Flength (const volScalarField::Internal &nu) const
Empirical correlation that controls the length of the.
tmp< volScalarField::Internal > Fonset (const volScalarField::Internal &Rev, const volScalarField::Internal &ReThetac, const volScalarField::Internal &RT) const
Transition onset location control function.
tmp< volScalarField::Internal > ReThetat0 (const volScalarField::Internal &Us, const volScalarField::Internal &dUsds, const volScalarField::Internal &nu) const
Return the transition onset momentum-thickness Reynolds number.
void correctReThetatGammaInt ()
Solve the turbulence equations and correct the turbulence viscosity.
Protected Attributes
dimensionedScalar ca1_
dimensionedScalar ca2_
dimensionedScalar ce1_
dimensionedScalar ce2_
dimensionedScalar cThetat_
dimensionedScalar sigmaThetat_
scalar lambdaErr_
Convergence criterion for the lambda/thetat loop.
label maxLambdaIter_
Maximum number of iterations to converge the lambda/thetat loop.
const dimensionedScalar deltaU_
Stabilization for division by the magnitude of the velocity.
volScalarField ReThetat_
Transition onset momentum-thickness Reynolds number.
volScalarField gammaInt_
Intermittency.
volScalarField::Internal gammaIntEff_
Effective intermittency.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmegaSSTLM< BasicTurbulenceModel >
Langtry-Menter 4-equation transitional SST model based on the k-omega-SST RAS model.
References:
    Langtry, R. B., & Menter, F. R. (2009).
    Correlation-based transition modeling for unstructured parallelized
    computational fluid dynamics codes.
    AIAA journal, 47(12), 2894-2906.
    Menter, F. R., Langtry, R., & Volker, S. (2006).
    Transition modelling for general purpose CFD codes.
    Flow, turbulence and combustion, 77(1-4), 277-303.
    Langtry, R. B. (2006).
    A correlation-based transition model using local variables for
    unstructured parallelized CFD codes.
    Phd. Thesis, Universität Stuttgart.
The model coefficients are
    kOmegaSSTCoeffs
    {
        // Default SST coefficients
        alphaK1     0.85;
        alphaK2     1;
        alphaOmega1 0.5;
        alphaOmega2 0.856;
        beta1       0.075;
        beta2       0.0828;
        betaStar    0.09;
        gamma1      5/9;
        gamma2      0.44;
        a1          0.31;
        b1          1;
        c1          10;
        F3          no;
        // Default LM coefficients
        ca1         2;
        ca2         0.06;
        ce1         1;
        ce2         50;
        cThetat     0.03;
        sigmaThetat 2;
        lambdaErr   1e-6;
        maxLambdaIter 10;
    }
Source files
kOmegaSSTLM.H
kOmegaSSTLM.C
Definition at line 104 of file kOmegaSSTLM.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 212 of file kOmegaSSTLM.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 213 of file kOmegaSSTLM.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 214 of file kOmegaSSTLM.H.
Constructor & Destructor Documentation
kOmegaSSTLM (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 357 of file kOmegaSSTLM.C.
virtual ~kOmegaSSTLM () inline virtual
Destructor.
Definition at line 238 of file kOmegaSSTLM.H.
References kOmegaSSTLM< BasicTurbulenceModel >::read().
Member Function Documentation
tmp< volScalarField > F1 (const volScalarField & CDkOmega) const protected virtual
Modified form of the k-omega SST F1 function.
Definition at line 39 of file kOmegaSSTLM.C.
References Foam::exp(), F3, Foam::max(), nu, kOmegaSSTLM< BasicTurbulenceModel >::Pk(), Foam::pow(), Foam::Ry(), and Foam::sqrt().
tmp< volScalarField::Internal > Pk (const volScalarField::Internal & G) const protected virtual
Modified form of the k-omega SST k production rate.
Definition at line 52 of file kOmegaSSTLM.C.
References kOmegaSSTLM< BasicTurbulenceModel >::epsilonByk(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::Pk().
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::F1().
tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal & F1, const volScalarField::Internal & F2) const protected virtual
Modified form of the k-omega SST epsilon/k.
Definition at line 62 of file kOmegaSSTLM.C.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::epsilonByk(), kOmegaSSTLM< BasicTurbulenceModel >::Fthetat(), Foam::max(), and Foam::min().
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::Pk().
tmp< volScalarField::Internal > Fthetat (const volScalarField::Internal & Us, const volScalarField::Internal & Omega, const volScalarField::Internal & nu) const protected
Freestream blending-function.
Definition at line 75 of file kOmegaSSTLM.C.
References delta, Foam::exp(), IOobject::groupName(), Foam::max(), Foam::min(), Foam::pow4(), Foam::sqr(), and y.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::epsilonByk().
tmp< volScalarField::Internal > ReThetac () const protected
Empirical correlation for critical Reynolds number where the.
intermittency first starts to increase in the boundary layer
Definition at line 109 of file kOmegaSSTLM.C.
References Foam::dimless, kOmegaSSTLM< BasicTurbulenceModel >::Flength(), forAll, IOobject::groupName(), Foam::pow3(), Foam::pow4(), and Foam::sqr().
tmp< volScalarField::Internal > Flength (const volScalarField::Internal & nu) const protected
Empirical correlation that controls the length of the.
transition region
Definition at line 150 of file kOmegaSSTLM.C.
References Foam::dimless, Foam::e, Foam::exp(), forAll, IOobject::groupName(), Foam::pow3(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0(), Foam::sqr(), and y.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::ReThetac().
tmp< volScalarField::Internal > Fonset (const volScalarField::Internal & Rev, const volScalarField::Internal & ReThetac, const volScalarField::Internal & RT) const protected
Transition onset location control function.
Definition at line 327 of file kOmegaSSTLM.C.
References IOobject::groupName(), Foam::max(), Foam::min(), Foam::pow3(), and Foam::pow4().
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0().
tmp< volScalarField::Internal > ReThetat0 (const volScalarField::Internal & Us, const volScalarField::Internal & dUsds, const volScalarField::Internal & nu) const protected
Return the transition onset momentum-thickness Reynolds number.
(based on freestream conditions)
Definition at line 213 of file kOmegaSSTLM.C.
References Foam::dimless, Foam::endl(), Foam::exp(), kOmegaSSTLM< BasicTurbulenceModel >::Fonset(), forAll, IOobject::groupName(), k, lambda(), Foam::mag(), Foam::max(), Foam::min(), Foam::pow(), Foam::pow3(), Foam::sqr(), Foam::sqrt(), and WarningInFunction.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::Flength().
void correctReThetatGammaInt () protected
Solve the turbulence equations and correct the turbulence viscosity.
Definition at line 509 of file kOmegaSSTLM.C.
References Foam::constant::atomic::alpha, Foam::bound(), tmp< T >::clear(), optionList::constrain(), optionList::correct(), Foam::fvm::ddt(), Foam::fvm::div(), Foam::exp(), fvOptions, Foam::fvc::grad(), k, Foam::fvm::laplacian(), Foam::mag(), Foam::magSqr(), Foam::max(), Foam::min(), options::New(), nu, Foam::pow4(), tmp< T >::ref(), rho, Foam::skew(), Foam::solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::sqrt(), Foam::symm(), U, and y.
TypeName ("kOmegaSSTLM< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Re-read model coefficients if they have changed.
Definition at line 486 of file kOmegaSSTLM.C.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::~kOmegaSSTLM().
const volScalarField& ReThetat () const inline
Access function transition onset momentum-thickness Reynolds number.
Definition at line 248 of file kOmegaSSTLM.H.
References kOmegaSSTLM< BasicTurbulenceModel >::ReThetat_.
const volScalarField& gammaInt () const inline
Access function to intermittency.
Definition at line 254 of file kOmegaSSTLM.H.
References kOmegaSSTLM< BasicTurbulenceModel >::DReThetatEff(), kOmegaSSTLM< BasicTurbulenceModel >::gammaInt_, and nu.
tmp<volScalarField> DReThetatEff () const inline
Return the effective diffusivity for transition onset.
momentum-thickness Reynolds number
Definition at line 261 of file kOmegaSSTLM.H.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::gammaInt().
tmp<volScalarField> DgammaIntEff () const inline
Return the effective diffusivity for intermittency.
Definition at line 274 of file kOmegaSSTLM.H.
References kOmegaSSTLM< BasicTurbulenceModel >::correct(), and nu.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Definition at line 607 of file kOmegaSSTLM.C.
References kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correct().
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::DgammaIntEff().
Member Data Documentation
dimensionedScalar ca1_ protected
Definition at line 121 of file kOmegaSSTLM.H.
dimensionedScalar ca2_ protected
Definition at line 122 of file kOmegaSSTLM.H.
dimensionedScalar ce1_ protected
Definition at line 124 of file kOmegaSSTLM.H.
dimensionedScalar ce2_ protected
Definition at line 125 of file kOmegaSSTLM.H.
dimensionedScalar cThetat_ protected
Definition at line 127 of file kOmegaSSTLM.H.
dimensionedScalar sigmaThetat_ protected
Definition at line 128 of file kOmegaSSTLM.H.
scalar lambdaErr_ protected
Convergence criterion for the lambda/thetat loop.
Definition at line 131 of file kOmegaSSTLM.H.
label maxLambdaIter_ protected
Maximum number of iterations to converge the lambda/thetat loop.
Definition at line 134 of file kOmegaSSTLM.H.
const dimensionedScalar deltaU_ protected
Stabilization for division by the magnitude of the velocity.
Definition at line 137 of file kOmegaSSTLM.H.
volScalarField ReThetat_ protected
Transition onset momentum-thickness Reynolds number.
Definition at line 143 of file kOmegaSSTLM.H.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::ReThetat().
volScalarField gammaInt_ protected
Intermittency.
Definition at line 146 of file kOmegaSSTLM.H.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::gammaInt().
volScalarField::Internal gammaIntEff_ protected
Effective intermittency.
Definition at line 149 of file kOmegaSSTLM.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTLM/kOmegaSSTLM.H
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTLM/kOmegaSSTLM.C