OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
StaticHashTable< T, Key, Hash >::Iterator< TRef, TableRef > Class Template Reference
An STL iterator.
Public Member Functions
Iterator (TableRef, label hashIndex_, label elemIndex_)
Construct from hash table, hash index and element index.
Iterator (const iterator &)
Construct from the non-const iterator.
void operator= (const iterator &)
bool operator== (const iterator &) const
bool operator== (const const_iterator &) const
bool operator!= (const iterator &) const
bool operator!= (const const_iterator &) const
TRef operator* ()
TRef operator() ()
Iterator & operator++ ()
Iterator operator++ (int)
const Key & key () const
Friends
class StaticHashTable
template<class TRef2 , class TableRef2 >
class Iterator
Detailed Description
template<class T, class Key = word, class Hash = string::hash>
template<class TRef, class TableRef>
class Foam::StaticHashTable< T, Key, Hash >::Iterator< TRef, TableRef >
An STL iterator.
Definition at line 138 of file StaticHashTable.H.
Constructor & Destructor Documentation
Iterator (TableRef hashTbl, label hashIndex_, label elemIndex_) inline
Construct from hash table, hash index and element index.
Definition at line 147 of file StaticHashTableI.H.
Iterator (const iterator & iter) inline
Construct from the non-const iterator.
Definition at line 162 of file StaticHashTableI.H.
References TRef().
Member Function Documentation
void operator= (const iterator & iter) inline
Definition at line 176 of file StaticHashTableI.H.
References TRef().
bool operator== (const iterator & iter) const inline
Definition at line 189 of file StaticHashTableI.H.
References TRef().
bool operator== (const const_iterator & iter) const inline
Definition at line 201 of file StaticHashTableI.H.
References TRef().
bool operator!= (const iterator & iter) const inline
Definition at line 213 of file StaticHashTableI.H.
References Foam::operator==(), and TRef().
bool operator!= (const const_iterator & iter) const inline
Definition at line 225 of file StaticHashTableI.H.
References Foam::operator==().
TRef operator* () inline
Definition at line 236 of file StaticHashTableI.H.
TRef operator() () inline
Definition at line 245 of file StaticHashTableI.H.
References Foam::operator*(), and TRef().
Foam::StaticHashTable< T, Key, Hash >::template Iterator< TRef, TableRef > & operator++ () inline
Definition at line 263 of file StaticHashTableI.H.
References TRef().
Foam::StaticHashTable< T, Key, Hash >::template Iterator< TRef, TableRef > operator++ (int) inline
Definition at line 316 of file StaticHashTableI.H.
const Key & key () const inline
Definition at line 329 of file StaticHashTableI.H.
Friends And Related Function Documentation
friend class StaticHashTable friend
Definition at line 297 of file StaticHashTable.H.
friend class Iterator friend
Definition at line 300 of file StaticHashTable.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/StaticHashTable/StaticHashTable.H
src/OpenFOAM/containers/HashTables/StaticHashTable/StaticHashTableI.H