OpenFOAM: LaheyKEpsilon< BasicTurbulenceModel > Class Template Reference
LaheyKEpsilon< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Continuous-phase k-epsilon model including bubble-generated turbulence.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kEpsilon< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel >::alphaField alphaField
typedef RASModel< BasicTurbulenceModel >::rhoField rhoField
typedef RASModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel >::alphaField alphaField
typedef RASModel< BasicTurbulenceModel >::rhoField rhoField
typedef RASModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("LaheyKEpsilon")
Runtime type information.
LaheyKEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~LaheyKEpsilon ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from kEpsilon< BasicTurbulenceModel >
TypeName ("kEpsilon")
Runtime type information.
kEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kEpsilon ()
Destructor.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual void correctNut ()
tmp< volScalarField > bubbleG () const
tmp< volScalarField > phaseTransferCoeff () const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar alphaInversion_
dimensionedScalar Cp_
dimensionedScalar C3_
dimensionedScalar Cmub_
Protected Attributes inherited from kEpsilon< BasicTurbulenceModel >
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::LaheyKEpsilon< BasicTurbulenceModel >
Continuous-phase k-epsilon model including bubble-generated turbulence.
Reference:
    Lahey Jr, R. T. (2005).
    The simulation of multidimensional multiphase flows.
    Nuclear Engineering and Design, 235(10), 1043-1060.
The default model coefficients are
    LaheyKEpsilonCoeffs
    {
        Cmu             0.09;
        C1              1.44;
        C2              1.92;
        C3              -0.33;
        sigmak          1.0;
        sigmaEps        1.3;
        Cp              0.25;
        Cmub            0.6;
        alphaInversion  0.3;
    }
Source files
LaheyKEpsilon.H
LaheyKEpsilon.C
Definition at line 77 of file LaheyKEpsilon.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 126 of file LaheyKEpsilon.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 127 of file LaheyKEpsilon.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 128 of file LaheyKEpsilon.H.
Constructor & Destructor Documentation
LaheyKEpsilon (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 41 of file LaheyKEpsilon.C.
virtual ~LaheyKEpsilon () inline virtual
Destructor.
Definition at line 152 of file LaheyKEpsilon.H.
References LaheyKEpsilon< BasicTurbulenceModel >::correct(), and LaheyKEpsilon< BasicTurbulenceModel >::read().
Member Function Documentation
void correctNut () protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 167 of file LaheyKEpsilon.C.
References optionList::correct(), Foam::mag(), options::New(), and Foam::sqr().
tmp< volScalarField > bubbleG () const protected
Definition at line 185 of file LaheyKEpsilon.C.
References dragModel::CdRe(), twoPhaseSystem::drag(), fluid, Foam::mag(), twoPhaseSystem::otherPhase(), Foam::pow(), and Foam::pow3().
tmp< volScalarField > phaseTransferCoeff () const protected
Definition at line 214 of file LaheyKEpsilon.C.
References TimeState::deltaT(), turbulenceModel::epsilon(), turbulenceModel::k(), Foam::max(), Foam::min(), and IOobject::time().
tmp< fvScalarMatrix > kSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 232 of file LaheyKEpsilon.C.
References Foam::fvm::Sp().
tmp< fvScalarMatrix > epsilonSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 250 of file LaheyKEpsilon.C.
References Foam::fvm::Sp().
TypeName ("LaheyKEpsilon< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 116 of file LaheyKEpsilon.C.
References IOobject::db(), fluid, IOobject::groupName(), objectRegistry::lookupObject(), twoPhaseSystem::otherPhase(), and turbulenceModel::propertiesName.
Referenced by LaheyKEpsilon< BasicTurbulenceModel >::~LaheyKEpsilon().
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 268 of file LaheyKEpsilon.C.
References kEpsilon< BasicTurbulenceModel >::correct().
Referenced by LaheyKEpsilon< BasicTurbulenceModel >::~LaheyKEpsilon().
Member Data Documentation
dimensionedScalar alphaInversion_ protected
Definition at line 109 of file LaheyKEpsilon.H.
dimensionedScalar Cp_ protected
Definition at line 110 of file LaheyKEpsilon.H.
dimensionedScalar C3_ protected
Definition at line 111 of file LaheyKEpsilon.H.
dimensionedScalar Cmub_ protected
Definition at line 112 of file LaheyKEpsilon.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/RAS/LaheyKEpsilon/LaheyKEpsilon.H
src/TurbulenceModels/phaseCompressible/RAS/LaheyKEpsilon/LaheyKEpsilon.C