OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
linearAxialAngularSpring Class Reference
sixDoFRigidBodyMotionRestraints model. Linear axial angular spring.
Public Member Functions
TypeName ("linearAxialAngularSpring")
Runtime type information.
linearAxialAngularSpring (const word &name, const dictionary &sDoFRBMRDict)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const
Construct and return a clone.
virtual ~linearAxialAngularSpring ()
Destructor.
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const
Calculate the restraint position, force and moment.
virtual bool read (const dictionary &sDoFRBMRCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
TypeName ("sixDoFRigidBodyMotionRestraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
Construct from the sDoFRBMRDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionRestraint ()
Destructor.
const word & name () const
Return the name.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Select constructed from the sDoFRBMRDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionRestraint
word name_
Name of the restraint.
dictionary sDoFRBMRCoeffs_
Restraint model specific coefficient dictionary.
Detailed Description
sixDoFRigidBodyMotionRestraints model. Linear axial angular spring.
Source files
linearAxialAngularSpring.H
linearAxialAngularSpring.C
Definition at line 53 of file linearAxialAngularSpring.H.
Constructor & Destructor Documentation
linearAxialAngularSpring (const word & name, const dictionary & sDoFRBMRDict)
Construct from components.
Definition at line 53 of file linearAxialAngularSpring.C.
References Foam::read(), and linearAxialAngularSpring::~linearAxialAngularSpring().
Referenced by linearAxialAngularSpring::clone().
~linearAxialAngularSpring () virtual
Destructor.
Definition at line 71 of file linearAxialAngularSpring.C.
References linearAxialAngularSpring::restrain().
Referenced by linearAxialAngularSpring::clone(), and linearAxialAngularSpring::linearAxialAngularSpring().
Member Function Documentation
TypeName ("linearAxialAngularSpring")
Runtime type information.
virtual autoPtr<sixDoFRigidBodyMotionRestraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 88 of file linearAxialAngularSpring.H.
References linearAxialAngularSpring::linearAxialAngularSpring(), linearAxialAngularSpring::read(), linearAxialAngularSpring::restrain(), linearAxialAngularSpring::write(), and linearAxialAngularSpring::~linearAxialAngularSpring().
void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const virtual
Calculate the restraint position, force and moment.
Global reference frame vectors.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 79 of file linearAxialAngularSpring.C.
References Foam::acos(), sixDoFRigidBodyMotion::centreOfRotation(), Foam::endl(), Foam::Info, Foam::mag(), Foam::min(), sixDoFRigidBodyMotion::omega(), sixDoFRigidBodyMotion::orientation(), linearAxialAngularSpring::read(), sixDoFRigidBodyMotion::report(), Foam::rotationTensor(), Foam::sign(), and VectorSpace< Vector< scalar >, scalar, 3 >::zero.
Referenced by linearAxialAngularSpring::clone(), and linearAxialAngularSpring::~linearAxialAngularSpring().
bool read (const dictionary & sDoFRBMRCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionRestraint.
Definition at line 145 of file linearAxialAngularSpring.C.
References Foam::abort(), Foam::e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::I, Foam::mag(), Foam::nl, sixDoFRigidBodyMotionRestraint::read(), Foam::sqrt(), and linearAxialAngularSpring::write().
Referenced by linearAxialAngularSpring::clone(), and linearAxialAngularSpring::restrain().
void write (Ostream & os) const virtual
Write.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 185 of file linearAxialAngularSpring.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by linearAxialAngularSpring::clone(), and linearAxialAngularSpring::read().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearAxialAngularSpring/linearAxialAngularSpring.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearAxialAngularSpring/linearAxialAngularSpring.C