OpenFOAM: LeastSquaresGrad< Type, Stencil > Class Template Reference
LeastSquaresGrad< Type, Stencil > Class Template Reference
Gradient calculated using weighted least-squares on an arbitrary stencil. The stencil type is provided via a template argument and any cell-based stencil is supported:
Public Member Functions
TypeName ("LeastSquares")
Runtime type information.
LeastSquaresGrad (const fvMesh &mesh, Istream &schemeData)
Construct from Istream.
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
Return the gradient of the given field to the gradScheme::grad.
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type, class Stencil>
class Foam::fv::LeastSquaresGrad< Type, Stencil >
Gradient calculated using weighted least-squares on an arbitrary stencil. The stencil type is provided via a template argument and any cell-based stencil is supported:
Stencil Connections Scheme name
centredCFCCellToCellStencil cell-face-cell Not Instantiated
centredCPCCellToCellStencil cell-point-cell pointCellsLeastSquares
centredCECCellToCellStencil cell-edge-cell edgeCellsLeastSquares
The first of these is not instantiated by default as the standard leastSquaresGrad is equivalent and more efficient.
Usage
Example of the gradient specification:
gradSchemes
{
    default         pointCellsLeastSquares;
}
See also
Foam::fv::LeastSquaresVectors Foam::fv::leastSquaresGrad
Source files
LeastSquaresGrad.H
LeastSquaresGrad.C
LeastSquaresVectors.H
LeastSquaresVectors.C
Definition at line 97 of file LeastSquaresGrad.H.
Constructor & Destructor Documentation
LeastSquaresGrad (const fvMesh & mesh, Istream & schemeData) inline
Construct from Istream.
Definition at line 125 of file LeastSquaresGrad.H.
References LeastSquaresGrad< Type, Stencil >::calcGrad(), and Foam::name().
Member Function Documentation
TypeName ("LeastSquares")
Runtime type information.
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const virtual
Return the gradient of the given field to the gradScheme::grad.
for optional caching
Implements gradScheme< Type >.
Referenced by LeastSquaresGrad< Type, Stencil >::LeastSquaresGrad().
The documentation for this class was generated from the following file:
src/finiteVolume/finiteVolume/gradSchemes/LeastSquaresGrad/LeastSquaresGrad.H