OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LISAAtomization< CloudType > Class Template Reference
Primary Breakup Model for pressure swirl atomizers.
Public Types
enum SMDMethods { method1, method2 }
Enumeration for SMD calculations.
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Public Member Functions
TypeName ("LISA")
Runtime type information.
LISAAtomization (const dictionary &, CloudType &)
Construct from dictionary.
LISAAtomization (const LISAAtomization< CloudType > &am)
Construct copy.
virtual autoPtr< AtomizationModel< CloudType > > clone () const
Construct and return a clone.
virtual ~LISAAtomization ()
Destructor.
virtual scalar initLiquidCore () const
Initial value of liquidCore.
virtual bool calcChi () const
Flag to indicate if chi needs to be calculated.
virtual void update (const scalar dt, scalar &d, scalar &liquidCore, scalar &tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector &pos, const vector &injectionPos, const scalar pAmbient, const scalar chi, cachedRandom &rndGen) const
Public Member Functions inherited from AtomizationModel< CloudType >
TypeName ("atomizationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AtomizationModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
AtomizationModel (CloudType &owner)
Construct null from owner.
AtomizationModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
AtomizationModel (const AtomizationModel< CloudType > &am)
Construct copy.
virtual ~AtomizationModel ()
Destructor.
scalar Taverage (const scalar &Tliq, const scalar &Tc) const
Average temperature calculation.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Static Public Member Functions inherited from AtomizationModel< CloudType >
static autoPtr< AtomizationModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::LISAAtomization< CloudType >
Primary Breakup Model for pressure swirl atomizers.
Accurate description in
P.K. Senecal, D.P. Schmidt, I. Nouar, C.J. Rutland, R.D. Reitz, M. Corradini
"Modeling high-speed viscous liquid sheet atomization"
International Journal of Multiphase Flow 25 (1999) pags. 1073-1097
and
D.P. Schmidt, I. Nouar, P.K. Senecal, C.J. Rutland, J.K. Martin, R.D. Reitz
"Pressure-Swirl Atomization in the Near Field"
SAE Techical Paper Series 1999-01-0496
Definition at line 60 of file LISAAtomization.H.
Member Enumeration Documentation
enum SMDMethods
Enumeration for SMD calculations.
Enumerator
method1
method2
Definition at line 68 of file LISAAtomization.H.
Constructor & Destructor Documentation
LISAAtomization (const dictionary & dict, CloudType & owner)
Construct from dictionary.
Definition at line 32 of file LISAAtomization.C.
References Foam::endl(), Foam::Info, and Foam::mag().
LISAAtomization (const LISAAtomization< CloudType > & am)
Construct copy.
Definition at line 67 of file LISAAtomization.C.
~LISAAtomization () virtual
Destructor.
Definition at line 84 of file LISAAtomization.C.
Referenced by LISAAtomization< CloudType >::clone().
Member Function Documentation
TypeName ("LISA")
Runtime type information.
virtual autoPtr<AtomizationModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements AtomizationModel< CloudType >.
Definition at line 104 of file LISAAtomization.H.
References LISAAtomization< CloudType >::calcChi(), LISAAtomization< CloudType >::initLiquidCore(), Foam::constant::physicoChemical::mu, Foam::pos(), rho, rndGen(), Foam::constant::physicoChemical::sigma, LISAAtomization< CloudType >::update(), Urel, and LISAAtomization< CloudType >::~LISAAtomization().
Foam::scalar initLiquidCore () const virtual
Initial value of liquidCore.
Implements AtomizationModel< CloudType >.
Definition at line 91 of file LISAAtomization.C.
Referenced by LISAAtomization< CloudType >::clone().
bool calcChi () const virtual
Flag to indicate if chi needs to be calculated.
Implements AtomizationModel< CloudType >.
Definition at line 98 of file LISAAtomization.C.
References LISAAtomization< CloudType >::update().
Referenced by LISAAtomization< CloudType >::clone().
void update (const scalar dt, scalar & d, scalar & liquidCore, scalar & tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector & pos, const vector & injectionPos, const scalar pAmbient, const scalar chi, cachedRandom & rndGen) const virtual
Implements AtomizationModel< CloudType >.
Definition at line 106 of file LISAAtomization.C.
References Foam::cbrt(), delta, Foam::diff(), Foam::constant::electromagnetic::e, Foam::constant::universal::h, k, Foam::mag(), Foam::min(), nu, Foam::constant::mathematical::pi(), Foam::pow(), Foam::pow3(), Foam::pow4(), rho, Foam::constant::physicoChemical::sigma, Foam::sqr(), Foam::sqrt(), Urel, and x.
Referenced by LISAAtomization< CloudType >::calcChi(), and LISAAtomization< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/spray/submodels/AtomizationModel/LISAAtomization/LISAAtomization.H
src/lagrangian/spray/submodels/AtomizationModel/LISAAtomization/LISAAtomization.C