OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
linearAxialAngularSpring Class Reference
Linear axial angular spring restraint.
Public Member Functions
TypeName ("linearAxialAngularSpring")
Runtime type information.
linearAxialAngularSpring (const word &name, const dictionary &dict, const rigidBodyModel &model)
Construct from components.
virtual autoPtr< restraint > clone () const
Construct and return a clone.
virtual ~linearAxialAngularSpring ()
Destructor.
virtual spatialVector restrain () const
Return the external force applied to the body by this restraint.
virtual bool read (const dictionary &dict)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from restraint
TypeName ("restraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, restraint, dictionary,(const word &name, const dictionary &dict, const rigidBodyModel &model),(name, dict, model))
restraint (const word &name, const dictionary &dict, const rigidBodyModel &model)
Construct from the dict dictionary and Time.
virtual ~restraint ()
Destructor.
const word & name () const
Return the name.
label bodyID () const
const dictionary & coeffDict () const
Return access to coeffs.
Additional Inherited Members
Static Public Member Functions inherited from restraint
static autoPtr< restraint > New (const word &name, const dictionary &dict, const rigidBodyModel &model)
Select constructed from the dict dictionary and Time.
Protected Member Functions inherited from restraint
point bodyPoint (const point &p) const
Transform the given point on the restrained body to the global frame.
spatialVector bodyPointVelocity (const point &p) const
Transform the velocity of the given point on the restrained body.
Protected Attributes inherited from restraint
word name_
Name of the restraint.
label bodyID_
ID of the body the restraint is applied to.
dictionary coeffs_
Restraint model specific coefficient dictionary.
const rigidBodyModel & model_
Reference to the model.
Detailed Description
Linear axial angular spring restraint.
Source files
linearAxialAngularSpring.H
linearAxialAngularSpring.C
Definition at line 52 of file linearAxialAngularSpring.H.
Constructor & Destructor Documentation
linearAxialAngularSpring (const word & name, const dictionary & dict, const rigidBodyModel & model)
Construct from components.
Definition at line 55 of file linearAxialAngularSpring.C.
References Foam::read(), and linearAxialAngularSpring::~linearAxialAngularSpring().
Referenced by linearAxialAngularSpring::clone().
~linearAxialAngularSpring () virtual
Destructor.
Definition at line 70 of file linearAxialAngularSpring.C.
Referenced by linearAxialAngularSpring::clone(), and linearAxialAngularSpring::linearAxialAngularSpring().
Member Function Documentation
TypeName ("linearAxialAngularSpring")
Runtime type information.
virtual autoPtr<restraint> clone () const inline virtual
Construct and return a clone.
Implements restraint.
Definition at line 88 of file linearAxialAngularSpring.H.
References linearAxialAngularSpring::linearAxialAngularSpring(), linearAxialAngularSpring::read(), linearAxialAngularSpring::restrain(), linearAxialAngularSpring::write(), and linearAxialAngularSpring::~linearAxialAngularSpring().
Foam::spatialVector restrain () const virtual
Return the external force applied to the body by this restraint.
Implements restraint.
Definition at line 77 of file linearAxialAngularSpring.C.
References Foam::acos(), Foam::endl(), Foam::Info, Foam::mag(), Foam::min(), linearAxialAngularSpring::read(), Foam::rotationTensor(), Foam::sign(), and Foam::Zero.
Referenced by linearAxialAngularSpring::clone().
bool read (const dictionary & dict) virtual
Update properties from given dictionary.
Reimplemented from restraint.
Definition at line 139 of file linearAxialAngularSpring.C.
References Foam::abort(), Foam::e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::I, Foam::mag(), Foam::nl, restraint::read(), Foam::sqrt(), and linearAxialAngularSpring::write().
Referenced by linearAxialAngularSpring::clone(), and linearAxialAngularSpring::restrain().
void write (Ostream & os) const virtual
Write.
Implements restraint.
Definition at line 179 of file linearAxialAngularSpring.C.
References token::END_STATEMENT, Foam::nl, restraint::write(), and Ostream::writeKeyword().
Referenced by linearAxialAngularSpring::clone(), and linearAxialAngularSpring::read().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/restraints/linearAxialAngularSpring/linearAxialAngularSpring.H
src/rigidBodyDynamics/restraints/linearAxialAngularSpring/linearAxialAngularSpring.C