OpenFOAM-dev: LESeddyViscosity< BasicTurbulenceModel > Class Template Reference 2
LESeddyViscosity< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
Eddy viscosity LES SGS model base class.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel >::alphaField alphaField
typedef LESModel< BasicTurbulenceModel >::rhoField rhoField
typedef LESModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel >::alphaField alphaField
typedef LESModel< BasicTurbulenceModel >::rhoField rhoField
typedef LESModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~LESeddyViscosity ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual tmp< volScalarField > epsilon () const
Return sub-grid disipation rate.
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > k () const =0
Return the turbulence kinetic energy.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Attributes
dimensionedScalar Ce_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Protected Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
virtual void correctNut ()=0
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::LESeddyViscosity< BasicTurbulenceModel >
Eddy viscosity LES SGS model base class.
Source files
LESeddyViscosity.H
LESeddyViscosity.C
Definition at line 55 of file LESeddyViscosity.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 75 of file LESeddyViscosity.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 76 of file LESeddyViscosity.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 77 of file LESeddyViscosity.H.
Constructor & Destructor Documentation
LESeddyViscosity (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName)
Construct from components.
Definition at line 39 of file LESeddyViscosity.C.
virtual ~LESeddyViscosity () inline virtual
Destructor.
Definition at line 97 of file LESeddyViscosity.H.
References LESeddyViscosity< BasicTurbulenceModel >::epsilon(), and LESeddyViscosity< BasicTurbulenceModel >::read().
Member Function Documentation
bool read () virtual
Read model coefficients if they have changed.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Reimplemented in SpalartAllmarasDES< BasicTurbulenceModel >, dynamicKEqn< BasicTurbulenceModel >, NicenoKEqn< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, SpalartAllmarasIDDES< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, continuousGasKEqn< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, and dynamicLagrangian< BasicTurbulenceModel >.
Definition at line 77 of file LESeddyViscosity.C.
References Foam::read().
Referenced by LESeddyViscosity< BasicTurbulenceModel >::~LESeddyViscosity().
tmp< volScalarField > epsilon () const virtual
Return sub-grid disipation rate.
Reimplemented in dynamicKEqn< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, and kEqn< BasicTurbulenceModel >.
Definition at line 93 of file LESeddyViscosity.C.
References delta, IOobject::groupName(), k, IOobject::NO_READ, IOobject::NO_WRITE, and Foam::sqrt().
Referenced by LESeddyViscosity< BasicTurbulenceModel >::~LESeddyViscosity().
Member Data Documentation
dimensionedScalar Ce_ protected
Definition at line 70 of file LESeddyViscosity.H.
Referenced by dynamicLagrangian< BasicTurbulenceModel >::k().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESeddyViscosity/LESeddyViscosity.H
src/TurbulenceModels/turbulenceModels/LES/LESeddyViscosity/LESeddyViscosity.C