OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LocalInteraction< CloudType > Class Template Reference
Patch interaction specified on a patch-by-patch basis.
Public Member Functions
TypeName ("localInteraction")
Runtime type information.
LocalInteraction (const dictionary &dict, CloudType &owner)
Construct from dictionary.
LocalInteraction (const LocalInteraction< CloudType > &pim)
Construct copy from owner cloud and patch interaction model.
virtual autoPtr< PatchInteractionModel< CloudType > > clone () const
Construct and return a clone using supplied owner cloud.
virtual ~LocalInteraction ()
Destructor.
volScalarField & massEscape ()
Return access to the massEscape field.
volScalarField & massStick ()
Return access to the massStick field.
virtual bool correct (typename CloudType::parcelType &p, const polyPatch &pp, bool &keepParticle, const scalar trackFraction, const tetIndices &tetIs)
Apply velocity correction.
virtual void info (Ostream &os)
Write patch interaction info to stream.
Public Member Functions inherited from PatchInteractionModel< CloudType >
TypeName ("patchInteractionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, PatchInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
PatchInteractionModel (CloudType &owner)
Construct null from owner.
PatchInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
PatchInteractionModel (const PatchInteractionModel< CloudType > &pim)
Construct copy.
virtual ~PatchInteractionModel ()
Destructor.
const word & UName () const
Return name of velocity field.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from PatchInteractionModel< CloudType >
enum interactionType { itRebound, itStick, itEscape, itOther }
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from PatchInteractionModel< CloudType >
static autoPtr< PatchInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
static word interactionTypeToWord (const interactionType &itEnum)
Convert interaction result to word.
static interactionType wordToInteractionType (const word &itWord)
Convert word to interaction result.
Static Public Attributes inherited from PatchInteractionModel< CloudType >
static wordList interactionTypeNames_
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::LocalInteraction< CloudType >
Patch interaction specified on a patch-by-patch basis.
Definition at line 47 of file LocalInteraction.H.
Constructor & Destructor Documentation
LocalInteraction (const dictionary & dict, CloudType & owner)
Construct from dictionary.
Definition at line 32 of file LocalInteraction.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::name(), and Foam::nl.
LocalInteraction (const LocalInteraction< CloudType > & pim)
Construct copy from owner cloud and patch interaction model.
Definition at line 86 of file LocalInteraction.C.
~LocalInteraction () virtual
Destructor.
Definition at line 105 of file LocalInteraction.C.
Referenced by LocalInteraction< CloudType >::clone().
Member Function Documentation
TypeName ("localInteraction")
Runtime type information.
virtual autoPtr<PatchInteractionModel<CloudType> > clone () const inline virtual
Construct and return a clone using supplied owner cloud.
Implements PatchInteractionModel< CloudType >.
Definition at line 97 of file LocalInteraction.H.
References LocalInteraction< CloudType >::correct(), LocalInteraction< CloudType >::info(), LocalInteraction< CloudType >::massEscape(), LocalInteraction< CloudType >::massStick(), p, and LocalInteraction< CloudType >::~LocalInteraction().
Foam::volScalarField & massEscape ()
Return access to the massEscape field.
Definition at line 112 of file LocalInteraction.C.
References Foam::dimMass, mesh, Foam::name(), fvMesh::time(), and Time::timeName().
Referenced by LocalInteraction< CloudType >::clone().
Foam::volScalarField & massStick ()
Return access to the massStick field.
Definition at line 141 of file LocalInteraction.C.
References LocalInteraction< CloudType >::correct(), Foam::dimMass, mesh, Foam::name(), fvMesh::time(), and Time::timeName().
Referenced by LocalInteraction< CloudType >::clone().
bool correct (typename CloudType::parcelType & p, const polyPatch & pp, bool & keepParticle, const scalar trackFraction, const tetIndices & tetIs) virtual
Apply velocity correction.
Returns true if particle remains in same cell
Implements PatchInteractionModel< CloudType >.
Definition at line 171 of file LocalInteraction.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, patchIdentifier::index(), nw, U, and polyPatch::whichFace().
Referenced by LocalInteraction< CloudType >::clone(), and LocalInteraction< CloudType >::massStick().
void info (Ostream & os) virtual
Write patch interaction info to stream.
Reimplemented from PatchInteractionModel< CloudType >.
Definition at line 276 of file LocalInteraction.C.
References forAll, and Foam::nl.
Referenced by LocalInteraction< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/LocalInteraction/LocalInteraction.H
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/LocalInteraction/LocalInteraction.C