OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
linear Class Reference
linear compressibility model.
Public Member Functions
TypeName ("linear")
Runtime type information.
linear (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Construct from components.
~linear ()
Destructor.
void correct ()
Correct the linear compressibility.
bool read (const dictionary &compressibilityProperties)
Read transportProperties dictionary.
Public Member Functions inherited from barotropicCompressibilityModel
TypeName ("barotropicCompressibilityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, barotropicCompressibilityModel, dictionary,(const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName),(compressibilityProperties, gamma, psiName))
barotropicCompressibilityModel (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Construct from components.
virtual ~barotropicCompressibilityModel ()
Destructor.
const dictionary & compressibilityProperties () const
Return the phase transport properties dictionary.
const volScalarField & psi () const
Return the compressibility.
Additional Inherited Members
Static Public Member Functions inherited from barotropicCompressibilityModel
static autoPtr< barotropicCompressibilityModel > New (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Return a reference to the selected compressibility model.
Protected Member Functions inherited from barotropicCompressibilityModel
barotropicCompressibilityModel (const barotropicCompressibilityModel &)
Disallow copy construct.
void operator= (const barotropicCompressibilityModel &)
Disallow default bitwise assignment.
Protected Attributes inherited from barotropicCompressibilityModel
dictionary compressibilityProperties_
volScalarField psi_
const volScalarField & gamma_
Detailed Description
linear compressibility model.
Source files
linear.H
linear.C
Definition at line 51 of file linear.H.
Constructor & Destructor Documentation
linear (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi")
Construct from components.
Definition at line 48 of file linear.C.
References correct.
~linear () inline
Destructor.
Definition at line 79 of file linear.H.
References linear::correct(), and linear::read().
Member Function Documentation
TypeName ("linear")
Runtime type information.
void correct () virtual
Correct the linear compressibility.
Implements barotropicCompressibilityModel.
Definition at line 75 of file linear.C.
References linear::read().
Referenced by linear::~linear().
bool read (const dictionary & compressibilityProperties) virtual
Read transportProperties dictionary.
Implements barotropicCompressibilityModel.
Definition at line 82 of file linear.C.
References barotropicCompressibilityModel::read().
Referenced by linear::correct(), and linear::~linear().
The documentation for this class was generated from the following files:
src/thermophysicalModels/barotropicCompressibilityModel/linear/linear.H
src/thermophysicalModels/barotropicCompressibilityModel/linear/linear.C