OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mag Class Reference
FunctionObjects » Field function objects
This function object calculates the magnitude of a field. The operation can be applied to any volume or surface fieldsm and the output is a volume or surface scalar field.
Public Member Functions
TypeName ("mag")
Runtime type information.
mag (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~mag ()
Destructor.
virtual const word & name () const
Return name of the set of mag.
virtual void read (const dictionary &)
Read the mag data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the mag and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
This function object calculates the magnitude of a field. The operation can be applied to any volume or surface fieldsm and the output is a volume or surface scalar field.
Source files
mag.H
mag.C
Definition at line 67 of file mag.H.
Constructor & Destructor Documentation
mag (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 45 of file mag.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::read().
~mag () virtual
Destructor.
Definition at line 69 of file mag.C.
Member Function Documentation
TypeName ("mag")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the set of mag.
Definition at line 132 of file mag.H.
References mag::end(), mag::execute(), mag::read(), mag::timeSet(), and mag::write().
void read (const dictionary & dict) virtual
Read the mag data.
Definition at line 75 of file mag.C.
References dictionary::lookup().
Referenced by mag::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 87 of file mag.C.
References Foam::endl(), and WarningInFunction.
Referenced by mag::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 105 of file mag.C.
Referenced by mag::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 111 of file mag.C.
Referenced by mag::name().
void write () virtual
Calculate the mag and write.
Definition at line 115 of file mag.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by mag::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 153 of file mag.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 157 of file mag.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/mag/mag.H
src/postProcessing/functionObjects/field/mag/mag.C
src/postProcessing/functionObjects/field/mag/magTemplates.C