OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
MaxwellianThermal< CloudType > Class Template Reference
Wall interaction setting microscopic velocity to a random one drawn from a Maxwellian distribution corresponding to a specified temperature.
Public Member Functions
TypeName ("MaxwellianThermal")
Runtime type information.
MaxwellianThermal (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
virtual ~MaxwellianThermal ()
Destructor.
virtual void correct (typename CloudType::parcelType &p, const wallPolyPatch &wpp)
Apply wall correction.
Public Member Functions inherited from WallInteractionModel< CloudType >
TypeName ("WallInteractionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, WallInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
WallInteractionModel (CloudType &owner)
Construct null from owner.
WallInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~WallInteractionModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
CloudType & owner ()
Return non-const access to the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from WallInteractionModel< CloudType >
static autoPtr< WallInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::MaxwellianThermal< CloudType >
Wall interaction setting microscopic velocity to a random one drawn from a Maxwellian distribution corresponding to a specified temperature.
Definition at line 47 of file MaxwellianThermal.H.
Constructor & Destructor Documentation
MaxwellianThermal (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 35 of file MaxwellianThermal.C.
~MaxwellianThermal () virtual
Destructor.
Definition at line 47 of file MaxwellianThermal.C.
References MaxwellianThermal< CloudType >::correct().
Member Function Documentation
TypeName ("MaxwellianThermal< CloudType >")
Runtime type information.
void correct (typename CloudType::parcelType & p, const wallPolyPatch & wpp) virtual
Apply wall correction.
Implements WallInteractionModel< CloudType >.
Definition at line 55 of file MaxwellianThermal.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DSMCCloud< ParcelType >::boundaryT(), DSMCCloud< ParcelType >::boundaryU(), DSMCCloud< ParcelType >::constProps(), DSMCCloud< ParcelType >::equipartitionInternalEnergy(), patchIdentifier::index(), Foam::constant::physicoChemical::k, Foam::log(), Foam::mag(), Foam::max(), nw, rndGen(), DSMCCloud< ParcelType >::rndGen(), Foam::sqrt(), Foam::T(), U, polyPatch::whichFace(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by MaxwellianThermal< CloudType >::~MaxwellianThermal().
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/submodels/WallInteractionModel/MaxwellianThermal/MaxwellianThermal.H
src/lagrangian/DSMC/submodels/WallInteractionModel/MaxwellianThermal/MaxwellianThermal.C