OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
meshRefinement Class Reference
Helper class which maintains intersections of (changing) mesh with (static) surfaces.
Public Types
enum IOdebugType {
IOMESH, IOOBJINTERSECTIONS, IOFEATURESEEDS, IOATTRACTION,
IOLAYERINFO
}
Enumeration for what to debug.
enum debugType {
MESH = 1<<IOMESH, OBJINTERSECTIONS = 1<<IOOBJINTERSECTIONS, FEATURESEEDS = 1<<IOFEATURESEEDS, ATTRACTION = 1<< IOATTRACTION,
LAYERINFO = 1<<IOLAYERINFO
}
enum IOoutputType { IOOUTPUTLAYERINFO }
Enumeration for what to output.
enum outputType { OUTPUTLAYERINFO = 1<<IOOUTPUTLAYERINFO }
enum IOwriteType { IOWRITEMESH, IOWRITELEVELS, IOWRITELAYERSETS, IOWRITELAYERFIELDS }
Enumeration for what to write.
enum writeType { WRITEMESH = 1<<IOWRITEMESH, WRITELEVELS = 1<<IOWRITELEVELS, WRITELAYERSETS = 1<<IOWRITELAYERSETS, WRITELAYERFIELDS = 1<<IOWRITELAYERFIELDS }
enum mapType { MASTERONLY = 1, KEEPALL = 2, REMOVE = 4 }
Enumeration for how the userdata is to be mapped upon refinement.
Public Member Functions
ClassName ("meshRefinement")
Runtime type information.
meshRefinement (fvMesh &mesh, const scalar mergeDistance, const bool overwrite, const refinementSurfaces &, const refinementFeatures &, const shellSurfaces &)
Construct from components.
const fvMesh & mesh () const
Reference to mesh.
fvMesh & mesh ()
scalar mergeDistance () const
bool overwrite () const
Overwrite the mesh?
const word & oldInstance () const
(points)instance of mesh upon construction
const refinementSurfaces & surfaces () const
Reference to surface search engines.
const refinementFeatures & features () const
Reference to feature edge mesh.
const shellSurfaces & shells () const
Reference to refinement shells (regions)
const hexRef8 & meshCutter () const
Reference to meshcutting engine.
const labelList & surfaceIndex () const
Per start-end edge the index of the surface hit.
labelList & surfaceIndex ()
const List< Tuple2< mapType,
labelList > > & userFaceData () const
Additional face data that is maintained across.
List< Tuple2< mapType,
labelList > > & userFaceData ()
label countHits () const
Count number of intersections (local)
autoPtr< mapDistributePolyMesh > balance (const bool keepZoneFaces, const bool keepBaffles, const scalarField &cellWeights, decompositionMethod &decomposer, fvMeshDistribute &distributor)
Redecompose according to cell count.
labelList intersectedFaces () const
Get faces with intersection.
labelList intersectedPoints () const
Get points on surfaces with intersection and boundary faces.
bool isGap (const scalar, const vector &, const vector &, const vector &, const vector &) const
Is local topology a small gap?
bool isNormalGap (const scalar, const vector &, const vector &, const vector &, const vector &) const
Is local topology a small gap normal to the test vector.
labelList refineCandidates (const pointField &keepPoints, const scalar curvature, const scalar planarAngle, const bool featureRefinement, const bool featureDistanceRefinement, const bool internalRefinement, const bool surfaceRefinement, const bool curvatureRefinement, const bool gapRefinement, const label maxGlobalCells, const label maxLocalCells) const
Calculate list of cells to refine.
autoPtr< mapPolyMesh > refine (const labelList &cellsToRefine)
Refine some cells.
autoPtr< mapDistributePolyMesh > refineAndBalance (const string &msg, decompositionMethod &decomposer, fvMeshDistribute &distributor, const labelList &cellsToRefine, const scalar maxLoadUnbalance)
Refine some cells and rebalance.
autoPtr< mapDistributePolyMesh > balanceAndRefine (const string &msg, decompositionMethod &decomposer, fvMeshDistribute &distributor, const labelList &cellsToRefine, const scalar maxLoadUnbalance)
Balance before refining some cells.
void baffleAndSplitMesh (const bool handleSnapProblems, const snapParameters &snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField &perpendicularAngle, const bool mergeFreeStanding, const scalar freeStandingAngle, const dictionary &motionDict, Time &runTime, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const point &keepPoint)
Split off unreachable areas of mesh.
autoPtr< mapPolyMesh > splitMesh (const label nBufferLayers, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const point &keepPoint)
Split off (with optional buffer layers) unreachable areas.
autoPtr< mapPolyMesh > dupNonManifoldPoints (const localPointRegion &)
Find boundary points that connect to more than one cell.
autoPtr< mapPolyMesh > dupNonManifoldPoints ()
Find boundary points that connect to more than one cell.
autoPtr< mapPolyMesh > createBaffles (const labelList &ownPatch, const labelList &neiPatch)
Create baffle for every internal face where ownPatch != -1.
void checkZoneFaces () const
Debug helper: check faceZones are not on processor patches.
autoPtr< mapPolyMesh > createZoneBaffles (const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, List< labelPair > &)
Create baffles for faces straddling zoned surfaces. Return.
autoPtr< mapPolyMesh > mergeBaffles (const List< labelPair > &)
Merge baffles. Gets pairs of faces.
autoPtr< mapPolyMesh > zonify (const point &keepPoint, const bool allowFreeStandingZoneFaces)
Put faces/cells into zones according to surface specification.
label addMeshedPatch (const word &name, const dictionary &)
Add patch originating from meshing. Update meshedPatches_.
labelList meshedPatches () const
Get patchIDs for patches added in addMeshedPatch.
void selectSeparatedCoupledFaces (boolList &) const
Select coupled faces that are not collocated.
autoPtr< mapPolyMesh > splitMeshRegions (const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const point &keepPoint)
Split mesh. Keep part containing point.
autoPtr< mapPolyMesh > splitFaces (const labelList &splitFaces, const labelPairList &splits)
Split faces into two.
void distribute (const mapDistributePolyMesh &)
Update local numbering for mesh redistribution.
void updateMesh (const mapPolyMesh &, const labelList &changedFaces)
Update for external change to mesh. changedFaces are in new mesh.
void storeData (const labelList &pointsToStore, const labelList &facesToStore, const labelList &cellsToStore)
Signal points/face/cells for which to store data.
void updateMesh (const mapPolyMesh &, const labelList &changedFaces, const Map< label > &pointsToRestore, const Map< label > &facesToRestore, const Map< label > &cellsToRestore)
Update local numbering + undo.
label mergePatchFacesUndo (const scalar minCos, const scalar concaveCos, const labelList &patchIDs, const dictionary &motionDict, const labelList &preserveFaces)
Merge coplanar faces. preserveFaces is != -1 for faces.
autoPtr< mapPolyMesh > doRemovePoints (removePoints &pointRemover, const boolList &pointCanBeDeleted)
autoPtr< mapPolyMesh > doRestorePoints (removePoints &pointRemover, const labelList &facesToRestore)
labelList collectFaces (const labelList &candidateFaces, const labelHashSet &set) const
labelList growFaceCellFace (const labelHashSet &set) const
label mergeEdgesUndo (const scalar minCos, const dictionary &motionDict)
Merge edges, maintain mesh quality. Return global number.
void checkData ()
Debugging: check that all faces still obey start()>end()
template<class T >
void testSyncBoundaryFaceList (const scalar mergeDistance, const string &, const UList< T > &, const UList< T > &) const
Compare two lists over all boundary faces.
void printMeshInfo (const bool, const string &) const
Print some mesh stats.
word timeName () const
Replacement for Time::timeName() : return oldInstance (if.
void setInstance (const fileName &)
Set instance of all local IOobjects.
bool write () const
Write mesh and all data.
void dumpRefinementLevel () const
Write refinement level as volScalarFields for postprocessing.
void dumpIntersections (const fileName &prefix) const
Debug: Write intersection information to OBJ format.
void write (const debugType debugFlags, const writeType writeFlags, const fileName &) const
Do any one of above IO functions.
Static Public Member Functions
static autoPtr
< indirectPrimitivePatch > makePatch (const polyMesh &, const labelList &)
Create patch from set of patches.
static tmp< pointVectorField > makeDisplacementField (const pointMesh &pMesh, const labelList &adaptPatchIDs)
Helper function to make a pointVectorField with correct.
static void checkCoupledFaceZones (const polyMesh &)
Helper function: check that face zones are synced.
static void calculateEdgeWeights (const polyMesh &mesh, const PackedBoolList &isMasterEdge, const labelList &meshPoints, const edgeList &edges, scalarField &edgeWeights, scalarField &invSumWeight)
Helper: calculate edge weights (1/length)
template<class Type >
static void weightedSum (const polyMesh &mesh, const PackedBoolList &isMasterEdge, const labelList &meshPoints, const edgeList &edges, const scalarField &edgeWeights, const Field< Type > &data, Field< Type > &sum)
Helper: weighted sum (over all subset of mesh points) by.
static label appendPatch (fvMesh &, const label insertPatchI, const word &, const dictionary &)
Helper:append patch to end of mesh.
static label addPatch (fvMesh &, const word &name, const dictionary &)
Helper:add patch to mesh. Update all registered fields.
static label findRegion (const polyMesh &, const labelList &cellRegion, const vector &perturbVec, const point &p)
Find region point is in. Uses optional perturbation to re-test.
template<class T >
static void updateList (const labelList &newToOld, const T &nullValue, List< T > &elems)
Helper: reorder list according to map.
static void testSyncPointList (const string &msg, const polyMesh &mesh, const List< scalar > &fld)
static void testSyncPointList (const string &msg, const polyMesh &mesh, const List< point > &fld)
template<class T >
static void collectAndPrint (const UList< point > &points, const UList< T > &data)
Print list according to (collected and) sorted coordinate.
static PackedBoolList getMasterPoints (const polyMesh &mesh, const labelList &meshPoints)
Determine master point for subset of points. If coupled.
static PackedBoolList getMasterEdges (const polyMesh &mesh, const labelList &meshEdges)
Determine master edge for subset of edges. If coupled.
template<class T >
static T gAverage (const PackedBoolList &isMasterElem, const UList< T > &values)
Helper: calculate average.
static writeType writeLevel ()
Get/set write level.
static void writeLevel (const writeType)
static outputType outputLevel ()
Get/set output level.
static void outputLevel (const outputType)
template<class Enum >
static int readFlags (const Enum &namedEnum, const wordList &)
Helper: convert wordList into bit pattern using provided.
Static Public Attributes
static const NamedEnum
< IOdebugType, 5 > IOdebugTypeNames
static const NamedEnum
< IOoutputType, 1 > IOoutputTypeNames
static const NamedEnum
< IOwriteType, 4 > IOwriteTypeNames
Detailed Description
Helper class which maintains intersections of (changing) mesh with (static) surfaces.
Maintains
per face any intersections of the cc-cc segment with any of the surfaces
Source files
meshRefinement.H
meshRefinement.C
meshRefinementBaffles.C
meshRefinementMerge.C
meshRefinementProblemCells.C
meshRefinementRefine.C
Definition at line 80 of file meshRefinement.H.
Member Enumeration Documentation
enum IOdebugType
Enumeration for what to debug.
Enumerator
IOMESH
IOOBJINTERSECTIONS
IOFEATURESEEDS
IOATTRACTION
IOLAYERINFO
Definition at line 88 of file meshRefinement.H.
enum debugType
Enumerator
MESH
OBJINTERSECTIONS
FEATURESEEDS
ATTRACTION
LAYERINFO
Definition at line 98 of file meshRefinement.H.
enum IOoutputType
Enumeration for what to output.
Enumerator
IOOUTPUTLAYERINFO
Definition at line 109 of file meshRefinement.H.
enum outputType
Enumerator
OUTPUTLAYERINFO
Definition at line 114 of file meshRefinement.H.
enum IOwriteType
Enumeration for what to write.
Enumerator
IOWRITEMESH
IOWRITELEVELS
IOWRITELAYERSETS
IOWRITELAYERFIELDS
Definition at line 120 of file meshRefinement.H.
enum writeType
Enumerator
WRITEMESH
WRITELEVELS
WRITELAYERSETS
WRITELAYERFIELDS
Definition at line 128 of file meshRefinement.H.
enum mapType
Enumeration for how the userdata is to be mapped upon refinement.
Enumerator
MASTERONLY
maintain master only
KEEPALL
have slaves (upon refinement) from master
REMOVE
set value to -1 any face that was refined
Definition at line 137 of file meshRefinement.H.
Constructor & Destructor Documentation
meshRefinement (fvMesh & mesh, const scalar mergeDistance, const bool overwrite, const refinementSurfaces & surfaces, const refinementFeatures & features, const shellSurfaces & shells)
Construct from components.
Definition at line 1172 of file meshRefinement.C.
References Foam::identity().
Member Function Documentation
ClassName ("meshRefinement")
Runtime type information.
const fvMesh& mesh () const inline
Reference to mesh.
Definition at line 608 of file meshRefinement.H.
Referenced by autoSnapDriver::calcNearestSurface(), and autoSnapDriver::preSmoothPatch().
fvMesh& mesh () inline
Definition at line 612 of file meshRefinement.H.
scalar mergeDistance () const inline
Definition at line 617 of file meshRefinement.H.
bool overwrite () const inline
Overwrite the mesh?
Definition at line 623 of file meshRefinement.H.
const word& oldInstance () const inline
(points)instance of mesh upon construction
Definition at line 629 of file meshRefinement.H.
const refinementSurfaces& surfaces () const inline
Reference to surface search engines.
Definition at line 635 of file meshRefinement.H.
Referenced by autoSnapDriver::calcNearestSurface().
const refinementFeatures& features () const inline
Reference to feature edge mesh.
Definition at line 641 of file meshRefinement.H.
const shellSurfaces& shells () const inline
Reference to refinement shells (regions)
Definition at line 647 of file meshRefinement.H.
const hexRef8& meshCutter () const inline
Reference to meshcutting engine.
Definition at line 653 of file meshRefinement.H.
const labelList& surfaceIndex () const inline
Per start-end edge the index of the surface hit.
Definition at line 659 of file meshRefinement.H.
labelList& surfaceIndex () inline
Definition at line 664 of file meshRefinement.H.
const List<Tuple2<mapType, labelList> >& userFaceData () const inline
Additional face data that is maintained across.
topo changes. Every entry is a list over all faces. Bit of a hack. Additional flag to say whether to maintain master only (false) or increase set to account for face-from-face.
Definition at line 673 of file meshRefinement.H.
List<Tuple2<mapType, labelList> >& userFaceData () inline
Definition at line 678 of file meshRefinement.H.
Foam::label countHits () const
Count number of intersections (local)
Definition at line 1216 of file meshRefinement.C.
References forAll, PackedList< nBits >::get(), and syncTools::getMasterFaces().
Foam::autoPtr< Foam::mapDistributePolyMesh > balance (const bool keepZoneFaces, const bool keepBaffles, const scalarField & cellWeights, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Redecompose according to cell count.
keepZoneFaces : find all faceZones from zoned surfaces and keep owner and neighbour together keepBaffles : find all baffles and keep them together
Definition at line 1379 of file meshRefinement.C.
References fvMeshDistribute::countCells(), decompositionMethod::decompose(), fvMeshDistribute::distribute(), Foam::endl(), localPointRegion::findDuplicateFacePairs(), Pair< T >::first(), forAll, i, Foam::Info, Pstream::listCombineGather(), Pstream::listCombineScatter(), UPstream::parRun(), Foam::Pout, Foam::reduce(), Foam::returnReduce(), Pair< T >::second(), decompositionMethod::setConstraints(), List< T >::setSize(), List< T >::size(), refinementSurfaces::surfZones(), syncTools::syncFaceList(), timeName, and polyBoundaryMesh::whichPatch().
Foam::labelList intersectedFaces () const
Get faces with intersection.
Definition at line 1659 of file meshRefinement.C.
References forAll.
Foam::labelList intersectedPoints () const
Get points on surfaces with intersection and boundary faces.
Definition at line 1686 of file meshRefinement.C.
References f(), and forAll.
Foam::autoPtr< Foam::indirectPrimitivePatch > makePatch (const polyMesh & mesh, const labelList & patchIDs) static
Create patch from set of patches.
Definition at line 1755 of file meshRefinement.C.
References polyMesh::boundaryMesh(), polyMesh::faces(), forAll, i, polyMesh::points(), and polyPatch::start().
Referenced by autoLayerDriver::addLayers(), autoSnapDriver::doSnap(), and autoSnapDriver::repatchToSurface().
Foam::tmp< Foam::pointVectorField > makeDisplacementField (const pointMesh & pMesh, const labelList & adaptPatchIDs) static
Helper function to make a pointVectorField with correct.
bcs for mesh movement:
adaptPatchIDs : fixedValue
processor : calculated (so free to move)
cyclic/wedge/symmetry : slip
other : slip
Definition at line 1801 of file meshRefinement.C.
References IOobject::AUTO_WRITE, pointMesh::boundary(), Foam::dimLength, forAll, i, mesh, IOobject::NO_READ, PtrList< T >::size(), objectRegistry::time(), Time::timeName(), and Vector< scalar >::zero.
Referenced by autoSnapDriver::doSnap().
void checkCoupledFaceZones (const polyMesh & mesh) static
Helper function: check that face zones are synced.
Definition at line 1858 of file meshRefinement.C.
References Foam::abort(), Foam::exit(), polyMesh::faceZones(), Foam::FatalError, FatalErrorIn, forAll, Pstream::gatherList(), i, UPstream::myProcNo(), zone::name(), IOobject::name(), ZoneMesh< Zone, MeshType >::names(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, UPstream::nProcs(), Pstream::scatterList(), and syncTools::swapBoundaryFaceList().
void calculateEdgeWeights (const polyMesh & mesh, const PackedBoolList & isMasterEdge, const labelList & meshPoints, const edgeList & edges, scalarField & edgeWeights, scalarField & invSumWeight) static
Helper: calculate edge weights (1/length)
Definition at line 1954 of file meshRefinement.C.
References Foam::e, forAll, Foam::mag(), Foam::max(), polyMesh::points(), List< T >::setSize(), List< T >::size(), and PackedList< nBits >::size().
void weightedSum (const polyMesh & mesh, const PackedBoolList & isMasterEdge, const labelList & meshPoints, const edgeList & edges, const scalarField & edgeWeights, const Field< Type > & data, Field< Type > & sum) static
Helper: weighted sum (over all subset of mesh points) by.
summing contribution from (master) edges
Definition at line 289 of file meshRefinementTemplates.C.
References Foam::abort(), Foam::e, Foam::FatalError, FatalErrorIn, forAll, List< Type >::setSize(), List< T >::size(), List< Type >::size(), PackedList< nBits >::size(), and syncTools::syncPointList().
bool isGap (const scalar planarCos, const vector & point0, const vector & normal0, const vector & point1, const vector & normal1) const
Is local topology a small gap?
Hits differ and angles are oppositeish and
hits have a normal distance
Definition at line 1513 of file meshRefinementRefine.C.
References Foam::mag(), and Vector< scalar >::zero.
bool isNormalGap (const scalar planarCos, const vector & point0, const vector & normal0, const vector & point1, const vector & normal1) const
Is local topology a small gap normal to the test vector.
Hits differ and angles are oppositeish and
hits have a normal distance
Definition at line 1570 of file meshRefinementRefine.C.
References Foam::cos(), Foam::degToRad(), Foam::mag(), and Vector< scalar >::zero.
Foam::labelList refineCandidates (const pointField & keepPoints, const scalar curvature, const scalar planarAngle, const bool featureRefinement, const bool featureDistanceRefinement, const bool internalRefinement, const bool surfaceRefinement, const bool curvatureRefinement, const bool gapRefinement, const label maxGlobalCells, const label maxLocalCells) const
Calculate list of cells to refine.
Disable refinement shortcut. nAllowRefine is per processor limit.
Definition at line 2037 of file meshRefinementRefine.C.
References Foam::cos(), Foam::degToRad(), Foam::endl(), forAll, Foam::Info, Foam::labelMax, Foam::max(), UPstream::nProcs(), and List< T >::setSize().
Foam::autoPtr< Foam::mapPolyMesh > refine (const labelList & cellsToRefine)
Refine some cells.
Definition at line 2240 of file meshRefinementRefine.C.
References polyTopoChange::changeMesh(), and timeName.
Foam::autoPtr< Foam::mapDistributePolyMesh > refineAndBalance (const string & msg, decompositionMethod & decomposer, fvMeshDistribute & distributor, const labelList & cellsToRefine, const scalar maxLoadUnbalance)
Refine some cells and rebalance.
Definition at line 2281 of file meshRefinementRefine.C.
References Foam::endl(), Foam::Info, Foam::mag(), UPstream::nProcs(), Foam::Pout, Foam::returnReduce(), timeName, and write().
Foam::autoPtr< Foam::mapDistributePolyMesh > balanceAndRefine (const string & msg, decompositionMethod & decomposer, fvMeshDistribute & distributor, const labelList & cellsToRefine, const scalar maxLoadUnbalance)
Balance before refining some cells.
Definition at line 2382 of file meshRefinementRefine.C.
References Foam::endl(), forAll, i, Foam::Info, Foam::mag(), UPstream::nProcs(), Foam::Pout, Foam::returnReduce(), List< T >::size(), timeName, and write().
void baffleAndSplitMesh (const bool handleSnapProblems, const snapParameters & snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField & perpendicularAngle, const bool mergeFreeStanding, const scalar freeStandingAngle, const dictionary & motionDict, Time & runTime, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const point & keepPoint)
Split off unreachable areas of mesh.
Definition at line 2331 of file meshRefinementBaffles.C.
References cpuTime::cpuTimeIncrement(), Foam::endl(), localPointRegion::findDuplicateFacePairs(), Foam::Info, Foam::nl, Time::path(), Foam::Pout, Foam::reduce(), Foam::returnReduce(), List< T >::size(), timeName, and write().
Foam::autoPtr< Foam::mapPolyMesh > splitMesh (const label nBufferLayers, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const point & keepPoint)
Split off (with optional buffer layers) unreachable areas.
of mesh. Does not introduce baffles.
Definition at line 2522 of file meshRefinementBaffles.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, removeCells::getExposedFaces(), i, Foam::Info, j, Foam::max(), Foam::nl, regionSplit::nRegions(), pFaces, Foam::reduce(), List< T >::size(), syncTools::syncFaceList(), syncTools::syncPointList(), List< T >::transfer(), and WarningIn.
Foam::autoPtr< Foam::mapPolyMesh > dupNonManifoldPoints (const localPointRegion & regionSide)
Find boundary points that connect to more than one cell.
region and split them.
Definition at line 2810 of file meshRefinementBaffles.C.
References polyTopoChange::changeMesh(), Foam::endl(), Foam::Info, localPointRegion::meshPointMap(), Foam::returnReduce(), duplicatePoints::setRefinement(), HashTable< T, Key, Hash >::size(), and timeName.
Foam::autoPtr< Foam::mapPolyMesh > dupNonManifoldPoints ()
Find boundary points that connect to more than one cell.
region and split them.
Definition at line 2864 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > createBaffles (const labelList & ownPatch, const labelList & neiPatch)
Create baffle for every internal face where ownPatch != -1.
External faces get repatched according to ownPatch (neiPatch should be -1 for these)
Redo the intersections on the newly create baffle faces. Note that
this changes also the cell centre positions.
Definition at line 394 of file meshRefinementBaffles.C.
References Foam::abort(), polyTopoChange::changeMesh(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, HashSet< Key, Hash >::insert(), List< T >::size(), faceSet::sync(), syncTools::syncFaceList(), timeName, and HashTable< T, Key, Hash >::toc().
void checkZoneFaces () const
Debug helper: check faceZones are not on processor patches.
Definition at line 535 of file meshRefinementBaffles.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, i, patchIdentifier::name(), IOobject::name(), polyPatch::start(), and ZoneMesh< Zone, MeshType >::whichZone().
Foam::autoPtr< Foam::mapPolyMesh > createZoneBaffles (const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, List< labelPair > & baffles)
Create baffles for faces straddling zoned surfaces. Return.
baffles.
Definition at line 566 of file meshRefinementBaffles.C.
References Foam::abort(), HashTableCore::end(), Foam::endl(), Foam::FatalError, FatalErrorIn, HashTable< T, label, Hash< label > >::find(), forAll, forAllConstIter, surfaceZonesInfo::getNamedSurfaces(), Foam::Info, iter, Foam::nl, Foam::Pout, Foam::returnReduce(), List< T >::setSize(), List< T >::size(), HashTable< T, label, Hash< label > >::size(), timeName, and write().
Foam::autoPtr< Foam::mapPolyMesh > mergeBaffles (const List< labelPair > & couples)
Merge baffles. Gets pairs of faces.
Definition at line 932 of file meshRefinementBaffles.C.
References polyTopoChange::changeMesh(), UList< T >::first(), faceZone::flipMap(), forAll, i, polyTopoChange::setAction(), List< T >::size(), timeName, faceZone::whichFace(), and ZoneMesh< Zone, MeshType >::whichZone().
Foam::autoPtr< Foam::mapPolyMesh > zonify (const point & keepPoint, const bool allowFreeStandingZoneFaces)
Put faces/cells into zones according to surface specification.
Returns null if no zone surfaces present. Region containing the keepPoint will not be put into a cellZone.
Definition at line 2875 of file meshRefinementBaffles.C.
References surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), polyTopoChange::changeMesh(), polyPatch::coupled(), cz(), end(), Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, fz(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), syncTools::getMasterFaces(), surfaceZonesInfo::getNamedSurfaces(), i, Foam::Info, HashTable< T, Key, Hash >::insert(), Foam::magSqr(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), Foam::max(), n, zone::name(), Foam::nl, Foam::Pout, Foam::returnReduce(), polyTopoChange::setAction(), List< T >::size(), PtrList< T >::size(), Foam::sqrt(), polyPatch::start(), syncTools::swapBoundaryFaceList(), syncTools::syncFaceList(), and timeName.
Foam::label appendPatch (fvMesh & mesh, const label insertPatchI, const word & patchName, const dictionary & patchDict) static
Helper:append patch to end of mesh.
Definition at line 2010 of file meshRefinement.C.
References fvMesh::boundary(), polyMesh::boundaryMesh(), fvMesh::clearOut(), mesh, fvPatch::New(), polyPatch::New(), PtrList< T >::set(), PtrList< T >::setSize(), and PtrList< T >::size().
Foam::label addPatch (fvMesh & mesh, const word & name, const dictionary & patchInfo) static
Helper:add patch to mesh. Update all registered fields.
Used by addMeshedPatch to add patches originating from surfaces.
Definition at line 2109 of file meshRefinement.C.
References fvMesh::boundary(), polyMesh::boundaryMesh(), polyBoundaryMesh::findPatchID(), forAll, i, mesh, primitiveMesh::nFaces(), PtrList< T >::reorder(), polyBoundaryMesh::reorder(), dictionary::set(), PtrList< T >::size(), and polyPatch::start().
Foam::label addMeshedPatch (const word & name, const dictionary & patchInfo)
Add patch originating from meshing. Update meshedPatches_.
Definition at line 2187 of file meshRefinement.C.
References Foam::findIndex().
Foam::labelList meshedPatches () const
Get patchIDs for patches added in addMeshedPatch.
Definition at line 2234 of file meshRefinement.C.
References Foam::abort(), List< T >::append(), polyPatch::constraintType(), Foam::FatalError, FatalErrorIn, polyBoundaryMesh::findPatchID(), forAll, i, polyBoundaryMesh::names(), and Foam::type().
void selectSeparatedCoupledFaces (boolList & selected) const
Select coupled faces that are not collocated.
Definition at line 2260 of file meshRefinement.C.
References forAll, i, coupledPolyPatch::parallel(), coupledPolyPatch::separated(), and polyPatch::start().
Foam::label findRegion (const polyMesh & mesh, const labelList & cellRegion, const vector & perturbVec, const point & p) static
Find region point is in. Uses optional perturbation to re-test.
Definition at line 2287 of file meshRefinement.C.
References polyMesh::findCell(), and Foam::reduce().
Foam::autoPtr< Foam::mapPolyMesh > splitMeshRegions (const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const point & keepPoint)
Split mesh. Keep part containing point.
Definition at line 2317 of file meshRefinement.C.
References List< T >::append(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, removeCells::getExposedFaces(), Foam::Info, Foam::nl, Foam::reduce(), Foam::returnReduce(), List< T >::size(), and WarningIn.
Foam::autoPtr< Foam::mapPolyMesh > splitFaces (const labelList & splitFaces, const labelPairList & splits)
Split faces into two.
Definition at line 682 of file meshRefinement.C.
References polyTopoChange::addFace(), polyTopoChange::changeMesh(), Foam::endl(), f(), f1, UList< T >::fcIndex(), faceZone::flipMap(), forAll, fz(), i, polyTopoChange::modifyFace(), Foam::Pout, Foam::renumber(), List< T >::setSize(), List< T >::size(), timeName, and faceZone::whichFace().
void distribute (const mapDistributePolyMesh & map)
Update local numbering for mesh redistribution.
Definition at line 2419 of file meshRefinement.C.
References autoPtr< T >::clear(), mapDistributePolyMesh::distributeFaceData(), Foam::e, treeBoundBox::extend(), forAll, i, meshBb(), rndGen(), and autoPtr< T >::valid().
void updateMesh (const mapPolyMesh & map, const labelList & changedFaces)
Update for external change to mesh. changedFaces are in new mesh.
face labels.
Definition at line 2478 of file meshRefinement.C.
void updateList (const labelList & newToOld, const T & nullValue, List< T > & elems) static
Helper: reorder list according to map.
Definition at line 35 of file meshRefinementTemplates.C.
References forAll, i, List< T >::size(), and List< T >::transfer().
Referenced by autoLayerDriver::addLayers(), and autoSnapDriver::doSnap().
void storeData (const labelList & pointsToStore, const labelList & facesToStore, const labelList & cellsToStore)
Signal points/face/cells for which to store data.
Definition at line 2490 of file meshRefinement.C.
void updateMesh (const mapPolyMesh & map, const labelList & changedFaces, const Map< label > & pointsToRestore, const Map< label > & facesToRestore, const Map< label > & cellsToRestore)
Update local numbering + undo.
Data to restore given as new pointlabel + stored pointlabel (i.e. what was in pointsToStore)
Definition at line 2507 of file meshRefinement.C.
References mapPolyMesh::faceMap(), forAll, i, mapPolyMesh::reverseFaceMap(), List< T >::size(), and List< T >::transfer().
Foam::label mergePatchFacesUndo (const scalar minCos, const scalar concaveCos, const labelList & patchIDs, const dictionary & motionDict, const labelList & preserveFaces)
Merge coplanar faces. preserveFaces is != -1 for faces.
to be preserved
Definition at line 248 of file meshRefinementMerge.C.
References polyTopoChange::changeMesh(), polyPatch::coupled(), Foam::endl(), forAll, forAllConstIter, combineFaces::getMergeSets(), i, Foam::Info, Foam::inplaceMapKey(), IOobject::instance(), iter, j, combineFaces::masterFace(), Foam::nl, IOobject::objectPath(), patches, Foam::Pout, Foam::returnReduce(), combineFaces::savedPointLabels(), set(), combineFaces::setRefinement(), combineFaces::setUnrefinement(), HashTable< T, Key, Hash >::size(), polyPatch::start(), timeName, combineFaces::updateMesh(), write(), Ostream::write(), and regIOobject::write().
Foam::autoPtr< Foam::mapPolyMesh > doRemovePoints (removePoints & pointRemover, const boolList & pointCanBeDeleted)
Definition at line 627 of file meshRefinementMerge.C.
References polyTopoChange::changeMesh(), Foam::endl(), forAll, i, Foam::Pout, removePoints::savedFaceLabels(), removePoints::setRefinement(), List< T >::size(), timeName, and removePoints::updateMesh().
Foam::autoPtr< Foam::mapPolyMesh > doRestorePoints (removePoints & pointRemover, const labelList & facesToRestore)
Definition at line 685 of file meshRefinementMerge.C.
References polyTopoChange::changeMesh(), Foam::endl(), forAll, removePoints::getUnrefimentSet(), i, Foam::Pout, removePoints::setUnrefinement(), List< T >::size(), timeName, and removePoints::updateMesh().
Foam::labelList collectFaces (const labelList & candidateFaces, const labelHashSet & set) const
Definition at line 758 of file meshRefinementMerge.C.
References Foam::findIndices(), forAll, HashTable< T, Key, Hash >::found(), and i.
Foam::labelList growFaceCellFace (const labelHashSet & set) const
Definition at line 790 of file meshRefinementMerge.C.
References Foam::findIndices(), forAll, forAllConstIter, and iter.
Foam::label mergeEdgesUndo (const scalar minCos, const dictionary & motionDict)
Merge edges, maintain mesh quality. Return global number.
of edges merged
Definition at line 832 of file meshRefinementMerge.C.
References removePoints::countPointUsage(), Foam::endl(), Foam::Info, n, Foam::nl, Foam::Pout, Foam::returnReduce(), removePoints::savedFaceLabels(), List< T >::size(), timeName, write(), and Ostream::write().
void checkData ()
Debugging: check that all faces still obey start()>end()
Definition at line 415 of file meshRefinement.C.
References end(), Foam::endl(), localPointRegion::findDuplicateFaces(), forAll, i, Foam::identity(), Foam::Pout, Foam::sqrt(), syncTools::swapBoundaryFaceList(), syncTools::syncBoundaryFacePositions(), and WarningIn.
void testSyncPointList (const string & msg, const polyMesh & mesh, const List< scalar > & fld) static
Definition at line 316 of file meshRefinement.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, Foam::mag(), Foam::nl, primitiveMesh::nPoints(), polyMesh::points(), Foam::Pout, List< T >::size(), and syncTools::syncPointList().
void testSyncPointList (const string & msg, const polyMesh & mesh, const List< point > & fld) static
Definition at line 366 of file meshRefinement.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, Foam::mag(), Foam::nl, primitiveMesh::nPoints(), polyMesh::points(), Foam::Pout, List< T >::size(), syncTools::syncPointList(), and Vector< scalar >::zero.
void testSyncBoundaryFaceList (const scalar mergeDistance, const string & msg, const UList< T > & faceData, const UList< T > & syncedFaceData) const
Compare two lists over all boundary faces.
Definition at line 108 of file meshRefinementTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, i, Foam::mag(), patchIdentifier::name(), patches, UList< T >::size(), polyPatch::start(), and T.
void collectAndPrint (const UList< point > & points, const UList< T > & data) static
Print list according to (collected and) sorted coordinate.
Definition at line 168 of file meshRefinementTemplates.C.
References Foam::DelaunayMeshTools::allPoints(), Foam::endl(), forAll, i, Foam::identity(), Foam::Info, Foam::mag(), UList< T >::size(), and Foam::sortedOrder().
Foam::PackedBoolList getMasterPoints (const polyMesh & mesh, const labelList & meshPoints) static
Determine master point for subset of points. If coupled.
chooses only one
Definition at line 2641 of file meshRefinement.C.
References forAll, Foam::labelMax, List< T >::size(), and syncTools::syncPointList().
Referenced by autoSnapDriver::calcNearestSurface(), and autoSnapDriver::detectNearSurfaces().
Foam::PackedBoolList getMasterEdges (const polyMesh & mesh, const labelList & meshEdges) static
Determine master edge for subset of edges. If coupled.
chooses only one
Definition at line 2678 of file meshRefinement.C.
References forAll, Foam::labelMax, List< T >::size(), and syncTools::syncEdgeList().
void printMeshInfo (const bool debug, const string & msg) const
Print some mesh stats.
Definition at line 2714 of file meshRefinement.C.
References Foam::endl(), forAll, syncTools::getMasterFaces(), syncTools::getMasterPoints(), Foam::gMax(), i, Foam::Info, Pstream::listCombineGather(), Pstream::listCombineScatter(), globalMeshData::nTotalCells(), Foam::Pout, and Foam::returnReduce().
Foam::word timeName () const
Replacement for Time::timeName() : return oldInstance (if.
Return either time().constant() or oldInstance.
overwrite_)
Definition at line 2782 of file meshRefinement.C.
Referenced by autoSnapDriver::preSmoothPatch().
void setInstance (const fileName & inst)
Set instance of all local IOobjects.
Definition at line 612 of file meshRefinement.C.
bool write () const
Write mesh and all data.
Definition at line 2601 of file meshRefinement.C.
References TimePaths::caseConstant(), TimePaths::caseSystem(), TimePaths::constant(), forAll, i, IOobject::instance(), s(), TimePaths::system(), IOobject::time(), Time::timeName(), and regIOobject::write().
Referenced by autoSnapDriver::preSmoothPatch().
void dumpRefinementLevel () const
Write refinement level as volScalarFields for postprocessing.
Definition at line 2795 of file meshRefinement.C.
References IOobject::AUTO_WRITE, Foam::dimless, forAll, MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), IOobject::NO_READ, and IOobject::NO_WRITE.
void dumpIntersections (const fileName & prefix) const
Debug: Write intersection information to OBJ format.
Definition at line 2857 of file meshRefinement.C.
References end(), Foam::endl(), forAll, i, OFstream::name(), Foam::nl, Foam::Pout, List< T >::size(), Foam::sqrt(), and Foam::meshTools::writeOBJ().
void write (const debugType debugFlags, const writeType writeFlags, const fileName & prefix) const
Do any one of above IO functions.
Definition at line 2938 of file meshRefinement.C.
References write().
T gAverage (const PackedBoolList & isMasterElem, const UList< T > & values) static
Helper: calculate average.
Definition at line 59 of file meshRefinementTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, i, n, reduce(), PackedList< nBits >::size(), UList< T >::size(), Foam::sum(), and T.
Referenced by autoSnapDriver::calcNearestSurface().
Foam::meshRefinement::writeType writeLevel () static
Get/set write level.
Definition at line 2959 of file meshRefinement.C.
Referenced by autoLayerDriver::addLayers(), autoSnapDriver::doSnap(), autoSnapDriver::preSmoothPatch(), and autoSnapDriver::smoothDisplacement().
void writeLevel (const writeType flags) static
Definition at line 2965 of file meshRefinement.C.
Foam::meshRefinement::outputType outputLevel () static
Get/set output level.
Definition at line 2971 of file meshRefinement.C.
void outputLevel (const outputType flags) static
Definition at line 2977 of file meshRefinement.C.
int readFlags (const Enum & namedEnum, const wordList & words) static
Helper: convert wordList into bit pattern using provided.
NamedEnum
Definition at line 270 of file meshRefinementTemplates.C.
References forAll, and i.
Member Data Documentation
const Foam::NamedEnum< Foam::meshRefinement::IOdebugType, 5 > IOdebugTypeNames static
Definition at line 97 of file meshRefinement.H.
const Foam::NamedEnum< Foam::meshRefinement::IOoutputType, 1 > IOoutputTypeNames static
Definition at line 113 of file meshRefinement.H.
const Foam::NamedEnum< Foam::meshRefinement::IOwriteType, 4 > IOwriteTypeNames static
Definition at line 127 of file meshRefinement.H.
The documentation for this class was generated from the following files:
src/mesh/autoMesh/autoHexMesh/meshRefinement/meshRefinement.H
src/mesh/autoMesh/autoHexMesh/meshRefinement/meshRefinement.C
src/mesh/autoMesh/autoHexMesh/meshRefinement/meshRefinementBaffles.C
src/mesh/autoMesh/autoHexMesh/meshRefinement/meshRefinementMerge.C
src/mesh/autoMesh/autoHexMesh/meshRefinement/meshRefinementProblemCells.C
src/mesh/autoMesh/autoHexMesh/meshRefinement/meshRefinementRefine.C
src/mesh/autoMesh/autoHexMesh/meshRefinement/meshRefinementTemplates.C