OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
LRR< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Launder, Reece and Rodi Reynolds-stress turbulence model for incompressible and compressible flows.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel >::alphaField alphaField
typedef RASModel< BasicTurbulenceModel >::rhoField rhoField
typedef RASModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("LRR")
Runtime type information.
LRR (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~LRR ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
tmp< volSymmTensorField > DREff () const
Return the effective diffusivity for R.
tmp< volSymmTensorField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual void correct ()
Solve the turbulence equations and correct eddy-Viscosity and.
Public Member Functions inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
ReynoldsStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~ReynoldsStress ()
Destructor.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual void correctNut ()
Update the eddy-viscosity.
Protected Member Functions inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
void boundNormalStress (volSymmTensorField &R) const
void correctWallShearStress (volSymmTensorField &R) const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar Ceps1_
dimensionedScalar Ceps2_
dimensionedScalar Cs_
dimensionedScalar Ceps_
Switch wallReflection_
dimensionedScalar kappa_
dimensionedScalar Cref1_
dimensionedScalar Cref2_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
dimensionedScalar couplingFactor_
volSymmTensorField R_
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::LRR< BasicTurbulenceModel >
Launder, Reece and Rodi Reynolds-stress turbulence model for incompressible and compressible flows.
Reference:
    Launder, B. E., Reece, G. J., & Rodi, W. (1975).
    Progress in the development of a Reynolds-stress turbulence closure.
    Journal of fluid mechanics, 68(03), 537-566.
Including the recommended generalized gradient diffusion model of Daly and Harlow:
    Daly, B. J., & Harlow, F. H. (1970).
    Transport equations in turbulence.
    Physics of Fluids (1958-1988), 13(11), 2634-2649.
Optional Gibson-Launder wall-reflection is also provided:
    Gibson, M. M., & Launder, B. E. (1978).
    Ground effects on pressure fluctuations in the
    atmospheric boundary layer.
    Journal of Fluid Mechanics, 86(03), 491-511.
The default model coefficients are:
    LRRCoeffs
    {
        Cmu             0.09;
        C1              1.8;
        C2              0.6;
        Ceps1           1.44;
        Ceps2           1.92;
        Cs              0.25;
        Ceps            0.15;
        wallReflection  yes;
        kappa           0.41
        Cref1           0.5;
        Cref2           0.3;
        couplingFactor  0.0;
    }
Source files
LRR.H
LRR.C
Definition at line 100 of file LRR.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 150 of file LRR.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 151 of file LRR.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 152 of file LRR.H.
Constructor & Destructor Documentation
LRR (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 54 of file LRR.C.
References Foam::bound(), and Foam::tr().
virtual ~LRR () inline virtual
Destructor.
Definition at line 176 of file LRR.H.
References LRR< BasicTurbulenceModel >::read().
Member Function Documentation
void correctNut () protected virtual
Update the eddy-viscosity.
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 40 of file LRR.C.
References optionList::correct(), options::New(), and Foam::sqr().
TypeName ("LRR< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Read model coefficients if they have changed.
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 217 of file LRR.C.
References Foam::read().
Referenced by LRR< BasicTurbulenceModel >::~LRR().
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Reimplemented from ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 186 of file LRR.H.
References LRR< BasicTurbulenceModel >::k_.
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 192 of file LRR.H.
References LRR< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::DepsilonEff(), LRR< BasicTurbulenceModel >::DREff(), and LRR< BasicTurbulenceModel >::epsilon_.
tmp< volSymmTensorField > DREff () const
Return the effective diffusivity for R.
Definition at line 244 of file LRR.C.
References Foam::I, and nu.
Referenced by LRR< BasicTurbulenceModel >::epsilon().
tmp< volSymmTensorField > DepsilonEff () const
Return the effective diffusivity for epsilon.
Definition at line 258 of file LRR.C.
References Foam::I, and nu.
Referenced by LRR< BasicTurbulenceModel >::epsilon().
void correct () virtual
Solve the turbulence equations and correct eddy-Viscosity and.
related properties
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 272 of file LRR.C.
References Foam::bound(), optionList::constrain(), correct, optionList::correct(), Foam::fvm::ddt(), Foam::dev(), Foam::fvm::div(), fvPatch::faceCells(), forAll, fvOptions, Foam::constant::universal::G, Foam::fvc::grad(), Foam::I, Foam::fvm::laplacian(), Foam::mag(), Foam::min(), n, options::New(), MeshObject< fvMesh, UpdateableMeshObject, wallDist >::New(), patches, patchi, Foam::pow(), R, tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), Foam::sqrt(), Foam::symm(), Foam::tr(), Foam::twoSymm(), and y.
Referenced by LRR< BasicTurbulenceModel >::epsilon().
Member Data Documentation
dimensionedScalar Cmu_ protected
Definition at line 117 of file LRR.H.
dimensionedScalar C1_ protected
Definition at line 119 of file LRR.H.
dimensionedScalar C2_ protected
Definition at line 120 of file LRR.H.
dimensionedScalar Ceps1_ protected
Definition at line 122 of file LRR.H.
dimensionedScalar Ceps2_ protected
Definition at line 123 of file LRR.H.
dimensionedScalar Cs_ protected
Definition at line 124 of file LRR.H.
dimensionedScalar Ceps_ protected
Definition at line 125 of file LRR.H.
Switch wallReflection_ protected
Definition at line 130 of file LRR.H.
dimensionedScalar kappa_ protected
Definition at line 131 of file LRR.H.
dimensionedScalar Cref1_ protected
Definition at line 132 of file LRR.H.
dimensionedScalar Cref2_ protected
Definition at line 133 of file LRR.H.
volScalarField k_ protected
Definition at line 138 of file LRR.H.
Referenced by LRR< BasicTurbulenceModel >::k().
volScalarField epsilon_ protected
Definition at line 139 of file LRR.H.
Referenced by LRR< BasicTurbulenceModel >::epsilon().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/LRR/LRR.H
src/TurbulenceModels/turbulenceModels/RAS/LRR/LRR.C