OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mappedFieldFvPatchField< Type > Class Template Reference
Boundary Conditions » Generic boundary ConditionsBoundary Conditions » | Coupled boundary Conditions
This boundary condition provides a self-contained version of the mapped condition. It does not use information on the patch; instead it holds thr data locally.
Public Member Functions
TypeName ("mappedField")
Runtime type information.
mappedFieldFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
mappedFieldFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mappedFieldFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar distance, const word &fieldName, const bool setAverage, const Type average, const word &interpolationScheme)
Construct from patch, internal field and distance for normal type.
mappedFieldFvPatchField (const mappedFieldFvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
mappedFieldFvPatchField (const mappedFieldFvPatchField< Type > &)
Construct as copy.
virtual tmp< fvPatchField< Type > > clone () const
Construct and return a clone.
mappedFieldFvPatchField (const mappedFieldFvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< Type > > clone (const DimensionedField< Type, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from fixedValueFvPatchField< Type >
TypeName ("fixedValue")
Runtime type information.
fixedValueFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
fixedValueFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedValueFvPatchField (const fixedValueFvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fixedValueFvPatchField<Type>
fixedValueFvPatchField (const fixedValueFvPatchField< Type > &)
Construct as copy.
fixedValueFvPatchField (const fixedValueFvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< scalarField > &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< scalarField > &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the.
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvPatchField< Type > &)
virtual void operator+= (const fvPatchField< Type > &)
virtual void operator-= (const fvPatchField< Type > &)
virtual void operator*= (const fvPatchField< scalar > &)
virtual void operator/= (const fvPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
Public Member Functions inherited from fvPatchField< Type >
TypeName ("fvPatchField")
Runtime type information.
declareRunTimeSelectionTable (tmp, fvPatchField, patch,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvPatchField, patchMapper,(const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict),(p, iF, dict))
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const word &patchType)
Construct from patch and internal field and patch type.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &, const bool valueRequired=false)
Construct from patch, internal field and dictionary.
fvPatchField (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fvPatchField onto a new patch.
fvPatchField (const fvPatchField< Type > &)
Construct as copy.
fvPatchField (const fvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual ~fvPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
const fvPatch & patch () const
Return patch.
const DimensionedField< Type, volMesh > & dimensionedInternalField () const
Return dimensioned internal field reference.
const Field< Type > & internalField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
bool manipulatedMatrix () const
Return true if the matrix has already been manipulated.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchField< Type > &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual tmp< Field< Type > > snGrad () const
Return patch-normal gradient.
virtual tmp< Field< Type > > snGrad (const scalarField &deltaCoeffs) const
Return patch-normal gradient for coupled-patches.
virtual void updateCoeffs (const scalarField &weights)
Update the coefficients associated with the patch field.
virtual tmp< Field< Type > > patchInternalField () const
Return internal field next to patch as patch field.
virtual void patchInternalField (Field< Type > &) const
Return internal field next to patch as patch field.
virtual tmp< Field< Type > > patchNeighbourField () const
Return patchField on the opposite patch of a coupled patch.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise the evaluation of the patch field.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field, sets Updated to false.
virtual tmp< Field< Type > > gradientInternalCoeffs (const scalarField &deltaCoeffs) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs (const scalarField &deltaCoeffs) const
Return the matrix source coefficients corresponding to the.
virtual void manipulateMatrix (fvMatrix< Type > &matrix)
Manipulate matrix.
virtual void manipulateMatrix (fvMatrix< Type > &matrix, const scalarField &weights)
Manipulate matrix with given weights.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
void check (const fvPatchField< Type > &) const
Check fvPatchField<Type> against given fvPatchField<Type>
virtual void operator== (const fvPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &pf)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type > > &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type > > &tmapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reUse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type > > &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type > > &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type > > &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map)
Map from the given field.
void map (const tmp< Field< Type > > &tmapF, const FieldMapper &map)
Map from the given tmp field.
void autoMap (const FieldMapper &map)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type > > &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType > > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type > > &)
void operator= (const Type &)
template<class Form , class Cmpt , int nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type > > &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type > > &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar > > &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type > > &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reUse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< Type >
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< Type > &)
Assign elements to those from UList.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
void operator= (const Type &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Public Member Functions inherited from mappedPatchBase
TypeName ("mappedPatchBase")
Runtime type information.
mappedPatchBase (const polyPatch &)
Construct from patch.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
Construct with offsetMode=non-uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &offset)
Construct from offsetMode=uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar distance)
Construct from offsetMode=normal and distance.
mappedPatchBase (const polyPatch &, const dictionary &)
Construct from dictionary.
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
Construct from dictionary and (collocated) sample mode.
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
Construct as copy, resetting patch.
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
Construct as copy, resetting patch, map original data.
virtual ~mappedPatchBase ()
Destructor.
void clearOut ()
const sampleMode & mode () const
What to sample.
const word & sampleRegion () const
Region to sample.
const word & samplePatch () const
Patch (only if NEARESTPATCHFACE)
const word & coupleGroup () const
PatchGroup (only if NEARESTPATCHFACE)
label sampleSize () const
Return size of mapped mesh/patch/boundary.
const vector & offset () const
Offset vector (from patch faces to destination mesh objects)
const vectorField & offsets () const
Offset vector (from patch faces to destination mesh objects)
bool sameRegion () const
Cached sampleRegion != mesh.name()
const mapDistribute & map () const
Return reference to the parallel distribution map.
const AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
Return reference to the AMI interpolator.
const autoPtr< Foam::searchableSurface > & surfPtr () const
Return a pointer to the AMI projection surface.
const polyMesh & sampleMesh () const
Get the region mesh.
const polyPatch & samplePolyPatch () const
Get the patch on the region.
tmp< pointField > samplePoints () const
Get the sample points.
template<class Type >
void distribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
template<class Type >
void reverseDistribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
Public Member Functions inherited from mappedPatchFieldBase< Type >
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const word &fieldName, const bool setAverage, const Type average, const word &interpolationScheme)
Construct from components.
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const dictionary &dict)
Construct from dictionary.
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField)
Construct empty.
mappedPatchFieldBase (const mappedPatchFieldBase< Type > &mapper)
Construct copy.
mappedPatchFieldBase (const mappedPatchBase &mapper, const fvPatchField< Type > &patchField, const mappedPatchFieldBase< Type > &base)
Construct copy, resetting patch and field.
virtual ~mappedPatchFieldBase ()
Destructor.
const GeometricField< Type, fvPatchField, volMesh > & sampleField () const
Field to sample. Either on my or nbr mesh.
virtual tmp< Field< Type > > mappedField () const
Map sampleField onto *this patch.
Additional Inherited Members
Public Types inherited from fvPatchField< Type >
typedef fvPatch Patch
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Types inherited from mappedPatchBase
enum sampleMode {
NEARESTCELL, NEARESTPATCHFACE, NEARESTPATCHFACEAMI, NEARESTPATCHPOINT,
NEARESTFACE, NEARESTONLYCELL
}
Mesh items to sample.
enum offsetMode { UNIFORM, NONUNIFORM, NORMAL }
How to project face centres.
typedef Tuple2< pointIndexHit, Tuple2< scalar, label > > nearInfo
Helper class for finding nearest.
Static Public Member Functions inherited from fvPatchField< Type >
static tmp< fvPatchField< Type > > New (const word &, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const word &, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static tmp< fvPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatch &)
Return a pointer to a new calculatedFvPatchField created on.
template<class Type2 >
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &)
Return a pointer to a new calculatedFvPatchField created on.
static const word & calculatedType ()
Return the type of the calculated for of fvPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Member Functions inherited from mappedPatchBase
static pointIndexHit facePoint (const polyMesh &, const label faceI, const polyMesh::cellDecomposition)
Get a point on the face given a face decomposition method:
Static Public Attributes inherited from fvPatchField< Type >
static int disallowGenericFvPatchField
Debug switch to disallow the use of genericFvPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Static Public Attributes inherited from mappedPatchBase
static const NamedEnum< sampleMode, 6 > sampleModeNames_
static const NamedEnum< offsetMode, 3 > offsetModeNames_
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Member Functions inherited from mappedPatchBase
tmp< pointField > facePoints (const polyPatch &) const
Get the points from face-centre-decomposition face centres.
void collectSamples (const pointField &facePoints, pointField &, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
Collect single list of samples and originating processor+face.
void findSamples (const sampleMode mode, const pointField &, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
Find cells/faces containing samples.
tmp< pointField > samplePoints (const pointField &) const
Get the sample points given the face points.
void calcMapping () const
Calculate mapping.
void calcAMI () const
Calculate AMI interpolator.
Static Protected Member Functions inherited from mappedPatchBase
static tmp< pointField > readListOrField (const word &keyword, const dictionary &dict, const label size)
Helper to read field or non-uniform list from dictionary.
Protected Attributes inherited from mappedPatchBase
const polyPatch & patch_
Patch to sample.
word sampleRegion_
Region to sample.
const sampleMode mode_
What to sample.
word samplePatch_
Patch (if in sampleMode NEARESTPATCH*)
const coupleGroupIdentifier coupleGroup_
PatchGroup (if in sampleMode NEARESTPATCH*)
offsetMode offsetMode_
How to obtain samples.
vector offset_
Offset vector (uniform)
vectorField offsets_
Offset vector (nonuniform)
scalar distance_
Offset distance (normal)
bool sameRegion_
Same region.
autoPtr< mapDistribute > mapPtr_
Communication schedule:
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
Pointer to AMI interpolator.
const bool AMIReverse_
Flag to indicate that slave patch should be reversed for AMI.
autoPtr< searchableSurface > surfPtr_
Pointer to projection surface employed by AMI interpolator.
dictionary surfDict_
Dictionary storing projection surface description.
Protected Attributes inherited from mappedPatchFieldBase< Type >
const mappedPatchBase & mapper_
Mapping engine.
const fvPatchField< Type > & patchField_
Underlying patch field.
word fieldName_
Name of field to sample.
const bool setAverage_
If true adjust the mapped field to maintain average value average_.
const Type average_
Average value the mapped field is adjusted to maintain if.
word interpolationScheme_
Interpolation scheme to use for nearestcell mode.
Detailed Description
template<class Type>
class Foam::mappedFieldFvPatchField< Type >
This boundary condition provides a self-contained version of the mapped condition. It does not use information on the patch; instead it holds thr data locally.
Patch usage
Property Description Required Default value
fieldName name of field to be mapped no this field name
setAverage flag to activate setting of average value yes
average average value to apply if setAverage = yes yes
Example of the boundary condition specification:
    myPatch
    {
        type            mappedField;
        fieldName       T;              // optional field name
        setAverage      no;             // apply an average value
        average         0;              // average to apply if setAverage
        value           uniform 0;      // place holder
    }
Note
Since this condition can be applied on a per-field and per-patch basis, it is possible to duplicate the mapping information. If possible, employ the mapped condition in preference to avoid this situation, and only employ this condition if it is not possible to change the underlying geometric (poly) patch type to mapped.
See also
Foam::mappedPatchBase Foam::mappedPolyPatch Foam::mappedFvPatch Foam::fixedValueFvPatchField
Source files
mappedFieldFvPatchField.H
mappedFieldFvPatchField.C
Definition at line 111 of file mappedFieldFvPatchField.H.
Constructor & Destructor Documentation
mappedFieldFvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF)
Construct from patch and internal field.
Definition at line 34 of file mappedFieldFvPatchField.C.
mappedFieldFvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 47 of file mappedFieldFvPatchField.C.
mappedFieldFvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const scalar distance, const word & fieldName, const bool setAverage, const Type average, const word & interpolationScheme)
Construct from patch, internal field and distance for normal type.
sampling
Definition at line 76 of file mappedFieldFvPatchField.C.
mappedFieldFvPatchField (const mappedFieldFvPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
mappedFieldFvPatchField onto a new patch
Definition at line 61 of file mappedFieldFvPatchField.C.
mappedFieldFvPatchField (const mappedFieldFvPatchField< Type > & ptf)
Construct as copy.
Definition at line 116 of file mappedFieldFvPatchField.C.
mappedFieldFvPatchField (const mappedFieldFvPatchField< Type > & ptf, const DimensionedField< Type, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 128 of file mappedFieldFvPatchField.C.
Member Function Documentation
TypeName ("mappedField")
Runtime type information.
virtual tmp<fvPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from fixedValueFvPatchField< Type >.
Definition at line 179 of file mappedFieldFvPatchField.H.
virtual tmp<fvPatchField<Type> > clone (const DimensionedField< Type, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from fixedValueFvPatchField< Type >.
Definition at line 199 of file mappedFieldFvPatchField.H.
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from fvPatchField< Type >.
Definition at line 142 of file mappedFieldFvPatchField.C.
References dimensionedInternalField(), Foam::endl(), Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, and Foam::operator==().
void write (Ostream & os) const virtual
Write.
Reimplemented from fixedValueFvPatchField< Type >.
Definition at line 166 of file mappedFieldFvPatchField.C.
References write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedField/mappedFieldFvPatchField.H
src/finiteVolume/fields/fvPatchFields/derived/mappedField/mappedFieldFvPatchField.C