OpenFOAM: manualRenumber Class Reference
manualRenumber Class Reference
Renumber given a ordered-to-original cell association in a file.
Public Member Functions
TypeName ("manual")
Runtime type information.
manualRenumber (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~manualRenumber ()
Destructor.
virtual labelList renumber (const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const labelListList &cellCells, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~renumberMethod ()
Destructor.
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
Return the order in which cells need to be visited, i.e.
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Return a reference to the selected renumbering method.
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Renumber given a ordered-to-original cell association in a file.
Source files
manualRenumber.H
manualRenumber.C
Definition at line 46 of file manualRenumber.H.
Constructor & Destructor Documentation
manualRenumber (const dictionary & renumberDict)
Construct given the renumber dictionary.
Definition at line 48 of file manualRenumber.C.
References manualRenumber::renumber().
virtual ~manualRenumber () inline virtual
Destructor.
Definition at line 75 of file manualRenumber.H.
References mesh, NotImplemented, and manualRenumber::renumber().
Member Function Documentation
TypeName ("manual")
Runtime type information.
virtual labelList renumber (const pointField &) const inline virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. This is only defined for geometric renumberMethods.
Reimplemented from renumberMethod.
Definition at line 84 of file manualRenumber.H.
Referenced by manualRenumber::manualRenumber(), and manualRenumber::~manualRenumber().
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Use the mesh connectivity (if needed)
Reimplemented from renumberMethod.
Definition at line 61 of file manualRenumber.C.
References IOobject::AUTO_WRITE, Foam::endl(), Foam::exit(), polyMesh::facesInstance(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, IOobject::MUST_READ, and List< T >::size().
virtual labelList renumber (const labelListList & cellCells, const pointField & cc) const inline virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. The connectivity is equal to mesh.cellCells() except
the connections are across coupled patches
Implements renumberMethod.
Definition at line 104 of file manualRenumber.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/manualRenumber/manualRenumber.H
src/renumber/renumberMethods/manualRenumber/manualRenumber.C