OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mag Class Reference
FunctionObjects » Field function objects
This function object calculates the magnitude of a field. The operation can be applied to any volume or surface fieldsm and the output is a volume or surface scalar field.
Public Member Functions
TypeName ("mag")
Runtime type information.
mag (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~mag ()
Destructor.
virtual bool read (const dictionary &)
Read the mag data.
virtual bool execute (const bool postProcess=false)
Calculate the magnitude field.
virtual bool write (const bool postProcess=false)
Write the magnitude field.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from functionObject
static int debug
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Detailed Description
This function object calculates the magnitude of a field. The operation can be applied to any volume or surface fieldsm and the output is a volume or surface scalar field.
See also
Foam::functionObjects::fvMeshFunctionObject
Source files
mag.H
mag.C
Definition at line 63 of file mag.H.
Constructor & Destructor Documentation
mag (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 45 of file mag.C.
References Foam::read().
~mag () virtual
Destructor.
Definition at line 59 of file mag.C.
Member Function Documentation
TypeName ("mag")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the mag data.
Implements functionObject.
Definition at line 65 of file mag.C.
References dictionary::lookup().
bool execute (const bool postProcess = false) virtual
Calculate the magnitude field.
Implements functionObject.
Definition at line 79 of file mag.C.
References Foam::endl(), and WarningInFunction.
bool write (const bool postProcess = false) virtual
Write the magnitude field.
Implements functionObject.
Definition at line 99 of file mag.C.
References Foam::endl(), Foam::Info, Foam::name(), IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/mag/mag.H
src/postProcessing/functionObjects/field/mag/mag.C
src/postProcessing/functionObjects/field/mag/magTemplates.C