OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
listPlusEqOp< T > Class Template Reference
Public Member Functions
void operator() (List< T > &x, const List< T > &y) const
Detailed Description
template<class T>
class Foam::listPlusEqOp< T >
Definition at line 47 of file snappySnapDriverFeature.C.
Member Function Documentation
void operator() (List< T > & x, const List< T > & y) const inline
Definition at line 51 of file snappySnapDriverFeature.C.
References List< T >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), pointConstraint::applyConstraint(), meshRefinement::ATTRACTION, polyMesh::boundaryMesh(), PrimitivePatch< Face, FaceList, PointField, PointType >::boundaryPoints(), Foam::constant::universal::c, DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), Foam::cos(), polyPatch::coupled(), Foam::degToRad(), Foam::diag(), Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), primitiveMesh::edges(), UList< T >::empty(), Foam::endl(), Foam::exit(), snapParameters::explicitFeatureSnap(), f(), primitiveMesh::faceAreas(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceCentres(), primitiveMesh::faceCentres(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementSurfaces::findNearestRegion(), refinementFeatures::findNearestRegionEdge(), ZoneMesh< ZoneType, MeshType >::findZoneID(), Tuple2< Type1, Type2 >::first(), UList< T >::first(), forAll, meshRefinement::gAverage(), meshRefinement::getMasterEdges(), syncTools::getMasterFaces(), meshRefinement::getMasterPoints(), surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), refinementSurfaces::globalRegion(), Foam::gMaxMagSqr(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), snapParameters::implicitFeatureSnap(), PointIndexHit< Point >::index(), Foam::Info, primitiveMesh::isInternalFace(), Foam::labelMax, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), face::mag(), Foam::mag(), Foam::magSqr(), Foam::max(), mesh, PrimitivePatch< Face, FaceList, PointField, PointType >::meshEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), PointIndexHit< Point >::missPoint(), snapParameters::multiRegionFeatureSnap(), n, Foam::name(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), edge::otherVertex(), p, motionSmootherAlgo::patch(), patchi, polyBoundaryMesh::patchID(), Time::path(), pFaces, plane::planeIntersect(), plane::planePlaneIntersect(), PrimitivePatch< Face, FaceList, PointField, PointType >::pointEdges(), primitiveMesh::pointEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::pointFaces(), primitiveMesh::pointFaces(), PatchTools::pointNormals(), points, polyMesh::points(), Foam::reduce(), relax(), autoPtr< T >::reset(), Foam::returnReduce(), rndGen(), s(), Tuple2< Type1, Type2 >::second(), List< T >::setSize(), indexedOctree< Type >::shapes(), List< T >::size(), UPtrList< T >::size(), Foam::sortedOrder(), Foam::sqr(), Foam::sqrt(), polyPatch::start(), refinementSurfaces::surfaces(), refinementSurfaces::surfZones(), syncTools::syncEdgeList(), syncTools::syncPointList(), fvMesh::time(), Foam::transform(), autoPtr< T >::valid(), WarningInFunction, Foam::Zero, and VectorSpace< Vector< scalar >, scalar, 3 >::zero.
The documentation for this class was generated from the following file:
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappySnapDriverFeature.C