OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
MatrixSpace< Form, Cmpt, Mrows, Ncols > Class Template Reference
Templated matrix space.
Classes
class Block
Sub-block type.
class ConstBlock
Const sub-block type.
Public Types
typedef MatrixSpace< Form, Cmpt, Mrows, Ncols > msType
MatrixSpace type.
Public Types inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
typedef VectorSpace< Form, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
Public Member Functions
MatrixSpace ()
Construct null.
MatrixSpace (const Foam::zero)
Construct initialized to zero.
template<class Form2 , class Cmpt2 >
MatrixSpace (const VectorSpace< Form2, Cmpt2, Mrows *Ncols > &)
Construct as copy of a VectorSpace with the same size.
template<template< class, direction, direction > class Block2, direction BRowStart, direction BColStart>
MatrixSpace (const Block2< Form, BRowStart, BColStart > &block)
Construct from a block of another matrix space.
MatrixSpace (Istream &)
Construct from Istream.
template<direction Row, direction Col>
const Cmpt & elmt () const
Fast const element access using compile-time addressing.
template<direction Row, direction Col>
Cmpt & elmt ()
Fast element access using compile-time addressing.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & xz () const
const Cmpt & yx () const
const Cmpt & yy () const
const Cmpt & yz () const
const Cmpt & zx () const
const Cmpt & zy () const
const Cmpt & zz () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & xz ()
Cmpt & yx ()
Cmpt & yy ()
Cmpt & yz ()
Cmpt & zx ()
Cmpt & zy ()
Cmpt & zz ()
typeOfTranspose< Cmpt, Form >::type T () const
Return the transpose of the matrix.
template<class SubTensor , direction BRowStart, direction BColStart>
ConstBlock< SubTensor, BRowStart, BColStart > block () const
Return a const sub-block corresponding to the specified type.
template<class SubTensor , direction BRowStart, direction BColStart>
Block< SubTensor, BRowStart, BColStart > block ()
Return a sub-block corresponding to the specified type.
const Cmpt & operator() (const direction &i, const direction &j) const
(i, j) const element access operator
Cmpt & operator() (const direction &i, const direction &j)
(i, j) element access operator
void operator= (const Foam::zero)
Assignment to zero.
template<template< class, direction, direction > class Block2, direction BRowStart, direction BColStart>
void operator= (const Block2< Form, BRowStart, BColStart > &block)
Assignment to a block of another matrix space.
template<class Form2 >
void operator&= (const MatrixSpace< Form, Cmpt, Ncols, Ncols > &matrix)
Inner product with a compatible square matrix.
template<class SubTensor , Foam::direction BRowStart, Foam::direction BColStart>
Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >::template ConstBlock< SubTensor, BRowStart, BColStart > block () const
template<class SubTensor , Foam::direction BRowStart, Foam::direction BColStart>
Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >::template Block< SubTensor, BRowStart, BColStart > block ()
Public Member Functions inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Form, Cmpt, Ncmpts > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Member Functions
static direction m ()
Return the number of rows.
static direction n ()
Return the number of columns.
static msType identity ()
Return the identity matrix for square matrix spaces.
Static Public Member Functions inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Form uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Static Public Attributes
static const direction mRows = Mrows
static const direction nCols = Ncols
Static Public Attributes inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
static const direction dim
Dimensionality of space.
static const direction nComponents
Number of components in this vector space.
static const direction mRows
static const direction nCols
static const char *const typeName
static const char *const componentNames []
static const Form zero
static const Form one
static const Form max
static const Form min
static const Form rootMax
static const Form rootMin
Additional Inherited Members
Public Attributes inherited from VectorSpace< Form, Cmpt, Mrows *Ncols >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Form, class Cmpt, direction Mrows, direction Ncols>
class Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >
Templated matrix space.
Template arguments are the Form the matrix space will be used to create, the type of the elements and the number of rows and columns of the matrix.
Source files
MatrixSpace.H
MatrixSpaceI.H
See also
Foam::VectorSpace
Definition at line 55 of file MatrixSpace.H.
Member Typedef Documentation
typedef MatrixSpace<Form, Cmpt, Mrows, Ncols> msType
MatrixSpace type.
Definition at line 63 of file MatrixSpace.H.
Constructor & Destructor Documentation
MatrixSpace () inline
Construct null.
Definition at line 31 of file MatrixSpaceI.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::MatrixSpace(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
MatrixSpace (const Foam::zero) inline
Construct initialized to zero.
Definition at line 37 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::MatrixSpace().
MatrixSpace (const VectorSpace< Form2, Cmpt2, Mrows *Ncols > & vs) inline explicit
Construct as copy of a VectorSpace with the same size.
Definition at line 48 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::MatrixSpace().
MatrixSpace (const Block2< Form, BRowStart, BColStart > & block) inline
Construct from a block of another matrix space.
Definition at line 64 of file MatrixSpaceI.H.
MatrixSpace (Istream & is) inline
Construct from Istream.
Definition at line 79 of file MatrixSpaceI.H.
Member Function Documentation
static direction m () inline static
Return the number of rows.
Definition at line 75 of file MatrixSpace.H.
static direction n () inline static
Return the number of columns.
Definition at line 81 of file MatrixSpace.H.
Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols > identity () inline static
Return the identity matrix for square matrix spaces.
Definition at line 273 of file MatrixSpaceI.H.
References Foam::Zero.
Referenced by MatrixSpace< Tensor< scalar >, scalar, 3, 3 >::n().
const Cmpt & elmt () const inline
Fast const element access using compile-time addressing.
Definition at line 131 of file MatrixSpaceI.H.
References VectorSpace< Form, Cmpt, Mrows *Ncols >::v_.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
Cmpt & elmt () inline
Fast element access using compile-time addressing.
Definition at line 140 of file MatrixSpaceI.H.
References VectorSpace< Form, Cmpt, Mrows *Ncols >::v_.
const Cmpt & xx () const inline
Definition at line 148 of file MatrixSpaceI.H.
Referenced by Rxyz::jcalc(), Rzyx::jcalc(), Ryxz::jcalc(), Rs::jcalc(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
const Cmpt & xy () const inline
Definition at line 162 of file MatrixSpaceI.H.
Referenced by Rxyz::jcalc(), Ryxz::jcalc(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
const Cmpt & xz () const inline
Definition at line 176 of file MatrixSpaceI.H.
Referenced by Rzyx::jcalc(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
const Cmpt & yx () const inline
Definition at line 190 of file MatrixSpaceI.H.
Referenced by Rxyz::jcalc(), Rzyx::jcalc(), Ryxz::jcalc(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
const Cmpt & yy () const inline
Definition at line 204 of file MatrixSpaceI.H.
Referenced by Rxyz::jcalc(), Rzyx::jcalc(), Ryxz::jcalc(), Rs::jcalc(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
const Cmpt & yz () const inline
Definition at line 218 of file MatrixSpaceI.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
const Cmpt & zx () const inline
Definition at line 232 of file MatrixSpaceI.H.
Referenced by Rxyz::jcalc(), Rzyx::jcalc(), Ryxz::jcalc(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
const Cmpt & zy () const inline
Definition at line 246 of file MatrixSpaceI.H.
Referenced by Rzyx::jcalc(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
const Cmpt & zz () const inline
Definition at line 260 of file MatrixSpaceI.H.
Referenced by Rxyz::jcalc(), Ryxz::jcalc(), Rs::jcalc(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
Cmpt & xx () inline
Definition at line 155 of file MatrixSpaceI.H.
Cmpt & xy () inline
Definition at line 169 of file MatrixSpaceI.H.
Cmpt & xz () inline
Definition at line 183 of file MatrixSpaceI.H.
Cmpt & yx () inline
Definition at line 197 of file MatrixSpaceI.H.
Cmpt & yy () inline
Definition at line 211 of file MatrixSpaceI.H.
Cmpt & yz () inline
Definition at line 225 of file MatrixSpaceI.H.
Cmpt & zx () inline
Definition at line 239 of file MatrixSpaceI.H.
Cmpt & zy () inline
Definition at line 253 of file MatrixSpaceI.H.
Cmpt & zz () inline
Definition at line 266 of file MatrixSpaceI.H.
Foam::typeOfTranspose< Cmpt, Form >::type T () const inline
Return the transpose of the matrix.
Definition at line 289 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator()().
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=(), and Foam::T().
ConstBlock<SubTensor, BRowStart, BColStart> block () const inline
Return a const sub-block corresponding to the specified type.
starting at the specified row and column
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator=().
Block<SubTensor, BRowStart, BColStart> block () inline
Return a sub-block corresponding to the specified type.
starting at the specified row and column
const Cmpt & operator() (const direction & i, const direction & j) const inline
(i, j) const element access operator
Definition at line 340 of file MatrixSpaceI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, VectorSpace< Form, Cmpt, Mrows *Ncols >::operator, and VectorSpace< Form, Cmpt, Mrows *Ncols >::v_.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::operator()(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator()(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator()().
Cmpt & operator() (const direction & i, const direction & j) inline
(i, j) element access operator
Definition at line 360 of file MatrixSpaceI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator()(), and VectorSpace< Form, Cmpt, Mrows *Ncols >::v_.
void operator= (const Foam::zero) inline
Assignment to zero.
Definition at line 445 of file MatrixSpaceI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::operator=(), and Foam::Zero.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
void operator= (const Block2< Form, BRowStart, BColStart > & block) inline
Assignment to a block of another matrix space.
Definition at line 472 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::block(), VectorSpace< Form, Cmpt, Mrows *Ncols >::operator, and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator()().
void operator&= (const MatrixSpace< Form, Cmpt, Ncols, Ncols > & matrix) inline
Inner product with a compatible square matrix.
Definition at line 456 of file MatrixSpaceI.H.
Foam::MatrixSpace<Form, Cmpt, Mrows, Ncols>::template ConstBlock<SubTensor, BRowStart, BColStart> block () const inline
Definition at line 314 of file MatrixSpaceI.H.
Foam::MatrixSpace<Form, Cmpt, Mrows, Ncols>::template Block<SubTensor, BRowStart, BColStart> block () inline
Definition at line 330 of file MatrixSpaceI.H.
References VectorSpace< Form, Cmpt, Mrows *Ncols >::operator.
Member Data Documentation
const direction mRows = Mrows static
Definition at line 68 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::Block(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::ConstBlock().
const direction nCols = Ncols static
Definition at line 69 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::Block(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::ConstBlock().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/MatrixSpace/MatrixSpace.H
src/OpenFOAM/primitives/MatrixSpace/MatrixSpaceI.H