OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Matrix< Form, Type > Class Template Reference
A templated 2D matrix of objects of <T>, where the n x m matrix dimensions are known and used for subscript bounds checking, etc.
Public Member Functions
Matrix ()
Null constructor.
Matrix (const label n, const label m)
Construct given number of rows and columns.
Matrix (const label n, const label m, const Type &)
Construct with given number of rows and columns.
Matrix (const Matrix< Form, Type > &)
Copy constructor.
Matrix (Istream &)
Construct from Istream.
autoPtr< Matrix< Form, Type > > clone () const
Clone.
~Matrix ()
Destructor.
label n () const
Return the number of rows.
label m () const
Return the number of columns.
label size () const
Return the number of elements in matrix (n*m)
void checki (const label i) const
Check index i is within valid range (0 ... n-1).
void checkj (const label j) const
Check index j is within valid range (0 ... m-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (Matrix< Form, Type > &)
Transfer the contents of the argument Matrix into this Matrix.
Form T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
void operator= (const Matrix< Form, Type > &)
Assignment operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Static Public Member Functions
static const Matrix< Form, Type > & null ()
Return a null Matrix.
Friends
Istream & operator>> (Istream &, Matrix< Form, Type > &)
Read Matrix from Istream, discarding contents of existing Matrix.
Ostream & operator (Ostream &, const Matrix< Form, Type > &)
Detailed Description
template<class Form, class Type>
class Foam::Matrix< Form, Type >
A templated 2D matrix of objects of <T>, where the n x m matrix dimensions are known and used for subscript bounds checking, etc.
Source files
Matrix.H
Matrix.C
MatrixI.H
MatrixIO.C
Definition at line 47 of file DiagonalMatrix.H.
Constructor & Destructor Documentation
Matrix () inline
Null constructor.
Definition at line 29 of file MatrixI.H.
References Matrix< Form, Type >::clone().
Matrix (const label n, const label m)
Construct given number of rows and columns.
Definition at line 62 of file Matrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Matrix (const label n, const label m, const Type & a)
Construct with given number of rows and columns.
and value for all elements.
Definition at line 80 of file Matrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Matrix (const Matrix< Form, Type > & a)
Copy constructor.
Definition at line 110 of file Matrix.C.
Matrix (Istream & is)
Construct from Istream.
Definition at line 35 of file MatrixIO.C.
References IOstream::ASCII, token::BEGIN_BLOCK, token::BEGIN_LIST, Matrix< Form, Type >::clear(), token::END_BLOCK, token::END_LIST, Foam::exit(), IOstream::fatalCheck(), Foam::FatalIOError, FatalIOErrorInFunction, IOstream::format(), token::info(), token::isLabel(), k, token::labelToken(), Matrix< Form, Type >::m(), M, Matrix< Form, Type >::n(), Foam::nl, Foam::operator>>(), Matrix< Form, Type >::operator>>, Istream::read(), Istream::readBeginList(), Istream::readEndList(), Foam::readLabel(), and token::SPACE.
~Matrix ()
Destructor.
Definition at line 49 of file Matrix.C.
Member Function Documentation
const Foam::Matrix< Form, Type > & null () inline static
Return a null Matrix.
Definition at line 48 of file MatrixI.H.
Foam::autoPtr< Foam::Matrix< Form, Type > > clone () const inline
Clone.
Definition at line 39 of file MatrixI.H.
Referenced by Matrix< Form, Type >::Matrix().
Foam::label n () const inline
Return the number of rows.
Definition at line 56 of file MatrixI.H.
Referenced by Foam::LUBacksubstitute(), Foam::LUDecompose(), Foam::LUsolve(), Matrix< Form, Type >::Matrix(), Foam::max(), Foam::min(), Foam::multiply(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Foam::solve(), SVD::SVD(), and Matrix< Form, Type >::T().
Foam::label m () const inline
Return the number of columns.
Definition at line 63 of file MatrixI.H.
Referenced by Matrix< Form, Type >::Matrix(), Foam::max(), Foam::min(), Foam::multiply(), Foam::operator*(), Foam::operator+(), Foam::operator-(), SVD::SVD(), and Matrix< Form, Type >::T().
Foam::label size () const inline
Return the number of elements in matrix (n*m)
Definition at line 70 of file MatrixI.H.
void checki (const label i) const inline
Check index i is within valid range (0 ... n-1).
Definition at line 77 of file MatrixI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by Matrix< Form, Type >::operator[]().
void checkj (const label j) const inline
Check index j is within valid range (0 ... m-1).
Definition at line 95 of file MatrixI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
void clear ()
Clear the Matrix, i.e. set sizes to zero.
Definition at line 132 of file Matrix.C.
Referenced by Matrix< Form, Type >::Matrix(), Matrix< Form, Type >::operator=(), and Matrix< Form, Type >::transfer().
void transfer (Matrix< Form, Type > & a)
Transfer the contents of the argument Matrix into this Matrix.
and annul the argument Matrix.
Definition at line 146 of file Matrix.C.
References Matrix< Form, Type >::clear().
Form T () const
Return the transpose of the matrix.
Definition at line 162 of file Matrix.C.
References Matrix< Form, Type >::m(), and Matrix< Form, Type >::n().
Referenced by SVD::SVD().
Type * operator[] (const label i) inline
Return subscript-checked row of Matrix.
Definition at line 115 of file MatrixI.H.
References Matrix< Form, Type >::checki().
const Type * operator[] (const label i) const inline
Return subscript-checked row of constant Matrix.
Definition at line 125 of file MatrixI.H.
References Matrix< Form, Type >::checki().
void operator= (const Matrix< Form, Type > & a)
Assignment operator. Takes linear time.
Definition at line 199 of file Matrix.C.
References Foam::abort(), Matrix< Form, Type >::clear(), Foam::FatalError, and FatalErrorInFunction.
void operator= (const Type & t)
Assignment of all entries to the given value.
Definition at line 182 of file Matrix.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , Matrix< Form, Type > &) friend
Read Matrix from Istream, discarding contents of existing Matrix.
Referenced by Matrix< Form, Type >::Matrix().
Ostream& operator (Ostream & , const Matrix< Form, Type > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/DiagonalMatrix/DiagonalMatrix.H
src/OpenFOAM/matrices/Matrix/Matrix.H
src/OpenFOAM/matrices/Matrix/Matrix.C
src/OpenFOAM/matrices/Matrix/MatrixI.H
src/OpenFOAM/matrices/Matrix/MatrixIO.C