OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
metisDecomp Class Reference
Metis domain decomposition.
Public Member Functions
TypeName ("metis")
Runtime type information.
metisDecomp (const dictionary &)
Construct given the decomposition dictionary.
virtual ~metisDecomp ()
Destructor.
virtual bool parallelAware () const
Is method parallel aware (i.e. does it synchronize domains across.
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const polyMesh &mesh, const labelList &agglom, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)
Return for every coordinate the wanted processor number. Explicitly.
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual labelList decompose (const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &, const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
Protected Attributes inherited from decompositionMethod
const dictionary & decompositionDict_
label nProcessors_
Detailed Description
Metis domain decomposition.
Source files
metisDecomp.H
metisDecomp.C
Definition at line 46 of file metisDecomp.H.
Constructor & Destructor Documentation
metisDecomp (const dictionary & decompositionDict)
Construct given the decomposition dictionary.
Definition at line 76 of file dummyMetisDecomp.C.
virtual ~metisDecomp () inline virtual
Destructor.
Definition at line 80 of file metisDecomp.H.
Member Function Documentation
TypeName ("metis")
Runtime type information.
virtual bool parallelAware () const inline virtual
Is method parallel aware (i.e. does it synchronize domains across.
proc boundaries)
Implements decompositionMethod.
Definition at line 86 of file metisDecomp.H.
Foam::labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) virtual
Return for every coordinate the wanted processor number. Use the.
mesh connectivity (if needed) Weights get normalised so the minimum value is 1 before truncation to an integer so the weights should be multiples of the minimum value. The overall sum of weights might otherwise overflow.
Implements decompositionMethod.
Definition at line 87 of file dummyMetisDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and notImplementedMessage.
Foam::labelList decompose (const polyMesh & mesh, const labelList & agglom, const pointField & regionPoints, const scalarField & regionWeights) virtual
Return for every coordinate the wanted processor number. Gets.
passed agglomeration map (from fine to coarse cells) and coarse cell location. Can be overridden by decomposers that provide this functionality natively. See note on weights above.
Reimplemented from decompositionMethod.
Definition at line 101 of file dummyMetisDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and notImplementedMessage.
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) virtual
Return for every coordinate the wanted processor number. Explicitly.
provided mesh connectivity. The connectivity is equal to mesh.cellCells() except for
in parallel the cell numbers are global cell numbers (starting from 0 at processor0 and then incrementing all through the processors)
the connections are across coupled patches See note on weights above.
Implements decompositionMethod.
Definition at line 116 of file dummyMetisDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and notImplementedMessage.
The documentation for this class was generated from the following files:
src/parallel/decompose/metisDecomp/metisDecomp.H
src/dummyThirdParty/metisDecomp/dummyMetisDecomp.C
src/parallel/decompose/metisDecomp/metisDecomp.C