OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mapDistribute Class Reference
Class containing processor-to-processor mapping information.
Classes
class transform
Default transformation behaviour.
class transformPosition
Default transformation behaviour for position.
Public Member Functions
ClassName ("mapDistribute")
mapDistribute ()
Construct null.
mapDistribute (const label constructSize, const Xfer< labelListList > &subMap, const Xfer< labelListList > &constructMap)
Construct from components.
mapDistribute (const label constructSize, const Xfer< labelListList > &subMap, const Xfer< labelListList > &constructMap, const Xfer< labelListList > &transformElements, const Xfer< labelList > &transformStart)
Construct from components.
mapDistribute (const labelList &sendProcs, const labelList &recvProcs)
Construct from reverse addressing: per data item the send.
mapDistribute (const globalIndex &, labelList &elements, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex.
mapDistribute (const globalIndex &, labelListList &cellCells, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Special variant that works with the info sorted into bins.
mapDistribute (const globalIndex &, labelList &untransformedElements, const globalIndexAndTransform &, const labelPairList &transformedElements, labelList &transformedIndices, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly remote) untransformed elements.
mapDistribute (const globalIndex &, labelListList &cellCells, const globalIndexAndTransform &, const List< labelPairList > &transformedElements, labelListList &transformedIndices, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
As above but with ListLists.
mapDistribute (const Xfer< mapDistribute > &)
Construct by transferring parameter content.
mapDistribute (const mapDistribute &)
Construct copy.
label constructSize () const
Constructed data size.
label & constructSize ()
Constructed data size.
const labelListList & subMap () const
From subsetted data back to original data.
labelListList & subMap ()
From subsetted data back to original data.
const labelListList & constructMap () const
From subsetted data to new reconstructed data.
labelListList & constructMap ()
From subsetted data to new reconstructed data.
const labelListList & transformElements () const
For every globalIndexAndTransform::transformPermutations.
const labelList & transformStart () const
Destination in constructMap for transformed elements.
label whichTransform (const label index) const
Find transform from transformElements.
const List< labelPair > & schedule () const
Return a schedule. Demand driven. See above.
void transfer (mapDistribute &)
Transfer the contents of the argument and annul the argument.
Xfer< mapDistribute > xfer ()
Transfer contents to the Xfer container.
void compact (const boolList &elemIsUsed, const int tag=UPstream::msgType())
Compact maps. Gets per field a bool whether it is used (locally)
template<class T >
void distribute (DynamicList< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void distribute (List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T , class TransformOp >
void distribute (const globalIndexAndTransform &, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
Same but with transforms.
template<class T >
void reverseDistribute (const label constructSize, List< T > &, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
Same but with transforms.
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, const T &nullValue, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
Same but with transforms.
template<class T >
void send (PstreamBuffers &, const List< T > &) const
Do all sends using PstreamBuffers.
template<class T >
void receive (PstreamBuffers &, List< T > &) const
Do all receives using PstreamBuffers.
void printLayout (Ostream &os) const
Debug: print layout. Can only be used on maps with sorted.
void updateMesh (const mapPolyMesh &)
Correct for topo change.
void operator= (const mapDistribute &)
Static Public Member Functions
static List< labelPair > schedule (const labelListList &subMap, const labelListList &constructMap, const int tag)
Calculate a schedule. See above.
static label renumber (const globalIndex &, const List< Map< label >> &compactMap, const label globalElement)
Helper for construct from globalIndex. Renumbers element.
template<class T >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const labelListList &constructMap, List< T > &, const int tag=UPstream::msgType())
Distribute data. Note:schedule only used for Pstream::scheduled.
template<class T , class CombineOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const labelListList &constructMap, List< T > &, const CombineOp &cop, const T &nullValue, const int tag=UPstream::msgType())
Distribute data. If multiple processors writing to same.
Friends
Istream & operator>> (Istream &, mapDistribute &)
Read dictionary from Istream.
Ostream & operator<< (Ostream &, const mapDistribute &)
Write dictionary to Ostream.
Detailed Description
Class containing processor-to-processor mapping information.
We store mapping from the bits-to-send to the complete starting list (subXXXMap) and from the received bits to their location in the new list (constructXXXMap).
Note: Schedule is a list of processor pairs (one send, one receive. One of them will be myself) which forms a scheduled (i.e. non-buffered) exchange. See distribute on how to use it. Note2: number of items sent on one processor have to equal the number of items received on the other processor.
To aid constructing these maps there are the constructors from global numbering, either with or without transforms.
without transforms: Constructors using compact numbering: layout is
all my own elements first (whether used or not)
followed by used-only remote elements sorted by remote processor. So e.g 4 procs and on proc 1 the compact table will first have all globalIndex.localSize() elements from proc1 followed by used-only elements of proc0, proc2, proc3. The constructed mapDistribute sends the local elements from and receives the remote elements into their compact position. compactMap[proci] is the position of elements from proci in the compact map. compactMap[myProcNo()] is empty since trivial addressing.
It rewrites the input global indices into indices into the constructed data.
with transforms: This requires the precalculated set of possible transforms (globalIndexAndTransform). These are given as permutations (+, -, or none) of up to 3 independent transforms. The layout of the data is
all my own elements first (whether used or not)
followed by used-only remote elements sorted by remote processor.
followed by - for each transformation index - the set of local or remote elements with that transformation. The inputs for the constructor are
the set of untransformed local or remote indices in globalIndex numbering. These get rewritten to be indices into the layout of the data.
the set of transformed local or remote indices in globalIndexAndTransform encoding. These are labelPairs.
Any distribute with transforms is now done as: 1. exchange data with other processors and receive these into the slots for that processor 2. for all transformations transform a subset of the data according to transformElements_[transformI] and store this starting from transformStart_[transformI]
In the same way a reverse distribute will 1. apply the inverse transform to the data starting at transformStart_[transformI] and copy the result back into the transformElements_[transformI]. These might be local or remote slots. 2. the data in the remote slots will now be sent back to the correct location in the originating processor.
E.g. a map to handle
mesh points on a mesh with
1 cyclic so 3 permutations (+,-,none) will have layout
on e.g. processor 1 out of 2:
+——+ <- transformStart[2] | | | | <- transform2 applied to data in local or remote slots | | +——+ <- transformStart[1] | | | | <- transform1 applied to data in local or remote slots | | +——+ <- transformStart[1] | | | | <- transform0 applied to data in local or remote slots | | +——+ <- transformStart[0] | | | | <- data from proc2 | | +——+ | | | | <- data from proc0 | | +——+ <- mesh.nPoints() | | | | | | +——+ 0
Source files
mapDistribute.H
mapDistribute.C
mapDistributeTemplates.C
Definition at line 152 of file mapDistribute.H.
Constructor & Destructor Documentation
mapDistribute ()
Construct null.
Definition at line 632 of file mapDistribute.C.
Referenced by mapDistribute::mapDistribute(), and mapDistribute::transformPosition::operator()().
mapDistribute (const label constructSize, const Xfer< labelListList > & subMap, const Xfer< labelListList > & constructMap)
Construct from components.
Definition at line 640 of file mapDistribute.C.
References mapDistribute::mapDistribute().
mapDistribute (const label constructSize, const Xfer< labelListList > & subMap, const Xfer< labelListList > & constructMap, const Xfer< labelListList > & transformElements, const Xfer< labelList > & transformStart)
Construct from components.
Definition at line 654 of file mapDistribute.C.
References mapDistribute::mapDistribute().
mapDistribute (const labelList & sendProcs, const labelList & recvProcs)
Construct from reverse addressing: per data item the send.
processor and the receive processor. (note: data is not stored sorted per processor so cannot use printLayout).
Definition at line 672 of file mapDistribute.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, mapDistribute::mapDistribute(), UPstream::myProcNo(), UPstream::nProcs(), List< T >::setSize(), and List< T >::size().
mapDistribute (const globalIndex & globalNumbering, labelList & elements, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex.
numbering (or -1). Determines compact numbering (see above) and distribute map to get data into this ordering and renumbers the elements to be in compact numbering.
Definition at line 744 of file mapDistribute.C.
References mapDistribute::mapDistribute(), Foam::Pout, and mapDistribute::printLayout().
mapDistribute (const globalIndex & globalNumbering, labelListList & cellCells, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Special variant that works with the info sorted into bins.
according to local indices. E.g. think cellCells where cellCells[localCelli] is a list of global cells
Definition at line 802 of file mapDistribute.C.
References mapDistribute::mapDistribute(), Foam::Pout, and mapDistribute::printLayout().
mapDistribute (const globalIndex & globalNumbering, labelList & untransformedElements, const globalIndexAndTransform & globalTransforms, const labelPairList & transformedElements, labelList & transformedIndices, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Construct from list of (possibly remote) untransformed elements.
in globalIndex numbering (or -1) and (possibly remote) transformded elements in globalIndexAndTransform numbering. Determines compact numbering (see above) and distribute map to get data into this ordering and renumbers the elements to be in compact numbering.
Definition at line 860 of file mapDistribute.C.
References forAll, globalIndexAndTransform::index(), mapDistribute::mapDistribute(), UPstream::myProcNo(), n, Foam::Pout, mapDistribute::printLayout(), globalIndexAndTransform::processor(), List< T >::setSize(), List< T >::size(), globalIndexAndTransform::transformIndex(), and globalIndexAndTransform::transformPermutations().
mapDistribute (const globalIndex & globalNumbering, labelListList & cellCells, const globalIndexAndTransform & globalTransforms, const List< labelPairList > & transformedElements, labelListList & transformedIndices, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
As above but with ListLists.
Definition at line 966 of file mapDistribute.C.
References forAll, globalIndexAndTransform::index(), UPstream::myProcNo(), n, Foam::Pout, mapDistribute::printLayout(), globalIndexAndTransform::processor(), List< T >::setSize(), List< T >::size(), globalIndexAndTransform::transformIndex(), and globalIndexAndTransform::transformPermutations().
mapDistribute (const Xfer< mapDistribute > & map)
Construct by transferring parameter content.
Definition at line 1095 of file mapDistribute.C.
mapDistribute (const mapDistribute & map)
Construct copy.
Definition at line 1084 of file mapDistribute.C.
Member Function Documentation
ClassName ("mapDistribute")
Referenced by mapDistribute::transformPosition::operator()().
label constructSize () const inline
Constructed data size.
Definition at line 465 of file mapDistribute.H.
Referenced by extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), PointEdgeWave< Type, TrackingData >::countPatchType(), PatchTools::edgeNormals(), globalMeshData::mergePoints(), minEqOp< labelPair >::operator()(), mapDistribute::transformPosition::operator()(), PatchTools::pointNormals(), syncTools::syncEdgeList(), syncTools::syncPointList(), pointConstraints::syncUntransformedData(), mapDistribute::transformStart(), and AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod().
label& constructSize () inline
Constructed data size.
Definition at line 471 of file mapDistribute.H.
const labelListList& subMap () const inline
From subsetted data back to original data.
Definition at line 477 of file mapDistribute.H.
Referenced by refinementHistory::distribute(), NamedEnum< Enum, nEnum >::names(), mapDistribute::transformPosition::operator()(), InteractionLists< ParticleType >::sendReferredData(), AMIInterpolation< SourcePatch, TargetPatch >::update(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), and extendedCellToFaceStencil::writeStencilStats().
labelListList& subMap () inline
From subsetted data back to original data.
Definition at line 483 of file mapDistribute.H.
const labelListList& constructMap () const inline
From subsetted data to new reconstructed data.
Definition at line 489 of file mapDistribute.H.
Referenced by refinementHistory::distribute(), NamedEnum< Enum, nEnum >::names(), mapDistribute::transformPosition::operator()(), InteractionLists< ParticleType >::receiveReferredData(), AMIInterpolation< SourcePatch, TargetPatch >::update(), and AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod().
labelListList& constructMap () inline
From subsetted data to new reconstructed data.
Definition at line 495 of file mapDistribute.H.
References mapDistribute::transformElements().
const labelListList& transformElements () const inline
For every globalIndexAndTransform::transformPermutations.
gives the elements that need to be transformed
Definition at line 502 of file mapDistribute.H.
Referenced by mapDistribute::constructMap(), and mapDistribute::transformPosition::operator()().
const labelList& transformStart () const inline
Destination in constructMap for transformed elements.
Definition at line 508 of file mapDistribute.H.
References mapDistribute::compact(), mapDistribute::constructSize(), mapDistribute::distribute(), fld(), UPstream::msgType(), mapDistribute::printLayout(), mapDistribute::receive(), mapDistribute::renumber(), mapDistribute::reverseDistribute(), mapDistribute::schedule(), mapDistribute::send(), Foam::T(), mapDistribute::transfer(), mapDistribute::whichTransform(), and mapDistribute::xfer().
Referenced by mapDistribute::transformPosition::operator()().
Foam::label whichTransform (const label index) const
Find transform from transformElements.
Definition at line 1108 of file mapDistribute.C.
References Foam::findLower().
Referenced by mapDistribute::transformStart().
Foam::List< Foam::labelPair > schedule (const labelListList & subMap, const labelListList & constructMap, const int tag) static
Calculate a schedule. See above.
Definition at line 138 of file mapDistribute.C.
References Foam::findIndex(), UPstream::firstSlave(), forAll, HashSet< Key, Hash >::insert(), UPstream::lastSlave(), UPstream::master(), UPstream::masterNo(), UPstream::myProcNo(), UPstream::nProcs(), UPstream::scheduled, List< T >::setSize(), List< T >::size(), and HashTable< nil, Key, Hash >::toc().
const Foam::List< Foam::labelPair > & schedule () const
Return a schedule. Demand driven. See above.
Definition at line 263 of file mapDistribute.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UPstream::msgType().
Referenced by mapDistribute::distribute(), mapDistribute::transform::operator()(), mapDistribute::reverseDistribute(), and mapDistribute::transformStart().
void transfer (mapDistribute & rhs)
Transfer the contents of the argument and annul the argument.
Definition at line 1114 of file mapDistribute.C.
References List< T >::transfer().
Referenced by IOmapDistribute::IOmapDistribute(), and mapDistribute::transformStart().
Foam::Xfer< Foam::mapDistribute > xfer ()
Transfer contents to the Xfer container.
Definition at line 1125 of file mapDistribute.C.
References mapDistribute::renumber(), and Foam::xferMove().
Referenced by minEqOp< labelPair >::operator()(), and mapDistribute::transformStart().
Foam::label renumber (const globalIndex & globalNumbering, const List< Map< label >> & compactMap, const label globalElement) static
Helper for construct from globalIndex. Renumbers element.
(in globalIndex numbering) into compact indices.
Definition at line 1132 of file mapDistribute.C.
References globalIndex::isLocal(), globalIndex::toLocal(), and globalIndex::whichProcID().
Referenced by mapDistribute::transformStart(), and mapDistribute::xfer().
void compact (const boolList & elemIsUsed, const int tag = UPstream::msgType())
Compact maps. Gets per field a bool whether it is used (locally)
and works out itself what this side and sender side can remove from maps.
Definition at line 1155 of file mapDistribute.C.
References UList< T >::begin(), forAll, Foam::max(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UPstream::parRun(), UIPstream::read(), List< T >::setSize(), List< T >::size(), List< T >::transfer(), UPstream::waitRequests(), and UOPstream::write().
Referenced by mapDistribute::transformStart().
void distribute (const Pstream::commsTypes commsType, const List< labelPair > & schedule, const label constructSize, const labelListList & subMap, const labelListList & constructMap, List< T > & field, const int tag = UPstream::msgType()) static
Distribute data. Note:schedule only used for Pstream::scheduled.
for now, all others just use send-to-all, receive-from-all.
Definition at line 36 of file mapDistributeTemplates.C.
References Foam::abort(), UList< T >::begin(), UList< T >::byteSize(), Foam::FatalError, FatalErrorInFunction, PstreamBuffers::finishedSends(), forAll, Foam::read(), List< T >::setSize(), List< T >::size(), List< T >::transfer(), and write().
Referenced by extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), PointEdgeWave< Type, TrackingData >::countPatchType(), mappedPatchBase::distribute(), mapDistribute::distribute(), mapDistributePolyMesh::distributeCellData(), mapDistributePolyMesh::distributeFaceData(), mapDistributeLagrangian::distributeLagrangianData(), mapDistributePolyMesh::distributePatchData(), mapDistributePolyMesh::distributePointData(), distributedTriSurfaceMesh::findNearest(), sampledPatchInternalField::interpolateField(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), mappedPatchFieldBase< Type >::mappedField(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), globalMeshData::mergePoints(), NamedEnum< Enum, nEnum >::names(), PatchTools::pointNormals(), mapDistribute::receive(), mappedPatchBase::reverseDistribute(), mapDistribute::reverseDistribute(), globalMeshData::syncData(), pointConstraints::syncUntransformedData(), thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField(), mapDistribute::transformStart(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), streamLine::write(), and wallBoundedStreamLine::write().
void distribute (const Pstream::commsTypes commsType, const List< labelPair > & schedule, const label constructSize, const labelListList & subMap, const labelListList & constructMap, List< T > & field, const CombineOp & cop, const T & nullValue, const int tag = UPstream::msgType()) static
Distribute data. If multiple processors writing to same.
position adds contributions using cop.
Definition at line 385 of file mapDistributeTemplates.C.
References Foam::abort(), UList< T >::begin(), Foam::FatalError, FatalErrorInFunction, PstreamBuffers::finishedSends(), forAll, Foam::read(), List< T >::setSize(), List< T >::size(), T, List< T >::transfer(), and write().
void distribute (DynamicList< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 879 of file mapDistributeTemplates.C.
References mapDistribute::distribute(), fld(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), and List< T >::size().
void distribute (List< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 897 of file mapDistributeTemplates.C.
References UPstream::blocking, UPstream::defaultCommsType, mapDistribute::distribute(), UPstream::nonBlocking, mapDistribute::reverseDistribute(), mapDistribute::schedule(), and UPstream::scheduled.
void distribute (const globalIndexAndTransform & git, List< T > & fld, const TransformOp & top, const int tag = UPstream::msgType()) const
Same but with transforms.
Definition at line 1072 of file mapDistributeTemplates.C.
References mapDistribute::distribute(), and mapDistribute::reverseDistribute().
void reverseDistribute (const label constructSize, List< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Reverse distribute data using default commsType.
Definition at line 953 of file mapDistributeTemplates.C.
References UPstream::blocking, UPstream::defaultCommsType, mapDistribute::distribute(), UPstream::nonBlocking, mapDistribute::schedule(), and UPstream::scheduled.
Referenced by PointEdgeWave< Type, TrackingData >::countPatchType(), mapDistribute::distribute(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::getField(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), sampledPatchInternalField::interpolateField(), mappedPatchFieldBase< Type >::mappedField(), globalMeshData::mergePoints(), NamedEnum< Enum, nEnum >::names(), minEqOp< labelPair >::operator()(), PatchTools::pointNormals(), mappedPatchBase::reverseDistribute(), mapDistribute::reverseDistribute(), globalMeshData::syncData(), pointConstraints::syncUntransformedData(), and mapDistribute::transformStart().
void reverseDistribute (const globalIndexAndTransform & git, const label constructSize, List< T > & fld, const TransformOp & top, const int tag = UPstream::msgType()) const
Same but with transforms.
Definition at line 1088 of file mapDistributeTemplates.C.
References mapDistribute::reverseDistribute().
void reverseDistribute (const label constructSize, const T & nullValue, List< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Reverse distribute data using default commsType.
Since constructSize might be larger than supplied size supply a nullValue
Definition at line 1009 of file mapDistributeTemplates.C.
References UPstream::blocking, UPstream::defaultCommsType, mapDistribute::distribute(), UPstream::nonBlocking, mapDistribute::schedule(), and UPstream::scheduled.
void reverseDistribute (const globalIndexAndTransform & git, const label constructSize, const T & nullValue, List< T > & fld, const TransformOp & top, const int tag = UPstream::msgType()) const
Same but with transforms.
Definition at line 1108 of file mapDistributeTemplates.C.
References mapDistribute::reverseDistribute().
void send (PstreamBuffers & pBufs, const List< T > & field) const
Do all sends using PstreamBuffers.
Definition at line 730 of file mapDistributeTemplates.C.
References PstreamBuffers::finishedSends(), UPstream::nProcs(), and List< T >::size().
Referenced by InteractionLists< ParticleType >::sendReferredData(), and mapDistribute::transformStart().
void receive (PstreamBuffers & pBufs, List< T > & field) const
Do all receives using PstreamBuffers.
Definition at line 752 of file mapDistributeTemplates.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, n, UPstream::nProcs(), List< T >::setSize(), List< T >::size(), and globalIndexAndTransform::transformPermutations().
Referenced by InteractionLists< ParticleType >::receiveReferredData(), and mapDistribute::transformStart().
void printLayout (Ostream & os) const
Debug: print layout. Can only be used on maps with sorted.
storage (local data first, then non-local data)
Definition at line 297 of file mapDistribute.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, forAllIter, Foam::identity(), globalIndex::isLocal(), Foam::labelMax, Foam::labelMin, globalIndex::localSize(), Foam::max(), Foam::min(), UPstream::myProcNo(), UPstream::nProcs(), Foam::renumber(), List< T >::setSize(), List< T >::size(), globalIndex::toLocal(), globalIndex::whichProcID(), and UPstream::worldComm.
Referenced by mapDistribute::mapDistribute(), and mapDistribute::transformStart().
void updateMesh (const mapPolyMesh &) inline
Correct for topo change.
Definition at line 670 of file mapDistribute.H.
References fld(), NotImplemented, mapDistribute::operator<<, mapDistribute::operator=(), and mapDistribute::operator>>.
void operator= (const mapDistribute & rhs)
Definition at line 1301 of file mapDistribute.C.
References Foam::abort(), IOstream::fatalCheck(), Foam::FatalError, FatalErrorInFunction, token::NL, Foam::operator<<(), and Foam::operator>>().
Referenced by IOmapDistribute::IOmapDistribute(), and mapDistribute::updateMesh().
Friends And Related Function Documentation
Istream& operator>> (Istream & , mapDistribute &) friend
Read dictionary from Istream.
Referenced by mapDistribute::updateMesh().
Ostream& operator<< (Ostream & , const mapDistribute &) friend
Write dictionary to Ostream.
Referenced by mapDistribute::updateMesh().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeTemplates.C