OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
meanVelocityForce Class Reference
Calculates and applies the force necessary to maintain the specified mean velocity.
Public Member Functions
TypeName ("meanVelocityForce")
Runtime type information.
meanVelocityForce (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from explicit source name and mesh.
virtual void correct (volVectorField &U)
Correct the pressure gradient.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
Add explicit contribution to momentum equation.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Add explicit contribution to compressible momentum equation.
virtual void constrain (fvMatrix< vector > &eqn, const label fieldI)
Set 1/A coefficient.
virtual bool read (const dictionary &dict)
Read source dictionary.
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
Runtime type information.
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~cellSetOption ()
Destructor.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const labelList & cells () const
Return const access to the cell set.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
Switch & active ()
Return access to the source active flag.
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldI)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldI)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldI)
virtual void correct (volScalarField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Protected Member Functions
virtual scalar magUbarAve (const volVectorField &U) const
Calculate and return the magnitude of the mean velocity.
void writeProps (const scalar gradP) const
Write the pressure gradient to file (for restarts etc)
void update (fvMatrix< vector > &eqn)
Correct driving force for a constant mass flow rate.
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Protected Attributes
vector Ubar_
Average velocity.
scalar gradP0_
Pressure gradient before correction.
scalar dGradP_
Change in pressure gradient.
vector flowDir_
Flow direction.
scalar relaxation_
Relaxation factor.
autoPtr< volScalarField > rAPtr_
Matrix 1/A coefficients field pointer.
Protected Attributes inherited from cellSetOption
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType { smPoints, smCellSet, smCellZone, smAll }
Enumeration for selection mode types.
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Static Public Attributes inherited from cellSetOption
static const NamedEnum< selectionModeType, 4 > selectionModeTypeNames_
Word list of selection mode type names.
Detailed Description
Calculates and applies the force necessary to maintain the specified mean velocity.
Note: Currently only handles kinematic pressure (incompressible solvers).
Source usage Example usage:
meanVelocityForceCoeffs
{
    selectionMode   all;                    // Apply force to all cells
    fieldNames      (U);                    // Name of velocity field
    Ubar            (10.0 0 0);             // Desired mean velocity
    relaxation      0.2;                    // Optional relaxation factor
}
Source files
meanVelocityForce.H
meanVelocityForce.C
Definition at line 70 of file meanVelocityForce.H.
Constructor & Destructor Documentation
meanVelocityForce (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from explicit source name and mesh.
Definition at line 81 of file meanVelocityForce.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), Foam::Info, dictionary::lookup(), meanVelocityForce::magUbarAve(), Foam::nl, dictionary::null, and propsDict().
Member Function Documentation
Foam::scalar magUbarAve (const volVectorField & U) const protected virtual
Calculate and return the magnitude of the mean velocity.
averaged over the selected cellSet
Reimplemented in patchMeanVelocityForce.
Definition at line 126 of file meanVelocityForce.C.
References forAll, and Foam::reduce().
Referenced by meanVelocityForce::meanVelocityForce().
void writeProps (const scalar gradP) const protected
Write the pressure gradient to file (for restarts etc)
Definition at line 53 of file meanVelocityForce.C.
References dictionary::add(), IOobject::NO_READ, IOobject::NO_WRITE, and propsDict().
void update (fvMatrix< vector > & eqn) protected
Correct driving force for a constant mass flow rate.
TypeName ("meanVelocityForce")
Runtime type information.
void correct (volVectorField & U) virtual
Correct the pressure gradient.
Reimplemented from option.
Definition at line 148 of file meanVelocityForce.C.
References meanVelocityForce::addSup(), Foam::endl(), forAll, Foam::Info, Foam::mag(), rAU(), and Foam::reduce().
void addSup (fvMatrix< vector > & eqn, const label fieldI) virtual
Add explicit contribution to momentum equation.
Reimplemented from option.
Definition at line 191 of file meanVelocityForce.C.
References fvMatrix< Type >::dimensions(), Foam::dimVolume, IOobject::NO_READ, IOobject::NO_WRITE, Foam::fvc::Su(), and Vector< scalar >::zero.
Referenced by meanVelocityForce::correct().
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldI) virtual
Add explicit contribution to compressible momentum equation.
Reimplemented from option.
Definition at line 219 of file meanVelocityForce.C.
References meanVelocityForce::constrain().
void constrain (fvMatrix< vector > & eqn, const label fieldI) virtual
Set 1/A coefficient.
Reimplemented from option.
Definition at line 230 of file meanVelocityForce.C.
References fvMatrix< Type >::A(), IOobject::NO_READ, and IOobject::NO_WRITE.
Referenced by meanVelocityForce::addSup().
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented from cellSetOption.
Definition at line 30 of file meanVelocityForceIO.C.
References NotImplemented.
Member Data Documentation
vector Ubar_ protected
Average velocity.
Definition at line 79 of file meanVelocityForce.H.
scalar gradP0_ protected
Pressure gradient before correction.
Definition at line 82 of file meanVelocityForce.H.
scalar dGradP_ protected
Change in pressure gradient.
Definition at line 85 of file meanVelocityForce.H.
vector flowDir_ protected
Flow direction.
Definition at line 88 of file meanVelocityForce.H.
scalar relaxation_ protected
Relaxation factor.
Definition at line 91 of file meanVelocityForce.H.
autoPtr<volScalarField> rAPtr_ protected
Matrix 1/A coefficients field pointer.
Definition at line 94 of file meanVelocityForce.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/meanVelocityForce/meanVelocityForce.H
src/fvOptions/sources/derived/meanVelocityForce/meanVelocityForce.C
src/fvOptions/sources/derived/meanVelocityForce/meanVelocityForceIO.C