OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NASedgeFormat Class Reference
Nastran edge reader.
Public Member Functions
NASedgeFormat (const fileName &)
Construct from file name.
virtual ~NASedgeFormat ()
Destructor.
virtual bool read (const fileName &)
Read from a file.
Public Member Functions inherited from edgeMesh
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const pointField &, const edgeList &)
Construct from components.
edgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges).
edgeMesh (const edgeMesh &)
Construct as copy.
edgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
edgeMesh (Istream &)
Construct from Istream.
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< edgeMesh > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void clear ()
Clear all storage.
virtual void reset (const Xfer< pointField > &points, const Xfer< edgeList > &edges)
Reset primitive data (points, edges)
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
void mergeEdges ()
Merge similar edges.
virtual void writeStats (Ostream &) const
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void operator= (const edgeMesh &)
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Public Member Functions inherited from NASCore
NASCore ()
Construct null.
Static Public Member Functions
static autoPtr< edgeMesh > New (const fileName &name)
Read file and return edge mesh.
Static Public Member Functions inherited from edgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const edgeMesh &)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Static Public Member Functions inherited from NASCore
static scalar parseNASCoord (const string &)
Do weird things to extract number.
Additional Inherited Members
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
Nastran edge reader.
Source files
NASedgeFormat.H
NASedgeFormat.C
Definition at line 51 of file NASedgeFormat.H.
Constructor & Destructor Documentation
NASedgeFormat (const fileName & filename)
Construct from file name.
Definition at line 34 of file NASedgeFormat.C.
References Foam::read(), and NASedgeFormat::read().
virtual ~NASedgeFormat () inline virtual
Destructor.
Definition at line 85 of file NASedgeFormat.H.
References NASedgeFormat::read().
Member Function Documentation
static autoPtr<edgeMesh> New (const fileName & name) inline static
Read file and return edge mesh.
Definition at line 75 of file NASedgeFormat.H.
bool read (const fileName & filename) virtual
Read from a file.
Reimplemented from edgeMesh.
Definition at line 45 of file NASedgeFormat.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), clear(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clearStorage(), PackedList< nBits >::count(), Foam::constant::electromagnetic::e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, PackedList< nBits >::get(), ISstream::getLine(), IOstream::good(), IOstream::lineNumber(), IFstream::name(), Foam::nl, Foam::parseNASCoord(), points, Foam::readLabel(), PackedBoolList::set(), List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), List< T >::size(), FixedList< T, Size >::transfer(), x, and y.
Referenced by NASedgeFormat::NASedgeFormat(), and NASedgeFormat::~NASedgeFormat().
The documentation for this class was generated from the following files:
src/edgeMesh/edgeMeshFormats/nas/NASedgeFormat.H
src/edgeMesh/edgeMeshFormats/nas/NASedgeFormat.C