OpenFOAM: MeshedSurface< Face > Class Template Reference
MeshedSurface< Face > Class Template Reference
A surface geometry mesh with zone information, not to be confused with the similarly named surfaceMesh, which actually refers to the cell faces of a volume mesh.
Public Types
typedef Face FaceType
Face type used.
Public Types inherited from PrimitivePatch< Face,::Foam::List, pointField, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef ::Foam::List< Face > FaceListType
typedef pointField PointFieldType
Public Types inherited from List< Face >
typedef SubList< Face > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
ClassName ("MeshedSurface")
Runtime type information.
MeshedSurface ()
Construct null.
MeshedSurface (const Xfer< pointField > &, const Xfer< List< Face >> &, const Xfer< surfZoneList > &)
Construct by transferring components (points, faces, zones).
MeshedSurface (const Xfer< pointField > &, const Xfer< List< Face >> &, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Construct by transferring components (points, faces).
MeshedSurface (const MeshedSurface &)
Construct as copy.
MeshedSurface (const UnsortedMeshedSurface< Face > &)
Construct from a UnsortedMeshedSurface.
MeshedSurface (const polyBoundaryMesh &, const bool globalPoints=false)
Construct from a boundary mesh with local points/faces.
MeshedSurface (const surfMesh &)
Construct from a surfMesh.
MeshedSurface (const Xfer< UnsortedMeshedSurface< Face >> &)
Construct by transferring the contents from a UnsortedMeshedSurface.
MeshedSurface (const Xfer< MeshedSurface< Face >> &)
Construct by transferring the contents from a MeshedSurface.
MeshedSurface (const fileName &)
Construct from file name (uses extension to determine type)
MeshedSurface (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
MeshedSurface (const Time &, const word &surfName="")
Construct from database.
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
Destructor.
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< Face > &surf),(name, surf))
label size () const
The surface size is the number of faces.
const List< Face > & faces () const
Return const access to the faces.
const List< surfZone > & surfZones () const
Const access to the surface zones.
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
Add surface zones.
virtual void removeZones ()
Remove surface zones.
virtual void clear ()
Clear all storage.
virtual void movePoints (const pointField &)
Move points.
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
virtual void reset (const Xfer< pointField > &points, const Xfer< List< Face >> &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void reset (const Xfer< List< point >> &points, const Xfer< List< Face >> &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void cleanup (const bool verbose)
Remove invalid faces.
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label triangulate ()
Triangulate in-place, returning the number of triangles added.
virtual label triangulate (List< label > &faceMap)
Triangulate in-place, returning the number of triangles added.
MeshedSurface subsetMesh (const labelHashSet &include, labelList &pointMap, labelList &faceMap) const
Return new surface.
MeshedSurface subsetMesh (const labelHashSet &include) const
Return new surface.
void transfer (MeshedSurface< Face > &)
Transfer the contents of the argument and annul the argument.
void transfer (UnsortedMeshedSurface< Face > &)
Transfer the contents of the argument and annul the argument.
Xfer< MeshedSurface< Face > > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &)
Read from file. Chooses reader based on detected extension.
void writeStats (Ostream &os) const
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void write (const Time &, const word &surfName="") const
Write to database.
void operator= (const MeshedSurface< Face > &)
operator MeshedSurfaceProxy< Face > () const
Conversion operator to MeshedSurfaceProxy.
template<class Face>
MeshedSurface (const MeshedSurface< Face > &surf)
template<>
bool isTri ()
Specialization for holding triangulated information.
template<>
label triangulate ()
Specialization for holding triangulated information.
template<>
label triangulate (List< label > &faceMap)
Specialization for holding triangulated information.
Public Member Functions inherited from PrimitivePatch< Face,::Foam::List, pointField, point >
PrimitivePatch (const ::Foam::List< Face > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (const Xfer< ::Foam::List< Face >> &faces, const Xfer< List< point >> &points)
Construct from components.
PrimitivePatch (::Foam::List< Face > &faces, Field< point > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face,::Foam::List, pointField, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceNormals () const
Return face normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face,::Foam::List, pointField, point > &)
Assignment.
Public Member Functions inherited from List< Face >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Face &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Face > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< Face >> &)
Construct by transferring the parameter contents.
List (List< Face > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Face > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Face, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Face > &)
Construct as copy of PtrList<T>
List (const SLList< Face > &)
Construct as copy of SLList<T>
List (const UIndirectList< Face > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Face > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< Face >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< Face > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Face &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Face &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Face &)
Append an element at the end of the list.
void append (const UList< Face > &)
Append a List at the end of this list.
void append (const UIndirectList< Face > &)
Append a UIndirectList at the end of this list.
void transfer (List< Face > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Face, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Face > &)
Transfer the contents of the argument List into this list.
Xfer< List< Face > > xfer ()
Transfer contents to the Xfer container.
Face & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Face > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Face > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< Face > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Face > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< Face > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Face > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< Face >)
Assignment to an initializer list.
void operator= (const Face &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()
Construct null.
virtual ~surfaceFormatsCore ()
Destructor.
Static Public Member Functions
static bool isTri ()
Face storage only handles triangulated faces.
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< MeshedSurface > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< MeshedSurface > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const MeshedSurface< Face > &)
Write to file.
Static Public Member Functions inherited from List< Face >
static const List< Face > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
static fileName localMeshFileName (const word &surfName="")
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName="")
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName="")
Find mesh file with surfName.
Protected Member Functions
void transcribe (MeshedSurface< face > &)
Transfer points/zones and transcribe face -> triFace.
void checkZones ()
Basic sanity check on zones.
pointField & storedPoints ()
Non-const access to global points.
List< Face > & storedFaces ()
Non-const access to the faces.
surfZoneList & storedZones ()
Non-const access to the zones.
void sortFacesAndStore (const Xfer< List< Face >> &unsortedFaces, const Xfer< List< label >> &zoneIds, const bool sorted)
Sort faces by zones and store sorted faces.
virtual void remapFaces (const labelUList &faceMap)
Set new zones from faceMap.
template<>
void transcribe (MeshedSurface< face > &surf)
template<>
void transcribe (MeshedSurface< face > &surf)
Protected Member Functions inherited from List< Face >
void size (const label)
Override size to be inconsistent with allocated storage.
Friends
template<class Face2 >
class MeshedSurface
template<class Face2 >
class UnsortedMeshedSurface
class surfMesh
Additional Inherited Members
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Static Protected Member Functions inherited from surfaceFormatsCore
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a list with a single entry,.
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
template<class Face>
class Foam::MeshedSurface< Face >
A surface geometry mesh with zone information, not to be confused with the similarly named surfaceMesh, which actually refers to the cell faces of a volume mesh.
A MeshedSurface can have zero or more surface zones (roughly equivalent to faceZones for a polyMesh). If surface zones are defined, they must be contiguous and cover all of the faces.
The MeshedSurface is intended for surfaces from a variety of sources.
A set of points and faces without any surface zone information.
A set of points and faces with randomly ordered zone information. This could arise, for example, from reading external file formats such as STL, etc.
Source files
MeshedSurface.H
MeshedSurface.C
Definition at line 72 of file MeshedSurface.H.
Member Typedef Documentation
typedef Face FaceType
Face type used.
Definition at line 161 of file MeshedSurface.H.
Constructor & Destructor Documentation
MeshedSurface ()
Construct null.
Definition at line 158 of file MeshedSurface.C.
Referenced by MeshedSurface< Face >::MeshedSurface(), and MeshedSurface< Face >::subsetMesh().
MeshedSurface (const Xfer< pointField > & pointLst, const Xfer< List< Face >> & faceLst, const Xfer< surfZoneList > & zoneLst)
Construct by transferring components (points, faces, zones).
Definition at line 166 of file MeshedSurface.C.
References MeshedSurface< Face >::MeshedSurface(), and MeshedSurface< Face >::reset().
MeshedSurface (const Xfer< pointField > & pointLst, const Xfer< List< Face >> & faceLst, const labelUList & zoneSizes = labelUList(), const UList< word > & zoneNames = UList<word>())
Construct by transferring components (points, faces).
Use zone information if available
Definition at line 181 of file MeshedSurface.C.
References MeshedSurface< Face >::addZones(), MeshedSurface< Face >::MeshedSurface(), MeshedSurface< Face >::reset(), and UList< T >::size().
MeshedSurface (const MeshedSurface< Face > &)
Construct as copy.
MeshedSurface (const UnsortedMeshedSurface< Face > & surf)
Construct from a UnsortedMeshedSurface.
Definition at line 219 of file MeshedSurface.C.
References Foam::faceMap(), MeshedSurface< Face >::faces(), forAll, List< T >::size(), UnsortedMeshedSurface< Face >::sortedZones(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedZones(), and List< T >::transfer().
MeshedSurface (const polyBoundaryMesh & bMesh, const bool globalPoints = false)
Construct from a boundary mesh with local points/faces.
Definition at line 259 of file MeshedSurface.C.
References polyMesh::faces(), forAll, mesh, polyBoundaryMesh::mesh(), MeshedSurface< Face >::MeshedSurface(), patchIdentifier::name(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), p, patchi, polyMesh::points(), UPtrList< T >::size(), MeshedSurface< Face >::transcribe(), Foam::xferCopy(), and Foam::xferMove().
MeshedSurface (const surfMesh & mesh)
Construct from a surfMesh.
Definition at line 241 of file MeshedSurface.C.
References surfMesh::faces(), MeshedSurface< Face >::MeshedSurface(), surfMesh::points(), surfMesh::surfZones(), MeshedSurface< Face >::transcribe(), and Foam::xferCopy().
MeshedSurface (const Xfer< UnsortedMeshedSurface< Face >> & surf)
Construct by transferring the contents from a UnsortedMeshedSurface.
Definition at line 391 of file MeshedSurface.C.
References MeshedSurface< Face >::MeshedSurface(), and MeshedSurface< Face >::transfer().
MeshedSurface (const Xfer< MeshedSurface< Face >> & surf)
Construct by transferring the contents from a MeshedSurface.
Definition at line 403 of file MeshedSurface.C.
References MeshedSurface< Face >::transfer().
MeshedSurface (const fileName & name)
Construct from file name (uses extension to determine type)
Definition at line 346 of file MeshedSurface.C.
References MeshedSurface< Face >::MeshedSurface(), and MeshedSurface< Face >::read().
MeshedSurface (const fileName & name, const word & ext)
Construct from file name (uses extension to determine type)
Definition at line 334 of file MeshedSurface.C.
References MeshedSurface< Face >::read().
MeshedSurface (const Time & t, const word & surfName = "")
Construct from database.
Definition at line 356 of file MeshedSurface.C.
References mesh, MeshedSurface< Face >::MeshedSurface(), IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, surfMesh::storedFaces(), surfMesh::storedPoints(), surfMesh::storedZones(), Time::timeName(), MeshedSurface< Face >::transcribe(), and Foam::xferMove().
~MeshedSurface () virtual
Destructor.
Definition at line 417 of file MeshedSurface.C.
References MeshedSurface< Face >::remapFaces().
MeshedSurface (const MeshedSurface< Face > & surf)
Definition at line 208 of file MeshedSurface.C.
References MeshedSurface< Face >::MeshedSurface().
Member Function Documentation
void transcribe (MeshedSurface< face > &) protected
Transfer points/zones and transcribe face -> triFace.
Referenced by MeshedSurface< Face >::MeshedSurface(), and OFSsurfaceFormat< Face >::read().
void checkZones () protected
Basic sanity check on zones.
Definition at line 31 of file MeshedSurfaceZones.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UList< T >::last(), List< T >::size(), MeshedSurface< Face >::sortFacesAndStore(), and WarningInFunction.
pointField& storedPoints () inline protected
Non-const access to global points.
Definition at line 127 of file MeshedSurface.H.
Referenced by MeshedSurface< Face >::clear(), MeshedSurface< Face >::movePoints(), UnsortedMeshedSurface< Face >::operator=(), MeshedSurface< Face >::operator=(), MeshedSurface< Face >::reset(), MeshedSurface< Face >::scalePoints(), MeshedSurface< Face >::stitchFaces(), MeshedSurface< Face >::transcribe(), surfMesh::transfer(), UnsortedMeshedSurface< Face >::transfer(), and MeshedSurface< Face >::transfer().
List<Face>& storedFaces () inline protected
Non-const access to the faces.
Definition at line 133 of file MeshedSurface.H.
Referenced by MeshedSurface< Face >::checkFaces(), MeshedSurface< Face >::clear(), MeshedSurface< Face >::MeshedSurface(), UnsortedMeshedSurface< Face >::operator=(), MeshedSurface< Face >::operator=(), MeshedSurface< Face >::reset(), UnsortedMeshedSurface< Face >::setSize(), MeshedSurface< Face >::stitchFaces(), MeshedSurface< Face >::transcribe(), surfMesh::transfer(), UnsortedMeshedSurface< Face >::transfer(), MeshedSurface< Face >::transfer(), and MeshedSurface< Face >::triangulate().
surfZoneList& storedZones () inline protected
Non-const access to the zones.
Definition at line 139 of file MeshedSurface.H.
Referenced by MeshedSurface< Face >::clear(), MeshedSurface< Face >::MeshedSurface(), MeshedSurface< Face >::operator=(), MeshedSurface< Face >::remapFaces(), MeshedSurface< Face >::reset(), MeshedSurface< Face >::transcribe(), surfMesh::transfer(), and MeshedSurface< Face >::transfer().
void sortFacesAndStore (const Xfer< List< Face >> & unsortedFaces, const Xfer< List< label >> & zoneIds, const bool sorted) protected
Sort faces by zones and store sorted faces.
Definition at line 66 of file MeshedSurfaceZones.C.
References MeshedSurface< Face >::addZones(), List< T >::clear(), Foam::faceMap(), forAll, List< T >::size(), and Foam::sortedOrder().
Referenced by MeshedSurface< Face >::checkZones(), and MeshedSurface< Foam::face >::storedZones().
void remapFaces (const labelUList & faceMap) protected virtual
Set new zones from faceMap.
Reimplemented in cuttingPlane, and UnsortedMeshedSurface< Face >.
Definition at line 425 of file MeshedSurface.C.
References forAll, Foam::notNull(), List< T >::size(), surfZone::size(), UList< T >::size(), surfZone::start(), and MeshedSurface< Face >::storedZones().
Referenced by MeshedSurface< Face >::checkFaces(), MeshedSurface< Face >::stitchFaces(), MeshedSurface< Foam::face >::storedZones(), MeshedSurface< Face >::triangulate(), and MeshedSurface< Face >::~MeshedSurface().
ClassName ("MeshedSurface< Face >")
Runtime type information.
bool isTri () inline static
Face storage only handles triangulated faces.
Definition at line 41 of file MeshedSurface.C.
bool canRead (const fileName & name, const bool verbose = false) static
Can we read this file format?
Definition at line 99 of file MeshedSurface.C.
References fileName::ext(), fileName::lessExt(), and MeshedSurface< Face >::write().
Referenced by MeshedSurface< Face >::canWriteType().
bool canReadType (const word & ext, const bool verbose = false) static
Can we read this file format?
Definition at line 65 of file MeshedSurface.C.
References MeshedSurface< Face >::canWriteType().
Referenced by MeshedSurface< Face >::writeTypes().
bool canWriteType (const word & ext, const bool verbose = false) static
Can we write this file format?
Definition at line 82 of file MeshedSurface.C.
References MeshedSurface< Face >::canRead().
Referenced by MeshedSurface< Face >::canReadType().
Foam::wordHashSet readTypes () static
Definition at line 48 of file MeshedSurface.C.
Foam::wordHashSet writeTypes () static
Definition at line 55 of file MeshedSurface.C.
References MeshedSurface< Face >::canReadType().
declareRunTimeSelectionTable (autoPtr , MeshedSurface< Face > , fileExtension , (const fileName &name) , (name))
Foam::autoPtr< Foam::MeshedSurface< Face > > New (const fileName & name, const word & ext) static
Select constructed from filename (explicit extension)
Definition at line 33 of file MeshedSurfaceNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::found(), InfoInFunction, Foam::name(), Foam::New(), and Foam::nl.
Referenced by MeshedSurface< Face >::read().
Foam::autoPtr< Foam::MeshedSurface< Face > > New (const fileName & name) static
Select constructed from filename (implicit extension)
Definition at line 72 of file MeshedSurfaceNew.C.
References fileName::ext(), fileName::lessExt(), and Foam::New().
declareMemberFunctionSelectionTable (void , UnsortedMeshedSurface< Face > , write , fileExtension , (const fileName &name, const MeshedSurface< Face > &surf) , (name, surf))
void write (const fileName & name, const MeshedSurface< Face > & surf) static
Write to file.
Definition at line 115 of file MeshedSurface.C.
References Foam::endl(), Foam::exit(), fileName::ext(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::found(), InfoInFunction, Foam::name(), Foam::nl, and write().
Referenced by MeshedSurface< Face >::canRead(), MeshedSurface< Face >::read(), and MeshedSurface< Foam::face >::write().
label size () const inline
The surface size is the number of faces.
Definition at line 295 of file MeshedSurface.H.
Referenced by UnsortedMeshedSurface< Face >::size(), and GTSsurfaceFormat< Face >::write().
const List<Face>& faces () const inline
Return const access to the faces.
Definition at line 301 of file MeshedSurface.H.
Referenced by MeshedSurface< Foam::face >::faces(), MeshedSurface< Face >::MeshedSurface(), UnsortedMeshedSurface< Face >::operator=(), MeshedSurface< Face >::operator=(), GTSsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeAscii(), and STLsurfaceFormat< Face >::writeBinary().
const List<surfZone>& surfZones () const inline
Const access to the surface zones.
If zones are defined, they must be contiguous and cover the entire surface
Definition at line 309 of file MeshedSurface.H.
Referenced by MeshedSurface< Foam::face >::faces(), MeshedSurface< Face >::operator=(), MeshedSurface< Face >::subsetMesh(), UnsortedMeshedSurface< Face >::transfer(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), and GTSsurfaceFormat< Face >::write().
void addZones (const UList< surfZone > & srfZones, const bool cullEmpty = false) virtual
Add surface zones.
Definition at line 105 of file MeshedSurfaceZones.C.
References forAll, List< T >::setSize(), and List< T >::size().
Referenced by MeshedSurface< Face >::addZones(), MeshedSurface< Foam::face >::faces(), MeshedSurface< Face >::MeshedSurface(), and MeshedSurface< Face >::sortFacesAndStore().
void addZones (const labelUList & sizes, const UList< word > & names, const bool cullEmpty = false) virtual
Add surface zones.
Definition at line 128 of file MeshedSurfaceZones.C.
References MeshedSurface< Face >::addZones(), forAll, List< T >::setSize(), and UList< T >::size().
void addZones (const labelUList & sizes, const bool cullEmpty = false) virtual
Add surface zones.
Definition at line 160 of file MeshedSurfaceZones.C.
References forAll, Foam::name(), List< T >::setSize(), and UList< T >::size().
void removeZones () virtual
Remove surface zones.
Definition at line 190 of file MeshedSurfaceZones.C.
Referenced by MeshedSurface< Foam::face >::faces().
void clear () virtual
Clear all storage.
Reimplemented in UnsortedMeshedSurface< Face >.
Definition at line 474 of file MeshedSurface.C.
References List< T >::clear(), PrimitivePatch< Face,::Foam::List, pointField, point >::clearOut(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), and MeshedSurface< Face >::storedZones().
Referenced by UnsortedMeshedSurface< Face >::clear(), MeshedSurface< Foam::face >::faces(), MeshedSurface< Face >::operator=(), OFSsurfaceFormat< Face >::read(), MeshedSurface< Face >::read(), MeshedSurface< Face >::transcribe(), UnsortedMeshedSurface< Face >::transfer(), and MeshedSurface< Face >::transfer().
void movePoints (const pointField & newPoints) virtual
Move points.
Definition at line 485 of file MeshedSurface.C.
References PrimitivePatch< Face,::Foam::List, pointField, point >::movePoints(), and MeshedSurface< Face >::storedPoints().
Referenced by MeshedSurface< Foam::face >::faces().
void scalePoints (const scalar scaleFactor) virtual
Scale points. A non-positive factor is ignored.
Definition at line 496 of file MeshedSurface.C.
References PrimitivePatch< Face,::Foam::List, pointField, point >::movePoints(), PrimitivePatch< Face,::Foam::List, pointField, point >::points(), MeshedSurface< Face >::reset(), and MeshedSurface< Face >::storedPoints().
Referenced by MeshedSurface< Foam::face >::faces().
void reset (const Xfer< pointField > & points, const Xfer< List< Face >> & faces, const Xfer< surfZoneList > & zones) virtual
Reset primitive data (points, faces and zones)
Note, optimized to avoid overwriting data (with Xfer::null)
Definition at line 513 of file MeshedSurface.C.
References PrimitivePatch< Face,::Foam::List, pointField, point >::clearOut(), Foam::notNull(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), MeshedSurface< Face >::storedZones(), and List< T >::transfer().
Referenced by MeshedSurface< Foam::face >::faces(), MeshedSurface< Face >::MeshedSurface(), OFSsurfaceFormat< Face >::read(), UnsortedMeshedSurface< Face >::reset(), MeshedSurface< Face >::scalePoints(), UnsortedMeshedSurface< Face >::transfer(), and MeshedSurface< Face >::transfer().
void reset (const Xfer< List< point >> & points, const Xfer< List< Face >> & faces, const Xfer< surfZoneList > & zones) virtual
Reset primitive data (points, faces and zones)
Note, optimized to avoid overwriting data (with Xfer::null)
Definition at line 542 of file MeshedSurface.C.
References PrimitivePatch< Face,::Foam::List, pointField, point >::clearOut(), Foam::notNull(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), MeshedSurface< Face >::storedZones(), and List< T >::transfer().
void cleanup (const bool verbose) virtual
Remove invalid faces.
Definition at line 571 of file MeshedSurface.C.
References MeshedSurface< Face >::checkFaces(), PrimitivePatch< Face,::Foam::List, pointField, point >::checkTopology(), and MeshedSurface< Face >::stitchFaces().
Referenced by MeshedSurface< Foam::face >::faces().
bool stitchFaces (const scalar tol = SMALL, const bool verbose = false) virtual
Definition at line 583 of file MeshedSurface.C.
References MeshedSurface< Face >::checkFaces(), PrimitivePatch< Face,::Foam::List, pointField, point >::clearOut(), Foam::endl(), f(), Foam::faceMap(), forAll, InfoInFunction, Foam::mergePoints(), Foam::Pout, MeshedSurface< Face >::remapFaces(), List< T >::setSize(), List< T >::size(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), and List< T >::transfer().
Referenced by MeshedSurface< Face >::cleanup(), and MeshedSurface< Foam::face >::faces().
bool checkFaces (const bool verbose = false) virtual
Definition at line 665 of file MeshedSurface.C.
References PrimitivePatch< Face,::Foam::List, pointField, point >::clearOut(), Foam::endl(), Foam::exit(), f(), PrimitivePatch< Face,::Foam::List, pointField, point >::faceFaces(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, PrimitivePatch< Face,::Foam::List, pointField, point >::points(), MeshedSurface< Face >::remapFaces(), List< T >::setSize(), List< T >::size(), MeshedSurface< Face >::storedFaces(), and WarningInFunction.
Referenced by MeshedSurface< Face >::cleanup(), MeshedSurface< Foam::face >::faces(), and MeshedSurface< Face >::stitchFaces().
Foam::label triangulate () virtual
Triangulate in-place, returning the number of triangles added.
Definition at line 817 of file MeshedSurface.C.
Referenced by MeshedSurface< Foam::face >::faces(), and MeshedSurface< Face >::transcribe().
Foam::label triangulate (List< label > & faceMap) virtual
Triangulate in-place, returning the number of triangles added.
and setting a map of original face Ids. The faceMap is zero-sized when no triangulation was done.
Definition at line 828 of file MeshedSurface.C.
References List< T >::clear(), PrimitivePatch< Face,::Foam::List, pointField, point >::clearOut(), UList< T >::empty(), f(), Foam::faceMap(), UList< T >::fcIndex(), forAll, n, Foam::notNull(), PrimitivePatch< Face,::Foam::List, pointField, point >::points(), MeshedSurface< Face >::remapFaces(), List< T >::setSize(), List< T >::size(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::subsetMesh(), List< T >::transfer(), face::triangles(), and triFace().
Foam::MeshedSurface< Face > subsetMesh (const labelHashSet & include, labelList & pointMap, labelList & faceMap) const
Return new surface.
Returns return pointMap, faceMap from subsetMeshMap
Definition at line 934 of file MeshedSurface.C.
References f(), forAll, PrimitivePatch< Face,::Foam::List, pointField, point >::localFaces(), PrimitivePatch< Face,::Foam::List, pointField, point >::localPoints(), MeshedSurface< Face >::MeshedSurface(), List< T >::size(), surfZone::size(), surfZone::start(), PatchTools::subsetMap(), MeshedSurface< Face >::surfZones(), and Foam::xferMove().
Referenced by MeshedSurface< Foam::face >::faces(), MeshedSurface< Face >::subsetMesh(), and MeshedSurface< Face >::triangulate().
Foam::MeshedSurface< Face > subsetMesh (const labelHashSet & include) const
Return new surface.
Definition at line 1021 of file MeshedSurface.C.
References Foam::faceMap(), MeshedSurface< Face >::subsetMesh(), and MeshedSurface< Face >::transfer().
void transfer (MeshedSurface< Face > & surf)
Transfer the contents of the argument and annul the argument.
Definition at line 1033 of file MeshedSurface.C.
References MeshedSurface< Face >::reset(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), MeshedSurface< Face >::storedZones(), and Foam::xferMove().
Referenced by MeshedSurface< Foam::face >::faces(), MeshedSurface< Face >::MeshedSurface(), MeshedSurface< Face >::read(), and MeshedSurface< Face >::subsetMesh().
void transfer (UnsortedMeshedSurface< Face > & surf)
Transfer the contents of the argument and annul the argument.
Definition at line 1048 of file MeshedSurface.C.
References List< T >::clear(), UnsortedMeshedSurface< Face >::clear(), MeshedSurface< Face >::clear(), Foam::faceMap(), forAll, MeshedSurface< Face >::reset(), List< T >::size(), UnsortedMeshedSurface< Face >::sortedZones(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), and Foam::xferMove().
Foam::Xfer< Foam::MeshedSurface< Face > > xfer ()
Transfer contents to the Xfer container.
Definition at line 1090 of file MeshedSurface.C.
References Foam::xferMove().
Referenced by MeshedSurface< Foam::face >::faces().
bool read (const fileName & name, const word & ext)
Read from file. Chooses reader based on explicit extension.
Definition at line 1116 of file MeshedSurface.C.
References MeshedSurface< Face >::clear(), MeshedSurface< Face >::New(), MeshedSurface< Face >::transfer(), and MeshedSurface< Face >::write().
Referenced by MeshedSurface< Foam::face >::faces(), MeshedSurface< Face >::MeshedSurface(), and MeshedSurface< Face >::read().
bool read (const fileName & name) virtual
Read from file. Chooses reader based on detected extension.
Reimplemented in UnsortedMeshedSurface< Face >, STLsurfaceFormat< Face >, OFSsurfaceFormat< Face >, STARCDsurfaceFormat< Face >, TRIsurfaceFormat< Face >, AC3DsurfaceFormat< Face >, OFFsurfaceFormat< Face >, VTKsurfaceFormat< Face >, NASsurfaceFormat< Face >, GTSsurfaceFormat< Face >, and OBJsurfaceFormat< Face >.
Definition at line 1098 of file MeshedSurface.C.
References fileName::ext(), fileName::lessExt(), and MeshedSurface< Face >::read().
void writeStats (Ostream & os) const
Definition at line 33 of file MeshedSurfaceIO.C.
References Foam::endl(), forAll, n, Foam::nl, and points.
Referenced by MeshedSurface< Foam::face >::faces().
virtual void write (const fileName & name) const inline virtual
Generic write routine. Chooses writer based on extension.
Reimplemented in UnsortedMeshedSurface< Face >, STLsurfaceFormat< Face >, OFSsurfaceFormat< Face >, STARCDsurfaceFormat< Face >, TRIsurfaceFormat< Face >, AC3DsurfaceFormat< Face >, OFFsurfaceFormat< Face >, VTKsurfaceFormat< Face >, GTSsurfaceFormat< Face >, OBJsurfaceFormat< Face >, SMESHsurfaceFormat< Face >, WRLsurfaceFormat< Face >, and X3DsurfaceFormat< Face >.
Definition at line 431 of file MeshedSurface.H.
void write (const Time & t, const word & surfName = "") const
Write to database.
Definition at line 1131 of file MeshedSurface.C.
References MeshedSurfaceProxy< Face >::write().
void operator= (const MeshedSurface< Face > &)
Definition at line 1143 of file MeshedSurface.C.
References MeshedSurface< Face >::clear(), MeshedSurface< Face >::faces(), PrimitivePatch< Face,::Foam::List, pointField, point >::points(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), MeshedSurface< Face >::storedZones(), and MeshedSurface< Face >::surfZones().
Referenced by MeshedSurface< Foam::face >::write().
operator MeshedSurfaceProxy< Face > () const
Conversion operator to MeshedSurfaceProxy.
bool isTri () inline
Specialization for holding triangulated information.
Definition at line 453 of file MeshedSurface.H.
label triangulate () inline
Specialization for holding triangulated information.
Definition at line 461 of file MeshedSurface.H.
label triangulate (List< label > & faceMap) inline
Specialization for holding triangulated information.
Definition at line 469 of file MeshedSurface.H.
References List< T >::clear(), and Foam::notNull().
void transcribe (MeshedSurface< face > & surf) protected
Definition at line 35 of file MeshedSurfaceCore.C.
References MeshedSurface< Face >::clear(), forAll, List< T >::size(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), MeshedSurface< Face >::storedZones(), MeshedSurface< Face >::triangulate(), and triFace().
void transcribe (MeshedSurface< face > & surf) protected
Definition at line 60 of file MeshedSurfaceCore.C.
Friends And Related Function Documentation
friend class MeshedSurface friend
Definition at line 87 of file MeshedSurface.H.
friend class UnsortedMeshedSurface friend
Definition at line 88 of file MeshedSurface.H.
friend class surfMesh friend
Definition at line 89 of file MeshedSurface.H.
The documentation for this class was generated from the following files:
src/surfMesh/MeshedSurface/MeshedSurface.H
src/surfMesh/MeshedSurface/MeshedSurface.C
src/surfMesh/MeshedSurface/MeshedSurfaceIO.C
src/surfMesh/MeshedSurface/MeshedSurfaceNew.C
src/surfMesh/MeshedSurface/MeshedSurfaceZones.C