OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Moment< Type > Class Template Reference
Moment lagrangian averaging procedure.
Public Types
typedef AveragingMethod< Type >::TypeGrad TypeGrad
Public typedefs.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from FieldField< Field, Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from PtrList< Field< Type > >
typedef Field< Type > value_type
Type of values the PtrList contains.
typedef Field< Type > & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const Field< Type > & const_reference
Type that can be used for storing into constant PtrList::value_type.
Public Member Functions
TypeName ("moment")
Runtime type information.
Moment (const IOobject &io, const dictionary &dict, const fvMesh &mesh)
Constructors.
Moment (const Moment< Type > &am)
Construct a copy.
virtual autoPtr< AveragingMethod< Type > > clone () const
Construct and return a clone.
virtual ~Moment ()
Destructor.
void add (const point position, const tetIndices &tetIs, const Type &value)
Member Functions.
Type interpolate (const point position, const tetIndices &tetIs) const
Interpolate.
TypeGrad interpolateGrad (const point position, const tetIndices &tetIs) const
Interpolate gradient.
tmp< Field< Type > > internalField () const
Return an internal field of the average.
tmp< Field< TypeGrad > > internalFieldGrad () const
Return an internal field of the gradient.
Public Member Functions inherited from AveragingMethod< Type >
TypeName ("averagingMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AveragingMethod, dictionary,(const IOobject &io, const dictionary &dict, const fvMesh &mesh),(io, dict, mesh))
Declare runtime constructor selection table.
AveragingMethod (const IOobject &io, const dictionary &dict, const fvMesh &mesh, const labelList &size)
Constructors.
AveragingMethod (const AveragingMethod< Type > &am)
Construct a copy.
virtual ~AveragingMethod ()
Destructor.
virtual void average ()
Calculate the average.
virtual void average (const AveragingMethod< scalar > &weight)
virtual bool writeData (Ostream &) const
Dummy write.
virtual bool write () const
Write using setting from DB.
void operator= (const AveragingMethod< Type > &x)
Assign to another average.
void operator= (const Type &x)
Assign to value.
void operator= (tmp< FieldField< Field, Type > > x)
Assign to tmp.
void operator+= (tmp< FieldField< Field, Type > > x)
Add-equal tmp.
void operator*= (tmp< FieldField< Field, Type > > x)
Multiply-equal tmp.
void operator/= (tmp< FieldField< Field, scalar > > x)
Divide-equal tmp.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from FieldField< Field, Type >
FieldField ()
Construct null.
FieldField (const label)
Construct given size.
FieldField (const word &, const FieldField< Field, Type > &)
Construct using the Field sizes from the given FieldField.
FieldField (const FieldField< Field, Type > &)
Construct as copy.
FieldField (FieldField< Field, Type > &, bool reUse)
Construct as copy or re-use as specified.
FieldField (const PtrList< Field< Type > > &)
Construct as copy of a PtrList<Field, Type>
FieldField (const tmp< FieldField< Field, Type > > &)
Construct as copy of tmp<FieldField>
FieldField (Istream &)
Construct from Istream.
tmp< FieldField< Field, Type > > clone () const
Clone.
void negate ()
Negate this field.
tmp< FieldField< Field, cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const FieldField< Field, cmptType > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< FieldField< Field, Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const FieldField< Field, Type > &)
void operator= (const tmp< FieldField< Field, Type > > &)
void operator= (const Type &)
void operator+= (const FieldField< Field, Type > &)
void operator+= (const tmp< FieldField< Field, Type > > &)
void operator-= (const FieldField< Field, Type > &)
void operator-= (const tmp< FieldField< Field, Type > > &)
void operator*= (const FieldField< Field, scalar > &)
void operator*= (const tmp< FieldField< Field, scalar > > &)
void operator/= (const FieldField< Field, scalar > &)
void operator/= (const tmp< FieldField< Field, scalar > > &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from PtrList< Field< Type > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< Field< Type > > &)
Copy constructor.
PtrList (const PtrList< Field< Type > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< Field< Type > > > &)
Construct by transferring the parameter contents.
PtrList (PtrList< Field< Type > > &, bool reUse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< Field< Type > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
Field< Type > & first ()
Return reference to the first element of the list.
const Field< Type > & first () const
Return reference to first element of the list.
Field< Type > & last ()
Return reference to the last element of the list.
const Field< Type > & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (Field< Type > *)
Append an element at the end of the list.
void append (const autoPtr< Field< Type > > &)
void append (const tmp< Field< Type > > &)
void transfer (PtrList< Field< Type > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< Field< Type > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< Field< Type > > set (const label, Field< Type > *)
Set element. Return old element (can be NULL).
autoPtr< Field< Type > > set (const label, const autoPtr< Field< Type > > &)
autoPtr< Field< Type > > set (const label, const tmp< Field< Type > > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const Field< Type > & operator[] (const label) const
Return element const reference.
Field< Type > & operator[] (const label)
Return element reference.
const Field< Type > * operator() (const label) const
Return element const pointer.
PtrList< Field< Type > > & operator= (const PtrList< Field< Type > > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
const_iterator end () const
Return an const_iterator to end traversing the PtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the PtrList.
const_iterator cend () const
Return an const_iterator to end traversing the PtrList.
Additional Inherited Members
Static Public Member Functions inherited from AveragingMethod< Type >
static autoPtr< AveragingMethod< Type > > New (const IOobject &io, const dictionary &dict, const fvMesh &mesh)
Selector.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from FieldField< Field, Type >
template<class Type2 >
static tmp< FieldField< Field, Type > > NewCalculatedType (const FieldField< Field, Type2 > &ff)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Types inherited from AveragingMethod< Type >
typedef outerProduct< vector, Type >::type TypeGrad
Protected typedefs.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from PtrList< Field< Type > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Attributes inherited from AveragingMethod< Type >
const dictionary & dict_
Protected data.
const fvMesh & mesh_
The mesh on which the averaging is to be done.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Type>
class Foam::AveragingMethods::Moment< Type >
Moment lagrangian averaging procedure.
Point values and moments from the cell centroid are summed over computational cells. A linear function is generated which has the same integrated moment as that of the point data.
The computed linear function is used to interpolate values within a cell. The gradient is calculated from the coefficients of the function, and is assumed constant over the cell.
Source files
Moment.H
Moment.C
Definition at line 61 of file Moment.H.
Member Typedef Documentation
typedef AveragingMethod<Type>::TypeGrad TypeGrad
Public typedefs.
Gradient type
Definition at line 70 of file Moment.H.
Constructor & Destructor Documentation
Moment (const IOobject & io, const dictionary & dict, const fvMesh & mesh)
Constructors.
Construct from components
Definition at line 33 of file Moment.C.
References Foam::constant::physicoChemical::b, Foam::constant::universal::c, f(), tetIndices::face(), tetIndices::faceBasePt(), tetIndices::facePtA(), tetIndices::facePtB(), forAll, Foam::inv(), tetrahedron< Point, PointRef >::mag(), Foam::sqr(), Foam::sum(), T, and tetIndices::tet().
Moment (const Moment< Type > & am)
Construct a copy.
Definition at line 100 of file Moment.C.
~Moment () virtual
Destructor.
Definition at line 116 of file Moment.C.
Member Function Documentation
TypeName ("moment")
Runtime type information.
virtual autoPtr<AveragingMethod<Type> > clone () const inline virtual
Construct and return a clone.
Implements AveragingMethod< Type >.
Definition at line 122 of file Moment.H.
void add (const point position, const tetIndices & tetIs, const Type & value) virtual
Member Functions.
Add point value to interpolation
Implements AveragingMethod< Type >.
Definition at line 131 of file Moment.C.
References tetIndices::cell().
Type interpolate (const point position, const tetIndices & tetIs) const virtual
Interpolate.
Implements AveragingMethod< Type >.
Definition at line 157 of file Moment.C.
References tetIndices::cell().
Foam::AveragingMethods::Moment< Type >::TypeGrad interpolateGrad (const point position, const tetIndices & tetIs) const virtual
Interpolate gradient.
Implements AveragingMethod< Type >.
Definition at line 182 of file Moment.C.
References tetIndices::cell().
Foam::tmp< Foam::Field< Type > > internalField () const virtual
Return an internal field of the average.
Implements AveragingMethod< Type >.
Definition at line 201 of file Moment.C.
tmp<Field<TypeGrad> > internalFieldGrad () const
Return an internal field of the gradient.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/AveragingMethods/Moment/Moment.H
src/lagrangian/intermediate/submodels/MPPIC/AveragingMethods/Moment/Moment.C