OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NamedEnum< Enum, nEnum > Class Template Reference
Initialise the NamedEnum HashTable from the static list of names.
Inherits HashTable< int >.
Public Member Functions
NamedEnum ()
Construct from names.
Enum read (Istream &) const
Read a word from Istream and return the corresponding.
void write (const Enum e, Ostream &) const
Write the name representation of the enumeration to an Ostream.
const Enum operator[] (const char *name) const
Return the enumeration element corresponding to the given name.
const Enum operator[] (const word &name) const
Return the enumeration element corresponding to the given name.
const char * operator[] (const Enum e) const
Return the name of the given enumeration element.
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
Public Member Functions inherited from HashTable< int >
bool set (const word &, const int &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< int, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< int, word, string::hash >> &)
Construct by transferring the parameter contents.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const int &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< int, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< int, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
int & operator[] (const word &)
Find and return a hashedEntry.
const int & operator[] (const word &) const
Find and return a hashedEntry.
int & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< int, word, string::hash > &)
Assignment.
bool operator== (const HashTable< int, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< int, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Static Public Member Functions
static stringList strings ()
The set of names as a list of strings.
static wordList words ()
The set of names as a list of words.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes
static const char * names [nEnum]
The set of names corresponding to the enumeration Enum.
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Additional Inherited Members
Public Types inherited from HashTable< int >
typedef int value_type
Type of values the HashTable contains.
typedef int & reference
Type that can be used for storing into HashTable::value_type.
typedef const int & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Detailed Description
template<class Enum, int nEnum>
class Foam::NamedEnum< Enum, nEnum >
Initialise the NamedEnum HashTable from the static list of names.
Source files
NamedEnum.H
NamedEnum.C
Definition at line 52 of file NamedEnum.H.
Constructor & Destructor Documentation
NamedEnum ()
Construct from names.
Definition at line 31 of file NamedEnum.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, HashTable< int >::insert(), and NamedEnum< Enum, nEnum >::names().
Member Function Documentation
Enum read (Istream & is) const
Read a word from Istream and return the corresponding.
enumeration element
Definition at line 61 of file NamedEnum.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, HashTable< int >::find(), Foam::name(), and HashTable< int >::sortedToc().
Referenced by nastranSurfaceWriter::nastranSurfaceWriter(), solidificationMeltingSource::read(), addfileModificationCheckingToOpt::readData(), addcommsTypeToOpt::readData(), Time::readDict(), and sampledPatchInternalField::sampledPatchInternalField().
void write (const Enum e, Ostream & os) const
Write the name representation of the enumeration to an Ostream.
Definition at line 79 of file NamedEnum.C.
References NamedEnum< Enum, nEnum >::operator[]().
Foam::stringList strings () static
The set of names as a list of strings.
Definition at line 86 of file NamedEnum.C.
References NamedEnum< Enum, nEnum >::names(), and List< T >::setSize().
Foam::wordList words () static
The set of names as a list of words.
Definition at line 105 of file NamedEnum.C.
References NamedEnum< Enum, nEnum >::names(), and List< T >::setSize().
Referenced by mappedPatchBase::mappedPatchBase().
const Enum operator[] (const char * name) const inline
Return the enumeration element corresponding to the given name.
Definition at line 101 of file NamedEnum.H.
Referenced by NamedEnum< Enum, nEnum >::write().
const Enum operator[] (const word & name) const inline
Return the enumeration element corresponding to the given name.
Definition at line 107 of file NamedEnum.H.
const char* operator[] (const Enum e) const inline
Return the name of the given enumeration element.
Definition at line 113 of file NamedEnum.H.
const char * names ()
Definition at line 46 of file directions.C.
References Foam::abort(), primitiveMesh::cellCells(), primitiveMesh::cellCentres(), Foam::meshTools::cutDirToEdge(), Foam::e, Foam::meshTools::edgeToCutDir(), directionInfo::edgeToFaceIndex(), Foam::endl(), Foam::exit(), polyMesh::faceOwner(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), Foam::isA(), Foam::mag(), mesh, Foam::min(), patchIdentifier::name(), globalMeshData::nTotalCells(), twoDPointCorrector::planeNormal(), Foam::Pout, polyPatch::start(), WarningInFunction, Foam::meshTools::writeOBJ(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by NamedEnum< Enum, nEnum >::NamedEnum(), NamedEnum< Enum, nEnum >::strings(), and NamedEnum< Enum, nEnum >::words().
const char * names ()
Definition at line 41 of file tetDecomposer.C.
References polyTopoChange::addFace(), tetDecomposer::decompositionTypeNames, f(), polyTopoChange::modifyFace(), UList< T >::rcIndex(), face::reverseFace(), and List< T >::size().
const char * names ()
Definition at line 54 of file slidingInterface.C.
References Foam::abort(), PtrList< T >::empty(), Foam::endl(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, mesh, Foam::name(), Foam::nl, Foam::Pout, and slidingInterface::typeOfMatchNames_.
const char * names ()
Definition at line 47 of file extendedEdgeMesh.C.
const char * names ()
Definition at line 60 of file extendedEdgeMesh.C.
const char * names ()
Definition at line 75 of file extendedEdgeMesh.C.
References extendedEdgeMesh::convexStart_, Foam::cos(), extendedEdgeMesh::cosNormalAngleTol_, Foam::degToRad(), extendedEdgeMesh::edgeStatusNames_, extendedEdgeMesh::externalStart_, extendedEdgeMesh::nEdgeTypes, extendedEdgeMesh::nPointTypes, extendedEdgeMesh::pointStatusNames_, and extendedEdgeMesh::sideVolumeTypeNames_.
const char * names ()
Definition at line 37 of file coordSet.C.
References coordSet::coordSet().
const char * names ()
Definition at line 41 of file vtkUnstructuredReader.C.
References vtkUnstructuredReader::vtkDataTypeNames.
const char * names ()
Definition at line 58 of file vtkUnstructuredReader.C.
References vtkUnstructuredReader::vtkDataSetTypeNames.
const char * names ()
Definition at line 70 of file vtkUnstructuredReader.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), Foam::exit(), f(), Foam::FatalIOError, FatalIOErrorInFunction, fields, forAll, ISstream::getLine(), Foam::hex(), Foam::Info, HashSet< Key, Hash >::insert(), IOWarningInFunction, cellModeller::lookup(), vtkUnstructuredReader::parseModeNames, Foam::Pout, Foam::readLabel(), List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), List< T >::size(), regIOobject::store(), Foam::type(), and vtkUnstructuredReader::vtkUnstructuredReader().
const char * names ()
Definition at line 40 of file fanPressureFvPatchScalarField.C.
References fanPressureFvPatchScalarField::fanFlowDirectionNames_, and fanPressureFvPatchScalarField::fanPressureFvPatchScalarField().
const char * names ()
Definition at line 45 of file waveSurfacePressureFvPatchScalarField.C.
References waveSurfacePressureFvPatchScalarField::waveSurfacePressureFvPatchScalarField().
const char * names ()
Definition at line 44 of file surfaceDisplacementPointPatchVectorField.C.
References polyMesh::bounds(), Foam::endl(), searchableSurfaces::findAnyIntersection(), searchableSurfaces::findNearest(), surfaceDisplacementPointPatchVectorField::FIXEDNORMAL, forAll, PointIndexHit< Point >::hit(), Foam::Info, objectRegistry::lookupObject(), Foam::mag(), Foam::magSqr(), boundBox::max(), mesh, boundBox::min(), n, zone::name(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, surfaceDisplacementPointPatchVectorField::NEAREST, surfaceDisplacementPointPatchVectorField::POINTNORMAL, polyMesh::pointZones(), Foam::Pout, pZones(), PointIndexHit< Point >::rawPoint(), Foam::reduce(), Foam::returnReduce(), List< T >::size(), Foam::sqr(), surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField(), surfaceDisplacementPointPatchVectorField::surfaces(), pointZone::whichPoint(), and VectorSpace< Vector< scalar >, scalar, 3 >::zero.
const char * names ()
Definition at line 43 of file surfaceSlipDisplacementPointPatchVectorField.C.
References pointPatch::boundaryMesh(), polyMesh::bounds(), Foam::endl(), searchableSurfaces::findAnyIntersection(), searchableSurfaces::findNearest(), surfaceSlipDisplacementPointPatchVectorField::FIXEDNORMAL, forAll, PointIndexHit< Point >::hit(), Foam::Info, pointPatch::localPoints(), objectRegistry::lookupObject(), Foam::mag(), Foam::magSqr(), boundBox::max(), mesh, pointBoundaryMesh::mesh(), pointPatch::meshPoints(), boundBox::min(), n, pointPatch::name(), zone::name(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, surfaceSlipDisplacementPointPatchVectorField::NEAREST, pointPatchField< Type >::patch(), surfaceSlipDisplacementPointPatchVectorField::POINTNORMAL, pointPatch::pointNormals(), polyMesh::pointZones(), Foam::Pout, pZones(), PointIndexHit< Point >::rawPoint(), Foam::reduce(), Foam::returnReduce(), List< T >::size(), Foam::sqr(), surfaceSlipDisplacementPointPatchVectorField::surfaces(), surfaceSlipDisplacementPointPatchVectorField::surfaceSlipDisplacementPointPatchVectorField(), and pointZone::whichPoint().
const char * names ()
Definition at line 42 of file cellSetOption.C.
References cellSetOption::selectionModeTypeNames_.
const char * names ()
Definition at line 44 of file solidificationMeltingSource.C.
References Foam::abort(), Foam::fv::addToRunTimeSelectionTable(), basicThermo::Cp(), Foam::fv::defineTypeNameAndDebug(), dictionaryName::dictName(), Foam::dimEnergy, Foam::dimMass, Foam::dimTemperature, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, fv(), Foam::Info, Foam::max(), Foam::min(), IOobject::NO_READ, IOobject::NO_WRITE, Foam::readScalar(), Foam::T(), solidificationMeltingSource::thermoModeTypeNames_, Foam::type(), and dimensioned< Type >::value().
const char * names ()
Definition at line 37 of file phaseProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, found, Foam::mag(), Foam::nl, phaseProperties::phaseTypeNames, List< T >::setSize(), List< T >::size(), and Y0().
const char * names ()
Definition at line 70 of file meshRefinement.C.
const char * names ()
Definition at line 85 of file meshRefinement.C.
const char * names ()
Definition at line 95 of file meshRefinement.C.
References Foam::abort(), polyPatch::coupled(), Foam::endl(), polyPatch::faceAreas(), polyPatch::faceCells(), polyPatch::faceCentres(), Foam::FatalError, FatalErrorInFunction, forAll, HashTable< T, Key, Hash >::found(), PackedList< nBits >::get(), syncTools::getMasterFaces(), Foam::Info, meshRefinement::IOdebugTypeNames, meshRefinement::IOoutputTypeNames, meshRefinement::IOwriteTypeNames, Foam::mag(), Foam::nl, patches, Foam::reduce(), Foam::returnReduce(), List< T >::size(), polyPatch::start(), syncTools::swapBoundaryFaceList(), syncTools::swapBoundaryFacePositions(), syncTools::syncFaceList(), and meshRefinement::testSyncPointList().
const char * names ()
Definition at line 41 of file surfaceZonesInfo.C.
References surfaceZonesInfo::areaSelectionAlgoNames.
const char * names ()
Definition at line 60 of file surfaceZonesInfo.C.
References surfaceZonesInfo::faceZoneTypeNames, and surfaceZonesInfo::surfaceZonesInfo().
const char * names ()
Definition at line 45 of file shellSurfaces.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findLower(), forAll, forAllReverse, Foam::Info, volumeType::INSIDE, boundBox::invertedBox, Foam::mag(), boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), IOobject::name(), orientedSurface::orient(), volumeType::OUTSIDE, points, triSurfaceMesh::points(), s(), List< T >::setSize(), shellSurfaces::shellSurfaces(), List< T >::size(), boundBox::span(), and Foam::sqr().
const char * names ()
Definition at line 33 of file faceAreaIntersect.C.
References Foam::e, faceAreaIntersect::faceAreaIntersect(), FixedList< T, Size >::fcIndex(), forAll, Foam::mag(), n, plane::normal(), p, plane::refPoint(), s(), Foam::sqrt(), and faceAreaIntersect::triangulationModeNames_.
const char * names ()
Definition at line 57 of file mappedPatchBase.C.
const char * names ()
Definition at line 72 of file mappedPatchBase.C.
References mappedPatchBase::facePoints(), mappedPatchBase::offsetModeNames_, and mappedPatchBase::sampleModeNames_.
const char * names ()
Definition at line 45 of file faceToCell.C.
References Foam::add(), HashTableCore::end(), faceToCell::faceToCell(), HashTable< T, Key, Hash >::find(), forAllConstIter(), and HashTable< T, Key, Hash >::size().
const char * names ()
Definition at line 44 of file faceZoneToCell.C.
References Foam::add(), Foam::endl(), faceZoneToCell::faceZoneToCell(), forAll, Foam::Info, faceZone::masterCells(), zone::name(), List< T >::size(), faceZone::slaveCells(), and WarningInFunction.
const char * names ()
Definition at line 45 of file pointToCell.C.
References Foam::add(), f(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::found(), face::nextLabel(), and pointToCell::pointToCell().
const char * names ()
Definition at line 46 of file cellToFace.C.
References Foam::add(), cellToFace::cellToFace(), polyPatch::coupled(), Foam::endl(), Foam::exists(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::found(), topoSet::localPath(), patches, Foam::SeriousError, polyPatch::start(), and syncTools::swapBoundaryFaceList().
const char * names ()
Definition at line 45 of file pointToFace.C.
References Foam::add(), HashTableCore::end(), f(), HashTable< T, Key, Hash >::find(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::found(), face::nextLabel(), pFaces, pointToFace::pointToFace(), and HashTable< T, Key, Hash >::size().
const char * names ()
Definition at line 45 of file cellToPoint.C.
References Foam::add(), cellToPoint::cellToPoint(), f(), forAll, and forAllConstIter().
const char * names ()
Definition at line 45 of file faceToPoint.C.
References Foam::add(), f(), faceToPoint::faceToPoint(), forAll, and forAllConstIter().
const char * names ()
Definition at line 43 of file topoSetSource.C.
References topoSetSource::New(), and topoSetSource::usageTablePtr_.
const char * names ()
Definition at line 37 of file volumeType.C.
References volumeType::names.
const char * names ()
Definition at line 43 of file UPstream.C.
References UPstream::allocateCommunicator(), List< T >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), UPstream::commsTypeNames, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::identity(), Foam::name(), Foam::Perr, Foam::Pout, prefixOSstream::prefix(), and UPstream::worldComm.
const char * names ()
Definition at line 42 of file regIOobject.C.
References regIOobject::fileCheckTypesNames, regIOobject::fileModificationChecking, regIOobject::fileModificationSkew, dictionary::lookup(), Foam::debug::optimisationSwitch(), Foam::debug::optimisationSwitches(), and registerOptSwitch().
const char * names ()
Definition at line 43 of file Time.C.
const char * names ()
Definition at line 56 of file Time.C.
References Time::controlDictName, Time::format_, Time::general, Foam::log10(), Time::maxPrecision_, Time::precision_, Time::stopAtControlNames_, and Time::writeControlNames_.
const char * names ()
Definition at line 40 of file coupledPolyPatch.C.
References coupledPolyPatch::transformTypeNames.
const char * names ()
Definition at line 39 of file intersection.C.
const char * names ()
Definition at line 50 of file intersection.C.
References intersection::algorithmNames_, and intersection::directionNames_.
const char * names ()
Definition at line 60 of file fileMonitor.C.
const char * names ()
Definition at line 59 of file distributedTriSurfaceMesh.C.
References Foam::DelaunayMeshTools::allPoints(), List< T >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), treeBoundBox::contains(), geomDecomp::decompose(), mapDistribute::distribute(), distributedTriSurfaceMesh::distributionTypeNames_, Foam::endl(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, FixedList< T, Size >::fcIndex(), Foam::findIndex(), indexedOctree< Type >::findLineAny(), forAll, Pstream::gatherList(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), Foam::identity(), triangleFuncs::intersectBb(), treeBoundBox::intersects(), Foam::invertManyToMany(), Foam::magSqr(), Foam::matchPoints(), VectorSpace< Form, Cmpt, Ncmpts >::max, boundBox::max(), Foam::max(), VectorSpace< Form, Cmpt, Ncmpts >::min, boundBox::min(), Foam::min(), IOobject::MUST_READ_IF_MODIFIED, UPstream::myProcNo(), n, decompositionMethod::New(), IOobject::NO_WRITE, UPstream::nProcs(), boundBox::overlaps(), UPstream::parRun(), triSurface::patches(), pFaces, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::readScalar(), Foam::reduce(), labelledTri::region(), Foam::returnReduce(), mapDistribute::reverseDistribute(), s(), Pstream::scatterList(), PointIndexHit< Point >::setIndex(), List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), List< T >::size(), Foam::system(), IOobject::time(), globalIndex::toGlobal(), globalIndex::toLocal(), List< T >::transfer(), globalIndex::whichProcID(), and List< T >::xfer().
const char * names ()
Definition at line 40 of file fieldAverageItem.C.
const char * names ()
Definition at line 40 of file fieldMinMax.C.
References fieldMinMax::fieldMinMax(), and fieldMinMax::modeTypeNames_.
const char * names ()
Definition at line 36 of file cellSource.C.
const char * names ()
Definition at line 44 of file cellSource.C.
const char * names ()
Definition at line 42 of file faceSource.C.
const char * names ()
Definition at line 51 of file faceSource.C.
References Foam::fieldValues::addToRunTimeSelectionTable(), Foam::DelaunayMeshTools::allPoints(), Foam::fieldValues::defineTypeNameAndDebug(), dict, Foam::e, Foam::endl(), Foam::exit(), f(), faceId(), sampledSurface::faces(), Foam::FatalError, FatalErrorInFunction, faceZone::flipMap(), forAll, PatchTools::gatherAndMerge(), Pstream::gatherList(), Foam::gSum(), Foam::inplaceRenumber(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mergePoints(), mesh, UPstream::myProcNo(), sampledSurface::New(), Foam::nl, nPoints, UPstream::nProcs(), faceSource::operationTypeNames_, UPstream::parRun(), patchId(), points, sampledSurface::points(), Foam::Pout, Foam::returnReduce(), s(), List< T >::setSize(), List< T >::size(), faceSource::sourceTypeNames_, polyPatch::start(), dictionary::subDict(), List< T >::transfer(), Foam::type(), and polyPatch::whichFace().
const char * names ()
Definition at line 43 of file fieldValueDelta.C.
References fieldValueDelta::fieldValueDelta(), and fieldValueDelta::operationTypeNames_.
const char * names ()
Definition at line 50 of file abortCalculation.C.
References Foam::isFile(), UPstream::master(), Foam::reduce(), and Foam::rm().
const char * names ()
Definition at line 38 of file turbulenceFields.C.
References turbulenceFields::compressibleFieldNames_.
const char * names ()
Definition at line 53 of file turbulenceFields.C.
References turbulenceFields::incompressibleFieldNames_, turbulenceFields::modelName, and turbulenceModel::propertiesName.
const char * names ()
Definition at line 40 of file energyRegionCoupledFvPatchScalarField.C.
References fvPatch::delta(), dictionaryName::dictName(), energyRegionCoupledFvPatchScalarField::energyRegionCoupledFvPatchScalarField(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::constant::electromagnetic::kappa, basicThermo::kappa(), ThermalDiffusivity< BasicTurbulenceModel >::kappaEff(), fvPatch::lookupPatchField(), fvPatch::nf(), fvPatch::patch(), turbulenceModel::propertiesName, tmp< T >::ref(), and Foam::refCast().
const char * names ()
Definition at line 42 of file meshToMesh.C.
References List< T >::append(), polyMesh::bounds(), meshToMeshMethod::calculate(), cells, primitiveMesh::cells(), mapDistribute::constructMap(), mapDistribute::distribute(), Foam::endl(), polyMesh::faces(), forAll, boundBox::inflate(), Foam::Info, meshToMesh::interpolationMethodNames_, boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), UPstream::myProcNo(), OSstream::name(), Foam::name(), meshToMeshMethod::New(), Foam::nl, IOobject::NO_READ, UPstream::nonBlocking, word::null, boundBox::overlaps(), patches, points, polyMesh::points(), Foam::Pout, Foam::reduce(), Foam::returnReduce(), s(), List< T >::size(), HashTable< T, Key, Hash >::size(), mapDistribute::subMap(), Foam::sum(), meshToMeshMethod::V(), Ostream::write(), meshToMeshMethod::writeConnectivity(), and Foam::xferMove().
const char * names ()
Definition at line 49 of file sampledTriSurfaceMesh.C.
const char * names ()
Definition at line 42 of file nastranSurfaceWriter.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, p, points, OSstream::precision(), Foam::scientific(), IOstream::setf(), Foam::setw(), List< T >::size(), face::triangles(), IOstream::unsetf(), nastranSurfaceWriter::writeFormatNames_, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
const char * names ()
Definition at line 48 of file radiationCoupledBase.C.
References radiationCoupledBase::radiationCoupledBase().
const char * names ()
Definition at line 42 of file alphaContactAngleFvPatchScalarField.C.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), and alphaContactAngleFvPatchScalarField::limitControlNames_.
const char * names ()
Definition at line 42 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
References externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), and externalWallHeatFluxTemperatureFvPatchScalarField::operationModeNames.
const char * names ()
Definition at line 41 of file temperatureCoupledBase.C.
References temperatureCoupledBase::KMethodTypeNames_, and temperatureCoupledBase::temperatureCoupledBase().
const char * names ()
Definition at line 43 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
References compressible, and turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField().
Member Data Documentation
const char* names[nEnum] static
The set of names corresponding to the enumeration Enum.
Definition at line 73 of file NamedEnum.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/NamedEnum/NamedEnum.H
src/OpenFOAM/containers/NamedEnum/NamedEnum.C