OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
multivariateGaussConvectionScheme< Type > Class Template Reference
Basic second-order convection using face-gradients and Gauss' theorem.
Public Member Functions
TypeName ("Gauss")
Runtime type information.
multivariateGaussConvectionScheme (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &is)
Construct from flux and Istream.
tmp< multivariateSurfaceInterpolationScheme< Type > > interpolationScheme () const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from convectionScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
declareRunTimeSelectionTable (tmp, convectionScheme, Multivariate,(const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >:: fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, fields, faceFlux, schemeData))
convectionScheme (const convectionScheme &)
Copy construct.
convectionScheme (const fvMesh &mesh, const surfaceScalarField &)
Construct from mesh, flux and Istream.
virtual ~convectionScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
void operator= (const convectionScheme< Type > &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from convectionScheme< Type >
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new convectionScheme created on freestore.
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new multivariate convectionScheme.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::fv::multivariateGaussConvectionScheme< Type >
Basic second-order convection using face-gradients and Gauss' theorem.
Source files
multivariateGaussConvectionScheme.H
multivariateGaussConvectionScheme.C
Definition at line 54 of file multivariateGaussConvectionScheme.H.
Constructor & Destructor Documentation
multivariateGaussConvectionScheme (const fvMesh & mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable & fields, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from flux and Istream.
Definition at line 73 of file multivariateGaussConvectionScheme.H.
Member Function Documentation
TypeName ("Gauss")
Runtime type information.
tmp<multivariateSurfaceInterpolationScheme<Type> > interpolationScheme () const inline
Definition at line 95 of file multivariateGaussConvectionScheme.H.
References multivariateGaussConvectionScheme< Type >::flux(), multivariateGaussConvectionScheme< Type >::fvcDiv(), multivariateGaussConvectionScheme< Type >::fvmDiv(), and multivariateGaussConvectionScheme< Type >::interpolate().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 45 of file multivariateGaussConvectionScheme.C.
References multivariateGaussConvectionScheme< Type >::flux(), gaussConvectionScheme< Type >::interpolate(), and mesh.
Referenced by multivariateGaussConvectionScheme< Type >::interpolationScheme().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 62 of file multivariateGaussConvectionScheme.C.
References gaussConvectionScheme< Type >::flux(), multivariateGaussConvectionScheme< Type >::fvmDiv(), and mesh.
Referenced by multivariateGaussConvectionScheme< Type >::interpolate(), and multivariateGaussConvectionScheme< Type >::interpolationScheme().
tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 79 of file multivariateGaussConvectionScheme.C.
References multivariateGaussConvectionScheme< Type >::fvcDiv(), gaussConvectionScheme< Type >::fvmDiv(), and mesh.
Referenced by multivariateGaussConvectionScheme< Type >::flux(), and multivariateGaussConvectionScheme< Type >::interpolationScheme().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 96 of file multivariateGaussConvectionScheme.C.
References gaussConvectionScheme< Type >::fvcDiv(), and mesh.
Referenced by multivariateGaussConvectionScheme< Type >::fvmDiv(), and multivariateGaussConvectionScheme< Type >::interpolationScheme().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/convectionSchemes/multivariateGaussConvectionScheme/multivariateGaussConvectionScheme.H
src/finiteVolume/finiteVolume/convectionSchemes/multivariateGaussConvectionScheme/multivariateGaussConvectionScheme.C