OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
multiComponentMixture< ThermoType > Class Template Reference
Foam::multiComponentMixture.
Public Types
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Public Types inherited from basicSpecieMixture
typedef basicSpecieMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Member Functions
multiComponentMixture (const dictionary &, const wordList &specieNames, const HashPtrTable< ThermoType > &thermoData, const fvMesh &, const word &)
Construct from dictionary, specie names, thermo database,.
multiComponentMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
virtual ~multiComponentMixture ()
Destructor.
const ThermoType & cellMixture (const label celli) const
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
const ThermoType & cellVolMixture (const scalar p, const scalar T, const label celli) const
const ThermoType & patchFaceVolMixture (const scalar p, const scalar T, const label patchi, const label facei) const
const PtrList< ThermoType > & speciesData () const
Return the raw specie thermodynamic data.
void read (const dictionary &)
Read dictionary.
const ThermoType & getLocalThermo (const label speciei) const
Return thermo based on index.
Public Member Functions inherited from basicSpecieMixture
TypeName ("basicSpecieMixture")
Run time type information.
basicSpecieMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicSpecieMixture ()
Destructor.
virtual scalar nMoles (const label speciei) const =0
Number of moles of the given specie [].
virtual scalar W (const label speciei) const =0
Molecular weight of the given specie [kg/kmol].
tmp< volScalarField > W () const
Molecular weight of the mixture [kg/kmol].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar Hc (const label speciei) const =0
Chemical enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
Density [kg/m3].
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
bool contains (const word &specieName) const
Does the mixture include this specie?
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
Table of specie names.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
template<class ThermoType>
class Foam::multiComponentMixture< ThermoType >
Foam::multiComponentMixture.
Source files
multiComponentMixture.H
multiComponentMixture.C
Definition at line 50 of file multiComponentMixture.H.
Member Typedef Documentation
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Definition at line 83 of file multiComponentMixture.H.
Constructor & Destructor Documentation
multiComponentMixture (const dictionary & thermoDict, const wordList & specieNames, const HashPtrTable< ThermoType > & thermoData, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, specie names, thermo database,.
mesh and phase name
Definition at line 78 of file multiComponentMixture.C.
References forAll.
multiComponentMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, mesh and phase name.
Definition at line 106 of file multiComponentMixture.C.
References multiComponentMixture< ThermoType >::cellMixture().
virtual ~multiComponentMixture () inline virtual
Destructor.
Definition at line 104 of file multiComponentMixture.H.
References multiComponentMixture< ThermoType >::cellMixture(), multiComponentMixture< ThermoType >::cellVolMixture(), p, multiComponentMixture< ThermoType >::patchFaceMixture(), multiComponentMixture< ThermoType >::patchFaceVolMixture(), patchi, and Foam::T().
Member Function Documentation
const ThermoType & cellMixture (const label celli) const
Definition at line 131 of file multiComponentMixture.C.
References n, and multiComponentMixture< ThermoType >::patchFaceMixture().
Referenced by multiComponentMixture< ThermoType >::multiComponentMixture(), and multiComponentMixture< ThermoType >::~multiComponentMixture().
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
Definition at line 148 of file multiComponentMixture.C.
References multiComponentMixture< ThermoType >::cellVolMixture(), n, and patchi.
Referenced by multiComponentMixture< ThermoType >::cellMixture(), and multiComponentMixture< ThermoType >::~multiComponentMixture().
const ThermoType & cellVolMixture (const scalar p, const scalar T, const label celli) const
Definition at line 170 of file multiComponentMixture.C.
References forAll, n, and multiComponentMixture< ThermoType >::patchFaceVolMixture().
Referenced by multiComponentMixture< ThermoType >::patchFaceMixture(), and multiComponentMixture< ThermoType >::~multiComponentMixture().
const ThermoType & patchFaceVolMixture (const scalar p, const scalar T, const label patchi, const label facei) const
Definition at line 198 of file multiComponentMixture.C.
References forAll, n, patchi, and multiComponentMixture< ThermoType >::read().
Referenced by multiComponentMixture< ThermoType >::cellVolMixture(), and multiComponentMixture< ThermoType >::~multiComponentMixture().
const PtrList<ThermoType>& speciesData () const inline
Return the raw specie thermodynamic data.
Definition at line 134 of file multiComponentMixture.H.
References multiComponentMixture< ThermoType >::read().
void read (const dictionary & thermoDict)
Read dictionary.
Definition at line 229 of file multiComponentMixture.C.
References forAll, and dictionary::subDict().
Referenced by multiComponentMixture< ThermoType >::patchFaceVolMixture(), and multiComponentMixture< ThermoType >::speciesData().
const ThermoType& getLocalThermo (const label speciei) const inline
Return thermo based on index.
Definition at line 143 of file multiComponentMixture.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/multiComponentMixture/multiComponentMixture.H
src/thermophysicalModels/reactionThermo/mixtures/multiComponentMixture/multiComponentMixture.C