OpenFOAM: multiLevelDecomp Class Reference
multiLevelDecomp Class Reference
Decomposition given using consecutive application of decomposers.
Public Member Functions
TypeName ("multiLevel")
Runtime type information.
multiLevelDecomp (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~multiLevelDecomp ()
Destructor.
virtual bool parallelAware () const
Is method parallel aware (i.e. does it synchronize domains across.
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)
Return for every coordinate the wanted processor number. Explicitly.
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual labelList decompose (const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &, const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp)
Helper: apply constraints to a decomposition. This gives.
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Helper: determine (local or global) cellCells and face weights.
Protected Attributes inherited from decompositionMethod
const dictionary & decompositionDict_
label nProcessors_
PtrList< decompositionConstraint > constraints_
Optional constraints.
Detailed Description
Decomposition given using consecutive application of decomposers.
Source files
multiLevelDecomp.H
multiLevelDecomp.C
Definition at line 46 of file multiLevelDecomp.H.
Constructor & Destructor Documentation
multiLevelDecomp (const dictionary & decompositionDict)
Construct given the decomposition dictionary.
Definition at line 330 of file multiLevelDecomp.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIter(), Foam::Info, decompositionMethod::nDomains(), decompositionMethod::New(), DLListBase::size(), and Foam::type().
virtual ~multiLevelDecomp () inline virtual
Destructor.
Definition at line 103 of file multiLevelDecomp.H.
References decompositionMethod::decompose(), mesh, and multiLevelDecomp::parallelAware().
Member Function Documentation
TypeName ("multiLevel")
Runtime type information.
bool parallelAware () const virtual
Is method parallel aware (i.e. does it synchronize domains across.
proc boundaries)
Implements decompositionMethod.
Definition at line 365 of file multiLevelDecomp.C.
References forAll.
Referenced by multiLevelDecomp::~multiLevelDecomp().
Foam::labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) virtual
Return for every coordinate the wanted processor number. Use the.
mesh connectivity (if needed)
Implements decompositionMethod.
Definition at line 379 of file multiLevelDecomp.C.
References decompositionMethod::calcCellCells(), Foam::identity(), and List< T >::size().
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) virtual
Return for every coordinate the wanted processor number. Explicitly.
provided connectivity - does not use mesh_.
Implements decompositionMethod.
Definition at line 407 of file multiLevelDecomp.C.
References Foam::identity(), and List< T >::size().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/multiLevelDecomp/multiLevelDecomp.H
src/parallel/decompose/decompositionMethods/multiLevelDecomp/multiLevelDecomp.C