OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
movingWallVelocityFvPatchVectorField Class Reference
Boundary Conditions » Wall boundary Conditions
This boundary condition provides a velocity condition for cases with moving walls. In addition, it should also be applied to 'moving' walls for moving reference frame (MRF) calculations.
Public Member Functions
TypeName ("movingWallVelocity")
Runtime type information.
movingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
movingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given movingWallVelocityFvPatchVectorField.
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a velocity condition for cases with moving walls. In addition, it should also be applied to 'moving' walls for moving reference frame (MRF) calculations.
Patch usage
Property Description Required Default value
U velociy field name no U
Example of the boundary condition specification:
    myPatch
    {
        type            movingWallVelocity;
        U               U;
        value           uniform 0; // initial value
    }
See also
Foam::fixedValueFvPatchVectorField Foam::MRFZone
Source files
movingWallVelocityFvPatchVectorField.H
movingWallVelocityFvPatchVectorField.C
Definition at line 86 of file movingWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
movingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file movingWallVelocityFvPatchVectorField.C.
Referenced by movingWallVelocityFvPatchVectorField::clone(), and movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField().
movingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 63 of file movingWallVelocityFvPatchVectorField.C.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField(), fvPatch::size(), and vectorField().
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given movingWallVelocityFvPatchVectorField.
onto a new patch
Definition at line 49 of file movingWallVelocityFvPatchVectorField.C.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField().
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField & mwvpvf)
Construct as copy.
Definition at line 78 of file movingWallVelocityFvPatchVectorField.C.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField().
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField & mwvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 89 of file movingWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName ("movingWallVelocity")
Runtime type information.
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 136 of file movingWallVelocityFvPatchVectorField.H.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField().
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 153 of file movingWallVelocityFvPatchVectorField.H.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField(), movingWallVelocityFvPatchVectorField::updateCoeffs(), and movingWallVelocityFvPatchVectorField::write().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 101 of file movingWallVelocityFvPatchVectorField.C.
References TimeState::deltaTValue(), dimensionedInternalField(), polyPatch::faceCentres(), forAll, fvPatch::magSf(), mesh, Foam::fvc::meshPhi(), polyMesh::moving(), n, fvPatch::nf(), polyMesh::oldPoints(), Field< vector >::operator=(), fvPatch::patch(), fvPatch::patchField(), fvMesh::time(), and U.
Referenced by movingWallVelocityFvPatchVectorField::clone().
void write (Ostream & os) const virtual
Write.
Definition at line 145 of file movingWallVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by movingWallVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/movingWallVelocity/movingWallVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/movingWallVelocity/movingWallVelocityFvPatchVectorField.C