OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
moleFractions< ThermoType > Class Template Reference
This function object calculates mole-fraction fields from the mass-fraction fields of the psi/rhoReactionThermo and caches them for output and further post-processing.
Public Member Functions
TypeName ("moleFractions")
Runtime type information.
moleFractions (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~moleFractions ()
Destructor.
virtual const word & name () const
Return name of the moleFractions functionObject.
virtual void read (const dictionary &)
Read the moleFractions data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the moleFractions and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void writeFileHeader (const label i=0)
File header information.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Detailed Description
template<class ThermoType>
class Foam::moleFractions< ThermoType >
This function object calculates mole-fraction fields from the mass-fraction fields of the psi/rhoReactionThermo and caches them for output and further post-processing.
The names of the mole-fraction fields are obtained from the corresponding mass-fraction fields prepended by "X_"
Example of function object specification:
moleFractions
{
    type psiReactionThermoMoleFractions;
}
or
moleFractions
{
    type rhoReactionThermoMoleFractions;
}
depending on the thermodynamics package used in the solver.
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
moleFractions.H
moleFractions.C
Definition at line 75 of file moleFractions.H.
Constructor & Destructor Documentation
moleFractions (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 52 of file moleFractions.C.
References dictName(), Foam::dimless, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::name(), and PtrList< T >::setSize().
~moleFractions () virtual
Destructor.
Definition at line 108 of file moleFractions.C.
References moleFractions< ThermoType >::read().
Member Function Documentation
TypeName ("moleFractions< ThermoType >")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the moleFractions functionObject.
Definition at line 129 of file moleFractions.H.
References moleFractions< ThermoType >::end(), moleFractions< ThermoType >::execute(), moleFractions< ThermoType >::read(), moleFractions< ThermoType >::timeSet(), and moleFractions< ThermoType >::write().
void read (const dictionary & dict) virtual
Read the moleFractions data.
Definition at line 116 of file moleFractions.C.
Referenced by moleFractions< ThermoType >::name(), and moleFractions< ThermoType >::~moleFractions().
void execute () virtual
Execute, currently does nothing.
Definition at line 123 of file moleFractions.C.
Referenced by moleFractions< ThermoType >::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 130 of file moleFractions.C.
Referenced by moleFractions< ThermoType >::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 135 of file moleFractions.C.
Referenced by moleFractions< ThermoType >::name().
void write () virtual
Calculate the moleFractions and write.
Reimplemented from functionObjectFile.
Definition at line 140 of file moleFractions.C.
Referenced by moleFractions< ThermoType >::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 150 of file moleFractions.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 154 of file moleFractions.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/functionObjects/moleFractions/moleFractions.H
src/thermophysicalModels/reactionThermo/functionObjects/moleFractions/moleFractions.C