OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
MRFZoneList Class Reference
List container for MRF zomes.
Public Member Functions
MRFZoneList (const fvMesh &mesh, const dictionary &dict)
Constructor.
~MRFZoneList ()
Destructor.
bool active (const bool warn=false) const
Return active status.
void reset (const dictionary &dict)
Reset the source list.
void addAcceleration (const volVectorField &U, volVectorField &ddtU) const
Add the frame acceleration.
void addAcceleration (fvVectorMatrix &UEqn) const
Add the frame acceleration contribution to the momentum equation.
void addAcceleration (const volScalarField &rho, fvVectorMatrix &UEqn) const
Add the frame acceleration contribution to the momentum equation.
tmp< volVectorField > DDt (const volVectorField &U) const
Return the frame acceleration.
tmp< volVectorField > DDt (const volScalarField &rho, const volVectorField &U) const
Return the frame acceleration.
void makeRelative (volVectorField &U) const
Make the given absolute velocity relative within the MRF region.
void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative within the MRF region.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &phi) const
Return the given absolute flux relative within the MRF region.
tmp< FieldField< fvsPatchField, scalar > > relative (const tmp< FieldField< fvsPatchField, scalar > > &tphi) const
Return the given absolute boundary flux relative within.
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative within the MRF region.
void makeAbsolute (volVectorField &U) const
Make the given relative velocity absolute within the MRF region.
void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute within the MRF region.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &phi) const
Return the given relative flux absolute within the MRF region.
void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute within the MRF region.
void correctBoundaryVelocity (volVectorField &U) const
Correct the boundary velocity for the rotation of the MRF region.
void correctBoundaryFlux (const volVectorField &U, surfaceScalarField &phi) const
Correct the boundary flux for the rotation of the MRF region.
bool read (const dictionary &dict)
Read dictionary.
bool writeData (Ostream &os) const
Write data to Ostream.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh database.
Friends
Ostream & operator<< (Ostream &os, const MRFZoneList &models)
Ostream operator.
Detailed Description
List container for MRF zomes.
Source files
MRFZoneList.H
MRFZoneList.C
Definition at line 55 of file MRFZoneList.H.
Constructor & Destructor Documentation
MRFZoneList (const fvMesh & mesh, const dictionary & dict)
Constructor.
Definition at line 33 of file MRFZoneList.C.
~MRFZoneList ()
Destructor.
Definition at line 49 of file MRFZoneList.C.
Member Function Documentation
bool active (const bool warn = false) const
Return active status.
Definition at line 55 of file MRFZoneList.C.
References Foam::endl(), forAll, and Foam::Info.
void reset (const dictionary & dict)
Reset the source list.
Definition at line 72 of file MRFZoneList.C.
References Foam::endl(), forAllConstIter, Foam::Info, Foam::name(), and setSize().
void addAcceleration (const volVectorField & U, volVectorField & ddtU) const
Add the frame acceleration.
Definition at line 130 of file MRFZoneList.C.
References forAll.
void addAcceleration (fvVectorMatrix & UEqn) const
Add the frame acceleration contribution to the momentum equation.
Definition at line 142 of file MRFZoneList.C.
References forAll.
void addAcceleration (const volScalarField & rho, fvVectorMatrix & UEqn) const
Add the frame acceleration contribution to the momentum equation.
Definition at line 152 of file MRFZoneList.C.
References forAll.
Foam::tmp< Foam::volVectorField > DDt (const volVectorField & U) const
Return the frame acceleration.
Definition at line 165 of file MRFZoneList.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, forAll, DimensionedField< Type, GeoMesh >::mesh(), and Vector< scalar >::zero.
Foam::tmp< Foam::volVectorField > DDt (const volScalarField & rho, const volVectorField & U) const
Return the frame acceleration.
Definition at line 195 of file MRFZoneList.C.
References Foam::fvc::DDt().
void makeRelative (volVectorField & U) const
Make the given absolute velocity relative within the MRF region.
Definition at line 204 of file MRFZoneList.C.
References forAll.
void makeRelative (surfaceScalarField & phi) const
Make the given absolute flux relative within the MRF region.
Definition at line 213 of file MRFZoneList.C.
References forAll.
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & phi) const
Return the given absolute flux relative within the MRF region.
Definition at line 223 of file MRFZoneList.C.
References Foam::fvc::makeRelative(), and tmp< T >::ptr().
Foam::tmp< Foam::FieldField< Foam::fvsPatchField, Foam::scalar > > relative (const tmp< FieldField< fvsPatchField, scalar > > & tphi) const
Return the given absolute boundary flux relative within.
the MRF region
Definition at line 235 of file MRFZoneList.C.
References forAll, and tmp< T >::ptr().
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given absolute mass-flux relative within the MRF region.
Definition at line 251 of file MRFZoneList.C.
References forAll.
void makeAbsolute (volVectorField & U) const
Make the given relative velocity absolute within the MRF region.
Definition at line 263 of file MRFZoneList.C.
References forAll.
void makeAbsolute (surfaceScalarField & phi) const
Make the given relative flux absolute within the MRF region.
Definition at line 272 of file MRFZoneList.C.
References forAll.
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & phi) const
Return the given relative flux absolute within the MRF region.
Definition at line 282 of file MRFZoneList.C.
References Foam::fvc::makeAbsolute(), and tmp< T >::ptr().
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given relative mass-flux absolute within the MRF region.
Definition at line 293 of file MRFZoneList.C.
References forAll.
void correctBoundaryVelocity (volVectorField & U) const
Correct the boundary velocity for the rotation of the MRF region.
Definition at line 305 of file MRFZoneList.C.
References forAll.
void correctBoundaryFlux (const volVectorField & U, surfaceScalarField & phi) const
Correct the boundary flux for the rotation of the MRF region.
Definition at line 315 of file MRFZoneList.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, patchi, and Foam::fvc::relative().
bool read (const dictionary & dict)
Read dictionary.
Definition at line 104 of file MRFZoneList.C.
References forAll, MRFZone::name(), MRFZone::read(), and dictionary::subDict().
Referenced by IOMRFZoneList::read().
bool writeData (Ostream & os) const
Write data to Ostream.
Definition at line 117 of file MRFZoneList.C.
References forAll, IOstream::good(), and Foam::nl.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const MRFZoneList & models) friend
Ostream operator.
Member Data Documentation
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 75 of file MRFZoneList.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.H
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.C