OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
multivariateSelectionScheme< Type > Class Template Reference
Generic multi-variate discretisation scheme class for which any of the NVD, CNVD or NVDV schemes may be selected for each variable.
Classes
class fieldScheme
surfaceInterpolationScheme sub-class returned by operator(field)
Public Member Functions
TypeName ("multivariateSelection")
Runtime type information.
multivariateSelectionScheme (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Construct for field, faceFlux and Istream.
tmp< surfaceInterpolationScheme< Type > > operator() (const GeometricField< Type, fvPatchField, volMesh > &field) const
Public Member Functions inherited from multivariateSurfaceInterpolationScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, multivariateSurfaceInterpolationScheme, Istream,(const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &is),(mesh, fields, faceFlux, is))
multivariateSurfaceInterpolationScheme (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Construct for interpolating given field.
virtual ~multivariateSurfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
const fieldTable & fields () const
Return fields to be interpolated.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from multivariateSurfaceInterpolationScheme< Type >
static tmp< multivariateSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::multivariateSelectionScheme< Type >
Generic multi-variate discretisation scheme class for which any of the NVD, CNVD or NVDV schemes may be selected for each variable.
Source files
multivariateSelectionScheme.H
multivariateSelectionScheme.C
Definition at line 51 of file multivariateSelectionScheme.H.
Constructor & Destructor Documentation
multivariateSelectionScheme (const fvMesh & mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData)
Construct for field, faceFlux and Istream.
Definition at line 37 of file multivariateSelectionScheme.C.
References fields, Foam::MULES::limiter(), limitedSurfaceInterpolationScheme< Type >::limiter(), Foam::min(), Foam::name(), and upwind< Type >::weights().
Member Function Documentation
TypeName ("multivariateSelection")
Runtime type information.
tmp<surfaceInterpolationScheme<Type> > operator() (const GeometricField< Type, fvPatchField, volMesh > & field) const inline virtual
Implements multivariateSurfaceInterpolationScheme< Type >.
Definition at line 131 of file multivariateSelectionScheme.H.
References multivariateSelectionScheme< Type >::fieldScheme::fieldScheme().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateSelectionScheme/multivariateSelectionScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateSelectionScheme/multivariateSelectionScheme.C