OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
normalToFace Class Reference
A topoSetSource to select faces based on normal.
Public Member Functions
TypeName ("normalToFace")
Runtime type information.
normalToFace (const polyMesh &mesh, const vector &normal, const scalar tol)
Construct from components.
normalToFace (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
normalToFace (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~normalToFace ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label cellI, const bool) const
Add (if bool) cellI to set or delete cellI from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = NULL
A table of usage strings.
Detailed Description
A topoSetSource to select faces based on normal.
Source files
normalToFace.H
normalToFace.C
Definition at line 49 of file normalToFace.H.
Constructor & Destructor Documentation
normalToFace (const polyMesh & mesh, const vector & normal, const scalar tol)
Construct from components.
Definition at line 76 of file normalToFace.C.
normalToFace (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 91 of file normalToFace.C.
normalToFace (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 102 of file normalToFace.C.
~normalToFace () virtual
Destructor.
Definition at line 114 of file normalToFace.C.
References normalToFace::applyToSet().
Member Function Documentation
TypeName ("normalToFace")
Runtime type information.
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 100 of file normalToFace.H.
References normalToFace::applyToSet(), and topoSetSource::FACESETSOURCE.
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 121 of file normalToFace.C.
References topoSetSource::ADD, DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), topoSetSource::DELETE, Foam::endl(), primitiveMesh::faceAreas(), forAll, forAllConstIter(), Foam::Info, Foam::mag(), topoSetSource::mesh_, n, and topoSetSource::NEW.
Referenced by normalToFace::setType(), and normalToFace::~normalToFace().
The documentation for this class was generated from the following files:
src/meshTools/sets/faceSources/normalToFace/normalToFace.H
src/meshTools/sets/faceSources/normalToFace/normalToFace.C