OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
nearWallDistNoSearch Class Reference
Distance calculation for cells with face on a wall. Does not search anything, just takes normal component of distance.
Public Member Functions
nearWallDistNoSearch (const fvMesh &mesh)
Construct from components.
virtual ~nearWallDistNoSearch ()
Destructor.
virtual void correct ()
Correct for mesh geom/topo changes.
Public Member Functions inherited from GeometricField< Type, PatchField, GeoMesh >::Boundary
Boundary (const BoundaryMesh &)
Construct from a BoundaryMesh.
Boundary (const BoundaryMesh &, const Internal &, const word &)
Construct from a BoundaryMesh,.
Boundary (const BoundaryMesh &, const Internal &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Construct from a BoundaryMesh,.
Boundary (const BoundaryMesh &, const Internal &, const PtrList< PatchField< Type >> &)
Construct from a BoundaryMesh,.
Boundary (const Internal &, const Boundary &)
Construct as copy setting the reference to the internal field.
Boundary (const Boundary &)
Construct as copy.
Boundary (const BoundaryMesh &, const Internal &, const dictionary &)
Construct from dictionary.
void readField (const Internal &field, const dictionary &dict)
Read the boundary field.
void updateCoeffs ()
Update the boundary condition coefficients.
void evaluate ()
Evaluate boundary conditions.
wordList types () const
Return a list of the patch types.
Boundary boundaryInternalField () const
Return BoundaryField of the cell values neighbouring.
LduInterfaceFieldPtrsList< Type > interfaces () const
Return a list of pointers for each patch field with only those.
lduInterfaceFieldPtrsList scalarInterfaces () const
Return a list of pointers for each patch field with only those.
void writeEntry (const word &keyword, Ostream &os) const
Write boundary field as dictionary entry.
void operator= (const Boundary &)
Assignment to BoundaryField<Type, PatchField, BoundaryMesh>
void operator= (const FieldField< PatchField, Type > &)
Assignment to FieldField<PatchField, Type>
void operator= (const Type &)
Assignment to Type.
void operator== (const Boundary &)
Forced assignment to.
void operator== (const FieldField< PatchField, Type > &)
Forced assignment to FieldField<PatchField, Type>
void operator== (const Type &)
Forced assignment to Type.
Public Member Functions inherited from FieldField< PatchField, Type >
FieldField ()
Construct null.
FieldField (const label)
Construct given size.
FieldField (const word &, const FieldField< PatchField, Type > &)
Construct using the Field sizes from the given FieldField.
FieldField (const FieldField< PatchField, Type > &)
Construct as copy.
FieldField (FieldField< PatchField, Type > &, bool reuse)
Construct as copy or re-use as specified.
FieldField (const PtrList< PatchField< Type >> &)
Construct as copy of a PtrList<Field, Type>
FieldField (const tmp< FieldField< PatchField, Type >> &)
Construct as copy of tmp<FieldField>
FieldField (Istream &)
Construct from Istream.
tmp< FieldField< PatchField, Type > > clone () const
Clone.
void negate ()
Negate this field.
tmp< FieldField< PatchField, cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const FieldField< PatchField, cmptType > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< FieldField< PatchField, Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const FieldField< PatchField, Type > &)
void operator= (const tmp< FieldField< PatchField, Type >> &)
void operator= (const Type &)
void operator+= (const FieldField< PatchField, Type > &)
void operator+= (const tmp< FieldField< PatchField, Type >> &)
void operator+= (const Type &)
void operator-= (const FieldField< PatchField, Type > &)
void operator-= (const tmp< FieldField< PatchField, Type >> &)
void operator-= (const Type &)
void operator*= (const FieldField< PatchField, scalar > &)
void operator*= (const tmp< FieldField< PatchField, scalar >> &)
void operator*= (const scalar &)
void operator/= (const FieldField< PatchField, scalar > &)
void operator/= (const tmp< FieldField< PatchField, scalar >> &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from PtrList< PatchField< Type > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< PatchField< Type > > &)
Copy constructor.
PtrList (const PtrList< PatchField< Type > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< PatchField< Type > >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< PatchField< Type > > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< PatchField< Type > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (PatchField< Type > *)
Append an element at the end of the list.
void append (const autoPtr< PatchField< Type > > &)
void append (const tmp< PatchField< Type > > &)
void transfer (PtrList< PatchField< Type > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< PatchField< Type > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< PatchField< Type > > set (const label, PatchField< Type > *)
Set element to given T* and return old element (can be NULL)
autoPtr< PatchField< Type > > set (const label, const autoPtr< PatchField< Type > > &)
Set element to given autoPtr<T> and return old element.
autoPtr< PatchField< Type > > set (const label, const tmp< PatchField< Type > > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< PatchField< Type > > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from FieldField< PatchField, Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Static Public Member Functions inherited from FieldField< PatchField, Type >
static tmp< FieldField< PatchField, Type > > NewCalculatedType (const FieldField< PatchField, Type2 > &ff)
Return a pointer to a new calculatedFvPatchFieldField created on.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from PtrList< PatchField< Type > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Distance calculation for cells with face on a wall. Does not search anything, just takes normal component of distance.
Source files
nearWallDistNoSearch.H
nearWallDistNoSearch.C
Definition at line 52 of file nearWallDistNoSearch.H.
Constructor & Destructor Documentation
nearWallDistNoSearch (const fvMesh & mesh)
Construct from components.
Definition at line 77 of file nearWallDistNoSearch.C.
~nearWallDistNoSearch () virtual
Destructor.
Definition at line 93 of file nearWallDistNoSearch.C.
Member Function Documentation
void correct () virtual
Correct for mesh geom/topo changes.
Definition at line 99 of file nearWallDistNoSearch.C.
References fvMesh::boundary(), polyMesh::changing(), forAll, UPtrList< T >::operator[](), patchi, and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/nearWallDist/nearWallDistNoSearch.H
src/finiteVolume/fvMesh/wallDist/nearWallDist/nearWallDistNoSearch.C