OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NoDispersion< CloudType > Class Template Reference
Place holder for 'none' option.
Public Member Functions
TypeName ("none")
Runtime type information.
NoDispersion (const dictionary &dict, CloudType &owner)
Construct from components.
NoDispersion (const NoDispersion< CloudType > &dm)
Construct copy.
virtual autoPtr< DispersionModel< CloudType > > clone () const
Construct and return a clone.
virtual ~NoDispersion ()
Destructor.
virtual bool active () const
Flag to indicate whether model activates injection model.
virtual vector update (const scalar dt, const label cellI, const vector &U, const vector &Uc, vector &UTurb, scalar &tTurb)
Update (disperse particles)
Public Member Functions inherited from DispersionModel< CloudType >
TypeName ("dispersionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DispersionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
DispersionModel (CloudType &owner)
Construct null from owner.
DispersionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
DispersionModel (const DispersionModel< CloudType > &dm)
Construct copy.
virtual ~DispersionModel ()
Destructor.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from DispersionModel< CloudType >
static autoPtr< DispersionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::NoDispersion< CloudType >
Place holder for 'none' option.
Definition at line 46 of file NoDispersion.H.
Constructor & Destructor Documentation
NoDispersion (const dictionary & dict, CloudType & owner)
Construct from components.
Definition at line 31 of file NoDispersion.C.
NoDispersion (const NoDispersion< CloudType > & dm)
Construct copy.
Definition at line 38 of file NoDispersion.C.
~NoDispersion () virtual
Destructor.
Definition at line 47 of file NoDispersion.C.
Referenced by NoDispersion< CloudType >::clone().
Member Function Documentation
TypeName ("none")
Runtime type information.
virtual autoPtr<DispersionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements DispersionModel< CloudType >.
Definition at line 65 of file NoDispersion.H.
References NoDispersion< CloudType >::active(), U, NoDispersion< CloudType >::update(), and NoDispersion< CloudType >::~NoDispersion().
bool active () const virtual
Flag to indicate whether model activates injection model.
Reimplemented from subModelBase.
Definition at line 54 of file NoDispersion.C.
References NoDispersion< CloudType >::update().
Referenced by NoDispersion< CloudType >::clone().
Foam::vector update (const scalar dt, const label cellI, const vector & U, const vector & Uc, vector & UTurb, scalar & tTurb) virtual
Update (disperse particles)
Implements DispersionModel< CloudType >.
Definition at line 62 of file NoDispersion.C.
Referenced by NoDispersion< CloudType >::active(), and NoDispersion< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/DispersionModel/NoDispersion/NoDispersion.H
src/lagrangian/intermediate/submodels/Kinematic/DispersionModel/NoDispersion/NoDispersion.C