OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NonInertialFrameForce< CloudType > Class Template Reference
Calculates particle non-inertial reference frame force. Variable names as from Landau and Lifshitz, Mechanics, 3rd Ed, p126-129.
Public Member Functions
TypeName ("nonInertialFrame")
Runtime type information.
NonInertialFrameForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
Construct from mesh.
NonInertialFrameForce (const NonInertialFrameForce &niff)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~NonInertialFrameForce ()
Destructor.
const vector & W () const
Return the linear acceleration of the reference frame.
const vector & omega () const
Return the angular velocity of the reference frame.
const vector & omegaDot () const
Return the angular acceleration of the reference frame.
const vector & centreOfRotation () const
Return the centre of rotation of the reference frame.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::NonInertialFrameForce< CloudType >
Calculates particle non-inertial reference frame force. Variable names as from Landau and Lifshitz, Mechanics, 3rd Ed, p126-129.
Source files
NonInertialFrameForce.H
NonInertialFrameForce.C
Definition at line 52 of file NonInertialFrameForce.H.
Constructor & Destructor Documentation
NonInertialFrameForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Construct from mesh.
Definition at line 33 of file NonInertialFrameForce.C.
NonInertialFrameForce (const NonInertialFrameForce< CloudType > & niff)
Construct copy.
Definition at line 81 of file NonInertialFrameForce.C.
~NonInertialFrameForce () virtual
Destructor.
Definition at line 100 of file NonInertialFrameForce.C.
Referenced by NonInertialFrameForce< CloudType >::clone().
Member Function Documentation
TypeName ("nonInertialFrame")
Runtime type information.
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from ParticleForce< CloudType >.
Definition at line 103 of file NonInertialFrameForce.H.
References NonInertialFrameForce< CloudType >::cacheFields(), NonInertialFrameForce< CloudType >::calcNonCoupled(), NonInertialFrameForce< CloudType >::centreOfRotation(), NonInertialFrameForce< CloudType >::omega(), NonInertialFrameForce< CloudType >::omegaDot(), p, Foam::Re(), NonInertialFrameForce< CloudType >::W(), and NonInertialFrameForce< CloudType >::~NonInertialFrameForce().
const Foam::vector & W () const inline
Return the linear acceleration of the reference frame.
Definition at line 29 of file NonInertialFrameForceI.H.
Referenced by NonInertialFrameForce< CloudType >::clone().
const Foam::vector & omega () const inline
Return the angular velocity of the reference frame.
Definition at line 36 of file NonInertialFrameForceI.H.
Referenced by NonInertialFrameForce< CloudType >::clone().
const Foam::vector & omegaDot () const inline
Return the angular acceleration of the reference frame.
Definition at line 44 of file NonInertialFrameForceI.H.
Referenced by NonInertialFrameForce< CloudType >::clone().
const Foam::vector & centreOfRotation () const inline
Return the centre of rotation of the reference frame.
Definition at line 52 of file NonInertialFrameForceI.H.
Referenced by NonInertialFrameForce< CloudType >::clone().
void cacheFields (const bool store) virtual
Cache fields.
Reimplemented from ParticleForce< CloudType >.
Definition at line 107 of file NonInertialFrameForce.C.
References NonInertialFrameForce< CloudType >::calcNonCoupled(), mesh, and dimensioned< Type >::value().
Referenced by NonInertialFrameForce< CloudType >::clone().
Foam::forceSuSp calcNonCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the non-coupled force.
Reimplemented from ParticleForce< CloudType >.
Definition at line 181 of file NonInertialFrameForce.C.
References forceSuSp::Su().
Referenced by NonInertialFrameForce< CloudType >::cacheFields(), and NonInertialFrameForce< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/NonInertialFrame/NonInertialFrameForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/NonInertialFrame/NonInertialFrameForce.C
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/NonInertialFrame/NonInertialFrameForceI.H