OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
NicenoKEqn< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
One-equation SGS model for the continuous phase in a two-phase system including bubble-generated turbulence.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kEqn< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel >::alphaField alphaField
typedef LESModel< BasicTurbulenceModel >::rhoField rhoField
typedef LESModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel >::alphaField alphaField
typedef LESModel< BasicTurbulenceModel >::rhoField rhoField
typedef LESModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("NicenoKEqn")
Runtime type information.
NicenoKEqn (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~NicenoKEqn ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
Public Member Functions inherited from kEqn< BasicTurbulenceModel >
TypeName ("kEqn")
Runtime type information.
kEqn (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Constructor from components.
virtual ~kEqn ()
Destructor.
virtual tmp< volScalarField > k () const
Return SGS kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return sub-grid disipation rate.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
virtual void correct ()
Correct eddy-Viscosity and related properties.
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~LESeddyViscosity ()
Destructor.
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual void correctNut ()
tmp< volScalarField > bubbleG () const
tmp< volScalarField > phaseTransferCoeff () const
virtual tmp< fvScalarMatrix > kSource () const
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar alphaInversion_
dimensionedScalar Cp_
dimensionedScalar Cmub_
Protected Attributes inherited from kEqn< BasicTurbulenceModel >
volScalarField k_
dimensionedScalar Ck_
Protected Attributes inherited from LESeddyViscosity< BasicTurbulenceModel >
dimensionedScalar Ce_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::NicenoKEqn< BasicTurbulenceModel >
One-equation SGS model for the continuous phase in a two-phase system including bubble-generated turbulence.
Reference:
    Niceno, B., Dhotre, M. T., & Deen, N. G. (2008).
    One-equation sub-grid scale (SGS) modelling for
    EulerEuler large eddy simulation (EELES) of dispersed bubbly flow.
    Chemical Engineering Science, 63(15), 3923-3931.
The default model coefficients are:
    NicenoKEqnCoeffs
    {
        Ck              0.094;
        Ce              1.048;
        alphaInversion  0.3;
        Cp              Ck;
        Cmub            0.6;
    }
Source files
NicenoKEqn.H
NicenoKEqn.C
Definition at line 75 of file NicenoKEqn.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 122 of file NicenoKEqn.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 123 of file NicenoKEqn.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 124 of file NicenoKEqn.H.
Constructor & Destructor Documentation
NicenoKEqn (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 41 of file NicenoKEqn.C.
virtual ~NicenoKEqn () inline virtual
Destructor.
Definition at line 148 of file NicenoKEqn.H.
References NicenoKEqn< BasicTurbulenceModel >::read().
Member Function Documentation
void correctNut () protected virtual
Reimplemented from kEqn< BasicTurbulenceModel >.
Definition at line 156 of file NicenoKEqn.C.
References optionList::correct(), delta, Foam::mag(), options::New(), and Foam::sqrt().
tmp< volScalarField > bubbleG () const protected
Definition at line 174 of file NicenoKEqn.C.
References twoPhaseSystem::drag(), fluid, dragModel::K(), Foam::mag(), twoPhaseSystem::otherPhase(), and Foam::sqr().
tmp< volScalarField > phaseTransferCoeff () const protected
Definition at line 197 of file NicenoKEqn.C.
References delta, TimeState::deltaT(), turbulenceModel::k(), Foam::max(), Foam::min(), Foam::sqrt(), and IOobject::time().
tmp< fvScalarMatrix > kSource () const protected virtual
Reimplemented from kEqn< BasicTurbulenceModel >.
Definition at line 219 of file NicenoKEqn.C.
References Foam::fvm::Sp().
TypeName ("NicenoKEqn< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from kEqn< BasicTurbulenceModel >.
Definition at line 106 of file NicenoKEqn.C.
References IOobject::db(), fluid, IOobject::groupName(), objectRegistry::lookupObject(), twoPhaseSystem::otherPhase(), and turbulenceModel::propertiesName.
Referenced by NicenoKEqn< BasicTurbulenceModel >::~NicenoKEqn().
Member Data Documentation
dimensionedScalar alphaInversion_ protected
Definition at line 107 of file NicenoKEqn.H.
dimensionedScalar Cp_ protected
Definition at line 108 of file NicenoKEqn.H.
dimensionedScalar Cmub_ protected
Definition at line 109 of file NicenoKEqn.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/LES/Niceno/NicenoKEqn.H
src/TurbulenceModels/phaseCompressible/LES/Niceno/NicenoKEqn.C