OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ode< ChemistryModel > Class Template Reference
An ODE solver for chemistry.
Public Member Functions
TypeName ("ode")
Runtime type information.
ode (const fvMesh &mesh, const word &phaseName)
Construct from mesh and phase name.
virtual ~ode ()
Destructor.
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const
Update the concentrations and return the chemical time.
Public Member Functions inherited from chemistrySolver< ChemistryModel >
chemistrySolver (const fvMesh &mesh, const word &phaseName)
Construct from components and phase name.
virtual ~chemistrySolver ()
Destructor.
Detailed Description
template<class ChemistryModel>
class Foam::ode< ChemistryModel >
An ODE solver for chemistry.
Source files
ode.H
ode.C
Definition at line 50 of file ode.H.
Constructor & Destructor Documentation
ode (const fvMesh & mesh, const word & phaseName)
Construct from mesh and phase name.
Definition at line 33 of file ode.C.
~ode () virtual
Destructor.
Definition at line 48 of file ode.C.
References ode< ChemistryModel >::solve().
Member Function Documentation
TypeName ("ode< ChemistryModel >")
Runtime type information.
void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const virtual
Update the concentrations and return the chemical time.
Implements chemistrySolver< ChemistryModel >.
Definition at line 56 of file ode.C.
References Foam::max(), nSpecie, p, and T.
Referenced by ode< ChemistryModel >::~ode().
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistrySolver/ode/ode.H
src/thermophysicalModels/chemistryModel/chemistrySolver/ode/ode.C