OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
OBJedgeFormat Class Reference
Provide a means of reading/writing Alias/Wavefront OBJ format.
Public Member Functions
OBJedgeFormat (const fileName &)
Construct from file name.
virtual ~OBJedgeFormat ()
Destructor.
virtual bool read (const fileName &)
Read from file.
virtual void write (const fileName &name) const
Write object file.
Public Member Functions inherited from edgeMesh
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const pointField &, const edgeList &)
Construct from components.
edgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges).
edgeMesh (const edgeMesh &)
Construct as copy.
edgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
edgeMesh (Istream &)
Construct from Istream.
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< edgeMesh > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void clear ()
Clear all storage.
virtual void reset (const Xfer< pointField > &points, const Xfer< edgeList > &edges)
Reset primitive data (points, edges)
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
void mergeEdges ()
Merge similar edges.
virtual void writeStats (Ostream &) const
void operator= (const edgeMesh &)
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Static Public Member Functions
static autoPtr< edgeMesh > New (const fileName &name)
Read file and return surface.
static void write (const fileName &, const edgeMesh &)
Write surface mesh components by proxy.
Static Public Member Functions inherited from edgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const edgeMesh &)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Additional Inherited Members
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
Provide a means of reading/writing Alias/Wavefront OBJ format.
Does not handle negative vertex indices.
Source files
OBJedgeFormat.H
OBJedgeFormat.C
Definition at line 55 of file OBJedgeFormat.H.
Constructor & Destructor Documentation
OBJedgeFormat (const fileName & filename)
Construct from file name.
Definition at line 37 of file OBJedgeFormat.C.
References Foam::read().
virtual ~OBJedgeFormat () inline virtual
Destructor.
Definition at line 96 of file OBJedgeFormat.H.
Member Function Documentation
static autoPtr<edgeMesh> New (const fileName & name) inline static
Read file and return surface.
Definition at line 86 of file OBJedgeFormat.H.
void write (const fileName & filename, const edgeMesh & mesh) static
Write surface mesh components by proxy.
Definition at line 233 of file OBJedgeFormat.C.
References clock::dateTime(), Foam::e, edgeMesh::edges(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, IOstream::good(), fileName::lessExt(), OFstream::name(), fileName::name(), Foam::nl, p, edgeMesh::points(), List< T >::size(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by OBJedgeFormat::write().
bool read (const fileName & filename) virtual
Read from file.
Reimplemented from edgeMesh.
Definition at line 97 of file OBJedgeFormat.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), clear(), Foam::e, Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, IOstream::good(), i, DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::size(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer(), x, and y.
virtual void write (const fileName & name) const inline virtual
Write object file.
Reimplemented from edgeMesh.
Definition at line 109 of file OBJedgeFormat.H.
References OBJedgeFormat::write().
The documentation for this class was generated from the following files:
src/edgeMesh/edgeMeshFormats/obj/OBJedgeFormat.H
src/edgeMesh/edgeMeshFormats/obj/OBJedgeFormat.C