OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
OutputFilterFunctionObject< OutputFilter > Class Template Reference
A functionObject wrapper around OutputFilter to allow them to be created via the functions entry within controlDict.
Public Member Functions
TypeName (OutputFilter::typeName_())
Runtime type information.
OutputFilterFunctionObject (const word &name, const Time &, const dictionary &)
Construct from components.
const Time & time () const
Return time database.
const dictionary & dict () const
Return the input dictionary.
const word & regionName () const
Return the region name.
const outputFilterOutputControl & outputControl () const
Return the output control object.
const OutputFilter & outputFilter () const
Return the output filter.
virtual bool execute (const bool forceWrite=false)
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool read (const dictionary &)
Read and set the function object if its data have changed.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
virtual const word & name () const
Name.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
template<class OutputFilter>
class Foam::OutputFilterFunctionObject< OutputFilter >
A functionObject wrapper around OutputFilter to allow them to be created via the functions entry within controlDict.
Note
Since the timeIndex is used directly from Foam::Time, it is unaffected by user-time conversions. For example, Foam::engineTime might cause writeInterval to be degrees crank angle, but the functionObject execution interval would still be in timestep.
Source files
OutputFilterFunctionObject.H
OutputFilterFunctionObject.C
Definition at line 58 of file OutputFilterFunctionObject.H.
Constructor & Destructor Documentation
OutputFilterFunctionObject (const word & name, const Time & t, const dictionary & dict)
Construct from components.
Definition at line 55 of file OutputFilterFunctionObject.C.
References OutputFilterFunctionObject< OutputFilter >::execute().
Member Function Documentation
TypeName (OutputFilter::typeName_())
Runtime type information.
const Foam::Time & time () const inline
Return time database.
Definition at line 30 of file OutputFilterFunctionObjectI.H.
const Foam::dictionary & dict () const inline
Return the input dictionary.
Definition at line 38 of file OutputFilterFunctionObjectI.H.
const Foam::word & regionName () const inline
Return the region name.
Definition at line 46 of file OutputFilterFunctionObjectI.H.
const Foam::outputFilterOutputControl & outputControl () const inline
Return the output control object.
Definition at line 54 of file OutputFilterFunctionObjectI.H.
const OutputFilter & outputFilter () const inline
Return the output filter.
Definition at line 62 of file OutputFilterFunctionObjectI.H.
bool execute (const bool forceWrite = false) virtual
Called at each ++ or += of the time-loop.
forceWrite overrides the usual outputControl behaviour and forces writing (used in post-processing mode)
Implements functionObject.
Definition at line 88 of file OutputFilterFunctionObject.C.
Referenced by OutputFilterFunctionObject< OutputFilter >::OutputFilterFunctionObject().
bool end () virtual
Called when Time::run() determines that the time-loop exits.
Reimplemented from functionObject.
Definition at line 110 of file OutputFilterFunctionObject.C.
bool timeSet () virtual
Called when time was set at the end of the Time::operator++.
Reimplemented from functionObject.
Definition at line 124 of file OutputFilterFunctionObject.C.
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Reimplemented from functionObject.
Definition at line 136 of file OutputFilterFunctionObject.C.
References Foam::max(), and OutputFilterFunctionObject< OutputFilter >::read().
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Implements functionObject.
Definition at line 183 of file OutputFilterFunctionObject.C.
References dict, and OutputFilterFunctionObject< OutputFilter >::updateMesh().
Referenced by OutputFilterFunctionObject< OutputFilter >::adjustTimeStep().
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Implements functionObject.
Definition at line 206 of file OutputFilterFunctionObject.C.
References mapPolyMesh::mesh(), OutputFilterFunctionObject< OutputFilter >::movePoints(), and IOobject::name().
Referenced by OutputFilterFunctionObject< OutputFilter >::read().
void movePoints (const polyMesh & mesh) virtual
Update for changes of mesh.
Implements functionObject.
Definition at line 219 of file OutputFilterFunctionObject.C.
References IOobject::name().
Referenced by OutputFilterFunctionObject< OutputFilter >::updateMesh().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/OutputFilterFunctionObject/OutputFilterFunctionObject.H
src/OpenFOAM/db/functionObjects/OutputFilterFunctionObject/OutputFilterFunctionObject.C
src/OpenFOAM/db/functionObjects/OutputFilterFunctionObject/OutputFilterFunctionObjectI.H