OpenFOAM: nutkFilmWallFunctionFvPatchScalarField Class Reference
nutkFilmWallFunctionFvPatchScalarField Class Reference
Region boundary conditions » Surface film boundary conditionsCompressible turbulence » Compressible Turbulence BCs » | Compressible turbulence wall functions
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy, for use with surface film models.
Public Member Functions
TypeName ("nutkFilmWallFunction")
Runtime type information.
nutkFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutkFilmWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from nutkWallFunctionFvPatchScalarField
TypeName ("nutkWallFunction")
Runtime type information.
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &)
Construct as copy.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcNut () const
Calculate the turbulence viscosity.
virtual tmp< scalarField > calcUTau (const scalarField &magGradU) const
Calculate the friction velocity.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
scalar B_
B Coefficient (default = 5.5)
scalar yPlusCrit_
y+ value for laminar -> turbulent transition (default = 11.05)
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent viscosity condition when using wall functions, based on turbulence kinetic energy, for use with surface film models.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            nutkFilmWallFunction;
    value           uniform 0;
}
See also
Foam::nutkWallFunctionFvPatchScalarField
Source files
nutkFilmWallFunctionFvPatchScalarField.H
nutkFilmWallFunctionFvPatchScalarField.C
Definition at line 70 of file nutkFilmWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutkFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 155 of file nutkFilmWallFunctionFvPatchScalarField.C.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::clone(), and nutkFilmWallFunctionFvPatchScalarField::nutkFilmWallFunctionFvPatchScalarField().
nutkFilmWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 181 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::nutkFilmWallFunctionFvPatchScalarField().
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutkFilmWallFunctionFvPatchScalarField onto a new patch
Definition at line 167 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::nutkFilmWallFunctionFvPatchScalarField().
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 194 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::nutkFilmWallFunctionFvPatchScalarField().
nutkFilmWallFunctionFvPatchScalarField (const nutkFilmWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 205 of file nutkFilmWallFunctionFvPatchScalarField.C.
Member Function Documentation
tmp< scalarField > calcNut () const protected virtual
Calculate the turbulence viscosity.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 126 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::calcUTau(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), Foam::max(), nutkFilmWallFunctionFvPatchScalarField::nutkFilmWallFunctionFvPatchScalarField(), patchi, turbulenceModel::propertiesName, and Foam::sqr().
tmp< scalarField > calcUTau (const scalarField & magGradU) const protected virtual
Calculate the friction velocity.
Definition at line 47 of file nutkFilmWallFunctionFvPatchScalarField.C.
References Foam::exp(), forAll, objectRegistry::foundObject(), Foam::constant::atomic::group, IOobject::groupName(), k, Foam::max(), Foam::min(), patchi, Foam::pow(), turbulenceModel::propertiesName, tmp< T >::ref(), Foam::sqrt(), regionModel::time(), uTau, y, and yPlus.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcNut(), and nutkFilmWallFunctionFvPatchScalarField::yPlus().
TypeName ("nutkFilmWallFunction")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 135 of file nutkFilmWallFunctionFvPatchScalarField.H.
References nutkFilmWallFunctionFvPatchScalarField::nutkFilmWallFunctionFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 152 of file nutkFilmWallFunctionFvPatchScalarField.H.
References nutkFilmWallFunctionFvPatchScalarField::nutkFilmWallFunctionFvPatchScalarField(), nutkFilmWallFunctionFvPatchScalarField::write(), and nutkFilmWallFunctionFvPatchScalarField::yPlus().
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 218 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::calcUTau(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), patchi, turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), and y.
Referenced by nutkFilmWallFunctionFvPatchScalarField::clone().
void write (Ostream & os) const virtual
Write.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 240 of file nutkFilmWallFunctionFvPatchScalarField.C.
References nutkFilmWallFunctionFvPatchScalarField::B_, token::END_STATEMENT, Foam::compressible::RASModels::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), Ostream::writeKeyword(), nutWallFunctionFvPatchScalarField::writeLocalEntries(), and nutkFilmWallFunctionFvPatchScalarField::yPlusCrit_.
Referenced by nutkFilmWallFunctionFvPatchScalarField::clone().
Member Data Documentation
scalar B_ protected
B Coefficient (default = 5.5)
Definition at line 79 of file nutkFilmWallFunctionFvPatchScalarField.H.
Referenced by nutkFilmWallFunctionFvPatchScalarField::write().
scalar yPlusCrit_ protected
y+ value for laminar -> turbulent transition (default = 11.05)
Definition at line 82 of file nutkFilmWallFunctionFvPatchScalarField.H.
Referenced by nutkFilmWallFunctionFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/nutkFilmWallFunction/nutkFilmWallFunctionFvPatchScalarField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/wallFunctions/nutkFilmWallFunction/nutkFilmWallFunctionFvPatchScalarField.C