OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
orientation Class Reference
Orientation constraint: fixed in global space.
Public Member Functions
TypeName ("orientation")
Runtime type information.
orientation (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const
Construct and return a clone.
virtual ~orientation ()
Destructor.
virtual void constrainTranslation (pointConstraint &) const
Apply and accumulate translational constraints.
virtual void constrainRotation (pointConstraint &) const
Apply and accumulate rotational constraints.
virtual bool read (const dictionary &sDoFRBMCCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
TypeName ("sixDoFRigidBodyMotionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from the sDoFRBMCDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionConstraint ()
Destructor.
const word & name () const
Return the name.
virtual void setCentreOfRotation (point &) const
Set the centre of rotation if not the centre of mass.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
static autoPtr< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Select constructed from the sDoFRBMCDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionConstraint
word name_
Name of the constraint.
dictionary sDoFRBMCCoeffs_
Constraint model specific coefficient dictionary.
const sixDoFRigidBodyMotion & motion_
Reference to the body motion.
Detailed Description
Orientation constraint: fixed in global space.
Source files
sixDoFRigidBodyMotionOrientationConstraint.H
sixDoFRigidBodyMotionOrientationConstraint.C
Definition at line 52 of file sixDoFRigidBodyMotionOrientationConstraint.H.
Constructor & Destructor Documentation
orientation (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Construct from components.
Definition at line 51 of file sixDoFRigidBodyMotionOrientationConstraint.C.
References Foam::read().
Referenced by orientation::clone().
~orientation () virtual
Destructor.
Definition at line 65 of file sixDoFRigidBodyMotionOrientationConstraint.C.
References orientation::constrainTranslation().
Referenced by orientation::clone().
Member Function Documentation
TypeName ("orientation")
Runtime type information.
virtual autoPtr<sixDoFRigidBodyMotionConstraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 74 of file sixDoFRigidBodyMotionOrientationConstraint.H.
References orientation::constrainRotation(), orientation::constrainTranslation(), orientation::orientation(), orientation::read(), orientation::write(), and orientation::~orientation().
void constrainTranslation (pointConstraint & pc) const virtual
Apply and accumulate translational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 73 of file sixDoFRigidBodyMotionOrientationConstraint.C.
References orientation::constrainRotation().
Referenced by orientation::clone(), and orientation::~orientation().
void constrainRotation (pointConstraint & pc) const virtual
Apply and accumulate rotational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 81 of file sixDoFRigidBodyMotionOrientationConstraint.C.
References pointConstraint::combine(), orientation::read(), and Vector< scalar >::zero.
Referenced by orientation::clone(), and orientation::constrainTranslation().
bool read (const dictionary & sDoFRBMCCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 90 of file sixDoFRigidBodyMotionOrientationConstraint.C.
References sixDoFRigidBodyMotionConstraint::read(), and orientation::write().
Referenced by orientation::clone(), and orientation::constrainRotation().
void write (Ostream & os) const virtual
Write.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 101 of file sixDoFRigidBodyMotionOrientationConstraint.C.
Referenced by orientation::clone(), and orientation::read().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/orientation/sixDoFRigidBodyMotionOrientationConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/orientation/sixDoFRigidBodyMotionOrientationConstraint.C