OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
omegaWallFunctionFvPatchScalarField Class Reference
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a wall function constraint on turbulnce specific dissipation, omega. The values are computed using:
Public Member Functions
TypeName ("omegaWallFunction")
Runtime type information.
omegaWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
omegaWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
omegaWallFunctionFvPatchScalarField (const omegaWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
omegaWallFunctionFvPatchScalarField (const omegaWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
omegaWallFunctionFvPatchScalarField (const omegaWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
scalarField & G (bool init=false)
Return non-const access to the master's G field.
scalarField & omega (bool init=false)
Return non-const access to the master's omega field.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void updateCoeffs (const scalarField &weights)
Update the coefficients associated with the patch field.
virtual void manipulateMatrix (fvMatrix< scalar > &matrix)
Manipulate matrix.
virtual void manipulateMatrix (fvMatrix< scalar > &matrix, const scalarField &weights)
Manipulate matrix with given weights.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from fixedValueFvPatchField< scalar >
TypeName ("fixedValue")
Runtime type information.
fixedValueFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fixedValueFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const scalar &value)
Construct from patch, internal field and value.
fixedValueFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedValueFvPatchField (const fixedValueFvPatchField< scalar > &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fixedValueFvPatchField<Type>
fixedValueFvPatchField (const fixedValueFvPatchField< scalar > &)
Construct as copy.
fixedValueFvPatchField (const fixedValueFvPatchField< scalar > &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool assignable () const
Return false: this patch field is not altered by assignment.
virtual tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< scalar > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< scalar > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the.
virtual void operator= (const UList< scalar > &)
virtual void operator= (const fvPatchField< scalar > &)
virtual void operator= (const scalar &)
virtual void operator+= (const fvPatchField< scalar > &)
virtual void operator+= (const Field< scalar > &)
virtual void operator+= (const scalar &)
virtual void operator-= (const fvPatchField< scalar > &)
virtual void operator-= (const Field< scalar > &)
virtual void operator-= (const scalar &)
virtual void operator*= (const fvPatchField< scalar > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator*= (const scalar)
virtual void operator/= (const fvPatchField< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator/= (const scalar)
Public Member Functions inherited from fvPatchField< Type >
TypeName ("fvPatchField")
Runtime type information.
declareRunTimeSelectionTable (tmp, fvPatchField, patch,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvPatchField, patchMapper,(const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict),(p, iF, dict))
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Type &value)
Construct from patch, internal field and value.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const word &patchType)
Construct from patch and internal field and patch type.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &, const bool valueRequired=false)
Construct from patch, internal field and dictionary.
fvPatchField (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fvPatchField onto a new patch.
fvPatchField (const fvPatchField< Type > &)
Construct as copy.
fvPatchField (const fvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< Type > > clone (const DimensionedField< Type, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual ~fvPatchField ()
Destructor.
virtual bool coupled () const
Return true if this patch field is coupled.
const objectRegistry & db () const
Return local objectRegistry.
const fvPatch & patch () const
Return patch.
const DimensionedField< Type, volMesh > & dimensionedInternalField () const
Return dimensioned internal field reference.
const Field< Type > & internalField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
bool updated () const
Return true if the boundary condition has already been updated.
bool manipulatedMatrix () const
Return true if the matrix has already been manipulated.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchField< Type > &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual tmp< Field< Type > > snGrad () const
Return patch-normal gradient.
virtual tmp< Field< Type > > snGrad (const scalarField &deltaCoeffs) const
Return patch-normal gradient for coupled-patches.
virtual tmp< Field< Type > > patchInternalField () const
Return internal field next to patch as patch field.
virtual void patchInternalField (Field< Type > &) const
Return internal field next to patch as patch field.
virtual tmp< Field< Type > > patchNeighbourField () const
Return patchField on the opposite patch of a coupled patch.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise the evaluation of the patch field.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field, sets Updated to false.
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< Field< scalar >> &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< Field< scalar >> &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs (const scalarField &deltaCoeffs) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs (const scalarField &deltaCoeffs) const
Return the matrix source coefficients corresponding to the.
virtual void manipulateMatrix (fvMatrix< Type > &matrix)
Manipulate matrix.
virtual void manipulateMatrix (fvMatrix< Type > &matrix, const scalarField &weights)
Manipulate matrix with given weights.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
void check (const fvPatchField< Type > &) const
Check fvPatchField<Type> against given fvPatchField<Type>
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvPatchField< Type > &)
virtual void operator+= (const fvPatchField< Type > &)
virtual void operator-= (const fvPatchField< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator== (const fvPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &pf)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map)
Map from the given tmp field.
void autoMap (const FieldMapper &map)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< Type >
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< Type > &)
Assign elements to those from UList.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
void operator= (const Type &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Protected Member Functions
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
virtual void setMaster ()
Set the master patch - master is responsible for updating all.
virtual void createAveragingWeights ()
Create the averaging weights for cells which are bounded by.
virtual omegaWallFunctionFvPatchScalarField & omegaPatch (const label patchi)
Helper function to return non-const access to an omega patch.
virtual void calculateTurbulenceFields (const turbulenceModel &turbulence, scalarField &G0, scalarField &omega0)
Main driver to calculate the turbulence fields.
virtual void calculate (const turbulenceModel &turbulence, const List< scalar > &cornerWeights, const fvPatch &patch, scalarField &G, scalarField &omega)
Calculate the omega and G.
virtual label & master ()
Return non-const access to the master patch ID.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Attributes
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar beta1_
beta1 coefficient
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
scalarField G_
Local copy of turbulence G field.
scalarField omega_
Local copy of turbulence omega field.
bool initialised_
Initialised flag.
label master_
Master patch ID.
List< List< scalar > > cornerWeights_
List of averaging corner weights.
Static Protected Attributes
static scalar tolerance_ = 1e-5
Tolerance used in weighted calculations.
Additional Inherited Members
Public Types inherited from fvPatchField< Type >
typedef fvPatch Patch
typedef calculatedFvPatchField< Type > Calculated
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from fvPatchField< Type >
static tmp< fvPatchField< Type > > New (const word &, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const word &, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static tmp< fvPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatch &)
Return a pointer to a new calculatedFvPatchField created on.
template<class Type2 >
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &)
Return a pointer to a new calculatedFvPatchField created on.
static const word & calculatedType ()
Return the type of the calculated for of fvPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes inherited from fvPatchField< Type >
static int disallowGenericFvPatchField
Debug switch to disallow the use of genericFvPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Detailed Description
This boundary condition provides a wall function constraint on turbulnce specific dissipation, omega. The values are computed using:
where
= omega in viscous region
= omega in logarithmic region
Model described by Eq.(15) of:
        Menter, F., Esch, T.
        "Elements of Industrial Heat Transfer Prediction"
        16th Brazilian Congress of Mechanical Engineering (COBEM),
        Nov. 2001
Patch usage
Property Description Required Default value
Cmu model coefficient no 0.09
kappa Von Karman constant no 0.41
E model coefficient no 9.8
beta1 model coefficient no 0.075
Example of the boundary condition specification:
    myPatch
    {
        type            omegaWallFunction;
    }
Source files
omegaWallFunctionFvPatchScalarField.H
omegaWallFunctionFvPatchScalarField.C
Definition at line 124 of file omegaWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
omegaWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 261 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::checkType().
Referenced by omegaWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::clone(), omegaWallFunctionFvPatchScalarField::master(), and omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField().
omegaWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 307 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::checkType(), omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField(), fvPatchField< Type >::operator==(), and fvPatchField< Type >::patchInternalField().
omegaWallFunctionFvPatchScalarField (const omegaWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
omegaWallFunctionFvPatchScalarField onto a new patch
Definition at line 283 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::checkType(), and omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField().
omegaWallFunctionFvPatchScalarField (const omegaWallFunctionFvPatchScalarField & owfpsf)
Construct as copy.
Definition at line 333 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::checkType(), and omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField().
omegaWallFunctionFvPatchScalarField (const omegaWallFunctionFvPatchScalarField & owfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 354 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::checkType().
Member Function Documentation
void checkType () protected virtual
Check the type of the patch.
Definition at line 46 of file omegaWallFunctionFvPatchScalarField.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, fvPatch::name(), Foam::nl, and fvPatchField< Type >::patch().
Referenced by omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField().
void writeLocalEntries (Ostream & os) const protected virtual
Write local wall function variables.
Definition at line 60 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::beta1_, omegaWallFunctionFvPatchScalarField::Cmu_, omegaWallFunctionFvPatchScalarField::E_, token::END_STATEMENT, omegaWallFunctionFvPatchScalarField::kappa_, Foam::nl, and Ostream::writeKeyword().
Referenced by omegaWallFunctionFvPatchScalarField::write().
void setMaster () protected virtual
Set the master patch - master is responsible for updating all.
wall function patches
Definition at line 69 of file omegaWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatchField< Type >::dimensionedInternalField(), forAll, omegaWallFunctionFvPatchScalarField::master(), omegaWallFunctionFvPatchScalarField::master_, omegaWallFunctionFvPatchScalarField::omega(), omegaWallFunctionFvPatchScalarField::omegaPatch(), and patchi.
Referenced by omegaWallFunctionFvPatchScalarField::updateCoeffs().
void createAveragingWeights () protected virtual
Create the averaging weights for cells which are bounded by.
multiple wall function faces
Definition at line 99 of file omegaWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::changing(), omegaWallFunctionFvPatchScalarField::cornerWeights_, fvPatchField< Type >::dimensionedInternalField(), Foam::dimless, forAll, omegaWallFunctionFvPatchScalarField::G_, omegaWallFunctionFvPatchScalarField::initialised_, mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, omegaWallFunctionFvPatchScalarField::omega(), omegaWallFunctionFvPatchScalarField::omega_, patchi, fvPatchField< Type >::patchInternalField(), List< T >::setSize(), List< Type >::size(), fvMesh::time(), and Time::timeName().
Referenced by omegaWallFunctionFvPatchScalarField::updateCoeffs().
omegaWallFunctionFvPatchScalarField & omegaPatch (const label patchi) protected virtual
Helper function to return non-const access to an omega patch.
Definition at line 160 of file omegaWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), omegaWallFunctionFvPatchScalarField::calculateTurbulenceFields(), fvPatchField< Type >::dimensionedInternalField(), omegaWallFunctionFvPatchScalarField::omega(), and patchi.
Referenced by omegaWallFunctionFvPatchScalarField::calculateTurbulenceFields(), omegaWallFunctionFvPatchScalarField::G(), omegaWallFunctionFvPatchScalarField::omega(), and omegaWallFunctionFvPatchScalarField::setMaster().
void calculateTurbulenceFields (const turbulenceModel & turbulence, scalarField & G0, scalarField & omega0) protected virtual
Main driver to calculate the turbulence fields.
Definition at line 175 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::cornerWeights_, UList< Type >::empty(), fvPatch::faceCells(), forAll, Foam::constant::electromagnetic::G0, omegaWallFunctionFvPatchScalarField::omegaPatch(), fvPatchField< Type >::patch(), and patchi.
Referenced by omegaWallFunctionFvPatchScalarField::omegaPatch(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
void calculate (const turbulenceModel & turbulence, const List< scalar > & cornerWeights, const fvPatch & patch, scalarField & G, scalarField & omega) protected virtual
Calculate the omega and G.
Definition at line 208 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::beta1_, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), omegaWallFunctionFvPatchScalarField::Cmu_, fvPatch::faceCells(), forAll, fvPatch::index(), k, turbulenceModel::k(), omegaWallFunctionFvPatchScalarField::kappa_, Foam::mag(), turbulenceModel::nu(), turbulenceModel::nut(), omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField(), patchi, Foam::pow025(), fvPatchField< Type >::snGrad(), Foam::sqr(), Foam::sqrt(), turbulenceModel::U(), y, and turbulenceModel::y().
Referenced by omegaWallFunctionFvPatchScalarField::calculateTurbulenceFields().
virtual label& master () inline protected virtual
Return non-const access to the master patch ID.
Definition at line 207 of file omegaWallFunctionFvPatchScalarField.H.
References omegaWallFunctionFvPatchScalarField::master_, omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField(), and omegaWallFunctionFvPatchScalarField::TypeName().
Referenced by omegaWallFunctionFvPatchScalarField::setMaster().
TypeName ("omegaWallFunction")
Runtime type information.
Referenced by omegaWallFunctionFvPatchScalarField::master().
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from fixedValueFvPatchField< scalar >.
Definition at line 254 of file omegaWallFunctionFvPatchScalarField.H.
References omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from fixedValueFvPatchField< scalar >.
Definition at line 271 of file omegaWallFunctionFvPatchScalarField.H.
References omegaWallFunctionFvPatchScalarField::G(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::omega(), omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), and omegaWallFunctionFvPatchScalarField::write().
scalarField & G (bool init = false)
Return non-const access to the master's G field.
Definition at line 377 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::G(), omegaWallFunctionFvPatchScalarField::G_, omegaWallFunctionFvPatchScalarField::master_, omegaWallFunctionFvPatchScalarField::omegaPatch(), and fvPatchField< Type >::patch().
Referenced by omegaWallFunctionFvPatchScalarField::clone(), omegaWallFunctionFvPatchScalarField::G(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
scalarField & omega (bool init = false)
Return non-const access to the master's omega field.
Definition at line 393 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::master_, omegaWallFunctionFvPatchScalarField::omega(), omegaWallFunctionFvPatchScalarField::omega_, omegaWallFunctionFvPatchScalarField::omegaPatch(), and fvPatchField< Type >::patch().
Referenced by omegaWallFunctionFvPatchScalarField::clone(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::omega(), omegaWallFunctionFvPatchScalarField::omegaPatch(), omegaWallFunctionFvPatchScalarField::setMaster(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from fvPatchField< Type >.
Definition at line 409 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::calculateTurbulenceFields(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), fvPatchField< Type >::db(), fvPatchField< Type >::dimensionedInternalField(), fvPatch::faceCells(), forAll, omegaWallFunctionFvPatchScalarField::G(), turbulenceModel::GName(), Foam::constant::atomic::group, IOobject::groupName(), objectRegistry::lookupObject(), omegaWallFunctionFvPatchScalarField::master_, omegaWallFunctionFvPatchScalarField::omega(), fvPatchField< Type >::patch(), turbulenceModel::propertiesName, omegaWallFunctionFvPatchScalarField::setMaster(), fvPatchField< Type >::updateCoeffs(), and fvPatchField< Type >::updated().
Referenced by omegaWallFunctionFvPatchScalarField::clone().
void updateCoeffs (const scalarField & weights) virtual
Update the coefficients associated with the patch field.
Reimplemented from fvPatchField< Type >.
Definition at line 459 of file omegaWallFunctionFvPatchScalarField.C.
References omegaWallFunctionFvPatchScalarField::calculateTurbulenceFields(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), fvPatchField< Type >::db(), fvPatchField< Type >::dimensionedInternalField(), fvPatch::faceCells(), forAll, omegaWallFunctionFvPatchScalarField::G(), turbulenceModel::GName(), Foam::constant::atomic::group, IOobject::groupName(), objectRegistry::lookupObject(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::master_, omegaWallFunctionFvPatchScalarField::omega(), fvPatchField< Type >::patch(), turbulenceModel::propertiesName, omegaWallFunctionFvPatchScalarField::setMaster(), omegaWallFunctionFvPatchScalarField::tolerance_, fvPatchField< Type >::updateCoeffs(), and fvPatchField< Type >::updated().
void manipulateMatrix (fvMatrix< scalar > & matrix) virtual
Manipulate matrix.
Definition at line 520 of file omegaWallFunctionFvPatchScalarField.C.
References fvPatchField< Type >::manipulatedMatrix(), fvPatchField< Type >::manipulateMatrix(), fvPatchField< Type >::patch(), fvPatchField< Type >::patchInternalField(), and fvMatrix< Type >::setValues().
Referenced by omegaWallFunctionFvPatchScalarField::clone(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
void manipulateMatrix (fvMatrix< scalar > & matrix, const scalarField & weights) virtual
Manipulate matrix with given weights.
Definition at line 536 of file omegaWallFunctionFvPatchScalarField.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), fvPatchField< Type >::dimensionedInternalField(), Foam::endl(), fvPatch::faceCells(), forAll, fvPatchField< Type >::manipulatedMatrix(), fvPatchField< Type >::manipulateMatrix(), fvPatch::name(), fvPatchField< Type >::patch(), Foam::Pout, fvMatrix< Type >::setValues(), List< T >::size(), fvPatch::size(), and omegaWallFunctionFvPatchScalarField::tolerance_.
void write (Ostream & os) const virtual
Write.
Reimplemented from fixedValueFvPatchField< scalar >.
Definition at line 588 of file omegaWallFunctionFvPatchScalarField.C.
References Foam::makePatchTypeField(), fixedValueFvPatchField< Type >::write(), and omegaWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by omegaWallFunctionFvPatchScalarField::clone().
Member Data Documentation
scalar tolerance_ = 1e-5 static protected
Tolerance used in weighted calculations.
Definition at line 133 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::manipulateMatrix(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
scalar Cmu_ protected
Cmu coefficient.
Definition at line 136 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::calculate(), and omegaWallFunctionFvPatchScalarField::writeLocalEntries().
scalar kappa_ protected
Von Karman constant.
Definition at line 139 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::calculate(), and omegaWallFunctionFvPatchScalarField::writeLocalEntries().
scalar E_ protected
E coefficient.
Definition at line 142 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::writeLocalEntries().
scalar beta1_ protected
beta1 coefficient
Definition at line 145 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::calculate(), and omegaWallFunctionFvPatchScalarField::writeLocalEntries().
scalar yPlusLam_ protected
Y+ at the edge of the laminar sublayer.
Definition at line 148 of file omegaWallFunctionFvPatchScalarField.H.
scalarField G_ protected
Local copy of turbulence G field.
Definition at line 151 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::createAveragingWeights(), and omegaWallFunctionFvPatchScalarField::G().
scalarField omega_ protected
Local copy of turbulence omega field.
Definition at line 154 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::createAveragingWeights(), and omegaWallFunctionFvPatchScalarField::omega().
bool initialised_ protected
Initialised flag.
Definition at line 157 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::createAveragingWeights().
label master_ protected
Master patch ID.
Definition at line 160 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::G(), omegaWallFunctionFvPatchScalarField::master(), omegaWallFunctionFvPatchScalarField::omega(), omegaWallFunctionFvPatchScalarField::setMaster(), and omegaWallFunctionFvPatchScalarField::updateCoeffs().
List<List<scalar> > cornerWeights_ protected
List of averaging corner weights.
Definition at line 163 of file omegaWallFunctionFvPatchScalarField.H.
Referenced by omegaWallFunctionFvPatchScalarField::calculateTurbulenceFields(), and omegaWallFunctionFvPatchScalarField::createAveragingWeights().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/omegaWallFunctions/omegaWallFunction/omegaWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/omegaWallFunctions/omegaWallFunction/omegaWallFunctionFvPatchScalarField.C