OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
outletStabilised< Type > Class Template Reference
Outlet-stabilised interpolation scheme which applies upwind differencing to the faces of the cells adjacent to outlets.
Public Member Functions
TypeName ("outletStabilised")
Runtime type information.
outletStabilised (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
outletStabilised (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from mesh, faceFlux and Istream.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the interpolation weighting factors.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::outletStabilised< Type >
Outlet-stabilised interpolation scheme which applies upwind differencing to the faces of the cells adjacent to outlets.
This is particularly useful to stabilise the velocity at entrainment boundaries for LES cases using linear or other centred differencing schemes.
Source files
outletStabilised.H
outletStabilised.C
Definition at line 60 of file outletStabilised.H.
Constructor & Destructor Documentation
outletStabilised (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 89 of file outletStabilised.H.
outletStabilised (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from mesh, faceFlux and Istream.
Definition at line 111 of file outletStabilised.H.
References outletStabilised< Type >::weights().
Member Function Documentation
TypeName ("outletStabilised< Type >")
Runtime type information.
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 130 of file outletStabilised.H.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cells, primitiveMesh::cells(), forAll, Foam::isA(), primitiveMesh::isInternalFace(), surfaceInterpolationScheme< Type >::mesh(), patchi, Foam::pos(), and tmp< T >::ref().
Referenced by outletStabilised< Type >::outletStabilised().
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 176 of file outletStabilised.H.
References outletStabilised< Type >::correction().
Referenced by outletStabilised< Type >::correction().
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the explicit correction to the face-interpolate.
set to zero on the near-boundary faces where upwinf is applied
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 185 of file outletStabilised.H.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cells, primitiveMesh::cells(), outletStabilised< Type >::corrected(), forAll, Foam::isA(), primitiveMesh::isInternalFace(), surfaceInterpolationScheme< Type >::mesh(), patchi, tmp< T >::ref(), and Foam::Zero.
Referenced by outletStabilised< Type >::corrected().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/outletStabilised/outletStabilised.H