OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PackedList< nBits > Class Template Reference
A dynamically allocatable list of packed unsigned integers.
Classes
class const_iterator
The const_iterator for PackedList.
class iterator
The iterator class used for PackedList.
class iteratorBase
The iterator base for PackedList.
Public Member Functions
PackedList ()
Null constructor.
PackedList (const label size)
Construct with given size, initializes list to 0.
PackedList (const label size, const unsigned val)
Construct with given size and value for all elements.
PackedList (Istream &)
Construct from Istream.
PackedList (const PackedList< nBits > &)
Copy constructor.
PackedList (const Xfer< PackedList< nBits >> &)
Construct by transferring the parameter contents.
PackedList (const labelUList &)
Construct from a list of labels.
PackedList (const UIndirectList< label > &)
Construct from an indirect list of labels.
autoPtr< PackedList< nBits > > clone () const
Clone.
label capacity () const
The number of elements that can be stored before reallocating.
label size () const
Number of entries.
bool empty () const
Return true if the list is empty (ie, size() is zero).
unsigned int get (const label) const
Get value at index I.
bool set (const label, const unsigned int val=~0u)
Set value at index I. Return true if value changed.
bool unset (const label)
Unset the entry at index I. Return true if value changed.
List< unsigned int > & storage ()
Return the underlying packed storage.
const List< unsigned int > & storage () const
Return the underlying packed storage.
label packedLength () const
The list length when packed.
std::streamsize byteSize () const
Return the binary size in number of characters.
unsigned int count () const
Count number of bits set, O(log(n))
Xfer< labelList > values () const
Return the values as a list of labels.
Ostream & printBits (Ostream &, const bool fullOutput=false) const
Print bit patterns, optionally output unused elements.
Ostream & printInfo (Ostream &, const bool fullOutput=false) const
Print information and bit patterns (with printBits)
bool trim ()
Trim any trailing zero elements.
void flip ()
Invert the bits in the addressable region.
void reset ()
Clear all bits.
void setCapacity (const label)
Alter the size of the underlying storage.
void resize (const label, const unsigned int &val=0u)
Reset addressable list size, does not shrink the allocated size.
void setSize (const label, const unsigned int &val=0u)
Alias for resize()
void reserve (const label)
Reserve allocation space for at least this size.
void clear ()
Clear the list, i.e. set addressable size to zero.
void clearStorage ()
Clear the list and delete storage.
void shrink ()
Shrink the allocated space to what is actually used.
void transfer (PackedList< nBits > &)
Transfer the contents of the argument list into this list.
Xfer< PackedList< nBits > > xfer ()
Transfer contents to the Xfer container.
Istream & read (Istream &)
Clear list and read from stream.
Ostream & write (Ostream &, const bool indexedOutput=false) const
Write, optionally with indexedOutput.
void writeEntry (Ostream &) const
Write as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write as a dictionary entry with keyword.
PackedList< nBits > & append (const unsigned int val)
Append a value at the end of the list.
unsigned int remove ()
Remove and return the last element.
unsigned int operator[] (const label) const
Get value at index I.
iteratorBase operator[] (const label)
Set value at index I.
void operator= (const unsigned int val)
Assignment of all entries to the given value. Takes linear time.
void operator= (const PackedList< nBits > &)
Assignment operator.
void operator= (const labelUList &)
Assignment operator.
void operator= (const UIndirectList< label > &)
Assignment operator.
iterator begin ()
Iterator set to the beginning of the PackedList.
iterator end ()
Iterator set to beyond the end of the PackedList.
const_iterator cbegin () const
const_iterator set to the beginning of the PackedList
const_iterator cend () const
const_iterator set to beyond the end of the PackedList
const_iterator begin () const
const_iterator set to the beginning of the PackedList
const_iterator end () const
const_iterator set to beyond the end of the PackedList
Public Member Functions inherited from PackedListCore
PackedListCore ()
Construct null.
ClassName ("PackedList")
Define template name and debug.
Static Public Member Functions
static unsigned int max_bits ()
The max. number of bits that can be templated.
static unsigned int max_value ()
The max. value for an entry, which simultaneously the bit-mask.
static unsigned int packing ()
The number of entries per packed storage element.
static unsigned int maskLower (unsigned offset)
Masking for all bits below the offset.
Protected Types
typedef unsigned int StorageType
typedef List< StorageType > StorageList
Protected Member Functions
void setPair (Istream &)
Read an index/value pair and set accordingly.
template<>
unsigned int readValue (Istream &is)
template<>
void setPair (Istream &is)
Static Protected Member Functions
static label packedLength (const label)
Calculate the list length when packed.
static unsigned int readValue (Istream &)
Read a list entry (allows for specialization)
Friends
Istream & operator>> (Istream &, PackedList< nBits > &)
Ostream & operator (Ostream &, const PackedList< nBits > &)
Detailed Description
template<unsigned nBits = 1>
class Foam::PackedList< nBits >
A dynamically allocatable list of packed unsigned integers.
The list resizing is similar to DynamicList, thus the methods clear() and setSize() behave like their DynamicList counterparts and the methods reserve() and setCapacity() can be used to influence the allocation.
The number of bits per item is specified by the template parameter nBits.
Note
In a const context, the '[]' operator simply returns the stored value, with out-of-range elements returned as zero. In a non-const context, the '[]' operator returns an iteratorBase, which might not have a valid reference for out-of-range elements. The iteratorBase class handles the assignment of new values.
Using the iteratorBase as a proxy allows assignment of values between list elements. Thus the following bit of code works as expected:
list[1] = list[5];      // value assignment, not iterator position
list[2] = list[5] = 4;  // propagates value
list[1] = list[5] = list[6];  // propagates value
Using get() or the '[]' operator are similarly fast. Looping and reading via an iterator is approx. 15% slower, but can be more flexible.
Using the set() operator (and the '[]' operator) are marginally slower (approx. 5%) than using an iterator, but the set() method has the advantage of also returning a bool if the value changed. This can be useful for branching on changed values.
list[5] = 4;
changed = list.set(5, 8);
if (changed) ...
The lazy evaluation used means that reading an out-of-range element returns zero, but does not affect the list size. Even in a non-const context, only the assigment itself causes the element to be created. For example,
list.resize(4);
Info<< list[10] << "\n";  // print zero, but doesn't adjust list
list[8] = 1;
Also note that all unused internal storage elements are guaranteed to always be bit-wise zero. This property must not be violated by any inheriting classes.
In addition to the normal output format, PackedList also supports a compact ASCII format that may be convenient for user input in some situations. The general format is a group of index/value pairs:
    { (index1 value1) (index2 value2) (index3 value3) }
The bool specialization just uses the indices corresponding to non-zero entries instead of a index/value pair:
    { index1 index2 index3 }
In both cases, the supplied indices can be randomly ordered.
See also
Foam::DynamicList
Source files
PackedList.H
PackedListI.H
PackedList.C
Definition at line 117 of file PackedList.H.
Member Typedef Documentation
typedef unsigned int StorageType protected
Definition at line 153 of file PackedList.H.
typedef List<StorageType> StorageList protected
Definition at line 154 of file PackedList.H.
Constructor & Destructor Documentation
PackedList () inline
Null constructor.
Definition at line 169 of file PackedListI.H.
Referenced by PackedList< nBits >::PackedList().
PackedList (const label size) inline explicit
Construct with given size, initializes list to 0.
Definition at line 178 of file PackedListI.H.
References PackedList< nBits >::operator=(), PackedList< nBits >::packedLength(), PackedList< nBits >::PackedList(), PackedListCore::PackedListCore(), and PackedList< nBits >::size().
PackedList (const label size, const unsigned val) inline
Construct with given size and value for all elements.
PackedList (Istream & is) inline
Construct from Istream.
Definition at line 205 of file PackedListI.H.
References PackedList< nBits >::read().
PackedList (const PackedList< nBits > & lst) inline
Copy constructor.
Definition at line 216 of file PackedListI.H.
PackedList (const Xfer< PackedList< nBits >> & lst) inline
Construct by transferring the parameter contents.
Definition at line 225 of file PackedListI.H.
References PackedList< nBits >::transfer().
PackedList (const labelUList & lst) inline explicit
Construct from a list of labels.
Definition at line 232 of file PackedListI.H.
References forAll.
PackedList (const UIndirectList< label > & lst) inline explicit
Construct from an indirect list of labels.
Definition at line 246 of file PackedListI.H.
References forAll.
Member Function Documentation
Foam::label packedLength (const label nElem) inline static protected
Calculate the list length when packed.
Definition at line 63 of file PackedListI.H.
Referenced by PackedBoolList::unset().
unsigned int readValue (Istream & is) inline static protected
Read a list entry (allows for specialization)
Definition at line 104 of file PackedListI.H.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::readLabel().
Referenced by PackedList< nBits >::read().
void setPair (Istream & is) inline protected
Read an index/value pair and set accordingly.
For bool specialization, read a single index value
Definition at line 121 of file PackedListI.H.
References IOstream::check(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Istream::readBegin(), Istream::readEnd(), and Foam::readLabel().
Referenced by PackedList< nBits >::read().
unsigned int max_bits () inline static
The max. number of bits that can be templated.
Might someday be useful for a template assert.
Definition at line 32 of file PackedListI.H.
unsigned int max_value () inline static
The max. value for an entry, which simultaneously the bit-mask.
eg, ((1 << 2) - 1) yields 0b0011
Definition at line 39 of file PackedListI.H.
Referenced by PackedList< nBits >::iteratorBase::get(), PackedList< nBits >::operator=(), PackedList< nBits >::resize(), and PackedList< nBits >::iteratorBase::set().
unsigned int packing () inline static
The number of entries per packed storage element.
Definition at line 46 of file PackedListI.H.
Referenced by PackedList< nBits >::capacity(), PackedList< nBits >::iteratorBase::get(), PackedList< nBits >::operator=(), PackedList< nBits >::resize(), PackedList< nBits >::iteratorBase::set(), and PackedList< nBits >::setCapacity().
unsigned int maskLower (unsigned offset) inline static
Masking for all bits below the offset.
Definition at line 53 of file PackedListI.H.
Referenced by PackedList< nBits >::operator=(), PackedList< nBits >::resize(), and PackedList< nBits >::setCapacity().
Foam::autoPtr< Foam::PackedList< nBits > > clone () const inline
Clone.
Definition at line 261 of file PackedListI.H.
Foam::label capacity () const inline
The number of elements that can be stored before reallocating.
Definition at line 834 of file PackedListI.H.
References PackedList< nBits >::packing(), and List< T >::size().
Foam::label size () const inline
Number of entries.
Definition at line 714 of file PackedListI.H.
Referenced by meshRefinement::calculateEdgeWeights(), primitiveMesh::checkClosedBoundary(), meshRefinement::gAverage(), indexedOctree< Type >::getVolumeType(), PackedList< nBits >::operator=(), PackedList< nBits >::PackedList(), PackedBoolList::subset(), syncTools::syncEdgeList(), syncTools::syncFaceList(), syncTools::syncPointList(), meshRefinement::weightedSum(), and PackedList< nBits >::write().
bool empty () const inline
Return true if the list is empty (ie, size() is zero).
Definition at line 721 of file PackedListI.H.
References PackedList< nBits >::resize().
Referenced by dynamicRefineFvMesh::selectRefineCells().
unsigned int get (const label i) const inline
Get value at index I.
Never auto-vivify entries.
Definition at line 964 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::iteratorBase().
Referenced by motionSmootherAlgo::avg(), dynamicRefineFvMesh::calculateProtectedCells(), hexRef8::consistentRefinement(), hexRef8::consistentSlowRefinement2(), dynamicRefineFvMesh::count(), meshRefinement::countHits(), dynamicRefineFvMesh::dynamicRefineFvMesh(), dynamicRefineFvMesh::extendMarkedCells(), hexRef8::getAnchorLevel(), indexedOctree< Type >::getVolumeType(), NamedEnum< Enum, nEnum >::names(), PackedList< nBits >::iteratorBase::operator!=(), PackedList< nBits >::iteratorBase::operator=(), PackedList< nBits >::iteratorBase::operator==(), NASedgeFormat::read(), STARCDedgeFormat::read(), dynamicRefineFvMesh::selectRefineCells(), and dynamicRefineFvMesh::selectUnrefinePoints().
bool set (const label i, const unsigned int val = ~0u) inline
Set value at index I. Return true if value changed.
Does auto-vivify for non-existent entries. Default value set is the max_value.
Definition at line 995 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::iteratorBase(), and PackedList< nBits >::resize().
Referenced by PackedList< nBits >::operator[]().
bool unset (const label i) inline
Unset the entry at index I. Return true if value changed.
Never auto-vivify entries.
Definition at line 1016 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::iteratorBase().
Foam::List< unsigned int > & storage () inline
Return the underlying packed storage.
Manipulate with utmost caution
Definition at line 919 of file PackedListI.H.
Referenced by PackedBoolList::operator^=(), PackedList< nBits >::read(), PackedBoolList::set(), PackedBoolList::subset(), PackedBoolList::unset(), and PackedList< nBits >::write().
const Foam::List< unsigned int > & storage () const inline
Return the underlying packed storage.
Definition at line 926 of file PackedListI.H.
Foam::label packedLength () const inline
The list length when packed.
Definition at line 933 of file PackedListI.H.
Referenced by PackedList< nBits >::byteSize(), PackedList< nBits >::operator=(), PackedList< nBits >::PackedList(), PackedList< nBits >::reserve(), PackedList< nBits >::resize(), PackedList< nBits >::setCapacity(), and PackedList< nBits >::shrink().
std::streamsize byteSize () const inline
Return the binary size in number of characters.
used in the underlying storage
Definition at line 940 of file PackedListI.H.
References PackedList< nBits >::packedLength().
Referenced by PackedList< nBits >::read(), and PackedList< nBits >::write().
unsigned int count () const
Count number of bits set, O(log(n))
Uses the Hamming weight (population count) method http://en.wikipedia.org/wiki/Hamming_weight
Definition at line 55 of file PackedList.C.
References Foam::constant::universal::c, and COUNT_PACKEDBITS.
Referenced by polyMeshFilter::filterEdges(), NASedgeFormat::read(), and STARCDedgeFormat::read().
Foam::Xfer< Foam::labelList > values () const
Return the values as a list of labels.
Definition at line 134 of file PackedList.C.
References forAll, PackedList< nBits >::iteratorBase::printInfo(), and List< T >::xfer().
Foam::Ostream & printBits (Ostream & os, const bool fullOutput = false) const
Print bit patterns, optionally output unused elements.
addressable bits: on: '1', off: '-'
non-addressable bits: on: '!', off: '.'
Definition at line 166 of file PackedList.C.
References PackedList< nBits >::printInfo().
Referenced by PackedList< nBits >::iteratorBase::printInfo().
Foam::Ostream & printInfo (Ostream & os, const bool fullOutput = false) const
Print information and bit patterns (with printBits)
Definition at line 235 of file PackedList.C.
References Foam::nl.
Referenced by PackedList< nBits >::printBits().
bool trim ()
Trim any trailing zero elements.
Definition at line 74 of file PackedList.C.
Referenced by Foam::operator&(), and Foam::operator^().
void flip ()
Invert the bits in the addressable region.
Definition at line 104 of file PackedList.C.
Referenced by PackedBoolList::operator~().
void reset () inline
Clear all bits.
Definition at line 885 of file PackedListI.H.
References List< T >::operator=().
Referenced by PackedList< nBits >::clear().
void setCapacity (const label nElem) inline
Alter the size of the underlying storage.
The addressed size will be truncated if needed to fit, but will remain otherwise untouched.
Definition at line 841 of file PackedListI.H.
References PackedList< nBits >::maskLower(), UList< T >::operator[](), PackedList< nBits >::packedLength(), PackedList< nBits >::packing(), and List< T >::setSize().
Referenced by polyTopoChange::addMesh(), and polyTopoChange::setCapacity().
void resize (const label newSize, const unsigned int & val = 0u) inline
Reset addressable list size, does not shrink the allocated size.
Optionally specify a value for new elements.
Definition at line 729 of file PackedListI.H.
References PackedList< nBits >::maskLower(), PackedList< nBits >::max_value(), UList< T >::operator[](), PackedList< nBits >::packedLength(), PackedList< nBits >::packing(), PackedList< nBits >::reserve(), and PackedList< nBits >::setSize().
Referenced by PackedList< nBits >::empty(), PackedList< nBits >::iteratorBase::operator=(), PackedList< nBits >::read(), PackedList< nBits >::remove(), PackedList< nBits >::set(), and PackedList< nBits >::setSize().
void setSize (const label newSize, const unsigned int & val = 0u) inline
Alias for resize()
Definition at line 823 of file PackedListI.H.
References PackedList< nBits >::resize().
Referenced by indexedOctree< Type >::getVolumeType(), PatchTools::matchEdges(), and PackedList< nBits >::resize().
void reserve (const label nElem) inline
Reserve allocation space for at least this size.
Never shrinks the allocated size. The list size is adjusted as per DynamicList with SizeInc=0, SizeMult=2, SizeDiv=1
Definition at line 863 of file PackedListI.H.
References Foam::max(), PackedList< nBits >::packedLength(), List< T >::setSize(), and List< T >::size().
Referenced by PackedList< nBits >::append(), PackedList< nBits >::resize(), and PackedBoolList::subsetIndices().
void clear () inline
Clear the list, i.e. set addressable size to zero.
Does not adjust the underlying storage
Definition at line 892 of file PackedListI.H.
References PackedList< nBits >::reset().
Referenced by dynamicRefineFvMesh::calculateProtectedCells(), dynamicRefineFvMesh::dynamicRefineFvMesh(), and PackedList< nBits >::read().
void clearStorage () inline
Clear the list and delete storage.
Definition at line 900 of file PackedListI.H.
References List< T >::clear().
Referenced by polyTopoChange::changeMesh(), polyTopoChange::clear(), and polyTopoChange::makeMesh().
void shrink () inline
Shrink the allocated space to what is actually used.
Definition at line 908 of file PackedListI.H.
References PackedList< nBits >::packedLength(), List< T >::setSize(), and List< T >::size().
void transfer (PackedList< nBits > & lst) inline
Transfer the contents of the argument list into this list.
and annul the argument list.
Definition at line 947 of file PackedListI.H.
References List< T >::transfer().
Referenced by PackedList< nBits >::PackedList(), and PackedBoolList::transfer().
Foam::Xfer< Foam::PackedList< nBits > > xfer () inline
Transfer contents to the Xfer container.
Definition at line 957 of file PackedListI.H.
References Foam::xferMove().
Foam::Istream & read (Istream & is)
Clear list and read from stream.
Definition at line 254 of file PackedList.C.
References PackedList< nBits >::append(), PackedList< nBits >::byteSize(), PackedList< nBits >::clear(), UList< T >::data(), Foam::exit(), IOstream::fatalCheck(), Foam::FatalIOError, FatalIOErrorInFunction, IOstream::format(), token::info(), token::isLabel(), token::isPunctuation(), token::labelToken(), token::pToken(), Istream::putBack(), Istream::read(), Istream::readBeginList(), Istream::readEndList(), PackedList< nBits >::readValue(), PackedList< nBits >::resize(), PackedList< nBits >::setPair(), PackedList< nBits >::storage(), and PackedList< nBits >::write().
Referenced by PackedList< nBits >::operator=(), and PackedList< nBits >::PackedList().
Foam::Ostream & write (Ostream & os, const bool indexedOutput = false) const
Write, optionally with indexedOutput.
The indexed output may be convenient in some situations. The general format is a group of index/value pairs:
    { (index1 value1) (index2 value2) (index3 value3) }
The bool specialization just uses the indices corresponding to non-zero entries instead of a index/value pair:
   { index1 index2 index3 }
Note the indexed output is only supported for ASCII streams.
Definition at line 399 of file PackedList.C.
References PackedList< nBits >::byteSize(), PackedList< nBits >::cbegin(), UList< T >::cdata(), PackedList< nBits >::cend(), forAll, IOstream::format(), Foam::nl, PackedList< nBits >::size(), PackedList< nBits >::storage(), and Ostream::write().
Referenced by PackedList< nBits >::operator=(), and PackedList< nBits >::read().
void writeEntry (Ostream & os) const
Write as a dictionary entry.
Definition at line 494 of file PackedList.C.
void writeEntry (const word & keyword, Ostream & os) const
Write as a dictionary entry with keyword.
Definition at line 502 of file PackedList.C.
References Foam::endl(), and Ostream::writeKeyword().
Foam::PackedList< nBits > & append (const unsigned int val) inline
Append a value at the end of the list.
Definition at line 1032 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::iteratorBase(), and PackedList< nBits >::reserve().
Referenced by extendedEdgeMesh::edgeBaffles(), and PackedList< nBits >::read().
unsigned int remove () inline
Remove and return the last element.
Definition at line 1044 of file PackedListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, PackedList< nBits >::iteratorBase::iteratorBase(), and PackedList< nBits >::resize().
unsigned int operator[] (const label i) const inline
Get value at index I.
Never auto-vivify entries.
Definition at line 979 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::iteratorBase(), and PackedList< nBits >::set().
Foam::PackedList< nBits >::iteratorBase operator[] (const label i) inline
Set value at index I.
Returns iterator to perform the actual operation. Does not auto-vivify entries, but will when assigned to.
Definition at line 1062 of file PackedListI.H.
References PackedList< nBits >::iteratorBase::iteratorBase().
void operator= (const unsigned int val) inline
Assignment of all entries to the given value. Takes linear time.
Definition at line 1069 of file PackedListI.H.
References PackedList< nBits >::maskLower(), PackedList< nBits >::max_value(), UList< T >::operator[](), PackedList< nBits >::packedLength(), and PackedList< nBits >::packing().
Referenced by PackedBoolList::operator=(), and PackedList< nBits >::PackedList().
void operator= (const PackedList< nBits > & lst)
Assignment operator.
Definition at line 516 of file PackedList.C.
References PackedList< nBits >::size().
void operator= (const labelUList & lst)
Assignment operator.
Definition at line 524 of file PackedList.C.
References forAll, and UList< T >::size().
void operator= (const UIndirectList< label > & lst)
Assignment operator.
Definition at line 537 of file PackedList.C.
References forAll, Foam::operator>>(), PackedList< nBits >::read(), UIndirectList< T >::size(), and PackedList< nBits >::write().
Foam::PackedList< nBits >::iterator begin () inline
Iterator set to the beginning of the PackedList.
Definition at line 665 of file PackedListI.H.
Foam::PackedList< nBits >::iterator end () inline
Iterator set to beyond the end of the PackedList.
Definition at line 689 of file PackedListI.H.
Foam::PackedList< nBits >::const_iterator cbegin () const inline
const_iterator set to the beginning of the PackedList
Definition at line 681 of file PackedListI.H.
References PackedList< nBits >::const_iterator::const_iterator().
Referenced by PackedList< nBits >::write().
Foam::PackedList< nBits >::const_iterator cend () const inline
const_iterator set to beyond the end of the PackedList
Definition at line 705 of file PackedListI.H.
References PackedList< nBits >::const_iterator::const_iterator().
Referenced by PackedList< nBits >::write().
Foam::PackedList< nBits >::const_iterator begin () const inline
const_iterator set to the beginning of the PackedList
Definition at line 673 of file PackedListI.H.
References PackedList< nBits >::const_iterator::const_iterator().
Foam::PackedList< nBits >::const_iterator end () const inline
const_iterator set to beyond the end of the PackedList
Definition at line 697 of file PackedListI.H.
References PackedList< nBits >::const_iterator::const_iterator().
unsigned int readValue (Istream & is) inline protected
Definition at line 73 of file PackedListI.H.
References Foam::readBool().
void setPair (Istream & is) inline protected
Definition at line 80 of file PackedListI.H.
References Foam::readLabel().
Friends And Related Function Documentation
Istream& operator>> (Istream & , PackedList< nBits > &) friend
Ostream& operator (Ostream & , const PackedList< nBits > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/PackedList/PackedList.H
src/OpenFOAM/containers/Lists/PackedList/PackedList.C
src/OpenFOAM/containers/Lists/PackedList/PackedListI.H