OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PackedListCore Struct Reference
Template-invariant bits for PackedList.
Public Member Functions
PackedListCore ()
Construct null.
ClassName ("PackedList")
Define template name and debug.
Detailed Description
Template-invariant bits for PackedList.
Definition at line 130 of file PackedList.H.
Constructor & Destructor Documentation
PackedListCore () inline
Construct null.
Definition at line 133 of file PackedList.H.
References PackedListCore::ClassName().
Referenced by PackedList< nBits >::PackedList().
Member Function Documentation
ClassName ("PackedList")
Define template name and debug.
Referenced by PackedListCore::PackedListCore().
The documentation for this struct was generated from the following file:
src/OpenFOAM/containers/Lists/PackedList/PackedList.H