OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ParticleForceList< CloudType > Class Template Reference
List of particle forces.
Public Member Functions
ParticleForceList (CloudType &owner, const fvMesh &mesh)
Null constructor.
ParticleForceList (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const bool readFields)
Construct from mesh.
ParticleForceList (const ParticleForceList &pfl)
Construct copy.
virtual ~ParticleForceList ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & dict () const
Return the forces dictionary.
void setCalcCoupled (bool flag)
Set the calcCoupled flag.
void setCalcNonCoupled (bool flag)
Set the calcNonCoupled flag.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massEff (const typename CloudType::parcelType &p, const scalar mass) const
Return the effective mass.
Public Member Functions inherited from PtrList< ParticleForce< CloudType > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< ParticleForce< CloudType > > &)
Copy constructor.
PtrList (const PtrList< ParticleForce< CloudType > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< ParticleForce< CloudType > >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< ParticleForce< CloudType > > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< ParticleForce< CloudType > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
ParticleForce< CloudType > & first ()
Return reference to the first element of the list.
const ParticleForce< CloudType > & first () const
Return reference to first element of the list.
ParticleForce< CloudType > & last ()
Return reference to the last element of the list.
const ParticleForce< CloudType > & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (ParticleForce< CloudType > *)
Append an element at the end of the list.
void append (const autoPtr< ParticleForce< CloudType > > &)
void append (const tmp< ParticleForce< CloudType > > &)
void transfer (PtrList< ParticleForce< CloudType > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< ParticleForce< CloudType > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< ParticleForce< CloudType > > set (const label, ParticleForce< CloudType > *)
Set element. Return old element (can be NULL).
autoPtr< ParticleForce< CloudType > > set (const label, const autoPtr< ParticleForce< CloudType > > &)
autoPtr< ParticleForce< CloudType > > set (const label, const tmp< ParticleForce< CloudType > > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const ParticleForce< CloudType > & operator[] (const label) const
Return element const reference.
ParticleForce< CloudType > & operator[] (const label)
Return element reference.
const ParticleForce< CloudType > * operator() (const label) const
Return element const pointer.
void operator= (const PtrList< ParticleForce< CloudType > > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
const_iterator end () const
Return an const_iterator to end traversing the PtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the PtrList.
const_iterator cend () const
Return an const_iterator to end traversing the PtrList.
Additional Inherited Members
Public Types inherited from PtrList< ParticleForce< CloudType > >
typedef ParticleForce< CloudType > value_type
Type of values the PtrList contains.
typedef ParticleForce< CloudType > & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const ParticleForce< CloudType > & const_reference
Type that can be used for storing into constant PtrList::value_type.
Protected Member Functions inherited from PtrList< ParticleForce< CloudType > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
template<class CloudType>
class Foam::ParticleForceList< CloudType >
List of particle forces.
Source files
ParticleForceList.H
ParticleForceListI.H
ParticleForceList.C
Definition at line 51 of file ParticleForceList.H.
Constructor & Destructor Documentation
ParticleForceList (CloudType & owner, const fvMesh & mesh)
Null constructor.
Definition at line 33 of file ParticleForceList.C.
Referenced by ParticleForceList< CloudType >::ParticleForceList().
ParticleForceList (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const bool readFields)
Construct from mesh.
Definition at line 49 of file ParticleForceList.C.
References dict, Foam::endl(), forAllConstIter(), Foam::Info, Foam::New(), ParticleForceList< CloudType >::ParticleForceList(), setSize(), and dictionary::toc().
ParticleForceList (const ParticleForceList< CloudType > & pfl)
Construct copy.
Definition at line 117 of file ParticleForceList.C.
~ParticleForceList () virtual
Destructor.
Definition at line 131 of file ParticleForceList.C.
Member Function Documentation
const CloudType & owner () const inline
Return const access to the cloud owner.
Definition at line 29 of file ParticleForceListI.H.
CloudType & owner () inline
Return refernce to the cloud owner.
Definition at line 36 of file ParticleForceListI.H.
const Foam::fvMesh & mesh () const inline
Return the mesh database.
Definition at line 43 of file ParticleForceListI.H.
const Foam::dictionary & dict () const inline
Return the forces dictionary.
Definition at line 50 of file ParticleForceListI.H.
void setCalcCoupled (bool flag) inline
Set the calcCoupled flag.
Definition at line 57 of file ParticleForceListI.H.
void setCalcNonCoupled (bool flag) inline
Set the calcNonCoupled flag.
Definition at line 64 of file ParticleForceListI.H.
void cacheFields (const bool store) virtual
Cache fields.
Definition at line 138 of file ParticleForceList.C.
References ParticleForceList< CloudType >::calcCoupled(), and forAll.
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the coupled force.
Definition at line 149 of file ParticleForceList.C.
References ParticleForceList< CloudType >::calcNonCoupled(), and forAll.
Referenced by ParticleForceList< CloudType >::cacheFields().
Foam::forceSuSp calcNonCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the non-coupled force.
Definition at line 173 of file ParticleForceList.C.
References forAll, and ParticleForceList< CloudType >::massEff().
Referenced by ParticleForceList< CloudType >::calcCoupled().
Foam::scalar massEff (const typename CloudType::parcelType & p, const scalar mass) const virtual
Return the effective mass.
Definition at line 197 of file ParticleForceList.C.
References forAll.
Referenced by ParticleForceList< CloudType >::calcNonCoupled().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/ForceTypes/ParticleForceList/ParticleForceList.H
src/lagrangian/intermediate/submodels/ForceTypes/ParticleForceList/ParticleForceList.C
src/lagrangian/intermediate/submodels/ForceTypes/ParticleForceList/ParticleForceListI.H