OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
oldCyclicPolyPatch Class Reference
'old' style cyclic polyPatch with all faces in single patch. Does ordering but cannot be used to run. Writes 'type cyclic' so foamUpgradeCyclics can be run afterwards. Used to get cyclics from mesh converters that assume cyclics in single patch (e.g. fluent3DMeshToFoam)
Public Member Functions
TypeName ("oldCyclic")
Runtime type information.
oldCyclicPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN)
Construct from components.
oldCyclicPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
oldCyclicPolyPatch (const oldCyclicPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
oldCyclicPolyPatch (const oldCyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~oldCyclicPolyPatch ()
virtual bool owner () const
Does this side own the patch ?
virtual void transformPosition (pointField &l) const
Transform a patch-based position from other side to this side.
virtual void transformPosition (point &, const label facei) const
Transform a patch-based position from other side to this side.
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
Calculate the patch geometry.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
virtual bool coupled () const
Return true because this patch is coupled.
virtual bool neighbour () const
Does the coupled side own the patch ?
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes inherited from coupledPolyPatch
static const NamedEnum< transformType, 5 > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Detailed Description
'old' style cyclic polyPatch with all faces in single patch. Does ordering but cannot be used to run. Writes 'type cyclic' so foamUpgradeCyclics can be run afterwards. Used to get cyclics from mesh converters that assume cyclics in single patch (e.g. fluent3DMeshToFoam)
Source files
oldCyclicPolyPatch.H
oldCyclicPolyPatch.C
Definition at line 52 of file oldCyclicPolyPatch.H.
Constructor & Destructor Documentation
oldCyclicPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform = UNKNOWN)
Construct from components.
Definition at line 562 of file oldCyclicPolyPatch.C.
Referenced by oldCyclicPolyPatch::clone(), and oldCyclicPolyPatch::oldCyclicPolyPatch().
oldCyclicPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 581 of file oldCyclicPolyPatch.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), dictionary::lookup(), oldCyclicPolyPatch::oldCyclicPolyPatch(), dictionary::readIfPresent(), and Foam::transform().
oldCyclicPolyPatch (const oldCyclicPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 632 of file oldCyclicPolyPatch.C.
References oldCyclicPolyPatch::oldCyclicPolyPatch().
oldCyclicPolyPatch (const oldCyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 646 of file oldCyclicPolyPatch.C.
~oldCyclicPolyPatch () virtual
Definition at line 664 of file oldCyclicPolyPatch.C.
Referenced by oldCyclicPolyPatch::clone().
Member Function Documentation
void initGeometry (PstreamBuffers & pBufs) protected virtual
Initialise the calculation of the patch geometry.
Implements coupledPolyPatch.
Definition at line 670 of file oldCyclicPolyPatch.C.
References oldCyclicPolyPatch::calcGeometry(), and polyPatch::initGeometry().
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Calculate the patch geometry.
Implements coupledPolyPatch.
Definition at line 689 of file oldCyclicPolyPatch.C.
References oldCyclicPolyPatch::initMovePoints().
Referenced by oldCyclicPolyPatch::initGeometry(), and oldCyclicPolyPatch::transformPosition().
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Initialise the patches for moving points.
Implements coupledPolyPatch.
Definition at line 694 of file oldCyclicPolyPatch.C.
References polyPatch::initMovePoints(), and oldCyclicPolyPatch::movePoints().
Referenced by oldCyclicPolyPatch::calcGeometry().
void movePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Correct patches after moving points.
Implements coupledPolyPatch.
Definition at line 704 of file oldCyclicPolyPatch.C.
References polyPatch::movePoints().
Referenced by oldCyclicPolyPatch::initMovePoints().
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Implements coupledPolyPatch.
Definition at line 713 of file oldCyclicPolyPatch.C.
References polyPatch::initUpdateMesh().
void updateMesh (PstreamBuffers & pBufs) protected virtual
Update of the patch topology.
Implements coupledPolyPatch.
Definition at line 719 of file oldCyclicPolyPatch.C.
References oldCyclicPolyPatch::initOrder(), and polyPatch::updateMesh().
TypeName ("oldCyclic")
Runtime type information.
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from polyPatch.
Definition at line 215 of file oldCyclicPolyPatch.H.
References oldCyclicPolyPatch::oldCyclicPolyPatch().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from polyPatch.
Definition at line 223 of file oldCyclicPolyPatch.H.
References oldCyclicPolyPatch::oldCyclicPolyPatch(), and oldCyclicPolyPatch::~oldCyclicPolyPatch().
virtual bool owner () const inline virtual
Does this side own the patch ?
Implements coupledPolyPatch.
Definition at line 247 of file oldCyclicPolyPatch.H.
References NotImplemented.
virtual void transformPosition (pointField & l) const inline virtual
Transform a patch-based position from other side to this side.
Implements coupledPolyPatch.
Definition at line 254 of file oldCyclicPolyPatch.H.
References NotImplemented.
virtual void transformPosition (point & , const label facei) const inline virtual
Transform a patch-based position from other side to this side.
Implements coupledPolyPatch.
Definition at line 260 of file oldCyclicPolyPatch.H.
References oldCyclicPolyPatch::calcGeometry(), oldCyclicPolyPatch::initOrder(), NotImplemented, oldCyclicPolyPatch::order(), and oldCyclicPolyPatch::write().
void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) virtual
Calculate the patch geometry.
Implements coupledPolyPatch.
Definition at line 677 of file oldCyclicPolyPatch.C.
void initOrder (PstreamBuffers & , const primitivePatch & pp) const virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Implements coupledPolyPatch.
Definition at line 726 of file oldCyclicPolyPatch.C.
References oldCyclicPolyPatch::order().
Referenced by oldCyclicPolyPatch::transformPosition(), and oldCyclicPolyPatch::updateMesh().
bool order (PstreamBuffers & , const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Implements coupledPolyPatch.
Definition at line 738 of file oldCyclicPolyPatch.C.
References Foam::abort(), Foam::constant::physicoChemical::c1, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::identity(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), Foam::matchPoints(), mesh, OSstream::name(), Foam::name(), path(), pFaces, PrimitivePatch< Face, FaceList, PointField, PointType >::pointFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::Pout, SeriousErrorInFunction, List< T >::setSize(), and Foam::meshTools::writeOBJ().
Referenced by oldCyclicPolyPatch::initOrder(), and oldCyclicPolyPatch::transformPosition().
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from coupledPolyPatch.
Definition at line 1221 of file oldCyclicPolyPatch.C.
References token::END_STATEMENT, Foam::endl(), Foam::nl, Foam::transform(), WarningInFunction, patchIdentifier::write(), and Ostream::writeKeyword().
Referenced by oldCyclicPolyPatch::transformPosition().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/oldCyclic/oldCyclicPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/oldCyclic/oldCyclicPolyPatch.C