OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
particle< Type > Class Template Reference
Base particle class.
Classes
class iNew
Factory class to read-construct particles used for.
class TrackingData
Public Member Functions
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label cellI, bool doCellFacePt=true)
Construct from components, tetFaceI_ and tetPtI_ are not.
particle (const polyMesh &mesh, Istream &, bool readFields=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with refernce to a new mesh.
virtual autoPtr< particle > clone () const
Construct a clone.
virtual ~particle ()
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const vector & position () const
Return current particle position.
vector & position ()
Return current particle position.
label & cell ()
Return current cell particle is in.
label cell () const
Return current cell particle is in.
label & tetFace ()
Return current tet face particle is in.
label tetFace () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in.
label tetPt () const
Return current tet face particle is in.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
tetPointRef currentTet () const
Return the geometry of the current tet that the.
vector normal () const
Return the normal of the tri on tetFaceI_ for the.
vector oldNormal () const
Return the normal of the tri on tetFaceI_ for the.
label & face ()
Return current face particle is on otherwise -1.
label face () const
Return current face particle is on otherwise -1.
bool softImpact () const
Return the impact model to be used, soft or hard (default).
scalar currentTime () const
Return the particle current time.
void initCellFacePt ()
Check the stored cell value (setting if necessary) and.
bool onBoundary () const
Is the particle on the boundary/(or outside the domain)?
bool internalFace (const label faceI) const
Is this global face an internal face?
bool boundaryFace (const label faceI) const
Is this global face a boundary face?
label patch (const label faceI) const
Which patch is particle on.
label patchFace (const label patchI, const label faceI) const
Which face of this patch is this particle on.
scalar & stepFraction ()
Return the fraction of time-step completed.
scalar stepFraction () const
Return the fraction of time-step completed.
label origProc () const
Return const access to the originating processor id.
label & origProc ()
Return the originating processor id for manipulation.
label origId () const
Return const access to the particle id on originating processor.
label & origId ()
Return the particle id on originating processor for manipulation.
template<class TrackData >
label track (const vector &endPosition, TrackData &td)
Track particle to end of trajectory.
template<class TrackData >
scalar trackToFace (const vector &endPosition, TrackData &td)
Track particle to a given position and returns 1.0 if the.
label faceInterpolation () const
Return the index of the face to be used in the interpolation.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
virtual scalar wallImpactDistance (const vector &n) const
The nearest distance to a wall that.
template<class TrackData >
void prepareForParallelTransfer (const label patchI, TrackData &td)
Convert global addressing to the processor patch.
template<class TrackData >
void correctAfterParallelTransfer (const label patchI, TrackData &td)
Convert processor patch addressing to the global equivalents.
void writePosition (Ostream &) const
Write the particle position and cell.
template<class TrackData >
Foam::label track (const vector &endPosition, TrackData &td)
template<class TrackData >
Foam::scalar trackToFace (const vector &endPosition, TrackData &td)
Public Member Functions inherited from DLListBase::link
link ()
Null construct.
bool registered () const
Check if the link is registered with the DLListBase.
void deregister ()
Deregister the link after removal.
Static Public Member Functions
static string propertyList ()
template<class CloudType >
static void readFields (CloudType &c)
Read the fields associated with the owner cloud.
template<class CloudType >
static void writeFields (const CloudType &c)
Write the fields associated with the owner cloud.
Static Public Attributes
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provode unique ID.
static const scalar trackingCorrectionTol = 1e-5
Fraction of distance to tet centre to move a particle to.
static const scalar lambdaDistanceToleranceCoeff = 1e3*SMALL
Fraction of the cell volume to use in determining tolerance values.
static const scalar minStepFractionTol = 1e5*SMALL
Minimum stepFraction tolerance.
Protected Member Functions
void findTris (const vector &position, DynamicList< label > &faceList, const tetPointRef &tet, const FixedList< vector, 4 > &tetAreas, const FixedList< label, 4 > &tetPlaneBasePtIs, const scalar tol) const
Find the tet tri faces between position and tet centre.
scalar tetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for the line to-from across the.
scalar movingTetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for a moving tri face.
void tetNeighbour (label triI)
Modify the tet owner data by crossing triI.
void crossEdgeConnectedFace (const label &cellI, label &tetFaceI, label &tetPtI, const edge &e)
Cross the from the given face across the given edge of the.
template<class CloudType >
void hitWallFaces (const CloudType &td, const vector &from, const vector &to, scalar &lambdaMin, tetIndices &closestTetIs)
template<class TrackData >
void hitFace (TrackData &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackData >
void hitCyclicAMIPatch (const cyclicAMIPolyPatch &, TrackData &td, const vector &direction)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &tetIs)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
Protected Attributes
const polyMesh & mesh_
Reference to the polyMesh database.
vector position_
Position of particle.
label cellI_
Index of the cell it is in.
label faceI_
Face index if the particle is on a face otherwise -1.
scalar stepFraction_
Fraction of time-step completed.
label tetFaceI_
Index of the face that owns the decomposed tet that the.
label tetPtI_
Index of the point on the face that defines the decomposed.
label origProc_
Originating processor id.
label origId_
Local particle id on originating processor.
Friends
Ostream & operator<< (Ostream &, const particle &)
bool operator== (const particle &pA, const particle &pB)
bool operator!= (const particle &pA, const particle &pB)
Additional Inherited Members
Public Attributes inherited from DLListBase::link
link * prev_
Pointer to next entry in list.
link * next_
Detailed Description
template<class Type>
class Foam::particle< Type >
Base particle class.
Definition at line 78 of file particle.H.
Constructor & Destructor Documentation
particle (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from components.
Definition at line 48 of file particle.C.
Referenced by particle< Type >::clone(), and particle< Type >::iNew::operator()().
particle (const polyMesh & mesh, const vector & position, const label cellI, bool doCellFacePt = true)
Construct from components, tetFaceI_ and tetPtI_ are not.
supplied so they will be deduced by a search
Definition at line 69 of file particle.C.
particle (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 46 of file particleIO.C.
References IOstream::ASCII, particle< Type >::cellI_, IOstream::check(), particle< Type >::faceI_, IOstream::format(), particle< Type >::origId_, particle< Type >::origProc_, particle< Type >::position_, Istream::read(), particle< Type >::stepFraction_, particle< Type >::tetFaceI_, and particle< Type >::tetPtI_.
particle (const particle< Type > & p)
Construct as a copy.
Definition at line 93 of file particle.C.
particle (const particle< Type > & p, const polyMesh & mesh)
Construct as a copy with refernce to a new mesh.
Definition at line 107 of file particle.C.
virtual ~particle () inline virtual
Destructor.
Definition at line 390 of file particle.H.
Member Function Documentation
void findTris (const vector & position, DynamicList< label > & faceList, const tetPointRef & tet, const FixedList< vector, 4 > & tetAreas, const FixedList< label, 4 > & tetPlaneBasePtIs, const scalar tol) const inline protected
Find the tet tri faces between position and tet centre.
Definition at line 32 of file particleI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), tetrahedron< Point, PointRef >::centre(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), i, and lambda().
Foam::scalar tetLambda (const vector & from, const vector & to, const label triI, const vector & tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const inline protected
Find the lambda value for the line to-from across the.
given tri face, where p = from + lambda*(to - from)
Definition at line 69 of file particleI.H.
References Foam::mag(), and Foam::sign().
Foam::scalar movingTetLambda (const vector & from, const vector & to, const label triI, const vector & tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const inline protected
Find the lambda value for a moving tri face.
Definition at line 144 of file particleI.H.
References tetrahedron< Point, PointRef >::a(), Foam::constant::physicoChemical::b, tetrahedron< Point, PointRef >::b(), c(), tetrahedron< Point, PointRef >::c(), tetrahedron< Point, PointRef >::d(), Foam::mag(), n, tetIndices::oldTet(), Foam::sign(), Foam::sqr(), Foam::sqrt(), and tetIndices::tet().
void tetNeighbour (label triI) inline protected
Modify the tet owner data by crossing triI.
Definition at line 339 of file particleI.H.
References Foam::abort(), particle< Type >::cellI_, particle< Type >::crossEdgeConnectedFace(), f(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorIn, UList< T >::fcIndex(), particle< Type >::mesh_, pFaces, UList< T >::rcIndex(), List< T >::size(), polyMesh::tetBasePtIs(), particle< Type >::tetFaceI_, and particle< Type >::tetPtI_.
void crossEdgeConnectedFace (const label & cellI, label & tetFaceI, label & tetPtI, const edge & e) inline protected
Cross the from the given face across the given edge of the.
given cell to find the resulting face and tetPtI
Definition at line 483 of file particleI.H.
References Foam::abort(), face::edgeDirection(), edge::end(), f(), Foam::FatalError, FatalErrorIn, Foam::findIndex(), forAll, Foam::neg(), Foam::meshTools::otherFace(), pFaces, List< T >::size(), and edge::start().
Referenced by wallBoundedParticle::crossEdgeConnectedFace(), and particle< Type >::tetNeighbour().
void hitWallFaces (const CloudType & td, const vector & from, const vector & to, scalar & lambdaMin, tetIndices & closestTetIs) inline protected
Hit wall faces in the current cell if the wallImpactDistance is non-zero. They may not be in Different tets to the current.
Definition at line 717 of file particleTemplates.C.
References triangle< Point, PointRef >::a(), triangle< Point, PointRef >::b(), triangle< Point, PointRef >::c(), Cloud< ParticleType >::cellHasWallFaces(), tetrahedron< Point, PointRef >::centre(), f(), tetIndices::faceBasePt(), polyMeshTetDecomposition::faceTetIndices(), tetIndices::faceTri(), forAll, intersection::FULL_RAY, Cloud< ParticleType >::hasWallImpactDistance(), hitInfo(), triangle< Point, PointRef >::intersection(), lambda(), Foam::mag(), Foam::max(), Foam::min(), n, triangle< Point, PointRef >::normal(), tetIndices::oldFaceTri(), p, patches, polyBoundaryMesh::patchID(), pFaces, tetIndices::tet(), tetIndices::tetPt(), and Vector< scalar >::zero.
void hitFace (TrackData & td) protected
Overridable function to handle the particle hitting a face.
Definition at line 926 of file particleTemplates.C.
bool hitPatch (const polyPatch & , TrackData & td, const label patchI, const scalar trackFraction, const tetIndices & tetIs) protected
Overridable function to handle the particle hitting a.
patch. Executed before other patch-hitting functions. trackFraction is passed in to allow mesh motion to interpolate in time to the correct face state.
Definition at line 932 of file particleTemplates.C.
void hitWedgePatch (const wedgePolyPatch & wpp, TrackData & td) protected
Overridable function to handle the particle hitting a wedgePatch.
Definition at line 946 of file particleTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, Foam::I, Foam::mag(), and nf().
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch & spp, TrackData & td) protected
Overridable function to handle the particle hitting a.
symmetryPlanePatch
Definition at line 970 of file particleTemplates.C.
References Foam::I, Foam::mag(), and nf().
void hitSymmetryPatch (const symmetryPolyPatch & spp, TrackData & td) protected
Overridable function to handle the particle hitting a.
symmetryPatch
Definition at line 984 of file particleTemplates.C.
References Foam::I, Foam::mag(), and nf().
void hitCyclicPatch (const cyclicPolyPatch & cpp, TrackData & td) protected
Overridable function to handle the particle hitting a cyclicPatch.
Definition at line 998 of file particleTemplates.C.
References coupledPolyPatch::forwardT(), cyclicPolyPatch::neighbPatch(), coupledPolyPatch::parallel(), s(), coupledPolyPatch::separated(), coupledPolyPatch::separation(), List< T >::size(), Foam::T(), cyclicPolyPatch::transformGlobalFace(), cyclicPolyPatch::transformPosition(), and polyPatch::whichFace().
void hitCyclicAMIPatch (const cyclicAMIPolyPatch & cpp, TrackData & td, const vector & direction) protected
Overridable function to handle the particle hitting a cyclicAMIPatch.
Definition at line 1046 of file particleTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, coupledPolyPatch::forwardT(), patchIdentifier::name(), cyclicAMIPolyPatch::neighbPatch(), coupledPolyPatch::parallel(), cyclicAMIPolyPatch::pointFace(), s(), coupledPolyPatch::separated(), coupledPolyPatch::separation(), List< T >::size(), polyPatch::start(), Foam::T(), and cyclicAMIPolyPatch::transformPosition().
void hitProcessorPatch (const processorPolyPatch & , TrackData & td) protected
Overridable function to handle the particle hitting a.
processorPatch
Definition at line 1117 of file particleTemplates.C.
void hitWallPatch (const wallPolyPatch & , TrackData & td, const tetIndices & tetIs) protected
Overridable function to handle the particle hitting a wallPatch.
Definition at line 1123 of file particleTemplates.C.
void hitPatch (const polyPatch & , TrackData & td) protected
Overridable function to handle the particle hitting a.
general patch
Definition at line 1132 of file particleTemplates.C.
TypeName ("particle< Type >")
Runtime type information.
static string propertyList () inline static
Definition at line 315 of file particle.H.
virtual autoPtr<particle> clone () const inline virtual
Construct a clone.
Reimplemented in molecule, wallBoundedParticle, streamLineParticle, wallBoundedStreamLineParticle, solidParticle, trackedParticle, findCellParticle, indexedParticle, and passiveParticle.
Definition at line 364 of file particle.H.
References particle< Type >::particle().
Foam::label getNewParticleID () const inline
Get unique particle creation id.
Definition at line 606 of file particleI.H.
References Foam::endl(), Foam::labelMax, and WarningIn.
const Foam::polyMesh & mesh () const inline
Return the mesh database.
Definition at line 620 of file particleI.H.
const Foam::vector & position () const inline
Return current particle position.
Definition at line 626 of file particleI.H.
Referenced by nearWallFields::calcAddressing(), streamLineParticle::move(), wallBoundedStreamLineParticle::move(), and Foam::reconstructLagrangianPositions().
Foam::vector & position () inline
Return current particle position.
Definition at line 632 of file particleI.H.
Foam::label & cell () inline
Return current cell particle is in.
Definition at line 644 of file particleI.H.
Referenced by Foam::reconstructLagrangianPositions().
Foam::label cell () const inline
Return current cell particle is in.
Definition at line 638 of file particleI.H.
Foam::label & tetFace () inline
Return current tet face particle is in.
Definition at line 656 of file particleI.H.
Referenced by wallBoundedParticle::currentEdge().
Foam::label tetFace () const inline
Return current tet face particle is in.
Definition at line 650 of file particleI.H.
Foam::label & tetPt () inline
Return current tet face particle is in.
Definition at line 668 of file particleI.H.
Foam::label tetPt () const inline
Return current tet face particle is in.
Definition at line 662 of file particleI.H.
Foam::tetIndices currentTetIndices () const inline
Return the indices of the current tet that the.
particle occupies.
Definition at line 674 of file particleI.H.
Foam::tetPointRef currentTet () const inline
Return the geometry of the current tet that the.
particle occupies.
Definition at line 680 of file particleI.H.
Foam::vector normal () const inline
Return the normal of the tri on tetFaceI_ for the.
current tet.
Definition at line 686 of file particleI.H.
Foam::vector oldNormal () const inline
Return the normal of the tri on tetFaceI_ for the.
current tet at the start of the timestep, i.e. based on oldPoints
Definition at line 692 of file particleI.H.
Foam::label & face () inline
Return current face particle is on otherwise -1.
Definition at line 704 of file particleI.H.
Foam::label face () const inline
Return current face particle is on otherwise -1.
Definition at line 698 of file particleI.H.
bool softImpact () const inline
Return the impact model to be used, soft or hard (default).
Definition at line 893 of file particleI.H.
Foam::scalar currentTime () const inline
Return the particle current time.
Definition at line 899 of file particleI.H.
void initCellFacePt () inline
Check the stored cell value (setting if necessary) and.
initialise the tetFace and tetPt values
Definition at line 710 of file particleI.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, Foam::mag(), Foam::nl, and WarningIn.
bool onBoundary () const inline
Is the particle on the boundary/(or outside the domain)?
Definition at line 851 of file particleI.H.
bool internalFace (const label faceI) const inline
Is this global face an internal face?
Definition at line 907 of file particleI.H.
bool boundaryFace (const label faceI) const inline
Is this global face a boundary face?
Definition at line 913 of file particleI.H.
Foam::label patch (const label faceI) const inline
Which patch is particle on.
Definition at line 919 of file particleI.H.
Foam::label patchFace (const label patchI, const label faceI) const inline
Which face of this patch is this particle on.
Definition at line 926 of file particleI.H.
Foam::scalar & stepFraction () inline
Return the fraction of time-step completed.
Definition at line 857 of file particleI.H.
Foam::scalar stepFraction () const inline
Return the fraction of time-step completed.
Definition at line 863 of file particleI.H.
Foam::label origProc () const inline
Return const access to the originating processor id.
Definition at line 869 of file particleI.H.
Referenced by Foam::operator==().
Foam::label & origProc () inline
Return the originating processor id for manipulation.
Definition at line 875 of file particleI.H.
Foam::label origId () const inline
Return const access to the particle id on originating processor.
Definition at line 881 of file particleI.H.
Referenced by Foam::operator==(), and particle< Type >::readFields().
Foam::label & origId () inline
Return the particle id on originating processor for manipulation.
Definition at line 887 of file particleI.H.
label track (const vector & endPosition, TrackData & td)
Track particle to end of trajectory.
or until it hits the boundary. On entry 'stepFraction()' should be set to the fraction of the time-step at which the tracking starts and on exit it contains the fraction of the time-step completed. Returns the boundary face index if the track stops at the boundary, -1 otherwise.
scalar trackToFace (const vector & endPosition, TrackData & td)
Track particle to a given position and returns 1.0 if the.
trajectory is completed without hitting a face otherwise stops at the face and returns the fraction of the trajectory completed. on entry 'stepFraction()' should be set to the fraction of the time-step at which the tracking starts.
Foam::label faceInterpolation () const inline
Return the index of the face to be used in the interpolation.
routine
Definition at line 935 of file particleI.H.
void transformProperties (const tensor & T) virtual
Transform the physical properties of the particle.
according to the given transformation tensor
Reimplemented in molecule, and solidParticle.
Definition at line 123 of file particle.C.
Referenced by solidParticle::transformProperties(), and molecule::transformProperties().
void transformProperties (const vector & separation) virtual
Transform the physical properties of the particle.
according to the given separation vector
Reimplemented in molecule, and solidParticle.
Definition at line 127 of file particle.C.
Foam::scalar wallImpactDistance (const vector & n) const virtual
The nearest distance to a wall that.
the particle can be in the n direction
Reimplemented in solidParticle.
Definition at line 131 of file particle.C.
References Foam::endl(), and Foam::Info.
void prepareForParallelTransfer (const label patchI, TrackData & td)
Convert global addressing to the processor patch.
local equivalents
Definition at line 41 of file particleTemplates.C.
void correctAfterParallelTransfer (const label patchI, TrackData & td)
Convert processor patch addressing to the global equivalents.
and set the cellI to the face-neighbour
Definition at line 53 of file particleTemplates.C.
References polyPatch::faceCells(), coupledPolyPatch::forwardT(), coupledPolyPatch::parallel(), s(), coupledPolyPatch::separated(), coupledPolyPatch::separation(), List< T >::size(), polyPatch::start(), T, and coupledPolyPatch::transformPosition().
void readFields (CloudType & c) static
Read the fields associated with the owner cloud.
Definition at line 129 of file particleTemplates.C.
References Cloud< ParticleType >::checkFieldIOobject(), Cloud< ParticleType >::fieldIOobject(), forAllIter(), i, iter, IOobject::MUST_READ, particle< Type >::origId(), particle< Type >::origId_, particle< Type >::origProc_, p, and Cloud< ParticleType >::size().
Referenced by solidParticle::readFields(), streamLineParticle::readFields(), wallBoundedParticle::readFields(), and molecule::readFields().
void writeFields (const CloudType & c) static
Write the fields associated with the owner cloud.
Definition at line 159 of file particleTemplates.C.
References Cloud< ParticleType >::fieldIOobject(), forAllConstIter, i, iter, IOobject::NO_READ, Cloud< ParticleType >::size(), IOPosition< ParticleType >::write(), and regIOobject::write().
Referenced by solidParticle::writeFields(), streamLineParticle::writeFields(), wallBoundedParticle::writeFields(), and molecule::writeFields().
void writePosition (Ostream & os) const
Write the particle position and cell.
Definition at line 89 of file particleIO.C.
References IOstream::ASCII, IOstream::check(), IOstream::format(), token::SPACE, and Ostream::write().
Foam::label track (const vector & endPosition, TrackData & td)
Definition at line 188 of file particleTemplates.C.
Foam::scalar trackToFace (const vector & endPosition, TrackData & td)
Definition at line 204 of file particleTemplates.C.
References Foam::abort(), polyPatch::boundaryMesh(), tetIndices::cell(), tetrahedron< Point, PointRef >::centre(), UList< T >::empty(), Foam::endl(), f(), tetIndices::face(), tetIndices::faceTri(), Foam::FatalError, FatalErrorIn, UList< T >::fcIndex(), forAll, i, Foam::mag(), triangle< Point, PointRef >::normal(), p, patches, polyBoundaryMesh::patchID(), pFaces, Foam::Pout, tetrahedron< Point, PointRef >::Sa(), tetrahedron< Point, PointRef >::Sb(), tetrahedron< Point, PointRef >::Sc(), tetrahedron< Point, PointRef >::Sd(), List< T >::size(), and tetIndices::tet().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const particle< Type > &) friend
bool operator== (const particle< Type > & pA, const particle< Type > & pB) friend
bool operator!= (const particle< Type > & pA, const particle< Type > & pB) friend
Member Data Documentation
const polyMesh& mesh_ protected
Reference to the polyMesh database.
Definition at line 137 of file particle.H.
Referenced by wallBoundedParticle::currentEdge(), and particle< Type >::tetNeighbour().
vector position_ protected
Position of particle.
Definition at line 140 of file particle.H.
Referenced by Foam::operator<<(), and particle< Type >::particle().
label cellI_ protected
Index of the cell it is in.
Definition at line 143 of file particle.H.
Referenced by Foam::operator<<(), particle< Type >::particle(), and particle< Type >::tetNeighbour().
label faceI_ protected
Face index if the particle is on a face otherwise -1.
Definition at line 146 of file particle.H.
Referenced by Foam::operator<<(), and particle< Type >::particle().
scalar stepFraction_ protected
Fraction of time-step completed.
Definition at line 149 of file particle.H.
Referenced by Foam::operator<<(), and particle< Type >::particle().
label tetFaceI_ protected
Index of the face that owns the decomposed tet that the.
particle is in
Definition at line 153 of file particle.H.
Referenced by Foam::operator<<(), particle< Type >::particle(), and particle< Type >::tetNeighbour().
label tetPtI_ protected
Index of the point on the face that defines the decomposed.
tet that the particle is in. Relative to the face base point.
Definition at line 158 of file particle.H.
Referenced by Foam::operator<<(), particle< Type >::particle(), and particle< Type >::tetNeighbour().
label origProc_ protected
Originating processor id.
Definition at line 161 of file particle.H.
Referenced by Foam::operator<<(), particle< Type >::particle(), and particle< Type >::readFields().
label origId_ protected
Local particle id on originating processor.
Definition at line 164 of file particle.H.
Referenced by Foam::operator<<(), particle< Type >::particle(), and particle< Type >::readFields().
Foam::string propertyList_ = Foam::particle::propertyList() static
String representation of properties.
Definition at line 315 of file particle.H.
Foam::label particleCount_ = 0 static
Cumulative particle counter - used to provode unique ID.
Definition at line 315 of file particle.H.
const Foam::scalar trackingCorrectionTol = 1e-5 static
Fraction of distance to tet centre to move a particle to.
'rescue' it from a tracking problem
Definition at line 322 of file particle.H.
Referenced by sampledSet::pushIn().
const Foam::scalar lambdaDistanceToleranceCoeff = 1e3*SMALL static
Fraction of the cell volume to use in determining tolerance values.
for the denominator and numerator of lambda
Definition at line 326 of file particle.H.
const Foam::scalar minStepFractionTol = 1e5*SMALL static
Minimum stepFraction tolerance.
Definition at line 329 of file particle.H.
Referenced by KinematicParcel< ParcelType >::move().
The documentation for this class was generated from the following files:
src/lagrangian/basic/particle/particle.H
src/lagrangian/basic/particle/particle.C
src/lagrangian/basic/particle/particleI.H
src/lagrangian/basic/particle/particleIO.C
src/lagrangian/basic/particle/particleTemplates.C