OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
OFstream Class Reference
Output to file stream.
Public Member Functions
ClassName ("OFstream")
OFstream (const fileName &pathname, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct from pathname.
~OFstream ()
Destructor.
const fileName & name () const
Return the name of the stream.
fileName & name ()
Return non-const access to the name of the stream.
virtual ostream & stdStream ()
Access to underlying std::ostream.
virtual const ostream & stdStream () const
Const access to underlying std::ostream.
void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from OSstream
OSstream (ostream &os, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
virtual Ostream & write (const token &)
Write next token to stream.
virtual Ostream & write (const char)
Write character.
virtual Ostream & write (const char *)
Write character string.
virtual Ostream & write (const word &)
Write word.
virtual Ostream & write (const string &)
Write string.
virtual Ostream & writeQuoted (const std::string &, const bool quoted=true)
Write std::string surrounded by quotes.
virtual Ostream & write (const int32_t)
Write int32_t.
virtual Ostream & write (const int64_t)
Write int64_t.
virtual Ostream & write (const floatScalar)
Write floatScalar.
virtual Ostream & write (const doubleScalar)
Write doubleScalar.
virtual Ostream & write (const char *, std::streamsize)
Write binary block.
virtual void indent ()
Add indentation characters.
virtual ios_base::fmtflags flags (const ios_base::fmtflags flags)
Set flags of output stream.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual int width () const
Get width of output field.
virtual int width (const int)
Set width of output field (and return old width)
virtual int precision () const
Get precision of output field.
virtual int precision (const int)
Set precision of output field (and return old precision)
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Ostream ()
Destructor.
virtual Ostream & write (const keyType &)
Write keyType.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Incrememt the indent level.
void decrIndent ()
Decrememt the indent level.
Ostream & writeKeyword (const keyType &)
Write the keyword followed by an appropriate indentation.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from Ostream
unsigned short indentLevel_
Current indent level.
Protected Attributes inherited from IOstream
label lineNumber_
Static Protected Attributes inherited from Ostream
static const unsigned short indentSize_ = 4
Number of spaces per indent level.
static const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Detailed Description
Output to file stream.
Source files
OFstream.H
OFstream.C
Definition at line 81 of file OFstream.H.
Constructor & Destructor Documentation
OFstream (const fileName & pathname, streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED)
Construct from pathname.
Definition at line 88 of file OFstream.C.
References Foam::endl(), IOstream::good(), IOstream::info(), InfoInFunction, IOstream::lineNumber_, IOstream::setBad(), IOstream::setClosed(), IOstream::setOpened(), and IOstream::setState().
~OFstream ()
Destructor.
Definition at line 125 of file OFstream.C.
Member Function Documentation
ClassName ("OFstream")
const fileName& name () const inline virtual
Return the name of the stream.
Reimplemented from OSstream.
Definition at line 118 of file OFstream.H.
Referenced by polyDualMesh::calcFeatures(), processorPolyPatch::calcGeometry(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), meshRefinement::dumpIntersections(), indexedOctree< Type >::findLine(), dynamicIndexedOctree< Type >::findNearest(), processorPolyPatch::initOrder(), ListPlusEqOp< T, Size >::operator()(), nearestEqOp::operator()(), processorPolyPatch::order(), probes::prepare(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), externalCoupledMixedFvPatchField< Type >::transferData(), vtkSurfaceWriter::write(), OBJsurfaceFormat< Face >::write(), OBJedgeFormat::write(), ensightSurfaceWriter::write(), rawSurfaceWriter::write(), nastranSurfaceWriter::write(), graph::write(), starcdSurfaceWriter::writeData(), vtkSurfaceWriter::writeData(), dxSurfaceWriter::writeData(), rawSurfaceWriter::writeData(), externalCoupledMixedFvPatchField< Type >::writeGeometry(), surfaceFeatures::writeObj(), and extendedEdgeMesh::writeObj().
fileName& name () inline virtual
Return non-const access to the name of the stream.
Reimplemented from OSstream.
Definition at line 124 of file OFstream.H.
References Foam::Snull.
std::ostream & stdStream () virtual
Access to underlying std::ostream.
Reimplemented from OSstream.
Definition at line 131 of file OFstream.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by ensightFile::newline(), and ensightFile::write().
const std::ostream & stdStream () const virtual
Const access to underlying std::ostream.
Reimplemented from OSstream.
Definition at line 142 of file OFstream.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from OSstream.
Definition at line 153 of file OFstream.C.
References OSstream::print().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Fstreams/OFstream.H
src/OpenFOAM/db/IOstreams/Fstreams/OFstream.C