OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pairPotentialList Class Reference
Public Member Functions
pairPotentialList ()
pairPotentialList (const List< word > &idList, const dictionary &pairPotentialDict, const polyMesh &mesh)
Construct from idList and potental dictionaries.
~pairPotentialList ()
Destructor.
void buildPotentials (const List< word > &idList, const dictionary &pairPotentialDict, const polyMesh &mesh)
scalar rCutMax () const
scalar rCutMaxSqr () const
bool rCutMaxSqr (scalar rIJMagSqr) const
const pairPotential & pairPotentialFunction (const label a, const label b) const
bool rCutSqr (const label a, const label b, const scalar rIJMagSqr) const
scalar rMin (const label a, const label b) const
scalar dr (const label a, const label b) const
scalar rCutSqr (const label a, const label b) const
scalar rCut (const label a, const label b) const
scalar force (const label a, const label b, const scalar rIJMag) const
scalar energy (const label a, const label b, const scalar rIJMag) const
const pairPotential & electrostatic () const
Public Member Functions inherited from PtrList< pairPotential >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< pairPotential > &)
Copy constructor.
PtrList (const PtrList< pairPotential > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< pairPotential > > &)
Construct by transferring the parameter contents.
PtrList (PtrList< pairPotential > &, bool reUse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< pairPotential > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
pairPotential & first ()
Return reference to the first element of the list.
const pairPotential & first () const
Return reference to first element of the list.
pairPotential & last ()
Return reference to the last element of the list.
const pairPotential & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (pairPotential *)
Append an element at the end of the list.
void append (const autoPtr< pairPotential > &)
void append (const tmp< pairPotential > &)
void transfer (PtrList< pairPotential > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< pairPotential > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< pairPotential > set (const label, pairPotential *)
Set element. Return old element (can be NULL).
autoPtr< pairPotential > set (const label, const autoPtr< pairPotential > &)
autoPtr< pairPotential > set (const label, const tmp< pairPotential > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const pairPotential & operator[] (const label) const
Return element const reference.
pairPotential & operator[] (const label)
Return element reference.
const pairPotential * operator() (const label) const
Return element const pointer.
PtrList< pairPotential > & operator= (const PtrList< pairPotential > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
const_iterator end () const
Return an const_iterator to end traversing the PtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the PtrList.
const_iterator cend () const
Return an const_iterator to end traversing the PtrList.
Additional Inherited Members
Public Types inherited from PtrList< pairPotential >
typedef pairPotential value_type
Type of values the PtrList contains.
typedef pairPotential & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const pairPotential & const_reference
Type that can be used for storing into constant PtrList::value_type.
Protected Member Functions inherited from PtrList< pairPotential >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Source files
pairPotentialList.H
pairPotentialListI.H
pairPotentialList.C
Definition at line 51 of file pairPotentialList.H.
Constructor & Destructor Documentation
pairPotentialList ()
Definition at line 175 of file pairPotentialList.C.
pairPotentialList (const List< word > & idList, const dictionary & pairPotentialDict, const polyMesh & mesh)
Construct from idList and potental dictionaries.
Definition at line 182 of file pairPotentialList.C.
~pairPotentialList ()
Destructor.
Definition at line 196 of file pairPotentialList.C.
Member Function Documentation
void buildPotentials (const List< word > & idList, const dictionary & pairPotentialDict, const polyMesh & mesh)
Definition at line 203 of file pairPotentialList.C.
References setSize(), and List< T >::size().
Foam::scalar rCutMax () const inline
Definition at line 61 of file pairPotentialListI.H.
Foam::scalar rCutMaxSqr () const inline
Definition at line 67 of file pairPotentialListI.H.
bool rCutMaxSqr (scalar rIJMagSqr) const
Definition at line 227 of file pairPotentialList.C.
const Foam::pairPotential & pairPotentialFunction (const label a, const label b) const
Definition at line 218 of file pairPotentialList.C.
bool rCutSqr (const label a, const label b, const scalar rIJMagSqr) const
Definition at line 241 of file pairPotentialList.C.
Foam::scalar rMin (const label a, const label b) const
Definition at line 259 of file pairPotentialList.C.
Foam::scalar dr (const label a, const label b) const
Definition at line 269 of file pairPotentialList.C.
Foam::scalar rCutSqr (const label a, const label b) const
Definition at line 279 of file pairPotentialList.C.
Foam::scalar rCut (const label a, const label b) const
Definition at line 289 of file pairPotentialList.C.
Foam::scalar force (const label a, const label b, const scalar rIJMag) const
Definition at line 299 of file pairPotentialList.C.
References f().
Foam::scalar energy (const label a, const label b, const scalar rIJMag) const
Definition at line 312 of file pairPotentialList.C.
References Foam::e.
const Foam::pairPotential & electrostatic () const inline
Definition at line 73 of file pairPotentialListI.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/pairPotential/pairPotentialList/pairPotentialList.H
src/lagrangian/molecularDynamics/potential/pairPotential/pairPotentialList/pairPotentialList.C
src/lagrangian/molecularDynamics/potential/pairPotential/pairPotentialList/pairPotentialListI.H