OpenFOAM: options Class Reference
options Class Reference
Finite-volume options.
Public Member Functions
ClassName ("fvOptions")
options (const fvMesh &mesh)
Construct from components with list of field names.
virtual ~options ()
Destructor.
virtual bool read ()
Read dictionary.
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
iterator begin ()
const_iterator begin () const
const iterator & end ()
const const_iterator & end () const
const_iterator cbegin () const
const const_iterator & cend () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Public Member Functions inherited from optionList
TypeName ("optionList")
Runtime type information.
optionList (const fvMesh &mesh)
Construct null.
optionList (const fvMesh &mesh, const dictionary &dict)
Construct from mesh and dictionary.
virtual ~optionList ()
Destructor.
void reset (const dictionary &dict)
Reset the source list.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const geometricOneField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const geometricOneField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
void constrain (fvMatrix< Type > &eqn)
Apply constraints to equation.
template<class Type >
void correct (GeometricField< Type, fvPatchField, volMesh > &field)
Apply correction to field.
virtual bool read (const dictionary &dict)
Read dictionary.
virtual bool writeData (Ostream &os) const
Write data to Ostream.
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const geometricOneField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const geometricOneField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Public Member Functions inherited from PtrList< option >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< option > &)
Copy constructor.
PtrList (const PtrList< option > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< option >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< option > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< option > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (option *)
Append an element at the end of the list.
void append (const autoPtr< option > &)
void append (const tmp< option > &)
void transfer (PtrList< option > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< option > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< option > set (const label, option *)
Set element to given T* and return old element (can be NULL)
autoPtr< option > set (const label, const autoPtr< option > &)
Set element to given autoPtr<T> and return old element.
autoPtr< option > set (const label, const tmp< option > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< option > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Static Public Member Functions
static options & New (const fvMesh &mesh)
Construct fvOptions and register to datbase if not present.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase::iterator LListBase_iterator
typedef DLListBase::const_iterator LListBase_const_iterator
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from optionList
const dictionary & optionsDict (const dictionary &dict) const
Return the "options" sub-dictionary if present otherwise return dict.
bool readOptions (const dictionary &dict)
Read options dictionary.
void checkApplied () const
Check that all sources have been applied.
optionList (const optionList &)
Disallow default bitwise copy construct.
void operator= (const optionList &)
Disallow default bitwise assignment.
Protected Member Functions inherited from PtrList< option >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Attributes inherited from optionList
const fvMesh & mesh_
Reference to the mesh database.
label checkTimeIndex_
Time index to check that all defined sources have been applied.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Finite-volume options.
Source files
fvOptions.H
options.C
Definition at line 52 of file fvOptions.H.
Constructor & Destructor Documentation
options (const fvMesh & mesh)
Construct from components with list of field names.
Definition at line 94 of file fvOptions.C.
virtual ~options () inline virtual
Destructor.
Definition at line 86 of file fvOptions.H.
References options::read(), and optionList::read().
Member Function Documentation
ClassName ("fvOptions")
Foam::fv::options & New (const fvMesh & mesh) static
Construct fvOptions and register to datbase if not present.
otherwise lookup and return
Definition at line 103 of file fvOptions.C.
References Foam::endl(), objectRegistry::foundObject(), InfoInFunction, objectRegistry::lookupObject(), fvMesh::name(), regIOobject::store(), and fvMesh::thisDb().
Referenced by DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), kEqn< BasicTurbulenceModel >::correctNut(), kOmega< BasicTurbulenceModel >::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), continuousGasKEpsilon< BasicTurbulenceModel >::correctNut(), DeardorffDiffStress< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), NicenoKEqn< BasicTurbulenceModel >::correctNut(), realizableKE< BasicTurbulenceModel >::correctNut(), LaheyKEpsilon< BasicTurbulenceModel >::correctNut(), kEpsilon< BasicTurbulenceModel >::correctNut(), RNGkEpsilon< BasicTurbulenceModel >::correctNut(), LaunderSharmaKE< BasicTurbulenceModel >::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), SSG< BasicTurbulenceModel >::correctNut(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), LRR< BasicTurbulenceModel >::correctNut(), SpalartAllmaras< BasicTurbulenceModel >::correctNut(), SpalartAllmarasDES< BasicTurbulenceModel >::correctNut(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), v2f< BasicTurbulenceModel >::correctNut(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correctNut(), and phaseSystem::fvOptions().
bool read () virtual
Read dictionary.
Reimplemented from regIOobject.
Definition at line 128 of file fvOptions.C.
References Foam::read(), and optionList::read().
Referenced by options::~options().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/fvOptions/fvOptions.H
src/finiteVolume/cfdTools/general/fvOptions/fvOptions.C