OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointPatch Class Reference abstract
Basic pointPatch represents a set of points from the mesh.
Public Member Functions
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()
Destructor.
virtual const word & name () const =0
Return name.
virtual label size () const =0
Return size.
virtual label index () const =0
Return the index of this patch in the pointBoundaryMesh.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const =0
Return mesh points.
virtual const vectorField & localPoints () const =0
Return mesh points.
virtual const vectorField & pointNormals () const =0
Return point normals.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Friends
class pointBoundaryMesh
Detailed Description
Basic pointPatch represents a set of points from the mesh.
Source files
pointPatch.H
pointPatch.C
Definition at line 56 of file pointPatch.H.
Constructor & Destructor Documentation
pointPatch (const pointBoundaryMesh & bm) inline
Definition at line 114 of file pointPatch.H.
virtual ~pointPatch () inline virtual
Destructor.
Definition at line 123 of file pointPatch.H.
Member Function Documentation
virtual void initGeometry (PstreamBuffers &) inline protected virtual
Initialise the calculation of the patch geometry.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 81 of file pointPatch.H.
virtual void calcGeometry (PstreamBuffers &) inline protected virtual
Calculate the patch geometry.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, coupledFacePointPatch, and facePointPatch.
Definition at line 85 of file pointPatch.H.
virtual void initMovePoints (PstreamBuffers & , const pointField &) inline protected virtual
Initialise the patches for moving points.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 89 of file pointPatch.H.
virtual void movePoints (PstreamBuffers & , const pointField &) inline protected virtual
Correct patches after moving points.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 93 of file pointPatch.H.
virtual void initUpdateMesh (PstreamBuffers &) inline protected virtual
Initialise the update of the patch topology.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 97 of file pointPatch.H.
virtual void updateMesh (PstreamBuffers &) inline protected virtual
Update of the patch topology.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 101 of file pointPatch.H.
TypeName ("basePatch")
Runtime type information.
virtual const word& name () const pure virtual
Return name.
Implemented in facePointPatch.
Referenced by sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
virtual label size () const pure virtual
Return size.
Implemented in facePointPatch.
Referenced by angularOscillatingDisplacementPointPatchVectorField::angularOscillatingDisplacementPointPatchVectorField(), angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), fvMeshSubset::interpolate(), oscillatingVelocityPointPatchVectorField::oscillatingVelocityPointPatchVectorField(), sixDoFRigidBodyDisplacementPointPatchVectorField::sixDoFRigidBodyDisplacementPointPatchVectorField(), pointPatchMapper::size(), pointPatchField< Type >::size(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField(), and uniformFixedValuePointPatchField< Type >::uniformFixedValuePointPatchField().
virtual label index () const pure virtual
Return the index of this patch in the pointBoundaryMesh.
Implemented in facePointPatch.
const pointBoundaryMesh& boundaryMesh () const inline
Return boundaryMesh reference.
Definition at line 139 of file pointPatch.H.
Referenced by cyclicAMIPointPatch::neighbPatch(), cyclicPointPatch::neighbPatch(), and cyclicACMIPointPatch::neighbPatch().
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in facePointPatch, and cyclicACMIPointPatch.
Definition at line 145 of file pointPatch.H.
virtual const labelList& meshPoints () const pure virtual
Return mesh points.
Implemented in facePointPatch.
Referenced by fvMeshSubset::interpolate().
virtual const vectorField& localPoints () const pure virtual
Return mesh points.
Implemented in facePointPatch.
Referenced by angularOscillatingDisplacementPointPatchVectorField::angularOscillatingDisplacementPointPatchVectorField(), angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), oscillatingVelocityPointPatchVectorField::oscillatingVelocityPointPatchVectorField(), sixDoFRigidBodyDisplacementPointPatchVectorField::sixDoFRigidBodyDisplacementPointPatchVectorField(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), and angularOscillatingVelocityPointPatchVectorField::updateCoeffs().
virtual const vectorField& pointNormals () const pure virtual
Return point normals.
Implemented in facePointPatch, cyclicSlipPointPatch, and nonuniformTransformCyclicPointPatch.
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatch implements.
Reimplemented in processorPointPatch, cyclicACMIPointPatch, cyclicAMIPointPatch, cyclicPointPatch, symmetryPointPatch, symmetryPlanePointPatch, wedgePointPatch, and emptyPointPatch.
Definition at line 160 of file pointPatch.H.
References word::null.
Referenced by pointPatchField< T >::New().
virtual void applyConstraint (const label pointi, pointConstraint &) const inline virtual
Accumulate the effect of constraint direction of this patch.
Reimplemented in cyclicSlipPointPatch, nonuniformTransformCyclicPointPatch, symmetryPointPatch, symmetryPlanePointPatch, wedgePointPatch, and emptyPointPatch.
Definition at line 167 of file pointPatch.H.
Friends And Related Function Documentation
friend class pointBoundaryMesh friend
Definition at line 78 of file pointPatch.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/pointMesh/pointPatches/pointPatch/pointPatch.H