OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ParticleErosion< CloudType > Class Template Reference
Creates particle erosion field, Q.
Public Member Functions
TypeName ("particleErosion")
Runtime type information.
ParticleErosion (const dictionary &dict, CloudType &owner, const word &modelName)
Construct from dictionary.
ParticleErosion (const ParticleErosion< CloudType > &pe)
Construct copy.
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
Construct and return a clone.
virtual ~ParticleErosion ()
Destructor.
virtual void preEvolve ()
Pre-evolve hook.
virtual void postPatch (const parcelType &p, const polyPatch &pp, const scalar trackFraction, const tetIndices &tetIs, bool &keepParticle)
Post-patch hook.
Public Member Functions inherited from CloudFunctionObject< CloudType >
TypeName ("cloudFunctionObject")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
Declare runtime constructor selection table.
CloudFunctionObject (CloudType &owner)
Construct null from owner.
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Construct from dictionary.
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
Construct copy.
virtual ~CloudFunctionObject ()
Destructor.
virtual void postEvolve ()
Post-evolve hook.
virtual void postMove (typename CloudType::parcelType &p, const label celli, const scalar dt, const point &position0, bool &keepParticle)
Post-move hook.
virtual void postPatch (const typename CloudType::parcelType &p, const polyPatch &pp, const scalar trackFraction, const tetIndices &testIs, bool &keepParticle)
Post-patch hook.
virtual void postFace (const typename CloudType::parcelType &p, const label facei, bool &keepParticle)
Post-face hook.
const fileName & outputDir () const
Return the output path.
fileName writeTimeDir () const
Return the output time path.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Member Functions
label applyToPatch (const label globalPatchi) const
Returns local patchi if patch is in patchIds_ list.
virtual void write ()
Write post-processing info.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from CloudFunctionObject< CloudType >
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Selector.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::ParticleErosion< CloudType >
Creates particle erosion field, Q.
Source files
ParticleErosion.H
ParticleErosion.C
Definition at line 50 of file ParticleErosion.H.
Constructor & Destructor Documentation
ParticleErosion (const dictionary & dict, CloudType & owner, const word & modelName)
Construct from dictionary.
Definition at line 67 of file ParticleErosion.C.
References UList< T >::empty(), Foam::endl(), Foam::findStrings(), forAllReverse, HashSet< Key, Hash >::insert(), lookup(), HashTable< T, Key, Hash >::toc(), and WarningInFunction.
Referenced by ParticleErosion< CloudType >::write().
ParticleErosion (const ParticleErosion< CloudType > & pe)
Construct copy.
Definition at line 107 of file ParticleErosion.C.
~ParticleErosion () virtual
Destructor.
Definition at line 123 of file ParticleErosion.C.
Referenced by ParticleErosion< CloudType >::clone().
Member Function Documentation
Foam::label applyToPatch (const label globalPatchi) const protected
Returns local patchi if patch is in patchIds_ list.
Definition at line 32 of file ParticleErosion.C.
References forAll.
void write () protected virtual
Write post-processing info.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 49 of file ParticleErosion.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and ParticleErosion< CloudType >::ParticleErosion().
TypeName ("particleErosion")
Runtime type information.
virtual autoPtr<CloudFunctionObject<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 109 of file ParticleErosion.H.
References p, ParticleErosion< CloudType >::postPatch(), ParticleErosion< CloudType >::preEvolve(), and ParticleErosion< CloudType >::~ParticleErosion().
void preEvolve () virtual
Pre-evolve hook.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 130 of file ParticleErosion.C.
References Foam::dimVolume, mesh, Foam::name(), ParticleErosion< CloudType >::postPatch(), fvMesh::time(), and Time::timeName().
Referenced by ParticleErosion< CloudType >::clone().
void postPatch (const parcelType & p, const polyPatch & pp, const scalar trackFraction, const tetIndices & tetIs, bool & keepParticle) virtual
Post-patch hook.
Definition at line 162 of file ParticleErosion.C.
References Foam::acos(), Foam::constant::atomic::alpha, Foam::cos(), patchIdentifier::index(), Foam::mag(), nw, patchi, Foam::constant::mathematical::pi(), Foam::sin(), Foam::sqr(), Foam::tan(), U, and polyPatch::whichFace().
Referenced by ParticleErosion< CloudType >::clone(), and ParticleErosion< CloudType >::preEvolve().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleErosion/ParticleErosion.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/ParticleErosion/ParticleErosion.C