OpenFOAM: PilchErdman< CloudType > Class Template Reference
PilchErdman< CloudType > Class Template Reference
Particle secondary breakup model, based on the reference:
Public Member Functions
TypeName ("PilchErdman")
Runtime type information.
PilchErdman (const dictionary &, CloudType &)
Construct from dictionary.
PilchErdman (const PilchErdman< CloudType > &bum)
Construct copy.
virtual autoPtr< BreakupModel< CloudType > > clone () const
Construct and return a clone.
virtual ~PilchErdman ()
Destructor.
virtual bool update (const scalar dt, const vector &g, scalar &d, scalar &tc, scalar &ms, scalar &nParticle, scalar &KHindex, scalar &y, scalar &yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector &U, const scalar rhoc, const scalar muc, const vector &Urel, const scalar Urmag, const scalar tMom, scalar &dChild, scalar &massChild)
Update the parcel properties.
Public Member Functions inherited from BreakupModel< CloudType >
TypeName ("breakupModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, BreakupModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
BreakupModel (CloudType &owner)
Construct null from owner.
BreakupModel (const dictionary &dict, CloudType &owner, const word &type, bool solveOscillationEq=false)
Construct from dictionary.
BreakupModel (const BreakupModel< CloudType > &bum)
Construct copy.
virtual ~BreakupModel ()
Destructor.
const Switch & solveOscillationEq () const
const scalar & y0 () const
const scalar & yDot0 () const
const scalar & TABComega () const
const scalar & TABCmu () const
const scalar & TABtwoWeCrit () const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from BreakupModel< CloudType >
static autoPtr< BreakupModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from BreakupModel< CloudType >
Switch solveOscillationEq_
scalar y0_
scalar yDot0_
scalar TABComega_
scalar TABCmu_
scalar TABtwoWeCrit_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::PilchErdman< CloudType >
Particle secondary breakup model, based on the reference:
Pilch, M. and Erdman, C.A.
"Use of breakup time data and velocity history data
 to predict the maximum size of stable fragments for acceleration
 induced breakup of a liquid drop."
Int. J. Multiphase Flows 13 (1987), 741-757
The droplet fragment velocity is described by the equation:
Where: V_d : fragment velocity V : magnitude of the relative velocity epsilon : density ratio (rho_carrier/rho_droplet) T : characteristic break-up time B1, B2 : model input coefficients
The authors suggest that: compressible flow : B1 = 0.75*1.0; B2 = 3*0.116 incompressible flow : B1 = 0.75*0.5; B2 = 3*0.0758
Definition at line 71 of file PilchErdman.H.
Constructor & Destructor Documentation
PilchErdman (const dictionary & dict, CloudType & owner)
Construct from dictionary.
Definition at line 32 of file PilchErdman.C.
PilchErdman (const PilchErdman< CloudType > & bum)
Construct copy.
Definition at line 50 of file PilchErdman.C.
~PilchErdman () virtual
Destructor.
Definition at line 61 of file PilchErdman.C.
References PilchErdman< CloudType >::update().
Referenced by PilchErdman< CloudType >::clone().
Member Function Documentation
TypeName ("PilchErdman< CloudType >")
Runtime type information.
virtual autoPtr<BreakupModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements BreakupModel< CloudType >.
Definition at line 98 of file PilchErdman.H.
References g, Foam::constant::physicoChemical::mu, rho, Foam::constant::physicoChemical::sigma, U, PilchErdman< CloudType >::update(), Urel, y, and PilchErdman< CloudType >::~PilchErdman().
bool update (const scalar dt, const vector & g, scalar & d, scalar & tc, scalar & ms, scalar & nParticle, scalar & KHindex, scalar & y, scalar & yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector & U, const scalar rhoc, const scalar muc, const vector & Urel, const scalar Urmag, const scalar tMom, scalar & dChild, scalar & massChild) virtual
Update the parcel properties.
Implements BreakupModel< CloudType >.
Definition at line 69 of file PilchErdman.C.
References Foam::max(), Foam::pow(), Foam::pow3(), Foam::constant::physicoChemical::sigma, Foam::sqr(), and Foam::sqrt().
Referenced by PilchErdman< CloudType >::clone(), and PilchErdman< CloudType >::~PilchErdman().
The documentation for this class was generated from the following files:
src/lagrangian/spray/submodels/BreakupModel/PilchErdman/PilchErdman.H
src/lagrangian/spray/submodels/BreakupModel/PilchErdman/PilchErdman.C