OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PatchPostProcessing< CloudType > Class Template Reference
Standard post-processing.
Public Member Functions
TypeName ("patchPostProcessing")
Runtime type information.
PatchPostProcessing (const dictionary &dict, CloudType &owner, const word &modelName)
Construct from dictionary.
PatchPostProcessing (const PatchPostProcessing< CloudType > &ppm)
Construct copy.
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
Construct and return a clone.
virtual ~PatchPostProcessing ()
Destructor.
label maxStoredParcels () const
Return maximum number of parcels to store per patch.
const labelList & patchIDs () const
Return const mapping from local to global patch ids.
virtual void postPatch (const parcelType &p, const polyPatch &pp, const scalar trackFraction, const tetIndices &tetIs, bool &keepParticle)
Post-patch hook.
Public Member Functions inherited from CloudFunctionObject< CloudType >
TypeName ("cloudFunctionObject")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
Declare runtime constructor selection table.
CloudFunctionObject (CloudType &owner)
Construct null from owner.
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Construct from dictionary.
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
Construct copy.
virtual ~CloudFunctionObject ()
Destructor.
virtual void preEvolve ()
Pre-evolve hook.
virtual void postEvolve ()
Post-evolve hook.
virtual void postMove (typename CloudType::parcelType &p, const label cellI, const scalar dt, const point &position0, bool &keepParticle)
Post-move hook.
virtual void postPatch (const typename CloudType::parcelType &p, const polyPatch &pp, const scalar trackFraction, const tetIndices &testIs, bool &keepParticle)
Post-patch hook.
virtual void postFace (const typename CloudType::parcelType &p, const label faceI, bool &keepParticle)
Post-face hook.
const fileName & outputDir () const
Return the output path.
fileName outputTimeDir () const
Return the output time path.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Member Functions
void write ()
Write post-processing info.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from CloudFunctionObject< CloudType >
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Selector.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::PatchPostProcessing< CloudType >
Standard post-processing.
Source files
PatchPostProcessing.H
PatchPostProcessing.C
Definition at line 49 of file PatchPostProcessing.H.
Constructor & Destructor Documentation
PatchPostProcessing (const dictionary & dict, CloudType & owner, const word & modelName)
Construct from dictionary.
Definition at line 125 of file PatchPostProcessing.C.
References UList< T >::empty(), Foam::endl(), Foam::findStrings(), forAll, forAllReverse, Foam::Info, HashSet< Key, Hash >::insert(), lookup(), HashTable< T, Key, Hash >::toc(), and WarningInFunction.
Referenced by PatchPostProcessing< CloudType >::write().
PatchPostProcessing (const PatchPostProcessing< CloudType > & ppm)
Construct copy.
Definition at line 174 of file PatchPostProcessing.C.
~PatchPostProcessing () virtual
Destructor.
Definition at line 189 of file PatchPostProcessing.C.
References PatchPostProcessing< CloudType >::postPatch().
Referenced by PatchPostProcessing< CloudType >::clone().
Member Function Documentation
void write () protected virtual
Write post-processing info.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 55 of file PatchPostProcessing.C.
References polyMesh::boundaryMesh(), forAll, mesh, Foam::mkDir(), IOobject::name(), Foam::nl, PatchPostProcessing< CloudType >::PatchPostProcessing(), Foam::sortedOrder(), fvMesh::time(), and Time::writeCompression().
TypeName ("patchPostProcessing")
Runtime type information.
virtual autoPtr<CloudFunctionObject<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 104 of file PatchPostProcessing.H.
References PatchPostProcessing< CloudType >::maxStoredParcels(), p, PatchPostProcessing< CloudType >::patchIDs(), PatchPostProcessing< CloudType >::postPatch(), and PatchPostProcessing< CloudType >::~PatchPostProcessing().
Foam::label maxStoredParcels () const inline
Return maximum number of parcels to store per patch.
Definition at line 27 of file PatchPostProcessingI.H.
Referenced by PatchPostProcessing< CloudType >::clone().
const Foam::labelList & patchIDs () const inline
Return const mapping from local to global patch ids.
Definition at line 34 of file PatchPostProcessingI.H.
Referenced by PatchPostProcessing< CloudType >::clone().
void postPatch (const parcelType & p, const polyPatch & pp, const scalar trackFraction, const tetIndices & tetIs, bool & keepParticle) virtual
Post-patch hook.
Definition at line 197 of file PatchPostProcessing.C.
References patchIdentifier::index(), p, and OStringStream::str().
Referenced by PatchPostProcessing< CloudType >::clone(), and PatchPostProcessing< CloudType >::~PatchPostProcessing().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/PatchPostProcessing/PatchPostProcessing.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/PatchPostProcessing/PatchPostProcessing.C
src/lagrangian/intermediate/submodels/CloudFunctionObjects/PatchPostProcessing/PatchPostProcessingI.H