OpenFOAM-dev: PhaseCompressibleTurbulenceModel< TransportModel > Class Template Reference 2
PhaseCompressibleTurbulenceModel< TransportModel > Class Template Reference
Templated abstract base class for multiphase compressible turbulence models.
Public Types
typedef volScalarField alphaField
typedef volScalarField rhoField
typedef TransportModel transportModel
Public Member Functions
PhaseCompressibleTurbulenceModel (const word &type, const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasport, const word &propertiesName)
Construct.
virtual ~PhaseCompressibleTurbulenceModel ()
Destructor.
virtual tmp< volScalarField > mu () const
Return the laminar dynamic viscosity.
virtual tmp< scalarField > mu (const label patchi) const
Return the laminar dynamic viscosity on patch.
virtual tmp< volScalarField > mut () const
Return the turbulence dynamic viscosity.
virtual tmp< scalarField > mut (const label patchi) const
Return the turbulence dynamic viscosity on patch.
virtual tmp< volScalarField > muEff () const
Return the effective dynamic viscosity.
virtual tmp< scalarField > muEff (const label patchi) const
Return the effective dynamic viscosity on patch.
virtual tmp< volScalarField > pPrime () const
Return the phase-pressure'.
virtual tmp< surfaceScalarField > pPrimef () const
Return the face-phase-pressure'.
Static Public Member Functions
static autoPtr< PhaseCompressibleTurbulenceModel > New (const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Detailed Description
template<class TransportModel>
class Foam::PhaseCompressibleTurbulenceModel< TransportModel >
Templated abstract base class for multiphase compressible turbulence models.
Source files
PhaseCompressibleTurbulenceModel.H
PhaseCompressibleTurbulenceModel.C
Definition at line 51 of file PhaseCompressibleTurbulenceModel.H.
Member Typedef Documentation
typedef volScalarField alphaField
Definition at line 64 of file PhaseCompressibleTurbulenceModel.H.
typedef volScalarField rhoField
Definition at line 65 of file PhaseCompressibleTurbulenceModel.H.
typedef TransportModel transportModel
Definition at line 66 of file PhaseCompressibleTurbulenceModel.H.
Constructor & Destructor Documentation
PhaseCompressibleTurbulenceModel (const word & type, const alphaField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & trasport, const word & propertiesName)
Construct.
Definition at line 33 of file PhaseCompressibleTurbulenceModel.C.
References PhaseCompressibleTurbulenceModel< TransportModel >::New().
virtual ~PhaseCompressibleTurbulenceModel () inline virtual
Destructor.
Definition at line 101 of file PhaseCompressibleTurbulenceModel.H.
Member Function Documentation
Foam::autoPtr< Foam::PhaseCompressibleTurbulenceModel< TransportModel > > New (const alphaField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & trasportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Definition at line 68 of file PhaseCompressibleTurbulenceModel.C.
References Foam::New().
Referenced by PhaseCompressibleTurbulenceModel< TransportModel >::PhaseCompressibleTurbulenceModel().
virtual tmp<volScalarField> mu () const inline virtual
Return the laminar dynamic viscosity.
Definition at line 108 of file PhaseCompressibleTurbulenceModel.H.
Referenced by PhaseCompressibleTurbulenceModel< Foam::phaseModel >::muEff().
virtual tmp<scalarField> mu (const label patchi) const inline virtual
Return the laminar dynamic viscosity on patch.
Definition at line 114 of file PhaseCompressibleTurbulenceModel.H.
virtual tmp<volScalarField> mut () const inline virtual
Return the turbulence dynamic viscosity.
Definition at line 120 of file PhaseCompressibleTurbulenceModel.H.
Referenced by PhaseCompressibleTurbulenceModel< Foam::phaseModel >::muEff().
virtual tmp<scalarField> mut (const label patchi) const inline virtual
Return the turbulence dynamic viscosity on patch.
Definition at line 126 of file PhaseCompressibleTurbulenceModel.H.
virtual tmp<volScalarField> muEff () const inline virtual
Return the effective dynamic viscosity.
Definition at line 132 of file PhaseCompressibleTurbulenceModel.H.
virtual tmp<scalarField> muEff (const label patchi) const inline virtual
Return the effective dynamic viscosity on patch.
Definition at line 138 of file PhaseCompressibleTurbulenceModel.H.
Foam::tmp< Foam::volScalarField > pPrime () const virtual
Return the phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Definition at line 105 of file PhaseCompressibleTurbulenceModel.C.
References Foam::dimPressure.
Referenced by PhaseCompressibleTurbulenceModel< Foam::phaseModel >::muEff().
Foam::tmp< Foam::surfaceScalarField > pPrimef () const virtual
Return the face-phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Definition at line 128 of file PhaseCompressibleTurbulenceModel.C.
References Foam::dimPressure.
Referenced by PhaseCompressibleTurbulenceModel< Foam::phaseModel >::muEff().
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/PhaseCompressibleTurbulenceModel/PhaseCompressibleTurbulenceModel.H
src/TurbulenceModels/phaseCompressible/PhaseCompressibleTurbulenceModel/PhaseCompressibleTurbulenceModel.C