OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PhaseIncompressibleTurbulenceModel< TransportModel > Class Template Reference
Templated abstract base class for multiphase incompressible turbulence models.
Public Types
typedef volScalarField alphaField
typedef geometricOneField rhoField
typedef TransportModel transportModel
Public Member Functions
PhaseIncompressibleTurbulenceModel (const word &type, const alphaField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const TransportModel &trasportModel, const word &propertiesName)
Construct.
virtual ~PhaseIncompressibleTurbulenceModel ()
Destructor.
virtual tmp< volScalarField > pPrime () const
Return the phase-pressure'.
virtual tmp< surfaceScalarField > pPrimef () const
Return the face-phase-pressure'.
virtual tmp< volSymmTensorField > devReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
Static Public Member Functions
static autoPtr< PhaseIncompressibleTurbulenceModel > New (const alphaField &alpha, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const TransportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Detailed Description
template<class TransportModel>
class Foam::PhaseIncompressibleTurbulenceModel< TransportModel >
Templated abstract base class for multiphase incompressible turbulence models.
Source files
PhaseIncompressibleTurbulenceModel.H
PhaseIncompressibleTurbulenceModel.C
Definition at line 51 of file PhaseIncompressibleTurbulenceModel.H.
Member Typedef Documentation
typedef volScalarField alphaField
Definition at line 64 of file PhaseIncompressibleTurbulenceModel.H.
typedef geometricOneField rhoField
Definition at line 65 of file PhaseIncompressibleTurbulenceModel.H.
typedef TransportModel transportModel
Definition at line 66 of file PhaseIncompressibleTurbulenceModel.H.
Constructor & Destructor Documentation
PhaseIncompressibleTurbulenceModel (const word & type, const alphaField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const TransportModel & trasportModel, const word & propertiesName)
Construct.
Definition at line 33 of file PhaseIncompressibleTurbulenceModel.C.
References PhaseIncompressibleTurbulenceModel< TransportModel >::New().
virtual ~PhaseIncompressibleTurbulenceModel () inline virtual
Destructor.
Definition at line 100 of file PhaseIncompressibleTurbulenceModel.H.
References PhaseIncompressibleTurbulenceModel< TransportModel >::devReff(), PhaseIncompressibleTurbulenceModel< TransportModel >::devRhoReff(), PhaseIncompressibleTurbulenceModel< TransportModel >::divDevReff(), PhaseIncompressibleTurbulenceModel< TransportModel >::divDevRhoReff(), PhaseIncompressibleTurbulenceModel< TransportModel >::pPrime(), PhaseIncompressibleTurbulenceModel< TransportModel >::pPrimef(), and U.
Member Function Documentation
Foam::autoPtr< Foam::PhaseIncompressibleTurbulenceModel< TransportModel > > New (const alphaField & alpha, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const TransportModel & trasportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Definition at line 68 of file PhaseIncompressibleTurbulenceModel.C.
References Foam::New().
Referenced by PhaseIncompressibleTurbulenceModel< TransportModel >::PhaseIncompressibleTurbulenceModel().
Foam::tmp< Foam::volScalarField > pPrime () const virtual
Return the phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Definition at line 104 of file PhaseIncompressibleTurbulenceModel.C.
References Foam::dimPressure.
Referenced by PhaseIncompressibleTurbulenceModel< TransportModel >::~PhaseIncompressibleTurbulenceModel().
Foam::tmp< Foam::surfaceScalarField > pPrimef () const virtual
Return the face-phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Definition at line 127 of file PhaseIncompressibleTurbulenceModel.C.
References Foam::dimPressure.
Referenced by PhaseIncompressibleTurbulenceModel< TransportModel >::~PhaseIncompressibleTurbulenceModel().
Foam::tmp< Foam::volSymmTensorField > devReff () const virtual
Return the effective stress tensor.
Definition at line 150 of file PhaseIncompressibleTurbulenceModel.C.
References PhaseIncompressibleTurbulenceModel< TransportModel >::divDevReff().
Referenced by PhaseIncompressibleTurbulenceModel< TransportModel >::~PhaseIncompressibleTurbulenceModel().
Foam::tmp< Foam::fvVectorMatrix > divDevReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 159 of file PhaseIncompressibleTurbulenceModel.C.
References PhaseIncompressibleTurbulenceModel< TransportModel >::devRhoReff().
Referenced by PhaseIncompressibleTurbulenceModel< TransportModel >::devReff(), and PhaseIncompressibleTurbulenceModel< TransportModel >::~PhaseIncompressibleTurbulenceModel().
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Return the effective stress tensor.
Definition at line 170 of file PhaseIncompressibleTurbulenceModel.C.
References PhaseIncompressibleTurbulenceModel< TransportModel >::divDevRhoReff(), and NotImplemented.
Referenced by PhaseIncompressibleTurbulenceModel< TransportModel >::divDevReff(), and PhaseIncompressibleTurbulenceModel< TransportModel >::~PhaseIncompressibleTurbulenceModel().
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 182 of file PhaseIncompressibleTurbulenceModel.C.
References NotImplemented.
Referenced by PhaseIncompressibleTurbulenceModel< TransportModel >::devRhoReff(), and PhaseIncompressibleTurbulenceModel< TransportModel >::~PhaseIncompressibleTurbulenceModel().
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseIncompressible/PhaseIncompressibleTurbulenceModel/PhaseIncompressibleTurbulenceModel.H
src/TurbulenceModels/phaseIncompressible/PhaseIncompressibleTurbulenceModel/PhaseIncompressibleTurbulenceModel.C