OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pairGAMGAgglomeration Class Reference
Agglomerate using the pair algorithm.
Public Member Functions
TypeName ("pair")
Runtime type information.
pairGAMGAgglomeration (const lduMesh &mesh, const dictionary &controlDict)
Construct given mesh and controls.
Public Member Functions inherited from GAMGAgglomeration
TypeName ("GAMGAgglomeration")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, lduMesh,(const lduMesh &mesh, const dictionary &controlDict),(mesh, controlDict))
Runtime selection table for pure geometric agglomerators.
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, lduMatrix,(const lduMatrix &matrix, const dictionary &controlDict),(matrix, controlDict))
Runtime selection table for matrix or mixed geometric/matrix.
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, geometry,(const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict),(mesh, cellVolumes, faceAreas, controlDict))
Runtime selection table for matrix or mixed geometric/matrix.
GAMGAgglomeration (const lduMesh &mesh, const dictionary &controlDict)
Construct given mesh and controls.
~GAMGAgglomeration ()
Destructor.
label size () const
const lduMesh & meshLevel (const label leveli) const
Return LDU mesh of given level.
bool hasMeshLevel (const label leveli) const
Do we have mesh for given level?
const lduInterfacePtrsList & interfaceLevel (const label leveli) const
Return LDU interface addressing of given level.
const labelField & restrictAddressing (const label leveli) const
Return cell restrict addressing of given level.
const labelList & faceRestrictAddressing (const label leveli) const
Return face restrict addressing of given level.
const labelListList & patchFaceRestrictAddressing (const label leveli) const
const boolList & faceFlipMap (const label leveli) const
Return face flip map of given level.
label nCells (const label leveli) const
Return number of coarse cells (before processor agglomeration)
label nFaces (const label leveli) const
Return number of coarse faces (before processor agglomeration)
const labelList & nPatchFaces (const label leveli) const
Return number of coarse patch faces (before processor.
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex, const bool procAgglom) const
Restrict (integrate by summation) cell field.
template<class Type >
void restrictFaceField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex) const
Restrict (integrate by summation) face field.
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const labelList &fineToCoarse) const
Restrict (integrate by summation) cell field.
template<class Type >
void prolongField (Field< Type > &ff, const Field< Type > &cf, const label coarseLevelIndex, const bool procAgglom) const
Prolong (interpolate by injection) cell field.
bool processorAgglomerate () const
Whether to agglomerate across processors.
const labelList & procAgglomMap (const label fineLeveli) const
Mapping from processor to agglomerated processor (global, all.
const labelList & agglomProcIDs (const label fineLeveli) const
Set of processors to agglomerate. Element 0 is the.
bool hasProcMesh (const label fineLeveli) const
Check that level has combined mesh.
label procCommunicator (const label fineLeveli) const
Communicator for current level or -1.
const labelList & cellOffsets (const label fineLeveli) const
Mapping from processor to procMesh cells.
const labelListList & faceMap (const label fineLeveli) const
Mapping from processor to procMesh face.
const labelListList & boundaryMap (const label fineLeveli) const
Mapping from processor to procMesh boundary.
const labelListListList & boundaryFaceMap (const label fineLeveli) const
Mapping from processor to procMesh boundary face.
Public Member Functions inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
MeshObject (const lduMesh &mesh)
virtual ~MeshObject ()
const lduMesh & mesh () const
virtual bool writeData (Foam::Ostream &) const
Public Member Functions inherited from GeometricMeshObject< lduMesh >
GeometricMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from TopologicalMeshObject< lduMesh >
TopologicalMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from meshObject
ClassName ("meshObject")
meshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static tmp< labelField > agglomerate (label &nCoarseCells, const lduAddressing &fineMatrixAddressing, const scalarField &faceWeights)
Calculate and return agglomeration.
Static Public Member Functions inherited from GAMGAgglomeration
static const GAMGAgglomeration & New (const lduMesh &mesh, const dictionary &controlDict)
Return the selected geometric agglomerator.
static const GAMGAgglomeration & New (const lduMatrix &matrix, const dictionary &controlDict)
Return the selected matrix agglomerator.
static autoPtr< GAMGAgglomeration > New (const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict)
Return the selected geometric agglomerator.
static void calculateRegionMaster (const label comm, const labelList &procAgglomMap, labelList &masterProcs, List< label > &agglomProcIDs)
Given fine to coarse processor map determine:
static bool checkRestriction (labelList &newRestrict, label &nNewCoarse, const lduAddressing &fineAddressing, const labelUList &restrict, const label nCoarse)
Given restriction determines if coarse cells are connected.
Static Public Member Functions inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
static const GAMGAgglomeration & New (const lduMesh &mesh)
static const GAMGAgglomeration & New (const lduMesh &mesh, const Data1 &d)
static const GAMGAgglomeration & New (const lduMesh &mesh, const Data1 &, const Data2 &)
static const GAMGAgglomeration & New (const lduMesh &mesh, const Data1 &, const Data2 &, const Data3 &)
static const GAMGAgglomeration & New (const lduMesh &mesh, const Data1 &, const Data2 &, const Data3 &, const Data4 &)
static bool Delete (const lduMesh &mesh)
Static Public Member Functions inherited from meshObject
template<class Mesh >
static void movePoints (objectRegistry &)
template<class Mesh >
static void updateMesh (objectRegistry &, const mapPolyMesh &)
template<class Mesh , template< class > class MeshObjectType>
static void clear (objectRegistry &)
template<class Mesh , template< class > class FromType, template< class > class ToType>
static void clearUpto (objectRegistry &)
Clear all meshObject derived from FromType up to (but not including)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Protected Member Functions
void agglomerate (const lduMesh &mesh, const scalarField &faceWeights)
Agglomerate all levels starting from the given face weights.
pairGAMGAgglomeration (const pairGAMGAgglomeration &)
Disallow default bitwise copy construct.
void operator= (const pairGAMGAgglomeration &)
Disallow default bitwise assignment.
Protected Member Functions inherited from GAMGAgglomeration
void agglomerateLduAddressing (const label fineLevelIndex)
Assemble coarse mesh addressing.
void combineLevels (const label curLevel)
Combine a level with the previous one.
void compactLevels (const label nCreatedLevels)
Shrink the number of levels to that specified.
bool continueAgglomerating (const label nCoarseCells) const
Check the need for further agglomeration.
void clearLevel (const label leveli)
void procAgglomerateLduAddressing (const label comm, const labelList &procAgglomMap, const labelList &procIDs, const label allMeshComm, const label levelIndex)
Collect and combine processor meshes into allMesh:
void procAgglomerateRestrictAddressing (const label comm, const labelList &procIDs, const label levelIndex)
Collect and combine basic restriction addressing:
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Protected Member Functions inherited from GAMGAgglomeration
template<class Type >
static void gatherList (const label comm, const labelList &procIDs, const Type &myVal, List< Type > &allVals, const int tag=Pstream::msgType())
Gather value from all procIDs onto procIDs[0].
Protected Attributes inherited from GAMGAgglomeration
const label maxLevels_
Max number of levels.
const label nCellsInCoarsestLevel_
Number of cells in coarsest level.
const lduInterfacePtrsList meshInterfaces_
Cached mesh interfaces.
autoPtr< GAMGProcAgglomeration > procAgglomeratorPtr_
labelList nCells_
The number of cells in each level.
PtrList< labelField > restrictAddressing_
Cell restriction addressing array.
labelList nFaces_
The number of (coarse) faces in each level.
PtrList< labelList > faceRestrictAddressing_
Face restriction addressing array.
PtrList< boolList > faceFlipMap_
Face flip: for faces mapped to internal faces stores whether.
PtrList< labelList > nPatchFaces_
The number of (coarse) patch faces in each level.
PtrList< labelListList > patchFaceRestrictAddressing_
Patch-local face restriction addressing array.
PtrList< lduPrimitiveMesh > meshLevels_
Hierarchy of mesh addressing.
PtrList< labelList > procAgglomMap_
Per level, per processor the processor it agglomerates into.
PtrList< labelList > agglomProcIDs_
Per level the set of processors to agglomerate. Element 0 is.
labelList procCommunicator_
Communicator for given level.
PtrList< labelList > procCellOffsets_
Mapping from processor to procMeshLevel cells.
PtrList< labelListList > procFaceMap_
Mapping from processor to procMeshLevel face.
PtrList< labelListList > procBoundaryMap_
Mapping from processor to procMeshLevel boundary.
PtrList< labelListListList > procBoundaryFaceMap_
Mapping from processor to procMeshLevel boundary face.
Protected Attributes inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
const lduMesh & mesh_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Agglomerate using the pair algorithm.
Source files
pairGAMGAgglomeration.H
pairGAMGAgglomeration.C
pairGAMGAgglomerate.C
Definition at line 49 of file pairGAMGAgglomeration.H.
Constructor & Destructor Documentation
pairGAMGAgglomeration (const pairGAMGAgglomeration &) protected
Disallow default bitwise copy construct.
pairGAMGAgglomeration (const lduMesh & mesh, const dictionary & controlDict)
Construct given mesh and controls.
Definition at line 40 of file pairGAMGAgglomeration.C.
Member Function Documentation
void agglomerate (const lduMesh & mesh, const scalarField & faceWeights) protected
Agglomerate all levels starting from the given face weights.
Definition at line 32 of file pairGAMGAgglomerate.C.
void operator= (const pairGAMGAgglomeration &) protected
Disallow default bitwise assignment.
TypeName ("pair")
Runtime type information.
Foam::tmp< Foam::labelField > agglomerate (label & nCoarseCells, const lduAddressing & fineMatrixAddressing, const scalarField & faceWeights) static
Calculate and return agglomeration.
Definition at line 121 of file pairGAMGAgglomerate.C.
References forAll, lduAddressing::lowerAddr(), Foam::max(), tmp< T >::ref(), lduAddressing::size(), UList< T >::size(), and lduAddressing::upperAddr().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/pairGAMGAgglomeration/pairGAMGAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/pairGAMGAgglomeration/pairGAMGAgglomerate.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/pairGAMGAgglomeration/pairGAMGAgglomeration.C