OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
plane Class Reference
Translation constraint on the centre of rotation: may only move on a plane.
Public Member Functions
TypeName ("plane")
Runtime type information.
plane (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const
Construct and return a clone.
virtual ~plane ()
Destructor.
virtual void setCentreOfRotation (point &) const
Set the centre of rotation to the projection of the.
virtual void constrainTranslation (pointConstraint &) const
Apply and accumulate translational constraints.
virtual void constrainRotation (pointConstraint &) const
Apply and accumulate rotational constraints.
virtual bool read (const dictionary &sDoFRBMCCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
TypeName ("sixDoFRigidBodyMotionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from the sDoFRBMCDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionConstraint ()
Destructor.
const word & name () const
Return the name.
virtual void setCentreOfRotation (point &) const
Set the centre of rotation if not the centre of mass.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
static autoPtr< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Select constructed from the sDoFRBMCDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionConstraint
word name_
Name of the constraint.
dictionary sDoFRBMCCoeffs_
Constraint model specific coefficient dictionary.
const sixDoFRigidBodyMotion & motion_
Reference to the body motion.
Detailed Description
Translation constraint on the centre of rotation: may only move on a plane.
If 'centreOfRotation' is not provided in the dictionary the centre of mass is used.
Source files
sixDoFRigidBodyMotionPlaneConstraint.H
sixDoFRigidBodyMotionPlaneConstraint.C
Definition at line 55 of file sixDoFRigidBodyMotionPlaneConstraint.H.
Constructor & Destructor Documentation
plane (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Construct from components.
Definition at line 51 of file sixDoFRigidBodyMotionPlaneConstraint.C.
References Foam::read().
Referenced by plane::clone().
~plane () virtual
Destructor.
Definition at line 65 of file sixDoFRigidBodyMotionPlaneConstraint.C.
Member Function Documentation
TypeName ("plane")
Runtime type information.
virtual autoPtr<sixDoFRigidBodyMotionConstraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 85 of file sixDoFRigidBodyMotionPlaneConstraint.H.
References plane::plane().
void setCentreOfRotation (point & CofR) const virtual
Set the centre of rotation to the projection of the.
centre of mass onto the plane
Definition at line 72 of file sixDoFRigidBodyMotionPlaneConstraint.C.
void constrainTranslation (pointConstraint & pc) const virtual
Apply and accumulate translational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 81 of file sixDoFRigidBodyMotionPlaneConstraint.C.
References pointConstraint::applyConstraint().
void constrainRotation (pointConstraint & pc) const virtual
Apply and accumulate rotational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 90 of file sixDoFRigidBodyMotionPlaneConstraint.C.
bool read (const dictionary & sDoFRBMCCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 97 of file sixDoFRigidBodyMotionPlaneConstraint.C.
References sixDoFRigidBodyMotionConstraint::read().
void write (Ostream & os) const virtual
Write.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 116 of file sixDoFRigidBodyMotionPlaneConstraint.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/plane/sixDoFRigidBodyMotionPlaneConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/plane/sixDoFRigidBodyMotionPlaneConstraint.C