OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PBiCG Class Reference
Preconditioned bi-conjugate gradient solver for asymmetric lduMatrices using a run-time selectable preconditiioner.
Public Member Functions
TypeName ("PBiCG")
Runtime type information.
PBiCG (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Construct from matrix components and solver data stream.
virtual ~PBiCG ()
Destructor.
virtual solverPerformance solve (scalarField &psi, const scalarField &source, const direction cmpt=0) const
Solve the matrix with this solver.
Public Member Functions inherited from lduMatrix::solver
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
solver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~solver ()
Destructor.
const word & fieldName () const
const lduMatrix & matrix () const
const FieldField< Field, scalar > & interfaceBouCoeffs () const
const FieldField< Field, scalar > & interfaceIntCoeffs () const
const lduInterfaceFieldPtrsList & interfaces () const
virtual void read (const dictionary &)
Read and reset the solver parameters from the given stream.
scalar normFactor (const scalarField &psi, const scalarField &source, const scalarField &Apsi, scalarField &tmpField) const
Return the matrix norm used to normalise the residual for the.
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::solver
static autoPtr< solver > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Return a new solver.
Protected Member Functions inherited from lduMatrix::solver
virtual void readControls ()
Read the control parameters from the controlDict_.
Protected Attributes inherited from lduMatrix::solver
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
lduInterfaceFieldPtrsList interfaces_
dictionary controlDict_
Dictionary of controls.
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
scalar tolerance_
Final convergence tolerance.
scalar relTol_
Convergence tolerance relative to the initial.
Detailed Description
Preconditioned bi-conjugate gradient solver for asymmetric lduMatrices using a run-time selectable preconditiioner.
Source files
PBiCG.H
PBiCG.C
Definition at line 49 of file PBiCG.H.
Constructor & Destructor Documentation
PBiCG (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls)
Construct from matrix components and solver data stream.
Definition at line 42 of file PBiCG.C.
References PBiCG::solve().
virtual ~PBiCG () inline virtual
Destructor.
Definition at line 83 of file PBiCG.H.
References psi, and PBiCG::solve().
Member Function Documentation
TypeName ("PBiCG")
Runtime type information.
Foam::solverPerformance solve (scalarField & psi, const scalarField & source, const direction cmpt = 0) const virtual
Solve the matrix with this solver.
Implements lduMatrix::solver.
Definition at line 66 of file PBiCG.C.
References Foam::constant::atomic::alpha, UList< T >::begin(), beta(), SolverPerformance< Type >::checkConvergence(), SolverPerformance< Type >::checkSingularity(), Foam::endl(), SolverPerformance< Type >::finalResidual(), lduMatrix::preconditioner::getName(), SolverPerformance< Type >::great_, Foam::gSumMag(), Foam::gSumProd(), Foam::Info, SolverPerformance< Type >::initialResidual(), Foam::mag(), lduMatrix::mesh(), lduMatrix::preconditioner::New(), SolverPerformance< Type >::nIterations(), and List< T >::size().
Referenced by PBiCG::PBiCG(), GAMGSolver::solve(), and PBiCG::~PBiCG().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/PBiCG/PBiCG.H
src/OpenFOAM/matrices/lduMatrix/solvers/PBiCG/PBiCG.C