OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
partialWrite Class Reference
FunctionObjects » Utility function objects
This function object allows user-selected fields/registered objects to be written at a custom write interval. The interval is given in terms of number of overall dumps.
Public Member Functions
TypeName ("partialWrite")
Runtime type information.
partialWrite (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~partialWrite ()
Destructor.
virtual const word & name () const
Return name of the partialWrite.
virtual void read (const dictionary &)
Read the partialWrite data.
virtual void execute ()
Execute.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write the partialWrite.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
partialWrite (const partialWrite &)
Disallow default bitwise copy construct.
void operator= (const partialWrite &)
Disallow default bitwise assignment.
template<class Type >
void loadField (const word &, UPtrList< GeometricField< Type, fvPatchField, volMesh >> &, UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &) const
Load objects in the objectNames.
template<class Type >
void changeWriteOptions (UPtrList< GeometricField< Type, fvPatchField, volMesh >> &, UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &, const IOobject::writeOption) const
Protected Attributes
word name_
Name of this partialWrite functionObject.
const objectRegistry & obr_
UPtrList< volScalarField > vsf_
Loaded fields.
UPtrList< volVectorField > vvf_
UPtrList< volSphericalTensorField > vSpheretf_
UPtrList< volSymmTensorField > vSymmtf_
UPtrList< volTensorField > vtf_
UPtrList< surfaceScalarField > ssf_
UPtrList< surfaceVectorField > svf_
UPtrList< surfaceSphericalTensorField > sSpheretf_
UPtrList< surfaceSymmTensorField > sSymmtf_
UPtrList< surfaceTensorField > stf_
HashSet< word > objectNames_
Names of objects to dump always.
label writeInterval_
Write interval for restart dump.
label writeInstance_
Current dump instance. If reaches writeInterval do a full write.
Detailed Description
This function object allows user-selected fields/registered objects to be written at a custom write interval. The interval is given in terms of number of overall dumps.
Example of function object specification:
partialWrite1
{
    type        partialWrite;
    functionObjectLibs ("libIOFunctionObjects.so");
    ...
    objectNames (p U T);
    writeInterval 100;
}
Function object usage
Property Description Required Default value
type type name: partialWrite yes
objectNames objects to write yes
writeInterval write interval yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
partialWrite.H
partialWrite.C
Definition at line 109 of file partialWrite.H.
Constructor & Destructor Documentation
partialWrite (const partialWrite &) protected
Disallow default bitwise copy construct.
partialWrite (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 47 of file partialWrite.C.
References Foam::read().
~partialWrite () virtual
Destructor.
Definition at line 63 of file partialWrite.C.
Member Function Documentation
void operator= (const partialWrite &) protected
Disallow default bitwise assignment.
void loadField (const word & fieldName, UPtrList< GeometricField< Type, fvPatchField, volMesh >> & vflds, UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> & sflds) const protected
Load objects in the objectNames.
Definition at line 35 of file partialWriteTemplates.C.
References partialWrite::changeWriteOptions(), Foam::endl(), and Foam::Info.
void changeWriteOptions (UPtrList< GeometricField< Type, fvPatchField, volMesh >> & vflds, UPtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> & sflds, const IOobject::writeOption wOption) const protected
Definition at line 87 of file partialWriteTemplates.C.
References forAll.
Referenced by partialWrite::loadField().
TypeName ("partialWrite")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the partialWrite.
Definition at line 200 of file partialWrite.H.
References partialWrite::end(), partialWrite::execute(), partialWrite::name_, partialWrite::read(), partialWrite::timeSet(), and partialWrite::write().
void read (const dictionary & dict) virtual
Read the partialWrite data.
Definition at line 69 of file partialWrite.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAllConstIter(), Foam::Info, dictionary::lookup(), Foam::name(), Foam::nl, and Foam::type().
Referenced by partialWrite::name().
void execute () virtual
Execute.
Definition at line 116 of file partialWrite.C.
Referenced by partialWrite::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 120 of file partialWrite.C.
Referenced by partialWrite::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 124 of file partialWrite.C.
References IOobject::AUTO_WRITE, and IOobject::NO_WRITE.
Referenced by partialWrite::name().
void write () virtual
Write the partialWrite.
Definition at line 174 of file partialWrite.C.
Referenced by partialWrite::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 221 of file partialWrite.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 225 of file partialWrite.H.
Member Data Documentation
word name_ protected
Name of this partialWrite functionObject.
Definition at line 116 of file partialWrite.H.
Referenced by partialWrite::name().
const objectRegistry& obr_ protected
Definition at line 118 of file partialWrite.H.
UPtrList<volScalarField> vsf_ protected
Loaded fields.
Definition at line 121 of file partialWrite.H.
UPtrList<volVectorField> vvf_ protected
Definition at line 122 of file partialWrite.H.
UPtrList<volSphericalTensorField> vSpheretf_ protected
Definition at line 123 of file partialWrite.H.
UPtrList<volSymmTensorField> vSymmtf_ protected
Definition at line 124 of file partialWrite.H.
UPtrList<volTensorField> vtf_ protected
Definition at line 125 of file partialWrite.H.
UPtrList<surfaceScalarField> ssf_ protected
Definition at line 127 of file partialWrite.H.
UPtrList<surfaceVectorField> svf_ protected
Definition at line 128 of file partialWrite.H.
UPtrList<surfaceSphericalTensorField> sSpheretf_ protected
Definition at line 129 of file partialWrite.H.
UPtrList<surfaceSymmTensorField> sSymmtf_ protected
Definition at line 130 of file partialWrite.H.
UPtrList<surfaceTensorField> stf_ protected
Definition at line 131 of file partialWrite.H.
HashSet<word> objectNames_ protected
Names of objects to dump always.
Definition at line 136 of file partialWrite.H.
label writeInterval_ protected
Write interval for restart dump.
Definition at line 139 of file partialWrite.H.
label writeInstance_ protected
Current dump instance. If reaches writeInterval do a full write.
Definition at line 144 of file partialWrite.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/partialWrite/partialWrite.H
src/postProcessing/functionObjects/utilities/partialWrite/partialWrite.C
src/postProcessing/functionObjects/utilities/partialWrite/partialWriteTemplates.C