OpenFOAM: pointFieldDecomposer::patchFieldDecomposer Class Reference
pointFieldDecomposer::patchFieldDecomposer Class Reference
Point patch field decomposer class.
Public Member Functions
patchFieldDecomposer (const pointPatch &completeMeshPatch, const pointPatch &procMeshPatch, const labelList &directAddr)
Construct given addressing.
label size () const
bool direct () const
bool hasUnmapped () const
Are there unmapped values? I.e. do all size() elements get.
const labelUList & directAddressing () const
Public Member Functions inherited from pointPatchFieldMapperPatchRef
pointPatchFieldMapperPatchRef (const pointPatch &source, const pointPatch &target)
Construct from components.
const pointPatch & sourcePatch () const
const pointPatch & targetPatch () const
Public Member Functions inherited from pointPatchFieldMapper
pointPatchFieldMapper ()
Null constructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
Point patch field decomposer class.
Definition at line 57 of file pointFieldDecomposer.H.
Constructor & Destructor Documentation
patchFieldDecomposer (const pointPatch & completeMeshPatch, const pointPatch & procMeshPatch, const labelList & directAddr)
Construct given addressing.
Member Function Documentation
label size () const inline virtual
Implements FieldMapper.
Definition at line 83 of file pointFieldDecomposer.H.
References List< T >::size().
bool direct () const inline virtual
Implements FieldMapper.
Definition at line 88 of file pointFieldDecomposer.H.
bool hasUnmapped () const inline virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implements FieldMapper.
Definition at line 93 of file pointFieldDecomposer.H.
const labelUList& directAddressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 98 of file pointFieldDecomposer.H.
References pointFieldDecomposer::decomposeField(), pointFieldDecomposer::decomposeFields(), fields, and pointFieldDecomposer::~pointFieldDecomposer().
The documentation for this class was generated from the following file:
applications/utilities/parallelProcessing/decomposePar/pointFieldDecomposer.H