OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointBoundaryMesh Class Reference
Foam::pointBoundaryMesh.
Public Member Functions
pointBoundaryMesh (const pointMesh &, const polyBoundaryMesh &)
Construct from polyBoundaryMesh.
const pointMesh & mesh () const
Return the mesh reference.
label findPatchID (const word &patchName) const
Find patch index given a name.
labelList findIndices (const keyType &, const bool useGroups) const
Find patch indices given a name.
void movePoints (const pointField &)
Correct polyBoundaryMesh after moving points.
void updateMesh ()
Correct polyBoundaryMesh after topology update.
Public Member Functions inherited from PtrList< T >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< T > &)
Copy constructor.
template<class CloneArg >
PtrList (const PtrList< T > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< T > > &)
Construct by transferring the parameter contents.
PtrList (PtrList< T > &, bool reUse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &)
Construct as copy of SLPtrList<T>
template<class INew >
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (T *)
Append an element at the end of the list.
void append (const autoPtr< T > &)
void append (const tmp< T > &)
void transfer (PtrList< T > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< T > set (const label, T *)
Set element. Return old element (can be NULL).
autoPtr< T > set (const label, const autoPtr< T > &)
autoPtr< T > set (const label, const tmp< T > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
PtrList< T > & operator= (const PtrList< T > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
Friends
class pointMesh
Declare friendship with pointMesh.
Additional Inherited Members
Public Types inherited from PtrList< T >
typedef T value_type
Type of values the PtrList contains.
typedef T & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant PtrList::value_type.
Protected Member Functions inherited from PtrList< T >
template<class INew >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Foam::pointBoundaryMesh.
Source files
pointBoundaryMesh.H
pointBoundaryMesh.C
Definition at line 52 of file pointBoundaryMesh.H.
Constructor & Destructor Documentation
pointBoundaryMesh (const pointMesh & m, const polyBoundaryMesh & basicBdry)
Construct from polyBoundaryMesh.
Definition at line 37 of file pointBoundaryMesh.C.
References forAll, and PtrList< T >::set().
Member Function Documentation
const pointMesh& mesh () const inline
Return the mesh reference.
Definition at line 93 of file pointBoundaryMesh.H.
Referenced by motionSmootherAlgo::curPoints(), and pointBoundaryMesh::findPatchID().
Foam::label findPatchID (const word & patchName) const
Find patch index given a name.
Definition at line 61 of file pointBoundaryMesh.C.
References pointBoundaryMesh::mesh().
Foam::labelList findIndices (const keyType & key, const bool useGroups) const
Find patch indices given a name.
Definition at line 68 of file pointBoundaryMesh.C.
References mesh.
void movePoints (const pointField & p)
Correct polyBoundaryMesh after moving points.
Definition at line 123 of file pointBoundaryMesh.C.
References UPstream::blocking, UPstream::defaultCommsType, PstreamBuffers::finishedSends(), forAll, polyMesh::globalData(), mesh, UPstream::nonBlocking, ProcessorTopology< Container, ProcPatch >::patchSchedule(), and UPstream::scheduled.
void updateMesh ()
Correct polyBoundaryMesh after topology update.
Definition at line 169 of file pointBoundaryMesh.C.
References UPstream::blocking, UPstream::defaultCommsType, PstreamBuffers::finishedSends(), forAll, polyMesh::globalData(), mesh, UPstream::nonBlocking, ProcessorTopology< Container, ProcPatch >::patchSchedule(), and UPstream::scheduled.
Friends And Related Function Documentation
friend class pointMesh friend
Declare friendship with pointMesh.
Definition at line 77 of file pointBoundaryMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointBoundaryMesh/pointBoundaryMesh.H
src/OpenFOAM/meshes/pointMesh/pointBoundaryMesh/pointBoundaryMesh.C