OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
primitiveMesh Class Reference abstract
Cell-face mesh analysis engine.
Public Member Functions
ClassName ("primitiveMesh")
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Construct from components.
virtual ~primitiveMesh ()
Destructor.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Reset this primitiveMesh given the primitive array sizes.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList &cells)
Reset this primitiveMesh given the primitive array sizes and cells.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, const Xfer< cellList > &cells)
Reset this primitiveMesh given the primitive array sizes and cells.
label nPoints () const
label nEdges () const
label nInternalFaces () const
label nFaces () const
label nCells () const
label nInternalPoints () const
Points not on boundary.
label nInternal0Edges () const
Internal edges (i.e. not on boundary face) using.
label nInternal1Edges () const
Internal edges using 0 or 1 boundary point.
label nInternalEdges () const
Internal edges using 0,1 or 2 boundary points.
virtual const pointField & points () const =0
Return mesh points.
virtual const faceList & faces () const =0
Return faces.
virtual const labelList & faceOwner () const =0
Face face-owner addresing.
virtual const labelList & faceNeighbour () const =0
Face face-neighbour addressing.
virtual const pointField & oldPoints () const =0
Return old points for mesh motion.
const cellShapeList & cellShapes () const
Return cell shapes.
const edgeList & edges () const
Return mesh edges. Uses calcEdges.
const labelListList & cellCells () const
const labelListList & edgeCells () const
const labelListList & pointCells () const
const cellList & cells () const
const labelListList & edgeFaces () const
const labelListList & pointFaces () const
const labelListList & cellEdges () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointPoints () const
const labelListList & cellPoints () const
const vectorField & cellCentres () const
const vectorField & faceCentres () const
const scalarField & cellVolumes () const
const vectorField & faceAreas () const
tmp< scalarField > movePoints (const pointField &p, const pointField &oldP)
Move points, returns volumes swept by faces in motion.
bool isInternalFace (const label faceIndex) const
Return true if given face label is internal to the mesh.
virtual bool checkUpperTriangular (const bool report=false, labelHashSet *setPtr=NULL) const
Check face ordering.
virtual bool checkCellsZipUp (const bool report=false, labelHashSet *setPtr=NULL) const
Check cell zip-up.
virtual bool checkFaceVertices (const bool report=false, labelHashSet *setPtr=NULL) const
Check uniqueness of face vertices.
virtual bool checkPoints (const bool report=false, labelHashSet *setPtr=NULL) const
Check for unused points.
virtual bool checkFaceFaces (const bool report=false, labelHashSet *setPtr=NULL) const
Check face-face connectivity.
virtual bool checkClosedBoundary (const bool report=false) const
Check boundary for closedness.
virtual bool checkClosedCells (const bool report=false, labelHashSet *setPtr=NULL, labelHashSet *highAspectSetPtr=NULL, const Vector< label > &solutionD=Vector< label >::one) const
Check cells for closedness.
virtual bool checkFaceAreas (const bool report=false, labelHashSet *setPtr=NULL) const
Check for negative face areas.
virtual bool checkCellVolumes (const bool report=false, labelHashSet *setPtr=NULL) const
Check for negative cell volumes.
virtual bool checkFaceOrthogonality (const bool report=false, labelHashSet *setPtr=NULL) const
Check for non-orthogonality.
virtual bool checkFacePyramids (const bool report=false, const scalar minPyrVol=-SMALL, labelHashSet *setPtr=NULL) const
Check face pyramid volume.
virtual bool checkFaceSkewness (const bool report=false, labelHashSet *setPtr=NULL) const
Check face skewness.
virtual bool checkFaceAngles (const bool report=false, const scalar maxSin=10, labelHashSet *setPtr=NULL) const
Check face angles.
virtual bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage: decompose face and check ratio between.
virtual bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet *setPtr=NULL) const
Check for point-point-nearness,.
virtual bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet *setPtr=NULL) const
Check edge length.
virtual bool checkConcaveCells (const bool report=false, labelHashSet *setPtr=NULL) const
Check for concave cells by the planes of faces.
virtual bool checkTopology (const bool report=false) const
Check mesh topology for correctness.
virtual bool checkGeometry (const bool report=false) const
Check mesh geometry (& implicitly topology) for correctness.
virtual bool checkMesh (const bool report=false) const
Check mesh for correctness. Returns false for no error.
bool pointInCellBB (const point &p, label celli, scalar inflationFraction=0) const
Return true if the point in the cell bounding box.
bool pointInCell (const point &p, label celli) const
Return true if the point is in the cell.
label findNearestCell (const point &location) const
Find the cell with the nearest cell centre to location.
label findCell (const point &location) const
Find cell enclosing this location (-1 if not in mesh)
void printAllocated () const
Print a list of all the currently allocated mesh data.
bool hasCellShapes () const
bool hasEdges () const
bool hasCellCells () const
bool hasEdgeCells () const
bool hasPointCells () const
bool hasCells () const
bool hasEdgeFaces () const
bool hasPointFaces () const
bool hasCellEdges () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointPoints () const
bool hasCellPoints () const
bool hasCellCentres () const
bool hasFaceCentres () const
bool hasCellVolumes () const
bool hasFaceAreas () const
const labelList & cellCells (const label cellI, DynamicList< label > &) const
cellCells using cells.
const labelList & cellCells (const label cellI) const
const labelList & cellPoints (const label cellI, DynamicList< label > &) const
cellPoints using cells
const labelList & cellPoints (const label cellI) const
const labelList & pointCells (const label pointI, DynamicList< label > &) const
pointCells using pointFaces
const labelList & pointCells (const label pointI) const
const labelList & pointPoints (const label pointI, DynamicList< label > &) const
pointPoints using edges, pointEdges
const labelList & pointPoints (const label pointI) const
const labelList & faceEdges (const label faceI, DynamicList< label > &) const
faceEdges using pointFaces, edges, pointEdges
const labelList & faceEdges (const label faceI) const
const labelList & edgeFaces (const label edgeI, DynamicList< label > &) const
edgeFaces using pointFaces, edges, pointEdges
const labelList & edgeFaces (const label edgeI) const
const labelList & edgeCells (const label edgeI, DynamicList< label > &) const
edgeCells using pointFaces, edges, pointEdges
const labelList & edgeCells (const label edgeI) const
const labelList & cellEdges (const label cellI, DynamicList< label > &) const
cellEdges using cells, pointFaces, edges, pointEdges
const labelList & cellEdges (const label cellI) const
void clearGeom ()
Clear geometry.
void clearAddressing ()
Clear topological data.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Static Public Member Functions
static void calcCells (cellList &, const labelUList &own, const labelUList &nei, const label nCells=-1)
Helper function to calculate cell-face addressing from.
static bool calcPointOrder (label &nInternalPoints, labelList &pointMap, const faceList &, const label nInternalFaces, const label nPoints)
Helper function to calculate point ordering. Returns true.
static scalar setClosedThreshold (const scalar)
Set the closedness ratio warning threshold.
static scalar setAspectThreshold (const scalar)
Set the aspect ratio warning threshold.
static scalar setNonOrthThreshold (const scalar)
Set the non-orthogonality warning threshold in degrees.
static scalar setSkewThreshold (const scalar)
Set the skewness warning threshold as percentage.
Static Public Attributes
static const unsigned cellsPerEdge_ = 4
Estimated number of cells per edge.
static const unsigned cellsPerPoint_ = 8
Estimated number of cells per point.
static const unsigned facesPerCell_ = 6
Estimated number of faces per cell.
static const unsigned facesPerEdge_ = 4
Estimated number of faces per edge.
static const unsigned facesPerPoint_ = 12
Estimated number of faces per point.
static const unsigned edgesPerCell_ = 12
Estimated number of edges per cell.
static const unsigned edgesPerFace_ = 4
Estimated number of edges per cell.
static const unsigned edgesPerPoint_ = 6
Estimated number of edges per point.
static const unsigned pointsPerCell_ = 8
Estimated number of points per cell.
static const unsigned pointsPerFace_ = 4
Estimated number of points per face.
Protected Member Functions
void calcFaceCentresAndAreas () const
Calculate face centres and areas.
void makeFaceCentresAndAreas (const pointField &p, vectorField &fCtrs, vectorField &fAreas) const
void calcCellCentresAndVols () const
Calculate cell centres and volumes.
void makeCellCentresAndVols (const vectorField &fCtrs, const vectorField &fAreas, vectorField &cellCtrs, scalarField &cellVols) const
void calcEdgeVectors () const
Calculate edge vectors.
bool checkDuplicateFaces (const label, const Map< label > &, label &nBaffleFaces, labelHashSet *) const
Check if all points on face are shared with another face.
bool checkCommonOrder (const label, const Map< label > &, labelHashSet *) const
Check that shared points are in consecutive order.
bool checkClosedBoundary (const vectorField &, const bool, const PackedBoolList &) const
Check boundary for closedness.
bool checkClosedCells (const vectorField &faceAreas, const scalarField &cellVolumes, const bool report, labelHashSet *setPtr, labelHashSet *aspectSetPtr, const Vector< label > &meshD) const
Check cells for closedness.
bool checkFaceAreas (const vectorField &faceAreas, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative face areas.
bool checkCellVolumes (const scalarField &vols, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative cell volumes.
bool checkFaceOrthogonality (const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check for non-orthogonality.
bool checkFacePyramids (const pointField &points, const vectorField &ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet *setPtr) const
Check face pyramid volume.
bool checkFaceSkewness (const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check face skewness.
bool checkFaceAngles (const pointField &points, const vectorField &faceAreas, const bool report, const scalar maxDeg, labelHashSet *setPtr) const
Check face angles.
bool checkFaceFlatness (const pointField &points, const vectorField &faceCentres, const vectorField &faceAreas, const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage.
bool checkConcaveCells (const vectorField &fAreas, const pointField &fCentres, const bool report, labelHashSet *setPtr) const
Check for concave cells by the planes of faces.
primitiveMesh ()
Construct null.
Static Protected Attributes
static scalar closedThreshold_ = 1.0e-6
Static data to control mesh checking.
static scalar aspectThreshold_ = 1000
Aspect ratio warning threshold.
static scalar nonOrthThreshold_ = 70
Non-orthogonality warning threshold in deg.
static scalar skewThreshold_ = 4
Skewness warning threshold.
static scalar planarCosAngle_ = 1.0e-6
Threshold where faces are considered coplanar.
Detailed Description
Cell-face mesh analysis engine.
Source files
primitiveMesh.H
primitiveMeshI.H
primitiveMesh.C
primitiveMeshClear.C
primitiveMeshCellCells.C
primitiveMeshEdgeCells.C
primitiveMeshPointCells.C
primitiveMeshCells.C
primitiveMeshEdgeFaces.C
primitiveMeshPointFaces.C
primitiveMeshCellEdges.C
primitiveMeshPointEdges.C
primitiveMeshPointPoints.C
primitiveMeshEdges.C
primitiveMeshCellCentresAndVols.C
primitiveMeshFaceCentresAndAreas.C
primitiveMeshFindCell.C
Definition at line 74 of file primitiveMesh.H.
Constructor & Destructor Documentation
primitiveMesh () protected
Construct null.
Definition at line 39 of file primitiveMesh.C.
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Construct from components.
Definition at line 79 of file primitiveMesh.C.
~primitiveMesh () virtual
Destructor.
Definition at line 120 of file primitiveMesh.C.
Member Function Documentation
void calcFaceCentresAndAreas () const protected
Calculate face centres and areas.
Definition at line 38 of file primitiveMeshFaceCentresAndAreas.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::makeFaceCentresAndAreas(), primitiveMesh::nFaces(), primitiveMesh::points(), and Foam::Pout.
void makeFaceCentresAndAreas (const pointField & p, vectorField & fCtrs, vectorField & fAreas) const protected
Definition at line 74 of file primitiveMeshFaceCentresAndAreas.C.
References Foam::constant::universal::c, f(), forAll, Foam::mag(), n, nPoints, Foam::constant::mathematical::pi(), List< T >::size(), and Vector< scalar >::zero.
Referenced by primitiveMesh::calcFaceCentresAndAreas().
void calcCellCentresAndVols () const protected
Calculate cell centres and volumes.
Definition at line 34 of file primitiveMeshCellCentresAndVols.C.
References Foam::abort(), cellVols, Foam::endl(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::makeCellCentresAndVols(), primitiveMesh::nCells(), and Foam::Pout.
void makeCellCentresAndVols (const vectorField & fCtrs, const vectorField & fAreas, vectorField & cellCtrs, scalarField & cellVols) const protected
Definition at line 73 of file primitiveMeshCellCentresAndVols.C.
References forAll, Foam::mag(), and Vector< scalar >::zero.
Referenced by primitiveMesh::calcCellCentresAndVols().
void calcEdgeVectors () const protected
Calculate edge vectors.
bool checkDuplicateFaces (const label faceI, const Map< label > & nCommonPoints, label & nBaffleFaces, labelHashSet * setPtr) const protected
Check if all points on face are shared with another face.
Definition at line 1407 of file primitiveMeshCheck.C.
References forAllConstIter, HashSet< Key, Hash >::insert(), and List< T >::size().
bool checkCommonOrder (const label faceI, const Map< label > & nCommonPoints, labelHashSet * setPtr) const protected
Check that shared points are in consecutive order.
Definition at line 1449 of file primitiveMeshCheck.C.
References UList< T >::fcIndex(), Foam::findIndex(), forAll, forAllConstIter, HashSet< Key, Hash >::insert(), Foam::labelMax, UList< T >::rcIndex(), and List< T >::size().
bool checkClosedBoundary (const vectorField & areas, const bool report, const PackedBoolList & internalOrCoupledFaces) const protected
Check boundary for closedness.
Definition at line 46 of file primitiveMeshCheck.C.
References Foam::cmptMag(), Foam::cmptMax(), Foam::endl(), Foam::Info, Foam::mag(), Foam::reduce(), List< T >::size(), and PackedList< nBits >::size().
Referenced by primitiveMesh::checkClosedBoundary().
bool checkClosedCells (const vectorField & faceAreas, const scalarField & cellVolumes, const bool report, labelHashSet * setPtr, labelHashSet * aspectSetPtr, const Vector< label > & meshD) const protected
Check cells for closedness.
Definition at line 104 of file primitiveMeshCheck.C.
References Foam::constant::universal::c, cells, Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::max(), Foam::min(), Foam::nl, and Foam::reduce().
bool checkFaceAreas (const vectorField & faceAreas, const bool report, const bool detailedReport, labelHashSet * setPtr) const protected
Check for negative face areas.
Definition at line 238 of file primitiveMeshCheck.C.
References Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::max(), Foam::min(), Foam::Pout, and Foam::reduce().
bool checkCellVolumes (const scalarField & vols, const bool report, const bool detailedReport, labelHashSet * setPtr) const protected
Check for negative cell volumes.
Definition at line 318 of file primitiveMeshCheck.C.
References Foam::endl(), forAll, Foam::gSum(), Foam::Info, HashSet< Key, Hash >::insert(), Foam::max(), Foam::min(), Foam::Pout, and Foam::reduce().
bool checkFaceOrthogonality (const vectorField & fAreas, const vectorField & cellCtrs, const bool report, labelHashSet * setPtr) const protected
Check for non-orthogonality.
Definition at line 390 of file primitiveMeshCheck.C.
References Foam::acos(), Foam::cos(), Foam::degToRad(), Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::min(), Foam::radToDeg(), Foam::reduce(), List< T >::size(), and Foam::sum().
bool checkFacePyramids (const pointField & points, const vectorField & ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet * setPtr) const protected
Check face pyramid volume.
Definition at line 502 of file primitiveMeshCheck.C.
References cells, Foam::endl(), f(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::nl, Foam::Pout, and Foam::reduce().
bool checkFaceSkewness (const pointField & points, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs, const bool report, labelHashSet * setPtr) const protected
Check face skewness.
Definition at line 606 of file primitiveMeshCheck.C.
References Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::max(), and Foam::reduce().
bool checkFaceAngles (const pointField & points, const vectorField & faceAreas, const bool report, const scalar maxDeg, labelHashSet * setPtr) const protected
Check face angles.
Definition at line 685 of file primitiveMeshCheck.C.
References Foam::asin(), Foam::degToRad(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::max(), Foam::min(), Foam::radToDeg(), Foam::reduce(), and Foam::sin().
bool checkFaceFlatness (const pointField & points, const vectorField & faceCentres, const vectorField & faceAreas, const bool report, const scalar warnFlatness, labelHashSet * setPtr) const protected
Check face warpage.
Definition at line 767 of file primitiveMeshCheck.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::min(), and Foam::reduce().
bool checkConcaveCells (const vectorField & fAreas, const pointField & fCentres, const bool report, labelHashSet * setPtr) const protected
Check for concave cells by the planes of faces.
Definition at line 874 of file primitiveMeshCheck.C.
References Foam::constant::universal::c, cells, Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::max(), and Foam::reduce().
ClassName ("primitiveMesh")
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Reset this primitiveMesh given the primitive array sizes.
Definition at line 208 of file primitiveMesh.C.
References Foam::endl(), nPoints, and Foam::Pout.
Referenced by LiftForce< CloudType >::cacheFields(), and streamLine::read().
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList & cells)
Reset this primitiveMesh given the primitive array sizes and cells.
Definition at line 264 of file primitiveMesh.C.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, const Xfer< cellList > & cells)
Reset this primitiveMesh given the primitive array sizes and cells.
Definition at line 285 of file primitiveMesh.C.
label nPoints () const inline
Definition at line 41 of file primitiveMeshI.H.
Referenced by polyMeshAdder::add(), polyTopoChange::addMesh(), motionSmootherAlgo::avg(), polyTopoChange::changeMesh(), pointZone::checkParallelSync(), componentDisplacementMotionSolver::componentDisplacementMotionSolver(), displacementInterpolationMotionSolver::curPoints(), displacementMotionSolver::displacementMotionSolver(), fvMeshDistribute::distribute(), autoSnapDriver::doSnap(), edgeVertex::edgeToEVert(), polyMeshFilter::filterEdges(), edgeVertex::getEdge(), surfaceSets::getHangingCells(), syncTools::getMasterPoints(), hexRef8::hexRef8(), edgeVertex::isEdge(), localPointRegion::localPointRegion(), polyTopoChange::makeMesh(), pointSet::maxSize(), pointZoneSet::maxSize(), meshTriangulation::meshTriangulation(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), vtkMesh::nFieldPoints(), sampledSurface::pointAverage(), primitiveMesh::pointFaces(), pointSet::pointSet(), pointZoneSet::pointZoneSet(), polyMesh::polyMesh(), fvMeshDistribute::printMeshInfo(), processorMeshes::reconstructPoints(), decompositionMethod::setConstraints(), pointMesh::size(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), sixDoFRigidBodyMotionSolver::solve(), pointSet::sync(), syncTools::syncPointList(), meshRefinement::testSyncPointList(), and edgeVertex::vertToEVert().
label nEdges () const inline
Definition at line 71 of file primitiveMeshI.H.
References primitiveMesh::edges(), and List< T >::size().
Referenced by primitiveMesh::edgeCells(), primitiveMesh::edgeFaces(), edgeVertex::edgeToEVert(), directionInfo::edgeToFaceIndex(), syncTools::getMasterEdges(), addPatchCellLayer::globalEdgeFaces(), edgeVertex::isEdge(), primitiveMesh::nInternal0Edges(), primitiveMesh::nInternal1Edges(), primitiveMesh::nInternalEdges(), and syncTools::syncEdgeList().
label nInternalFaces () const inline
Definition at line 82 of file primitiveMeshI.H.
Referenced by autoLayerDriver::addLayers(), polyTopoChange::addMesh(), decompositionMethod::calcCellCells(), polyDualMesh::calcFeatures(), CentredFitSnGradData< Polynomial >::calcFit(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkDefinition(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), decompositionMethod::decompose(), fvMeshDistribute::distribute(), dynamicRefineFvMesh::dynamicRefineFvMesh(), faceCoupleInfo::faceCoupleInfo(), primitiveMeshTools::faceOrthogonality(), polyMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTools::faceWeights(), localPointRegion::findDuplicateFacePairs(), localPointRegion::findDuplicateFaces(), polyMeshTetDecomposition::findFaceBasePts(), volPointInterpolation::flatBoundaryField(), boundaryMesh::getNearest(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), fvMeshSubset::interpolate(), primitiveMesh::isInternalFace(), MeshedSurface< Face >::MeshedSurface(), Cloud< ParticleType >::move(), boundaryMesh::patchify(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), boundaryMesh::read(), SloanRenumber::renumber(), mappedPatchBase::sampleSize(), surfaceMesh::size(), fvSurfaceMapper::size(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), syncTools::swapFaceList(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncFacePositions(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), cellToCellStencil::validBoundaryFaces(), cellToFaceStencil::validBoundaryFaces(), polyMeshTools::volRatio(), extendedUpwindCellToFaceStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), polyBoundaryMesh::whichPatch(), and regionSizeDistribution::write().
label nFaces () const inline
Definition at line 88 of file primitiveMeshI.H.
Referenced by polyMeshAdder::add(), autoLayerDriver::addLayers(), fvMeshTools::addPatch(), meshRefinement::addPatch(), decompositionMethod::calcCellCells(), primitiveMesh::calcFaceCentresAndAreas(), polyDualMesh::calcFeatures(), CentredFitSnGradData< Polynomial >::calcFit(), polyTopoChange::changeMesh(), edgeCollapser::checkBadFaces(), meshRefinement::checkCoupledFaceZones(), polyMeshGeometry::checkFaceDotProduct(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), motionSmootherAlgo::checkMesh(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), structuredDecomp::decompose(), decompositionMethod::decompose(), fvMeshDistribute::distribute(), autoLayerDriver::doLayers(), autoSnapDriver::doSnap(), dynamicRefineFvMesh::dynamicRefineFvMesh(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), faceMapper::faceMapper(), polyMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), faceSet::faceSet(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTools::faceWeights(), faceZoneSet::faceZoneSet(), localPointRegion::findDuplicateFacePairs(), polyMeshTetDecomposition::findFaceBasePts(), volPointInterpolation::flatBoundaryField(), fvFieldReconstructor::fvFieldReconstructor(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), boundaryMesh::getNearest(), Foam::MULES::limit(), Foam::MULES::limitCorr(), polyTopoChange::makeMesh(), mappedPatchFieldBase< Type >::mappedField(), faceSet::maxSize(), faceZoneSet::maxSize(), autoLayerDriver::mergePatchFacesUndo(), MeshedSurface< Face >::MeshedSurface(), boundaryMesh::patchify(), autoSnapDriver::preSmoothPatch(), fvMeshDistribute::printMeshInfo(), boundaryMesh::read(), wallBoundedStreamLine::read(), SloanRenumber::renumber(), structuredRenumber::renumber(), autoSnapDriver::repatchToSurface(), mappedPatchBase::sampleSize(), autoSnapDriver::scaleMesh(), decompositionMethod::setConstraints(), Foam::fvc::smooth(), Foam::fvc::spread(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), syncTools::swapFaceList(), Foam::fvc::sweep(), faceSet::sync(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncFacePositions(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), polyMeshTools::volRatio(), polyBoundaryMesh::whichPatch(), and regionSizeDistribution::write().
label nCells () const inline
Definition at line 94 of file primitiveMeshI.H.
Referenced by polyMeshAdder::add(), autoLayerDriver::addLayers(), polyTopoChange::addMesh(), nearWallFields::calcAddressing(), primitiveMesh::calcCellCentresAndVols(), curvatureSeparation::calcCosAngle(), primitiveMeshTools::cellClosedness(), cellCuts::cellCuts(), primitiveMeshTools::cellDeterminant(), cellMapper::cellMapper(), primitiveMesh::cellPoints(), cellSet::cellSet(), cellZoneSet::cellZoneSet(), polyTopoChange::changeMesh(), drippingInjection::correct(), structuredDecomp::decompose(), decompositionMethod::decompose(), fvMeshDistribute::distribute(), refinementHistory::distribute(), autoLayerDriver::doLayers(), autoRefineDriver::doRefine(), dynamicRefineFvMesh::dynamicRefineFvMesh(), refinementParameters::findCells(), fvFieldReconstructor::fvFieldReconstructor(), get_edge_list(), get_geom_list(), get_num_edges_list(), get_number_of_vertices(), get_vertex_list(), surfaceSets::getHangingCells(), hexRef8::hexRef8(), Kmesh::Kmesh(), polyTopoChange::makeMesh(), mappedPatchFieldBase< Type >::mappedField(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), meshToMeshMethod::maskCells(), cellSet::maxSize(), cellZoneSet::maxSize(), momentOfInertia::meshInertia(), cellTable::operator=(), sampledSurface::pointAverage(), polyMesh::polyMesh(), fvMeshDistribute::printMeshInfo(), ensightParts::recalculate(), zoltanRenumber::renumber(), CuthillMcKeeRenumber::renumber(), SloanRenumber::renumber(), structuredRenumber::renumber(), springRenumber::renumber(), renumberMethod::renumber(), volMesh::size(), Foam::fvc::smooth(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), Foam::fvc::spread(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), Foam::fvc::sweep(), regionSizeDistribution::write(), and meshToMeshMethod::writeConnectivity().
label nInternalPoints () const inline
Points not on boundary.
Definition at line 35 of file primitiveMeshI.H.
label nInternal0Edges () const inline
Internal edges (i.e. not on boundary face) using.
no boundary point
Definition at line 47 of file primitiveMeshI.H.
References primitiveMesh::nEdges().
label nInternal1Edges () const inline
Internal edges using 0 or 1 boundary point.
Definition at line 55 of file primitiveMeshI.H.
References primitiveMesh::nEdges().
label nInternalEdges () const inline
Internal edges using 0,1 or 2 boundary points.
Definition at line 63 of file primitiveMeshI.H.
References primitiveMesh::nEdges().
virtual const pointField& points () const pure virtual
Return mesh points.
Implemented in polyMesh.
Referenced by primitiveMesh::calcFaceCentresAndAreas(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), edgeVertex::coord(), localPointRegion::findDuplicateFaces(), boundaryMesh::getNearest(), Foam::meshTools::normEdgeVec(), treeDataFace::findNearestOp::operator()(), treeDataFace::findIntersectOp::operator()(), cuttingPlane::reCut(), and pointSet::writeDebug().
virtual const faceList& faces () const pure virtual
Return faces.
Implemented in polyMesh.
Referenced by primitiveMeshTools::boundaryFaceSkewness(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), primitiveMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFaceTwist(), directionInfo::edgeToFaceIndex(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), primitiveMeshTools::facePyramidVolume(), primitiveMeshTools::faceSkewness(), localPointRegion::findDuplicateFaces(), surfaceSets::getHangingCells(), boundaryMesh::getNearest(), Foam::interpolatePointToCell(), prismMatcher::isA(), pyrMatcher::isA(), tetMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), hexMatcher::isA(), degenerateMatcher::match(), prismMatcher::matches(), tetMatcher::matches(), pyrMatcher::matches(), wedgeMatcher::matches(), tetWedgeMatcher::matches(), hexMatcher::matches(), treeDataFace::findNearestOp::operator()(), treeDataFace::findIntersectOp::operator()(), and primitiveMesh::pointFaces().
virtual const labelList& faceOwner () const pure virtual
Face face-owner addresing.
Implemented in polyMesh.
Referenced by tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), primitiveMeshTools::cellClosedness(), primitiveMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFaceSkewness(), primitiveMeshGeometry::checkFaceWeights(), Foam::meshTools::faceOnCell(), primitiveMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), primitiveMeshTools::faceSkewness(), Foam::meshTools::getSharedFace(), prismMatcher::isA(), tetMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), hexMatcher::isA(), pyrMatcher::isA(), degenerateMatcher::match(), tetWedgeMatcher::matches(), pyrMatcher::matches(), tetMatcher::matches(), wedgeMatcher::matches(), hexMatcher::matches(), prismMatcher::matches(), Foam::meshTools::otherCell(), and primitiveMesh::pointInCell().
virtual const labelList& faceNeighbour () const pure virtual
Face face-neighbour addressing.
Implemented in polyMesh.
Referenced by primitiveMeshTools::cellClosedness(), primitiveMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFaceSkewness(), primitiveMeshGeometry::checkFaceWeights(), Foam::meshTools::faceOnCell(), primitiveMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), primitiveMeshTools::faceSkewness(), Foam::meshTools::getSharedFace(), and Foam::meshTools::otherCell().
virtual const pointField& oldPoints () const pure virtual
Return old points for mesh motion.
Implemented in polyMesh.
const Foam::cellShapeList & cellShapes () const
Return cell shapes.
Definition at line 337 of file primitiveMesh.C.
const Foam::edgeList & edges () const
Return mesh edges. Uses calcEdges.
Definition at line 496 of file primitiveMeshEdges.C.
Referenced by autoLayerDriver::addLayers(), motionSmootherAlgo::avg(), polyDualMesh::calcFeatures(), addPatchCellLayer::calcSidePatch(), edgeVertex::coord(), geomCellLooper::cut(), topoCellLooper::cut(), Foam::meshTools::edgeToCutDir(), directionInfo::edgeToFaceIndex(), Foam::meshTools::findEdge(), Foam::meshTools::getEdgeFaces(), Foam::meshTools::getParallelEdges(), addPatchCellLayer::globalEdgeFaces(), primitiveMesh::nEdges(), Foam::meshTools::normEdgeVec(), Foam::meshTools::otherEdge(), boundaryMesh::setFeatureEdges(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), directionInfo::updateCell(), pointEdgePoint::updateEdge(), externalPointEdgePoint::updateEdge(), and Foam::meshTools::walkFace().
void calcCells (cellList & cellFaceAddr, const labelUList & own, const labelUList & nei, const label nCells = -1) static
Helper function to calculate cell-face addressing from.
face-cell addressing. If nCells is not provided it will scan for the maximum.
Definition at line 31 of file primitiveMeshCells.C.
References forAll, Foam::max(), List< T >::setSize(), and List< T >::size().
bool calcPointOrder (label & nInternalPoints, labelList & pointMap, const faceList & faces, const label nInternalFaces, const label nPoints) static
Helper function to calculate point ordering. Returns true.
if points already ordered, false and fills pointMap (old to new). Map splits points into those not used by any boundary face and those that are.
Definition at line 129 of file primitiveMesh.C.
References f(), forAll, List< T >::setSize(), and List< T >::size().
const Foam::labelListList & cellCells () const
Definition at line 100 of file primitiveMeshCellCells.C.
Referenced by meshToMeshMethod::appendNbrCells().
const Foam::labelListList & edgeCells () const
Definition at line 32 of file primitiveMeshEdgeCells.C.
References Foam::abort(), primitiveMesh::cellEdges(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nEdges(), and Foam::Pout.
Referenced by Foam::meshTools::edgeOnCell().
const Foam::labelListList & pointCells () const
Definition at line 108 of file primitiveMeshPointCells.C.
Referenced by primitiveMesh::cellPoints(), cellDistFuncs::correctBoundaryPointCells(), dynamicRefineFvMesh::dynamicRefineFvMesh(), and sampledSurface::pointAverage().
const Foam::cellList & cells () const
Definition at line 136 of file primitiveMeshCells.C.
Referenced by pointMVCWeight::calcWeights(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), primitiveMeshTools::cellDeterminant(), polyMeshTetDecomposition::cellTetIndices(), layerAdditionRemoval::changeTopology(), primitiveMeshGeometry::checkCellDeterminant(), polyMeshGeometry::checkCellDeterminant(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFacePyramids(), inversePointDistanceDiffusivity::correct(), outletStabilised< Type >::correction(), geomCellLooper::cut(), topoCellLooper::cut(), dynamicRefineFvMesh::dynamicRefineFvMesh(), probes::findElements(), sampledSet::findNearFace(), polyMeshTetDecomposition::findTet(), get_edge_list(), get_num_edges_list(), surfaceSets::getHangingCells(), Foam::meshTools::getSharedFace(), Foam::interpolatePointToCell(), tetMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), hexMatcher::isA(), prismMatcher::isA(), pyrMatcher::isA(), meshToMeshMethod::maskCells(), degenerateMatcher::match(), tetMatcher::matches(), hexMatcher::matches(), wedgeMatcher::matches(), pyrMatcher::matches(), tetWedgeMatcher::matches(), prismMatcher::matches(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), tetIndices::oldTet(), treeDataCell::findIntersectOp::operator()(), primitiveMesh::pointInCell(), Foam::polyMeshZipUpCells(), wallBoundedStreamLine::read(), patchInjectionBase::setPositionAndCell(), meshCutter::setRefinement(), fvMatrix< Type >::setValuesFromList(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), outletStabilised< Type >::weights(), and meshToMeshMethod::writeConnectivity().
const Foam::labelListList & edgeFaces () const
Definition at line 31 of file primitiveMeshEdgeFaces.C.
References Foam::abort(), Foam::endl(), primitiveMesh::faceEdges(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nEdges(), and Foam::Pout.
Referenced by addPatchCellLayer::calcSidePatch(), Foam::meshTools::getEdgeFaces(), boundaryMesh::setFeatureEdges(), meshCutAndRemove::setRefinement(), and meshCutter::setRefinement().
const Foam::labelListList & pointFaces () const
Definition at line 32 of file primitiveMeshPointFaces.C.
References Foam::endl(), primitiveMesh::faces(), Foam::invertManyToMany(), primitiveMesh::nPoints(), and Foam::Pout.
Referenced by decompositionMethod::decompose(), Foam::polyMeshZipUpCells(), decompositionMethod::setConstraints(), and perfectInterface::setRefinement().
const Foam::labelListList & cellEdges () const
Definition at line 118 of file primitiveMeshCellEdges.C.
Referenced by polyDualMesh::calcFeatures(), geomCellLooper::cut(), Foam::meshTools::cutDirToEdge(), and primitiveMesh::edgeCells().
const Foam::labelListList & faceEdges () const
Definition at line 519 of file primitiveMeshEdges.C.
References Foam::endl(), UList< T >::fcIndex(), forAll, Foam::Pout, List< T >::setSize(), and List< T >::size().
Referenced by primitiveMesh::edgeFaces(), Foam::meshTools::edgeOnFace(), Foam::meshTools::getSharedEdge(), directionInfo::updateCell(), and Foam::meshTools::walkFace().
const Foam::labelListList & pointEdges () const
Definition at line 507 of file primitiveMeshEdges.C.
Referenced by autoLayerDriver::addLayers(), addPatchCellLayer::calcSidePatch(), Foam::meshTools::findEdge(), and addPatchCellLayer::globalEdgeFaces().
const Foam::labelListList & pointPoints () const
Definition at line 91 of file primitiveMeshPointPoints.C.
const Foam::labelListList & cellPoints () const
Definition at line 31 of file primitiveMeshCellPoints.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nCells(), primitiveMesh::pointCells(), and Foam::Pout.
Referenced by tetOverlapVolume::overlappingCells(), pointMVCWeight::pointMVCWeight(), and meshCutAndRemove::setRefinement().
const Foam::vectorField & cellCentres () const
Definition at line 160 of file primitiveMeshCellCentresAndVols.C.
Referenced by polyTopoChange::addMesh(), autoSnapDriver::avgCellCentres(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), polyMeshTetDecomposition::checkFaceTets(), motionSmootherAlgo::checkMesh(), cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), structuredDecomp::decompose(), decompositionMethod::decompose(), mappedPatchBase::facePoint(), polyMeshTetDecomposition::findBasePoint(), probes::findElements(), polyMeshTetDecomposition::findFaceBasePts(), mapNearestMethod::findNearestCell(), mappedPatchBase::findSamples(), polyMeshTetDecomposition::findSharedBasePoint(), get_geom_list(), treeDataCell::findNearestOp::operator()(), InflationInjection< CloudType >::parcelsToInject(), sampledSet::pushIn(), structuredRenumber::renumber(), patchInjectionBase::setPositionAndCell(), tetIndices::tet(), sweepData::updateCell(), wallPoint::updateCell(), refinementDistanceData::updateCell(), cylindrical::updateCells(), reactingOneDim::updateQr(), meshToMeshMethod::writeConnectivity(), and cellSet::writeDebug().
const Foam::vectorField & faceCentres () const
Definition at line 140 of file primitiveMeshFaceCentresAndAreas.C.
Referenced by primitiveMesh::calcCellCentresAndVols(), sampledSet::calcSign(), polyMeshTetDecomposition::checkFaceTets(), motionSmootherAlgo::checkMesh(), decompositionMethod::decompose(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), mappedPatchBase::facePoint(), patchProbes::findElements(), probes::findElements(), FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs(), mappedPatchBase::findSamples(), boundaryMesh::getNearest(), meshTriangulation::meshTriangulation(), treeDataFace::findIntersectOp::operator()(), primitiveMesh::pointInCell(), fvMeshDistribute::printCoupleInfo(), sampledSet::pushIn(), autoSnapDriver::repatchToSurface(), Foam::fvc::sweep(), triSurfaceTools::triangulateFaceCentre(), wallPointYPlus::updateFace(), wallPointData< Type >::updateFace(), sweepData::updateFace(), wallPoint::updateFace(), refinementDistanceData::updateFace(), and faceSet::writeDebug().
const Foam::scalarField & cellVolumes () const
Definition at line 171 of file primitiveMeshCellCentresAndVols.C.
Referenced by polyTopoChange::changeMesh(), layerAdditionRemoval::changeTopology(), motionSmootherAlgo::checkMesh(), cellPointWeight::findTetrahedron(), polyTopoChange::makeMesh(), and fvMesh::V().
const Foam::vectorField & faceAreas () const
Definition at line 151 of file primitiveMeshFaceCentresAndAreas.C.
Referenced by primitiveMesh::calcCellCentresAndVols(), sampledSet::calcSign(), layerAdditionRemoval::changeTopology(), edgeCollapser::checkBadFaces(), primitiveMesh::checkClosedBoundary(), motionSmootherAlgo::checkMesh(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs(), cellPointWeight::findTriangle(), boundaryMesh::getNearest(), and primitiveMesh::pointInCell().
Foam::tmp< Foam::scalarField > movePoints (const pointField & p, const pointField & oldP)
Move points, returns volumes swept by faces in motion.
Definition at line 306 of file primitiveMesh.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, forAll, nPoints, and List< T >::size().
Referenced by polyMesh::movePoints().
bool isInternalFace (const label faceIndex) const inline
Return true if given face label is internal to the mesh.
Definition at line 100 of file primitiveMeshI.H.
References primitiveMesh::nInternalFaces().
Referenced by polyMeshGeometry::affectedCells(), addPatchCellLayer::calcSidePatch(), primitiveMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), primitiveMeshGeometry::checkFaceWeights(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), outletStabilised< Type >::correction(), decompositionMethod::decompose(), Foam::meshTools::faceOnCell(), primitiveMeshTools::facePyramidVolume(), get_edge_list(), get_num_edges_list(), Foam::meshTools::getSharedFace(), meshTriangulation::meshTriangulation(), Foam::meshTools::otherCell(), perfectInterface::setRefinement(), fvMatrix< Type >::setValuesFromList(), and outletStabilised< Type >::weights().
bool checkUpperTriangular (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check face ordering.
Definition at line 991 of file primitiveMeshCheck.C.
References Foam::constant::universal::c, cells, Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::labelMax, Foam::reduce(), and List< T >::size().
bool checkCellsZipUp (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check cell zip-up.
Definition at line 1156 of file primitiveMeshCheck.C.
References Foam::constant::universal::c, cells, Foam::endl(), f(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::reduce(), and List< T >::size().
bool checkFaceVertices (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check uniqueness of face vertices.
Definition at line 1257 of file primitiveMeshCheck.C.
References Foam::endl(), f(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::max(), Foam::min(), nPoints, Foam::reduce(), and List< T >::size().
bool checkPoints (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check for unused points.
Definition at line 1332 of file primitiveMeshCheck.C.
References UList< T >::empty(), Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), and Foam::reduce().
bool checkFaceFaces (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check face-face connectivity.
Definition at line 1612 of file primitiveMeshCheck.C.
References HashTable< T, Key, Hash >::clear(), HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, Foam::Info, HashTable< T, Key, Hash >::insert(), and Foam::reduce().
bool checkClosedBoundary (const bool report = false) const virtual
Check boundary for closedness.
Definition at line 1724 of file primitiveMeshCheck.C.
References primitiveMesh::checkClosedBoundary(), and primitiveMesh::faceAreas().
bool checkClosedCells (const bool report = false, labelHashSet * setPtr = NULL, labelHashSet * highAspectSetPtr = NULL, const Vector< label > & solutionD = Vector<label>::one) const virtual
Check cells for closedness.
Definition at line 1731 of file primitiveMeshCheck.C.
bool checkFaceAreas (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check for negative face areas.
Definition at line 1751 of file primitiveMeshCheck.C.
bool checkCellVolumes (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check for negative cell volumes.
Definition at line 1767 of file primitiveMeshCheck.C.
bool checkFaceOrthogonality (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check for non-orthogonality.
Reimplemented in polyMesh.
Definition at line 1783 of file primitiveMeshCheck.C.
bool checkFacePyramids (const bool report = false, const scalar minPyrVol = -SMALL, labelHashSet * setPtr = NULL) const virtual
Check face pyramid volume.
Definition at line 1799 of file primitiveMeshCheck.C.
References points.
bool checkFaceSkewness (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check face skewness.
Reimplemented in polyMesh.
Definition at line 1818 of file primitiveMeshCheck.C.
References points.
bool checkFaceAngles (const bool report = false, const scalar maxSin = 10, labelHashSet * setPtr = NULL) const virtual
Check face angles.
Definition at line 1836 of file primitiveMeshCheck.C.
References points.
bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet * setPtr) const virtual
Check face warpage: decompose face and check ratio between.
magnitude of sum of triangle areas and sum of magnitude of triangle areas.
Definition at line 1854 of file primitiveMeshCheck.C.
References points.
bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet * setPtr = NULL) const virtual
Check for point-point-nearness,.
e.g. colocated points which may be part of baffles.
Definition at line 32 of file primitiveMeshCheckPointNearness.C.
References Foam::endl(), SortableList< T >::indices(), Foam::Info, HashSet< Key, Hash >::insert(), Foam::magSqr(), points, Foam::reduce(), List< T >::size(), and Foam::sqrt().
bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet * setPtr = NULL) const virtual
Check edge length.
Definition at line 31 of file primitiveMeshCheckEdgeLength.C.
References Foam::endl(), f(), UList< T >::fcIndex(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::magSqr(), Foam::max(), Foam::min(), nPoints, points, Foam::reduce(), HashTable< T, Key, Hash >::size(), Foam::sqr(), Foam::sqrt(), and HashTable< T, Key, Hash >::transfer().
bool checkConcaveCells (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check for concave cells by the planes of faces.
Definition at line 1873 of file primitiveMeshCheck.C.
bool checkTopology (const bool report = false) const virtual
Check mesh topology for correctness.
Returns false for no error.
Definition at line 1888 of file primitiveMeshCheck.C.
References Foam::endl(), and Foam::Info.
bool checkGeometry (const bool report = false) const virtual
Check mesh geometry (& implicitly topology) for correctness.
Returns false for no error.
Definition at line 1920 of file primitiveMeshCheck.C.
References Foam::endl(), and Foam::Info.
bool checkMesh (const bool report = false) const virtual
Check mesh for correctness. Returns false for no error.
Definition at line 1953 of file primitiveMeshCheck.C.
References Foam::checkGeometry(), Foam::checkTopology(), Foam::endl(), and Foam::Info.
Referenced by attachPolyTopoChanger::attach().
Foam::scalar setClosedThreshold (const scalar val) static
Set the closedness ratio warning threshold.
Definition at line 1985 of file primitiveMeshCheck.C.
Foam::scalar setAspectThreshold (const scalar val) static
Set the aspect ratio warning threshold.
Definition at line 1994 of file primitiveMeshCheck.C.
Foam::scalar setNonOrthThreshold (const scalar val) static
Set the non-orthogonality warning threshold in degrees.
Definition at line 2003 of file primitiveMeshCheck.C.
Foam::scalar setSkewThreshold (const scalar val) static
Set the skewness warning threshold as percentage.
of the face area vector
Definition at line 2012 of file primitiveMeshCheck.C.
bool pointInCellBB (const point & p, label celli, scalar inflationFraction = 0) const
Return true if the point in the cell bounding box.
The bounding box may be isotropically inflated by the fraction inflationFraction
Definition at line 33 of file primitiveMeshFindCell.C.
References cells, boundBox::contains(), Foam::mag(), Vector< Cmpt >::max, points, and boundBox::span().
bool pointInCell (const point & p, label celli) const
Return true if the point is in the cell.
Definition at line 59 of file primitiveMeshFindCell.C.
References primitiveMesh::cells(), f(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), primitiveMesh::faceOwner(), and forAll.
Referenced by polyMesh::pointInCell().
Foam::label findNearestCell (const point & location) const
Find the cell with the nearest cell centre to location.
Definition at line 86 of file primitiveMeshFindCell.C.
References Foam::magSqr(), and List< T >::size().
Foam::label findCell (const point & location) const
Find cell enclosing this location (-1 if not in mesh)
Definition at line 108 of file primitiveMeshFindCell.C.
References n.
void printAllocated () const
Print a list of all the currently allocated mesh data.
Definition at line 31 of file primitiveMeshClear.C.
References Foam::endl(), and Foam::Pout.
bool hasCellShapes () const inline
Definition at line 106 of file primitiveMeshI.H.
bool hasEdges () const inline
Definition at line 112 of file primitiveMeshI.H.
bool hasCellCells () const inline
Definition at line 118 of file primitiveMeshI.H.
bool hasEdgeCells () const inline
Definition at line 124 of file primitiveMeshI.H.
bool hasPointCells () const inline
Definition at line 130 of file primitiveMeshI.H.
bool hasCells () const inline
Definition at line 136 of file primitiveMeshI.H.
bool hasEdgeFaces () const inline
Definition at line 142 of file primitiveMeshI.H.
bool hasPointFaces () const inline
Definition at line 148 of file primitiveMeshI.H.
bool hasCellEdges () const inline
Definition at line 154 of file primitiveMeshI.H.
bool hasFaceEdges () const inline
Definition at line 160 of file primitiveMeshI.H.
bool hasPointEdges () const inline
Definition at line 166 of file primitiveMeshI.H.
bool hasPointPoints () const inline
Definition at line 172 of file primitiveMeshI.H.
bool hasCellPoints () const inline
Definition at line 178 of file primitiveMeshI.H.
bool hasCellCentres () const inline
Definition at line 184 of file primitiveMeshI.H.
bool hasFaceCentres () const inline
Definition at line 190 of file primitiveMeshI.H.
bool hasCellVolumes () const inline
Definition at line 196 of file primitiveMeshI.H.
bool hasFaceAreas () const inline
Definition at line 202 of file primitiveMeshI.H.
const Foam::labelList & cellCells (const label cellI, DynamicList< label > & storage) const
cellCells using cells.
Definition at line 112 of file primitiveMeshCellCells.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), cells, DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), and forAll.
const Foam::labelList & cellCells (const label cellI) const
Definition at line 151 of file primitiveMeshCellCells.C.
const Foam::labelList & cellPoints (const label cellI, DynamicList< label > & storage) const
cellPoints using cells
Definition at line 59 of file primitiveMeshCellPoints.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::capacity(), cells, DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), List< T >::clear(), f(), forAll, forAllConstIter, and DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity().
const Foam::labelList & cellPoints (const label cellI) const
Definition at line 101 of file primitiveMeshCellPoints.C.
const Foam::labelList & pointCells (const label pointI, DynamicList< label > & storage) const
pointCells using pointFaces
Definition at line 120 of file primitiveMeshPointCells.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), forAll, n, pFaces, DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::size(), and Foam::sort().
const Foam::labelList & pointCells (const label pointI) const
Definition at line 174 of file primitiveMeshPointCells.C.
const Foam::labelList & pointPoints (const label pointI, DynamicList< label > & storage) const
pointPoints using edges, pointEdges
Definition at line 103 of file primitiveMeshPointPoints.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::capacity(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), forAll, DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), and List< T >::size().
const Foam::labelList & pointPoints (const label pointI) const
Definition at line 135 of file primitiveMeshPointPoints.C.
const Foam::labelList & faceEdges (const label faceI, DynamicList< label > & storage) const
faceEdges using pointFaces, edges, pointEdges
Definition at line 581 of file primitiveMeshEdges.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::capacity(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), forAll, face::nextLabel(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), and List< T >::size().
const Foam::labelList & faceEdges (const label faceI) const
Definition at line 618 of file primitiveMeshEdges.C.
const Foam::labelList & edgeFaces (const label edgeI, DynamicList< label > & storage) const
edgeFaces using pointFaces, edges, pointEdges
Definition at line 58 of file primitiveMeshEdgeFaces.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), Foam::e, and List< T >::size().
const Foam::labelList & edgeFaces (const label edgeI) const
Definition at line 103 of file primitiveMeshEdgeFaces.C.
const Foam::labelList & edgeCells (const label edgeI, DynamicList< label > & storage) const
edgeCells using pointFaces, edges, pointEdges
Definition at line 58 of file primitiveMeshEdgeCells.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), and forAll.
const Foam::labelList & edgeCells (const label edgeI) const
Definition at line 127 of file primitiveMeshEdgeCells.C.
const Foam::labelList & cellEdges (const label cellI, DynamicList< label > & storage) const
cellEdges using cells, pointFaces, edges, pointEdges
Definition at line 625 of file primitiveMeshEdges.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::capacity(), cells, DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), List< T >::clear(), forAll, forAllConstIter, and DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity().
const Foam::labelList & cellEdges (const label cellI) const
Definition at line 667 of file primitiveMeshEdges.C.
void clearGeom ()
Clear geometry.
Definition at line 125 of file primitiveMeshClear.C.
References Foam::deleteDemandDrivenData(), Foam::endl(), and Foam::Pout.
Referenced by polyMesh::clearGeom().
void clearAddressing ()
Clear topological data.
Definition at line 141 of file primitiveMeshClear.C.
References Foam::deleteDemandDrivenData(), Foam::endl(), and Foam::Pout.
Referenced by polyMesh::clearAddressing().
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Definition at line 170 of file primitiveMeshClear.C.
Member Data Documentation
Foam::scalar closedThreshold_ = 1.0e-6 static protected
Static data to control mesh checking.
Cell closedness warning threshold
set as the fraction of un-closed area to closed area
Definition at line 234 of file primitiveMesh.H.
Foam::scalar aspectThreshold_ = 1000 static protected
Aspect ratio warning threshold.
Definition at line 237 of file primitiveMesh.H.
Foam::scalar nonOrthThreshold_ = 70 static protected
Non-orthogonality warning threshold in deg.
Definition at line 240 of file primitiveMesh.H.
Foam::scalar skewThreshold_ = 4 static protected
Skewness warning threshold.
Definition at line 243 of file primitiveMesh.H.
Foam::scalar planarCosAngle_ = 1.0e-6 static protected
Threshold where faces are considered coplanar.
Definition at line 246 of file primitiveMesh.H.
const unsigned cellsPerEdge_ = 4 static
Estimated number of cells per edge.
Definition at line 403 of file primitiveMesh.H.
const unsigned cellsPerPoint_ = 8 static
Estimated number of cells per point.
Definition at line 406 of file primitiveMesh.H.
const unsigned facesPerCell_ = 6 static
Estimated number of faces per cell.
Definition at line 409 of file primitiveMesh.H.
const unsigned facesPerEdge_ = 4 static
Estimated number of faces per edge.
Definition at line 412 of file primitiveMesh.H.
const unsigned facesPerPoint_ = 12 static
Estimated number of faces per point.
Definition at line 415 of file primitiveMesh.H.
const unsigned edgesPerCell_ = 12 static
Estimated number of edges per cell.
Definition at line 418 of file primitiveMesh.H.
const unsigned edgesPerFace_ = 4 static
Estimated number of edges per cell.
Definition at line 421 of file primitiveMesh.H.
const unsigned edgesPerPoint_ = 6 static
Estimated number of edges per point.
Definition at line 424 of file primitiveMesh.H.
const unsigned pointsPerCell_ = 8 static
Estimated number of points per cell.
Definition at line 427 of file primitiveMesh.H.
const unsigned pointsPerFace_ = 4 static
Estimated number of points per face.
Definition at line 430 of file primitiveMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/primitiveMesh.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMesh.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCalcCellShapes.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellCentresAndVols.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellEdges.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellPoints.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheck.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheckEdgeLength.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheckPointNearness.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshClear.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdgeCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdgeFaces.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdges.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshFaceCentresAndAreas.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshFindCell.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshI.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointFaces.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointPoints.C