OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
procLduInterface Class Reference
IO interface for processorLduInterface.
Public Member Functions
procLduInterface (const lduInterfaceField &interface, const scalarField &coeffs)
procLduInterface (Istream &is)
autoPtr< procLduInterface > clone ()
Static Public Member Functions
static autoPtr< procLduInterface > New (Istream &is)
Friends
class LUscalarMatrix
Ostream & operator<< (Ostream &, const procLduInterface &)
Detailed Description
IO interface for processorLduInterface.
Source files
procLduInterface.H
procLduInterface.C
Definition at line 51 of file procLduInterface.H.
Constructor & Destructor Documentation
procLduInterface (const lduInterfaceField & interface, const scalarField & coeffs)
Definition at line 34 of file procLduInterface.C.
References processorLduInterface::comm(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, lduInterfaceField::interface(), processorLduInterface::myProcNo(), processorLduInterface::neighbProcNo(), and processorLduInterface::tag().
procLduInterface (Istream & is)
Definition at line 69 of file procLduInterface.C.
Member Function Documentation
autoPtr<procLduInterface> clone () inline
Definition at line 84 of file procLduInterface.H.
References NotImplemented.
static autoPtr<procLduInterface> New (Istream & is) inline static
Definition at line 90 of file procLduInterface.H.
Friends And Related Function Documentation
friend class LUscalarMatrix friend
Definition at line 71 of file procLduInterface.H.
Ostream& operator<< (Ostream & , const procLduInterface &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LUscalarMatrix/procLduInterface.H
src/OpenFOAM/matrices/LUscalarMatrix/procLduInterface.C