OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polyMesh Class Reference
Mesh consisting of general polyhedral cells.
Public Types
enum readUpdateState { UNCHANGED, POINTS_MOVED, TOPO_CHANGE, TOPO_PATCH_CHANGE }
Enumeration defining the state of the mesh after a read update.
enum cellDecomposition { FACE_PLANES, FACE_CENTRE_TRIS, FACE_DIAG_TRIS, CELL_TETS }
Enumeration defining the decomposition of the cell for.
typedef polyMesh Mesh
typedef polyBoundaryMesh BoundaryMesh
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject * >
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Member Functions
TypeName ("polyMesh")
Runtime type information.
polyMesh (const IOobject &io)
Construct from IOobject.
polyMesh (const IOobject &io, const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< labelList > &owner, const Xfer< labelList > &neighbour, const bool syncPar=true)
Construct from IOobject or from components.
polyMesh (const IOobject &io, const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< cellList > &cells, const bool syncPar=true)
Construct without boundary with cells rather than owner/neighbour.
polyMesh (const IOobject &io, const Xfer< pointField > &points, const cellShapeList &shapes, const faceListList &boundaryFaces, const wordList &boundaryPatchNames, const wordList &boundaryPatchTypes, const word &defaultBoundaryPatchName, const word &defaultBoundaryPatchType, const wordList &boundaryPatchPhysicalTypes, const bool syncPar=true)
Construct from cell shapes.
polyMesh (const IOobject &io, const Xfer< pointField > &points, const cellShapeList &shapes, const faceListList &boundaryFaces, const wordList &boundaryPatchNames, const PtrList< dictionary > &boundaryDicts, const word &defaultBoundaryPatchName, const word &defaultBoundaryPatchType, const bool syncPar=true)
Construct from cell shapes with patch information in dictionary.
virtual ~polyMesh ()
Destructor.
virtual const fileName & dbDir () const
Override the objectRegistry dbDir for a single-region case.
fileName meshDir () const
Return the local mesh directory (dbDir()/meshSubDir)
const fileName & pointsInstance () const
Return the current instance directory for points.
const fileName & facesInstance () const
Return the current instance directory for faces.
void setInstance (const fileName &)
Set the instance for mesh files.
virtual const pointField & points () const
Return raw points.
virtual bool upToDatePoints (const regIOobject &io) const
Return true if io is up-to-date with points.
virtual void setUpToDatePoints (regIOobject &io) const
Set io to be up-to-date with points.
virtual const faceList & faces () const
Return raw faces.
virtual const labelList & faceOwner () const
Return face owner.
virtual const labelList & faceNeighbour () const
Return face neighbour.
virtual const pointField & oldPoints () const
Return old points for mesh motion.
const polyBoundaryMesh & boundaryMesh () const
Return boundary mesh.
const boundBox & bounds () const
Return mesh bounding box.
const Vector< label > & geometricD () const
Return the vector of geometric directions in mesh.
label nGeometricD () const
Return the number of valid geometric dimensions in the mesh.
const Vector< label > & solutionD () const
Return the vector of solved-for directions in mesh.
label nSolutionD () const
Return the number of valid solved-for dimensions in the mesh.
const labelList & tetBasePtIs () const
Return the tetBasePtIs.
const indexedOctree< treeDataCell > & cellTree () const
Return the cell search tree.
const pointZoneMesh & pointZones () const
Return point zone mesh.
const faceZoneMesh & faceZones () const
Return face zone mesh.
const cellZoneMesh & cellZones () const
Return cell zone mesh.
const globalMeshData & globalData () const
Return parallel info.
label comm () const
Return communicator used for parallel communication.
label & comm ()
Return communicator used for parallel communication.
const objectRegistry & thisDb () const
Return the object registry.
bool moving () const
Is mesh moving.
bool moving (const bool m)
Set the mesh to be moving.
bool topoChanging () const
Is mesh topology changing.
bool topoChanging (const bool c)
Set the mesh topology to be changing.
bool changing () const
Is mesh changing (topology changing and/or moving)
virtual tmp< scalarField > movePoints (const pointField &)
Move points, returns volumes swept by faces in motion.
void resetMotion () const
Reset motion.
pointZoneMesh & pointZones ()
Return non-const access to the pointZones.
faceZoneMesh & faceZones ()
Return non-const access to the faceZones.
cellZoneMesh & cellZones ()
Return non-const access to the cellZones.
void addPatches (const List< polyPatch * > &, const bool validBoundary=true)
Add boundary patches.
void addZones (const List< pointZone * > &pz, const List< faceZone * > &fz, const List< cellZone * > &cz)
Add mesh zones.
virtual readUpdateState readUpdate ()
Update the mesh based on the mesh files saved in.
virtual void updateMesh (const mapPolyMesh &mpm)
Update the mesh corresponding to given map.
void removeBoundary ()
Remove boundary patches.
void resetPrimitives (const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< labelList > &owner, const Xfer< labelList > &neighbour, const labelList &patchSizes, const labelList &patchStarts, const bool validBoundary=true)
Reset mesh primitive data. Assumes all patch info correct.
void clearGeom ()
Clear geometry.
void clearAddressing (const bool isMeshUpdate=false)
Clear addressing.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
void clearPrimitives ()
Clear primitive data (points, faces and cells)
void clearAdditionalGeom ()
Clear geometry not used for CFD (cellTree, tetBasePtIs)
void clearCellTree ()
Clear cell tree data.
void removeFiles (const fileName &instanceDir) const
Remove all files from mesh instance.
void removeFiles () const
Remove all files from mesh instance()
virtual bool checkFaceOrthogonality (const bool report=false, labelHashSet *setPtr=NULL) const
Check non-orthogonality.
virtual bool checkFaceSkewness (const bool report=false, labelHashSet *setPtr=NULL) const
Check face skewness.
virtual bool checkEdgeAlignment (const bool report, const Vector< label > &directions, labelHashSet *setPtr) const
Check edge alignment for 1D/2D cases.
virtual bool checkCellDeterminant (const bool report, labelHashSet *setPtr) const
virtual bool checkMeshMotion (const pointField &newPoints, const bool report=false, const bool detailedReport=false) const
Check mesh motion for correctness given motion points.
virtual bool checkFaceWeight (const bool report, const scalar minWeight=0.05, labelHashSet *setPtr=NULL) const
Check for face weights.
virtual bool checkVolRatio (const bool report, const scalar minRatio=0.01, labelHashSet *setPtr=NULL) const
Check for neighbouring cell volumes.
void findCellFacePt (const point &p, label &celli, label &tetFacei, label &tetPti) const
Find the cell, tetFacei and tetPti for point p.
void findTetFacePt (const label celli, const point &p, label &tetFacei, label &tetPti) const
Find the tetFacei and tetPti for point p in celli.
bool pointInCell (const point &p, label celli, const cellDecomposition=CELL_TETS) const
Test if point p is in the celli.
label findCell (const point &p, const cellDecomposition=CELL_TETS) const
Find cell enclosing this location and return index.
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write the objects.
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject * >
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash > > &)
Construct by transferring the parameter contents.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from primitiveMesh
ClassName ("primitiveMesh")
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Construct from components.
virtual ~primitiveMesh ()
Destructor.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Reset this primitiveMesh given the primitive array sizes.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList &cells)
Reset this primitiveMesh given the primitive array sizes and cells.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, const Xfer< cellList > &cells)
Reset this primitiveMesh given the primitive array sizes and cells.
label nPoints () const
label nEdges () const
label nInternalFaces () const
label nFaces () const
label nCells () const
label nInternalPoints () const
Points not on boundary.
label nInternal0Edges () const
Internal edges (i.e. not on boundary face) using.
label nInternal1Edges () const
Internal edges using 0 or 1 boundary point.
label nInternalEdges () const
Internal edges using 0,1 or 2 boundary points.
const cellShapeList & cellShapes () const
Return cell shapes.
const edgeList & edges () const
Return mesh edges. Uses calcEdges.
const labelListList & cellCells () const
const labelListList & edgeCells () const
const labelListList & pointCells () const
const cellList & cells () const
const labelListList & edgeFaces () const
const labelListList & pointFaces () const
const labelListList & cellEdges () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointPoints () const
const labelListList & cellPoints () const
const vectorField & cellCentres () const
const vectorField & faceCentres () const
const scalarField & cellVolumes () const
const vectorField & faceAreas () const
tmp< scalarField > movePoints (const pointField &p, const pointField &oldP)
Move points, returns volumes swept by faces in motion.
bool isInternalFace (const label faceIndex) const
Return true if given face label is internal to the mesh.
virtual bool checkUpperTriangular (const bool report=false, labelHashSet *setPtr=NULL) const
Check face ordering.
virtual bool checkCellsZipUp (const bool report=false, labelHashSet *setPtr=NULL) const
Check cell zip-up.
virtual bool checkFaceVertices (const bool report=false, labelHashSet *setPtr=NULL) const
Check uniqueness of face vertices.
virtual bool checkPoints (const bool report=false, labelHashSet *setPtr=NULL) const
Check for unused points.
virtual bool checkFaceFaces (const bool report=false, labelHashSet *setPtr=NULL) const
Check face-face connectivity.
virtual bool checkClosedBoundary (const bool report=false) const
Check boundary for closedness.
virtual bool checkClosedCells (const bool report=false, labelHashSet *setPtr=NULL, labelHashSet *highAspectSetPtr=NULL, const Vector< label > &solutionD=Vector< label >::one) const
Check cells for closedness.
virtual bool checkFaceAreas (const bool report=false, labelHashSet *setPtr=NULL) const
Check for negative face areas.
virtual bool checkCellVolumes (const bool report=false, labelHashSet *setPtr=NULL) const
Check for negative cell volumes.
virtual bool checkFacePyramids (const bool report=false, const scalar minPyrVol=-SMALL, labelHashSet *setPtr=NULL) const
Check face pyramid volume.
virtual bool checkFaceAngles (const bool report=false, const scalar maxSin=10, labelHashSet *setPtr=NULL) const
Check face angles.
virtual bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage: decompose face and check ratio between.
virtual bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet *setPtr=NULL) const
Check for point-point-nearness,.
virtual bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet *setPtr=NULL) const
Check edge length.
virtual bool checkConcaveCells (const bool report=false, labelHashSet *setPtr=NULL) const
Check for concave cells by the planes of faces.
virtual bool checkTopology (const bool report=false) const
Check mesh topology for correctness.
virtual bool checkGeometry (const bool report=false) const
Check mesh geometry (& implicitly topology) for correctness.
virtual bool checkMesh (const bool report=false) const
Check mesh for correctness. Returns false for no error.
bool pointInCellBB (const point &p, label celli, scalar inflationFraction=0) const
Return true if the point in the cell bounding box.
bool pointInCell (const point &p, label celli) const
Return true if the point is in the cell.
label findNearestCell (const point &location) const
Find the cell with the nearest cell centre to location.
label findCell (const point &location) const
Find cell enclosing this location (-1 if not in mesh)
void printAllocated () const
Print a list of all the currently allocated mesh data.
bool hasCellShapes () const
bool hasEdges () const
bool hasCellCells () const
bool hasEdgeCells () const
bool hasPointCells () const
bool hasCells () const
bool hasEdgeFaces () const
bool hasPointFaces () const
bool hasCellEdges () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointPoints () const
bool hasCellPoints () const
bool hasCellCentres () const
bool hasFaceCentres () const
bool hasCellVolumes () const
bool hasFaceAreas () const
const labelList & cellCells (const label cellI, DynamicList< label > &) const
cellCells using cells.
const labelList & cellCells (const label cellI) const
const labelList & cellPoints (const label cellI, DynamicList< label > &) const
cellPoints using cells
const labelList & cellPoints (const label cellI) const
const labelList & pointCells (const label pointI, DynamicList< label > &) const
pointCells using pointFaces
const labelList & pointCells (const label pointI) const
const labelList & pointPoints (const label pointI, DynamicList< label > &) const
pointPoints using edges, pointEdges
const labelList & pointPoints (const label pointI) const
const labelList & faceEdges (const label faceI, DynamicList< label > &) const
faceEdges using pointFaces, edges, pointEdges
const labelList & faceEdges (const label faceI) const
const labelList & edgeFaces (const label edgeI, DynamicList< label > &) const
edgeFaces using pointFaces, edges, pointEdges
const labelList & edgeFaces (const label edgeI) const
const labelList & edgeCells (const label edgeI, DynamicList< label > &) const
edgeCells using pointFaces, edges, pointEdges
const labelList & edgeCells (const label edgeI) const
const labelList & cellEdges (const label cellI, DynamicList< label > &) const
cellEdges using cells, pointFaces, edges, pointEdges
const labelList & cellEdges (const label cellI) const
void clearGeom ()
Clear geometry.
void clearAddressing ()
Clear topological data.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Static Public Attributes
static word defaultRegion = "region0"
Return the default region name.
static word meshSubDir = "polyMesh"
Return the mesh sub-directory name (usually "polyMesh")
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Static Public Attributes inherited from primitiveMesh
static const unsigned cellsPerEdge_ = 4
Estimated number of cells per edge.
static const unsigned cellsPerPoint_ = 8
Estimated number of cells per point.
static const unsigned facesPerCell_ = 6
Estimated number of faces per cell.
static const unsigned facesPerEdge_ = 4
Estimated number of faces per edge.
static const unsigned facesPerPoint_ = 12
Estimated number of faces per point.
static const unsigned edgesPerCell_ = 12
Estimated number of edges per cell.
static const unsigned edgesPerFace_ = 4
Estimated number of edges per cell.
static const unsigned edgesPerPoint_ = 6
Estimated number of edges per point.
static const unsigned pointsPerCell_ = 8
Estimated number of points per cell.
static const unsigned pointsPerFace_ = 4
Estimated number of points per face.
Additional Inherited Members
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Member Functions inherited from primitiveMesh
static void calcCells (cellList &, const labelUList &own, const labelUList &nei, const label nCells=-1)
Helper function to calculate cell-face addressing from.
static bool calcPointOrder (label &nInternalPoints, labelList &pointMap, const faceList &, const label nInternalFaces, const label nPoints)
Helper function to calculate point ordering. Returns true.
static scalar setClosedThreshold (const scalar)
Set the closedness ratio warning threshold.
static scalar setAspectThreshold (const scalar)
Set the aspect ratio warning threshold.
static scalar setNonOrthThreshold (const scalar)
Set the non-orthogonality warning threshold in degrees.
static scalar setSkewThreshold (const scalar)
Set the skewness warning threshold as percentage.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from primitiveMesh
void calcFaceCentresAndAreas () const
Calculate face centres and areas.
void makeFaceCentresAndAreas (const pointField &p, vectorField &fCtrs, vectorField &fAreas) const
void calcCellCentresAndVols () const
Calculate cell centres and volumes.
void makeCellCentresAndVols (const vectorField &fCtrs, const vectorField &fAreas, vectorField &cellCtrs, scalarField &cellVols) const
void calcEdgeVectors () const
Calculate edge vectors.
bool checkDuplicateFaces (const label, const Map< label > &, label &nBaffleFaces, labelHashSet *) const
Check if all points on face are shared with another face.
bool checkCommonOrder (const label, const Map< label > &, labelHashSet *) const
Check that shared points are in consecutive order.
bool checkClosedBoundary (const vectorField &, const bool, const PackedBoolList &) const
Check boundary for closedness.
bool checkClosedCells (const vectorField &faceAreas, const scalarField &cellVolumes, const bool report, labelHashSet *setPtr, labelHashSet *aspectSetPtr, const Vector< label > &meshD) const
Check cells for closedness.
bool checkFaceAreas (const vectorField &faceAreas, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative face areas.
bool checkCellVolumes (const scalarField &vols, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative cell volumes.
bool checkFaceOrthogonality (const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check for non-orthogonality.
bool checkFacePyramids (const pointField &points, const vectorField &ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet *setPtr) const
Check face pyramid volume.
bool checkFaceSkewness (const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check face skewness.
bool checkFaceAngles (const pointField &points, const vectorField &faceAreas, const bool report, const scalar maxDeg, labelHashSet *setPtr) const
Check face angles.
bool checkFaceFlatness (const pointField &points, const vectorField &faceCentres, const vectorField &faceAreas, const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage.
bool checkConcaveCells (const vectorField &fAreas, const pointField &fCentres, const bool report, labelHashSet *setPtr) const
Check for concave cells by the planes of faces.
primitiveMesh ()
Construct null.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Static Protected Attributes inherited from primitiveMesh
static scalar closedThreshold_ = 1.0e-6
Static data to control mesh checking.
static scalar aspectThreshold_ = 1000
Aspect ratio warning threshold.
static scalar nonOrthThreshold_ = 70
Non-orthogonality warning threshold in deg.
static scalar skewThreshold_ = 4
Skewness warning threshold.
static scalar planarCosAngle_ = 1.0e-6
Threshold where faces are considered coplanar.
Detailed Description
Mesh consisting of general polyhedral cells.
Source files
polyMesh.H
polyMesh.C
polyMeshInitMesh.C
polyMeshClear.C
polyMeshFromShapeMesh.C
polyMeshIO.C
polyMeshUpdate.C
polyMeshCheck.C
Definition at line 74 of file polyMesh.H.
Member Typedef Documentation
typedef polyMesh Mesh
Definition at line 298 of file polyMesh.H.
typedef polyBoundaryMesh BoundaryMesh
Definition at line 299 of file polyMesh.H.
Member Enumeration Documentation
enum readUpdateState
Enumeration defining the state of the mesh after a read update.
Used for post-processing applications, where the mesh needs to update based on the files written in time directores
Enumerator
UNCHANGED
POINTS_MOVED
TOPO_CHANGE
TOPO_PATCH_CHANGE
Definition at line 88 of file polyMesh.H.
enum cellDecomposition
Enumeration defining the decomposition of the cell for.
inside/outside test
Enumerator
FACE_PLANES
FACE_CENTRE_TRIS
FACE_DIAG_TRIS
CELL_TETS
Definition at line 98 of file polyMesh.H.
Constructor & Destructor Documentation
polyMesh (const IOobject & io) explicit
Construct from IOobject.
Definition at line 140 of file polyMesh.C.
References Foam::endl(), Foam::exists(), polyMesh::meshDir(), polyMesh::meshSubDir, IOobject::MUST_READ, primitiveMesh::nCells(), IOobject::NO_WRITE, primitiveMesh::nPoints(), IOobject::objectPath(), Foam::returnReduce(), objectRegistry::time(), polyBoundaryMesh::updateMesh(), WarningIn, and regIOobject::write().
polyMesh (const IOobject & io, const Xfer< pointField > & points, const Xfer< faceList > & faces, const Xfer< labelList > & owner, const Xfer< labelList > & neighbour, const bool syncPar = true)
Construct from IOobject or from components.
Boundary is added using addPatches() member function
Definition at line 322 of file polyMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, Foam::max(), Foam::min(), and List< T >::size().
polyMesh (const IOobject & io, const Xfer< pointField > & points, const Xfer< faceList > & faces, const Xfer< cellList > & cells, const bool syncPar = true)
Construct without boundary with cells rather than owner/neighbour.
Boundary is added using addPatches() member function
Definition at line 482 of file polyMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, Foam::max(), Foam::min(), and List< T >::size().
polyMesh (const IOobject & io, const Xfer< pointField > & points, const cellShapeList & shapes, const faceListList & boundaryFaces, const wordList & boundaryPatchNames, const wordList & boundaryPatchTypes, const word & defaultBoundaryPatchName, const word & defaultBoundaryPatchType, const wordList & boundaryPatchPhysicalTypes, const bool syncPar = true)
Construct from cell shapes.
Definition at line 422 of file polyMeshFromShapeMesh.C.
References cells, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::findIndex(), forAll, Foam::Info, polyPatch::New(), Foam::reduce(), List< T >::size(), and WarningIn.
polyMesh (const IOobject & io, const Xfer< pointField > & points, const cellShapeList & shapes, const faceListList & boundaryFaces, const wordList & boundaryPatchNames, const PtrList< dictionary > & boundaryDicts, const word & defaultBoundaryPatchName, const word & defaultBoundaryPatchType, const bool syncPar = true)
Construct from cell shapes with patch information in dictionary.
format.
Definition at line 707 of file polyMeshFromShapeMesh.C.
References cells, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::findIndex(), forAll, Foam::Info, Foam::name(), polyPatch::New(), Foam::reduce(), dictionary::set(), List< T >::size(), Foam::type(), and WarningIn.
~polyMesh () virtual
Destructor.
Definition at line 790 of file polyMesh.C.
Member Function Documentation
TypeName ("polyMesh")
Runtime type information.
const Foam::fileName & dbDir () const virtual
Override the objectRegistry dbDir for a single-region case.
Reimplemented from objectRegistry.
Definition at line 799 of file polyMesh.C.
References objectRegistry::dbDir().
Referenced by topoSet::localPath().
Foam::fileName meshDir () const
Return the local mesh directory (dbDir()/meshSubDir)
Definition at line 812 of file polyMesh.C.
Referenced by displacementMotionSolver::points0IO(), and polyMesh::polyMesh().
const Foam::fileName & pointsInstance () const
Return the current instance directory for points.
Used in the consruction of gemometric mesh data dependent on points
Definition at line 818 of file polyMesh.C.
Referenced by timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), and fvMesh::delta().
const Foam::fileName & facesInstance () const
Return the current instance directory for faces.
Definition at line 824 of file polyMesh.C.
Referenced by attachPolyTopoChanger::attach(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), manualDecomp::decompose(), topoSet::localPath(), and manualRenumber::renumber().
void setInstance (const fileName & inst)
Set the instance for mesh files.
Definition at line 32 of file polyMeshIO.C.
References IOobject::AUTO_WRITE, Foam::endl(), Foam::Info, IOobject::instance(), and IOobject::writeOpt().
Referenced by autoLayerDriver::addLayers(), attachPolyTopoChanger::attach(), Foam::polyMeshZipUpCells(), and polyMesh::updateMesh().
const Foam::pointField & points () const virtual
Return raw points.
Implements primitiveMesh.
Definition at line 1035 of file polyMesh.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by autoLayerDriver::addLayers(), polyTopoChange::addMesh(), polyDualMesh::calcFeatures(), meshRefinement::calculateEdgeWeights(), polyTopoChange::changeMesh(), layerAdditionRemoval::changeTopology(), polyMeshTetDecomposition::checkFaceTets(), motionSmootherAlgo::checkMesh(), pointZone::checkParallelSync(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), pointLinear< Type >::correction(), geomCellLooper::cut(), faceCoupleInfo::faceCoupleInfo(), mappedPatchBase::facePoint(), tetIndices::faceTri(), polyMeshTetDecomposition::findBasePoint(), FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs(), mappedPatchBase::findSamples(), polyMeshTetDecomposition::findSharedBasePoint(), polyMeshAdder::findSharedPoints(), faceCorrectedSnGrad< Type >::fullGradCorrection(), meshRefinement::makePatch(), meshToMeshMethod::maskCells(), polyMeshAdder::mergePoints(), MeshedSurface< Face >::MeshedSurface(), momentOfInertia::meshInertia(), meshTriangulation::meshTriangulation(), movingConeTopoFvMesh::movingConeTopoFvMesh(), treeDataCell::findIntersectOp::operator()(), tetOverlapVolume::overlappingCells(), pointMVCWeight::pointMVCWeight(), Foam::polyMeshZipUpCells(), fvMeshDistribute::printMeshInfo(), boundaryMesh::read(), boundaryMesh::setFeatureEdges(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), meshRefinement::testSyncPointList(), tetIndices::tet(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), cellMotionFvPatchField< Type >::updateCoeffs(), pointEdgePoint::updateEdge(), componentDisplacementMotionSolver::updateMesh(), displacementMotionSolver::updateMesh(), pointEdgePoint::updatePoint(), Implicit< CloudType >::velocityCorrection(), wallLayerCells::wallLayerCells(), FacePostProcessing< CloudType >::write(), and meshToMeshMethod::writeConnectivity().
bool upToDatePoints (const regIOobject & io) const virtual
Return true if io is up-to-date with points.
Definition at line 1048 of file polyMesh.C.
References regIOobject::upToDate().
void setUpToDatePoints (regIOobject & io) const virtual
Set io to be up-to-date with points.
Definition at line 1054 of file polyMesh.C.
References regIOobject::eventNo().
const Foam::faceList & faces () const virtual
Return raw faces.
Implements primitiveMesh.
Definition at line 1060 of file polyMesh.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
Referenced by polyTopoChange::addMesh(), faceZone::calcFaceZonePatch(), polyDualMesh::calcFeatures(), pointMVCWeight::calcWeights(), polyMeshTetDecomposition::cellTetIndices(), layerAdditionRemoval::changeTopology(), polyMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceFlatness(), polyMeshGeometry::checkFacePyramids(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), edgeCollapser::checkMeshQuality(), polyMeshGeometry::checkTriangleTwist(), inversePointDistanceDiffusivity::correct(), pointLinear< Type >::correction(), wallBoundedParticle::currentEdge(), decompositionMethod::decompose(), autoSnapDriver::doSnap(), dynamicRefineFvMesh::dynamicRefineFvMesh(), faceCoupleInfo::faceCoupleInfo(), mappedPatchBase::facePoint(), polyMeshTetDecomposition::faceTetIndices(), tetIndices::faceTri(), tetIndices::faceTriIs(), polyMeshTetDecomposition::findBasePoint(), polyMeshTetDecomposition::findFaceBasePts(), FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs(), sampledSet::findNearFace(), polyMeshTetDecomposition::findSharedBasePoint(), polyMeshTetDecomposition::findTet(), cellPointWeight::findTetrahedron(), cellPointWeight::findTriangle(), faceCorrectedSnGrad< Type >::fullGradCorrection(), autoSnapDriver::getZoneSurfacePoints(), meshRefinement::makePatch(), meshToMeshMethod::maskCells(), polyMeshAdder::mergePoints(), MeshedSurface< Face >::MeshedSurface(), meshTriangulation::meshTriangulation(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), tetIndices::oldFaceTri(), tetIndices::oldTet(), treeDataCell::findIntersectOp::operator()(), pointMVCWeight::pointMVCWeight(), Foam::polyMeshZipUpCells(), wallBoundedStreamLine::read(), decompositionMethod::setConstraints(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), syncTools::syncEdgeMap(), tetIndices::tet(), tetIndices::tetIndices(), particle< Type >::tetNeighbour(), polyMeshTetDecomposition::triangleTetIndices(), directionInfo::updateCell(), Implicit< CloudType >::velocityCorrection(), wallLayerCells::wallLayerCells(), and meshToMeshMethod::writeConnectivity().
const Foam::labelList & faceOwner () const virtual
Return face owner.
Implements primitiveMesh.
Definition at line 1073 of file polyMesh.C.
Referenced by polyTopoChange::addMesh(), polyMeshGeometry::affectedCells(), autoSnapDriver::avgCellCentres(), decompositionMethod::calcCellCells(), polyDualMesh::calcFeatures(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), polyMeshGeometry::checkVolRatio(), cellDistFuncs::correctBoundaryFaceCells(), decompositionMethod::decompose(), dynamicRefineFvMesh::dynamicRefineFvMesh(), polyMeshTools::faceOrthogonality(), mappedPatchBase::facePoint(), polyMeshTools::faceSkewness(), polyMeshTetDecomposition::faceTetIndices(), polyMeshTools::faceWeights(), polyMeshTetDecomposition::findBasePoint(), polyMeshTetDecomposition::findFaceBasePts(), polyMeshTetDecomposition::findSharedBasePoint(), cellPointWeight::findTriangle(), get_edge_list(), sampledSet::getBoundaryCell(), sampledSet::getCell(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), polyMeshAdder::mergePoints(), meshTriangulation::meshTriangulation(), fvFieldDecomposer::processorVolPatchFieldDecomposer::processorVolPatchFieldDecomposer(), sampledSet::pushIn(), undoableMeshCutter::removeSplitFaces(), SloanRenumber::renumber(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), Foam::fvc::smooth(), Foam::fvc::spread(), Foam::fvc::sweep(), tetIndices::tetIndices(), particle< Type >::tetNeighbour(), polyMeshTetDecomposition::triangleTetIndices(), polyMeshTools::volRatio(), and regionSizeDistribution::write().
const Foam::labelList & faceNeighbour () const virtual
Return face neighbour.
Implements primitiveMesh.
Definition at line 1079 of file polyMesh.C.
Referenced by addPatchCellLayer::addedCells(), polyTopoChange::addMesh(), polyMeshGeometry::affectedCells(), decompositionMethod::calcCellCells(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), polyMeshGeometry::checkVolRatio(), decompositionMethod::decompose(), dynamicRefineFvMesh::dynamicRefineFvMesh(), polyMeshTools::faceOrthogonality(), polyMeshTools::faceSkewness(), polyMeshTools::faceWeights(), polyMeshTetDecomposition::findSharedBasePoint(), get_edge_list(), sampledSet::getCell(), interRegionExplicitPorositySource::initialise(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), polyMeshAdder::mergePoints(), fvFieldDecomposer::processorVolPatchFieldDecomposer::processorVolPatchFieldDecomposer(), undoableMeshCutter::removeSplitFaces(), SloanRenumber::renumber(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), polyMeshTools::volRatio(), and regionSizeDistribution::write().
const Foam::pointField & oldPoints () const virtual
Return old points for mesh motion.
Implements primitiveMesh.
Definition at line 1085 of file polyMesh.C.
References Foam::endl(), and WarningIn.
Referenced by attachPolyTopoChanger::attach(), tetIndices::oldFaceTri(), tetIndices::oldTet(), and movingWallVelocityFvPatchVectorField::updateCoeffs().
const polyBoundaryMesh& boundaryMesh () const inline
Return boundary mesh.
Definition at line 421 of file polyMesh.H.
Referenced by isoSurface::adaptPatchFields(), fvMeshAdder::add(), polyMeshAdder::add(), autoLayerDriver::addLayers(), polyTopoChange::addMesh(), fvMeshTools::addPatch(), meshRefinement::addPatch(), cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), meshRefinement::appendPatch(), attachPolyTopoChanger::attach(), extrudePatchMesh::bottomPatch(), decompositionMethod::calcCellCells(), polyDualMesh::calcFeatures(), curvatureSeparation::calcInvR1(), wallShearStress::calcShearStress(), addPatchCellLayer::calcSidePatch(), cellPointWeightWallModified::cellPointWeightWallModified(), polyTopoChange::changeMesh(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), polyMeshGeometry::checkVolRatio(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), patchInjection::correct(), wallDistData< TransferType >::correct(), cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), curvatureSeparation::curvatureSeparation(), structuredDecomp::decompose(), decompositionMethod::decompose(), directions::directions(), fvMeshDistribute::distribute(), autoLayerDriver::doLayers(), extendedCellToCellStencil::extendedCellToCellStencil(), extendedCellToFaceStencil::extendedCellToFaceStencil(), extendedFaceToCellStencil::extendedFaceToCellStencil(), extrudePatchMesh::extrudePatchMesh(), polyMeshTools::faceOrthogonality(), polyMeshTools::faceSkewness(), polyMeshTools::faceWeights(), localPointRegion::findDuplicateFacePairs(), patchProbes::findElements(), polyMeshTetDecomposition::findFaceBasePts(), fvBoundaryMesh::findIndices(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), cellDistFuncs::getPatchIDs(), injectionModelList::info(), SurfaceFilmModel< CloudType >::inject(), interpolationCellPatchConstrained< Type >::interpolate(), localPointRegion::localPointRegion(), polyTopoChange::makeMesh(), meshRefinement::makePatch(), Foam::MapConsistentSubMesh(), mappedPatchFieldBase< Type >::mappedField(), cellDistFuncs::maxPatchSize(), polyMeshAdder::mergePoints(), meshTriangulation::meshTriangulation(), DSMCParcel< ParcelType >::move(), Cloud< ParticleType >::move(), KinematicParcel< ParcelType >::move(), regionModel::nbrCoupledPatchID(), regionCoupledBase::neighbPatch(), regionCoupledBase::neighbPatchID(), sampledPatch::patchIDs(), boundaryMesh::patchify(), patchInjection::patchInjection(), patchInjectionBase::patchInjectionBase(), patchInteractionDataList::patchInteractionDataList(), Foam::polyMeshZipUpCells(), polyTopoChange::polyTopoChange(), nearWallFields::read(), boundaryMesh::read(), forces::read(), ensightParts::recalculate(), SloanRenumber::renumber(), structuredRenumber::renumber(), fvMeshTools::reorderPatches(), autoSnapDriver::repatchToSurface(), sampledCuttingPlane::sampledCuttingPlane(), sampledIsoSurface::sampledIsoSurface(), sampledPatchInternalField::sampledPatchInternalField(), mappedPatchFieldBase< Type >::sampleField(), mappedPatchBase::sampleMesh(), mappedPatchBase::samplePolyPatch(), decompositionMethod::setConstraints(), patchInjectionBase::setPositionAndCell(), perfectInterface::setRefinement(), meshCutAndRemove::setRefinement(), fvMatrix< Type >::setValuesFromList(), extrudePatchMesh::sidesPatch(), singleCellFvMesh::singleCellFvMesh(), Foam::fvc::smooth(), thermalBaffle::solveEnergy(), Foam::fvc::spread(), thermoSingleLayer::Srho(), cellDistFuncs::sumPatchSize(), regionCoupledBase::surfPtr(), mappedPatchBase::surfPtr(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), Foam::fvc::sweep(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncPointMap(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), extrudePatchMesh::topPatch(), sampledPatch::update(), surfaceDisplacementPointPatchVectorField::updateCoeffs(), thermalBaffleFvPatchScalarField::updateCoeffs(), patchInjectionBase::updateMesh(), perfectInterface::updateMesh(), attachDetach::updateMesh(), slidingInterface::updateMesh(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), cellToFaceStencil::validBoundaryFaces(), cellToCellStencil::validBoundaryFaces(), Implicit< CloudType >::velocityCorrection(), polyMeshTools::volRatio(), wallLayerCells::wallLayerCells(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), PatchPostProcessing< CloudType >::write(), and thermalBaffleFvPatchScalarField::write().
const boundBox& bounds () const inline
Return mesh bounding box.
Definition at line 427 of file polyMesh.H.
Referenced by nearWallFields::calcAddressing(), Foam::meshTools::constrainToMeshCentre(), refinementParameters::findCells(), isoSurfaceCell::isoSurfaceCell(), Kmesh::Kmesh(), meshToMeshMethod::maskCells(), and interRegionOption::setMapper().
const Foam::Vector< Foam::label > & geometricD () const
Return the vector of geometric directions in mesh.
Defined according to the presence of empty and wedge patches. 1 indicates unconstrained direction and -1 a constrained direction.
Definition at line 830 of file polyMesh.C.
Referenced by Foam::meshTools::constrainToMeshCentre(), and FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs().
Foam::label nGeometricD () const
Return the number of valid geometric dimensions in the mesh.
Definition at line 841 of file polyMesh.C.
References Foam::cmptSum().
Referenced by FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs().
const Foam::Vector< Foam::label > & solutionD () const
Return the vector of solved-for directions in mesh.
Differs from geometricD in that it includes for wedge cases the circumferential direction in case of swirl. 1 indicates valid direction and -1 an invalid direction.
Definition at line 847 of file polyMesh.C.
Referenced by get_geom_list(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), DSMCParcel< ParcelType >::move(), and ThermoSurfaceFilm< CloudType >::splashInteraction().
Foam::label nSolutionD () const
Return the number of valid solved-for dimensions in the mesh.
Definition at line 858 of file polyMesh.C.
References Foam::cmptSum().
Referenced by get_geom_list(), get_mesh_dim(), and GradientDispersionRAS< CloudType >::update().
const Foam::labelList & tetBasePtIs () const
Return the tetBasePtIs.
Definition at line 864 of file polyMesh.C.
References Foam::endl(), polyMeshTetDecomposition::findFaceBasePts(), and WarningIn.
Referenced by wallBoundedParticle::currentEdge(), mappedPatchBase::facePoint(), mappedPatchBase::facePoints(), polyMeshTetDecomposition::faceTetIndices(), refinementParameters::findCells(), patchProbes::findElements(), meshSearch::meshSearch(), tetIndices::tetIndices(), particle< Type >::tetNeighbour(), and polyMeshTetDecomposition::triangleTetIndices().
const Foam::indexedOctree< Foam::treeDataCell > & cellTree () const
Return the cell search tree.
Definition at line 890 of file polyMesh.C.
References Foam::e, treeBoundBox::extend(), boundBox::max(), boundBox::min(), points, and rndGen().
Referenced by mappedPatchBase::findSamples(), and tetOverlapVolume::overlappingCells().
const pointZoneMesh& pointZones () const inline
Return point zone mesh.
Definition at line 457 of file polyMesh.H.
Referenced by polyTopoChange::addMesh(), polyTopoChange::changeMesh(), polyTopoChange::makeMesh(), slidingInterface::modifyMotionPoints(), pointZoneSet::pointZoneSet(), polyTopoChange::polyTopoChange(), fvMeshDistribute::printMeshInfo(), and slidingInterface::updateMesh().
const faceZoneMesh& faceZones () const inline
Return face zone mesh.
Definition at line 463 of file polyMesh.H.
Referenced by surfaceZonesInfo::addFaceZonesToMesh(), polyTopoChange::addMesh(), polyTopoChange::changeMesh(), layerAdditionRemoval::changeTopology(), meshRefinement::checkCoupledFaceZones(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), autoSnapDriver::doSnap(), faceZoneSet::faceZoneSet(), autoSnapDriver::getZoneSurfacePoints(), polyTopoChange::makeMesh(), polyMeshAdder::mergePoints(), slidingInterface::modifyMotionPoints(), movingConeTopoFvMesh::movingConeTopoFvMesh(), Foam::polyMeshZipUpCells(), polyTopoChange::polyTopoChange(), fvMeshDistribute::printMeshInfo(), autoSnapDriver::repatchToSurface(), decompositionMethod::setConstraints(), perfectInterface::setRefinement(), perfectInterface::updateMesh(), attachDetach::updateMesh(), slidingInterface::updateMesh(), and FacePostProcessing< CloudType >::write().
const cellZoneMesh& cellZones () const inline
Return cell zone mesh.
Definition at line 469 of file polyMesh.H.
Referenced by cellTable::addCellZones(), surfaceZonesInfo::addCellZonesToMesh(), polyTopoChange::addMesh(), forces::calcForcesMoment(), cellZoneSet::cellZoneSet(), polyTopoChange::changeMesh(), interRegionExplicitPorositySource::initialise(), polyTopoChange::makeMesh(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), cellTable::operator=(), polyTopoChange::polyTopoChange(), fvMeshDistribute::printMeshInfo(), ensightParts::recalculate(), sampledPlane::sampledPlane(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), displacementLayeredMotionMotionSolver::solve(), sampledPlane::update(), and CellZoneInjection< CloudType >::updateMesh().
const Foam::globalMeshData & globalData () const
Return parallel info.
Definition at line 1200 of file polyMesh.C.
References Foam::endl(), and Foam::Pout.
Referenced by structuredDecomp::decompose(), decompositionMethod::decompose(), PatchTools::edgeNormals(), polyMeshAdder::findSharedPoints(), syncTools::getMasterEdges(), syncTools::getMasterPoints(), pointBoundaryMesh::movePoints(), polyBoundaryMesh::movePoints(), PatchTools::pointNormals(), zoltanRenumber::renumber(), structuredRenumber::renumber(), Foam::fvc::smooth(), syncTools::syncEdgeList(), syncTools::syncEdgeMap(), syncTools::syncPointList(), syncTools::syncPointMap(), pointConstraints::syncUntransformedData(), pointBoundaryMesh::updateMesh(), polyBoundaryMesh::updateMesh(), and FacePostProcessing< CloudType >::write().
Foam::label comm () const
Return communicator used for parallel communication.
Definition at line 1218 of file polyMesh.C.
Referenced by fvMesh::comm(), and processorPolyPatch::comm().
Foam::label & comm ()
Return communicator used for parallel communication.
Definition at line 1224 of file polyMesh.C.
const objectRegistry& thisDb () const inline
Return the object registry.
Definition at line 484 of file polyMesh.H.
Referenced by regionCoupledBaseGAMGInterface::nbrLduInterface(), and fvMesh::thisDb().
bool moving () const inline
Is mesh moving.
Definition at line 493 of file polyMesh.H.
Referenced by polyMesh::changing(), Foam::MULES::correct(), Foam::MULES::explicitSolve(), fvMesh::fvMesh(), cyclicACMIPolyPatch::initPatchFaceAreas(), Foam::MULES::limiter(), reactingOneDim::solveContinuity(), reactingOneDim::solveSpeciesMass(), movingWallVelocityFvPatchVectorField::updateCoeffs(), fvMesh::Vsc(), and fvMesh::Vsc0().
bool moving (const bool m) inline
Set the mesh to be moving.
Definition at line 499 of file polyMesh.H.
bool topoChanging () const inline
Is mesh topology changing.
Definition at line 507 of file polyMesh.H.
Referenced by polyTopoChange::changeMesh(), and polyMesh::changing().
bool topoChanging (const bool c) inline
Set the mesh topology to be changing.
Definition at line 513 of file polyMesh.H.
References Foam::constant::universal::c.
bool changing () const inline
Is mesh changing (topology changing and/or moving)
Definition at line 521 of file polyMesh.H.
References polyMesh::moving(), and polyMesh::topoChanging().
Referenced by Foam::correctUphiBCs(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), and pyrolysisModelCollection::evolve().
Foam::tmp< Foam::scalarField > movePoints (const pointField & newPoints) virtual
Move points, returns volumes swept by faces in motion.
Reimplemented in fvMesh.
Definition at line 1105 of file polyMesh.C.
References IOobject::AUTO_WRITE, Foam::endl(), Foam::Info, primitiveMesh::movePoints(), Foam::nl, timeIndex, and regIOobject::write().
Referenced by attachPolyTopoChanger::attach(), and fvMesh::movePoints().
void resetMotion () const
Reset motion.
Definition at line 1192 of file polyMesh.C.
pointZoneMesh& pointZones () inline
Return non-const access to the pointZones.
Definition at line 536 of file polyMesh.H.
faceZoneMesh& faceZones () inline
Return non-const access to the faceZones.
Definition at line 542 of file polyMesh.H.
cellZoneMesh& cellZones () inline
Return non-const access to the cellZones.
Definition at line 548 of file polyMesh.H.
void addPatches (const List< polyPatch * > & p, const bool validBoundary = true)
Add boundary patches.
Definition at line 925 of file polyMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, forAll, and List< T >::size().
Referenced by polyMeshAdder::add(), attachPolyTopoChanger::attach(), and meshReader::mesh().
void addZones (const List< pointZone * > & pz, const List< faceZone * > & fz, const List< cellZone * > & cz)
Add mesh zones.
Definition at line 971 of file polyMesh.C.
References Foam::abort(), IOobject::AUTO_WRITE, Foam::FatalError, FatalErrorIn, forAll, and List< T >::size().
Referenced by polyTopoChange::makeMesh().
Foam::polyMesh::readUpdateState readUpdate () virtual
Update the mesh based on the mesh files saved in.
time directories
Reimplemented in fvMesh.
Definition at line 66 of file polyMeshIO.C.
References cells, Foam::endl(), Foam::exists(), Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, Foam::Info, IOobject::MUST_READ, Foam::name(), polyBoundaryMesh::names(), Foam::nl, IOobject::NO_WRITE, IOobject::objectPath(), polyMesh::POINTS_MOVED, IOobject::READ_IF_PRESENT, PtrList< T >::setSize(), List< T >::size(), PtrList< T >::size(), polyMesh::TOPO_CHANGE, polyMesh::TOPO_PATCH_CHANGE, Foam::type(), polyBoundaryMesh::types(), polyMesh::UNCHANGED, and WarningIn.
Referenced by fvMesh::readUpdate().
void updateMesh (const mapPolyMesh & mpm) virtual
Update the mesh corresponding to given map.
Reimplemented in fvMesh.
Definition at line 39 of file polyMeshUpdate.C.
References ZoneMesh< ZoneType, MeshType >::clearAddressing(), Foam::endl(), forAll, Foam::Info, Field< Type >::map(), mapPolyMesh::pointMap(), polyMesh::setInstance(), List< T >::setSize(), List< T >::size(), objectRegistry::time(), timeName, and polyBoundaryMesh::updateMesh().
Referenced by fvMesh::updateMesh().
void removeBoundary ()
Remove boundary patches.
Definition at line 36 of file polyMeshClear.C.
References PtrList< T >::clear(), polyMesh::clearOut(), Foam::endl(), Foam::Info, and PtrList< T >::setSize().
Referenced by attachPolyTopoChanger::attach(), and fvMesh::removeFvBoundary().
void resetPrimitives (const Xfer< pointField > & points, const Xfer< faceList > & faces, const Xfer< labelList > & owner, const Xfer< labelList > & neighbour, const labelList & patchSizes, const labelList & patchStarts, const bool validBoundary = true)
Reset mesh primitive data. Assumes all patch info correct.
(so does e.g. parallel communication). If not use validBoundary=false
Definition at line 666 of file polyMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorIn, forAll, Foam::max(), Foam::min(), Foam::notNull(), nPoints, points, Foam::returnReduce(), List< T >::size(), and timeName.
Referenced by polyTopoChange::changeMesh(), and Foam::polyMeshZipUpCells().
void clearGeom ()
Clear geometry.
Definition at line 55 of file polyMeshClear.C.
References primitiveMesh::clearGeom(), Foam::endl(), and Foam::Info.
void clearAddressing (const bool isMeshUpdate = false)
Clear addressing.
Definition at line 99 of file polyMeshClear.C.
References primitiveMesh::clearAddressing(), meshObject::clearUpto(), Foam::endl(), and Foam::Info.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Definition at line 173 of file polyMeshClear.C.
Referenced by fvMesh::clearOut(), Foam::polyMeshZipUpCells(), and polyMesh::removeBoundary().
void clearPrimitives ()
Clear primitive data (points, faces and cells)
Definition at line 160 of file polyMeshClear.C.
void clearAdditionalGeom ()
Clear geometry not used for CFD (cellTree, tetBasePtIs)
Definition at line 83 of file polyMeshClear.C.
References Foam::endl(), and Foam::Info.
void clearCellTree ()
Clear cell tree data.
Definition at line 180 of file polyMeshClear.C.
References Foam::endl(), and Foam::Info.
void removeFiles (const fileName & instanceDir) const
Remove all files from mesh instance.
Definition at line 1230 of file polyMesh.C.
References Foam::isDir(), fileName::path(), Foam::rm(), and Foam::rmDir().
Referenced by meshReader::writeMesh().
void removeFiles () const
Remove all files from mesh instance()
Definition at line 1254 of file polyMesh.C.
bool checkFaceOrthogonality (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check non-orthogonality.
Could override checkClosedBoundary to not look at (collocated!) coupled.
faces bool Foam::polyMesh::checkClosedBoundary(const bool report) const { return primitiveMesh::checkClosedBoundary (faceAreas(), report, syncTools::getInternalOrCollocatedCoupledFaces(*this)); }
Reimplemented from primitiveMesh.
Definition at line 709 of file polyMeshCheck.C.
bool checkFaceSkewness (const bool report = false, labelHashSet * setPtr = NULL) const virtual
Check face skewness.
Reimplemented from primitiveMesh.
Definition at line 726 of file polyMeshCheck.C.
References points.
bool checkEdgeAlignment (const bool report, const Vector< label > & directions, labelHashSet * setPtr) const virtual
Check edge alignment for 1D/2D cases.
Definition at line 745 of file polyMeshCheck.C.
References points.
bool checkCellDeterminant (const bool report, labelHashSet * setPtr) const virtual
Definition at line 762 of file polyMeshCheck.C.
bool checkMeshMotion (const pointField & newPoints, const bool report = false, const bool detailedReport = false) const virtual
Check mesh motion for correctness given motion points.
Definition at line 808 of file polyMeshCheck.C.
References cellVols, Foam::endl(), and Foam::Pout.
bool checkFaceWeight (const bool report, const scalar minWeight = 0.05, labelHashSet * setPtr = NULL) const virtual
Check for face weights.
Definition at line 778 of file polyMeshCheck.C.
bool checkVolRatio (const bool report, const scalar minRatio = 0.01, labelHashSet * setPtr = NULL) const virtual
Check for neighbouring cell volumes.
Definition at line 797 of file polyMeshCheck.C.
void findCellFacePt (const point & p, label & celli, label & tetFacei, label & tetPti) const
Find the cell, tetFacei and tetPti for point p.
Definition at line 1261 of file polyMesh.C.
References Foam::abort(), treeDataCell::cellLabels(), Foam::FatalError, FatalErrorIn, indexedOctree< Type >::findIndices(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), indexedOctree< Type >::shapes(), and Foam::sqr().
Referenced by nearWallFields::calcAddressing().
void findTetFacePt (const label celli, const point & p, label & tetFacei, label & tetPti) const
Find the tetFacei and tetPti for point p in celli.
tetFaceI and tetPtI are set to -1 if not found
Definition at line 1341 of file polyMesh.C.
References tetIndices::face(), polyMeshTetDecomposition::findTet(), mesh, and tetIndices::tetPt().
Referenced by sampledSet::pushIn().
bool pointInCell (const point & p, label celli, const cellDecomposition decompMode = CELL_TETS) const
Test if point p is in the celli.
Definition at line 1357 of file polyMesh.C.
References cells, triangle< Point, PointRef >::centre(), f(), tetIndices::faceTri(), forAll, face::nextLabel(), triangle< Point, PointRef >::normal(), primitiveMesh::pointInCell(), points, List< T >::size(), and polyMeshTetDecomposition::triangleTetIndices().
Referenced by sampledSet::getTrackingPoint().
Foam::label findCell (const point & p, const cellDecomposition decompMode = CELL_TETS) const
Find cell enclosing this location and return index.
If not found -1 is returned
Definition at line 1476 of file polyMesh.C.
References UPstream::parRun().
Referenced by actuationDiskSource::actuationDiskSource(), refinementParameters::findCells(), probes::findElements(), meshRefinement::findRegion(), and sampledSet::getTrackingPoint().
Member Data Documentation
word defaultRegion = "region0" static
Return the default region name.
Definition at line 306 of file polyMesh.H.
Referenced by functionObjectFile::baseFileDir(), regIOobject::checkIn(), meshReader::mesh(), dynamicFvMesh::New(), probes::prepare(), sampledSets::sampledSets(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), thermalBaffleFvPatchScalarField::updateCoeffs(), thermalBaffleFvPatchScalarField::write(), streamLine::write(), and wallBoundedStreamLine::write().
word meshSubDir = "polyMesh" static
Return the mesh sub-directory name (usually "polyMesh")
Definition at line 309 of file polyMesh.H.
Referenced by componentDisplacementMotionSolver::componentDisplacementMotionSolver(), fvMesh::delta(), solidBodyMotionDisplacementPointPatchVectorField::localPoints0(), polyMesh::polyMesh(), and processorMeshes::reconstructPoints().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyMesh.H
src/OpenFOAM/meshes/polyMesh/polyMesh.C
src/OpenFOAM/meshes/polyMesh/polyMeshCheck/polyMeshCheck.C
src/OpenFOAM/meshes/polyMesh/polyMeshClear.C
src/OpenFOAM/meshes/polyMesh/polyMeshFromShapeMesh.C
src/OpenFOAM/meshes/polyMesh/polyMeshInitMesh.C
src/OpenFOAM/meshes/polyMesh/polyMeshIO.C
src/OpenFOAM/meshes/polyMesh/polyMeshUpdate.C