OpenFOAM: pointConstraints Class Reference
pointConstraints Class Reference
Application of (multi-)patch point contraints.
Public Member Functions
ClassName ("pointConstraints")
pointConstraints (const pointMesh &)
Constructor from pointMesh.
~pointConstraints ()
Destructor.
const labelList & patchPatchPointConstraintPoints () const
Mesh points on which to apply special constraints.
const tensorField & patchPatchPointConstraintTensors () const
Special constraints.
const List< pointConstraint > & patchPatchPointConstraints () const
Actual constraints.
void updateMesh (const mapPolyMesh &)
Update mesh topology using the morph engine.
bool movePoints ()
Correct weighting factors for moving mesh.
template<class Type >
void constrainCorners (GeometricField< Type, pointPatchField, pointMesh > &pf) const
Apply patch-patch constraints only.
template<class Type >
void constrain (GeometricField< Type, pointPatchField, pointMesh > &pf, const bool overrideValue=false) const
Apply boundary conditions (single-patch constraints) and.
void constrainDisplacement (pointVectorField &displacement, const bool overrideValue=false) const
Apply boundary conditions (single-patch constraints),.
template<>
void constrainCorners (GeometricField< scalar, pointPatchField, pointMesh > &pf) const
template<>
void constrainCorners (GeometricField< label, pointPatchField, pointMesh > &pf) const
Public Member Functions inherited from MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >
MeshObject (const pointMesh &mesh)
virtual ~MeshObject ()
const pointMesh & mesh () const
virtual bool writeData (Foam::Ostream &) const
Public Member Functions inherited from UpdateableMeshObject< pointMesh >
UpdateableMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from MoveableMeshObject< pointMesh >
MoveableMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from GeometricMeshObject< pointMesh >
GeometricMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from TopologicalMeshObject< pointMesh >
TopologicalMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from meshObject
ClassName ("meshObject")
meshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
template<class Type , class CombineOp >
static void syncUntransformedData (const polyMesh &mesh, List< Type > &pointData, const CombineOp &cop)
Helper: sync data on collocated points only.
template<class Type >
static void setPatchFields (GeometricField< Type, pointPatchField, pointMesh > &)
Helper: set patchField values from internal values (on.
Static Public Member Functions inherited from MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >
static const pointConstraints & New (const pointMesh &mesh)
static const pointConstraints & New (const pointMesh &mesh, const Data1 &d)
static const pointConstraints & New (const pointMesh &mesh, const Data1 &, const Data2 &)
static const pointConstraints & New (const pointMesh &mesh, const Data1 &, const Data2 &, const Data3 &)
static const pointConstraints & New (const pointMesh &mesh, const Data1 &, const Data2 &, const Data3 &, const Data4 &)
static bool Delete (const pointMesh &mesh)
Static Public Member Functions inherited from meshObject
template<class Mesh >
static void movePoints (objectRegistry &)
template<class Mesh >
static void updateMesh (objectRegistry &, const mapPolyMesh &)
template<class Mesh , template< class > class MeshObjectType>
static void clear (objectRegistry &)
template<class Mesh , template< class > class FromType, template< class > class ToType>
static void clearUpto (objectRegistry &)
Clear all meshObject derived from FromType up to (but not including)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes inherited from MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >
const pointMesh & mesh_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Application of (multi-)patch point contraints.
Note: includes all points which are on the boundary of a patch with a constraint. It includes them (even though the constraint will already be implemented through the patch evaluation) since these points might be coupled to points which are not on any constraint patch and we don't want to get inconsistency between the two points.
Source files
pointConstraints.H
pointConstraints.C
pointConstraintsTemplates.C
Definition at line 62 of file pointConstraints.H.
Constructor & Destructor Documentation
pointConstraints (const pointMesh & pm) explicit
Constructor from pointMesh.
Definition at line 326 of file pointConstraints.C.
References Foam::endl(), IOobject::name(), and Foam::Pout.
~pointConstraints ()
Destructor.
Definition at line 343 of file pointConstraints.C.
References Foam::endl(), and Foam::Pout.
Member Function Documentation
ClassName ("pointConstraints")
const labelList& patchPatchPointConstraintPoints () const inline
Mesh points on which to apply special constraints.
Definition at line 111 of file pointConstraints.H.
const tensorField& patchPatchPointConstraintTensors () const inline
Special constraints.
Definition at line 117 of file pointConstraints.H.
const List<pointConstraint>& patchPatchPointConstraints () const inline
Actual constraints.
Definition at line 123 of file pointConstraints.H.
References pointConstraints::constrain(), pointConstraints::constrainCorners(), pointConstraints::constrainDisplacement(), MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >::mesh(), pointConstraints::movePoints(), pointConstraints::setPatchFields(), pointConstraints::syncUntransformedData(), and pointConstraints::updateMesh().
void updateMesh (const mapPolyMesh &) virtual
Update mesh topology using the morph engine.
Implements UpdateableMeshObject< pointMesh >.
Definition at line 354 of file pointConstraints.C.
Referenced by pointConstraints::patchPatchPointConstraints().
bool movePoints () virtual
Correct weighting factors for moving mesh.
Implements MoveableMeshObject< pointMesh >.
Definition at line 360 of file pointConstraints.C.
References pointConstraints::constrainDisplacement().
Referenced by pointConstraints::patchPatchPointConstraints().
void syncUntransformedData (const polyMesh & mesh, List< Type > & pointData, const CombineOp & cop) static
Helper: sync data on collocated points only.
Definition at line 34 of file pointConstraintsTemplates.C.
References mapDistributeBase::constructSize(), globalMeshData::coupledPatch(), mapDistribute::distribute(), forAll, globalMeshData::globalCoPointSlaves(), globalMeshData::globalCoPointSlavesMap(), polyMesh::globalData(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), mapDistribute::reverseDistribute(), and pointConstraints::setPatchFields().
Referenced by pointConstraints::constrainDisplacement(), volPointInterpolation::interpolateBoundaryField(), and pointConstraints::patchPatchPointConstraints().
void setPatchFields (GeometricField< Type, pointPatchField, pointMesh > & pf) static
Helper: set patchField values from internal values (on.
valuePointPatchFields). Opposite of pointPatchField::setInInternalField
Definition at line 90 of file pointConstraintsTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), pointConstraints::constrainCorners(), forAll, Foam::isA(), patchi, and pointPatchField< Type >::patchInternalField().
Referenced by pointConstraints::constrainDisplacement(), pointConstraints::patchPatchPointConstraints(), and pointConstraints::syncUntransformedData().
void constrainCorners (GeometricField< Type, pointPatchField, pointMesh > & pf) const
Apply patch-patch constraints only.
Definition at line 112 of file pointConstraintsTemplates.C.
References pointConstraints::constrain(), forAll, and Foam::transform().
Referenced by pointConstraints::constrainDisplacement(), pointConstraints::patchPatchPointConstraints(), and pointConstraints::setPatchFields().
void constrain (GeometricField< Type, pointPatchField, pointMesh > & pf, const bool overrideValue = false) const
Apply boundary conditions (single-patch constraints) and.
patch-patch constraints on generic pointField. Optionally override valuePointPatchFields with constrained values (see setPatchFields above)
Definition at line 129 of file pointConstraintsTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), mesh, and GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef().
Referenced by pointConstraints::constrainCorners(), volPointInterpolation::interpolateBoundaryField(), pointConstraints::patchPatchPointConstraints(), rigidBodyMeshMotion::rigidBodyMeshMotion(), and sixDoFRigidBodyMotionSolver::sixDoFRigidBodyMotionSolver().
void constrainDisplacement (pointVectorField & displacement, const bool overrideValue = false) const
Apply boundary conditions (single-patch constraints),.
patch-patch constraints and two-D constraints on displacement field
Definition at line 367 of file pointConstraints.C.
References pointConstraints::constrainCorners(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), twoDPointCorrector::correctDisplacement(), MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >::mesh(), DimensionedField< Type, GeoMesh >::mesh(), MeshObject< polyMesh, UpdateableMeshObject, twoDPointCorrector >::New(), points, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), pointConstraints::setPatchFields(), and pointConstraints::syncUntransformedData().
Referenced by volPointInterpolation::interpolateDisplacement(), pointConstraints::movePoints(), pointConstraints::patchPatchPointConstraints(), and displacementLayeredMotionMotionSolver::solve().
void constrainCorners (GeometricField< scalar, pointPatchField, pointMesh > & pf) const
void constrainCorners (GeometricField< label, pointPatchField, pointMesh > & pf) const
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/volPointInterpolation/pointConstraints.H
src/finiteVolume/interpolation/volPointInterpolation/pointConstraints.C
src/finiteVolume/interpolation/volPointInterpolation/pointConstraintsTemplates.C