OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
processorPolyPatch Class Reference
Neighbour processor patch.
Public Member Functions
TypeName ("processor")
Runtime type information.
processorPolyPatch (const label size, const label start, const label index, const polyBoundaryMesh &bm, const int myProcNo, const int neighbProcNo, const transformType transform=UNKNOWN, const word &patchType=typeName)
Construct from components with automatically generated standard name.
processorPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &, const word &patchType)
Construct from dictionary.
processorPolyPatch (const processorPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
processorPolyPatch (const processorPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct as given the original patch and resetting the.
processorPolyPatch (const processorPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~processorPolyPatch ()
Destructor.
virtual bool coupled () const
Return true only if this is a parallel run.
int myProcNo () const
Return processor number.
int neighbProcNo () const
Return neigbour processor number.
virtual bool owner () const
Does the processor own the patch ?
bool neighbour () const
Is the processor the patch neighbour ?
const vectorField & neighbFaceCentres () const
Return processor-neighbbour patch face centres.
const vectorField & neighbFaceAreas () const
Return processor-neighbbour patch face areas.
const vectorField & neighbFaceCellCentres () const
Return processor-neighbbour patch neighbour cell centres.
const labelList & neighbPoints () const
Return neighbour point labels. WIP.
const labelList & neighbEdges () const
Return neighbour edge labels. WIP.
virtual int tag () const
Return message tag to use for communication.
virtual label comm () const
Return communicator used for communication.
virtual void transformPosition (pointField &l) const
Transform a patch-based position from other side to this side.
virtual void transformPosition (point &, const label facei) const
Transform a patch-based position from other side to this side.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reUse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Static Public Member Functions
static word newName (const label myProcNo, const label neighbProcNo)
Return the name of a processorPolyPatch.
static label matchFace (const face &localFace, const pointField &localPts, const face &masterFace, const pointField &masterPts, const bool sameOrientation, const scalar absTolSqr, scalar &matchDistSqr)
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Protected Member Functions
processorPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const int myProcNo, const int neighbProcNo, const transformType transform=UNKNOWN, const word &patchType=typeName)
Construct from components with specified name.
void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
Calculate the patch geometry with externally.
void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Attributes inherited from coupledPolyPatch
static const NamedEnum< transformType, 5 > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Detailed Description
Neighbour processor patch.
Note: morph patch face ordering tries to do a geometric ordering. (assumes faces coincident) Hence will have problems when cyclics are present.
Source files
processorPolyPatch.H
processorPolyPatch.C
Definition at line 55 of file processorPolyPatch.H.
Constructor & Destructor Documentation
processorPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const int myProcNo, const int neighbProcNo, const transformType transform = UNKNOWN, const word & patchType = typeName) protected
Construct from components with specified name.
Definition at line 51 of file processorPolyPatch.C.
Referenced by processorPolyPatch::calcGeometry(), processorPolyPatch::clone(), and processorPolyPatch::processorPolyPatch().
processorPolyPatch (const label size, const label start, const label index, const polyBoundaryMesh & bm, const int myProcNo, const int neighbProcNo, const transformType transform = UNKNOWN, const word & patchType = typeName)
Construct from components with automatically generated standard name.
Definition at line 73 of file processorPolyPatch.C.
References processorPolyPatch::processorPolyPatch().
processorPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 103 of file processorPolyPatch.C.
References processorPolyPatch::processorPolyPatch().
processorPolyPatch (const processorPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 121 of file processorPolyPatch.C.
References processorPolyPatch::processorPolyPatch().
processorPolyPatch (const processorPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct as given the original patch and resetting the.
face list and boundary mesh information
Definition at line 136 of file processorPolyPatch.C.
References processorPolyPatch::processorPolyPatch().
processorPolyPatch (const processorPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 154 of file processorPolyPatch.C.
~processorPolyPatch () virtual
Destructor.
Definition at line 173 of file processorPolyPatch.C.
References processorPolyPatch::newName().
Referenced by processorPolyPatch::clone().
Member Function Documentation
void initGeometry (PstreamBuffers & pBufs) protected virtual
Initialise the calculation of the patch geometry.
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 196 of file processorPolyPatch.C.
References UPstream::parRun().
Referenced by processorCyclicPolyPatch::initGeometry(), and processorPolyPatch::initMovePoints().
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Calculate the patch geometry.
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 210 of file processorPolyPatch.C.
References Foam::constant::physicoChemical::c1, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, processorPolyPatch::initMovePoints(), Foam::mag(), mesh, OFstream::name(), Foam::name(), UPstream::parRun(), path(), points, Foam::Pout, Foam::sqr(), Foam::transform(), and Foam::meshTools::writeOBJ().
Referenced by processorCyclicPolyPatch::calcGeometry(), and processorPolyPatch::movePoints().
virtual void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) inline protected virtual
Calculate the patch geometry with externally.
provided geometry
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 111 of file processorPolyPatch.H.
References dict, processorPolyPatch::initMovePoints(), processorPolyPatch::initUpdateMesh(), processorPolyPatch::movePoints(), NotImplemented, processorPolyPatch::processorPolyPatch(), coupledPolyPatch::transform(), processorPolyPatch::TypeName(), coupledPolyPatch::UNKNOWN, and processorPolyPatch::updateMesh().
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Initialise the patches for moving points.
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 327 of file processorPolyPatch.C.
References processorPolyPatch::initGeometry(), polyPatch::movePoints(), and processorPolyPatch::movePoints().
Referenced by processorPolyPatch::calcGeometry().
void movePoints (PstreamBuffers & pBufs, const pointField &) protected virtual
Correct patches after moving points.
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 338 of file processorPolyPatch.C.
References processorPolyPatch::calcGeometry().
Referenced by processorPolyPatch::calcGeometry(), and processorPolyPatch::initMovePoints().
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 347 of file processorPolyPatch.C.
References f(), Foam::findIndex(), polyPatch::initUpdateMesh(), nPoints, and UPstream::parRun().
Referenced by processorPolyPatch::calcGeometry(), and processorCyclicPolyPatch::initUpdateMesh().
void updateMesh (PstreamBuffers & pBufs) protected virtual
Update of the patch topology.
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 394 of file processorPolyPatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::clearOut(), f(), forAll, nPoints, UPstream::parRun(), List< T >::size(), and polyPatch::updateMesh().
Referenced by processorPolyPatch::calcGeometry(), and processorCyclicPolyPatch::updateMesh().
TypeName ("processor")
Runtime type information.
Referenced by processorPolyPatch::calcGeometry().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from polyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 193 of file processorPolyPatch.H.
References processorPolyPatch::processorPolyPatch().
Referenced by processorPolyPatch::clone().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from polyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 201 of file processorPolyPatch.H.
References processorPolyPatch::clone(), and processorPolyPatch::processorPolyPatch().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from polyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 224 of file processorPolyPatch.H.
References processorPolyPatch::processorPolyPatch(), and processorPolyPatch::~processorPolyPatch().
virtual bool coupled () const inline virtual
Return true only if this is a parallel run.
Reimplemented from coupledPolyPatch.
Definition at line 252 of file processorPolyPatch.H.
References UPstream::parRun().
int myProcNo () const inline
Return processor number.
Definition at line 265 of file processorPolyPatch.H.
Referenced by processorCyclicPolyPatch::calcGeometry(), processorFvPatch::myProcNo(), and processorPointPatch::myProcNo().
int neighbProcNo () const inline
Return neigbour processor number.
Definition at line 271 of file processorPolyPatch.H.
Referenced by processorCyclicPolyPatch::calcGeometry(), PointEdgeWave< Type, TrackingData >::countPatchType(), processorFvPatch::neighbProcNo(), processorPointPatch::neighbProcNo(), fvMeshDistribute::printCoupleInfo(), FaceCellWave< Type, TrackingData >::setFaceInfo(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), and syncTools::syncPointMap().
virtual bool owner () const inline virtual
Does the processor own the patch ?
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 277 of file processorPolyPatch.H.
Referenced by processorPolyPatch::neighbour(), and fvMeshDistribute::printCoupleInfo().
bool neighbour () const inline virtual
Is the processor the patch neighbour ?
Reimplemented from coupledPolyPatch.
Definition at line 283 of file processorPolyPatch.H.
References processorPolyPatch::newName(), and processorPolyPatch::owner().
Foam::word newName (const label myProcNo, const label neighbProcNo) static
Return the name of a processorPolyPatch.
constructed from the processor IDs
Definition at line 183 of file processorPolyPatch.C.
References Foam::name().
Referenced by processorPolyPatch::neighbour(), processorCyclicPolyPatch::newName(), and processorPolyPatch::~processorPolyPatch().
const vectorField& neighbFaceCentres () const inline
Return processor-neighbbour patch face centres.
Definition at line 297 of file processorPolyPatch.H.
const vectorField& neighbFaceAreas () const inline
Return processor-neighbbour patch face areas.
Definition at line 303 of file processorPolyPatch.H.
const vectorField& neighbFaceCellCentres () const inline
Return processor-neighbbour patch neighbour cell centres.
Definition at line 309 of file processorPolyPatch.H.
References processorPolyPatch::neighbEdges(), and processorPolyPatch::neighbPoints().
const Foam::labelList & neighbPoints () const
Return neighbour point labels. WIP.
Definition at line 506 of file processorPolyPatch.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::name().
Referenced by PointEdgeWave< Type, TrackingData >::countPatchType(), processorPolyPatch::neighbFaceCellCentres(), syncTools::syncEdgeMap(), and syncTools::syncPointMap().
const Foam::labelList & neighbEdges () const
Return neighbour edge labels. WIP.
Definition at line 518 of file processorPolyPatch.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, processorPolyPatch::initOrder(), and Foam::name().
Referenced by processorPolyPatch::neighbFaceCellCentres().
virtual int tag () const inline virtual
Return message tag to use for communication.
Reimplemented in processorCyclicPolyPatch.
Definition at line 321 of file processorPolyPatch.H.
References UPstream::msgType().
Referenced by processorPointPatch::tag().
virtual label comm () const inline virtual
Return communicator used for communication.
Definition at line 327 of file processorPolyPatch.H.
References polyPatch::boundaryMesh(), polyMesh::comm(), and polyBoundaryMesh::mesh().
Referenced by processorFvPatch::comm(), and processorPointPatch::comm().
virtual void transformPosition (pointField & l) const inline virtual
Transform a patch-based position from other side to this side.
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 333 of file processorPolyPatch.H.
virtual void transformPosition (point & , const label facei) const inline virtual
Transform a patch-based position from other side to this side.
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 337 of file processorPolyPatch.H.
References Foam::faceMap(), processorPolyPatch::initOrder(), processorPolyPatch::matchFace(), processorPolyPatch::order(), and processorPolyPatch::write().
void initOrder (PstreamBuffers & pBufs, const primitivePatch & pp) const virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 531 of file processorPolyPatch.C.
References Foam::endl(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceCentres(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), processorPolyPatch::matchFace(), mesh, OFstream::name(), Foam::name(), UPstream::parRun(), path(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::Pout, List< T >::size(), Foam::transform(), Foam::meshTools::writeOBJ(), and Vector< scalar >::zero.
Referenced by processorCyclicPolyPatch::initOrder(), processorPolyPatch::neighbEdges(), and processorPolyPatch::transformPosition().
Foam::label matchFace (const face & localFace, const pointField & localPts, const face & masterFace, const pointField & masterPts, const bool sameOrientation, const scalar absTolSqr, scalar & matchDistSqr) static
Definition at line 619 of file processorPolyPatch.C.
References CirculatorBase::ANTICLOCKWISE, ConstCirculator< ContainerType >::circulate(), CirculatorBase::CLOCKWISE, Foam::magSqr(), ConstCirculator< ContainerType >::nRotations(), processorPolyPatch::order(), ConstCirculator< ContainerType >::setFulcrumToIterator(), ConstCirculator< ContainerType >::setIteratorToFulcrum(), List< T >::size(), and Foam::sqr().
Referenced by processorPolyPatch::initOrder(), and processorPolyPatch::transformPosition().
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Implements coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 729 of file processorPolyPatch.C.
References Foam::abort(), Foam::constant::physicoChemical::c1, Foam::endl(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceCentres(), Foam::faceMap(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), Foam::FatalError, FatalErrorInFunction, forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::matchPoints(), mesh, OSstream::name(), OFstream::name(), fileName::name(), Foam::name(), Foam::nl, UPstream::parRun(), path(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::Pout, SeriousErrorInFunction, List< T >::setSize(), List< T >::size(), Foam::sqr(), Foam::transform(), Foam::meshTools::writeOBJ(), and Vector< scalar >::zero.
Referenced by processorPolyPatch::matchFace(), processorCyclicPolyPatch::order(), and processorPolyPatch::transformPosition().
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from coupledPolyPatch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 1116 of file processorPolyPatch.C.
References token::END_STATEMENT, Foam::nl, coupledPolyPatch::write(), and Ostream::writeKeyword().
Referenced by processorPolyPatch::transformPosition(), and processorCyclicPolyPatch::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/processor/processorPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/processor/processorPolyPatch.C