OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointLinear< Type > Class Template Reference
Face-point interpolation scheme class derived from linear and returns linear weighting factors but also applies an explicit correction.
Public Member Functions
TypeName ("pointLinear")
Runtime type information.
pointLinear (const fvMesh &mesh)
Construct from mesh.
pointLinear (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
pointLinear (const fvMesh &mesh, const surfaceScalarField &, Istream &)
Construct from mesh, faceFlux and Istream.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from linear< Type >
TypeName ("linear")
Runtime type information.
linear (const fvMesh &mesh)
Construct from mesh.
linear (const fvMesh &mesh, Istream &)
Construct from Istream.
linear (const fvMesh &mesh, const surfaceScalarField &, Istream &)
Construct from faceFlux and Istream.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
linear (const Specie &sp, const scalar psi, const scalar rho0)
Construct from components.
linear (Istream &)
Construct from Istream.
linear (const dictionary &dict)
Construct from dictionary.
linear (const word &name, const linear &)
Construct as named copy.
autoPtr< linear > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar h (const scalar p, const scalar T) const
Return enthalpy departure [J/kmol].
scalar cp (scalar p, scalar T) const
Return cp departure [J/(kmol K].
scalar s (const scalar p, const scalar T) const
Return entropy [J/(kmol K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const linear &)
void operator-= (const linear &)
void operator*= (const scalar)
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from linear< Type >
static autoPtr< linear > New (Istream &is)
static autoPtr< linear > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Static Public Attributes inherited from linear< Type >
static const bool incompressible = false
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::pointLinear< Type >
Face-point interpolation scheme class derived from linear and returns linear weighting factors but also applies an explicit correction.
Uses volPointInterpolation to obtain the field values at the face-points.
Source files
pointLinear.H
pointLinear.C
Definition at line 52 of file pointLinear.H.
Constructor & Destructor Documentation
pointLinear (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 74 of file pointLinear.H.
pointLinear (const fvMesh & mesh, Istream &) inline
Construct from mesh and Istream.
Definition at line 82 of file pointLinear.H.
pointLinear (const fvMesh & mesh, const surfaceScalarField & , Istream &) inline
Construct from mesh, faceFlux and Istream.
Definition at line 93 of file pointLinear.H.
Member Function Documentation
TypeName ("pointLinear< Type >")
Runtime type information.
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 106 of file pointLinear.H.
References pointLinear< Type >::correction().
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the explicit correction to the face-interpolate.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 37 of file pointLinear.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvsPatchField< Type >::coupled(), f(), fvPatch::faceCells(), polyMesh::faces(), forAll, Foam::MULES::interpolate(), Foam::linearInterpolate(), Foam::mag(), Foam::makeSurfaceInterpolationScheme(), mesh, fvMesh::neighbour(), Foam::New(), fvMesh::owner(), patchi, Foam::constant::mathematical::pi(), points, polyMesh::points(), tmp< T >::ref(), fvPatch::start(), surfaceInterpolation::weights(), and Foam::Zero.
Referenced by pointLinear< Type >::corrected().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/pointLinear/pointLinear.H
src/finiteVolume/interpolation/surfaceInterpolation/schemes/pointLinear/pointLinear.C