OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
prghTotalPressureFvPatchScalarField Class Reference
Boundary Conditions » Generic boundary Conditions
This boundary condition provides static pressure condition for p_rgh, calculated as:
Public Member Functions
TypeName ("prghTotalPressure")
Runtime type information.
prghTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
prghTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & p0 () const
Return the total pressure.
scalarField & p0 ()
Return reference to the total pressure to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Attributes
word UName_
Name of the velocity field.
word phiName_
Name of the flux transporting the field.
word rhoName_
Name of phase-fraction field.
scalarField p0_
Total pressure.
Detailed Description
This boundary condition provides static pressure condition for p_rgh, calculated as:
where
= Pseudo hydrostatic pressure [Pa]
= Static pressure [Pa]
= Total pressure [Pa]
= Height in the opposite direction to gravity
= Reference height in the opposite direction to gravity
= density
= acceleration due to gravity [m/s^2]
Patch usage
Property Description Required Default value
U velocity field name no U
phi flux field name no phi
rho density field name no rho
p0 total pressure yes
Example of the boundary condition specification:
    myPatch
    {
        type            prghTotalPressure;
        U               U;
        phi             phi;
        rho             rho;
        p0              uniform 0;
        value           uniform 0; // optional initial value
    }
See also
Foam::fixedValueFvPatchScalarField
Source files
prghTotalPressureFvPatchScalarField.H
prghTotalPressureFvPatchScalarField.C
Definition at line 147 of file prghTotalPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
prghTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file prghTotalPressureFvPatchScalarField.C.
Referenced by prghTotalPressureFvPatchScalarField::clone().
prghTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 52 of file prghTotalPressureFvPatchScalarField.C.
References dictionary::found(), scalarField(), and fvPatch::size().
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
prghTotalPressureFvPatchScalarField onto a new patch
Definition at line 80 of file prghTotalPressureFvPatchScalarField.C.
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 97 of file prghTotalPressureFvPatchScalarField.C.
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 111 of file prghTotalPressureFvPatchScalarField.C.
Member Function Documentation
TypeName ("prghTotalPressure")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 209 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 226 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField().
const scalarField& p0 () const inline
Return the total pressure.
Definition at line 242 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::p0_.
scalarField& p0 () inline
Return reference to the total pressure to allow adjustment.
Definition at line 248 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::p0_.
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 127 of file prghTotalPressureFvPatchScalarField.C.
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 137 of file prghTotalPressureFvPatchScalarField.C.
References prghTotalPressureFvPatchScalarField::p0_, and prghTotalPressureFvPatchScalarField::rmap().
Referenced by prghTotalPressureFvPatchScalarField::rmap().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 151 of file prghTotalPressureFvPatchScalarField.C.
References Foam::cmptMag(), Foam::dimLength, g, Foam::mag(), Foam::magSqr(), prghTotalPressureFvPatchScalarField::p0_, prghTotalPressureFvPatchScalarField::phiName_, Foam::pos(), prghTotalPressureFvPatchScalarField::rhoName_, and prghTotalPressureFvPatchScalarField::UName_.
void write (Ostream & os) const virtual
Write.
Definition at line 191 of file prghTotalPressureFvPatchScalarField.C.
References fvPatchField< Type >::write().
Member Data Documentation
word UName_ protected
Name of the velocity field.
Definition at line 157 of file prghTotalPressureFvPatchScalarField.H.
Referenced by prghTotalPressureFvPatchScalarField::updateCoeffs().
word phiName_ protected
Name of the flux transporting the field.
Definition at line 160 of file prghTotalPressureFvPatchScalarField.H.
Referenced by prghTotalPressureFvPatchScalarField::updateCoeffs().
word rhoName_ protected
Name of phase-fraction field.
Definition at line 163 of file prghTotalPressureFvPatchScalarField.H.
Referenced by prghTotalPressureFvPatchScalarField::updateCoeffs().
scalarField p0_ protected
Total pressure.
Definition at line 166 of file prghTotalPressureFvPatchScalarField.H.
Referenced by prghTotalPressureFvPatchScalarField::p0(), prghTotalPressureFvPatchScalarField::rmap(), and prghTotalPressureFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/prghTotalPressure/prghTotalPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/prghTotalPressure/prghTotalPressureFvPatchScalarField.C