OpenFOAM-dev: pointPatchField< Type > Class Template Reference 2
pointPatchField< Type > Class Template Reference abstract
Abstract base class for point-mesh patch fields.
Public Types
typedef pointPatch Patch
typedef calculatedPointPatchField< Type > Calculated
Public Member Functions
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
virtual autoPtr< pointPatchField< Type > > clone () const =0
Construct and return a clone.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const =0
Construct and return a clone setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type, pointMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Static Public Member Functions
static autoPtr< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new calculatedPointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Attributes
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Friends
Ostream & operator (Ostream &, const pointPatchField< Type > &)
Detailed Description
template<class Type>
class Foam::pointPatchField< Type >
Abstract base class for point-mesh patch fields.
The base-field does not store values as they are part of the "internal field". There are derived classes to store constraint values e.g. fixedValuePointPatchField derived from the generic valuePointPatchField which ensures the values in the "internal field" are reset to the fixed-values by applying the stored values.
Source files
pointPatchField.H
pointPatchField.C
newPointPatchField.C
Definition at line 58 of file pointMVCWeight.H.
Member Typedef Documentation
typedef pointPatch Patch
Definition at line 103 of file pointPatchField.H.
typedef calculatedPointPatchField<Type> Calculated
Definition at line 104 of file pointPatchField.H.
Constructor & Destructor Documentation
pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 34 of file pointPatchField.C.
Referenced by pointPatchField< Type >::pointPatchField().
pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 48 of file pointPatchField.C.
References pointPatchField< Type >::pointPatchField().
pointPatchField (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
Definition at line 63 of file pointPatchField.C.
References pointPatchField< Type >::pointPatchField().
pointPatchField (const pointPatchField< Type > & ptf)
Construct as copy.
Definition at line 79 of file pointPatchField.C.
References pointPatchField< Type >::pointPatchField().
pointPatchField (const pointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 92 of file pointPatchField.C.
virtual ~pointPatchField () inline virtual
Destructor.
Definition at line 256 of file pointPatchField.H.
Member Function Documentation
TypeName ("pointPatchField< Type >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , pointPatch , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF) , (p, iF))
declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , patchMapper , (const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m) , (dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , dictionary , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict) , (p, iF, dict))
virtual autoPtr<pointPatchField<Type> > clone () const pure virtual
Construct and return a clone.
Implemented in codedFixedValuePointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, zeroFixedValuePointPatchField< Type >, genericPointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, processorCyclicPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, valuePointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, valuePointPatchField< vector >, waveDisplacementPointPatchVectorField, processorPointPatchField< Type >, oscillatingDisplacementPointPatchVectorField, coupledPointPatchField< Type >, fixedValuePointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, wedgePointPatchField< Type >, fixedValuePointPatchField< vector >, calculatedPointPatchField< Type >, zeroGradientPointPatchField< Type >, slipPointPatchField< Type >, and basicSymmetryPointPatchField< Type >.
virtual autoPtr<pointPatchField<Type> > clone (const DimensionedField< Type, pointMesh > & iF) const pure virtual
Construct and return a clone setting internal field reference.
Implemented in codedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, zeroFixedValuePointPatchField< Type >, genericPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, processorCyclicPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, valuePointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, valuePointPatchField< vector >, waveDisplacementPointPatchVectorField, processorPointPatchField< Type >, oscillatingDisplacementPointPatchVectorField, calculatedPointPatchField< Type >, fixedValuePointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, wedgePointPatchField< Type >, fixedValuePointPatchField< vector >, zeroGradientPointPatchField< Type >, slipPointPatchField< Type >, basicSymmetryPointPatchField< Type >, and coupledPointPatchField< Type >.
Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values)
Definition at line 97 of file pointPatchFieldNew.C.
References Foam::New().
Referenced by pointPatchField< Type >::New().
Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const word & actualPatchType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values). Allows override of constraint type
Definition at line 32 of file pointPatchFieldNew.C.
References pointPatch::constraintType(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, pointPatchField< Type >::New(), Foam::nl, and p.
Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & pfMapper) static
Return a pointer to a new patchField created on freestore from.
a given pointPatchField mapped onto a new patch
Definition at line 186 of file pointPatchFieldNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, Foam::nl, and p.
Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict) static
Return a pointer to a new patchField created on freestore.
from dictionary
Definition at line 109 of file pointPatchFieldNew.C.
References pointPatch::constraintType(), dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), InfoInFunction, dictionary::lookup(), pointPatchField< Type >::New(), Foam::nl, and p.
static autoPtr<pointPatchField<Type> > NewCalculatedType (const pointPatchField< Type2 > &) static
Return a pointer to a new calculatedPointPatchField created on.
freestore without setting patchField values
Referenced by calculatedPointPatchField< Type >::calculatedPointPatchField().
const Foam::objectRegistry & db () const
Return local objectRegistry.
Definition at line 107 of file pointPatchField.C.
Referenced by surfaceSlipDisplacementPointPatchVectorField::surfaces(), and pointPatchField< vector >::~pointPatchField().
label size () const inline
Return size.
Definition at line 268 of file pointPatchField.H.
Referenced by valuePointPatchField< Type >::valuePointPatchField().
const pointPatch& patch () const inline
Return patch.
Definition at line 274 of file pointPatchField.H.
Referenced by NamedEnum< Enum, nEnum >::names(), pointPatchField< Type >::NewCalculatedType(), and pointPatchField< vector >::size().
const DimensionedField<Type, pointMesh>& internalField () const inline
Return dimensioned internal field reference.
Definition at line 281 of file pointPatchField.H.
const Field<Type>& primitiveField () const inline
Return internal field reference.
Definition at line 287 of file pointPatchField.H.
Referenced by surfaceSlipDisplacementPointPatchVectorField::evaluate().
const word& patchType () const inline
Optional patch type.
Definition at line 293 of file pointPatchField.H.
word& patchType () inline
Optional patch type.
Definition at line 299 of file pointPatchField.H.
virtual bool fixesValue () const inline virtual
Return true if this patch field fixes a value.
Reimplemented in fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 305 of file pointPatchField.H.
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in processorCyclicPointPatchField< Type >, processorPointPatchField< Type >, and coupledPointPatchField< Type >.
Definition at line 311 of file pointPatchField.H.
bool updated () const inline
Return true if the boundary condition has already been updated.
Definition at line 317 of file pointPatchField.H.
Foam::tmp< Foam::Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
Definition at line 128 of file pointPatchField.C.
Referenced by surfaceSlipDisplacementPointPatchVectorField::evaluate(), pointPatchField< Type >::patchInternalField(), pointConstraints::setPatchFields(), and pointPatchField< vector >::updated().
tmp<Field<Type1> > patchInternalField (const Field< Type1 > & iF) const
Return field created from appropriate internal field values.
given internal field reference
tmp<Field<Type1> > patchInternalField (const Field< Type1 > & iF, const labelList & meshPoints) const
Return field created from selected internal field values.
given internal field reference
void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Given the internal field and a patch field,.
add the patch field to the internal field
Definition at line 172 of file pointPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::constant::atomic::mp, and List< Type >::size().
Referenced by pointPatchField< Type >::patchInternalField(), and pointPatchField< vector >::updated().
void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelList & points) const
Given the internal field and a patch field,.
add selected elements of the patch field to the internal field
Definition at line 209 of file pointPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::constant::atomic::mp, pointPatchField< Type >::setInInternalField(), and List< Type >::size().
void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelList & meshPoints) const
Given the internal field and a patch field,.
set the patch field in the internal field
Definition at line 248 of file pointPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, List< T >::size(), and List< Type >::size().
Referenced by pointPatchField< Type >::addToInternalField(), surfaceSlipDisplacementPointPatchVectorField::evaluate(), and pointPatchField< vector >::updated().
void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Given the internal field and a patch field,.
set the patch field in the internal field
Definition at line 283 of file pointPatchField.C.
const Foam::word & calculatedType () static
Return the type of the calculated form of pointPatchField.
Definition at line 31 of file calculatedPointPatchField.C.
References calculatedPointPatchField< Type >::calculatedPointPatchField().
Referenced by pointPatchField< vector >::updated().
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatchField implements.
Reimplemented in cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, processorPointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, emptyPointPatchField< Type >, wedgePointPatchField< Type >, and symmetryPointPatchField< Type >.
Definition at line 384 of file pointPatchField.H.
virtual void autoMap (const pointPatchFieldMapper &) inline virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, genericPointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, and oscillatingVelocityPointPatchVectorField.
Definition at line 394 of file pointPatchField.H.
Referenced by pointPatchField< vector >::constraintType().
virtual void rmap (const pointPatchField< Type > & , const labelList &) inline virtual
Reverse map the given pointPatchField onto this pointPatchField.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, genericPointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, and oscillatingVelocityPointPatchVectorField.
Definition at line 401 of file pointPatchField.H.
Referenced by pointPatchField< vector >::autoMap().
virtual void updateCoeffs () inline virtual
Update the coefficients associated with the patch field.
Sets Updated to true
Reimplemented in codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformInterpolatedDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, timeVaryingUniformFixedValuePointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 412 of file pointPatchField.H.
Referenced by pointPatchField< vector >::rmap().
virtual void initEvaluate (const Pstream::commsTypes commsType = Pstream::blocking) inline virtual
Initialise evaluation of the patch field (do nothing)
Definition at line 419 of file pointPatchField.H.
Referenced by pointPatchField< vector >::rmap().
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Evaluate the patch field.
Reimplemented in codedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, processorPointPatchField< Type >, processorCyclicPointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, cyclicPointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, symmetryPlanePointPatchField< Type >, wedgePointPatchField< Type >, cyclicSlipPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, basicSymmetryPointPatchField< Type >, and coupledPointPatchField< Type >.
Definition at line 293 of file pointPatchField.C.
References pointPatchField< Type >::write().
Referenced by pointPatchField< vector >::initEvaluate().
void write (Ostream & os) const virtual
Write.
Reimplemented in codedFixedValuePointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformInterpolatedDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, uniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, genericPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, fixedNormalSlipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 114 of file pointPatchField.C.
References Foam::nl, Foam::type(), and Ostream::writeKeyword().
Referenced by pointPatchField< Type >::evaluate(), pointPatchField< vector >::initEvaluate(), oscillatingDisplacementPointPatchVectorField::write(), waveDisplacementPointPatchVectorField::write(), oscillatingVelocityPointPatchVectorField::write(), angularOscillatingVelocityPointPatchVectorField::write(), angularOscillatingDisplacementPointPatchVectorField::write(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write(), uniformInterpolatedDisplacementPointPatchVectorField::write(), and sixDoFRigidBodyDisplacementPointPatchVectorField::write().
virtual void operator= (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 437 of file pointPatchField.H.
virtual void operator+= (const pointPatchField< Type > &) inline virtual
Definition at line 438 of file pointPatchField.H.
virtual void operator-= (const pointPatchField< Type > &) inline virtual
Definition at line 439 of file pointPatchField.H.
virtual void operator*= (const pointPatchField< scalar > &) inline virtual
Definition at line 440 of file pointPatchField.H.
virtual void operator/= (const pointPatchField< scalar > &) inline virtual
Definition at line 441 of file pointPatchField.H.
virtual void operator= (const Field< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, valuePointPatchField< vector >, fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 443 of file pointPatchField.H.
virtual void operator+= (const Field< Type > &) inline virtual
Definition at line 444 of file pointPatchField.H.
virtual void operator-= (const Field< Type > &) inline virtual
Definition at line 445 of file pointPatchField.H.
virtual void operator*= (const Field< scalar > &) inline virtual
Definition at line 447 of file pointPatchField.H.
virtual void operator/= (const Field< scalar > &) inline virtual
Definition at line 448 of file pointPatchField.H.
virtual void operator= (const Type &) inline virtual
Reimplemented in valuePointPatchField< Type >, valuePointPatchField< vector >, fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 450 of file pointPatchField.H.
virtual void operator+= (const Type &) inline virtual
Definition at line 451 of file pointPatchField.H.
virtual void operator-= (const Type &) inline virtual
Definition at line 452 of file pointPatchField.H.
virtual void operator*= (const scalar) inline virtual
Definition at line 453 of file pointPatchField.H.
virtual void operator/= (const scalar) inline virtual
Definition at line 454 of file pointPatchField.H.
virtual void operator== (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 461 of file pointPatchField.H.
virtual void operator== (const Field< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 462 of file pointPatchField.H.
virtual void operator== (const Type &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 463 of file pointPatchField.H.
Foam::autoPtr<Foam::pointPatchField<Type> > NewCalculatedType (const pointPatchField< Type2 > & pf)
Definition at line 90 of file calculatedPointPatchField.C.
References pointPatchField< Type >::patch().
Foam::tmp<Foam::Field<Type1> > patchInternalField (const Field< Type1 > & iF, const labelList & meshPoints) const
Definition at line 138 of file pointPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, pointPatchField< Type >::patchInternalField(), and List< Type >::size().
Foam::tmp<Foam::Field<Type1> > patchInternalField (const Field< Type1 > & iF) const
Definition at line 161 of file pointPatchField.C.
References pointPatchField< Type >::addToInternalField().
Friends And Related Function Documentation
Ostream& operator (Ostream & , const pointPatchField< Type > &) friend
Member Data Documentation
int disallowGenericPointPatchField static
Debug switch to disallow the use of genericPointPatchField.
Definition at line 111 of file pointPatchField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeight.H
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.H
src/OpenFOAM/fields/pointPatchFields/basic/calculated/calculatedPointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFieldNew.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFields.C