OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointToFace Class Reference
A topoSetSource to select faces based on use of points.
Public Types
enum pointAction { ANY, ALL, EDGE }
Enumeration defining the valid options.
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Public Member Functions
TypeName ("pointToFace")
Runtime type information.
pointToFace (const polyMesh &mesh, const word &setName, const pointAction option)
Construct from components.
pointToFace (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
pointToFace (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~pointToFace ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label celli, const bool) const
Add (if bool) celli to set or delete celli from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = NULL
A table of usage strings.
Detailed Description
A topoSetSource to select faces based on use of points.
Source files
pointToFace.H
pointToFace.C
Definition at line 49 of file pointToFace.H.
Member Enumeration Documentation
enum pointAction
Enumeration defining the valid options.
Enumerator
ANY
ALL
EDGE
Definition at line 57 of file pointToFace.H.
Constructor & Destructor Documentation
pointToFace (const polyMesh & mesh, const word & setName, const pointAction option)
Construct from components.
Definition at line 155 of file pointToFace.C.
Referenced by NamedEnum< Enum, nEnum >::names(), and pointToFace::pointToFace().
pointToFace (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 169 of file pointToFace.C.
References pointToFace::pointToFace().
pointToFace (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 182 of file pointToFace.C.
~pointToFace () virtual
Destructor.
Definition at line 195 of file pointToFace.C.
References pointToFace::applyToSet().
Member Function Documentation
TypeName ("pointToFace")
Runtime type information.
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 121 of file pointToFace.H.
References pointToFace::applyToSet(), and topoSetSource::FACESETSOURCE.
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 202 of file pointToFace.C.
References topoSetSource::ADD, Foam::ListListOps::combine(), topoSetSource::DELETE, Foam::endl(), Foam::Info, and topoSetSource::NEW.
Referenced by pointToFace::setType(), and pointToFace::~pointToFace().
The documentation for this class was generated from the following files:
src/meshTools/sets/faceSources/pointToFace/pointToFace.H
src/meshTools/sets/faceSources/pointToFace/pointToFace.C