OpenFOAM-dev: prefixOSstream Class Reference 2
prefixOSstream Class Reference
Version of OSstream which prints a prefix on each line.
Public Member Functions
prefixOSstream (ostream &os, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
const string & prefix () const
Return the prefix of the stream.
string & prefix ()
Return non-const access to the prefix of the stream.
virtual Ostream & write (const token &)
Write next token to stream.
virtual Ostream & write (const char)
Write character.
virtual Ostream & write (const char *)
Write character string.
virtual Ostream & write (const word &)
Write word.
virtual Ostream & write (const string &)
Write string.
virtual Ostream & writeQuoted (const std::string &, const bool quoted=true)
Write std::string surrounded by quotes.
virtual Ostream & write (const int32_t)
Write int32_t.
virtual Ostream & write (const int64_t)
Write int64_t.
virtual Ostream & write (const floatScalar)
Write floatScalar.
virtual Ostream & write (const doubleScalar)
Write doubleScalar.
virtual Ostream & write (const char *, std::streamsize)
Write binary block.
virtual void indent ()
Add indentation characters.
virtual void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from OSstream
OSstream (ostream &os, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
virtual ios_base::fmtflags flags (const ios_base::fmtflags flags)
Set flags of output stream.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual int width () const
Get width of output field.
virtual int width (const int)
Set width of output field (and return old width)
virtual int precision () const
Get precision of output field.
virtual int precision (const int)
Set precision of output field (and return old precision)
virtual ostream & stdStream ()
Access to underlying std::ostream.
virtual const ostream & stdStream () const
Const access to underlying std::ostream.
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Ostream ()
Destructor.
virtual Ostream & write (const keyType &)
Write keyType.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Incrememt the indent level.
void decrIndent ()
Decrememt the indent level.
Ostream & writeKeyword (const keyType &)
Write the keyword followed by an appropriate indentation.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from Ostream
unsigned short indentLevel_
Current indent level.
Protected Attributes inherited from IOstream
label lineNumber_
Static Protected Attributes inherited from Ostream
static const unsigned short indentSize_ = 4
Number of spaces per indent level.
static const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Detailed Description
Version of OSstream which prints a prefix on each line.
This is useful for running in parallel as it allows the processor number to be automatically prepended to each message line.
Source files
prefixOSstream.H
prefixOSstream.C
Definition at line 51 of file prefixOSstream.H.
Constructor & Destructor Documentation
prefixOSstream (ostream & os, const string & name, streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED)
Set stream status.
Definition at line 45 of file prefixOSstream.C.
Member Function Documentation
const string& prefix () const inline
Return the prefix of the stream.
Definition at line 86 of file prefixOSstream.H.
Referenced by NamedEnum< Enum, nEnum >::names(), dynamicIndexedOctree< Type >::print(), and indexedOctree< Type >::print().
string& prefix () inline
Return non-const access to the prefix of the stream.
Definition at line 92 of file prefixOSstream.H.
References prefixOSstream::indent(), prefixOSstream::print(), prefixOSstream::write(), and prefixOSstream::writeQuoted().
Foam::Ostream & write (const token & t) virtual
Write next token to stream.
Reimplemented from OSstream.
Definition at line 68 of file prefixOSstream.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::HASH, token::stringToken(), token::type(), token::VARIABLE, token::VERBATIMSTRING, and prefixOSstream::writeQuoted().
Referenced by prefixOSstream::prefix(), and prefixOSstream::write().
Foam::Ostream & write (const char c) virtual
Write character.
Reimplemented from OSstream.
Definition at line 86 of file prefixOSstream.C.
References token::NL, and OSstream::write().
Foam::Ostream & write (const char * str) virtual
Write character string.
Reimplemented from OSstream.
Definition at line 100 of file prefixOSstream.C.
References token::NL, and OSstream::write().
Foam::Ostream & write (const word & val) virtual
Write word.
Reimplemented from OSstream.
Definition at line 115 of file prefixOSstream.C.
References OSstream::write().
Foam::Ostream & write (const string & val) virtual
Write string.
Reimplemented from OSstream.
Definition at line 122 of file prefixOSstream.C.
References OSstream::write(), and prefixOSstream::writeQuoted().
Foam::Ostream & writeQuoted (const std::string & val, const bool quoted = true) virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Reimplemented from OSstream.
Definition at line 130 of file prefixOSstream.C.
References OSstream::writeQuoted().
Referenced by prefixOSstream::prefix(), and prefixOSstream::write().
Foam::Ostream & write (const int32_t val) virtual
Write int32_t.
Reimplemented from OSstream.
Definition at line 140 of file prefixOSstream.C.
References OSstream::write().
Foam::Ostream & write (const int64_t val) virtual
Write int64_t.
Reimplemented from OSstream.
Definition at line 147 of file prefixOSstream.C.
References OSstream::write().
Foam::Ostream & write (const floatScalar val) virtual
Write floatScalar.
Reimplemented from OSstream.
Definition at line 154 of file prefixOSstream.C.
References OSstream::write().
Foam::Ostream & write (const doubleScalar val) virtual
Write doubleScalar.
Reimplemented from OSstream.
Definition at line 161 of file prefixOSstream.C.
References prefixOSstream::write(), and OSstream::write().
Foam::Ostream & write (const char * buf, std::streamsize count) virtual
Write binary block.
Reimplemented from OSstream.
Definition at line 169 of file prefixOSstream.C.
References OSstream::write().
void indent () virtual
Add indentation characters.
Reimplemented from OSstream.
Definition at line 179 of file prefixOSstream.C.
References OSstream::indent().
Referenced by prefixOSstream::prefix().
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from OSstream.
Definition at line 61 of file prefixOSstream.C.
References OSstream::print().
Referenced by prefixOSstream::prefix().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Sstreams/prefixOSstream.H
src/OpenFOAM/db/IOstreams/Sstreams/prefixOSstream.C