OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pointMesh Class Reference
Mesh representing a set of points created from polyMesh.
Public Types
typedef pointMesh Mesh
typedef pointBoundaryMesh BoundaryMesh
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from GeoMesh< polyMesh >
typedef polyMesh Mesh
typedef polyMesh::BoundaryMesh BoundaryMesh
Public Member Functions
ClassName ("pointMesh")
pointMesh (const polyMesh &pMesh)
Construct from polyMesh.
~pointMesh ()
Destructor.
label size () const
Return number of points.
const pointBoundaryMesh & boundary () const
Return reference to boundary mesh.
const globalMeshData & globalData () const
Return parallel info.
const objectRegistry & thisDb () const
Return database. For now is its polyMesh.
bool movePoints ()
Move points.
void updateMesh (const mapPolyMesh &mpm)
Update the mesh corresponding to given map.
bool operator!= (const pointMesh &pm) const
bool operator== (const pointMesh &pm) const
Public Member Functions inherited from MeshObject< polyMesh, UpdateableMeshObject, pointMesh >
MeshObject (const polyMesh &mesh)
virtual ~MeshObject ()
const polyMesh & mesh () const
virtual bool writeData (Foam::Ostream &) const
Public Member Functions inherited from UpdateableMeshObject< polyMesh >
UpdateableMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from MoveableMeshObject< polyMesh >
MoveableMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from GeometricMeshObject< polyMesh >
GeometricMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from TopologicalMeshObject< polyMesh >
TopologicalMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from meshObject
ClassName ("meshObject")
meshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from GeoMesh< polyMesh >
GeoMesh (const polyMesh &mesh)
Construct from MESH.
const objectRegistry & thisDb () const
Return the object registry.
const polyMesh & operator() () const
Return reference to polyMesh.
Static Public Member Functions
static label size (const Mesh &mesh)
Return number of points.
Static Public Member Functions inherited from MeshObject< polyMesh, UpdateableMeshObject, pointMesh >
static const pointMesh & New (const polyMesh &mesh)
static const pointMesh & New (const polyMesh &mesh, const Data1 &d)
static const pointMesh & New (const polyMesh &mesh, const Data1 &, const Data2 &)
static const pointMesh & New (const polyMesh &mesh, const Data1 &, const Data2 &, const Data3 &)
static const pointMesh & New (const polyMesh &mesh, const Data1 &, const Data2 &, const Data3 &, const Data4 &)
static bool Delete (const polyMesh &mesh)
Static Public Member Functions inherited from meshObject
template<class Mesh >
static void movePoints (objectRegistry &)
template<class Mesh >
static void updateMesh (objectRegistry &, const mapPolyMesh &)
template<class Mesh , template< class > class MeshObjectType>
static void clear (objectRegistry &)
template<class Mesh , template< class > class FromType, template< class > class ToType>
static void clearUpto (objectRegistry &)
Clear all meshObject derived from FromType up to (but not including)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Additional Inherited Members
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes inherited from MeshObject< polyMesh, UpdateableMeshObject, pointMesh >
const polyMesh & mesh_
Protected Attributes inherited from GeoMesh< polyMesh >
const polyMesh & mesh_
Reference to Mesh.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Mesh representing a set of points created from polyMesh.
Definition at line 48 of file pointMesh.H.
Member Typedef Documentation
typedef pointMesh Mesh
Definition at line 77 of file pointMesh.H.
typedef pointBoundaryMesh BoundaryMesh
Definition at line 78 of file pointMesh.H.
Constructor & Destructor Documentation
pointMesh (const polyMesh & pMesh) explicit
Construct from polyMesh.
Definition at line 73 of file pointMesh.C.
References Foam::endl(), IOobject::name(), and Foam::Pout.
~pointMesh ()
Destructor.
Definition at line 93 of file pointMesh.C.
References Foam::endl(), and Foam::Pout.
Member Function Documentation
ClassName ("pointMesh")
label size () const inline
Return number of points.
Definition at line 94 of file pointMesh.H.
Referenced by pointMapper::pointMapper(), and pointFieldReconstructor::reconstructField().
static label size (const Mesh & mesh) inline static
Return number of points.
Definition at line 100 of file pointMesh.H.
References GeoMesh< MESH >::GeoMesh(), GeoMesh< polyMesh >::mesh_, and primitiveMesh::nPoints().
const pointBoundaryMesh& boundary () const inline
Return reference to boundary mesh.
Definition at line 106 of file pointMesh.H.
Referenced by fvMeshSubset::interpolate(), meshRefinement::makeDisplacementField(), pointBoundaryMeshMapper::pointBoundaryMeshMapper(), pointFieldReconstructor::pointFieldReconstructor(), and pointFieldReconstructor::reconstructField().
const globalMeshData& globalData () const inline
Return parallel info.
Definition at line 112 of file pointMesh.H.
Referenced by pointBoundaryMesh::findIndices(), pointBoundaryMesh::movePoints(), and pointBoundaryMesh::updateMesh().
const objectRegistry& thisDb () const inline
Return database. For now is its polyMesh.
Definition at line 118 of file pointMesh.H.
References pointMesh::movePoints(), GeoMesh< MESH >::thisDb(), and pointMesh::updateMesh().
Referenced by fvMeshSubset::interpolate(), volPointInterpolation::interpolate(), and uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
bool movePoints () virtual
Move points.
Implements MoveableMeshObject< polyMesh >.
Definition at line 105 of file pointMesh.C.
References Foam::endl(), pointBoundaryMesh::movePoints(), points, and Foam::Pout.
Referenced by pointMesh::thisDb().
void updateMesh (const mapPolyMesh & mpm) virtual
Update the mesh corresponding to given map.
Implements UpdateableMeshObject< polyMesh >.
Definition at line 119 of file pointMesh.C.
References Foam::endl(), Foam::Pout, and pointBoundaryMesh::updateMesh().
Referenced by pointMesh::thisDb().
bool operator!= (const pointMesh & pm) const inline
Definition at line 135 of file pointMesh.H.
bool operator== (const pointMesh & pm) const inline
Definition at line 140 of file pointMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointMesh.H
src/OpenFOAM/meshes/pointMesh/pointMesh.C