OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polyModifyFace Class Reference
Class describing modification of a face.
Public Member Functions
TypeName ("modifyFace")
Runtime type information.
polyModifyFace ()
Construct null. Used in constructing lists.
polyModifyFace (const face &f, const label faceID, const label owner, const label neighbour, const bool flipFaceFlux, const label patchID, const bool removeFromZone, const label zoneID, const bool zoneFlip)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
const face & newFace () const
Return face.
label faceID () const
Return master face ID.
label owner () const
Return owner cell ID.
label neighbour () const
Return owner cell ID.
bool flipFaceFlux () const
Does the face flux need to be flipped.
bool isInPatch () const
Does the face belong to a boundary patch?
label patchID () const
Boundary patch ID.
bool isInZone () const
Does the face belong to a zone?
bool onlyInZone () const
Is the face only a zone face (i.e. not belonging to a cell)
bool removeFromZone () const
label zoneID () const
Face zone ID.
label zoneFlip () const
Face zone flip.
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()
Destructor.
Detailed Description
Class describing modification of a face.
Definition at line 48 of file polyModifyFace.H.
Constructor & Destructor Documentation
polyModifyFace () inline
Construct null. Used in constructing lists.
Definition at line 93 of file polyModifyFace.H.
Referenced by polyModifyFace::clone().
polyModifyFace (const face & f, const label faceID, const label owner, const label neighbour, const bool flipFaceFlux, const label patchID, const bool removeFromZone, const label zoneID, const bool zoneFlip) inline
Construct from components.
Definition at line 108 of file polyModifyFace.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::min(), and List< T >::size().
Member Function Documentation
TypeName ("modifyFace")
Runtime type information.
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 187 of file polyModifyFace.H.
References polyModifyFace::polyModifyFace().
const face& newFace () const inline
Return face.
Definition at line 198 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
label faceID () const inline
Return master face ID.
Definition at line 204 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
label owner () const inline
Return owner cell ID.
Definition at line 210 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
label neighbour () const inline
Return owner cell ID.
Definition at line 216 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
bool flipFaceFlux () const inline
Does the face flux need to be flipped.
Definition at line 222 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
bool isInPatch () const inline
Does the face belong to a boundary patch?
Definition at line 228 of file polyModifyFace.H.
label patchID () const inline
Boundary patch ID.
Definition at line 234 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
bool isInZone () const inline
Does the face belong to a zone?
Definition at line 240 of file polyModifyFace.H.
bool onlyInZone () const inline
Is the face only a zone face (i.e. not belonging to a cell)
Definition at line 246 of file polyModifyFace.H.
bool removeFromZone () const inline
Definition at line 251 of file polyModifyFace.H.
label zoneID () const inline
Face zone ID.
Definition at line 257 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
label zoneFlip () const inline
Face zone flip.
Definition at line 263 of file polyModifyFace.H.
Referenced by polyTopoChange::setAction().
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/modifyObject/polyModifyFace.H