OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
polyMeshGeometry Class Reference
Updateable mesh geometry and checking routines.
Public Member Functions
ClassName ("polyMeshGeometry")
polyMeshGeometry (const polyMesh &)
Construct from mesh.
const polyMesh & mesh () const
const vectorField & faceAreas () const
const vectorField & faceCentres () const
const vectorField & cellCentres () const
const scalarField & cellVolumes () const
void correct ()
Take over properties from mesh.
void correct (const pointField &p, const labelList &changedFaces)
Recalculate on selected faces. Recalculates cell properties.
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFaceTets (const bool report, const scalar minTetQuality, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkVolRatio (const bool report, const scalar warnRatio, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkTriangleTwist (const bool report, const scalar minTwist, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceFlatness (const bool report, const scalar minFlatness, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceArea (const bool report, const scalar minArea, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr) const
Static Public Member Functions
static labelList affectedCells (const polyMesh &, const labelList &changedFaces)
Helper function: get affected cells from faces.
static bool checkFaceDotProduct (const bool report, const scalar orthWarn, const polyMesh &, const vectorField &cellCentres, const vectorField &faceAreas, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
See primitiveMesh.
static bool checkFacePyramids (const bool report, const scalar minPyrVol, const polyMesh &, const vectorField &cellCentres, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *)
See primitiveMesh.
static bool checkFaceTets (const bool report, const scalar minPyrVol, const polyMesh &, const vectorField &cellCentres, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *)
See primitiveMesh.
static bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const polyMesh &mesh, const pointField &points, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
See primitiveMesh.
static bool checkFaceWeights (const bool report, const scalar warnWeight, const polyMesh &mesh, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
Interpolation weights (0.5 for regular mesh)
static bool checkVolRatio (const bool report, const scalar warnRatio, const polyMesh &mesh, const scalarField &cellVolumes, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
Cell volume ratio of neighbouring cells (1 for regular mesh)
static bool checkFaceAngles (const bool report, const scalar maxDeg, const polyMesh &mesh, const vectorField &faceAreas, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
See primitiveMesh.
static bool checkFaceTwist (const bool report, const scalar minTwist, const polyMesh &, const vectorField &cellCentres, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
Triangle (from face-centre decomposition) normal v.s.
static bool checkTriangleTwist (const bool report, const scalar minTwist, const polyMesh &, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
Consecutive triangle (from face-centre decomposition) normals.
static bool checkFaceFlatness (const bool report, const scalar minFlatness, const polyMesh &, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
Area of faces v.s. sum of triangle areas.
static bool checkFaceArea (const bool report, const scalar minArea, const polyMesh &, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
Small faces.
static bool checkCellDeterminant (const bool report, const scalar minDet, const polyMesh &, const vectorField &faceAreas, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr)
Area of internal faces v.s. boundary faces.
Detailed Description
Updateable mesh geometry and checking routines.
- non-ortho done across coupled faces.
faceWeight (delta factors) done across coupled faces.
Source files
polyMeshGeometry.H
polyMeshGeometry.C
Definition at line 52 of file polyMeshGeometry.H.
Constructor & Destructor Documentation
polyMeshGeometry (const polyMesh & mesh)
Construct from mesh.
Definition at line 342 of file polyMeshGeometry.C.
References polyMeshGeometry::correct().
Member Function Documentation
ClassName ("polyMeshGeometry")
const polyMesh& mesh () const inline
Definition at line 138 of file polyMeshGeometry.H.
Referenced by motionSmootherAlgo::checkMesh().
const vectorField& faceAreas () const inline
Definition at line 143 of file polyMeshGeometry.H.
const vectorField& faceCentres () const inline
Definition at line 147 of file polyMeshGeometry.H.
const vectorField& cellCentres () const inline
Definition at line 151 of file polyMeshGeometry.H.
const scalarField& cellVolumes () const inline
Definition at line 155 of file polyMeshGeometry.H.
void correct ()
Take over properties from mesh.
Definition at line 353 of file polyMeshGeometry.C.
Referenced by polyMeshGeometry::polyMeshGeometry().
void correct (const pointField & p, const labelList & changedFaces)
Recalculate on selected faces. Recalculates cell properties.
Recalculate on selected faces.
on owner and neighbour of these cells.
Definition at line 364 of file polyMeshGeometry.C.
Foam::labelList affectedCells (const polyMesh & mesh, const labelList & changedFaces) static
Helper function: get affected cells from faces.
Definition at line 194 of file polyMeshGeometry.C.
References polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, primitiveMesh::isInternalFace(), and List< T >::size().
Referenced by motionSmootherAlgo::checkMesh().
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceAreas, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 377 of file polyMeshGeometry.C.
References Foam::acos(), polyMesh::boundaryMesh(), Foam::cos(), Foam::degToRad(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), UList< T >::first(), forAll, Foam::Info, primitiveMesh::isInternalFace(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patches, Foam::radToDeg(), Foam::reduce(), SeriousErrorInFunction, syncTools::swapBoundaryFacePositions(), and polyBoundaryMesh::whichPatch().
Referenced by motionSmootherAlgo::checkMesh().
bool checkFacePyramids (const bool report, const scalar minPyrVol, const polyMesh & mesh, const vectorField & cellCentres, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 559 of file polyMeshGeometry.C.
References primitiveMesh::cells(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), UList< T >::first(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), Foam::Pout, Foam::reduce(), and SeriousErrorInFunction.
Referenced by motionSmootherAlgo::checkMesh().
bool checkFaceTets (const bool report, const scalar minPyrVol, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 740 of file polyMeshGeometry.C.
References polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMeshTetDecomposition::findBasePoint(), polyMeshTetDecomposition::findSharedBasePoint(), UList< T >::first(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patches, Foam::reduce(), SeriousErrorInFunction, syncTools::swapBoundaryFacePositions(), and polyBoundaryMesh::whichPatch().
Referenced by motionSmootherAlgo::checkMesh().
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const polyMesh & mesh, const pointField & points, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 969 of file polyMeshGeometry.C.
References primitiveMeshTools::boundaryFaceSkewness(), polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), primitiveMeshTools::faceSkewness(), UList< T >::first(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), Foam::max(), primitiveMesh::nInternalFaces(), Foam::nl, patches, Foam::Pout, Foam::reduce(), syncTools::swapBoundaryCellPositions(), WarningInFunction, and polyBoundaryMesh::whichPatch().
bool checkFaceWeights (const bool report, const scalar warnWeight, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Interpolation weights (0.5 for regular mesh)
Definition at line 1182 of file polyMeshGeometry.C.
References polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), UList< T >::first(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), Foam::mag(), Foam::min(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, patches, Foam::Pout, Foam::reduce(), syncTools::swapBoundaryFacePositions(), WarningInFunction, and polyBoundaryMesh::whichPatch().
Referenced by motionSmootherAlgo::checkMesh().
bool checkVolRatio (const bool report, const scalar warnRatio, const polyMesh & mesh, const scalarField & cellVolumes, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Cell volume ratio of neighbouring cells (1 for regular mesh)
Definition at line 1337 of file polyMeshGeometry.C.
References polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), UList< T >::first(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), Foam::mag(), Foam::max(), Foam::min(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, patches, Foam::Pout, Foam::reduce(), syncTools::swapBoundaryFaceList(), WarningInFunction, and polyBoundaryMesh::whichPatch().
Referenced by motionSmootherAlgo::checkMesh().
bool checkFaceAngles (const bool report, const scalar maxDeg, const polyMesh & mesh, const vectorField & faceAreas, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 1479 of file polyMeshGeometry.C.
References Foam::abort(), Foam::asin(), Foam::degToRad(), Foam::endl(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), UList< T >::first(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), UList< T >::last(), Foam::mag(), Foam::max(), Foam::min(), Foam::radToDeg(), Foam::reduce(), Foam::sin(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
bool checkFaceTwist (const bool report, const scalar minTwist, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Triangle (from face-centre decomposition) normal v.s.
average face normal
Definition at line 1612 of file polyMeshGeometry.C.
References Foam::abort(), polyMesh::boundaryMesh(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), Foam::mag(), face::nextLabel(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, patches, Foam::reduce(), List< T >::size(), syncTools::swapBoundaryFacePositions(), WarningInFunction, polyBoundaryMesh::whichPatch(), and Vector< scalar >::zero.
Referenced by motionSmootherAlgo::checkMesh().
bool checkTriangleTwist (const bool report, const scalar minTwist, const polyMesh & mesh, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Consecutive triangle (from face-centre decomposition) normals.
Definition at line 1797 of file polyMeshGeometry.C.
References Foam::abort(), Foam::endl(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), face::nextLabel(), Foam::nl, Foam::reduce(), List< T >::size(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
bool checkFaceFlatness (const bool report, const scalar minFlatness, const polyMesh & mesh, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Area of faces v.s. sum of triangle areas.
Definition at line 1947 of file polyMeshGeometry.C.
References Foam::abort(), Foam::endl(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), face::nextLabel(), Foam::nl, Foam::reduce(), List< T >::size(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
bool checkFaceArea (const bool report, const scalar minArea, const polyMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Small faces.
Definition at line 2045 of file polyMeshGeometry.C.
References Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::nl, Foam::reduce(), and WarningInFunction.
Referenced by motionSmootherAlgo::checkMesh().
bool checkCellDeterminant (const bool report, const scalar minDet, const polyMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) static
Area of internal faces v.s. boundary faces.
Definition at line 2106 of file polyMeshGeometry.C.
References cells, primitiveMesh::cells(), Foam::det(), Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::min(), Foam::nl, Foam::reduce(), WarningInFunction, and Tensor< scalar >::zero.
Referenced by motionSmootherAlgo::checkMesh().
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2207 of file polyMeshGeometry.C.
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2230 of file polyMeshGeometry.C.
bool checkFaceTets (const bool report, const scalar minTetQuality, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2254 of file polyMeshGeometry.C.
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2305 of file polyMeshGeometry.C.
bool checkVolRatio (const bool report, const scalar warnRatio, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2329 of file polyMeshGeometry.C.
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2351 of file polyMeshGeometry.C.
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2373 of file polyMeshGeometry.C.
bool checkTriangleTwist (const bool report, const scalar minTwist, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2397 of file polyMeshGeometry.C.
bool checkFaceFlatness (const bool report, const scalar minFlatness, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2420 of file polyMeshGeometry.C.
bool checkFaceArea (const bool report, const scalar minArea, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2443 of file polyMeshGeometry.C.
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) const
Definition at line 2463 of file polyMeshGeometry.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSmoother/polyMeshGeometry/polyMeshGeometry.H
src/dynamicMesh/motionSmoother/polyMeshGeometry/polyMeshGeometry.C