OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Reaction< ReactionThermo > Class Template Reference
Simple extension of ReactionThermo to handle reaction kinetics in addition to the equilibrium thermodynamics already handled.
Classes
class iNew
Class used for the read-construction of PtrLists of reaction.
struct specieCoeffs
Class to hold the specie index and its coefficients in the.
Public Member Functions
TypeName ("Reaction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, Reaction, Istream,(const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is),(species, thermoDatabase, is))
declareRunTimeSelectionTable (autoPtr, Reaction, dictionary,(const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict),(species, thermoDatabase, dict))
Reaction (const speciesTable &species, const List< specieCoeffs > &lhs, const List< specieCoeffs > &rhs, const HashPtrTable< ReactionThermo > &thermoDatabase)
Construct from components.
Reaction (const Reaction< ReactionThermo > &, const speciesTable &species)
Construct as copy given new speciesTable.
Reaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Construct from Istream.
Reaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Construct from dictionary.
virtual autoPtr< Reaction< ReactionThermo > > clone () const
Construct and return a clone.
virtual autoPtr< Reaction< ReactionThermo > > clone (const speciesTable &species) const
Construct and return a clone with new speciesTable.
virtual ~Reaction ()
Destructor.
word & name ()
const word & name () const
const List< specieCoeffs > & lhs () const
const List< specieCoeffs > & rhs () const
virtual const List< specieCoeffs > & grhs () const
virtual const List< specieCoeffs > & glhs () const
const speciesTable & species () const
virtual const speciesTable & gasSpecies () const
void setLRhs (Istream &, const speciesTable &, List< specieCoeffs > &lhs, List< specieCoeffs > &rhs)
Construct the left- and right-hand-side reaction coefficients.
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
Forward rate constant.
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant from the given forward rate constant.
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant.
virtual void write (Ostream &) const
Write.
Static Public Member Functions
static autoPtr< Reaction< ReactionThermo > > New (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Return a pointer to new patchField created on freestore from input.
static autoPtr< Reaction< ReactionThermo > > New (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Return a pointer to new patchField created on freestore from dict.
Static Public Attributes
static label nUnNamedReactions = 0
Number of un-named reactions.
Protected Member Functions
void reactionStrLeft (OStringStream &reaction) const
Return string representation of the left of the reaction.
void reactionStrRight (OStringStream &reaction) const
Return string representation of the right of the reaction.
Friends
Ostream & operator (Ostream &, const Reaction< ReactionThermo > &)
Detailed Description
template<class ReactionThermo>
class Foam::Reaction< ReactionThermo >
Simple extension of ReactionThermo to handle reaction kinetics in addition to the equilibrium thermodynamics already handled.
Source files
Reaction.H
ReactionI.H
Reaction.C
Definition at line 53 of file Reaction.H.
Constructor & Destructor Documentation
Reaction (const speciesTable & species, const List< specieCoeffs > & lhs, const List< specieCoeffs > & rhs, const HashPtrTable< ReactionThermo > & thermoDatabase)
Construct from components.
Definition at line 145 of file Reaction.C.
Reaction (const Reaction< ReactionThermo > & r, const speciesTable & species)
Construct as copy given new speciesTable.
Definition at line 164 of file Reaction.C.
Reaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, Istream & is)
Construct from Istream.
Definition at line 317 of file Reaction.C.
Reaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict)
Construct from dictionary.
Definition at line 334 of file Reaction.C.
References dictionary::lookup().
virtual ~Reaction () inline virtual
Destructor.
Definition at line 295 of file Reaction.H.
Member Function Documentation
void reactionStrLeft (OStringStream & reaction) const protected
Return string representation of the left of the reaction.
Definition at line 38 of file Reaction.C.
References Foam::mag().
void reactionStrRight (OStringStream & reaction) const protected
Return string representation of the right of the reaction.
Definition at line 63 of file Reaction.C.
References Foam::mag().
TypeName ("Reaction< ReactionThermo >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , Reaction< ReactionThermo > , Istream , (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is) , (species, thermoDatabase, is))
declareRunTimeSelectionTable (autoPtr , Reaction< ReactionThermo > , dictionary , (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict) , (species, thermoDatabase, dict))
virtual autoPtr<Reaction<ReactionThermo> > clone () const inline virtual
Construct and return a clone.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 254 of file Reaction.H.
virtual autoPtr<Reaction<ReactionThermo> > clone (const speciesTable & species) const inline virtual
Construct and return a clone with new speciesTable.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 264 of file Reaction.H.
References Reaction< ReactionThermo >::species().
Foam::autoPtr< Foam::Reaction< ReactionThermo > > New (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, Istream & is) static
Return a pointer to new patchField created on freestore from input.
Definition at line 360 of file Reaction.C.
References IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, and Foam::nl.
Referenced by Reaction< ReactionThermo >::iNew::operator()().
Foam::autoPtr< Foam::Reaction< ReactionThermo > > New (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict) static
Return a pointer to new patchField created on freestore from dict.
Definition at line 408 of file Reaction.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorIn, dictionary::lookup(), and Foam::nl.
word & name () inline
Definition at line 36 of file ReactionI.H.
Referenced by ReactionList< ThermoType >::write().
const word & name () const inline
Definition at line 43 of file ReactionI.H.
const List< typename Reaction< ReactionThermo >::specieCoeffs > & lhs () const inline
Definition at line 51 of file ReactionI.H.
Referenced by singleStepReactingMixture< ThermoType >::calculateqFuel(), singleStepReactingMixture< ThermoType >::fresCorrect(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), chemistryModel< CompType, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), chemistryModel< CompType, ThermoType >::omega(), and EulerImplicit< ChemistryModel >::updateRRInReactionI().
const List< typename Reaction< ReactionThermo >::specieCoeffs > & rhs () const inline
Definition at line 59 of file ReactionI.H.
Referenced by singleStepReactingMixture< ThermoType >::calculateMaxProducts(), singleStepReactingMixture< ThermoType >::calculateqFuel(), singleStepReactingMixture< ThermoType >::fresCorrect(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), chemistryModel< CompType, ThermoType >::jacobian(), mixtureFractionSoot< ThermoType >::mixtureFractionSoot(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), chemistryModel< CompType, ThermoType >::omega(), chemistryModel< CompType, ThermoType >::tc(), and EulerImplicit< ChemistryModel >::updateRRInReactionI().
const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & grhs () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 517 of file Reaction.C.
References NotImplemented.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega().
const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & glhs () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 508 of file Reaction.C.
References NotImplemented.
const Foam::speciesTable & species () const
Definition at line 492 of file Reaction.C.
Referenced by solidReaction< ReactionThermo >::clone(), and Reaction< ReactionThermo >::clone().
const Foam::speciesTable & gasSpecies () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 499 of file Reaction.C.
References NotImplemented.
void setLRhs (Istream & is, const speciesTable & species, List< specieCoeffs > & lhs, List< specieCoeffs > & rhs)
Construct the left- and right-hand-side reaction coefficients.
Definition at line 234 of file Reaction.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), UList< T >::empty(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, IOstream::good(), token::isPunctuation(), UList< T >::last(), Istream::putBack(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink().
Foam::scalar kf (const scalar p, const scalar T, const scalarField & c) const virtual
Forward rate constant.
Definition at line 456 of file Reaction.C.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), chemistryModel< CompType, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), and chemistryModel< CompType, ThermoType >::omega().
Foam::scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant from the given forward rate constant.
Definition at line 468 of file Reaction.C.
Referenced by chemistryModel< CompType, ThermoType >::jacobian(), and chemistryModel< CompType, ThermoType >::omega().
Foam::scalar kr (const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant.
Note this evaluates the forward rate constant and divides by the equilibrium constant
Definition at line 481 of file Reaction.C.
void write (Ostream & os) const virtual
Write.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 446 of file Reaction.C.
References Foam::nl, reaction(), and Ostream::writeKeyword().
Referenced by ReactionList< ThermoType >::write().
Friends And Related Function Documentation
Ostream& operator (Ostream & , const Reaction< ReactionThermo > &) friend
Member Data Documentation
Foam::label nUnNamedReactions = 0 static
Number of un-named reactions.
Definition at line 84 of file Reaction.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.H
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.C
src/thermophysicalModels/specie/reaction/Reactions/Reaction/ReactionI.H