OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PtrListDictionary< T > Class Template Reference
Template dictionary class which manages the storage associated with it.
Public Member Functions
PtrListDictionary (const label size)
Construct given initial list size.
PtrListDictionary (const PtrListDictionary &)
Copy construct.
template<class INew >
PtrListDictionary (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrListDictionary (Istream &)
Construct from Istream.
autoPtr< T > set (const label, const word &key, T *)
Set element to pointer provided and return old element.
autoPtr< T > set (const label, const word &key, autoPtr< T > &)
Set element to autoPtr value provided and return old element.
autoPtr< T > set (const label, const word &key, tmp< T > &)
Set element to tmp value provided and return old element.
const T & operator[] (const word &key) const
Find and return entry.
T & operator[] (const word &key)
Find and return entry.
Public Member Functions inherited from DictionaryBase< PtrList< T >, T >
DictionaryBase (const label size=128)
Construct given initial table size.
DictionaryBase (const DictionaryBase &)
Copy construct.
DictionaryBase (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
DictionaryBase (Istream &)
Construct from Istream using default Istream constructor class.
bool found (const word &) const
Search DictionaryBase for given keyword.
const T * lookupPtr (const word &) const
Find and return an entry if present, otherwise return NULL.
T * lookupPtr (const word &)
Find and return an entry if present, otherwise return NULL.
const T * lookup (const word &) const
Find and return entry.
T * lookup (const word &)
Find and return entry.
wordList toc () const
Return the table of contents.
void insert (const word &, T *)
Add at head of dictionary.
void append (const word &, T *)
Add at tail of dictionary.
T * remove (const word &)
Remove and return entry specified by keyword.
void clear ()
Clear the dictionary.
void transfer (DictionaryBase< PtrList< T >, T > &)
Transfer the contents of the argument into this DictionaryBase.
void operator= (const DictionaryBase &)
const T * operator[] (const word &key) const
Find and return entry.
T * operator[] (const word &key)
Find and return entry.
Public Member Functions inherited from PtrList< T >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< T > &)
Copy constructor.
template<class CloneArg >
PtrList (const PtrList< T > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< T >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &)
Construct as copy of SLPtrList<T>
template<class INew >
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (T *)
Append an element at the end of the list.
void append (const autoPtr< T > &)
void append (const tmp< T > &)
void transfer (PtrList< T > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< T > set (const label, T *)
Set element. Return old element (can be NULL).
autoPtr< T > set (const label, const autoPtr< T > &)
autoPtr< T > set (const label, const tmp< T > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
void operator= (const PtrList< T > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the PtrList.
const_iterator cend () const
Return an const_iterator to end traversing the PtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the PtrList.
const_iterator end () const
Return an const_iterator to end traversing the PtrList.
Additional Inherited Members
Public Types inherited from PtrList< T >
typedef T value_type
Type of values the PtrList contains.
typedef T & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant PtrList::value_type.
Protected Member Functions inherited from DictionaryBase< PtrList< T >, T >
void addEntries ()
Protected Member Functions inherited from PtrList< T >
template<class INew >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Attributes inherited from DictionaryBase< PtrList< T >, T >
HashTable< T * > hashedTs_
HashTable of the entries held on the IDLListType for quick lookup.
Detailed Description
template<class T>
class Foam::PtrListDictionary< T >
Template dictionary class which manages the storage associated with it.
It is derived from DictionaryBase instantiated on the memory managed PtrList of <T> to provide ordered indexing in addition to the dictionary lookup.
Source files
PtrListDictionary.H
PtrListDictionary.C
Definition at line 53 of file PtrListDictionary.H.
Constructor & Destructor Documentation
PtrListDictionary (const label size)
Construct given initial list size.
Definition at line 31 of file PtrListDictionary.C.
References PtrList< T >::setSize().
PtrListDictionary (const PtrListDictionary< T > & dict)
Copy construct.
Definition at line 40 of file PtrListDictionary.C.
PtrListDictionary (Istream & is, const INew & iNew)
Construct from Istream using given Istream constructor class.
Definition at line 48 of file PtrListDictionary.C.
PtrListDictionary (Istream & is)
Construct from Istream.
Definition at line 55 of file PtrListDictionary.C.
References PtrListDictionary< T >::set().
Member Function Documentation
Foam::autoPtr< T > set (const label i, const word & key, T * ptr) inline
Set element to pointer provided and return old element.
Definition at line 65 of file PtrListDictionary.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, DictionaryBase< PtrList< T >, T >::hashedTs_, HashTable< T, Key, Hash >::insert(), PtrList< T >::set(), and Foam::T().
Referenced by PtrListDictionary< T >::PtrListDictionary(), and PtrListDictionary< T >::set().
Foam::autoPtr< T > set (const label i, const word & key, autoPtr< T > & aptr) inline
Set element to autoPtr value provided and return old element.
Definition at line 83 of file PtrListDictionary.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, DictionaryBase< PtrList< T >, T >::hashedTs_, HashTable< T, Key, Hash >::insert(), autoPtr< T >::ptr(), PtrListDictionary< T >::set(), PtrList< T >::set(), and Foam::T().
Foam::autoPtr< T > set (const label i, const word & key, tmp< T > & t) inline
Set element to tmp value provided and return old element.
Definition at line 102 of file PtrListDictionary.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, DictionaryBase< PtrList< T >, T >::hashedTs_, HashTable< T, Key, Hash >::insert(), tmp< T >::ptr(), PtrList< T >::set(), and Foam::T().
const T& operator[] (const word & key) const inline
Find and return entry.
Definition at line 93 of file PtrListDictionary.H.
T& operator[] (const word & key) inline
Find and return entry.
Definition at line 99 of file PtrListDictionary.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Dictionaries/PtrListDictionary/PtrListDictionary.H
src/OpenFOAM/containers/Dictionaries/PtrListDictionary/PtrListDictionary.C