OpenFOAM: profileModelList Class Reference
profileModelList Class Reference
Base class for profile models.
Public Member Functions
profileModelList (const dictionary &dict, const bool readFields=true)
Constructor.
~profileModelList ()
Destructor.
void connectBlades (const List< word > &names, List< label > &addr) const
Set blade->profile addressing.
Public Member Functions inherited from PtrList< profileModel >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< profileModel > &)
Copy constructor.
PtrList (const PtrList< profileModel > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< profileModel >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< profileModel > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< profileModel > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (profileModel *)
Append an element at the end of the list.
void append (const autoPtr< profileModel > &)
void append (const tmp< profileModel > &)
void transfer (PtrList< profileModel > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< profileModel > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< profileModel > set (const label, profileModel *)
Set element to given T* and return old element (can be NULL)
autoPtr< profileModel > set (const label, const autoPtr< profileModel > &)
Set element to given autoPtr<T> and return old element.
autoPtr< profileModel > set (const label, const tmp< profileModel > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< profileModel > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Attributes
const dictionary dict_
Dictionary.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< profileModel >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Base class for profile models.
Source files
profileModelList.H
profileModelList.C
Definition at line 49 of file profileModelList.H.
Constructor & Destructor Documentation
profileModelList (const dictionary & dict, const bool readFields = true)
Constructor.
Definition at line 31 of file profileModelList.C.
References Foam::endl(), forAll, Foam::Info, Foam::New(), setSize(), dictionary::subDict(), and dictionary::toc().
~profileModelList ()
Destructor.
Definition at line 70 of file profileModelList.C.
References profileModelList::connectBlades().
Member Function Documentation
void connectBlades (const List< word > & names, List< label > & addr) const
Set blade->profile addressing.
Definition at line 77 of file profileModelList.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, profileModel::name(), UPtrList< T >::operator[](), and UPtrList< T >::size().
Referenced by profileModelList::~profileModelList().
Member Data Documentation
const dictionary dict_ protected
Dictionary.
Definition at line 59 of file profileModelList.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/profileModel/profileModelList.H
src/fvOptions/sources/derived/rotorDiskSource/profileModel/profileModelList.C