OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionCoupledBaseFvPatch Class Reference abstract
Base class of regionCoupledFvPatch with common functionality for regionCoupledFvPatch and regionCoupledWallFvPatch.
Public Member Functions
TypeName ("regionCoupledBase")
Runtime type information.
regionCoupledBaseFvPatch (const polyPatch &pp, const fvPatch &patch)
Construct from polyPatch.
virtual ~regionCoupledBaseFvPatch ()
Destructor.
virtual label neighbPatchID () const
Return neighbour.
virtual bool owner () const
Is it the owner?
virtual const
regionCoupledBaseFvPatch & neighbPatch () const
Return regionCoupledBase neighb Patch.
virtual const
AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
virtual const polyMesh & nbrMesh () const
Returns neighbour polyMesh.
const fvPatch & patch () const
Return fvPatch.
bool sameRegion () const
Returns if it is the same Region.
const regionCoupledBase & regionCoupledPatch () const
Return regionCoupledPolyPatch.
const fvPatch & neighbFvPatch () const
Return neighbor fvPatch.
const word & regionCoupleType () const
Return the interface type.
virtual const labelUList & faceCells () const =0
Return faceCell addressing.
Public Member Functions inherited from regionCoupledLduInterface
TypeName ("regionCoupledLduInterface")
Runtime type information.
regionCoupledLduInterface ()
Construct null.
virtual ~regionCoupledLduInterface ()
Destructor.
Protected Member Functions
const fvMesh & nbrFvMesh () const
Returns fvMesh.
Protected Attributes
const regionCoupledBase & regionCoupledBase_
Reference to regionCoupledBase.
const fvPatch & patch_
Reference to fvPatch.
Detailed Description
Base class of regionCoupledFvPatch with common functionality for regionCoupledFvPatch and regionCoupledWallFvPatch.
Source files
regionCoupledBaseFvPatch.H
regionCoupledBaseFvPatch.C
Definition at line 53 of file regionCoupledBaseFvPatch.H.
Constructor & Destructor Documentation
regionCoupledBaseFvPatch (const polyPatch & pp, const fvPatch & patch) inline
Construct from polyPatch.
Definition at line 93 of file regionCoupledBaseFvPatch.H.
virtual ~regionCoupledBaseFvPatch () inline virtual
Destructor.
Definition at line 108 of file regionCoupledBaseFvPatch.H.
Member Function Documentation
const fvMesh& nbrFvMesh () const inline protected
Returns fvMesh.
Definition at line 71 of file regionCoupledBaseFvPatch.H.
References fvPatch::boundaryMesh(), objectRegistry::lookupObject(), fvBoundaryMesh::mesh(), regionCoupledBase::nbrRegionName(), regionCoupledBaseFvPatch::patch_, regionCoupledBaseFvPatch::regionCoupledBase_, and fvMesh::time().
Referenced by regionCoupledBaseFvPatch::neighbFvPatch(), and regionCoupledBaseFvPatch::neighbPatch().
TypeName ("regionCoupledBase")
Runtime type information.
virtual label neighbPatchID () const inline virtual
Return neighbour.
Implements regionCoupledLduInterface.
Definition at line 117 of file regionCoupledBaseFvPatch.H.
References regionCoupledBase::neighbPatchID(), and regionCoupledBaseFvPatch::regionCoupledBase_.
virtual bool owner () const inline virtual
Is it the owner?
Implements regionCoupledLduInterface.
Definition at line 123 of file regionCoupledBaseFvPatch.H.
References regionCoupledBase::owner(), and regionCoupledBaseFvPatch::regionCoupledBase_.
virtual const regionCoupledBaseFvPatch& neighbPatch () const inline virtual
Return regionCoupledBase neighb Patch.
Implements regionCoupledLduInterface.
Definition at line 129 of file regionCoupledBaseFvPatch.H.
References fvMesh::boundary(), regionCoupledBaseFvPatch::nbrFvMesh(), regionCoupledBase::neighbPatchID(), and regionCoupledBaseFvPatch::regionCoupledBase_.
virtual const AMIPatchToPatchInterpolation& AMI () const inline virtual
Return a reference to the AMI interpolator.
Definition at line 141 of file regionCoupledBaseFvPatch.H.
References regionCoupledBase::AMI(), and regionCoupledBaseFvPatch::regionCoupledBase_.
virtual const polyMesh& nbrMesh () const inline virtual
Returns neighbour polyMesh.
Implements regionCoupledLduInterface.
Definition at line 147 of file regionCoupledBaseFvPatch.H.
References fvPatch::boundaryMesh(), objectRegistry::lookupObject(), fvBoundaryMesh::mesh(), regionCoupledBase::nbrRegionName(), regionCoupledBaseFvPatch::patch_, regionCoupledBaseFvPatch::regionCoupledBase_, and fvMesh::time().
const fvPatch& patch () const inline
Return fvPatch.
Definition at line 159 of file regionCoupledBaseFvPatch.H.
References regionCoupledBaseFvPatch::patch_.
bool sameRegion () const inline
Returns if it is the same Region.
Definition at line 165 of file regionCoupledBaseFvPatch.H.
References regionCoupledBaseFvPatch::regionCoupledBase_, and regionCoupledBase::sameRegion().
const regionCoupledBase& regionCoupledPatch () const inline
Return regionCoupledPolyPatch.
Definition at line 171 of file regionCoupledBaseFvPatch.H.
References regionCoupledBaseFvPatch::regionCoupledBase_.
const fvPatch& neighbFvPatch () const inline
Return neighbor fvPatch.
Definition at line 177 of file regionCoupledBaseFvPatch.H.
References fvMesh::boundary(), regionCoupledBaseFvPatch::nbrFvMesh(), regionCoupledBase::neighbPatchID(), and regionCoupledBaseFvPatch::regionCoupledBase_.
const word& regionCoupleType () const inline
Return the interface type.
Definition at line 189 of file regionCoupledBaseFvPatch.H.
References regionCoupledBaseFvPatch::regionCoupledBase_, and regionCoupledBase::regionCoupleType().
Referenced by energyRegionCoupledFvPatchScalarField::interfaceFieldType().
virtual const labelUList& faceCells () const pure virtual
Return faceCell addressing.
Implemented in regionCoupledWallFvPatch, and regionCoupledFvPatch.
Member Data Documentation
const regionCoupledBase& regionCoupledBase_ protected
Reference to regionCoupledBase.
Definition at line 62 of file regionCoupledBaseFvPatch.H.
Referenced by regionCoupledBaseFvPatch::AMI(), regionCoupledBaseFvPatch::nbrFvMesh(), regionCoupledBaseFvPatch::nbrMesh(), regionCoupledBaseFvPatch::neighbFvPatch(), regionCoupledBaseFvPatch::neighbPatch(), regionCoupledBaseFvPatch::neighbPatchID(), regionCoupledBaseFvPatch::owner(), regionCoupledBaseFvPatch::regionCoupledPatch(), regionCoupledBaseFvPatch::regionCoupleType(), and regionCoupledBaseFvPatch::sameRegion().
const fvPatch& patch_ protected
Reference to fvPatch.
Definition at line 65 of file regionCoupledBaseFvPatch.H.
Referenced by regionCoupledBaseFvPatch::nbrFvMesh(), regionCoupledBaseFvPatch::nbrMesh(), and regionCoupledBaseFvPatch::patch().
The documentation for this class was generated from the following file:
src/finiteVolume/fvMesh/fvPatches/derived/regionCoupled/regionCoupledBaseFvPatch.H