OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PtrList< T > Class Template Reference
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
Inherited by DictionaryBase< PtrList< T >, T >, blockMesh, fvBoundaryMesh, IOPtrList< T >, pointBoundaryMesh, and polyBoundaryMesh.
Classes
class const_iterator
An STL-conforming const_iterator.
class iterator
An STL-conforming iterator.
Public Types
typedef T value_type
Type of values the PtrList contains.
typedef T & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant PtrList::value_type.
Public Member Functions
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< T > &)
Copy constructor.
template<class CloneArg >
PtrList (const PtrList< T > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< T >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &)
Construct as copy of SLPtrList<T>
template<class INew >
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (T *)
Append an element at the end of the list.
void append (const autoPtr< T > &)
void append (const tmp< T > &)
void transfer (PtrList< T > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< T > set (const label, T *)
Set element. Return old element (can be NULL).
autoPtr< T > set (const label, const autoPtr< T > &)
autoPtr< T > set (const label, const tmp< T > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
void operator= (const PtrList< T > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the PtrList.
const_iterator cend () const
Return an const_iterator to end traversing the PtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the PtrList.
const_iterator end () const
Return an const_iterator to end traversing the PtrList.
Protected Member Functions
template<class INew >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Friends
class iterator
class const_iterator
Istream & operator>> (Istream &, PtrList< T > &)
Read List from Istream, discarding contents of existing List.
Ostream & operator (Ostream &, const PtrList< T > &)
Detailed Description
template<class T>
class Foam::PtrList< T >
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
The element operator [] returns a reference to the object rather than a pointer.
Source files
PtrList.H
PtrListI.H
PtrList.C
PtrListIO.C
Definition at line 61 of file List.H.
Member Typedef Documentation
typedef T value_type
Type of values the PtrList contains.
Definition at line 261 of file PtrList.H.
typedef T& reference
Type that can be used for storing into PtrList::value_type objects.
Definition at line 264 of file PtrList.H.
typedef const T& const_reference
Type that can be used for storing into constant PtrList::value_type.
objects.
Definition at line 268 of file PtrList.H.
Constructor & Destructor Documentation
PtrList ()
Null Constructor.
Definition at line 34 of file PtrList.C.
PtrList (const label s) explicit
Construct with size specified.
Definition at line 41 of file PtrList.C.
PtrList (const PtrList< T > & a)
Copy constructor.
Definition at line 48 of file PtrList.C.
References forAll.
PtrList (const PtrList< T > & a, const CloneArg & cloneArg)
Copy constructor with additional argument for clone.
Definition at line 61 of file PtrList.C.
References forAll.
PtrList (const Xfer< PtrList< T >> & lst)
Construct by transferring the parameter contents.
Definition at line 73 of file PtrList.C.
References PtrList< T >::transfer().
PtrList (PtrList< T > & a, bool reuse)
Construct as copy or re-use as specified.
Definition at line 80 of file PtrList.C.
References forAll.
PtrList (const SLPtrList< T > & sll) explicit
Construct as copy of SLPtrList<T>
Definition at line 95 of file PtrList.C.
References LList< SLListBase, T * >::begin(), LList< SLListBase, T * >::end(), and SLListBase::size().
PtrList (Istream & is, const INew & inewt)
Construct from Istream using given Istream constructor class.
Definition at line 160 of file PtrListIO.C.
References Foam::read().
PtrList (Istream & is)
Construct from Istream using default Istream constructor class.
Definition at line 167 of file PtrListIO.C.
References PtrList< T >::clear(), forAll, Foam::nl, Foam::operator>>(), Foam::read(), PtrList< T >::read(), and PtrList< T >::size().
~PtrList ()
Destructor.
Definition at line 118 of file PtrList.C.
References forAll.
Member Function Documentation
void read (Istream & is, const INew & inewt) protected
Read from Istream using given Istream constructor class.
Definition at line 36 of file PtrListIO.C.
References LList< SLListBase, T >::append(), LList< SLListBase, T >::begin(), LList< SLListBase, T >::end(), IOstream::eof(), Foam::exit(), IOstream::fatalCheck(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, token::info(), token::isLabel(), token::isPunctuation(), token::labelToken(), token::pToken(), Istream::putBack(), Istream::readBeginList(), Istream::readEndList(), s(), setSize(), SLListBase::size(), and T.
Referenced by IOPtrList< T >::IOPtrList(), and PtrList< T >::PtrList().
Foam::label size () const inline
Return the number of elements in the PtrList.
Definition at line 32 of file PtrListI.H.
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), snappyLayerDriver::addLayers(), fvMeshTools::addPatch(), meshRefinement::addPatch(), extendedEdgeMesh::allNearestFeatureEdges(), meshRefinement::appendPatch(), attachPolyTopoChanger::attach(), nearWallFields::calcAddressing(), addPatchCellLayer::calcSidePatch(), polyTopoChange::changeMesh(), repatchPolyTopoChanger::changePatchID(), polyBoundaryMesh::checkDefinition(), polyBoundaryMesh::checkParallelSync(), inverseFaceDistanceDiffusivity::correct(), nearWallDistNoSearch::correct(), nearWallDist::correct(), pointPatchDist::correct(), wallDistData< TransferType >::correct(), motionSmootherAlgo::curPoints(), structuredDecomp::decompose(), decompositionMethod::decompose(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), fvMeshDistribute::distribute(), snappyLayerDriver::doLayers(), Foam::facePointN(), polyBoundaryMesh::findPatchIDs(), fvFieldReconstructor::fvFieldReconstructor(), surfaceZonesInfo::getAllClosedNamedSurfaces(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), surfaceZonesInfo::getNamedSurfaces(), cellDistFuncs::getPatchIDs(), surfaceZonesInfo::getUnclosedNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), injectionModelList::info(), interRegionExplicitPorositySource::initialise(), fvBoundaryMesh::interfaces(), meshToMesh::interpolationMethodAMI(), regionModel::interRegionAMI(), rigidBodyModel::join(), rigidBodyModel::join_(), layerParameters::layerParameters(), lduPrimitiveMesh::lduPrimitiveMesh(), LUscalarMatrix::LUscalarMatrix(), meshRefinement::makeDisplacementField(), polyTopoChange::makeMesh(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), MeshedSurface< Face >::MeshedSurface(), meshTriangulation::meshTriangulation(), polyTopoChanger::names(), ZoneMesh< ZoneType, MeshType >::names(), polyBoundaryMesh::names(), regionModel::nbrCoupledPatchID(), extendedEdgeMesh::nearestFeatureEdgeByType(), potential::nPairPotentials(), blockMesh::numZonedBlocks(), ListPlusEqOp< T, Size >::operator()(), procLess::operator()(), listPlusEqOp< T >::operator()(), PtrList< T >::operator=(), polyTopoChanger::operator==(), blockMesh::patchDicts(), patchInjection::patchInjection(), patchDistMethod::patchTypes(), polyBoundaryMesh::physicalTypes(), pointFieldReconstructor::pointFieldReconstructor(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), Foam::polyMeshZipUpCells(), polyTopoChange::polyTopoChange(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), PtrList< T >::PtrList(), thermalBaffleModel::read(), boundaryMesh::read(), polyMesh::readUpdate(), ensightParts::recalculate(), pointFieldReconstructor::reconstructField(), SloanRenumber::renumber(), structuredRenumber::renumber(), PtrList< T >::reorder(), fvMeshSubset::setCellSubset(), polyBoundaryMesh::setGroup(), fvMeshSubset::setLargeCellSubset(), removeCells::setRefinement(), meshCutAndRemove::setRefinement(), PtrList< T >::setSize(), singleCellFvMesh::singleCellFvMesh(), ensightParts::size(), pairPatchAgglomeration::size(), GAMGAgglomeration::size(), surfacePatchIOList::surfacePatchIOList(), surfZoneIOList::surfZoneIOList(), polyTopoChanger::types(), ZoneMesh< ZoneType, MeshType >::types(), polyBoundaryMesh::types(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::types(), valveBank::valveBank(), wallLayerCells::wallLayerCells(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), vtkSetWriter< Type >::write(), gnuplotSetWriter< Type >::write(), xmgraceSetWriter< Type >::write(), polyBoundaryMesh::writeData(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), fvMeshTools::zeroPatchFields(), ZoneMesh< ZoneType, MeshType >::ZoneMesh(), meshRefinement::zonify(), and externalCoupledMixedFvPatchField< Type >::~externalCoupledMixedFvPatchField().
bool empty () const inline
Return true if the PtrList is empty (ie, size() is zero).
Definition at line 39 of file PtrListI.H.
Referenced by NamedEnum< Enum, nEnum >::names(), and fvMeshTools::zeroPatchFields().
T & first () inline
Return reference to the first element of the list.
Definition at line 46 of file PtrListI.H.
const T & first () const inline
Return reference to first element of the list.
Definition at line 53 of file PtrListI.H.
T & last () inline
Return reference to the last element of the list.
Definition at line 60 of file PtrListI.H.
const T & last () const inline
Return reference to the last element of the list.
Definition at line 67 of file PtrListI.H.
void setSize (const label newSize)
Reset size of PtrList. If extending the PtrList, new entries are.
set to NULL. If truncating the PtrList, removed entries are deleted.
Definition at line 133 of file PtrList.C.
References Foam::abort(), PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, Foam::name(), List< T >::setSize(), PtrList< T >::size(), and Foam::T().
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), cellTable::addCellZones(), fvMeshTools::addPatch(), polyMesh::addPatches(), polyMesh::addZones(), meshRefinement::appendPatch(), polyBoundaryMesh::checkParallelSync(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), FacePostProcessing< CloudType >::FacePostProcessing(), lduPrimitiveMesh::gather(), interRegionExplicitPorositySource::initialise(), fvMeshAdder::MapVolFields(), moleFractions< ThermoType >::moleFractions(), PtrList< T >::operator=(), patchInjection::patchInjection(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), Foam::preservePatchTypes(), fvMeshDistribute::printFieldInfo(), PtrListDictionary< T >::PtrListDictionary(), functionObjectList::read(), polyMesh::readUpdate(), polyMesh::removeBoundary(), fvMesh::removeFvBoundary(), searchableSurfaces::searchableSurfaces(), decompositionMethod::setConstraints(), GAMGSolver::solve(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), fvMeshTools::zeroPatchFields(), and ZoneMesh< ZoneType, MeshType >::ZoneMesh().
void resize (const label newSize) inline
Alias for setSize(const label)
Definition at line 74 of file PtrListI.H.
References setSize().
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
allocated entries.
Definition at line 176 of file PtrList.C.
References List< T >::clear(), and forAll.
Referenced by functionObjectList::clear(), PtrList< T >::PtrList(), functionObjectList::read(), fvBoundaryMesh::readUpdate(), polyMesh::readUpdate(), polyMesh::removeBoundary(), fvMesh::removeFvBoundary(), decompositionMethod::setConstraints(), PtrList< T >::setSize(), and PtrList< T >::transfer().
void append (T * ptr) inline
Append an element at the end of the list.
Definition at line 81 of file PtrListI.H.
References setSize().
Referenced by PtrList< T >::append(), meshToMesh::interpolationMethodAMI(), and rigidBodyModel::join_().
void append (const autoPtr< T > & aptr) inline
Definition at line 90 of file PtrListI.H.
References PtrList< T >::append().
void append (const tmp< T > & t) inline
Definition at line 98 of file PtrListI.H.
void transfer (PtrList< T > & a)
Transfer the contents of the argument PtrList into this PtrList.
and annul the argument list.
Definition at line 191 of file PtrList.C.
References PtrList< T >::clear(), and List< T >::transfer().
Referenced by IOPtrList< T >::IOPtrList(), PtrList< T >::PtrList(), and functionObjectList::read().
Foam::Xfer< Foam::PtrList< T > > xfer () inline
Transfer contents to the Xfer container.
Definition at line 145 of file PtrListI.H.
References Foam::xferMove().
bool set (const label i) const inline
Is element set.
Definition at line 107 of file PtrListI.H.
Referenced by fvMeshAdder::add(), cellTable::addCellZones(), fvMeshTools::addPatch(), polyMesh::addPatches(), polyMesh::addZones(), meshRefinement::appendPatch(), fvFieldDecomposer::decomposeField(), boundaryMesh::deletePatch(), forAll(), lduPrimitiveMesh::gather(), surfaceZonesInfo::getAllClosedNamedSurfaces(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnclosedNamedSurfaces(), interRegionExplicitPorositySource::initialise(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), isoSurface::isoSurface(), LUscalarMatrix::LUscalarMatrix(), fvMeshAdder::MapVolFields(), pointBoundaryMesh::pointBoundaryMesh(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), Foam::preservePatchTypes(), fvMeshDistribute::printFieldInfo(), functionObjectList::read(), polyMesh::readUpdate(), refinementSurfaces::refinementSurfaces(), refinementFeatures::regionEdgeTrees(), PtrListDictionary< T >::set(), PtrList< T >::set(), decompositionMethod::setConstraints(), GAMGSolver::solve(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), and ZoneMesh< ZoneType, MeshType >::ZoneMesh().
Foam::autoPtr< T > set (const label i, T * ptr) inline
Set element. Return old element (can be NULL).
No checks on new element.
Definition at line 114 of file PtrListI.H.
References PtrList< T >::set().
Foam::autoPtr< T > set (const label i, const autoPtr< T > & aptr) inline
Definition at line 124 of file PtrListI.H.
References PtrList< T >::set().
Foam::autoPtr< T > set (const label i, const tmp< T > & t) inline
Definition at line 135 of file PtrListI.H.
void reorder (const labelUList & oldToNew)
Reorders elements. Ordering does not have to be done in.
ascending or descending order. Reordering has to be unique. (is shuffle)
Definition at line 199 of file PtrList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::name(), Foam::nl, List< T >::size(), PtrList< T >::size(), UList< T >::size(), Foam::T(), and List< T >::transfer().
Referenced by fvMeshTools::addPatch(), meshRefinement::addPatch(), fvMeshAdder::MapVolFields(), polyBoundaryMesh::reorder(), and fvMeshTools::reorderPatches().
const T & operator[] (const label i) const inline
Return element const reference.
Definition at line 154 of file PtrListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and T.
Referenced by pointBoundaryMesh::findIndices(), pointBoundaryMesh::movePoints(), and pointBoundaryMesh::updateMesh().
T & operator[] (const label i) inline
Return element reference.
Definition at line 171 of file PtrListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and T.
const T * operator() (const label i) const inline
Return element const pointer.
Definition at line 188 of file PtrListI.H.
void operator= (const PtrList< T > & a)
Assignment.
Definition at line 252 of file PtrList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::name(), PtrList< T >::setSize(), PtrList< T >::size(), and Foam::T().
Referenced by IOPtrList< T >::IOPtrList(), and IOPtrList< T >::operator=().
Foam::PtrList< T >::iterator begin () inline
Return an iterator to begin traversing the PtrList.
Definition at line 361 of file PtrListI.H.
Foam::PtrList< T >::iterator end () inline
Return an iterator to end traversing the PtrList.
Definition at line 368 of file PtrListI.H.
Foam::PtrList< T >::const_iterator cbegin () const inline
Return an const_iterator to begin traversing the PtrList.
Definition at line 583 of file PtrListI.H.
Foam::PtrList< T >::const_iterator cend () const inline
Return an const_iterator to end traversing the PtrList.
Definition at line 591 of file PtrListI.H.
Foam::PtrList< T >::const_iterator begin () const inline
Return an const_iterator to begin traversing the PtrList.
Definition at line 567 of file PtrListI.H.
Foam::PtrList< T >::const_iterator end () const inline
Return an const_iterator to end traversing the PtrList.
Definition at line 575 of file PtrListI.H.
Friends And Related Function Documentation
friend class iterator friend
Definition at line 275 of file PtrList.H.
friend class const_iterator friend
Definition at line 277 of file PtrList.H.
Istream& operator>> (Istream & , PtrList< T > &) friend
Read List from Istream, discarding contents of existing List.
Ostream& operator (Ostream & , const PtrList< T > &) friend
Referenced by fvBoundaryMesh::mesh(), polyBoundaryMesh::mesh(), fvBoundaryMesh::operator[](), polyBoundaryMesh::operator[](), fvBoundaryMesh::readUpdate(), and polyBoundaryMesh::writeObject().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/List/List.H
src/OpenFOAM/containers/Lists/PtrList/PtrList.H
src/OpenFOAM/containers/Lists/PtrList/PtrList.C
src/OpenFOAM/containers/Lists/PtrList/PtrListI.H
src/OpenFOAM/containers/Lists/PtrList/PtrListIO.C