OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
realizableKE< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Realizable k-epsilon turbulence model for incompressible and compressible flows.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel >::alphaField alphaField
typedef RASModel< BasicTurbulenceModel >::rhoField rhoField
typedef RASModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel >::alphaField alphaField
typedef RASModel< BasicTurbulenceModel >::rhoField rhoField
typedef RASModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("realizableKE")
Runtime type information.
realizableKE (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~realizableKE ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
tmp< volScalarField > rCmu (const volTensorField &gradU, const volScalarField &S2, const volScalarField &magS)
virtual void correctNut (const volTensorField &gradU, const volScalarField &S2, const volScalarField &magS)
virtual void correctNut ()
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar A0_
dimensionedScalar C2_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::realizableKE< BasicTurbulenceModel >
Realizable k-epsilon turbulence model for incompressible and compressible flows.
References:
    Shih, T. H., Liou, W. W., Shabbir, A., Yang, Z., & Zhu, J. (1994).
    A new k-epsilon eddy viscosity model for high Reynolds number
    turbulent flows: Model development and validation.
    NASA STI/Recon Technical Report N, 95, 11442.
    Shih, T. H., Liou, W. W., Shabbir, A., Yang, Z., & Zhu, J. (1995).
    A New k-epsilon Eddy Viscosity Model for High Reynolds Number
    Turbulent Flows.
    Computers and Fluids, 24(3), 227-238.
The default model coefficients are
    realizableKECoeffs
    {
        Cmu         0.09;
        A0          4.0;
        C2          1.9;
        sigmak      1.0;
        sigmaEps    1.2;
    }
Source files
realizableKE.H
realizableKE.C
Definition at line 81 of file realizableKE.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 128 of file realizableKE.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 129 of file realizableKE.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 130 of file realizableKE.H.
Constructor & Destructor Documentation
realizableKE (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 130 of file realizableKE.C.
References Foam::bound().
virtual ~realizableKE () inline virtual
Destructor.
Definition at line 153 of file realizableKE.H.
Member Function Documentation
tmp< volScalarField > rCmu (const volTensorField & gradU, const volScalarField & S2, const volScalarField & magS) protected
Definition at line 40 of file realizableKE.C.
References Foam::acos(), tmp< T >::clear(), Foam::cos(), Foam::dev(), Foam::magSqr(), Foam::max(), Foam::min(), Foam::skew(), Foam::sqrt(), and Foam::symm().
void correctNut (const volTensorField & gradU, const volScalarField & S2, const volScalarField & magS) protected virtual
Definition at line 73 of file realizableKE.C.
References Foam::sqr().
void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 87 of file realizableKE.C.
References Foam::dev(), Foam::fvc::grad(), Foam::magSqr(), Foam::sqrt(), and Foam::symm().
tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 97 of file realizableKE.C.
References Foam::dimTime, and Foam::dimVolume.
tmp< fvScalarMatrix > epsilonSource () const protected virtual
Definition at line 112 of file realizableKE.C.
References Foam::dimTime, and Foam::dimVolume.
TypeName ("realizableKE< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Re-read model coefficients if they have changed.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 238 of file realizableKE.C.
References Foam::read().
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 163 of file realizableKE.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
tmp<volScalarField> DepsilonEff () const inline
Return the effective diffusivity for epsilon.
Definition at line 176 of file realizableKE.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 189 of file realizableKE.H.
References realizableKE< BasicTurbulenceModel >::k_.
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 195 of file realizableKE.H.
References realizableKE< BasicTurbulenceModel >::epsilon_.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 258 of file realizableKE.C.
References Foam::fvc::absolute(), Foam::bound(), correct, Foam::fvm::ddt(), Foam::dev(), Foam::fvm::div(), Foam::fvc::div(), divU(), Foam::constant::universal::G, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), Foam::max(), nu, nut, phi, Foam::solve(), Foam::fvm::Sp(), Foam::sqrt(), Foam::fvm::SuSp(), Foam::symm(), and Foam::twoSymm().
Member Data Documentation
dimensionedScalar Cmu_ protected
Definition at line 92 of file realizableKE.H.
dimensionedScalar A0_ protected
Definition at line 93 of file realizableKE.H.
dimensionedScalar C2_ protected
Definition at line 94 of file realizableKE.H.
dimensionedScalar sigmak_ protected
Definition at line 95 of file realizableKE.H.
dimensionedScalar sigmaEps_ protected
Definition at line 96 of file realizableKE.H.
volScalarField k_ protected
Definition at line 101 of file realizableKE.H.
Referenced by realizableKE< BasicTurbulenceModel >::k().
volScalarField epsilon_ protected
Definition at line 102 of file realizableKE.H.
Referenced by realizableKE< BasicTurbulenceModel >::epsilon().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/realizableKE/realizableKE.H
src/TurbulenceModels/turbulenceModels/RAS/realizableKE/realizableKE.C