OpenFOAM: PrimitivePatchInterpolation< Patch > Class Template Reference
PrimitivePatchInterpolation< Patch > Class Template Reference
Interpolation class within a primitive patch. Allows interpolation from points to faces and vice versa.
Public Member Functions
PrimitivePatchInterpolation (const Patch &p)
Construct from PrimitivePatch.
~PrimitivePatchInterpolation ()
Destructor.
template<class Type >
tmp< Field< Type > > faceToPointInterpolate (const Field< Type > &ff) const
Interpolate from faces to points.
template<class Type >
tmp< Field< Type > > faceToPointInterpolate (const tmp< Field< Type >> &tff) const
template<class Type >
tmp< Field< Type > > pointToFaceInterpolate (const Field< Type > &pf) const
Interpolate from points to faces.
template<class Type >
tmp< Field< Type > > pointToFaceInterpolate (const tmp< Field< Type >> &tpf) const
template<class Type >
tmp< Field< Type > > faceToEdgeInterpolate (const Field< Type > &ff) const
Interpolate from faces to edges.
template<class Type >
tmp< Field< Type > > faceToEdgeInterpolate (const tmp< Field< Type >> &tff) const
bool movePoints ()
Do what is neccessary if the mesh has moved.
Detailed Description
template<class Patch>
class Foam::PrimitivePatchInterpolation< Patch >
Interpolation class within a primitive patch. Allows interpolation from points to faces and vice versa.
Source files
PrimitivePatchInterpolation.H
PrimitivePatchInterpolation.C
Definition at line 51 of file PrimitivePatchInterpolation.H.
Constructor & Destructor Documentation
PrimitivePatchInterpolation (const Patch & p)
Construct from PrimitivePatch.
Definition at line 152 of file PrimitivePatchInterpolation.C.
~PrimitivePatchInterpolation ()
Destructor.
Definition at line 163 of file PrimitivePatchInterpolation.C.
References PrimitivePatchInterpolation< Patch >::faceToPointInterpolate().
Member Function Documentation
tmp< Field< Type > > faceToPointInterpolate (const Field< Type > & ff) const
Interpolate from faces to points.
Definition at line 174 of file PrimitivePatchInterpolation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, tmp< T >::ref(), List< Type >::size(), and Foam::Zero.
Referenced by PrimitivePatchInterpolation< Patch >::faceToPointInterpolate(), and PrimitivePatchInterpolation< Patch >::~PrimitivePatchInterpolation().
tmp< Field< Type > > faceToPointInterpolate (const tmp< Field< Type >> & tff) const
Definition at line 218 of file PrimitivePatchInterpolation.C.
References PrimitivePatchInterpolation< Patch >::faceToPointInterpolate(), and PrimitivePatchInterpolation< Patch >::pointToFaceInterpolate().
tmp< Field< Type > > pointToFaceInterpolate (const Field< Type > & pf) const
Interpolate from points to faces.
Definition at line 231 of file PrimitivePatchInterpolation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, tmp< T >::ref(), List< Type >::size(), List< T >::size(), and Foam::Zero.
Referenced by PrimitivePatchInterpolation< Patch >::faceToPointInterpolate(), and PrimitivePatchInterpolation< Patch >::pointToFaceInterpolate().
tmp< Field< Type > > pointToFaceInterpolate (const tmp< Field< Type >> & tpf) const
Definition at line 275 of file PrimitivePatchInterpolation.C.
References PrimitivePatchInterpolation< Patch >::faceToEdgeInterpolate(), and PrimitivePatchInterpolation< Patch >::pointToFaceInterpolate().
tmp< Field< Type > > faceToEdgeInterpolate (const Field< Type > & ff) const
Interpolate from faces to edges.
Definition at line 288 of file PrimitivePatchInterpolation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, tmp< T >::ref(), List< Type >::size(), List< T >::size(), and Foam::Zero.
Referenced by PrimitivePatchInterpolation< Patch >::faceToEdgeInterpolate(), and PrimitivePatchInterpolation< Patch >::pointToFaceInterpolate().
tmp< Field< Type > > faceToEdgeInterpolate (const tmp< Field< Type >> & tff) const
Definition at line 332 of file PrimitivePatchInterpolation.C.
References PrimitivePatchInterpolation< Patch >::faceToEdgeInterpolate().
bool movePoints ()
Do what is neccessary if the mesh has moved.
Definition at line 343 of file PrimitivePatchInterpolation.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/primitivePatchInterpolation/PrimitivePatchInterpolation.H
src/OpenFOAM/interpolations/primitivePatchInterpolation/PrimitivePatchInterpolation.C