OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Pstream Class Reference
Inter-processor communications stream.
Public Member Functions
ClassName ("Pstream")
Pstream (const commsTypes commsType, const label bufSize=0)
Construct given optional buffer size.
Public Member Functions inherited from UPstream
ClassName ("UPstream")
UPstream (const commsTypes commsType)
Construct given optional buffer size.
commsTypes commsType () const
Get the communications type of the stream.
commsTypes commsType (const commsTypes ct)
Set the communications type of the stream.
Static Public Member Functions
template<class T , class BinaryOp >
static void gather (const List< commsStruct > &comms, T &Value, const BinaryOp &bop, const int tag, const label comm)
Gather data. Apply bop to combine Value.
template<class T , class BinaryOp >
static void gather (T &Value, const BinaryOp &bop, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void scatter (const List< commsStruct > &comms, T &Value, const int tag, const label comm)
Scatter data. Distribute without modification. Reverse of gather.
template<class T >
static void scatter (T &Value, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T , class CombineOp >
static void combineGather (const List< commsStruct > &comms, T &Value, const CombineOp &cop, const int tag, const label comm)
template<class T , class CombineOp >
static void combineGather (T &Value, const CombineOp &cop, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void combineScatter (const List< commsStruct > &comms, T &Value, const int tag, const label comm)
Scatter data. Reverse of combineGather.
template<class T >
static void combineScatter (T &Value, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T , class CombineOp >
static void listCombineGather (const List< commsStruct > &comms, List< T > &Value, const CombineOp &cop, const int tag, const label comm)
template<class T , class CombineOp >
static void listCombineGather (List< T > &Value, const CombineOp &cop, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void listCombineScatter (const List< commsStruct > &comms, List< T > &Value, const int tag, const label comm)
Scatter data. Reverse of combineGather.
template<class T >
static void listCombineScatter (List< T > &Value, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class Container , class CombineOp >
static void mapCombineGather (const List< commsStruct > &comms, Container &Values, const CombineOp &cop, const int tag, const label comm)
template<class Container , class CombineOp >
static void mapCombineGather (Container &Values, const CombineOp &cop, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class Container >
static void mapCombineScatter (const List< commsStruct > &comms, Container &Values, const int tag, const label comm)
Scatter data. Reverse of combineGather.
template<class Container >
static void mapCombineScatter (Container &Values, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void gatherList (const List< commsStruct > &comms, List< T > &Values, const int tag, const label comm)
Gather data but keep individual values separate.
template<class T >
static void gatherList (List< T > &Values, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void scatterList (const List< commsStruct > &comms, List< T > &Values, const int tag, const label comm)
Scatter data. Reverse of gatherList.
template<class T >
static void scatterList (List< T > &Values, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class Container , class T >
static void exchange (const UList< Container > &sendData, const labelUList &recvSizes, List< Container > &recvData, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool block=true)
Helper: exchange contiguous data. Sends sendData, receives into.
template<class Container >
static void exchangeSizes (const Container &sendData, labelList &sizes, const label comm=UPstream::worldComm)
Helper: exchange sizes of sendData. sendData is the data per.
template<class Container , class T >
static void exchange (const UList< Container > &sendData, List< Container > &recvData, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool block=true)
Exchange contiguous data. Sends sendData, receives into.
Static Public Member Functions inherited from UPstream
static label allocateCommunicator (const label parent, const labelList &subRanks, const bool doPstream=true)
Allocate a new communicator.
static void freeCommunicator (const label communicator, const bool doPstream=true)
Free a previously allocated communicator.
static void freeCommunicators (const bool doPstream)
Free all communicators.
static int baseProcNo (const label myComm, const int procID)
Return physical processor number (i.e. processor number in.
static label procNo (const label comm, const int baseProcID)
Return processor number in communicator (given physical processor.
static label procNo (const label myComm, const label currentComm, const int currentProcID)
Return processor number in communicator (given processor number.
static void addValidParOptions (HashTable< string > &validParOptions)
Add the valid option this type of communications library.
static bool init (int &argc, char **&argv)
Initialisation function called from main.
static label nRequests ()
Get number of outstanding requests.
static void resetRequests (const label sz)
Truncate number of outstanding requests.
static void waitRequests (const label start=0)
Wait until all requests (from start onwards) have finished.
static void waitRequest (const label i)
Wait until request i has finished.
static bool finishedRequest (const label i)
Non-blocking comms: has request i finished?
static int allocateTag (const char *)
static int allocateTag (const word &)
static void freeTag (const char *, const int tag)
static void freeTag (const word &, const int tag)
static bool & parRun ()
Is this a parallel run?
static label nProcs (const label communicator=0)
Number of processes in parallel run.
static int masterNo ()
Process index of the master.
static bool master (const label communicator=0)
Am I the master process.
static int myProcNo (const label communicator=0)
Number of this process (starting from masterNo() = 0)
static label parent (const label communicator)
static List< int > & procID (label communicator)
Process ID of given process index.
static int firstSlave ()
Process index of first slave.
static int lastSlave (const label communicator=0)
Process index of last slave.
static const List< commsStruct > & linearCommunication (const label communicator=0)
Communication schedule for linear all-to-master (proc 0)
static const List< commsStruct > & treeCommunication (const label communicator=0)
Communication schedule for tree all-to-master (proc 0)
static int & msgType ()
Message tag of standard messages.
static void exit (int errnum=1)
Exit program.
static void abort ()
Abort program.
static void allToAll (const labelUList &sendData, labelUList &recvData, const label communicator=0)
Exchange label with all processors (in the communicator).
Protected Attributes
DynamicList< char > buf_
Transfer buffer.
Protected Attributes inherited from UPstream
commsTypes commsType_
Communications type of this stream.
Additional Inherited Members
Public Types inherited from UPstream
enum commsTypes { blocking, scheduled, nonBlocking }
Types of communications.
Static Public Attributes inherited from UPstream
static const NamedEnum< commsTypes, 3 > commsTypeNames
static bool floatTransfer
Should compact transfer be used in which floats replace doubles.
static int nProcsSimpleSum
Number of processors at which the sum algorithm changes from linear.
static commsTypes defaultCommsType
Default commsType.
static int nPollProcInterfaces
Number of polling cycles in processor updates.
static label worldComm
Default communicator (all processors)
static label warnComm
Debugging: warn for use of any communicator differing from warnComm.
Detailed Description
Inter-processor communications stream.
Source files
Pstream.H
Pstream.C
gatherScatter.C
combineGatherScatter.C
gatherScatterList.C
exchange.C
Definition at line 53 of file Pstream.H.
Constructor & Destructor Documentation
Pstream (const commsTypes commsType, const label bufSize = 0) inline
Construct given optional buffer size.
Definition at line 75 of file Pstream.H.
References Pstream::combineGather(), Pstream::combineScatter(), Pstream::exchange(), Pstream::exchangeSizes(), Pstream::gather(), Pstream::gatherList(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), UPstream::msgType(), Pstream::scatter(), Pstream::scatterList(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), Foam::T(), and UPstream::worldComm.
Member Function Documentation
ClassName ("Pstream")
void gather (const List< commsStruct > & comms, T & Value, const BinaryOp & bop, const int tag, const label comm) static
Gather data. Apply bop to combine Value.
from different processors
Definition at line 47 of file gatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), forAll, UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), UIPstream::read(), UPstream::scheduled, Foam::T(), and UOPstream::write().
Referenced by Pstream::Pstream(), and Foam::reduce().
void gather (T & Value, const BinaryOp & bop, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 127 of file gatherScatter.C.
References UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, Pstream::scatter(), and UPstream::treeCommunication().
void scatter (const List< commsStruct > & comms, T & Value, const int tag, const label comm) static
Scatter data. Distribute without modification. Reverse of gather.
Definition at line 147 of file gatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), forAllReverse, UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), UIPstream::read(), UPstream::scheduled, Foam::T(), and UOPstream::write().
Referenced by Pstream::gather(), cachedRandom::globalGaussNormal(), cachedRandom::globalPosition(), cachedRandom::globalRandomise01(), cachedRandom::globalSample01(), IOdictionary::IOdictionary(), InflationInjection< CloudType >::parcelsToInject(), Pstream::Pstream(), regIOobject::read(), Foam::reduce(), Pstream::scatter(), patchInjectionBase::setPositionAndCell(), rigidBodyMotion::solve(), ParSortableList< Type >::sort(), hexRef8Data::sync(), sixDoFRigidBodyMotion::update(), and fileMonitor::updateStates().
void scatter (T & Value, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 223 of file gatherScatter.C.
References UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, Pstream::scatter(), and UPstream::treeCommunication().
void combineGather (const List< commsStruct > & comms, T & Value, const CombineOp & cop, const int tag, const label comm) static
Definition at line 45 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), Foam::endl(), forAll, Foam::Pout, Foam::read(), T, and write().
Referenced by Foam::combineReduce(), and Pstream::Pstream().
void combineGather (T & Value, const CombineOp & cop, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 139 of file combineGatherScatter.C.
References Pstream::combineGather(), and Pstream::combineScatter().
Referenced by Pstream::combineGather().
void combineScatter (const List< commsStruct > & comms, T & Value, const int tag, const label comm) static
Scatter data. Reverse of combineGather.
Definition at line 173 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), Foam::endl(), forAllReverse, Foam::Pout, Foam::read(), T, and write().
Referenced by Pstream::combineGather(), Foam::combineReduce(), and Pstream::Pstream().
void combineScatter (T & Value, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 254 of file combineGatherScatter.C.
References Pstream::listCombineGather().
void listCombineGather (const List< commsStruct > & comms, List< T > & Value, const CombineOp & cop, const int tag, const label comm) static
Definition at line 273 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UList< T >::begin(), UPstream::commsStruct::below(), UList< T >::byteSize(), Foam::endl(), forAll, Foam::Pout, Foam::read(), List< T >::size(), and write().
Referenced by meshRefinement::balance(), forces::calcForcesMoment(), viewFactor::calculate(), Pstream::combineScatter(), patchInjection::correct(), patchProbes::findElements(), mappedPatchBase::findSamples(), injectionModelList::info(), meshRefinement::mergeBaffles(), ifEqEqOp< value >::operator()(), nearestEqOp::operator()(), patchInjection::patchInjectedMassTotals(), meshRefinement::printMeshInfo(), Pstream::Pstream(), patchProbes::sample(), probes::sample(), fvMeshSubset::setLargeCellSubset(), patchInjectionBase::updateMesh(), fileMonitor::updateStates(), and histogram::write().
void listCombineGather (List< T > & Value, const CombineOp & cop, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 374 of file combineGatherScatter.C.
References Pstream::listCombineScatter().
void listCombineScatter (const List< commsStruct > & comms, List< T > & Value, const int tag, const label comm) static
Scatter data. Reverse of combineGather.
Definition at line 408 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UList< T >::begin(), UPstream::commsStruct::below(), UList< T >::byteSize(), Foam::endl(), forAllReverse, Foam::Pout, Foam::read(), and write().
Referenced by meshRefinement::balance(), forces::calcForcesMoment(), viewFactor::calculate(), patchProbes::findElements(), mappedPatchBase::findSamples(), Pstream::listCombineGather(), meshRefinement::mergeBaffles(), ifEqEqOp< value >::operator()(), nearestEqOp::operator()(), meshRefinement::printMeshInfo(), Pstream::Pstream(), patchProbes::sample(), probes::sample(), fvMeshSubset::setLargeCellSubset(), patchInjectionBase::updateMesh(), and fileMonitor::updateStates().
void listCombineScatter (List< T > & Value, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 489 of file combineGatherScatter.C.
References Pstream::mapCombineGather().
void mapCombineGather (const List< commsStruct > & comms, Container & Values, const CombineOp & cop, const int tag, const label comm) static
Definition at line 520 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), Foam::endl(), forAll, and Foam::Pout.
Referenced by extrudePatchMesh::extrudePatchMesh(), Pstream::listCombineScatter(), ListPlusEqOp< T, Size >::operator()(), Pstream::Pstream(), and meshRefinement::zonify().
void mapCombineGather (Container & Values, const CombineOp & cop, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 587 of file combineGatherScatter.C.
References Pstream::mapCombineScatter().
void mapCombineScatter (const List< commsStruct > & comms, Container & Values, const int tag, const label comm) static
Scatter data. Reverse of combineGather.
Definition at line 621 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), Foam::endl(), forAllReverse, and Foam::Pout.
Referenced by extrudePatchMesh::extrudePatchMesh(), Pstream::mapCombineGather(), ListPlusEqOp< T, Size >::operator()(), Pstream::Pstream(), and meshRefinement::zonify().
void mapCombineScatter (Container & Values, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 672 of file combineGatherScatter.C.
void gatherList (const List< commsStruct > & comms, List< T > & Values, const int tag, const label comm) static
Gather data but keep individual values separate.
Definition at line 49 of file gatherScatterList.C.
References Foam::abort(), UPstream::commsStruct::above(), UPstream::commsStruct::allBelow(), UList< T >::begin(), UPstream::commsStruct::below(), UList< T >::byteSize(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), Foam::Pout, UIPstream::read(), UPstream::scheduled, List< T >::size(), and UOPstream::write().
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkParallelSync(), mappedPatchBase::collectSamples(), fieldValue::combineFields(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), Pstream::gatherList(), globalIndex::globalIndex(), NamedEnum< Enum, nEnum >::names(), lessProcPatches::operator()(), InflationInjection< CloudType >::parcelsToInject(), Pstream::Pstream(), fvMeshSubset::setLargeCellSubset(), ParSortableList< Type >::sort(), and externalCoupledTemperatureMixedFvPatchScalarField::transferData().
void gatherList (List< T > & Values, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 190 of file gatherScatterList.C.
References Pstream::gatherList(), UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, Pstream::scatterList(), and UPstream::treeCommunication().
void scatterList (const List< commsStruct > & comms, List< T > & Values, const int tag, const label comm) static
Scatter data. Reverse of gatherList.
Definition at line 205 of file gatherScatterList.C.
References Foam::abort(), UPstream::commsStruct::above(), UPstream::commsStruct::allNotBelow(), UPstream::commsStruct::below(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, forAllReverse, UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), Foam::Pout, UIPstream::read(), UPstream::scheduled, List< T >::size(), and UOPstream::write().
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkParallelSync(), mappedPatchBase::collectSamples(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), Pstream::gatherList(), globalIndex::globalIndex(), NamedEnum< Enum, nEnum >::names(), lessProcPatches::operator()(), Pstream::Pstream(), Pstream::scatterList(), and fvMeshSubset::setLargeCellSubset().
void scatterList (List< T > & Values, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 325 of file gatherScatterList.C.
References UPstream::linearCommunication(), UPstream::nProcs(), UPstream::nProcsSimpleSum, Pstream::scatterList(), and UPstream::treeCommunication().
void exchange (const UList< Container > & sendData, const labelUList & recvSizes, List< Container > & recvData, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool block = true) static
Helper: exchange contiguous data. Sends sendData, receives into.
recvData. If block=true will wait for all transfers to finish.
Definition at line 38 of file exchange.C.
References Foam::abort(), Pstream::exchangeSizes(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::read(), List< T >::setSize(), UList< T >::size(), T, and write().
Referenced by Pstream::exchangeSizes(), and Pstream::Pstream().
void exchangeSizes (const Container & sendData, labelList & sizes, const label comm = UPstream::worldComm) static
Helper: exchange sizes of sendData. sendData is the data per.
processor (in the communicator). Returns sizes of sendData on the sending processor.
Definition at line 139 of file exchange.C.
References Foam::abort(), Pstream::exchange(), Foam::FatalError, FatalErrorInFunction, forAll, and List< T >::setSize().
Referenced by Pstream::exchange(), PstreamBuffers::finishedSends(), and Pstream::Pstream().
void exchange (const UList< Container > & sendData, List< Container > & recvData, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool block = true) static
Exchange contiguous data. Sends sendData, receives into.
recvData. Determines sizes to receive. If block=true will wait for all transfers to finish.
Definition at line 166 of file exchange.C.
Member Data Documentation
DynamicList<char> buf_ protected
Transfer buffer.
Definition at line 63 of file Pstream.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/Pstream.H
src/OpenFOAM/db/IOstreams/Pstreams/combineGatherScatter.C
src/OpenFOAM/db/IOstreams/Pstreams/exchange.C
src/OpenFOAM/db/IOstreams/Pstreams/gatherScatter.C
src/OpenFOAM/db/IOstreams/Pstreams/gatherScatterList.C