OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PressureGradientForce< CloudType > Class Template Reference
Calculates particle pressure gradient force.
Public Member Functions
TypeName ("pressureGradient")
Runtime type information.
PressureGradientForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType=typeName)
Construct from mesh.
PressureGradientForce (const PressureGradientForce &pgf)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~PressureGradientForce ()
Destructor.
const interpolation< vector > & DUcDtInterp () const
Return the rate of change of carrier phase velocity interpolator.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
Protected Attributes
const word UName_
Name of velocity field.
autoPtr< interpolation< vector > > DUcDtInterpPtr_
Rate of change of carrier phase velocity interpolator.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::PressureGradientForce< CloudType >
Calculates particle pressure gradient force.
Source files
PressureGradientForce.H
PressureGradientForceI.H
PressureGradientForce.C
Definition at line 52 of file PressureGradientForce.H.
Constructor & Destructor Documentation
PressureGradientForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const word & forceType = typeName)
Construct from mesh.
Definition at line 34 of file PressureGradientForce.C.
PressureGradientForce (const PressureGradientForce< CloudType > & pgf)
Construct copy.
Definition at line 49 of file PressureGradientForce.C.
~PressureGradientForce () virtual
Destructor.
Definition at line 62 of file PressureGradientForce.C.
Referenced by PressureGradientForce< CloudType >::clone().
Member Function Documentation
TypeName ("pressureGradient")
Runtime type information.
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from ParticleForce< CloudType >.
Reimplemented in VirtualMassForce< CloudType >.
Definition at line 88 of file PressureGradientForce.H.
References PressureGradientForce< CloudType >::cacheFields(), PressureGradientForce< CloudType >::calcCoupled(), PressureGradientForce< CloudType >::DUcDtInterp(), PressureGradientForce< CloudType >::massAdd(), p, Foam::Re(), and PressureGradientForce< CloudType >::~PressureGradientForce().
const Foam::interpolation< Foam::vector > & DUcDtInterp () const inline
Return the rate of change of carrier phase velocity interpolator.
Definition at line 30 of file PressureGradientForceI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by PressureGradientForce< CloudType >::clone().
void cacheFields (const bool store) virtual
Cache fields.
Reimplemented from ParticleForce< CloudType >.
Reimplemented in VirtualMassForce< CloudType >.
Definition at line 69 of file PressureGradientForce.C.
References PressureGradientForce< CloudType >::calcCoupled(), Foam::fvc::ddt(), Foam::fvc::grad(), and mesh.
Referenced by PressureGradientForce< CloudType >::clone().
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the non-coupled force.
Reimplemented from ParticleForce< CloudType >.
Reimplemented in VirtualMassForce< CloudType >.
Definition at line 120 of file PressureGradientForce.C.
References PressureGradientForce< CloudType >::massAdd(), forceSuSp::Su(), and Foam::Zero.
Referenced by PressureGradientForce< CloudType >::cacheFields(), and PressureGradientForce< CloudType >::clone().
Foam::scalar massAdd (const typename CloudType::parcelType & p, const scalar mass) const virtual
Return the added mass.
Reimplemented from ParticleForce< CloudType >.
Reimplemented in VirtualMassForce< CloudType >.
Definition at line 141 of file PressureGradientForce.C.
Referenced by PressureGradientForce< CloudType >::calcCoupled(), and PressureGradientForce< CloudType >::clone().
Member Data Documentation
const word UName_ protected
Name of velocity field.
Definition at line 61 of file PressureGradientForce.H.
autoPtr<interpolation<vector> > DUcDtInterpPtr_ protected
Rate of change of carrier phase velocity interpolator.
Definition at line 64 of file PressureGradientForce.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/PressureGradient/PressureGradientForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/PressureGradient/PressureGradientForce.C
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/PressureGradient/PressureGradientForceI.H