OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
processorFvPatchField< Type > Class Template Reference
Boundary Conditions » Coupled boundary Conditions
This boundary condition enables processor communication across patches.
Public Member Functions
TypeName (processorFvPatch::typeName_())
Runtime type information.
processorFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
processorFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
processorFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
processorFvPatchField (const processorFvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given processorFvPatchField onto a new patch.
processorFvPatchField (const processorFvPatchField< Type > &)
Construct as copy.
virtual tmp< fvPatchField< Type > > clone () const
Construct and return a clone.
processorFvPatchField (const processorFvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< Type > > clone (const DimensionedField< Type, volMesh > &iF) const
Construct and return a clone setting internal field reference.
~processorFvPatchField ()
Destructor.
virtual bool coupled () const
Return true if running parallel.
virtual tmp< Field< Type > > patchNeighbourField () const
Return neighbour field given internal field.
virtual void initEvaluate (const Pstream::commsTypes commsType)
Initialise the evaluation of the patch field.
virtual void evaluate (const Pstream::commsTypes commsType)
Evaluate the patch field.
virtual tmp< Field< Type > > snGrad (const scalarField &deltaCoeffs) const
Return patch-normal gradient.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &result, const scalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
virtual void updateInterfaceMatrix (scalarField &result, const scalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
Update result field based on interface functionality.
virtual void initInterfaceMatrixUpdate (Field< Type > &result, const Field< Type > &psiInternal, const scalarField &coeffs, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
virtual void updateInterfaceMatrix (Field< Type > &result, const Field< Type > &psiInternal, const scalarField &coeffs, const Pstream::commsTypes commsType) const
Update result field based on interface functionality.
virtual label comm () const
Processor coupled interface functions.
virtual int myProcNo () const
Return processor number.
virtual int neighbProcNo () const
Return neigbour processor number.
virtual bool doTransform () const
Does the patch field perform the transfromation.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual int rank () const
Return rank of component for transform.
template<>
void initInterfaceMatrixUpdate (scalarField &, const scalarField &psiInternal, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
template<>
void updateInterfaceMatrix (scalarField &result, const scalarField &, const scalarField &coeffs, const direction, const Pstream::commsTypes commsType) const
Update result field based on interface functionality.
template<>
void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
template<>
void updateInterfaceMatrix (scalarField &result, const scalarField &, const scalarField &coeffs, const direction, const Pstream::commsTypes commsType) const
Update result field based on interface functionality.
Public Member Functions inherited from processorLduInterfaceField
TypeName ("processorLduInterfaceField")
Runtime type information.
processorLduInterfaceField ()
Construct given coupled patch.
virtual ~processorLduInterfaceField ()
Destructor.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &f, const direction cmpt) const
Transform given patch component field.
Public Member Functions inherited from coupledFvPatchField< Type >
TypeName (coupledFvPatch::typeName_())
Runtime type information.
coupledFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
coupledFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
coupledFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
coupledFvPatchField (const coupledFvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given coupledFvPatchField onto a new patch.
coupledFvPatchField (const coupledFvPatchField< Type > &)
Construct as copy.
coupledFvPatchField (const coupledFvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< Field< Type > > snGrad () const
Return patch-normal gradient.
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< scalarField > &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< scalarField > &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs (const scalarField &deltaCoeffs) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs (const scalarField &deltaCoeffs) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from LduInterfaceField< Type >
TypeName ("LduInterfaceField")
Runtime type information.
LduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~LduInterfaceField ()
Destructor.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
Public Member Functions inherited from fvPatchField< Type >
TypeName ("fvPatchField")
Runtime type information.
declareRunTimeSelectionTable (tmp, fvPatchField, patch,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvPatchField, patchMapper,(const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict),(p, iF, dict))
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Type &value)
Construct from patch, internal field and value.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const word &patchType)
Construct from patch and internal field and patch type.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &, const bool valueRequired=false)
Construct from patch, internal field and dictionary.
fvPatchField (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fvPatchField onto a new patch.
fvPatchField (const fvPatchField< Type > &)
Construct as copy.
fvPatchField (const fvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual ~fvPatchField ()
Destructor.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool assignable () const
Return true if the value of the patch field.
const objectRegistry & db () const
Return local objectRegistry.
const fvPatch & patch () const
Return patch.
const DimensionedField< Type, volMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
bool updated () const
Return true if the boundary condition has already been updated.
bool manipulatedMatrix () const
Return true if the matrix has already been manipulated.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchField< Type > &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void updateWeightedCoeffs (const scalarField &weights)
Update the coefficients associated with the patch field.
virtual tmp< Field< Type > > patchInternalField () const
Return internal field next to patch as patch field.
virtual void patchInternalField (Field< Type > &) const
Return internal field next to patch as patch field.
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< Field< scalar >> &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< Field< scalar >> &) const
Return the matrix source coefficients corresponding to the.
virtual void manipulateMatrix (fvMatrix< Type > &matrix)
Manipulate matrix.
virtual void manipulateMatrix (fvMatrix< Type > &matrix, const scalarField &weights)
Manipulate matrix with given weights.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
void check (const fvPatchField< Type > &) const
Check fvPatchField<Type> against given fvPatchField<Type>
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvPatchField< Type > &)
virtual void operator+= (const fvPatchField< Type > &)
virtual void operator-= (const fvPatchField< Type > &)
virtual void operator*= (const fvPatchField< scalar > &)
virtual void operator/= (const fvPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const fvPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &pf)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Additional Inherited Members
Public Types inherited from fvPatchField< Type >
typedef fvPatch Patch
typedef calculatedFvPatchField< Type > Calculated
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from fvPatchField< Type >
static tmp< fvPatchField< Type > > New (const word &, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const word &, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static tmp< fvPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatch &)
Return a pointer to a new calculatedFvPatchField created on.
template<class Type2 >
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &)
Return a pointer to a new calculatedFvPatchField created on.
static const word & calculatedType ()
Return the type of the calculated for of fvPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes inherited from fvPatchField< Type >
static int disallowGenericFvPatchField
Debug switch to disallow the use of genericFvPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::processorFvPatchField< Type >
This boundary condition enables processor communication across patches.
Patch usage
Example of the boundary condition specification:
myPatch
{
    type            processor;
}
Source files
processorFvPatchField.H
processorFvPatchField.C
Definition at line 64 of file processorFvPatchField.H.
Constructor & Destructor Documentation
processorFvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file processorFvPatchField.C.
Referenced by processorFvPatchField< Type >::clone(), and processorFvPatchField< Type >::processorFvPatchField().
processorFvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const Field< Type > & f)
Construct from patch and internal field and patch field.
Definition at line 53 of file processorFvPatchField.C.
References processorFvPatchField< Type >::processorFvPatchField().
processorFvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 108 of file processorFvPatchField.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and processorFvPatchField< Type >::processorFvPatchField().
processorFvPatchField (const processorFvPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given processorFvPatchField onto a new patch.
Definition at line 72 of file processorFvPatchField.C.
References Foam::abort(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, processorFvPatchField< Type >::processorFvPatchField(), and lduInterfaceField::ready().
processorFvPatchField (const processorFvPatchField< Type > & ptf)
Construct as copy.
Definition at line 140 of file processorFvPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, processorFvPatchField< Type >::processorFvPatchField(), and processorFvPatchField< Type >::ready().
processorFvPatchField (const processorFvPatchField< Type > & ptf, const DimensionedField< Type, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 165 of file processorFvPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and lduInterfaceField::ready().
~processorFvPatchField ()
Destructor.
Definition at line 191 of file processorFvPatchField.C.
Referenced by processorFvPatchField< Type >::clone().
Member Function Documentation
TypeName (processorFvPatch::typeName_())
Runtime type information.
virtual tmp<fvPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Implements coupledFvPatchField< Type >.
Reimplemented in processorCyclicFvPatchField< Type >.
Definition at line 138 of file processorFvPatchField.H.
References processorFvPatchField< Type >::processorFvPatchField().
virtual tmp<fvPatchField<Type> > clone (const DimensionedField< Type, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Implements coupledFvPatchField< Type >.
Reimplemented in processorCyclicFvPatchField< Type >.
Definition at line 155 of file processorFvPatchField.H.
References processorFvPatchField< Type >::~processorFvPatchField().
virtual bool coupled () const inline virtual
Return true if running parallel.
Reimplemented from coupledFvPatchField< Type >.
Definition at line 175 of file processorFvPatchField.H.
References processorFvPatchField< Type >::evaluate(), processorFvPatchField< Type >::initEvaluate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), UPstream::parRun(), processorFvPatchField< Type >::patchNeighbourField(), processorFvPatchField< Type >::ready(), coupledFvPatchField< Type >::snGrad(), and processorFvPatchField< Type >::updateInterfaceMatrix().
Foam::tmp< Foam::Field< Type > > patchNeighbourField () const virtual
Return neighbour field given internal field.
Implements coupledFvPatchField< Type >.
Definition at line 199 of file processorFvPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and processorFvPatchField< Type >::initEvaluate().
Referenced by processorFvPatchField< Type >::coupled().
void initEvaluate (const Pstream::commsTypes commsType) virtual
Initialise the evaluation of the patch field.
Reimplemented from coupledFvPatchField< Type >.
Definition at line 214 of file processorFvPatchField.C.
References processorFvPatchField< Type >::evaluate(), Foam::read(), setSize(), and write().
Referenced by processorFvPatchField< Type >::coupled(), and processorFvPatchField< Type >::patchNeighbourField().
void evaluate (const Pstream::commsTypes commsType) virtual
Evaluate the patch field.
Reimplemented from coupledFvPatchField< Type >.
Definition at line 258 of file processorFvPatchField.C.
References coupledFvPatchField< Type >::snGrad(), and Foam::transform().
Referenced by processorFvPatchField< Type >::coupled(), and processorFvPatchField< Type >::initEvaluate().
Foam::tmp< Foam::Field< Type > > snGrad (const scalarField & deltaCoeffs) const virtual
Return patch-normal gradient.
Reimplemented from coupledFvPatchField< Type >.
Definition at line 295 of file processorFvPatchField.C.
References processorFvPatchField< Type >::initInterfaceMatrixUpdate().
bool ready () const virtual
Is all data available.
Reimplemented from lduInterfaceField.
Definition at line 542 of file processorFvPatchField.C.
Referenced by processorFvPatchField< Type >::coupled(), and processorFvPatchField< Type >::processorFvPatchField().
void initInterfaceMatrixUpdate (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Initialise neighbour matrix update.
Reimplemented from lduInterfaceField.
Definition at line 305 of file processorFvPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::read(), lduInterfaceField::updatedMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), and write().
Referenced by processorFvPatchField< Type >::coupled(), processorFvPatchField< Type >::snGrad(), and processorFvPatchField< Type >::updateInterfaceMatrix().
void updateInterfaceMatrix (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Update result field based on interface functionality.
Implements coupledFvPatchField< Type >.
Definition at line 361 of file processorFvPatchField.C.
References forAll, processorFvPatchField< Type >::initInterfaceMatrixUpdate(), and lduInterfaceField::updatedMatrix().
Referenced by processorFvPatchField< Type >::coupled(), and processorFvPatchField< Type >::initInterfaceMatrixUpdate().
void initInterfaceMatrixUpdate (Field< Type > & result, const Field< Type > & psiInternal, const scalarField & coeffs, const Pstream::commsTypes commsType) const virtual
Initialise neighbour matrix update.
Reimplemented from LduInterfaceField< Type >.
Definition at line 425 of file processorFvPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::read(), lduInterfaceField::updatedMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), and write().
void updateInterfaceMatrix (Field< Type > & result, const Field< Type > & psiInternal, const scalarField & coeffs, const Pstream::commsTypes commsType) const virtual
Update result field based on interface functionality.
Implements coupledFvPatchField< Type >.
Definition at line 480 of file processorFvPatchField.C.
References forAll, and lduInterfaceField::updatedMatrix().
virtual label comm () const inline virtual
Processor coupled interface functions.
Return communicator used for comms
Implements processorLduInterfaceField.
Definition at line 250 of file processorFvPatchField.H.
References processorFvPatch::comm().
virtual int myProcNo () const inline virtual
Return processor number.
Implements processorLduInterfaceField.
Definition at line 256 of file processorFvPatchField.H.
References processorFvPatch::myProcNo().
virtual int neighbProcNo () const inline virtual
Return neigbour processor number.
Implements processorLduInterfaceField.
Definition at line 262 of file processorFvPatchField.H.
References processorFvPatch::neighbProcNo().
virtual bool doTransform () const inline virtual
Does the patch field perform the transfromation.
Implements processorLduInterfaceField.
Reimplemented in processorCyclicFvPatchField< Type >.
Definition at line 268 of file processorFvPatchField.H.
References processorFvPatch::parallel().
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements processorLduInterfaceField.
Reimplemented in processorCyclicFvPatchField< Type >.
Definition at line 274 of file processorFvPatchField.H.
References processorFvPatch::forwardT().
virtual int rank () const inline virtual
Return rank of component for transform.
Implements processorLduInterfaceField.
Definition at line 280 of file processorFvPatchField.H.
void initInterfaceMatrixUpdate (scalarField & , const scalarField & , const scalarField & , const direction , const Pstream::commsTypes commsType) const virtual
Initialise neighbour matrix update.
Reimplemented from lduInterfaceField.
Definition at line 37 of file processorFvPatchScalarField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, UPstream::floatTransfer, UPstream::nonBlocking, UPstream::nRequests(), UIPstream::read(), lduInterfaceField::updatedMatrix(), processorFvPatchField< Type >::updateInterfaceMatrix(), and UOPstream::write().
void updateInterfaceMatrix (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction , const Pstream::commsTypes commsType) const virtual
Update result field based on interface functionality.
Implements coupledFvPatchField< Type >.
Definition at line 93 of file processorFvPatchScalarField.C.
References UPstream::floatTransfer, forAll, UPstream::nonBlocking, UPstream::nRequests(), lduInterfaceField::updatedMatrix(), and UPstream::waitRequest().
void initInterfaceMatrixUpdate (scalarField & , const scalarField & , const scalarField & , const direction , const Pstream::commsTypes commsType) const virtual
Initialise neighbour matrix update.
Reimplemented from lduInterfaceField.
void updateInterfaceMatrix (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction , const Pstream::commsTypes commsType) const virtual
Update result field based on interface functionality.
Implements coupledFvPatchField< Type >.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/constraint/processor/processorFvPatchField.H
src/finiteVolume/fields/fvPatchFields/constraint/processor/processorFvPatchField.C