OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pressureDirectedInletOutletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This velocity inlet/outlet boundary condition is applied to pressure boundaries where the pressure is specified. A zero-gradient condtion is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with the specified inlet direction.
Public Member Functions
TypeName ("pressureDirectedInletOutletVelocity")
Runtime type information.
pressureDirectedInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
pressureDirectedInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: this patch field is altered by assignment.
const word & rhoName () const
Return the name of rho.
word & rhoName ()
Return reference to the name of rho to allow adjustment.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition is applied to pressure boundaries where the pressure is specified. A zero-gradient condtion is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with the specified inlet direction.
Patch usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
inletDirection inlet direction per patch face yes
Example of the boundary condition specification:
    myPatch
    {
        type            pressureDirectedInletOutletVelocity;
        phi             phi;
        rho             rho;
        inletDirection  uniform (1 0 0);
        value           uniform 0;
    }
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux with specified direction
See also
Foam::mixedFvPatchVectorField
Source files
pressureDirectedInletOutletVelocityFvPatchVectorField.H
pressureDirectedInletOutletVelocityFvPatchVectorField.C
Definition at line 105 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureDirectedInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References Foam::Zero.
Referenced by pressureDirectedInletOutletVelocityFvPatchVectorField::clone(), and pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField().
pressureDirectedInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 70 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField(), fvPatch::size(), vectorField(), and Foam::Zero.
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
pressureDirectedInletOutletVelocityFvPatchVectorField onto a new patch
Definition at line 54 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField().
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField & pivpvf)
Construct as copy.
Definition at line 90 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField().
pressureDirectedInletOutletVelocityFvPatchVectorField (const pressureDirectedInletOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 103 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References pressureDirectedInletOutletVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName ("pressureDirectedInletOutletVelocity")
Runtime type information.
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 162 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
References pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField().
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 182 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
References pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField().
virtual bool assignable () const inline virtual
Return true: this patch field is altered by assignment.
Definition at line 202 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
const word& rhoName () const inline
Return the name of rho.
Definition at line 211 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
word& rhoName () inline
Return reference to the name of rho to allow adjustment.
Definition at line 217 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
const word& phiName () const inline
Return the name of phi.
Definition at line 223 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 229 of file pressureDirectedInletOutletVelocityFvPatchVectorField.H.
References pressureDirectedInletOutletVelocityFvPatchVectorField::autoMap(), pressureDirectedInletOutletVelocityFvPatchVectorField::operator=(), pressureDirectedInletOutletVelocityFvPatchVectorField::rmap(), pressureDirectedInletOutletVelocityFvPatchVectorField::updateCoeffs(), and pressureDirectedInletOutletVelocityFvPatchVectorField::write().
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 118 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References pressureDirectedInletOutletVelocityFvPatchVectorField::rmap().
Referenced by pressureDirectedInletOutletVelocityFvPatchVectorField::phiName(), and pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField().
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 128 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References pressureDirectedInletOutletVelocityFvPatchVectorField::rmap().
Referenced by pressureDirectedInletOutletVelocityFvPatchVectorField::autoMap(), pressureDirectedInletOutletVelocityFvPatchVectorField::phiName(), and pressureDirectedInletOutletVelocityFvPatchVectorField::rmap().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 143 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, phi, Foam::pos(), and pressureDirectedInletOutletVelocityFvPatchVectorField::write().
Referenced by pressureDirectedInletOutletVelocityFvPatchVectorField::phiName().
void write (Ostream & os) const virtual
Write.
Definition at line 187 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by pressureDirectedInletOutletVelocityFvPatchVectorField::phiName(), and pressureDirectedInletOutletVelocityFvPatchVectorField::updateCoeffs().
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 202 of file pressureDirectedInletOutletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField().
Referenced by pressureDirectedInletOutletVelocityFvPatchVectorField::phiName().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureDirectedInletOutletVelocity/pressureDirectedInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureDirectedInletOutletVelocity/pressureDirectedInletOutletVelocityFvPatchVectorField.C