OpenFOAM-dev: PtrList< T > Class Template Reference 2
PtrList< T > Class Template Reference
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
Inherits UPtrList< T >.
Inherited by DictionaryBase< PtrList< T >, T >, blockMesh, fvBoundaryMesh, IOPtrList< T >, pointBoundaryMesh, and polyBoundaryMesh.
Public Member Functions
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< T > &)
Copy constructor.
template<class CloneArg >
PtrList (const PtrList< T > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< T >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &)
Construct as copy of SLPtrList<T>
template<class INew >
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (T *)
Append an element at the end of the list.
void append (const autoPtr< T > &)
void append (const tmp< T > &)
void transfer (PtrList< T > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< T > set (const label, T *)
Set element to given T* and return old element (can be NULL)
autoPtr< T > set (const label, const autoPtr< T > &)
Set element to given autoPtr<T> and return old element.
autoPtr< T > set (const label, const tmp< T > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< T > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Member Functions
template<class INew >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Friends
Istream & operator>> (Istream &, PtrList< T > &)
Read PtrList from Istream, discarding contents of existing PtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Detailed Description
template<class T>
class Foam::PtrList< T >
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
The element operator [] returns a reference to the object rather than a pointer.
Source files
PtrList.H
PtrListI.H
PtrList.C
PtrListIO.C
Definition at line 62 of file List.H.
Constructor & Destructor Documentation
PtrList ()
Null Constructor.
Definition at line 32 of file PtrList.C.
PtrList (const label s) explicit
Construct with size specified.
Definition at line 39 of file PtrList.C.
PtrList (const PtrList< T > & a)
Copy constructor.
Definition at line 46 of file PtrList.C.
References forAll.
PtrList (const PtrList< T > & a, const CloneArg & cloneArg)
Copy constructor with additional argument for clone.
Definition at line 59 of file PtrList.C.
References forAll.
PtrList (const Xfer< PtrList< T >> & lst)
Construct by transferring the parameter contents.
Definition at line 71 of file PtrList.C.
References PtrList< T >::transfer().
PtrList (PtrList< T > & a, bool reuse)
Construct as copy or re-use as specified.
Definition at line 78 of file PtrList.C.
References forAll.
PtrList (const SLPtrList< T > & sll) explicit
Construct as copy of SLPtrList<T>
Definition at line 93 of file PtrList.C.
References LList< SLListBase, T * >::begin(), LList< SLListBase, T * >::end(), and SLListBase::size().
PtrList (Istream & is, const INew & inewt)
Construct from Istream using given Istream constructor class.
Definition at line 160 of file PtrListIO.C.
References Foam::read().
PtrList (Istream & is)
Construct from Istream using default Istream constructor class.
Definition at line 167 of file PtrListIO.C.
References PtrList< T >::clear(), Foam::operator>>(), Foam::read(), and PtrList< T >::read().
~PtrList ()
Destructor.
Definition at line 116 of file PtrList.C.
References forAll.
Member Function Documentation
void read (Istream & is, const INew & inewt) protected
Read from Istream using given Istream constructor class.
Definition at line 36 of file PtrListIO.C.
References LList< SLListBase, T >::append(), LList< SLListBase, T >::begin(), LList< SLListBase, T >::end(), IOstream::eof(), Foam::exit(), IOstream::fatalCheck(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, token::info(), token::isLabel(), token::isPunctuation(), token::labelToken(), token::pToken(), Istream::putBack(), Istream::readBeginList(), Istream::readEndList(), s(), setSize(), SLListBase::size(), and T.
Referenced by IOPtrList< T >::IOPtrList(), and PtrList< T >::PtrList().
void setSize (const label newSize)
Reset size of PtrList. If extending the PtrList, new entries are.
set to NULL. If truncating the PtrList, removed entries are deleted
Definition at line 131 of file PtrList.C.
References Foam::abort(), PtrList< T >::clear(), Foam::FatalError, FatalErrorInFunction, Foam::name(), UPtrList< T >::size(), and Foam::T().
Referenced by fvMeshAdder::add(), polyMeshAdder::add(), cellTable::addCellZones(), fvMeshTools::addPatch(), polyMesh::addPatches(), polyMesh::addZones(), meshRefinement::appendPatch(), polyBoundaryMesh::checkParallelSync(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), FacePostProcessing< CloudType >::FacePostProcessing(), lduPrimitiveMesh::gather(), interRegionExplicitPorositySource::initialise(), fvMeshDistribute::mapExposedFaces(), fvMeshAdder::MapVolFields(), moleFractions< ThermoType >::moleFractions(), PtrList< T >::operator=(), patchInjection::patchInjection(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), Foam::preservePatchTypes(), PtrListDictionary< T >::PtrListDictionary(), functionObjectList::read(), polyMesh::readUpdate(), polyMesh::removeBoundary(), fvMesh::removeFvBoundary(), searchableSurfaces::searchableSurfaces(), GAMGSolver::solve(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), fvMeshTools::zeroPatchFields(), and ZoneMesh< ZoneType, MeshType >::ZoneMesh().
void resize (const label newSize) inline
Alias for setSize(const label)
Definition at line 32 of file PtrListI.H.
References setSize().
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
allocated entries
Definition at line 174 of file PtrList.C.
References forAll.
Referenced by functionObjectList::clear(), PtrList< T >::PtrList(), functionObjectList::read(), fvBoundaryMesh::readUpdate(), polyMesh::readUpdate(), polyMesh::removeBoundary(), fvMesh::removeFvBoundary(), decompositionMethod::setConstraints(), PtrList< T >::setSize(), and PtrList< T >::transfer().
void append (T * ptr) inline
Append an element at the end of the list.
Definition at line 39 of file PtrListI.H.
References setSize().
Referenced by singleProcessorFaceSetsConstraint::add(), PtrList< T >::append(), meshToMesh::interpolationMethodAMI(), and rigidBodyModel::join_().
void append (const autoPtr< T > & aptr) inline
Definition at line 48 of file PtrListI.H.
References PtrList< T >::append().
void append (const tmp< T > & t) inline
Definition at line 56 of file PtrListI.H.
void transfer (PtrList< T > & a)
Transfer the contents of the argument PtrList into this PtrList.
and annul the argument list
Definition at line 189 of file PtrList.C.
References PtrList< T >::clear().
Referenced by wallDistData< TransferType >::correct(), IOPtrList< T >::IOPtrList(), PtrList< T >::PtrList(), and functionObjectList::read().
Foam::Xfer< Foam::PtrList< T > > xfer () inline
Transfer contents to the Xfer container.
Definition at line 103 of file PtrListI.H.
References Foam::xferMove().
bool set (const label i) const inline
Is element set.
Definition at line 65 of file PtrListI.H.
Referenced by isoSurface::adaptPatchFields(), fvMeshAdder::add(), cellTable::addCellZones(), fvMeshTools::addPatch(), polyMesh::addPatches(), polyMesh::addZones(), meshRefinement::appendPatch(), fvFieldDecomposer::decomposeField(), boundaryMesh::deletePatch(), forAll(), lduPrimitiveMesh::gather(), surfaceZonesInfo::getAllClosedNamedSurfaces(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnclosedNamedSurfaces(), interRegionExplicitPorositySource::initialise(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), isoSurface::isoSurface(), LUscalarMatrix::LUscalarMatrix(), fvMeshDistribute::mapExposedFaces(), fvMeshAdder::MapVolFields(), pointBoundaryMesh::pointBoundaryMesh(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), Foam::preservePatchTypes(), functionObjectList::read(), polyMesh::readUpdate(), refinementSurfaces::refinementSurfaces(), refinementFeatures::regionEdgeTrees(), PtrListDictionary< T >::set(), PtrList< T >::set(), GAMGSolver::solve(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), and ZoneMesh< ZoneType, MeshType >::ZoneMesh().
Foam::autoPtr< T > set (const label i, T * ptr) inline
Set element to given T* and return old element (can be NULL)
Definition at line 72 of file PtrListI.H.
References PtrList< T >::set().
Foam::autoPtr< T > set (const label i, const autoPtr< T > & aptr) inline
Set element to given autoPtr<T> and return old element.
Definition at line 82 of file PtrListI.H.
References PtrList< T >::set().
Foam::autoPtr< T > set (const label i, const tmp< T > & t) inline
Set element to given tmp<T> and return old element.
Definition at line 93 of file PtrListI.H.
void reorder (const labelUList & oldToNew)
Reorders elements. Ordering does not have to be done in.
ascending or descending order. Reordering has to be unique. (is shuffle)
Definition at line 197 of file PtrList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::name(), Foam::nl, UPtrList< T >::size(), UList< T >::size(), and Foam::T().
Referenced by fvMeshTools::addPatch(), meshRefinement::addPatch(), fvMeshAdder::MapVolFields(), polyBoundaryMesh::reorder(), and fvMeshTools::reorderPatches().
void operator= (const PtrList< T > & a)
Assignment.
Definition at line 250 of file PtrList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::name(), PtrList< T >::setSize(), UPtrList< T >::size(), and Foam::T().
Referenced by IOPtrList< T >::IOPtrList(), and IOPtrList< T >::operator=().
Friends And Related Function Documentation
Istream& operator>> (Istream & , PtrList< T > &) friend
Read PtrList from Istream, discarding contents of existing PtrList.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/List/List.H
src/OpenFOAM/containers/Lists/PtrList/PtrList.H
src/OpenFOAM/containers/Lists/PtrList/PtrList.C
src/OpenFOAM/containers/Lists/PtrList/PtrListI.H
src/OpenFOAM/containers/Lists/PtrList/PtrListIO.C