OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
randomise Class Reference
Adds a random component to a field, with a given perturbation magnitude.
Public Member Functions
TypeName ("randomise")
Runtime type information.
randomise ()
Construct null.
virtual ~randomise ()
Destructor.
Public Member Functions inherited from calcType
TypeName ("calcType")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, calcType, dictionary,(),())
calcType ()
Construct null.
virtual ~calcType ()
Destructor.
void tryInit ()
Initialise - typically setting static variables,.
void tryPreCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Pre-time loop calculations.
void tryCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Time loop calculations.
void tryPostCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Post-time loop calculations.
Protected Member Functions
virtual void init ()
Initialise - typically setting static variables,.
virtual void preCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Pre-time loop calculations.
virtual void calc (const argList &args, const Time &runTime, const fvMesh &mesh)
Time loop calculations.
template<class Type >
void writeRandomField (const IOobject &header, const scalar pertMag, Random &rand, const fvMesh &mesh, bool &processed)
Write component fields.
Protected Member Functions inherited from calcType
virtual void postCalc (const argList &args, const Time &runTime, const fvMesh &mesh)
Post-time loop calculations.
Additional Inherited Members
Static Public Member Functions inherited from calcType
static autoPtr< calcType > New (const word &calcTypeName)
Detailed Description
Adds a random component to a field, with a given perturbation magnitude.
Source files
randomise.H
randomise.C
Definition at line 52 of file randomise.H.
Constructor & Destructor Documentation
randomise ()
Construct null.
Definition at line 43 of file randomise.C.
~randomise () virtual
Destructor.
Definition at line 51 of file randomise.C.
Member Function Documentation
void init () protected virtual
Initialise - typically setting static variables,.
e.g. command line arguments
Reimplemented from calcType.
Definition at line 57 of file randomise.C.
References argList::validArgs.
void preCalc (const argList & args, const Time & runTime, const fvMesh & mesh) protected virtual
Pre-time loop calculations.
Reimplemented from calcType.
Definition at line 66 of file randomise.C.
void calc (const argList & args, const Time & runTime, const fvMesh & mesh) protected virtual
Time loop calculations.
Reimplemented from calcType.
Definition at line 75 of file randomise.C.
References argList::argRead(), Foam::endl(), Foam::exit(), Foam::FatalError, Foam::Info, mesh, IOobject::MUST_READ, Foam::nl, and Time::timeName().
void writeRandomField (const IOobject & header, const scalar pertMag, Random & rand, const fvMesh & mesh, bool & processed) protected
Write component fields.
Definition at line 28 of file writeRandomField.C.
References Foam::endl(), forAll, IOobject::headerClassName(), Foam::Info, Foam::mag(), mesh, IOobject::name(), Random::randomise(), fvMesh::time(), Time::timeName(), and Ostream::write().
TypeName ("randomise")
Runtime type information.
The documentation for this class was generated from the following files:
src/postProcessing/foamCalcFunctions/field/randomise/randomise.H
src/postProcessing/foamCalcFunctions/field/randomise/randomise.C
src/postProcessing/foamCalcFunctions/field/randomise/writeRandomField.C