OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
probes Class Reference
FunctionObjects » Utility function objects
Set of locations to sample.
Classes
class fieldGroup
Class used for grouping field types.
Public Member Functions
TypeName ("probes")
Runtime type information.
probes (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~probes ()
Destructor.
virtual const word & name () const
Return name of the set of probes.
virtual const wordReList & fieldNames () const
Return names of fields to probe.
virtual const pointField & probeLocations () const
Return locations to probe.
virtual const point & probe (const label i) const
Return location for probe i.
const labelList & elements () const
Cells to be probed (obtained from the locations)
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Sample and write.
virtual void read (const dictionary &)
Read the probes.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
virtual void readUpdate (const polyMesh::readUpdateState state)
Update for changes of mesh due to readUpdate.
template<class Type >
tmp< Field< Type > > sample (const GeometricField< Type, fvPatchField, volMesh > &) const
Sample a volume field at all locations.
template<class Type >
tmp< Field< Type > > sample (const word &fieldName) const
Sample a single vol field on all sample locations.
template<class Type >
tmp< Field< Type > > sampleSurfaceFields (const word &fieldName) const
Sample a single scalar field on all sample locations.
template<class Type >
tmp< Field< Type > > sample (const GeometricField< Type, fvsPatchField, surfaceMesh > &) const
Sample a surface field at all locations.
template<class Type >
Foam::tmp< Foam::Field< Type > > sample (const GeometricField< Type, fvPatchField, volMesh > &vField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sample (const word &fieldName) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sample (const GeometricField< Type, fvsPatchField, surfaceMesh > &sField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleSurfaceFields (const word &fieldName) const
Public Member Functions inherited from Field< vector >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const vector &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< vector > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< vector >> &)
Construct by transferring the List contents.
Field (const UList< vector > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< vector > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< vector >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< vector > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
Field (const UList< vector > &mapF, const FieldMapper &map, const vector &defaultValue)
Construct by mapping from the given field.
Field (const UList< vector > &mapF, const FieldMapper &map, const UList< vector > &defaultValues)
Construct by mapping from the given field.
Field (const tmp< Field< vector >> &tmapF, const FieldMapper &map)
Construct by mapping from the given tmp field.
Field (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const vector &defaultValue)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< vector >> &tmapF, const FieldMapper &map, const UList< vector > &defaultValues)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< vector > &)
Construct as copy.
Field (Field< vector > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< vector >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< vector >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< vector > > clone () const
Clone.
void map (const UList< vector > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< vector > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< vector >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< vector > &mapF, const FieldMapper &map)
Map from the given field.
void map (const tmp< Field< vector >> &tmapF, const FieldMapper &map)
Map from the given tmp field.
void autoMap (const FieldMapper &map)
Map from self.
void rmap (const UList< vector > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< vector > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< vector >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
VSForm block (const label start) const
tmp< Field< vector > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< vector > &)
void operator= (const UList< vector > &)
void operator= (const SubField< vector > &)
void operator= (const tmp< Field< vector >> &)
void operator= (const vector &)
void operator= (const zero)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< vector > &)
void operator+= (const tmp< Field< vector >> &)
void operator+= (const vector &)
void operator-= (const UList< vector > &)
void operator-= (const tmp< Field< vector >> &)
void operator-= (const vector &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator*= (const scalar &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< vector >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const vector &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< vector > &)
Copy constructor.
List (const Xfer< List< vector >> &)
Construct by transferring the parameter contents.
List (List< vector > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< vector > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< vector, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< vector > &)
Construct as copy of PtrList<T>
List (const SLList< vector > &)
Construct as copy of SLList<T>
List (const UIndirectList< vector > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< vector > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< vector > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const vector &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const vector &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const vector &)
Append an element at the end of the list.
void append (const UList< vector > &)
Append a List at the end of this list.
void append (const UIndirectList< vector > &)
Append a UIndirectList at the end of this list.
void transfer (List< vector > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< vector, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< vector > &)
Transfer the contents of the argument List into this list.
Xfer< List< vector > > xfer ()
Transfer contents to the Xfer container.
vector & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< vector > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< vector > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< vector > &)
Assignment operator. Takes linear time.
void operator= (const SLList< vector > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< vector > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< vector > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const vector &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Protected Member Functions
void clearFieldGroups ()
Clear old field groups.
label appendFieldGroup (const word &fieldName, const word &fieldType)
Append fieldName to the appropriate group.
label classifyFields ()
Classify field types, returns the number of fields.
virtual void findElements (const fvMesh &)
Find cells and faces containing probes.
label prepare ()
Classify field type and Open/close file streams,.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< vector >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Attributes
word name_
Name of this set of probes,.
const fvMesh & mesh_
Const reference to fvMesh.
bool loadFromFiles_
Load fields from files (not from objectRegistry)
wordReList fieldSelection_
Names of fields to probe.
bool fixedLocations_
Fixed locations, default = yes.
word interpolationScheme_
Interpolation scheme name.
fieldGroup< scalar > scalarFields_
Categorized scalar/vector/tensor vol fields.
fieldGroup< vector > vectorFields_
fieldGroup< sphericalTensor > sphericalTensorFields_
fieldGroup< symmTensor > symmTensorFields_
fieldGroup< tensor > tensorFields_
fieldGroup< scalar > surfaceScalarFields_
Categorized scalar/vector/tensor surf fields.
fieldGroup< vector > surfaceVectorFields_
fieldGroup< sphericalTensor > surfaceSphericalTensorFields_
fieldGroup< symmTensor > surfaceSymmTensorFields_
fieldGroup< tensor > surfaceTensorFields_
labelList elementList_
labelList faceList_
HashPtrTable< OFstream > probeFilePtrs_
Current open files.
Additional Inherited Members
Public Types inherited from Field< vector >
typedef pTraits< vector >::cmptType cmptType
Component type.
typedef SubField< vector > subField
Declare type of subField.
Public Types inherited from List< vector >
typedef SubList< vector > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from Field< vector >
static const Field< vector > & null ()
Return a null field.
static tmp< Field< vector > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< vector >
static const List< vector > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes inherited from Field< vector >
static const char *const typeName
Detailed Description
Set of locations to sample.
Call write() to sample and write files.
Source files
probes.H
probes.C
Definition at line 66 of file probes.H.
Constructor & Destructor Documentation
probes (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 271 of file probes.C.
References Foam::read().
~probes () virtual
Destructor.
Definition at line 292 of file probes.C.
Member Function Documentation
void clearFieldGroups () protected
Clear old field groups.
Definition at line 34 of file probesGrouping.C.
References probes::appendFieldGroup(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), probes::scalarFields_, probes::sphericalTensorFields_, probes::surfaceScalarFields_, probes::surfaceSphericalTensorFields_, probes::surfaceSymmTensorFields_, probes::surfaceTensorFields_, probes::surfaceVectorFields_, probes::symmTensorFields_, probes::tensorFields_, and probes::vectorFields_.
Referenced by probes::classifyFields().
Foam::label appendFieldGroup (const word & fieldName, const word & fieldType) protected
Append fieldName to the appropriate group.
Definition at line 51 of file probesGrouping.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), probes::scalarFields_, probes::sphericalTensorFields_, probes::surfaceScalarFields_, probes::surfaceSphericalTensorFields_, probes::surfaceSymmTensorFields_, probes::surfaceTensorFields_, probes::surfaceVectorFields_, probes::symmTensorFields_, probes::tensorFields_, Field< Type >::typeName, and probes::vectorFields_.
Referenced by probes::classifyFields(), and probes::clearFieldGroups().
Foam::label classifyFields () protected
Classify field types, returns the number of fields.
Definition at line 111 of file probesGrouping.C.
References probes::appendFieldGroup(), probes::clearFieldGroups(), probes::fieldSelection_, HashTable< T, Key, Hash >::find(), Foam::findStrings(), forAll, probes::loadFromFiles_, probes::mesh_, objectRegistry::sortedNames(), fvMesh::time(), Time::timeName(), and Foam::type().
void findElements (const fvMesh & mesh) protected virtual
Find cells and faces containing probes.
Reimplemented in patchProbes.
Definition at line 43 of file probes.C.
References primitiveMesh::cellCentres(), primitiveMesh::cells(), Foam::endl(), primitiveMesh::faceCentres(), polyMesh::findCell(), forAll, Foam::Info, Foam::mag(), UPstream::master(), UPstream::myProcNo(), Foam::Pout, Foam::reduce(), and WarningInFunction.
Foam::label prepare () protected
Classify field type and Open/close file streams,.
returns number of fields to sample
Definition at line 160 of file probes.C.
References IOstream::defaultPrecision(), polyMesh::defaultRegion, Foam::endl(), HashTable< T, Key, Hash >::erase(), forAll, forAllConstIter(), forAllIter, Foam::Info, HashSet< Key, Hash >::insert(), UPstream::master(), Foam::mkDir(), OFstream::name(), fileName::name(), Foam::nl, UPstream::parRun(), fileName::path(), and Foam::setw().
TypeName ("probes")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the set of probes.
Definition at line 220 of file probes.H.
References probes::name_.
virtual const wordReList& fieldNames () const inline virtual
Return names of fields to probe.
Definition at line 226 of file probes.H.
References probes::fieldSelection_.
virtual const pointField& probeLocations () const inline virtual
Return locations to probe.
Definition at line 232 of file probes.H.
virtual const point& probe (const label i) const inline virtual
Return location for probe i.
Definition at line 238 of file probes.H.
References UList< T >::operator[]().
const labelList& elements () const inline
Cells to be probed (obtained from the locations)
Definition at line 244 of file probes.H.
References probes::elementList_, UList< T >::end(), probes::execute(), probes::movePoints(), probes::read(), probes::timeSet(), probes::updateMesh(), and probes::write().
void execute () virtual
Execute, currently does nothing.
Definition at line 298 of file probes.C.
Referenced by probes::elements().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 302 of file probes.C.
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 306 of file probes.C.
Referenced by probes::elements().
void write () virtual
Sample and write.
Reimplemented in patchProbes.
Definition at line 310 of file probes.C.
Referenced by probes::elements().
void read (const dictionary & dict) virtual
Read the probes.
Reimplemented in patchProbes.
Definition at line 329 of file probes.C.
References dictionary::lookup(), dictionary::readIfPresent(), and WarningInFunction.
Referenced by probes::elements(), and patchProbes::read().
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Definition at line 353 of file probes.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), forAll, Foam::Info, mapPolyMesh::reverseCellMap(), and mapPolyMesh::reverseFaceMap().
Referenced by probes::elements().
void movePoints (const polyMesh &) virtual
Update for changes of mesh.
Definition at line 430 of file probes.C.
References Foam::endl(), and Foam::Info.
Referenced by probes::elements().
virtual void readUpdate (const polyMesh::readUpdateState state) inline virtual
Update for changes of mesh due to readUpdate.
Definition at line 271 of file probes.H.
References probes::sample(), and probes::sampleSurfaceFields().
tmp<Field<Type> > sample (const GeometricField< Type, fvPatchField, volMesh > &) const
Sample a volume field at all locations.
Referenced by isNotEqOp< T >::operator()(), probes::readUpdate(), and probes::sample().
tmp<Field<Type> > sample (const word & fieldName) const
Sample a single vol field on all sample locations.
tmp<Field<Type> > sampleSurfaceFields (const word & fieldName) const
Sample a single scalar field on all sample locations.
Referenced by probes::readUpdate().
tmp<Field<Type> > sample (const GeometricField< Type, fvsPatchField, surfaceMesh > &) const
Sample a surface field at all locations.
Foam::tmp<Foam::Field<Type> > sample (const GeometricField< Type, fvPatchField, volMesh > & vField) const
Definition at line 216 of file probesTemplates.C.
References forAll, Pstream::listCombineGather(), Pstream::listCombineScatter(), and tmp< T >::ref().
Foam::tmp<Foam::Field<Type> > sample (const word & fieldName) const
Definition at line 271 of file probesTemplates.C.
References probes::sample().
Foam::tmp<Foam::Field<Type> > sample (const GeometricField< Type, fvsPatchField, surfaceMesh > & sField) const
Definition at line 286 of file probesTemplates.C.
References forAll, Pstream::listCombineGather(), Pstream::listCombineScatter(), and tmp< T >::ref().
Foam::tmp<Foam::Field<Type> > sampleSurfaceFields (const word & fieldName) const
Definition at line 316 of file probesTemplates.C.
Member Data Documentation
word name_ protected
Name of this set of probes,.
Also used as the name of the probes directory.
Definition at line 93 of file probes.H.
Referenced by probes::fieldGroup< Foam::SphericalTensor >::fieldGroup(), and probes::name().
const fvMesh& mesh_ protected
Const reference to fvMesh.
Definition at line 96 of file probes.H.
Referenced by probes::classifyFields(), and patchProbes::sample().
bool loadFromFiles_ protected
Load fields from files (not from objectRegistry)
Definition at line 99 of file probes.H.
Referenced by probes::classifyFields().
wordReList fieldSelection_ protected
Names of fields to probe.
Definition at line 105 of file probes.H.
Referenced by probes::classifyFields(), and probes::fieldNames().
bool fixedLocations_ protected
Fixed locations, default = yes.
Note: set to false for moving mesh calations where locations should move with the mesh
Definition at line 110 of file probes.H.
word interpolationScheme_ protected
Interpolation scheme name.
Note: only possible when fixedLocations_ is true
Definition at line 114 of file probes.H.
fieldGroup<scalar> scalarFields_ protected
Categorized scalar/vector/tensor vol fields.
Definition at line 120 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
fieldGroup<vector> vectorFields_ protected
Definition at line 121 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
fieldGroup<sphericalTensor> sphericalTensorFields_ protected
Definition at line 122 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
fieldGroup<symmTensor> symmTensorFields_ protected
Definition at line 123 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
fieldGroup<tensor> tensorFields_ protected
Definition at line 124 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
fieldGroup<scalar> surfaceScalarFields_ protected
Categorized scalar/vector/tensor surf fields.
Definition at line 127 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
fieldGroup<vector> surfaceVectorFields_ protected
Definition at line 128 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
fieldGroup<sphericalTensor> surfaceSphericalTensorFields_ protected
Definition at line 129 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
fieldGroup<symmTensor> surfaceSymmTensorFields_ protected
Definition at line 130 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
fieldGroup<tensor> surfaceTensorFields_ protected
Definition at line 131 of file probes.H.
Referenced by probes::appendFieldGroup(), and probes::clearFieldGroups().
labelList elementList_ protected
Definition at line 134 of file probes.H.
Referenced by probes::elements(), and patchProbes::sample().
labelList faceList_ protected
Definition at line 137 of file probes.H.
HashPtrTable<OFstream> probeFilePtrs_ protected
Current open files.
Definition at line 140 of file probes.H.
The documentation for this class was generated from the following files:
src/sampling/probes/probes.H
src/sampling/probes/probes.C
src/sampling/probes/probesGrouping.C
src/sampling/probes/probesTemplates.C