OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
PrimitivePatch< Face, FaceList, PointField, PointType > Class Template Reference
A list of faces which address into the list of points.
Public Types
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Public Member Functions
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Detailed Description
template<class Face, template< class > class FaceList, class PointField, class PointType = point>
class Foam::PrimitivePatch< Face, FaceList, PointField, PointType >
A list of faces which address into the list of points.
The class is templated on the face type (e.g. triangle, polygon etc.) and on the list type of faces and points so that it can refer to existing lists using UList and const pointField& or hold the storage using List and pointField.
Source files
PrimitivePatch.H
PrimitivePatchAddressing.C
PrimitivePatchBdryPoints.C
PrimitivePatch.C
PrimitivePatchCheck.C
PrimitivePatchClear.C
PrimitivePatchEdgeLoops.C
PrimitivePatchLocalPointOrder.C
PrimitivePatchMeshData.C
PrimitivePatchMeshEdges.C
PrimitivePatchName.C
PrimitivePatchPointAddressing.C
PrimitivePatchProjectPoints.C
Definition at line 87 of file PrimitivePatch.H.
Member Typedef Documentation
typedef Face FaceType
Definition at line 97 of file PrimitivePatch.H.
typedef FaceList<Face> FaceListType
Definition at line 98 of file PrimitivePatch.H.
typedef PointField PointFieldType
Definition at line 99 of file PrimitivePatch.H.
Member Enumeration Documentation
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
Enumerator
MANIFOLD
OPEN
ILLEGAL
Definition at line 105 of file PrimitivePatch.H.
Constructor & Destructor Documentation
PrimitivePatch (const FaceList< Face > & faces, const Field< PointType > & points)
Construct from components.
Definition at line 39 of file PrimitivePatch.C.
Referenced by PrimitivePatch< Face, FaceList, PointField, PointType >::PrimitivePatch().
PrimitivePatch (const Xfer< FaceList< Face >> & faces, const Xfer< List< PointType >> & points)
Construct from components.
Definition at line 75 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::PrimitivePatch().
PrimitivePatch (FaceList< Face > & faces, Field< PointType > & points, const bool reuse)
Construct from components, reuse storage.
Definition at line 111 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::PrimitivePatch().
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > & pp)
Construct as copy.
Definition at line 148 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::~PrimitivePatch().
~PrimitivePatch () virtual
Destructor.
Definition at line 185 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::movePoints().
Referenced by PrimitivePatch< Face, FaceList, PointField, PointType >::PrimitivePatch().
Member Function Documentation
void clearOut ()
Definition at line 126 of file PrimitivePatchClear.C.
Referenced by PrimitivePatch< Face, FaceList, PointField, PointType >::clearPatchMeshAddr(), and processorPolyPatch::updateMesh().
void clearGeom ()
Definition at line 41 of file PrimitivePatchClear.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::clearTopology(), Foam::deleteDemandDrivenData(), Foam::endl(), and InfoInFunction.
Referenced by polyPatch::clearGeom(), and polyPatch::updateMesh().
void clearTopology ()
Definition at line 64 of file PrimitivePatchClear.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::clearPatchMeshAddr(), Foam::deleteDemandDrivenData(), Foam::endl(), and InfoInFunction.
Referenced by polyPatch::clearAddressing(), and PrimitivePatch< Face, FaceList, PointField, PointType >::clearGeom().
void clearPatchMeshAddr ()
Definition at line 104 of file PrimitivePatchClear.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::clearOut(), Foam::deleteDemandDrivenData(), Foam::endl(), and InfoInFunction.
Referenced by polyPatch::clearAddressing(), and PrimitivePatch< Face, FaceList, PointField, PointType >::clearTopology().
const Field<PointType>& points () const inline
Return reference to global points.
Definition at line 284 of file PrimitivePatch.H.
Referenced by booleanSurface::booleanSurface(), PatchTools::calcBounds(), Foam::meshTools::calcBoxPointNormals(), triSurfaceTools::calcInterpolationWeights(), addPatchCellLayer::calcSidePatch(), cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), PatchTools::checkOrientation(), searchableSurfaces::checkQuality(), triSurfaceTools::classify(), distributedTriSurfaceMesh::distribute(), edgeIntersections::edgeIntersections(), extrudePatchMesh::extrudePatchMesh(), patchProbes::findElements(), mappedPatchBase::findSamples(), PatchTools::gatherAndMerge(), triSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getNormal(), processorPolyPatch::initOrder(), cyclicPolyPatch::initOrder(), momentOfInertia::massPropertiesShell(), momentOfInertia::massPropertiesSolid(), coupledPolyPatch::matchTolerance(), NamedEnum< Enum, nEnum >::names(), combineEqOp< Type, TrackingData >::operator()(), nearestEqOp::operator()(), triSurface::operator=(), MeshedSurface< Face >::operator=(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), cyclicPolyPatch::order(), orientedSurface::orient(), orientedSurface::orientedSurface(), distributedTriSurfaceMesh::overlappingSurface(), pairPatchAgglomeration::patchLevel(), sampledPlane::points(), sampledThresholdCellFaces::points(), sampledCuttingPlane::points(), distanceSurface::points(), sampledPatch::points(), sampledIsoSurface::points(), sampledTriSurfaceMesh::points(), boundaryMesh::read(), boundaryMesh::setFeatureEdges(), patchInjectionBase::setPositionAndCell(), addPatchCellLayer::setRefinement(), triSurfacePointGeoMesh::size(), cellDistFuncs::smallestDist(), triSurfaceTools::surfaceNormal(), triSurfaceTools::surfaceSide(), triSurfaceSearch::tree(), triSurfaceTools::triangulate(), patchEdgeFaceInfo::updateEdge(), patchInjectionBase::updateMesh(), and surfaceLocation::write().
label nPoints () const inline
Return number of points supporting patch faces.
Definition at line 295 of file PrimitivePatch.H.
Referenced by booleanSurface::booleanSurface(), Foam::meshTools::calcBoxPointNormals(), cyclicPolyPatch::calcTransforms(), PointEdgeWave< Type, TrackingData >::countPatchType(), snappySnapDriver::detectNearSurfaces(), snappySnapDriver::doSnap(), boundaryMesh::getNPoints(), snappySnapDriver::getZoneSurfacePoints(), triSurfaceTools::greenRefine(), PatchTools::matchPoints(), triSurfaceTools::mergePoints(), globalMeshData::mergePoints(), medialAxisMeshMover::move(), listPlusEqOp< T >::operator()(), PatchTools::pointNormals(), mappedPatchBase::sampleSize(), addPatchCellLayer::setRefinement(), PatchTools::subsetMap(), surfaceIntersection::surfaceIntersection(), syncTools::syncPointList(), and AC3DsurfaceFormat< Face >::write().
label nEdges () const inline
Return number of edges in patch.
Definition at line 301 of file PrimitivePatch.H.
Referenced by booleanSurface::booleanSurface(), createShellMesh::calcPointRegions(), addPatchCellLayer::calcSidePatch(), PatchTools::checkOrientation(), triSurfaceTools::collapseEdges(), patchPatchDist::correct(), edgeIntersections::edgeIntersections(), PatchTools::edgeNormals(), edgeSurface::edgeSurface(), extrudePatchMesh::extrudePatchMesh(), surfaceFeatures::findFeatures(), triSurfaceTools::greenRefine(), PatchTools::matchEdges(), meshRefinement::mergeBaffles(), surfaceFeatures::nearestFeatEdge(), polyBoundaryMesh::neighbourEdges(), listPlusEqOp< T >::operator()(), orientedSurface::orient(), boundaryMesh::read(), boundaryMesh::readTriSurface(), edgeIntersections::removeDegenerates(), addPatchCellLayer::setRefinement(), surfaceFeatures::surfaceFeatures(), surfaceIntersection::surfaceIntersection(), syncTools::syncEdgeList(), surfaceFeatures::trimFeatures(), and searchableSurfaces::writeStats().
const Foam::edgeList & edges () const
Return list of edges, address into LOCAL point list.
Definition at line 228 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::nInternalEdges().
Referenced by booleanSurface::booleanSurface(), createShellMesh::calcPointRegions(), addPatchCellLayer::calcSidePatch(), snappySnapDriver::calcSnapDistance(), searchableSurfaces::checkIntersection(), PatchTools::checkOrientation(), triSurfaceTools::collapseEdges(), patchPatchDist::correct(), cyclicPolyPatch::coupledEdges(), PatchTools::edgeOwner(), edgeSurface::edgeSurface(), triSurfaceTools::getEdge(), combineFaces::getOutsideFace(), triSurfaceTools::getVertexTriangles(), triSurfaceTools::getVertexVertices(), triSurfaceTools::greenRefine(), PatchTools::matchEdges(), triSurfaceTools::maxEdge(), polyPatch::meshEdges(), triSurfaceTools::minEdge(), edgeIntersections::minEdgeLength(), slidingInterface::modifyMotionPoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::movePoints(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::nEdges(), polyBoundaryMesh::neighbourEdges(), listPlusEqOp< T >::operator()(), triSurfaceTools::oppositeEdge(), triSurfaceTools::oppositeVertex(), triSurfaceTools::otherEdges(), boundaryMesh::setFeatureEdges(), perfectInterface::setRefinement(), addPatchCellLayer::setRefinement(), PatchTools::sortedEdgeFaces(), PatchTools::sortedPointEdges(), surfaceFeatures::surfaceFeatures(), surfaceIntersection::surfaceIntersection(), triSurfaceTools::surfaceSide(), syncTools::syncEdgeMap(), surfaceFeatures::trimFeatures(), patchFaceOrientation::updateEdge(), patchEdgeFaceInfo::updateEdge(), patchFaceOrientation::updateFace(), surfaceLocation::write(), and surfaceFeatures::writeObj().
Foam::label nInternalEdges () const
Number of internal edges.
Definition at line 248 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::boundaryPoints().
Referenced by patchPatchDist::correct(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), extrudePatchMesh::extrudePatchMesh(), combineFaces::getOutsideFace(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::nEdges(), polyBoundaryMesh::neighbourEdges(), and addPatchCellLayer::setRefinement().
bool isInternalEdge (const label edgeI) const inline
Is internal edge?
Definition at line 313 of file PrimitivePatch.H.
const Foam::labelList & boundaryPoints () const
Return list of boundary points,.
address into LOCAL point list
Definition at line 268 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::faceFaces().
Referenced by PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), PrimitivePatch< Face, FaceList, PointField, PointType >::nInternalEdges(), and listPlusEqOp< T >::operator()().
const Foam::labelListList & faceFaces () const
Return face-face addressing.
Definition at line 288 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces().
Referenced by pairPatchAgglomeration::agglomerate(), PrimitivePatch< Face, FaceList, PointField, PointType >::boundaryPoints(), triSurfaceMesh::getNormal(), cellDistFuncs::getPointNeighbours(), and PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge().
const Foam::labelListList & edgeFaces () const
Return edge-face addressing.
Definition at line 308 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges().
Referenced by booleanSurface::booleanSurface(), createShellMesh::calcPointRegions(), addPatchCellLayer::calcSidePatch(), searchableSurfaces::checkClosed(), PatchTools::checkOrientation(), triSurfaceTools::collapseEdges(), PatchTools::edgeNormals(), PatchTools::edgeOwner(), triSurfaceTools::edgeSide(), edgeSurface::edgeSurface(), extendedEdgeMesh::extendedEdgeMesh(), extrudePatchMesh::extrudePatchMesh(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceFaces(), surfaceFeatures::findFeatures(), combineFaces::getOutsideFace(), triSurfaceTools::getTriangle(), triSurfaceTools::getVertexTriangles(), addPatchCellLayer::globalEdgeFaces(), triSurfaceTools::greenRefine(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), PatchTools::markZone(), surfaceLocation::normal(), listPlusEqOp< T >::operator()(), orientedSurface::orient(), triSurfaceTools::otherFace(), boundaryMesh::setFeatureEdges(), addPatchCellLayer::setRefinement(), PatchTools::sortedEdgeFaces(), PatchTools::sortedPointEdges(), surfaceFeatures::surfaceFeatures(), surfaceIntersection::surfaceIntersection(), triSurfaceTools::surfaceNormal(), and triSurfaceTools::trackToEdge().
const Foam::labelListList & faceEdges () const
Return face-edge addressing.
Definition at line 328 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::pointEdges().
Referenced by createShellMesh::calcPointRegions(), PatchTools::checkOrientation(), triSurfaceTools::classify(), cyclicPolyPatch::coupledEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), combineFaces::getOutsideFace(), triSurfaceTools::getTriangle(), intersectedSurface::intersectedSurface(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), PatchTools::markZone(), meshRefinement::mergeBaffles(), triSurfaceTools::oppositeEdge(), triSurfaceTools::otherEdges(), addPatchCellLayer::setRefinement(), PatchTools::sortedPointEdges(), triSurfaceTools::surfaceNormal(), and triSurfaceTools::surfaceSide().
const Foam::labelListList & pointEdges () const
Return point-edge addressing.
Definition at line 348 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::pointFaces().
Referenced by snappySnapDriver::calcSnapDistance(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), triSurfaceTools::getEdge(), triSurfaceTools::getVertexVertices(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), polyPatch::meshEdges(), edgeIntersections::minEdgeLength(), listPlusEqOp< T >::operator()(), PatchTools::sortedPointEdges(), and triSurfaceTools::surfaceSide().
const Foam::labelListList & pointFaces () const
Return point-face addressing.
Definition at line 368 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces().
Referenced by snappySnapDriver::avgCellCentres(), Foam::meshTools::calcBoxPointNormals(), cellDistFuncs::correctBoundaryPointCells(), cellDistFuncs::getPointNeighbours(), triSurfaceTools::getVertexTriangles(), volPointInterpolation::interpolateBoundaryField(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), listPlusEqOp< T >::operator()(), oldCyclicPolyPatch::order(), PrimitivePatch< Face, FaceList, PointField, PointType >::pointEdges(), PatchTools::pointNormals(), and triSurfaceTools::trackToEdge().
const Foam::List< Face > & localFaces () const
Return patch faces addressing into local point list.
Definition at line 388 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints().
Referenced by mappedPatchBase::calcAMI(), createShellMesh::calcPointRegions(), PatchTools::checkOrientation(), triSurfaceTools::classify(), triSurfaceTools::collapseEdges(), PatchTools::edgeOwner(), extrudePatchMesh::extrudePatchMesh(), combineFaces::getOutsideFace(), cellDistFuncs::getPointNeighbours(), triSurfaceTools::greenRefine(), processorPolyPatch::initOrder(), intersectedSurface::intersectedSurface(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), triSurfaceTools::mergePoints(), meshTriangulation::meshTriangulation(), NamedEnum< Enum, nEnum >::names(), listPlusEqOp< T >::operator()(), triSurfaceTools::oppositeVertex(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), triSurfaceTools::otherEdges(), triSurfaceTools::otherVertices(), pairPatchAgglomeration::pairPatchAgglomeration(), PrimitivePatch< Face, FaceList, PointField, PointType >::pointFaces(), PatchTools::pointNormals(), boundaryMesh::readTriSurface(), snappySnapDriver::repatchToSurface(), cyclicAMIPolyPatch::resetAMI(), addPatchCellLayer::setRefinement(), PatchTools::sortedEdgeFaces(), PatchTools::subsetMap(), triSurfaceTools::surfaceNormal(), triSurfaceTools::surfaceSide(), triSurfaceTools::triangulateFaceCentre(), boundaryMesh::triangulateLocal(), sampledPatch::update(), patchFaceOrientation::updateEdge(), patchFaceOrientation::updateFace(), AC3DsurfaceFormat< Face >::write(), and meshRefinement::zonify().
const Foam::labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
walking through the faces in incremental order and not sorted anymore.
Definition at line 408 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::meshPointMap().
Referenced by snappySnapDriver::avgCellCentres(), Foam::meshTools::calcBoxPointNormals(), snappySnapDriver::calcNearestSurface(), addPatchCellLayer::calcSidePatch(), snappySnapDriver::calcSnapDistance(), inversePointDistanceDiffusivity::correct(), patchPatchDist::correct(), cellDistFuncs::correctBoundaryPointCells(), PointEdgeWave< Type, TrackingData >::countPatchType(), cyclicPolyPatch::coupledEdges(), snappySnapDriver::detectNearSurfaces(), extrudePatchMesh::extrudePatchMesh(), mappedPatchBase::findSamples(), combineFaces::getOutsideFace(), globalPoints::globalPoints(), volPointInterpolation::interpolateBoundaryField(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), localPointRegion::localPointRegion(), PatchTools::matchEdges(), PatchTools::matchPoints(), globalMeshData::mergePoints(), facePointPatch::meshPoints(), medialAxisMeshMover::move(), polyBoundaryMesh::neighbourEdges(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::nPoints(), listPlusEqOp< T >::operator()(), combineEqOp< Type, TrackingData >::operator()(), orientedSurface::orientedSurface(), PatchTools::pointNormals(), motionSmootherAlgo::setDisplacementPatchFields(), perfectInterface::setRefinement(), addPatchCellLayer::setRefinement(), snappySnapDriver::smoothDisplacement(), syncTools::syncEdgeMap(), globalMeshData::syncPointData(), syncTools::syncPointList(), syncTools::syncPointMap(), pointConstraints::syncUntransformedData(), boundaryMesh::triangulateLocal(), patchEdgeFaceInfo::updateEdge(), and medialAxisMeshMover::~medialAxisMeshMover().
const Foam::Map< Foam::label > & meshPointMap () const
Mesh point map. Given the global point index find its.
location in the patch
Definition at line 428 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints().
Referenced by snappySnapDriver::getZoneSurfacePoints(), globalPoints::globalPoints(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), PatchTools::matchPoints(), globalMeshData::mergePoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), PatchTools::pointNormals(), and syncTools::syncPointList().
const Foam::Field< PointType > & localPoints () const
Return pointField of points in patch.
Definition at line 448 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::localPointOrder().
Referenced by booleanSurface::booleanSurface(), mappedPatchBase::calcAMI(), snappySnapDriver::calcNearestSurface(), snappySnapDriver::calcSnapDistance(), cyclicPolyPatch::calcTransforms(), searchableSurfaces::checkIntersection(), PatchTools::checkOrientation(), triSurfaceTools::collapseEdges(), patchPatchDist::correct(), cyclicPolyPatch::coupledEdges(), snappySnapDriver::detectNearSurfaces(), snappySnapDriver::doSnap(), edgeSurface::edgeSurface(), triSurfaceTools::greenRefine(), processorPolyPatch::initOrder(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), facePointPatch::localPoints(), triSurfaceTools::maxEdge(), triSurfaceTools::mergePoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPointMap(), meshTriangulation::meshTriangulation(), triSurfaceTools::minEdge(), edgeIntersections::minEdgeLength(), slidingInterface::modifyMotionPoints(), NamedEnum< Enum, nEnum >::names(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), polyBoundaryMesh::neighbourEdges(), listPlusEqOp< T >::operator()(), processorPolyPatch::order(), pairPatchAgglomeration::pairPatchAgglomeration(), boundaryMesh::readTriSurface(), snappySnapDriver::repatchToSurface(), perfectInterface::setRefinement(), addPatchCellLayer::setRefinement(), snappySnapDriver::smoothDisplacement(), PatchTools::sortedEdgeFaces(), surfaceIntersection::surfaceIntersection(), triSurfaceTools::surfaceSide(), triSurfaceTools::triangulateFaceCentre(), boundaryMesh::triangulateLocal(), surfaceFeatures::trimFeatures(), sampledPatch::update(), AC3DsurfaceFormat< Face >::write(), surfaceLocation::write(), triSurfaceTools::writeOBJ(), surfaceFeatures::writeObj(), and meshRefinement::zonify().
const Foam::labelList & localPointOrder () const
Return orders the local points for most efficient search.
Definition at line 468 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::whichPoint().
Referenced by PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), and PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints().
Foam::label whichPoint (const label gp) const
Given a global point index, return the local point index.
If the point is not found, return -1
Definition at line 489 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::faceCentres(), and HashTable< T, Key, Hash >::find().
Referenced by PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPointOrder(), and slidingInterface::modifyMotionPoints().
Foam::label whichEdge (const edge & e) const
Given an edge in local point labels, return its.
index in the edge list. If the edge is not found, return -1
Definition at line 175 of file PrimitivePatchMeshEdges.C.
References forAll, nPoints, and edge::start().
Referenced by PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshEdges(), and slidingInterface::modifyMotionPoints().
Foam::labelList meshEdges (const edgeList & allEdges, const labelListList & cellEdges, const labelList & faceCells) const
Return labels of patch edges in the global edge list using.
cell addressing
Definition at line 41 of file PrimitivePatchMeshEdges.C.
References Foam::endl(), forAll, found, Foam::Info, and List< T >::size().
Referenced by addPatchCellLayer::calcSidePatch(), addPatchCellLayer::globalEdgeFaces(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), meshRefinement::mergeBaffles(), polyPatch::meshEdges(), listPlusEqOp< T >::operator()(), addPatchCellLayer::setRefinement(), and medialAxisMeshMover::~medialAxisMeshMover().
Foam::labelList meshEdges (const edgeList & allEdges, const labelListList & pointEdges) const
Return labels of patch edges in the global edge list using.
basic edge addressing.
Definition at line 118 of file PrimitivePatchMeshEdges.C.
References Foam::endl(), forAll, Foam::Info, List< T >::size(), and PrimitivePatch< Face, FaceList, PointField, PointType >::whichEdge().
const Foam::Field< PointType > & faceCentres () const
Return face centres for patch.
Definition at line 516 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals().
Referenced by symmetryPlanePolyPatch::calcGeometry(), wedgePolyPatch::calcGeometry(), cyclicPolyPatch::calcTransforms(), processorPolyPatch::initOrder(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), meshRefinement::mergeBaffles(), listPlusEqOp< T >::operator()(), processorPolyPatch::order(), patchEdgeFaceInfo::updateFace(), and PrimitivePatch< Face, FaceList, PointField, PointType >::whichPoint().
const Foam::Field< PointType > & faceNormals () const
Return face normals for patch.
Definition at line 536 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::pointNormals().
Referenced by ThermoSurfaceFilm< CloudType >::absorbInteraction(), ThermoSurfaceFilm< CloudType >::bounceInteraction(), Foam::meshTools::calcBoxPointNormals(), PatchTools::checkOrientation(), directions::directions(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), PatchTools::edgeNormals(), triSurfaceTools::edgeSide(), extrudePatchMesh::extrudePatchMesh(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceCentres(), boundaryMesh::getNearest(), processorPolyPatch::initOrder(), intersectedSurface::intersectedSurface(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), regionModel1D::moveMesh(), surfaceLocation::normal(), listPlusEqOp< T >::operator()(), processorPolyPatch::order(), PatchTools::pointNormals(), boundaryMesh::setFeatureEdges(), removeFaces::setRefinement(), ThermoSurfaceFilm< CloudType >::splashInteraction(), triSurfaceTools::surfaceNormal(), triSurfaceTools::surfaceSide(), wallLayerCells::wallLayerCells(), and ThermoSurfaceFilm< CloudType >::wetSplashInteraction().
const Foam::Field< PointType > & pointNormals () const
Return point normals for patch.
Definition at line 556 of file PrimitivePatch.C.
Referenced by Foam::meshTools::calcBoxPointNormals(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), slidingInterface::modifyMotionPoints(), surfaceLocation::normal(), facePointPatch::pointNormals(), and triSurfaceTools::surfaceNormal().
List<objectHit> projectPoints (const ToPatch & targetPatch, const Field< PointType > & projectionDirection, const intersection::algorithm = intersection::FULL_RAY, const intersection::direction = intersection::VECTOR) const
Project vertices of patch onto another patch.
Referenced by PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge().
List<objectHit> projectFaceCentres (const ToPatch & targetPatch, const Field< PointType > & projectionDirection, const intersection::algorithm = intersection::FULL_RAY, const intersection::direction = intersection::VECTOR) const
Project vertices of patch onto another patch.
Referenced by PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), and PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints().
const Foam::labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
Edge loops are given as ordered lists of vertices in local addressing
Definition at line 167 of file PrimitivePatchEdgeLoops.C.
Referenced by combineFaces::getOutsideFace(), and PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge().
Foam::PrimitivePatch< Face, FaceList, PointField, PointType >::surfaceTopo surfaceType () const
Calculate surface type formed by patch.
Types:
all edges have two neighbours (manifold)
some edges have more than two neighbours (illegal)
other (open)
Definition at line 120 of file PrimitivePatchCheck.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::checkTopology(), Foam::endl(), forAll, Foam::Info, InfoInFunction, and List< T >::size().
Referenced by PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge().
bool checkTopology (const bool report = false, labelHashSet * setPtr = NULL) const
Check surface formed by patch for manifoldness (see above).
Return true if any incorrect edges are found. Insert vertices of incorrect edges into set.
Definition at line 168 of file PrimitivePatchCheck.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::checkPointManifold(), edge::end(), Foam::endl(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), List< T >::size(), and edge::start().
Referenced by PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), and PrimitivePatch< Face, FaceList, PointField, PointType >::surfaceType().
bool checkPointManifold (const bool report = false, labelHashSet * setPtr = NULL) const
Checks primitivePatch for faces sharing point but not edge.
This denotes a surface that is pinched at a single point (test for pinched at single edge is already in PrimitivePatch) Returns true if this situation found and puts conflicting (mesh)point in set. Based on all the checking routines in primitiveMesh.
Definition at line 228 of file PrimitivePatchCheck.C.
References Foam::endl(), Foam::findIndex(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::constant::atomic::mp, Foam::nl, and List< T >::size().
Referenced by PrimitivePatch< Face, FaceList, PointField, PointType >::checkTopology(), and PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge().
void movePoints (const Field< PointType > &) virtual
Correct patch after moving points.
Definition at line 203 of file PrimitivePatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), Foam::endl(), and Foam::Pout.
Referenced by cyclicAMIPolyPatch::initMovePoints(), PrimitivePatch< face,::Foam::UList,::Foam::SubField< point >, point >::isInternalEdge(), polyPatch::movePoints(), and PrimitivePatch< Face, FaceList, PointField, PointType >::~PrimitivePatch().
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > & pp)
Assignment.
Definition at line 579 of file PrimitivePatch.C.
Referenced by polyPatch::operator=().
Foam::List<Foam::objectHit> projectPoints (const ToPatch & targetPatch, const Field< PointType > & projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Definition at line 48 of file PrimitivePatchProjectPoints.C.
References Foam::abort(), Foam::fvc::average(), PointHit< Point >::distance(), PointHit< Point >::eligibleMiss(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, PointHit< Point >::hit(), Foam::Info, Foam::mag(), Foam::magSqr(), PointHit< Point >::missPoint(), Foam::nl, nPoints, points, PrimitivePatch< Face, FaceList, PointField, PointType >::projectFaceCentres(), and List< T >::size().
Foam::List<Foam::objectHit> projectFaceCentres (const ToPatch & targetPatch, const Field< PointType > & projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Definition at line 291 of file PrimitivePatchProjectPoints.C.
References Foam::abort(), Foam::bandCompression(), PointHit< Point >::distance(), PointHit< Point >::eligibleMiss(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, PointHit< Point >::hit(), Foam::Info, Foam::mag(), Foam::magSqr(), PointHit< Point >::missPoint(), Foam::nl, points, and List< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatch.H
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatch.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchAddressing.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchBdryPoints.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchCheck.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchClear.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchEdgeLoops.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchLocalPointOrder.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchMeshData.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchMeshEdges.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchPointAddressing.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchProjectPoints.C