OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionModelFunctionObjectList Class Reference
Public Member Functions
regionModelFunctionObjectList (regionModel &owner)
Null constructor.
regionModelFunctionObjectList (regionModel &owner, const dictionary &dict, const bool readFields=true)
Construct from mesh.
regionModelFunctionObjectList (const regionModelFunctionObjectList &rmfol)
Construct copy.
virtual ~regionModelFunctionObjectList ()
Destructor.
const regionModel & owner () const
Return const access to the cloud owner.
regionModel & owner ()
Return refernce to the cloud owner.
const dictionary & dict () const
Return the forces dictionary.
virtual void preEvolveRegion ()
Pre-evolve hook.
virtual void postEvolveRegion ()
Post-evolve hook.
Public Member Functions inherited from PtrList< regionModelFunctionObject >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< regionModelFunctionObject > &)
Copy constructor.
PtrList (const PtrList< regionModelFunctionObject > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< regionModelFunctionObject > > &)
Construct by transferring the parameter contents.
PtrList (PtrList< regionModelFunctionObject > &, bool reUse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< regionModelFunctionObject > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
regionModelFunctionObject & first ()
Return reference to the first element of the list.
const regionModelFunctionObject & first () const
Return reference to first element of the list.
regionModelFunctionObject & last ()
Return reference to the last element of the list.
const regionModelFunctionObject & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (regionModelFunctionObject *)
Append an element at the end of the list.
void append (const autoPtr< regionModelFunctionObject > &)
void append (const tmp< regionModelFunctionObject > &)
void transfer (PtrList< regionModelFunctionObject > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList
< regionModelFunctionObject > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr
< regionModelFunctionObject > set (const label, regionModelFunctionObject *)
Set element. Return old element (can be NULL).
autoPtr
< regionModelFunctionObject > set (const label, const autoPtr< regionModelFunctionObject > &)
autoPtr
< regionModelFunctionObject > set (const label, const tmp< regionModelFunctionObject > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const regionModelFunctionObject & operator[] (const label) const
Return element const reference.
regionModelFunctionObject & operator[] (const label)
Return element reference.
const regionModelFunctionObject * operator() (const label) const
Return element const pointer.
PtrList
< regionModelFunctionObject > & operator= (const PtrList< regionModelFunctionObject > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
Protected Attributes
regionModel & owner_
Reference to the owner region model.
const dictionary dict_
Dictionary.
Additional Inherited Members
Public Types inherited from PtrList< regionModelFunctionObject >
typedef regionModelFunctionObject value_type
Type of values the PtrList contains.
typedef regionModelFunctionObject & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const
regionModelFunctionObject & const_reference
Type that can be used for storing into constant PtrList::value_type.
Protected Member Functions inherited from PtrList< regionModelFunctionObject >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Definition at line 54 of file regionModelFunctionObjectList.H.
Constructor & Destructor Documentation
regionModelFunctionObjectList (regionModel & owner)
Null constructor.
Definition at line 31 of file regionModelFunctionObjectList.C.
regionModelFunctionObjectList (regionModel & owner, const dictionary & dict, const bool readFields = true)
Construct from mesh.
Definition at line 42 of file regionModelFunctionObjectList.C.
References Foam::endl(), forAll, i, Foam::Info, set(), setSize(), and dictionary::toc().
regionModelFunctionObjectList (const regionModelFunctionObjectList & rmfol)
Construct copy.
Definition at line 87 of file regionModelFunctionObjectList.C.
~regionModelFunctionObjectList () virtual
Destructor.
Definition at line 100 of file regionModelFunctionObjectList.C.
Member Function Documentation
const Foam::regionModels::regionModel & owner () const inline
Return const access to the cloud owner.
Definition at line 27 of file regionModelFunctionObjectListI.H.
References regionModelFunctionObjectList::owner_.
Foam::regionModels::regionModel & owner () inline
Return refernce to the cloud owner.
Definition at line 34 of file regionModelFunctionObjectListI.H.
const Foam::dictionary & dict () const inline
Return the forces dictionary.
Definition at line 41 of file regionModelFunctionObjectListI.H.
void preEvolveRegion () virtual
Pre-evolve hook.
Definition at line 106 of file regionModelFunctionObjectList.C.
References forAll, and i.
void postEvolveRegion () virtual
Post-evolve hook.
Definition at line 115 of file regionModelFunctionObjectList.C.
References forAll, and i.
Member Data Documentation
regionModel& owner_ protected
Reference to the owner region model.
Definition at line 63 of file regionModelFunctionObjectList.H.
Referenced by regionModelFunctionObjectList::owner().
const dictionary dict_ protected
Dictionary.
Definition at line 66 of file regionModelFunctionObjectList.H.
The documentation for this class was generated from the following files:
src/regionModels/regionModel/regionModelFunctionObject/regionModelFunctionObject/regionModelFunctionObjectList.H
src/regionModels/regionModel/regionModelFunctionObject/regionModelFunctionObject/regionModelFunctionObjectList.C
src/regionModels/regionModel/regionModelFunctionObject/regionModelFunctionObject/regionModelFunctionObjectListI.H