OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pureUpwindCFCCellToFaceStencilObject Class Reference
Public Member Functions
TypeName ("pureUpwindCFCCellToFaceStencil")
pureUpwindCFCCellToFaceStencilObject (const fvMesh &mesh)
Construct from uncompacted face stencil.
virtual ~pureUpwindCFCCellToFaceStencilObject ()
Destructor.
Public Member Functions inherited from extendedUpwindCellToFaceStencil
extendedUpwindCellToFaceStencil (const cellToFaceStencil &, const bool pureUpwind, const scalar minOpposedness)
Construct from mesh and uncompacted centred face stencil.
extendedUpwindCellToFaceStencil (const cellToFaceStencil &)
Construct from mesh and uncompacted centred face stencil. Splits.
bool pureUpwind () const
const mapDistribute & ownMap () const
Return reference to the parallel distribution map.
const mapDistribute & neiMap () const
Return reference to the parallel distribution map.
const labelListList & ownStencil () const
Return reference to the stencil.
const labelListList & neiStencil () const
Return reference to the stencil.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &ownWeights, const List< List< scalar >> &neiWeights) const
Sum vol field contributions to create face values.
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &ownWeights, const List< List< scalar >> &neiWeights) const
Public Member Functions inherited from extendedCellToFaceStencil
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type >> &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedCellToFaceStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T >> &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Sum vol field contributions to create face values.
Static Protected Member Functions inherited from extendedCellToFaceStencil
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Write some statistics about stencil.
Protected Attributes inherited from extendedCellToFaceStencil
const polyMesh & mesh_
Detailed Description
Source files
pureUpwindCFCCellToFaceStencilObject.H
Definition at line 48 of file pureUpwindCFCCellToFaceStencilObject.H.
Constructor & Destructor Documentation
pureUpwindCFCCellToFaceStencilObject (const fvMesh & mesh) inline explicit
Construct from uncompacted face stencil.
Definition at line 67 of file pureUpwindCFCCellToFaceStencilObject.H.
References Foam::endl(), Foam::Info, Foam::nl, extendedUpwindCellToFaceStencil::ownMap(), extendedUpwindCellToFaceStencil::ownStencil(), Foam::type(), and extendedCellToFaceStencil::writeStencilStats().
virtual ~pureUpwindCFCCellToFaceStencilObject () inline virtual
Destructor.
Definition at line 89 of file pureUpwindCFCCellToFaceStencilObject.H.
Member Function Documentation
TypeName ("pureUpwindCFCCellToFaceStencil")
The documentation for this class was generated from the following file:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/MeshObjects/pureUpwindCFCCellToFaceStencilObject.H