OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
procLess Class Reference
Less operator for pairs of <processor><index>
Public Member Functions
procLess (const labelPairList &lst)
bool operator() (const label a, const label b)
Detailed Description
Less operator for pairs of <processor><index>
Definition at line 39 of file lduPrimitiveMesh.C.
Constructor & Destructor Documentation
procLess (const labelPairList & lst) inline
Definition at line 45 of file lduPrimitiveMesh.C.
Member Function Documentation
bool operator() (const label a, const label b) inline
Definition at line 50 of file lduPrimitiveMesh.C.
References Foam::abort(), Foam::constant::physicoChemical::b, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), forAll, UList< T >::last(), List< T >::setSize(), PtrList< T >::size(), UList< T >::size(), and Foam::sortedOrder().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/lduMesh/lduPrimitiveMesh.C