OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
quadraticFitPolynomial Class Reference
Quadratic polynomial for centred interpolation fitting.
Static Public Member Functions
static label nTerms (const direction dim)
static void addCoeffs (scalar *coeffs, const vector &d, const scalar weight, const direction dim)
Detailed Description
Quadratic polynomial for centred interpolation fitting.
Can be used with the CentredFit scheme to create a quadratic surface interpolation scheme
Definition at line 48 of file quadraticFitPolynomial.H.
Member Function Documentation
static label nTerms (const direction dim) inline static
Definition at line 54 of file quadraticFitPolynomial.H.
References quadraticFitPolynomial::addCoeffs().
static void addCoeffs (scalar * coeffs, const vector & d, const scalar weight, const direction dim) inline static
Definition at line 65 of file quadraticFitPolynomial.H.
References Foam::sqr(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by quadraticFitPolynomial::nTerms().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/quadraticFit/quadraticFitPolynomial.H