OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ReactingMultiphaseLookupTableInjection< CloudType > Class Template Reference
Particle injection sources read from look-up table. Each row corresponds to an injection site.
Public Member Functions
TypeName ("reactingMultiphaseLookupTableInjection")
Runtime type information.
ReactingMultiphaseLookupTableInjection (const dictionary &dict, CloudType &owner, const word &modelName)
Construct from dictionary.
ReactingMultiphaseLookupTableInjection (const ReactingMultiphaseLookupTableInjection< CloudType > &im)
Construct copy.
virtual autoPtr< InjectionModel< CloudType > > clone () const
Construct and return a clone.
virtual ~ReactingMultiphaseLookupTableInjection ()
Destructor.
virtual void updateMesh ()
Set injector locations when mesh is updated.
scalar timeEnd () const
Return the end-of-injection time.
virtual label parcelsToInject (const scalar time0, const scalar time1)
Number of parcels to introduce relative to SOI.
virtual scalar volumeToInject (const scalar time0, const scalar time1)
Volume of parcels to introduce relative to SOI.
virtual void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector &position, label &cellOwner, label &tetFaceI, label &tetPtI)
Set the injection position and owner cell, tetFace and tetPt.
virtual void setProperties (const label parcelI, const label nParcels, const scalar time, typename CloudType::parcelType &parcel)
Set the parcel properties.
virtual bool fullyDescribed () const
Flag to identify whether model fully describes the parcel.
virtual bool validInjection (const label parcelI)
Return flag to identify whether or not injection of parcelI is.
Public Member Functions inherited from InjectionModel< CloudType >
TypeName ("injectionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, InjectionModel, dictionary,(const dictionary &dict, CloudType &owner, const word &modelType),(dict, owner, modelType))
Declare runtime constructor selection table.
InjectionModel (CloudType &owner)
Construct null from owner.
InjectionModel (const dictionary &dict, CloudType &owner, const word &modelName, const word &modelType)
Construct from dictionary.
InjectionModel (const InjectionModel< CloudType > &im)
Construct copy.
virtual ~InjectionModel ()
Destructor.
scalar timeStart () const
Return the start-of-injection time.
scalar volumeTotal () const
Return the total volume to be injected across the event.
scalar massTotal () const
Return mass of particles to introduce.
scalar massInjected () const
Return mass of particles injected (cumulative)
virtual scalar averageParcelMass ()
Return the average parcel mass over the injection period.
label nInjections () const
Return the number of injections.
label parcelsAddedTotal () const
Return the total number parcels added.
template<class TrackData >
void inject (TrackData &td)
Main injection loop.
template<class TrackData >
void injectSteadyState (TrackData &td, const scalar trackTime)
Main injection loop - steady-state.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from InjectionModel< CloudType >
enum parcelBasis { pbNumber, pbMass, pbFixed }
Parcel basis representation options.
typedef CloudType::parcelType parcelType
Convenience typedef for parcelType.
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from InjectionModel< CloudType >
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector with lookup from dictionary.
static autoPtr< InjectionModel< CloudType > > New (const dictionary &dict, const word &modelName, const word &modelType, CloudType &owner)
Selector with name and type.
Protected Member Functions inherited from InjectionModel< CloudType >
virtual bool prepareForNextTimeStep (const scalar time, label &newParcels, scalar &newVolumeFraction)
Determine properties for next time step/injection interval.
virtual bool findCellAtPosition (label &cellI, label &tetFaceI, label &tetPtI, vector &position, bool errorOnNotFound=true)
Find the cell that contains the supplied position.
virtual scalar setNumberOfParticles (const label parcels, const scalar volumeFraction, const scalar diameter, const scalar rho)
Set number of particles to inject given parcel properties.
virtual void postInjectCheck (const label parcelsAdded, const scalar massAdded)
Post injection checks.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from InjectionModel< CloudType >
scalar SOI_
Start of injection [s].
scalar volumeTotal_
Total volume of particles introduced by this injector [m^3].
scalar massTotal_
Total mass to inject [kg].
TimeFunction1< scalar > massFlowRate_
Mass flow rate profile for steady calculations.
scalar massInjected_
Total mass injected to date [kg].
label nInjections_
Number of injections counter.
label parcelsAddedTotal_
Running counter of total number of parcels added.
parcelBasis parcelBasis_
Parcel basis enumeration.
scalar nParticleFixed_
nParticle to assign to parcels when the 'fixed' basis
scalar time0_
Continuous phase time at start of injection time step [s].
scalar timeStep0_
Time at start of injection time step [s].
scalar delayedVolume_
Volume that should have been injected, but would lead to.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::ReactingMultiphaseLookupTableInjection< CloudType >
Particle injection sources read from look-up table. Each row corresponds to an injection site.
((x y z) (u v w) d rho mDot T cp (Y0..Y2) (Yg0..YgN) (Yl0..YlN) (Ys0..YsN) (x y z) (u v w) d rho mDot T cp (Y0..Y2) (Yg0..YgN) (Yl0..YlN) (Ys0..YsN) ... (x y z) (u v w) d rho mDot T cp (Y0..Y2) (Yg0..YgN) (Yl0..YlN) (Ys0..YsN));
where: x, y, z = global cartesian co-ordinates [m] u, v, w = global cartesian velocity components [m/s] d = diameter [m] rho = density [kg/m3] mDot = mass flow rate [kg/m3] T = temperature [K] cp = specific heat capacity [J/kg/K] Y(3) = total mass fraction of gas (Y0), liquid (Y1), solid (Y3) Yg(Ngas) = mass fractions of gaseous components Yl(Nliq) = mass fractions of liquid components Ys(Nsld) = mass fractions of solid components
Source files
ReactingMultiphaseLookupTableInjection.H
ReactingMultiphaseLookupTableInjection.C
Definition at line 71 of file ReactingMultiphaseLookupTableInjection.H.
Constructor & Destructor Documentation
ReactingMultiphaseLookupTableInjection (const dictionary & dict, CloudType & owner, const word & modelName)
Construct from dictionary.
Definition at line 33 of file ReactingMultiphaseLookupTableInjection.C.
References forAll.
ReactingMultiphaseLookupTableInjection (const ReactingMultiphaseLookupTableInjection< CloudType > & im)
Construct copy.
Definition at line 84 of file ReactingMultiphaseLookupTableInjection.C.
References ReactingMultiphaseLookupTableInjection< CloudType >::~ReactingMultiphaseLookupTableInjection().
~ReactingMultiphaseLookupTableInjection () virtual
Destructor.
Definition at line 104 of file ReactingMultiphaseLookupTableInjection.C.
Referenced by ReactingMultiphaseLookupTableInjection< CloudType >::clone(), and ReactingMultiphaseLookupTableInjection< CloudType >::ReactingMultiphaseLookupTableInjection().
Member Function Documentation
TypeName ("reactingMultiphaseLookupTableInjection")
Runtime type information.
virtual autoPtr<InjectionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements InjectionModel< CloudType >.
Definition at line 125 of file ReactingMultiphaseLookupTableInjection.H.
References ReactingMultiphaseLookupTableInjection< CloudType >::fullyDescribed(), ReactingMultiphaseLookupTableInjection< CloudType >::parcelsToInject(), ReactingMultiphaseLookupTableInjection< CloudType >::setPositionAndCell(), ReactingMultiphaseLookupTableInjection< CloudType >::setProperties(), ReactingMultiphaseLookupTableInjection< CloudType >::timeEnd(), ReactingMultiphaseLookupTableInjection< CloudType >::updateMesh(), ReactingMultiphaseLookupTableInjection< CloudType >::validInjection(), ReactingMultiphaseLookupTableInjection< CloudType >::volumeToInject(), and ReactingMultiphaseLookupTableInjection< CloudType >::~ReactingMultiphaseLookupTableInjection().
void updateMesh () virtual
Set injector locations when mesh is updated.
Reimplemented from InjectionModel< CloudType >.
Definition at line 111 of file ReactingMultiphaseLookupTableInjection.C.
References forAll, and x.
Referenced by ReactingMultiphaseLookupTableInjection< CloudType >::clone().
Foam::scalar timeEnd () const virtual
Return the end-of-injection time.
Implements InjectionModel< CloudType >.
Definition at line 129 of file ReactingMultiphaseLookupTableInjection.C.
References ReactingMultiphaseLookupTableInjection< CloudType >::parcelsToInject().
Referenced by ReactingMultiphaseLookupTableInjection< CloudType >::clone().
Foam::label parcelsToInject (const scalar time0, const scalar time1) virtual
Number of parcels to introduce relative to SOI.
Implements InjectionModel< CloudType >.
Definition at line 138 of file ReactingMultiphaseLookupTableInjection.C.
References ReactingMultiphaseLookupTableInjection< CloudType >::volumeToInject().
Referenced by ReactingMultiphaseLookupTableInjection< CloudType >::clone(), and ReactingMultiphaseLookupTableInjection< CloudType >::timeEnd().
Foam::scalar volumeToInject (const scalar time0, const scalar time1) virtual
Volume of parcels to introduce relative to SOI.
Implements InjectionModel< CloudType >.
Definition at line 157 of file ReactingMultiphaseLookupTableInjection.C.
References forAll, and ReactingMultiphaseLookupTableInjection< CloudType >::setPositionAndCell().
Referenced by ReactingMultiphaseLookupTableInjection< CloudType >::clone(), and ReactingMultiphaseLookupTableInjection< CloudType >::parcelsToInject().
void setPositionAndCell (const label parcelI, const label nParcels, const scalar time, vector & position, label & cellOwner, label & tetFaceI, label & tetPtI) virtual
Set the injection position and owner cell, tetFace and tetPt.
Implements InjectionModel< CloudType >.
Definition at line 177 of file ReactingMultiphaseLookupTableInjection.C.
References cachedRandom::position(), ReactingMultiphaseLookupTableInjection< CloudType >::setProperties(), and Vector< Cmpt >::x().
Referenced by ReactingMultiphaseLookupTableInjection< CloudType >::clone(), and ReactingMultiphaseLookupTableInjection< CloudType >::volumeToInject().
void setProperties (const label parcelI, const label nParcels, const scalar time, typename CloudType::parcelType & parcel) virtual
Set the parcel properties.
Implements InjectionModel< CloudType >.
Definition at line 207 of file ReactingMultiphaseLookupTableInjection.C.
Referenced by ReactingMultiphaseLookupTableInjection< CloudType >::clone(), and ReactingMultiphaseLookupTableInjection< CloudType >::setPositionAndCell().
bool fullyDescribed () const virtual
Flag to identify whether model fully describes the parcel.
Implements InjectionModel< CloudType >.
Definition at line 247 of file ReactingMultiphaseLookupTableInjection.C.
References ReactingMultiphaseLookupTableInjection< CloudType >::validInjection().
Referenced by ReactingMultiphaseLookupTableInjection< CloudType >::clone().
bool validInjection (const label parcelI) virtual
Return flag to identify whether or not injection of parcelI is.
permitted
Implements InjectionModel< CloudType >.
Definition at line 255 of file ReactingMultiphaseLookupTableInjection.C.
Referenced by ReactingMultiphaseLookupTableInjection< CloudType >::clone(), and ReactingMultiphaseLookupTableInjection< CloudType >::fullyDescribed().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/ReactingMultiphase/InjectionModel/ReactingMultiphaseLookupTableInjection/ReactingMultiphaseLookupTableInjection.H
src/lagrangian/intermediate/submodels/ReactingMultiphase/InjectionModel/ReactingMultiphaseLookupTableInjection/ReactingMultiphaseLookupTableInjection.C