OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Q Class Reference
Function objects » Utility function objects
This function object calculates and outputs the second invariant of the velocity gradient tensor [1/s^2].
Public Member Functions
TypeName ("Q")
Runtime type information.
Q (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~Q ()
Destructor.
virtual const word & name () const
Return name of the set of Q.
virtual void read (const dictionary &)
Read the Q data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the Q and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
This function object calculates and outputs the second invariant of the velocity gradient tensor [1/s^2].
Source files
Q.H
Q.C
IOQ.H
Definition at line 66 of file Q.H.
Constructor & Destructor Documentation
Q (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 42 of file Q.C.
References Foam::dimless, Foam::dimTime, Foam::endl(), mesh, Foam::nl, Foam::read(), Foam::sqr(), fvMesh::time(), Time::timeName(), Foam::type(), and WarningInFunction.
~Q () virtual
Destructor.
Definition at line 93 of file Q.C.
Member Function Documentation
TypeName ("Q")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the set of Q.
Definition at line 118 of file Q.H.
void read (const dictionary & dict) virtual
Read the Q data.
Definition at line 99 of file Q.C.
References dictionary::lookupOrDefault().
void execute () virtual
Execute, currently does nothing.
Definition at line 108 of file Q.C.
References Foam::fvc::grad(), objectRegistry::lookupObject(), mesh, Foam::sqr(), Foam::tr(), Foam::type(), and U.
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 130 of file Q.C.
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 139 of file Q.C.
void write () virtual
Calculate the Q and write.
Definition at line 145 of file Q.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), and regIOobject::write().
Referenced by molecule::writeFields().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 139 of file Q.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 143 of file Q.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/Q/Q.H
src/postProcessing/functionObjects/utilities/Q/Q.C