OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionSizeDistribution Class Reference
Function objects » Field function objects
This function object creates a size distribution via interrogating a continuous phase fraction field.
Public Member Functions
TypeName ("regionSizeDistribution")
Runtime type information.
regionSizeDistribution (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~regionSizeDistribution ()
virtual const word & name () const
Return name of the set of regionSizeDistribution.
virtual void read (const dictionary &)
Read the regionSizeDistribution data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the regionSizeDistribution and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
template<class Type >
Foam::Map< Type > regionSum (const regionSplit &regions, const Field< Type > &fld) const
template<class Type >
Foam::List< Type > extractData (const UList< label > &keys, const Map< Type > &regionData) const
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void writeFileHeader (const label i=0)
File header information.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Detailed Description
This function object creates a size distribution via interrogating a continuous phase fraction field.
Looks up a phase-fraction (alpha) field and splits the mesh into regions based on where the field is below the threshold value. These regions ("droplets") can now be analysed.
Regions:
print the regions connected to a user-defined set of patches. (in spray calculation these form the liquid core)
print the regions with too large volume. These are the 'background' regions.
(debug) write regions as a volScalarField
(debug) print for all regions the sum of volume and alpha*volume
Output (volume scalar) fields include:
alpha_liquidCore : alpha with outside liquid core set to 0
alpha_background : alpha with outside background set to 0.
Histogram:
determine histogram of diameter (given minDiameter, maxDiameter, nBins)
write graph of number of droplets per bin
write graph of sum, average and deviation of droplet volume per bin
write graph of sum, average and deviation of user-defined fields. For volVectorFields these are those of the 3 components and the magnitude.
Example of function object specification:
regionSizeDistribution1
{
    type            regionSizeDistribution;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    field           alpha;
    patches         (inlet);
    threshold       0.4;
    fields          (p U);
    nBins           100;
    maxDiameter     0.5e-4;
    minDiameter     0;
    setFormat       gnuplot;
    coordinateSystem
    {
        type            cartesian;
        origin          (0 0 0);
        e3              (0 1 1);
        e1              (1 0 0);
    }
}
Function object usage
Property Description Required Default value
type type name: regionSizeDistribution yes
field phase field to interrogate yes
patches patches from which the liquid core is identified yes
threshold phase fraction applied to delimit regions yes
fields fields to sample yes
nBins number of bins for histogram yes
maxDiameter maximum region equivalent diameter yes
minDiameter minimum region equivalent diameter no 0
setFormat writing format yes
coordinateSystem transformation for vector fields no
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
regionSizeDistribution.H
regionSizeDistribution.C
Definition at line 187 of file regionSizeDistribution.H.
Constructor & Destructor Documentation
regionSizeDistribution (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 318 of file regionSizeDistribution.C.
References Foam::endl(), Foam::nl, Foam::read(), and WarningInFunction.
~regionSizeDistribution () virtual
Definition at line 349 of file regionSizeDistribution.C.
Member Function Documentation
TypeName ("regionSizeDistribution")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the set of regionSizeDistribution.
Definition at line 321 of file regionSizeDistribution.H.
References regionSizeDistribution::end(), regionSizeDistribution::execute(), regionSizeDistribution::read(), regionSizeDistribution::timeSet(), and regionSizeDistribution::write().
void read (const dictionary & dict) virtual
Read the regionSizeDistribution data.
Definition at line 355 of file regionSizeDistribution.C.
References Foam::endl(), format(), dictionary::found(), Foam::Info, dictionary::lookup(), writer< Type >::New(), and dictionary::readIfPresent().
Referenced by regionSizeDistribution::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 382 of file regionSizeDistribution.C.
Referenced by regionSizeDistribution::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 388 of file regionSizeDistribution.C.
Referenced by regionSizeDistribution::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 394 of file regionSizeDistribution.C.
Referenced by regionSizeDistribution::name().
void write () virtual
Calculate the regionSizeDistribution and write.
Reimplemented from functionObjectFile.
Definition at line 400 of file regionSizeDistribution.C.
References alphaPtr, HashTable< T, label, Hash< label > >::begin(), HashTable< T, Key, Hash >::begin(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::cbrt(), Field< Type >::component(), Vector< scalar >::componentNames, fvPatchField< Type >::coupled(), delta, Foam::dimless, Foam::fvc::domainIntegrate(), HashTableCore::end(), Foam::endl(), HashTable< T, label, Hash< label > >::erase(), HashTable< T, Key, Hash >::erase(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), Foam::findStrings(), fld(), forAll, forAllConstIter(), forAllIter, HashTable< T, Key, Hash >::found(), Foam::gSum(), Foam::Info, internalField(), GeometricField< Type, PatchField, GeoMesh >::internalField(), HashTable< T, Key, Hash >::iteratorBase::key(), Foam::mag(), UPstream::master(), mesh, IOobject::MUST_READ, IOobject::name(), primitiveMesh::nCells(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, regionSplit::nRegions(), fvPatch::patch(), fvPatchField< Type >::patch(), fvPatchField< Type >::patchInternalField(), fvPatchField< Type >::patchNeighbourField(), Foam::constant::mathematical::pi(), Foam::pow(), List< T >::size(), HashTable< T, label, Hash< label > >::sortedToc(), polyPatch::start(), token::TAB, fvMesh::time(), Time::timeName(), Foam::type(), Field< Type >::typeName, fvMesh::V(), regIOobject::write(), and x.
Referenced by regionSizeDistribution::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 342 of file regionSizeDistribution.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 346 of file regionSizeDistribution.H.
Foam::Map<Type> regionSum (const regionSplit & regions, const Field< Type > & fld) const
Definition at line 34 of file regionSizeDistributionTemplates.C.
References forAll, and regionSplit::nRegions().
Foam::List<Type> extractData (const UList< label > & keys, const Map< Type > & regionData) const
Definition at line 66 of file regionSizeDistributionTemplates.C.
References forAll, and UList< T >::size().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/regionSizeDistribution/regionSizeDistribution.H
src/postProcessing/functionObjects/field/regionSizeDistribution/regionSizeDistribution.C
src/postProcessing/functionObjects/field/regionSizeDistribution/regionSizeDistributionTemplates.C