OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh > Class Template Reference
Static Public Member Functions
static tmp< GeometricField< TypeR, PatchField, GeoMesh > > New (const tmp< GeometricField< Type1, PatchField, GeoMesh >> &tdf1, const word &name, const dimensionSet &dimensions)
static void clear (const tmp< GeometricField< Type1, PatchField, GeoMesh >> &tdf1)
Detailed Description
template<class TypeR, class Type1, template< class > class PatchField, class GeoMesh>
class Foam::reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh >
Definition at line 43 of file GeometricFieldReuseFunctions.H.
Member Function Documentation
static tmp<GeometricField<TypeR, PatchField, GeoMesh> > New (const tmp< GeometricField< Type1, PatchField, GeoMesh >> & tdf1, const word & name, const dimensionSet & dimensions) inline static
Definition at line 48 of file GeometricFieldReuseFunctions.H.
References reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh >::clear(), IOobject::db(), IOobject::instance(), and DimensionedField< Type, GeoMesh >::mesh().
static void clear (const tmp< GeometricField< Type1, PatchField, GeoMesh >> & tdf1) inline static
Definition at line 73 of file GeometricFieldReuseFunctions.H.
Referenced by Foam::atan2(), reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh >::New(), reuseTmpGeometricField< TypeR, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpGeometricField < TypeR, Type1, Type12, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh >::New(), Foam::pow(), and Foam::stabilise().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricFieldReuseFunctions.H