OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
tmpNrc< T >::refCount Class Reference
Public Member Functions
refCount ()
Detailed Description
template<class T>
class Foam::tmpNrc< T >::refCount
Definition at line 73 of file tmpNrc.H.
Constructor & Destructor Documentation
refCount () inline
Definition at line 77 of file tmpNrc.H.
References tmpNrc< T >::clear(), tmpNrc< T >::empty(), tmpNrc< T >::isTmp(), tmpNrc< T >::operator()(), tmpNrc< T >::operator->(), tmpNrc< T >::operator=(), tmpNrc< T >::ptr(), tmpNrc< T >::ref(), Foam::T(), tmpNrc< T >::tmpNrc(), tmpNrc< T >::typeName(), tmpNrc< T >::valid(), and tmpNrc< T >::~tmpNrc().
The documentation for this class was generated from the following file:
src/OpenFOAM/memory/tmpNrc/tmpNrc.H