OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reuseTmp< TypeR, Type1 > Class Template Reference
Static Public Member Functions
static tmp< Field< TypeR > > New (const tmp< Field< Type1 >> &tf1)
static void clear (const tmp< Field< Type1 >> &tf1)
Detailed Description
template<class TypeR, class Type1>
class Foam::reuseTmp< TypeR, Type1 >
Definition at line 37 of file FieldReuseFunctions.H.
Member Function Documentation
static tmp<Field<TypeR> > New (const tmp< Field< Type1 >> & tf1) inline static
Definition at line 41 of file FieldReuseFunctions.H.
Referenced by Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), Foam::inv(), Foam::mag(), Foam::magSqr(), Foam::pow(), Foam::sqr(), and Foam::transform().
static void clear (const tmp< Field< Type1 >> & tf1) inline static
Definition at line 46 of file FieldReuseFunctions.H.
Referenced by Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), Foam::inv(), Foam::mag(), Foam::magSqr(), reuseTmpTmp< TypeR, Type1, Type12, Type2 >::New(), reuseTmpTmp< TypeR, Type1, Type12, TypeR >::New(), reuseTmpTmp< TypeR, TypeR, TypeR, Type2 >::New(), reuseTmpTmp< TypeR, TypeR, TypeR, TypeR >::New(), Foam::pow(), Foam::sqr(), and Foam::transform().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/Fields/Field/FieldReuseFunctions.H