OpenFOAM-dev: referredWallFace Class Reference 2
referredWallFace Class Reference
Storage for referred wall faces. Stores patch index, face and associated points.
Public Member Functions
referredWallFace ()
Construct null.
referredWallFace (const face &f, const pointField &pts, label patchi)
Construct from components.
referredWallFace (const referredWallFace &)
Construct as copy.
~referredWallFace ()
Destructor.
const pointField & points () const
Return access to the stored points.
pointField & points ()
Return non-const access to the stored points.
label patchIndex () const
Return access to the patch index.
label & patchIndex ()
Return non-const access to the patch index.
bool operator== (const referredWallFace &) const
bool operator!= (const referredWallFace &) const
Public Member Functions inherited from face
face ()
Construct null.
face (label)
Construct given size.
face (const labelUList &)
Construct from list of labels.
face (const labelList &)
Construct from list of labels.
face (const Xfer< labelList > &)
Construct by transferring the parameter contents.
face (const triFace &)
Copy construct from triFace.
face (Istream &)
Construct from Istream.
label collapse ()
Collapse face by removing duplicate point labels.
void flip ()
Flip the face in-place.
pointField points (const pointField &) const
Return the points corresponding to this face.
point centre (const pointField &) const
Centre point of face.
template<class Type >
Type average (const pointField &, const Field< Type > &) const
Calculate average value at centroid of face.
scalar mag (const pointField &) const
Magnitude of face area.
vector normal (const pointField &) const
Vector normal; magnitude is equal to area of face.
face reverseFace () const
Return face with reverse direction.
label which (const label globalIndex) const
Navigation through face vertices.
label nextLabel (const label i) const
Next vertex on face.
label prevLabel (const label i) const
Previous vertex on face.
scalar sweptVol (const pointField &oldPoints, const pointField &newPoints) const
Return the volume swept out by the face when its points move.
tensor inertia (const pointField &, const point &refPt=vector::zero, scalar density=1.0) const
Return the inertia tensor, with optional reference.
pointHit ray (const point &p, const vector &n, const pointField &, const intersection::algorithm alg=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR) const
Return potential intersection with face with a ray starting.
pointHit intersection (const point &p, const vector &q, const point &ctr, const pointField &, const intersection::algorithm alg, const scalar tol=0.0) const
Fast intersection with a ray.
pointHit nearestPoint (const point &p, const pointField &) const
Return nearest point to face.
pointHit nearestPointClassify (const point &p, const pointField &, label &nearType, label &nearLabel) const
Return nearest point to face and classify it:
scalar contactSphereDiameter (const point &p, const vector &n, const pointField &) const
Return contact sphere diameter.
scalar areaInContact (const pointField &, const scalarField &v) const
Return area in contact, given the displacement in vertices.
label nEdges () const
Return number of edges.
edgeList edges () const
Return edges in face point ordering,.
edge faceEdge (const label n) const
Return n-th face edge.
int edgeDirection (const edge &) const
Return the edge direction on the face.
label nTriangles () const
Number of triangles after splitting.
label nTriangles (const pointField &points) const
Number of triangles after splitting.
label triangles (const pointField &points, label &triI, faceList &triFaces) const
Split into triangles using existing points.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
label triangles (const pointField &points, DynamicList< face, SizeInc, SizeMult, SizeDiv > &triFaces) const
Split into triangles using existing points.
label nTrianglesQuads (const pointField &points, label &nTris, label &nQuads) const
Number of triangles and quads after splitting.
label trianglesQuads (const pointField &points, label &triI, label &quadI, faceList &triFaces, faceList &quadFaces) const
Split into triangles and quads.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
Foam::label triangles (const pointField &points, DynamicList< face, SizeInc, SizeMult, SizeDiv > &triFaces) const
Public Member Functions inherited from List< label >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const label &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< label > &)
Copy constructor.
List (const Xfer< List< label >> &)
Construct by transferring the parameter contents.
List (List< label > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< label > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< label, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< label > &)
Construct as copy of PtrList<T>
List (const SLList< label > &)
Construct as copy of SLList<T>
List (const UIndirectList< label > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< label > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< label > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const label &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const label &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const label &)
Append an element at the end of the list.
void append (const UList< label > &)
Append a List at the end of this list.
void append (const UIndirectList< label > &)
Append a UIndirectList at the end of this list.
void transfer (List< label > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< label, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< label > &)
Transfer the contents of the argument List into this list.
Xfer< List< label > > xfer ()
Transfer contents to the Xfer container.
label & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< label > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< label > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< label > &)
Assignment operator. Takes linear time.
void operator= (const SLList< label > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< label > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< label > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const label &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Friends
Istream & operator>> (Istream &, referredWallFace &)
Ostream & operator<< (Ostream &, const referredWallFace &)
Additional Inherited Members
Public Types inherited from face
enum proxType { NONE, POINT, EDGE }
Return types for classify.
Public Types inherited from List< label >
typedef SubList< label > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from face
static int compare (const face &, const face &)
Compare faces.
static bool sameVertices (const face &, const face &)
Return true if the faces have the same vertices.
Static Public Member Functions inherited from List< label >
static const List< label > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes inherited from face
static const char *const typeName = "face"
Protected Member Functions inherited from List< label >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
Storage for referred wall faces. Stores patch index, face and associated points.
Source files
referredWallFace.H
referredWallFaceI.H
referredWallFace.C
Definition at line 61 of file referredWallFace.H.
Constructor & Destructor Documentation
referredWallFace ()
Construct null.
Definition at line 30 of file referredWallFace.C.
referredWallFace (const face & f, const pointField & pts, label patchi)
Construct from components.
Definition at line 39 of file referredWallFace.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, List< T >::size(), and List< label >::size().
referredWallFace (const referredWallFace & rWF)
Construct as copy.
Definition at line 58 of file referredWallFace.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, List< T >::size(), and List< label >::size().
~referredWallFace ()
Destructor.
Definition at line 75 of file referredWallFace.C.
Member Function Documentation
const Foam::pointField & points () const inline
Return access to the stored points.
Definition at line 30 of file referredWallFaceI.H.
Foam::pointField & points () inline
Return non-const access to the stored points.
Definition at line 36 of file referredWallFaceI.H.
Foam::label patchIndex () const inline
Return access to the patch index.
Definition at line 42 of file referredWallFaceI.H.
Foam::label & patchIndex () inline
Return non-const access to the patch index.
Definition at line 48 of file referredWallFaceI.H.
bool operator== (const referredWallFace & rhs) const
Definition at line 81 of file referredWallFace.C.
bool operator!= (const referredWallFace & rhs) const
Definition at line 92 of file referredWallFace.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , referredWallFace &) friend
Ostream& operator<< (Ostream & , const referredWallFace &) friend
The documentation for this class was generated from the following files:
src/lagrangian/basic/InteractionLists/referredWallFace/referredWallFace.H
src/lagrangian/basic/InteractionLists/referredWallFace/referredWallFace.C
src/lagrangian/basic/InteractionLists/referredWallFace/referredWallFaceI.H