OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
refinementData Class Reference
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
Public Member Functions
refinementData ()
Construct null.
refinementData (const label refinementCount, const label count)
Construct from count.
label refinementCount () const
label & refinementCount ()
label count () const
label & count ()
bool isRefined () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const refinementData &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const refinementData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const refinementData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const refinementData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const refinementData &, TrackingData &td) const
Same (like operator==)
bool operator== (const refinementData &) const
bool operator!= (const refinementData &) const
Friends
Ostream & operator<< (Ostream &, const refinementData &)
Istream & operator>> (Istream &, refinementData &)
Detailed Description
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
Source files
refinementData.H
refinementDataI.H
refinementData.C
Definition at line 54 of file refinementData.H.
Constructor & Destructor Documentation
refinementData () inline
Construct null.
Definition at line 29 of file refinementDataI.H.
refinementData (const label refinementCount, const label count) inline
Construct from count.
Definition at line 38 of file refinementDataI.H.
Member Function Documentation
label refinementCount () const inline
Definition at line 79 of file refinementData.H.
Referenced by hexRef8::consistentSlowRefinement(), refinementData::operator==(), refinementData::updateCell(), and refinementData::updateFace().
label& refinementCount () inline
Definition at line 84 of file refinementData.H.
label count () const inline
Definition at line 89 of file refinementData.H.
Referenced by hexRef8::consistentSlowRefinement(), refinementData::operator==(), refinementData::updateCell(), and refinementData::updateFace().
label& count () inline
Definition at line 94 of file refinementData.H.
bool isRefined () const inline
Definition at line 99 of file refinementData.H.
Referenced by hexRef8::consistentSlowRefinement(), and refinementData::updateCell().
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 51 of file refinementDataI.H.
bool sameGeometry (const polyMesh & , const refinementData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 60 of file refinementDataI.H.
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 74 of file refinementDataI.H.
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 98 of file refinementDataI.H.
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 87 of file refinementDataI.H.
bool updateCell (const polyMesh & , const label thisCellI, const label neighbourFaceI, const refinementData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 111 of file refinementDataI.H.
References Foam::abort(), refinementData::count(), Foam::FatalError, FatalErrorInFunction, refinementData::isRefined(), Foam::max(), and refinementData::refinementCount().
bool updateFace (const polyMesh & , const label thisFaceI, const label neighbourCellI, const refinementData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 173 of file refinementDataI.H.
References refinementData::count(), and refinementData::refinementCount().
Referenced by hexRef8::consistentSlowRefinement().
bool updateFace (const polyMesh & , const label thisFaceI, const refinementData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 208 of file refinementDataI.H.
References refinementData::count(), and refinementData::refinementCount().
bool equal (const refinementData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 241 of file refinementDataI.H.
References Foam::operator==().
bool operator== (const refinementData & rhs) const inline
Definition at line 252 of file refinementDataI.H.
References refinementData::count(), and refinementData::refinementCount().
bool operator!= (const refinementData & rhs) const inline
Definition at line 259 of file refinementDataI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const refinementData &) friend
Istream& operator>> (Istream & , refinementData &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementData.H
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementDataI.H