OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
repatchPolyTopoChanger Class Reference
A mesh which allows changes in the patch distribution of the boundary faces. The change in patching is set using changePatchID. For a boundary face, a new patch ID is given.
Public Member Functions
repatchPolyTopoChanger (polyMesh &mesh)
Construct for given mesh.
virtual ~repatchPolyTopoChanger ()
Destructor.
void changePatches (const List< polyPatch * > &patches)
Change patches.
void changePatchID (const label faceID, const label patchID)
Change patch ID for a boundary face. Note: patchID should be in new.
void setFaceZone (const label faceID, const label zoneID, const bool zoneFlip)
Set zone ID for a face.
void changeAnchorPoint (const label faceID, const label fp)
Change anchor point (zero'th point of face) for a boundary face.
void repatch ()
Re-patch the mesh.
Detailed Description
A mesh which allows changes in the patch distribution of the boundary faces. The change in patching is set using changePatchID. For a boundary face, a new patch ID is given.
Source files
repatchPolyTopoChanger.H
repatchPolyTopoChanger.C
Definition at line 51 of file repatchPolyTopoChanger.H.
Constructor & Destructor Documentation
repatchPolyTopoChanger (polyMesh & mesh) explicit
Construct for given mesh.
Definition at line 52 of file repatchPolyTopoChanger.C.
virtual ~repatchPolyTopoChanger () inline virtual
Destructor.
Definition at line 83 of file repatchPolyTopoChanger.H.
Member Function Documentation
void changePatches (const List< polyPatch * > & patches)
Change patches.
Definition at line 62 of file repatchPolyTopoChanger.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, and Foam::nl.
Referenced by boundaryMesh::patchify().
void changePatchID (const label faceID, const label patchID)
Change patch ID for a boundary face. Note: patchID should be in new.
numbering.
Definition at line 82 of file repatchPolyTopoChanger.C.
References Foam::abort(), Foam::FatalError, FatalErrorIn, faceZone::flipMap(), and faceZone::whichFace().
Referenced by boundaryMesh::patchify().
void setFaceZone (const label faceID, const label zoneID, const bool zoneFlip)
Set zone ID for a face.
Definition at line 141 of file repatchPolyTopoChanger.C.
References Foam::abort(), Foam::FatalError, and FatalErrorIn.
void changeAnchorPoint (const label faceID, const label fp)
Change anchor point (zero'th point of face) for a boundary face.
Definition at line 185 of file repatchPolyTopoChanger.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorIn, faceZone::flipMap(), forAll, List< T >::size(), and faceZone::whichFace().
void repatch ()
Re-patch the mesh.
Definition at line 295 of file repatchPolyTopoChanger.C.
Referenced by boundaryMesh::patchify().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/repatchPolyTopoChanger/repatchPolyTopoChanger.H
src/dynamicMesh/polyTopoChange/repatchPolyTopoChanger/repatchPolyTopoChanger.C