OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
RNGkEpsilon< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Renormalization group k-epsilon turbulence model for incompressible and compressible flows.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel >::alphaField alphaField
typedef RASModel< BasicTurbulenceModel >::rhoField rhoField
typedef RASModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel >::alphaField alphaField
typedef RASModel< BasicTurbulenceModel >::rhoField rhoField
typedef RASModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("RNGkEpsilon")
Runtime type information.
RNGkEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~RNGkEpsilon ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual void correctNut ()
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
dimensionedScalar eta0_
dimensionedScalar beta_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::RNGkEpsilon< BasicTurbulenceModel >
Renormalization group k-epsilon turbulence model for incompressible and compressible flows.
Reference:
    Yakhot, V., Orszag, S. A., Thangam, S.,
    Gatski, T. B., & Speziale, C. G. (1992).
    Development of turbulence models for shear flows
    by a double expansion technique.
    Physics of Fluids A: Fluid Dynamics (1989-1993), 4(7), 1510-1520.
For the RDT-based compression term:
    El Tahry, S. H. (1983).
    k-epsilon equation for compressible reciprocating engine flows.
    Journal of Energy, 7(4), 345-353.
The default model coefficients are
    RNGkEpsilonCoeffs
    {
        Cmu         0.0845;
        C1          1.42;
        C2          1.68;
        C3          -0.33;
        sigmak      0.71942;
        sigmaEps    0.71942;
        eta0        4.38;
        beta        0.012;
    }
Source files
RNGkEpsilon.H
RNGkEpsilon.C
Definition at line 85 of file RNGkEpsilon.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 127 of file RNGkEpsilon.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 128 of file RNGkEpsilon.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 129 of file RNGkEpsilon.H.
Constructor & Destructor Documentation
RNGkEpsilon (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 82 of file RNGkEpsilon.C.
References Foam::bound().
virtual ~RNGkEpsilon () inline virtual
Destructor.
Definition at line 153 of file RNGkEpsilon.H.
Member Function Documentation
void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 39 of file RNGkEpsilon.C.
References Foam::sqr().
tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 49 of file RNGkEpsilon.C.
References Foam::dimTime, and Foam::dimVolume.
tmp< fvScalarMatrix > epsilonSource () const protected virtual
Definition at line 64 of file RNGkEpsilon.C.
References Foam::dimTime, and Foam::dimVolume.
TypeName ("RNGkEpsilon< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Re-read model coefficients if they have changed.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 217 of file RNGkEpsilon.C.
References Foam::read().
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 163 of file RNGkEpsilon.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
tmp<volScalarField> DepsilonEff () const inline
Return the effective diffusivity for epsilon.
Definition at line 176 of file RNGkEpsilon.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 189 of file RNGkEpsilon.H.
References RNGkEpsilon< BasicTurbulenceModel >::k_.
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 195 of file RNGkEpsilon.H.
References RNGkEpsilon< BasicTurbulenceModel >::epsilon_.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 240 of file RNGkEpsilon.C.
References Foam::fvc::absolute(), Foam::bound(), tmp< T >::clear(), correct, Foam::fvm::ddt(), Foam::dev(), Foam::fvm::div(), Foam::fvc::div(), divU(), Foam::constant::universal::G, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::mag(), nut, phi, R, Foam::solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::sqrt(), Foam::fvm::SuSp(), and Foam::twoSymm().
Member Data Documentation
dimensionedScalar Cmu_ protected
Definition at line 102 of file RNGkEpsilon.H.
dimensionedScalar C1_ protected
Definition at line 103 of file RNGkEpsilon.H.
dimensionedScalar C2_ protected
Definition at line 104 of file RNGkEpsilon.H.
dimensionedScalar C3_ protected
Definition at line 105 of file RNGkEpsilon.H.
dimensionedScalar sigmak_ protected
Definition at line 106 of file RNGkEpsilon.H.
dimensionedScalar sigmaEps_ protected
Definition at line 107 of file RNGkEpsilon.H.
dimensionedScalar eta0_ protected
Definition at line 108 of file RNGkEpsilon.H.
dimensionedScalar beta_ protected
Definition at line 109 of file RNGkEpsilon.H.
volScalarField k_ protected
Definition at line 114 of file RNGkEpsilon.H.
Referenced by RNGkEpsilon< BasicTurbulenceModel >::k().
volScalarField epsilon_ protected
Definition at line 115 of file RNGkEpsilon.H.
Referenced by RNGkEpsilon< BasicTurbulenceModel >::epsilon().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/RNGkEpsilon/RNGkEpsilon.H
src/TurbulenceModels/turbulenceModels/RAS/RNGkEpsilon/RNGkEpsilon.C