OpenFOAM: readFields Class Reference
readFields Class Reference
FunctionObjects » Field function objects
This function object reads fields from the time directories and adds them to the mesh database for further post-processing.
Public Member Functions
TypeName ("readFields")
Runtime type information.
readFields (const word &name, const Time &runTime, const dictionary &dict)
Construct for given objectRegistry and dictionary.
virtual ~readFields ()
Destructor.
virtual bool read (const dictionary &)
Read the set of fields from dictionary.
virtual bool execute ()
Read the fields.
virtual bool write ()
Do nothing.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
template<class Type >
void loadField (const word &, PtrList< GeometricField< Type, fvPatchField, volMesh >> &, PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &) const
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
wordList fieldSet_
Fields to load.
PtrList< volScalarField > vsf_
Loaded fields.
PtrList< volVectorField > vvf_
PtrList< volSphericalTensorField > vSpheretf_
PtrList< volSymmTensorField > vSymmtf_
PtrList< volTensorField > vtf_
PtrList< surfaceScalarField > ssf_
PtrList< surfaceVectorField > svf_
PtrList< surfaceSphericalTensorField > sSpheretf_
PtrList< surfaceSymmTensorField > sSymmtf_
PtrList< surfaceTensorField > stf_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
This function object reads fields from the time directories and adds them to the mesh database for further post-processing.
Example of function object specification:
readFields1
{
    type        readFields;
    libs ("libfieldFunctionObjects.so");
    ...
    fields
    (
        U
        p
    );
}
Usage
Property Description Required Default value
type type name: readFields yes
fields list of fields to read no
See also
Foam::functionObjects::fvMeshFunctionObject
Source files
readFields.H
readFields.C
Definition at line 96 of file readFields.H.
Constructor & Destructor Documentation
readFields (const word & name, const Time & runTime, const dictionary & dict)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 46 of file readFields.C.
References Foam::read().
~readFields () virtual
Destructor.
Definition at line 61 of file readFields.C.
Member Function Documentation
void loadField (const word & fieldName, PtrList< GeometricField< Type, fvPatchField, volMesh >> & vflds, PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> & sflds) const protected
Definition at line 35 of file readFieldsTemplates.C.
References DebugInfo, Foam::endl(), and Log.
TypeName ("readFields")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the set of fields from dictionary.
Reimplemented from regionFunctionObject.
Definition at line 67 of file readFields.C.
References dictionary::lookup(), and regionFunctionObject::read().
bool execute () virtual
Read the fields.
Implements functionObject.
Definition at line 77 of file readFields.C.
References forAll.
bool write () virtual
Do nothing.
Implements functionObject.
Definition at line 108 of file readFields.C.
Member Data Documentation
wordList fieldSet_ protected
Fields to load.
Definition at line 105 of file readFields.H.
PtrList<volScalarField> vsf_ protected
Loaded fields.
Definition at line 108 of file readFields.H.
PtrList<volVectorField> vvf_ protected
Definition at line 109 of file readFields.H.
PtrList<volSphericalTensorField> vSpheretf_ protected
Definition at line 110 of file readFields.H.
PtrList<volSymmTensorField> vSymmtf_ protected
Definition at line 111 of file readFields.H.
PtrList<volTensorField> vtf_ protected
Definition at line 112 of file readFields.H.
PtrList<surfaceScalarField> ssf_ protected
Definition at line 114 of file readFields.H.
PtrList<surfaceVectorField> svf_ protected
Definition at line 115 of file readFields.H.
PtrList<surfaceSphericalTensorField> sSpheretf_ protected
Definition at line 116 of file readFields.H.
PtrList<surfaceSymmTensorField> sSymmtf_ protected
Definition at line 117 of file readFields.H.
PtrList<surfaceTensorField> stf_ protected
Definition at line 118 of file readFields.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/readFields/readFields.H
src/functionObjects/field/readFields/readFields.C
src/functionObjects/field/readFields/readFieldsTemplates.C