OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reuseTmpTmpDimensionedField< TypeR, Type1, Type12, Type2, GeoMesh > Class Template Reference
Static Public Member Functions
static tmp< DimensionedField< TypeR, GeoMesh > > New (const tmp< DimensionedField< Type1, GeoMesh > > &tdf1, const tmp< DimensionedField< Type2, GeoMesh > > &tdf2, const word &name, const dimensionSet &dimensions)
static void clear (const tmp< DimensionedField< Type1, GeoMesh > > &tdf1, const tmp< DimensionedField< Type2, GeoMesh > > &tdf2)
Detailed Description
template<class TypeR, class Type1, class Type12, class Type2, class GeoMesh>
class Foam::reuseTmpTmpDimensionedField< TypeR, Type1, Type12, Type2, GeoMesh >
Definition at line 124 of file DimensionedFieldReuseFunctions.H.
Member Function Documentation
static tmp<DimensionedField<TypeR, GeoMesh> > New (const tmp< DimensionedField< Type1, GeoMesh > > & tdf1, const tmp< DimensionedField< Type2, GeoMesh > > & tdf2, const word & name, const dimensionSet & dimensions) inline static
Definition at line 129 of file DimensionedFieldReuseFunctions.H.
References IOobject::db(), IOobject::instance(), and DimensionedField< Type, GeoMesh >::mesh().
Referenced by Foam::atan2(), and Foam::pow().
static void clear (const tmp< DimensionedField< Type1, GeoMesh > > & tdf1, const tmp< DimensionedField< Type2, GeoMesh > > & tdf2) inline static
Definition at line 155 of file DimensionedFieldReuseFunctions.H.
Referenced by Foam::atan2(), and Foam::pow().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedFieldReuseFunctions.H