OpenFOAM: ReactionList< ThermoType > Class Template Reference
ReactionList< ThermoType > Class Template Reference
List of templated reactions.
Public Member Functions
ReactionList (const speciesTable &species, const HashPtrTable< ThermoType > &thermoDatabase)
Construct null.
ReactionList (const speciesTable &species, const HashPtrTable< ThermoType > &thermoDatabase, const dictionary &dict)
Construct from dictionary.
ReactionList (const speciesTable &species, const HashPtrTable< ThermoType > &thermoDatabase, const fileName &fName)
Construct from file using (Istream)
ReactionList (const ReactionList< ThermoType > &reactions)
Construct copy.
~ReactionList ()
Destructor.
bool readReactionDict ()
Read reactions from dictionary.
void write (Ostream &os) const
Write.
Public Member Functions inherited from SLPtrList< Reaction< ThermoType > >
SLPtrList ()
Null construct.
SLPtrList (Reaction< ThermoType > *a)
Construct given initial T*.
SLPtrList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
SLPtrList (Istream &is)
Construct from Istream.
Public Member Functions inherited from LPtrList< LListBase, T >
LPtrList ()
Null construct.
LPtrList (T *a)
Construct given initial T.
template<class INew >
LPtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
LPtrList (Istream &)
Construct from Istream using default Istream constructor class.
LPtrList (const LPtrList &)
Construct as copy.
~LPtrList ()
Destructor.
T & first ()
Return the first entry added.
const T & first () const
Return const access to the first entry added.
T & last ()
Return the last entry added.
const T & last () const
Return const access to the last entry added.
bool eraseHead ()
Remove the head element from the list and delete the pointer.
void clear ()
Clear the contents of the list.
void transfer (LPtrList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const LPtrList< LListBase, T > &)
Assign copy.
Public Member Functions inherited from LList< LListBase, T * >
LList ()
Null construct.
LList (T * a)
Construct given initial T.
LList (Istream &)
Construct from Istream.
LList (const LList< LListBase, T * > &)
Construct as copy.
~LList ()
Destructor.
T * & first ()
Return the first entry added.
const T * & first () const
Return const access to the first entry added.
T * & last ()
Return the last entry added.
const T * & last () const
Return const access to the last entry added.
void insert (const T * &a)
Add at head of list.
void append (const T * &a)
Add at tail of list.
T * removeHead ()
Remove and return head.
T * remove (link *l)
Remove and return element.
T * remove (iterator &it)
Remove and return element specified by iterator.
void clear ()
Delete contents of list.
void transfer (LList< LListBase, T * > &)
Transfer the contents of the argument into this List.
void operator= (const LList< LListBase, T * > &)
iterator begin ()
const_iterator begin () const
const iterator & end ()
const const_iterator & end () const
const_iterator cbegin () const
const const_iterator & cend () const
Additional Inherited Members
Public Types inherited from LPtrList< LListBase, T >
typedef T & reference
Type that can be used for storing into LPtrList::value_type.
typedef T & const_reference
Type that can be used for storing into constant.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Public Types inherited from LList< LListBase, T * >
typedef T * value_type
Type of values the LList contains.
typedef T * & reference
Type that can be used for storing into value_type.
typedef const T * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a LList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Detailed Description
template<class ThermoType>
class Foam::ReactionList< ThermoType >
List of templated reactions.
Source files
ReactionList.H
ReactionList.C
Definition at line 54 of file ReactionList.H.
Constructor & Destructor Documentation
ReactionList (const speciesTable & species, const HashPtrTable< ThermoType > & thermoDatabase)
Construct null.
Definition at line 34 of file ReactionList.C.
Referenced by ReactionList< ThermoType >::ReactionList().
ReactionList (const speciesTable & species, const HashPtrTable< ThermoType > & thermoDatabase, const dictionary & dict)
Construct from dictionary.
Definition at line 48 of file ReactionList.C.
References ReactionList< ThermoType >::ReactionList().
ReactionList (const speciesTable & species, const HashPtrTable< ThermoType > & thermoDatabase, const fileName & fName)
Construct from file using (Istream)
Definition at line 65 of file ReactionList.C.
References ReactionList< ThermoType >::ReactionList().
ReactionList (const ReactionList< ThermoType > & reactions)
Construct copy.
~ReactionList ()
Destructor.
Definition at line 95 of file ReactionList.C.
Member Function Documentation
bool readReactionDict ()
Read reactions from dictionary.
Definition at line 102 of file ReactionList.C.
References forAllConstIter().
void write (Ostream & os) const
Write.
Definition at line 126 of file ReactionList.C.
References Foam::decrIndent(), forAllConstIter(), Foam::incrIndent(), Foam::indent(), Reaction< ReactionThermo >::name(), Foam::nl, Reaction< ReactionThermo >::write(), and Ostream::writeKeyword().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/ReactionList/ReactionList.H
src/thermophysicalModels/specie/reaction/Reactions/ReactionList/ReactionList.C