OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionCoupledBaseGAMGInterface Class Reference
Base class for GAMG agglomerated coupled region interface.
Public Member Functions
regionCoupledBaseGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &restrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Construct from fine level interface,.
virtual ~regionCoupledBaseGAMGInterface ()
Destructor.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Transfer and return internal field adjacent to the interface.
virtual label neighbPatchID () const
Cyclic interface functions.
virtual bool owner () const
Is it owner?
virtual const regionCoupledBaseGAMGInterface & neighbPatch () const
Return neighb regionCoupledLduInterface.
virtual const polyMesh & nbrMesh () const
Return AMI.
const lduInterface & nbrLduInterface (const label fineLevelIndex, const label index) const
Public Member Functions inherited from GAMGInterface
TypeName ("GAMGInterface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterface, lduInterface,(const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm),(index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr, GAMGInterface, Istream,(const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is),(index, coarseInterfaces, is))
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces)
Construct from interfaces, restrict addressing set later on.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddressing)
Construct from interfaces and restrict addressing.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Construct from Istream.
virtual label size () const
Return size.
virtual label index () const
virtual const lduInterfacePtrsList & coarseInterfaces () const
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual const labelList & faceRestrictAddressing () const
Return (local)face restrict addressing.
virtual labelList & faceRestrictAddressing ()
Return non-const access to face restrict addressing.
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData) const
Return the interface internal field of the given field.
template<class Type >
void interfaceInternalField (const UList< Type > &internalData, List< Type > &) const
Get the interface internal field of the given field.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
void combine (const GAMGInterface &)
Merge the next level with this level.
virtual tmp< scalarField > agglomerateCoeffs (const scalarField &fineCoeffs) const
Agglomerating the given fine-level coefficients and return.
virtual void write (Ostream &) const =0
Write to stream.
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF) const
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
Public Member Functions inherited from regionCoupledLduInterface
TypeName ("regionCoupledLduInterface")
Runtime type information.
regionCoupledLduInterface ()
Construct null.
virtual ~regionCoupledLduInterface ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterface
static autoPtr< GAMGInterface > New (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterface > New (const word &coupleType, const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Return a pointer to a new interface created on freestore given.
Protected Attributes inherited from GAMGInterface
const label index_
My index in coarseInterfaces.
const lduInterfacePtrsList & coarseInterfaces_
All interfaces.
labelList faceCells_
Face-cell addressing.
labelList faceRestrictAddressing_
Face restrict addressing.
Detailed Description
Base class for GAMG agglomerated coupled region interface.
Source files
regionCoupledBaseGAMGInterface.H
regionCoupledBaseGAMGInterface.C
Definition at line 50 of file regionCoupledBaseGAMGInterface.H.
Constructor & Destructor Documentation
regionCoupledBaseGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const lduInterface & fineInterface, const labelField & restrictAddressing, const labelField & neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Construct from fine level interface,.
local and neighbour restrict addressing
Definition at line 35 of file regionCoupledBaseGAMGInterface.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::find(), forAll, and List< T >::size().
~regionCoupledBaseGAMGInterface () virtual
Destructor.
Definition at line 207 of file regionCoupledBaseGAMGInterface.C.
References regionCoupledBaseGAMGInterface::internalFieldTransfer().
Member Function Documentation
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Transfer and return internal field adjacent to the interface.
Implements lduInterface.
Definition at line 215 of file regionCoupledBaseGAMGInterface.C.
Referenced by regionCoupledBaseGAMGInterface::~regionCoupledBaseGAMGInterface().
virtual label neighbPatchID () const inline virtual
Cyclic interface functions.
Return neigbour processor number
Implements regionCoupledLduInterface.
Definition at line 112 of file regionCoupledBaseGAMGInterface.H.
References regionCoupledLduInterface::neighbPatchID().
virtual bool owner () const inline virtual
Is it owner?
Implements regionCoupledLduInterface.
Definition at line 117 of file regionCoupledBaseGAMGInterface.H.
References regionCoupledLduInterface::owner().
virtual const regionCoupledBaseGAMGInterface& neighbPatch () const inline virtual
Return neighb regionCoupledLduInterface.
Implements regionCoupledLduInterface.
Definition at line 122 of file regionCoupledBaseGAMGInterface.H.
References regionCoupledLduInterface::neighbPatch().
virtual const polyMesh& nbrMesh () const inline virtual
Return AMI.
virtual const AMIPatchToPatchInterpolation& AMI() const = 0;Return nbrMesh
Implements regionCoupledLduInterface.
Definition at line 135 of file regionCoupledBaseGAMGInterface.H.
References regionCoupledBaseGAMGInterface::nbrLduInterface(), and regionCoupledLduInterface::nbrMesh().
Referenced by regionCoupledBaseGAMGInterface::nbrLduInterface().
const lduInterface& nbrLduInterface (const label fineLevelIndex, const label index) const inline
Definition at line 141 of file regionCoupledBaseGAMGInterface.H.
References GAMGInterface::index(), lduMesh::interfaces(), objectRegistry::lookupObject(), mesh, GAMGAgglomeration::meshLevel(), regionCoupledBaseGAMGInterface::nbrMesh(), and polyMesh::thisDb().
Referenced by regionCoupledBaseGAMGInterface::nbrMesh().
The documentation for this class was generated from the following files:
src/meshTools/regionCoupled/GAMG/interfaces/regionCoupledGAMGInterface/regionCoupledBaseGAMGInterface.H
src/meshTools/regionCoupled/GAMG/interfaces/regionCoupledGAMGInterface/regionCoupledBaseGAMGInterface.C