OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
regionModel Class Reference
Public Member Functions
TypeName ("regionModel")
Runtime type information.
regionModel (const fvMesh &mesh, const word &regionType)
Construct null.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
Construct from mesh and name and dict.
virtual ~regionModel ()
Destructor.
const fvMesh & primaryMesh () const
Return the reference to the primary mesh database.
const Time & time () const
Return the reference to the time database.
const Switch & active () const
Return the active flag.
const Switch & infoOutput () const
Return the information flag.
const word & modelName () const
Return the model name.
const fvMesh & regionMesh () const
Return the region mesh database.
fvMesh & regionMesh ()
Return the region mesh database for manipulation.
const dictionary & coeffs () const
Return the model coefficients dictionary.
const dictionary & solution () const
Return the solution dictionary.
const IOdictionary & outputProperties () const
Return const access to the output properties dictionary.
IOdictionary & outputProperties ()
Return output properties dictionary.
bool isCoupledPatch (const label regionPatchi) const
Return true if patchI on the local region is a coupled.
bool isRegionPatch (const label primaryPatchi) const
Return true if patchI on the primary region is a coupled.
const labelList & primaryPatchIDs () const
Return the list of patch IDs on the primary region coupled.
const labelList & intCoupledPatchIDs () const
Return the list of patch IDs internally coupled with the.
label regionPatchID (const label primaryPatchID) const
Return region ID corresponding to primaryPatchID.
label nbrCoupledPatchID (const regionModel &nbrRegion, const label regionPatchi) const
Return the coupled patch ID paired with coupled patch.
template<class Type >
tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > &nbrField, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip=false) const
Map patch internal field from another region model to local.
template<class Type >
void toPrimary (const label regionPatchi, List< Type > &regionField) const
Convert a local region field to the primary region.
template<class Type >
void toRegion (const label regionPatchi, List< Type > &primaryFieldField) const
Convert a primary region field to the local region.
template<class Type , class CombineOp >
void toPrimary (const label regionPatchi, List< Type > &regionField, const CombineOp &cop) const
Convert a local region field to the primary region with op.
template<class Type , class CombineOp >
void toRegion (const label regionPatchi, List< Type > &primaryFieldField, const CombineOp &cop) const
Convert a primary region field to the local region with op.
virtual void evolve ()
Main driver routing to evolve the region - calls other evolves.
virtual void preEvolveRegion ()
Pre-evolve region.
virtual void evolveRegion ()
Evolve the region.
virtual void postEvolveRegion ()
Post-evolve region.
virtual void info ()
Provide some feedback.
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > &nbrField, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip) const
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
iterator begin ()
const_iterator begin () const
const iterator & end ()
const const_iterator & end () const
const_iterator cbegin () const
const const_iterator & cend () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Protected Member Functions
virtual bool read ()
Read control parameters from dictionary.
virtual bool read (const dictionary &dict)
Read control parameters from dictionary.
virtual const AMIPatchToPatchInterpolation & interRegionAMI (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const bool flip) const
Create or return a new inter-region AMI object.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
const fvMesh & primaryMesh_
Reference to the primary mesh database.
const Time & time_
Reference to the time database.
Switch active_
Active flag.
Switch infoOutput_
Active information output.
const word modelName_
Model name.
autoPtr< fvMesh > regionMeshPtr_
Pointer to the region mesh database.
dictionary coeffs_
Model coefficients dictionary.
autoPtr< IOdictionary > outputPropertiesPtr_
Dictionary of output properties.
labelList primaryPatchIDs_
List of patch IDs on the primary region coupled to this region.
labelList intCoupledPatchIDs_
List of patch IDs internally coupled with the primary region.
word regionName_
Region name.
regionModelFunctionObjectList functions_
Region model function objects.
wordList interRegionAMINames_
List of region names this region is coupled to.
PtrList< PtrList< AMIPatchToPatchInterpolation > > interRegionAMI_
List of AMI objects per coupled region.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase::iterator LListBase_iterator
typedef DLListBase::const_iterator LListBase_const_iterator
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Definition at line 57 of file regionModel.H.
Constructor & Destructor Documentation
regionModel (const fvMesh & mesh, const word & regionType)
Construct null.
Definition at line 373 of file regionModel.C.
regionModel (const fvMesh & mesh, const word & regionType, const word & modelName, bool readFields = true)
Construct from mesh, region type and name.
Definition at line 407 of file regionModel.C.
References Foam::read().
regionModel (const fvMesh & mesh, const word & regionType, const word & modelName, const dictionary & dict, bool readFields = true)
Construct from mesh and name and dict.
Definition at line 452 of file regionModel.C.
References Foam::read().
~regionModel () virtual
Destructor.
Definition at line 501 of file regionModel.C.
Member Function Documentation
bool read () protected virtual
Read control parameters from dictionary.
Reimplemented from regIOobject.
Reimplemented in kinematicSingleLayer, thermoSingleLayer, reactingOneDim, thermalBaffle, regionModel1D, thermalBaffleModel, singleLayerRegion, surfaceFilmModel, pyrolysisModel, noPyrolysis, noThermo, and noFilm.
Definition at line 171 of file regionModel.C.
References regIOobject::read().
Referenced by singleLayerRegion::read(), and regionModel1D::read().
bool read (const dictionary & dict) protected virtual
Read control parameters from dictionary.
Reimplemented in reactingOneDim, thermalBaffle, regionModel1D, thermalBaffleModel, pyrolysisModel, and noPyrolysis.
Definition at line 194 of file regionModel.C.
References regionModel::interRegionAMI(), and dictionary::subDictPtr().
const Foam::AMIPatchToPatchInterpolation & interRegionAMI (const regionModel & nbrRegion, const label regionPatchi, const label nbrPatchi, const bool flip) const protected virtual
Create or return a new inter-region AMI object.
Definition at line 216 of file regionModel.C.
References polyPatch::boundaryMesh(), Foam::findIndex(), AMIInterpolation< SourcePatch, TargetPatch >::imFaceAreaWeight, UPstream::msgType(), IOdictionary::name(), regionModel::nbrCoupledPatchID(), p, regionModel::regionMesh(), UPtrList< T >::size(), and faceAreaIntersect::tmMesh.
Referenced by regionModel::read().
TypeName ("regionModel")
Runtime type information.
const Foam::fvMesh & primaryMesh () const inline
Return the reference to the primary mesh database.
Definition at line 31 of file regionModelI.H.
References regionModel::primaryMesh_.
Referenced by noThermo::Cp(), pyrolysisModelCollection::evolve(), liquidFilmThermo::initLiquid(), noFilm::primaryMassTrans(), kinematicSingleLayer::primaryMassTrans(), noFilm::Sh(), thermoSingleLayer::Sh(), kinematicSingleLayer::Sh(), noFilm::Srho(), thermoSingleLayer::Srho(), kinematicSingleLayer::Srho(), thermoSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
const Foam::Time & time () const inline
Return the reference to the time database.
Definition at line 37 of file regionModelI.H.
References regionModel::time_.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcUTau(), contactAngleForce::correct(), noThermo::Cp(), kinematicSingleLayer::deltaMass(), reactingOneDim::evolveRegion(), kinematicSingleLayer::gNorm(), kinematicSingleLayer::gNormClipped(), kinematicSingleLayer::gTan(), constantHeatTransfer::h(), thermoSingleLayer::hs(), phaseChangeModel::info(), kinematicSingleLayer::kinematicSingleLayer(), mappedVariableThicknessWallFvPatch::makeDeltaCoeffs(), kinematicSingleLayer::netMass(), filmSubModelBase::outputTime(), noFilm::primaryMassTrans(), kinematicSingleLayer::primaryMassTrans(), noFilm::Sh(), thermoSingleLayer::Sh(), kinematicSingleLayer::Sh(), constantRadiation::Shs(), reactingOneDim::solidRegionDiffNo(), thermalBaffle::solveEnergy(), noFilm::Srho(), thermoSingleLayer::Srho(), kinematicSingleLayer::Srho(), thermoSingleLayer::T(), thermoSingleLayer::thermoSingleLayer(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), thermoSingleLayer::updateSubmodels(), and kinematicSingleLayer::updateSubmodels().
const Foam::Switch & active () const inline
Return the active flag.
Definition at line 43 of file regionModelI.H.
References regionModel::active_.
Referenced by pyrolysisModelCollection::evolve(), SurfaceFilmModel< CloudType >::inject(), and noPyrolysis::noPyrolysis().
const Foam::Switch & infoOutput () const inline
Return the information flag.
Definition at line 49 of file regionModelI.H.
References regionModel::infoOutput_.
Referenced by pyrolysisModelCollection::evolve().
const Foam::word & modelName () const inline
Return the model name.
Definition at line 55 of file regionModelI.H.
References regionModel::modelName_.
Referenced by pyrolysisModelCollection::evolve().
const Foam::fvMesh & regionMesh () const inline
Return the region mesh database.
Definition at line 61 of file regionModelI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, objectRegistry::foundObject(), objectRegistry::lookupObject(), regionModel::regionMeshPtr_, regionModel::regionName_, and regionModel::time_.
Referenced by noPyrolysis::constructThermoChemistry(), patchInjection::correct(), contactAngleForce::correct(), drippingInjection::correct(), curvatureSeparation::correct(), thixotropicViscosity::correct(), solidification::correctModel(), kinematicSingleLayer::CourantNumber(), curvatureSeparation::curvatureSeparation(), reactingOneDim::evolveRegion(), kinematicSingleLayer::gNorm(), kinematicSingleLayer::gNormClipped(), kinematicSingleLayer::gTan(), constantHeatTransfer::h(), thermoSingleLayer::hs(), injectionModelList::info(), thermalBaffle::info(), reactingOneDim::info(), regionModel::interRegionAMI(), kinematicSingleLayer::kinematicSingleLayer(), singleLayerRegion::mappedFieldAndInternalPatchTypes(), singleLayerRegion::mappedPushedFieldPatchTypes(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), laminar::mut(), regionModel::nbrCoupledPatchID(), patchInjection::patchInjection(), kinematicSingleLayer::pp(), kinematicSingleLayer::pu(), thermalBaffleModel::read(), reactingOneDim::solidRegionDiffNo(), regionModel::solution(), reactingOneDim::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), kinematicSingleLayer::solveMomentum(), reactingOneDim::solveSpeciesMass(), kinematicSingleLayer::solveThickness(), thermoSingleLayer::T(), thermoSingleLayer::thermoSingleLayer(), reactingOneDim::updateMesh(), reactingOneDim::updatePhiGas(), reactingOneDim::updateQr(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), and laminar::Us().
Foam::fvMesh & regionMesh () inline
Return the region mesh database for manipulation.
Definition at line 77 of file regionModelI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, objectRegistry::foundObject(), objectRegistry::lookupObject(), regionModel::regionMeshPtr_, regionModel::regionName_, and regionModel::time_.
const Foam::dictionary & coeffs () const inline
Return the model coefficients dictionary.
Definition at line 96 of file regionModelI.H.
References regionModel::coeffs_.
Referenced by thermoSingleLayer::thermoSingleLayer().
const Foam::dictionary & solution () const inline
Return the solution dictionary.
Definition at line 103 of file regionModelI.H.
References regionModel::regionMesh(), and solution::solutionDict().
Referenced by thermalBaffle::read(), and kinematicSingleLayer::read().
const Foam::IOdictionary & outputProperties () const inline
Return const access to the output properties dictionary.
Definition at line 110 of file regionModelI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and regionModel::outputPropertiesPtr_.
Referenced by kinematicSingleLayer::info(), and kinematicSingleLayer::transferPrimaryRegionSourceFields().
Foam::IOdictionary & outputProperties () inline
Return output properties dictionary.
Definition at line 124 of file regionModelI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, regionModel::isCoupledPatch(), and regionModel::outputPropertiesPtr_.
bool isCoupledPatch (const label regionPatchi) const inline
Return true if patchI on the local region is a coupled.
patch to the primary region
Definition at line 138 of file regionModelI.H.
References forAll, regionModel::intCoupledPatchIDs_, and regionModel::isRegionPatch().
Referenced by contactAngleForce::correct(), and regionModel::outputProperties().
bool isRegionPatch (const label primaryPatchi) const inline
Return true if patchI on the primary region is a coupled.
patch to the local region
Definition at line 155 of file regionModelI.H.
References forAll, and regionModel::primaryPatchIDs_.
Referenced by regionModel::isCoupledPatch(), and ThermoSurfaceFilm< CloudType >::transferParcel().
const Foam::labelList & primaryPatchIDs () const inline
Return the list of patch IDs on the primary region coupled.
to this region
Definition at line 172 of file regionModelI.H.
References regionModel::primaryPatchIDs_.
Referenced by SurfaceFilmModel< CloudType >::inject(), and thermoSingleLayer::Srho().
const Foam::labelList & intCoupledPatchIDs () const inline
Return the list of patch IDs internally coupled with the.
primary region
Definition at line 179 of file regionModelI.H.
References regionModel::intCoupledPatchIDs_, and regionModel::regionPatchID().
Referenced by injectionModelList::correct(), injectionModelList::info(), thermalBaffle::info(), SurfaceFilmModel< CloudType >::inject(), regionModel::nbrCoupledPatchID(), and thermoSingleLayer::Srho().
Foam::label regionPatchID (const label primaryPatchID) const inline
Return region ID corresponding to primaryPatchID.
Definition at line 186 of file regionModelI.H.
References forAll, regionModel::intCoupledPatchIDs_, and regionModel::primaryPatchIDs_.
Referenced by regionModel::intCoupledPatchIDs().
Foam::label nbrCoupledPatchID (const regionModel & nbrRegion, const label regionPatchi) const
Return the coupled patch ID paired with coupled patch.
regionPatchi
Definition at line 303 of file regionModel.C.
References Foam::abort(), polyPatch::boundaryMesh(), polyMesh::boundaryMesh(), Foam::FatalError, FatalErrorInFunction, forAll, regionModel::intCoupledPatchIDs(), IOdictionary::name(), patchIdentifier::name(), p, regionModel::regionMesh(), mappedPatchBase::samplePatch(), and UPtrList< T >::size().
Referenced by regionModel::interRegionAMI(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
tmp<Foam::Field<Type> > mapRegionPatchField (const regionModel & nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > & nbrField, const bool flip = false) const
Map patch field from another region model to local patch.
Referenced by regionModel::mapRegionPatchField(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
tmp<Field<Type> > mapRegionPatchField (const regionModel & nbrRegion, const word & fieldName, const label regionPatchi, const bool flip = false) const
Map patch field from another region model to local patch.
tmp<Field<Type> > mapRegionPatchInternalField (const regionModel & nbrRegion, const word & fieldName, const label regionPatchi, const bool flip = false) const
Map patch internal field from another region model to local.
patch
Referenced by regionModel::mapRegionPatchField().
void toPrimary (const label regionPatchi, List< Type > & regionField) const
Convert a local region field to the primary region.
Definition at line 161 of file regionModelTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, mappedPatchBase::reverseDistribute(), and regionModel::toRegion().
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields(), ThermoSurfaceFilm< CloudType >::cacheFilmFields(), regionModel::mapRegionPatchInternalField(), thermoSingleLayer::Srho(), regionModel::toRegion(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
void toRegion (const label regionPatchi, List< Type > & primaryFieldField) const
Convert a primary region field to the local region.
Definition at line 188 of file regionModelTemplates.C.
References Foam::abort(), mappedPatchBase::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, and regionModel::toPrimary().
Referenced by regionModel::toPrimary().
void toPrimary (const label regionPatchi, List< Type > & regionField, const CombineOp & cop) const
Convert a local region field to the primary region with op.
Definition at line 215 of file regionModelTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, mappedPatchBase::reverseDistribute(), and regionModel::toRegion().
void toRegion (const label regionPatchi, List< Type > & primaryFieldField, const CombineOp & cop) const
Convert a primary region field to the local region with op.
Definition at line 243 of file regionModelTemplates.C.
References Foam::abort(), mappedPatchBase::distribute(), Foam::FatalError, FatalErrorInFunction, and forAll.
void evolve () virtual
Main driver routing to evolve the region - calls other evolves.
Definition at line 507 of file regionModel.C.
References IOstream::ASCII, IOstream::currentVersion, Foam::decrIndent(), Foam::endl(), Foam::incrIndent(), and Foam::Info.
void preEvolveRegion () virtual
Pre-evolve region.
Reimplemented in kinematicSingleLayer, thermoSingleLayer, reactingOneDim, thermalBaffleModel, thermalBaffle, noPyrolysis, and noThermo.
Definition at line 543 of file regionModel.C.
Referenced by pyrolysisModelCollection::evolve(), reactingOneDim::preEvolveRegion(), and kinematicSingleLayer::preEvolveRegion().
void evolveRegion () virtual
Evolve the region.
Reimplemented in kinematicSingleLayer, thermoSingleLayer, reactingOneDim, thermalBaffle, noPyrolysis, and noThermo.
Definition at line 549 of file regionModel.C.
Referenced by pyrolysisModelCollection::evolve().
void postEvolveRegion () virtual
Post-evolve region.
Definition at line 555 of file regionModel.C.
void info () virtual
Provide some feedback.
Reimplemented in kinematicSingleLayer, thermoSingleLayer, reactingOneDim, and thermalBaffle.
Definition at line 561 of file regionModel.C.
Referenced by pyrolysisModelCollection::evolve().
Foam::tmp<Foam::Field<Type> > mapRegionPatchField (const regionModel & nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > & nbrField, const bool flip) const
Definition at line 29 of file regionModelTemplates.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), and regionModel::mapRegionPatchField().
Foam::tmp<Foam::Field<Type> > mapRegionPatchField (const regionModel & nbrRegion, const word & fieldName, const label regionPatchi, const bool flip) const
Definition at line 54 of file regionModelTemplates.C.
References objectRegistry::foundObject(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), objectRegistry::lookupObject(), regionModel::mapRegionPatchInternalField(), p, regionModel::regionMesh(), and Foam::Zero.
Foam::tmp<Foam::Field<Type> > mapRegionPatchInternalField (const regionModel & nbrRegion, const word & fieldName, const label regionPatchi, const bool flip) const
Definition at line 106 of file regionModelTemplates.C.
References objectRegistry::foundObject(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), objectRegistry::lookupObject(), p, regionModel::regionMesh(), regionModel::toPrimary(), and Foam::Zero.
Member Data Documentation
const fvMesh& primaryMesh_ protected
Reference to the primary mesh database.
Definition at line 87 of file regionModel.H.
Referenced by regionModel::primaryMesh().
const Time& time_ protected
Reference to the time database.
Definition at line 90 of file regionModel.H.
Referenced by reactingOneDim::calculateMassTransfer(), kinematicSingleLayer::CourantNumber(), kinematicSingleLayer::pp(), kinematicSingleLayer::pu(), regionModel::regionMesh(), thermoSingleLayer::Srho(), regionModel::time(), thermoSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), and thermoSingleLayer::updateSubmodels().
Switch active_ protected
Active flag.
Definition at line 93 of file regionModel.H.
Referenced by regionModel::active(), pyrolysisModel::pyrolysisModel(), reactingOneDim::reactingOneDim(), thermalBaffleModel::read(), and surfaceFilmModel::surfaceFilmModel().
Switch infoOutput_ protected
Active information output.
Definition at line 96 of file regionModel.H.
Referenced by reactingOneDim::calculateMassTransfer(), and regionModel::infoOutput().
const word modelName_ protected
Model name.
Definition at line 99 of file regionModel.H.
Referenced by regionModel::modelName().
autoPtr<fvMesh> regionMeshPtr_ protected
Pointer to the region mesh database.
Definition at line 102 of file regionModel.H.
Referenced by regionModel::regionMesh().
dictionary coeffs_ protected
Model coefficients dictionary.
Definition at line 105 of file regionModel.H.
Referenced by regionModel::coeffs(), and thermoSingleLayer::thermoSingleLayer().
autoPtr<IOdictionary> outputPropertiesPtr_ protected
Dictionary of output properties.
Definition at line 108 of file regionModel.H.
Referenced by regionModel::outputProperties().
labelList primaryPatchIDs_ protected
List of patch IDs on the primary region coupled to this region.
Definition at line 114 of file regionModel.H.
Referenced by reactingOneDim::addMassSources(), regionModel::isRegionPatch(), regionModel::primaryPatchIDs(), and regionModel::regionPatchID().
labelList intCoupledPatchIDs_ protected
List of patch IDs internally coupled with the primary region.
Definition at line 117 of file regionModel.H.
Referenced by reactingOneDim::addMassSources(), reactingOneDim::calculateMassTransfer(), regionModel::intCoupledPatchIDs(), regionModel::isCoupledPatch(), singleLayerRegion::mappedFieldAndInternalPatchTypes(), singleLayerRegion::mappedPushedFieldPatchTypes(), thermalBaffleModel::read(), regionModel::regionPatchID(), thermalBaffle::solveEnergy(), thermoSingleLayer::Srho(), reactingOneDim::updatePhiGas(), reactingOneDim::updateQr(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), and thermalBaffle::~thermalBaffle().
word regionName_ protected
Region name.
Definition at line 121 of file regionModel.H.
Referenced by regionModel::regionMesh().
regionModelFunctionObjectList functions_ protected
Region model function objects.
Definition at line 124 of file regionModel.H.
wordList interRegionAMINames_ mutable protected
List of region names this region is coupled to.
Definition at line 130 of file regionModel.H.
PtrList<PtrList<AMIPatchToPatchInterpolation> > interRegionAMI_ mutable protected
List of AMI objects per coupled region.
Definition at line 134 of file regionModel.H.
The documentation for this class was generated from the following files:
src/regionModels/regionModel/regionModel/regionModel.H
src/regionModels/regionModel/regionModel/regionModel.C
src/regionModels/regionModel/regionModel/regionModelI.H
src/regionModels/regionModel/regionModel/regionModelTemplates.C