OpenFOAM: RectangularMatrix< Type > Class Template Reference
RectangularMatrix< Type > Class Template Reference
A templated 2D rectangular m x n matrix of objects of <Type>.
Public Member Functions
RectangularMatrix ()
Null constructor.
RectangularMatrix (const label m, const label n)
Construct given number of rows and columns,.
template<class MatrixType >
RectangularMatrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
template<class MatrixType >
RectangularMatrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
RectangularMatrix (const label m, const label n, const zero)
Construct with given number of rows and columns.
RectangularMatrix (const label m, const label n, const Type &)
Construct with given number of rows and columns.
RectangularMatrix (const SquareMatrix< Type > &)
Construct as copy of a square matrix.
RectangularMatrix (Istream &)
Construct from Istream.
autoPtr< RectangularMatrix< Type > > clone () const
Clone.
void operator= (const zero)
Assignment of all elements to zero.
Public Member Functions inherited from Matrix< RectangularMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label m, const label n)
Construct given number of rows and columns.
Matrix (const label m, const label n, const zero)
Construct with given number of rows and columns.
Matrix (const label m, const label n, const Type &)
Construct with given number of rows and columns.
Matrix (const mType &)
Copy constructor.
Matrix (const Matrix< Form2, Type > &)
Copy constructor from matrix of a different form.
Matrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (Istream &)
Construct from Istream.
autoPtr< mType > clone () const
Clone.
~Matrix ()
Destructor.
label m () const
Return the number of rows.
label n () const
Return the number of columns.
label size () const
Return the number of elements in matrix (m*n)
const Type * v () const
Return element vector of the constant Matrix.
Type * v ()
Return element vector of the Matrix.
ConstMatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart) const
ConstMatrixBlock< mType > block (const label mStart, const label nStart) const
MatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart)
MatrixBlock< mType > block (const label mStart, const label nStart)
ConstMatrixBlock< mType > col (const label m, const label rowStart) const
ConstMatrixBlock< mType > col (const label m, const label mStart, const label nStart) const
MatrixBlock< mType > col (const label m, const label rowStart)
MatrixBlock< mType > col (const label m, const label mStart, const label nStart)
void checki (const label i) const
Check index i is within valid range (0 ... m-1).
void checkj (const label j) const
Check index j is within valid range (0 ... n-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (mType &)
Transfer the contents of the argument Matrix into this Matrix.
void setSize (const label m, const label n)
Resize the matrix preserving the elements.
void shallowResize (const label m, const label n)
Resize the matrix without reallocating storage (unsafe)
RectangularMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
const Type & operator() (const label i, const label j) const
(i, j) const element access operator
Type & operator() (const label i, const label j)
(i, j) element access operator
void operator= (const mType &)
Assignment operator. Takes linear time.
void operator= (const ConstMatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const MatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Type &)
Assignment of all elements to the given value.
Additional Inherited Members
Public Types inherited from Matrix< RectangularMatrix< Type >, Type >
typedef Matrix< RectangularMatrix< Type >, Type > mType
Matrix type.
typedef Type cmptType
Component type.
Static Public Member Functions inherited from Matrix< RectangularMatrix< Type >, Type >
static const mType & null ()
Return a null Matrix.
Detailed Description
template<class Type>
class Foam::RectangularMatrix< Type >
A templated 2D rectangular m x n matrix of objects of <Type>.
The matrix dimensions are used for subscript bounds checking etc.
Source files
RectangularMatrix.H
RectangularMatrixI.H
RectangularMatrix.C
Definition at line 53 of file RectangularMatrix.H.
Constructor & Destructor Documentation
RectangularMatrix () inline
Null constructor.
Definition at line 29 of file RectangularMatrixI.H.
Referenced by RectangularMatrix< Type >::RectangularMatrix().
RectangularMatrix (const label m, const label n) inline
Construct given number of rows and columns,.
Definition at line 37 of file RectangularMatrixI.H.
References RectangularMatrix< Type >::RectangularMatrix().
RectangularMatrix (const ConstMatrixBlock< MatrixType > & block) inline
Construct from a block of another matrix.
Definition at line 49 of file RectangularMatrixI.H.
References RectangularMatrix< Type >::RectangularMatrix().
RectangularMatrix (const MatrixBlock< MatrixType > & block) inline
Construct from a block of another matrix.
Definition at line 60 of file RectangularMatrixI.H.
References RectangularMatrix< Type >::RectangularMatrix().
RectangularMatrix (const label m, const label n, const zero) inline
Construct with given number of rows and columns.
initializing all elements to zero
Definition at line 70 of file RectangularMatrixI.H.
References RectangularMatrix< Type >::RectangularMatrix().
RectangularMatrix (const label m, const label n, const Type & t) inline
Construct with given number of rows and columns.
and value for all elements.
Definition at line 82 of file RectangularMatrixI.H.
References RectangularMatrix< Type >::RectangularMatrix().
RectangularMatrix (const SquareMatrix< Type > & SM) inline
Construct as copy of a square matrix.
Definition at line 94 of file RectangularMatrixI.H.
RectangularMatrix (Istream & is) inline
Construct from Istream.
Definition at line 103 of file RectangularMatrixI.H.
Member Function Documentation
Foam::autoPtr< Foam::RectangularMatrix< Type > > clone () const inline
Clone.
Definition at line 111 of file RectangularMatrixI.H.
void operator= (const zero)
Assignment of all elements to zero.
Definition at line 123 of file RectangularMatrixI.H.
References Matrix< RectangularMatrix< Type >, Type >::operator, Foam::outer(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/RectangularMatrix/RectangularMatrix.H
src/OpenFOAM/matrices/RectangularMatrix/RectangularMatrixI.H