OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
residuals Class Reference
Function objects » Utility function objects
This function object writes out the initial residual for specified fields.
Public Member Functions
TypeName ("residuals")
Runtime type information.
residuals (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~residuals ()
Destructor.
virtual const word & name () const
Return name of the set of field min/max.
virtual void read (const dictionary &)
Read the field min/max data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
template<class Type >
void writeResidual (const word &fieldName)
Calculate the field min/max.
virtual void write ()
Write the residuals.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct null.
functionObjectFile (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFile (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFile ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Protected Member Functions
template<class Type >
void writeFileHeader (const word &fieldName)
Output field header information.
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of residuals.
const objectRegistry & obr_
bool active_
on/off switch
wordList fieldSet_
Fields to write residuals.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Detailed Description
This function object writes out the initial residual for specified fields.
Example of function object specification:
residuals
{
    type            residuals;
    outputControl   timeStep;
    outputInterval  1;
    fields
    (
        U
        p
    );
}
Output data is written to the dir postProcessing/residuals/<timeDir>/ For vector/tensor fields, e.g. U, where an equation is solved for each component, the largest residual of each component is written out.
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
residuals.H
residuals.C
IOresiduals.H
Definition at line 88 of file residuals.H.
Constructor & Destructor Documentation
residuals (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 42 of file residuals.C.
References Foam::endl(), Foam::read(), and WarningInFunction.
~residuals () virtual
Destructor.
Definition at line 70 of file residuals.C.
Member Function Documentation
void writeFileHeader (const word & fieldName) protected
Output field header information.
Definition at line 35 of file residualsTemplates.C.
References Foam::component(), functionObjectFile::file(), objectRegistry::foundObject(), objectRegistry::lookupObject(), mesh, residuals::obr_, and functionObjectFile::writeTabbed().
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from functionObjectFile.
Definition at line 85 of file residuals.C.
References Foam::endl(), forAll, and UPstream::master().
TypeName ("residuals")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the set of field min/max.
Definition at line 156 of file residuals.H.
References residuals::end(), residuals::execute(), residuals::name_, residuals::read(), residuals::timeSet(), residuals::write(), and residuals::writeResidual().
void read (const dictionary & dict) virtual
Read the field min/max data.
Definition at line 76 of file residuals.C.
References dictionary::lookup().
Referenced by residuals::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 108 of file residuals.C.
Referenced by residuals::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 112 of file residuals.C.
Referenced by residuals::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 116 of file residuals.C.
Referenced by residuals::name().
void writeResidual (const word & fieldName)
Calculate the field min/max.
Definition at line 65 of file residualsTemplates.C.
References Foam::component(), functionObjectFile::file(), UList< T >::first(), dictionary::found(), objectRegistry::foundObject(), dictionary::lookup(), objectRegistry::lookupObject(), mesh, residuals::obr_, and token::TAB.
Referenced by residuals::name().
void write () virtual
Write the residuals.
Reimplemented from functionObjectFile.
Definition at line 120 of file residuals.C.
References Foam::endl(), forAll, UPstream::master(), and functionObjectFile::write().
Referenced by residuals::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 181 of file residuals.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 185 of file residuals.H.
Member Data Documentation
word name_ protected
Name of this set of residuals.
Also used as the name of the output directory
Definition at line 98 of file residuals.H.
Referenced by residuals::name().
const objectRegistry& obr_ protected
Definition at line 100 of file residuals.H.
Referenced by residuals::writeFileHeader(), and residuals::writeResidual().
bool active_ protected
on/off switch
Definition at line 103 of file residuals.H.
wordList fieldSet_ protected
Fields to write residuals.
Definition at line 106 of file residuals.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/residuals/residuals.H
src/postProcessing/functionObjects/utilities/residuals/residuals.C
src/postProcessing/functionObjects/utilities/residuals/residualsTemplates.C