OpenFOAM: residuals Class Reference
residuals Class Reference
FunctionObjects » Utility function objects
Writes out the initial residual for specified fields.
Public Member Functions
TypeName ("residuals")
Runtime type information.
residuals (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~residuals ()
Destructor.
virtual bool read (const dictionary &)
Read the controls.
virtual bool execute ()
Execute, currently does nothing.
virtual bool write ()
Write the residuals.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from logFiles
logFiles (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
virtual ~logFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file ()
Return access to the file (if only 1)
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
~writeFile ()
Destructor.
void initStream (Ostream &os) const
Initialise the output stream for writing.
fileName baseFileDir () const
Return the base directory for output.
fileName baseTimeDir () const
Return the base directory for the current time value.
Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Protected Member Functions
template<class Type >
void writeFileHeader (const word &fieldName)
Output field header information.
virtual void writeFileHeader (const label i)
Output file header information.
template<class Type >
void writeResidual (const word &fieldName)
Calculate the field min/max.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Member Functions inherited from logFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
Protected Attributes
wordList fieldSet_
Fields to write residuals.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Protected Attributes inherited from logFiles
wordList names_
File names.
PtrList< OFstream > filePtrs_
File pointer.
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
Reference to the region objectRegistry.
const word prefix_
Prefix.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Detailed Description
Writes out the initial residual for specified fields.
Example of function object specification:
residuals
{
    type            residuals;
    writeControl   timeStep;
    writeInterval  1;
    fields
    (
        U
        p
    );
}
Output data is written to the dir postProcessing/residuals/<timeDir>/ For vector/tensor fields, e.g. U, where an equation is solved for each component, the largest residual of each component is written out.
See also
Foam::functionObject Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::logFiles Foam::functionObjects::timeControl
Source files
residuals.H
residuals.C
Definition at line 79 of file residuals.H.
Constructor & Destructor Documentation
residuals (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 50 of file residuals.C.
References Foam::read().
~residuals () virtual
Destructor.
Definition at line 67 of file residuals.C.
Member Function Documentation
void writeFileHeader (const word & fieldName) protected
Output field header information.
Definition at line 33 of file residualsTemplates.C.
References Foam::component(), logFiles::file(), objectRegistry::foundObject(), fvMeshFunctionObject::mesh_, regionFunctionObject::obr_, fvMesh::validComponents(), and writeFile::writeTabbed().
void writeFileHeader (const label i) protected virtual
Output file header information.
Implements logFiles.
Definition at line 83 of file residuals.C.
References Foam::endl(), forAll, and UPstream::master().
void writeResidual (const word & fieldName) protected
Calculate the field min/max.
Definition at line 60 of file residualsTemplates.C.
References Foam::component(), logFiles::file(), UList< T >::first(), dictionary::found(), objectRegistry::foundObject(), dictionary::lookup(), fvMeshFunctionObject::mesh_, regionFunctionObject::obr_, data::solverPerformanceDict(), token::TAB, and fvMesh::validComponents().
TypeName ("residuals")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the controls.
Reimplemented from regionFunctionObject.
Definition at line 73 of file residuals.C.
References dictionary::lookup(), and regionFunctionObject::read().
bool execute () virtual
Execute, currently does nothing.
Implements functionObject.
Definition at line 106 of file residuals.C.
bool write () virtual
Write the residuals.
Reimplemented from logFiles.
Definition at line 112 of file residuals.C.
References Foam::endl(), forAll, UPstream::master(), and logFiles::write().
Member Data Documentation
wordList fieldSet_ protected
Fields to write residuals.
Definition at line 89 of file residuals.H.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/residuals/residuals.H
src/functionObjects/utilities/residuals/residuals.C
src/functionObjects/utilities/residuals/residualsTemplates.C