OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sampledPatch Class Reference
A sampledSurface on patches. Non-triangulated by default.
Public Member Functions
TypeName ("sampledPatch")
Runtime type information.
sampledPatch (const word &name, const polyMesh &mesh, const wordReList &patchNames, const bool triangulate=false)
Construct from components.
sampledPatch (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
virtual ~sampledPatch ()
Destructor.
virtual bool needsUpdate () const
Does the surface need an update?
virtual bool expire ()
Mark the surface as needing an update.
virtual bool update ()
Update the surface as required.
virtual const pointField & points () const
Points of surface.
virtual const faceList & faces () const
Faces of surface.
virtual tmp< scalarField > sample (const volScalarField &) const
Sample field on surface.
virtual tmp< vectorField > sample (const volVectorField &) const
Sample field on surface.
virtual tmp< sphericalTensorField > sample (const volSphericalTensorField &) const
Sample field on surface.
virtual tmp< symmTensorField > sample (const volSymmTensorField &) const
Sample field on surface.
virtual tmp< tensorField > sample (const volTensorField &) const
Sample field on surface.
virtual tmp< scalarField > sample (const surfaceScalarField &) const
Surface sample field on surface.
virtual tmp< vectorField > sample (const surfaceVectorField &) const
Surface Sample field on surface.
virtual tmp< sphericalTensorField > sample (const surfaceSphericalTensorField &) const
Surface sample field on surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &) const
Surface sample field on surface.
virtual tmp< tensorField > sample (const surfaceTensorField &) const
Surface sample field on surface.
virtual tmp< scalarField > interpolate (const interpolation< scalar > &) const
Interpolate field on surface.
virtual tmp< vectorField > interpolate (const interpolation< vector > &) const
Interpolate field on surface.
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &) const
Interpolate field on surface.
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &) const
Interpolate field on surface.
virtual tmp< tensorField > interpolate (const interpolation< tensor > &) const
Interpolate field on surface.
virtual void print (Ostream &) const
Write.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleField (const GeometricField< Type, fvPatchField, volMesh > &vField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleField (const GeometricField< Type, fvsPatchField, surfaceMesh > &sField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateField (const interpolation< Type > &interpolator) const
Public Member Functions inherited from MeshedSurface< face >
MeshedSurface ()
Construct null.
MeshedSurface (const Xfer< pointField > &, const Xfer< List< face >> &, const Xfer< surfZoneList > &)
Construct by transferring components (points, faces, zones).
MeshedSurface (const Xfer< pointField > &, const Xfer< List< face >> &, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Construct by transferring components (points, faces).
MeshedSurface (const MeshedSurface &)
Construct as copy.
MeshedSurface (const UnsortedMeshedSurface< face > &)
Construct from a UnsortedMeshedSurface.
MeshedSurface (const polyBoundaryMesh &, const bool globalPoints=false)
Construct from a boundary mesh with local points/faces.
MeshedSurface (const surfMesh &)
Construct from a surfMesh.
MeshedSurface (const Xfer< UnsortedMeshedSurface< face >> &)
Construct by transferring the contents from a UnsortedMeshedSurface.
MeshedSurface (const Xfer< MeshedSurface< face >> &)
Construct by transferring the contents from a MeshedSurface.
MeshedSurface (const fileName &)
Construct from file name (uses extension to determine type)
MeshedSurface (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
MeshedSurface (const Time &, const word &surfName="")
Construct from database.
ClassName ("MeshedSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
Destructor.
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< face > &surf),(name, surf))
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void write (const Time &, const word &surfName="") const
Write to database.
label size () const
The surface size is the number of faces.
const List< face > & faces () const
Return const access to the faces.
const List< surfZone > & surfZones () const
Const access to the surface zones.
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
Add surface zones.
virtual void removeZones ()
Remove surface zones.
virtual void clear ()
Clear all storage.
virtual void movePoints (const pointField &)
Move points.
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
virtual void reset (const Xfer< pointField > &points, const Xfer< List< face >> &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void reset (const Xfer< List< point >> &points, const Xfer< List< face >> &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void cleanup (const bool verbose)
Remove invalid faces.
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label triangulate ()
Triangulate in-place, returning the number of triangles added.
virtual label triangulate (List< label > &faceMap)
Triangulate in-place, returning the number of triangles added.
MeshedSurface subsetMesh (const labelHashSet &include, labelList &pointMap, labelList &faceMap) const
Return new surface.
MeshedSurface subsetMesh (const labelHashSet &include) const
Return new surface.
void transfer (MeshedSurface< face > &)
Transfer the contents of the argument and annul the argument.
void transfer (UnsortedMeshedSurface< face > &)
Transfer the contents of the argument and annul the argument.
Xfer< MeshedSurface< face > > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &)
Read from file. Chooses reader based on detected extension.
void writeStats (Ostream &os) const
void operator= (const MeshedSurface< face > &)
operator MeshedSurfaceProxy< face > () const
Conversion operator to MeshedSurfaceProxy.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()
Construct null.
virtual ~surfaceFormatsCore ()
Destructor.
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &, const dictionary &)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor.
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool interpolate () const
Interpolation requested for surface.
virtual const vectorField & Sf () const
Return face area vectors.
virtual const scalarField & magSf () const
Return face area magnitudes.
virtual const vectorField & Cf () const
Return face centres as vectorField.
scalar area () const
The total surface area.
template<class Type >
Type integrate (const Field< Type > &) const
Integration of a field across the surface.
template<class Type >
Type integrate (const tmp< Field< Type >> &) const
Integration of a field across the surface.
template<class Type >
Type average (const Field< Type > &) const
Area-averaged value of a field across the surface.
template<class Type >
Type average (const tmp< Field< Type >> &) const
Area-averaged value of a field across the surface.
tmp< Field< scalar > > project (const Field< scalar > &) const
Project field onto surface.
tmp< Field< scalar > > project (const Field< vector > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< sphericalTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< symmTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< tensor > &) const
Project field onto surface.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Interpolate from points to cell centre.
virtual void rename (const word &newName)
Rename.
template<class ReturnType , class Type >
Foam::tmp< Foam::Field< ReturnType > > project (const tmp< Field< Type >> &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Protected Member Functions
const wordReList & patchNames () const
const labelList & patchIDs () const
const labelList & patchStart () const
const labelList & patchFaceLabels () const
Protected Member Functions inherited from MeshedSurface< face >
void transcribe (MeshedSurface< face > &)
Transfer points/zones and transcribe face -> triFace.
void checkZones ()
Basic sanity check on zones.
pointField & storedPoints ()
Non-const access to global points.
List< face > & storedFaces ()
Non-const access to the faces.
surfZoneList & storedZones ()
Non-const access to the zones.
void sortFacesAndStore (const Xfer< List< face >> &unsortedFaces, const Xfer< List< label >> &zoneIds, const bool sorted)
Sort faces by zones and store sorted faces.
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
Additional Inherited Members
Public Types inherited from MeshedSurface< face >
typedef face FaceType
Face type used.
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Member Functions inherited from MeshedSurface< face >
static bool isTri ()
Face storage only handles triangulated faces.
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< MeshedSurface > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< MeshedSurface > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const MeshedSurface< face > &)
Write to file.
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
static fileName localMeshFileName (const word &surfName="")
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName="")
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName="")
Find mesh file with surfName.
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &, const dictionary &)
Return a reference to the selected surface.
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Static Protected Member Functions inherited from surfaceFormatsCore
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a list with a single entry,.
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
A sampledSurface on patches. Non-triangulated by default.
Source files
sampledPatch.H
sampledPatch.C
Definition at line 49 of file sampledPatch.H.
Constructor & Destructor Documentation
sampledPatch (const word & name, const polyMesh & mesh, const wordReList & patchNames, const bool triangulate = false)
Construct from components.
Definition at line 47 of file sampledPatch.C.
Referenced by sampledPatch::patchFaceLabels().
sampledPatch (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 62 of file sampledPatch.C.
~sampledPatch () virtual
Destructor.
Definition at line 77 of file sampledPatch.C.
Referenced by sampledPatch::patchFaceLabels().
Member Function Documentation
const wordReList& patchNames () const inline protected
Definition at line 107 of file sampledPatch.H.
References sampledPatch::patchIDs().
Referenced by sampledPatch::patchFaceLabels().
const Foam::labelList & patchIDs () const protected
Definition at line 83 of file sampledPatch.C.
References polyMesh::boundaryMesh(), mesh, polyBoundaryMesh::patchSet(), and HashTable< T, Key, Hash >::sortedToc().
Referenced by sampledPatch::patchNames().
const labelList& patchStart () const inline protected
Definition at line 114 of file sampledPatch.H.
const labelList& patchFaceLabels () const inline protected
Definition at line 119 of file sampledPatch.H.
References dict, sampledPatch::expire(), sampledSurface::mesh(), sampledSurface::name(), sampledPatch::needsUpdate(), sampledPatch::patchNames(), sampledPatch::sampledPatch(), MeshedSurface< face >::triangulate(), sampledPatch::TypeName(), sampledPatch::update(), and sampledPatch::~sampledPatch().
TypeName ("sampledPatch")
Runtime type information.
Referenced by sampledPatch::patchFaceLabels().
bool needsUpdate () const virtual
Does the surface need an update?
Implements sampledSurface.
Definition at line 97 of file sampledPatch.C.
Referenced by sampledPatch::patchFaceLabels().
bool expire () virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implements sampledSurface.
Definition at line 103 of file sampledPatch.C.
References clear(), and sampledSurface::clearGeom().
Referenced by sampledPatch::patchFaceLabels().
bool update () virtual
Update the surface as required.
Do nothing (and return false) if no update was needed
Implements sampledSurface.
Definition at line 123 of file sampledPatch.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), mesh, patchIdentifier::name(), Foam::notNull(), points, Foam::Pout, sampledPatch::sample(), UList< T >::size(), and polyPatch::start().
Referenced by sampledPatch::patchFaceLabels().
virtual const pointField& points () const inline virtual
Points of surface.
Implements sampledSurface.
Definition at line 171 of file sampledPatch.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::points().
virtual const faceList& faces () const inline virtual
Faces of surface.
Implements sampledSurface.
Definition at line 177 of file sampledPatch.H.
References MeshedSurface< face >::faces(), sampledSurface::interpolate(), sampledPatch::print(), and sampledPatch::sample().
Foam::tmp< Foam::sphericalTensorField > sample (const volScalarField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 235 of file sampledPatch.C.
Referenced by sampledPatch::faces(), sampledPatch::sample(), and sampledPatch::update().
Foam::tmp< Foam::vectorField > sample (const volVectorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 244 of file sampledPatch.C.
References sampledPatch::sample().
Foam::tmp< Foam::sphericalTensorField > sample (const volSphericalTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 253 of file sampledPatch.C.
References sampledPatch::sample().
Foam::tmp< Foam::symmTensorField > sample (const volSymmTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 262 of file sampledPatch.C.
References sampledPatch::sample().
Foam::tmp< Foam::tensorField > sample (const volTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 271 of file sampledPatch.C.
References sampledPatch::sample().
Foam::tmp< Foam::scalarField > sample (const surfaceScalarField & sField) const virtual
Surface sample field on surface.
Reimplemented from sampledSurface.
Definition at line 280 of file sampledPatch.C.
References sampledPatch::sample().
virtual tmp<vectorField> sample (const surfaceVectorField &) const virtual
Surface Sample field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
virtual tmp<sphericalTensorField> sample (const surfaceSphericalTensorField &) const virtual
Surface sample field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Foam::tmp< Foam::symmTensorField > sample (const surfaceSymmTensorField & sField) const virtual
Surface sample field on surface.
Reimplemented from sampledSurface.
Definition at line 307 of file sampledPatch.C.
References sampledPatch::sample().
Foam::tmp< Foam::tensorField > sample (const surfaceTensorField & sField) const virtual
Surface sample field on surface.
Reimplemented from sampledSurface.
Definition at line 316 of file sampledPatch.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 325 of file sampledPatch.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 334 of file sampledPatch.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 343 of file sampledPatch.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 352 of file sampledPatch.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 361 of file sampledPatch.C.
void print (Ostream & os) const virtual
Write.
Reimplemented from sampledSurface.
Reimplemented in sampledPatchInternalField.
Definition at line 369 of file sampledPatch.C.
References Foam::name(), patchNames(), points, and List< T >::size().
Referenced by sampledPatch::faces().
Foam::tmp<Foam::Field<Type> > sampleField (const GeometricField< Type, fvPatchField, volMesh > & vField) const
Definition at line 33 of file sampledPatchTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, and tmp< T >::ref().
Foam::tmp<Foam::Field<Type> > sampleField (const GeometricField< Type, fvsPatchField, surfaceMesh > & sField) const
Definition at line 54 of file sampledPatchTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, and tmp< T >::ref().
Foam::tmp<Foam::Field<Type> > interpolateField (const interpolation< Type > & interpolator) const
Definition at line 75 of file sampledPatchTemplates.C.
References f(), forAll, interpolation< Type >::interpolate(), mesh, points, tmp< T >::ref(), and polyPatch::start().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledPatch/sampledPatch.H
src/sampling/sampledSurface/sampledPatch/sampledPatch.C
src/sampling/sampledSurface/sampledPatch/sampledPatchTemplates.C