OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
smoothSolver Class Reference
Iterative solver for symmetric and asymetric matrices which uses a run-time selected smoother e.g. GaussSeidel to converge the solution to the required tolerance.
Public Member Functions
TypeName ("smoothSolver")
Runtime type information.
smoothSolver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Construct from matrix components and solver controls.
virtual ~smoothSolver ()
Destructor.
virtual solverPerformance solve (scalarField &psi, const scalarField &source, const direction cmpt=0) const
Solve the matrix with this solver.
Public Member Functions inherited from lduMatrix::solver
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
solver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~solver ()
Destructor.
const word & fieldName () const
const lduMatrix & matrix () const
const FieldField< Field, scalar > & interfaceBouCoeffs () const
const FieldField< Field, scalar > & interfaceIntCoeffs () const
const lduInterfaceFieldPtrsList & interfaces () const
virtual void read (const dictionary &)
Read and reset the solver parameters from the given stream.
scalar normFactor (const scalarField &psi, const scalarField &source, const scalarField &Apsi, scalarField &tmpField) const
Return the matrix norm used to normalise the residual for the.
Protected Member Functions
virtual void readControls ()
Read the control parameters from the controlDict_.
Protected Attributes
label nSweeps_
Number of sweeps before the evaluation of residual.
Protected Attributes inherited from lduMatrix::solver
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
lduInterfaceFieldPtrsList interfaces_
dictionary controlDict_
Dictionary of controls.
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
scalar tolerance_
Final convergence tolerance.
scalar relTol_
Convergence tolerance relative to the initial.
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::solver
static autoPtr< solver > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Return a new solver.
Detailed Description
Iterative solver for symmetric and asymetric matrices which uses a run-time selected smoother e.g. GaussSeidel to converge the solution to the required tolerance.
To improve efficiency, the residual is evaluated after every nSweeps smoothing iterations.
Source files
smoothSolver.H
smoothSolver.C
Definition at line 53 of file smoothSolver.H.
Constructor & Destructor Documentation
smoothSolver (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls)
Construct from matrix components and solver controls.
Definition at line 45 of file smoothSolver.C.
virtual ~smoothSolver () inline virtual
Destructor.
Definition at line 88 of file smoothSolver.H.
Member Function Documentation
void readControls () protected virtual
Read the control parameters from the controlDict_.
Reimplemented from lduMatrix::solver.
Definition at line 70 of file smoothSolver.C.
References lduMatrix::solver::controlDict_, dictionary::lookupOrDefault(), smoothSolver::nSweeps_, and lduMatrix::solver::readControls().
TypeName ("smoothSolver")
Runtime type information.
Foam::solverPerformance solve (scalarField & psi, const scalarField & source, const direction cmpt = 0) const virtual
Solve the matrix with this solver.
Implements lduMatrix::solver.
Definition at line 78 of file smoothSolver.C.
References SolverPerformance< Type >::checkConvergence(), lduMesh::comm(), Foam::endl(), SolverPerformance< Type >::finalResidual(), Foam::gSumMag(), Foam::Info, SolverPerformance< Type >::initialResidual(), messageStream::masterStream(), mesh, lduMatrix::mesh(), lduMatrix::smoother::New(), SolverPerformance< Type >::nIterations(), List< T >::size(), and lduMatrix::smoother::smooth().
Member Data Documentation
label nSweeps_ protected
Number of sweeps before the evaluation of residual.
Definition at line 62 of file smoothSolver.H.
Referenced by smoothSolver::readControls().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/smoothSolver/smoothSolver.H
src/OpenFOAM/matrices/lduMatrix/solvers/smoothSolver/smoothSolver.C