OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
residuals Class Reference
FunctionObjects » Utility function objects
This function object writes out the initial residual for specified fields.
Public Member Functions
TypeName ("residuals")
Runtime type information.
residuals (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~residuals ()
Destructor.
virtual bool read (const dictionary &)
Read the controls.
virtual bool execute (const bool postProcess=false)
Execute, currently does nothing.
virtual bool write (const bool postProcess=false)
Write the residuals.
Public Member Functions inherited from writeFiles
writeFiles (const word &name, const Time &time, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFiles (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from writeFile
writeFile (const word &name, const Time &t, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFile (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
template<class Type >
void writeFileHeader (const word &fieldName)
Output field header information.
virtual void writeFileHeader (const label i)
Output file header information.
template<class Type >
void writeResidual (const word &fieldName)
Calculate the field min/max.
Protected Member Functions inherited from writeFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
writeFiles (const writeFiles &)
Disallow default bitwise copy construct.
void operator= (const writeFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from writeFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
writeFile (const writeFile &)
Disallow default bitwise copy construct.
void operator= (const writeFile &)
Disallow default bitwise assignment.
Protected Attributes
wordList fieldSet_
Fields to write residuals.
Protected Attributes inherited from writeFile
const word prefix_
Prefix.
Switch log_
Switch to send output to Info as well as to file.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
This function object writes out the initial residual for specified fields.
Example of function object specification:
residuals
{
    type            residuals;
    writeControl   timeStep;
    writeInterval  1;
    fields
    (
        U
        p
    );
}
Output data is written to the dir postProcessing/residuals/<timeDir>/ For vector/tensor fields, e.g. U, where an equation is solved for each component, the largest residual of each component is written out.
See also
Foam::functionObject Foam::functionObjects::writeFiles Foam::functionObjects::timeControl
Source files
residuals.H
residuals.C
Definition at line 77 of file residuals.H.
Constructor & Destructor Documentation
residuals (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 50 of file residuals.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::read().
~residuals () virtual
Destructor.
Definition at line 72 of file residuals.C.
Member Function Documentation
void writeFileHeader (const word & fieldName) protected
Output field header information.
Definition at line 33 of file residualsTemplates.C.
References Foam::component(), writeFiles::file(), objectRegistry::foundObject(), objectRegistry::lookupObject(), mesh, regionFunctionObject::obr_, and writeFile::writeTabbed().
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from writeFile.
Definition at line 86 of file residuals.C.
References Foam::endl(), forAll, and UPstream::master().
void writeResidual (const word & fieldName) protected
Calculate the field min/max.
Definition at line 63 of file residualsTemplates.C.
References Foam::component(), writeFiles::file(), UList< T >::first(), dictionary::found(), objectRegistry::foundObject(), dictionary::lookup(), objectRegistry::lookupObject(), mesh, regionFunctionObject::obr_, and token::TAB.
TypeName ("residuals")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the controls.
Reimplemented from writeFile.
Definition at line 78 of file residuals.C.
References dictionary::lookup().
bool execute (const bool postProcess = false) virtual
Execute, currently does nothing.
Implements functionObject.
Definition at line 109 of file residuals.C.
bool write (const bool postProcess = false) virtual
Write the residuals.
Reimplemented from writeFiles.
Definition at line 116 of file residuals.C.
References Foam::endl(), forAll, UPstream::master(), and writeFiles::write().
Member Data Documentation
wordList fieldSet_ protected
Fields to write residuals.
Definition at line 86 of file residuals.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/residuals/residuals.H
src/postProcessing/functionObjects/utilities/residuals/residuals.C
src/postProcessing/functionObjects/utilities/residuals/residualsTemplates.C