OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Rzyx Class Reference
Spherical joint for rotation about the x/y/z-axes using Euler-angles in the order z, y, x.
Public Member Functions
TypeName ("Rzyx")
Runtime type information.
Rzyx ()
Construct for given model.
Rzyx (const dictionary &dict)
Construct for given model from dictionary.
virtual autoPtr< joint > clone () const
Clone this joint.
virtual ~Rzyx ()
Destructor.
virtual void jcalc (joint::XSvc &J, const scalarField &q, const scalarField &qDot) const
Update the model state for this joint.
Public Member Functions inherited from joint
TypeName ("joint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, joint, dictionary,(const dictionary &dict),(dict))
joint (const label nDoF)
Construct joint setting the size of the motion sub-space.
virtual ~joint ()
Destructor.
label nDoF () const
Return the number of degrees of freedom in this joint.
virtual bool unitQuaternion () const
Return true if this joint describes rotation using a quaternion.
label index () const
Return the index of this joint in the model.
label qIndex () const
Return start index for the state variables for this joint.
const List< spatialVector > & S () const
Return the joint motion sub-space.
virtual void write (Ostream &) const
Write.
quaternion unitQuaternion (const scalarField &q) const
Return the unit quaternion for this joint.
void unitQuaternion (const quaternion &quat, scalarField &q) const
Set the unit quaternion for this joint.
Additional Inherited Members
Static Public Member Functions inherited from joint
static autoPtr< joint > New (joint *jointPtr)
Simple selector to return an autoPtr<joint> of the given joint*.
static autoPtr< joint > New (const dictionary &dict)
Select from dictionary.
Protected Attributes inherited from joint
List< spatialVector > S_
Joint motion sub-space.
label index_
Index of this joint in the rigidBodyModel.
label qIndex_
Index of this joints data in the rigidBodyModel state.
Detailed Description
Spherical joint for rotation about the x/y/z-axes using Euler-angles in the order z, y, x.
Reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
    Chapter 4.
Source files
Rzyx.H
Rzyx.C
Definition at line 61 of file Rzyx.H.
Constructor & Destructor Documentation
Rzyx ()
Construct for given model.
Definition at line 53 of file Rzyx.C.
References joint::S_.
Referenced by Rzyx::clone().
Rzyx (const dictionary & dict)
Construct for given model from dictionary.
Definition at line 63 of file Rzyx.C.
References joint::S_.
~Rzyx () virtual
Destructor.
Definition at line 81 of file Rzyx.C.
References Rzyx::jcalc().
Member Function Documentation
TypeName ("Rzyx")
Runtime type information.
Foam::autoPtr< Foam::RBD::joint > clone () const virtual
Clone this joint.
Implements joint.
Definition at line 73 of file Rzyx.C.
References Rzyx::Rzyx().
void jcalc (joint::XSvc & J, const scalarField & q, const scalarField & qDot) const virtual
Update the model state for this joint.
Implements joint.
Definition at line 88 of file Rzyx.C.
References Field< Type >::block(), joint::XSvc::c, Foam::constant::physicoChemical::c1, Foam::constant::physicoChemical::c2, Foam::cos(), spatialTransform::E(), joint::qIndex_, spatialTransform::r(), joint::XSvc::S, Foam::sin(), joint::XSvc::v, Vector< Cmpt >::x(), joint::XSvc::X, MatrixSpace< Form, Cmpt, Mrows, Ncols >::xx(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::xz(), Vector< Cmpt >::y(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::yx(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::yy(), Vector< Cmpt >::z(), Foam::Zero, MatrixSpace< Form, Cmpt, Mrows, Ncols >::zx(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::zy().
Referenced by Rzyx::~Rzyx().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/joints/Rzyx/Rzyx.H
src/rigidBodyDynamics/joints/Rzyx/Rzyx.C