OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
scotchDecomp Class Reference
Scotch domain decomposition. When run in parallel will collect the whole graph on to the master, decompose and send back. Run ptscotchDecomp for proper distributed decomposition.
Public Member Functions
TypeName ("scotch")
Runtime type information.
scotchDecomp (const dictionary &decompositionDict)
Construct given the decomposition dictionary and mesh.
virtual ~scotchDecomp ()
Destructor.
virtual bool parallelAware () const
Is method parallel aware (i.e. does it synchronize domains across.
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const polyMesh &mesh, const labelList &agglom, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)
Return for every coordinate the wanted processor number. Explicitly.
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual labelList decompose (const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &, const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
Protected Attributes inherited from decompositionMethod
const dictionary & decompositionDict_
label nProcessors_
Detailed Description
Scotch domain decomposition. When run in parallel will collect the whole graph on to the master, decompose and send back. Run ptscotchDecomp for proper distributed decomposition.
Source files
scotchDecomp.H
scotchDecomp.C
Definition at line 49 of file scotchDecomp.H.
Constructor & Destructor Documentation
scotchDecomp (const dictionary & decompositionDict)
Construct given the decomposition dictionary and mesh.
Definition at line 80 of file dummyScotchDecomp.C.
virtual ~scotchDecomp () inline virtual
Destructor.
Definition at line 95 of file scotchDecomp.H.
Member Function Documentation
TypeName ("scotch")
Runtime type information.
virtual bool parallelAware () const inline virtual
Is method parallel aware (i.e. does it synchronize domains across.
proc boundaries)
Implements decompositionMethod.
Definition at line 101 of file scotchDecomp.H.
References decompositionMethod::decompose(), mesh, and points.
Foam::labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) virtual
Return for every coordinate the wanted processor number. Use the.
mesh connectivity (if needed) Weights get normalised with minimum weight and truncated to convert into integer so e.g. 3.5 is seen as 3. The overall sum of weights might otherwise overflow.
Implements decompositionMethod.
Definition at line 91 of file dummyScotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, notImplementedMessage, and List< label >::null().
Foam::labelList decompose (const polyMesh & mesh, const labelList & agglom, const pointField & regionPoints, const scalarField & regionWeights) virtual
Return for every coordinate the wanted processor number. Gets.
passed agglomeration map (from fine to coarse cells) and coarse cell location. Can be overridden by decomposers that provide this functionality natively. See note on weights above.
Reimplemented from decompositionMethod.
Definition at line 105 of file dummyScotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, notImplementedMessage, and List< label >::null().
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) virtual
Return for every coordinate the wanted processor number. Explicitly.
provided mesh connectivity. The connectivity is equal to mesh.cellCells() except for
in parallel the cell numbers are global cell numbers (starting from 0 at processor0 and then incrementing all through the processors)
the connections are across coupled patches See note on weights above.
Implements decompositionMethod.
Definition at line 120 of file dummyScotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, notImplementedMessage, and List< label >::null().
The documentation for this class was generated from the following files:
src/parallel/decompose/scotchDecomp/scotchDecomp.H
src/dummyThirdParty/scotchDecomp/dummyScotchDecomp.C
src/parallel/decompose/scotchDecomp/scotchDecomp.C