OpenFOAM: regionFunctionObject Class Reference
regionFunctionObject Class Reference
Specialization of Foam::functionObject for a region and providing a reference to the region Foam::objectRegistry.
Public Member Functions
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
virtual bool read (const dictionary &)
Read optional controls.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool execute ()=0
Called at each ++ or += of the time-loop.
virtual bool write ()=0
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Specialization of Foam::functionObject for a region and providing a reference to the region Foam::objectRegistry.
See also
Foam::functionObject
Source files
regionFunctionObject.H
regionFunctionObject.C
Definition at line 58 of file regionFunctionObject.H.
Constructor & Destructor Documentation
regionFunctionObject (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
The region objectRegistry is looked-up runTime with the name looked-up from the dictionary (defaults to polyMesh::defaultRegion)
Definition at line 94 of file regionFunctionObject.C.
regionFunctionObject (const word & name, const objectRegistry & obr, const dictionary & dict)
Construct from the region objectRegistry and dictionary.
Definition at line 113 of file regionFunctionObject.C.
~regionFunctionObject () virtual
Destructor.
Definition at line 127 of file regionFunctionObject.C.
Member Function Documentation
bool foundObject (const word & fieldName) const protected
Find field in the objectRegistry.
Definition at line 33 of file regionFunctionObjectTemplates.C.
References regionFunctionObject::lookupObject().
const ObjectType & lookupObject (const word & fieldName) const protected
Lookup field from the objectRegistry.
Definition at line 43 of file regionFunctionObjectTemplates.C.
References regionFunctionObject::store().
Referenced by regionFunctionObject::foundObject(), moleFractions< ThermoType >::moleFractions(), and wallShearStress::write().
bool store (word & fieldName, const tmp< ObjectType > & tfield, bool cacheable = false) protected
Store the given field in the objectRegistry under the given name.
Definition at line 53 of file regionFunctionObjectTemplates.C.
References Foam::endl(), Foam::name(), Foam::nl, tmp< T >::ptr(), tmp< T >::ref(), and WarningInFunction.
Referenced by regionFunctionObject::lookupObject().
bool writeObject (const word & fieldName) protected
Write field if present in objectRegistry.
Definition at line 44 of file regionFunctionObject.C.
References regionFunctionObject::clearObject(), Foam::endl(), Log, Foam::name(), IOobject::name(), Foam::type(), and regIOobject::write().
bool clearObject (const word & fieldName) protected
Clear field from the objectRegistry if present.
Definition at line 67 of file regionFunctionObject.C.
References regIOobject::ownedByRegistry().
Referenced by regionFunctionObject::writeObject().
TypeName ("regionFunctionObject")
Runtime type information.
bool read (const dictionary & dict) virtual
Read optional controls.
Reimplemented from functionObject.
Reimplemented in surfaceFieldValue, forces, pressure, fieldAverage, volFieldValue, regionSizeDistribution, wallBoundedStreamLine, streamLine, turbulenceFields, forceCoeffs, nearWallFields, fieldMinMax, fieldValueDelta, histogram, wallShearStress, icoUncoupledKinematicCloud, fieldValue, surfaceInterpolate, readFields, fieldCoordinateSystemTransform, wallHeatFlux, cloudInfo, writeVTK, residuals, scalarTransport, processorField, moleFractions< ThermoType >, fieldExpression, yPlus, CourantNo, specieReactionRates< ChemistryModelType >, blendingFactor, randomise, and dsmcFields.
Definition at line 133 of file regionFunctionObject.C.
References functionObject::read().
Referenced by yPlus::read(), fieldExpression::read(), processorField::read(), scalarTransport::read(), residuals::read(), cloudInfo::read(), wallHeatFlux::read(), fieldCoordinateSystemTransform::read(), readFields::read(), fieldValue::read(), icoUncoupledKinematicCloud::read(), wallShearStress::read(), fieldValueDelta::read(), fieldMinMax::read(), nearWallFields::read(), fieldAverage::read(), and forces::read().
Member Data Documentation
const Time& time_ protected
Reference to the Time.
Definition at line 68 of file regionFunctionObject.H.
const objectRegistry& obr_ protected
Reference to the region objectRegistry.
Definition at line 71 of file regionFunctionObject.H.
Referenced by fieldAverage::addMeanField(), fieldAverage::addMeanFieldType(), fieldAverage::addMeanSqrToPrime2MeanType(), fieldAverage::addPrime2MeanField(), fieldAverage::addPrime2MeanFieldType(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), surfaceFieldValue::outputDir(), fieldAverage::writeFieldType(), residuals::writeFileHeader(), and residuals::writeResidual().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/regionFunctionObject/regionFunctionObject.H
src/OpenFOAM/db/functionObjects/regionFunctionObject/regionFunctionObject.C
src/OpenFOAM/db/functionObjects/regionFunctionObject/regionFunctionObjectTemplates.C