OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ReynoldsStress< BasicTurbulenceModel > Class Template Reference abstract
Turbulence
Reynolds-stress turbulence model base class.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
ReynoldsStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~ReynoldsStress ()
Destructor.
virtual bool read ()=0
Re-read model coefficients if they have changed.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
virtual void validate ()
Validate the turbulence fields after construction.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
Protected Member Functions
void boundNormalStress (volSymmTensorField &R) const
void correctWallShearStress (volSymmTensorField &R) const
virtual void correctNut ()=0
Update the eddy-viscosity.
Protected Attributes
dimensionedScalar couplingFactor_
volSymmTensorField R_
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::ReynoldsStress< BasicTurbulenceModel >
Reynolds-stress turbulence model base class.
Source files
ReynoldsStress.H
ReynoldsStress.C
Definition at line 50 of file ReynoldsStress.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 80 of file ReynoldsStress.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 81 of file ReynoldsStress.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 82 of file ReynoldsStress.H.
Constructor & Destructor Documentation
ReynoldsStress (const word & modelName, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 112 of file ReynoldsStress.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by ReynoldsStress< BasicTurbulenceModel >::correctWallShearStress().
virtual ~ReynoldsStress () inline virtual
Destructor.
Definition at line 102 of file ReynoldsStress.H.
Member Function Documentation
void boundNormalStress (volSymmTensorField & R) const protected
Definition at line 35 of file ReynoldsStress.C.
References ReynoldsStress< BasicTurbulenceModel >::correctWallShearStress(), DimensionedField< Type, GeoMesh >::dimensions(), and GeometricField< Type, PatchField, GeoMesh >::max().
void correctWallShearStress (volSymmTensorField & R) const protected
Definition at line 60 of file ReynoldsStress.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::dev(), forAll, patches, patchi, ReynoldsStress< BasicTurbulenceModel >::ReynoldsStress(), Foam::symm(), tauw, Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), and Tensor< Cmpt >::yz().
Referenced by ReynoldsStress< BasicTurbulenceModel >::boundNormalStress().
virtual void correctNut () protected pure virtual
Update the eddy-viscosity.
Implemented in LRR< BasicTurbulenceModel >, SSG< BasicTurbulenceModel >, and DeardorffDiffStress< BasicTurbulenceModel >.
bool read () pure virtual
Re-read model coefficients if they have changed.
Implemented in LRR< BasicTurbulenceModel >, SSG< BasicTurbulenceModel >, and DeardorffDiffStress< BasicTurbulenceModel >.
Definition at line 184 of file ReynoldsStress.C.
References Foam::read().
Referenced by ReynoldsStress< RASModel< BasicTurbulenceModel > >::~ReynoldsStress().
virtual tmp<volScalarField> nut () const inline virtual
Return the turbulence viscosity.
Definition at line 112 of file ReynoldsStress.H.
virtual tmp<scalarField> nut (const label patchi) const inline virtual
Return the turbulence viscosity on patch.
Definition at line 118 of file ReynoldsStress.H.
Foam::tmp< Foam::volScalarField > k () const virtual
Return the turbulence kinetic energy.
Reimplemented in LRR< BasicTurbulenceModel >, and SSG< BasicTurbulenceModel >.
Definition at line 200 of file ReynoldsStress.C.
References tmp< T >::ref(), regIOobject::rename(), and Foam::tr().
Referenced by ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut().
Foam::tmp< Foam::volSymmTensorField > R () const virtual
Return the Reynolds stress tensor.
Definition at line 192 of file ReynoldsStress.C.
Referenced by ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut().
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Return the effective stress tensor.
Definition at line 210 of file ReynoldsStress.C.
References Foam::dev(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), Foam::fvc::grad(), nu, and Foam::twoSymm().
Referenced by ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut().
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 235 of file ReynoldsStress.C.
References Foam::dev2(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvc::laplacian(), nu, nut, and T.
Referenced by ReynoldsStress< BasicTurbulenceModel >::devRhoReff(), and ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut().
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (const volScalarField & rho, volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 287 of file ReynoldsStress.C.
References Foam::dev2(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvc::laplacian(), and T.
void validate () virtual
Validate the turbulence fields after construction.
Update turbulence viscosity and other derived fields as requires
Definition at line 301 of file ReynoldsStress.C.
Referenced by ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut().
void correct () pure virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implemented in LRR< BasicTurbulenceModel >, SSG< BasicTurbulenceModel >, and DeardorffDiffStress< BasicTurbulenceModel >.
Definition at line 308 of file ReynoldsStress.C.
References correct.
Referenced by ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut().
Member Data Documentation
dimensionedScalar couplingFactor_ protected
Definition at line 61 of file ReynoldsStress.H.
volSymmTensorField R_ protected
Definition at line 65 of file ReynoldsStress.H.
volScalarField nut_ protected
Definition at line 66 of file ReynoldsStress.H.
Referenced by ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/ReynoldsStress/ReynoldsStress.H
src/TurbulenceModels/turbulenceModels/ReynoldsStress/ReynoldsStress.C