OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
removeRegisteredObject Class Reference
FunctionObjects » Utility function objects
This function object removes registered objects if present in the database.
Public Member Functions
TypeName ("removeRegisteredObject")
Runtime type information.
removeRegisteredObject (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~removeRegisteredObject ()
Destructor.
virtual const word & name () const
Return name of the removeRegisteredObject.
virtual void read (const dictionary &)
Read the removeRegisteredObject data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write the removeRegisteredObject.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Static Public Member Functions
static bool viable (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Return true if the construction of this functionObject is viable.
Protected Attributes
word name_
Name of this set of removeRegisteredObject.
const objectRegistry & obr_
wordList objectNames_
Names of objects to control.
Detailed Description
This function object removes registered objects if present in the database.
Example of function object specification:
removeRegisteredObject1
{
    type        removeRegisteredObject;
    functionObjectLibs ("libIOFunctionObjects.so");
    ...
    objectNames (obj1 obj2);
}
Function object usage
Property Description Required Default value
type type name: removeRegisteredObject yes
objectNames objects to remove yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
removeRegisteredObject.H
removeRegisteredObject.C
IOremoveRegisteredObject.H
Definition at line 99 of file removeRegisteredObject.H.
Constructor & Destructor Documentation
removeRegisteredObject (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 44 of file removeRegisteredObject.C.
References Foam::read(), and removeRegisteredObject::viable().
~removeRegisteredObject () virtual
Destructor.
Definition at line 73 of file removeRegisteredObject.C.
Member Function Documentation
TypeName ("removeRegisteredObject")
Runtime type information.
bool viable (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false) static
Return true if the construction of this functionObject is viable.
i.e. the prerequisites for construction are available
Definition at line 60 of file removeRegisteredObject.C.
Referenced by removeRegisteredObject::removeRegisteredObject().
virtual const word& name () const inline virtual
Return name of the removeRegisteredObject.
Definition at line 163 of file removeRegisteredObject.H.
References removeRegisteredObject::end(), removeRegisteredObject::execute(), removeRegisteredObject::name_, removeRegisteredObject::read(), removeRegisteredObject::timeSet(), and removeRegisteredObject::write().
void read (const dictionary & dict) virtual
Read the removeRegisteredObject data.
Definition at line 79 of file removeRegisteredObject.C.
References dictionary::lookup().
Referenced by removeRegisteredObject::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 85 of file removeRegisteredObject.C.
References Foam::endl(), forAll, Foam::Info, IOobject::name(), Foam::nl, regIOobject::ownedByRegistry(), and Foam::type().
Referenced by removeRegisteredObject::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 108 of file removeRegisteredObject.C.
Referenced by removeRegisteredObject::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 114 of file removeRegisteredObject.C.
Referenced by removeRegisteredObject::name().
void write () virtual
Write the removeRegisteredObject.
Definition at line 118 of file removeRegisteredObject.C.
Referenced by removeRegisteredObject::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 184 of file removeRegisteredObject.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 188 of file removeRegisteredObject.H.
Member Data Documentation
word name_ protected
Name of this set of removeRegisteredObject.
Definition at line 106 of file removeRegisteredObject.H.
Referenced by removeRegisteredObject::name().
const objectRegistry& obr_ protected
Definition at line 108 of file removeRegisteredObject.H.
wordList objectNames_ protected
Names of objects to control.
Definition at line 113 of file removeRegisteredObject.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/removeRegisteredObject/removeRegisteredObject.H
src/postProcessing/functionObjects/utilities/removeRegisteredObject/removeRegisteredObject.C