OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sampledSets Class Reference
Set of sets to sample. Call sampledSets.write() to sample&write files.
Public Member Functions
TypeName ("sets")
Runtime type information.
sampledSets (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~sampledSets ()
Destructor.
virtual const word & name () const
Return name of the set of probes.
void verbose (const bool verbosity=true)
Set verbosity level.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Sample and write.
virtual void read (const dictionary &)
Read the sampledSets.
void correct ()
Correct for mesh changes.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for mesh point-motion.
virtual void readUpdate (const polyMesh::readUpdateState state)
Update for changes of mesh due to readUpdate.
Public Member Functions inherited from PtrList< sampledSet >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< sampledSet > &)
Copy constructor.
PtrList (const PtrList< sampledSet > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< sampledSet >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< sampledSet > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< sampledSet > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (sampledSet *)
Append an element at the end of the list.
void append (const autoPtr< sampledSet > &)
void append (const tmp< sampledSet > &)
void transfer (PtrList< sampledSet > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< sampledSet > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< sampledSet > set (const label, sampledSet *)
Set element to given T* and return old element (can be NULL)
autoPtr< sampledSet > set (const label, const autoPtr< sampledSet > &)
Set element to given autoPtr<T> and return old element.
autoPtr< sampledSet > set (const label, const tmp< sampledSet > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< sampledSet > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< sampledSet >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Set of sets to sample. Call sampledSets.write() to sample&write files.
Source files
sampledSets.H
sampledSets.C
Definition at line 59 of file sampledSets.H.
Constructor & Destructor Documentation
sampledSets (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
allow the possibility to load fields from files
Definition at line 133 of file sampledSets.C.
References polyMesh::defaultRegion, UPstream::parRun(), and Foam::read().
~sampledSets () virtual
Destructor.
Definition at line 168 of file sampledSets.C.
Member Function Documentation
TypeName ("sets")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the set of probes.
Definition at line 276 of file sampledSets.H.
References sampledSets::correct(), sampledSets::end(), sampledSets::execute(), sampledSets::movePoints(), sampledSets::read(), sampledSets::readUpdate(), sampledSets::timeSet(), sampledSets::updateMesh(), sampledSets::verbose(), and sampledSets::write().
void verbose (const bool verbosity = true)
Set verbosity level.
Definition at line 174 of file sampledSets.C.
Referenced by sampledSets::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 180 of file sampledSets.C.
Referenced by sampledSets::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 184 of file sampledSets.C.
Referenced by sampledSets::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 188 of file sampledSets.C.
Referenced by sampledSets::name().
void write () virtual
Sample and write.
Definition at line 192 of file sampledSets.C.
References Foam::endl(), UPstream::master(), Foam::mkDir(), Foam::nl, and Foam::Pout.
Referenced by sampledSets::name().
void read (const dictionary & dict) virtual
Read the sampledSets.
Definition at line 235 of file sampledSets.C.
References dict, Foam::endl(), forAll, dictionary::found(), Foam::Info, dictionary::lookup(), UPstream::master(), Foam::nl, and Foam::Pout.
Referenced by sampledSets::name().
void correct ()
Correct for mesh changes.
Definition at line 281 of file sampledSets.C.
Referenced by sampledSets::name().
void updateMesh (const mapPolyMesh &) virtual
Update for changes of mesh.
Definition at line 299 of file sampledSets.C.
References correct.
Referenced by sampledSets::name().
void movePoints (const polyMesh &) virtual
Update for mesh point-motion.
Definition at line 305 of file sampledSets.C.
References correct.
Referenced by sampledSets::name().
void readUpdate (const polyMesh::readUpdateState state) virtual
Update for changes of mesh due to readUpdate.
Definition at line 311 of file sampledSets.C.
References correct, and polyMesh::UNCHANGED.
Referenced by sampledSets::name().
The documentation for this class was generated from the following files:
src/sampling/sampledSet/sampledSets/sampledSets.H
src/sampling/sampledSet/sampledSets/sampledSets.C
src/sampling/sampledSet/sampledSets/sampledSetsGrouping.C
src/sampling/sampledSet/sampledSets/sampledSetsTemplates.C