OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sampledIsoSurfaceCell Class Reference
A sampledSurface defined by a surface of iso value. Always triangulated. To be used in sampleSurfaces / functionObjects. Recalculates iso surface only if time changes.
Public Member Functions
TypeName ("sampledIsoSurfaceCell")
Runtime type information.
sampledIsoSurfaceCell (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
virtual ~sampledIsoSurfaceCell ()
Destructor.
virtual bool needsUpdate () const
Does the surface need an update?
virtual bool expire ()
Mark the surface as needing an update.
virtual bool update ()
Update the surface as required.
virtual const pointField & points () const
Points of surface.
virtual const faceList & faces () const
Faces of surface.
virtual tmp< scalarField > sample (const volScalarField &) const
Sample field on surface.
virtual tmp< vectorField > sample (const volVectorField &) const
Sample field on surface.
virtual tmp< sphericalTensorField > sample (const volSphericalTensorField &) const
Sample field on surface.
virtual tmp< symmTensorField > sample (const volSymmTensorField &) const
Sample field on surface.
virtual tmp< tensorField > sample (const volTensorField &) const
Sample field on surface.
virtual tmp< scalarField > interpolate (const interpolation< scalar > &) const
Interpolate field on surface.
virtual tmp< vectorField > interpolate (const interpolation< vector > &) const
Interpolate field on surface.
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &) const
Interpolate field on surface.
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &) const
Interpolate field on surface.
virtual tmp< tensorField > interpolate (const interpolation< tensor > &) const
Interpolate field on surface.
virtual void print (Ostream &) const
Write.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleField (const GeometricField< Type, fvPatchField, volMesh > &vField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateField (const interpolation< Type > &interpolator) const
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &, const dictionary &)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor.
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool interpolate () const
Interpolation requested for surface.
virtual const vectorField & Sf () const
Return face area vectors.
virtual const scalarField & magSf () const
Return face area magnitudes.
virtual const vectorField & Cf () const
Return face centres as vectorField.
scalar area () const
The total surface area.
template<class Type >
Type integrate (const Field< Type > &) const
Integration of a field across the surface.
template<class Type >
Type integrate (const tmp< Field< Type >> &) const
Integration of a field across the surface.
template<class Type >
Type average (const Field< Type > &) const
Area-averaged value of a field across the surface.
template<class Type >
Type average (const tmp< Field< Type >> &) const
Area-averaged value of a field across the surface.
tmp< Field< scalar > > project (const Field< scalar > &) const
Project field onto surface.
tmp< Field< scalar > > project (const Field< vector > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< sphericalTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< symmTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< tensor > &) const
Project field onto surface.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Interpolate from points to cell centre.
virtual tmp< scalarField > sample (const surfaceScalarField &) const
Surface sample field on surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &) const
Surface sample field on surface.
virtual tmp< tensorField > sample (const surfaceTensorField &) const
Surface sample field on surface.
virtual void rename (const word &newName)
Rename.
template<class ReturnType , class Type >
Foam::tmp< Foam::Field< ReturnType > > project (const tmp< Field< Type >> &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Public Member Functions inherited from triSurface
ClassName ("triSurface")
Runtime type information.
triSurface ()
Construct null.
triSurface (const List< labelledTri > &, const geometricSurfacePatchList &, const pointField &)
Construct from triangles, patches, points.
triSurface (List< labelledTri > &, const geometricSurfacePatchList &, pointField &, const bool reuse)
Construct from triangles, patches, points. Reuse storage.
triSurface (const Xfer< List< labelledTri >> &, const geometricSurfacePatchList &, const Xfer< List< point >> &)
Construct from triangles, patches, points.
triSurface (const List< labelledTri > &, const pointField &)
Construct from triangles, points. Set patchnames to default.
triSurface (const triFaceList &, const pointField &)
Construct from triangles, points. Set region to 0 and default.
triSurface (const fileName &)
Construct from file name (uses extension to determine type)
triSurface (Istream &)
Construct from Istream.
triSurface (const Time &d)
Construct from objectRegistry.
triSurface (const triSurface &)
Construct as copy.
~triSurface ()
Destructor.
void clearOut ()
void clearTopology ()
void clearPatchMeshAddr ()
const geometricSurfacePatchList & patches () const
geometricSurfacePatchList & patches ()
const labelListList & sortedEdgeFaces () const
Return edge-face addressing sorted (for edges with more than.
const labelList & edgeOwner () const
If 2 face neighbours: label of face where ordering of edge.
virtual void movePoints (const pointField &)
Move points.
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void checkTriangles (const bool verbose)
Check/remove duplicate/degenerate triangles.
void checkEdges (const bool verbose)
Check triply (or more) connected edges.
void cleanup (const bool verbose)
Remove non-valid triangles.
void markZone (const boolList &borderEdge, const label facei, const label currentZone, labelList &faceZone) const
Fill faceZone with currentZone for every face reachable.
label markZones (const boolList &borderEdge, labelList &faceZone) const
(size and) fills faceZone with zone of face. Zone is area
void subsetMeshMap (const boolList &include, labelList &pointMap, labelList &faceMap) const
'Create' sub mesh, including only faces for which
triSurface subsetMesh (const boolList &include, labelList &pointMap, labelList &faceMap) const
Return new surface. Returns pointMap, faceMap from.
void write (Ostream &) const
Write to Ostream in simple FOAM format.
void write (const fileName &, const bool sortByRegion=false) const
Generic write routine. Chooses writer based on extension.
void write (const Time &) const
Write to database.
void writeDX (const scalarField &, Ostream &) const
Write to Ostream in OpenDX format.
void writeDX (const vectorField &, Ostream &) const
void writeStats (Ostream &) const
Write some statistics.
void operator= (const triSurface &)
Public Member Functions inherited from PrimitivePatch< labelledTri,::Foam::List, pointField, point >
PrimitivePatch (const ::Foam::List< labelledTri > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (const Xfer< ::Foam::List< labelledTri >> &faces, const Xfer< List< point >> &points)
Construct from components.
PrimitivePatch (::Foam::List< labelledTri > &faces, Field< point > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< labelledTri,::Foam::List, pointField, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< labelledTri > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceNormals () const
Return face normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< labelledTri,::Foam::List, pointField, point > &)
Assignment.
Public Member Functions inherited from List< labelledTri >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const labelledTri &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< labelledTri > &)
Copy constructor.
List (const Xfer< List< labelledTri >> &)
Construct by transferring the parameter contents.
List (List< labelledTri > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< labelledTri > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< labelledTri, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< labelledTri > &)
Construct as copy of PtrList<T>
List (const SLList< labelledTri > &)
Construct as copy of SLList<T>
List (const UIndirectList< labelledTri > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< labelledTri > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< labelledTri > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const labelledTri &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const labelledTri &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const labelledTri &)
Append an element at the end of the list.
void append (const UList< labelledTri > &)
Append a List at the end of this list.
void append (const UIndirectList< labelledTri > &)
Append a UIndirectList at the end of this list.
void transfer (List< labelledTri > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< labelledTri, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< labelledTri > &)
Transfer the contents of the argument List into this list.
Xfer< List< labelledTri > > xfer ()
Transfer contents to the Xfer container.
labelledTri & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< labelledTri > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< labelledTri > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< labelledTri > &)
Assignment operator. Takes linear time.
void operator= (const SLList< labelledTri > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< labelledTri > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< labelledTri > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const labelledTri &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Additional Inherited Members
Public Types inherited from triSurface
typedef bool BoundaryMesh
Placeholder only, but do not remove - it is needed for GeoMesh.
Public Types inherited from PrimitivePatch< labelledTri,::Foam::List, pointField, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef labelledTri FaceType
typedef ::Foam::List< labelledTri > FaceListType
typedef pointField PointFieldType
Public Types inherited from List< labelledTri >
typedef SubList< labelledTri > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &, const dictionary &)
Return a reference to the selected surface.
Static Public Member Functions inherited from triSurface
static fileName triSurfInstance (const Time &)
Name of triSurface directory to use.
Static Public Member Functions inherited from List< labelledTri >
static const List< labelledTri > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
Protected Member Functions inherited from triSurface
pointField & storedPoints ()
Non-const access to global points.
List< Face > & storedFaces ()
Non-const access to the faces.
Protected Member Functions inherited from List< labelledTri >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
A sampledSurface defined by a surface of iso value. Always triangulated. To be used in sampleSurfaces / functionObjects. Recalculates iso surface only if time changes.
Source files
sampledIsoSurfaceCell.H
sampledIsoSurfaceCell.C
Definition at line 51 of file sampledIsoSurfaceCell.H.
Constructor & Destructor Documentation
sampledIsoSurfaceCell (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 200 of file sampledIsoSurfaceCell.C.
~sampledIsoSurfaceCell () virtual
Destructor.
Definition at line 220 of file sampledIsoSurfaceCell.C.
Member Function Documentation
TypeName ("sampledIsoSurfaceCell")
Runtime type information.
bool needsUpdate () const virtual
Does the surface need an update?
Implements sampledSurface.
Definition at line 226 of file sampledIsoSurfaceCell.C.
References mesh, fvMesh::time(), and TimeState::timeIndex().
bool expire () virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implements sampledSurface.
Definition at line 234 of file sampledIsoSurfaceCell.C.
References sampledSurface::clearGeom().
bool update () virtual
Update the surface as required.
Do nothing (and return false) if no update was needed
Implements sampledSurface.
Definition at line 253 of file sampledIsoSurfaceCell.C.
References sampledIsoSurfaceCell::sample().
virtual const pointField& points () const inline virtual
Points of surface.
Implements sampledSurface.
Definition at line 142 of file sampledIsoSurfaceCell.H.
References PrimitivePatch< labelledTri,::Foam::List, pointField, point >::points().
virtual const faceList& faces () const inline virtual
Faces of surface.
Implements sampledSurface.
Definition at line 148 of file sampledIsoSurfaceCell.H.
References autoPtr< T >::empty(), forAll, sampledSurface::interpolate(), sampledIsoSurfaceCell::print(), autoPtr< T >::reset(), s(), sampledIsoSurfaceCell::sample(), and List< T >::size().
Foam::tmp< Foam::scalarField > sample (const volScalarField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 261 of file sampledIsoSurfaceCell.C.
Referenced by sampledIsoSurfaceCell::faces(), sampledIsoSurfaceCell::sample(), and sampledIsoSurfaceCell::update().
Foam::tmp< Foam::vectorField > sample (const volVectorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 271 of file sampledIsoSurfaceCell.C.
References sampledIsoSurfaceCell::sample().
Foam::tmp< Foam::sphericalTensorField > sample (const volSphericalTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 281 of file sampledIsoSurfaceCell.C.
References sampledIsoSurfaceCell::sample().
Foam::tmp< Foam::symmTensorField > sample (const volSymmTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 291 of file sampledIsoSurfaceCell.C.
References sampledIsoSurfaceCell::sample().
Foam::tmp< Foam::tensorField > sample (const volTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 301 of file sampledIsoSurfaceCell.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 311 of file sampledIsoSurfaceCell.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 321 of file sampledIsoSurfaceCell.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 330 of file sampledIsoSurfaceCell.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 340 of file sampledIsoSurfaceCell.C.
References sampledSurface::interpolate().
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 350 of file sampledIsoSurfaceCell.C.
void print (Ostream & os) const virtual
Write.
Reimplemented from sampledSurface.
Definition at line 358 of file sampledIsoSurfaceCell.C.
References Foam::name().
Referenced by sampledIsoSurfaceCell::faces().
Foam::tmp<Foam::Field<Type> > sampleField (const GeometricField< Type, fvPatchField, volMesh > & vField) const
Definition at line 37 of file sampledIsoSurfaceCellTemplates.C.
Foam::tmp<Foam::Field<Type> > interpolateField (const interpolation< Type > & interpolator) const
Definition at line 51 of file sampledIsoSurfaceCellTemplates.C.
References f(), forAll, interpolation< Type >::interpolate(), points, and tmp< T >::ref().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/isoSurface/sampledIsoSurfaceCell.H
src/sampling/sampledSurface/isoSurface/sampledIsoSurfaceCell.C
src/sampling/sampledSurface/isoSurface/sampledIsoSurfaceCellTemplates.C