OpenFOAM: reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh > Class Template Reference
reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh > Class Template Reference
Static Public Member Functions
static tmp< GeometricField< TypeR, PatchField, GeoMesh > > New (const tmp< GeometricField< TypeR, PatchField, GeoMesh >> &tgf1, const tmp< GeometricField< Type2, PatchField, GeoMesh >> &tgf2, const word &name, const dimensionSet &dimensions)
Detailed Description
template<class TypeR, class Type2, template< class > class PatchField, class GeoMesh>
class Foam::reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >
Definition at line 303 of file GeometricFieldReuseFunctions.H.
Member Function Documentation
static tmp<GeometricField<TypeR, PatchField, GeoMesh> > New (const tmp< GeometricField< TypeR, PatchField, GeoMesh >> & tgf1, const tmp< GeometricField< Type2, PatchField, GeoMesh >> & tgf2, const word & name, const dimensionSet & dimensions) inline static
Definition at line 308 of file GeometricFieldReuseFunctions.H.
References IOobject::db(), DimensionedField< Type, GeoMesh >::dimensions(), IOobject::instance(), DimensionedField< Type, GeoMesh >::mesh(), regIOobject::rename(), and Foam::reusable().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricFieldReuseFunctions.H