OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sensibleEnthalpy< Thermo > Class Template Reference
Thermodynamics mapping class to expose the sensible enthalpy function as the standard enthalpy function h(T).
Public Member Functions
sensibleEnthalpy ()
Construct.
scalar he (const Thermo &thermo, const scalar p, const scalar T) const
scalar cpv (const Thermo &thermo, const scalar p, const scalar T) const
scalar cpBycpv (const Thermo &thermo, const scalar p, const scalar T) const
cp/cp []
scalar HE (const Thermo &thermo, const scalar p, const scalar T) const
scalar THE (const Thermo &thermo, const scalar h, const scalar p, const scalar T0) const
Temperature from sensible enthalpy.
Static Public Member Functions
static word typeName ()
Return the instantiated type name.
static word name ()
Detailed Description
template<class Thermo>
class Foam::sensibleEnthalpy< Thermo >
Thermodynamics mapping class to expose the sensible enthalpy function as the standard enthalpy function h(T).
Definition at line 45 of file sensibleEnthalpy.H.
Constructor & Destructor Documentation
sensibleEnthalpy () inline
Construct.
Definition at line 53 of file sensibleEnthalpy.H.
Member Function Documentation
static word typeName () inline static
Return the instantiated type name.
Definition at line 60 of file sensibleEnthalpy.H.
static word name () inline static
Definition at line 67 of file sensibleEnthalpy.H.
References sensibleEnthalpy< Thermo >::he().
scalar he (const Thermo & thermo, const scalar p, const scalar T) const inline
Definition at line 74 of file sensibleEnthalpy.H.
References sensibleEnthalpy< Thermo >::cpv().
Referenced by sensibleEnthalpy< Thermo >::name().
scalar cpv (const Thermo & thermo, const scalar p, const scalar T) const inline
Definition at line 85 of file sensibleEnthalpy.H.
References sensibleEnthalpy< Thermo >::cpBycpv().
Referenced by sensibleEnthalpy< Thermo >::he().
scalar cpBycpv (const Thermo & thermo, const scalar p, const scalar T) const inline
cp/cp []
Definition at line 96 of file sensibleEnthalpy.H.
References sensibleEnthalpy< Thermo >::HE().
Referenced by sensibleEnthalpy< Thermo >::cpv().
scalar HE (const Thermo & thermo, const scalar p, const scalar T) const inline
Definition at line 107 of file sensibleEnthalpy.H.
References sensibleEnthalpy< Thermo >::THE().
Referenced by sensibleEnthalpy< Thermo >::cpBycpv().
scalar THE (const Thermo & thermo, const scalar h, const scalar p, const scalar T0) const inline
Temperature from sensible enthalpy.
given an initial temperature T0
Definition at line 119 of file sensibleEnthalpy.H.
Referenced by sensibleEnthalpy< Thermo >::HE().
The documentation for this class was generated from the following file:
src/thermophysicalModels/specie/thermo/sensibleEnthalpy/sensibleEnthalpy.H