OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
rigidBody Class Reference
Public Member Functions
TypeName ("rigidBody")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, rigidBody, dictionary,(const word &name, const dictionary &dict),(name, dict))
rigidBody (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
Construct from mass, centre of mass and moment of inertia tensor.
rigidBody (const word &name, const rigidBodyInertia &rbi)
Construct from with the given rigidBodyInertia.
rigidBody (const word &name, const dictionary &dict)
Construct from dictionary.
virtual autoPtr< rigidBody > clone () const
Return clone of this rigidBody.
virtual ~rigidBody ()
Destructor.
const word & name () const
Return name.
virtual bool massless () const
Return false as this body is not massless.
void merge (const subBody &)
Merge a body into this parent body.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from rigidBodyInertia
rigidBodyInertia ()
Null constructor, initializes to zero.
rigidBodyInertia (const scalar m, const vector &c, const symmTensor &Ic)
Construct from mass, centre of mass and moment of inertia tensor.
rigidBodyInertia (const dictionary &dict)
Construct from dictionary.
rigidBodyInertia (const spatialTensor &st)
Construct from the components of a spatial tensor.
rigidBodyInertia (Istream &is)
Construct from Istream.
scalar m () const
Return the mass of the rigid-body.
const vector & c () const
Return the centre of mass of the rigid-body.
const symmTensor & Ic () const
Return the inertia tensor of the rigid-body about the centre of mass.
symmTensor Ioc () const
Return the difference between the inertia tensor of the rigid-body.
symmTensor Icc (const vector &c) const
Return the difference between the inertia tensor of the rigid-body.
symmTensor Io () const
Return the inertia tensor of the rigid-body about the origin.
scalar kineticEnergy (const spatialVector &v)
Return the kinetic energy of the body with the given velocity.
operator spatialTensor () const
Conversion to spatial tensor.
void operator+= (const rigidBodyInertia &)
Static Public Member Functions
static autoPtr< rigidBody > New (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
Select constructed from components.
static autoPtr< rigidBody > New (const word &name, const dictionary &dict)
Select constructed from name and dictionary.
Static Public Member Functions inherited from rigidBodyInertia
static symmTensor Ioc (const scalar m, const vector &c)
Return the difference between the inertia tensor of the rigid-body.
Friends
Ostream & operator<< (Ostream &, const rigidBody &)
Detailed Description
Source files
rigidBody.H
rigidBodyI.H
Definition at line 60 of file rigidBody.H.
Constructor & Destructor Documentation
rigidBody (const word & name, const scalar & m, const vector & c, const symmTensor & Ic) inline
Construct from mass, centre of mass and moment of inertia tensor.
about the centre of mass
Definition at line 29 of file rigidBodyI.H.
Referenced by rigidBody::rigidBody().
rigidBody (const word & name, const rigidBodyInertia & rbi) inline
Construct from with the given rigidBodyInertia.
Definition at line 42 of file rigidBodyI.H.
References rigidBody::rigidBody().
rigidBody (const word & name, const dictionary & dict) inline
Construct from dictionary.
Definition at line 53 of file rigidBodyI.H.
~rigidBody () virtual
Destructor.
Definition at line 98 of file rigidBody.C.
Member Function Documentation
TypeName ("rigidBody")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , rigidBody , dictionary , (const word &name, const dictionary &dict) , (name, dict))
Foam::autoPtr< Foam::RBD::rigidBody > clone () const virtual
Return clone of this rigidBody.
Reimplemented in sphere, jointBody, masslessBody, and compositeBody.
Definition at line 51 of file rigidBody.C.
References rigidBody::New().
Foam::autoPtr< Foam::RBD::rigidBody > New (const word & name, const scalar & m, const vector & c, const symmTensor & Ic) static
Select constructed from components.
Definition at line 60 of file rigidBody.C.
Referenced by rigidBody::clone(), and rigidBodyModel::rigidBodyModel().
Foam::autoPtr< Foam::RBD::rigidBody > New (const word & name, const dictionary & dict) static
Select constructed from name and dictionary.
Definition at line 72 of file rigidBody.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), Foam::name(), and Foam::nl.
const Foam::word & name () const inline
Return name.
Definition at line 65 of file rigidBodyI.H.
Referenced by rigidBodyModel::join_().
bool massless () const virtual
Return false as this body is not massless.
Reimplemented in masslessBody.
Definition at line 104 of file rigidBody.C.
void merge (const subBody & subBody)
Merge a body into this parent body.
Definition at line 110 of file rigidBody.C.
References subBody::body(), subBody::masterXT(), Foam::name(), and Foam::RBD::transform().
void write (Ostream & os) const virtual
Write.
Reimplemented in sphere, masslessBody, and compositeBody.
Definition at line 120 of file rigidBody.C.
References Foam::constant::universal::c, token::END_STATEMENT, Foam::nl, Foam::type(), and Ostream::writeKeyword().
Referenced by Foam::RBD::operator<<().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const rigidBody &) friend
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/bodies/rigidBody/rigidBody.H
src/rigidBodyDynamics/bodies/rigidBody/rigidBody.C
src/rigidBodyDynamics/bodies/rigidBody/rigidBodyI.H