OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
searchableSurfaceWithGaps Class Reference
searchableSurface using multiple slightly shifted underlying surfaces to make sure pierces don't go through gaps:
Public Member Functions
TypeName ("searchableSurfaceWithGaps")
Runtime type information.
searchableSurfaceWithGaps (const IOobject &io, const dictionary &dict)
Construct from dictionary (used by searchableSurface)
virtual ~searchableSurfaceWithGaps ()
Destructor.
const searchableSurface & surface () const
virtual const wordList & regions () const
Names of regions.
virtual bool hasVolumeType () const
Whether supports volume type below.
virtual label size () const
Range of local indices that can be returned.
virtual tmp< pointField > coordinates () const
Get representative set of element coordinates.
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const
Get bounding spheres (centre and radius squared), one per element.
virtual tmp< pointField > points () const
Get the points that define the surface.
virtual bool overlaps (const boundBox &bb) const
Does any part of the surface overlap the supplied bound box?
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &info) const
Find nearest on original surface. Note:does not use perturbation.
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Find first intersection on segment from start to end.
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Return any intersection on segment from start to end.
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit >> &) const
Get all intersections in order from start to end.
virtual void getRegion (const List< pointIndexHit > &info, labelList &region) const
From a set of points and indices get the region.
virtual void getNormal (const List< pointIndexHit > &info, vectorField &normal) const
From a set of points and indices get the normal.
virtual void getVolumeType (const pointField &samples, List< volumeType > &info) const
Determine type (inside/outside/mixed) for point. unknown if.
virtual void setField (const labelList &values)
Set bounds of surface. Bounds currently set as list of.
virtual void getField (const List< pointIndexHit > &info, labelList &values) const
WIP. From a set of hits (points and.
bool writeData (Ostream &os) const
Pure virtual writaData function.
Public Member Functions inherited from searchableSurface
TypeName ("searchableSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr< searchableSurface > clone () const
Clone.
virtual ~searchableSurface ()
Destructor.
const boundBox & bounds () const
Return const reference to boundBox.
boundBox & bounds ()
Return non-const access to the boundBox to allow it to be set.
virtual label globalSize () const
Range of global indices that can be returned.
virtual void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
Find the nearest locations for the supplied points to a.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &, vectorField &normal, labelList &region) const
Find nearest, normal and region. Can be overridden with.
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
Set bounds of surface. Bounds currently set as list of.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from searchableSurface
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Return a reference to the selected searchableSurface.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
searchableSurface using multiple slightly shifted underlying surfaces to make sure pierces don't go through gaps:
- shift test vector with two small vectors (of size gap_) perpendicular to the original. Test with + and - this vector. Only if both register a hit is it seen as one.
extend the test vector slightly (with SMALL) to account for numerical inaccuracies.
Source files
searchableSurfaceWithGaps.H
searchableSurfaceWithGaps.C
Definition at line 59 of file searchableSurfaceWithGaps.H.
Constructor & Destructor Documentation
searchableSurfaceWithGaps (const IOobject & io, const dictionary & dict)
Construct from dictionary (used by searchableSurface)
Definition at line 175 of file searchableSurfaceWithGaps.C.
References searchableSurface::bounds(), IOobject::db(), dictionary::lookup(), objectRegistry::lookupObject(), and s().
~searchableSurfaceWithGaps () virtual
Destructor.
Definition at line 197 of file searchableSurfaceWithGaps.C.
References searchableSurfaceWithGaps::findLine().
Member Function Documentation
TypeName ("searchableSurfaceWithGaps")
Runtime type information.
const searchableSurface& surface () const inline
Definition at line 128 of file searchableSurfaceWithGaps.H.
Referenced by searchableSurfaceWithGaps::boundingSpheres(), searchableSurfaceWithGaps::findNearest(), searchableSurfaceWithGaps::getField(), searchableSurfaceWithGaps::getNormal(), searchableSurfaceWithGaps::getRegion(), searchableSurfaceWithGaps::getVolumeType(), searchableSurfaceWithGaps::hasVolumeType(), searchableSurfaceWithGaps::points(), searchableSurfaceWithGaps::regions(), searchableSurfaceWithGaps::size(), and searchableSurfaceWithGaps::writeData().
virtual const wordList& regions () const inline virtual
Names of regions.
Implements searchableSurface.
Definition at line 134 of file searchableSurfaceWithGaps.H.
References searchableSurface::regions(), and searchableSurfaceWithGaps::surface().
virtual bool hasVolumeType () const inline virtual
Whether supports volume type below.
Implements searchableSurface.
Definition at line 140 of file searchableSurfaceWithGaps.H.
References searchableSurface::hasVolumeType(), and searchableSurfaceWithGaps::surface().
virtual label size () const inline virtual
Range of local indices that can be returned.
Implements searchableSurface.
Definition at line 146 of file searchableSurfaceWithGaps.H.
References searchableSurfaceWithGaps::boundingSpheres(), searchableSurfaceWithGaps::coordinates(), searchableSurface::coordinates(), searchableSurface::size(), and searchableSurfaceWithGaps::surface().
virtual tmp<pointField> coordinates () const inline virtual
Get representative set of element coordinates.
Usually the element centres (should be of length size()).
Implements searchableSurface.
Definition at line 153 of file searchableSurfaceWithGaps.H.
Referenced by searchableSurfaceWithGaps::size().
virtual void boundingSpheres (pointField & centres, scalarField & radiusSqr) const inline virtual
Get bounding spheres (centre and radius squared), one per element.
Any point on element is guaranteed to be inside.
Implements searchableSurface.
Definition at line 161 of file searchableSurfaceWithGaps.H.
References searchableSurface::boundingSpheres(), and searchableSurfaceWithGaps::surface().
Referenced by searchableSurfaceWithGaps::size().
virtual tmp<pointField> points () const inline virtual
Get the points that define the surface.
Implements searchableSurface.
Definition at line 170 of file searchableSurfaceWithGaps.H.
References searchableSurfaceWithGaps::findNearest(), searchableSurfaceWithGaps::overlaps(), searchableSurface::overlaps(), searchableSurface::points(), and searchableSurfaceWithGaps::surface().
virtual bool overlaps (const boundBox & bb) const inline virtual
Does any part of the surface overlap the supplied bound box?
Note: use perturbed surface? Since uses boundbox of points and not actual intersection chosen to use unperturbed surface.
Implements searchableSurface.
Definition at line 178 of file searchableSurfaceWithGaps.H.
Referenced by searchableSurfaceWithGaps::points().
virtual void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info) const inline virtual
Find nearest on original surface. Note:does not use perturbation.
and hence might be inconsistent with intersections.
Implements searchableSurface.
Definition at line 189 of file searchableSurfaceWithGaps.H.
References searchableSurfaceWithGaps::findLine(), searchableSurfaceWithGaps::findLineAll(), searchableSurfaceWithGaps::findLineAny(), searchableSurface::findNearest(), searchableSurfaceWithGaps::getRegion(), and searchableSurfaceWithGaps::surface().
Referenced by searchableSurfaceWithGaps::points().
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Find first intersection on segment from start to end.
Note: searchableSurfacesQueries expects no intersection to be found if start==end. Is problem?
Implements searchableSurface.
Definition at line 204 of file searchableSurfaceWithGaps.C.
References Foam::e, searchableSurfaceWithGaps::findLineAny(), forAll, Foam::returnReduce(), List< T >::setSize(), and List< T >::size().
Referenced by searchableSurfaceWithGaps::findNearest(), and searchableSurfaceWithGaps::~searchableSurfaceWithGaps().
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Return any intersection on segment from start to end.
Implements searchableSurface.
Definition at line 329 of file searchableSurfaceWithGaps.C.
References searchableSurfaceWithGaps::findLineAll().
Referenced by searchableSurfaceWithGaps::findLine(), and searchableSurfaceWithGaps::findNearest().
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit >> & info) const virtual
Get all intersections in order from start to end.
Implements searchableSurface.
Definition at line 341 of file searchableSurfaceWithGaps.C.
References List< T >::clear(), forAll, List< T >::setSize(), and List< T >::size().
Referenced by searchableSurfaceWithGaps::findLineAny(), and searchableSurfaceWithGaps::findNearest().
virtual void getRegion (const List< pointIndexHit > & info, labelList & region) const inline virtual
From a set of points and indices get the region.
Implements searchableSurface.
Definition at line 227 of file searchableSurfaceWithGaps.H.
References searchableSurfaceWithGaps::getNormal(), searchableSurface::getRegion(), and searchableSurfaceWithGaps::surface().
Referenced by searchableSurfaceWithGaps::findNearest().
virtual void getNormal (const List< pointIndexHit > & info, vectorField & normal) const inline virtual
From a set of points and indices get the normal.
Implements searchableSurface.
Definition at line 237 of file searchableSurfaceWithGaps.H.
References searchableSurface::getNormal(), searchableSurfaceWithGaps::getVolumeType(), and searchableSurfaceWithGaps::surface().
Referenced by searchableSurfaceWithGaps::getRegion().
virtual void getVolumeType (const pointField & samples, List< volumeType > & info) const inline virtual
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Implements searchableSurface.
Definition at line 248 of file searchableSurfaceWithGaps.H.
References searchableSurfaceWithGaps::getField(), searchableSurface::getVolumeType(), searchableSurfaceWithGaps::setField(), and searchableSurfaceWithGaps::surface().
Referenced by searchableSurfaceWithGaps::getNormal().
virtual void setField (const labelList & values) inline virtual
Set bounds of surface. Bounds currently set as list of.
bounding boxes. The bounds are hints to the surface as for the range of queries it can expect. faceMap/pointMap can be set if the surface has done any redistribution. virtual void distribute (const List<treeBoundBox>& bbs, const bool keepNonLocal, autoPtr<mapDistribute>& faceMap, autoPtr<mapDistribute>& pointMap) { subGeom_[0].distribute(bbs, keepNonLocal, faceMap, pointMap); }WIP. Store element-wise field.
Reimplemented from searchableSurface.
Definition at line 275 of file searchableSurfaceWithGaps.H.
Referenced by searchableSurfaceWithGaps::getVolumeType().
virtual void getField (const List< pointIndexHit > & info, labelList & values) const inline virtual
WIP. From a set of hits (points and.
indices) get the specified field. Misses do not get set. Return empty field if not supported.
Reimplemented from searchableSurface.
Definition at line 284 of file searchableSurfaceWithGaps.H.
References searchableSurface::getField(), and searchableSurfaceWithGaps::surface().
Referenced by searchableSurfaceWithGaps::getVolumeType().
bool writeData (Ostream &) const inline virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 294 of file searchableSurfaceWithGaps.H.
References searchableSurfaceWithGaps::surface(), and regIOobject::writeData().
The documentation for this class was generated from the following files:
src/meshTools/searchableSurface/searchableSurfaceWithGaps.H
src/meshTools/searchableSurface/searchableSurfaceWithGaps.C