OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sampledSurfaces Class Reference
Set of surfaces to sample.
Public Member Functions
TypeName ("surfaces")
Runtime type information.
sampledSurfaces (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~sampledSurfaces ()
Destructor.
virtual bool needsUpdate () const
Does any of the surfaces need an update?
virtual bool expire ()
Mark the surfaces as needing an update.
virtual bool update ()
Update the surfaces as required and merge surface points (parallel).
virtual const word & name () const
Return name of the set of surfaces.
void verbose (const bool verbosity=true)
Set verbosity level.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Sample and write.
virtual void read (const dictionary &)
Read the sampledSurfaces dictionary.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh - expires the surfaces.
virtual void movePoints (const polyMesh &)
Update for mesh point-motion - expires the surfaces.
virtual void readUpdate (const polyMesh::readUpdateState state)
Update for changes of mesh due to readUpdate - expires the surfaces.
Public Member Functions inherited from PtrList< sampledSurface >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< sampledSurface > &)
Copy constructor.
PtrList (const PtrList< sampledSurface > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< sampledSurface >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< sampledSurface > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< sampledSurface > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
label size () const
Return the number of elements in the PtrList.
bool empty () const
Return true if the PtrList is empty (ie, size() is zero).
sampledSurface & first ()
Return reference to the first element of the list.
const sampledSurface & first () const
Return reference to first element of the list.
sampledSurface & last ()
Return reference to the last element of the list.
const sampledSurface & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (sampledSurface *)
Append an element at the end of the list.
void append (const autoPtr< sampledSurface > &)
void append (const tmp< sampledSurface > &)
void transfer (PtrList< sampledSurface > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< sampledSurface > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< sampledSurface > set (const label, sampledSurface *)
Set element. Return old element (can be NULL).
autoPtr< sampledSurface > set (const label, const autoPtr< sampledSurface > &)
autoPtr< sampledSurface > set (const label, const tmp< sampledSurface > &)
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const sampledSurface & operator[] (const label) const
Return element const reference.
sampledSurface & operator[] (const label)
Return element reference.
const sampledSurface * operator() (const label) const
Return element const pointer.
void operator= (const PtrList< sampledSurface > &)
Assignment.
iterator begin ()
Return an iterator to begin traversing the PtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the PtrList.
iterator end ()
Return an iterator to end traversing the PtrList.
const_iterator end () const
Return an const_iterator to end traversing the PtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the PtrList.
const_iterator cend () const
Return an const_iterator to end traversing the PtrList.
Additional Inherited Members
Public Types inherited from PtrList< sampledSurface >
typedef sampledSurface value_type
Type of values the PtrList contains.
typedef sampledSurface & reference
Type that can be used for storing into PtrList::value_type objects.
typedef const sampledSurface & const_reference
Type that can be used for storing into constant PtrList::value_type.
Protected Member Functions inherited from PtrList< sampledSurface >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Set of surfaces to sample.
The write() method is used to sample and write files.
Source files
sampledSurfaces.H
sampledSurfaces.C
Definition at line 58 of file sampledSurfaces.H.
Constructor & Destructor Documentation
sampledSurfaces (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
allow the possibility to load fields from files
Definition at line 88 of file sampledSurfaces.C.
References UPstream::parRun(), and Foam::read().
~sampledSurfaces () virtual
Destructor.
Definition at line 120 of file sampledSurfaces.C.
Member Function Documentation
TypeName ("surfaces")
Runtime type information.
bool needsUpdate () const virtual
Does any of the surfaces need an update?
Definition at line 277 of file sampledSurfaces.C.
References forAll.
bool expire () virtual
Mark the surfaces as needing an update.
May also free up unneeded data. Return false if all surfaces were already marked as expired.
Definition at line 291 of file sampledSurfaces.C.
References forAll, and UPstream::parRun().
bool update () virtual
Update the surfaces as required and merge surface points (parallel).
Return false if no surfaces required an update.
Definition at line 314 of file sampledSurfaces.C.
References Foam::endl(), sampledSurface::faces(), forAll, PatchTools::gatherAndMerge(), UPstream::master(), Foam::nl, UPstream::parRun(), points, sampledSurface::points(), Foam::Pout, List< T >::size(), and sampledSurface::update().
virtual const word& name () const inline virtual
Return name of the set of surfaces.
Definition at line 209 of file sampledSurfaces.H.
References sampledSurfaces::end(), sampledSurfaces::execute(), sampledSurfaces::movePoints(), sampledSurfaces::read(), sampledSurfaces::readUpdate(), sampledSurfaces::timeSet(), sampledSurfaces::updateMesh(), sampledSurfaces::verbose(), and sampledSurfaces::write().
void verbose (const bool verbosity = true)
Set verbosity level.
Definition at line 126 of file sampledSurfaces.C.
Referenced by sampledSurfaces::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 132 of file sampledSurfaces.C.
Referenced by sampledSurfaces::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 138 of file sampledSurfaces.C.
Referenced by sampledSurfaces::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 144 of file sampledSurfaces.C.
Referenced by sampledSurfaces::name().
void write () virtual
Sample and write.
Definition at line 150 of file sampledSurfaces.C.
References Foam::endl(), UPstream::master(), Foam::mkDir(), Foam::nl, and Foam::Pout.
Referenced by sampledSurfaces::name().
void read (const dictionary & dict) virtual
Read the sampledSurfaces dictionary.
Definition at line 195 of file sampledSurfaces.C.
References Foam::endl(), forAll, dictionary::found(), Foam::Info, dictionary::lookup(), UPstream::master(), surfaceWriter::New(), Foam::nl, UPstream::parRun(), Foam::Pout, and dictionary::subOrEmptyDict().
Referenced by sampledSurfaces::name().
void updateMesh (const mapPolyMesh &) virtual
Update for changes of mesh - expires the surfaces.
Definition at line 254 of file sampledSurfaces.C.
Referenced by sampledSurfaces::name().
void movePoints (const polyMesh &) virtual
Update for mesh point-motion - expires the surfaces.
Definition at line 262 of file sampledSurfaces.C.
Referenced by sampledSurfaces::name().
void readUpdate (const polyMesh::readUpdateState state) virtual
Update for changes of mesh due to readUpdate - expires the surfaces.
Definition at line 268 of file sampledSurfaces.C.
References polyMesh::UNCHANGED.
Referenced by sampledSurfaces::name().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledSurfaces/sampledSurfaces.H
src/sampling/sampledSurface/sampledSurfaces/sampledSurfaces.C
src/sampling/sampledSurface/sampledSurfaces/sampledSurfacesGrouping.C
src/sampling/sampledSurface/sampledSurfaces/sampledSurfacesTemplates.C