OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, Type2, GeoMesh > Class Template Reference
Static Public Member Functions
static tmp< DimensionedField< TypeR, GeoMesh > > New (const tmp< DimensionedField< TypeR, GeoMesh >> &tdf1, const tmp< DimensionedField< Type2, GeoMesh >> &tdf2, const word &name, const dimensionSet &dimensions)
Detailed Description
template<class TypeR, class Type2, class GeoMesh>
class Foam::reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, Type2, GeoMesh >
Definition at line 225 of file DimensionedFieldReuseFunctions.H.
Member Function Documentation
static tmp<DimensionedField<TypeR, GeoMesh> > New (const tmp< DimensionedField< TypeR, GeoMesh >> & tdf1, const tmp< DimensionedField< Type2, GeoMesh >> & tdf2, const word & name, const dimensionSet & dimensions) inline static
Definition at line 230 of file DimensionedFieldReuseFunctions.H.
References IOobject::db(), DimensionedField< Type, GeoMesh >::dimensions(), IOobject::instance(), DimensionedField< Type, GeoMesh >::mesh(), and regIOobject::rename().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedFieldReuseFunctions.H