OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
searchableSurfaceToFaceZone Class Reference
A topoSetSource to select faces based on intersection (of cell-cell vector) with a surface.
Public Member Functions
TypeName ("searchableSurfaceToFaceZone")
Runtime type information.
searchableSurfaceToFaceZone (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
virtual ~searchableSurfaceToFaceZone ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label cellI, const bool) const
Add (if bool) cellI to set or delete cellI from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = NULL
A table of usage strings.
Detailed Description
A topoSetSource to select faces based on intersection (of cell-cell vector) with a surface.
Source files
searchableSurfaceToFaceZone.H
searchableSurfaceToFaceZone.C
Definition at line 51 of file searchableSurfaceToFaceZone.H.
Constructor & Destructor Documentation
searchableSurfaceToFaceZone (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 62 of file searchableSurfaceToFaceZone.C.
~searchableSurfaceToFaceZone () virtual
Destructor.
Definition at line 90 of file searchableSurfaceToFaceZone.C.
References searchableSurfaceToFaceZone::applyToSet().
Member Function Documentation
TypeName ("searchableSurfaceToFaceZone")
Runtime type information.
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 84 of file searchableSurfaceToFaceZone.H.
References searchableSurfaceToFaceZone::applyToSet(), and topoSetSource::FACEZONESOURCE.
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 97 of file searchableSurfaceToFaceZone.C.
References topoSetSource::ADD, faceZoneSet::addressing(), polyPatch::coupled(), topoSetSource::DELETE, Foam::endl(), faceZoneSet::flipMap(), forAll, HashTable< T, Key, Hash >::found(), Foam::Info, topoSetSource::NEW, List< T >::size(), polyPatch::start(), syncTools::swapBoundaryCellPositions(), List< T >::transfer(), faceZoneSet::updateSet(), and WarningInFunction.
Referenced by searchableSurfaceToFaceZone::setType(), and searchableSurfaceToFaceZone::~searchableSurfaceToFaceZone().
The documentation for this class was generated from the following files:
src/meshTools/sets/faceZoneSources/searchableSurfaceToFaceZone/searchableSurfaceToFaceZone.H
src/meshTools/sets/faceZoneSources/searchableSurfaceToFaceZone/searchableSurfaceToFaceZone.C