OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
simpleMatrix< Type > Class Template Reference
A simple square matrix solver with scalar coefficients.
Public Member Functions
simpleMatrix (const label)
Construct given size.
simpleMatrix (const label, const scalar, const Type &)
Construct given size and initial values for coefficients and source.
simpleMatrix (const scalarSquareMatrix &, const Field< Type > &)
Construct from components.
simpleMatrix (Istream &)
Construct from Istream.
simpleMatrix (const simpleMatrix< Type > &)
Construct as copy.
Field< Type > & source ()
Return access to the source.
const Field< Type > & source () const
Return const-access to the source.
Field< Type > solve () const
Solve the matrix using Gaussian elimination with pivoting.
Field< Type > LUsolve () const
Solve the matrix using LU decomposition with pivoting.
void operator= (const simpleMatrix< Type > &)
Public Member Functions inherited from SquareMatrix< Type >
SquareMatrix ()
Null constructor.
SquareMatrix (const label n)
Construct given number of rows/columns.
SquareMatrix (const label m, const label n)
Construct given number of rows and columns,.
SquareMatrix (const label m, const label n, const Type &)
Construct with given number of rows and rows.
SquareMatrix (Istream &)
Construct from Istream.
autoPtr< SquareMatrix< Type > > clone () const
Clone.
Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label n, const label m)
Construct given number of rows and columns.
Matrix (const label n, const label m, const Type &)
Construct with given number of rows and columns.
Matrix (const Matrix< SquareMatrix< Type >, Type > &)
Copy constructor.
Matrix (Istream &)
Construct from Istream.
autoPtr< Matrix< SquareMatrix< Type >, Type > > clone () const
Clone.
~Matrix ()
Destructor.
label n () const
Return the number of rows.
label m () const
Return the number of columns.
label size () const
Return the number of elements in matrix (n*m)
void checki (const label i) const
Check index i is within valid range (0 ... n-1).
void checkj (const label j) const
Check index j is within valid range (0 ... m-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (Matrix< SquareMatrix< Type >, Type > &)
Transfer the contents of the argument Matrix into this Matrix.
SquareMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
void operator= (const Matrix< SquareMatrix< Type >, Type > &)
Assignment operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Friends
Ostream & operator (Ostream &, const simpleMatrix< Type > &)
Additional Inherited Members
Static Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
static const Matrix< SquareMatrix< Type >, Type > & null ()
Return a null Matrix.
Detailed Description
template<class Type>
class Foam::simpleMatrix< Type >
A simple square matrix solver with scalar coefficients.
Source files
simpleMatrix.H
simpleMatrix.C
Definition at line 47 of file simpleMatrix.H.
Constructor & Destructor Documentation
simpleMatrix (const label mSize)
Construct given size.
Note: this does not initialise the coefficients or the source.
Definition at line 31 of file simpleMatrix.C.
simpleMatrix (const label mSize, const scalar coeffVal, const Type & sourceVal)
Construct given size and initial values for coefficients and source.
Definition at line 40 of file simpleMatrix.C.
simpleMatrix (const scalarSquareMatrix & matrix, const Field< Type > & source)
Construct from components.
Definition at line 53 of file simpleMatrix.C.
simpleMatrix (Istream & is)
Construct from Istream.
Definition at line 64 of file simpleMatrix.C.
simpleMatrix (const simpleMatrix< Type > &)
Construct as copy.
Member Function Documentation
Field<Type>& source () inline
Return access to the source.
Definition at line 97 of file simpleMatrix.H.
Referenced by EulerImplicit< ChemistryModel >::solve().
const Field<Type>& source () const inline
Return const-access to the source.
Definition at line 103 of file simpleMatrix.H.
Foam::Field< Type > solve () const
Solve the matrix using Gaussian elimination with pivoting.
and return the solution
Definition at line 74 of file simpleMatrix.C.
References Foam::solve().
Foam::Field< Type > LUsolve () const
Solve the matrix using LU decomposition with pivoting.
and return the solution
Definition at line 86 of file simpleMatrix.C.
References Foam::LUsolve().
Referenced by EulerImplicit< ChemistryModel >::solve().
void operator= (const simpleMatrix< Type > & m)
Definition at line 100 of file simpleMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, n, Matrix< SquareMatrix< Type >, Type >::n(), and Matrix< SquareMatrix< scalar >, scalar >::operator=().
Friends And Related Function Documentation
Ostream& operator (Ostream & , const simpleMatrix< Type > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/simpleMatrix/simpleMatrix.H
src/OpenFOAM/matrices/simpleMatrix/simpleMatrix.C