OpenFOAM: setTimeStepFunctionObject Class Reference
setTimeStepFunctionObject Class Reference
FunctionObjects » Utility function objects
Overrides the timeStep. Can only be used with solvers with adjustTimeStep control (e.g. pimpleFoam). Makes no attempt to cooperate with other timeStep 'controllers' (maxCo, other functionObjects). Supports 'enabled' flag but none of othe other ones 'timeStart', 'timeEnd', 'writeControl' etc.
Public Member Functions
TypeName ("setTimeStep")
Runtime type information.
setTimeStepFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from components.
virtual ~setTimeStepFunctionObject ()
const Time & time () const
Return time database.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool read (const dictionary &)
Read and set the function object if its data have changed.
virtual bool execute ()
Called at each ++ or += of the time-loop.
virtual bool write ()
Called at each ++ or += of the time-loop.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Overrides the timeStep. Can only be used with solvers with adjustTimeStep control (e.g. pimpleFoam). Makes no attempt to cooperate with other timeStep 'controllers' (maxCo, other functionObjects). Supports 'enabled' flag but none of othe other ones 'timeStart', 'timeEnd', 'writeControl' etc.
Source files
setTimeStepFunctionObject.H
setTimeStepFunctionObject.C
Definition at line 58 of file setTimeStepFunctionObject.H.
Constructor & Destructor Documentation
setTimeStepFunctionObject (const word & name, const Time & runTime, const dictionary & dict)
Construct from components.
Definition at line 50 of file setTimeStepFunctionObject.C.
References Foam::read().
~setTimeStepFunctionObject () virtual
Definition at line 65 of file setTimeStepFunctionObject.C.
Member Function Documentation
TypeName ("setTimeStep")
Runtime type information.
const Foam::Time & time () const
Return time database.
Definition at line 72 of file setTimeStepFunctionObject.C.
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Reimplemented from functionObject.
Definition at line 78 of file setTimeStepFunctionObject.C.
References setTimeStepFunctionObject::read().
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Reimplemented from functionObject.
Definition at line 91 of file setTimeStepFunctionObject.C.
References controlDict(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Function1< Type >::New(), and dictionary::readIfPresent().
Referenced by setTimeStepFunctionObject::adjustTimeStep().
bool execute () virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual executeControl behaviour and forces execution (used in post-processing mode)
Implements functionObject.
Definition at line 116 of file setTimeStepFunctionObject.C.
bool write () virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual writeControl behaviour and forces writing always (used in post-processing mode)
Implements functionObject.
Definition at line 122 of file setTimeStepFunctionObject.C.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/setTimeStep/setTimeStepFunctionObject.H
src/functionObjects/utilities/setTimeStep/setTimeStepFunctionObject.C