OpenFOAM: seulex Class Reference
seulex Class Reference
An extrapolation-algorithm, based on the linearly implicit Euler method with step size control and order selection.
Public Member Functions
TypeName ("seulex")
Runtime type information.
seulex (const ODESystem &ode, const dictionary &dict)
Construct from ODESystem.
virtual ~seulex ()
Destructor.
virtual bool resize ()
Resize the ODE solver.
virtual void solve (scalar &x, scalarField &y, stepState &step) const
Solve the ODE system and the update the state.
Public Member Functions inherited from ODESolver
TypeName ("ODESolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
Construct for given ODESystem.
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
Construct for given ODESystem specifying tolerances.
virtual ~ODESolver ()
Destructor.
label nEqns () const
Return the number of equations to solve.
scalarField & absTol ()
Return access to the absolute tolerance field.
scalarField & relTol ()
Return access to the relative tolerance field.
template<class Type >
void resizeField (UList< Type > &f) const
void resizeMatrix (scalarSquareMatrix &m) const
virtual void solve (scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system as far as possible upto dxTry.
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Solve the ODE system from xStart to xEnd, update the state.
Additional Inherited Members
Static Public Member Functions inherited from ODESolver
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
Select null constructed.
template<class Type >
static void resizeField (UList< Type > &f, const label n)
Protected Member Functions inherited from ODESolver
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
Return the nomalized scalar error.
ODESolver (const ODESolver &)
Disallow default bitwise copy construct.
void operator= (const ODESolver &)
Disallow default bitwise assignment.
Protected Attributes inherited from ODESolver
const ODESystem & odes_
Reference to ODESystem.
const label maxN_
Maximum size of the ODESystem.
label n_
Size of the ODESystem (adjustable)
scalarField absTol_
Absolute convergence tolerance per step.
scalarField relTol_
Relative convergence tolerance per step.
label maxSteps_
The maximum number of sub-steps allowed for the integration step.
Detailed Description
An extrapolation-algorithm, based on the linearly implicit Euler method with step size control and order selection.
Reference:
    Hairer, E., Nørsett, S. P., & Wanner, G. (1996).
    Solving Ordinary Differential Equations II:
    Stiff and Differential-Algebraic Problems, second edition",
    Springer-Verlag, Berlin.
Source files
seulex.H
seulex.C
Definition at line 59 of file seulex.H.
Constructor & Destructor Documentation
seulex (const ODESystem & ode, const dictionary & dict)
Construct from ODESystem.
Definition at line 50 of file seulex.C.
References ODESystem::derivatives(), k, Foam::LUBacksubstitute(), Foam::LUDecompose(), Foam::mag(), Foam::min(), ODESolver::n_, ODESolver::odes_, Foam::sqr(), Foam::sqrt(), y, and Foam::y0().
virtual ~seulex () inline virtual
Destructor.
Definition at line 138 of file seulex.H.
References seulex::resize(), seulex::solve(), and x.
Member Function Documentation
TypeName ("seulex")
Runtime type information.
bool resize () virtual
Resize the ODE solver.
Implements ODESolver.
Definition at line 214 of file seulex.C.
References ODESolver::n_, ODESolver::resize(), ODESolver::resizeField(), ODESolver::resizeMatrix(), Matrix< Form, Type >::shallowResize(), and seulex::solve().
Referenced by seulex::~seulex().
void solve (scalar & x, scalarField & y, stepState & step) const virtual
Solve the ODE system and the update the state.
Reimplemented from ODESolver.
Definition at line 240 of file seulex.C.
References ODESolver::absTol_, ODESolver::stepState::dxDid, ODESolver::stepState::dxTry, Foam::endl(), ODESolver::stepState::first, forAll, ODESolver::stepState::forward, ODESystem::jacobian(), k, ODESolver::stepState::last, Foam::log10(), Foam::mag(), Foam::max(), Foam::min(), ODESolver::n_, ODESolver::odes_, Foam::pow(), ODESolver::stepState::prevReject, ODESolver::stepState::reject, ODESolver::relTol_, Foam::sqr(), Foam::sqrt(), success, WarningInFunction, and y.
Referenced by seulex::resize(), and seulex::~seulex().
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/seulex/seulex.H
src/ODE/ODESolvers/seulex/seulex.C