OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SpalartAllmarasDES< BasicTurbulenceModel > Class Template Reference
SpalartAllmarasDES DES turbulence model for incompressible and compressible flows.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel >::alphaField alphaField
typedef LESModel< BasicTurbulenceModel >::rhoField rhoField
typedef LESModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel >::alphaField alphaField
typedef LESModel< BasicTurbulenceModel >::rhoField rhoField
typedef LESModel< BasicTurbulenceModel >::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SpalartAllmarasDES")
Runtime type information.
SpalartAllmarasDES (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~SpalartAllmarasDES ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
virtual tmp< volScalarField > k () const
Return SGS kinetic energy.
tmp< volScalarField > nuTilda () const
virtual tmp< volScalarField > LESRegion () const
Return the LES field indicator.
virtual void correct ()
Correct nuTilda and related properties.
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~LESeddyViscosity ()
Destructor.
virtual tmp< volScalarField > epsilon () const
Return sub-grid disipation rate.
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > S (const volTensorField &gradU) const
tmp< volScalarField > Omega (const volTensorField &gradU) const
tmp< volScalarField > Stilda (const volScalarField &chi, const volScalarField &fv1, const volScalarField &Omega, const volScalarField &dTilda) const
tmp< volScalarField > r (const volScalarField &nur, const volScalarField &Omega, const volScalarField &dTilda) const
tmp< volScalarField > fw (const volScalarField &Omega, const volScalarField &dTilda) const
virtual tmp< volScalarField > dTilda (const volScalarField &chi, const volScalarField &fv1, const volTensorField &gradU) const
Length scale.
void correctNut (const volScalarField &fv1)
virtual void correctNut ()
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar sigmaNut_
dimensionedScalar kappa_
dimensionedScalar Cb1_
dimensionedScalar Cb2_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar Cv1_
dimensionedScalar Cs_
dimensionedScalar CDES_
dimensionedScalar ck_
volScalarField nuTilda_
const volScalarField & y_
Wall distance.
Protected Attributes inherited from LESeddyViscosity< BasicTurbulenceModel >
dimensionedScalar Ce_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::SpalartAllmarasDES< BasicTurbulenceModel >
SpalartAllmarasDES DES turbulence model for incompressible and compressible flows.
Reference:
    Spalart, P. R., Jou, W. H., Strelets, M., & Allmaras, S. R. (1997).
    Comments on the feasibility of LES for wings, and on a hybrid
    RANS/LES approach.
    Advances in DNS/LES, 1, 4-8.
Source files
SpalartAllmarasDES.H
SpalartAllmarasDES.C
Definition at line 63 of file SpalartAllmarasDES.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 154 of file SpalartAllmarasDES.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 155 of file SpalartAllmarasDES.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 156 of file SpalartAllmarasDES.H.
Constructor & Destructor Documentation
SpalartAllmarasDES (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 191 of file SpalartAllmarasDES.C.
virtual ~SpalartAllmarasDES () inline virtual
Destructor.
Definition at line 180 of file SpalartAllmarasDES.H.
References SpalartAllmarasDES< BasicTurbulenceModel >::DnuTildaEff(), SpalartAllmarasDES< BasicTurbulenceModel >::k(), and SpalartAllmarasDES< BasicTurbulenceModel >::read().
Member Function Documentation
tmp< volScalarField > chi () const protected
Definition at line 39 of file SpalartAllmarasDES.C.
References SpalartAllmarasDES< BasicTurbulenceModel >::fv1(), and nu.
tmp< volScalarField > fv1 (const volScalarField & chi) const protected
Definition at line 47 of file SpalartAllmarasDES.C.
References SpalartAllmarasDES< BasicTurbulenceModel >::fv2(), and Foam::pow3().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::chi().
tmp< volScalarField > fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 58 of file SpalartAllmarasDES.C.
References SpalartAllmarasDES< BasicTurbulenceModel >::S().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::fv1().
tmp< volScalarField > S (const volTensorField & gradU) const protected
Definition at line 69 of file SpalartAllmarasDES.C.
References Foam::mag(), SpalartAllmarasDES< BasicTurbulenceModel >::Omega(), Foam::sqrt(), and Foam::symm().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::fv2().
tmp< volScalarField > Omega (const volTensorField & gradU) const protected
Definition at line 79 of file SpalartAllmarasDES.C.
References Foam::mag(), Foam::skew(), Foam::sqrt(), and SpalartAllmarasDES< BasicTurbulenceModel >::Stilda().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::S().
tmp< volScalarField > Stilda (const volScalarField & chi, const volScalarField & fv1, const volScalarField & Omega, const volScalarField & dTilda) const protected
Definition at line 89 of file SpalartAllmarasDES.C.
References Foam::max(), SpalartAllmarasDES< BasicTurbulenceModel >::r(), and Foam::sqr().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::Omega().
tmp< volScalarField > r (const volScalarField & nur, const volScalarField & Omega, const volScalarField & dTilda) const protected
Definition at line 110 of file SpalartAllmarasDES.C.
References DimensionedField< Type, GeoMesh >::dimensions(), SpalartAllmarasDES< BasicTurbulenceModel >::fw(), Foam::max(), Foam::min(), Foam::sqr(), and Foam::tr().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::Stilda().
tmp< volScalarField > fw (const volScalarField & Omega, const volScalarField & dTilda) const protected
Definition at line 140 of file SpalartAllmarasDES.C.
References SpalartAllmarasDES< BasicTurbulenceModel >::dTilda(), g, Foam::pow(), and Foam::pow6().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::r().
tmp< volScalarField > dTilda (const volScalarField & chi, const volScalarField & fv1, const volTensorField & gradU) const protected virtual
Length scale.
Reimplemented in SpalartAllmarasIDDES< BasicTurbulenceModel >, and SpalartAllmarasDDES< BasicTurbulenceModel >.
Definition at line 154 of file SpalartAllmarasDES.C.
References SpalartAllmarasDES< BasicTurbulenceModel >::correctNut(), delta, dimensionedInternalField(), and Foam::min().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::fw().
void correctNut (const volScalarField & fv1) protected
Definition at line 168 of file SpalartAllmarasDES.C.
References optionList::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), and options::New().
void correctNut () protected virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 181 of file SpalartAllmarasDES.C.
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::dTilda().
TypeName ("SpalartAllmarasDES< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Reimplemented in SpalartAllmarasIDDES< BasicTurbulenceModel >.
Definition at line 331 of file SpalartAllmarasDES.C.
References SpalartAllmarasDES< BasicTurbulenceModel >::DnuTildaEff(), dimensioned< Type >::readIfPresent(), and Foam::sqr().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::~SpalartAllmarasDES().
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
Definition at line 360 of file SpalartAllmarasDES.C.
References nu.
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::read(), and SpalartAllmarasDES< BasicTurbulenceModel >::~SpalartAllmarasDES().
tmp< volScalarField > k () const virtual
Return SGS kinetic energy.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 370 of file SpalartAllmarasDES.C.
References Foam::fvc::grad(), nut, and Foam::sqr().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::~SpalartAllmarasDES().
tmp<volScalarField> nuTilda () const inline
Definition at line 195 of file SpalartAllmarasDES.H.
References SpalartAllmarasDES< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), and SpalartAllmarasDES< BasicTurbulenceModel >::nuTilda_.
tmp< volScalarField > LESRegion () const virtual
Return the LES field indicator.
Definition at line 379 of file SpalartAllmarasDES.C.
References Foam::fvc::grad(), Foam::neg(), IOobject::NO_READ, and IOobject::NO_WRITE.
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::nuTilda().
void correct () virtual
Correct nuTilda and related properties.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 405 of file SpalartAllmarasDES.C.
References Foam::bound(), optionList::constrain(), eddyViscosity< LESModel< BasicTurbulenceModel > >::correct(), optionList::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvm::ddt(), Foam::fvm::div(), fvOptions, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), options::New(), Foam::solve(), Foam::fvm::Sp(), and Foam::sqr().
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::nuTilda().
Member Data Documentation
dimensionedScalar sigmaNut_ protected
Definition at line 80 of file SpalartAllmarasDES.H.
dimensionedScalar kappa_ protected
Definition at line 81 of file SpalartAllmarasDES.H.
dimensionedScalar Cb1_ protected
Definition at line 83 of file SpalartAllmarasDES.H.
dimensionedScalar Cb2_ protected
Definition at line 84 of file SpalartAllmarasDES.H.
dimensionedScalar Cw1_ protected
Definition at line 85 of file SpalartAllmarasDES.H.
dimensionedScalar Cw2_ protected
Definition at line 86 of file SpalartAllmarasDES.H.
dimensionedScalar Cw3_ protected
Definition at line 87 of file SpalartAllmarasDES.H.
dimensionedScalar Cv1_ protected
Definition at line 88 of file SpalartAllmarasDES.H.
dimensionedScalar Cs_ protected
Definition at line 89 of file SpalartAllmarasDES.H.
dimensionedScalar CDES_ protected
Definition at line 90 of file SpalartAllmarasDES.H.
dimensionedScalar ck_ protected
Definition at line 91 of file SpalartAllmarasDES.H.
volScalarField nuTilda_ protected
Definition at line 95 of file SpalartAllmarasDES.H.
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::nuTilda().
const volScalarField& y_ protected
Wall distance.
Note: different to wall distance in parent RASModel which is for near-wall cells only
Definition at line 100 of file SpalartAllmarasDES.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/SpalartAllmarasDES/SpalartAllmarasDES.H
src/TurbulenceModels/turbulenceModels/LES/SpalartAllmarasDES/SpalartAllmarasDES.C