OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Reaction< ReactionThermo >::specieCoeffs Struct Reference
Class to hold the specie index and its coefficients in the.
Public Member Functions
specieCoeffs ()
specieCoeffs (const speciesTable &species, Istream &is)
bool operator== (const specieCoeffs &sc) const
bool operator!= (const specieCoeffs &sc) const
Public Attributes
label index
scalar stoichCoeff
scalar exponent
Friends
Ostream & operator<< (Ostream &os, const specieCoeffs &sc)
Detailed Description
template<class ReactionThermo>
struct Foam::Reaction< ReactionThermo >::specieCoeffs
Class to hold the specie index and its coefficients in the.
reaction rate expression
Definition at line 91 of file Reaction.H.
Constructor & Destructor Documentation
specieCoeffs () inline
Definition at line 97 of file Reaction.H.
specieCoeffs (const speciesTable & species, Istream & is)
Definition at line 179 of file Reaction.C.
References hashedWordList::contains(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, i, token::info(), token::isNumber(), token::isWord(), token::number(), and token::wordToken().
Member Function Documentation
bool operator== (const specieCoeffs & sc) const inline
Definition at line 106 of file Reaction.H.
References Reaction< ReactionThermo >::specieCoeffs::index.
bool operator!= (const specieCoeffs & sc) const inline
Definition at line 111 of file Reaction.H.
References Reaction< ReactionThermo >::specieCoeffs::index.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const specieCoeffs & sc) friend
Definition at line 116 of file Reaction.H.
Member Data Documentation
label index
Definition at line 93 of file Reaction.H.
Referenced by Reaction< ReactionThermo >::specieCoeffs::operator!=(), and Reaction< ReactionThermo >::specieCoeffs::operator==().
scalar stoichCoeff
Definition at line 94 of file Reaction.H.
scalar exponent
Definition at line 95 of file Reaction.H.
The documentation for this struct was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.H
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.C