OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sampledSurfaces Class Reference
Set of surfaces to sample.
Public Member Functions
TypeName ("surfaces")
Runtime type information.
sampledSurfaces (const word &name, const Time &time, const dictionary &dict)
Construct from Time and dictionary.
sampledSurfaces (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~sampledSurfaces ()
Destructor.
virtual bool needsUpdate () const
Does any of the surfaces need an update?
virtual bool expire ()
Mark the surfaces as needing an update.
virtual bool update ()
Update the surfaces as required and merge surface points (parallel).
void verbose (const bool verbosity=true)
Set verbosity level.
virtual bool read (const dictionary &)
Read the sampledSurfaces dictionary.
virtual bool execute ()
Execute, currently does nothing.
virtual bool write ()
Sample and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh - expires the surfaces.
virtual void movePoints (const polyMesh &)
Update for mesh point-motion - expires the surfaces.
virtual void readUpdate (const polyMesh::readUpdateState state)
Update for changes of mesh due to readUpdate - expires the surfaces.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Public Member Functions inherited from PtrList< sampledSurface >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< sampledSurface > &)
Copy constructor.
PtrList (const PtrList< sampledSurface > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< sampledSurface >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< sampledSurface > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< sampledSurface > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (sampledSurface *)
Append an element at the end of the list.
void append (const autoPtr< sampledSurface > &)
void append (const tmp< sampledSurface > &)
void transfer (PtrList< sampledSurface > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< sampledSurface > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< sampledSurface > set (const label, sampledSurface *)
Set element to given T* and return old element (can be NULL)
autoPtr< sampledSurface > set (const label, const autoPtr< sampledSurface > &)
Set element to given autoPtr<T> and return old element.
autoPtr< sampledSurface > set (const label, const tmp< sampledSurface > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< sampledSurface > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Protected Member Functions inherited from PtrList< sampledSurface >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Set of surfaces to sample.
The write() method is used to sample and write files.
Source files
sampledSurfaces.H
sampledSurfaces.C
Definition at line 61 of file sampledSurfaces.H.
Constructor & Destructor Documentation
sampledSurfaces (const word & name, const Time & time, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 97 of file sampledSurfaces.C.
References Foam::name(), UPstream::parRun(), and Foam::read().
sampledSurfaces (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
allow the possibility to load fields from files
Definition at line 136 of file sampledSurfaces.C.
References Foam::name(), UPstream::parRun(), and Foam::read().
~sampledSurfaces () virtual
Destructor.
Definition at line 168 of file sampledSurfaces.C.
Member Function Documentation
TypeName ("surfaces")
Runtime type information.
bool needsUpdate () const virtual
Does any of the surfaces need an update?
Definition at line 323 of file sampledSurfaces.C.
References forAll.
bool expire () virtual
Mark the surfaces as needing an update.
May also free up unneeded data. Return false if all surfaces were already marked as expired.
Definition at line 337 of file sampledSurfaces.C.
References forAll, and UPstream::parRun().
bool update () virtual
Update the surfaces as required and merge surface points (parallel).
Return false if no surfaces required an update.
Definition at line 360 of file sampledSurfaces.C.
References Foam::endl(), sampledSurface::faces(), forAll, PatchTools::gatherAndMerge(), UPstream::master(), Foam::nl, UPstream::parRun(), points, sampledSurface::points(), Foam::Pout, List< T >::size(), and sampledSurface::update().
void verbose (const bool verbosity = true)
Set verbosity level.
Definition at line 174 of file sampledSurfaces.C.
bool read (const dictionary & dict) virtual
Read the sampledSurfaces dictionary.
Reimplemented from functionObject.
Definition at line 233 of file sampledSurfaces.C.
References Foam::endl(), forAll, dictionary::found(), Foam::Info, dictionary::lookup(), UPstream::master(), surfaceWriter::New(), Foam::nl, UPstream::parRun(), Foam::Pout, and dictionary::subOrEmptyDict().
bool execute () virtual
Execute, currently does nothing.
Implements functionObject.
Definition at line 180 of file sampledSurfaces.C.
bool write () virtual
Sample and write.
Implements functionObject.
Definition at line 186 of file sampledSurfaces.C.
References Foam::endl(), UPstream::master(), Foam::mkDir(), Foam::nl, and Foam::Pout.
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh - expires the surfaces.
Reimplemented from functionObject.
Definition at line 294 of file sampledSurfaces.C.
References mapPolyMesh::mesh().
void movePoints (const polyMesh & mesh) virtual
Update for mesh point-motion - expires the surfaces.
Reimplemented from functionObject.
Definition at line 305 of file sampledSurfaces.C.
void readUpdate (const polyMesh::readUpdateState state) virtual
Update for changes of mesh due to readUpdate - expires the surfaces.
Definition at line 314 of file sampledSurfaces.C.
References polyMesh::UNCHANGED.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledSurfaces/sampledSurfaces.H
src/sampling/sampledSurface/sampledSurfaces/sampledSurfaces.C
src/sampling/sampledSurface/sampledSurfaces/sampledSurfacesGrouping.C
src/sampling/sampledSurface/sampledSurfaces/sampledSurfacesTemplates.C