OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SIBS Class Reference
Foam::SIBS.
Public Member Functions
TypeName ("SIBS")
Runtime type information.
SIBS (const ODESystem &ode, const dictionary &dict)
Construct from ODE.
void solve (scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system as far as possible upto dxTry.
Public Member Functions inherited from ODESolver
TypeName ("ODESolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
Construct for given ODESystem.
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
Construct for given ODESystem specifying tolerances.
virtual ~ODESolver ()
Destructor.
scalarField & absTol ()
scalarField & relTol ()
virtual void solve (scalar &x, scalarField &y, stepState &step) const
Solve the ODE system as far as possible upto dxTry.
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Solve the ODE system from xStart to xEnd, update the state.
Additional Inherited Members
Static Public Member Functions inherited from ODESolver
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
Select null constructed.
Protected Member Functions inherited from ODESolver
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
Return the nomalized scalar error.
ODESolver (const ODESolver &)
Disallow default bitwise copy construct.
void operator= (const ODESolver &)
Disallow default bitwise assignment.
Protected Attributes inherited from ODESolver
const ODESystem & odes_
Reference to ODESystem.
label n_
Size of the ODESystem.
scalarField absTol_
Absolute convergence tolerance per step.
scalarField relTol_
Relative convergence tolerance per step.
label maxSteps_
The maximum number of sub-steps allowed for the integration step.
Detailed Description
Foam::SIBS.
Bader, G. and Deuflhard, P. "A Semi-Implicit Mid-Point Rule for Stiff Systems of Ordinary Differential Equations." Numer. Math. 41, 373-398, 1983.
Source files
SIBS.H
SIMPR.C
polyExtrapolate.C
Definition at line 54 of file SIBS.H.
Constructor & Destructor Documentation
SIBS (const ODESystem & ode, const dictionary & dict)
Construct from ODE.
Definition at line 49 of file SIBS.C.
References SIBS::solve().
Member Function Documentation
TypeName ("SIBS")
Runtime type information.
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Solve the ODE system as far as possible upto dxTry.
adjusting the step as necessary to provide a solution within the specified tolerance. Update the state and return an estimate for the next step in dxTry
Reimplemented from ODESolver.
Definition at line 72 of file SIBS.C.
References ODESolver::absTol_, ODESystem::derivatives(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::constant::universal::h, ODESystem::jacobian(), k, Foam::mag(), Foam::max(), Foam::min(), ODESolver::n_, ODESolver::odes_, Foam::pow(), ODESolver::relTol_, Foam::sqr(), and y.
Referenced by SIBS::SIBS().
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/SIBS/SIBS.H
src/ODE/ODESolvers/SIBS/polyExtrapolate.C
src/ODE/ODESolvers/SIBS/SIBS.C
src/ODE/ODESolvers/SIBS/SIMPR.C