OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
scalarTransport Class Reference
FunctionObjects » Utility function objects
This function object evolves a passive scalar transport equation. The field in ininitially zero, to which sources are added. The field name is assigned the name of the function object. Boundary conditions are automatically applied, based on the velocity boundary conditions.
Public Member Functions
TypeName ("scalarTransport")
Runtime type information.
scalarTransport (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~scalarTransport ()
Destructor.
virtual const word & name () const
Return name of the set of scalarTransport.
virtual void read (const dictionary &)
Read the scalarTransport data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the scalarTransport and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Detailed Description
This function object evolves a passive scalar transport equation. The field in ininitially zero, to which sources are added. The field name is assigned the name of the function object. Boundary conditions are automatically applied, based on the velocity boundary conditions.
- the field can be zeroed on start-up using the resetOnStartUp flag
to employ the same numerical schemes as the flow velocity, use the autoSchemes flag
the diffusivity can be set manually using the DT entry, or retrieved from the turbulence model (if applicable)
Source files
scalarTransport.H
scalarTransport.C
Definition at line 72 of file scalarTransport.H.
Constructor & Destructor Documentation
scalarTransport (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 146 of file scalarTransport.C.
References Foam::dimless, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::read().
~scalarTransport () virtual
Destructor.
Definition at line 196 of file scalarTransport.C.
Member Function Documentation
TypeName ("scalarTransport")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the set of scalarTransport.
Definition at line 154 of file scalarTransport.H.
References scalarTransport::end(), scalarTransport::execute(), scalarTransport::read(), scalarTransport::timeSet(), and scalarTransport::write().
void read (const dictionary & dict) virtual
Read the scalarTransport data.
Definition at line 202 of file scalarTransport.C.
References Foam::Info, dictionary::lookup(), dictionary::lookupOrDefault(), Foam::nl, dictionary::readIfPresent(), dictionary::subDict(), and Foam::type().
Referenced by scalarTransport::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 226 of file scalarTransport.C.
References Foam::fvm::ddt(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimMass, Foam::dimTime, Foam::dimVolume, Foam::fvm::div(), Foam::endl(), FatalErrorInFunction, Foam::Info, Foam::fvm::laplacian(), Foam::nl, fvMatrix< Type >::relax(), rho, fvMatrix< Type >::solve(), TEqn(), and Foam::type().
Referenced by scalarTransport::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 310 of file scalarTransport.C.
Referenced by scalarTransport::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 316 of file scalarTransport.C.
Referenced by scalarTransport::name().
void write () virtual
Calculate the scalarTransport and write.
Definition at line 320 of file scalarTransport.C.
Referenced by scalarTransport::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 175 of file scalarTransport.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 179 of file scalarTransport.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/scalarTransport/scalarTransport.H
src/postProcessing/functionObjects/utilities/scalarTransport/scalarTransport.C