OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sigInt Class Reference
Signal handler for INT interupt.
Public Member Functions
sigInt ()
Construct null.
~sigInt ()
Destructor.
void set (const bool verbose)
Activate SIGINT signal handler.
Detailed Description
Signal handler for INT interupt.
The standard interupt handler is overridden to ensure that the runningJob file is removed.
See also
Foam::JobInfo
Source files
sigInt.H
sigInt.C
Definition at line 54 of file sigInt.H.
Constructor & Destructor Documentation
sigInt ()
Construct null.
Definition at line 58 of file sigInt.C.
~sigInt ()
Destructor.
Definition at line 66 of file sigInt.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Member Function Documentation
void set (const bool verbose)
Activate SIGINT signal handler.
Definition at line 80 of file sigInt.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by argList::parse().
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigInt.H
src/OSspecific/POSIX/signals/sigInt.C