OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setTimeStepFunctionObject Class Reference
FunctionObjects » Utility function objects
Overrides the timeStep. Can only be used with solvers with adjustTimeStep control (e.g. pimpleFoam). Makes no attempt to cooperate with other timeStep 'controllers' (maxCo, other functionObjects). Supports 'enabled' flag but none of othe other ones 'timeStart', 'timeEnd', 'outputControl' etc.
Public Member Functions
TypeName ("setTimeStep")
Runtime type information.
setTimeStepFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from components.
virtual const Time & time () const
Return time database.
virtual bool enabled () const
Return the enabled flag.
virtual void on ()
Switch the function object on.
virtual void off ()
Switch the function object off.
virtual bool start ()
Called at the start of the time-loop.
virtual bool execute (const bool forceWrite)
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool read (const dictionary &)
Read and set the function object if its data have changed.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
virtual const word & name () const
Name.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
Overrides the timeStep. Can only be used with solvers with adjustTimeStep control (e.g. pimpleFoam). Makes no attempt to cooperate with other timeStep 'controllers' (maxCo, other functionObjects). Supports 'enabled' flag but none of othe other ones 'timeStart', 'timeEnd', 'outputControl' etc.
Source files
setTimeStepFunctionObject.H
setTimeStepFunctionObject.C
Definition at line 59 of file setTimeStepFunctionObject.H.
Constructor & Destructor Documentation
setTimeStepFunctionObject (const word & name, const Time & runTime, const dictionary & dict)
Construct from components.
Definition at line 50 of file setTimeStepFunctionObject.C.
References Foam::read().
Member Function Documentation
TypeName ("setTimeStep")
Runtime type information.
virtual const Time& time () const inline virtual
Return time database.
Definition at line 105 of file setTimeStepFunctionObject.H.
virtual bool enabled () const inline virtual
Return the enabled flag.
Definition at line 111 of file setTimeStepFunctionObject.H.
References setTimeStepFunctionObject::adjustTimeStep(), setTimeStepFunctionObject::end(), setTimeStepFunctionObject::execute(), mesh, setTimeStepFunctionObject::movePoints(), setTimeStepFunctionObject::off(), setTimeStepFunctionObject::on(), setTimeStepFunctionObject::read(), setTimeStepFunctionObject::start(), setTimeStepFunctionObject::timeSet(), and setTimeStepFunctionObject::updateMesh().
void on () virtual
Switch the function object on.
Definition at line 66 of file setTimeStepFunctionObject.C.
Referenced by setTimeStepFunctionObject::enabled().
void off () virtual
Switch the function object off.
Definition at line 72 of file setTimeStepFunctionObject.C.
Referenced by setTimeStepFunctionObject::enabled().
bool start () virtual
Called at the start of the time-loop.
Implements functionObject.
Definition at line 78 of file setTimeStepFunctionObject.C.
References setTimeStepFunctionObject::execute().
Referenced by setTimeStepFunctionObject::enabled().
bool execute (const bool forceWrite) virtual
Called at each ++ or += of the time-loop.
Implements functionObject.
Definition at line 85 of file setTimeStepFunctionObject.C.
Referenced by setTimeStepFunctionObject::enabled(), and setTimeStepFunctionObject::start().
bool end () virtual
Called when Time::run() determines that the time-loop exits.
Reimplemented from functionObject.
Definition at line 93 of file setTimeStepFunctionObject.C.
Referenced by setTimeStepFunctionObject::enabled().
bool timeSet () virtual
Called when time was set at the end of the Time::operator++.
Reimplemented from functionObject.
Definition at line 99 of file setTimeStepFunctionObject.C.
Referenced by setTimeStepFunctionObject::enabled().
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Reimplemented from functionObject.
Definition at line 105 of file setTimeStepFunctionObject.C.
References setTimeStepFunctionObject::read().
Referenced by setTimeStepFunctionObject::enabled().
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Implements functionObject.
Definition at line 124 of file setTimeStepFunctionObject.C.
References controlDict(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::lookupOrDefault(), Function1< Type >::New(), dictionary::readIfPresent(), and setTimeStepFunctionObject::updateMesh().
Referenced by setTimeStepFunctionObject::adjustTimeStep(), and setTimeStepFunctionObject::enabled().
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Implements functionObject.
Definition at line 154 of file setTimeStepFunctionObject.C.
References setTimeStepFunctionObject::movePoints().
Referenced by setTimeStepFunctionObject::enabled(), and setTimeStepFunctionObject::read().
void movePoints (const polyMesh & mesh) virtual
Update for changes of mesh.
Implements functionObject.
Definition at line 161 of file setTimeStepFunctionObject.C.
Referenced by setTimeStepFunctionObject::enabled(), and setTimeStepFunctionObject::updateMesh().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/setTimeStep/setTimeStepFunctionObject.H
src/postProcessing/functionObjects/utilities/setTimeStep/setTimeStepFunctionObject.C