OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
STARCDCoordinateRotation Class Reference
A coordinateRotation defined by the STAR-CD convention.
Public Member Functions
TypeName ("STARCDRotation")
Runtime type information.
STARCDCoordinateRotation ()
Construct null.
STARCDCoordinateRotation (const vector &rotZrotXrotY, const bool inDegrees=true)
Construct from rotation vector.
STARCDCoordinateRotation (const scalar rotZ, const scalar rotX, const scalar rotY, const bool inDegrees=true)
Construct from components of rotation vector.
STARCDCoordinateRotation (const dictionary &)
Construct from dictionary.
STARCDCoordinateRotation (const dictionary &, const objectRegistry &)
Construct from dictionary and mesh.
virtual void clear ()
Reset rotation to an identity rotation.
virtual void updateCells (const polyMesh &, const labelList &)
Update the rotation for a list of cells.
virtual const tensor & R () const
Return local-to-global transformation tensor.
virtual const tensor & Rtr () const
Return global-to-local transformation tensor.
virtual const vector e1 () const
Return local Cartesian x-axis.
virtual const vector e2 () const
Return local Cartesian y-axis.
virtual const vector e3 () const
Return local Cartesian z-axis.
virtual const tensorField & Tr () const
Return transformation tensor field.
virtual tmp< vectorField > transform (const vectorField &st) const
Transform vectorField using transformation tensor field.
virtual vector transform (const vector &st) const
Transform vector using transformation tensor.
virtual tmp< vectorField > invTransform (const vectorField &st) const
Inverse transform vectorField using transformation tensor field.
virtual vector invTransform (const vector &st) const
Inverse transform vector using transformation tensor.
virtual tmp< tensorField > transformTensor (const tensorField &st) const
Transform tensor field using transformation tensorField.
virtual tensor transformTensor (const tensor &st) const
Transform tensor using transformation tensorField.
virtual tmp< tensorField > transformTensor (const tensorField &st, const labelList &cellMap) const
Transform tensor sub-field using transformation tensorField.
virtual tmp< symmTensorField > transformVector (const vectorField &st) const
Transform vectorField using transformation tensorField and return.
virtual symmTensor transformVector (const vector &st) const
Transform vector using transformation tensor and return.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from coordinateRotation
TypeName ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, coordinateRotation, objectRegistry,(const dictionary &dict, const objectRegistry &obr),(dict, obr))
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()
Destructor.
virtual bool uniform () const
Return true if the rotation tensor is uniform.
Additional Inherited Members
Static Public Member Functions inherited from coordinateRotation
static autoPtr
< coordinateRotation > New (const dictionary &dict, const objectRegistry &obr)
Select constructed from dictionary and objectRegistry.
static autoPtr
< coordinateRotation > New (const dictionary &dict)
Select constructed from dictionary.
Protected Member Functions inherited from coordinateRotation
symmTensor transformPrincipal (const tensor &, const vector &) const
Transform principal.
Detailed Description
A coordinateRotation defined by the STAR-CD convention.
The 3 rotations are defined in the STAR-CD convention (around Z, around X' and around Y''). The order of the parameter arguments matches this rotation order.
the rotation angles are in degrees, unless otherwise explictly specified:
    coordinateRotation
    {
        type        STARCDRotation;
        degrees     false;
        rotation    (0 0 3.141592654);
    }
Definition at line 60 of file STARCDCoordinateRotation.H.
Constructor & Destructor Documentation
STARCDCoordinateRotation ()
Construct null.
Definition at line 215 of file STARCDCoordinateRotation.C.
STARCDCoordinateRotation (const vector & rotZrotXrotY, const bool inDegrees = true)
Construct from rotation vector.
Definition at line 223 of file STARCDCoordinateRotation.C.
References VectorSpace< Form, Cmpt, nCmpt >::component(), Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
STARCDCoordinateRotation (const scalar rotZ, const scalar rotX, const scalar rotY, const bool inDegrees = true)
Construct from components of rotation vector.
Definition at line 242 of file STARCDCoordinateRotation.C.
STARCDCoordinateRotation (const dictionary & dict)
Construct from dictionary.
Definition at line 257 of file STARCDCoordinateRotation.C.
References dictionary::lookup(), dictionary::lookupOrDefault(), Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
STARCDCoordinateRotation (const dictionary & dict, const objectRegistry &)
Construct from dictionary and mesh.
Definition at line 277 of file STARCDCoordinateRotation.C.
References dictionary::lookup(), dictionary::lookupOrDefault(), Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
Member Function Documentation
TypeName ("STARCDRotation")
Runtime type information.
virtual void clear () inline virtual
Reset rotation to an identity rotation.
Implements coordinateRotation.
Definition at line 122 of file STARCDCoordinateRotation.H.
References SphericalTensor< Cmpt >::I.
virtual void updateCells (const polyMesh & , const labelList &) inline virtual
Update the rotation for a list of cells.
Implements coordinateRotation.
Definition at line 129 of file STARCDCoordinateRotation.H.
virtual const tensor& R () const inline virtual
Return local-to-global transformation tensor.
Implements coordinateRotation.
Definition at line 135 of file STARCDCoordinateRotation.H.
virtual const tensor& Rtr () const inline virtual
Return global-to-local transformation tensor.
Implements coordinateRotation.
Definition at line 141 of file STARCDCoordinateRotation.H.
virtual const vector e1 () const inline virtual
Return local Cartesian x-axis.
Implements coordinateRotation.
Definition at line 147 of file STARCDCoordinateRotation.H.
References Tensor< Cmpt >::x().
virtual const vector e2 () const inline virtual
Return local Cartesian y-axis.
Implements coordinateRotation.
Definition at line 153 of file STARCDCoordinateRotation.H.
References Tensor< Cmpt >::y().
virtual const vector e3 () const inline virtual
Return local Cartesian z-axis.
Implements coordinateRotation.
Definition at line 159 of file STARCDCoordinateRotation.H.
References Tensor< Cmpt >::z().
const Foam::tensorField & Tr () const virtual
Return transformation tensor field.
Implements coordinateRotation.
Definition at line 96 of file STARCDCoordinateRotation.C.
References notImplemented.
Foam::tmp< Foam::vectorField > transform (const vectorField & st) const virtual
Transform vectorField using transformation tensor field.
Implements coordinateRotation.
Definition at line 69 of file STARCDCoordinateRotation.C.
References notImplemented.
Foam::vector transform (const vector & st) const virtual
Transform vector using transformation tensor.
Implements coordinateRotation.
Definition at line 53 of file STARCDCoordinateRotation.C.
Foam::tmp< Foam::vectorField > invTransform (const vectorField & st) const virtual
Inverse transform vectorField using transformation tensor field.
Implements coordinateRotation.
Definition at line 83 of file STARCDCoordinateRotation.C.
References notImplemented.
Foam::vector invTransform (const vector & st) const virtual
Inverse transform vector using transformation tensor.
Implements coordinateRotation.
Definition at line 60 of file STARCDCoordinateRotation.C.
Foam::tmp< Foam::tensorField > transformTensor (const tensorField & st) const virtual
Transform tensor field using transformation tensorField.
Implements coordinateRotation.
Definition at line 107 of file STARCDCoordinateRotation.C.
References notImplemented.
Foam::tensor transformTensor (const tensor & st) const virtual
Transform tensor using transformation tensorField.
Implements coordinateRotation.
Definition at line 120 of file STARCDCoordinateRotation.C.
Foam::tmp< Foam::tensorField > transformTensor (const tensorField & st, const labelList & cellMap) const virtual
Transform tensor sub-field using transformation tensorField.
Implements coordinateRotation.
Definition at line 129 of file STARCDCoordinateRotation.C.
References notImplemented.
Foam::tmp< Foam::symmTensorField > transformVector (const vectorField & st) const virtual
Transform vectorField using transformation tensorField and return.
symmetrical tensorField
Implements coordinateRotation.
Definition at line 147 of file STARCDCoordinateRotation.C.
References fld(), forAll, i, and List< T >::size().
Foam::symmTensor transformVector (const vector & st) const virtual
Transform vector using transformation tensor and return.
symmetrical tensor
Implements coordinateRotation.
Definition at line 163 of file STARCDCoordinateRotation.C.
void write (Ostream & os) const virtual
Write.
Implements coordinateRotation.
Definition at line 294 of file STARCDCoordinateRotation.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/coordinateRotation/STARCDCoordinateRotation.H
src/meshTools/coordinateSystems/coordinateRotation/STARCDCoordinateRotation.C