OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
streamLine Class Reference
Field function objects
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field.
Public Member Functions
TypeName ("streamLine")
Runtime type information.
streamLine (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~streamLine ()
Destructor.
virtual const word & name () const
Return name of the set of field averages.
virtual void read (const dictionary &)
Read the field average data.
virtual void execute ()
Execute the averaging.
virtual void end ()
Execute the averaging at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the field average data and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for mesh point-motion.
Detailed Description
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field.
Example of function object specification:
streamLine1
{
    type            streamLine;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    setFormat       vtk;
    UName           U;
    trackForward    yes;
    fields
    (
        U
        p
    );
    lifeTime        10000;
    trackLength     1e-3;
    nSubCycle       5;
    cloudName       particleTracks;
    seedSampleSet   uniform;
    uniformCoeffs
    {
        type        uniform;
        axis        x;  //distance;
        start       (-0.0205 0.0001 0.00001);
        end         (-0.0205 0.0005 0.00001);
        nPoints     100;
    }
}
Function object usage
Property Description Required Default value
type type name: streamLine yes
setFormat output data type yes
UName tracking velocity field name yes
fields fields to sample yes
lifetime maximum number of particle tracking steps yes
trackLength tracking segment length no
nSubCycle number of tracking steps per cell no
cloudName cloud name to use yes
seedSampleSet seeding method (see below) yes
Where seedSampleSet is typically one of
uniform : uniform particle seeding
cloud : cloud of points
triSurfaceMeshPointSet : points according to a tri-surface mesh
Note
When specifying the track resolution, the trackLength OR nSubCycle option should be used
See Also
Foam::functionObject Foam::OutputFilterFunctionObject Foam::sampledSet Foam::wallBoundedStreamLine
Source files
streamLine.H
streamLine.C
Definition at line 193 of file streamLine.H.
Constructor & Destructor Documentation
streamLine (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 326 of file streamLine.C.
References Foam::endl(), Foam::nl, Foam::read(), and WarningIn.
~streamLine () virtual
Destructor.
Definition at line 365 of file streamLine.C.
Member Function Documentation
TypeName ("streamLine")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the set of field averages.
Definition at line 316 of file streamLine.H.
void read (const dictionary & dict) virtual
Read the field average data.
Definition at line 371 of file streamLine.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::FatalIOError, FatalIOErrorIn, Foam::findIndex(), dictionary::found(), Foam::Info, IOWarningIn, dictionary::lookup(), dictionary::lookupOrDefault(), writer< Type >::New(), sampledSet::New(), Foam::nl, dictionary::readIfPresent(), primitiveMesh::reset(), dictionary::subDict(), and Foam::type().
void execute () virtual
Execute the averaging.
Definition at line 480 of file streamLine.C.
void end () virtual
Execute the averaging at the final time-loop, currently does nothing.
Definition at line 516 of file streamLine.C.
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 520 of file streamLine.C.
void write () virtual
Calculate the field average data and write.
Definition at line 524 of file streamLine.C.
References polyMesh::defaultRegion, mapDistribute::distribute(), Foam::endl(), forAll, i, Foam::Info, UPstream::master(), Foam::mkDir(), n, Foam::name(), fvMesh::name(), Foam::nl, UPstream::nProcs(), UPstream::parRun(), fileName::path(), Time::path(), UPstream::scheduled, DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::setSize(), List< T >::size(), objectRegistry::time(), fvMesh::time(), Time::timeName(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer(), Foam::type(), Ostream::write(), and List< T >::xfer().
void updateMesh (const mapPolyMesh &) virtual
Update for changes of mesh.
Definition at line 757 of file streamLine.C.
References Foam::read().
void movePoints (const polyMesh &) virtual
Update for mesh point-motion.
Definition at line 763 of file streamLine.C.
References Foam::read().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/streamLine/streamLine.H
src/postProcessing/functionObjects/field/streamLine/streamLine.C