OpenFOAM: SIBS Class Reference
SIBS Class Reference
A semi-implicit mid-point solver for stiff systems of ordinary differential equations.
Public Member Functions
TypeName ("SIBS")
Runtime type information.
SIBS (const ODESystem &ode, const dictionary &dict)
Construct from ODE system.
virtual ~SIBS ()
Destructor.
virtual bool resize ()
Resize the ODE solver.
virtual void solve (scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system as far as possible upto dxTry.
Public Member Functions inherited from ODESolver
TypeName ("ODESolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
Construct for given ODESystem.
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
Construct for given ODESystem specifying tolerances.
virtual ~ODESolver ()
Destructor.
label nEqns () const
Return the number of equations to solve.
scalarField & absTol ()
Return access to the absolute tolerance field.
scalarField & relTol ()
Return access to the relative tolerance field.
template<class Type >
void resizeField (UList< Type > &f) const
void resizeMatrix (scalarSquareMatrix &m) const
virtual void solve (scalar &x, scalarField &y, stepState &step) const
Solve the ODE system as far as possible upto dxTry.
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Solve the ODE system from xStart to xEnd, update the state.
Additional Inherited Members
Static Public Member Functions inherited from ODESolver
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
Select null constructed.
template<class Type >
static void resizeField (UList< Type > &f, const label n)
Protected Member Functions inherited from ODESolver
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
Return the nomalized scalar error.
ODESolver (const ODESolver &)
Disallow default bitwise copy construct.
void operator= (const ODESolver &)
Disallow default bitwise assignment.
Protected Attributes inherited from ODESolver
const ODESystem & odes_
Reference to ODESystem.
const label maxN_
Maximum size of the ODESystem.
label n_
Size of the ODESystem (adjustable)
scalarField absTol_
Absolute convergence tolerance per step.
scalarField relTol_
Relative convergence tolerance per step.
label maxSteps_
The maximum number of sub-steps allowed for the integration step.
Detailed Description
A semi-implicit mid-point solver for stiff systems of ordinary differential equations.
Reference:
    Bader, G., & Deuflhard, P. (1983).
    A semi-implicit mid-point rule for stiff systems
    of ordinary differential equations.
    Numerische Mathematik, 41(3), 373-398.
Source files
SIBS.H
SIMPR.C
polyExtrapolate.C
Definition at line 58 of file SIBS.H.
Constructor & Destructor Documentation
SIBS (const ODESystem & ode, const dictionary & dict)
Construct from ODE system.
Definition at line 49 of file SIBS.C.
virtual ~SIBS () inline virtual
Destructor.
Definition at line 125 of file SIBS.H.
References SIBS::resize(), SIBS::solve(), and x.
Member Function Documentation
TypeName ("SIBS")
Runtime type information.
bool resize () virtual
Resize the ODE solver.
Implements ODESolver.
Definition at line 71 of file SIBS.C.
References ODESolver::resize(), ODESolver::resizeField(), ODESolver::resizeMatrix(), and SIBS::solve().
Referenced by SIBS::~SIBS().
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Solve the ODE system as far as possible upto dxTry.
adjusting the step as necessary to provide a solution within the specified tolerance. Update the state and return an estimate for the next step in dxTry
Reimplemented from ODESolver.
Definition at line 92 of file SIBS.C.
References ODESolver::absTol_, ODESystem::derivatives(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, h, ODESystem::jacobian(), k, Foam::mag(), Foam::max(), Foam::min(), ODESolver::n_, ODESolver::odes_, Foam::pow(), ODESolver::relTol_, Foam::sqr(), and y.
Referenced by SIBS::resize(), and SIBS::~SIBS().
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/SIBS/SIBS.H
src/ODE/ODESolvers/SIBS/polyExtrapolate.C
src/ODE/ODESolvers/SIBS/SIBS.C
src/ODE/ODESolvers/SIBS/SIMPR.C