OpenFOAM: setToFaceZone Class Reference
setToFaceZone Class Reference
A topoSetSource to select faces based on usage in a faceSet. Sets flipMap to true.
Public Member Functions
TypeName ("setToFaceZone")
Runtime type information.
setToFaceZone (const polyMesh &mesh, const word &setName)
Construct from components.
setToFaceZone (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
setToFaceZone (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~setToFaceZone ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label celli, const bool) const
Add (if bool) celli to set or delete celli from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = NULL
A table of usage strings.
Detailed Description
A topoSetSource to select faces based on usage in a faceSet. Sets flipMap to true.
Source files
setToFaceZone.H
setToFaceZone.C
Definition at line 49 of file setToFaceZone.H.
Constructor & Destructor Documentation
setToFaceZone (const polyMesh & mesh, const word & setName)
Construct from components.
Definition at line 59 of file setToFaceZone.C.
Referenced by setToFaceZone::setToFaceZone().
setToFaceZone (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 71 of file setToFaceZone.C.
References setToFaceZone::setToFaceZone().
setToFaceZone (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 83 of file setToFaceZone.C.
~setToFaceZone () virtual
Destructor.
Definition at line 95 of file setToFaceZone.C.
References setToFaceZone::applyToSet().
Member Function Documentation
TypeName ("setToFaceZone")
Runtime type information.
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 96 of file setToFaceZone.H.
References setToFaceZone::applyToSet(), and topoSetSource::FACEZONESOURCE.
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 102 of file setToFaceZone.C.
References topoSetSource::ADD, faceZoneSet::addressing(), topoSetSource::DELETE, Foam::endl(), faceZoneSet::flipMap(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::found(), Foam::Info, topoSetSource::NEW, List< T >::size(), List< T >::transfer(), faceZoneSet::updateSet(), and WarningInFunction.
Referenced by setToFaceZone::setType(), and setToFaceZone::~setToFaceZone().
The documentation for this class was generated from the following files:
src/meshTools/sets/faceZoneSources/setToFaceZone/setToFaceZone.H
src/meshTools/sets/faceZoneSources/setToFaceZone/setToFaceZone.C