OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SphericalTensor2D< Cmpt > Class Template Reference
Templated 2D sphericalTensor derived from VectorSpace adding construction from 1 component, element access using ii() member function and the inner-product (dot-product) and outer-product operators.
Public Types
enum { rank = 2 }
enum components { II }
Component labeling enumeration.
Public Types inherited from VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >
enum
typedef Cmpt cmptType
Component type.
Public Member Functions
SphericalTensor2D ()
Construct null.
SphericalTensor2D (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 > &)
Construct given VectorSpace.
SphericalTensor2D (const Cmpt &tii)
Construct given the component.
SphericalTensor2D (Istream &)
Construct from Istream.
const Cmpt & ii () const
Cmpt & ii ()
Public Member Functions inherited from VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, nCmpt > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, nCmpt > &)
void operator+= (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, nCmpt > &)
void operator-= (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName = "sphericalTensor2D"
static const char * componentNames [] = {"ii"}
static const SphericalTensor2D zero
static const SphericalTensor2D one
static const SphericalTensor2D max
static const SphericalTensor2D min
static const SphericalTensor2D I
static const SphericalTensor2D oneThirdI
static const SphericalTensor2D twoThirdsI
Additional Inherited Members
Public Attributes inherited from VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >
Cmpt v_ [nCmpt]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SphericalTensor2D< Cmpt >
Templated 2D sphericalTensor derived from VectorSpace adding construction from 1 component, element access using ii() member function and the inner-product (dot-product) and outer-product operators.
Source files
SphericalTensor2D.H
SphericalTensor2DI.H
Definition at line 51 of file SphericalTensor2D.H.
Member Enumeration Documentation
anonymous enum
Enumerator
rank
Definition at line 60 of file SphericalTensor2D.H.
enum components
Component labeling enumeration.
Enumerator
II
Definition at line 80 of file SphericalTensor2D.H.
Constructor & Destructor Documentation
SphericalTensor2D () inline
Construct null.
Definition at line 37 of file SphericalTensor2DI.H.
SphericalTensor2D (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 > & vs) inline
Construct given VectorSpace.
Definition at line 44 of file SphericalTensor2DI.H.
SphericalTensor2D (const Cmpt & tii) inline
Construct given the component.
Definition at line 54 of file SphericalTensor2DI.H.
SphericalTensor2D (Istream & is) inline
Construct from Istream.
Definition at line 62 of file SphericalTensor2DI.H.
Member Function Documentation
const Cmpt & ii () const inline
Definition at line 71 of file SphericalTensor2DI.H.
References SphericalTensor2D< Cmpt >::II, and VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >::v_.
Referenced by Foam::det(), Foam::inv(), Foam::operator&(), Foam::operator&&(), Foam::operator+(), Foam::operator-(), Foam::operator/(), SymmTensor2D< Cmpt >::operator=(), Tensor2D< Cmpt >::operator=(), SymmTensor2D< Cmpt >::SymmTensor2D(), Tensor2D< Cmpt >::Tensor2D(), and Foam::tr().
Cmpt & ii () inline
Definition at line 78 of file SphericalTensor2DI.H.
References SphericalTensor2D< Cmpt >::II, and VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >::v_.
Member Data Documentation
const char *const typeName = "sphericalTensor2D" static
Definition at line 68 of file SphericalTensor2D.H.
const char * componentNames = {"ii"} static
Definition at line 69 of file SphericalTensor2D.H.
const sphericalTensor2D zero static
Definition at line 70 of file SphericalTensor2D.H.
const sphericalTensor2D one static
Definition at line 71 of file SphericalTensor2D.H.
const sphericalTensor2D max static
Definition at line 72 of file SphericalTensor2D.H.
const sphericalTensor2D min static
Definition at line 73 of file SphericalTensor2D.H.
const sphericalTensor2D I static
Definition at line 74 of file SphericalTensor2D.H.
const sphericalTensor2D oneThirdI static
Definition at line 75 of file SphericalTensor2D.H.
const sphericalTensor2D twoThirdsI static
Definition at line 76 of file SphericalTensor2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SphericalTensor2D/SphericalTensor2D.H
src/OpenFOAM/primitives/SphericalTensor2D/sphericalTensor2D/sphericalTensor2D.C
src/OpenFOAM/primitives/SphericalTensor2D/SphericalTensor2DI.H