OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SquareMatrix< Type > Class Template Reference
A templated 2D square matrix of objects of <T>, where the n x n matrix dimension is known and used for subscript bounds checking, etc.
Public Member Functions
SquareMatrix ()
Null constructor.
SquareMatrix (const label n)
Construct given number of rows/columns.
SquareMatrix (const label m, const label n)
Construct given number of rows and columns,.
SquareMatrix (const label m, const label n, const Type &)
Construct with given number of rows and rows.
SquareMatrix (Istream &)
Construct from Istream.
autoPtr< SquareMatrix< Type > > clone () const
Clone.
Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label n, const label m)
Construct given number of rows and columns.
Matrix (const label n, const label m, const Type &)
Construct with given number of rows and columns.
Matrix (const Matrix< SquareMatrix< Type >, Type > &)
Copy constructor.
Matrix (Istream &)
Construct from Istream.
autoPtr< Matrix< SquareMatrix< Type >, Type > > clone () const
Clone.
~Matrix ()
Destructor.
label n () const
Return the number of rows.
label m () const
Return the number of columns.
label size () const
Return the number of elements in matrix (n*m)
void checki (const label i) const
Check index i is within valid range (0 ... n-1).
void checkj (const label j) const
Check index j is within valid range (0 ... m-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (Matrix< SquareMatrix< Type >, Type > &)
Transfer the contents of the argument Matrix into this Matrix.
SquareMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
void operator= (const Matrix< SquareMatrix< Type >, Type > &)
Assignment operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
Additional Inherited Members
Static Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
static const Matrix< SquareMatrix< Type >, Type > & null ()
Return a null Matrix.
Detailed Description
template<class Type>
class Foam::SquareMatrix< Type >
A templated 2D square matrix of objects of <T>, where the n x n matrix dimension is known and used for subscript bounds checking, etc.
Source files
SquareMatrix.H
SquareMatrixI.H
SquareMatrix.C
Definition at line 51 of file SquareMatrix.H.
Constructor & Destructor Documentation
SquareMatrix () inline
Null constructor.
Definition at line 29 of file SquareMatrixI.H.
Referenced by SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const label n) inline
Construct given number of rows/columns.
Definition at line 35 of file SquareMatrixI.H.
SquareMatrix (const label m, const label n) inline
Construct given number of rows and columns,.
It checks that m == n.
Definition at line 41 of file SquareMatrixI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const label m, const label n, const Type & t) inline
Construct with given number of rows and rows.
and value for all elements. It checks that m == n.
Definition at line 54 of file SquareMatrixI.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
SquareMatrix (Istream & is) inline
Construct from Istream.
Definition at line 70 of file SquareMatrixI.H.
Member Function Documentation
Foam::autoPtr< Foam::SquareMatrix< Type > > clone () const inline
Clone.
Definition at line 77 of file SquareMatrixI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/SquareMatrix/SquareMatrix.H
src/OpenFOAM/matrices/SquareMatrix/SquareMatrixI.H