OpenFOAM: singleStepReactingMixture< ThermoType > Class Template Reference
singleStepReactingMixture< ThermoType > Class Template Reference
Single step reacting mixture.
Public Types
typedef ThermoType thermoType
The type of thermo package this mixture is instantiated for.
Public Types inherited from reactingMixture< ThermoType >
typedef ThermoType thermoType
The type of thermo package this mixture is instantiated for.
Public Types inherited from List< word >
typedef SubList< word > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Types inherited from autoPtr< chemistryReader< ThermoType > >
typedef chemistryReader< ThermoType > Type
Public Types inherited from multiComponentMixture< ThermoType >
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Public Types inherited from basicSpecieMixture
typedef basicSpecieMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Public Member Functions
singleStepReactingMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
virtual ~singleStepReactingMixture ()
Destructor.
void fresCorrect ()
Calculates the residual for all components.
const dimensionedScalar stoicRatio () const
Return the stoichiometric air-fuel mass ratio.
const dimensionedScalar s () const
Return the Stoichiometric oxygen-fuel mass ratio.
const dimensionedScalar qFuel () const
Return the heat of combustion [J/Kg].
const List< scalar > & specieStoichCoeffs () const
Return the stoichiometric coefficient for the reaction.
tmp< volScalarField > fres (const label index) const
Return the list of components residual.
label inertIndex () const
Return the inert specie index.
label fuelIndex () const
Return the fuel specie index.
const List< int > & specieProd () const
Return the list to indicate if specie is produced/consumed.
const scalarList & Yprod0 () const
Return the list of products mass concentrations.
void read (const dictionary &)
Read dictionary.
Public Member Functions inherited from reactingMixture< ThermoType >
reactingMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
virtual ~reactingMixture ()
Destructor.
void read (const dictionary &)
Read dictionary.
label size () const
Reaction< ThermoType > & operator[] (const label i)
const Reaction< ThermoType > & operator[] (const label i) const
const speciesCompositionTable & specieComposition () const
Table of species composition.
Public Member Functions inherited from hashedWordList
hashedWordList ()
Construct null.
hashedWordList (const hashedWordList &)
Copy constructor.
hashedWordList (const UList< word > &names)
Construct from list of names.
hashedWordList (const Xfer< List< word >> &names)
Construct by transferring the parameter contents.
hashedWordList (const label nNames, const char **names)
Construct from number and list of names.
hashedWordList (const char **names)
Construct from a nullptr-terminated list of names.
hashedWordList (Istream &)
Construct from Istream.
void clear ()
Clear the list, i.e. set size to zero.
void append (const word &)
Append an element at the end of the list.
bool found (const word &) const
Does the list contain the specified name.
bool contains (const word &) const
Does the list contain the specified name.
void transfer (List< word > &)
Transfer the contents of the argument List into this list.
void operator= (const UList< word > &names)
Assignment operator from list of names.
void operator= (const hashedWordList &)
Assignment operator.
const word & operator[] (const label index) const
Return name corresponding to specified index.
label operator[] (const word &) const
Return index corresponding to specified name.
Public Member Functions inherited from List< word >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const word &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< word > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< word >> &)
Construct by transferring the parameter contents.
List (List< word > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< word > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< word, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< word > &)
Construct as copy of PtrList<T>
List (const SLList< word > &)
Construct as copy of SLList<T>
List (const UIndirectList< word > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< word > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< word >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< word > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const word &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const word &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const word &)
Append an element at the end of the list.
void append (const UList< word > &)
Append a List at the end of this list.
void append (const UIndirectList< word > &)
Append a UIndirectList at the end of this list.
void transfer (List< word > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< word, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< word > &)
Transfer the contents of the argument List into this list.
Xfer< List< word > > xfer ()
Transfer contents to the Xfer container.
word & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< word > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< word > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< word > &)
Assignment operator. Takes linear time.
void operator= (const SLList< word > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< word > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< word > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< word >)
Assignment to an initializer list.
void operator= (const word &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Public Member Functions inherited from autoPtr< chemistryReader< ThermoType > >
autoPtr (chemistryReader< ThermoType > *=0)
Store object pointer.
autoPtr (const autoPtr< chemistryReader< ThermoType > > &)
Construct as copy by transferring pointer to this autoPtr and.
autoPtr (const autoPtr< chemistryReader< ThermoType > > &, const bool reuse)
Construct either by transferring pointer or cloning.
~autoPtr ()
Destructor, delete object if pointer is not nullptr.
bool empty () const
Return true if the autoPtr is empty (ie, no pointer set)
bool valid () const
Return true if the autoPtr valid (ie, the pointer is set)
chemistryReader< ThermoType > * ptr ()
Return object pointer for reuse.
void set (chemistryReader< ThermoType > *)
Set pointer to that given.
void reset (chemistryReader< ThermoType > *=0)
If object pointer already set, delete object and set to given.
void clear ()
Delete object (if the pointer is valid) and set pointer to.
chemistryReader< ThermoType > & operator() ()
Return reference to the object data.
const chemistryReader< ThermoType > & operator() () const
Return const reference to the object data.
operator const chemistryReader< ThermoType > & () const
Const cast to the underlying type reference.
chemistryReader< ThermoType > * operator-> ()
Return object pointer.
const chemistryReader< ThermoType > * operator-> () const
Return const object pointer.
void operator= (const autoPtr< chemistryReader< ThermoType > > &)
Take over the object pointer from parameter.
Public Member Functions inherited from multiComponentMixture< ThermoType >
multiComponentMixture (const dictionary &, const wordList &specieNames, const HashPtrTable< ThermoType > &thermoData, const fvMesh &, const word &)
Construct from dictionary, specie names, thermo database,.
multiComponentMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
virtual ~multiComponentMixture ()
Destructor.
const ThermoType & cellMixture (const label celli) const
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
const ThermoType & cellVolMixture (const scalar p, const scalar T, const label celli) const
const ThermoType & patchFaceVolMixture (const scalar p, const scalar T, const label patchi, const label facei) const
const PtrList< ThermoType > & speciesData () const
Return the raw specie thermodynamic data.
void read (const dictionary &)
Read dictionary.
const ThermoType & getLocalThermo (const label speciei) const
Return thermo based on index.
Public Member Functions inherited from basicSpecieMixture
TypeName ("basicSpecieMixture")
Run time type information.
basicSpecieMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicSpecieMixture ()
Destructor.
virtual scalar nMoles (const label speciei) const =0
Number of moles of the given specie [].
virtual scalar W (const label speciei) const =0
Molecular weight of the given specie [kg/kmol].
tmp< volScalarField > W () const
Molecular weight of the mixture [kg/kmol].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar Hc (const label speciei) const =0
Chemical enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
Density [kg/m3].
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
bool contains (const word &specieName) const
Does the mixture include this specie?
bool active (label speciei) const
Return true for active species.
const List< bool > & active () const
Return the bool list of active species.
void setActive (label speciei)
Set speciei active.
void setInactive (label speciei)
Set speciei inactive.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
Public Member Functions inherited from PtrList< Reaction< ThermoType > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< Reaction< ThermoType > > &)
Copy constructor.
PtrList (const PtrList< Reaction< ThermoType > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< Reaction< ThermoType > >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< Reaction< ThermoType > > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< Reaction< ThermoType > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (Reaction< ThermoType > *)
Append an element at the end of the list.
void append (const autoPtr< Reaction< ThermoType > > &)
void append (const tmp< Reaction< ThermoType > > &)
void transfer (PtrList< Reaction< ThermoType > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< Reaction< ThermoType > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< Reaction< ThermoType > > set (const label, Reaction< ThermoType > *)
Set element to given T* and return old element (can be nullptr)
autoPtr< Reaction< ThermoType > > set (const label, const autoPtr< Reaction< ThermoType > > &)
Set element to given autoPtr<T> and return old element.
autoPtr< Reaction< ThermoType > > set (const label, const tmp< Reaction< ThermoType > > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< Reaction< ThermoType > > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Member Functions
void calculateqFuel ()
Calculate qFuel.
void massAndAirStoichRatios ()
Calculate air/fuel and oxygen/fuel ratio.
void calculateMaxProducts ()
Calculate maximum products at stoichiometric mixture.
Protected Member Functions inherited from List< word >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Member Functions inherited from PtrList< Reaction< ThermoType > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Attributes
dimensionedScalar stoicRatio_
Stoichiometric air-fuel mass ratio.
dimensionedScalar s_
Stoichiometric oxygen-fuel mass ratio.
dimensionedScalar qFuel_
Heat of combustion [J/Kg].
scalarList specieStoichCoeffs_
Stoichiometric coefficient for the reaction.
scalarList Yprod0_
Mass concentrations at stoichiometric mixture for fres.
PtrList< volScalarField > fres_
List of components residual.
label inertIndex_
Inert specie index.
label fuelIndex_
Fuel specie index.
List< int > specieProd_
List to indicate if specie is produced/consumed.
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
Table of specie names.
List< bool > active_
List of specie active flags.
PtrList< volScalarField > Y_
Species mass fractions.
Additional Inherited Members
Static Public Member Functions inherited from List< word >
static const List< word > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Detailed Description
template<class ThermoType>
class Foam::singleStepReactingMixture< ThermoType >
Single step reacting mixture.
Source files
singleStepReactingMixture.H
singleStepReactingMixture.C
Definition at line 50 of file singleStepReactingMixture.H.
Member Typedef Documentation
typedef ThermoType thermoType
The type of thermo package this mixture is instantiated for.
Definition at line 113 of file singleStepReactingMixture.H.
Constructor & Destructor Documentation
singleStepReactingMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, mesh and phase name.
Definition at line 192 of file singleStepReactingMixture.C.
References clear(), Foam::dimless, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, Foam::name(), and singleStepReactingMixture< ThermoType >::read().
virtual ~singleStepReactingMixture () inline virtual
Destructor.
Definition at line 128 of file singleStepReactingMixture.H.
References singleStepReactingMixture< ThermoType >::fres(), singleStepReactingMixture< ThermoType >::fresCorrect(), singleStepReactingMixture< ThermoType >::fuelIndex(), singleStepReactingMixture< ThermoType >::inertIndex(), singleStepReactingMixture< ThermoType >::qFuel(), singleStepReactingMixture< ThermoType >::read(), singleStepReactingMixture< ThermoType >::s(), singleStepReactingMixture< ThermoType >::specieProd(), singleStepReactingMixture< ThermoType >::specieStoichCoeffs(), singleStepReactingMixture< ThermoType >::stoicRatio(), and singleStepReactingMixture< ThermoType >::Yprod0().
Member Function Documentation
void calculateqFuel () protected
Calculate qFuel.
Definition at line 32 of file singleStepReactingMixture.C.
References Foam::endl(), forAll, Foam::Info, Reaction< ReactionThermo >::lhs(), reaction(), and Reaction< ReactionThermo >::rhs().
void massAndAirStoichRatios () protected
Calculate air/fuel and oxygen/fuel ratio.
Definition at line 59 of file singleStepReactingMixture.C.
References Foam::endl(), Foam::Info, and Foam::mag().
void calculateMaxProducts () protected
Calculate maximum products at stoichiometric mixture.
Definition at line 83 of file singleStepReactingMixture.C.
References forAll, Foam::Info, Foam::mag(), Foam::nl, reaction(), and Reaction< ReactionThermo >::rhs().
void fresCorrect ()
Calculates the residual for all components.
Definition at line 133 of file singleStepReactingMixture.C.
References forAll, Reaction< ReactionThermo >::lhs(), Foam::max(), reaction(), Reaction< ReactionThermo >::rhs(), and Y.
Referenced by singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
const Foam::dimensionedScalar stoicRatio () const inline
Return the stoichiometric air-fuel mass ratio.
Definition at line 32 of file singleStepReactingMixtureI.H.
Referenced by singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
const Foam::dimensionedScalar s () const inline
Return the Stoichiometric oxygen-fuel mass ratio.
Definition at line 40 of file singleStepReactingMixtureI.H.
Referenced by singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
const Foam::dimensionedScalar qFuel () const inline
Return the heat of combustion [J/Kg].
Definition at line 48 of file singleStepReactingMixtureI.H.
Referenced by singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
const Foam::List< Foam::scalar > & specieStoichCoeffs () const inline
Return the stoichiometric coefficient for the reaction.
Definition at line 56 of file singleStepReactingMixtureI.H.
References singleStepReactingMixture< ThermoType >::fres().
Referenced by singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
Foam::tmp< Foam::volScalarField > fres (const label index) const inline
Return the list of components residual.
Definition at line 65 of file singleStepReactingMixtureI.H.
Referenced by singleStepReactingMixture< ThermoType >::specieStoichCoeffs(), and singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
Foam::label inertIndex () const inline
Return the inert specie index.
Definition at line 75 of file singleStepReactingMixtureI.H.
Referenced by singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
Foam::label fuelIndex () const inline
Return the fuel specie index.
Definition at line 83 of file singleStepReactingMixtureI.H.
Referenced by singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
const Foam::List< int > & specieProd () const inline
Return the list to indicate if specie is produced/consumed.
Definition at line 91 of file singleStepReactingMixtureI.H.
Referenced by singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
const Foam::scalarList & Yprod0 () const inline
Return the list of products mass concentrations.
Definition at line 99 of file singleStepReactingMixtureI.H.
Referenced by singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
void read (const dictionary & thermoDict)
Read dictionary.
Definition at line 255 of file singleStepReactingMixture.C.
Referenced by singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), and singleStepReactingMixture< ThermoType >::~singleStepReactingMixture().
Member Data Documentation
dimensionedScalar stoicRatio_ protected
Stoichiometric air-fuel mass ratio.
Definition at line 60 of file singleStepReactingMixture.H.
dimensionedScalar s_ protected
Stoichiometric oxygen-fuel mass ratio.
Definition at line 63 of file singleStepReactingMixture.H.
dimensionedScalar qFuel_ protected
Heat of combustion [J/Kg].
Definition at line 66 of file singleStepReactingMixture.H.
scalarList specieStoichCoeffs_ protected
Stoichiometric coefficient for the reaction.
Definition at line 69 of file singleStepReactingMixture.H.
scalarList Yprod0_ protected
Mass concentrations at stoichiometric mixture for fres.
Definition at line 72 of file singleStepReactingMixture.H.
PtrList<volScalarField> fres_ protected
List of components residual.
Definition at line 75 of file singleStepReactingMixture.H.
label inertIndex_ protected
Inert specie index.
Definition at line 78 of file singleStepReactingMixture.H.
label fuelIndex_ protected
Fuel specie index.
Definition at line 81 of file singleStepReactingMixture.H.
List<int> specieProd_ protected
List to indicate if specie is produced/consumed.
Definition at line 84 of file singleStepReactingMixture.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/singleStepReactingMixture/singleStepReactingMixture.H
src/thermophysicalModels/reactionThermo/mixtures/singleStepReactingMixture/singleStepReactingMixture.C
src/thermophysicalModels/reactionThermo/mixtures/singleStepReactingMixture/singleStepReactingMixtureI.H