OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SLTSDdtScheme< Type > Class Template Reference
Stabilised local time-step first-order Euler implicit/explicit ddt. The time-step is adjusted locally so that an advective equations remains diagonally dominant.
Public Types
typedef ddtScheme< Type >::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("SLTS")
Runtime type information.
SLTSDdtScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
Construct from mesh.
ddtScheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~ddtScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new ddtScheme created on freestore.
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)
Disallow copy construct.
void operator= (const ddtScheme &)
Disallow default bitwise assignment.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::SLTSDdtScheme< Type >
Stabilised local time-step first-order Euler implicit/explicit ddt. The time-step is adjusted locally so that an advective equations remains diagonally dominant.
This scheme should only be used for steady-state computations using transient codes where local time-stepping is preferably to under-relaxation for transport consistency reasons.
See also
Foam::fv::CoEulerDdtScheme
Source files
SLTSDdtScheme.H
SLTSDdtScheme.C
Definition at line 63 of file SLTSDdtScheme.H.
Member Typedef Documentation
typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 174 of file SLTSDdtScheme.H.
Constructor & Destructor Documentation
SLTSDdtScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 104 of file SLTSDdtScheme.H.
Member Function Documentation
TypeName ("SLTS")
Runtime type information.
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 116 of file SLTSDdtScheme.H.
References Foam::constant::atomic::alpha, SLTSDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvmDdt(), ddtScheme< Type >::mesh(), psi, and rho.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 156 of file SLTSDdtScheme.C.
References dimensioned< Type >::dimensions(), Foam::dimTime, mesh, dimensioned< Type >::name(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), tmp< T >::ref(), dimensioned< Type >::value(), and Foam::Zero.
Referenced by SLTSDdtScheme< Type >::fvcDdt(), and SLTSDdtScheme< Type >::mesh().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 215 of file SLTSDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), SLTSDdtScheme< Type >::fvcDdt(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and GeometricField< Type, PatchField, GeoMesh >::primitiveField().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 266 of file SLTSDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), SLTSDdtScheme< Type >::fvcDdt(), mesh, dimensioned< Type >::name(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and dimensioned< Type >::value().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 318 of file SLTSDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), SLTSDdtScheme< Type >::fvcDdt(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and GeometricField< Type, PatchField, GeoMesh >::primitiveField().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 373 of file SLTSDdtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), SLTSDdtScheme< Type >::fvmDdt(), mesh, IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), and GeometricField< Type, PatchField, GeoMesh >::primitiveField().
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 442 of file SLTSDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), tmp< T >::ref(), and fvMatrix< Type >::source().
Referenced by SLTSDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvmDdt(), and SLTSDdtScheme< Type >::mesh().
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 477 of file SLTSDdtScheme.C.
References lduMatrix::diag(), dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, SLTSDdtScheme< Type >::fvmDdt(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), tmp< T >::ref(), fvMatrix< Type >::source(), and dimensioned< Type >::value().
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 514 of file SLTSDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, SLTSDdtScheme< Type >::fvmDdt(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), tmp< T >::ref(), and fvMatrix< Type >::source().
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 553 of file SLTSDdtScheme.C.
References lduMatrix::diag(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, SLTSDdtScheme< Type >::fvcDdtUfCorr(), mesh, GeometricField< Type, PatchField, GeoMesh >::oldTime(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), tmp< T >::ref(), and fvMatrix< Type >::source().
tmp< typename SLTSDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 596 of file SLTSDdtScheme.C.
References Foam::fvc::dotInterpolate(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
Referenced by SLTSDdtScheme< Type >::fvcDdtPhiCorr(), and SLTSDdtScheme< Type >::fvmDdt().
tmp< typename SLTSDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 629 of file SLTSDdtScheme.C.
References Foam::fvc::dotInterpolate(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
Referenced by SLTSDdtScheme< Type >::fvcDdtUfCorr().
tmp< typename SLTSDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 661 of file SLTSDdtScheme.C.
References Foam::abort(), Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::fvc::dotInterpolate(), Foam::FatalError, FatalErrorInFunction, SLTSDdtScheme< Type >::fvcDdtPhiCorr(), Foam::fvc::interpolate(), mesh, IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< typename SLTSDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 720 of file SLTSDdtScheme.C.
References Foam::abort(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::fvc::dotInterpolate(), Foam::FatalError, FatalErrorInFunction, mesh, SLTSDdtScheme< Type >::meshPhi(), IOobject::name(), and GeometricField< Type, PatchField, GeoMesh >::oldTime().
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &) virtual
Implements ddtScheme< Type >.
Definition at line 781 of file SLTSDdtScheme.C.
References Foam::dimTime, Foam::dimVolume, mesh, IOobject::NO_READ, IOobject::NO_WRITE, and timeName.
Referenced by SLTSDdtScheme< Type >::fvcDdtPhiCorr().
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/SLTSDdtScheme/SLTSDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/SLTSDdtScheme/SLTSDdtScheme.C