OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SphereDragForce< CloudType > Class Template Reference
Drag model based on assumption of solid spheres.
Public Member Functions
TypeName ("sphereDrag")
Runtime type information.
SphereDragForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
Construct from mesh.
SphereDragForce (const SphereDragForce< CloudType > &df)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~SphereDragForce ()
Destructor.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::SphereDragForce< CloudType >
Drag model based on assumption of solid spheres.
Definition at line 45 of file SphereDragForce.H.
Constructor & Destructor Documentation
SphereDragForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Construct from mesh.
Definition at line 48 of file SphereDragForce.C.
SphereDragForce (const SphereDragForce< CloudType > & df)
Construct copy.
Definition at line 60 of file SphereDragForce.C.
~SphereDragForce () virtual
Destructor.
Definition at line 71 of file SphereDragForce.C.
References SphereDragForce< CloudType >::calcCoupled().
Referenced by SphereDragForce< CloudType >::clone().
Member Function Documentation
TypeName ("sphereDrag")
Runtime type information.
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from ParticleForce< CloudType >.
Definition at line 75 of file SphereDragForce.H.
References SphereDragForce< CloudType >::calcCoupled(), p, and SphereDragForce< CloudType >::~SphereDragForce().
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the coupled force.
Reimplemented from ParticleForce< CloudType >.
Definition at line 79 of file SphereDragForce.C.
References forceSuSp::Sp(), Foam::sqr(), and Foam::Zero.
Referenced by SphereDragForce< CloudType >::clone(), and SphereDragForce< CloudType >::~SphereDragForce().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/SphereDrag/SphereDragForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/SphereDrag/SphereDragForce.C