OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SphericalTensor2D< Cmpt > Class Template Reference
Templated 2D sphericalTensor derived from VectorSpace adding construction from 1 component, element access using ii() member function and the inner-product (dot-product) and outer-product operators.
Public Types
enum components { II }
Component labeling enumeration.
Public Types inherited from VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >
typedef VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
Public Member Functions
SphericalTensor2D ()
Construct null.
SphericalTensor2D (const Foam::zero)
Construct initialized to zero.
SphericalTensor2D (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 > &)
Construct given VectorSpace.
SphericalTensor2D (const Cmpt &tii)
Construct given the component.
SphericalTensor2D (Istream &)
Construct from Istream.
const Cmpt & ii () const
Cmpt & ii ()
Public Member Functions inherited from VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, Ncmpts > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const direction rank = 2
Rank of SphericalTensor2D is 2.
static const SphericalTensor2D I
static const SphericalTensor2D oneThirdI
static const SphericalTensor2D twoThirdsI
Static Public Attributes inherited from VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >
static const direction dim
Dimensionality of space.
static const direction nComponents
Number of components in this vector space.
static const direction mRows
static const direction nCols
static const char *const typeName
static const char *const componentNames []
static const SphericalTensor2D< Cmpt > zero
static const SphericalTensor2D< Cmpt > one
static const SphericalTensor2D< Cmpt > max
static const SphericalTensor2D< Cmpt > min
static const SphericalTensor2D< Cmpt > rootMax
static const SphericalTensor2D< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static SphericalTensor2D< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SphericalTensor2D< Cmpt >
Templated 2D sphericalTensor derived from VectorSpace adding construction from 1 component, element access using ii() member function and the inner-product (dot-product) and outer-product operators.
Source files
SphericalTensor2D.H
SphericalTensor2DI.H
Definition at line 51 of file SphericalTensor2D.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
II
Definition at line 72 of file SphericalTensor2D.H.
Constructor & Destructor Documentation
SphericalTensor2D () inline
Construct null.
Definition at line 31 of file SphericalTensor2DI.H.
Referenced by SphericalTensor2D< Cmpt >::SphericalTensor2D().
SphericalTensor2D (const Foam::zero) inline
Construct initialized to zero.
Definition at line 36 of file SphericalTensor2DI.H.
References SphericalTensor2D< Cmpt >::SphericalTensor2D().
SphericalTensor2D (const VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 > & vs) inline
Construct given VectorSpace.
Definition at line 44 of file SphericalTensor2DI.H.
SphericalTensor2D (const Cmpt & tii) inline
Construct given the component.
Definition at line 53 of file SphericalTensor2DI.H.
References SphericalTensor2D< Cmpt >::II, and VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >::v_.
SphericalTensor2D (Istream & is) inline
Construct from Istream.
Definition at line 60 of file SphericalTensor2DI.H.
Member Function Documentation
const Cmpt & ii () const inline
Definition at line 69 of file SphericalTensor2DI.H.
References SphericalTensor2D< Cmpt >::II, and VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >::v_.
Referenced by Foam::det(), Foam::inv(), Foam::operator&(), Foam::operator&&(), Foam::operator+(), Foam::operator-(), Foam::operator/(), Tensor2D< Cmpt >::operator=(), SymmTensor2D< Cmpt >::SymmTensor2D(), Tensor2D< Cmpt >::Tensor2D(), and Foam::tr().
Cmpt & ii () inline
Definition at line 76 of file SphericalTensor2DI.H.
References SphericalTensor2D< Cmpt >::II, and VectorSpace< SphericalTensor2D< Cmpt >, Cmpt, 1 >::v_.
Member Data Documentation
const direction rank = 2 static
Rank of SphericalTensor2D is 2.
Definition at line 61 of file SphericalTensor2D.H.
const Foam::sphericalTensor2D I static
Definition at line 66 of file SphericalTensor2D.H.
const Foam::sphericalTensor2D oneThirdI static
Definition at line 67 of file SphericalTensor2D.H.
const Foam::sphericalTensor2D twoThirdsI static
Definition at line 68 of file SphericalTensor2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SphericalTensor2D/SphericalTensor2D.H
src/OpenFOAM/primitives/SphericalTensor2D/sphericalTensor2D/sphericalTensor2D.C
src/OpenFOAM/primitives/SphericalTensor2D/SphericalTensor2DI.H