OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
solidParticle Class Reference
Simple solid spherical particle class with one-way coupling with the continuous phase.
Classes
class iNew
Factory class to read-construct particles used for.
class trackingData
Class used to pass tracking data to the trackToFace function.
Public Member Functions
solidParticle (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI, const scalar d, const vector &U)
Construct from components.
solidParticle (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
virtual autoPtr< particle > clone () const
Construct and return a clone.
scalar d () const
Return diameter.
const vector & U () const
Return velocity.
bool move (trackingData &, const scalar)
Move.
bool hitPatch (const polyPatch &, trackingData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a patch.
void hitProcessorPatch (const processorPolyPatch &, trackingData &td)
Overridable function to handle the particle hitting a.
void hitWallPatch (const wallPolyPatch &, trackingData &td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
void hitPatch (const polyPatch &, trackingData &td)
Overridable function to handle the particle hitting a polyPatch.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
virtual scalar wallImpactDistance (const vector &n) const
The nearest distance to a wall that.
Public Member Functions inherited from particle< Type >
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const vector &position, const label cellI, const label tetFaceI, const label tetPtI)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label cellI, bool doCellFacePt=true)
Construct from components, tetFaceI_ and tetPtI_ are not.
particle (const polyMesh &mesh, Istream &, bool readFields=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with refernce to a new mesh.
virtual ~particle ()
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const vector & position () const
Return current particle position.
vector & position ()
Return current particle position.
label & cell ()
Return current cell particle is in.
label cell () const
Return current cell particle is in.
label & tetFace ()
Return current tet face particle is in.
label tetFace () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in.
label tetPt () const
Return current tet face particle is in.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
tetPointRef currentTet () const
Return the geometry of the current tet that the.
vector normal () const
Return the normal of the tri on tetFaceI_ for the.
vector oldNormal () const
Return the normal of the tri on tetFaceI_ for the.
label & face ()
Return current face particle is on otherwise -1.
label face () const
Return current face particle is on otherwise -1.
bool softImpact () const
Return the impact model to be used, soft or hard (default).
scalar currentTime () const
Return the particle current time.
void initCellFacePt ()
Check the stored cell value (setting if necessary) and.
bool onBoundary () const
Is the particle on the boundary/(or outside the domain)?
bool internalFace (const label faceI) const
Is this global face an internal face?
bool boundaryFace (const label faceI) const
Is this global face a boundary face?
label patch (const label faceI) const
Which patch is particle on.
label patchFace (const label patchI, const label faceI) const
Which face of this patch is this particle on.
scalar & stepFraction ()
Return the fraction of time-step completed.
scalar stepFraction () const
Return the fraction of time-step completed.
label origProc () const
Return const access to the originating processor id.
label & origProc ()
Return the originating processor id for manipulation.
label origId () const
Return const access to the particle id on originating processor.
label & origId ()
Return the particle id on originating processor for manipulation.
template<class TrackData >
label track (const vector &endPosition, TrackData &td)
Track particle to end of trajectory.
template<class TrackData >
scalar trackToFace (const vector &endPosition, TrackData &td)
Track particle to a given position and returns 1.0 if the.
label faceInterpolation () const
Return the index of the face to be used in the interpolation.
template<class TrackData >
void prepareForParallelTransfer (const label patchI, TrackData &td)
Convert global addressing to the processor patch.
template<class TrackData >
void correctAfterParallelTransfer (const label patchI, TrackData &td)
Convert processor patch addressing to the global equivalents.
void writePosition (Ostream &) const
Write the particle position and cell.
template<class TrackData >
Foam::label track (const vector &endPosition, TrackData &td)
template<class TrackData >
Foam::scalar trackToFace (const vector &endPosition, TrackData &td)
Public Member Functions inherited from DLListBase::link
link ()
Null construct.
bool registered () const
Check if the link is registered with the DLListBase.
void deregister ()
Deregister the link after removal.
Static Public Member Functions
static void readFields (Cloud< solidParticle > &c)
static void writeFields (const Cloud< solidParticle > &c)
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class CloudType >
static void readFields (CloudType &c)
Read the fields associated with the owner cloud.
template<class CloudType >
static void writeFields (const CloudType &c)
Write the fields associated with the owner cloud.
Friends
class Cloud< solidParticle >
Ostream & operator<< (Ostream &, const solidParticle &)
Additional Inherited Members
Public Attributes inherited from DLListBase::link
link * prev_
Pointer to next entry in list.
link * next_
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provode unique ID.
static const scalar trackingCorrectionTol = 1e-5
Fraction of distance to tet centre to move a particle to.
static const scalar lambdaDistanceToleranceCoeff = 1e3*SMALL
Fraction of the cell volume to use in determining tolerance values.
static const scalar minStepFractionTol = 1e5*SMALL
Minimum stepFraction tolerance.
Protected Member Functions inherited from particle< Type >
void findTris (const vector &position, DynamicList< label > &faceList, const tetPointRef &tet, const FixedList< vector, 4 > &tetAreas, const FixedList< label, 4 > &tetPlaneBasePtIs, const scalar tol) const
Find the tet tri faces between position and tet centre.
scalar tetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for the line to-from across the.
scalar movingTetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label cellI, const label tetFaceI, const label tetPtI, const scalar tol) const
Find the lambda value for a moving tri face.
void tetNeighbour (label triI)
Modify the tet owner data by crossing triI.
void crossEdgeConnectedFace (const label &cellI, label &tetFaceI, label &tetPtI, const edge &e)
Cross the from the given face across the given edge of the.
template<class CloudType >
void hitWallFaces (const CloudType &td, const vector &from, const vector &to, scalar &lambdaMin, tetIndices &closestTetIs)
template<class TrackData >
void hitFace (TrackData &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchI, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackData >
void hitCyclicAMIPatch (const cyclicAMIPolyPatch &, TrackData &td, const vector &direction)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &tetIs)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
Protected Attributes inherited from particle< Type >
const polyMesh & mesh_
Reference to the polyMesh database.
vector position_
Position of particle.
label cellI_
Index of the cell it is in.
label faceI_
Face index if the particle is on a face otherwise -1.
scalar stepFraction_
Fraction of time-step completed.
label tetFaceI_
Index of the face that owns the decomposed tet that the.
label tetPtI_
Index of the point on the face that defines the decomposed.
label origProc_
Originating processor id.
label origId_
Local particle id on originating processor.
Detailed Description
Simple solid spherical particle class with one-way coupling with the continuous phase.
Source files
solidParticle.H
solidParticleI.H
solidParticle.C
solidParticleIO.C
Definition at line 57 of file solidParticle.H.
Constructor & Destructor Documentation
solidParticle (const polyMesh & mesh, const vector & position, const label cellI, const label tetFaceI, const label tetPtI, const scalar d, const vector & U) inline
Construct from components.
Definition at line 46 of file solidParticleI.H.
Referenced by solidParticle::clone(), solidParticle::iNew::operator()(), and solidParticle::trackingData::trackingData().
solidParticle (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 40 of file solidParticleIO.C.
References IOstream::check(), IOstream::format(), Istream::read(), and readScalar.
Member Function Documentation
virtual autoPtr<particle> clone () const inline virtual
Construct and return a clone.
Reimplemented from particle< Type >.
Definition at line 141 of file solidParticle.H.
References particle< Type >::mesh_, and solidParticle::solidParticle().
Foam::scalar d () const inline
Return diameter.
Definition at line 90 of file solidParticleI.H.
Referenced by solidParticle::iNew::operator()(), solidParticle::readFields(), and solidParticle::writeFields().
const Foam::vector & U () const inline
Return velocity.
Definition at line 96 of file solidParticleI.H.
Referenced by solidParticle::iNew::operator()(), solidParticle::readFields(), and solidParticle::writeFields().
bool move (trackingData & td, const scalar trackTime)
Move.
Definition at line 38 of file solidParticle.C.
References particle< Type >::TrackingData< CloudType >::cloud(), Foam::endl(), solidParticle::trackingData::g(), solidParticle::hitPatch(), Foam::Info, interpolationCellPoint< Type >::interpolate(), particle< Type >::TrackingData< CloudType >::keepParticle, Foam::mag(), Foam::min(), solidParticle::trackingData::nuInterp(), Foam::pow(), Foam::Re(), solidParticle::trackingData::rhoInterp(), solidParticleCloud::rhop(), particle< Type >::TrackingData< CloudType >::switchProcessor, and solidParticle::trackingData::UInterp().
Referenced by solidParticle::iNew::operator()().
bool hitPatch (const polyPatch & , trackingData & td, const label patchI, const scalar trackFraction, const tetIndices & tetIs)
Overridable function to handle the particle hitting a patch.
Executed before other patch-hitting functions
Definition at line 107 of file solidParticle.C.
References solidParticle::hitProcessorPatch().
Referenced by solidParticle::hitWallPatch(), solidParticle::move(), and solidParticle::iNew::operator()().
void hitProcessorPatch (const processorPolyPatch & , trackingData & td)
Overridable function to handle the particle hitting a.
processorPatch
Definition at line 120 of file solidParticle.C.
References solidParticle::hitWallPatch(), and particle< Type >::TrackingData< CloudType >::switchProcessor.
Referenced by solidParticle::hitPatch(), and solidParticle::iNew::operator()().
void hitWallPatch (const wallPolyPatch & wpp, trackingData & td, const tetIndices & tetIs)
Overridable function to handle the particle hitting a wallPatch.
Definition at line 130 of file solidParticle.C.
References particle< Type >::TrackingData< CloudType >::cloud(), solidParticleCloud::e(), tetIndices::faceTri(), solidParticle::hitPatch(), Foam::mag(), solidParticleCloud::mu(), triangle< Point, PointRef >::normal(), and nw.
Referenced by solidParticle::hitProcessorPatch(), and solidParticle::iNew::operator()().
void hitPatch (const polyPatch & , trackingData & td)
Overridable function to handle the particle hitting a polyPatch.
Definition at line 152 of file solidParticle.C.
References particle< Type >::TrackingData< CloudType >::keepParticle.
void transformProperties (const tensor & T) virtual
Transform the physical properties of the particle.
according to the given transformation tensor
Reimplemented from particle< Type >.
Definition at line 161 of file solidParticle.C.
References Foam::transform(), and particle< Type >::transformProperties().
Referenced by solidParticle::iNew::operator()().
void transformProperties (const vector & separation) virtual
Transform the physical properties of the particle.
according to the given separation vector
Reimplemented from particle< Type >.
Definition at line 168 of file solidParticle.C.
References particle< Type >::transformProperties().
Foam::scalar wallImpactDistance (const vector & n) const virtual
The nearest distance to a wall that.
the particle can be in the n direction
Reimplemented from particle< Type >.
Definition at line 174 of file solidParticle.C.
Referenced by solidParticle::iNew::operator()().
void readFields (Cloud< solidParticle > & c) static
Definition at line 66 of file solidParticleIO.C.
References Cloud< ParticleType >::checkFieldIOobject(), solidParticle::d(), Cloud< ParticleType >::fieldIOobject(), forAllIter, IOobject::MUST_READ, p, particle< Type >::readFields(), Cloud< ParticleType >::size(), and solidParticle::U().
Referenced by solidParticle::iNew::operator()().
void writeFields (const Cloud< solidParticle > & c) static
Definition at line 93 of file solidParticleIO.C.
References IOstream::ASCII, IOstream::check(), solidParticle::d(), Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), IOstream::format(), IOobject::NO_READ, Foam::operator<<(), p, Cloud< ParticleType >::size(), token::SPACE, solidParticle::U(), Ostream::write(), and particle< Type >::writeFields().
Referenced by solidParticle::iNew::operator()().
Friends And Related Function Documentation
friend class Cloud< solidParticle > friend
Definition at line 75 of file solidParticle.H.
Ostream& operator<< (Ostream & , const solidParticle &) friend
Referenced by solidParticle::iNew::operator()().
The documentation for this class was generated from the following files:
src/lagrangian/solidParticle/solidParticle.H
src/lagrangian/solidParticle/solidParticle.C
src/lagrangian/solidParticle/solidParticleI.H
src/lagrangian/solidParticle/solidParticleIO.C