OpenFOAM: skewCorrected< Type > Class Template Reference
skewCorrected< Type > Class Template Reference
Skewness-corrected interpolation scheme that applies an explicit correction to given scheme.
Public Member Functions
TypeName ("skewCorrected")
Runtime type information.
skewCorrected (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
skewCorrected (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from mesh, faceFlux and Istream.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the interpolation weighting factors.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > skewCorrection (const GeometricField< Type, fvPatchField, volMesh > &vf) const
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::skewCorrected< Type >
Skewness-corrected interpolation scheme that applies an explicit correction to given scheme.
Source files
skewCorrected.H
skewCorrected.C
Definition at line 53 of file skewCorrected.H.
Constructor & Destructor Documentation
skewCorrected (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 81 of file skewCorrected.H.
skewCorrected (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from mesh, faceFlux and Istream.
Definition at line 96 of file skewCorrected.H.
References skewCorrected< Type >::weights().
Member Function Documentation
TypeName ("skewCorrected< Type >")
Runtime type information.
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 114 of file skewCorrected.H.
Referenced by skewCorrected< Type >::skewCorrected().
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 122 of file skewCorrected.H.
References surfaceInterpolationScheme< Type >::mesh(), MeshObject< fvMesh, MoveableMeshObject, skewCorrectionVectors >::New(), skewCorrectionVectors::skew(), and skewCorrected< Type >::skewCorrection().
Referenced by skewCorrected< Type >::correction().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > skewCorrection (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline
Definition at line 131 of file skewCorrected.H.
References GeometricField< Type, PatchField, GeoMesh >::component(), skewCorrected< Type >::correction(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fvc::grad(), surfaceInterpolationScheme< Type >::interpolate(), surfaceInterpolationScheme< Type >::mesh(), IOobject::name(), MeshObject< fvMesh, MoveableMeshObject, skewCorrectionVectors >::New(), tmp< T >::ref(), fvMesh::time(), Time::timeName(), Foam::type(), and Foam::Zero.
Referenced by skewCorrected< Type >::corrected(), and skewCorrected< Type >::correction().
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the explicit correction to the face-interpolate.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 186 of file skewCorrected.H.
References skewCorrected< Type >::corrected(), surfaceInterpolationScheme< Type >::mesh(), MeshObject< fvMesh, MoveableMeshObject, skewCorrectionVectors >::New(), Foam::skew(), and skewCorrected< Type >::skewCorrection().
Referenced by skewCorrected< Type >::skewCorrection().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/skewCorrected/skewCorrected.H