OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfaceInterpolateFields Class Reference
This function object linearly interpolates volume fields to generate surface fields.
Public Member Functions
TypeName ("surfaceInterpolateFields")
Runtime type information.
surfaceInterpolateFields (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~surfaceInterpolateFields ()
Destructor.
virtual const word & name () const
Return name of the surfaceInterpolateFields object.
virtual void read (const dictionary &)
Read the field min/max data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Protected Member Functions
template<class Type >
void interpolateFields (PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &) const
Protected Attributes
word name_
Name of this set of surfaceInterpolateFields object.
const objectRegistry & obr_
bool active_
on/off switch
List< Tuple2< word, word > > fieldSet_
Fields to process.
PtrList< surfaceScalarField > ssf_
Locally constructed fields.
PtrList< surfaceVectorField > svf_
PtrList< surfaceSphericalTensorField > sSpheretf_
PtrList< surfaceSymmTensorField > sSymmtf_
PtrList< surfaceTensorField > stf_
Detailed Description
This function object linearly interpolates volume fields to generate surface fields.
Group grpFieldFunctionObjects
Fields are stored
every time step the field is updated with new values
at output it writes the fields
This functionObject can either be used
to calculate a new field as a post-processing step or
since the fields are registered, used in another functionObject
Example of function object specification:
surfaceInterpolateFields1
{
    type        surfaceInterpolateFields;
    functionObjectLibs ("libfieldFunctionObjects.so");
    ...
    fields      ((p pNear)(U UNear));
}
Function object usage
Property Description Required Default value
type type name: nearWallFields yes
fields list of fields with correspoding output field names yes
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
surfaceInterpolateFields.H
surfaceInterpolateFields.C
IOsurfaceInterpolateFields.H
Definition at line 105 of file surfaceInterpolateFields.H.
Constructor & Destructor Documentation
surfaceInterpolateFields (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 39 of file surfaceInterpolateFields.C.
References Foam::endl(), Foam::read(), and WarningInFunction.
~surfaceInterpolateFields () virtual
Destructor.
Definition at line 68 of file surfaceInterpolateFields.C.
Member Function Documentation
void interpolateFields (PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> & sflds) const protected
Definition at line 34 of file surfaceInterpolateFieldsTemplates.C.
References Foam::endl(), fld(), forAll, forAllConstIter(), Foam::Info, and Foam::linearInterpolate().
TypeName ("surfaceInterpolateFields")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the surfaceInterpolateFields object.
Definition at line 177 of file surfaceInterpolateFields.H.
References surfaceInterpolateFields::end(), surfaceInterpolateFields::execute(), surfaceInterpolateFields::name_, surfaceInterpolateFields::read(), surfaceInterpolateFields::timeSet(), and surfaceInterpolateFields::write().
void read (const dictionary & dict) virtual
Read the field min/max data.
Definition at line 74 of file surfaceInterpolateFields.C.
References dictionary::lookup().
Referenced by surfaceInterpolateFields::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 83 of file surfaceInterpolateFields.C.
References Foam::endl(), Foam::Info, Foam::nl, and Foam::type().
Referenced by surfaceInterpolateFields::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 107 of file surfaceInterpolateFields.C.
Referenced by surfaceInterpolateFields::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 116 of file surfaceInterpolateFields.C.
Referenced by surfaceInterpolateFields::name().
void write () virtual
Write.
Definition at line 122 of file surfaceInterpolateFields.C.
References Foam::endl(), forAll, Foam::Info, Foam::nl, and Foam::type().
Referenced by surfaceInterpolateFields::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 198 of file surfaceInterpolateFields.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 202 of file surfaceInterpolateFields.H.
Member Data Documentation
word name_ protected
Name of this set of surfaceInterpolateFields object.
Definition at line 112 of file surfaceInterpolateFields.H.
Referenced by surfaceInterpolateFields::name().
const objectRegistry& obr_ protected
Definition at line 114 of file surfaceInterpolateFields.H.
bool active_ protected
on/off switch
Definition at line 117 of file surfaceInterpolateFields.H.
List<Tuple2<word, word> > fieldSet_ protected
Fields to process.
wordList fieldSet_;
Definition at line 121 of file surfaceInterpolateFields.H.
PtrList<surfaceScalarField> ssf_ protected
Locally constructed fields.
Definition at line 124 of file surfaceInterpolateFields.H.
PtrList<surfaceVectorField> svf_ protected
Definition at line 125 of file surfaceInterpolateFields.H.
PtrList<surfaceSphericalTensorField> sSpheretf_ protected
Definition at line 126 of file surfaceInterpolateFields.H.
PtrList<surfaceSymmTensorField> sSymmtf_ protected
Definition at line 127 of file surfaceInterpolateFields.H.
PtrList<surfaceTensorField> stf_ protected
Definition at line 128 of file surfaceInterpolateFields.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/surfaceInterpolateFields/surfaceInterpolateFields.H
src/postProcessing/functionObjects/field/surfaceInterpolateFields/surfaceInterpolateFields.C
src/postProcessing/functionObjects/field/surfaceInterpolateFields/surfaceInterpolateFieldsTemplates.C