OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfaceFilmModel Class Reference abstract
Base class for surface film models.
Public Member Functions
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceFilmModel, mesh,(const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType),(modelType, mesh, g, regionType))
surfaceFilmModel (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType)
Construct from type name, mesh and gravity vector.
virtual ~surfaceFilmModel ()
Destructor.
const dimensionedVector & g () const
Return the accleration due to gravity.
virtual void addSources (const label patchI, const label faceI, const scalar massSource, const vector &momentumSource, const scalar pressureSource, const scalar energySource)=0
External hook to add sources to the film.
virtual scalar CourantNumber () const
Courant number evaluation.
virtual const volScalarField & delta () const =0
Return the film thickness [m].
virtual const volScalarField & alpha () const =0
Return the film coverage, 1 = covered, 0 = uncovered / [].
virtual const volVectorField & U () const =0
Return the film velocity [m/s].
virtual const volVectorField & Us () const =0
Return the film surface velocity [m/s].
virtual const volVectorField & Uw () const =0
Return the film wall velocity [m/s].
virtual const volScalarField & rho () const =0
Return the film density [kg/m3].
virtual const volScalarField & T () const =0
Return the film mean temperature [K].
virtual const volScalarField & Ts () const =0
Return the film surface temperature [K].
virtual const volScalarField & Tw () const =0
Return the film wall temperature [K].
virtual const volScalarField & Cp () const =0
Return the film specific heat capacity [J/kg/K].
virtual const volScalarField & kappa () const =0
Return the film thermal conductivity [W/m/K].
virtual const volScalarField & sigma () const =0
Return the film surface tension [N/m].
virtual tmp< volScalarField > primaryMassTrans () const =0
Return mass transfer source - Eulerian phase only.
virtual const volScalarField & cloudMassTrans () const =0
Return the film mass available for transfer.
virtual const volScalarField & cloudDiameterTrans () const =0
Return the parcel diameters originating from film.
virtual tmp< DimensionedField< scalar, volMesh > > Srho () const
Return total mass source - Eulerian phase only.
virtual tmp< DimensionedField< scalar, volMesh > > Srho (const label i) const
Return mass source for specie i - Eulerian phase only.
virtual tmp< DimensionedField< scalar, volMesh > > Sh () const
Return enthalpy source - Eulerian phase only.
Public Member Functions inherited from singleLayerRegion
TypeName ("regionModel")
Runtime type information.
singleLayerRegion (const fvMesh &mesh, const word &regionType)
Construct null.
singleLayerRegion (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
virtual ~singleLayerRegion ()
Destructor.
virtual const volVectorField & nHat () const
Return the patch normal vectors.
virtual const volScalarField & magSf () const
Return the face area magnitudes / [m2].
virtual const labelList & passivePatchIDs () const
Return the list of patch IDs opposite to internally.
template<class Type >
wordList mappedFieldAndInternalPatchTypes () const
Return boundary types for mapped field patches.
template<class Type >
wordList mappedPushedFieldPatchTypes () const
Return boundary types for pushed mapped field patches.
template<class Type >
Foam::wordList mappedFieldAndInternalPatchTypes () const
template<class Type >
Foam::wordList mappedPushedFieldPatchTypes () const
Public Member Functions inherited from regionModel
TypeName ("regionModel")
Runtime type information.
regionModel (const fvMesh &mesh, const word &regionType)
Construct null.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
Construct from mesh and name and dict.
virtual ~regionModel ()
Destructor.
const fvMesh & primaryMesh () const
Return the reference to the primary mesh database.
const Time & time () const
Return the reference to the time database.
const Switch & active () const
Return the active flag.
const Switch & infoOutput () const
Return the information flag.
const word & modelName () const
Return the model name.
const fvMesh & regionMesh () const
Return the region mesh database.
fvMesh & regionMesh ()
Return the region mesh database for manipulation.
const dictionary & coeffs () const
Return the model coefficients dictionary.
const dictionary & solution () const
Return the solution dictionary.
const IOdictionary & outputProperties () const
Return const access to the output properties dictionary.
IOdictionary & outputProperties ()
Return output properties dictionary.
bool isCoupledPatch (const label regionPatchI) const
Return true if patchI on the local region is a coupled.
bool isRegionPatch (const label primaryPatchI) const
Return true if patchI on the primary region is a coupled.
const labelList & primaryPatchIDs () const
Return the list of patch IDs on the primary region coupled.
const labelList & intCoupledPatchIDs () const
Return the list of patch IDs internally coupled with the.
label regionPatchID (const label primaryPatchID) const
Return region ID corresponding to primaryPatchID.
label nbrCoupledPatchID (const regionModel &nbrRegion, const label regionPatchI) const
Return the coupled patch ID paired with coupled patch.
template<class Type >
tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const Field< Type > &nbrField, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip=false) const
Map patch internal field from another region model to local.
template<class Type >
void toPrimary (const label regionPatchI, List< Type > &regionField) const
Convert a local region field to the primary region.
template<class Type >
void toRegion (const label regionPatchI, List< Type > &primaryFieldField) const
Convert a primary region field to the local region.
template<class Type , class CombineOp >
void toPrimary (const label regionPatchI, List< Type > &regionField, const CombineOp &cop) const
Convert a local region field to the primary region with op.
template<class Type , class CombineOp >
void toRegion (const label regionPatchI, List< Type > &primaryFieldField, const CombineOp &cop) const
Convert a primary region field to the local region with op.
virtual void evolve ()
Main driver routing to evolve the region - calls other evolves.
virtual void preEvolveRegion ()
Pre-evolve region.
virtual void evolveRegion ()
Evolve the region.
virtual void postEvolveRegion ()
Post-evolve region.
virtual void info ()
Provide some feedback.
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const Field< Type > &nbrField, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchI, const bool flip) const
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
iterator begin ()
const_iterator begin () const
const iterator & end ()
const const_iterator & end () const
const_iterator cbegin () const
const const_iterator & cend () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Static Public Member Functions
static autoPtr< surfaceFilmModel > New (const fvMesh &mesh, const dimensionedVector &g, const word &regionType="surfaceFilm")
Return a reference to the selected surface film model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Protected Member Functions
virtual bool read ()
Read control parameters from dictionary.
Protected Member Functions inherited from regionModel
virtual bool read (const dictionary &dict)
Read control parameters from dictionary.
virtual const AMIPatchToPatchInterpolation & interRegionAMI (const regionModel &nbrRegion, const label regionPatchI, const label nbrPatchI, const bool flip) const
Create or return a new inter-region AMI object.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
const dimensionedVector & g_
Acceleration due to gravity [m/s2].
Protected Attributes inherited from singleLayerRegion
autoPtr< volVectorField > nHatPtr_
Patch normal vectors.
autoPtr< volScalarField > magSfPtr_
Face area magnitudes / [m2].
labelList passivePatchIDs_
List of patch IDs opposite to internally coupled patches.
Protected Attributes inherited from regionModel
const fvMesh & primaryMesh_
Reference to the primary mesh database.
const Time & time_
Reference to the time database.
Switch active_
Active flag.
Switch infoOutput_
Active information output.
const word modelName_
Model name.
autoPtr< fvMesh > regionMeshPtr_
Pointer to the region mesh database.
dictionary coeffs_
Model coefficients dictionary.
autoPtr< IOdictionary > outputPropertiesPtr_
Dictionary of output properties.
labelList primaryPatchIDs_
List of patch IDs on the primary region coupled to this region.
labelList intCoupledPatchIDs_
List of patch IDs internally coupled with the primary region.
word regionName_
Region name.
regionModelFunctionObjectList functions_
Region model function objects.
wordList interRegionAMINames_
List of region names this region is coupled to.
PtrList< PtrList< AMIPatchToPatchInterpolation > > interRegionAMI_
List of AMI objects per coupled region.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase::iterator LListBase_iterator
typedef DLListBase::const_iterator LListBase_const_iterator
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Base class for surface film models.
Source files
surfaceFilmModel.H
surfaceFilmModelI.H
surfaceFilmModel.C
surfaceFilmModelNew.C
Definition at line 61 of file surfaceFilmModel.H.
Constructor & Destructor Documentation
surfaceFilmModel (const word & modelType, const fvMesh & mesh, const dimensionedVector & g, const word & regionType)
Construct from type name, mesh and gravity vector.
Definition at line 61 of file surfaceFilmModel.C.
References regionModel::active_, and surfaceFilmModel::read().
~surfaceFilmModel () virtual
Destructor.
Definition at line 80 of file surfaceFilmModel.C.
Member Function Documentation
bool read () protected virtual
Read control parameters from dictionary.
Reimplemented from singleLayerRegion.
Reimplemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
Definition at line 45 of file surfaceFilmModel.C.
References singleLayerRegion::read().
Referenced by noFilm::read(), kinematicSingleLayer::read(), and surfaceFilmModel::surfaceFilmModel().
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , surfaceFilmModel , mesh , (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType) , (modelType, mesh, g, regionType))
autoPtr< surfaceFilmModel > New (const fvMesh & mesh, const dimensionedVector & g, const word & regionType = "surfaceFilm") static
Return a reference to the selected surface film model.
Definition at line 42 of file surfaceFilmModelNew.C.
References TimePaths::constant(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, g, Foam::Info, dictionary::lookup(), mesh, IOobject::MUST_READ, Foam::nl, IOobject::NO_WRITE, and fvMesh::time().
const Foam::dimensionedVector & g () const inline
Return the accleration due to gravity.
Definition at line 39 of file surfaceFilmModelI.H.
References surfaceFilmModel::g_.
Referenced by curvatureSeparation::curvatureSeparation().
virtual void addSources (const label patchI, const label faceI, const scalar massSource, const vector & momentumSource, const scalar pressureSource, const scalar energySource) pure virtual
External hook to add sources to the film.
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
Referenced by ThermoSurfaceFilm< CloudType >::absorbInteraction().
Foam::scalar CourantNumber () const virtual
Courant number evaluation.
Reimplemented in kinematicSingleLayer.
Definition at line 86 of file surfaceFilmModel.C.
virtual const volScalarField& delta () const pure virtual
Return the film thickness [m].
Implemented in kinematicSingleLayer, and noFilm.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields(), patchInjection::correct(), and standardRadiation::Shs().
virtual const volScalarField& alpha () const pure virtual
Return the film coverage, 1 = covered, 0 = uncovered / [].
Implemented in kinematicSingleLayer, and noFilm.
Referenced by contactAngleForce::correct(), primaryRadiation::Shs(), standardRadiation::Shs(), and constantRadiation::Shs().
virtual const volVectorField& U () const pure virtual
Return the film velocity [m/s].
Implemented in kinematicSingleLayer, and noFilm.
Referenced by laminar::Us().
virtual const volVectorField& Us () const pure virtual
Return the film surface velocity [m/s].
Implemented in kinematicSingleLayer, and noFilm.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields().
virtual const volVectorField& Uw () const pure virtual
Return the film wall velocity [m/s].
Implemented in kinematicSingleLayer, and noFilm.
virtual const volScalarField& rho () const pure virtual
Return the film density [kg/m3].
Implemented in kinematicSingleLayer, and noFilm.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields(), and patchInjection::correct().
virtual const volScalarField& T () const pure virtual
Return the film mean temperature [K].
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
virtual const volScalarField& Ts () const pure virtual
Return the film surface temperature [K].
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
Referenced by ThermoSurfaceFilm< CloudType >::cacheFilmFields().
virtual const volScalarField& Tw () const pure virtual
Return the film wall temperature [K].
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
virtual const volScalarField& Cp () const pure virtual
Return the film specific heat capacity [J/kg/K].
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
Referenced by ThermoSurfaceFilm< CloudType >::cacheFilmFields().
virtual const volScalarField& kappa () const pure virtual
Return the film thermal conductivity [W/m/K].
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
virtual const volScalarField& sigma () const pure virtual
Return the film surface tension [N/m].
Implemented in kinematicSingleLayer, and noFilm.
Referenced by thermocapillaryForce::correct(), and contactAngleForce::correct().
virtual tmp<volScalarField> primaryMassTrans () const pure virtual
Return mass transfer source - Eulerian phase only.
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
virtual const volScalarField& cloudMassTrans () const pure virtual
Return the film mass available for transfer.
Implemented in kinematicSingleLayer, and noFilm.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields().
virtual const volScalarField& cloudDiameterTrans () const pure virtual
Return the parcel diameters originating from film.
Implemented in kinematicSingleLayer, and noFilm.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields().
tmp< DimensionedField< scalar, volMesh > > Srho () const virtual
Return total mass source - Eulerian phase only.
Reimplemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
Definition at line 92 of file surfaceFilmModel.C.
References NotImplemented.
tmp< DimensionedField< scalar, volMesh > > Srho (const label i) const virtual
Return mass source for specie i - Eulerian phase only.
Reimplemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
Definition at line 101 of file surfaceFilmModel.C.
References NotImplemented.
tmp< DimensionedField< scalar, volMesh > > Sh () const virtual
Return enthalpy source - Eulerian phase only.
Reimplemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
Definition at line 109 of file surfaceFilmModel.C.
References NotImplemented.
Member Data Documentation
const dimensionedVector& g_ protected
Acceleration due to gravity [m/s2].
Definition at line 82 of file surfaceFilmModel.H.
Referenced by surfaceFilmModel::g(), kinematicSingleLayer::gNorm(), kinematicSingleLayer::gNormClipped(), and kinematicSingleLayer::gTan().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/surfaceFilmModel/surfaceFilmModel.H
src/regionModels/surfaceFilmModels/surfaceFilmModel/surfaceFilmModel.C
src/regionModels/surfaceFilmModels/surfaceFilmModel/surfaceFilmModelI.H
src/regionModels/surfaceFilmModels/surfaceFilmModel/surfaceFilmModelNew.C