OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfZoneIOList Class Reference
IOobject for a surfZoneList.
Public Member Functions
TypeName ("surfZoneList")
Runtime type information.
surfZoneIOList (const IOobject &)
Construct from IOobject.
surfZoneIOList (const IOobject &, const surfZoneList &)
Construct from IOobject and surfZoneList.
surfZoneIOList (const IOobject &, const Xfer< surfZoneList > &)
Construct from IOobject and surfZoneList.
~surfZoneIOList ()
Destructor.
bool writeData (Ostream &) const
writeData member function required by regIOobject
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const List< T > &)
Copy constructor.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void operator= (const UList< T > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const T &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
void assign (const UList< T > &)
Assign elements to those from UList.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Friends
Ostream & operator<< (Ostream &, const surfZoneIOList &)
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
IOobject for a surfZoneList.
Source files
surfZoneIOList.H
surfZoneIOList.C
Definition at line 53 of file surfZoneIOList.H.
Constructor & Destructor Documentation
surfZoneIOList (const IOobject & io) explicit
Construct from IOobject.
Definition at line 39 of file surfZoneIOList.C.
References IOstream::check(), dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, dictionary::lookup(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, Foam::nl, IOobject::objectPath(), dictionary::readIfPresent(), Foam::readLabel(), List< T >::setSize(), and PtrList< T >::size().
surfZoneIOList (const IOobject & io, const surfZoneList & zones)
Construct from IOobject and surfZoneList.
Definition at line 107 of file surfZoneIOList.C.
surfZoneIOList (const IOobject & io, const Xfer< surfZoneList > & zones)
Construct from IOobject and surfZoneList.
Definition at line 118 of file surfZoneIOList.C.
~surfZoneIOList ()
Destructor.
Definition at line 130 of file surfZoneIOList.C.
Member Function Documentation
TypeName ("surfZoneList")
Runtime type information.
bool writeData (Ostream & os) const virtual
writeData member function required by regIOobject
Implements regIOobject.
Definition at line 138 of file surfZoneIOList.C.
References token::BEGIN_LIST, Foam::decrIndent(), token::END_LIST, forAll, IOstream::good(), Foam::incrIndent(), Foam::nl, Foam::operator<<(), and List< T >::size().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const surfZoneIOList &) friend
The documentation for this class was generated from the following files:
src/surfMesh/surfZone/surfZone/surfZoneIOList.H
src/surfMesh/surfZone/surfZone/surfZoneIOList.C