OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SubField< Type > Class Template Reference
Pre-declare related SubField type.
Public Types
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
SubField (const SubList< Type > &)
Construct from a SubList.
SubField (const UList< Type > &)
Construct from a UList<Type>, using the entire size.
SubField (const UList< Type > &list, const label subSize)
Construct from a UList<Type> with a given size.
SubField (const UList< Type > &list, const label subSize, const label startIndex)
Construct from a UList<Type> with a given size and start index.
SubField (const SubField< Type > &)
Construct as copy.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const SubField< Type > &)
Assignment via UList operator. Takes linear time.
void operator= (const Field< Type > &)
Assignment via UList operator. Takes linear time.
template<class Form , direction Ncmpts>
void operator= (const VectorSpace< Form, Type, Ncmpts > &)
Assignment via UList operator. Takes linear time.
operator const Field< Type > & () const
Allow cast to a const Field<Type>&.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from SubList< Type >
SubList (const UList< Type > &list, const label subSize)
Construct from UList and sub-list size.
SubList (const UList< Type > &list, const label subSize, const label startIndex)
Construct from UList, sub-list size and start index.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
void operator= (const SubList< Type > &)
Assignment of all entries to the given sub-list.
void operator= (const UList< Type > &)
Assignment of all entries to the given list.
void operator= (const Type &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static const SubField< Type > & null ()
Return a null SubField.
Static Public Member Functions inherited from SubList< Type >
static const SubList< Type > & null ()
Return a null SubList.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::SubField< Type >
Pre-declare related SubField type.
SubField is a Field obtained as a section of another Field.
Thus it is itself unallocated so that no storage is allocated or deallocated during its use. To achieve this behaviour, SubField is derived from a SubList rather than a List.
Source files
SubField.H
SubFieldI.H
Definition at line 61 of file Field.H.
Member Typedef Documentation
typedef pTraits<Type>::cmptType cmptType
Component type.
Definition at line 68 of file SubField.H.
Constructor & Destructor Documentation
SubField (const SubList< Type > & list) inline
Construct from a SubList.
Definition at line 30 of file SubFieldI.H.
Referenced by SubField< Type >::SubField().
SubField (const UList< Type > & list) inline explicit
Construct from a UList<Type>, using the entire size.
Definition at line 40 of file SubFieldI.H.
References SubField< Type >::SubField().
SubField (const UList< Type > & list, const label subSize) inline
Construct from a UList<Type> with a given size.
Definition at line 50 of file SubFieldI.H.
References SubField< Type >::SubField().
SubField (const UList< Type > & list, const label subSize, const label startIndex) inline
Construct from a UList<Type> with a given size and start index.
Definition at line 61 of file SubFieldI.H.
References SubField< Type >::SubField().
SubField (const SubField< Type > & sfield) inline
Construct as copy.
Definition at line 73 of file SubFieldI.H.
Member Function Documentation
const Foam::SubField< Type > & null () inline static
Return a null SubField.
Definition at line 85 of file SubFieldI.H.
References SubField< Type >::component().
Foam::tmp< Foam::Field< typename Foam::SubField< Type >::cmptType > > component (const direction d) const inline
Return a component field of the field.
Definition at line 94 of file SubFieldI.H.
Referenced by SubField< Type >::null().
Foam::tmp< Foam::Field< Type > > T () const inline
Return the field transpose (only defined for second rank tensors)
Definition at line 103 of file SubFieldI.H.
void operator= (const SubField< Type > & rhs) inline
Assignment via UList operator. Takes linear time.
Definition at line 112 of file SubFieldI.H.
void operator= (const Field< Type > & rhs) inline
Assignment via UList operator. Takes linear time.
Definition at line 119 of file SubFieldI.H.
void operator= (const VectorSpace< Form, Type, Ncmpts > & rhs) inline
Assignment via UList operator. Takes linear time.
Definition at line 128 of file SubFieldI.H.
References forAll.
operator const Field< Type > & () const inline
Allow cast to a const Field<Type>&.
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/Fields/Field/Field.H
src/OpenFOAM/fields/Fields/Field/SubField.H
src/OpenFOAM/fields/Fields/Field/SubFieldI.H