OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
thermalDiffusivity< TransportModel > Class Template Reference
Templated abstract base class for single-phase compressible turbulence models.
Public Types
typedef geometricOneField alphaField
typedef volScalarField rhoField
typedef TransportModel transportModel
Public Types inherited from CompressibleTurbulenceModel< TransportModel >
typedef geometricOneField alphaField
typedef volScalarField rhoField
typedef TransportModel transportModel
Public Types inherited from TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >
typedef geometricOneField alphaField
typedef volScalarField rhoField
typedef TransportModel transportModel
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase::iterator LListBase_iterator
typedef DLListBase::const_iterator LListBase_const_iterator
Public Member Functions
thermalDiffusivity (const word &type, const geometricOneField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasport, const word &propertiesName)
Construct.
virtual ~thermalDiffusivity ()
Destructor.
virtual tmp< volScalarField > kappa () const
Return the thermal diffusivity for temperature [J/m/s/K].
virtual tmp< scalarField > kappa (const label patchi) const
Return the laminar thermal diffusivity for temperature on patch.
virtual tmp< volScalarField > alpha () const
Return the laminar thermal diffusivity for enthalpy [kg/m/s].
virtual tmp< scalarField > alpha (const label patchi) const
Return the laminar thermal diffusivity for enthalpy on patch.
virtual tmp< volScalarField > alphat () const
Return the turbulent thermal diffusivity for enthalpy [kg/m/s].
virtual tmp< scalarField > alphat (const label patchi) const
Return the turbulent thermal diffusivity for enthalpy for a patch.
virtual tmp< volScalarField > kappaEff () const
Return the effective turbulent thermal diffusivity for temperature.
virtual tmp< scalarField > kappaEff (const label patchi) const
Return the effective turbulent thermal diffusivity for temperature.
virtual tmp< volScalarField > alphaEff () const
Return the effective turbulent thermal diffusivity for enthalpy.
virtual tmp< scalarField > alphaEff (const label patchi) const
Return the effective turbulent thermal diffusivity for enthalpy.
Public Member Functions inherited from CompressibleTurbulenceModel< TransportModel >
CompressibleTurbulenceModel (const word &type, const geometricOneField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasport, const word &propertiesName)
Construct.
virtual ~CompressibleTurbulenceModel ()
Destructor.
virtual tmp< volScalarField > mu () const
Return the laminar dynamic viscosity.
virtual tmp< scalarField > mu (const label patchi) const
Return the laminar dynamic viscosity on patch.
virtual tmp< volScalarField > mut () const
Return the turbulence dynamic viscosity.
virtual tmp< scalarField > mut (const label patchi) const
Return the turbulence dynamic viscosity on patch.
virtual tmp< volScalarField > muEff () const
Return the effective dynamic viscosity.
virtual tmp< scalarField > muEff (const label patchi) const
Return the effective dynamic viscosity on patch.
Public Member Functions inherited from TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >
TurbulenceModel (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct.
declareRunTimeNewSelectionTable (autoPtr, TurbulenceModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
virtual ~TurbulenceModel ()
Destructor.
const alphaField & alpha () const
Access function to phase fraction.
const transportModel & transport () const
Access function to incompressible transport model.
tmp< volScalarField > nu () const
Return the laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity on patchi.
Public Member Functions inherited from compressibleTurbulenceModel
TypeName ("compressibleTurbulenceModel")
Runtime type information.
compressibleTurbulenceModel (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const word &propertiesName)
Construct from components.
virtual ~compressibleTurbulenceModel ()
Destructor.
const volScalarField & rho () const
Return the density field.
virtual tmp< surfaceScalarField > phi () const
Return the volumetric flux field.
virtual tmp< volSymmTensorField > devRhoReff () const =0
Return the effective stress tensor including the laminar stress.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const =0
Return the source term for the momentum equation.
Public Member Functions inherited from turbulenceModel
TypeName ("turbulenceModel")
Runtime type information.
turbulenceModel (const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const word &propertiesName)
Construct from components.
virtual ~turbulenceModel ()
Destructor.
virtual bool read ()=0
Read model coefficients if they have changed.
const Time & time () const
const fvMesh & mesh () const
virtual const dictionary & coeffDict () const =0
Const access to the coefficients dictionary.
word GName () const
Helper function to return the nam eof the turbulence G field.
const volVectorField & U () const
Access function to velocity field.
const surfaceScalarField & alphaRhoPhi () const
Access function to phase flux field.
const nearWallDist & y () const
Return the near wall distances.
virtual tmp< volScalarField > nut () const =0
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const =0
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > nuEff () const =0
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const =0
Return the effective viscosity on patch.
virtual tmp< volScalarField > k () const =0
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const =0
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volSymmTensorField > R () const =0
Return the Reynolds stress tensor.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (Istream &, const INew &)
Copy constructor with additional argument for clone.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Static Public Member Functions
static autoPtr
< thermalDiffusivity > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const transportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from CompressibleTurbulenceModel< TransportModel >
static autoPtr
< CompressibleTurbulenceModel > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const transportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >
static autoPtr< TurbulenceModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Additional Inherited Members
Static Public Attributes inherited from turbulenceModel
static const word propertiesName
Default name of the turbulence properties dictionary.
Static Public Attributes inherited from regIOobject
static const NamedEnum
< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Protected Member Functions inherited from compressibleTurbulenceModel
virtual void correctNut ()
***HGW Temporary function to be removed when the run-time selectable
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes inherited from TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >
const alphaField & alpha_
const transportModel & transport_
Protected Attributes inherited from compressibleTurbulenceModel
const volScalarField & rho_
Protected Attributes inherited from turbulenceModel
const Time & runTime_
const fvMesh & mesh_
const volVectorField & U_
const surfaceScalarField & alphaRhoPhi_
const surfaceScalarField & phi_
nearWallDist y_
Near wall distance boundary field.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class TransportModel>
class Foam::thermalDiffusivity< TransportModel >
Templated abstract base class for single-phase compressible turbulence models.
Source files
thermalDiffusivity.H
thermalDiffusivity.C
Definition at line 50 of file thermalDiffusivity.H.
Member Typedef Documentation
typedef geometricOneField alphaField
Definition at line 57 of file thermalDiffusivity.H.
typedef volScalarField rhoField
Definition at line 58 of file thermalDiffusivity.H.
typedef TransportModel transportModel
Definition at line 59 of file thermalDiffusivity.H.
Constructor & Destructor Documentation
thermalDiffusivity (const word & type, const geometricOneField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & trasport, const word & propertiesName)
Construct.
Definition at line 32 of file thermalDiffusivity.C.
virtual ~thermalDiffusivity () inline virtual
Destructor.
Definition at line 92 of file thermalDiffusivity.H.
Member Function Documentation
Foam::autoPtr< Foam::thermalDiffusivity< TransportModel > > New (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const transportModel & trasportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Definition at line 62 of file thermalDiffusivity.C.
virtual tmp<volScalarField> kappa () const inline virtual
Return the thermal diffusivity for temperature [J/m/s/K].
Definition at line 99 of file thermalDiffusivity.H.
References TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >::transport_.
Referenced by thermalDiffusivity< TransportModel >::kappaEff().
virtual tmp<scalarField> kappa (const label patchi) const inline virtual
Return the laminar thermal diffusivity for temperature on patch.
[J/m/s/K]
Definition at line 106 of file thermalDiffusivity.H.
References TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >::transport_.
virtual tmp<volScalarField> alpha () const inline virtual
Return the laminar thermal diffusivity for enthalpy [kg/m/s].
Definition at line 112 of file thermalDiffusivity.H.
References TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >::transport_.
Referenced by thermalDiffusivity< TransportModel >::alphaEff(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
virtual tmp<scalarField> alpha (const label patchi) const inline virtual
Return the laminar thermal diffusivity for enthalpy on patch.
[kg/m/s]
Definition at line 119 of file thermalDiffusivity.H.
References TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >::transport_.
Foam::tmp< Foam::volScalarField > alphat () const virtual
Return the turbulent thermal diffusivity for enthalpy [kg/m/s].
Reimplemented in eddyDiffusivity< compressible::turbulenceModel >.
Definition at line 89 of file thermalDiffusivity.C.
References Foam::dimDensity, and Foam::dimViscosity.
Referenced by turbulenceFields::execute().
Foam::tmp< Foam::scalarField > alphat (const label patchi) const virtual
Return the turbulent thermal diffusivity for enthalpy for a patch.
[kg/m/s]
Reimplemented in eddyDiffusivity< compressible::turbulenceModel >.
Definition at line 113 of file thermalDiffusivity.C.
References patchi, and scalarField().
virtual tmp<volScalarField> kappaEff () const inline virtual
Return the effective turbulent thermal diffusivity for temperature.
[J/m/s/K]
Reimplemented in eddyDiffusivity< compressible::turbulenceModel >.
Definition at line 133 of file thermalDiffusivity.H.
References thermalDiffusivity< TransportModel >::kappa().
Referenced by wallHeatTransferFvPatchScalarField::updateCoeffs(), and thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs().
virtual tmp<scalarField> kappaEff (const label patchi) const inline virtual
Return the effective turbulent thermal diffusivity for temperature.
[J/m/s/K]
Reimplemented in eddyDiffusivity< compressible::turbulenceModel >.
Definition at line 140 of file thermalDiffusivity.H.
References thermalDiffusivity< TransportModel >::kappa().
virtual tmp<volScalarField> alphaEff () const inline virtual
Return the effective turbulent thermal diffusivity for enthalpy.
[kg/m/s]
Reimplemented in eddyDiffusivity< compressible::turbulenceModel >.
Definition at line 147 of file thermalDiffusivity.H.
References thermalDiffusivity< TransportModel >::alpha().
Referenced by turbulenceFields::execute(), and convectiveHeatTransferFvPatchScalarField::updateCoeffs().
virtual tmp<scalarField> alphaEff (const label patchi) const inline virtual
Return the effective turbulent thermal diffusivity for enthalpy.
for a patch [kg/m/s]
Reimplemented in eddyDiffusivity< compressible::turbulenceModel >.
Definition at line 154 of file thermalDiffusivity.H.
References thermalDiffusivity< TransportModel >::alpha().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/thermalDiffusivity/thermalDiffusivity.H
src/TurbulenceModels/compressible/thermalDiffusivity/thermalDiffusivity.C