OpenFOAM-dev: SurfaceReactionModel< CloudType > Class Template Reference 2
SurfaceReactionModel< CloudType > Class Template Reference abstract
Templated surface reaction model class.
Public Member Functions
TypeName ("surfaceReactionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, SurfaceReactionModel, dictionary,(const dictionary &dict, CloudType &cloud),(dict, cloud))
Declare runtime constructor selection table.
SurfaceReactionModel (CloudType &owner)
Construct null from owner.
SurfaceReactionModel (const dictionary &dict, CloudType &cloud, const word &type)
Construct from dictionary.
SurfaceReactionModel (const SurfaceReactionModel< CloudType > &srm)
Construct copy.
virtual autoPtr< SurfaceReactionModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~SurfaceReactionModel ()
Destructor.
virtual scalar calculate (const scalar dt, const label celli, const scalar d, const scalar T, const scalar Tc, const scalar pc, const scalar rhoc, const scalar mass, const scalarField &YGas, const scalarField &YLiquid, const scalarField &YSolid, const scalarField &YMixture, const scalar N, scalarField &dMassGas, scalarField &dMassLiquid, scalarField &dMassSolid, scalarField &dMassSRCarrier) const =0
Update surface reactions.
void addToSurfaceReactionMass (const scalar dMass)
Add to devolatilisation mass.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< SurfaceReactionModel< CloudType > > New (const dictionary &dict, CloudType &cloud)
Selector.
Protected Attributes
scalar dMass_
Mass of lagrangian phase converted.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Detailed Description
template<class CloudType>
class Foam::SurfaceReactionModel< CloudType >
Templated surface reaction model class.
Source files
SurfaceReactionModel.H
SurfaceReactionModel.C
SurfaceReactionModelNew.C
Definition at line 56 of file ReactingMultiphaseCloud.H.
Constructor & Destructor Documentation
SurfaceReactionModel (CloudType & owner)
Construct null from owner.
Definition at line 32 of file SurfaceReactionModel.C.
Referenced by SurfaceReactionModel< CloudType >::SurfaceReactionModel().
SurfaceReactionModel (const dictionary & dict, CloudType & cloud, const word & type)
Construct from dictionary.
Definition at line 43 of file SurfaceReactionModel.C.
References SurfaceReactionModel< CloudType >::SurfaceReactionModel().
SurfaceReactionModel (const SurfaceReactionModel< CloudType > & srm)
Construct copy.
Definition at line 56 of file SurfaceReactionModel.C.
~SurfaceReactionModel () virtual
Destructor.
Definition at line 68 of file SurfaceReactionModel.C.
References SurfaceReactionModel< CloudType >::addToSurfaceReactionMass().
Member Function Documentation
TypeName ("surfaceReactionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , SurfaceReactionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &cloud) , (dict, cloud))
Declare runtime constructor selection table.
virtual autoPtr<SurfaceReactionModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in COxidationMurphyShaddix< CloudType >, COxidationIntrinsicRate< CloudType >, COxidationHurtMitchell< CloudType >, COxidationKineticDiffusionLimitedRate< CloudType >, COxidationDiffusionLimitedRate< CloudType >, and NoSurfaceReaction< CloudType >.
Foam::autoPtr< Foam::SurfaceReactionModel< CloudType > > New (const dictionary & dict, CloudType & cloud) static
Selector.
Definition at line 33 of file SurfaceReactionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
virtual scalar calculate (const scalar dt, const label celli, const scalar d, const scalar T, const scalar Tc, const scalar pc, const scalar rhoc, const scalar mass, const scalarField & YGas, const scalarField & YLiquid, const scalarField & YSolid, const scalarField & YMixture, const scalar N, scalarField & dMassGas, scalarField & dMassLiquid, scalarField & dMassSolid, scalarField & dMassSRCarrier) const pure virtual
Update surface reactions.
Returns the heat of reaction
Implemented in COxidationMurphyShaddix< CloudType >, COxidationIntrinsicRate< CloudType >, COxidationHurtMitchell< CloudType >, COxidationKineticDiffusionLimitedRate< CloudType >, COxidationDiffusionLimitedRate< CloudType >, and NoSurfaceReaction< CloudType >.
void addToSurfaceReactionMass (const scalar dMass)
Add to devolatilisation mass.
Definition at line 76 of file SurfaceReactionModel.C.
Referenced by SurfaceReactionModel< CloudType >::~SurfaceReactionModel().
void info (Ostream & os) virtual
Write injection info to stream.
Definition at line 85 of file SurfaceReactionModel.C.
References Foam::Info, Foam::nl, and Foam::returnReduce().
Member Data Documentation
scalar dMass_ protected
Mass of lagrangian phase converted.
Definition at line 63 of file SurfaceReactionModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/ReactingMultiphaseCloud/ReactingMultiphaseCloud.H
src/lagrangian/intermediate/submodels/ReactingMultiphase/SurfaceReactionModel/SurfaceReactionModel/SurfaceReactionModel.H
src/lagrangian/intermediate/submodels/ReactingMultiphase/SurfaceReactionModel/SurfaceReactionModel/SurfaceReactionModel.C
src/lagrangian/intermediate/submodels/ReactingMultiphase/SurfaceReactionModel/SurfaceReactionModel/SurfaceReactionModelNew.C