OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
STLtriangle Class Reference
A triangle representation for STL files.
Public Member Functions
STLtriangle ()
Construct null.
STLtriangle (const STLpoint &normal, const STLpoint &a, const STLpoint &b, const STLpoint &c, unsigned short attrib)
Construct from components.
STLtriangle (istream &)
Construct from istream (read binary)
const STLpoint & normal () const
const STLpoint & a () const
const STLpoint & b () const
const STLpoint & c () const
unsigned short attrib () const
void read (istream &)
Read from istream (binary)
void write (ostream &)
Write to ostream (binary)
Friends
Ostream & operator<< (Ostream &, const STLtriangle &)
Detailed Description
A triangle representation for STL files.
Source files
STLtriangle.H
STLtriangleI.H
Definition at line 50 of file STLtriangle.H.
Constructor & Destructor Documentation
STLtriangle () inline
Construct null.
Definition at line 28 of file STLtriangleI.H.
STLtriangle (const STLpoint & normal, const STLpoint & a, const STLpoint & b, const STLpoint & c, unsigned short attrib) inline
Construct from components.
Definition at line 33 of file STLtriangleI.H.
STLtriangle (istream & is) inline
Construct from istream (read binary)
Definition at line 49 of file STLtriangleI.H.
References STLtriangle::read().
Member Function Documentation
const Foam::STLpoint & normal () const inline
Definition at line 57 of file STLtriangleI.H.
const Foam::STLpoint & a () const inline
Definition at line 63 of file STLtriangleI.H.
const Foam::STLpoint & b () const inline
Definition at line 69 of file STLtriangleI.H.
const Foam::STLpoint & c () const inline
Definition at line 75 of file STLtriangleI.H.
unsigned short attrib () const inline
Definition at line 81 of file STLtriangleI.H.
void read (istream & is) inline
Read from istream (binary)
Definition at line 87 of file STLtriangleI.H.
Referenced by STLtriangle::STLtriangle().
void write (ostream & os) inline
Write to ostream (binary)
Definition at line 94 of file STLtriangleI.H.
References Foam::operator<<(), and token::SPACE.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const STLtriangle &) friend
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/stl/STLtriangle.H
src/surfMesh/surfaceFormats/stl/STLtriangleI.H