OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
sweepData Class Reference
Helper class used by fvc::sweep function.
Public Member Functions
sweepData ()
Construct null.
sweepData (const scalar value, const point &origin)
Construct from component.
scalar value () const
Return value.
const point & origin () const
Return origin.
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const sweepData &, const scalar, TrackingData &td) const
Check for identical geometrical data.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFaceI, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCellI, const label neighbourFaceI, const sweepData &svf, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const label neighbourCellI, const sweepData &svf, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFaceI, const sweepData &svf, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const sweepData &, TrackingData &td) const
Same (like operator==)
void operator= (const scalar value)
bool operator== (const sweepData &) const
bool operator!= (const sweepData &) const
Friends
Ostream & operator<< (Ostream &os, const sweepData &svf)
Istream & operator>> (Istream &is, sweepData &svf)
Detailed Description
Helper class used by fvc::sweep function.
Source files
sweepData.H
sweepData.H
sweepDataI.H
Definition at line 47 of file sweepData.H.
Constructor & Destructor Documentation
sweepData () inline
Construct null.
Definition at line 74 of file sweepDataI.H.
sweepData (const scalar value, const point & origin) inline
Construct from component.
Definition at line 81 of file sweepDataI.H.
Member Function Documentation
scalar value () const inline
Return value.
Definition at line 82 of file sweepData.H.
const point& origin () const inline
Return origin.
Definition at line 88 of file sweepData.H.
Referenced by sweepData::operator==().
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value
Definition at line 91 of file sweepDataI.H.
bool sameGeometry (const polyMesh & , const sweepData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data.
Used for cyclics checking
Definition at line 99 of file sweepDataI.H.
void leaveDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to.
(patch)face centre
Definition at line 112 of file sweepDataI.H.
void enterDomain (const polyMesh & , const polyPatch & , const label patchFaceI, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 138 of file sweepDataI.H.
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 126 of file sweepDataI.H.
References Foam::transform().
bool updateCell (const polyMesh & mesh, const label thisCellI, const label neighbourFaceI, const sweepData & svf, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 153 of file sweepDataI.H.
References primitiveMesh::cellCentres().
bool updateFace (const polyMesh & mesh, const label thisFaceI, const label neighbourCellI, const sweepData & svf, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 168 of file sweepDataI.H.
References primitiveMesh::faceCentres().
bool updateFace (const polyMesh & mesh, const label thisFaceI, const sweepData & svf, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 184 of file sweepDataI.H.
References primitiveMesh::faceCentres().
bool equal (const sweepData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 198 of file sweepDataI.H.
References Foam::operator==().
void operator= (const scalar value) inline
Definition at line 210 of file sweepDataI.H.
bool operator== (const sweepData & rhs) const inline
Definition at line 219 of file sweepDataI.H.
References sweepData::origin().
bool operator!= (const sweepData & rhs) const inline
Definition at line 228 of file sweepDataI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const sweepData & svf) friend
Definition at line 197 of file sweepData.H.
Istream& operator>> (Istream & is, sweepData & svf) friend
Definition at line 205 of file sweepData.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/fvc/fvcSmooth/sweepData.H
src/finiteVolume/finiteVolume/fvc/fvcSmooth/sweepDataI.H