OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
StochasticCollisionModel< CloudType > Class Template Reference abstract
Templated stochastic collision model class.
Public Member Functions
TypeName ("collisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, StochasticCollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
StochasticCollisionModel (CloudType &owner)
Construct null from owner.
StochasticCollisionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
StochasticCollisionModel (const StochasticCollisionModel< CloudType > &cm)
Construct copy.
virtual autoPtr< StochasticCollisionModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~StochasticCollisionModel ()
Destructor.
void update (const scalar dt)
Update the model.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool outputTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< StochasticCollisionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions
virtual void collide (const scalar dt)=0
Main collision routine.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::StochasticCollisionModel< CloudType >
Templated stochastic collision model class.
Source files
StochasticCollisionModel.H
StochasticCollisionModel.C
StochasticCollisionModelNew.C
Definition at line 88 of file KinematicCloud.H.
Constructor & Destructor Documentation
StochasticCollisionModel (CloudType & owner)
Construct null from owner.
Definition at line 32 of file StochasticCollisionModel.C.
Referenced by StochasticCollisionModel< CloudType >::StochasticCollisionModel().
StochasticCollisionModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from dictionary.
Definition at line 52 of file StochasticCollisionModel.C.
StochasticCollisionModel (const StochasticCollisionModel< CloudType > & cm)
Construct copy.
Definition at line 42 of file StochasticCollisionModel.C.
References StochasticCollisionModel< CloudType >::StochasticCollisionModel().
~StochasticCollisionModel () virtual
Destructor.
Definition at line 65 of file StochasticCollisionModel.C.
Member Function Documentation
virtual void collide (const scalar dt) protected pure virtual
Main collision routine.
Implemented in ORourkeCollision< CloudType >, TrajectoryCollision< CloudType >, SuppressionCollision< CloudType >, and NoStochasticCollision< CloudType >.
TypeName ("collisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , StochasticCollisionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
virtual autoPtr<StochasticCollisionModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in ORourkeCollision< CloudType >, TrajectoryCollision< CloudType >, SuppressionCollision< CloudType >, and NoStochasticCollision< CloudType >.
Foam::autoPtr< Foam::StochasticCollisionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file StochasticCollisionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
void update (const scalar dt)
Update the model.
Definition at line 72 of file StochasticCollisionModel.C.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.H
src/lagrangian/intermediate/submodels/Kinematic/StochasticCollision/StochasticCollisionModel/StochasticCollisionModel.H
src/lagrangian/intermediate/submodels/Kinematic/StochasticCollision/StochasticCollisionModel/StochasticCollisionModel.C
src/lagrangian/intermediate/submodels/Kinematic/StochasticCollision/StochasticCollisionModel/StochasticCollisionModelNew.C