OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
TableBase< Type > Class Template Reference
Base class for table with bounds handling, interpolation and integration.
Public Types
enum boundsHandling { ERROR, WARN, CLAMP, REPEAT }
Enumeration for handling out-of-bound values.
Public Member Functions
TableBase (const word &name, const dictionary &dict)
Construct from dictionary - note table is not populated.
TableBase (const TableBase< Type > &tbl)
Copy constructor. Note: steals interpolator, tableSamples.
virtual ~TableBase ()
Destructor.
word boundsHandlingToWord (const boundsHandling &bound) const
Return the out-of-bounds handling as a word.
boundsHandling wordToBoundsHandling (const word &bound) const
Return the out-of-bounds handling as an enumeration.
boundsHandling outOfBounds (const boundsHandling &bound)
Set the out-of-bounds handling from enum, return previous setting.
void check () const
Check the table for size and consistency.
bool checkMinBounds (const scalar x, scalar &xDash) const
Check minimum table bounds.
bool checkMaxBounds (const scalar x, scalar &xDash) const
Check maximum table bounds.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return Table value.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual dimensioned< Type > dimValue (const scalar x) const
Return dimensioned constant value.
virtual dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const
Integrate between two values and return dimensioned type.
virtual tmp< scalarField > x () const
Return the reference values.
virtual tmp< Field< Type > > y () const
Return the dependent values.
virtual void writeData (Ostream &os) const
Write all table data in dictionary format.
virtual void writeEntries (Ostream &os) const
Write keywords only in dictionary format. Used for non-inline.
Public Member Functions inherited from DataEntry< Type >
TypeName ("DataEntry") declareRunTimeSelectionTable(autoPtr
Runtime type information.
DataEntry (const word &entryName)
Construct from entry name.
DataEntry (const DataEntry< Type > &de)
Copy constructor.
virtual tmp< DataEntry< Type > > clone () const
Construct and return a clone.
virtual ~DataEntry ()
Destructor.
const word & name () const
Return the name of the entry.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
virtual tmp< Field< dimensioned< Type > > > dimValue (const scalarField &x) const
Return dimensioned type as a function of (scalar)
virtual tmp< Field< dimensioned< Type > > > dimIntegrate (const scalarField &x1, const scalarField &x2) const
Integrate between two scalar fields and return a field of.
Public Member Functions inherited from refCount
refCount ()
Construct null with zero count.
int count () const
Return the reference count.
bool okToDelete () const
Return true if the reference count is zero.
void resetRefCount ()
Reset the reference count to zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Protected Member Functions
const interpolationWeights & interpolator () const
Return (demand driven) interpolator.
void operator= (const TableBase< Type > &)
Disallow default bitwise assignment.
Protected Attributes
const word name_
Table name.
const boundsHandling boundsHandling_
Enumeration for handling out-of-bound values.
const word interpolationScheme_
Interpolation type.
List< Tuple2< scalar, Type > > table_
Table data.
dimensionSet dimensions_
The dimension set.
autoPtr< scalarField > tableSamplesPtr_
Extracted values.
autoPtr< interpolationWeights > interpolatorPtr_
Interpolator method.
labelList currentIndices_
Cached indices and weights.
scalarField currentWeights_
Protected Attributes inherited from DataEntry< Type >
const word name_
Name of entry.
Friends
Ostream & operator (Ostream &os, const TableBase< Type > &tbl)
Ostream Operator.
Additional Inherited Members
Static Public Member Functions inherited from DataEntry< Type >
static autoPtr< DataEntry< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from DataEntry< Type >
DataEntry
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Detailed Description
template<class Type>
class Foam::TableBase< Type >
Base class for table with bounds handling, interpolation and integration.
Source files
TableBase.H
TableBase.C
Definition at line 47 of file TableBase.H.
Member Enumeration Documentation
enum boundsHandling
Enumeration for handling out-of-bound values.
Enumerator
ERROR
Exit with a FatalError
WARN
Issue warning and clamp value (default)
CLAMP
Clamp value to the start/end value
REPEAT
Treat as a repeating list
Definition at line 72 of file TableBase.H.
Constructor & Destructor Documentation
TableBase (const word & name, const dictionary & dict)
Construct from dictionary - note table is not populated.
Definition at line 58 of file TableBase.C.
TableBase (const TableBase< Type > & tbl)
Copy constructor. Note: steals interpolator, tableSamples.
Definition at line 79 of file TableBase.C.
~TableBase () virtual
Destructor.
Definition at line 95 of file TableBase.C.
Member Function Documentation
const Foam::interpolationWeights & interpolator () const protected
Return (demand driven) interpolator.
Definition at line 33 of file TableBase.C.
References UList< T >::first(), forAll, and scalarField().
void operator= (const TableBase< Type > &) protected
Disallow default bitwise assignment.
Foam::word boundsHandlingToWord (const boundsHandling & bound) const
Return the out-of-bounds handling as a word.
Definition at line 103 of file TableBase.C.
Foam::TableBase< Type >::boundsHandling wordToBoundsHandling (const word & bound) const
Return the out-of-bounds handling as an enumeration.
Definition at line 140 of file TableBase.C.
References Foam::endl(), and WarningIn.
Foam::TableBase< Type >::boundsHandling outOfBounds (const boundsHandling & bound)
Set the out-of-bounds handling from enum, return previous setting.
Definition at line 174 of file TableBase.C.
References Foam::bound().
void check () const
Check the table for size and consistency.
Definition at line 186 of file TableBase.C.
References Foam::exit(), Foam::FatalError, FatalErrorIn, n, and Foam::nl.
Referenced by Table< Type >::Table(), and TableFile< Type >::TableFile().
bool checkMinBounds (const scalar x, scalar & xDash) const
Check minimum table bounds.
Definition at line 216 of file TableBase.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::nl, WarningIn, and x.
bool checkMaxBounds (const scalar x, scalar & xDash) const
Check maximum table bounds.
Definition at line 278 of file TableBase.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::nl, WarningIn, and x.
void convertTimeBase (const Time & t) virtual
Convert time.
Reimplemented from DataEntry< Type >.
Definition at line 339 of file TableBase.C.
References forAll, and TimeState::userTimeToTime().
Type value (const scalar x) const virtual
Return Table value.
Reimplemented from DataEntry< Type >.
Definition at line 353 of file TableBase.C.
References x.
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Reimplemented from DataEntry< Type >.
Definition at line 381 of file TableBase.C.
References Foam::sum().
Foam::dimensioned< Type > dimValue (const scalar x) const virtual
Return dimensioned constant value.
Reimplemented from DataEntry< Type >.
Definition at line 398 of file TableBase.C.
Foam::dimensioned< Type > dimIntegrate (const scalar x1, const scalar x2) const virtual
Integrate between two values and return dimensioned type.
Reimplemented from DataEntry< Type >.
Definition at line 406 of file TableBase.C.
Foam::tmp< Foam::scalarField > x () const virtual
Return the reference values.
Definition at line 420 of file TableBase.C.
References fld(), and forAll.
Foam::tmp< Foam::Field< Type > > y () const virtual
Return the dependent values.
Definition at line 435 of file TableBase.C.
References fld(), and forAll.
void writeData (Ostream & os) const virtual
Write all table data in dictionary format.
Reimplemented from DataEntry< Type >.
Reimplemented in CSV< Type >, and TableFile< Type >.
Definition at line 63 of file TableBaseIO.C.
References Foam::indent(), Foam::nl, and writeData().
void writeEntries (Ostream & os) const virtual
Write keywords only in dictionary format. Used for non-inline.
table types
Definition at line 72 of file TableBaseIO.C.
References Foam::nl, and Ostream::writeKeyword().
Friends And Related Function Documentation
Ostream& operator (Ostream & os, const TableBase< Type > & tbl) friend
Ostream Operator.
Member Data Documentation
const word name_ protected
Table name.
Definition at line 86 of file TableBase.H.
const boundsHandling boundsHandling_ protected
Enumeration for handling out-of-bound values.
Definition at line 89 of file TableBase.H.
const word interpolationScheme_ protected
Interpolation type.
Definition at line 92 of file TableBase.H.
List<Tuple2<scalar, Type> > table_ protected
Table data.
Definition at line 95 of file TableBase.H.
Referenced by Table< Type >::Table(), and TableFile< Type >::TableFile().
dimensionSet dimensions_ protected
The dimension set.
Definition at line 98 of file TableBase.H.
Referenced by Table< Type >::Table(), and TableFile< Type >::TableFile().
autoPtr<scalarField> tableSamplesPtr_ mutable protected
Extracted values.
Definition at line 101 of file TableBase.H.
autoPtr<interpolationWeights> interpolatorPtr_ mutable protected
Interpolator method.
Definition at line 104 of file TableBase.H.
labelList currentIndices_ mutable protected
Cached indices and weights.
Definition at line 107 of file TableBase.H.
scalarField currentWeights_ mutable protected
Definition at line 109 of file TableBase.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/DataEntry/Table/TableBase.H
src/OpenFOAM/primitives/functions/DataEntry/Table/TableBase.C
src/OpenFOAM/primitives/functions/DataEntry/Table/TableBaseIO.C