OpenFOAM-dev: SurfaceFilmModel< CloudType > Class Template Reference 2
SurfaceFilmModel< CloudType > Class Template Reference abstract
Templated wall surface film model class.
Public Member Functions
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, SurfaceFilmModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
SurfaceFilmModel (CloudType &owner)
Construct null from owner.
SurfaceFilmModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
SurfaceFilmModel (const SurfaceFilmModel< CloudType > &sfm)
Construct copy.
virtual autoPtr< SurfaceFilmModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~SurfaceFilmModel ()
Destructor.
const dimensionedVector & g () const
Return gravitational acceleration constant.
label nParcelsTransferred () const
Return const access to the number of parcels transferred to the.
label & nParcelsTransferred ()
Return non-const access to the number of parcels transferred to.
label nParcelsInjected () const
Return const access to the number of parcels injected from the.
label & nParcelsInjected ()
Return non-const access to the number of parcels injected from.
virtual bool transferParcel (parcelType &p, const polyPatch &pp, bool &keepParticle)=0
Transfer parcel from cloud to surface film.
template<class TrackData >
void inject (TrackData &td)
Inject parcels into the cloud.
virtual void info (Ostream &os)
Write surface film info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< SurfaceFilmModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Types
typedef CloudType::parcelType parcelType
Convenience typedef to the cloud's parcel type.
Protected Member Functions
virtual void cacheFilmFields (const label filmPatchi, const label primaryPatchi, const regionModels::surfaceFilmModels::surfaceFilmModel &filmModel)
Cache the film fields in preparation for injection.
virtual void setParcelProperties (parcelType &p, const label filmFacei) const
Set the individual parcel properties.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
const dimensionedVector & g_
Gravitational acceleration constant.
label ejectedParcelType_
Ejected parcel type label - id assigned to identify parcel for.
scalarList massParcelPatch_
Parcel mass / patch face.
scalarList diameterParcelPatch_
Parcel diameter / patch face.
List< vector > UFilmPatch_
Film velocity / patch face.
scalarList rhoFilmPatch_
Film density / patch face.
scalarListList deltaFilmPatch_
Film height of all film patches / patch face.
label nParcelsTransferred_
Number of parcels transferred to the film model.
label nParcelsInjected_
Number of parcels injected from the film model.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Detailed Description
template<class CloudType>
class Foam::SurfaceFilmModel< CloudType >
Templated wall surface film model class.
Source files
SurfaceFilmModel.H
SurfaceFilmModel.C
SurfaceFilmModelNew.C
Definition at line 85 of file KinematicCloud.H.
Member Typedef Documentation
typedef CloudType::parcelType parcelType protected
Convenience typedef to the cloud's parcel type.
Definition at line 71 of file SurfaceFilmModel.H.
Constructor & Destructor Documentation
SurfaceFilmModel (CloudType & owner)
Construct null from owner.
Definition at line 35 of file SurfaceFilmModel.C.
Referenced by SurfaceFilmModel< CloudType >::SurfaceFilmModel().
SurfaceFilmModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from components.
Definition at line 52 of file SurfaceFilmModel.C.
References SurfaceFilmModel< CloudType >::SurfaceFilmModel().
SurfaceFilmModel (const SurfaceFilmModel< CloudType > & sfm)
Construct copy.
Definition at line 76 of file SurfaceFilmModel.C.
~SurfaceFilmModel () virtual
Destructor.
Definition at line 96 of file SurfaceFilmModel.C.
Member Function Documentation
void cacheFilmFields (const label filmPatchi, const label primaryPatchi, const regionModels::surfaceFilmModels::surfaceFilmModel & filmModel) protected virtual
Cache the film fields in preparation for injection.
Reimplemented in ThermoSurfaceFilm< CloudType >.
Definition at line 207 of file SurfaceFilmModel.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), surfaceFilmModel::cloudDiameterTrans(), surfaceFilmModel::cloudMassTrans(), surfaceFilmModel::delta(), SurfaceFilmModel< CloudType >::deltaFilmPatch_, SurfaceFilmModel< CloudType >::diameterParcelPatch_, SurfaceFilmModel< CloudType >::massParcelPatch_, surfaceFilmModel::rho(), SurfaceFilmModel< CloudType >::rhoFilmPatch_, SurfaceFilmModel< CloudType >::setParcelProperties(), regionModel::toPrimary(), SurfaceFilmModel< CloudType >::UFilmPatch_, and surfaceFilmModel::Us().
Referenced by ThermoSurfaceFilm< CloudType >::cacheFilmFields(), and SurfaceFilmModel< CloudType >::inject().
void setParcelProperties (parcelType & p, const label filmFacei) const protected virtual
Set the individual parcel properties.
Reimplemented in ThermoSurfaceFilm< CloudType >, and NoSurfaceFilm< CloudType >.
Definition at line 234 of file SurfaceFilmModel.C.
References SurfaceFilmModel< CloudType >::diameterParcelPatch_, SurfaceFilmModel< CloudType >::ejectedParcelType_, SurfaceFilmModel< CloudType >::massParcelPatch_, Foam::constant::mathematical::pi(), Foam::pow3(), SurfaceFilmModel< CloudType >::rhoFilmPatch_, and SurfaceFilmModel< CloudType >::UFilmPatch_.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields(), SurfaceFilmModel< CloudType >::inject(), and ThermoSurfaceFilm< CloudType >::setParcelProperties().
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , SurfaceFilmModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
virtual autoPtr<SurfaceFilmModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in ThermoSurfaceFilm< CloudType >, and NoSurfaceFilm< CloudType >.
Foam::autoPtr< Foam::SurfaceFilmModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file SurfaceFilmModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
const Foam::dimensionedVector & g () const inline
Return gravitational acceleration constant.
Definition at line 31 of file SurfaceFilmModelI.H.
Foam::label nParcelsTransferred () const inline
Return const access to the number of parcels transferred to the.
film model
Definition at line 45 of file SurfaceFilmModelI.H.
Foam::label & nParcelsTransferred () inline
Return non-const access to the number of parcels transferred to.
the film model
Definition at line 38 of file SurfaceFilmModelI.H.
Foam::label nParcelsInjected () const inline
Return const access to the number of parcels injected from the.
film model
Definition at line 59 of file SurfaceFilmModelI.H.
Foam::label & nParcelsInjected () inline
Return non-const access to the number of parcels injected from.
the film model
Definition at line 52 of file SurfaceFilmModelI.H.
virtual bool transferParcel (parcelType & p, const polyPatch & pp, bool & keepParticle) pure virtual
Transfer parcel from cloud to surface film.
Returns true if parcel is to be transferred
Implemented in ThermoSurfaceFilm< CloudType >, and NoSurfaceFilm< CloudType >.
void inject (TrackData & td)
Inject parcels into the cloud.
Definition at line 104 of file SurfaceFilmModel.C.
References subModelBase::active(), regionModel::active(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), fvMesh::C(), SurfaceFilmModel< CloudType >::cacheFilmFields(), primitiveMesh::cells(), SurfaceFilmModel< CloudType >::deltaFilmPatch_, SurfaceFilmModel< CloudType >::diameterParcelPatch_, forAll, regionModel::intCoupledPatchIDs(), fvMesh::magSf(), Foam::max(), mesh, DSMCCloud< ParcelType >::mesh(), SurfaceFilmModel< CloudType >::nParcelsInjected_, CloudSubModelBase< CloudType >::owner(), Foam::pos(), regionModel::primaryPatchIDs(), SurfaceFilmModel< CloudType >::setParcelProperties(), fvMesh::Sf(), and fvMesh::time().
void info (Ostream & os) virtual
Write surface film info to stream.
Reimplemented in ThermoSurfaceFilm< CloudType >, and NoSurfaceFilm< CloudType >.
Definition at line 255 of file SurfaceFilmModel.C.
References Foam::endl(), Foam::nl, SurfaceFilmModel< CloudType >::nParcelsInjected_, SurfaceFilmModel< CloudType >::nParcelsTransferred_, Foam::returnReduce(), subModelBase::setModelProperty(), and CloudSubModelBase< CloudType >::writeTime().
Referenced by ThermoSurfaceFilm< CloudType >::info().
Member Data Documentation
const dimensionedVector& g_ protected
Gravitational acceleration constant.
Definition at line 74 of file SurfaceFilmModel.H.
label ejectedParcelType_ protected
Ejected parcel type label - id assigned to identify parcel for.
post-processing. If not specified, defaults to originating cloud type
Definition at line 79 of file SurfaceFilmModel.H.
Referenced by SurfaceFilmModel< CloudType >::setParcelProperties().
scalarList massParcelPatch_ protected
Parcel mass / patch face.
Definition at line 85 of file SurfaceFilmModel.H.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields(), and SurfaceFilmModel< CloudType >::setParcelProperties().
scalarList diameterParcelPatch_ protected
Parcel diameter / patch face.
Definition at line 88 of file SurfaceFilmModel.H.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields(), SurfaceFilmModel< CloudType >::inject(), and SurfaceFilmModel< CloudType >::setParcelProperties().
List<vector> UFilmPatch_ protected
Film velocity / patch face.
Definition at line 91 of file SurfaceFilmModel.H.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields(), and SurfaceFilmModel< CloudType >::setParcelProperties().
scalarList rhoFilmPatch_ protected
Film density / patch face.
Definition at line 94 of file SurfaceFilmModel.H.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields(), and SurfaceFilmModel< CloudType >::setParcelProperties().
scalarListList deltaFilmPatch_ protected
Film height of all film patches / patch face.
Definition at line 97 of file SurfaceFilmModel.H.
Referenced by SurfaceFilmModel< CloudType >::cacheFilmFields(), and SurfaceFilmModel< CloudType >::inject().
label nParcelsTransferred_ protected
Number of parcels transferred to the film model.
Definition at line 103 of file SurfaceFilmModel.H.
Referenced by SurfaceFilmModel< CloudType >::info().
label nParcelsInjected_ protected
Number of parcels injected from the film model.
Definition at line 106 of file SurfaceFilmModel.H.
Referenced by SurfaceFilmModel< CloudType >::info(), and SurfaceFilmModel< CloudType >::inject().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.H
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/SurfaceFilmModel/SurfaceFilmModel.H
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/SurfaceFilmModel/SurfaceFilmModel.C
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/SurfaceFilmModel/SurfaceFilmModelI.H
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/SurfaceFilmModel/SurfaceFilmModelNew.C