OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SquareMatrix< Type > Class Template Reference
A templated 2D square matrix of objects of <T>, where the n x n matrix dimension is known and used for subscript bounds checking, etc.
Public Member Functions
SquareMatrix ()
Null constructor.
SquareMatrix (const label n)
Construct given number of rows/columns.
template<class MatrixType >
SquareMatrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
template<class MatrixType >
SquareMatrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
SquareMatrix (const label n, const zero)
Construct given number of rows/columns.
SquareMatrix (const label m, const label n, const zero)
Construct given number of rows and columns (checked to be equal)
SquareMatrix (const label n, const Identity< Type >)
Construct given number of rows/columns.
SquareMatrix (const label n, const Type &)
Construct with given number of rows and rows.
SquareMatrix (const RectangularMatrix< Type > &)
Construct as copy of a RectangularMatrix.
SquareMatrix (Istream &)
Construct from Istream.
autoPtr< SquareMatrix< Type > > clone () const
Clone.
void setSize (const label m)
Resize the matrix preserving the elements.
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Identity< Type >)
Assignment elements to the.
Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label m, const label n)
Construct given number of rows and columns.
Matrix (const label m, const label n, const zero)
Construct with given number of rows and columns.
Matrix (const label m, const label n, const Type &)
Construct with given number of rows and columns.
Matrix (const mType &)
Copy constructor.
Matrix (const Matrix< Form2, Type > &)
Copy constructor from matrix of a different form.
Matrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (Istream &)
Construct from Istream.
autoPtr< mType > clone () const
Clone.
~Matrix ()
Destructor.
label m () const
Return the number of rows.
label n () const
Return the number of columns.
label size () const
Return the number of elements in matrix (m*n)
const Type * v () const
Return element vector of the constant Matrix.
Type * v ()
Return element vector of the Matrix.
ConstMatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart) const
ConstMatrixBlock< mType > block (const label mStart, const label nStart) const
MatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart)
MatrixBlock< mType > block (const label mStart, const label nStart)
ConstMatrixBlock< mType > col (const label m, const label rowStart) const
ConstMatrixBlock< mType > col (const label m, const label mStart, const label nStart) const
MatrixBlock< mType > col (const label m, const label rowStart)
MatrixBlock< mType > col (const label m, const label mStart, const label nStart)
void checki (const label i) const
Check index i is within valid range (0 ... m-1).
void checkj (const label j) const
Check index j is within valid range (0 ... n-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (mType &)
Transfer the contents of the argument Matrix into this Matrix.
void setSize (const label m, const label n)
Resize the matrix preserving the elements.
SquareMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
const Type & operator() (const label i, const label j) const
(i, j) const element access operator
Type & operator() (const label i, const label j)
(i, j) element access operator
void operator= (const mType &)
Assignment operator. Takes linear time.
void operator= (const ConstMatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const MatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Type &)
Assignment of all elements to the given value.
Additional Inherited Members
Public Types inherited from Matrix< SquareMatrix< Type >, Type >
typedef Matrix< SquareMatrix< Type >, Type > mType
Matrix type.
typedef Type cmptType
Component type.
Static Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
static const mType & null ()
Return a null Matrix.
Detailed Description
template<class Type>
class Foam::SquareMatrix< Type >
A templated 2D square matrix of objects of <T>, where the n x n matrix dimension is known and used for subscript bounds checking, etc.
Source files
SquareMatrix.H
SquareMatrixI.H
SquareMatrix.C
Definition at line 58 of file SquareMatrix.H.
Constructor & Destructor Documentation
SquareMatrix () inline
Null constructor.
Definition at line 29 of file SquareMatrixI.H.
Referenced by SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const label n) inline
Construct given number of rows/columns.
Definition at line 36 of file SquareMatrixI.H.
References SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const ConstMatrixBlock< MatrixType > & block) inline
Construct from a block of another matrix.
Definition at line 45 of file SquareMatrixI.H.
References SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const MatrixBlock< MatrixType > & block) inline
Construct from a block of another matrix.
Definition at line 56 of file SquareMatrixI.H.
References SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const label n, const zero) inline
Construct given number of rows/columns.
initializing all elements to zero
Definition at line 66 of file SquareMatrixI.H.
References SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const label m, const label n, const zero) inline
Construct given number of rows and columns (checked to be equal)
initializing all elements to zero
Definition at line 77 of file SquareMatrixI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const label n, const Identity< Type >) inline
Construct given number of rows/columns.
Initializing to the identity matrix
Definition at line 97 of file SquareMatrixI.H.
References Foam::I, Matrix< SquareMatrix< Type >, Type >::n(), Matrix< SquareMatrix< Type >, Type >::operator()(), and SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const label n, const Type & t) inline
Construct with given number of rows and rows.
initializing all elements to the given value
Definition at line 113 of file SquareMatrixI.H.
References SquareMatrix< Type >::SquareMatrix().
SquareMatrix (const RectangularMatrix< Type > & RM) inline explicit
Construct as copy of a RectangularMatrix.
which is checked to be square
Definition at line 124 of file SquareMatrixI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Matrix< SquareMatrix< Type >, Type >::m(), Matrix< SquareMatrix< Type >, Type >::n(), and Foam::nl.
SquareMatrix (Istream & is) inline
Construct from Istream.
Definition at line 141 of file SquareMatrixI.H.
Member Function Documentation
Foam::autoPtr< Foam::SquareMatrix< Type > > clone () const inline
Clone.
Definition at line 149 of file SquareMatrixI.H.
void setSize (const label m) inline
Resize the matrix preserving the elements.
Definition at line 158 of file SquareMatrixI.H.
void operator= (const zero)
Assignment of all elements to zero.
Definition at line 167 of file SquareMatrixI.H.
References Matrix< SquareMatrix< Type >, Type >::operator, and Foam::Zero.
void operator= (const Identity< Type >)
Assignment elements to the.
Definition at line 174 of file SquareMatrixI.H.
References Foam::I, Matrix< SquareMatrix< Type >, Type >::n(), Matrix< SquareMatrix< Type >, Type >::operator, Matrix< SquareMatrix< Type >, Type >::operator()(), Foam::symmOuter(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/SquareMatrix/SquareMatrix.H
src/OpenFOAM/matrices/SquareMatrix/SquareMatrixI.H