OpenFOAM: Stochastic< CloudType > Class Template Reference
Stochastic< CloudType > Class Template Reference
Stochastic return-to-isotropy model.
Public Member Functions
TypeName ("stochastic")
Runtime type information.
Stochastic (const dictionary &dict, CloudType &owner)
Construct from components.
Stochastic (const Stochastic< CloudType > &cm)
Construct copy.
virtual autoPtr< IsotropyModel< CloudType > > clone () const
Construct and return a clone.
virtual ~Stochastic ()
Destructor.
virtual void calculate ()
Member Functions.
Public Member Functions inherited from IsotropyModel< CloudType >
TypeName ("isotropyModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IsotropyModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
IsotropyModel (CloudType &owner)
Construct null from owner.
IsotropyModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
IsotropyModel (const IsotropyModel< CloudType > &cm)
Construct a copy.
virtual ~IsotropyModel ()
Destructor.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from IsotropyModel< CloudType >
static autoPtr< IsotropyModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from IsotropyModel< CloudType >
autoPtr< TimeScaleModel > timeScaleModel_
Time scale model.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::IsotropyModels::Stochastic< CloudType >
Stochastic return-to-isotropy model.
Particle velocities are modified by sampling a gaussian-plus-delta distribution, which depends on a time-scale. This randomises some particle velocities whilst leaving others unchanged. The lower the value of the time-scale, the greater the proportion of particle velocities affected.
A correction step is performed at the end to ensure that the model conserves both momentum and granular temperature.
Reference:
    "Inclusion of collisional return-to-isotropy in the MP-PIC method"
    P O'Rourke and D Snider
    Chemical Engineering Science
    Volume 80, Issue 0, Pages 39-54, December 2012
Source files
Stochastic.H
Stochastic.C
Definition at line 67 of file Stochastic.H.
Constructor & Destructor Documentation
Stochastic (const dictionary & dict, CloudType & owner)
Construct from components.
Definition at line 32 of file Stochastic.C.
Stochastic (const Stochastic< CloudType > & cm)
Construct copy.
Definition at line 43 of file Stochastic.C.
~Stochastic () virtual
Destructor.
Definition at line 54 of file Stochastic.C.
References f(), Foam::log(), rndGen(), cachedRandom::sample01(), Foam::sqrt(), x, and y.
Referenced by Stochastic< CloudType >::clone().
Member Function Documentation
TypeName ("stochastic")
Runtime type information.
virtual autoPtr<IsotropyModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements IsotropyModel< CloudType >.
Definition at line 93 of file Stochastic.H.
References Stochastic< CloudType >::calculate(), and Stochastic< CloudType >::~Stochastic().
void calculate () virtual
Member Functions.
Calculate velocities
Implements IsotropyModel< CloudType >.
Definition at line 97 of file Stochastic.C.
References AveragingMethod< Type >::add(), AveragingMethod< Type >::average(), dict, Foam::exp(), forAllIter, AveragingMethod< Type >::interpolate(), objectRegistry::lookupObject(), Foam::magSqr(), Foam::max(), mesh, Foam::name(), p, rndGen(), cachedRandom::sample01(), Foam::sqrt(), timeName, and x.
Referenced by Stochastic< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/IsotropyModels/Stochastic/Stochastic.H
src/lagrangian/intermediate/submodels/MPPIC/IsotropyModels/Stochastic/Stochastic.C