OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfaceSlipDisplacementPointPatchVectorField Class Reference
Displacement follows a triSurface. Use in a displacementMotionSolver as a bc on the pointDisplacement field. Following is done by calculating the projection onto the surface according to the projectMode.
Public Types
enum projectMode { NEAREST, POINTNORMAL, FIXEDNORMAL }
Public Types inherited from pointPatchField< Type >
typedef pointPatch Patch
typedef calculatedPointPatchField< Type > Calculated
Public Member Functions
TypeName ("surfaceSlipDisplacement")
Runtime type information.
surfaceSlipDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
Construct from patch and internal field.
surfaceSlipDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<vector> onto a new patch.
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField &)
Construct as copy.
virtual autoPtr< pointPatchVectorField > clone () const
Construct and return a clone.
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField &, const DimensionedField< vector, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchVectorField > clone (const DimensionedField< vector, pointMesh > &iF) const
Construct and return a clone setting internal field reference.
const searchableSurfaces & surfaces () const
Surface to follow. Demand loads surfaceNames.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Update the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from pointPatchField< Type >
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const =0
Construct and return a clone setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type, pointMesh > & dimensionedInternalField () const
Return dimensioned internal field reference.
const Field< Type > & internalField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Additional Inherited Members
Static Public Member Functions inherited from pointPatchField< Type >
static autoPtr< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new calculatedPointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Attributes inherited from pointPatchField< Type >
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Detailed Description
Displacement follows a triSurface. Use in a displacementMotionSolver as a bc on the pointDisplacement field. Following is done by calculating the projection onto the surface according to the projectMode.
- NEAREST : nearest
POINTNORMAL : intersection with point normal
FIXEDNORMAL : intersection with fixed vector
Optionally (intersection only) removes a component ("wedgePlane") to stay in 2D.
Needs:
geometry : dictionary with searchableSurfaces. (usually triSurfaceMeshes in constant/triSurface)
projectMode : see above
projectDirection : if projectMode = fixedNormal
wedgePlane : -1 or component to knock out of intersection normal
frozenPointsZone : empty or name of pointZone containing points that do not move
Source files
surfaceSlipDisplacementPointPatchVectorField.H
surfaceSlipDisplacementPointPatchVectorField.C
Definition at line 67 of file surfaceSlipDisplacementPointPatchVectorField.H.
Member Enumeration Documentation
enum projectMode
Enumerator
NEAREST
POINTNORMAL
FIXEDNORMAL
Definition at line 76 of file surfaceSlipDisplacementPointPatchVectorField.H.
Constructor & Destructor Documentation
surfaceSlipDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 304 of file surfaceSlipDisplacementPointPatchVectorField.C.
Referenced by surfaceSlipDisplacementPointPatchVectorField::clone(), NamedEnum< Enum, nEnum >::names(), and surfaceSlipDisplacementPointPatchVectorField::surfaceSlipDisplacementPointPatchVectorField().
surfaceSlipDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 318 of file surfaceSlipDisplacementPointPatchVectorField.C.
References surfaceSlipDisplacementPointPatchVectorField::surfaceSlipDisplacementPointPatchVectorField().
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField & ppf, const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const pointPatchFieldMapper &)
Construct by mapping given patchField<vector> onto a new patch.
Definition at line 335 of file surfaceSlipDisplacementPointPatchVectorField.C.
References surfaceSlipDisplacementPointPatchVectorField::surfaceSlipDisplacementPointPatchVectorField().
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField & ppf)
Construct as copy.
Definition at line 353 of file surfaceSlipDisplacementPointPatchVectorField.C.
References surfaceSlipDisplacementPointPatchVectorField::surfaceSlipDisplacementPointPatchVectorField().
surfaceSlipDisplacementPointPatchVectorField (const surfaceSlipDisplacementPointPatchVectorField & ppf, const DimensionedField< vector, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 368 of file surfaceSlipDisplacementPointPatchVectorField.C.
Member Function Documentation
TypeName ("surfaceSlipDisplacement")
Runtime type information.
virtual autoPtr<pointPatchVectorField> clone () const inline virtual
Construct and return a clone.
Implements pointPatchField< Type >.
Definition at line 157 of file surfaceSlipDisplacementPointPatchVectorField.H.
References surfaceSlipDisplacementPointPatchVectorField::surfaceSlipDisplacementPointPatchVectorField().
virtual autoPtr<pointPatchVectorField> clone (const DimensionedField< vector, pointMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 177 of file surfaceSlipDisplacementPointPatchVectorField.H.
References UPstream::blocking, surfaceSlipDisplacementPointPatchVectorField::evaluate(), surfaceSlipDisplacementPointPatchVectorField::surfaces(), surfaceSlipDisplacementPointPatchVectorField::surfaceSlipDisplacementPointPatchVectorField(), and surfaceSlipDisplacementPointPatchVectorField::write().
const searchableSurfaces & surfaces () const
Surface to follow. Demand loads surfaceNames.
Definition at line 385 of file surfaceSlipDisplacementPointPatchVectorField.C.
References pointPatchField< Type >::db(), surfaceSlipDisplacementPointPatchVectorField::evaluate(), IOobject::MUST_READ, and IOobject::NO_WRITE.
Referenced by surfaceSlipDisplacementPointPatchVectorField::clone(), and NamedEnum< Enum, nEnum >::names().
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Update the patch field.
Reimplemented from pointPatchField< Type >.
Definition at line 412 of file surfaceSlipDisplacementPointPatchVectorField.C.
References pointPatchField< vector >::evaluate(), pointPatchField< Type >::internalField(), pointPatchField< Type >::patchInternalField(), and pointPatchField< Type >::setInInternalField().
Referenced by surfaceSlipDisplacementPointPatchVectorField::clone(), and surfaceSlipDisplacementPointPatchVectorField::surfaces().
void write (Ostream & os) const virtual
Write.
Reimplemented from pointPatchField< Type >.
Definition at line 431 of file surfaceSlipDisplacementPointPatchVectorField.C.
References token::END_STATEMENT, Foam::makePointPatchTypeField(), Foam::nl, word::null, pointPatchField< vector >::write(), and Ostream::writeKeyword().
Referenced by surfaceSlipDisplacementPointPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/fvMotionSolver/pointPatchFields/derived/surfaceSlipDisplacement/surfaceSlipDisplacementPointPatchVectorField.H
src/fvMotionSolver/pointPatchFields/derived/surfaceSlipDisplacement/surfaceSlipDisplacementPointPatchVectorField.C