OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
surfaceInterpolationScheme< Type > Class Template Reference abstract
Abstract base class for surface interpolation schemes.
Public Member Functions
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const =0
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::surfaceInterpolationScheme< Type >
Abstract base class for surface interpolation schemes.
Source files
surfaceInterpolationScheme.H
surfaceInterpolationScheme.C
Definition at line 55 of file surfaceInterpolationScheme.H.
Constructor & Destructor Documentation
surfaceInterpolationScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 111 of file surfaceInterpolationScheme.H.
~surfaceInterpolationScheme () virtual
Destructor.
Definition at line 131 of file surfaceInterpolationScheme.C.
References surfaceInterpolationScheme< Type >::interpolate().
Referenced by surfaceInterpolationScheme< GType >::surfaceInterpolationScheme().
Member Function Documentation
TypeName ("surfaceInterpolationScheme< Type >")
Runtime type information.
declareRunTimeSelectionTable (tmp , surfaceInterpolationScheme< Type > , Mesh , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
declareRunTimeSelectionTable (tmp , surfaceInterpolationScheme< Type > , MeshFlux , (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
Foam::tmp< Foam::surfaceInterpolationScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return new tmp interpolation scheme.
Definition at line 37 of file surfaceInterpolationScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, and Foam::nl.
Referenced by gaussGrad< Type >::gaussGrad(), laplacianScheme< Type, GType >::laplacianScheme(), multivariateIndependentScheme< Type >::operator()(), and surfaceInterpolationScheme< GType >::surfaceInterpolationScheme().
Foam::tmp< Foam::surfaceInterpolationScheme< Type > > New (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) static
Return new tmp interpolation scheme.
Definition at line 83 of file surfaceInterpolationScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, and Foam::nl.
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 142 of file surfaceInterpolationScheme.H.
Referenced by blended< Type >::blendingFactor(), localBlended< Type >::blendingFactor(), CoBlended< Type >::blendingFactor(), cellCoBlended< Type >::blendingFactor(), skewCorrected< Type >::corrected(), cubic< Type >::correction(), CentredFitScheme< Type, Polynomial, Stencil >::correction(), PureUpwindFitScheme< Type, Polynomial, Stencil >::correction(), UpwindFitScheme< Type, Polynomial, Stencil >::correction(), outletStabilised< Type >::correction(), skewCorrected< Type >::correction(), localBlended< Type >::correction(), localMin< Type >::interpolate(), localMax< Type >::interpolate(), localBlended< Type >::interpolate(), upwind< Type >::limiter(), blended< Type >::limiter(), skewCorrected< Type >::skewCorrection(), midPoint< Type >::weights(), linear< Type >::weights(), reverseLinear< Type >::weights(), LUST< Type >::weights(), clippedLinear< Type >::weights(), outletStabilised< Type >::weights(), localBlended< Type >::weights(), and blended< Type >::weights().
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas, const tmp< surfaceScalarField > & tys) static
Return the face-interpolate of the given cell field.
with the given owner and neighbour weigting factors
Definition at line 140 of file surfaceInterpolationScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), tmp< T >::clear(), IOobject::db(), DimensionedField< Type, GeoMesh >::dimensions(), surfaceInterpolationScheme< Type >::dotInterpolate(), Foam::endl(), forAll, InfoInFunction, IOobject::instance(), lambda(), DimensionedField< Type, GeoMesh >::mesh(), N, IOobject::name(), fvMesh::neighbour(), fvMesh::owner(), Foam::constant::mathematical::pi(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), tmp< T >::ref(), sf(), UList< T >::size(), and y.
Referenced by cubic< Type >::correction(), surfaceInterpolationScheme< GType >::correction(), surfaceInterpolationScheme< Type >::interpolate(), Foam::linearInterpolate(), surfaceInterpolationScheme< GType >::mesh(), skewCorrected< Type >::skewCorrection(), and surfaceInterpolationScheme< Type >::~surfaceInterpolationScheme().
static tmp< GeometricField < typename innerProduct<typename SFType::value_type, Type>::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType & Sf, const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas) static
Return the face-interpolate of the given cell field.
with the given weighting factors dotted with given field Sf
Referenced by surfaceInterpolationScheme< GType >::correction(), surfaceInterpolationScheme< Type >::interpolate(), and surfaceInterpolationScheme< GType >::mesh().
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas) static
Return the face-interpolate of the given cell field.
with the given weighting factors
Definition at line 321 of file surfaceInterpolationScheme.C.
References Foam::correction(), surfaceInterpolationScheme< Type >::dotInterpolate(), Foam::fvc::dotInterpolate(), Foam::endl(), InfoInFunction, surfaceInterpolationScheme< Type >::interpolate(), and IOobject::name().
virtual tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Return the interpolation weighting factors for the given field.
Implemented in cellCoBlended< Type >, CoBlended< Type >, multivariateSurfaceInterpolationScheme< Type >::fieldScheme, blended< Type >, limitedSurfaceInterpolationScheme< Type >, fixedBlended< Type >, localBlended< Type >, upwind< Type >, limiterBlended< Type >, outletStabilised< Type >, multivariateUpwind< Type >::fieldScheme, clippedLinear< Type >, limitWith< Type >, multivariateSelectionScheme< Type >::fieldScheme, downwind< Type >, weighted< Type >, skewCorrected< Type >, harmonic, localMax< Type >, localMin< Type >, LUST< Type >, reverseLinear< Type >, linear< Type >, and midPoint< Type >.
Referenced by surfaceInterpolationScheme< GType >::mesh().
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented in cellCoBlended< Type >, CoBlended< Type >, fixedBlended< Type >, localBlended< Type >, outletStabilised< Type >, limiterBlended< Type >, linearUpwind< Type >, linearUpwindV< Type >, limitWith< Type >, skewCorrected< Type >, PureUpwindFitScheme< Type, Polynomial, Stencil >, UpwindFitScheme< Type, Polynomial, Stencil >, LUST< Type >, CentredFitScheme< Type, Polynomial, Stencil >, pointLinear< Type >, and cubic< Type >.
Definition at line 193 of file surfaceInterpolationScheme.H.
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the explicit correction to the face-interpolate.
for the given field
Reimplemented in cellCoBlended< Type >, CoBlended< Type >, fixedBlended< Type >, localBlended< Type >, skewCorrected< Type >, outletStabilised< Type >, limiterBlended< Type >, linearUpwind< Type >, linearUpwindV< Type >, limitWith< Type >, PureUpwindFitScheme< Type, Polynomial, Stencil >, UpwindFitScheme< Type, Polynomial, Stencil >, LUST< Type >, CentredFitScheme< Type, Polynomial, Stencil >, pointLinear< Type >, and cubic< Type >.
Definition at line 201 of file surfaceInterpolationScheme.H.
virtual tmp< GeometricField < typename innerProduct<vector, Type>::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the face-interpolate of the given cell field.
with explicit correction dotted with given field Sf
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
with explicit correction dotted with given field Sf
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the face-interpolate of the given cell field.
with explicit correction
Reimplemented in cellCoBlended< Type >, CoBlended< Type >, fixedBlended< Type >, localBlended< Type >, limiterBlended< Type >, harmonic, localMax< Type >, and localMin< Type >.
Definition at line 408 of file surfaceInterpolationScheme.C.
References Foam::correction(), Foam::endl(), InfoInFunction, Foam::MULES::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), IOobject::name(), and tmp< T >::ref().
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf) const
Return the face-interpolate of the given tmp cell field.
with explicit correction
Definition at line 437 of file surfaceInterpolationScheme.C.
References Foam::MULES::interpolate().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolationScheme/surfaceInterpolationScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolationScheme/surfaceInterpolationScheme.C