OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
timeActivatedFileUpdate Class Reference
FunctionObjects » Utility function objects
Performs a file copy/replacement once a specified time has been reached.
Public Member Functions
TypeName ("timeActivatedFileUpdate")
Runtime type information.
timeActivatedFileUpdate (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~timeActivatedFileUpdate ()
Destructor.
virtual bool read (const dictionary &)
Read the timeActivatedFileUpdate data.
virtual bool execute ()
Execute file updates.
virtual bool write ()
Do nothing.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Performs a file copy/replacement once a specified time has been reached.
Example usage to update the fvSolution dictionary at various times throughout the calculation:
fileUpdate1
{
    type              timeActivatedFileUpdate;
    libs ("libutilityFunctionObjects.so");
    writeControl     timeStep;
    writeInterval    1;
    fileToUpdate      "$FOAM_CASE/system/fvSolution";
    timeVsFile
    (
        (-1 "$FOAM_CASE/system/fvSolution.0")
        (0.10 "$FOAM_CASE/system/fvSolution.10")
        (0.20 "$FOAM_CASE/system/fvSolution.20")
        (0.35 "$FOAM_CASE/system/fvSolution.35")
    );
}
Source files
timeActivatedFileUpdate.H
timeActivatedFileUpdate.C
Definition at line 79 of file timeActivatedFileUpdate.H.
Constructor & Destructor Documentation
timeActivatedFileUpdate (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 77 of file timeActivatedFileUpdate.C.
References Foam::read().
~timeActivatedFileUpdate () virtual
Destructor.
Definition at line 95 of file timeActivatedFileUpdate.C.
References timeActivatedFileUpdate::read().
Member Function Documentation
TypeName ("timeActivatedFileUpdate")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the timeActivatedFileUpdate data.
Reimplemented from functionObject.
Definition at line 102 of file timeActivatedFileUpdate.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::isFile(), dictionary::lookup(), Foam::nl, Foam::tab, and Foam::type().
Referenced by timeActivatedFileUpdate::~timeActivatedFileUpdate().
bool execute () virtual
Execute file updates.
Implements functionObject.
Definition at line 134 of file timeActivatedFileUpdate.C.
bool write () virtual
Do nothing.
Implements functionObject.
Definition at line 142 of file timeActivatedFileUpdate.C.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/timeActivatedFileUpdate/timeActivatedFileUpdate.H
src/functionObjects/utilities/timeActivatedFileUpdate/timeActivatedFileUpdate.C