OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Tensor< Cmpt > Class Template Reference
Templated 3D tensor derived from MatrixSpace adding construction from 9 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Public Types
enum components {
XX, XY, XZ, YX,
YY, YZ, ZX, ZY,
ZZ
}
Component labeling enumeration.
typedef Tensor< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
typedef MatrixSpace< Tensor< Cmpt >, Cmpt, Mrows, Ncols > msType
MatrixSpace type.
Public Types inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
typedef VectorSpace< Tensor< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
Public Member Functions
Tensor ()
Construct null.
Tensor (const Foam::zero)
Construct initialized to zero.
template<class Cmpt2 >
Tensor (const MatrixSpace< Tensor< Cmpt2 >, Cmpt2, 3, 3 > &)
Construct given MatrixSpace of the same rank.
template<class Cmpt2 >
Tensor (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > &)
Construct given VectorSpace of the same rank.
Tensor (const SphericalTensor< Cmpt > &)
Construct given SphericalTensor.
Tensor (const SymmTensor< Cmpt > &)
Construct given SymmTensor.
Tensor (const Vector< Vector< Cmpt >> &)
Construct given triad.
Tensor (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z)
Construct given the three vector components.
Tensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyx, const Cmpt tyy, const Cmpt tyz, const Cmpt tzx, const Cmpt tzy, const Cmpt tzz)
Construct given the nine components.
template<template< class, direction, direction > class Block2, direction BRowStart, direction BColStart>
Tensor (const Block2< Tensor< Cmpt >, BRowStart, BColStart > &block)
Construct from a block of another matrix space.
Tensor (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & xz () const
const Cmpt & yx () const
const Cmpt & yy () const
const Cmpt & yz () const
const Cmpt & zx () const
const Cmpt & zy () const
const Cmpt & zz () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & xz ()
Cmpt & yx ()
Cmpt & yy ()
Cmpt & yz ()
Cmpt & zx ()
Cmpt & zy ()
Cmpt & zz ()
Vector< Cmpt > x () const
Vector< Cmpt > y () const
Vector< Cmpt > z () const
Vector< Cmpt > vectorComponent (const direction) const
Tensor< Cmpt > T () const
Return transpose.
Tensor< Cmpt > inv () const
Return inverse.
void operator&= (const Tensor< Cmpt > &)
Inner-product with a Tensor.
template<class Cmpt2 >
void operator= (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > &)
Assign to an equivalent vector space.
void operator= (const SphericalTensor< Cmpt > &)
Assign to a SphericalTensor.
void operator= (const SymmTensor< Cmpt > &)
Assign to a SymmTensor.
void operator= (const Vector< Vector< Cmpt >> &)
Assign to a triad.
Public Member Functions inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
MatrixSpace ()
Construct null.
MatrixSpace (const Foam::zero)
Construct initialized to zero.
MatrixSpace (const VectorSpace< Form2, Cmpt2, Mrows *Ncols > &)
Construct as copy of a VectorSpace with the same size.
MatrixSpace (const Block2< Tensor< Cmpt >, BRowStart, BColStart > &block)
Construct from a block of another matrix space.
MatrixSpace (Istream &)
Construct from Istream.
const Cmpt & elmt () const
Fast const element access using compile-time addressing.
Cmpt & elmt ()
Fast element access using compile-time addressing.
const Cmpt & xx () const
Cmpt & xx ()
const Cmpt & xy () const
Cmpt & xy ()
const Cmpt & xz () const
Cmpt & xz ()
const Cmpt & yx () const
Cmpt & yx ()
const Cmpt & yy () const
Cmpt & yy ()
const Cmpt & yz () const
Cmpt & yz ()
const Cmpt & zx () const
Cmpt & zx ()
const Cmpt & zy () const
Cmpt & zy ()
const Cmpt & zz () const
Cmpt & zz ()
typeOfTranspose< Cmpt, Tensor< Cmpt > >::type T () const
Return the transpose of the matrix.
ConstBlock< SubTensor, BRowStart, BColStart > block () const
Return a const sub-block corresponding to the specified type.
Block< SubTensor, BRowStart, BColStart > block ()
Return a sub-block corresponding to the specified type.
const Cmpt & operator() (const direction &i, const direction &j) const
(i, j) const element access operator
Cmpt & operator() (const direction &i, const direction &j)
(i, j) element access operator
void operator= (const Foam::zero)
Assignment to zero.
void operator= (const Block2< Tensor< Cmpt >, BRowStart, BColStart > &block)
Assignment to a block of another matrix space.
void operator&= (const MatrixSpace< Tensor< Cmpt >, Cmpt, Ncols, Ncols > &matrix)
Inner product with a compatible square matrix.
Public Member Functions inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Tensor< Cmpt >, Cmpt, Ncmpts > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Tensor< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Tensor< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Tensor< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const direction rank = 2
Rank of Tensor is 2.
static const Tensor I
Static Public Attributes inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
static const direction mRows
static const direction nCols
Static Public Attributes inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
static const direction dim
Dimensionality of space.
static const direction nComponents
Number of components in this vector space.
static const direction mRows
static const direction nCols
static const char *const typeName
static const char *const componentNames []
static const Tensor< Cmpt > zero
static const Tensor< Cmpt > one
static const Tensor< Cmpt > max
static const Tensor< Cmpt > min
static const Tensor< Cmpt > rootMax
static const Tensor< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
static direction m ()
Return the number of rows.
static direction n ()
Return the number of columns.
static msType identity ()
Return the identity matrix for square matrix spaces.
Static Public Member Functions inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Tensor< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::Tensor< Cmpt >
Templated 3D tensor derived from MatrixSpace adding construction from 9 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Source files
Tensor.H
TensorI.H
See also
Foam::MatrixSpace Foam::Vector
Definition at line 222 of file complexI.H.
Member Typedef Documentation
typedef Tensor<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 69 of file Tensor.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
XX
XY
XZ
YX
YY
YZ
ZX
ZY
ZZ
Definition at line 84 of file Tensor.H.
Constructor & Destructor Documentation
Tensor () inline
Construct null.
Definition at line 31 of file TensorI.H.
Referenced by Tensor< Cmpt >::Tensor().
Tensor (const Foam::zero) inline
Construct initialized to zero.
Definition at line 36 of file TensorI.H.
References Tensor< Cmpt >::Tensor().
Tensor (const MatrixSpace< Tensor< Cmpt2 >, Cmpt2, 3, 3 > & vs) inline
Construct given MatrixSpace of the same rank.
Definition at line 45 of file TensorI.H.
References Tensor< Cmpt >::Tensor().
Tensor (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > & vs) inline
Construct given VectorSpace of the same rank.
Definition at line 56 of file TensorI.H.
Tensor (const SphericalTensor< Cmpt > & st) inline
Construct given SphericalTensor.
Definition at line 65 of file TensorI.H.
References SphericalTensor< Cmpt >::ii(), VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::XX, Tensor< Cmpt >::XY, Tensor< Cmpt >::XZ, Tensor< Cmpt >::YX, Tensor< Cmpt >::YY, Tensor< Cmpt >::YZ, Tensor< Cmpt >::ZX, Tensor< Cmpt >::ZY, and Tensor< Cmpt >::ZZ.
Tensor (const SymmTensor< Cmpt > & st) inline
Construct given SymmTensor.
Definition at line 74 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::XX, SymmTensor< Cmpt >::xx(), Tensor< Cmpt >::XY, SymmTensor< Cmpt >::xy(), Tensor< Cmpt >::XZ, SymmTensor< Cmpt >::xz(), Tensor< Cmpt >::YX, Tensor< Cmpt >::YY, SymmTensor< Cmpt >::yy(), Tensor< Cmpt >::YZ, SymmTensor< Cmpt >::yz(), Tensor< Cmpt >::ZX, Tensor< Cmpt >::ZY, Tensor< Cmpt >::ZZ, and SymmTensor< Cmpt >::zz().
Tensor (const Vector< Vector< Cmpt >> & tr) inline
Construct given triad.
Definition at line 83 of file TensorI.H.
References Tensor< Cmpt >::Tensor(), Foam::tr(), VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::XX, Tensor< Cmpt >::XY, Tensor< Cmpt >::XZ, Tensor< Cmpt >::YX, Tensor< Cmpt >::YY, Tensor< Cmpt >::YZ, Tensor< Cmpt >::ZX, Tensor< Cmpt >::ZY, and Tensor< Cmpt >::ZZ.
Tensor (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z) inline
Construct given the three vector components.
Definition at line 101 of file TensorI.H.
References Tensor< Cmpt >::Tensor(), VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Vector< Cmpt >::x(), Tensor< Cmpt >::XX, Tensor< Cmpt >::XY, Tensor< Cmpt >::XZ, Vector< Cmpt >::y(), Tensor< Cmpt >::YX, Tensor< Cmpt >::YY, Tensor< Cmpt >::YZ, Vector< Cmpt >::z(), Tensor< Cmpt >::ZX, Tensor< Cmpt >::ZY, and Tensor< Cmpt >::ZZ.
Tensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyx, const Cmpt tyy, const Cmpt tyz, const Cmpt tzx, const Cmpt tzy, const Cmpt tzz) inline
Construct given the nine components.
Definition at line 115 of file TensorI.H.
References Tensor< Cmpt >::Tensor(), VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::XX, Tensor< Cmpt >::XY, Tensor< Cmpt >::XZ, Tensor< Cmpt >::YX, Tensor< Cmpt >::YY, Tensor< Cmpt >::YZ, Tensor< Cmpt >::ZX, Tensor< Cmpt >::ZY, and Tensor< Cmpt >::ZZ.
Tensor (const Block2< Tensor< Cmpt >, BRowStart, BColStart > & block) inline
Construct from a block of another matrix space.
Definition at line 135 of file TensorI.H.
Tensor (Istream & is) inline
Construct from Istream.
Definition at line 144 of file TensorI.H.
Member Function Documentation
const Cmpt & xx () const inline
Definition at line 153 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::XX.
Referenced by globalIndexAndTransform::addToTransformIndex(), Foam::cof(), molecule::constantProperties::constantProperties(), Foam::det(), Foam::diag(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator&&(), Tensor< Cmpt >::operator&=(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), triad::sortxyz(), SpatialTensor< Cmpt >::SpatialTensor(), Foam::symm(), Tensor< Cmpt >::T(), Foam::tr(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
const Cmpt & xy () const inline
Definition at line 160 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::XY.
Referenced by Foam::cof(), ReynoldsStress< BasicTurbulenceModel >::correctWallShearStress(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator&&(), Tensor< Cmpt >::operator&=(), Foam::operator*(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), SpatialTensor< Cmpt >::SpatialTensor(), Foam::symm(), Tensor< Cmpt >::T(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
const Cmpt & xz () const inline
Definition at line 167 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::XZ.
Referenced by Foam::cof(), ReynoldsStress< BasicTurbulenceModel >::correctWallShearStress(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator&&(), Tensor< Cmpt >::operator&=(), Foam::operator*(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), SpatialTensor< Cmpt >::SpatialTensor(), Foam::symm(), Tensor< Cmpt >::T(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
const Cmpt & yx () const inline
Definition at line 174 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::YX.
Referenced by Foam::cof(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator&&(), Tensor< Cmpt >::operator&=(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), SpatialTensor< Cmpt >::SpatialTensor(), Foam::symm(), Tensor< Cmpt >::T(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
const Cmpt & yy () const inline
Definition at line 181 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::YY.
Referenced by globalIndexAndTransform::addToTransformIndex(), Foam::cof(), molecule::constantProperties::constantProperties(), Foam::det(), Foam::diag(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator&&(), Tensor< Cmpt >::operator&=(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), triad::sortxyz(), SpatialTensor< Cmpt >::SpatialTensor(), Foam::symm(), Tensor< Cmpt >::T(), Foam::tr(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
const Cmpt & yz () const inline
Definition at line 188 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::YZ.
Referenced by Foam::cof(), ReynoldsStress< BasicTurbulenceModel >::correctWallShearStress(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator&&(), Tensor< Cmpt >::operator&=(), Foam::operator*(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), SpatialTensor< Cmpt >::SpatialTensor(), Foam::symm(), Tensor< Cmpt >::T(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
const Cmpt & zx () const inline
Definition at line 195 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::ZX.
Referenced by Foam::cof(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator&&(), Tensor< Cmpt >::operator&=(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), SpatialTensor< Cmpt >::SpatialTensor(), Foam::symm(), Tensor< Cmpt >::T(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
const Cmpt & zy () const inline
Definition at line 202 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::ZY.
Referenced by Foam::cof(), Foam::det(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator&&(), Tensor< Cmpt >::operator&=(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), Foam::skew(), triad::sortxyz(), SpatialTensor< Cmpt >::SpatialTensor(), Foam::symm(), Tensor< Cmpt >::T(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
const Cmpt & zz () const inline
Definition at line 209 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::ZZ.
Referenced by globalIndexAndTransform::addToTransformIndex(), Foam::cof(), molecule::constantProperties::constantProperties(), Foam::det(), Foam::diag(), Foam::eigenValues(), Foam::eigenVector(), Foam::inv(), Foam::invariantII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator&&(), Tensor< Cmpt >::operator&=(), Foam::operator+(), Foam::operator-(), quaternion::quaternion(), Foam::readUpto(), triad::sortxyz(), SpatialTensor< Cmpt >::SpatialTensor(), Foam::symm(), Tensor< Cmpt >::T(), Foam::tr(), Foam::transform(), coordinateRotation::transformPrincipal(), Foam::twoSymm(), and dxSurfaceWriter::writeData().
Cmpt & xx () inline
Definition at line 216 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::XX.
Cmpt & xy () inline
Definition at line 223 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::XY.
Cmpt & xz () inline
Definition at line 230 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::XZ.
Cmpt & yx () inline
Definition at line 237 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::YX.
Cmpt & yy () inline
Definition at line 244 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::YY.
Cmpt & yz () inline
Definition at line 251 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::YZ.
Cmpt & zx () inline
Definition at line 258 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::ZX.
Cmpt & zy () inline
Definition at line 265 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::ZY.
Cmpt & zz () inline
Definition at line 272 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, and Tensor< Cmpt >::ZZ.
Foam::Vector< Cmpt > x () const inline
Definition at line 279 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::XX, Tensor< Cmpt >::XY, and Tensor< Cmpt >::XZ.
Referenced by molecule::constantProperties::constantProperties(), STARCDCoordinateRotation::e1(), EulerCoordinateRotation::e1(), axesRotation::e1(), triad::operator=(), triad::triad(), and Tensor< Cmpt >::vectorComponent().
Foam::Vector< Cmpt > y () const inline
Definition at line 286 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::YX, Tensor< Cmpt >::YY, and Tensor< Cmpt >::YZ.
Referenced by molecule::constantProperties::constantProperties(), STARCDCoordinateRotation::e2(), EulerCoordinateRotation::e2(), axesRotation::e2(), triad::operator=(), triad::triad(), and Tensor< Cmpt >::vectorComponent().
Foam::Vector< Cmpt > z () const inline
Definition at line 293 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::vectorComponent(), Tensor< Cmpt >::ZX, Tensor< Cmpt >::ZY, and Tensor< Cmpt >::ZZ.
Referenced by molecule::constantProperties::constantProperties(), STARCDCoordinateRotation::e3(), EulerCoordinateRotation::e3(), axesRotation::e3(), triad::operator=(), triad::triad(), and Tensor< Cmpt >::vectorComponent().
Foam::Vector< Cmpt > vectorComponent (const direction cmpt) const inline
Definition at line 301 of file TensorI.H.
References Tensor< Cmpt >::x(), Tensor< Cmpt >::y(), and Tensor< Cmpt >::z().
Referenced by Tensor< Cmpt >::z().
Foam::Tensor< Cmpt > T () const inline
Return transpose.
Definition at line 321 of file TensorI.H.
References Tensor< Cmpt >::xx(), Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), Tensor< Cmpt >::yx(), Tensor< Cmpt >::yy(), Tensor< Cmpt >::yz(), Tensor< Cmpt >::zx(), Tensor< Cmpt >::zy(), and Tensor< Cmpt >::zz().
Referenced by sixDoFRigidBodyMotion::addConstraints(), cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), Foam::inv(), vectorTensorTransform::invTransformPosition(), molecule::move(), spatialTransform::transpose::operator spatialTensor(), spatialTransform::transpose::operator&(), mapDistribute::transform::operator()(), transformOp< PrimitivePatchType, Type, TrackingData >::operator()(), Foam::RBD::transform(), sixDoFRigidBodyMotion::transform(), and triad::triad().
Tensor< Cmpt > inv () const inline
Return inverse.
Definition at line 642 of file TensorI.H.
References Foam::inv().
Referenced by Foam::inv(), and Foam::operator/().
void operator&= (const Tensor< Cmpt > & t) inline
Inner-product with a Tensor.
Definition at line 335 of file TensorI.H.
References Tensor< Cmpt >::xx(), Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), Tensor< Cmpt >::yx(), Tensor< Cmpt >::yy(), Tensor< Cmpt >::yz(), Tensor< Cmpt >::zx(), Tensor< Cmpt >::zy(), and Tensor< Cmpt >::zz().
void operator= (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > & vs) inline
Assign to an equivalent vector space.
Definition at line 360 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::operator.
void operator= (const SphericalTensor< Cmpt > & st) inline
Assign to a SphericalTensor.
Definition at line 369 of file TensorI.H.
References SphericalTensor< Cmpt >::ii(), VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::XX, Tensor< Cmpt >::XY, Tensor< Cmpt >::XZ, Tensor< Cmpt >::YX, Tensor< Cmpt >::YY, Tensor< Cmpt >::YZ, Tensor< Cmpt >::ZX, Tensor< Cmpt >::ZY, and Tensor< Cmpt >::ZZ.
void operator= (const SymmTensor< Cmpt > & st) inline
Assign to a SymmTensor.
Definition at line 378 of file TensorI.H.
References VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::XX, SymmTensor< Cmpt >::xx(), Tensor< Cmpt >::XY, SymmTensor< Cmpt >::xy(), Tensor< Cmpt >::XZ, SymmTensor< Cmpt >::xz(), Tensor< Cmpt >::YX, Tensor< Cmpt >::YY, SymmTensor< Cmpt >::yy(), Tensor< Cmpt >::YZ, SymmTensor< Cmpt >::yz(), Tensor< Cmpt >::ZX, Tensor< Cmpt >::ZY, Tensor< Cmpt >::ZZ, and SymmTensor< Cmpt >::zz().
void operator= (const Vector< Vector< Cmpt >> & tr) inline
Assign to a triad.
Definition at line 387 of file TensorI.H.
References Foam::tr(), VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::XX, Tensor< Cmpt >::XY, Tensor< Cmpt >::XZ, Tensor< Cmpt >::YX, Tensor< Cmpt >::YY, Tensor< Cmpt >::YZ, Tensor< Cmpt >::ZX, Tensor< Cmpt >::ZY, and Tensor< Cmpt >::ZZ.
Member Data Documentation
const direction rank = 2 static
Rank of Tensor is 2.
Definition at line 75 of file Tensor.H.
const Foam::floatTensor I static
Definition at line 80 of file Tensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/complex/complexI.H
src/OpenFOAM/primitives/Tensor/Tensor.H
src/OpenFOAM/primitives/Tensor/floatTensor/floatTensor.C
src/OpenFOAM/primitives/Tensor/TensorI.H