OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
turbulenceFields Class Reference
Function objects » Field function objects
This function object stores turbulence fields on the mesh database for further manipulation.
Public Types
enum compressibleField {
cfK, cfEpsilon, cfMut, cfMuEff,
cfAlphat, cfAlphaEff, cfR, cfDevRhoReff
}
enum incompressibleField {
ifK, ifEpsilon, ifNut, ifNuEff,
ifR, ifDevReff
}
Public Member Functions
TypeName ("turbulenceFields")
Runtime type information.
turbulenceFields (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~turbulenceFields ()
Destructor.
virtual const word & name () const
Return name of the turbulenceFields object.
virtual void read (const dictionary &)
Read the field min/max data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Static Public Attributes
static const NamedEnum< compressibleField, 8 > compressibleFieldNames_
static const NamedEnum< incompressibleField, 6 > incompressibleFieldNames_
static const word modelName = turbulenceModel::propertiesName
Protected Member Functions
turbulenceFields (const turbulenceFields &)
Disallow default bitwise copy construct.
void operator= (const turbulenceFields &)
Disallow default bitwise assignment.
bool compressible ()
Return true if compressible turbulence model is identified.
template<class Type >
void processField (const word &fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvalue)
Process the turbulence field.
Protected Attributes
word name_
Name of this set of turbulenceFields object.
const objectRegistry & obr_
bool active_
on/off switch
wordHashSet fieldSet_
Fields to load.
Detailed Description
This function object stores turbulence fields on the mesh database for further manipulation.
Fields are stored as copies of the original, with the prefix "tubulenceModel:", e.g.
turbulenceModel:R
Example of function object specification:
turbulenceFields1
{
    type        turbulenceFields;
    functionObjectLibs ("libutilityFunctionObjects.so");
    ...
    fields
    (
        R
        devRhoReff
    );
}
Function object usage
Property Description Required Default value
type type name: processorField yes
fields fields to store (see below) yes
Where fields can include:
k : turbulence kinetic energy
epsilon : turbulence kinetic energy dissipation rate
nut : turbulence viscosity (incompressible)
nuEff : effective turbulence viscosity (incompressible)
mut : turbulence viscosity (compressible)
muEff : effective turbulence viscosity (compressible)
alphat : turbulence thermal diffusivity (compressible)
alphaEff : effective turbulence thermal diffusivity (compressible)
R : Reynolds stress tensor
devReff : Deviatoric part of the effective Reynolds stress
devRhoReff : Divergence of the Reynolds stress
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
turbulenceFields.H
turbulenceFields.C
Definition at line 166 of file turbulenceFields.H.
Member Enumeration Documentation
enum compressibleField
Enumerator
cfK
cfEpsilon
cfMut
cfMuEff
cfAlphat
cfAlphaEff
cfR
cfDevRhoReff
Definition at line 170 of file turbulenceFields.H.
enum incompressibleField
Enumerator
ifK
ifEpsilon
ifNut
ifNuEff
ifR
ifDevReff
Definition at line 183 of file turbulenceFields.H.
Constructor & Destructor Documentation
turbulenceFields (const turbulenceFields &) protected
Disallow default bitwise copy construct.
turbulenceFields (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 95 of file turbulenceFields.C.
References Foam::endl(), Foam::read(), and WarningInFunction.
~turbulenceFields () virtual
Destructor.
Definition at line 124 of file turbulenceFields.C.
Member Function Documentation
void operator= (const turbulenceFields &) protected
Disallow default bitwise assignment.
bool compressible () protected
Return true if compressible turbulence model is identified.
Definition at line 71 of file turbulenceFields.C.
References turbulenceFields::active_, objectRegistry::foundObject(), turbulenceFields::modelName, turbulenceFields::obr_, and WarningInFunction.
void processField (const word & fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvalue) protected
Process the turbulence field.
Definition at line 32 of file turbulenceFieldsTemplates.C.
References Foam::endl(), fld(), Foam::nl, and WarningInFunction.
TypeName ("turbulenceFields")
Runtime type information.
virtual const word& name () const inline virtual
Return name of the turbulenceFields object.
Definition at line 259 of file turbulenceFields.H.
References turbulenceFields::name_.
void read (const dictionary & dict) virtual
Read the field min/max data.
Definition at line 130 of file turbulenceFields.C.
References Foam::endl(), forAllConstIter, Foam::Info, dictionary::lookup(), Foam::nl, and Foam::type().
void execute () virtual
Execute, currently does nothing.
Definition at line 154 of file turbulenceFields.C.
References Foam::abort(), ThermalDiffusivity< BasicTurbulenceModel >::alphaEff(), ThermalDiffusivity< BasicTurbulenceModel >::alphat(), compressible, IncompressibleTurbulenceModel< TransportModel >::devReff(), f(), Foam::FatalError, FatalErrorInFunction, and forAllConstIter.
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 272 of file turbulenceFields.C.
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 281 of file turbulenceFields.C.
void write () virtual
Write.
Definition at line 285 of file turbulenceFields.C.
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 280 of file turbulenceFields.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 284 of file turbulenceFields.H.
Member Data Documentation
const NamedEnum< turbulenceFields::compressibleField, 8 > compressibleFieldNames_ static
Definition at line 181 of file turbulenceFields.H.
const NamedEnum< turbulenceFields::incompressibleField, 6 > incompressibleFieldNames_ static
Definition at line 192 of file turbulenceFields.H.
const word modelName = turbulenceModel::propertiesName static
Definition at line 194 of file turbulenceFields.H.
Referenced by turbulenceFields::compressible().
word name_ protected
Name of this set of turbulenceFields object.
Definition at line 202 of file turbulenceFields.H.
Referenced by turbulenceFields::name().
const objectRegistry& obr_ protected
Definition at line 204 of file turbulenceFields.H.
Referenced by turbulenceFields::compressible().
bool active_ protected
on/off switch
Definition at line 207 of file turbulenceFields.H.
Referenced by turbulenceFields::compressible().
wordHashSet fieldSet_ protected
Fields to load.
Definition at line 210 of file turbulenceFields.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/utilities/turbulenceFields/turbulenceFields.H
src/postProcessing/functionObjects/utilities/turbulenceFields/turbulenceFields.C
src/postProcessing/functionObjects/utilities/turbulenceFields/turbulenceFieldsTemplates.C