OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
tmp< T > Class Template Reference
A class for managing temporary objects.
Public Member Functions
tmp (T *=0)
Store object pointer.
tmp (const T &)
Store object const reference.
tmp (const tmp< T > &)
Construct copy and increment reference count.
tmp (const tmp< T > &, bool allowTransfer)
Construct copy transferring content of temporary if required.
~tmp ()
Destructor, delete object when reference count == 0.
bool isTmp () const
Return true if this is really a temporary object.
bool empty () const
Return true if this temporary object empty,.
bool valid () const
Is this temporary object valid,.
T * ptr () const
Return tmp pointer for reuse.
void clear () const
If object pointer points to valid object:
T & operator() ()
Dereference operator.
const T & operator() () const
Const dereference operator.
operator const T & () const
Const cast to the underlying type reference.
T * operator-> ()
Return object pointer.
const T * operator-> () const
Return const object pointer.
void operator= (const tmp< T > &)
Assignment operator.
Detailed Description
template<class T>
class Foam::tmp< T >
A class for managing temporary objects.
Source files
tmp.H
tmpI.H
Definition at line 118 of file PtrList.H.
Constructor & Destructor Documentation
tmp (T * tPtr = 0) inline explicit
Store object pointer.
Definition at line 32 of file tmpI.H.
tmp (const T & tRef) inline
Store object const reference.
Definition at line 41 of file tmpI.H.
tmp (const tmp< T > & t) inline
Construct copy and increment reference count.
Definition at line 50 of file tmpI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
tmp (const tmp< T > & t, bool allowTransfer) inline
Construct copy transferring content of temporary if required.
Definition at line 74 of file tmpI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
~tmp () inline
Destructor, delete object when reference count == 0.
Definition at line 105 of file tmpI.H.
Member Function Documentation
bool isTmp () const inline
Return true if this is really a temporary object.
Definition at line 125 of file tmpI.H.
Referenced by DispersionRASModel< CloudType >::cacheFields(), and BrownianMotionForce< CloudType >::cacheFields().
bool empty () const inline
Return true if this temporary object empty,.
ie, a temporary without allocation
Definition at line 132 of file tmpI.H.
bool valid () const inline
Is this temporary object valid,.
ie, it is a reference or a temporary that has been allocated
Definition at line 139 of file tmpI.H.
T * ptr () const inline
Return tmp pointer for reuse.
Definition at line 146 of file tmpI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
Referenced by MRFZoneList::absolute(), DispersionRASModel< CloudType >::cacheFields(), BrownianMotionForce< CloudType >::cacheFields(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), volPointInterpolation::interpolate(), Field< Type >::operator=(), MRFZoneList::relative(), and PtrListDictionary< T >::set().
void clear () const inline
If object pointer points to valid object:
delete object and set pointer to NULL
Definition at line 172 of file tmpI.H.
Referenced by lduMatrix::Amul(), boundBox::boundBox(), Implicit< CloudType >::cacheFields(), kEqn< BasicTurbulenceModel >::correct(), LamBremhorstKE::correct(), LienLeschziner::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kOmegaSST< BasicTurbulenceModel >::correct(), Foam::fvc::DDt(), Foam::fvm::div(), Foam::fvc::div(), Foam::fvc::flux(), fft::forwardTransform(), surfaceInterpolationScheme< Type >::interpolate(), anisotropicFilter::operator()(), noiseFFT::Pf(), PatchToPatchInterpolation< FromPatch, ToPatch >::pointInterpolate(), Foam::pow(), realizableKE< BasicTurbulenceModel >::rCmu(), Foam::fvc::reconstructMag(), fft::reverseTransform(), snGradScheme< Type >::snGrad(), lduMatrix::Tmul(), Foam::transform(), reactingOneDim::updatePhiGas(), and Foam::fvc::volumeIntegrate().
T & operator() () inline
Dereference operator.
Definition at line 185 of file tmpI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
const T & operator() () const inline
Const dereference operator.
Definition at line 214 of file tmpI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
operator const T & () const inline
Const cast to the underlying type reference.
Definition at line 235 of file tmpI.H.
T * operator-> () inline
Return object pointer.
Definition at line 242 of file tmpI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
const T * operator-> () const inline
Return const object pointer.
Definition at line 263 of file tmpI.H.
void operator= (const tmp< T > & t) inline
Assignment operator.
Definition at line 270 of file tmpI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::T().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/PtrList/PtrList.H
src/OpenFOAM/memory/tmp/tmp.H
src/OpenFOAM/memory/tmp/tmpI.H