OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
TimeState Class Reference
The time value with time-stepping information, user-defined remapping, etc.
Public Member Functions
TimeState ()
virtual ~TimeState ()
Destructor.
virtual scalar userTimeToTime (const scalar theta) const
Convert the user-time (e.g. CA deg) to real-time (s).
virtual scalar timeToUserTime (const scalar t) const
Convert the real-time (s) into user-time (e.g. CA deg)
scalar timeOutputValue () const
Return current time value.
label timeIndex () const
Return current time index.
scalar deltaTValue () const
Return time step value.
scalar deltaT0Value () const
Return old time step value.
dimensionedScalar deltaT () const
Return time step.
dimensionedScalar deltaT0 () const
Return old time step.
bool outputTime () const
Return true if this is an output time (primary or secondary)
Public Member Functions inherited from dimensioned< scalar >
dimensioned (const word &, const dimensionSet &, const scalar)
Construct given a name, a value and its dimensionSet.
dimensioned (const word &, const dimensioned< scalar > &)
Construct from a dimensioned<Type> changing the name.
dimensioned (const scalar &t)
Construct given a value (creates dimensionless value).
dimensioned (Istream &)
Construct from Istream.
dimensioned (const word &, Istream &)
Construct from an Istream with a given name.
dimensioned (const word &, const dimensionSet &, Istream &)
Construct from an Istream with a given name and dimensions.
dimensioned (const word &, const dimensionSet &, const dictionary &)
Construct from dictionary lookup with a given name and dimensions.
dimensioned ()
Null constructor.
const word & name () const
Return const reference to name.
word & name ()
Return non-const reference to name.
const dimensionSet & dimensions () const
Return const reference to dimensions.
dimensionSet & dimensions ()
Return non-const reference to dimensions.
const scalar & value () const
Return const reference to value.
scalar & value ()
Return non-const reference to value.
dimensioned< cmptType > component (const direction) const
Return a component as a dimensioned<cmptType>
void replace (const direction, const dimensioned< cmptType > &)
Return a component with a dimensioned<cmptType>
dimensioned< scalar > T () const
Return transpose.
void read (const dictionary &)
Update the value of dimensioned<Type>
Istream & read (Istream &is, const dictionary &)
Read value from stream and units from dictionary.
Istream & read (Istream &is, const HashTable< dimensionedScalar > &)
Read value from stream and units from table.
Istream & read (Istream &is)
Read value from stream and units from system table.
bool readIfPresent (const dictionary &)
Update the value of dimensioned<Type> if found in the dictionary.
dimensioned< cmptType > operator[] (const direction) const
Return a component as a dimensioned<cmptType>
void operator+= (const dimensioned< scalar > &)
void operator-= (const dimensioned< scalar > &)
void operator*= (const scalar)
void operator/= (const scalar)
Protected Attributes
label timeIndex_
scalar deltaT_
scalar deltaTSave_
scalar deltaT0_
bool deltaTchanged_
label outputTimeIndex_
bool primaryOutputTime_
Is outputTime because of primary?
label secondaryOutputTimeIndex_
bool secondaryOutputTime_
Is outputTime because of secondary?
bool outputTime_
Additional Inherited Members
Public Types inherited from dimensioned< scalar >
typedef pTraits< scalar >::cmptType cmptType
Component type.
Static Public Member Functions inherited from dimensioned< scalar >
static dimensioned< scalar > lookupOrDefault (const word &, const dictionary &, const dimensionSet &dims=dimless, const scalar &defaultValue=pTraits< scalar >::zero)
Construct from dictionary, with default dimensions and value.
static dimensioned< scalar > lookupOrDefault (const word &, const dictionary &, const scalar &defaultValue=pTraits< scalar >::zero)
Construct from dictionary dimensionless with value.
static dimensioned< scalar > lookupOrAddToDict (const word &, dictionary &, const dimensionSet &dims=dimless, const scalar &defaultValue=pTraits< scalar >::zero)
Construct from dictionary, with default value.
static dimensioned< scalar > lookupOrAddToDict (const word &, dictionary &, const scalar &defaultValue=pTraits< scalar >::zero)
Construct from dictionary, dimensionless with default value.
Detailed Description
The time value with time-stepping information, user-defined remapping, etc.
Source files
TimeState.H
TimeState.C
Definition at line 49 of file TimeState.H.
Constructor & Destructor Documentation
TimeState ()
Definition at line 31 of file TimeState.C.
~TimeState () virtual
Destructor.
Definition at line 49 of file TimeState.C.
Member Function Documentation
Foam::scalar userTimeToTime (const scalar theta) const virtual
Convert the user-time (e.g. CA deg) to real-time (s).
Reimplemented in engineTime.
Definition at line 55 of file TimeState.C.
Referenced by Polynomial< Type >::convertTimeBase(), and TableBase< Type >::convertTimeBase().
Foam::scalar timeToUserTime (const scalar t) const virtual
Convert the real-time (s) into user-time (e.g. CA deg)
Reimplemented in engineTime.
Definition at line 61 of file TimeState.C.
Referenced by TimeState::timeOutputValue(), and Time::writeObject().
Foam::scalar timeOutputValue () const
Return current time value.
Definition at line 67 of file TimeState.C.
References TimeState::timeToUserTime(), and dimensioned< scalar >::value().
Referenced by edgeMeshFormatsCore::getLineNoComment(), surfaceFormatsCore::getLineNoComment(), triSurface::triSurfInstance(), and uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
Foam::label timeIndex () const
Return current time index.
Definition at line 73 of file TimeState.C.
References TimeState::timeIndex_.
Referenced by ignitionSite::cells(), layerAdditionRemoval::changeTopology(), radiationModel::correct(), fvMesh::movePoints(), polyMesh::movePoints(), sampledThresholdCellFaces::needsUpdate(), sampledIsoSurfaceCell::needsUpdate(), sampledIsoSurface::needsUpdate(), polyMesh::oldPoints(), fvMesh::phi(), cloudSolution::solveThisStep(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and subCycleField< GeometricField >::~subCycleField().
scalar deltaTValue () const inline
Return time step value.
Definition at line 100 of file TimeState.H.
References TimeState::deltaT_.
Referenced by cellCoBlended< Type >::blendingFactor(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), cloudSolution::canEvolve(), Foam::MULES::correct(), solidification::correctModel(), kinematicSingleLayer::CourantNumber(), particle< Type >::currentTime(), engineValve::curVelocity(), engineTime::deltaTheta(), Foam::MULES::explicitSolve(), ignitionSite::ignited(), ignitionSite::igniting(), Foam::MULES::implicitSolve(), phaseChangeModel::info(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), solidParticleCloud::move(), fvMesh::movePoints(), engineTime::pistonSpeed(), VoidFraction< CloudType >::postEvolve(), reactingOneDim::solidRegionDiffNo(), sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotion::solve(), thermoSingleLayer::Srho(), thermoSingleLayer::transferPrimaryRegionSourceFields(), kinematicSingleLayer::transferPrimaryRegionSourceFields(), movingWallVelocityFvPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), surfaceDisplacementPointPatchVectorField::updateCoeffs(), plenumPressureFvPatchScalarField::updateCoeffs(), thermoSingleLayer::updateSubmodels(), fvMesh::Vsc(), and fvMesh::Vsc0().
scalar deltaT0Value () const inline
Return old time step value.
Definition at line 106 of file TimeState.H.
References TimeState::deltaT(), TimeState::deltaT0(), TimeState::deltaT0_, and TimeState::outputTime().
Referenced by sixDoFRigidBodyMotionSolver::solve(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
Foam::dimensionedScalar deltaT () const
Return time step.
Definition at line 79 of file TimeState.C.
References TimeState::deltaT_, and Foam::dimTime.
Referenced by CoBlended< Type >::blendingFactor(), reactingOneDim::calculateMassTransfer(), thixotropicViscosity::correct(), kinematicSingleLayer::deltaMass(), TimeState::deltaT0Value(), CourantNo::execute(), Foam::MULES::implicitSolve(), kinematicSingleLayer::netMass(), continuousGasKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), continuousGasKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), NicenoKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), LaheyKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), movingConeTopoFvMesh::update(), thermoSingleLayer::updateSubmodels(), and kinematicSingleLayer::updateSubmodels().
Foam::dimensionedScalar deltaT0 () const
Return old time step.
Definition at line 85 of file TimeState.C.
References TimeState::deltaT0_, and Foam::dimTime.
Referenced by TimeState::deltaT0Value().
bool outputTime () const
Return true if this is an output time (primary or secondary)
Definition at line 91 of file TimeState.C.
References TimeState::outputTime_.
Referenced by curvatureSeparation::calcCosAngle(), curvatureSeparation::calcInvR1(), contactAngleForce::correct(), thixotropicViscosity::correct(), TimeState::deltaT0Value(), cloudSolution::output(), filmSubModelBase::outputTime(), CloudSubModelBase< CloudType >::outputTime(), cloudSolution::solveThisStep(), and Time::writeObject().
Member Data Documentation
label timeIndex_ protected
Definition at line 56 of file TimeState.H.
Referenced by Time::setTime(), TimeState::timeIndex(), and Time::writeObject().
scalar deltaT_ protected
Definition at line 57 of file TimeState.H.
Referenced by TimeState::deltaT(), TimeState::deltaTValue(), engineTime::engineTime(), Time::readDict(), and Time::writeObject().
scalar deltaTSave_ protected
Definition at line 58 of file TimeState.H.
Referenced by engineTime::engineTime().
scalar deltaT0_ protected
Definition at line 59 of file TimeState.H.
Referenced by TimeState::deltaT0(), TimeState::deltaT0Value(), engineTime::engineTime(), and Time::writeObject().
bool deltaTchanged_ protected
Definition at line 60 of file TimeState.H.
Referenced by Time::readDict().
label outputTimeIndex_ protected
Definition at line 62 of file TimeState.H.
Referenced by Time::readDict().
bool primaryOutputTime_ protected
Is outputTime because of primary?
Definition at line 64 of file TimeState.H.
Referenced by Time::writeNow(), and Time::writeObject().
label secondaryOutputTimeIndex_ protected
Definition at line 66 of file TimeState.H.
Referenced by Time::readDict().
bool secondaryOutputTime_ protected
Is outputTime because of secondary?
Definition at line 68 of file TimeState.H.
Referenced by Time::writeObject().
bool outputTime_ protected
Definition at line 70 of file TimeState.H.
Referenced by TimeState::outputTime(), and Time::writeNow().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/TimeState.H
src/OpenFOAM/db/Time/TimeState.C