OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
SymmTensor< Cmpt > Class Template Reference
Templated 3D symmetric tensor derived from VectorSpace adding construction from 6 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Public Types
enum components {
XX, XY, XZ, YY,
YZ, ZZ
}
Component labeling enumeration.
typedef SymmTensor< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
typedef VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
Public Member Functions
SymmTensor ()
Construct null.
SymmTensor (const Foam::zero)
Construct initialized to zero.
template<class Cmpt2 >
SymmTensor (const VectorSpace< SymmTensor< Cmpt2 >, Cmpt2, 6 > &)
Construct given VectorSpace of the same rank.
SymmTensor (const SphericalTensor< Cmpt > &)
Construct given SphericalTensor.
SymmTensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyy, const Cmpt tyz, const Cmpt tzz)
Construct given the six components.
SymmTensor (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & xz () const
const Cmpt & yy () const
const Cmpt & yz () const
const Cmpt & zz () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & xz ()
Cmpt & yy ()
Cmpt & yz ()
Cmpt & zz ()
const SymmTensor< Cmpt > & T () const
Transpose.
void operator= (const SphericalTensor< Cmpt > &)
Assign to given SphericalTensor.
Public Member Functions inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const direction rank = 2
Rank of SymmTensor is 2.
static const SymmTensor I
Static Public Attributes inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
static const direction dim
Dimensionality of space.
static const direction nComponents
Number of components in this vector space.
static const direction mRows
static const direction nCols
static const char *const typeName
static const char *const componentNames []
static const SymmTensor< Cmpt > zero
static const SymmTensor< Cmpt > one
static const SymmTensor< Cmpt > max
static const SymmTensor< Cmpt > min
static const SymmTensor< Cmpt > rootMax
static const SymmTensor< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static SymmTensor< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SymmTensor< Cmpt >
Templated 3D symmetric tensor derived from VectorSpace adding construction from 6 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Source files
SymmTensor.H
SymmTensorI.H
Definition at line 53 of file SymmTensor.H.
Member Typedef Documentation
typedef SymmTensor<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 61 of file SymmTensor.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
XX
XY
XZ
YY
YZ
ZZ
Definition at line 76 of file SymmTensor.H.
Constructor & Destructor Documentation
SymmTensor () inline
Construct null.
Definition at line 32 of file SymmTensorI.H.
Referenced by SymmTensor< Cmpt >::SymmTensor().
SymmTensor (const Foam::zero) inline
Construct initialized to zero.
Definition at line 37 of file SymmTensorI.H.
References SymmTensor< Cmpt >::SymmTensor().
SymmTensor (const VectorSpace< SymmTensor< Cmpt2 >, Cmpt2, 6 > & vs) inline
Construct given VectorSpace of the same rank.
Definition at line 46 of file SymmTensorI.H.
SymmTensor (const SphericalTensor< Cmpt > & st) inline
Construct given SphericalTensor.
Definition at line 55 of file SymmTensorI.H.
References SphericalTensor< Cmpt >::ii(), SymmTensor< Cmpt >::SymmTensor(), VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, SymmTensor< Cmpt >::XX, SymmTensor< Cmpt >::XY, SymmTensor< Cmpt >::XZ, SymmTensor< Cmpt >::YY, SymmTensor< Cmpt >::YZ, and SymmTensor< Cmpt >::ZZ.
SymmTensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyy, const Cmpt tyz, const Cmpt tzz) inline
Construct given the six components.
Definition at line 65 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, SymmTensor< Cmpt >::XX, SymmTensor< Cmpt >::XY, SymmTensor< Cmpt >::XZ, SymmTensor< Cmpt >::YY, SymmTensor< Cmpt >::YZ, and SymmTensor< Cmpt >::ZZ.
SymmTensor (Istream & is) inline
Construct from Istream.
Definition at line 78 of file SymmTensorI.H.
Member Function Documentation
const Cmpt & xx () const inline
Definition at line 87 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XX.
Referenced by primitiveMeshTools::cellDeterminant(), Foam::cof(), Foam::det(), Foam::diag(), Foam::innerSqr(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator&(), Foam::operator&&(), Foam::operator+(), Foam::operator-(), Tensor< Cmpt >::operator=(), Tensor< Cmpt >::Tensor(), Foam::tr(), Foam::transform(), and dxSurfaceWriter::writeData().
const Cmpt & xy () const inline
Definition at line 93 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XY.
Referenced by Foam::cof(), Foam::det(), Foam::innerSqr(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator&(), Foam::operator&&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Tensor< Cmpt >::operator=(), Tensor< Cmpt >::Tensor(), Foam::transform(), and dxSurfaceWriter::writeData().
const Cmpt & xz () const inline
Definition at line 99 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XZ.
Referenced by Foam::cof(), Foam::det(), Foam::innerSqr(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator&(), Foam::operator&&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Tensor< Cmpt >::operator=(), Tensor< Cmpt >::Tensor(), Foam::transform(), and dxSurfaceWriter::writeData().
const Cmpt & yy () const inline
Definition at line 105 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YY.
Referenced by primitiveMeshTools::cellDeterminant(), Foam::cof(), Foam::det(), Foam::diag(), Foam::innerSqr(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator&(), Foam::operator&&(), Foam::operator+(), Foam::operator-(), Tensor< Cmpt >::operator=(), Tensor< Cmpt >::Tensor(), Foam::tr(), Foam::transform(), and dxSurfaceWriter::writeData().
const Cmpt & yz () const inline
Definition at line 111 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YZ.
Referenced by Foam::cof(), Foam::det(), Foam::innerSqr(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator&(), Foam::operator&&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Tensor< Cmpt >::operator=(), Tensor< Cmpt >::Tensor(), Foam::transform(), and dxSurfaceWriter::writeData().
const Cmpt & zz () const inline
Definition at line 117 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::ZZ.
Referenced by primitiveMeshTools::cellDeterminant(), Foam::cof(), Foam::det(), Foam::diag(), Foam::innerSqr(), Foam::inv(), Foam::invariantII(), Foam::magSqr(), Foam::operator&(), Foam::operator&&(), Foam::operator+(), Foam::operator-(), Tensor< Cmpt >::operator=(), Tensor< Cmpt >::Tensor(), Foam::tr(), Foam::transform(), and dxSurfaceWriter::writeData().
Cmpt & xx () inline
Definition at line 124 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XX.
Cmpt & xy () inline
Definition at line 130 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XY.
Cmpt & xz () inline
Definition at line 136 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::XZ.
Cmpt & yy () inline
Definition at line 142 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YY.
Cmpt & yz () inline
Definition at line 148 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::YZ.
Cmpt & zz () inline
Definition at line 154 of file SymmTensorI.H.
References VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, and SymmTensor< Cmpt >::ZZ.
const Foam::SymmTensor< Cmpt > & T () const inline
Transpose.
Definition at line 161 of file SymmTensorI.H.
void operator= (const SphericalTensor< Cmpt > & st) inline
Assign to given SphericalTensor.
Definition at line 170 of file SymmTensorI.H.
References SphericalTensor< Cmpt >::ii(), VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >::v_, SymmTensor< Cmpt >::XX, SymmTensor< Cmpt >::XY, SymmTensor< Cmpt >::XZ, SymmTensor< Cmpt >::YY, SymmTensor< Cmpt >::YZ, and SymmTensor< Cmpt >::ZZ.
Member Data Documentation
const direction rank = 2 static
Rank of SymmTensor is 2.
Definition at line 67 of file SymmTensor.H.
const Foam::labelSymmTensor I static
Definition at line 72 of file SymmTensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SymmTensor/SymmTensor.H
src/OpenFOAM/primitives/SymmTensor/labelSymmTensor/labelSymmTensor.C
src/OpenFOAM/primitives/SymmTensor/SymmTensorI.H