OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
tableReader< Type > Class Template Reference abstract
Base class to read table data for the interpolationTable.
Public Member Functions
TypeName ("tableReader")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, tableReader, dictionary,(const dictionary &dict),(dict))
tableReader (const dictionary &dict)
Construct from dictionary.
virtual autoPtr< tableReader< Type > > clone () const =0
Construct and return a clone.
virtual ~tableReader ()
Destructor.
virtual void operator() (const fileName &, List< Tuple2< scalar, Type >> &)=0
Read the table.
virtual void operator() (const fileName &, List< Tuple2< scalar, List< Tuple2< scalar, Type >>>> &)=0
Read the 2D table.
virtual void write (Ostream &os) const
Write additional information.
Static Public Member Functions
static autoPtr< tableReader > New (const dictionary &spec)
Return a reference to the selected tableReader.
Detailed Description
template<class Type>
class Foam::tableReader< Type >
Base class to read table data for the interpolationTable.
Source files
tableReader.H
tableReader.C
Definition at line 57 of file tableReader.H.
Constructor & Destructor Documentation
tableReader (const dictionary & dict)
Construct from dictionary.
Definition at line 63 of file tableReader.C.
~tableReader () virtual
Destructor.
Definition at line 70 of file tableReader.C.
Member Function Documentation
TypeName ("tableReader< Type >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , tableReader< Type > , dictionary , (const dictionary &dict) , (dict))
virtual autoPtr<tableReader<Type> > clone () const pure virtual
Construct and return a clone.
Implemented in csvTableReader< Type >, and openFoamTableReader< Type >.
Foam::autoPtr< Foam::tableReader< Type > > New (const dictionary & spec) static
Return a reference to the selected tableReader.
Definition at line 32 of file tableReader.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookupOrDefault(), and Foam::nl.
virtual void operator() (const fileName & , List< Tuple2< scalar, Type >> &) pure virtual
Read the table.
Implemented in csvTableReader< Type >, and openFoamTableReader< Type >.
virtual void operator() (const fileName & , List< Tuple2< scalar, List< Tuple2< scalar, Type >>>> &) pure virtual
Read the 2D table.
Implemented in csvTableReader< Type >, and openFoamTableReader< Type >.
void write (Ostream & os) const virtual
Write additional information.
Reimplemented in csvTableReader< Type >.
Definition at line 77 of file tableReader.C.
References Foam::nl, Foam::type(), and Ostream::writeKeyword().
Referenced by csvTableReader< Type >::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationTable/tableReaders/tableReader.H
src/OpenFOAM/interpolations/interpolationTable/tableReaders/tableReader.C