OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
uniformTotalPressureFvPatchScalarField Class Reference
Inlet boundary Conditions | Outlet boundary Conditions
This boundary condition provides a time-varying form of the uniform total pressure boundary condition.
Public Member Functions
TypeName ("uniformTotalPressure")
Runtime type information.
uniformTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
uniformTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given patch field onto a new patch.
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const word & UName () const
Return the name of the velocity field.
word & UName ()
Return reference to the name of the velocity field.
scalar gamma () const
Return the heat capacity ratio.
scalar & gamma ()
Return reference to the heat capacity ratio to allow adjustment.
virtual void updateCoeffs (const vectorField &Up)
Update the coefficients associated with the patch field.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a time-varying form of the uniform total pressure boundary condition.
Patch usage
Property Description Required Default value
U velocity field name no U
phi flux field name no phi
rho density field name no none
psi compressibility field name no none
gamma ratio of specific heats (Cp/Cv) yes
pressure total pressure as a function of time yes
Example of the boundary condition specification:
    myPatch
    {
        type            uniformTotalPressure;
        U               U;
        phi             phi;
        rho             rho;
        psi             psi;
        gamma           1.4;
        pressure        uniform 1e5;
    }
The pressure entry is specified as a DataEntry type, able to describe time varying functions.
Note
The default boundary behaviour is for subsonic, incompressible flow.
See Also
Foam::DataEntry Foam::uniformFixedValueFvPatchField Foam::totalPressureFvPatchField
Source files
uniformTotalPressureFvPatchScalarField.H
uniformTotalPressureFvPatchScalarField.C
Definition at line 126 of file uniformTotalPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
uniformTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file uniformTotalPressureFvPatchScalarField.C.
uniformTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 53 of file uniformTotalPressureFvPatchScalarField.C.
References dictionary::found(), scalarField(), and fvPatch::size().
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given patch field onto a new patch.
Definition at line 84 of file uniformTotalPressureFvPatchScalarField.C.
References Foam::operator==().
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 107 of file uniformTotalPressureFvPatchScalarField.C.
uniformTotalPressureFvPatchScalarField (const uniformTotalPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 128 of file uniformTotalPressureFvPatchScalarField.C.
Member Function Documentation
TypeName ("uniformTotalPressure")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 191 of file uniformTotalPressureFvPatchScalarField.H.
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 208 of file uniformTotalPressureFvPatchScalarField.H.
const word& UName () const inline
Return the name of the velocity field.
Definition at line 224 of file uniformTotalPressureFvPatchScalarField.H.
word& UName () inline
Return reference to the name of the velocity field.
to allow adjustment
Definition at line 231 of file uniformTotalPressureFvPatchScalarField.H.
scalar gamma () const inline
Return the heat capacity ratio.
Definition at line 237 of file uniformTotalPressureFvPatchScalarField.H.
scalar& gamma () inline
Return reference to the heat capacity ratio to allow adjustment.
Definition at line 243 of file uniformTotalPressureFvPatchScalarField.H.
void updateCoeffs (const vectorField & Up) virtual
Update the coefficients associated with the patch field.
using the given patch velocity field
Definition at line 151 of file uniformTotalPressureFvPatchScalarField.C.
References dimensionedInternalField(), Foam::exit(), Foam::FatalError, FatalErrorIn, Foam::magSqr(), Foam::operator==(), Foam::pos(), Foam::pow(), and rho.
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 218 of file uniformTotalPressureFvPatchScalarField.C.
void write (Ostream & os) const virtual
Write.
Definition at line 224 of file uniformTotalPressureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::nl, and fvPatchField< Type >::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/uniformTotalPressure/uniformTotalPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/uniformTotalPressure/uniformTotalPressureFvPatchScalarField.C