OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UOPstream Class Reference
Output inter-processor communications stream operating on external buffer.
Public Member Functions
UOPstream (const commsTypes commsType, const int toProcNo, DynamicList< char > &sendBuf, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool sendAtDestruct=true, streamFormat format=BINARY, versionNumber version=currentVersion)
Construct given process index to send to and optional buffer size,.
UOPstream (const int toProcNo, PstreamBuffers &)
Construct given buffers.
~UOPstream ()
Destructor.
ios_base::fmtflags flags () const
Return flags of output stream.
Ostream & write (const token &)
Write next token to stream.
Ostream & write (const char)
Write character.
Ostream & write (const char *)
Write character string.
Ostream & write (const word &)
Write word.
Ostream & write (const string &)
Write string.
Ostream & writeQuoted (const std::string &, const bool quoted=true)
Write std::string surrounded by quotes.
virtual Ostream & write (const int32_t)
Write int32_t.
Ostream & write (const int64_t)
Write int64_t.
Ostream & write (const floatScalar)
Write floatScalar.
Ostream & write (const doubleScalar)
Write doubleScalar.
Ostream & write (const char *, std::streamsize)
Write binary block.
void indent ()
Add indentation characters.
void flush ()
Flush stream.
void endl ()
Add newline and flush stream.
int width () const
Get width of output field.
int width (const int)
Set width of output field (and return old width)
int precision () const
Get precision of output field.
int precision (const int)
Set precision of output field (and return old precision)
ios_base::fmtflags flags (const ios_base::fmtflags)
Set flags of stream.
void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from UPstream
ClassName ("UPstream")
UPstream (const commsTypes commsType)
Construct given optional buffer size.
commsTypes commsType () const
Get the communications type of the stream.
commsTypes commsType (const commsTypes ct)
Set the communications type of the stream.
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Ostream ()
Destructor.
virtual Ostream & write (const keyType &)
Write keyType.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Incrememt the indent level.
void decrIndent ()
Decrememt the indent level.
Ostream & writeKeyword (const keyType &)
Write the keyword followed by an appropriate indentation.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Static Public Member Functions
static bool write (const commsTypes commsType, const int toProcNo, const char *buf, const std::streamsize bufSize, const int tag=UPstream::msgType(), const label communicator=0)
Write given buffer to given processor.
Static Public Member Functions inherited from UPstream
static label allocateCommunicator (const label parent, const labelList &subRanks, const bool doPstream=true)
Allocate a new communicator.
static void freeCommunicator (const label communicator, const bool doPstream=true)
Free a previously allocated communicator.
static void freeCommunicators (const bool doPstream)
Free all communicators.
static int baseProcNo (const label myComm, const int procID)
Return physical processor number (i.e. processor number in.
static label procNo (const label comm, const int baseProcID)
Return processor number in communicator (given physical processor.
static label procNo (const label myComm, const label currentComm, const int currentProcID)
Return processor number in communicator (given processor number.
static void addValidParOptions (HashTable< string > &validParOptions)
Add the valid option this type of communications library.
static bool init (int &argc, char **&argv)
Initialisation function called from main.
static label nRequests ()
Get number of outstanding requests.
static void resetRequests (const label sz)
Truncate number of outstanding requests.
static void waitRequests (const label start=0)
Wait until all requests (from start onwards) have finished.
static void waitRequest (const label i)
Wait until request i has finished.
static bool finishedRequest (const label i)
Non-blocking comms: has request i finished?
static int allocateTag (const char *)
static int allocateTag (const word &)
static void freeTag (const char *, const int tag)
static void freeTag (const word &, const int tag)
static bool & parRun ()
Is this a parallel run?
static label nProcs (const label communicator=0)
Number of processes in parallel run.
static int masterNo ()
Process index of the master.
static bool master (const label communicator=0)
Am I the master process.
static int myProcNo (const label communicator=0)
Number of this process (starting from masterNo() = 0)
static label parent (const label communicator)
static List< int > & procID (label communicator)
Process ID of given process index.
static int firstSlave ()
Process index of first slave.
static int lastSlave (const label communicator=0)
Process index of last slave.
static const List< commsStruct > & linearCommunication (const label communicator=0)
Communication schedule for linear all-to-master (proc 0)
static const List< commsStruct > & treeCommunication (const label communicator=0)
Communication schedule for tree all-to-master (proc 0)
static int & msgType ()
Message tag of standard messages.
static void exit (int errnum=1)
Exit program.
static void abort ()
Abort program.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Additional Inherited Members
Public Types inherited from UPstream
enum commsTypes { blocking, scheduled, nonBlocking }
Types of communications.
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Attributes inherited from UPstream
static const NamedEnum< commsTypes, 3 > commsTypeNames
static bool floatTransfer
Should compact transfer be used in which floats replace doubles.
static int nProcsSimpleSum
Number of processors at which the sum algorithm changes from linear.
static commsTypes defaultCommsType
Default commsType.
static int nPollProcInterfaces
Number of polling cycles in processor updates.
static label worldComm
Default communicator (all processors)
static label warnComm
Debugging: warn for use of any communicator differing from warnComm.
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from UPstream
commsTypes commsType_
Communications type of this stream.
Protected Attributes inherited from Ostream
unsigned short indentLevel_
Current indent level.
Protected Attributes inherited from IOstream
label lineNumber_
Static Protected Attributes inherited from Ostream
static const unsigned short indentSize_ = 4
Number of spaces per indent level.
static const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Detailed Description
Output inter-processor communications stream operating on external buffer.
Source files
UOPstream.H
UOPstream.C
Definition at line 54 of file UOPstream.H.
Constructor & Destructor Documentation
UOPstream (const commsTypes commsType, const int toProcNo, DynamicList< char > & sendBuf, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool sendAtDestruct = true, streamFormat format = BINARY, versionNumber version = currentVersion)
Construct given process index to send to and optional buffer size,.
write format and IO version
Definition at line 89 of file UOPstream.C.
References IOstream::setGood(), and IOstream::setOpened().
UOPstream (const int toProcNo, PstreamBuffers & buffers)
Construct given buffers.
Definition at line 113 of file UOPstream.C.
References IOstream::setGood(), and IOstream::setOpened().
~UOPstream ()
Destructor.
Definition at line 130 of file UOPstream.C.
References Foam::abort(), UList< T >::begin(), UPstream::commsType_, Foam::FatalError, FatalErrorInFunction, List< T >::size(), and UOPstream::write().
Member Function Documentation
ios_base::fmtflags flags () const inline virtual
Return flags of output stream.
Implements IOstream.
Definition at line 116 of file UOPstream.H.
References UPstream::msgType(), UOPstream::write(), and UOPstream::writeQuoted().
bool write (const commsTypes commsType, const int toProcNo, const char * buf, const std::streamsize bufSize, const int tag = UPstream::msgType(), const label communicator = 0) static
Write given buffer to given processor.
Definition at line 34 of file UOPwrite.C.
References NotImplemented.
Referenced by Pstream::combineGather(), Pstream::combineScatter(), mapDistribute::compact(), UOPstream::flags(), Pstream::gather(), Pstream::gatherList(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), Pstream::listCombineGather(), Pstream::listCombineScatter(), Pstream::scatter(), Pstream::scatterList(), LUscalarMatrix::solve(), UOPstream::write(), UOPstream::writeQuoted(), and UOPstream::~UOPstream().
Foam::Ostream & write (const token & t) virtual
Write next token to stream.
Implements Ostream.
Definition at line 158 of file UOPstream.C.
References NotImplemented, IOstream::setBad(), token::stringToken(), token::type(), token::VARIABLE, token::VERBATIMSTRING, and UOPstream::write().
Foam::Ostream & write (const char c) virtual
Write character.
Implements Ostream.
Definition at line 180 of file UOPstream.C.
References Foam::isspace().
Foam::Ostream & write (const char * str) virtual
Write character string.
Implements Ostream.
Definition at line 191 of file UOPstream.C.
References UOPstream::write().
Foam::Ostream & write (const word & str) virtual
Write word.
Implements Ostream.
Definition at line 210 of file UOPstream.C.
References token::WORD, and UOPstream::write().
Foam::Ostream & write (const string & str) virtual
Write string.
Implements Ostream.
Definition at line 222 of file UOPstream.C.
References token::STRING, UOPstream::write(), and UOPstream::writeQuoted().
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Implements Ostream.
Definition at line 235 of file UOPstream.C.
References token::STRING, token::WORD, and UOPstream::write().
Referenced by UOPstream::flags(), and UOPstream::write().
Foam::Ostream & write (const int32_t val) virtual
Write int32_t.
Implements Ostream.
Definition at line 257 of file UOPstream.C.
References token::LABEL, and UOPstream::write().
Foam::Ostream & write (const int64_t val) virtual
Write int64_t.
Implements Ostream.
Definition at line 265 of file UOPstream.C.
References token::LABEL, and UOPstream::write().
Foam::Ostream & write (const floatScalar val) virtual
Write floatScalar.
Implements Ostream.
Definition at line 273 of file UOPstream.C.
References token::FLOAT_SCALAR, and UOPstream::write().
Foam::Ostream & write (const doubleScalar val) virtual
Write doubleScalar.
Implements Ostream.
Definition at line 281 of file UOPstream.C.
References token::DOUBLE_SCALAR, and UOPstream::write().
Foam::Ostream & write (const char * data, std::streamsize count) virtual
Write binary block.
Implements Ostream.
Definition at line 289 of file UOPstream.C.
References Foam::abort(), IOstream::BINARY, Foam::FatalError, FatalErrorInFunction, and IOstream::format().
void indent () inline virtual
Add indentation characters.
Implements Ostream.
Definition at line 174 of file UOPstream.H.
void flush () inline virtual
Flush stream.
Implements Ostream.
Definition at line 181 of file UOPstream.H.
void endl () inline virtual
Add newline and flush stream.
Implements Ostream.
Definition at line 185 of file UOPstream.H.
int width () const inline virtual
Get width of output field.
Implements Ostream.
Definition at line 189 of file UOPstream.H.
int width (const int) inline virtual
Set width of output field (and return old width)
Implements Ostream.
Definition at line 195 of file UOPstream.H.
int precision () const inline virtual
Get precision of output field.
Implements Ostream.
Definition at line 201 of file UOPstream.H.
int precision (const int) inline virtual
Set precision of output field (and return old precision)
Implements Ostream.
Definition at line 207 of file UOPstream.H.
ios_base::fmtflags flags (const ios_base::fmtflags) inline virtual
Set flags of stream.
Implements IOstream.
Definition at line 216 of file UOPstream.H.
References UOPstream::print().
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from IOstream.
Definition at line 304 of file UOPstream.C.
References Foam::endl(), and UPstream::myProcNo().
Referenced by UOPstream::flags().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UOPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UOPstream.C
src/Pstream/dummy/UOPwrite.C