OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
solidParticle::trackingData Class Reference
Class used to pass tracking data to the trackToFace function.
Public Member Functions
trackingData (solidParticleCloud &spc, const interpolationCellPoint< scalar > &rhoInterp, const interpolationCellPoint< vector > &UInterp, const interpolationCellPoint< scalar > &nuInterp, const vector &g)
const interpolationCellPoint< scalar > & rhoInterp () const
const interpolationCellPoint< vector > & UInterp () const
const interpolationCellPoint< scalar > & nuInterp () const
const vector & g () const
Public Member Functions inherited from particle< Type >::TrackingData< solidParticleCloud >
TrackingData (solidParticleCloud &cloud)
solidParticleCloud & cloud ()
Return a reference to the cloud.
Additional Inherited Members
Public Types inherited from particle< Type >::TrackingData< solidParticleCloud >
typedef solidParticleCloud cloudType
Public Attributes inherited from particle< Type >::TrackingData< solidParticleCloud >
bool switchProcessor
Flag to switch processor.
bool keepParticle
Flag to indicate whether to keep particle (false = delete)
Detailed Description
Class used to pass tracking data to the trackToFace function.
Definition at line 86 of file solidParticle.H.
Constructor & Destructor Documentation
trackingData (solidParticleCloud & spc, const interpolationCellPoint< scalar > & rhoInterp, const interpolationCellPoint< vector > & UInterp, const interpolationCellPoint< scalar > & nuInterp, const vector & g) inline
Definition at line 29 of file solidParticleI.H.
References solidParticle::solidParticle().
Member Function Documentation
const Foam::interpolationCellPoint< Foam::scalar > & rhoInterp () const inline
Definition at line 65 of file solidParticleI.H.
Referenced by solidParticle::move().
const Foam::interpolationCellPoint< Foam::vector > & UInterp () const inline
Definition at line 72 of file solidParticleI.H.
Referenced by solidParticle::move().
const Foam::interpolationCellPoint< Foam::scalar > & nuInterp () const inline
Definition at line 79 of file solidParticleI.H.
Referenced by solidParticle::move().
const Foam::vector & g () const inline
Definition at line 84 of file solidParticleI.H.
Referenced by solidParticle::move().
The documentation for this class was generated from the following files:
src/lagrangian/solidParticle/solidParticle.H
src/lagrangian/solidParticle/solidParticleI.H