OpenFOAM: wallBoundedParticle::TrackingData< CloudType > Class Template Reference
wallBoundedParticle::TrackingData< CloudType > Class Template Reference
Class used to pass tracking data to the trackToFace function.
Public Member Functions
TrackingData (CloudType &cloud, const PackedBoolList &isWallPatch)
Public Member Functions inherited from particle< Type >::TrackingData< CloudType >
TrackingData (CloudType &cloud)
CloudType & cloud ()
Return a reference to the cloud.
Public Attributes
const PackedBoolList & isWallPatch_
Public Attributes inherited from particle< Type >::TrackingData< CloudType >
bool switchProcessor
Flag to switch processor.
bool keepParticle
Flag to indicate whether to keep particle (false = delete)
Additional Inherited Members
Public Types inherited from particle< Type >::TrackingData< CloudType >
typedef CloudType cloudType
Detailed Description
template<class CloudType>
class Foam::wallBoundedParticle::TrackingData< CloudType >
Class used to pass tracking data to the trackToFace function.
Definition at line 74 of file wallBoundedParticle.H.
Constructor & Destructor Documentation
TrackingData (CloudType & cloud, const PackedBoolList & isWallPatch) inline
Definition at line 86 of file wallBoundedParticle.H.
References Foam::constant::universal::c, wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), wallBoundedParticle::currentEdge(), wallBoundedParticle::diagEdge(), wallBoundedParticle::diagEdge_, wallBoundedParticle::hitCyclicPatch(), wallBoundedParticle::hitPatch(), wallBoundedParticle::hitProcessorPatch(), wallBoundedParticle::hitSymmetryPatch(), wallBoundedParticle::hitSymmetryPlanePatch(), wallBoundedParticle::hitWallPatch(), wallBoundedParticle::hitWedgePatch(), wallBoundedParticle::isTriAlongTrack(), wallBoundedParticle::meshEdgeStart(), wallBoundedParticle::meshEdgeStart_, p, patchi, wallBoundedParticle::patchInteraction(), particle< Type >::position(), wallBoundedParticle::readFields(), wallBoundedParticle::trackFaceTri(), and wallBoundedParticle::wallBoundedParticle().
Member Data Documentation
const PackedBoolList& isWallPatch_
Definition at line 81 of file wallBoundedParticle.H.
The documentation for this class was generated from the following file:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticle.H