OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
streamLineParticle::trackingData Class Reference
Class used to pass tracking data to the trackToFace function.
Public Member Functions
trackingData (Cloud< streamLineParticle > &cloud, const PtrList< interpolation< scalar >> &vsInterp, const PtrList< interpolation< vector >> &vvInterp, const label UIndex, const bool trackForward, const label nSubCycle, const scalar trackLength, DynamicList< List< point >> &allPositions, List< DynamicList< scalarList >> &allScalars, List< DynamicList< vectorList >> &allVectors)
Public Member Functions inherited from particle< Type >::TrackingData< Cloud< streamLineParticle > >
TrackingData (Cloud< streamLineParticle > &cloud)
Cloud< streamLineParticle > & cloud ()
Return a reference to the cloud.
Public Attributes
const PtrList< interpolation< scalar > > & vsInterp_
const PtrList< interpolation< vector > > & vvInterp_
const label UIndex_
const bool trackForward_
const label nSubCycle_
const scalar trackLength_
DynamicList< vectorList > & allPositions_
List< DynamicList< scalarList > > & allScalars_
List< DynamicList< vectorList > > & allVectors_
Public Attributes inherited from particle< Type >::TrackingData< Cloud< streamLineParticle > >
bool switchProcessor
Flag to switch processor.
bool keepParticle
Flag to indicate whether to keep particle (false = delete)
Additional Inherited Members
Public Types inherited from particle< Type >::TrackingData< Cloud< streamLineParticle > >
typedef Cloud< streamLineParticle > cloudType
Detailed Description
Class used to pass tracking data to the trackToFace function.
Definition at line 70 of file streamLineParticle.H.
Constructor & Destructor Documentation
trackingData (Cloud< streamLineParticle > & cloud, const PtrList< interpolation< scalar >> & vsInterp, const PtrList< interpolation< vector >> & vvInterp, const label UIndex, const bool trackForward, const label nSubCycle, const scalar trackLength, DynamicList< List< point >> & allPositions, List< DynamicList< scalarList >> & allScalars, List< DynamicList< vectorList >> & allVectors) inline
Definition at line 93 of file streamLineParticle.H.
References Foam::constant::universal::c, p, particle< Type >::position(), streamLineParticle::readFields(), streamLineParticle::streamLineParticle(), and U.
Member Data Documentation
const PtrList<interpolation<scalar> >& vsInterp_
Definition at line 78 of file streamLineParticle.H.
const PtrList<interpolation<vector> >& vvInterp_
Definition at line 79 of file streamLineParticle.H.
const label UIndex_
Definition at line 80 of file streamLineParticle.H.
const bool trackForward_
Definition at line 81 of file streamLineParticle.H.
Referenced by streamLineParticle::move().
const label nSubCycle_
Definition at line 82 of file streamLineParticle.H.
Referenced by streamLineParticle::move().
const scalar trackLength_
Definition at line 83 of file streamLineParticle.H.
Referenced by streamLineParticle::move().
DynamicList<vectorList>& allPositions_
Definition at line 85 of file streamLineParticle.H.
Referenced by streamLineParticle::move().
List<DynamicList<scalarList> >& allScalars_
Definition at line 86 of file streamLineParticle.H.
Referenced by streamLineParticle::move().
List<DynamicList<vectorList> >& allVectors_
Definition at line 87 of file streamLineParticle.H.
Referenced by streamLineParticle::move().
The documentation for this class was generated from the following file:
src/functionObjects/field/streamLine/streamLineParticle.H