OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallBoundedStreamLineParticle::trackingData Class Reference
Class used to pass tracking data to the trackToEdge function.
Public Member Functions
trackingData (Cloud< wallBoundedStreamLineParticle > &cloud, const PtrList< interpolation< scalar >> &vsInterp, const PtrList< interpolation< vector >> &vvInterp, const label UIndex, const bool trackForward, const scalar trackLength, const PackedBoolList &isWallPatch, DynamicList< List< point >> &allPositions, List< DynamicList< scalarList >> &allScalars, List< DynamicList< vectorList >> &allVectors)
Public Attributes
const PtrList< interpolation< scalar > > & vsInterp_
const PtrList< interpolation< vector > > & vvInterp_
const label UIndex_
const bool trackForward_
const scalar trackLength_
DynamicList< vectorList > & allPositions_
List< DynamicList< scalarList > > & allScalars_
List< DynamicList< vectorList > > & allVectors_
Detailed Description
Class used to pass tracking data to the trackToEdge function.
Definition at line 71 of file wallBoundedStreamLineParticle.H.
Constructor & Destructor Documentation
trackingData (Cloud< wallBoundedStreamLineParticle > & cloud, const PtrList< interpolation< scalar >> & vsInterp, const PtrList< interpolation< vector >> & vvInterp, const label UIndex, const bool trackForward, const scalar trackLength, const PackedBoolList & isWallPatch, DynamicList< List< point >> & allPositions, List< DynamicList< scalarList >> & allScalars, List< DynamicList< vectorList >> & allVectors) inline
Definition at line 96 of file wallBoundedStreamLineParticle.H.
References Foam::constant::universal::c, wallBoundedParticle::diagEdge(), wallBoundedParticle::meshEdgeStart(), p, particle< Type >::position(), wallBoundedStreamLineParticle::readFields(), and wallBoundedStreamLineParticle::wallBoundedStreamLineParticle().
Member Data Documentation
const PtrList<interpolation<scalar> >& vsInterp_
Definition at line 82 of file wallBoundedStreamLineParticle.H.
const PtrList<interpolation<vector> >& vvInterp_
Definition at line 83 of file wallBoundedStreamLineParticle.H.
const label UIndex_
Definition at line 84 of file wallBoundedStreamLineParticle.H.
const bool trackForward_
Definition at line 85 of file wallBoundedStreamLineParticle.H.
const scalar trackLength_
Definition at line 86 of file wallBoundedStreamLineParticle.H.
Referenced by wallBoundedStreamLineParticle::move().
DynamicList<vectorList>& allPositions_
Definition at line 88 of file wallBoundedStreamLineParticle.H.
Referenced by wallBoundedStreamLineParticle::move().
List<DynamicList<scalarList> >& allScalars_
Definition at line 89 of file wallBoundedStreamLineParticle.H.
Referenced by wallBoundedStreamLineParticle::move().
List<DynamicList<vectorList> >& allVectors_
Definition at line 90 of file wallBoundedStreamLineParticle.H.
Referenced by wallBoundedStreamLineParticle::move().
The documentation for this class was generated from the following file:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLineParticle.H