OpenFOAM: topoCellLooper Class Reference
topoCellLooper Class Reference
Implementation of cellLooper. This one recognizes splitHexes and tries to make a cut such that if the neighbour was split (in a previous iteration) this one also gets split in the same direction so that the result will be a mesh without splitHexes.
Public Member Functions
TypeName ("topoCellLooper")
Runtime type information.
topoCellLooper (const polyMesh &mesh)
Construct from components.
virtual ~topoCellLooper ()
Destructor.
virtual bool cut (const vector &refDir, const label celli, const boolList &vertIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, labelList &loop, scalarField &loopWeights) const
Create cut along circumference of celli. Gets current mesh cuts.
virtual bool cut (const plane &cutPlane, const label celli, const boolList &vertIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, labelList &loop, scalarField &loopWeights) const
Same but now also base point of cut provided (instead of always.
Public Member Functions inherited from hexCellLooper
TypeName ("hexCellLooper")
Runtime type information.
hexCellLooper (const polyMesh &mesh)
Construct from components.
virtual ~hexCellLooper ()
Destructor.
Public Member Functions inherited from geomCellLooper
TypeName ("geomCellLooper")
Runtime type information.
geomCellLooper (const polyMesh &mesh)
Construct from components.
virtual ~geomCellLooper ()
Destructor.
Public Member Functions inherited from cellLooper
TypeName ("cellLooper")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, cellLooper, word,(const polyMesh &mesh),(mesh))
cellLooper (const polyMesh &mesh)
Construct from components.
autoPtr< cellLooper > clone () const
Clone.
virtual ~cellLooper ()
Destructor.
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Static Public Attributes
static const scalar featureCos = Foam::cos(degToRad(10.0))
Cos of angle for feature recognition (of splitHexes)
Additional Inherited Members
Static Public Member Functions inherited from geomCellLooper
static scalar snapTol ()
static void setSnapTol (const scalar tol)
Static Public Member Functions inherited from cellLooper
static autoPtr< cellLooper > New (const word &type, const polyMesh &mesh)
Return a reference to the selected cellLooper.
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
Is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
Convert eVert to edge label.
static label getVertex (const primitiveMesh &mesh, const label eVert)
Convert eVert to vertex label.
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointi to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Protected Member Functions inherited from cellLooper
labelList getVertFacesNonEdge (const label celli, const label edgeI, const label vertI) const
Get faces (on cell) connected to vertI which are not using edgeI.
label getFirstVertEdge (const label facei, const label vertI) const
Get first edge connected to vertI and on facei.
labelList getVertEdgesNonFace (const label celli, const label facei, const label vertI) const
Get edges (on cell) connected to vertI which are not on facei.
label getMisAlignedEdge (const vector &refDir, const label celli) const
Return edge from cellEdges that is most perpendicular.
Protected Attributes inherited from hexCellLooper
const cellModel & hex_
Reference to hex cell shape.
Detailed Description
Implementation of cellLooper. This one recognizes splitHexes and tries to make a cut such that if the neighbour was split (in a previous iteration) this one also gets split in the same direction so that the result will be a mesh without splitHexes.
'splitHexes' are cells of which the 'featureEdges' (see cellFeatures class) form a hex. The remaining non-feature edges are assumed to result from splitting the neighbour and this class tries to start from one of these and cut through to an opposite edge.
The current set of cuts (vertIsCut, edgeIsCut, edgeWeight) are not being used by this implementation.
All non-splitHexes are done by the parent classes.
Source files
topoCellLooper.H
topoCellLooper.C
Definition at line 66 of file topoCellLooper.H.
Constructor & Destructor Documentation
topoCellLooper (const polyMesh & mesh)
Construct from components.
Definition at line 683 of file topoCellLooper.C.
~topoCellLooper () virtual
Destructor.
Definition at line 691 of file topoCellLooper.C.
References topoCellLooper::cut().
Member Function Documentation
TypeName ("topoCellLooper")
Runtime type information.
bool cut (const vector & refDir, const label celli, const boolList & vertIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, labelList & loop, scalarField & loopWeights) const virtual
Create cut along circumference of celli. Gets current mesh cuts.
Cut along circumference is expressed as loop of cuts plus weights for cuts along edges (only valid for edge cuts). Return true if successful cut.
Reimplemented from hexCellLooper.
Definition at line 698 of file topoCellLooper.C.
References primitiveMesh::cells(), cellShapes, hexCellLooper::cut(), primitiveMesh::edges(), cellFeatures::faces(), topoCellLooper::featureCos, Foam::meshTools::getEdgeFaces(), cellLooper::getMisAlignedEdge(), hexCellLooper::hex_, Foam::isA(), edgeVertex::mesh(), List< T >::size(), and List< T >::transfer().
Referenced by topoCellLooper::~topoCellLooper().
bool cut (const plane & cutPlane, const label celli, const boolList & vertIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, labelList & loop, scalarField & loopWeights) const virtual
Same but now also base point of cut provided (instead of always.
cell centre)
Reimplemented from hexCellLooper.
Definition at line 809 of file topoCellLooper.C.
References hexCellLooper::cut().
Member Data Documentation
const Foam::scalar featureCos = Foam::cos(degToRad(10.0)) static
Cos of angle for feature recognition (of splitHexes)
Definition at line 161 of file topoCellLooper.H.
Referenced by topoCellLooper::cut().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/cellLooper/topoCellLooper.H
src/dynamicMesh/meshCut/cellLooper/topoCellLooper.C