OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
twoPhaseSystem Class Reference abstract
Class which solves the volume fraction equations for two phases.
Public Member Functions
TypeName ("twoPhaseSystem")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, twoPhaseSystem, dictionary,(const fvMesh &mesh),(mesh))
twoPhaseSystem (const fvMesh &)
Construct from fvMesh.
virtual ~twoPhaseSystem ()
Destructor.
const phaseModel & phase1 () const
Constant access phase model 1.
phaseModel & phase1 ()
Access phase model 1.
const phaseModel & phase2 () const
Constant access phase model 2.
phaseModel & phase2 ()
Access phase model 2.
const phaseModel & otherPhase (const phaseModel &phase) const
Constant access the phase not given as an argument.
virtual autoPtr< momentumTransferTable > momentumTransfer () const =0
Return the momentum transfer matrices.
virtual autoPtr< heatTransferTable > heatTransfer () const =0
Return the heat transfer matrices.
virtual autoPtr< massTransferTable > massTransfer () const =0
Return the mass transfer matrices.
tmp< volScalarField > sigma () const
Return the surface tension coefficient.
const dragModel & drag (const phaseModel &phase) const
Return the drag model for the given phase.
tmp< volScalarField > Kd () const
Return the drag coefficient.
tmp< surfaceScalarField > Kdf () const
Return the face drag coefficient.
const virtualMassModel & virtualMass (const phaseModel &phase) const
Return the virtual mass model for the given phase.
tmp< volScalarField > Vm () const
Return the virtual mass coefficient.
tmp< surfaceScalarField > Vmf () const
Return the face virtual mass coefficient.
tmp< volVectorField > F () const
Return the combined force (lift + wall-lubrication)
tmp< surfaceScalarField > Ff () const
Return the combined face-force (lift + wall-lubrication)
tmp< volScalarField > D () const
Return the turbulent diffusivity.
bool transfersMass () const
Return true if there is mass transfer.
tmp< volScalarField > dmdt () const
Return the interfacial mass flow rate.
virtual void solve ()
Solve for the phase fractions.
twoPhaseSystem (const fvMesh &, const dimensionedVector &g)
Construct from fvMesh.
virtual ~twoPhaseSystem ()
Destructor.
tmp< volScalarField > rho () const
Return the mixture density.
tmp< volVectorField > U () const
Return the mixture velocity.
tmp< volScalarField > Kd () const
Return the drag coefficient.
tmp< surfaceScalarField > Kdf () const
Return the face drag coefficient.
tmp< volScalarField > Vm () const
Return the virtual mass coefficient.
tmp< surfaceScalarField > Vmf () const
Return the face virtual mass coefficient.
tmp< volScalarField > Kh () const
Return the heat transfer coefficient.
tmp< volVectorField > F () const
Return the combined force (lift + wall-lubrication)
tmp< surfaceScalarField > Ff () const
Return the combined face-force (lift + wall-lubrication)
tmp< volScalarField > D () const
Return the turbulent diffusivity.
void solve ()
Solve for the two-phase-fractions.
void correct ()
Correct two-phase properties other than turbulence.
void correctTurbulence ()
Correct two-phase turbulence.
bool read ()
Read base phaseProperties dictionary.
const dragModel & drag (const phaseModel &phase) const
Return the drag model for the given phase.
const virtualMassModel & virtualMass (const phaseModel &phase) const
Return the virtual mass model for the given phase.
const dimensionedScalar & sigma () const
Return the surface tension coefficient.
const fvMesh & mesh () const
Return the mesh.
const phaseModel & phase1 () const
Return phase model 1.
phaseModel & phase1 ()
Return non-const access to phase model 1.
const phaseModel & phase2 () const
Return phase model 2.
phaseModel & phase2 ()
Return non-const access to phase model 2.
const phaseModel & otherPhase (const phaseModel &phase) const
Return the phase not given as an argument.
const surfaceScalarField & phi () const
Return the mixture flux.
surfaceScalarField & phi ()
Return non-const access to the the mixture flux.
const volScalarField & dgdt () const
Return the dilatation term.
volScalarField & dgdt ()
Return non-const access to the dilatation parameter.
tmp< surfaceScalarField > & pPrimeByA ()
Return non-const access to the dispersion diffusivity.
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from IDLList< entry >
IDLList ()
Null construct.
IDLList (const entry &a)
Construct given initial T.
IDLList (Istream &is, const INew &inewt)
Construct from Istream using given Istream constructor class.
IDLList (Istream &is)
Construct from Istream.
IDLList (const IDLList< entry > &idll, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
Public Member Functions inherited from ILList< DLListBase, entry >
ILList ()
Null construct.
ILList (entry *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< DLListBase, entry > &)
Construct as copy.
ILList (const ILList< DLListBase, entry > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (entry *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< DLListBase, entry > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< DLListBase, entry > &)
Public Member Functions inherited from UILList< DLListBase, entry >
UILList ()
Null construct.
UILList (entry *a)
Construct given initial T.
UILList (const UILList< DLListBase, entry > &)
Construct as copy.
entry * first ()
Return the first entry.
const entry * first () const
Return the first entry.
entry * last ()
Return the last entry.
const entry * last () const
Return the last entry.
entry * removeHead ()
Remove and return head.
entry * remove (entry *p)
Remove and return element.
entry * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< DLListBase, entry > &)
iterator begin ()
const_iterator begin () const
const iterator & end ()
const const_iterator & end () const
const_iterator cbegin () const
const const_iterator & cend () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< DLListBase, entry > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< DLListBase, entry > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from DLListBase
DLListBase ()
Null construct.
DLListBase (link *)
Construct given initial entry.
~DLListBase ()
Destructor.
label size () const
Return number of elements in list.
bool empty () const
Return true if the list is empty.
link * first ()
Return first entry.
const link * first () const
Return const access to first entry.
link * last ()
Return last entry.
const link * last () const
Return const access to last entry.
void insert (link *)
Add at head of list.
void append (link *)
Add at tail of list.
bool swapUp (link *)
Swap this element with the one above unless it is at the top.
bool swapDown (link *)
Swap this element with the one below unless it is at the bottom.
link * removeHead ()
Remove and return head.
link * remove (link *)
Remove and return element.
link * remove (iterator &)
link * replace (link *oldLink, link *newLink)
Replace oldLink with newLink and return element.
link * replace (iterator &oldIter, link *newLink)
Replace oldIter with newLink and return element.
void clear ()
Clear the list.
void transfer (DLListBase &)
Transfer the contents of the argument into this List.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
Public Member Functions inherited from phaseSystem
TypeName ("phaseSystem")
Runtime type information.
phaseSystem (const fvMesh &mesh)
Construct from fvMesh.
virtual ~phaseSystem ()
Destructor.
const fvMesh & mesh () const
Constant access the mesh.
const phaseModelList & phases () const
Constant access the phase models.
phaseModelList & phases ()
Access the phase models.
const phasePairTable & phasePairs () const
Constant access the phase pairs.
tmp< volScalarField > rho () const
Return the mixture density.
tmp< volVectorField > U () const
Return the mixture velocity.
const surfaceScalarField & phi () const
Constant access the mixture flux.
surfaceScalarField & phi ()
Access the mixture flux.
const volScalarField & dpdt () const
Constant access the rate of change of the pressure.
volScalarField & dpdt ()
Access the rate of change of the pressure.
tmp< volScalarField > E (const phasePairKey &key) const
Return the aspect-ratio.
tmp< volScalarField > sigma (const phasePairKey &key) const
Return the surface tension coefficient.
const IOMRFZoneList & MRF () const
Return MRF zones.
fv::options & fvOptions () const
Optional FV-options.
template<class modelType >
const modelType & lookupSubModel (const phasePair &key) const
Access a sub model between a phase pair.
template<class modelType >
const modelType & lookupSubModel (const phaseModel &dispersed, const phaseModel &continuous) const
Access a sub model between two phases.
virtual void correctKinematics ()
Correct the kinematics.
virtual void correctThermo ()
Correct the thermodynamics.
virtual void correctEnergyTransport ()
Correct the energy transport e.g. alphat.
Static Public Member Functions
static autoPtr< twoPhaseSystem > New (const fvMesh &mesh)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Protected Attributes
phaseModel & phase1_
Phase model 1.
phaseModel & phase2_
Phase model 2.
Protected Attributes inherited from phaseSystem
const fvMesh & mesh_
Reference to the mesh.
phaseModelList phaseModels_
Phase models.
phasePairTable phasePairs_
Phase pairs.
surfaceScalarField phi_
Total volumetric flux.
volScalarField dpdt_
Rate of change of pressure.
IOMRFZoneList MRF_
Optional MRF zones.
blendingMethodTable blendingMethods_
Blending methods.
surfaceTensionModelTable surfaceTensionModels_
Surface tension models.
aspectRatioModelTable aspectRatioModels_
Aspect ratio models.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< DLListBase, entry >
typedef entry value_type
Type of values the DLList contains.
typedef entry & reference
Type that can be used for storing into DLList::value_type.
typedef const entry & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef DLListBase::iterator LListBase_iterator
typedef DLListBase::const_iterator LListBase_const_iterator
Public Types inherited from phaseSystem
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > KdTable
typedef HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash > VmTable
typedef HashPtrTable< fvVectorMatrix, word, string::hash > momentumTransferTable
typedef HashPtrTable< fvScalarMatrix, word, string::hash > heatTransferTable
typedef HashPtrTable< fvScalarMatrix, word, string::hash > massTransferTable
typedef PtrListDictionary< phaseModel > phaseModelList
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Static Public Attributes inherited from phaseSystem
static const word propertiesName
Default name of the phase properties dictionary.
Protected Types inherited from phaseSystem
typedef HashTable< dictionary, phasePairKey, phasePairKey::hash > dictTable
typedef HashTable< autoPtr< phasePair >, phasePairKey, phasePairKey::hash > phasePairTable
typedef HashTable< autoPtr< blendingMethod >, word, word::hash > blendingMethodTable
typedef HashTable< autoPtr< surfaceTensionModel >, phasePairKey, phasePairKey::hash > surfaceTensionModelTable
typedef HashTable< autoPtr< aspectRatioModel >, phasePairKey, phasePairKey::hash > aspectRatioModelTable
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from phaseSystem
tmp< surfaceScalarField > calcPhi (const phaseModelList &phaseModels) const
Calculate and return the mixture flux.
void generatePairs (const dictTable &modelDicts)
Generate pairs.
template<class modelType >
void createSubModels (const dictTable &modelDicts, HashTable< autoPtr< modelType >, phasePairKey, phasePairKey::hash > &models)
Generate pairs and sub-model tables.
template<class modelType >
void generatePairsAndSubModels (const word &modelName, HashTable< autoPtr< modelType >, phasePairKey, phasePairKey::hash > &models)
Generate pairs and sub-model tables.
template<class modelType >
void generatePairsAndSubModels (const word &modelName, HashTable< autoPtr< BlendedInterfacialModel< modelType >>, phasePairKey, phasePairKey::hash > &models)
Generate pairs and blended sub-model tables.
template<class modelType >
void generatePairsAndSubModels (const word &modelName, HashTable< HashTable< autoPtr< modelType >>, phasePairKey, phasePairKey::hash > &models)
Generate pairs and per-phase sub-model tables.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Class which solves the volume fraction equations for two phases.
Source files
twoPhaseSystem.H
twoPhaseSystem.C
Source files
twoPhaseSystem.H
twoPhaseSystem.C
Definition at line 51 of file twoPhaseSystem.H.
Constructor & Destructor Documentation
twoPhaseSystem (const fvMesh &)
Construct from fvMesh.
virtual ~twoPhaseSystem () virtual
Destructor.
twoPhaseSystem (const fvMesh & , const dimensionedVector & g)
Construct from fvMesh.
virtual ~twoPhaseSystem () virtual
Destructor.
Member Function Documentation
TypeName ("twoPhaseSystem")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , twoPhaseSystem , dictionary , (const fvMesh &mesh) , (mesh))
static autoPtr<twoPhaseSystem> New (const fvMesh & mesh) static
const Foam::phaseModel & phase1 () const inline
Constant access phase model 1.
Definition at line 28 of file twoPhaseSystemI.H.
References twoPhaseSystem::phase1_.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::correct(), and twoPhaseSystem::mesh().
Foam::phaseModel & phase1 () inline
Access phase model 1.
Definition at line 34 of file twoPhaseSystemI.H.
References twoPhaseSystem::phase1_.
const Foam::phaseModel & phase2 () const inline
Constant access phase model 2.
Definition at line 40 of file twoPhaseSystemI.H.
References twoPhaseSystem::phase2_.
Referenced by twoPhaseSystem::mesh().
Foam::phaseModel & phase2 () inline
Access phase model 2.
Definition at line 46 of file twoPhaseSystemI.H.
References twoPhaseSystem::otherPhase(), and twoPhaseSystem::phase2_.
const Foam::phaseModel & otherPhase (const phaseModel & phase) const inline
Constant access the phase not given as an argument.
Definition at line 53 of file twoPhaseSystemI.H.
References twoPhaseSystem::phase1_, and twoPhaseSystem::phase2_.
Referenced by NicenoKEqn< BasicTurbulenceModel >::bubbleG(), LaheyKEpsilon< BasicTurbulenceModel >::bubbleG(), mixtureKEpsilon< BasicTurbulenceModel >::bubbleG(), continuousGasKEpsilon< BasicTurbulenceModel >::correctNut(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), twoPhaseSystem::mesh(), IATEsource::otherPhase(), twoPhaseSystem::phase2(), SmagorinskyZhang< BasicTurbulenceModel >::read(), NicenoKEqn< BasicTurbulenceModel >::read(), LaheyKEpsilon< BasicTurbulenceModel >::read(), kOmegaSSTSato< BasicTurbulenceModel >::read(), continuousGasKEpsilon< BasicTurbulenceModel >::rhoEff(), mixtureKEpsilon< BasicTurbulenceModel >::rhogEff(), and mixtureKEpsilon< BasicTurbulenceModel >::rholEff().
virtual autoPtr<momentumTransferTable> momentumTransfer () const pure virtual
Return the momentum transfer matrices.
virtual autoPtr<heatTransferTable> heatTransfer () const pure virtual
Return the heat transfer matrices.
virtual autoPtr<massTransferTable> massTransfer () const pure virtual
Return the mass transfer matrices.
tmp<volScalarField> sigma () const
Return the surface tension coefficient.
const dragModel& drag (const phaseModel & phase) const
Return the drag model for the given phase.
Referenced by NicenoKEqn< BasicTurbulenceModel >::bubbleG(), LaheyKEpsilon< BasicTurbulenceModel >::bubbleG(), mixtureKEpsilon< BasicTurbulenceModel >::bubbleG(), and mixtureKEpsilon< BasicTurbulenceModel >::Ct2().
tmp<volScalarField> Kd () const
Return the drag coefficient.
tmp<surfaceScalarField> Kdf () const
Return the face drag coefficient.
const virtualMassModel& virtualMass (const phaseModel & phase) const
Return the virtual mass model for the given phase.
Referenced by continuousGasKEpsilon< BasicTurbulenceModel >::correctNut(), continuousGasKEpsilon< BasicTurbulenceModel >::rhoEff(), and mixtureKEpsilon< BasicTurbulenceModel >::rhogEff().
tmp<volScalarField> Vm () const
Return the virtual mass coefficient.
tmp<surfaceScalarField> Vmf () const
Return the face virtual mass coefficient.
tmp<volVectorField> F () const
Return the combined force (lift + wall-lubrication)
tmp<surfaceScalarField> Ff () const
Return the combined face-force (lift + wall-lubrication)
tmp<volScalarField> D () const
Return the turbulent diffusivity.
Multiplies the phase-fraction gradient
bool transfersMass () const
Return true if there is mass transfer.
tmp<volScalarField> dmdt () const
Return the interfacial mass flow rate.
virtual void solve () virtual
Solve for the phase fractions.
Reimplemented from phaseSystem.
tmp<volScalarField> rho () const
Return the mixture density.
tmp<volVectorField> U () const
Return the mixture velocity.
tmp<volScalarField> Kd () const
Return the drag coefficient.
tmp<surfaceScalarField> Kdf () const
Return the face drag coefficient.
tmp<volScalarField> Vm () const
Return the virtual mass coefficient.
tmp<surfaceScalarField> Vmf () const
Return the face virtual mass coefficient.
tmp<volScalarField> Kh () const
Return the heat transfer coefficient.
tmp<volVectorField> F () const
Return the combined force (lift + wall-lubrication)
tmp<surfaceScalarField> Ff () const
Return the combined face-force (lift + wall-lubrication)
tmp<volScalarField> D () const
Return the turbulent diffusivity.
Multiplies the phase-fraction gradient
void solve () virtual
Solve for the two-phase-fractions.
Reimplemented from phaseSystem.
void correct () virtual
Correct two-phase properties other than turbulence.
Reimplemented from phaseSystem.
void correctTurbulence () virtual
Correct two-phase turbulence.
Reimplemented from phaseSystem.
bool read () virtual
Read base phaseProperties dictionary.
Reimplemented from phaseSystem.
const dragModel& drag (const phaseModel & phase) const
Return the drag model for the given phase.
const virtualMassModel& virtualMass (const phaseModel & phase) const
Return the virtual mass model for the given phase.
const dimensionedScalar& sigma () const
Return the surface tension coefficient.
const Foam::fvMesh & mesh () const inline
Return the mesh.
Definition at line 28 of file twoPhaseSystemI.H.
References twoPhaseSystem::otherPhase(), twoPhaseSystem::phase1(), twoPhaseSystem::phase1_, twoPhaseSystem::phase2(), and twoPhaseSystem::phase2_.
const phaseModel& phase1 () const inline
Return phase model 1.
phaseModel& phase1 () inline
Return non-const access to phase model 1.
const phaseModel& phase2 () const inline
Return phase model 2.
phaseModel& phase2 () inline
Return non-const access to phase model 2.
const phaseModel& otherPhase (const phaseModel & phase) const inline
Return the phase not given as an argument.
const Foam::surfaceScalarField & phi () const inline
Return the mixture flux.
Definition at line 74 of file twoPhaseSystemI.H.
Foam::surfaceScalarField & phi () inline
Return non-const access to the the mixture flux.
Definition at line 80 of file twoPhaseSystemI.H.
const Foam::volScalarField & dgdt () const inline
Return the dilatation term.
Definition at line 86 of file twoPhaseSystemI.H.
Foam::volScalarField & dgdt () inline
Return non-const access to the dilatation parameter.
Definition at line 92 of file twoPhaseSystemI.H.
Foam::tmp< Foam::surfaceScalarField > & pPrimeByA () inline
Return non-const access to the dispersion diffusivity.
Definition at line 98 of file twoPhaseSystemI.H.
Member Data Documentation
phaseModel& phase1_ protected
Phase model 1.
Definition at line 92 of file twoPhaseSystem.H.
Referenced by twoPhaseSystem::mesh(), twoPhaseSystem::otherPhase(), and twoPhaseSystem::phase1().
phaseModel& phase2_ protected
Phase model 2.
Definition at line 95 of file twoPhaseSystem.H.
Referenced by twoPhaseSystem::mesh(), twoPhaseSystem::otherPhase(), and twoPhaseSystem::phase2().
The documentation for this class was generated from the following files:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/twoPhaseSystem.H
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/twoPhaseSystemI.H