OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
VectorSpace< Form, Cmpt, nCmpt > Class Template Reference
Templated vector space.
Public Types
enum { dim = 3, nComponents = nCmpt }
typedef Cmpt cmptType
Component type.
Public Member Functions
VectorSpace ()
Construct null.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Form, Cmpt, nCmpt > &)
Construct as copy.
template<class Form2 , class Cmpt2 >
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > &)
Construct as copy of another VectorSpace type of the same rank.
label size () const
Return the number of elements in the VectorSpace = nCmpt.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator-= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator*= (const scalar)
void operator/= (const scalar)
Public Attributes
Cmpt v_ [nCmpt]
The components of this vector space.
Friends
Istream & operator>> (Istream &, VectorSpace< Form, Cmpt, nCmpt > &)
Ostream & operator (Ostream &, const VectorSpace< Form, Cmpt, nCmpt > &)
Detailed Description
template<class Form, class Cmpt, int nCmpt>
class Foam::VectorSpace< Form, Cmpt, nCmpt >
Templated vector space.
Template arguments are the Form the vector space will be used to create, the type of the elements and the number of elements.
Source files
VectorSpace.H
VectorSpaceI.H
VectorSpace.C
Definition at line 52 of file VectorSpace.H.
Member Typedef Documentation
typedef Cmpt cmptType
Component type.
Definition at line 80 of file VectorSpace.H.
Member Enumeration Documentation
anonymous enum
Enumerator
dim
Dimensionality of space.
nComponents
Number of components in this vector space.
Definition at line 85 of file VectorSpace.H.
Constructor & Destructor Documentation
VectorSpace () inline
Construct null.
Definition at line 39 of file VectorSpaceI.H.
Referenced by VectorSpace< Form, Cmpt, nCmpt >::VectorSpace().
VectorSpace (Istream & is)
Construct from Istream.
Definition at line 36 of file VectorSpace.C.
References IOstream::check(), Foam::name(), Istream::readBegin(), Istream::readEnd(), and VectorSpace< Form, Cmpt, nCmpt >::v_.
VectorSpace (const VectorSpace< Form, Cmpt, nCmpt > & vs) inline
Construct as copy.
Definition at line 45 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOp(), and VectorSpace< Form, Cmpt, nCmpt >::VectorSpace().
VectorSpace (const VectorSpace< Form2, Cmpt2, nCmpt > & vs) inline
Construct as copy of another VectorSpace type of the same rank.
Definition at line 56 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOp().
Member Function Documentation
label size () const inline
Return the number of elements in the VectorSpace = nCmpt.
Definition at line 67 of file VectorSpaceI.H.
References VectorSpace< Form, Cmpt, nCmpt >::component().
Referenced by edgeCollapser::checkMeshQuality(), streamLineParticle::move(), and createShellMesh::setRefinement().
const Cmpt & component (const direction d) const inline
Definition at line 75 of file VectorSpaceI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by VectorSpace< Form, Cmpt, nCmpt >::component(), Foam::component(), EulerCoordinateRotation::EulerCoordinateRotation(), cellMDLimitedGrad< Type >::limitFace(), Random::position(), Foam::setComponent(), VectorSpace< Form, Cmpt, nCmpt >::size(), STARCDCoordinateRotation::STARCDCoordinateRotation(), Random::symmTensor01(), Random::tensor01(), and Random::vector01().
Cmpt & component (const direction d) inline
Definition at line 94 of file VectorSpaceI.H.
References Foam::abort(), VectorSpace< Form, Cmpt, nCmpt >::component(), Foam::FatalError, and FatalErrorInFunction.
void component (Cmpt & c, const direction d) const inline
Definition at line 113 of file VectorSpaceI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and VectorSpace< Form, Cmpt, nCmpt >::replace().
void replace (const direction d, const Cmpt & c) inline
Definition at line 133 of file VectorSpaceI.H.
References Foam::abort(), Foam::constant::universal::c, Foam::FatalError, and FatalErrorInFunction.
Referenced by VectorSpace< Form, Cmpt, nCmpt >::component().
const Cmpt & operator[] (const direction d) const inline
Definition at line 155 of file VectorSpaceI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Cmpt & operator[] (const direction d) inline
Definition at line 174 of file VectorSpaceI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
void operator= (const VectorSpace< Form, Cmpt, nCmpt > & vs) inline
Definition at line 193 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOp().
void operator+= (const VectorSpace< Form, Cmpt, nCmpt > & vs) inline
Definition at line 203 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOp().
void operator-= (const VectorSpace< Form, Cmpt, nCmpt > & vs) inline
Definition at line 213 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOp().
void operator*= (const scalar s) inline
Definition at line 223 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOpS(), and s().
void operator/= (const scalar s) inline
Definition at line 233 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOpS(), s(), and Foam::setComponent().
Friends And Related Function Documentation
Istream& operator>> (Istream & , VectorSpace< Form, Cmpt, nCmpt > &) friend
Ostream& operator (Ostream & , const VectorSpace< Form, Cmpt, nCmpt > &) friend
Member Data Documentation
Cmpt v_[nCmpt]
The components of this vector space.
Definition at line 95 of file VectorSpace.H.
Referenced by Foam::cmptMax(), Foam::cmptMin(), Foam::cmptProduct(), Foam::cmptSum(), Foam::magSqr(), Foam::operator&&(), Foam::operator<(), Foam::operator==(), Foam::operator>(), and VectorSpace< Form, Cmpt, nCmpt >::VectorSpace().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/VectorSpace/VectorSpace.H
src/OpenFOAM/primitives/VectorSpace/VectorSpace.C
src/OpenFOAM/primitives/VectorSpace/VectorSpaceI.H