OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
timeSelector Class Reference
A List of scalarRange for selecting times.
Public Member Functions
timeSelector ()
Construct Null.
timeSelector (Istream &)
Construct from Istream.
bool selected (const instant &) const
Return true if the given instant is within the ranges.
List< bool > selected (const instantList &) const
Return the set of selected instants in the given list that are.
instantList select (const instantList &) const
Select a list of Time values that are within the ranges.
void inplaceSelect (instantList &) const
Select a list of Time values that are within the ranges.
Public Member Functions inherited from scalarRanges
scalarRanges ()
Construct Null.
scalarRanges (Istream &)
Construct from Istream.
bool selected (const scalar) const
Return true if the given value is within the ranges.
List< bool > selected (const List< scalar > &) const
Return the set of selected entries in the given list.
List< scalar > select (const List< scalar > &) const
Select a list of values that are within the ranges.
void inplaceSelect (List< scalar > &) const
Select a list of values that are within the ranges.
Public Member Functions inherited from List< scalarRange >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const scalarRange &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< scalarRange > &)
Copy constructor.
List (const Xfer< List< scalarRange >> &)
Construct by transferring the parameter contents.
List (List< scalarRange > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< scalarRange > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< scalarRange, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< scalarRange > &)
Construct as copy of PtrList<T>
List (const SLList< scalarRange > &)
Construct as copy of SLList<T>
List (const UIndirectList< scalarRange > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< scalarRange > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< scalarRange > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const scalarRange &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const scalarRange &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const scalarRange &)
Append an element at the end of the list.
void append (const UList< scalarRange > &)
Append a List at the end of this list.
void append (const UIndirectList< scalarRange > &)
Append a UIndirectList at the end of this list.
void transfer (List< scalarRange > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< scalarRange, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< scalarRange > &)
Transfer the contents of the argument List into this list.
Xfer< List< scalarRange > > xfer ()
Transfer contents to the Xfer container.
scalarRange & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< scalarRange > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< scalarRange > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< scalarRange > &)
Assignment operator. Takes linear time.
void operator= (const SLList< scalarRange > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< scalarRange > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< scalarRange > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const scalarRange &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static void addOptions (const bool constant=true, const bool withZero=false)
Add the options handled by timeSelector to argList::validOptions.
static instantList select (const instantList &, const argList &args, const word &constantName="constant")
Return the set of times selected based on the argList options.
static instantList select0 (Time &runTime, const argList &args)
Return the set of times selected based on the argList options.
static instantList selectIfPresent (Time &runTime, const argList &args)
If any time option provided return the set of times (as select0)
static instantList select (Time &runTime, const argList &args, const word &fName)
Return the set of times selected based on the argList options.
Static Public Member Functions inherited from List< scalarRange >
static const List< scalarRange > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Additional Inherited Members
Public Types inherited from List< scalarRange >
typedef SubList< scalarRange > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Protected Member Functions inherited from List< scalarRange >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
A List of scalarRange for selecting times.
The timeSelector provides a convenient means of selecting multiple times. A typical use would be the following:
timeSelector::addOptions();
// add other options
#include "setRootCase.H"
#include "createTime.H"
instantList timeDirs = timeSelector::select0(runTime, args);
...
forAll(timeDirs, timeI)
{
    ...
}
The result program would receive -time, -latestTime, -constant and -noZero options. The -constant option explicitly includes the constant/ directory in the time list and the -noZero option explicitly excludes the 0/ directory from the time list.
There may however also be many cases in which neither the constant/ directory nor the 0/ directory contain particularly relevant information. This might occur, for example, when post-processing results. In this case, addOptions is called with optional boolean arguments.
timeSelector::addOptions(false, true);
The first argument avoids adding the -constant option. The second argument adds an additional -withZero option and also prevents the 0/ directory from being included in the default time range and in the -latestTime selection.
Source files
timeSelector.H
timeSelector.C
Definition at line 89 of file timeSelector.H.
Constructor & Destructor Documentation
timeSelector ()
Construct Null.
Definition at line 34 of file timeSelector.C.
Referenced by timeSelector::select().
timeSelector (Istream & is)
Construct from Istream.
Definition at line 40 of file timeSelector.C.
Member Function Documentation
bool selected (const instant & value) const
Return true if the given instant is within the ranges.
Definition at line 48 of file timeSelector.C.
References scalarRanges::selected(), and instant::value().
Referenced by timeSelector::inplaceSelect(), timeSelector::select(), and timeSelector::selected().
Foam::List< bool > selected (const instantList & Times) const
Return the set of selected instants in the given list that are.
within the ranges
Definition at line 54 of file timeSelector.C.
References Foam::diff(), forAll, Foam::name(), UList< T >::operator[](), timeSelector::selected(), and List< T >::size().
Foam::instantList select (const instantList & Times) const
Select a list of Time values that are within the ranges.
Definition at line 100 of file timeSelector.C.
References timeSelector::selected(), and Foam::subset().
Referenced by timeSelector::addOptions(), timeSelector::select0(), and timeSelector::selectIfPresent().
void inplaceSelect (instantList & Times) const
Select a list of Time values that are within the ranges.
Definition at line 107 of file timeSelector.C.
References timeSelector::addOptions(), Foam::inplaceSubset(), and timeSelector::selected().
void addOptions (const bool constant = true, const bool withZero = false) static
Add the options handled by timeSelector to argList::validOptions.
Parameters
constant Add the -constant option to include the constant/ directory
withZero Enable the -withZero option and alter the normal time selection behaviour (and -latestTime behaviour) to exclude the 0/ directory. The 0/ directory will only be included when -withZero is specified. The -noZero option has precedence over the -withZero option.
Definition at line 114 of file timeSelector.C.
References argList::addBoolOption(), argList::addOption(), and timeSelector::select().
Referenced by if(), and timeSelector::inplaceSelect().
Foam::instantList select (const instantList & timeDirs, const argList & args, const word & constantName = "constant") static
Return the set of times selected based on the argList options.
Definition at line 161 of file timeSelector.C.
References forAll, found, Foam::name(), argList::optionFound(), argList::optionLookup(), timeSelector::select0(), List< T >::size(), Foam::subset(), timeDirs, timeSelector::timeSelector(), and argList::validOptions.
Foam::instantList select0 (Time & runTime, const argList & args) static
Return the set of times selected based on the argList options.
also set the runTime to the first instance or the constant/ directory if no instances are specified or available
Definition at line 253 of file timeSelector.C.
References List< T >::append(), args, TimePaths::constant(), UList< T >::empty(), Foam::endl(), timeSelector::select(), timeSelector::selectIfPresent(), Time::setTime(), timeDirs, Time::times(), and WarningInFunction.
Referenced by if(), timeSelector::select(), and timeSelector::selectIfPresent().
Foam::instantList selectIfPresent (Time & runTime, const argList & args) static
If any time option provided return the set of times (as select0)
otherwise return just the current time. Also set the runTime to the first instance
Definition at line 284 of file timeSelector.C.
References argList::optionFound(), timeSelector::select(), timeSelector::select0(), Time::timeName(), and dimensioned< Type >::value().
Referenced by timeSelector::select0().
Foam::instantList select (Time & runTime, const argList & args, const word & fName) static
Return the set of times selected based on the argList options.
including support for -newTimes in which times are selected if the file 'fName' does not exist in the time directory. Also set the runTime to the first instance or the constant/ directory if no instances are specified or available
Definition at line 309 of file timeSelector.C.
References Foam::exists(), forAll, argList::optionFound(), Time::path(), timeSelector::select0(), List< T >::size(), Foam::subset(), and timeDirs.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/timeSelector.H
src/OpenFOAM/db/Time/timeSelector.C