OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
variableHeatTransfer Class Reference
Variable heat transfer model depending on local values. The area of contact between regions (area) must be provided. The Nu number is calculated as:
Public Member Functions
TypeName ("variableHeatTransfer")
Runtime type information.
variableHeatTransfer (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from dictionary.
virtual ~variableHeatTransfer ()
Destructor.
virtual void calculateHtc ()
Calculate the heat transfer coefficient.
virtual void writeData (Ostream &) const
Write data.
virtual bool read (const dictionary &dict)
Read dictionary.
Public Member Functions inherited from interRegionHeatTransferModel
TypeName ("interRegionHeatTransferModel")
Runtime type information.
interRegionHeatTransferModel (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from dictionary.
virtual ~interRegionHeatTransferModel ()
Destructor.
const volScalarField & htc () const
Return the heat transfer coefficient.
const
interRegionHeatTransferModel & nbrModel () const
Return const access to the neighbour model.
interRegionHeatTransferModel & nbrModel ()
Return access to the neighbour model.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldI)
Source term to energy equation.
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Source term to compressible energy equation.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &field) const
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh, const bool master=false)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
const labelList & cells () const
Return const access to the cell set.
void setApplied (const label fieldI)
Set the applied flag to true for field index fieldI.
bool & active ()
Return access to the source active flag.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void correct (volScalarField &fld)
Scalar.
virtual void correct (volVectorField &fld)
Vector.
virtual void correct (volSphericalTensorField &fld)
Spherical tensor.
virtual void correct (volSymmTensorField &fld)
Symmetric tensor.
virtual void correct (volTensorField &fld)
Tensor.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void setValue (fvMatrix< scalar > &eqn, const label fieldI)
Scalar.
virtual void setValue (fvMatrix< vector > &eqn, const label fieldI)
Vector.
virtual void setValue (fvMatrix< sphericalTensor > &eqn, const label fieldI)
Spherical tensor.
virtual void setValue (fvMatrix< symmTensor > &eqn, const label fieldI)
Symmetric tensor.
virtual void setValue (fvMatrix< tensor > &eqn, const label fieldI)
Tensor.
virtual void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative.
virtual void makeRelative (FieldField< fvsPatchField, scalar > &phi) const
Make the given absolute boundary flux relative.
virtual void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative.
virtual void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute.
virtual void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute.
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
Additional Inherited Members
Public Types inherited from option
enum selectionModeType {
smPoints, smCellSet, smCellZone, smMapRegion,
smAll
}
Enumeration for selection mode types.
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Static Public Attributes inherited from option
static const NamedEnum
< selectionModeType, 5 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Member Functions inherited from interRegionHeatTransferModel
void setNbrModel ()
Set the neighbour interRegionHeatTransferModel.
void correct ()
Correct to calculate the inter-region heat transfer coefficient.
template<class Type >
tmp< Field< Type > > interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field) const
Interpolate field with nbrModel specified.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &field) const
Interpolate field without nbrModel specified.
template<class Type >
void interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field, Field< Type > &result) const
Interpolate field with nbrModel specified.
template<class Type >
void interpolate (const Field< Type > &field, Field< Type > &result) const
Interpolate field without nbrModel specified.
Protected Member Functions inherited from option
virtual bool alwaysApply () const
Flag to bypass the apply flag list checking.
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Protected Attributes inherited from interRegionHeatTransferModel
volScalarField htc_
Heat transfer coefficient [W/m2/k] times area/volume [1/m].
bool semiImplicit_
Flag to activate semi-implicit coupling.
word TName_
Name of temperature field; default = "T".
word TNbrName_
Name of neighbour temperature field; default = "T".
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
bool active_
Source active flag.
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
autoPtr< meshToMesh > meshInterpPtr_
Mesh to mesh interpolation object.
word nbrRegionName_
Name of the neighbour region to map.
bool master_
Master or slave region.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Detailed Description
Variable heat transfer model depending on local values. The area of contact between regions (area) must be provided. The Nu number is calculated as:
Nu = a*pow(Re, b)*pow(Pr, c)
and the heat transfer coefficient as:
htc = Nu*K/ds
where: K is the heat conduction ds is the strut diameter
Definition at line 59 of file variableHeatTransfer.H.
Constructor & Destructor Documentation
variableHeatTransfer (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from dictionary.
Definition at line 50 of file variableHeatTransfer.C.
References readScalar.
~variableHeatTransfer () virtual
Destructor.
Definition at line 94 of file variableHeatTransfer.C.
Member Function Documentation
TypeName ("variableHeatTransfer")
Runtime type information.
void calculateHtc () virtual
Calculate the heat transfer coefficient.
Implements interRegionHeatTransferModel.
Definition at line 100 of file variableHeatTransfer.C.
References Foam::interpolate(), objectRegistry::lookupObject(), Foam::mag(), Foam::pow(), turbulenceModel::propertiesName, and fvMesh::time().
void writeData (Ostream & os) const virtual
Write data.
Reimplemented from interRegionHeatTransferModel.
Definition at line 129 of file variableHeatTransfer.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::nl, Foam::type(), and interRegionHeatTransferModel::writeData().
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from interRegionHeatTransferModel.
Definition at line 143 of file variableHeatTransfer.C.
References option::read().
The documentation for this class was generated from the following files:
src/fvOptions/sources/interRegion/interRegionHeatTransferModel/variableHeatTransfer/variableHeatTransfer.H
src/fvOptions/sources/interRegion/interRegionHeatTransferModel/variableHeatTransfer/variableHeatTransfer.C