OpenFOAM-dev: timeVaryingAlphaContactAngleFvPatchScalarField Class Reference 2
timeVaryingAlphaContactAngleFvPatchScalarField Class Reference
A time-varying alphaContactAngle scalar boundary condition (alphaContactAngleFvPatchScalarField)
Public Member Functions
TypeName ("timeVaryingAlphaContactAngle")
Runtime type information.
timeVaryingAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
timeVaryingAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
timeVaryingAlphaContactAngleFvPatchScalarField (const timeVaryingAlphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
timeVaryingAlphaContactAngleFvPatchScalarField (const timeVaryingAlphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const
Evaluate and return the time-varying equilibrium contact-angle.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from alphaContactAngleFvPatchScalarField
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &)
Construct as copy.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
Additional Inherited Members
Public Types inherited from alphaContactAngleFvPatchScalarField
enum limitControls { lcNone, lcGradient, lcZeroGradient, lcAlpha }
Alpha limit options.
typedef HashTable< interfaceThetaProps, multiphaseMixtureThermo::interfacePair, multiphaseMixtureThermo::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseSystem::interfacePair, multiphaseSystem::interfacePair::symmHash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseMixture::interfacePair, multiphaseMixture::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, phasePairKey, phasePairKey::hash > thetaPropsTable
Public Attributes inherited from alphaContactAngleFvPatchScalarField
limitControls limit_
Static Public Attributes inherited from alphaContactAngleFvPatchScalarField
static const NamedEnum< limitControls, 4 > limitControlNames_
Detailed Description
A time-varying alphaContactAngle scalar boundary condition (alphaContactAngleFvPatchScalarField)
Source files
timeVaryingAlphaContactAngleFvPatchScalarField.H
timeVaryingAlphaContactAngleFvPatchScalarField.C
Definition at line 49 of file timeVaryingAlphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
timeVaryingAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
Referenced by timeVaryingAlphaContactAngleFvPatchScalarField::clone(), and timeVaryingAlphaContactAngleFvPatchScalarField::timeVaryingAlphaContactAngleFvPatchScalarField().
timeVaryingAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 68 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
References timeVaryingAlphaContactAngleFvPatchScalarField::timeVaryingAlphaContactAngleFvPatchScalarField().
timeVaryingAlphaContactAngleFvPatchScalarField (const timeVaryingAlphaContactAngleFvPatchScalarField & gcpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
timeVaryingAlphaContactAngleFvPatchScalarField onto a new patch
Definition at line 51 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
References timeVaryingAlphaContactAngleFvPatchScalarField::timeVaryingAlphaContactAngleFvPatchScalarField().
timeVaryingAlphaContactAngleFvPatchScalarField (const timeVaryingAlphaContactAngleFvPatchScalarField & gcpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 86 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
References timeVaryingAlphaContactAngleFvPatchScalarField::theta().
Member Function Documentation
TypeName ("timeVaryingAlphaContactAngle")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 96 of file timeVaryingAlphaContactAngleFvPatchScalarField.H.
References timeVaryingAlphaContactAngleFvPatchScalarField::timeVaryingAlphaContactAngleFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 113 of file timeVaryingAlphaContactAngleFvPatchScalarField.H.
References timeVaryingAlphaContactAngleFvPatchScalarField::theta(), timeVaryingAlphaContactAngleFvPatchScalarField::timeVaryingAlphaContactAngleFvPatchScalarField(), and timeVaryingAlphaContactAngleFvPatchScalarField::write().
Foam::tmp< Foam::scalarField > theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const virtual
Evaluate and return the time-varying equilibrium contact-angle.
Implements alphaContactAngleFvPatchScalarField.
Definition at line 103 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
References scalarField(), and timeVaryingAlphaContactAngleFvPatchScalarField::write().
Referenced by timeVaryingAlphaContactAngleFvPatchScalarField::clone(), and timeVaryingAlphaContactAngleFvPatchScalarField::timeVaryingAlphaContactAngleFvPatchScalarField().
void write (Ostream & os) const virtual
Write.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 129 of file timeVaryingAlphaContactAngleFvPatchScalarField.C.
References Foam::makePatchTypeField(), Foam::nl, write(), and Ostream::writeKeyword().
Referenced by timeVaryingAlphaContactAngleFvPatchScalarField::clone(), and timeVaryingAlphaContactAngleFvPatchScalarField::theta().
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaContactAngle/timeVaryingAlphaContactAngle/timeVaryingAlphaContactAngleFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaContactAngle/timeVaryingAlphaContactAngle/timeVaryingAlphaContactAngleFvPatchScalarField.C