OpenFOAM: TRIsurfaceFormatCore Class Reference
TRIsurfaceFormatCore Class Reference
Internal class used by the TRIsurfaceFormat.
Public Member Functions
TRIsurfaceFormatCore (const fileName &)
Read from file, filling in the information.
~TRIsurfaceFormatCore ()
Destructor.
bool sorted () const
File read was already sorted.
void clear ()
Flush all values.
pointField & points ()
Return full access to the points.
List< label > & zoneIds ()
Return full access to the zones.
List< label > & sizes ()
The list of zone sizes in the order of their first appearance.
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()
Construct null.
virtual ~surfaceFormatsCore ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
static fileName localMeshFileName (const word &surfName="")
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName="")
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName="")
Find mesh file with surfName.
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Static Protected Member Functions inherited from surfaceFormatsCore
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a list with a single entry,.
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
Internal class used by the TRIsurfaceFormat.
Source files
TRIsurfaceFormatCore.H
TRIsurfaceFormatCore.C
Definition at line 55 of file TRIsurfaceFormatCore.H.
Constructor & Destructor Documentation
TRIsurfaceFormatCore (const fileName & filename)
Read from file, filling in the information.
Definition at line 35 of file TRIsurfaceFormatCore.C.
References Foam::read().
~TRIsurfaceFormatCore ()
Destructor.
Definition at line 50 of file TRIsurfaceFormatCore.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), TRIsurfaceFormatCore::clear(), HashTableCore::end(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), forAll, surfaceFormatsCore::getLineNoComment(), IOstream::good(), HashTable< T, Key, Hash >::insert(), lookup(), Foam::name(), p, Foam::readScalar(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), List< T >::size(), and List< T >::transfer().
Member Function Documentation
bool sorted () const inline
File read was already sorted.
Definition at line 99 of file TRIsurfaceFormatCore.H.
Referenced by TRIsurfaceFormat< Face >::read().
void clear () inline
Flush all values.
Definition at line 105 of file TRIsurfaceFormatCore.H.
References List< T >::clear().
Referenced by TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
pointField& points () inline
Return full access to the points.
Definition at line 114 of file TRIsurfaceFormatCore.H.
Referenced by TRIsurfaceFormat< Face >::read().
List<label>& zoneIds () inline
Return full access to the zones.
Definition at line 120 of file TRIsurfaceFormatCore.H.
Referenced by TRIsurfaceFormat< Face >::read().
List<label>& sizes () inline
The list of zone sizes in the order of their first appearance.
Definition at line 126 of file TRIsurfaceFormatCore.H.
Referenced by TRIsurfaceFormat< Face >::read().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/tri/TRIsurfaceFormatCore.H
src/surfMesh/surfaceFormats/tri/TRIsurfaceFormatCore.C