OpenFOAM: TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel > Class Template Reference
TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel > Class Template Reference
Templated abstract base class for turbulence models.
Public Types
typedef Alpha alphaField
typedef Rho rhoField
typedef TransportModel transportModel
Public Member Functions
declareRunTimeNewSelectionTable (autoPtr, TurbulenceModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
TurbulenceModel (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct.
virtual ~TurbulenceModel ()
Destructor.
const alphaField & alpha () const
Access function to phase fraction.
const transportModel & transport () const
Access function to incompressible transport model.
tmp< volScalarField > nu () const
Return the laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity on patchi.
Static Public Member Functions
static autoPtr< TurbulenceModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Protected Attributes
const alphaField & alpha_
const transportModel & transport_
Detailed Description
template<class Alpha, class Rho, class BasicTurbulenceModel, class TransportModel>
class Foam::TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >
Templated abstract base class for turbulence models.
Source files
TurbulenceModel.H
TurbulenceModel.C
Definition at line 57 of file TurbulenceModel.H.
Member Typedef Documentation
typedef Alpha alphaField
Definition at line 64 of file TurbulenceModel.H.
typedef Rho rhoField
Definition at line 65 of file TurbulenceModel.H.
typedef TransportModel transportModel
Definition at line 66 of file TurbulenceModel.H.
Constructor & Destructor Documentation
TurbulenceModel (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct.
Definition at line 41 of file TurbulenceModel.C.
References Foam::constant::atomic::alpha, TimePaths::constant(), IOobject::db(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobject::group(), Foam::Info, dictionary::lookup(), TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::New(), Foam::nl, phi, rho, IOobject::time(), and U.
virtual ~TurbulenceModel () inline virtual
Destructor.
Definition at line 141 of file TurbulenceModel.H.
Member Function Documentation
declareRunTimeNewSelectionTable (autoPtr , TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel > , dictionary , (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName) , (alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
static autoPtr<TurbulenceModel> New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Referenced by TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::TurbulenceModel().
const alphaField& alpha () const inline
Access function to phase fraction.
Definition at line 148 of file TurbulenceModel.H.
References TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::alpha_.
const transportModel& transport () const inline
Access function to incompressible transport model.
Definition at line 154 of file TurbulenceModel.H.
References TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::transport_.
tmp<volScalarField> nu () const inline
Return the laminar viscosity.
Definition at line 160 of file TurbulenceModel.H.
Referenced by kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::DkEff(), and kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::DomegaEff().
tmp<scalarField> nu (const label patchi) const inline
Return the laminar viscosity on patchi.
Definition at line 166 of file TurbulenceModel.H.
Member Data Documentation
const alphaField& alpha_ protected
Definition at line 73 of file TurbulenceModel.H.
Referenced by TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::alpha().
const transportModel& transport_ protected
Definition at line 74 of file TurbulenceModel.H.
Referenced by TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::transport().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/TurbulenceModel/TurbulenceModel.H
src/TurbulenceModels/turbulenceModels/TurbulenceModel/TurbulenceModel.C