OpenFOAM: twoPhaseMixtureThermo Class Reference
twoPhaseMixtureThermo Class Reference
Public Member Functions
TypeName ("twoPhaseMixtureThermo")
Runtime type information.
twoPhaseMixtureThermo (const fvMesh &mesh)
Construct from mesh.
virtual ~twoPhaseMixtureThermo ()
Destructor.
const rhoThermo & thermo1 () const
const rhoThermo & thermo2 () const
rhoThermo & thermo1 ()
rhoThermo & thermo2 ()
virtual void correct ()
Update properties.
virtual bool incompressible () const
Return true if the equation of state is incompressible.
virtual bool isochoric () const
Return true if the equation of state is isochoric.
virtual volScalarField & he ()
Enthalpy/Internal energy [J/kg].
virtual const volScalarField & he () const
Enthalpy/Internal energy [J/kg].
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &T) const
Enthalpy/Internal energy.
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const labelList &cells) const
Enthalpy/Internal energy for cell-set [J/kg].
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const label patchi) const
Enthalpy/Internal energy for patch [J/kg].
virtual tmp< volScalarField > hc () const
Chemical enthalpy [J/kg].
virtual tmp< scalarField > THE (const scalarField &h, const scalarField &p, const scalarField &T0, const labelList &cells) const
Temperature from enthalpy/internal energy for cell-set.
virtual tmp< scalarField > THE (const scalarField &h, const scalarField &p, const scalarField &T0, const label patchi) const
Temperature from enthalpy/internal energy for patch.
virtual tmp< volScalarField > Cp () const
Heat capacity at constant pressure [J/kg/K].
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant pressure for patch [J/kg/K].
virtual tmp< volScalarField > Cv () const
Heat capacity at constant volume [J/kg/K].
virtual tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant volume for patch [J/kg/K].
virtual tmp< volScalarField > gamma () const
Gamma = Cp/Cv [].
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &T, const label patchi) const
Gamma = Cp/Cv for patch [].
virtual tmp< volScalarField > Cpv () const
Heat capacity at constant pressure/volume [J/kg/K].
virtual tmp< scalarField > Cpv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant pressure/volume for patch [J/kg/K].
virtual tmp< volScalarField > CpByCpv () const
Heat capacity ratio [].
virtual tmp< scalarField > CpByCpv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity ratio for patch [].
virtual tmp< volScalarField > nu () const
Kinematic viscosity of mixture [m^2/s].
virtual tmp< scalarField > nu (const label patchi) const
Kinematic viscosity of mixture for patch [m^2/s].
virtual tmp< volScalarField > kappa () const
Thermal diffusivity for temperature of mixture [J/m/s/K].
virtual tmp< scalarField > kappa (const label patchi) const
Thermal diffusivity of mixture for patch [J/m/s/K].
virtual tmp< volScalarField > kappaEff (const volScalarField &alphat) const
Effective thermal diffusivity of mixture [J/m/s/K].
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
Effective thermal diffusivity of mixture for patch [J/m/s/K].
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
Effective thermal diffusivity of mixture [J/m/s/K].
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
Effective thermal diffusivity of mixture for patch [J/m/s/K].
Public Member Functions inherited from psiThermo
TypeName ("psiThermo")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, psiThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
Declare run-time constructor selection table.
psiThermo (const fvMesh &, const word &phaseName)
Construct from mesh and phase name.
virtual ~psiThermo ()
Destructor.
virtual tmp< volScalarField > rho () const
Density [kg/m^3] - uses current value of pressure.
virtual tmp< scalarField > rho (const label patchi) const
Density for patch [kg/m^3].
virtual const volScalarField & psi () const
Compressibility [s^2/m^2].
virtual tmp< volScalarField > mu () const
Dynamic viscosity of mixture [kg/m/s].
virtual tmp< scalarField > mu (const label patchi) const
Dynamic viscosity of mixture for patch [kg/m/s].
Public Member Functions inherited from fluidThermo
TypeName ("fluidThermo")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fluidThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
Declare run-time constructor selection table.
fluidThermo (const fvMesh &, const word &phaseName)
Construct from mesh and phase name.
fluidThermo (const fvMesh &, const dictionary &, const word &phaseName)
Construct from mesh and phase name.
virtual ~fluidThermo ()
Destructor.
Public Member Functions inherited from basicThermo
TypeName ("basicThermo")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, basicThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
Declare run-time constructor selection table.
basicThermo (const fvMesh &, const word &phaseName)
Construct from mesh and phase name.
basicThermo (const fvMesh &, const dictionary &, const word &phaseName)
Construct from mesh, dictionary and phase name.
virtual ~basicThermo ()
Destructor.
word phasePropertyName (const word &name) const
void validate (const string &app, const word &) const
Check that the thermodynamics package is consistent.
void validate (const string &app, const word &, const word &) const
Check that the thermodynamics package is consistent.
void validate (const string &app, const word &, const word &, const word &) const
Check that the thermodynamics package is consistent.
void validate (const string &app, const word &, const word &, const word &, const word &) const
Check that the thermodynamics package is consistent.
Switch dpdt () const
Should the dpdt term be included in the enthalpy equation.
virtual volScalarField & p ()
Pressure [Pa].
virtual const volScalarField & p () const
Pressure [Pa].
virtual const volScalarField & T () const
Temperature [K].
virtual volScalarField & T ()
Temperature [K].
virtual const volScalarField & alpha () const
Thermal diffusivity for enthalpy of mixture [kg/m/s].
virtual const scalarField & alpha (const label patchi) const
Thermal diffusivity for enthalpy of mixture for patch [kg/m/s].
virtual bool read ()
Read thermophysical properties dictionary.
template<class Thermo >
Foam::autoPtr< Thermo > New (const fvMesh &mesh, const word &phaseName)
template<class Thermo >
Foam::autoPtr< Thermo > New (const fvMesh &mesh, const dictionary &dict, const word &phaseName)
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()
Null construct.
ILList (T *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< LListBase, T > &)
Construct as copy.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
template<class INew >
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< LListBase, T > &)
Assignment operator.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()
Null construct.
UILList (T *a)
Construct given initial T.
UILList (const UILList< LListBase, T > &)
Construct as copy.
T * first ()
Return the first entry.
const T * first () const
Return the first entry.
T * last ()
Return the last entry.
const T * last () const
Return the last entry.
T * removeHead ()
Remove and return head.
T * remove (T *p)
Remove and return element.
T * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< LListBase, T > &)
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< LListBase, T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< LListBase, T > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from compressibleTransportModel
TypeName ("compressibleTransportModel")
Runtime type information.
compressibleTransportModel ()
Construct from components.
virtual ~compressibleTransportModel ()
Destructor.
Public Member Functions inherited from twoPhaseMixture
twoPhaseMixture (const fvMesh &mesh, const dictionary &dict)
Construct from components.
~twoPhaseMixture ()
Destructor.
const word & phase1Name () const
const word & phase2Name () const
const volScalarField & alpha1 () const
Return the phase-fraction of phase 1.
volScalarField & alpha1 ()
Return the phase-fraction of phase 1.
const volScalarField & alpha2 () const
Return the phase-fraction of phase 2.
volScalarField & alpha2 ()
Return the phase-fraction of phase 2.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values the DLList contains.
typedef T & reference
Type that can be used for storing into DLList::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Static Public Member Functions inherited from psiThermo
static autoPtr< psiThermo > New (const fvMesh &mesh, const word &phaseName=word::null)
Selector.
Static Public Member Functions inherited from fluidThermo
static autoPtr< fluidThermo > New (const fvMesh &, const word &phaseName=word::null)
Selector.
Static Public Member Functions inherited from basicThermo
template<class Thermo , class Table >
static Table::iterator lookupThermo (const dictionary &thermoDict, Table *tablePtr)
Generic lookup for each of the related thermodynamics packages.
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const word &phaseName=word::null)
Generic New for each of the related thermodynamics packages.
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const dictionary &, const word &phaseName=word::null)
Generic New for each of the related thermodynamics packages.
static autoPtr< basicThermo > New (const fvMesh &, const word &phaseName=word::null)
Specialisation of the Generic New for basicThermo.
static word phasePropertyName (const word &name, const word &phaseName)
static const basicThermo & lookupThermo (const fvPatchScalarField &pf)
static wordList splitThermoName (const word &thermoName, const int nCmpt)
Split name of thermo package into a list of the components names.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Static Public Attributes inherited from basicThermo
static const word dictName
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Protected Member Functions inherited from psiThermo
psiThermo (const psiThermo &)
Construct as copy (not implemented)
Protected Member Functions inherited from basicThermo
basicThermo (const basicThermo &)
Construct as copy (not implemented)
volScalarField & lookupOrConstruct (const fvMesh &mesh, const char *name) const
wordList heBoundaryTypes ()
Return the enthalpy/internal energy field boundary types.
wordList heBoundaryBaseTypes ()
Return the enthalpy/internal energy field boundary base types.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes inherited from psiThermo
volScalarField psi_
Compressibility [s^2/m^2].
volScalarField mu_
Dynamic viscosity [kg/m/s].
Protected Attributes inherited from basicThermo
const word & phaseName_
Phase-name.
volScalarField & p_
Pressure [Pa].
volScalarField T_
Temperature [K].
volScalarField alpha_
Laminar thermal diffusuvity [kg/m/s].
Switch dpdt_
Should the dpdt term be included in the enthalpy equation.
Protected Attributes inherited from twoPhaseMixture
word phase1Name_
word phase2Name_
volScalarField alpha1_
volScalarField alpha2_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Source files
twoPhaseMixtureThermo.H
twoPhaseMixtureThermoI.H
twoPhaseMixtureThermo.C
twoPhaseMixtureThermoIO.C
Definition at line 51 of file twoPhaseMixtureThermo.H.
Constructor & Destructor Documentation
twoPhaseMixtureThermo (const fvMesh & mesh)
Construct from mesh.
virtual ~twoPhaseMixtureThermo () virtual
Destructor.
Member Function Documentation
TypeName ("twoPhaseMixtureThermo")
Runtime type information.
const rhoThermo& thermo1 () const inline
Definition at line 86 of file twoPhaseMixtureThermo.H.
const rhoThermo& thermo2 () const inline
Definition at line 91 of file twoPhaseMixtureThermo.H.
rhoThermo& thermo1 () inline
Definition at line 96 of file twoPhaseMixtureThermo.H.
rhoThermo& thermo2 () inline
Definition at line 101 of file twoPhaseMixtureThermo.H.
References twoPhaseMixtureThermo::correct(), twoPhaseMixtureThermo::he(), twoPhaseMixtureThermo::incompressible(), twoPhaseMixtureThermo::isochoric(), and NotImplemented.
virtual void correct () virtual
Update properties.
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::thermo2().
virtual bool incompressible () const virtual
Return true if the equation of state is incompressible.
i.e. rho != f(p)
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::thermo2().
virtual bool isochoric () const virtual
Return true if the equation of state is isochoric.
i.e. rho = const
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::thermo2().
virtual volScalarField& he () inline virtual
Enthalpy/Internal energy [J/kg].
Non-const access allowed for transport equations
Implements basicThermo.
Definition at line 122 of file twoPhaseMixtureThermo.H.
Referenced by twoPhaseMixtureThermo::he(), and twoPhaseMixtureThermo::thermo2().
virtual const volScalarField& he () const inline virtual
Enthalpy/Internal energy [J/kg].
Implements basicThermo.
Definition at line 129 of file twoPhaseMixtureThermo.H.
References twoPhaseMixtureThermo::alphaEff(), cells, twoPhaseMixtureThermo::Cp(), twoPhaseMixtureThermo::CpByCpv(), twoPhaseMixtureThermo::Cpv(), twoPhaseMixtureThermo::Cv(), twoPhaseMixtureThermo::gamma(), h, twoPhaseMixtureThermo::hc(), twoPhaseMixtureThermo::he(), twoPhaseMixtureThermo::kappa(), twoPhaseMixtureThermo::kappaEff(), NotImplemented, twoPhaseMixtureThermo::nu(), basicThermo::p(), patchi, basicThermo::T(), and twoPhaseMixtureThermo::THE().
virtual tmp<volScalarField> he (const volScalarField & p, const volScalarField & T) const virtual
Enthalpy/Internal energy.
for given pressure and temperature [J/kg]
Implements basicThermo.
virtual tmp<scalarField> he (const scalarField & p, const scalarField & T, const labelList & cells) const virtual
Enthalpy/Internal energy for cell-set [J/kg].
Implements basicThermo.
virtual tmp<scalarField> he (const scalarField & p, const scalarField & T, const label patchi) const virtual
Enthalpy/Internal energy for patch [J/kg].
Implements basicThermo.
virtual tmp<volScalarField> hc () const virtual
Chemical enthalpy [J/kg].
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> THE (const scalarField & h, const scalarField & p, const scalarField & T0, const labelList & cells) const virtual
Temperature from enthalpy/internal energy for cell-set.
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> THE (const scalarField & h, const scalarField & p, const scalarField & T0, const label patchi) const virtual
Temperature from enthalpy/internal energy for patch.
Implements basicThermo.
virtual tmp<volScalarField> Cp () const virtual
Heat capacity at constant pressure [J/kg/K].
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> Cp (const scalarField & p, const scalarField & T, const label patchi) const virtual
Heat capacity at constant pressure for patch [J/kg/K].
Implements basicThermo.
virtual tmp<volScalarField> Cv () const virtual
Heat capacity at constant volume [J/kg/K].
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> Cv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Heat capacity at constant volume for patch [J/kg/K].
Implements basicThermo.
virtual tmp<volScalarField> gamma () const virtual
Gamma = Cp/Cv [].
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> gamma (const scalarField & p, const scalarField & T, const label patchi) const virtual
Gamma = Cp/Cv for patch [].
Implements basicThermo.
virtual tmp<volScalarField> Cpv () const virtual
Heat capacity at constant pressure/volume [J/kg/K].
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> Cpv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Heat capacity at constant pressure/volume for patch [J/kg/K].
Implements basicThermo.
virtual tmp<volScalarField> CpByCpv () const virtual
Heat capacity ratio [].
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> CpByCpv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Heat capacity ratio for patch [].
Implements basicThermo.
virtual tmp<volScalarField> nu () const virtual
Kinematic viscosity of mixture [m^2/s].
Reimplemented from fluidThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> nu (const label patchi) const virtual
Kinematic viscosity of mixture for patch [m^2/s].
Reimplemented from fluidThermo.
virtual tmp<volScalarField> kappa () const virtual
Thermal diffusivity for temperature of mixture [J/m/s/K].
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> kappa (const label patchi) const virtual
Thermal diffusivity of mixture for patch [J/m/s/K].
Implements basicThermo.
virtual tmp<volScalarField> kappaEff (const volScalarField & alphat) const virtual
Effective thermal diffusivity of mixture [J/m/s/K].
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> kappaEff (const scalarField & alphat, const label patchi) const virtual
Effective thermal diffusivity of mixture for patch [J/m/s/K].
Implements basicThermo.
virtual tmp<volScalarField> alphaEff (const volScalarField & alphat) const virtual
Effective thermal diffusivity of mixture [J/m/s/K].
Implements basicThermo.
Referenced by twoPhaseMixtureThermo::he().
virtual tmp<scalarField> alphaEff (const scalarField & alphat, const label patchi) const virtual
Effective thermal diffusivity of mixture for patch [J/m/s/K].
Implements basicThermo.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/compressibleInterFoam/twoPhaseMixtureThermo/twoPhaseMixtureThermo.H