OpenFOAM-dev: UPtrList< T > Class Template Reference 2
UPtrList< T > Class Template Reference
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
Inherited by PtrList< T >, PtrList< bodyMesh >, PtrList< cellZone >, PtrList< CloudFunctionObject< CloudType > >, PtrList< CloudFunctionObject< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, PtrList< CloudFunctionObject< KinematicCloud< CloudType > > >, PtrList< CloudFunctionObject< KinematicCloud< Foam::DSMCCloud > > >, PtrList< coalCloud >, PtrList< const Foam::lduInterface >, PtrList< coordinateSystem >, PtrList< curvedEdge >, PtrList< engineValve >, PtrList< entry >, PtrList< extendedFeatureEdgeMesh >, PtrList< faceZone >, PtrList< Field< Type > >, PtrList< Foam::AMIInterpolation >, PtrList< Foam::boundaryPatch >, PtrList< Foam::cellModel >, PtrList< Foam::cellSizeAndAlignmentControl >, PtrList< Foam::cellSizeFunction >, PtrList< Foam::coordinateSystem >, PtrList< Foam::coordSet >, PtrList< Foam::coupledFacePair >, PtrList< Foam::decompositionConstraint >, PtrList< Foam::decompositionMethod >, PtrList< Foam::diameterModels::IATEsource >, PtrList< Foam::dictionary >, PtrList< Foam::dimensioned >, PtrList< Foam::DimensionedField< scalar, Foam::volMesh > >, PtrList< Foam::ensightPart >, PtrList< Foam::extendedFeatureEdgeMesh >, PtrList< Foam::Field >, PtrList< Foam::Field< LUType > >, PtrList< Foam::Field< scalar > >, PtrList< Foam::FieldField< Foam::Field, scalar > >, PtrList< Foam::fvMesh >, PtrList< Foam::ignitionSite >, PtrList< Foam::indexedOctree >, PtrList< Foam::indexedOctree< Foam::treeDataEdge > >, PtrList< Foam::indexedOctree< Foam::treeDataPoint > >, PtrList< Foam::interpolation< Foam::Vector > >, PtrList< Foam::interpolation< scalar > >, PtrList< Foam::IOList >, PtrList< Foam::lduMatrix >, PtrList< Foam::lduPrimitiveMesh >, PtrList< Foam::liquidProperties >, PtrList< Foam::List >, PtrList< Foam::mappedPatchBase >, PtrList< Foam::OFstream >, PtrList< Foam::PatchInteractionModel< Foam::DSMCCloud > >, PtrList< Foam::pointMesh >, PtrList< Foam::PrimitivePatch >, PtrList< Foam::procLduInterface >, PtrList< Foam::PtrList< Foam::AMIInterpolation > >, PtrList< Foam::PtrList< Foam::lduInterfaceField > >, PtrList< Foam::radiation::radiativeIntensityRay >, PtrList< Foam::RBD::joint >, PtrList< Foam::RBD::restraint >, PtrList< Foam::RBD::rigidBody >, PtrList< Foam::RBD::subBody >, PtrList< Foam::Reaction< SolidThermo > >, PtrList< Foam::Reaction< ThermoType > >, PtrList< Foam::sixDoFRigidBodyMotionConstraint >, PtrList< Foam::sixDoFRigidBodyMotionRestraint >, PtrList< Foam::solidBodyMotionFunction >, PtrList< Foam::solidProperties >, PtrList< Foam::surfaceZonesInfo >, PtrList< Foam::Time >, PtrList< Foam::UPtrList >, PtrList< force >, PtrList< functionObject >, PtrList< fvPatchMapper >, PtrList< GasThermo >, PtrList< injectionModel >, PtrList< InjectionModel< CloudType > >, PtrList< InjectionModel< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, PtrList< InjectionModel< Foam::KinematicCloud< CloudType > > >, PtrList< InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > > >, PtrList< joint >, PtrList< MRFZone >, PtrList< option >, PtrList< pairPotential >, PtrList< ParticleForce< CloudType > >, PtrList< ParticleForce< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, PtrList< ParticleForce< KinematicCloud< CloudType > > >, PtrList< ParticleForce< KinematicCloud< Foam::DSMCCloud > > >, PtrList< PatchField< Type > >, PtrList< phaseModel >, PtrList< pointPatchMapper >, PtrList< pointZone >, PtrList< polyMeshModifier >, PtrList< porosityModel >, PtrList< profileModel >, PtrList< pyrolysisModel >, PtrList< Reaction< ThermoType > >, PtrList< regionModelFunctionObject >, PtrList< sampledSet >, PtrList< sampledSurface >, PtrList< searchableSurface >, PtrList< SolidThermo >, PtrList< tetherPotential >, PtrList< ThermoType >, and PtrList< ZoneType >.
Classes
class const_iterator
An STL-conforming const_iterator.
class iterator
An STL iterator.
Public Types
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Public Member Functions
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be NULL).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Friends
class PtrList< T >
Declare friendship with the UPtrList class.
class iterator
Ostream & operator (Ostream &, const UPtrList< T > &)
Write UPtrList to Ostream.
Detailed Description
template<class T>
class Foam::UPtrList< T >
A templated 1D list of pointers to objects of type <T>, where the size of the array is known and used for subscript bounds checking, etc.
The element operator [] returns a reference to the object rather than a pointer. Storage is not allocated during construction or use but is supplied to the constructor as an argument.
Source files
UPtrList.H
UPtrList.C
UPtrListIO.C
Definition at line 54 of file UPtrList.H.
Member Typedef Documentation
typedef T value_type
Type of values the UPtrList contains.
Definition at line 227 of file UPtrList.H.
typedef T& reference
Type that can be used for storing into UPtrList::value_type objects.
Definition at line 230 of file UPtrList.H.
typedef const T& const_reference
Type that can be used for storing into constant UPtrList::value_type.
objects
Definition at line 234 of file UPtrList.H.
Constructor & Destructor Documentation
UPtrList ()
Null Constructor.
Definition at line 31 of file UPtrList.C.
UPtrList (const label s) explicit
Construct with size specified.
Definition at line 38 of file UPtrList.C.
UPtrList (const Xfer< UPtrList< T >> & lst)
Construct by transferring the parameter contents.
Definition at line 45 of file UPtrList.C.
References UPtrList< T >::transfer().
UPtrList (UPtrList< T > & a, bool reuse)
Construct as copy or re-use as specified.
Definition at line 52 of file UPtrList.C.
Member Function Documentation
Foam::label size () const inline
Return the number of elements in the UPtrList.
Definition at line 29 of file UPtrListI.H.
Referenced by MRFZoneList::absolute(), MRFZoneList::active(), porosityModelList::active(), singleProcessorFaceSetsConstraint::add(), fvMeshAdder::add(), polyMeshAdder::add(), surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), snappyLayerDriver::addLayers(), fvMeshTools::addPatch(), meshRefinement::addPatch(), GAMGAgglomeration::agglomerateLduAddressing(), extendedEdgeMesh::allNearestFeatureEdges(), meshRefinement::appendPatch(), attachPolyTopoChanger::attach(), addPatchCellLayer::calcSidePatch(), polyTopoChange::changeMesh(), repatchPolyTopoChanger::changePatchID(), searchableSurfaces::checkClosed(), polyBoundaryMesh::checkDefinition(), polyBoundaryMesh::checkParallelSync(), searchableSurfaces::checkSizes(), profileModelList::connectBlades(), inverseFaceDistanceDiffusivity::correct(), nearWallDistNoSearch::correct(), nearWallDist::correct(), pointPatchDist::correct(), wallDistData< TransferType >::correct(), motionSmootherAlgo::curPoints(), structuredDecomp::decompose(), decompositionMethod::decompose(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), fvMeshDistribute::distribute(), snappyLayerDriver::doLayers(), Foam::facePointN(), coordinateSystems::findIndices(), polyBoundaryMesh::findPatchIDs(), fvFieldReconstructor::fvFieldReconstructor(), GAMGSolver::GAMGSolver(), lduPrimitiveMesh::gather(), Foam::gAverage(), surfaceZonesInfo::getAllClosedNamedSurfaces(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), surfaceZonesInfo::getNamedSurfaces(), cellDistFuncs::getPatchIDs(), surfaceZonesInfo::getUnclosedNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), GAMGProcAgglomeration::globalCellCells(), hexRef8Data::hexRef8Data(), injectionModelList::info(), interRegionExplicitPorositySource::initialise(), lduMatrix::initMatrixInterfaces(), fvBoundaryMesh::interfaces(), GeometricField< Type, PatchField, GeoMesh >::Boundary::interfaces(), meshToMesh::interpolationMethodAMI(), regionModel::interRegionAMI(), rigidBodyModel::join(), rigidBodyModel::join_(), layerParameters::layerParameters(), lduPrimitiveMesh::lduPrimitiveMesh(), Foam::MULES::limitSum(), LUscalarMatrix::LUscalarMatrix(), meshRefinement::makeDisplacementField(), polyTopoChange::makeMesh(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), Foam::max(), MeshedSurface< Face >::MeshedSurface(), meshTriangulation::meshTriangulation(), polyTopoChanger::names(), ZoneMesh< ZoneType, MeshType >::names(), polyBoundaryMesh::names(), regionModel::nbrCoupledPatchID(), extendedEdgeMesh::nearestFeatureEdgeByType(), FieldField< Field, Type >::NewCalculatedType(), nonBlockingGaussSeidelSmoother::nonBlockingGaussSeidelSmoother(), lduPrimitiveMesh::nonBlockingSchedule(), potential::nPairPotentials(), blockMesh::numZonedBlocks(), procLess::operator()(), ListPlusEqOp< T, Size >::operator()(), listPlusEqOp< T >::operator()(), Foam::operator<<(), PtrList< T >::operator=(), blockMesh::patchDicts(), patchInjection::patchInjection(), patchDistMethod::patchTypes(), polyBoundaryMesh::physicalTypes(), pointFieldReconstructor::pointFieldReconstructor(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), Foam::polyMeshZipUpCells(), polyTopoChange::polyTopoChange(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), thermalBaffleModel::read(), boundaryMesh::read(), polyMesh::readUpdate(), ensightParts::recalculate(), pointFieldReconstructor::reconstructField(), refinementHistory::refinementHistory(), refinementFeatures::regionEdgeTrees(), MRFZoneList::relative(), SloanRenumber::renumber(), structuredRenumber::renumber(), PtrList< T >::reorder(), UPtrList< T >::reorder(), lduMatrix::residual(), GeometricField< Type, PatchField, GeoMesh >::Boundary::scalarInterfaces(), fvMeshSubset::setCellSubset(), polyBoundaryMesh::setGroup(), fvMeshSubset::setLargeCellSubset(), removeCells::setRefinement(), meshCutAndRemove::setRefinement(), PtrList< T >::setSize(), UPtrList< T >::setSize(), singleCellFvMesh::singleCellFvMesh(), ensightParts::size(), pairPatchAgglomeration::size(), GAMGAgglomeration::size(), surfacePatchIOList::surfacePatchIOList(), surfZoneIOList::surfZoneIOList(), ParticleStressModel::tau(), coordinateSystems::toc(), polyTopoChanger::types(), ZoneMesh< ZoneType, MeshType >::types(), polyBoundaryMesh::types(), GeometricField< Type, PatchField, GeoMesh >::Boundary::types(), lduMatrix::updateMatrixInterfaces(), valveBank::valveBank(), wallLayerCells::wallLayerCells(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), vtkSetWriter< Type >::write(), gnuplotSetWriter< Type >::write(), xmgraceSetWriter< Type >::write(), coordinateSystems::writeData(), polyBoundaryMesh::writeData(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), searchableSurfaces::writeStats(), fvMeshTools::zeroPatchFields(), ZoneMesh< ZoneType, MeshType >::ZoneMesh(), meshRefinement::zonify(), and externalCoupledMixedFvPatchField< Type >::~externalCoupledMixedFvPatchField().
bool empty () const inline
Return true if the UPtrList is empty (ie, size() is zero)
Definition at line 36 of file UPtrListI.H.
Referenced by NamedEnum< Enum, nEnum >::names(), and fvMeshTools::zeroPatchFields().
T & first () inline
Return reference to the first element of the list.
Definition at line 43 of file UPtrListI.H.
Referenced by functionObjectList::readFunctionObject().
const T & first () const inline
Return reference to first element of the list.
Definition at line 50 of file UPtrListI.H.
T & last () inline
Return reference to the last element of the list.
Definition at line 57 of file UPtrListI.H.
Referenced by composite::jcalc().
const T & last () const inline
Return reference to the last element of the list.
Definition at line 64 of file UPtrListI.H.
void setSize (const label newSize)
Reset size of UPtrList. This can only be used to set the size.
of an empty UPtrList, extend a UPtrList, remove entries from the end of a UPtrList
Definition at line 61 of file UPtrList.C.
References UPtrList< T >::clear(), List< T >::setSize(), and UPtrList< T >::size().
void resize (const label newSize) inline
Reset size of UPtrList. This can only be used to set the size.
of an empty UPtrList, extend a UPtrList, remove entries from the end of a UPtrList
Definition at line 71 of file UPtrListI.H.
References setSize().
void clear ()
Clear the UPtrList, i.e. set size to zero.
Definition at line 87 of file UPtrList.C.
References List< T >::clear().
Referenced by UPtrList< T >::setSize().
void transfer (UPtrList< T > & a)
Transfer the contents of the argument UPtrList into this.
UPtrList and annul the argument list
Definition at line 94 of file UPtrList.C.
References List< T >::transfer().
Referenced by wallDistData< TransferType >::correct(), meshWave::correct(), and UPtrList< T >::UPtrList().
Foam::Xfer< Foam::UPtrList< T > > xfer () inline
Transfer contents to the Xfer container.
Definition at line 94 of file UPtrListI.H.
References Foam::xferMove().
bool set (const label i) const inline
Is element set.
Definition at line 78 of file UPtrListI.H.
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::combineLevels(), GAMGSolver::GAMGSolver(), lduPrimitiveMesh::gather(), GAMGProcAgglomeration::globalCellCells(), lduMatrix::initMatrixInterfaces(), fvBoundaryMesh::interfaces(), lduPrimitiveMesh::lduPrimitiveMesh(), LUscalarMatrix::LUscalarMatrix(), nonBlockingGaussSeidelSmoother::nonBlockingGaussSeidelSmoother(), lduPrimitiveMesh::nonBlockingSchedule(), Foam::operator<<(), procLduMatrix::procLduMatrix(), lduMatrix::residual(), GeometricField< Type, PatchField, GeoMesh >::Boundary::scalarInterfaces(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), lduMatrix::sumA(), and lduMatrix::updateMatrixInterfaces().
T * set (const label i, T * ptr) inline
Set element. Return old element (can be NULL).
No checks on new element
Definition at line 85 of file UPtrListI.H.
References T.
void reorder (const labelUList & oldToNew)
Reorders elements. Ordering does not have to be done in.
ascending or descending order. Reordering has to be unique. (is shuffle)
Definition at line 101 of file UPtrList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, List< T >::size(), UPtrList< T >::size(), UList< T >::size(), Foam::T(), and List< T >::transfer().
const T & operator[] (const label i) const inline
Return element const reference.
Definition at line 103 of file UPtrListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by MRFZoneList::active(), porosityModelList::active(), MRFZoneList::addAcceleration(), porosityModelList::addResistance(), functionObjectList::adjustTimeStep(), InjectionModelList< CloudType >::averageParcelMass(), GeometricField< Type, PatchField, GeoMesh >::Boundary::boundaryInternalField(), profileModelList::connectBlades(), optionList::constrain(), forceList::correct(), nearWallDistNoSearch::correct(), injectionModelList::correct(), optionList::correct(), MRFZoneList::correctBoundaryVelocity(), MRFZoneList::DDt(), functionObjectList::end(), GeometricField< Type, PatchField, GeoMesh >::Boundary::evaluate(), coalCloudList::evolve(), pyrolysisModelCollection::evolve(), pyrolysisModelCollection::evolveRegion(), functionObjectList::execute(), pointBoundaryMesh::findIndices(), coalCloudList::hsTrans(), pyrolysisModelCollection::info(), injectionModelList::info(), InjectionModelList< CloudType >::info(), InjectionModelList< CloudType >::inject(), InjectionModelList< CloudType >::injectSteadyState(), MRFZoneList::makeAbsolute(), MRFZoneList::makeRelative(), pyrolysisModelCollection::maxDiff(), pointBoundaryMesh::movePoints(), functionObjectList::movePoints(), FieldField< Field, Type >::negate(), FieldField< Field, Type >::operator=(), GeometricField< Type, PatchField, GeoMesh >::Boundary::operator=(), GeometricField< Type, PatchField, GeoMesh >::Boundary::operator==(), regionModelFunctionObjectList::postEvolveRegion(), pyrolysisModelCollection::preEvolveRegion(), regionModelFunctionObjectList::preEvolveRegion(), porosityModelList::read(), MRFZoneList::read(), refinementFeatures::regionEdgeTrees(), MRFZoneList::relative(), FieldField< Field, Type >::replace(), coalCloudList::rhoTrans(), coalCloudList::Sh(), pyrolysisModelCollection::solidRegionDiffNo(), coalCloudList::Srho(), coalCloudList::SU(), coalCloudList::SYi(), coordinateSystems::toc(), GeometricField< Type, PatchField, GeoMesh >::Boundary::updateCoeffs(), InjectionModelList< CloudType >::updateMesh(), pointBoundaryMesh::updateMesh(), functionObjectList::updateMesh(), coalCloudList::UTrans(), InjectionModelList< CloudType >::volumeToInject(), porosityModelList::writeData(), coordinateSystems::writeData(), MRFZoneList::writeData(), optionList::writeData(), and GeometricField< Type, PatchField, GeoMesh >::Boundary::writeEntry().
T & operator[] (const label i) inline
Return element reference.
Definition at line 119 of file UPtrListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
const T * operator() (const label i) const inline
Return element const pointer.
Definition at line 135 of file UPtrListI.H.
Foam::UPtrList< T >::iterator begin () inline
Return an iterator to begin traversing the UPtrList.
Definition at line 289 of file UPtrListI.H.
Referenced by LUscalarMatrix::LUscalarMatrix().
Foam::UPtrList< T >::iterator end () inline
Return an iterator to end traversing the UPtrList.
Definition at line 296 of file UPtrListI.H.
Referenced by searchableSurfaces::checkIntersection(), and searchableSurfaces::regionNames().
Foam::UPtrList< T >::const_iterator cbegin () const inline
Return an const_iterator to begin traversing the UPtrList.
Definition at line 511 of file UPtrListI.H.
Foam::UPtrList< T >::const_iterator cend () const inline
Return an const_iterator to end traversing the UPtrList.
Definition at line 519 of file UPtrListI.H.
Foam::UPtrList< T >::const_iterator begin () const inline
Return an const_iterator to begin traversing the UPtrList.
Definition at line 495 of file UPtrListI.H.
Foam::UPtrList< T >::const_iterator end () const inline
Return an const_iterator to end traversing the UPtrList.
Definition at line 503 of file UPtrListI.H.
Friends And Related Function Documentation
friend class PtrList< T > friend
Declare friendship with the UPtrList class.
Definition at line 136 of file UPtrList.H.
friend class iterator friend
Definition at line 240 of file UPtrList.H.
Ostream& operator (Ostream & , const UPtrList< T > &) friend
Write UPtrList to Ostream.
Referenced by fvBoundaryMesh::mesh(), polyBoundaryMesh::mesh(), optionList::operator()(), reactingMixture< ThermoType >::operator[](), fvBoundaryMesh::operator[](), polyBoundaryMesh::operator[](), searchableSurfaces::operator[](), fvBoundaryMesh::readUpdate(), polyBoundaryMesh::writeObject(), and searchableSurfaces::writeStats().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/UPtrList/UPtrList.H
src/OpenFOAM/containers/Lists/UPtrList/UPtrList.C
src/OpenFOAM/containers/Lists/UPtrList/UPtrListI.H