OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA)&mesh.Sf())+fvc::interpolate(rho *rAU)*fvc::ddtCorr(U, Uf))
surfaceScalarField phig ((interface.surfaceTensionForce()-ghf *fvc::snGrad(rho))*rAUf *mesh.magSf())
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField()-(mesh.Sf().boundaryField()&U.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
surfaceScalarField phid2 ("phid2", fvc::interpolate(psi2)*phi)
deleteDemandDrivenData (p_rghEqnComp1().faceFluxCorrectionPtr())
p_rghEqnComp1 ().relax()
deleteDemandDrivenData (p_rghEqnComp2().faceFluxCorrectionPtr())
p_rghEqnComp2 ().relax()
volScalarField p_rgh_0 (p_rgh)
solve (((max(alpha1, scalar(0))/rho1)*p_rghEqnComp1()+(max(alpha2, scalar(0))/rho2)*p_rghEqnComp2())+p_rghEqnIncomp, mesh.solver(p_rgh.select(pimple.finalInnerIter())))
U correctBoundaryConditions ()
surfaceVectorField n (mesh.Sf()/mesh.magSf())
Variables
HbyA = rAU*UEqn.H()
phiHbyA = phig
tmp< fvScalarMatrix > p_rghEqnComp1
tmp< fvScalarMatrix > p_rghEqnComp2
else
p_rgh = p - (alpha1*rho1 + alpha2*rho2)*gh
dgdt
phi = phiHbyA + p_rghEqnIncomp.flux()
U
Uf = n*(fvc::absolute(phi, U)/mesh.magSf() - (n & Uf))
rho1 = psi1*(p_rgh - p_rgh_0)
rho2 = psi2*(p_rgh - p_rgh_0)
rho = alpha1*rho1 + alpha2*rho2
K = 0.5*magSqr(U)
Function Documentation
surfaceScalarField rAUf ("rAUf" , fvc:: interpolaterAU)
volVectorField HbyA ("HbyA" , U)
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA)&mesh.Sf())+fvc::interpolate(rho *rAU)*fvc::ddtCorr(U, Uf))
surfaceScalarField phig ((interface.surfaceTensionForce()-ghf *fvc::snGrad(rho))*rAUf *mesh.magSf())
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField()-(mesh.Sf().boundaryField()&U.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
surfaceScalarField phid2 ("phid2" , fvc::interpolate(psi2)* phi)
deleteDemandDrivenData (p_rghEqnComp1().faceFluxCorrectionPtr())
p_rghEqnComp1 ()
deleteDemandDrivenData (p_rghEqnComp2().faceFluxCorrectionPtr())
p_rghEqnComp2 ()
volScalarField p_rgh_0 (p_rgh)
solve (((max(alpha1, scalar(0))/rho1)*p_rghEqnComp1()+(max(alpha2, scalar(0))/rho2)*p_rghEqnComp2())+ p_rghEqnIncomp, mesh. solverp_rgh.select(pimple.finalInnerIter()))
U correctBoundaryConditions ()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Variable Documentation
HbyA = rAU*UEqn.H()
Definition at line 6 of file pEqn.H.
phiHbyA = phig
Definition at line 23 of file pEqn.H.
p_rghEqnComp1
Initial value:
=
            fvc::ddt(rho1) + fvc::div(phi, rho1) - fvc::Sp(fvc::div(phi), rho1)
          + correction
            (
                psi1*fvm::ddt(p_rgh)
              + fvm::div(phid1, p_rgh) - fvm::Sp(fvc::div(phid1), p_rgh)
            )
Definition at line 38 of file pEqn.H.
p_rghEqnComp2
Initial value:
=
            fvc::ddt(rho2) + fvc::div(phi, rho2) - fvc::Sp(fvc::div(phi), rho2)
          + correction
            (
                psi2*fvm::ddt(p_rgh)
              + fvm::div(phid2, p_rgh) - fvm::Sp(fvc::div(phid2), p_rgh)
            )
Definition at line 39 of file pEqn.H.
else
Initial value:
{
        p_rghEqnComp1 =
            fvc::ddt(rho1) + psi1*correction(fvm::ddt(p_rgh))
          + fvc::div(phi, rho1) - fvc::Sp(fvc::div(phi), rho1)
Definition at line 67 of file pEqn.H.
p_rgh = p - (alpha1*rho1 + alpha2*rho2)*gh
Definition at line 101 of file pEqn.H.
dgdt
Initial value:
=
            (
                pos(alpha2)*(p_rghEqnComp2 & p_rgh)/rho2
              - pos(alpha1)*(p_rghEqnComp1 & p_rgh)/rho1
            )
Definition at line 103 of file pEqn.H.
Referenced by for().
phi = phiHbyA + p_rghEqnIncomp.flux()
Definition at line 109 of file pEqn.H.
U
Initial value:
= HbyA
              + rAU*fvc::reconstruct((phig + p_rghEqnIncomp.flux())/rAUf)
Definition at line 111 of file pEqn.H.
Uf = n*(fvc::absolute(phi, U)/mesh.magSf() - (n & Uf))
Definition at line 120 of file pEqn.H.
rho1 = psi1*(p_rgh - p_rgh_0)
Definition at line 124 of file pEqn.H.
Referenced by SprayParcel< ParcelType >::calc(), ORourkeCollision< CloudType >::collideSorted(), for(), and if().
rho2 = psi2*(p_rgh - p_rgh_0)
Definition at line 125 of file pEqn.H.
Referenced by ORourkeCollision< CloudType >::collideSorted(), for(), and if().
rho = alpha1*rho1 + alpha2*rho2
Definition at line 127 of file pEqn.H.
K = 0.5*magSqr(U)
Definition at line 129 of file pEqn.H.