OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
valuePointPatchField< Type > Class Template Reference
Foam::valuePointPatchField.
Public Member Functions
TypeName ("value")
Runtime type information.
valuePointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
valuePointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &, const bool valueRequired=true)
Construct from patch, internal field and dictionary.
valuePointPatchField (const valuePointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
virtual autoPtr< pointPatchField< Type > > clone () const
Construct and return a clone.
valuePointPatchField (const valuePointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const
Construct and return a clone setting internal field reference.
label size () const
Return size.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given PointPatchField onto.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const valuePointPatchField< Type > &)
virtual void operator= (const pointPatchField< Type > &)
virtual void operator= (const Field< Type > &)
virtual void operator= (const Type &)
virtual void operator== (const valuePointPatchField< Type > &)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
Public Member Functions inherited from pointPatchField< Type >
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type, pointMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
template<class Type2 >
Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map)
Map from the given tmp field.
void autoMap (const FieldMapper &map)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Additional Inherited Members
Public Types inherited from pointPatchField< Type >
typedef pointPatch Patch
typedef calculatedPointPatchField< Type > Calculated
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from pointPatchField< Type >
static autoPtr< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new calculatedPointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes inherited from pointPatchField< Type >
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::valuePointPatchField< Type >
Foam::valuePointPatchField.
Source files
valuePointPatchField.H
valuePointPatchField.C
Definition at line 49 of file valuePointPatchField.H.
Constructor & Destructor Documentation
valuePointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 49 of file valuePointPatchField.C.
Referenced by valuePointPatchField< vector >::clone(), and valuePointPatchField< Type >::valuePointPatchField().
valuePointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict, const bool valueRequired = true)
Construct from patch, internal field and dictionary.
Definition at line 61 of file valuePointPatchField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), pointPatchField< Type >::size(), valuePointPatchField< Type >::valuePointPatchField(), and Foam::Zero.
valuePointPatchField (const valuePointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Construct by mapping given patchField<Type> onto a new patch.
Definition at line 95 of file valuePointPatchField.C.
References valuePointPatchField< Type >::valuePointPatchField().
valuePointPatchField (const valuePointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 109 of file valuePointPatchField.C.
References valuePointPatchField< Type >::autoMap().
Member Function Documentation
TypeName ("value")
Runtime type information.
virtual autoPtr<pointPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Implements pointPatchField< Type >.
Reimplemented in codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, zeroFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, waveDisplacementPointPatchVectorField, oscillatingDisplacementPointPatchVectorField, fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 93 of file valuePointPatchField.H.
Referenced by valuePointPatchField< vector >::clone().
virtual autoPtr<pointPatchField<Type> > clone (const DimensionedField< Type, pointMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Implements pointPatchField< Type >.
Reimplemented in codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, zeroFixedValuePointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, waveDisplacementPointPatchVectorField, oscillatingDisplacementPointPatchVectorField, fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 113 of file valuePointPatchField.H.
label size () const inline
Return size.
Definition at line 133 of file valuePointPatchField.H.
Referenced by angularOscillatingDisplacementPointPatchVectorField::angularOscillatingDisplacementPointPatchVectorField(), angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), oscillatingVelocityPointPatchVectorField::oscillatingVelocityPointPatchVectorField(), sixDoFRigidBodyDisplacementPointPatchVectorField::sixDoFRigidBodyDisplacementPointPatchVectorField(), timeVaryingMappedFixedValuePointPatchField< Type >::timeVaryingMappedFixedValuePointPatchField(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField(), and uniformFixedValuePointPatchField< Type >::uniformFixedValuePointPatchField().
void autoMap (const pointPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented from pointPatchField< Type >.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, and oscillatingVelocityPointPatchVectorField.
Definition at line 123 of file valuePointPatchField.C.
References valuePointPatchField< Type >::rmap().
Referenced by oscillatingVelocityPointPatchVectorField::autoMap(), angularOscillatingVelocityPointPatchVectorField::autoMap(), angularOscillatingDisplacementPointPatchVectorField::autoMap(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::autoMap(), sixDoFRigidBodyDisplacementPointPatchVectorField::autoMap(), valuePointPatchField< vector >::size(), and valuePointPatchField< Type >::valuePointPatchField().
void rmap (const pointPatchField< Type > & ptf, const labelList & addr) virtual
Reverse map the given PointPatchField onto.
this PointPatchField
Reimplemented from pointPatchField< Type >.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, and oscillatingVelocityPointPatchVectorField.
Definition at line 133 of file valuePointPatchField.C.
References Foam::refCast().
Referenced by valuePointPatchField< Type >::autoMap(), oscillatingVelocityPointPatchVectorField::rmap(), angularOscillatingVelocityPointPatchVectorField::rmap(), angularOscillatingDisplacementPointPatchVectorField::rmap(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::rmap(), sixDoFRigidBodyDisplacementPointPatchVectorField::rmap(), and valuePointPatchField< vector >::size().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from pointPatchField< Type >.
Reimplemented in codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformInterpolatedDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, timeVaryingUniformFixedValuePointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 150 of file valuePointPatchField.C.
Referenced by valuePointPatchField< vector >::size(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingDisplacementPointPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Evaluate the patch field.
Reimplemented from pointPatchField< Type >.
Reimplemented in codedFixedValuePointPatchField< Type >.
Definition at line 167 of file valuePointPatchField.C.
Referenced by valuePointPatchField< vector >::size().
void write (Ostream & os) const virtual
Write.
Reimplemented from pointPatchField< Type >.
Reimplemented in codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformInterpolatedDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, timeVaryingUniformFixedValuePointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 179 of file valuePointPatchField.C.
References write().
Referenced by valuePointPatchField< vector >::size().
void operator= (const valuePointPatchField< Type > & ptf) virtual
Definition at line 190 of file valuePointPatchField.C.
Referenced by valuePointPatchField< vector >::size().
void operator= (const pointPatchField< Type > & ptf) virtual
Reimplemented from pointPatchField< Type >.
Definition at line 200 of file valuePointPatchField.C.
void operator= (const Field< Type > & tf) virtual
Reimplemented from pointPatchField< Type >.
Reimplemented in fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 210 of file valuePointPatchField.C.
References tf.
void operator= (const Type & t) virtual
Reimplemented from pointPatchField< Type >.
Reimplemented in fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 220 of file valuePointPatchField.C.
void operator== (const valuePointPatchField< Type > & ptf) virtual
Definition at line 230 of file valuePointPatchField.C.
Referenced by valuePointPatchField< vector >::size().
void operator== (const pointPatchField< Type > & ptf) virtual
Reimplemented from pointPatchField< Type >.
Definition at line 240 of file valuePointPatchField.C.
void operator== (const Field< Type > & tf) virtual
Reimplemented from pointPatchField< Type >.
Definition at line 250 of file valuePointPatchField.C.
References tf.
void operator== (const Type & t) virtual
Reimplemented from pointPatchField< Type >.
Definition at line 260 of file valuePointPatchField.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/pointPatchFields/basic/value/valuePointPatchField.H
src/OpenFOAM/fields/pointPatchFields/basic/value/valuePointPatchField.C