OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
rho relax ()
volScalarField rAU ("rAU", 1.0/UEqn().A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
UEqn clear ()
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(rho *HbyA)&mesh.Sf()))
fvOptions makeRelative (fvc::interpolate(rho), phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField()-fvOptions.relative(mesh.Sf().boundaryField()&U.boundaryField())*rho.boundaryField())/(mesh.magSf().boundaryField()*rhorAUf.boundaryField()))
for (int nonOrth=0;nonOrth<=nNonOrthCorr;nonOrth++)
if (closedVolume &&compressible)
Variables
rho = max(rho, rhoMin[i])
HbyA = rAU*UEqn().H()
bool closedVolume = adjustPhi(phiHbyA, U, p_rgh)
phiHbyA = phig
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
bool compressible = (compressibility.value() > SMALL)
p = p_rgh + rho*gh
Function Documentation
rho relax ()
volScalarField rAU ("rAU" , 1.0/ UEqn).A()
surfaceScalarField rhorAUf ("rhorAUf" , fvc:: interpolaterho *rAU)
volVectorField HbyA ("HbyA" , U)
UEqn clear ()
surfaceScalarField phig (-rhorAUf *ghf *fvc:: snGradrho)*mesh.magSf()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(rho *HbyA)&mesh.Sf()))
fvOptions makeRelative (fvc:: interpolaterho, phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField()-fvOptions.relative(mesh.Sf().boundaryField()&U.boundaryField())*rho.boundaryField())/(mesh.magSf().boundaryField()*rhorAUf.boundaryField()))
for (int nonOrth = 0; nonOrth<=nNonOrthCorr; nonOrth++)
Definition at line 43 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::getRefCellValue(), HbyA, Foam::fvc::laplacian(), nNonOrthCorr, p_rgh, phi, phig(), phiHbyA, pRefCell, pRefValue, rAU(), Foam::fvc::reconstruct(), rhorAUf(), and U.
if (closedVolume && compressible)
Definition at line 80 of file pEqn.H.
References compressibility, Foam::fvc::domainIntegrate(), gh, initialMass, p, p_rgh, rho, and thermo.
Variable Documentation
rho = max(rho, rhoMin[i])
Definition at line 3 of file pEqn.H.
HbyA = rAU*UEqn().H()
Definition at line 11 of file pEqn.H.
bool closedVolume = adjustPhi(phiHbyA, U, p_rgh)
Definition at line 24 of file pEqn.H.
phiHbyA = phig
Definition at line 26 of file pEqn.H.
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
Definition at line 39 of file pEqn.H.
Referenced by if().
bool compressible = (compressibility.value() > SMALL)
Definition at line 40 of file pEqn.H.
Referenced by turbulenceFields::execute().
p = p_rgh + rho*gh
Definition at line 74 of file pEqn.H.