OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UnsortedMeshedSurface< Face > Class Template Reference
A surface geometry mesh, in which the surface zone information is conveyed by the 'zoneId' associated with each face.
Public Types
typedef Face FaceType
Face type used.
Public Types inherited from MeshedSurface< Face >
typedef Face FaceType
Face type used.
Public Types inherited from PrimitivePatch< Face,::Foam::List, pointField, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef ::Foam::List< Face > FaceListType
typedef pointField PointFieldType
Public Types inherited from List< Face >
typedef SubList< Face > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("UnsortedMeshedSurface")
Runtime type information.
UnsortedMeshedSurface ()
Construct null.
UnsortedMeshedSurface (const Xfer< pointField > &, const Xfer< List< Face >> &, const Xfer< List< label >> &zoneIds, const Xfer< surfZoneIdentifierList > &)
Construct by transferring components.
UnsortedMeshedSurface (const Xfer< pointField > &, const Xfer< List< Face >> &, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Construct by transferring points, faces.
UnsortedMeshedSurface (const UnsortedMeshedSurface< Face > &)
Construct as copy.
UnsortedMeshedSurface (const MeshedSurface< Face > &)
Construct from a meshedSurface.
UnsortedMeshedSurface (const Xfer< UnsortedMeshedSurface< Face >> &)
Construct by transferring the contents from a UnsortedMeshedSurface.
UnsortedMeshedSurface (const Xfer< MeshedSurface< Face >> &)
Construct by transferring the contents from a meshedSurface.
UnsortedMeshedSurface (const fileName &)
Construct from file name (uses extension to determine type)
UnsortedMeshedSurface (const fileName &, const word &)
Construct from file name (uses extension to determine type)
UnsortedMeshedSurface (const Time &, const word &surfName="")
Construct from objectRegistry and a named surface.
declareRunTimeSelectionTable (autoPtr, UnsortedMeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~UnsortedMeshedSurface ()
Destructor.
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const UnsortedMeshedSurface< Face > &surf),(name, surf))
label size () const
The surface size is the number of faces.
void setSize (const label)
Reset size of face and zone list.
const List< label > & zoneIds () const
Return const access to the zone ids.
const List< surfZoneIdentifier > & zoneToc () const
Return const access to the zone table-of-contents.
surfZoneList sortedZones (labelList &faceMap) const
Sort faces according to zoneIds.
void setOneZone ()
Set zones to 0 and set a single zone.
void setZones (const surfZoneList &)
Set zone ids and zones.
void setZones (const labelUList &sizes, const UList< word > &names)
Set zone ids and zones.
void setZones (const labelUList &sizes)
Set zone ids and zones with default names.
virtual void clear ()
Clear all storage.
UnsortedMeshedSurface subsetMesh (const labelHashSet &include, labelList &pointMap, labelList &faceMap) const
Return new surface.
UnsortedMeshedSurface subsetMesh (const labelHashSet &include) const
Return new surface.
virtual void reset (const Xfer< pointField > &, const Xfer< List< Face >> &, const Xfer< List< label >> &zoneIds)
Transfer components (points, faces, zone ids).
virtual void reset (const Xfer< List< point >> &, const Xfer< List< Face >> &, const Xfer< List< label >> &zoneIds)
Transfer components (points, faces, zone ids).
void transfer (UnsortedMeshedSurface< Face > &)
Transfer the contents of the argument and annul the argument.
void transfer (MeshedSurface< Face > &)
Transfer the contents of the argument and annul the argument.
Xfer< UnsortedMeshedSurface< Face > > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &)
Read from file. Chooses reader based on detected extension.
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void write (const Time &, const word &surfName="") const
Write to database.
void operator= (const UnsortedMeshedSurface< Face > &)
operator MeshedSurfaceProxy< Face > () const
Conversion operator to MeshedSurfaceProxy.
Public Member Functions inherited from MeshedSurface< Face >
ClassName ("MeshedSurface")
Runtime type information.
MeshedSurface ()
Construct null.
MeshedSurface (const Xfer< pointField > &, const Xfer< List< Face >> &, const Xfer< surfZoneList > &)
Construct by transferring components (points, faces, zones).
MeshedSurface (const Xfer< pointField > &, const Xfer< List< Face >> &, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Construct by transferring components (points, faces).
MeshedSurface (const MeshedSurface &)
Construct as copy.
MeshedSurface (const UnsortedMeshedSurface< Face > &)
Construct from a UnsortedMeshedSurface.
MeshedSurface (const polyBoundaryMesh &, const bool globalPoints=false)
Construct from a boundary mesh with local points/faces.
MeshedSurface (const surfMesh &)
Construct from a surfMesh.
MeshedSurface (const Xfer< UnsortedMeshedSurface< Face >> &)
Construct by transferring the contents from a UnsortedMeshedSurface.
MeshedSurface (const Xfer< MeshedSurface< Face >> &)
Construct by transferring the contents from a MeshedSurface.
MeshedSurface (const fileName &)
Construct from file name (uses extension to determine type)
MeshedSurface (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
MeshedSurface (const Time &, const word &surfName="")
Construct from database.
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
Destructor.
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< Face > &surf),(name, surf))
label size () const
The surface size is the number of faces.
const List< Face > & faces () const
Return const access to the faces.
const List< surfZone > & surfZones () const
Const access to the surface zones.
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
Add surface zones.
virtual void removeZones ()
Remove surface zones.
virtual void movePoints (const pointField &)
Move points.
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
virtual void reset (const Xfer< pointField > &points, const Xfer< List< Face >> &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void reset (const Xfer< List< point >> &points, const Xfer< List< Face >> &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void cleanup (const bool verbose)
Remove invalid faces.
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label triangulate ()
Triangulate in-place, returning the number of triangles added.
virtual label triangulate (List< label > &faceMap)
Triangulate in-place, returning the number of triangles added.
MeshedSurface subsetMesh (const labelHashSet &include, labelList &pointMap, labelList &faceMap) const
Return new surface.
MeshedSurface subsetMesh (const labelHashSet &include) const
Return new surface.
void transfer (MeshedSurface< Face > &)
Transfer the contents of the argument and annul the argument.
void transfer (UnsortedMeshedSurface< Face > &)
Transfer the contents of the argument and annul the argument.
Xfer< MeshedSurface< Face > > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
void writeStats (Ostream &os) const
void write (const Time &, const word &surfName="") const
Write to database.
void operator= (const MeshedSurface< Face > &)
operator MeshedSurfaceProxy< Face > () const
Conversion operator to MeshedSurfaceProxy.
template<class Face>
MeshedSurface (const MeshedSurface< Face > &surf)
template<>
bool isTri ()
Specialization for holding triangulated information.
template<>
label triangulate ()
Specialization for holding triangulated information.
template<>
label triangulate (List< label > &faceMap)
Specialization for holding triangulated information.
Public Member Functions inherited from PrimitivePatch< Face,::Foam::List, pointField, point >
PrimitivePatch (const ::Foam::List< Face > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (const Xfer< ::Foam::List< Face >> &faces, const Xfer< List< point >> &points)
Construct from components.
PrimitivePatch (::Foam::List< Face > &faces, Field< point > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face,::Foam::List, pointField, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceNormals () const
Return face normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=NULL) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=NULL) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face,::Foam::List, pointField, point > &)
Assignment.
Public Member Functions inherited from List< Face >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Face &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Face > &)
Copy constructor.
List (const Xfer< List< Face >> &)
Construct by transferring the parameter contents.
List (List< Face > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Face > &, const labelUList &mapAddressing)
Construct as subset.
List (const FixedList< Face, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Face > &)
Construct as copy of PtrList<T>
List (const SLList< Face > &)
Construct as copy of SLList<T>
List (const UIndirectList< Face > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Face > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< Face > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Face &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Face &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Face &)
Append an element at the end of the list.
void append (const UList< Face > &)
Append a List at the end of this list.
void append (const UIndirectList< Face > &)
Append a UIndirectList at the end of this list.
void transfer (List< Face > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Face, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Face > &)
Transfer the contents of the argument List into this list.
Xfer< List< Face > > xfer ()
Transfer contents to the Xfer container.
Face & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Face > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Face > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< Face > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Face > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< Face > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Face > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const Face &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()
Construct null.
virtual ~surfaceFormatsCore ()
Destructor.
Static Public Member Functions
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< UnsortedMeshedSurface > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< UnsortedMeshedSurface > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const UnsortedMeshedSurface< Face > &)
Write to file.
Static Public Member Functions inherited from MeshedSurface< Face >
static bool isTri ()
Face storage only handles triangulated faces.
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< MeshedSurface > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< MeshedSurface > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const MeshedSurface< Face > &)
Write to file.
Static Public Member Functions inherited from List< Face >
static const List< Face > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
static fileName localMeshFileName (const word &surfName="")
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName="")
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName="")
Find mesh file with surfName.
Protected Member Functions
List< label > & storedZoneIds ()
Return non-const access to the zone Ids.
List< surfZoneIdentifier > & storedZoneToc ()
Return non-const access to the zone table-of-contents.
virtual void remapFaces (const labelUList &faceMap)
Set new zones from faceMap.
Protected Member Functions inherited from MeshedSurface< Face >
void transcribe (MeshedSurface< face > &)
Transfer points/zones and transcribe face -> triFace.
void checkZones ()
Basic sanity check on zones.
pointField & storedPoints ()
Non-const access to global points.
List< Face > & storedFaces ()
Non-const access to the faces.
surfZoneList & storedZones ()
Non-const access to the zones.
void sortFacesAndStore (const Xfer< List< Face >> &unsortedFaces, const Xfer< List< label >> &zoneIds, const bool sorted)
Sort faces by zones and store sorted faces.
template<>
void transcribe (MeshedSurface< face > &surf)
template<>
void transcribe (MeshedSurface< face > &surf)
Protected Member Functions inherited from List< Face >
void size (const label)
Override size to be inconsistent with allocated storage.
Friends
template<class Face2 >
class MeshedSurface
template<class Face2 >
class UnsortedMeshedSurface
class surfMesh
Additional Inherited Members
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Static Protected Member Functions inherited from surfaceFormatsCore
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a list with a single entry,.
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
template<class Face>
class Foam::UnsortedMeshedSurface< Face >
A surface geometry mesh, in which the surface zone information is conveyed by the 'zoneId' associated with each face.
This form of surface description is particularly useful for reading in surface meshes from third-party formats (eg, obj, stl, gts, etc.). It can also be particularly useful for situations in which the surface many be adjusted in an arbitrary manner without worrying about needed to adjust the zone information (eg, surface refinement).
See also
The Foam::MeshedSurface - which is organized as a surface mesh, but with independent zone information.
Source files
UnsortedMeshedSurface.H
UnsortedMeshedSurface.C
Definition at line 74 of file MeshedSurface.H.
Member Typedef Documentation
typedef Face FaceType
Face type used.
Definition at line 137 of file UnsortedMeshedSurface.H.
Constructor & Destructor Documentation
UnsortedMeshedSurface ()
Construct null.
Definition at line 146 of file UnsortedMeshedSurface.C.
Referenced by UnsortedMeshedSurface< Face >::subsetMesh(), and UnsortedMeshedSurface< Face >::UnsortedMeshedSurface().
UnsortedMeshedSurface (const Xfer< pointField > & pointLst, const Xfer< List< Face >> & faceLst, const Xfer< List< label >> & zoneIds, const Xfer< surfZoneIdentifierList > & zoneTofc)
Construct by transferring components.
(points, faces, zone ids, zone info).
Definition at line 154 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::UnsortedMeshedSurface().
UnsortedMeshedSurface (const Xfer< pointField > & pointLst, const Xfer< List< Face >> & faceLst, const labelUList & zoneSizes = labelUList(), const UList< word > & zoneNames = UList<word>())
Construct by transferring points, faces.
Use zone information, or set single default zone
Definition at line 169 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::setOneZone(), UnsortedMeshedSurface< Face >::setZones(), UList< T >::size(), and UnsortedMeshedSurface< Face >::UnsortedMeshedSurface().
UnsortedMeshedSurface (const UnsortedMeshedSurface< Face > & surf)
Construct as copy.
Definition at line 198 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::UnsortedMeshedSurface().
UnsortedMeshedSurface (const MeshedSurface< Face > & surf)
Construct from a meshedSurface.
Definition at line 214 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::setZones(), MeshedSurface< Face >::surfZones(), and UnsortedMeshedSurface< Face >::UnsortedMeshedSurface().
UnsortedMeshedSurface (const Xfer< UnsortedMeshedSurface< Face >> & surf)
Construct by transferring the contents from a UnsortedMeshedSurface.
Definition at line 230 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::transfer(), and UnsortedMeshedSurface< Face >::UnsortedMeshedSurface().
UnsortedMeshedSurface (const Xfer< MeshedSurface< Face >> & surf)
Construct by transferring the contents from a meshedSurface.
Definition at line 242 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::transfer(), and UnsortedMeshedSurface< Face >::UnsortedMeshedSurface().
UnsortedMeshedSurface (const fileName & name)
Construct from file name (uses extension to determine type)
Definition at line 266 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::read(), and UnsortedMeshedSurface< Face >::UnsortedMeshedSurface().
UnsortedMeshedSurface (const fileName & name, const word & ext)
Construct from file name (uses extension to determine type)
Definition at line 254 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::read().
UnsortedMeshedSurface (const Time & t, const word & surfName = "")
Construct from objectRegistry and a named surface.
Definition at line 276 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::transfer().
~UnsortedMeshedSurface () virtual
Destructor.
Definition at line 291 of file UnsortedMeshedSurface.C.
Member Function Documentation
List<label>& storedZoneIds () inline protected
Return non-const access to the zone Ids.
Definition at line 117 of file UnsortedMeshedSurface.H.
List<surfZoneIdentifier>& storedZoneToc () inline protected
Return non-const access to the zone table-of-contents.
Definition at line 123 of file UnsortedMeshedSurface.H.
References Foam::faceMap(), and UnsortedMeshedSurface< Face >::remapFaces().
void remapFaces (const labelUList & faceMap) protected virtual
Set new zones from faceMap.
Reimplemented from MeshedSurface< Face >.
Definition at line 393 of file UnsortedMeshedSurface.C.
References forAll, Foam::notNull(), UnsortedMeshedSurface< Face >::setOneZone(), UList< T >::size(), and List< T >::transfer().
Referenced by UnsortedMeshedSurface< Face >::setZones(), and UnsortedMeshedSurface< Face >::storedZoneToc().
TypeName ("UnsortedMeshedSurface< Face >")
Runtime type information.
bool canReadType (const word & ext, const bool verbose = false) static
Can we read this file format?
Definition at line 53 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::canWriteType().
Referenced by UnsortedMeshedSurface< Face >::writeTypes().
bool canRead (const fileName & name, const bool verbose = false) static
Can we read this file format?
Definition at line 87 of file UnsortedMeshedSurface.C.
References fileName::ext(), fileName::lessExt(), and UnsortedMeshedSurface< Face >::write().
Referenced by UnsortedMeshedSurface< Face >::canWriteType().
bool canWriteType (const word & ext, const bool verbose = false) static
Can we write this file format?
Definition at line 70 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::canRead().
Referenced by UnsortedMeshedSurface< Face >::canReadType().
Foam::wordHashSet readTypes () static
Definition at line 38 of file UnsortedMeshedSurface.C.
Foam::wordHashSet writeTypes () static
Definition at line 45 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::canReadType().
declareRunTimeSelectionTable (autoPtr , UnsortedMeshedSurface< Face > , fileExtension , (const fileName &name) , (name))
Foam::autoPtr< Foam::UnsortedMeshedSurface< Face > > New (const fileName & name, const word & ext) static
Select constructed from filename (explicit extension)
Definition at line 32 of file UnsortedMeshedSurfaceNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::found(), InfoInFunction, Foam::name(), Foam::New(), and Foam::nl.
Referenced by UnsortedMeshedSurface< Face >::read().
Foam::autoPtr< Foam::UnsortedMeshedSurface< Face > > New (const fileName & name) static
Select constructed from filename (implicit extension)
Definition at line 74 of file UnsortedMeshedSurfaceNew.C.
References fileName::ext(), fileName::lessExt(), and Foam::New().
declareMemberFunctionSelectionTable (void , UnsortedMeshedSurface< Face > , write , fileExtension , (const fileName &name, const UnsortedMeshedSurface< Face > &surf) , (name, surf))
void write (const fileName & name, const UnsortedMeshedSurface< Face > & surf) static
Write to file.
Definition at line 103 of file UnsortedMeshedSurface.C.
References Foam::endl(), Foam::exit(), fileName::ext(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::found(), InfoInFunction, Foam::name(), Foam::nl, and write().
Referenced by UnsortedMeshedSurface< Face >::canRead(), UnsortedMeshedSurface< Face >::read(), and UnsortedMeshedSurface< Face >::write().
label size () const inline
The surface size is the number of faces.
Definition at line 260 of file UnsortedMeshedSurface.H.
References setSize(), and MeshedSurface< Face >::size().
Referenced by UnsortedMeshedSurface< Face >::setOneZone(), UnsortedMeshedSurface< Face >::setZones(), GTSsurfaceFormat< Face >::write(), and AC3DsurfaceFormat< Face >::write().
void setSize (const label s)
Reset size of face and zone list.
Definition at line 426 of file UnsortedMeshedSurface.C.
References List< T >::setSize(), and MeshedSurface< Face >::storedFaces().
const List<label>& zoneIds () const inline
Return const access to the zone ids.
Definition at line 269 of file UnsortedMeshedSurface.H.
Referenced by UnsortedMeshedSurface< Face >::reset(), GTSsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeBinary(), and UnsortedMeshedSurface< Face >::zoneToc().
const List<surfZoneIdentifier>& zoneToc () const inline
Return const access to the zone table-of-contents.
Definition at line 275 of file UnsortedMeshedSurface.H.
References UnsortedMeshedSurface< Face >::clear(), UnsortedMeshedSurface< Face >::read(), UnsortedMeshedSurface< Face >::reset(), UnsortedMeshedSurface< Face >::setOneZone(), UnsortedMeshedSurface< Face >::setZones(), UnsortedMeshedSurface< Face >::sortedZones(), UnsortedMeshedSurface< Face >::subsetMesh(), UnsortedMeshedSurface< Face >::transfer(), UnsortedMeshedSurface< Face >::xfer(), and UnsortedMeshedSurface< Face >::zoneIds().
Referenced by GTSsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), and STLsurfaceFormat< Face >::writeAscii().
Foam::surfZoneList sortedZones (labelList & faceMap) const
Sort faces according to zoneIds.
Returns a surfZoneList and sets faceMap to index within faces() (i.e. map from original,unsorted to sorted)
Definition at line 445 of file UnsortedMeshedSurface.C.
References HashTableCore::end(), HashTable< T, label, Hash< label > >::find(), HashTable< T, Key, Hash >::find(), forAll, forAllIter, HashTable< T, label, Hash< label > >::insert(), HashTable< T, Key, Hash >::insert(), lookup(), Foam::name(), List< T >::setSize(), List< T >::size(), HashTable< T, Key, Hash >::size(), and UnsortedMeshedSurface< Face >::subsetMesh().
Referenced by UnsortedMeshedSurface< Face >::clear(), MeshedSurface< Face >::MeshedSurface(), UnsortedMeshedSurface< Face >::operator=(), MeshedSurface< Face >::transfer(), AC3DsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeAscii(), and UnsortedMeshedSurface< Face >::zoneToc().
void setOneZone ()
Set zones to 0 and set a single zone.
Definition at line 298 of file UnsortedMeshedSurface.C.
References List< T >::setSize(), UnsortedMeshedSurface< Face >::setZones(), and UnsortedMeshedSurface< Face >::size().
Referenced by UnsortedMeshedSurface< Face >::remapFaces(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), and UnsortedMeshedSurface< Face >::zoneToc().
void setZones (const surfZoneList & zoneLst)
Set zone ids and zones.
Definition at line 321 of file UnsortedMeshedSurface.C.
References forAll, List< T >::setSize(), List< T >::size(), surfZone::size(), UnsortedMeshedSurface< Face >::size(), and surfZone::start().
Referenced by UnsortedMeshedSurface< Face >::setOneZone(), UnsortedMeshedSurface< Face >::setZones(), UnsortedMeshedSurface< Face >::transfer(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), and UnsortedMeshedSurface< Face >::zoneToc().
void setZones (const labelUList & sizes, const UList< word > & names)
Set zone ids and zones.
Definition at line 342 of file UnsortedMeshedSurface.C.
References forAll, List< T >::setSize(), UnsortedMeshedSurface< Face >::setZones(), UnsortedMeshedSurface< Face >::size(), and UList< T >::size().
void setZones (const labelUList & sizes)
Set zone ids and zones with default names.
Definition at line 366 of file UnsortedMeshedSurface.C.
References forAll, Foam::name(), UnsortedMeshedSurface< Face >::remapFaces(), List< T >::setSize(), UnsortedMeshedSurface< Face >::size(), and UList< T >::size().
void clear () virtual
Clear all storage.
Reimplemented from MeshedSurface< Face >.
Definition at line 435 of file UnsortedMeshedSurface.C.
References List< T >::clear(), MeshedSurface< Face >::clear(), and UnsortedMeshedSurface< Face >::sortedZones().
Referenced by UnsortedMeshedSurface< Face >::operator=(), OFSsurfaceFormat< Face >::read(), UnsortedMeshedSurface< Face >::read(), UnsortedMeshedSurface< Face >::transfer(), MeshedSurface< Face >::transfer(), and UnsortedMeshedSurface< Face >::zoneToc().
Foam::UnsortedMeshedSurface< Face > subsetMesh (const labelHashSet & include, labelList & pointMap, labelList & faceMap) const
Return new surface.
Returns return pointMap, faceMap from subsetMeshMap
Definition at line 531 of file UnsortedMeshedSurface.C.
References List< T >::clear(), f(), forAll, PrimitivePatch< Face,::Foam::List, pointField, point >::localFaces(), PrimitivePatch< Face,::Foam::List, pointField, point >::localPoints(), List< T >::size(), PatchTools::subsetMap(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), Foam::xferCopy(), and Foam::xferMove().
Referenced by UnsortedMeshedSurface< Face >::sortedZones(), UnsortedMeshedSurface< Face >::subsetMesh(), AC3DsurfaceFormat< Face >::write(), and UnsortedMeshedSurface< Face >::zoneToc().
Foam::UnsortedMeshedSurface< Face > subsetMesh (const labelHashSet & include) const
Return new surface.
Definition at line 585 of file UnsortedMeshedSurface.C.
References Foam::faceMap(), UnsortedMeshedSurface< Face >::reset(), and UnsortedMeshedSurface< Face >::subsetMesh().
void reset (const Xfer< pointField > & pointLst, const Xfer< List< Face >> & faceLst, const Xfer< List< label >> & zoneIds) virtual
Transfer components (points, faces, zone ids).
Definition at line 596 of file UnsortedMeshedSurface.C.
References Foam::notNull(), MeshedSurface< Face >::reset(), List< T >::transfer(), and UnsortedMeshedSurface< Face >::zoneIds().
Referenced by UnsortedMeshedSurface< Face >::subsetMesh(), and UnsortedMeshedSurface< Face >::zoneToc().
void reset (const Xfer< List< point >> & pointLst, const Xfer< List< Face >> & faceLst, const Xfer< List< label >> & zoneIds) virtual
Transfer components (points, faces, zone ids).
Definition at line 618 of file UnsortedMeshedSurface.C.
References Foam::notNull(), MeshedSurface< Face >::reset(), List< T >::transfer(), UnsortedMeshedSurface< Face >::transfer(), and UnsortedMeshedSurface< Face >::zoneIds().
void transfer (UnsortedMeshedSurface< Face > & surf)
Transfer the contents of the argument and annul the argument.
Definition at line 640 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::clear(), MeshedSurface< Face >::reset(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), List< T >::transfer(), and Foam::xferMove().
Referenced by OFSsurfaceFormat< Face >::read(), UnsortedMeshedSurface< Face >::read(), UnsortedMeshedSurface< Face >::reset(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), and UnsortedMeshedSurface< Face >::zoneToc().
void transfer (MeshedSurface< Face > & surf)
Transfer the contents of the argument and annul the argument.
Definition at line 660 of file UnsortedMeshedSurface.C.
References MeshedSurface< Face >::clear(), MeshedSurface< Face >::reset(), UnsortedMeshedSurface< Face >::setZones(), MeshedSurface< Face >::storedFaces(), MeshedSurface< Face >::storedPoints(), MeshedSurface< Face >::surfZones(), and Foam::xferMove().
Foam::Xfer< Foam::UnsortedMeshedSurface< Face > > xfer ()
Transfer contents to the Xfer container.
Definition at line 678 of file UnsortedMeshedSurface.C.
References Foam::xferMove().
Referenced by UnsortedMeshedSurface< Face >::zoneToc().
bool read (const fileName & name, const word & ext)
Read from file. Chooses reader based on explicit extension.
Definition at line 704 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::clear(), UnsortedMeshedSurface< Face >::New(), UnsortedMeshedSurface< Face >::transfer(), and UnsortedMeshedSurface< Face >::write().
Referenced by UnsortedMeshedSurface< Face >::read(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), and UnsortedMeshedSurface< Face >::zoneToc().
bool read (const fileName & name) virtual
Read from file. Chooses reader based on detected extension.
Reimplemented from MeshedSurface< Face >.
Reimplemented in FTRsurfaceFormat< Face >, and GTSsurfaceFormat< Face >.
Definition at line 686 of file UnsortedMeshedSurface.C.
References fileName::ext(), fileName::lessExt(), and UnsortedMeshedSurface< Face >::read().
virtual void write (const fileName & name) const inline virtual
Generic write routine. Chooses writer based on extension.
Reimplemented from MeshedSurface< Face >.
Reimplemented in GTSsurfaceFormat< Face >.
Definition at line 359 of file UnsortedMeshedSurface.H.
References UnsortedMeshedSurface< Face >::operator=(), and UnsortedMeshedSurface< Face >::write().
void write (const Time & t, const word & surfName = "") const
Write to database.
Definition at line 719 of file UnsortedMeshedSurface.C.
References MeshedSurfaceProxy< Face >::write().
void operator= (const UnsortedMeshedSurface< Face > & surf)
Definition at line 732 of file UnsortedMeshedSurface.C.
References UnsortedMeshedSurface< Face >::clear(), Foam::faceMap(), MeshedSurface< Face >::faces(), PrimitivePatch< Face,::Foam::List, pointField, point >::points(), UnsortedMeshedSurface< Face >::sortedZones(), MeshedSurface< Face >::storedFaces(), and MeshedSurface< Face >::storedPoints().
Referenced by UnsortedMeshedSurface< Face >::write().
operator MeshedSurfaceProxy< Face > () const
Conversion operator to MeshedSurfaceProxy.
Friends And Related Function Documentation
friend class MeshedSurface friend
Definition at line 80 of file UnsortedMeshedSurface.H.
friend class UnsortedMeshedSurface friend
Definition at line 81 of file UnsortedMeshedSurface.H.
friend class surfMesh friend
Definition at line 82 of file UnsortedMeshedSurface.H.
The documentation for this class was generated from the following files:
src/surfMesh/MeshedSurface/MeshedSurface.H
src/surfMesh/UnsortedMeshedSurface/UnsortedMeshedSurface.H
src/surfMesh/UnsortedMeshedSurface/UnsortedMeshedSurface.C
src/surfMesh/UnsortedMeshedSurface/UnsortedMeshedSurfaceNew.C