OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UList< T > Class Template Reference
A 1D vector of objects of type <T>, where the size of the vector is known and can be used for subscript bounds checking, etc.
Inherited by List< T >, pTraits< UList< T > >, SubList< T >, List< bodyMesh * >, List< bool >, List< cell >, List< cellCutType >, List< cellShape >, List< cellZone * >, List< CGAL::indexedVertex >, List< char >, List< CloudFunctionObject< CloudType > * >, List< CloudFunctionObject< KinematicCloud< CloudType > > * >, List< CloudFunctionObject< KinematicCloud< Foam::DSMCCloud > > * >, List< coalCloud * >, List< const Foam::cellModel * >, List< const Foam::lduInterface * >, List< const Foam::UList * >, List< const label * >, List< const lduInterface * >, List< const lduInterfaceField * >, List< const LduInterfaceField< Type > * >, List< coordinateSystem * >, List< curvedEdge * >, List< edge >, List< engineValve * >, List< entry * >, List< extendedFeatureEdgeMesh * >, List< Face >, List< faceList >, List< faceZone * >, List< Field< scalar > >, List< Field< Type > * >, List< Field< Type > >, List< Foam::AMIInterpolation * >, List< Foam::boundaryPatch * >, List< Foam::boundBox >, List< Foam::cellModel * >, List< Foam::cellSizeAndAlignmentControl * >, List< Foam::cellSizeFunction * >, List< Foam::coordinateSystem * >, List< Foam::coordSet * >, List< Foam::coupledFacePair * >, List< Foam::decompositionMethod * >, List< Foam::diameterModels::IATEsource * >, List< Foam::dictionary * >, List< Foam::dictionary >, List< Foam::dimensioned * >, List< Foam::DimensionedField< scalar, Foam::volMesh > * >, List< Foam::DynamicList< char > >, List< Foam::DynamicList< DSMCParcel< ParcelType > * > >, List< Foam::DynamicList< Foam::List > >, List< Foam::DynamicList< Foam::molecule * > >, List< Foam::DynamicList< Foam::string > >, List< Foam::DynamicList< Foam::Vector > >, List< Foam::DynamicList< label > >, List< Foam::DynamicList< ParcelType * > >, List< Foam::DynamicList< parcelType * > >, List< Foam::DynamicList< scalar > >, List< Foam::ensightPart * >, List< Foam::extendedFeatureEdgeMesh * >, List< Foam::face >, List< Foam::faceSets >, List< Foam::Field * >, List< Foam::Field >, List< Foam::Field< Foam::Vector > >, List< Foam::Field< LUType > * >, List< Foam::Field< scalar > * >, List< Foam::Field< Type > * >, List< Foam::fieldAverageItem >, List< Foam::FieldField< Foam::Field, scalar > * >, List< Foam::FixedList< label, 3 > >, List< Foam::FixedList< scalar, 2 > >, List< Foam::FixedList< scalar, 3 > >, List< Foam::fvFieldDecomposer::patchFieldDecomposer * >, List< Foam::fvFieldDecomposer::processorSurfacePatchFieldDecomposer * >, List< Foam::fvFieldDecomposer::processorVolPatchFieldDecomposer * >, List< Foam::fvMesh * >, List< Foam::GeometricField * >, List< Foam::gradingDescriptors >, List< Foam::IDLList< Foam::molecule > >, List< Foam::IDLList< ParticleType > >, List< Foam::IDLList< typename Foam::DSMCCloud::parcelType > >, List< Foam::ignitionSite * >, List< Foam::indexedOctree * >, List< Foam::indexedOctree::node >, List< Foam::indexedOctree< Foam::treeDataEdge > * >, List< Foam::indexedOctree< Foam::treeDataPoint > * >, List< Foam::interpolation< Foam::Vector > * >, List< Foam::interpolation< scalar > * >, List< Foam::IOList * >, List< Foam::lduMatrix * >, List< Foam::lduPrimitiveMesh * >, List< Foam::liquidProperties * >, List< Foam::List * >, List< Foam::List >, List< Foam::List< Foam::face > >, List< Foam::List< Foam::Field< scalar > > >, List< Foam::List< Foam::List< scalar > > >, List< Foam::List< Foam::meshReader::cellFaceIdentifier > >, List< Foam::List< Foam::treeBoundBox > >, List< Foam::List< Foam::Vector > >, List< Foam::List< Key > >, List< Foam::List< label > >, List< Foam::List< scalar > >, List< Foam::List< T > >, List< Foam::mappedPatchBase * >, List< Foam::molecule::constantProperties >, List< Foam::objectHit >, List< Foam::objectMap >, List< Foam::OFstream * >, List< Foam::PackedBoolList >, List< Foam::Pair >, List< Foam::Pair< label > >, List< Foam::PatchInteractionModel< Foam::DSMCCloud > * >, List< Foam::phaseProperties >, List< Foam::pointConstraint >, List< Foam::pointFieldDecomposer::patchFieldDecomposer * >, List< Foam::pointMesh * >, List< Foam::PrimitivePatch * >, List< Foam::procLduInterface * >, List< Foam::PtrList< Foam::AMIInterpolation > * >, List< Foam::PtrList< Foam::fvMatrix > >, List< Foam::PtrList< Foam::lduInterfaceField > * >, List< Foam::radiation::radiativeIntensityRay * >, List< Foam::RBD::joint * >, List< Foam::RBD::restraint * >, List< Foam::RBD::rigidBody * >, List< Foam::RBD::subBody * >, List< Foam::Reaction::specieCoeffs >, List< Foam::Reaction< SolidThermo > * >, List< Foam::Reaction< ThermoType > * >, List< Foam::referredWallFace >, List< Foam::searchableSurface * >, List< Foam::SHA1Digest >, List< Foam::sixDoFRigidBodyMotionConstraint * >, List< Foam::sixDoFRigidBodyMotionRestraint * >, List< Foam::solidBodyMotionFunction * >, List< Foam::solidProperties * >, List< Foam::solutionControl::fieldData >, List< Foam::spatialTransform >, List< Foam::SpatialVector >, List< Foam::surfaceZonesInfo * >, List< Foam::surfZone >, List< Foam::surfZoneIdentifier >, List< Foam::Tensor >, List< Foam::Time * >, List< Foam::token >, List< Foam::Tuple2< Foam::Vector, Foam::Vector > >, List< Foam::Tuple2< Foam::word, Foam::Tuple2< bool, scalar > > >, List< Foam::Tuple2< Foam::word, Foam::word > >, List< Foam::Tuple2< Foam::word, scalar > >, List< Foam::Tuple2< label, Foam::List< Foam::List > > >, List< Foam::Tuple2< label, scalar > >, List< Foam::Tuple2< mapType, Foam::List > >, List< Foam::Tuple2< scalar, Foam::fileName > >, List< Foam::Tuple2< scalar, scalar > >, List< Foam::Tuple2< scalar, Type > >, List< Foam::Tuple2< Type, scalar > >, List< Foam::Tuple2< Type, Type > >, List< Foam::UPtrList * >, List< Foam::Vector >, List< Foam::VectorSpace >, List< Foam::vectorTensorTransform >, List< Foam::volumeType >, List< Foam::word >, List< force * >, List< functionObject * >, List< fvPatchMapper * >, List< GasThermo * >, List< geometricSurfacePatch >, List< gradingDescriptor >, List< injectionModel * >, List< InjectionModel< CloudType > * >, List< InjectionModel< Foam::KinematicCloud< CloudType > > * >, List< InjectionModel< Foam::KinematicCloud< Foam::DSMCCloud > > * >, List< instant >, List< int >, List< joint * >, List< kinematicParcelInjectionData >, List< label >, List< labelledTri >, List< labelList >, List< labelListList >, List< lduScheduleEntry >, List< List< pointIndexHit > >, List< List< scalar > >, List< mergeInfo >, List< MRFZone * >, List< option * >, List< pairPotential * >, List< ParticleForce< CloudType > * >, List< ParticleForce< KinematicCloud< CloudType > > * >, List< ParticleForce< KinematicCloud< Foam::DSMCCloud > > * >, List< PatchField< Type > * >, List< patchInteractionData >, List< phaseModel * >, List< pointPatchMapper * >, List< pointZone * >, List< polyDecomp >, List< polyMeshModifier * >, List< porosityModel * >, List< profileModel * >, List< pyrolysisModel * >, List< reactingMultiphaseParcelInjectionData >, List< reactingParcelInjectionData >, List< Reaction< ThermoType > * >, List< refineCell >, List< refineMode >, List< regionModelFunctionObject * >, List< sampledSet * >, List< sampledSurface * >, List< scalar >, List< scalarField >, List< scalarList >, List< scalarRange >, List< searchableSurface * >, List< sideVolumeType >, List< simpleRegIOobject * >, List< SolidThermo * >, List< string >, List< substance >, List< surfAndLabel >, List< T * >, List< tetherPotential * >, List< ThermoType * >, List< treeBoundBox >, List< Tuple2< scalar, List< Tuple2< scalar, scalar > > > >, List< Tuple2< scalar, List< Tuple2< scalar, Type > > > >, List< Tuple2< scalar, scalar > >, List< Tuple2< scalar, Type > >, List< typename DSMCParcel< ParcelType >::constantProperties >, List< typename ParcelType::constantProperties >, List< unsigned int >, List< vector >, List< vectorField >, List< volatileData >, List< vtkTextActor * >, List< word >, List< wordRe >, List< ZoneType * >, and SubList< point >.
Classes
class greater
Greater function class that can be used for sorting.
class less
Less function class that can be used for sorting.
Public Types
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static const UList< T > & null ()
Return a null UList.
Friends
class List< T >
Declare friendship with the List class.
class SubList< T >
Declare friendship with the SubList class.
Ostream & operator (Ostream &, const UList< T > &)
Istream & operator>> (Istream &, UList< T > &)
Read UList contents from Istream. Requires size to have been set.
Detailed Description
template<class T>
class Foam::UList< T >
A 1D vector of objects of type <T>, where the size of the vector is known and can be used for subscript bounds checking, etc.
Storage is not allocated during construction or use but is supplied to the constructor as an argument. This type of list is particularly useful for lists that refer to parts of existing lists such as SubList.
Source files
UList.H
UList.C
UListI.H
UListIO.C
Definition at line 60 of file HashTable.H.
Member Typedef Documentation
typedef T value_type
Type of values the UList contains.
Definition at line 251 of file UList.H.
typedef T& reference
Type that can be used for storing into.
UList::value_type objects.
Definition at line 255 of file UList.H.
typedef const T& const_reference
Type that can be used for storing into.
constant UList::value_type objects
Definition at line 259 of file UList.H.
typedef label difference_type
The type that can represent the difference between any two.
UList iterator objects.
Definition at line 263 of file UList.H.
typedef label size_type
The type that can represent the size of a UList.
Definition at line 266 of file UList.H.
typedef T* iterator
Random access iterator for traversing UList.
Definition at line 272 of file UList.H.
typedef const T* const_iterator
Random access iterator for traversing UList.
Definition at line 284 of file UList.H.
typedef T* reverse_iterator
Reverse iterator for reverse traversal of UList.
Definition at line 302 of file UList.H.
typedef const T* const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Definition at line 314 of file UList.H.
Constructor & Destructor Documentation
UList () inline
Null constructor.
Definition at line 33 of file UListI.H.
Referenced by UList< T >::greater::operator()().
UList (T *__restrict__ v, label size) inline
Construct from components.
Definition at line 41 of file UListI.H.
Member Function Documentation
const Foam::UList< T > & null () inline static
Return a null UList.
Definition at line 51 of file UListI.H.
Referenced by FieldMapper::directAddressing(), pointFieldReconstructor::pointPatchFieldReconstructor::directAddressing(), fvFieldReconstructor::fvPatchFieldReconstructor::directAddressing(), ensightPart::writeScalarField(), and ensightPart::writeVectorField().
Foam::label fcIndex (const label i) const inline
Return the forward circular index, i.e. the next index.
which returns to the first at the end of the list
Definition at line 58 of file UListI.H.
References UList< T >::size().
Referenced by pointMVCWeight::calcWeights(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), primitiveMesh::checkCommonOrder(), primitiveMesh::checkEdgeLength(), primitiveMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceAngles(), edgeCollapser::checkMeshQuality(), polyMeshGeometry::checkTriangleTwist(), wallBoundedParticle::crossDiagonalEdge(), face::edgeDirection(), primitiveMeshTools::faceConcavity(), face::faceEdge(), primitiveMesh::faceEdges(), mappedPatchBase::facePoint(), polyMeshTetDecomposition::faceTetIndices(), isoSurface::generateFaceTriPoints(), hexRef8::getAnchorLevel(), edgeFaceCirculator::getMinIndex(), combineFaces::getOutsideFace(), face::inertia(), face::nextLabel(), minEqOpFace::operator()(), listPlusEqOp< T >::operator()(), ifEqEqOp< value >::operator()(), UList< T >::greater::operator()(), triSurfaceTools::otherEdges(), treeDataFace::overlaps(), OBJsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), snappySnapDriver::repatchToSurface(), faceCollapser::setRefinement(), createShellMesh::setRefinement(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), meshRefinement::splitFaces(), syncTools::syncEdgeMap(), tetIndices::tetIndices(), particle< Type >::tetNeighbour(), wallBoundedParticle::trackToEdge(), particle< Type >::trackToFace(), polyMeshTetDecomposition::triangleTetIndices(), MeshedSurface< Face >::triangulate(), triSurfaceTools::triangulateFaceCentre(), patchEdgeFaceRegions::updateEdge(), and patchEdgeFaceRegions::updateFace().
Foam::label rcIndex (const label i) const inline
Return the reverse circular index, i.e. the previous index.
which returns to the last at the beginning of the list
Definition at line 65 of file UListI.H.
References UList< T >::size().
Referenced by pointMVCWeight::calcWeights(), primitiveMesh::checkCommonOrder(), wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), face::edgeDirection(), hexRef8::getAnchorLevel(), edgeFaceCirculator::getMinIndex(), NamedEnum< Enum, nEnum >::names(), minEqOpFace::operator()(), faceEqOp< T, CombineOp >::operator()(), ifEqEqOp< value >::operator()(), UList< T >::greater::operator()(), face::prevLabel(), snappySnapDriver::repatchToSurface(), faceCollapser::setRefinement(), createShellMesh::setRefinement(), tetDecomposer::setRefinement(), particle< Type >::tetNeighbour(), and wallBoundedParticle::trackToEdge().
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
if the element is a primitive type i.e. contiguous<T>() == true. Note that is of type streamsize since used in stream ops
Definition at line 102 of file UList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and T.
Referenced by mapDistribute::distribute(), globalIndex::gather(), Pstream::gatherList(), List< T >::List(), Pstream::listCombineGather(), Pstream::listCombineScatter(), UList< T >::greater::operator()(), processorLduInterface::receive(), globalIndex::scatter(), and processorLduInterface::send().
const T * cdata () const inline
Return a const pointer to the first data element,.
similar to the STL front() method and the string::data() method This can be used (with caution) when interfacing with C code.
Definition at line 142 of file UListI.H.
Referenced by UList< T >::greater::operator()(), and PackedList< nBits >::write().
T * data () inline
Return a pointer to the first data element,.
similar to the STL front() method and the string::data() method This can be used (with caution) when interfacing with C code.
Definition at line 149 of file UListI.H.
Referenced by patchDataWave< TransferType >::correct(), Foam::cwd(), decompositionMethod::decompose(), List< T >::List(), UList< T >::greater::operator()(), PackedList< nBits >::read(), structuredRenumber::renumber(), and UList< T >::writeEntry().
T & first () inline
Return the first element of the list.
Definition at line 114 of file UListI.H.
References UList< T >::operator[]().
Referenced by bladeModel::bladeModel(), TableBase< Type >::check(), interpolationTable< Type >::check(), primitiveMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceWeights(), TableBase< Type >::checkMaxBounds(), edgeCollapser::checkMeshQuality(), TableBase< Type >::checkMinBounds(), interpolation2DTable< Type >::checkOrder(), polyMeshGeometry::checkVolRatio(), TableBase< Type >::convertTimeBase(), meshRefinement::createZoneBaffles(), Distribution< Type >::cumulativeNormalised(), Distribution< Type >::cumulativeRaw(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), primitiveMeshTools::faceConcavity(), patchProbes::findElements(), mappedPatchBase::findSamples(), interpolation2DTable< Type >::interpolation2DTable(), TableBase< Type >::interpolator(), cell::labels(), solutionControl::maxTypeResidual(), distribution::median(), Distribution< Type >::median(), meshRefinement::mergeBaffles(), distribution::normalised(), Distribution< Type >::normalised(), distribution::normalisedShifted(), procLess::operator()(), listPlusEqOp< T >::operator()(), UList< T >::greater::operator()(), interpolation2DTable< Type >::operator()(), interpolationTable< Type >::operator()(), Distribution< Type >::operator=(), ParticleCollector< CloudType >::ParticleCollector(), SprayCloud< CloudType >::penetration(), BSpline::position(), CatmullRomSpline::position(), polyLine::position(), interpolationTable< Type >::rateOfChange(), distribution::raw(), Distribution< Type >::raw(), tabulated6DoFAcceleration::read(), tabulated6DoFMotion::read(), ITstream::rewind(), decompositionMethod::setConstraints(), primitiveEntry::startLineNumber(), Distribution< Type >::write(), pairPotential::writeEnergyAndForceTables(), residuals::writeResidual(), TableBase< Type >::x(), interpolation2DTable< Type >::Xi(), and RaviPetersen::~RaviPetersen().
const T & first () const inline
Return first element of the list.
Definition at line 121 of file UListI.H.
References UList< T >::operator[]().
T & last () inline
Return the last element of the list.
Definition at line 128 of file UListI.H.
References UList< T >::operator[](), and UList< T >::size().
Referenced by masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), polyLine::calcParam(), triSurface::checkEdges(), primitiveMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceAngles(), TableBase< Type >::checkMaxBounds(), edgeCollapser::checkMeshQuality(), TableBase< Type >::checkMinBounds(), MeshedSurface< Face >::checkZones(), surfMesh::checkZones(), processorLduInterface::compressedReceive(), processorLduInterface::compressedSend(), face::edges(), edgeSurface::edgeSurface(), primitiveEntry::endLineNumber(), primitiveMeshTools::faceConcavity(), Time::findClosestTime(), searchableBox::findLineAll(), globalIndex::gather(), FreeStream< CloudType >::inflow(), distribution::insertMissingKeys(), linearInterpolationWeights::integrationWeights(), lduPrimitiveMesh::lduPrimitiveMesh(), List< T >::List(), solutionControl::maxTypeResidual(), procLess::operator()(), UList< T >::greater::operator()(), Foam::operator<<(), SprayCloud< CloudType >::penetration(), BSpline::position(), CatmullRomSpline::position(), polyLine::position(), GAMGAgglomeration::procAgglomerateRestrictAddressing(), ITstream::read(), Time::setControls(), surfaceFeatures::setFromStatus(), hexRef8::setInstance(), Reaction< ReactionThermo >::setLRhs(), createShellMesh::setRefinement(), addPatchCellLayer::setRefinement(), globalIndex::size(), TableBase< Type >::value(), and RaviPetersen::~RaviPetersen().
const T & last () const inline
Return the last element of the list.
Definition at line 135 of file UListI.H.
References UList< T >::operator[](), and UList< T >::size().
void checkStart (const label start) const inline
Check start is within valid range (0 ... size-1).
Definition at line 72 of file UListI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::max().
Referenced by UList< T >::greater::operator()(), and SubList< T >::SubList().
void checkSize (const label size) const inline
Check size is within valid range (0 ... size).
Definition at line 84 of file UListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by UList< T >::greater::operator()(), and SubList< T >::SubList().
void checkIndex (const label i) const inline
Check index i is within valid range (0 ... size-1).
Definition at line 96 of file UListI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by UList< T >::greater::operator()(), and UList< T >::operator[]().
void shallowCopy (const UList< T > & a) inline
Copy the pointer held by the given UList.
Definition at line 156 of file UListI.H.
Referenced by UList< T >::greater::operator()().
void deepCopy (const UList< T > & a)
Copy elements of the given UList.
Definition at line 37 of file UList.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, List_ACCESS, List_CONST_ACCESS, List_ELEM, List_END_FOR_ALL, List_FOR_ALL, and T.
Referenced by UPstream::allToAll(), UList< T >::greater::operator()(), and globalIndex::scatter().
void writeEntry (Ostream & os) const
Write the UList as a dictionary entry.
Definition at line 35 of file UListIO.C.
Referenced by UList< T >::greater::operator()(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), ensightPart::writeData(), faceZone::writeDict(), and Field< Type >::writeEntry().
void writeEntry (const word & keyword, Ostream & os) const
Write the UList as a dictionary entry with keyword.
Definition at line 54 of file UListIO.C.
References LList< SLListBase, T >::begin(), UList< T >::data(), Foam::dynamicCast(), LList< SLListBase, T >::end(), Foam::endl(), Foam::exit(), IOstream::fatalCheck(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, IOstream::format(), token::info(), token::isCompound(), token::isLabel(), token::isPunctuation(), token::labelToken(), Foam::nl, Foam::operator>>(), token::pToken(), Istream::putBack(), Istream::read(), Istream::readBeginList(), Istream::readEndList(), s(), List< T >::size(), SLListBase::size(), UList< T >::size(), T, List< T >::transfer(), token::transferCompoundToken(), and Ostream::writeKeyword().
T & operator[] (const label i) inline
Return element of UList.
Definition at line 167 of file UListI.H.
References UList< T >::checkIndex().
Referenced by labelRanges::add(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::append(), triSurfaceMesh::boundingSpheres(), face::centre(), face::collapse(), cellClassification::fillHangingCells(), cellClassification::fillRegionEdges(), cellClassification::fillRegionPoints(), UList< T >::first(), triSurfaceMesh::getRegion(), distributedTriSurfaceMesh::getRegion(), cellClassification::growSurface(), hashedWordList::hashedWordList(), sortLabelledTri::indices(), interpolationLookUpTable< Type >::interpolationLookUpTable(), gradingDescriptors::inv(), UList< T >::last(), List< T >::List(), interpolationLookUpTable< Type >::lookUp(), thirdBodyEfficiencies::M(), edgeIntersections::merge(), mixture::mixture(), face::nextLabel(), face::normal(), UList< T >::greater::operator()(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::operator()(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::operator()(), List< T >::operator=(), PackedList< nBits >::operator=(), hashedWordList::operator[](), interpolationLookUpTable< Type >::operator[](), cellShape::points(), face::points(), face::prevLabel(), probes::probe(), ITstream::read(), labelRanges::remove(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::remove(), PackedList< nBits >::resize(), SortableList< T >::reverseSort(), scalarRanges::selected(), timeSelector::selected(), PackedList< nBits >::setCapacity(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize(), SortableList< T >::sort(), sortLabelledTri::sortLabelledTri(), cellClassification::trimCutCells(), thirdBodyEfficiencies::write(), primitiveEntry::write(), and triSurface::writeStats().
const T & operator[] (const label i) const inline
Return element of constant UList.
Note that the bool specialization adds lazy evaluation so reading an out-of-range element returns false without any ill-effects
Definition at line 196 of file UListI.H.
References UList< T >::checkIndex().
operator const Foam::List< T > & () const inline
Allow cast to a const List<T>&.
Definition at line 206 of file UListI.H.
void operator= (const T & t)
Assignment of all entries to the given value.
Definition at line 70 of file UList.C.
References List_ACCESS, List_ELEM, List_END_FOR_ALL, List_FOR_ALL, and T.
void operator= (const zero)
Assignment of all entries to zero.
Definition at line 80 of file UList.C.
References List_ACCESS, List_ELEM, List_END_FOR_ALL, List_FOR_ALL, T, and Foam::Zero.
Foam::UList< T >::iterator begin () inline
Return an iterator to begin traversing the UList.
Definition at line 216 of file UListI.H.
Referenced by lduMatrix::Amul(), TDILUPreconditioner< Type, DType, LUType >::calcInvD(), DICPreconditioner::calcReciprocalD(), DILUPreconditioner::calcReciprocalD(), mapDistribute::compact(), processorLduInterface::compressedReceive(), processorLduInterface::compressedSend(), triSurfaceTools::delaunay2D(), mapDistribute::distribute(), globalIndex::gather(), Pstream::gatherList(), lduMatrix::H(), lduMatrix::H1(), Pstream::listCombineGather(), Pstream::listCombineScatter(), LUscalarMatrix::LUscalarMatrix(), UList< T >::operator<(), noPreconditioner::precondition(), DICPreconditioner::precondition(), DILUPreconditioner::precondition(), diagonalPreconditioner::precondition(), FDICPreconditioner::precondition(), DILUPreconditioner::preconditionT(), ITstream::print(), processorLduInterface::receive(), lduMatrix::residual(), globalIndex::scatter(), processorLduInterface::send(), Foam::shuffle(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), DILUSmoother::smooth(), DICSmoother::smooth(), FDICSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), PBiCICG< Type, DType, LUType >::solve(), PBiCCCG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCG::solve(), PCG::solve(), Foam::sort(), Foam::stableSort(), lduMatrix::sumA(), TGaussSeidelSmoother< Type, DType, LUType >::TGaussSeidelSmoother(), lduMatrix::Tmul(), fft::transform(), ensightBinaryStream::write(), and UOPstream::~UOPstream().
Foam::UList< T >::iterator end () inline
Return an iterator to end traversing the UList.
Definition at line 237 of file UListI.H.
Referenced by twoDPointCorrector::correctPoints(), triFace::edges(), Foam::meshTools::edgeToCutDir(), directionInfo::edgeToFaceIndex(), probes::elements(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::erase(), Foam::meshTools::getParallelEdges(), UList< T >::operator<(), Foam::shuffle(), Foam::sort(), extendedEdgeMesh::sortPointsAndEdges(), Foam::stableSort(), and GTSsurfaceFormat< Face >::write().
Foam::UList< T >::const_iterator cbegin () const inline
Return const_iterator to begin traversing the constant UList.
Definition at line 230 of file UListI.H.
Foam::UList< T >::const_iterator cend () const inline
Return const_iterator to end traversing the constant UList.
Definition at line 251 of file UListI.H.
Foam::UList< T >::const_iterator begin () const inline
Return const_iterator to begin traversing the constant UList.
Definition at line 223 of file UListI.H.
Foam::UList< T >::const_iterator end () const inline
Return const_iterator to end traversing the constant UList.
Definition at line 244 of file UListI.H.
Foam::UList< T >::iterator rbegin () inline
Return reverse_iterator to begin reverse traversing the UList.
Definition at line 258 of file UListI.H.
Referenced by ITstream::print().
Foam::UList< T >::iterator rend () inline
Return reverse_iterator to end reverse traversing the UList.
Definition at line 279 of file UListI.H.
Foam::UList< T >::const_iterator crbegin () const inline
Return const_reverse_iterator to begin reverse traversing the UList.
Definition at line 272 of file UListI.H.
Foam::UList< T >::const_iterator crend () const inline
Return const_reverse_iterator to end reverse traversing the UList.
Definition at line 293 of file UListI.H.
Foam::UList< T >::const_iterator rbegin () const inline
Return const_reverse_iterator to begin reverse traversing the UList.
Definition at line 265 of file UListI.H.
Foam::UList< T >::const_iterator rend () const inline
Return const_reverse_iterator to end reverse traversing the UList.
Definition at line 286 of file UListI.H.
Foam::label size () const inline
Return the number of elements in the UList.
Definition at line 299 of file UListI.H.
Referenced by isoSurface::adaptPatchFields(), fvMatrix< Type >::addToInternalField(), MeshedSurface< Face >::addZones(), pairGAMGAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), List< T >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::append(), Field< Type >::autoMap(), fvPatchField< Type >::autoMap(), coupledPolyPatch::calcFaceTol(), edgeCollapser::checkMeshQuality(), GAMGAgglomeration::checkRestriction(), Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), meshRefinement::collectAndPrint(), GAMGAgglomeration::compactLevels(), Foam::ComplexField(), processorLduInterface::compressedReceive(), processorLduInterface::compressedSend(), Keyed< T >::createList(), directFvPatchFieldMapper::directFvPatchFieldMapper(), directPointPatchFieldMapper::directPointPatchFieldMapper(), Foam::duplicateOrder(), HashTable< T, Key, Hash >::erase(), Pstream::exchange(), regionSizeDistribution::extractData(), FaceCellWave< Type, TrackingData >::FaceCellWave(), lduMatrix::faceH(), LduMatrix< Type, DType, LUType >::faceH(), Foam::facePointN(), UList< T >::fcIndex(), FixedList< T, Size >::FixedList(), globalIndex::gather(), Foam::gAverage(), meshRefinement::gAverage(), coupledPolyPatch::getAnchorPoints(), Foam::Im(), Foam::ImComplexField(), Foam::inplaceSubset(), cyclicAMIGAMGInterface::internalFieldTransfer(), cyclicACMIGAMGInterface::internalFieldTransfer(), regionCoupledFvPatch::internalFieldTransfer(), regionCoupledWallFvPatch::internalFieldTransfer(), surfaceInterpolationScheme< Type >::interpolate(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), Foam::inv(), cell::labels(), UList< T >::last(), lduPrimitiveMesh::lduPrimitiveMesh(), LduMatrix< Type, DType, LUType >::lower(), Foam::mag(), Foam::magSqr(), Field< Type >::map(), Foam::matchPoints(), Foam::max(), Foam::mergePoints(), MeshedSurface< Face >::MeshedSurface(), LduMatrix< Type, DType, LUType >::negSumDiag(), lduMatrix::negSumDiag(), procLess::operator()(), UList< T >::greater::operator()(), UIndirectList< T >::operator=(), BiIndirectList< T >::operator=(), PackedBoolList::operator=(), FixedList< T, Size >::operator=(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::operator=(), PackedList< nBits >::operator=(), directFieldMapper::patchFieldSubset(), Polynomial< PolySize >::Polynomial(), Foam::pow(), UList< T >::rcIndex(), Foam::Re(), OBJsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), Foam::ReComplexField(), fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvVolumeField(), Foam::ReImSum(), UnsortedMeshedSurface< Face >::remapFaces(), cuttingPlane::remapFaces(), MeshedSurface< Face >::remapFaces(), ensightPart::renumber(), UPtrList< T >::reorder(), PtrList< T >::reorder(), Foam::reverse(), CompactListList< T, Container >::setSize(), UnsortedMeshedSurface< Face >::setZones(), directFieldMapper::size(), directFvPatchFieldMapper::size(), directPointPatchFieldMapper::size(), Foam::sortedOrder(), Foam::sqr(), Foam::stabilise(), Foam::subset(), fvMatrix< Type >::subtractFromInternalField(), Foam::sumCmptProd(), LduMatrix< Type, DType, LUType >::sumDiag(), lduMatrix::sumDiag(), LduMatrix< Type, DType, LUType >::sumMagOffDiag(), lduMatrix::sumMagOffDiag(), Foam::sumProd(), Foam::sumSqr(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), syncTools::syncBoundaryFaceList(), meshRefinement::testSyncBoundaryFaceList(), lduMesh::thisDb(), Foam::transformList(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), sampledPatch::update(), LduMatrix< Type, DType, LUType >::upper(), ensightPartFaces::writeConnectivity(), VTKedgeFormat::writeEdges(), UList< T >::writeEntry(), ensightPart::writeField(), WRLsurfaceFormatCore::writeHeader(), OFSsurfaceFormatCore::writeHeader(), AC3DsurfaceFormatCore::writeHeader(), coupledPolyPatch::writeOBJ(), Foam::meshTools::writeOBJ(), ensightPart::writeScalarField(), VTKsurfaceFormatCore::writeTail(), ensightPart::writeVectorField(), and ensightPartCells::~ensightPartCells().
Foam::label max_size () const inline
Return size of the largest possible UList.
Definition at line 306 of file UListI.H.
References Foam::labelMax.
bool empty () const inline
Return true if the UList is empty (ie, size() is zero).
Definition at line 313 of file UListI.H.
Referenced by DynamicID< pointZoneMesh >::active(), labelRanges::add(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::bb(), indexedOctree< Foam::treeDataFace >::bb(), block::boundaryPatches(), boundBox::boundBox(), cellVolumeWeightMethod::calculateAddressing(), cellMapper::cellMapper(), block::cells(), blockMesh::cells(), triSurface::checkEdges(), edgeCollapser::checkMeshQuality(), primitiveMesh::checkPoints(), labelRanges::const_iterator::const_iterator(), boundBox::contains(), boundBox::containsAny(), dynamicCode::copyOrCreateFiles(), hexCellLooper::cut(), fvSchemes::d2dt2Scheme(), fvSchemes::ddtScheme(), fvSchemes::divScheme(), edgeSurface::edgeSurface(), primitiveEntry::endLineNumber(), faceMapper::faceMapper(), searchableSurfacesQueries::findAllIntersections(), Foam::findEtcFiles(), coordinateSystems::findIndex(), ZoneMesh< ZoneType, MeshType >::findIndex(), polyBoundaryMesh::findIndex(), triSurfaceRegionSearch::findNearest(), searchableSurfacesQueries::findNearest(), fvSchemes::gradScheme(), Distribution< Type >::index(), DynamicID< pointZoneMesh >::index(), cyclicACMIPolyPatch::initPatchFaceAreas(), fvSchemes::interpolationScheme(), intersectedSurface::intersectedSurface(), fvSchemes::laplacianScheme(), meshTriangulation::meshTriangulation(), cellCuts::nonAnchorPoints(), Distribution< Type >::normalised(), dlLibraryTable::open(), listPlusEqOp< T >::operator()(), cellToCellStencil::unionEqOp::operator()(), cellToFaceStencil::unionEqOp::operator()(), Foam::operator<<(), triSurfaceMesh::overlaps(), coupledPolyPatch::parallel(), ParticleErosion< CloudType >::ParticleErosion(), blockMesh::patches(), patchInteractionDataList::patchInteractionDataList(), boundaryMesh::patchNames(), PatchPostProcessing< CloudType >::PatchPostProcessing(), polyBoundaryMesh::patchSet(), pointMapper::pointMapper(), block::points(), blockMesh::points(), polynomialFunction::polynomialFunction(), Distribution< Type >::raw(), boundaryMesh::readTriSurface(), triSurfaceMesh::regions(), labelRanges::remove(), timeSelector::select0(), Reaction< ReactionThermo >::setLRhs(), combineFaces::setUnrefinement(), fvSchemes::snGradScheme(), primitiveEntry::startLineNumber(), surfaceIntersection::surfaceIntersection(), particle< Type >::trackToFace(), treeBoundBox::treeBoundBox(), MeshedSurface< Face >::triangulate(), sampledPlane::update(), and walkPatch::walkPatch().
void swap (UList< T > & a)
Swap two ULists of the same type in constant time.
Definition at line 92 of file UList.C.
References Foam::Swap().
bool operator== (const UList< T > & a) const
Equality operation on ULists of the same type.
Returns true when the ULists are element-wise equal (using UList::value_type::operator==). Takes linear time.
Definition at line 154 of file UList.C.
References Foam::equal(), List_CONST_ACCESS, List_ELEM, List_END_FOR_ALL, List_FOR_ALL, and T.
bool operator!= (const UList< T > & a) const
The opposite of the equality operation. Takes linear time.
Definition at line 175 of file UList.C.
References Foam::operator==().
bool operator< (const UList< T > & a) const
Compare two ULists lexicographically. Takes linear time.
Definition at line 182 of file UList.C.
References UList< T >::begin(), and UList< T >::end().
bool operator> (const UList< T > & a) const
Compare two ULists lexicographically. Takes linear time.
Definition at line 213 of file UList.C.
References UList< T >::operator.
bool operator<= (const UList< T > & a) const
Return true if !(a > b). Takes linear time.
Definition at line 220 of file UList.C.
References Foam::operator>().
bool operator>= (const UList< T > & a) const
Return true if !(a < b). Takes linear time.
Definition at line 227 of file UList.C.
References Foam::operator<().
const bool & operator[] (const label i) const inline
Definition at line 180 of file UListI.H.
Friends And Related Function Documentation
friend class List< T > friend
Declare friendship with the List class.
Definition at line 100 of file UList.H.
friend class SubList< T > friend
Declare friendship with the SubList class.
Definition at line 103 of file UList.H.
Ostream& operator (Ostream & , const UList< T > &) friend
Referenced by booleanSurface::booleanSurface(), interpolationTable< Type >::check(), intersectedSurface::intersectedSurface(), isoSurface::isoSurface(), isoSurfaceCell::isoSurfaceCell(), meshTriangulation::meshTriangulation(), interpolationTable< Type >::operator()(), hashedWordList::operator=(), UList< T >::operator>(), interpolationTable< Type >::operator[](), interpolationTable< Type >::rateOfChange(), and interpolation2DTable< Type >::Xi().
Istream& operator>> (Istream & , UList< T > &) friend
Read UList contents from Istream. Requires size to have been set.
before.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/Lists/UList/UList.H
src/OpenFOAM/containers/Lists/UList/UList.C
src/OpenFOAM/containers/Lists/UList/UListI.H
src/OpenFOAM/containers/Lists/UList/UListIO.C