OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UniformDimensionedField< Type > Class Template Reference
Dimensioned<Type> registered with the database as a registered IOobject which has the functionality of a uniform field and allows values from the top-level code to be passed to boundary conditions etc.
Public Member Functions
TypeName ("UniformDimensionedField")
Runtime type information.
UniformDimensionedField (const IOobject &, const dimensioned< Type > &)
Construct from components. Either reads or uses supplied value.
UniformDimensionedField (const UniformDimensionedField< Type > &)
Construct as copy.
UniformDimensionedField (const IOobject &)
Construct from Istream.
virtual ~UniformDimensionedField ()
Destructor.
virtual const word & name () const
Name function provided to resolve the ambiguity between the.
bool writeData (Ostream &) const
Pure virtual writaData function.
void operator= (const UniformDimensionedField< Type > &)
void operator= (const dimensioned< Type > &)
Type operator[] (const label) const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dimensioned< Type >
dimensioned (const word &, const dimensionSet &, const Type)
Construct given a name, a value and its dimensionSet.
dimensioned (const word &, const dimensioned< Type > &)
Construct from a dimensioned<Type> changing the name.
dimensioned (const Type &t)
Construct given a value (creates dimensionless value).
dimensioned (Istream &)
Construct from Istream.
dimensioned (const word &, Istream &)
Construct from an Istream with a given name.
dimensioned (const word &, const dimensionSet &, Istream &)
Construct from an Istream with a given name and dimensions.
dimensioned (const word &, const dimensionSet &, const dictionary &)
Construct from dictionary lookup with a given name and dimensions.
dimensioned ()
Null constructor.
const word & name () const
Return const reference to name.
word & name ()
Return non-const reference to name.
const dimensionSet & dimensions () const
Return const reference to dimensions.
dimensionSet & dimensions ()
Return non-const reference to dimensions.
const Type & value () const
Return const reference to value.
Type & value ()
Return non-const reference to value.
dimensioned< cmptType > component (const direction) const
Return a component as a dimensioned<cmptType>
void replace (const direction, const dimensioned< cmptType > &)
Return a component with a dimensioned<cmptType>
dimensioned< Type > T () const
Return transpose.
void read (const dictionary &)
Update the value of dimensioned<Type>
bool readIfPresent (const dictionary &)
Update the value of dimensioned<Type> if found in the dictionary.
Istream & read (Istream &is, const dictionary &)
Read value from stream and units from dictionary.
Istream & read (Istream &is, const HashTable< dimensionedScalar > &)
Read value from stream and units from table.
Istream & read (Istream &is)
Read value from stream and units from system table.
dimensioned< cmptType > operator[] (const direction) const
Return a component as a dimensioned<cmptType>
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const scalar)
void operator/= (const scalar)
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from dimensioned< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dimensioned< Type >
static dimensioned< Type > lookupOrDefault (const word &, const dictionary &, const dimensionSet &dims=dimless, const Type &defaultValue=pTraits< Type >::zero)
Construct from dictionary, with default dimensions and value.
static dimensioned< Type > lookupOrDefault (const word &, const dictionary &, const Type &defaultValue=pTraits< Type >::zero)
Construct from dictionary dimensionless with value.
static dimensioned< Type > lookupOrAddToDict (const word &, dictionary &, const dimensionSet &dims=dimless, const Type &defaultValue=pTraits< Type >::zero)
Construct from dictionary, with default value.
static dimensioned< Type > lookupOrAddToDict (const word &, dictionary &, const Type &defaultValue=pTraits< Type >::zero)
Construct from dictionary, dimensionless with default value.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Type>
class Foam::UniformDimensionedField< Type >
Dimensioned<Type> registered with the database as a registered IOobject which has the functionality of a uniform field and allows values from the top-level code to be passed to boundary conditions etc.
Source files
UniformDimensionedField.H
UniformDimensionedField.C
Definition at line 52 of file UniformDimensionedField.H.
Constructor & Destructor Documentation
UniformDimensionedField (const IOobject & io, const dimensioned< Type > & dt)
Construct from components. Either reads or uses supplied value.
Definition at line 32 of file UniformDimensionedField.C.
References dict, dictionary::lookup(), and IOobject::readOpt().
Referenced by UniformDimensionedField< Type >::UniformDimensionedField().
UniformDimensionedField (const UniformDimensionedField< Type > & rdt)
Construct as copy.
Definition at line 61 of file UniformDimensionedField.C.
References UniformDimensionedField< Type >::UniformDimensionedField().
UniformDimensionedField (const IOobject & io)
Construct from Istream.
Definition at line 72 of file UniformDimensionedField.C.
References dict, and dictionary::lookup().
~UniformDimensionedField () virtual
Destructor.
Definition at line 90 of file UniformDimensionedField.C.
Member Function Documentation
TypeName ("UniformDimensionedField< Type >")
Runtime type information.
virtual const word& name () const inline virtual
Name function provided to resolve the ambiguity between the.
name functions in regIOobject and dimensioned<Type>
Definition at line 84 of file UniformDimensionedField.H.
bool writeData (Ostream &) const virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 97 of file UniformDimensionedField.C.
References IOstream::good(), Foam::nl, Ostream::write(), and Ostream::writeKeyword().
void operator= (const UniformDimensionedField< Type > & rhs)
Definition at line 114 of file UniformDimensionedField.C.
void operator= (const dimensioned< Type > & rhs)
Definition at line 124 of file UniformDimensionedField.C.
Type operator[] (const label) const inline
Definition at line 97 of file UniformDimensionedField.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/UniformDimensionedFields/UniformDimensionedField.H
src/OpenFOAM/fields/UniformDimensionedFields/UniformDimensionedField.C