OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
virtualMassModel Class Reference abstract
Public Member Functions
TypeName ("virtualMassModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, virtualMassModel, dictionary,(const dictionary &dict, const phasePair &pair, const bool registerObject),(dict, pair, registerObject))
virtualMassModel (const dictionary &dict, const phasePair &pair, const bool registerObject)
Construct from a dictionary and a phase pair.
virtual ~virtualMassModel ()
Destructor.
virtual tmp< volScalarField > Cvm () const =0
Return the virtual mass coefficient.
virtual tmp< volScalarField > Ki () const
Return the phase-intensive virtual mass coefficient Ki.
virtual tmp< volScalarField > K () const
Return the virtual mass coefficient K.
virtual tmp< surfaceScalarField > Kf () const
Return the virtual mass coefficient Kf.
bool writeData (Ostream &os) const
Pure virtual writaData function.
TypeName ("virtualMassModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, virtualMassModel, dictionary,(const dictionary &dict, const phasePair &pair, const bool registerObject),(dict, pair, registerObject))
virtualMassModel (const dictionary &dict, const phasePair &pair, const bool registerObject)
Construct from a dictionary and a phase pair.
virtual ~virtualMassModel ()
Destructor.
virtual tmp< volScalarField > Cvm () const =0
Return the virtual mass coefficient.
virtual tmp< volScalarField > Ki () const
Return the phase-intensive virtual mass coefficient Ki.
virtual tmp< volScalarField > K () const
Return the virtual mass coefficient K.
virtual tmp< surfaceScalarField > Kf () const
Return the virtual mass coefficient Kf.
bool writeData (Ostream &os) const
Pure virtual writaData function.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static autoPtr< virtualMassModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< virtualMassModel > New (const dictionary &dict, const phasePair &pair)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes
static const dimensionSet dimK
Coefficient dimensions.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Attributes
const phasePair & pair_
Phase pair.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Source files
virtualMassModel.H
virtualMassModel.C
newVirtualMassModel.C
Source files
virtualMassModel.H
virtualMassModel.C
newVirtualMassModel.C
Definition at line 52 of file virtualMassModel.H.
Constructor & Destructor Documentation
virtualMassModel (const dictionary & dict, const phasePair & pair, const bool registerObject)
Construct from a dictionary and a phase pair.
virtual ~virtualMassModel () virtual
Destructor.
virtualMassModel (const dictionary & dict, const phasePair & pair, const bool registerObject)
Construct from a dictionary and a phase pair.
virtual ~virtualMassModel () virtual
Destructor.
Member Function Documentation
TypeName ("virtualMassModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , virtualMassModel , dictionary , (const dictionary &dict, const phasePair &pair, const bool registerObject) , (dict, pair, registerObject))
static autoPtr<virtualMassModel> New (const dictionary & dict, const phasePair & pair) static
virtual tmp<volScalarField> Cvm () const pure virtual
Return the virtual mass coefficient.
Implemented in Lamb, Lamb, constantVirtualMassCoefficient, constantVirtualMassCoefficient, noVirtualMass, and noVirtualMass.
Referenced by continuousGasKEpsilon< BasicTurbulenceModel >::correctNut(), continuousGasKEpsilon< BasicTurbulenceModel >::rhoEff(), and mixtureKEpsilon< BasicTurbulenceModel >::rhogEff().
virtual tmp<volScalarField> Ki () const virtual
Return the phase-intensive virtual mass coefficient Ki.
used in the momentum equation ddt(alpha1*rho1*U1) + ... = ... alphad*K*(DU1_Dt - DU2_Dt) ddt(alpha2*rho2*U2) + ... = ... alphad*K*(DU1_Dt - DU2_Dt)
virtual tmp<volScalarField> K () const virtual
Return the virtual mass coefficient K.
used in the momentum equation ddt(alpha1*rho1*U1) + ... = ... K*(DU1_Dt - DU2_Dt) ddt(alpha2*rho2*U2) + ... = ... K*(DU1_Dt - DU2_Dt)
Reimplemented in noVirtualMass, and noVirtualMass.
virtual tmp<surfaceScalarField> Kf () const virtual
Return the virtual mass coefficient Kf.
used in the face-momentum equations
bool writeData (Ostream &) const virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
TypeName ("virtualMassModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , virtualMassModel , dictionary , (const dictionary &dict, const phasePair &pair, const bool registerObject) , (dict, pair, registerObject))
static autoPtr<virtualMassModel> New (const dictionary & dict, const phasePair & pair) static
virtual tmp<volScalarField> Cvm () const pure virtual
Return the virtual mass coefficient.
Implemented in Lamb, Lamb, constantVirtualMassCoefficient, constantVirtualMassCoefficient, noVirtualMass, and noVirtualMass.
virtual tmp<volScalarField> Ki () const virtual
Return the phase-intensive virtual mass coefficient Ki.
used in the momentum equation ddt(alpha1*rho1*U1) + ... = ... alphad*K*(DU1_Dt - DU2_Dt) ddt(alpha2*rho2*U2) + ... = ... alphad*K*(DU1_Dt - DU2_Dt)
virtual tmp<volScalarField> K () const virtual
Return the virtual mass coefficient K.
used in the momentum equation ddt(alpha1*rho1*U1) + ... = ... K*(DU1_Dt - DU2_Dt) ddt(alpha2*rho2*U2) + ... = ... K*(DU1_Dt - DU2_Dt)
Reimplemented in noVirtualMass, and noVirtualMass.
virtual tmp<surfaceScalarField> Kf () const virtual
Return the virtual mass coefficient Kf.
used in the face-momentum equations
bool writeData (Ostream &) const virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Member Data Documentation
const phasePair & pair_ protected
Phase pair.
Definition at line 61 of file virtualMassModel.H.
static const dimensionSet dimK static
Coefficient dimensions.
Definition at line 89 of file virtualMassModel.H.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/interfacialModels/virtualMassModels/virtualMassModel/virtualMassModel.H