OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA)&mesh.Sf())+fvc::interpolate(rho *rAU)*fvc::ddtCorr(U, phi))
surfaceScalarField phig ((mixture.surfaceTensionForce()-ghf *fvc::snGrad(rho))*rAUf *mesh.magSf())
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField()-(mesh.Sf().boundaryField()&U.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
PtrList< fvScalarMatrix > p_rghEqnComps (mixture.phases().size())
forAllConstIter (PtrDictionary< phaseModel >, mixture.phases(), phase)
volScalarField p_rgh_0 (p_rgh)
solve (p_rghEqnComp+p_rghEqnIncomp, mesh.solver(p_rgh.select(pimple.finalInnerIter())))
forAllIter (PtrDictionary< phaseModel >, mixture.phases(), phase)
U correctBoundaryConditions ()
mixture correctRho (p_rgh-p_rgh_0)
Variables
HbyA = rAU*UEqn.H()
phiHbyA = phig
label phasei = 0
tmp< fvScalarMatrix > p_rghEqnComp
phi = phiHbyA + p_rghEqnIncomp.flux()
U
p = max(p_rgh + mixture.rho()*gh, pMin)
rho = mixture.rho()
K = 0.5*magSqr(U)
Function Documentation
surfaceScalarField rAUf ("rAUf" , fvc:: interpolaterAU)
volVectorField HbyA ("HbyA" , U)
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA)&mesh.Sf())+fvc::interpolate(rho *rAU)*fvc::ddtCorr(U, phi))
surfaceScalarField phig ((mixture.surfaceTensionForce()-ghf *fvc::snGrad(rho))*rAUf *mesh.magSf())
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField()-(mesh.Sf().boundaryField()&U.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
PtrList<fvScalarMatrix> p_rghEqnComps (mixture. phases).size()
Referenced by forAllConstIter(), and forAllIter().
forAllConstIter (PtrDictionary< phaseModel > , mixture. phases(), phase)
Definition at line 39 of file pEqn.H.
References Foam::correction(), Foam::fvc::ddt(), Foam::fvc::div(), p_rgh, p_rghEqnComps(), phi, rho, Foam::fvc::Sp(), and thermo.
volScalarField p_rgh_0 (p_rgh)
solve (p_rghEqnComp+ p_rghEqnIncomp, mesh. solverp_rgh.select(pimple.finalInnerIter()))
forAllIter (PtrDictionary< phaseModel > , mixture. phases(), phase)
Definition at line 113 of file pEqn.H.
References p_rgh, p_rghEqnComps(), phasei, and Foam::pos().
Referenced by moleculeCloud::applyConstraintsAndThermostats(), genericPointPatchField< Type >::autoMap(), genericFvPatchField< Type >::autoMap(), Cloud< ParticleType >::autoMap(), KinematicCloud< CloudType >::buildCellOccupancy(), Stochastic< CloudType >::calculate(), moleculeCloud::calculateForce(), meshObject::clear(), meshObject::clearUpto(), SuppressionCollision< CloudType >::collide(), ORourkeCollision< CloudType >::collide(), dictionary::dictionary(), for(), if(), objectRegistry::lookupClass(), Foam::mapClouds(), Foam::MapLagrangianFields(), Foam::MapVolFields(), Cloud< ParticleType >::move(), meshObject::movePoints(), mapDistribute::transformPosition::operator()(), probes::prepare(), functionObjectList::read(), STARCD::readBoundary(), wallBoundedStreamLineParticle::readFields(), solidParticle::readFields(), MPPICParcel< ParcelType >::readFields(), streamLineParticle::readFields(), CollidingParcel< ParcelType >::readFields(), DSMCParcel< ParcelType >::readFields(), wallBoundedParticle::readFields(), molecule::readFields(), ReactingParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readFields(), particle< Type >::readFields(), KinematicParcel< ParcelType >::readFields(), dynamicRefineFvMesh::refine(), genericPointPatchField< Type >::rmap(), genericFvPatchField< Type >::rmap(), UnsortedMeshedSurface< Face >::sortedZones(), solutionControl::storePrevIter(), Foam::transformList(), dynamicRefineFvMesh::unrefine(), meshObject::updateMesh(), solution::upgradeSolverDict(), regionSizeDistribution::write(), CallbackRegistry< CallbackType >::~CallbackRegistry(), and undoableMeshCutter::~undoableMeshCutter().
U correctBoundaryConditions ()
mixture correctRho (p_rgh- p_rgh_0)
Variable Documentation
HbyA = rAU*UEqn.H()
Definition at line 6 of file pEqn.H.
phiHbyA = phig
Definition at line 23 of file pEqn.H.
phasei = 0
Definition at line 37 of file pEqn.H.
Referenced by CompositionModel< CloudType >::componentNames(), CompositionModel< CloudType >::Cp(), for(), forAllIter(), CompositionModel< CloudType >::H(), CompositionModel< CloudType >::Hc(), CompositionModel< CloudType >::Hs(), CompositionModel< CloudType >::L(), Foam::MULES::limitSum(), CompositionModel< CloudType >::localId(), CompositionModel< CloudType >::localToCarrierId(), CompositionModel< CloudType >::X(), and CompositionModel< CloudType >::Y0().
tmp<fvScalarMatrix> p_rghEqnComp
Initial value:
{
        fvScalarMatrix p_rghEqnIncomp
        (
            fvc::div(phiHbyA)
          - fvm::laplacian(rAUf, p_rgh)
        )
Definition at line 64 of file pEqn.H.
phi = phiHbyA + p_rghEqnIncomp.flux()
Definition at line 124 of file pEqn.H.
U
Initial value:
= HbyA
              + rAU*fvc::reconstruct((phig + p_rghEqnIncomp.flux())/rAUf)
Definition at line 126 of file pEqn.H.
p = max(p_rgh + mixture.rho()*gh, pMin)
Definition at line 132 of file pEqn.H.
rho = mixture.rho()
Definition at line 136 of file pEqn.H.
K = 0.5*magSqr(U)
Definition at line 138 of file pEqn.H.