OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
WallModel< CloudType > Class Template Reference abstract
Templated wall interaction class.
Public Member Functions
TypeName ("wallModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, WallModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
WallModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~WallModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
CloudType & owner ()
Return non-const access to the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
virtual scalar pREff (const typename CloudType::parcelType &p) const =0
Return the effective radius for a particle for the model.
virtual bool controlsTimestep () const =0
Whether the WallModel has a timestep limit that will.
virtual label nSubCycles () const =0
For WallModels that control the timestep, calculate the.
virtual void evaluateWall (typename CloudType::parcelType &p, const List< point > &flatSitePoints, const List< WallSiteData< vector >> &flatSiteData, const List< point > &sharpSitePoints, const List< WallSiteData< vector >> &sharpSiteData) const =0
Calculate the wall interaction for a parcel.
Static Public Member Functions
static autoPtr< WallModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::WallModel< CloudType >
Templated wall interaction class.
Source files
WallModel.H
WallModel.C
WallModelNew.C
Definition at line 51 of file PairCollision.H.
Constructor & Destructor Documentation
WallModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from components.
Definition at line 32 of file WallModel.C.
~WallModel () virtual
Destructor.
Definition at line 47 of file WallModel.C.
Member Function Documentation
TypeName ("wallModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , WallModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::WallModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file WallModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
const CloudType & owner () const
Return the owner cloud object.
Definition at line 55 of file WallModel.C.
CloudType & owner ()
Return non-const access to the owner cloud object.
Definition at line 63 of file WallModel.C.
const Foam::dictionary & dict () const
Return the dictionary.
Definition at line 70 of file WallModel.C.
const Foam::dictionary & coeffDict () const
Return the coefficients dictionary.
Definition at line 78 of file WallModel.C.
virtual scalar pREff (const typename CloudType::parcelType & p) const pure virtual
Return the effective radius for a particle for the model.
Implemented in WallLocalSpringSliderDashpot< CloudType >, and WallSpringSliderDashpot< CloudType >.
virtual bool controlsTimestep () const pure virtual
Whether the WallModel has a timestep limit that will.
require subCycling
Implemented in WallLocalSpringSliderDashpot< CloudType >, and WallSpringSliderDashpot< CloudType >.
virtual label nSubCycles () const pure virtual
For WallModels that control the timestep, calculate the.
number of subCycles needed to satisfy the minimum allowable timestep
Implemented in WallLocalSpringSliderDashpot< CloudType >, and WallSpringSliderDashpot< CloudType >.
virtual void evaluateWall (typename CloudType::parcelType & p, const List< point > & flatSitePoints, const List< WallSiteData< vector >> & flatSiteData, const List< point > & sharpSitePoints, const List< WallSiteData< vector >> & sharpSiteData) const pure virtual
Calculate the wall interaction for a parcel.
Implemented in WallLocalSpringSliderDashpot< CloudType >, and WallSpringSliderDashpot< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairCollision.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallModel/WallModel.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallModel/WallModel.C
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallModel/WallModelNew.C