OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
readInitialConditions.H File Reference
Functions
word constProp (initialConditions.lookup("constantProperty"))
if ((constProp!="pressure")&&(constProp!="volume"))
word fractionBasis (initialConditions.lookup("fractionBasis"))
if ((fractionBasis!="mass")&&(fractionBasis!="mole"))
PtrList< gasHThermoPhysics > specieData (Y.size())
forAll (specieData, i)
scalarList Y0 (nSpecie, 0.0)
scalarList X0 (nSpecie, 0.0)
dictionary fractions (initialConditions.subDict("fractions"))
if (fractionBasis=="mole")
forAll (Y, i)
thermo he ()
thermo correct ()
Variables
label nSpecie = Y.size()
else
const scalar mTot = sum(Y0)
const scalar mw = 1.0/invW
scalar h0 = 0.0
rho = thermo.rho()
scalar rho0 = rho[0]
scalar u0 = h0 - p0/rho0
scalar R0 = p0/(rho0*T0)
Rspecific [0] = R0
scalar integratedHeat = 0.0
Function Documentation
word constProp (initialConditions. lookup"constantProperty")
Referenced by if().
if ((constProp!="pressure")&&(constProp!="volume"))
Definition at line 2 of file readInitialConditions.H.
References Foam::abort(), constProp(), Foam::FatalError, and Foam::nl.
word fractionBasis (initialConditions. lookup"fractionBasis")
Referenced by if().
if ((fractionBasis!="mass")&&(fractionBasis!="mole"))
Definition at line 10 of file readInitialConditions.H.
References Foam::abort(), Foam::FatalError, fractionBasis(), and Foam::nl.
PtrList<gasHThermoPhysics> specieData (Y. size())
Referenced by forAll(), and if().
forAll (specieData , i)
Definition at line 19 of file readInitialConditions.H.
References i, specieData(), and thermo.
scalarList Y0 (nSpecie , 0. 0)
Referenced by forAll(), and if().
scalarList X0 (nSpecie , 0. 0)
Referenced by SprayParcel< ParcelType >::calc(), and if().
dictionary fractions (initialConditions. subDict"fractions")
Referenced by if().
if (fractionBasis = = "mole")
Definition at line 36 of file readInitialConditions.H.
References forAll, fractions(), i, mTot, mw, Foam::name(), readScalar, specieData(), Foam::sum(), X0(), Y, and Y0().
forAll (Y , i)
Definition at line 73 of file readInitialConditions.H.
References i, mTot, specieData(), and Y0().
thermo he ()
thermo correct ()
Variable Documentation
label nSpecie = Y.size()
Definition at line 17 of file readInitialConditions.H.
Referenced by chemistryModel< CompType, ThermoType >::jacobian(), ode< ChemistryModel >::solve(), and EulerImplicit< ChemistryModel >::solve().
else
Initial value:
{
        forAll(Y, i)
        {
            const word& name = Y[i].name();
            {
                Y0[i] = readScalar(fractions.lookup(name));
            }
        }
        scalar invW = 0.0
Definition at line 61 of file readInitialConditions.H.
const scalar mTot = sum(Y0)
Definition at line 72 of file readInitialConditions.H.
Referenced by ORourkeCollision< CloudType >::collideSorted(), forAll(), and if().
const scalar mw = 1.0/invW
Definition at line 78 of file readInitialConditions.H.
Referenced by if().
scalar h0 = 0.0
Definition at line 86 of file readInitialConditions.H.
thermo rho = thermo.rho()
Definition at line 96 of file readInitialConditions.H.
Referenced by CoBlended< Type >::blendingFactor(), Implicit< CloudType >::cacheFields(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), forces::calcForcesMoment(), ThermoParcel< ParcelType >::calcHeatTransfer(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), removeInjection::correct(), PaSR< Type >::correct(), relaxation::correct(), drippingInjection::correct(), curvatureSeparation::correct(), fixedCoeff::correct(), standardPhaseChange::correctModel(), chemistryModel< CompType, ThermoType >::derivatives(), forces::devRhoReff(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), thermo< Thermo, Type >::ea(), thermo< Thermo, Type >::es(), Peclet::execute(), CourantNo::execute(), scalarTransport::execute(), PatchFlowRateInjection< CloudType >::flowRate(), forAll(), forAllConstIter(), if(), Foam::MULES::implicitSolve(), PhiScheme< Type, PhiLimiter >::limiter(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), solidParticleCloud::move(), forces::mu(), RASModel< BasicTurbulenceModel >::New(), LESModel< BasicTurbulenceModel >::New(), fluidThermo::nu(), rhoMagSqr< Type >::operator()(), KinematicParcel< ParcelType >::readFields(), liquidMixtureProperties::rho(), InjectionModel< CloudType >::setNumberOfParticles(), ConeNozzleInjection< CloudType >::setProperties(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), chemistryModel< CompType, ThermoType >::solve(), SprayParcel< ParcelType >::solveTABEq(), chemistryModel< CompType, ThermoType >::tc(), LISAAtomization< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), alphaFixedPressureFvPatchScalarField::updateCoeffs(), uniformTotalPressureFvPatchScalarField::updateCoeffs(), totalPressureFvPatchScalarField::updateCoeffs(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), and KinematicParcel< ParcelType >::writeFields().
scalar rho0 = rho[0]
Definition at line 97 of file readInitialConditions.H.
Referenced by SprayParcel< ParcelType >::calc(), and if().
scalar u0 = h0 - p0/rho0
Definition at line 98 of file readInitialConditions.H.
Referenced by if(), and triangleFuncs::intersectAxesBundle().
scalar R0 = p0/(rho0*T0)
Definition at line 99 of file readInitialConditions.H.
Rspecific[0] = R0
Definition at line 100 of file readInitialConditions.H.
Referenced by if().
scalar integratedHeat = 0.0
Definition at line 102 of file readInitialConditions.H.
Referenced by if().