OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField alpha2f ("alpha2f", scalar(1)-alpha1f)
surfaceScalarField rAlphaAU1f (fvc::interpolate(alpha1 *rho1 *rAU1))
surfaceScalarField rAlphaAU2f (fvc::interpolate(alpha2 *rho2 *rAU2))
volVectorField HbyA1 (IOobject::groupName("HbyA", phase1.name()), U1)
volVectorField HbyA2 (IOobject::groupName("HbyA", phase2.name()), U2)
mrfZones makeAbsolute (phi1.oldTime())
mrfZones makeAbsolute (phi1)
mrfZones makeAbsolute (phi2.oldTime())
mrfZones makeAbsolute (phi2)
surfaceScalarField phiP1 ("phiP1", fvc::interpolate(rAU1 *phase1.turbulence().pPrime())*fvc::snGrad(alpha1)*mesh.magSf())
phiP1 boundaryField () == 0
surfaceScalarField phiP2 ("phiP2", fvc::interpolate(rAU2 *phase2.turbulence().pPrime())*fvc::snGrad(alpha2)*mesh.magSf())
surfaceScalarField phiHbyA1 (IOobject::groupName("phiHbyA", phase1.name()),(fvc::interpolate(HbyA1)&mesh.Sf())+rAlphaAU1f *fvc::ddtCorr(U1, phi1))
surfaceScalarField phiHbyA2 (IOobject::groupName("phiHbyA", phase2.name()),(fvc::interpolate(HbyA2)&mesh.Sf())+rAlphaAU2f *fvc::ddtCorr(U2, phi2))
mrfZones makeRelative (phiHbyA1)
mrfZones makeRelative (phiHbyA2)
mrfZones makeRelative (phi1.oldTime())
mrfZones makeRelative (phi1)
mrfZones makeRelative (phi2.oldTime())
mrfZones makeRelative (phi2)
surfaceScalarField phiHbyA ("phiHbyA", alpha1f *phiHbyA1+alpha2f *phiHbyA2)
surfaceScalarField rAUf ("rAUf", mag(alpha1f *rAlphaAU1f/fvc::interpolate(rho1)+alpha2f *rAlphaAU2f/fvc::interpolate(rho2)))
setSnGrad< fixedFluxPressureFvPatchScalarField > (p.boundaryField(),(phiHbyA.boundaryField()-mrfZones.relative(alpha1f.boundaryField()*(mesh.Sf().boundaryField()&U1.boundaryField())+alpha2f.boundaryField()*(mesh.Sf().boundaryField()&U2.boundaryField())))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
surfaceScalarField phid2 (IOobject::groupName("phid", phase2.name()), fvc::interpolate(psi2)*phi2)
deleteDemandDrivenData (pEqnComp1().faceFluxCorrectionPtr())
pEqnComp1 ().relax()
deleteDemandDrivenData (pEqnComp2().faceFluxCorrectionPtr())
pEqnComp2 ().relax()
volScalarField p_0 (p)
solve (pEqnComp1()+pEqnComp2()+pEqnIncomp, mesh.solver(p.select(pimple.finalInnerIter())))
fluid dgdt ()
p relax ()
U1 correctBoundaryConditions ()
fvOptions correct (U1)
fvOptions correct (U2)
if (thermo1.dpdt()||thermo2.dpdt())
Variables
rAU1 = 1.0/U1Eqn.A()
rAU2 = 1.0/U2Eqn.A()
HbyA1 = rAU1*U1Eqn.H()
HbyA2 = rAU2*U2Eqn.H()
phiHbyA1
phiHbyA2
tmp< fvScalarMatrix > pEqnComp1
tmp< fvScalarMatrix > pEqnComp2
else
phi1 = phiHbyA1 + rAlphaAU1f*mSfGradp/fvc::interpolate(rho1)
phi2 = phiHbyA2 + rAlphaAU2f*mSfGradp/fvc::interpolate(rho2)
phi = alpha1f*phi1 + alpha2f*phi2
mSfGradp = pEqnIncomp.flux()/rAUf
U1
U2
U = fluid.U()
p = max(p, pMin)
rho1 = psi1*(p - p_0)
rho2 = psi2*(p - p_0)
K1 = 0.5*magSqr(U1)
K2 = 0.5*magSqr(U2)
Function Documentation
surfaceScalarField alpha2f ("alpha2f" , scalar(1)- alpha1f)
surfaceScalarField rAlphaAU1f (fvc:: interpolatealpha1 *rho1 *rAU1)
surfaceScalarField rAlphaAU2f (fvc:: interpolatealpha2 *rho2 *rAU2)
volVectorField HbyA1 (IOobject:: groupName"HbyA", phase1.name(), U1)
volVectorField HbyA2 (IOobject:: groupName"HbyA", phase2.name(), U2)
mrfZones makeAbsolute (phi1. oldTime())
mrfZones makeAbsolute (phi1)
mrfZones makeAbsolute (phi2. oldTime())
mrfZones makeAbsolute (phi2)
surfaceScalarField phiP1 ("phiP1" , fvc:: interpolaterAU1 *phase1.turbulence().pPrime())*fvc::snGrad(alpha1)*mesh.magSf()
phi2 boundaryField () == 0
Referenced by eddyDiffusivity< compressible::turbulenceModel >::alphat(), wallDistData< TransferType >::correct(), radiationCoupledBase::emissivity(), thermalBaffle::info(), Foam::MULES::limitSum(), GeometricField< Type, PatchField, GeoMesh >::max(), GeometricField< Type, PatchField, GeoMesh >::min(), GeometricField< Type, PatchField, GeoMesh >::negate(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator==(), thermoSingleLayer::Qconvp(), thermoSingleLayer::Qconvw(), GeometricField< Type, PatchField, GeoMesh >::replace(), snGradScheme< Type >::snGrad(), GeometricField< Type, PatchField, GeoMesh >::T(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
surfaceScalarField phiP2 ("phiP2" , fvc:: interpolaterAU2 *phase2.turbulence().pPrime())*fvc::snGrad(alpha2)*mesh.magSf()
surfaceScalarField phiHbyA1 (IOobject:: groupName"phiHbyA", phase1.name(), (fvc::interpolate(HbyA1)&mesh.Sf())+rAlphaAU1f *fvc::ddtCorr(U1, phi1))
surfaceScalarField phiHbyA2 (IOobject:: groupName"phiHbyA", phase2.name(), (fvc::interpolate(HbyA2)&mesh.Sf())+rAlphaAU2f *fvc::ddtCorr(U2, phi2))
mrfZones makeRelative (phiHbyA1)
mrfZones makeRelative (phiHbyA2)
mrfZones makeRelative (phi1. oldTime())
mrfZones makeRelative (phi1)
mrfZones makeRelative (phi2. oldTime())
mrfZones makeRelative (phi2)
surfaceScalarField phiHbyA ("phiHbyA" , alpha1f *phiHbyA1+alpha2f * phiHbyA2)
surfaceScalarField rAUf ("rAUf" , mag(alpha1f *rAlphaAU1f/fvc::interpolate(rho1)+alpha2f *rAlphaAU2f/fvc::interpolate(rho2)))
setSnGrad< fixedFluxPressureFvPatchScalarField > (p. boundaryField(), (phiHbyA.boundaryField()-mrfZones.relative(alpha1f.boundaryField()*(mesh.Sf().boundaryField()&U1.boundaryField())+alpha2f.boundaryField()*(mesh.Sf().boundaryField()&U2.boundaryField())))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
surfaceScalarField phid2 (IOobject:: groupName"phid", phase2.name(), fvc::interpolate(psi2)* phi2)
deleteDemandDrivenData (pEqnComp1().faceFluxCorrectionPtr())
pEqnComp1 ()
deleteDemandDrivenData (pEqnComp2().faceFluxCorrectionPtr())
pEqnComp2 ()
volScalarField p_0 (p)
solve (pEqnComp1()+pEqnComp2()+ pEqnIncomp, mesh. solverp.select(pimple.finalInnerIter()))
fluid dgdt ()
p relax ()
U1 correctBoundaryConditions ()
fvOptions correct (U1)
fvOptions correct (U2)
if (thermo1. dpdt)||thermo2.dpdt()
Definition at line 258 of file pEqn.H.
References Foam::fvc::ddt(), dpdt, and p.
Variable Documentation
rAU1 = 1.0/U1Eqn.A()
Definition at line 5 of file pEqn.H.
rAU2 = 1.0/U2Eqn.A()
Definition at line 6 of file pEqn.H.
HbyA1 = rAU1*U1Eqn.H()
Definition at line 16 of file pEqn.H.
HbyA2 = rAU2*U2Eqn.H()
Definition at line 23 of file pEqn.H.
phiHbyA1
Initial value:
=
    (
        fvc::interpolate(rAU1*dragCoeff)*phi2
      - phiP1
      + rAlphaAU1f*(g & mesh.Sf())
    )
Definition at line 62 of file pEqn.H.
phiHbyA2
Initial value:
=
    (
        fvc::interpolate(rAU2*dragCoeff)*phi1
      - phiP2
      + rAlphaAU2f*(g & mesh.Sf())
    )
Definition at line 69 of file pEqn.H.
pEqnComp1
Initial value:
=
            (
                contErr1
              - fvc::Sp(fvc::ddt(alpha1) + fvc::div(alphaPhi1), rho1)
            )/rho1
          + (alpha1/rho1)*correction
            (
                psi1*fvm::ddt(p)
              + fvm::div(phid1, p) - fvm::Sp(fvc::div(phid1), p)
            )
Definition at line 114 of file pEqn.H.
pEqnComp2
Initial value:
=
            (
                contErr2
              - fvc::Sp(fvc::ddt(alpha2) + fvc::div(alphaPhi2), rho2)
            )/rho2
          + (alpha2/rho2)*correction
            (
                psi2*fvm::ddt(p)
              + fvm::div(phid2, p) - fvm::Sp(fvc::div(phid2), p)
            )
Definition at line 115 of file pEqn.H.
else
Initial value:
{
        pEqnComp1 =
            (
                contErr1
              - fvc::Sp(fvc::ddt(alpha1) + fvc::div(alphaPhi1), rho1)
            )/rho1
          + (alpha1*psi1/rho1)*correction(fvm::ddt(p))
Definition at line 157 of file pEqn.H.
phi1 = phiHbyA1 + rAlphaAU1f*mSfGradp/fvc::interpolate(rho1)
Definition at line 199 of file pEqn.H.
phi2 = phiHbyA2 + rAlphaAU2f*mSfGradp/fvc::interpolate(rho2)
Definition at line 206 of file pEqn.H.
phi = alpha1f*phi1 + alpha2f*phi2
Definition at line 208 of file pEqn.H.
mSfGradp = pEqnIncomp.flux()/rAUf
Definition at line 217 of file pEqn.H.
U1
Initial value:
= HbyA1
              + fvc::reconstruct
                (
                    rAlphaAU1f
                   *(
                        (g & mesh.Sf())
                      + mSfGradp/fvc::interpolate(rho1)
                    )
                  - phiP1
                )
Definition at line 219 of file pEqn.H.
Referenced by TrajectoryCollision< CloudType >::collideParcels(), and ORourkeCollision< CloudType >::collideSorted().
U2
Initial value:
= HbyA2
              + fvc::reconstruct
                (
                    rAlphaAU2f
                   *(
                        (g & mesh.Sf())
                      + mSfGradp/fvc::interpolate(rho2)
                    )
                  - phiP2
                )
Definition at line 232 of file pEqn.H.
Referenced by TrajectoryCollision< CloudType >::collideParcels(), and ORourkeCollision< CloudType >::collideSorted().
U = fluid.U()
Definition at line 245 of file pEqn.H.
p = max(p, pMin)
Definition at line 249 of file pEqn.H.
rho1 = psi1*(p - p_0)
Definition at line 252 of file pEqn.H.
rho2 = psi2*(p - p_0)
Definition at line 253 of file pEqn.H.
K1 = 0.5*magSqr(U1)
Definition at line 255 of file pEqn.H.
K2 = 0.5*magSqr(U2)
Definition at line 256 of file pEqn.H.