OpenFOAM: volRegion Class Reference
volRegion Class Reference
FunctionObjects » Field function objects
Volume (cell) region selection class.
Public Types
enum regionTypes { vrtCellZone, vrtAll }
Region type enumeration.
Public Member Functions
TypeName ("volRegion")
Run-time type information.
volRegion (const fvMesh &mesh, const dictionary &dict)
Construct from fvMesh and dictionary.
virtual ~volRegion ()
Destructor.
bool read (const dictionary &)
Read from dictionary.
const regionTypes & regionType () const
Return the region type.
const labelList & cellIDs () const
Return the local list of cell IDs.
label nCells () const
Return the number of cells in the region.
scalar V () const
Return total volume of the region.
Static Public Attributes
static const NamedEnum< regionTypes, 2 > regionTypeNames_
Region type names.
Protected Member Functions
void writeFileHeader (const writeFile &wf, Ostream &file)
Output file header information.
Protected Attributes
regionTypes regionType_
Region type.
word regionName_
Region name (patch, zone, etc.)
label regionID_
Region ID (patch ID, zone ID, etc.)
Detailed Description
Volume (cell) region selection class.
Examples of function object specification:
volRegion0
{
    .
    .
    regionType      cellZone;
    name            c0;
    .
    .
}
volRegionAll
{
    .
    .
    regionType      all;
    .
    .
}
Usage
Property Description Required Default value
regionType cellZone or all no all
name Name of cellZone if required no
See also
Foam::functionObject
Source files
volRegion.H
volRegion.C
Definition at line 105 of file volRegion.H.
Member Enumeration Documentation
enum regionTypes
Region type enumeration.
Enumerator
vrtCellZone
vrtAll
Definition at line 117 of file volRegion.H.
Constructor & Destructor Documentation
volRegion (const fvMesh & mesh, const dictionary & dict)
Construct from fvMesh and dictionary.
Definition at line 73 of file volRegion.C.
References Foam::read().
Referenced by volRegion::writeFileHeader().
~volRegion () virtual
Destructor.
Definition at line 93 of file volRegion.C.
References volRegion::read().
Member Function Documentation
void writeFileHeader (const writeFile & wf, Ostream & file) protected
Output file header information.
Definition at line 58 of file volRegion.C.
References Foam::endl(), volRegion::volRegion(), writeFile::writeCommented(), and writeFile::writeHeaderValue().
Referenced by NamedEnum< Enum, nEnum >::names(), and volFieldValue::writeFileHeader().
TypeName ("volRegion")
Run-time type information.
bool read (const dictionary & dict)
Read from dictionary.
Definition at line 100 of file volRegion.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::lookup(), and Foam::nl.
Referenced by volRegion::~volRegion().
const Foam::functionObjects::volRegion::regionTypes & regionType () const inline
Return the region type.
Definition at line 29 of file volRegionI.H.
References volRegion::regionType_.
const Foam::labelList & cellIDs () const
Return the local list of cell IDs.
Definition at line 150 of file volRegion.C.
References List< label >::null().
Foam::label nCells () const
Return the number of cells in the region.
Definition at line 163 of file volRegion.C.
References Foam::returnReduce().
Foam::scalar V () const
Return total volume of the region.
Definition at line 176 of file volRegion.C.
References Foam::gSum().
Member Data Documentation
const Foam::NamedEnum< Foam::functionObjects::volRegion::regionTypes, 2 > regionTypeNames_ static
Region type names.
Definition at line 124 of file volRegion.H.
Referenced by NamedEnum< Enum, nEnum >::names().
regionTypes regionType_ protected
Region type.
Definition at line 132 of file volRegion.H.
Referenced by volRegion::regionType().
word regionName_ protected
Region name (patch, zone, etc.)
Definition at line 135 of file volRegion.H.
label regionID_ protected
Region ID (patch ID, zone ID, etc.)
Definition at line 138 of file volRegion.H.
The documentation for this class was generated from the following files:
src/finiteVolume/functionObjects/volRegion/volRegion.H
src/finiteVolume/functionObjects/volRegion/volRegion.C
src/finiteVolume/functionObjects/volRegion/volRegionI.H