OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volVectorField HbyA ("HbyA", U)
if (pressureImplicitPorosity)
UEqn clear ()
surfaceScalarField phiHbyA ("phiHbyA", fvc::interpolate(rho *HbyA)&mesh.Sf())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
Variables
else
bool closedVolume = false
rho = thermo.rho()
Function Documentation
volVectorField HbyA ("HbyA" , U)
if (pressureImplicitPorosity)
Definition at line 6 of file pEqn.H.
References HbyA, trTU, and UEqn().
UEqn clear ()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::interpolate(rho *HbyA)&mesh.Sf())
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
while (simple. correctNonOrthogonal())
Definition at line 29 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::grad(), Foam::fvc::laplacian(), p, phi, phiHbyA, pRefCell, pRefValue, pressureImplicitPorosity(), rho, simple, trAU, trTU, and U.
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
Definition at line 83 of file pEqn.H.
References Foam::fvc::domainIntegrate(), initialMass, and p.
Variable Documentation
else
Initial value:
{
        HbyA = trAU()*UEqn().H()
Definition at line 11 of file pEqn.H.
closedVolume = false
Definition at line 17 of file pEqn.H.
rho = thermo.rho()
Definition at line 89 of file pEqn.H.