OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallShearStress Class Reference
FunctionObjects » Forces function objects
This function object evaluates and outputs the shear stress at wall patches. The result is written as a volVectorField to time directories as field 'wallShearStress'.
Public Member Functions
TypeName ("wallShearStress")
Runtime type information.
wallShearStress (const word &name, const Time &runTime, const dictionary &)
Construct from Time and dictionary.
virtual ~wallShearStress ()
Destructor.
virtual bool read (const dictionary &)
Read the wallShearStress data.
virtual bool execute ()
Calculate the wall shear-stress.
virtual bool write ()
Write the wall shear-stress.
Public Member Functions inherited from writeFiles
writeFiles (const word &name, const Time &time, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFiles (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from writeFile
writeFile (const word &name, const Time &t, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFile (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
virtual void writeFileHeader (const label i)
File header information.
void calcShearStress (const fvMesh &mesh, const volSymmTensorField &Reff, volVectorField &shearStress)
Calculate the shear stress.
Protected Member Functions inherited from writeFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
writeFiles (const writeFiles &)
Disallow default bitwise copy construct.
void operator= (const writeFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from writeFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
writeFile (const writeFile &)
Disallow default bitwise copy construct.
void operator= (const writeFile &)
Disallow default bitwise assignment.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
labelHashSet patchSet_
Optional list of patches to process.
Protected Attributes inherited from writeFile
const word prefix_
Prefix.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
This function object evaluates and outputs the shear stress at wall patches. The result is written as a volVectorField to time directories as field 'wallShearStress'.
where
= stress tensor
= patch normal vector (into the domain)
The shear stress (symmetrical) tensor field is retrieved from the turbulence model. All wall patches are included by default; to restrict the calculation to certain patches, use the optional 'patches' entry.
Example of function object specification:
    wallShearStress1
    {
        type        wallShearStress;
        libs ("libfieldFunctionObjects.so");
        ...
        patches     (".*Wall");
    }
Function object usage
Property Description Required Default value
type type name: wallShearStress yes
patches list of patches to process no all wall patches
See also
Foam::functionObject Foam::functionObjects::writeFiles Foam::functionObjects::pressureTools Foam::functionObjects::timeControl
Source files
wallShearStress.H
wallShearStress.C
Definition at line 122 of file wallShearStress.H.
Constructor & Destructor Documentation
wallShearStress (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 84 of file wallShearStress.C.
References Foam::dimLength, Foam::dimTime, Foam::exit(), Foam::FatalError, FatalErrorInFunction, mesh, IOobject::NO_READ, IOobject::NO_WRITE, Foam::read(), Foam::sqr(), fvMesh::time(), Time::timeName(), Foam::type(), and Foam::Zero.
~wallShearStress () virtual
Destructor.
Definition at line 132 of file wallShearStress.C.
Member Function Documentation
void writeFileHeader (const label i) protected virtual
File header information.
Reimplemented from writeFile.
Definition at line 48 of file wallShearStress.C.
References wallShearStress::calcShearStress(), and Foam::endl().
void calcShearStress (const fvMesh & mesh, const volSymmTensorField & Reff, volVectorField & shearStress) protected
Calculate the shear stress.
Definition at line 61 of file wallShearStress.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAllConstIter(), fvMesh::magSf(), patchi, and fvMesh::Sf().
Referenced by wallShearStress::writeFileHeader().
TypeName ("wallShearStress")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the wallShearStress data.
Reimplemented from regionFunctionObject.
Definition at line 138 of file wallShearStress.C.
References polyMesh::boundaryMesh(), Foam::endl(), forAll, forAllConstIter(), Foam::Info, HashSet< Key, Hash >::insert(), dictionary::lookupOrDefault(), Foam::name(), Foam::nl, patchi, polyBoundaryMesh::patchSet(), regionFunctionObject::read(), Foam::type(), and WarningInFunction.
bool execute () virtual
Calculate the wall shear-stress.
Implements functionObject.
Definition at line 194 of file wallShearStress.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, objectRegistry::foundObject(), objectRegistry::lookupObject(), turbulenceModel::propertiesName, and Foam::type().
bool write () virtual
Write the wall shear-stress.
Reimplemented from writeFiles.
Definition at line 235 of file wallShearStress.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::endl(), forAllConstIter(), Foam::gMax(), Foam::gMin(), Log, regionFunctionObject::lookupObject(), UPstream::master(), fvPatch::name(), Foam::name(), IOobject::name(), Foam::nl, patches, patchi, token::TAB, fvMesh::time(), Foam::type(), dimensioned< Type >::value(), writeFiles::write(), and regIOobject::write().
Member Data Documentation
labelHashSet patchSet_ protected
Optional list of patches to process.
Definition at line 131 of file wallShearStress.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/wallShearStress/wallShearStress.H
src/functionObjects/field/wallShearStress/wallShearStress.C