OpenFOAM-dev: writeFile Class Reference 2
writeFile Class Reference
functionObject base class for writing single files
Public Member Functions
writeFile (const word &name, const Time &t, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFile (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
virtual bool read (const dictionary &)
Read optional controls.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool execute ()=0
Called at each ++ or += of the time-loop.
virtual bool write ()=0
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Static Public Attributes
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Protected Member Functions
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void writeFileHeader (const label i=0)
File header information.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
writeFile (const writeFile &)
Disallow default bitwise copy construct.
void operator= (const writeFile &)
Disallow default bitwise assignment.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
const word prefix_
Prefix.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Detailed Description
functionObject base class for writing single files
See also
Foam::regionFunctionObject Foam::functionObject
Source files
writeFile.H
functionObjectFile.C
Definition at line 56 of file writeFile.H.
Constructor & Destructor Documentation
writeFile (const writeFile &) protected
Disallow default bitwise copy construct.
Referenced by writeFile::valueWidth(), and writeFile::writeFile().
writeFile (const word & name, const Time & t, const dictionary & dict, const word & prefix)
Construct from name, Time, dictionary and prefix.
Definition at line 101 of file writeFile.C.
References writeFile::writeFile().
writeFile (const word & name, const objectRegistry & obr, const dictionary & dict, const word & prefix)
Construct from name, objectRegistry, dictionary and prefix.
Definition at line 114 of file writeFile.C.
~writeFile () virtual
Destructor.
Definition at line 128 of file writeFile.C.
Member Function Documentation
void initStream (Ostream & os) const protected virtual
Initialise the output stream for writing.
Definition at line 43 of file writeFile.C.
References writeFile::charWidth(), Foam::scientific(), IOstream::setf(), and Ostream::width().
Referenced by writeFiles::createFiles().
Foam::fileName baseFileDir () const protected virtual
Return the base directory for output.
Definition at line 50 of file writeFile.C.
References polyMesh::defaultRegion, mesh, IOobject::name(), regionFunctionObject::obr_, writeFile::outputPrefix, UPstream::parRun(), Time::path(), and objectRegistry::time().
Referenced by writeFile::baseTimeDir(), and writeFiles::createFiles().
Foam::fileName baseTimeDir () const protected virtual
Return the base directory for the current time value.
Definition at line 79 of file writeFile.C.
References writeFile::baseFileDir(), regionFunctionObject::obr_, writeFile::prefix_, objectRegistry::time(), and Time::timeName().
void writeFileHeader (const label i = 0) protected virtual
File header information.
Reimplemented in surfaceRegion, volRegion, forces, forceCoeffs, fieldMinMax, fieldValueDelta, wallShearStress, cloudInfo, and residuals.
Definition at line 85 of file writeFile.C.
References writeFile::valueWidth().
Referenced by writeFiles::createFiles().
Foam::Omanip< int > valueWidth (const label offset = 0) const protected virtual
Return the value width when writing to stream with optional offset.
Definition at line 90 of file writeFile.C.
References writeFile::addChars, IOstream::defaultPrecision(), Foam::setw(), and writeFile::writeFile().
Referenced by writeFile::writeFileHeader().
void operator= (const writeFile &) protected
Disallow default bitwise assignment.
void writeCommented (Ostream & os, const string & str) const
Write a commented string to stream.
Definition at line 141 of file writeFile.C.
References writeFile::charWidth(), Foam::setw(), and writeFile::writeTabbed().
Referenced by writeFile::charWidth().
void writeTabbed (Ostream & os, const string & str) const
Write a tabbed string to stream.
Definition at line 152 of file writeFile.C.
References writeFile::charWidth(), Foam::setw(), Foam::tab, and writeFile::writeHeader().
Referenced by writeFile::writeCommented(), and residuals::writeFileHeader().
void writeHeader (Ostream & os, const string & str) const
Write a commented header to stream.
Definition at line 162 of file writeFile.C.
References writeFile::charWidth(), Foam::nl, Foam::setf(), and Foam::setw().
Referenced by writeFile::writeTabbed().
void writeTime (Ostream & os) const
Write the current time to stream.
Definition at line 172 of file writeFile.C.
References writeFile::charWidth(), regionFunctionObject::obr_, Foam::setw(), objectRegistry::time(), and Time::timeName().
void writeHeaderValue (Ostream & os, const string & property, const Type & value) const
Write a (commented) header property and value pair.
Definition at line 30 of file writeFileTemplates.C.
References Foam::nl, Foam::setf(), and Foam::setw().
Foam::label charWidth () const
Return width of character stream output.
Definition at line 134 of file writeFile.C.
References writeFile::addChars, IOstream::defaultPrecision(), and writeFile::writeCommented().
Referenced by writeFile::initStream(), writeFile::writeCommented(), writeFile::writeHeader(), writeFile::writeTabbed(), and writeFile::writeTime().
Member Data Documentation
const word prefix_ protected
Prefix.
Definition at line 66 of file writeFile.H.
Referenced by writeFile::baseTimeDir(), and writeFiles::createFiles().
const Foam::word outputPrefix static
Directory prefix.
Definition at line 96 of file writeFile.H.
Referenced by writeFile::baseFileDir().
Foam::label addChars = 7 static
Additional characters for writing.
Definition at line 99 of file writeFile.H.
Referenced by writeFile::charWidth(), and writeFile::valueWidth().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/writeFile/writeFile.H
src/OpenFOAM/db/functionObjects/writeFile/writeFile.C
src/OpenFOAM/db/functionObjects/writeFile/writeFileTemplates.C