OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+turbulence->divDevRhoReff(U)==parcels.SU(U)+fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
fvOptions correct (U)
Variables
K = 0.5*magSqr(U)
Function Documentation
fvVectorMatrix UEqn (fvm:: ddtrho, U)+fvm::div(phi, U)+turbulence->divDevRhoReff(U = =parcels.SU(U)+fvOptions(rho, U))
U2Eqn relax ()
Initial value:
{
            phi = phiHbyA + pEqn.flux()
Referenced by fvMatrix< Type >::relax(), GeometricField< Type, PatchField, GeoMesh >::relax(), ReactingCloud< CloudType >::relaxSources(), ThermoCloud< CloudType >::relaxSources(), and KinematicCloud< CloudType >::relaxSources().
fvOptions constrain (UEqn)
fvOptions correct (U)
Variable Documentation
K = 0.5*magSqr(U)
Definition at line 31 of file UEqn.H.