OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wakeEntrainmentCoalescence Class Reference
Bubble coalescence due to wake entrainment IATE source as defined in paper:
Public Member Functions
TypeName ("wakeEntrainmentCoalescence")
Runtime type information.
wakeEntrainmentCoalescence (const IATE &iate, const dictionary &dict)
virtual ~wakeEntrainmentCoalescence ()
Destructor.
virtual tmp< volScalarField > R () const
TypeName ("wakeEntrainmentCoalescence")
Runtime type information.
wakeEntrainmentCoalescence (const IATE &iate, const dictionary &dict)
virtual ~wakeEntrainmentCoalescence ()
Destructor.
virtual tmp< volScalarField > R () const
Public Member Functions inherited from IATEsource
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
Additional Inherited Members
Static Public Member Functions inherited from IATEsource
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes inherited from IATEsource
const IATE & iate_
Reference to the IATE this source applies to.
Detailed Description
Bubble coalescence due to wake entrainment IATE source as defined in paper:
    "Development of Interfacial Area Transport Equation"
    Ishii, M., Kim, S. and Kelly, J.,
    Nuclear Engineering and Technology, Vol.37 No.6 December 2005
Source files
wakeEntrainmentCoalescence.H
wakeEntrainmentCoalescence.C
    "Development of Interfacial Area Transport Equation"
    Ishii, M., Kim, S. and Kelly, J.,
    Nuclear Engineering and Technology, Vol.37 No.6 December 2005
Source files
wakeEntrainmentCoalescence.H
wakeEntrainmentCoalescence.C
Definition at line 58 of file wakeEntrainmentCoalescence.H.
Constructor & Destructor Documentation
wakeEntrainmentCoalescence (const IATE & iate, const dictionary & dict)
virtual ~wakeEntrainmentCoalescence () inline virtual
Destructor.
Definition at line 82 of file wakeEntrainmentCoalescence.H.
References wakeEntrainmentCoalescence::R().
wakeEntrainmentCoalescence (const IATE & iate, const dictionary & dict)
virtual ~wakeEntrainmentCoalescence () inline virtual
Destructor.
Definition at line 82 of file wakeEntrainmentCoalescence.H.
References wakeEntrainmentCoalescence::R().
Member Function Documentation
TypeName ("wakeEntrainmentCoalescence")
Runtime type information.
virtual tmp<volScalarField> R () const virtual
Implements IATEsource.
Referenced by wakeEntrainmentCoalescence::~wakeEntrainmentCoalescence().
TypeName ("wakeEntrainmentCoalescence")
Runtime type information.
virtual tmp<volScalarField> R () const virtual
Implements IATEsource.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATEsources/wakeEntrainmentCoalescence/wakeEntrainmentCoalescence.H