OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
writeFiles Class Reference
functionObject base class for writing files
Public Member Functions
writeFiles (const word &name, const Time &time, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFiles (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
virtual bool write (const bool postProcess=false)
Write function.
Public Member Functions inherited from writeFile
writeFile (const word &name, const Time &t, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFile (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
virtual bool read (const dictionary &)
Read optional controls.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool execute (const bool postProcess=false)=0
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
writeFiles (const writeFiles &)
Disallow default bitwise copy construct.
void operator= (const writeFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from writeFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual void writeFileHeader (const label i=0)
File header information.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
writeFile (const writeFile &)
Disallow default bitwise copy construct.
void operator= (const writeFile &)
Disallow default bitwise assignment.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from regionFunctionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Static Public Attributes inherited from functionObject
static int debug
Protected Attributes inherited from writeFile
const word prefix_
Prefix.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Detailed Description
functionObject base class for writing files
See also
Foam::functionObject Foam::OutputFilterFunctionObject
Source files
writeFiles.H
functionObjectFiles.C
Definition at line 56 of file writeFiles.H.
Constructor & Destructor Documentation
writeFiles (const writeFiles &) protected
Disallow default bitwise copy construct.
Referenced by writeFiles::resetName(), and writeFiles::writeFiles().
writeFiles (const word & name, const Time & time, const dictionary & dict, const word & prefix)
Construct from name, Time, dictionary and prefix.
Definition at line 96 of file writeFiles.C.
References writeFiles::writeFiles().
writeFiles (const word & name, const objectRegistry & obr, const dictionary & dict, const word & prefix)
Construct from name, objectRegistry, dictionary and prefix.
Definition at line 110 of file writeFiles.C.
~writeFiles () virtual
Destructor.
Definition at line 125 of file writeFiles.C.
Member Function Documentation
void createFiles () protected virtual
Create the output file.
Definition at line 32 of file writeFiles.C.
References writeFile::baseFileDir(), forAll, IOstream::good(), writeFile::initStream(), UPstream::master(), Foam::mkDir(), regionFunctionObject::obr_, writeFile::prefix_, Time::startTime(), objectRegistry::time(), Time::timeName(), dimensioned< Type >::value(), and writeFile::writeFileHeader().
Referenced by writeFiles::write().
void resetNames (const wordList & names) protected virtual
Reset the list of names from a wordList.
Definition at line 67 of file writeFiles.C.
References List< T >::append(), List< T >::clear(), UPstream::master(), and List< T >::size().
Referenced by cloudInfo::read().
void resetName (const word & name) protected virtual
Reset the list of names to a single name entry.
Definition at line 80 of file writeFiles.C.
References List< T >::append(), List< T >::clear(), UPstream::master(), and writeFiles::writeFiles().
void operator= (const writeFiles &) protected
Disallow default bitwise assignment.
const Foam::wordList & names () const
Return const access to the names.
Definition at line 131 of file writeFiles.C.
Foam::OFstream & file ()
Return access to the file (if only 1)
Definition at line 137 of file writeFiles.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, UPstream::master(), and WarningInFunction.
Referenced by residuals::writeFileHeader(), and residuals::writeResidual().
Foam::PtrList< Foam::OFstream > & files ()
Return access to the files.
Definition at line 164 of file writeFiles.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UPstream::master().
Foam::OFstream & file (const label i)
Return file 'i'.
Definition at line 177 of file writeFiles.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UPstream::master().
bool write (const bool postProcess = false) virtual
Write function.
Implements functionObject.
Reimplemented in faceSource, cellSource, forces, forceCoeffs, fieldMinMax, fieldValueDelta, wallShearStress, fieldValue, cloudInfo, residuals, and yPlus.
Definition at line 197 of file writeFiles.C.
References writeFiles::createFiles().
Referenced by yPlus::execute(), wallShearStress::execute(), yPlus::write(), residuals::write(), cloudInfo::write(), fieldValue::write(), wallShearStress::write(), fieldValueDelta::write(), fieldMinMax::write(), forceCoeffs::write(), and forces::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/writeFiles/writeFiles.H
src/OpenFOAM/db/functionObjects/writeFiles/writeFiles.C