OpenFOAM-dev: writeDictionary Class Reference 2
writeDictionary Class Reference
FunctionObjects » Utility function objects
This function object writes dictionaries on start-up, and on change.
Public Member Functions
TypeName ("writeDictionary")
Runtime type information.
writeDictionary (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~writeDictionary ()
Destructor.
virtual bool read (const dictionary &)
Read the writeDictionary data.
virtual bool execute ()
Execute, currently does nothing.
virtual bool write ()
Write the selected dictionaries.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
This function object writes dictionaries on start-up, and on change.
Source files
writeDictionary.H
writeDictionary.C
Definition at line 59 of file writeDictionary.H.
Constructor & Destructor Documentation
writeDictionary (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 100 of file writeDictionary.C.
References Foam::read().
~writeDictionary () virtual
Destructor.
Definition at line 124 of file writeDictionary.C.
Member Function Documentation
TypeName ("writeDictionary")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the writeDictionary data.
Reimplemented from functionObject.
Definition at line 130 of file writeDictionary.C.
References Foam::endl(), forAll, Foam::Info, dictionary::lookup(), Foam::name(), Foam::nl, and Foam::type().
bool execute () virtual
Execute, currently does nothing.
Implements functionObject.
Definition at line 156 of file writeDictionary.C.
bool write () virtual
Write the selected dictionaries.
Implements functionObject.
Definition at line 162 of file writeDictionary.C.
References dictionaryName::dictName(), dictionary::digest(), Foam::endl(), forAll, Foam::Info, Foam::name(), Foam::nl, Foam::type(), and IOobject::writeDivider().
The documentation for this class was generated from the following files:
src/functionObjects/utilities/writeDictionary/writeDictionary.H
src/functionObjects/utilities/writeDictionary/writeDictionary.C