OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
writeRegisteredObject Class Reference
FunctionObjects » Utility function objects
This function object allows specification of different writing frequency of objects registered to the database. It has similar functionality as the main time database through the writeControl setting:
Public Member Functions
TypeName ("writeRegisteredObject")
Runtime type information.
writeRegisteredObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~writeRegisteredObject ()
Destructor.
virtual bool read (const dictionary &)
Read the writeRegisteredObject data.
virtual bool execute (const bool postProcess=false)
Do nothing.
virtual bool write (const bool postProcess=false)
Write the registered objects.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
This function object allows specification of different writing frequency of objects registered to the database. It has similar functionality as the main time database through the writeControl setting:
timeStep
writeTime
adjustableRunTime
runTime
clockTime
cpuTime
Example of function object specification:
writeRegisteredObject1
{
    type        writeRegisteredObject;
    libs ("libutilityFunctionObjects.so");
    exclusiveWriting     true;
    ...
    objectNames (obj1 obj2);
}
Function object usage
Property Description Required Default value
type type name: writeRegisteredObject yes
objectNames objects to write yes
exclusiveWriting Takes over object writing no yes
exclusiveWriting disables automatic writing (i.e through database) of the objects to avoid duplicate writing.
See also
Foam::functionObject Foam::functionObjects::timeControl
Source files
writeRegisteredObject.H
writeRegisteredObject.C
Definition at line 114 of file writeRegisteredObject.H.
Constructor & Destructor Documentation
writeRegisteredObject (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 52 of file writeRegisteredObject.C.
References Foam::read().
~writeRegisteredObject () virtual
Destructor.
Definition at line 75 of file writeRegisteredObject.C.
Member Function Documentation
TypeName ("writeRegisteredObject")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the writeRegisteredObject data.
Implements functionObject.
Definition at line 81 of file writeRegisteredObject.C.
References writeRegisteredObject::execute(), dictionary::lookup(), and dictionary::readIfPresent().
bool execute (const bool postProcess = false) virtual
Do nothing.
Implements functionObject.
Definition at line 91 of file writeRegisteredObject.C.
References writeRegisteredObject::write().
Referenced by writeRegisteredObject::read().
bool write (const bool postProcess = false) virtual
Write the registered objects.
Implements functionObject.
Definition at line 100 of file writeRegisteredObject.C.
References Foam::endl(), forAll, Foam::Info, Foam::name(), IOobject::name(), Foam::nl, IOobject::NO_WRITE, List< T >::size(), Foam::type(), WarningInFunction, regIOobject::write(), and IOobject::writeOpt().
Referenced by writeRegisteredObject::execute().
The documentation for this class was generated from the following files:
src/functionObjects/utilities/writeRegisteredObject/writeRegisteredObject.H
src/functionObjects/utilities/writeRegisteredObject/writeRegisteredObject.C