OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volScalarField rAUrel (1.0/UrelEqn().A())
volVectorField HbyA ("HbyA", Urel)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA)&mesh.Sf())+fvc::interpolate(rAUrel)*fvc::ddtCorr(Urel, phi))
adjustPhi (phiHbyA, Urel, p)
tmp< volScalarField > rAtUrel (rAUrel)
if (pimple.consistent())
if (pimple.nCorrPISO()<=1)
while (pimple.correctNonOrthogonal())
p relax ()
Urel correctBoundaryConditions ()
fvOptions correct (Urel)
Variables
HbyA = rAUrel*UrelEqn().H()
Urel = HbyA - rAtUrel()*fvc::grad(p)
Function Documentation
volScalarField rAUrel (1.0/ UrelEqn).A()
Referenced by if().
volVectorField HbyA ("HbyA" , Urel)
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA)&mesh.Sf())+fvc::interpolate(rAUrel)*fvc::ddtCorr(Urel, phi))
adjustPhi (phiHbyA , Urel , p)
tmp<volScalarField> rAtUrel (rAUrel)
Referenced by if(), and while().
if (pimple. consistent())
Definition at line 16 of file pEqn.H.
References Foam::fvc::grad(), HbyA, Foam::MULES::interpolate(), Foam::max(), mesh, p, phiHbyA, rAtUrel(), rAUrel(), Foam::fvc::snGrad(), and UrelEqn().
if (pimple.nCorrPISO()<= 1)
Definition at line 24 of file pEqn.H.
References UrelEqn().
while (pimple. correctNonOrthogonal())
Definition at line 30 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), mesh, p, phi, phiHbyA, pimple, pRefCell, pRefValue, and rAtUrel().
p relax ()
Urel correctBoundaryConditions ()
fvOptions correct (Urel)
Variable Documentation
HbyA = rAUrel*UrelEqn().H()
Definition at line 3 of file pEqn.H.
Urel = HbyA - rAtUrel()*fvc::grad(p)
Definition at line 53 of file pEqn.H.
Referenced by ThermoSurfaceFilm< CloudType >::absorbInteraction(), ThermoSurfaceFilm< CloudType >::bounceInteraction(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), NoAtomization< CloudType >::clone(), NoBreakup< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), BlobsSheetAtomization< CloudType >::clone(), ReitzDiwakar< CloudType >::clone(), ETAB< CloudType >::clone(), PilchErdman< CloudType >::clone(), LISAAtomization< CloudType >::clone(), TAB< CloudType >::clone(), SHF< CloudType >::clone(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), SRFModel::New(), ThermoSurfaceFilm< CloudType >::splashInteraction(), BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::TABtwoWeCrit(), LISAAtomization< CloudType >::update(), and ThermoSurfaceFilm< CloudType >::wetSplashInteraction().