OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
volRegion Class Reference
FunctionObjects » Field function objects
This function object provides a 'cell region' variant of the fieldValues function object. Given a list of user-specified fields and a selection of mesh cells, a number of operations can be performed, such as sums, averages and integrations.
Public Types
enum regionTypes { stCellZone, stAll }
region type enumeration
enum operationType {
opNone, opSum, opSumMag, opAverage,
opWeightedAverage, opVolAverage, opWeightedVolAverage, opVolIntegrate,
opMin, opMax, opCoV
}
Operation type enumeration.
Public Member Functions
TypeName ("volRegion")
Run-time type information.
volRegion (const word &name, const Time &runTime, const dictionary &dict)
Construct from name, Time and dictionary.
volRegion (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from name, objectRegistry and dictionary.
virtual ~volRegion ()
Destructor.
const regionTypes & regionType () const
Return the region type.
const labelList & cellId () const
Return the local list of cell IDs.
template<class Type >
bool writeValues (const word &fieldName)
Templated helper function to output field values.
template<class Type >
tmp< Field< Type > > filterField (const Field< Type > &field) const
Filter a field according to cellIds.
virtual bool read (const dictionary &)
Read from dictionary.
virtual bool write ()
Calculate and write.
template<class Type >
Foam::tmp< Foam::Field< Type > > setFieldValues (const word &fieldName, const bool mustGet) const
template<class Type >
Foam::tmp< Foam::Field< Type > > filterField (const Field< Type > &field) const
Public Member Functions inherited from fieldValue
TypeName ("fieldValue")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, fieldValue, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict),(name, obr, dict))
fieldValue (const word &name, const Time &runTime, const dictionary &dict, const word &valueType)
Construct from Time and dictionary.
fieldValue (const word &name, const objectRegistry &obr, const dictionary &dict, const word &valueType)
Construct from objectRegistry and dictionary.
virtual ~fieldValue ()
Destructor.
const dictionary & dict () const
Return the reference to the construction dictionary.
const word & regionName () const
Return the region name.
const wordList & fields () const
Return the list of field names.
const Switch & writeFields () const
Return the output field values flag.
const fvMesh & mesh () const
Helper function to return the reference to the mesh.
const dictionary & resultDict () const
Return access to the latest set of results.
virtual bool execute ()
Execute.
Public Member Functions inherited from writeFiles
writeFiles (const word &name, const Time &time, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFiles (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from writeFile
writeFile (const word &name, const Time &t, const dictionary &dict, const word &prefix)
Construct from name, Time, dictionary and prefix.
writeFile (const word &name, const objectRegistry &obr, const dictionary &dict, const word &prefix)
Construct from name, objectRegistry, dictionary and prefix.
virtual ~writeFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Static Public Attributes
static const NamedEnum< regionTypes, 2 > regionTypeNames_
region type names
static const NamedEnum< operationType, 11 > operationTypeNames_
Operation type names.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Protected Member Functions
void initialise (const dictionary &dict)
Initialise, e.g. cell addressing.
template<class Type >
bool validField (const word &fieldName) const
Return true if the field name is valid.
template<class Type >
tmp< Field< Type > > setFieldValues (const word &fieldName, const bool mustGet=false) const
Insert field values into values list.
template<class Type >
Type processValues (const Field< Type > &values, const scalarField &V, const scalarField &weightField) const
Apply the 'operation' to the values.
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from fieldValue
template<class Type >
void combineFields (Field< Type > &field)
Combine fields from all processor domains into single field.
template<class Type >
void combineFields (tmp< Field< Type >> &)
Combine fields from all processor domains into single field.
Protected Member Functions inherited from writeFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
writeFiles (const writeFiles &)
Disallow default bitwise copy construct.
void operator= (const writeFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from writeFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
writeFile (const writeFile &)
Disallow default bitwise copy construct.
void operator= (const writeFile &)
Disallow default bitwise assignment.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
regionTypes regionType_
region type
operationType operation_
Operation to apply to values.
label nCells_
Global number of cells.
labelList cellId_
Local list of cell IDs.
word weightFieldName_
Weight field name - only used for opWeightedAverage mode.
scalar volume_
Volume of the volRegion.
bool writeVolume_
Optionally write the volume of the volRegion.
Protected Attributes inherited from fieldValue
dictionary dict_
Construction dictionary.
word regionName_
Name of region (patch, zone, etc.)
wordList fields_
List of field names to operate on.
Switch writeFields_
Output field values flag.
dictionary resultDict_
Results dictionary for external access of results.
Protected Attributes inherited from writeFile
const word prefix_
Prefix.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from fieldValue
static autoPtr< fieldValue > New (const word &name, const objectRegistry &obr, const dictionary &dict, const bool output=true)
Return a reference to the selected fieldValue.
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Detailed Description
This function object provides a 'cell region' variant of the fieldValues function object. Given a list of user-specified fields and a selection of mesh cells, a number of operations can be performed, such as sums, averages and integrations.
Example of function object specification:
volRegion1
{
    type            volRegion;
    libs ("libfieldFunctionObjects.so");
    ...
    log             true;
    writeFields     true;
    regionType      cellZone;
    name            c0;
    operation       volAverage;
    weightField     alpha1;
    fields
    (
        p
        U
    );
}
Function object usage
Property Description Required Default value
type Type name: volRegion yes
log Write data to standard output no no
writeFields Write the region field values yes
writeVolume Write the volume of the volRegion no
regionType cell regionType: see below yes
name name of cell regionType if required no
operation operation to perform yes
weightField name of field to apply weighting no
fields list of fields to operate on yes
Where regionType is defined by
cellZone : requires a 'name' entry to specify the cellZone
all : all cells
The operation is one of:
none : no operation
sum : sum
sumMag : sum of component magnitudes
average : ensemble average
weightedAverage : weighted average
volAverage : volume weighted average
weightedVolAverage : weighted volume average
volIntegrate : volume integral
min : minimum
max : maximum
CoV : coefficient of variation: standard deviation/mean
See also
Foam::fieldValues Foam::functionObject
Source files
volRegion.H
volRegion.C
Definition at line 224 of file volRegion.H.
Member Enumeration Documentation
enum regionTypes
region type enumeration
Enumerator
stCellZone
stAll
Definition at line 234 of file volRegion.H.
enum operationType
Operation type enumeration.
Enumerator
opNone
opSum
opSumMag
opAverage
opWeightedAverage
opVolAverage
opWeightedVolAverage
opVolIntegrate
opMin
opMax
opCoV
Definition at line 245 of file volRegion.H.
Constructor & Destructor Documentation
volRegion (const word & name, const Time & runTime, const dictionary & dict)
Construct from name, Time and dictionary.
Definition at line 207 of file volRegion.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::read().
Referenced by volRegion::writeFileHeader().
volRegion (const word & name, const objectRegistry & obr, const dictionary & dict)
Construct from name, objectRegistry and dictionary.
Definition at line 232 of file volRegion.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::read().
~volRegion () virtual
Destructor.
Definition at line 258 of file volRegion.C.
References volRegion::read().
Member Function Documentation
void initialise (const dictionary & dict) protected
Initialise, e.g. cell addressing.
Definition at line 144 of file volRegion.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::name(), Foam::nl, dictionary::readIfPresent(), Foam::type(), and volRegion::writeFileHeader().
Referenced by NamedEnum< Enum, nEnum >::names().
bool validField (const word & fieldName) const protected
Return true if the field name is valid.
Definition at line 33 of file volRegionTemplates.C.
References volRegion::setFieldValues().
tmp<Field<Type> > setFieldValues (const word & fieldName, const bool mustGet = false) const protected
Insert field values into values list.
Referenced by volRegion::validField().
Type processValues (const Field< Type > & values, const scalarField & V, const scalarField & weightField) const protected
Apply the 'operation' to the values.
Definition at line 76 of file volRegionTemplates.C.
References Foam::cmptMag(), Foam::component(), Field< Type >::component(), Foam::max(), Foam::min(), Foam::setComponent(), List< Type >::size(), Foam::sqr(), Foam::sqrt(), Foam::sum(), volRegion::writeValues(), and Foam::Zero.
Referenced by volRegion::setFieldValues().
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from writeFile.
Definition at line 176 of file volRegion.C.
References Foam::endl(), forAll, Foam::tab, and volRegion::volRegion().
Referenced by volRegion::initialise().
TypeName ("volRegion")
Run-time type information.
const Foam::functionObjects::fieldValues::volRegion::regionTypes & regionType () const inline
Return the region type.
Definition at line 31 of file volRegionI.H.
References volRegion::regionType_.
const Foam::labelList & cellId () const inline
Return the local list of cell IDs.
Definition at line 38 of file volRegionI.H.
References volRegion::cellId_.
bool writeValues (const word & fieldName)
Templated helper function to output field values.
Definition at line 159 of file volRegionTemplates.C.
References Foam::endl(), volRegion::filterField(), Log, mesh, List< Type >::size(), Foam::tab, and regIOobject::write().
Referenced by volRegion::processValues().
tmp<Field<Type> > filterField (const Field< Type > & field) const
Filter a field according to cellIds.
Referenced by volRegion::writeValues().
bool read (const dictionary & dict) virtual
Read from dictionary.
Reimplemented from fieldValue.
Definition at line 265 of file volRegion.C.
References fieldValue::read().
Referenced by volRegion::~volRegion().
bool write () virtual
Calculate and write.
Reimplemented from fieldValue.
Definition at line 278 of file volRegion.C.
References Foam::endl(), forAll, Log, UPstream::master(), Foam::tab, WarningInFunction, and fieldValue::write().
Foam::tmp<Foam::Field<Type> > setFieldValues (const word & fieldName, const bool mustGet) const
Definition at line 51 of file volRegionTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and volRegion::processValues().
Foam::tmp<Foam::Field<Type> > filterField (const Field< Type > & field) const
Definition at line 221 of file volRegionTemplates.C.
Member Data Documentation
const Foam::NamedEnum< Foam::functionObjects::fieldValues::volRegion::regionTypes, 2 > regionTypeNames_ static
region type names
Definition at line 241 of file volRegion.H.
Referenced by NamedEnum< Enum, nEnum >::names().
const Foam::NamedEnum< Foam::functionObjects::fieldValues::volRegion::operationType, 11 > operationTypeNames_ static
Operation type names.
Definition at line 261 of file volRegion.H.
Referenced by NamedEnum< Enum, nEnum >::names().
regionTypes regionType_ protected
region type
Definition at line 283 of file volRegion.H.
Referenced by volRegion::regionType().
operationType operation_ protected
Operation to apply to values.
Definition at line 286 of file volRegion.H.
label nCells_ protected
Global number of cells.
Definition at line 289 of file volRegion.H.
labelList cellId_ protected
Local list of cell IDs.
Definition at line 292 of file volRegion.H.
Referenced by volRegion::cellId().
word weightFieldName_ protected
Weight field name - only used for opWeightedAverage mode.
Definition at line 295 of file volRegion.H.
scalar volume_ protected
Volume of the volRegion.
Definition at line 298 of file volRegion.H.
bool writeVolume_ protected
Optionally write the volume of the volRegion.
Definition at line 301 of file volRegion.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldValues/volRegion/volRegion.H
src/functionObjects/field/fieldValues/volRegion/volRegion.C
src/functionObjects/field/fieldValues/volRegion/volRegionI.H
src/functionObjects/field/fieldValues/volRegion/volRegionTemplates.C