OpenFOAM: IOstream::versionNumber Class Reference
IOstream::versionNumber Class Reference
Version number type.
Public Member Functions
versionNumber (const scalar num)
Construct from number.
versionNumber (Istream &is)
Construct from Istream.
int numberToIndex (const scalar num) const
Convert a version number into an index.
int majorVersion () const
Return major version.
int minorVersion () const
Return minor version.
string str () const
Return the versionNumber as a character string.
bool operator== (const versionNumber &vn)
Are these versionNumbers the same?
bool operator!= (const versionNumber &vn)
Are these versionNumbers different?
bool operator< (const versionNumber &vn)
Is this version older than the one given.
bool operator<= (const versionNumber &vn)
Is this version the same as or older than the one given.
bool operator> (const versionNumber &vn)
Is this version newer than the one given.
bool operator>= (const versionNumber &vn)
This version the same as or newer than the one given.
Friends
Ostream & operator<< (Ostream &os, const versionNumber &vn)
Ostream operator.
Detailed Description
Version number type.
Definition at line 96 of file IOstream.H.
Constructor & Destructor Documentation
versionNumber (const scalar num) inline
Construct from number.
Definition at line 110 of file IOstream.H.
versionNumber (Istream & is) inline
Construct from Istream.
Definition at line 117 of file IOstream.H.
Member Function Documentation
int numberToIndex (const scalar num) const inline
Convert a version number into an index.
Definition at line 127 of file IOstream.H.
int majorVersion () const inline
Return major version.
Definition at line 133 of file IOstream.H.
Referenced by IOstream::versionNumber::minorVersion().
int minorVersion () const inline
Return minor version.
Definition at line 139 of file IOstream.H.
References IOstream::versionNumber::majorVersion(), and IOstream::versionNumber::str().
Foam::string str () const
Return the versionNumber as a character string.
Definition at line 116 of file IOstream.C.
References Foam::fixed().
Referenced by IOstream::versionNumber::minorVersion(), and Foam::operator<<().
bool operator== (const versionNumber & vn) inline
Are these versionNumbers the same?
Definition at line 151 of file IOstream.H.
bool operator!= (const versionNumber & vn) inline
Are these versionNumbers different?
Definition at line 157 of file IOstream.H.
bool operator< (const versionNumber & vn) inline
Is this version older than the one given.
Definition at line 163 of file IOstream.H.
bool operator<= (const versionNumber & vn) inline
Is this version the same as or older than the one given.
Definition at line 169 of file IOstream.H.
bool operator> (const versionNumber & vn) inline
Is this version newer than the one given.
Definition at line 175 of file IOstream.H.
bool operator>= (const versionNumber & vn) inline
This version the same as or newer than the one given.
Definition at line 181 of file IOstream.H.
References IOstream::versionNumber::operator<<.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const versionNumber & vn) friend
Ostream operator.
Referenced by IOstream::versionNumber::operator>=(), and IOstream::unsetf().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.H
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.C