OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallShearStress Class Reference
FunctionObjects » Forces function objects
This function object evaluates and outputs the shear stress at wall patches. The result is written as a volVectorField to time directories as field 'wallShearStress'.
Public Member Functions
TypeName ("wallShearStress")
Runtime type information.
wallShearStress (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~wallShearStress ()
Destructor.
virtual const word & name () const
Return name of the set of wallShearStress.
virtual void read (const dictionary &)
Read the wallShearStress data.
virtual void execute ()
Execute, currently does nothing.
virtual void end ()
Execute at the final time-loop, currently does nothing.
virtual void timeSet ()
Called when time was set at the end of the Time::operator++.
virtual void write ()
Calculate the wallShearStress and write.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for changes of mesh.
Public Member Functions inherited from functionObjectFiles
functionObjectFiles (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
functionObjectFiles (const objectRegistry &obr, const word &prefix, const word &name)
Construct from components.
functionObjectFiles (const objectRegistry &obr, const word &prefix, const wordList &names)
Construct from components.
virtual ~functionObjectFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
OFstream & file ()
Return access to the file (if only 1)
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from functionObjectFile
functionObjectFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry.
virtual ~functionObjectFile ()
Destructor.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Member Functions
static bool viable (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Return true if the construction of this functionObject is viable.
Protected Member Functions
virtual void writeFileHeader (const label i)
File header information.
void calcShearStress (const fvMesh &mesh, const volSymmTensorField &Reff, volVectorField &shearStress)
Calculate the shear stress.
Protected Member Functions inherited from functionObjectFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
functionObjectFiles (const functionObjectFiles &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFiles &)
Disallow default bitwise assignment.
Protected Member Functions inherited from functionObjectFile
virtual void initStream (Ostream &os) const
Initialise the output stream for writing.
virtual fileName baseFileDir () const
Return the base directory for output.
virtual fileName baseTimeDir () const
Return the base directory for the current time value.
virtual Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
functionObjectFile (const functionObjectFile &)
Disallow default bitwise copy construct.
void operator= (const functionObjectFile &)
Disallow default bitwise assignment.
Protected Attributes
word name_
Name of this set of wallShearStress object.
const objectRegistry & obr_
Switch log_
Switch to send output to Info as well as to file.
labelHashSet patchSet_
Optional list of patches to process.
Protected Attributes inherited from functionObjectFile
const objectRegistry & obr_
Reference to the objectRegistry.
const word prefix_
Prefix.
Additional Inherited Members
Static Public Attributes inherited from functionObjectFile
static const word outputPrefix = "postProcessing"
Directory prefix.
static label addChars = 7
Additional characters for writing.
Detailed Description
This function object evaluates and outputs the shear stress at wall patches. The result is written as a volVectorField to time directories as field 'wallShearStress'.
where
= stress tensor
= patch normal vector (into the domain)
The shear stress (symmetrical) tensor field is retrieved from the turbulence model. All wall patches are included by default; to restrict the calculation to certain patches, use the optional 'patches' entry.
Example of function object specification:
    wallShearStress1
    {
        type        wallShearStress;
        functionObjectLibs ("libutilityFunctionObjects.so");
        ...
        patches     (".*Wall");
    }
Function object usage
Property Description Required Default value
type type name: wallShearStress yes
patches list of patches to process no all wall patches
Source files
wallShearStress.H
wallShearStress.C
IOwallShearStress.H
Definition at line 122 of file wallShearStress.H.
Constructor & Destructor Documentation
wallShearStress (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 98 of file wallShearStress.C.
References Foam::dimLength, Foam::dimTime, mesh, IOobject::NO_READ, IOobject::NO_WRITE, Foam::read(), Foam::sqr(), fvMesh::time(), Time::timeName(), Foam::type(), wallShearStress::viable(), and Foam::Zero.
~wallShearStress () virtual
Destructor.
Definition at line 156 of file wallShearStress.C.
Member Function Documentation
void writeFileHeader (const label i) protected virtual
File header information.
Reimplemented from functionObjectFile.
Definition at line 46 of file wallShearStress.C.
References wallShearStress::calcShearStress(), and Foam::endl().
void calcShearStress (const fvMesh & mesh, const volSymmTensorField & Reff, volVectorField & shearStress) protected
Calculate the shear stress.
Definition at line 59 of file wallShearStress.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), polyMesh::boundaryMesh(), Foam::endl(), forAllConstIter(), Foam::gMax(), Foam::gMin(), Foam::Info, fvMesh::magSf(), UPstream::master(), patchIdentifier::name(), patchi, fvMesh::Sf(), token::TAB, fvMesh::time(), and dimensioned< Type >::value().
Referenced by wallShearStress::writeFileHeader().
TypeName ("wallShearStress")
Runtime type information.
bool viable (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false) static
Return true if the construction of this functionObject is viable.
i.e. the prerequisites for construction are available
Definition at line 142 of file wallShearStress.C.
Referenced by wallShearStress::wallShearStress().
virtual const word& name () const inline virtual
Return name of the set of wallShearStress.
Definition at line 203 of file wallShearStress.H.
References wallShearStress::end(), wallShearStress::execute(), wallShearStress::name_, wallShearStress::read(), wallShearStress::timeSet(), and wallShearStress::write().
void read (const dictionary & dict) virtual
Read the wallShearStress data.
Definition at line 162 of file wallShearStress.C.
References Foam::endl(), forAll, forAllConstIter(), Foam::Info, HashSet< Key, Hash >::insert(), dictionary::lookupOrDefault(), Foam::nl, patchi, polyBoundaryMesh::patchSet(), Foam::type(), and WarningInFunction.
Referenced by wallShearStress::name().
void execute () virtual
Execute, currently does nothing.
Definition at line 216 of file wallShearStress.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, objectRegistry::foundObject(), Foam::Info, objectRegistry::lookupObject(), Foam::nl, turbulenceModel::propertiesName, Foam::type(), and functionObjectFiles::write().
Referenced by wallShearStress::name().
void end () virtual
Execute at the final time-loop, currently does nothing.
Definition at line 260 of file wallShearStress.C.
Referenced by wallShearStress::name().
void timeSet () virtual
Called when time was set at the end of the Time::operator++.
Definition at line 266 of file wallShearStress.C.
Referenced by wallShearStress::name().
void write () virtual
Calculate the wallShearStress and write.
Reimplemented from functionObjectFiles.
Definition at line 270 of file wallShearStress.C.
References Foam::endl(), Foam::Info, IOobject::name(), Foam::nl, Foam::type(), functionObjectFiles::write(), and regIOobject::write().
Referenced by wallShearStress::name().
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update for changes of mesh.
Definition at line 224 of file wallShearStress.H.
virtual void movePoints (const polyMesh &) inline virtual
Update for changes of mesh.
Definition at line 228 of file wallShearStress.H.
Member Data Documentation
word name_ protected
Name of this set of wallShearStress object.
Definition at line 131 of file wallShearStress.H.
Referenced by wallShearStress::name().
const objectRegistry& obr_ protected
Definition at line 133 of file wallShearStress.H.
Switch log_ protected
Switch to send output to Info as well as to file.
Definition at line 136 of file wallShearStress.H.
labelHashSet patchSet_ protected
Optional list of patches to process.
Definition at line 139 of file wallShearStress.H.
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/forces/wallShearStress/wallShearStress.H
src/postProcessing/functionObjects/forces/wallShearStress/wallShearStress.C