OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Function Documentation
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm:: ddtrho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U = =fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple. momentumPredictor())
Definition at line 16 of file UEqn.H.
References fvOptions, ghf, Foam::magSqr(), mesh, p_rgh, Foam::fvc::reconstruct(), rho, Foam::fvc::snGrad(), solve(), U, and UEqn().