OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
volVectorField HbyA ("HbyA", U)
UEqn clear ()
if (simple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
if (!simple.transonic())
Variables
HbyA = rAU*UEqn().H()
bool closedVolume = false
else
U = HbyA - rAU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
volVectorField HbyA ("HbyA" , U)
UEqn clear ()
if (simple. transonic())
Definition at line 10 of file pEqn.H.
References Foam::fvc::div(), fvOptions, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, MRF, p, phi, phid(), pRefCell, pRefValue, psi, rAU(), rho, and simple.
MRF makeRelative (fvc:: interpolaterho, phiHbyA)
while (simple. correctNonOrthogonal())
Definition at line 56 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, phiHbyA, pRefCell, pRefValue, psi, rAU(), rho, and simple.
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
Definition at line 89 of file pEqn.H.
References Foam::fvc::domainIntegrate(), initialMass, p, and psi.
if (!simple. transonic())
Definition at line 99 of file pEqn.H.
References rho.
Variable Documentation
HbyA = rAU*UEqn().H()
Definition at line 4 of file pEqn.H.
closedVolume = false
Definition at line 8 of file pEqn.H.
else
Initial value:
{
        surfaceScalarField phiHbyA
        (
            "phiHbyA",
            fvc::interpolate(rho*HbyA) & mesh.Sf()
        )
Definition at line 45 of file pEqn.H.
U = HbyA - rAU*fvc::grad(p)
Definition at line 83 of file pEqn.H.
rho = thermo.rho()
Definition at line 95 of file pEqn.H.