OpenFOAM-dev: Wallis Class Reference 2
Wallis Class Reference
Wallis compressibility model.
Public Member Functions
TypeName ("Wallis")
Runtime type information.
Wallis (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Construct from components.
~Wallis ()
Destructor.
void correct ()
Correct the Wallis compressibility.
bool read (const dictionary &compressibilityProperties)
Read transportProperties dictionary.
Public Member Functions inherited from barotropicCompressibilityModel
TypeName ("barotropicCompressibilityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, barotropicCompressibilityModel, dictionary,(const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName),(compressibilityProperties, gamma, psiName))
barotropicCompressibilityModel (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Construct from components.
virtual ~barotropicCompressibilityModel ()
Destructor.
const dictionary & compressibilityProperties () const
Return the phase transport properties dictionary.
const volScalarField & psi () const
Return the compressibility.
Additional Inherited Members
Static Public Member Functions inherited from barotropicCompressibilityModel
static autoPtr< barotropicCompressibilityModel > New (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Return a reference to the selected compressibility model.
Protected Member Functions inherited from barotropicCompressibilityModel
barotropicCompressibilityModel (const barotropicCompressibilityModel &)
Disallow copy construct.
void operator= (const barotropicCompressibilityModel &)
Disallow default bitwise assignment.
Protected Attributes inherited from barotropicCompressibilityModel
dictionary compressibilityProperties_
volScalarField psi_
const volScalarField & gamma_
Detailed Description
Wallis compressibility model.
Source files
Wallis.H
Wallis.C
Definition at line 51 of file Wallis.H.
Constructor & Destructor Documentation
Wallis (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi")
Construct from components.
Definition at line 48 of file Wallis.C.
References correct.
~Wallis () inline
Destructor.
Definition at line 82 of file Wallis.H.
References Wallis::correct(), and Wallis::read().
Member Function Documentation
TypeName ("Wallis")
Runtime type information.
void correct () virtual
Correct the Wallis compressibility.
Implements barotropicCompressibilityModel.
Definition at line 86 of file Wallis.C.
References Wallis::read().
Referenced by Wallis::~Wallis().
bool read (const dictionary & compressibilityProperties) virtual
Read transportProperties dictionary.
Implements barotropicCompressibilityModel.
Definition at line 95 of file Wallis.C.
References barotropicCompressibilityModel::read().
Referenced by Wallis::correct(), and Wallis::~Wallis().
The documentation for this class was generated from the following files:
src/thermophysicalModels/barotropicCompressibilityModel/Wallis/Wallis.H
src/thermophysicalModels/barotropicCompressibilityModel/Wallis/Wallis.C