OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
tmp< fvVectorMatrix > UEqn (fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==fvOptions(rho, U))
UEqn ().relax()
fvOptions constrain (UEqn())
if (simple.momentumPredictor())
Function Documentation
MRF correctBoundaryVelocity (U)
tmp<fvVectorMatrix> UEqn (fvm:: divphi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U = =fvOptions(rho, U))
UEqn ()
fvOptions constrain (UEqn())
if (simple. momentumPredictor())
Definition at line 18 of file UEqn.H.
References fvOptions, ghf, mesh, p_rgh, Foam::fvc::reconstruct(), rho, Foam::fvc::snGrad(), solve(), U, and UEqn().