OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA ("HbyA", U)
if (pimple.nCorrPISO()<=1)
surfaceScalarField phiHbyA ("phiHbyA",(fvc::interpolate(HbyA)&mesh.Sf())+rAUf *fvc::ddtCorr(U, Uf))
MRF makeRelative (phiHbyA)
if (p_gh.needReference())
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_gh.boundaryField(),(phiHbyA.boundaryField() -(mesh.Sf().boundaryField()&U.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
while (pimple.correctNonOrthogonal())
surfaceVectorField n (mesh.Sf()/mesh.magSf())
Variables
HbyA = rAU*UEqn().H()
Uf = n*(phi/mesh.magSf() - (n & Uf))
p = p_gh + (g & mesh.C())
Function Documentation
surfaceScalarField rAUf ("rAUf" , fvc:: interpolaterAU)
volVectorField HbyA ("HbyA" , U)
if (pimple.nCorrPISO()<= 1)
Definition at line 8 of file pEqn.H.
References UEqn().
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::interpolate(HbyA)&mesh.Sf())+rAUf *fvc::ddtCorr(U, Uf))
MRF makeRelative (phiHbyA)
if (p_gh. needReference())
Definition at line 22 of file pEqn.H.
References adjustPhi(), Foam::fvc::makeAbsolute(), makeRelative(), phiHbyA, and U.
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_gh. boundaryField(), (phiHbyA.boundaryField() -(mesh.Sf().boundaryField()&U.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
while (pimple. correctNonOrthogonal())
Definition at line 40 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::grad(), HbyA, Foam::fvc::laplacian(), mesh, phi, phiHbyA, pimple, rAU(), rAUf(), and U.
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Variable Documentation
HbyA = rAU*UEqn().H()
Definition at line 6 of file pEqn.H.
Uf = n*(phi/mesh.magSf() - (n & Uf))
Definition at line 69 of file pEqn.H.
p = p_gh + (g & mesh.C())
Definition at line 75 of file pEqn.H.