OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallLayerCells Class Reference
After construction is a list of <refineCell> of cells within a certain distance to the wall and with the wall normal direction.
Public Member Functions
ClassName ("wallLayerCells")
Runtime type information.
wallLayerCells (const polyMesh &mesh, const List< word > &patchNames, const label nLayers)
Construct from components.
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Public Member Functions inherited from List< refineCell >
label size () const
Return the number of elements in the UList.
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const refineCell &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< refineCell > &)
Copy constructor.
List (const Xfer< List< refineCell >> &)
Construct by transferring the parameter contents.
List (List< refineCell > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< refineCell > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< refineCell, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< refineCell > &)
Construct as copy of PtrList<T>
List (const SLList< refineCell > &)
Construct as copy of SLList<T>
List (const UIndirectList< refineCell > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< refineCell > &)
Construct as copy of BiIndirectList<T>
List (Istream &)
Construct from Istream.
autoPtr< List< refineCell > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const refineCell &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const refineCell &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const refineCell &)
Append an element at the end of the list.
void append (const UList< refineCell > &)
Append a List at the end of this list.
void append (const UIndirectList< refineCell > &)
Append a UIndirectList at the end of this list.
void transfer (List< refineCell > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< refineCell, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< refineCell > &)
Transfer the contents of the argument List into this list.
Xfer< List< refineCell > > xfer ()
Transfer contents to the Xfer container.
refineCell & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< refineCell > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< refineCell > &)
Assignment from UList operator. Takes linear time.
void operator= (const List< refineCell > &)
Assignment operator. Takes linear time.
void operator= (const SLList< refineCell > &)
Assignment from SLList operator. Takes linear time.
void operator= (const UIndirectList< refineCell > &)
Assignment from UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< refineCell > &)
Assignment from BiIndirectList operator. Takes linear time.
void operator= (const refineCell &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1).
void checkSize (const label size) const
Check size is within valid range (0 ... size).
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1).
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero).
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Additional Inherited Members
Public Types inherited from List< refineCell >
typedef SubList< refineCell > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
Is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
Convert eVert to edge label.
static label getVertex (const primitiveMesh &mesh, const label eVert)
Convert eVert to vertex label.
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointI to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Static Public Member Functions inherited from List< refineCell >
static const List< refineCell > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< refineCell >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
After construction is a list of <refineCell> of cells within a certain distance to the wall and with the wall normal direction.
Source files
wallLayerCells.H
wallLayerCells.C
Definition at line 52 of file wallLayerCells.H.
Constructor & Destructor Documentation
wallLayerCells (const polyMesh & mesh, const List< word > & patchNames, const label nLayers)
Construct from components.
Definition at line 65 of file wallLayerCells.C.
References MeshWave< Type, TrackingData >::allCellInfo(), MeshWave< Type, TrackingData >::allFaceInfo(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), polyMesh::boundaryMesh(), MeshWave< Type, TrackingData >::data(), Foam::endl(), f(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), polyMesh::faces(), forAll, InfoInFunction, MeshWave< Type, TrackingData >::iterate(), Foam::name(), wallNormalInfo::normal(), polyMesh::points(), List< T >::size(), PtrList< T >::size(), polyPatch::start(), wallNormalInfo::valid(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Member Function Documentation
ClassName ("wallLayerCells")
Runtime type information.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/wallLayerCells/wallLayerCells.H
src/dynamicMesh/meshCut/wallLayerCells/wallLayerCells.C