OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
thermo rho ()-
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
surfaceScalarField phig (-rAUf *ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",((fvc::interpolate(rho *HbyA)&mesh.Sf()) +rAUf *fvc::ddtCorr(rho, U, phi))+phig)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryField(),(phiHbyA.boundaryField() -MRF.relative(mesh.Sf().boundaryField()&U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA)==fvOptions(psi, p_rgh, rho.name()))
while (pimple.correctNonOrthogonal())
if (thermo.dpdt())
Variables
HbyA = rAU*UEqn.H()
p = p_rgh + rho*gh
Function Documentation
thermo rho ()
volScalarField rAU (1.0/UEqn. A())
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA" , U)
surfaceScalarField phig (-rAUf *ghf * fvc::snGradrho)*mesh.magSf()
surfaceScalarField phiHbyA ("phiHbyA" , ((fvc::interpolate(rho *HbyA)&mesh.Sf()) +rAUf *fvc::ddtCorr(rho, U, phi))+ phig)
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryField(), (phiHbyA.boundaryField() -MRF.relative(mesh.Sf().boundaryField()&U.boundaryField()) *rho.boundaryField())/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA) = =fvOptions(psi, p_rgh, rho.name()))
while (pimple. correctNonOrthogonal())
Definition at line 47 of file pEqn.H.
References fvOptions, HbyA, Foam::fvc::laplacian(), Foam::magSqr(), mesh, p_rghDDtEqn(), phi, phig(), phiHbyA, pimple, rAU(), rAUf(), Foam::fvc::reconstruct(), and U.
if (thermo. dpdt())
Definition at line 79 of file pEqn.H.
References Foam::fvc::ddt(), dpdt, and p.
Variable Documentation
HbyA = rAU*UEqn.H()
Definition at line 12 of file pEqn.H.
p = p_rgh + rho*gh
Definition at line 74 of file pEqn.H.