OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
wallBoundedStreamLine Class Reference
FunctionObjects » Field function objects
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
Public Member Functions
TypeName ("wallBoundedStreamLine")
Runtime type information.
wallBoundedStreamLine (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~wallBoundedStreamLine ()
Destructor.
virtual bool read (const dictionary &)
Read the field average data.
virtual bool execute (const bool postProcess=false)
Do nothing.
virtual bool write (const bool postProcess=false)
Calculate and write the wall-bounded streamlines.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for mesh point-motion.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &t, const dictionary &dict),(name, t, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool timeSet ()
Called when time was set at the end of the Time::operator++.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Static Public Attributes inherited from functionObject
static int debug
Detailed Description
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
Example of function object specification:
wallBoundedStreamLine1
{
    type            wallBoundedStreamLine;
    libs ("libfieldFunctionObjects.so");
    ...
    setFormat       vtk;
    UName           UNear;
    trackForward    yes;
    fields
    (
        UNear
        p
    );
    lifeTime        10000;
    trackLength     1e-3;
    nSubCycle       5;
    cloudName       particleTracks;
    seedSampleSet   patchSeed;
    patchSeedCoeffs
    {
        type        patchSeed;
        patches     (wall);
        axis        x;
        maxPoints   20000;
    }
}
Function object usage
Property Description Required Default value
type type name: wallBoundedStreamLine yes
setFormat output data type yes
UName tracking velocity field name yes
fields fields to sample yes
lifetime maximum number of particle tracking steps yes
trackLength tracking segment length no
nSubCycle number of tracking steps per cell no
cloudName cloud name to use yes
seedSampleSet seeding method (see below) yes
Where seedSampleSet is typically one of
uniform : uniform particle seeding
cloud : cloud of points
patchSeed : seeding via patch faces
triSurfaceMeshPointSet : points according to a tri-surface mesh
Note
When specifying the track resolution, the trackLength OR nSubCycle option should be used
See also
Foam::functionObject Foam::functionObjects::timeControl Foam::sampledSet Foam::streamLine
Source files
wallBoundedStreamLine.H
wallBoundedStreamLine.C
Definition at line 197 of file wallBoundedStreamLine.H.
Constructor & Destructor Documentation
wallBoundedStreamLine (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 406 of file wallBoundedStreamLine.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::read().
~wallBoundedStreamLine () virtual
Destructor.
Definition at line 434 of file wallBoundedStreamLine.C.
Member Function Documentation
TypeName ("wallBoundedStreamLine")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the field average data.
Implements functionObject.
Definition at line 440 of file wallBoundedStreamLine.C.
References Foam::abort(), primitiveMesh::cells(), polyMeshTetDecomposition::checkFaceTets(), HashTable< T, Key, Hash >::clear(), Foam::e, HashTableCore::end(), Foam::endl(), wallBoundedStreamLine::execute(), Foam::exit(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInFunction, HashTable< T, Key, Hash >::find(), Foam::findIndex(), forAll, forAllConstIter(), dictionary::found(), Foam::Info, HashTable< T, Key, Hash >::insert(), IOWarningInFunction, dictionary::lookup(), dictionary::lookupOrDefault(), polyMeshTetDecomposition::minTetQuality, MeshObject< polyMesh, GeometricMeshObject, meshSearchMeshObject >::New(), writer< Type >::New(), sampledSet::New(), face::nextLabel(), primitiveMesh::nFaces(), Foam::nl, Foam::returnReduce(), dictionary::subDict(), Foam::type(), and WarningInFunction.
bool execute (const bool postProcess = false) virtual
Do nothing.
Implements functionObject.
Definition at line 592 of file wallBoundedStreamLine.C.
Referenced by wallBoundedStreamLine::read().
bool write (const bool postProcess = false) virtual
Calculate and write the wall-bounded streamlines.
Implements functionObject.
Definition at line 600 of file wallBoundedStreamLine.C.
References polyMesh::defaultRegion, mapDistributeBase::distribute(), Foam::endl(), forAll, Foam::Info, UPstream::master(), Foam::mkDir(), n, Foam::name(), fvMesh::name(), Foam::nl, UPstream::nProcs(), UPstream::parRun(), fileName::path(), Time::path(), UPstream::scheduled, DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::setSize(), List< T >::size(), objectRegistry::time(), fvMesh::time(), Time::timeName(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer(), wallBoundedStreamLine::updateMesh(), Ostream::write(), and List< T >::xfer().
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Reimplemented from functionObject.
Definition at line 841 of file wallBoundedStreamLine.C.
References mapPolyMesh::mesh(), wallBoundedStreamLine::movePoints(), and Foam::read().
Referenced by wallBoundedStreamLine::write().
void movePoints (const polyMesh & mesh) virtual
Update for mesh point-motion.
Reimplemented from functionObject.
Definition at line 855 of file wallBoundedStreamLine.C.
References Foam::read().
Referenced by wallBoundedStreamLine::updateMesh().
The documentation for this class was generated from the following files:
src/postProcessing/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLine.H
src/postProcessing/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLine.C