OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
rho relax ()
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple.nCorrPISO()<=1)
if (pimple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p, rho, U, phiHbyA, rhorAUf, MRF)
while (pimple.correctNonOrthogonal())
Variables
rho = thermo.rho()
else
Function Documentation
rho relax ()
volScalarField rAU (1.0/UEqn. A())
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple.nCorrPISO()<= 1)
Definition at line 10 of file pEqn.H.
References tUEqn().
if (pimple. transonic())
Definition at line 15 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::ddtCorr(), Foam::fvc::div(), Foam::fvc::flux(), fvOptions, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), makeRelative(), mesh, MRF, p, phi, phid(), pimple, psi, rho, rhorAUf(), rhoUf, and U.
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure (p , rho , U , phiHbyA , rhorAUf , MRF)
while (pimple. correctNonOrthogonal())
Definition at line 65 of file pEqn.H.
References Foam::fvc::absolute(), Foam::fvc::ddt(), Foam::fvc::div(), dpdt, Foam::endl(), fvOptions, Foam::fvc::grad(), Foam::Info, Foam::MULES::interpolate(), Foam::fvc::laplacian(), Foam::magSqr(), Foam::max(), mesh, Foam::fvc::meshPhi(), Foam::min(), n(), p, phi, pimple, psi, rAU(), rho, rhoMax(), rhoMin(), rhorAUf(), rhoUf, thermo, and U.
Variable Documentation
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        fvc::flux(rho*HbyA)
      + rhorAUf*fvc::ddtCorr(rho, U, rhoUf)
    )
Definition at line 51 of file pEqn.H.