OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
tmp< fvVectorMatrix > UEqn (fvm::ddt(U)+fvm::div(phi, U)+MRF.DDt(U)+turbulence->divDevReff(U)==fvOptions(U))
UEqn ().relax()
fvOptions constrain (UEqn())
if (pimple.momentumPredictor())
Function Documentation
MRF correctBoundaryVelocity (U)
tmp<fvVectorMatrix> UEqn (fvm::ddt(U)+fvm::div(phi, U)+MRF.DDt(U)+turbulence->divDevReff(U) = =fvOptions(U))
UEqn ()
fvOptions constrain (UEqn())
if (pimple. momentumPredictor())
Definition at line 16 of file UEqn.H.
References fvOptions, Foam::fvc::grad(), solve(), U, and UEqn().