OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
rho relax ()
volScalarField rAU ("rAU", 1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
tUEqn clear ()
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(rho *HbyA))
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
while (simple.correctNonOrthogonal())
if (closedVolume)
Variables
bool closedVolume = adjustPhi(phiHbyA, U, p_rgh)
phiHbyA = phig
p = p_rgh + rho*gh
rho = thermo.rho()
Function Documentation
rho relax ()
volScalarField rAU ("rAU" , 1.0/UEqn. A())
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
tUEqn clear ()
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho)*mesh.magSf()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(rho *HbyA))
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
while (simple. correctNonOrthogonal())
Definition at line 27 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::getRefCellValue(), HbyA, Foam::fvc::laplacian(), p_rgh, phi, phig(), phiHbyA, pRefCell, rAU(), Foam::fvc::reconstruct(), rhorAUf(), simple, and U.
if (closedVolume)
Definition at line 59 of file pEqn.H.
References Foam::fvc::domainIntegrate(), gh, initialMass, p, p_rgh, psi, and rho.
Variable Documentation
bool closedVolume = adjustPhi(phiHbyA, U, p_rgh)
Definition at line 20 of file pEqn.H.
phiHbyA = phig
Definition at line 22 of file pEqn.H.
p = p_rgh + rho*gh
Definition at line 55 of file pEqn.H.
rho = thermo.rho()
Definition at line 66 of file pEqn.H.