OpenFOAM: applications/solvers/multiphase/potentialFreeSurfaceFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_gh))
if (pimple.nCorrPISO()<=1)
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+rAUf *fvc::ddtCorr(U, phi))
MRF makeRelative (phiHbyA)
adjustPhi (phiHbyA, U, p_gh)
constrainPressure (p_gh, U, phiHbyA, rAUf)
while (pimple.correctNonOrthogonal())
p_gh relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
p = p_gh + (g & mesh.C())
U = HbyA - rAU*fvc::grad(p_gh)
Function Documentation
volScalarField rAU (1.0/UEqn. A())
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_gh))
if (pimple.nCorrPISO()<= 1)
Definition at line 5 of file pEqn.H.
References adjustPhi(), constrainPressure(), Foam::fvc::ddtCorr(), Foam::fvc::flux(), HbyA, MRF, phi, phiHbyA, rAUf(), tUEqn(), and U.
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+rAUf *fvc::ddtCorr(U, phi))
MRF makeRelative (phiHbyA)
adjustPhi (phiHbyA , U , p_gh)
constrainPressure (p_gh , U , phiHbyA , rAUf)
while (pimple. correctNonOrthogonal())
Definition at line 24 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), mesh, phi, pimple, and rAUf().
p_gh relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
Variable Documentation
p = p_gh + (g & mesh.C())
Definition at line 46 of file pEqn.H.
U = HbyA - rAU*fvc::grad(p_gh)
Definition at line 48 of file pEqn.H.