OpenFOAM: applications/solvers/combustion/coldEngineFoam/createFieldRefs.H File Reference
createFieldRefs.H File Reference
Variables
const volScalarField & psi = thermo.psi()
const volScalarField & T = thermo.T()
Variable Documentation
const volScalarField& psi = thermo.psi()
Definition at line 1 of file createFieldRefs.H.
Referenced by Amultiplier< Type, LUType >::addAmul(), SemiImplicitSource< Type >::addSup(), LduMatrix< Type, DType, LUType >::Amul(), lduMatrix::Amul(), LduMatrix< Type, DType, LUType >::asymmetric(), lduMatrix::asymmetric(), rotorDiskSource::constructGeometry(), Foam::fvc::DDt(), Foam::MULES::explicitSolve(), for(), if(), Foam::MULES::implicitSolve(), lduMatrix::solver::interfaces(), lduMatrix::smoother::interfaces(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), LduMatrix< Type, DType, LUType >::solver::matrix(), LduMatrix< Type, DType, LUType >::smoother::matrix(), steadyStateDdtScheme< Type >::mesh(), EulerDdtScheme< Type >::mesh(), boundedDdtScheme< Type >::mesh(), backwardDdtScheme< Type >::mesh(), CoEulerDdtScheme< Type >::mesh(), SLTSDdtScheme< Type >::mesh(), localEulerDdtScheme< Type >::mesh(), interpolation< Type >::New(), CrankNicolsonDdtScheme< Type >::ocCoeff(), fixedTrim::read(), diagonalSolver::read(), LduMatrix< Type, DType, LUType >::residual(), lduMatrix::residual(), fvMatrix< Type >::setValuesFromList(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solveSegregated(), targetCoeffTrim::thetag(), LduMatrix< Type, DType, LUType >::Tmul(), lduMatrix::Tmul(), EulerCoordinateRotation::transformVector(), while(), PBiCCCG< Type, DType, LUType >::~PBiCCCG(), PBiCG::~PBiCG(), PBiCICG< Type, DType, LUType >::~PBiCICG(), PCG::~PCG(), PCICG< Type, DType, LUType >::~PCICG(), and smoothSolver::~smoothSolver().
const volScalarField& T = thermo.T()
Definition at line 2 of file createFieldRefs.H.
Referenced by mapDistributeBase::accessAndFlip(), UList< T >::byteSize(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), SprayParcel< ParcelType >::chi(), Pstream::combineGather(), Pstream::combineScatter(), MixedDiffuseSpecular< CloudType >::correct(), particle< Type >::correctAfterParallelTransfer(), PengRobinsonGas< Specie >::cp(), PengRobinsonGas< Specie >::cpMcv(), Foam::createWithValues(), UList< T >::deepCopy(), mapDistributeBase::distribute(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), Pstream::exchange(), FixedList< T, Size >::FixedList(), mapDistributeBase::flipAndCombine(), forAll(), forAllIter(), rigidBodyModel::forwardDynamics(), meshRefinement::gAverage(), heThermo< BasicThermo, MixtureType >::he(), if(), Dual< Type >::interpolateGrad(), thermo< Thermo, Type >::K(), hPowerThermo< EquationOfState >::limit(), LList< LListBase, T >::LList(), dictionary::lookupOrDefault(), Moment< Type >::Moment(), sutherlandTransport< Thermo >::mu(), radiationModel::New(), Foam::NullObjectPtr(), Foam::NullObjectRef(), LandauTellerReactionRate::operator()(), JanevReactionRate::operator()(), StaticHashTable< T, Key, Hash >::operator()(), UList< T >::operator=(), FixedList< T, Size >::operator==(), UList< T >::operator==(), StaticHashTable< T, Key, Hash >::operator[](), StaticHashTable< T, Key, Hash >::printInfo(), perfectFluid< Specie >::psi(), PengRobinsonGas< Specie >::psi(), PtrList< T >::read(), ThermoParcel< ParcelType >::readFields(), Foam::ReadHex(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), perfectFluid< Specie >::rho(), incompressiblePerfectGas< Specie >::rho(), PengRobinsonGas< Specie >::rho(), UPtrList< T >::set(), ode< ChemistryModel >::solve(), FixedList< T, Size >::swap(), FieldField< Field, Type >::T(), Field< Type >::T(), thermo< Thermo, Type >::TEa(), thermo< Thermo, Type >::TEs(), meshRefinement::testSyncBoundaryFaceList(), thermo< Thermo, Type >::THa(), thermo< Thermo, Type >::THs(), Foam::transformPoints(), meshRefinement::updateList(), HashPtrTable< T, Key, Hash >::write(), FixedList< T, Size >::writeEntry(), UList< T >::writeEntry(), ThermoParcel< ParcelType >::writeFields(), and PengRobinsonGas< Specie >::Z().