OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rho *rAU)*fvc::ddtCorr(U, phi))
adjustPhi (phiHbyA, U, p_rgh)
surfaceScalarField phig ((interface.surfaceTensionForce() -ghf *fvc::snGrad(rho))*rAUf *mesh.magSf())
constrainPressure (p_rgh, U, phiHbyA, rAUf)
while (pimple.correctNonOrthogonal())
if (p_rgh.needReference())
Variables
phiHbyA = phig
Pair< tmp< volScalarField > > vDotP = mixture->vDotP()
const volScalarField & vDotcP = vDotP[0]()
const volScalarField & vDotvP = vDotP[1]()
p == p_rgh + rho*gh
Function Documentation
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rho *rAU)*fvc::ddtCorr(U, phi))
adjustPhi (phiHbyA , U , p_rgh)
surfaceScalarField phig ((interface.surfaceTensionForce() -ghf *fvc::snGrad(rho))*rAUf *mesh.magSf())
constrainPressure (p_rgh , U , phiHbyA , rAUf)
while (pimple. correctNonOrthogonal())
Definition at line 30 of file pEqn.H.
References Foam::fvc::div(), fvOptions, gh, HbyA, Foam::fvc::laplacian(), mesh, mixture, p_rgh, phi, phig(), phiHbyA, pimple, pRefCell, pRefValue, rAUf(), Foam::fvc::reconstruct(), rho, Foam::fvc::Sp(), and U.
if (p_rgh. needReference())
Definition at line 55 of file pEqn.H.
References Foam::getRefCellValue(), gh, p, p_rgh, pRefCell, pRefValue, and rho.
Variable Documentation
phiHbyA = phig
Definition at line 21 of file pEqn.H.
Pair<tmp<volScalarField> > vDotP = mixture->vDotP()
Definition at line 26 of file pEqn.H.
const volScalarField& vDotcP = vDotP[0]()
Definition at line 27 of file pEqn.H.
const volScalarField& vDotvP = vDotP[1]()
Definition at line 28 of file pEqn.H.
p == p_rgh + rho*gh
Definition at line 53 of file pEqn.H.