OpenFOAM: ZoneMesh< ZoneType, MeshType > Class Template Reference
ZoneMesh< ZoneType, MeshType > Class Template Reference
A list of mesh zones.
Public Member Functions
ZoneMesh (const IOobject &, const MeshType &)
Read constructor given IOobject and a MeshType reference.
ZoneMesh (const IOobject &, const MeshType &, const label size)
Construct given size.
ZoneMesh (const IOobject &, const MeshType &, const PtrList< ZoneType > &)
Construct given a PtrList.
~ZoneMesh ()
Destructor.
const MeshType & mesh () const
Return the mesh reference.
const Map< label > & zoneMap () const
Map of zones containing zone index for all zoned elements.
label whichZone (const label objectIndex) const
Given a global object index, return the zone it is in.
wordList types () const
Return a list of zone types.
wordList names () const
Return a list of zone names.
labelList findIndices (const keyType &) const
Return zone indices for all matches.
label findIndex (const keyType &) const
Return zone index for the first match, return -1 if not found.
label findZoneID (const word &zoneName) const
Find zone index given a name.
PackedBoolList findMatching (const keyType &) const
Mark cells that match the zone specification.
void clearAddressing ()
Clear addressing.
void clear ()
Clear the zones.
bool checkDefinition (const bool report=false) const
Check zone definition. Return true if in error.
bool checkParallelSync (const bool report=false) const
Check whether all procs have all zones and in same order. Return.
void movePoints (const pointField &)
Correct zone mesh after moving points.
bool writeData (Ostream &) const
writeData member function required by regIOobject
const ZoneType & operator[] (const word &) const
Return const reference to ZoneType by name.
ZoneType & operator[] (const word &)
Return reference to ZoneType by name.
Public Member Functions inherited from PtrList< ZoneType >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< ZoneType > &)
Copy constructor.
PtrList (const PtrList< ZoneType > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< ZoneType >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< ZoneType > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< ZoneType > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (ZoneType *)
Append an element at the end of the list.
void append (const autoPtr< ZoneType > &)
void append (const tmp< ZoneType > &)
void transfer (PtrList< ZoneType > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< ZoneType > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< ZoneType > set (const label, ZoneType *)
Set element to given T* and return old element (can be nullptr)
autoPtr< ZoneType > set (const label, const autoPtr< ZoneType > &)
Set element to given autoPtr<T> and return old element.
autoPtr< ZoneType > set (const label, const tmp< ZoneType > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< ZoneType > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Friends
Ostream & operator (Ostream &, const ZoneMesh< ZoneType, MeshType > &)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from PtrList< ZoneType >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class ZoneType, class MeshType>
class Foam::ZoneMesh< ZoneType, MeshType >
A list of mesh zones.
Source files
ZoneMesh.H
ZoneMesh.C
Definition at line 39 of file cellZoneMeshFwd.H.
Constructor & Destructor Documentation
ZoneMesh (const IOobject & io, const MeshType & mesh)
Read constructor given IOobject and a MeshType reference.
Definition at line 137 of file ZoneMesh.C.
References Foam::read().
ZoneMesh (const IOobject & io, const MeshType & mesh, const label size)
Construct given size.
Definition at line 153 of file ZoneMesh.C.
References Foam::read().
ZoneMesh (const IOobject & io, const MeshType & mesh, const PtrList< ZoneType > & pzm)
Construct given a PtrList.
Definition at line 171 of file ZoneMesh.C.
References forAll, Foam::read(), PtrList< T >::set(), PtrList< T >::setSize(), and UPtrList< T >::size().
~ZoneMesh ()
Destructor.
Definition at line 198 of file ZoneMesh.C.
Member Function Documentation
const MeshType& mesh () const inline
Return the mesh reference.
Definition at line 127 of file ZoneMesh.H.
const Foam::Map< Foam::label > & zoneMap () const
Map of zones containing zone index for all zoned elements.
Return -1 if the object is not in the zone
Definition at line 208 of file ZoneMesh.C.
References ZoneMesh< ZoneType, MeshType >::whichZone().
Referenced by ZoneMesh< cellZone, polyMesh >::mesh().
Foam::label whichZone (const label objectIndex) const
Given a global object index, return the zone it is in.
If object does not belong to any zones, return -1
Definition at line 221 of file ZoneMesh.C.
References HashTableCore::end(), and HashTable< T, Key, Hash >::find().
Referenced by repatchPolyTopoChanger::changeAnchorPoint(), repatchPolyTopoChanger::changePatchID(), meshRefinement::checkZoneFaces(), meshRefinement::mergeBaffles(), polyMeshAdder::mergePoints(), ZoneMesh< cellZone, polyMesh >::mesh(), removeCells::setRefinement(), duplicatePoints::setRefinement(), perfectInterface::setRefinement(), tetDecomposer::setRefinement(), edgeCollapser::setRefinement(), and ZoneMesh< ZoneType, MeshType >::zoneMap().
Foam::wordList types () const
Return a list of zone types.
Definition at line 240 of file ZoneMesh.C.
References forAll, and UPtrList< T >::size().
Referenced by ZoneMesh< cellZone, polyMesh >::mesh().
Foam::wordList names () const
Return a list of zone names.
Definition at line 256 of file ZoneMesh.C.
References ZoneMesh< ZoneType, MeshType >::findIndices(), forAll, and UPtrList< T >::size().
Referenced by preserveFaceZonesConstraint::add(), preserveFaceZonesConstraint::apply(), meshRefinement::checkCoupledFaceZones(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), fvMeshDistribute::distribute(), ZoneMesh< cellZone, polyMesh >::mesh(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), cellTable::operator=(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), displacementLayeredMotionMotionSolver::solve(), and CellZoneInjection< CloudType >::updateMesh().
Foam::labelList findIndices (const keyType & key) const
Return zone indices for all matches.
Definition at line 273 of file ZoneMesh.C.
References ZoneMesh< ZoneType, MeshType >::findIndex(), Foam::findStrings(), forAll, keyType::isPattern(), Foam::name(), and List< T >::setSize().
Referenced by ZoneMesh< cellZone, polyMesh >::mesh(), and ZoneMesh< ZoneType, MeshType >::names().
Foam::label findIndex (const keyType & key) const
Return zone index for the first match, return -1 if not found.
Definition at line 306 of file ZoneMesh.C.
References UList< T >::empty(), Foam::findIndices(), ZoneMesh< ZoneType, MeshType >::findZoneID(), forAll, keyType::isPattern(), and Foam::name().
Referenced by ZoneMesh< ZoneType, MeshType >::findIndices(), ZoneMesh< cellZone, polyMesh >::mesh(), and sampledPlane::sampledPlane().
Foam::label findZoneID (const word & zoneName) const
Find zone index given a name.
Definition at line 341 of file ZoneMesh.C.
References Foam::endl(), ZoneMesh< ZoneType, MeshType >::findMatching(), forAll, InfoInFunction, and Foam::name().
Referenced by cellZoneSet::cellZoneSet(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), snappySnapDriver::doSnap(), FacePostProcessing< CloudType >::FacePostProcessing(), faceZoneSet::faceZoneSet(), ZoneMesh< ZoneType, MeshType >::findIndex(), snappySnapDriver::getZoneSurfacePoints(), interRegionExplicitPorositySource::initialise(), ZoneMesh< cellZone, polyMesh >::mesh(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), listPlusEqOp< T >::operator()(), pointZoneSet::pointZoneSet(), fvMeshDistribute::printCoupleInfo(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), displacementLayeredMotionMotionSolver::solve(), CellZoneInjection< CloudType >::updateMesh(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), and faceZoneSet::writeObject().
Foam::PackedBoolList findMatching (const keyType & key) const
Mark cells that match the zone specification.
Definition at line 370 of file ZoneMesh.C.
References Foam::findIndices(), and forAll.
Referenced by ZoneMesh< ZoneType, MeshType >::findZoneID(), ZoneMesh< cellZone, polyMesh >::mesh(), and sampledPlane::update().
void clearAddressing ()
Clear addressing.
Definition at line 387 of file ZoneMesh.C.
References Foam::deleteDemandDrivenData(), and forAll.
Referenced by polyMesh::clearAddressing(), interRegionExplicitPorositySource::initialise(), ZoneMesh< cellZone, polyMesh >::mesh(), Foam::polyMeshZipUpCells(), polyMesh::updateMesh(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), and faceZoneSet::writeObject().
void clear ()
Clear the zones.
Definition at line 401 of file ZoneMesh.C.
References ZoneMesh< ZoneType, MeshType >::checkDefinition(), and clear().
Referenced by cellTable::addCellZones(), and ZoneMesh< cellZone, polyMesh >::mesh().
bool checkDefinition (const bool report = false) const
Check zone definition. Return true if in error.
Definition at line 410 of file ZoneMesh.C.
References ZoneMesh< ZoneType, MeshType >::checkParallelSync(), and forAll.
Referenced by ZoneMesh< ZoneType, MeshType >::clear(), and ZoneMesh< cellZone, polyMesh >::mesh().
bool checkParallelSync (const bool report = false) const
Check whether all procs have all zones and in same order. Return.
true if in error.
Definition at line 428 of file ZoneMesh.C.
References Foam::endl(), forAll, Foam::Info, and List< T >::size().
Referenced by ZoneMesh< ZoneType, MeshType >::checkDefinition(), and ZoneMesh< cellZone, polyMesh >::mesh().
void movePoints (const pointField & p)
Correct zone mesh after moving points.
Definition at line 505 of file ZoneMesh.C.
References forAll.
Referenced by ZoneMesh< cellZone, polyMesh >::mesh(), and polyMesh::movePoints().
bool writeData (Ostream & os) const virtual
writeData member function required by regIOobject
Implements regIOobject.
Definition at line 517 of file ZoneMesh.C.
References IOstream::good().
Referenced by ZoneMesh< cellZone, polyMesh >::mesh().
const ZoneType & operator[] (const word & zoneName) const
Return const reference to ZoneType by name.
Definition at line 528 of file ZoneMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by ZoneMesh< cellZone, polyMesh >::mesh().
ZoneType & operator[] (const word & zoneName)
Return reference to ZoneType by name.
Definition at line 548 of file ZoneMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, and Foam::nl.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const ZoneMesh< ZoneType, MeshType > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/zones/ZoneMesh/cellZoneMeshFwd.H
src/OpenFOAM/meshes/polyMesh/zones/ZoneMesh/ZoneMesh.H
src/OpenFOAM/meshes/polyMesh/zones/ZoneMesh/ZoneMesh.C