OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+turbulence->divDevRhoReff(U)==fvOptions(rho, U))
if (pimple.momentumPredictor())
Function Documentation
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+turbulence->divDevRhoReff(U) = =fvOptions(rho, U))
if (pimple. momentumPredictor())
Definition at line 10 of file UEqn.H.
References fvOptions, Foam::fvc::grad(), Foam::magSqr(), p, solve(), U, and UEqn.