OpenFOAM: applications/solvers/multiphase/cavitatingFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiGradp (rhorAUf *mesh.magSf()*fvc::snGrad(p))
while (pimple.correctNonOrthogonal())
p correctBoundaryConditions ()
Variables
phi
Info<< "Predicted p max-min : "<< max(p).value()<< " "<< min(p).value()<< endl;rho==max(psi *p+alphal *rhol0+((alphav *psiv+alphal *psil)-psi)*pSat, rhoMin);#1"/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/multiphase/cavitatingFoam/alphavPsi.H"1{alphav=max(min((rho-rholSat)/(rhovSat-rholSat), scalar(1)), scalar(0));alphal=1.0-alphav;Info<< "max-min alphav: "<< max(alphav).value()<< " "<< min(alphav).value()<< endl;psiModel-> correct ()
p
Function Documentation
volScalarField rAU (1.0/UEqn. A())
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiGradp (rhorAUf *mesh. magSf)*fvc::snGrad(p)
while (pimple. correctNonOrthogonal())
Definition at line 25 of file pEqn.H.
References alphal, Foam::fvc::ddt(), Foam::fvc::div(), Foam::endl(), Foam::Info, Foam::fvc::laplacian(), Foam::max(), mesh, Foam::min(), p, phiGradp(), pimple, psi, rho, rhof(), rhoMin(), and rhorAUf().
p correctBoundaryConditions ()
Variable Documentation
phi
Initial value:
= fvc::flux(HbyA)
         + rhorAUf*fvc::ddtCorr(U, phi)
Definition at line 18 of file pEqn.H.
radiation correct ()
Definition at line 72 of file pEqn.H.
Referenced by porosityModel::addResistance(), interRegionHeatTransferModel::addSup(), Chung::Chung(), Foam::MULES::correct(), motionDirectionalDiffusivity::correct(), PaSR< Type >::correct(), linearViscousStress< BasicTurbulenceModel >::correct(), laminar< BasicTurbulenceModel >::correct(), eddyViscosity< BasicTurbulenceModel >::correct(), ReynoldsStress< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), Poisson::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), LESModel< BasicTurbulenceModel >::correct(), RASModel< BasicTurbulenceModel >::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correct(), directionalDiffusivity::directionalDiffusivity(), for(), if(), inverseDistanceDiffusivity::inverseDistanceDiffusivity(), inverseFaceDistanceDiffusivity::inverseFaceDistanceDiffusivity(), inversePointDistanceDiffusivity::inversePointDistanceDiffusivity(), inverseVolumeDiffusivity::inverseVolumeDiffusivity(), linear::linear(), meshStructure::meshStructure(), sampledSets::movePoints(), patchDataWave< TransferType >::patchDataWave(), patchPatchDist::patchPatchDist(), pointPatchDist::pointPatchDist(), primitiveMeshGeometry::primitiveMeshGeometry(), sampledSets::readUpdate(), chemistryModel< CompType, ThermoType >::solve(), sampledSets::updateMesh(), wallDistData< TransferType >::wallDistData(), Wallis::Wallis(), and optionList::~optionList().
p
Initial value:
=
    (
        rho
      - alphal*rhol0
      - ((alphav*psiv + alphal*psil) - psi)*pSat
    )/psi
Definition at line 57 of file pEqn.H.