OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
bEqn.H File Reference
Functions
if (ign.ignited())
Function Documentation
if (ign. ignited())
Definition at line 1 of file bEqn.H.
References Foam::abort(), args, Foam::constant::physicoChemical::b, Foam::constant::universal::c, Foam::fvc::ddt(), Foam::fvc::div(), Foam::constant::electromagnetic::e, Foam::endl(), epsilon, argList::executable(), Foam::FatalError, fvOptions, Foam::constant::universal::G, Foam::fvc::grad(), Foam::Info, Foam::MULES::interpolate(), Foam::fvc::laplacian(), Foam::mag(), Foam::max(), mesh, Foam::min(), mvConvection(), n, phi, Foam::pow(), R, rho, Foam::fvc::snGrad(), Foam::fvc::Sp(), Foam::sqr(), Foam::sqrt(), StCorr(), Foam::fvc::Su(), Foam::fvc::SuSp(), thermo, turbulence, U, and unstrainedLaminarFlameSpeed.