OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(mixture.rhoPhi(), U)+turbulence->divDevRhoReff(U))
UEqn relax ()
if (pimple.momentumPredictor())
Function Documentation
fvVectorMatrix UEqn (fvm:: ddtrho, U)+fvm::div(mixture.rhoPhi(), U)+turbulence->divDevRhoReff(U)
UEqn relax ()
if (pimple. momentumPredictor())
Definition at line 10 of file UEqn.H.
References ghf, Foam::magSqr(), mesh, mixture, p_rgh, Foam::fvc::reconstruct(), rho, Foam::fvc::snGrad(), solve(), U, and UEqn().