OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
tmp< fvVectorMatrix > UEqn (fvm::div(phi, U)+MRF.DDt(U)+turbulence->divDevReff(U)==fvOptions(U))
UEqn ().relax()
if (pressureImplicitPorosity)
fvOptions constrain (UEqn())
solve (UEqn()==-fvc::grad(p))
fvOptions correct (U)
trAU ().rename("rAU")
Variables
tmp< volScalarField > trAU = 1.0/UEqn().A()
tmp< volTensorField > trTU
else
Function Documentation
MRF correctBoundaryVelocity (U)
tmp<fvVectorMatrix> UEqn (fvm::div(phi, U)+MRF.DDt(U)+turbulence->divDevReff(U) = =fvOptions(U))
UEqn ()
if (pressureImplicitPorosity)
Definition at line 23 of file UEqn.H.
References fvOptions, Foam::fvc::grad(), Foam::I, Foam::inv(), nUCorr, p, pZones(), trTU, U, and UEqn().
fvOptions constrain (UEqn())
solve (UEqn() = =-fvc::grad(p))
fvOptions correct (U)
trAU ()
Variable Documentation
trAU = 1.0/UEqn().A()
Definition at line 20 of file UEqn.H.
tmp<volTensorField> trTU
Definition at line 21 of file UEqn.H.
else
Initial value:
{
        pZones.addResistance(UEqn())
Definition at line 43 of file UEqn.H.