OpenFOAM: applications/solvers/combustion/chemFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
if (constProp=="volume")
Function Documentation
if (constProp = = "volume")
Definition at line 3 of file pEqn.H.
References forAll(), p, R, rho, rho0(), Rspecific, specieData(), thermo, and Y.