OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setRDeltaT.H File Reference
Functions
scalar rDeltaTSmoothingCoeff (runTime.controlDict().lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02))
rDeltaT dimensionedInternalField ()
rDeltaT correctBoundaryConditions ()
Function Documentation
scalar rDeltaTSmoothingCoeff (runTime. controlDict).lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02)
rDeltaT dimensionedInternalField ()
Referenced by advectiveFvPatchField< Type >::advectiveFvPatchField(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), kkLOmega::correct(), cyclicACMIFvPatchField< Type >::cyclicACMIFvPatchField(), cyclicAMIFvPatchField< Type >::cyclicAMIFvPatchField(), cyclicFvPatchField< Type >::cyclicFvPatchField(), SpalartAllmarasDES< BasicTurbulenceModel >::dTilda(), emptyFvPatchField< Type >::emptyFvPatchField(), energyRegionCoupledFvPatchScalarField::energyRegionCoupledFvPatchScalarField(), fluxCorrectedVelocityFvPatchVectorField::evaluate(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), forAll(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), calculatedFvPatchField< Type >::gradientBoundaryCoeffs(), genericFvPatchField< Type >::gradientBoundaryCoeffs(), calculatedFvPatchField< Type >::gradientInternalCoeffs(), genericFvPatchField< Type >::gradientInternalCoeffs(), if(), basicThermo::lookupThermo(), mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator==(), processorCyclicFvPatchField< Type >::processorCyclicFvPatchField(), processorFvPatchField< Type >::processorFvPatchField(), codedFixedValueFvPatchField< Type >::redirectPatchField(), codedFixedValuePointPatchField< Type >::redirectPatchField(), codedMixedFvPatchField< Type >::redirectPatchField(), P1::Ru(), fvDOM::Ru(), supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField(), cyclicPointPatchField< Type >::swapAddSeparated(), cyclicACMIPointPatchField< Type >::swapAddSeparated(), cyclicAMIPointPatchField< Type >::swapAddSeparated(), symmetryFvPatchField< Type >::symmetryFvPatchField(), symmetryPlaneFvPatchField< Type >::symmetryPlaneFvPatchField(), turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), uniformInterpolatedDisplacementPointPatchVectorField::uniformInterpolatedDisplacementPointPatchVectorField(), cellMotionFvPatchField< Type >::updateCoeffs(), fixedShearStressFvPatchVectorField::updateCoeffs(), movingWallVelocityFvPatchVectorField::updateCoeffs(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), filmPyrolysisVelocityCoupledFvPatchVectorField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), freestreamPressureFvPatchScalarField::updateCoeffs(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::updateCoeffs(), pressureInletVelocityFvPatchVectorField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), alphatWallFunctionFvPatchScalarField::updateCoeffs(), swirlFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), mappedFixedValueFvPatchField< Type >::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), wallHeatTransferFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), mappedFieldFvPatchField< Type >::updateCoeffs(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), fanPressureFvPatchScalarField::updateCoeffs(), SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), pressureInletOutletParSlipVelocityFvPatchVectorField::updateCoeffs(), pressureNormalInletOutletVelocityFvPatchVectorField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), pressureDirectedInletVelocityFvPatchVectorField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), pressureDirectedInletOutletVelocityFvPatchVectorField::updateCoeffs(), uniformTotalPressureFvPatchScalarField::updateCoeffs(), supersonicFreestreamFvPatchVectorField::updateCoeffs(), syringePressureFvPatchScalarField::updateCoeffs(), externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs(), totalPressureFvPatchScalarField::updateCoeffs(), calculatedFvPatchField< Type >::valueBoundaryCoeffs(), genericFvPatchField< Type >::valueBoundaryCoeffs(), calculatedFvPatchField< Type >::valueInternalCoeffs(), genericFvPatchField< Type >::valueInternalCoeffs(), wedgeFvPatchField< Type >::wedgeFvPatchField(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), timeVaryingMappedFixedValueFvPatchField< Type >::write(), externalCoupledMixedFvPatchField< Type >::writeData(), externalCoupledMixedFvPatchField< Type >::writeGeometry(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), nutkFilmWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), and externalCoupledMixedFvPatchField< Type >::~externalCoupledMixedFvPatchField().
rDeltaT correctBoundaryConditions ()