OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createSolidFields.H File Reference
Functions
PtrList< coordinateSystem > coordinates (solidRegions.size())
PtrList< solidThermo > thermos (solidRegions.size())
PtrList< radiation::radiationModel > radiations (solidRegions.size())
PtrList< fv::IOoptionList > solidHeatSources (solidRegions.size())
PtrList< volScalarField > betavSolid (solidRegions.size())
PtrList< volSymmTensorField > aniAlphas (solidRegions.size())
forAll (solidRegions, i)
Function Documentation
PtrList<coordinateSystem> coordinates (solidRegions. size())
Referenced by triSurfaceMesh::boundingSpheres(), searchableSurfaceCollection::coordinates(), forAll(), and if().
PtrList<solidThermo> thermos (solidRegions. size())
Referenced by forAll(), and basicThermo::lookupThermo().
PtrList<radiation::radiationModel> radiations (solidRegions. size())
Referenced by forAll().
PtrList<fv::IOoptionList> solidHeatSources (solidRegions. size())
Referenced by forAll().
PtrList<volScalarField> betavSolid (solidRegions. size())
Referenced by forAll().
PtrList<volSymmTensorField> aniAlphas (solidRegions. size())
Referenced by forAll(), and if().
forAll (solidRegions , i)
Definition at line 10 of file createSolidFields.H.
References aniAlphas(), betavSolid(), coordinates(), Foam::dimless, Foam::endl(), Foam::Info, Foam::nl, radiations(), PtrList< T >::set(), solidHeatSources(), solidRegions(), T, and thermos().