OpenFOAM: applications/solvers/multiphase/twoLiquidMixingFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rho *rAU)*fvc::ddtCorr(U, phi))
adjustPhi (phiHbyA, U, p_rgh)
surfaceScalarField phig (-ghf *fvc::snGrad(rho)*rAUf *mesh.magSf())
constrainPressure (p_rgh, U, phiHbyA, rAUf)
while (pimple.correctNonOrthogonal())
if (p_rgh.needReference())
Variables
phiHbyA = phig
p == p_rgh + rho*gh
Function Documentation
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rho *rAU)*fvc::ddtCorr(U, phi))
adjustPhi (phiHbyA , U , p_rgh)
surfaceScalarField phig (-ghf * fvc::snGradrho)*rAUf *mesh.magSf()
constrainPressure (p_rgh , U , phiHbyA , rAUf)
while (pimple. correctNonOrthogonal())
Definition at line 23 of file pEqn.H.
References Foam::fvc::div(), Foam::getRefCellValue(), HbyA, Foam::fvc::laplacian(), mesh, p_rgh, phi, phig(), phiHbyA, pimple, pRefCell, rAUf(), Foam::fvc::reconstruct(), and U.
if (p_rgh. needReference())
Definition at line 47 of file pEqn.H.
References Foam::getRefCellValue(), gh, p, p_rgh, pRefCell, pRefValue, and rho.
Variable Documentation
phiHbyA = phig
Definition at line 18 of file pEqn.H.
p == p_rgh + rho*gh
Definition at line 45 of file pEqn.H.