OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
tmp< fvVectorMatrix > tUEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Variables
fvVectorMatrix & UEqn = tUEqn.ref()
Function Documentation
MRF correctBoundaryVelocity (U)
tmp<fvVectorMatrix> tUEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U) = =fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple. momentumPredictor())
Definition at line 19 of file UEqn.H.
References fvOptions, Foam::fvc::grad(), Foam::magSqr(), p, solve(), and U.
Variable Documentation
fvVectorMatrix& UEqn = tUEqn.ref()
Definition at line 13 of file UEqn.H.