OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(rhoPhi, U)+MRF.DDt(rho, U)+fvc::div(UdmModel.tauDm())+turbulence->divDevRhoReff(U)==fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Function Documentation
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(rhoPhi, U)+MRF.DDt(rho, U)+fvc::div(UdmModel.tauDm())+turbulence->divDevRhoReff(U) = =fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple. momentumPredictor())
Definition at line 19 of file UEqn.H.
References fvOptions, ghf, mesh, p_rgh, Foam::fvc::reconstruct(), rho, Foam::fvc::snGrad(), solve(), U, and UEqn.