OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pcEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn().A())
volScalarField rAtU (1.0/(1.0/rAU-UEqn().H1()))
volVectorField HbyA ("HbyA", U)
UEqn clear ()
if (simple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
volScalarField rhorAtU ("rhorAtU", rho *rAtU)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
if (!simple.transonic())
Variables
HbyA = rAU*UEqn().H()
bool closedVolume = false
else
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
U = HbyA - rAtU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
volScalarField rAU (1.0/ UEqn).A()
volScalarField rAtU (1.0/ 1.0/rAU-UEqn().H1())
volVectorField HbyA ("HbyA" , U)
UEqn clear ()
Referenced by Foam::atan2(), ILList< LListBase, T >::clear(), DictionaryBase< IDLListType, T >::clear(), ZoneMesh< ZoneType, MeshType >::clear(), wordRe::clear(), LList< LListBase, T >::clear(), UnsortedMeshedSurface< Face >::clear(), StaticHashTable< T, Key, Hash >::clearStorage(), HashTable< T, Key, Hash >::clearStorage(), DSMCCloud< ParcelType >::DSMCCloud(), sampledPatch::expire(), sampledTriSurfaceMesh::expire(), topoSet::invert(), moleculeCloud::moleculeCloud(), ILList< LListBase, T >::operator=(), HashPtrTable< T, Key, Hash >::operator=(), UILList< LListBase, T >::operator=(), LPtrList< LListBase, T >::operator=(), Matrix< Form, Type >::operator=(), PackedBoolList::operator=(), LList< LListBase, T >::operator=(), StaticHashTable< T, Key, Hash >::operator=(), HashTable< T, Key, Hash >::operator=(), UnsortedMeshedSurface< Face >::operator=(), MeshedSurface< Face >::operator=(), dictionary::operator=(), Foam::pow(), reactingMixture< ThermoType >::reactingMixture(), extendedEdgeMeshFormat::read(), extendedFeatureEdgeMeshFormat::read(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJedgeFormat::read(), VTKsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), FTRsurfaceFormat< Face >::read(), edgeMeshFormat::read(), OFSsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), fvSchemes::read(), STLsurfaceFormat< Face >::read(), UnsortedMeshedSurface< Face >::read(), MeshedSurface< Face >::read(), boundaryRegion::readDict(), cellTable::readDict(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), fvBoundaryMesh::readUpdate(), cuttingPlane::reCut(), dynamicCode::reset(), regExp::set(), UPtrList< T >::setSize(), CompactListList< T, Container >::setSize(), List< T >::setSize(), PtrList< T >::setSize(), SHA1::SHA1(), SHA1Digest::SHA1Digest(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), Foam::stabilise(), topoSet::subset(), PackedBoolList::subsetIndices(), ILList< LListBase, T >::transfer(), Matrix< Form, Type >::transfer(), LPtrList< LListBase, T >::transfer(), LList< LListBase, T >::transfer(), PtrList< T >::transfer(), StaticHashTable< T, Key, Hash >::transfer(), HashTable< T, Key, Hash >::transfer(), MeshedSurface< Face >::transfer(), Foam::transform(), autoPtr< T >::~autoPtr(), HashPtrTable< T, Key, Hash >::~HashPtrTable(), HashTable< T, Key, Hash >::~HashTable(), ILList< LListBase, T >::~ILList(), LList< LListBase, T >::~LList(), LPtrList< LListBase, T >::~LPtrList(), and regExp::~regExp().
if (simple. transonic())
Definition at line 11 of file pcEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::grad(), HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, MRF, p, phi, phic, phid(), pRefCell, pRefValue, psi, rAtU(), rAU(), rho, rhorAtU(), simple, and Foam::fvc::snGrad().
MRF makeRelative (fvc:: interpolaterho, phiHbyA)
volScalarField rhorAtU ("rhorAtU" , rho * rAtU)
while (simple. correctNonOrthogonal())
Definition at line 73 of file pcEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, phiHbyA, pRefCell, pRefValue, psi, rho, rhorAtU(), and simple.
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
Definition at line 107 of file pcEqn.H.
References Foam::fvc::domainIntegrate(), initialMass, p, and psi.
if (!simple. transonic())
Definition at line 118 of file pcEqn.H.
References rho.
Variable Documentation
HbyA = rAU*UEqn().H()
Definition at line 5 of file pcEqn.H.
closedVolume = false
Definition at line 9 of file pcEqn.H.
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        fvc::interpolate(rho*HbyA) & mesh.Sf()
    )
Definition at line 57 of file pcEqn.H.
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
Definition at line 68 of file pcEqn.H.
U = HbyA - rAtU*fvc::grad(p)
Definition at line 101 of file pcEqn.H.
rho = thermo.rho()
Definition at line 114 of file pcEqn.H.