OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
YEqn.H File Reference
Functions
tmp< fv::convectionScheme< scalar > > mvConvection (fv::convectionScheme< scalar >::New(mesh, fields, phi, mesh.divScheme("div(phi,Yi_h)")))
volScalarField Yt (0.0 *Y[0])
forAll (Y, i)
Y[inertIndex] max (0.0)
Variables
dQ = reaction->dQ()
label inertIndex = -1
Y [inertIndex] = scalar(1) - Yt
Function Documentation
tmp<fv::convectionScheme<scalar> > mvConvection (fv::convectionScheme< scalar > ::New mesh, fields, phi, mesh.divScheme("div(phi,Yi_h)"))
Referenced by forAll().
volScalarField Yt (0.0 * Y[0])
Referenced by forAll().
forAll (Y , i)
Definition at line 18 of file YEqn.H.
References Foam::fvc::ddt(), fvOptions, inertSpecie(), Foam::fvc::laplacian(), mesh, mvConvection(), Foam::name(), phi, reaction(), rho, turbulence, Y, and Yt().
Y [inertIndex] max (0. 0)
Variable Documentation
dQ = reaction->dQ()
Definition at line 14 of file YEqn.H.
label inertIndex = -1
Definition at line 15 of file YEqn.H.
Y[inertIndex] = scalar(1) - Yt
Definition at line 51 of file YEqn.H.
Referenced by forAll().