OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setRDeltaT.H File Reference
Functions
scalar maxCo (pimpleDict.lookupOrDefault< scalar >("maxCo", 0.9))
scalar maxAlphaCo (pimpleDict.lookupOrDefault< scalar >("maxAlphaCo", 0.2))
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.1))
label nAlphaSpreadIter (pimpleDict.lookupOrDefault< label >("nAlphaSpreadIter", 1))
scalar alphaSpreadDiff (pimpleDict.lookupOrDefault< scalar >("alphaSpreadDiff", 0.2))
scalar alphaSpreadMax (pimpleDict.lookupOrDefault< scalar >("alphaSpreadMax", 0.99))
scalar alphaSpreadMin (pimpleDict.lookupOrDefault< scalar >("alphaSpreadMin", 0.01))
label nAlphaSweepIter (pimpleDict.lookupOrDefault< label >("nAlphaSweepIter", 5))
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTDampingCoeff", 1.0))
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar >("maxDeltaT", GREAT))
volScalarField rDeltaT0 ("rDeltaT0", rDeltaT)
rDeltaT dimensionedInternalField ()
if (maxAlphaCo< maxCo)
rDeltaT correctBoundaryConditions ()
Variables
const dictionary & pimpleDict = pimple.dict()
Function Documentation
scalar maxCo (pimpleDict.lookupOrDefault< scalar > "maxCo", 0.9)
scalar maxAlphaCo (pimpleDict.lookupOrDefault< scalar > "maxAlphaCo", 0.2)
Referenced by if().
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTSmoothingCoeff", 0.1)
label nAlphaSpreadIter (pimpleDict.lookupOrDefault< label > "nAlphaSpreadIter", 1)
Referenced by if().
scalar alphaSpreadDiff (pimpleDict.lookupOrDefault< scalar > "alphaSpreadDiff", 0.2)
Referenced by if().
scalar alphaSpreadMax (pimpleDict.lookupOrDefault< scalar > "alphaSpreadMax", 0.99)
Referenced by if().
scalar alphaSpreadMin (pimpleDict.lookupOrDefault< scalar > "alphaSpreadMin", 0.01)
Referenced by if().
label nAlphaSweepIter (pimpleDict.lookupOrDefault< label > "nAlphaSweepIter", 5)
Referenced by if().
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTDampingCoeff", 1.0)
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar > "maxDeltaT", GREAT)
volScalarField rDeltaT0 ("rDeltaT0" , rDeltaT)
rDeltaT dimensionedInternalField ()
if ()
Definition at line 66 of file setRDeltaT.H.
References alpha1, alphaSpreadDiff(), alphaSpreadMax(), alphaSpreadMin(), Foam::fvc::average(), Foam::endl(), Foam::gMax(), Foam::gMin(), Foam::Info, Foam::mag(), Foam::max(), maxAlphaCo(), mesh, nAlphaSpreadIter(), nAlphaSweepIter(), phi, Foam::pos(), rDeltaT0(), rDeltaTDampingCoeff(), rDeltaTSmoothingCoeff(), Foam::fvc::smooth(), Foam::fvc::spread(), Foam::fvc::surfaceSum(), and Foam::fvc::sweep().
rDeltaT correctBoundaryConditions ()
Variable Documentation
const dictionary& pimpleDict = pimple.dict()
Definition at line 4 of file setRDeltaT.H.