OpenFOAM: applications/solvers/combustion/XiFoam/UEqn.H File Reference
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Function Documentation
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U) = =fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple. momentumPredictor())
Definition at line 16 of file UEqn.H.
References fvOptions, Foam::fvc::grad(), Foam::magSqr(), p, solve(), U, and UEqn.