OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ftEqn.H File Reference
Functions
if (composition.contains("ft"))
Function Documentation
if (composition. contains"ft")
Definition at line 1 of file ftEqn.H.
References betav, composition, Db(), Foam::fvc::ddt(), Foam::fvc::laplacian(), mvConvection(), phi, rho, and solve().