OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setRegionSolidFields.H File Reference
Functions
aniAlpha internalField ()
aniAlpha correctBoundaryConditions ()
Variables
fvMesh & mesh = solidRegions[i]
solidThermo & thermo = thermos[i]
const radiation::radiationModel & radiation = radiations[i]
tmp< volScalarField > trho = thermo.rho()
const volScalarField & rho = trho()
tmp< volScalarField > tcp = thermo.Cp()
const volScalarField & cp = tcp()
tmp< volSymmTensorField > taniAlpha
tmp< volVectorField > tkappaByCp = thermo.Kappa()/cp
const coordinateSystem & coodSys = coordinates[i]
volScalarField & h = thermo.he()
Planck constant.
const volScalarField & betav = betavSolid[i]
fv::IOoptionList & fvOptions = solidHeatSources[i]
Function Documentation
aniAlpha internalField ()
aniAlpha correctBoundaryConditions ()
Variable Documentation
fvMesh& mesh = solidRegions[i]
Definition at line 1 of file setRegionSolidFields.H.
solidThermo& thermo = thermos[i]
Definition at line 2 of file setRegionSolidFields.H.
const radiation::radiationModel& radiation = radiations[i]
Definition at line 3 of file setRegionSolidFields.H.
Referenced by fvDOM::aLambda(), radiationCoupledBase::emissivity(), forAll(), viewFactor::Qr(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
tmp<volScalarField> trho = thermo.rho()
Definition at line 5 of file setRegionSolidFields.H.
Referenced by PaSR< Type >::correct(), forAll(), liquidFilmThermo::rho(), and constantFilmThermo::rho().
const volScalarField& rho = trho()
Definition at line 6 of file setRegionSolidFields.H.
tmp<volScalarField> tcp = thermo.Cp()
Definition at line 8 of file setRegionSolidFields.H.
Referenced by forAll().
const volScalarField& cp = tcp()
Definition at line 9 of file setRegionSolidFields.H.
Referenced by Foam::cp(), heThermo< BasicThermo, MixtureType >::Cp(), thermo< Thermo, Type >::Cp(), thermo< Thermo, Type >::cv(), chemistryModel< CompType, ThermoType >::derivatives(), forAll(), thermo< Thermo, Type >::gamma(), triangle< Point, PointRef >::nearestPointClassify(), fvFieldReconstructor::reconstructFvSurfaceField(), and fvFieldReconstructor::reconstructFvVolumeField().
taniAlpha
Initial value:
= tmp<volSymmTensorField>
        (
            new volSymmTensorField(aniAlpha)
        )
Definition at line 11 of file setRegionSolidFields.H.
tmp<volVectorField> tkappaByCp = thermo.Kappa()/cp
Definition at line 15 of file setRegionSolidFields.H.
Referenced by forAll().
const coordinateSystem& coodSys = coordinates[i]
Definition at line 16 of file setRegionSolidFields.H.
volScalarField& h = thermo.he()
Planck constant.
Definition at line 29 of file setRegionSolidFields.H.
Referenced by normal::erfInv(), SIBS::solve(), SVD::SVD(), and LISAAtomization< CloudType >::update().
const volScalarField& betav = betavSolid[i]
Definition at line 31 of file setRegionSolidFields.H.
fv::IOoptionList& fvOptions = solidHeatSources[i]
Definition at line 33 of file setRegionSolidFields.H.