OpenFOAM: applications/solvers/combustion/fireFoam/UEqn.H File Reference
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==parcels.SU(U)+fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Function Documentation
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U) = =parcels.SU(U)+fvOptions(rho, U))
E2Eqn relax ()
Initial value:
{
        U2Eqn =
        (
            phase2.UEqn()
         ==
           *momentumTransfer[phase2.name()]
          + fvOptions(alpha2, rho2, U2)
        )
Referenced by listPlusEqOp< T >::operator()(), GeometricField< Type, PatchField, GeoMesh >::relax(), ReactingCloud< CloudType >::relaxSources(), ThermoCloud< CloudType >::relaxSources(), and KinematicCloud< CloudType >::relaxSources().
fvOptions constrain (UEqn)
if (pimple. momentumPredictor())
Definition at line 17 of file UEqn.H.
References fvOptions, ghf, Foam::magSqr(), mesh, p_rgh, Foam::fvc::reconstruct(), rho, Foam::fvc::snGrad(), solve(), U, and UEqn.