OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1)-alphaf1)
volScalarField rAU1 (IOobject::groupName("rAU", phase1.name()), 1.0/(U1Eqn.A() +max(phase1.residualAlpha()-alpha1, scalar(0)) *rho1/runTime.deltaT()))
volScalarField rAU2 (IOobject::groupName("rAU", phase2.name()), 1.0/(U2Eqn.A() +max(phase2.residualAlpha()-alpha2, scalar(0)) *rho2/runTime.deltaT()))
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha())*rAU1))
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha())*rAU2))
volScalarField Kd (fluid.Kd())
tmp< surfaceScalarField > DbyA1 (fvc::interpolate(rAU1 *(D+phase1.turbulence().pPrime())))
tmp< surfaceScalarField > DbyA2 (fvc::interpolate(rAU2 *(D+phase2.turbulence().pPrime())))
volVectorField F (fluid.F())
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1)*mesh.magSf())
if (implicitPhasePressure)
while (pimple.correct())
Variables
tmp< surfaceScalarField > phiF1 = DbyA1()*snGradAlpha1 + fvc::flux(rAU1*F)
tmp< surfaceScalarField > phiF2 = - DbyA2()*snGradAlpha1 - fvc::flux(rAU2*F)
Function Documentation
surfaceScalarField alphaf1 ("alphaf1" , fvc::interpolate(alpha1))
Referenced by while().
surfaceScalarField alphaf2 ("alphaf2" , scalar(1)- alphaf1)
Referenced by while().
volScalarField rAU1 (IOobject::groupName("rAU", phase1.name()) , 1.0/ U1Eqn.A() +max(phase1.residualAlpha()-alpha1, scalar(0)) *rho1/runTime.deltaT())
Referenced by if(), and while().
volScalarField rAU2 (IOobject::groupName("rAU", phase2.name()) , 1.0/ U2Eqn.A() +max(phase2.residualAlpha()-alpha2, scalar(0)) *rho2/runTime.deltaT())
Referenced by if(), and while().
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha())*rAU1))
Referenced by while().
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha())*rAU2))
Referenced by while().
volScalarField Kd (fluid. Kd())
Referenced by while().
tmp<surfaceScalarField> DbyA1 (fvc::interpolate(rAU1 *(D+phase1.turbulence().pPrime())))
Referenced by if().
tmp<surfaceScalarField> DbyA2 (fvc::interpolate(rAU2 *(D+phase2.turbulence().pPrime())))
Referenced by if().
volVectorField F (fluid. F())
Referenced by if().
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1)*mesh.magSf())
Referenced by if().
if (implicitPhasePressure)
Definition at line 75 of file pEqn.H.
References DbyA1(), DbyA2(), phase1, and phase2.
while (pimple. correct())
Definition at line 84 of file pEqn.H.
References alpha1, alpha2, alphaf1(), alphaf2(), alphaPhi1, alphaPhi2, alpharAUf1(), alpharAUf2(), Foam::fvc::average(), Foam::correction(), Foam::fvc::ddt(), Foam::deleteDemandDrivenData(), Foam::fvc::div(), fluid, forAll(), fvOptions, g, gh, ghf, ghSnGradRho(), Foam::MULES::interpolate(), Kd(), Foam::fvc::laplacian(), Foam::mag(), Foam::max(), mesh, MRF, p, p_rgh, p_rgh_0(), patchi, phase1, phase2, phi, phi1, phi2, phiF1, phiF2, phiHbyA, phir(), pimple, pMin(), Foam::pos(), psi1, psi2, rAU1(), rAU2(), rAUf(), Foam::fvc::reconstruct(), rho, rho1, rho2, setSnGrad< fixedFluxPressureFvPatchScalarField >(), Foam::fvc::snGrad(), solve(), Foam::fvc::Sp(), Foam::fvc::Su(), U, U1, and U2.
Variable Documentation
phiF1 = DbyA1()*snGradAlpha1 + fvc::flux(rAU1*F)
Definition at line 37 of file pEqn.H.
Referenced by while().
phiF2 = - DbyA2()*snGradAlpha1 - fvc::flux(rAU2*F)
Definition at line 38 of file pEqn.H.
Referenced by while().