OpenFOAM: applications/solvers/lagrangian/coalChemistryFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p, rho, U, phiHbyA, rhorAUf, MRF)
while (pimple.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
if (thermo.dpdt())
Variables
rho = thermo.rho()
else
U = HbyA - rAU*fvc::grad(p)
K = 0.5*magSqr(U)
Function Documentation
volScalarField rAU (1.0/UEqn. A())
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple. transonic())
Definition at line 7 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::ddtCorr(), Foam::fvc::div(), Foam::fvc::flux(), fvOptions, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, MRF, p, phi, phid(), pimple, psi, rho, rhorAUf(), and U.
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure (p , rho , U , phiHbyA , rhorAUf , MRF)
while (pimple. correctNonOrthogonal())
Definition at line 57 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), mesh, p, phi, pimple, psi, rho, and rhorAUf().
U correctBoundaryConditions ()
fvOptions correct (U)
if (thermo. dpdt())
Definition at line 87 of file pEqn.H.
References Foam::fvc::ddt(), dpdt, and p.
Variable Documentation
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        (
            fvc::flux(rho*HbyA)
          + rhorAUf*fvc::ddtCorr(rho, U, phi)
        )
    )
Definition at line 42 of file pEqn.H.
U = HbyA - rAU*fvc::grad(p)
Definition at line 81 of file pEqn.H.
K = 0.5*magSqr(U)
Definition at line 85 of file pEqn.H.