OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setRDeltaT.H File Reference
Functions
scalar maxCo (pimpleDict.lookupOrDefault< scalar >("maxCo", 0.2))
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar >("maxDeltaT", GREAT))
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02))
surfaceScalarField maxPhi ("maxPhi", phi)
forAll (phases, phasei)
rDeltaT ref ()
rDeltaT correctBoundaryConditions ()
Variables
const dictionary & pimpleDict = pimple.dict()
Function Documentation
scalar maxCo (pimpleDict.lookupOrDefault< scalar > "maxCo", 0.2)
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar > "maxDeltaT", GREAT)
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTSmoothingCoeff", 0.02)
surfaceScalarField maxPhi ("maxPhi" , phi)
Referenced by forAll().
forAll (phases , phasei)
Definition at line 23 of file setRDeltaT.H.
References Foam::dimTime, Foam::endl(), Foam::gMax(), Foam::gMin(), Foam::Info, Foam::mag(), Foam::max(), maxCo(), maxDeltaT(), maxPhi(), mesh, phasei, phases, phi, rDeltaTSmoothingCoeff(), Foam::fvc::smooth(), and Foam::fvc::surfaceSum().
rDeltaT ref ()
rDeltaT correctBoundaryConditions ()
Variable Documentation
const dictionary& pimpleDict = pimple.dict()
Definition at line 4 of file setRDeltaT.H.