OpenFOAM: applications/solvers/combustion/reactingFoam/pcEqn.H File Reference
pcEqn.H File Reference
Functions
rho relax ()
volScalarField rAU (1.0/UEqn.A())
volScalarField rAtU (1.0/(1.0/rAU-UEqn.H1()))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple.nCorrPISO()<=1)
if (pimple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
volScalarField rhorAtU ("rhorAtU", rho *rAtU)
constrainPressure (p, rho, U, phiHbyA, rhorAtU, MRF)
while (pimple.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
if (thermo.dpdt())
if (!pimple.transonic())
Variables
rho = thermo.rho()
else
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
HbyA = (rAU - rAtU)*fvc::grad(p)
U = HbyA - rAtU*fvc::grad(p)
K = 0.5*magSqr(U)
Function Documentation
rho relax ()
volScalarField rAU (1.0/UEqn. A())
Referenced by if().
volScalarField rAtU (1.0/ 1.0/rAU-UEqn.H1())
Referenced by if().
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple.nCorrPISO()<= 1)
Definition at line 10 of file pcEqn.H.
References tUEqn().
if (pimple. transonic())
Definition at line 15 of file pcEqn.H.
References Foam::fvc::ddt(), Foam::fvc::ddtCorr(), Foam::fvc::div(), Foam::fvc::flux(), fvOptions, Foam::fvc::grad(), HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, MRF, p, phi, phic, phid(), pimple, psi, rAtU(), rAU(), rho, rhorAtU(), Foam::fvc::snGrad(), and U.
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
volScalarField rhorAtU ("rhorAtU" , rho * rAtU)
Referenced by if(), and while().
constrainPressure (p , rho , U , phiHbyA , rhorAtU , MRF)
while (pimple. correctNonOrthogonal())
Definition at line 81 of file pcEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), mesh, p, phi, pimple, psi, rho, and rhorAtU().
U correctBoundaryConditions ()
fvOptions correct (U)
if (thermo. dpdt())
Definition at line 112 of file pcEqn.H.
References Foam::fvc::ddt(), dpdt, Foam::max(), Foam::min(), p, rho, rhoMax(), rhoMin(), and thermo.
if (!pimple. transonic())
Definition at line 122 of file pcEqn.H.
References Foam::endl(), Foam::Info, Foam::max(), Foam::min(), and rho.
Variable Documentation
rho = thermo.rho()
Definition at line 1 of file pcEqn.H.
Referenced by if(), and while().
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        (
            fvc::flux(rho*HbyA)
          + fvc::interpolate(rho*rAU)*fvc::ddtCorr(rho, U, phi)
        )
    )
Definition at line 61 of file pcEqn.H.
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
Definition at line 73 of file pcEqn.H.
Referenced by NullMRF::relative().
HbyA = (rAU - rAtU)*fvc::grad(p)
Definition at line 74 of file pcEqn.H.
Referenced by Foam::constrainHbyA(), and if().
U = HbyA - rAtU*fvc::grad(p)
Definition at line 107 of file pcEqn.H.
Referenced by if().
K = 0.5*magSqr(U)
Definition at line 110 of file pcEqn.H.