OpenFOAM: applications/solvers/combustion/XiFoam/ftEqn.H File Reference
ftEqn.H File Reference
Functions
tmp< fv::convectionScheme< scalar > > mvConvection (fv::convectionScheme< scalar >::New(mesh, fields, phi, mesh.divScheme("div(phi,ft_b_ha_hau)")))
if (composition.contains("ft"))
Function Documentation
tmp<fv::convectionScheme<scalar> > mvConvection (fv::convectionScheme< scalar > ::New mesh, fields, phi, mesh.divScheme("div(phi,ft_b_ha_hau)"))
Referenced by if().
if (composition. contains"ft")
Definition at line 12 of file ftEqn.H.
References composition, Foam::fvc::ddt(), fvOptions, Foam::fvc::laplacian(), mvConvection(), phi, rho, and turbulence.