OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
correctPhi.H File Reference
Functions
correctUphiBCs (U, phi)
surfaceScalarField rhof (fvc::interpolate(rho,"div(phi,rho)"))
dimensionedScalar rAUf ("rAUf", dimTime, 1.0)
mesh setFluxRequired (pcorr.name())
while (pimple.correctNonOrthogonal())
Function Documentation
correctUphiBCs (U , phi)
Referenced by Foam::CorrectPhi().
surfaceScalarField rhof (fvc::interpolate(rho,"div(phi,rho)"))
Referenced by if(), kinematicSingleLayer::solveThickness(), and while().
dimensionedScalar rAUf ("rAUf" , dimTime , 1. 0)
Referenced by while().
mesh setFluxRequired (pcorr. name())
while (pimple. correctNonOrthogonal())
Definition at line 24 of file correctPhi.H.
References Foam::fvc::ddt(), Foam::fvc::div(), Foam::fvc::laplacian(), phi, pimple, rAUf(), rho, and rhof().