OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
interrogateWallPatches.H File Reference
Functions
label faceId (-1)
label patchId (-1)
label nWallFaces (0)
vector wallNormal (vector::zero)
forAll (patches, patchi)
if (nWallFaces==0)
scalarField y (wallNormal &(mesh.C().internalField()-mesh.C().boundaryField()[patchId][faceId]))
Variables
const fvPatchList & patches = mesh.boundary()
else
label cellId = patches[patchId].faceCells()[faceId]
Function Documentation
label faceId (- 1)
Referenced by forAll(), NamedEnum< Enum, nEnum >::names(), FacePostProcessing< CloudType >::postFace(), and ensightPartCells::~ensightPartCells().
label patchId (- 1)
Referenced by forAll(), and NamedEnum< Enum, nEnum >::names().
label nWallFaces (0)
Referenced by forAll(), cellDistFuncs::mesh(), and cellDistFuncs::smallestDist().
vector wallNormal (vector::zero)
Referenced by forAll().
forAll (patches , patchi)
Check that wall faces are parallel
Definition at line 10 of file interrogateWallPatches.H.
References Foam::exit(), faceId(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), Foam::nl, nWallFaces(), patches, patchi, patchId(), vectorField(), and wallNormal().
if (nWallFaces = = 0)
Definition at line 55 of file interrogateWallPatches.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
scalarField y (wallNormal & mesh.C().internalField()-mesh.C().boundaryField()[patchId][faceId])
Variable Documentation
const fvPatchList& patches = mesh.boundary()
Definition at line 8 of file interrogateWallPatches.H.
Referenced by forAll().
else
Initial value:
{
    Info<< "Generating wall data for patch: " << patches[patchId].name()
        << endl
Definition at line 61 of file interrogateWallPatches.H.
label cellId = patches[patchId].faceCells()[faceId]
Definition at line 67 of file interrogateWallPatches.H.
Referenced by STARCD::readBoundary(), and thermalBaffle::solveEnergy().