OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphaEqnSubCycle.H File Reference
Functions
if (nAlphaSubCycles > 1)
Variables
else
Function Documentation
if (nAlphaSubCycles , 1)
Definition at line 3 of file alphaEqnSubCycle.H.
References alpha1(), end(), mesh, nAlphaSubCycles(), and rhoPhi.
Variable Documentation
else
Initial value:
{
# 1 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/multiphase/twoLiquidMixingFoam/alphaEqn.H" 1
{
    word alphaScheme("div(phi,alpha)");
    surfaceScalarField phiAlpha
    (
        phi.name() + alpha1.name(),
        fvc::flux
        (
            phi,
            alpha1,
            alphaScheme
        )
    );
    MULES::explicitSolve(alpha1, phi, phiAlpha, 1, 0);
    rhoPhi = phiAlpha*(rho1 - rho2) + phi*rho2;
    Info<< "Phase-1 volume fraction = "
        << alpha1.weightedAverage(mesh.Vsc()).value()
        << "  Min(" << alpha1.name() << ") = " << min(alpha1).value()
        << "  Max(" << alpha1.name() << ") = " << max(alpha1).value()
        << endl;
}
# 32 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/multiphase/twoLiquidMixingFoam/alphaEqnSubCycle.H" 2
}
rho == alpha1*rho1 + alpha2*rho2
Definition at line 31 of file alphaEqnSubCycle.H.