OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFluidFields.H File Reference
Functions
PtrList< rhoThermo > thermoFluid (fluidRegions.size())
PtrList< volScalarField > rhoFluid (fluidRegions.size())
PtrList< volVectorField > UFluid (fluidRegions.size())
PtrList< surfaceScalarField > phiFluid (fluidRegions.size())
PtrList< uniformDimensionedVectorField > gFluid (fluidRegions.size())
PtrList< uniformDimensionedScalarField > hRefFluid (fluidRegions.size())
PtrList< volScalarField > ghFluid (fluidRegions.size())
PtrList< surfaceScalarField > ghfFluid (fluidRegions.size())
PtrList< compressible::turbulenceModel > turbulence (fluidRegions.size())
PtrList< volScalarField > p_rghFluid (fluidRegions.size())
PtrList< radiation::radiationModel > radiation (fluidRegions.size())
List< scalar > initialMassFluid (fluidRegions.size())
List< label > pRefCellFluid (fluidRegions.size(), 0)
List< scalar > pRefValueFluid (fluidRegions.size(), 0.0)
List< bool > frozenFlowFluid (fluidRegions.size(), false)
PtrList< dimensionedScalar > rhoMax (fluidRegions.size())
PtrList< dimensionedScalar > rhoMin (fluidRegions.size())
PtrList< IOMRFZoneList > MRFfluid (fluidRegions.size())
PtrList< fv::options > fluidFvOptions (fluidRegions.size())
forAll (fluidRegions, i)
Function Documentation
PtrList<rhoThermo> thermoFluid (fluidRegions. size())
Referenced by forAll().
PtrList<volScalarField> rhoFluid (fluidRegions. size())
Referenced by forAll().
PtrList<volVectorField> UFluid (fluidRegions. size())
Referenced by forAll().
PtrList<surfaceScalarField> phiFluid (fluidRegions. size())
Referenced by forAll().
PtrList<uniformDimensionedVectorField> gFluid (fluidRegions. size())
Referenced by forAll().
PtrList<uniformDimensionedScalarField> hRefFluid (fluidRegions. size())
Referenced by forAll().
PtrList<volScalarField> ghFluid (fluidRegions. size())
Referenced by forAll().
PtrList<surfaceScalarField> ghfFluid (fluidRegions. size())
Referenced by forAll().
PtrList<compressible::turbulenceModel> turbulence (fluidRegions. size())
Referenced by forAll().
PtrList<volScalarField> p_rghFluid (fluidRegions. size())
Referenced by forAll().
PtrList<radiation::radiationModel> radiation (fluidRegions. size())
Referenced by forAll().
List<scalar> initialMassFluid (fluidRegions. size())
Referenced by forAll().
List<label> pRefCellFluid (fluidRegions. size(), 0)
Referenced by forAll().
List<scalar> pRefValueFluid (fluidRegions. size(), 0. 0)
Referenced by forAll().
List<bool> frozenFlowFluid (fluidRegions. size(), false)
Referenced by forAll().
PtrList<dimensionedScalar> rhoMax (fluidRegions. size())
Referenced by forAll(), if(), WallSpringSliderDashpot< CloudType >::nSubCycles(), PairSpringSliderDashpot< CloudType >::nSubCycles(), WallLocalSpringSliderDashpot< CloudType >::nSubCycles(), and while().
PtrList<dimensionedScalar> rhoMin (fluidRegions. size())
Referenced by forAll(), if(), and while().
PtrList<IOMRFZoneList> MRFfluid (fluidRegions. size())
Referenced by forAll().
PtrList<fv::options> fluidFvOptions (fluidRegions. size())
Referenced by forAll().
forAll (fluidRegions , i)
Definition at line 26 of file createFluidFields.H.
References C, Foam::cmptMag(), Foam::dimDensity, Foam::dimLength, Foam::fvc::domainIntegrate(), Foam::endl(), fluidFvOptions(), fluidRegions(), frozenFlowFluid(), gFluid(), ghfFluid(), ghFluid(), hRefFluid(), Foam::Info, initialMassFluid(), Foam::linearInterpolate(), Foam::mag(), MRFfluid(), Foam::name(), Foam::New(), Foam::nl, p, p_rghFluid(), phiFluid(), pRefCellFluid(), pRefValueFluid(), radiation(), rho, rhoFluid(), rhoMax(), rhoMin(), Foam::setRefCell(), T, thermoFluid(), turbulence(), and UFluid().