OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setRegionSolidFields.H File Reference
Functions
if (!thermo.isotropic())
Variables
fvMesh & mesh = solidRegions[i]
solidThermo & thermo = thermos[i]
tmp< volScalarField > trho = thermo.rho()
const volScalarField & rho = trho()
tmp< volScalarField > tcp = thermo.Cp()
const volScalarField & cp = tcp()
tmp< volSymmTensorField > taniAlpha
volScalarField & h = thermo.he()
Planck constant.
const volScalarField & betav = betavSolid[i]
fv::options & fvOptions = solidHeatSources[i]
Function Documentation
if (!thermo. isotropic())
Definition at line 11 of file setRegionSolidFields.H.
References aniAlphas(), coordinates(), cp, and thermo.
Variable Documentation
fvMesh& mesh = solidRegions[i]
Definition at line 1 of file setRegionSolidFields.H.
solidThermo& thermo = thermos[i]
Definition at line 2 of file setRegionSolidFields.H.
Referenced by if().
tmp<volScalarField> trho = thermo.rho()
Definition at line 4 of file setRegionSolidFields.H.
Referenced by PaSR< Type >::correct(), forAll(), liquidFilmThermo::rho(), and constantFilmThermo::rho().
const volScalarField& rho = trho()
Definition at line 5 of file setRegionSolidFields.H.
tmp<volScalarField> tcp = thermo.Cp()
Definition at line 7 of file setRegionSolidFields.H.
Referenced by forAll().
const volScalarField& cp = tcp()
Definition at line 8 of file setRegionSolidFields.H.
Referenced by Foam::cp(), heThermo< BasicThermo, MixtureType >::Cp(), thermo< Thermo, Type >::Cp(), thermo< Thermo, Type >::cv(), chemistryModel< CompType, ThermoType >::derivatives(), forAll(), thermo< Thermo, Type >::gamma(), if(), triangle< Point, PointRef >::nearestPointClassify(), fvFieldReconstructor::reconstructFvSurfaceField(), and fvFieldReconstructor::reconstructFvVolumeField().
tmp<volSymmTensorField> taniAlpha
Definition at line 10 of file setRegionSolidFields.H.
volScalarField& h = thermo.he()
Planck constant.
Definition at line 28 of file setRegionSolidFields.H.
Referenced by normal::erfInv(), if(), SIBS::solve(), SVD::SVD(), and LISAAtomization< CloudType >::update().
const volScalarField& betav = betavSolid[i]
Definition at line 30 of file setRegionSolidFields.H.
Referenced by if(), and while().
fv::options& fvOptions = solidHeatSources[i]
Definition at line 32 of file setRegionSolidFields.H.