OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setRDeltaT.H File Reference
Functions
scalar rDeltaTSmoothingCoeff (runTime.controlDict().lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02))
rDeltaT ref ()
rDeltaT correctBoundaryConditions ()
Function Documentation
scalar rDeltaTSmoothingCoeff (runTime. controlDict).lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02)
rDeltaT ref ()
Referenced by polyTopoChanger::changeMesh(), Foam::fvc::div(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::operator==(), and polyTopoChanger::topoChangeRequest().
rDeltaT correctBoundaryConditions ()