OpenFOAM: applications/solvers/combustion/fireFoam/phrghEqn.H File Reference
phrghEqn.H File Reference
Functions
if (pimple.dict().lookupOrDefault< bool >("hydrostaticInitialization", false))
Function Documentation
if (pimple. dict).lookupOrDefault< bool >("hydrostaticInitialization", false)
Definition at line 1 of file phrghEqn.H.
References Foam::constrainPressure(), Foam::fvc::div(), Foam::endl(), Foam::equal(), gh, ghf, Foam::Info, Foam::MULES::interpolate(), Foam::fvc::laplacian(), Foam::max(), mesh, Foam::min(), nCorr, p, p_rgh, phig(), pimple, pRef, rho, rhof(), Foam::fvc::snGrad(), thermo, U, and Ostream::write().