OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
pcEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volScalarField rAtU (1.0/(1.0/rAU-UEqn.H1()))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
tUEqn clear ()
if (simple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
volScalarField rhorAtU ("rhorAtU", rho *rAtU)
constrainPressure (p, rho, U, phiHbyA, rhorAtU, MRF)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
if (!simple.transonic())
Variables
bool closedVolume = false
else
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
HbyA = (rAU - rAtU)*fvc::grad(p)
U = HbyA - rAtU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
volScalarField rAU (1.0/UEqn. A())
volScalarField rAtU (1.0/ 1.0/rAU-UEqn.H1())
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
tUEqn clear ()
Referenced by cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), ILList< LListBase, T >::clear(), DictionaryBase< IDLListType, T >::clear(), ZoneMesh< ZoneType, MeshType >::clear(), wordRe::clear(), LList< LListBase, T >::clear(), DSMCCloud< ParcelType >::DSMCCloud(), fieldExpression::execute(), sampledPatch::expire(), sampledTriSurfaceMesh::expire(), moleculeCloud::moleculeCloud(), UILList< LListBase, T >::operator=(), dictionary::parent(), reactingMixture< ThermoType >::reactingMixture(), extendedEdgeMeshFormat::read(), extendedFeatureEdgeMeshFormat::read(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), FTRsurfaceFormat< Face >::read(), edgeMeshFormat::read(), OFSsurfaceFormat< Face >::read(), STLsurfaceFormat< Face >::read(), GeometricField< Type, PatchField, GeoMesh >::Boundary::readField(), and singleStepReactingMixture< ThermoType >::singleStepReactingMixture().
if (simple. transonic())
Definition at line 8 of file pcEqn.H.
References Foam::fvc::div(), Foam::fvc::flux(), fvOptions, Foam::fvc::grad(), HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, MRF, p, phi, phic, phid(), pRefCell, pRefValue, psi, rAtU(), rAU(), rho, rhorAtU(), simple, and Foam::fvc::snGrad().
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
volScalarField rhorAtU ("rhorAtU" , rho * rAtU)
constrainPressure (p , rho , U , phiHbyA , rhorAtU , MRF)
while (simple. correctNonOrthogonal())
Definition at line 68 of file pcEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, pRefCell, pRefValue, psi, rho, rhorAtU(), and simple.
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
Definition at line 102 of file pcEqn.H.
References Foam::fvc::domainIntegrate(), initialMass, p, and psi.
if (!simple. transonic())
Definition at line 113 of file pcEqn.H.
References Foam::endl(), Foam::Info, Foam::max(), Foam::min(), and rho.
Variable Documentation
closedVolume = false
Definition at line 6 of file pcEqn.H.
else
Initial value:
{
    surfaceScalarField phiHbyA("phiHbyA", fvc::flux(rho*HbyA))
Definition at line 54 of file pcEqn.H.
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
Definition at line 60 of file pcEqn.H.
HbyA = (rAU - rAtU)*fvc::grad(p)
Definition at line 61 of file pcEqn.H.
U = HbyA - rAtU*fvc::grad(p)
Definition at line 96 of file pcEqn.H.
rho = thermo.rho()
Definition at line 109 of file pcEqn.H.