OpenFOAM: applications/solvers/lagrangian/icoUncoupledKinematicParcelFoam/createNonInertialFrameFields.H File Reference
createNonInertialFrameFields.H File Reference
Functions
if (linearAccelerationHeader.headerOk())
IOobject angularVelocityHeader ("angularVelocity", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
if (angularVelocityHeader.headerOk())
IOobject angularAccelerationHeader ("angularAcceleration", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
if (angularAccelerationHeader.headerOk())
IOobject centreOfRotationHeader ("centreOfRotation", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
if (centreOfRotationHeader.headerOk())
Variables
Info<< "Reading non-inertial frame fields"<< endl;IOobject linearAccelerationHeader("linearAcceleration", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE);autoPtr< uniformDimensionedVectorField > linearAccelerationPtr
autoPtr< uniformDimensionedVectorField > angularVelocityPtr
autoPtr< uniformDimensionedVectorField > angularAccelerationPtr
autoPtr< uniformDimensionedVectorField > centreOfRotationPtr
Function Documentation
if (linearAccelerationHeader. headerOk())
Definition at line 14 of file createNonInertialFrameFields.H.
References angularVelocityHeader(), Foam::endl(), Foam::Info, and mesh.
IOobject angularVelocityHeader ("angularVelocity" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
Referenced by if().
if (angularVelocityHeader. headerOk())
Definition at line 36 of file createNonInertialFrameFields.H.
References angularAccelerationHeader(), angularVelocityHeader(), Foam::endl(), Foam::Info, and mesh.
IOobject angularAccelerationHeader ("angularAcceleration" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
Referenced by if().
if (angularAccelerationHeader. headerOk())
Definition at line 58 of file createNonInertialFrameFields.H.
References angularAccelerationHeader(), centreOfRotationHeader(), Foam::endl(), Foam::Info, and mesh.
IOobject centreOfRotationHeader ("centreOfRotation" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
Referenced by if().
if (centreOfRotationHeader. headerOk())
Definition at line 80 of file createNonInertialFrameFields.H.
References centreOfRotationHeader(), Foam::endl(), and Foam::Info.
Variable Documentation
Info<< "Reading non-inertial frame fields" << endl; IOobject linearAccelerationHeader ("linearAcceleration", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE); autoPtr<uniformDimensionedVectorField> linearAccelerationPtr
Definition at line 12 of file createNonInertialFrameFields.H.
autoPtr<uniformDimensionedVectorField> angularVelocityPtr
Definition at line 34 of file createNonInertialFrameFields.H.
autoPtr<uniformDimensionedVectorField> angularAccelerationPtr
Definition at line 56 of file createNonInertialFrameFields.H.
autoPtr<uniformDimensionedVectorField> centreOfRotationPtr
Definition at line 78 of file createNonInertialFrameFields.H.