OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
zonePhaseVolumes.H File Reference
Functions
forAll (cellLabels, cli)
reduce (phaseVolume, sumOp< scalar >())
Variables
scalar phaseVolume = 0
Function Documentation
forAll (cellLabels , cli)
Definition at line 13 of file zonePhaseVolumes.H.
reduce (phaseVolume , sumOp< scalar > ())
Referenced by Foam::adjustPhi(), boundBox::boundBox(), FaceCellWave< Type, TrackingData >::cellToFace(), primitiveMesh::checkCellsZipUp(), primitiveMesh::checkCellVolumes(), primitiveMesh::checkClosedBoundary(), primitiveMesh::checkClosedCells(), primitiveMesh::checkConcaveCells(), primitiveMesh::checkEdgeLength(), primitiveMesh::checkFaceAngles(), primitiveMesh::checkFaceAreas(), primitiveMesh::checkFaceFaces(), primitiveMesh::checkFaceFlatness(), primitiveMesh::checkFaceOrthogonality(), primitiveMesh::checkFacePyramids(), primitiveMesh::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), primitiveMesh::checkFaceVertices(), primitiveMesh::checkPointNearness(), primitiveMesh::checkPoints(), primitiveMesh::checkUpperTriangular(), decompositionMethod::decompose(), KinematicCloud< CloudType >::Dij(), KinematicCloud< CloudType >::Dmax(), PointEdgeWave< Type, TrackingData >::edgeToPoint(), FaceCellWave< Type, TrackingData >::faceToCell(), PatchFlowRateInjection< CloudType >::flowRate(), meshRefinement::gAverage(), MPPICCloud< CloudType >::info(), CollidingCloud< CloudType >::info(), Cloud< ParticleType >::move(), KinematicCloud< CloudType >::penetration(), PointEdgeWave< Type, TrackingData >::pointToEdge(), decompositionMethod::setConstraints(), and extendedCellToFaceStencil::writeStencilStats().
Variable Documentation
scalar phaseVolume = 0
Definition at line 11 of file zonePhaseVolumes.H.