OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createPorousZones.H File Reference
Functions
IOporosityModelList pZones (mesh)
Switch pressureImplicitPorosity (false)
if (pZones.active())
Variables
int nUCorr = 0
Function Documentation
IOporosityModelList pZones (mesh)
Switch pressureImplicitPorosity (false)
Referenced by if().
if (pZones. active())
Definition at line 6 of file createPorousZones.H.
References Foam::endl(), Foam::Info, nUCorr, pressureImplicitPorosity(), and simple.
Variable Documentation
int nUCorr = 0
Definition at line 5 of file createPorousZones.H.
Referenced by if().