OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqns.H File Reference
Functions
PtrList< fvVectorMatrix > UEqns (fluid.phases().size())
autoPtr
< multiphaseSystem::dragCoeffFields > dragCoeffs (fluid.dragCoeffs())
volScalarField nuEff (turbulence->nut()+iter().nu())
UEqns set (phasei, new fvVectorMatrix(fvm::ddt(alpha, U)+fvm::div(phase.phiAlpha(), U)+(alpha/phase.rho())*fluid.Cvm(phase)*(fvm::ddt(U)+fvm::div(phase.phi(), U)-fvm::Sp(fvc::div(phase.phi()), U))-fvm::laplacian(alpha *nuEff, U)-fvc::div(alpha *(nuEff *dev(T(fvc::grad(U)))),"div(Rc)")==(alpha/phase.rho())*fluid.Svm(phase)-fvm::Sp(slamDampCoeff *max(mag(U.dimensionedInternalField())-maxSlamVelocity,)/pow(mesh.V(), 1.0/3.0), U)))
mrfZones addCoriolis (alpha *(1+(1/phase.rho())*fluid.Cvm(phase)), UEqns[phasei])
Variables
int phasei = 0
const volScalarField & alpha = phase
Fine-structure constant: default SI units: [].
volVectorField & U = phase.U()
Function Documentation
PtrList<fvVectorMatrix> UEqns (fluid. phases).size()
Referenced by for().
autoPtr<multiphaseSystem::dragCoeffFields> dragCoeffs (fluid. dragCoeffs())
volScalarField nuEff (turbulence-> nut)+iter().nu()
Referenced by dynamicKEqn< BasicTurbulenceModel >::Ce(), linearViscousStress< BasicTurbulenceModel >::devRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), Peclet::execute(), incompressibleTurbulenceModel::muEff(), and fixedShearStressFvPatchVectorField::updateCoeffs().
UEqns set (phasei , new fvVectorMatrixfvm::ddt(alpha, U)+fvm::div(phase.phiAlpha(), U)+(alpha/phase.rho())*fluid.Cvm(phase)*(fvm::ddt(U)+fvm::div(phase.phi(), U)-fvm::Sp(fvc::div(phase.phi()), U))-fvm::laplacian(alpha *nuEff, U)-fvc::div(alpha *(nuEff *dev(T(fvc::grad(U)))),"div(Rc)")==(alpha/phase.rho())*fluid.Svm(phase)-fvm::Sp(slamDampCoeff *max(mag(U.dimensionedInternalField())-maxSlamVelocity,)/pow(mesh.V(), 1.0/3.0), U))
mrfZones addCoriolis (alpha * 1+(1/phase.rho())*fluid.Cvm(phase), UEqns [phasei])
Variable Documentation
phasei = 0
Definition at line 6 of file UEqns.H.
const volScalarField& alpha = phase
Fine-structure constant: default SI units: [].
Definition at line 10 of file UEqns.H.
volVectorField& U = phase.U()
Definition at line 11 of file UEqns.H.