OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFluidMeshes.H File Reference
Functions
const wordList fluidNames (rp["fluid"])
PtrList< fvMesh > fluidRegions (fluidNames.size())
forAll (fluidNames, i)
Function Documentation
const wordList fluidNames (rp ["fluid"])
Referenced by forAll().
PtrList<fvMesh> fluidRegions (fluidNames. size())
Referenced by forAll().
forAll (fluidNames , i)
Definition at line 5 of file createFluidMeshes.H.
References Foam::endl(), fluidNames(), fluidRegions(), Foam::Info, and Foam::nl.