OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
alphaEqnSubCycle.H File Reference
Functions
if (icAlpha > 0)
volScalarField divU (fvc::div(phi))
if (nAlphaSubCycles > 1)
Variables
else
Function Documentation
if (icAlpha , 0)
Definition at line 6 of file alphaEqnSubCycle.H.
References Foam::fvc::div(), divU(), icAlpha(), interface(), Foam::MULES::interpolate(), Foam::mag(), phi, phic, and U.
volScalarField divU (fvc::div(phi))
Referenced by if().
if (nAlphaSubCycles , 1)
Definition at line 14 of file alphaEqnSubCycle.H.
References alpha1, nAlphaSubCycles(), and rhoPhi.
Variable Documentation
else
Definition at line 32 of file alphaEqnSubCycle.H.