OpenFOAM: src/finiteVolume/finiteVolume/gradSchemes/limitedGradSchemes/cellMDLimitedGrad/cellMDLimitedGrads.C File Reference
cellMDLimitedGrads.C File Reference
Functions
makeFvGradScheme (cellMDLimitedGrad)
Detailed Description
Original source file cellMDLimitedGrads.C
Definition in file cellMDLimitedGrads.C.
Function Documentation
makeFvGradScheme()
makeFvGradScheme (cellMDLimitedGrad)
Definition at line 36 of file cellMDLimitedGrads.C.
References C, cellMDLimitedGrad< Type >::calcGrad(), correctBoundaryConditions(), forAll, g, Foam::max(), mesh, Foam::min(), patchi, scalarField(), and vectorField().