OpenFOAM: applications/solvers/incompressible/boundaryFoam/evaluateNearWall.H File Reference
evaluateNearWall.H File Reference
Variables
scalar nut = turbulence->nut()().boundaryField()[patchId][faceId]
symmTensor R = turbulence->devReff()().boundaryField()[patchId][faceId]
Universal gas constant: default SI units: [J/mol/K].
scalar epsilon = turbulence->epsilon()()[cellId]
scalar k = turbulence->k()()[cellId]
Boltzmann constant.
scalar magUp = mag(U[cellId] - U.boundaryField()[patchId][faceId])
scalar tauw = flowDirection & R & wallNormal
scalar uTau = ::sqrt(mag(tauw))
scalar yPlus = uTau*y[cellId]/(nu + ROOTVSMALL)
scalar uPlus = magUp/(uTau + ROOTVSMALL)
scalar nutPlus = nut/nu
scalar kPlus = k/(sqr(uTau) + ROOTVSMALL)
scalar epsilonPlus = epsilon*nu/(pow4(uTau) + ROOTVSMALL)
scalar Rey = magUp*y[cellId]/nu
Variable Documentation
scalar nut = turbulence->nut()().boundaryField()[patchId][faceId]
Definition at line 5 of file evaluateNearWall.H.
Referenced by kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correct(), EddyDiffusivity< BasicTurbulenceModel >::correctNut(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), SpalartAllmarasDES< BasicTurbulenceModel >::k(), incompressibleTurbulenceModel::mut(), CompressibleTurbulenceModel< TransportModel >::mut(), PhaseCompressibleTurbulenceModel< Foam::phaseModel >::mut(), phasePressureModel::nuEff(), kineticTheoryModel::nuEff(), LESModel< BasicTurbulenceModel >::nuEff(), and RASModel< BasicTurbulenceModel >::nuEff().
symmTensor R = turbulence->devReff()().boundaryField()[patchId][faceId]
Universal gas constant: default SI units: [J/mol/K].
Definition at line 6 of file evaluateNearWall.H.
scalar epsilon = turbulence->epsilon()()[cellId]
Definition at line 7 of file evaluateNearWall.H.
Referenced by ThermoCloud< CloudType >::ap(), atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), ThermoParcel< ParcelType >::calcHeatTransfer(), PaSR< Type >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), ThermoCloud< CloudType >::Ep(), if(), turbulenceFields::omega(), ThermoCloud< CloudType >::sigmap(), StochasticDispersionRAS< CloudType >::update(), GradientDispersionRAS< CloudType >::update(), fWallFunctionFvPatchScalarField::updateCoeffs(), and ThermoSurfaceFilm< CloudType >::wetSplashInteraction().
scalar k = turbulence->k()()[cellId]
Boltzmann constant.
Definition at line 9 of file evaluateNearWall.H.
Referenced by BrownianMotionForce< CloudType >::calcCoupled(), MaxwellianThermal< CloudType >::correct(), DSMCCloud< ParcelType >::equipartitionInternalEnergy(), DSMCCloud< ParcelType >::equipartitionLinearVelocity(), FreeStream< CloudType >::inflow(), DSMCCloud< ParcelType >::maxwellianAverageSpeed(), DSMCCloud< ParcelType >::maxwellianMostProbableSpeed(), DSMCCloud< ParcelType >::maxwellianRMSSpeed(), VariableHardSphere< CloudType >::sigmaTcR(), LarsenBorgnakkeVariableHardSphere< CloudType >::sigmaTcR(), and dsmcFields::write().
scalar magUp = mag(U[cellId] - U.boundaryField()[patchId][faceId])
Definition at line 10 of file evaluateNearWall.H.
Referenced by nutUWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), nutUWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), and nutURoughWallFunctionFvPatchScalarField::yPlus().
scalar tauw = flowDirection & R & wallNormal
Definition at line 12 of file evaluateNearWall.H.
Referenced by ReynoldsStress< BasicTurbulenceModel >::correctWallShearStress().
scalar uTau = ::sqrt(mag(tauw))
Definition at line 14 of file evaluateNearWall.H.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
scalar yPlus = uTau*y[cellId]/(nu + ROOTVSMALL)
Definition at line 16 of file evaluateNearWall.H.
Referenced by epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
scalar uPlus = magUp/(uTau + ROOTVSMALL)
Definition at line 18 of file evaluateNearWall.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus().
scalar nutPlus = nut/nu
Definition at line 20 of file evaluateNearWall.H.
scalar kPlus = k/(sqr(uTau) + ROOTVSMALL)
Definition at line 22 of file evaluateNearWall.H.
scalar epsilonPlus = epsilon*nu/(pow4(uTau) + ROOTVSMALL)
Definition at line 24 of file evaluateNearWall.H.
scalar Rey = magUp*y[cellId]/nu
Definition at line 28 of file evaluateNearWall.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::yPlus().