OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
UEqns.H File Reference
Functions
PtrList< fvVectorMatrix > UEqns (fluid.phases().size())
autoPtr< multiphaseSystem::dragCoeffFields > dragCoeffs (fluid.dragCoeffs())
forAllIter (PtrDictionary< phaseModel >, fluid.phases(), iter)
Variables
int phasei = 0
Function Documentation
PtrList<fvVectorMatrix> UEqns (fluid. phases).size()
Referenced by forAll(), forAllIter(), and while().
autoPtr<multiphaseSystem::dragCoeffFields> dragCoeffs (fluid. dragCoeffs())
Referenced by forAllIter().
forAllIter (PtrDictionary< phaseModel > , fluid. phases(), iter)
fvm::Sp(fluid.dragCoeff(phase, dragCoeffs())/phase.rho(), U) (alpha*phase.rho())*fluid.lift(phase)
+
Definition at line 7 of file UEqns.H.
References Foam::constant::atomic::alpha, Foam::fvc::ddt(), Foam::dev(), Foam::dimVelocity, Foam::fvc::div(), fluid, Foam::fvc::grad(), Foam::fvc::laplacian(), Foam::mag(), Foam::max(), mesh, MRF, Foam::pow(), Foam::fvc::Sp(), T, turbulence, U, and UEqns().
Variable Documentation
int phasei = 0
Definition at line 6 of file UEqns.H.
Referenced by forAll().