OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
mergePatchPairs.H File Reference
Functions
List< pointZone * > pz (mergePatchPairs.size())
List< faceZone * > fz (3 *mergePatchPairs.size())
List< cellZone * > cz (0)
forAll (mergePatchPairs, pairI)
Function Documentation
List<pointZone*> pz (mergePatchPairs. size())
Referenced by displacementComponentLaplacianFvMotionSolver::curPoints(), displacementLaplacianFvMotionSolver::curPoints(), forAll(), and fvMeshDistribute::printMeshInfo().
List<faceZone*> fz (3 *mergePatchPairs. size())
Referenced by cellZoneSet::cellZoneSet(), layerAdditionRemoval::changeTopology(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), FacePostProcessing< CloudType >::FacePostProcessing(), faceZoneSet::faceZoneSet(), forAll(), pointZoneSet::pointZoneSet(), FacePostProcessing< CloudType >::postFace(), fvMeshDistribute::printMeshInfo(), decompositionMethod::setConstraints(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), meshRefinement::splitFaces(), and meshRefinement::zonify().
List<cellZone*> cz (0)
Referenced by interRegionExplicitPorositySource::initialise(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), fvMeshDistribute::printMeshInfo(), and meshRefinement::zonify().
forAll (mergePatchPairs , pairI)
Definition at line 10 of file mergePatchPairs.H.
References forAll, fz(), i, mesh, Foam::name(), and pz().