OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
getTimeIndex.H File Reference
Functions
if (optIndex)
else if (runTime.timeName()!=runTime.constant()&&runTime.timeName()!="0")
timeIndices insert (timeIndex, timeDirs[timeI].value())
Variables
label timeIndex = 0
Function Documentation
if (optIndex)
Definition at line 6 of file getTimeIndex.H.
References timeIndex.
else if (runTime.timeName()! = runTime.constant() && runTime.timeName() != "0")
Definition at line 11 of file getTimeIndex.H.
References Foam::endl(), Foam::Info, and timeIndex.
timeIndices insert (timeIndex , timeDirs. value()[timeI])
Referenced by IOobjectList::add(), distribution::add(), topoSet::addSet(), boundaryRegion::append(), cellTable::append(), dynamicIndexedOctree< Type >::dynamicIndexedOctree(), graph::graph(), HashPtrTable< T, Key, Hash >::HashPtrTable(), HashSet< Key, Hash >::HashSet(), HashSet< Key, Hash >::insert(), DictionaryBase< IDLListType, T >::insert(), cellShapeControlMesh::insert(), LList< DLListBase, Foam::entry * >::insert(), cellShapeControlMesh::insertFar(), distribution::insertMissingKeys(), topoSet::invert(), IOobjectList::IOobjectList(), CV2D::movePoint(), StaticHashTable< T, Key, Hash >::operator()(), HashTable< T, Key, Hash >::operator()(), HashPtrTable< T, Key, Hash >::operator=(), StaticHashTable< T, Key, Hash >::operator=(), HashTable< T, Key, Hash >::operator=(), HashSet< Key, Hash >::operator^=(), HashSet< Key, Hash >::operator|=(), faceCollapser::setRefinement(), and topoSet::subset().
Variable Documentation
label timeIndex = 0
Definition at line 4 of file getTimeIndex.H.
Referenced by externalCoupledMixedFvPatchField< Type >::evaluate(), if(), fvMesh::movePoints(), polyMesh::movePoints(), Time::operator++(), scalarRanges::selected(), layerAdditionRemoval::setRefinement(), sixDoFRigidBodyMotionSolver::solve(), GeometricField< Type, PatchField, GeoMesh >::storeOldTimes(), Time::subCycle(), linearValveLayersFvMesh::update(), linearValveFvMesh::update(), dynamicRefineFvMesh::update(), fixedFluxPressureFvPatchScalarField::updateCoeffs(), syringePressureFvPatchScalarField::updateCoeffs(), turbulentInletFvPatchField< Type >::updateCoeffs(), activeBaffleVelocityFvPatchVectorField::updateCoeffs(), oscillatingFixedValueFvPatchField< Type >::updateCoeffs(), and activePressureForceBaffleVelocityFvPatchVectorField::updateCoeffs().