OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
gmvOutputLagrangian.H File Reference
Functions
gmvFile<< "tracers "
<< particles.size()<< nl;forAllConstIter(Cloud
< passiveParticle >, particles,
iter){gmvFile<< iter().position().x()
<< ' ';}gmvFile<< nl;forAllConstIter(Cloud
< passiveParticle >, particles,
iter){gmvFile<< iter().position().y()
<< ' ';}gmvFile<< nl;forAllConstIter(Cloud
< passiveParticle >, particles,
iter){gmvFile<< iter().position().z()
<< ' ';}gmvFile<< nl;forAll(lagrangianScalarNames,
i){const word &name=lagrangianScalarNames[i];IOField
< scalar > fld (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
forAll (fld, n)
Function Documentation
gmvFile<< "tracers " << particles.size() << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().x() << ' ';}gmvFile << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().y() << ' ';}gmvFile << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().z() << ' ';}gmvFile << nl;forAll(lagrangianScalarNames, i){ const word& name = lagrangianScalarNames[i]; IOField<scalar> fld (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
Referenced by nearWallFields::createFields(), DataEntry< Type >::dimIntegrate(), DataEntry< Type >::dimValue(), mapDistribute::distribute(), for(), forAll(), globalIndex::gather(), triSurfaceMesh::getField(), distributedTriSurfaceMesh::getField(), faceSource::getFieldValues(), coalCloudList::hsTrans(), DataEntry< Type >::integrate(), pointToPointPlanarInterpolation::interpolate(), vtkMesh::interpolate(), surfaceInterpolateFields::interpolateFields(), fvMeshAdder::MapSurfaceFields(), fvMeshAdder::MapVolFields(), cyclicFvPatchField< Type >::neighbourPatchField(), cyclicAMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::nonOverlapPatchField(), mapDistribute::transform::operator()(), mapDistribute::transformPosition::operator()(), transformOp< PrimitivePatchType, Type, TrackingData >::operator()(), fvMeshDistribute::printFieldInfo(), turbulenceFields::processField(), mappedPatchBase::readListOrField(), coalCloudList::rhoTrans(), cuttingPlane::sample(), nearWallFields::sampleFields(), mappedPatchBase::samplePoints(), globalIndex::scatter(), coalCloudList::Srho(), solutionControl::storePrevIter(), cyclicPointPatchField< Type >::swapAddSeparated(), cyclicACMIPointPatchField< Type >::swapAddSeparated(), cyclicAMIPointPatchField< Type >::swapAddSeparated(), vectorTensorTransform::transform(), STARCDCoordinateRotation::transformVector(), EulerCoordinateRotation::transformVector(), axesRotation::transformVector(), localAxesRotation::transformVector(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValueFvPatchField< Type >::updateCoeffs(), fvPatchField< Type >::updateCoeffs(), coalCloudList::UTrans(), DataEntry< Type >::value(), vtkSetWriter< Type >::write(), ensightSetWriter< Type >::write(), regionSizeDistribution::write(), rotorDiskSource::writeField(), TableBase< Type >::x(), and TableBase< Type >::y().
forAll (fld , n)
Initial value:
{
        gmvFile << name + "x" << nl
Definition at line 41 of file gmvOutputLagrangian.H.
References fld(), and n.