OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
getFieldScalar.H File Reference
Functions
if (nVar >=Num_variables-nSprayVariables)
IOobject fieldObjectPtr (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::NO_READ)
IOobject fieldObject (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE)
volScalarField scalarField (fieldObject, mesh)
if (which_type==Z_HEX08)
Variables
const cellShapeList & cellShapes = meshPtr->cellShapes()
Function Documentation
if (nVar >=Num_variables- nSprayVariables)
Definition at line 2 of file getFieldScalar.H.
IOobject fieldObjectPtr (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::NO_READ)
IOobject fieldObject (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::NO_WRITE)
Referenced by fieldToCell::applyToSet(), for(), and USERD_get_var_value_at_specific().
volScalarField scalarField (fieldObject , mesh)
Referenced by alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField(), thermalDiffusivity< TransportModel >::alphat(), primitiveMeshTools::cellDeterminant(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::CpByCpv(), heThermo< BasicThermo, MixtureType >::Cpv(), heThermo< BasicThermo, MixtureType >::Cv(), energyJumpAMIFvPatchScalarField::energyJumpAMIFvPatchScalarField(), energyJumpFvPatchScalarField::energyJumpFvPatchScalarField(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), primitiveMeshTools::faceOrthogonality(), polyMeshTools::faceOrthogonality(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTools::faceWeights(), fanFvPatchField< Type >::fanFvPatchField(), filmPyrolysisTemperatureCoupledFvPatchScalarField::filmPyrolysisTemperatureCoupledFvPatchScalarField(), fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), for(), forAll(), heThermo< BasicThermo, MixtureType >::gamma(), genericFvPatchField< Type >::genericFvPatchField(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField(), heThermo< BasicThermo, MixtureType >::he(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), if(), inclinedFilmNusseltHeightFvPatchScalarField::inclinedFilmNusseltHeightFvPatchScalarField(), inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField(), TableBase< Type >::interpolator(), temperatureCoupledBase::kappa(), MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField(), laminar< BasicTurbulenceModel >::nut(), chemistryModel< CompType, ThermoType >::omega(), phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField(), prghPressureFvPatchScalarField::prghPressureFvPatchScalarField(), radiationCoupledBase::radiationCoupledBase(), lduMatrix::residual(), basicSymmetryFvPatchField< Type >::snGrad(), symmetryPlaneFvPatchField< Type >::snGrad(), Foam::stabilise(), heThermo< BasicThermo, MixtureType >::THE(), timeVaryingAlphaContactAngleFvPatchScalarField::theta(), constantAlphaContactAngleFvPatchScalarField::theta(), dynamicAlphaContactAngleFvPatchScalarField::theta(), totalPressureFvPatchScalarField::totalPressureFvPatchScalarField(), totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField(), turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField(), uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField(), uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField(), CellZoneInjection< CloudType >::updateMesh(), USERD_get_var_value_at_specific(), variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField(), polyMeshTools::volRatio(), wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField(), and waveSurfacePressureFvPatchScalarField::waveSurfacePressureFvPatchScalarField().
if (which_type = = Z_HEX08)
Definition at line 38 of file getFieldScalar.H.
References Foam::hex(), and scalarField().
Variable Documentation
const cellShapeList& cellShapes = meshPtr->cellShapes()
Definition at line 35 of file getFieldScalar.H.
Referenced by hexCellLooper::cut(), topoCellLooper::cut(), forAll(), if(), USERD_get_gold_part_build_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_part_element_ids_by_type(), and USERD_get_part_elements_by_type().