OpenFOAM-dev: applications/utilities/mesh/conversion/kivaToFoam/checkPatch.H File Reference 2
checkPatch.H File Reference
Functions
if (bci!=0)
Variables
else
Function Documentation
if (bci! = 0)
Definition at line 1 of file checkPatch.H.
References forAll, fv(), idface(), Foam::mag(), Foam::max(), pFaces, points, quadFace(), triFace(), and y.
Variable Documentation
else
Initial value:
{
        FatalErrorInFunction
            << "bc not defined for active cell = " << i
            << exit(FatalError)
Definition at line 90 of file checkPatch.H.