OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Creating reaction
model\n"<< endl;autoPtr
< combustionModels::psiCombustionModel > reaction (combustionModels::psiCombustionModel::New(mesh))
thermo validate (args.executable(),"h","e")
word inertSpecie (thermo.lookup("inertSpecie"))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh), thermo.rho())
Info<< "Reading field U\n"
<< endl;volVectorField U(IOobject("U",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);volScalarField
&p=thermo.p();const
volScalarField &psi=thermo.psi();const
volScalarField &T=thermo.T();Info
<< "Creating turbulence
model.\n"<< nl;autoPtr
< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
reaction setTurbulence (turbulence())
forAll (Y, i)
fields add (thermo.he())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh,)
Variables
psiReactionThermo & thermo = reaction->thermo()
basicMultiComponentMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
Info<< "Creating field dpdt\n"
<< endl;volScalarField dpdt(IOobject("dpdt",
runTime.timeName(), mesh),
mesh,);Info<< "Creating field
kinetic energy K\n"<< endl;volScalarField
K("K", 0.5 *magSqr(U));multivariateSurfaceInterpolationScheme
< scalar >::fieldTable fields
Function Documentation
Info<< "Creating reaction model\n" << endl;autoPtr<combustionModels::psiCombustionModel> reaction (combustionModels::psiCombustionModel:: Newmesh)
Referenced by singleStepReactingMixture< ThermoType >::calculateMaxProducts(), singleStepReactingMixture< ThermoType >::calculateqFuel(), forAll(), singleStepReactingMixture< ThermoType >::fresCorrect(), mixtureFractionSoot< ThermoType >::mixtureFractionSoot(), Foam::operator<<(), solidReaction< ReactionThermo >::write(), and Reaction< ReactionThermo >::write().
thermo validate (args. executable(), "h" , "e")
word inertSpecie (thermo. lookup"inertSpecie")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh) , thermo. rho())
Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);volScalarField& p = thermo.p();const volScalarField& psi = thermo.psi();const volScalarField& T = thermo.T();Info << "Creating turbulence model.\n" << nl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel:: Newrho, U, phi, thermo)
reaction setTurbulence (turbulence())
forAll (Y , i)
Definition at line 83 of file createFields.H.
References i.
fields add (thermo. he())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh)
Variable Documentation
psiReactionThermo& thermo = reaction->thermo()
Definition at line 8 of file createFields.H.
basicMultiComponentMixture& composition = thermo.composition()
Definition at line 11 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 12 of file createFields.H.
Info<< "Creating field dpdt\n" << endl;volScalarField dpdt(IOobject ("dpdt", runTime.timeName(), mesh), mesh,);Info<< "Creating field kinetic energy K\n" << endl;volScalarField K("K", 0.5*magSqr(U));multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 81 of file createFields.H.