OpenFOAM-dev: applications/solvers/stressAnalysis/solidEquilibriumDisplacementFoam/kineticEnergyLimiter.H File Reference 2
kineticEnergyLimiter.H File Reference
Functions
if (!(runTime.timeIndex()%5))
Function Documentation
if (! runTime.timeIndex()%5)
Definition at line 1 of file kineticEnergyLimiter.H.
References Foam::fvc::domainIntegrate(), Foam::endl(), Foam::Info, Foam::magSqr(), and Foam::Zero.