OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToEnsightParts/getTimeIndex.H File Reference
getTimeIndex.H File Reference
Functions
if (optIndex)
else if (runTime.timeName()!=runTime.constant()&&runTime.timeName()!="0")
timeIndices insert (timeIndex, timeDirs[timeI].value())
Variables
label timeIndex = 0
Function Documentation
if (optIndex)
Definition at line 6 of file getTimeIndex.H.
References timeIndex.
else if (runTime.timeName()! = runTime.constant() && runTime.timeName() != "0")
Definition at line 11 of file getTimeIndex.H.
References Foam::endl(), Foam::Info, Foam::nl, timeDirs, and timeIndex.
timeIndices insert (timeIndex , timeDirs. value()[timeI])
Referenced by dynamicIndexedOctree< Type >::dynamicIndexedOctree(), graph::graph(), DictionaryBase< IDLListType, T >::insert(), cellShapeControlMesh::insert(), LList< Foam::chemPointISAT< CompType, ThermoType > * >::insert(), cellShapeControlMesh::insertFar(), CV2D::movePoint(), StaticHashTable< T, Key, Hash >::operator()(), HashTable< T, Key, Hash >::operator()(), and graph::wordify().
Variable Documentation
label timeIndex = 0
Definition at line 4 of file getTimeIndex.H.
Referenced by externalCoupledMixedFvPatchField< Type >::evaluate(), if(), fvMesh::movePoints(), polyMesh::movePoints(), Time::operator++(), scalarRanges::selected(), layerAdditionRemoval::setRefinement(), sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotion::solve(), GeometricField< Type, PatchField, GeoMesh >::storeOldTimes(), Time::subCycle(), ensightMesh::uniquePointMap(), linearValveFvMesh::update(), linearValveLayersFvMesh::update(), dynamicRefineFvMesh::update(), fixedFluxPressureFvPatchScalarField::updateCoeffs(), turbulentInletFvPatchField< Type >::updateCoeffs(), syringePressureFvPatchScalarField::updateCoeffs(), and plenumPressureFvPatchScalarField::updateCoeffs().