OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading field U\n"
<< endl;volVectorField U(IOobject("U",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);singlePhaseTransportModel
laminarTransport(U, phi);dimensionedScalar
rhoInfValue(laminarTransport.lookup("rhoInf"));volScalarField
rhoInf(IOobject("rho",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::AUTO_WRITE), mesh,
rhoInfValue);autoPtr
< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, laminarTransport))
volScalarField mu (IOobject("mu", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), laminarTransport.nu()*rhoInfValue)
word kinematicCloudName ("kinematicCloud")
args optionReadIfPresent ("cloudName", kinematicCloudName)
HPtr reset (new volVectorField(Hheader, mesh))
IOobject HdotGradHheader ("HdotGradH", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE)
HdotGradHPtr reset (new volVectorField(HdotGradHheader, mesh))
Variables
Info<< "Constructing
kinematicCloud "
<< kinematicCloudName<< endl;basicKinematicCollidingCloud
kinematicCloud(kinematicCloudName,
rhoInf, U, mu, g);IOobject
Hheader("H", runTime.timeName(),
mesh, IOobject::MUST_READ,
IOobject::AUTO_WRITE);autoPtr
< volVectorField > HPtr
autoPtr< volVectorField > HdotGradHPtr
Function Documentation
Info<< "Reading field U\n" << endl; volVectorField U (IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); singlePhaseTransportModel laminarTransport(U, phi); dimensionedScalar rhoInfValue (laminarTransport.lookup("rhoInf")); volScalarField rhoInf (IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, rhoInfValue); autoPtr<incompressible::turbulenceModel> turbulence (incompressible::turbulenceModel:: NewU, phi, laminarTransport)
volScalarField mu (IOobject("mu", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , laminarTransport.nu()* rhoInfValue)
word kinematicCloudName ("kinematicCloud")
args optionReadIfPresent ("cloudName" , kinematicCloudName)
HPtr reset (new volVectorFieldHheader, mesh)
Referenced by extendedEdgeMesh::add(), autoPtr< T >::clear(), extendedEdgeMesh::flipNormals(), MeshedSurface< Face >::MeshedSurface(), MRFZoneList::MRFZoneList(), dimensionSet::operator*=(), dimensionSet::operator/=(), autoPtr< T >::operator=(), porosityModelList::porosityModelList(), OFFsurfaceFormat< Face >::read(), UnsortedMeshedSurface< Face >::reset(), primitiveMesh::reset(), surfMesh::resetPrimitives(), extendedEdgeMesh::sortPointsAndEdges(), UnsortedMeshedSurface< Face >::transfer(), and MeshedSurface< Face >::transfer().
IOobject HdotGradHheader ("HdotGradH" , runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::AUTO_WRITE)
HdotGradHPtr reset (new volVectorFieldHdotGradHheader, mesh)
Variable Documentation
Info<< "Constructing kinematicCloud " << kinematicCloudName << endl; basicKinematicCollidingCloud kinematicCloud (kinematicCloudName, rhoInf, U, mu, g); IOobject Hheader ("H", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE); autoPtr<volVectorField> HPtr
Definition at line 78 of file createFields.H.
autoPtr<volVectorField> HdotGradHPtr
Definition at line 96 of file createFields.H.