OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading thermophysical
properties\n"<< endl;autoPtr
< psiThermo > pThermo (psiThermo::New(mesh))
bool inviscid (true)
if (max(mu.internalField()) > 0.0)
Variables
psiThermo & thermo = pThermo()
volScalarField & p = thermo.p()
volScalarField & e = thermo.he()
Elementary charge.
const volScalarField & T = thermo.T()
const volScalarField & psi = thermo.psi()
const volScalarField & mu = thermo.mu()
Atomic mass unit.
Info<< "Reading field U\n"
<< endl;volVectorField U(IOobject("U",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);#35"/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/compressible/rhoCentralFoam/createFields.H"2volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho(), rhoBoundaryTypes);volVectorField rhoU(IOobject("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *U);volScalarField rhoE(IOobject("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *(e+0.5 *magSqr(U)));surfaceScalarField pos(IOobject("pos", runTime.timeName(), mesh), mesh,);surfaceScalarField neg(IOobject("neg", runTime.timeName(), mesh), mesh,);surfaceScalarField phi("phi", mesh.Sf()&fvc::interpolate(rhoU));Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Function Documentation
Info<< "Reading thermophysical properties\n" << endl;autoPtr<psiThermo> pThermo (psiThermo:: Newmesh)
bool inviscid (true)
Referenced by if().
if (max(mu.internalField()) , 0. 0)
Definition at line 16 of file createFields.H.
References inviscid().
Variable Documentation
psiThermo& thermo = pThermo()
Definition at line 7 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 9 of file createFields.H.
volScalarField& e = thermo.he()
Elementary charge.
Definition at line 10 of file createFields.H.
const volScalarField& T = thermo.T()
Definition at line 11 of file createFields.H.
const volScalarField& psi = thermo.psi()
Definition at line 12 of file createFields.H.
const volScalarField& mu = thermo.mu()
Atomic mass unit.
Definition at line 13 of file createFields.H.
Referenced by interRegionExplicitPorositySource::addSup(), constTransport< Thermo >::alphah(), forces::calcForcesMoment(), tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::circumRadius(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), Foam::interpolateSplineXY(), constTransport< Thermo >::kappa(), sutherlandTransport< Thermo >::kappa(), liquidMixtureProperties::mu(), filmViscosityModel::New(), fluidThermo::nu(), BSpline::position(), CatmullRomSpline::position(), polyLine::position(), SprayParcel< ParcelType >::readFields(), laminar::Su(), ReitzKHRT< CloudType >::update(), SHF< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), splineInterpolationWeights::valueWeights(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), and SprayParcel< ParcelType >::writeFields().
Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);# 35 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/compressible/rhoCentralFoam/createFields.H" 2volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho(), rhoBoundaryTypes);volVectorField rhoU(IOobject ("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho*U);volScalarField rhoE(IOobject ("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho*(e + 0.5*magSqr(U)));surfaceScalarField pos(IOobject ("pos", runTime.timeName(), mesh), mesh,);surfaceScalarField neg(IOobject ("neg", runTime.timeName(), mesh), mesh,);surfaceScalarField phi("phi", mesh.Sf() & fvc::interpolate(rhoU));Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence(compressible::turbulenceModel::New(rho,U,phi,thermo))
Definition at line 105 of file createFields.H.