OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading field psi\n"
<< endl;volScalarField psi(IOobject("psi",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);Info
<< "Reading
transportProperties\n"<< endl;IOdictionary
transportProperties(IOobject("transportProperties",
runTime.constant(), mesh,
IOobject::MUST_READ_IF_MODIFIED,
IOobject::NO_WRITE));List
< magnet > magnets (transportProperties.lookup("magnets"))
surfaceScalarField murf (IOobject("murf", runTime.timeName(), mesh), mesh, 1)
surfaceScalarField Mrf (IOobject("Mrf", runTime.timeName(), mesh), mesh,)
forAll (magnets, i)
Function Documentation
Info<< "Reading field psi\n" << endl; volScalarField psi (IOobject ("psi", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); Info<< "Reading transportProperties\n" << endl; IOdictionary transportProperties (IOobject ("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); List<magnet> magnets (transportProperties. lookup"magnets")
Referenced by forAll().
surfaceScalarField murf (IOobject("murf", runTime.timeName(), mesh) , mesh , 1)
Referenced by forAll().
surfaceScalarField Mrf (IOobject("Mrf", runTime.timeName(), mesh) , mesh)
Referenced by forAll().
forAll (magnets , i)
Definition at line 55 of file createFields.H.
References args, argList::executable(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, forAll, i, magnets(), mesh, Mrf(), murf(), Foam::name(), and transportProperties().