OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
readTransportProperties.H File Reference
Functions
singlePhaseTransportModel laminarTransport (U, phi)
dimensionedScalar beta (laminarTransport.lookup("beta"))
dimensionedScalar TRef (laminarTransport.lookup("TRef"))
dimensionedScalar Pr (laminarTransport.lookup("Pr"))
dimensionedScalar Prt (laminarTransport.lookup("Prt"))
Function Documentation
singlePhaseTransportModel laminarTransport (U , phi)
dimensionedScalar beta (laminarTransport. lookup"beta")
Referenced by ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), TrajectoryCollision< CloudType >::collideParcels(), rotorDiskSource::constructGeometry(), kOmegaSST< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), Analytical< Type >::integrate(), triangleFuncs::intersectAxesBundle(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeInjection< CloudType >::setProperties(), PBiCICG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCCCG< Type, DType, LUType >::solve(), PBiCG::solve(), PCG::solve(), FacePostProcessing< CloudType >::write(), and ParticleCollector< CloudType >::write().
dimensionedScalar TRef (laminarTransport. lookup"TRef")
dimensionedScalar Pr (laminarTransport. lookup"Pr")
Referenced by ThermoParcel< ParcelType >::calc(), SRIFallOffFunction::operator()(), TroeFallOffFunction::operator()(), FallOffReactionRate< ReactionRate, FallOffFunction >::operator()(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::operator()(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
dimensionedScalar Prt (laminarTransport. lookup"Prt")