OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
gmvOutputHeader.H File Reference
Variables
const pointField & points = mesh.points()
label nPoints = points.size()
const cellShapeList & cells = mesh.cellShapes()
Variable Documentation
const pointField& points = mesh.points()
Definition at line 1 of file gmvOutputHeader.H.
Referenced by extendedEdgeMesh::add(), cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::allNearestFeaturePoints(), setAndNormalToFaceZone::applyToSet(), PatchTools::calcBounds(), faceZone::calcFaceZonePatch(), processorPolyPatch::calcGeometry(), polyMesh::cellTree(), boundaryMesh::changeFaces(), polyMesh::checkEdgeAlignment(), primitiveMesh::checkEdgeLength(), primitiveMesh::checkFaceAngles(), primitiveMesh::checkFaceFlatness(), primitiveMesh::checkFacePyramids(), MeshedSurface< Face >::checkFaces(), polyMesh::checkFaceSkewness(), primitiveMesh::checkFaceSkewness(), primitiveMesh::checkPointNearness(), triSurface::checkTriangles(), pointConstraints::constrainDisplacement(), inversePointDistanceDiffusivity::correct(), pointLinear< Type >::correction(), removePoints::countPointUsage(), cyclicPolyPatch::coupledPoints(), displacementMeshMoverMotionSolver::curPoints(), hexCellLooper::cut(), geomCellLooper::cut(), simpleGeomDecomp::decompose(), triSurfaceTools::delaunay2D(), distributedTriSurfaceMesh::distribute(), extendedEdgeMesh::edgeTree(), extendedEdgeMesh::edgeTreesByType(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), searchablePlateFeatures::features(), cellVolumeWeightMethod::findInitialSeeds(), directMethod::findInitialSeeds(), sampledSet::findNearFace(), extendedEdgeMesh::flipNormals(), faceCorrectedSnGrad< Type >::fullGradCorrection(), boundaryMesh::getNearest(), boundaryMesh::getNPoints(), boundaryMesh::getNTris(), coupledPolyPatch::getRotation(), if(), isoSurfaceCell::interpolate(), isoSurface::interpolate(), sampledPlane::interpolateField(), sampledIsoSurfaceCell::interpolateField(), sampledThresholdCellFaces::interpolateField(), sampledPatchInternalField::interpolateField(), sampledPatch::interpolateField(), meshToMeshMethod::maskCells(), meshTriangulation::meshTriangulation(), layeredEngineMesh::move(), medialAxisMeshMover::move(), pointMesh::movePoints(), curvedEdge::New(), surfMesh::nPoints(), polyMesh::pointInCell(), primitiveMesh::pointInCellBB(), searchableSurfaceCollection::points(), extendedEdgeMesh::pointTree(), Foam::polyMeshZipUpCells(), BSpline::position(), CatmullRomSpline::position(), polyLine::position(), sampledPatchInternalField::print(), sampledPlane::print(), sampledCuttingPlane::print(), distanceSurface::print(), sampledPatch::print(), sampledTriSurfaceMesh::print(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectFaceCentres(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints(), face::ray(), NASedgeFormat::read(), STARCDsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), MeshedSurfaceIOAllocator::reset(), cyclicAMIPolyPatch::resetAMI(), polyMesh::resetPrimitives(), MeshedSurface< Face >::scalePoints(), patchInjectionBase::setPositionAndCell(), refinementIterator::setRefinement(), faceCollapser::setRefinement(), cellDistFuncs::smallestDist(), displacementMeshMoverMotionSolver::solve(), displacementLayeredMotionMotionSolver::solve(), extendedEdgeMesh::sortPointsAndEdges(), sixDoFRigidBodyMotion::transform(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), boundaryMesh::triangulate(), MeshedSurface< Face >::triangulate(), boundaryMesh::triangulateLocal(), triSurfaceMeshPointSet::triSurfaceMeshPointSet(), mixerFvMesh::update(), movingConeTopoFvMesh::update(), sampledPatch::update(), sampledSurfaces::update(), cellMotionFvPatchField< Type >::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), patchInjectionBase::updateMesh(), componentDisplacementMotionSolver::updateMesh(), displacementMotionSolver::updateMesh(), surfMesh::updatePointsRef(), USERD_get_gold_part_build_info(), USERD_get_maxsize_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_part_coords(), USERD_get_part_element_ids_by_type(), USERD_get_part_elements_by_type(), USERD_get_part_node_ids(), proxySurfaceWriter::write(), ensightSurfaceWriter::write(), starcdSurfaceWriter::write(), MeshedSurfaceProxy< Face >::write(), triSurface::write(), extendedEdgeMesh::writeObj(), edgeMesh::writeStats(), triSurface::writeStats(), MeshedSurface< Face >::writeStats(), extendedEdgeMesh::writeStats(), boundaryMesh::writeTriSurface(), and faceSource::writeValues().
label nPoints = points.size()
Definition at line 2 of file gmvOutputHeader.H.
Referenced by autoLayerDriver::addLayers(), face::average(), dynamicRefineFvMesh::cellToPoint(), face::centre(), primitiveMesh::checkEdgeLength(), primitiveMesh::checkFaceVertices(), inversePointDistanceDiffusivity::correct(), pointPatchDist::correct(), cyclicPolyPatch::coupledPoints(), STARCD::cullPoints(), displacementInterpolationMotionSolver::curPoints(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), triSurfaceMesh::edgeTree(), globalMeshData::globalPointNumbering(), if(), processorPolyPatch::initUpdateMesh(), PointEdgeWave< Type, TrackingData >::iterate(), primitiveMesh::makeFaceCentresAndAreas(), dynamicRefineFvMesh::maxCellField(), primitiveMesh::movePoints(), face::nearestPointClassify(), face::normal(), searchableSurfaceCollection::points(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints(), face::ray(), GTSsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), STARCD::readPoints(), primitiveMesh::reset(), polyMesh::resetPrimitives(), boundaryMesh::setFeatureEdges(), meshCutAndRemove::setRefinement(), edgeCollapser::setRefinement(), sixDoFRigidBodyMotionSolver::solve(), triSurface::subsetMeshMap(), face::sweptVol(), syncTools::syncPointMap(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), processorPolyPatch::updateMesh(), USERD_get_gold_part_build_info(), USERD_get_maxsize_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_nsided_conn(), USERD_get_part_coords(), USERD_get_part_element_ids_by_type(), USERD_get_part_elements_by_type(), USERD_get_part_node_ids(), PrimitivePatch< Face, FaceList, PointField, PointType >::whichEdge(), vtkSetWriter< Type >::write(), triSurface::writeStats(), and distributedTriSurfaceMesh::writeStats().
const cellShapeList& cells = mesh.cellShapes()
Definition at line 3 of file gmvOutputHeader.H.
Referenced by MRFZone::addCoriolis(), targetCoeffTrim::calcCoeffs(), fixedCoeff::calcTranformModelData(), DarcyForchheimer::calcTranformModelData(), primitiveMesh::cellCells(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), FaceCellWave< Type, TrackingData >::cellToFace(), primitiveMeshGeometry::checkCellDeterminant(), polyMeshGeometry::checkCellDeterminant(), primitiveMesh::checkCellsZipUp(), primitiveMesh::checkClosedCells(), primitiveMesh::checkConcaveCells(), primitiveMesh::checkFacePyramids(), primitiveMesh::checkUpperTriangular(), edgeCollapser::consistentCollapse(), outletStabilised< Type >::correction(), hexCellLooper::cut(), dynamicRefineFvMesh::extendMarkedCells(), surfaceSets::getHangingCells(), MPPICCloud< CloudType >::info(), sampledTriSurfaceMesh::interpolateField(), MRFZone::makeAbsolute(), MRFZone::makeRelative(), meshToMeshMethod::maskCells(), regionModel1D::moveMesh(), polyMesh::pointInCell(), primitiveMesh::pointInCellBB(), polyMesh::polyMesh(), polyMesh::readUpdate(), sampledTriSurfaceMesh::sampleField(), refinementIterator::setRefinement(), edgeCollapser::setRefinement(), fvMatrix< Type >::setValuesFromList(), thermalBaffle::solveEnergy(), thermoSingleLayer::Srho(), reactingOneDim::updatePhiGas(), reactingOneDim::updateQr(), USERD_get_gold_part_build_info(), USERD_get_maxsize_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_part_element_ids_by_type(), USERD_get_part_elements_by_type(), USERD_get_var_by_component(), and outletStabilised< Type >::weights().