OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
readConversionProperties.H File Reference
Functions
IOdictionary conversionProperties (IOobject("conversionProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
scalar startTime (readScalar(conversionProperties.lookup("startTime")))
word vComp (conversionProperties.lookup("vector"))
word format (conversionProperties.lookup("format"))
if ((format!="ascii")&&(format!="ieeei4r8"))
word cells (conversionProperties.lookup("cells"))
if ((cells!="hex"))
Function Documentation
IOdictionary conversionProperties (IOobject("conversionProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
scalar startTime (readScalar(conversionProperties.lookup("startTime")))
word vComp (conversionProperties. lookup"vector")
Referenced by for().
word format (conversionProperties. lookup"format")
Referenced by if(), ensightFile::newline(), UIPstream::read(), ISstream::read(), regionSizeDistribution::read(), ensightFile::write(), OSstream::write(), UOPstream::write(), and ensightFile::writeBinaryHeader().
if ((format!="ascii")&&(format!="ieeei4r8"))
Definition at line 29 of file readConversionProperties.H.
References Foam::abort(), Foam::FatalError, and format().
word cells (conversionProperties. lookup"cells")
Referenced by if().
if ((cells!="hex"))
Definition at line 44 of file readConversionProperties.H.
References Foam::abort(), cells(), and Foam::FatalError.