OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
gmvOutputSpray.H File Reference
Functions
gmvFile<< "tracers "<< particles.size()<< nl;forAllConstIter(Cloud< passiveParticle >, particles, iter){gmvFile<< iter().position().x()<< " ";}gmvFile<< nl;forAllConstIter(Cloud< passiveParticle >, particles, iter){gmvFile<< iter().position().y()<< " ";}gmvFile<< nl;forAllConstIter(Cloud< passiveParticle >, particles, iter){gmvFile<< iter().position().z()<< " ";}gmvFile<< nl;forAll(lagrangianScalarNames, i){word name=lagrangianScalarNames[i];IOField< scalar > s (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
if (s.size())
Function Documentation
gmvFile<< "tracers " << particles.size() << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().x() << " ";}gmvFile << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().y() << " ";}gmvFile << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().z() << " ";}gmvFile << nl;forAll(lagrangianScalarNames, i){ word name = lagrangianScalarNames[i]; IOField<scalar> s (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
Referenced by thermo< Thermo, Type >::a(), greyMeanAbsorptionEmission::aCont(), ThermoParcel< ParcelType >::calcHeatTransfer(), triSurfaceTools::calcInterpolationWeights(), primitiveMeshGeometry::checkFaceDotProduct(), Foam::cmptAv(), Foam::cmptMax(), Foam::cmptMin(), Foam::component(), rotorDiskSource::constructGeometry(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), particle< Type >::correctAfterParallelTransfer(), diaedg(), Foam::dot(), molecule::constantProperties::electrostaticSite(), VectorSpaceOps< N, I >::eqOpS(), calcEntry::execute(), Foam::stringOps::expand(), cellQuality::faceNonOrthogonality(), sampledIsoSurfaceCell::faces(), sampledCuttingPlane::faces(), distanceSurface::faces(), sampledIsoSurface::faces(), Field< Type >::Field(), searchableSurfaceCollection::findLine(), thermo< Thermo, Type >::g(), Foam::gAverage(), triSurfaceMesh::getNormal(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), if(), Foam::stringOps::inplaceExpand(), Foam::stringOps::inplaceTrim(), Foam::stringOps::inplaceTrimLeft(), Foam::stringOps::inplaceTrimRight(), Dual< Type >::interpolateGrad(), triangleFuncs::intersectAxesBundle(), treeBoundBox::intersects(), Foam::inv(), List< T >::List(), Foam::LUDecompose(), Foam::magSqr(), SVD::minNonZeroS(), molecule::move(), multiNormal::multiNormal(), line< Point, PointRef >::nearestDist(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), entry::New(), cellQuality::nonOrthogonality(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), chemistryModel< CompType, ThermoType >::omega(), Foam::operator*(), specie::operator*=(), VectorSpace< Form, Cmpt, nCmpt >::operator*=(), complex::operator*=(), septernion::operator*=(), constTransport< Thermo >::operator*=(), polynomialTransport< Thermo, PolySize >::operator*=(), polynomialSolidTransport< Thermo, PolySize >::operator*=(), polynomialFunction::operator*=(), hPolynomialThermo< EquationOfState, PolySize >::operator*=(), sutherlandTransport< Thermo >::operator*=(), quaternion::operator*=(), dimensioned< Type >::operator*=(), fvsPatchField< Type >::operator*=(), fvPatchField< Type >::operator*=(), LduMatrix< Type, DType, LUType >::operator*=(), lduMatrix::operator*=(), complex::operator+=(), complex::operator-=(), Foam::operator/(), VectorSpace< Form, Cmpt, nCmpt >::operator/=(), complex::operator/=(), septernion::operator/=(), polynomialFunction::operator/=(), quaternion::operator/=(), dimensioned< Type >::operator/=(), fvsPatchField< Type >::operator/=(), fvPatchField< Type >::operator/=(), Foam::operator<<(), complex::operator=(), quaternion::operator=(), token::operator=(), pointData::operator==(), Foam::operator>>(), VectorSpaceOps< N, I >::opSV(), VectorSpaceOps< N, I >::opVS(), Pair< word >::Pair(), molecule::constantProperties::pairPotentialSite(), quaternion::quaternion(), triangle< Point, PointRef >::randomPoint(), tetrahedron< Point, PointRef >::randomPoint(), PtrList< T >::read(), dimensionSet::read(), IOPosition< CloudType >::readData(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), cyclicAMIPolyPatch::reverseTransformPosition(), Foam::rotationTensor(), hConstThermo< EquationOfState >::s(), hRefConstThermo< EquationOfState >::s(), eConstThermo< EquationOfState >::s(), hPolynomialThermo< EquationOfState, PolySize >::s(), hPowerThermo< EquationOfState >::s(), janafThermo< EquationOfState >::s(), thermo< Thermo, Type >::S(), s_len_trim(), multiNormal::sample(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), VectorSpaceOps< N, I >::SeqOp(), Foam::setComponent(), SprayParcel< ParcelType >::solveTABEq(), Foam::sqr(), SVD::SVD(), swapec(), chemistryModel< CompType, ThermoType >::tc(), timestring(), wallBoundedParticle::trackFaceTri(), Foam::transform(), sixDoFRigidBodyMotion::transform(), cyclicAMIPolyPatch::transformPosition(), cyclicPolyPatch::transformPosition(), triangulation_print(), Foam::stringOps::trimLeft(), Foam::stringOps::trimRight(), turbGen::U(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValueFvPatchField< Type >::updateCoeffs(), EulerImplicit< ChemistryModel >::updateRRInReactionI(), meshRefinement::write(), and searchableSurfaces::writeStats().
if (s. size())
Definition at line 37 of file gmvOutputSpray.H.
References forAll, n, Foam::nl, and s().