OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
if (mesh.nCells()!=1)
Info<< "Reading initial conditions.\n"<< endl;IOdictionary initialConditions(IOobject("initialConditions", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));scalar p0=readScalar(initialConditions.lookup("p"));scalar T0=readScalar(initialConditions.lookup("T"));#24"/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/combustion/chemFoam/createFields.H"2 Info<< nl<< "Reading thermophysicalProperties"<< endl;autoPtr< psiChemistryModel > pChemistry (psiChemistryModel::New(mesh))
thermo validate (args.executable(),"h")
volScalarField rho (IOobject("rho", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("zero", dimensionSet(dimEnergy/dimMass/dimTemperature), 0.0))
volVectorField U (IOobject("U", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("zero", dimVelocity, vector::zero), p.boundaryField().types())
Info<< "Creating turbulence model.\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
OFstream post (args.path()/"chemFoam.out")
Variables
psiChemistryModel & chemistry = pChemistry()
scalar dtChem = refCast<const psiChemistryModel>(chemistry).deltaTChem()[0]
psiReactionThermo & thermo = chemistry.thermo()
basicMultiComponentMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
Function Documentation
if (mesh.nCells()! = 1)
Definition at line 1 of file createFields.H.
References args, argList::executable(), Foam::exit(), Foam::FatalError, and FatalErrorIn.
Info<< "Reading initial conditions.\n" << endl; IOdictionary initialConditions (IOobject ("initialConditions", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); scalar p0 = readScalar(initialConditions.lookup("p")); scalar T0 = readScalar(initialConditions.lookup("T"));# 24 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/combustion/chemFoam/createFields.H" 2 Info<< nl << "Reading thermophysicalProperties" << endl; autoPtr<psiChemistryModel> pChemistry (psiChemistryModel:: Newmesh)
thermo validate (args. executable(), "h")
volScalarField rho (IOobject("rho", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("zero", dimensionSet(dimEnergy/dimMass/dimTemperature), 0.0))
volVectorField U (IOobject("U", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("zero", dimVelocity, vector::zero) , p. boundaryField).types()
Referenced by if().
Info<< "Creating turbulence model.\n" << endl; autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel:: New rho, U, phi, thermo)
OFstream post (args.path()/"chemFoam.out")
Variable Documentation
psiChemistryModel& chemistry = pChemistry()
Definition at line 29 of file createFields.H.
scalar dtChem = refCast<const psiChemistryModel>(chemistry).deltaTChem()[0]
Definition at line 30 of file createFields.H.
Referenced by if().
psiReactionThermo& thermo = chemistry.thermo()
Definition at line 32 of file createFields.H.
Referenced by LiquidEvaporationBoil< CloudType >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), for(), forAll(), forAllConstIter(), if(), laminar< Type >::R(), ReactingCloud< CloudType >::ReactingCloud(), ReactingCloud< CloudType >::setParcelThermoProperties(), singleStepCombustion< CombThermoType, ThermoType >::singleStepCombustion(), chemistryModel< CompType, ThermoType >::solve(), chemistryModel< CompType, ThermoType >::tc(), and while().
basicMultiComponentMixture& composition = thermo.composition()
Definition at line 35 of file createFields.H.
Referenced by ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), ReactingMultiphaseCloud< CloudType >::checkParcelProperties(), ReactingCloud< CloudType >::checkParcelProperties(), SprayParcel< ParcelType >::chi(), if(), ReactingCloud< CloudType >::ReactingCloud(), ReactingMultiphaseCloud< CloudType >::ReactingMultiphaseCloud(), SprayCloud< CloudType >::setParcelThermoProperties(), ReactingMultiphaseCloud< CloudType >::setParcelThermoProperties(), ReactingCloud< CloudType >::setParcelThermoProperties(), SprayCloud< CloudType >::SprayCloud(), ReactingMultiphaseCloud< CloudType >::writeFields(), and ReactingCloud< CloudType >::writeFields().
PtrList<volScalarField>& Y = composition.Y()
Definition at line 36 of file createFields.H.
Referenced by SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), LiquidEvaporationBoil< CloudType >::calculate(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), forAll(), singleStepReactingMixture< ThermoType >::fresCorrect(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), if(), ReactingParcel< ParcelType >::readFields(), coordSet::scalarCoord(), SprayCloud< CloudType >::setParcelThermoProperties(), basicSymmetryFvPatchField< Type >::snGradTransformDiag(), symmetryPlaneFvPatchField< Type >::snGradTransformDiag(), fixedNormalSlipFvPatchField< Type >::snGradTransformDiag(), partialSlipFvPatchField< Type >::snGradTransformDiag(), directionMixedFvPatchField< Type >::snGradTransformDiag(), Vector< Cmpt >::Vector(), Vector2D< Cmpt >::Vector2D(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), ReactingParcel< ParcelType >::writeFields(), Vector2D< Cmpt >::y(), Vector< Cmpt >::y(), and liquidMixtureProperties::Y().
volScalarField& p = thermo.p()
Definition at line 51 of file createFields.H.
Referenced by greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), autoLayerDriver::addLayers(), KinematicCloud< CloudType >::alpha(), attachPolyTopoChanger::attach(), FreeStream< CloudType >::autoMap(), Cloud< ParticleType >::autoMap(), SprayParcel< ParcelType >::calcBreakup(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< FitDataType, ExtendedStencil, Polynomial >::calcFit(), forces::calcForcesMoment(), Stochastic< CloudType >::calculate(), KinematicParcel< ParcelType >::calcVelocity(), polyMeshTetDecomposition::checkFaceTets(), SuppressionCollision< CloudType >::collide(), ORourkeCollision< CloudType >::collide(), molecule::constantProperties::constantProperties(), face::contactSphereDiameter(), cyclicACMIGAMGInterfaceField::cyclicACMIGAMGInterfaceField(), cyclicAMIGAMGInterfaceField::cyclicAMIGAMGInterfaceField(), cyclicGAMGInterfaceField::cyclicGAMGInterfaceField(), fvFieldDecomposer::decomposeField(), IOstream::defaultPrecision(), Cloud< ParticleType >::deleteParticle(), LiquidEvaporationBoil< CloudType >::dh(), KinematicCloud< CloudType >::Dij(), KinematicCloud< CloudType >::Dmax(), Foam::domainName(), pitchForkRing::energy(), atmBoundaryLayer::epsilon(), mappedPatchBase::facePoint(), for(), forAll(), pitchForkRing::force(), FreeStream< CloudType >::FreeStream(), PatchTools::gatherAndMerge(), get_geom_list(), KinematicParcel< ParcelType >::hitFace(), KinematicParcel< ParcelType >::hitPatch(), particle< Type >::hitWallFaces(), if(), FreeStream< CloudType >::inflow(), DSMCCloud< ParcelType >::internalEnergyOfSystem(), regionModel::interRegionAMI(), cell::labels(), DSMCCloud< ParcelType >::linearKineticEnergyOfSystem(), KinematicCloud< CloudType >::linearKineticEnergyOfSystem(), DSMCCloud< ParcelType >::linearMomentumOfSystem(), KinematicCloud< CloudType >::linearMomentumOfSystem(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), DSMCCloud< ParcelType >::massInSystem(), KinematicCloud< CloudType >::massInSystem(), MeshedSurface< Face >::MeshedSurface(), layeredEngineMesh::move(), DSMCParcel< ParcelType >::move(), Cloud< ParticleType >::move(), MPPICParcel< ParcelType >::move(), CollidingParcel< ParcelType >::move(), KinematicParcel< ParcelType >::move(), regionModel::nbrCoupledPatchID(), tetrahedron< Point, PointRef >::nearestPoint(), pointPatchField< Type >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), fvsPatchField< Type >::NewCalculatedType(), fvPatchField< Type >::NewCalculatedType(), surfacePatch::operator!=(), geometricSurfacePatch::operator!=(), sigmaRadial::operator()(), Hash< Foam::string >::operator()(), Hash< Foam::word >::operator()(), Hash< Foam::fileName >::operator()(), Hash< Foam::wordRe >::operator()(), Hash< Foam::keyType >::operator()(), Foam::operator*(), Foam::operator/(), token::operator=(), dynamicTreeDataPoint::overlaps(), wallBoundedParticle::patchInteraction(), KinematicCloud< CloudType >::penetration(), cell::points(), cellShape::points(), triFace::points(), face::points(), PatchPostProcessing< CloudType >::postPatch(), processorGAMGInterfaceField::processorGAMGInterfaceField(), triangle< Point, PointRef >::ray(), solidParticle::readFields(), MPPICParcel< ParcelType >::readFields(), CollidingParcel< ParcelType >::readFields(), DSMCParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readFields(), particle< Type >::readFields(), KinematicParcel< ParcelType >::readFields(), UILList< DLListBase, Foam::molecule >::remove(), SLListBase::remove(), autoPtr< T >::reset(), linear< Type >::rho(), KinematicCloud< CloudType >::rhoEff(), CollidingCloud< CloudType >::rotationalKineticEnergyOfSystem(), general::sample(), multiNormal::sample(), coordSet::scalarCoord(), autoPtr< T >::set(), PointIndexHit< Point >::setPoint(), PointHit< point >::setPoint(), liquidMixtureProperties::sigma(), ode< ChemistryModel >::solve(), KinematicCloud< CloudType >::theta(), ThermoCloud< CloudType >::Tmax(), ThermoCloud< CloudType >::Tmin(), dictionary::topDict(), CV2D::toPoint2D(), particle< Type >::trackToFace(), SHF< CloudType >::update(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), KinematicCloud< CloudType >::vDotSweep(), coordSet::vectorCoord(), while(), OBJedgeFormat::write(), OBJstream::write(), dsmcFields::write(), meshToMeshMethod::writeConnectivity(), solidParticle::writeFields(), MPPICParcel< ParcelType >::writeFields(), CollidingParcel< ParcelType >::writeFields(), DSMCParcel< ParcelType >::writeFields(), ReactingParcel< ParcelType >::writeFields(), ThermoParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::writeFields(), KinematicParcel< ParcelType >::writeFields(), Cloud< ParticleType >::writePositions(), and liquidMixtureProperties::Xs().