OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
vtkOpenFOAMPoints.H File Reference
Functions
void vtkInsertNextOpenFOAMPoint (vtkPoints *points, const Foam::point &p)
Detailed Description
Original source file vtkOpenFOAMPoints.H
InClass vtkPV3Foam
Definition in file vtkOpenFOAMPoints.H.
Function Documentation
void vtkInsertNextOpenFOAMPoint (vtkPoints * points, const Foam::point & p) inline
Definition at line 38 of file vtkOpenFOAMPoints.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().