OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createDynamicFvMesh.H File Reference
Functions
Info<< "Create mesh for time = "
<< runTime.timeName()<< nl
<< endl;autoPtr< dynamicFvMesh > meshPtr (dynamicFvMesh::New(IOobject(dynamicFvMesh::defaultRegion, runTime.timeName(), runTime, IOobject::MUST_READ)))
Variables
dynamicFvMesh & mesh = meshPtr()
Function Documentation
Info<< "Create mesh for time = " << runTime.timeName() << nl << endl; autoPtr<dynamicFvMesh> meshPtr (dynamicFvMesh:: NewIOobject(dynamicFvMesh::defaultRegion, runTime.timeName(), runTime, IOobject::MUST_READ))
Variable Documentation
dynamicFvMesh& mesh = meshPtr()
Definition at line 18 of file createDynamicFvMesh.H.
Referenced by greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), isoSurface::adaptPatchFields(), autoLayerDriver::addLayers(), fvMeshTools::addPatch(), boundaryMesh::addPatch(), meshRefinement::addPatch(), cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), ThermoCloud< CloudType >::ap(), meshRefinement::appendPatch(), fieldToCell::applyToSet(), FreeStream< CloudType >::autoMap(), activePressureForceBaffleVelocityFvPatchVectorField::autoMap(), Foam::fvc::average(), functionObjectFile::baseFileDir(), basicMultiComponentMixture::basicMultiComponentMixture(), SRFForce< CloudType >::cacheFields(), Relaxation< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), ParamagneticForce< CloudType >::cacheFields(), Explicit< CloudType >::cacheFields(), LiftForce< CloudType >::cacheFields(), NonInertialFrameForce< CloudType >::cacheFields(), interpolate::calc(), mag::calc(), magSqr::calc(), components::calc(), magGrad::calc(), div::calc(), randomise::calc(), addSubtract::calc(), nearWallFields::calcAddressing(), curvatureSeparation::calcCosAngle(), faceZone::calcFaceZonePatch(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< FitDataType, ExtendedStencil, Polynomial >::calcFit(), forces::calcForcesMoment(), processorPolyPatch::calcGeometry(), cellLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), curvatureSeparation::calcInvR1(), fieldMinMax::calcMinMaxFields(), sampledSet::calcSign(), Stochastic< CloudType >::calculate(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), KinematicParcel< ParcelType >::calcVelocity(), Foam::fvc::cellReduce(), boundaryMesh::changeFaces(), layerAdditionRemoval::changeTopology(), attachDetach::changeTopology(), slidingInterface::changeTopology(), polyBoundaryMesh::checkDefinition(), faceZone::checkDefinition(), pointZone::checkParallelSync(), faceZone::checkParallelSync(), chemistryModel< CompType, ThermoType >::chemistryModel(), SprayParcel< ParcelType >::clone(), ReactingParcel< ParcelType >::clone(), componentDisplacementMotionSolver::componentDisplacementMotionSolver(), pointConstraints::constrain(), pointConstraints::constrainDisplacement(), GAMGAgglomeration::continueAgglomerating(), Foam::MULES::correct(), inverseVolumeDiffusivity::correct(), directionalDiffusivity::correct(), motionDirectionalDiffusivity::correct(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), inverseDistanceDiffusivity::correct(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), laminar< Type >::correct(), pointPatchDist::correct(), patchWave::correct(), wallDistData< TransferType >::correct(), curvatureSeparation::correct(), patchDataWave< TransferType >::correct(), cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), pointLinear< Type >::correction(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), Foam::CorrectPhi(), Foam::correctUphiBCs(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), CourantNo::CourantNo(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::CpByCpv(), heThermo< BasicThermo, MixtureType >::Cpv(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), displacementMeshMoverMotionSolver::curPoints(), displacementInterpolationMotionSolver::curPoints(), hexCellLooper::cut(), geomCellLooper::cut(), topoCellLooper::cut(), heThermo< BasicThermo, MixtureType >::Cv(), CrankNicolsonDdtScheme< Type >::ddt0_(), manualDecomp::decompose(), DESModelRegions::DESModelRegions(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), noCombustion< CombThermoType >::dQ(), singleStepCombustion< CombThermoType, ThermoType >::dQ(), laminar< Type >::dQ(), wideBandAbsorptionEmission::ECont(), ThermoCloud< CloudType >::Ep(), Lambda2::execute(), Peclet::execute(), Q::execute(), DESModelRegions::execute(), Foam::MULES::explicitLTSSolve(), Foam::MULES::explicitSolve(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), polyPatch::faceAreas(), polyPatch::faceCells(), polyPatch::faceCentres(), mappedPatchBase::facePoints(), blendingFactor::factor(), FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs(), pointBoundaryMesh::findIndices(), fvBoundaryMesh::findIndices(), sampledSet::findNearFace(), mappedPatchBase::findSamples(), polyMesh::findTetFacePt(), cellCuts::flip(), PatchFlowRateInjection< CloudType >::flowRate(), multivariateGaussConvectionScheme< Type >::flux(), for(), forAll(), correctedSnGrad< Type >::fullGradCorrection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), steadyStateD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), ddtScheme< Type >::fvcDdtPhiCoeff(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), multivariateGaussConvectionScheme< Type >::fvcDiv(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), multivariateGaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), heThermo< BasicThermo, MixtureType >::gamma(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), get_edge_list(), get_geom_list(), get_mesh_dim(), get_num_edges_list(), get_number_of_vertices(), get_vertex_list(), sampledSet::getCell(), cellLooper::getFirstVertEdge(), cellLooper::getMisAlignedEdge(), boundaryMesh::getNearest(), boundaryMesh::getNPoints(), boundaryMesh::getNTris(), cellDistFuncs::getPatchIDs(), undoableMeshCutter::getSplitFaces(), sampledSet::getTrackingPoint(), cellLooper::getVertEdgesNonFace(), cellLooper::getVertFacesNonEdge(), calcFvcGrad::gradField(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), heThermo< BasicThermo, MixtureType >::hc(), heThermo< BasicThermo, MixtureType >::he(), if(), Foam::MULES::implicitSolve(), InflationInjection< CloudType >::InflationInjection(), FreeStream< CloudType >::inflow(), MPPICCloud< CloudType >::info(), cellSource::initialise(), faceSource::initialise(), processorPolyPatch::initOrder(), SurfaceFilmModel< CloudType >::inject(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), multivariateGaussConvectionScheme< Type >::interpolate(), volPointInterpolation::interpolateBoundaryField(), distanceSurface::interpolateField(), sampledPatchInternalField::interpolateField(), sampledPatch::interpolateField(), sampledTriSurfaceMesh::interpolateField(), Foam::interpolatePointToCell(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), temperatureCoupledBase::kappa(), Lambda2::Lambda2(), lduPrimitiveMesh::lduPrimitiveMesh(), Foam::MULES::limit(), Foam::MULES::limitCorr(), PhiScheme< Type, PhiLimiter >::limiter(), Foam::MULES::limiter(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), Foam::MULES::limiterCorr(), readFields::loadField(), basicThermo::lookupOrConstruct(), Foam::MULES::LTScorrect(), main(), meshRefinement::makeDisplacementField(), boundaryMesh::markFaces(), KinematicParcel< ParcelType >::massCell(), LocalInteraction< CloudType >::massEscape(), LocalInteraction< CloudType >::massStick(), cellDistFuncs::maxPatchSize(), meshReader::mesh(), faceZone::meshEdges(), polyPatch::meshEdges(), MeshedSurface< Face >::MeshedSurface(), displacementMeshMoverMotionSolver::meshMover(), steadyStateDdtScheme< Type >::meshPhi(), EulerDdtScheme< Type >::meshPhi(), backwardDdtScheme< Type >::meshPhi(), localEulerDdtScheme< Type >::meshPhi(), CoEulerDdtScheme< Type >::meshPhi(), SLTSDdtScheme< Type >::meshPhi(), CrankNicolsonDdtScheme< Type >::meshPhi(), DSMCParcel< ParcelType >::move(), medialAxisMeshMover::move(), KinematicParcel< ParcelType >::move(), pointBoundaryMesh::movePoints(), polyBoundaryMesh::movePoints(), regionCoupledBaseGAMGInterface::nbrLduInterface(), sampledThresholdCellFaces::needsUpdate(), sampledIsoSurfaceCell::needsUpdate(), sampledIsoSurface::needsUpdate(), regionCoupledBase::neighbPatch(), regionCoupledBase::neighbPatchID(), basicChemistryModel::New(), motionDiffusivity::New(), psiReactionThermo::New(), rhoReactionThermo::New(), scatterModel::New(), fluidThermo::New(), psiuReactionThermo::New(), psiCombustionModel::New(), absorptionEmissionModel::New(), rhoCombustionModel::New(), psiThermo::New(), motionSolver::New(), sootModel::New(), rhoChemistryModel::New(), LESfilter::New(), psiChemistryModel::New(), basicSolidChemistryModel::New(), solidReactionThermo::New(), snGradScheme< Type >::New(), gradScheme< Type >::New(), rhoThermo::New(), patchDistMethod::New(), solidThermo::New(), AveragingMethod< Type >::New(), surfaceInterpolationScheme< Type >::New(), d2dt2Scheme< Type >::New(), ddtScheme< Type >::New(), ParticleForce< CloudType >::New(), divScheme< Type >::New(), surfaceFilmModel::New(), convectionScheme< Type >::New(), reactionRateFlameArea::New(), multivariateSurfaceInterpolationScheme< Type >::New(), limitedSurfaceInterpolationScheme< Type >::New(), basicThermo::New(), laplacianScheme< Type, GType >::New(), cellLooper::New(), thermalBaffleModel::New(), pyrolysisModel::New(), porosityModel::New(), sampledSurface::New(), topoSet::New(), sampledSet::New(), option::New(), topoSetSource::New(), GAMGAgglomeration::New(), simpleFilter::operator()(), anisotropicFilter::operator()(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), cyclicPolyPatch::order(), InflationInjection< CloudType >::parcelsToInject(), sampledPatch::patchIDs(), Peclet::Peclet(), sampledSurface::pointAverage(), VoidFraction< CloudType >::postEvolve(), VoidFraction< CloudType >::preEvolve(), ParticleTrap< CloudType >::preEvolve(), ParticleErosion< CloudType >::preEvolve(), pressureTools::pressureTools(), processorField::processorField(), sampledSet::pushIn(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), pyrolysisModelCollection::pyrolysisModelCollection(), Q::Q(), ReactingCloud< CloudType >::ReactingCloud(), nearWallFields::read(), forces::read(), IOPosition< ParticleType >::readData(), Foam::fvc::reconstruct(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), Foam::fvc::reconstructMag(), GeometricField< Type, PatchField, GeoMesh >::relax(), undoableMeshCutter::removeSplitFaces(), manualRenumber::renumber(), zoltanRenumber::renumber(), fvMeshTools::reorderPatches(), cyclicAMIPolyPatch::resetAMI(), forces::rho(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::RRg(), solidChemistryModel< CompType, SolidThermo >::RRs(), sampledTriSurfaceMesh::sampleField(), mappedPatchBase::sampleSize(), boundaryMesh::setExtraEdges(), boundaryMesh::setFeatureEdges(), ThermoCloud< CloudType >::setModels(), PatchInjection< CloudType >::setPositionAndCell(), PatchFlowRateInjection< CloudType >::setPositionAndCell(), refinementIterator::setRefinement(), perfectInterface::setRefinement(), layerAdditionRemoval::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), fixedTemperatureConstraint::setValue(), fvMatrix< Type >::setValuesFromList(), noCombustion< CombThermoType >::Sh(), laminar< Type >::Sh(), ThermoCloud< CloudType >::Sh(), ThermoCloud< CloudType >::sigmap(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), Foam::fvc::smooth(), solidChemistryModel< CompType, SolidThermo >::solidChemistryModel(), PCG::solve(), PBiCG::solve(), smoothSolver::solve(), displacementMeshMoverMotionSolver::solve(), sixDoFRigidBodyMotionSolver::solve(), displacementLayeredMotionMotionSolver::solve(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), GAMGSolver::solve(), fvMatrix< Type >::solve(), chemistryModel< CompType, ThermoType >::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solver(), fvMatrix< Type >::solveSegregated(), ThermoSurfaceFilm< CloudType >::splashInteraction(), Foam::fvc::spread(), ReactingCloud< CloudType >::Srho(), cellDistFuncs::sumPatchSize(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), regionCoupledBase::surfPtr(), cyclicAMIPolyPatch::surfPtr(), mappedPatchBase::surfPtr(), Foam::fvc::sweep(), ReactingCloud< CloudType >::SYi(), GeometricField< Type, PatchField, GeoMesh >::T(), chemistryModel< CompType, ThermoType >::tc(), polyTopoChanger::topoChangeRequest(), boundaryMesh::triangulate(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), boundaryMesh::triangulateLocal(), Foam::tryCalc(), GradientDispersionRAS< CloudType >::update(), sampledPlane::update(), sampledPatch::update(), sampledTriSurfaceMesh::update(), cellMotionFvPatchField< Type >::updateCoeffs(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingDisplacementPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), movingWallVelocityFvPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), pointBoundaryMesh::updateMesh(), PatchInjection< CloudType >::updateMesh(), PatchFlowRateInjection< CloudType >::updateMesh(), componentDisplacementMotionSolver::updateMesh(), displacementMotionSolver::updateMesh(), perfectInterface::updateMesh(), layerAdditionRemoval::updateMesh(), polyBoundaryMesh::updateMesh(), USERD_get_var_by_component(), USERD_get_var_value_at_specific(), Implicit< CloudType >::velocityCorrection(), Explicit< CloudType >::velocityCorrection(), vorticity::vorticity(), basicSpecieMixture::W(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), wallShearStress::wallShearStress(), extendedUpwindCellToFaceStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), limitedSurfaceInterpolationScheme< Type >::weights(), polyBoundaryMesh::whichPatch(), PatchPostProcessing< CloudType >::write(), FacePostProcessing< CloudType >::write(), dsmcFields::write(), edgeMesh::write(), ParticleCollector< CloudType >::write(), regionSizeDistribution::write(), cellSource::write(), faceSource::write(), addSubtract::writeAddSubtractField(), addSubtract::writeAddSubtractValue(), components::writeComponentFields(), edgeVertex::writeCut(), div::writeDivField(), interpolate::writeInterpolateField(), mag::writeMagField(), magGrad::writeMagGradField(), magSqr::writeMagSqrField(), sixDoFRigidBodyMotionSolver::writeObject(), randomise::writeRandomField(), boundaryMesh::writeTriSurface(), cellSource::writeValues(), faceSource::writeValues(), yPlusLES::yPlusLES(), yPlusRAS::yPlusRAS(), and fvMeshTools::zeroPatchFields().