OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
ensightCaseTail.H File Reference
Functions
if (Pstream::master())
Function Documentation
if (Pstream::master())
Definition at line 1 of file ensightCaseTail.H.
References Foam::endl(), forAll, Foam::Info, n, Foam::nl, Foam::scientific(), and Foam::setw().