OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToEnsightParts/findFields.H File Reference
findFields.H File Reference
Functions
if (timeDirs.size())
Variables
HashTable< word > volumeFields
HashTable< HashTable< word > > cloudFields
Function Documentation
if (timeDirs. size())
Definition at line 9 of file findFields.H.
References cloudFields, cloudName(), Foam::endl(), forAll, forAllConstIter(), forAllIter, Foam::Info, mesh, Foam::name(), Foam::readDir(), timeDirs, and volumeFields.
Variable Documentation
HashTable<word> volumeFields
Definition at line 4 of file findFields.H.
Referenced by if().
HashTable<HashTable<word> > cloudFields
Definition at line 7 of file findFields.H.
Referenced by if().