OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/gmvOutputLagrangian.H File Reference
gmvOutputLagrangian.H File Reference
Functions
gmvFile<< "tracers "<< particles.size()<< nl;forAllConstIter(Cloud< passiveParticle >, particles, iter){gmvFile<< iter().position().x()<< ' ';}gmvFile<< nl;forAllConstIter(Cloud< passiveParticle >, particles, iter){gmvFile<< iter().position().y()<< ' ';}gmvFile<< nl;forAllConstIter(Cloud< passiveParticle >, particles, iter){gmvFile<< iter().position().z()<< ' ';}gmvFile<< nl;forAll(lagrangianScalarNames, i){const word &name=lagrangianScalarNames[i];IOField< scalar > fld (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
if (fld.size())
forAll (lagrangianVectorNames, i)
Function Documentation
gmvFile<< "tracers " << particles.size() << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().x() << ' ';}gmvFile << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().y() << ' ';}gmvFile << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().z() << ' ';}gmvFile << nl;forAll(lagrangianScalarNames, i){ const word& name = lagrangianScalarNames[i]; IOField<scalar> fld (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
Referenced by cyclicAMIPolyPatch::clone(), meshRefinement::collectAndPrint(), mapDistributeBase::constructHasFlip(), polyMeshFilter::copyMesh(), nearWallFields::createFields(), mapDistributeBase::distribute(), mapDistribute::distribute(), for(), forAll(), globalIndex::gather(), triSurfaceMesh::getField(), distributedTriSurfaceMesh::getField(), surfaceFieldValue::getFieldValues(), coalCloudList::hsTrans(), if(), Function1< Type >::integrate(), pointToPointPlanarInterpolation::interpolate(), vtkMesh::interpolate(), surfaceInterpolate::interpolateFields(), fvMeshAdder::MapDimFields(), fvMeshAdder::MapSurfaceFields(), fvMeshAdder::MapVolFields(), cyclicFvPatchField< Type >::neighbourPatchField(), cyclicAMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::neighbourPatchField(), extendedUpwindCellToFaceStencil::neiStencil(), cyclicACMIFvPatchField< Type >::nonOverlapPatchField(), ListPlusEqOp< T, Size >::operator()(), mapDistribute::transform::operator()(), mapDistribute::transformPosition::operator()(), transformOp< PrimitivePatchType, Type, TrackingData >::operator()(), fvMeshDistribute::printFieldInfo(), turbulenceFields::processField(), mappedPatchBase::readListOrField(), coalCloudList::rhoTrans(), regionCoupledBase::sameRegion(), cuttingPlane::sample(), nearWallFields::sampleFields(), mappedPatchBase::samplePoints(), globalIndex::scatter(), coalCloudList::Srho(), solutionControl::storePrevIter(), cyclicPointPatchField< Type >::swapAddSeparated(), cyclicACMIPointPatchField< Type >::swapAddSeparated(), cyclicAMIPointPatchField< Type >::swapAddSeparated(), vectorTensorTransform::transform(), mapDistribute::transformStart(), STARCDCoordinateRotation::transformVector(), EulerCoordinateRotation::transformVector(), axesRotation::transformVector(), cylindrical::transformVector(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValueFvPatchField< Type >::updateCoeffs(), mapDistribute::updateMesh(), meshRefinement::userFaceData(), coalCloudList::UTrans(), Function1< Type >::value(), ensightSetWriter< Type >::write(), vtkSetWriter< Type >::write(), regionSizeDistribution::write(), TableBase< Type >::x(), and TableBase< Type >::y().
if (fld. size())
Definition at line 37 of file gmvOutputLagrangian.H.
References fld(), forAll(), n, and Foam::nl.
forAll (lagrangianVectorNames , i)
Definition at line 51 of file gmvOutputLagrangian.H.
References fld(), lagrangianVectorNames, mesh, n, and Foam::nl.
Referenced by if().