OpenFOAM: applications/utilities/postProcessing/graphics/ensightFoamReader/getFieldVector.H File Reference
getFieldVector.H File Reference
Functions
if (nVar >=Num_variables-nSprayVariables)
IOobject fieldObjectPtr (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::NO_READ)
if (!fieldObjectPtr.headerOk())
IOobject fieldObject (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE)
volVectorField vectorField (fieldObject, mesh)
if (which_type==Z_HEX08)
Variables
const cellShapeList & cellShapes = meshPtr->cellShapes()
Function Documentation
if (nVar >=Num_variables- nSprayVariables)
Definition at line 1 of file getFieldVector.H.
References fieldNames, fieldObjectPtr(), mesh, nVar, and var2field.
IOobject fieldObjectPtr (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::NO_READ)
Referenced by if().
if (!fieldObjectPtr. headerOk())
Definition at line 15 of file getFieldVector.H.
References fieldNames, fieldObject(), mesh, var2field, and vectorField().
IOobject fieldObject (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::NO_WRITE)
Referenced by if().
volVectorField vectorField (fieldObject , mesh)
Referenced by filmHeightInletVelocityFvPatchVectorField::filmHeightInletVelocityFvPatchVectorField(), filmPyrolysisVelocityCoupledFvPatchVectorField::filmPyrolysisVelocityCoupledFvPatchVectorField(), fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField(), flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField(), forAll(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), if(), inclinedFilmNusseltInletVelocityFvPatchVectorField::inclinedFilmNusseltInletVelocityFvPatchVectorField(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), makeFvGradScheme(), movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField(), outletPhaseMeanVelocityFvPatchVectorField::outletPhaseMeanVelocityFvPatchVectorField(), ParticleCollector< CloudType >::ParticleCollector(), pressureDirectedInletOutletVelocityFvPatchVectorField::pressureDirectedInletOutletVelocityFvPatchVectorField(), pressureDirectedInletVelocityFvPatchVectorField::pressureDirectedInletVelocityFvPatchVectorField(), pressureInletOutletParSlipVelocityFvPatchVectorField::pressureInletOutletParSlipVelocityFvPatchVectorField(), pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), pressureInletVelocityFvPatchVectorField::pressureInletVelocityFvPatchVectorField(), pressureNormalInletOutletVelocityFvPatchVectorField::pressureNormalInletOutletVelocityFvPatchVectorField(), rotatingWallVelocityFvPatchVectorField::rotatingWallVelocityFvPatchVectorField(), extendedEdgeMesh::sortPointsAndEdges(), SRFFreestreamVelocityFvPatchVectorField::SRFFreestreamVelocityFvPatchVectorField(), SRFVelocityFvPatchVectorField::SRFVelocityFvPatchVectorField(), SRFWallVelocityFvPatchVectorField::SRFWallVelocityFvPatchVectorField(), supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField(), surfaceNormalFixedValueFvPatchVectorField::surfaceNormalFixedValueFvPatchVectorField(), Foam::transform(), Foam::transformPoints(), USERD_get_part_coords(), USERD_get_part_node_ids(), and USERD_get_var_value_at_specific().
if (which_type = = Z_HEX08)
Definition at line 38 of file getFieldVector.H.
References cells, Foam::component(), Foam::hex(), lookup(), meshPtr, n, and points.
Variable Documentation
const cellShapeList& cellShapes = meshPtr->cellShapes()
Definition at line 35 of file getFieldVector.H.