OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< psiThermo > pThermo (psiThermo::New(mesh))
thermo validate (args.executable(),"e")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh), thermo.rho())
Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variables
psiThermo & thermo = pThermo()
volScalarField & p = thermo.p()
volScalarField & e = thermo.he()
Elementary charge.
const volScalarField & psi = thermo.psi()
Function Documentation
Info<< "Reading thermophysical properties\n" << endl;autoPtr<psiThermo> pThermo (psiThermo::New(mesh))
thermo validate (args. executable(), "e")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh) , thermo. rho())
Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variable Documentation
psiThermo& thermo = pThermo()
Definition at line 7 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 10 of file createFields.H.
volScalarField& e = thermo.he()
Elementary charge.
Definition at line 11 of file createFields.H.
Referenced by Foam::adjustPhi(), enrichedPatch::calcEnrichedFaces(), PatchTools::checkOrientation(), TrajectoryCollision< CloudType >::collideParcels(), edgeVertex::coord(), dtris2(), thermo< Thermo, Type >::E(), Foam::meshTools::findEdge(), indexedOctree< Type >::findLine(), dynamicIndexedOctree< Type >::findNearest(), treeDataPrimitivePatch< PatchType >::getVolumeType(), if(), interpolationCellPointFace< Type >::interpolate(), PatchTools::matchEdges(), treeDataPrimitivePatch< PatchType >::findSelfIntersectOp::operator()(), cell::opposingFace(), Foam::meshTools::otherEdge(), NASedgeFormat::read(), CodedSource< Type >::read(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), Foam::solve(), EulerImplicit< ChemistryModel >::solve(), SprayParcel< ParcelType >::solveTABEq(), PatchTools::sortedEdgeFaces(), swapec(), triangulation_plot_eps(), LISAAtomization< CloudType >::update(), vbedg(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), timeVaryingMappedFixedValueFvPatchField< Type >::write(), edgeVertex::writeCut(), and VTKedgeFormat::writeEdges().
const volScalarField& psi = thermo.psi()
Definition at line 12 of file createFields.H.