OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Creating combustion model\n"<< endl;autoPtr< combustionModels::psiCombustionModel > combustion (combustionModels::psiCombustionModel::New(mesh))
thermo validate (args.executable(),"h","e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.lookup("inertSpecie"))
if (!composition.contains(inertSpecie))
forAll (Y, i)
fields add (thermo.he())
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volScalarField rhoEffLagrangian (IOobject("rhoEffLagrangian", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("zero", dimDensity, 0.0))
volScalarField pDyn (IOobject("pDyn", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("zero", dimPressure, 0.0))
Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
Variables
psiReactionThermo & thermo = combustion->thermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
const volScalarField & T = thermo.T()
const volScalarField & psi = thermo.psi()
multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
Info<< "Creating combustion model\n" << endl;autoPtr<combustionModels::psiCombustionModel> combustion (combustionModels::psiCombustionModel::New(mesh))
thermo validate (args. executable(), "h" , "e")
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo. lookup"inertSpecie")
if (!composition. containsinertSpecie)
Definition at line 18 of file createFields.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and inertSpecie().
forAll (Y , i)
Definition at line 32 of file createFields.H.
References combustion(), Foam::dimDensity, Foam::dimEnergy, Foam::dimPressure, Foam::dimTime, dpdt, dQ(), Foam::endl(), Foam::Info, Foam::magSqr(), mesh, Foam::compressible::New(), pDyn(), phi, rho, rhoEffLagrangian(), turbulence, and U().
fields add (thermo. he())
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
volScalarField rhoEffLagrangian (IOobject("rhoEffLagrangian", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("zero", dimDensity, 0.0))
Referenced by forAll().
volScalarField pDyn (IOobject("pDyn", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("zero", dimPressure, 0.0))
Referenced by rotorDiskSource::calculate(), pressureTools::execute(), forAll(), and forceCoeffs::write().
Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
Variable Documentation
psiReactionThermo& thermo = combustion->thermo()
Definition at line 8 of file createFields.H.
basicSpecieMixture& composition = thermo.composition()
Definition at line 13 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 14 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 26 of file createFields.H.
const volScalarField& T = thermo.T()
Definition at line 27 of file createFields.H.
const volScalarField& psi = thermo.psi()
Definition at line 28 of file createFields.H.
multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 30 of file createFields.H.