OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Creating phaseSystem\n"<< endl;autoPtr< twoPhaseSystem > fluidPtr (twoPhaseSystem::New(mesh))
dimensionedScalar pMin ("pMin", dimPressure, fluid)
Variables
twoPhaseSystem & fluid = fluidPtr()
phaseModel & phase1 = fluid.phase1()
phaseModel & phase2 = fluid.phase2()
volScalarField & alpha1 = phase1
volScalarField & alpha2 = phase2
volVectorField & U1 = phase1.U()
surfaceScalarField & phi1 = phase1.phi()
surfaceScalarField & alphaPhi1 = phase1.alphaPhi()
surfaceScalarField & alphaRhoPhi1 = phase1.alphaRhoPhi()
volVectorField & U2 = phase2.U()
surfaceScalarField & phi2 = phase2.phi()
surfaceScalarField & alphaPhi2 = phase2.alphaPhi()
surfaceScalarField & alphaRhoPhi2 = phase2.alphaRhoPhi()
surfaceScalarField & phi = fluid.phi()
rhoThermo & thermo1 = phase1.thermo()
rhoThermo & thermo2 = phase2.thermo()
volScalarField & p = thermo1.p()
volScalarField & rho1 = thermo1.rho()
const volScalarField & psi1 = thermo1.psi()
volScalarField & rho2 = thermo2.rho()
const volScalarField & psi2 = thermo2.psi()
Function Documentation
Info<< "Creating phaseSystem\n" << endl;autoPtr<twoPhaseSystem> fluidPtr (twoPhaseSystem:: Newmesh)
dimensionedScalar pMin ("pMin" , dimPressure , fluid)
Variable Documentation
twoPhaseSystem& fluid = fluidPtr()
Definition at line 10 of file createFields.H.
phaseModel& phase1 = fluid.phase1()
Definition at line 12 of file createFields.H.
Referenced by for(), forAll(), if(), and while().
phaseModel& phase2 = fluid.phase2()
Definition at line 13 of file createFields.H.
Referenced by for(), forAll(), if(), and while().
volScalarField& alpha1 = phase1
Definition at line 15 of file createFields.H.
Referenced by for(), forAll(), if(), and while().
volScalarField& alpha2 = phase2
Definition at line 16 of file createFields.H.
volVectorField& U1 = phase1.U()
Definition at line 18 of file createFields.H.
Referenced by TrajectoryCollision< CloudType >::collideParcels(), ORourkeCollision< CloudType >::collideSorted(), for(), if(), and while().
surfaceScalarField& phi1 = phase1.phi()
Definition at line 19 of file createFields.H.
Referenced by while().
surfaceScalarField& alphaPhi1 = phase1.alphaPhi()
Definition at line 20 of file createFields.H.
Referenced by for(), and while().
surfaceScalarField& alphaRhoPhi1 = phase1.alphaRhoPhi()
Definition at line 21 of file createFields.H.
volVectorField& U2 = phase2.U()
Definition at line 23 of file createFields.H.
Referenced by TrajectoryCollision< CloudType >::collideParcels(), ORourkeCollision< CloudType >::collideSorted(), for(), if(), and while().
surfaceScalarField& phi2 = phase2.phi()
Definition at line 24 of file createFields.H.
Referenced by while().
surfaceScalarField& alphaPhi2 = phase2.alphaPhi()
Definition at line 25 of file createFields.H.
Referenced by for(), and while().
surfaceScalarField& alphaRhoPhi2 = phase2.alphaRhoPhi()
Definition at line 26 of file createFields.H.
surfaceScalarField& phi = fluid.phi()
Definition at line 28 of file createFields.H.
rhoThermo& thermo1 = phase1.thermo()
Definition at line 39 of file createFields.H.
rhoThermo& thermo2 = phase2.thermo()
Definition at line 40 of file createFields.H.
volScalarField& p = thermo1.p()
Definition at line 42 of file createFields.H.
volScalarField& rho1 = thermo1.rho()
Definition at line 44 of file createFields.H.
const volScalarField& psi1 = thermo1.psi()
Definition at line 45 of file createFields.H.
volScalarField& rho2 = thermo2.rho()
Definition at line 47 of file createFields.H.
const volScalarField& psi2 = thermo2.psi()
Definition at line 48 of file createFields.H.