OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Creating combustion model\n"<< endl;autoPtr< combustionModels::psiCombustionModel > combustion (combustionModels::psiCombustionModel::New(mesh))
thermo validate (args.executable(),"h","e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.lookup("inertSpecie"))
if (!composition.contains(inertSpecie))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), thermo.rho())
Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());dimensionedScalar rhoMax(dimensionedScalar::lookupOrDefault("rhoMax", pimple.dict(), dimDensity, GREAT));dimensionedScalar rhoMin(dimensionedScalar::lookupOrDefault("rhoMin", pimple.dict(), dimDensity, 0));Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
forAll (Y, i)
fields add (thermo.he())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variables
psiReactionThermo & thermo = combustion->thermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
const volScalarField & T = thermo.T()
const volScalarField & psi = thermo.psi()
Info<< "Creating field dpdt\n"<< endl;volScalarField dpdt(IOobject("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n"<< endl;volScalarField K("K", 0.5 *magSqr(U));multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
Info<< "Creating combustion model\n" << endl;autoPtr<combustionModels::psiCombustionModel> combustion (combustionModels::psiCombustionModel:: Newmesh)
thermo validate (args. executable(), "h" , "e")
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo. lookup"inertSpecie")
if (!composition. containsinertSpecie)
Definition at line 18 of file createFields.H.
References args, argList::executable(), Foam::exit(), Foam::FatalError, FatalErrorIn, and inertSpecie().
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE) , thermo. rho())
Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());dimensionedScalar rhoMax(dimensionedScalar::lookupOrDefault ("rhoMax", pimple.dict(), dimDensity, GREAT));dimensionedScalar rhoMin(dimensionedScalar::lookupOrDefault ("rhoMin", pimple.dict(), dimDensity, 0));Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel:: New rho, U, phi, thermo)
combustion setTurbulence (turbulence())
forAll (Y , i)
Definition at line 115 of file createFields.H.
fields add (thermo. he())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variable Documentation
psiReactionThermo& thermo = combustion->thermo()
Definition at line 8 of file createFields.H.
basicSpecieMixture& composition = thermo.composition()
Definition at line 13 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 14 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 26 of file createFields.H.
const volScalarField& T = thermo.T()
Definition at line 27 of file createFields.H.
const volScalarField& psi = thermo.psi()
Definition at line 28 of file createFields.H.
Info<< "Creating field dpdt\n" << endl;volScalarField dpdt(IOobject ("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n" << endl;volScalarField K("K", 0.5*magSqr(U));multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 113 of file createFields.H.