OpenFOAM-dev: applications/utilities/postProcessing/graphics/ensightFoamReader/getLagrangianVector.H File Reference 2
getLagrangianVector.H File Reference
Functions
if (nVar >=0)
Variables
nVar = Num_variables - nSprayVariables + lagrangianScalarNames.size()
else
Function Documentation
if (nVar >= 0)
Definition at line 6 of file getLagrangianVector.H.
References Foam::component(), forAll, lagrangianVectorNames, mesh, n, Foam::name(), and nVar.
Variable Documentation
nVar = Num_variables - nSprayVariables + lagrangianScalarNames.size()
Definition at line 4 of file getLagrangianVector.H.
Referenced by if().
else
Initial value:
{
    return Z_UNDEF
Definition at line 43 of file getLagrangianVector.H.