OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< psiThermo > pThermo (psiThermo::New(mesh))
thermo validate (args.executable(),"h","e")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variables
psiThermo & thermo = pThermo()
volScalarField & p = thermo.p()
const volScalarField & psi = thermo.psi()
const volScalarField & T = thermo.T()
Function Documentation
Info<< "Reading thermophysical properties\n" << endl; autoPtr<psiThermo> pThermo (psiThermo::New(mesh))
thermo validate (args. executable(), "h" , "e")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
Info<< "\nReading field U\n" << endl; volVectorField U (IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh); Info<< "Creating turbulence model\n" << endl; autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Variable Documentation
psiThermo& thermo = pThermo()
Definition at line 7 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 23 of file createFields.H.
const volScalarField& psi = thermo.psi()
Definition at line 24 of file createFields.H.
Referenced by Amultiplier< Type, LUType >::addAmul(), SemiImplicitSource< Type >::addSup(), LduMatrix< Type, DType, LUType >::Amul(), lduMatrix::Amul(), LduMatrix< Type, DType, LUType >::asymmetric(), lduMatrix::asymmetric(), rotorDiskSource::constructGeometry(), Foam::fvc::DDt(), Foam::MULES::explicitSolve(), for(), if(), lduMatrix::solver::interfaces(), lduMatrix::smoother::interfaces(), Foam::MULES::interpolate(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), LduMatrix< Type, DType, LUType >::solver::matrix(), LduMatrix< Type, DType, LUType >::smoother::matrix(), steadyStateDdtScheme< Type >::mesh(), EulerDdtScheme< Type >::mesh(), boundedDdtScheme< Type >::mesh(), backwardDdtScheme< Type >::mesh(), CoEulerDdtScheme< Type >::mesh(), SLTSDdtScheme< Type >::mesh(), localEulerDdtScheme< Type >::mesh(), interpolation< Type >::New(), CrankNicolsonDdtScheme< Type >::ocCoeff(), fixedTrim::read(), diagonalSolver::read(), fvMatrix< Type >::setValuesFromList(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solveSegregated(), targetCoeffTrim::thetag(), LduMatrix< Type, DType, LUType >::Tmul(), lduMatrix::Tmul(), EulerCoordinateRotation::transformVector(), while(), PBiCCCG< Type, DType, LUType >::~PBiCCCG(), PBiCG::~PBiCG(), PBiCICG< Type, DType, LUType >::~PBiCICG(), PCG::~PCG(), PCICG< Type, DType, LUType >::~PCICG(), and smoothSolver::~smoothSolver().
const volScalarField& T = thermo.T()
Definition at line 25 of file createFields.H.
Referenced by UList< T >::assign(), UList< T >::byteSize(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), FixedList< T, Size >::cdata(), SprayParcel< ParcelType >::chi(), MixedDiffuseSpecular< CloudType >::correct(), particle< Type >::correctAfterParallelTransfer(), Foam::createWithValues(), mapDistribute::distribute(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), Pstream::exchange(), FixedList< T, Size >::FixedList(), for(), forAll(), forAllIter(), meshRefinement::gAverage(), if(), Dual< Type >::interpolateGrad(), thermo< Thermo, Type >::K(), hPowerThermo< EquationOfState >::limit(), LList< LListBase, T >::LList(), dictionary::lookupOrDefault(), Moment< Type >::Moment(), sutherlandTransport< Thermo >::mu(), radiationModel::New(), Foam::NullObjectPtr(), Foam::NullObjectRef(), LandauTellerReactionRate::operator()(), JanevReactionRate::operator()(), StaticHashTable< T, Key, Hash >::operator()(), UList< T >::operator=(), FixedList< T, Size >::operator==(), UList< T >::operator==(), PtrList< T >::operator[](), StaticHashTable< T, Key, Hash >::operator[](), StaticHashTable< T, Key, Hash >::printInfo(), perfectFluid< Specie >::psi(), PengRobinsonGas< Specie >::psi(), PtrList< T >::read(), ThermoParcel< ParcelType >::readFields(), Foam::ReadHex(), perfectFluid< Specie >::rho(), incompressiblePerfectGas< Specie >::rho(), PengRobinsonGas< Specie >::rho(), UPtrList< T >::set(), ode< ChemistryModel >::solve(), FixedList< T, Size >::swap(), FieldField< Field, Type >::T(), Field< Type >::T(), thermo< Thermo, Type >::TEa(), thermo< Thermo, Type >::TEs(), meshRefinement::testSyncBoundaryFaceList(), thermo< Thermo, Type >::THa(), thermo< Thermo, Type >::THs(), FixedList< T, Size >::transfer(), Foam::transform(), meshRefinement::updateList(), HashPtrTable< T, Key, Hash >::write(), FixedList< T, Size >::writeEntry(), UList< T >::writeEntry(), ThermoParcel< ParcelType >::writeFields(), and PengRobinsonGas< Specie >::Z().