OpenFOAM: applications/utilities/postProcessing/graphics/ensightFoamReader/getFieldScalar.H File Reference
getFieldScalar.H File Reference
Functions
if (nVar >=Num_variables-nSprayVariables)
IOobject fieldObjectPtr (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::NO_READ)
if (!fieldObjectPtr.headerOk())
IOobject fieldObject (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE)
volScalarField scalarField (fieldObject, mesh)
if (which_type==Z_HEX08)
Variables
const cellShapeList & cellShapes = meshPtr->cellShapes()
Function Documentation
if (nVar >=Num_variables- nSprayVariables)
Definition at line 2 of file getFieldScalar.H.
References fieldNames, fieldObjectPtr(), mesh, nVar, and var2field.
IOobject fieldObjectPtr (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::NO_READ)
Referenced by if().
if (!fieldObjectPtr. headerOk())
Definition at line 15 of file getFieldScalar.H.
References fieldNames, fieldObject(), mesh, scalarField(), and var2field.
IOobject fieldObject (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::NO_WRITE)
Referenced by fieldToCell::applyToSet(), for(), if(), and USERD_get_var_value_at_specific().
volScalarField scalarField (fieldObject , mesh)
Referenced by alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField(), ThermalDiffusivity< BasicTurbulenceModel >::alphat(), primitiveMeshTools::cellDeterminant(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::CpByCpv(), heThermo< BasicThermo, MixtureType >::Cpv(), heThermo< BasicThermo, MixtureType >::Cv(), energyJumpAMIFvPatchScalarField::energyJumpAMIFvPatchScalarField(), energyJumpFvPatchScalarField::energyJumpFvPatchScalarField(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), primitiveMeshTools::faceOrthogonality(), polyMeshTools::faceOrthogonality(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTools::faceWeights(), fanFvPatchField< Type >::fanFvPatchField(), filmPyrolysisTemperatureCoupledFvPatchScalarField::filmPyrolysisTemperatureCoupledFvPatchScalarField(), fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), for(), heThermo< BasicThermo, MixtureType >::gamma(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), transformFvPatchField< Type >::gradientInternalCoeffs(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField(), heThermo< BasicThermo, MixtureType >::he(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), if(), inclinedFilmNusseltHeightFvPatchScalarField::inclinedFilmNusseltHeightFvPatchScalarField(), inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField(), TableBase< Type >::interpolator(), makeFvGradScheme(), MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField(), laminar< BasicTurbulenceModel >::nut(), chemistryModel< CompType, ThermoType >::omega(), phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField(), plenumPressureFvPatchScalarField::plenumPressureFvPatchScalarField(), prghPressureFvPatchScalarField::prghPressureFvPatchScalarField(), prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField(), lduMatrix::residual(), symmetryPlaneFvPatchField< Type >::snGrad(), basicSymmetryFvPatchField< Type >::snGrad(), Foam::stabilise(), heThermo< BasicThermo, MixtureType >::THE(), timeVaryingAlphaContactAngleFvPatchScalarField::theta(), constantAlphaContactAngleFvPatchScalarField::theta(), dynamicAlphaContactAngleFvPatchScalarField::theta(), totalPressureFvPatchScalarField::totalPressureFvPatchScalarField(), totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField(), turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField(), uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField(), uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField(), CellZoneInjection< CloudType >::updateMesh(), USERD_get_var_value_at_specific(), transformFvPatchField< Type >::valueInternalCoeffs(), variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField(), polyMeshTools::volRatio(), wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField(), and AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod().
if (which_type = = Z_HEX08)
Definition at line 38 of file getFieldScalar.H.
References cells, Foam::hex(), lookup(), meshPtr, n, and points.
Variable Documentation
const cellShapeList& cellShapes = meshPtr->cellShapes()
Definition at line 35 of file getFieldScalar.H.
Referenced by hexCellLooper::cut(), topoCellLooper::cut(), forAll(), if(), ensightMesh::nFacePrimitives::nFacePrimitives(), USERD_get_gold_part_build_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_part_element_ids_by_type(), and USERD_get_part_elements_by_type().