OpenFOAM: applications/utilities/postProcessing/noise/createFields.H File Reference
createFields.H File Reference
Functions
word dictName ("noiseDict")
if (args.optionFound("dict"))
IOdictionary dict (IOobject(dictName, runTime.system(), runTime, IOobject::MUST_READ))
Variables
scalar pRef = dict.lookupOrDefault("pRef", 0.0)
label N = dict.lookupOrDefault("N", 65536)
label nw = dict.lookupOrDefault("nw", 100)
scalar f1 = dict.lookupOrDefault("f1", 25.0)
scalar fU = dict.lookupOrDefault("fU", 10000.0)
word graphFormat = dict.lookupOrDefault<word>("graphFormat", "raw")
Function Documentation
word dictName ("noiseDict")
Referenced by if(), basicThermo::lookupThermo(), moleFractions< ThermoType >::moleFractions(), basicChemistryModel::New(), basicSolidChemistryModel::New(), basicThermo::New(), and pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
if (args. optionFound"dict")
Definition at line 2 of file createFields.H.
References args, dict(), and dictName().
IOdictionary dict (IOobject(dictName, runTime.system(), runTime, IOobject::MUST_READ))
Referenced by if().
Variable Documentation
scalar pRef = dict.lookupOrDefault("pRef", 0.0)
Definition at line 19 of file createFields.H.
Referenced by forces::calcForcesMoment(), if(), while(), Gulders::~Gulders(), and GuldersEGR::~GuldersEGR().
label N = dict.lookupOrDefault("N", 65536)
Definition at line 22 of file createFields.H.
Referenced by NoSurfaceReaction< CloudType >::clone(), COxidationDiffusionLimitedRate< CloudType >::clone(), COxidationKineticDiffusionLimitedRate< CloudType >::clone(), COxidationHurtMitchell< CloudType >::clone(), COxidationIntrinsicRate< CloudType >::clone(), COxidationMurphyShaddix< CloudType >::clone(), v2f< BasicTurbulenceModel >::correct(), PengRobinsonGas< Specie >::cp(), PengRobinsonGas< Specie >::cpMcv(), surfaceInterpolationScheme< Type >::interpolate(), pairPotential::setLookupTables(), fWallFunctionFvPatchScalarField::updateCoeffs(), and noiseFFT::window().
label nw = dict.lookupOrDefault("nw", 100)
Definition at line 25 of file createFields.H.
Referenced by SpecularReflection< CloudType >::correct(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), Rebound< CloudType >::correct(), LocalInteraction< CloudType >::correct(), StandardWallInteraction< CloudType >::correct(), solidParticle::hitWallPatch(), DSMCParcel< ParcelType >::hitWallPatch(), molecule::hitWallPatch(), noiseFFT::meanPf(), ParticleErosion< CloudType >::postPatch(), and noiseFFT::RMSmeanPf().
scalar f1 = dict.lookupOrDefault("f1", 25.0)
Definition at line 28 of file createFields.H.
Referenced by preserveBafflesConstraint::apply(), addPatchCellLayer::calcSidePatch(), meshRefinement::createZoneBaffles(), decompositionMethod::decompose(), Foam::meshTools::getSharedEdge(), minEqOpFace::operator()(), snappySnapDriver::repatchToSurface(), removeFaces::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), meshRefinement::splitFaces(), externalDisplacementMeshMover::updateMesh(), and Function1< Type >::writeData().
scalar fU = dict.lookupOrDefault("fU", 10000.0)
Definition at line 31 of file createFields.H.
word graphFormat = dict.lookupOrDefault<word>("graphFormat", "raw")
Definition at line 34 of file createFields.H.
Referenced by Foam::makeGraph(), Foam::writeCellGraph(), and Foam::writePatchGraph().