OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
StCorr.H File Reference
Functions
dimensionedScalar StCorr ("StCorr", dimless, 1.0)
dimensionedScalar Ak ("Ak", dimArea, 0.0)
StCorr value ()
Variables
dimensionedScalar AkEst = gSum(mgb*mesh.V().field())
Function Documentation
dimensionedScalar StCorr ("StCorr" , dimless , 1. 0)
dimensionedScalar Ak ("Ak" , dimArea , 0. 0)
StCorr value ()
Referenced by ensightFile::allowUndef(), Foam::allReduce(), sampledSurface::average(), SphereDragForce< CloudType >::calcCoupled(), DistortedSphereDragForce< CloudType >::calcCoupled(), VirtualMassForce< CloudType >::calcCoupled(), PressureGradientForce< CloudType >::calcCoupled(), LiftForce< CloudType >::calcCoupled(), ParticleForceList< CloudType >::calcCoupled(), BrownianMotionForce< CloudType >::calcCoupled(), NonSphereDragForce< CloudType >::calcCoupled(), ParticleForce< CloudType >::calcCoupled(), SRFForce< CloudType >::calcNonCoupled(), GravityForce< CloudType >::calcNonCoupled(), ParamagneticForce< CloudType >::calcNonCoupled(), ParticleForceList< CloudType >::calcNonCoupled(), NonInertialFrameForce< CloudType >::calcNonCoupled(), ParticleForce< CloudType >::calcNonCoupled(), veryInhomogeneousMixture< ThermoType >::cellProducts(), attachDetach::changeTopology(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), timeVaryingMappedFixedValueFvPatchField< Type >::checkTable(), Pstream::combineGather(), kinematicSingleLayer::constrainFilmField(), kinematicSingleLayer::continuityCheck(), PolynomialEntry< Type >::convertTimeBase(), TableBase< Type >::convertTimeBase(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), displacementInterpolationMotionSolver::curPoints(), diaedg(), PolynomialEntry< Type >::dimValue(), TableBase< Type >::dimValue(), Foam::eigenValues(), Time::end(), engineTime::engineTime(), DSMCCloud< ParcelType >::equipartitionInternalEnergy(), DSMCCloud< ParcelType >::equipartitionLinearVelocity(), Time::findClosestTime(), Time::findClosestTimeIndex(), Time::findInstance(), pointToPointPlanarInterpolation::findTime(), Pstream::gather(), Foam::stringOps::getVariable(), cachedRandom::globalPosition(), cachedRandom::globalSample01(), ReactingMultiphaseParcel< ParcelType >::constantProperties::hRetentionCoeff(), i_modp(), i_wrap(), if(), FreeStream< CloudType >::inflow(), sampledSurface::integrate(), laminarFlameSpeed::laminarFlameSpeed(), dimensioned< Type >::lookupOrAddToDict(), lrline(), ensightPart::materialId(), DSMCCloud< ParcelType >::maxwellianAverageSpeed(), DSMCCloud< ParcelType >::maxwellianMostProbableSpeed(), DSMCCloud< ParcelType >::maxwellianRMSSpeed(), ensightPart::name(), ifEqEqOp< value >::operator()(), csvTableReader< Type >::operator()(), interpolationTable< Type >::operator()(), Time::operator++(), sweepData::operator=(), smoothData::operator=(), veryInhomogeneousMixture< ThermoType >::patchFaceProducts(), engineTime::pistonDisplacement(), engineTime::pistonSpeed(), cachedRandom::position(), PatchPostProcessing< CloudType >::postPatch(), interpolationTable< Type >::rateOfChange(), zoltanRenumber::renumber(), Time::run(), cachedRandom::sample01(), timeSelector::select(), timeSelector::selected(), fvMatrix< Type >::setComponentReference(), fvMatrix< Type >::setReference(), Time::setTime(), demandDrivenEntry< Type >::setValue(), fvMatrix< Type >::setValuesFromList(), VariableHardSphere< CloudType >::sigmaTcR(), LarsenBorgnakkeVariableHardSphere< CloudType >::sigmaTcR(), Foam::fvc::sweep(), ParticleStressModel::tau(), engineTime::theta(), TimeState::timeOutputValue(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), externalCoupledMixedFvPatchField< Type >::transferData(), triSurface::triSurfInstance(), ensightFile::undefValue(), UniformDimensionedField< Type >::UniformDimensionedField(), uniformInterpolatedDisplacementPointPatchVectorField::uniformInterpolatedDisplacementPointPatchVectorField(), memInfo::update(), dynamicInkJetFvMesh::update(), movingConeTopoFvMesh::update(), uniformJumpFvPatchField< Type >::updateCoeffs(), uniformJumpAMIFvPatchField< Type >::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), fixedPressureCompressibleDensityFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), activePressureForceBaffleVelocityFvPatchVectorField::updateCoeffs(), USERD_get_sol_times(), USERD_get_timeset_description(), DataEntry< Type >::value(), dsmcFields::write(), ensightFile::write(), writer< Type >::write(), addSubtract::writeAddSubtractValue(), Time::writeAndEnd(), UniformDimensionedField< Type >::writeData(), and Time::writeObject().
Variable Documentation
dimensionedScalar AkEst = gSum(mgb*mesh.V().field())
Definition at line 87 of file StCorr.H.