OpenFOAM: applications/utilities/postProcessing/toBeFunctionObjects/wallHeatFlux/createFields.H File Reference
createFields.H File Reference
Functions
autoPtr< basicThermo > thermo (basicThermo::New(mesh))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh), thermo->rho())
if (isA< fluidThermo >(thermo()))
volScalarField Qr (IOobject("Qr", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE), mesh, dimensionedScalar("Qr", dimMass/pow3(dimTime), 0.0))
Variables
const volScalarField & h = thermo->he()
Planck constant.
autoPtr< volVectorField > UPtr
autoPtr< surfaceScalarField > phiPtr
autoPtr< compressible::turbulenceModel > turbulence
Function Documentation
autoPtr<basicThermo> thermo (basicThermo::New(mesh))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh) , thermo-> rho())
if (isA< fluidThermo > thermo())
Definition at line 25 of file createFields.H.
References Foam::dimMass, Foam::dimTime, mesh, Foam::New(), phi, phiPtr, Foam::pow3(), Qr(), rho, thermo, U(), and UPtr.
volScalarField Qr (IOobject("Qr", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE) , mesh , dimensionedScalar("Qr", dimMass/pow3(dimTime), 0.0))
Referenced by if(), constantRadiation::Shs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), and externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs().
Variable Documentation
const volScalarField& h = thermo->he()
Planck constant.
Definition at line 6 of file createFields.H.
autoPtr<volVectorField> UPtr
Definition at line 21 of file createFields.H.
Referenced by if().
autoPtr<surfaceScalarField> phiPtr
Definition at line 22 of file createFields.H.
Referenced by if().
autoPtr<compressible::turbulenceModel> turbulence
Definition at line 23 of file createFields.H.
Referenced by PaSR< Type >::correct(), diffusion< CombThermoType, ThermoType >::correct(), relaxation::correct(), forAll(), forAllIter(), if(), and LESdelta::New().