OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\n"<< endl;autoPtr< psiuReactionThermo > pThermo (psiuReactionThermo::New(mesh))
thermo validate (args.executable(),"ha","ea")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
Info<< "min(b) = "<< min(b).value()<< endl;Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
if (composition.contains("ft"))
fields add (b)
fields add (thermo.he())
Variables
psiuReactionThermo & thermo = pThermo()
basicMultiComponentMixture & composition = thermo.composition()
volScalarField & p = thermo.p()
const volScalarField & psi = thermo.psi()
volScalarField & b = composition.Y("b")
Wien displacement law constant: default SI units: [m.K].
Info<< "Creating field dpdt\n"<< endl;volScalarField dpdt(IOobject("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n"<< endl;volScalarField K("K", 0.5 *magSqr(U));Info<< "Creating field Xi\n"<< endl;volScalarField Xi(IOobject("Xi", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating the unstrained laminar flame speed\n"<< endl;autoPtr< laminarFlameSpeed > unstrainedLaminarFlameSpeed (laminarFlameSpeed::New(thermo))
Info<< "Reading strained laminar flame speed field Su\n"<< endl;volScalarField Su(IOobject("Su", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);dimensionedScalar SuMin=0.01 *Su.average();dimensionedScalar SuMax=4 *Su.average();Info<< "Calculating turbulent flame speed field St\n"<< endl;volScalarField St(IOobject("St", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), Xi *Su);multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
Info<< "Reading thermophysical properties\n" << endl;autoPtr<psiuReactionThermo> pThermo (psiuReactionThermo::New(mesh))
thermo validate (args. executable(), "ha" , "ea")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
Info<< "min(b) = " << min(b).value() << endl;Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
if (composition. contains"ft")
Definition at line 134 of file createFields.H.
fields add (b)
fields add (thermo. he())
Variable Documentation
psiuReactionThermo& thermo = pThermo()
Definition at line 7 of file createFields.H.
basicMultiComponentMixture& composition = thermo.composition()
Definition at line 10 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 25 of file createFields.H.
const volScalarField& psi = thermo.psi()
Definition at line 26 of file createFields.H.
volScalarField& b = composition.Y("b")
Wien displacement law constant: default SI units: [m.K].
Definition at line 28 of file createFields.H.
Referenced by greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), bufferedAccumulator< Type >::addToBuffers(), tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::circumRadius(), triSurfaceTools::collapseEdges(), boundBox::containsInside(), SSG< BasicTurbulenceModel >::correct(), Foam::vectorTools::cosPhi(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), PengRobinsonGas< Specie >::cp(), PengRobinsonGas< Specie >::cpMcv(), treeBoundBox::distanceCmp(), dmat_uniform(), edge::edge(), Foam::eigenValues(), globalIndexAndTransform::encodeTransformIndex(), searchableSphere::findLine(), searchableCylinder::findLine(), searchableSphere::findLineAny(), searchableCylinder::findLineAny(), forAll(), Foam::HasherDual(), Foam::HasherInt(), if(), coordinateSystem::init(), Foam::interpolate(), jenkins_hashbig(), jenkins_hashlittle(), Smagorinsky< BasicTurbulenceModel >::k(), homogeneousMixture< ThermoType >::mixture(), inhomogeneousMixture< ThermoType >::mixture(), egrMixture< ThermoType >::mixture(), slidingInterface::modifyMotionPoints(), Moment< Type >::Moment(), particle< Type >::movingTetLambda(), line< Point, PointRef >::nearestDist(), Foam::operator!=(), Foam::operator&(), procLess::operator()(), globalIndexAndTransform::less::operator()(), UList< T >::less::operator()(), UList< T >::greater::operator()(), Boussinesq< Specie >::operator*=(), Foam::operator/(), Foam::operator<(), Foam::operator<<(), Foam::operator<=(), Foam::operator==(), Foam::operator>=(), Pair< word >::other(), Foam::parseNASCoord(), plane::planePlaneIntersect(), searchableCylinder::points(), Foam::pow(), Foam::vectorTools::radAngleBetween(), Foam::readBool(), Foam::readLabel(), Foam::readULabel(), normal::sample(), PointHit< point >::setDistance(), bufferedAccumulator< Type >::setSizes(), lduAddressing::size(), Foam::Swap(), swapec(), tetCell::tetCell(), tetPoints::tetPoints(), globalIndexAndTransform::transformIndicesForPatches(), triFace::triFace(), vbedg(), Boussinesq< Specie >::write(), PengRobinsonGas< Specie >::Z(), and FSD< CombThermoType, ThermoType >::~FSD().
Info<< "Creating field dpdt\n" << endl;volScalarField dpdt(IOobject ("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n" << endl;volScalarField K("K", 0.5*magSqr(U));Info<< "Creating field Xi\n" << endl;volScalarField Xi(IOobject ("Xi", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating the unstrained laminar flame speed\n" << endl;autoPtr<laminarFlameSpeed> unstrainedLaminarFlameSpeed(laminarFlameSpeed::New(thermo))
Definition at line 95 of file createFields.H.
Info<< "Reading strained laminar flame speed field Su\n" << endl;volScalarField Su(IOobject ("Su", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);dimensionedScalar SuMin = 0.01*Su.average();dimensionedScalar SuMax = 4*Su.average();Info<< "Calculating turbulent flame speed field St\n" << endl;volScalarField St(IOobject ("St", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), Xi*Su);multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 132 of file createFields.H.