OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
Info<< "Creating combustion model\n"<< endl;autoPtr< combustionModels::psiCombustionModel > combustion (combustionModels::psiCombustionModel::New(mesh))
Info<< "Reading thermophysical properties\n"<< endl;psiReactionThermo &thermo=combustion-> thermo ()
thermo validate (args.executable(),"h","e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.lookup("inertSpecie"))
Info<< "Creating field rho\n"<< endl;volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField &p=thermo.p();const volScalarField &T=thermo.T();const volScalarField &psi=thermo.psi();Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
forAll (Y, i)
fields add (thermo.he())
IOdictionary additionalControlsDict (IOobject("additionalControls", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
Switch solvePrimaryRegion (additionalControlsDict.lookup("solvePrimaryRegion"))
Variables
basicMultiComponentMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
Info<< "Creating field dpdt\n"<< endl;volScalarField dpdt(IOobject("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n"<< endl;volScalarField K("K", 0.5 *magSqr(U));volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);p_rgh=p-rho *gh;mesh.setFluxRequired(p_rgh.name());multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
Info<< "Creating combustion model\n" << endl;autoPtr<combustionModels::psiCombustionModel> combustion (combustionModels::psiCombustionModel::New(mesh))
Referenced by forAll().
Info<< "Reading thermophysical properties\n" << endl;psiReactionThermo& thermo = combustion-> thermo ()
thermo validate (args. executable(), "h" , "e")
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo. lookup"inertSpecie")
Referenced by forAll(), and if().
Info<< "Creating field rho\n" << endl;volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField& p = thermo.p();const volScalarField& T = thermo.T();const volScalarField& psi = thermo.psi();Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Referenced by forAll().
forAll (Y , i)
Definition at line 129 of file createFields.H.
References additionalControlsDict(), mesh, and solvePrimaryRegion().
Referenced by forAll().
fields add (thermo. he())
IOdictionary additionalControlsDict (IOobject("additionalControls", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
Referenced by forAll().
Switch solvePrimaryRegion (additionalControlsDict. lookup"solvePrimaryRegion")
Referenced by forAll().
Variable Documentation
basicMultiComponentMixture& composition = thermo.composition()
Definition at line 18 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 19 of file createFields.H.
Info<< "Creating field dpdt\n" << endl;volScalarField dpdt(IOobject ("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n" << endl;volScalarField K("K", 0.5*magSqr(U));volScalarField p_rgh(IOobject ("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);p_rgh = p - rho*gh;mesh.setFluxRequired(p_rgh.name());multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 127 of file createFields.H.
Referenced by pointFieldDecomposer::patchFieldDecomposer::directAddressing(), Foam::MapConsistentVolFields(), Foam::MapDimensionedFields(), Foam::MapGeometricFields(), Foam::MapLagrangianFields(), fvMeshAdder::MapSurfaceFields(), Foam::MapVolFields(), fvMeshAdder::MapVolFields(), multivariateScheme< Type, Scheme >::multivariateScheme(), multivariateSelectionScheme< Type >::multivariateSelectionScheme(), NamedEnum< Enum, nEnum >::names(), convectionScheme< Type >::New(), isNotEqOp< T >::operator()(), fvMeshDistribute::printFieldInfo(), pointFieldReconstructor::reconstructFields(), fvFieldReconstructor::reconstructFvSurfaceFields(), fvFieldReconstructor::reconstructFvVolumeFields(), fvFieldReconstructor::reconstructFvVolumeInternalFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), Foam::UnMapped(), and fvFieldDecomposer::processorSurfacePatchFieldDecomposer::weights().