OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
readTransportProperties.H File Reference
Functions
singlePhaseTransportModel laminarTransport (U, phi)
dimensionedScalar beta ("beta", dimless/dimTemperature, laminarTransport)
dimensionedScalar TRef ("TRef", dimTemperature, laminarTransport)
dimensionedScalar Pr ("Pr", dimless, laminarTransport)
dimensionedScalar Prt ("Prt", dimless, laminarTransport)
Function Documentation
singlePhaseTransportModel laminarTransport (U , phi)
dimensionedScalar beta ("beta" , dimless/ dimTemperature, laminarTransport)
Referenced by ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), TrajectoryCollision< CloudType >::collideParcels(), rotorDiskSource::constructGeometry(), kOmegaSST< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), Analytical< Type >::integrate(), triangleFuncs::intersectAxesBundle(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeInjection< CloudType >::setProperties(), PBiCICG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCCCG< Type, DType, LUType >::solve(), PBiCG::solve(), PCG::solve(), FacePostProcessing< CloudType >::write(), and ParticleCollector< CloudType >::write().
dimensionedScalar TRef ("TRef" , dimTemperature , laminarTransport)
dimensionedScalar Pr ("Pr" , dimless , laminarTransport)
Referenced by ThermoParcel< ParcelType >::calc(), SRIFallOffFunction::operator()(), TroeFallOffFunction::operator()(), FallOffReactionRate< ReactionRate, FallOffFunction >::operator()(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::operator()(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
dimensionedScalar Prt ("Prt" , dimless , laminarTransport)