OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
if (mesh.nCells()!=1)
Info<< "Reading initial conditions.\n"<< endl;IOdictionary initialConditions(IOobject("initialConditions", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));scalar p0=readScalar(initialConditions.lookup("p"));scalar T0=readScalar(initialConditions.lookup("T"));#24"/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/combustion/chemFoam/createFields.H"2 Info<< nl<< "Reading thermophysicalProperties"<< endl;autoPtr< psiChemistryModel > pChemistry (psiChemistryModel::New(mesh))
thermo validate (args.executable(),"h")
volScalarField rho (IOobject("rho", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("zero", dimensionSet(dimEnergy/dimMass/dimTemperature), 0.0))
volVectorField U (IOobject("U", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("zero", dimVelocity, Zero))
OFstream post (args.path()/"chemFoam.out")
Variables
psiChemistryModel & chemistry = pChemistry()
psiReactionThermo & thermo = chemistry.thermo()
Function Documentation
if (mesh.nCells()! = 1)
Definition at line 1 of file createFields.H.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, mesh, Foam::New(), Foam::nl, pChemistry(), and readScalar.
Info<< "Reading initial conditions.\n" << endl; IOdictionary initialConditions (IOobject ("initialConditions", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); scalar p0 = readScalar(initialConditions.lookup("p")); scalar T0 = readScalar(initialConditions.lookup("T"));# 24 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/combustion/chemFoam/createFields.H" 2 Info<< nl << "Reading thermophysicalProperties" << endl; autoPtr<psiChemistryModel> pChemistry (psiChemistryModel::New(mesh))
Referenced by if().
thermo validate (args. executable(), "h")
Referenced by surfMesh::surfZones().
volScalarField rho (IOobject("rho", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("zero", dimensionSet(dimEnergy/dimMass/dimTemperature), 0.0))
volVectorField U (IOobject("U", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("zero", dimVelocity, Zero))
Referenced by forAll(), and if().
OFstream post (args.path()/"chemFoam.out")
Variable Documentation
psiChemistryModel& chemistry = pChemistry()
Definition at line 29 of file createFields.H.
psiReactionThermo& thermo = chemistry.thermo()
Definition at line 31 of file createFields.H.
Referenced by LiquidEvaporationBoil< CloudType >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), for(), forAll(), forAllConstIter(), if(), laminar< Type >::R(), ReactingCloud< CloudType >::ReactingCloud(), ReactingCloud< CloudType >::setParcelThermoProperties(), singleStepCombustion< CombThermoType, ThermoType >::singleStepCombustion(), chemistryModel< CompType, ThermoType >::solve(), chemistryModel< CompType, ThermoType >::tc(), and while().