OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createFields.H File Reference
Functions
IOdictionary propsDict (IOobject("particleTrackProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED))
const word cloudName (propsDict.lookup("cloudName"))
label sampleFrequency (readLabel(propsDict.lookup("sampleFrequency")))
label maxPositions (readLabel(propsDict.lookup("maxPositions")))
word setFormat (propsDict.lookupOrDefault< word >("setFormat","vtk"))
Function Documentation
IOdictionary propsDict (IOobject("particleTrackProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED))
Referenced by meanVelocityForce::meanVelocityForce(), fieldAverage::readAveragingProperties(), fieldAverage::writeAveragingProperties(), and meanVelocityForce::writeProps().
const word cloudName (propsDict. lookup"cloudName")
Referenced by Relaxation< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), Explicit< CloudType >::cacheFields(), if(), Foam::MapLagrangianFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), and cloudInfo::write().
label sampleFrequency (readLabel(propsDict.lookup("sampleFrequency")))
label maxPositions (readLabel(propsDict.lookup("maxPositions")))
word setFormat (propsDict.lookupOrDefault< word > "setFormat","vtk")