OpenFOAM: applications/solvers/combustion/fireFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Creating combustion model\n"<< endl;autoPtr< combustionModels::psiCombustionModel > combustion (combustionModels::psiCombustionModel::New(mesh))
Info<< "Reading thermophysical properties\n"<< endl;psiReactionThermo &thermo=combustion-> thermo ()
thermo validate (args.executable(),"h","e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.lookup("inertSpecie"))
if (!composition.species().found(inertSpecie))
Info<< "Creating field rho\n"<< endl;volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField &p=thermo.p();Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
volScalarField p_rgh (IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh)
mesh setFluxRequired (p_rgh.name())
forAll (Y, i)
fields add (thermo.he())
IOdictionary additionalControlsDict (IOobject("additionalControls", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
Switch solvePrimaryRegion (additionalControlsDict.lookup("solvePrimaryRegion"))
Switch solvePyrolysisRegion (additionalControlsDict.lookupOrDefault< bool >("solvePyrolysisRegion", true))
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variables
basicMultiComponentMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
Info<< "Creating combustion model\n" << endl;autoPtr<combustionModels::psiCombustionModel> combustion (combustionModels::psiCombustionModel::New(mesh))
Referenced by forAll(), and if().
Info<< "Reading thermophysical properties\n" << endl;psiReactionThermo& thermo = combustion-> thermo ()
thermo validate (args. executable(), "h" , "e")
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo. lookup"inertSpecie")
Referenced by if().
if (!composition. species).found(inertSpecie)
Definition at line 22 of file createFields.H.
References args, combustion(), Foam::endl(), argList::executable(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, inertSpecie(), Foam::Info, mesh, Foam::New(), p, p_rgh(), phi, rho, thermo, turbulence, and U().
Info<< "Creating field rho\n" << endl;volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField& p = thermo.p();Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
volScalarField p_rgh (IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE) , mesh)
Referenced by if().
mesh setFluxRequired (p_rgh. name())
forAll (Y , i)
Definition at line 106 of file createFields.H.
References additionalControlsDict(), Foam::dimEnergy, Foam::dimTime, dpdt, dQ(), Foam::endl(), Foam::Info, Foam::magSqr(), mesh, solvePrimaryRegion(), and solvePyrolysisRegion().
Referenced by forAll().
fields add (thermo. he())
IOdictionary additionalControlsDict (IOobject("additionalControls", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
Referenced by forAll().
Switch solvePrimaryRegion (additionalControlsDict. lookup"solvePrimaryRegion")
Referenced by forAll().
Switch solvePyrolysisRegion (additionalControlsDict.lookupOrDefault< bool > "solvePyrolysisRegion", true)
Referenced by forAll().
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Referenced by forAll().
Variable Documentation
basicMultiComponentMixture& composition = thermo.composition()
Definition at line 18 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 19 of file createFields.H.
multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 104 of file createFields.H.
Referenced by pointFieldDecomposer::patchFieldDecomposer::directAddressing(), Foam::MapConsistentVolFields(), Foam::MapDimensionedFields(), fvMeshAdder::MapDimFields(), Foam::MapGeometricFields(), Foam::MapLagrangianFields(), fvMeshAdder::MapSurfaceFields(), Foam::MapVolFields(), fvMeshAdder::MapVolFields(), multivariateScheme< Type, Scheme >::multivariateScheme(), multivariateSelectionScheme< Type >::multivariateSelectionScheme(), NamedEnum< Enum, nEnum >::names(), convectionScheme< Type >::New(), isNotEqOp< T >::operator()(), fvMeshDistribute::printFieldInfo(), Foam::readFields(), Foam::readUniformFields(), pointFieldReconstructor::reconstructFields(), fvFieldReconstructor::reconstructFvSurfaceFields(), fvFieldReconstructor::reconstructFvVolumeFields(), fvFieldReconstructor::reconstructFvVolumeInternalFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), Foam::UnMapped(), and fvFieldDecomposer::processorSurfacePatchFieldDecomposer::weights().