OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
rhoEqn.H File Reference
Solve the continuity for density.
Functions
fvOptions constrain (rhoEqn)
rhoEqn solve ()
fvOptions correct (rho)
Detailed Description
Solve the continuity for density.
Original source file rhoEqn.H
Definition in file rhoEqn.H.
Function Documentation
fvOptions constrain (rhoEqn)
Referenced by motionSmootherAlgo::avg(), and motionSmootherAlgo::smooth().
he2Eqn solve ()
Referenced by MPPICCloud< CloudType >::evolve(), CollidingCloud< CloudType >::evolve(), SprayCloud< CloudType >::evolve(), ReactingMultiphaseCloud< CloudType >::evolve(), ReactingCloud< CloudType >::evolve(), ThermoCloud< CloudType >::evolve(), for(), if(), Foam::MULES::implicitSolve(), Foam::solve(), adaptiveSolver::solve(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), chemistryModel< CompType, ThermoType >::solve(), and fvMatrix< Type >::solveSegregated().
fvOptions correct (rho)