OpenFOAM: applications/solvers/combustion/reactingFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Creating reaction model\n"<< endl;autoPtr< combustionModels::psiCombustionModel > reaction (combustionModels::psiCombustionModel::New(mesh))
thermo validate (args.executable(),"h","e")
const word inertSpecie (thermo.lookup("inertSpecie"))
if (!composition.species().found(inertSpecie))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh), thermo.rho())
Info<< "Reading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);volScalarField &p=thermo.p();dimensionedScalar rhoMax(dimensionedScalar::lookupOrDefault("rhoMax", pimple.dict(), dimDensity, GREAT));dimensionedScalar rhoMin(dimensionedScalar::lookupOrDefault("rhoMin", pimple.dict(), dimDensity, 0));mesh.setFluxRequired(p.name());Info<< "Creating turbulence model.\n"<< nl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
reaction setTurbulence (turbulence())
forAll (Y, i)
fields add (thermo.he())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variables
psiReactionThermo & thermo = reaction->thermo()
basicMultiComponentMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
Info<< "Creating field dpdt\n"<< endl;volScalarField dpdt(IOobject("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n"<< endl;volScalarField K("K", 0.5 *magSqr(U));multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
Info<< "Creating reaction model\n" << endl;autoPtr<combustionModels::psiCombustionModel> reaction (combustionModels::psiCombustionModel::New(mesh))
Referenced by singleStepReactingMixture< ThermoType >::calculateMaxProducts(), singleStepReactingMixture< ThermoType >::calculateqFuel(), forAll(), singleStepReactingMixture< ThermoType >::fresCorrect(), if(), mixtureFractionSoot< ThermoType >::mixtureFractionSoot(), Foam::operator<<(), solidReaction< ReactionThermo >::write(), and Reaction< ReactionThermo >::write().
thermo validate (args. executable(), "h" , "e")
const word inertSpecie (thermo. lookup"inertSpecie")
if (!composition. species).found(inertSpecie)
Definition at line 15 of file createFields.H.
References args, Foam::dimDensity, Foam::dimTime, dpdt, Foam::endl(), argList::executable(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, inertSpecie(), Foam::Info, Foam::magSqr(), mesh, Foam::New(), Foam::nl, p, phi, pimple, reaction(), rho, rhoMax(), rhoMin(), thermo, turbulence, and U().
volScalarField rho (IOobject("rho", runTime.timeName(), mesh) , thermo. rho())
Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);volScalarField& p = thermo.p();dimensionedScalar rhoMax(dimensionedScalar::lookupOrDefault ("rhoMax", pimple.dict(), dimDensity, GREAT));dimensionedScalar rhoMin(dimensionedScalar::lookupOrDefault ("rhoMin", pimple.dict(), dimDensity, 0));mesh.setFluxRequired(p.name());Info << "Creating turbulence model.\n" << nl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
reaction setTurbulence (turbulence())
forAll (Y , i)
Definition at line 112 of file createFields.H.
References Foam::dimEnergy, Foam::dimTime, dQ(), and mesh.
fields add (thermo. he())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variable Documentation
psiReactionThermo& thermo = reaction->thermo()
Definition at line 8 of file createFields.H.
basicMultiComponentMixture& composition = thermo.composition()
Definition at line 11 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 12 of file createFields.H.
Info<< "Creating field dpdt\n" << endl;volScalarField dpdt(IOobject ("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n" << endl;volScalarField K("K", 0.5*magSqr(U));multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 110 of file createFields.H.