OpenFOAM: applications/solvers/lagrangian/reactingParcelFilmFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Creating combustion model\n"<< endl;autoPtr< combustionModels::psiCombustionModel > combustion (combustionModels::psiCombustionModel::New(mesh))
thermo validate (args.executable(),"h","e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.lookup("inertSpecie"))
Info<< "Creating field rho\n"<< endl;volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField &p=thermo.p();const volScalarField &T=thermo.T();const volScalarField &psi=thermo.psi();Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
forAll (Y, i)
fields add (thermo.he())
IOdictionary additionalControlsDict (IOobject("additionalControls", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
Switch solvePrimaryRegion (additionalControlsDict.lookup("solvePrimaryRegion"))
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variables
psiReactionThermo & thermo = combustion->thermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
Info<< "Creating field dpdt\n"<< endl;volScalarField dpdt(IOobject("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n"<< endl;volScalarField K("K", 0.5 *magSqr(U));volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);p_rgh=p-rho *gh;mesh.setFluxRequired(p_rgh.name());multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
Info<< "Creating combustion model\n" << endl;autoPtr<combustionModels::psiCombustionModel> combustion (combustionModels::psiCombustionModel::New(mesh))
thermo validate (args. executable(), "h" , "e")
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo. lookup"inertSpecie")
Info<< "Creating field rho\n" << endl;volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField& p = thermo.p();const volScalarField& T = thermo.T();const volScalarField& psi = thermo.psi();Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
forAll (Y , i)
Definition at line 109 of file createFields.H.
References additionalControlsDict(), Foam::dimEnergy, Foam::dimTime, dQ(), mesh, and solvePrimaryRegion().
fields add (thermo. he())
IOdictionary additionalControlsDict (IOobject("additionalControls", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
Switch solvePrimaryRegion (additionalControlsDict. lookup"solvePrimaryRegion")
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variable Documentation
psiReactionThermo& thermo = combustion->thermo()
Definition at line 8 of file createFields.H.
basicSpecieMixture& composition = thermo.composition()
Definition at line 13 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 14 of file createFields.H.
Info<< "Creating field dpdt\n" << endl;volScalarField dpdt(IOobject ("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n" << endl;volScalarField K("K", 0.5*magSqr(U));volScalarField p_rgh(IOobject ("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);p_rgh = p - rho*gh;mesh.setFluxRequired(p_rgh.name());multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 107 of file createFields.H.