OpenFOAM-dev: applications/solvers/lagrangian/reactingParcelFoam/createFields.H File Reference 2
createFields.H File Reference
Functions
Info<< "Creating combustion model\n"<< endl;autoPtr< combustionModels::rhoCombustionModel > combustion (combustionModels::rhoCombustionModel::New(mesh))
thermo validate (args.executable(),"h","e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.lookup("inertSpecie"))
if (!composition.contains(inertSpecie))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
Info<< "\nReading field U\n"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());dimensionedScalar rhoMax(dimensionedScalar::lookupOrDefault("rhoMax", pimple.dict(), dimDensity, GREAT));dimensionedScalar rhoMin(dimensionedScalar::lookupOrDefault("rhoMin", pimple.dict(), dimDensity, 0));Info<< "Creating turbulence model\n"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
forAll (Y, i)
fields add (thermo.he())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variables
rhoReactionThermo & thermo = combustion->thermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
Info<< "Creating field dpdt\n"<< endl;volScalarField dpdt(IOobject("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n"<< endl;volScalarField K("K", 0.5 *magSqr(U));Info<< "Creating multi-variate interpolation scheme\n"<< endl;multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
Info<< "Creating combustion model\n" << endl;autoPtr<combustionModels::rhoCombustionModel> combustion (combustionModels::rhoCombustionModel::New(mesh))
thermo validate (args. executable(), "h" , "e")
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo. lookup"inertSpecie")
if (!composition. containsinertSpecie)
Definition at line 20 of file createFields.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and inertSpecie().
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());dimensionedScalar rhoMax(dimensionedScalar::lookupOrDefault ("rhoMax", pimple.dict(), dimDensity, GREAT));dimensionedScalar rhoMin(dimensionedScalar::lookupOrDefault ("rhoMin", pimple.dict(), dimDensity, 0));Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
forAll (Y , i)
Definition at line 117 of file createFields.H.
References Foam::dimEnergy, Foam::dimTime, dQ(), and mesh.
fields add (thermo. he())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variable Documentation
rhoReactionThermo& thermo = combustion->thermo()
Definition at line 10 of file createFields.H.
basicSpecieMixture& composition = thermo.composition()
Definition at line 15 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 16 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 28 of file createFields.H.
Info<< "Creating field dpdt\n" << endl;volScalarField dpdt(IOobject ("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n" << endl;volScalarField K("K", 0.5*magSqr(U));Info<< "Creating multi-variate interpolation scheme\n" << endl;multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 115 of file createFields.H.