OpenFOAM: applications/solvers/stressAnalysis/solidDisplacementFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading field D\n"<< endl;volVectorField D(IOobject("D", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);autoPtr< volScalarField > Tptr (nullptr)
if (thermalStress)
Function Documentation
Info<< "Reading field D\n" << endl;volVectorField D(IOobject ("D", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);autoPtr<volScalarField> Tptr (nullptr)
Referenced by if().
if (thermalStress)
Definition at line 21 of file createFields.H.
References compactNormalStress(), Foam::fvc::div(), Foam::endl(), Foam::fvc::grad(), Foam::I, Foam::Info, lambda(), Foam::fvc::laplacian(), mesh, mu(), Tptr(), Foam::tr(), and Foam::twoSymm().