OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createDynamicFvMesh.H File Reference
Functions
Info<< "Create mesh for time = "<< runTime.timeName()<< nl<< endl;autoPtr< dynamicFvMesh > meshPtr (dynamicFvMesh::New(IOobject (dynamicFvMesh::defaultRegion, runTime.timeName(), runTime, IOobject::MUST_READ)))
Variables
dynamicFvMesh & mesh = meshPtr()
Function Documentation
Info<< "Create mesh for time = " << runTime.timeName() << nl << endl; autoPtr<dynamicFvMesh> meshPtr (dynamicFvMesh::New(IOobject (dynamicFvMesh::defaultRegion, runTime.timeName(), runTime, IOobject::MUST_READ)))
Variable Documentation
dynamicFvMesh& mesh = meshPtr()
Definition at line 18 of file createDynamicFvMesh.H.
Referenced by Foam::fvc::absolute(), greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), isoSurface::adaptPatchFields(), refinementHistoryConstraint::add(), refinementHistory::add(), snappyLayerDriver::addLayers(), fvMeshTools::addPatch(), meshRefinement::addPatch(), ThermoCloud< CloudType >::ap(), meshRefinement::appendPatch(), refinementHistoryConstraint::apply(), refinementHistory::apply(), fieldToCell::applyToSet(), FreeStream< CloudType >::autoMap(), Foam::fvc::average(), writeFile::baseFileDir(), basicMultiComponentMixture::basicMultiComponentMixture(), SRFForce< CloudType >::cacheFields(), Relaxation< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), ParamagneticForce< CloudType >::cacheFields(), Explicit< CloudType >::cacheFields(), NonInertialFrameForce< CloudType >::cacheFields(), interpolate::calc(), mag::calc(), magSqr::calc(), div::calc(), components::calc(), magGrad::calc(), randomise::calc(), addSubtract::calc(), curvatureSeparation::calcCosAngle(), faceZone::calcFaceZonePatch(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< FitDataType, ExtendedStencil, Polynomial >::calcFit(), forces::calcForcesMoment(), processorPolyPatch::calcGeometry(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), ThermoParcel< ParcelType >::calcHeatTransfer(), curvatureSeparation::calcInvR1(), fieldMinMax::calcMinMaxFields(), sampledSet::calcSign(), ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), cyclicPolyPatch::calcTransforms(), Stochastic< CloudType >::calculate(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), KinematicParcel< ParcelType >::calcVelocity(), Foam::fvc::cellReduce(), CentredFitData< Polynomial >::CentredFitData(), layerAdditionRemoval::changeTopology(), attachDetach::changeTopology(), slidingInterface::changeTopology(), polyBoundaryMesh::checkDefinition(), faceZone::checkDefinition(), pointZone::checkParallelSync(), faceZone::checkParallelSync(), chemistryModel< CompType, ThermoType >::chemistryModel(), polyBoundaryMesh::clearAddressing(), SprayParcel< ParcelType >::clone(), functionObject::clone(), ReactingParcel< ParcelType >::clone(), meshRefinement::collectAndPrint(), componentDisplacementMotionSolver::componentDisplacementMotionSolver(), fixedTemperatureConstraint::constrain(), pointConstraints::constrain(), Foam::constrainPressure(), GAMGAgglomeration::continueAgglomerating(), Foam::MULES::correct(), inverseVolumeDiffusivity::correct(), directionalDiffusivity::correct(), motionDirectionalDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), inverseFaceDistanceDiffusivity::correct(), inverseDistanceDiffusivity::correct(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), laminar< Type >::correct(), wallDistData< TransferType >::correct(), curvatureSeparation::correct(), patchDataWave< TransferType >::correct(), pointLinear< Type >::correction(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwind< Type >::correction(), Foam::CorrectPhi(), Foam::correctUphiBCs(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), heThermo< BasicThermo, MixtureType >::Cp(), heThermo< BasicThermo, MixtureType >::CpByCpv(), heThermo< BasicThermo, MixtureType >::Cpv(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), displacementMeshMoverMotionSolver::curPoints(), displacementInterpolationMotionSolver::curPoints(), heThermo< BasicThermo, MixtureType >::Cv(), manualDecomp::decompose(), decompositionMethod::decompose(), fvFieldDecomposer::patchFieldDecomposer::directAddressing(), pointFieldReconstructor::pointPatchFieldReconstructor::directAddressing(), fvFieldReconstructor::fvPatchFieldReconstructor::directAddressing(), directions::directions(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), pointTopoDistanceData::distance(), refinementHistory::distribute(), snappyRefineDriver::doRefine(), noCombustion< CombThermoType >::dQ(), singleStepCombustion< CombThermoType, ThermoType >::dQ(), laminar< Type >::dQ(), wideBandAbsorptionEmission::ECont(), ThermoCloud< CloudType >::Ep(), yPlus::execute(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), faceAreaPairGAMGAgglomeration::faceAreaPairGAMGAgglomeration(), polyPatch::faceAreas(), polyPatch::faceCells(), polyPatch::faceCentres(), mappedPatchBase::facePoints(), surfaceZonesInfo::faceType(), FitData< FitDataType, ExtendedStencil, Polynomial >::findFaceDirs(), sampledSet::findNearFace(), mappedPatchBase::findSamples(), polyMesh::findTetFacePt(), cellCuts::flip(), PatchFlowRateInjection< CloudType >::flowRate(), multivariateGaussConvectionScheme< Type >::flux(), for(), forAll(), forAllIter(), correctedSnGrad< Type >::fullGradCorrection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), steadyStateD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), ddtScheme< Type >::fvcDdtPhiCoeff(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), multivariateGaussConvectionScheme< Type >::fvcDiv(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), multivariateGaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), heThermo< BasicThermo, MixtureType >::gamma(), GeometricField< Type, PatchField, GeoMesh >::GeometricField(), get_edge_list(), get_geom_list(), get_mesh_dim(), get_num_edges_list(), get_number_of_vertices(), get_vertex_list(), sampledSet::getBoundaryCell(), cellLooper::getFirstVertEdge(), cellLooper::getMisAlignedEdge(), sampledSet::getNeighbourCell(), undoableMeshCutter::getSplitFaces(), sampledSet::getTrackingPoint(), cellLooper::getVertEdgesNonFace(), cellLooper::getVertFacesNonEdge(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), heThermo< BasicThermo, MixtureType >::hc(), heThermo< BasicThermo, MixtureType >::he(), hexRef8Data::hexRef8Data(), if(), Foam::MULES::implicitSolve(), InflationInjection< CloudType >::InflationInjection(), FreeStream< CloudType >::inflow(), MPPICCloud< CloudType >::info(), processorPolyPatch::initOrder(), SurfaceFilmModel< CloudType >::inject(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), multivariateGaussConvectionScheme< Type >::interpolate(), distanceSurface::interpolateField(), sampledPatchInternalField::interpolateField(), sampledPatch::interpolateField(), sampledTriSurfaceMesh::interpolateField(), Foam::interpolatePointToCell(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), temperatureCoupledBase::kappa(), lduPrimitiveMesh::lduPrimitiveMesh(), Foam::MULES::limitCorr(), PhiScheme< Type, PhiLimiter >::limiter(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), Foam::MULES::limiterCorr(), localEulerDdt::localEulerDdt(), basicThermo::lookupOrConstruct(), main(), meshRefinement::makeDisplacementField(), makeFvGradScheme(), fvMeshDistribute::mapExposedFaces(), KinematicParcel< ParcelType >::massCell(), LocalInteraction< CloudType >::massEscape(), LocalInteraction< CloudType >::massStick(), faceZone::meshEdges(), polyPatch::meshEdges(), MeshedSurface< Face >::MeshedSurface(), displacementMeshMoverMotionSolver::meshMover(), steadyStateDdtScheme< Type >::meshPhi(), EulerDdtScheme< Type >::meshPhi(), backwardDdtScheme< Type >::meshPhi(), CoEulerDdtScheme< Type >::meshPhi(), SLTSDdtScheme< Type >::meshPhi(), localEulerDdtScheme< Type >::meshPhi(), slidingInterface::modifyMotionPoints(), DSMCParcel< ParcelType >::move(), medialAxisMeshMover::move(), polyBoundaryMesh::movePoints(), NamedEnum< Enum, nEnum >::names(), regionCoupledBaseGAMGInterface::nbrLduInterface(), sampledThresholdCellFaces::needsUpdate(), sampledIsoSurfaceCell::needsUpdate(), sampledIsoSurface::needsUpdate(), regionCoupledBase::neighbPatch(), regionCoupledBase::neighbPatchID(), basicChemistryModel::New(), psiReactionThermo::New(), rhoReactionThermo::New(), scatterModel::New(), fluidThermo::New(), psiuReactionThermo::New(), absorptionEmissionModel::New(), psiThermo::New(), sootModel::New(), rhoChemistryModel::New(), psiChemistryModel::New(), LESfilter::New(), basicSolidChemistryModel::New(), psiCombustionModel::New(), rhoCombustionModel::New(), solidReactionThermo::New(), gradScheme< Type >::New(), snGradScheme< Type >::New(), rhoThermo::New(), patchDistMethod::New(), solidThermo::New(), AveragingMethod< Type >::New(), surfaceInterpolationScheme< Type >::New(), d2dt2Scheme< Type >::New(), ddtScheme< Type >::New(), ParticleForce< CloudType >::New(), divScheme< Type >::New(), surfaceFilmModel::New(), reactionRateFlameArea::New(), multivariateSurfaceInterpolationScheme< Type >::New(), limitedSurfaceInterpolationScheme< Type >::New(), laplacianScheme< Type, GType >::New(), cellLooper::New(), thermalBaffleModel::New(), basicThermo::New(), pyrolysisModel::New(), option::New(), porosityModel::New(), sampledSet::New(), sampledSurface::New(), topoSet::New(), topoSetSource::New(), GAMGAgglomeration::New(), pyrMatcher::nMaxVertPerFace(), tetWedgeMatcher::nMaxVertPerFace(), wedgeMatcher::nMaxVertPerFace(), prismMatcher::nMaxVertPerFace(), hexMatcher::nMaxVertPerFace(), tetMatcher::nMaxVertPerFace(), cellCuts::nonAnchorPoints(), minEqOpFace::operator()(), ListPlusEqOp< T, Size >::operator()(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), anisotropicFilter::operator()(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), cyclicPolyPatch::order(), metisDecomp::parallelAware(), ptscotchDecomp::parallelAware(), scotchDecomp::parallelAware(), InflationInjection< CloudType >::parcelsToInject(), sampledPatch::patchIDs(), boundaryMesh::patchNames(), sampledSet::pointInCell(), VoidFraction< CloudType >::postEvolve(), VoidFraction< CloudType >::preEvolve(), ParticleTrap< CloudType >::preEvolve(), ParticleErosion< CloudType >::preEvolve(), sampledSet::pushIn(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), pyrolysisModelCollection::pyrolysisModelCollection(), ReactingCloud< CloudType >::ReactingCloud(), forces::read(), IOPosition< CloudType >::readData(), Foam::fvc::reconstruct(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), Foam::fvc::reconstructMag(), refinementHistory::refinementHistory(), Foam::fvc::relative(), GeometricField< Type, PatchField, GeoMesh >::relax(), undoableMeshCutter::removeSplitFaces(), manualRenumber::renumber(), zoltanRenumber::renumber(), fvMeshTools::reorderPatches(), cyclicAMIPolyPatch::resetAMI(), forces::rho(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::RRg(), solidChemistryModel< CompType, SolidThermo >::RRs(), sampledTriSurfaceMesh::sampleField(), mappedPatchBase::sampleSize(), ThermoCloud< CloudType >::setModels(), fvMeshTools::setPatchFields(), PatchInjection< CloudType >::setPositionAndCell(), PatchFlowRateInjection< CloudType >::setPositionAndCell(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setPropagationTol(), PointEdgeWave< Type, TrackingData >::setPropagationTol(), refinementIterator::setRefinement(), perfectInterface::setRefinement(), layerAdditionRemoval::setRefinement(), fvMatrix< Type >::setValuesFromList(), noCombustion< CombThermoType >::Sh(), laminar< Type >::Sh(), ThermoCloud< CloudType >::Sh(), ThermoCloud< CloudType >::sigmap(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), Foam::fvc::smooth(), snappyRefineDriver::snappyRefineDriver(), solidChemistryModel< CompType, SolidThermo >::solidChemistryModel(), displacementMeshMoverMotionSolver::solve(), sixDoFRigidBodyMotionSolver::solve(), displacementLayeredMotionMotionSolver::solve(), rigidBodyMeshMotion::solve(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), GAMGSolver::solve(), fvMatrix< Type >::solve(), chemistryModel< CompType, ThermoType >::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solver(), fvMatrix< Type >::solveSegregated(), SprayParcel< ParcelType >::solveTABEq(), ThermoSurfaceFilm< CloudType >::splashInteraction(), Foam::fvc::spread(), ReactingCloud< CloudType >::Srho(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), regionCoupledBase::surfPtr(), cyclicAMIPolyPatch::surfPtr(), mappedPatchBase::surfPtr(), Foam::fvc::sweep(), ReactingCloud< CloudType >::SYi(), hexRef8Data::sync(), GeometricField< Type, PatchField, GeoMesh >::T(), chemistryModel< CompType, ThermoType >::tc(), externalPointEdgePoint::trackingData::trackingData(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), sampledPlane::update(), sampledPatch::update(), sampledTriSurfaceMesh::update(), cellMotionFvPatchField< Type >::updateCoeffs(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), movingWallVelocityFvPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingDisplacementPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), surfaceDisplacementPointPatchVectorField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), ReactingParcel< ParcelType >::updateMassFraction(), PatchInjection< CloudType >::updateMesh(), PatchFlowRateInjection< CloudType >::updateMesh(), componentDisplacementMotionSolver::updateMesh(), displacementMotionSolver::updateMesh(), perfectInterface::updateMesh(), layerAdditionRemoval::updateMesh(), polyBoundaryMesh::updateMesh(), slidingInterface::updateMesh(), UpwindFitData< Polynomial >::UpwindFitData(), USERD_get_var_by_component(), USERD_get_var_value_at_specific(), Implicit< CloudType >::velocityCorrection(), Explicit< CloudType >::velocityCorrection(), basicSpecieMixture::W(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), wallShearStress::wallShearStress(), extendedUpwindCellToFaceStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), limitedSurfaceInterpolationScheme< Type >::weights(), polyBoundaryMesh::whichPatch(), while(), PatchPostProcessing< CloudType >::write(), dsmcFields::write(), FacePostProcessing< CloudType >::write(), histogram::write(), edgeMesh::write(), ParticleCollector< CloudType >::write(), regionSizeDistribution::write(), addSubtract::writeAddSubtractField(), addSubtract::writeAddSubtractValue(), components::writeComponentFields(), edgeVertex::writeCut(), div::writeDivField(), residuals::writeFileHeader(), interpolate::writeInterpolateField(), mag::writeMagField(), magGrad::writeMagGradField(), magSqr::writeMagSqrField(), sixDoFRigidBodyMotionSolver::writeObject(), rigidBodyMeshMotion::writeObject(), randomise::writeRandomField(), residuals::writeResidual(), cellSource::writeValues(), faceSource::writeValues(), yPlus::yPlus(), fvMeshTools::zeroPatchFields(), cellMatcher::~cellMatcher(), coordinateRotation::~coordinateRotation(), CuthillMcKeeRenumber::~CuthillMcKeeRenumber(), cylindrical::~cylindrical(), FSD< CombThermoType, ThermoType >::~FSD(), gradScheme< Type >::~gradScheme(), greyMeanSolidAbsorptionEmission::~greyMeanSolidAbsorptionEmission(), inverseDistanceDiffusivity::~inverseDistanceDiffusivity(), manualDecomp::~manualDecomp(), manualRenumber::~manualRenumber(), medialAxisMeshMover::~medialAxisMeshMover(), multiLevelDecomp::~multiLevelDecomp(), preserveBafflesConstraint::~preserveBafflesConstraint(), preserveFaceZonesConstraint::~preserveFaceZonesConstraint(), preservePatchesConstraint::~preservePatchesConstraint(), randomRenumber::~randomRenumber(), refinementHistoryConstraint::~refinementHistoryConstraint(), renumberMethod::~renumberMethod(), singleProcessorFaceSetsConstraint::~singleProcessorFaceSetsConstraint(), SloanRenumber::~SloanRenumber(), springRenumber::~springRenumber(), structuredDecomp::~structuredDecomp(), structuredRenumber::~structuredRenumber(), and zoltanRenumber::~zoltanRenumber().