OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
volContinuity.H File Reference
Functions
conserve internalField ()+
Variables
scalar sumLocalContErr
scalar globalContErr
Function Documentation
conserve internalField ()
Referenced by pointPatchField< Type >::addToInternalField(), anisotropicFilter::anisotropicFilter(), Foam::fvc::average(), cellCoBlended< Type >::blendingFactor(), Foam::bound(), kinematicSingleLayer::CourantNumber(), displacementComponentLaplacianFvMotionSolver::curPoints(), displacementSBRStressFvMotionSolver::curPoints(), displacementLaplacianFvMotionSolver::curPoints(), fvFieldDecomposer::decomposeField(), basicSymmetryPointPatchField< Type >::evaluate(), cyclicSlipPointPatchField< Type >::evaluate(), nonuniformTransformCyclicPointPatchField< Type >::evaluate(), wedgePointPatchField< Type >::evaluate(), symmetryPlanePointPatchField< Type >::evaluate(), fixedNormalSlipPointPatchField< Type >::evaluate(), valuePointPatchField< Type >::evaluate(), surfaceSlipDisplacementPointPatchVectorField::evaluate(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), if(), MPPICCloud< CloudType >::info(), meshToMesh0::interpolate(), GeometricField< Type, PatchField, GeoMesh >::max(), GeometricField< Type, PatchField, GeoMesh >::min(), GeometricField< Type, PatchField, GeoMesh >::negate(), cyclicFvPatchField< Type >::neighbourPatchField(), cyclicAMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::neighbourPatchField(), cyclicACMIFvPatchField< Type >::nonOverlapPatchField(), GeometricField< Type, PatchField, GeoMesh >::operator=(), pointPatchField< Type >::patchInternalField(), jumpCyclicFvPatchField< Type >::patchNeighbourField(), jumpCyclicAMIFvPatchField< Type >::patchNeighbourField(), cyclicFvPatchField< Type >::patchNeighbourField(), cyclicAMIFvPatchField< Type >::patchNeighbourField(), cyclicACMIFvPatchField< Type >::patchNeighbourField(), pointFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvVolumeField(), fvFieldReconstructor::reconstructFvVolumeInternalField(), GeometricField< Type, PatchField, GeoMesh >::replace(), pointPatchField< Type >::setInInternalField(), fvMatrix< Type >::setValuesFromList(), GeometricField< Type, PatchField, GeoMesh >::T(), valuePointPatchField< Type >::updateCoeffs(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), mappedFixedPushedInternalValueFvPatchField< Type >::updateCoeffs(), jumpCyclicFvPatchField< Type >::updateInterfaceMatrix(), jumpCyclicAMIFvPatchField< Type >::updateInterfaceMatrix(), energyRegionCoupledFvPatchScalarField::updateInterfaceMatrix(), and regionSizeDistribution::write().
Variable Documentation
scalar sumLocalContErr
Initial value:
= runTime.deltaTValue()*
        mag(conserve)().weightedAverage(mesh.V()).value()
Definition at line 9 of file volContinuity.H.
scalar globalContErr
Initial value:
= runTime.deltaTValue()*
        conserve.weightedAverage(mesh.V()).value()
Definition at line 12 of file volContinuity.H.