OpenFOAM: src/finiteVolume/cfdTools/general/include/volContinuity.H File Reference
volContinuity.H File Reference
Functions
conserve primitiveFieldRef ()+
Variables
scalar sumLocalContErr
scalar globalContErr
Function Documentation
conserve primitiveFieldRef ()
Referenced by displacementComponentLaplacianFvMotionSolver::curPoints(), displacementLaplacianFvMotionSolver::curPoints(), GeometricField< Type, PatchField, GeoMesh >::max(), GeometricField< Type, PatchField, GeoMesh >::min(), GeometricField< Type, PatchField, GeoMesh >::negate(), GeometricField< Type, PatchField, GeoMesh >::operator=(), GeometricField< Type, PatchField, GeoMesh >::replace(), fvMatrix< Type >::setValuesFromList(), and GeometricField< Type, PatchField, GeoMesh >::T().
Variable Documentation
scalar sumLocalContErr
Initial value:
= runTime.deltaTValue()*
        mag(conserve)().weightedAverage(mesh.V()).value()
Definition at line 9 of file volContinuity.H.
scalar globalContErr
Initial value:
= runTime.deltaTValue()*
        conserve.weightedAverage(mesh.V()).value()
Definition at line 12 of file volContinuity.H.