OpenFOAM: src/finiteVolume/cfdTools/incompressible/movingMeshRhoUContinuityErrs.H File Reference
movingMeshRhoUContinuityErrs.H File Reference
Calculates and prints the continuity errors for moving mesh calculation.
Functions
if (mesh.moving())
Detailed Description
Calculates and prints the continuity errors for moving mesh calculation.
Original source file movingMeshRhoUContinuityErrs.H
Definition in file movingMeshRhoUContinuityErrs.H.
Function Documentation
if (mesh. moving())
Definition at line 29 of file movingMeshRhoUContinuityErrs.H.
References cumulativeContErr, Foam::fvc::div(), Foam::endl(), globalContErr, Foam::Info, Foam::mag(), mesh, Foam::fvc::meshPhi(), phi, rho, sumLocalContErr, and U.