OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
cellLimitedGrads.C File Reference
Functions
makeFvGradScheme (cellLimitedGrad)
Detailed Description
Original source file cellLimitedGrads.C
Definition in file cellLimitedGrads.C.
Function Documentation
makeFvGradScheme (cellLimitedGrad)
Definition at line 36 of file cellLimitedGrads.C.
References C, cellLimitedGrad< Type >::calcGrad(), correctBoundaryConditions(), Foam::endl(), forAll, g, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, Foam::MULES::limiter(), Foam::max(), mesh, Foam::min(), patchi, scalarField(), and vectorField().