OpenFOAM: src/finiteVolume/finiteVolume/gradSchemes/limitedGradSchemes/faceLimitedGrad/faceLimitedGrads.C File Reference
faceLimitedGrads.C File Reference
Functions
makeFvGradScheme (faceLimitedGrad)
Detailed Description
Original source file faceLimitedGrads.C
Definition in file faceLimitedGrads.C.
Function Documentation
makeFvGradScheme (faceLimitedGrad)
Definition at line 36 of file faceLimitedGrads.C.
References C, faceLimitedGrad< Type >::calcGrad(), correctBoundaryConditions(), Foam::endl(), forAll, g, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, Foam::MULES::limiter(), Foam::max(), mesh, Foam::min(), patchi, scalarField(), and vectorField().