OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
averageMDFields.H File Reference
Functions
scalarField totalRhoN_sum (mesh.nCells(), 0.0)
forAll (allSpeciesRhoN, rN)
totalRhoN internalField ()
scalarField totalRhoM_sum (mesh.nCells(), 0.0)
forAll (allSpeciesRhoM, rM)
vectorField totalMomentum_sum (mesh.nCells(), vector::zero)
scalarField totalMass_sum (mesh.nCells(), 0.0)
forAll (allSpeciesVelocity, v)
forAll (itotalVelocity, tV)
scalarField totalTemperatureVTerms_sum (mesh.nCells(), 0.0)
scalarField totalN_sum (mesh.nCells(), 0.0)
forAll (allSpeciesTemperature, t)
forAll (itotalTemperature, tT)
scalarField totalKE_sum (mesh.nCells(), 0.0)
forAll (allSpeciesMeanKE, mKE)
forAll (itotalMeanKE, tMKE)
Variables
volVectorField::InternalField & itotalVelocity
volScalarField::InternalField & itotalTemperature
volScalarField::InternalField & itotalMeanKE = totalMeanKE.internalField()
Function Documentation
scalarField totalRhoN_sum (mesh. nCells(), 0. 0)
Referenced by forAll().
forAll (allSpeciesRhoN , rN)
Definition at line 9 of file averageMDFields.H.
References allSpeciesN_RU(), allSpeciesRhoN(), mesh, and totalRhoN_sum().
totalRhoN internalField ()
scalarField totalRhoM_sum (mesh. nCells(), 0. 0)
Referenced by forAll().
forAll (allSpeciesRhoM , rM)
Definition at line 28 of file averageMDFields.H.
References allSpeciesM_RU, allSpeciesRhoM(), mesh, and totalRhoM_sum().
vectorField totalMomentum_sum (mesh. nCells(), vector::zero)
Referenced by forAll().
scalarField totalMass_sum (mesh. nCells(), 0. 0)
Referenced by forAll().
forAll (allSpeciesVelocity , v)
Definition at line 48 of file averageMDFields.H.
References allSpeciesM_RU, allSpeciesN_RU(), allSpeciesVelocity(), allSpeciesVelocitySum_RU, forAll, internalField(), totalMass_sum(), totalMomentum_sum(), and vectorField().
forAll (itotalVelocity , tV)
Definition at line 82 of file averageMDFields.H.
References totalMass_sum(), and totalMomentum_sum().
scalarField totalTemperatureVTerms_sum (mesh. nCells(), 0. 0)
Referenced by forAll().
scalarField totalN_sum (mesh. nCells(), 0. 0)
Referenced by forAll().
forAll (allSpeciesTemperature , t)
Definition at line 102 of file averageMDFields.H.
References allSpeciesM_RU, allSpeciesN_RU(), allSpeciesTemperature(), allSpeciesVelocityMagSquaredSum_RU, allSpeciesVelocitySum_RU, forAll, internalField(), scalarField(), totalN_sum(), and totalTemperatureVTerms_sum().
forAll (itotalTemperature , tT)
Definition at line 156 of file averageMDFields.H.
References totalN_sum(), and totalTemperatureVTerms_sum().
scalarField totalKE_sum (mesh. nCells(), 0. 0)
Referenced by forAll().
forAll (allSpeciesMeanKE , mKE)
Definition at line 176 of file averageMDFields.H.
References allSpeciesM_RU, allSpeciesMeanKE(), allSpeciesN_RU(), allSpeciesVelocityMagSquaredSum_RU, forAll, internalField(), scalarField(), and totalKE_sum().
forAll (itotalMeanKE , tMKE)
Definition at line 214 of file averageMDFields.H.
References totalKE_sum(), and totalN_sum().
Variable Documentation
volVectorField::InternalField& itotalVelocity
Initial value:
=
        totalVelocity.internalField()
Definition at line 79 of file averageMDFields.H.
volScalarField::InternalField& itotalTemperature
Initial value:
=
        totalTemperature.internalField()
Definition at line 153 of file averageMDFields.H.
volScalarField::InternalField& itotalMeanKE = totalMeanKE.internalField()
Definition at line 212 of file averageMDFields.H.