OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
meanMomentumEnergyAndNMols.H File Reference
Calculates and prints the mean momentum and energy in the system and the number of molecules.
Functions
vector singleStepTotalLinearMomentum (vector::zero)
vector singleStepTotalAngularMomentum (vector::zero)
forAllConstIter (IDLList< molecule >, molecules, mol)
if (Pstream::parRun())
if (singleStepNMols)
Variables
scalar singleStepMaxVelocityMag = 0.0
scalar singleStepTotalMass = 0.0
scalar singleStepTotalLinearKE = 0.0
scalar singleStepTotalAngularKE = 0.0
scalar singleStepTotalPE = 0.0
scalar singleStepTotalrDotf = 0.0
label singleStepNMols = molecules.size()
label singleStepDOFs = 0
else
Detailed Description
Calculates and prints the mean momentum and energy in the system and the number of molecules.
Original source file meanMomentumEnergyAndNMols.H
Definition in file meanMomentumEnergyAndNMols.H.
Function Documentation
vector singleStepTotalLinearMomentum (vector::zero)
Referenced by if().
vector singleStepTotalAngularMomentum (vector::zero)
Referenced by if().
forAllConstIter (IDLList< molecule > , molecules , mol)
Definition at line 54 of file meanMomentumEnergyAndNMols.H.
References singleStepTotalMass.
if (Pstream:: parRun())
Definition at line 108 of file meanMomentumEnergyAndNMols.H.
References Foam::reduce(), singleStepMaxVelocityMag, singleStepNMols, singleStepTotalAngularKE, singleStepTotalAngularMomentum(), singleStepTotalLinearKE, singleStepTotalLinearMomentum(), singleStepTotalMass, singleStepTotalPE, and singleStepTotalrDotf.
if (singleStepNMols)
Definition at line 131 of file meanMomentumEnergyAndNMols.H.
References Foam::endl(), Foam::Info, Foam::mag(), meshVolume, Foam::nl, singleStepMaxVelocityMag, singleStepNMols, singleStepTotalAngularKE, singleStepTotalAngularMomentum(), singleStepTotalLinearKE, singleStepTotalLinearMomentum(), singleStepTotalMass, and singleStepTotalPE.
Variable Documentation
scalar singleStepMaxVelocityMag = 0.0
Definition at line 35 of file meanMomentumEnergyAndNMols.H.
Referenced by if().
scalar singleStepTotalMass = 0.0
Definition at line 37 of file meanMomentumEnergyAndNMols.H.
Referenced by forAllConstIter(), and if().
scalar singleStepTotalLinearKE = 0.0
Definition at line 39 of file meanMomentumEnergyAndNMols.H.
Referenced by if().
scalar singleStepTotalAngularKE = 0.0
Definition at line 41 of file meanMomentumEnergyAndNMols.H.
Referenced by if().
scalar singleStepTotalPE = 0.0
Definition at line 43 of file meanMomentumEnergyAndNMols.H.
Referenced by if().
scalar singleStepTotalrDotf = 0.0
Definition at line 45 of file meanMomentumEnergyAndNMols.H.
Referenced by if().
label singleStepNMols = molecules.size()
Definition at line 49 of file meanMomentumEnergyAndNMols.H.
Referenced by if().
label singleStepDOFs = 0
Definition at line 51 of file meanMomentumEnergyAndNMols.H.
else
Initial value:
{
    Info<< "No molecules in system" << endl
Definition at line 172 of file meanMomentumEnergyAndNMols.H.