OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createRefUnits.H File Reference
Functions
IOobject reducedUnitsDictIOobject ("reducedUnitsDict", runTime.system(), mesh, IOobject::READ_IF_PRESENT, IOobject::NO_WRITE)
if (reducedUnitsDictIOobject.headerOk())
Variables
reducedUnits refUnits
Function Documentation
IOobject reducedUnitsDictIOobject ("reducedUnitsDict" , runTime. system(), mesh , IOobject::READ_IF_PRESENT , IOobject::NO_WRITE)
Referenced by if().
if (reducedUnitsDictIOobject. headerOk())
Definition at line 12 of file createRefUnits.H.
References Foam::endl(), Foam::Info, Foam::nl, reducedUnitsDictIOobject(), and refUnits.
Variable Documentation
reducedUnits refUnits
Definition at line 1 of file createRefUnits.H.
Referenced by if().