OpenFOAM: src/lagrangian/molecularDynamics/molecule/mdTools/createAutoCorrelationFunctions.H File Reference
createAutoCorrelationFunctions.H File Reference
Functions
Info<< nl<< "Creating autocorrelation functions."<< endl;IOdictionary mdTransportProperitesDict(IOobject("mdTransportProperitesDict", mesh.time().system(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, false));const dictionary &autocorrelationFunctionDict(mdTransportProperitesDict.subDict("autocorrelationFunctions"));Info<< tab<< "velocty"<< endl;const dictionary &velocityACFDict(autocorrelationFunctionDict.subDict("velocity"));correlationFunction< vector > vacf (mesh, velocityACFDict, molecules.size())
bool writeVacf (Switch(velocityACFDict.lookup("writeFile")))
Info<< tab<< "pressure"<< endl;const dictionary &pressureACFDict(autocorrelationFunctionDict.subDict("pressure"));correlationFunction< vector > pacf (mesh, pressureACFDict, 1)
Pressure autocorrelation function.
bool writePacf (Switch(pressureACFDict.lookup("writeFile")))
Info<< tab<< "heat flux"<< endl;const dictionary &heatFluxACFDict(autocorrelationFunctionDict.subDict("heatFlux"));correlationFunction< vector > hfacf (mesh, heatFluxACFDict, 1)
Heat flux autocorrelation function.
bool writeHFacf (Switch(heatFluxACFDict.lookup("writeFile")))
Detailed Description
Original source file createAutoCorrelationFunctions.H
Definition in file createAutoCorrelationFunctions.H.
Function Documentation
vacf()
Info<< nl << "Creating autocorrelation functions." << endl;IOdictionary mdTransportProperitesDict(IOobject ("mdTransportProperitesDict", mesh.time().system(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, false));const dictionary& autocorrelationFunctionDict(mdTransportProperitesDict.subDict("autocorrelationFunctions"));Info << tab << "velocty" << endl;const dictionary& velocityACFDict(autocorrelationFunctionDict.subDict("velocity"));correlationFunction<vector> vacf (mesh , velocityACFDict , molecules. size())
Referenced by if().
writeVacf()
bool writeVacf (Switch(velocityACFDict.lookup("writeFile")))
pacf()
Info<< tab << "pressure" << endl;const dictionary& pressureACFDict(autocorrelationFunctionDict.subDict("pressure"));correlationFunction<vector> pacf (mesh , pressureACFDict , 1)
Pressure autocorrelation function.
Referenced by if().
writePacf()
bool writePacf (Switch(pressureACFDict.lookup("writeFile")))
Referenced by if().
hfacf()
Info<< tab << "heat flux" << endl;const dictionary& heatFluxACFDict(autocorrelationFunctionDict.subDict("heatFlux"));correlationFunction<vector> hfacf (mesh , heatFluxACFDict , 1)
Heat flux autocorrelation function.
Referenced by if().
writeHFacf()
bool writeHFacf (Switch(heatFluxACFDict.lookup("writeFile")))
Referenced by if().