OpenFOAM: src/lagrangian/molecularDynamics/molecule/mdTools/calculateAutoCorrelationFunctions.H File Reference
calculateAutoCorrelationFunctions.H File Reference
Functions
if (mesh.time().timeIndex() % vacf.sampleSteps()==0)
if (mesh.time().timeIndex() % pacf.sampleSteps()==0)
if (mesh.time().timeIndex() % hfacf.sampleSteps()==0)
Detailed Description
Original source file calculateAutoCorrelationFunctions.H
Definition in file calculateAutoCorrelationFunctions.H.
Function Documentation
if() [1/3]
if (mesh. time).timeIndex() % vacf.sampleSteps(= = 0)
Definition at line 26 of file calculateAutoCorrelationFunctions.H.
References forAllConstIter(), and vacf().
if() [2/3]
if (mesh. time).timeIndex() % pacf.sampleSteps(= = 0)
Definition at line 40 of file calculateAutoCorrelationFunctions.H.
References forAllConstIter(), p, pacf(), and Foam::Zero.
if() [3/3]
if (mesh. time).timeIndex() % hfacf.sampleSteps(= = 0)
Definition at line 62 of file calculateAutoCorrelationFunctions.H.
References forAllConstIter(), hfacf(), Foam::magSqr(), s(), U, and Foam::Zero.