OpenFOAM-dev: src/lagrangian/spray/submodels/AtomizationModel/LISAAtomization/LISASMDCalcMethod2.H File Reference 2
LISASMDCalcMethod2.H File Reference
Functions
if (maxValue-minValue< SMALL)
forAll (rrd, n)
while (!success &&(k< 500))
Variables
scalar delta = dD/factorGamma
scalar minValue = dD/10.0
scalar maxValue = dD
scalar range = maxValue - minValue
scalar nExp = 3
FixedList< scalar, 500 > rrd
scalar probFactorMin = exp(-pow(minValue/delta, nExp))
scalar probFactorMax = exp(-pow(maxValue/delta, nExp))
scalar probFactor = 1.0/(probFactorMin - probFactorMax)
bool success = false
scalar y = rndGen.sample01<scalar>()
label k = 0
Boltzmann constant.
x = minValue + range*(k - 0.5)/500.0
Function Documentation
if ()
Definition at line 18 of file LISASMDCalcMethod2.H.
forAll (rrd , n)
Definition at line 31 of file LISASMDCalcMethod2.H.
References Foam::exp(), n, and Foam::pow().
while (!success && k< 500)
Definition at line 43 of file LISASMDCalcMethod2.H.
Variable Documentation
scalar delta = dD/factorGamma
Definition at line 8 of file LISASMDCalcMethod2.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), dynamicKEqn< BasicTurbulenceModel >::Ce(), dynamicKEqn< BasicTurbulenceModel >::Ck(), patchInjection::correct(), drippingInjection::correct(), curvatureSeparation::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), standardPhaseChange::correctModel(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), kEqn< BasicTurbulenceModel >::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), DeardorffDiffStress< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), NicenoKEqn< BasicTurbulenceModel >::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), SpalartAllmarasDDES< BasicTurbulenceModel >::dTilda(), SpalartAllmarasIDDES< BasicTurbulenceModel >::dTilda(), SpalartAllmarasDES< BasicTurbulenceModel >::dTilda(), Foam::eigenValues(), LESeddyViscosity< BasicTurbulenceModel >::epsilon(), kEqn< BasicTurbulenceModel >::epsilon(), DeardorffDiffStress< BasicTurbulenceModel >::epsilon(), WALE< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), dynamicKEqn< BasicTurbulenceModel >::epsilon(), kOmegaSSTDES< BasicTurbulenceModel >::FDES(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), chemistryModel< CompType, ThermoType >::jacobian(), WALE< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), surfaceInterpolation::movePoints(), continuousGasKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), NicenoKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), standardRadiation::Shs(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), laminar::Su(), LISAAtomization< CloudType >::update(), reactingOneDim::updateQr(), histogram::write(), regionSizeDistribution::write(), and FSD< CombThermoType, ThermoType >::~FSD().
scalar minValue = dD/10.0
Definition at line 12 of file LISASMDCalcMethod2.H.
Referenced by distributionModel::check(), InflationInjection< CloudType >::parcelsToInject(), and fixedValue::~fixedValue().
scalar maxValue = dD
Definition at line 13 of file LISASMDCalcMethod2.H.
scalar range = maxValue - minValue
Definition at line 23 of file LISASMDCalcMethod2.H.
scalar nExp = 3
Definition at line 25 of file LISASMDCalcMethod2.H.
Referenced by while().
FixedList<scalar, 500> rrd
Definition at line 26 of file LISASMDCalcMethod2.H.
scalar probFactorMin = exp(-pow(minValue/delta, nExp))
Definition at line 27 of file LISASMDCalcMethod2.H.
scalar probFactorMax = exp(-pow(maxValue/delta, nExp))
Definition at line 28 of file LISASMDCalcMethod2.H.
scalar probFactor = 1.0/(probFactorMin - probFactorMax)
Definition at line 29 of file LISASMDCalcMethod2.H.
bool success = false
Definition at line 38 of file LISASMDCalcMethod2.H.
scalar y = rndGen.sample01<scalar>()
Definition at line 40 of file LISASMDCalcMethod2.H.
label k = 0
Boltzmann constant.
Definition at line 41 of file LISASMDCalcMethod2.H.
Referenced by atmBoundaryLayerInletKFvPatchScalarField::atmBoundaryLayerInletKFvPatchScalarField(), nutkWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), addPatchCellLayer::calcSidePatch(), epsilonLowReWallFunctionFvPatchScalarField::calculate(), viewFactor::calculate(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), block::clone(), CompactListList< T, Container >::CompactListList(), MixedDiffuseSpecular< CloudType >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), radiativeIntensityRay::correct(), trackedParticle::correctAfterParallelTransfer(), WALE< BasicTurbulenceModel >::correctNut(), DeardorffDiffStress< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), LLTMatrix< Type >::decompose(), QRMatrix< MatrixType >::decompose(), dmat_uniform(), dtris2(), pairPotential::energy(), pairPotential::energyTable(), LESeddyViscosity< BasicTurbulenceModel >::epsilon(), DeardorffDiffStress< BasicTurbulenceModel >::epsilon(), kEqn< BasicTurbulenceModel >::epsilon(), WALE< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), dynamicKEqn< BasicTurbulenceModel >::epsilon(), normal::erfInv(), pairPotential::force(), pairPotential::forceTable(), general::general(), if(), distribution::insertMissingKeys(), jenkins_hashbig(), jenkins_hashlittle(), Distribution< Type >::keys(), Foam::LUDecompose(), Matrix< Form, Type >::Matrix(), distribution::mean(), Distribution< Type >::mean(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), distribution::normalised(), Distribution< Type >::normalised(), turbulenceFields::omega(), Foam::operator&(), triad::operator+=(), Foam::operator/(), points_delaunay_naive_2d(), Foam::printTable(), eddyViscosity< BasicTurbulenceModel >::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), distribution::raw(), Distribution< Type >::raw(), general::sample(), pairPotential::setLookupTables(), seulex::seulex(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), Foam::solve(), SIBS::solve(), seulex::solve(), extendedEdgeMesh::sortPointsAndEdges(), SVD::SVD(), triangulation_plot_eps(), triangulation_print(), StochasticDispersionRAS< CloudType >::update(), GradientDispersionRAS< CloudType >::update(), LISAAtomization< CloudType >::update(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), reactingOneDim::updatePhiGas(), reactingOneDim::updateQr(), and nutkWallFunctionFvPatchScalarField::yPlus().
x = minValue + range*(k - 0.5)/500.0
Definition at line 52 of file LISASMDCalcMethod2.H.
Referenced by targetCoeffTrim::calcCoeffs(), treeBoundBox::calcExtremities(), cellLimitedGrad< Type >::calcGrad(), Stochastic< CloudType >::calculate(), Polynomial< Type >::clone(), Function1< Foam::Vector >::clone(), rotorDiskSource::constructGeometry(), treeBoundBox::corner(), d_max(), d_min(), QRMatrix< MatrixType >::decompose(), Polynomial< PolySize >::derivative(), normal::erfInv(), quaternion::eulerAngles(), rigidBodyModel::forwardDynamics(), Foam::interpolateXY(), QRMatrix< MatrixType >::inv(), DiagonalMatrix< Type >::invert(), Foam::kShellIntegration(), Foam::kShellMean(), multiNormal::multiNormal(), cellToFaceStencil::unionEqOp::operator()(), cellToCellStencil::unionEqOp::operator()(), accessOp< T >::operator()(), combineReduceFileStates::operator()(), AveragingMethod< Type >::operator*=(), AveragingMethod< Type >::operator+=(), AveragingMethod< Type >::operator/=(), AveragingMethod< Type >::operator=(), InflationInjection< CloudType >::parcelsToInject(), Foam::parseNASCoord(), searchableCylinder::points(), quaternion::R(), fixedTrim::read(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJedgeFormat::read(), OFFsurfaceFormat< Face >::read(), STARCD::readPoints(), STARCDCore::readPoints(), general::sample(), RosinRammler::sample(), multiNormal::sample(), normal::sample(), ODESolver::solve(), SVD::SVD(), swapec(), targetCoeffTrim::thetag(), CV2D::toPoint2D(), STARCDCoordinateRotation::transformVector(), pointConstraint::unconstrainedDirections(), azizChen::unscaledEnergy(), LISAAtomization< CloudType >::update(), SHF< CloudType >::update(), ReactingLookupTableInjection< CloudType >::updateMesh(), ThermoLookupTableInjection< CloudType >::updateMesh(), ReactingMultiphaseLookupTableInjection< CloudType >::updateMesh(), KinematicLookupTableInjection< CloudType >::updateMesh(), USERD_get_part_coords(), Polynomial< PolySize >::value(), polynomialFunction::value(), Relaxation< CloudType >::velocityCorrection(), block::vtxLabel(), while(), histogram::write(), regionSizeDistribution::write(), dxSurfaceWriter::writeData(), adaptiveSolver::~adaptiveSolver(), ODESystem::~ODESystem(), RaviPetersen::~RaviPetersen(), and Stochastic< CloudType >::~Stochastic().