OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
setConstantMeshDictionaryIO.H File Reference
Functions
if (args.optionFound("dict"))
IOobject dictIO (dictName, runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)
if (dictPath.size())
Variables
fileName dictPath = ""
Function Documentation
if (args. optionFound"dict")
Definition at line 6 of file setConstantMeshDictionaryIO.H.
References args, dictName(), dictPath, and Foam::isDir().
IOobject dictIO (dictName , runTime. constant(), mesh , IOobject::MUST_READ_IF_MODIFIED , IOobject::NO_WRITE)
Referenced by if(), and writeDictionary::tryDirectory().
if (dictPath. size())
Definition at line 24 of file setConstantMeshDictionaryIO.H.
References dictIO(), dictPath, and mesh.
Variable Documentation
fileName dictPath = ""
Definition at line 5 of file setConstantMeshDictionaryIO.H.
Referenced by if().