OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
createIncompressibleRadiationModel.H File Reference
Functions
autoPtr
< radiation::radiationModel > radiation (radiation::radiationModel::New(T))
dimensionedScalar rhoCpRef ("rhoCpRef", dimDensity *dimEnergy/dimMass/dimTemperature, 1.0)
IOdictionary transportProperties (IOobject("transportProperties", runTime.constant(), runTime, IOobject::MUST_READ, IOobject::NO_WRITE, false))
dimensionedScalar rhoRef (transportProperties.lookup("rhoRef"))
dimensionedScalar CpRef (transportProperties.lookup("CpRef"))
Variables
rhoCpRef = rhoRef*CpRef
Function Documentation
autoPtr<radiation::radiationModel> radiation (radiation::radiationModel:: NewT)
dimensionedScalar rhoCpRef ("rhoCpRef" , dimDensity *dimEnergy/dimMass/ dimTemperature, 1. 0)
IOdictionary transportProperties (IOobject("transportProperties", runTime.constant(), runTime, IOobject::MUST_READ, IOobject::NO_WRITE, false))
Referenced by forces::devRhoReff(), forAll(), forces::mu(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
dimensionedScalar rhoRef (transportProperties. lookup"rhoRef")
Referenced by fixedCoeff::calcForce(), and targetCoeffTrim::correctTrim().
dimensionedScalar CpRef (transportProperties. lookup"CpRef")
Variable Documentation
rhoCpRef = rhoRef*CpRef
Definition at line 31 of file createIncompressibleRadiationModel.H.