OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::fvc Namespace Reference
Namespace of functions to calculate explicit derivatives.
Functions
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
Area-weighted average a surfaceField creating a volField.
template<class Type , class CombineOp >
tmp< GeometricField< Type,
fvPatchField, volMesh > > cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf, const CombineOp &cop)
template<class Type , class CombineOp >
tmp< GeometricField< Type,
fvPatchField, volMesh > > cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > & > tssf, const CombineOp &cop)
template<class Type , class CombineOp >
tmp< GeometricField< Type,
fvPatchField, volMesh > > cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &, const CombineOp &cop)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > d2dt2 (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh &mesh)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > ddt (const dimensionedScalar &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > ddt (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > ddt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > ddt (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf, const one &)
template<class Type >
tmp< GeometricField< typename
flux< Type >::type,
fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename
flux< Type >::type,
fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename
flux< Type >::type,
fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename
flux< Type >::type,
fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > DDt (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &psi)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > &tphi, const GeometricField< Type, fvPatchField, volMesh > &psi)
geometricZeroField ddt (const one &, const one &)
template<class Type >
tmp< GeometricField< typename
Foam::flux< Type >::type,
fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename
Foam::flux< Type >::type,
fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename
Foam::flux< Type >::type,
fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename
Foam::flux< Type >::type,
fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvPatchField, volMesh >> div (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvPatchField, volMesh >> div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvvf, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvPatchField, volMesh >> div (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvPatchField, volMesh >> div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvvf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &tphi, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &phi, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &tphi, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &phi, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type , class GType >
tmp< GeometricField< Type,
fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
tmp< surfaceScalarField > meshPhi (const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const dimensionedScalar &rho, const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const volScalarField &rho, const volVectorField &U)
void makeRelative (surfaceScalarField &phi, const volVectorField &U)
Make the given flux relative.
void makeRelative (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
Make the given flux relative.
void makeRelative (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
Make the given flux relative.
void makeAbsolute (surfaceScalarField &phi, const volVectorField &U)
Make the given flux absolute.
void makeAbsolute (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
Make the given flux absolute.
void makeAbsolute (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
Make the given flux absolute.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
Return the given absolute flux in relative form.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
Return the given absolute flux in relative form.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
Return the given relative flux in absolute form.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
Return the given relative flux in absolute form.
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh >> reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh >> reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
tmp< volScalarField > reconstructMag (const surfaceScalarField &)
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > &)
void smooth (volScalarField &field, const scalar coeff)
void spread (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2, const scalar alphaMax=0.99, const scalar alphaMin=0.01)
void sweep (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > &su, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tsu, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > Sp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > Sp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > Sp (const dimensionedScalar &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > SuSp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > SuSp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
void surfaceIntegrate (Field< Type > &ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &tssf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh > > &tdf)
template<class Type >
dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
template<class Type >
dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh > > &tdf)
template<class Type >
tmp
< surfaceInterpolationScheme
< Type > > scheme (const surfaceScalarField &faceFlux, Istream &streamData)
template<class Type >
tmp
< surfaceInterpolationScheme
< Type > > scheme (const surfaceScalarField &faceFlux, const word &name)
template<class Type >
tmp
< surfaceInterpolationScheme
< Type > > scheme (const fvMesh &mesh, Istream &streamData)
Return weighting factors for scheme given from Istream.
template<class Type >
tmp
< surfaceInterpolationScheme
< Type > > scheme (const fvMesh &mesh, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const surfaceScalarField &faceFlux, Istream &schemeData)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const surfaceScalarField &faceFlux, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const surfaceScalarField &faceFlux, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tFaceFlux, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const tmp< surfaceScalarField > &tFaceFlux, const word &name)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf)
Interpolate field onto faces using 'interpolate(<name>)'.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
Interpolate tmp field onto faces using 'interpolate(<name>)'.
template<class Type >
tmp< FieldField< fvsPatchField,
Type > > interpolate (const FieldField< fvPatchField, Type > &fvpff)
Interpolate boundary field onto faces (simply a type conversion)
template<class Type >
tmp< FieldField< fvsPatchField,
Type > > interpolate (const tmp< FieldField< fvPatchField, Type > > &tfvpff)
Interpolate boundary field onto faces (simply a type conversion)
template<class Type >
static tmp
< surfaceInterpolationScheme
< Type > > scheme (const surfaceScalarField &faceFlux, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp
< surfaceInterpolationScheme
< Type > > scheme (const surfaceScalarField &faceFlux, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp
< surfaceInterpolationScheme
< Type > > scheme (const fvMesh &mesh, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp
< surfaceInterpolationScheme
< Type > > scheme (const fvMesh &mesh, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const surfaceScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > &tvf)
Interpolate tmp field onto faces using 'interpolate(<name>)'.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf)
Interpolate field onto faces using 'interpolate(<name>)'.
template<class Type >
static tmp< FieldField
< fvsPatchField, Type > > interpolate (const FieldField< fvPatchField, Type > &fvpff)
Interpolate boundary field onto faces (simply a type conversion)
template<class Type >
static tmp< FieldField
< fvsPatchField, Type > > interpolate (const tmp< FieldField< fvPatchField, Type > > &tfvpff)
Interpolate boundary field onto faces (simply a type conversion)
one interpolate (const one &)
Interpolate 'one' returning 'one'.
Detailed Description
Namespace of functions to calculate explicit derivatives.
Function Documentation
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Area-weighted average a surfaceField creating a volField.
Definition at line 46 of file fvcAverage.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), internalField(), GeometricField< Type, PatchField, GeoMesh >::internalField(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, and surfaceSum().
Referenced by average(), Dual< Type >::average(), Foam::bound(), if(), and PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints().
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Area-weighted average a surfaceField creating a volField.
Definition at line 93 of file fvcAverage.C.
References average().
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > & vtf)
Area-weighted average a surfaceField creating a volField.
Definition at line 109 of file fvcAverage.C.
References average(), and Foam::linearInterpolate().
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvtf)
Area-weighted average a surfaceField creating a volField.
Definition at line 120 of file fvcAverage.C.
References average().
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf, const CombineOp & cop)
Definition at line 46 of file fvcCellReduce.C.
References DimensionedField< Type, GeoMesh >::dimensions(), forAll, i, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, and fvMesh::owner().
Referenced by cellReduce().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > & > tssf, const CombineOp & cop)
Definition at line 97 of file fvcCellReduce.C.
References cellReduce().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & , const CombineOp & cop)
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcCurl.C.
References grad(), IOobject::name(), and Foam::skew().
Referenced by LiftForce< CloudType >::cacheFields(), curl(), and vorticity::execute().
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 68 of file fvcCurl.C.
References curl().
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 60 of file fvcD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh & mesh)
Definition at line 45 of file fvcDdt.C.
References fvSchemes::ddtScheme(), dimensioned< Type >::name(), and ddtScheme< Type >::New().
Referenced by PressureGradientForce< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), Foam::CorrectPhi(), DDt(), ddt(), for(), forAll(), forAllConstIter(), boundedDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvmDdt(), if(), and Foam::MULES::implicitSolve().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 61 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 76 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 92 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 108 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 131 of file fvcDdt.C.
References ddt().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf, const one &)
Definition at line 143 of file fvcDdt.C.
References ddt().
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 155 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
Referenced by CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), and CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr().
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 171 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 192 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 209 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 45 of file fvcDDt.C.
References ddt(), div(), DimensionedField< Type, GeoMesh >::mesh(), and psi.
Referenced by DDt().
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 67 of file fvcDDt.C.
References tmp< T >::clear(), and DDt().
geometricZeroField Foam::fvc::ddt (const one & , const one &) inline
Definition at line 106 of file fvcDdt.H.
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 155 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
Referenced by CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), and CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr().
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 171 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 192 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 209 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 47 of file fvcDiv.C.
References IOobject::name(), and surfaceIntegrate().
Referenced by Implicit< CloudType >::cacheFields(), kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< BasicTurbulenceModel >::correct(), Foam::CorrectPhi(), DDt(), div(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), nonlinearEddyViscosity< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), for(), forAllConstIter(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), Foam::MULES::implicitSolve(), displacementSBRStressFvMotionSolver::solve(), reactingOneDim::solveContinuity(), kinematicSingleLayer::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), reactingOneDim::solveSpeciesMass(), and div::writeDivField().
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 65 of file fvcDiv.C.
References div().
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 84 of file fvcDiv.C.
References DimensionedField< Type, GeoMesh >::mesh(), and divScheme< Type >::New().
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvvf, const word & name)
Definition at line 105 of file fvcDiv.C.
References div().
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 128 of file fvcDiv.C.
References div(), and IOobject::name().
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvvf)
Definition at line 145 of file fvcDiv.C.
References div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 159 of file fvcDiv.C.
References flux(), DimensionedField< Type, GeoMesh >::mesh(), and convectionScheme< Type >::New().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 177 of file fvcDiv.C.
References tmp< T >::clear(), and div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 195 of file fvcDiv.C.
References div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 213 of file fvcDiv.C.
References tmp< T >::clear(), and div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 232 of file fvcDiv.C.
References div(), and IOobject::name().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 247 of file fvcDiv.C.
References tmp< T >::clear(), and div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 264 of file fvcDiv.C.
References div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 281 of file fvcDiv.C.
References tmp< T >::clear(), and div().
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & , const word & name)
Definition at line 84 of file fvcDiv.C.
References DimensionedField< Type, GeoMesh >::mesh(), and divScheme< Type >::New().
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh > > & , const word & name)
Definition at line 105 of file fvcDiv.C.
References div().
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 128 of file fvcDiv.C.
References div(), and IOobject::name().
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
Definition at line 145 of file fvcDiv.C.
References div().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcFlux.C.
References DimensionedField< Type, GeoMesh >::mesh(), convectionScheme< Type >::New(), and phi.
Referenced by Foam::fvm::div(), div(), flux(), for(), gaussConvectionScheme< Type >::fvcDiv(), and Foam::MULES::limit().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 63 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 81 of file fvcFlux.C.
References flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 99 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 118 of file fvcFlux.C.
References flux(), and IOobject::name().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 133 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 150 of file fvcFlux.C.
References flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 167 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
tmp< GeometricField < typename outerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 52 of file fvcGrad.C.
References gaussGrad< Type >::gradf(), and IOobject::name().
Referenced by GradientDispersionRAS< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), dynamicKEqn< BasicTurbulenceModel >::Ce(), thermocapillaryForce::correct(), diffusion< CombThermoType, ThermoType >::correct(), contactAngleForce::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), Poisson::correct(), LamBremhorstKE::correct(), ShihQuadraticKE::correct(), LienLeschziner::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< BasicTurbulenceModel >::correct(), cubic< Type >::correction(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), ShihQuadraticKE::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), realizableKE< BasicTurbulenceModel >::correctNut(), LienCubicKE::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), kOmegaSST< BasicTurbulenceModel >::correctNut(), curl(), linearViscousStress< BasicTurbulenceModel >::devRhoReff(), ReynoldsStress< BasicTurbulenceModel >::devRhoReff(), forces::devRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), WALE< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), Lambda2::execute(), Q::execute(), correctedSnGrad< Type >::fullGradCorrection(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), grad(), if(), dynamicLagrangian< BasicTurbulenceModel >::k(), WALE< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), magSqrGradGrad(), ParticleTrap< CloudType >::preEvolve(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), eddyViscosity< BasicTurbulenceModel >::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), skewCorrected< Type >::skewCorrection(), displacementSBRStressFvMotionSolver::solve(), SpalartAllmaras< BasicTurbulenceModel >::Stilda(), viscosityModel::strainRate(), and magGrad::writeMagGradField().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 69 of file fvcGrad.C.
References grad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 92 of file fvcGrad.C.
References DimensionedField< Type, GeoMesh >::mesh(), and gradScheme< Type >::New().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 114 of file fvcGrad.C.
References grad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 143 of file fvcGrad.C.
References grad(), and IOobject::name().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 160 of file fvcGrad.C.
References grad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Definition at line 52 of file fvcGrad.C.
References gaussGrad< Type >::gradf(), and IOobject::name().
Referenced by GradientDispersionRAS< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), dynamicKEqn< BasicTurbulenceModel >::Ce(), thermocapillaryForce::correct(), diffusion< CombThermoType, ThermoType >::correct(), contactAngleForce::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), Poisson::correct(), LamBremhorstKE::correct(), ShihQuadraticKE::correct(), LienLeschziner::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< BasicTurbulenceModel >::correct(), cubic< Type >::correction(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), ShihQuadraticKE::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), realizableKE< BasicTurbulenceModel >::correctNut(), LienCubicKE::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), kOmegaSST< BasicTurbulenceModel >::correctNut(), curl(), linearViscousStress< BasicTurbulenceModel >::devRhoReff(), ReynoldsStress< BasicTurbulenceModel >::devRhoReff(), forces::devRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), WALE< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), Lambda2::execute(), Q::execute(), correctedSnGrad< Type >::fullGradCorrection(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), grad(), if(), dynamicLagrangian< BasicTurbulenceModel >::k(), WALE< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), magSqrGradGrad(), ParticleTrap< CloudType >::preEvolve(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), eddyViscosity< BasicTurbulenceModel >::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), skewCorrected< Type >::skewCorrection(), displacementSBRStressFvMotionSolver::solve(), SpalartAllmaras< BasicTurbulenceModel >::Stilda(), viscosityModel::strainRate(), and magGrad::writeMagGradField().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
Definition at line 69 of file fvcGrad.C.
References grad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & , const word & name)
Definition at line 92 of file fvcGrad.C.
References DimensionedField< Type, GeoMesh >::mesh(), and gradScheme< Type >::New().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & , const word & name)
Definition at line 114 of file fvcGrad.C.
References grad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 143 of file fvcGrad.C.
References grad(), and IOobject::name().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh > > &)
Definition at line 160 of file fvcGrad.C.
References grad().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcLaplacian.C.
References DimensionedField< Type, GeoMesh >::mesh(), and laplacianScheme< Type, GType >::New().
Referenced by Implicit< CloudType >::cacheFields(), Foam::CorrectPhi(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), for(), forAll(), laplacian(), laplaceFilter::operator()(), kinematicSingleLayer::pu(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), and reactingOneDim::solveEnergy().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 61 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 89 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 107 of file fvcLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 133 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 151 of file fvcLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 176 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 195 of file fvcLaplacian.C.
References DimensionedField< Type, GeoMesh >::mesh(), and laplacianScheme< Type, GType >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 212 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 230 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 248 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 267 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 284 of file fvcLaplacian.C.
References laplacian(), Foam::name(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 301 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 318 of file fvcLaplacian.C.
References laplacian(), and Foam::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 337 of file fvcLaplacian.C.
References DimensionedField< Type, GeoMesh >::mesh(), and laplacianScheme< Type, GType >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 354 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 372 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 389 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 408 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 425 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 442 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh > > & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 458 of file fvcLaplacian.C.
References laplacian().
tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 44 of file fvcMagSqrGradGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::component(), grad(), and Foam::magSqr().
Referenced by LaunderSharmaKE< BasicTurbulenceModel >::correct(), qZeta::correct(), and magSqrGradGrad().
tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 66 of file fvcMagSqrGradGrad.C.
References magSqrGradGrad().
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volVectorField & U)
Definition at line 33 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), and IOobject::name().
Referenced by meshPhi(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), and movingWallVelocityFvPatchVectorField::updateCoeffs().
Foam::tmp< Foam::surfaceScalarField > meshPhi (const dimensionedScalar & rho, const volVectorField & U)
Definition at line 46 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), meshPhi(), dimensioned< Type >::name(), and IOobject::name().
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volScalarField & rho, const volVectorField & U)
Definition at line 60 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), meshPhi(), and IOobject::name().
void Foam::fvc::makeRelative (surfaceScalarField & phi, const volVectorField & U)
Make the given flux relative.
Referenced by Foam::CorrectPhi().
void Foam::fvc::makeRelative (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Make the given flux relative.
void Foam::fvc::makeRelative (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Make the given flux relative.
void Foam::fvc::makeAbsolute (surfaceScalarField & phi, const volVectorField & U)
Make the given flux absolute.
Referenced by Foam::CorrectPhi().
void Foam::fvc::makeAbsolute (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Make the given flux absolute.
void Foam::fvc::makeAbsolute (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Make the given flux absolute.
tmp<surfaceScalarField> Foam::fvc::relative (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Return the given absolute flux in relative form.
Referenced by pimpleControl::criteriaSatisfied().
tmp<surfaceScalarField> Foam::fvc::relative (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Return the given absolute flux in relative form.
tmp<surfaceScalarField> Foam::fvc::absolute (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Return the given relative flux in absolute form.
Referenced by kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), and kOmegaSST< BasicTurbulenceModel >::correct().
tmp<surfaceScalarField> Foam::fvc::absolute (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Return the given relative flux in absolute form.
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 54 of file fvcReconstruct.C.
References IOobject::instance(), Foam::inv(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::Sf(), SfHat(), and surfaceSum().
Referenced by Implicit< CloudType >::cacheFields(), for(), if(), reconstruct(), kinematicSingleLayer::solveMomentum(), and kinematicSingleLayer::solveThickness().
tmp< GeometricField < typename outerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 96 of file fvcReconstruct.C.
References reconstruct().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Definition at line 54 of file fvcReconstruct.C.
References IOobject::instance(), Foam::inv(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::Sf(), SfHat(), and surfaceSum().
Referenced by Implicit< CloudType >::cacheFields(), for(), if(), reconstruct(), kinematicSingleLayer::solveMomentum(), and kinematicSingleLayer::solveThickness().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > &)
Definition at line 96 of file fvcReconstruct.C.
References reconstruct().
tmp< volScalarField > reconstructMag (const surfaceScalarField & ssf)
Definition at line 44 of file fvcReconstructMag.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvMesh::Cf(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), patchi, fvMesh::Sf(), and fvMesh::V().
Referenced by reconstructMag().
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > & tssf)
Definition at line 118 of file fvcReconstructMag.C.
References tmp< T >::clear(), and reconstructMag().
void smooth (volScalarField & field, const scalar coeff)
Definition at line 35 of file fvcSmooth.C.
References List< T >::append(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), polyMesh::faceOwner(), forAll, polyMesh::globalData(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), globalMeshData::nTotalCells(), fvMesh::owner(), patchi, and polyPatch::start().
Referenced by GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), and nonBlockingGaussSeidelSmoother::smooth().
void spread (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2, const scalar alphaMax = 0.99, const scalar alphaMin = 0.01)
Definition at line 124 of file fvcSmooth.C.
References List< T >::append(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), polyMesh::faceOwner(), forAll, FaceCellWave< Type, TrackingData >::iterate(), Foam::mag(), Foam::max(), smoothData::trackData::maxRatio, mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), fvMesh::owner(), patchi, FaceCellWave< Type, TrackingData >::setFaceInfo(), and polyPatch::start().
void sweep (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2)
Definition at line 222 of file fvcSmooth.C.
References List< T >::append(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), FaceCellWave< Type, TrackingData >::data(), primitiveMesh::faceCentres(), polyMesh::faceOwner(), forAll, FaceCellWave< Type, TrackingData >::iterate(), Foam::mag(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), fvMesh::owner(), patchi, FaceCellWave< Type, TrackingData >::setFaceInfo(), polyPatch::start(), and value().
Referenced by GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), DILUSmoother::smooth(), DICSmoother::smooth(), FDICSmoother::smooth(), and nonBlockingGaussSeidelSmoother::smooth().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcSnGrad.C.
References DimensionedField< Type, GeoMesh >::mesh(), and snGradScheme< Type >::New().
Referenced by for(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), transformFvPatchField< Type >::gradientBoundaryCoeffs(), if(), anisotropicFilter::operator()(), snGradScheme< Type >::sndGrad(), snGrad(), snGradScheme< Type >::snGrad(), energyRegionCoupledFvPatchScalarField::snGrad(), cyclicACMIFvPatchField< Type >::snGrad(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), interfaceProperties::surfaceTensionForce(), externalCoupledMixedFvPatchField< Type >::transferData(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), and externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Definition at line 61 of file fvcSnGrad.C.
References snGrad().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcSnGrad.C.
References IOobject::name(), and snGrad().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 89 of file fvcSnGrad.C.
References snGrad().
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > & su, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 44 of file fvcSup.C.
Referenced by pressureGradientExplicitSource::addSup(), SemiImplicitSource< Type >::addSup(), solidificationMeltingSource::addSup(), ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ThermoParcel< ParcelType >::calc(), KinematicParcel< ParcelType >::calc(), KinematicParcel< ParcelType >::calcVelocity(), for(), forceSuSp::forceSuSp(), Foam::MULES::implicitSolve(), and laminar< Type >::R().
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tsu, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 55 of file fvcSup.C.
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 67 of file fvcSup.C.
Referenced by SemiImplicitSource< Type >::addSup(), solidificationMeltingSource::addSup(), for(), forAllConstIter(), forceSuSp::forceSuSp(), if(), Foam::MULES::implicitSolve(), KinematicCloud< CloudType >::SU(), and ReactingCloud< CloudType >::SYi().
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcSup.C.
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const dimensionedScalar & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 90 of file fvcSup.C.
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 102 of file fvcSup.C.
Referenced by SemiImplicitSource< Type >::addSup(), and ReactingCloud< CloudType >::Srho().
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 113 of file fvcSup.C.
void surfaceIntegrate (Field< Type > & ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 44 of file fvcSurfaceIntegrate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, mesh, DimensionedField< Type, GeoMesh >::mesh(), fvMesh::neighbour(), fvMesh::owner(), patchi, and fvMesh::Vsc().
Referenced by Foam::MULES::correct(), div(), Foam::MULES::explicitSolve(), boundedConvectionScheme< Type >::fvcDiv(), gaussConvectionScheme< Type >::fvcDiv(), boundedConvectionScheme< Type >::fvmDiv(), gaussConvectionScheme< Type >::fvmDiv(), anisotropicFilter::operator()(), and surfaceIntegrate().
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 82 of file fvcSurfaceIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, and surfaceIntegrate().
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 122 of file fvcSurfaceIntegrate.C.
References surfaceIntegrate().
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 138 of file fvcSurfaceIntegrate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), and patchi.
Referenced by anisotropicFilter::anisotropicFilter(), average(), kinematicSingleLayer::CourantNumber(), CourantNo::execute(), if(), kinematicSingleLayer::netMass(), simpleFilter::operator()(), reconstruct(), and surfaceSum().
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > & tssf)
Definition at line 193 of file fvcSurfaceIntegrate.C.
References surfaceSum().
tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcVolumeIntegrate.C.
References GeometricField< Type, PatchField, GeoMesh >::internalField(), and DimensionedField< Type, GeoMesh >::mesh().
Referenced by domainIntegrate().
tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 56 of file fvcVolumeIntegrate.C.
References tmp< T >::clear().
tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 67 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::field(), and DimensionedField< Type, GeoMesh >::mesh().
tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh > > & tdf)
Definition at line 75 of file fvcVolumeIntegrate.C.
References tmp< T >::clear().
dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 86 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, Foam::gSum(), IOobject::name(), and volumeIntegrate().
Referenced by interRegionHeatTransferModel::addSup(), reactingOneDim::calculateMassTransfer(), kinematicSingleLayer::continuityCheck(), domainIntegrate(), forAll(), if(), and regionSizeDistribution::write().
dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Definition at line 101 of file fvcVolumeIntegrate.C.
References domainIntegrate().
dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 113 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, Foam::gSum(), IOobject::name(), and volumeIntegrate().
dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh > > & tdf)
Definition at line 128 of file fvcVolumeIntegrate.C.
References domainIntegrate().
tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, Istream & streamData)
Definition at line 43 of file surfaceInterpolate.C.
References DimensionedField< Type, GeoMesh >::mesh(), and surfaceInterpolationScheme< Type >::New().
Referenced by cloudSolution::read().
tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, const word & name)
Definition at line 60 of file surfaceInterpolate.C.
References DimensionedField< Type, GeoMesh >::mesh(), and surfaceInterpolationScheme< Type >::New().
tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, Istream & streamData)
Return weighting factors for scheme given from Istream.
Definition at line 77 of file surfaceInterpolate.C.
References surfaceInterpolationScheme< Type >::New().
tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, const word & name)
Return weighting factors for scheme given by name in dictionary.
Definition at line 93 of file surfaceInterpolate.C.
References fvSchemes::interpolationScheme(), and surfaceInterpolationScheme< Type >::New().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const surfaceScalarField & faceFlux, Istream & schemeData)
Definition at line 110 of file surfaceInterpolate.C.
References Foam::endl(), and Foam::Info.
Referenced by effectivenessHeatExchangerSource::addSup(), CoBlended< Type >::blendingFactor(), inverseVolumeDiffusivity::correct(), motionDirectionalDiffusivity::correct(), inverseDistanceDiffusivity::correct(), thixotropicViscosity::correct(), advectionDiffusion::correct(), Peclet::execute(), ddtScheme< Type >::fvcDdtPhiCoeff(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), Foam::interpolate(), Foam::MULES::interpolate(), interpolate(), kinematicSingleLayer::kinematicSingleLayer(), mixtureKEpsilon< BasicTurbulenceModel >::mixFlux(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), incompressibleTwoPhaseMixture::muf(), kinematicSingleLayer::netMass(), incompressibleTwoPhaseMixture::nuf(), simpleFilter::operator()(), compressibleTurbulenceModel::phi(), dynamicRefineFvMesh::refine(), reactingOneDim::solidRegionDiffNo(), displacementSBRStressFvMotionSolver::solve(), reactingOneDim::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), kinematicSingleLayer::solveMomentum(), reactingOneDim::solveSpeciesMass(), kinematicSingleLayer::solveThickness(), interfaceProperties::surfaceTensionForce(), thermoSingleLayer::thermoSingleLayer(), and dynamicRefineFvMesh::unrefine().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const surfaceScalarField & faceFlux, const word & name)
Definition at line 133 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, and Foam::name().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const surfaceScalarField & faceFlux, const word & name)
Definition at line 156 of file surfaceInterpolate.C.
References interpolate().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tFaceFlux, const word & name)
Definition at line 174 of file surfaceInterpolate.C.
References tmp< T >::clear(), and interpolate().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const tmp< surfaceScalarField > & tFaceFlux, const word & name)
Definition at line 192 of file surfaceInterpolate.C.
References tmp< T >::clear(), and interpolate().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, Istream & schemeData)
Interpolate field onto faces using scheme given by Istream.
Definition at line 212 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, and DimensionedField< Type, GeoMesh >::mesh().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 233 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, DimensionedField< Type, GeoMesh >::mesh(), and Foam::name().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name)
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 255 of file surfaceInterpolate.C.
References interpolate().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Interpolate field onto faces using 'interpolate(<name>)'.
Definition at line 273 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, interpolate(), and IOobject::name().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf)
Interpolate tmp field onto faces using 'interpolate(<name>)'.
Definition at line 294 of file surfaceInterpolate.C.
References interpolate().
tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const FieldField< fvPatchField, Type > & fvpff)
Interpolate boundary field onto faces (simply a type conversion)
Definition at line 307 of file surfaceInterpolate.C.
References forAll, patchi, PtrList< Field< Type > >::set(), and PtrList< Field< Type > >::size().
tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const tmp< FieldField< fvPatchField, Type > > & tfvpff)
Interpolate boundary field onto faces (simply a type conversion)
Definition at line 332 of file surfaceInterpolate.C.
References interpolate().
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, const word & name) static
Return weighting factors for scheme given by name in dictionary.
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
Definition at line 77 of file surfaceInterpolate.C.
References surfaceInterpolationScheme< Type >::New().
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, const word & name) static
Return weighting factors for scheme given by name in dictionary.
Definition at line 93 of file surfaceInterpolate.C.
References fvSchemes::interpolationScheme(), and surfaceInterpolationScheme< Type >::New().
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const surfaceScalarField & faceFlux, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const surfaceScalarField & dir, const word & reconFieldName = word::null) static
Interpolate field onto faces using scheme given by name in fvSchemes.
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 7 of file directionInterpolate.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, interpolate(), IOobject::name(), word::null, patchi, and sf().
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const surfaceScalarField & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
Definition at line 212 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, and DimensionedField< Type, GeoMesh >::mesh().
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 233 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, DimensionedField< Type, GeoMesh >::mesh(), and Foam::name().
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 255 of file surfaceInterpolate.C.
References interpolate().
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh > > & tvf) static
Interpolate tmp field onto faces using 'interpolate(<name>)'.
Definition at line 294 of file surfaceInterpolate.C.
References interpolate().
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf) static
Interpolate field onto faces using 'interpolate(<name>)'.
Definition at line 273 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, interpolate(), and IOobject::name().
static tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const FieldField< fvPatchField, Type > & fvpff) static
Interpolate boundary field onto faces (simply a type conversion)
Definition at line 307 of file surfaceInterpolate.C.
References forAll, patchi, PtrList< Field< Type > >::set(), and PtrList< Field< Type > >::size().
static tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const tmp< FieldField< fvPatchField, Type > > & tfvpff) static
Interpolate boundary field onto faces (simply a type conversion)
Definition at line 332 of file surfaceInterpolate.C.
References interpolate().
one Foam::fvc::interpolate (const one &) inline
Interpolate 'one' returning 'one'.
Definition at line 189 of file surfaceInterpolate.H.