OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::compressible Namespace Reference
Namespaces
RASModels
Classes
class alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField
A simple alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField with a fixed volumetric phase-change mass flux.
class alphatJayatillekeWallFunctionFvPatchScalarField
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model.
class alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model for the Eulerian multiphase solvers.
class alphatPhaseChangeWallFunctionFvPatchScalarField
Abstract base-class for all alphatWallFunctions supporting phase-change.
class alphatWallBoilingWallFunctionFvPatchScalarField
A thermal wall function for simulation of subcooled nucleate wall boiling.
class alphatWallFunctionFvPatchScalarField
This boundary condition provides a turbulent thermal diffusivity conditon when using wall functions.
class convectiveHeatTransferFvPatchScalarField
This boundary condition provides a convective heat transfer coefficient condition.
class filmPyrolysisRadiativeCoupledMixedFvPatchScalarField
Mixed boundary condition for temperature, to be used in the flow and pyrolysis regions when a film region model is used.
class thermalBaffle1DFvPatchScalarField
class thermalBaffleFvPatchScalarField
class turbulentHeatFluxTemperatureFvPatchScalarField
class turbulentTemperatureCoupledBaffleMixedFvPatchScalarField
Mixed boundary condition for temperature, to be used for heat-transfer on back-to-back baffles.Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
class turbulentTemperatureRadCoupledMixedFvPatchScalarField
Mixed boundary condition for temperature and radiation heat transfer to be used for in multiregion cases. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
Typedefs
typedef thermalBaffle1DFvPatchScalarField< hConstSolidThermoPhysics > constSolid_thermalBaffle1DFvPatchScalarField
typedef thermalBaffle1DFvPatchScalarField< hPowerSolidThermoPhysics > expoSolid_thermalBaffle1DFvPatchScalarField
typedef ThermalDiffusivity< CompressibleTurbulenceModel< fluidThermo > > turbulenceModel
typedef RASModel< EddyDiffusivity< turbulenceModel > > RASModel
typedef LESModel< EddyDiffusivity< turbulenceModel > > LESModel
Typedefs for turbulence, RAS and LES models for compressible flow based on the standard laminar transport package.
Functions
makePatchTypeField (fvPatchScalarField, thermalBaffleFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, convectiveHeatTransferFvPatchScalarField)
addToPatchFieldRunTimeSelection (fvPatchScalarField, constSolid_thermalBaffle1DFvPatchScalarField)
addToPatchFieldRunTimeSelection (fvPatchScalarField, expoSolid_thermalBaffle1DFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentHeatFluxTemperatureFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentTemperatureCoupledBaffleMixedFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentTemperatureRadCoupledMixedFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, alphatJayatillekeWallFunctionFvPatchScalarField)
defineTypeNameAndDebug (alphatPhaseChangeWallFunctionFvPatchScalarField, 0)
makePatchTypeField (fvPatchScalarField, alphatWallFunctionFvPatchScalarField)
template<class BasicCompressibleTurbulenceModel >
autoPtr< BasicCompressibleTurbulenceModel > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const typename BasicCompressibleTurbulenceModel::transportModel &transport, const word &propertiesName)
Typedef Documentation
typedef thermalBaffle1DFvPatchScalarField< hConstSolidThermoPhysics > constSolid_thermalBaffle1DFvPatchScalarField
Definition at line 44 of file thermalBaffle1DFvPatchScalarFields.H.
typedef thermalBaffle1DFvPatchScalarField< hPowerSolidThermoPhysics > expoSolid_thermalBaffle1DFvPatchScalarField
Definition at line 49 of file thermalBaffle1DFvPatchScalarFields.H.
turbulenceModel
Foam::compressible::RASModel
Definition at line 60 of file turbulentFluidThermoModel.H.
typedef RASModel<EddyDiffusivity<turbulenceModel> > RASModel
Definition at line 62 of file turbulentFluidThermoModel.H.
LESModel
Typedefs for turbulence, RAS and LES models for compressible flow based on the standard laminar transport package.
Source files
turbulentFluidThermoModel.H
turbulentFluidThermoModel.C
turbulentFluidThermoModels.C
Definition at line 63 of file turbulentFluidThermoModel.H.
Function Documentation
Foam::compressible::makePatchTypeField (fvPatchScalarField , thermalBaffleFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , convectiveHeatTransferFvPatchScalarField)
Foam::compressible::addToPatchFieldRunTimeSelection (fvPatchScalarField , constSolid_thermalBaffle1DFvPatchScalarField)
Foam::compressible::addToPatchFieldRunTimeSelection (fvPatchScalarField , expoSolid_thermalBaffle1DFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentHeatFluxTemperatureFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentTemperatureCoupledBaffleMixedFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentTemperatureRadCoupledMixedFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatJayatillekeWallFunctionFvPatchScalarField)
Foam::compressible::defineTypeNameAndDebug (alphatPhaseChangeWallFunctionFvPatchScalarField , 0)
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatWallFunctionFvPatchScalarField)
autoPtr<BasicCompressibleTurbulenceModel> Foam::compressible::New (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const typename BasicCompressibleTurbulenceModel::transportModel & transport, const word & propertiesName)
Definition at line 36 of file turbulentFluidThermoModel.C.
Referenced by fvMeshTools::addPatch(), Foam::vtkPV4Readers::AddToBlock(), Foam::vtkPV3Readers::AddToBlock(), GAMGAgglomeration::agglomerateLduAddressing(), Foam::atan2(), ParamagneticForce< CloudType >::cacheFields(), CentredFitSnGradScheme< Type, Polynomial, Stencil >::correction(), CentredFitScheme< Type, Polynomial, Stencil >::correction(), pointLinear< Type >::correction(), PureUpwindFitScheme< Type, Polynomial, Stencil >::correction(), UpwindFitScheme< Type, Polynomial, Stencil >::correction(), displacementComponentLaplacianFvMotionSolver::displacementComponentLaplacianFvMotionSolver(), displacementLaplacianFvMotionSolver::displacementLaplacianFvMotionSolver(), explicitPorositySource::explicitPorositySource(), fanFvPatchField< Type >::fanFvPatchField(), mappedPatchBase::findSamples(), flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField(), for(), forAll(), faceCorrectedSnGrad< Type >::fullGradCorrection(), GAMGSolver::GAMGSolver(), if(), sampledCuttingPlane::interpolateField(), sampledIsoSurface::interpolateField(), distanceSurface::interpolateField(), TableBase< Type >::interpolator(), liquidMixtureProperties::liquidMixtureProperties(), Foam::fvc::meshPhi(), ThermalDiffusivity< BasicTurbulenceModel >::New(), CompressibleTurbulenceModel< TransportModel >::New(), PhaseCompressibleTurbulenceModel< TransportModel >::New(), PhaseIncompressibleTurbulenceModel< TransportModel >::New(), IncompressibleTurbulenceModel< TransportModel >::New(), motionSolver::New(), interpolation< Type >::New(), pointPatchField< Type >::New(), fvsPatchField< Type >::New(), UnsortedMeshedSurface< Face >::New(), fvPatchField< Type >::New(), MeshedSurface< Face >::New(), polyPatch::New(), GAMGAgglomeration::New(), extendedEdgeMesh::New(), INew< T >::operator()(), pointBoundaryMesh::pointBoundaryMesh(), polyBoundaryMesh::polyBoundaryMesh(), Foam::pow(), profileModelList::profileModelList(), edgeMesh::read(), UnsortedMeshedSurface< Face >::read(), MeshedSurface< Face >::read(), extendedEdgeMesh::read(), GeometricField< Type, PatchField, GeoMesh >::GeometricBoundaryField::readField(), CodedSource< Type >::redirectFvOption(), regionModelFunctionObjectList::regionModelFunctionObjectList(), CollidingCloud< CloudType >::setModels(), SprayCloud< CloudType >::setModels(), MPPICCloud< CloudType >::setModels(), ReactingCloud< CloudType >::setModels(), ReactingMultiphaseCloud< CloudType >::setModels(), ThermoCloud< CloudType >::setModels(), KinematicCloud< CloudType >::setModels(), sixDoFRigidBodyMotionSolver::sixDoFRigidBodyMotionSolver(), SmoothSolver< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), PBiCCCG< Type, DType, LUType >::solve(), PCG::solve(), PBiCG::solve(), fvMatrix< Type >::solver(), fvMatrix< Type >::solveSegregated(), Foam::stabilise(), LeastSquaresVectors< Stencil >::stencil(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), timeVaryingMappedFixedValuePointPatchField< Type >::timeVaryingMappedFixedValuePointPatchField(), Foam::transform(), uniformJumpAMIFvPatchField< Type >::uniformJumpAMIFvPatchField(), uniformJumpFvPatchField< Type >::uniformJumpFvPatchField(), FacePostProcessing< CloudType >::write(), and ParticleCollector< CloudType >::write().