OpenFOAM-dev: Foam::fvc Namespace Reference 2
Foam::fvc Namespace Reference
Namespace of functions to calculate explicit derivatives.
Functions
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
Area-weighted average a surfaceField creating a volField.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const CombineOp &cop)
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &, const CombineOp &cop)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &psi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > &tphi, const GeometricField< Type, fvPatchField, volMesh > &psi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh &mesh)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensionedScalar &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf, const one &)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
geometricZeroField ddt (const one &, const one &)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvvf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
tmp< surfaceScalarField > flux (const volVectorField &vvf)
Return the face-flux field obtained from the given volVectorField.
tmp< surfaceScalarField > flux (const tmp< volVectorField > &tvvf)
Return the face-flux field obtained from the given tmp volVectorField.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
tmp< surfaceScalarField > meshPhi (const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const dimensionedScalar &rho, const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const volScalarField &rho, const volVectorField &U)
void makeRelative (surfaceScalarField &phi, const volVectorField &U)
Make the given flux relative.
void makeRelative (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
Make the given flux relative.
void makeRelative (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
Make the given flux relative.
void makeAbsolute (surfaceScalarField &phi, const volVectorField &U)
Make the given flux absolute.
void makeAbsolute (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
Make the given flux absolute.
void makeAbsolute (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
Make the given flux absolute.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
Return the given absolute flux in relative form.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
Return the given absolute flux in relative form.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
Return the given relative flux in absolute form.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
Return the given relative flux in absolute form.
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
tmp< volScalarField > reconstructMag (const surfaceScalarField &)
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > &)
void smooth (volScalarField &field, const scalar coeff)
void spread (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2, const scalar alphaMax=0.99, const scalar alphaMin=0.01)
void sweep (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > &su, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tsu, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const dimensionedScalar &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
void surfaceIntegrate (Field< Type > &ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh >> &tdf)
template<class Type >
dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh >> &tdf)
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const surfaceScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf)
Interpolate field onto faces using 'interpolate(<name>)'.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
Interpolate tmp field onto faces using 'interpolate(<name>)'.
template<class Type >
static tmp< FieldField< fvsPatchField, Type > > interpolate (const FieldField< fvPatchField, Type > &fvpff)
Interpolate boundary field onto faces (simply a type conversion)
template<class Type >
static tmp< FieldField< fvsPatchField, Type > > interpolate (const tmp< FieldField< fvPatchField, Type >> &tfvpff)
Interpolate boundary field onto faces (simply a type conversion)
one interpolate (const one &)
Interpolate 'one' returning 'one'.
template<class Type >
static tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &tvf)
Interpolate field onto faces.
template<class Type >
static tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
Interpolate tmp field onto faces.
Detailed Description
Namespace of functions to calculate explicit derivatives.
Function Documentation
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Area-weighted average a surfaceField creating a volField.
Definition at line 46 of file fvcAverage.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), tmp< T >::ref(), and surfaceSum().
Referenced by average(), Dual< Type >::average(), Foam::bound(), if(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints(), and while().
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Area-weighted average a surfaceField creating a volField.
Definition at line 93 of file fvcAverage.C.
References average().
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > & vtf)
Area-weighted average a surfaceField creating a volField.
Definition at line 109 of file fvcAverage.C.
References average(), and Foam::linearInterpolate().
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvtf)
Area-weighted average a surfaceField creating a volField.
Definition at line 120 of file fvcAverage.C.
References average().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > & , const CombineOp & cop)
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & , const CombineOp & cop)
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcCurl.C.
References grad(), IOobject::name(), tmp< T >::ref(), and Foam::skew().
Referenced by LiftForce< CloudType >::cacheFields(), and curl().
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 68 of file fvcCurl.C.
References curl().
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::d2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 60 of file fvcD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 45 of file fvcDDt.C.
References ddt(), div(), DimensionedField< Type, GeoMesh >::mesh(), and psi.
Referenced by DDt().
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 67 of file fvcDDt.C.
References tmp< T >::clear(), and DDt().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh & mesh)
Definition at line 45 of file fvcDdt.C.
References fvSchemes::ddtScheme(), dimensioned< Type >::name(), and ddtScheme< Type >::New().
Referenced by PressureGradientForce< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), Foam::CorrectPhi(), DDt(), ddt(), for(), forAll(), forAllConstIter(), forAllIter(), boundedDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvmDdt(), if(), and while().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 61 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 76 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 92 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 108 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 131 of file fvcDdt.C.
References ddt().
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf, const one &)
Definition at line 143 of file fvcDdt.C.
References ddt(), and ddtCorr().
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 155 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
Referenced by ddt(), ddtCorr(), forAllIter(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), and if().
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 171 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 192 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 209 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
geometricZeroField Foam::fvc::ddt (const one & , const one &) inline
Definition at line 106 of file fvcDdt.H.
References ddtCorr(), phi, rho, U, and Uf.
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 155 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
Referenced by ddt(), ddtCorr(), forAllIter(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), and if().
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 171 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 192 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 209 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 47 of file fvcDiv.C.
References IOobject::name(), and surfaceIntegrate().
Referenced by Implicit< CloudType >::cacheFields(), kEqn< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correct(), Foam::CorrectPhi(), DDt(), div(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), nonlinearEddyViscosity< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), for(), forAllConstIter(), forAllIter(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), if(), Foam::MULES::implicitSolve(), displacementSBRStressFvMotionSolver::solve(), reactingOneDim::solveContinuity(), kinematicSingleLayer::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), reactingOneDim::solveSpeciesMass(), while(), and FSD< CombThermoType, ThermoType >::~FSD().
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 65 of file fvcDiv.C.
References div().
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 84 of file fvcDiv.C.
References div(), DimensionedField< Type, GeoMesh >::mesh(), divScheme< Type >::New(), and ref().
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvvf, const word & name)
Definition at line 105 of file fvcDiv.C.
References div().
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 128 of file fvcDiv.C.
References div(), and IOobject::name().
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvvf)
Definition at line 145 of file fvcDiv.C.
References div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 159 of file fvcDiv.C.
References div(), flux(), DimensionedField< Type, GeoMesh >::mesh(), convectionScheme< Type >::New(), and ref().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 177 of file fvcDiv.C.
References tmp< T >::clear(), and div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 195 of file fvcDiv.C.
References div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 213 of file fvcDiv.C.
References tmp< T >::clear(), and div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 232 of file fvcDiv.C.
References div(), and IOobject::name().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 247 of file fvcDiv.C.
References tmp< T >::clear(), and div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 264 of file fvcDiv.C.
References div().
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 281 of file fvcDiv.C.
References tmp< T >::clear(), and div().
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & , const word & name)
Definition at line 84 of file fvcDiv.C.
References div(), DimensionedField< Type, GeoMesh >::mesh(), divScheme< Type >::New(), and ref().
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh >> & , const word & name)
Definition at line 105 of file fvcDiv.C.
References div().
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 128 of file fvcDiv.C.
References div(), and IOobject::name().
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
Definition at line 145 of file fvcDiv.C.
References div().
Foam::tmp< Foam::surfaceScalarField > flux (const volVectorField & vvf)
Return the face-flux field obtained from the given volVectorField.
Definition at line 32 of file fvcFlux.C.
References DimensionedField< Type, GeoMesh >::mesh(), and IOobject::name().
Referenced by Foam::fvm::div(), div(), flux(), for(), forAll(), forAllIter(), gaussConvectionScheme< Type >::fvcDiv(), if(), kinematicSingleLayer::kinematicSingleLayer(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), thermoSingleLayer::thermoSingleLayer(), and while().
Foam::tmp< Foam::surfaceScalarField > flux (const tmp< volVectorField > & tvvf)
Return the face-flux field obtained from the given tmp volVectorField.
Definition at line 45 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 150 of file fvcFluxTemplates.C.
References flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcFluxTemplates.C.
References flux(), DimensionedField< Type, GeoMesh >::mesh(), convectionScheme< Type >::New(), and phi.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 63 of file fvcFluxTemplates.C.
References tmp< T >::clear(), and flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 81 of file fvcFluxTemplates.C.
References flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 99 of file fvcFluxTemplates.C.
References tmp< T >::clear(), and flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 118 of file fvcFluxTemplates.C.
References flux(), and IOobject::name().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 133 of file fvcFluxTemplates.C.
References tmp< T >::clear(), and flux().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 167 of file fvcFluxTemplates.C.
References tmp< T >::clear(), and flux().
tmp< GeometricField < typename outerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 52 of file fvcGrad.C.
References grad(), gaussGrad< Type >::gradf(), and IOobject::name().
Referenced by GradientDispersionRAS< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), dynamicKEqn< BasicTurbulenceModel >::Ce(), thermocapillaryForce::correct(), diffusion< CombThermoType, ThermoType >::correct(), contactAngleForce::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), ShihQuadraticKE::correct(), Poisson::correct(), LamBremhorstKE::correct(), LienLeschziner::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correct(), cubic< Type >::correction(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), ShihQuadraticKE::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), realizableKE< BasicTurbulenceModel >::correctNut(), LienCubicKE::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correctNut(), curl(), linearViscousStress< BasicTurbulenceModel >::devRhoReff(), ReynoldsStress< BasicTurbulenceModel >::devRhoReff(), forces::devRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), WALE< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), forAllIter(), correctedSnGrad< Type >::fullGradCorrection(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), grad(), if(), dynamicLagrangian< BasicTurbulenceModel >::k(), WALE< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), magSqrGradGrad(), ParticleTrap< CloudType >::preEvolve(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), eddyViscosity< BasicTurbulenceModel >::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), skewCorrected< Type >::skewCorrection(), displacementSBRStressFvMotionSolver::solve(), SpalartAllmaras< BasicTurbulenceModel >::Stilda(), viscosityModel::strainRate(), while(), Basic< Type >::~Basic(), FSD< CombThermoType, ThermoType >::~FSD(), and gradScheme< Type >::~gradScheme().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 69 of file fvcGrad.C.
References grad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 92 of file fvcGrad.C.
References grad(), DimensionedField< Type, GeoMesh >::mesh(), and gradScheme< Type >::New().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 114 of file fvcGrad.C.
References grad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 143 of file fvcGrad.C.
References grad(), and IOobject::name().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 160 of file fvcGrad.C.
References grad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Definition at line 52 of file fvcGrad.C.
References grad(), gaussGrad< Type >::gradf(), and IOobject::name().
Referenced by GradientDispersionRAS< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), dynamicKEqn< BasicTurbulenceModel >::Ce(), thermocapillaryForce::correct(), diffusion< CombThermoType, ThermoType >::correct(), contactAngleForce::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), ShihQuadraticKE::correct(), Poisson::correct(), LamBremhorstKE::correct(), LienLeschziner::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correct(), cubic< Type >::correction(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), ShihQuadraticKE::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), realizableKE< BasicTurbulenceModel >::correctNut(), LienCubicKE::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correctNut(), curl(), linearViscousStress< BasicTurbulenceModel >::devRhoReff(), ReynoldsStress< BasicTurbulenceModel >::devRhoReff(), forces::devRhoReff(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), WALE< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), forAllIter(), correctedSnGrad< Type >::fullGradCorrection(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), grad(), if(), dynamicLagrangian< BasicTurbulenceModel >::k(), WALE< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), magSqrGradGrad(), ParticleTrap< CloudType >::preEvolve(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), eddyViscosity< BasicTurbulenceModel >::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), skewCorrected< Type >::skewCorrection(), displacementSBRStressFvMotionSolver::solve(), SpalartAllmaras< BasicTurbulenceModel >::Stilda(), viscosityModel::strainRate(), while(), Basic< Type >::~Basic(), FSD< CombThermoType, ThermoType >::~FSD(), and gradScheme< Type >::~gradScheme().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
Definition at line 69 of file fvcGrad.C.
References grad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & , const word & name)
Definition at line 92 of file fvcGrad.C.
References grad(), DimensionedField< Type, GeoMesh >::mesh(), and gradScheme< Type >::New().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & , const word & name)
Definition at line 114 of file fvcGrad.C.
References grad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 143 of file fvcGrad.C.
References grad(), and IOobject::name().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
Definition at line 160 of file fvcGrad.C.
References grad().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcLaplacian.C.
References DimensionedField< Type, GeoMesh >::mesh(), laplacianScheme< Type, GType >::New(), and ref().
Referenced by Implicit< CloudType >::cacheFields(), Foam::CorrectPhi(), linearViscousStress< BasicTurbulenceModel >::divDevRhoReff(), ReynoldsStress< BasicTurbulenceModel >::divDevRhoReff(), for(), forAll(), forAllIter(), if(), laplacian(), laplaceFilter::operator()(), kinematicSingleLayer::pu(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), reactingOneDim::solveEnergy(), and while().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 61 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 89 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 107 of file fvcLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 133 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 151 of file fvcLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 176 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 195 of file fvcLaplacian.C.
References laplacian(), DimensionedField< Type, GeoMesh >::mesh(), laplacianScheme< Type, GType >::New(), and ref().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 212 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 230 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 248 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 267 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 284 of file fvcLaplacian.C.
References laplacian(), Foam::name(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 301 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 318 of file fvcLaplacian.C.
References laplacian(), and Foam::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 337 of file fvcLaplacian.C.
References laplacian(), DimensionedField< Type, GeoMesh >::mesh(), laplacianScheme< Type, GType >::New(), and ref().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 354 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 372 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 389 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 408 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 425 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 442 of file fvcLaplacian.C.
References laplacian().
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 458 of file fvcLaplacian.C.
References laplacian().
tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 44 of file fvcMagSqrGradGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::component(), grad(), Foam::magSqr(), and tmp< T >::ref().
Referenced by LaunderSharmaKE< BasicTurbulenceModel >::correct(), qZeta::correct(), and magSqrGradGrad().
tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 67 of file fvcMagSqrGradGrad.C.
References magSqrGradGrad().
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volVectorField & U)
Definition at line 34 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and Foam::New().
Referenced by absolute(), if(), makeAbsolute(), makeRelative(), meshPhi(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), relative(), movingWallVelocityFvPatchVectorField::updateCoeffs(), and while().
Foam::tmp< Foam::surfaceScalarField > meshPhi (const dimensionedScalar & rho, const volVectorField & U)
Definition at line 47 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), meshPhi(), dimensioned< Type >::name(), IOobject::name(), and Foam::New().
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volScalarField & rho, const volVectorField & U)
Definition at line 61 of file fvcMeshPhi.C.
References makeRelative(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and Foam::New().
void makeRelative (surfaceScalarField & phi, const volVectorField & U)
Make the given flux relative.
Definition at line 75 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
Referenced by Foam::CorrectPhi(), makeRelative(), and meshPhi().
void makeRelative (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Make the given flux relative.
Definition at line 87 of file fvcMeshPhi.C.
References makeRelative(), DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
void makeRelative (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Make the given flux relative.
Definition at line 100 of file fvcMeshPhi.C.
References Foam::MULES::interpolate(), makeAbsolute(), DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
void makeAbsolute (surfaceScalarField & phi, const volVectorField & U)
Make the given flux absolute.
Definition at line 114 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
Referenced by Foam::CorrectPhi(), if(), makeAbsolute(), and makeRelative().
void makeAbsolute (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Make the given flux absolute.
Definition at line 126 of file fvcMeshPhi.C.
References makeAbsolute(), DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
void makeAbsolute (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Make the given flux absolute.
Definition at line 139 of file fvcMeshPhi.C.
References Foam::MULES::interpolate(), DimensionedField< Type, GeoMesh >::mesh(), meshPhi(), and relative().
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Return the given absolute flux in relative form.
Definition at line 153 of file fvcMeshPhi.C.
References mesh, and meshPhi().
Referenced by pimpleControl::criteriaSatisfied(), and makeAbsolute().
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Return the given absolute flux in relative form.
Definition at line 170 of file fvcMeshPhi.C.
References absolute(), Foam::MULES::interpolate(), mesh, and meshPhi().
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Return the given relative flux in absolute form.
Definition at line 188 of file fvcMeshPhi.C.
References mesh, and meshPhi().
Referenced by kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< TurbulenceModel, BasicTurbulenceModel >::correct(), if(), relative(), and while().
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Return the given relative flux in absolute form.
Definition at line 205 of file fvcMeshPhi.C.
References Foam::MULES::interpolate(), mesh, and meshPhi().
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 54 of file fvcReconstruct.C.
References IOobject::instance(), Foam::inv(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, reconstruct(), fvMesh::Sf(), and surfaceSum().
Referenced by Implicit< CloudType >::cacheFields(), for(), if(), reconstruct(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and while().
tmp< GeometricField < typename outerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 96 of file fvcReconstruct.C.
References reconstruct().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Definition at line 54 of file fvcReconstruct.C.
References IOobject::instance(), Foam::inv(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, reconstruct(), fvMesh::Sf(), and surfaceSum().
Referenced by Implicit< CloudType >::cacheFields(), for(), if(), reconstruct(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and while().
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
Definition at line 96 of file fvcReconstruct.C.
References reconstruct().
tmp< volScalarField > reconstructMag (const surfaceScalarField & ssf)
Definition at line 44 of file fvcReconstructMag.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvMesh::Cf(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), patchi, fvMesh::Sf(), and fvMesh::V().
Referenced by reconstructMag().
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > & tssf)
Definition at line 117 of file fvcReconstructMag.C.
References tmp< T >::clear(), and reconstructMag().
void smooth (volScalarField & field, const scalar coeff)
Definition at line 35 of file fvcSmooth.C.
References List< T >::append(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), polyMesh::faceOwner(), forAll, polyMesh::globalData(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), globalMeshData::nTotalCells(), fvMesh::owner(), patchi, spread(), and polyPatch::start().
Referenced by forAll(), if(), lduMatrix::smoother::interfaces(), LduMatrix< Type, DType, LUType >::smoother::matrix(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), and nonBlockingGaussSeidelSmoother::smooth().
void spread (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2, const scalar alphaMax = 0.99, const scalar alphaMin = 0.01)
Definition at line 124 of file fvcSmooth.C.
References List< T >::append(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), polyMesh::faceOwner(), forAll, FaceCellWave< Type, TrackingData >::iterate(), Foam::mag(), Foam::max(), smoothData::trackData::maxRatio, mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), fvMesh::owner(), patchi, FaceCellWave< Type, TrackingData >::setFaceInfo(), polyPatch::start(), and sweep().
Referenced by if(), and smooth().
void sweep (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2)
Definition at line 222 of file fvcSmooth.C.
References List< T >::append(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), FaceCellWave< Type, TrackingData >::data(), primitiveMesh::faceCentres(), polyMesh::faceOwner(), forAll, FaceCellWave< Type, TrackingData >::iterate(), Foam::mag(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), fvMesh::owner(), patchi, FaceCellWave< Type, TrackingData >::setFaceInfo(), and polyPatch::start().
Referenced by if(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), DILUSmoother::smooth(), DICSmoother::smooth(), FDICSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), and spread().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcSnGrad.C.
References DimensionedField< Type, GeoMesh >::mesh(), and snGradScheme< Type >::New().
Referenced by for(), forAllIter(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), transformFvPatchField< Type >::gradientBoundaryCoeffs(), if(), anisotropicFilter::operator()(), snGradScheme< Type >::sndGrad(), snGrad(), snGradScheme< Type >::snGrad(), energyRegionCoupledFvPatchScalarField::snGrad(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), interfaceProperties::surfaceTensionForce(), externalCoupledMixedFvPatchField< Type >::transferData(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs(), and while().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 61 of file fvcSnGrad.C.
References snGrad().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcSnGrad.C.
References IOobject::name(), and snGrad().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 89 of file fvcSnGrad.C.
References snGrad().
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > & su, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 44 of file fvcSup.C.
Referenced by meanVelocityForce::addSup(), SemiImplicitSource< Type >::addSup(), solidificationMeltingSource::addSup(), ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ThermoParcel< ParcelType >::calc(), KinematicParcel< ParcelType >::calc(), KinematicParcel< ParcelType >::calcVelocity(), for(), forAll(), if(), Foam::MULES::implicitSolve(), laminar< Type >::R(), while(), and RaviPetersen::~RaviPetersen().
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tsu, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 55 of file fvcSup.C.
References Sp().
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 67 of file fvcSup.C.
Referenced by SemiImplicitSource< Type >::addSup(), solidificationMeltingSource::addSup(), for(), forAllConstIter(), forAllIter(), if(), Foam::MULES::implicitSolve(), Sp(), Foam::fvm::Su(), KinematicCloud< CloudType >::SU(), ReactingCloud< CloudType >::SYi(), and while().
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcSup.C.
References Sp().
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const dimensionedScalar & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 90 of file fvcSup.C.
References SuSp().
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 102 of file fvcSup.C.
Referenced by SemiImplicitSource< Type >::addSup(), if(), Foam::fvm::Sp(), and ReactingCloud< CloudType >::Srho().
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 113 of file fvcSup.C.
void surfaceIntegrate (Field< Type > & ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 44 of file fvcSurfaceIntegrate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, mesh, DimensionedField< Type, GeoMesh >::mesh(), fvMesh::neighbour(), fvMesh::owner(), patchi, and fvMesh::Vsc().
Referenced by Foam::MULES::correct(), div(), boundedConvectionScheme< Type >::fvcDiv(), gaussConvectionScheme< Type >::fvcDiv(), boundedConvectionScheme< Type >::fvmDiv(), gaussConvectionScheme< Type >::fvmDiv(), anisotropicFilter::operator()(), and surfaceIntegrate().
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 82 of file fvcSurfaceIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::ref(), surfaceIntegrate(), and Foam::Zero.
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 122 of file fvcSurfaceIntegrate.C.
References surfaceIntegrate(), and surfaceSum().
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 138 of file fvcSurfaceIntegrate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), patchi, GeometricField< Type, PatchField, GeoMesh >::ref(), and Foam::Zero.
Referenced by anisotropicFilter::anisotropicFilter(), average(), cellCoBlended< Type >::blendingFactor(), kinematicSingleLayer::CourantNumber(), forAll(), if(), kinematicSingleLayer::netMass(), simpleFilter::operator()(), reconstruct(), surfaceIntegrate(), and surfaceSum().
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 193 of file fvcSurfaceIntegrate.C.
References surfaceSum().
tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::mesh(), and GeometricField< Type, PatchField, GeoMesh >::primitiveField().
Referenced by domainIntegrate().
tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 56 of file fvcVolumeIntegrate.C.
References tmp< T >::clear().
tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 67 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::field(), and DimensionedField< Type, GeoMesh >::mesh().
tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh >> & tdf)
Definition at line 75 of file fvcVolumeIntegrate.C.
References tmp< T >::clear(), and domainIntegrate().
dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 86 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, Foam::gSum(), IOobject::name(), and volumeIntegrate().
Referenced by interRegionHeatTransferModel::addSup(), reactingOneDim::calculateMassTransfer(), kinematicSingleLayer::continuityCheck(), domainIntegrate(), forAll(), if(), ListPlusEqOp< T, Size >::operator()(), volumeIntegrate(), and regionSizeDistribution::write().
dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 101 of file fvcVolumeIntegrate.C.
References domainIntegrate().
dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 113 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, domainIntegrate(), Foam::gSum(), IOobject::name(), and volumeIntegrate().
dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh >> & tdf)
Definition at line 128 of file fvcVolumeIntegrate.C.
References domainIntegrate().
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
Referenced by cloudSolution::read().
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, const word & name) static
Return weighting factors for scheme given by name in dictionary.
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, const word & name) static
Return weighting factors for scheme given by name in dictionary.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const surfaceScalarField & faceFlux, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
Referenced by effectivenessHeatExchangerSource::addSup(), CoBlended< Type >::blendingFactor(), cellCoBlended< Type >::blendingFactor(), inverseVolumeDiffusivity::correct(), motionDirectionalDiffusivity::correct(), inverseDistanceDiffusivity::correct(), thixotropicViscosity::correct(), advectionDiffusion::correct(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), Foam::interpolate(), Foam::MULES::interpolate(), mixtureKEpsilon< BasicTurbulenceModel >::mixFlux(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), incompressibleTwoPhaseMixture::muf(), kinematicSingleLayer::netMass(), incompressibleTwoPhaseMixture::nuf(), simpleFilter::operator()(), compressibleTurbulenceModel::phi(), dynamicRefineFvMesh::refine(), reactingOneDim::solidRegionDiffNo(), displacementSBRStressFvMotionSolver::solve(), reactingOneDim::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), kinematicSingleLayer::solveMomentum(), reactingOneDim::solveSpeciesMass(), kinematicSingleLayer::solveThickness(), interfaceProperties::surfaceTensionForce(), and dynamicRefineFvMesh::unrefine().
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const surfaceScalarField & dir, const word & reconFieldName = word::null) static
Interpolate field onto faces using scheme given by name in fvSchemes.
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 7 of file directionInterpolate.H.
References interpolate(), IOobject::name(), word::null, GeometricField< Type, PatchField, GeoMesh >::ref(), and sf().
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const surfaceScalarField & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf) static
Interpolate field onto faces using 'interpolate(<name>)'.
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf) static
Interpolate tmp field onto faces using 'interpolate(<name>)'.
static tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const FieldField< fvPatchField, Type > & fvpff) static
Interpolate boundary field onto faces (simply a type conversion)
static tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const tmp< FieldField< fvPatchField, Type >> & tfvpff) static
Interpolate boundary field onto faces (simply a type conversion)
one Foam::fvc::interpolate (const one &) inline
Interpolate 'one' returning 'one'.
Definition at line 190 of file surfaceInterpolate.H.
References dotInterpolate().
static tmp< GeometricField < typename innerProduct<vector, Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::dotInterpolate (const surfaceVectorField & Sf, const GeometricField< Type, fvPatchField, volMesh > & tvf) static
Interpolate field onto faces.
and 'dot' with given surfaceVectorField Sf
Referenced by correctedSnGrad< Type >::fullGradCorrection(), ddtScheme< Type >::fvcDdtPhiCoeff(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), surfaceInterpolationScheme< Type >::interpolate(), interpolate(), and displacementSBRStressFvMotionSolver::solve().
static tmp< GeometricField < typename innerProduct<vector, Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::dotInterpolate (const surfaceVectorField & Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf) static
Interpolate tmp field onto faces.
and 'dot' with given surfaceVectorField Sf