OpenFOAM: CGAL Namespace Reference
CGAL Namespace Reference
Namespaces
indexedCellOps
indexedVertexOps
Classes
class indexedCell
An indexed form of CGAL::Triangulation_cell_base_3<K> used to keep track of the Delaunay cells (tets) in the tessellation.
class indexedFace
An indexed form of CGAL::Triangulation_face_base_2<K> used to keep track of the vertices in the triangulation.
class indexedVertex
An indexed form of CGAL::Triangulation_vertex_base_3<K> used to keep track of the Delaunay vertices in the tessellation.
Functions
template<class Gt , class Vb >
bool pointPair (const indexedVertex< Gt, Vb > &v0, const indexedVertex< Gt, Vb > &v1)
template<class Gt , class Vb >
bool boundaryTriangle (const indexedVertex< Gt, Vb > &v0, const indexedVertex< Gt, Vb > &v1, const indexedVertex< Gt, Vb > &v2)
template<class Gt , class Vb >
bool outsideTriangle (const indexedVertex< Gt, Vb > &v0, const indexedVertex< Gt, Vb > &v1, const indexedVertex< Gt, Vb > &v2)
Function Documentation
bool pointPair (const indexedVertex< Gt, Vb > & v0, const indexedVertex< Gt, Vb > & v1)
Definition at line 196 of file indexedVertexI.H.
References boundaryTriangle().
Referenced by indexedVertex< Gt, Vb >::ppSlave().
bool boundaryTriangle (const indexedVertex< Gt, Vb > & v0, const indexedVertex< Gt, Vb > & v1, const indexedVertex< Gt, Vb > & v2)
Definition at line 207 of file indexedVertexI.H.
References outsideTriangle(), indexedVertex< Gt, Vb >::pairPoint(), and indexedVertex< Gt, Vb >::pointPair.
Referenced by pointPair().
bool outsideTriangle (const indexedVertex< Gt, Vb > & v0, const indexedVertex< Gt, Vb > & v1, const indexedVertex< Gt, Vb > & v2)
Definition at line 221 of file indexedVertexI.H.
References indexedVertex< Gt, Vb >::farPoint(), and indexedVertex< Gt, Vb >::ppSlave().
Referenced by boundaryTriangle().