OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::functionObjects Namespace Reference
Namespace for functionObjects.
Namespaces
fieldValues
Classes
class abort
Watches for presence of the named file in the $FOAM_CASE directory and aborts the calculation if it is present.
class blendingFactor
This function object calculates and outputs the blendingFactor as used by the bended convection schemes. The output is a volume field (cells) whose value is calculated via the maximum blending factor for any cell face.
class cloudInfo
This function object outputs Lagrangian cloud information to a file. The current outputs include:
class components
This function object calculates the components of a field.
class CourantNo
This function object calculates and outputs the Courant number as a volScalarField. The field is stored on the mesh database so that it can be retrieved and used for other applications.
class div
This function object calculates the divergence of a field. The operation is limited to surfaceScalarFields and volVectorFields, and the output is a volScalarField.
class dsmcFields
Calculate intensive fields:
class enstrophy
This function object calculates the enstrophy of the velocity.
class fieldAverage
This function object calculates average quantities for a user-specified selection of volumetric and surface fields. Fields are entered as a list of sub-dictionaries, which indicate the type of averages to perform, and can be updated during the calculation. The current options include:
class fieldAverageItem
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the form:
class fieldCoordinateSystemTransform
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
class fieldExpression
class fieldMinMax
This function object calculates the value and location of scalar minimim and maximum for a list of user-specified fields. For variables with a rank greater than zero, either the min/max of a component value or the magnitude is reported. When operating in parallel, the processor owning the value is also given.
class fieldValue
class flowType
This function object calculates and writes the flowType of a velocity field.
class forceCoeffs
This function object extends the Foam::forces function object by providing lift, drag and moment coefficients. The data can optionally be output into bins, defined in a given direction.
class forces
This function object calculates the forces and moments by integrating the pressure and skin-friction forces over a given list of patches.
class fvMeshFunctionObject
Specialization of Foam::functionObject for an Foam::fvMesh, providing a reference to the Foam::fvMesh.
class grad
This function object calculates the gradient of a field. The operation is limited to scalar and vector volume or surface fields, and the output is a volume vector or tensor field.
class histogram
Write the volume-weighted histogram of a volScalarField.
class icoUncoupledKinematicCloud
This functionObject tracks a uncoupled kinematic particle cloud in the specified velocity field of an incompressible flow (laminar, RANS or LES).
class Lambda2
This function object calculates and outputs the second largest eigenvalue of the sum of the square of the symmetrical and anti-symmetrical parts of the velocity gradient tensor.
class MachNo
This function object calculates and writes the Mach number as a volScalarField.
class mag
This function object calculates the magnitude of a field.
class magSqr
This function object calculates the magnitude of the sqr of a field.
class nearWallFields
This function object samples near-patch volume fields.
class PecletNo
This function object calculates and outputs the Peclet number as a surfaceScalarField.
class pressure
This function object includes tools to manipulate the pressure into different forms. These currently include:
class processorField
This function object writes a scalar field whose value is the local processor ID. The output field name is 'processorID'.
class Q
This function object calculates and outputs the second invariant of the velocity gradient tensor [1/s^2].
class randomise
This function object adds a random component to a field, with a specified perturbation magnitude.
class readFields
This function object reads fields from the time directories and adds them to the mesh database for further post-processing.
class regionFunctionObject
Specialization of Foam::functionObject for a region and providing a reference to the region Foam::objectRegistry.
class regionSizeDistribution
This function object creates a size distribution via interrogating a continuous phase fraction field.
class removeRegisteredObject
This function object removes registered objects if present in the database.
class residuals
This function object writes out the initial residual for specified fields.
class scalarTransport
This function object evolves a passive scalar transport equation.
class setTimeStepFunctionObject
Overrides the timeStep. Can only be used with solvers with adjustTimeStep control (e.g. pimpleFoam). Makes no attempt to cooperate with other timeStep 'controllers' (maxCo, other functionObjects). Supports 'enabled' flag but none of othe other ones 'timeStart', 'timeEnd', 'writeControl' etc.
class streamLine
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field.
class surfaceInterpolate
class systemCall
This function object executes system calls, entered in the form of a string lists. Calls can be made at the following points in the calculation:
class timeActivatedFileUpdate
Performs a file copy/replacement once a specified time has been reached.
class timeControl
class turbulenceFields
This function object stores turbulence fields on the mesh database for further manipulation.
class vorticity
This function object calculates the vorticity, the curl of the velocity.
class wallBoundedStreamLine
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
class wallShearStress
This function object evaluates and outputs the shear stress at wall patches. The result is written as a volVectorField to time directories as field 'wallShearStress'.
class writeDictionary
This function object writes dictionaries on start-up, and on change.
class writeFile
functionObject base class for writing single files
class writeFiles
functionObject base class for writing files
class writeObjects
This function object allows specification of different writing frequency of objects registered to the database.
class writeVTK
This functionObject writes objects registered to the database in VTK format using the foamToVTK library.
class yPlus
Evaluates and outputs turbulence y+ for models. Values written to time directories as field 'yPlus'.
Functions
defineTypeNameAndDebug (fvMeshFunctionObject, 0)
defineTypeNameAndDebug (blendingFactor, 0)
addToRunTimeSelectionTable (functionObject, blendingFactor, dictionary)
defineTypeNameAndDebug (components, 0)
addToRunTimeSelectionTable (functionObject, components, dictionary)
defineTypeNameAndDebug (CourantNo, 0)
addToRunTimeSelectionTable (functionObject, CourantNo, dictionary)
defineTypeNameAndDebug (div, 0)
addToRunTimeSelectionTable (functionObject, div, dictionary)
defineTypeNameAndDebug (enstrophy, 0)
addToRunTimeSelectionTable (functionObject, enstrophy, dictionary)
defineTypeNameAndDebug (fieldAverage, 0)
addToRunTimeSelectionTable (functionObject, fieldAverage, dictionary)
Istream & operator>> (Istream &, fieldAverageItem &)
Ostream & operator<< (Ostream &, const fieldAverageItem &)
defineTypeNameAndDebug (fieldCoordinateSystemTransform, 0)
addToRunTimeSelectionTable (functionObject, fieldCoordinateSystemTransform, dictionary)
defineTypeNameAndDebug (fieldExpression, 0)
defineTypeNameAndDebug (fieldMinMax, 0)
addToRunTimeSelectionTable (functionObject, fieldMinMax, dictionary)
defineTypeNameAndDebug (fieldValue, 0)
defineRunTimeSelectionTable (fieldValue, dictionary)
defineTypeNameAndDebug (flowType, 0)
addToRunTimeSelectionTable (functionObject, flowType, dictionary)
defineTypeNameAndDebug (grad, 0)
addToRunTimeSelectionTable (functionObject, grad, dictionary)
defineTypeNameAndDebug (histogram, 0)
addToRunTimeSelectionTable (functionObject, histogram, dictionary)
defineTypeNameAndDebug (Lambda2, 0)
addToRunTimeSelectionTable (functionObject, Lambda2, dictionary)
defineTypeNameAndDebug (MachNo, 0)
addToRunTimeSelectionTable (functionObject, MachNo, dictionary)
defineTypeNameAndDebug (mag, 0)
addToRunTimeSelectionTable (functionObject, mag, dictionary)
defineTypeNameAndDebug (magSqr, 0)
addToRunTimeSelectionTable (functionObject, magSqr, dictionary)
defineTypeNameAndDebug (nearWallFields, 0)
addToRunTimeSelectionTable (functionObject, nearWallFields, dictionary)
defineTypeNameAndDebug (PecletNo, 0)
addToRunTimeSelectionTable (functionObject, PecletNo, dictionary)
defineTypeNameAndDebug (pressure, 0)
addToRunTimeSelectionTable (functionObject, pressure, dictionary)
defineTypeNameAndDebug (processorField, 0)
addToRunTimeSelectionTable (functionObject, processorField, dictionary)
defineTypeNameAndDebug (Q, 0)
addToRunTimeSelectionTable (functionObject, Q, dictionary)
defineTypeNameAndDebug (randomise, 0)
addToRunTimeSelectionTable (functionObject, randomise, dictionary)
defineTypeNameAndDebug (readFields, 0)
addToRunTimeSelectionTable (functionObject, readFields, dictionary)
defineTypeNameAndDebug (regionSizeDistribution, 0)
addToRunTimeSelectionTable (functionObject, regionSizeDistribution, dictionary)
defineTypeNameAndDebug (streamLine, 0)
addToRunTimeSelectionTable (functionObject, streamLine, dictionary)
defineTypeNameAndDebug (surfaceInterpolate, 0)
addToRunTimeSelectionTable (functionObject, surfaceInterpolate, dictionary)
defineTypeNameAndDebug (turbulenceFields, 0)
addToRunTimeSelectionTable (functionObject, turbulenceFields, dictionary)
defineTypeNameAndDebug (vorticity, 0)
addToRunTimeSelectionTable (functionObject, vorticity, dictionary)
defineTypeNameAndDebug (wallBoundedStreamLine, 0)
addToRunTimeSelectionTable (functionObject, wallBoundedStreamLine, dictionary)
defineTypeNameAndDebug (wallShearStress, 0)
addToRunTimeSelectionTable (functionObject, wallShearStress, dictionary)
defineTypeNameAndDebug (yPlus, 0)
addToRunTimeSelectionTable (functionObject, yPlus, dictionary)
defineTypeNameAndDebug (forceCoeffs, 0)
addToRunTimeSelectionTable (functionObject, forceCoeffs, dictionary)
defineTypeNameAndDebug (forces, 0)
addToRunTimeSelectionTable (functionObject, forces, dictionary)
defineTypeNameAndDebug (cloudInfo, 0)
addToRunTimeSelectionTable (functionObject, cloudInfo, dictionary)
defineTypeNameAndDebug (dsmcFields, 0)
addToRunTimeSelectionTable (functionObject, dsmcFields, dictionary)
defineTypeNameAndDebug (icoUncoupledKinematicCloud, 0)
addToRunTimeSelectionTable (functionObject, icoUncoupledKinematicCloud, dictionary)
defineTypeNameAndDebug (scalarTransport, 0)
addToRunTimeSelectionTable (functionObject, scalarTransport, dictionary)
defineTypeNameAndDebug (abort, 0)
addToRunTimeSelectionTable (functionObject, abort, dictionary)
defineTypeNameAndDebug (removeRegisteredObject, 0)
addToRunTimeSelectionTable (functionObject, removeRegisteredObject, dictionary)
defineTypeNameAndDebug (residuals, 0)
addToRunTimeSelectionTable (functionObject, residuals, dictionary)
defineTypeNameAndDebug (setTimeStepFunctionObject, 0)
addToRunTimeSelectionTable (functionObject, setTimeStepFunctionObject, dictionary)
defineTypeNameAndDebug (systemCall, 0)
addToRunTimeSelectionTable (functionObject, systemCall, dictionary)
defineTypeNameAndDebug (timeActivatedFileUpdate, 0)
addToRunTimeSelectionTable (functionObject, timeActivatedFileUpdate, dictionary)
defineTypeNameAndDebug (writeDictionary, 0)
addToRunTimeSelectionTable (functionObject, writeDictionary, dictionary)
defineTypeNameAndDebug (writeObjects, 0)
addToRunTimeSelectionTable (functionObject, writeObjects, dictionary)
defineTypeNameAndDebug (regionFunctionObject, 0)
defineTypeNameAndDebug (timeControl, 0)
Detailed Description
Namespace for functionObjects.
OpenFOAM includes a collection of functionObjects selected by the user at run-time to manipulate the simulation and provide mechanisms to extract field and derived quantities. Alternatively, the same actions can be executed after the simulation using the -postProcess command-line option.
FunctionObjects are selected by additional entries in the $FOAM_CASE/system/controlDict dictionary. Each object is listed in the functions sub-dictionary, e.g. to select the functionObjectType functionObject the following entry would be specified:
    functions
    {
        myFunctionObject    // Name of functionObject entry
        {
            type                functionObjectType;
            libs  ("libMyFunctionObjectlib.so");
            region              defaultRegion;
            enabled             yes;
            timeStart           0;
            timeEnd             10;
            writeControl        writeTime;
            writeInterval       1;
            ...
        }
    }
Where:
Property Description Required Default value
type Type of function object yes
libs Libraries containing implementation yes
region Name of region for multi-region cases no
enabled On/off switch no yes
timeStart Start time no
timeEnd End time no
evaluateControl See time controls below no timeStep
evaluateInterval Steps between output no
writeControl See time controls below no timeStep
writeInterval Steps between output no
Time controls:
Option Description
timeStep Execute/write every 'writeInterval' time-steps
writeTime Execute/write every 'writeInterval' output times
adjustableRunTime Execute/write every 'writeInterval' run time period
runTime Execute/write every 'writeInterval' run time period
clockTime Execute/write every 'writeInterval' clock time period
cpuTime Execute/write every 'writeInterval' CPU time period
none Execute/write every time-step
The sub-dictionary name myFunctionObject is chosen by the user, and is typically used as the name of the output directory for any data written by the functionObject. The type entry defines the type of function object properties that follow. FunctionObjects are packaged into separate libraries and the libs entry is used to specify which library should be loaded.
Function Documentation
Foam::functionObjects::defineTypeNameAndDebug (fvMeshFunctionObject , 0)
Foam::functionObjects::defineTypeNameAndDebug (blendingFactor , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , blendingFactor , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (components , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , components , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (CourantNo , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , CourantNo , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (div , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , div , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (enstrophy , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , enstrophy , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (fieldAverage , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , fieldAverage , dictionary)
Foam::Istream & operator>> (Istream & is, fieldAverageItem & faItem)
Definition at line 70 of file fieldAverageItemIO.C.
References IOstream::check(), fieldAverageItem::EXT_MEAN, fieldAverageItem::EXT_PRIME2MEAN, entry::keyword(), dictionary::lookup(), dictionary::lookupOrDefault(), and dictionary::null.
Foam::Ostream & operator<< (Ostream & os, const fieldAverageItem & faItem)
Definition at line 107 of file fieldAverageItemIO.C.
References token::BEGIN_BLOCK, IOstream::check(), token::END_BLOCK, token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Foam::functionObjects::defineTypeNameAndDebug (fieldCoordinateSystemTransform , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , fieldCoordinateSystemTransform , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (fieldExpression , 0)
Foam::functionObjects::defineTypeNameAndDebug (fieldMinMax , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , fieldMinMax , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (fieldValue , 0)
Foam::functionObjects::defineRunTimeSelectionTable (fieldValue , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (flowType , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , flowType , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (grad , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , grad , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (histogram , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , histogram , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (Lambda2 , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , Lambda2 , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (MachNo , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , MachNo , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (mag , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , mag , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (magSqr , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , magSqr , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (nearWallFields , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , nearWallFields , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (PecletNo , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , PecletNo , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (pressure , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , pressure , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (processorField , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , processorField , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (Q , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , Q , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (randomise , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , randomise , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (readFields , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , readFields , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (regionSizeDistribution , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , regionSizeDistribution , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (streamLine , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , streamLine , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (surfaceInterpolate , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , surfaceInterpolate , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (turbulenceFields , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , turbulenceFields , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (vorticity , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , vorticity , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (wallBoundedStreamLine , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , wallBoundedStreamLine , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (wallShearStress , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , wallShearStress , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (yPlus , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , yPlus , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (forceCoeffs , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , forceCoeffs , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (forces , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , forces , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (cloudInfo , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , cloudInfo , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (dsmcFields , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , dsmcFields , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (icoUncoupledKinematicCloud , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , icoUncoupledKinematicCloud , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (scalarTransport , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , scalarTransport , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (abort , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , abort , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (removeRegisteredObject , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , removeRegisteredObject , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (residuals , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , residuals , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (setTimeStepFunctionObject , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , setTimeStepFunctionObject , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (systemCall , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , systemCall , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (timeActivatedFileUpdate , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , timeActivatedFileUpdate , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (writeDictionary , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , writeDictionary , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (writeObjects , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , writeObjects , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (regionFunctionObject , 0)
Foam::functionObjects::defineTypeNameAndDebug (timeControl , 0)