OpenFOAM® Programmer's C++ documentation
OpenFOAM C++ Documentation
Foam::functionObjects Namespace Reference
Namespace for functionObjects.
Namespaces
fieldValues
Classes
class abort
Watches for presence of the named file in the $FOAM_CASE directory and aborts the calculation if it is present.
class blendingFactor
This function object calculates and outputs the blendingFactor as used by the bended convection schemes. The output is a volume field (cells) whose value is calculated via the maximum blending factor for any cell face.
class cloudInfo
This function object outputs Lagrangian cloud information to a file. The current outputs include:
class CourantNo
This function object calculates and outputs the Courant number as a volScalarField. The field is stored on the mesh database so that it can be retrieved and used for other applications.
class div
This function object calculates the divergence of a field. The operation is limited to surfaceScalarFields and volumeVector fields, and the output is a volume scalar field.
class dsmcFields
Calculate intensive fields:
class fieldAverage
This function object calculates average quantities for a user-specified selection of volumetric and surface fields. Fields are entered as a list of sub-dictionaries, which indicate the type of averages to perform, and can be updated during the calculation. The current options include:
class fieldAverageItem
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the form:
class fieldCoordinateSystemTransform
This function object transforms a user-specified selection of fields from global Cartesian co-ordinates to a local co-ordinate system. The fields are run-time modifiable.
class fieldMinMax
This function object calculates the value and location of scalar minimim and maximum for a list of user-specified fields. For variables with a rank greater than zero, either the min/max of a component value or the magnitude is reported. When operating in parallel, the processor owning the value is also given.
class forceCoeffs
This function object extends the Foam::forces function object by providing lift, drag and moment coefficients. The data can optionally be output into bins, defined in a given direction.
class forces
This function object calculates the forces and moments by integrating the pressure and skin-friction forces over a given list of patches.
class grad
This function object calculates the gradient of a field. The operation is limited to scalar and vector volume or surface fields, and the output is a volume vector or tensor field.
class histogram
Write the volume-weighted histogram of a volScalarField.
class Lambda2
This function object calculates and outputs the second largest eigenvalue of the sum of the square of the symmetrical and anti-symmetrical parts of the velocity gradient tensor.
class mag
This function object calculates the magnitude of a field. The operation can be applied to any volume or surface fieldsm and the output is a volume or surface scalar field.
class nearWallFields
This function object samples near-patch volume fields.
class partialWrite
This function object allows user-selected fields/registered objects to be written at a custom write interval. The interval is given in terms of number of overall dumps.
class Peclet
This function object calculates and outputs the Peclet number as a surfaceScalarField.
class pressureTools
This function object includes tools to manipulate the pressure into different forms. These currently include:
class processorField
This function object writes a scalar field whose value is the local processor ID. The output field name is 'processorID'.
class Q
This function object calculates and outputs the second invariant of the velocity gradient tensor [1/s^2].
class readFields
This function object reads fields from the time directories and adds them to the mesh database for further post-processing.
class regionSizeDistribution
This function object creates a size distribution via interrogating a continuous phase fraction field.
class removeRegisteredObject
This function object removes registered objects if present in the database.
class residuals
This function object writes out the initial residual for specified fields.
class scalarTransport
This function object evolves a passive scalar transport equation. The field in ininitially zero, to which sources are added. The field name is assigned the name of the function object. Boundary conditions are automatically applied, based on the velocity boundary conditions.
class setTimeStepFunctionObject
Overrides the timeStep. Can only be used with solvers with adjustTimeStep control (e.g. pimpleFoam). Makes no attempt to cooperate with other timeStep 'controllers' (maxCo, other functionObjects). Supports 'enabled' flag but none of othe other ones 'timeStart', 'timeEnd', 'outputControl' etc.
class streamLine
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field.
class surfaceInterpolateFields
class systemCall
This function object executes system calls, entered in the form of a string lists. Calls can be made at the following points in the calculation:
class timeActivatedFileUpdate
Performs a file copy/replacement once a specified time has been reached.
class turbulenceFields
This function object stores turbulence fields on the mesh database for further manipulation.
class vorticity
This function object calculates the vorticity, the curl of the velocity.
class wallBoundedStreamLine
This function object generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
class wallShearStress
This function object evaluates and outputs the shear stress at wall patches. The result is written as a volVectorField to time directories as field 'wallShearStress'.
class writeDictionary
This function object writes dictionaries on start-up, and on change.
class writeRegisteredObject
This function object allows specification of different writing frequency of objects registered to the database. It has similar functionality as the main time database through the outputControl setting:
class yPlus
Evaluates and outputs turbulence y+ for models. Values written to time directories as field 'yPlus'.
Functions
defineTypeNameAndDebug (div, 0)
defineTypeNameAndDebug (fieldAverage, 0)
Istream & operator>> (Istream &, fieldAverageItem &)
Ostream & operator<< (Ostream &, const fieldAverageItem &)
defineTypeNameAndDebug (fieldCoordinateSystemTransform, 0)
defineTypeNameAndDebug (fieldMinMax, 0)
defineTypeNameAndDebug (grad, 0)
defineTypeNameAndDebug (histogram, 0)
defineTypeNameAndDebug (mag, 0)
defineTypeNameAndDebug (nearWallFields, 0)
defineTypeNameAndDebug (processorField, 0)
defineTypeNameAndDebug (readFields, 0)
defineTypeNameAndDebug (regionSizeDistribution, 0)
defineTypeNameAndDebug (streamLine, 0)
defineTypeNameAndDebug (surfaceInterpolateFields, 0)
defineTypeNameAndDebug (wallBoundedStreamLine, 0)
defineTypeNameAndDebug (forceCoeffs, 0)
defineTypeNameAndDebug (forces, 0)
defineTypeNameAndDebug (pressureTools, 0)
defineTypeNameAndDebug (wallShearStress, 0)
defineTypeNameAndDebug (cloudInfo, 0)
defineTypeNameAndDebug (abort, 0)
defineTypeNameAndDebug (blendingFactor, 0)
defineTypeNameAndDebug (CourantNo, 0)
defineTypeNameAndDebug (dsmcFields, 0)
defineTypeNameAndDebug (Lambda2, 0)
defineTypeNameAndDebug (partialWrite, 0)
defineTypeNameAndDebug (Peclet, 0)
defineTypeNameAndDebug (Q, 0)
defineTypeNameAndDebug (removeRegisteredObject, 0)
defineTypeNameAndDebug (residuals, 0)
defineTypeNameAndDebug (scalarTransport, 0)
defineTypeNameAndDebug (setTimeStepFunctionObject, 0)
addToRunTimeSelectionTable (functionObject, setTimeStepFunctionObject, dictionary)
defineTypeNameAndDebug (systemCall, 0)
defineTypeNameAndDebug (timeActivatedFileUpdate, 0)
defineTypeNameAndDebug (turbulenceFields, 0)
defineTypeNameAndDebug (vorticity, 0)
defineTypeNameAndDebug (writeDictionary, 0)
defineTypeNameAndDebug (writeRegisteredObject, 0)
defineTypeNameAndDebug (yPlus, 0)
Detailed Description
Namespace for functionObjects.
OpenFOAM includes a collection of functionObjects selected by the user at run-time to manipulate the simulation and provide mechanisms to extract field and derived quantities. Alternatively, the same actions can be executed after the simulation using the execFlowFunctionObjects utility.
FunctionObjects are selected by additional entries in the $FOAM_CASE/system/controlDict dictionary. Each object is listed in the functions sub-dictionary, e.g. to select the functionObjectType functionObject the following entry would be specified:
    functions
    {
        myFunctionObject    // Name of functionObject entry
        {
            type                functionObjectType;
            functionObjectLibs  ("libMyFunctionObjectlib.so");
            region              defaultRegion;
            enabled             yes;
            timeStart           0;
            timeEnd             10;
            outputControl       outputTime;
            outputInterval      1;
            ...
        }
    }
Where:
Property Description Required Default value
type Type of function object yes
functionObjectLibs Libraries containing object implementation yes
region Name of region for multi-region cases no
enabled On/off switch no yes
timeStart Start time no
timeEnd End time no
outputControl Either 'outputTime' or 'timeStep' no timeStep
outputInterval Steps between output for outputControl=timeStep no 1
The sub-dictionary name myFunctionObject is chosen by the user, and is typically used as the name of the output directory for any data written by the functionObject. The type entry defines the type of function object properties that follow. FunctionObjects are packaged into separate libraries and the libs entry is used to specify which library should be loaded.
Function Documentation
Foam::functionObjects::defineTypeNameAndDebug (div , 0)
Foam::functionObjects::defineTypeNameAndDebug (fieldAverage , 0)
Foam::Istream & operator>> (Istream & is, fieldAverageItem & faItem)
Definition at line 70 of file fieldAverageItemIO.C.
References IOstream::check(), fieldAverageItem::EXT_MEAN, fieldAverageItem::EXT_PRIME2MEAN, entry::keyword(), dictionary::lookup(), dictionary::lookupOrDefault(), and dictionary::null.
Foam::Ostream & operator<< (Ostream & os, const fieldAverageItem & faItem)
Definition at line 107 of file fieldAverageItemIO.C.
References token::BEGIN_BLOCK, IOstream::check(), token::END_BLOCK, token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Foam::functionObjects::defineTypeNameAndDebug (fieldCoordinateSystemTransform , 0)
Foam::functionObjects::defineTypeNameAndDebug (fieldMinMax , 0)
Foam::functionObjects::defineTypeNameAndDebug (grad , 0)
Foam::functionObjects::defineTypeNameAndDebug (histogram , 0)
Foam::functionObjects::defineTypeNameAndDebug (mag , 0)
Foam::functionObjects::defineTypeNameAndDebug (nearWallFields , 0)
Foam::functionObjects::defineTypeNameAndDebug (processorField , 0)
Foam::functionObjects::defineTypeNameAndDebug (readFields , 0)
Foam::functionObjects::defineTypeNameAndDebug (regionSizeDistribution , 0)
Foam::functionObjects::defineTypeNameAndDebug (streamLine , 0)
Foam::functionObjects::defineTypeNameAndDebug (surfaceInterpolateFields , 0)
Foam::functionObjects::defineTypeNameAndDebug (wallBoundedStreamLine , 0)
Foam::functionObjects::defineTypeNameAndDebug (forceCoeffs , 0)
Foam::functionObjects::defineTypeNameAndDebug (forces , 0)
Foam::functionObjects::defineTypeNameAndDebug (pressureTools , 0)
Foam::functionObjects::defineTypeNameAndDebug (wallShearStress , 0)
Foam::functionObjects::defineTypeNameAndDebug (cloudInfo , 0)
Foam::functionObjects::defineTypeNameAndDebug (abort , 0)
Foam::functionObjects::defineTypeNameAndDebug (blendingFactor , 0)
Foam::functionObjects::defineTypeNameAndDebug (CourantNo , 0)
Foam::functionObjects::defineTypeNameAndDebug (dsmcFields , 0)
Foam::functionObjects::defineTypeNameAndDebug (Lambda2 , 0)
Foam::functionObjects::defineTypeNameAndDebug (partialWrite , 0)
Foam::functionObjects::defineTypeNameAndDebug (Peclet , 0)
Foam::functionObjects::defineTypeNameAndDebug (Q , 0)
Foam::functionObjects::defineTypeNameAndDebug (removeRegisteredObject , 0)
Foam::functionObjects::defineTypeNameAndDebug (residuals , 0)
Foam::functionObjects::defineTypeNameAndDebug (scalarTransport , 0)
Foam::functionObjects::defineTypeNameAndDebug (setTimeStepFunctionObject , 0)
Foam::functionObjects::addToRunTimeSelectionTable (functionObject , setTimeStepFunctionObject , dictionary)
Foam::functionObjects::defineTypeNameAndDebug (systemCall , 0)
Foam::functionObjects::defineTypeNameAndDebug (timeActivatedFileUpdate , 0)
Foam::functionObjects::defineTypeNameAndDebug (turbulenceFields , 0)
Foam::functionObjects::defineTypeNameAndDebug (vorticity , 0)
Foam::functionObjects::defineTypeNameAndDebug (writeDictionary , 0)
Foam::functionObjects::defineTypeNameAndDebug (writeRegisteredObject , 0)
Foam::functionObjects::defineTypeNameAndDebug (yPlus , 0)