OpenFOAM: src/OpenFOAM/include/setConstantMeshDictionaryIO.H File Reference
setConstantMeshDictionaryIO.H File Reference
Functions
if (args.optionFound("dict"))
IOobject dictIO (dictName, runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)
if (dictPath.size())
Variables
fileName dictPath = ""
Function Documentation
if() [1/2]
if (args. optionFound"dict")
Definition at line 2 of file setConstantMeshDictionaryIO.H.
References args, dictIO(), dictName(), dictPath, Foam::isDir(), and mesh.
dictIO()
IOobject dictIO (dictName , runTime. constant(), mesh , IOobject::MUST_READ_IF_MODIFIED , IOobject::NO_WRITE)
Referenced by if().
if() [2/2]
if (dictPath. size())
Definition at line 20 of file setConstantMeshDictionaryIO.H.
References dictIO(), dictPath, and mesh.
Variable Documentation
dictPath
fileName dictPath = ""
Definition at line 1 of file setConstantMeshDictionaryIO.H.
Referenced by if().