OpenFOAM: src/OpenFOAM/include/setRootCase.H File Reference
setRootCase.H File Reference
Functions
if (!args.checkRootCase())
Variables
Foam::argList args (argc, argv)
Function Documentation
if()
if (!args. checkRootCase())
Definition at line 2 of file setRootCase.H.
References error::exit(), and Foam::FatalError.
Variable Documentation
args
Foam::argList args(argc, argv)
Referenced by AC3DsurfaceFormatCore::cueToOrDie(), forAll(), if(), AC3DsurfaceFormat< Face >::read(), functionObjectList::readFunctionObject(), Foam::readUpto(), zoltanRenumber::renumber(), and timeSelector::select0().