OpenFOAM: src/renumber/zoltanRenumber/zoltanRenumber.C File Reference
zoltanRenumber.C File Reference
Namespaces
Foam
Namespace for OpenFOAM.
Functions
defineTypeNameAndDebug (zoltanRenumber, 0)
addToRunTimeSelectionTable (renumberMethod, zoltanRenumber, dictionary)
static int get_number_of_vertices (void *data, int *ierr)
static void get_vertex_list (void *data, int sizeGID, int sizeLID, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int wgt_dim, float *obj_wgts, int *ierr)
static void get_num_edges_list (void *data, int sizeGID, int sizeLID, int num_obj, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int *numEdges, int *ierr)
static void get_edge_list (void *data, int sizeGID, int sizeLID, int num_obj, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int *num_edges, ZOLTAN_ID_PTR nborGID, int *nborProc, int wgt_dim, float *ewgts, int *ierr)
static int get_mesh_dim (void *data, int *ierr)
static void get_geom_list (void *data, int num_gid_entries, int num_lid_entries, int num_obj, ZOLTAN_ID_PTR global_ids, ZOLTAN_ID_PTR local_ids, int num_dim, double *geom_vec, int *ierr)
Detailed Description
Original source file zoltanRenumber.C
Definition in file zoltanRenumber.C.
Function Documentation
get_number_of_vertices()
static int get_number_of_vertices (void * data, int * ierr) static
Definition at line 77 of file zoltanRenumber.C.
References mesh, and primitiveMesh::nCells().
Referenced by zoltanRenumber::renumber().
get_vertex_list()
static void get_vertex_list (void * data, int sizeGID, int sizeLID, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int wgt_dim, float * obj_wgts, int * ierr) static
Definition at line 85 of file zoltanRenumber.C.
References mesh, and primitiveMesh::nCells().
Referenced by zoltanRenumber::renumber().
get_num_edges_list()
static void get_num_edges_list (void * data, int sizeGID, int sizeLID, int num_obj, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int * numEdges, int * ierr) static
Definition at line 108 of file zoltanRenumber.C.
References primitiveMesh::cells(), forAll, primitiveMesh::isInternalFace(), mesh, n, and primitiveMesh::nCells().
Referenced by zoltanRenumber::renumber().
get_edge_list()
static void get_edge_list (void * data, int sizeGID, int sizeLID, int num_obj, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int * num_edges, ZOLTAN_ID_PTR nborGID, int * nborProc, int wgt_dim, float * ewgts, int * ierr) static
Definition at line 140 of file zoltanRenumber.C.
References primitiveMesh::cells(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, primitiveMesh::isInternalFace(), mesh, n, and primitiveMesh::nCells().
Referenced by zoltanRenumber::renumber().
get_mesh_dim()
static int get_mesh_dim (void * data, int * ierr) static
Definition at line 200 of file zoltanRenumber.C.
References get_geom_list(), mesh, and polyMesh::nSolutionD().
Referenced by zoltanRenumber::renumber().
get_geom_list()
static void get_geom_list (void * data, int num_gid_entries, int num_lid_entries, int num_obj, ZOLTAN_ID_PTR global_ids, ZOLTAN_ID_PTR local_ids, int num_dim, double * geom_vec, int * ierr) static
Definition at line 209 of file zoltanRenumber.C.
References primitiveMesh::cellCentres(), mesh, primitiveMesh::nCells(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, polyMesh::nSolutionD(), p, and polyMesh::solutionD().
Referenced by get_mesh_dim(), and zoltanRenumber::renumber().