OpenFOAM: src/thermophysicalModels/radiation/include/createIncompressibleRadiationModel.H File Reference
createIncompressibleRadiationModel.H File Reference
Functions
autoPtr< radiation::radiationModel > radiation (radiation::radiationModel::New(T))
dimensionedScalar rhoCpRef ("rhoCpRef", dimDensity *dimEnergy/dimMass/dimTemperature, 1.0)
if (radiation->radiation())
Function Documentation
radiation()
autoPtr<radiation::radiationModel> radiation (radiation::radiationModel::New(T))
Referenced by fvDOM::a(), radiationCoupledBase::emissivity(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::write(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::write(), and greyDiffusiveRadiationMixedFvPatchScalarField::write().
rhoCpRef()
dimensionedScalar rhoCpRef ("rhoCpRef" , dimDensity *dimEnergy/dimMass/ dimTemperature, 1. 0)
Referenced by if().
if()
if (radiation-> radiation())
Definition at line 13 of file createIncompressibleRadiationModel.H.
References Foam::dimDensity, Foam::dimSpecificHeatCapacity, and rhoCpRef().