OpenFOAM: applications/utilities/mesh/conversion/kivaToFoam/readKivaGrid.H File Reference
readKivaGrid.H File Reference
Functions
ifstream kivaFile (kivaFileName.c_str())
if (!kivaFile.good())
pointField points (nPoints)
labelList idface (nPoints)
labelList fv (nPoints)
for (label i=0;i< nPoints;i++)
labelList i1tab (nPoints)
labelList i3tab (nPoints)
labelList i8tab (nPoints)
labelList idreg (nPoints)
labelList f (nPoints)
labelList bcl (nPoints)
labelList bcf (nPoints)
labelList bcb (nPoints)
if (mTable==0)
labelList imtab (nPoints)
labelList jmtab (nPoints)
labelList kmtab (nPoints)
face quadFace (4)
face triFace (3)
if (pFaces[LINER].size() &&pFaces[LINER][0].size() &&pFaces[CYLINDERHEAD].size() &&pFaces[CYLINDERHEAD][0].size())
if (pFaces[WEDGE].size() &&pFaces[WEDGE][0].size())
faceListList boundary (nPatches)
wordList patchNames (nPatches)
wordList patchTypes (nPatches)
labelList pointLabels (nPoints, -1)
forAll (cellShapes, celli)
forAll (pointLabels, pointi)
points setSize (newPointi)
forAll (boundary, patchi)
preservePatchTypes (runTime, runTime.constant(), polyMesh::meshSubDir, patchNames, patchDicts, defaultFacesName, defaultFacesType)
forAll (patchNames, patchi)
polyMesh pShapeMesh (IOobject(polyMesh::defaultRegion, runTime.constant(), runTime), xferMove(points), cellShapes, boundary, patchNames, patchDicts, defaultFacesName, defaultFacesType)
Variables
Info<< "Reading kiva grid from file "<< kivaFileName<< endl;char title[120];kivaFile.getline(title, 120, '\n');label nPoints, nCells, nRegs;kivaFile > nCells nPoints nRegs
label i4
label nBfaces = 0
label mTable
Info<< "Finished reading KIVA file"<< endl;cellShapeList cellShapes(nPoints);labelList cellZoning(nPoints, -1);const cellModel &hex=*(cellModeller::lookup("hex"));labelList hexLabels(8);label activeCells=0;labelList pointMap(nPoints);forAll(pointMap, i){ pointMap[i]=i;}for(label i=0;i< nPoints;i++){ if(f[i] > 0.0) { hexLabels[0]=i;hexLabels[1]=i1tab[i];hexLabels[2]=i3tab[i1tab[i]];hexLabels[3]=i3tab[i];hexLabels[4]=i8tab[i];hexLabels[5]=i1tab[i8tab[i]];hexLabels[6]=i3tab[i1tab[i8tab[i]]];hexLabels[7]=i3tab[i8tab[i]];cellShapes[activeCells]=cellShape(hex, hexLabels);edgeList edges=cellShapes[activeCells].edges();forAll(edges, ei) { if(edges[ei].mag(points)< SMALL) { label start=pointMap[edges[ei].start()];while(start !=pointMap[start]) { start=pointMap[start];} label end=pointMap[edges[ei].end()];while(end !=pointMap[end]) { end=pointMap[end];} label minLabel=min(start, end);pointMap[start]=pointMap[end]=minLabel;} } cellZoning[activeCells]=idreg[i];activeCells++;}}cellShapes.setSize(activeCells);cellZoning.setSize(activeCells);forAll(cellShapes, celli){ cellShape &cs=cellShapes[celli];forAll(cs, i) { cs[i]=pointMap[cs[i]];} cs.collapse();}label bcIDs[11]={-1, 0, 2, 4, -1, 5, -1, 6, 7, 8, 9};const label nBCs=12;const word *kivaPatchTypes[nBCs]={ &wallPolyPatch::typeName, &wallPolyPatch::typeName, &wallPolyPatch::typeName, &wallPolyPatch::typeName, &symmetryPolyPatch::typeName, &wedgePolyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &symmetryPolyPatch::typeName, &oldCyclicPolyPatch::typeName};enum patchTypeNames{ PISTON, VALVE, LINER, CYLINDERHEAD, AXIS, WEDGE, INFLOW, OUTFLOW, PRESIN, PRESOUT, SYMMETRYPLANE, CYCLIC};const char *kivaPatchNames[nBCs]={ "piston", "valve", "liner", "cylinderHead", "axis", "wedge", "inflow", "outflow", "presin", "presout", "symmetryPlane", "cyclic"};List< SLList< face > > pFaces [nBCs]
label nPatches = 0
word defaultFacesName = "defaultFaces"
word defaultFacesType = emptyPolyPatch::typeName
label nAddedPatches = 0
label newPointi = 0
PtrList< dictionary > patchDicts
Function Documentation
kivaFile()
ifstream kivaFile (kivaFileName. c_str())
Referenced by for(), and if().
if() [1/4]
if (!kivaFile. good())
Definition at line 3 of file readKivaGrid.H.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, kivaFile(), nPoints, and nRegs.
points()
pointField points (nPoints)
Referenced by for(), forAll(), and if().
idface()
labelList idface (nPoints)
Referenced by for(), and if().
fv()
labelList fv (nPoints)
Referenced by for(), if(), and NamedEnum< directionType, 3 >::names().
for()
for ()
Definition at line 23 of file readKivaGrid.H.
References bcb(), bcf(), bcl(), f(), fv(), i1tab(), i3tab(), i8tab(), idface(), idreg(), kivaFile(), and points().
i1tab()
labelList i1tab (nPoints)
Referenced by for(), and if().
i3tab()
labelList i3tab (nPoints)
Referenced by for(), and if().
i8tab()
labelList i8tab (nPoints)
Referenced by for(), and if().
idreg()
labelList idreg (nPoints)
Referenced by for(), and if().
f()
labelList f (nPoints)
Referenced by isoSurface::adaptPatchFields(), multivariateSurfaceInterpolationScheme< Type >::fieldTable::add(), singleProcessorFaceSetsConstraint::add(), singleProcessorFaceSetsConstraint::apply(), booleanSurface::booleanSurface(), primitiveMeshTools::boundaryFaceSkewness(), searchableBox::boundingSpheres(), PatchTools::calcBounds(), BrownianMotionForce< CloudType >::calcCoupled(), cellMatcher::calcEdgeAddressing(), coupledPolyPatch::calcFaceTol(), faceZone::calcFaceZonePatch(), cellMatcher::calcLocalFaces(), cellMatcher::calcPointFaceIndex(), primitiveMesh::calcPointOrder(), createShellMesh::calcPointRegions(), rotorDiskSource::calculate(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), cellMatcher::cellMatcher(), primitiveMesh::cellPoints(), repatchPolyTopoChanger::changeAnchorPoint(), primitiveMesh::checkCellsZipUp(), primitiveMesh::checkEdgeLength(), primitiveMesh::checkFacePyramids(), MeshedSurface< Foam::face >::checkFaces(), polyMeshTetDecomposition::checkFaceTets(), primitiveMesh::checkFaceVertices(), regIOobject::checkIn(), hexRef8::checkMesh(), edgeCollapser::checkMeshQuality(), PatchTools::checkOrientation(), searchableSurfaces::checkQuality(), triSurface::checkTriangles(), ensightPartFaces::classify(), isotropic::clone(), equilibrium::clone(), nonEquilibrium::clone(), Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), cellShape::collapsedFaces(), ORourkeCollision< CloudType >::collideSorted(), Foam::component(), processorLduInterface::compressedReceive(), polyMeshFilter::copyMesh(), inversePointDistanceDiffusivity::correct(), CentredFitScheme< Type, Polynomial, Stencil >::correction(), pointLinear< Type >::correction(), removePoints::countPointUsage(), wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), particle< Type >::crossEdgeConnectedFace(), wallBoundedParticle::currentEdge(), cyclicACMILduInterfaceField::cyclicACMILduInterfaceField(), cyclicAMILduInterfaceField::cyclicAMILduInterfaceField(), cyclicLduInterfaceField::cyclicLduInterfaceField(), decompositionMethod::decompose(), Dual< Type >::Dual(), dynamicRefineFvMesh::dynamicRefineFvMesh(), PatchTools::edgeOwner(), directionInfo::edgeToFaceIndex(), directionInfo::enterDomain(), turbulenceFields::execute(), extrudePatchMesh::extrudePatchMesh(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), hexRef8::faceLevel(), mappedPatchBase::facePoint(), primitiveMeshTools::facePyramidVolume(), cellModel::faces(), primitiveMeshTools::faceSkewness(), polyMeshTetDecomposition::faceTetIndices(), tetIndices::faceTri(), tetIndices::faceTriIs(), fanFvPatchField< Type >::fanFvPatchField(), polyMeshTetDecomposition::findBasePoint(), localPointRegion::findDuplicateFaces(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::findFaceDirs(), sampledSet::findNearFace(), polyMeshTetDecomposition::findSharedBasePoint(), polyMeshTetDecomposition::findTet(), cellPointWeight::findTetrahedron(), cellPointWeight::findTriangle(), for(), forAll(), pairPotentialList::force(), pairPotential::force(), isoSurface::generateFaceTriPoints(), coupledPolyPatch::getAnchorPoints(), surfaceFieldValue::getFieldValues(), surfaceSets::getHangingCells(), boundaryMesh::getNearest(), boundaryMesh::getNTris(), cellDistFuncs::getPointNeighbours(), coupledPolyPatch::getRotation(), wallBoundedParticle::hitProcessorPatch(), particle< Type >::hitWallFaces(), if(), FreeStream< CloudType >::inflow(), processorPolyPatch::initUpdateMesh(), interpolationCellPoint< Foam::Vector >::interpolate(), sampledPlane::interpolateField(), sampledIsoSurfaceCell::interpolateField(), sampledThresholdCellFaces::interpolateField(), sampledPatch::interpolateField(), meshToMesh0::interpolateField(), Foam::interpolatePointToCell(), meshRefinement::intersectedPoints(), face::intersection(), IOField< vector >::IOField(), noiseFFT::Ldelta(), Foam::mag(), Foam::magSqr(), primitiveMesh::makeFaceCentresAndAreas(), Field< Foam::Vector2D >::map(), noiseFFT::meanPf(), polyMeshAdder::mergePoints(), polyTopoChange::modifyFace(), Moment< Type >::Moment(), MPPICParcel< ParcelType >::move(), molecule::move(), regionModel1D::moveMesh(), primitiveMesh::movePoints(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), NamedEnum< directionType, 3 >::names(), face::nearestPointClassify(), cellCuts::nonAnchorPoints(), tetIndices::oldFaceTri(), tetIndices::oldTet(), ConstMatrixBlock< MatrixType >::operator Field< cmptType >(), MatrixBlock< MatrixType >::operator Field< cmptType >(), spatialTransform::transpose::operator spatialTensor(), spatialTransform::dual::operator spatialTensor(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), listPlusEqOp< T >::operator()(), ifEqEqOp< value >::operator()(), nearestEqOp::operator()(), FieldMapper::operator()(), offsetOp< face >::operator()(), Foam::operator/(), Field< Foam::Vector2D >::operator/=(), Foam::operator<<(), Foam::operator>>(), Foam::operator^(), oldCyclicPolyPatch::order(), distributedTriSurfaceMesh::overlappingSurface(), Pair< word >::Pair(), CollisionRecordList< vector, vector >::pairAccessed(), CollisionRecordList< vector, vector >::pairData(), CollisionRecordList< vector, vector >::pairOrigIdOfOther(), CollisionRecordList< vector, vector >::pairOrigProcOfOther(), Foam::parseNASCoord(), noiseFFT::Pdelta(), polyMesh::pointInCell(), primitiveMesh::pointInCell(), PatchTools::pointNormals(), Foam::pow(), processorLduInterfaceField::processorLduInterfaceField(), face::ray(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), boundaryMesh::read(), STARCD::readCells(), DimensionedField< Type, Foam::pointMesh >::readField(), CollidingParcel< ParcelType >::readFields(), SLListBase::removeHead(), DLListBase::removeHead(), face::reverseFace(), Field< Foam::Vector2D >::rmap(), noiseFFT::RMSmeanPf(), decompositionModel::selectIO(), IOstream::setBad(), hexRef8::setInstance(), removeCells::setRefinement(), duplicatePoints::setRefinement(), perfectInterface::setRefinement(), removePoints::setRefinement(), createShellMesh::setRefinement(), removeFaces::setRefinement(), addPatchCellLayer::setRefinement(), ThermoCloud< Foam::DSMCCloud >::sigmap(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotionSolver::solve(), rigidBodyMeshMotion::solve(), PatchTools::sortedEdgeFaces(), meshRefinement::splitFaces(), Foam::sqr(), AMIInterpolation< SourcePatch, TargetPatch >::srcPointFace(), MeshedSurface< Foam::face >::stitchFaces(), PatchTools::subsetMap(), UnsortedMeshedSurface< Face >::subsetMesh(), MeshedSurface< Foam::face >::subsetMesh(), SVD::SVD(), swapec(), syncTools::syncEdgeMap(), tetIndices::tet(), tetIndices::tetIndices(), particle< Type >::tetNeighbour(), tetOverlapVolume::tetOverlapVolume(), AMIInterpolation< SourcePatch, TargetPatch >::tgtPointFace(), thermo< Thermo, Type >::thermo(), Time::Time(), fileName::toAbsolute(), wallBoundedParticle::trackToEdge(), particle< Type >::trackToFace(), Foam::transformFieldMask(), polyMeshTetDecomposition::triangleTetIndices(), boundaryMesh::triangulate(), MeshedSurface< Foam::face >::triangulate(), boundaryMesh::triangulateLocal(), triFace::triFaceFace(), triSurface::triSurfInstance(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), directionInfo::updateCell(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), patchFaceOrientation::updateEdge(), patchEdgeFaceRegions::updateEdge(), patchFaceOrientation::updateFace(), patchEdgeFaceRegions::updateFace(), patchInjectionBase::updateMesh(), processorPolyPatch::updateMesh(), removePoints::updateMesh(), vtkUnstructuredReader::vtkUnstructuredReader(), CollisionRecordList< vector, vector >::wallAccessed(), CollisionRecordList< vector, vector >::wallData(), wallLayerCells::wallLayerCells(), CollisionRecordList< vector, vector >::wallPRel(), face::which(), X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), AveragingMethod< Foam::Vector >::write(), forces::writeBins(), ensightPartFaces::writeConnectivity(), CollidingParcel< ParcelType >::writeFields(), fieldAverage::writeFieldType(), forces::writeFileHeader(), Foam::meshTools::writeOBJ(), coupledPolyPatch::writeOBJ(), alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm(), Dual< Type >::~Dual(), ensightPartCells::~ensightPartCells(), ensightPartFaces::~ensightPartFaces(), ODESolver::~ODESolver(), and Stochastic< CloudType >::~Stochastic().
bcl()
labelList bcl (nPoints)
Referenced by for().
bcf()
labelList bcf (nPoints)
Referenced by for().
bcb()
labelList bcb (nPoints)
Referenced by for().
if() [2/4]
if (mTable = = 0)
Definition at line 77 of file readKivaGrid.H.
References cellShapes, Foam::endl(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, forAll(), Foam::hex(), i1tab(), i3tab(), i8tab(), idreg(), imtab(), Foam::Info, jmtab(), kivaFile(), kmtab(), lookup(), Foam::mag(), Foam::min(), nPoints, and points().
imtab()
labelList imtab (nPoints)
Referenced by if().
jmtab()
labelList jmtab (nPoints)
Referenced by if().
kmtab()
labelList kmtab (nPoints)
Referenced by if().
quadFace()
face quadFace (4)
Referenced by if().
triFace()
face triFace (3)
Referenced by tetCell::face(), tetIndices::faceTriIs(), if(), momentOfInertia::massPropertiesShell(), momentOfInertia::massPropertiesSolid(), OBJsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), STLsurfaceFormat< Face >::read(), MeshedSurface< Foam::face >::transcribe(), MeshedSurface< Foam::face >::triangulate(), and patchInjectionBase::updateMesh().
if() [3/4]
if (pFaces. size() &&pFaces.size() &&pFaces.size() &&pFaces.size()[LINER][LINER][0][CYLINDERHEAD][CYLINDERHEAD][0])
Definition at line 321 of file readKivaGrid.H.
References Foam::endl(), forAll(), forAllConstIter(), Foam::Info, Foam::min(), and points().
if() [4/4]
if (pFaces. size() &&pFaces.size()[WEDGE][WEDGE][0])
Definition at line 416 of file readKivaGrid.H.
References boundary(), Foam::degToRad(), forAllIter, patchNames(), patchTypes(), points(), and Foam::tan().
boundary()
faceListList boundary (nPatches)
Referenced by forAll(), if(), singleCellFvMesh::interpolate(), volPointInterpolation::interpolateBoundaryField(), mappedFlowRateFvPatchVectorField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
patchNames()
wordList patchNames (nPatches)
Referenced by polyBoundaryMesh::checkDefinition(), extrudePatchMesh::extrudePatchMesh(), forAll(), if(), cellDistFuncs::mesh(), polyBoundaryMesh::mesh(), patchInjection::patchInjection(), sampledPatchInternalField::print(), sampledPatch::print(), thermalBaffleFvPatchScalarField::rmap(), and fvMeshSubset::setLargeCellSubset().
patchTypes()
wordList patchTypes (nPatches)
Referenced by extrudePatchMesh::extrudePatchMesh(), if(), and thermalBaffleFvPatchScalarField::rmap().
pointLabels()
labelList pointLabels (nPoints , - 1)
Referenced by polyTopoChange::addMesh(), edgeCollapser::checkMeshQuality(), cellModel::clone(), cell::points(), globalMeshData::sharedPointGlobalLabels(), and globalMeshData::sharedPoints().
forAll() [1/4]
forAll (cellShapes , celli)
Definition at line 492 of file readKivaGrid.H.
Referenced by forAll(), and if().
forAll() [2/4]
forAll (pointLabels , pointi)
Definition at line 502 of file readKivaGrid.H.
References forAll(), newPointi, and points().
setSize()
points setSize (newPointi)
Referenced by PtrList< MRFZone >::append(), DynamicList< Foam::Tensor >::append(), List< Field< scalar > >::append(), Field< Foam::Vector2D >::autoMap(), cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), CloudFunctionObjectList< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::CloudFunctionObjectList(), coalCloudList::coalCloudList(), CompactIOList< face, label >::CompactIOList(), nearWallDist::correct(), DynamicList< Foam::Tensor >::erase(), Field< Foam::Vector2D >::Field(), processorFvPatchField< Type >::initEvaluate(), InjectionModelList< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::InjectionModelList(), IOField< vector >::IOField(), IOList< labelList >::IOList(), IOMap< T >::IOMap(), Field< Foam::Vector2D >::map(), List< Field< scalar > >::newElmt(), DynamicList< Foam::Tensor >::operator()(), PtrList< MRFZone >::operator=(), ParticleForceList< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::ParticleForceList(), profileModelList::profileModelList(), PtrListDictionary< phaseModel >::PtrListDictionary(), PtrList< MRFZone >::read(), GeometricField< Type, PatchField, GeoMesh >::Boundary::readField(), regionModelFunctionObjectList::regionModelFunctionObjectList(), DynamicList< Foam::Tensor >::reserve(), PtrList< MRFZone >::resize(), DynamicList< Foam::Tensor >::resize(), UPtrList< Foam::Field< Type > >::resize(), List< Field< scalar > >::resize(), DynamicList< Foam::Tensor >::setCapacity(), sampledSet::setSamples(), SquareMatrix< cmptType >::setSize(), DynamicList< Foam::Tensor >::setSize(), List< Field< scalar > >::setSize(), DynamicList< Foam::Tensor >::shrink(), UnsortedMeshedSurface< Face >::size(), and uniformInterpolationTable< scalar >::uniformInterpolationTable().
forAll() [3/4]
forAll (boundary , patchi)
Definition at line 524 of file readKivaGrid.H.
References f(), forAll(), and patchi.
preservePatchTypes()
preservePatchTypes (runTime , runTime. constant(), polyMesh::meshSubDir , patchNames , patchDicts , defaultFacesName , defaultFacesType)
forAll() [4/4]
forAll (patchNames , patchi)
Definition at line 549 of file readKivaGrid.H.
References boundary(), cellShapes, defaultFacesName, defaultFacesType, Foam::endl(), Foam::Info, patchDicts, patchi, patchNames(), points(), pShapeMesh(), and Foam::xferMove().
pShapeMesh()
polyMesh pShapeMesh (IOobject(polyMesh::defaultRegion, runTime.constant(), runTime) , xferMove(points) , cellShapes , boundary , patchNames , patchDicts , defaultFacesName , defaultFacesType)
Referenced by forAll().
Variable Documentation
nRegs
Info<< "Reading kiva grid from file " << kivaFileName << endl;char title[120];kivaFile.getline(title, 120, '\n');label nPoints, nCells, nRegs;kivaFile > nCells nPoints nRegs
Definition at line 17 of file readKivaGrid.H.
Referenced by if().
i4
label i4
Definition at line 20 of file readKivaGrid.H.
nBfaces
label nBfaces = 0
Definition at line 45 of file readKivaGrid.H.
mTable
kivaFile mTable
Definition at line 74 of file readKivaGrid.H.
pFaces
Info<< "Finished reading KIVA file" << endl;cellShapeList cellShapes(nPoints);labelList cellZoning(nPoints, -1);const cellModel& hex = *(cellModeller::lookup("hex"));labelList hexLabels(8);label activeCells = 0;labelList pointMap(nPoints);forAll(pointMap, i){ pointMap[i] = i;}for (label i=0; i<nPoints; i++){ if (f[i] > 0.0) { hexLabels[0] = i; hexLabels[1] = i1tab[i]; hexLabels[2] = i3tab[i1tab[i]]; hexLabels[3] = i3tab[i]; hexLabels[4] = i8tab[i]; hexLabels[5] = i1tab[i8tab[i]]; hexLabels[6] = i3tab[i1tab[i8tab[i]]]; hexLabels[7] = i3tab[i8tab[i]]; cellShapes[activeCells] = cellShape(hex, hexLabels); edgeList edges = cellShapes[activeCells].edges(); forAll(edges, ei) { if (edges[ei].mag(points) < SMALL) { label start = pointMap[edges[ei].start()]; while (start != pointMap[start]) { start = pointMap[start]; } label end = pointMap[edges[ei].end()]; while (end != pointMap[end]) { end = pointMap[end]; } label minLabel = min(start, end); pointMap[start] = pointMap[end] = minLabel; } } cellZoning[activeCells] = idreg[i]; activeCells++; }}cellShapes.setSize(activeCells);cellZoning.setSize(activeCells);forAll(cellShapes, celli){ cellShape& cs = cellShapes[celli]; forAll(cs, i) { cs[i] = pointMap[cs[i]]; } cs.collapse();}label bcIDs[11] = {-1, 0, 2, 4, -1, 5, -1, 6, 7, 8, 9};const label nBCs = 12;const word* kivaPatchTypes[nBCs] ={ &wallPolyPatch::typeName, &wallPolyPatch::typeName, &wallPolyPatch::typeName, &wallPolyPatch::typeName, &symmetryPolyPatch::typeName, &wedgePolyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &polyPatch::typeName, &symmetryPolyPatch::typeName, &oldCyclicPolyPatch::typeName};enum patchTypeNames{ PISTON, VALVE, LINER, CYLINDERHEAD, AXIS, WEDGE, INFLOW, OUTFLOW, PRESIN, PRESOUT, SYMMETRYPLANE, CYCLIC};const char* kivaPatchNames[nBCs] ={ "piston", "valve", "liner", "cylinderHead", "axis", "wedge", "inflow", "outflow", "presin", "presout", "symmetryPlane", "cyclic"};List<SLList<face> > pFaces[nBCs]
Definition at line 235 of file readKivaGrid.H.
Referenced by singleProcessorFaceSetsConstraint::add(), singleProcessorFaceSetsConstraint::apply(), Foam::meshTools::calcBoxPointNormals(), polyMeshTetDecomposition::cellTetIndices(), particle< Type >::crossEdgeConnectedFace(), decompositionMethod::decompose(), polyMeshTetDecomposition::faceTetIndices(), tetIndices::faceTri(), tetIndices::faceTriIs(), cellClassification::fillRegionPoints(), polyMeshTetDecomposition::findBasePoint(), localPointRegion::findDuplicateFaces(), polyMeshTetDecomposition::findSharedBasePoint(), polyMeshTetDecomposition::findTet(), cellPointWeight::findTetrahedron(), cellLooper::getVertFacesNonEdge(), treeDataFace::getVolumeType(), particle< Type >::hitWallFaces(), if(), interpolationCellPoint< Foam::Vector >::interpolate(), volPointInterpolation::interpolateBoundaryField(), NamedEnum< directionType, 3 >::names(), tetIndices::oldFaceTri(), tetIndices::oldTet(), listPlusEqOp< T >::operator()(), oldCyclicPolyPatch::order(), boundaryMesh::patchify(), primitiveMesh::pointCells(), PatchTools::pointNormals(), Foam::polyMeshZipUpCells(), hexRef8::setInstance(), perfectInterface::setRefinement(), removePoints::setRefinement(), hexRef8::setUnrefinement(), meshRefinement::splitMesh(), tetIndices::tet(), tetIndices::tetIndices(), particle< Type >::tetNeighbour(), triSurfaceTools::trackToEdge(), particle< Type >::trackToFace(), and dynamicRefineFvMesh::unrefine().
nPatches
label nPatches = 0
Definition at line 402 of file readKivaGrid.H.
Referenced by addPatchCellLayer::calcSidePatch(), PointEdgeWave< Type, TrackingData >::countPatchType(), addPatchCellLayer::layerFaces(), Foam::parseNASCoord(), STARCD::readBoundary(), Foam::readUpto(), polyTopoChange::setNumPatches(), USERD_get_gold_part_build_info(), USERD_get_gold_variable_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_nsided_conn(), USERD_get_part_coords(), USERD_get_part_element_ids_by_type(), USERD_get_part_elements_by_type(), USERD_get_part_node_ids(), USERD_get_var_by_component(), USERD_set_filenames(), USERD_set_time_set_and_step(), and fvMeshTools::zeroPatchFields().
defaultFacesName
word defaultFacesName = "defaultFaces"
Definition at line 460 of file readKivaGrid.H.
Referenced by forAll().
defaultFacesType
word defaultFacesType = emptyPolyPatch::typeName
Definition at line 461 of file readKivaGrid.H.
Referenced by forAll().
nAddedPatches
label nAddedPatches = 0
Definition at line 463 of file readKivaGrid.H.
newPointi
label newPointi = 0
Definition at line 501 of file readKivaGrid.H.
Referenced by extendedEdgeMesh::add(), polyTopoChange::changeMesh(), edgeCollapser::checkMeshQuality(), polyMeshFilter::copyMesh(), extendedEdgeMesh::flipNormals(), forAll(), triSurfaceTools::greenRefine(), nearestEqOp::operator()(), fvMeshDistribute::printCoupleInfo(), hexRef8::subset(), pointZoneSet::updateMesh(), boundaryCutter::updateMesh(), localPointRegion::updateMesh(), addPatchCellLayer::updateMesh(), hexRef8::updateMesh(), and polyMesh::updateMesh().
patchDicts
PtrList<dictionary> patchDicts
Definition at line 537 of file readKivaGrid.H.
Referenced by forAll().