OpenFOAM: applications/utilities/parallelProcessing/reconstructPar/checkFaceAddressingComp.H File Reference
checkFaceAddressingComp.H File Reference
Functions
forAll (faceProcAddressing, proci)
if (minFaceIndex< 1)
Variables
PtrList< labelIOList > & faceProcAddressing = procMeshes.faceProcAddressing()
Function Documentation
forAll()
forAll (faceProcAddressing , proci)
Definition at line 11 of file checkFaceAddressingComp.H.
References Foam::mag().
Referenced by if().
if()
if ()
Definition at line 24 of file checkFaceAddressingComp.H.
References Foam::endl(), forAll(), Foam::sign(), and WarningInFunction.
Variable Documentation
faceProcAddressing
PtrList<labelIOList>& faceProcAddressing = procMeshes.faceProcAddressing()
Definition at line 9 of file checkFaceAddressingComp.H.
Referenced by fvFieldReconstructor::fvPatchFieldReconstructor::directAddressing().