OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/gmvOutputHeader.H File Reference
gmvOutputHeader.H File Reference
Variables
const pointField & points = mesh.points()
label nPoints = points.size()
const cellShapeList & cells = mesh.cellShapes()
Variable Documentation
points
const pointField& points = mesh.points()
Definition at line 1 of file gmvOutputHeader.H.
Referenced by cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), setAndNormalToFaceZone::applyToSet(), PatchTools::calcBounds(), faceZone::calcFaceZonePatch(), processorPolyPatch::calcGeometry(), polyMeshGeometry::cellVolumes(), boundaryMesh::changeFaces(), primitiveMesh::checkEdgeLength(), MeshedSurface< Foam::face >::checkFaces(), edgeCollapser::checkMeshQuality(), primitiveMesh::checkPointNearness(), triSurface::checkTriangles(), sampledSurface::clearGeom(), cellModel::clone(), pointConstraints::constrainDisplacement(), inversePointDistanceDiffusivity::correct(), pointLinear< Type >::correction(), removePoints::countPointUsage(), cyclicPolyPatch::coupledPoints(), displacementMeshMoverMotionSolver::curPoints(), hexCellLooper::cut(), geomCellLooper::cut(), simpleGeomDecomp::decompose(), triSurfaceTools::delaunay2D(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), Foam::facePointN(), searchablePlateFeatures::features(), cellVolumeWeightMethod::findInitialSeeds(), sampledSet::findNearFace(), faceCorrectedSnGrad< Type >::fullGradCorrection(), boundaryMesh::getNearest(), boundaryMesh::getNPoints(), boundaryMesh::getNTris(), coupledPolyPatch::getRotation(), if(), sampledPlane::interpolateField(), sampledIsoSurfaceCell::interpolateField(), sampledThresholdCellFaces::interpolateField(), sampledPatchInternalField::interpolateField(), sampledPatch::interpolateField(), meshToMesh::mapAndOpTgtToSrc(), edgeCollapser::markMergeEdges(), edgeCollapser::markSmallEdges(), meshToMeshMethod::maskCells(), medialAxisMeshMover::move(), pointMesh::movePoints(), NamedEnum< directionType, 3 >::names(), curvedEdge::New(), cellCuts::nonAnchorPoints(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), MeshedSurface< Foam::face >::operator=(), metisDecomp::parallelAware(), ptscotchDecomp::parallelAware(), scotchDecomp::parallelAware(), primitiveMesh::pointInCellBB(), searchableSurfaceCollection::points(), Foam::polyMeshZipUpCells(), sampledPatchInternalField::print(), sampledPlane::print(), sampledCuttingPlane::print(), distanceSurface::print(), sampledPatch::print(), sampledTriSurfaceMesh::print(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectFaceCentres(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints(), face::ray(), NASedgeFormat::read(), STARCDsurfaceFormat< Face >::read(), MeshedSurfaceIOAllocator::reset(), cyclicAMIPolyPatch::resetAMI(), MeshedSurface< Foam::face >::scalePoints(), surfaceFeatures::setFromStatus(), hexRef8::setInstance(), patchInjectionBase::setPositionAndCell(), refinementIterator::setRefinement(), faceCollapser::setRefinement(), cellDistFuncs::smallestDist(), displacementMeshMoverMotionSolver::solve(), displacementLayeredMotionMotionSolver::solve(), extendedEdgeMesh::sortPointsAndEdges(), tetOverlapVolume::tetOverlapVolume(), sixDoFRigidBodyMotion::transform(), rigidBodyMotion::transformPoints(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), boundaryMesh::triangulate(), MeshedSurface< Foam::face >::triangulate(), boundaryMesh::triangulateLocal(), triSurfaceMeshPointSet::triSurfaceMeshPointSet(), triSurface::triSurfInstance(), mixerFvMesh::update(), sampledPatch::update(), sampledSurfaces::update(), cellMotionFvPatchField< Type >::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), pointPatchField< vector >::updated(), patchInjectionBase::updateMesh(), componentDisplacementMotionSolver::updateMesh(), displacementMotionSolver::updateMesh(), USERD_get_gold_part_build_info(), USERD_get_maxsize_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_part_coords(), USERD_get_part_element_ids_by_type(), USERD_get_part_elements_by_type(), USERD_get_part_node_ids(), meshRefinement::userFaceData(), proxySurfaceWriter::write(), ensightSurfaceWriter::write(), starcdSurfaceWriter::write(), MeshedSurfaceProxy< Face >::write(), surfaceFieldValue::write(), ensightPart::writeConnectivity(), starcdSurfaceWriter::writeData(), MeshedSurface< Foam::face >::writeStats(), boundaryMesh::writeTriSurface(), surfaceFieldValue::writeValues(), and structuredDecomp::~structuredDecomp().
nPoints
label nPoints = points.size()
Definition at line 2 of file gmvOutputHeader.H.
Referenced by snappyLayerDriver::addLayers(), face::average(), dynamicRefineFvMesh::cellToPoint(), face::centre(), primitiveMesh::checkEdgeLength(), primitiveMesh::checkFaceVertices(), inversePointDistanceDiffusivity::correct(), pointPatchDist::correct(), cyclicPolyPatch::coupledPoints(), STARCD::cullPoints(), displacementInterpolationMotionSolver::curPoints(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), polyTopoChange::faceNeighbour(), globalMeshData::globalPointNumbering(), if(), processorPolyPatch::initUpdateMesh(), PointEdgeWave< Type, TrackingData >::iterate(), dynamicRefineFvMesh::maxCellField(), NamedEnum< directionType, 3 >::names(), face::nearestPointClassify(), ensightMesh::nFacePrimitives::nFacePrimitives(), face::normal(), minEqOp< labelPair >::operator()(), searchableSurfaceCollection::points(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints(), face::ray(), GTSsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), STARCD::readPoints(), boundaryMesh::setFeatureEdges(), meshCutAndRemove::setRefinement(), edgeCollapser::setRefinement(), sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotionSolver::solve(), rigidBodyMeshMotion::solve(), face::sweptVol(), syncTools::syncPointMap(), triSurfaceSearch::tree(), triSurfaceRegionSearch::treeByRegion(), processorPolyPatch::updateMesh(), USERD_get_gold_part_build_info(), USERD_get_maxsize_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_nsided_conn(), USERD_get_part_coords(), USERD_get_part_element_ids_by_type(), USERD_get_part_elements_by_type(), USERD_get_part_node_ids(), vtkUnstructuredReader::vtkUnstructuredReader(), PrimitivePatch< Face, ::Foam::List, pointField, point >::whichEdge(), vtkSetWriter< Type >::write(), ensightPartCells::~ensightPartCells(), ensightPartFaces::~ensightPartFaces(), and medialAxisMeshMover::~medialAxisMeshMover().
cells
const cellShapeList& cells = mesh.cellShapes()
Definition at line 3 of file gmvOutputHeader.H.
Referenced by MRFZone::addCoriolis(), targetCoeffTrim::calcCoeffs(), fixedCoeff::calcTransformModelData(), DarcyForchheimer::calcTransformModelData(), FaceCellWave< Type, TrackingData >::cellToFace(), primitiveMeshGeometry::checkCellDeterminant(), polyMeshGeometry::checkCellDeterminant(), primitiveMesh::checkCellsZipUp(), primitiveMesh::checkClosedCells(), primitiveMesh::checkConcaveCells(), primitiveMesh::checkFacePyramids(), primitiveMesh::checkUpperTriangular(), edgeCollapser::consistentCollapse(), outletStabilised< Type >::correction(), hexCellLooper::cut(), basicThermo::dpdt(), dynamicRefineFvMesh::extendMarkedCells(), fvMatrix< Type >::faceFluxCorrectionPtr(), surfaceSets::getHangingCells(), twoPhaseMixtureThermo::he(), heThermo< BasicSolidThermo, MixtureType >::he(), multiphaseMixtureThermo::he(), if(), MPPICCloud< Foam::DSMCCloud >::info(), sampledTriSurfaceMesh::interpolateField(), hexRef8::level0EdgeLength(), MRFZone::makeAbsolute(), MRFZone::makeRelative(), meshToMesh::mapAndOpTgtToSrc(), meshToMeshMethod::maskCells(), regionModel1D::moveMesh(), cellCuts::nonAnchorPoints(), nearestEqOp::operator()(), sampledSet::pointInCell(), primitiveMesh::pointInCellBB(), sampledTriSurfaceMesh::sampleField(), refinementIterator::setRefinement(), edgeCollapser::setRefinement(), fvMatrix< Type >::setValuesFromList(), snappyRefineDriver::snappyRefineDriver(), thermalBaffle::solveEnergy(), thermoSingleLayer::Srho(), heheuPsiThermo< BasicPsiThermo, MixtureType >::Tu(), reactingOneDim::updatePhiGas(), reactingOneDim::updateQr(), USERD_get_gold_part_build_info(), USERD_get_maxsize_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_part_element_ids_by_type(), USERD_get_part_elements_by_type(), USERD_get_var_by_component(), outletStabilised< Type >::weights(), and coordinateRotation::~coordinateRotation().