OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/readConversionProperties.H File Reference
readConversionProperties.H File Reference
Functions
IOdictionary conversionProperties (IOobject("conversionProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
scalar startTime (readScalar(conversionProperties.lookup("startTime")))
word vComp (conversionProperties.lookup("vector"))
word format (conversionProperties.lookup("format"))
if ((format !="ascii") &&(format !="ieeei4r8"))
word cells (conversionProperties.lookup("cells"))
if ((cells !="hex"))
Function Documentation
conversionProperties()
IOdictionary conversionProperties (IOobject("conversionProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
Referenced by if().
startTime()
scalar startTime (readScalar(conversionProperties.lookup("startTime")))
vComp()
word vComp (conversionProperties. lookup"vector")
Referenced by for().
format()
word format (conversionProperties. lookup"format")
Referenced by if(), histogram::read(), regionSizeDistribution::read(), and graph::writer::~writer().
if() [1/2]
if ((format !="ascii") &&(format !="ieeei4r8"))
Definition at line 29 of file readConversionProperties.H.
References Foam::abort(), cells(), conversionProperties(), Foam::FatalError, and format().
cells()
word cells (conversionProperties. lookup"cells")
Referenced by if().
if() [2/2]
if ((cells !="hex"))
Definition at line 44 of file readConversionProperties.H.
References Foam::abort(), cells(), and Foam::FatalError.