OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/gmvOutputSpray.H File Reference
gmvOutputSpray.H File Reference
Functions
gmvFile<< "tracers "<< particles.size()<< nl;forAllConstIter(Cloud< passiveParticle >, particles, iter){ gmvFile<< iter().position().x()<< " ";}gmvFile<< nl;forAllConstIter(Cloud< passiveParticle >, particles, iter){ gmvFile<< iter().position().y()<< " ";}gmvFile<< nl;forAllConstIter(Cloud< passiveParticle >, particles, iter){ gmvFile<< iter().position().z()<< " ";}gmvFile<< nl;forAll(lagrangianScalarNames, i){ word name=lagrangianScalarNames[i];IOField< scalar > s (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
if (s.size())
Function Documentation
s()
gmvFile<< "tracers " << particles.size() << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().x() << " ";}gmvFile << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().y() << " ";}gmvFile << nl;forAllConstIter(Cloud<passiveParticle>, particles, iter){ gmvFile << iter().position().z() << " ";}gmvFile << nl;forAll(lagrangianScalarNames, i){ word name = lagrangianScalarNames[i]; IOField<scalar> s (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
Referenced by thermo< Thermo, Type >::a(), greyMeanAbsorptionEmission::aCont(), isoSurface::adaptPatchFields(), polyMeshGeometry::affectedCells(), ThermoParcel< ParcelType >::calcHeatTransfer(), triSurfaceTools::calcInterpolationWeights(), primitiveMeshGeometry::checkFaceDotProduct(), Foam::cmptAv(), Foam::cmptMax(), Foam::cmptMin(), Foam::component(), rotorDiskSource::constructGeometry(), Foam::contiguous< quaternion >(), Foam::contiguous< septernion >(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), particle< Type >::correctAfterParallelTransfer(), diaedg(), Foam::dot(), molecule::constantProperties::electrostaticSite(), VectorSpaceOps< N, I >::eqOpS(), calcEntry::execute(), Foam::stringOps::expand(), hexRef8::faceLevel(), cellQuality::faceNonOrthogonality(), sampledIsoSurfaceCell::faces(), sampledCuttingPlane::faces(), distanceSurface::faces(), sampledIsoSurface::faces(), Field< Foam::Vector2D >::Field(), searchableSurfaceCollection::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), thermo< Thermo, Type >::g(), Foam::gAverage(), triSurfaceMesh::getNormal(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), if(), Foam::stringOps::inplaceExpand(), Foam::stringOps::inplaceTrim(), Foam::stringOps::inplaceTrimLeft(), Foam::stringOps::inplaceTrimRight(), Dual< Type >::interpolateGrad(), triangleFuncs::intersectAxesBundle(), treeBoundBox::intersects(), Foam::inv(), SLListBase::iterator::iterator(), DLListBase::iterator::iterator(), List< Field< scalar > >::List(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::LList(), Foam::LUDecompose(), Foam::magSqr(), meshToMesh::mapAndOpTgtToSrc(), Matrix< RectangularMatrix< Type >, Type >::Matrix(), SVD::minNonZeroS(), molecule::move(), multiNormal::multiNormal(), NamedEnum< directionType, 3 >::names(), line< Point, PointRef >::nearestDist(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), entry::New(), cellQuality::nonOrthogonality(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), chemistryModel< CompType, ThermoType >::omega(), TDACChemistryModel< CompType, ThermoType >::omega(), pTraits< Scalar >::operator Scalar &(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), Foam::operator*(), complex::operator*=(), specie::operator*=(), septernion::operator*=(), constTransport< Thermo >::operator*=(), polynomialTransport< Thermo, PolySize >::operator*=(), rhoConst< Specie >::operator*=(), polynomialSolidTransport< Thermo, PolySize >::operator*=(), logPolynomialTransport< Thermo, PolySize >::operator*=(), polynomialFunction::operator*=(), perfectFluid< Specie >::operator*=(), icoPolynomial< Specie, PolySize >::operator*=(), linear< Type >::operator*=(), incompressiblePerfectGas< Specie >::operator*=(), sutherlandTransport< Thermo >::operator*=(), VectorSpace< Vector< vector >, vector, 3 >::operator*=(), PengRobinsonGas< Specie >::operator*=(), adiabaticPerfectFluid< Specie >::operator*=(), Boussinesq< Specie >::operator*=(), dimensioned< vector >::operator*=(), quaternion::operator*=(), thermo< Thermo, Type >::operator*=(), fvsPatchField< Type >::operator*=(), fvPatchField< Type >::operator*=(), LduMatrix< Type, DType, LUType >::operator*=(), lduMatrix::operator*=(), complex::operator+=(), complex::operator-=(), constAnIsoSolidTransport< Thermo >::operator-=(), constIsoSolidTransport< Thermo >::operator-=(), exponentialSolidTransport< Thermo >::operator-=(), hPowerThermo< EquationOfState >::operator-=(), Foam::operator/(), complex::operator/=(), septernion::operator/=(), polynomialFunction::operator/=(), VectorSpace< Vector< vector >, vector, 3 >::operator/=(), dimensioned< vector >::operator/=(), quaternion::operator/=(), fvsPatchField< Type >::operator/=(), fvPatchField< Type >::operator/=(), Foam::operator<<(), simpleMatrix< Type >::operator=(), complex::operator=(), quaternion::operator=(), Matrix< RectangularMatrix< Type >, Type >::operator=(), token::operator=(), Foam::operator>>(), VectorSpaceOps< N, I >::opSV(), VectorSpaceOps< N, I >::opVS(), Pair< word >::Pair(), molecule::constantProperties::pairPotentialSite(), searchableCylinder::points(), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< Foam::phase *>::printInfo(), quaternion::quaternion(), Foam::Ra(), triangle< Point, PointRef >::randomPoint(), tetrahedron< Point, PointRef >::randomPoint(), PtrList< MRFZone >::read(), dimensionSet::read(), IOPosition< CloudType >::readData(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), cyclicAMIPolyPatch::reverseTransformPosition(), Foam::rotationTensor(), Foam::Rx(), Foam::Ry(), Foam::Rz(), hConstThermo< EquationOfState >::s(), hRefConstThermo< EquationOfState >::s(), eConstThermo< EquationOfState >::s(), hPolynomialThermo< EquationOfState, PolySize >::s(), hPowerThermo< EquationOfState >::s(), janafThermo< EquationOfState >::s(), thermo< Thermo, Type >::S(), s_len_trim(), multiNormal::sample(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), VectorSpaceOps< N, I >::SeqOp(), SprayParcel< ParcelType >::solveTABEq(), Foam::sqr(), Foam::stabilise(), SVD::SVD(), swapec(), chemistryModel< CompType, ThermoType >::tc(), timestring(), wallBoundedParticle::trackFaceTri(), Foam::transform(), sixDoFRigidBodyMotion::transform(), rigidBodyMotion::transformPoints(), cyclicAMIPolyPatch::transformPosition(), cyclicPolyPatch::transformPosition(), surfaceLocation::triangle(), triangulation_print(), Foam::stringOps::trimLeft(), Foam::stringOps::trimRight(), thermo< Thermo, Type >::typeName(), turbGen::U(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValueFvPatchField< Type >::updateCoeffs(), plenumPressureFvPatchScalarField::updateCoeffs(), EulerImplicit< ChemistryModel >::updateRRInReactionI(), vtkUnstructuredReader::vtkUnstructuredReader(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), meshRefinement::write(), UList< Foam::wordRe >::writeEntry(), searchableSurfaces::writeStats(), FSD< CombThermoType, ThermoType >::~FSD(), and RaviPetersen::~RaviPetersen().
if()
if (s. size())
Definition at line 37 of file gmvOutputSpray.H.
References forAll, n, Foam::nl, and s().