OpenFOAM: applications/utilities/postProcessing/graphics/ensightFoamReader/getPatchFieldTensor.H File Reference
getPatchFieldTensor.H File Reference
Functions
if (nVar >=Num_variables - nSprayVariables)
IOobject fieldObjectPtr (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::NO_READ)
if (!fieldObjectPtr.headerOk())
IOobject fieldObject (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE)
volTensorField sf (fieldObject, mesh)
if (which_type==Z_TRI03)
Variables
label patchi = which_part - 2
const tensorField & tf = sf.boundaryField()[patchi]
const polyBoundaryMesh & bMesh = meshPtr->boundaryMesh()
Function Documentation
if() [1/3]
if (nVar >=Num_variables - nSprayVariables)
Definition at line 3 of file getPatchFieldTensor.H.
References fieldNames, fieldObjectPtr(), mesh, nVar, and var2field.
fieldObjectPtr()
IOobject fieldObjectPtr (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::NO_READ)
Referenced by if().
if() [2/3]
if (!fieldObjectPtr. headerOk())
Definition at line 16 of file getPatchFieldTensor.H.
References fieldNames, fieldObject(), mesh, sf(), and var2field.
fieldObject()
IOobject fieldObject (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::NO_WRITE)
Referenced by if().
sf()
volTensorField sf (fieldObject , mesh)
Referenced by if().
if() [3/3]
if (which_type = = Z_TRI03)
Definition at line 39 of file getPatchFieldTensor.H.
References forAll, n, nPoints, and patchi.
Variable Documentation
patchi
label patchi = which_part - 2
Definition at line 1 of file getPatchFieldTensor.H.
Referenced by if().
tf
const tensorField& tf = sf.boundaryField()[patchi]
Definition at line 36 of file getPatchFieldTensor.H.
Referenced by Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), processorLduInterface::compressedReceive(), Field< Foam::Vector2D >::Field(), FieldField< Foam::Field, LUType >::FieldField(), if(), Foam::inv(), Foam::mag(), Foam::magSqr(), momentOfInertia::meshInertia(), fvsPatchField< Type >::operator*=(), fvPatchField< Type >::operator*=(), fvsPatchField< Type >::operator+=(), fvPatchField< Type >::operator+=(), fvsPatchField< Type >::operator-=(), fvPatchField< Type >::operator-=(), fvsPatchField< Type >::operator/=(), Field< Foam::Vector2D >::operator/=(), fvPatchField< Type >::operator/=(), Foam::operator<<(), FieldField< Foam::Field, LUType >::operator=(), valuePointPatchField< vector >::operator=(), valuePointPatchField< vector >::operator==(), fvsPatchField< Type >::operator==(), fvPatchField< Type >::operator==(), Foam::pow(), processorLduInterface::receive(), patchInjectionBase::setPositionAndCell(), Foam::sqr(), Foam::stabilise(), cylindrical::Tr(), Foam::transform(), Foam::transformFieldMask< sphericalTensor >(), Foam::transformFieldMask< symmTensor >(), and Foam::transformPoints().
bMesh
const polyBoundaryMesh& bMesh = meshPtr->boundaryMesh()
Definition at line 37 of file getPatchFieldTensor.H.