OpenFOAM: applications/utilities/postProcessing/graphics/ensightFoamReader/getFieldScalar.H File Reference
getFieldScalar.H File Reference
Functions
if (nVar >=Num_variables - nSprayVariables)
IOobject fieldObjectPtr (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::NO_READ)
if (!fieldObjectPtr.headerOk())
IOobject fieldObject (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE)
volScalarField scalarField (fieldObject, mesh)
if (which_type==Z_HEX08)
Variables
const cellShapeList & cellShapes = meshPtr->cellShapes()
Function Documentation
if() [1/3]
if (nVar >=Num_variables - nSprayVariables)
Definition at line 2 of file getFieldScalar.H.
References fieldNames, fieldObjectPtr(), mesh, nVar, and var2field.
fieldObjectPtr()
IOobject fieldObjectPtr (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::NO_READ)
Referenced by if().
if() [2/3]
if (!fieldObjectPtr. headerOk())
Definition at line 15 of file getFieldScalar.H.
References fieldNames, fieldObject(), mesh, scalarField(), and var2field.
fieldObject()
IOobject fieldObject (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::NO_WRITE)
Referenced by fieldToCell::applyToSet(), for(), if(), and USERD_get_var_value_at_specific().
scalarField()
volScalarField scalarField (fieldObject , mesh)
Referenced by alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField(), ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::alphat(), primitiveMeshTools::cellDeterminant(), heThermo< BasicSolidThermo, MixtureType >::Cp(), heThermo< BasicSolidThermo, MixtureType >::CpByCpv(), heThermo< BasicSolidThermo, MixtureType >::Cpv(), heThermo< BasicSolidThermo, MixtureType >::Cv(), energyJumpAMIFvPatchScalarField::energyJumpAMIFvPatchScalarField(), energyJumpFvPatchScalarField::energyJumpFvPatchScalarField(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), primitiveMeshTools::faceOrthogonality(), polyMeshTools::faceOrthogonality(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), polyMeshTools::faceWeights(), fanFvPatchField< Type >::fanFvPatchField(), fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), for(), heThermo< BasicSolidThermo, MixtureType >::gamma(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), transformFvPatchField< Type >::gradientInternalCoeffs(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::greyDiffusiveViewFactorFixedValueFvPatchScalarField(), heThermo< BasicSolidThermo, MixtureType >::he(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), if(), inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField(), TableBase< Type >::interpolator(), makeFvGradScheme(), MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField(), laminarModel< BasicTurbulenceModel >::nut(), phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField(), prghPressureFvPatchScalarField::prghPressureFvPatchScalarField(), prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField(), lduMatrix::residual(), basicSymmetryFvPatchField< Type >::snGrad(), symmetryPlaneFvPatchField< Type >::snGrad(), Foam::stabilise(), heThermo< BasicSolidThermo, MixtureType >::THE(), timeVaryingAlphaContactAngleFvPatchScalarField::theta(), constantAlphaContactAngleFvPatchScalarField::theta(), dynamicAlphaContactAngleFvPatchScalarField::theta(), totalPressureFvPatchScalarField::totalPressureFvPatchScalarField(), totalTemperatureFvPatchScalarField::totalTemperatureFvPatchScalarField(), turbulentIntensityKineticEnergyInletFvPatchScalarField::turbulentIntensityKineticEnergyInletFvPatchScalarField(), uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField(), uniformTotalPressureFvPatchScalarField::uniformTotalPressureFvPatchScalarField(), CellZoneInjection< CloudType >::updateMesh(), USERD_get_var_value_at_specific(), transformFvPatchField< Type >::valueInternalCoeffs(), variableHeightFlowRateFvPatchScalarField::variableHeightFlowRateFvPatchScalarField(), polyMeshTools::volRatio(), wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), and specieReactionRates< ChemistryModelType >::write().
if() [3/3]
if (which_type = = Z_HEX08)
Definition at line 38 of file getFieldScalar.H.
References cells, Foam::hex(), lookup(), meshPtr, n, and points.
Variable Documentation
cellShapes
const cellShapeList& cellShapes = meshPtr->cellShapes()
Definition at line 35 of file getFieldScalar.H.
Referenced by hexCellLooper::cut(), topoCellLooper::cut(), forAll(), if(), ensightMesh::nFacePrimitives::nFacePrimitives(), USERD_get_gold_part_build_info(), USERD_get_nfaced_conn(), USERD_get_nfaced_nodes_per_face(), USERD_get_part_element_ids_by_type(), and USERD_get_part_elements_by_type().