OpenFOAM: applications/utilities/postProcessing/graphics/ensightFoamReader/getFieldTensor.H File Reference
getFieldTensor.H File Reference
Functions
if (nVar >=Num_variables - nSprayVariables)
IOobject fieldObjectPtr (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::NO_READ)
if (!fieldObjectPtr.headerOk())
IOobject fieldObject (fieldNames[var2field[nVar]], runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE)
volTensorField tf (fieldObject, mesh)
if (which_type==Z_HEX08)
Variables
const cellShapeList & cellShapes = meshPtr->cellShapes()
Function Documentation
if() [1/3]
if (nVar >=Num_variables - nSprayVariables)
Definition at line 1 of file getFieldTensor.H.
References fieldNames, fieldObjectPtr(), mesh, nVar, and var2field.
fieldObjectPtr()
IOobject fieldObjectPtr (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::NO_READ)
Referenced by if().
if() [2/3]
if (!fieldObjectPtr. headerOk())
Definition at line 15 of file getFieldTensor.H.
References fieldNames, fieldObject(), mesh, tf(), and var2field.
fieldObject()
IOobject fieldObject (fieldNames] [var2field[nVar], runTime. timeName(), mesh , IOobject::MUST_READ , IOobject::NO_WRITE)
Referenced by if().
tf()
volTensorField tf (fieldObject , mesh)
Referenced by if().
if() [3/3]
if (which_type = = Z_HEX08)
Definition at line 38 of file getFieldTensor.H.
References cells, Foam::hex(), lookup(), meshPtr, n, and points.
Variable Documentation
cellShapes
const cellShapeList& cellShapes = meshPtr->cellShapes()
Definition at line 35 of file getFieldTensor.H.