OpenFOAM: applications/utilities/postProcessing/graphics/ensightFoamReader/USERD_set_filenames.H File Reference
USERD_set_filenames.H File Reference
Functions
int USERD_set_filenames (char filename_1[], char filename_2[], char the_path[], int swapbytes)
Function Documentation
USERD_set_filenames()
int USERD_set_filenames (char filename_1[], char filename_2[], char the_path[], int swapbytes)
Definition at line 5 of file USERD_set_filenames.H.
References caseDir, Current_time_step, Foam::endl(), fieldNames, Time::findTimes(), Foam::flush(), forAll, Foam::Info, Foam::isDir(), isScalar, isSpray, isTensor, isVector, lagrangianScalarNames, lagrangianVectorNames, meshPtr, n, nPatches, nSprayVariables, Num_structured_parts, Num_time_steps, Num_unstructured_parts, Num_variables, Numparts_available, nVar, rootDir, runTimePtr, scalarName, List< T >::size(), sprayPtr, sprayScalarFieldName, sprayVectorFieldName, tensorName, timeDirs, var2field, and vectorName.