OpenFOAM: applications/utilities/postProcessing/graphics/ensightFoamReader/USERD_get_gold_variable_info.H File Reference
USERD_get_gold_variable_info.H File Reference
Functions
int USERD_get_gold_variable_info (char **var_description, char **var_filename, int *var_type, int *var_classify, int *var_complex, char **var_ifilename, float *var_freq, int *var_contran, int *var_timeset)
Function Documentation
USERD_get_gold_variable_info()
int USERD_get_gold_variable_info (char ** var_description, char ** var_filename, int * var_type, int * var_classify, int * var_complex, char ** var_ifilename, float * var_freq, int * var_contran, int * var_timeset)
Definition at line 5 of file USERD_get_gold_variable_info.H.
References Foam::endl(), fieldNames, Foam::flush(), forAll, Foam::Info, isScalar, isTensor, isVector, lagrangianScalarNames, lagrangianVectorNames, n, Foam::name(), nPatches, nSprayVariables, Num_variables, Numparts_available, parcelPrepend, List< T >::size(), and var2field.