OpenFOAM: applications/utilities/postProcessing/graphics/ensightFoamReader/USERD_structured_data.H File Reference
USERD_structured_data.H File Reference
Functions
int USERD_get_block_vector_values_by_component (int block_number, int which_vector, int which_component, float *vector_array)
int USERD_get_block_coords_by_component (int block_number, int which_component, float *coord_array)
int USERD_get_block_iblanking (int block_number, int *iblank_array)
int USERD_get_block_scalar_values (int block_number, int which_scalar, float *scalar_array)
int USERD_get_ghosts_in_model_flag (void)
int USERD_get_ghosts_in_block_flag (int block_number)
int USERD_get_block_ghost_flags (int block_number, int *ghost_flags)
Function Documentation
USERD_get_block_vector_values_by_component()
int USERD_get_block_vector_values_by_component (int block_number, int which_vector, int which_component, float * vector_array)
Definition at line 2 of file USERD_structured_data.H.
References USERD_get_block_coords_by_component().
USERD_get_block_coords_by_component()
int USERD_get_block_coords_by_component (int block_number, int which_component, float * coord_array)
Definition at line 13 of file USERD_structured_data.H.
References USERD_get_block_iblanking().
Referenced by USERD_get_block_vector_values_by_component().
USERD_get_block_iblanking()
int USERD_get_block_iblanking (int block_number, int * iblank_array)
Definition at line 24 of file USERD_structured_data.H.
References USERD_get_block_scalar_values().
Referenced by USERD_get_block_coords_by_component().
USERD_get_block_scalar_values()
int USERD_get_block_scalar_values (int block_number, int which_scalar, float * scalar_array)
Definition at line 33 of file USERD_structured_data.H.
Referenced by USERD_get_block_iblanking().
USERD_get_ghosts_in_model_flag()
int USERD_get_ghosts_in_model_flag (void)
Definition at line 41 of file USERD_structured_data.H.
References USERD_get_ghosts_in_block_flag().
USERD_get_ghosts_in_block_flag()
int USERD_get_ghosts_in_block_flag (int block_number)
Definition at line 47 of file USERD_structured_data.H.
References USERD_get_block_ghost_flags().
Referenced by USERD_get_ghosts_in_model_flag().
USERD_get_block_ghost_flags()
int USERD_get_block_ghost_flags (int block_number, int * ghost_flags)
Definition at line 55 of file USERD_structured_data.H.
Referenced by USERD_get_ghosts_in_block_flag().