OpenFOAM: applications/solvers/combustion/chemFoam/readInitialConditions.H File Reference
readInitialConditions.H File Reference
Functions
word constProp (initialConditions.lookup("constantProperty"))
if ((constProp !="pressure") &&(constProp !="volume"))
word fractionBasis (initialConditions.lookup("fractionBasis"))
if ((fractionBasis !="mass") &&(fractionBasis !="mole"))
PtrList< gasHThermoPhysics > specieData (Y.size())
forAll (specieData, i)
scalarList Y0 (nSpecie, 0.0)
scalarList X0 (nSpecie, 0.0)
dictionary fractions (initialConditions.subDict("fractions"))
if (fractionBasis=="mole")
forAll (Y, i)
thermo he ()
thermo correct ()
Variables
label nSpecie = Y.size()
else
const scalar mTot = sum(Y0)
const scalar mw = 1.0/invW
scalar h0 = 0.0
rho = thermo.rho()
scalar rho0 = rho[0]
scalar u0 = h0 - p0/rho0
scalar R0 = p0/(rho0*T0)
Rspecific [0] = R0
scalar integratedHeat = 0.0
Function Documentation
constProp()
word constProp (initialConditions. lookup"constantProperty")
Referenced by if().
if() [1/3]
if ((constProp !="pressure") &&(constProp !="volume"))
Definition at line 2 of file readInitialConditions.H.
References Foam::abort(), constProp(), Foam::FatalError, fractionBasis(), and Foam::nl.
fractionBasis()
word fractionBasis (initialConditions. lookup"fractionBasis")
Referenced by if().
if() [2/3]
if ((fractionBasis !="mass") &&(fractionBasis !="mole"))
Definition at line 10 of file readInitialConditions.H.
References Foam::abort(), Foam::FatalError, fractionBasis(), and Foam::nl.
specieData()
PtrList<gasHThermoPhysics> specieData (Y. size())
Referenced by forAll(), and if().
forAll() [1/2]
forAll (specieData , i)
Definition at line 19 of file readInitialConditions.H.
References fractions(), specieData(), thermo, X0(), and Y0().
Referenced by if().
Y0()
scalarList Y0 (nSpecie , 0. 0)
Referenced by forAll(), and NamedEnum< directionType, 3 >::names().
X0()
scalarList X0 (nSpecie , 0. 0)
Referenced by SprayParcel< ParcelType >::calc(), and forAll().
fractions()
dictionary fractions (initialConditions. subDict"fractions")
Referenced by forAll(), and if().
if() [3/3]
if (fractionBasis = = "mole")
Definition at line 36 of file readInitialConditions.H.
References forAll(), fractions(), mTot, mw, Foam::name(), readScalar, specieData(), Foam::sum(), and Y.
forAll() [2/2]
forAll (Y , i)
Definition at line 73 of file readInitialConditions.H.
References mTot, and specieData().
he()
thermo he ()
correct()
thermo correct ()
Variable Documentation
nSpecie
label nSpecie = Y.size()
Definition at line 17 of file readInitialConditions.H.
Referenced by TDACChemistryModel< CompType, ThermoType >::derivatives(), ode< ChemistryModel >::solve(), EulerImplicit< ChemistryModel >::solve(), TDACChemistryModel< CompType, ThermoType >::solve(), and specieReactionRates< ChemistryModelType >::write().
else
else
Initial value:
{
        forAll(Y, i)
        {
            const word& name = Y[i].name();
            if (fractions.found(name))
            {
                Y0[i] = readScalar(fractions.lookup(name));
            }
        }
        scalar invW = 0.0
Definition at line 61 of file readInitialConditions.H.
mTot
const scalar mTot = sum(Y0)
Definition at line 72 of file readInitialConditions.H.
Referenced by ORourkeCollision< CloudType >::collideSorted(), forAll(), and if().
mw
const scalar mw = 1.0/invW
Definition at line 78 of file readInitialConditions.H.
Referenced by if().
h0
scalar h0 = 0.0
Definition at line 86 of file readInitialConditions.H.
rho
thermo rho = thermo.rho()
Definition at line 96 of file readInitialConditions.H.
Referenced by tabulatedAccelerationSource::addSup(), effectivenessHeatExchangerSource::addSup(), CoBlended< Type >::blendingFactor(), cellCoBlended< Type >::blendingFactor(), Implicit< CloudType >::cacheFields(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), forces::calcForcesMoment(), ThermoParcel< ParcelType >::calcHeatTransfer(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), NoAtomization< CloudType >::clone(), NoBreakup< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), exponential::clone(), BlobsSheetAtomization< CloudType >::clone(), ReitzDiwakar< CloudType >::clone(), ETAB< CloudType >::clone(), Lun::clone(), PilchErdman< CloudType >::clone(), LISAAtomization< CloudType >::clone(), TAB< CloudType >::clone(), HarrisCrighton::clone(), SHF< CloudType >::clone(), ReactingCloud< Foam::DSMCCloud >::cloneBare(), infinitelyFastChemistry< CombThermoType, ThermoType >::correct(), patchInjection::correct(), PaSR< Type >::correct(), relaxation::correct(), drippingInjection::correct(), BrunDrippingInjection::correct(), curvatureSeparation::correct(), fixedCoeff::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), standardPhaseChange::correctModel(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), Foam::fvc::ddt(), TDACChemistryModel< CompType, ThermoType >::derivatives(), chemistryModel< CompType, ThermoType >::derivatives(), forces::devRhoReff(), actuationDiskSource::diskArea(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), thermo< Thermo, Type >::ea(), thermo< Thermo, Type >::es(), scalarTransport::execute(), PatchFlowRateInjection< CloudType >::flowRate(), flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField(), for(), forAll(), EulerDdtScheme< Type >::fvcDdt(), if(), Foam::MULES::implicitSolve(), PhiScheme< Type, PhiLimiter >::limiter(), steadyStateDdtScheme< Type >::mesh(), EulerDdtScheme< Type >::mesh(), boundedDdtScheme< Type >::mesh(), backwardDdtScheme< Type >::mesh(), CoEulerDdtScheme< Type >::mesh(), SLTSDdtScheme< Type >::mesh(), ddtScheme< Type >::mesh(), localEulerDdtScheme< Type >::mesh(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), solidParticleCloud::move(), forces::mu(), laminarModel< BasicTurbulenceModel >::New(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::New(), LESModel< BasicTurbulenceModel >::New(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut(), CrankNicolsonDdtScheme< Type >::ocCoeff(), rhoMagSqr< Type >::operator()(), option::iNew::operator()(), porosityModel::iNew::operator()(), KinematicParcel< ParcelType >::readFields(), NullMRF::relative(), InjectionModel< CloudType >::setNumberOfParticles(), ConeNozzleInjection< CloudType >::setProperties(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), TDACChemistryModel< CompType, ThermoType >::solve(), chemistryModel< CompType, ThermoType >::solve(), SprayParcel< ParcelType >::solveTABEq(), BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::TABtwoWeCrit(), chemistryModel< CompType, ThermoType >::tc(), chemistryTabulationMethod< CompType, ThermoType >::tolerance(), porosityModel::transformModelData(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), LISAAtomization< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), alphaFixedPressureFvPatchScalarField::updateCoeffs(), uniformTotalPressureFvPatchScalarField::updateCoeffs(), totalPressureFvPatchScalarField::updateCoeffs(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), while(), KinematicParcel< ParcelType >::writeFields(), explicitPorositySource::~explicitPorositySource(), IncompressibleTurbulenceModel< TransportModel >::~IncompressibleTurbulenceModel(), interRegionExplicitPorositySource::~interRegionExplicitPorositySource(), linearViscousStress< RASModel< BasicTurbulenceModel > >::~linearViscousStress(), Maxwell< BasicTurbulenceModel >::~Maxwell(), nonlinearEddyViscosity< incompressible::RASModel >::~nonlinearEddyViscosity(), optionList::~optionList(), and tabulatedAccelerationSource::~tabulatedAccelerationSource().
rho0
scalar rho0 = rho[0]
Definition at line 97 of file readInitialConditions.H.
Referenced by SprayParcel< ParcelType >::calc().
u0
scalar u0 = h0 - p0/rho0
Definition at line 98 of file readInitialConditions.H.
Referenced by if(), and triangleFuncs::intersectAxesBundle().
R0
scalar R0 = p0/(rho0*T0)
Definition at line 99 of file readInitialConditions.H.
Rspecific
Rspecific[0] = R0
Definition at line 100 of file readInitialConditions.H.
Referenced by if().
integratedHeat
scalar integratedHeat = 0.0
Definition at line 102 of file readInitialConditions.H.
Referenced by if().