OpenFOAM: applications/solvers/combustion/chemFoam/solveChemistry.H File Reference
solveChemistry.H File Reference
Variables
dtChem = chemistry.solve(runTime.deltaT().value())
scalar Sh = chemistry.Sh()()[0]/rho[0]
integratedHeat = Sh*runTime.deltaT().value()
Variable Documentation
dtChem
dtChem = chemistry.solve(runTime.deltaT().value())
Definition at line 1 of file solveChemistry.H.
Sh
scalar Sh = chemistry.Sh()()[0]/rho[0]
Definition at line 2 of file solveChemistry.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::calc(), ThermoParcel< ParcelType >::calc(), LiquidEvaporation< CloudType >::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), singleStepCombustion< CombThermoType, ThermoType >::dQ(), solidChemistryModel< CompType, SolidThermo >::dQ(), chemistryModel< CompType, ThermoType >::dQ(), solidChemistryModel< CompType, SolidThermo >::Sh(), and chemistryModel< CompType, ThermoType >::Sh().
integratedHeat
integratedHeat = Sh*runTime.deltaT().value()
Definition at line 3 of file solveChemistry.H.