OpenFOAM: applications/solvers/combustion/PDRFoam/StCourantNo.H File Reference
StCourantNo.H File Reference
Calculates and outputs the mean and maximum Courant Numbers.
Functions
if (mesh.nInternalFaces())
Detailed Description
Calculates and outputs the mean and maximum Courant Numbers.
Original source file StCourantNo.H
Definition in file StCourantNo.H.
Function Documentation
if()
if (mesh. nInternalFaces())
Definition at line 32 of file StCourantNo.H.
References Foam::endl(), Foam::gMax(), Foam::gSum(), Foam::Info, Foam::mag(), mesh, rho, scalarField(), and Foam::fvc::surfaceSum().