OpenFOAM: applications/solvers/compressible/rhoCentralFoam/readFluxScheme.H File Reference
readFluxScheme.H File Reference
Functions
word fluxScheme ("Kurganov")
if (mesh.schemesDict().readIfPresent("fluxScheme", fluxScheme))
Function Documentation
fluxScheme()
word fluxScheme ("Kurganov")
Referenced by if().
if()
if (mesh. schemesDict).readIfPresent("fluxScheme", fluxScheme)
Definition at line 2 of file readFluxScheme.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, fluxScheme(), and Foam::Info.