OpenFOAM: applications/solvers/compressible/rhoCentralFoam/centralCourantNo.H File Reference
centralCourantNo.H File Reference
Calculates the mean and maximum wave speed based Courant Numbers.
Functions
if (mesh.nInternalFaces())
Detailed Description
Calculates the mean and maximum wave speed based Courant Numbers.
Original source file centralCourantNo.H
Definition in file centralCourantNo.H.
Function Documentation
if()
if (mesh. nInternalFaces())
Definition at line 29 of file centralCourantNo.H.
References CoNum, Foam::endl(), Foam::gMax(), Foam::gSum(), Foam::Info, meanCoNum, mesh, scalarField(), and Foam::fvc::surfaceSum().