OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/readPIMPLEControls.H File Reference
readPIMPLEControls.H File Reference
Functions
fvSolution solutionDict (runTime)
Variables
const dictionary & pimple = solutionDict.subDict("PIMPLE")
const int nOuterCorr
Function Documentation
solutionDict()
fvSolution solutionDict (runTime)
Referenced by solutionControl::read(), solution::read(), and solution::solution().
Variable Documentation
pimple
const dictionary& pimple = solutionDict.subDict("PIMPLE")
Definition at line 5 of file readPIMPLEControls.H.
nOuterCorr
const int nOuterCorr
Initial value:
=
        pimple.lookupOrDefault<int>("nOuterCorrectors", 1)
Definition at line 7 of file readPIMPLEControls.H.
Referenced by for().