OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/solid/createSolidFields.H File Reference
createSolidFields.H File Reference
Functions
PtrList< coordinateSystem > coordinates (solidRegions.size())
PtrList< solidThermo > thermos (solidRegions.size())
PtrList< radiation::radiationModel > radiations (solidRegions.size())
PtrList< fv::options > solidHeatSources (solidRegions.size())
PtrList< volScalarField > betavSolid (solidRegions.size())
PtrList< volSymmTensorField > aniAlphas (solidRegions.size())
forAll (solidRegions, i)
Function Documentation
coordinates()
PtrList<coordinateSystem> coordinates (solidRegions. size())
Referenced by searchableSurfaceCollection::coordinates(), forAll(), and if().
thermos()
PtrList<solidThermo> thermos (solidRegions. size())
Referenced by forAll(), and basicThermo::lookupThermo().
radiations()
PtrList<radiation::radiationModel> radiations (solidRegions. size())
Referenced by forAll().
solidHeatSources()
PtrList<fv::options> solidHeatSources (solidRegions. size())
Referenced by forAll().
betavSolid()
PtrList<volScalarField> betavSolid (solidRegions. size())
Referenced by forAll().
aniAlphas()
PtrList<volSymmTensorField> aniAlphas (solidRegions. size())
Referenced by forAll(), and if().
forAll()
forAll (solidRegions , i)
Definition at line 10 of file createSolidFields.H.
References aniAlphas(), betavSolid(), coordinates(), Foam::dimless, Foam::endl(), Foam::Info, Foam::New(), Foam::nl, radiations(), PtrList< T >::set(), solidHeatSources(), solidRegions(), T, thermos(), and Foam::Zero.