OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/solid/createSolidMeshes.H File Reference
createSolidMeshes.H File Reference
Functions
const wordList solidsNames (rp["solid"])
PtrList< fvMesh > solidRegions (solidsNames.size())
forAll (solidsNames, i)
Function Documentation
solidsNames()
const wordList solidsNames (rp ["solid"])
Referenced by forAll().
solidRegions()
PtrList<fvMesh> solidRegions (solidsNames. size())
Referenced by forAll().
forAll()
forAll (solidsNames , i)
Definition at line 5 of file createSolidMeshes.H.
References Foam::endl(), Foam::Info, Foam::nl, solidRegions(), and solidsNames().