OpenFOAM: applications/solvers/incompressible/simpleFoam/porousSimpleFoam/createPorousZones.H File Reference
createPorousZones.H File Reference
Functions
IOporosityModelList pZones (mesh)
Switch pressureImplicitPorosity (false)
if (pZones.active())
Variables
int nUCorr = 0
Function Documentation
pZones()
IOporosityModelList pZones (mesh)
pressureImplicitPorosity()
Switch pressureImplicitPorosity (false)
Referenced by if().
if()
if (pZones. active())
Definition at line 6 of file createPorousZones.H.
References Foam::endl(), Foam::Info, nUCorr, pressureImplicitPorosity(), and simple.
Variable Documentation
nUCorr
int nUCorr = 0
Definition at line 5 of file createPorousZones.H.
Referenced by if().