OpenFOAM: applications/solvers/incompressible/boundaryFoam/interrogateWallPatches.H File Reference
interrogateWallPatches.H File Reference
Functions
label faceId (-1)
label patchId (-1)
label nWallFaces (0)
vector wallNormal (Zero)
forAll (patches, patchi)
if (nWallFaces==0)
scalarField y (wallNormal &(mesh.C().primitiveField() - mesh.C().boundaryField()[patchId][faceId]))
Variables
const fvPatchList & patches = mesh.boundary()
else
label cellId = patches[patchId].faceCells()[faceId]
Function Documentation
faceId()
label faceId (- 1)
Referenced by forAll(), NamedEnum< directionType, 3 >::names(), FacePostProcessing< CloudType >::postFace(), and ensightPartCells::~ensightPartCells().
patchId()
label patchId (- 1)
Referenced by forAll().
nWallFaces()
label nWallFaces (0)
Referenced by forAll(), cellDistFuncs::mesh(), and cellDistFuncs::smallestDist().
wallNormal()
vector wallNormal (Zero)
Referenced by forAll().
forAll()
forAll (patches , patchi)
Check that wall faces are parallel
Definition at line 10 of file interrogateWallPatches.H.
References Foam::exit(), faceId(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), Foam::nl, nWallFaces(), patches, patchi, patchId(), vectorField(), and wallNormal().
if()
if (nWallFaces = = 0)
Definition at line 55 of file interrogateWallPatches.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
y()
scalarField y (wallNormal & mesh.C().primitiveField() - mesh.C().boundaryField()[patchId][faceId])
Variable Documentation
patches
const fvPatchList& patches = mesh.boundary()
Definition at line 8 of file interrogateWallPatches.H.
Referenced by forAll().
else
else
Initial value:
{
    Info<< "Generating wall data for patch: " << patches[patchId].name()
        << endl
Definition at line 61 of file interrogateWallPatches.H.
cellId
label cellId = patches[patchId].faceCells()[faceId]
Definition at line 67 of file interrogateWallPatches.H.
Referenced by STARCD::readBoundary(), and thermalBaffle::solveEnergy().