OpenFOAM: applications/solvers/incompressible/boundaryFoam/evaluateNearWall.H File Reference
evaluateNearWall.H File Reference
Variables
scalar nut = turbulence->nut()().boundaryField()[patchId][faceId]
symmTensor R = turbulence->devReff()().boundaryField()[patchId][faceId]
Universal gas constant: default SI units: [J/mol/K].
scalar epsilon = turbulence->epsilon()()[cellId]
scalar k = turbulence->k()()[cellId]
Boltzmann constant.
scalar magUp = mag(U[cellId] - U.boundaryField()[patchId][faceId])
scalar tauw = flowDirection & R & wallNormal
scalar uTau = ::sqrt(mag(tauw))
scalar yPlus = uTau*y[cellId]/(nu + ROOTVSMALL)
scalar uPlus = magUp/(uTau + ROOTVSMALL)
scalar nutPlus = nut/nu
scalar kPlus = k/(sqr(uTau) + ROOTVSMALL)
scalar epsilonPlus = epsilon*nu/(pow4(uTau) + ROOTVSMALL)
scalar Rey = magUp*y[cellId]/nu
Variable Documentation
nut
scalar nut = turbulence->nut()().boundaryField()[patchId][faceId]
Definition at line 5 of file evaluateNearWall.H.
Referenced by kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), EddyDiffusivity< compressible::turbulenceModel >::correctNut(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), SpalartAllmarasDES< BasicTurbulenceModel >::k(), incompressibleTurbulenceModel::mut(), LESModel< BasicTurbulenceModel >::nuEff(), and RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::nuEff().
R
symmTensor R = turbulence->devReff()().boundaryField()[patchId][faceId]
Universal gas constant: default SI units: [J/mol/K].
Definition at line 6 of file evaluateNearWall.H.
epsilon
scalar epsilon = turbulence->epsilon()()[cellId]
Definition at line 7 of file evaluateNearWall.H.
Referenced by ThermoCloud< Foam::DSMCCloud >::ap(), atmBoundaryLayerInletEpsilonFvPatchScalarField::atmBoundaryLayerInletEpsilonFvPatchScalarField(), ThermoParcel< ParcelType >::calcHeatTransfer(), PaSR< Type >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), ThermoCloud< Foam::DSMCCloud >::Ep(), if(), turbulenceFields::omega(), ThermoCloud< Foam::DSMCCloud >::sigmap(), StochasticDispersionRAS< CloudType >::update(), GradientDispersionRAS< CloudType >::update(), fWallFunctionFvPatchScalarField::updateCoeffs(), and ThermoSurfaceFilm< CloudType >::wetSplashInteraction().
k
scalar k = turbulence->k()()[cellId]
Boltzmann constant.
Definition at line 9 of file evaluateNearWall.H.
Referenced by BrownianMotionForce< CloudType >::calcCoupled(), MaxwellianThermal< CloudType >::correct(), DSMCCloud< DSMCParcel< ParcelType > >::equipartitionInternalEnergy(), DSMCCloud< DSMCParcel< ParcelType > >::equipartitionLinearVelocity(), FreeStream< CloudType >::inflow(), DSMCCloud< DSMCParcel< ParcelType > >::maxwellianAverageSpeed(), DSMCCloud< DSMCParcel< ParcelType > >::maxwellianMostProbableSpeed(), DSMCCloud< DSMCParcel< ParcelType > >::maxwellianRMSSpeed(), VariableHardSphere< CloudType >::sigmaTcR(), LarsenBorgnakkeVariableHardSphere< CloudType >::sigmaTcR(), and dsmcFields::write().
magUp
scalar magUp = mag(U[cellId] - U.boundaryField()[patchId][faceId])
Definition at line 10 of file evaluateNearWall.H.
Referenced by nutUWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), nutUWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), and nutURoughWallFunctionFvPatchScalarField::yPlus().
tauw
scalar tauw = flowDirection & R & wallNormal
Definition at line 12 of file evaluateNearWall.H.
Referenced by ReynoldsStress< RASModel< BasicTurbulenceModel > >::correctWallShearStress().
uTau
scalar uTau = ::sqrt(mag(tauw))
Definition at line 14 of file evaluateNearWall.H.
Referenced by nutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
yPlus
scalar yPlus = uTau*y[cellId]/(nu + ROOTVSMALL)
Definition at line 16 of file evaluateNearWall.H.
Referenced by epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
uPlus
scalar uPlus = magUp/(uTau + ROOTVSMALL)
Definition at line 18 of file evaluateNearWall.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus().
nutPlus
scalar nutPlus = nut/nu
Definition at line 20 of file evaluateNearWall.H.
kPlus
scalar kPlus = k/(sqr(uTau) + ROOTVSMALL)
Definition at line 22 of file evaluateNearWall.H.
epsilonPlus
scalar epsilonPlus = epsilon*nu/(pow4(uTau) + ROOTVSMALL)
Definition at line 24 of file evaluateNearWall.H.
Rey
scalar Rey = magUp*y[cellId]/nu
Definition at line 28 of file evaluateNearWall.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::yPlus().