OpenFOAM: applications/solvers/multiphase/multiphaseEulerFoam/zonePhaseVolumes.H File Reference
zonePhaseVolumes.H File Reference
Functions
forAll (mesh.cellZones(), czi)
Function Documentation
forAll()
forAll (mesh. cellZones(), czi)
Definition at line 4 of file zonePhaseVolumes.H.
References Foam::constant::atomic::alpha, Foam::endl(), fluid, forAllConstIter(), Foam::Info, mesh, and Foam::reduce().