OpenFOAM: applications/solvers/stressAnalysis/solidDisplacementFoam/readThermalProperties.H File Reference
readThermalProperties.H File Reference
Functions
IOobject CIO ("C", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
const dictionary & CDict (thermalProperties.subDict("C"))
word CType (CDict.lookup("type"))
if (CType=="uniform")
IOobject rhoKIO ("k", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
const dictionary & kDict (thermalProperties.subDict("k"))
word kType (kDict.lookup("type"))
if (kType=="uniform")
IOobject alphaIO ("alpha", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
const dictionary & alphaDict (thermalProperties.subDict("alpha"))
word alphaType (alphaDict.lookup("type"))
if (alphaType=="uniform")
Variables
Info<< "Reading thermal properties\"<< endl;IOdictionary thermalProperties(IOobject("thermalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));Switch thermalStress(thermalProperties.lookup("thermalStress"));volScalarField threeKalpha(IOobject("threeKalpha", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("0", dimensionSet(0, 2, -2, -1, 0), 0.0));volScalarField DT(IOobject("DT", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("0", dimensionSet(0, 2, -1, 0, 0), 0.0));if(thermalStress){ autoPtr< volScalarField > CPtr
else
volScalarField & C = CPtr()
autoPtr< volScalarField > rhoKPtr
volScalarField & rhoK = rhoKPtr()
autoPtr< volScalarField > alphaPtr
volScalarField & alpha = alphaPtr()
Fine-structure constant: default SI units: [].
Function Documentation
CIO()
IOobject CIO ("C" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
CDict()
const dictionary& CDict (thermalProperties. subDict"C")
Referenced by if().
CType()
word CType (CDict. lookup"type")
Referenced by if().
if() [1/3]
else if (CType = = "uniform")
Definition at line 63 of file readThermalProperties.H.
References CDict(), CIO(), CType(), mesh, and readScalar.
rhoKIO()
IOobject rhoKIO ("k" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
kDict()
const dictionary& kDict (thermalProperties. subDict"k")
Referenced by if().
kType()
word kType (kDict. lookup"type")
Referenced by if().
if() [2/3]
else if (kType = = "uniform")
Definition at line 118 of file readThermalProperties.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, kDict(), kType(), mesh, readScalar, and rhoKIO().
alphaIO()
IOobject alphaIO ("alpha" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
alphaDict()
const dictionary& alphaDict (thermalProperties. subDict"alpha")
Referenced by if().
alphaType()
word alphaType (alphaDict. lookup"type")
Referenced by if().
if() [3/3]
else if (alphaType = = "uniform")
Definition at line 175 of file readThermalProperties.H.
References Foam::abort(), alphaDict(), alphaIO(), alphaType(), Foam::dimTemperature, Foam::FatalError, FatalErrorInFunction, Foam::inv(), mesh, and readScalar.
Variable Documentation
CPtr
Info<< "Reading thermal properties\n" << endl;IOdictionary thermalProperties(IOobject ("thermalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));Switch thermalStress(thermalProperties.lookup("thermalStress"));volScalarField threeKalpha(IOobject ("threeKalpha", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("0", dimensionSet(0, 2, -2 , -1, 0), 0.0));volScalarField DT(IOobject ("DT", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("0", dimensionSet(0, 2, -1 , 0, 0), 0.0));if (thermalStress){ autoPtr<volScalarField> CPtr
Definition at line 50 of file readThermalProperties.H.
else
else
Initial value:
{
        FatalErrorInFunction
            << "Valid type entries are uniform or field for C"
            << abort(FatalError)
Definition at line 97 of file readThermalProperties.H.
C
volScalarField& C = CPtr()
Definition at line 103 of file readThermalProperties.H.
Referenced by viewFactor::calculate(), forAll(), makeFvGradScheme(), Foam::multiply(), plane::plane(), plane::planeCoeffs(), and writeCellCentres::write().
rhoKPtr
autoPtr<volScalarField> rhoKPtr
Definition at line 105 of file readThermalProperties.H.
rhoK
volScalarField& rhoK = rhoKPtr()
Definition at line 158 of file readThermalProperties.H.
alphaPtr
autoPtr<volScalarField> alphaPtr
Definition at line 160 of file readThermalProperties.H.
Referenced by regionSizeDistribution::write().
alpha
volScalarField& alpha = alphaPtr()
Fine-structure constant: default SI units: [].
Definition at line 213 of file readThermalProperties.H.
Referenced by KinematicCloud< Cloud< basicKinematicCollidingParcel > >::alpha(), BrownianMotionForce< CloudType >::calcCoupled(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), pointMVCWeight::calcWeights(), equilibrium::clone(), isotropic::clone(), nonEquilibrium::clone(), exponential::clone(), Lun::clone(), TrajectoryCollision< CloudType >::collideParcels(), contactAngleForce::correct(), thixotropicViscosity::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), solidification::correctModel(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), PengRobinsonGas< Specie >::cp(), PengRobinsonGas< Specie >::cpMcv(), QRMatrix< MatrixType >::decompose(), SpalartAllmarasIDDES< BasicTurbulenceModel >::dTilda(), fvMatrix< Type >::faceFluxCorrectionPtr(), for(), forAll(), forAllIter(), EulerDdtScheme< Type >::fvcDdt(), PengRobinsonGas< Specie >::h(), MPPICCloud< Foam::DSMCCloud >::info(), Analytical< Type >::integrate(), triangleFuncs::intersectAxesBundle(), steadyStateDdtScheme< Type >::mesh(), EulerDdtScheme< Type >::mesh(), boundedDdtScheme< Type >::mesh(), backwardDdtScheme< Type >::mesh(), CoEulerDdtScheme< Type >::mesh(), SLTSDdtScheme< Type >::mesh(), ddtScheme< Type >::mesh(), localEulerDdtScheme< Type >::mesh(), laminarModel< BasicTurbulenceModel >::New(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::New(), LESModel< BasicTurbulenceModel >::New(), CrankNicolsonDdtScheme< Type >::ocCoeff(), ListPlusEqOp< T, Size >::operator()(), option::iNew::operator()(), SprayCloud< Foam::DSMCCloud >::penetration(), ParticleErosion< CloudType >::postPatch(), ParticleTrap< CloudType >::preEvolve(), fvMatrix< Type >::relax(), general::sample(), ConeInjection< CloudType >::setProperties(), ConeNozzleInjection< CloudType >::setProperties(), primaryRadiation::Shs(), standardRadiation::Shs(), constantRadiation::Shs(), PBiCCCG< Type, DType, LUType >::solve(), PBiCICG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCG::solve(), PCG::solve(), PBiCGStab::solve(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), ThermoSurfaceFilm< CloudType >::splashDirection(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), advectiveFvPatchField< Type >::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), Explicit< CloudType >::velocityCorrection(), while(), FacePostProcessing< CloudType >::write(), ParticleCollector< CloudType >::write(), PengRobinsonGas< Specie >::Z(), explicitPorositySource::~explicitPorositySource(), HarrisCrighton::~HarrisCrighton(), and optionList::~optionList().