OpenFOAM: applications/solvers/stressAnalysis/solidDisplacementFoam/readMechanicalProperties.H File Reference
readMechanicalProperties.H File Reference
Functions
IOobject rhoIO ("rho", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
if (rhoType=="uniform")
const dictionary & EDict (mechanicalProperties.subDict("E"))
word EType (EDict.lookup("type"))
IOobject EHeader ("E", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
if (EType=="uniform")
IOobject nuIO ("nu", runTime.timeName(0), mesh, IOobject::NO_READ, IOobject::NO_WRITE)
const dictionary & nuDict (mechanicalProperties.subDict("nu"))
word nuType (nuDict.lookup("type"))
if (nuType=="uniform")
Variables
Info<< "Reading mechanical properties\"<< endl;IOdictionary mechanicalProperties(IOobject("mechanicalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));const dictionary &rhoDict(mechanicalProperties.subDict("rho"));word rhoType(rhoDict.lookup("type"));autoPtr< volScalarField > rhoPtr
else
volScalarField & rho = rhoPtr()
autoPtr< volScalarField > EPtr
volScalarField & rhoE = EPtr()
autoPtr< volScalarField > nuPtr
volScalarField & nu = nuPtr()
Function Documentation
rhoIO()
IOobject rhoIO ("rho" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
if() [1/3]
else if (rhoType = = "uniform")
Definition at line 29 of file readMechanicalProperties.H.
References Foam::dimMass, Foam::dimVolume, mesh, readScalar, and rhoIO().
EDict()
const dictionary& EDict (mechanicalProperties. subDict"E")
Referenced by if().
EType()
word EType (EDict. lookup"type")
Referenced by if().
EHeader()
IOobject EHeader ("E" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
if() [2/3]
else if (EType = = "uniform")
Definition at line 84 of file readMechanicalProperties.H.
References Foam::abort(), Foam::dimLength, Foam::dimMass, Foam::dimTime, EDict(), EHeader(), EType(), Foam::FatalError, FatalErrorInFunction, mesh, readScalar, and Foam::sqr().
nuIO()
IOobject nuIO ("nu" , runTime. timeName0, mesh , IOobject::NO_READ , IOobject::NO_WRITE)
Referenced by if().
nuDict()
const dictionary& nuDict (mechanicalProperties. subDict"nu")
Referenced by if().
nuType()
word nuType (nuDict. lookup"type")
Referenced by if().
if() [3/3]
else if (nuType = = "uniform")
Definition at line 139 of file readMechanicalProperties.H.
References Foam::abort(), Foam::dimless, Foam::FatalError, FatalErrorInFunction, mesh, nuDict(), nuIO(), nuType(), and readScalar.
Variable Documentation
rhoPtr
Info<< "Reading mechanical properties\n" << endl; IOdictionary mechanicalProperties (IOobject ("mechanicalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); const dictionary& rhoDict(mechanicalProperties.subDict("rho")); word rhoType(rhoDict.lookup("type")); autoPtr<volScalarField> rhoPtr
Definition at line 18 of file readMechanicalProperties.H.
else
else
Initial value:
{
        FatalErrorInFunction
            << "Valid type entries are uniform or field for rho"
            << abort(FatalError)
Definition at line 62 of file readMechanicalProperties.H.
rho
volScalarField& rho = rhoPtr()
Definition at line 68 of file readMechanicalProperties.H.
EPtr
autoPtr<volScalarField> EPtr
Definition at line 73 of file readMechanicalProperties.H.
rhoE
volScalarField& rhoE = EPtr()
Definition at line 123 of file readMechanicalProperties.H.
nuPtr
autoPtr<volScalarField> nuPtr
Definition at line 125 of file readMechanicalProperties.H.
nu
volScalarField& nu = nuPtr()
Definition at line 176 of file readMechanicalProperties.H.
Referenced by SpalartAllmarasDES< BasicTurbulenceModel >::chi(), SpalartAllmaras< BasicTurbulenceModel >::chi(), NoPhaseChange< CloudType >::clone(), LiquidEvaporation< CloudType >::clone(), LiquidEvaporationBoil< CloudType >::clone(), ORourkeCollision< CloudType >::collideParcels(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), DarcyForchheimer::correct(), realizableKE< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), qZeta::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), ShihQuadraticKE::DepsilonEff(), LamBremhorstKE::DepsilonEff(), LienLeschziner::DepsilonEff(), LienCubicKE::DepsilonEff(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::DepsilonEff(), LaunderSharmaKE< BasicTurbulenceModel >::DepsilonEff(), realizableKE< BasicTurbulenceModel >::DepsilonEff(), RNGkEpsilon< BasicTurbulenceModel >::DepsilonEff(), SSG< BasicTurbulenceModel >::DepsilonEff(), LRR< BasicTurbulenceModel >::DepsilonEff(), v2f< BasicTurbulenceModel >::DepsilonEff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::devRhoReff(), Maxwell< BasicTurbulenceModel >::devRhoReff(), forces::devRhoReff(), kOmegaSSTLM< BasicTurbulenceModel >::DgammaIntEff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), LamBremhorstKE::DkEff(), ShihQuadraticKE::DkEff(), kOmega< BasicTurbulenceModel >::DkEff(), dynamicLagrangian< BasicTurbulenceModel >::DkEff(), LienLeschziner::DkEff(), kEqn< BasicTurbulenceModel >::DkEff(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::DkEff(), LienCubicKE::DkEff(), LaunderSharmaKE< BasicTurbulenceModel >::DkEff(), realizableKE< BasicTurbulenceModel >::DkEff(), RNGkEpsilon< BasicTurbulenceModel >::DkEff(), dynamicKEqn< BasicTurbulenceModel >::DkEff(), v2f< BasicTurbulenceModel >::DkEff(), kkLOmega::DkEff(), SpalartAllmaras< BasicTurbulenceModel >::DnuTildaEff(), SpalartAllmarasDES< BasicTurbulenceModel >::DnuTildaEff(), kOmega< BasicTurbulenceModel >::DomegaEff(), kkLOmega::DomegaEff(), qZeta::DqEff(), SSG< BasicTurbulenceModel >::DREff(), LRR< BasicTurbulenceModel >::DREff(), qZeta::DzetaEff(), LienLeschziner::E(), LienCubicKE::E(), kOmegaSSTLM< BasicTurbulenceModel >::F1(), qZeta::f2(), LienLeschziner::f2(), LaunderSharmaKE< BasicTurbulenceModel >::f2(), LienCubicKE::f2(), qZeta::fMu(), LienLeschziner::fMu(), LaunderSharmaKE< BasicTurbulenceModel >::fMu(), LienCubicKE::fMu(), kOmegaSSTLM< BasicTurbulenceModel >::gammaInt(), v2f< BasicTurbulenceModel >::Ls(), solidParticleCloud::move(), incompressibleTurbulenceModel::mu(), forces::mu(), Maxwell< BasicTurbulenceModel >::nu0(), Stokes< BasicTurbulenceModel >::nuEff(), continuousGasKEpsilon< BasicTurbulenceModel >::nuEff(), laminarModel< BasicTurbulenceModel >::nuEff(), LESModel< BasicTurbulenceModel >::nuEff(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::nuEff(), PairSpringSliderDashpot< CloudType >::PairSpringSliderDashpot(), multiNormal::sample(), v2f< BasicTurbulenceModel >::Ts(), LISAAtomization< CloudType >::update(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), and WallSpringSliderDashpot< CloudType >::WallSpringSliderDashpot().