OpenFOAM: applications/solvers/stressAnalysis/solidDisplacementFoam/readSolidDisplacementFoamControls.H File Reference
readSolidDisplacementFoamControls.H File Reference
Functions
stressControl lookup ("compactNormalStress") >> compactNormalStress
Variables
nCorr = stressControl.lookupOrDefault<int>("nCorrectors", 1)
convergenceTolerance = readScalar(stressControl.lookup("D"))
Function Documentation
lookup()
stressControl lookup ("compactNormalStress")
Referenced by boundaryRegion::boundaryTypes(), laminar< Type >::correct(), displacementLaplacianFvMotionSolver::diffusivity(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), FacePostProcessing< CloudType >::FacePostProcessing(), if(), InflationInjection< CloudType >::InflationInjection(), InjectionModel< CloudType >::InjectionModel(), cellTable::materialTypes(), displacementMeshMoverMotionSolver::meshMover(), boundaryRegion::names(), cellTable::names(), Foam::operator>>(), PairSpringSliderDashpot< CloudType >::PairSpringSliderDashpot(), dictionary::parent(), ParticleCollector< CloudType >::ParticleCollector(), ParticleErosion< CloudType >::ParticleErosion(), PatchPostProcessing< CloudType >::PatchPostProcessing(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), SRFModel::read(), combustionModel::read(), interfaceProperties::read(), STARCDsurfaceFormatCore::readInpCellTable(), rigidBodyMeshMotion::rigidBodyMeshMotion(), cellTable::selectType(), sixDoFRigidBodyMotionSolver::sixDoFRigidBodyMotionSolver(), solution::solutionDict(), rigidBodyMeshMotion::solve(), UnsortedMeshedSurface< Face >::sortedZones(), StandardWallInteraction< CloudType >::StandardWallInteraction(), velocityComponentLaplacianFvMotionSolver::updateMesh(), velocityLaplacianFvMotionSolver::updateMesh(), displacementSBRStressFvMotionSolver::updateMesh(), displacementComponentLaplacianFvMotionSolver::updateMesh(), USERD_get_part_elements_by_type(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), WallSpringSliderDashpot< CloudType >::WallSpringSliderDashpot(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
Variable Documentation
nCorr
nCorr = stressControl.lookupOrDefault<int>("nCorrectors", 1)
Definition at line 1 of file readSolidDisplacementFoamControls.H.
convergenceTolerance
convergenceTolerance = readScalar(stressControl.lookup("D"))
Definition at line 2 of file readSolidDisplacementFoamControls.H.