OpenFOAM: Foam::constant::mathematical Namespace Reference
Foam::constant::mathematical Namespace Reference
mathematical constants.
Functions
const scalar e (M_E)
const scalar pi (M_PI)
const scalar twoPi (2 *pi)
const scalar piByTwo (0.5 *pi)
Variables
static const char *const group = "mathematical"
Detailed Description
mathematical constants.
Function Documentation
e()
const scalar Foam::constant::mathematical::e (M_E)
Referenced by LiquidEvaporationBoil< CloudType >::calculate(), and ORourkeCollision< CloudType >::collideSorted().
pi()
const scalar Foam::constant::mathematical::pi (M_PI)
Referenced by KinematicParcel< ParcelType >::areaS(), primitiveMeshTools::boundaryFaceSkewness(), ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), targetCoeffTrim::calcCoeffs(), BrownianMotionForce< CloudType >::calcCoupled(), LiquidEvaporation< CloudType >::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), COxidationDiffusionLimitedRate< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), rotorDiskSource::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), ORourkeCollision< CloudType >::collide(), ORourkeCollision< CloudType >::collideParcels(), drippingInjection::correct(), radiativeIntensityRay::correct(), cubic< Type >::correction(), pointLinear< Type >::correction(), rotorDiskSource::createCoordinateSystem(), Foam::degToRad(), normal::erfInv(), primitiveMeshTools::faceSkewness(), FieldActivatedInjection< CloudType >::FieldActivatedInjection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), cylindricalCS::globalToLocal(), if(), FreeStream< CloudType >::inflow(), surfaceInterpolationScheme< GType >::interpolate(), Foam::kShellIntegration(), cylindricalCS::localToGlobal(), primitiveMesh::makeFaceCentresAndAreas(), ManualInjection< CloudType >::ManualInjection(), DSMCCloud< DSMCParcel< ParcelType > >::maxwellianAverageSpeed(), sixDoFRigidBodyMotion::omega(), equilibrium::oneByTau(), isotropic::oneByTau(), nonEquilibrium::oneByTau(), Foam::operator<<(), PairSpringSliderDashpot< CloudType >::overlapArea(), IATEsource::phi(), ParticleErosion< CloudType >::postPatch(), Foam::radToDeg(), rigidBodyMeshMotion::rigidBodyMeshMotion(), InjectionModel< CloudType >::setNumberOfParticles(), SurfaceFilmModel< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::setParcelProperties(), ConeNozzleInjection< CloudType >::setProperties(), DSMCParcel< ParcelType >::constantProperties::sigmaT(), VariableHardSphere< CloudType >::sigmaTcR(), LarsenBorgnakkeVariableHardSphere< CloudType >::sigmaTcR(), sixDoFRigidBodyMotionSolver::sixDoFRigidBodyMotionSolver(), symplectic::solve(), Newmark::solve(), CrankNicolson::solve(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), TDACChemistryModel< CompType, ThermoType >::solve(), chemistryModel< CompType, ThermoType >::solve(), ThermoSurfaceFilm< CloudType >::splashDirection(), ThermoSurfaceFilm< CloudType >::splashInteraction(), face::sweptVol(), chemistryModel< CompType, ThermoType >::tc(), oscillatingRotatingMotion::transformation(), tabulated6DoFMotion::transformation(), SDA::transformation(), STARCDCoordinateRotation::transformVector(), EulerCoordinateRotation::transformVector(), ReitzKHRT< CloudType >::update(), BlobsSheetAtomization< CloudType >::update(), LISAAtomization< CloudType >::update(), SHF< CloudType >::update(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), swirlFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), cylindricalInletVelocityFvPatchVectorField::updateCoeffs(), CellZoneInjection< CloudType >::updateMesh(), KinematicParcel< ParcelType >::volume(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), regionSizeDistribution::write(), and PengRobinsonGas< Specie >::Z().
twoPi()
const scalar Foam::constant::mathematical::twoPi (2 * pi)
Referenced by BrownianMotionForce< CloudType >::calcCoupled(), rotorDiskSource::calculate(), VariableHardSphere< CloudType >::collide(), LarsenBorgnakkeVariableHardSphere< CloudType >::collide(), noiseFFT::Hanning(), Kmesh::Kmesh(), rpm::read(), rotorDiskSource::read(), rpm::rpm(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeInjection< CloudType >::setProperties(), ThermoSurfaceFilm< CloudType >::splashDirection(), SDA::transformation(), turbGen::U(), StochasticDispersionRAS< CloudType >::update(), ReitzKHRT< CloudType >::update(), dynamicInkJetFvMesh::update(), ETAB< CloudType >::update(), TAB< CloudType >::update(), SHF< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), and Sine< Type >::value().
piByTwo()
const scalar Foam::constant::mathematical::piByTwo (0.5 * pi)
Referenced by Foam::pseudoAngle(), and SDA::transformation().
Variable Documentation
group
const char* const group = "mathematical" static
Definition at line 48 of file mathematicalConstants.H.