OpenFOAM: Foam::MULES Namespace Reference
Foam::MULES Namespace Reference
Functions
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void correct (const RdeltaTType &rDeltaT, const RhoType &rho, volScalarField &psi, const surfaceScalarField &phi, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su)
template<class RhoType , class SpType , class SuType >
void correct (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
void correct (volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const scalar psiMax, const scalar psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void limiterCorr (scalarField &allLambda, const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void limitCorr (const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
template<class RhoType , class SpType , class SuType >
void implicitSolve (const RhoType &rho, volScalarField &gamma, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
void implicitSolve (volScalarField &gamma, const surfaceScalarField &phi, surfaceScalarField &phiCorr, const scalar psiMax, const scalar psiMin)
template<class RhoType >
tmp< surfaceScalarField > interpolate (const RhoType &rho)
template<>
tmp< surfaceScalarField > interpolate (const volScalarField &rho)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void explicitSolve (const RdeltaTType &rDeltaT, const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su)
template<class RhoType , class SpType , class SuType >
void explicitSolve (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su)
template<class RhoType , class SpType , class SuType >
void explicitSolve (const RhoType &rho, volScalarField &psi, const surfaceScalarField &phiBD, surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
void explicitSolve (volScalarField &psi, const surfaceScalarField &phiBD, surfaceScalarField &phiPsi, const scalar psiMax, const scalar psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void limiter (scalarField &allLambda, const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phiBD, const surfaceScalarField &phiCorr, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin)
template<class RdeltaTType , class RhoType , class SpType , class SuType >
void limit (const RdeltaTType &rDeltaT, const RhoType &rho, const volScalarField &psi, const surfaceScalarField &phi, surfaceScalarField &phiPsi, const SpType &Sp, const SuType &Su, const scalar psiMax, const scalar psiMin, const bool returnCorr)
void limitSum (UPtrList< scalarField > &phiPsiCorrs)
template<class SurfaceScalarFieldList >
void limitSum (SurfaceScalarFieldList &phiPsiCorrs)
Function Documentation
correct() [1/3]
void correct (const RdeltaTType & rDeltaT, const RhoType & rho, volScalarField & psi, const surfaceScalarField & phi, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su)
Definition at line 37 of file CMULESTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::endl(), Foam::Info, mesh, DimensionedField< Type, GeoMesh >::mesh(), polyMesh::moving(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), List< T >::size(), and Foam::fvc::surfaceIntegrate().
correct() [2/3]
void correct (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
Definition at line 79 of file CMULESTemplates.C.
References correct, TimeState::deltaTValue(), limitCorr(), limiterCorr(), mesh, DimensionedField< Type, GeoMesh >::mesh(), and fvMesh::time().
correct() [3/3]
void correct (volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const scalar psiMax, const scalar psiMin)
Definition at line 31 of file CMULES.C.
References correct.
limiterCorr()
void limiterCorr (scalarField & allLambda, const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
Definition at line 134 of file CMULESTemplates.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), fvPatchField< Type >::coupled(), Foam::dimless, forAll, lambda(), limitCorr(), dictionary::lookup(), dictionary::lookupOrDefault(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), IOobject::name(), fvMesh::neighbour(), fvMesh::owner(), patchi, fvPatchField< Type >::patchNeighbourField(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), psi, Foam::readLabel(), List< T >::size(), solution::solverDict(), fvMesh::time(), Time::timeName(), and fvMesh::Vsc().
Referenced by correct(), and limitCorr().
limitCorr()
void limitCorr (const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
Definition at line 467 of file CMULESTemplates.C.
References Foam::dimless, lambda(), limiterCorr(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nFaces(), fvMesh::time(), and Time::timeName().
Referenced by correct(), and limiterCorr().
implicitSolve() [1/2]
void implicitSolve (const RhoType & rho, volScalarField & gamma, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
fv::gaussLaplacianScheme<scalar, scalar>(mesh, CDs, snGrads)
.fvmLaplacian(Dpsif, psi)
Definition at line 57 of file IMULESTemplates.C.
References Foam::fvm::ddt(), TimeState::deltaT(), TimeState::deltaTValue(), Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimless, Foam::dimVelocity, Foam::fvc::div(), Foam::endl(), fvMatrix< Type >::flux(), Foam::gMax(), Foam::gMin(), Foam::Info, interpolate(), lambda(), limiter(), dictionary::lookup(), Foam::mag(), fvMesh::magSf(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), IOobject::name(), primitiveMesh::nFaces(), IOobject::NO_READ, IOobject::NO_WRITE, psi, Foam::readLabel(), Foam::readScalar(), rho, Foam::solve(), solution::solverDict(), Foam::fvc::Sp(), Foam::fvm::Sp(), Foam::fvc::Su(), fvMesh::time(), and Time::timeName().
Referenced by implicitSolve(), and interpolate().
implicitSolve() [2/2]
void implicitSolve (volScalarField & gamma, const surfaceScalarField & phi, surfaceScalarField & phiCorr, const scalar psiMax, const scalar psiMin)
Definition at line 31 of file IMULES.C.
References implicitSolve().
interpolate() [1/2]
tmp<surfaceScalarField> Foam::MULES::interpolate (const RhoType & rho) inline
Definition at line 40 of file IMULESTemplates.C.
References NotImplemented.
Referenced by Foam::fvc::absolute(), Implicit< CloudType >::cacheFields(), pointLinear< Type >::correction(), limitedSurfaceInterpolationScheme< Type >::flux(), for(), forAll(), forAllIter(), faceCorrectedSnGrad< Type >::fullGradCorrection(), surfaceFieldValue::getFieldValues(), if(), implicitSolve(), interRegionHeatTransferModel::interpolate(), cyclicAMIPolyPatch::interpolate(), interpolationCellPointWallModified< Type >::interpolate(), interpolationCellPoint< Foam::Vector >::interpolate(), interpolationPointMVC< Type >::interpolate(), surfaceInterpolationScheme< GType >::interpolate(), meshToMesh0::interpolate(), sampledCuttingPlane::interpolateField(), sampledIsoSurface::interpolateField(), distanceSurface::interpolateField(), uniformInterpolationTable< scalar >::interpolateLog10(), PhiScheme< Type, PhiLimiter >::limiter(), interpolationLookUpTable< scalar >::lookUp(), Foam::fvc::makeAbsolute(), Foam::fvc::makeRelative(), isoSurface::meshCells(), Foam::fvc::relative(), GAMGSolver::solve(), while(), and AveragingMethod< Foam::Vector >::write().
interpolate() [2/2]
tmp<surfaceScalarField> Foam::MULES::interpolate (const volScalarField & rho) inline
Definition at line 47 of file IMULESTemplates.C.
References implicitSolve(), and Foam::fvc::interpolate().
explicitSolve() [1/4]
void explicitSolve (const RdeltaTType & rDeltaT, const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su)
Definition at line 38 of file MULESTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::endl(), Foam::Info, mesh, DimensionedField< Type, GeoMesh >::mesh(), polyMesh::moving(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), psi, Foam::fvc::surfaceIntegrate(), fvMesh::Vsc(), and fvMesh::Vsc0().
Referenced by explicitSolve(), and for().
explicitSolve() [2/4]
void explicitSolve (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su)
Definition at line 83 of file MULESTemplates.C.
References TimeState::deltaTValue(), explicitSolve(), mesh, DimensionedField< Type, GeoMesh >::mesh(), and fvMesh::time().
explicitSolve() [3/4]
void explicitSolve (const RhoType & rho, volScalarField & psi, const surfaceScalarField & phiBD, surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
Definition at line 108 of file MULESTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), TimeState::deltaTValue(), explicitSolve(), limit(), limiter(), mesh, DimensionedField< Type, GeoMesh >::mesh(), and fvMesh::time().
explicitSolve() [4/4]
void explicitSolve (volScalarField & psi, const surfaceScalarField & phiBD, surfaceScalarField & phiPsi, const scalar psiMax, const scalar psiMin)
Definition at line 31 of file MULES.C.
References explicitSolve().
limiter()
void limiter (scalarField & allLambda, const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phiBD, const surfaceScalarField & phiCorr, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin)
Definition at line 168 of file MULESTemplates.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), fvPatchField< Type >::coupled(), Foam::dimless, forAll, lambda(), limit(), dictionary::lookupOrDefault(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), polyMesh::moving(), IOobject::name(), fvMesh::neighbour(), GeometricField< Type, PatchField, GeoMesh >::oldTime(), fvMesh::owner(), patchi, fvPatchField< Type >::patchNeighbourField(), psi, List< T >::size(), solution::solverDict(), fvMesh::time(), Time::timeName(), fvMesh::Vsc(), and fvMesh::Vsc0().
Referenced by faceLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::cellLimitedGrad(), limitedSnGrad< Type >::correction(), limiterBlended< Type >::correction(), explicitSolve(), for(), implicitSolve(), limiterBlended< Type >::interpolate(), limit(), PhiScheme< Type, PhiLimiter >::limiter(), makeFvGradScheme(), multivariateScheme< Type, Scheme >::multivariateScheme(), multivariateSelectionScheme< Type >::multivariateSelectionScheme(), limitWith< Type >::weights(), limiterBlended< Type >::weights(), and limitedSurfaceInterpolationScheme< Type >::weights().
limit()
void limit (const RdeltaTType & rDeltaT, const RhoType & rho, const volScalarField & psi, const surfaceScalarField & phi, surfaceScalarField & phiPsi, const SpType & Sp, const SuType & Su, const scalar psiMax, const scalar psiMin, const bool returnCorr)
Definition at line 535 of file MULESTemplates.C.
References Foam::dimless, Foam::fvc::flux(), lambda(), limiter(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nFaces(), phi, fvMesh::time(), and Time::timeName().
Referenced by explicitSolve(), limiter(), and thermo< Thermo, Type >::thermo().
limitSum() [1/2]
void limitSum (UPtrList< scalarField > & phiPsiCorrs)
Definition at line 51 of file MULES.C.
References forAll, lambda(), phasei, UPtrList< T >::size(), and Foam::sum().
Referenced by limitSum().
limitSum() [2/2]
void limitSum (SurfaceScalarFieldList & phiPsiCorrs)
Definition at line 600 of file MULESTemplates.C.
References forAll, limitSum(), patchi, and phasei.