OpenFOAM: Foam::stringOps Namespace Reference
Foam::stringOps Namespace Reference
Collection of static functions to do various simple string-related operations.
Functions
string expand (const string &, const HashTable< string, word, string::hash > &mapping, const char sigil='$')
Expand occurences of variables according to the mapping.
string & inplaceExpand (string &, const HashTable< string, word, string::hash > &mapping, const char sigil='$')
Inplace expand occurences of variables according to the mapping.
string expand (const string &, const dictionary &dict, const char sigil='$')
Expand occurences of variables according to the dictionary.
string getVariable (const word &name, const dictionary &dict, const bool allowEnvVars, const bool allowEmpty)
Get dictionary or (optionally) environment variable.
string expand (const string &s, string::size_type &index, const dictionary &dict, const bool allowEnvVars, const bool allowEmpty)
Recursively expands (dictionary or environment) variable.
string & inplaceExpand (string &s, const dictionary &dict, const bool allowEnvVars, const bool allowEmpty, const char sigil='$')
Inplace expand occurences of variables according to the dictionary.
string & inplaceExpand (string &, const dictionary &dict, const char sigil='$')
Inplace expand occurences of variables according to the dictionary.
string expand (const string &, const bool allowEmpty=false)
Expand initial tildes and all occurences of environment variables.
string & inplaceExpand (string &, const bool allowEmpty=false)
Expand initial tildes and all occurences of environment variables.
string trimLeft (const string &)
Return string trimmed of leading whitespace.
string & inplaceTrimLeft (string &)
Trim leading whitespace inplace.
string trimRight (const string &)
Return string trimmed of trailing whitespace.
string & inplaceTrimRight (string &)
Trim trailing whitespace inplace.
string trim (const string &)
Return string trimmed of leading and trailing whitespace.
string & inplaceTrim (string &)
Trim leading and trailing whitespace inplace.
Detailed Description
Collection of static functions to do various simple string-related operations.
Source files
stringOps.H
stringOps.C
Function Documentation
expand() [1/4]
Foam::string expand (const string & original, const HashTable< string, word, string::hash > & mapping, const char sigil = '$')
Expand occurences of variables according to the mapping.
Expansion includes:
variables
"$VAR", "${VAR}"
Supports default values as per the Bourne/Korn shell.
"${parameter:-defValue}"
If parameter is unset or null, the defValue is substituted. Otherwise, the value of parameter is substituted.
Supports alternative values as per the Bourne/Korn shell.
"${parameter:+altValue}"
If parameter is unset or null, nothing is substituted. Otherwise the altValue is substituted.
Any unknown entries are removed silently.
Malformed entries (eg, brace mismatch, sigil followed by bad character) are left as is.
Note
the leading sigil can be changed to avoid conflicts with other string expansions
Definition at line 75 of file stringOps.C.
References inplaceExpand(), and s().
Referenced by chemkinReader::chemkinReader(), dynamicCode::copyOrCreateFiles(), expand(), functionObjectList::findDict(), getVariable(), inplaceExpand(), dlLibraryTable::open(), tabulated6DoFAcceleration::read(), and tabulated6DoFMotion::read().
inplaceExpand() [1/4]
Foam::string & inplaceExpand (string & s, const HashTable< string, word, string::hash > & mapping, const char sigil = '$')
Inplace expand occurences of variables according to the mapping.
Expansion includes:
variables
"$VAR", "${VAR}"
Supports default values as per the Bourne/Korn shell.
"${parameter:-defValue}"
If parameter is unset or null, the defValue is substituted. Otherwise, the value of parameter is substituted.
Supports alternative values as per the Bourne/Korn shell.
"${parameter:+altValue}"
If parameter is unset or null, nothing is substituted. Otherwise the altValue is substituted.
Any unknown entries are removed silently.
Malformed entries (eg, brace mismatch, sigil followed by bad character) are left as is.
Note
the leading sigil can be changed to avoid conflicts with other string expansions
Definition at line 87 of file stringOps.C.
References expand(), HashTable< T, Key, Hash >::find(), and s().
Referenced by dynamicCode::copyAndFilter(), dynamicCodeContext::dynamicCodeContext(), expand(), string::expand(), includeEntry::includeFileName(), inplaceExpand(), entry::New(), codedFunctionObject::read(), and CodedSource< Type >::read().
expand() [2/4]
Foam::string expand (const string & original, const dictionary & dict, const char sigil = '$')
Expand occurences of variables according to the dictionary.
Expansion includes:
variables
"$VAR", "${VAR}"
Any unknown entries are left as-is
Note
the leading sigil can be changed to avoid conflicts with other string expansions
Definition at line 241 of file stringOps.C.
References getVariable(), inplaceExpand(), and s().
getVariable()
Foam::string getVariable (const word & name, const dictionary & dict, const bool allowEnvVars, const bool allowEmpty)
Get dictionary or (optionally) environment variable.
Definition at line 253 of file stringOps.C.
References Foam::exit(), expand(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::fixed(), Foam::getEnv(), dictionary::lookupScopedEntryPtr(), OSstream::precision(), OStringStream::str(), and write().
Referenced by expand(), and inplaceExpand().
expand() [3/4]
Foam::string expand (const string & s, string::size_type & index, const dictionary & dict, const bool allowEnvVars, const bool allowEmpty)
Recursively expands (dictionary or environment) variable.
starting at index in string. Updates index.
Definition at line 311 of file stringOps.C.
References expand(), getVariable(), and inplaceExpand().
inplaceExpand() [2/4]
Foam::string & inplaceExpand (string & s, const dictionary & dict, const bool allowEnvVars, const bool allowEmpty, const char sigil = '$')
Inplace expand occurences of variables according to the dictionary.
and optionally environment variables Expansion includes:
variables
"$VAR", "${VAR}"
with the "${}" syntax doing a recursive substitution. Any unknown entries are left as-is
Note
the leading sigil can be changed to avoid conflicts with other string expansions
Definition at line 345 of file stringOps.C.
References Foam::cwd(), expand(), Foam::findEtcFile(), getVariable(), Foam::home(), inplaceExpand(), and s().
inplaceExpand() [3/4]
Foam::string & inplaceExpand (string & s, const dictionary & dict, const char sigil = '$')
Inplace expand occurences of variables according to the dictionary.
Expansion includes:
variables
"$VAR", "${VAR}"
Any unknown entries are left as-is
Note
the leading sigil can be changed to avoid conflicts with other string expansions
Definition at line 502 of file stringOps.C.
References expand(), Foam::fixed(), dictionary::lookupScopedEntryPtr(), OSstream::precision(), s(), OStringStream::str(), and write().
expand() [4/4]
Foam::string expand (const string & original, const bool allowEmpty = false)
Expand initial tildes and all occurences of environment variables.
Expansion includes:
environment variables
"$VAR", "${VAR}"
current directory
leading "./" : the current directory
tilde expansion
leading "~/" : home directory
leading "~user" : home directory for specified user
leading "~OpenFOAM" : site/user OpenFOAM configuration directory
Supports default values as per the Bourne/Korn shell.
"${parameter:-defValue}"
If parameter is unset or null, the defValue is substituted. Otherwise, the value of parameter is substituted.
Supports alternative values as per the Bourne/Korn shell.
"${parameter:+altValue}"
If parameter is unset or null, nothing is substituted. Otherwise the altValue is substituted.
Any unknown entries are removed silently, if allowEmpty is true.
Malformed entries (eg, brace mismatch, sigil followed by bad character) are left as is.
See also
Foam::findEtcFile
Definition at line 629 of file stringOps.C.
References inplaceExpand(), and s().
inplaceExpand() [4/4]
Foam::string & inplaceExpand (string & s, const bool allowEmpty = false)
Expand initial tildes and all occurences of environment variables.
Expansion includes:
environment variables
"$VAR", "${VAR}"
current directory
leading "./" : the current directory
tilde expansion
leading "~/" : home directory
leading "~user" : home directory for specified user
leading "~OpenFOAM" : site/user OpenFOAM configuration directory
Supports default values as per the Bourne/Korn shell.
"${parameter:-defValue}"
If parameter is unset or null, the defValue is substituted. Otherwise, the value of parameter is substituted.
Supports alternative values as per the Bourne/Korn shell.
"${parameter:+altValue}"
If parameter is unset or null, nothing is substituted. Otherwise the altValue is substituted.
Any unknown entries are removed silently, if allowEmpty is true.
Malformed entries (eg, brace mismatch, sigil followed by bad character) are left as is.
Any unknown entries are removed silently if allowEmpty is true.
See also
Foam::findEtcFile
Definition at line 640 of file stringOps.C.
References Foam::cwd(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findEtcFile(), Foam::getEnv(), Foam::home(), and s().
trimLeft()
Foam::string trimLeft (const string & s)
Return string trimmed of leading whitespace.
Definition at line 846 of file stringOps.C.
References Foam::isspace(), and s().
Referenced by trim().
inplaceTrimLeft()
Foam::string & inplaceTrimLeft (string & s)
Trim leading whitespace inplace.
Definition at line 866 of file stringOps.C.
References Foam::isspace(), and s().
Referenced by inplaceTrim().
trimRight()
Foam::string trimRight (const string & s)
Return string trimmed of trailing whitespace.
Definition at line 886 of file stringOps.C.
References Foam::isspace(), and s().
Referenced by trim().
inplaceTrimRight()
Foam::string & inplaceTrimRight (string & s)
Trim trailing whitespace inplace.
Definition at line 906 of file stringOps.C.
References Foam::isspace(), and s().
Referenced by inplaceTrim().
trim()
Foam::string trim (const string & original)
Return string trimmed of leading and trailing whitespace.
Definition at line 923 of file stringOps.C.
References trimLeft(), and trimRight().
Referenced by dynamicCodeContext::dynamicCodeContext(), codedFunctionObject::read(), and CodedSource< Type >::read().
inplaceTrim()
Foam::string & inplaceTrim (string & s)
Trim leading and trailing whitespace inplace.
Definition at line 929 of file stringOps.C.
References inplaceTrimLeft(), inplaceTrimRight(), and s().