OpenFOAM: Foam::fvc Namespace Reference
Foam::fvc Namespace Reference
Namespace of functions to calculate explicit derivatives.
Functions
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > &)
Area-weighted average a surfaceField creating a volField.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
Area-weighted average a surfaceField creating a volField.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const CombineOp &cop, const Type &nullValue=pTraits< Type >::zero)
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &, const CombineOp &cop, const Type &nullValue=pTraits< Type >::zero)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &psi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > &tphi, const GeometricField< Type, fvPatchField, volMesh > &psi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh &mesh)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensionedScalar &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf, const one &)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
geometricZeroField ddt (const one &, const one &)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
template<class Type >
tmp< GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > > ddtCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > &phi)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvvf, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh >> div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const surfaceScalarField &flux, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< surfaceScalarField > &tflux, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
tmp< surfaceScalarField > flux (const volVectorField &vvf)
Return the face-flux field obtained from the given volVectorField.
tmp< surfaceScalarField > flux (const tmp< volVectorField > &tvvf)
Return the face-flux field obtained from the given tmp volVectorField.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type , class GType >
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
tmp< surfaceScalarField > meshPhi (const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const dimensionedScalar &rho, const volVectorField &U)
tmp< surfaceScalarField > meshPhi (const volScalarField &rho, const volVectorField &U)
void makeRelative (surfaceScalarField &phi, const volVectorField &U)
Make the given flux relative.
void makeRelative (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
Make the given flux relative.
void makeRelative (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
Make the given flux relative.
void makeAbsolute (surfaceScalarField &phi, const volVectorField &U)
Make the given flux absolute.
void makeAbsolute (surfaceScalarField &phi, const dimensionedScalar &rho, const volVectorField &U)
Make the given flux absolute.
void makeAbsolute (surfaceScalarField &phi, const volScalarField &rho, const volVectorField &U)
Make the given flux absolute.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
Return the given absolute flux in relative form.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
Return the given absolute flux in relative form.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volVectorField &U)
Return the given relative flux in absolute form.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &tphi, const volScalarField &rho, const volVectorField &U)
Return the given relative flux in absolute form.
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh >> reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
template<class Type >
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
tmp< volScalarField > reconstructMag (const surfaceScalarField &)
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > &)
void smooth (volScalarField &field, const scalar coeff)
void spread (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2, const scalar alphaMax=0.99, const scalar alphaMin=0.01)
void sweep (volScalarField &field, const volScalarField &alpha, const label nLayers, const scalar alphaDiff=0.2)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > &su, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tsu, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const dimensionedScalar &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const volScalarField &sp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const tmp< volScalarField > &tsp, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
void surfaceIntegrate (Field< Type > &ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > &ssf)
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tssf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh >> &tdf)
template<class Type >
dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
template<class Type >
dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > &df)
template<class Type >
dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh >> &tdf)
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const surfaceScalarField &faceFlux, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp< surfaceInterpolationScheme< Type > > scheme (const fvMesh &mesh, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const surfaceScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const surfaceScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const tmp< surfaceScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf, const word &name)
Interpolate field onto faces using scheme given by name in fvSchemes.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &tvf)
Interpolate field onto faces using 'interpolate(<name>)'.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
Interpolate tmp field onto faces using 'interpolate(<name>)'.
template<class Type >
static tmp< FieldField< fvsPatchField, Type > > interpolate (const FieldField< fvPatchField, Type > &fvpff)
Interpolate boundary field onto faces (simply a type conversion)
template<class Type >
static tmp< FieldField< fvsPatchField, Type > > interpolate (const tmp< FieldField< fvPatchField, Type >> &tfvpff)
Interpolate boundary field onto faces (simply a type conversion)
one interpolate (const one &)
Interpolate 'one' returning 'one'.
template<class Type >
static tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &tvf)
Interpolate field onto faces.
template<class Type >
static tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvf)
Interpolate tmp field onto faces.
Detailed Description
Namespace of functions to calculate explicit derivatives.
Function Documentation
average() [1/4]
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Area-weighted average a surfaceField creating a volField.
Definition at line 46 of file fvcAverage.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), tmp< T >::ref(), and surfaceSum().
Referenced by average(), Dual< Type >::average(), Foam::bound(), if(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints(), and while().
average() [2/4]
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Area-weighted average a surfaceField creating a volField.
Definition at line 93 of file fvcAverage.C.
References average().
average() [3/4]
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const GeometricField< Type, fvPatchField, volMesh > & vtf)
Area-weighted average a surfaceField creating a volField.
Definition at line 109 of file fvcAverage.C.
References average(), and Foam::linearInterpolate().
average() [4/4]
tmp< GeometricField< Type, fvPatchField, volMesh > > average (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvtf)
Area-weighted average a surfaceField creating a volField.
Definition at line 120 of file fvcAverage.C.
References average().
cellReduce() [1/2]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::cellReduce (const GeometricField< Type, fvsPatchField, surfaceMesh > & , const CombineOp & cop, const Type & nullValue = pTraits< Type >::zero)
cellReduce() [2/2]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::cellReduce (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & , const CombineOp & cop, const Type & nullValue = pTraits< Type >::zero)
curl() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcCurl.C.
References grad(), IOobject::name(), tmp< T >::ref(), and Foam::skew().
Referenced by LiftForce< CloudType >::cacheFields(), and curl().
curl() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > curl (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 68 of file fvcCurl.C.
References curl().
d2dt2() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
d2dt2() [2/2]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::d2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 60 of file fvcD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
DDt() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 45 of file fvcDDt.C.
References ddt(), div(), DimensionedField< Type, GeoMesh >::mesh(), and psi.
Referenced by DDt().
DDt() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > DDt (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & psi)
Definition at line 67 of file fvcDDt.C.
References tmp< T >::clear(), and DDt().
ddt() [1/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensioned< Type > dt, const fvMesh & mesh)
Definition at line 45 of file fvcDdt.C.
References fvSchemes::ddtScheme(), dimensioned< Type >::name(), and ddtScheme< Type >::New().
Referenced by PressureGradientForce< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), Foam::CorrectPhi(), DDt(), ddt(), for(), forAll(), forAllConstIter(), forAllIter(), boundedDdtScheme< Type >::fvcDdt(), boundedDdtScheme< Type >::fvmDdt(), if(), and while().
ddt() [2/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 61 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [3/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 76 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [4/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 92 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [5/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 108 of file fvcDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [6/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 131 of file fvcDdt.C.
References ddt().
ddt() [7/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf, const one &)
Definition at line 143 of file fvcDdt.C.
References ddt(), and ddtCorr().
ddtCorr() [1/8]
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 155 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
Referenced by ddt(), ddtCorr(), forAllIter(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), and if().
ddtCorr() [2/8]
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 171 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
ddtCorr() [3/8]
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 192 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddtCorr() [4/8]
tmp<GeometricField<typename flux<Type>::type, fvsPatchField, surfaceMesh> > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 209 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
ddt() [8/8]
geometricZeroField Foam::fvc::ddt (const one & , const one &) inline
Definition at line 106 of file fvcDdt.H.
References ddtCorr(), phi, rho, U, and Uf.
ddtCorr() [5/8]
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 155 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
Referenced by ddt(), ddtCorr(), forAllIter(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), and if().
ddtCorr() [6/8]
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 171 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
ddtCorr() [7/8]
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf)
Definition at line 192 of file fvcDdt.C.
References ddtCorr(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddtCorr() [8/8]
tmp< GeometricField < typename Foam::flux<Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::ddtCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< typename Foam::flux< Type >::type, fvsPatchField, surfaceMesh > & phi)
Definition at line 209 of file fvcDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), ddtScheme< Type >::New(), and phi.
div() [1/18]
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 47 of file fvcDiv.C.
References IOobject::name(), and surfaceIntegrate().
Referenced by Implicit< CloudType >::cacheFields(), kEqn< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), Foam::CorrectPhi(), DDt(), div(), linearViscousStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), nonlinearEddyViscosity< incompressible::RASModel >::divDevRhoReff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), for(), forAllConstIter(), forAllIter(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), if(), Foam::MULES::implicitSolve(), displacementSBRStressFvMotionSolver::solve(), reactingOneDim::solveContinuity(), kinematicSingleLayer::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), reactingOneDim::solveSpeciesMass(), while(), and FSD< CombThermoType, ThermoType >::~FSD().
div() [2/18]
tmp< GeometricField< Type, fvPatchField, volMesh > > div (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 65 of file fvcDiv.C.
References div().
div() [3/18]
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 84 of file fvcDiv.C.
References div(), DimensionedField< Type, GeoMesh >::mesh(), divScheme< Type >::New(), and ref().
div() [4/18]
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvvf, const word & name)
Definition at line 105 of file fvcDiv.C.
References div().
div() [5/18]
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 128 of file fvcDiv.C.
References div(), and IOobject::name().
div() [6/18]
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvvf)
Definition at line 145 of file fvcDiv.C.
References div().
div() [7/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 159 of file fvcDiv.C.
References div(), flux(), DimensionedField< Type, GeoMesh >::mesh(), convectionScheme< Type >::New(), and ref().
div() [8/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 177 of file fvcDiv.C.
References tmp< T >::clear(), and div().
div() [9/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 195 of file fvcDiv.C.
References div().
div() [10/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 213 of file fvcDiv.C.
References tmp< T >::clear(), and div().
div() [11/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 232 of file fvcDiv.C.
References div(), and IOobject::name().
div() [12/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 247 of file fvcDiv.C.
References tmp< T >::clear(), and div().
div() [13/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const surfaceScalarField & flux, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 264 of file fvcDiv.C.
References div().
div() [14/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< surfaceScalarField > & tflux, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 281 of file fvcDiv.C.
References tmp< T >::clear(), and div().
div() [15/18]
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > & , const word & name)
Definition at line 84 of file fvcDiv.C.
References div(), DimensionedField< Type, GeoMesh >::mesh(), divScheme< Type >::New(), and ref().
div() [16/18]
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh >> & , const word & name)
Definition at line 105 of file fvcDiv.C.
References div().
div() [17/18]
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 128 of file fvcDiv.C.
References div(), and IOobject::name().
div() [18/18]
tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::div (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
Definition at line 145 of file fvcDiv.C.
References div().
flux() [1/10]
Foam::tmp< Foam::surfaceScalarField > flux (const volVectorField & vvf)
Return the face-flux field obtained from the given volVectorField.
Definition at line 32 of file fvcFlux.C.
References DimensionedField< Type, GeoMesh >::mesh(), and IOobject::name().
Referenced by Foam::fvm::div(), div(), flux(), for(), forAll(), forAllIter(), gaussConvectionScheme< Type >::fvcDiv(), if(), kinematicSingleLayer::kinematicSingleLayer(), Foam::MULES::limit(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), thermoSingleLayer::thermoSingleLayer(), and while().
flux() [2/10]
Foam::tmp< Foam::surfaceScalarField > flux (const tmp< volVectorField > & tvvf)
Return the face-flux field obtained from the given tmp volVectorField.
Definition at line 45 of file fvcFlux.C.
References tmp< T >::clear(), and flux().
flux() [3/10]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 150 of file fvcFluxTemplates.C.
References flux().
flux() [4/10]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcFluxTemplates.C.
References flux(), DimensionedField< Type, GeoMesh >::mesh(), convectionScheme< Type >::New(), and phi.
flux() [5/10]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 63 of file fvcFluxTemplates.C.
References tmp< T >::clear(), and flux().
flux() [6/10]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 81 of file fvcFluxTemplates.C.
References flux().
flux() [7/10]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 99 of file fvcFluxTemplates.C.
References tmp< T >::clear(), and flux().
flux() [8/10]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 118 of file fvcFluxTemplates.C.
References flux(), and IOobject::name().
flux() [9/10]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 133 of file fvcFluxTemplates.C.
References tmp< T >::clear(), and flux().
flux() [10/10]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const tmp< surfaceScalarField > & tphi, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 167 of file fvcFluxTemplates.C.
References tmp< T >::clear(), and flux().
grad() [1/12]
tmp< GeometricField < typename outerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 52 of file fvcGrad.C.
References grad(), gaussGrad< Type >::gradf(), and IOobject::name().
Referenced by GradientDispersionRAS< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), dynamicKEqn< BasicTurbulenceModel >::Ce(), thermocapillaryForce::correct(), diffusion< CombThermoType, ThermoType >::correct(), contactAngleForce::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), ShihQuadraticKE::correct(), Poisson::correct(), LamBremhorstKE::correct(), LienLeschziner::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), cubic< Type >::correction(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), ShihQuadraticKE::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), realizableKE< BasicTurbulenceModel >::correctNut(), LienCubicKE::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correctNut(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), curl(), linearViscousStress< RASModel< BasicTurbulenceModel > >::devRhoReff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::devRhoReff(), Maxwell< BasicTurbulenceModel >::devRhoReff(), forces::devRhoReff(), linearViscousStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), WALE< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), forAllIter(), correctedSnGrad< Type >::fullGradCorrection(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), grad(), if(), dynamicLagrangian< BasicTurbulenceModel >::k(), WALE< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), magSqrGradGrad(), ParticleTrap< CloudType >::preEvolve(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), eddyViscosity< RASModel< BasicTurbulenceModel > >::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), skewCorrected< Type >::skewCorrection(), displacementSBRStressFvMotionSolver::solve(), SpalartAllmaras< BasicTurbulenceModel >::Stilda(), viscosityModel::strainRate(), while(), XiReactionRate::write(), Basic< Type >::~Basic(), FSD< CombThermoType, ThermoType >::~FSD(), and gradScheme< Type >::~gradScheme().
grad() [2/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 69 of file fvcGrad.C.
References grad().
grad() [3/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 92 of file fvcGrad.C.
References grad(), DimensionedField< Type, GeoMesh >::mesh(), and gradScheme< Type >::New().
grad() [4/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 114 of file fvcGrad.C.
References grad().
grad() [5/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 143 of file fvcGrad.C.
References grad(), and IOobject::name().
grad() [6/12]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 160 of file fvcGrad.C.
References grad().
grad() [7/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Definition at line 52 of file fvcGrad.C.
References grad(), gaussGrad< Type >::gradf(), and IOobject::name().
Referenced by GradientDispersionRAS< CloudType >::cacheFields(), PressureGradientForce< CloudType >::cacheFields(), dynamicKEqn< BasicTurbulenceModel >::Ce(), thermocapillaryForce::correct(), diffusion< CombThermoType, ThermoType >::correct(), contactAngleForce::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), ShihQuadraticKE::correct(), Poisson::correct(), LamBremhorstKE::correct(), LienLeschziner::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), cubic< Type >::correction(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), ShihQuadraticKE::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), realizableKE< BasicTurbulenceModel >::correctNut(), LienCubicKE::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correctNut(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), curl(), linearViscousStress< RASModel< BasicTurbulenceModel > >::devRhoReff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::devRhoReff(), Maxwell< BasicTurbulenceModel >::devRhoReff(), forces::devRhoReff(), linearViscousStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), WALE< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), forAllIter(), correctedSnGrad< Type >::fullGradCorrection(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), buoyantKEpsilon< BasicTurbulenceModel >::Gcoef(), grad(), if(), dynamicLagrangian< BasicTurbulenceModel >::k(), WALE< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::k(), SpalartAllmarasDES< BasicTurbulenceModel >::LESRegion(), magSqrGradGrad(), ParticleTrap< CloudType >::preEvolve(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), eddyViscosity< RASModel< BasicTurbulenceModel > >::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), skewCorrected< Type >::skewCorrection(), displacementSBRStressFvMotionSolver::solve(), SpalartAllmaras< BasicTurbulenceModel >::Stilda(), viscosityModel::strainRate(), while(), XiReactionRate::write(), Basic< Type >::~Basic(), FSD< CombThermoType, ThermoType >::~FSD(), and gradScheme< Type >::~gradScheme().
grad() [8/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
Definition at line 69 of file fvcGrad.C.
References grad().
grad() [9/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > & , const word & name)
Definition at line 92 of file fvcGrad.C.
References grad(), DimensionedField< Type, GeoMesh >::mesh(), and gradScheme< Type >::New().
grad() [10/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & , const word & name)
Definition at line 114 of file fvcGrad.C.
References grad().
grad() [11/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 143 of file fvcGrad.C.
References grad(), and IOobject::name().
grad() [12/12]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
Definition at line 160 of file fvcGrad.C.
References grad().
laplacian() [1/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcLaplacian.C.
References DimensionedField< Type, GeoMesh >::mesh(), laplacianScheme< Type, GType >::New(), and ref().
Referenced by Implicit< CloudType >::cacheFields(), Foam::CorrectPhi(), linearViscousStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), for(), forAll(), forAllIter(), if(), laplacian(), laplaceFilter::operator()(), kinematicSingleLayer::pu(), kOmegaSSTSAS< BasicTurbulenceModel >::Qsas(), reactingOneDim::solveEnergy(), and while().
laplacian() [2/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 61 of file fvcLaplacian.C.
References laplacian().
laplacian() [3/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [4/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 89 of file fvcLaplacian.C.
References laplacian().
laplacian() [5/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 107 of file fvcLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
laplacian() [6/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 133 of file fvcLaplacian.C.
References laplacian().
laplacian() [7/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 151 of file fvcLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
laplacian() [8/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const dimensioned< GType > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 176 of file fvcLaplacian.C.
References laplacian().
laplacian() [9/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 195 of file fvcLaplacian.C.
References laplacian(), DimensionedField< Type, GeoMesh >::mesh(), laplacianScheme< Type, GType >::New(), and ref().
laplacian() [10/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 212 of file fvcLaplacian.C.
References laplacian().
laplacian() [11/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 230 of file fvcLaplacian.C.
References laplacian().
laplacian() [12/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 248 of file fvcLaplacian.C.
References laplacian().
laplacian() [13/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 267 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [14/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 284 of file fvcLaplacian.C.
References laplacian(), Foam::name(), and IOobject::name().
laplacian() [15/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 301 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [16/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 318 of file fvcLaplacian.C.
References laplacian(), and Foam::name().
laplacian() [17/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 337 of file fvcLaplacian.C.
References laplacian(), DimensionedField< Type, GeoMesh >::mesh(), laplacianScheme< Type, GType >::New(), and ref().
laplacian() [18/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 354 of file fvcLaplacian.C.
References laplacian().
laplacian() [19/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 372 of file fvcLaplacian.C.
References laplacian().
laplacian() [20/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 389 of file fvcLaplacian.C.
References laplacian().
laplacian() [21/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 408 of file fvcLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [22/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 425 of file fvcLaplacian.C.
References laplacian().
laplacian() [23/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 442 of file fvcLaplacian.C.
References laplacian().
laplacian() [24/24]
tmp< GeometricField< Type, fvPatchField, volMesh > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tgamma, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 458 of file fvcLaplacian.C.
References laplacian().
magSqrGradGrad() [1/2]
tmp< volScalarField > magSqrGradGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 44 of file fvcMagSqrGradGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::component(), grad(), Foam::magSqr(), and tmp< T >::ref().
Referenced by LaunderSharmaKE< BasicTurbulenceModel >::correct(), qZeta::correct(), and magSqrGradGrad().
magSqrGradGrad() [2/2]
tmp< volScalarField > magSqrGradGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 67 of file fvcMagSqrGradGrad.C.
References magSqrGradGrad().
meshPhi() [1/3]
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volVectorField & U)
Definition at line 34 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and Foam::New().
Referenced by absolute(), if(), makeAbsolute(), makeRelative(), meshPhi(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), relative(), movingWallVelocityFvPatchVectorField::updateCoeffs(), and while().
meshPhi() [2/3]
Foam::tmp< Foam::surfaceScalarField > meshPhi (const dimensionedScalar & rho, const volVectorField & U)
Definition at line 47 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), meshPhi(), dimensioned< Type >::name(), IOobject::name(), and Foam::New().
meshPhi() [3/3]
Foam::tmp< Foam::surfaceScalarField > meshPhi (const volScalarField & rho, const volVectorField & U)
Definition at line 61 of file fvcMeshPhi.C.
References makeRelative(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and Foam::New().
makeRelative() [1/3]
void makeRelative (surfaceScalarField & phi, const volVectorField & U)
Make the given flux relative.
Definition at line 75 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
Referenced by Foam::CorrectPhi(), makeRelative(), and meshPhi().
makeRelative() [2/3]
void makeRelative (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Make the given flux relative.
Definition at line 87 of file fvcMeshPhi.C.
References makeRelative(), DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
makeRelative() [3/3]
void makeRelative (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Make the given flux relative.
Definition at line 100 of file fvcMeshPhi.C.
References Foam::MULES::interpolate(), makeAbsolute(), DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
makeAbsolute() [1/3]
void makeAbsolute (surfaceScalarField & phi, const volVectorField & U)
Make the given flux absolute.
Definition at line 114 of file fvcMeshPhi.C.
References DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
Referenced by Foam::CorrectPhi(), if(), makeAbsolute(), and makeRelative().
makeAbsolute() [2/3]
void makeAbsolute (surfaceScalarField & phi, const dimensionedScalar & rho, const volVectorField & U)
Make the given flux absolute.
Definition at line 126 of file fvcMeshPhi.C.
References makeAbsolute(), DimensionedField< Type, GeoMesh >::mesh(), and meshPhi().
makeAbsolute() [3/3]
void makeAbsolute (surfaceScalarField & phi, const volScalarField & rho, const volVectorField & U)
Make the given flux absolute.
Definition at line 139 of file fvcMeshPhi.C.
References Foam::MULES::interpolate(), DimensionedField< Type, GeoMesh >::mesh(), meshPhi(), and relative().
relative() [1/2]
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Return the given absolute flux in relative form.
Definition at line 153 of file fvcMeshPhi.C.
References mesh, and meshPhi().
Referenced by pimpleControl::criteriaSatisfied(), and makeAbsolute().
relative() [2/2]
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Return the given absolute flux in relative form.
Definition at line 170 of file fvcMeshPhi.C.
References absolute(), Foam::MULES::interpolate(), mesh, and meshPhi().
absolute() [1/2]
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & tphi, const volVectorField & U)
Return the given relative flux in absolute form.
Definition at line 188 of file fvcMeshPhi.C.
References mesh, and meshPhi().
Referenced by kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), if(), relative(), and while().
absolute() [2/2]
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & tphi, const volScalarField & rho, const volVectorField & U)
Return the given relative flux in absolute form.
Definition at line 205 of file fvcMeshPhi.C.
References Foam::MULES::interpolate(), mesh, and meshPhi().
reconstruct() [1/4]
tmp< GeometricField < typename outerProduct<vector,Type>::type, fvPatchField, volMesh >> Foam::fvc::reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 54 of file fvcReconstruct.C.
References IOobject::instance(), Foam::inv(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, reconstruct(), fvMesh::Sf(), and surfaceSum().
Referenced by Implicit< CloudType >::cacheFields(), for(), if(), reconstruct(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and while().
reconstruct() [2/4]
tmp< GeometricField < typename outerProduct<vector, Type>::type, fvPatchField, volMesh >> Foam::fvc::reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 96 of file fvcReconstruct.C.
References reconstruct().
reconstruct() [3/4]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::reconstruct (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
Definition at line 54 of file fvcReconstruct.C.
References IOobject::instance(), Foam::inv(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, reconstruct(), fvMesh::Sf(), and surfaceSum().
Referenced by Implicit< CloudType >::cacheFields(), for(), if(), reconstruct(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), and while().
reconstruct() [4/4]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > Foam::fvc::reconstruct (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &)
Definition at line 96 of file fvcReconstruct.C.
References reconstruct().
reconstructMag() [1/2]
tmp< volScalarField > reconstructMag (const surfaceScalarField & ssf)
Definition at line 44 of file fvcReconstructMag.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvMesh::Cf(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), fvMesh::magSf(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), patchi, fvMesh::Sf(), and fvMesh::V().
Referenced by reconstructMag().
reconstructMag() [2/2]
tmp< volScalarField > reconstructMag (const tmp< surfaceScalarField > & tssf)
Definition at line 117 of file fvcReconstructMag.C.
References tmp< T >::clear(), and reconstructMag().
smooth()
void smooth (volScalarField & field, const scalar coeff)
Definition at line 35 of file fvcSmooth.C.
References List< T >::append(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), polyMesh::faceOwner(), forAll, polyMesh::globalData(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), globalMeshData::nTotalCells(), fvMesh::owner(), patchi, spread(), and polyPatch::start().
Referenced by forAll(), if(), lduMatrix::smoother::interfaces(), LduMatrix< Type, DType, LUType >::smoother::matrix(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), and nonBlockingGaussSeidelSmoother::smooth().
spread()
void spread (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2, const scalar alphaMax = 0.99, const scalar alphaMin = 0.01)
Definition at line 124 of file fvcSmooth.C.
References List< T >::append(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), polyMesh::faceOwner(), forAll, FaceCellWave< Type, TrackingData >::iterate(), Foam::mag(), Foam::max(), smoothData::trackData::maxRatio, mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), fvMesh::owner(), patchi, FaceCellWave< Type, TrackingData >::setFaceInfo(), polyPatch::start(), and sweep().
Referenced by if(), and smooth().
sweep()
void sweep (volScalarField & field, const volScalarField & alpha, const label nLayers, const scalar alphaDiff = 0.2)
Definition at line 222 of file fvcSmooth.C.
References List< T >::append(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), polyPatch::coupled(), FaceCellWave< Type, TrackingData >::data(), primitiveMesh::faceCentres(), polyMesh::faceOwner(), forAll, FaceCellWave< Type, TrackingData >::iterate(), Foam::mag(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), fvMesh::neighbour(), primitiveMesh::nFaces(), fvMesh::owner(), patchi, FaceCellWave< Type, TrackingData >::setFaceInfo(), and polyPatch::start().
Referenced by if(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), DILUSmoother::smooth(), DICSmoother::smooth(), FDICSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), and spread().
snGrad() [1/4]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 45 of file fvcSnGrad.C.
References DimensionedField< Type, GeoMesh >::mesh(), and snGradScheme< Type >::New().
Referenced by wallHeatFlux::calcHeatFlux(), for(), forAllIter(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), transformFvPatchField< Type >::gradientBoundaryCoeffs(), if(), anisotropicFilter::operator()(), snGradScheme< Type >::sndGrad(), snGrad(), snGradScheme< Type >::snGrad(), energyRegionCoupledFvPatchScalarField::snGrad(), kinematicSingleLayer::solveMomentum(), kinematicSingleLayer::solveThickness(), interfaceProperties::surfaceTensionForce(), externalCoupledMixedFvPatchField< scalar >::transferData(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs(), and while().
snGrad() [2/4]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name)
Definition at line 61 of file fvcSnGrad.C.
References snGrad().
snGrad() [3/4]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcSnGrad.C.
References IOobject::name(), and snGrad().
snGrad() [4/4]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 89 of file fvcSnGrad.C.
References snGrad().
Su() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const GeometricField< Type, fvPatchField, volMesh > & su, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 44 of file fvcSup.C.
Referenced by meanVelocityForce::addSup(), SemiImplicitSource< Type >::addSup(), solidificationMeltingSource::addSup(), ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), ThermoParcel< ParcelType >::calc(), KinematicParcel< ParcelType >::calc(), KinematicParcel< ParcelType >::calcVelocity(), for(), forAll(), if(), Foam::MULES::implicitSolve(), laminar< Type >::R(), while(), XiReactionRate::write(), and RaviPetersen::~RaviPetersen().
Su() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tsu, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 55 of file fvcSup.C.
References Sp().
Sp() [1/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 67 of file fvcSup.C.
Referenced by SemiImplicitSource< Type >::addSup(), solidificationMeltingSource::addSup(), for(), forAllConstIter(), forAllIter(), if(), Foam::MULES::implicitSolve(), Foam::fvm::Sp(), Foam::fvm::Su(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::SU(), ReactingCloud< Foam::DSMCCloud >::SYi(), and while().
Sp() [2/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvcSup.C.
References Sp().
Sp() [3/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > Sp (const dimensionedScalar & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 90 of file fvcSup.C.
References SuSp().
SuSp() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const volScalarField & sp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 102 of file fvcSup.C.
Referenced by SemiImplicitSource< Type >::addSup(), if(), Foam::fvm::Sp(), and ReactingCloud< Foam::DSMCCloud >::Srho().
SuSp() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > SuSp (const tmp< volScalarField > & tsp, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 113 of file fvcSup.C.
surfaceIntegrate() [1/3]
void surfaceIntegrate (Field< Type > & ivf, const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 44 of file fvcSurfaceIntegrate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, mesh, DimensionedField< Type, GeoMesh >::mesh(), fvMesh::neighbour(), fvMesh::owner(), patchi, and fvMesh::Vsc().
Referenced by Foam::MULES::correct(), div(), Foam::MULES::explicitSolve(), boundedConvectionScheme< Type >::fvcDiv(), gaussConvectionScheme< Type >::fvcDiv(), boundedConvectionScheme< Type >::fvmDiv(), gaussConvectionScheme< Type >::fvmDiv(), anisotropicFilter::operator()(), and surfaceIntegrate().
surfaceIntegrate() [2/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 82 of file fvcSurfaceIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::ref(), surfaceIntegrate(), and Foam::Zero.
surfaceIntegrate() [3/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceIntegrate (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 122 of file fvcSurfaceIntegrate.C.
References surfaceIntegrate(), and surfaceSum().
surfaceSum() [1/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const GeometricField< Type, fvsPatchField, surfaceMesh > & ssf)
Definition at line 138 of file fvcSurfaceIntegrate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), patchi, GeometricField< Type, PatchField, GeoMesh >::ref(), and Foam::Zero.
Referenced by anisotropicFilter::anisotropicFilter(), average(), cellCoBlended< Type >::blendingFactor(), kinematicSingleLayer::CourantNumber(), forAll(), if(), kinematicSingleLayer::netMass(), simpleFilter::operator()(), reconstruct(), surfaceIntegrate(), and surfaceSum().
surfaceSum() [2/2]
tmp< GeometricField< Type, fvPatchField, volMesh > > surfaceSum (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tssf)
Definition at line 193 of file fvcSurfaceIntegrate.C.
References surfaceSum().
volumeIntegrate() [1/4]
tmp< Field< Type > > volumeIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 45 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::mesh(), and GeometricField< Type, PatchField, GeoMesh >::primitiveField().
Referenced by domainIntegrate().
volumeIntegrate() [2/4]
tmp< Field< Type > > volumeIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 56 of file fvcVolumeIntegrate.C.
References tmp< T >::clear().
volumeIntegrate() [3/4]
tmp< Field< Type > > volumeIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 67 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::field(), and DimensionedField< Type, GeoMesh >::mesh().
volumeIntegrate() [4/4]
tmp< Field< Type > > volumeIntegrate (const tmp< DimensionedField< Type, volMesh >> & tdf)
Definition at line 75 of file fvcVolumeIntegrate.C.
References tmp< T >::clear(), and domainIntegrate().
domainIntegrate() [1/4]
dimensioned< Type > domainIntegrate (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 86 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, Foam::gSum(), IOobject::name(), and volumeIntegrate().
Referenced by interRegionHeatTransferModel::addSup(), reactingOneDim::calculateMassTransfer(), kinematicSingleLayer::continuityCheck(), domainIntegrate(), forAll(), if(), ListPlusEqOp< T, Size >::operator()(), volumeIntegrate(), specieReactionRates< ChemistryModelType >::write(), and regionSizeDistribution::write().
domainIntegrate() [2/4]
dimensioned< Type > domainIntegrate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf)
Definition at line 101 of file fvcVolumeIntegrate.C.
References domainIntegrate().
domainIntegrate() [3/4]
dimensioned< Type > domainIntegrate (const DimensionedField< Type, volMesh > & df)
Definition at line 113 of file fvcVolumeIntegrate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, domainIntegrate(), Foam::gSum(), IOobject::name(), and volumeIntegrate().
domainIntegrate() [4/4]
dimensioned< Type > domainIntegrate (const tmp< DimensionedField< Type, volMesh >> & tdf)
Definition at line 128 of file fvcVolumeIntegrate.C.
References domainIntegrate().
scheme() [1/4]
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
Referenced by cloudSolution::read().
scheme() [2/4]
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const surfaceScalarField & faceFlux, const word & name) static
Return weighting factors for scheme given by name in dictionary.
scheme() [3/4]
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
scheme() [4/4]
static tmp<surfaceInterpolationScheme<Type> > Foam::fvc::scheme (const fvMesh & mesh, const word & name) static
Return weighting factors for scheme given by name in dictionary.
interpolate() [1/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const surfaceScalarField & faceFlux, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
Referenced by effectivenessHeatExchangerSource::addSup(), CoBlended< Type >::blendingFactor(), cellCoBlended< Type >::blendingFactor(), wallHeatFlux::calcHeatFlux(), inverseVolumeDiffusivity::correct(), motionDirectionalDiffusivity::correct(), inverseDistanceDiffusivity::correct(), thixotropicViscosity::correct(), advectionDiffusion::correct(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), Foam::interpolate(), Foam::MULES::interpolate(), mixtureKEpsilon< BasicTurbulenceModel >::mixFlux(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), incompressibleTwoPhaseMixture::muf(), kinematicSingleLayer::netMass(), incompressibleTwoPhaseMixture::nuf(), simpleFilter::operator()(), compressibleTurbulenceModel::phi(), dynamicRefineFvMesh::refine(), reactingOneDim::solidRegionDiffNo(), displacementSBRStressFvMotionSolver::solve(), reactingOneDim::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), kinematicSingleLayer::solveMomentum(), reactingOneDim::solveSpeciesMass(), kinematicSingleLayer::solveThickness(), interfaceProperties::surfaceTensionForce(), and dynamicRefineFvMesh::unrefine().
interpolate() [2/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const surfaceScalarField & dir, const word & reconFieldName = word::null) static
Interpolate field onto faces using scheme given by name in fvSchemes.
Interpolate field onto faces using scheme given by name in fvSchemes.
Definition at line 7 of file directionInterpolate.H.
References interpolate(), IOobject::name(), word::null, GeometricField< Type, PatchField, GeoMesh >::ref(), and sf().
interpolate() [3/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const surfaceScalarField & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
interpolate() [4/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
interpolate() [5/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const tmp< surfaceScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
interpolate() [6/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
interpolate() [7/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
interpolate() [8/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in fvSchemes.
interpolate() [9/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const GeometricField< Type, fvPatchField, volMesh > & tvf) static
Interpolate field onto faces using 'interpolate(<name>)'.
interpolate() [10/13]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::fvc::interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf) static
Interpolate tmp field onto faces using 'interpolate(<name>)'.
interpolate() [11/13]
static tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const FieldField< fvPatchField, Type > & fvpff) static
Interpolate boundary field onto faces (simply a type conversion)
interpolate() [12/13]
static tmp<FieldField<fvsPatchField, Type> > Foam::fvc::interpolate (const tmp< FieldField< fvPatchField, Type >> & tfvpff) static
Interpolate boundary field onto faces (simply a type conversion)
interpolate() [13/13]
one Foam::fvc::interpolate (const one &) inline
Interpolate 'one' returning 'one'.
Definition at line 190 of file surfaceInterpolate.H.
References dotInterpolate().
dotInterpolate() [1/2]
static tmp< GeometricField < typename innerProduct<vector, Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::dotInterpolate (const surfaceVectorField & Sf, const GeometricField< Type, fvPatchField, volMesh > & tvf) static
Interpolate field onto faces.
and 'dot' with given surfaceVectorField Sf
Referenced by correctedSnGrad< Type >::fullGradCorrection(), ddtScheme< Type >::fvcDdtPhiCoeff(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), surfaceInterpolationScheme< GType >::interpolate(), interpolate(), and displacementSBRStressFvMotionSolver::solve().
dotInterpolate() [2/2]
static tmp< GeometricField < typename innerProduct<vector, Type>::type, fvsPatchField, surfaceMesh > > Foam::fvc::dotInterpolate (const surfaceVectorField & Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf) static
Interpolate tmp field onto faces.
and 'dot' with given surfaceVectorField Sf