OpenFOAM: Foam::constant::thermodynamic Namespace Reference
Foam::constant::thermodynamic Namespace Reference
Thermodynamic scalar constants.
Variables
const scalar RR = 1e3*physicoChemical::R.value()
Universal gas constant (default in [J/(kmol K)])
const scalar Pstd = standard::Pstd.value()
Standard pressure (default in [Pa])
const scalar Tstd = standard::Tstd.value()
Standard temperature (default in [K])
Detailed Description
Thermodynamic scalar constants.
Variable Documentation
RR
const scalar RR = 1e3*physicoChemical::R.value()
Universal gas constant (default in [J/(kmol K)])
Definition at line 44 of file thermodynamicConstants.C.
Referenced by SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), LiquidEvaporation< CloudType >::calculate(), LiquidEvaporationBoil< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), SingleKineticRateDevolatilisation< CloudType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), ReactingParcel< ParcelType >::correctSurfaceValues(), PengRobinsonGas< Specie >::cp(), janafThermo< EquationOfState >::cp(), perfectGas< Specie >::cpMcv(), incompressiblePerfectGas< Specie >::cpMcv(), PengRobinsonGas< Specie >::cpMcv(), Boussinesq< Specie >::cpMcv(), PengRobinsonGas< Specie >::h(), janafThermo< EquationOfState >::ha(), janafThermo< EquationOfState >::hc(), thermo< Thermo, Type >::K(), thermo< Thermo, Type >::Kc(), PengRobinsonGas< Specie >::operator*=(), PengRobinsonGas< Specie >::operator+=(), PengRobinsonGas< Specie >::operator-=(), PengRobinsonGas< Specie >::PengRobinsonGas(), liquidMixtureProperties::Ppc(), specie::R(), perfectGas< Specie >::s(), perfectFluid< Specie >::s(), PengRobinsonGas< Specie >::s(), janafThermo< EquationOfState >::s(), EulerImplicit< ChemistryModel >::solve(), specieReactionRates< ChemistryModelType >::write(), and PengRobinsonGas< Specie >::Z().
Pstd
const scalar Pstd = standard::Pstd.value()
Standard pressure (default in [Pa])
Standard pressure.
Definition at line 46 of file thermodynamicConstants.C.
Referenced by thermo< Thermo, Type >::K(), thermo< Thermo, Type >::Kc(), thermo< Thermo, Type >::Kn(), thermo< Thermo, Type >::Kx(), perfectGas< Specie >::s(), perfectFluid< Specie >::s(), linear< Type >::s(), adiabaticPerfectFluid< Specie >::s(), and PengRobinsonGas< Specie >::s().
Tstd
const scalar Tstd = standard::Tstd.value()
Standard temperature (default in [K])
Standard temperature.
Definition at line 47 of file thermodynamicConstants.C.
Referenced by janafThermo< EquationOfState >::hc(), hPolynomialThermo< EquationOfState, PolySize >::hPolynomialThermo(), hPowerThermo< EquationOfState >::hs(), solidProperties::Hs(), hConstThermo< EquationOfState >::s(), hRefConstThermo< EquationOfState >::s(), eConstThermo< EquationOfState >::s(), and hPowerThermo< EquationOfState >::s().