OpenFOAM: Foam::fvm Namespace Reference
Foam::fvm Namespace Reference
Namespace of functions to calculate implicit derivatives returning a matrix.
Functions
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (const dimensionedScalar &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const dimensionedScalar &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const one &, const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const one &, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > ddt (const volScalarField &alpha, const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > div (const surfaceScalarField &flux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > div (const tmp< surfaceScalarField > &tflux, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const zero &, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const zero &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type >
tmp< fvMatrix< Type > > laplacian (const one &, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const dimensioned< GType > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvPatchField, volMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tgamma, const GeometricField< Type, fvPatchField, volMesh > &vf, const word &name)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &gamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type , class GType >
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> &tGamma, const GeometricField< Type, fvPatchField, volMesh > &vf)
template<class Type >
tmp< fvMatrix< Type > > Su (const DimensionedField< Type, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Su (const tmp< DimensionedField< Type, volMesh >> &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Su (const tmp< GeometricField< Type, fvPatchField, volMesh >> &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
zeroField Su (const zero &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Sp (const volScalarField::Internal &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Sp (const tmp< volScalarField::Internal > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Sp (const tmp< volScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > Sp (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
zeroField Sp (const zero &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > SuSp (const volScalarField::Internal &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > SuSp (const tmp< volScalarField::Internal > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
tmp< fvMatrix< Type > > SuSp (const tmp< volScalarField > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<class Type >
zeroField SuSp (const zero &, const GeometricField< Type, fvPatchField, volMesh > &)
Detailed Description
Namespace of functions to calculate implicit derivatives returning a matrix.
Temporal derivatives are calculated using Euler-implicit, backward differencing or Crank-Nicolson. Spatial derivatives are calculated using Gauss' Theorem.
Function Documentation
d2dt2() [1/3]
tmp< fvMatrix< Type > > d2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 46 of file fvmD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
Referenced by d2dt2().
d2dt2() [2/3]
tmp< fvMatrix< Type > > d2dt2 (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 61 of file fvmD2dt2.C.
References d2dt2(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), IOobject::name(), and d2dt2Scheme< Type >::New().
d2dt2() [3/3]
tmp< fvMatrix< Type > > d2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 77 of file fvmD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and d2dt2Scheme< Type >::New().
ddt() [1/8]
tmp< fvMatrix< Type > > ddt (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 46 of file fvmDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
Referenced by relaxation::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), ShihQuadraticKE::correct(), LamBremhorstKE::correct(), LienLeschziner::correct(), thixotropicViscosity::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), ddt(), scalarTransport::execute(), Foam::MULES::implicitSolve(), reactingOneDim::solveContinuity(), kinematicSingleLayer::solveContinuity(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), reactingOneDim::solveSpeciesMass(), and kinematicSingleLayer::solveThickness().
ddt() [2/8]
tmp< fvMatrix< Type > > ddt (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 61 of file fvmDdt.C.
References ddt().
ddt() [3/8]
tmp< fvMatrix< Type > > ddt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 73 of file fvmDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [4/8]
tmp< fvMatrix< Type > > ddt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 89 of file fvmDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [5/8]
tmp< fvMatrix< Type > > ddt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 105 of file fvmDdt.C.
References ddt(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and ddtScheme< Type >::New().
ddt() [6/8]
tmp< fvMatrix< Type > > ddt (const one & , const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 128 of file fvmDdt.C.
References ddt().
ddt() [7/8]
tmp< fvMatrix< Type > > ddt (const one & , const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 141 of file fvmDdt.C.
References ddt().
ddt() [8/8]
tmp< fvMatrix< Type > > ddt (const volScalarField & alpha, const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 154 of file fvmDdt.C.
References ddt().
div() [1/4]
tmp< fvMatrix< Type > > div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 46 of file fvmDiv.C.
References Foam::fvc::flux(), DimensionedField< Type, GeoMesh >::mesh(), and convectionScheme< Type >::New().
Referenced by relaxation::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), radiativeIntensityRay::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), LamBremhorstKE::correct(), ShihQuadraticKE::correct(), LienLeschziner::correct(), thixotropicViscosity::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), div(), scalarTransport::execute(), thermoSingleLayer::solveEnergy(), kinematicSingleLayer::solveMomentum(), and kinematicSingleLayer::solveThickness().
div() [2/4]
tmp< fvMatrix< Type > > div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 63 of file fvmDiv.C.
References tmp< T >::clear(), and div().
div() [3/4]
tmp< fvMatrix< Type > > div (const surfaceScalarField & flux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 78 of file fvmDiv.C.
References div(), and IOobject::name().
div() [4/4]
tmp< fvMatrix< Type > > div (const tmp< surfaceScalarField > & tflux, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 89 of file fvmDiv.C.
References tmp< T >::clear(), and div().
laplacian() [1/16]
tmp< fvMatrix< Type > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 46 of file fvmLaplacian.C.
References Foam::dimless, DimensionedField< Type, GeoMesh >::mesh(), IOobject::NO_READ, and IOobject::time().
Referenced by P1::calculate(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), ShihQuadraticKE::correct(), Poisson::correct(), LamBremhorstKE::correct(), LienLeschziner::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), scalarTransport::execute(), laplacian(), velocityComponentLaplacianFvMotionSolver::solve(), velocityLaplacianFvMotionSolver::solve(), displacementSBRStressFvMotionSolver::solve(), displacementComponentLaplacianFvMotionSolver::solve(), displacementLaplacianFvMotionSolver::solve(), thermalBaffle::solveEnergy(), reactingOneDim::solveEnergy(), and kinematicSingleLayer::solveThickness().
laplacian() [2/16]
tmp< fvMatrix< Type > > laplacian (const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 71 of file fvmLaplacian.C.
References Foam::dimless, laplacian(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, and IOobject::time().
laplacian() [3/16]
tmp< fvMatrix< Type > > laplacian (const zero & , const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 100 of file fvmLaplacian.C.
References laplacian().
laplacian() [4/16]
tmp< fvMatrix< Type > > laplacian (const zero & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 116 of file fvmLaplacian.C.
References laplacian().
laplacian() [5/16]
tmp< fvMatrix< Type > > laplacian (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 131 of file fvmLaplacian.C.
References laplacian().
laplacian() [6/16]
tmp< fvMatrix< Type > > laplacian (const one & , const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 144 of file fvmLaplacian.C.
References laplacian().
laplacian() [7/16]
tmp< fvMatrix< Type > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 156 of file fvmLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
laplacian() [8/16]
tmp< fvMatrix< Type > > laplacian (const dimensioned< GType > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 182 of file fvmLaplacian.C.
References IOobject::instance(), laplacian(), DimensionedField< Type, GeoMesh >::mesh(), dimensioned< Type >::name(), and IOobject::NO_READ.
laplacian() [9/16]
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 209 of file fvmLaplacian.C.
References laplacian(), DimensionedField< Type, GeoMesh >::mesh(), laplacianScheme< Type, GType >::New(), and ref().
laplacian() [10/16]
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 226 of file fvmLaplacian.C.
References laplacian().
laplacian() [11/16]
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 241 of file fvmLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [12/16]
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvPatchField, volMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 258 of file fvmLaplacian.C.
References laplacian().
laplacian() [13/16]
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 274 of file fvmLaplacian.C.
References laplacian(), DimensionedField< Type, GeoMesh >::mesh(), laplacianScheme< Type, GType >::New(), and ref().
laplacian() [14/16]
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tgamma, const GeometricField< Type, fvPatchField, volMesh > & vf, const word & name)
Definition at line 291 of file fvmLaplacian.C.
References laplacian().
laplacian() [15/16]
tmp< fvMatrix< Type > > laplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 306 of file fvmLaplacian.C.
References laplacian(), and IOobject::name().
laplacian() [16/16]
tmp< fvMatrix< Type > > laplacian (const tmp< GeometricField< GType, fvsPatchField, surfaceMesh >> & tGamma, const GeometricField< Type, fvPatchField, volMesh > & vf)
Definition at line 323 of file fvmLaplacian.C.
References laplacian().
Su() [1/4]
tmp<fvMatrix<Type> > Foam::fvm::Su (const DimensionedField< Type, volMesh > & , const GeometricField< Type, fvPatchField, volMesh > &)
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::epsilonSource(), mixtureKEpsilon< BasicTurbulenceModel >::kSource(), and kOmegaSSTSAS< BasicTurbulenceModel >::Qsas().
Su() [2/4]
tmp<fvMatrix<Type> > Foam::fvm::Su (const tmp< DimensionedField< Type, volMesh >> & , const GeometricField< Type, fvPatchField, volMesh > &)
Su() [3/4]
tmp<fvMatrix<Type> > Foam::fvm::Su (const tmp< GeometricField< Type, fvPatchField, volMesh >> & , const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 55 of file fvcSup.C.
References Foam::fvc::Sp().
Su() [4/4]
zeroField Foam::fvm::Su (const zero & , const GeometricField< Type, fvPatchField, volMesh > &)
Sp() [1/5]
tmp<fvMatrix<Type> > Foam::fvm::Sp (const volScalarField::Internal & , const GeometricField< Type, fvPatchField, volMesh > &)
Referenced by interRegionHeatTransferModel::addSup(), P1::calculate(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), radiativeIntensityRay::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), LamBremhorstKE::correct(), ShihQuadraticKE::correct(), LienLeschziner::correct(), thixotropicViscosity::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), LienCubicKE::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), qZeta::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), continuousGasKEpsilon< BasicTurbulenceModel >::epsilonSource(), LaheyKEpsilon< BasicTurbulenceModel >::epsilonSource(), boundedDdtScheme< Type >::fvmDdt(), boundedConvectionScheme< Type >::fvmDiv(), Foam::MULES::implicitSolve(), continuousGasKEqn< BasicTurbulenceModel >::kSource(), continuousGasKEpsilon< BasicTurbulenceModel >::kSource(), NicenoKEqn< BasicTurbulenceModel >::kSource(), LaheyKEpsilon< BasicTurbulenceModel >::kSource(), thermoSingleLayer::q(), singleStepCombustion< CombThermoType, ThermoType >::R(), radiationModel::Sh(), reactingOneDim::solveEnergy(), radiationModel::ST(), and laminar::Su().
Sp() [2/5]
tmp<fvMatrix<Type> > Foam::fvm::Sp (const tmp< volScalarField::Internal > & , const GeometricField< Type, fvPatchField, volMesh > &)
Sp() [3/5]
tmp<fvMatrix<Type> > Foam::fvm::Sp (const tmp< volScalarField > & , const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 78 of file fvcSup.C.
References Foam::fvc::Sp().
Sp() [4/5]
tmp<fvMatrix<Type> > Foam::fvm::Sp (const dimensionedScalar & , const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 90 of file fvcSup.C.
References Foam::fvc::SuSp().
Sp() [5/5]
zeroField Foam::fvm::Sp (const zero & , const GeometricField< Type, fvPatchField, volMesh > &)
SuSp() [1/4]
tmp<fvMatrix<Type> > Foam::fvm::SuSp (const volScalarField::Internal & , const GeometricField< Type, fvPatchField, volMesh > &)
Referenced by relaxation::correct(), kEqn< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), qZeta::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kkLOmega::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), buoyantKEpsilon< BasicTurbulenceModel >::epsilonSource(), buoyantKEpsilon< BasicTurbulenceModel >::kSource(), and ThermoCloud< Foam::DSMCCloud >::Sh().
SuSp() [2/4]
tmp<fvMatrix<Type> > Foam::fvm::SuSp (const tmp< volScalarField::Internal > & , const GeometricField< Type, fvPatchField, volMesh > &)
SuSp() [3/4]
tmp<fvMatrix<Type> > Foam::fvm::SuSp (const tmp< volScalarField > & , const GeometricField< Type, fvPatchField, volMesh > &)
Definition at line 113 of file fvcSup.C.
SuSp() [4/4]
zeroField Foam::fvm::SuSp (const zero & , const GeometricField< Type, fvPatchField, volMesh > &)