OpenFOAM: Foam::compressible Namespace Reference
Foam::compressible Namespace Reference
Namespaces
RASModels
Classes
class alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField
A simple alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField with a fixed volumetric phase-change mass flux.
class alphatJayatillekeWallFunctionFvPatchScalarField
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model.
class alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model for the Eulerian multiphase solvers.
class alphatPhaseChangeWallFunctionFvPatchScalarField
Abstract base-class for all alphatWallFunctions supporting phase-change.
class alphatWallBoilingWallFunctionFvPatchScalarField
A thermal wall function for simulation of subcooled nucleate wall boiling.
class alphatWallFunctionFvPatchScalarField
This boundary condition provides a turbulent thermal diffusivity conditon when using wall functions.
class convectiveHeatTransferFvPatchScalarField
This boundary condition provides a convective heat transfer coefficient condition.
class thermalBaffle1DFvPatchScalarField
This BC solves a steady 1D thermal baffle.
class thermalBaffleFvPatchScalarField
This boundary condition provides a coupled temperature condition between multiple mesh regions.
class turbulentHeatFluxTemperatureFvPatchScalarField
Fixed heat boundary condition to specify temperature gradient. Input heat source either specified in terms of an absolute power [W], or as a flux [W/m^2].
class turbulentTemperatureCoupledBaffleMixedFvPatchScalarField
Mixed boundary condition for temperature, to be used for heat-transfer on back-to-back baffles. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
class turbulentTemperatureRadCoupledMixedFvPatchScalarField
Mixed boundary condition for temperature and radiation heat transfer to be used for in multiregion cases. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
Typedefs
typedef thermalBaffle1DFvPatchScalarField< hConstSolidThermoPhysics > constSolid_thermalBaffle1DFvPatchScalarField
typedef thermalBaffle1DFvPatchScalarField< hPowerSolidThermoPhysics > expoSolid_thermalBaffle1DFvPatchScalarField
typedef ThermalDiffusivity< CompressibleTurbulenceModel< fluidThermo > > turbulenceModel
typedef laminarModel< turbulenceModel > laminarModel
typedef RASModel< EddyDiffusivity< turbulenceModel > > RASModel
typedef LESModel< EddyDiffusivity< turbulenceModel > > LESModel
Typedefs for turbulence, RAS and LES models for compressible flow based on the standard laminar transport package.
Functions
makePatchTypeField (fvPatchScalarField, thermalBaffleFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, convectiveHeatTransferFvPatchScalarField)
addToPatchFieldRunTimeSelection (fvPatchScalarField, constSolid_thermalBaffle1DFvPatchScalarField)
addToPatchFieldRunTimeSelection (fvPatchScalarField, expoSolid_thermalBaffle1DFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentHeatFluxTemperatureFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentTemperatureCoupledBaffleMixedFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentTemperatureRadCoupledMixedFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, alphatJayatillekeWallFunctionFvPatchScalarField)
defineTypeNameAndDebug (alphatPhaseChangeWallFunctionFvPatchScalarField, 0)
makePatchTypeField (fvPatchScalarField, alphatWallFunctionFvPatchScalarField)
template<class BasicCompressibleTurbulenceModel >
autoPtr< BasicCompressibleTurbulenceModel > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const typename BasicCompressibleTurbulenceModel::transportModel &transport, const word &propertiesName)
Typedef Documentation
constSolid_thermalBaffle1DFvPatchScalarField
typedef thermalBaffle1DFvPatchScalarField< hConstSolidThermoPhysics > constSolid_thermalBaffle1DFvPatchScalarField
Definition at line 44 of file thermalBaffle1DFvPatchScalarFields.H.
expoSolid_thermalBaffle1DFvPatchScalarField
typedef thermalBaffle1DFvPatchScalarField< hPowerSolidThermoPhysics > expoSolid_thermalBaffle1DFvPatchScalarField
Definition at line 49 of file thermalBaffle1DFvPatchScalarFields.H.
turbulenceModel
turbulenceModel
Foam::compressible::RASModel
Definition at line 61 of file turbulentFluidThermoModel.H.
laminarModel
typedef laminarModel<turbulenceModel> laminarModel
Definition at line 63 of file turbulentFluidThermoModel.H.
RASModel
typedef RASModel<EddyDiffusivity<turbulenceModel> > RASModel
Definition at line 64 of file turbulentFluidThermoModel.H.
LESModel
LESModel
Typedefs for turbulence, RAS and LES models for compressible flow based on the standard laminar transport package.
Source files
turbulentFluidThermoModel.H
turbulentFluidThermoModel.C
turbulentFluidThermoModels.C
Definition at line 65 of file turbulentFluidThermoModel.H.
Function Documentation
makePatchTypeField() [1/7]
Foam::compressible::makePatchTypeField (fvPatchScalarField , thermalBaffleFvPatchScalarField)
Referenced by alphatWallFunctionFvPatchScalarField::write(), convectiveHeatTransferFvPatchScalarField::write(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), turbulentHeatFluxTemperatureFvPatchScalarField::write(), and thermalBaffleFvPatchScalarField::write().
makePatchTypeField() [2/7]
Foam::compressible::makePatchTypeField (fvPatchScalarField , convectiveHeatTransferFvPatchScalarField)
addToPatchFieldRunTimeSelection() [1/2]
Foam::compressible::addToPatchFieldRunTimeSelection (fvPatchScalarField , constSolid_thermalBaffle1DFvPatchScalarField)
addToPatchFieldRunTimeSelection() [2/2]
Foam::compressible::addToPatchFieldRunTimeSelection (fvPatchScalarField , expoSolid_thermalBaffle1DFvPatchScalarField)
makePatchTypeField() [3/7]
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentHeatFluxTemperatureFvPatchScalarField)
makePatchTypeField() [4/7]
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentTemperatureCoupledBaffleMixedFvPatchScalarField)
makePatchTypeField() [5/7]
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentTemperatureRadCoupledMixedFvPatchScalarField)
makePatchTypeField() [6/7]
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatJayatillekeWallFunctionFvPatchScalarField)
defineTypeNameAndDebug()
Foam::compressible::defineTypeNameAndDebug (alphatPhaseChangeWallFunctionFvPatchScalarField , 0)
makePatchTypeField() [7/7]
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatWallFunctionFvPatchScalarField)
New()
autoPtr<BasicCompressibleTurbulenceModel> Foam::compressible::New (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const typename BasicCompressibleTurbulenceModel::transportModel & transport, const word & propertiesName)
Definition at line 36 of file turbulentFluidThermoModel.C.