OpenFOAM: laminar< Type > Class Template Reference
laminar< Type > Class Template Reference
Laminar combustion model.
Public Member Functions
TypeName ("laminar")
Runtime type information.
laminar (const word &modelType, const fvMesh &mesh, const word &phaseName)
Construct from components.
virtual ~laminar ()
Destructor.
virtual void correct ()
Correct combustion rate.
virtual tmp< fvScalarMatrix > R (volScalarField &Y) const
Fuel consumption rate matrix.
virtual tmp< volScalarField > dQ () const
Heat release rate calculated from fuel consumption rate matrix.
virtual tmp< volScalarField > Sh () const
Return source for enthalpy equation [kg/m/s3].
virtual bool read ()
Update properties from given dictionary.
Protected Member Functions
tmp< volScalarField > tc () const
Return the chemical time scale.
Detailed Description
template<class Type>
class Foam::combustionModels::laminar< Type >
Laminar combustion model.
Source files
laminar.H
laminar.C
Definition at line 49 of file laminar.H.
Constructor & Destructor Documentation
laminar()
laminar (const word & modelType, const fvMesh & mesh, const word & phaseName)
Construct from components.
Definition at line 34 of file laminar.C.
References Foam::endl(), and Foam::Info.
~laminar()
~laminar () virtual
Destructor.
Definition at line 60 of file laminar.C.
Member Function Documentation
tc()
Foam::tmp< Foam::volScalarField > tc () const protected
Return the chemical time scale.
Definition at line 68 of file laminar.C.
TypeName()
TypeName ("laminar< Type >")
Runtime type information.
correct()
void correct () virtual
Correct combustion rate.
Reimplemented in PaSR< Type >.
Definition at line 75 of file laminar.C.
References found, lookup(), mesh, Foam::min(), and readScalar.
R()
Foam::tmp< Foam::fvScalarMatrix > R (volScalarField & Y) const virtual
Fuel consumption rate matrix.
Reimplemented in PaSR< Type >.
Definition at line 118 of file laminar.C.
References Foam::dimMass, Foam::dimTime, IOobject::member(), tmp< T >::ref(), Foam::fvc::Su(), and thermo.
dQ()
Foam::tmp< Foam::volScalarField > dQ () const virtual
Heat release rate calculated from fuel consumption rate matrix.
Reimplemented in PaSR< Type >.
Definition at line 138 of file laminar.C.
References Foam::dimEnergy, Foam::dimTime, mesh, tmp< T >::ref(), and timeName.
Sh()
Foam::tmp< Foam::volScalarField > Sh () const virtual
Return source for enthalpy equation [kg/m/s3].
Reimplemented in PaSR< Type >.
Definition at line 169 of file laminar.C.
References Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, mesh, tmp< T >::ref(), and timeName.
read()
bool read () virtual
Update properties from given dictionary.
Reimplemented in PaSR< Type >.
Definition at line 199 of file laminar.C.
References Foam::read().
The documentation for this class was generated from the following files:
src/combustionModels/laminar/laminar.H
src/combustionModels/laminar/laminar.C