OpenFOAM: Foam::vtkPV3Readers Namespace Reference
Foam::vtkPV3Readers Namespace Reference
A collection of helper functions when building a reader interface in ParaView3.
Classes
class partInfo
Bookkeeping for GUI checklists and the multi-block organization.
Functions
NamespaceName ("vtkPV3Readers")
Declare name of the class and its debug switch.
void AddToBlock (vtkMultiBlockDataSet *output, vtkDataSet *dataset, const partInfo &selector, const label datasetNo, const std::string &datasetName)
Convenience method use to convert the readers from VTK 5.
vtkDataSet * GetDataSetFromBlock (vtkMultiBlockDataSet *output, const partInfo &selector, const label datasetNo)
Convenience method use to convert the readers from VTK 5.
label GetNumberOfDataSets (vtkMultiBlockDataSet *output, const partInfo &selector)
Convenience method use to convert the readers from VTK 5.
wordHashSet getSelected (vtkDataArraySelection *select)
Retrieve the current selections as a wordHashSet.
wordHashSet getSelected (vtkDataArraySelection *, const partInfo &)
Retrieve a sub-list of the current selections.
stringList getSelectedArrayEntries (vtkDataArraySelection *)
Retrieve the current selections.
stringList getSelectedArrayEntries (vtkDataArraySelection *select, const partInfo &selector)
Retrieve a sub-list of the current selections.
void setSelectedArrayEntries (vtkDataArraySelection *, const stringList &)
Set selection(s)
Detailed Description
A collection of helper functions when building a reader interface in ParaView3.
Source files
vtkPV3Readers.H
vtkPV3Readers.C
Function Documentation
NamespaceName()
Foam::vtkPV3Readers::NamespaceName ("vtkPV3Readers")
Declare name of the class and its debug switch.
AddToBlock()
void AddToBlock (vtkMultiBlockDataSet * output, vtkDataSet * dataset, const partInfo & selector, const label datasetNo, const std::string & datasetName)
Convenience method use to convert the readers from VTK 5.
multiblock API to the current composite data infrastructure
Definition at line 80 of file vtkPV3Readers.C.
References partInfo::block(), Foam::endl(), FatalErrorInFunction, GetDataSetFromBlock(), Foam::Info, partInfo::name(), and Foam::New().
Referenced by partInfo::operator+=().
GetDataSetFromBlock()
vtkDataSet * GetDataSetFromBlock (vtkMultiBlockDataSet * output, const partInfo & selector, const label datasetNo)
Convenience method use to convert the readers from VTK 5.
multiblock API to the current composite data infrastructure
Definition at line 140 of file vtkPV3Readers.C.
References partInfo::block(), and GetNumberOfDataSets().
Referenced by AddToBlock(), and partInfo::operator+=().
GetNumberOfDataSets()
Foam::label GetNumberOfDataSets (vtkMultiBlockDataSet * output, const partInfo & selector)
Convenience method use to convert the readers from VTK 5.
multiblock API to the current composite data infrastructure ununsed at the moment
Definition at line 162 of file vtkPV3Readers.C.
References partInfo::block(), and getSelected().
Referenced by GetDataSetFromBlock(), and partInfo::operator+=().
getSelected() [1/2]
Foam::wordHashSet getSelected (vtkDataArraySelection * select)
Retrieve the current selections as a wordHashSet.
Definition at line 187 of file vtkPV3Readers.C.
References HashSet< Key, Hash >::insert().
Referenced by GetNumberOfDataSets(), and partInfo::operator+=().
getSelected() [2/2]
Foam::wordHashSet getSelected (vtkDataArraySelection * select, const partInfo & selector)
Retrieve a sub-list of the current selections.
Definition at line 207 of file vtkPV3Readers.C.
References partInfo::end(), getSelectedArrayEntries(), HashSet< Key, Hash >::insert(), and partInfo::start().
getSelectedArrayEntries() [1/2]
Foam::stringList getSelectedArrayEntries (vtkDataArraySelection * select)
Retrieve the current selections.
Definition at line 228 of file vtkPV3Readers.C.
References forAll, and Foam::Info.
Referenced by getSelected(), and partInfo::operator+=().
getSelectedArrayEntries() [2/2]
Foam::stringList getSelectedArrayEntries (vtkDataArraySelection * select, const partInfo & selector)
Retrieve a sub-list of the current selections.
Definition at line 267 of file vtkPV3Readers.C.
References partInfo::end(), forAll, Foam::Info, setSelectedArrayEntries(), List< T >::setSize(), partInfo::size(), and partInfo::start().
setSelectedArrayEntries()
void setSelectedArrayEntries (vtkDataArraySelection * select, const stringList & selections)
Set selection(s)
Definition at line 306 of file vtkPV3Readers.C.
References forAll.
Referenced by getSelectedArrayEntries(), and partInfo::operator+=().