OpenFOAM: Foam::RBD Namespace Reference
Foam::RBD Namespace Reference
Namespaces
joints
Namespace for rigid-body joints.
restraints
Namespace for rigid-body dynamics restraints.
rigidBodySolvers
Classes
class compositeBody
class cuboid
class joint
Abstract base-class for all rigid-body joints.
class jointBody
class masslessBody
class restraint
Base class for defining restraints for rigid-body dynamics.
class rigidBody
class rigidBodyInertia
class rigidBodyModel
Basic rigid-body model representing a system of rigid-bodies connected by 1-6 DoF joints.
class rigidBodyModelState
Holds the motion state of rigid-body model.
class rigidBodyMotion
Six degree of freedom motion for a rigid body.
class rigidBodySolver
class sphere
class subBody
Functions
defineTypeNameAndDebug (cuboid, 0)
addToRunTimeSelectionTable (rigidBody, cuboid, dictionary)
defineTypeNameAndDebug (jointBody, 0)
addToRunTimeSelectionTable (rigidBody, jointBody, dictionary)
defineTypeNameAndDebug (masslessBody, 0)
addToRunTimeSelectionTable (rigidBody, masslessBody, dictionary)
defineTypeNameAndDebug (rigidBody, 0)
defineRunTimeSelectionTable (rigidBody, dictionary)
addToRunTimeSelectionTable (rigidBody, rigidBody, dictionary)
Ostream & operator<< (Ostream &, const rigidBody &)
defineTypeNameAndDebug (sphere, 0)
addToRunTimeSelectionTable (rigidBody, sphere, dictionary)
defineTypeNameAndDebug (joint, 0)
defineRunTimeSelectionTable (joint, dictionary)
Ostream & operator<< (Ostream &, const joint &)
defineTypeNameAndDebug (restraint, 0)
defineRunTimeSelectionTable (restraint, dictionary)
Istream & operator>> (Istream &, rigidBodyInertia &)
Ostream & operator<< (Ostream &, const rigidBodyInertia &)
rigidBodyInertia operator+ (const rigidBodyInertia &rbi1, const rigidBodyInertia &rbi2)
Return the rigid-body inertia of the combined body.
spatialVector operator & (const rigidBodyInertia &rbi, const spatialVector &sv)
Inner-product with a spatialVector (e.g. velocity returning the momentum)
rigidBodyInertia transform (const spatialTransform &X, const rigidBodyInertia &I)
Return (^BX_A)^* I ^AX_B.
defineTypeNameAndDebug (rigidBodyModel, 0)
Ostream & operator<< (Ostream &, const rigidBodyModel &)
Istream & operator>> (Istream &, rigidBodyModelState &)
Ostream & operator<< (Ostream &, const rigidBodyModelState &)
defineTypeNameAndDebug (rigidBodySolver, 0)
defineRunTimeSelectionTable (rigidBodySolver, dictionary)
Function Documentation
defineTypeNameAndDebug() [1/9]
Foam::RBD::defineTypeNameAndDebug (cuboid , 0)
addToRunTimeSelectionTable() [1/5]
Foam::RBD::addToRunTimeSelectionTable (rigidBody , cuboid , dictionary)
defineTypeNameAndDebug() [2/9]
Foam::RBD::defineTypeNameAndDebug (jointBody , 0)
addToRunTimeSelectionTable() [2/5]
Foam::RBD::addToRunTimeSelectionTable (rigidBody , jointBody , dictionary)
defineTypeNameAndDebug() [3/9]
Foam::RBD::defineTypeNameAndDebug (masslessBody , 0)
addToRunTimeSelectionTable() [3/5]
Foam::RBD::addToRunTimeSelectionTable (rigidBody , masslessBody , dictionary)
defineTypeNameAndDebug() [4/9]
Foam::RBD::defineTypeNameAndDebug (rigidBody , 0)
defineRunTimeSelectionTable() [1/4]
Foam::RBD::defineRunTimeSelectionTable (rigidBody , dictionary)
addToRunTimeSelectionTable() [4/5]
Foam::RBD::addToRunTimeSelectionTable (rigidBody , rigidBody , dictionary)
operator<<() [1/5]
Foam::Ostream & operator<< (Ostream & os, const rigidBody & rb) inline
Definition at line 73 of file rigidBodyI.H.
References rigidBody::write().
defineTypeNameAndDebug() [5/9]
Foam::RBD::defineTypeNameAndDebug (sphere , 0)
addToRunTimeSelectionTable() [5/5]
Foam::RBD::addToRunTimeSelectionTable (rigidBody , sphere , dictionary)
defineTypeNameAndDebug() [6/9]
Foam::RBD::defineTypeNameAndDebug (joint , 0)
defineRunTimeSelectionTable() [2/4]
Foam::RBD::defineRunTimeSelectionTable (joint , dictionary)
operator<<() [2/5]
Foam::Ostream & operator<< (Ostream & os, const joint & j) inline
Definition at line 113 of file jointI.H.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, Foam::endl(), Foam::incrIndent(), Foam::indent(), and joint::write().
defineTypeNameAndDebug() [7/9]
Foam::RBD::defineTypeNameAndDebug (restraint , 0)
defineRunTimeSelectionTable() [3/4]
Foam::RBD::defineRunTimeSelectionTable (restraint , dictionary)
operator>>() [1/2]
Foam::Istream & operator>> (Istream & is, rigidBodyInertia & rbi) inline
Definition at line 139 of file rigidBodyInertiaI.H.
operator<<() [3/5]
Foam::Ostream & operator<< (Ostream & os, const rigidBodyInertia & rbi) inline
Definition at line 150 of file rigidBodyInertiaI.H.
References Foam::endl(), and Foam::nl.
operator+()
rigidBodyInertia Foam::RBD::operator+ (const rigidBodyInertia & rbi1, const rigidBodyInertia & rbi2) inline
Return the rigid-body inertia of the combined body.
Definition at line 171 of file rigidBodyInertiaI.H.
References rigidBodyInertia::c(), rigidBodyInertia::Ic(), rigidBodyInertia::Icc(), rigidBodyInertia::m(), and rigidBodyInertia::rigidBodyInertia().
operator &()
spatialVector Foam::RBD::operator& (const rigidBodyInertia & rbi, const spatialVector & sv) inline
Inner-product with a spatialVector (e.g. velocity returning the momentum)
Definition at line 190 of file rigidBodyInertiaI.H.
References rigidBodyInertia::c(), rigidBodyInertia::Io(), rigidBodyInertia::m(), and transform().
transform()
rigidBodyInertia Foam::RBD::transform (const spatialTransform & X, const rigidBodyInertia & I) inline
Return (^BX_A)^* I ^AX_B.
Definition at line 208 of file rigidBodyInertiaI.H.
References rigidBodyInertia::c(), spatialTransform::E(), rigidBodyInertia::Ic(), rigidBodyInertia::kineticEnergy(), rigidBodyInertia::m(), spatialTransform::r(), rigidBodyInertia::rigidBodyInertia(), and Tensor< Cmpt >::T().
Referenced by rigidBody::merge(), and operator &().
defineTypeNameAndDebug() [8/9]
Foam::RBD::defineTypeNameAndDebug (rigidBodyModel , 0)
operator<<() [4/5]
Foam::Ostream & operator<< (Ostream & os, const rigidBodyModel & rbm)
Definition at line 467 of file rigidBodyModel.C.
References rigidBodyModel::write().
operator>>() [2/2]
Foam::Istream & operator>> (Istream & is, rigidBodyModelState & state)
Definition at line 52 of file rigidBodyModelStateIO.C.
References IOstream::check().
operator<<() [5/5]
Foam::Ostream & operator<< (Ostream & os, const rigidBodyModelState & state)
Definition at line 74 of file rigidBodyModelStateIO.C.
References IOstream::check(), and token::SPACE.
defineTypeNameAndDebug() [9/9]
Foam::RBD::defineTypeNameAndDebug (rigidBodySolver , 0)
defineRunTimeSelectionTable() [4/4]
Foam::RBD::defineRunTimeSelectionTable (rigidBodySolver , dictionary)