OpenFOAM: relaxation Class Reference
relaxation Class Reference
Consumption rate per unit of flame area obtained from a relaxation equation.
Public Member Functions
TypeName ("relaxation")
Runtime type information.
relaxation (const word modelType, const dictionary &dictCoeffs, const fvMesh &mesh, const combustionModel &combModel)
Construct from dictionary and psiReactionThermo.
virtual ~relaxation ()
virtual void correct (const volScalarField &sigma)
Correct omega.
virtual bool read (const dictionary &dictProperties)
Update properties from given dictionary.
Public Member Functions inherited from reactionRateFlameArea
TypeName ("reactionRateFlameArea")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, reactionRateFlameArea, dictionary,(const word modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel),(modelType, dict, mesh, combModel))
reactionRateFlameArea (const word &modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel)
Construct from components.
virtual ~reactionRateFlameArea ()
const volScalarField & omega () const
Access functions.
Additional Inherited Members
Static Public Member Functions inherited from reactionRateFlameArea
static autoPtr< reactionRateFlameArea > New (const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel)
Protected Attributes inherited from reactionRateFlameArea
dictionary coeffDict_
Dictionary.
const fvMesh & mesh_
Mesh reference.
const combustionModel & combModel_
Combstion model owner.
word fuel_
Fuel name.
volScalarField omega_
Fuel consumption rate per unit of flame area.
Detailed Description
Consumption rate per unit of flame area obtained from a relaxation equation.
Source files
relaxation.H
relaxation.C
Definition at line 51 of file relaxation.H.
Constructor & Destructor Documentation
relaxation()
relaxation (const word modelType, const dictionary & dictCoeffs, const fvMesh & mesh, const combustionModel & combModel)
Construct from dictionary and psiReactionThermo.
Definition at line 51 of file relaxation.C.
~relaxation()
~relaxation () virtual
Definition at line 67 of file relaxation.C.
References relaxation::correct().
Member Function Documentation
TypeName()
TypeName ("relaxation")
Runtime type information.
correct()
void correct (const volScalarField & sigma) virtual
Correct omega.
Implements reactionRateFlameArea.
Definition at line 74 of file relaxation.C.
References Foam::fvm::ddt(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::fvm::div(), Foam::e, turbulenceModel::epsilon(), turbulenceModel::k(), Foam::mag(), phi, relaxation::read(), rho, Foam::solve(), Foam::sqr(), Foam::fvm::SuSp(), and turbulence.
Referenced by relaxation::~relaxation().
read()
bool read (const dictionary & dictProperties) virtual
Update properties from given dictionary.
Reimplemented from reactionRateFlameArea.
Definition at line 145 of file relaxation.C.
References dictionary::lookup(), reactionRateFlameArea::read(), ITstream::read(), and dictionary::subDict().
Referenced by relaxation::correct().
The documentation for this class was generated from the following files:
src/combustionModels/FSD/reactionRateFlameAreaModels/relaxation/relaxation.H
src/combustionModels/FSD/reactionRateFlameAreaModels/relaxation/relaxation.C