OpenFOAM: Foam::DelaunayMeshTools Namespace Reference
Foam::DelaunayMeshTools Namespace Reference
Functions
void writeOBJ (const fileName &fName, const List< Foam::point > &points)
Write list of points to file.
void writeOBJ (const fileName &fName, const List< Vb > &points)
Write list of points to file.
void writeObjMesh (const fileName &fName, const pointField &points, const faceList &faces)
Write an OBJ mesh consisting of points and faces.
template<class Triangulation >
void writeOBJ (const fileName &fName, const Triangulation &t, const indexedVertexEnum::vertexType startPointType, const indexedVertexEnum::vertexType endPointType)
Write Delaunay points in the range between (and including)
template<class Triangulation >
void writeOBJ (const fileName &fName, const Triangulation &t, const indexedVertexEnum::vertexType pointType)
Write Delaunay points of type pointType to .obj file.
template<class Triangulation >
void writeFixedPoints (const fileName &fName, const Triangulation &t)
Write the fixed Delaunay points to an OBJ file.
template<class Triangulation >
void writeBoundaryPoints (const fileName &fName, const Triangulation &t)
Write the boundary Delaunay points to an OBJ file.
template<class Triangulation >
void writeProcessorInterface (const fileName &fName, const Triangulation &t, const faceList &faces)
Write the processor interface to an OBJ file.
template<class Triangulation >
void writeInternalDelaunayVertices (const fileName &instance, const Triangulation &t)
Write the internal Delaunay vertices of the tessellation as a.
template<class CellHandle >
void drawDelaunayCell (Ostream &os, const CellHandle &c, label offset=0)
Draws a tet cell to an output stream. The offset is supplied as the tet.
template<class Triangulation >
tmp< pointField > allPoints (const Triangulation &t)
Extract all points in vertex-index order.
Function Documentation
writeOBJ() [1/4]
void Foam::DelaunayMeshTools::writeOBJ (const fileName & fName, const List< Foam::point > & points)
Write list of points to file.
writeOBJ() [2/4]
void Foam::DelaunayMeshTools::writeOBJ (const fileName & fName, const List< Vb > & points)
Write list of points to file.
writeObjMesh()
void Foam::DelaunayMeshTools::writeObjMesh (const fileName & fName, const pointField & points, const faceList & faces)
Write an OBJ mesh consisting of points and faces.
writeOBJ() [3/4]
void Foam::DelaunayMeshTools::writeOBJ (const fileName & fName, const Triangulation & t, const indexedVertexEnum::vertexType startPointType, const indexedVertexEnum::vertexType endPointType)
Write Delaunay points in the range between (and including)
type startPointType and endPointType to an OBJ file
writeOBJ() [4/4]
void Foam::DelaunayMeshTools::writeOBJ (const fileName & fName, const Triangulation & t, const indexedVertexEnum::vertexType pointType)
Write Delaunay points of type pointType to .obj file.
writeFixedPoints()
void Foam::DelaunayMeshTools::writeFixedPoints (const fileName & fName, const Triangulation & t)
Write the fixed Delaunay points to an OBJ file.
writeBoundaryPoints()
void Foam::DelaunayMeshTools::writeBoundaryPoints (const fileName & fName, const Triangulation & t)
Write the boundary Delaunay points to an OBJ file.
writeProcessorInterface()
void Foam::DelaunayMeshTools::writeProcessorInterface (const fileName & fName, const Triangulation & t, const faceList & faces)
Write the processor interface to an OBJ file.
writeInternalDelaunayVertices()
void Foam::DelaunayMeshTools::writeInternalDelaunayVertices (const fileName & instance, const Triangulation & t)
Write the internal Delaunay vertices of the tessellation as a.
pointField that may be used to restart the meshing process
drawDelaunayCell()
void Foam::DelaunayMeshTools::drawDelaunayCell (Ostream & os, const CellHandle & c, label offset = 0)
Draws a tet cell to an output stream. The offset is supplied as the tet.
number to be drawn.
allPoints()
tmp<pointField> Foam::DelaunayMeshTools::allPoints (const Triangulation & t)
Extract all points in vertex-index order.
Referenced by polyMeshAdder::add(), meshRefinement::collectAndPrint(), simpleGeomDecomp::decompose(), distributedTriSurfaceMesh::distribute(), NamedEnum< directionType, 3 >::names(), Foam::parseNASCoord(), Foam::readUpto(), and FacePostProcessing< CloudType >::write().