OpenFOAM: FSD< CombThermoType, ThermoType > Class Template Reference
FSD< CombThermoType, ThermoType > Class Template Reference
Flame Surface Dennsity (FDS) combustion model.
Public Member Functions
TypeName ("FSD")
Runtime type information.
FSD (const word &modelType, const fvMesh &mesh, const word &phaseName)
Construct from components.
virtual ~FSD ()
virtual void correct ()
Correct combustion rate.
virtual bool read ()
Update properties.
Public Member Functions inherited from singleStepCombustion< CombThermoType, ThermoType >
singleStepCombustion (const word &modelType, const fvMesh &mesh, const word &phaseName)
Construct from components.
virtual ~singleStepCombustion ()
Destructor.
virtual tmp< fvScalarMatrix > R (volScalarField &Y) const
Fuel consumption rate matrix.
virtual tmp< volScalarField > dQ () const
Heat release rate calculated from fuel consumption rate matrix.
virtual tmp< volScalarField > Sh () const
Sensible enthalpy source term.
Additional Inherited Members
Protected Attributes inherited from singleStepCombustion< CombThermoType, ThermoType >
singleStepReactingMixture< ThermoType > * singleMixturePtr_
Pointer to singleStepReactingMixture mixture.
volScalarField wFuel_
Fuel consumption rate.
bool semiImplicit_
Semi-implicit (true) or explicit (false) treatment.
Detailed Description
template<class CombThermoType, class ThermoType>
class Foam::combustionModels::FSD< CombThermoType, ThermoType >
Flame Surface Dennsity (FDS) combustion model.
The fuel source term is given by mgft*pc*omegaFuelBar.
where: mgft: filtered flame area. pc: probability of the combustion progress. omegaFuelBar: filtered consumption speed per unit of flame area.
pc is considered from the IFC solution. omegaFuelBar is calculated solving a relaxation equation which tends to omegaEq. This omegaEq is obtained from the flamelet solution for different strain rates and fit using a expential distribution.
The spacial distribution of the consumption speed (omega) is obtained also from a strained flamelet solution and it is assumed to have a guassian distribution.
If the grid resolution is not enough to resolve the flame, the consumption speed distribution is linearly thickened conserving the overall heat release.
If the turbulent fluctuation of the mixture fraction at the sub-grid level is large (>1e-04) then a beta pdf is used for filtering.
At the moment the flame area combustion model is only fit to work in a LES frame work. In RAS the subgrid fluctuation has to be solved by an extra transport equation.
Source files
FSD.H
FSD.C
Definition at line 80 of file FSD.H.
Constructor & Destructor Documentation
FSD()
FSD (const word & modelType, const fvMesh & mesh, const word & phaseName)
Construct from components.
Definition at line 41 of file FSD.C.
~FSD()
~FSD () virtual
Definition at line 89 of file FSD.C.
References Foam::constant::physicoChemical::b, Foam::constant::universal::c, IOobject::db(), delta, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimLength, Foam::dimless, Foam::fvc::div(), Foam::e, Foam::exp(), forAll, Foam::fvc::grad(), IOobject::groupName(), objectRegistry::lookupObject(), Foam::mag(), Foam::max(), mesh, DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), IOobject::NO_READ, IOobject::NO_WRITE, Foam::pow(), turbulenceModel::propertiesName, tmp< T >::ref(), GeometricField< Type, PatchField, GeoMesh >::ref(), s(), Foam::constant::physicoChemical::sigma, Foam::sqr(), IOobject::time(), Time::timeName(), U, and dimensioned< Type >::value().
Member Function Documentation
TypeName()
TypeName ("FSD< CombThermoType, ThermoType >")
Runtime type information.
correct()
void correct () virtual
Correct combustion rate.
Definition at line 337 of file FSD.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, and Foam::pow3().
read()
bool read () virtual
Update properties.
Reimplemented from singleStepCombustion< CombThermoType, ThermoType >.
Definition at line 350 of file FSD.C.
The documentation for this class was generated from the following files:
src/combustionModels/FSD/FSD.H
src/combustionModels/FSD/FSD.C