OpenFOAM: ensightPartCells Class Reference
ensightPartCells Class Reference
An implementation of ensightPart to hold volume mesh cells.
Public Member Functions
TypeName ("ensightCells")
Runtime type information.
ensightPartCells (label partNumber, const string &partDescription)
Construct empty part with number and description.
ensightPartCells (label partNumber, const polyMesh &)
Construct from polyMesh without zones.
ensightPartCells (label partNumber, const polyMesh &, const labelUList &)
Construct from polyMesh and list of (non-zoned) cells.
ensightPartCells (label partNumber, const polyMesh &, const cellZone &)
Construct from polyMesh and cellZone.
ensightPartCells (const ensightPartCells &)
Construct as copy.
ensightPartCells (Istream &)
Reconstruct part characteristics (eg, element types) from Istream.
virtual ~ensightPartCells ()
Destructor.
virtual void writeGeometry (ensightGeoFile &) const
Write geometry.
virtual const List< word > & elementTypes () const
Static listing of the element types.
Public Member Functions inherited from ensightPart
TypeName ("ensightPart")
Runtime type information.
ensightPart ()
Construct null.
ensightPart (label partNumber, const string &partDescription)
Construct empty part with number and description.
ensightPart (label partNumber, const string &partDescription, const pointField &points)
Construct part with number, description and points reference.
ensightPart (const ensightPart &)
Construct as copy.
declareRunTimeSelectionTable (autoPtr, ensightPart, istream,(Istream &is),(is))
autoPtr< ensightPart > clone () const
Construct and return clone.
virtual ~ensightPart ()
Destructor.
label size () const
Number of elements in this part.
bool isCellData () const
Represents cell data.
bool isFaceData () const
Represents face data.
label number () const
Part number.
const string & name () const
Part name or description.
label materialId () const
Material id.
void name (const string &value)
non-const access to part name or description
void materialId (const label value)
non-const access to material id
const labelListList & elemLists () const
Simple labelList with a name.
label offset () const
Offset for element ids.
void renumber (const labelUList &)
Renumber elements.
bool writeSummary (Ostream &) const
Write summary information about the object.
bool writeData (Ostream &) const
Write reconstruction information for the object.
void writeGeometry (ensightGeoFile &, const pointField &) const
Helper: write geometry given the pointField.
void writeScalarField (ensightFile &, const List< scalar > &field, const bool perNode=false) const
Write scalar field.
void writeVectorField (ensightFile &, const List< scalar > &field0, const List< scalar > &field1, const List< scalar > &field2, const bool perNode=false) const
Write vector field components.
template<class Type >
void writeField (ensightFile &, const Field< Type > &, const bool perNode=false) const
Write generalized field components.
void operator= (const ensightPart &)
Disallow default bitwise assignment.
Static Public Member Functions
static autoPtr< ensightPartCells > New (Istream &is)
Reconstruct part characteristics on freestore from Istream.
Static Public Member Functions inherited from ensightPart
static autoPtr< ensightPart > New (Istream &)
Reconstruct part characteristics on freestore from Istream.
Protected Types
enum elemType {
tetra4Elements, pyramid5Elements, penta6Elements, hexa8Elements,
nfacedElements
}
Addressable ensight element types.
Protected Attributes
const polyMesh & mesh_
Mesh referenced.
Protected Attributes inherited from ensightPart
label number_
Part number.
string name_
Part name (or description)
labelListList elemLists_
Simple labelList with a name.
label offset_
Start offset for elemLists_.
label size_
Number of elements in this part.
bool isCellData_
Cell or face data.
label matId_
Material id (numeric)
const pointField & points_
pointField referenced
Static Protected Attributes
static const List< word > elemTypes_
Additional Inherited Members
Protected Member Functions inherited from ensightPart
void reconstruct (Istream &)
Reconstruct part characteristics (eg, element types) from Istream.
bool isFieldDefined (const List< scalar > &) const
Check for fully defined fields.
void writeHeader (ensightFile &, bool withDescription=false) const
Write the part header.
void writeFieldList (ensightFile &os, const List< scalar > &field, const labelUList &idList) const
Write a scalar field for idList.
Detailed Description
An implementation of ensightPart to hold volume mesh cells.
Source files
ensightPartCells.H
ensightPartCells.C
Definition at line 49 of file ensightPartCells.H.
Member Enumeration Documentation
elemType
enum elemType protected
Addressable ensight element types.
Enumerator
tetra4Elements
pyramid5Elements
penta6Elements
hexa8Elements
nfacedElements
Definition at line 84 of file ensightPartCells.H.
Constructor & Destructor Documentation
ensightPartCells() [1/6]
ensightPartCells (label partNumber, const string & partDescription)
Construct empty part with number and description.
Definition at line 179 of file ensightPartCells.C.
Referenced by ensightPartCells::ensightPartCells(), and ensightPartCells::New().
ensightPartCells() [2/6]
ensightPartCells (label partNumber, const polyMesh & mesh)
Construct from polyMesh without zones.
Definition at line 190 of file ensightPartCells.C.
References ensightPartCells::ensightPartCells().
ensightPartCells() [3/6]
ensightPartCells (label partNumber, const polyMesh & mesh, const labelUList & idList)
Construct from polyMesh and list of (non-zoned) cells.
Definition at line 203 of file ensightPartCells.C.
References ensightPartCells::ensightPartCells().
ensightPartCells() [4/6]
ensightPartCells (label partNumber, const polyMesh & mesh, const cellZone & cZone)
Construct from polyMesh and cellZone.
Definition at line 217 of file ensightPartCells.C.
ensightPartCells() [5/6]
ensightPartCells (const ensightPartCells & part)
Construct as copy.
Definition at line 230 of file ensightPartCells.C.
ensightPartCells() [6/6]
ensightPartCells (Istream & is)
Reconstruct part characteristics (eg, element types) from Istream.
A part reconstructed in this manner can be used when writing fields, but cannot be used to write a new geometry
See also
Foam::ensightPart::reconstruct
Definition at line 237 of file ensightPartCells.C.
References ensightPart::reconstruct().
~ensightPartCells()
~ensightPartCells () virtual
Destructor.
Definition at line 248 of file ensightPartCells.C.
References primitiveMesh::cells(), primitiveMesh::cellShapes(), ensightPart::elemLists_, f(), faceId(), polyMesh::faceOwner(), polyMesh::faces(), forAll, ensightPart::localPoints::list, ensightPartCells::mesh_, ensightFile::newline(), nPoints, ensightPart::localPoints::nPoints, ensightPart::offset_, ensightPart::points_, List< T >::size(), UList< T >::size(), ensightFile::write(), and ensightGeoFile::writeKeyword().
Referenced by ensightPartCells::New().
Member Function Documentation
TypeName()
TypeName ("ensightCells")
Runtime type information.
New()
static autoPtr<ensightPartCells> New (Istream & is) inline static
Reconstruct part characteristics on freestore from Istream.
Definition at line 144 of file ensightPartCells.H.
References ensightPartCells::ensightPartCells(), ensightPartCells::writeGeometry(), and ensightPartCells::~ensightPartCells().
writeGeometry()
void writeGeometry (ensightGeoFile & os) const virtual
Write geometry.
Reimplemented from ensightPart.
Definition at line 402 of file ensightPartCells.C.
References ensightPart::points_, and ensightPart::writeGeometry().
Referenced by ensightPartCells::New().
elementTypes()
virtual const List<word>& elementTypes () const inline virtual
Static listing of the element types.
Reimplemented from ensightPart.
Definition at line 160 of file ensightPartCells.H.
References ensightPartCells::elemTypes_.
Member Data Documentation
elemTypes_
const Foam::List< Foam::word > elemTypes_ static protected
Definition at line 96 of file ensightPartCells.H.
Referenced by ensightPartCells::elementTypes().
mesh_
const polyMesh& mesh_ protected
Mesh referenced.
Definition at line 102 of file ensightPartCells.H.
Referenced by ensightPartCells::~ensightPartCells().
The documentation for this class was generated from the following files:
src/conversion/ensight/part/ensightPartCells.H
src/conversion/ensight/part/ensightPartCells.C