OpenFOAM: ensightPartFaces Class Reference
ensightPartFaces Class Reference
An implementation of ensightPart to hold volume mesh faces.
Public Member Functions
TypeName ("ensightFaces")
Runtime type information.
ensightPartFaces (label partNumber, const string &partDescription)
Construct empty part with number and description.
ensightPartFaces (label partNumber, const string &partDescription, const pointField &, const faceList &, const bool contiguousPoints=false)
Construct part with number, description, points and faces.
ensightPartFaces (label partNumber, const polyMesh &, const polyPatch &)
Construct from polyMesh and polyPatch.
ensightPartFaces (const ensightPartFaces &)
Construct as copy.
ensightPartFaces (Istream &)
Reconstruct part characteristics (eg, element types) from Istream.
virtual ~ensightPartFaces ()
Destructor.
virtual void writeGeometry (ensightGeoFile &) const
Write geometry.
virtual const List< word > & elementTypes () const
Static listing of the element types.
Public Member Functions inherited from ensightPart
TypeName ("ensightPart")
Runtime type information.
ensightPart ()
Construct null.
ensightPart (label partNumber, const string &partDescription)
Construct empty part with number and description.
ensightPart (label partNumber, const string &partDescription, const pointField &points)
Construct part with number, description and points reference.
ensightPart (const ensightPart &)
Construct as copy.
declareRunTimeSelectionTable (autoPtr, ensightPart, istream,(Istream &is),(is))
autoPtr< ensightPart > clone () const
Construct and return clone.
virtual ~ensightPart ()
Destructor.
label size () const
Number of elements in this part.
bool isCellData () const
Represents cell data.
bool isFaceData () const
Represents face data.
label number () const
Part number.
const string & name () const
Part name or description.
label materialId () const
Material id.
void name (const string &value)
non-const access to part name or description
void materialId (const label value)
non-const access to material id
const labelListList & elemLists () const
Simple labelList with a name.
label offset () const
Offset for element ids.
void renumber (const labelUList &)
Renumber elements.
bool writeSummary (Ostream &) const
Write summary information about the object.
bool writeData (Ostream &) const
Write reconstruction information for the object.
void writeGeometry (ensightGeoFile &, const pointField &) const
Helper: write geometry given the pointField.
void writeScalarField (ensightFile &, const List< scalar > &field, const bool perNode=false) const
Write scalar field.
void writeVectorField (ensightFile &, const List< scalar > &field0, const List< scalar > &field1, const List< scalar > &field2, const bool perNode=false) const
Write vector field components.
template<class Type >
void writeField (ensightFile &, const Field< Type > &, const bool perNode=false) const
Write generalized field components.
void operator= (const ensightPart &)
Disallow default bitwise assignment.
Static Public Member Functions
static autoPtr< ensightPartFaces > New (Istream &is)
Reconstruct part characteristics on freestore from Istream.
Static Public Member Functions inherited from ensightPart
static autoPtr< ensightPart > New (Istream &)
Reconstruct part characteristics on freestore from Istream.
Protected Types
enum elemType { tria3Elements, quad4Elements, nsidedElements }
Addressable ensight element types.
Protected Member Functions
void classify (const faceList &)
Classify the face shapes, set elemLists.
void writeConnectivity (ensightGeoFile &, const word &key, const faceList &, const labelUList &idList, const labelUList &pointMap) const
Helper: write connectivity.
Protected Member Functions inherited from ensightPart
void reconstruct (Istream &)
Reconstruct part characteristics (eg, element types) from Istream.
bool isFieldDefined (const List< scalar > &) const
Check for fully defined fields.
void writeHeader (ensightFile &, bool withDescription=false) const
Write the part header.
void writeFieldList (ensightFile &os, const List< scalar > &field, const labelUList &idList) const
Write a scalar field for idList.
Protected Attributes
const faceList & faces_
Faces referenced.
const bool contiguousPoints_
Can skip local point renumbering when points are contiguous.
Protected Attributes inherited from ensightPart
label number_
Part number.
string name_
Part name (or description)
labelListList elemLists_
Simple labelList with a name.
label offset_
Start offset for elemLists_.
label size_
Number of elements in this part.
bool isCellData_
Cell or face data.
label matId_
Material id (numeric)
const pointField & points_
pointField referenced
Static Protected Attributes
static const List< word > elemTypes_
Detailed Description
An implementation of ensightPart to hold volume mesh faces.
Source files
ensightPartFaces.H
ensightPartFaces.C
Definition at line 48 of file ensightPartFaces.H.
Member Enumeration Documentation
elemType
enum elemType protected
Addressable ensight element types.
Enumerator
tria3Elements
quad4Elements
nsidedElements
Definition at line 73 of file ensightPartFaces.H.
Constructor & Destructor Documentation
ensightPartFaces() [1/5]
ensightPartFaces (label partNumber, const string & partDescription)
Construct empty part with number and description.
Definition at line 121 of file ensightPartFaces.C.
Referenced by ensightPartFaces::classify(), ensightPartFaces::ensightPartFaces(), and ensightPartFaces::New().
ensightPartFaces() [2/5]
ensightPartFaces (label partNumber, const string & partDescription, const pointField & points, const faceList & faces, const bool contiguousPoints = false)
Construct part with number, description, points and faces.
Can skip local point renumbering when points are contiguous
Definition at line 137 of file ensightPartFaces.C.
References ensightPartFaces::ensightPartFaces().
ensightPartFaces() [3/5]
ensightPartFaces (label partNumber, const polyMesh & mesh, const polyPatch & patch)
Construct from polyMesh and polyPatch.
Definition at line 159 of file ensightPartFaces.C.
References polyPatch::start().
ensightPartFaces() [4/5]
ensightPartFaces (const ensightPartFaces & part)
Construct as copy.
Definition at line 177 of file ensightPartFaces.C.
ensightPartFaces() [5/5]
ensightPartFaces (Istream & is)
Reconstruct part characteristics (eg, element types) from Istream.
A part reconstructed in this manner can be used when writing fields, but cannot be used to write a new geometry
See also
Foam::ensightPart::reconstruct
Definition at line 185 of file ensightPartFaces.C.
References ensightPart::isCellData_, and ensightPart::reconstruct().
~ensightPartFaces()
~ensightPartFaces () virtual
Destructor.
Definition at line 198 of file ensightPartFaces.C.
References ensightPartFaces::contiguousPoints_, ensightPart::elemLists_, f(), ensightPartFaces::faces_, forAll, Foam::identity(), ensightPart::localPoints::list, nPoints, ensightPart::localPoints::nPoints, ensightPart::offset_, ensightPart::points_, and List< T >::size().
Referenced by ensightPartFaces::New().
Member Function Documentation
classify()
void classify (const faceList & faces) protected
Classify the face shapes, set elemLists.
Definition at line 52 of file ensightPartFaces.C.
References ensightPartFaces::ensightPartFaces(), f(), forAll, List< T >::setSize(), and List< T >::size().
writeConnectivity()
void writeConnectivity (ensightGeoFile & os, const word & key, const faceList & faces, const labelUList & idList, const labelUList & pointMap) const protected
Helper: write connectivity.
Definition at line 254 of file ensightPartFaces.C.
References f(), ensightPartFaces::faces_, forAll, ensightFile::newline(), ensightPart::offset_, List< T >::size(), UList< T >::size(), ensightFile::write(), and ensightGeoFile::writeKeyword().
TypeName()
TypeName ("ensightFaces")
Runtime type information.
New()
static autoPtr<ensightPartFaces> New (Istream & is) inline static
Reconstruct part characteristics on freestore from Istream.
Definition at line 150 of file ensightPartFaces.H.
References ensightPartFaces::ensightPartFaces(), ensightPartFaces::writeGeometry(), and ensightPartFaces::~ensightPartFaces().
writeGeometry()
void writeGeometry (ensightGeoFile & os) const virtual
Write geometry.
Reimplemented from ensightPart.
Definition at line 316 of file ensightPartFaces.C.
References ensightPart::points_, and ensightPart::writeGeometry().
Referenced by ensightPartFaces::New().
elementTypes()
virtual const List<word>& elementTypes () const inline virtual
Static listing of the element types.
Reimplemented from ensightPart.
Definition at line 166 of file ensightPartFaces.H.
References ensightPartFaces::elemTypes_.
Member Data Documentation
elemTypes_
const Foam::List< Foam::word > elemTypes_ static protected
Definition at line 83 of file ensightPartFaces.H.
Referenced by ensightPartFaces::elementTypes().
faces_
const faceList& faces_ protected
Faces referenced.
Definition at line 89 of file ensightPartFaces.H.
Referenced by ensightPartFaces::writeConnectivity(), and ensightPartFaces::~ensightPartFaces().
contiguousPoints_
const bool contiguousPoints_ protected
Can skip local point renumbering when points are contiguous.
Definition at line 92 of file ensightPartFaces.H.
Referenced by ensightPartFaces::~ensightPartFaces().
The documentation for this class was generated from the following files:
src/conversion/ensight/part/ensightPartFaces.H
src/conversion/ensight/part/ensightPartFaces.C