OpenFOAM: noCombustion< CombThermoType > Class Template Reference
noCombustion< CombThermoType > Class Template Reference
Dummy combustion model for 'no combustion'.
Public Member Functions
TypeName ("noCombustion")
Runtime type information.
noCombustion (const word &modelType, const fvMesh &mesh, const word &phaseName)
Construct from components.
virtual ~noCombustion ()
Destructor.
virtual void correct ()
Correct combustion rate.
virtual tmp< fvScalarMatrix > R (volScalarField &Y) const
Fuel consumption rate matrix.
virtual tmp< volScalarField > dQ () const
Heat release rate calculated from fuel consumption rate matrix.
virtual tmp< volScalarField > Sh () const
Return source for enthalpy equation [kg/m/s3].
virtual bool read ()
Update properties from given dictionary.
Detailed Description
template<class CombThermoType>
class Foam::combustionModels::noCombustion< CombThermoType >
Dummy combustion model for 'no combustion'.
Source files
noCombustion.H
noCombustion.C
Definition at line 49 of file noCombustion.H.
Constructor & Destructor Documentation
noCombustion()
noCombustion (const word & modelType, const fvMesh & mesh, const word & phaseName)
Construct from components.
Definition at line 33 of file noCombustion.C.
~noCombustion()
~noCombustion () virtual
Destructor.
Definition at line 46 of file noCombustion.C.
Member Function Documentation
TypeName()
TypeName ("noCombustion< CombThermoType >")
Runtime type information.
correct()
void correct () virtual
Correct combustion rate.
Definition at line 53 of file noCombustion.C.
References noCombustion< CombThermoType >::R().
R()
Foam::tmp< Foam::fvScalarMatrix > R (volScalarField & Y) const virtual
Fuel consumption rate matrix.
Definition at line 62 of file noCombustion.C.
References Foam::dimMass, and Foam::dimTime.
Referenced by noCombustion< CombThermoType >::correct().
dQ()
Foam::tmp< Foam::volScalarField > dQ () const virtual
Heat release rate calculated from fuel consumption rate matrix.
Definition at line 77 of file noCombustion.C.
References Foam::dimEnergy, Foam::dimTime, mesh, and timeName.
Sh()
Foam::tmp< Foam::volScalarField > Sh () const virtual
Return source for enthalpy equation [kg/m/s3].
Definition at line 103 of file noCombustion.C.
References Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, mesh, and timeName.
read()
bool read () virtual
Update properties from given dictionary.
Definition at line 128 of file noCombustion.C.
References Foam::read().
The documentation for this class was generated from the following files:
src/combustionModels/noCombustion/noCombustion.H
src/combustionModels/noCombustion/noCombustion.C