OpenFOAM: ensightParts Class Reference
ensightParts Class Reference
A collection of several ensightPart elements.
Public Member Functions
ensightParts (const polyMesh &)
Construct from polyMesh.
ensightParts (const IOobject &)
Construct from IOobject.
~ensightParts ()
Destructor.
void recalculate (const polyMesh &)
Clear old information and construct anew from polyMesh.
void renumber (const labelUList &origCellId, const labelUList &origFaceId)
Renumber elements.
label size () const
Number of parts.
void writeGeometry (ensightGeoFile &) const
Write the geometry.
bool writeSummary (Ostream &) const
Write summary information about the objects.
void writeData (Ostream &) const
Write the lists.
void writeScalarField (ensightFile &, const List< scalar > &field, const bool useFaceData=false, const bool perNode=false) const
Write (volume) scalar field.
void writeVectorField (ensightFile &, const List< scalar > &field0, const List< scalar > &field1, const List< scalar > &field2, const bool useFaceData=false, const bool perNode=false) const
Write (volume) vector field components.
template<class Type >
void writeField (ensightFile &, const GeometricField< Type, fvPatchField, volMesh > &) const
Write generalized volume field components.
Friends
ensightGeoFile & operator<< (ensightGeoFile &, const ensightParts &)
Write geometry.
Detailed Description
A collection of several ensightPart elements.
Source files
ensightParts.H
ensightParts.C
ensightPartsTemplates.C
Definition at line 59 of file ensightParts.H.
Constructor & Destructor Documentation
ensightParts() [1/2]
ensightParts (const polyMesh & mesh)
Construct from polyMesh.
Definition at line 30 of file ensightParts.C.
References ensightParts::recalculate().
ensightParts() [2/2]
ensightParts (const IOobject & ioObj)
Construct from IOobject.
Definition at line 38 of file ensightParts.C.
~ensightParts()
~ensightParts ()
Destructor.
Definition at line 49 of file ensightParts.C.
Member Function Documentation
recalculate()
void recalculate (const polyMesh & mesh)
Clear old information and construct anew from polyMesh.
Definition at line 55 of file ensightParts.C.
References polyMesh::boundaryMesh(), polyMesh::cellZones(), forAll, primitiveMesh::nCells(), patchi, ensightParts::renumber(), List< T >::size(), and UPtrList< T >::size().
Referenced by ensightParts::ensightParts().
renumber()
void renumber (const labelUList & origCellId, const labelUList & origFaceId)
Renumber elements.
Definition at line 164 of file ensightParts.C.
References forAll.
Referenced by ensightParts::recalculate().
size()
label size () const inline
Number of parts.
Definition at line 103 of file ensightParts.H.
References ensightParts::operator<<, UPtrList< T >::size(), ensightParts::writeData(), ensightParts::writeField(), ensightParts::writeGeometry(), ensightParts::writeScalarField(), ensightParts::writeSummary(), and ensightParts::writeVectorField().
writeGeometry()
void writeGeometry (ensightGeoFile & os) const
Write the geometry.
Definition at line 183 of file ensightParts.C.
References Foam::flush(), forAll, Foam::Info, and Foam::nl.
Referenced by ensightParts::size().
writeSummary()
bool writeSummary (Ostream & os) const
Write summary information about the objects.
Definition at line 196 of file ensightParts.C.
References forAll.
Referenced by ensightParts::size().
writeData()
void writeData (Ostream & os) const
Write the lists.
Definition at line 207 of file ensightParts.C.
References token::BEGIN_LIST, IOstream::check(), token::END_LIST, forAll, Foam::nl, and ensightParts::writeScalarField().
Referenced by ensightParts::size().
writeScalarField()
void writeScalarField (ensightFile & os, const List< scalar > & field, const bool useFaceData = false, const bool perNode = false) const
Write (volume) scalar field.
optionally write data for face parts optionally write data per node
Definition at line 228 of file ensightParts.C.
References forAll, and ensightParts::writeVectorField().
Referenced by ensightParts::size(), and ensightParts::writeData().
writeVectorField()
void writeVectorField (ensightFile & os, const List< scalar > & field0, const List< scalar > & field1, const List< scalar > & field2, const bool useFaceData = false, const bool perNode = false) const
Write (volume) vector field components.
optionally write data for face parts optionally write data per node
Definition at line 251 of file ensightParts.C.
References forAll.
Referenced by ensightParts::size(), and ensightParts::writeScalarField().
writeField()
void writeField (ensightFile & os, const GeometricField< Type, fvPatchField, volMesh > & field) const
Write generalized volume field components.
Definition at line 35 of file ensightPartsTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, and patchi.
Referenced by ensightParts::size().
Friends And Related Function Documentation
operator<<
ensightGeoFile& operator<< (ensightGeoFile & , const ensightParts &) friend
Write geometry.
Referenced by ensightParts::size().
The documentation for this class was generated from the following files:
src/conversion/ensight/part/ensightParts.H
src/conversion/ensight/part/ensightParts.C
src/conversion/ensight/part/ensightPartsTemplates.C