OpenFOAM: ensightPart::localPoints Class Reference
ensightPart::localPoints Class Reference
Track the points used by the part and map global to local indices.
Public Member Functions
localPoints ()
Null constructor.
localPoints (const pointField &pts)
Construct for mesh points.
Public Attributes
label nPoints
Number of points used.
labelList list
Map global to local indices.
Detailed Description
Track the points used by the part and map global to local indices.
Definition at line 105 of file ensightPart.H.
Constructor & Destructor Documentation
localPoints() [1/2]
localPoints () inline
Null constructor.
Definition at line 115 of file ensightPart.H.
Referenced by ensightPart::calcLocalPoints().
localPoints() [2/2]
localPoints (const pointField & pts) inline
Construct for mesh points.
Definition at line 122 of file ensightPart.H.
References ensightPart::isFieldDefined(), ensightPart::reconstruct(), ensightPart::writeFieldList(), and ensightPart::writeHeader().
Member Data Documentation
nPoints
label nPoints
Number of points used.
Definition at line 109 of file ensightPart.H.
Referenced by ensightPart::writeGeometry(), ensightPartCells::~ensightPartCells(), and ensightPartFaces::~ensightPartFaces().
list
labelList list
Map global to local indices.
Definition at line 112 of file ensightPart.H.
Referenced by ensightPart::writeGeometry(), ensightPartCells::~ensightPartCells(), and ensightPartFaces::~ensightPartFaces().
The documentation for this class was generated from the following file:
src/conversion/ensight/part/ensightPart.H