OpenFOAM: ensightFile Class Reference
ensightFile Class Reference
Ensight output with specialized write() for strings, integers and floats. Correctly handles binary write as well.
Public Member Functions
ensightFile (const fileName &pathname, IOstream::streamFormat format=IOstream::BINARY)
Construct from pathname.
~ensightFile ()
Destructor.
virtual Ostream & write (const char *buf, std::streamsize count)
Binary write.
virtual Ostream & writeKeyword (const string &key)
Write element keyword with trailing newline, optionally with undef.
Ostream & writeBinaryHeader ()
Write "C Binary" for binary files (eg, geometry/measured)
Ostream & writeUndef ()
Write undef value.
Ostream & write (const char *value)
Write C-string as "%80s" or as binary.
Ostream & write (const string &value)
Write string as "%80s" or as binary.
Ostream & write (const label value)
Write integer as "%10d" or as binary.
Ostream & write (const label value, const label fieldWidth)
Write integer with specified width or as binary.
Ostream & write (const scalar value)
Write float as "%12.5e" or as binary.
void newline ()
Add carriage return to ascii stream.
Public Member Functions inherited from OFstream
ClassName ("OFstream")
OFstream (const fileName &pathname, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct from pathname.
~OFstream ()
Destructor.
const fileName & name () const
Return the name of the stream.
fileName & name ()
Return non-const access to the name of the stream.
virtual ostream & stdStream ()
Access to underlying std::ostream.
virtual const ostream & stdStream () const
Const access to underlying std::ostream.
void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from OSstream
OSstream (ostream &os, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
virtual Ostream & write (const token &)
Write next token to stream.
virtual Ostream & write (const char)
Write character.
virtual Ostream & write (const word &)
Write word.
virtual Ostream & writeQuoted (const std::string &, const bool quoted=true)
Write std::string surrounded by quotes.
virtual Ostream & write (const int32_t)
Write int32_t.
virtual Ostream & write (const int64_t)
Write int64_t.
virtual Ostream & write (const floatScalar)
Write floatScalar.
virtual Ostream & write (const doubleScalar)
Write doubleScalar.
virtual void indent ()
Add indentation characters.
virtual ios_base::fmtflags flags (const ios_base::fmtflags flags)
Set flags of output stream.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual int width () const
Get width of output field.
virtual int width (const int)
Set width of output field (and return old width)
virtual int precision () const
Get precision of output field.
virtual int precision (const int)
Set precision of output field (and return old precision)
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Ostream ()
Destructor.
virtual Ostream & write (const keyType &)
Write keyType.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Incrememt the indent level.
void decrIndent ()
Decrememt the indent level.
Ostream & writeKeyword (const keyType &)
Write the keyword followed by an appropriate indentation.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Static Public Member Functions
static bool allowUndef ()
Return setting for whether 'undef' values are allowed in results.
static string mask ()
The '*' mask appropriate for subDir.
static string subDir (const label)
Consistent zero-padded numbers for subdirectories.
static void subDirWidth (const label)
Set width of subDir and mask. Default width is 8 digits.
static label subDirWidth ()
Return current width of subDir and mask.
static bool allowUndef (bool)
static scalar undefValue (const scalar)
Assign the value to represent undef in the results.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from Ostream
unsigned short indentLevel_
Current indent level.
Protected Attributes inherited from IOstream
label lineNumber_
Static Protected Attributes inherited from Ostream
static const unsigned short indentSize_ = 4
Number of spaces per indent level.
static const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Detailed Description
Ensight output with specialized write() for strings, integers and floats. Correctly handles binary write as well.
Definition at line 47 of file ensightFile.H.
Constructor & Destructor Documentation
ensightFile()
ensightFile (const fileName & pathname, IOstream::streamFormat format = IOstream::BINARY)
Construct from pathname.
Definition at line 85 of file ensightFile.C.
References OSstream::precision(), Foam::scientific(), and IOstream::setf().
~ensightFile()
~ensightFile ()
Destructor.
Definition at line 104 of file ensightFile.C.
Member Function Documentation
allowUndef() [1/2]
bool allowUndef () static
Return setting for whether 'undef' values are allowed in results.
Definition at line 110 of file ensightFile.C.
Referenced by ensightPart::writeScalarField(), and ensightPart::writeVectorField().
mask()
Foam::string mask () static
The '*' mask appropriate for subDir.
Definition at line 43 of file ensightFile.C.
subDir()
Foam::string subDir (const label n) static
Consistent zero-padded numbers for subdirectories.
Definition at line 49 of file ensightFile.C.
References n.
subDirWidth() [1/2]
void subDirWidth (const label n) static
Set width of subDir and mask. Default width is 8 digits.
Max width is 31 digits.
Definition at line 58 of file ensightFile.C.
subDirWidth() [2/2]
Foam::label subDirWidth () static
Return current width of subDir and mask.
Definition at line 76 of file ensightFile.C.
allowUndef() [2/2]
bool allowUndef (bool value) static
Definition at line 116 of file ensightFile.C.
undefValue()
Foam::scalar undefValue (const scalar value) static
Assign the value to represent undef in the results.
Returns the previous value NB: do not use values larger than floatScalarVGREAT
Definition at line 124 of file ensightFile.C.
References ensightFile::write().
write() [1/6]
Foam::Ostream & write (const char * buf, std::streamsize count) virtual
Binary write.
Reimplemented from OSstream.
Definition at line 136 of file ensightFile.C.
References OFstream::stdStream().
Referenced by ensightFile::undefValue(), ensightFile::write(), ensightFile::writeBinaryHeader(), ensightPartFaces::writeConnectivity(), ensightPart::writeFieldList(), ensightPart::writeGeometry(), ensightPart::writeHeader(), ensightGeoFile::writeKeyword(), ensightFile::writeKeyword(), ensightFile::writeUndef(), and ensightPartCells::~ensightPartCells().
writeKeyword()
Foam::Ostream & writeKeyword (const string & key) virtual
Write element keyword with trailing newline, optionally with undef.
Reimplemented in ensightGeoFile.
Definition at line 275 of file ensightFile.C.
References ensightFile::newline(), and ensightFile::write().
Referenced by ensightPart::writeField(), ensightPart::writeScalarField(), and ensightPart::writeVectorField().
writeBinaryHeader()
Foam::Ostream & writeBinaryHeader ()
Write "C Binary" for binary files (eg, geometry/measured)
Definition at line 293 of file ensightFile.C.
References IOstream::BINARY, IOstream::format(), and ensightFile::write().
writeUndef()
Foam::Ostream & writeUndef ()
Write undef value.
Definition at line 268 of file ensightFile.C.
References ensightFile::write().
Referenced by ensightPart::writeFieldList().
write() [2/6]
Foam::Ostream & write (const char * value) virtual
Write C-string as "%80s" or as binary.
Reimplemented from OSstream.
Definition at line 146 of file ensightFile.C.
References ensightFile::write().
write() [3/6]
Foam::Ostream & write (const string & value) virtual
Write string as "%80s" or as binary.
Reimplemented from OSstream.
Definition at line 152 of file ensightFile.C.
References IOstream::BINARY, IOstream::format(), n, OFstream::stdStream(), and ensightFile::write().
write() [4/6]
Foam::Ostream & write (const label value)
Write integer as "%10d" or as binary.
Definition at line 189 of file ensightFile.C.
References IOstream::BINARY, IOstream::format(), OFstream::stdStream(), and ensightFile::write().
write() [5/6]
Foam::Ostream & write (const label value, const label fieldWidth)
Write integer with specified width or as binary.
Definition at line 212 of file ensightFile.C.
References IOstream::BINARY, IOstream::format(), OFstream::stdStream(), and ensightFile::write().
write() [6/6]
Foam::Ostream & write (const scalar value)
Write float as "%12.5e" or as binary.
Definition at line 237 of file ensightFile.C.
References IOstream::BINARY, IOstream::format(), OFstream::stdStream(), and ensightFile::write().
newline()
void newline ()
Add carriage return to ascii stream.
Definition at line 259 of file ensightFile.C.
References IOstream::ASCII, IOstream::format(), Foam::nl, and OFstream::stdStream().
Referenced by ensightPartFaces::writeConnectivity(), ensightPart::writeFieldList(), ensightPart::writeGeometry(), ensightPart::writeHeader(), ensightGeoFile::writeKeyword(), ensightFile::writeKeyword(), and ensightPartCells::~ensightPartCells().
The documentation for this class was generated from the following files:
src/conversion/ensight/file/ensightFile.H
src/conversion/ensight/file/ensightFile.C