OpenFOAM: boundaryRegion Class Reference
boundaryRegion Class Reference
The boundaryRegion persistent data saved as a Map<dictionary>.
Public Member Functions
boundaryRegion ()
Construct null.
boundaryRegion (const objectRegistry &, const word &name="boundaryRegion", const fileName &instance="constant")
Construct read from registry, name. instance.
~boundaryRegion ()
Destructor.
label append (const dictionary &)
Append to the end, return index.
label findIndex (const word &name) const
Return index corresponding to patch 'name'.
Map< word > names () const
Return a Map of (id => name)
Map< word > names (const UList< wordRe > &patterns) const
Return a Map of (id => names) selected by patterns.
Map< word > boundaryTypes () const
Return a Map of (id => type)
word boundaryType (const word &name) const
Return BoundaryType corresponding to patch 'name'.
void readDict (const objectRegistry &, const word &name="boundaryRegion", const fileName &instance="constant")
Read constant/boundaryRegion.
void writeDict (const objectRegistry &, const word &name="boundaryRegion", const fileName &instance="constant") const
Write constant/boundaryRegion for later reuse.
void operator= (const boundaryRegion &)
Assignment.
void operator= (const Map< dictionary > &)
Assign from Map<dictionary>
void rename (const dictionary &)
Rename regions.
Public Member Functions inherited from Map< dictionary >
Map (const label size=128)
Construct given initial size.
Map (Istream &is)
Construct from Istream.
Map (const Map< dictionary > &map)
Construct as copy.
Map (const Xfer< Map< dictionary >> &map)
Construct by transferring the parameter contents.
Map (const Xfer< HashTable< dictionary, label, Hash< label >>> &map)
Construct by transferring the parameter contents.
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< T, Key, Hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< T, Key, Hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< Key, T >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const Key &) const
Return true if hashedEntry is found in table.
iterator find (const Key &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const Key &) const
Find and return an const_iterator set at the hashedEntry.
List< Key > toc () const
Return the table of contents.
List< Key > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const Key &, const T &newElmt)
Insert a new hashedEntry.
bool set (const Key &, const T &newElmt)
Assign a new hashedEntry, overwriting existing entries.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const Key &)
Erase a hashedEntry specified by the given key.
label erase (const UList< Key > &)
Remove entries given by the listed keys from this HashTable.
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< T, Key, Hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< T, Key, Hash > > xfer ()
Transfer contents to the Xfer container.
T & operator[] (const Key &)
Find and return a hashedEntry.
const T & operator[] (const Key &) const
Find and return a hashedEntry.
T & operator() (const Key &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< T, Key, Hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< Key, T >>)
Assignment to an initializer list.
bool operator== (const HashTable< T, Key, Hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< T, Key, Hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &rhs)
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Public Types inherited from Map< dictionary >
typedef HashTable< dictionary, label, Hash< label > >::iterator iterator
typedef HashTable< dictionary, label, Hash< label > >::const_iterator const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef T value_type
Type of values the HashTable contains.
typedef T & reference
Type that can be used for storing into HashTable::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Detailed Description
The boundaryRegion persistent data saved as a Map<dictionary>.
The meshReader supports boundaryRegion information.
The constant/boundaryRegion file is an IOMap<dictionary> that is used to save the information persistently. It contains the boundaryRegion information of the following form:
    (
        INT
        {
            BoundaryType    WORD;
            Label           WORD;
        }
        ...
    )
Source files
boundaryRegion.H
boundaryRegion.C
Definition at line 70 of file boundaryRegion.H.
Constructor & Destructor Documentation
boundaryRegion() [1/2]
boundaryRegion ()
Construct null.
Definition at line 33 of file boundaryRegion.C.
boundaryRegion() [2/2]
boundaryRegion (const objectRegistry & registry, const word & name = "boundaryRegion", const fileName & instance = "constant")
Construct read from registry, name. instance.
Definition at line 40 of file boundaryRegion.C.
References boundaryRegion::readDict().
~boundaryRegion()
~boundaryRegion ()
Destructor.
Definition at line 54 of file boundaryRegion.C.
Member Function Documentation
append()
Foam::label append (const dictionary & dict)
Append to the end, return index.
Definition at line 60 of file boundaryRegion.C.
References forAllConstIter(), and HashTable< T, Key, Hash >::insert().
findIndex()
Foam::label findIndex (const word & name) const
Return index corresponding to patch 'name'.
returns -1 if not found
Definition at line 139 of file boundaryRegion.C.
References forAllConstIter(), and word::null.
Referenced by boundaryRegion::boundaryType(), and boundaryRegion::rename().
names() [1/2]
Foam::Map< Foam::word > names () const
Return a Map of (id => name)
Definition at line 76 of file boundaryRegion.C.
References forAllConstIter(), HashTable< T, label, Hash< label > >::insert(), lookup(), and Foam::name().
names() [2/2]
Foam::Map< Foam::word > names (const UList< wordRe > & patterns) const
Return a Map of (id => names) selected by patterns.
Definition at line 98 of file boundaryRegion.C.
References Foam::findStrings(), forAllConstIter(), HashTable< T, label, Hash< label > >::insert(), lookup(), and Foam::name().
boundaryTypes()
Foam::Map< Foam::word > boundaryTypes () const
Return a Map of (id => type)
Definition at line 122 of file boundaryRegion.C.
References forAllConstIter(), HashTable< T, label, Hash< label > >::insert(), and lookup().
boundaryType()
Foam::word boundaryType (const word & name) const
Return BoundaryType corresponding to patch 'name'.
Definition at line 158 of file boundaryRegion.C.
References boundaryRegion::findIndex(), HashTable< T, Key, Hash >::operator[](), and boundaryRegion::readDict().
readDict()
void readDict (const objectRegistry & registry, const word & name = "boundaryRegion", const fileName & instance = "constant")
Read constant/boundaryRegion.
Definition at line 173 of file boundaryRegion.C.
References HashTable< T, Key, Hash >::clear(), Foam::endl(), IOobject::headerOk(), Foam::Info, IOobject::NO_WRITE, IOobject::READ_IF_PRESENT, and boundaryRegion::writeDict().
Referenced by boundaryRegion::boundaryRegion(), boundaryRegion::boundaryType(), STARCD::readAux(), and STARCD::STARCD().
writeDict()
void writeDict (const objectRegistry & registry, const word & name = "boundaryRegion", const fileName & instance = "constant") const
Write constant/boundaryRegion for later reuse.
Definition at line 207 of file boundaryRegion.C.
References Foam::endl(), Foam::Info, IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, IOobject::note(), IOobject::objectPath(), and IOobject::writeHeader().
Referenced by boundaryRegion::readDict().
operator=() [1/2]
void operator= (const boundaryRegion & rhs)
Assignment.
Definition at line 240 of file boundaryRegion.C.
References HashTable< T, label, Hash< label > >::operator=().
operator=() [2/2]
void operator= (const Map< dictionary > & rhs)
Assign from Map<dictionary>
Definition at line 246 of file boundaryRegion.C.
References HashTable< T, label, Hash< label > >::operator=().
rename()
void rename (const dictionary & mapDict)
Rename regions.
each dictionary entry is a single word:
    newPatchName    originalName;
Definition at line 254 of file boundaryRegion.C.
References dict, boundaryRegion::findIndex(), forAllConstIter(), Foam::Info, HashTable< T, label, Hash< label > >::insert(), dictionary::lookup(), Foam::nl, HashTable< T, Key, Hash >::operator[](), and dictionary::set().
The documentation for this class was generated from the following files:
src/conversion/meshTables/boundaryRegion.H
src/conversion/meshTables/boundaryRegion.C