OpenFOAM: STARCD Class Reference
STARCD Class Reference
Read pro-STAR vrt/cel/bnd files. The protected data in meshReader are filled.
Public Member Functions
STARCD (const fileName &prefix, const objectRegistry &, const scalar scaleFactor=1.0)
Construct from case name.
virtual ~STARCD ()
Destructor.
Public Member Functions inherited from meshReader
meshReader (const fileName &, const scalar scaleFactor=1.0)
Construct from fileName.
virtual ~meshReader ()
Destructor.
virtual autoPtr< polyMesh > mesh (const objectRegistry &)
Create and return polyMesh.
void writeAux (const objectRegistry &) const
Write auxiliary information.
void writeMesh (const polyMesh &, IOstream::streamFormat fmt=IOstream::BINARY) const
Write mesh.
Static Public Attributes
static bool keepSolids = false
Keep solids (default false)
Protected Types
enum cellType {
starcdFluidType = 1, starcdSolidType = 2, starcdBaffleType = 3, starcdShellType = 4,
starcdLineType = 5, starcdPointType = 6
}
enum shapeType {
starcdPoint = 1, starcdLine = 2, starcdShell = 3, starcdHex = 11,
starcdPrism = 12, starcdTet = 13, starcdPyr = 14, starcdPoly = 255
}
Protected Member Functions
virtual bool readGeometry (const scalar scaleFactor=1.0)
Read the mesh from the file(s)
void readPoints (const fileName &, const scalar scaleFactor)
Read points from file.
virtual void readCells (const fileName &)
Read cell connectivities from file.
void cullPoints ()
Remove unused points.
void readBoundary (const fileName &)
Read boundary (cell/face) definitions.
void readAux (const objectRegistry &)
Read auxiliary data from constant/{boundaryRegion,cellTable}.
Static Protected Member Functions
static void readToNewline (IFstream &)
Read and discard to newline.
static bool readHeader (IFstream &, word fileSignature)
Read header.
Protected Attributes
cellShapeList cellShapes_
Cell shapes.
labelList mapToFoamPointId_
Point labels (imported Point numbering not necessarily contiguous)
labelList mapToFoamCellId_
Cell labels (imported Cell numbering not necessarily contiguous)
boundaryRegion boundaryRegion_
Boundary region data.
Protected Attributes inherited from meshReader
fileName geometryFile_
Referenced filename.
scalar scaleFactor_
Geometry scaling.
pointField points_
Points supporting the mesh.
labelList origCellId_
Lookup original Cell number for a given cell.
List< List< cellFaceIdentifier > > boundaryIds_
Identify boundary faces by cells and their faces.
wordList patchTypes_
Boundary patch types.
wordList patchNames_
Boundary patch names.
wordList patchPhysicalTypes_
Boundary patch physical types.
faceListList cellFaces_
List of faces for every cell.
faceList baffleFaces_
List of each baffle face.
labelList cellTableId_
Cell table id for each cell.
cellTable cellTable_
Cell table persistent data saved as a dictionary.
Static Protected Attributes
static const char *const defaultBoundaryName
static const char *const defaultSolidBoundaryName
static const int starToFoamFaceAddr [4][6]
Face addressing from pro-STAR faces -> OpenFOAM faces.
Static Protected Attributes inherited from meshReader
static const cellModel * unknownModel
Pointers to cell shape models.
static const cellModel * tetModel
static const cellModel * pyrModel
static const cellModel * prismModel
static const cellModel * hexModel
Additional Inherited Members
Static Public Member Functions inherited from meshReader
static void warnDuplicates (const word &context, const wordList &)
Warn about repeated names.
Detailed Description
Read pro-STAR vrt/cel/bnd files. The protected data in meshReader are filled.
Starting with pro-STAR version 4, the files have become easier to read.
vertices are space-delimited.
the cell format is logical.
trimmed and degenerate cells are saved as polyhedral.
the boundaries corresponds to cells and their faces.
Source files
STARCDMeshReader.H
STARCDMeshReader.C
Definition at line 61 of file STARCDMeshReader.H.
Member Enumeration Documentation
cellType
enum cellType protected
Enumerator
starcdFluidType
starcdSolidType
starcdBaffleType
starcdShellType
starcdLineType
starcdPointType
Definition at line 129 of file STARCDMeshReader.H.
shapeType
enum shapeType protected
Enumerator
starcdPoint
starcdLine
starcdShell
starcdHex
starcdPrism
starcdTet
starcdPyr
starcdPoly
Definition at line 139 of file STARCDMeshReader.H.
Constructor & Destructor Documentation
STARCD()
STARCD (const fileName & prefix, const objectRegistry & registry, const scalar scaleFactor = 1.0)
Construct from case name.
Definition at line 1056 of file STARCDMeshReader.C.
References STARCD::readAux().
~STARCD()
~STARCD () virtual
Destructor.
Definition at line 1073 of file STARCDMeshReader.C.
Member Function Documentation
readGeometry()
bool readGeometry (const scalar scaleFactor = 1.0) protected virtual
Read the mesh from the file(s)
Implements meshReader.
Definition at line 1042 of file STARCDMeshReader.C.
References STARCD::cullPoints(), meshReader::geometryFile_, STARCD::readBoundary(), STARCD::readCells(), and STARCD::readPoints().
readPoints()
void readPoints (const fileName & inputName, const scalar scaleFactor) protected
Read points from file.
Original Point number for a given vertex
might need again in the future labelList origPointId(nPoints); origPointId = -1;
Definition at line 119 of file STARCDMeshReader.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::Info, STARCD::mapToFoamPointId_, Foam::max(), nPoints, meshReader::points_, STARCD::readHeader(), List< T >::setSize(), x, and y.
Referenced by STARCD::readAux(), and STARCD::readGeometry().
readCells()
void readCells (const fileName & inputName) protected virtual
Read cell connectivities from file.
Definition at line 244 of file STARCDMeshReader.C.
References Foam::abort(), meshReader::baffleFaces_, meshReader::cellFaces_, STARCD::cellShapes_, meshReader::cellTable_, meshReader::cellTableId_, List< T >::clear(), face::collapse(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::found(), meshReader::hexModel, Foam::Info, STARCD::keepSolids, STARCD::mapToFoamCellId_, STARCD::mapToFoamPointId_, Foam::max(), n, Foam::nl, meshReader::origCellId_, meshReader::prismModel, meshReader::pyrModel, STARCD::readHeader(), STARCD::readToNewline(), cellTable::setMaterial(), cellTable::setName(), List< T >::setSize(), List< T >::size(), STARCD::starcdBaffleType, STARCD::starcdFluidType, STARCD::starcdHex, STARCD::starcdPoly, STARCD::starcdPrism, STARCD::starcdPyr, STARCD::starcdShellType, STARCD::starcdSolidType, STARCD::starcdTet, meshReader::tetModel, and meshReader::unknownModel.
Referenced by STARCD::readGeometry().
cullPoints()
void cullPoints () protected
Remove unused points.
Definition at line 982 of file STARCDMeshReader.C.
References meshReader::baffleFaces_, meshReader::cellFaces_, Foam::endl(), forAll, Foam::Info, Foam::inplaceRenumber(), Foam::inplaceReorder(), nPoints, meshReader::points_, List< T >::setSize(), and List< T >::size().
Referenced by STARCD::readGeometry().
readBoundary()
void readBoundary (const fileName & inputName) protected
Read boundary (cell/face) definitions.
Definition at line 635 of file STARCDMeshReader.C.
References meshReader::boundaryIds_, STARCD::boundaryRegion_, cellId, STARCD::cellShapes_, List< T >::clear(), STARCD::defaultBoundaryName, HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, forAllIter, HashTable< T, Key, Hash >::found(), IOstream::good(), meshReader::hexModel, Foam::identity(), cellModel::index(), Foam::Info, Foam::inplaceReorder(), HashTable< T, Key, Hash >::insert(), STARCD::mapToFoamCellId_, Foam::max(), Foam::name(), nPatches, patchi, meshReader::patchNames_, meshReader::patchPhysicalTypes_, meshReader::patchTypes_, meshReader::prismModel, meshReader::pyrModel, STARCD::readHeader(), List< T >::setSize(), List< T >::size(), Foam::sortedOrder(), STARCD::starToFoamFaceAddr, and meshReader::tetModel.
Referenced by STARCD::readGeometry().
readAux()
void readAux (const objectRegistry & registry) protected
Read auxiliary data from constant/{boundaryRegion,cellTable}.
Definition at line 98 of file STARCDMeshReader.C.
References STARCD::boundaryRegion_, meshReader::cellTable_, boundaryRegion::readDict(), cellTable::readDict(), and STARCD::readPoints().
Referenced by STARCD::STARCD().
readToNewline()
void readToNewline (IFstream & is) static protected
Read and discard to newline.
Definition at line 57 of file STARCDMeshReader.C.
Referenced by STARCD::readCells(), and STARCD::readHeader().
readHeader()
bool readHeader (IFstream & is, word fileSignature) static protected
Read header.
Definition at line 68 of file STARCDMeshReader.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), Foam::Info, IFstream::name(), and STARCD::readToNewline().
Referenced by STARCD::readBoundary(), STARCD::readCells(), and STARCD::readPoints().
Member Data Documentation
defaultBoundaryName
const char *const defaultBoundaryName static protected
Initial value:
=
    "Default_Boundary_Region"
Definition at line 70 of file STARCDMeshReader.H.
Referenced by STARCD::readBoundary().
defaultSolidBoundaryName
const char *const defaultSolidBoundaryName static protected
Initial value:
=
    "Default_Boundary_Solid"
Definition at line 71 of file STARCDMeshReader.H.
starToFoamFaceAddr
const int starToFoamFaceAddr static protected
Initial value:
=
{
    { 4, 5, 2, 3, 0, 1 },
    { 0, 1, 4, -1, 2, 3 },
    { 3, -1, 2, -1, 1, 0 },
    { 0, -1, 4, 2, 1, 3 }
}
Face addressing from pro-STAR faces -> OpenFOAM faces.
Definition at line 74 of file STARCDMeshReader.H.
Referenced by STARCD::readBoundary().
cellShapes_
cellShapeList cellShapes_ protected
Cell shapes.
Definition at line 77 of file STARCDMeshReader.H.
Referenced by STARCD::readBoundary(), and STARCD::readCells().
mapToFoamPointId_
labelList mapToFoamPointId_ protected
Point labels (imported Point numbering not necessarily contiguous)
Definition at line 80 of file STARCDMeshReader.H.
Referenced by STARCD::readCells(), and STARCD::readPoints().
mapToFoamCellId_
labelList mapToFoamCellId_ protected
Cell labels (imported Cell numbering not necessarily contiguous)
Definition at line 83 of file STARCDMeshReader.H.
Referenced by STARCD::readBoundary(), and STARCD::readCells().
boundaryRegion_
boundaryRegion boundaryRegion_ protected
Boundary region data.
Definition at line 86 of file STARCDMeshReader.H.
Referenced by STARCD::readAux(), and STARCD::readBoundary().
keepSolids
bool keepSolids = false static
Keep solids (default false)
Definition at line 157 of file STARCDMeshReader.H.
Referenced by STARCD::readCells().
The documentation for this class was generated from the following files:
src/conversion/meshReader/starcd/STARCDMeshReader.H
src/conversion/meshReader/starcd/STARCDMeshReader.C