OpenFOAM: solidBodyMotionDisplacementPointPatchVectorField Class Reference
solidBodyMotionDisplacementPointPatchVectorField Class Reference
Enables the specification of a fixed value boundary condition using the solid body motion functions.
Public Member Functions
TypeName ("solidBodyMotionDisplacement")
Runtime type information.
solidBodyMotionDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
Construct from patch and internal field.
solidBodyMotionDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<vector> onto a new patch.
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField &)
Construct as copy.
virtual autoPtr< pointPatchField< vector > > clone () const
Construct and return a clone.
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField &, const DimensionedField< vector, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< vector > > clone (const DimensionedField< vector, pointMesh > &iF) const
Construct and return a clone setting internal field reference.
const solidBodyMotionFunction & motion () const
Return the fluctuation scale.
const pointField & localPoints0 () const
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Enables the specification of a fixed value boundary condition using the solid body motion functions.
Source files
solidBodyMotionDisplacementPointPatchVectorField.H
solidBodyMotionDisplacementPointPatchVectorField.C
Definition at line 50 of file solidBodyMotionDisplacementPointPatchVectorField.H.
Constructor & Destructor Documentation
solidBodyMotionDisplacementPointPatchVectorField() [1/5]
solidBodyMotionDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 40 of file solidBodyMotionDisplacementPointPatchVectorField.C.
Referenced by solidBodyMotionDisplacementPointPatchVectorField::clone(), and solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField().
solidBodyMotionDisplacementPointPatchVectorField() [2/5]
solidBodyMotionDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 52 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References dictionary::found(), solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField(), and Foam::transformPoints().
solidBodyMotionDisplacementPointPatchVectorField() [3/5]
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField & ptf, const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Construct by mapping given patchField<vector> onto a new patch.
Definition at line 75 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField(), and Foam::transformPoints().
solidBodyMotionDisplacementPointPatchVectorField() [4/5]
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField & ptf)
Construct as copy.
Definition at line 97 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField().
solidBodyMotionDisplacementPointPatchVectorField() [5/5]
solidBodyMotionDisplacementPointPatchVectorField (const solidBodyMotionDisplacementPointPatchVectorField & ptf, const DimensionedField< vector, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 108 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References Foam::transformPoints().
Member Function Documentation
TypeName()
TypeName ("solidBodyMotionDisplacement")
Runtime type information.
clone() [1/2]
virtual autoPtr<pointPatchField<vector> > clone () const inline virtual
Construct and return a clone.
Definition at line 101 of file solidBodyMotionDisplacementPointPatchVectorField.H.
References solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField().
clone() [2/2]
virtual autoPtr<pointPatchField<vector> > clone (const DimensionedField< vector, pointMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 122 of file solidBodyMotionDisplacementPointPatchVectorField.H.
References solidBodyMotionDisplacementPointPatchVectorField::solidBodyMotionDisplacementPointPatchVectorField().
motion()
const solidBodyMotionFunction& motion () const inline
Return the fluctuation scale.
Definition at line 142 of file solidBodyMotionDisplacementPointPatchVectorField.H.
References solidBodyMotionDisplacementPointPatchVectorField::localPoints0(), solidBodyMotionDisplacementPointPatchVectorField::updateCoeffs(), and solidBodyMotionDisplacementPointPatchVectorField::write().
localPoints0()
const pointField & localPoints0 () const
Definition at line 129 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References polyMesh::meshSubDir, IOobject::MUST_READ, and IOobject::NO_WRITE.
Referenced by solidBodyMotionDisplacementPointPatchVectorField::motion(), and solidBodyMotionDisplacementPointPatchVectorField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 153 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References solidBodyMotionDisplacementPointPatchVectorField::localPoints0(), Foam::transformPoints(), and solidBodyMotionDisplacementPointPatchVectorField::write().
Referenced by solidBodyMotionDisplacementPointPatchVectorField::motion().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 172 of file solidBodyMotionDisplacementPointPatchVectorField.C.
References token::END_STATEMENT, Foam::indent(), Foam::makePointPatchTypeField(), Foam::nl, write(), and Ostream::writeKeyword().
Referenced by solidBodyMotionDisplacementPointPatchVectorField::motion(), and solidBodyMotionDisplacementPointPatchVectorField::updateCoeffs().
The documentation for this class was generated from the following files:
src/dynamicFvMesh/solidBodyMotionFvMesh/pointPatchFields/derived/solidBodyMotionDisplacement/solidBodyMotionDisplacementPointPatchVectorField.H
src/dynamicFvMesh/solidBodyMotionFvMesh/pointPatchFields/derived/solidBodyMotionDisplacement/solidBodyMotionDisplacementPointPatchVectorField.C