OpenFOAM: minEqOp< labelPair > Class Template Reference
minEqOp< labelPair > Class Template Reference
Public Member Functions
void operator() (labelPair &x, const labelPair &y) const
void operator() (labelPair &x, const labelPair &y) const
Detailed Description
template<>
class Foam::minEqOp< labelPair >
Definition at line 48 of file createShellMesh.C.
Member Function Documentation
operator()() [1/2]
void operator() (labelPair & x, const labelPair & y) const inline
Definition at line 51 of file createShellMesh.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), createShellMesh::calcPointRegions(), mapDistributeBase::constructSize(), forAll, globalMeshData::globalEdgeOrientation(), globalMeshData::globalEdgeSlaves(), globalMeshData::globalEdgeSlavesMap(), globalMeshData::globalEdgeTransformedSlaves(), Foam::labelMax, Foam::min(), List< T >::size(), and globalMeshData::syncData().
operator()() [2/2]
void operator() (labelPair & x, const labelPair & y) const inline
Definition at line 49 of file globalMeshData.C.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), UPstream::blocking, List< T >::clear(), HashTable< T, Key, Hash >::clear(), Pair< Type >::compare(), mapDistributeBase::constructSize(), polyPatch::coupled(), Foam::e, globalIndexAndTransform::encode(), HashTableCore::end(), Foam::endl(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), Foam::findIndex(), PstreamBuffers::finishedSends(), UPstream::firstSlave(), forAll, forAllConstIter(), globalIndexAndTransform::index(), HashTable< T, Key, Hash >::insert(), Foam::labelMax, UPstream::lastSlave(), globalIndex::localSize(), globalPoints::map(), UPstream::master(), UPstream::masterNo(), Foam::min(), UPstream::myProcNo(), n, Foam::name(), Foam::nl, UPstream::nonBlocking, nPoints, UPstream::nProcs(), globalIndexAndTransform::nullTransformIndex(), UPstream::parRun(), patchi, globalPoints::pointPoints(), Foam::Pout, globalIndexAndTransform::processor(), mapDistribute::reverseDistribute(), List< T >::setSize(), List< T >::size(), globalIndex::size(), HashTable< T, Key, Hash >::size(), HashTable< T, edge, Hash< edge > >::size(), Foam::sort(), polyPatch::start(), globalIndexAndTransform::subtractTransformIndex(), globalIndex::toGlobal(), globalIndex::toLocal(), List< T >::transfer(), Foam::transform(), globalPoints::transformedPointPoints(), globalIndexAndTransform::transformIndex(), globalIndex::whichProcID(), List< T >::xfer(), and mapDistribute::xfer().
The documentation for this class was generated from the following files:
src/dynamicMesh/createShellMesh/createShellMesh.C
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalMeshData.C