OpenFOAM: boundaryMesh Class Reference
boundaryMesh Class Reference
Addressing for all faces on surface of mesh. Can either be read from polyMesh or from triSurface. Used for repatching existing meshes.
Public Member Functions
ClassName ("boundaryMesh")
Runtime type information.
boundaryMesh ()
Construct null.
~boundaryMesh ()
Destructor.
void clearOut ()
const bMesh & mesh () const
const PtrList< boundaryPatch > & patches () const
const labelList & meshFace () const
Label of original face in polyMesh (before patchify(...))
const pointField & featurePoints () const
Feature points.
const edgeList & featureEdges () const
Feature edges. Indices into featurePoints.
const labelList & featureToEdge () const
From index into featureEdge to index into meshedges,.
const labelList & edgeToFeature () const
From edge into featureEdges.
const labelListList & featureSegments () const
Lists of connected featureEdges. Indices into featureEdges.
const labelList & extraEdges () const
Indices into edges of additional edges.
void read (const polyMesh &)
Read from boundaryMesh of polyMesh.
void readTriSurface (const fileName &)
Read from triSurface.
void writeTriSurface (const fileName &) const
Write to file.
labelList getNearest (const primitiveMesh &pMesh, const vector &searchSpan) const
Get bMesh index of nearest face for every boundary face in.
void patchify (const labelList &nearest, const polyBoundaryMesh &oldPatches, polyMesh &newMesh) const
Take over patches onto polyMesh from nearest face in *this.
label whichPatch (const label facei) const
Get index of patch face is in.
label findPatchID (const word &patchName) const
Get index of patch by name.
wordList patchNames () const
Get names of patches.
void addPatch (const word &patchName)
Add to back of patch list.
void deletePatch (const word &patchName)
Delete from patch list.
void changePatchType (const word &patchName, const word &type)
Change patch.
void changeFaces (const labelList &patchIDs, labelList &oldToNew)
Recalculate face ordering and patches. Return old to new.
void setFeatureEdges (const scalar minCos)
Set featureEdges, edgeToFeature, featureSegments according.
void setExtraEdges (const label edgeI)
Set extraEdges to edges 'near' to edgeI. Uses point-edge walk.
label getNTris (const label facei) const
Simple triangulation of face subset. Returns number of triangles.
label getNTris (const label startFacei, const label nFaces, labelList &nTris) const
Simple triangulation of face subset. TotalNTris is total number.
void triangulate (const label startFacei, const label nFaces, const label totalNTris, labelList &triVerts) const
Simple triangulation of face subset. TotalNTris is total number.
label getNPoints (const label startFacei, const label nFaces) const
Number of points used in face subset.
void triangulateLocal (const label startFacei, const label nFaces, const label totalNTris, labelList &triVerts, labelList &localToGlobal) const
Same as triangulate but in local vertex numbering.
void markFaces (const labelList &protectedEdges, const label facei, boolList &visited) const
Detailed Description
Addressing for all faces on surface of mesh. Can either be read from polyMesh or from triSurface. Used for repatching existing meshes.
Source files
boundaryMesh.H
boundaryMesh.C
Definition at line 59 of file boundaryMesh.H.
Constructor & Destructor Documentation
boundaryMesh()
boundaryMesh ()
Construct null.
Definition at line 437 of file boundaryMesh.C.
~boundaryMesh()
~boundaryMesh ()
Destructor.
Definition at line 453 of file boundaryMesh.C.
References boundaryMesh::clearOut().
Member Function Documentation
ClassName()
ClassName ("boundaryMesh")
Runtime type information.
clearOut()
void clearOut ()
Definition at line 459 of file boundaryMesh.C.
Referenced by boundaryMesh::changeFaces(), boundaryMesh::read(), boundaryMesh::readTriSurface(), and boundaryMesh::~boundaryMesh().
mesh()
const bMesh& mesh () const inline
Definition at line 202 of file boundaryMesh.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by boundaryMesh::addPatch(), boundaryMesh::changeFaces(), boundaryMesh::getNearest(), boundaryMesh::getNPoints(), boundaryMesh::getNTris(), fvPatch::lookupPatchField(), boundaryMesh::markFaces(), cyclicACMIPolyPatch::resetAMI(), cyclicAMIPolyPatch::resetAMI(), boundaryMesh::setExtraEdges(), boundaryMesh::setFeatureEdges(), cyclicAMIPolyPatch::surfPtr(), boundaryMesh::triangulate(), boundaryMesh::triangulateLocal(), and boundaryMesh::writeTriSurface().
patches()
const PtrList<boundaryPatch>& patches () const inline
Definition at line 213 of file boundaryMesh.H.
meshFace()
const labelList& meshFace () const inline
Label of original face in polyMesh (before patchify(...))
Definition at line 220 of file boundaryMesh.H.
featurePoints()
const pointField& featurePoints () const inline
Feature points.
Definition at line 226 of file boundaryMesh.H.
featureEdges()
const edgeList& featureEdges () const inline
Feature edges. Indices into featurePoints.
Definition at line 232 of file boundaryMesh.H.
featureToEdge()
const labelList& featureToEdge () const inline
From index into featureEdge to index into meshedges,.
Definition at line 238 of file boundaryMesh.H.
edgeToFeature()
const labelList& edgeToFeature () const inline
From edge into featureEdges.
Definition at line 244 of file boundaryMesh.H.
featureSegments()
const labelListList& featureSegments () const inline
Lists of connected featureEdges. Indices into featureEdges.
Definition at line 250 of file boundaryMesh.H.
extraEdges()
const labelList& extraEdges () const inline
Indices into edges of additional edges.
Definition at line 256 of file boundaryMesh.H.
References boundaryMesh::addPatch(), boundaryMesh::changeFaces(), boundaryMesh::changePatchType(), boundaryMesh::deletePatch(), boundaryMesh::getNearest(), boundaryMesh::getNPoints(), boundaryMesh::getNTris(), boundaryMesh::markFaces(), boundaryMesh::patchify(), boundaryMesh::patchNames(), boundaryMesh::read(), boundaryMesh::readTriSurface(), boundaryMesh::setExtraEdges(), boundaryMesh::setFeatureEdges(), boundaryMesh::triangulate(), boundaryMesh::triangulateLocal(), Foam::type(), and boundaryMesh::writeTriSurface().
read()
void read (const polyMesh & mesh)
Read from boundaryMesh of polyMesh.
Definition at line 472 of file boundaryMesh.C.
References polyMesh::boundaryMesh(), boundaryMesh::clearOut(), Foam::endl(), f(), forAll, patchIdentifier::name(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, patchIdentifier::physicalType(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), polyMesh::points(), Foam::Pout, List< T >::setSize(), boundaryPatch::size(), List< T >::size(), UPtrList< T >::size(), boundaryPatch::start(), polyPatch::start(), and Foam::Zero.
Referenced by boundaryMesh::extraEdges().
readTriSurface()
void readTriSurface (const fileName & fName)
Read from triSurface.
Definition at line 602 of file boundaryMesh.C.
References boundaryMesh::clearOut(), UList< T >::empty(), Foam::endl(), forAll, geometricSurfacePatch::geometricType(), HashTable< T, Key, Hash >::insert(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), geometricSurfacePatch::name(), Foam::name(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), triSurface::patches(), patchi, Foam::Pout, labelledTri::region(), List< T >::setSize(), boundaryPatch::size(), List< T >::size(), HashTable< T, Key, Hash >::size(), and boundaryPatch::start().
Referenced by boundaryMesh::extraEdges().
writeTriSurface()
void writeTriSurface (const fileName & fName) const
Write to file.
Definition at line 771 of file boundaryMesh.C.
References forAll, boundaryMesh::getNearest(), boundaryMesh::getNTris(), boundaryMesh::mesh(), patchIdentifier::name(), patchi, patchIdentifier::physicalType(), points, boundaryPatch::start(), and boundaryMesh::triangulate().
Referenced by boundaryMesh::extraEdges().
getNearest()
Foam::labelList getNearest (const primitiveMesh & pMesh, const vector & searchSpan) const
Get bMesh index of nearest face for every boundary face in.
pMesh. Gets passed initial search box. If not found returns -1 for the face.
Definition at line 861 of file boundaryMesh.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), boundBox::avgDim(), Foam::endl(), f(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), primitiveMesh::faces(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), Foam::mag(), Foam::magSqr(), boundBox::max(), Foam::max(), boundaryMesh::mesh(), boundBox::min(), n, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), boundaryMesh::patchify(), points, primitiveMesh::points(), Foam::Pout, DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), Foam::sign(), List< T >::size(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by boundaryMesh::extraEdges(), and boundaryMesh::writeTriSurface().
patchify()
void patchify (const labelList & nearest, const polyBoundaryMesh & oldPatches, polyMesh & newMesh) const
Take over patches onto polyMesh from nearest face in *this.
(from call to getNearest). Insert as -new set of patches (newMesh.addPatches) -topoChanges to change faces. nearest is list of nearest face in *this for every boundary face. oldPatches is list of existing patches in mesh. newMesh is the mesh to which the new patches are added. (so has to be constructed without patches).
Definition at line 1116 of file boundaryMesh.C.
References List< T >::append(), polyMesh::boundaryMesh(), repatchPolyTopoChanger::changePatches(), repatchPolyTopoChanger::changePatchID(), polyPatch::clone(), Foam::endl(), forAll, patchIdentifier::name(), polyPatch::New(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, pFaces, patchIdentifier::physicalType(), Foam::Pout, repatchPolyTopoChanger::repatch(), List< T >::size(), and polyPatch::start().
Referenced by boundaryMesh::extraEdges(), and boundaryMesh::getNearest().
whichPatch()
Foam::label whichPatch (const label facei) const
Get index of patch face is in.
Definition at line 1535 of file boundaryMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, patchi, boundaryPatch::size(), and boundaryPatch::start().
findPatchID()
Foam::label findPatchID (const word & patchName) const
Get index of patch by name.
Definition at line 1556 of file boundaryMesh.C.
References forAll, Foam::name(), and patchi.
patchNames()
Foam::wordList patchNames () const
Get names of patches.
Definition at line 271 of file boundaryMesh.C.
References primitiveMesh::edgeFaces(), UList< T >::empty(), Foam::endl(), primitiveMesh::faceEdges(), forAll, mesh, patchi, Foam::Pout, List< T >::setSize(), List< T >::size(), and polyPatch::start().
Referenced by boundaryMesh::extraEdges().
addPatch()
void addPatch (const word & patchName)
Add to back of patch list.
Definition at line 1570 of file boundaryMesh.C.
References Foam::endl(), forAll, boundaryMesh::mesh(), patchIdentifier::name(), patchi, patchIdentifier::physicalType(), Foam::Pout, boundaryPatch::size(), and boundaryPatch::start().
Referenced by boundaryMesh::extraEdges().
deletePatch()
void deletePatch (const word & patchName)
Delete from patch list.
Definition at line 1607 of file boundaryMesh.C.
References Foam::abort(), boundaryMesh::changePatchType(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, patchIdentifier::name(), patchi, patchIdentifier::physicalType(), Foam::Pout, PtrList< T >::set(), boundaryPatch::size(), and boundaryPatch::start().
Referenced by boundaryMesh::extraEdges().
changePatchType()
void changePatchType (const word & patchName, const word & type)
Change patch.
Definition at line 1663 of file boundaryMesh.C.
References Foam::abort(), boundaryMesh::changeFaces(), Foam::FatalError, FatalErrorInFunction, forAll, patchIdentifier::index(), patchIdentifier::name(), patchi, boundaryPatch::size(), and boundaryPatch::start().
Referenced by boundaryMesh::deletePatch(), and boundaryMesh::extraEdges().
changeFaces()
void changeFaces (const labelList & patchIDs, labelList & oldToNew)
Recalculate face ordering and patches. Return old to new.
mapping.
Definition at line 1714 of file boundaryMesh.C.
References Foam::abort(), boundaryMesh::clearOut(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, boundaryMesh::mesh(), patchIdentifier::name(), patchi, patchIdentifier::physicalType(), points, Foam::Pout, List< T >::setSize(), boundaryPatch::size(), List< T >::size(), boundaryPatch::start(), and List< T >::transfer().
Referenced by boundaryMesh::changePatchType(), and boundaryMesh::extraEdges().
setFeatureEdges()
void setFeatureEdges (const scalar minCos)
Set featureEdges, edgeToFeature, featureSegments according.
to angle of faces across edge
Definition at line 1319 of file boundaryMesh.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), forAll, boundaryMesh::mesh(), nPoints, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), List< T >::setSize(), List< T >::size(), and edge::start().
Referenced by boundaryMesh::extraEdges().
setExtraEdges()
void setExtraEdges (const label edgeI)
Set extraEdges to edges 'near' to edgeI. Uses point-edge walk.
to determine 'near'.
Definition at line 1520 of file boundaryMesh.C.
References boundaryMesh::mesh(), and List< T >::transfer().
Referenced by boundaryMesh::extraEdges().
getNTris() [1/2]
Foam::label getNTris (const label facei) const
Simple triangulation of face subset. Returns number of triangles.
needed.
Definition at line 1832 of file boundaryMesh.C.
References f(), boundaryMesh::mesh(), face::nTriangles(), and points.
Referenced by boundaryMesh::extraEdges(), boundaryMesh::getNTris(), and boundaryMesh::writeTriSurface().
getNTris() [2/2]
Foam::label getNTris (const label startFacei, const label nFaces, labelList & nTris) const
Simple triangulation of face subset. TotalNTris is total number.
of triangles, nTris is per face number of triangles.
Definition at line 1841 of file boundaryMesh.C.
References boundaryMesh::getNTris(), List< T >::setSize(), and boundaryMesh::triangulate().
triangulate()
void triangulate (const label startFacei, const label nFaces, const label totalNTris, labelList & triVerts) const
Simple triangulation of face subset. TotalNTris is total number.
of triangles (from call to getNTris) triVerts is triangle vertices, three per triangle.
Definition at line 1866 of file boundaryMesh.C.
References f(), forAll, boundaryMesh::getNPoints(), boundaryMesh::mesh(), face::nTriangles(), points, List< T >::setSize(), and face::triangles().
Referenced by boundaryMesh::extraEdges(), boundaryMesh::getNTris(), and boundaryMesh::writeTriSurface().
getNPoints()
Foam::label getNPoints (const label startFacei, const label nFaces) const
Number of points used in face subset.
Definition at line 1907 of file boundaryMesh.C.
References boundaryMesh::mesh(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), points, and boundaryMesh::triangulateLocal().
Referenced by boundaryMesh::extraEdges(), and boundaryMesh::triangulate().
triangulateLocal()
void triangulateLocal (const label startFacei, const label nFaces, const label totalNTris, labelList & triVerts, labelList & localToGlobal) const
Same as triangulate but in local vertex numbering.
(Map returned).
Definition at line 1922 of file boundaryMesh.C.
References f(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), boundaryMesh::markFaces(), boundaryMesh::mesh(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), face::nTriangles(), points, List< T >::setSize(), and face::triangles().
Referenced by boundaryMesh::extraEdges(), and boundaryMesh::getNPoints().
markFaces()
void markFaces (const labelList & protectedEdges, const label facei, boolList & visited) const
Definition at line 1969 of file boundaryMesh.C.
References forAll, boundaryMesh::mesh(), and List< T >::setSize().
Referenced by boundaryMesh::extraEdges(), and boundaryMesh::triangulateLocal().
The documentation for this class was generated from the following files:
src/dynamicMesh/boundaryMesh/boundaryMesh.H
src/dynamicMesh/boundaryMesh/boundaryMesh.C