OpenFOAM: multiMotion Class Reference
multiMotion Class Reference
Combination of SolidBodyMotionFvMesh 6DoF motion functions.
Public Member Functions
TypeName ("multiMotion")
Runtime type information.
multiMotion (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from components.
virtual autoPtr< solidBodyMotionFunction > clone () const
Construct and return a clone.
virtual ~multiMotion ()
Destructor.
virtual septernion transformation () const
Return the solid-body motion transformation septernion.
virtual bool read (const dictionary &SBMFCoeffs)
Update properties from given dictionary.
Public Member Functions inherited from solidBodyMotionFunction
TypeName ("solidBodyMotionFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidBodyMotionFunction, dictionary,(const dictionary &SBMFCoeffs, const Time &runTime),(SBMFCoeffs, runTime))
solidBodyMotionFunction (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from the SBMFCoeffs dictionary and Time.
virtual ~solidBodyMotionFunction ()
Destructor.
virtual void writeData (Ostream &) const
Write in dictionary format.
Additional Inherited Members
Static Public Member Functions inherited from solidBodyMotionFunction
static autoPtr< solidBodyMotionFunction > New (const dictionary &SBMFCoeffs, const Time &runTime)
Select constructed from the SBMFCoeffs dictionary and Time.
Protected Attributes inherited from solidBodyMotionFunction
dictionary SBMFCoeffs_
const Time & time_
Detailed Description
Combination of SolidBodyMotionFvMesh 6DoF motion functions.
Source files
multiMotion.H
multiMotion.C
Definition at line 52 of file multiMotion.H.
Constructor & Destructor Documentation
multiMotion()
multiMotion (const dictionary & SBMFCoeffs, const Time & runTime)
Construct from components.
Definition at line 49 of file multiMotion.C.
References Foam::read().
~multiMotion()
~multiMotion () virtual
Destructor.
Definition at line 62 of file multiMotion.C.
Referenced by multiMotion::clone().
Member Function Documentation
TypeName()
TypeName ("multiMotion")
Runtime type information.
clone()
virtual autoPtr<solidBodyMotionFunction> clone () const inline virtual
Construct and return a clone.
Implements solidBodyMotionFunction.
Definition at line 87 of file multiMotion.H.
References multiMotion::read(), solidBodyMotionFunction::SBMFCoeffs_, solidBodyMotionFunction::time_, multiMotion::transformation(), and multiMotion::~multiMotion().
transformation()
Foam::septernion transformation () const virtual
Return the solid-body motion transformation septernion.
Implements solidBodyMotionFunction.
Definition at line 69 of file multiMotion.C.
References DebugInFunction, Foam::endl(), and multiMotion::read().
Referenced by multiMotion::clone().
read()
bool read (const dictionary & SBMFCoeffs) virtual
Update properties from given dictionary.
Implements solidBodyMotionFunction.
Definition at line 87 of file multiMotion.C.
References dict, Foam::endl(), forAllConstIter(), Foam::Info, solidBodyMotionFunction::New(), and solidBodyMotionFunction::read().
Referenced by multiMotion::clone(), and multiMotion::transformation().
The documentation for this class was generated from the following files:
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/multiMotion/multiMotion.H
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/multiMotion/multiMotion.C