OpenFOAM: linearMotion Class Reference
linearMotion Class Reference
SolidBodyMotionFvMesh 6DoF motion function. Constant velocity displacement.
Public Member Functions
TypeName ("linearMotion")
Runtime type information.
linearMotion (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from components.
virtual autoPtr< solidBodyMotionFunction > clone () const
Construct and return a clone.
virtual ~linearMotion ()
Destructor.
virtual septernion transformation () const
Return the solid-body motion transformation septernion.
virtual bool read (const dictionary &SBMFCoeffs)
Update properties from given dictionary.
Public Member Functions inherited from solidBodyMotionFunction
TypeName ("solidBodyMotionFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidBodyMotionFunction, dictionary,(const dictionary &SBMFCoeffs, const Time &runTime),(SBMFCoeffs, runTime))
solidBodyMotionFunction (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from the SBMFCoeffs dictionary and Time.
virtual ~solidBodyMotionFunction ()
Destructor.
virtual void writeData (Ostream &) const
Write in dictionary format.
Additional Inherited Members
Static Public Member Functions inherited from solidBodyMotionFunction
static autoPtr< solidBodyMotionFunction > New (const dictionary &SBMFCoeffs, const Time &runTime)
Select constructed from the SBMFCoeffs dictionary and Time.
Protected Attributes inherited from solidBodyMotionFunction
dictionary SBMFCoeffs_
const Time & time_
Detailed Description
SolidBodyMotionFvMesh 6DoF motion function. Constant velocity displacement.
Source files
linearMotion.H
linearMotion.C
Definition at line 52 of file linearMotion.H.
Constructor & Destructor Documentation
linearMotion()
linearMotion (const dictionary & SBMFCoeffs, const Time & runTime)
Construct from components.
Definition at line 49 of file linearMotion.C.
References Foam::read().
~linearMotion()
~linearMotion () virtual
Destructor.
Definition at line 62 of file linearMotion.C.
Referenced by linearMotion::clone().
Member Function Documentation
TypeName()
TypeName ("linearMotion")
Runtime type information.
clone()
virtual autoPtr<solidBodyMotionFunction> clone () const inline virtual
Construct and return a clone.
Implements solidBodyMotionFunction.
Definition at line 87 of file linearMotion.H.
References linearMotion::read(), solidBodyMotionFunction::SBMFCoeffs_, solidBodyMotionFunction::time_, linearMotion::transformation(), and linearMotion::~linearMotion().
transformation()
Foam::septernion transformation () const virtual
Return the solid-body motion transformation septernion.
Implements solidBodyMotionFunction.
Definition at line 69 of file linearMotion.C.
References DebugInFunction, Foam::endl(), R, and linearMotion::read().
Referenced by linearMotion::clone().
read()
bool read (const dictionary & SBMFCoeffs) virtual
Update properties from given dictionary.
Implements solidBodyMotionFunction.
Definition at line 86 of file linearMotion.C.
References solidBodyMotionFunction::read().
Referenced by linearMotion::clone(), and linearMotion::transformation().
The documentation for this class was generated from the following files:
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/linearMotion/linearMotion.H
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/linearMotion/linearMotion.C