OpenFOAM: lessProcPatches Class Reference
lessProcPatches Class Reference
Less function class that can be used for sorting processor patches.
Public Member Functions
lessProcPatches (const labelList &nbrProc, const labelList &referPatchID)
bool operator() (const label a, const label b)
Detailed Description
Less function class that can be used for sorting processor patches.
Definition at line 52 of file fvMeshDistribute.C.
Constructor & Destructor Documentation
lessProcPatches()
lessProcPatches (const labelList & nbrProc, const labelList & referPatchID) inline
Definition at line 59 of file fvMeshDistribute.C.
Referenced by fvMeshDistribute::printCoupleInfo().
Member Function Documentation
operator()()
bool operator() (const label a, const label b) inline
Definition at line 65 of file fvMeshDistribute.C.
References Foam::constant::physicoChemical::b, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Pstream::gatherList(), Foam::inplaceRenumber(), HashSet< Key, Hash >::insert(), UPstream::myProcNo(), n, UPstream::nProcs(), Pstream::scatterList(), Foam::sign(), UList< T >::size(), and HashTable< nil, Key, Hash >::toc().
The documentation for this class was generated from the following file:
src/dynamicMesh/fvMeshDistribute/fvMeshDistribute.C