OpenFOAM: tabulated6DoFMotion Class Reference
tabulated6DoFMotion Class Reference
Tabulated 6DoF motion function.
Public Member Functions
TypeName ("tabulated6DoFMotion")
Runtime type information.
tabulated6DoFMotion (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from components.
virtual autoPtr< solidBodyMotionFunction > clone () const
Construct and return a clone.
virtual ~tabulated6DoFMotion ()
Destructor.
virtual septernion transformation () const
Return the solid-body motion transformation septernion.
virtual bool read (const dictionary &SBMFCoeffs)
Update properties from given dictionary.
Public Member Functions inherited from solidBodyMotionFunction
TypeName ("solidBodyMotionFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidBodyMotionFunction, dictionary,(const dictionary &SBMFCoeffs, const Time &runTime),(SBMFCoeffs, runTime))
solidBodyMotionFunction (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from the SBMFCoeffs dictionary and Time.
virtual ~solidBodyMotionFunction ()
Destructor.
virtual void writeData (Ostream &) const
Write in dictionary format.
Additional Inherited Members
Static Public Member Functions inherited from solidBodyMotionFunction
static autoPtr< solidBodyMotionFunction > New (const dictionary &SBMFCoeffs, const Time &runTime)
Select constructed from the SBMFCoeffs dictionary and Time.
Protected Attributes inherited from solidBodyMotionFunction
dictionary SBMFCoeffs_
const Time & time_
Detailed Description
Tabulated 6DoF motion function.
Obtained by interpolating tabulated data for surge (x-translation), sway (y-translation), heave (z-translation), roll (rotation about x), pitch (rotation about y) and yaw (rotation about z).
Source files
tabulated6DoFMotion.H
tabulated6DoFMotion.C
Definition at line 56 of file tabulated6DoFMotion.H.
Constructor & Destructor Documentation
tabulated6DoFMotion()
tabulated6DoFMotion (const dictionary & SBMFCoeffs, const Time & runTime)
Construct from components.
Definition at line 55 of file tabulated6DoFMotion.C.
References Foam::read().
~tabulated6DoFMotion()
~tabulated6DoFMotion () virtual
Destructor.
Definition at line 68 of file tabulated6DoFMotion.C.
Referenced by tabulated6DoFMotion::clone().
Member Function Documentation
TypeName()
TypeName ("tabulated6DoFMotion")
Runtime type information.
clone()
virtual autoPtr<solidBodyMotionFunction> clone () const inline virtual
Construct and return a clone.
Implements solidBodyMotionFunction.
Definition at line 103 of file tabulated6DoFMotion.H.
References tabulated6DoFMotion::read(), solidBodyMotionFunction::SBMFCoeffs_, solidBodyMotionFunction::time_, tabulated6DoFMotion::transformation(), and tabulated6DoFMotion::~tabulated6DoFMotion().
transformation()
Foam::septernion transformation () const virtual
Return the solid-body motion transformation septernion.
Implements solidBodyMotionFunction.
Definition at line 75 of file tabulated6DoFMotion.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::interpolateSplineXY(), Foam::constant::mathematical::pi(), R, tabulated6DoFMotion::read(), and quaternion::XYZ.
Referenced by tabulated6DoFMotion::clone().
read()
bool read (const dictionary & SBMFCoeffs) virtual
Update properties from given dictionary.
Implements solidBodyMotionFunction.
Definition at line 117 of file tabulated6DoFMotion.C.
References Foam::exit(), Foam::stringOps::expand(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), forAll, IOstream::good(), solidBodyMotionFunction::read(), and List< T >::size().
Referenced by tabulated6DoFMotion::clone(), and tabulated6DoFMotion::transformation().
The documentation for this class was generated from the following files:
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/tabulated6DoFMotion/tabulated6DoFMotion.H
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/tabulated6DoFMotion/tabulated6DoFMotion.C