OpenFOAM: solidBodyMotionFunction Class Reference
solidBodyMotionFunction Class Reference abstract
Base class for defining solid-body motions.
Public Member Functions
TypeName ("solidBodyMotionFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidBodyMotionFunction, dictionary,(const dictionary &SBMFCoeffs, const Time &runTime),(SBMFCoeffs, runTime))
solidBodyMotionFunction (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from the SBMFCoeffs dictionary and Time.
virtual autoPtr< solidBodyMotionFunction > clone () const =0
Construct and return a clone.
virtual ~solidBodyMotionFunction ()
Destructor.
virtual septernion transformation () const =0
Return the solid-body motion transformation septernion.
virtual bool read (const dictionary &SBMFCoeffs)=0
Update properties from given dictionary.
virtual void writeData (Ostream &) const
Write in dictionary format.
Static Public Member Functions
static autoPtr< solidBodyMotionFunction > New (const dictionary &SBMFCoeffs, const Time &runTime)
Select constructed from the SBMFCoeffs dictionary and Time.
Protected Attributes
dictionary SBMFCoeffs_
const Time & time_
Detailed Description
Base class for defining solid-body motions.
Source files
solidBodyMotionFunction.H
solidBodyMotionFunction.C
dynamicFvMeshNew.C
Definition at line 60 of file solidBodyMotionFunction.H.
Constructor & Destructor Documentation
solidBodyMotionFunction()
solidBodyMotionFunction (const dictionary & SBMFCoeffs, const Time & runTime)
Construct from the SBMFCoeffs dictionary and Time.
Definition at line 40 of file solidBodyMotionFunction.C.
~solidBodyMotionFunction()
~solidBodyMotionFunction () virtual
Destructor.
Definition at line 58 of file solidBodyMotionFunction.C.
Member Function Documentation
TypeName()
TypeName ("solidBodyMotionFunction")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , solidBodyMotionFunction , dictionary , (const dictionary &SBMFCoeffs, const Time &runTime) , (SBMFCoeffs, runTime))
clone()
virtual autoPtr<solidBodyMotionFunction> clone () const pure virtual
Construct and return a clone.
Implemented in SDA, tabulated6DoFMotion, rotatingMotion, oscillatingRotatingMotion, axisRotationMotion, oscillatingLinearMotion, linearMotion, and multiMotion.
New()
Foam::autoPtr< Foam::solidBodyMotionFunction > New (const dictionary & SBMFCoeffs, const Time & runTime) static
Select constructed from the SBMFCoeffs dictionary and Time.
Definition at line 31 of file solidBodyMotionFunctionNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
Referenced by multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), and multiMotion::read().
transformation()
virtual septernion transformation () const pure virtual
Return the solid-body motion transformation septernion.
Implemented in SDA, tabulated6DoFMotion, rotatingMotion, oscillatingRotatingMotion, axisRotationMotion, oscillatingLinearMotion, linearMotion, and multiMotion.
read()
bool read (const dictionary & SBMFCoeffs) pure virtual
Update properties from given dictionary.
Implemented in SDA, tabulated6DoFMotion, rotatingMotion, oscillatingRotatingMotion, axisRotationMotion, oscillatingLinearMotion, linearMotion, and multiMotion.
Definition at line 64 of file solidBodyMotionFunction.C.
References dictionary::subDict(), and Foam::type().
Referenced by linearMotion::read(), multiMotion::read(), oscillatingLinearMotion::read(), axisRotationMotion::read(), oscillatingRotatingMotion::read(), rotatingMotion::read(), tabulated6DoFMotion::read(), and SDA::read().
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Definition at line 72 of file solidBodyMotionFunction.C.
Member Data Documentation
SBMFCoeffs_
dictionary SBMFCoeffs_ protected
Definition at line 66 of file solidBodyMotionFunction.H.
Referenced by linearMotion::clone(), multiMotion::clone(), oscillatingLinearMotion::clone(), axisRotationMotion::clone(), oscillatingRotatingMotion::clone(), rotatingMotion::clone(), tabulated6DoFMotion::clone(), and SDA::clone().
time_
const Time& time_ protected
Definition at line 67 of file solidBodyMotionFunction.H.
Referenced by linearMotion::clone(), multiMotion::clone(), oscillatingLinearMotion::clone(), axisRotationMotion::clone(), oscillatingRotatingMotion::clone(), rotatingMotion::clone(), tabulated6DoFMotion::clone(), and SDA::clone().
The documentation for this class was generated from the following files:
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/solidBodyMotionFunction/solidBodyMotionFunction.H
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/solidBodyMotionFunction/solidBodyMotionFunction.C
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/solidBodyMotionFunction/solidBodyMotionFunctionNew.C