OpenFOAM: axisRotationMotion Class Reference
axisRotationMotion Class Reference
Constant velocity rotation around CoG. Similar to rotatingMotion but motion specified as rotation vector.
Public Member Functions
TypeName ("axisRotationMotion")
Runtime type information.
axisRotationMotion (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from components.
virtual autoPtr< solidBodyMotionFunction > clone () const
Construct and return a clone.
virtual ~axisRotationMotion ()
Destructor.
virtual septernion transformation () const
Return the solid-body motion transformation septernion.
virtual bool read (const dictionary &SBMFCoeffs)
Update properties from given dictionary.
Public Member Functions inherited from solidBodyMotionFunction
TypeName ("solidBodyMotionFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidBodyMotionFunction, dictionary,(const dictionary &SBMFCoeffs, const Time &runTime),(SBMFCoeffs, runTime))
solidBodyMotionFunction (const dictionary &SBMFCoeffs, const Time &runTime)
Construct from the SBMFCoeffs dictionary and Time.
virtual ~solidBodyMotionFunction ()
Destructor.
virtual void writeData (Ostream &) const
Write in dictionary format.
Additional Inherited Members
Static Public Member Functions inherited from solidBodyMotionFunction
static autoPtr< solidBodyMotionFunction > New (const dictionary &SBMFCoeffs, const Time &runTime)
Select constructed from the SBMFCoeffs dictionary and Time.
Protected Attributes inherited from solidBodyMotionFunction
dictionary SBMFCoeffs_
const Time & time_
Detailed Description
Constant velocity rotation around CoG. Similar to rotatingMotion but motion specified as rotation vector.
Source files
axisRotationMotion.H
axisRotationMotion.C
Definition at line 53 of file axisRotationMotion.H.
Constructor & Destructor Documentation
axisRotationMotion()
axisRotationMotion (const dictionary & SBMFCoeffs, const Time & runTime)
Construct from components.
Definition at line 52 of file axisRotationMotion.C.
References Foam::read().
~axisRotationMotion()
~axisRotationMotion () virtual
Destructor.
Definition at line 65 of file axisRotationMotion.C.
Referenced by axisRotationMotion::clone().
Member Function Documentation
TypeName()
TypeName ("axisRotationMotion")
Runtime type information.
clone()
virtual autoPtr<solidBodyMotionFunction> clone () const inline virtual
Construct and return a clone.
Implements solidBodyMotionFunction.
Definition at line 91 of file axisRotationMotion.H.
References axisRotationMotion::read(), solidBodyMotionFunction::SBMFCoeffs_, solidBodyMotionFunction::time_, axisRotationMotion::transformation(), and axisRotationMotion::~axisRotationMotion().
transformation()
Foam::septernion transformation () const virtual
Return the solid-body motion transformation septernion.
Implements solidBodyMotionFunction.
Definition at line 72 of file axisRotationMotion.C.
References DebugInFunction, Foam::degToRad(), Foam::endl(), Foam::mag(), R, and axisRotationMotion::read().
Referenced by axisRotationMotion::clone().
read()
bool read (const dictionary & SBMFCoeffs) virtual
Update properties from given dictionary.
Implements solidBodyMotionFunction.
Definition at line 95 of file axisRotationMotion.C.
References solidBodyMotionFunction::read().
Referenced by axisRotationMotion::clone(), and axisRotationMotion::transformation().
The documentation for this class was generated from the following files:
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/axisRotationMotion/axisRotationMotion.H
src/dynamicFvMesh/solidBodyMotionFvMesh/solidBodyMotionFunctions/axisRotationMotion/axisRotationMotion.C