OpenFOAM: undoableMeshCutter Class Reference
undoableMeshCutter Class Reference
The main refinement handler. Gets cellCuts which is structure that describes which cells are to be cut and in what way. Maintains an undo list (if told so during construction). Apart from undo list is just wrapper around meshCutter.
Public Member Functions
ClassName ("undoableMeshCutter")
Runtime type information.
undoableMeshCutter (const polyMesh &mesh, const bool undoable=true)
Construct from mesh and flag whether refinement pattern needs.
~undoableMeshCutter ()
Destructor.
const Map< splitCell * > & liveSplitCells () const
All current live split cells. Warning: cell labels will change.
const removeFaces & faceRemover () const
void setRefinement (const cellCuts &cuts, polyTopoChange &)
Refine cells acc. to cellCuts. Plays topology changes.
void updateMesh (const mapPolyMesh &morphMap)
Update stored refinement pattern for changes to mesh. Only.
labelList getSplitFaces () const
Calculate split faces from current liveCells. Only.
Map< label > getAddedCells () const
Like getSplitFaces but returns map from original to added cell.
labelList removeSplitFaces (const labelList &splitFaces, polyTopoChange &)
Remove some refinement. Needs to be supplied subset of.
Public Member Functions inherited from meshCutter
ClassName ("meshCutter")
Runtime type information.
meshCutter (const polyMesh &mesh)
Construct from mesh.
~meshCutter ()
Destructor.
void setRefinement (const cellCuts &cuts, polyTopoChange &meshMod)
Do actual cutting with cut description. Inserts mesh changes.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
const Map< label > & addedCells () const
Cells added. Per split cell label of added cell.
const Map< label > & addedFaces () const
Faces added. Per split cell label of added face.
const HashTable< label, edge, Hash< edge > > & addedPoints () const
Points added. Per split edge label of added point.
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Additional Inherited Members
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
Is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
Convert eVert to edge label.
static label getVertex (const primitiveMesh &mesh, const label eVert)
Convert eVert to vertex label.
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointi to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Detailed Description
The main refinement handler. Gets cellCuts which is structure that describes which cells are to be cut and in what way. Maintains an undo list (if told so during construction). Apart from undo list is just wrapper around meshCutter.
Undo list: contains a refinement tree (of type splitCell; cell labels are of no consequence) and a list of visible splitCells, i.e. the top of the tree (where the cell labels are valid). Now every cell added gets put on the tree and every updateMesh action updates the labels of visible splitcells.
We can now ask this structure for a list of visible split cells or the list of faces between these. These can be passed to removeFaces for actual deletion and we delete the top splitCell and update the now newly visible underlying cells for the new cell number (passed back from removeFaces).
NOTE: Undoing note properly tested. Expect it to fail if the faces to be removed cause other faces to be additionally removed (i.e. removeFaces adds additional faces to remove).
splitCell:
original cell number.
pointer to parent (null for first level splitCell)
two pointers to splitCell children. Both null (unrefined=visible cell) or both non-null.
live are: (-all unrefined cells (original cell without any splitCells)) -all splitCells with null children
liveSplitCells contains pointers to splitCells with null children.
Source files
undoableMeshCutter.H
undoableMeshCutter.C
Definition at line 93 of file undoableMeshCutter.H.
Constructor & Destructor Documentation
undoableMeshCutter()
undoableMeshCutter (const polyMesh & mesh, const bool undoable = true)
Construct from mesh and flag whether refinement pattern needs.
to be stored.
Definition at line 176 of file undoableMeshCutter.C.
~undoableMeshCutter()
~undoableMeshCutter ()
Destructor.
Definition at line 194 of file undoableMeshCutter.C.
References forAllIter, splitCell::getOther(), splitCell::parent(), and undoableMeshCutter::setRefinement().
Member Function Documentation
ClassName()
ClassName ("undoableMeshCutter")
Runtime type information.
liveSplitCells()
const Map<splitCell*>& liveSplitCells () const inline
All current live split cells. Warning: cell labels will change.
during morphing. Only this map is guaranteed to hold uptodate info.
Definition at line 162 of file undoableMeshCutter.H.
faceRemover()
const removeFaces& faceRemover () const inline
Definition at line 167 of file undoableMeshCutter.H.
References undoableMeshCutter::getAddedCells(), undoableMeshCutter::getSplitFaces(), undoableMeshCutter::removeSplitFaces(), undoableMeshCutter::setRefinement(), and undoableMeshCutter::updateMesh().
setRefinement()
void setRefinement (const cellCuts & cuts, polyTopoChange & meshMod)
Refine cells acc. to cellCuts. Plays topology changes.
into polyTopoChange.
Definition at line 229 of file undoableMeshCutter.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAllConstIter(), splitCell::master(), Foam::Pout, meshCutter::setRefinement(), and splitCell::slave().
Referenced by undoableMeshCutter::faceRemover(), and undoableMeshCutter::~undoableMeshCutter().
updateMesh()
void updateMesh (const mapPolyMesh & morphMap)
Update stored refinement pattern for changes to mesh. Only.
call if undoable set.
Definition at line 324 of file undoableMeshCutter.C.
References mapPolyMesh::reverseCellMap(), and meshCutter::updateMesh().
Referenced by undoableMeshCutter::faceRemover().
getSplitFaces()
Foam::labelList getSplitFaces () const
Calculate split faces from current liveCells. Only.
call if undoable set.
Definition at line 342 of file undoableMeshCutter.C.
References Foam::abort(), splitCell::cellLabel(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAllConstIter(), splitCell::getOther(), Foam::meshTools::getSharedFace(), splitCell::isMaster(), splitCell::isUnrefined(), mesh, and splitCell::parent().
Referenced by undoableMeshCutter::faceRemover().
getAddedCells()
Foam::Map< Foam::label > getAddedCells () const
Like getSplitFaces but returns map from original to added cell.
Only call if undoable set.
Definition at line 401 of file undoableMeshCutter.C.
References Foam::abort(), splitCell::cellLabel(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAllConstIter(), splitCell::getOther(), splitCell::isMaster(), splitCell::isUnrefined(), splitCell::parent(), and undoableMeshCutter::removeSplitFaces().
Referenced by undoableMeshCutter::faceRemover().
removeSplitFaces()
Foam::labelList removeSplitFaces (const labelList & splitFaces, polyTopoChange & meshMod)
Remove some refinement. Needs to be supplied subset of.
getSplitFaces() output. Returns list of faces removed (can be more or equal but never less than splitFaces - since removeFaces might decide to take down unnecessary faces) Only call if undoable set.
important: Redo search since ownFind entry deleted.
Definition at line 448 of file undoableMeshCutter.C.
References Foam::abort(), splitCell::cellLabel(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), Foam::FatalError, FatalErrorInFunction, forAll, splitCell::isUnrefined(), mesh, splitCell::parent(), Foam::Pout, and List< T >::size().
Referenced by undoableMeshCutter::faceRemover(), and undoableMeshCutter::getAddedCells().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/undoableMeshCutter/undoableMeshCutter.H
src/dynamicMesh/meshCut/meshModifiers/undoableMeshCutter/undoableMeshCutter.C