OpenFOAM: meshCutter Class Reference
meshCutter Class Reference
Cuts (splits) cells.
Public Member Functions
ClassName ("meshCutter")
Runtime type information.
meshCutter (const polyMesh &mesh)
Construct from mesh.
~meshCutter ()
Destructor.
void setRefinement (const cellCuts &cuts, polyTopoChange &meshMod)
Do actual cutting with cut description. Inserts mesh changes.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
const Map< label > & addedCells () const
Cells added. Per split cell label of added cell.
const Map< label > & addedFaces () const
Faces added. Per split cell label of added face.
const HashTable< label, edge, Hash< edge > > & addedPoints () const
Points added. Per split edge label of added point.
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Additional Inherited Members
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
Is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
Convert eVert to edge label.
static label getVertex (const primitiveMesh &mesh, const label eVert)
Convert eVert to vertex label.
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointi to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Detailed Description
Cuts (splits) cells.
Description of cut is given as a loop of 'cuts' per cell (see cellCuts). setRefinement() takes this cut description and inserts the necessary topoActions (add points/faces/cells) into the polyTopoChange.
Stores added cells/faces/points.
Cut description gives orientation to cut by calculating 'anchorPoints'. The side of the cell that contains the anchorPoints is the master cell. Likewise the cells' edges will have the split added as a duplicate of the master (anchor) point. Think of it as the cell with the anchor points at the bottom. Add a face at the bottom to split the cell and then sweep this face up to be through the middle of the cell (inflation).
Start: cell with anchor points at bottom
+-------+
|       +
|       +
|       +
|       +
|       +
|       +
|       +
+-------+
anchor  anchor
Topo change: splitface introduced at bottom of cell, introducing a new cell and splitting the side faces into two.
+-------+
|       +
|       +
|       + <- addedCell
|       +
|       +
|       +
+-------+ <- splitFace
+-------+ <- original cell
anchor  anchor
Inflation: splitface shifted up to middle of cell (or wherever cut was)
+-------+
|       +
|       + <- addedCell
|       +
+-------+ <- splitFace
|       +
|       + <- original cell
|       +
+-------+
anchor  anchor
Anyway this was the original idea. Inflation was meant to handle conservative properties distribution without interpolation. (just face sweeping through space). But problem was that only if the introduced splitface was exactly the same shape as bottom face (so same 2D topo or perfectly flat) the volume between them was 0.
This meshCutting still uses anchorPoints though:
the master cell is the one without the anchor points. The added cell (on top of the splitFace) is the with.
the splitFace is owned by the master cell (since it has the lower number)
the side faces get split and get either the original cell as neighbour or the added cell (if the faces contain the cell anchor points)
Source files
meshCutter.H
meshCutter.C
Definition at line 134 of file meshCutter.H.
Constructor & Destructor Documentation
meshCutter()
meshCutter (const polyMesh & mesh)
Construct from mesh.
Definition at line 505 of file meshCutter.C.
~meshCutter()
~meshCutter ()
Destructor.
Definition at line 517 of file meshCutter.C.
References meshCutter::setRefinement().
Member Function Documentation
ClassName()
ClassName ("meshCutter")
Runtime type information.
setRefinement()
void setRefinement (const cellCuts & cuts, polyTopoChange & meshMod)
Do actual cutting with cut description. Inserts mesh changes.
into meshMod.
Definition at line 524 of file meshCutter.C.
References Foam::abort(), cellCuts::cellAnchorPoints(), cellCuts::cellLoops(), primitiveMesh::cells(), HashTable< T, Key, Hash >::clear(), primitiveMesh::edgeFaces(), cellCuts::edgeIsCut(), primitiveMesh::edges(), cellCuts::edgeWeight(), edge::end(), Foam::endl(), f1, polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), cellCuts::faceSplitCut(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIter(), edgeVertex::getEdge(), edgeVertex::getVertex(), HashTable< T, Key, Hash >::insert(), edgeVertex::isEdge(), edgeVertex::mesh(), Foam::nl, cellCuts::nLoops(), polyMesh::points(), Foam::Pout, HashTable< T, Key, Hash >::resize(), polyTopoChange::setAction(), List< T >::size(), HashTable< T, Key, Hash >::size(), edge::start(), and edgeVertex::writeCuts().
Referenced by undoableMeshCutter::setRefinement(), and meshCutter::~meshCutter().
updateMesh()
void updateMesh (const mapPolyMesh & morphMap)
Force recalculation of locally stored data on topological change.
Definition at line 972 of file meshCutter.C.
References edge::end(), Foam::endl(), forAllConstIter(), Foam::Pout, mapPolyMesh::reverseCellMap(), mapPolyMesh::reverseFaceMap(), mapPolyMesh::reversePointMap(), HashTable< T, Key, Hash >::size(), edge::start(), and HashTable< T, Key, Hash >::transfer().
Referenced by undoableMeshCutter::updateMesh().
addedCells()
const Map<label>& addedCells () const inline
Cells added. Per split cell label of added cell.
Definition at line 297 of file meshCutter.H.
addedFaces()
const Map<label>& addedFaces () const inline
Faces added. Per split cell label of added face.
Definition at line 303 of file meshCutter.H.
addedPoints()
const HashTable<label, edge, Hash<edge> >& addedPoints () const inline
Points added. Per split edge label of added point.
Definition at line 309 of file meshCutter.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/meshCutter/meshCutter.H
src/dynamicMesh/meshCut/meshModifiers/meshCutter/meshCutter.C