OpenFOAM: layerAdditionRemoval Class Reference
layerAdditionRemoval Class Reference
Cell layer addition mesh modifier.
Public Member Functions
TypeName ("layerAdditionRemoval")
Runtime type information.
layerAdditionRemoval (const word &name, const label index, const polyTopoChanger &ptc, const word &zoneName, const scalar minThickness, const scalar maxThickness, const Switch thicknessFromVolume=true)
Construct from components.
layerAdditionRemoval (const word &name, const dictionary &dict, const label index, const polyTopoChanger &ptc)
Construct from dictionary.
virtual ~layerAdditionRemoval ()
Destructor.
virtual bool changeTopology () const
Check for topology change.
virtual void setRefinement (polyTopoChange &) const
Insert the layer addition/removal instructions.
virtual void modifyMotionPoints (pointField &motionPoints) const
Modify motion points to comply with the topological change.
virtual void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
scalar minLayerThickness () const
Return min layer thickness which triggers removal.
void setMinLayerThickness (const scalar t) const
Set min layer thickness which triggers removal.
scalar maxLayerThickness () const
Return max layer thickness which triggers removal.
void setMaxLayerThickness (const scalar t) const
Set max layer thickness which triggers removal.
virtual void write (Ostream &) const
Write.
virtual void writeDict (Ostream &) const
Write dictionary.
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
Construct from components.
virtual ~polyMeshModifier ()
Destructor.
const word & name () const
Return name of this modifier.
label index () const
Return the index of this modifier.
const polyTopoChanger & topoChanger () const
Return reference to morph engine.
const Switch & active () const
void enable () const
Activate mesh modifier.
void disable () const
Activate mesh modifier.
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Select constructed from dictionary.
Detailed Description
Cell layer addition mesh modifier.
Source files
layerAdditionRemoval.H
layerAdditionRemoval.C
addCellLayer.C
removeCellLayer.C
Definition at line 52 of file layerAdditionRemoval.H.
Constructor & Destructor Documentation
layerAdditionRemoval() [1/2]
layerAdditionRemoval (const word & name, const label index, const polyTopoChanger & ptc, const word & zoneName, const scalar minThickness, const scalar maxThickness, const Switch thicknessFromVolume = true)
Construct from components.
Definition at line 136 of file layerAdditionRemoval.C.
layerAdditionRemoval() [2/2]
layerAdditionRemoval (const word & name, const dictionary & dict, const label index, const polyTopoChanger & ptc)
Construct from dictionary.
Definition at line 162 of file layerAdditionRemoval.C.
~layerAdditionRemoval()
~layerAdditionRemoval () virtual
Destructor.
Definition at line 189 of file layerAdditionRemoval.C.
Member Function Documentation
TypeName()
TypeName ("layerAdditionRemoval")
Runtime type information.
changeTopology()
bool changeTopology () const virtual
Check for topology change.
Implements polyMeshModifier.
Definition at line 197 of file layerAdditionRemoval.C.
References Foam::abort(), primitiveMesh::cells(), primitiveMesh::cellVolumes(), Foam::e, cell::edges(), Foam::endl(), primitiveMesh::faceAreas(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, forAll, HashTable< T, Key, Hash >::found(), edge::mag(), Foam::mag(), faceZone::masterCells(), Foam::max(), mesh, Foam::min(), Foam::name(), Foam::nl, polyMesh::points(), Foam::Pout, Foam::reduce(), List< T >::size(), objectRegistry::time(), and TimeState::timeIndex().
setRefinement()
void setRefinement (polyTopoChange & ref) const virtual
Insert the layer addition/removal instructions.
into the topological change
Implements polyMeshModifier.
Definition at line 395 of file layerAdditionRemoval.C.
References Foam::endl(), mesh, Foam::name(), Foam::Pout, and timeIndex.
modifyMotionPoints()
void modifyMotionPoints (pointField & motionPoints) const virtual
Modify motion points to comply with the topological change.
Implements polyMeshModifier.
Definition at line 214 of file setLayerPairing.C.
References Foam::endl(), polyMeshModifier::name(), and Foam::Pout.
updateMesh()
void updateMesh (const mapPolyMesh &) virtual
Force recalculation of locally stored data on topological change.
Implements polyMeshModifier.
Definition at line 434 of file layerAdditionRemoval.C.
References Foam::endl(), mesh, Foam::name(), and Foam::Pout.
minLayerThickness()
scalar minLayerThickness () const inline
Return min layer thickness which triggers removal.
Definition at line 196 of file layerAdditionRemoval.H.
References layerAdditionRemoval::setMinLayerThickness().
setMinLayerThickness()
void setMinLayerThickness (const scalar t) const
Set min layer thickness which triggers removal.
Definition at line 459 of file layerAdditionRemoval.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by layerAdditionRemoval::minLayerThickness().
maxLayerThickness()
scalar maxLayerThickness () const inline
Return max layer thickness which triggers removal.
Definition at line 205 of file layerAdditionRemoval.H.
References layerAdditionRemoval::setMaxLayerThickness(), layerAdditionRemoval::write(), and layerAdditionRemoval::writeDict().
setMaxLayerThickness()
void setMaxLayerThickness (const scalar t) const
Set max layer thickness which triggers removal.
Definition at line 472 of file layerAdditionRemoval.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by layerAdditionRemoval::maxLayerThickness().
write()
void write (Ostream & os) const virtual
Write.
Implements polyMeshModifier.
Definition at line 485 of file layerAdditionRemoval.C.
References Foam::endl(), Foam::name(), Foam::nl, and Foam::type().
Referenced by layerAdditionRemoval::maxLayerThickness().
writeDict()
void writeDict (Ostream & os) const virtual
Write dictionary.
Implements polyMeshModifier.
Definition at line 497 of file layerAdditionRemoval.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::name(), Foam::nl, and Foam::type().
Referenced by layerAdditionRemoval::maxLayerThickness().
The documentation for this class was generated from the following files:
src/dynamicMesh/layerAdditionRemoval/layerAdditionRemoval.H
src/dynamicMesh/layerAdditionRemoval/addCellLayer.C
src/dynamicMesh/layerAdditionRemoval/layerAdditionRemoval.C
src/dynamicMesh/layerAdditionRemoval/removeCellLayer.C
src/dynamicMesh/layerAdditionRemoval/setLayerPairing.C