OpenFOAM: meshCutAndRemove Class Reference
meshCutAndRemove Class Reference
like meshCutter but also removes non-anchor side of cell.
Public Member Functions
ClassName ("meshCutAndRemove")
Runtime type information.
meshCutAndRemove (const polyMesh &mesh)
Construct from mesh.
void setRefinement (const label exposedPatchi, const cellCuts &cuts, const labelList &cutPatch, polyTopoChange &meshMod)
Do actual cutting with cut description. Inserts mesh changes.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
const Map< label > & addedFaces () const
Faces added. Per split cell label of added face.
const HashTable< label, edge, Hash< edge > > & addedPoints () const
Points added. Per split edge label of added point.
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Additional Inherited Members
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
Is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
Convert eVert to edge label.
static label getVertex (const primitiveMesh &mesh, const label eVert)
Convert eVert to vertex label.
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointi to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Detailed Description
like meshCutter but also removes non-anchor side of cell.
Source files
meshCutAndRemove.H
meshCutAndRemove.C
Definition at line 60 of file meshCutAndRemove.H.
Constructor & Destructor Documentation
meshCutAndRemove()
meshCutAndRemove (const polyMesh & mesh)
Construct from mesh.
Definition at line 564 of file meshCutAndRemove.C.
References meshCutAndRemove::setRefinement().
Member Function Documentation
ClassName()
ClassName ("meshCutAndRemove")
Runtime type information.
setRefinement()
void setRefinement (const label exposedPatchi, const cellCuts & cuts, const labelList & cutPatch, polyTopoChange & meshMod)
Do actual cutting with cut description. Inserts mesh changes.
into meshMod. cuts: all loops and topological information cutPatch: for every cell that has loop the patch number exposedPatch: patch for other exposed faces
Definition at line 575 of file meshCutAndRemove.C.
References Foam::abort(), polyMesh::boundaryMesh(), cellCuts::cellAnchorPoints(), cellCuts::cellLoops(), primitiveMesh::cellPoints(), HashTable< T, Key, Hash >::clear(), primitiveMesh::edgeFaces(), cellCuts::edgeIsCut(), primitiveMesh::edges(), cellCuts::edgeWeight(), edge::end(), Foam::endl(), f1, polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), cellCuts::faceSplitCut(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIter(), edgeVertex::getEdge(), edgeVertex::getVertex(), HashTable< T, Key, Hash >::insert(), edgeVertex::isEdge(), edgeVertex::mesh(), Foam::nl, cellCuts::nLoops(), nPoints, cellCuts::pointIsCut(), polyMesh::points(), Foam::Pout, HashTable< T, Key, Hash >::resize(), Foam::reverse(), polyTopoChange::setAction(), List< T >::size(), UPtrList< T >::size(), HashTable< T, Key, Hash >::size(), edge::start(), polyBoundaryMesh::whichPatch(), and edgeVertex::writeCuts().
Referenced by meshCutAndRemove::meshCutAndRemove().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Force recalculation of locally stored data on topological change.
Definition at line 1267 of file meshCutAndRemove.C.
References edge::end(), Foam::endl(), forAllConstIter(), Foam::Pout, mapPolyMesh::reverseCellMap(), mapPolyMesh::reverseFaceMap(), mapPolyMesh::reversePointMap(), HashTable< T, Key, Hash >::size(), edge::start(), and HashTable< T, Key, Hash >::transfer().
addedFaces()
const Map<label>& addedFaces () const inline
Faces added. Per split cell label of added face.
Definition at line 219 of file meshCutAndRemove.H.
References meshCutAndRemove::addedPoints().
addedPoints()
const HashTable<label, edge, Hash<edge> >& addedPoints () const inline
Points added. Per split edge label of added point.
(note: fairly useless across topology changes since one of the points of the edge will probably disappear)
Definition at line 227 of file meshCutAndRemove.H.
Referenced by meshCutAndRemove::addedFaces().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/meshCutAndRemove/meshCutAndRemove.H
src/dynamicMesh/meshCut/meshModifiers/meshCutAndRemove/meshCutAndRemove.C