OpenFOAM: edgeVertex Class Reference
edgeVertex Class Reference
Combines edge or vertex in single label. Used to specify cuts across cell circumference.
Public Member Functions
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Static Public Member Functions
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
Is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
Convert eVert to edge label.
static label getVertex (const primitiveMesh &mesh, const label eVert)
Convert eVert to vertex label.
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointi to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Detailed Description
Combines edge or vertex in single label. Used to specify cuts across cell circumference.
Source files
edgeVertex.H
Definition at line 52 of file edgeVertex.H.
Constructor & Destructor Documentation
edgeVertex()
edgeVertex (const polyMesh & mesh) inline
Construct from mesh.
Definition at line 90 of file edgeVertex.H.
Member Function Documentation
updateLabels() [1/3]
void updateLabels (const labelList & map, List< refineCell > & refCells) static
Update refine list from map. Used to update cell/face labels.
after morphing
Definition at line 36 of file edgeVertex.C.
References refineCell::cellNo(), refineCell::direction(), forAll, and List< T >::setSize().
Referenced by edgeVertex::updateLabels().
updateLabels() [2/3]
void updateLabels (const labelList & map, Map< label > & cellPairs) static
Update map from map. Used to update cell/face labels.
after morphing
Definition at line 63 of file edgeVertex.C.
References Foam::endl(), forAllConstIter(), HashTable< T, Key, Hash >::size(), edgeVertex::updateLabels(), and WarningInFunction.
updateLabels() [3/3]
void updateLabels (const labelList & map, labelHashSet & cells) static
Update map from map. Used to update cell/face labels.
after morphing
Definition at line 126 of file edgeVertex.C.
References edgeVertex::coord(), forAllConstIter(), and HashTable< T, Key, Hash >::size().
mesh()
const polyMesh& mesh () const inline
Definition at line 98 of file edgeVertex.H.
Referenced by hexCellLooper::cut(), geomCellLooper::cut(), topoCellLooper::cut(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), and geomCellLooper::setSnapTol().
isEdge() [1/2]
static bool isEdge (const primitiveMesh & mesh, const label eVert) inline static
Is eVert an edge?
Definition at line 107 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::nEdges(), and primitiveMesh::nPoints().
Referenced by geomCellLooper::cut(), edgeVertex::getEdge(), edgeVertex::getVertex(), edgeVertex::isEdge(), meshCutAndRemove::setRefinement(), and meshCutter::setRefinement().
isEdge() [2/2]
bool isEdge (const label eVert) const inline
Definition at line 120 of file edgeVertex.H.
References edgeVertex::isEdge().
getEdge() [1/2]
static label getEdge (const primitiveMesh & mesh, const label eVert) inline static
Convert eVert to edge label.
Definition at line 126 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, edgeVertex::isEdge(), and primitiveMesh::nPoints().
Referenced by edgeVertex::getEdge(), meshCutAndRemove::setRefinement(), and meshCutter::setRefinement().
getEdge() [2/2]
label getEdge (const label eVert) const inline
Definition at line 136 of file edgeVertex.H.
References edgeVertex::getEdge().
getVertex() [1/2]
static label getVertex (const primitiveMesh & mesh, const label eVert) inline static
Convert eVert to vertex label.
Definition at line 142 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and edgeVertex::isEdge().
Referenced by edgeVertex::getVertex(), meshCutAndRemove::setRefinement(), and meshCutter::setRefinement().
getVertex() [2/2]
label getVertex (const label eVert) const inline
Definition at line 152 of file edgeVertex.H.
References edgeVertex::getVertex().
vertToEVert() [1/2]
static label vertToEVert (const primitiveMesh & mesh, const label vertI) inline static
Convert pointi to eVert.
Definition at line 158 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and primitiveMesh::nPoints().
Referenced by geomCellLooper::cut(), and edgeVertex::vertToEVert().
vertToEVert() [2/2]
label vertToEVert (const label vertI) const inline
Definition at line 168 of file edgeVertex.H.
References edgeVertex::vertToEVert().
edgeToEVert() [1/2]
static label edgeToEVert (const primitiveMesh & mesh, const label edgeI) inline static
Convert edgeI to eVert.
Definition at line 174 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::nEdges(), and primitiveMesh::nPoints().
Referenced by geomCellLooper::cut(), and edgeVertex::edgeToEVert().
edgeToEVert() [2/2]
label edgeToEVert (const label edgeI) const inline
Definition at line 184 of file edgeVertex.H.
References edgeVertex::coord(), and edgeVertex::edgeToEVert().
coord() [1/2]
Foam::point coord (const primitiveMesh & mesh, const label cut, const scalar weight) static
Return coordinate of cut (uses weight if edgeCut)
Definition at line 169 of file edgeVertex.C.
References edgeVertex::cutPairToEdge(), Foam::constant::electromagnetic::e, primitiveMesh::edges(), edge::end(), primitiveMesh::points(), and edge::start().
Referenced by edgeVertex::coord(), geomCellLooper::cut(), edgeVertex::edgeToEVert(), and edgeVertex::updateLabels().
coord() [2/2]
point coord (const label cut, const scalar weight) const inline
Definition at line 196 of file edgeVertex.H.
References edgeVertex::coord(), and edgeVertex::cutPairToEdge().
cutPairToEdge() [1/2]
Foam::label cutPairToEdge (const primitiveMesh & mesh, const label cut0, const label cut1) static
Find mesh edge (or -1) between two cuts.
Definition at line 191 of file edgeVertex.C.
References Foam::meshTools::findEdge(), and edgeVertex::writeCut().
Referenced by edgeVertex::coord(), and edgeVertex::cutPairToEdge().
cutPairToEdge() [2/2]
label cutPairToEdge (const label cut0, const label cut1) const inline
Definition at line 208 of file edgeVertex.H.
References edgeVertex::cutPairToEdge(), edgeVertex::writeCut(), and edgeVertex::writeCuts().
writeCut()
Foam::Ostream & writeCut (Ostream & os, const label cut, const scalar weight) const
Write cut description to Ostream.
Definition at line 214 of file edgeVertex.C.
References Foam::constant::electromagnetic::e, mesh, and edgeVertex::writeCuts().
Referenced by geomCellLooper::cut(), and edgeVertex::cutPairToEdge().
writeCuts()
Foam::Ostream & writeCuts (Ostream & os, const labelList & cuts, const scalarField & weights) const
Write cut descriptions to Ostream.
Definition at line 239 of file edgeVertex.C.
References forAll.
Referenced by edgeVertex::cutPairToEdge(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), and edgeVertex::writeCut().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/edgeVertex/edgeVertex.H
src/dynamicMesh/meshCut/edgeVertex/edgeVertex.C