OpenFOAM: directionInfo Class Reference
directionInfo Class Reference
Holds direction in which to split cell (in fact a local coordinate axes). Information is a label and a direction.
Public Member Functions
directionInfo ()
Construct null.
directionInfo (const label, const vector &n)
Construct from components.
directionInfo (const directionInfo &)
Construct as copy.
label index () const
const vector & n () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const directionInfo &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const directionInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const directionInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const directionInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const directionInfo &, TrackingData &td) const
Same (like operator==)
bool operator== (const directionInfo &) const
bool operator!= (const directionInfo &) const
Static Public Member Functions
static label edgeToFaceIndex (const primitiveMesh &mesh, const label celli, const label facei, const label edgeI)
Given edge on hex cell find corresponding edge on face. Is either.
Friends
Ostream & operator<< (Ostream &, const directionInfo &)
Istream & operator>> (Istream &, directionInfo &)
Detailed Description
Holds direction in which to split cell (in fact a local coordinate axes). Information is a label and a direction.
The direction is the normal direction to cut in. The label's meaning depends on whether the info is on a cell or on a face:
in cell: edge that is being cut. (determines for hex how cut is)
in face: local face point that is being cut or -1.
(-1) : cut is tangential to plane
(>= 0): edge fp..fp+1 is cut
(has to be facepoint, not vertex since vertex not valid across processors whereas f[0] should correspond to f[0] on other side)
The rule is that if the label is set (-1 or higher) it is used (topological information only), otherwise the vector is used. This makes sure that we use topological information as much as possible and so a hex mesh is cut purely topologically. All other shapes are cut geometrically.
Source files
directionInfo.H
directionInfoI.H
directionInfo.C
Definition at line 84 of file directionInfo.H.
Constructor & Destructor Documentation
directionInfo() [1/3]
directionInfo () inline
Construct null.
Definition at line 33 of file directionInfoI.H.
directionInfo() [2/3]
directionInfo (const label index, const vector & n) inline
Construct from components.
Definition at line 42 of file directionInfoI.H.
directionInfo() [3/3]
directionInfo (const directionInfo & w2) inline
Construct as copy.
Definition at line 53 of file directionInfoI.H.
Member Function Documentation
edgeToFaceIndex()
Foam::label edgeToFaceIndex (const primitiveMesh & mesh, const label celli, const label facei, const label edgeI) static
Given edge on hex cell find corresponding edge on face. Is either.
index in face or -1 (cut tangential to face). Public since is needed to fill in seed faces in meshWave.
Definition at line 93 of file directionInfo.C.
References Foam::abort(), Foam::e, primitiveMesh::edges(), edge::end(), UList< T >::end(), Foam::endl(), f(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), Foam::meshTools::getEdgeFaces(), primitiveMesh::nEdges(), List< T >::size(), edge::start(), and Foam::meshTools::walkFace().
Referenced by NamedEnum< directionType, 3 >::names(), and directionInfo::updateFace().
index()
label index () const inline
Definition at line 149 of file directionInfo.H.
Referenced by directionInfo::operator==(), directionInfo::updateCell(), and directionInfo::updateFace().
n()
const vector& n () const inline
Definition at line 154 of file directionInfo.H.
References directionInfo::enterDomain(), directionInfo::equal(), directionInfo::leaveDomain(), directionInfo::operator!=(), directionInfo::operator<<, directionInfo::operator==(), directionInfo::operator>>, directionInfo::sameGeometry(), directionInfo::transform(), directionInfo::updateCell(), directionInfo::updateFace(), and directionInfo::valid().
Referenced by directionInfo::operator==(), directionInfo::updateCell(), and directionInfo::updateFace().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 63 of file directionInfoI.H.
References directionInfo::sameGeometry().
Referenced by directionInfo::n().
sameGeometry()
bool sameGeometry (const polyMesh & , const directionInfo & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 72 of file directionInfoI.H.
References directionInfo::leaveDomain().
Referenced by directionInfo::n(), and directionInfo::valid().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 87 of file directionInfoI.H.
References directionInfo::enterDomain().
Referenced by directionInfo::n(), and directionInfo::sameGeometry().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 103 of file directionInfoI.H.
References f(), List< T >::size(), and directionInfo::transform().
Referenced by directionInfo::leaveDomain(), and directionInfo::n().
transform()
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 123 of file directionInfoI.H.
References directionInfo::updateCell().
Referenced by directionInfo::enterDomain(), and directionInfo::n().
updateCell()
bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const directionInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 134 of file directionInfoI.H.
References Foam::e, primitiveMesh::edges(), f(), primitiveMesh::faceEdges(), polyMesh::faces(), directionInfo::index(), Foam::isA(), directionInfo::n(), Foam::meshTools::otherEdge(), Foam::meshTools::otherFace(), List< T >::size(), edge::start(), and directionInfo::updateFace().
Referenced by directionInfo::n(), and directionInfo::transform().
updateFace() [1/2]
bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const directionInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 215 of file directionInfoI.H.
References directionInfo::edgeToFaceIndex(), directionInfo::index(), and directionInfo::n().
Referenced by directionInfo::n(), and directionInfo::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & mesh, const label thisFacei, const directionInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 264 of file directionInfoI.H.
References directionInfo::equal(), directionInfo::index(), and directionInfo::n().
equal()
bool equal (const directionInfo & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 290 of file directionInfoI.H.
References directionInfo::operator==().
Referenced by directionInfo::n(), and directionInfo::updateFace().
operator==()
bool operator== (const directionInfo & rhs) const inline
Definition at line 301 of file directionInfoI.H.
References directionInfo::index(), and directionInfo::n().
Referenced by directionInfo::equal(), and directionInfo::n().
operator!=()
bool operator!= (const directionInfo & rhs) const inline
Definition at line 308 of file directionInfoI.H.
Referenced by directionInfo::n().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const directionInfo &) friend
Referenced by directionInfo::n().
operator>>
Istream& operator>> (Istream & , directionInfo &) friend
Referenced by directionInfo::n().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/directions/directionInfo/directionInfo.H
src/dynamicMesh/meshCut/directions/directionInfo/directionInfo.C
src/dynamicMesh/meshCut/directions/directionInfo/directionInfoI.H