OpenFOAM: fvMeshSubset Class Reference
fvMeshSubset Class Reference
Post-processing mesh subset tool. Given the original mesh and the list of selected cells, it creates the mesh consisting only of the desired cells, with the mapping list for points, faces, and cells.
Public Member Functions
fvMeshSubset (const fvMesh &)
Construct given a mesh to subset.
void setCellSubset (const labelHashSet &globalCellMap, const label patchID=-1)
Set the subset. Create "oldInternalFaces" patch for exposed.
void setLargeCellSubset (const labelList &region, const label currentRegion, const label patchID=-1, const bool syncCouples=true)
Set the subset from all cells with region == currentRegion.
void setLargeCellSubset (const labelHashSet &globalCellMap, const label patchID=-1, const bool syncPar=true)
setLargeCellSubset but with labelHashSet.
labelList getExposedFaces (const labelList &region, const label currentRegion, const bool syncCouples=true) const
Two step subsetting.
void setLargeCellSubset (const labelList &region, const label currentRegion, const labelList &exposedFaces, const labelList &patchIDs, const bool syncCouples=true)
For every exposed face (from above getExposedFaces)
const fvMesh & baseMesh () const
Original mesh.
bool hasSubMesh () const
Have subMesh?
const fvMesh & subMesh () const
Return reference to subset mesh.
fvMesh & subMesh ()
const labelList & pointMap () const
Return point map.
const labelList & faceMap () const
Return face map.
const labelList & faceFlipMap () const
Return face map with sign to encode flipped faces.
const labelList & cellMap () const
Return cell map.
const labelList & patchMap () const
Return patch map.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const bool negateIfFlipped=true) const
template<class Type >
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &) const
template<class Type >
tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > &) const
Static Public Member Functions
template<class Type >
static tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const fvMesh &sMesh, const labelList &patchMap, const labelList &cellMap, const labelList &faceMap)
Map volume field.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const fvMesh &sMesh, const labelList &patchMap, const labelList &cellMap, const labelList &faceMap, const bool negateIfFlipped=true)
Map surface field. Optionally negates value if flipping.
template<class Type >
static tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &, const pointMesh &sMesh, const labelList &patchMap, const labelList &pointMap)
Map point field.
template<class Type >
static tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > &, const fvMesh &sMesh, const labelList &cellMap)
Map dimensioned field.
Detailed Description
Post-processing mesh subset tool. Given the original mesh and the list of selected cells, it creates the mesh consisting only of the desired cells, with the mapping list for points, faces, and cells.
Puts all exposed internal faces into either
a user supplied patch
a newly created patch "oldInternalFaces"
setCellSubset is for small subsets. Uses Maps to minimize memory.
setLargeCellSubset is for largish subsets (>10% of mesh). Uses labelLists instead.
setLargeCellSubset does coupled patch subsetting as well. If it detects a face on a coupled patch 'losing' its neighbour it will move the face into the oldInternalFaces patch.
if a user supplied patch is used it is up to the destination patchField to handle exposed internal faces (mapping from face -1). If not provided the default is to assign the internalField. All the basic patch field types (e.g. fixedValue) will give a warning and preferably derived patch field types should be used that know how to handle exposed faces (e.g. use uniformFixedValue instead of fixedValue)
Source files
fvMeshSubset.H
fvMeshSubset.C
Definition at line 73 of file fvMeshSubset.H.
Constructor & Destructor Documentation
fvMeshSubset()
fvMeshSubset (const fvMesh & baseMesh) explicit
Construct given a mesh to subset.
Definition at line 395 of file fvMeshSubset.C.
References fvMeshSubset::setCellSubset().
Member Function Documentation
setCellSubset()
void setCellSubset (const labelHashSet & globalCellMap, const label patchID = -1)
Set the subset. Create "oldInternalFaces" patch for exposed.
internal faces (patchID==-1) or use supplied patch. Does not handle coupled patches correctly if only one side gets deleted.
Definition at line 410 of file fvMeshSubset.C.
References Foam::abort(), fvMeshSubset::baseMesh(), polyMesh::boundaryMesh(), primitiveMesh::cells(), IOobject::clone(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::findPatchID(), forAll, HashTable< T, Key, Hash >::found(), HashTable< T, Key, Hash >::insert(), HashTable< T, label, Hash< label > >::insert(), primitiveMesh::isInternalFace(), Foam::labelMax, Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, polyMesh::points(), Foam::Pout, fvMeshSubset::setLargeCellSubset(), List< T >::setSize(), List< T >::size(), UPtrList< T >::size(), HashTable< T, label, Hash< label > >::size(), HashTable< T, Key, Hash >::size(), Foam::sort(), timeName, HashTable< T, Key, Hash >::toc(), polyBoundaryMesh::whichPatch(), and Foam::xferMove().
Referenced by fvMeshSubset::fvMeshSubset().
setLargeCellSubset() [1/3]
void setLargeCellSubset (const labelList & region, const label currentRegion, const label patchID = -1, const bool syncCouples = true)
Set the subset from all cells with region == currentRegion.
Create "oldInternalFaces" patch for exposed internal faces (patchID==-1) or use supplied patch. Handles coupled patches by if necessary making coupled patch face part of patchID (so uncoupled)
Definition at line 795 of file fvMeshSubset.C.
References Foam::abort(), fvMeshSubset::baseMesh(), polyMesh::boundaryMesh(), primitiveMesh::cells(), IOobject::clone(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::findPatchID(), forAll, Pstream::gatherList(), Foam::identity(), primitiveMesh::isInternalFace(), Foam::labelMax, Pstream::listCombineGather(), Pstream::listCombineScatter(), UPstream::myProcNo(), Foam::name(), polyBoundaryMesh::names(), primitiveMesh::nInternalFaces(), IOobject::NO_READ, IOobject::NO_WRITE, UPstream::nProcs(), UPstream::parRun(), patchi, patchNames(), polyMesh::points(), Foam::reduce(), Pstream::scatterList(), List< T >::setSize(), List< T >::size(), UPtrList< T >::size(), polyPatch::start(), timeName, and Foam::xferMove().
Referenced by structuredDecomp::decompose(), fvMeshDistribute::distribute(), fvMeshSubset::getExposedFaces(), structuredRenumber::renumber(), fvMeshSubset::setCellSubset(), and fvMeshSubset::setLargeCellSubset().
setLargeCellSubset() [2/3]
void setLargeCellSubset (const labelHashSet & globalCellMap, const label patchID = -1, const bool syncPar = true)
setLargeCellSubset but with labelHashSet.
Definition at line 1388 of file fvMeshSubset.C.
References fvMeshSubset::baseMesh(), forAllConstIter(), fvMeshSubset::getExposedFaces(), and fvMeshSubset::setLargeCellSubset().
getExposedFaces()
Foam::labelList getExposedFaces (const labelList & region, const label currentRegion, const bool syncCouples = true) const
Two step subsetting.
Get labels of exposed faces.
These are
internal faces that become boundary faces
coupled faces that become uncoupled (since one of the sides gets deleted)
Definition at line 1405 of file fvMeshSubset.C.
References fvMeshSubset::baseMesh(), removeCells::getExposedFaces(), and fvMeshSubset::setLargeCellSubset().
Referenced by fvMeshSubset::setLargeCellSubset().
setLargeCellSubset() [3/3]
void setLargeCellSubset (const labelList & region, const label currentRegion, const labelList & exposedFaces, const labelList & patchIDs, const bool syncCouples = true)
For every exposed face (from above getExposedFaces)
used supplied (existing!) patch
Definition at line 1419 of file fvMeshSubset.C.
References fvMeshSubset::baseMesh(), Foam::identity(), polyTopoChange::makeMesh(), Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, removeCells::setRefinement(), and timeName.
baseMesh()
const fvMesh& baseMesh () const inline
Original mesh.
Definition at line 217 of file fvMeshSubset.H.
References fvMeshSubset::cellMap(), fvMeshSubset::faceFlipMap(), fvMeshSubset::faceMap(), fvMeshSubset::hasSubMesh(), fvMeshSubset::interpolate(), fvMeshSubset::patchMap(), fvMeshSubset::pointMap(), and fvMeshSubset::subMesh().
Referenced by fvMeshSubset::getExposedFaces(), fvMeshDistribute::printFieldInfo(), fvMeshSubset::setCellSubset(), and fvMeshSubset::setLargeCellSubset().
hasSubMesh()
bool hasSubMesh () const
Have subMesh?
Definition at line 1466 of file fvMeshSubset.C.
Referenced by fvMeshSubset::baseMesh().
subMesh() [1/2]
const fvMesh & subMesh () const
Return reference to subset mesh.
Definition at line 1472 of file fvMeshSubset.C.
Referenced by fvMeshSubset::baseMesh(), structuredDecomp::decompose(), fvMeshDistribute::distribute(), fvMeshSubset::faceFlipMap(), vtkMesh::mesh(), and structuredRenumber::renumber().
subMesh() [2/2]
fvMesh & subMesh ()
Definition at line 1480 of file fvMeshSubset.C.
pointMap()
const labelList & pointMap () const
Return point map.
Definition at line 1488 of file fvMeshSubset.C.
Referenced by fvMeshSubset::baseMesh(), and fvMeshDistribute::distribute().
faceMap()
const labelList & faceMap () const
Return face map.
Definition at line 1496 of file fvMeshSubset.C.
Referenced by fvMeshSubset::baseMesh(), fvMeshDistribute::distribute(), and fvMeshSubset::faceFlipMap().
faceFlipMap()
const labelList & faceFlipMap () const
Return face map with sign to encode flipped faces.
Definition at line 1504 of file fvMeshSubset.C.
References fvMeshSubset::cellMap(), fvMeshSubset::faceMap(), polyMesh::faceOwner(), primitiveMesh::nInternalFaces(), List< T >::size(), and fvMeshSubset::subMesh().
Referenced by fvMeshSubset::baseMesh(), and fvMeshDistribute::distribute().
cellMap()
const labelList & cellMap () const
Return cell map.
Definition at line 1542 of file fvMeshSubset.C.
Referenced by fvMeshSubset::baseMesh(), structuredDecomp::decompose(), fvMeshDistribute::distribute(), fvMeshSubset::faceFlipMap(), and structuredRenumber::renumber().
patchMap()
const labelList & patchMap () const
Return patch map.
Definition at line 1550 of file fvMeshSubset.C.
Referenced by fvMeshSubset::baseMesh(), and fvMeshDistribute::distribute().
interpolate() [1/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const fvMesh & sMesh, const labelList & patchMap, const labelList & cellMap, const labelList & faceMap) static
Map volume field.
Definition at line 43 of file fvMeshSubsetInterpolate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::null(), patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), GeometricField< Type, PatchField, GeoMesh >::ref(), List< T >::size(), fvPatch::size(), fvPatch::start(), fvMesh::time(), and Time::timeName().
Referenced by fvMeshSubset::baseMesh(), vtkMesh::interpolate(), fvMeshSubset::interpolate(), and fvMeshDistribute::printFieldInfo().
interpolate() [2/8]
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const
Definition at line 161 of file fvMeshSubsetInterpolate.C.
References Foam::faceMap(), Foam::interpolate(), and fvMeshSubset::interpolate().
interpolate() [3/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > & vf, const fvMesh & sMesh, const labelList & patchMap, const labelList & cellMap, const labelList & faceMap, const bool negateIfFlipped = true) static
Map surface field. Optionally negates value if flipping.
a face (from exposing an internal face)
Definition at line 178 of file fvMeshSubsetInterpolate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::faceMap(), forAll, GeometricField< Type, PatchField, GeoMesh >::internalField(), fvMeshSubset::interpolate(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), primitiveMesh::nInternalFaces(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::null(), fvPatch::patch(), patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), tmp< T >::ref(), List< T >::size(), fvPatch::size(), fvPatch::start(), fvMesh::time(), Time::timeName(), and polyPatch::whichFace().
interpolate() [4/8]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvsPatchField, surfaceMesh > & sf, const bool negateIfFlipped = true) const
Definition at line 344 of file fvMeshSubsetInterpolate.C.
References Foam::faceMap(), Foam::interpolate(), and fvMeshSubset::interpolate().
interpolate() [5/8]
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > & vf, const pointMesh & sMesh, const labelList & patchMap, const labelList & pointMap) static
Map point field.
Definition at line 364 of file fvMeshSubsetInterpolate.C.
References pointMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), HashTableCore::end(), HashTable< T, Key, Hash >::find(), forAll, fvMeshSubset::interpolate(), DimensionedField< Type, GeoMesh >::mesh(), pointPatch::meshPoints(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::null(), patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), GeometricField< Type, PatchField, GeoMesh >::ref(), List< T >::size(), pointPatch::size(), pointMesh::thisDb(), IOobject::time(), and Time::timeName().
interpolate() [6/8]
tmp< GeometricField< Type, pointPatchField, pointMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > & sf) const
Definition at line 494 of file fvMeshSubsetInterpolate.C.
References Foam::interpolate(), fvMeshSubset::interpolate(), and MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New().
interpolate() [7/8]
tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > & df, const fvMesh & sMesh, const labelList & cellMap) static
Map dimensioned field.
Definition at line 510 of file fvMeshSubsetInterpolate.C.
References DimensionedField< Type, GeoMesh >::dimensions(), fvMeshSubset::interpolate(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::time(), and Time::timeName().
interpolate() [8/8]
tmp< DimensionedField< Type, volMesh > > interpolate (const DimensionedField< Type, volMesh > & df) const
Definition at line 541 of file fvMeshSubsetInterpolate.C.
References Foam::interpolate().
The documentation for this class was generated from the following files:
src/dynamicMesh/fvMeshSubset/fvMeshSubset.H
src/dynamicMesh/fvMeshSubset/fvMeshSubset.C
src/dynamicMesh/fvMeshSubset/fvMeshSubsetInterpolate.C