OpenFOAM: multiDirRefinement Class Reference
multiDirRefinement Class Reference
Does multiple pass refinement to refine cells in multiple directions.
Public Member Functions
ClassName ("multiDirRefinement")
Runtime type information.
multiDirRefinement (polyMesh &mesh, const labelList &cellLabels, const dictionary &dict)
Construct from dictionary. After construction all refinement will.
multiDirRefinement (polyMesh &mesh, const labelList &cellLabels, const List< vectorField > &, const dictionary &dict)
Explicitly provided directions to split in.
multiDirRefinement (polyMesh &mesh, undoableMeshCutter &cutter, const cellLooper &cellCutter, const labelList &cellLabels, const List< vectorField > &directions, const bool writeMesh=false)
Construct from components. Only this one would allow undo actions.
const labelListList & addedCells () const
Access to addedCells (on the original mesh; see above)
Detailed Description
Does multiple pass refinement to refine cells in multiple directions.
Gets a list of cells to refine and vectorFields for the whole mesh. It then tries to refine in one direction after the other the wanted cells. After construction the mesh will have been refined in multiple directions.
Holds the list of cells to refine and the map from original to added for every refinement level.
Gets constructed from a dictionary or from components. Uses an undoableMeshCutter which does the actual cutting. Undo facility is switched of unless constructed from external one which allows this.
The cut cells get stored in addedCells which is for every vectorField to cut with the map from uncut to added cell (i.e. from master to slave). Note: map is only valid for a given direction.
Parallel: should be ok. Uses 'reduce' whenever it needs to make a local decision.
Source files
multiDirRefinement.H
multiDirRefinement.C
Definition at line 74 of file multiDirRefinement.H.
Constructor & Destructor Documentation
multiDirRefinement() [1/3]
multiDirRefinement (polyMesh & mesh, const labelList & cellLabels, const dictionary & dict)
Construct from dictionary. After construction all refinement will.
have been done (and runTime will have increased a few time steps if writeMesh = true)
Definition at line 483 of file multiDirRefinement.C.
References dictionary::lookup(), and Foam::reduce().
multiDirRefinement() [2/3]
multiDirRefinement (polyMesh & mesh, const labelList & cellLabels, const List< vectorField > & cellDirs, const dictionary & dict)
Explicitly provided directions to split in.
Definition at line 525 of file multiDirRefinement.C.
References dictionary::lookup(), and Foam::reduce().
multiDirRefinement() [3/3]
multiDirRefinement (polyMesh & mesh, undoableMeshCutter & cutter, const cellLooper & cellCutter, const labelList & cellLabels, const List< vectorField > & directions, const bool writeMesh = false)
Construct from components. Only this one would allow undo actions.
Definition at line 567 of file multiDirRefinement.C.
Member Function Documentation
ClassName()
ClassName ("multiDirRefinement")
Runtime type information.
addedCells()
const labelListList& addedCells () const inline
Access to addedCells (on the original mesh; see above)
Definition at line 190 of file multiDirRefinement.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/meshModifiers/multiDirRefinement/multiDirRefinement.H
src/dynamicMesh/meshCut/meshModifiers/multiDirRefinement/multiDirRefinement.C