OpenFOAM: combineFaces Class Reference
combineFaces Class Reference
Combines boundary faces into single face. The faces get the patch of the first face ('the master')
Public Member Functions
ClassName ("combineFaces")
Runtime type information.
combineFaces (const polyMesh &mesh, const bool undoable=false)
Construct from mesh.
const labelList & masterFace () const
If undoable: masterface for every set.
const labelList & savedPointLabels () const
If undoable: set of original point labels of stored points.
labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const labelHashSet &boundaryCells) const
Extract lists of all (non-coupled) boundary faces on selected.
labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos) const
Extract lists of all (non-coupled) boundary faces that can.
void setRefinement (const labelListList &, polyTopoChange &)
Play commands into polyTopoChange to combine faces. Gets.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
void setUnrefinement (const labelList &masterFaces, polyTopoChange &meshMod, Map< label > &restoredPoints, Map< label > &restoredFaces, Map< label > &restoredCells)
Play commands into polyTopoChange to reinsert original faces.
Static Public Member Functions
static face getOutsideFace (const indirectPrimitivePatch &)
Gets outside of patch as a face (in mesh point labels)
Detailed Description
Combines boundary faces into single face. The faces get the patch of the first face ('the master')
Source files
combineFaces.H
combineFaces.C
Definition at line 55 of file combineFaces.H.
Constructor & Destructor Documentation
combineFaces()
combineFaces (const polyMesh & mesh, const bool undoable = false)
Construct from mesh.
Definition at line 282 of file combineFaces.C.
References combineFaces::getMergeSets().
Member Function Documentation
ClassName()
ClassName ("combineFaces")
Runtime type information.
masterFace()
const labelList& masterFace () const inline
If undoable: masterface for every set.
Definition at line 140 of file combineFaces.H.
Referenced by meshRefinement::mergePatchFacesUndo().
savedPointLabels()
const labelList& savedPointLabels () const inline
If undoable: set of original point labels of stored points.
Definition at line 146 of file combineFaces.H.
References combineFaces::getMergeSets(), combineFaces::getOutsideFace(), combineFaces::setRefinement(), combineFaces::setUnrefinement(), and combineFaces::updateMesh().
Referenced by meshRefinement::mergePatchFacesUndo().
getMergeSets() [1/2]
Foam::labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const labelHashSet & boundaryCells) const
Extract lists of all (non-coupled) boundary faces on selected.
cells that can be merged. Uses getFaceRegions.
Definition at line 299 of file combineFaces.C.
References forAllConstIter(), List< T >::setSize(), List< T >::size(), and HashTable< T, Key, Hash >::size().
Referenced by combineFaces::combineFaces(), meshRefinement::mergePatchFacesUndo(), and combineFaces::savedPointLabels().
getMergeSets() [2/2]
Foam::labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos) const
Extract lists of all (non-coupled) boundary faces that can.
be merged. Uses getFaceRegions.
Definition at line 383 of file combineFaces.C.
References polyPatch::coupled(), forAll, combineFaces::getOutsideFace(), HashSet< Key, Hash >::insert(), patchi, and polyPatch::start().
getOutsideFace()
Foam::face getOutsideFace (const indirectPrimitivePatch & fp) static
Gets outside of patch as a face (in mesh point labels)
Definition at line 414 of file combineFaces.C.
References Foam::abort(), Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::edgeLoops(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), Foam::findIndex(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), face::nextLabel(), PrimitivePatch< Face, FaceList, PointField, PointType >::nInternalEdges(), Foam::renumber(), Foam::reverse(), combineFaces::setRefinement(), and List< T >::size().
Referenced by combineFaces::getMergeSets(), and combineFaces::savedPointLabels().
setRefinement()
void setRefinement (const labelListList & faceSets, polyTopoChange & meshMod)
Play commands into polyTopoChange to combine faces. Gets.
labelListList of sets of faces to combine. Does no check for whether resulting face is legal.
Definition at line 542 of file combineFaces.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, faceZone::flipMap(), forAll, HashTable< T, Key, Hash >::insert(), n, Foam::nl, patchi, polyTopoChange::setAction(), UIndirectList< T >::size(), List< T >::size(), syncTools::syncPointList(), faceZone::whichFace(), and polyBoundaryMesh::whichPatch().
Referenced by combineFaces::getOutsideFace(), meshRefinement::mergePatchFacesUndo(), and combineFaces::savedPointLabels().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Force recalculation of locally stored data on topological change.
Definition at line 767 of file combineFaces.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::inplaceRenumber(), Foam::nl, mapPolyMesh::reverseFaceMap(), mapPolyMesh::reversePointMap(), and combineFaces::setUnrefinement().
Referenced by meshRefinement::mergePatchFacesUndo(), and combineFaces::savedPointLabels().
setUnrefinement()
void setUnrefinement (const labelList & masterFaces, polyTopoChange & meshMod, Map< label > & restoredPoints, Map< label > & restoredFaces, Map< label > & restoredCells)
Play commands into polyTopoChange to reinsert original faces.
No other topo changes can be done inbetween setRefinement and setUnrefinement. Can be called multiple times to undo parts of the last setRefinement call. Gets the master face labels whose sets need to be restored. Returns maps from added restored point to original point label (i.e. content of savedPointLabels_). (only restoredPoints are actually set; rest are just for generalness)
Definition at line 816 of file combineFaces.C.
References Foam::abort(), UList< T >::empty(), HashTableCore::end(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), faceZone::flipMap(), forAll, HashTable< T, Key, Hash >::insert(), patchi, polyTopoChange::setAction(), List< T >::size(), and faceZone::whichFace().
Referenced by meshRefinement::mergePatchFacesUndo(), combineFaces::savedPointLabels(), and combineFaces::updateMesh().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/combineFaces.H
src/dynamicMesh/polyTopoChange/polyTopoChange/combineFaces.C