OpenFOAM: polyMeshFilter Class Reference
polyMeshFilter Class Reference
Remove the edges and faces of a polyMesh whilst satisfying the given mesh quality criteria.
Public Member Functions
ClassName ("polyMeshFilter")
Runtime type information.
polyMeshFilter (const fvMesh &mesh)
Construct from fvMesh.
polyMeshFilter (const fvMesh &mesh, const labelList &pointPriority)
Construct from fvMesh and a label list of point priorities.
polyMeshFilter (const fvMesh &mesh, const labelList &pointPriority, const dictionary &dict)
Construct from fvMesh and a label list of point priorities.
~polyMeshFilter ()
Destructor.
const autoPtr< fvMesh > & filteredMesh () const
Return reference to the filtered mesh. Does not check if the.
const autoPtr< labelList > & pointPriority () const
Return the new pointPriority list.
label filter (const label nOriginalBadFaces)
Filter edges and faces.
label filter (const faceSet &fSet)
Filter all faces that are in the face set.
label filterEdges (const label nOriginalBadFaces)
Filter edges only.
Static Public Member Functions
static autoPtr< fvMesh > copyMesh (const fvMesh &mesh)
Return a copy of an fvMesh.
static void copySets (const polyMesh &oldMesh, const polyMesh &newMesh)
Copy loaded topoSets from the old mesh to the new mesh.
static void updateSets (const mapPolyMesh &map)
Update the loaded topoSets.
Detailed Description
Remove the edges and faces of a polyMesh whilst satisfying the given mesh quality criteria.
Works on a copy of the mesh.
Source files
polyMeshFilter.H
polyMeshFilter.C
polyMeshFilterTemplates.C
Definition at line 62 of file polyMeshFilter.H.
Constructor & Destructor Documentation
polyMeshFilter() [1/3]
polyMeshFilter (const fvMesh & mesh) explicit
Construct from fvMesh.
Definition at line 892 of file polyMeshFilter.C.
References Foam::Info, and polyMeshFilterSettings::writeSettings().
polyMeshFilter() [2/3]
polyMeshFilter (const fvMesh & mesh, const labelList & pointPriority)
Construct from fvMesh and a label list of point priorities.
Definition at line 920 of file polyMeshFilter.C.
References Foam::Info, and polyMeshFilterSettings::writeSettings().
polyMeshFilter() [3/3]
polyMeshFilter (const fvMesh & mesh, const labelList & pointPriority, const dictionary & dict)
Construct from fvMesh and a label list of point priorities.
Definition at line 950 of file polyMeshFilter.C.
References Foam::Info, and polyMeshFilterSettings::writeSettings().
~polyMeshFilter()
~polyMeshFilter ()
Destructor.
Definition at line 970 of file polyMeshFilter.C.
Member Function Documentation
ClassName()
ClassName ("polyMeshFilter")
Runtime type information.
filteredMesh()
const Foam::autoPtr< Foam::fvMesh > & filteredMesh () const
Return reference to the filtered mesh. Does not check if the.
mesh has actually been filtered.
Definition at line 1125 of file polyMeshFilter.C.
pointPriority()
const Foam::autoPtr< Foam::labelList > & pointPriority () const
Return the new pointPriority list.
Definition at line 1132 of file polyMeshFilter.C.
copyMesh()
Foam::autoPtr< Foam::fvMesh > copyMesh (const fvMesh & mesh) static
Return a copy of an fvMesh.
Definition at line 67 of file polyMeshFilter.C.
References polyTopoChange::changeMesh(), edgeCollapser::checkMeshQuality(), collapseEdge(), Foam::decrIndent(), Foam::e, primitiveMesh::edges(), edge::end(), Foam::endl(), f(), Foam::faceMap(), mapPolyMesh::faceMap(), Pair< Type >::first(), fld(), forAll, mapPolyMesh::hasMotionPoints(), Foam::identity(), Foam::incrIndent(), Foam::indent(), Foam::Info, Foam::labelMax, Foam::labelMin, polyTopoChange::makeMesh(), Foam::max(), Foam::min(), polyMesh::movePoints(), fvMesh::name(), primitiveMesh::nEdges(), newPointi, primitiveMesh::nFaces(), Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, primitiveMesh::nPoints(), mapPolyMesh::pointMap(), mapPolyMesh::preMotionPoints(), Foam::reduce(), Foam::returnReduce(), mapPolyMesh::reversePointMap(), Pair< Type >::second(), List< T >::size(), edge::start(), Foam::sum(), syncTools::syncEdgeList(), syncTools::syncFaceList(), syncTools::syncPointList(), fvMesh::time(), List< T >::transfer(), and polyMesh::updateMesh().
Referenced by polyMeshFilter::filterEdges().
copySets()
void copySets (const polyMesh & oldMesh, const polyMesh & newMesh) static
Copy loaded topoSets from the old mesh to the new mesh.
Definition at line 56 of file polyMeshFilter.C.
updateSets()
void updateSets (const mapPolyMesh & map) static
Update the loaded topoSets.
Definition at line 47 of file polyMeshFilter.C.
filter() [1/2]
Foam::label filter (const label nOriginalBadFaces)
Filter edges and faces.
Definition at line 976 of file polyMeshFilter.C.
References polyMeshFilterSettings::initialFaceLengthFactor(), polyMeshFilterSettings::minLen(), primitiveMesh::nEdges(), primitiveMesh::nFaces(), and List< T >::resize().
filter() [2/2]
Foam::label filter (const faceSet & fSet)
Filter all faces that are in the face set.
Definition at line 985 of file polyMeshFilter.C.
References forAll, HashTable< T, Key, Hash >::found(), polyMeshFilterSettings::initialFaceLengthFactor(), polyMeshFilterSettings::minLen(), primitiveMesh::nEdges(), primitiveMesh::nFaces(), and List< T >::resize().
filterEdges()
Foam::label filterEdges (const label nOriginalBadFaces)
Filter edges only.
Definition at line 1003 of file polyMeshFilter.C.
References edgeCollapser::checkMeshQuality(), polyMeshFilterSettings::controlMeshQuality(), polyMeshFilter::copyMesh(), PackedList< nBits >::count(), Foam::decrIndent(), Foam::endl(), Foam::identity(), Foam::incrIndent(), Foam::indent(), Foam::Info, Foam::labelMax, polyMeshFilterSettings::maxIterations(), polyMeshFilterSettings::meshQualityCoeffDict(), polyMeshFilterSettings::minLen(), primitiveMesh::nEdges(), Foam::nl, primitiveMesh::nPoints(), List< T >::resize(), and Foam::returnReduce().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyMeshFilter/polyMeshFilter.H
src/dynamicMesh/polyMeshFilter/polyMeshFilter.C
src/dynamicMesh/polyMeshFilter/polyMeshFilterTemplates.C