OpenFOAM: polyMeshFilterSettings Class Reference
polyMeshFilterSettings Class Reference
Class to store the settings for the polyMeshFilter class.
Public Member Functions
polyMeshFilterSettings (const dictionary &dict)
Construct from dictionary.
~polyMeshFilterSettings ()
Destructor.
const dictionary & collapseEdgesCoeffDict () const
const dictionary & collapseFacesCoeffDict () const
const dictionary & meshQualityCoeffDict () const
const Switch & controlMeshQuality () const
const scalar & minLen () const
const scalar & maxCos () const
const scalar & edgeReductionFactor () const
const label & maxIterations () const
const label & maxSmoothIters () const
const scalar & initialFaceLengthFactor () const
const scalar & faceReductionFactor () const
const label & maxPointErrorCount () const
void writeSettings (Ostream &os) const
Write the settings to a stream.
Detailed Description
Class to store the settings for the polyMeshFilter class.
Source files
polyMeshFilterSettings.H
polyMeshFilterSettings.C
polyMeshFilterSettingsI.H
Definition at line 52 of file polyMeshFilterSettings.H.
Constructor & Destructor Documentation
polyMeshFilterSettings()
polyMeshFilterSettings (const dictionary & dict) explicit
Construct from dictionary.
Definition at line 31 of file polyMeshFilterSettings.C.
~polyMeshFilterSettings()
~polyMeshFilterSettings () inline
Destructor.
Definition at line 113 of file polyMeshFilterSettings.H.
References polyMeshFilterSettings::collapseEdgesCoeffDict(), polyMeshFilterSettings::collapseFacesCoeffDict(), polyMeshFilterSettings::controlMeshQuality(), polyMeshFilterSettings::edgeReductionFactor(), polyMeshFilterSettings::faceReductionFactor(), polyMeshFilterSettings::initialFaceLengthFactor(), polyMeshFilterSettings::maxCos(), polyMeshFilterSettings::maxIterations(), polyMeshFilterSettings::maxPointErrorCount(), polyMeshFilterSettings::maxSmoothIters(), polyMeshFilterSettings::meshQualityCoeffDict(), polyMeshFilterSettings::minLen(), and polyMeshFilterSettings::writeSettings().
Member Function Documentation
collapseEdgesCoeffDict()
const Foam::dictionary & collapseEdgesCoeffDict () const inline
Definition at line 29 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilterSettings::~polyMeshFilterSettings().
collapseFacesCoeffDict()
const Foam::dictionary & collapseFacesCoeffDict () const inline
Definition at line 35 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
meshQualityCoeffDict()
const Foam::dictionary & meshQualityCoeffDict () const inline
Definition at line 41 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilter::filterEdges(), and polyMeshFilterSettings::~polyMeshFilterSettings().
controlMeshQuality()
const Foam::Switch & controlMeshQuality () const inline
Definition at line 48 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilter::filterEdges(), polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
minLen()
const Foam::scalar & minLen () const inline
Definition at line 53 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilter::filter(), polyMeshFilter::filterEdges(), polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
maxCos()
const Foam::scalar & maxCos () const inline
Definition at line 58 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
edgeReductionFactor()
const Foam::scalar & edgeReductionFactor () const inline
Definition at line 64 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
maxIterations()
const Foam::label & maxIterations () const inline
Definition at line 69 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilter::filterEdges(), polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
maxSmoothIters()
const Foam::label & maxSmoothIters () const inline
Definition at line 74 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
initialFaceLengthFactor()
const Foam::scalar & initialFaceLengthFactor () const inline
Definition at line 80 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilter::filter(), polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
faceReductionFactor()
const Foam::scalar & faceReductionFactor () const inline
Definition at line 86 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
maxPointErrorCount()
const Foam::label & maxPointErrorCount () const inline
Definition at line 92 of file polyMeshFilterSettingsI.H.
Referenced by polyMeshFilterSettings::writeSettings(), and polyMeshFilterSettings::~polyMeshFilterSettings().
writeSettings()
void writeSettings (Ostream & os) const
Write the settings to a stream.
Definition at line 93 of file polyMeshFilterSettings.C.
References Foam::acos(), Switch::asText(), polyMeshFilterSettings::collapseFacesCoeffDict(), polyMeshFilterSettings::controlMeshQuality(), polyMeshFilterSettings::edgeReductionFactor(), Foam::endl(), polyMeshFilterSettings::faceReductionFactor(), polyMeshFilterSettings::initialFaceLengthFactor(), polyMeshFilterSettings::maxCos(), polyMeshFilterSettings::maxIterations(), polyMeshFilterSettings::maxPointErrorCount(), polyMeshFilterSettings::maxSmoothIters(), polyMeshFilterSettings::minLen(), Foam::nl, and Foam::radToDeg().
Referenced by polyMeshFilter::polyMeshFilter(), and polyMeshFilterSettings::~polyMeshFilterSettings().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyMeshFilter/polyMeshFilterSettings.H
src/dynamicMesh/polyMeshFilter/polyMeshFilterSettings.C
src/dynamicMesh/polyMeshFilter/polyMeshFilterSettingsI.H