OpenFOAM: polyModifyPoint Class Reference
polyModifyPoint Class Reference
Class describing modification of a point.
Public Member Functions
TypeName ("modifyPoint")
Runtime type information.
polyModifyPoint ()
Construct null. Used only for list construction.
polyModifyPoint (const label pointID, const point &newP, const bool removeFromZone, const label newZoneID, const bool inCell)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
label pointID () const
Point ID.
const point & newPoint () const
New point location.
bool isInZone () const
Does the point belong to a zone?
bool removeFromZone () const
Should the point be removed from current zone.
label zoneID () const
Point zone ID.
bool inCell () const
Does the point support a cell.
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()
Destructor.
Detailed Description
Class describing modification of a point.
Definition at line 47 of file polyModifyPoint.H.
Constructor & Destructor Documentation
polyModifyPoint() [1/2]
polyModifyPoint () inline
Construct null. Used only for list construction.
Definition at line 80 of file polyModifyPoint.H.
Referenced by polyModifyPoint::clone().
polyModifyPoint() [2/2]
polyModifyPoint (const label pointID, const point & newP, const bool removeFromZone, const label newZoneID, const bool inCell) inline
Construct from components.
Definition at line 91 of file polyModifyPoint.H.
Member Function Documentation
TypeName()
TypeName ("modifyPoint")
Runtime type information.
clone()
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 107 of file polyModifyPoint.H.
References polyModifyPoint::polyModifyPoint().
pointID()
label pointID () const inline
Point ID.
Definition at line 118 of file polyModifyPoint.H.
Referenced by polyTopoChange::setAction().
newPoint()
const point& newPoint () const inline
New point location.
Definition at line 124 of file polyModifyPoint.H.
Referenced by polyTopoChange::setAction().
isInZone()
bool isInZone () const inline
Does the point belong to a zone?
Definition at line 130 of file polyModifyPoint.H.
removeFromZone()
bool removeFromZone () const inline
Should the point be removed from current zone.
Definition at line 136 of file polyModifyPoint.H.
zoneID()
label zoneID () const inline
Point zone ID.
Definition at line 142 of file polyModifyPoint.H.
Referenced by polyTopoChange::setAction().
inCell()
bool inCell () const inline
Does the point support a cell.
Definition at line 148 of file polyModifyPoint.H.
Referenced by polyTopoChange::setAction().
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/modifyObject/polyModifyPoint.H