OpenFOAM: hexRef8Data Class Reference
hexRef8Data Class Reference
Various for reading/decomposing/reconstructing/distributing refinement data.
Public Member Functions
hexRef8Data (const IOobject &io)
Construct read. Has special provision for only some processors.
hexRef8Data (const IOobject &io, const hexRef8Data &, const labelList &cellMap, const labelList &pointMap)
Construct as subset.
hexRef8Data (const IOobject &io, const UPtrList< const labelList > &cellMaps, const UPtrList< const labelList > &pointMaps, const UPtrList< const hexRef8Data > &)
Construct from multiple hexRef8Data.
~hexRef8Data ()
Destructor.
void sync (const IOobject &io)
Parallel synchronise. This enforces valid objects on all processors.
void distribute (const mapDistributePolyMesh &)
In-place distribute.
bool write () const
Write.
Detailed Description
Various for reading/decomposing/reconstructing/distributing refinement data.
Source files
hexRef8Data.H
hexRef8Data.C
Definition at line 57 of file hexRef8Data.H.
Constructor & Destructor Documentation
hexRef8Data() [1/3]
hexRef8Data (const IOobject & io)
Construct read. Has special provision for only some processors.
having the files so can be used in redistribution.
Definition at line 39 of file hexRef8Data.C.
References Foam::endl(), IOobject::headerOk(), Foam::Info, IOobject::name(), IOobject::rename(), and Foam::returnReduce().
hexRef8Data() [2/3]
hexRef8Data (const IOobject & io, const hexRef8Data & data, const labelList & cellMap, const labelList & pointMap)
Construct as subset.
Definition at line 85 of file hexRef8Data.C.
References IOobject::rename().
hexRef8Data() [3/3]
hexRef8Data (const IOobject & io, const UPtrList< const labelList > & cellMaps, const UPtrList< const labelList > & pointMaps, const UPtrList< const hexRef8Data > & procDatas)
Construct from multiple hexRef8Data.
Definition at line 141 of file hexRef8Data.C.
References IOobject::db(), forAll, mesh, Foam::name(), primitiveMesh::nCells(), primitiveMesh::nPoints(), IOobject::rename(), and UPtrList< T >::size().
~hexRef8Data()
~hexRef8Data ()
Destructor.
Definition at line 232 of file hexRef8Data.C.
Member Function Documentation
sync()
void sync (const IOobject & io)
Parallel synchronise. This enforces valid objects on all processors.
(even if they don't have a mesh). Used by redistributePar.
Definition at line 238 of file hexRef8Data.C.
References IOobject::db(), Foam::dimLength, mesh, primitiveMesh::nCells(), IOobject::NO_READ, primitiveMesh::nPoints(), IOobject::readOpt(), IOobject::rename(), Foam::returnReduce(), and Pstream::scatter().
distribute()
void distribute (const mapDistributePolyMesh & map)
In-place distribute.
Definition at line 296 of file hexRef8Data.C.
References mapDistributePolyMesh::cellMap(), mapDistribute::distribute(), and mapDistributePolyMesh::pointMap().
write()
bool write () const
Write.
Definition at line 316 of file hexRef8Data.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8Data.H
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8Data.C