OpenFOAM: polyRemovePoint Class Reference
polyRemovePoint Class Reference
Class containing data for point removal.
Public Member Functions
TypeName ("removePoint")
Runtime type information.
polyRemovePoint ()
Construct null. Used for constructing lists.
polyRemovePoint (const label pointID, const label mergePointID=-1)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
label pointID () const
Return point ID.
label mergePointID () const
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()
Destructor.
Detailed Description
Class containing data for point removal.
Definition at line 46 of file polyRemovePoint.H.
Constructor & Destructor Documentation
polyRemovePoint() [1/2]
polyRemovePoint () inline
Construct null. Used for constructing lists.
Definition at line 70 of file polyRemovePoint.H.
Referenced by polyRemovePoint::clone().
polyRemovePoint() [2/2]
polyRemovePoint (const label pointID, const label mergePointID = -1) inline
Construct from components.
Definition at line 77 of file polyRemovePoint.H.
Member Function Documentation
TypeName()
TypeName ("removePoint")
Runtime type information.
clone()
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 84 of file polyRemovePoint.H.
References polyRemovePoint::polyRemovePoint().
pointID()
label pointID () const inline
Return point ID.
Definition at line 96 of file polyRemovePoint.H.
Referenced by polyTopoChange::setAction().
mergePointID()
label mergePointID () const inline
Definition at line 101 of file polyRemovePoint.H.
Referenced by polyTopoChange::setAction().
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/removeObject/polyRemovePoint.H