OpenFOAM: removeFaces Class Reference
removeFaces Class Reference
Given list of faces to remove insert all the topology changes. Contains helper function to get consistent set of faces to remove.
Public Member Functions
ClassName ("removeFaces")
Runtime type information.
removeFaces (const polyMesh &, const scalar minCos)
Construct from mesh and min cos of angle for boundary faces.
label compatibleRemoves (const labelList &inPiercedFaces, labelList &cellRegion, labelList &cellRegionMaster, labelList &outPiercedFaces) const
Find faces including those with cells which have the same mastercell.
void setRefinement (const labelList &piercedFaces, const labelList &cellRegion, const labelList &cellRegionMaster, polyTopoChange &) const
Play commands into polyTopoChange to remove faces.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
void distribute (const mapDistributePolyMesh &)
Force recalculation of locally stored data for mesh distribution.
Detailed Description
Given list of faces to remove insert all the topology changes. Contains helper function to get consistent set of faces to remove.
Not very well tested in parallel.
Source files
removeFaces.H
removeFaces.C
Definition at line 62 of file removeFaces.H.
Constructor & Destructor Documentation
removeFaces()
removeFaces (const polyMesh & mesh, const scalar minCos)
Construct from mesh and min cos of angle for boundary faces.
to be considered aligned. Set to >= 1 to disable checking and always merge (if on same patch)
Definition at line 562 of file removeFaces.C.
References removeFaces::compatibleRemoves().
Member Function Documentation
ClassName()
ClassName ("removeFaces")
Runtime type information.
compatibleRemoves()
Foam::label compatibleRemoves (const labelList & inPiercedFaces, labelList & cellRegion, labelList & cellRegionMaster, labelList & outPiercedFaces) const
Find faces including those with cells which have the same mastercell.
Given set of faces to pierce calculates:
region for connected cells
mastercell for each region. This is the lowest numbered cell of all cells that get merged.
new set of faces which contains input set + additional ones where cells on both sides would have same mastercell. Returns number of regions.
Definition at line 581 of file removeFaces.C.
References Foam::abort(), List< T >::append(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::min(), removeFaces::setRefinement(), List< T >::setSize(), List< T >::size(), and List< T >::transfer().
Referenced by removeFaces::removeFaces(), and hexRef8::setUnrefinement().
setRefinement()
void setRefinement (const labelList & piercedFaces, const labelList & cellRegion, const labelList & cellRegionMaster, polyTopoChange & meshMod) const
Play commands into polyTopoChange to remove faces.
Definition at line 762 of file removeFaces.C.
References Foam::abort(), Foam::e, Foam::endl(), f(), f1, PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIter(), Foam::invertOneToMany(), Foam::labelI, Foam::labelMin, Foam::mag(), OSstream::name(), IOobject::name(), Foam::nl, patches, Foam::Pout, polyTopoChange::setAction(), List< T >::size(), polyPatch::start(), syncTools::swapFaceList(), syncTools::syncEdgeList(), syncTools::syncPointList(), WarningInFunction, polyBoundaryMesh::whichPatch(), regIOobject::write(), and Foam::meshTools::writeOBJ().
Referenced by removeFaces::compatibleRemoves(), and hexRef8::setUnrefinement().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Force recalculation of locally stored data on topological change.
Definition at line 207 of file removeFaces.H.
Referenced by hexRef8::updateMesh().
distribute()
void distribute (const mapDistributePolyMesh &) inline
Force recalculation of locally stored data for mesh distribution.
Definition at line 211 of file removeFaces.H.
Referenced by hexRef8::distribute().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/removeFaces.H
src/dynamicMesh/polyTopoChange/polyTopoChange/removeFaces.C