OpenFOAM: faceEqOp< T, CombineOp > Class Template Reference
faceEqOp< T, CombineOp > Class Template Reference
Public Member Functions
void operator() (List< T > &x, const List< T > &y) const
Detailed Description
template<class T, template< class > class CombineOp>
class Foam::faceEqOp< T, CombineOp >
Definition at line 48 of file removePoints.C.
Member Function Documentation
operator()()
void operator() (List< T > & x, const List< T > & y) const inline
Definition at line 53 of file removePoints.C.
References faceZone::flipMap(), forAll, patchi, UList< T >::rcIndex(), polyTopoChange::setAction(), List< T >::size(), faceZone::whichFace(), and y.
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/removePoints.C