OpenFOAM: refinementHistory Class Reference
refinementHistory Class Reference
All refinement history. Used in unrefinement.
Classes
class splitCell8
Public Member Functions
TypeName ("refinementHistory")
refinementHistory (const IOobject &)
Construct (read) given an IOobject. If global number of visible.
refinementHistory (const IOobject &, const List< splitCell8 > &splitCells, const labelList &visibleCells, const bool active)
Construct (read) or construct from components.
refinementHistory (const IOobject &, const label nCells)
Construct (read) or construct from initial number of cells.
refinementHistory (const IOobject &, const label nCells, const bool active)
Construct (read) or construct from initial number of cells.
refinementHistory (const IOobject &, const refinementHistory &)
Construct as copy.
refinementHistory (const IOobject &, const UPtrList< const labelList > &cellMaps, const UPtrList< const refinementHistory > &)
Construct from multiple refinement histories. If global number of.
refinementHistory (const IOobject &, Istream &)
Construct from Istream. If global number of.
const labelList & visibleCells () const
Per cell in the current mesh (i.e. visible) either -1 (unrefined)
const DynamicList< splitCell8 > & splitCells () const
Storage for splitCell8s.
const DynamicList< label > & freeSplitCells () const
Cache of unused indices in splitCells.
bool active () const
Is there unrefinement history?
bool & active ()
Is there unrefinement history?
label parentIndex (const label celli) const
Get parent of cell.
void storeSplit (const label celli, const labelList &addedCells)
Store splitting of cell into 8.
void combineCells (const label masterCelli, const labelList &combinedCells)
Store combining 8 cells into master.
autoPtr< refinementHistory > clone (const IOobject &io, const labelList &decomposition, const labelList &splitCellProc, const labelList &splitCellNum, const label procI, labelList &oldToNewSplit) const
Low level clone.
autoPtr< refinementHistory > clone (const IOobject &io, const labelList &cellMap) const
Create clone from subset.
void updateMesh (const mapPolyMesh &)
Update numbering for mesh changes.
void subset (const labelList &pointMap, const labelList &faceMap, const labelList &cellMap)
Update numbering for subsetting.
void distribute (const mapDistributePolyMesh &)
Update local numbering for mesh redistribution.
void compact ()
Compact splitCells_. Removes all freeSplitCells_ elements.
void resize (const label nCells)
Extend/shrink storage. additional visibleCells_ elements get.
void writeDebug () const
Debug write.
virtual bool read ()
Read object. If global number of visible cells > 0 becomes active.
virtual bool readData (Istream &)
ReadData function required for regIOobject read operation. Note:
virtual bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void add (boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
Add my decomposition constraints.
void apply (const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &decomposition) const
Apply any additional post-decomposition constraints.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Friends
Istream & operator>> (Istream &, refinementHistory &)
Istream operator. Note: does not do a reduction - does not set.
Ostream & operator<< (Ostream &, const refinementHistory &)
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
All refinement history. Used in unrefinement.
- visibleCells: valid for the current mesh and contains per cell -1 (cell unrefined) or an index into splitCells_.
splitCells: for every split contains the parent (also index into splitCells) and optionally a subsplit as 8 indices into splitCells. Note that the numbers in splitCells are not cell labels, they are purely indices into splitCells.
E.g. 2 cells, cell 1 gets refined so end up with 9 cells:
    // splitCells
    9
    (
    -1 (1 2 3 4 5 6 7 8)
    0 0()
    0 0()
    0 0()
    0 0()
    0 0()
    0 0()
    0 0()
    0 0()
    )
    // visibleCells
    9(-1 1 2 3 4 5 6 7 8)
So cell0 (visibleCells=-1) is unrefined. Cells 1-8 have all valid splitCells entries which are:
parent:0
subsplits:0()
The parent 0 refers back to the splitcell entries.
Source files
refinementHistory.H
refinementHistory.C
Definition at line 103 of file refinementHistory.H.
Constructor & Destructor Documentation
refinementHistory() [1/7]
refinementHistory (const IOobject & io)
Construct (read) given an IOobject. If global number of visible.
cells > 0 becomes active
Definition at line 557 of file refinementHistory.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, Foam::Pout, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), Foam::returnReduce(), List< T >::size(), and WarningInFunction.
Referenced by refinementHistory::clone(), and refinementHistory::refinementHistory().
refinementHistory() [2/7]
refinementHistory (const IOobject & io, const List< splitCell8 > & splitCells, const labelList & visibleCells, const bool active)
Construct (read) or construct from components.
Definition at line 600 of file refinementHistory.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, Foam::Pout, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), refinementHistory::refinementHistory(), List< T >::size(), and WarningInFunction.
refinementHistory() [3/7]
refinementHistory (const IOobject & io, const label nCells)
Construct (read) or construct from initial number of cells.
(all visible). If global number of visible cells > 0 becomes active
Definition at line 649 of file refinementHistory.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, Foam::Pout, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), refinementHistory::refinementHistory(), Foam::returnReduce(), List< T >::setSize(), List< T >::size(), and WarningInFunction.
refinementHistory() [4/7]
refinementHistory (const IOobject & io, const label nCells, const bool active)
Construct (read) or construct from initial number of cells.
(all visible) and active flag
Definition at line 709 of file refinementHistory.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, Foam::Pout, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), refinementHistory::refinementHistory(), List< T >::setSize(), List< T >::size(), and WarningInFunction.
refinementHistory() [5/7]
refinementHistory (const IOobject & io, const refinementHistory & rh)
Construct as copy.
Definition at line 767 of file refinementHistory.C.
References Foam::endl(), Foam::Pout, and refinementHistory::refinementHistory().
refinementHistory() [6/7]
refinementHistory (const IOobject & io, const UPtrList< const labelList > & cellMaps, const UPtrList< const refinementHistory > & refs)
Construct from multiple refinement histories. If global number of.
visible cells > 0 becomes active
Definition at line 788 of file refinementHistory.C.
References refinementHistory::active(), refinementHistory::splitCell8::addedCellsPtr_, IOobject::db(), Foam::endl(), forAll, IOobject::headerOk(), mesh, IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, primitiveMesh::nCells(), refinementHistory::splitCell8::parent_, Foam::Pout, IOobject::READ_IF_PRESENT, IOobject::readOpt(), List< T >::setSize(), List< T >::size(), UPtrList< T >::size(), and WarningIn.
refinementHistory() [7/7]
refinementHistory (const IOobject & io, Istream & is)
Construct from Istream. If global number of.
visible cells > 0 becomes active
Definition at line 907 of file refinementHistory.C.
References IOobject::clone(), Foam::endl(), Foam::Pout, Foam::returnReduce(), and List< T >::size().
Member Function Documentation
TypeName()
TypeName ("refinementHistory")
visibleCells()
const labelList& visibleCells () const inline
Per cell in the current mesh (i.e. visible) either -1 (unrefined)
or an index into splitCells.
Definition at line 268 of file refinementHistory.H.
Referenced by hexRef8::getSplitPoints(), and hexRef8::hexRef8().
splitCells()
const DynamicList<splitCell8>& splitCells () const inline
Storage for splitCell8s.
Definition at line 274 of file refinementHistory.H.
freeSplitCells()
const DynamicList<label>& freeSplitCells () const inline
Cache of unused indices in splitCells.
Definition at line 280 of file refinementHistory.H.
active() [1/2]
bool active () const inline
Is there unrefinement history?
Definition at line 286 of file refinementHistory.H.
Referenced by refinementHistoryConstraint::add(), refinementHistoryConstraint::apply(), refinementHistory::distribute(), hexRef8::distribute(), hexRef8::getSplitPoints(), hexRef8::hexRef8(), refinementHistory::refinementHistory(), hexRef8::setRefinement(), hexRef8::setUnrefinement(), refinementHistory::subset(), hexRef8::subset(), refinementHistory::updateMesh(), hexRef8::updateMesh(), and hexRef8::write().
active() [2/2]
bool& active () inline
Is there unrefinement history?
Definition at line 292 of file refinementHistory.H.
parentIndex()
label parentIndex (const label celli) const inline
Get parent of cell.
Definition at line 298 of file refinementHistory.H.
References Foam::abort(), refinementHistory::add(), refinementHistory::apply(), IOobject::clone(), refinementHistory::combineCells(), refinementHistory::compact(), refinementHistory::distribute(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, refinementHistory::splitCell8::operator<<, refinementHistory::splitCell8::operator>>, refinementHistory::read(), refinementHistory::readData(), refinementHistory::resize(), refinementHistory::storeSplit(), refinementHistory::subset(), refinementHistory::updateMesh(), refinementHistory::writeData(), and refinementHistory::writeDebug().
Referenced by refinementHistory::combineCells(), hexRef8::getSplitPoints(), and refinementHistory::storeSplit().
storeSplit()
void storeSplit (const label celli, const labelList & addedCells)
Store splitting of cell into 8.
Definition at line 1679 of file refinementHistory.C.
References refinementHistory::combineCells(), forAll, and refinementHistory::parentIndex().
Referenced by refinementHistory::parentIndex(), hexRef8::setRefinement(), and refinementHistory::writeDebug().
combineCells()
void combineCells (const label masterCelli, const labelList & combinedCells)
Store combining 8 cells into master.
Definition at line 1717 of file refinementHistory.C.
References refinementHistory::splitCell8::addedCellsPtr_, forAll, and refinementHistory::parentIndex().
Referenced by refinementHistory::parentIndex(), hexRef8::setUnrefinement(), and refinementHistory::storeSplit().
clone() [1/2]
Foam::autoPtr< Foam::refinementHistory > clone (const IOobject & io, const labelList & decomposition, const labelList & splitCellProc, const labelList & splitCellNum, const label procI, labelList & oldToNewSplit) const
Low level clone.
Definition at line 933 of file refinementHistory.C.
References refinementHistory::splitCell8::addedCellsPtr_, DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), IOobject::clone(), forAll, refinementHistory::splitCell8::parent_, refinementHistory::refinementHistory(), List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), and List< T >::size().
clone() [2/2]
Foam::autoPtr< Foam::refinementHistory > clone (const IOobject & io, const labelList & cellMap) const
Create clone from subset.
Definition at line 1054 of file refinementHistory.C.
References IOobject::clone(), forAll, refinementHistory::refinementHistory(), and List< T >::size().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Update numbering for mesh changes.
Definition at line 1138 of file refinementHistory.C.
References Foam::abort(), refinementHistory::active(), mapPolyMesh::cellMap(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, mapPolyMesh::reverseCellMap(), List< T >::size(), refinementHistory::subset(), and List< T >::transfer().
Referenced by refinementHistory::parentIndex(), and hexRef8::updateMesh().
subset()
void subset (const labelList & pointMap, const labelList & faceMap, const labelList & cellMap)
Update numbering for subsetting.
Definition at line 1185 of file refinementHistory.C.
References Foam::abort(), refinementHistory::active(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), Foam::Pout, List< T >::size(), and List< T >::transfer().
Referenced by refinementHistory::parentIndex(), hexRef8::subset(), and refinementHistory::updateMesh().
distribute()
void distribute (const mapDistributePolyMesh & map)
Update local numbering for mesh redistribution.
Can only distribute clusters sent across in one go; cannot handle parts recombined in multiple passes.
Definition at line 1266 of file refinementHistory.C.
References Foam::abort(), refinementHistory::active(), refinementHistory::splitCell8::addedCellsPtr_, DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), UPstream::blocking, mapDistributePolyMesh::cellMap(), refinementHistory::compact(), mapDistributeBase::constructMap(), IOobject::db(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, primitiveMesh::nCells(), UPstream::nProcs(), refinementHistory::splitCell8::parent_, UPstream::parRun(), List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), List< T >::size(), and mapDistributeBase::subMap().
Referenced by hexRef8::distribute(), and refinementHistory::parentIndex().
compact()
void compact ()
Compact splitCells_. Removes all freeSplitCells_ elements.
Definition at line 1516 of file refinementHistory.C.
References Foam::abort(), refinementHistory::splitCell8::addedCellsPtr_, DynamicList< T, SizeInc, SizeMult, SizeDiv >::clearStorage(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, refinementHistory::splitCell8::parent_, Foam::Pout, and List< T >::size().
Referenced by refinementHistory::distribute(), Foam::operator<<(), and refinementHistory::parentIndex().
resize()
void resize (const label nCells)
Extend/shrink storage. additional visibleCells_ elements get.
set to -1.
Definition at line 1118 of file refinementHistory.C.
References Foam::endl(), Foam::Pout, List< T >::setSize(), and List< T >::size().
Referenced by refinementHistory::parentIndex(), and hexRef8::setRefinement().
writeDebug()
void writeDebug () const
Debug write.
Definition at line 1672 of file refinementHistory.C.
References refinementHistory::storeSplit().
Referenced by refinementHistory::parentIndex().
read()
bool read () virtual
Read object. If global number of visible cells > 0 becomes active.
Reimplemented from regIOobject.
Definition at line 1740 of file refinementHistory.C.
References regIOobject::close(), refinementHistory::readData(), regIOobject::readStream(), Foam::returnReduce(), and List< T >::size().
Referenced by hexRef8::hexRef8(), and refinementHistory::parentIndex().
readData()
bool readData (Istream & is) virtual
ReadData function required for regIOobject read operation. Note:
does not do a reduction - does not set active_ flag
Reimplemented from regIOobject.
Definition at line 1751 of file refinementHistory.C.
References IOstream::bad().
Referenced by refinementHistory::parentIndex(), and refinementHistory::read().
writeData()
bool writeData (Ostream & os) const virtual
WriteData function required for regIOobject write operation.
Implements regIOobject.
Definition at line 1758 of file refinementHistory.C.
References IOstream::good().
Referenced by refinementHistory::parentIndex().
add()
void add (boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const
Add my decomposition constraints.
Definition at line 451 of file refinementHistory.C.
References refinementHistory::apply(), IOobject::db(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::Info, mesh, primitiveMesh::nFaces(), Foam::reduce(), List< T >::setSize(), syncTools::syncFaceList(), and Foam::type().
Referenced by refinementHistoryConstraint::add(), Foam::operator<<(), and refinementHistory::parentIndex().
apply()
void apply (const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & decomposition) const
Apply any additional post-decomposition constraints.
Definition at line 497 of file refinementHistory.C.
References IOobject::db(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::Info, mesh, Foam::reduce(), and Foam::type().
Referenced by refinementHistory::add(), refinementHistoryConstraint::apply(), and refinementHistory::parentIndex().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , refinementHistory &) friend
Istream operator. Note: does not do a reduction - does not set.
active_ flag
operator<<
Ostream& operator<< (Ostream & , const refinementHistory &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/refinementHistory.H
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/refinementHistory.C