OpenFOAM: polyTopoChanger Class Reference
polyTopoChanger Class Reference
List of mesh modifiers defining the mesh dynamics.
Public Member Functions
TypeName ("polyTopoChanger")
Runtime type information.
polyTopoChanger (const IOobject &, polyMesh &)
Read constructor given IOobject and a polyMesh.
polyTopoChanger (polyMesh &)
Read constructor for given polyMesh.
virtual ~polyTopoChanger ()
Destructor.
const polyMesh & mesh () const
Return the mesh reference.
wordList types () const
Return a list of patch types.
wordList names () const
Return a list of patch names.
bool changeTopology () const
Is topology change required.
autoPtr< polyTopoChange > topoChangeRequest () const
Return topology change request.
void modifyMotionPoints (pointField &) const
Modify point motion.
autoPtr< mapPolyMesh > changeMesh (const bool inflate, const bool syncParallel=true, const bool orderCells=false, const bool orderPoints=false)
void update (const mapPolyMesh &m)
Force recalculation of locally stored data on topological change.
void addTopologyModifiers (const List< polyMeshModifier *> &tm)
Add given set of topology modifiers to the topoChanger.
label findModifierID (const word &modName) const
Find modifier given a name.
bool writeData (Ostream &) const
writeData member function required by regIOobject
bool operator!= (const polyTopoChanger &) const
bool operator== (const polyTopoChanger &) const
Public Member Functions inherited from PtrList< polyMeshModifier >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< polyMeshModifier > &)
Copy constructor.
PtrList (const PtrList< polyMeshModifier > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< polyMeshModifier >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< polyMeshModifier > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< polyMeshModifier > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (polyMeshModifier *)
Append an element at the end of the list.
void append (const autoPtr< polyMeshModifier > &)
void append (const tmp< polyMeshModifier > &)
void transfer (PtrList< polyMeshModifier > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< polyMeshModifier > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< polyMeshModifier > set (const label, polyMeshModifier *)
Set element to given T* and return old element (can be nullptr)
autoPtr< polyMeshModifier > set (const label, const autoPtr< polyMeshModifier > &)
Set element to given autoPtr<T> and return old element.
autoPtr< polyMeshModifier > set (const label, const tmp< polyMeshModifier > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< polyMeshModifier > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Protected Attributes
polyMesh & mesh_
Reference to mesh.
Friends
Ostream & operator<< (Ostream &, const polyTopoChanger &)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from PtrList< polyMeshModifier >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
List of mesh modifiers defining the mesh dynamics.
Source files
polyTopoChanger.H
polyTopoChanger.C
Definition at line 64 of file polyTopoChanger.H.
Constructor & Destructor Documentation
polyTopoChanger() [1/2]
polyTopoChanger (const IOobject & io, polyMesh & mesh)
Read constructor given IOobject and a polyMesh.
Definition at line 91 of file polyTopoChanger.C.
polyTopoChanger() [2/2]
polyTopoChanger (polyMesh & mesh) explicit
Read constructor for given polyMesh.
Definition at line 104 of file polyTopoChanger.C.
~polyTopoChanger()
virtual ~polyTopoChanger () inline virtual
Destructor.
Definition at line 103 of file polyTopoChanger.H.
Member Function Documentation
TypeName()
TypeName ("polyTopoChanger")
Runtime type information.
mesh()
const polyMesh& mesh () const inline
Return the mesh reference.
Definition at line 110 of file polyTopoChanger.H.
References polyTopoChanger::addTopologyModifiers(), polyTopoChanger::changeMesh(), polyTopoChanger::changeTopology(), polyTopoChanger::findModifierID(), polyTopoChanger::mesh_, polyTopoChanger::modifyMotionPoints(), polyTopoChanger::names(), polyTopoChanger::operator!=(), polyTopoChanger::operator<<, polyTopoChanger::operator==(), polyTopoChanger::topoChangeRequest(), polyTopoChanger::types(), polyTopoChanger::update(), and polyTopoChanger::writeData().
Referenced by polyTopoChanger::topoChangeRequest().
types()
Foam::wordList types () const
Return a list of patch types.
Definition at line 130 of file polyTopoChanger.C.
References forAll, and UPtrList< T >::size().
Referenced by polyTopoChanger::mesh().
names()
Foam::wordList names () const
Return a list of patch names.
Definition at line 145 of file polyTopoChanger.C.
References forAll, and UPtrList< T >::size().
Referenced by polyTopoChanger::findModifierID(), and polyTopoChanger::mesh().
changeTopology()
bool changeTopology () const
Is topology change required.
Definition at line 160 of file polyTopoChanger.C.
References Foam::endl(), forAll, and Foam::Info.
Referenced by polyTopoChanger::changeMesh(), and polyTopoChanger::mesh().
topoChangeRequest()
Foam::autoPtr< Foam::polyTopoChange > topoChangeRequest () const
Return topology change request.
Definition at line 206 of file polyTopoChanger.C.
References forAll, polyTopoChanger::mesh(), and ref().
Referenced by polyTopoChanger::changeMesh(), and polyTopoChanger::mesh().
modifyMotionPoints()
void modifyMotionPoints (pointField & p) const
Modify point motion.
Definition at line 226 of file polyTopoChanger.C.
References forAll.
Referenced by polyTopoChanger::mesh(), and rawTopoChangerFvMesh::update().
changeMesh()
Foam::autoPtr< Foam::mapPolyMesh > changeMesh (const bool inflate, const bool syncParallel = true, const bool orderCells = false, const bool orderPoints = false)
Definition at line 259 of file polyTopoChanger.C.
References polyTopoChanger::addTopologyModifiers(), polyTopoChanger::changeTopology(), polyTopoChanger::mesh_, ref(), polyTopoChanger::topoChangeRequest(), polyTopoChanger::update(), and polyMesh::updateMesh().
Referenced by attachPolyTopoChanger::attach(), polyTopoChanger::mesh(), rawTopoChangerFvMesh::update(), movingConeTopoFvMesh::update(), and polyTopoChanger::update().
update()
void update (const mapPolyMesh & m)
Force recalculation of locally stored data on topological change.
Definition at line 240 of file polyTopoChanger.C.
References IOobject::AUTO_WRITE, polyTopoChanger::changeMesh(), forAll, IOobject::instance(), polyTopoChanger::mesh_, objectRegistry::time(), Time::timeName(), and IOobject::writeOpt().
Referenced by polyTopoChanger::changeMesh(), and polyTopoChanger::mesh().
addTopologyModifiers()
void addTopologyModifiers (const List< polyMeshModifier *> & tm)
Add given set of topology modifiers to the topoChanger.
Definition at line 291 of file polyTopoChanger.C.
References Foam::abort(), IOobject::AUTO_WRITE, Foam::FatalError, FatalErrorInFunction, polyTopoChanger::findModifierID(), forAll, PtrList< polyMeshModifier >::setSize(), List< T >::size(), and IOobject::writeOpt().
Referenced by polyTopoChanger::changeMesh(), and polyTopoChanger::mesh().
findModifierID()
Foam::label findModifierID (const word & modName) const
Find modifier given a name.
Definition at line 314 of file polyTopoChanger.C.
References Foam::endl(), forAll, IOobject::name(), polyTopoChanger::names(), and WarningInFunction.
Referenced by polyTopoChanger::addTopologyModifiers(), and polyTopoChanger::mesh().
writeData()
bool writeData (Ostream & os) const virtual
writeData member function required by regIOobject
Implements regIOobject.
Definition at line 340 of file polyTopoChanger.C.
References IOstream::good().
Referenced by polyTopoChanger::mesh().
operator!=()
bool operator!= (const polyTopoChanger & me) const
Definition at line 349 of file polyTopoChanger.C.
Referenced by polyTopoChanger::mesh().
operator==()
bool operator== (const polyTopoChanger & me) const
Definition at line 355 of file polyTopoChanger.C.
Referenced by polyTopoChanger::mesh().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const polyTopoChanger &) friend
Referenced by polyTopoChanger::mesh().
Member Data Documentation
mesh_
polyMesh& mesh_ protected
Reference to mesh.
Definition at line 85 of file polyTopoChanger.H.
Referenced by attachPolyTopoChanger::attach(), polyTopoChanger::changeMesh(), polyTopoChanger::mesh(), and polyTopoChanger::update().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChanger/polyTopoChanger.H
src/dynamicMesh/polyTopoChange/polyTopoChanger/polyTopoChanger.C