OpenFOAM: removeCells Class Reference
removeCells Class Reference
Given list of cells to remove insert all the topology changes.
Public Member Functions
ClassName ("removeCells")
Runtime type information.
removeCells (const polyMesh &mesh, const bool syncPar=true)
Construct from mesh. syncPar: do parallel synchronization.
labelList getExposedFaces (const labelList &cellsToRemove) const
Get labels of exposed faces.
void setRefinement (const labelList &cellsToRemove, const labelList &facesToExpose, const labelList &patchIDs, polyTopoChange &) const
Play commands into polyTopoChange to remove cells.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
Detailed Description
Given list of cells to remove insert all the topology changes.
Works in two passes:
get faces that will become boundary faces
given these faces and the patches they have to go into make the changes.
Source files
removeCells.H
removeCells.C
Definition at line 59 of file removeCells.H.
Constructor & Destructor Documentation
removeCells()
removeCells (const polyMesh & mesh, const bool syncPar = true)
Construct from mesh. syncPar: do parallel synchronization.
Definition at line 60 of file removeCells.C.
References removeCells::getExposedFaces().
Member Function Documentation
ClassName()
ClassName ("removeCells")
Runtime type information.
getExposedFaces()
Foam::labelList getExposedFaces (const labelList & cellsToRemove) const
Get labels of exposed faces.
These are
internal faces that become boundary faces
coupled faces that become uncoupled (since one of the sides gets deleted)
Definition at line 73 of file removeCells.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), List< T >::append(), polyPatch::coupled(), forAll, patches, patchi, removeCells::setRefinement(), polyPatch::start(), and syncTools::syncFaceList().
Referenced by fvMeshSubset::getExposedFaces(), fvMeshDistribute::printCoupleInfo(), removeCells::removeCells(), meshRefinement::splitMesh(), and meshRefinement::splitMeshRegions().
setRefinement()
void setRefinement (const labelList & cellsToRemove, const labelList & facesToExpose, const labelList & patchIDs, polyTopoChange & meshMod) const
Play commands into polyTopoChange to remove cells.
patchIDs is for every element in facesToExpose (see above) the patch it has to go into. This cannot be a coupled patch!
Definition at line 179 of file removeCells.C.
References Foam::abort(), polyPatch::coupled(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, faceZone::flipMap(), forAll, IOobject::name(), Foam::nl, patches, patchi, face::reverseFace(), polyTopoChange::setAction(), List< T >::size(), UPtrList< T >::size(), polyPatch::start(), WarningInFunction, faceZone::whichFace(), and ZoneMesh< ZoneType, MeshType >::whichZone().
Referenced by removeCells::getExposedFaces(), fvMeshDistribute::printCoupleInfo(), meshRefinement::setInstance(), and fvMeshSubset::setLargeCellSubset().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Force recalculation of locally stored data on topological change.
Definition at line 115 of file removeCells.H.
Referenced by meshRefinement::setInstance().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/removeCells.H
src/dynamicMesh/polyTopoChange/polyTopoChange/removeCells.C