OpenFOAM: tetDecomposer Class Reference
tetDecomposer Class Reference
Decomposes polyMesh into tets.
Public Types
enum decompositionType { FACE_CENTRE_TRIS, FACE_DIAG_TRIS }
Public Member Functions
ClassName ("tetDecomposer")
Runtime type information.
tetDecomposer (const polyMesh &)
Construct from mesh.
const labelList & cellToPoint () const
From cell to tet point.
const labelList & faceToPoint () const
From face to tet point.
const labelListList & faceOwnerCells () const
Per face, per point (faceCentre) or triangle (faceDiag)
const labelListList & faceNeighbourCells () const
Per face, per point (faceCentre) or triangle (faceDiag)
void setRefinement (const decompositionType decomposeType, polyTopoChange &meshMod)
Insert all changes into meshMod to convert the polyMesh into.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
Static Public Attributes
static const NamedEnum< decompositionType, 2 > decompositionTypeNames
Detailed Description
Decomposes polyMesh into tets.
Source files
tetDecomposer.H
tetDecomposer.C
Definition at line 57 of file tetDecomposer.H.
Member Enumeration Documentation
decompositionType
enum decompositionType
Enumerator
FACE_CENTRE_TRIS
FACE_DIAG_TRIS
Definition at line 63 of file tetDecomposer.H.
Constructor & Destructor Documentation
tetDecomposer()
tetDecomposer (const polyMesh & mesh)
Construct from mesh.
Definition at line 174 of file tetDecomposer.C.
References tetDecomposer::setRefinement().
Member Function Documentation
ClassName()
ClassName ("tetDecomposer")
Runtime type information.
cellToPoint()
const labelList& cellToPoint () const inline
From cell to tet point.
Definition at line 152 of file tetDecomposer.H.
faceToPoint()
const labelList& faceToPoint () const inline
From face to tet point.
Definition at line 158 of file tetDecomposer.H.
References tetDecomposer::faceNeighbourCells(), tetDecomposer::faceOwnerCells(), tetDecomposer::setRefinement(), and tetDecomposer::updateMesh().
faceOwnerCells()
const labelListList& faceOwnerCells () const inline
Per face, per point (faceCentre) or triangle (faceDiag)
the added tet on the owner side
Definition at line 166 of file tetDecomposer.H.
Referenced by tetDecomposer::faceToPoint().
faceNeighbourCells()
const labelListList& faceNeighbourCells () const inline
Per face, per point (faceCentre) or triangle (faceDiag)
the added tet on the neighbour side
Definition at line 173 of file tetDecomposer.H.
Referenced by tetDecomposer::faceToPoint().
setRefinement()
void setRefinement (const decompositionType decomposeType, polyTopoChange & meshMod)
Insert all changes into meshMod to convert the polyMesh into.
tets.
Definition at line 183 of file tetDecomposer.C.
References Foam::abort(), polyTopoChange::addCell(), polyTopoChange::addPoint(), polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), primitiveMesh::cells(), polyMesh::cellZones(), HashTable< T, Key, Hash >::clear(), Foam::e, HashTableCore::end(), tetDecomposer::FACE_CENTRE_TRIS, primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), HashTable< T, Key, Hash >::find(), Foam::findIndex(), faceZone::flipMap(), forAll, HashTable< T, Key, Hash >::insert(), primitiveMesh::nCells(), face::nextLabel(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, face::prevLabel(), UList< T >::rcIndex(), List< T >::setSize(), List< T >::size(), polyMesh::tetBasePtIs(), faceZone::whichFace(), polyBoundaryMesh::whichPatch(), and ZoneMesh< ZoneType, MeshType >::whichZone().
Referenced by tetDecomposer::faceToPoint(), and tetDecomposer::tetDecomposer().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Force recalculation of locally stored data on topological change.
Definition at line 697 of file tetDecomposer.C.
References forAll, Foam::inplaceRenumber(), mapPolyMesh::reverseCellMap(), and mapPolyMesh::reversePointMap().
Referenced by tetDecomposer::faceToPoint().
Member Data Documentation
decompositionTypeNames
const NamedEnum< tetDecomposer::decompositionType, 2 > decompositionTypeNames static
Definition at line 70 of file tetDecomposer.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/tetDecomposer.H
src/dynamicMesh/polyTopoChange/polyTopoChange/tetDecomposer.C