OpenFOAM: polyTopoChange Class Reference
polyTopoChange Class Reference
Direct mesh changes based on v1.3 polyTopoChange syntax.
Public Member Functions
ClassName ("polyTopoChange")
Runtime type information.
polyTopoChange (const label nPatches, const bool strict=true)
Construct without mesh. Either specify nPatches or use.
polyTopoChange (const polyMesh &mesh, const bool strict=true)
Construct from mesh. Adds all points/face/cells from mesh.
const DynamicList< point > & points () const
Points. Shrunk after constructing mesh (or calling of compact())
const DynamicList< face > & faces () const
const DynamicList< label > & region () const
const DynamicList< label > & faceOwner () const
const DynamicList< label > & faceNeighbour () const
bool pointRemoved (const label pointi) const
Is point removed?
bool faceRemoved (const label facei) const
Is face removed?
bool cellRemoved (const label celli) const
Is cell removed?
void clear ()
Clear all storage.
void addMesh (const polyMesh &, const labelList &patchMap, const labelList &pointZoneMap, const labelList &faceZoneMap, const labelList &cellZoneMap)
Add all points/faces/cells of mesh. Additional offset for patch.
void setCapacity (const label nPoints, const label nFaces, const label nCells)
Explicitly pre-size the dynamic storage for expected mesh.
void movePoints (const pointField &newPoints)
Move all points. Incompatible with other topology changes.
label setAction (const topoAction &action)
For compatibility with polyTopoChange: set topological action.
label addPoint (const point &, const label masterPointID, const label zoneID, const bool inCell)
Add point. Return new point label.
void modifyPoint (const label, const point &, const label newZoneID, const bool inCell)
Modify coordinate.
void removePoint (const label, const label)
Remove/merge point.
label addFace (const face &f, const label own, const label nei, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Add face to cells. Return new face label.
void modifyFace (const face &f, const label facei, const label own, const label nei, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Modify vertices or cell of face.
void removeFace (const label, const label)
Remove/merge face.
label addCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID)
Add cell. Return new cell label.
void modifyCell (const label, const label zoneID)
Modify zone of cell.
void removeCell (const label, const label)
Remove/merge cell.
void setNumPatches (const label nPatches)
Explicitly set the number of patches if construct-without-mesh.
autoPtr< mapPolyMesh > changeMesh (polyMesh &mesh, const bool inflate, const bool syncParallel=true, const bool orderCells=false, const bool orderPoints=false)
Inplace changes mesh without change of patches.
autoPtr< mapPolyMesh > makeMesh (autoPtr< fvMesh > &newMesh, const IOobject &io, const polyMesh &mesh, const bool syncParallel=true, const bool orderCells=false, const bool orderPoints=false)
Create new mesh with old mesh patches.
Detailed Description
Direct mesh changes based on v1.3 polyTopoChange syntax.
Instead of recording changes and executing them all in one go (as did v1.3 polyTopoChange) this class actually holds the current points/faces/cells and does the change immediately. It can be asked to compress out all unused points/faces/cells and renumber everything to be consistent.
Note:
polyTopoChange can be copied.
adding a face using non-existing cells causes all intermediate cells to be added. So always first add cells/points and then faces. (or set strict checking)
strict checking:
any added/modified face can only use already existing vertices
any added face can only use already existing cells
no item can be removed more than once.
removed cell: cell set to 0 faces.
removed face: face set to 0 vertices.
removed point: coordinate set to vector::max (VGREAT,VGREAT,VGREAT). Note that this might give problems if this value is used already. To see if point is equal to above value we don't use == (which might give problems with roundoff error) but instead compare the individual component with >.
coupled patches: the reorderCoupledFaces routine (borrowed from the couplePatches utility) reorders coupled patch faces and uses the cyclicPolyPatch,processorPolyPatch functionality.
Source files
polyTopoChange.H
polyTopoChange.C
polyTopoChangeI.H
polyTopoChangeTemplates.C
Definition at line 97 of file polyTopoChange.H.
Constructor & Destructor Documentation
polyTopoChange() [1/2]
polyTopoChange (const label nPatches, const bool strict = true)
Construct without mesh. Either specify nPatches or use.
setNumPatches before trying to make a mesh (makeMesh, changeMesh)
Definition at line 2169 of file polyTopoChange.C.
polyTopoChange() [2/2]
polyTopoChange (const polyMesh & mesh, const bool strict = true)
Construct from mesh. Adds all points/face/cells from mesh.
Definition at line 2201 of file polyTopoChange.C.
References polyTopoChange::addMesh(), polyMesh::boundaryMesh(), polyMesh::cellZones(), polyMesh::faceZones(), Foam::identity(), polyMesh::pointZones(), and UPtrList< T >::size().
Member Function Documentation
ClassName()
ClassName ("polyTopoChange")
Runtime type information.
points()
const DynamicList<point>& points () const inline
Points. Shrunk after constructing mesh (or calling of compact())
Definition at line 421 of file polyTopoChange.H.
Referenced by hexRef8::faceLevel(), duplicatePoints::setRefinement(), and addPatchCellLayer::setRefinement().
faces()
const DynamicList<face>& faces () const inline
Definition at line 426 of file polyTopoChange.H.
Referenced by polyTopoChange::addMesh().
region()
const DynamicList<label>& region () const inline
Definition at line 431 of file polyTopoChange.H.
faceOwner()
const DynamicList<label>& faceOwner () const inline
Definition at line 436 of file polyTopoChange.H.
Referenced by polyTopoChange::addMesh().
faceNeighbour()
const DynamicList<label>& faceNeighbour () const inline
Definition at line 441 of file polyTopoChange.H.
References polyTopoChange::addCell(), polyTopoChange::addFace(), polyTopoChange::addMesh(), polyTopoChange::addPoint(), polyTopoChange::cellRemoved(), polyTopoChange::changeMesh(), polyTopoChange::clear(), polyTopoChange::faceRemoved(), polyTopoChange::makeMesh(), polyTopoChange::modifyCell(), polyTopoChange::modifyFace(), polyTopoChange::modifyPoint(), polyTopoChange::movePoints(), nPoints, polyTopoChange::pointRemoved(), polyTopoChange::removeCell(), polyTopoChange::removeFace(), polyTopoChange::removePoint(), polyTopoChange::setAction(), polyTopoChange::setCapacity(), and polyTopoChange::setNumPatches().
Referenced by polyTopoChange::addMesh().
pointRemoved()
bool pointRemoved (const label pointi) const inline
Is point removed?
Definition at line 30 of file polyTopoChangeI.H.
References VectorSpace< Vector< scalar >, scalar, 3 >::max, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by polyTopoChange::faceNeighbour(), polyTopoChange::modifyPoint(), and polyTopoChange::removePoint().
faceRemoved()
bool faceRemoved (const label facei) const inline
Is face removed?
Definition at line 41 of file polyTopoChangeI.H.
Referenced by polyTopoChange::faceNeighbour(), and polyTopoChange::removeFace().
cellRemoved()
bool cellRemoved (const label celli) const inline
Is cell removed?
Definition at line 47 of file polyTopoChangeI.H.
Referenced by polyTopoChange::faceNeighbour().
clear()
void clear ()
Clear all storage.
Definition at line 2245 of file polyTopoChange.C.
References polyTopoChange::addMesh(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clearStorage(), HashTable< T, Key, Hash >::clearStorage(), and PackedList< nBits >::clearStorage().
Referenced by polyTopoChange::faceNeighbour().
addMesh()
void addMesh (const polyMesh & mesh, const labelList & patchMap, const labelList & pointZoneMap, const labelList & faceZoneMap, const labelList & cellZoneMap)
Add all points/faces/cells of mesh. Additional offset for patch.
or zone ids.
Definition at line 2276 of file polyTopoChange.C.
References Foam::abort(), polyTopoChange::addCell(), polyTopoChange::addFace(), polyTopoChange::addPoint(), polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), polyMesh::cellZones(), Foam::endl(), polyMesh::faceNeighbour(), polyTopoChange::faceNeighbour(), polyMesh::faceOwner(), polyTopoChange::faceOwner(), polyMesh::faces(), polyTopoChange::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), patchIdentifier::name(), IOobject::name(), primitiveMesh::nCells(), primitiveMesh::nInternalFaces(), primitiveMesh::nPoints(), patchi, pointLabels(), polyMesh::points(), polyMesh::pointZones(), HashTable< T, Key, Hash >::resize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), PackedList< nBits >::setCapacity(), polyTopoChange::setCapacity(), List< T >::size(), HashTable< T, Key, Hash >::size(), polyPatch::start(), and WarningInFunction.
Referenced by polyTopoChange::clear(), polyTopoChange::faceNeighbour(), and polyTopoChange::polyTopoChange().
setCapacity()
void setCapacity (const label nPoints, const label nFaces, const label nCells)
Explicitly pre-size the dynamic storage for expected mesh.
size for if construct-without-mesh
Definition at line 2483 of file polyTopoChange.C.
References HashTable< T, Key, Hash >::resize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), PackedList< nBits >::setCapacity(), and HashTable< T, Key, Hash >::size().
Referenced by polyTopoChange::addMesh(), and polyTopoChange::faceNeighbour().
movePoints()
void movePoints (const pointField & newPoints)
Move all points. Incompatible with other topology changes.
Definition at line 2723 of file polyTopoChange.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, polyTopoChange::removePoint(), and List< T >::size().
Referenced by polyTopoChange::faceNeighbour().
setAction()
Foam::label setAction (const topoAction & action)
For compatibility with polyTopoChange: set topological action.
Definition at line 2515 of file polyTopoChange.C.
References Foam::abort(), polyTopoChange::addCell(), polyTopoChange::addFace(), polyTopoChange::addPoint(), polyRemoveCell::cellID(), polyModifyCell::cellID(), polyRemoveFace::faceID(), polyModifyFace::faceID(), Foam::FatalError, FatalErrorInFunction, polyModifyFace::flipFaceFlux(), polyAddFace::flipFaceFlux(), polyModifyPoint::inCell(), polyAddPoint::inCell(), polyAddCell::masterCellID(), polyAddCell::masterEdgeID(), polyAddFace::masterEdgeID(), polyAddCell::masterFaceID(), polyAddFace::masterFaceID(), polyAddPoint::masterPointID(), polyAddCell::masterPointID(), polyAddFace::masterPointID(), polyRemoveCell::mergeCellID(), polyRemoveFace::mergeFaceID(), polyRemovePoint::mergePointID(), polyTopoChange::modifyCell(), polyTopoChange::modifyFace(), polyTopoChange::modifyPoint(), polyModifyFace::neighbour(), polyAddFace::neighbour(), polyModifyFace::newFace(), polyAddFace::newFace(), polyModifyPoint::newPoint(), polyAddPoint::newPoint(), polyModifyFace::owner(), polyAddFace::owner(), polyModifyFace::patchID(), polyAddFace::patchID(), polyRemovePoint::pointID(), polyModifyPoint::pointID(), polyTopoChange::removeCell(), polyTopoChange::removeFace(), polyModifyCell::removeFromZone(), polyTopoChange::removePoint(), polyModifyFace::zoneFlip(), polyAddFace::zoneFlip(), polyModifyCell::zoneID(), polyModifyPoint::zoneID(), polyAddPoint::zoneID(), polyAddCell::zoneID(), polyModifyFace::zoneID(), and polyAddFace::zoneID().
Referenced by repatchPolyTopoChanger::changeAnchorPoint(), repatchPolyTopoChanger::changePatchID(), polyTopoChange::faceNeighbour(), meshRefinement::mergeBaffles(), polyMeshAdder::mergePoints(), faceEqOp< T, CombineOp >::operator()(), ifEqEqOp< value >::operator()(), fvMeshDistribute::printCoupleInfo(), repatchPolyTopoChanger::setFaceZone(), removeCells::setRefinement(), perfectInterface::setRefinement(), faceCollapser::setRefinement(), removePoints::setRefinement(), boundaryCutter::setRefinement(), combineFaces::setRefinement(), removeFaces::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), addPatchCellLayer::setRefinement(), hexRef8::setRefinement(), removePoints::setUnrefinement(), combineFaces::setUnrefinement(), and meshRefinement::zonify().
addPoint()
Foam::label addPoint (const point & pt, const label masterPointID, const label zoneID, const bool inCell)
Add point. Return new point label.
Notes:
masterPointID can be < 0 (appended points)
inCell = false: add retired point (to end of point list)
Definition at line 2644 of file polyTopoChange.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), HashSet< Key, Hash >::insert(), HashTable< T, Key, Hash >::insert(), and polyTopoChange::modifyPoint().
Referenced by polyTopoChange::addMesh(), polyTopoChange::faceNeighbour(), polyTopoChange::setAction(), duplicatePoints::setRefinement(), createShellMesh::setRefinement(), and tetDecomposer::setRefinement().
modifyPoint()
void modifyPoint (const label pointi, const point & pt, const label newZoneID, const bool inCell)
Modify coordinate.
Notes:
inCell = false: add retired point (to end of point list)
Definition at line 2672 of file polyTopoChange.C.
References Foam::abort(), HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::erase(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), HashSet< Key, Hash >::insert(), HashTable< T, Key, Hash >::insert(), and polyTopoChange::pointRemoved().
Referenced by polyTopoChange::addPoint(), polyTopoChange::faceNeighbour(), polyTopoChange::setAction(), and edgeCollapser::setRefinement().
removePoint()
void removePoint (const label pointi, const label mergePointi)
Remove/merge point.
Definition at line 2742 of file polyTopoChange.C.
References Foam::abort(), polyTopoChange::addFace(), Foam::endl(), HashTable< T, Key, Hash >::erase(), Foam::FatalError, FatalErrorInFunction, VectorSpace< Vector< scalar >, scalar, 3 >::max, and polyTopoChange::pointRemoved().
Referenced by polyTopoChange::faceNeighbour(), polyMeshAdder::mergePoints(), polyTopoChange::movePoints(), polyTopoChange::setAction(), and edgeCollapser::setRefinement().
addFace()
Foam::label addFace (const face & f, const label own, const label nei, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Add face to cells. Return new face label.
own,nei<0, zoneID>=0 : add inactive face (to end of face list)
Definition at line 2790 of file polyTopoChange.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), HashTable< T, Key, Hash >::insert(), and polyTopoChange::modifyFace().
Referenced by polyTopoChange::addMesh(), polyTopoChange::faceNeighbour(), NamedEnum< directionType, 3 >::names(), polyTopoChange::removePoint(), polyTopoChange::setAction(), createShellMesh::setRefinement(), and meshRefinement::splitFaces().
modifyFace()
void modifyFace (const face & f, const label facei, const label own, const label nei, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Modify vertices or cell of face.
Definition at line 2854 of file polyTopoChange.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::erase(), f(), HashTable< T, Key, Hash >::find(), and HashTable< T, Key, Hash >::insert().
Referenced by polyTopoChange::addFace(), polyTopoChange::faceNeighbour(), NamedEnum< directionType, 3 >::names(), polyTopoChange::setAction(), duplicatePoints::setRefinement(), edgeCollapser::setRefinement(), and meshRefinement::splitFaces().
removeFace()
void removeFace (const label facei, const label mergeFacei)
Remove/merge face.
Definition at line 2899 of file polyTopoChange.C.
References Foam::abort(), polyTopoChange::addCell(), Foam::endl(), HashTable< T, Key, Hash >::erase(), polyTopoChange::faceRemoved(), Foam::FatalError, and FatalErrorInFunction.
Referenced by polyTopoChange::faceNeighbour(), polyTopoChange::setAction(), and edgeCollapser::setRefinement().
addCell()
Foam::label addCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID)
Add cell. Return new cell label.
Definition at line 2943 of file polyTopoChange.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), HashTable< T, Key, Hash >::insert(), polyTopoChange::modifyCell(), and List< T >::size().
Referenced by polyTopoChange::addMesh(), polyTopoChange::faceNeighbour(), polyTopoChange::removeFace(), polyTopoChange::setAction(), createShellMesh::setRefinement(), and tetDecomposer::setRefinement().
modifyCell()
void modifyCell (const label celli, const label zoneID)
Modify zone of cell.
Definition at line 2980 of file polyTopoChange.C.
Referenced by polyTopoChange::addCell(), polyTopoChange::faceNeighbour(), and polyTopoChange::setAction().
removeCell()
void removeCell (const label celli, const label mergeCelli)
Remove/merge cell.
Definition at line 2989 of file polyTopoChange.C.
References Foam::abort(), polyTopoChange::changeMesh(), Foam::endl(), HashTable< T, Key, Hash >::erase(), Foam::FatalError, FatalErrorInFunction, and List< T >::size().
Referenced by polyTopoChange::faceNeighbour(), polyTopoChange::setAction(), and edgeCollapser::setRefinement().
setNumPatches()
void setNumPatches (const label nPatches) inline
Explicitly set the number of patches if construct-without-mesh.
used.
Definition at line 53 of file polyTopoChangeI.H.
References nPatches.
Referenced by polyTopoChange::faceNeighbour().
changeMesh()
Foam::autoPtr< Foam::mapPolyMesh > changeMesh (polyMesh & mesh, const bool inflate, const bool syncParallel = true, const bool orderCells = false, const bool orderPoints = false)
Inplace changes mesh without change of patches.
Adapts patch start/end and by default does parallel matching. Clears all data. Returns map. inflate = true : keep old mesh points. Put new points into the returned map (preMotionPoints) so we can use inflation. Any points out of nothing (appended points) are vector::zero. inflate = false: set mesh points directly. Empty preMotionPoints in the map. orderCells : whether to order the cells (see bandCompression.H) orderPoints : whether to order the points into internal first followed by boundary points. This is not fully consistent with upper-triangular ordering of points and edges so is only done when explicitly asked for.
Definition at line 3024 of file polyTopoChange.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellVolumes(), polyMesh::cellZones(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clearStorage(), HashTable< T, Key, Hash >::clearStorage(), PackedList< nBits >::clearStorage(), Foam::endl(), polyMesh::faceZones(), forAll, polyTopoChange::makeMesh(), primitiveMesh::nCells(), newPointi, primitiveMesh::nFaces(), Foam::nl, primitiveMesh::nPoints(), polyMesh::points(), polyMesh::pointZones(), Foam::Pout, polyMesh::resetPrimitives(), List< T >::size(), UPtrList< T >::size(), polyMesh::topoChanging(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::xfer(), Foam::xferMove(), and Foam::Zero.
Referenced by polyMeshFilter::copyMesh(), meshRefinement::createBaffles(), meshRefinement::doRemovePoints(), meshRefinement::doRestorePoints(), meshRefinement::dupNonManifoldPoints(), polyTopoChange::faceNeighbour(), meshRefinement::mergeBaffles(), meshRefinement::mergePatchFacesUndo(), fvMeshDistribute::printCoupleInfo(), dynamicRefineFvMesh::refine(), meshRefinement::refine(), polyTopoChange::removeCell(), repatchPolyTopoChanger::repatch(), meshRefinement::setInstance(), refinementIterator::setRefinement(), meshRefinement::splitFaces(), dynamicRefineFvMesh::unrefine(), and meshRefinement::zonify().
makeMesh()
Foam::autoPtr< Foam::mapPolyMesh > makeMesh (autoPtr< fvMesh > & newMesh, const IOobject & io, const polyMesh & mesh, const bool syncParallel = true, const bool orderCells = false, const bool orderPoints = false)
Create new mesh with old mesh patches.
Definition at line 3290 of file polyTopoChange.C.
References fvMesh::addFvPatches(), polyMesh::addZones(), polyMesh::boundaryMesh(), primitiveMesh::cellVolumes(), polyMesh::cellZones(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clearStorage(), HashTable< T, Key, Hash >::clearStorage(), PackedList< nBits >::clearStorage(), IOobject::clone(), Foam::endl(), polyMesh::faceZones(), forAll, Foam::name(), primitiveMesh::nCells(), primitiveMesh::nFaces(), Foam::nl, IOobject::NO_READ, primitiveMesh::nPoints(), patchi, polyMesh::pointZones(), Foam::Pout, IOobject::readOpt(), autoPtr< T >::reset(), UPtrList< T >::size(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::xfer(), and Foam::xferMove().
Referenced by snappyLayerDriver::addLayers(), polyTopoChange::changeMesh(), polyMeshFilter::copyMesh(), polyTopoChange::faceNeighbour(), and fvMeshSubset::setLargeCellSubset().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChange.H
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChange.C
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChangeI.H
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChangeTemplates.C