OpenFOAM: STARCDedgeFormat Class Reference
STARCDedgeFormat Class Reference
Read/write the lines from pro-STAR vrt/cel files.
Public Member Functions
STARCDedgeFormat (const fileName &)
Construct from file name.
virtual ~STARCDedgeFormat ()
Destructor.
virtual bool read (const fileName &)
Read from file.
virtual void write (const fileName &name) const
Write object.
Public Member Functions inherited from edgeMesh
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const pointField &, const edgeList &)
Construct from components.
edgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges).
edgeMesh (const edgeMesh &)
Construct as copy.
edgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
edgeMesh (Istream &)
Construct from Istream.
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< edgeMesh > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void clear ()
Clear all storage.
virtual void reset (const Xfer< pointField > &points, const Xfer< edgeList > &edges)
Reset primitive data (points, edges)
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
void mergeEdges ()
Merge similar edges.
virtual void writeStats (Ostream &) const
void operator= (const edgeMesh &)
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Public Member Functions inherited from STARCDCore
STARCDCore ()
Construct null.
Static Public Member Functions
static autoPtr< edgeMesh > New (const fileName &name)
Read file and return edgeMesh.
static void write (const fileName &, const edgeMesh &)
Write edge mesh.
Static Public Member Functions inherited from edgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const edgeMesh &)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Static Public Member Functions inherited from STARCDCore
static bool readPoints (IFstream &, pointField &, labelList &ids)
Read points from a (.vrt) file.
static void writePoints (Ostream &, const pointField &)
Write header and points to (.vrt) file.
Static Protected Member Functions
static void writeCase (Ostream &, const pointField &, const label nEdges)
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (IFstream &)
Read non-comment line.
Static Protected Member Functions inherited from STARCDCore
static bool readHeader (IFstream &, const word &fileSignature)
Read header.
static void writeHeader (Ostream &, const word &fileType)
Write header for fileType (CELL|VERTEX|BOUNDARY)
Additional Inherited Members
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Types inherited from STARCDCore
enum cellType {
starcdFluidType = 1, starcdSolidType = 2, starcdBaffleType = 3, starcdShellType = 4,
starcdLineType = 5, starcdPointType = 6
}
enum shapeType {
starcdPoint = 1, starcdLine = 2, starcdShell = 3, starcdHex = 11,
starcdPrism = 12, starcdTet = 13, starcdPyr = 14, starcdPoly = 255
}
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Detailed Description
Read/write the lines from pro-STAR vrt/cel files.
Note
Uses the extension .inp (input) to denote the format.
See also
Foam::meshReaders::STARCD
Source files
STARCDedgeFormat.H
STARCDedgeFormat.C
Definition at line 61 of file STARCDedgeFormat.H.
Constructor & Destructor Documentation
STARCDedgeFormat()
STARCDedgeFormat (const fileName & filename)
Construct from file name.
Definition at line 96 of file STARCDedgeFormat.C.
References STARCDedgeFormat::read().
~STARCDedgeFormat()
virtual ~STARCDedgeFormat () inline virtual
Destructor.
Definition at line 122 of file STARCDedgeFormat.H.
References STARCDedgeFormat::read(), and STARCDedgeFormat::write().
Member Function Documentation
writeCase()
void writeCase (Ostream & os, const pointField & pointLst, const label nEdges) static protected
Definition at line 62 of file STARCDedgeFormat.C.
References clock::dateTime(), Ostream::flush(), fileName::lessExt(), fileName::name(), IOstream::name(), Foam::nl, and List< T >::size().
Referenced by STARCDedgeFormat::write().
New()
static autoPtr<edgeMesh> New (const fileName & name) inline static
Read file and return edgeMesh.
Definition at line 112 of file STARCDedgeFormat.H.
write() [1/2]
void write (const fileName & filename, const edgeMesh & mesh) static
Write edge mesh.
Definition at line 232 of file STARCDedgeFormat.C.
References edgeMesh::edges(), fileName::lessExt(), edgeMesh::points(), List< T >::size(), STARCDedgeFormat::writeCase(), and STARCDCore::writePoints().
Referenced by STARCDedgeFormat::read(), STARCDedgeFormat::write(), and STARCDedgeFormat::~STARCDedgeFormat().
read()
bool read (const fileName & filename) virtual
Read from file.
Reimplemented from edgeMesh.
Definition at line 107 of file STARCDedgeFormat.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), List< T >::clear(), edgeMesh::clear(), PackedList< nBits >::count(), Foam::e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, PackedList< nBits >::get(), IOstream::good(), fileName::lessExt(), IFstream::name(), edgeMesh::points(), STARCDCore::readHeader(), STARCDCore::readPoints(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::reserve(), PackedBoolList::set(), List< T >::setSize(), List< T >::size(), edgeMesh::storedEdges(), edgeMesh::storedPoints(), List< T >::transfer(), and STARCDedgeFormat::write().
Referenced by STARCDedgeFormat::STARCDedgeFormat(), and STARCDedgeFormat::~STARCDedgeFormat().
write() [2/2]
virtual void write (const fileName & name) const inline virtual
Write object.
Reimplemented from edgeMesh.
Definition at line 135 of file STARCDedgeFormat.H.
References STARCDedgeFormat::write().
The documentation for this class was generated from the following files:
src/edgeMesh/edgeMeshFormats/starcd/STARCDedgeFormat.H
src/edgeMesh/edgeMeshFormats/starcd/STARCDedgeFormat.C