OpenFOAM: extendedFeatureEdgeMesh Class Reference
extendedFeatureEdgeMesh Class Reference
extendedEdgeMesh + IO.
Public Member Functions
TypeName ("extendedFeatureEdgeMesh")
Runtime type information.
extendedFeatureEdgeMesh (const IOobject &)
Construct (read) given an IOobject.
extendedFeatureEdgeMesh (const IOobject &, const extendedEdgeMesh &)
Construct as copy.
extendedFeatureEdgeMesh (const surfaceFeatures &sFeat, const objectRegistry &obr, const fileName &sFeatFileName, const boolList &surfBaffleRegions)
Construct given a surface with selected edges,point.
extendedFeatureEdgeMesh (const IOobject &, const PrimitivePatch< face, List, pointField, point > &surf, const labelList &featureEdges, const labelList &regionFeatureEdges, const labelList &featurePoints)
Construct from PrimitivePatch.
extendedFeatureEdgeMesh (const IOobject &io, const pointField &pts, const edgeList &eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField &normals, const List< sideVolumeType > &normalVolumeTypes, const vectorField &edgeDirections, const labelListList &normalDirections, const labelListList &edgeNormals, const labelListList &featurePointNormals, const labelListList &featurePointEdges, const labelList &regionEdges)
Construct from all components.
virtual ~extendedFeatureEdgeMesh ()
Destructor.
virtual bool readData (Istream &)
ReadData function required for regIOobject read operation.
virtual bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from extendedEdgeMesh
TypeName ("extendedEdgeMesh")
Runtime type information.
extendedEdgeMesh ()
Construct null.
extendedEdgeMesh (const extendedEdgeMesh &)
Construct as copy.
extendedEdgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
extendedEdgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
extendedEdgeMesh (Istream &)
Construct from Istream.
extendedEdgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges)
extendedEdgeMesh (const surfaceFeatures &sFeat, const boolList &surfBaffleRegions)
Construct given a surface with selected edges,point.
extendedEdgeMesh (const PrimitivePatch< face, List, pointField, point > &surf, const labelList &featureEdges, const labelList &regionFeatureEdges, const labelList &featurePoints)
Construct from PrimitivePatch.
extendedEdgeMesh (const pointField &pts, const edgeList &eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField &normals, const List< sideVolumeType > &normalVolumeTypes, const vectorField &edgeDirections, const labelListList &normalDirections, const labelListList &edgeNormals, const labelListList &featurePointNormals, const labelListList &featurePointEdges, const labelList &regionEdges)
Construct from all components.
declareRunTimeSelectionTable (autoPtr, extendedEdgeMesh, fileExtension,(const fileName &name),(name))
~extendedEdgeMesh ()
Destructor.
void nearestFeaturePoint (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
Find nearest surface edge for the sample point.
void nearestFeatureEdge (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
Find nearest surface edge for the sample point.
void nearestFeatureEdge (const pointField &samples, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
Find nearest surface edge for each sample point.
void nearestFeatureEdgeByType (const point &sample, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
Find the nearest point on each type of feature edge.
void allNearestFeaturePoints (const point &sample, scalar searchRadiusSqr, List< pointIndexHit > &info) const
Find all the feature points within searchDistSqr of sample.
void allNearestFeatureEdges (const point &sample, const scalar searchRadiusSqr, List< pointIndexHit > &info) const
Find all the feature edges within searchDistSqr of sample.
label convexStart () const
Return the index of the start of the convex feature points.
label concaveStart () const
Return the index of the start of the concave feature points.
label mixedStart () const
Return the index of the start of the mixed type feature points.
label nonFeatureStart () const
Return the index of the start of the non-feature points.
label externalStart () const
Return the index of the start of the external feature edges.
label internalStart () const
Return the index of the start of the internal feature edges.
label flatStart () const
Return the index of the start of the flat feature edges.
label openStart () const
Return the index of the start of the open feature edges.
label multipleStart () const
Return the index of the start of the multiply-connected feature.
bool featurePoint (label ptI) const
Return whether or not the point index is a feature point.
const vectorField & normals () const
Return the normals of the surfaces adjacent to the feature edges.
const List< sideVolumeType > & normalVolumeTypes () const
Return.
const vectorField & edgeDirections () const
Return the edgeDirection vectors.
const labelListList & normalDirections () const
vector edgeDirection (label edgeI, label ptI) const
Return the direction of edgeI, pointing away from ptI.
const labelListList & edgeNormals () const
Return the indices of the normals that are adjacent to the.
vectorField edgeNormals (const labelList &edgeNormIs) const
Return the normal vectors for a given set of normal indices.
vectorField edgeNormals (label edgeI) const
Return the normal vectors for a given edge.
const labelListList & featurePointNormals () const
Return the indices of the normals that are adjacent to the.
vectorField featurePointNormals (label ptI) const
Return the normal vectors for a given feature point.
const labelListList & featurePointEdges () const
Return the edge labels for a given feature point. Edges are.
const labelList & regionEdges () const
Return the feature edges which are on the boundary between.
pointStatus getPointStatus (label ptI) const
Return the pointStatus of a specified point.
edgeStatus getEdgeStatus (label edgeI) const
Return the edgeStatus of a specified edge.
PackedList< 2 > edgeBaffles (label edgeI) const
Return the baffle faces of a specified edge.
const indexedOctree< treeDataPoint > & pointTree () const
Demand driven construction of octree for feature points.
const indexedOctree< treeDataEdge > & edgeTree () const
Demand driven construction of octree for boundary edges.
const PtrList< indexedOctree< treeDataEdge > > & edgeTreesByType () const
Demand driven construction of octree for boundary edges by type.
void transfer (extendedEdgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< extendedEdgeMesh > xfer ()
Transfer contents to the Xfer container.
virtual void clear ()
Clear all storage.
void add (const extendedEdgeMesh &)
Add extendedEdgeMesh. No filtering of duplicates.
void flipNormals ()
Flip normals. All concave become convex, all internal external.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &)
Read from file. Chooses reader based on detected extension.
void writeObj (const fileName &prefix) const
Write all components of the extendedEdgeMesh as obj files.
virtual void writeStats (Ostream &os) const
Dump some information.
Public Member Functions inherited from edgeMesh
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const pointField &, const edgeList &)
Construct from components.
edgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges).
edgeMesh (const edgeMesh &)
Construct as copy.
edgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
edgeMesh (Istream &)
Construct from Istream.
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< edgeMesh > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void reset (const Xfer< pointField > &points, const Xfer< edgeList > &edges)
Reset primitive data (points, edges)
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
void mergeEdges ()
Merge similar edges.
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void operator= (const edgeMesh &)
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from extendedEdgeMesh
enum pointStatus { CONVEX, CONCAVE, MIXED, NONFEATURE }
enum edgeStatus {
EXTERNAL, INTERNAL, FLAT, OPEN,
MULTIPLE, NONE
}
enum sideVolumeType { INSIDE = 0, OUTSIDE = 1, BOTH = 2, NEITHER = 3 }
Normals point to the outside.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from extendedEdgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< extendedEdgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< extendedEdgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static edgeStatus classifyEdge (const List< vector > &norms, const labelList &edNorms, const vector &fC0tofC1)
Classify the type of feature edge. Requires face centre 0 to face.
Static Public Member Functions inherited from edgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const edgeMesh &)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from extendedEdgeMesh
static const Foam::NamedEnum< pointStatus, 4 > pointStatusNames_
static const Foam::NamedEnum< edgeStatus, 6 > edgeStatusNames_
static const Foam::NamedEnum< sideVolumeType, 4 > sideVolumeTypeNames_
static scalar cosNormalAngleTol_
Angular closeness tolerance for treating normals as the same.
static label nPointTypes = 4
Number of possible point types (i.e. number of slices)
static label nEdgeTypes = 5
Number of possible feature edge types (i.e. number of slices)
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from extendedEdgeMesh
pointStatus classifyFeaturePoint (label ptI) const
Classify the type of feature point. Requires valid stored member.
template<class Patch >
void sortPointsAndEdges (const Patch &, const labelList &featureEdges, const labelList &regionFeatureEdges, const labelList &feaurePoints)
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (IFstream &)
Read non-comment line.
Protected Attributes inherited from extendedEdgeMesh
label concaveStart_
Index of the start of the concave feature points.
label mixedStart_
Index of the start of the mixed type feature points.
label nonFeatureStart_
Index of the start of the non-feature points.
label internalStart_
Index of the start of the internal feature edges.
label flatStart_
Index of the start of the flat feature edges.
label openStart_
Index of the start of the open feature edges.
label multipleStart_
Index of the start of the multiply-connected feature edges.
vectorField normals_
Normals of the features, to be referred to by index by both feature.
List< sideVolumeType > normalVolumeTypes_
Type per normal: which side of normal to mesh.
vectorField edgeDirections_
Flat and open edges require the direction of the edge.
labelListList normalDirections_
Starting directions for the edges.
labelListList edgeNormals_
Indices of the normals that are adjacent to the feature edges.
labelListList featurePointNormals_
Indices of the normals that are adjacent to the feature points.
labelListList featurePointEdges_
Indices of feature edges attached to feature points. The edges are.
labelList regionEdges_
Feature edges which are on the boundary between regions.
autoPtr< indexedOctree< treeDataPoint > > pointTree_
Search tree for all feature points.
autoPtr< indexedOctree< treeDataEdge > > edgeTree_
Search tree for all edges.
PtrList< indexedOctree< treeDataEdge > > edgeTreesByType_
Individual search trees for each type of edge.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Static Protected Attributes inherited from extendedEdgeMesh
static label convexStart_ = 0
Index of the start of the convex feature points - static as 0.
static label externalStart_ = 0
Index of the start of the external feature edges - static as 0.
Detailed Description
extendedEdgeMesh + IO.
Source files
extendedFeatureEdgeMesh.H
extendedFeatureEdgeMesh.C
Definition at line 52 of file extendedFeatureEdgeMesh.H.
Constructor & Destructor Documentation
extendedFeatureEdgeMesh() [1/5]
extendedFeatureEdgeMesh (const IOobject & io)
Construct (read) given an IOobject.
Definition at line 38 of file extendedFeatureEdgeMesh.C.
References regIOobject::close(), extendedEdgeMesh::edgeDirections_, edgeMesh::edges(), Foam::endl(), forAll, IOobject::headerOk(), Foam::mag(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, edgeMesh::points(), Foam::Pout, IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), List< T >::setSize(), List< T >::size(), and WarningInFunction.
Referenced by extendedFeatureEdgeMesh::extendedFeatureEdgeMesh().
extendedFeatureEdgeMesh() [2/5]
extendedFeatureEdgeMesh (const IOobject & io, const extendedEdgeMesh & em)
Construct as copy.
Definition at line 91 of file extendedFeatureEdgeMesh.C.
References extendedFeatureEdgeMesh::extendedFeatureEdgeMesh().
extendedFeatureEdgeMesh() [3/5]
extendedFeatureEdgeMesh (const surfaceFeatures & sFeat, const objectRegistry & obr, const fileName & sFeatFileName, const boolList & surfBaffleRegions)
Construct given a surface with selected edges,point.
(surfaceFeatures), an objectRegistry and a fileName to write to. Extracts, classifies and reorders the data from surfaceFeatures.
Definition at line 102 of file extendedFeatureEdgeMesh.C.
References extendedFeatureEdgeMesh::extendedFeatureEdgeMesh().
extendedFeatureEdgeMesh() [4/5]
extendedFeatureEdgeMesh (const IOobject & io, const PrimitivePatch< face, List, pointField, point > & surf, const labelList & featureEdges, const labelList & regionFeatureEdges, const labelList & featurePoints)
Construct from PrimitivePatch.
Definition at line 126 of file extendedFeatureEdgeMesh.C.
References extendedFeatureEdgeMesh::extendedFeatureEdgeMesh().
extendedFeatureEdgeMesh() [5/5]
extendedFeatureEdgeMesh (const IOobject & io, const pointField & pts, const edgeList & eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField & normals, const List< sideVolumeType > & normalVolumeTypes, const vectorField & edgeDirections, const labelListList & normalDirections, const labelListList & edgeNormals, const labelListList & featurePointNormals, const labelListList & featurePointEdges, const labelList & regionEdges)
Construct from all components.
Definition at line 140 of file extendedFeatureEdgeMesh.C.
~extendedFeatureEdgeMesh()
~extendedFeatureEdgeMesh () virtual
Destructor.
Definition at line 187 of file extendedFeatureEdgeMesh.C.
Member Function Documentation
TypeName()
TypeName ("extendedFeatureEdgeMesh")
Runtime type information.
readData()
bool readData (Istream & is) virtual
ReadData function required for regIOobject read operation.
Reimplemented from regIOobject.
Definition at line 196 of file extendedFeatureEdgeMesh.C.
References IOstream::bad().
writeData()
bool writeData (Ostream & os) const virtual
WriteData function required for regIOobject write operation.
Implements regIOobject.
Definition at line 203 of file extendedFeatureEdgeMesh.C.
References IOstream::good().
The documentation for this class was generated from the following files:
src/edgeMesh/extendedEdgeMesh/extendedFeatureEdgeMesh/extendedFeatureEdgeMesh.H
src/edgeMesh/extendedEdgeMesh/extendedFeatureEdgeMesh/extendedFeatureEdgeMesh.C