OpenFOAM: edgeMesh Class Reference
edgeMesh Class Reference
Points connected by edges.
Public Member Functions
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const pointField &, const edgeList &)
Construct from components.
edgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges).
edgeMesh (const edgeMesh &)
Construct as copy.
edgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
edgeMesh (Istream &)
Construct from Istream.
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< edgeMesh > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &)
Read from file. Chooses reader based on detected extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void clear ()
Clear all storage.
virtual void reset (const Xfer< pointField > &points, const Xfer< edgeList > &edges)
Reset primitive data (points, edges)
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
void mergeEdges ()
Merge similar edges.
virtual void writeStats (Ostream &) const
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void operator= (const edgeMesh &)
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Static Public Member Functions
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const edgeMesh &)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Protected Member Functions
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Friends
Ostream & operator<< (Ostream &, const edgeMesh &)
Istream & operator>> (Istream &, edgeMesh &)
Additional Inherited Members
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
Points connected by edges.
Can be read from fileName based on extension. Uses New factory method to select the reader and transfer the result.
Source files
edgeMesh.H
edgeMeshI.H
edgeMesh.C
edgeMeshIO.C
edgeMeshNew.C
Definition at line 69 of file edgeMesh.H.
Constructor & Destructor Documentation
edgeMesh() [1/7]
edgeMesh ()
Construct null.
Definition at line 123 of file edgeMesh.C.
Referenced by edgeMesh::edgeMesh().
edgeMesh() [2/7]
edgeMesh (const pointField & points, const edgeList & edges)
Construct from components.
Definition at line 133 of file edgeMesh.C.
References edgeMesh::edgeMesh().
edgeMesh() [3/7]
edgeMesh (const Xfer< pointField > & pointLst, const Xfer< edgeList > & edgeLst)
Construct by transferring components (points, edges).
Definition at line 146 of file edgeMesh.C.
References List< T >::transfer().
edgeMesh() [4/7]
edgeMesh (const edgeMesh & em) inline
Construct as copy.
Definition at line 28 of file edgeMeshI.H.
edgeMesh() [5/7]
edgeMesh (const fileName & name)
Construct from file name (uses extension to determine type)
Definition at line 46 of file edgeMeshIO.C.
References edgeMesh::read().
edgeMesh() [6/7]
edgeMesh (const fileName & name, const word & ext)
Construct from file name (uses extension to determine type)
Definition at line 33 of file edgeMeshIO.C.
References Foam::read().
edgeMesh() [7/7]
edgeMesh (Istream &)
Construct from Istream.
~edgeMesh()
~edgeMesh () virtual
Destructor.
Definition at line 163 of file edgeMesh.C.
Member Function Documentation
storedPoints()
Foam::pointField & storedPoints () inline protected
Non-const access to global points.
Definition at line 61 of file edgeMeshI.H.
Referenced by OBJedgeFormat::read(), and STARCDedgeFormat::read().
storedEdges()
Foam::edgeList & storedEdges () inline protected
Non-const access to the edges.
Definition at line 67 of file edgeMeshI.H.
Referenced by OBJedgeFormat::read(), and STARCDedgeFormat::read().
TypeName()
TypeName ("edgeMesh")
Runtime type information.
canRead()
bool canRead (const fileName & name, const bool verbose = false) static
Can we read this file format?
Definition at line 90 of file edgeMesh.C.
References Foam::abort(), fileName::ext(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), fileName::lessExt(), and List< T >::size().
Referenced by edgeMesh::canWriteType().
canReadType()
bool canReadType (const word & ext, const bool verbose = false) static
Can we read this file format?
Definition at line 58 of file edgeMesh.C.
References edgeMesh::canWriteType().
Referenced by edgeMesh::writeTypes().
canWriteType()
bool canWriteType (const word & ext, const bool verbose = false) static
Can we write this file format type?
Definition at line 74 of file edgeMesh.C.
References edgeMesh::canRead().
Referenced by edgeMesh::canReadType().
readTypes()
Foam::wordHashSet readTypes () static
Definition at line 43 of file edgeMesh.C.
writeTypes()
Foam::wordHashSet writeTypes () static
Definition at line 49 of file edgeMesh.C.
References edgeMesh::canReadType().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , edgeMesh , fileExtension , (const fileName &name) , (name))
New() [1/2]
Foam::autoPtr< Foam::edgeMesh > New (const fileName & name, const word & ext) static
Select constructed from filename (explicit extension)
Definition at line 31 of file edgeMeshNew.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::nl.
Referenced by edgeMesh::New(), and edgeMesh::read().
New() [2/2]
Foam::autoPtr< Foam::edgeMesh > New (const fileName & name) static
Select constructed from filename (implicit extension)
Definition at line 53 of file edgeMeshNew.C.
References fileName::ext(), fileName::lessExt(), and edgeMesh::New().
declareMemberFunctionSelectionTable()
declareMemberFunctionSelectionTable (void , edgeMesh , write , fileExtension , (const fileName &name, const edgeMesh &mesh) , (name, mesh))
write() [1/2]
void write (const fileName & name, const edgeMesh & mesh) static
Write to file.
Definition at line 87 of file edgeMeshIO.C.
References Foam::endl(), Foam::exit(), fileName::ext(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, mesh, Foam::name(), and Foam::nl.
Referenced by edgeMesh::read(), edgeMesh::write(), and extendedEdgeMesh::writeObj().
transfer()
void transfer (edgeMesh & mesh)
Transfer the contents of the argument and annul the argument.
Definition at line 200 of file edgeMesh.C.
References List< T >::transfer().
Referenced by edgeMesh::read(), and extendedEdgeMesh::transfer().
xfer()
Foam::Xfer< Foam::edgeMesh > xfer ()
Transfer contents to the Xfer container.
Definition at line 208 of file edgeMesh.C.
References Foam::xferMove().
read() [1/2]
bool read (const fileName & name, const word & ext)
Read from file. Chooses reader based on explicit extension.
Definition at line 75 of file edgeMeshIO.C.
References edgeMesh::New(), edgeMesh::transfer(), and edgeMesh::write().
Referenced by edgeMesh::edgeMesh(), and edgeMesh::read().
read() [2/2]
bool read (const fileName & name) virtual
Read from file. Chooses reader based on detected extension.
Reimplemented in extendedEdgeMesh, STARCDedgeFormat, edgeMeshFormat, VTKedgeFormat, OBJedgeFormat, NASedgeFormat, extendedFeatureEdgeMeshFormat, and extendedEdgeMeshFormat.
Definition at line 58 of file edgeMeshIO.C.
References fileName::ext(), fileName::lessExt(), and edgeMesh::read().
points()
const Foam::pointField & points () const inline
Return points.
Definition at line 39 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::allNearestFeaturePoints(), extendedEdgeMesh::edgeTree(), extendedEdgeMesh::edgeTreesByType(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), extendedEdgeMesh::flipNormals(), Foam::operator<<(), extendedEdgeMesh::pointTree(), STARCDedgeFormat::read(), refinementFeatures::regionEdgeTrees(), OBJedgeFormat::write(), VTKedgeFormat::write(), edgeMeshFormat::write(), STARCDedgeFormat::write(), extendedEdgeMesh::writeObj(), edgeMesh::writeStats(), and extendedEdgeMesh::writeStats().
edges()
const Foam::edgeList & edges () const inline
Return edges.
Definition at line 45 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::edgeDirection(), extendedEdgeMesh::edgeTree(), extendedEdgeMesh::edgeTreesByType(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), extendedEdgeMesh::flipNormals(), Foam::operator<<(), refinementFeatures::regionEdgeTrees(), OBJedgeFormat::write(), VTKedgeFormat::write(), edgeMeshFormat::write(), STARCDedgeFormat::write(), extendedEdgeMesh::writeObj(), edgeMesh::writeStats(), and extendedEdgeMesh::writeStats().
pointEdges()
const Foam::labelListList & pointEdges () const inline
Return edges.
Definition at line 51 of file edgeMeshI.H.
Referenced by edgeMesh::regions(), and extendedEdgeMesh::writeObj().
regions()
Foam::label regions (labelList & edgeRegion) const
Find connected regions. Set region number per edge.
Returns number of regions.
Definition at line 214 of file edgeMesh.C.
References List< T >::append(), Foam::e, forAll, edgeMesh::pointEdges(), List< T >::setSize(), List< T >::size(), and List< T >::transfer().
clear()
void clear () virtual
Clear all storage.
Reimplemented in extendedEdgeMesh.
Definition at line 169 of file edgeMesh.C.
References List< T >::clear(), and edgeMesh::reset().
Referenced by extendedEdgeMesh::clear(), OBJedgeFormat::read(), and STARCDedgeFormat::read().
reset()
void reset (const Xfer< pointField > & points, const Xfer< edgeList > & edges) virtual
Reset primitive data (points, edges)
Note, optimized to avoid overwriting data (with Xfer::null)
Definition at line 178 of file edgeMesh.C.
References Foam::notNull(), and List< T >::transfer().
Referenced by extendedEdgeMesh::add(), edgeMesh::clear(), and extendedEdgeMesh::flipNormals().
scalePoints()
void scalePoints (const scalar scaleFactor) virtual
Scale points. A non-positive factor is ignored.
Definition at line 279 of file edgeMesh.C.
mergePoints()
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
Definition at line 289 of file edgeMesh.C.
References Foam::e, forAll, forAllConstIter(), Foam::mergePoints(), List< T >::setSize(), List< T >::size(), List< T >::transfer(), and VectorSpace< Vector< scalar >, scalar, 3 >::zero.
mergeEdges()
void mergeEdges ()
Merge similar edges.
Definition at line 358 of file edgeMesh.C.
References Foam::e, Foam::endl(), forAll, forAllConstIter(), Foam::Info, List< T >::setSize(), and List< T >::size().
writeStats()
void writeStats (Ostream & os) const virtual
Reimplemented in extendedEdgeMesh.
Definition at line 117 of file edgeMeshIO.C.
References edgeMesh::edges(), Foam::endl(), Foam::indent(), Foam::nl, edgeMesh::points(), and List< T >::size().
Referenced by extendedEdgeMesh::writeStats().
write() [2/2]
virtual void write (const fileName & name) const inline virtual
Generic write routine. Chooses writer based on extension.
Reimplemented in STARCDedgeFormat, edgeMeshFormat, VTKedgeFormat, and OBJedgeFormat.
Definition at line 261 of file edgeMesh.H.
References edgeMesh::operator<<, edgeMesh::operator=(), edgeMesh::operator>>, and edgeMesh::write().
operator=()
void operator= (const edgeMesh & rhs) inline
Definition at line 75 of file edgeMeshI.H.
Referenced by edgeMesh::write().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const edgeMesh &) friend
Referenced by edgeMesh::write().
operator>>
Istream& operator>> (Istream & , edgeMesh &) friend
Referenced by edgeMesh::write().
The documentation for this class was generated from the following files:
src/edgeMesh/edgeMesh.H
src/edgeMesh/edgeMesh.C
src/edgeMesh/edgeMeshI.H
src/edgeMesh/edgeMeshIO.C
src/edgeMesh/edgeMeshNew.C