OpenFOAM: extendedEdgeMeshFormat Class Reference
extendedEdgeMeshFormat Class Reference
Provide a means of reading/writing the single-file OpenFOAM extendedEdgeMesh format.
Public Member Functions
extendedEdgeMeshFormat (const fileName &)
Construct from file name.
virtual ~extendedEdgeMeshFormat ()
Destructor.
virtual bool read (const fileName &)
Read from file.
Public Member Functions inherited from extendedEdgeMesh
TypeName ("extendedEdgeMesh")
Runtime type information.
extendedEdgeMesh ()
Construct null.
extendedEdgeMesh (const extendedEdgeMesh &)
Construct as copy.
extendedEdgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
extendedEdgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
extendedEdgeMesh (Istream &)
Construct from Istream.
extendedEdgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges)
extendedEdgeMesh (const surfaceFeatures &sFeat, const boolList &surfBaffleRegions)
Construct given a surface with selected edges,point.
extendedEdgeMesh (const PrimitivePatch< face, List, pointField, point > &surf, const labelList &featureEdges, const labelList &regionFeatureEdges, const labelList &featurePoints)
Construct from PrimitivePatch.
extendedEdgeMesh (const pointField &pts, const edgeList &eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField &normals, const List< sideVolumeType > &normalVolumeTypes, const vectorField &edgeDirections, const labelListList &normalDirections, const labelListList &edgeNormals, const labelListList &featurePointNormals, const labelListList &featurePointEdges, const labelList &regionEdges)
Construct from all components.
declareRunTimeSelectionTable (autoPtr, extendedEdgeMesh, fileExtension,(const fileName &name),(name))
~extendedEdgeMesh ()
Destructor.
void nearestFeaturePoint (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
Find nearest surface edge for the sample point.
void nearestFeatureEdge (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
Find nearest surface edge for the sample point.
void nearestFeatureEdge (const pointField &samples, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
Find nearest surface edge for each sample point.
void nearestFeatureEdgeByType (const point &sample, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
Find the nearest point on each type of feature edge.
void allNearestFeaturePoints (const point &sample, scalar searchRadiusSqr, List< pointIndexHit > &info) const
Find all the feature points within searchDistSqr of sample.
void allNearestFeatureEdges (const point &sample, const scalar searchRadiusSqr, List< pointIndexHit > &info) const
Find all the feature edges within searchDistSqr of sample.
label convexStart () const
Return the index of the start of the convex feature points.
label concaveStart () const
Return the index of the start of the concave feature points.
label mixedStart () const
Return the index of the start of the mixed type feature points.
label nonFeatureStart () const
Return the index of the start of the non-feature points.
label externalStart () const
Return the index of the start of the external feature edges.
label internalStart () const
Return the index of the start of the internal feature edges.
label flatStart () const
Return the index of the start of the flat feature edges.
label openStart () const
Return the index of the start of the open feature edges.
label multipleStart () const
Return the index of the start of the multiply-connected feature.
bool featurePoint (label ptI) const
Return whether or not the point index is a feature point.
const vectorField & normals () const
Return the normals of the surfaces adjacent to the feature edges.
const List< sideVolumeType > & normalVolumeTypes () const
Return.
const vectorField & edgeDirections () const
Return the edgeDirection vectors.
const labelListList & normalDirections () const
vector edgeDirection (label edgeI, label ptI) const
Return the direction of edgeI, pointing away from ptI.
const labelListList & edgeNormals () const
Return the indices of the normals that are adjacent to the.
vectorField edgeNormals (const labelList &edgeNormIs) const
Return the normal vectors for a given set of normal indices.
vectorField edgeNormals (label edgeI) const
Return the normal vectors for a given edge.
const labelListList & featurePointNormals () const
Return the indices of the normals that are adjacent to the.
vectorField featurePointNormals (label ptI) const
Return the normal vectors for a given feature point.
const labelListList & featurePointEdges () const
Return the edge labels for a given feature point. Edges are.
const labelList & regionEdges () const
Return the feature edges which are on the boundary between.
pointStatus getPointStatus (label ptI) const
Return the pointStatus of a specified point.
edgeStatus getEdgeStatus (label edgeI) const
Return the edgeStatus of a specified edge.
PackedList< 2 > edgeBaffles (label edgeI) const
Return the baffle faces of a specified edge.
const indexedOctree< treeDataPoint > & pointTree () const
Demand driven construction of octree for feature points.
const indexedOctree< treeDataEdge > & edgeTree () const
Demand driven construction of octree for boundary edges.
const PtrList< indexedOctree< treeDataEdge > > & edgeTreesByType () const
Demand driven construction of octree for boundary edges by type.
void transfer (extendedEdgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< extendedEdgeMesh > xfer ()
Transfer contents to the Xfer container.
virtual void clear ()
Clear all storage.
void add (const extendedEdgeMesh &)
Add extendedEdgeMesh. No filtering of duplicates.
void flipNormals ()
Flip normals. All concave become convex, all internal external.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
void writeObj (const fileName &prefix) const
Write all components of the extendedEdgeMesh as obj files.
virtual void writeStats (Ostream &os) const
Dump some information.
Public Member Functions inherited from edgeMesh
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const pointField &, const edgeList &)
Construct from components.
edgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges).
edgeMesh (const edgeMesh &)
Construct as copy.
edgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
edgeMesh (Istream &)
Construct from Istream.
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< edgeMesh > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void reset (const Xfer< pointField > &points, const Xfer< edgeList > &edges)
Reset primitive data (points, edges)
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
void mergeEdges ()
Merge similar edges.
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void operator= (const edgeMesh &)
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Additional Inherited Members
Public Types inherited from extendedEdgeMesh
enum pointStatus { CONVEX, CONCAVE, MIXED, NONFEATURE }
enum edgeStatus {
EXTERNAL, INTERNAL, FLAT, OPEN,
MULTIPLE, NONE
}
enum sideVolumeType { INSIDE = 0, OUTSIDE = 1, BOTH = 2, NEITHER = 3 }
Normals point to the outside.
Static Public Member Functions inherited from extendedEdgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< extendedEdgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< extendedEdgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static edgeStatus classifyEdge (const List< vector > &norms, const labelList &edNorms, const vector &fC0tofC1)
Classify the type of feature edge. Requires face centre 0 to face.
Static Public Member Functions inherited from edgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const edgeMesh &)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Static Public Attributes inherited from extendedEdgeMesh
static const Foam::NamedEnum< pointStatus, 4 > pointStatusNames_
static const Foam::NamedEnum< edgeStatus, 6 > edgeStatusNames_
static const Foam::NamedEnum< sideVolumeType, 4 > sideVolumeTypeNames_
static scalar cosNormalAngleTol_
Angular closeness tolerance for treating normals as the same.
static label nPointTypes = 4
Number of possible point types (i.e. number of slices)
static label nEdgeTypes = 5
Number of possible feature edge types (i.e. number of slices)
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Member Functions inherited from extendedEdgeMesh
pointStatus classifyFeaturePoint (label ptI) const
Classify the type of feature point. Requires valid stored member.
template<class Patch >
void sortPointsAndEdges (const Patch &, const labelList &featureEdges, const labelList &regionFeatureEdges, const labelList &feaurePoints)
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (IFstream &)
Read non-comment line.
Protected Attributes inherited from extendedEdgeMesh
label concaveStart_
Index of the start of the concave feature points.
label mixedStart_
Index of the start of the mixed type feature points.
label nonFeatureStart_
Index of the start of the non-feature points.
label internalStart_
Index of the start of the internal feature edges.
label flatStart_
Index of the start of the flat feature edges.
label openStart_
Index of the start of the open feature edges.
label multipleStart_
Index of the start of the multiply-connected feature edges.
vectorField normals_
Normals of the features, to be referred to by index by both feature.
List< sideVolumeType > normalVolumeTypes_
Type per normal: which side of normal to mesh.
vectorField edgeDirections_
Flat and open edges require the direction of the edge.
labelListList normalDirections_
Starting directions for the edges.
labelListList edgeNormals_
Indices of the normals that are adjacent to the feature edges.
labelListList featurePointNormals_
Indices of the normals that are adjacent to the feature points.
labelListList featurePointEdges_
Indices of feature edges attached to feature points. The edges are.
labelList regionEdges_
Feature edges which are on the boundary between regions.
autoPtr< indexedOctree< treeDataPoint > > pointTree_
Search tree for all feature points.
autoPtr< indexedOctree< treeDataEdge > > edgeTree_
Search tree for all edges.
PtrList< indexedOctree< treeDataEdge > > edgeTreesByType_
Individual search trees for each type of edge.
Static Protected Attributes inherited from extendedEdgeMesh
static label convexStart_ = 0
Index of the start of the convex feature points - static as 0.
static label externalStart_ = 0
Index of the start of the external feature edges - static as 0.
Detailed Description
Provide a means of reading/writing the single-file OpenFOAM extendedEdgeMesh format.
Source files
extendedEdgeMeshFormat.H
extendedEdgeMeshFormat.C
Definition at line 51 of file extendedEdgeMeshFormat.H.
Constructor & Destructor Documentation
extendedEdgeMeshFormat()
extendedEdgeMeshFormat (const fileName & filename)
Construct from file name.
Definition at line 34 of file extendedEdgeMeshFormat.C.
References Foam::read(), and extendedEdgeMeshFormat::read().
~extendedEdgeMeshFormat()
virtual ~extendedEdgeMeshFormat () inline virtual
Destructor.
Definition at line 73 of file extendedEdgeMeshFormat.H.
References extendedEdgeMeshFormat::read().
Member Function Documentation
read()
bool read (const fileName & filename) virtual
Read from file.
Reimplemented from extendedEdgeMesh.
Definition at line 45 of file extendedEdgeMeshFormat.C.
References clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOobject::filePath(), IOstream::good(), IOobject::headerOk(), fileName::name(), fileName::path(), and IOobject::readHeader().
Referenced by extendedEdgeMeshFormat::extendedEdgeMeshFormat(), and extendedEdgeMeshFormat::~extendedEdgeMeshFormat().
The documentation for this class was generated from the following files:
src/edgeMesh/extendedEdgeMesh/extendedEdgeMeshFormats/extendedEdgeMeshFormat/extendedEdgeMeshFormat.H
src/edgeMesh/extendedEdgeMesh/extendedEdgeMeshFormats/extendedEdgeMeshFormat/extendedEdgeMeshFormat.C