OpenFOAM: engineTime Class Reference
engineTime Class Reference
Manage time in terms of engine RPM and crank-angle.
Public Member Functions
engineTime (const word &name, const fileName &rootPath, const fileName &caseName, const fileName &systemName="system", const fileName &constantName="constant", const fileName &dictName="engineGeometry")
Construct from objectRegistry arguments.
virtual ~engineTime ()
Destructor.
scalar degToTime (const scalar theta) const
Convert degrees to seconds (for given engine speed in RPM)
scalar timeToDeg (const scalar t) const
Convert seconds to degrees (for given engine speed in RPM)
scalar pistonPosition (const scalar theta) const
Calculate the piston position from the engine geometry.
const IOdictionary & engineDict () const
Return the engine geometry dictionary.
const dimensionedScalar & rpm () const
Return the engines current operating RPM.
const dimensionedScalar & conRodLength () const
Return the engines connecting-rod length.
const dimensionedScalar & bore () const
Return the engines bore.
const dimensionedScalar & stroke () const
Return the engines stroke.
const dimensionedScalar & clearance () const
Return the engines clearance-gap.
scalar theta () const
Return current crank-angle.
scalar thetaRevolution () const
Return current crank-angle translated to a single revolution.
scalar deltaTheta () const
Return crank-angle increment.
dimensionedScalar pistonPosition () const
Return current piston position.
dimensionedScalar pistonDisplacement () const
Return piston displacement for current time step.
dimensionedScalar pistonSpeed () const
Return piston speed for current time step.
virtual scalar userTimeToTime (const scalar theta) const
Convert the user-time (CA deg) to real-time (s).
virtual scalar timeToUserTime (const scalar t) const
Convert the real-time (s) into user-time (CA deg)
virtual void readDict ()
Read the control dictionary and set the write controls etc.
virtual bool read ()
Read the controlDict and set all the parameters.
Public Member Functions inherited from Time
TypeName ("time")
Time (const word &name, const argList &args, const word &systemName="system", const word &constantName="constant")
Construct given name of dictionary to read and argument list.
Time (const word &name, const fileName &rootPath, const fileName &caseName, const word &systemName="system", const word &constantName="constant", const bool enableFunctionObjects=true)
Construct given name of dictionary to read, rootPath and casePath.
Time (const dictionary &dict, const fileName &rootPath, const fileName &caseName, const word &systemName="system", const word &constantName="constant", const bool enableFunctionObjects=true)
Construct given dictionary, rootPath and casePath.
Time (const fileName &rootPath, const fileName &caseName, const word &systemName="system", const word &constantName="constant", const bool enableFunctionObjects=true)
Construct given endTime, rootPath and casePath.
virtual ~Time ()
Destructor.
const fileName & rootPath () const
Return root path.
const fileName & caseName () const
Return case name.
fileName path () const
Return path.
const dictionary & controlDict () const
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
fileName timePath () const
Return current time path.
IOstream::streamFormat writeFormat () const
Default write format.
IOstream::versionNumber writeVersion () const
Default write version number.
IOstream::compressionType writeCompression () const
Default write compression.
const word & graphFormat () const
Default graph format.
const Switch & runTimeModifiable () const
Supports re-reading.
void readModifiedObjects ()
Read the objects that have been modified.
label addWatch (const fileName &) const
Add watching of a file. Returns handle.
bool removeWatch (const label) const
Remove watch on a file (using handle)
const fileName & getFile (const label) const
Get name of file being watched (using handle)
fileMonitor::fileState getState (const label) const
Get current state of file (using handle)
void setUnmodified (const label) const
Set current state of file (using handle) to unmodified.
word findInstance (const fileName &dir, const word &name=word::null, const IOobject::readOption rOpt=IOobject::MUST_READ, const word &stopInstance=word::null) const
Return the location of "dir" containing the file "name".
instantList times () const
Search the case for valid time directories.
word findInstancePath (const instant &) const
Search the case for the time directory path.
instant findClosestTime (const scalar) const
Search the case for the time closest to the given time.
virtual bool writeTimeDict () const
Write time dictionary to the <time>/uniform directory.
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
bool writeNow ()
Write the objects now (not at end of iteration) and continue.
bool writeAndEnd ()
Write the objects now (not at end of iteration) and end the run.
void writeOnce ()
Write the objects once (one shot) and continue the run.
virtual word timeName () const
Return current time name.
virtual label startTimeIndex () const
Return start time index.
virtual dimensionedScalar startTime () const
Return start time.
virtual dimensionedScalar endTime () const
Return end time.
const functionObjectList & functionObjects () const
Return the list of function objects.
const dlLibraryTable & libs () const
External access to the loaded libraries.
dlLibraryTable & libs ()
External access to the loaded libraries.
bool subCycling () const
Return true if time currently being sub-cycled, otherwise false.
const TimeState & prevTimeState () const
Return previous TimeState if time is being sub-cycled.
virtual bool run () const
Return true if run should continue,.
virtual bool loop ()
Return true if run should continue and if so increment time.
virtual bool end () const
Return true if end of run,.
virtual bool stopAt (const stopAtControls) const
Adjust the current stopAtControl. Note that this value.
virtual void setTime (const Time &)
Reset the time and time-index to those of the given time.
virtual void setTime (const instant &, const label newIndex)
Reset the time and time-index.
virtual void setTime (const dimensionedScalar &, const label newIndex)
Reset the time and time-index.
virtual void setTime (const scalar, const label newIndex)
Reset the time and time-index.
virtual void setEndTime (const dimensionedScalar &)
Reset end time.
virtual void setEndTime (const scalar)
Reset end time.
virtual void setDeltaT (const dimensionedScalar &, const bool adjustDeltaT=true)
Reset time step.
virtual void setDeltaT (const scalar, const bool adjustDeltaT=true)
Reset time step.
virtual TimeState subCycle (const label nSubCycles)
Set time to sub-cycle for the given number of steps.
virtual void endSubCycle ()
Reset time after sub-cycling back to previous TimeState.
functionObjectList & functionObjects ()
Return non-const access to the list of function objects.
virtual Time & operator+= (const dimensionedScalar &)
Set deltaT to that specified and increment time via operator++()
virtual Time & operator+= (const scalar)
Set deltaT to that specified and increment time via operator++()
virtual Time & operator++ ()
Prefix increment,.
virtual Time & operator++ (int)
Postfix increment, this is identical to the prefix increment.
Public Member Functions inherited from clock
clock ()
Null constructor which stores the start time.
time_t elapsedClockTime () const
Returns wall-clock time from clock instantiation.
time_t clockTimeIncrement () const
Returns wall-clock time from last call of clockTimeIncrement()
Public Member Functions inherited from cpuTime
cpuTime ()
Construct with the current clock time.
double elapsedCpuTime () const
Return CPU time (in seconds) from the start.
double cpuTimeIncrement () const
Return CPU time (in seconds) since last call to cpuTimeIncrement()
Public Member Functions inherited from TimePaths
TimePaths (const fileName &rootPath, const fileName &caseName, const word &systemName, const word &constantName)
Construct given database name, rootPath and casePath.
TimePaths (const bool processorCase, const fileName &rootPath, const fileName &globalCaseName, const fileName &caseName, const word &systemName, const word &constantName)
Construct given database name, rootPath and casePath.
bool processorCase () const
Return true if this is a processor case.
const fileName & rootPath () const
Return root path.
const fileName & globalCaseName () const
Return global case name.
const fileName & caseName () const
Return case name.
const word & system () const
Return system name.
fileName caseSystem () const
Return system name for the case.
const word & constant () const
Return constant name.
fileName caseConstant () const
Return constant name for the case.
fileName path () const
Return path.
fileName systemPath () const
Return system path.
fileName constantPath () const
Return constant path.
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject *>
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< word, regIOobject * >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Foam::label erase (const HashTable< AnyType, word, AnyHash > &rhs)
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< word, regIOobject * >>)
Assignment to an initializer list.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from TimeState
TimeState ()
virtual ~TimeState ()
Destructor.
scalar timeOutputValue () const
Return current time value.
label timeIndex () const
Return current time index.
scalar deltaTValue () const
Return time step value.
scalar deltaT0Value () const
Return old time step value.
dimensionedScalar deltaT () const
Return time step.
dimensionedScalar deltaT0 () const
Return old time step.
bool writeTime () const
Return true if this is a write time.
bool outputTime () const
Return true if this is a write time.
Public Member Functions inherited from dimensioned< scalar >
dimensioned (const word &, const dimensionSet &, const scalar)
Construct given a name, a value and its dimensionSet.
dimensioned (const word &, const dimensioned< scalar > &)
Construct from a dimensioned<Type> changing the name.
dimensioned (const scalar &t)
Construct given a value (creates dimensionless value).
dimensioned (Istream &)
Construct from Istream.
dimensioned (const word &, Istream &)
Construct from an Istream with a given name.
dimensioned (const word &, const dimensionSet &, Istream &)
Construct from an Istream with a given name and dimensions.
dimensioned (const word &, const dimensionSet &, const dictionary &)
Construct from dictionary lookup with a given name and dimensions.
dimensioned ()
Null constructor.
const word & name () const
Return const reference to name.
word & name ()
Return non-const reference to name.
const dimensionSet & dimensions () const
Return const reference to dimensions.
dimensionSet & dimensions ()
Return non-const reference to dimensions.
const scalar & value () const
Return const reference to value.
scalar & value ()
Return non-const reference to value.
dimensioned< cmptType > component (const direction) const
Return a component as a dimensioned<cmptType>
void replace (const direction, const dimensioned< cmptType > &)
Return a component with a dimensioned<cmptType>
dimensioned< scalar > T () const
Return transpose.
void read (const dictionary &)
Update the value of dimensioned<Type>
Istream & read (Istream &is, const dictionary &)
Read value from stream and units from dictionary.
Istream & read (Istream &is, const HashTable< dimensionedScalar > &)
Read value from stream and units from table.
Istream & read (Istream &is)
Read value from stream and units from system table.
bool readIfPresent (const dictionary &)
Update the value of dimensioned<Type> if found in the dictionary.
dimensioned< cmptType > operator[] (const direction) const
Return a component as a dimensioned<cmptType>
void operator+= (const dimensioned< scalar > &)
void operator-= (const dimensioned< scalar > &)
void operator*= (const scalar)
void operator/= (const scalar)
Additional Inherited Members
Public Types inherited from Time
enum writeControls {
wcTimeStep, wcRunTime, wcAdjustableRunTime, wcClockTime,
wcCpuTime
}
Write control options.
enum stopAtControls { saEndTime, saNoWriteNow, saWriteNow, saNextWrite }
Stop-run control options.
enum fmtflags { general = 0, fixed = ios_base::fixed, scientific = ios_base::scientific }
Supported time directory name formats.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject *>
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Types inherited from dimensioned< scalar >
typedef pTraits< scalar >::cmptType cmptType
Component type.
Static Public Member Functions inherited from Time
static label findClosestTimeIndex (const instantList &, const scalar, const word &constantName="constant")
Search instantList for the time index closest to the given time.
static word timeName (const scalar, const int precision=precision_)
Return time name of given scalar time.
static instantList findTimes (const fileName &, const word &constantName="constant")
Search a given directory for valid time directories.
Static Public Member Functions inherited from clock
static time_t getTime ()
Get the current clock time in seconds.
static const struct tm rawDate ()
Return the current wall-clock date as a raw struct.
static string dateTime ()
Return the current wall-clock date/time as a string.
static string date ()
Return the current wall-clock date as a string.
static string clockTime ()
Return the current wall-clock time as a string.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Member Functions inherited from dimensioned< scalar >
static dimensioned< scalar > lookupOrDefault (const word &, const dictionary &, const dimensionSet &dims=dimless, const scalar &defaultValue=pTraits< scalar >::zero)
Construct from dictionary, with default dimensions and value.
static dimensioned< scalar > lookupOrDefault (const word &, const dictionary &, const scalar &defaultValue=pTraits< scalar >::zero)
Construct from dictionary dimensionless with value.
static dimensioned< scalar > lookupOrAddToDict (const word &, dictionary &, const dimensionSet &dims=dimless, const scalar &defaultValue=pTraits< scalar >::zero)
Construct from dictionary, with default value.
static dimensioned< scalar > lookupOrAddToDict (const word &, dictionary &, const scalar &defaultValue=pTraits< scalar >::zero)
Construct from dictionary, dimensionless with default value.
Static Public Attributes inherited from Time
static word controlDictName
The default control dictionary name (normally "controlDict")
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Protected Member Functions inherited from Time
void adjustDeltaT ()
Adjust the time step so that writing occurs at the specified time.
void setControls ()
Set the controls from the current controlDict.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes inherited from Time
label startTimeIndex_
scalar startTime_
scalar endTime_
stopAtControls stopAt_
writeControls writeControl_
scalar writeInterval_
label purgeWrite_
FIFOStack< word > previousWriteTimes_
bool writeOnce_
bool subCycling_
Is the time currently being sub-cycled?
autoPtr< TimeState > prevTimeState_
If time is being sub-cycled this is the previous TimeState.
sigWriteNow sigWriteNow_
Enable one-shot writing upon signal.
sigStopAtWriteNow sigStopAtWriteNow_
Enable write and clean exit upon signal.
Protected Attributes inherited from TimeState
label timeIndex_
scalar deltaT_
scalar deltaTSave_
scalar deltaT0_
bool deltaTchanged_
label writeTimeIndex_
bool writeTime_
Static Protected Attributes inherited from Time
static const NamedEnum< stopAtControls, 4 > stopAtControlNames_
static const NamedEnum< writeControls, 5 > writeControlNames_
static fmtflags format_
Time directory name format.
static int precision_
Time directory name precision.
static const int maxPrecision_
Maximum time directory name precision.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Manage time in terms of engine RPM and crank-angle.
When engineTime is in effect, the userTime is reported in degrees crank-angle instead of in seconds. The RPM to be used is specified in constant/engineGeometry. If only a time conversion is required, the geometric engine parameters can be dropped or set to zero.
For example,
    rpm             rpm  [0 0 -1 0 0]  2000;
    conRodLength    conRodLength  [0 1 0 0 0] 0.0;
    bore            bore          [0 1 0 0 0] 0.0;
    stroke          stroke        [0 1 0 0 0] 0.0;
    clearance       clearance     [0 1 0 0 0] 0.0;
Note
The engineTime can currently only be selected at compile-time.
Source files
engineTime.H
engineTime.C
Definition at line 68 of file engineTime.H.
Constructor & Destructor Documentation
engineTime()
engineTime (const word & name, const fileName & rootPath, const fileName & caseName, const fileName & systemName = "system", const fileName & constantName = "constant", const fileName & dictName = "engineGeometry")
Construct from objectRegistry arguments.
Definition at line 50 of file engineTime.C.
References engineTime::degToTime(), TimeState::deltaT0_, TimeState::deltaT_, TimeState::deltaTSave_, dictionary::readIfPresent(), Time::startTime_, and dimensioned< scalar >::value().
~engineTime()
virtual ~engineTime () inline virtual
Destructor.
Definition at line 113 of file engineTime.H.
References engineTime::degToTime(), engineTime::pistonPosition(), engineTime::theta(), and engineTime::timeToDeg().
Member Function Documentation
degToTime()
Foam::scalar degToTime (const scalar theta) const
Convert degrees to seconds (for given engine speed in RPM)
Definition at line 125 of file engineTime.C.
References dimensioned< Type >::value().
Referenced by engineTime::engineTime(), engineTime::userTimeToTime(), and engineTime::~engineTime().
timeToDeg()
Foam::scalar timeToDeg (const scalar t) const
Convert seconds to degrees (for given engine speed in RPM)
Definition at line 132 of file engineTime.C.
References dimensioned< Type >::value().
Referenced by engineTime::deltaTheta(), engineTime::theta(), engineTime::timeToUserTime(), and engineTime::~engineTime().
pistonPosition() [1/2]
Foam::scalar pistonPosition (const scalar theta) const
Calculate the piston position from the engine geometry.
and given crank angle.
Definition at line 171 of file engineTime.C.
References Foam::cos(), Foam::degToRad(), Foam::sin(), Foam::sqr(), Foam::sqrt(), and dimensioned< Type >::value().
engineDict()
const IOdictionary& engineDict () const inline
Return the engine geometry dictionary.
Definition at line 135 of file engineTime.H.
Referenced by fvMotionSolverEngineMesh::fvMotionSolverEngineMesh(), and layeredEngineMesh::layeredEngineMesh().
rpm()
const dimensionedScalar& rpm () const inline
Return the engines current operating RPM.
Definition at line 141 of file engineTime.H.
conRodLength()
const dimensionedScalar& conRodLength () const inline
Return the engines connecting-rod length.
Definition at line 147 of file engineTime.H.
bore()
const dimensionedScalar& bore () const inline
Return the engines bore.
Definition at line 153 of file engineTime.H.
stroke()
const dimensionedScalar& stroke () const inline
Return the engines stroke.
Definition at line 159 of file engineTime.H.
clearance()
const dimensionedScalar& clearance () const inline
Return the engines clearance-gap.
Definition at line 165 of file engineTime.H.
References engineTime::deltaTheta(), engineTime::pistonDisplacement(), engineTime::pistonPosition(), engineTime::pistonSpeed(), engineTime::read(), engineTime::readDict(), engineTime::theta(), engineTime::thetaRevolution(), engineTime::timeToUserTime(), and engineTime::userTimeToTime().
theta()
Foam::scalar theta () const
Return current crank-angle.
Definition at line 139 of file engineTime.C.
References engineTime::timeToDeg(), and dimensioned< scalar >::value().
Referenced by engineTime::clearance(), engineValve::curLift(), engineValve::curVelocity(), engineValve::isOpen(), engineTime::pistonDisplacement(), engineTime::pistonPosition(), engineTime::thetaRevolution(), and engineTime::~engineTime().
thetaRevolution()
Foam::scalar thetaRevolution () const
Return current crank-angle translated to a single revolution.
(value between -180 and 180 with 0 = top dead centre)
Definition at line 147 of file engineTime.C.
References engineTime::theta().
Referenced by engineTime::clearance().
deltaTheta()
Foam::scalar deltaTheta () const
Return crank-angle increment.
Definition at line 165 of file engineTime.C.
References TimeState::deltaTValue(), and engineTime::timeToDeg().
Referenced by engineTime::clearance(), engineValve::curVelocity(), and engineTime::pistonDisplacement().
pistonPosition() [2/2]
Foam::dimensionedScalar pistonPosition () const
Return current piston position.
Definition at line 190 of file engineTime.C.
References Foam::dimLength, and engineTime::theta().
Referenced by engineTime::clearance(), engineTime::pistonDisplacement(), and engineTime::~engineTime().
pistonDisplacement()
Foam::dimensionedScalar pistonDisplacement () const
Return piston displacement for current time step.
Definition at line 201 of file engineTime.C.
References engineTime::deltaTheta(), Foam::dimLength, engineTime::pistonPosition(), engineTime::theta(), and dimensioned< scalar >::value().
Referenced by engineTime::clearance(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), and engineTime::pistonSpeed().
pistonSpeed()
Foam::dimensionedScalar pistonSpeed () const
Return piston speed for current time step.
Definition at line 212 of file engineTime.C.
References TimeState::deltaTValue(), Foam::dimVelocity, engineTime::pistonDisplacement(), and dimensioned< scalar >::value().
Referenced by engineTime::clearance().
userTimeToTime()
Foam::scalar userTimeToTime (const scalar theta) const virtual
Convert the user-time (CA deg) to real-time (s).
Reimplemented from TimeState.
Definition at line 223 of file engineTime.C.
References engineTime::degToTime().
Referenced by engineTime::clearance().
timeToUserTime()
Foam::scalar timeToUserTime (const scalar t) const virtual
Convert the real-time (s) into user-time (CA deg)
Reimplemented from TimeState.
Definition at line 229 of file engineTime.C.
References engineTime::timeToDeg().
Referenced by engineTime::clearance().
readDict()
void readDict () virtual
Read the control dictionary and set the write controls etc.
Reimplemented from Time.
Definition at line 103 of file engineTime.C.
References Time::readDict().
Referenced by engineTime::clearance().
read()
bool read () virtual
Read the controlDict and set all the parameters.
Reimplemented from Time.
Definition at line 111 of file engineTime.C.
References Time::read().
Referenced by engineTime::clearance().
The documentation for this class was generated from the following files:
src/engine/engineTime/engineTime.H
src/engine/engineTime/engineTime.C