OpenFOAM: repatchPolyTopoChanger Class Reference
repatchPolyTopoChanger Class Reference
A mesh which allows changes in the patch distribution of the boundary faces. The change in patching is set using changePatchID. For a boundary face, a new patch ID is given.
Public Member Functions
repatchPolyTopoChanger (polyMesh &mesh)
Construct for given mesh.
virtual ~repatchPolyTopoChanger ()
Destructor.
void changePatches (const List< polyPatch *> &patches)
Change patches.
void changePatchID (const label faceID, const label patchID)
Change patch ID for a boundary face. Note: patchID should be in new.
void setFaceZone (const label faceID, const label zoneID, const bool zoneFlip)
Set zone ID for a face.
void changeAnchorPoint (const label faceID, const label fp)
Change anchor point (zero'th point of face) for a boundary face.
void repatch ()
Re-patch the mesh.
Detailed Description
A mesh which allows changes in the patch distribution of the boundary faces. The change in patching is set using changePatchID. For a boundary face, a new patch ID is given.
Source files
repatchPolyTopoChanger.H
repatchPolyTopoChanger.C
Definition at line 51 of file repatchPolyTopoChanger.H.
Constructor & Destructor Documentation
repatchPolyTopoChanger()
repatchPolyTopoChanger (polyMesh & mesh) explicit
Construct for given mesh.
Definition at line 52 of file repatchPolyTopoChanger.C.
References repatchPolyTopoChanger::changePatches().
~repatchPolyTopoChanger()
virtual ~repatchPolyTopoChanger () inline virtual
Destructor.
Definition at line 83 of file repatchPolyTopoChanger.H.
References repatchPolyTopoChanger::changeAnchorPoint(), repatchPolyTopoChanger::changePatches(), repatchPolyTopoChanger::changePatchID(), patches, repatchPolyTopoChanger::repatch(), and repatchPolyTopoChanger::setFaceZone().
Member Function Documentation
changePatches()
void changePatches (const List< polyPatch *> & patches)
Change patches.
Definition at line 62 of file repatchPolyTopoChanger.C.
References polyMesh::addPatches(), repatchPolyTopoChanger::changePatchID(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and polyMesh::removeBoundary().
Referenced by boundaryMesh::patchify(), repatchPolyTopoChanger::repatchPolyTopoChanger(), and repatchPolyTopoChanger::~repatchPolyTopoChanger().
changePatchID()
void changePatchID (const label faceID, const label patchID)
Change patch ID for a boundary face. Note: patchID should be in new.
numbering.
Definition at line 80 of file repatchPolyTopoChanger.C.
References Foam::abort(), polyMesh::boundaryMesh(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, faceZone::flipMap(), primitiveMesh::isInternalFace(), polyTopoChange::setAction(), repatchPolyTopoChanger::setFaceZone(), List< T >::size(), UPtrList< T >::size(), faceZone::whichFace(), and ZoneMesh< ZoneType, MeshType >::whichZone().
Referenced by repatchPolyTopoChanger::changePatches(), boundaryMesh::patchify(), and repatchPolyTopoChanger::~repatchPolyTopoChanger().
setFaceZone()
void setFaceZone (const label faceID, const label zoneID, const bool zoneFlip)
Set zone ID for a face.
Definition at line 132 of file repatchPolyTopoChanger.C.
References Foam::abort(), polyMesh::boundaryMesh(), repatchPolyTopoChanger::changeAnchorPoint(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, polyTopoChange::setAction(), List< T >::size(), and polyBoundaryMesh::whichPatch().
Referenced by repatchPolyTopoChanger::changePatchID(), and repatchPolyTopoChanger::~repatchPolyTopoChanger().
changeAnchorPoint()
void changeAnchorPoint (const label faceID, const label fp)
Change anchor point (zero'th point of face) for a boundary face.
Definition at line 168 of file repatchPolyTopoChanger.C.
References Foam::abort(), polyMesh::boundaryMesh(), f(), polyMesh::faceOwner(), polyMesh::faces(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, faceZone::flipMap(), forAll, polyTopoChange::setAction(), List< T >::size(), faceZone::whichFace(), polyBoundaryMesh::whichPatch(), and ZoneMesh< ZoneType, MeshType >::whichZone().
Referenced by repatchPolyTopoChanger::setFaceZone(), and repatchPolyTopoChanger::~repatchPolyTopoChanger().
repatch()
void repatch ()
Re-patch the mesh.
Definition at line 264 of file repatchPolyTopoChanger.C.
References polyTopoChange::changeMesh().
Referenced by boundaryMesh::patchify(), and repatchPolyTopoChanger::~repatchPolyTopoChanger().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/repatchPolyTopoChanger/repatchPolyTopoChanger.H
src/dynamicMesh/polyTopoChange/repatchPolyTopoChanger/repatchPolyTopoChanger.C