OpenFOAM: enrichedPatch Class Reference
enrichedPatch Class Reference
The enriched patch contains a double set of faces from the two sides of the sliding interface before the cutting.
Public Member Functions
ClassName ("enrichedPatch")
enrichedPatch (const primitiveFacePatch &masterPatch, const primitiveFacePatch &slavePatch, const labelList &slavePointPointHits, const labelList &slavePointEdgeHits, const List< objectHit > &slavePointFaceHits)
Construct from components.
~enrichedPatch ()
Destructor.
Map< point > & pointMap ()
Return non-const access to point map to add points.
const Map< point > & pointMap () const
Return map of points.
Map< label > & pointMergeMap ()
Return map of point merges.
const Map< label > & pointMergeMap () const
Return map of point merges.
void calcEnrichedFaces (const labelListList &pointsIntoMasterEdges, const labelListList &pointsIntoSlaveEdges, const pointField &projectedSlavePoints)
Calculate enriched faces.
const faceList & enrichedFaces () const
Return enriched faces.
const labelList & meshPoints () const
Return mesh points.
const faceList & localFaces () const
Return local faces.
const pointField & localPoints () const
Return local points.
const labelListList & pointPoints () const
Return point-point addressing.
const Map< labelList > & masterPointFaces () const
Master point face addressing.
const faceList & cutFaces () const
Return list of cut faces.
const labelList & cutFaceMaster () const
Return cut face master list.
const labelList & cutFaceSlave () const
Return cut face slave list.
bool checkSupport () const
Check if the patch is fully supported.
void writeOBJ (const fileName &) const
Debugging: dump graphical representation to obj format file.
Detailed Description
The enriched patch contains a double set of faces from the two sides of the sliding interface before the cutting.
The patch basically consists of two over-lapping sets of faces sitting on a common point support, where every edge may be shared by more than 2 faces. The patch points are collected in a map. Additional information needed for cutting is the point insertion into every edge of master and slave.
Note: If new points are created during master-slave edge cutting, they should be registred with the pointMap.
Source files
enrichedPatch.H
enrichedPatch.C
enrichedPatchCutFaces.C
enrichedPatchFaces.C
enrichedPatchPointMap.C
enrichedPatchPointMergeMap.C
enrichedPatchPointPoints.C
Definition at line 67 of file enrichedPatch.H.
Constructor & Destructor Documentation
enrichedPatch()
enrichedPatch (const primitiveFacePatch & masterPatch, const primitiveFacePatch & slavePatch, const labelList & slavePointPointHits, const labelList & slavePointEdgeHits, const List< objectHit > & slavePointFaceHits)
Construct from components.
Definition at line 136 of file enrichedPatch.C.
~enrichedPatch()
~enrichedPatch ()
Destructor.
Definition at line 170 of file enrichedPatch.C.
Member Function Documentation
ClassName()
ClassName ("enrichedPatch")
pointMap() [1/2]
Foam::Map< Foam::point > & pointMap ()
Return non-const access to point map to add points.
Definition at line 83 of file enrichedPatchPointMap.C.
pointMap() [2/2]
const Foam::Map< Foam::point > & pointMap () const
Return map of points.
Definition at line 94 of file enrichedPatchPointMap.C.
pointMergeMap() [1/2]
Map<label>& pointMergeMap () inline
Return map of point merges.
Definition at line 222 of file enrichedPatch.H.
pointMergeMap() [2/2]
const Map<label>& pointMergeMap () const inline
Return map of point merges.
Definition at line 228 of file enrichedPatch.H.
References enrichedPatch::calcEnrichedFaces(), enrichedPatch::checkSupport(), enrichedPatch::cutFaceMaster(), enrichedPatch::cutFaces(), enrichedPatch::cutFaceSlave(), enrichedPatch::enrichedFaces(), enrichedPatch::localFaces(), enrichedPatch::localPoints(), enrichedPatch::masterPointFaces(), enrichedPatch::meshPoints(), enrichedPatch::pointPoints(), and enrichedPatch::writeOBJ().
calcEnrichedFaces()
void calcEnrichedFaces (const labelListList & pointsIntoMasterEdges, const labelListList & pointsIntoSlaveEdges, const pointField & projectedSlavePoints)
Calculate enriched faces.
Definition at line 37 of file enrichedPatchFaces.C.
References Foam::abort(), Foam::constant::electromagnetic::e, HashTableCore::end(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), forAll, Foam::Info, Foam::magSqr(), Foam::max(), Foam::min(), Foam::nl, and List< T >::size().
Referenced by enrichedPatch::pointMergeMap().
enrichedFaces()
const Foam::faceList & enrichedFaces () const
Return enriched faces.
Definition at line 379 of file enrichedPatchFaces.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by enrichedPatch::pointMergeMap().
meshPoints()
const Foam::labelList & meshPoints () const
Return mesh points.
Definition at line 178 of file enrichedPatch.C.
Referenced by enrichedPatch::pointMergeMap().
localFaces()
const Foam::faceList & localFaces () const
Return local faces.
Definition at line 189 of file enrichedPatch.C.
Referenced by enrichedPatch::pointMergeMap().
localPoints()
const Foam::pointField & localPoints () const
Return local points.
Definition at line 200 of file enrichedPatch.C.
Referenced by enrichedPatch::pointMergeMap().
pointPoints()
const Foam::labelListList & pointPoints () const
Return point-point addressing.
Definition at line 211 of file enrichedPatch.C.
Referenced by enrichedPatch::pointMergeMap().
masterPointFaces()
const Foam::Map< Foam::labelList > & masterPointFaces () const
Master point face addressing.
Definition at line 148 of file enrichedPatchMasterPoints.C.
Referenced by enrichedPatch::pointMergeMap().
cutFaces()
const Foam::faceList & cutFaces () const
Return list of cut faces.
Definition at line 669 of file enrichedPatchCutFaces.C.
Referenced by enrichedPatch::pointMergeMap().
cutFaceMaster()
const Foam::labelList & cutFaceMaster () const
Return cut face master list.
Definition at line 680 of file enrichedPatchCutFaces.C.
Referenced by enrichedPatch::pointMergeMap().
cutFaceSlave()
const Foam::labelList & cutFaceSlave () const
Return cut face slave list.
Definition at line 691 of file enrichedPatchCutFaces.C.
Referenced by enrichedPatch::pointMergeMap().
checkSupport()
bool checkSupport () const
Check if the patch is fully supported.
Definition at line 222 of file enrichedPatch.C.
References Foam::endl(), forAll, found, and WarningInFunction.
Referenced by enrichedPatch::pointMergeMap().
writeOBJ()
void writeOBJ (const fileName & fName) const
Debugging: dump graphical representation to obj format file.
Definition at line 251 of file enrichedPatch.C.
References forAll, Foam::nl, and Foam::meshTools::writeOBJ().
Referenced by enrichedPatch::pointMergeMap().
The documentation for this class was generated from the following files:
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatch.H
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatch.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchCutFaces.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchFaces.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchMasterPoints.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchPointMap.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchPointPoints.C