OpenFOAM: extendedEdgeMesh Class Reference
extendedEdgeMesh Class Reference
Description of feature edges and points.
Public Types
enum pointStatus { CONVEX, CONCAVE, MIXED, NONFEATURE }
enum edgeStatus {
EXTERNAL, INTERNAL, FLAT, OPEN,
MULTIPLE, NONE
}
enum sideVolumeType { INSIDE = 0, OUTSIDE = 1, BOTH = 2, NEITHER = 3 }
Normals point to the outside.
Public Member Functions
TypeName ("extendedEdgeMesh")
Runtime type information.
extendedEdgeMesh ()
Construct null.
extendedEdgeMesh (const extendedEdgeMesh &)
Construct as copy.
extendedEdgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
extendedEdgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
extendedEdgeMesh (Istream &)
Construct from Istream.
extendedEdgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges)
extendedEdgeMesh (const surfaceFeatures &sFeat, const boolList &surfBaffleRegions)
Construct given a surface with selected edges,point.
extendedEdgeMesh (const PrimitivePatch< face, List, pointField, point > &surf, const labelList &featureEdges, const labelList &regionFeatureEdges, const labelList &featurePoints)
Construct from PrimitivePatch.
extendedEdgeMesh (const pointField &pts, const edgeList &eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField &normals, const List< sideVolumeType > &normalVolumeTypes, const vectorField &edgeDirections, const labelListList &normalDirections, const labelListList &edgeNormals, const labelListList &featurePointNormals, const labelListList &featurePointEdges, const labelList &regionEdges)
Construct from all components.
declareRunTimeSelectionTable (autoPtr, extendedEdgeMesh, fileExtension,(const fileName &name),(name))
~extendedEdgeMesh ()
Destructor.
void nearestFeaturePoint (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
Find nearest surface edge for the sample point.
void nearestFeatureEdge (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
Find nearest surface edge for the sample point.
void nearestFeatureEdge (const pointField &samples, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
Find nearest surface edge for each sample point.
void nearestFeatureEdgeByType (const point &sample, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
Find the nearest point on each type of feature edge.
void allNearestFeaturePoints (const point &sample, scalar searchRadiusSqr, List< pointIndexHit > &info) const
Find all the feature points within searchDistSqr of sample.
void allNearestFeatureEdges (const point &sample, const scalar searchRadiusSqr, List< pointIndexHit > &info) const
Find all the feature edges within searchDistSqr of sample.
label convexStart () const
Return the index of the start of the convex feature points.
label concaveStart () const
Return the index of the start of the concave feature points.
label mixedStart () const
Return the index of the start of the mixed type feature points.
label nonFeatureStart () const
Return the index of the start of the non-feature points.
label externalStart () const
Return the index of the start of the external feature edges.
label internalStart () const
Return the index of the start of the internal feature edges.
label flatStart () const
Return the index of the start of the flat feature edges.
label openStart () const
Return the index of the start of the open feature edges.
label multipleStart () const
Return the index of the start of the multiply-connected feature.
bool featurePoint (label ptI) const
Return whether or not the point index is a feature point.
const vectorField & normals () const
Return the normals of the surfaces adjacent to the feature edges.
const List< sideVolumeType > & normalVolumeTypes () const
Return.
const vectorField & edgeDirections () const
Return the edgeDirection vectors.
const labelListList & normalDirections () const
vector edgeDirection (label edgeI, label ptI) const
Return the direction of edgeI, pointing away from ptI.
const labelListList & edgeNormals () const
Return the indices of the normals that are adjacent to the.
vectorField edgeNormals (const labelList &edgeNormIs) const
Return the normal vectors for a given set of normal indices.
vectorField edgeNormals (label edgeI) const
Return the normal vectors for a given edge.
const labelListList & featurePointNormals () const
Return the indices of the normals that are adjacent to the.
vectorField featurePointNormals (label ptI) const
Return the normal vectors for a given feature point.
const labelListList & featurePointEdges () const
Return the edge labels for a given feature point. Edges are.
const labelList & regionEdges () const
Return the feature edges which are on the boundary between.
pointStatus getPointStatus (label ptI) const
Return the pointStatus of a specified point.
edgeStatus getEdgeStatus (label edgeI) const
Return the edgeStatus of a specified edge.
PackedList< 2 > edgeBaffles (label edgeI) const
Return the baffle faces of a specified edge.
const indexedOctree< treeDataPoint > & pointTree () const
Demand driven construction of octree for feature points.
const indexedOctree< treeDataEdge > & edgeTree () const
Demand driven construction of octree for boundary edges.
const PtrList< indexedOctree< treeDataEdge > > & edgeTreesByType () const
Demand driven construction of octree for boundary edges by type.
void transfer (extendedEdgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< extendedEdgeMesh > xfer ()
Transfer contents to the Xfer container.
virtual void clear ()
Clear all storage.
void add (const extendedEdgeMesh &)
Add extendedEdgeMesh. No filtering of duplicates.
void flipNormals ()
Flip normals. All concave become convex, all internal external.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &)
Read from file. Chooses reader based on detected extension.
void writeObj (const fileName &prefix) const
Write all components of the extendedEdgeMesh as obj files.
virtual void writeStats (Ostream &os) const
Dump some information.
Public Member Functions inherited from edgeMesh
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const pointField &, const edgeList &)
Construct from components.
edgeMesh (const Xfer< pointField > &, const Xfer< edgeList > &)
Construct by transferring components (points, edges).
edgeMesh (const edgeMesh &)
Construct as copy.
edgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
edgeMesh (Istream &)
Construct from Istream.
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< edgeMesh > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void reset (const Xfer< pointField > &points, const Xfer< edgeList > &edges)
Reset primitive data (points, edges)
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void mergePoints (const scalar mergeDist)
Merge common points (points within mergeDist)
void mergeEdges ()
Merge similar edges.
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void operator= (const edgeMesh &)
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()
Construct null.
virtual ~edgeMeshFormatsCore ()
Destructor.
Static Public Member Functions
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< extendedEdgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< extendedEdgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static edgeStatus classifyEdge (const List< vector > &norms, const labelList &edNorms, const vector &fC0tofC1)
Classify the type of feature edge. Requires face centre 0 to face.
Static Public Member Functions inherited from edgeMesh
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const edgeMesh &)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Static Public Attributes
static const Foam::NamedEnum< pointStatus, 4 > pointStatusNames_
static const Foam::NamedEnum< edgeStatus, 6 > edgeStatusNames_
static const Foam::NamedEnum< sideVolumeType, 4 > sideVolumeTypeNames_
static scalar cosNormalAngleTol_
Angular closeness tolerance for treating normals as the same.
static label nPointTypes = 4
Number of possible point types (i.e. number of slices)
static label nEdgeTypes = 5
Number of possible feature edge types (i.e. number of slices)
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Member Functions
pointStatus classifyFeaturePoint (label ptI) const
Classify the type of feature point. Requires valid stored member.
template<class Patch >
void sortPointsAndEdges (const Patch &, const labelList &featureEdges, const labelList &regionFeatureEdges, const labelList &feaurePoints)
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Protected Attributes
label concaveStart_
Index of the start of the concave feature points.
label mixedStart_
Index of the start of the mixed type feature points.
label nonFeatureStart_
Index of the start of the non-feature points.
label internalStart_
Index of the start of the internal feature edges.
label flatStart_
Index of the start of the flat feature edges.
label openStart_
Index of the start of the open feature edges.
label multipleStart_
Index of the start of the multiply-connected feature edges.
vectorField normals_
Normals of the features, to be referred to by index by both feature.
List< sideVolumeType > normalVolumeTypes_
Type per normal: which side of normal to mesh.
vectorField edgeDirections_
Flat and open edges require the direction of the edge.
labelListList normalDirections_
Starting directions for the edges.
labelListList edgeNormals_
Indices of the normals that are adjacent to the feature edges.
labelListList featurePointNormals_
Indices of the normals that are adjacent to the feature points.
labelListList featurePointEdges_
Indices of feature edges attached to feature points. The edges are.
labelList regionEdges_
Feature edges which are on the boundary between regions.
autoPtr< indexedOctree< treeDataPoint > > pointTree_
Search tree for all feature points.
autoPtr< indexedOctree< treeDataEdge > > edgeTree_
Search tree for all edges.
PtrList< indexedOctree< treeDataEdge > > edgeTreesByType_
Individual search trees for each type of edge.
Static Protected Attributes
static label convexStart_ = 0
Index of the start of the convex feature points - static as 0.
static label externalStart_ = 0
Index of the start of the external feature edges - static as 0.
Friends
Istream & operator>> (Istream &is, sideVolumeType &vt)
Ostream & operator<< (Ostream &os, const sideVolumeType &vt)
Ostream & operator<< (Ostream &, const extendedEdgeMesh &)
Istream & operator>> (Istream &, extendedEdgeMesh &)
Additional Inherited Members
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
Description of feature edges and points.
Feature points are a sorted subset at the start of the overall points list: 0 .. concaveStart_-1 : convex points (w.r.t normals) concaveStart_ .. mixedStart_-1 : concave points mixedStart_ .. nonFeatureStart_-1 : mixed internal/external points nonFeatureStart_ .. size-1 : non-feature points
Feature edges are the edgeList of the edgeMesh and are sorted: 0 .. internalStart_-1 : external edges (convex w.r.t normals) internalStart_ .. flatStart_-1 : internal edges (concave) flatStart_ .. openStart_-1 : flat edges (neither concave or convex) can arise from region interfaces on flat surfaces openStart_ .. multipleStart_-1 : open edges (e.g. from baffle surfaces) multipleStart_ .. size-1 : multiply connected edges
The edge direction and feature edge and feature point adjacent normals are stored.
Source files
extendedEdgeMesh.H
extendedEdgeMeshI.H
extendedEdgeMesh.C
extendedEdgeMeshNew.C
Definition at line 84 of file extendedEdgeMesh.H.
Member Enumeration Documentation
pointStatus
enum pointStatus
Enumerator
CONVEX
CONCAVE
MIXED
NONFEATURE
Definition at line 94 of file extendedEdgeMesh.H.
edgeStatus
enum edgeStatus
Enumerator
EXTERNAL
INTERNAL
FLAT
OPEN
MULTIPLE
NONE
Definition at line 104 of file extendedEdgeMesh.H.
sideVolumeType
enum sideVolumeType
Normals point to the outside.
Enumerator
INSIDE
OUTSIDE
BOTH
NEITHER
Definition at line 118 of file extendedEdgeMesh.H.
Constructor & Destructor Documentation
extendedEdgeMesh() [1/9]
extendedEdgeMesh ()
Construct null.
Definition at line 266 of file extendedEdgeMesh.C.
Referenced by extendedEdgeMesh::extendedEdgeMesh().
extendedEdgeMesh() [2/9]
extendedEdgeMesh (const extendedEdgeMesh & fem) explicit
Construct as copy.
Definition at line 291 of file extendedEdgeMesh.C.
extendedEdgeMesh() [3/9]
extendedEdgeMesh (const fileName & name)
Construct from file name (uses extension to determine type)
Definition at line 541 of file extendedEdgeMesh.C.
References extendedEdgeMesh::read().
extendedEdgeMesh() [4/9]
extendedEdgeMesh (const fileName & name, const word & ext)
Construct from file name (uses extension to determine type)
Definition at line 512 of file extendedEdgeMesh.C.
References extendedEdgeMesh::read().
extendedEdgeMesh() [5/9]
extendedEdgeMesh (Istream & is)
Construct from Istream.
Definition at line 317 of file extendedEdgeMesh.C.
References extendedEdgeMesh::extendedEdgeMesh().
extendedEdgeMesh() [6/9]
extendedEdgeMesh (const Xfer< pointField > & pointLst, const Xfer< edgeList > & edgeLst)
Construct by transferring components (points, edges)
Definition at line 324 of file extendedEdgeMesh.C.
References extendedEdgeMesh::extendedEdgeMesh().
extendedEdgeMesh() [7/9]
extendedEdgeMesh (const surfaceFeatures & sFeat, const boolList & surfBaffleRegions)
Construct given a surface with selected edges,point.
(surfaceFeatures), an objectRegistry and a fileName to write to. Extracts, classifies and reorders the data from surfaceFeatures.
Definition at line 352 of file extendedEdgeMesh.C.
References extendedEdgeMesh::BOTH, PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), extendedEdgeMesh::extendedEdgeMesh(), Foam::faceMap(), surfaceFeatures::featureEdges(), surfaceFeatures::featurePoints(), forAll, Foam::identity(), extendedEdgeMesh::INSIDE, extendedEdgeMesh::normals_, extendedEdgeMesh::normalVolumeTypes_, surfaceFeatures::nRegionEdges(), List< T >::setSize(), List< T >::size(), extendedEdgeMesh::sortPointsAndEdges(), and surfaceFeatures::surface().
extendedEdgeMesh() [8/9]
extendedEdgeMesh (const PrimitivePatch< face, List, pointField, point > & surf, const labelList & featureEdges, const labelList & regionFeatureEdges, const labelList & featurePoints)
Construct from PrimitivePatch.
Definition at line 431 of file extendedEdgeMesh.C.
References extendedEdgeMesh::extendedEdgeMesh(), and extendedEdgeMesh::sortPointsAndEdges().
extendedEdgeMesh() [9/9]
extendedEdgeMesh (const pointField & pts, const edgeList & eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField & normals, const List< sideVolumeType > & normalVolumeTypes, const vectorField & edgeDirections, const labelListList & normalDirections, const labelListList & edgeNormals, const labelListList & featurePointNormals, const labelListList & featurePointEdges, const labelList & regionEdges)
Construct from all components.
Definition at line 469 of file extendedEdgeMesh.C.
References extendedEdgeMesh::extendedEdgeMesh().
~extendedEdgeMesh()
~extendedEdgeMesh ()
Destructor.
Definition at line 569 of file extendedEdgeMesh.C.
Member Function Documentation
TypeName()
TypeName ("extendedEdgeMesh")
Runtime type information.
classifyFeaturePoint()
Foam::extendedEdgeMesh::pointStatus classifyFeaturePoint (label ptI) const protected
Classify the type of feature point. Requires valid stored member.
data for edges and normals.
Definition at line 175 of file extendedEdgeMesh.C.
References extendedEdgeMesh::classifyEdge(), forAll, and List< T >::size().
Referenced by extendedEdgeMesh::canRead().
sortPointsAndEdges()
void sortPointsAndEdges (const Patch & surf, const labelList & featureEdges, const labelList & regionFeatureEdges, const labelList & feaurePoints) protected
Definition at line 37 of file extendedEdgeMeshTemplates.C.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Vector< Cmpt >::centre(), Foam::cross(), edge::end(), UList< T >::end(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), forAll, Foam::identity(), Foam::inplaceRenumber(), Foam::inplaceReorder(), Foam::invert(), k, Foam::mag(), Foam::nl, points, DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), List< T >::setSize(), List< T >::size(), edge::start(), List< T >::transfer(), edge::vec(), vectorField(), Foam::xferMove(), and Foam::Zero.
Referenced by extendedEdgeMesh::extendedEdgeMesh().
canRead()
bool canRead (const fileName & name, const bool verbose = false) static
Can we read this file format?
Definition at line 157 of file extendedEdgeMesh.C.
References extendedEdgeMesh::classifyFeaturePoint(), fileName::ext(), and fileName::lessExt().
Referenced by extendedEdgeMesh::canWriteType().
canReadType()
bool canReadType (const word & ext, const bool verbose = false) static
Can we read this file format?
Definition at line 125 of file extendedEdgeMesh.C.
References extendedEdgeMesh::canWriteType().
Referenced by extendedEdgeMesh::writeTypes().
canWriteType()
bool canWriteType (const word & ext, const bool verbose = false) static
Can we write this file format type?
Definition at line 141 of file extendedEdgeMesh.C.
References extendedEdgeMesh::canRead().
Referenced by extendedEdgeMesh::canReadType().
readTypes()
Foam::wordHashSet readTypes () static
Definition at line 109 of file extendedEdgeMesh.C.
writeTypes()
Foam::wordHashSet writeTypes () static
Definition at line 115 of file extendedEdgeMesh.C.
References extendedEdgeMesh::canReadType().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , extendedEdgeMesh , fileExtension , (const fileName &name) , (name))
New() [1/2]
Foam::autoPtr< Foam::extendedEdgeMesh > New (const fileName & name, const word & ext) static
Select constructed from filename (explicit extension)
Definition at line 40 of file extendedEdgeMeshNew.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::name(), and Foam::nl.
Referenced by extendedEdgeMesh::read().
New() [2/2]
Foam::autoPtr< Foam::extendedEdgeMesh > New (const fileName & name) static
Select constructed from filename (implicit extension)
Definition at line 63 of file extendedEdgeMeshNew.C.
References fileName::ext(), fileName::lessExt(), and Foam::New().
nearestFeaturePoint()
void nearestFeaturePoint (const point & sample, scalar searchDistSqr, pointIndexHit & info) const
Find nearest surface edge for the sample point.
Definition at line 604 of file extendedEdgeMesh.C.
References extendedEdgeMesh::nearestFeatureEdge(), and extendedEdgeMesh::pointTree().
Referenced by extendedEdgeMesh::read().
nearestFeatureEdge() [1/2]
void nearestFeatureEdge (const point & sample, scalar searchDistSqr, pointIndexHit & info) const
Find nearest surface edge for the sample point.
Definition at line 619 of file extendedEdgeMesh.C.
References extendedEdgeMesh::edgeTree().
Referenced by extendedEdgeMesh::nearestFeatureEdge(), and extendedEdgeMesh::nearestFeaturePoint().
nearestFeatureEdge() [2/2]
void nearestFeatureEdge (const pointField & samples, const scalarField & searchDistSqr, List< pointIndexHit > & info) const
Find nearest surface edge for each sample point.
Definition at line 634 of file extendedEdgeMesh.C.
References forAll, extendedEdgeMesh::nearestFeatureEdge(), extendedEdgeMesh::nearestFeatureEdgeByType(), List< T >::setSize(), and List< T >::size().
nearestFeatureEdgeByType()
void nearestFeatureEdgeByType (const point & sample, const scalarField & searchDistSqr, List< pointIndexHit > & info) const
Find the nearest point on each type of feature edge.
Definition at line 655 of file extendedEdgeMesh.C.
References extendedEdgeMesh::allNearestFeaturePoints(), extendedEdgeMesh::edgeTreesByType(), extendedEdgeMesh::externalStart_, extendedEdgeMesh::flatStart_, forAll, extendedEdgeMesh::internalStart_, extendedEdgeMesh::multipleStart_, extendedEdgeMesh::openStart_, List< T >::setSize(), and UPtrList< T >::size().
Referenced by extendedEdgeMesh::nearestFeatureEdge().
allNearestFeaturePoints()
void allNearestFeaturePoints (const point & sample, scalar searchRadiusSqr, List< pointIndexHit > & info) const
Find all the feature points within searchDistSqr of sample.
Definition at line 691 of file extendedEdgeMesh.C.
References extendedEdgeMesh::allNearestFeatureEdges(), forAll, edgeMesh::points(), extendedEdgeMesh::pointTree(), List< T >::size(), and List< T >::transfer().
Referenced by extendedEdgeMesh::nearestFeatureEdgeByType().
allNearestFeatureEdges()
void allNearestFeatureEdges (const point & sample, const scalar searchRadiusSqr, List< pointIndexHit > & info) const
Find all the feature edges within searchDistSqr of sample.
Definition at line 722 of file extendedEdgeMesh.C.
References Foam::e, edgeMesh::edges(), extendedEdgeMesh::edgeTreesByType(), extendedEdgeMesh::externalStart_, extendedEdgeMesh::flatStart_, forAll, PointHit< Point >::hit(), extendedEdgeMesh::internalStart_, edge::line(), extendedEdgeMesh::multipleStart_, line< Point, PointRef >::nearestDist(), extendedEdgeMesh::openStart_, edgeMesh::points(), PointHit< Point >::rawPoint(), List< T >::setSize(), UPtrList< T >::size(), and List< T >::transfer().
Referenced by extendedEdgeMesh::allNearestFeaturePoints().
convexStart()
Foam::label convexStart () const inline
Return the index of the start of the convex feature points.
Definition at line 28 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::convexStart_.
concaveStart()
Foam::label concaveStart () const inline
Return the index of the start of the concave feature points.
Definition at line 34 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::concaveStart_.
Referenced by extendedEdgeMesh::add(), and extendedEdgeMesh::flipNormals().
mixedStart()
Foam::label mixedStart () const inline
Return the index of the start of the mixed type feature points.
Definition at line 40 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::mixedStart_.
Referenced by extendedEdgeMesh::add(), and extendedEdgeMesh::flipNormals().
nonFeatureStart()
Foam::label nonFeatureStart () const inline
Return the index of the start of the non-feature points.
Definition at line 46 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::nonFeatureStart_.
Referenced by extendedEdgeMesh::add().
externalStart()
Foam::label externalStart () const inline
Return the index of the start of the external feature edges.
Definition at line 52 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::externalStart_.
internalStart()
Foam::label internalStart () const inline
Return the index of the start of the internal feature edges.
Definition at line 58 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::internalStart_.
Referenced by extendedEdgeMesh::add(), and extendedEdgeMesh::flipNormals().
flatStart()
Foam::label flatStart () const inline
Return the index of the start of the flat feature edges.
Definition at line 64 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::flatStart_.
Referenced by extendedEdgeMesh::add(), and extendedEdgeMesh::flipNormals().
openStart()
Foam::label openStart () const inline
Return the index of the start of the open feature edges.
Definition at line 70 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::openStart_.
Referenced by extendedEdgeMesh::add().
multipleStart()
Foam::label multipleStart () const inline
Return the index of the start of the multiply-connected feature.
edges
Definition at line 76 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::multipleStart_.
Referenced by extendedEdgeMesh::add().
featurePoint()
bool featurePoint (label ptI) const inline
Return whether or not the point index is a feature point.
Definition at line 82 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::nonFeatureStart_.
Referenced by extendedEdgeMesh::featurePointNormals().
normals()
const Foam::vectorField & normals () const inline
Return the normals of the surfaces adjacent to the feature edges.
and points
Definition at line 88 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::normals_.
Referenced by extendedEdgeMesh::add(), and extendedEdgeMesh::flipNormals().
normalVolumeTypes()
const Foam::List< Foam::extendedEdgeMesh::sideVolumeType > & normalVolumeTypes () const inline
Return.
Definition at line 95 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::normalVolumeTypes_.
edgeDirections()
const Foam::vectorField & edgeDirections () const inline
Return the edgeDirection vectors.
Definition at line 101 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::edgeDirections_.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::edgeDirection(), and extendedEdgeMesh::flipNormals().
normalDirections()
const Foam::labelListList & normalDirections () const inline
Definition at line 109 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::edgeDirection(), and extendedEdgeMesh::normalDirections_.
edgeDirection()
Foam::vector edgeDirection (label edgeI, label ptI) const inline
Return the direction of edgeI, pointing away from ptI.
Definition at line 116 of file extendedEdgeMeshI.H.
References Foam::e, extendedEdgeMesh::edgeDirections(), edgeMesh::edges(), edge::end(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, edge::start(), and Foam::Zero.
Referenced by extendedEdgeMesh::normalDirections().
edgeNormals() [1/3]
const Foam::labelListList & edgeNormals () const inline
Return the indices of the normals that are adjacent to the.
feature edges
Definition at line 144 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::edgeNormals_.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::edgeNormals(), and extendedEdgeMesh::flipNormals().
edgeNormals() [2/3]
Foam::vectorField edgeNormals (const labelList & edgeNormIs) const inline
Return the normal vectors for a given set of normal indices.
Definition at line 152 of file extendedEdgeMeshI.H.
References forAll, extendedEdgeMesh::normals_, and List< T >::size().
edgeNormals() [3/3]
Foam::vectorField edgeNormals (label edgeI) const inline
Return the normal vectors for a given edge.
Definition at line 167 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::edgeNormals(), and extendedEdgeMesh::edgeNormals_.
featurePointNormals() [1/2]
const Foam::labelListList & featurePointNormals () const inline
Return the indices of the normals that are adjacent to the.
feature points
Definition at line 175 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::featurePointNormals_.
Referenced by extendedEdgeMesh::add(), and extendedEdgeMesh::flipNormals().
featurePointNormals() [2/2]
Foam::vectorField featurePointNormals (label ptI) const inline
Return the normal vectors for a given feature point.
Definition at line 182 of file extendedEdgeMeshI.H.
References Foam::endl(), extendedEdgeMesh::featurePoint(), extendedEdgeMesh::featurePointNormals_, forAll, extendedEdgeMesh::normals_, List< T >::size(), and WarningInFunction.
featurePointEdges()
const Foam::labelListList & featurePointEdges () const inline
Return the edge labels for a given feature point. Edges are.
ordered by the faces that they share. The edge labels correspond to the entry in edges().
Definition at line 210 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::featurePointEdges_.
regionEdges()
const Foam::labelList & regionEdges () const inline
Return the feature edges which are on the boundary between.
regions
Definition at line 216 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::regionEdges_.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::flipNormals(), and refinementFeatures::regionEdgeTrees().
getPointStatus()
Foam::extendedEdgeMesh::pointStatus getPointStatus (label ptI) const inline
Return the pointStatus of a specified point.
Definition at line 223 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::CONCAVE, extendedEdgeMesh::concaveStart_, extendedEdgeMesh::CONVEX, extendedEdgeMesh::MIXED, extendedEdgeMesh::mixedStart_, extendedEdgeMesh::NONFEATURE, and extendedEdgeMesh::nonFeatureStart_.
getEdgeStatus()
Foam::extendedEdgeMesh::edgeStatus getEdgeStatus (label edgeI) const inline
Return the edgeStatus of a specified edge.
Definition at line 245 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::edgeBaffles(), extendedEdgeMesh::EXTERNAL, extendedEdgeMesh::FLAT, extendedEdgeMesh::flatStart_, extendedEdgeMesh::INTERNAL, extendedEdgeMesh::internalStart_, extendedEdgeMesh::MULTIPLE, extendedEdgeMesh::multipleStart_, extendedEdgeMesh::OPEN, and extendedEdgeMesh::openStart_.
edgeBaffles()
Foam::PackedList< 2 > edgeBaffles (label edgeI) const inline
Return the baffle faces of a specified edge.
Definition at line 271 of file extendedEdgeMeshI.H.
References PackedList< nBits >::append(), extendedEdgeMesh::edgeNormals_, forAll, extendedEdgeMesh::normalVolumeTypes_, and List< T >::size().
Referenced by extendedEdgeMesh::getEdgeStatus().
pointTree()
const Foam::indexedOctree< Foam::treeDataPoint > & pointTree () const
Demand driven construction of octree for feature points.
Definition at line 778 of file extendedEdgeMesh.C.
References Foam::e, Foam::identity(), boundBox::max(), boundBox::min(), extendedEdgeMesh::nonFeatureStart_, edgeMesh::points(), extendedEdgeMesh::pointTree_, and rndGen().
Referenced by extendedEdgeMesh::allNearestFeaturePoints(), and extendedEdgeMesh::nearestFeaturePoint().
edgeTree()
const Foam::indexedOctree< Foam::treeDataEdge > & edgeTree () const
Demand driven construction of octree for boundary edges.
Definition at line 818 of file extendedEdgeMesh.C.
References Foam::e, edgeMesh::edges(), extendedEdgeMesh::edgeTree_, Foam::identity(), boundBox::max(), boundBox::min(), edgeMesh::points(), and rndGen().
Referenced by extendedEdgeMesh::nearestFeatureEdge().
edgeTreesByType()
const Foam::PtrList< Foam::indexedOctree< Foam::treeDataEdge > > & edgeTreesByType () const
Demand driven construction of octree for boundary edges by type.
Definition at line 860 of file extendedEdgeMesh.C.
References Foam::e, edgeMesh::edges(), extendedEdgeMesh::edgeTreesByType_, extendedEdgeMesh::externalStart_, extendedEdgeMesh::flatStart_, forAll, Foam::identity(), extendedEdgeMesh::internalStart_, boundBox::max(), boundBox::min(), extendedEdgeMesh::multipleStart_, extendedEdgeMesh::nEdgeTypes, extendedEdgeMesh::openStart_, edgeMesh::points(), and rndGen().
Referenced by extendedEdgeMesh::allNearestFeatureEdges(), and extendedEdgeMesh::nearestFeatureEdgeByType().
transfer()
void transfer (extendedEdgeMesh & mesh)
Transfer the contents of the argument and annul the argument.
Definition at line 924 of file extendedEdgeMesh.C.
References extendedEdgeMesh::concaveStart_, extendedEdgeMesh::edgeDirections_, extendedEdgeMesh::edgeNormals_, extendedEdgeMesh::edgeTree_, extendedEdgeMesh::edgeTreesByType_, extendedEdgeMesh::featurePointEdges_, extendedEdgeMesh::featurePointNormals_, extendedEdgeMesh::flatStart_, extendedEdgeMesh::internalStart_, extendedEdgeMesh::mixedStart_, extendedEdgeMesh::multipleStart_, extendedEdgeMesh::nonFeatureStart_, extendedEdgeMesh::normalDirections_, extendedEdgeMesh::normals_, extendedEdgeMesh::normalVolumeTypes_, extendedEdgeMesh::openStart_, extendedEdgeMesh::pointTree_, extendedEdgeMesh::regionEdges_, edgeMesh::transfer(), and List< T >::transfer().
Referenced by extendedEdgeMesh::read().
xfer()
Foam::Xfer< Foam::extendedEdgeMesh > xfer ()
Transfer contents to the Xfer container.
Definition at line 949 of file extendedEdgeMesh.C.
clear()
void clear () virtual
Clear all storage.
Reimplemented from edgeMesh.
Definition at line 955 of file extendedEdgeMesh.C.
References List< T >::clear(), edgeMesh::clear(), extendedEdgeMesh::concaveStart_, extendedEdgeMesh::edgeDirections_, extendedEdgeMesh::edgeNormals_, extendedEdgeMesh::edgeTree_, extendedEdgeMesh::edgeTreesByType_, extendedEdgeMesh::featurePointEdges_, extendedEdgeMesh::featurePointNormals_, extendedEdgeMesh::flatStart_, extendedEdgeMesh::internalStart_, extendedEdgeMesh::mixedStart_, extendedEdgeMesh::multipleStart_, extendedEdgeMesh::nonFeatureStart_, extendedEdgeMesh::normalDirections_, extendedEdgeMesh::normals_, extendedEdgeMesh::normalVolumeTypes_, extendedEdgeMesh::openStart_, extendedEdgeMesh::pointTree_, and extendedEdgeMesh::regionEdges_.
add()
void add (const extendedEdgeMesh & fem)
Add extendedEdgeMesh. No filtering of duplicates.
Definition at line 979 of file extendedEdgeMesh.C.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::append(), extendedEdgeMesh::concaveStart(), extendedEdgeMesh::concaveStart_, Foam::e, extendedEdgeMesh::edgeDirections(), extendedEdgeMesh::edgeDirections_, extendedEdgeMesh::edgeNormals(), extendedEdgeMesh::edgeNormals_, edgeMesh::edges(), extendedEdgeMesh::edgeTree_, extendedEdgeMesh::edgeTreesByType_, extendedEdgeMesh::featurePointNormals(), extendedEdgeMesh::featurePointNormals_, extendedEdgeMesh::flatStart(), extendedEdgeMesh::flatStart_, forAll, extendedEdgeMesh::internalStart(), extendedEdgeMesh::internalStart_, extendedEdgeMesh::mixedStart(), extendedEdgeMesh::mixedStart_, extendedEdgeMesh::multipleStart(), extendedEdgeMesh::multipleStart_, newPointi, extendedEdgeMesh::nonFeatureStart(), extendedEdgeMesh::nonFeatureStart_, extendedEdgeMesh::normals(), extendedEdgeMesh::normals_, extendedEdgeMesh::openStart(), extendedEdgeMesh::openStart_, edgeMesh::points(), extendedEdgeMesh::pointTree_, extendedEdgeMesh::regionEdges(), extendedEdgeMesh::regionEdges_, edgeMesh::reset(), Field< Type >::rmap(), List< T >::size(), List< T >::transfer(), List< T >::xfer(), and Foam::xferMove().
flipNormals()
void flipNormals ()
Flip normals. All concave become convex, all internal external.
etc.
Definition at line 1227 of file extendedEdgeMesh.C.
References extendedEdgeMesh::concaveStart(), extendedEdgeMesh::concaveStart_, Foam::e, extendedEdgeMesh::edgeDirections(), extendedEdgeMesh::edgeDirections_, extendedEdgeMesh::edgeNormals(), extendedEdgeMesh::edgeNormals_, edgeMesh::edges(), extendedEdgeMesh::edgeTree_, extendedEdgeMesh::edgeTreesByType_, extendedEdgeMesh::featurePointNormals(), extendedEdgeMesh::featurePointNormals_, extendedEdgeMesh::flatStart(), forAll, Foam::identity(), extendedEdgeMesh::internalStart(), extendedEdgeMesh::internalStart_, extendedEdgeMesh::mixedStart(), newPointi, extendedEdgeMesh::normals(), extendedEdgeMesh::normals_, edgeMesh::points(), extendedEdgeMesh::pointTree_, extendedEdgeMesh::regionEdges(), extendedEdgeMesh::regionEdges_, edgeMesh::reset(), Field< Type >::rmap(), List< T >::size(), List< T >::transfer(), extendedEdgeMesh::writeObj(), List< T >::xfer(), and Foam::xferMove().
read() [1/2]
bool read (const fileName & name, const word & ext)
Read from file. Chooses reader based on explicit extension.
Definition at line 592 of file extendedEdgeMesh.C.
References extendedEdgeMesh::nearestFeaturePoint(), extendedEdgeMesh::New(), and extendedEdgeMesh::transfer().
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and extendedEdgeMesh::read().
read() [2/2]
bool read (const fileName & name) virtual
Read from file. Chooses reader based on detected extension.
Reimplemented from edgeMesh.
Reimplemented in extendedEdgeMeshFormat.
Definition at line 575 of file extendedEdgeMesh.C.
References fileName::ext(), fileName::lessExt(), and extendedEdgeMesh::read().
writeObj()
void writeObj (const fileName & prefix) const
Write all components of the extendedEdgeMesh as obj files.
Definition at line 1336 of file extendedEdgeMesh.C.
References extendedEdgeMesh::concaveStart_, Foam::e, extendedEdgeMesh::edgeDirections_, edgeMesh::edges(), Foam::endl(), extendedEdgeMesh::externalStart_, extendedEdgeMesh::flatStart_, forAll, Foam::Info, extendedEdgeMesh::internalStart_, extendedEdgeMesh::mixedStart_, extendedEdgeMesh::multipleStart_, OFstream::name(), Foam::nl, extendedEdgeMesh::nonFeatureStart_, extendedEdgeMesh::openStart_, edgeMesh::pointEdges(), edgeMesh::points(), extendedEdgeMesh::regionEdges_, List< T >::size(), edge::start(), OBJstream::write(), and edgeMesh::write().
Referenced by extendedEdgeMesh::flipNormals().
writeStats()
void writeStats (Ostream & os) const virtual
Dump some information.
Reimplemented from edgeMesh.
Definition at line 1459 of file extendedEdgeMesh.C.
References extendedEdgeMesh::concaveStart_, extendedEdgeMesh::convexStart_, Foam::decrIndent(), edgeMesh::edges(), extendedEdgeMesh::externalStart_, extendedEdgeMesh::flatStart_, Foam::incrIndent(), Foam::indent(), extendedEdgeMesh::internalStart_, extendedEdgeMesh::mixedStart_, extendedEdgeMesh::multipleStart_, Foam::nl, extendedEdgeMesh::nonFeatureStart_, extendedEdgeMesh::openStart_, edgeMesh::points(), Foam::setw(), List< T >::size(), and edgeMesh::writeStats().
classifyEdge()
Foam::extendedEdgeMesh::edgeStatus classifyEdge (const List< vector > & norms, const labelList & edNorms, const vector & fC0tofC1) static
Classify the type of feature edge. Requires face centre 0 to face.
centre 1 vector to distinguish internal from external
Definition at line 222 of file extendedEdgeMesh.C.
References List< T >::size().
Referenced by extendedEdgeMesh::classifyFeaturePoint().
Friends And Related Function Documentation
operator>> [1/2]
Istream& operator>> (Istream & is, sideVolumeType & vt) friend
operator<< [1/2]
Ostream& operator<< (Ostream & os, const sideVolumeType & vt) friend
operator<< [2/2]
Ostream& operator<< (Ostream & , const extendedEdgeMesh &) friend
operator>> [2/2]
Istream& operator>> (Istream & , extendedEdgeMesh &) friend
Member Data Documentation
pointStatusNames_
const Foam::NamedEnum< Foam::extendedEdgeMesh::pointStatus, 4 > pointStatusNames_ static
Definition at line 102 of file extendedEdgeMesh.H.
Referenced by NamedEnum< directionType, 3 >::names().
edgeStatusNames_
const Foam::NamedEnum< Foam::extendedEdgeMesh::edgeStatus, 6 > edgeStatusNames_ static
Definition at line 115 of file extendedEdgeMesh.H.
Referenced by NamedEnum< directionType, 3 >::names().
sideVolumeTypeNames_
const Foam::NamedEnum< Foam::extendedEdgeMesh::sideVolumeType, 4 > sideVolumeTypeNames_ static
Definition at line 126 of file extendedEdgeMesh.H.
Referenced by NamedEnum< directionType, 3 >::names(), and searchablePlateFeatures::searchablePlateFeatures().
cosNormalAngleTol_
Foam::scalar cosNormalAngleTol_ static
Initial value:
=
    Foam::cos(degToRad(0.1))
Angular closeness tolerance for treating normals as the same.
Definition at line 129 of file extendedEdgeMesh.H.
Referenced by NamedEnum< directionType, 3 >::names().
convexStart_
Foam::label convexStart_ = 0 static protected
Index of the start of the convex feature points - static as 0.
Definition at line 137 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::convexStart(), NamedEnum< directionType, 3 >::names(), and extendedEdgeMesh::writeStats().
externalStart_
Foam::label externalStart_ = 0 static protected
Index of the start of the external feature edges - static as 0.
Definition at line 140 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::edgeTreesByType(), extendedEdgeMesh::externalStart(), NamedEnum< directionType, 3 >::names(), extendedEdgeMesh::nearestFeatureEdgeByType(), extendedEdgeMesh::writeObj(), and extendedEdgeMesh::writeStats().
concaveStart_
label concaveStart_ protected
Index of the start of the concave feature points.
Definition at line 146 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::concaveStart(), extendedEdgeMesh::flipNormals(), extendedEdgeMesh::getPointStatus(), Foam::operator<<(), Foam::operator>>(), extendedEdgeMesh::transfer(), extendedEdgeMesh::writeObj(), and extendedEdgeMesh::writeStats().
mixedStart_
label mixedStart_ protected
Index of the start of the mixed type feature points.
Definition at line 149 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::getPointStatus(), extendedEdgeMesh::mixedStart(), Foam::operator<<(), Foam::operator>>(), extendedEdgeMesh::transfer(), extendedEdgeMesh::writeObj(), and extendedEdgeMesh::writeStats().
nonFeatureStart_
label nonFeatureStart_ protected
Index of the start of the non-feature points.
Definition at line 152 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::featurePoint(), extendedEdgeMesh::getPointStatus(), extendedEdgeMesh::nonFeatureStart(), Foam::operator<<(), Foam::operator>>(), extendedEdgeMesh::pointTree(), extendedEdgeMesh::transfer(), extendedEdgeMesh::writeObj(), and extendedEdgeMesh::writeStats().
internalStart_
label internalStart_ protected
Index of the start of the internal feature edges.
Definition at line 155 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::clear(), extendedEdgeMesh::edgeTreesByType(), extendedEdgeMesh::flipNormals(), extendedEdgeMesh::getEdgeStatus(), extendedEdgeMesh::internalStart(), extendedEdgeMesh::nearestFeatureEdgeByType(), Foam::operator<<(), Foam::operator>>(), extendedEdgeMesh::transfer(), extendedEdgeMesh::writeObj(), and extendedEdgeMesh::writeStats().
flatStart_
label flatStart_ protected
Index of the start of the flat feature edges.
Definition at line 158 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::clear(), extendedEdgeMesh::edgeTreesByType(), extendedEdgeMesh::flatStart(), extendedEdgeMesh::getEdgeStatus(), extendedEdgeMesh::nearestFeatureEdgeByType(), Foam::operator<<(), Foam::operator>>(), extendedEdgeMesh::transfer(), extendedEdgeMesh::writeObj(), and extendedEdgeMesh::writeStats().
openStart_
label openStart_ protected
Index of the start of the open feature edges.
Definition at line 161 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::clear(), extendedEdgeMesh::edgeTreesByType(), extendedEdgeMesh::getEdgeStatus(), extendedEdgeMesh::nearestFeatureEdgeByType(), extendedEdgeMesh::openStart(), Foam::operator<<(), Foam::operator>>(), extendedEdgeMesh::transfer(), extendedEdgeMesh::writeObj(), and extendedEdgeMesh::writeStats().
multipleStart_
label multipleStart_ protected
Index of the start of the multiply-connected feature edges.
Definition at line 164 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::clear(), extendedEdgeMesh::edgeTreesByType(), extendedEdgeMesh::getEdgeStatus(), extendedEdgeMesh::multipleStart(), extendedEdgeMesh::nearestFeatureEdgeByType(), Foam::operator<<(), Foam::operator>>(), extendedEdgeMesh::transfer(), extendedEdgeMesh::writeObj(), and extendedEdgeMesh::writeStats().
normals_
vectorField normals_ protected
Normals of the features, to be referred to by index by both feature.
points and edges, unsorted
Definition at line 168 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::edgeNormals(), extendedEdgeMesh::extendedEdgeMesh(), extendedEdgeMesh::featurePointNormals(), extendedEdgeMesh::flipNormals(), extendedEdgeMesh::normals(), Foam::operator<<(), Foam::operator>>(), and extendedEdgeMesh::transfer().
normalVolumeTypes_
List<sideVolumeType> normalVolumeTypes_ protected
Type per normal: which side of normal to mesh.
Definition at line 171 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::clear(), extendedEdgeMesh::edgeBaffles(), extendedEdgeMesh::extendedEdgeMesh(), extendedEdgeMesh::normalVolumeTypes(), Foam::operator<<(), Foam::operator>>(), and extendedEdgeMesh::transfer().
edgeDirections_
vectorField edgeDirections_ protected
Flat and open edges require the direction of the edge.
Definition at line 174 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::edgeDirections(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), extendedEdgeMesh::flipNormals(), extendedEdgeMesh::transfer(), and extendedEdgeMesh::writeObj().
normalDirections_
labelListList normalDirections_ protected
Starting directions for the edges.
This vector points to the half of the plane defined by the first edge normal.
Definition at line 179 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::clear(), extendedEdgeMesh::normalDirections(), Foam::operator<<(), Foam::operator>>(), and extendedEdgeMesh::transfer().
edgeNormals_
labelListList edgeNormals_ protected
Indices of the normals that are adjacent to the feature edges.
Definition at line 182 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::edgeBaffles(), extendedEdgeMesh::edgeNormals(), extendedEdgeMesh::flipNormals(), Foam::operator<<(), Foam::operator>>(), and extendedEdgeMesh::transfer().
featurePointNormals_
labelListList featurePointNormals_ protected
Indices of the normals that are adjacent to the feature points.
(only valid for 0..nonFeatureStart_-1)
Definition at line 186 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::featurePointNormals(), extendedEdgeMesh::flipNormals(), Foam::operator<<(), Foam::operator>>(), and extendedEdgeMesh::transfer().
featurePointEdges_
labelListList featurePointEdges_ protected
Indices of feature edges attached to feature points. The edges are.
ordered so that they can be circulated.
Definition at line 190 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::clear(), extendedEdgeMesh::featurePointEdges(), Foam::operator<<(), Foam::operator>>(), and extendedEdgeMesh::transfer().
regionEdges_
labelList regionEdges_ protected
Feature edges which are on the boundary between regions.
Definition at line 193 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::flipNormals(), Foam::operator<<(), Foam::operator>>(), extendedEdgeMesh::regionEdges(), extendedEdgeMesh::transfer(), and extendedEdgeMesh::writeObj().
pointTree_
autoPtr<indexedOctree<treeDataPoint> > pointTree_ mutable protected
Search tree for all feature points.
Definition at line 196 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::flipNormals(), extendedEdgeMesh::pointTree(), and extendedEdgeMesh::transfer().
edgeTree_
autoPtr<indexedOctree<treeDataEdge> > edgeTree_ mutable protected
Search tree for all edges.
Definition at line 199 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::edgeTree(), extendedEdgeMesh::flipNormals(), and extendedEdgeMesh::transfer().
edgeTreesByType_
PtrList<indexedOctree<treeDataEdge> > edgeTreesByType_ mutable protected
Individual search trees for each type of edge.
Definition at line 202 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::add(), extendedEdgeMesh::clear(), extendedEdgeMesh::edgeTreesByType(), extendedEdgeMesh::flipNormals(), and extendedEdgeMesh::transfer().
nPointTypes
Foam::label nPointTypes = 4 static
Number of possible point types (i.e. number of slices)
Definition at line 225 of file extendedEdgeMesh.H.
Referenced by NamedEnum< directionType, 3 >::names().
nEdgeTypes
Foam::label nEdgeTypes = 5 static
Number of possible feature edge types (i.e. number of slices)
Definition at line 228 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::edgeTreesByType(), and NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/edgeMesh/extendedEdgeMesh/extendedEdgeMesh.H
src/edgeMesh/extendedEdgeMesh/extendedEdgeMesh.C
src/edgeMesh/extendedEdgeMesh/extendedEdgeMeshI.H
src/edgeMesh/extendedEdgeMesh/extendedEdgeMeshNew.C
src/edgeMesh/extendedEdgeMesh/extendedEdgeMeshTemplates.C