OpenFOAM: STARCDCore Class Reference
STARCDCore Class Reference
Core routines used when reading/writing pro-STAR vrt/cel/bnd files.
Public Member Functions
STARCDCore ()
Construct null.
Static Public Member Functions
static bool readPoints (IFstream &, pointField &, labelList &ids)
Read points from a (.vrt) file.
static void writePoints (Ostream &, const pointField &)
Write header and points to (.vrt) file.
Protected Types
enum cellType {
starcdFluidType = 1, starcdSolidType = 2, starcdBaffleType = 3, starcdShellType = 4,
starcdLineType = 5, starcdPointType = 6
}
enum shapeType {
starcdPoint = 1, starcdLine = 2, starcdShell = 3, starcdHex = 11,
starcdPrism = 12, starcdTet = 13, starcdPyr = 14, starcdPoly = 255
}
Static Protected Member Functions
static bool readHeader (IFstream &, const word &fileSignature)
Read header.
static void writeHeader (Ostream &, const word &fileType)
Write header for fileType (CELL|VERTEX|BOUNDARY)
Detailed Description
Core routines used when reading/writing pro-STAR vrt/cel/bnd files.
Source files
STARCDCore.H
STARCDCore.C
Definition at line 52 of file STARCDCore.H.
Member Enumeration Documentation
cellType
enum cellType protected
Enumerator
starcdFluidType
starcdSolidType
starcdBaffleType
starcdShellType
starcdLineType
starcdPointType
Definition at line 67 of file STARCDCore.H.
shapeType
enum shapeType protected
Enumerator
starcdPoint
starcdLine
starcdShell
starcdHex
starcdPrism
starcdTet
starcdPyr
starcdPoly
Definition at line 77 of file STARCDCore.H.
Constructor & Destructor Documentation
STARCDCore()
STARCDCore ()
Construct null.
Definition at line 34 of file STARCDCore.C.
References STARCDCore::readHeader().
Member Function Documentation
readHeader()
bool readHeader (IFstream & is, const word & fileSignature) static protected
Read header.
Definition at line 41 of file STARCDCore.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, ISstream::getLine(), IOstream::good(), Foam::Info, IFstream::name(), and STARCDCore::writeHeader().
Referenced by STARCDedgeFormat::read(), STARCDCore::readPoints(), and STARCDCore::STARCDCore().
writeHeader()
void writeHeader (Ostream & os, const word & fileType) static protected
Write header for fileType (CELL|VERTEX|BOUNDARY)
Definition at line 75 of file STARCDCore.C.
References Foam::endl(), Foam::nl, and STARCDCore::readPoints().
Referenced by STARCDCore::readHeader(), and STARCDCore::writePoints().
readPoints()
bool readPoints (IFstream & is, pointField & points, labelList & ids) static
Read points from a (.vrt) file.
The file format is as follows:
Line 1:
PROSTAR_VERTEX  newline
Line 2:
{version} 0 0 0 0 0 0 0  newline
Body:
{vertexId}  {x}  {y}  {z}  newline
Definition at line 96 of file STARCDCore.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), IFstream::name(), STARCDCore::readHeader(), List< T >::transfer(), STARCDCore::writePoints(), x, List< T >::xfer(), and y.
Referenced by STARCDedgeFormat::read(), and STARCDCore::writeHeader().
writePoints()
void writePoints (Ostream & os, const pointField & pointLst) static
Write header and points to (.vrt) file.
Definition at line 138 of file STARCDCore.C.
References Ostream::flush(), forAll, Foam::nl, Ostream::precision(), IOstream::setf(), and STARCDCore::writeHeader().
Referenced by STARCDCore::readPoints(), and STARCDedgeFormat::write().
The documentation for this class was generated from the following files:
src/fileFormats/starcd/STARCDCore.H
src/fileFormats/starcd/STARCDCore.C