OpenFOAM: option Class Reference
option Class Reference
Finite volume options abstract base class. Provides a base set of controls, e.g.:
Classes
class iNew
Return pointer to new fvOption object created.
Public Member Functions
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldi)
Set the applied flag to true for field index fieldi.
Switch & active ()
Return access to the source active flag.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
virtual bool read (const dictionary &dict)
Read source dictionary.
Static Public Member Functions
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Protected Attributes
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Detailed Description
Finite volume options abstract base class. Provides a base set of controls, e.g.:
    type            scalarExplicitSource    // source type
    active          on;                     // on/off switch
Note
On evaluation, source/sink options are to be added to the equation R.H.S.
Source files
fvOption.H
fvOption.C
fvOptionIO.C
Definition at line 66 of file fvOption.H.
Constructor & Destructor Documentation
option()
option (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 44 of file fvOption.C.
References Foam::decrIndent(), Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::Info, and option::New().
~option()
~option () virtual
Destructor.
Definition at line 94 of file fvOption.C.
Referenced by option::iNew::operator()().
Member Function Documentation
TypeName()
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , option , dictionary , (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh) , (name, modelType, dict, mesh))
clone()
autoPtr<option> clone () const inline
Return clone.
Definition at line 132 of file fvOption.H.
References option::iNew::iNew(), and NotImplemented.
New()
Foam::autoPtr< Foam::fv::option > New (const word & name, const dictionary & dict, const fvMesh & mesh) static
Return a reference to the selected fvOption model.
Definition at line 67 of file fvOption.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::indent(), Foam::Info, dictionary::lookup(), mesh, Foam::name(), and Foam::nl.
Referenced by option::iNew::operator()(), option::option(), and optionList::reset().
name()
const Foam::word & name () const inline
Return const access to the source name.
Definition at line 28 of file fvOptionI.H.
References option::name_.
Referenced by optionList::constrain(), optionList::correct(), optionList::operator()(), option::iNew::operator()(), and optionList::readOptions().
mesh()
const Foam::fvMesh & mesh () const inline
Return const access to the mesh database.
Definition at line 34 of file fvOptionI.H.
References option::mesh_.
Referenced by option::iNew::operator()().
coeffs()
const Foam::dictionary & coeffs () const inline
Return dictionary.
Definition at line 40 of file fvOptionI.H.
References option::coeffs_.
Referenced by option::iNew::operator()().
active() [1/2]
bool active () const inline
Return const access to the source active flag.
Definition at line 46 of file fvOptionI.H.
References option::active_.
Referenced by option::iNew::operator()().
setApplied()
void setApplied (const label fieldi) inline
Set the applied flag to true for field index fieldi.
Definition at line 52 of file fvOptionI.H.
References option::applied_.
Referenced by optionList::constrain(), optionList::correct(), optionList::operator()(), and option::iNew::operator()().
active() [2/2]
Foam::Switch & active () inline
Return access to the source active flag.
Definition at line 58 of file fvOptionI.H.
References option::active_.
isActive()
bool isActive () virtual
Is the source active?
Reimplemented in cellSetOption.
Definition at line 100 of file fvOption.C.
Referenced by optionList::constrain(), optionList::correct(), cellSetOption::isActive(), optionList::operator()(), and option::iNew::operator()().
applyToField()
Foam::label applyToField (const word & fieldName) const virtual
Return index of field name if found in fieldNames list.
Definition at line 106 of file fvOption.C.
References Foam::findIndex().
Referenced by optionList::constrain(), optionList::correct(), optionList::operator()(), and option::iNew::operator()().
checkApplied()
void checkApplied () const virtual
Check that the source has been applied.
Definition at line 112 of file fvOption.C.
References option::addSup(), Foam::endl(), forAll, and WarningInFunction.
Referenced by optionList::checkApplied(), and option::iNew::operator()().
addSup() [1/15]
void addSup (fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in solidificationMeltingSource, effectivenessHeatExchangerSource, and interRegionHeatTransferModel.
Definition at line 127 of file fvOption.C.
Referenced by option::addSup(), option::checkApplied(), optionList::operator()(), and option::iNew::operator()().
addSup() [2/15]
void addSup (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in rotorDiskSource, solidificationMeltingSource, actuationDiskSource, radialActuationDiskSource, interRegionExplicitPorositySource, meanVelocityForce, explicitPorositySource, and tabulatedAccelerationSource.
Definition at line 135 of file fvOption.C.
References option::addSup().
addSup() [3/15]
void addSup (fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 151 of file fvOption.C.
References option::addSup().
addSup() [4/15]
void addSup (fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 143 of file fvOption.C.
References option::addSup().
addSup() [5/15]
void addSup (fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 159 of file fvOption.C.
References option::addSup().
addSup() [6/15]
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in effectivenessHeatExchangerSource, solidificationMeltingSource, interRegionHeatTransferModel, and buoyancyEnergy.
Definition at line 167 of file fvOption.C.
References option::addSup().
addSup() [7/15]
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in solidificationMeltingSource, rotorDiskSource, actuationDiskSource, radialActuationDiskSource, interRegionExplicitPorositySource, meanVelocityForce, explicitPorositySource, tabulatedAccelerationSource, and buoyancyForce.
Definition at line 176 of file fvOption.C.
References option::addSup().
addSup() [8/15]
void addSup (const volScalarField & rho, fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 194 of file fvOption.C.
References option::addSup().
addSup() [9/15]
void addSup (const volScalarField & rho, fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 185 of file fvOption.C.
References option::addSup().
addSup() [10/15]
void addSup (const volScalarField & rho, fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 203 of file fvOption.C.
References option::addSup().
addSup() [11/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Definition at line 212 of file fvOption.C.
References option::addSup().
addSup() [12/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in explicitPorositySource.
Definition at line 224 of file fvOption.C.
References option::addSup().
addSup() [13/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 248 of file fvOption.C.
References option::addSup().
addSup() [14/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 236 of file fvOption.C.
References option::addSup().
addSup() [15/15]
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 260 of file fvOption.C.
constrain() [1/5]
void constrain (fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in fixedTemperatureConstraint.
Definition at line 271 of file fvOption.C.
Referenced by optionList::constrain(), option::constrain(), and option::iNew::operator()().
constrain() [2/5]
void constrain (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in meanVelocityForce.
Definition at line 275 of file fvOption.C.
References option::constrain().
constrain() [3/5]
void constrain (fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 280 of file fvOption.C.
References option::constrain().
constrain() [4/5]
void constrain (fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 288 of file fvOption.C.
constrain() [5/5]
void constrain (fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 295 of file fvOption.C.
correct() [1/5]
void correct (volScalarField & field) virtual
Reimplemented in limitTemperature.
Definition at line 299 of file fvOption.C.
Referenced by optionList::correct(), and option::iNew::operator()().
correct() [2/5]
void correct (volVectorField & field) virtual
Reimplemented in meanVelocityForce, and limitVelocity.
Definition at line 303 of file fvOption.C.
correct() [3/5]
void correct (volSphericalTensorField & field) virtual
Definition at line 307 of file fvOption.C.
correct() [4/5]
void correct (volSymmTensorField & field) virtual
Definition at line 311 of file fvOption.C.
correct() [5/5]
void correct (volTensorField & field) virtual
Definition at line 315 of file fvOption.C.
writeHeader()
void writeHeader (Ostream & os) const virtual
Write the source header information.
Definition at line 30 of file fvOptionIO.C.
References token::BEGIN_BLOCK, Foam::incrIndent(), Foam::indent(), option::name_, and Foam::nl.
Referenced by option::iNew::operator()().
writeFooter()
void writeFooter (Ostream & os) const virtual
Write the source footer information.
Definition at line 37 of file fvOptionIO.C.
References Foam::decrIndent(), token::END_BLOCK, Foam::endl(), and Foam::indent().
Referenced by option::iNew::operator()().
writeData()
void writeData (Ostream & os) const virtual
Write the source properties.
Definition at line 43 of file fvOptionIO.C.
References option::active_, option::coeffs_, token::END_STATEMENT, Foam::indent(), Foam::nl, Foam::type(), dictionary::write(), and Ostream::writeKeyword().
Referenced by option::iNew::operator()().
read()
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented in solidificationMeltingSource, rotorDiskSource, effectivenessHeatExchangerSource, CodedSource< Type >, actuationDiskSource, SemiImplicitSource< Type >, cellSetOption, interRegionHeatTransferModel, radialActuationDiskSource, meanVelocityForce, interRegionExplicitPorositySource, explicitPorositySource, fixedTemperatureConstraint, tabulatedAccelerationSource, limitTemperature, limitVelocity, variableHeatTransfer, buoyancyEnergy, buoyancyForce, tabulatedHeatTransfer, interRegionOption, FixedValueConstraint< Type >, and constantHeatTransfer.
Definition at line 53 of file fvOptionIO.C.
References option::active_, option::coeffs_, option::modelType_, dictionary::readIfPresent(), and dictionary::subDict().
Referenced by option::iNew::operator()(), interRegionOption::read(), tabulatedAccelerationSource::read(), cellSetOption::read(), and optionList::readOptions().
Member Data Documentation
name_
const word name_ protected
Source name.
Definition at line 73 of file fvOption.H.
Referenced by option::name(), and option::writeHeader().
modelType_
const word modelType_ protected
Model type.
Definition at line 76 of file fvOption.H.
Referenced by option::read().
mesh_
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 79 of file fvOption.H.
Referenced by cellSetOption::inTimeLimits(), and option::mesh().
dict_
dictionary dict_ protected
Top level source dictionary.
Definition at line 82 of file fvOption.H.
coeffs_
dictionary coeffs_ protected
Dictionary containing source coefficients.
Definition at line 85 of file fvOption.H.
Referenced by option::coeffs(), cellSetOption::read(), solidificationMeltingSource::read(), option::read(), and option::writeData().
active_
Switch active_ protected
Source active flag.
Definition at line 88 of file fvOption.H.
Referenced by option::active(), option::read(), and option::writeData().
fieldNames_
wordList fieldNames_ protected
Field names to apply source to - populated by derived models.
Definition at line 91 of file fvOption.H.
applied_
List<bool> applied_ protected
Applied flag list - corresponds to each fieldNames_ entry.
Definition at line 94 of file fvOption.H.
Referenced by option::setApplied().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/fvOptions/fvOption.H
src/finiteVolume/cfdTools/general/fvOptions/fvOption.C
src/finiteVolume/cfdTools/general/fvOptions/fvOptionI.H
src/finiteVolume/cfdTools/general/fvOptions/fvOptionIO.C