OpenFOAM: vtkUnstructuredReader Class Reference
vtkUnstructuredReader Class Reference
Reader for vtk unstructured_grid legacy files. Supports single CELLS, POINTS etc. entry only.
Public Types
enum vtkDataType {
VTK_INT, VTK_UINT, VTK_LONG, VTK_ULONG,
VTK_FLOAT, VTK_DOUBLE, VTK_STRING, VTK_ID
}
Enumeration defining the vtk data types.
enum vtkDataSetType { VTK_FIELD, VTK_SCALARS, VTK_VECTORS }
Enumeration defining the vtk dataset types.
enum parseMode {
NOMODE, UNSTRUCTURED_GRID, POLYDATA, CELL_DATA,
POINT_DATA
}
Enumeration defining the parse mode - what type of data is being.
enum vtkTypes {
VTK_EMPTY_CELL = 0, VTK_VERTEX = 1, VTK_POLY_VERTEX = 2, VTK_LINE = 3,
VTK_POLY_LINE = 4, VTK_TRIANGLE = 5, VTK_TRIANGLE_STRIP = 6, VTK_POLYGON = 7,
VTK_PIXEL = 8, VTK_QUAD = 9, VTK_TETRA = 10, VTK_VOXEL = 11,
VTK_HEXAHEDRON = 12, VTK_WEDGE = 13, VTK_PYRAMID = 14, VTK_PENTAGONAL_PRISM = 15,
VTK_HEXAGONAL_PRISM = 16
}
Enumeration defining the cell types.
Public Member Functions
ClassName ("vtkUnstructuredReader")
Runtime type information.
vtkUnstructuredReader (const objectRegistry &obr, ISstream &)
Construct from Istream, read all.
const string header () const
Header.
const string & title () const
Title.
const string & dataType () const
DataType.
const pointField & points () const
Points.
pointField & points ()
const cellShapeList & cells () const
3D cells.
cellShapeList & cells ()
const labelList & cellMap () const
const faceList & faces () const
2D cells (=faces)
faceList & faces ()
const labelList & faceMap () const
const labelListList & lines () const
1D cells (=open lines)
labelListList & lines ()
const labelList & lineMap () const
const objectRegistry & cellData () const
Cell based fields.
objectRegistry & cellData ()
const objectRegistry & pointData () const
Point based fields.
objectRegistry & pointData ()
const objectRegistry & otherData () const
Other fields.
objectRegistry & otherData ()
template<class Type >
void printFieldStats (const objectRegistry &) const
Debug: print contents of objectRegistry.
Static Public Attributes
static const NamedEnum< vtkDataType, 8 > vtkDataTypeNames
static const NamedEnum< vtkDataSetType, 3 > vtkDataSetTypeNames
static const NamedEnum< parseMode, 5 > parseModeNames
Detailed Description
Reader for vtk unstructured_grid legacy files. Supports single CELLS, POINTS etc. entry only.
- all integer types (int, unsigned_int, long etc.) become Foam::label
all real types (float, double) become Foam::scalar
POINTS becomes OpenFOAM points
CELLS gets split into OpenFOAM
cells
faces
lines
CELL_DATA or POINT_DATA gets stored on the corresponding objectRegistry in original vtk numbering order so use e.g. faceMap() to go from entry in faces() back to vtk numbering.
Source files
vtkUnstructuredReader.H
vtkUnstructuredReader.C
Definition at line 63 of file vtkUnstructuredReader.H.
Member Enumeration Documentation
vtkDataType
enum vtkDataType
Enumeration defining the vtk data types.
Enumerator
VTK_INT
VTK_UINT
VTK_LONG
VTK_ULONG
VTK_FLOAT
VTK_DOUBLE
VTK_STRING
VTK_ID
Definition at line 70 of file vtkUnstructuredReader.H.
vtkDataSetType
enum vtkDataSetType
Enumeration defining the vtk dataset types.
Enumerator
VTK_FIELD
VTK_SCALARS
VTK_VECTORS
Definition at line 86 of file vtkUnstructuredReader.H.
parseMode
enum parseMode
Enumeration defining the parse mode - what type of data is being.
read
Enumerator
NOMODE
UNSTRUCTURED_GRID
POLYDATA
CELL_DATA
POINT_DATA
Definition at line 98 of file vtkUnstructuredReader.H.
vtkTypes
enum vtkTypes
Enumeration defining the cell types.
Enumerator
VTK_EMPTY_CELL
VTK_VERTEX
VTK_POLY_VERTEX
VTK_LINE
VTK_POLY_LINE
VTK_TRIANGLE
VTK_TRIANGLE_STRIP
VTK_POLYGON
VTK_PIXEL
VTK_QUAD
VTK_TETRA
VTK_VOXEL
VTK_HEXAHEDRON
VTK_WEDGE
VTK_PYRAMID
VTK_PENTAGONAL_PRISM
VTK_HEXAGONAL_PRISM
Definition at line 111 of file vtkUnstructuredReader.H.
Constructor & Destructor Documentation
vtkUnstructuredReader()
vtkUnstructuredReader (const objectRegistry & obr, ISstream & inFile)
Construct from Istream, read all.
Definition at line 535 of file vtkUnstructuredReader.C.
References List< T >::clear(), Foam::endl(), HashTable< T, Key, Hash >::erase(), Foam::exit(), f(), Foam::FatalIOError, FatalIOErrorInFunction, HashTable< T, Key, Hash >::find(), forAll, ISstream::getLine(), IOstream::good(), Foam::Info, HashTable< regIOobject *>::iterator, IOstream::lineNumber(), Foam::nl, nPoints, Foam::read(), Foam::readLabel(), s(), List< T >::setSize(), List< T >::size(), and regIOobject::store().
Referenced by NamedEnum< directionType, 3 >::names().
Member Function Documentation
ClassName()
ClassName ("vtkUnstructuredReader")
Runtime type information.
header()
const string header () const inline
Header.
Definition at line 246 of file vtkUnstructuredReader.H.
title()
const string& title () const inline
Title.
Definition at line 252 of file vtkUnstructuredReader.H.
dataType()
const string& dataType () const inline
DataType.
Definition at line 258 of file vtkUnstructuredReader.H.
points() [1/2]
const pointField& points () const inline
Points.
Definition at line 265 of file vtkUnstructuredReader.H.
Referenced by VTKsurfaceFormat< Face >::read(), and VTKedgeFormat::read().
points() [2/2]
pointField& points () inline
Definition at line 270 of file vtkUnstructuredReader.H.
cells() [1/2]
const cellShapeList& cells () const inline
3D cells.
Definition at line 276 of file vtkUnstructuredReader.H.
cells() [2/2]
cellShapeList& cells () inline
Definition at line 281 of file vtkUnstructuredReader.H.
cellMap()
const labelList& cellMap () const inline
Definition at line 286 of file vtkUnstructuredReader.H.
faces() [1/2]
const faceList& faces () const inline
2D cells (=faces)
Definition at line 292 of file vtkUnstructuredReader.H.
Referenced by VTKsurfaceFormat< Face >::read().
faces() [2/2]
faceList& faces () inline
Definition at line 297 of file vtkUnstructuredReader.H.
faceMap()
const labelList& faceMap () const inline
Definition at line 302 of file vtkUnstructuredReader.H.
lines() [1/2]
const labelListList& lines () const inline
1D cells (=open lines)
Definition at line 308 of file vtkUnstructuredReader.H.
Referenced by VTKedgeFormat::read().
lines() [2/2]
labelListList& lines () inline
Definition at line 313 of file vtkUnstructuredReader.H.
lineMap()
const labelList& lineMap () const inline
Definition at line 318 of file vtkUnstructuredReader.H.
cellData() [1/2]
const objectRegistry& cellData () const inline
Cell based fields.
Definition at line 324 of file vtkUnstructuredReader.H.
Referenced by VTKsurfaceFormat< Face >::read().
cellData() [2/2]
objectRegistry& cellData () inline
Definition at line 329 of file vtkUnstructuredReader.H.
pointData() [1/2]
const objectRegistry& pointData () const inline
Point based fields.
Definition at line 335 of file vtkUnstructuredReader.H.
pointData() [2/2]
objectRegistry& pointData () inline
Definition at line 340 of file vtkUnstructuredReader.H.
otherData() [1/2]
const objectRegistry& otherData () const inline
Other fields.
Definition at line 346 of file vtkUnstructuredReader.H.
otherData() [2/2]
objectRegistry& otherData () inline
Definition at line 351 of file vtkUnstructuredReader.H.
References vtkUnstructuredReader::printFieldStats().
printFieldStats()
void printFieldStats (const objectRegistry & obj) const
Debug: print contents of objectRegistry.
Definition at line 53 of file vtkUnstructuredReaderTemplates.C.
References Foam::endl(), fieldNames, forAll, Foam::Info, objectRegistry::lookupObject(), objectRegistry::names(), Foam::nl, and List< T >::size().
Referenced by vtkUnstructuredReader::otherData().
Member Data Documentation
vtkDataTypeNames
const NamedEnum< vtkUnstructuredReader::vtkDataType, 8 > vtkDataTypeNames static
Definition at line 82 of file vtkUnstructuredReader.H.
Referenced by NamedEnum< directionType, 3 >::names().
vtkDataSetTypeNames
const NamedEnum< vtkUnstructuredReader::vtkDataSetType, 3 > vtkDataSetTypeNames static
Definition at line 93 of file vtkUnstructuredReader.H.
Referenced by NamedEnum< directionType, 3 >::names().
parseModeNames
const NamedEnum< vtkUnstructuredReader::parseMode, 5 > parseModeNames static
Definition at line 107 of file vtkUnstructuredReader.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/fileFormats/vtk/vtkUnstructuredReader.H
src/fileFormats/vtk/vtkUnstructuredReader.C
src/fileFormats/vtk/vtkUnstructuredReaderTemplates.C