OpenFOAM: optionList Class Reference
optionList Class Reference
List of finite volume options.
Public Member Functions
TypeName ("optionList")
Runtime type information.
optionList (const fvMesh &mesh)
Construct null.
optionList (const fvMesh &mesh, const dictionary &dict)
Construct from mesh and dictionary.
virtual ~optionList ()
Destructor.
void reset (const dictionary &dict)
Reset the source list.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const geometricOneField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const geometricOneField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
void constrain (fvMatrix< Type > &eqn)
Apply constraints to equation.
template<class Type >
void correct (GeometricField< Type, fvPatchField, volMesh > &field)
Apply correction to field.
virtual bool read (const dictionary &dict)
Read dictionary.
virtual bool writeData (Ostream &os) const
Write data to Ostream.
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const geometricOneField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const geometricOneField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Public Member Functions inherited from PtrList< option >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< option > &)
Copy constructor.
PtrList (const PtrList< option > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< option >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< option > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< option > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (option *)
Append an element at the end of the list.
void append (const autoPtr< option > &)
void append (const tmp< option > &)
void transfer (PtrList< option > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< option > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< option > set (const label, option *)
Set element to given T* and return old element (can be nullptr)
autoPtr< option > set (const label, const autoPtr< option > &)
Set element to given autoPtr<T> and return old element.
autoPtr< option > set (const label, const tmp< option > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< option > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Member Functions
const dictionary & optionsDict (const dictionary &dict) const
Return the "options" sub-dictionary if present otherwise return dict.
bool readOptions (const dictionary &dict)
Read options dictionary.
void checkApplied () const
Check that all sources have been applied.
optionList (const optionList &)
Disallow default bitwise copy construct.
void operator= (const optionList &)
Disallow default bitwise assignment.
Protected Member Functions inherited from PtrList< option >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh database.
label checkTimeIndex_
Time index to check that all defined sources have been applied.
Friends
Ostream & operator<< (Ostream &os, const optionList &options)
Ostream operator.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Detailed Description
List of finite volume options.
SourceFile optionList.C
Definition at line 64 of file fvOptionList.H.
Constructor & Destructor Documentation
optionList() [1/3]
optionList (const optionList &) protected
Disallow default bitwise copy construct.
optionList() [2/3]
optionList (const fvMesh & mesh)
Construct null.
Definition at line 98 of file fvOptionList.C.
optionList() [3/3]
optionList (const fvMesh & mesh, const dictionary & dict)
Construct from mesh and dictionary.
Definition at line 88 of file fvOptionList.C.
References optionList::optionsDict(), and optionList::reset().
~optionList()
virtual ~optionList () inline virtual
Destructor.
Definition at line 113 of file fvOptionList.H.
References Foam::constant::atomic::alpha, constrain(), correct, dict, Foam::read(), rho, and writeData().
Member Function Documentation
optionsDict()
const Foam::dictionary & optionsDict (const dictionary & dict) const protected
Return the "options" sub-dictionary if present otherwise return dict.
Definition at line 43 of file fvOptionList.C.
References dict, dictionary::found(), and dictionary::subDict().
Referenced by optionList::optionList(), and optionList::read().
readOptions()
bool readOptions (const dictionary & dict) protected
Read options dictionary.
Definition at line 58 of file fvOptionList.C.
References forAll, option::name(), option::read(), and dictionary::subDict().
Referenced by optionList::read().
checkApplied()
void checkApplied () const protected
Check that all sources have been applied.
Definition at line 73 of file fvOptionList.C.
References option::checkApplied(), and forAll.
Referenced by optionList::constrain().
operator=()
void operator= (const optionList &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("optionList")
Runtime type information.
reset()
void reset (const dictionary & dict)
Reset the source list.
Definition at line 108 of file fvOptionList.C.
References forAllConstIter(), optionList::mesh_, Foam::name(), option::New(), and PtrList< option >::setSize().
Referenced by optionList::optionList().
operator()() [1/18]
tmp<fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
operator()() [2/18]
tmp<fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Return source for equation with specified name.
operator()() [3/18]
tmp<fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
operator()() [4/18]
tmp<fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Return source for equation with specified name.
operator()() [5/18]
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
operator()() [6/18]
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Return source for equation with specified name.
operator()() [7/18]
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
operator()() [8/18]
tmp<fvMatrix<Type> > operator() (const geometricOneField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
operator()() [9/18]
tmp<fvMatrix<Type> > operator() (const geometricOneField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
constrain()
void constrain (fvMatrix< Type > & eqn)
Apply constraints to equation.
Definition at line 246 of file fvOptionListTemplates.C.
References option::applyToField(), optionList::checkApplied(), option::constrain(), optionList::correct(), Foam::endl(), forAll, Foam::Info, option::isActive(), option::name(), UPtrList< T >::operator[](), fvMatrix< Type >::psi(), and option::setApplied().
Referenced by DeardorffDiffStress< BasicTurbulenceModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kOmega< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), and kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt().
correct()
void correct (GeometricField< Type, fvPatchField, volMesh > & field)
Apply correction to field.
Definition at line 277 of file fvOptionListTemplates.C.
References option::applyToField(), option::correct(), Foam::endl(), forAll, Foam::Info, option::isActive(), option::name(), IOobject::name(), UPtrList< T >::operator[](), and option::setApplied().
Referenced by optionList::constrain(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), Maxwell< BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correct(), kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), SpalartAllmarasDES< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), dynamicLagrangian< BasicTurbulenceModel >::correctNut(), kEqn< BasicTurbulenceModel >::correctNut(), kOmega< BasicTurbulenceModel >::correctNut(), WALE< BasicTurbulenceModel >::correctNut(), continuousGasKEpsilon< BasicTurbulenceModel >::correctNut(), DeardorffDiffStress< BasicTurbulenceModel >::correctNut(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), realizableKE< BasicTurbulenceModel >::correctNut(), Smagorinsky< BasicTurbulenceModel >::correctNut(), NicenoKEqn< BasicTurbulenceModel >::correctNut(), LaheyKEpsilon< BasicTurbulenceModel >::correctNut(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correctNut(), RNGkEpsilon< BasicTurbulenceModel >::correctNut(), LaunderSharmaKE< BasicTurbulenceModel >::correctNut(), dynamicKEqn< BasicTurbulenceModel >::correctNut(), SSG< BasicTurbulenceModel >::correctNut(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), LRR< BasicTurbulenceModel >::correctNut(), SpalartAllmaras< BasicTurbulenceModel >::correctNut(), SpalartAllmarasDES< BasicTurbulenceModel >::correctNut(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), v2f< BasicTurbulenceModel >::correctNut(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correctNut(), and kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt().
read()
bool read (const dictionary & dict) virtual
Read dictionary.
Definition at line 139 of file fvOptionList.C.
References optionList::optionsDict(), and optionList::readOptions().
Referenced by options::read(), and options::~options().
writeData()
bool writeData (Ostream & os) const virtual
Write data to Ostream.
Definition at line 145 of file fvOptionList.C.
References forAll, IOstream::good(), Foam::nl, and UPtrList< T >::operator[]().
Referenced by Foam::operator<<().
operator()() [10/18]
Foam::tmp<Foam::fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 30 of file fvOptionListTemplates.C.
References UPtrList< T >::operator.
operator()() [11/18]
Foam::tmp<Foam::fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Definition at line 40 of file fvOptionListTemplates.C.
References option::addSup(), option::applyToField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVolume, Foam::endl(), forAll, Foam::Info, option::isActive(), option::name(), UPtrList< T >::operator, tmp< T >::ref(), and option::setApplied().
operator()() [12/18]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 81 of file fvOptionListTemplates.C.
References IOobject::name(), and UPtrList< T >::operator.
operator()() [13/18]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Definition at line 92 of file fvOptionListTemplates.C.
References option::addSup(), option::applyToField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVolume, Foam::endl(), forAll, Foam::Info, option::isActive(), option::name(), UPtrList< T >::operator, and option::setApplied().
operator()() [14/18]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 137 of file fvOptionListTemplates.C.
References IOobject::name(), and UPtrList< T >::operator.
operator()() [15/18]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Definition at line 149 of file fvOptionListTemplates.C.
References option::addSup(), option::applyToField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVolume, Foam::endl(), forAll, Foam::Info, option::isActive(), option::name(), UPtrList< T >::operator, and option::setApplied().
operator()() [16/18]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const geometricOneField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 196 of file fvOptionListTemplates.C.
References IOobject::name(), and UPtrList< T >::operator.
operator()() [17/18]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 208 of file fvOptionListTemplates.C.
References Foam::dimless, IOobject::name(), and UPtrList< T >::operator.
operator()() [18/18]
Foam::tmp<Foam::fvMatrix<Type> > operator() (const geometricOneField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 235 of file fvOptionListTemplates.C.
References IOobject::name().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const optionList & options) friend
Ostream operator.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 73 of file fvOptionList.H.
Referenced by optionList::reset().
checkTimeIndex_
label checkTimeIndex_ protected
Time index to check that all defined sources have been applied.
Definition at line 76 of file fvOptionList.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/fvOptions/fvOptionList.H
src/finiteVolume/cfdTools/general/fvOptions/fvOptionList.C
src/finiteVolume/cfdTools/general/fvOptions/fvOptionListTemplates.C