OpenFOAM: ignitionSite Class Reference
ignitionSite Class Reference
Foam::ignitionSite.
Classes
class iNew
Class used for the read-construction of.
Public Member Functions
ignitionSite (Istream &, const Time &, const fvMesh &)
Construct from Istream and database.
ignitionSite (Istream &, const engineTime &, const fvMesh &)
Construct from Istream and engineTime.
autoPtr< ignitionSite > clone () const
Clone.
const vector & location () const
scalar diameter () const
scalar time () const
scalar duration () const
scalar strength () const
const labelList & cells () const
Return the ignition cells updated if the mesh moved.
const scalarList & cellVolumes () const
bool igniting () const
bool ignited () const
void operator= (const ignitionSite &)
Detailed Description
Foam::ignitionSite.
Source files
ignitionSite.H
ignitionSiteI.H
ignitionSite.C
ignitionSiteIO.C
Definition at line 58 of file ignitionSite.H.
Constructor & Destructor Documentation
ignitionSite() [1/2]
ignitionSite (Istream & is, const Time & db, const fvMesh & mesh)
Construct from Istream and database.
Definition at line 32 of file ignitionSiteIO.C.
References IOstream::check().
Referenced by ignitionSite::clone(), and ignitionSite::iNew::operator()().
ignitionSite() [2/2]
ignitionSite (Istream & is, const engineTime & edb, const fvMesh & mesh)
Construct from Istream and engineTime.
Definition at line 68 of file ignitionSiteIO.C.
References IOstream::check().
Member Function Documentation
clone()
autoPtr<ignitionSite> clone () const inline
Clone.
Definition at line 121 of file ignitionSite.H.
References ignitionSite::ignitionSite().
location()
const vector& location () const inline
Definition at line 131 of file ignitionSite.H.
diameter()
scalar diameter () const inline
Definition at line 136 of file ignitionSite.H.
time()
scalar time () const inline
Definition at line 141 of file ignitionSite.H.
duration()
scalar duration () const inline
Definition at line 146 of file ignitionSite.H.
strength()
scalar strength () const inline
Definition at line 151 of file ignitionSite.H.
References ignitionSite::cells().
cells()
const Foam::labelList & cells () const
Return the ignition cells updated if the mesh moved.
Definition at line 86 of file ignitionSite.C.
References polyMesh::changing(), and TimeState::timeIndex().
Referenced by ignitionSite::strength().
cellVolumes()
const scalarList& cellVolumes () const inline
Definition at line 159 of file ignitionSite.H.
References ignitionSite::ignited(), ignitionSite::igniting(), and ignitionSite::operator=().
igniting()
bool igniting () const
Definition at line 98 of file ignitionSite.C.
References TimeState::deltaTValue(), Foam::max(), and dimensioned< Type >::value().
Referenced by ignitionSite::cellVolumes().
ignited()
bool ignited () const
Definition at line 112 of file ignitionSite.C.
References TimeState::deltaTValue(), and dimensioned< Type >::value().
Referenced by ignitionSite::cellVolumes().
operator=()
void operator= (const ignitionSite & is)
Definition at line 123 of file ignitionSite.C.
Referenced by ignitionSite::cellVolumes().
The documentation for this class was generated from the following files:
src/engine/ignition/ignitionSite.H
src/engine/ignition/ignitionSite.C
src/engine/ignition/ignitionSiteIO.C