OpenFOAM: MRFZone Class Reference
MRFZone Class Reference
MRF zone definition based on cell zone and parameters obtained from a control dictionary constructed from the given stream.
Public Member Functions
ClassName ("MRFZone")
MRFZone (const word &name, const fvMesh &mesh, const dictionary &dict, const word &cellZoneName=word::null)
Construct from fvMesh.
autoPtr< MRFZone > clone () const
Return clone.
const word & name () const
Return const access to the MRF region name.
bool active () const
Return const access to the MRF active flag.
vector Omega () const
Return the current Omega vector.
void updateMesh (const mapPolyMesh &mpm)
Update the mesh corresponding to given map.
void addCoriolis (const volVectorField &U, volVectorField &ddtU) const
Add the Coriolis force contribution to the acceleration field.
void addCoriolis (fvVectorMatrix &UEqn, const bool rhs=false) const
Add the Coriolis force contribution to the momentum equation.
void addCoriolis (const volScalarField &rho, fvVectorMatrix &UEqn, const bool rhs=false) const
Add the Coriolis force contribution to the momentum equation.
void makeRelative (volVectorField &U) const
Make the given absolute velocity relative within the MRF region.
void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative within the MRF region.
void makeRelative (FieldField< fvsPatchField, scalar > &phi) const
Make the given absolute boundary flux relative.
void makeRelative (Field< scalar > &phi, const label patchi) const
Make the given absolute patch flux relative.
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative within the MRF region.
void makeAbsolute (volVectorField &U) const
Make the given relative velocity absolute within the MRF region.
void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute within the MRF region.
void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute within the MRF region.
void correctBoundaryVelocity (volVectorField &U) const
Correct the boundary velocity for the rotation of the MRF region.
void writeData (Ostream &os) const
Write.
bool read (const dictionary &dict)
Read MRF dictionary.
Detailed Description
MRF zone definition based on cell zone and parameters obtained from a control dictionary constructed from the given stream.
The rotation of the MRF region is defined by an origin and axis of rotation and an angular speed.
Source files
MRFZone.H
MRFZone.C
Definition at line 65 of file MRFZone.H.
Constructor & Destructor Documentation
MRFZone()
MRFZone (const word & name, const fvMesh & mesh, const dictionary & dict, const word & cellZoneName = word::null)
Construct from fvMesh.
Definition at line 237 of file MRFZone.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAllConstIter(), Foam::mag(), word::null, and Foam::reduce().
Member Function Documentation
ClassName()
ClassName ("MRFZone")
clone()
autoPtr<MRFZone> clone () const inline
Return clone.
Definition at line 173 of file MRFZone.H.
References MRFZone::active(), MRFZone::name(), NotImplemented, and MRFZone::Omega().
name()
const Foam::word & name () const inline
Return const access to the MRF region name.
Definition at line 26 of file MRFZoneI.H.
Referenced by MRFZone::clone(), and MRFZoneList::read().
active()
bool active () const inline
Return const access to the MRF active flag.
Definition at line 32 of file MRFZoneI.H.
Referenced by MRFZone::clone().
Omega()
Foam::vector Omega () const
Return the current Omega vector.
Definition at line 304 of file MRFZone.C.
References MRFZone::addCoriolis().
Referenced by MRFZone::clone().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) inline
Update the mesh corresponding to given map.
Definition at line 197 of file MRFZone.H.
References MRFZone::addCoriolis(), MRFZone::correctBoundaryVelocity(), MRFZone::makeAbsolute(), MRFZone::makeRelative(), MRFZone::read(), U, UEqn, and MRFZone::writeData().
addCoriolis() [1/3]
void addCoriolis (const volVectorField & U, volVectorField & ddtU) const
Add the Coriolis force contribution to the acceleration field.
Definition at line 311 of file MRFZone.C.
References cells, forAll, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and U.
Referenced by MRFZone::addCoriolis(), MRFZone::Omega(), and MRFZone::updateMesh().
addCoriolis() [2/3]
void addCoriolis (fvVectorMatrix & UEqn, const bool rhs = false) const
Add the Coriolis force contribution to the momentum equation.
Adds to the lhs of the equation; optionally add to rhs
Definition at line 335 of file MRFZone.C.
References MRFZone::addCoriolis(), cells, forAll, fvMatrix< Type >::psi(), and fvMatrix< Type >::source().
addCoriolis() [3/3]
void addCoriolis (const volScalarField & rho, fvVectorMatrix & UEqn, const bool rhs = false) const
Add the Coriolis force contribution to the momentum equation.
Adds to the lhs of the equation; optionally add to rhs
Definition at line 369 of file MRFZone.C.
References cells, forAll, fvMatrix< Type >::psi(), and fvMatrix< Type >::source().
makeRelative() [1/5]
void makeRelative (volVectorField & U) const
Make the given absolute velocity relative within the MRF region.
Definition at line 406 of file MRFZone.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), C::C(), cells, forAll, patchi, and Foam::Zero.
Referenced by MRFZone::makeRelative(), and MRFZone::updateMesh().
makeRelative() [2/5]
void makeRelative (surfaceScalarField & phi) const
Make the given absolute flux relative within the MRF region.
Definition at line 447 of file MRFZone.C.
makeRelative() [3/5]
void makeRelative (FieldField< fvsPatchField, scalar > & phi) const
Make the given absolute boundary flux relative.
within the MRF region
Definition at line 453 of file MRFZone.C.
makeRelative() [4/5]
void makeRelative (Field< scalar > & phi, const label patchi) const
Make the given absolute patch flux relative.
within the MRF region
Definition at line 459 of file MRFZone.C.
References MRFZone::makeRelative().
makeRelative() [5/5]
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given absolute mass-flux relative within the MRF region.
Definition at line 466 of file MRFZone.C.
makeAbsolute() [1/3]
void makeAbsolute (volVectorField & U) const
Make the given relative velocity absolute within the MRF region.
Definition at line 475 of file MRFZone.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), C::C(), cells, forAll, and patchi.
Referenced by MRFZone::makeAbsolute(), and MRFZone::updateMesh().
makeAbsolute() [2/3]
void makeAbsolute (surfaceScalarField & phi) const
Make the given relative flux absolute within the MRF region.
Definition at line 515 of file MRFZone.C.
References MRFZone::makeAbsolute().
makeAbsolute() [3/3]
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given relative mass-flux absolute within the MRF region.
Definition at line 522 of file MRFZone.C.
correctBoundaryVelocity()
void correctBoundaryVelocity (volVectorField & U) const
Correct the boundary velocity for the rotation of the MRF region.
Definition at line 531 of file MRFZone.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, and patchi.
Referenced by MRFZone::updateMesh().
writeData()
void writeData (Ostream & os) const
Write.
Definition at line 556 of file MRFZone.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::incrIndent(), Foam::nl, Ostream::write(), and Ostream::writeKeyword().
Referenced by MRFZone::updateMesh().
read()
bool read (const dictionary & dict)
Read MRF dictionary.
Definition at line 577 of file MRFZone.C.
References dict, and dictionary::lookupOrDefault().
Referenced by MRFZoneList::read(), and MRFZone::updateMesh().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/MRF/MRFZone.H
src/finiteVolume/cfdTools/general/MRF/MRFZone.C
src/finiteVolume/cfdTools/general/MRF/MRFZoneI.H
src/finiteVolume/cfdTools/general/MRF/MRFZoneTemplates.C