OpenFOAM: MRFZoneList Class Reference
MRFZoneList Class Reference
List container for MRF zomes.
Public Member Functions
MRFZoneList (const fvMesh &mesh, const dictionary &dict)
Constructor.
~MRFZoneList ()
Destructor.
bool active (const bool warn=false) const
Return active status.
void reset (const dictionary &dict)
Reset the source list.
void addAcceleration (const volVectorField &U, volVectorField &ddtU) const
Add the frame acceleration.
void addAcceleration (fvVectorMatrix &UEqn) const
Add the frame acceleration contribution to the momentum equation.
void addAcceleration (const volScalarField &rho, fvVectorMatrix &UEqn) const
Add the frame acceleration contribution to the momentum equation.
tmp< volVectorField > DDt (const volVectorField &U) const
Return the frame acceleration.
tmp< volVectorField > DDt (const volScalarField &rho, const volVectorField &U) const
Return the frame acceleration.
void makeRelative (volVectorField &U) const
Make the given absolute velocity relative within the MRF region.
void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative within the MRF region.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &phi) const
Return the given absolute flux relative within the MRF region.
tmp< FieldField< fvsPatchField, scalar > > relative (const tmp< FieldField< fvsPatchField, scalar >> &tphi) const
Return the given absolute boundary flux relative within.
tmp< Field< scalar > > relative (const tmp< Field< scalar >> &tphi, const label patchi) const
Return the given absolute patch flux relative within.
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative within the MRF region.
void makeAbsolute (volVectorField &U) const
Make the given relative velocity absolute within the MRF region.
void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute within the MRF region.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &phi) const
Return the given relative flux absolute within the MRF region.
void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute within the MRF region.
void correctBoundaryVelocity (volVectorField &U) const
Correct the boundary velocity for the rotation of the MRF region.
void correctBoundaryFlux (const volVectorField &U, surfaceScalarField &phi) const
Correct the boundary flux for the rotation of the MRF region.
bool read (const dictionary &dict)
Read dictionary.
bool writeData (Ostream &os) const
Write data to Ostream.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh database.
Friends
Ostream & operator<< (Ostream &os, const MRFZoneList &models)
Ostream operator.
Detailed Description
List container for MRF zomes.
Source files
MRFZoneList.H
MRFZoneList.C
Definition at line 55 of file MRFZoneList.H.
Constructor & Destructor Documentation
MRFZoneList()
MRFZoneList (const fvMesh & mesh, const dictionary & dict)
Constructor.
Definition at line 33 of file MRFZoneList.C.
~MRFZoneList()
~MRFZoneList ()
Destructor.
Definition at line 49 of file MRFZoneList.C.
Member Function Documentation
active()
bool active (const bool warn = false) const
Return active status.
Definition at line 55 of file MRFZoneList.C.
References Foam::endl(), forAll, Foam::Info, UPtrList< T >::operator[](), and UPtrList< T >::size().
reset()
void reset (const dictionary & dict)
Reset the source list.
Definition at line 72 of file MRFZoneList.C.
References Foam::endl(), forAllConstIter(), Foam::Info, MRFZoneList::mesh_, Foam::name(), and PtrList< MRFZone >::setSize().
addAcceleration() [1/3]
void addAcceleration (const volVectorField & U, volVectorField & ddtU) const
Add the frame acceleration.
Definition at line 130 of file MRFZoneList.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by MRFZoneList::addAcceleration(), and MRFZoneList::writeData().
addAcceleration() [2/3]
void addAcceleration (fvVectorMatrix & UEqn) const
Add the frame acceleration contribution to the momentum equation.
Definition at line 142 of file MRFZoneList.C.
References MRFZoneList::addAcceleration(), forAll, and UPtrList< T >::operator[]().
addAcceleration() [3/3]
void addAcceleration (const volScalarField & rho, fvVectorMatrix & UEqn) const
Add the frame acceleration contribution to the momentum equation.
Definition at line 152 of file MRFZoneList.C.
References MRFZoneList::DDt(), forAll, and UPtrList< T >::operator[]().
DDt() [1/2]
Foam::tmp< Foam::volVectorField > DDt (const volVectorField & U) const
Return the frame acceleration.
Definition at line 165 of file MRFZoneList.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, forAll, DimensionedField< Type, GeoMesh >::mesh(), UPtrList< T >::operator[](), GeometricField< Type, PatchField, GeoMesh >::ref(), and Foam::Zero.
Referenced by MRFZoneList::addAcceleration(), and MRFZoneList::DDt().
DDt() [2/2]
Foam::tmp< Foam::volVectorField > DDt (const volScalarField & rho, const volVectorField & U) const
Return the frame acceleration.
Definition at line 195 of file MRFZoneList.C.
References MRFZoneList::DDt().
makeRelative() [1/3]
void makeRelative (volVectorField & U) const
Make the given absolute velocity relative within the MRF region.
Definition at line 204 of file MRFZoneList.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by MRFZoneList::relative().
makeRelative() [2/3]
void makeRelative (surfaceScalarField & phi) const
Make the given absolute flux relative within the MRF region.
Definition at line 213 of file MRFZoneList.C.
References forAll, UPtrList< T >::operator[](), and MRFZoneList::relative().
relative() [1/3]
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & phi) const
Return the given absolute flux relative within the MRF region.
Definition at line 223 of file MRFZoneList.C.
References tmp< T >::clear(), MRFZoneList::makeRelative(), Foam::name(), Foam::New(), tmp< T >::ref(), and UPtrList< T >::size().
Referenced by MRFZoneList::correctBoundaryFlux(), MRFZoneList::makeRelative(), and MRFZoneList::relative().
relative() [2/3]
Foam::tmp< Foam::FieldField< Foam::fvsPatchField, Foam::scalar > > relative (const tmp< FieldField< fvsPatchField, scalar >> & tphi) const
Return the given absolute boundary flux relative within.
the MRF region
Definition at line 255 of file MRFZoneList.C.
References tmp< T >::clear(), forAll, Foam::New(), UPtrList< T >::operator[](), tmp< T >::ref(), MRFZoneList::relative(), and UPtrList< T >::size().
relative() [3/3]
Foam::tmp< Foam::Field< Foam::scalar > > relative (const tmp< Field< scalar >> & tphi, const label patchi) const
Return the given absolute patch flux relative within.
the MRF region
Definition at line 281 of file MRFZoneList.C.
References tmp< T >::clear(), forAll, MRFZoneList::makeRelative(), Foam::New(), UPtrList< T >::operator[](), patchi, tmp< T >::ref(), and UPtrList< T >::size().
makeRelative() [3/3]
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given absolute mass-flux relative within the MRF region.
Definition at line 307 of file MRFZoneList.C.
References forAll, and UPtrList< T >::operator[]().
makeAbsolute() [1/3]
void makeAbsolute (volVectorField & U) const
Make the given relative velocity absolute within the MRF region.
Definition at line 319 of file MRFZoneList.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by MRFZoneList::absolute().
makeAbsolute() [2/3]
void makeAbsolute (surfaceScalarField & phi) const
Make the given relative flux absolute within the MRF region.
Definition at line 328 of file MRFZoneList.C.
References MRFZoneList::absolute(), forAll, and UPtrList< T >::operator[]().
absolute()
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & phi) const
Return the given relative flux absolute within the MRF region.
Definition at line 338 of file MRFZoneList.C.
References tmp< T >::clear(), MRFZoneList::makeAbsolute(), Foam::name(), Foam::New(), tmp< T >::ref(), and UPtrList< T >::size().
Referenced by MRFZoneList::makeAbsolute().
makeAbsolute() [3/3]
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given relative mass-flux absolute within the MRF region.
Definition at line 369 of file MRFZoneList.C.
References forAll, and UPtrList< T >::operator[]().
correctBoundaryVelocity()
void correctBoundaryVelocity (volVectorField & U) const
Correct the boundary velocity for the rotation of the MRF region.
Definition at line 381 of file MRFZoneList.C.
References MRFZoneList::correctBoundaryFlux(), forAll, and UPtrList< T >::operator[]().
correctBoundaryFlux()
void correctBoundaryFlux (const volVectorField & U, surfaceScalarField & phi) const
Correct the boundary flux for the rotation of the MRF region.
Definition at line 391 of file MRFZoneList.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, MRFZoneList::mesh_, patchi, MRFZoneList::relative(), fvMesh::Sf(), and Uf.
Referenced by MRFZoneList::correctBoundaryVelocity().
read()
bool read (const dictionary & dict)
Read dictionary.
Definition at line 104 of file MRFZoneList.C.
References forAll, MRFZone::name(), UPtrList< T >::operator[](), MRFZone::read(), and dictionary::subDict().
Referenced by IOMRFZoneList::read().
writeData()
bool writeData (Ostream & os) const
Write data to Ostream.
Definition at line 117 of file MRFZoneList.C.
References MRFZoneList::addAcceleration(), forAll, IOstream::good(), Foam::nl, and UPtrList< T >::operator[]().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const MRFZoneList & models) friend
Ostream operator.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 75 of file MRFZoneList.H.
Referenced by MRFZoneList::correctBoundaryFlux(), and MRFZoneList::reset().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.H
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.C