OpenFOAM: ensightSetWriter< Type > Class Template Reference
ensightSetWriter< Type > Class Template Reference
Public Member Functions
TypeName ("ensight")
Runtime type information.
ensightSetWriter ()
Construct null.
virtual ~ensightSetWriter ()
Destructor.
virtual fileName getFileName (const coordSet &, const wordList &) const
Generate file name with correct extension.
virtual void write (const coordSet &, const wordList &, const List< const Field< Type > *> &, Ostream &) const
General entry point for writing.
virtual void write (const bool writeTracks, const PtrList< coordSet > &, const wordList &valueSetNames, const List< List< Field< Type >>> &, Ostream &) const
General entry point for writing of multiple coordSets.
Public Member Functions inherited from writer< Type >
TypeName ("writer")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, writer, word,(),())
writer ()
Construct null.
virtual ~writer ()=0
Destructor.
virtual void write (const coordSet &, const wordList &, const List< Field< Type >> &, Ostream &) const
General entry point for writing.
virtual Ostream & write (const scalar, Ostream &) const
Write scalar as ascii.
template<class VSType >
Ostream & writeVS (const VSType &, Ostream &) const
virtual Ostream & write (const vector &, Ostream &) const
Write vector. Tab separated ascii.
virtual Ostream & write (const sphericalTensor &, Ostream &) const
Write sphericalTensor. Tab separated ascii.
virtual Ostream & write (const symmTensor &, Ostream &) const
Write symmTensor. Tab separated ascii.
virtual Ostream & write (const tensor &, Ostream &) const
Write tensor. Tab separated ascii.
template<class VSType >
Foam::Ostream & writeVS (const VSType &value, Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from writer< Type >
static autoPtr< writer > New (const word &writeFormat)
Return a reference to the selected writer.
Protected Member Functions inherited from writer< Type >
fileName getBaseName (const coordSet &, const wordList &) const
Generates filename from coordSet and sampled fields.
void writeCoord (const coordSet &, const label sampleI, Ostream &) const
void writeTable (const coordSet &, const List< Type > &, Ostream &) const
Writes single-column ascii write. Column 1 is coordSet coordinate,.
void writeTable (const coordSet &, const List< const List< Type > *> &, Ostream &os) const
Writes multi-column ascii write. Column 1 is coordSet coordinate,.
virtual void writeSeparator (Ostream &os) const
Writes a separator. Used by write functions.
Detailed Description
template<class Type>
class Foam::ensightSetWriter< Type >
Source files
ensightSetWriter.H
ensightSetWriter.C
Definition at line 48 of file ensightSetWriter.H.
Constructor & Destructor Documentation
ensightSetWriter()
ensightSetWriter ()
Construct null.
Definition at line 36 of file ensightSetWriter.C.
~ensightSetWriter()
~ensightSetWriter () virtual
Destructor.
Definition at line 44 of file ensightSetWriter.C.
References ensightSetWriter< Type >::getFileName().
Member Function Documentation
TypeName()
TypeName ("ensight")
Runtime type information.
getFileName()
Foam::fileName getFileName (const coordSet & , const wordList &) const virtual
Generate file name with correct extension.
Implements writer< Type >.
Definition at line 52 of file ensightSetWriter.C.
References writer< Type >::getBaseName(), and ensightSetWriter< Type >::write().
Referenced by ensightSetWriter< Type >::~ensightSetWriter().
write() [1/2]
void write (const coordSet & , const wordList & , const List< const Field< Type > *> & , Ostream &) const virtual
General entry point for writing.
The data is organized in a set of point with one or more values per point
Implements writer< Type >.
Definition at line 67 of file ensightSetWriter.C.
References Foam::component(), fld(), Foam::floatScalarVSMALL, Foam::FOAMversion, forAll, fileName::lessExt(), Foam::mag(), fileName::name(), IOstream::name(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, Foam::nl, OSstream::precision(), Foam::scientific(), IOstream::setf(), Foam::setw(), and List< T >::size().
Referenced by ensightSetWriter< Type >::getFileName().
write() [2/2]
void write (const bool writeTracks, const PtrList< coordSet > & , const wordList & valueSetNames, const List< List< Field< Type >>> & , Ostream &) const virtual
General entry point for writing of multiple coordSets.
Each coordSet (track) has same data variables. The data is per variable, per track, per point of track. If writeTracks adds connecting lines (wherever applicable)
Implements writer< Type >.
Definition at line 180 of file ensightSetWriter.C.
References Foam::component(), fld(), Foam::floatScalarVSMALL, Foam::FOAMversion, forAll, fileName::lessExt(), Foam::mag(), fileName::name(), IOstream::name(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, Foam::nl, OSstream::precision(), Foam::scientific(), IOstream::setf(), Foam::setw(), and List< T >::size().
The documentation for this class was generated from the following files:
src/fileFormats/sampledSetWriters/ensight/ensightSetWriter.H
src/fileFormats/sampledSetWriters/ensight/ensightSetWriter.C