OpenFOAM: porosityModel Class Reference
porosityModel Class Reference abstract
Top level model for porosity models.
Classes
class iNew
Return pointer to new porosityModel object created on the freestore.
Public Member Functions
TypeName ("porosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, porosityModel, mesh,(const word &modelName, const word &name, const fvMesh &mesh, const dictionary &dict, const word &cellZoneName),(modelName, name, mesh, dict, cellZoneName))
Selection table.
porosityModel (const word &name, const word &modelType, const fvMesh &mesh, const dictionary &dict, const word &cellZoneName=word::null)
Constructor.
virtual ~porosityModel ()
Destructor.
const word & name () const
Return const access to the porosity model name.
bool active () const
Return const access to the porosity active flag.
const labelList & cellZoneIDs () const
Return const access to the cell zone IDs.
virtual void transformModelData ()
Transform the model data wrt mesh changes.
virtual tmp< vectorField > force (const volVectorField &U, const volScalarField &rho, const volScalarField &mu)
Return the force over the cell zone(s)
virtual void addResistance (fvVectorMatrix &UEqn)
Add resistance.
virtual void addResistance (fvVectorMatrix &UEqn, const volScalarField &rho, const volScalarField &mu)
Add resistance.
virtual void addResistance (const fvVectorMatrix &UEqn, volTensorField &AU, bool correctAUprocBC)
Add resistance.
virtual bool writeData (Ostream &os) const
Write.
virtual bool read (const dictionary &dict)
Read porosity dictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static autoPtr< porosityModel > New (const word &name, const fvMesh &mesh, const dictionary &dict, const word &cellZoneName=word::null)
Selector.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Protected Member Functions
virtual void calcTransformModelData ()=0
Transform the model data wrt mesh changes.
void adjustNegativeResistance (dimensionedVector &resist)
Adjust negative resistance values to be multiplier of max value.
virtual void calcForce (const volVectorField &U, const volScalarField &rho, const volScalarField &mu, vectorField &force) const =0
Calculate the porosity force.
virtual void correct (fvVectorMatrix &UEqn) const =0
virtual void correct (fvVectorMatrix &UEqn, const volScalarField &rho, const volScalarField &mu) const =0
virtual void correct (const fvVectorMatrix &UEqn, volTensorField &AU) const =0
label fieldIndex (const label index) const
Return label index.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
word name_
Porosity name.
const fvMesh & mesh_
Reference to the mesh database.
const dictionary dict_
Dictionary used for model construction.
dictionary coeffs_
Model coefficients dictionary.
bool active_
Porosity active flag.
keyType zoneName_
Name(s) of cell-zone.
labelList cellZoneIDs_
Cell zone IDs.
coordinateSystem coordSys_
Local co-ordinate system.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Top level model for porosity models.
Source files
porosityModel.H
porosityModel.C
porosityModelNew.C
Definition at line 55 of file porosityModel.H.
Constructor & Destructor Documentation
porosityModel()
porosityModel (const word & name, const word & modelType, const fvMesh & mesh, const dictionary & dict, const word & cellZoneName = word::null)
Constructor.
Definition at line 78 of file porosityModel.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), UPstream::master(), word::null, and Foam::reduce().
~porosityModel()
~porosityModel () virtual
Destructor.
Definition at line 130 of file porosityModel.C.
Referenced by porosityModel::iNew::operator()().
Member Function Documentation
calcTransformModelData()
virtual void calcTransformModelData () protected pure virtual
Transform the model data wrt mesh changes.
Implemented in DarcyForchheimer, powerLaw, and fixedCoeff.
adjustNegativeResistance()
void adjustNegativeResistance (dimensionedVector & resist) protected
Adjust negative resistance values to be multiplier of max value.
Definition at line 40 of file porosityModel.C.
References Foam::cmptMax(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, and dimensioned< Type >::value().
calcForce()
virtual void calcForce (const volVectorField & U, const volScalarField & rho, const volScalarField & mu, vectorField & force) const protected pure virtual
Calculate the porosity force.
Implemented in DarcyForchheimer, powerLaw, and fixedCoeff.
correct() [1/3]
virtual void correct (fvVectorMatrix & UEqn) const protected pure virtual
Implemented in DarcyForchheimer, powerLaw, and fixedCoeff.
correct() [2/3]
virtual void correct (fvVectorMatrix & UEqn, const volScalarField & rho, const volScalarField & mu) const protected pure virtual
Implemented in DarcyForchheimer, powerLaw, and fixedCoeff.
correct() [3/3]
virtual void correct (const fvVectorMatrix & UEqn, volTensorField & AU) const protected pure virtual
Implemented in DarcyForchheimer, powerLaw, and fixedCoeff.
fieldIndex()
Foam::label fieldIndex (const label index) const protected
Return label index.
Definition at line 64 of file porosityModel.C.
TypeName()
TypeName ("porosityModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , porosityModel , mesh , (const word &modelName, const word &name, const fvMesh &mesh, const dictionary &dict, const word &cellZoneName) , (modelName, name, mesh, dict, cellZoneName))
Selection table.
New()
Foam::autoPtr< Foam::porosityModel > New (const word & name, const fvMesh & mesh, const dictionary & dict, const word & cellZoneName = word::null) static
Selector.
Definition at line 31 of file porosityModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), mesh, Foam::name(), and Foam::nl.
Referenced by explicitPorositySource::explicitPorositySource(), interRegionExplicitPorositySource::initialise(), porosityModel::iNew::operator()(), and porosityModelList::reset().
name()
const Foam::word & name () const inline
Return const access to the porosity model name.
Definition at line 26 of file porosityModelI.H.
References porosityModel::name_.
Referenced by porosityModel::iNew::operator()(), and porosityModelList::read().
active()
bool active () const inline
Return const access to the porosity active flag.
Definition at line 32 of file porosityModelI.H.
References porosityModel::active_.
Referenced by porosityModel::iNew::operator()().
cellZoneIDs()
const Foam::labelList & cellZoneIDs () const inline
Return const access to the cell zone IDs.
Definition at line 38 of file porosityModelI.H.
References porosityModel::cellZoneIDs_.
Referenced by forces::calcForcesMoment(), and porosityModel::iNew::operator()().
transformModelData()
void transformModelData () virtual
Transform the model data wrt mesh changes.
Definition at line 136 of file porosityModel.C.
References Foam::constant::physicoChemical::mu, tmp< T >::ref(), rho, List< T >::size(), U, and Foam::Zero.
Referenced by porosityModel::iNew::operator()().
force()
virtual tmp<vectorField> force (const volVectorField & U, const volScalarField & rho, const volScalarField & mu) virtual
Return the force over the cell zone(s)
Referenced by forces::calcForcesMoment(), and porosityModel::iNew::operator()().
addResistance() [1/3]
void addResistance (fvVectorMatrix & UEqn) virtual
Add resistance.
Definition at line 168 of file porosityModel.C.
References correct.
Referenced by porosityModel::addResistance(), and porosityModel::iNew::operator()().
addResistance() [2/3]
void addResistance (fvVectorMatrix & UEqn, const volScalarField & rho, const volScalarField & mu) virtual
Add resistance.
Definition at line 181 of file porosityModel.C.
References porosityModel::addResistance(), and correct.
addResistance() [3/3]
void addResistance (const fvVectorMatrix & UEqn, volTensorField & AU, bool correctAUprocBC) virtual
Add resistance.
Definition at line 198 of file porosityModel.C.
References correct, and GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions().
writeData()
bool writeData (Ostream & os) const virtual
Write.
Implements regIOobject.
Reimplemented in DarcyForchheimer, powerLaw, and fixedCoeff.
Definition at line 222 of file porosityModel.C.
Referenced by porosityModel::iNew::operator()().
read()
bool read (const dictionary & dict) virtual
Read porosity dictionary.
Definition at line 228 of file porosityModel.C.
References dictionary::lookup(), Foam::readBool(), dictionary::subDict(), and Foam::type().
Referenced by porosityModelList::read().
Member Data Documentation
name_
word name_ protected
Porosity name.
Definition at line 73 of file porosityModel.H.
Referenced by porosityModel::name().
mesh_
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 76 of file porosityModel.H.
dict_
const dictionary dict_ protected
Dictionary used for model construction.
Definition at line 79 of file porosityModel.H.
coeffs_
dictionary coeffs_ protected
Model coefficients dictionary.
Definition at line 82 of file porosityModel.H.
active_
bool active_ protected
Porosity active flag.
Definition at line 85 of file porosityModel.H.
Referenced by porosityModel::active().
zoneName_
keyType zoneName_ protected
Name(s) of cell-zone.
Definition at line 88 of file porosityModel.H.
cellZoneIDs_
labelList cellZoneIDs_ protected
Cell zone IDs.
Definition at line 91 of file porosityModel.H.
Referenced by porosityModel::cellZoneIDs().
coordSys_
coordinateSystem coordSys_ protected
Local co-ordinate system.
Definition at line 94 of file porosityModel.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/porosityModel/porosityModel/porosityModel.H
src/finiteVolume/cfdTools/general/porosityModel/porosityModel/porosityModel.C
src/finiteVolume/cfdTools/general/porosityModel/porosityModel/porosityModelI.H
src/finiteVolume/cfdTools/general/porosityModel/porosityModel/porosityModelNew.C