OpenFOAM: SRFFreestreamVelocityFvPatchVectorField Class Reference
SRFFreestreamVelocityFvPatchVectorField Class Reference
Public Member Functions
TypeName ("SRFFreestreamVelocity")
Runtime type information.
SRFFreestreamVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
SRFFreestreamVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given SRFFreestreamVelocityFvPatchVectorField.
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const vector & UInf () const
Return the velocity at infinity.
vector & UInf ()
Return reference to the velocity at infinity to allow adjustment.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Definition at line 120 of file SRFFreestreamVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
SRFFreestreamVelocityFvPatchVectorField() [1/5]
SRFFreestreamVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 38 of file SRFFreestreamVelocityFvPatchVectorField.C.
Referenced by SRFFreestreamVelocityFvPatchVectorField::clone(), and SRFFreestreamVelocityFvPatchVectorField::SRFFreestreamVelocityFvPatchVectorField().
SRFFreestreamVelocityFvPatchVectorField() [2/5]
SRFFreestreamVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 66 of file SRFFreestreamVelocityFvPatchVectorField.C.
References dictionary::lookupOrDefault(), fvPatch::size(), SRFFreestreamVelocityFvPatchVectorField::SRFFreestreamVelocityFvPatchVectorField(), and vectorField().
SRFFreestreamVelocityFvPatchVectorField() [3/5]
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given SRFFreestreamVelocityFvPatchVectorField.
onto a new patch
Definition at line 51 of file SRFFreestreamVelocityFvPatchVectorField.C.
References SRFFreestreamVelocityFvPatchVectorField::SRFFreestreamVelocityFvPatchVectorField().
SRFFreestreamVelocityFvPatchVectorField() [4/5]
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField & srfvpvf)
Construct as copy.
Definition at line 84 of file SRFFreestreamVelocityFvPatchVectorField.C.
References SRFFreestreamVelocityFvPatchVectorField::SRFFreestreamVelocityFvPatchVectorField().
SRFFreestreamVelocityFvPatchVectorField() [5/5]
SRFFreestreamVelocityFvPatchVectorField (const SRFFreestreamVelocityFvPatchVectorField & srfvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 96 of file SRFFreestreamVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("SRFFreestreamVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 173 of file SRFFreestreamVelocityFvPatchVectorField.H.
References SRFFreestreamVelocityFvPatchVectorField::SRFFreestreamVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 190 of file SRFFreestreamVelocityFvPatchVectorField.H.
References SRFFreestreamVelocityFvPatchVectorField::SRFFreestreamVelocityFvPatchVectorField().
UInf() [1/2]
const vector& UInf () const inline
Return the velocity at infinity.
Definition at line 206 of file SRFFreestreamVelocityFvPatchVectorField.H.
UInf() [2/2]
vector& UInf () inline
Return reference to the velocity at infinity to allow adjustment.
Definition at line 212 of file SRFFreestreamVelocityFvPatchVectorField.H.
References SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), and SRFFreestreamVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 109 of file SRFFreestreamVelocityFvPatchVectorField.C.
References SRFModel::axis(), Foam::cos(), Foam::mag(), mesh, Foam::name(), SRFModel::omega(), Foam::pos(), Foam::sin(), fvPatchField< Type >::updateCoeffs(), dimensioned< Type >::value(), and SRFModel::velocity().
Referenced by SRFFreestreamVelocityFvPatchVectorField::UInf().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 158 of file SRFFreestreamVelocityFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by SRFFreestreamVelocityFvPatchVectorField::UInf().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFFreestreamVelocityFvPatchVectorField/SRFFreestreamVelocityFvPatchVectorField.H
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFFreestreamVelocityFvPatchVectorField/SRFFreestreamVelocityFvPatchVectorField.C