OpenFOAM: porosityModelList Class Reference
porosityModelList Class Reference
List container for porosity models.
Public Member Functions
porosityModelList (const fvMesh &mesh, const dictionary &dict)
Constructor.
~porosityModelList ()
Destructor.
bool active (const bool active=false) const
Return active status.
void reset (const dictionary &dict)
Reset the source list.
void addResistance (fvVectorMatrix &UEqn)
Add resistance.
void addResistance (fvVectorMatrix &UEqn, const volScalarField &rho, const volScalarField &mu)
Add resistance.
void addResistance (const fvVectorMatrix &UEqn, volTensorField &AU, bool correctAUprocBC=true)
Add resistance.
bool read (const dictionary &dict)
Read dictionary.
bool writeData (Ostream &os) const
Write data to Ostream.
Public Member Functions inherited from PtrList< porosityModel >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< porosityModel > &)
Copy constructor.
PtrList (const PtrList< porosityModel > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< porosityModel >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< porosityModel > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< porosityModel > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (porosityModel *)
Append an element at the end of the list.
void append (const autoPtr< porosityModel > &)
void append (const tmp< porosityModel > &)
void transfer (PtrList< porosityModel > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< porosityModel > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< porosityModel > set (const label, porosityModel *)
Set element to given T* and return old element (can be nullptr)
autoPtr< porosityModel > set (const label, const autoPtr< porosityModel > &)
Set element to given autoPtr<T> and return old element.
autoPtr< porosityModel > set (const label, const tmp< porosityModel > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< porosityModel > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh database.
Friends
Ostream & operator<< (Ostream &os, const porosityModelList &models)
Ostream operator.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< porosityModel >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
List container for porosity models.
Source files
porosityModelList.H
porosityModelList.C
Definition at line 55 of file porosityModelList.H.
Constructor & Destructor Documentation
porosityModelList()
porosityModelList (const fvMesh & mesh, const dictionary & dict)
Constructor.
Definition at line 32 of file porosityModelList.C.
~porosityModelList()
~porosityModelList ()
Destructor.
Definition at line 48 of file porosityModelList.C.
Member Function Documentation
active()
bool active (const bool active = false) const
Return active status.
Definition at line 54 of file porosityModelList.C.
References Foam::endl(), forAll, Foam::Info, UPtrList< T >::operator[](), and UPtrList< T >::size().
reset()
void reset (const dictionary & dict)
Reset the source list.
Definition at line 71 of file porosityModelList.C.
References forAllConstIter(), porosityModelList::mesh_, Foam::name(), porosityModel::New(), and PtrList< porosityModel >::setSize().
addResistance() [1/3]
void addResistance (fvVectorMatrix & UEqn)
Add resistance.
Definition at line 127 of file porosityModelList.C.
References forAll, and UPtrList< T >::operator[]().
Referenced by porosityModelList::addResistance(), and porosityModelList::writeData().
addResistance() [2/3]
void addResistance (fvVectorMatrix & UEqn, const volScalarField & rho, const volScalarField & mu)
Add resistance.
Definition at line 139 of file porosityModelList.C.
References porosityModelList::addResistance(), forAll, and UPtrList< T >::operator[]().
addResistance() [3/3]
void addResistance (const fvVectorMatrix & UEqn, volTensorField & AU, bool correctAUprocBC = true)
Add resistance.
Definition at line 153 of file porosityModelList.C.
References forAll, and UPtrList< T >::operator[]().
read()
bool read (const dictionary & dict)
Read dictionary.
Definition at line 101 of file porosityModelList.C.
References forAll, porosityModel::name(), UPtrList< T >::operator[](), porosityModel::read(), and dictionary::subDict().
Referenced by IOporosityModelList::read().
writeData()
bool writeData (Ostream & os) const
Write data to Ostream.
Definition at line 114 of file porosityModelList.C.
References porosityModelList::addResistance(), forAll, IOstream::good(), Foam::nl, and UPtrList< T >::operator[]().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const porosityModelList & models) friend
Ostream operator.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 75 of file porosityModelList.H.
Referenced by porosityModelList::reset().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/porosityModel/porosityModel/porosityModelList.H
src/finiteVolume/cfdTools/general/porosityModel/porosityModel/porosityModelList.C