OpenFOAM: SRFWallVelocityFvPatchVectorField Class Reference
SRFWallVelocityFvPatchVectorField Class Reference
Boundary Conditions » Wall boundary Conditions
Wall-velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: FOAM::SRFModel)
Public Member Functions
TypeName ("SRFWallVelocity")
Runtime type information.
SRFWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
SRFWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given SRFWallVelocityFvPatchVectorField.
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Wall-velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: FOAM::SRFModel)
The condition applies the appropriate rotation transformation in time and space to determine the local SRF velocity of the wall.
where
=
=
The normal component of is removed to ensure 0 wall-flux even if the wall patch faces are irregular.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            SRFWallVelocity;
    value           uniform (0 0 0);    // Initial value
}
See also
Foam::SRFModel Foam::SRFVelocityFvPatchVectorField Foam::fixedValueFvPatchField
Source files
SRFWallVelocityFvPatchVectorField.H
SRFWallVelocityFvPatchVectorField.C
Definition at line 91 of file SRFWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
SRFWallVelocityFvPatchVectorField() [1/5]
SRFWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file SRFWallVelocityFvPatchVectorField.C.
Referenced by SRFWallVelocityFvPatchVectorField::clone(), and SRFWallVelocityFvPatchVectorField::SRFWallVelocityFvPatchVectorField().
SRFWallVelocityFvPatchVectorField() [2/5]
SRFWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 57 of file SRFWallVelocityFvPatchVectorField.C.
References SRFWallVelocityFvPatchVectorField::SRFWallVelocityFvPatchVectorField().
SRFWallVelocityFvPatchVectorField() [3/5]
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given SRFWallVelocityFvPatchVectorField.
onto a new patch
Definition at line 45 of file SRFWallVelocityFvPatchVectorField.C.
References SRFWallVelocityFvPatchVectorField::SRFWallVelocityFvPatchVectorField().
SRFWallVelocityFvPatchVectorField() [4/5]
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField & srfvpvf)
Construct as copy.
Definition at line 68 of file SRFWallVelocityFvPatchVectorField.C.
References SRFWallVelocityFvPatchVectorField::SRFWallVelocityFvPatchVectorField().
SRFWallVelocityFvPatchVectorField() [5/5]
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField & srfvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 77 of file SRFWallVelocityFvPatchVectorField.C.
References SRFWallVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("SRFWallVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 136 of file SRFWallVelocityFvPatchVectorField.H.
References SRFWallVelocityFvPatchVectorField::SRFWallVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 153 of file SRFWallVelocityFvPatchVectorField.H.
References SRFWallVelocityFvPatchVectorField::autoMap(), SRFWallVelocityFvPatchVectorField::rmap(), SRFWallVelocityFvPatchVectorField::SRFWallVelocityFvPatchVectorField(), SRFWallVelocityFvPatchVectorField::updateCoeffs(), and SRFWallVelocityFvPatchVectorField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 89 of file SRFWallVelocityFvPatchVectorField.C.
References SRFWallVelocityFvPatchVectorField::rmap().
Referenced by SRFWallVelocityFvPatchVectorField::clone(), and SRFWallVelocityFvPatchVectorField::SRFWallVelocityFvPatchVectorField().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 98 of file SRFWallVelocityFvPatchVectorField.C.
Referenced by SRFWallVelocityFvPatchVectorField::autoMap(), and SRFWallVelocityFvPatchVectorField::clone().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 107 of file SRFWallVelocityFvPatchVectorField.C.
References n, Field< vector >::operator=(), and SRFModel::velocity().
Referenced by SRFWallVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 130 of file SRFWallVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by SRFWallVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFWallVelocityFvPatchVectorField/SRFWallVelocityFvPatchVectorField.H
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFWallVelocityFvPatchVectorField/SRFWallVelocityFvPatchVectorField.C