OpenFOAM: coupledFvPatchField< Type > Class Template Reference
coupledFvPatchField< Type > Class Template Reference abstract
Boundary Conditions » Coupled boundary Conditions
Abstract base class for coupled patches.
Public Member Functions
TypeName (coupledFvPatch::typeName_())
Runtime type information.
coupledFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
coupledFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
coupledFvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &, const bool valueRequired=true)
Construct from patch, internal field and dictionary.
coupledFvPatchField (const coupledFvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given coupledFvPatchField onto a new patch.
coupledFvPatchField (const coupledFvPatchField< Type > &)
Construct as copy.
virtual tmp< fvPatchField< Type > > clone () const =0
Construct and return a clone.
coupledFvPatchField (const coupledFvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< Type > > clone (const DimensionedField< Type, volMesh > &) const =0
Construct and return a clone.
virtual bool coupled () const
Return true if this patch field is derived from.
virtual tmp< Field< Type > > patchNeighbourField () const =0
Return neighbour field of internal field.
virtual tmp< Field< Type > > snGrad (const scalarField &deltaCoeffs) const
Return patch-normal gradient.
virtual tmp< Field< Type > > snGrad () const
Return patch-normal gradient.
virtual void initEvaluate (const Pstream::commsTypes commsType)
Initialise the evaluation of the patch field.
virtual void evaluate (const Pstream::commsTypes commsType)
Evaluate the patch field.
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< scalarField > &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< scalarField > &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs (const scalarField &deltaCoeffs) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs (const scalarField &deltaCoeffs) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the.
virtual void updateInterfaceMatrix (scalarField &result, const scalarField &psiInternal, const scalarField &coeffs, const direction, const Pstream::commsTypes commsType) const =0
Update result field based on interface functionality.
virtual void updateInterfaceMatrix (Field< Type > &, const Field< Type > &, const scalarField &, const Pstream::commsTypes commsType) const =0
Update result field based on interface functionality.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from LduInterfaceField< Type >
TypeName ("LduInterfaceField")
Runtime type information.
LduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~LduInterfaceField ()
Destructor.
virtual void initInterfaceMatrixUpdate (Field< Type > &, const Field< Type > &, const scalarField &, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
Public Member Functions inherited from fvPatchField< Type >
TypeName ("fvPatchField")
Runtime type information.
declareRunTimeSelectionTable (tmp, fvPatchField, patch,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvPatchField, patchMapper,(const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvPatchFieldType &>(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict),(p, iF, dict))
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Type &value)
Construct from patch, internal field and value.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const word &patchType)
Construct from patch and internal field and patch type.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &, const bool valueRequired=true)
Construct from patch, internal field and dictionary.
fvPatchField (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fvPatchField onto a new patch.
fvPatchField (const fvPatchField< Type > &)
Construct as copy.
fvPatchField (const fvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual ~fvPatchField ()
Destructor.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool assignable () const
Return true if the value of the patch field.
const objectRegistry & db () const
Return local objectRegistry.
const fvPatch & patch () const
Return patch.
const DimensionedField< Type, volMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
bool updated () const
Return true if the boundary condition has already been updated.
bool manipulatedMatrix () const
Return true if the matrix has already been manipulated.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchField< Type > &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void updateWeightedCoeffs (const scalarField &weights)
Update the coefficients associated with the patch field.
virtual tmp< Field< Type > > patchInternalField () const
Return internal field next to patch as patch field.
virtual void patchInternalField (Field< Type > &) const
Return internal field next to patch as patch field.
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< Field< scalar >> &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< Field< scalar >> &) const
Return the matrix source coefficients corresponding to the.
virtual void manipulateMatrix (fvMatrix< Type > &matrix)
Manipulate matrix.
virtual void manipulateMatrix (fvMatrix< Type > &matrix, const scalarField &weights)
Manipulate matrix with given weights.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
void check (const fvPatchField< Type > &) const
Check fvPatchField<Type> against given fvPatchField<Type>
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvPatchField< Type > &)
virtual void operator+= (const fvPatchField< Type > &)
virtual void operator-= (const fvPatchField< Type > &)
virtual void operator*= (const fvPatchField< scalar > &)
virtual void operator/= (const fvPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const fvPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &pf)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< Type >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< Type >)
Assignment to an initializer list.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Additional Inherited Members
Public Types inherited from fvPatchField< Type >
typedef fvPatch Patch
typedef calculatedFvPatchField< Type > Calculated
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from fvPatchField< Type >
static tmp< fvPatchField< Type > > New (const word &, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const word &, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static tmp< fvPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatch &)
Return a pointer to a new calculatedFvPatchField created on.
template<class Type2 >
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &)
Return a pointer to a new calculatedFvPatchField created on.
static const word & calculatedType ()
Return the type of the calculated for of fvPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes inherited from fvPatchField< Type >
static int disallowGenericFvPatchField
Debug switch to disallow the use of genericFvPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::coupledFvPatchField< Type >
Abstract base class for coupled patches.
Source files
coupledFvPatchField.H
coupledFvPatchField.C
Definition at line 54 of file coupledFvPatchField.H.
Constructor & Destructor Documentation
coupledFvPatchField() [1/6]
coupledFvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF)
Construct from patch and internal field.
Definition at line 32 of file coupledFvPatchField.C.
Referenced by coupledFvPatchField< scalar >::coupledFvPatchField().
coupledFvPatchField() [2/6]
coupledFvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const Field< Type > & f)
Construct from patch and internal field and patch field.
Definition at line 44 of file coupledFvPatchField.C.
coupledFvPatchField() [3/6]
coupledFvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const dictionary & dict, const bool valueRequired = true)
Construct from patch, internal field and dictionary.
Definition at line 71 of file coupledFvPatchField.C.
coupledFvPatchField() [4/6]
coupledFvPatchField (const coupledFvPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping the given coupledFvPatchField onto a new patch.
Definition at line 57 of file coupledFvPatchField.C.
coupledFvPatchField() [5/6]
coupledFvPatchField (const coupledFvPatchField< Type > & ptf)
Construct as copy.
Definition at line 85 of file coupledFvPatchField.C.
coupledFvPatchField() [6/6]
coupledFvPatchField (const coupledFvPatchField< Type > & ptf, const DimensionedField< Type, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 96 of file coupledFvPatchField.C.
Member Function Documentation
TypeName()
TypeName (coupledFvPatch::typeName_())
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchField<Type> > clone () const pure virtual
Construct and return a clone.
Reimplemented from fvPatchField< Type >.
Implemented in porousBafflePressureFvPatchField< Type >, fanFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, fixedJumpAMIFvPatchField< Type >, fixedJumpAMIFvPatchField< scalar >, fixedJumpFvPatchField< Type >, fixedJumpFvPatchField< scalar >, processorFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, cyclicACMIFvPatchField< Type >, processorCyclicFvPatchField< Type >, cyclicSlipFvPatchField< Type >, nonuniformTransformCyclicFvPatchField< Type >, energyJumpFvPatchScalarField, and energyJumpAMIFvPatchScalarField.
clone() [2/2]
virtual tmp<fvPatchField<Type> > clone (const DimensionedField< Type, volMesh > &) const pure virtual
Construct and return a clone.
Reimplemented from fvPatchField< Type >.
Implemented in fanFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, fixedJumpAMIFvPatchField< Type >, fixedJumpFvPatchField< Type >, processorFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, cyclicACMIFvPatchField< Type >, processorCyclicFvPatchField< Type >, cyclicSlipFvPatchField< Type >, and nonuniformTransformCyclicFvPatchField< Type >.
coupled()
virtual bool coupled () const inline virtual
Return true if this patch field is derived from.
coupledFvPatchField<Type>.
Reimplemented from fvPatchField< Type >.
Reimplemented in processorFvPatchField< Type >, cyclicAMIFvPatchField< Type >, and cyclicACMIFvPatchField< Type >.
Definition at line 130 of file coupledFvPatchField.H.
patchNeighbourField()
virtual tmp<Field<Type> > patchNeighbourField () const pure virtual
Return neighbour field of internal field.
Reimplemented from fvPatchField< Type >.
Implemented in energyRegionCoupledFvPatchScalarField, cyclicACMIFvPatchField< Type >, processorFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
snGrad() [1/2]
Foam::tmp< Foam::Field< Type > > snGrad (const scalarField & deltaCoeffs) const virtual
Return patch-normal gradient.
Reimplemented from fvPatchField< Type >.
Reimplemented in energyRegionCoupledFvPatchScalarField, and processorFvPatchField< Type >.
Definition at line 110 of file coupledFvPatchField.C.
snGrad() [2/2]
virtual tmp<Field<Type> > snGrad () const inline virtual
Return patch-normal gradient.
Reimplemented from fvPatchField< Type >.
Reimplemented in energyRegionCoupledFvPatchScalarField.
Definition at line 148 of file coupledFvPatchField.H.
Referenced by processorFvPatchField< Type >::coupled(), coupledFvPatchField< scalar >::coupledFvPatchField(), and processorFvPatchField< Type >::evaluate().
initEvaluate()
void initEvaluate (const Pstream::commsTypes commsType) virtual
Initialise the evaluation of the patch field.
Reimplemented from fvPatchField< Type >.
Reimplemented in processorFvPatchField< Type >.
Definition at line 121 of file coupledFvPatchField.C.
Referenced by coupledFvPatchField< scalar >::snGrad().
evaluate()
void evaluate (const Pstream::commsTypes commsType) virtual
Evaluate the patch field.
Reimplemented from fvPatchField< Type >.
Reimplemented in energyRegionCoupledFvPatchScalarField, and processorFvPatchField< Type >.
Definition at line 131 of file coupledFvPatchField.C.
Referenced by coupledFvPatchField< scalar >::snGrad().
valueInternalCoeffs()
Foam::tmp< Foam::Field< Type > > valueInternalCoeffs (const tmp< scalarField > & w) const virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the value of this patchField with given weights
Definition at line 151 of file coupledFvPatchField.C.
Referenced by coupledFvPatchField< scalar >::evaluate(), and coupledFvPatchField< scalar >::snGrad().
valueBoundaryCoeffs()
Foam::tmp< Foam::Field< Type > > valueBoundaryCoeffs (const tmp< scalarField > & w) const virtual
Return the matrix source coefficients corresponding to the.
evaluation of the value of this patchField with given weights
Definition at line 162 of file coupledFvPatchField.C.
Referenced by coupledFvPatchField< scalar >::snGrad(), and coupledFvPatchField< scalar >::valueInternalCoeffs().
gradientInternalCoeffs() [1/2]
Foam::tmp< Foam::Field< Type > > gradientInternalCoeffs (const scalarField & deltaCoeffs) const virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the gradient of this patchField
Reimplemented from fvPatchField< Type >.
Definition at line 173 of file coupledFvPatchField.C.
gradientInternalCoeffs() [2/2]
Foam::tmp< Foam::Field< Type > > gradientInternalCoeffs () const virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the gradient of this patchField
Reimplemented from fvPatchField< Type >.
Definition at line 183 of file coupledFvPatchField.C.
Referenced by coupledFvPatchField< scalar >::snGrad(), and coupledFvPatchField< scalar >::valueBoundaryCoeffs().
gradientBoundaryCoeffs() [1/2]
Foam::tmp< Foam::Field< Type > > gradientBoundaryCoeffs (const scalarField & deltaCoeffs) const virtual
Return the matrix source coefficients corresponding to the.
evaluation of the gradient of this patchField
Reimplemented from fvPatchField< Type >.
Definition at line 193 of file coupledFvPatchField.C.
gradientBoundaryCoeffs() [2/2]
Foam::tmp< Foam::Field< Type > > gradientBoundaryCoeffs () const virtual
Return the matrix source coefficients corresponding to the.
evaluation of the gradient of this patchField
Reimplemented from fvPatchField< Type >.
Definition at line 203 of file coupledFvPatchField.C.
Referenced by coupledFvPatchField< scalar >::gradientInternalCoeffs(), and coupledFvPatchField< scalar >::snGrad().
updateInterfaceMatrix() [1/2]
virtual void updateInterfaceMatrix (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction , const Pstream::commsTypes commsType) const pure virtual
Update result field based on interface functionality.
Implements lduInterfaceField.
Implemented in energyRegionCoupledFvPatchScalarField, processorFvPatchField< Type >, cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, jumpCyclicFvPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, jumpCyclicFvPatchField< Type >, processorFvPatchField< Type >, processorFvPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
Referenced by coupledFvPatchField< scalar >::snGrad().
updateInterfaceMatrix() [2/2]
virtual void updateInterfaceMatrix (Field< Type > & , const Field< Type > & , const scalarField & , const Pstream::commsTypes commsType) const pure virtual
Update result field based on interface functionality.
Implements LduInterfaceField< Type >.
Implemented in processorFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from fvPatchField< Type >.
Reimplemented in cyclicACMIFvPatchField< Type >, porousBafflePressureFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, fanFvPatchField< Type >, fixedJumpFvPatchField< Type >, fixedJumpFvPatchField< scalar >, fixedJumpAMIFvPatchField< Type >, fixedJumpAMIFvPatchField< scalar >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, energyJumpFvPatchScalarField, and energyJumpAMIFvPatchScalarField.
Definition at line 211 of file coupledFvPatchField.C.
Referenced by coupledFvPatchField< scalar >::snGrad().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/basic/coupled/coupledFvPatchField.H
src/finiteVolume/fields/fvPatchFields/basic/coupled/coupledFvPatchField.C