OpenFOAM: simpleControl Class Reference
simpleControl Class Reference
SIMPLE control class to supply convergence information/checks for the SIMPLE loop.
Public Member Functions
TypeName ("simpleControl")
Run-time type information.
simpleControl (fvMesh &mesh)
Construct from mesh.
virtual ~simpleControl ()
Destructor.
virtual bool loop ()
Loop loop.
Public Member Functions inherited from solutionControl
TypeName ("solutionControl")
Run-time type information.
solutionControl (fvMesh &mesh, const word &algorithmName)
Construct from mesh.
virtual ~solutionControl ()
Destructor.
const dictionary & dict () const
Return the solution dictionary.
label corr () const
Current corrector loop index.
label corrNonOrtho () const
Current non-orthogonal corrector index.
label nNonOrthCorr () const
Maximum number of non-orthogonal correctors.
bool finalNonOrthogonalIter () const
Helper function to identify final non-orthogonal iteration.
bool momentumPredictor () const
Flag to indicate to solve for momentum.
bool transonic () const
Flag to indicate to solve using transonic algorithm.
bool consistent () const
Flag to indicate to relax pressure using the.
bool correctNonOrthogonal ()
Non-orthogonal corrector loop.
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
virtual void rename (const word &newName)
Rename.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Protected Member Functions
void read ()
Read controls from fvSolution dictionary.
bool criteriaSatisfied ()
Return true if all convergence checks are satisfied.
Protected Member Functions inherited from solutionControl
virtual void read (const bool absTolOnly)
Read controls from fvSolution dictionary.
virtual label applyToField (const word &fieldName, const bool useRegEx=true) const
Return index of field in residualControl_ if present.
virtual void storePrevIterFields () const
Store previous iteration fields.
template<class Type >
void storePrevIter () const
Store previous iteration field for vol<Type>Fields.
template<class Type >
void maxTypeResidual (const word &fieldName, ITstream &data, scalar &firstRes, scalar &lastRes) const
scalar maxResidual (const word &fieldName, ITstream &data, scalar &lastRes) const
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
bool initialised_
Initialised flag.
Protected Attributes inherited from solutionControl
fvMesh & mesh_
Reference to the mesh database.
List< fieldData > residualControl_
List of residual data per field.
const word algorithmName_
The dictionary name, e.g. SIMPLE, PIMPLE.
label nNonOrthCorr_
Maximum number of non-orthogonal correctors.
bool momentumPredictor_
Flag to indicate to solve for momentum.
bool transonic_
Flag to indicate to solve using transonic algorithm.
bool consistent_
Flag to indicate to relax pressure using the.
label corr_
Current corrector loop index.
label corrNonOrtho_
Current non-orthogonal corrector loop index.
Additional Inherited Members
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Detailed Description
SIMPLE control class to supply convergence information/checks for the SIMPLE loop.
Definition at line 49 of file simpleControl.H.
Constructor & Destructor Documentation
simpleControl()
simpleControl (fvMesh & mesh)
Construct from mesh.
Definition at line 88 of file simpleControl.C.
References solutionControl::algorithmName_, Foam::endl(), Time::endTime(), forAll, Foam::Info, solutionControl::mesh_, Foam::nl, simpleControl::read(), solutionControl::residualControl_, Time::startTime(), token::TAB, fvMesh::time(), and dimensioned< Type >::value().
~simpleControl()
~simpleControl () virtual
Destructor.
Definition at line 120 of file simpleControl.C.
Member Function Documentation
read()
void read () protected virtual
Read controls from fvSolution dictionary.
Reimplemented from solutionControl.
Definition at line 39 of file simpleControl.C.
References solutionControl::read().
Referenced by simpleControl::loop(), and simpleControl::simpleControl().
criteriaSatisfied()
bool criteriaSatisfied () protected virtual
Return true if all convergence checks are satisfied.
Implements solutionControl.
Definition at line 45 of file simpleControl.C.
References Foam::endl(), forAllConstIter(), and Foam::Info.
Referenced by simpleControl::loop().
TypeName()
TypeName ("simpleControl")
Run-time type information.
loop()
bool loop () virtual
Loop loop.
Implements solutionControl.
Definition at line 126 of file simpleControl.C.
References solutionControl::algorithmName_, simpleControl::criteriaSatisfied(), Foam::endl(), Foam::Info, simpleControl::initialised_, Time::loop(), solutionControl::mesh_, Foam::nl, simpleControl::read(), solutionControl::storePrevIterFields(), fvMesh::time(), IOobject::time(), Time::timeName(), and Time::writeAndEnd().
Member Data Documentation
initialised_
bool initialised_ protected
Initialised flag.
Definition at line 59 of file simpleControl.H.
Referenced by simpleControl::loop().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/solutionControl/simpleControl/simpleControl.H
src/finiteVolume/cfdTools/general/solutionControl/simpleControl/simpleControl.C