OpenFOAM: solutionControl Class Reference
solutionControl Class Reference abstract
Base class for solution control classes.
Classes
struct fieldData
Public Member Functions
TypeName ("solutionControl")
Run-time type information.
solutionControl (fvMesh &mesh, const word &algorithmName)
Construct from mesh.
virtual ~solutionControl ()
Destructor.
const dictionary & dict () const
Return the solution dictionary.
label corr () const
Current corrector loop index.
label corrNonOrtho () const
Current non-orthogonal corrector index.
label nNonOrthCorr () const
Maximum number of non-orthogonal correctors.
bool finalNonOrthogonalIter () const
Helper function to identify final non-orthogonal iteration.
bool momentumPredictor () const
Flag to indicate to solve for momentum.
bool transonic () const
Flag to indicate to solve using transonic algorithm.
bool consistent () const
Flag to indicate to relax pressure using the.
virtual bool loop ()=0
Main control loop.
bool correctNonOrthogonal ()
Non-orthogonal corrector loop.
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
virtual void rename (const word &newName)
Rename.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Protected Member Functions
virtual void read (const bool absTolOnly)
Read controls from fvSolution dictionary.
virtual void read ()
Read controls from fvSolution dictionary.
virtual label applyToField (const word &fieldName, const bool useRegEx=true) const
Return index of field in residualControl_ if present.
virtual bool criteriaSatisfied ()=0
Return true if all convergence checks are satisfied.
virtual void storePrevIterFields () const
Store previous iteration fields.
template<class Type >
void storePrevIter () const
Store previous iteration field for vol<Type>Fields.
template<class Type >
void maxTypeResidual (const word &fieldName, ITstream &data, scalar &firstRes, scalar &lastRes) const
scalar maxResidual (const word &fieldName, ITstream &data, scalar &lastRes) const
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes
fvMesh & mesh_
Reference to the mesh database.
List< fieldData > residualControl_
List of residual data per field.
const word algorithmName_
The dictionary name, e.g. SIMPLE, PIMPLE.
label nNonOrthCorr_
Maximum number of non-orthogonal correctors.
bool momentumPredictor_
Flag to indicate to solve for momentum.
bool transonic_
Flag to indicate to solve using transonic algorithm.
bool consistent_
Flag to indicate to relax pressure using the.
label corr_
Current corrector loop index.
label corrNonOrtho_
Current non-orthogonal corrector loop index.
Additional Inherited Members
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Detailed Description
Base class for solution control classes.
Definition at line 45 of file solutionControl.H.
Constructor & Destructor Documentation
solutionControl()
solutionControl (fvMesh & mesh, const word & algorithmName)
Construct from mesh.
Definition at line 216 of file solutionControl.C.
~solutionControl()
~solutionControl () virtual
Destructor.
Definition at line 238 of file solutionControl.C.
Member Function Documentation
read() [1/2]
void read (const bool absTolOnly) protected virtual
Read controls from fvSolution dictionary.
Definition at line 38 of file solutionControl.C.
References solutionControl::fieldData::absTol, dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIter(), Foam::Info, solutionControl::fieldData::initialResidual, dictionary::lookup(), dictionary::lookupOrDefault(), solutionControl::fieldData::name, Foam::nl, Foam::readScalar(), solutionControl::fieldData::relTol, solutionDict(), and dictionary::subOrEmptyDict().
read() [2/2]
void read () protected virtual
Read controls from fvSolution dictionary.
Reimplemented in pimpleControl, and simpleControl.
Definition at line 136 of file solutionControl.C.
References solutionControl::applyToField(), and Foam::read().
Referenced by simpleControl::read(), and pimpleControl::read().
applyToField()
Foam::label applyToField (const word & fieldName, const bool useRegEx = true) const protected virtual
Return index of field in residualControl_ if present.
Definition at line 143 of file solutionControl.C.
References forAll, string::match(), and Foam::name().
Referenced by solutionControl::read().
criteriaSatisfied()
virtual bool criteriaSatisfied () protected pure virtual
Return true if all convergence checks are satisfied.
Implemented in pimpleControl, and simpleControl.
storePrevIterFields()
void storePrevIterFields () const protected virtual
Store previous iteration fields.
Definition at line 164 of file solutionControl.C.
References solutionControl::maxTypeResidual().
Referenced by simpleControl::loop(), and pimpleControl::loop().
storePrevIter()
void storePrevIter () const protected
Store previous iteration field for vol<Type>Fields.
Definition at line 33 of file solutionControlTemplates.C.
References solutionControl::algorithmName_, Foam::endl(), fld(), forAllIter, Foam::Info, solutionControl::mesh_, and solution::relaxField().
maxTypeResidual()
void maxTypeResidual (const word & fieldName, ITstream & data, scalar & firstRes, scalar & lastRes) const protected
Definition at line 177 of file solutionControl.C.
References Foam::cmptMax(), UList< T >::first(), UList< T >::last(), and solutionControl::maxResidual().
Referenced by solutionControl::storePrevIterFields().
maxResidual()
Foam::scalar maxResidual (const word & fieldName, ITstream & data, scalar & lastRes) const protected
Definition at line 196 of file solutionControl.C.
Referenced by solutionControl::maxTypeResidual().
TypeName()
TypeName ("solutionControl")
Run-time type information.
dict()
const Foam::dictionary & dict () const inline
Return the solution dictionary.
Definition at line 28 of file solutionControlI.H.
References solutionControl::algorithmName_, solutionControl::mesh_, solution::solutionDict(), and dictionary::subDict().
corr()
Foam::label corr () const inline
Current corrector loop index.
Definition at line 34 of file solutionControlI.H.
References solutionControl::corr_.
corrNonOrtho()
Foam::label corrNonOrtho () const inline
Current non-orthogonal corrector index.
Definition at line 40 of file solutionControlI.H.
References solutionControl::corrNonOrtho_.
nNonOrthCorr()
Foam::label nNonOrthCorr () const inline
Maximum number of non-orthogonal correctors.
Definition at line 46 of file solutionControlI.H.
References solutionControl::nNonOrthCorr_.
finalNonOrthogonalIter()
bool finalNonOrthogonalIter () const inline
Helper function to identify final non-orthogonal iteration.
Definition at line 52 of file solutionControlI.H.
References solutionControl::corrNonOrtho_, and solutionControl::nNonOrthCorr_.
Referenced by Foam::CorrectPhi().
momentumPredictor()
bool momentumPredictor () const inline
Flag to indicate to solve for momentum.
Definition at line 58 of file solutionControlI.H.
References solutionControl::momentumPredictor_.
transonic()
bool transonic () const inline
Flag to indicate to solve using transonic algorithm.
Definition at line 64 of file solutionControlI.H.
References solutionControl::transonic_.
consistent()
bool consistent () const inline
Flag to indicate to relax pressure using the.
"consistent" approach of SIMPLEC
Definition at line 70 of file solutionControlI.H.
References solutionControl::consistent_.
loop()
virtual bool loop () pure virtual
Main control loop.
Implemented in pimpleControl, and simpleControl.
correctNonOrthogonal()
bool correctNonOrthogonal () inline
Non-orthogonal corrector loop.
Definition at line 76 of file solutionControlI.H.
References solutionControl::algorithmName_, solutionControl::corrNonOrtho_, Foam::endl(), Foam::Info, and solutionControl::nNonOrthCorr_.
Referenced by Foam::CorrectPhi().
Member Data Documentation
mesh_
fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 65 of file solutionControl.H.
Referenced by solutionControl::dict(), simpleControl::loop(), pimpleControl::loop(), simpleControl::simpleControl(), and solutionControl::storePrevIter().
residualControl_
List<fieldData> residualControl_ protected
List of residual data per field.
Definition at line 68 of file solutionControl.H.
Referenced by pimpleControl::loop(), pimpleControl::pimpleControl(), and simpleControl::simpleControl().
algorithmName_
const word algorithmName_ protected
The dictionary name, e.g. SIMPLE, PIMPLE.
Definition at line 71 of file solutionControl.H.
Referenced by pimpleControl::correct(), solutionControl::correctNonOrthogonal(), solutionControl::dict(), simpleControl::loop(), pimpleControl::loop(), pimpleControl::pimpleControl(), simpleControl::simpleControl(), and solutionControl::storePrevIter().
nNonOrthCorr_
label nNonOrthCorr_ protected
Maximum number of non-orthogonal correctors.
Definition at line 77 of file solutionControl.H.
Referenced by solutionControl::correctNonOrthogonal(), pimpleControl::finalInnerIter(), solutionControl::finalNonOrthogonalIter(), and solutionControl::nNonOrthCorr().
momentumPredictor_
bool momentumPredictor_ protected
Flag to indicate to solve for momentum.
Definition at line 80 of file solutionControl.H.
Referenced by solutionControl::momentumPredictor().
transonic_
bool transonic_ protected
Flag to indicate to solve using transonic algorithm.
Definition at line 83 of file solutionControl.H.
Referenced by solutionControl::transonic().
consistent_
bool consistent_ protected
Flag to indicate to relax pressure using the.
"consistent" approach of SIMPLEC
Definition at line 87 of file solutionControl.H.
Referenced by solutionControl::consistent().
corr_
label corr_ protected
Current corrector loop index.
Definition at line 93 of file solutionControl.H.
Referenced by solutionControl::corr(), pimpleControl::finalIter(), pimpleControl::firstIter(), pimpleControl::loop(), and pimpleControl::storeInitialResiduals().
corrNonOrtho_
label corrNonOrtho_ protected
Current non-orthogonal corrector loop index.
Definition at line 96 of file solutionControl.H.
Referenced by solutionControl::correctNonOrthogonal(), solutionControl::corrNonOrtho(), pimpleControl::finalInnerIter(), solutionControl::finalNonOrthogonalIter(), and pimpleControl::storeInitialResiduals().
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/solutionControl/solutionControl/solutionControl.H
src/finiteVolume/cfdTools/general/solutionControl/solutionControl/solutionControl.C
src/finiteVolume/cfdTools/general/solutionControl/solutionControl/solutionControlI.H
src/finiteVolume/cfdTools/general/solutionControl/solutionControl/solutionControlTemplates.C