OpenFOAM: activeBaffleVelocityFvPatchVectorField Class Reference
activeBaffleVelocityFvPatchVectorField Class Reference
Boundary Conditions » Coupled boundary Conditions
This velocity boundary condition simulates the opening of a baffle due to local flow conditions, by merging the behaviours of wall and cyclic conditions. The baffle joins two mesh regions, where the open fraction determines the interpolation weights applied to each cyclic- and neighbour-patch contribution.
Public Member Functions
TypeName ("activeBaffleVelocity")
Runtime type information.
activeBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
activeBaffleVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given activeBaffleVelocityFvPatchVectorField.
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This velocity boundary condition simulates the opening of a baffle due to local flow conditions, by merging the behaviours of wall and cyclic conditions. The baffle joins two mesh regions, where the open fraction determines the interpolation weights applied to each cyclic- and neighbour-patch contribution.
We determine whether the baffle is opening or closing from the sign of the net force across the baffle, from which the baffle open fraction is updated using:
where
= baffle open fraction [0-1]
= baffle open fraction on previous evaluation
= simulation time step
= time taken to open the baffle
= net force across the baffle
The open fraction is then applied to scale the patch areas.
Usage
Property Description Required Default value
p pressure field name no p
cyclicPatch cylclic patch name yes
orientation 1 or -1 used to switch flow direction yes
openFraction current opatch open fraction [0-1] yes
openingTime time taken to open the baffle yes
maxOpenFractionDelta max open fraction change per timestep yes
Example of the boundary condition specification:
    <patchName>
    {
        type            activeBaffleVelocity;
        p               p;
        cyclicPatch     cyclic1;
        orientation     1;
        openFraction    0.2;
        openingTime     5.0;
        maxOpenFractionDelta 0.1;
    }
See also
Foam::fixedValueFvPatchField Foam::cyclicFvPatchField
Source files
activeBaffleVelocityFvPatchVectorField.H
activeBaffleVelocityFvPatchVectorField.C
Definition at line 160 of file activeBaffleVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
activeBaffleVelocityFvPatchVectorField() [1/5]
activeBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file activeBaffleVelocityFvPatchVectorField.C.
Referenced by activeBaffleVelocityFvPatchVectorField::activeBaffleVelocityFvPatchVectorField(), and activeBaffleVelocityFvPatchVectorField::clone().
activeBaffleVelocityFvPatchVectorField() [2/5]
activeBaffleVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 82 of file activeBaffleVelocityFvPatchVectorField.C.
References activeBaffleVelocityFvPatchVectorField::activeBaffleVelocityFvPatchVectorField(), and Foam::Zero.
activeBaffleVelocityFvPatchVectorField() [3/5]
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given activeBaffleVelocityFvPatchVectorField.
onto a new patch
Definition at line 58 of file activeBaffleVelocityFvPatchVectorField.C.
References activeBaffleVelocityFvPatchVectorField::activeBaffleVelocityFvPatchVectorField().
activeBaffleVelocityFvPatchVectorField() [4/5]
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField & ptf)
Construct as copy.
Definition at line 113 of file activeBaffleVelocityFvPatchVectorField.C.
References activeBaffleVelocityFvPatchVectorField::activeBaffleVelocityFvPatchVectorField().
activeBaffleVelocityFvPatchVectorField() [5/5]
activeBaffleVelocityFvPatchVectorField (const activeBaffleVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 134 of file activeBaffleVelocityFvPatchVectorField.C.
References activeBaffleVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("activeBaffleVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 243 of file activeBaffleVelocityFvPatchVectorField.H.
References activeBaffleVelocityFvPatchVectorField::activeBaffleVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 260 of file activeBaffleVelocityFvPatchVectorField.H.
References activeBaffleVelocityFvPatchVectorField::activeBaffleVelocityFvPatchVectorField(), activeBaffleVelocityFvPatchVectorField::autoMap(), activeBaffleVelocityFvPatchVectorField::rmap(), activeBaffleVelocityFvPatchVectorField::updateCoeffs(), and activeBaffleVelocityFvPatchVectorField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Note: cannot map field from cyclic patch anyway so just recalculate
Areas should be consistent when doing autoMap except in case of topo changes. ! Note: we don't want to use Sf here since triggers rebuilding of /*! fvMesh::S() which will give problems when mapped (since already on new mesh)
Definition at line 157 of file activeBaffleVelocityFvPatchVectorField.C.
Referenced by activeBaffleVelocityFvPatchVectorField::activeBaffleVelocityFvPatchVectorField(), and activeBaffleVelocityFvPatchVectorField::clone().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 186 of file activeBaffleVelocityFvPatchVectorField.C.
Referenced by activeBaffleVelocityFvPatchVectorField::clone().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 210 of file activeBaffleVelocityFvPatchVectorField.C.
Referenced by activeBaffleVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 292 of file activeBaffleVelocityFvPatchVectorField.C.
Referenced by activeBaffleVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/activeBaffleVelocity/activeBaffleVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/activeBaffleVelocity/activeBaffleVelocityFvPatchVectorField.C