OpenFOAM: fixedFluxExtrapolatedPressureFvPatchScalarField Class Reference
fixedFluxExtrapolatedPressureFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Wall boundary Conditions
This boundary condition sets the pressure gradient to the provided value such that the flux on the boundary is that specified by the velocity boundary condition.
Public Member Functions
TypeName ("fixedFluxExtrapolatedPressure")
Runtime type information.
fixedFluxExtrapolatedPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fixedFluxExtrapolatedPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedFluxExtrapolatedPressureFvPatchScalarField (const fixedFluxExtrapolatedPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
fixedFluxExtrapolatedPressureFvPatchScalarField (const fixedFluxExtrapolatedPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
fixedFluxExtrapolatedPressureFvPatchScalarField (const fixedFluxExtrapolatedPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
Public Member Functions inherited from fixedFluxPressureFvPatchScalarField
TypeName ("fixedFluxPressure")
Runtime type information.
fixedFluxPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fixedFluxPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedFluxPressureFvPatchScalarField (const fixedFluxPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given fixedFluxPressureFvPatchScalarField onto.
fixedFluxPressureFvPatchScalarField (const fixedFluxPressureFvPatchScalarField &)
Construct as copy.
fixedFluxPressureFvPatchScalarField (const fixedFluxPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void updateCoeffs (const scalarField &snGradp)
Update the patch pressure gradient field from the given snGradp.
virtual void updateCoeffs ()
Update the patch pressure gradient field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition sets the pressure gradient to the provided value such that the flux on the boundary is that specified by the velocity boundary condition.
Example of the boundary condition specification:
<patchName>
{
    type            fixedFluxExtrapolatedPressure;
}
See also
Foam::fixedGradientFvPatchField
Source files
fixedFluxExtrapolatedPressureFvPatchScalarField.H
fixedFluxExtrapolatedPressureFvPatchScalarField.C
Definition at line 64 of file fixedFluxExtrapolatedPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedFluxExtrapolatedPressureFvPatchScalarField() [1/5]
fixedFluxExtrapolatedPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 33 of file fixedFluxExtrapolatedPressureFvPatchScalarField.C.
Referenced by fixedFluxExtrapolatedPressureFvPatchScalarField::clone(), and fixedFluxExtrapolatedPressureFvPatchScalarField::fixedFluxExtrapolatedPressureFvPatchScalarField().
fixedFluxExtrapolatedPressureFvPatchScalarField() [2/5]
fixedFluxExtrapolatedPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 44 of file fixedFluxExtrapolatedPressureFvPatchScalarField.C.
References fixedFluxExtrapolatedPressureFvPatchScalarField::fixedFluxExtrapolatedPressureFvPatchScalarField().
fixedFluxExtrapolatedPressureFvPatchScalarField() [3/5]
fixedFluxExtrapolatedPressureFvPatchScalarField (const fixedFluxExtrapolatedPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
fixedFluxExtrapolatedPressureFvPatchScalarField onto a new patch
Definition at line 56 of file fixedFluxExtrapolatedPressureFvPatchScalarField.C.
References fixedFluxExtrapolatedPressureFvPatchScalarField::fixedFluxExtrapolatedPressureFvPatchScalarField().
fixedFluxExtrapolatedPressureFvPatchScalarField() [4/5]
fixedFluxExtrapolatedPressureFvPatchScalarField (const fixedFluxExtrapolatedPressureFvPatchScalarField & wbppsf)
Construct as copy.
Definition at line 69 of file fixedFluxExtrapolatedPressureFvPatchScalarField.C.
References fixedFluxExtrapolatedPressureFvPatchScalarField::fixedFluxExtrapolatedPressureFvPatchScalarField().
fixedFluxExtrapolatedPressureFvPatchScalarField() [5/5]
fixedFluxExtrapolatedPressureFvPatchScalarField (const fixedFluxExtrapolatedPressureFvPatchScalarField & wbppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 79 of file fixedFluxExtrapolatedPressureFvPatchScalarField.C.
References Foam::makePatchTypeField().
Member Function Documentation
TypeName()
TypeName ("fixedFluxExtrapolatedPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from fixedFluxPressureFvPatchScalarField.
Definition at line 109 of file fixedFluxExtrapolatedPressureFvPatchScalarField.H.
References fixedFluxExtrapolatedPressureFvPatchScalarField::fixedFluxExtrapolatedPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from fixedFluxPressureFvPatchScalarField.
Definition at line 126 of file fixedFluxExtrapolatedPressureFvPatchScalarField.H.
References fixedFluxExtrapolatedPressureFvPatchScalarField::fixedFluxExtrapolatedPressureFvPatchScalarField().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fixedFluxExtrapolatedPressure/fixedFluxExtrapolatedPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/fixedFluxExtrapolatedPressure/fixedFluxExtrapolatedPressureFvPatchScalarField.C