OpenFOAM: fixedFluxPressureFvPatchScalarField Class Reference
fixedFluxPressureFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Wall boundary Conditions
This boundary condition sets the pressure gradient to the provided value such that the flux on the boundary is that specified by the velocity boundary condition.
Public Member Functions
TypeName ("fixedFluxPressure")
Runtime type information.
fixedFluxPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fixedFluxPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedFluxPressureFvPatchScalarField (const fixedFluxPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given fixedFluxPressureFvPatchScalarField onto.
fixedFluxPressureFvPatchScalarField (const fixedFluxPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
fixedFluxPressureFvPatchScalarField (const fixedFluxPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs (const scalarField &snGradp)
Update the patch pressure gradient field from the given snGradp.
virtual void updateCoeffs ()
Update the patch pressure gradient field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition sets the pressure gradient to the provided value such that the flux on the boundary is that specified by the velocity boundary condition.
Example of the boundary condition specification:
<patchName>
{
    type            fixedFluxPressure;
}
See also
Foam::fixedGradientFvPatchField
Source files
fixedFluxPressureFvPatchScalarField.H
fixedFluxPressureFvPatchScalarField.C
Definition at line 65 of file fixedFluxPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedFluxPressureFvPatchScalarField() [1/5]
fixedFluxPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file fixedFluxPressureFvPatchScalarField.C.
Referenced by fixedFluxPressureFvPatchScalarField::clone(), and fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField().
fixedFluxPressureFvPatchScalarField() [2/5]
fixedFluxPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 46 of file fixedFluxPressureFvPatchScalarField.C.
References fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), dictionary::found(), scalarField(), and fvPatch::size().
fixedFluxPressureFvPatchScalarField() [3/5]
fixedFluxPressureFvPatchScalarField (const fixedFluxPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given fixedFluxPressureFvPatchScalarField onto.
a new patch
Definition at line 72 of file fixedFluxPressureFvPatchScalarField.C.
References fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), Foam::notNull(), and List< Type >::size().
fixedFluxPressureFvPatchScalarField() [4/5]
fixedFluxPressureFvPatchScalarField (const fixedFluxPressureFvPatchScalarField & wbppsf)
Construct as copy.
Definition at line 109 of file fixedFluxPressureFvPatchScalarField.C.
References fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField().
fixedFluxPressureFvPatchScalarField() [5/5]
fixedFluxPressureFvPatchScalarField (const fixedFluxPressureFvPatchScalarField & wbppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 119 of file fixedFluxPressureFvPatchScalarField.C.
References fixedFluxPressureFvPatchScalarField::updateCoeffs().
Member Function Documentation
TypeName()
TypeName ("fixedFluxPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented in fixedFluxExtrapolatedPressureFvPatchScalarField.
Definition at line 115 of file fixedFluxPressureFvPatchScalarField.H.
References fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in fixedFluxExtrapolatedPressureFvPatchScalarField.
Definition at line 132 of file fixedFluxPressureFvPatchScalarField.H.
References fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), Foam::setSnGrad(), fixedFluxPressureFvPatchScalarField::updateCoeffs(), and fixedFluxPressureFvPatchScalarField::write().
updateCoeffs() [1/2]
void updateCoeffs (const scalarField & snGradp) virtual
Update the patch pressure gradient field from the given snGradp.
Definition at line 132 of file fixedFluxPressureFvPatchScalarField.C.
updateCoeffs() [2/2]
void updateCoeffs () virtual
Update the patch pressure gradient field.
Definition at line 148 of file fixedFluxPressureFvPatchScalarField.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and timeIndex.
Referenced by fixedFluxPressureFvPatchScalarField::clone(), fixedFluxPressureFvPatchScalarField::fixedFluxPressureFvPatchScalarField(), and Foam::setSnGrad().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 165 of file fixedFluxPressureFvPatchScalarField.C.
References Foam::makePatchTypeField(), and write().
Referenced by fixedFluxPressureFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fixedFluxPressure/fixedFluxPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/fixedFluxPressure/fixedFluxPressureFvPatchScalarField.C