OpenFOAM: cylindricalInletVelocityFvPatchVectorField Class Reference
cylindricalInletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary Conditions
This boundary condition describes an inlet vector boundary condition in cylindrical co-ordinates given a central axis, central point, rpm, axial and radial velocity.
Public Member Functions
TypeName ("cylindricalInletVelocity")
Runtime type information.
cylindricalInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
cylindricalInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition describes an inlet vector boundary condition in cylindrical co-ordinates given a central axis, central point, rpm, axial and radial velocity.
Usage
Property Description Required Default value
axis axis of rotation yes
centre centre of rotation yes
axialVelocity axial velocity profile [m/s] yes
radialVelocity radial velocity profile [m/s] yes
rpm rotational speed (revolutions per minute) yes
Example of the boundary condition specification:
    <patchName>
    {
        type            cylindricalInletVelocity;
        axis            (0 0 1);
        centre          (0 0 0);
        axialVelocity   constant 30;
        radialVelocity  constant -10;
        rpm             constant 100;
    }
Note
The axialVelocity, radialVelocity and rpm entries are Function1 types, able to describe time varying functions. The example above gives the usage for supplying constant values.
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
cylindricalInletVelocityFvPatchVectorField.H
cylindricalInletVelocityFvPatchVectorField.C
Definition at line 115 of file cylindricalInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
cylindricalInletVelocityFvPatchVectorField() [1/5]
cylindricalInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file cylindricalInletVelocityFvPatchVectorField.C.
Referenced by cylindricalInletVelocityFvPatchVectorField::clone(), and cylindricalInletVelocityFvPatchVectorField::cylindricalInletVelocityFvPatchVectorField().
cylindricalInletVelocityFvPatchVectorField() [2/5]
cylindricalInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 71 of file cylindricalInletVelocityFvPatchVectorField.C.
References cylindricalInletVelocityFvPatchVectorField::cylindricalInletVelocityFvPatchVectorField().
cylindricalInletVelocityFvPatchVectorField() [3/5]
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
flowRateInletVelocityFvPatchVectorField onto a new patch
Definition at line 53 of file cylindricalInletVelocityFvPatchVectorField.C.
References cylindricalInletVelocityFvPatchVectorField::cylindricalInletVelocityFvPatchVectorField().
cylindricalInletVelocityFvPatchVectorField() [4/5]
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField & ptf)
Construct as copy.
Definition at line 88 of file cylindricalInletVelocityFvPatchVectorField.C.
References cylindricalInletVelocityFvPatchVectorField::cylindricalInletVelocityFvPatchVectorField().
cylindricalInletVelocityFvPatchVectorField() [5/5]
cylindricalInletVelocityFvPatchVectorField (const cylindricalInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 103 of file cylindricalInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("cylindricalInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 178 of file cylindricalInletVelocityFvPatchVectorField.H.
References cylindricalInletVelocityFvPatchVectorField::cylindricalInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 195 of file cylindricalInletVelocityFvPatchVectorField.H.
References cylindricalInletVelocityFvPatchVectorField::cylindricalInletVelocityFvPatchVectorField(), cylindricalInletVelocityFvPatchVectorField::updateCoeffs(), and cylindricalInletVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 119 of file cylindricalInletVelocityFvPatchVectorField.C.
References Foam::mag(), Foam::operator==(), Foam::constant::mathematical::pi(), and fvPatchField< Type >::updateCoeffs().
Referenced by cylindricalInletVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 147 of file cylindricalInletVelocityFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by cylindricalInletVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/cylindricalInletVelocity/cylindricalInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/cylindricalInletVelocity/cylindricalInletVelocityFvPatchVectorField.C