OpenFOAM: fixedPressureCompressibleDensityFvPatchScalarField Class Reference
fixedPressureCompressibleDensityFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary Conditions
This boundary condition calculates a (liquid) compressible density as a function of pressure and fluid properties:
Public Member Functions
TypeName ("fixedPressureCompressibleDensity")
Runtime type information.
fixedPressureCompressibleDensityFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fixedPressureCompressibleDensityFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition calculates a (liquid) compressible density as a function of pressure and fluid properties:
where
= density [kg/m3]
= saturation liquid density [kg/m3]
= liquid compressibility
= pressure [Pa]
= saturation pressure [Pa]
The variables rholSat, pSat and psil are retrieved from the thermodynamicProperties dictionary.
Usage
Property Description Required Default value
p pressure field name no p
Example of the boundary condition specification:
    <patchName>
    {
        type        fixedPressureCompressibleDensity;
        p           p;
        value       uniform 1;
    }
See also
Foam::fixedValueFvPatchField
Source files
fixedPressureCompressibleDensityFvPatchScalarField.H
fixedPressureCompressibleDensityFvPatchScalarField.C
Definition at line 118 of file fixedPressureCompressibleDensityFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedPressureCompressibleDensityFvPatchScalarField() [1/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
Referenced by fixedPressureCompressibleDensityFvPatchScalarField::clone(), and fixedPressureCompressibleDensityFvPatchScalarField::fixedPressureCompressibleDensityFvPatchScalarField().
fixedPressureCompressibleDensityFvPatchScalarField() [2/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 62 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
References fixedPressureCompressibleDensityFvPatchScalarField::fixedPressureCompressibleDensityFvPatchScalarField().
fixedPressureCompressibleDensityFvPatchScalarField() [3/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
fixedPressureCompressibleDensityFvPatchScalarField onto a new patch
Definition at line 48 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
References fixedPressureCompressibleDensityFvPatchScalarField::fixedPressureCompressibleDensityFvPatchScalarField().
fixedPressureCompressibleDensityFvPatchScalarField() [4/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField & ptf)
Construct as copy.
Definition at line 75 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
References fixedPressureCompressibleDensityFvPatchScalarField::fixedPressureCompressibleDensityFvPatchScalarField().
fixedPressureCompressibleDensityFvPatchScalarField() [5/5]
fixedPressureCompressibleDensityFvPatchScalarField (const fixedPressureCompressibleDensityFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 86 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("fixedPressureCompressibleDensity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 169 of file fixedPressureCompressibleDensityFvPatchScalarField.H.
References fixedPressureCompressibleDensityFvPatchScalarField::fixedPressureCompressibleDensityFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 186 of file fixedPressureCompressibleDensityFvPatchScalarField.H.
References fixedPressureCompressibleDensityFvPatchScalarField::fixedPressureCompressibleDensityFvPatchScalarField(), fixedPressureCompressibleDensityFvPatchScalarField::updateCoeffs(), and fixedPressureCompressibleDensityFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 98 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
References Foam::operator==(), fvPatchField< Type >::updateCoeffs(), and fixedPressureCompressibleDensityFvPatchScalarField::write().
Referenced by fixedPressureCompressibleDensityFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 126 of file fixedPressureCompressibleDensityFvPatchScalarField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by fixedPressureCompressibleDensityFvPatchScalarField::clone(), and fixedPressureCompressibleDensityFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fixedPressureCompressibleDensity/fixedPressureCompressibleDensityFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/fixedPressureCompressibleDensity/fixedPressureCompressibleDensityFvPatchScalarField.C