OpenFOAM: flowRateInletVelocityFvPatchVectorField Class Reference
flowRateInletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary Conditions
This boundary condition provides a velocity boundary condition, derived from the flux (volumetric or mass-based), whose direction is assumed to be normal to the patch.
Public Member Functions
TypeName ("flowRateInletVelocity")
Runtime type information.
flowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
flowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a velocity boundary condition, derived from the flux (volumetric or mass-based), whose direction is assumed to be normal to the patch.
For a mass-based flux:
the flow rate should be provided in kg/s
if rho is "none" the flow rate is in m3/s
otherwise rho should correspond to the name of the density field
if the density field cannot be found in the database, the user must specify the inlet density using the rhoInlet entry
For a volumetric-based flux:
the flow rate is in m3/s
Usage
Property Description Required Default value
massFlowRate mass flow rate [kg/s] no
volumetricFlowRate volumetric flow rate [m3/s] no
rhoInlet inlet density no
extrapolateProfile Extrapolate velocity profile no false
Example of the boundary condition specification for a volumetric flow rate:
    <patchName>
    {
        type                flowRateInletVelocity;
        volumetricFlowRate  0.2;
        extrapolateProfile  yes;
        value               uniform (0 0 0);
    }
Example of the boundary condition specification for a mass flow rate:
    <patchName>
    {
        type                flowRateInletVelocity;
        massFlowRate        0.2;
        extrapolateProfile  yes;
        rho                 rho;
        rhoInlet            1.0;
        value               uniform (0 0 0);
    }
The flowRate entry is a Function1 of time, see Foam::Function1Types.
Note
rhoInlet is required for the case of a mass flow rate, where the density field is not available at start-up
The value is positive into the domain (as an inlet)
May not work correctly for transonic inlets
Strange behaviour with potentialFoam since the U equation is not solved
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
flowRateInletVelocityFvPatchVectorField.H
flowRateInletVelocityFvPatchVectorField.C
Definition at line 135 of file flowRateInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
flowRateInletVelocityFvPatchVectorField() [1/5]
flowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file flowRateInletVelocityFvPatchVectorField.C.
Referenced by flowRateInletVelocityFvPatchVectorField::clone(), and flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField().
flowRateInletVelocityFvPatchVectorField() [2/5]
flowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 51 of file flowRateInletVelocityFvPatchVectorField.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField(), Foam::New(), List< Type >::size(), and vectorField().
flowRateInletVelocityFvPatchVectorField() [3/5]
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
flowRateInletVelocityFvPatchVectorField onto a new patch
Definition at line 102 of file flowRateInletVelocityFvPatchVectorField.C.
References flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField().
flowRateInletVelocityFvPatchVectorField() [4/5]
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField & ptf)
Construct as copy.
Definition at line 120 of file flowRateInletVelocityFvPatchVectorField.C.
References flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField().
flowRateInletVelocityFvPatchVectorField() [5/5]
flowRateInletVelocityFvPatchVectorField (const flowRateInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 135 of file flowRateInletVelocityFvPatchVectorField.C.
References Foam::gSum(), Foam::mag(), n, Foam::operator==(), and rho.
Member Function Documentation
TypeName()
TypeName ("flowRateInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 205 of file flowRateInletVelocityFvPatchVectorField.H.
References flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 222 of file flowRateInletVelocityFvPatchVectorField.H.
References flowRateInletVelocityFvPatchVectorField::flowRateInletVelocityFvPatchVectorField(), flowRateInletVelocityFvPatchVectorField::updateCoeffs(), and flowRateInletVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 188 of file flowRateInletVelocityFvPatchVectorField.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by flowRateInletVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 228 of file flowRateInletVelocityFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by flowRateInletVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/flowRateInletVelocity/flowRateInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/flowRateInletVelocity/flowRateInletVelocityFvPatchVectorField.C