OpenFOAM: interstitialInletVelocityFvPatchVectorField Class Reference
interstitialInletVelocityFvPatchVectorField Class Reference
Inlet velocity in which the actual interstitial velocity is calculated by dividing the specified inletVelocity field with the local phase-fraction.
Public Member Functions
TypeName ("interstitialInletVelocity")
Runtime type information.
interstitialInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
interstitialInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Inlet velocity in which the actual interstitial velocity is calculated by dividing the specified inletVelocity field with the local phase-fraction.
Example of the boundary condition specification:
inlet
{
    type              interstitialInletVelocity;
    inletVelocity     uniform (0 0.2 0);// Non-interstitial inlet velocity
    alpha             alpha.particles;  // Name of the phase-fraction field
    value             uniform (0 0 0);
}
Source files
interstitialInletVelocityFvPatchVectorField.H
interstitialInletVelocityFvPatchVectorField.C
Definition at line 59 of file interstitialInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
interstitialInletVelocityFvPatchVectorField() [1/5]
interstitialInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file interstitialInletVelocityFvPatchVectorField.C.
Referenced by interstitialInletVelocityFvPatchVectorField::clone(), and interstitialInletVelocityFvPatchVectorField::interstitialInletVelocityFvPatchVectorField().
interstitialInletVelocityFvPatchVectorField() [2/5]
interstitialInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 64 of file interstitialInletVelocityFvPatchVectorField.C.
References interstitialInletVelocityFvPatchVectorField::interstitialInletVelocityFvPatchVectorField().
interstitialInletVelocityFvPatchVectorField() [3/5]
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
interstitialInletVelocityFvPatchVectorField onto a new patch
Definition at line 49 of file interstitialInletVelocityFvPatchVectorField.C.
References interstitialInletVelocityFvPatchVectorField::interstitialInletVelocityFvPatchVectorField().
interstitialInletVelocityFvPatchVectorField() [4/5]
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField & ptf)
Construct as copy.
Definition at line 78 of file interstitialInletVelocityFvPatchVectorField.C.
References interstitialInletVelocityFvPatchVectorField::interstitialInletVelocityFvPatchVectorField().
interstitialInletVelocityFvPatchVectorField() [5/5]
interstitialInletVelocityFvPatchVectorField (const interstitialInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 90 of file interstitialInletVelocityFvPatchVectorField.C.
References interstitialInletVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("interstitialInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 113 of file interstitialInletVelocityFvPatchVectorField.H.
References interstitialInletVelocityFvPatchVectorField::interstitialInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 130 of file interstitialInletVelocityFvPatchVectorField.H.
References interstitialInletVelocityFvPatchVectorField::autoMap(), interstitialInletVelocityFvPatchVectorField::interstitialInletVelocityFvPatchVectorField(), interstitialInletVelocityFvPatchVectorField::rmap(), interstitialInletVelocityFvPatchVectorField::updateCoeffs(), and interstitialInletVelocityFvPatchVectorField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 104 of file interstitialInletVelocityFvPatchVectorField.C.
References interstitialInletVelocityFvPatchVectorField::rmap().
Referenced by interstitialInletVelocityFvPatchVectorField::clone(), and interstitialInletVelocityFvPatchVectorField::interstitialInletVelocityFvPatchVectorField().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 114 of file interstitialInletVelocityFvPatchVectorField.C.
References interstitialInletVelocityFvPatchVectorField::rmap().
Referenced by interstitialInletVelocityFvPatchVectorField::autoMap(), interstitialInletVelocityFvPatchVectorField::clone(), and interstitialInletVelocityFvPatchVectorField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 128 of file interstitialInletVelocityFvPatchVectorField.C.
References Foam::operator==().
Referenced by interstitialInletVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 143 of file interstitialInletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by interstitialInletVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/interstitialInletVelocity/interstitialInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/interstitialInletVelocity/interstitialInletVelocityFvPatchVectorField.C