OpenFOAM: movingWallVelocityFvPatchVectorField Class Reference
movingWallVelocityFvPatchVectorField Class Reference
Boundary Conditions » Wall boundary Conditions
This boundary condition provides a velocity condition for cases with moving walls. In addition, it should also be applied to 'moving' walls for moving reference frame (MRF) calculations.
Public Member Functions
TypeName ("movingWallVelocity")
Runtime type information.
movingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
movingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given movingWallVelocityFvPatchVectorField.
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a velocity condition for cases with moving walls. In addition, it should also be applied to 'moving' walls for moving reference frame (MRF) calculations.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            movingWallVelocity;
    value           uniform (0 0 0);    // Initial value
}
See also
Foam::fixedValueFvPatchVectorField Foam::MRFZone
Source files
movingWallVelocityFvPatchVectorField.H
movingWallVelocityFvPatchVectorField.C
Definition at line 67 of file movingWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
movingWallVelocityFvPatchVectorField() [1/5]
movingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file movingWallVelocityFvPatchVectorField.C.
Referenced by movingWallVelocityFvPatchVectorField::clone(), and movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField().
movingWallVelocityFvPatchVectorField() [2/5]
movingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 47 of file movingWallVelocityFvPatchVectorField.C.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField().
movingWallVelocityFvPatchVectorField() [3/5]
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given movingWallVelocityFvPatchVectorField.
onto a new patch
Definition at line 59 of file movingWallVelocityFvPatchVectorField.C.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField().
movingWallVelocityFvPatchVectorField() [4/5]
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField & mwvpvf)
Construct as copy.
Definition at line 72 of file movingWallVelocityFvPatchVectorField.C.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField().
movingWallVelocityFvPatchVectorField() [5/5]
movingWallVelocityFvPatchVectorField (const movingWallVelocityFvPatchVectorField & mwvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 82 of file movingWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("movingWallVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 112 of file movingWallVelocityFvPatchVectorField.H.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 129 of file movingWallVelocityFvPatchVectorField.H.
References movingWallVelocityFvPatchVectorField::movingWallVelocityFvPatchVectorField(), movingWallVelocityFvPatchVectorField::updateCoeffs(), and movingWallVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 93 of file movingWallVelocityFvPatchVectorField.C.
References TimeState::deltaTValue(), polyPatch::faceCentres(), forAll, fvPatch::magSf(), mesh, Foam::fvc::meshPhi(), polyMesh::moving(), n, fvPatch::nf(), polyMesh::oldPoints(), Field< vector >::operator=(), fvPatch::patch(), fvPatch::patchField(), fvMesh::time(), and U.
Referenced by movingWallVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 139 of file movingWallVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by movingWallVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/movingWallVelocity/movingWallVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/movingWallVelocity/movingWallVelocityFvPatchVectorField.C