OpenFOAM: noSlipFvPatchVectorField Class Reference
noSlipFvPatchVectorField Class Reference
Boundary Conditions » Wall boundary Conditions
This boundary condition fixes the velocity to zero at walls.
Public Member Functions
TypeName ("noSlip")
Runtime type information.
noSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
noSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
noSlipFvPatchVectorField (const noSlipFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given noSlipFvPatchVectorField.
noSlipFvPatchVectorField (const noSlipFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
noSlipFvPatchVectorField (const noSlipFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition fixes the velocity to zero at walls.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            noSlip;
}
See also
Foam::fixedValueFvPatchVectorField
Source files
noSlipFvPatchVectorField.H
noSlipFvPatchVectorField.C
Definition at line 63 of file noSlipFvPatchVectorField.H.
Constructor & Destructor Documentation
noSlipFvPatchVectorField() [1/5]
noSlipFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 32 of file noSlipFvPatchVectorField.C.
Referenced by noSlipFvPatchVectorField::clone(), and noSlipFvPatchVectorField::noSlipFvPatchVectorField().
noSlipFvPatchVectorField() [2/5]
noSlipFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 42 of file noSlipFvPatchVectorField.C.
References noSlipFvPatchVectorField::noSlipFvPatchVectorField().
noSlipFvPatchVectorField() [3/5]
noSlipFvPatchVectorField (const noSlipFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given noSlipFvPatchVectorField.
onto a new patch
Definition at line 53 of file noSlipFvPatchVectorField.C.
References noSlipFvPatchVectorField::noSlipFvPatchVectorField().
noSlipFvPatchVectorField() [4/5]
noSlipFvPatchVectorField (const noSlipFvPatchVectorField & mwvpvf)
Construct as copy.
Definition at line 65 of file noSlipFvPatchVectorField.C.
References noSlipFvPatchVectorField::noSlipFvPatchVectorField().
noSlipFvPatchVectorField() [5/5]
noSlipFvPatchVectorField (const noSlipFvPatchVectorField & mwvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 74 of file noSlipFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("noSlip")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 108 of file noSlipFvPatchVectorField.H.
References noSlipFvPatchVectorField::noSlipFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 125 of file noSlipFvPatchVectorField.H.
References noSlipFvPatchVectorField::noSlipFvPatchVectorField(), and noSlipFvPatchVectorField::write().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 85 of file noSlipFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by noSlipFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/noSlip/noSlipFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/noSlip/noSlipFvPatchVectorField.C