OpenFOAM: freestreamPressureFvPatchScalarField Class Reference
freestreamPressureFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This boundary condition provides a free-stream condition for pressure. It is a zero-gradient condition that constrains the flux across the patch based on the free-stream velocity.
Public Member Functions
TypeName ("freestreamPressure")
Runtime type information.
freestreamPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
freestreamPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given freestreamPressureFvPatchScalarField onto.
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a free-stream condition for pressure. It is a zero-gradient condition that constrains the flux across the patch based on the free-stream velocity.
Usage
Property Description Required Default value
U velocity field name no U
phi flux field name no phi
rho density field name no none
Example of the boundary condition specification:
    <patchName>
    {
        type            freestreamPressure;
    }
Note
This condition is designed to operate with a freestream velocity condition
See also
Foam::zeroGradientFvPatchField Foam::freestreamFvPatchField
Source files
freestreamPressureFvPatchScalarField.H
freestreamPressureFvPatchScalarField.C
Definition at line 97 of file freestreamPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
freestreamPressureFvPatchScalarField() [1/5]
freestreamPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file freestreamPressureFvPatchScalarField.C.
Referenced by freestreamPressureFvPatchScalarField::clone(), and freestreamPressureFvPatchScalarField::freestreamPressureFvPatchScalarField().
freestreamPressureFvPatchScalarField() [2/5]
freestreamPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 51 of file freestreamPressureFvPatchScalarField.C.
References freestreamPressureFvPatchScalarField::freestreamPressureFvPatchScalarField().
freestreamPressureFvPatchScalarField() [3/5]
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given freestreamPressureFvPatchScalarField onto.
a new patch
Definition at line 66 of file freestreamPressureFvPatchScalarField.C.
References freestreamPressureFvPatchScalarField::freestreamPressureFvPatchScalarField().
freestreamPressureFvPatchScalarField() [4/5]
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField & wbppsf)
Construct as copy.
Definition at line 82 of file freestreamPressureFvPatchScalarField.C.
References freestreamPressureFvPatchScalarField::freestreamPressureFvPatchScalarField().
freestreamPressureFvPatchScalarField() [5/5]
freestreamPressureFvPatchScalarField (const freestreamPressureFvPatchScalarField & wbppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 95 of file freestreamPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("freestreamPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 154 of file freestreamPressureFvPatchScalarField.H.
References freestreamPressureFvPatchScalarField::freestreamPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 171 of file freestreamPressureFvPatchScalarField.H.
References freestreamPressureFvPatchScalarField::freestreamPressureFvPatchScalarField(), freestreamPressureFvPatchScalarField::updateCoeffs(), and freestreamPressureFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 109 of file freestreamPressureFvPatchScalarField.C.
References Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and phi.
Referenced by freestreamPressureFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 156 of file freestreamPressureFvPatchScalarField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by freestreamPressureFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/freestreamPressure/freestreamPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/freestreamPressure/freestreamPressureFvPatchScalarField.C