OpenFOAM: fixedNormalInletOutletVelocityFvPatchVectorField Class Reference
fixedNormalInletOutletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Outlet boundary Conditions
This velocity inlet/outlet boundary condition combines a fixed normal component obtained from the "normalVelocity" patchField supplied with a fixed or zero-gradiented tangential component depending on the direction of the flow and the setting of "fixTangentialInflow":
Public Member Functions
TypeName ("fixedNormalInletOutletVelocity")
Runtime type information.
fixedNormalInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
fixedNormalInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: this patch field is altered by assignment.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
Switch fixTangentialInflow () const
const fvPatchVectorField & normalVelocity () const
Return the BC which provides the normal component of velocity.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition combines a fixed normal component obtained from the "normalVelocity" patchField supplied with a fixed or zero-gradiented tangential component depending on the direction of the flow and the setting of "fixTangentialInflow":
- Outflow: apply zero-gradient condition to tangential components
Inflow:
fixTangentialInflow is true apply value provided by the normalVelocity patchField to the tangential components
fixTangentialInflow is false apply zero-gradient condition to tangential components.
Usage
Property Description Required Default value
phi flux field name no phi
fixTangentialInflow If true fix the tangential component for inflow yes
normalVelocity patchField providing the normal velocity field yes
Example of the boundary condition specification:
    <patchName>
    {
        type            fixedNormalInletOutletVelocity;
        fixTangentialInflow false;
        normalVelocity
        {
            type            uniformFixedValue;
            uniformValue    sine;
            uniformValueCoeffs
            {
                frequency 1;
                amplitude table
                (
                    (0  0)
                    (2  0.088)
                    (8  0.088)
                );
                scale     (0 1 0);
                level     (0 0 0);
            }
        }
        value           uniform (0 0 0);
    }
Source files
fixedNormalInletOutletVelocityFvPatchVectorField.H
fixedNormalInletOutletVelocityFvPatchVectorField.C
Definition at line 121 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
fixedNormalInletOutletVelocityFvPatchVectorField() [1/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::Zero.
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::clone(), and fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField().
fixedNormalInletOutletVelocityFvPatchVectorField() [2/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 57 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField(), fvPatch::size(), vectorField(), and Foam::Zero.
fixedNormalInletOutletVelocityFvPatchVectorField() [3/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
fixedNormalInletOutletVelocityFvPatchVectorField onto a new patch
Definition at line 80 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField().
fixedNormalInletOutletVelocityFvPatchVectorField() [4/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField & pivpvf)
Construct as copy.
Definition at line 99 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField().
fixedNormalInletOutletVelocityFvPatchVectorField() [5/5]
fixedNormalInletOutletVelocityFvPatchVectorField (const fixedNormalInletOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 112 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References fixedNormalInletOutletVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("fixedNormalInletOutletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 177 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
References fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 194 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
References fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField().
assignable()
virtual bool assignable () const inline virtual
Return true: this patch field is altered by assignment.
Definition at line 210 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word& phiName () const inline
Return the name of phi.
Definition at line 219 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
phiName() [2/2]
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 225 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
fixTangentialInflow()
Switch fixTangentialInflow () const inline
Definition at line 230 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
normalVelocity()
const fvPatchVectorField& normalVelocity () const inline
Return the BC which provides the normal component of velocity.
Definition at line 236 of file fixedNormalInletOutletVelocityFvPatchVectorField.H.
References fixedNormalInletOutletVelocityFvPatchVectorField::autoMap(), fixedNormalInletOutletVelocityFvPatchVectorField::operator=(), fixedNormalInletOutletVelocityFvPatchVectorField::rmap(), fixedNormalInletOutletVelocityFvPatchVectorField::updateCoeffs(), and fixedNormalInletOutletVelocityFvPatchVectorField::write().
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::rmap(), and fixedNormalInletOutletVelocityFvPatchVectorField::updateCoeffs().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 127 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References fixedNormalInletOutletVelocityFvPatchVectorField::rmap().
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::fixedNormalInletOutletVelocityFvPatchVectorField(), and fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 137 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity(), and fixedNormalInletOutletVelocityFvPatchVectorField::rmap().
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::autoMap(), fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity(), and fixedNormalInletOutletVelocityFvPatchVectorField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 151 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::I, Foam::neg(), fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity(), Foam::sqr(), and fixedNormalInletOutletVelocityFvPatchVectorField::write().
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 177 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::nl, and fvPatchField< Type >::write().
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity(), and fixedNormalInletOutletVelocityFvPatchVectorField::updateCoeffs().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 197 of file fixedNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::I, Foam::makePatchTypeField(), fvPatchField< Type >::operator=(), and Foam::transform().
Referenced by fixedNormalInletOutletVelocityFvPatchVectorField::normalVelocity().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/fixedNormalInletOutletVelocity/fixedNormalInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/fixedNormalInletOutletVelocity/fixedNormalInletOutletVelocityFvPatchVectorField.C