OpenFOAM: inletOutletTotalTemperatureFvPatchScalarField Class Reference
inletOutletTotalTemperatureFvPatchScalarField Class Reference
Boundary Conditions » Outlet boundary Conditions
This boundary condition provides an outflow condition for total temperature for use with supersonic cases, where a user-specified value is applied in the case of reverse flow.
Public Member Functions
TypeName ("inletOutletTotalTemperature")
Runtime type information.
inletOutletTotalTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
inletOutletTotalTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & T0 () const
Return the total pressure.
scalarField & T0 ()
Return reference to the total pressure to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides an outflow condition for total temperature for use with supersonic cases, where a user-specified value is applied in the case of reverse flow.
Usage
Property Description Required Default value
U velocity field name no U
phi flux field name no phi
psi compressibility field name no psi
gamma heat capacity ration (Cp/Cv) yes
inletValue reverse flow (inlet) value yes
T0 static temperature [K] yes
Example of the boundary condition specification:
    <patchName>
    {
        type            inletOutletTotalTemperature;
        U               U;
        phi             phi;
        psi             psi;
        gamma           gamma;
        inletValue      uniform 0;
        T0              uniform 0;
        value           uniform 0;
    }
See also
Foam::inletOutletFvPatchField
Source files
inletOutletTotalTemperatureFvPatchScalarField.H
inletOutletTotalTemperatureFvPatchScalarField.C
Definition at line 117 of file inletOutletTotalTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
inletOutletTotalTemperatureFvPatchScalarField() [1/5]
inletOutletTotalTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References Foam::Zero.
Referenced by inletOutletTotalTemperatureFvPatchScalarField::clone(), and inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField().
inletOutletTotalTemperatureFvPatchScalarField() [2/5]
inletOutletTotalTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 72 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References dictionary::found(), inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField(), dictionary::lookupOrDefault(), scalarField(), fvPatch::size(), and Foam::Zero.
inletOutletTotalTemperatureFvPatchScalarField() [3/5]
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
inletOutletTotalTemperatureFvPatchScalarField onto a new patch
Definition at line 55 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField().
inletOutletTotalTemperatureFvPatchScalarField() [4/5]
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 106 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField().
inletOutletTotalTemperatureFvPatchScalarField() [5/5]
inletOutletTotalTemperatureFvPatchScalarField (const inletOutletTotalTemperatureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 120 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References inletOutletTotalTemperatureFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("inletOutletTotalTemperature")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 176 of file inletOutletTotalTemperatureFvPatchScalarField.H.
References inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 193 of file inletOutletTotalTemperatureFvPatchScalarField.H.
References inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField().
T0() [1/2]
const scalarField& T0 () const inline
Return the total pressure.
Definition at line 209 of file inletOutletTotalTemperatureFvPatchScalarField.H.
T0() [2/2]
scalarField& T0 () inline
Return reference to the total pressure to allow adjustment.
Definition at line 215 of file inletOutletTotalTemperatureFvPatchScalarField.H.
References inletOutletTotalTemperatureFvPatchScalarField::autoMap(), inletOutletTotalTemperatureFvPatchScalarField::rmap(), inletOutletTotalTemperatureFvPatchScalarField::updateCoeffs(), and inletOutletTotalTemperatureFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 136 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References inletOutletTotalTemperatureFvPatchScalarField::rmap().
Referenced by inletOutletTotalTemperatureFvPatchScalarField::inletOutletTotalTemperatureFvPatchScalarField(), and inletOutletTotalTemperatureFvPatchScalarField::T0().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 146 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References inletOutletTotalTemperatureFvPatchScalarField::rmap().
Referenced by inletOutletTotalTemperatureFvPatchScalarField::autoMap(), inletOutletTotalTemperatureFvPatchScalarField::rmap(), and inletOutletTotalTemperatureFvPatchScalarField::T0().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 160 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References Foam::magSqr(), and Foam::pos().
Referenced by inletOutletTotalTemperatureFvPatchScalarField::T0().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 186 of file inletOutletTotalTemperatureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by inletOutletTotalTemperatureFvPatchScalarField::T0().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/inletOutletTotalTemperature/inletOutletTotalTemperatureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/inletOutletTotalTemperature/inletOutletTotalTemperatureFvPatchScalarField.C