OpenFOAM: swirlFlowRateInletVelocityFvPatchVectorField Class Reference
swirlFlowRateInletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary Conditions
This boundary condition provides a volumetric- OR mass-flow normal vector boundary condition by its magnitude as an integral over its area with a swirl component determined by the angular speed, given in revolutions per minute (RPM)
Public Member Functions
TypeName ("swirlFlowRateInletVelocity")
Runtime type information.
swirlFlowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
swirlFlowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
swirlFlowRateInletVelocityFvPatchVectorField (const swirlFlowRateInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
swirlFlowRateInletVelocityFvPatchVectorField (const swirlFlowRateInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
swirlFlowRateInletVelocityFvPatchVectorField (const swirlFlowRateInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a volumetric- OR mass-flow normal vector boundary condition by its magnitude as an integral over its area with a swirl component determined by the angular speed, given in revolutions per minute (RPM)
The basis of the patch (volumetric or mass) is determined by the dimensions of the flux, phi. The current density is used to correct the velocity when applying the mass basis.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
flowRate flow rate profile yes
rpm rotational speed profile yes
Example of the boundary condition specification:
    <patchName>
    {
        type            swirlFlowRateInletVelocity;
        flowRate        constant 0.2;
        rpm             constant 100;
    }
Note
the flowRate and rpm entries are Function1 types, able to describe time varying functions. The example above gives the usage for supplying constant values.
the value is positive into the domain
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
swirlFlowRateInletVelocityFvPatchVectorField.H
swirlFlowRateInletVelocityFvPatchVectorField.C
Definition at line 112 of file swirlFlowRateInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
swirlFlowRateInletVelocityFvPatchVectorField() [1/5]
swirlFlowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file swirlFlowRateInletVelocityFvPatchVectorField.C.
Referenced by swirlFlowRateInletVelocityFvPatchVectorField::clone(), and swirlFlowRateInletVelocityFvPatchVectorField::swirlFlowRateInletVelocityFvPatchVectorField().
swirlFlowRateInletVelocityFvPatchVectorField() [2/5]
swirlFlowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 69 of file swirlFlowRateInletVelocityFvPatchVectorField.C.
References swirlFlowRateInletVelocityFvPatchVectorField::swirlFlowRateInletVelocityFvPatchVectorField().
swirlFlowRateInletVelocityFvPatchVectorField() [3/5]
swirlFlowRateInletVelocityFvPatchVectorField (const swirlFlowRateInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
flowRateInletVelocityFvPatchVectorField onto a new patch
Definition at line 52 of file swirlFlowRateInletVelocityFvPatchVectorField.C.
References swirlFlowRateInletVelocityFvPatchVectorField::swirlFlowRateInletVelocityFvPatchVectorField().
swirlFlowRateInletVelocityFvPatchVectorField() [4/5]
swirlFlowRateInletVelocityFvPatchVectorField (const swirlFlowRateInletVelocityFvPatchVectorField & ptf)
Construct as copy.
Definition at line 85 of file swirlFlowRateInletVelocityFvPatchVectorField.C.
References swirlFlowRateInletVelocityFvPatchVectorField::swirlFlowRateInletVelocityFvPatchVectorField().
swirlFlowRateInletVelocityFvPatchVectorField() [5/5]
swirlFlowRateInletVelocityFvPatchVectorField (const swirlFlowRateInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 99 of file swirlFlowRateInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("swirlFlowRateInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 172 of file swirlFlowRateInletVelocityFvPatchVectorField.H.
References swirlFlowRateInletVelocityFvPatchVectorField::swirlFlowRateInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 189 of file swirlFlowRateInletVelocityFvPatchVectorField.H.
References swirlFlowRateInletVelocityFvPatchVectorField::swirlFlowRateInletVelocityFvPatchVectorField(), swirlFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), and swirlFlowRateInletVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 114 of file swirlFlowRateInletVelocityFvPatchVectorField.C.
References Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gSum(), n, Foam::nl, Foam::operator==(), phi, Foam::constant::mathematical::pi(), fvPatchField< Type >::updateCoeffs(), and swirlFlowRateInletVelocityFvPatchVectorField::write().
Referenced by swirlFlowRateInletVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 171 of file swirlFlowRateInletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by swirlFlowRateInletVelocityFvPatchVectorField::clone(), and swirlFlowRateInletVelocityFvPatchVectorField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/swirlFlowRateInletVelocity/swirlFlowRateInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/swirlFlowRateInletVelocity/swirlFlowRateInletVelocityFvPatchVectorField.C