OpenFOAM: outletPhaseMeanVelocityFvPatchVectorField Class Reference
outletPhaseMeanVelocityFvPatchVectorField Class Reference
Boundary Conditions » Outlet boundary Conditions
This boundary condition adjusts the velocity for the given phase to achieve the specified mean thus causing the phase-fraction to adjust according to the mass flow rate.
Public Member Functions
TypeName ("outletPhaseMeanVelocity")
Runtime type information.
outletPhaseMeanVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
outletPhaseMeanVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
scalar Umean () const
Return the flux.
scalar & Umean ()
Return reference to the flux to allow adjustment.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition adjusts the velocity for the given phase to achieve the specified mean thus causing the phase-fraction to adjust according to the mass flow rate.
Typical usage is as the outlet condition for a towing-tank ship simulation to maintain the outlet water level at the level as the inlet.
Usage
Property Description Required Default value
Umean mean velocity normal to the boundary [m/s] yes
alpha phase-fraction field yes
Example of the boundary condition specification:
    <patchName>
    {
        type            outletPhaseMeanVelocity;
        Umean           1.2;
        alpha           alpha.water;
        value           uniform (1.2 0 0);
    }
See also
Foam::mixedFvPatchField Foam::variableHeightFlowRateInletVelocityFvPatchVectorField
Source files
outletPhaseMeanVelocityFvPatchVectorField.H
outletPhaseMeanVelocityFvPatchVectorField.C
Definition at line 92 of file outletPhaseMeanVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
outletPhaseMeanVelocityFvPatchVectorField() [1/5]
outletPhaseMeanVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References Foam::Zero.
Referenced by outletPhaseMeanVelocityFvPatchVectorField::clone(), and outletPhaseMeanVelocityFvPatchVectorField::outletPhaseMeanVelocityFvPatchVectorField().
outletPhaseMeanVelocityFvPatchVectorField() [2/5]
outletPhaseMeanVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 68 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References dictionary::found(), outletPhaseMeanVelocityFvPatchVectorField::outletPhaseMeanVelocityFvPatchVectorField(), List< Type >::size(), vectorField(), and Foam::Zero.
outletPhaseMeanVelocityFvPatchVectorField() [3/5]
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
outletPhaseMeanVelocityFvPatchVectorField onto a new patch
Definition at line 53 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References outletPhaseMeanVelocityFvPatchVectorField::outletPhaseMeanVelocityFvPatchVectorField().
outletPhaseMeanVelocityFvPatchVectorField() [4/5]
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField & ptf)
Construct as copy.
Definition at line 98 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References outletPhaseMeanVelocityFvPatchVectorField::outletPhaseMeanVelocityFvPatchVectorField().
outletPhaseMeanVelocityFvPatchVectorField() [5/5]
outletPhaseMeanVelocityFvPatchVectorField (const outletPhaseMeanVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 110 of file outletPhaseMeanVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("outletPhaseMeanVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 146 of file outletPhaseMeanVelocityFvPatchVectorField.H.
References outletPhaseMeanVelocityFvPatchVectorField::outletPhaseMeanVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 163 of file outletPhaseMeanVelocityFvPatchVectorField.H.
References outletPhaseMeanVelocityFvPatchVectorField::outletPhaseMeanVelocityFvPatchVectorField().
Umean() [1/2]
scalar Umean () const inline
Return the flux.
Definition at line 183 of file outletPhaseMeanVelocityFvPatchVectorField.H.
Umean() [2/2]
scalar& Umean () inline
Return reference to the flux to allow adjustment.
Definition at line 189 of file outletPhaseMeanVelocityFvPatchVectorField.H.
References outletPhaseMeanVelocityFvPatchVectorField::updateCoeffs(), and outletPhaseMeanVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 123 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References Foam::gSum(), Foam::max(), Foam::min(), fvPatchField< Type >::updateCoeffs(), outletPhaseMeanVelocityFvPatchVectorField::write(), and Foam::Zero.
Referenced by outletPhaseMeanVelocityFvPatchVectorField::Umean().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 162 of file outletPhaseMeanVelocityFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by outletPhaseMeanVelocityFvPatchVectorField::Umean(), and outletPhaseMeanVelocityFvPatchVectorField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/outletPhaseMeanVelocity/outletPhaseMeanVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/outletPhaseMeanVelocity/outletPhaseMeanVelocityFvPatchVectorField.C