OpenFOAM: pressureInletVelocityFvPatchVectorField Class Reference
pressureInletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary Conditions
This velocity inlet boundary condition is applied to patches where the pressure is specified. The inflow velocity is obtained from the flux with a direction normal to the patch faces.
Public Member Functions
TypeName ("pressureInletVelocity")
Runtime type information.
pressureInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
pressureInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given pressureInletVelocityFvPatchVectorField.
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: this patch field is altered by assignment.
const word & rhoName () const
Return the name of rho.
word & rhoName ()
Return reference to the name of rho to allow adjustment.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet boundary condition is applied to patches where the pressure is specified. The inflow velocity is obtained from the flux with a direction normal to the patch faces.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            pressureInletVelocity;
    phi             phi;
    rho             rho;
    value           uniform 0;
}
Note
If reverse flow is possible or expected use the pressureInletOutletVelocityFvPatchVectorField condition instead.
See also
Foam::fixedValueFvPatchField Foam::pressureInletOutletVelocityFvPatchVectorField
Source files
pressureInletVelocityFvPatchVectorField.H
pressureInletVelocityFvPatchVectorField.C
Definition at line 74 of file pressureInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureInletVelocityFvPatchVectorField() [1/5]
pressureInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file pressureInletVelocityFvPatchVectorField.C.
Referenced by pressureInletVelocityFvPatchVectorField::clone(), and pressureInletVelocityFvPatchVectorField::pressureInletVelocityFvPatchVectorField().
pressureInletVelocityFvPatchVectorField() [2/5]
pressureInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 63 of file pressureInletVelocityFvPatchVectorField.C.
References pressureInletVelocityFvPatchVectorField::pressureInletVelocityFvPatchVectorField().
pressureInletVelocityFvPatchVectorField() [3/5]
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given pressureInletVelocityFvPatchVectorField.
onto a new patch
Definition at line 48 of file pressureInletVelocityFvPatchVectorField.C.
References pressureInletVelocityFvPatchVectorField::pressureInletVelocityFvPatchVectorField().
pressureInletVelocityFvPatchVectorField() [4/5]
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField & pivpvf)
Construct as copy.
Definition at line 77 of file pressureInletVelocityFvPatchVectorField.C.
References pressureInletVelocityFvPatchVectorField::pressureInletVelocityFvPatchVectorField().
pressureInletVelocityFvPatchVectorField() [5/5]
pressureInletVelocityFvPatchVectorField (const pressureInletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 89 of file pressureInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Reimplemented in pressureInletUniformVelocityFvPatchVectorField.
Definition at line 127 of file pressureInletVelocityFvPatchVectorField.H.
References pressureInletVelocityFvPatchVectorField::pressureInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in pressureInletUniformVelocityFvPatchVectorField.
Definition at line 144 of file pressureInletVelocityFvPatchVectorField.H.
References pressureInletVelocityFvPatchVectorField::pressureInletVelocityFvPatchVectorField().
assignable()
virtual bool assignable () const inline virtual
Return true: this patch field is altered by assignment.
Reimplemented in pressureInletUniformVelocityFvPatchVectorField.
Definition at line 160 of file pressureInletVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word& rhoName () const inline
Return the name of rho.
Definition at line 169 of file pressureInletVelocityFvPatchVectorField.H.
rhoName() [2/2]
word& rhoName () inline
Return reference to the name of rho to allow adjustment.
Definition at line 175 of file pressureInletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word& phiName () const inline
Return the name of phi.
Definition at line 181 of file pressureInletVelocityFvPatchVectorField.H.
phiName() [2/2]
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 187 of file pressureInletVelocityFvPatchVectorField.H.
References pressureInletVelocityFvPatchVectorField::operator=(), pressureInletVelocityFvPatchVectorField::updateCoeffs(), and pressureInletVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented in pressureInletUniformVelocityFvPatchVectorField.
Definition at line 102 of file pressureInletVelocityFvPatchVectorField.C.
References Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, Foam::operator==(), and phi.
Referenced by pressureInletVelocityFvPatchVectorField::phiName(), and pressureInletUniformVelocityFvPatchVectorField::updateCoeffs().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 143 of file pressureInletVelocityFvPatchVectorField.C.
References fvPatchField< Type >::write().
Referenced by pressureInletVelocityFvPatchVectorField::phiName().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Reimplemented in pressureInletUniformVelocityFvPatchVectorField.
Definition at line 155 of file pressureInletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::operator=().
Referenced by pressureInletVelocityFvPatchVectorField::phiName().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureInletVelocity/pressureInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureInletVelocity/pressureInletVelocityFvPatchVectorField.C