OpenFOAM: pressureInletOutletVelocityFvPatchVectorField Class Reference
pressureInletOutletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Outlet boundary Conditions
This velocity inlet/outlet boundary condition is applied to pressure boundaries where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the patch-face normal component of the internal-cell value.
Public Member Functions
TypeName ("pressureInletOutletVelocity")
Runtime type information.
pressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
pressureInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: this patch field is altered by assignment.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
const vectorField & tangentialVelocity () const
Return the tangential velocity.
void setTangentialVelocity (const vectorField &tangentialVelocity)
Reset the tangential velocity.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition is applied to pressure boundaries where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the patch-face normal component of the internal-cell value.
The tangential patch velocity can be optionally specified.
Usage
Property Description Required Default value
phi flux field name no phi
tangentialVelocity tangential velocity field no
Example of the boundary condition specification:
    <patchName>
    {
        type            pressureInletOutletVelocity;
        phi             phi;
        tangentialVelocity uniform (0 0 0);
        value           uniform 0;
    }
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux in the patch-normal direction
Source files
pressureInletOutletVelocityFvPatchVectorField.H
pressureInletOutletVelocityFvPatchVectorField.C
Definition at line 96 of file pressureInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureInletOutletVelocityFvPatchVectorField() [1/5]
pressureInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file pressureInletOutletVelocityFvPatchVectorField.C.
References Foam::Zero.
Referenced by pressureInletOutletVelocityFvPatchVectorField::clone(), and pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField().
pressureInletOutletVelocityFvPatchVectorField() [2/5]
pressureInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 71 of file pressureInletOutletVelocityFvPatchVectorField.C.
References dictionary::found(), pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), fvPatch::size(), vectorField(), and Foam::Zero.
pressureInletOutletVelocityFvPatchVectorField() [3/5]
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
pressureInletOutletVelocityFvPatchVectorField onto a new patch
Definition at line 52 of file pressureInletOutletVelocityFvPatchVectorField.C.
References pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), and List< T >::size().
pressureInletOutletVelocityFvPatchVectorField() [4/5]
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField & pivpvf)
Construct as copy.
Definition at line 101 of file pressureInletOutletVelocityFvPatchVectorField.C.
References pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField().
pressureInletOutletVelocityFvPatchVectorField() [5/5]
pressureInletOutletVelocityFvPatchVectorField (const pressureInletOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 113 of file pressureInletOutletVelocityFvPatchVectorField.C.
References pressureInletOutletVelocityFvPatchVectorField::setTangentialVelocity().
Member Function Documentation
TypeName()
TypeName ("pressureInletOutletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Reimplemented in rotatingPressureInletOutletVelocityFvPatchVectorField.
Definition at line 149 of file pressureInletOutletVelocityFvPatchVectorField.H.
References pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in rotatingPressureInletOutletVelocityFvPatchVectorField.
Definition at line 166 of file pressureInletOutletVelocityFvPatchVectorField.H.
References pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField().
assignable()
virtual bool assignable () const inline virtual
Return true: this patch field is altered by assignment.
Definition at line 182 of file pressureInletOutletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word& phiName () const inline
Return the name of phi.
Definition at line 191 of file pressureInletOutletVelocityFvPatchVectorField.H.
Referenced by rotatingPressureInletOutletVelocityFvPatchVectorField::write().
phiName() [2/2]
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 197 of file pressureInletOutletVelocityFvPatchVectorField.H.
tangentialVelocity()
const vectorField& tangentialVelocity () const inline
Return the tangential velocity.
Definition at line 203 of file pressureInletOutletVelocityFvPatchVectorField.H.
References pressureInletOutletVelocityFvPatchVectorField::autoMap(), pressureInletOutletVelocityFvPatchVectorField::operator=(), pressureInletOutletVelocityFvPatchVectorField::rmap(), pressureInletOutletVelocityFvPatchVectorField::setTangentialVelocity(), pressureInletOutletVelocityFvPatchVectorField::updateCoeffs(), and pressureInletOutletVelocityFvPatchVectorField::write().
Referenced by pressureInletOutletVelocityFvPatchVectorField::setTangentialVelocity().
setTangentialVelocity()
void setTangentialVelocity (const vectorField & tangentialVelocity)
Reset the tangential velocity.
Definition at line 127 of file pressureInletOutletVelocityFvPatchVectorField.C.
References pressureInletOutletVelocityFvPatchVectorField::autoMap(), n, and pressureInletOutletVelocityFvPatchVectorField::tangentialVelocity().
Referenced by pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), and pressureInletOutletVelocityFvPatchVectorField::tangentialVelocity().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 136 of file pressureInletOutletVelocityFvPatchVectorField.C.
References Field< Type >::autoMap(), pressureInletOutletVelocityFvPatchVectorField::rmap(), and List< T >::size().
Referenced by pressureInletOutletVelocityFvPatchVectorField::setTangentialVelocity(), and pressureInletOutletVelocityFvPatchVectorField::tangentialVelocity().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 149 of file pressureInletOutletVelocityFvPatchVectorField.C.
References Field< Type >::rmap(), and List< T >::size().
Referenced by pressureInletOutletVelocityFvPatchVectorField::autoMap(), and pressureInletOutletVelocityFvPatchVectorField::tangentialVelocity().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 166 of file pressureInletOutletVelocityFvPatchVectorField.C.
References Foam::I, Foam::neg(), Foam::sqr(), and pressureInletOutletVelocityFvPatchVectorField::write().
Referenced by pressureInletOutletVelocityFvPatchVectorField::tangentialVelocity().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in rotatingPressureInletOutletVelocityFvPatchVectorField.
Definition at line 184 of file pressureInletOutletVelocityFvPatchVectorField.C.
References List< T >::size(), fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by pressureInletOutletVelocityFvPatchVectorField::tangentialVelocity(), and pressureInletOutletVelocityFvPatchVectorField::updateCoeffs().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 202 of file pressureInletOutletVelocityFvPatchVectorField.C.
References Foam::I, Foam::makePatchTypeField(), fvPatchField< Type >::operator=(), and Foam::transform().
Referenced by pressureInletOutletVelocityFvPatchVectorField::tangentialVelocity().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureInletOutletVelocity/pressureInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureInletOutletVelocity/pressureInletOutletVelocityFvPatchVectorField.C