OpenFOAM: pressureInletOutletParSlipVelocityFvPatchVectorField Class Reference
pressureInletOutletParSlipVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This velocity inlet/outlet boundary condition for pressure boundary where the pressure is specified. A zero-gradient is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with the specified inlet direction.
Public Member Functions
TypeName ("pressureInletOutletParSlipVelocity")
Runtime type information.
pressureInletOutletParSlipVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
pressureInletOutletParSlipVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: this patch field is altered by assignment.
const word & rhoName () const
Return the name of rho.
word & rhoName ()
Return reference to the name of rho to allow adjustment.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition for pressure boundary where the pressure is specified. A zero-gradient is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with the specified inlet direction.
A slip condition is applied tangential to the patch.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
Example of the boundary condition specification:
    <patchName>
    {
        type            pressureInletOutletParSlipVelocity;
        value           uniform 0;
    }
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux with specified direction
See also
Foam::mixedFvPatchVectorField Foam::pressureDirectedInletOutletVelocityFvPatchVectorField
Source files
pressureInletOutletParSlipVelocityFvPatchVectorField.H
pressureInletOutletParSlipVelocityFvPatchVectorField.C
Definition at line 98 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureInletOutletParSlipVelocityFvPatchVectorField() [1/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References Foam::Zero.
Referenced by pressureInletOutletParSlipVelocityFvPatchVectorField::clone(), and pressureInletOutletParSlipVelocityFvPatchVectorField::pressureInletOutletParSlipVelocityFvPatchVectorField().
pressureInletOutletParSlipVelocityFvPatchVectorField() [2/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
pressureInletOutletParSlipVelocityFvPatchVectorField onto a new patch
Definition at line 54 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References pressureInletOutletParSlipVelocityFvPatchVectorField::pressureInletOutletParSlipVelocityFvPatchVectorField().
pressureInletOutletParSlipVelocityFvPatchVectorField() [3/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 69 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References pressureInletOutletParSlipVelocityFvPatchVectorField::pressureInletOutletParSlipVelocityFvPatchVectorField(), fvPatch::size(), vectorField(), and Foam::Zero.
pressureInletOutletParSlipVelocityFvPatchVectorField() [4/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField & pivpvf)
Construct as copy.
Definition at line 88 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References pressureInletOutletParSlipVelocityFvPatchVectorField::pressureInletOutletParSlipVelocityFvPatchVectorField().
pressureInletOutletParSlipVelocityFvPatchVectorField() [5/5]
pressureInletOutletParSlipVelocityFvPatchVectorField (const pressureInletOutletParSlipVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 100 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureInletOutletParSlipVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 152 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
References pressureInletOutletParSlipVelocityFvPatchVectorField::pressureInletOutletParSlipVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 172 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
References pressureInletOutletParSlipVelocityFvPatchVectorField::pressureInletOutletParSlipVelocityFvPatchVectorField().
assignable()
virtual bool assignable () const inline virtual
Return true: this patch field is altered by assignment.
Definition at line 192 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word& rhoName () const inline
Return the name of rho.
Definition at line 201 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
rhoName() [2/2]
word& rhoName () inline
Return reference to the name of rho to allow adjustment.
Definition at line 207 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
phiName() [1/2]
const word& phiName () const inline
Return the name of phi.
Definition at line 213 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
phiName() [2/2]
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 219 of file pressureInletOutletParSlipVelocityFvPatchVectorField.H.
References pressureInletOutletParSlipVelocityFvPatchVectorField::operator=(), pressureInletOutletParSlipVelocityFvPatchVectorField::updateCoeffs(), and pressureInletOutletParSlipVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 113 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, Foam::nl, phi, Foam::pos(), and pressureInletOutletParSlipVelocityFvPatchVectorField::write().
Referenced by pressureInletOutletParSlipVelocityFvPatchVectorField::phiName().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 161 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References fvPatchField< Type >::write().
Referenced by pressureInletOutletParSlipVelocityFvPatchVectorField::phiName(), and pressureInletOutletParSlipVelocityFvPatchVectorField::updateCoeffs().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 175 of file pressureInletOutletParSlipVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::operator=().
Referenced by pressureInletOutletParSlipVelocityFvPatchVectorField::phiName().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureInletOutletParSlipVelocity/pressureInletOutletParSlipVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureInletOutletParSlipVelocity/pressureInletOutletParSlipVelocityFvPatchVectorField.C