OpenFOAM: phaseHydrostaticPressureFvPatchScalarField Class Reference
phaseHydrostaticPressureFvPatchScalarField Class Reference
Boundary Conditions » Generic boundary Conditions
This boundary condition provides a phase-based hydrostatic pressure condition, calculated as:
Public Member Functions
TypeName ("phaseHydrostaticPressure")
Runtime type information.
phaseHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
phaseHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: this patch field is altered by assignment.
const word & phaseFraction () const
Return the phaseFraction.
word & phaseFraction ()
Return reference to the phaseFraction to allow adjustment.
scalar rho () const
Return the constant density in the far-field.
scalar & rho ()
Return reference to the constant density in the far-field.
scalar pRefValue () const
Return the reference pressure.
scalar & pRefValue ()
Return reference to the reference pressure to allow adjustment.
const vector & pRefPoint () const
Return the pressure reference location.
vector & pRefPoint ()
Return reference to the pressure reference location.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchScalarField &pvf)
Protected Attributes
word phaseFraction_
Name of phase-fraction field.
scalar rho_
Constant density in the far-field.
scalar pRefValue_
Reference pressure.
vector pRefPoint_
Reference pressure location.
Detailed Description
This boundary condition provides a phase-based hydrostatic pressure condition, calculated as:
where
= hyrostatic pressure [Pa]
= reference pressure [Pa]
= reference point in Cartesian co-ordinates
= density (assumed uniform)
= acceleration due to gravity [m/s2]
The values are assigned according to the phase-fraction field:
1: apply $fp_{hyd}$f
0: apply a zero-gradient condition
Usage
Property Description Required Default value
phaseFraction phase-fraction field name no alpha
rho density field name no rho
pRefValue reference pressure [Pa] yes
pRefPoint reference pressure location yes
Example of the boundary condition specification:
    <patchName>
    {
        type            phaseHydrostaticPressure;
        phaseFraction   alpha1;
        rho             rho;
        pRefValue       1e5;
        pRefPoint       (0 0 0);
        value           uniform 0; // optional initial value
    }
See also
Foam::mixedFvPatchScalarField
Source files
phaseHydrostaticPressureFvPatchScalarField.H
phaseHydrostaticPressureFvPatchScalarField.C
Definition at line 139 of file phaseHydrostaticPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
phaseHydrostaticPressureFvPatchScalarField() [1/5]
phaseHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file phaseHydrostaticPressureFvPatchScalarField.C.
Referenced by phaseHydrostaticPressureFvPatchScalarField::clone(), and phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
phaseHydrostaticPressureFvPatchScalarField() [2/5]
phaseHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 56 of file phaseHydrostaticPressureFvPatchScalarField.C.
References dictionary::found(), phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField(), scalarField(), and fvPatch::size().
phaseHydrostaticPressureFvPatchScalarField() [3/5]
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
phaseHydrostaticPressureFvPatchScalarField onto a new patch
Definition at line 89 of file phaseHydrostaticPressureFvPatchScalarField.C.
References phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
phaseHydrostaticPressureFvPatchScalarField() [4/5]
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 106 of file phaseHydrostaticPressureFvPatchScalarField.C.
References phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
phaseHydrostaticPressureFvPatchScalarField() [5/5]
phaseHydrostaticPressureFvPatchScalarField (const phaseHydrostaticPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 117 of file phaseHydrostaticPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("phaseHydrostaticPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 201 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 218 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseHydrostaticPressureFvPatchScalarField().
assignable()
virtual bool assignable () const inline virtual
Return true: this patch field is altered by assignment.
Definition at line 234 of file phaseHydrostaticPressureFvPatchScalarField.H.
phaseFraction() [1/2]
const word& phaseFraction () const inline
Return the phaseFraction.
Definition at line 243 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseFraction_.
phaseFraction() [2/2]
word& phaseFraction () inline
Return reference to the phaseFraction to allow adjustment.
Definition at line 249 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::phaseFraction_.
rho() [1/2]
scalar rho () const inline
Return the constant density in the far-field.
Definition at line 255 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::rho_.
rho() [2/2]
scalar& rho () inline
Return reference to the constant density in the far-field.
to allow adjustment
Definition at line 262 of file phaseHydrostaticPressureFvPatchScalarField.H.
pRefValue() [1/2]
scalar pRefValue () const inline
Return the reference pressure.
Definition at line 268 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::pRefValue_.
pRefValue() [2/2]
scalar& pRefValue () inline
Return reference to the reference pressure to allow adjustment.
Definition at line 274 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::pRefValue_.
pRefPoint() [1/2]
const vector& pRefPoint () const inline
Return the pressure reference location.
Definition at line 280 of file phaseHydrostaticPressureFvPatchScalarField.H.
References phaseHydrostaticPressureFvPatchScalarField::operator=(), phaseHydrostaticPressureFvPatchScalarField::pRefPoint_, phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
pRefPoint() [2/2]
vector& pRefPoint () inline
Return reference to the pressure reference location.
to allow adjustment
Definition at line 287 of file phaseHydrostaticPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 132 of file phaseHydrostaticPressureFvPatchScalarField.C.
References g, Foam::max(), Foam::min(), phaseHydrostaticPressureFvPatchScalarField::phaseFraction_, phaseHydrostaticPressureFvPatchScalarField::pRefPoint_, phaseHydrostaticPressureFvPatchScalarField::pRefValue_, and phaseHydrostaticPressureFvPatchScalarField::rho_.
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefPoint().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 161 of file phaseHydrostaticPressureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::nl, phaseHydrostaticPressureFvPatchScalarField::phaseFraction_, phaseHydrostaticPressureFvPatchScalarField::pRefPoint_, phaseHydrostaticPressureFvPatchScalarField::pRefValue_, phaseHydrostaticPressureFvPatchScalarField::rho_, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefPoint().
operator=()
void operator= (const fvPatchScalarField & pvf) virtual
Definition at line 179 of file phaseHydrostaticPressureFvPatchScalarField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::operator.
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefPoint().
Member Data Documentation
phaseFraction_
word phaseFraction_ protected
Name of phase-fraction field.
Definition at line 149 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::phaseFraction(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
rho_
scalar rho_ protected
Constant density in the far-field.
Definition at line 152 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::rho(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
pRefValue_
scalar pRefValue_ protected
Reference pressure.
Definition at line 155 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefValue(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
pRefPoint_
vector pRefPoint_ protected
Reference pressure location.
Definition at line 158 of file phaseHydrostaticPressureFvPatchScalarField.H.
Referenced by phaseHydrostaticPressureFvPatchScalarField::pRefPoint(), phaseHydrostaticPressureFvPatchScalarField::updateCoeffs(), and phaseHydrostaticPressureFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/phaseHydrostaticPressure/phaseHydrostaticPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/phaseHydrostaticPressure/phaseHydrostaticPressureFvPatchScalarField.C