OpenFOAM: rotatingTotalPressureFvPatchScalarField Class Reference
rotatingTotalPressureFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This boundary condition provides a total pressure condition for patches in a rotating frame.
Public Member Functions
TypeName ("rotatingTotalPressure")
Runtime type information.
rotatingTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
rotatingTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given rotatingTotalPressureFvPatchScalarField.
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from totalPressureFvPatchScalarField
TypeName ("totalPressure")
Runtime type information.
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
totalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given totalPressureFvPatchScalarField.
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &)
Construct as copy.
totalPressureFvPatchScalarField (const totalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const word & UName () const
Return the name of the velocity field.
word & UName ()
Return reference to the name of the velocity field.
const word & phiName () const
Return the name of the flux field.
word & phiName ()
Return reference to the name of the flux field.
const word & rhoName () const
Return the name of the density field.
word & rhoName ()
Return reference to the name of the density field.
const word & psiName () const
Return the name of the compressibility field.
word & psiName ()
Return reference to the name of the compressibility field.
scalar gamma () const
Return the heat capacity ratio.
scalar & gamma ()
Return reference to the heat capacity ratio to allow adjustment.
const scalarField & p0 () const
Return the total pressure.
scalarField & p0 ()
Return reference to the total pressure to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs (const scalarField &p0p, const vectorField &Up)
Update the coefficients associated with the patch field.
Detailed Description
This boundary condition provides a total pressure condition for patches in a rotating frame.
Usage
Property Description Required Default value
U velocity field name no U
phi flux field name no phi
rho density field name no none
psi compressibility field name no none
gamma ratio of specific heats (Cp/Cv) yes
p0 static pressure reference yes
omega angular velocty of the frame [rad/s] yes
Example of the boundary condition specification:
    <patchName>
    {
        type            rotatingTotalPressure;
        U               U;
        phi             phi;
        rho             rho;
        psi             psi;
        gamma           1.4;
        p0              uniform 1e5;
        omega           100;
    }
The omega entry is a Function1 type, able to describe time varying functions.
See also
Foam::totalPressureFvPatchScalarField Foam::Function1Types
Source files
rotatingTotalPressureFvPatchScalarField.H
rotatingTotalPressureFvPatchScalarField.C
Definition at line 127 of file rotatingTotalPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
rotatingTotalPressureFvPatchScalarField() [1/5]
rotatingTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file rotatingTotalPressureFvPatchScalarField.C.
Referenced by rotatingTotalPressureFvPatchScalarField::clone(), and rotatingTotalPressureFvPatchScalarField::rotatingTotalPressureFvPatchScalarField().
rotatingTotalPressureFvPatchScalarField() [2/5]
rotatingTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 62 of file rotatingTotalPressureFvPatchScalarField.C.
References rotatingTotalPressureFvPatchScalarField::rotatingTotalPressureFvPatchScalarField().
rotatingTotalPressureFvPatchScalarField() [3/5]
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given rotatingTotalPressureFvPatchScalarField.
onto a new patch
Definition at line 48 of file rotatingTotalPressureFvPatchScalarField.C.
References rotatingTotalPressureFvPatchScalarField::rotatingTotalPressureFvPatchScalarField().
rotatingTotalPressureFvPatchScalarField() [4/5]
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField & rtppsf)
Construct as copy.
Definition at line 75 of file rotatingTotalPressureFvPatchScalarField.C.
References rotatingTotalPressureFvPatchScalarField::rotatingTotalPressureFvPatchScalarField().
rotatingTotalPressureFvPatchScalarField() [5/5]
rotatingTotalPressureFvPatchScalarField (const rotatingTotalPressureFvPatchScalarField & rtppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 86 of file rotatingTotalPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("rotatingTotalPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 177 of file rotatingTotalPressureFvPatchScalarField.H.
References rotatingTotalPressureFvPatchScalarField::rotatingTotalPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 194 of file rotatingTotalPressureFvPatchScalarField.H.
References rotatingTotalPressureFvPatchScalarField::rotatingTotalPressureFvPatchScalarField(), rotatingTotalPressureFvPatchScalarField::updateCoeffs(), and rotatingTotalPressureFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 98 of file rotatingTotalPressureFvPatchScalarField.C.
References Foam::mag(), totalPressureFvPatchScalarField::p0(), totalPressureFvPatchScalarField::UName(), and totalPressureFvPatchScalarField::updateCoeffs().
Referenced by rotatingTotalPressureFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from totalPressureFvPatchScalarField.
Definition at line 122 of file rotatingTotalPressureFvPatchScalarField.C.
References Foam::makePatchTypeField(), and totalPressureFvPatchScalarField::write().
Referenced by rotatingTotalPressureFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/rotatingTotalPressure/rotatingTotalPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/rotatingTotalPressure/rotatingTotalPressureFvPatchScalarField.C