OpenFOAM: pressureNormalInletOutletVelocityFvPatchVectorField Class Reference
pressureNormalInletOutletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This velocity inlet/outlet boundary condition is applied to patches where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with a direction normal to the patch faces.
Public Member Functions
TypeName ("pressureNormalInletOutletVelocity")
Runtime type information.
pressureNormalInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
pressureNormalInletOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: this patch field is altered by assignment.
const word & rhoName () const
Return the name of rho.
word & rhoName ()
Return reference to the name of rho to allow adjustment.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet/outlet boundary condition is applied to patches where the pressure is specified. A zero-gradient condition is applied for outflow (as defined by the flux); for inflow, the velocity is obtained from the flux with a direction normal to the patch faces.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
Example of the boundary condition specification:
    <patchName>
    {
        type            pressureNormalInletOutletVelocity;
        phi             phi;
        rho             rho;
        value           uniform 0;
    }
Note
Sign conventions:
positive flux (out of domain): apply zero-gradient condition
negative flux (into of domain): derive from the flux and patch-normal direction
See also
Foam::mixedFvPatchVectorField
Source files
pressureNormalInletOutletVelocityFvPatchVectorField.H
pressureNormalInletOutletVelocityFvPatchVectorField.C
Definition at line 97 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureNormalInletOutletVelocityFvPatchVectorField() [1/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::Zero.
Referenced by pressureNormalInletOutletVelocityFvPatchVectorField::clone(), and pressureNormalInletOutletVelocityFvPatchVectorField::pressureNormalInletOutletVelocityFvPatchVectorField().
pressureNormalInletOutletVelocityFvPatchVectorField() [2/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 69 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References pressureNormalInletOutletVelocityFvPatchVectorField::pressureNormalInletOutletVelocityFvPatchVectorField(), fvPatch::size(), vectorField(), and Foam::Zero.
pressureNormalInletOutletVelocityFvPatchVectorField() [3/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
pressureNormalInletOutletVelocityFvPatchVectorField onto a new patch
Definition at line 54 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References pressureNormalInletOutletVelocityFvPatchVectorField::pressureNormalInletOutletVelocityFvPatchVectorField().
pressureNormalInletOutletVelocityFvPatchVectorField() [4/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField & pivpvf)
Construct as copy.
Definition at line 88 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References pressureNormalInletOutletVelocityFvPatchVectorField::pressureNormalInletOutletVelocityFvPatchVectorField().
pressureNormalInletOutletVelocityFvPatchVectorField() [5/5]
pressureNormalInletOutletVelocityFvPatchVectorField (const pressureNormalInletOutletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 100 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("pressureNormalInletOutletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 151 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
References pressureNormalInletOutletVelocityFvPatchVectorField::pressureNormalInletOutletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 171 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
References pressureNormalInletOutletVelocityFvPatchVectorField::pressureNormalInletOutletVelocityFvPatchVectorField().
assignable()
virtual bool assignable () const inline virtual
Return true: this patch field is altered by assignment.
Definition at line 191 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word& rhoName () const inline
Return the name of rho.
Definition at line 200 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
rhoName() [2/2]
word& rhoName () inline
Return reference to the name of rho to allow adjustment.
Definition at line 206 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word& phiName () const inline
Return the name of phi.
Definition at line 212 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
phiName() [2/2]
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 219 of file pressureNormalInletOutletVelocityFvPatchVectorField.H.
References pressureNormalInletOutletVelocityFvPatchVectorField::operator=(), pressureNormalInletOutletVelocityFvPatchVectorField::updateCoeffs(), and pressureNormalInletOutletVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 113 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, phi, Foam::pos(), and pressureNormalInletOutletVelocityFvPatchVectorField::write().
Referenced by pressureNormalInletOutletVelocityFvPatchVectorField::phiName().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 157 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References token::END_STATEMENT, Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by pressureNormalInletOutletVelocityFvPatchVectorField::phiName(), and pressureNormalInletOutletVelocityFvPatchVectorField::updateCoeffs().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 171 of file pressureNormalInletOutletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField().
Referenced by pressureNormalInletOutletVelocityFvPatchVectorField::phiName().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureNormalInletOutletVelocity/pressureNormalInletOutletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureNormalInletOutletVelocity/pressureNormalInletOutletVelocityFvPatchVectorField.C