OpenFOAM: supersonicFreestreamFvPatchVectorField Class Reference
supersonicFreestreamFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary ConditionsBoundary Conditions » | Outlet boundary Conditions
This boundary condition provides a supersonic free-stream condition.
Public Member Functions
TypeName ("supersonicFreestream")
Runtime type information.
supersonicFreestreamFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
supersonicFreestreamFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given supersonicFreestreamFvPatchVectorField.
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const vector & UInf () const
Return the velocity at infinity.
vector & UInf ()
Return reference to the velocity at infinity to allow adjustment.
scalar pInf () const
Return the pressure at infinity.
scalar & pInf ()
Return reference to the pressure at infinity to allow adjustment.
scalar TInf () const
Return the temperature at infinity.
scalar & TInf ()
Return reference to the temperature at infinity.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a supersonic free-stream condition.
- supersonic outflow is vented according to ???
supersonic inflow is assumed to occur according to the Prandtl-Meyer expansion process.
subsonic outflow is applied via a zero-gradient condition from inside the domain.
Usage
Property Description Required Default value
T Temperature field name no T
p Pressure field name no p
psi Compressibility field name no thermo:psi
UInf free-stream velocity yes
pInf free-stream pressure yes
TInf free-stream temperature yes
gamma heat capacity ratio (cp/Cv) yes
Example of the boundary condition specification:
    <patchName>
    {
        type            supersonicFreestream;
        UInf            500;
        pInf            1e4;
        TInf            265;
        gamma           1.4;
    }
Note
This boundary condition is ill-posed if the free-stream flow is normal to the boundary.
Source files
supersonicFreestreamFvPatchVectorField.H
supersonicFreestreamFvPatchVectorField.C
Definition at line 126 of file supersonicFreestreamFvPatchVectorField.H.
Constructor & Destructor Documentation
supersonicFreestreamFvPatchVectorField() [1/5]
supersonicFreestreamFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file supersonicFreestreamFvPatchVectorField.C.
References Foam::Zero.
Referenced by supersonicFreestreamFvPatchVectorField::clone(), and supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField().
supersonicFreestreamFvPatchVectorField() [2/5]
supersonicFreestreamFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 57 of file supersonicFreestreamFvPatchVectorField.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), fvPatch::size(), supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField(), vectorField(), and Foam::Zero.
supersonicFreestreamFvPatchVectorField() [3/5]
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given supersonicFreestreamFvPatchVectorField.
onto a new patch
Definition at line 104 of file supersonicFreestreamFvPatchVectorField.C.
References supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField().
supersonicFreestreamFvPatchVectorField() [4/5]
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField & sfspvf)
Construct as copy.
Definition at line 124 of file supersonicFreestreamFvPatchVectorField.C.
References supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField().
supersonicFreestreamFvPatchVectorField() [5/5]
supersonicFreestreamFvPatchVectorField (const supersonicFreestreamFvPatchVectorField & sfspvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 141 of file supersonicFreestreamFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("supersonicFreestream")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 194 of file supersonicFreestreamFvPatchVectorField.H.
References supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 211 of file supersonicFreestreamFvPatchVectorField.H.
References supersonicFreestreamFvPatchVectorField::supersonicFreestreamFvPatchVectorField().
UInf() [1/2]
const vector& UInf () const inline
Return the velocity at infinity.
Definition at line 227 of file supersonicFreestreamFvPatchVectorField.H.
UInf() [2/2]
vector& UInf () inline
Return reference to the velocity at infinity to allow adjustment.
Definition at line 233 of file supersonicFreestreamFvPatchVectorField.H.
pInf() [1/2]
scalar pInf () const inline
Return the pressure at infinity.
Definition at line 239 of file supersonicFreestreamFvPatchVectorField.H.
pInf() [2/2]
scalar& pInf () inline
Return reference to the pressure at infinity to allow adjustment.
Definition at line 245 of file supersonicFreestreamFvPatchVectorField.H.
TInf() [1/2]
scalar TInf () const inline
Return the temperature at infinity.
Definition at line 251 of file supersonicFreestreamFvPatchVectorField.H.
References supersonicFreestreamFvPatchVectorField::updateCoeffs(), and supersonicFreestreamFvPatchVectorField::write().
TInf() [2/2]
scalar& TInf () inline
Return reference to the temperature at infinity.
to allow adjustment
Definition at line 258 of file supersonicFreestreamFvPatchVectorField.H.
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 159 of file supersonicFreestreamFvPatchVectorField.C.
References Foam::atan(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::log(), Foam::mag(), Foam::pow(), R, Foam::sqr(), Foam::sqrt(), and U.
Referenced by supersonicFreestreamFvPatchVectorField::TInf().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 295 of file supersonicFreestreamFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, and fvPatchField< Type >::write().
Referenced by supersonicFreestreamFvPatchVectorField::TInf().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/supersonicFreestream/supersonicFreestreamFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/supersonicFreestream/supersonicFreestreamFvPatchVectorField.C