OpenFOAM: prghTotalPressureFvPatchScalarField Class Reference
prghTotalPressureFvPatchScalarField Class Reference
Boundary Conditions » Generic boundary Conditions
This boundary condition provides static pressure condition for p_rgh, calculated as:
Public Member Functions
TypeName ("prghTotalPressure")
Runtime type information.
prghTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
prghTotalPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & p0 () const
Return the total pressure.
scalarField & p0 ()
Return reference to the total pressure to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Attributes
word UName_
Name of the velocity field.
word phiName_
Name of the flux transporting the field.
word rhoName_
Name of phase-fraction field.
scalarField p0_
Total pressure.
Detailed Description
This boundary condition provides static pressure condition for p_rgh, calculated as:
where
= Pseudo hydrostatic pressure [Pa]
= Static pressure [Pa]
= Total pressure [Pa]
= Height in the opposite direction to gravity
= Reference height in the opposite direction to gravity
= Density
= Acceleration due to gravity [m/s^2]
Usage
Property Description Required Default value
U Velocity field name no U
phi Flux field name no phi
rho Density field name no rho
p0 Total pressure yes
Example of the boundary condition specification:
    <patchName>
    {
        type            prghTotalPressure;
        p0              uniform 0;
    }
See also
Foam::fixedValueFvPatchScalarField
Source files
prghTotalPressureFvPatchScalarField.H
prghTotalPressureFvPatchScalarField.C
Definition at line 142 of file prghTotalPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
prghTotalPressureFvPatchScalarField() [1/5]
prghTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file prghTotalPressureFvPatchScalarField.C.
Referenced by prghTotalPressureFvPatchScalarField::clone(), and prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField().
prghTotalPressureFvPatchScalarField() [2/5]
prghTotalPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 52 of file prghTotalPressureFvPatchScalarField.C.
References dictionary::found(), prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField(), scalarField(), and fvPatch::size().
prghTotalPressureFvPatchScalarField() [3/5]
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
prghTotalPressureFvPatchScalarField onto a new patch
Definition at line 80 of file prghTotalPressureFvPatchScalarField.C.
References prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField().
prghTotalPressureFvPatchScalarField() [4/5]
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 97 of file prghTotalPressureFvPatchScalarField.C.
References prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField().
prghTotalPressureFvPatchScalarField() [5/5]
prghTotalPressureFvPatchScalarField (const prghTotalPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 111 of file prghTotalPressureFvPatchScalarField.C.
References prghTotalPressureFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("prghTotalPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 204 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 221 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField().
p0() [1/2]
const scalarField& p0 () const inline
Return the total pressure.
Definition at line 237 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::p0_.
p0() [2/2]
scalarField& p0 () inline
Return reference to the total pressure to allow adjustment.
Definition at line 243 of file prghTotalPressureFvPatchScalarField.H.
References prghTotalPressureFvPatchScalarField::autoMap(), prghTotalPressureFvPatchScalarField::p0_, prghTotalPressureFvPatchScalarField::rmap(), prghTotalPressureFvPatchScalarField::updateCoeffs(), and prghTotalPressureFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 127 of file prghTotalPressureFvPatchScalarField.C.
References prghTotalPressureFvPatchScalarField::rmap().
Referenced by prghTotalPressureFvPatchScalarField::p0(), and prghTotalPressureFvPatchScalarField::prghTotalPressureFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 137 of file prghTotalPressureFvPatchScalarField.C.
References prghTotalPressureFvPatchScalarField::p0_, and prghTotalPressureFvPatchScalarField::rmap().
Referenced by prghTotalPressureFvPatchScalarField::autoMap(), prghTotalPressureFvPatchScalarField::p0(), and prghTotalPressureFvPatchScalarField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 151 of file prghTotalPressureFvPatchScalarField.C.
References Foam::cmptMag(), Foam::dimLength, g, Foam::mag(), Foam::magSqr(), prghTotalPressureFvPatchScalarField::p0_, prghTotalPressureFvPatchScalarField::phiName_, Foam::pos(), prghTotalPressureFvPatchScalarField::rhoName_, and prghTotalPressureFvPatchScalarField::UName_.
Referenced by prghTotalPressureFvPatchScalarField::p0().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 191 of file prghTotalPressureFvPatchScalarField.C.
References Foam::makePatchTypeField(), prghTotalPressureFvPatchScalarField::p0_, prghTotalPressureFvPatchScalarField::phiName_, prghTotalPressureFvPatchScalarField::rhoName_, prghTotalPressureFvPatchScalarField::UName_, fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by prghTotalPressureFvPatchScalarField::p0().
Member Data Documentation
UName_
word UName_ protected
Name of the velocity field.
Definition at line 152 of file prghTotalPressureFvPatchScalarField.H.
Referenced by prghTotalPressureFvPatchScalarField::updateCoeffs(), and prghTotalPressureFvPatchScalarField::write().
phiName_
word phiName_ protected
Name of the flux transporting the field.
Definition at line 155 of file prghTotalPressureFvPatchScalarField.H.
Referenced by prghTotalPressureFvPatchScalarField::updateCoeffs(), and prghTotalPressureFvPatchScalarField::write().
rhoName_
word rhoName_ protected
Name of phase-fraction field.
Definition at line 158 of file prghTotalPressureFvPatchScalarField.H.
Referenced by prghTotalPressureFvPatchScalarField::updateCoeffs(), and prghTotalPressureFvPatchScalarField::write().
p0_
scalarField p0_ protected
Total pressure.
Definition at line 161 of file prghTotalPressureFvPatchScalarField.H.
Referenced by prghTotalPressureFvPatchScalarField::p0(), prghTotalPressureFvPatchScalarField::rmap(), prghTotalPressureFvPatchScalarField::updateCoeffs(), and prghTotalPressureFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/prghTotalPressure/prghTotalPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/prghTotalPressure/prghTotalPressureFvPatchScalarField.C