OpenFOAM: prghTotalHydrostaticPressureFvPatchScalarField Class Reference
prghTotalHydrostaticPressureFvPatchScalarField Class Reference
Boundary Conditions » Generic boundary Conditions
This boundary condition provides static pressure condition for p_rgh, calculated as:
Public Member Functions
TypeName ("prghTotalHydrostaticPressure")
Runtime type information.
prghTotalHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
prghTotalHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Attributes
word UName_
Name of the velocity field.
word phiName_
Name of the flux transporting the field.
word rhoName_
Name of density field.
word ph_rghName_
Name of hydrostatic pressure field.
Detailed Description
This boundary condition provides static pressure condition for p_rgh, calculated as:
where
= Pressure - g.(h - hRef) [Pa]
= Hydrostatic pressure - g.(h - hRef) [Pa]
= Height in the opposite direction to gravity
= Reference height in the opposite direction to gravity
= Density
= Acceleration due to gravity [m/s^2]
Usage
Property Description Required Default value
U Velocity field name no U
phi Flux field name no phi
rho Density field name no rho
ph_rgh ph_rgh field name no ph_rgh
value Patch face values yes
Example of the boundary condition specification:
    <patchName>
    {
        type            prghTotalHydrostaticPressure;
        value           uniform 0;
    }
See also
Foam::fixedValueFvPatchScalarField Foam::prghTotalPressureFvPatchScalarField
Source files
prghTotalHydrostaticPressureFvPatchScalarField.H
prghTotalHydrostaticPressureFvPatchScalarField.C
Definition at line 143 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
prghTotalHydrostaticPressureFvPatchScalarField() [1/5]
prghTotalHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
Referenced by prghTotalHydrostaticPressureFvPatchScalarField::clone(), and prghTotalHydrostaticPressureFvPatchScalarField::prghTotalHydrostaticPressureFvPatchScalarField().
prghTotalHydrostaticPressureFvPatchScalarField() [2/5]
prghTotalHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 52 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
References prghTotalHydrostaticPressureFvPatchScalarField::prghTotalHydrostaticPressureFvPatchScalarField().
prghTotalHydrostaticPressureFvPatchScalarField() [3/5]
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
prghTotalHydrostaticPressureFvPatchScalarField onto a new patch
Definition at line 68 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
References prghTotalHydrostaticPressureFvPatchScalarField::prghTotalHydrostaticPressureFvPatchScalarField().
prghTotalHydrostaticPressureFvPatchScalarField() [4/5]
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 85 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
References prghTotalHydrostaticPressureFvPatchScalarField::prghTotalHydrostaticPressureFvPatchScalarField().
prghTotalHydrostaticPressureFvPatchScalarField() [5/5]
prghTotalHydrostaticPressureFvPatchScalarField (const prghTotalHydrostaticPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 99 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("prghTotalHydrostaticPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 205 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
References prghTotalHydrostaticPressureFvPatchScalarField::prghTotalHydrostaticPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 222 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
References prghTotalHydrostaticPressureFvPatchScalarField::prghTotalHydrostaticPressureFvPatchScalarField(), prghTotalHydrostaticPressureFvPatchScalarField::updateCoeffs(), and prghTotalHydrostaticPressureFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 114 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
References Foam::magSqr(), prghTotalHydrostaticPressureFvPatchScalarField::ph_rghName_, prghTotalHydrostaticPressureFvPatchScalarField::phiName_, Foam::pos(), prghTotalHydrostaticPressureFvPatchScalarField::rhoName_, prghTotalHydrostaticPressureFvPatchScalarField::UName_, and prghTotalHydrostaticPressureFvPatchScalarField::write().
Referenced by prghTotalHydrostaticPressureFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 144 of file prghTotalHydrostaticPressureFvPatchScalarField.C.
References Foam::makePatchTypeField(), prghTotalHydrostaticPressureFvPatchScalarField::ph_rghName_, prghTotalHydrostaticPressureFvPatchScalarField::phiName_, prghTotalHydrostaticPressureFvPatchScalarField::rhoName_, prghTotalHydrostaticPressureFvPatchScalarField::UName_, and fvPatchField< Type >::write().
Referenced by prghTotalHydrostaticPressureFvPatchScalarField::clone(), and prghTotalHydrostaticPressureFvPatchScalarField::updateCoeffs().
Member Data Documentation
UName_
word UName_ protected
Name of the velocity field.
Definition at line 153 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
Referenced by prghTotalHydrostaticPressureFvPatchScalarField::updateCoeffs(), and prghTotalHydrostaticPressureFvPatchScalarField::write().
phiName_
word phiName_ protected
Name of the flux transporting the field.
Definition at line 156 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
Referenced by prghTotalHydrostaticPressureFvPatchScalarField::updateCoeffs(), and prghTotalHydrostaticPressureFvPatchScalarField::write().
rhoName_
word rhoName_ protected
Name of density field.
Definition at line 159 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
Referenced by prghTotalHydrostaticPressureFvPatchScalarField::updateCoeffs(), and prghTotalHydrostaticPressureFvPatchScalarField::write().
ph_rghName_
word ph_rghName_ protected
Name of hydrostatic pressure field.
Definition at line 162 of file prghTotalHydrostaticPressureFvPatchScalarField.H.
Referenced by prghTotalHydrostaticPressureFvPatchScalarField::updateCoeffs(), and prghTotalHydrostaticPressureFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/prghTotalHydrostaticPressure/prghTotalHydrostaticPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/prghTotalHydrostaticPressure/prghTotalHydrostaticPressureFvPatchScalarField.C