OpenFOAM: pressureDirectedInletVelocityFvPatchVectorField Class Reference
pressureDirectedInletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary Conditions
This velocity inlet boundary condition is applied to patches where the pressure is specified. The inflow velocity is obtained from the flux with the specified inlet direction" direction.
Public Member Functions
TypeName ("pressureDirectedInletVelocity")
Runtime type information.
pressureDirectedInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
pressureDirectedInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: this patch field is altered by assignment.
const word & rhoName () const
Return the name of rho.
word & rhoName ()
Return reference to the name of rho to allow adjustment.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This velocity inlet boundary condition is applied to patches where the pressure is specified. The inflow velocity is obtained from the flux with the specified inlet direction" direction.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
inletDirection inlet direction per patch face yes
Example of the boundary condition specification:
    <patchName>
    {
        type            pressureDirectedInletVelocity;
        phi             phi;
        rho             rho;
        inletDirection  uniform (1 0 0);
        value           uniform 0;
    }
Note
If reverse flow is possible or expected use the pressureDirectedInletOutletVelocityFvPatchVectorField condition instead.
See also
Foam::fixedValueFvPatchField Foam::pressureDirectedInletOutletVelocityFvPatchVectorField
Source files
pressureDirectedInletVelocityFvPatchVectorField.H
pressureDirectedInletVelocityFvPatchVectorField.C
Definition at line 103 of file pressureDirectedInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
pressureDirectedInletVelocityFvPatchVectorField() [1/5]
pressureDirectedInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file pressureDirectedInletVelocityFvPatchVectorField.C.
Referenced by pressureDirectedInletVelocityFvPatchVectorField::clone(), and pressureDirectedInletVelocityFvPatchVectorField::pressureDirectedInletVelocityFvPatchVectorField().
pressureDirectedInletVelocityFvPatchVectorField() [2/5]
pressureDirectedInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 67 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References pressureDirectedInletVelocityFvPatchVectorField::pressureDirectedInletVelocityFvPatchVectorField().
pressureDirectedInletVelocityFvPatchVectorField() [3/5]
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
pressureDirectedInletVelocityFvPatchVectorField onto a new patch
Definition at line 51 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References pressureDirectedInletVelocityFvPatchVectorField::pressureDirectedInletVelocityFvPatchVectorField().
pressureDirectedInletVelocityFvPatchVectorField() [4/5]
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField & pivpvf)
Construct as copy.
Definition at line 82 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References pressureDirectedInletVelocityFvPatchVectorField::pressureDirectedInletVelocityFvPatchVectorField().
pressureDirectedInletVelocityFvPatchVectorField() [5/5]
pressureDirectedInletVelocityFvPatchVectorField (const pressureDirectedInletVelocityFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 95 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References pressureDirectedInletVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("pressureDirectedInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 160 of file pressureDirectedInletVelocityFvPatchVectorField.H.
References pressureDirectedInletVelocityFvPatchVectorField::pressureDirectedInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 177 of file pressureDirectedInletVelocityFvPatchVectorField.H.
References pressureDirectedInletVelocityFvPatchVectorField::pressureDirectedInletVelocityFvPatchVectorField().
assignable()
virtual bool assignable () const inline virtual
Return true: this patch field is altered by assignment.
Definition at line 197 of file pressureDirectedInletVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word& rhoName () const inline
Return the name of rho.
Definition at line 205 of file pressureDirectedInletVelocityFvPatchVectorField.H.
rhoName() [2/2]
word& rhoName () inline
Return reference to the name of rho to allow adjustment.
Definition at line 211 of file pressureDirectedInletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word& phiName () const inline
Return the name of phi.
Definition at line 217 of file pressureDirectedInletVelocityFvPatchVectorField.H.
phiName() [2/2]
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 223 of file pressureDirectedInletVelocityFvPatchVectorField.H.
References pressureDirectedInletVelocityFvPatchVectorField::autoMap(), pressureDirectedInletVelocityFvPatchVectorField::operator=(), pressureDirectedInletVelocityFvPatchVectorField::rmap(), pressureDirectedInletVelocityFvPatchVectorField::updateCoeffs(), and pressureDirectedInletVelocityFvPatchVectorField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 110 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References pressureDirectedInletVelocityFvPatchVectorField::rmap().
Referenced by pressureDirectedInletVelocityFvPatchVectorField::phiName(), and pressureDirectedInletVelocityFvPatchVectorField::pressureDirectedInletVelocityFvPatchVectorField().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 120 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References pressureDirectedInletVelocityFvPatchVectorField::rmap().
Referenced by pressureDirectedInletVelocityFvPatchVectorField::autoMap(), pressureDirectedInletVelocityFvPatchVectorField::phiName(), and pressureDirectedInletVelocityFvPatchVectorField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 134 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, n, Foam::operator==(), phi, and pressureDirectedInletVelocityFvPatchVectorField::write().
Referenced by pressureDirectedInletVelocityFvPatchVectorField::phiName().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 176 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by pressureDirectedInletVelocityFvPatchVectorField::phiName(), and pressureDirectedInletVelocityFvPatchVectorField::updateCoeffs().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 191 of file pressureDirectedInletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::operator=().
Referenced by pressureDirectedInletVelocityFvPatchVectorField::phiName().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/pressureDirectedInletVelocity/pressureDirectedInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/pressureDirectedInletVelocity/pressureDirectedInletVelocityFvPatchVectorField.C