OpenFOAM: uniformDensityHydrostaticPressureFvPatchScalarField Class Reference
uniformDensityHydrostaticPressureFvPatchScalarField Class Reference
Boundary Conditions » Generic boundary Conditions
This boundary condition provides a hydrostatic pressure condition, calculated as:
Public Member Functions
TypeName ("uniformDensityHydrostaticPressure")
Runtime type information.
uniformDensityHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
uniformDensityHydrostaticPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
scalar rho () const
Return the constant density in the far-field.
scalar & rho ()
Return reference to the constant density in the far-field.
scalar pRefValue () const
Return the reference pressure.
scalar & pRefValue ()
Return reference to the reference pressure to allow adjustment.
const vector & pRefPoint () const
Return the pressure reference location.
vector & pRefPoint ()
Return reference to the pressure reference location.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a hydrostatic pressure condition, calculated as:
where
= hyrostatic pressure [Pa]
= reference pressure [Pa]
= reference point in Cartesian co-ordinates
= density (assumed uniform)
= acceleration due to gravity [m/s2]
Usage
Property Description Required Default value
rho uniform density [kg/m3] yes
pRefValue reference pressure [Pa] yes
pRefPoint reference pressure location yes
Example of the boundary condition specification:
    <patchName>
    {
        type            uniformDensityHydrostaticPressure;
        rho             rho;
        pRefValue       1e5;
        pRefPoint       (0 0 0);
        value           uniform 0; // optional initial value
    }
Source files
uniformDensityHydrostaticPressureFvPatchScalarField.H
uniformDensityHydrostaticPressureFvPatchScalarField.C
Definition at line 125 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
uniformDensityHydrostaticPressureFvPatchScalarField() [1/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
Referenced by uniformDensityHydrostaticPressureFvPatchScalarField::clone(), and uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField().
uniformDensityHydrostaticPressureFvPatchScalarField() [2/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 51 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
References dictionary::found(), scalarField(), fvPatch::size(), and uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField().
uniformDensityHydrostaticPressureFvPatchScalarField() [3/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
uniformDensityHydrostaticPressureFvPatchScalarField onto a new patch
Definition at line 78 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
References uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField().
uniformDensityHydrostaticPressureFvPatchScalarField() [4/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 94 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
References uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField().
uniformDensityHydrostaticPressureFvPatchScalarField() [5/5]
uniformDensityHydrostaticPressureFvPatchScalarField (const uniformDensityHydrostaticPressureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 107 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("uniformDensityHydrostaticPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 181 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
References uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 198 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
References uniformDensityHydrostaticPressureFvPatchScalarField::uniformDensityHydrostaticPressureFvPatchScalarField().
rho() [1/2]
scalar rho () const inline
Return the constant density in the far-field.
Definition at line 218 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
rho() [2/2]
scalar& rho () inline
Return reference to the constant density in the far-field.
to allow adjustment
Definition at line 225 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
pRefValue() [1/2]
scalar pRefValue () const inline
Return the reference pressure.
Definition at line 231 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
pRefValue() [2/2]
scalar& pRefValue () inline
Return reference to the reference pressure to allow adjustment.
Definition at line 237 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
pRefPoint() [1/2]
const vector& pRefPoint () const inline
Return the pressure reference location.
Definition at line 243 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
References uniformDensityHydrostaticPressureFvPatchScalarField::updateCoeffs(), and uniformDensityHydrostaticPressureFvPatchScalarField::write().
pRefPoint() [2/2]
vector& pRefPoint () inline
Return reference to the pressure reference location.
to allow adjustment
Definition at line 250 of file uniformDensityHydrostaticPressureFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 121 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
References g, dimensioned< Type >::value(), and uniformDensityHydrostaticPressureFvPatchScalarField::write().
Referenced by uniformDensityHydrostaticPressureFvPatchScalarField::pRefPoint().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 142 of file uniformDensityHydrostaticPressureFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by uniformDensityHydrostaticPressureFvPatchScalarField::pRefPoint(), and uniformDensityHydrostaticPressureFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/uniformDensityHydrostaticPressure/uniformDensityHydrostaticPressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/uniformDensityHydrostaticPressure/uniformDensityHydrostaticPressureFvPatchScalarField.C