OpenFOAM: translatingWallVelocityFvPatchVectorField Class Reference
translatingWallVelocityFvPatchVectorField Class Reference
Boundary Conditions » Wall boundary ConditionsBoundary Conditions » | Generic boundary Conditions
This boundary condition provides a velocity condition for translational motion on walls.
Public Member Functions
TypeName ("translatingWallVelocity")
Runtime type information.
translatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
translatingWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given a.
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a velocity condition for translational motion on walls.
Usage
Property Description Required Default value
U translational velocity yes
Example of the boundary condition specification:
    <patchName>
    {
        type            translatingWallVelocity;
        U               (100 0 0);
    }
The U entry is a Function1 of time, see Foam::Function1Types.
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
translatingWallVelocityFvPatchVectorField.H
translatingWallVelocityFvPatchVectorField.C
Definition at line 85 of file translatingWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
translatingWallVelocityFvPatchVectorField() [1/5]
translatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 34 of file translatingWallVelocityFvPatchVectorField.C.
Referenced by translatingWallVelocityFvPatchVectorField::clone(), and translatingWallVelocityFvPatchVectorField::translatingWallVelocityFvPatchVectorField().
translatingWallVelocityFvPatchVectorField() [2/5]
translatingWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 46 of file translatingWallVelocityFvPatchVectorField.C.
References translatingWallVelocityFvPatchVectorField::translatingWallVelocityFvPatchVectorField().
translatingWallVelocityFvPatchVectorField() [3/5]
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given a.
translatingWallVelocityFvPatchVectorField onto a new patch
Definition at line 62 of file translatingWallVelocityFvPatchVectorField.C.
References translatingWallVelocityFvPatchVectorField::translatingWallVelocityFvPatchVectorField().
translatingWallVelocityFvPatchVectorField() [4/5]
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField & twvpvf)
Construct as copy.
Definition at line 76 of file translatingWallVelocityFvPatchVectorField.C.
References translatingWallVelocityFvPatchVectorField::translatingWallVelocityFvPatchVectorField().
translatingWallVelocityFvPatchVectorField() [5/5]
translatingWallVelocityFvPatchVectorField (const translatingWallVelocityFvPatchVectorField & twvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 87 of file translatingWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("translatingWallVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 135 of file translatingWallVelocityFvPatchVectorField.H.
References translatingWallVelocityFvPatchVectorField::translatingWallVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 152 of file translatingWallVelocityFvPatchVectorField.H.
References translatingWallVelocityFvPatchVectorField::translatingWallVelocityFvPatchVectorField(), translatingWallVelocityFvPatchVectorField::updateCoeffs(), and translatingWallVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 99 of file translatingWallVelocityFvPatchVectorField.C.
References n, Field< vector >::operator=(), and U.
Referenced by translatingWallVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 117 of file translatingWallVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by translatingWallVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/translatingWallVelocity/translatingWallVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/translatingWallVelocity/translatingWallVelocityFvPatchVectorField.C