OpenFOAM: variableHeightFlowRateInletVelocityFvPatchVectorField Class Reference
variableHeightFlowRateInletVelocityFvPatchVectorField Class Reference
Boundary Conditions » Inlet boundary Conditions
This boundary condition provides a velocity boundary condition for multphase flow based on a user-specified volumetric flow rate.
Public Member Functions
TypeName ("variableHeightFlowRateInletVelocity")
Runtime type information.
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a velocity boundary condition for multphase flow based on a user-specified volumetric flow rate.
The flow rate is made proportional to the phase fraction alpha at each face of the patch and alpha is ensured to be bound between 0 and 1.
Usage
Property Description Required Default value
flowRate volumetric flow rate [m3/s] yes
alpha phase-fraction field yes
Example of the boundary condition specification:
    <patchName>
    {
        type            variableHeightFlowRateInletVelocity;
        flowRate        0.2;
        alpha           alpha.water;
        value           uniform (0 0 0); // placeholder
    }
The flowRate entry is a Function1 of time, see Foam::Function1Types.
Note
the value is positive into the domain
may not work correctly for transonic inlets
strange behaviour with potentialFoam since the momentum equation is not solved
See also
Foam::fixedValueFvPatchField Foam::Function1Types
Source files
variableHeightFlowRateInletVelocityFvPatchVectorField.H
variableHeightFlowRateInletVelocityFvPatchVectorField.C
Definition at line 100 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
variableHeightFlowRateInletVelocityFvPatchVectorField() [1/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 34 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
Referenced by variableHeightFlowRateInletVelocityFvPatchVectorField::clone(), and variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
variableHeightFlowRateInletVelocityFvPatchVectorField() [2/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 47 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
variableHeightFlowRateInletVelocityFvPatchVectorField() [3/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
variableHeightFlowRateInletVelocityFvPatchVectorField onto a new patch
Definition at line 61 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
variableHeightFlowRateInletVelocityFvPatchVectorField() [4/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField & ptf)
Construct as copy.
Definition at line 76 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
variableHeightFlowRateInletVelocityFvPatchVectorField() [5/5]
variableHeightFlowRateInletVelocityFvPatchVectorField (const variableHeightFlowRateInletVelocityFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 88 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References variableHeightFlowRateInletVelocityFvPatchVectorField::updateCoeffs().
Member Function Documentation
TypeName()
TypeName ("variableHeightFlowRateInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 154 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
References variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 171 of file variableHeightFlowRateInletVelocityFvPatchVectorField.H.
References variableHeightFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField(), and variableHeightFlowRateInletVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 102 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References Foam::gSum(), Foam::max(), Foam::min(), n, Foam::operator==(), and variableHeightFlowRateInletVelocityFvPatchVectorField::write().
Referenced by variableHeightFlowRateInletVelocityFvPatchVectorField::clone(), and variableHeightFlowRateInletVelocityFvPatchVectorField::variableHeightFlowRateInletVelocityFvPatchVectorField().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 130 of file variableHeightFlowRateInletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), Foam::nl, write(), and Ostream::writeKeyword().
Referenced by variableHeightFlowRateInletVelocityFvPatchVectorField::clone(), and variableHeightFlowRateInletVelocityFvPatchVectorField::updateCoeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRateInletVelocity/variableHeightFlowRateInletVelocityFvPatchVectorField.H
src/finiteVolume/fields/fvPatchFields/derived/variableHeightFlowRateInletVelocity/variableHeightFlowRateInletVelocityFvPatchVectorField.C