OpenFOAM: fvPatchField< Type > Class Template Reference
fvPatchField< Type > Class Template Reference
Abstract base class with a fat-interface to all derived classes covering all possible ways in which they might be used.
Public Types
typedef fvPatch Patch
typedef calculatedFvPatchField< Type > Calculated
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("fvPatchField")
Runtime type information.
declareRunTimeSelectionTable (tmp, fvPatchField, patch,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvPatchField, patchMapper,(const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvPatchFieldType &>(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict),(p, iF, dict))
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &)
Construct from patch and internal field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Type &value)
Construct from patch, internal field and value.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const word &patchType)
Construct from patch and internal field and patch type.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
fvPatchField (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &, const bool valueRequired=true)
Construct from patch, internal field and dictionary.
fvPatchField (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fvPatchField onto a new patch.
fvPatchField (const fvPatchField< Type > &)
Construct as copy.
virtual tmp< fvPatchField< Type > > clone () const
Construct and return a clone.
fvPatchField (const fvPatchField< Type > &, const DimensionedField< Type, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchField< Type > > clone (const DimensionedField< Type, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual ~fvPatchField ()
Destructor.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool assignable () const
Return true if the value of the patch field.
virtual bool coupled () const
Return true if this patch field is coupled.
const objectRegistry & db () const
Return local objectRegistry.
const fvPatch & patch () const
Return patch.
const DimensionedField< Type, volMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
bool updated () const
Return true if the boundary condition has already been updated.
bool manipulatedMatrix () const
Return true if the matrix has already been manipulated.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchField< Type > &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual tmp< Field< Type > > snGrad () const
Return patch-normal gradient.
virtual tmp< Field< Type > > snGrad (const scalarField &deltaCoeffs) const
Return patch-normal gradient for coupled-patches.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void updateWeightedCoeffs (const scalarField &weights)
Update the coefficients associated with the patch field.
virtual tmp< Field< Type > > patchInternalField () const
Return internal field next to patch as patch field.
virtual void patchInternalField (Field< Type > &) const
Return internal field next to patch as patch field.
virtual tmp< Field< Type > > patchNeighbourField () const
Return patchField on the opposite patch of a coupled patch.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise the evaluation of the patch field.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field, sets Updated to false.
virtual tmp< Field< Type > > valueInternalCoeffs (const tmp< Field< scalar >> &) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > valueBoundaryCoeffs (const tmp< Field< scalar >> &) const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientInternalCoeffs (const scalarField &deltaCoeffs) const
Return the matrix diagonal coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the.
virtual tmp< Field< Type > > gradientBoundaryCoeffs (const scalarField &deltaCoeffs) const
Return the matrix source coefficients corresponding to the.
virtual void manipulateMatrix (fvMatrix< Type > &matrix)
Manipulate matrix.
virtual void manipulateMatrix (fvMatrix< Type > &matrix, const scalarField &weights)
Manipulate matrix with given weights.
virtual void write (Ostream &) const
Write.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
void check (const fvPatchField< Type > &) const
Check fvPatchField<Type> against given fvPatchField<Type>
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvPatchField< Type > &)
virtual void operator+= (const fvPatchField< Type > &)
virtual void operator-= (const fvPatchField< Type > &)
virtual void operator*= (const fvPatchField< scalar > &)
virtual void operator/= (const fvPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const fvPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &pf)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< Type >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< Type >)
Assignment to an initializer list.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static tmp< fvPatchField< Type > > New (const word &, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const word &, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, volMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvPatchField< Type > > New (const fvPatchField< Type > &, const fvPatch &, const DimensionedField< Type, volMesh > &, const fvPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static tmp< fvPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, volMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatch &)
Return a pointer to a new calculatedFvPatchField created on.
template<class Type2 >
static tmp< fvPatchField< Type > > NewCalculatedType (const fvPatchField< Type2 > &)
Return a pointer to a new calculatedFvPatchField created on.
static const word & calculatedType ()
Return the type of the calculated for of fvPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes
static int disallowGenericFvPatchField
Debug switch to disallow the use of genericFvPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Friends
Ostream & operator (Ostream &, const fvPatchField< Type > &)
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::fvPatchField< Type >
Abstract base class with a fat-interface to all derived classes covering all possible ways in which they might be used.
The first level of derivation is to basic patchFields which cover zero-gradient, fixed-gradient, fixed-value and mixed conditions.
The next level of derivation covers all the specialised types with specific evaluation proceedures, particularly with respect to specific fields.
Source files
fvPatchField.H
fvPatchField.C
fvPatchFieldNew.C
Definition at line 65 of file fvPatchField.H.
Member Typedef Documentation
Patch
typedef fvPatch Patch
Definition at line 110 of file fvPatchField.H.
Calculated
typedef calculatedFvPatchField<Type> Calculated
Definition at line 111 of file fvPatchField.H.
Constructor & Destructor Documentation
fvPatchField() [1/8]
fvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file fvPatchField.C.
Referenced by fvPatchField< Type >::clone(), and fvPatchField< Type >::fvPatchField().
fvPatchField() [2/8]
fvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const Type & value)
Construct from patch, internal field and value.
Definition at line 52 of file fvPatchField.C.
References fvPatchField< Type >::fvPatchField().
fvPatchField() [3/8]
fvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const word & patchType)
Construct from patch and internal field and patch type.
Definition at line 69 of file fvPatchField.C.
References fvPatchField< Type >::fvPatchField().
fvPatchField() [4/8]
fvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const Field< Type > & f)
Construct from patch and internal field and patch field.
Definition at line 86 of file fvPatchField.C.
References fvPatchField< Type >::fvPatchField().
fvPatchField() [5/8]
fvPatchField (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const dictionary & dict, const bool valueRequired = true)
Construct from patch, internal field and dictionary.
Definition at line 103 of file fvPatchField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), fvPatchField< Type >::fvPatchField(), and fvPatch::size().
fvPatchField() [6/8]
fvPatchField (const fvPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping the given fvPatchField onto a new patch.
Definition at line 140 of file fvPatchField.C.
References fvPatchField< Type >::fvPatchField(), FieldMapper::hasUnmapped(), and Foam::notNull().
fvPatchField() [7/8]
fvPatchField (const fvPatchField< Type > & ptf)
Construct as copy.
Definition at line 165 of file fvPatchField.C.
References fvPatchField< Type >::fvPatchField().
fvPatchField() [8/8]
fvPatchField (const fvPatchField< Type > & ptf, const DimensionedField< Type, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 180 of file fvPatchField.C.
~fvPatchField()
virtual ~fvPatchField () inline virtual
Destructor.
Definition at line 300 of file fvPatchField.H.
References fvPatchField< Type >::assignable(), fvPatchField< Type >::calculatedType(), and fvPatchField< Type >::fixesValue().
Member Function Documentation
TypeName()
TypeName ("fvPatchField< Type >")
Runtime type information.
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (tmp , fvPatchField< Type > , patch , (const fvPatch &p, const DimensionedField< Type, volMesh > &iF) , (p, iF))
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (tmp , fvPatchField< Type > , patchMapper , (const fvPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const fvPatchFieldMapper &m) , (dynamic_cast< const fvPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (tmp , fvPatchField< Type > , dictionary , (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const dictionary &dict) , (p, iF, dict))
clone() [1/2]
virtual tmp<fvPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented in externalCoupledMixedFvPatchField< Type >, externalCoupledMixedFvPatchField< scalar >, omegaWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, externalCoupledTemperatureMixedFvPatchScalarField, porousBafflePressureFvPatchField< Type >, timeVaryingMappedFixedValueFvPatchField< Type >, codedMixedFvPatchField< Type >, turbulentInletFvPatchField< Type >, fixedProfileFvPatchField< Type >, waveTransmissiveFvPatchField< Type >, codedFixedValueFvPatchField< Type >, fanFvPatchField< Type >, mixedFvPatchField< Type >, mixedFvPatchField< scalar >, advectiveFvPatchField< Type >, mappedFixedValueFvPatchField< Type >, mappedFieldFvPatchField< Type >, kLowReWallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, fixedGradientFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, inletOutletFvPatchField< Type >, outletInletFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, fixedJumpAMIFvPatchField< Type >, fixedJumpAMIFvPatchField< scalar >, fixedJumpFvPatchField< Type >, mappedFixedPushedInternalValueFvPatchField< Type >, fixedJumpFvPatchField< scalar >, mappedFixedInternalValueFvPatchField< Type >, uniformFixedGradientFvPatchField< Type >, uniformFixedValueFvPatchField< Type >, outletMappedUniformInletFvPatchField< Type >, processorFvPatchField< Type >, fixedMeanFvPatchField< Type >, freestreamFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, partialSlipFvPatchField< Type >, cyclicAMIFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, cyclicFvPatchField< Type >, cyclicACMIFvPatchField< Type >, processorCyclicFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, fixedInternalValueFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, slicedFvPatchField< Type >, cyclicSlipFvPatchField< Type >, wedgeFvPatchField< Type >, genericFvPatchField< Type >, calculatedFvPatchField< Type >, emptyFvPatchField< Type >, symmetryFvPatchField< Type >, surfaceSlipDisplacementFvPatchField< Type >, coupledFvPatchField< Type >, extrapolatedCalculatedFvPatchField< Type >, totalFlowRateAdvectiveDiffusiveFvPatchScalarField, coupledFvPatchField< scalar >, zeroGradientFvPatchField< Type >, slipFvPatchField< Type >, nonuniformTransformCyclicFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, energyJumpFvPatchScalarField, energyJumpAMIFvPatchScalarField, transformFvPatchField< Type >, cellMotionFvPatchField< Type >, and basicSymmetryFvPatchField< Type >.
Definition at line 218 of file fvPatchField.H.
References fvPatchField< Type >::fvPatchField().
clone() [2/2]
virtual tmp<fvPatchField<Type> > clone (const DimensionedField< Type, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in externalCoupledMixedFvPatchField< Type >, timeVaryingMappedFixedValueFvPatchField< Type >, codedMixedFvPatchField< Type >, turbulentInletFvPatchField< Type >, fixedProfileFvPatchField< Type >, waveTransmissiveFvPatchField< Type >, codedFixedValueFvPatchField< Type >, fanFvPatchField< Type >, mappedFieldFvPatchField< Type >, mixedFvPatchField< Type >, advectiveFvPatchField< Type >, mappedFixedValueFvPatchField< Type >, fixedGradientFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, inletOutletFvPatchField< Type >, mappedFixedPushedInternalValueFvPatchField< Type >, outletInletFvPatchField< Type >, fixedJumpAMIFvPatchField< Type >, fixedJumpFvPatchField< Type >, mappedFixedInternalValueFvPatchField< Type >, uniformFixedGradientFvPatchField< Type >, uniformFixedValueFvPatchField< Type >, outletMappedUniformInletFvPatchField< Type >, processorFvPatchField< Type >, fixedMeanFvPatchField< Type >, freestreamFvPatchField< Type >, fixedValueFvPatchField< Type >, partialSlipFvPatchField< Type >, cyclicAMIFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, cyclicFvPatchField< Type >, cyclicACMIFvPatchField< Type >, processorCyclicFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, fixedInternalValueFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, surfaceSlipDisplacementFvPatchField< Type >, cyclicSlipFvPatchField< Type >, wedgeFvPatchField< Type >, genericFvPatchField< Type >, calculatedFvPatchField< Type >, emptyFvPatchField< Type >, symmetryFvPatchField< Type >, extrapolatedCalculatedFvPatchField< Type >, zeroGradientFvPatchField< Type >, slicedFvPatchField< Type >, slipFvPatchField< Type >, nonuniformTransformCyclicFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, coupledFvPatchField< Type >, directionMixedFvPatchField< Type >, cellMotionFvPatchField< Type >, basicSymmetryFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 232 of file fvPatchField.H.
References fvPatchField< Type >::New(), and fvPatchField< Type >::NewCalculatedType().
New() [1/4]
Foam::tmp< Foam::fvPatchField< Type > > New (const word & patchFieldType, const fvPatch & p, const DimensionedField< Type, volMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values)
Definition at line 92 of file fvPatchFieldNew.C.
References Foam::New().
Referenced by fvPatchField< Type >::clone(), nearWallDist::correct(), and fvPatchField< Type >::New().
New() [2/4]
Foam::tmp< Foam::fvPatchField< Type > > New (const word & patchFieldType, const word & actualPatchType, const fvPatch & p, const DimensionedField< Type, volMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values). Allows override of constraint type
Definition at line 30 of file fvPatchFieldNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, fvPatchField< Type >::New(), Foam::nl, p, and tmp< T >::ref().
New() [3/4]
Foam::tmp< Foam::fvPatchField< Type > > New (const fvPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const fvPatchFieldMapper & pfMapper) static
Return a pointer to a new patchField created on freestore from.
a given fvPatchField mapped onto a new patch
Definition at line 173 of file fvPatchFieldNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, Foam::nl, and p.
New() [4/4]
Foam::tmp< Foam::fvPatchField< Type > > New (const fvPatch & p, const DimensionedField< Type, volMesh > & iF, const dictionary & dict) static
Return a pointer to a new patchField created on freestore.
from dictionary
Definition at line 104 of file fvPatchFieldNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), InfoInFunction, dictionary::lookup(), fvPatchField< Type >::New(), Foam::nl, and p.
NewCalculatedType() [1/3]
Foam::tmp< Foam::fvPatchField< Type > > NewCalculatedType (const fvPatch & p) static
Return a pointer to a new calculatedFvPatchField created on.
freestore without setting patchField values
Definition at line 101 of file calculatedFvPatchField.C.
References p.
Referenced by calculatedFvPatchField< Type >::calculatedFvPatchField(), and fvPatchField< Type >::clone().
NewCalculatedType() [2/3]
static tmp<fvPatchField<Type> > NewCalculatedType (const fvPatchField< Type2 > &) static
Return a pointer to a new calculatedFvPatchField created on.
freestore without setting patchField values
calculatedType()
const Foam::word & calculatedType () static
Return the type of the calculated for of fvPatchField.
Definition at line 32 of file calculatedFvPatchField.C.
References calculatedFvPatchField< Type >::calculatedFvPatchField().
Referenced by fvPatchField< Type >::~fvPatchField().
fixesValue()
virtual bool fixesValue () const inline virtual
Return true if this patch field fixes a value.
Needed to check if a level has to be specified while solving Poissons equations.
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, cyclicACMIFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, calculatedFvPatchField< Type >, slicedFvPatchField< Type >, and directionMixedFvPatchField< Type >.
Definition at line 314 of file fvPatchField.H.
Referenced by Foam::adjustPhi(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), limitVelocity::correct(), limitTemperature::correct(), and fvPatchField< Type >::~fvPatchField().
assignable()
virtual bool assignable () const inline virtual
Return true if the value of the patch field.
is altered by assignment (the default)
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, uniformInletOutletFvPatchField< Type >, inletOutletFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, slipFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 321 of file fvPatchField.H.
Referenced by fvPatchField< Type >::~fvPatchField().
coupled()
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in processorFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicACMIFvPatchField< Type >, coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 327 of file fvPatchField.H.
References fvPatchField< Type >::db().
Referenced by fvMatrix< Type >::addBoundarySource(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), fvMatrix< Type >::DD(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), fvMatrix< Type >::H1(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), fvMatrix< Type >::relax(), snGradScheme< Type >::snGrad(), and regionSizeDistribution::write().
db()
const Foam::objectRegistry & db () const
Return local objectRegistry.
Definition at line 197 of file fvPatchField.C.
Referenced by fvPatchField< Type >::coupled(), basicThermo::lookupThermo(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs().
patch()
const fvPatch& patch () const inline
Return patch.
Definition at line 339 of file fvPatchField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::calculateTurbulenceFields(), omegaWallFunctionFvPatchScalarField::calculateTurbulenceFields(), fWallFunctionFvPatchScalarField::checkType(), v2WallFunctionFvPatchScalarField::checkType(), kLowReWallFunctionFvPatchScalarField::checkType(), epsilonWallFunctionFvPatchScalarField::checkType(), omegaWallFunctionFvPatchScalarField::checkType(), extendedCellToFaceStencil::collectData(), contactAngleForce::correct(), epsilonWallFunctionFvPatchScalarField::epsilon(), Foam::evaluateConstraintTypes(), epsilonWallFunctionFvPatchScalarField::G(), omegaWallFunctionFvPatchScalarField::G(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), mappedPatchFieldBase< Type >::mappedField(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvPatchField< Type >::NewCalculatedType(), omegaWallFunctionFvPatchScalarField::omega(), fvPatchField< Type >::operator*=(), fvPatchField< Type >::operator/=(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), energyJumpFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and regionSizeDistribution::write().
internalField()
const DimensionedField<Type, volMesh>& internalField () const inline
Return dimensioned internal field reference.
Definition at line 346 of file fvPatchField.H.
Referenced by epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), epsilonWallFunctionFvPatchScalarField::epsilonPatch(), basicThermo::lookupThermo(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::omegaPatch(), epsilonWallFunctionFvPatchScalarField::setMaster(), omegaWallFunctionFvPatchScalarField::setMaster(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs().
primitiveField()
const Field<Type>& primitiveField () const inline
Return internal field reference.
Definition at line 352 of file fvPatchField.H.
patchType() [1/2]
const word& patchType () const inline
Optional patch type.
Definition at line 358 of file fvPatchField.H.
Referenced by uniformInletOutletFvPatchField< Type >::uniformInletOutletFvPatchField().
patchType() [2/2]
word& patchType () inline
Optional patch type.
Definition at line 364 of file fvPatchField.H.
updated()
bool updated () const inline
Return true if the boundary condition has already been updated.
Definition at line 370 of file fvPatchField.H.
Referenced by energyJumpFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs().
manipulatedMatrix()
bool manipulatedMatrix () const inline
Return true if the matrix has already been manipulated.
Definition at line 376 of file fvPatchField.H.
References fvPatchField< Type >::autoMap(), fvPatchField< Type >::rmap(), and fvPatchField< Type >::snGrad().
Referenced by epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), and omegaWallFunctionFvPatchScalarField::manipulateMatrix().
autoMap()
void autoMap (const fvPatchFieldMapper & mapper) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, turbulentInletFvPatchField< Type >, timeVaryingMappedFixedValueFvPatchField< Type >, fixedGradientFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, fixedJumpAMIFvPatchField< Type >, fixedJumpAMIFvPatchField< scalar >, fixedJumpFvPatchField< Type >, fixedJumpFvPatchField< scalar >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, totalFlowRateAdvectiveDiffusiveFvPatchScalarField, mixedFixedValueSlipFvPatchField< Type >, genericFvPatchField< Type >, and emptyFvPatchField< Type >.
Definition at line 239 of file fvPatchField.C.
References FieldMapper::addressing(), FieldMapper::direct(), FieldMapper::directAddressing(), FieldMapper::distributed(), forAll, FieldMapper::hasUnmapped(), Foam::notNull(), fvPatchField< Type >::rmap(), List< Type >::setSize(), FieldMapper::size(), List< T >::size(), List< Type >::size(), and UList< T >::size().
Referenced by fvPatchField< Type >::manipulatedMatrix(), and fvPatchField< Type >::patchInternalField().
rmap()
void rmap (const fvPatchField< Type > & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Reimplemented in mixedFvPatchField< Type >, turbulentInletFvPatchField< Type >, timeVaryingMappedFixedValueFvPatchField< Type >, fixedGradientFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, fixedJumpFvPatchField< Type >, fixedJumpAMIFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, emptyFvPatchField< Type >, and genericFvPatchField< Type >.
Definition at line 301 of file fvPatchField.C.
Referenced by fvPatchField< Type >::autoMap(), fvPatchField< Type >::manipulatedMatrix(), meshToMesh::mapSrcToTgt(), and meshToMesh::mapTgtToSrc().
snGrad() [1/2]
Foam::tmp< Foam::Field< Type > > snGrad () const virtual
Return patch-normal gradient.
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, fixedGradientFvPatchField< Type >, partialSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, mixedFixedValueSlipFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, wedgeFvPatchField< Type >, slicedFvPatchField< Type >, coupledFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, coupledFvPatchField< scalar >, wedgeFvPatchField< Type >, basicSymmetryFvPatchField< Type >, zeroGradientFvPatchField< Type >, transformFvPatchField< Type >, basicSymmetryFvPatchField< Type >, wedgeFvPatchField< Type >, basicSymmetryFvPatchField< Type >, and symmetryPlaneFvPatchField< Type >.
Definition at line 216 of file fvPatchField.C.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), thermalBaffle::info(), fvPatchField< Type >::manipulatedMatrix(), snGradScheme< Type >::snGrad(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), gradientUnburntEnthalpyFvPatchScalarField::updateCoeffs(), gradientEnergyFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkFilmWallFunctionFvPatchScalarField::yPlus(), and nutUSpaldingWallFunctionFvPatchScalarField::yPlus().
snGrad() [2/2]
virtual tmp<Field<Type> > snGrad (const scalarField & deltaCoeffs) const inline virtual
Return patch-normal gradient for coupled-patches.
using the deltaCoeffs provided
Reimplemented in energyRegionCoupledFvPatchScalarField, processorFvPatchField< Type >, coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 406 of file fvPatchField.H.
References NotImplemented, fvPatchField< Type >::patchInternalField(), fvPatchField< Type >::updateCoeffs(), and fvPatchField< Type >::updateWeightedCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Sets Updated to true
Reimplemented in omegaWallFunctionFvPatchScalarField, epsilonWallFunctionFvPatchScalarField, turbulentInletFvPatchField< Type >, timeVaryingMappedFixedValueFvPatchField< Type >, porousBafflePressureFvPatchField< Type >, advectiveFvPatchField< Type >, codedMixedFvPatchField< Type >, fixedProfileFvPatchField< Type >, codedFixedValueFvPatchField< Type >, cyclicACMIFvPatchField< Type >, mappedFieldFvPatchField< Type >, fanFvPatchField< Type >, mappedFixedValueFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, kLowReWallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, inletOutletFvPatchField< Type >, mappedFixedPushedInternalValueFvPatchField< Type >, outletMappedUniformInletFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, outletInletFvPatchField< Type >, mappedFixedInternalValueFvPatchField< Type >, uniformFixedGradientFvPatchField< Type >, uniformFixedValueFvPatchField< Type >, fixedMeanFvPatchField< Type >, totalFlowRateAdvectiveDiffusiveFvPatchScalarField, emptyFvPatchField< Type >, slicedFvPatchField< Type >, energyJumpFvPatchScalarField, energyJumpAMIFvPatchScalarField, and cellMotionFvPatchField< Type >.
Definition at line 311 of file fvPatchField.C.
Referenced by fvPatchField< Type >::snGrad(), energyJumpFvPatchScalarField::updateCoeffs(), energyJumpAMIFvPatchScalarField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), surfaceNormalFixedValueFvPatchVectorField::updateCoeffs(), outletPhaseMeanVelocityFvPatchVectorField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), fixedPressureCompressibleDensityFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), swirlFlowRateInletVelocityFvPatchVectorField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), cylindricalInletVelocityFvPatchVectorField::updateCoeffs(), SRFFreestreamVelocityFvPatchVectorField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs().
updateWeightedCoeffs()
void updateWeightedCoeffs (const scalarField & weights) virtual
Update the coefficients associated with the patch field.
with a weight field (0..1). This weight field is ususally provided as the amount of geometric overlap for 'duplicate' patches. Sets Updated to true
Reimplemented in omegaWallFunctionFvPatchScalarField, and epsilonWallFunctionFvPatchScalarField.
Definition at line 318 of file fvPatchField.C.
Referenced by fvPatchField< Type >::snGrad().
patchInternalField() [1/2]
Foam::tmp< Foam::Field< Type > > patchInternalField () const virtual
Return internal field next to patch as patch field.
Reimplemented in slicedFvPatchField< Type >.
Definition at line 224 of file fvPatchField.C.
Referenced by isoSurface::adaptPatchFields(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField(), localMin< Type >::interpolate(), localMax< Type >::interpolate(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField(), fvPatchField< Type >::snGrad(), dynamicAlphaContactAngleFvPatchScalarField::theta(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), regionSizeDistribution::write(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().
patchInternalField() [2/2]
void patchInternalField (Field< Type > & pif) const virtual
Return internal field next to patch as patch field.
Reimplemented in slicedFvPatchField< Type >.
Definition at line 231 of file fvPatchField.C.
References fvPatchField< Type >::autoMap().
patchNeighbourField()
virtual tmp<Field<Type> > patchNeighbourField () const inline virtual
Return patchField on the opposite patch of a coupled patch.
Reimplemented in energyRegionCoupledFvPatchScalarField, cyclicACMIFvPatchField< Type >, processorFvPatchField< Type >, cyclicAMIFvPatchField< Type >, slicedFvPatchField< Type >, cyclicFvPatchField< Type >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
Definition at line 431 of file fvPatchField.H.
References fvPatchField< Type >::initEvaluate(), and NotImplemented.
Referenced by isoSurface::adaptPatchFields(), fvMatrix< Type >::addBoundarySource(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), localMin< Type >::interpolate(), localMax< Type >::interpolate(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), and regionSizeDistribution::write().
initEvaluate()
virtual void initEvaluate (const Pstream::commsTypes commsType = Pstream::blocking) inline virtual
Initialise the evaluation of the patch field.
Reimplemented in processorFvPatchField< Type >, slicedFvPatchField< Type >, coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 439 of file fvPatchField.H.
References UPstream::blocking, fvPatchField< Type >::evaluate(), and fvPatchField< Type >::valueInternalCoeffs().
Referenced by Foam::evaluateConstraintTypes(), and fvPatchField< Type >::patchNeighbourField().
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Evaluate the patch field, sets Updated to false.
Reimplemented in externalCoupledMixedFvPatchField< Type >, externalCoupledMixedFvPatchField< scalar >, mixedFvPatchField< Type >, mixedFvPatchField< scalar >, externalCoupledTemperatureMixedFvPatchScalarField, codedMixedFvPatchField< Type >, codedFixedValueFvPatchField< Type >, fixedGradientFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, kLowReWallFunctionFvPatchScalarField, v2WallFunctionFvPatchScalarField, partialSlipFvPatchField< Type >, fWallFunctionFvPatchScalarField, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, processorFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, slicedFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, wedgeFvPatchField< Type >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, kqRWallFunctionFvPatchField< Type >, symmetryPlaneFvPatchField< Type >, zeroGradientFvPatchField< Type >, wedgeFvPatchField< Type >, basicSymmetryFvPatchField< Type >, extrapolatedCalculatedFvPatchField< Type >, basicSymmetryFvPatchField< Type >, wedgeFvPatchField< Type >, basicSymmetryFvPatchField< Type >, and symmetryPlaneFvPatchField< Type >.
Definition at line 331 of file fvPatchField.C.
Referenced by fWallFunctionFvPatchScalarField::evaluate(), v2WallFunctionFvPatchScalarField::evaluate(), kLowReWallFunctionFvPatchScalarField::evaluate(), energyRegionCoupledFvPatchScalarField::evaluate(), Foam::evaluateConstraintTypes(), fvPatchField< Type >::initEvaluate(), fixedUnburntEnthalpyFvPatchScalarField::updateCoeffs(), gradientUnburntEnthalpyFvPatchScalarField::updateCoeffs(), fixedEnergyFvPatchScalarField::updateCoeffs(), and gradientEnergyFvPatchScalarField::updateCoeffs().
valueInternalCoeffs()
virtual tmp<Field<Type> > valueInternalCoeffs (const tmp< Field< scalar >> &) const inline virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the value of this patchField with given weights
Definition at line 454 of file fvPatchField.H.
References NotImplemented, and fvPatchField< Type >::valueBoundaryCoeffs().
Referenced by gaussConvectionScheme< Type >::fvmDiv(), and fvPatchField< Type >::initEvaluate().
valueBoundaryCoeffs()
virtual tmp<Field<Type> > valueBoundaryCoeffs (const tmp< Field< scalar >> &) const inline virtual
Return the matrix source coefficients corresponding to the.
evaluation of the value of this patchField with given weights
Definition at line 465 of file fvPatchField.H.
References fvPatchField< Type >::gradientInternalCoeffs(), and NotImplemented.
Referenced by gaussConvectionScheme< Type >::fvmDiv(), and fvPatchField< Type >::valueInternalCoeffs().
gradientInternalCoeffs() [1/2]
virtual tmp<Field<Type> > gradientInternalCoeffs () const inline virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the gradient of this patchField
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, fixedGradientFvPatchField< Type >, slicedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, emptyFvPatchField< Type >, genericFvPatchField< Type >, transformFvPatchField< Type >, zeroGradientFvPatchField< Type >, calculatedFvPatchField< Type >, transformFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 475 of file fvPatchField.H.
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), and fvPatchField< Type >::valueBoundaryCoeffs().
gradientInternalCoeffs() [2/2]
virtual tmp<Field<Type> > gradientInternalCoeffs (const scalarField & deltaCoeffs) const inline virtual
Return the matrix diagonal coefficients corresponding to the.
evaluation of the gradient of this coupled patchField using the deltaCoeffs provided
Reimplemented in coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 485 of file fvPatchField.H.
References fvPatchField< Type >::gradientBoundaryCoeffs(), and NotImplemented.
gradientBoundaryCoeffs() [1/2]
virtual tmp<Field<Type> > gradientBoundaryCoeffs () const inline virtual
Return the matrix source coefficients corresponding to the.
evaluation of the gradient of this patchField
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, fixedGradientFvPatchField< Type >, slicedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, emptyFvPatchField< Type >, genericFvPatchField< Type >, zeroGradientFvPatchField< Type >, calculatedFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 495 of file fvPatchField.H.
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), and fvPatchField< Type >::gradientInternalCoeffs().
gradientBoundaryCoeffs() [2/2]
virtual tmp<Field<Type> > gradientBoundaryCoeffs (const scalarField & deltaCoeffs) const inline virtual
Return the matrix source coefficients corresponding to the.
evaluation of the gradient of this coupled patchField using the deltaCoeffs provided
Reimplemented in coupledFvPatchField< Type >, and coupledFvPatchField< scalar >.
Definition at line 505 of file fvPatchField.H.
References fvPatchField< Type >::check(), fvPatchField< Type >::manipulateMatrix(), NotImplemented, fvPatchField< Type >::operator*=(), fvPatchField< Type >::operator+=(), fvPatchField< Type >::operator-=(), fvPatchField< Type >::operator/=(), fvPatchField< Type >::operator=(), fvPatchField< Type >::operator==(), fvPatchField< Type >::write(), and fvPatchField< Type >::writeEntryIfDifferent().
manipulateMatrix() [1/2]
void manipulateMatrix (fvMatrix< Type > & matrix) virtual
Manipulate matrix.
Reimplemented in cyclicACMIFvPatchField< Type >, and fixedInternalValueFvPatchField< Type >.
Definition at line 344 of file fvPatchField.C.
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), and omegaWallFunctionFvPatchScalarField::manipulateMatrix().
manipulateMatrix() [2/2]
void manipulateMatrix (fvMatrix< Type > & matrix, const scalarField & weights) virtual
Manipulate matrix with given weights.
Definition at line 352 of file fvPatchField.C.
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in externalCoupledMixedFvPatchField< Type >, externalCoupledMixedFvPatchField< scalar >, omegaWallFunctionFvPatchScalarField, mixedFvPatchField< Type >, mixedFvPatchField< scalar >, epsilonWallFunctionFvPatchScalarField, turbulentInletFvPatchField< Type >, timeVaryingMappedFixedValueFvPatchField< Type >, externalCoupledTemperatureMixedFvPatchScalarField, cyclicACMIFvPatchField< Type >, porousBafflePressureFvPatchField< Type >, fixedGradientFvPatchField< Type >, advectiveFvPatchField< Type >, energyRegionCoupledFvPatchScalarField, codedMixedFvPatchField< Type >, waveTransmissiveFvPatchField< Type >, codedFixedValueFvPatchField< Type >, cyclicAMIFvPatchField< Type >, fixedProfileFvPatchField< Type >, coupledFvPatchField< Type >, cyclicFvPatchField< Type >, coupledFvPatchField< scalar >, mappedFieldFvPatchField< Type >, fanFvPatchField< Type >, mappedFixedValueFvPatchField< Type >, partialSlipFvPatchField< Type >, kLowReWallFunctionFvPatchScalarField, directionMixedFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, v2WallFunctionFvPatchScalarField, fWallFunctionFvPatchScalarField, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, fixedJumpFvPatchField< Type >, fixedJumpFvPatchField< scalar >, fixedJumpAMIFvPatchField< Type >, fixedJumpAMIFvPatchField< scalar >, inletOutletFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, mappedFixedPushedInternalValueFvPatchField< Type >, outletMappedUniformInletFvPatchField< Type >, uniformJumpFvPatchField< Type >, uniformJumpAMIFvPatchField< Type >, outletInletFvPatchField< Type >, mappedFixedInternalValueFvPatchField< Type >, genericFvPatchField< Type >, uniformFixedGradientFvPatchField< Type >, freestreamFvPatchField< Type >, uniformFixedValueFvPatchField< Type >, calculatedFvPatchField< Type >, totalFlowRateAdvectiveDiffusiveFvPatchScalarField, fixedMeanFvPatchField< Type >, kqRWallFunctionFvPatchField< Type >, surfaceSlipDisplacementFvPatchField< Type >, energyJumpFvPatchScalarField, energyJumpAMIFvPatchScalarField, and cellMotionFvPatchField< Type >.
Definition at line 362 of file fvPatchField.C.
References Foam::nl, Foam::type(), fvPatchField< Type >::writeEntryIfDifferent(), and Ostream::writeKeyword().
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs(), fvPatchField< Type >::operator==(), noSlipFvPatchVectorField::write(), surfaceSlipDisplacementFvPatchField< Type >::write(), alphatPhaseChangeWallFunctionFvPatchScalarField::write(), inclinedFilmNusseltInletVelocityFvPatchVectorField::write(), movingWallVelocityFvPatchVectorField::write(), nutUWallFunctionFvPatchScalarField::write(), atmBoundaryLayerInletEpsilonFvPatchScalarField::write(), atmBoundaryLayerInletKFvPatchScalarField::write(), atmBoundaryLayerInletVelocityFvPatchVectorField::write(), interstitialInletVelocityFvPatchVectorField::write(), alphaFixedPressureFvPatchScalarField::write(), translatingWallVelocityFvPatchVectorField::write(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::write(), nutkFilmWallFunctionFvPatchScalarField::write(), mappedVelocityFluxFixedValueFvPatchField::write(), nutUSpaldingWallFunctionFvPatchScalarField::write(), filmPyrolysisTemperatureCoupledFvPatchScalarField::write(), filmPyrolysisVelocityCoupledFvPatchVectorField::write(), mappedFlowRateFvPatchVectorField::write(), SRFWallVelocityFvPatchVectorField::write(), freestreamPressureFvPatchScalarField::write(), nutUTabulatedWallFunctionFvPatchScalarField::write(), surfaceNormalFixedValueFvPatchVectorField::write(), variableHeightFlowRateFvPatchScalarField::write(), pressureInletVelocityFvPatchVectorField::write(), outletPhaseMeanVelocityFvPatchVectorField::write(), rotatingPressureInletOutletVelocityFvPatchVectorField::write(), nutWallFunctionFvPatchScalarField::write(), fixedPressureCompressibleDensityFvPatchScalarField::write(), alphatWallFunctionFvPatchScalarField::write(), swirlFlowRateInletVelocityFvPatchVectorField::write(), cylindricalInletVelocityFvPatchVectorField::write(), convectiveHeatTransferFvPatchScalarField::write(), turbulentIntensityKineticEnergyInletFvPatchScalarField::write(), rotatingWallVelocityFvPatchVectorField::write(), fluxCorrectedVelocityFvPatchVectorField::write(), wallHeatTransferFvPatchScalarField::write(), alphatFilmWallFunctionFvPatchScalarField::write(), nutkRoughWallFunctionFvPatchScalarField::write(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::write(), turbulentMixingLengthFrequencyInletFvPatchScalarField::write(), SRFFreestreamVelocityFvPatchVectorField::write(), nutkAtmRoughWallFunctionFvPatchScalarField::write(), pressureNormalInletOutletVelocityFvPatchVectorField::write(), pressureInletOutletParSlipVelocityFvPatchVectorField::write(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), pressureInletOutletVelocityFvPatchVectorField::write(), totalTemperatureFvPatchScalarField::write(), waveSurfacePressureFvPatchScalarField::write(), flowRateInletVelocityFvPatchVectorField::write(), prghTotalHydrostaticPressureFvPatchScalarField::write(), SRFVelocityFvPatchVectorField::write(), nutURoughWallFunctionFvPatchScalarField::write(), inletOutletTotalTemperatureFvPatchScalarField::write(), energyRegionCoupledFvPatchScalarField::write(), pressureDirectedInletVelocityFvPatchVectorField::write(), prghPressureFvPatchScalarField::write(), uniformTotalPressureFvPatchScalarField::write(), pressureDirectedInletOutletVelocityFvPatchVectorField::write(), fixedNormalInletOutletVelocityFvPatchVectorField::write(), uniformDensityHydrostaticPressureFvPatchScalarField::write(), supersonicFreestreamFvPatchVectorField::write(), prghTotalPressureFvPatchScalarField::write(), filmHeightInletVelocityFvPatchVectorField::write(), syringePressureFvPatchScalarField::write(), phaseHydrostaticPressureFvPatchScalarField::write(), plenumPressureFvPatchScalarField::write(), and totalPressureFvPatchScalarField::write().
writeEntryIfDifferent()
void writeEntryIfDifferent (Ostream & os, const word & entryName, const EntryType & value1, const EntryType & value2) const
Helper function to write the keyword and entry only if the.
values are not equal. The value is then output as value2
Definition at line 377 of file fvPatchField.C.
References Foam::nl, and Ostream::writeKeyword().
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs(), and fvPatchField< Type >::write().
check()
void check (const fvPatchField< Type > & ptf) const
Check fvPatchField<Type> against given fvPatchField<Type>
Definition at line 204 of file fvPatchField.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator=() [1/3]
void operator= (const UList< Type > & ul) virtual
Reimplemented in mixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 395 of file fvPatchField.C.
Referenced by alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), externalWallHeatFluxTemperatureFvPatchScalarField::externalWallHeatFluxTemperatureFvPatchScalarField(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), fvPatchField< Type >::gradientBoundaryCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField(), pressureInletVelocityFvPatchVectorField::operator=(), pressureInletOutletParSlipVelocityFvPatchVectorField::operator=(), pressureInletOutletVelocityFvPatchVectorField::operator=(), pressureDirectedInletVelocityFvPatchVectorField::operator=(), fixedNormalInletOutletVelocityFvPatchVectorField::operator=(), filmHeightInletVelocityFvPatchVectorField::operator=(), thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField(), turbulentHeatFluxTemperatureFvPatchScalarField::turbulentHeatFluxTemperatureFvPatchScalarField(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField(), turbulentMixingLengthFrequencyInletFvPatchScalarField::turbulentMixingLengthFrequencyInletFvPatchScalarField(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::turbulentTemperatureRadCoupledMixedFvPatchScalarField(), surfaceNormalFixedValueFvPatchVectorField::updateCoeffs(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
operator=() [2/3]
void operator= (const fvPatchField< Type > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, uniformInletOutletFvPatchField< Type >, fixedValueFvPatchField< Type >, mixedFixedValueSlipFvPatchField< Type >, inletOutletFvPatchField< Type >, and transformFvPatchField< Type >.
Definition at line 405 of file fvPatchField.C.
operator+=() [1/3]
void operator+= (const fvPatchField< Type > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 416 of file fvPatchField.C.
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator-=() [1/3]
void operator-= (const fvPatchField< Type > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 427 of file fvPatchField.C.
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator*=() [1/3]
void operator*= (const fvPatchField< scalar > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 438 of file fvPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and fvPatchField< Type >::patch().
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator/=() [1/3]
void operator/= (const fvPatchField< scalar > & ptf) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 455 of file fvPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and fvPatchField< Type >::patch().
Referenced by fvPatchField< Type >::gradientBoundaryCoeffs().
operator+=() [2/3]
void operator+= (const Field< Type > & tf) virtual
Reimplemented in mixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, slicedFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 471 of file fvPatchField.C.
References tf.
operator-=() [2/3]
void operator-= (const Field< Type > & tf) virtual
Reimplemented in mixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, directionMixedFvPatchField< Type >, slicedFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 481 of file fvPatchField.C.
References tf.
operator*=() [2/3]
void operator*= (const Field< scalar > & tf) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 491 of file fvPatchField.C.
References tf.
operator/=() [2/3]
void operator/= (const Field< scalar > & tf) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 501 of file fvPatchField.C.
References tf.
operator=() [3/3]
void operator= (const Type & t) virtual
Reimplemented in mixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 511 of file fvPatchField.C.
operator+=() [3/3]
void operator+= (const Type & t) virtual
Reimplemented in mixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 521 of file fvPatchField.C.
operator-=() [3/3]
void operator-= (const Type & t) virtual
Reimplemented in mixedFvPatchField< Type >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 531 of file fvPatchField.C.
operator*=() [3/3]
void operator*= (const scalar s) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 541 of file fvPatchField.C.
References s().
operator/=() [3/3]
void operator/= (const scalar s) virtual
Reimplemented in mixedFvPatchField< Type >, mixedFvPatchField< scalar >, partialSlipFvPatchField< Type >, fixedNormalSlipFvPatchField< Type >, slicedFvPatchField< Type >, directionMixedFvPatchField< Type >, fixedValueFvPatchField< Type >, fixedValueFvPatchField< scalar >, and mixedFixedValueSlipFvPatchField< Type >.
Definition at line 551 of file fvPatchField.C.
References s().
operator==() [1/3]
void operator== (const fvPatchField< Type > & ptf) virtual
Definition at line 561 of file fvPatchField.C.
Referenced by epsilonWallFunctionFvPatchScalarField::epsilonWallFunctionFvPatchScalarField(), fvPatchField< Type >::gradientBoundaryCoeffs(), and omegaWallFunctionFvPatchScalarField::omegaWallFunctionFvPatchScalarField().
operator==() [2/3]
void operator== (const Field< Type > & tf) virtual
Definition at line 571 of file fvPatchField.C.
References tf.
operator==() [3/3]
void operator== (const Type & t) virtual
Definition at line 581 of file fvPatchField.C.
References IOstream::check(), and fvPatchField< Type >::write().
NewCalculatedType() [3/3]
Foam::tmp<Foam::fvPatchField<Type> > NewCalculatedType (const fvPatchField< Type2 > & pf)
Definition at line 133 of file calculatedFvPatchField.C.
References fvPatchField< Type >::patch(), and calculatedFvPatchField< Type >::valueInternalCoeffs().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const fvPatchField< Type > &) friend
Referenced by greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField(), phaseHydrostaticPressureFvPatchScalarField::operator=(), and wideBandDiffusiveRadiationMixedFvPatchScalarField::wideBandDiffusiveRadiationMixedFvPatchScalarField().
Member Data Documentation
disallowGenericFvPatchField
int disallowGenericFvPatchField static
Debug switch to disallow the use of genericFvPatchField.
Definition at line 118 of file fvPatchField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchField.H
src/finiteVolume/fields/fvPatchFields/basic/calculated/calculatedFvPatchField.C
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchField.C
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchFieldNew.C
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchFields.C