OpenFOAM: fvMatrix< Type > Class Template Reference
fvMatrix< Type > Class Template Reference
A special matrix type and solver, designed for finite volume solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Classes
class fvSolver
Solver class returned by the solver function.
Public Types
typedef GeometricField< Type, fvsPatchField, surfaceMesh > * surfaceTypeFieldPtr
Declare return type of the faceFluxCorrectionPtr() function.
Public Member Functions
ClassName ("fvMatrix")
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > &, const dimensionSet &)
Construct given a field to solve for.
fvMatrix (const fvMatrix< Type > &)
Construct as copy.
fvMatrix (const tmp< fvMatrix< Type >> &)
Construct as copy of tmp<fvMatrix<Type>> deleting argument.
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > &, Istream &)
Construct from Istream given field to solve for.
virtual ~fvMatrix ()
Destructor.
const GeometricField< Type, fvPatchField, volMesh > & psi () const
const dimensionSet & dimensions () const
Field< Type > & source ()
const Field< Type > & source () const
FieldField< Field, Type > & internalCoeffs ()
fvBoundary scalar field containing pseudo-matrix coeffs
FieldField< Field, Type > & boundaryCoeffs ()
fvBoundary scalar field containing pseudo-matrix coeffs
surfaceTypeFieldPtr & faceFluxCorrectionPtr ()
Return pointer to face-flux non-orthogonal correction field.
void setValues (const labelUList &cells, const UList< Type > &values)
Set solution in given cells to the specified values.
void setValues (const labelUList &cells, const UIndirectList< Type > &values)
Set solution in given cells to the specified values.
void setReference (const label celli, const Type &value, const bool forceReference=false)
Set reference level for solution.
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Set reference level for a component of the solution.
void relax (const scalar alpha)
Relax matrix (for steady-state solution).
void relax ()
Relax matrix (for steady-state solution).
void boundaryManipulate (typename GeometricField< Type, fvPatchField, volMesh >::Boundary &values)
Manipulate based on a boundary field.
autoPtr< fvSolver > solver (const dictionary &)
Construct and return the solver.
autoPtr< fvSolver > solver ()
Construct and return the solver.
SolverPerformance< Type > solve (const dictionary &)
Solve segregated or coupled returning the solution statistics.
SolverPerformance< Type > solveSegregated (const dictionary &)
Solve segregated returning the solution statistics.
SolverPerformance< Type > solveCoupled (const dictionary &)
Solve coupled returning the solution statistics.
SolverPerformance< Type > solve ()
Solve returning the solution statistics.
tmp< Field< Type > > residual () const
Return the matrix residual.
tmp< scalarField > D () const
Return the matrix scalar diagonal.
tmp< Field< Type > > DD () const
Return the matrix Type diagonal.
tmp< volScalarField > A () const
Return the central coefficient.
tmp< GeometricField< Type, fvPatchField, volMesh > > H () const
Return the H operation source.
tmp< volScalarField > H1 () const
Return H(1)
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux () const
Return the face-flux field from the matrix.
void operator= (const fvMatrix< Type > &)
void operator= (const tmp< fvMatrix< Type >> &)
void negate ()
void operator+= (const fvMatrix< Type > &)
void operator+= (const tmp< fvMatrix< Type >> &)
void operator-= (const fvMatrix< Type > &)
void operator-= (const tmp< fvMatrix< Type >> &)
void operator+= (const DimensionedField< Type, volMesh > &)
void operator+= (const tmp< DimensionedField< Type, volMesh >> &)
void operator+= (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
void operator-= (const DimensionedField< Type, volMesh > &)
void operator-= (const tmp< DimensionedField< Type, volMesh >> &)
void operator-= (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator+= (const zero &)
void operator-= (const zero &)
void operator*= (const volScalarField::Internal &)
void operator*= (const tmp< volScalarField::Internal > &)
void operator*= (const tmp< volScalarField > &)
void operator*= (const dimensioned< scalar > &)
template<>
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
template<>
Foam::autoPtr< Foam::fvMatrix< Foam::scalar >::fvSolver > solver (const dictionary &solverControls)
template<>
Foam::solverPerformance solveSegregated (const dictionary &solverControls)
template<>
Foam::tmp< Foam::scalarField > residual () const
template<>
Foam::tmp< Foam::volScalarField > H () const
template<>
Foam::tmp< Foam::volScalarField > H1 () const
template<>
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
template<>
autoPtr< fvMatrix< scalar >::fvSolver > solver (const dictionary &)
template<>
solverPerformance solveSegregated (const dictionary &)
template<>
tmp< scalarField > residual () const
template<>
tmp< volScalarField > H () const
template<>
tmp< volScalarField > H1 () const
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from lduMatrix
ClassName ("lduMatrix")
lduMatrix (const lduMesh &)
Construct given an LDU addressed mesh.
lduMatrix (const lduMatrix &)
Construct as copy.
lduMatrix (lduMatrix &, bool reuse)
Construct as copy or re-use as specified.
lduMatrix (const lduMesh &, Istream &)
Construct given an LDU addressed mesh and an Istream.
~lduMatrix ()
Destructor.
const lduMesh & mesh () const
Return the LDU mesh from which the addressing is obtained.
const lduAddressing & lduAddr () const
Return the LDU addressing.
const lduSchedule & patchSchedule () const
Return the patch evaluation schedule.
scalarField & lower ()
scalarField & diag ()
scalarField & upper ()
scalarField & lower (const label size)
scalarField & diag (const label nCoeffs)
scalarField & upper (const label nCoeffs)
const scalarField & lower () const
const scalarField & diag () const
const scalarField & upper () const
bool hasDiag () const
bool hasUpper () const
bool hasLower () const
bool diagonal () const
bool symmetric () const
bool asymmetric () const
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (scalarField &sumOff) const
void Amul (scalarField &, const tmp< scalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix multiplication with updated interfaces.
void Tmul (scalarField &, const tmp< scalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix transpose multiplication with updated interfaces.
void sumA (scalarField &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &) const
Sum the coefficients on each row of the matrix.
void residual (scalarField &rA, const scalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
tmp< scalarField > residual (const scalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
void initMatrixInterfaces (const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const scalarField &psiif, scalarField &result, const direction cmpt) const
Initialise the update of interfaced interfaces.
void updateMatrixInterfaces (const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const scalarField &psiif, scalarField &result, const direction cmpt) const
Update interfaced interfaces for matrix operations.
template<class Type >
tmp< Field< Type > > H (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > H (const tmp< Field< Type >> &) const
tmp< scalarField > H1 () const
template<class Type >
tmp< Field< Type > > faceH (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > faceH (const tmp< Field< Type >> &) const
InfoProxy< lduMatrix > info () const
Return info proxy.
void operator= (const lduMatrix &)
void negate ()
void operator+= (const lduMatrix &)
void operator-= (const lduMatrix &)
void operator*= (const scalarField &)
void operator*= (scalar)
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type >> &tpsi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type >> &tpsi) const
Protected Member Functions
template<class Type2 >
void addToInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
Add patch contribution to internal field.
template<class Type2 >
void addToInternalField (const labelUList &addr, const tmp< Field< Type2 >> &tpf, Field< Type2 > &intf) const
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
Subtract patch contribution from internal field.
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const tmp< Field< Type2 >> &tpf, Field< Type2 > &intf) const
void addBoundaryDiag (scalarField &diag, const direction cmpt) const
void addCmptAvBoundaryDiag (scalarField &diag) const
void addBoundarySource (Field< Type > &source, const bool couples=true) const
template<template< class > class ListType>
void setValuesFromList (const labelUList &cells, const ListType< Type > &values)
Set solution in given cells to the specified values.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Friends
class fvSolver
Declare friendship with the fvSolver class.
tmp< GeometricField< Type, fvPatchField, volMesh > > operator & (const fvMatrix< Type > &, const DimensionedField< Type, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > operator & (const fvMatrix< Type > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
tmp< GeometricField< Type, fvPatchField, volMesh > > operator & (const tmp< fvMatrix< Type >> &, const DimensionedField< Type, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > operator & (const tmp< fvMatrix< Type >> &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
Ostream & operator (Ostream &, const fvMatrix< Type > &)
Detailed Description
template<class Type>
class Foam::fvMatrix< Type >
A special matrix type and solver, designed for finite volume solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Source files
fvMatrix.H
fvMatrix.C
fvMatrixSolve.C
fvScalarMatrix.C
Definition at line 71 of file fvPatchField.H.
Member Typedef Documentation
surfaceTypeFieldPtr
typedef GeometricField<Type, fvsPatchField, surfaceMesh>* surfaceTypeFieldPtr
Declare return type of the faceFluxCorrectionPtr() function.
Definition at line 318 of file fvMatrix.H.
Constructor & Destructor Documentation
fvMatrix() [1/4]
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > & psi, const dimensionSet & ds)
Construct given a field to solve for.
Definition at line 268 of file fvMatrix.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::endl(), regIOobject::eventNo(), forAll, InfoInFunction, DimensionedField< Type, GeoMesh >::mesh(), patchi, and Foam::Zero.
Referenced by fvMatrix< Type >::fvMatrix(), fvMatrix< Type >::fvSolver::fvSolver(), and fvMatrix< Type >::setValuesFromList().
fvMatrix() [2/4]
fvMatrix (const fvMatrix< Type > & fvm)
Construct as copy.
Definition at line 322 of file fvMatrix.C.
References Foam::endl(), and InfoInFunction.
fvMatrix() [3/4]
fvMatrix (const tmp< fvMatrix< Type >> & tfvm)
Construct as copy of tmp<fvMatrix<Type>> deleting argument.
Definition at line 352 of file fvMatrix.C.
References Foam::endl(), fvMatrix< Type >::fvMatrix(), and InfoInFunction.
fvMatrix() [4/4]
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > & psi, Istream & is)
Construct from Istream given field to solve for.
Definition at line 408 of file fvMatrix.C.
References Foam::endl(), forAll, InfoInFunction, DimensionedField< Type, GeoMesh >::mesh(), patchi, and Foam::Zero.
~fvMatrix()
~fvMatrix () virtual
Destructor.
Definition at line 455 of file fvMatrix.C.
References Foam::endl(), InfoInFunction, and fvMatrix< Type >::setValues().
Referenced by fvMatrix< Type >::fvSolver::fvSolver().
Member Function Documentation
addToInternalField() [1/2]
void addToInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Add patch contribution to internal field.
Definition at line 38 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, List< Type >::size(), and UList< T >::size().
Referenced by fvMatrix< Type >::DD(), and fvMatrix< Type >::H1().
addToInternalField() [2/2]
void addToInternalField (const labelUList & addr, const tmp< Field< Type2 >> & tpf, Field< Type2 > & intf) const protected
Definition at line 61 of file fvMatrix.C.
References fvMatrix< Type >::subtractFromInternalField().
subtractFromInternalField() [1/2]
void subtractFromInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Subtract patch contribution from internal field.
Definition at line 75 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, List< Type >::size(), and UList< T >::size().
Referenced by fvMatrix< Type >::addToInternalField().
subtractFromInternalField() [2/2]
void subtractFromInternalField (const labelUList & addr, const tmp< Field< Type2 >> & tpf, Field< Type2 > & intf) const protected
Definition at line 98 of file fvMatrix.C.
References fvMatrix< Type >::addBoundaryDiag().
addBoundaryDiag()
void addBoundaryDiag (scalarField & diag, const direction cmpt) const protected
Definition at line 111 of file fvMatrix.C.
References Foam::component(), forAll, and patchi.
Referenced by fvMatrix< Type >::H(), fvMatrix< Type >::residual(), and fvMatrix< Type >::subtractFromInternalField().
addCmptAvBoundaryDiag()
void addCmptAvBoundaryDiag (scalarField & diag) const protected
Definition at line 129 of file fvMatrix.C.
References fvMatrix< Type >::addBoundarySource(), Foam::cmptAv(), forAll, and patchi.
Referenced by fvMatrix< Type >::D(), and fvMatrix< Type >::H().
addBoundarySource()
void addBoundarySource (Field< Type > & source, const bool couples = true) const protected
Definition at line 145 of file fvMatrix.C.
References Foam::cmptMultiply(), fvPatchField< Type >::coupled(), forAll, patchi, fvPatchField< Type >::patchNeighbourField(), and fvMatrix< Type >::setValuesFromList().
Referenced by fvMatrix< Type >::addCmptAvBoundaryDiag(), fvMatrix< Type >::H(), and fvMatrix< Type >::residual().
setValuesFromList()
void setValuesFromList (const labelUList & cells, const ListType< Type > & values) protected
Set solution in given cells to the specified values.
Definition at line 178 of file fvMatrix.C.
References polyMesh::boundaryMesh(), Foam::constant::universal::c, cells, primitiveMesh::cells(), Foam::diag(), forAll, fvMatrix< Type >::fvMatrix(), primitiveMesh::isInternalFace(), mesh, fvMesh::neighbour(), fvMesh::owner(), patchi, primitiveFieldRef(), psi, polyBoundaryMesh::whichPatch(), and Foam::Zero.
Referenced by fvMatrix< Type >::addBoundarySource(), and fvMatrix< Type >::setValues().
ClassName()
ClassName ("fvMatrix< Type >")
Referenced by fvMatrix< Type >::fvSolver::fvSolver().
psi()
const GeometricField<Type, fvPatchField, volMesh>& psi () const inline
Definition at line 281 of file fvMatrix.H.
Referenced by MRFZone::addCoriolis(), explicitPorositySource::addSup(), interRegionExplicitPorositySource::addSup(), radialActuationDiskSource::addSup(), interRegionHeatTransferModel::addSup(), SemiImplicitSource< Type >::addSup(), actuationDiskSource::addSup(), solidificationMeltingSource::addSup(), rotorDiskSource::addSup(), Foam::checkMethod(), optionList::constrain(), fixedCoeff::correct(), powerLaw::correct(), DarcyForchheimer::correct(), fvMatrix< Type >::operator+=(), and fvMatrix< Type >::operator-=().
dimensions()
const dimensionSet& dimensions () const inline
Definition at line 286 of file fvMatrix.H.
Referenced by explicitPorositySource::addSup(), meanVelocityForce::addSup(), interRegionExplicitPorositySource::addSup(), SemiImplicitSource< Type >::addSup(), rotorDiskSource::addSup(), Foam::checkMethod(), fixedCoeff::correct(), powerLaw::correct(), DarcyForchheimer::correct(), and fvMatrix< Type >::flux().
source() [1/2]
Field<Type>& source () inline
Definition at line 291 of file fvMatrix.H.
Referenced by MRFZone::addCoriolis(), interRegionExplicitPorositySource::addSup(), radialActuationDiskSource::addSup(), actuationDiskSource::addSup(), solidificationMeltingSource::addSup(), effectivenessHeatExchangerSource::addSup(), fixedCoeff::correct(), DarcyForchheimer::correct(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), fvMatrix< Type >::operator+=(), fvMatrix< Type >::operator-=(), fvMatrix< Type >::relax(), fvMatrix< Type >::setReference(), ThermoCloud< Foam::DSMCCloud >::Sh(), ReactingCloud< Foam::DSMCCloud >::Srho(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::SU(), and ReactingCloud< Foam::DSMCCloud >::SYi().
source() [2/2]
const Field<Type>& source () const inline
Definition at line 296 of file fvMatrix.H.
References fvMatrix< Type >::boundaryCoeffs(), and fvMatrix< Type >::internalCoeffs().
internalCoeffs()
FieldField<Field, Type>& internalCoeffs () inline
fvBoundary scalar field containing pseudo-matrix coeffs
for internal cells
Definition at line 303 of file fvMatrix.H.
Referenced by gaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), and fvMatrix< Type >::source().
boundaryCoeffs()
FieldField<Field, Type>& boundaryCoeffs () inline
fvBoundary scalar field containing pseudo-matrix coeffs
for boundary cells
Definition at line 310 of file fvMatrix.H.
Referenced by gaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), and fvMatrix< Type >::source().
faceFluxCorrectionPtr()
surfaceTypeFieldPtr& faceFluxCorrectionPtr () inline
Return pointer to face-flux non-orthogonal correction field.
Definition at line 321 of file fvMatrix.H.
References fvMatrix< Type >::A(), Foam::constant::atomic::alpha, fvMatrix< Type >::boundaryManipulate(), cells, Foam::checkMethod(), Foam::correction(), fvMatrix< Type >::D(), fvMatrix< Type >::DD(), fvMatrix< Type >::flux(), fvMatrix< Type >::H(), fvMatrix< Type >::H1(), fvMatrix< Type >::negate(), fvMatrix< Type >::operator*=(), fvMatrix< Type >::operator+=(), fvMatrix< Type >::operator-=(), fvMatrix< Type >::operator=(), patchi, fvMatrix< Type >::relax(), fvMatrix< Type >::residual(), fvMatrix< Type >::setComponentReference(), fvMatrix< Type >::setReference(), fvMatrix< Type >::setValues(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solver(), and fvMatrix< Type >::solveSegregated().
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacian().
setValues() [1/2]
void setValues (const labelUList & cells, const UList< Type > & values)
Set solution in given cells to the specified values.
and eliminate the corresponding equations from the matrix.
Definition at line 474 of file fvMatrix.C.
References fvMatrix< Type >::setValuesFromList().
Referenced by FixedValueConstraint< Type >::constrain(), fixedTemperatureConstraint::constrain(), fvMatrix< Type >::faceFluxCorrectionPtr(), fixedInternalValueFvPatchField< Type >::manipulateMatrix(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), and fvMatrix< Type >::~fvMatrix().
setValues() [2/2]
void setValues (const labelUList & cells, const UIndirectList< Type > & values)
Set solution in given cells to the specified values.
and eliminate the corresponding equations from the matrix.
Definition at line 485 of file fvMatrix.C.
References fvMatrix< Type >::setReference(), and fvMatrix< Type >::setValuesFromList().
setReference()
void setReference (const label celli, const Type & value, const bool forceReference = false)
Set reference level for solution.
Definition at line 496 of file fvMatrix.C.
References lduMatrix::diag(), and fvMatrix< Type >::source().
Referenced by Foam::CorrectPhi(), fvMatrix< Type >::faceFluxCorrectionPtr(), and fvMatrix< Type >::setValues().
setComponentReference() [1/3]
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Set reference level for a component of the solution.
on a given patch face
Definition at line 33 of file fvMatrixSolve.C.
References Foam::diag(), patchi, and fvMatrix< Type >::solve().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr().
relax() [1/2]
void relax (const scalar alpha)
Relax matrix (for steady-state solution).
alpha = 1 : diagonally equal alpha < 1 : diagonally dominant alpha = 0 : do nothing Note: Requires positive diagonal.
Definition at line 511 of file fvMatrix.C.
References Foam::constant::atomic::alpha, Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), Foam::component(), fvPatchField< Type >::coupled(), fvMatrix< Type >::D(), lduMatrix::diag(), Foam::endl(), forAll, InfoInFunction, lduMatrix::lduAddr(), Foam::mag(), Foam::max(), UPstream::msgType(), Foam::nl, lduAddressing::patchAddr(), patchi, Foam::reduce(), Foam::returnReduce(), List< T >::size(), List< Type >::size(), fvMatrix< Type >::source(), and lduMatrix::sumMagOffDiag().
Referenced by dynamicLagrangian< BasicTurbulenceModel >::correct(), thixotropicViscosity::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), scalarTransport::execute(), and thermalBaffle::solveEnergy().
relax() [2/2]
void relax ()
Relax matrix (for steady-state solution).
alpha is read from controlDict
Definition at line 662 of file fvMatrix.C.
References fvMatrix< Type >::boundaryManipulate(), and Foam::name().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr().
boundaryManipulate()
void boundaryManipulate (typename GeometricField< Type, fvPatchField, volMesh >::Boundary & values)
Manipulate based on a boundary field.
Definition at line 679 of file fvMatrix.C.
References forAll, and patchi.
Referenced by kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), fvMatrix< Type >::faceFluxCorrectionPtr(), and fvMatrix< Type >::relax().
solver() [1/4]
autoPtr<fvSolver> solver (const dictionary &)
Construct and return the solver.
Use the given solver controls
solver() [2/4]
Foam::autoPtr< typename Foam::fvMatrix< Type >::fvSolver > solver ()
Construct and return the solver.
Solver controls read from fvSolution
Definition at line 280 of file fvMatrixSolve.C.
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr(), and fvMatrix< Type >::setComponentReference().
solve() [1/2]
Foam::SolverPerformance< Type > solve (const dictionary & solverControls)
Solve segregated or coupled returning the solution statistics.
Use the given solver controls
Definition at line 57 of file fvMatrixSolve.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::Info, dictionary::lookupOrDefault(), messageStream::masterStream(), mesh, dictionary::readIfPresent(), fvMatrix< Type >::solveSegregated(), and Foam::type().
Referenced by Implicit< CloudType >::cacheFields(), Foam::checkMethod(), dynamicLagrangian< BasicTurbulenceModel >::correct(), Foam::CorrectPhi(), scalarTransport::execute(), thermalBaffle::solveEnergy(), and kinematicSingleLayer::solveThickness().
solveSegregated() [1/3]
Foam::SolverPerformance< Type > solveSegregated (const dictionary & solverControls)
Solve segregated returning the solution statistics.
Use the given solver controls
Definition at line 104 of file fvMatrixSolve.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Field< Type >::component(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::diag(), Foam::endl(), Foam::Info, messageStream::masterStream(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), Foam::New(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), SolverPerformance< Type >::print(), psi, solve(), fvMatrix< Type >::solveCoupled(), and SolverPerformance< Type >::solverName().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr(), fvMatrix< Type >::fvSolver::solve(), and fvMatrix< Type >::solve().
solveCoupled()
Foam::SolverPerformance< Type > solveCoupled (const dictionary & solverControls)
Solve coupled returning the solution statistics.
Use the given solver controls
Definition at line 220 of file fvMatrixSolve.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::diag(), LduMatrix< Type, DType, LUType >::diag(), Foam::endl(), Foam::Info, messageStream::masterStream(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), SolverPerformance< Type >::print(), and psi.
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr(), and fvMatrix< Type >::solveSegregated().
solve() [2/2]
Foam::SolverPerformance< Type > solve ()
Solve returning the solution statistics.
Solver controls read from fvSolution
Definition at line 314 of file fvMatrixSolve.C.
References fvMatrix< Type >::fvSolver::solve().
Referenced by Foam::checkMethod(), and fvMatrix< Type >::setComponentReference().
residual() [1/3]
Foam::tmp< Foam::Field< Type > > residual () const
Return the matrix residual.
Definition at line 331 of file fvMatrixSolve.C.
References fvMatrix< Type >::addBoundaryDiag(), fvMatrix< Type >::addBoundarySource(), Field< Type >::component(), tmp< T >::ref(), Field< Type >::replace(), and lduMatrix::residual().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr().
D()
Foam::tmp< Foam::scalarField > D () const
Return the matrix scalar diagonal.
Definition at line 692 of file fvMatrix.C.
References fvMatrix< Type >::addCmptAvBoundaryDiag(), lduMatrix::diag(), and tmp< T >::ref().
Referenced by fvMatrix< Type >::A(), fvMatrix< Type >::faceFluxCorrectionPtr(), and fvMatrix< Type >::relax().
DD()
Foam::tmp< Foam::Field< Type > > DD () const
Return the matrix Type diagonal.
Definition at line 701 of file fvMatrix.C.
References fvMatrix< Type >::addToInternalField(), fvPatchField< Type >::coupled(), lduMatrix::diag(), forAll, lduMatrix::lduAddr(), patchi, tmp< T >::ref(), and List< Type >::size().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr().
A()
Foam::tmp< Foam::volScalarField > A () const
Return the central coefficient.
Definition at line 725 of file fvMatrix.C.
References fvMatrix< Type >::D(), Foam::dimVol, IOobject::NO_READ, IOobject::NO_WRITE, and tmp< T >::ref().
Referenced by Foam::checkMethod(), meanVelocityForce::constrain(), fvMatrix< Type >::faceFluxCorrectionPtr(), and kinematicSingleLayer::solveThickness().
H() [1/3]
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > H () const
Return the H operation source.
Definition at line 754 of file fvMatrix.C.
References fvMatrix< Type >::addBoundaryDiag(), fvMatrix< Type >::addBoundarySource(), fvMatrix< Type >::addCmptAvBoundaryDiag(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVol, lduMatrix::H(), IOobject::NO_READ, IOobject::NO_WRITE, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), tmp< T >::ref(), and GeometricField< Type, PatchField, GeoMesh >::replace().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr(), and kinematicSingleLayer::solveThickness().
H1() [1/3]
Foam::tmp< Foam::volScalarField > H1 () const
Return H(1)
Definition at line 816 of file fvMatrix.C.
References fvMatrix< Type >::addToInternalField(), Foam::component(), fvPatchField< Type >::coupled(), Foam::dimVol, fvMatrix< Type >::flux(), forAll, lduMatrix::H1(), lduMatrix::lduAddr(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, GeometricField< Type, PatchField, GeoMesh >::ref(), and List< Type >::size().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr().
flux()
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > flux () const
Return the face-flux field from the matrix.
Definition at line 864 of file fvMatrix.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::cmptMultiply(), fvMatrix< Type >::dimensions(), lduMatrix::faceH(), Foam::FatalError, FatalErrorInFunction, forAll, IOobject::NO_READ, IOobject::NO_WRITE, patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and tmp< T >::ref().
Referenced by Implicit< CloudType >::cacheFields(), Foam::checkMethod(), Foam::CorrectPhi(), fvMatrix< Type >::faceFluxCorrectionPtr(), fvMatrix< Type >::H1(), Foam::MULES::implicitSolve(), and kinematicSingleLayer::solveThickness().
operator=() [1/2]
void operator= (const fvMatrix< Type > & fvmv)
Definition at line 951 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and lduMatrix::operator=().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr(), and fvMatrix< Type >::operator=().
operator=() [2/2]
void operator= (const tmp< fvMatrix< Type >> & tfvmv)
Definition at line 987 of file fvMatrix.C.
References fvMatrix< Type >::operator=().
negate()
void negate ()
Definition at line 995 of file fvMatrix.C.
References lduMatrix::negate().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr().
operator+=() [1/7]
void operator+= (const fvMatrix< Type > & fvmv)
Definition at line 1010 of file fvMatrix.C.
References Foam::checkMethod(), and lduMatrix::operator+=().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr(), and fvMatrix< Type >::operator+=().
operator+=() [2/7]
void operator+= (const tmp< fvMatrix< Type >> & tfvmv)
Definition at line 1036 of file fvMatrix.C.
References fvMatrix< Type >::operator+=().
operator-=() [1/7]
void operator-= (const fvMatrix< Type > & fvmv)
Definition at line 1044 of file fvMatrix.C.
References Foam::checkMethod(), and lduMatrix::operator-=().
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr(), and fvMatrix< Type >::operator-=().
operator-=() [2/7]
void operator-= (const tmp< fvMatrix< Type >> & tfvmv)
Definition at line 1068 of file fvMatrix.C.
References fvMatrix< Type >::operator-=().
operator+=() [3/7]
void operator+= (const DimensionedField< Type, volMesh > & su)
Definition at line 1077 of file fvMatrix.C.
References Foam::checkMethod(), and fvMatrix< Type >::source().
operator+=() [4/7]
void operator+= (const tmp< DimensionedField< Type, volMesh >> & tsu)
Definition at line 1088 of file fvMatrix.C.
References fvMatrix< Type >::operator+=().
operator+=() [5/7]
void operator+= (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tsu)
Definition at line 1099 of file fvMatrix.C.
References fvMatrix< Type >::operator+=().
operator-=() [3/7]
void operator-= (const DimensionedField< Type, volMesh > & su)
Definition at line 1110 of file fvMatrix.C.
References Foam::checkMethod(), and fvMatrix< Type >::source().
operator-=() [4/7]
void operator-= (const tmp< DimensionedField< Type, volMesh >> & tsu)
Definition at line 1121 of file fvMatrix.C.
References fvMatrix< Type >::operator-=().
operator-=() [5/7]
void operator-= (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tsu)
Definition at line 1132 of file fvMatrix.C.
References fvMatrix< Type >::operator-=().
operator+=() [6/7]
void operator+= (const dimensioned< Type > & su)
Definition at line 1143 of file fvMatrix.C.
References fvMatrix< Type >::psi(), and fvMatrix< Type >::source().
operator-=() [6/7]
void operator-= (const dimensioned< Type > & su)
Definition at line 1153 of file fvMatrix.C.
References fvMatrix< Type >::psi(), and fvMatrix< Type >::source().
operator+=() [7/7]
void operator+= (const zero &)
Definition at line 1163 of file fvMatrix.C.
operator-=() [7/7]
void operator-= (const zero &)
Definition at line 1171 of file fvMatrix.C.
operator*=() [1/4]
void operator*= (const volScalarField::Internal & dsf)
Definition at line 1179 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, lduMatrix::operator*=(), and patchi.
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr(), and fvMatrix< Type >::operator*=().
operator*=() [2/4]
void operator*= (const tmp< volScalarField::Internal > & tdsf)
Definition at line 1209 of file fvMatrix.C.
References fvMatrix< Type >::operator*=().
operator*=() [3/4]
void operator*= (const tmp< volScalarField > & tvsf)
Definition at line 1220 of file fvMatrix.C.
References fvMatrix< Type >::operator*=().
operator*=() [4/4]
void operator*= (const dimensioned< scalar > & ds)
Definition at line 1231 of file fvMatrix.C.
References Foam::checkMethod(), and lduMatrix::operator*=().
setComponentReference() [2/3]
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
Definition at line 33 of file fvScalarMatrix.C.
References Foam::diag(), patchi, and fvMatrix< Type >::solver().
solver() [3/4]
Foam::autoPtr< Foam::fvMatrix< Foam::scalar >::fvSolver > solver (const dictionary & solverControls)
Definition at line 58 of file fvScalarMatrix.C.
References Foam::diag(), Foam::endl(), Foam::Info, messageStream::masterStream(), mesh, Foam::New(), and fvMatrix< Type >::fvSolver::solve().
solveSegregated() [2/3]
Foam::solverPerformance solveSegregated (const dictionary & solverControls)
Definition at line 138 of file fvScalarMatrix.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::diag(), Foam::endl(), Foam::Info, messageStream::masterStream(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), Foam::New(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), SolverPerformance< Type >::print(), psi, and solve().
residual() [2/3]
Foam::tmp< Foam::scalarField > residual () const
Definition at line 187 of file fvScalarMatrix.C.
References tmp< T >::ref().
H() [2/3]
Foam::tmp< Foam::volScalarField > H () const
Definition at line 211 of file fvScalarMatrix.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::dimVol, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and tmp< T >::ref().
H1() [2/3]
Foam::tmp< Foam::volScalarField > H1 () const
Definition at line 243 of file fvScalarMatrix.C.
References Foam::dimVol, and GeometricField< Type, PatchField, GeoMesh >::ref().
setComponentReference() [3/3]
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
solver() [4/4]
autoPtr< fvMatrix< scalar >::fvSolver > solver (const dictionary &)
solveSegregated() [3/3]
solverPerformance solveSegregated (const dictionary &)
residual() [3/3]
tmp< scalarField > residual () const
H() [3/3]
tmp< volScalarField > H () const
H1() [3/3]
tmp< volScalarField > H1 () const
Friends And Related Function Documentation
fvSolver
friend class fvSolver friend
Declare friendship with the fvSolver class.
Definition at line 148 of file fvMatrix.H.
operator & [1/4]
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const fvMatrix< Type > & , const DimensionedField< Type, volMesh > &) friend
operator & [2/4]
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const fvMatrix< Type > & , const tmp< GeometricField< Type, fvPatchField, volMesh >> &) friend
operator & [3/4]
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const tmp< fvMatrix< Type >> & , const DimensionedField< Type, volMesh > &) friend
operator & [4/4]
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const tmp< fvMatrix< Type >> & , const tmp< GeometricField< Type, fvPatchField, volMesh >> &) friend
operator
Ostream& operator (Ostream & , const fvMatrix< Type > &) friend
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchField.H
src/finiteVolume/fvMatrices/fvMatrix/fvMatrix.H
src/finiteVolume/fvMatrices/fvMatrix/fvMatrix.C
src/finiteVolume/fvMatrices/fvMatrix/fvMatrixSolve.C