OpenFOAM: waveSurfacePressureFvPatchScalarField Class Reference
waveSurfacePressureFvPatchScalarField Class Reference
Boundary Conditions » Inlet boundary Conditions
This is a pressure boundary condition, whose value is calculated as the hydrostatic pressure based on a given displacement:
Public Types
enum ddtSchemeType { tsEuler, tsCrankNicolson, tsBackward }
Enumeration defining the available ddt schemes.
Public Member Functions
TypeName ("waveSurfacePressure")
Runtime type information.
waveSurfacePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
waveSurfacePressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given waveSurfacePressureFvPatchScalarField.
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This is a pressure boundary condition, whose value is calculated as the hydrostatic pressure based on a given displacement:
= density [kg/m3]
= acceleration due to gravity [m/s2]
= wave amplitude [m]
The wave amplitude is updated as part of the calculation, derived from the local volumetric flux.
Usage
Property Description Required Default value
phi flux field name no phi
rho density field name no rho
zeta wave amplitude field name no zeta
Example of the boundary condition specification:
    <patchName>
    {
        type            waveSurfacePressure;
        phi             phi;
        rho             rho;
        zeta            zeta;
        value           uniform 0;  // place holder
    }
The density field is only required if the flux is mass-based as opposed to volumetric-based.
See also
Foam::fixedValueFvPatchField
Source files
waveSurfacePressureFvPatchScalarField.H
waveSurfacePressureFvPatchScalarField.C
Definition at line 124 of file waveSurfacePressureFvPatchScalarField.H.
Member Enumeration Documentation
ddtSchemeType
enum ddtSchemeType
Enumeration defining the available ddt schemes.
Enumerator
tsEuler
tsCrankNicolson
tsBackward
Definition at line 133 of file waveSurfacePressureFvPatchScalarField.H.
Constructor & Destructor Documentation
waveSurfacePressureFvPatchScalarField() [1/5]
waveSurfacePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 65 of file waveSurfacePressureFvPatchScalarField.C.
Referenced by waveSurfacePressureFvPatchScalarField::clone(), NamedEnum< directionType, 3 >::names(), and waveSurfacePressureFvPatchScalarField::waveSurfacePressureFvPatchScalarField().
waveSurfacePressureFvPatchScalarField() [2/5]
waveSurfacePressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 79 of file waveSurfacePressureFvPatchScalarField.C.
References waveSurfacePressureFvPatchScalarField::waveSurfacePressureFvPatchScalarField().
waveSurfacePressureFvPatchScalarField() [3/5]
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given waveSurfacePressureFvPatchScalarField.
onto a new patch
Definition at line 94 of file waveSurfacePressureFvPatchScalarField.C.
References waveSurfacePressureFvPatchScalarField::waveSurfacePressureFvPatchScalarField().
waveSurfacePressureFvPatchScalarField() [4/5]
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField & wspsf)
Construct as copy.
Definition at line 110 of file waveSurfacePressureFvPatchScalarField.C.
References waveSurfacePressureFvPatchScalarField::waveSurfacePressureFvPatchScalarField().
waveSurfacePressureFvPatchScalarField() [5/5]
waveSurfacePressureFvPatchScalarField (const waveSurfacePressureFvPatchScalarField & wspsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 123 of file waveSurfacePressureFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("waveSurfacePressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 198 of file waveSurfacePressureFvPatchScalarField.H.
References waveSurfacePressureFvPatchScalarField::waveSurfacePressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 215 of file waveSurfacePressureFvPatchScalarField.H.
References waveSurfacePressureFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::waveSurfacePressureFvPatchScalarField(), and waveSurfacePressureFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 137 of file waveSurfacePressureFvPatchScalarField.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::constant::universal::c, Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimVelocity, Foam::endl(), Foam::FatalError, FatalErrorInFunction, g, Foam::gMax(), Foam::gMin(), Foam::Info, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), Foam::nl, GeometricField< Type, PatchField, GeoMesh >::oldTime(), Foam::operator==(), patchi, phi, and dimensioned< Type >::value().
Referenced by waveSurfacePressureFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 231 of file waveSurfacePressureFvPatchScalarField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::write().
Referenced by waveSurfacePressureFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/waveSurfacePressure/waveSurfacePressureFvPatchScalarField.H
src/finiteVolume/fields/fvPatchFields/derived/waveSurfacePressure/waveSurfacePressureFvPatchScalarField.C