OpenFOAM: boundedConvectionScheme< Type > Class Template Reference
boundedConvectionScheme< Type > Class Template Reference
Bounded form of the selected convection scheme.
Public Member Functions
TypeName ("bounded")
Runtime type information.
boundedConvectionScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from flux and Istream.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const
Public Member Functions inherited from convectionScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
declareRunTimeSelectionTable (tmp, convectionScheme, Multivariate,(const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, fields, faceFlux, schemeData))
convectionScheme (const convectionScheme &)
Copy construct.
convectionScheme (const fvMesh &mesh, const surfaceScalarField &)
Construct from mesh, flux and Istream.
virtual ~convectionScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
void operator= (const convectionScheme< Type > &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from convectionScheme< Type >
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new convectionScheme created on freestore.
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new multivariate convectionScheme.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::fv::boundedConvectionScheme< Type >
Bounded form of the selected convection scheme.
Boundedness is achieved by subtracting div(phi)*vf or Sp(div(phi), vf) which is non-conservative if div(phi) != 0 but conservative otherwise.
Can be used for convection of bounded scalar properties in steady-state solvers to improve stability if insufficient convergence of the pressure equation causes temporary divergence of the flux field.
Source files
boundedConvectionScheme.H
boundedConvectionScheme.C
Definition at line 61 of file boundedConvectionScheme.H.
Constructor & Destructor Documentation
boundedConvectionScheme()
boundedConvectionScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from flux and Istream.
Definition at line 89 of file boundedConvectionScheme.H.
References boundedConvectionScheme< Type >::flux(), boundedConvectionScheme< Type >::fvcDiv(), boundedConvectionScheme< Type >::fvmDiv(), and boundedConvectionScheme< Type >::interpolate().
Member Function Documentation
TypeName()
TypeName ("bounded")
Runtime type information.
interpolate()
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 46 of file boundedConvectionScheme.C.
References boundedConvectionScheme< Type >::flux().
Referenced by boundedConvectionScheme< Type >::boundedConvectionScheme().
flux()
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 58 of file boundedConvectionScheme.C.
References boundedConvectionScheme< Type >::fvmDiv().
Referenced by boundedConvectionScheme< Type >::boundedConvectionScheme(), and boundedConvectionScheme< Type >::interpolate().
fvmDiv()
tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 70 of file boundedConvectionScheme.C.
References boundedConvectionScheme< Type >::fvcDiv(), Foam::fvm::Sp(), and Foam::fvc::surfaceIntegrate().
Referenced by boundedConvectionScheme< Type >::boundedConvectionScheme(), and boundedConvectionScheme< Type >::flux().
fvcDiv()
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField & faceFlux, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Implements convectionScheme< Type >.
Definition at line 84 of file boundedConvectionScheme.C.
References Foam::fvc::surfaceIntegrate().
Referenced by boundedConvectionScheme< Type >::boundedConvectionScheme(), and boundedConvectionScheme< Type >::fvmDiv().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/convectionSchemes/boundedConvectionScheme/boundedConvectionScheme.H
src/finiteVolume/finiteVolume/convectionSchemes/boundedConvectionScheme/boundedConvectionScheme.C