OpenFOAM: d2dt2Scheme< Type > Class Template Reference
d2dt2Scheme< Type > Class Template Reference abstract
Abstract base class for d2dt2 schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, d2dt2Scheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
d2dt2Scheme (const fvMesh &mesh)
Construct from mesh.
d2dt2Scheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~d2dt2Scheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmD2dt2 (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< d2dt2Scheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new d2dt2Scheme created on freestore.
Protected Member Functions
d2dt2Scheme (const d2dt2Scheme &)
Disallow copy construct.
void operator= (const d2dt2Scheme &)
Disallow default bitwise assignment.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::d2dt2Scheme< Type >
Abstract base class for d2dt2 schemes.
Source files
d2dt2Scheme.H
d2dt2Scheme.C
Definition at line 64 of file d2dt2Scheme.H.
Constructor & Destructor Documentation
d2dt2Scheme() [1/3]
d2dt2Scheme (const d2dt2Scheme< Type > &) protected
Disallow copy construct.
d2dt2Scheme() [2/3]
d2dt2Scheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 106 of file d2dt2Scheme.H.
d2dt2Scheme() [3/3]
d2dt2Scheme (const fvMesh & mesh, Istream &) inline
Construct from mesh and Istream.
Definition at line 112 of file d2dt2Scheme.H.
References d2dt2Scheme< Type >::New(), and d2dt2Scheme< Type >::~d2dt2Scheme().
~d2dt2Scheme()
~d2dt2Scheme () virtual
Destructor.
Definition at line 90 of file d2dt2Scheme.C.
Referenced by d2dt2Scheme< Type >::d2dt2Scheme().
Member Function Documentation
operator=()
void operator= (const d2dt2Scheme< Type > &) protected
Disallow default bitwise assignment.
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (tmp , d2dt2Scheme< Type > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
tmp< d2dt2Scheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new d2dt2Scheme created on freestore.
Definition at line 46 of file d2dt2Scheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fvc::d2dt2(), Foam::fvm::d2dt2(), and d2dt2Scheme< Type >::d2dt2Scheme().
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 135 of file d2dt2Scheme.H.
References d2dt2Scheme< Type >::fvcD2dt2(), d2dt2Scheme< Type >::fvmD2dt2(), and d2dt2Scheme< Type >::mesh_.
Referenced by steadyStateD2dt2Scheme< Type >::mesh(), and EulerD2dt2Scheme< Type >::mesh().
fvcD2dt2() [1/2]
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
Referenced by d2dt2Scheme< Type >::mesh().
fvcD2dt2() [2/2]
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcD2dt2 (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
fvmD2dt2() [1/3]
virtual tmp<fvMatrix<Type> > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
Referenced by d2dt2Scheme< Type >::mesh().
fvmD2dt2() [2/3]
virtual tmp<fvMatrix<Type> > fvmD2dt2 (const dimensionedScalar & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
fvmD2dt2() [3/3]
virtual tmp<fvMatrix<Type> > fvmD2dt2 (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 73 of file d2dt2Scheme.H.
Referenced by d2dt2Scheme< Type >::mesh().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/d2dt2Schemes/d2dt2Scheme/d2dt2Scheme.H
src/finiteVolume/finiteVolume/d2dt2Schemes/d2dt2Scheme/d2dt2Scheme.C