OpenFOAM: convectionScheme< Type > Class Template Reference
convectionScheme< Type > Class Template Reference abstract
Abstract base class for convection schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
declareRunTimeSelectionTable (tmp, convectionScheme, Multivariate,(const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, fields, faceFlux, schemeData))
convectionScheme (const convectionScheme &)
Copy construct.
convectionScheme (const fvMesh &mesh, const surfaceScalarField &)
Construct from mesh, flux and Istream.
virtual ~convectionScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
void operator= (const convectionScheme< Type > &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new convectionScheme created on freestore.
static tmp< convectionScheme< Type > > New (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new multivariate convectionScheme.
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::fv::convectionScheme< Type >
Abstract base class for convection schemes.
Source files
convectionScheme.H
convectionScheme.C
Definition at line 64 of file convectionScheme.H.
Constructor & Destructor Documentation
convectionScheme() [1/2]
convectionScheme (const convectionScheme< Type > & cs)
Copy construct.
Definition at line 47 of file convectionScheme.C.
References convectionScheme< Type >::New().
convectionScheme() [2/2]
convectionScheme (const fvMesh & mesh, const surfaceScalarField &) inline
Construct from mesh, flux and Istream.
Definition at line 117 of file convectionScheme.H.
References convectionScheme< Type >::New(), and convectionScheme< Type >::~convectionScheme().
~convectionScheme()
~convectionScheme () virtual
Destructor.
Definition at line 149 of file convectionScheme.C.
Referenced by convectionScheme< Type >::convectionScheme().
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (tmp , convectionScheme< Type > , Istream , (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (tmp , convectionScheme< Type > , Multivariate , (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, fields, faceFlux, schemeData))
New() [1/2]
tmp< convectionScheme< Type > > New (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) static
Return a pointer to a new convectionScheme created on freestore.
Definition at line 58 of file convectionScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, convectionScheme< Type >::mesh(), and Foam::nl.
Referenced by convectionScheme< Type >::convectionScheme(), Foam::fvm::div(), Foam::fvc::div(), and Foam::fvc::flux().
New() [2/2]
tmp< convectionScheme< Type > > New (const fvMesh & mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData) static
Return a pointer to a new multivariate convectionScheme.
created on freestore
Definition at line 102 of file convectionScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, fields, InfoInFunction, convectionScheme< Type >::mesh(), and Foam::nl.
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 156 of file convectionScheme.H.
References convectionScheme< Type >::flux(), convectionScheme< Type >::fvcDiv(), convectionScheme< Type >::fvmDiv(), convectionScheme< Type >::interpolate(), and convectionScheme< Type >::operator=().
Referenced by convectionScheme< Type >::New().
interpolate()
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > interpolate (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >, boundedConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
Referenced by convectionScheme< Type >::mesh().
flux()
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > flux (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >, boundedConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
Referenced by convectionScheme< Type >::mesh().
fvmDiv()
virtual tmp<fvMatrix<Type> > fvmDiv (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >, boundedConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
Referenced by convectionScheme< Type >::mesh().
fvcDiv()
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDiv (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >, boundedConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
Referenced by convectionScheme< Type >::mesh().
operator=()
void operator= (const convectionScheme< Type > & cs)
Definition at line 156 of file convectionScheme.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by convectionScheme< Type >::mesh().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/convectionSchemes/convectionScheme/convectionScheme.H
src/finiteVolume/finiteVolume/convectionSchemes/convectionScheme/convectionScheme.C