OpenFOAM: fvsPatchField< Type > Class Template Reference
fvsPatchField< Type > Class Template Reference
An abstract base class with a fat-interface to all derived classes covering all possible ways in which they might be used.
Public Types
typedef fvPatch Patch
typedef calculatedFvsPatchField< Type > Calculated
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("fvsPatchField")
Runtime type information.
declareRunTimeSelectionTable (tmp, fvsPatchField, patch,(const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF),(p, iF))
declareRunTimeSelectionTable (tmp, fvsPatchField, patchMapper,(const fvsPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF, const fvPatchFieldMapper &m),(dynamic_cast< const fvsPatchFieldType &>(ptf), p, iF, m))
declareRunTimeSelectionTable (tmp, fvsPatchField, dictionary,(const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF, const dictionary &dict),(p, iF, dict))
fvsPatchField (const fvPatch &, const DimensionedField< Type, surfaceMesh > &)
Construct from patch and internal field.
fvsPatchField (const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const Field< Type > &)
Construct from patch and internal field and patch field.
fvsPatchField (const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fvsPatchField (const fvsPatchField< Type > &, const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const fvPatchFieldMapper &)
Construct by mapping the given fvsPatchField onto a new patch.
fvsPatchField (const fvsPatchField< Type > &)
Construct as copy.
virtual tmp< fvsPatchField< Type > > clone () const
Construct and return a clone.
fvsPatchField (const fvsPatchField< Type > &, const DimensionedField< Type, surfaceMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvsPatchField< Type > > clone (const DimensionedField< Type, surfaceMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual ~fvsPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
const fvPatch & patch () const
Return patch.
const DimensionedField< Type, surfaceMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvsPatchField< Type > &, const labelList &)
Reverse map the given fvsPatchField onto this fvsPatchField.
virtual void write (Ostream &) const
Write.
void check (const fvsPatchField< Type > &) const
Check fvsPatchField<Type> against given fvsPatchField<Type>
virtual void operator= (const UList< Type > &)
virtual void operator= (const fvsPatchField< Type > &)
virtual void operator+= (const fvsPatchField< Type > &)
virtual void operator-= (const fvsPatchField< Type > &)
virtual void operator*= (const fvsPatchField< scalar > &)
virtual void operator/= (const fvsPatchField< scalar > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const fvsPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::tmp< Foam::fvsPatchField< Type > > NewCalculatedType (const fvsPatchField< Type2 > &pf)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< Type >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< Type >)
Assignment to an initializer list.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static tmp< fvsPatchField< Type > > New (const word &, const fvPatch &, const DimensionedField< Type, surfaceMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvsPatchField< Type > > New (const word &, const word &actualPatchType, const fvPatch &, const DimensionedField< Type, surfaceMesh > &)
Return a pointer to a new patchField created on freestore given.
static tmp< fvsPatchField< Type > > New (const fvsPatchField< Type > &, const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const fvPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static tmp< fvsPatchField< Type > > New (const fvPatch &, const DimensionedField< Type, surfaceMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
static tmp< fvsPatchField< Type > > NewCalculatedType (const fvPatch &)
Return a pointer to a new calculatedFvsPatchField created on.
template<class Type2 >
static tmp< fvsPatchField< Type > > NewCalculatedType (const fvsPatchField< Type2 > &)
Return a pointer to a new calculatedFvsPatchField created on.
static const word & calculatedType ()
Return the type of the calculated for of fvsPatchField.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes
static int disallowGenericFvsPatchField
Debug switch to disallow the use of genericFvsPatchField.
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Friends
Ostream & operator (Ostream &, const fvsPatchField< Type > &)
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::fvsPatchField< Type >
An abstract base class with a fat-interface to all derived classes covering all possible ways in which they might be used.
The first level of derivation is to basic patchFields which cover zero-gradient, fixed-gradient, fixed-value and mixed conditions.
The next level of derivation covers all the specialised typed with specific evaluation proceedures, particularly with respect to specific fields.
Source files
fvsPatchField.H
fvsPatchField.C
fvsPatchFieldNew.C
Definition at line 65 of file fvsPatchField.H.
Member Typedef Documentation
Patch
typedef fvPatch Patch
Definition at line 94 of file fvsPatchField.H.
Calculated
typedef calculatedFvsPatchField<Type> Calculated
Definition at line 95 of file fvsPatchField.H.
Constructor & Destructor Documentation
fvsPatchField() [1/6]
fvsPatchField (const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file fvsPatchField.C.
Referenced by fvsPatchField< Type >::clone(), and fvsPatchField< Type >::fvsPatchField().
fvsPatchField() [2/6]
fvsPatchField (const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const Field< Type > & f)
Construct from patch and internal field and patch field.
Definition at line 48 of file fvsPatchField.C.
References fvsPatchField< Type >::fvsPatchField().
fvsPatchField() [3/6]
fvsPatchField (const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 77 of file fvsPatchField.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), fvsPatchField< Type >::fvsPatchField(), and fvPatch::size().
fvsPatchField() [4/6]
fvsPatchField (const fvsPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping the given fvsPatchField onto a new patch.
Definition at line 62 of file fvsPatchField.C.
References fvsPatchField< Type >::fvsPatchField().
fvsPatchField() [5/6]
fvsPatchField (const fvsPatchField< Type > & ptf)
Construct as copy.
Definition at line 107 of file fvsPatchField.C.
References fvsPatchField< Type >::fvsPatchField().
fvsPatchField() [6/6]
fvsPatchField (const fvsPatchField< Type > & ptf, const DimensionedField< Type, surfaceMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 119 of file fvsPatchField.C.
~fvsPatchField()
virtual ~fvsPatchField () inline virtual
Destructor.
Definition at line 270 of file fvsPatchField.H.
References fvsPatchField< Type >::db().
Member Function Documentation
TypeName()
TypeName ("fvsPatchField< Type >")
Runtime type information.
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (tmp , fvsPatchField< Type > , patch , (const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF) , (p, iF))
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (tmp , fvsPatchField< Type > , patchMapper , (const fvsPatchField< Type > &ptf, const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF, const fvPatchFieldMapper &m) , (dynamic_cast< const fvsPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (tmp , fvsPatchField< Type > , dictionary , (const fvPatch &p, const DimensionedField< Type, surfaceMesh > &iF, const dictionary &dict) , (p, iF, dict))
clone() [1/2]
virtual tmp<fvsPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented in slicedFvsPatchField< Type >, processorCyclicFvsPatchField< Type >, processorFvsPatchField< Type >, coupledFvsPatchField< Type >, cyclicFvsPatchField< Type >, cyclicACMIFvsPatchField< Type >, cyclicAMIFvsPatchField< Type >, nonuniformTransformCyclicFvsPatchField< Type >, symmetryPlaneFvsPatchField< Type >, fixedValueFvsPatchField< Type >, cyclicSlipFvsPatchField< Type >, emptyFvsPatchField< Type >, symmetryFvsPatchField< Type >, wedgeFvsPatchField< Type >, and calculatedFvsPatchField< Type >.
Definition at line 185 of file fvsPatchField.H.
References fvsPatchField< Type >::fvsPatchField().
clone() [2/2]
virtual tmp<fvsPatchField<Type> > clone (const DimensionedField< Type, surfaceMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in processorCyclicFvsPatchField< Type >, processorFvsPatchField< Type >, slicedFvsPatchField< Type >, cyclicFvsPatchField< Type >, cyclicACMIFvsPatchField< Type >, cyclicAMIFvsPatchField< Type >, coupledFvsPatchField< Type >, nonuniformTransformCyclicFvsPatchField< Type >, symmetryPlaneFvsPatchField< Type >, fixedValueFvsPatchField< Type >, cyclicSlipFvsPatchField< Type >, emptyFvsPatchField< Type >, symmetryFvsPatchField< Type >, wedgeFvsPatchField< Type >, and calculatedFvsPatchField< Type >.
Definition at line 199 of file fvsPatchField.H.
References fvsPatchField< Type >::New(), and fvsPatchField< Type >::NewCalculatedType().
New() [1/4]
Foam::tmp< Foam::fvsPatchField< Type > > New (const word & patchFieldType, const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values)
Definition at line 82 of file fvsPatchFieldNew.C.
References Foam::New().
Referenced by fvsPatchField< Type >::clone(), and fvsPatchField< Type >::New().
New() [2/4]
Foam::tmp< Foam::fvsPatchField< Type > > New (const word & patchFieldType, const word & actualPatchType, const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values) Allows override of constraint type
Definition at line 30 of file fvsPatchFieldNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, fvsPatchField< Type >::New(), Foam::nl, and p.
New() [3/4]
Foam::tmp< Foam::fvsPatchField< Type > > New (const fvsPatchField< Type > & ptf, const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const fvPatchFieldMapper & pfMapper) static
Return a pointer to a new patchField created on freestore from.
a given fvsPatchField mapped onto a new patch
Definition at line 161 of file fvsPatchFieldNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, Foam::nl, and p.
New() [4/4]
Foam::tmp< Foam::fvsPatchField< Type > > New (const fvPatch & p, const DimensionedField< Type, surfaceMesh > & iF, const dictionary & dict) static
Return a pointer to a new patchField created on freestore.
from dictionary
Definition at line 94 of file fvsPatchFieldNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), InfoInFunction, dictionary::lookup(), fvsPatchField< Type >::New(), Foam::nl, and p.
NewCalculatedType() [1/3]
Foam::tmp< Foam::fvsPatchField< Type > > NewCalculatedType (const fvPatch & p) static
Return a pointer to a new calculatedFvsPatchField created on.
freestore without setting patchField values
Definition at line 99 of file calculatedFvsPatchField.C.
References p.
Referenced by calculatedFvsPatchField< Type >::calculatedFvsPatchField(), and fvsPatchField< Type >::clone().
NewCalculatedType() [2/3]
static tmp<fvsPatchField<Type> > NewCalculatedType (const fvsPatchField< Type2 > &) static
Return a pointer to a new calculatedFvsPatchField created on.
freestore without setting patchField values
db()
const Foam::objectRegistry & db () const
Return local objectRegistry.
Definition at line 133 of file fvsPatchField.C.
Referenced by fvsPatchField< Type >::~fvsPatchField().
patch()
const fvPatch& patch () const inline
Return patch.
Definition at line 282 of file fvsPatchField.H.
Referenced by curvatureSeparation::calcCosAngle(), CentredFitSnGradData< Polynomial >::calcFit(), CentredFitData< Polynomial >::CentredFitData(), extendedFaceToCellStencil::collectData(), inversePointDistanceDiffusivity::correct(), inverseFaceDistanceDiffusivity::correct(), surfaceInterpolation::movePoints(), fvsPatchField< Type >::NewCalculatedType(), fvsPatchField< Type >::operator*=(), fvsPatchField< Type >::operator/=(), fvMeshDistribute::printFieldInfo(), dynamicRefineFvMesh::refine(), UpwindFitData< Polynomial >::UpwindFitData(), extendedUpwindCellToFaceStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), leastSquaresVectors::~leastSquaresVectors(), and skewCorrectionVectors::~skewCorrectionVectors().
internalField()
const DimensionedField<Type, surfaceMesh>& internalField () const inline
Return dimensioned internal field reference.
Definition at line 289 of file fvsPatchField.H.
primitiveField()
const Field<Type>& primitiveField () const inline
Return internal field reference.
Definition at line 295 of file fvsPatchField.H.
References fvsPatchField< Type >::calculatedType(), and fvsPatchField< Type >::fixesValue().
calculatedType()
const Foam::word & calculatedType () static
Return the type of the calculated for of fvsPatchField.
Definition at line 32 of file calculatedFvsPatchField.C.
References calculatedFvsPatchField< Type >::calculatedFvsPatchField().
Referenced by fvsPatchField< Type >::primitiveField().
fixesValue()
virtual bool fixesValue () const inline virtual
Return true if this patch field fixes a value.
Needed to check if a level has to be specified while solving Poissons equations.
Reimplemented in slicedFvsPatchField< Type >, fixedValueFvsPatchField< Type >, and calculatedFvsPatchField< Type >.
Definition at line 306 of file fvsPatchField.H.
Referenced by fvsPatchField< Type >::primitiveField().
coupled()
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in processorCyclicFvsPatchField< Type >, processorFvsPatchField< Type >, cyclicACMIFvsPatchField< Type >, cyclicAMIFvsPatchField< Type >, and coupledFvsPatchField< Type >.
Definition at line 312 of file fvsPatchField.H.
References fvsPatchField< Type >::autoMap(), fvsPatchField< Type >::check(), fvsPatchField< Type >::operator*=(), fvsPatchField< Type >::operator+=(), fvsPatchField< Type >::operator-=(), fvsPatchField< Type >::operator/=(), fvsPatchField< Type >::operator=(), fvsPatchField< Type >::operator==(), fvsPatchField< Type >::rmap(), and fvsPatchField< Type >::write().
Referenced by Foam::adjustPhi(), CentredFitSnGradData< Polynomial >::calcFit(), CentredFitData< Polynomial >::CentredFitData(), pointLinear< Type >::correction(), linearUpwind< Type >::correction(), linearUpwindV< Type >::correction(), surfaceInterpolation::movePoints(), UpwindFitData< Polynomial >::UpwindFitData(), extendedUpwindCellToFaceStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), and skewCorrectionVectors::~skewCorrectionVectors().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in emptyFvsPatchField< Type >.
Definition at line 153 of file fvsPatchField.C.
References fvsPatchField< Type >::rmap().
Referenced by fvsPatchField< Type >::check(), and fvsPatchField< Type >::coupled().
rmap()
void rmap (const fvsPatchField< Type > & ptf, const labelList & addr) virtual
Reverse map the given fvsPatchField onto this fvsPatchField.
Reimplemented in emptyFvsPatchField< Type >.
Definition at line 163 of file fvsPatchField.C.
Referenced by fvsPatchField< Type >::autoMap(), and fvsPatchField< Type >::coupled().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 173 of file fvsPatchField.C.
References Foam::nl, Foam::type(), and Ostream::writeKeyword().
Referenced by fvsPatchField< Type >::coupled(), and fvsPatchField< Type >::operator==().
check()
void check (const fvsPatchField< Type > & ptf) const
Check fvsPatchField<Type> against given fvsPatchField<Type>
Definition at line 140 of file fvsPatchField.C.
References Foam::abort(), fvsPatchField< Type >::autoMap(), Foam::FatalError, and FatalErrorInFunction.
Referenced by fvsPatchField< Type >::coupled().
operator=() [1/3]
void operator= (const UList< Type > & ul) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 184 of file fvsPatchField.C.
Referenced by fvsPatchField< Type >::coupled().
operator=() [2/3]
void operator= (const fvsPatchField< Type > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 194 of file fvsPatchField.C.
operator+=() [1/3]
void operator+= (const fvsPatchField< Type > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 205 of file fvsPatchField.C.
Referenced by fvsPatchField< Type >::coupled().
operator-=() [1/3]
void operator-= (const fvsPatchField< Type > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 216 of file fvsPatchField.C.
Referenced by fvsPatchField< Type >::coupled().
operator*=() [1/3]
void operator*= (const fvsPatchField< scalar > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 227 of file fvsPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and fvsPatchField< Type >::patch().
Referenced by fvsPatchField< Type >::coupled().
operator/=() [1/3]
void operator/= (const fvsPatchField< scalar > & ptf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 244 of file fvsPatchField.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and fvsPatchField< Type >::patch().
Referenced by fvsPatchField< Type >::coupled().
operator+=() [2/3]
void operator+= (const Field< Type > & tf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 260 of file fvsPatchField.C.
References tf.
operator-=() [2/3]
void operator-= (const Field< Type > & tf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 270 of file fvsPatchField.C.
References tf.
operator*=() [2/3]
void operator*= (const Field< scalar > & tf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 280 of file fvsPatchField.C.
References tf.
operator/=() [2/3]
void operator/= (const Field< scalar > & tf) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 290 of file fvsPatchField.C.
References tf.
operator=() [3/3]
void operator= (const Type & t) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 300 of file fvsPatchField.C.
operator+=() [3/3]
void operator+= (const Type & t) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 310 of file fvsPatchField.C.
operator-=() [3/3]
void operator-= (const Type & t) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 320 of file fvsPatchField.C.
operator*=() [3/3]
void operator*= (const scalar s) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 330 of file fvsPatchField.C.
References s().
operator/=() [3/3]
void operator/= (const scalar s) virtual
Reimplemented in fixedValueFvsPatchField< Type >, and slicedFvsPatchField< Type >.
Definition at line 340 of file fvsPatchField.C.
References s().
operator==() [1/3]
void operator== (const fvsPatchField< Type > & ptf) virtual
Definition at line 350 of file fvsPatchField.C.
Referenced by fvsPatchField< Type >::coupled().
operator==() [2/3]
void operator== (const Field< Type > & tf) virtual
Definition at line 360 of file fvsPatchField.C.
References tf.
operator==() [3/3]
void operator== (const Type & t) virtual
Definition at line 370 of file fvsPatchField.C.
References fvsPatchField< Type >::write().
NewCalculatedType() [3/3]
Foam::tmp<Foam::fvsPatchField<Type> > NewCalculatedType (const fvsPatchField< Type2 > & pf)
Definition at line 132 of file calculatedFvsPatchField.C.
References fvsPatchField< Type >::patch().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const fvsPatchField< Type > &) friend
Member Data Documentation
disallowGenericFvsPatchField
int disallowGenericFvsPatchField static
Debug switch to disallow the use of genericFvsPatchField.
Definition at line 102 of file fvsPatchField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchField.H
src/finiteVolume/fields/fvsPatchFields/basic/calculated/calculatedFvsPatchField.C
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchField.C
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchFieldNew.C
src/finiteVolume/fields/fvsPatchFields/fvsPatchField/fvsPatchFields.C