OpenFOAM: ddtScheme< Type > Class Template Reference
ddtScheme< Type > Class Template Reference abstract
Abstract base class for ddt schemes.
Public Types
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
Construct from mesh.
ddtScheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~ddtScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)=0
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
virtual tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)=0
virtual tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)=0
virtual tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)=0
virtual tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)=0
virtual tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)=0
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new ddtScheme created on freestore.
Protected Member Functions
ddtScheme (const ddtScheme &)
Disallow copy construct.
void operator= (const ddtScheme &)
Disallow default bitwise assignment.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::ddtScheme< Type >
Abstract base class for ddt schemes.
Source files
ddtScheme.H
ddtScheme.C
Definition at line 64 of file ddtScheme.H.
Member Typedef Documentation
fluxFieldType
typedef GeometricField< typename flux<Type>::type, fvsPatchField, surfaceMesh > fluxFieldType
Definition at line 198 of file ddtScheme.H.
Constructor & Destructor Documentation
ddtScheme() [1/3]
ddtScheme (const ddtScheme< Type > &) protected
Disallow copy construct.
ddtScheme() [2/3]
ddtScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 106 of file ddtScheme.H.
ddtScheme() [3/3]
ddtScheme (const fvMesh & mesh, Istream &) inline
Construct from mesh and Istream.
Definition at line 112 of file ddtScheme.H.
References ddtScheme< Type >::New(), and ddtScheme< Type >::~ddtScheme().
~ddtScheme()
~ddtScheme () virtual
Destructor.
Definition at line 90 of file ddtScheme.C.
References ddtScheme< Type >::fvcDdt().
Referenced by ddtScheme< Type >::ddtScheme().
Member Function Documentation
operator=()
void operator= (const ddtScheme< Type > &) protected
Disallow default bitwise assignment.
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (tmp , ddtScheme< Type > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
tmp< ddtScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new ddtScheme created on freestore.
Definition at line 46 of file ddtScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fvc::ddt(), Foam::fvm::ddt(), Foam::fvc::ddtCorr(), and ddtScheme< Type >::ddtScheme().
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 135 of file ddtScheme.H.
References Foam::constant::atomic::alpha, ddtScheme< Type >::fvcDdt(), ddtScheme< Type >::fvmDdt(), ddtScheme< Type >::mesh_, and rho.
Referenced by steadyStateDdtScheme< Type >::mesh(), EulerDdtScheme< Type >::mesh(), boundedDdtScheme< Type >::mesh(), backwardDdtScheme< Type >::mesh(), CoEulerDdtScheme< Type >::mesh(), SLTSDdtScheme< Type >::mesh(), localEulerDdtScheme< Type >::mesh(), and CrankNicolsonDdtScheme< Type >::mesh().
fvcDdt() [1/5]
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDdt (const dimensioned< Type > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Referenced by ddtScheme< Type >::mesh(), and ddtScheme< Type >::~ddtScheme().
fvcDdt() [2/5]
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdt() [3/5]
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDdt (const dimensionedScalar & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdt() [4/5]
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDdt (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdt() [5/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Definition at line 98 of file ddtScheme.C.
References ddtScheme< Type >::fvmDdt(), NotImplemented, and GeometricField< Type, PatchField, GeoMesh >::null().
fvmDdt() [1/4]
virtual tmp<fvMatrix<Type> > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Referenced by ddtScheme< Type >::fvcDdt(), and ddtScheme< Type >::mesh().
fvmDdt() [2/4]
virtual tmp<fvMatrix<Type> > fvmDdt (const dimensionedScalar & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvmDdt() [3/4]
virtual tmp<fvMatrix<Type> > fvmDdt (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvmDdt() [4/4]
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Definition at line 115 of file ddtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, ddtScheme< Type >::fvcDdtPhiCoeff(), and NotImplemented.
fvcDdtPhiCoeff() [1/2]
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi, const fluxFieldType & phiCorr)
Definition at line 137 of file ddtScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::endl(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), InfoInFunction, Foam::mag(), mesh, Foam::min(), patchi, and tmp< T >::ref().
Referenced by CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), and ddtScheme< Type >::fvmDdt().
fvcDdtPhiCoeff() [2/2]
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi)
Definition at line 184 of file ddtScheme.C.
References Foam::fvc::dotInterpolate(), and mesh.
fvcDdtUfCorr() [1/2]
virtual tmp<fluxFieldType> fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdtPhiCorr() [1/2]
virtual tmp<fluxFieldType> fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdtUfCorr() [2/2]
virtual tmp<fluxFieldType> fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
fvcDdtPhiCorr() [2/2]
virtual tmp<fluxFieldType> fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
meshPhi()
virtual tmp<surfaceScalarField> meshPhi (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, CoEulerDdtScheme< Type >, backwardDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 73 of file ddtScheme.H.
Referenced by ddtScheme< Type >::mesh().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/ddtScheme/ddtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/ddtScheme/ddtScheme.C