OpenFOAM: gaussGrad< Type > Class Template Reference
gaussGrad< Type > Class Template Reference
Basic second-order gradient scheme using face-interpolation and Gauss' theorem.
Public Member Functions
TypeName ("Gauss")
Runtime type information.
gaussGrad (const fvMesh &mesh)
Construct from mesh.
gaussGrad (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
Return the gradient of the given field to the gradScheme::grad.
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > gradf (const GeometricField< Type, fvsPatchField, surfaceMesh > &, const word &name)
Return the gradient of the given field.
static void correctBoundaryConditions (const GeometricField< Type, fvPatchField, volMesh > &, GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > &)
Correct the boundary values of the gradient using the patchField.
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::fv::gaussGrad< Type >
Basic second-order gradient scheme using face-interpolation and Gauss' theorem.
Source files
gaussGrad.H
gaussGrad.C
Definition at line 57 of file gaussGrad.H.
Constructor & Destructor Documentation
gaussGrad() [1/2]
gaussGrad (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 84 of file gaussGrad.H.
gaussGrad() [2/2]
gaussGrad (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 91 of file gaussGrad.H.
References gaussGrad< Type >::calcGrad(), gaussGrad< Type >::correctBoundaryConditions(), IOstream::eof(), gaussGrad< Type >::gradf(), gradScheme< Type >::mesh(), Foam::name(), and surfaceInterpolationScheme< Type >::New().
Member Function Documentation
TypeName()
TypeName ("Gauss")
Runtime type information.
gradf()
static tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > gradf (const GeometricField< Type, fvsPatchField, surfaceMesh > & , const word & name) static
Return the gradient of the given field.
calculated using Gauss' theorem on the given surface field
Referenced by gaussGrad< Type >::gaussGrad(), and Foam::fvc::grad().
calcGrad()
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const virtual
Return the gradient of the given field to the gradScheme::grad.
for optional caching
Implements gradScheme< Type >.
Referenced by gaussGrad< Type >::gaussGrad().
correctBoundaryConditions()
void correctBoundaryConditions (const GeometricField< Type, fvPatchField, volMesh > & vsf, GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > & gGrad) static
Correct the boundary values of the gradient using the patchField.
snGrad functions
Definition at line 145 of file gaussGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, DimensionedField< Type, GeoMesh >::mesh(), n, and patchi.
Referenced by gaussGrad< Type >::gaussGrad().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/gradSchemes/gaussGrad/gaussGrad.H
src/finiteVolume/finiteVolume/gradSchemes/gaussGrad/gaussGrad.C