OpenFOAM: gradScheme< Type > Class Template Reference
gradScheme< Type > Class Template Reference abstract
Abstract base class for gradient schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const =0
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename outerProduct< vector, Type >::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::fv::gradScheme< Type >
Abstract base class for gradient schemes.
Source files
gradScheme.H
gradScheme.C
Definition at line 60 of file gradScheme.H.
Constructor & Destructor Documentation
gradScheme()
gradScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 99 of file gradScheme.H.
References gradScheme< Type >::New(), and gradScheme< Type >::~gradScheme().
~gradScheme()
~gradScheme () virtual
Destructor.
Definition at line 78 of file gradScheme.C.
References Foam::fvc::grad(), gradScheme< Type >::grad(), mesh, Foam::name(), IOobject::name(), and tmp< T >::ptr().
Referenced by gradScheme< Type >::gradScheme().
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (tmp , gradScheme< Type > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
Foam::tmp< Foam::fv::gradScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new gradScheme created on freestore.
Definition at line 34 of file gradScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fvc::grad(), and gradScheme< Type >::gradScheme().
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 122 of file gradScheme.H.
References gradScheme< Type >::calcGrad(), gradScheme< Type >::grad(), and Foam::name().
Referenced by gaussGrad< Type >::gaussGrad().
calcGrad()
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & , const word & name) const pure virtual
Calculate and return the grad of the given field.
Used by grad either to recalculate the cached gradient when it is out of date with respect to the field or when it is not cached.
Implemented in LeastSquaresGrad< Type, Stencil >, gaussGrad< Type >, faceLimitedGrad< Type >, faceMDLimitedGrad< Type >, cellLimitedGrad< Type >, cellMDLimitedGrad< Type >, leastSquaresGrad< Type >, and fourthGrad< Type >.
Referenced by gradScheme< Type >::mesh().
grad() [1/3]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > grad (const GeometricField< Type, fvPatchField, volMesh > & , const word & name) const
Calculate and return the grad of the given field.
which may have been cached
Referenced by faceLimitedGrad< Type >::calcGrad(), gradScheme< Type >::mesh(), and gradScheme< Type >::~gradScheme().
grad() [2/3]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
with the default name which may have been cached
grad() [3/3]
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
with the default name which may have been cached
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/gradSchemes/gradScheme/gradScheme.H
src/finiteVolume/finiteVolume/gradSchemes/gradScheme/gradScheme.C