OpenFOAM: localEulerDdt Class Reference
localEulerDdt Class Reference
Public Member Functions
localEulerDdt ()
Static Public Member Functions
static bool enabled (const fvMesh &mesh)
Return true if LTS is enabled.
static const volScalarField & localRDeltaT (const fvMesh &mesh)
Return the reciprocal of the local time-step.
static tmp< volScalarField > localRSubDeltaT (const fvMesh &mesh, const label nAlphaSubCycles)
Calculate and return the reciprocal of the local sub-cycling.
Static Public Attributes
static word rDeltaTName
Name of the reciprocal local time-step field.
static word rSubDeltaTName
Name of the reciprocal local sub-cycling time-step field.
Detailed Description
Definition at line 64 of file localEulerDdtScheme.H.
Constructor & Destructor Documentation
localEulerDdt()
localEulerDdt () inline
Definition at line 77 of file localEulerDdtScheme.H.
References localEulerDdt::enabled(), localEulerDdt::localRDeltaT(), localEulerDdt::localRSubDeltaT(), mesh, and nAlphaSubCycles().
Member Function Documentation
enabled()
bool enabled (const fvMesh & mesh) static
Return true if LTS is enabled.
Definition at line 36 of file localEulerDdt.C.
References fvSchemes::ddtScheme(), and localEulerDdt::localRDeltaT().
Referenced by localEulerDdt::localEulerDdt().
localRDeltaT()
const Foam::volScalarField & localRDeltaT (const fvMesh & mesh) static
Return the reciprocal of the local time-step.
looked-up from the objectRegistry
Definition at line 45 of file localEulerDdt.C.
References localEulerDdt::localRSubDeltaT(), localEulerDdt::rDeltaTName, localEulerDdt::rSubDeltaTName, Time::subCycling(), and fvMesh::time().
Referenced by localEulerDdt::enabled(), and localEulerDdt::localEulerDdt().
localRSubDeltaT()
Foam::tmp< Foam::volScalarField > localRSubDeltaT (const fvMesh & mesh, const label nAlphaSubCycles) static
Calculate and return the reciprocal of the local sub-cycling.
time-step
Definition at line 57 of file localEulerDdt.C.
References localEulerDdt::rDeltaTName, and localEulerDdt::rSubDeltaTName.
Referenced by localEulerDdt::localEulerDdt(), and localEulerDdt::localRDeltaT().
Member Data Documentation
rDeltaTName
Foam::word rDeltaTName static
Name of the reciprocal local time-step field.
Definition at line 69 of file localEulerDdtScheme.H.
Referenced by localEulerDdt::localRDeltaT(), and localEulerDdt::localRSubDeltaT().
rSubDeltaTName
Foam::word rSubDeltaTName static
Name of the reciprocal local sub-cycling time-step field.
Definition at line 72 of file localEulerDdtScheme.H.
Referenced by localEulerDdt::localRDeltaT(), and localEulerDdt::localRSubDeltaT().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/localEulerDdtScheme/localEulerDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/localEulerDdtScheme/localEulerDdt.C