OpenFOAM: divScheme< Type > Class Template Reference
divScheme< Type > Class Template Reference abstract
Abstract base class for div schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, divScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
divScheme (const fvMesh &mesh)
Construct from mesh.
divScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual ~divScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvPatchField, volMesh > > fvcDiv (const GeometricField< Type, fvPatchField, volMesh > &)=0
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< divScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new divScheme created on freestore.
Protected Member Functions
divScheme (const divScheme &)
Disallow copy construct.
void operator= (const divScheme &)
Disallow default bitwise assignment.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes
const fvMesh & mesh_
tmp< surfaceInterpolationScheme< Type > > tinterpScheme_
Detailed Description
template<class Type>
class Foam::fv::divScheme< Type >
Abstract base class for div schemes.
Source files
divScheme.H
divScheme.C
Definition at line 64 of file divScheme.H.
Constructor & Destructor Documentation
divScheme() [1/3]
divScheme (const divScheme< Type > &) protected
Disallow copy construct.
divScheme() [2/3]
divScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 107 of file divScheme.H.
divScheme() [3/3]
divScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 114 of file divScheme.H.
References divScheme< Type >::New(), and divScheme< Type >::~divScheme().
~divScheme()
~divScheme () virtual
Destructor.
Definition at line 92 of file divScheme.C.
Referenced by divScheme< Type >::divScheme().
Member Function Documentation
operator=()
void operator= (const divScheme< Type > &) protected
Disallow default bitwise assignment.
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (tmp , divScheme< Type > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
tmp< divScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new divScheme created on freestore.
Definition at line 47 of file divScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fvc::div(), and divScheme< Type >::divScheme().
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 138 of file divScheme.H.
References divScheme< Type >::fvcDiv(), and divScheme< Type >::mesh_.
fvcDiv()
virtual tmp< GeometricField <typename innerProduct<vector, Type>::type, fvPatchField, volMesh> > fvcDiv (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussDivScheme< Type >.
Referenced by divScheme< Type >::mesh().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 73 of file divScheme.H.
Referenced by divScheme< Type >::mesh().
tinterpScheme_
tmp<surfaceInterpolationScheme<Type> > tinterpScheme_ protected
Definition at line 74 of file divScheme.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/divSchemes/divScheme/divScheme.H
src/finiteVolume/finiteVolume/divSchemes/divScheme/divScheme.C