OpenFOAM: steadyStateDdtScheme< Type > Class Template Reference
steadyStateDdtScheme< Type > Class Template Reference
SteadyState implicit/explicit ddt which returns 0.
Public Types
typedef ddtScheme< Type >::fluxFieldType fluxFieldType
Public Types inherited from ddtScheme< Type >
typedef GeometricField< typename flux< Type >::type, fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
TypeName ("steadyState")
Runtime type information.
steadyStateDdtScheme (const fvMesh &mesh)
Construct from mesh.
steadyStateDdtScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &psi)
tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)
tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > &U, const GeometricField< scalar, fvsPatchField, surfaceMesh > &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &U, const surfaceScalarField &phi)
template<>
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &Uf)
template<>
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField &rho, const volScalarField &U, const surfaceScalarField &phi)
Public Member Functions inherited from ddtScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
Construct from mesh.
ddtScheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~ddtScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from ddtScheme< Type >
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new ddtScheme created on freestore.
Protected Member Functions inherited from ddtScheme< Type >
ddtScheme (const ddtScheme &)
Disallow copy construct.
void operator= (const ddtScheme &)
Disallow default bitwise assignment.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes inherited from ddtScheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::steadyStateDdtScheme< Type >
SteadyState implicit/explicit ddt which returns 0.
Source files
steadyStateDdtScheme.H
steadyStateDdtScheme.C
Definition at line 54 of file steadyStateDdtScheme.H.
Member Typedef Documentation
fluxFieldType
typedef ddtScheme<Type>::fluxFieldType fluxFieldType
Definition at line 149 of file steadyStateDdtScheme.H.
Constructor & Destructor Documentation
steadyStateDdtScheme() [1/2]
steadyStateDdtScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 76 of file steadyStateDdtScheme.H.
steadyStateDdtScheme() [2/2]
steadyStateDdtScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 82 of file steadyStateDdtScheme.H.
Member Function Documentation
TypeName()
TypeName ("steadyState")
Runtime type information.
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 91 of file steadyStateDdtScheme.H.
References Foam::constant::atomic::alpha, steadyStateDdtScheme< Type >::fvcDdt(), steadyStateDdtScheme< Type >::fvmDdt(), ddtScheme< Type >::mesh(), psi, and rho.
fvcDdt() [1/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > & dt) virtual
Implements ddtScheme< Type >.
Definition at line 45 of file steadyStateDdtScheme.C.
References dimensioned< Type >::dimensions(), Foam::dimTime, mesh, dimensioned< Type >::name(), and Foam::Zero.
Referenced by steadyStateDdtScheme< Type >::fvcDdt(), and steadyStateDdtScheme< Type >::mesh().
fvcDdt() [2/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 74 of file steadyStateDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, steadyStateDdtScheme< Type >::fvcDdt(), mesh, IOobject::name(), and Foam::Zero.
fvcDdt() [3/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 103 of file steadyStateDdtScheme.C.
References dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, steadyStateDdtScheme< Type >::fvcDdt(), mesh, dimensioned< Type >::name(), IOobject::name(), and Foam::Zero.
fvcDdt() [4/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 133 of file steadyStateDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, steadyStateDdtScheme< Type >::fvcDdt(), mesh, IOobject::name(), and Foam::Zero.
fvcDdt() [5/5]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 163 of file steadyStateDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, steadyStateDdtScheme< Type >::fvmDdt(), mesh, IOobject::name(), and Foam::Zero.
fvmDdt() [1/4]
tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 194 of file steadyStateDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, and Foam::dimVol.
Referenced by steadyStateDdtScheme< Type >::fvcDdt(), steadyStateDdtScheme< Type >::fvmDdt(), and steadyStateDdtScheme< Type >::mesh().
fvmDdt() [2/4]
tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 214 of file steadyStateDdtScheme.C.
References dimensioned< Type >::dimensions(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, and steadyStateDdtScheme< Type >::fvmDdt().
fvmDdt() [3/4]
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 235 of file steadyStateDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, and steadyStateDdtScheme< Type >::fvmDdt().
fvmDdt() [4/4]
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & psi) virtual
Implements ddtScheme< Type >.
Definition at line 256 of file steadyStateDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVol, and steadyStateDdtScheme< Type >::fvcDdtUfCorr().
fvcDdtUfCorr() [1/4]
tmp< typename steadyStateDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 278 of file steadyStateDdtScheme.C.
References Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), mesh, IOobject::name(), and Foam::Zero.
Referenced by steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), and steadyStateDdtScheme< Type >::fvmDdt().
fvcDdtPhiCorr() [1/4]
tmp< typename steadyStateDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 308 of file steadyStateDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, steadyStateDdtScheme< Type >::fvcDdtUfCorr(), mesh, IOobject::name(), and Foam::Zero.
Referenced by steadyStateDdtScheme< Type >::fvcDdtUfCorr().
fvcDdtUfCorr() [2/4]
tmp< typename steadyStateDdtScheme< Type >::fluxFieldType > fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) virtual
Implements ddtScheme< Type >.
Definition at line 338 of file steadyStateDdtScheme.C.
References Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), mesh, IOobject::name(), and Foam::Zero.
fvcDdtPhiCorr() [2/4]
tmp< typename steadyStateDdtScheme< Type >::fluxFieldType > fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) virtual
Implements ddtScheme< Type >.
Definition at line 371 of file steadyStateDdtScheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, mesh, steadyStateDdtScheme< Type >::meshPhi(), IOobject::name(), and Foam::Zero.
meshPhi()
tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements ddtScheme< Type >.
Definition at line 403 of file steadyStateDdtScheme.C.
References Foam::dimTime, Foam::dimVolume, mesh, IOobject::NO_READ, IOobject::NO_WRITE, and timeName.
Referenced by steadyStateDdtScheme< Type >::fvcDdtPhiCorr().
fvcDdtUfCorr() [3/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const GeometricField< scalar, fvPatchField, volMesh > & U, const GeometricField< scalar, fvsPatchField, surfaceMesh > & Uf)
fvcDdtPhiCorr() [3/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & U, const surfaceScalarField & phi)
fvcDdtUfCorr() [4/4]
tmp< surfaceScalarField > fvcDdtUfCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & Uf)
fvcDdtPhiCorr() [4/4]
tmp< surfaceScalarField > fvcDdtPhiCorr (const volScalarField & rho, const volScalarField & U, const surfaceScalarField & phi)
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/steadyStateDdtScheme/steadyStateDdtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/steadyStateDdtScheme/steadyStateDdtScheme.C