OpenFOAM: orthogonalSnGrad< Type > Class Template Reference
orthogonalSnGrad< Type > Class Template Reference
Simple central-difference snGrad scheme without non-orthogonal correction.
Public Member Functions
TypeName ("orthogonal")
Runtime type information.
orthogonalSnGrad (const fvMesh &mesh)
Construct from mesh.
orthogonalSnGrad (const fvMesh &mesh, Istream &)
Construct from mesh and data stream.
virtual ~orthogonalSnGrad ()
Destructor.
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the orthogonalSnGrad.
Public Member Functions inherited from snGradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~snGradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the snGrad of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the snGrad of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from snGradScheme< Type >
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
Return the snGrad of the given cell field with the given deltaCoeffs.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Return the sndGrad of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::fv::orthogonalSnGrad< Type >
Simple central-difference snGrad scheme without non-orthogonal correction.
Source files
orthogonalSnGrad.H
orthogonalSnGrad.C
Definition at line 54 of file orthogonalSnGrad.H.
Constructor & Destructor Documentation
orthogonalSnGrad() [1/2]
orthogonalSnGrad (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 73 of file orthogonalSnGrad.H.
orthogonalSnGrad() [2/2]
orthogonalSnGrad (const fvMesh & mesh, Istream &) inline
Construct from mesh and data stream.
Definition at line 80 of file orthogonalSnGrad.H.
References orthogonalSnGrad< Type >::deltaCoeffs(), and orthogonalSnGrad< Type >::~orthogonalSnGrad().
~orthogonalSnGrad()
~orthogonalSnGrad () virtual
Destructor.
Definition at line 46 of file orthogonalSnGrad.C.
References orthogonalSnGrad< Type >::correction().
Referenced by orthogonalSnGrad< Type >::orthogonalSnGrad().
Member Function Documentation
TypeName()
TypeName ("orthogonal")
Runtime type information.
deltaCoeffs()
virtual tmp<surfaceScalarField> deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors for the given field.
Implements snGradScheme< Type >.
Definition at line 94 of file orthogonalSnGrad.H.
References surfaceInterpolation::deltaCoeffs(), and snGradScheme< Type >::mesh().
Referenced by orthogonalSnGrad< Type >::orthogonalSnGrad().
corrected()
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from snGradScheme< Type >.
Definition at line 102 of file orthogonalSnGrad.H.
References orthogonalSnGrad< Type >::correction().
correction()
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const virtual
Return the explicit correction to the orthogonalSnGrad.
for the given field
Reimplemented from snGradScheme< Type >.
Definition at line 55 of file orthogonalSnGrad.C.
References NotImplemented.
Referenced by orthogonalSnGrad< Type >::corrected(), and orthogonalSnGrad< Type >::~orthogonalSnGrad().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/orthogonalSnGrad/orthogonalSnGrad.H
src/finiteVolume/finiteVolume/snGradSchemes/orthogonalSnGrad/orthogonalSnGrad.C