OpenFOAM: CentredFitSnGradData< Polynomial > Class Template Reference
CentredFitSnGradData< Polynomial > Class Template Reference
Data for centred fit snGrad schemes.
Public Member Functions
TypeName ("CentredFitSnGradData")
CentredFitSnGradData (const fvMesh &mesh, const extendedCentredCellToFaceStencil &stencil, const scalar linearLimitFactor, const scalar centralWeight)
Construct from components.
virtual ~CentredFitSnGradData ()
Destructor.
const List< scalarList > & coeffs () const
Return reference to fit coefficients.
void calcFit (scalarList &coeffsi, const List< point > &, const scalar wLin, const scalar deltaCoeff, const label faci)
Calculate the fit for the specified face and set the coefficients.
void calcFit ()
Calculate the fit for all the faces.
Public Member Functions inherited from FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >
FitData (const fvMesh &mesh, const extendedCentredCellToFaceStencil &stencil, const bool linearCorrection, const scalar linearLimitFactor, const scalar centralWeight)
Construct from components.
virtual ~FitData ()
Destructor.
const extendedCentredCellToFaceStencil & stencil () const
Return reference to the stencil.
scalar linearLimitFactor () const
Factor the fit is allowed to deviate from the base scheme.
scalar centralWeight () const
Return weight for central stencil.
label dim () const
Dimensionality of the geometry.
label minSize () const
Minimum stencil size.
bool linearCorrection () const
void calcFit (scalarList &coeffsi, const List< point > &, const scalar wLin, const label faci)
Calculate the fit for the specified face and set the coefficients.
bool movePoints ()
Recalculate weights (but not stencil) when the mesh moves.
Public Member Functions inherited from MeshObject< fvMesh, MoveableMeshObject, CentredFitSnGradData< Polynomial > >
MeshObject (const fvMesh &mesh)
virtual ~MeshObject ()
const fvMesh & mesh () const
virtual bool writeData (Foam::Ostream &) const
Public Member Functions inherited from MoveableMeshObject< fvMesh >
MoveableMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from GeometricMeshObject< fvMesh >
GeometricMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from TopologicalMeshObject< fvMesh >
TopologicalMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from meshObject
ClassName ("meshObject")
meshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from MeshObject< fvMesh, MoveableMeshObject, CentredFitSnGradData< Polynomial > >
static const CentredFitSnGradData< Polynomial > & New (const fvMesh &mesh)
static const CentredFitSnGradData< Polynomial > & New (const fvMesh &mesh, const Data1 &d)
static const CentredFitSnGradData< Polynomial > & New (const fvMesh &mesh, const Data1 &, const Data2 &)
static const CentredFitSnGradData< Polynomial > & New (const fvMesh &mesh, const Data1 &, const Data2 &, const Data3 &)
static const CentredFitSnGradData< Polynomial > & New (const fvMesh &mesh, const Data1 &, const Data2 &, const Data3 &, const Data4 &)
static bool Delete (const fvMesh &mesh)
Static Public Member Functions inherited from meshObject
template<class Mesh >
static void movePoints (objectRegistry &)
template<class Mesh >
static void updateMesh (objectRegistry &, const mapPolyMesh &)
template<class Mesh , template< class > class MeshObjectType>
static void clear (objectRegistry &)
template<class Mesh , template< class > class FromType, template< class > class ToType>
static void clearUpto (objectRegistry &)
Clear all meshObject derived from FromType up to (but not including)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >
void findFaceDirs (vector &idir, vector &jdir, vector &kdir, const label faci)
Find the normal direction (i) and j and k directions for face faci.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes inherited from MeshObject< fvMesh, MoveableMeshObject, CentredFitSnGradData< Polynomial > >
const fvMesh & mesh_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Polynomial>
class Foam::CentredFitSnGradData< Polynomial >
Data for centred fit snGrad schemes.
Source files
CentredFitSnGradData.H
CentredFitSnGradData.C
Definition at line 51 of file CentredFitSnGradData.H.
Constructor & Destructor Documentation
CentredFitSnGradData()
CentredFitSnGradData (const fvMesh & mesh, const extendedCentredCellToFaceStencil & stencil, const scalar linearLimitFactor, const scalar centralWeight)
Construct from components.
Definition at line 35 of file CentredFitSnGradData.C.
References CentredFitSnGradData< Polynomial >::calcFit(), Foam::endl(), Foam::Info, and InfoInFunction.
~CentredFitSnGradData()
virtual ~CentredFitSnGradData () inline virtual
Destructor.
Definition at line 85 of file CentredFitSnGradData.H.
Member Function Documentation
TypeName()
TypeName ("CentredFitSnGradData< Polynomial >")
coeffs()
const List<scalarList>& coeffs () const inline
Return reference to fit coefficients.
Definition at line 92 of file CentredFitSnGradData.H.
References CentredFitSnGradData< Polynomial >::calcFit().
Referenced by CentredFitSnGradScheme< Type, Polynomial, Stencil >::correction().
calcFit() [1/2]
void calcFit (scalarList & coeffsi, const List< point > & C, const scalar wLin, const scalar deltaCoeff, const label faci)
Calculate the fit for the specified face and set the coefficients.
Definition at line 72 of file CentredFitSnGradData.C.
References Foam::cmptMag(), Foam::cmptMax(), Foam::endl(), forAll, Foam::mag(), mesh, Foam::nl, p, SVD::S(), List< T >::setSize(), List< T >::size(), Foam::sum(), SVD::VSinvUt(), WarningInFunction, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
calcFit() [2/2]
void calcFit () virtual
Calculate the fit for all the faces.
Implements FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >.
Definition at line 209 of file CentredFitSnGradData.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvsPatchField< Type >::coupled(), forAll, mesh, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), surfaceInterpolation::nonOrthDeltaCoeffs(), fvsPatchField< Type >::patch(), patchi, and fvPatch::start().
Referenced by CentredFitSnGradData< Polynomial >::CentredFitSnGradData(), and CentredFitSnGradData< Polynomial >::coeffs().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/CentredFitSnGrad/CentredFitSnGradData.H
src/finiteVolume/finiteVolume/snGradSchemes/CentredFitSnGrad/CentredFitSnGradData.C