OpenFOAM: volRegion Class Reference
volRegion Class Reference
FunctionObjects » Field function objects
Volume (cell) region selection class.
Public Types
enum regionTypes { vrtCellZone, vrtAll }
Region type enumeration.
Public Member Functions
TypeName ("volRegion")
Run-time type information.
volRegion (const fvMesh &mesh, const dictionary &dict)
Construct from fvMesh and dictionary.
virtual ~volRegion ()
Destructor.
bool read (const dictionary &)
Read from dictionary.
const regionTypes & regionType () const
Return the region type.
const labelList & cellIDs () const
Return the local list of cell IDs.
label nCells () const
Return the number of cells in the region.
scalar V () const
Return total volume of the region.
Static Public Attributes
static const NamedEnum< regionTypes, 2 > regionTypeNames_
Region type names.
Protected Member Functions
void writeFileHeader (const writeFile &wf, Ostream &file)
Output file header information.
Protected Attributes
regionTypes regionType_
Region type.
word regionName_
Region name (patch, zone, etc.)
label regionID_
Region ID (patch ID, zone ID, etc.)
Detailed Description
Volume (cell) region selection class.
Examples of function object specification:
volRegion0
{
    .
    .
    regionType      cellZone;
    name            c0;
    .
    .
}
volRegionAll
{
    .
    .
    regionType      all;
    .
    .
}
Usage
Property Description Required Default value
regionType cellZone or all no all
name Name of cellZone if required no
See also
Foam::functionObject
Source files
volRegion.H
volRegion.C
Definition at line 105 of file volRegion.H.
Member Enumeration Documentation
regionTypes
enum regionTypes
Region type enumeration.
Enumerator
vrtCellZone
vrtAll
Definition at line 121 of file volRegion.H.
Constructor & Destructor Documentation
volRegion()
volRegion (const fvMesh & mesh, const dictionary & dict)
Construct from fvMesh and dictionary.
Definition at line 74 of file volRegion.C.
References Foam::read().
Referenced by volRegion::writeFileHeader().
~volRegion()
~volRegion () virtual
Destructor.
Definition at line 98 of file volRegion.C.
References volRegion::read().
Member Function Documentation
writeFileHeader()
void writeFileHeader (const writeFile & wf, Ostream & file) protected
Output file header information.
Definition at line 58 of file volRegion.C.
References Foam::endl(), Foam::setw(), volRegion::volRegion(), writeFile::writeCommented(), and writeFile::writeHeaderValue().
Referenced by NamedEnum< directionType, 3 >::names(), and volFieldValue::writeFileHeader().
TypeName()
TypeName ("volRegion")
Run-time type information.
read()
bool read (const dictionary & dict)
Read from dictionary.
Definition at line 105 of file volRegion.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::lookup(), and Foam::nl.
Referenced by volRegion::~volRegion().
regionType()
const Foam::functionObjects::volRegion::regionTypes & regionType () const inline
Return the region type.
Definition at line 29 of file volRegionI.H.
References volRegion::regionType_.
cellIDs()
const Foam::labelList & cellIDs () const
Return the local list of cell IDs.
Definition at line 155 of file volRegion.C.
References List< label >::null().
nCells()
Foam::label nCells () const
Return the number of cells in the region.
Definition at line 168 of file volRegion.C.
References Foam::returnReduce().
V()
Foam::scalar V () const
Return total volume of the region.
Definition at line 181 of file volRegion.C.
References Foam::gSum().
Member Data Documentation
regionTypeNames_
const Foam::NamedEnum< Foam::functionObjects::volRegion::regionTypes, 2 > regionTypeNames_ static
Region type names.
Definition at line 128 of file volRegion.H.
Referenced by NamedEnum< directionType, 3 >::names().
regionType_
regionTypes regionType_ protected
Region type.
Definition at line 136 of file volRegion.H.
Referenced by volRegion::regionType().
regionName_
word regionName_ protected
Region name (patch, zone, etc.)
Definition at line 139 of file volRegion.H.
regionID_
label regionID_ protected
Region ID (patch ID, zone ID, etc.)
Definition at line 142 of file volRegion.H.
The documentation for this class was generated from the following files:
src/finiteVolume/functionObjects/volRegion/volRegion.H
src/finiteVolume/functionObjects/volRegion/volRegion.C
src/finiteVolume/functionObjects/volRegion/volRegionI.H