OpenFOAM: laplacianScheme< Type, GType > Class Template Reference
laplacianScheme< Type, GType > Class Template Reference abstract
Abstract base class for laplacian schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, laplacianScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
laplacianScheme (const fvMesh &mesh)
Construct from mesh.
laplacianScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
laplacianScheme (const fvMesh &mesh, const tmp< surfaceInterpolationScheme< GType >> &igs, const tmp< snGradScheme< Type >> &sngs)
Construct from mesh, interpolation and snGradScheme schemes.
virtual ~laplacianScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< laplacianScheme< Type, GType > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new laplacianScheme created on freestore.
Protected Attributes
const fvMesh & mesh_
tmp< surfaceInterpolationScheme< GType > > tinterpGammaScheme_
tmp< snGradScheme< Type > > tsnGradScheme_
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type, class GType>
class Foam::fv::laplacianScheme< Type, GType >
Abstract base class for laplacian schemes.
Source files
laplacianScheme.H
laplacianScheme.C
Definition at line 65 of file laplacianScheme.H.
Constructor & Destructor Documentation
laplacianScheme() [1/3]
laplacianScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 111 of file laplacianScheme.H.
laplacianScheme() [2/3]
laplacianScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 119 of file laplacianScheme.H.
References snGradScheme< Type >::New(), and surfaceInterpolationScheme< Type >::New().
laplacianScheme() [3/3]
laplacianScheme (const fvMesh & mesh, const tmp< surfaceInterpolationScheme< GType >> & igs, const tmp< snGradScheme< Type >> & sngs) inline
Construct from mesh, interpolation and snGradScheme schemes.
Definition at line 138 of file laplacianScheme.H.
References laplacianScheme< Type, GType >::New(), and laplacianScheme< Type, GType >::~laplacianScheme().
~laplacianScheme()
~laplacianScheme () virtual
Destructor.
Definition at line 89 of file laplacianScheme.C.
References laplacianScheme< Type, GType >::fvmLaplacian().
Referenced by laplacianScheme< Type, GType >::laplacianScheme().
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (tmp , laplacianScheme< Type, GType > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
tmp< laplacianScheme< Type, GType > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new laplacianScheme created on freestore.
Definition at line 45 of file laplacianScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fvc::laplacian(), Foam::fvm::laplacian(), and laplacianScheme< Type, GType >::laplacianScheme().
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 167 of file laplacianScheme.H.
References laplacianScheme< Type, GType >::fvcLaplacian(), laplacianScheme< Type, GType >::fvmLaplacian(), and laplacianScheme< Type, GType >::mesh_.
fvmLaplacian() [1/2]
virtual tmp<fvMatrix<Type> > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >.
Referenced by laplacianScheme< Type, GType >::mesh(), and laplacianScheme< Type, GType >::~laplacianScheme().
fvmLaplacian() [2/2]
tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Definition at line 98 of file laplacianScheme.C.
References laplacianScheme< Type, GType >::fvcLaplacian(), and Foam::interpolate().
fvcLaplacian() [1/3]
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >.
Referenced by laplacianScheme< Type, GType >::fvmLaplacian(), and laplacianScheme< Type, GType >::mesh().
fvcLaplacian() [2/3]
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >.
fvcLaplacian() [3/3]
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Definition at line 110 of file laplacianScheme.C.
References Foam::interpolate().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 74 of file laplacianScheme.H.
Referenced by laplacianScheme< Type, GType >::mesh().
tinterpGammaScheme_
tmp<surfaceInterpolationScheme<GType> > tinterpGammaScheme_ protected
Definition at line 75 of file laplacianScheme.H.
tsnGradScheme_
tmp<snGradScheme<Type> > tsnGradScheme_ protected
Definition at line 76 of file laplacianScheme.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/laplacianSchemes/laplacianScheme/laplacianScheme.H
src/finiteVolume/finiteVolume/laplacianSchemes/laplacianScheme/laplacianScheme.C