OpenFOAM: limitedSnGrad< Type > Class Template Reference
limitedSnGrad< Type > Class Template Reference
Run-time selected snGrad scheme with limited non-orthogonal correction.
Public Member Functions
TypeName ("limited")
Runtime type information.
limitedSnGrad (const fvMesh &mesh)
Construct from mesh.
limitedSnGrad (const fvMesh &mesh, Istream &schemeData)
Construct from mesh and data stream.
virtual ~limitedSnGrad ()
Destructor.
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the limitedSnGrad.
Public Member Functions inherited from snGradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~snGradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the snGrad of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the snGrad of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from snGradScheme< Type >
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
Return the snGrad of the given cell field with the given deltaCoeffs.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Return the sndGrad of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::fv::limitedSnGrad< Type >
Run-time selected snGrad scheme with limited non-orthogonal correction.
The limiter is controlled by a coefficient with a value between 0 and 1 which when 0 switches the correction off and the scheme behaves as uncorrectedSnGrad, when set to 1 the full correction of the selected scheme is used and when set to 0.5 the limiter is calculated such that the non-orthogonal contribution does not exceed the orthogonal part.
Format: limited <corrected scheme> <coefficient>;
or
limited <coefficient>; // Backward compatibility
Source files
limitedSnGrad.H
limitedSnGrad.C
Definition at line 67 of file limitedSnGrad.H.
Constructor & Destructor Documentation
limitedSnGrad() [1/2]
limitedSnGrad (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 121 of file limitedSnGrad.H.
limitedSnGrad() [2/2]
limitedSnGrad (const fvMesh & mesh, Istream & schemeData) inline
Construct from mesh and data stream.
Definition at line 130 of file limitedSnGrad.H.
References limitedSnGrad< Type >::deltaCoeffs(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and limitedSnGrad< Type >::~limitedSnGrad().
~limitedSnGrad()
~limitedSnGrad () virtual
Destructor.
Definition at line 45 of file limitedSnGrad.C.
References limitedSnGrad< Type >::correction().
Referenced by limitedSnGrad< Type >::limitedSnGrad().
Member Function Documentation
TypeName()
TypeName ("limited")
Runtime type information.
deltaCoeffs()
virtual tmp<surfaceScalarField> deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors for the given field.
Implements snGradScheme< Type >.
Definition at line 155 of file limitedSnGrad.H.
References snGradScheme< Type >::mesh(), and surfaceInterpolation::nonOrthDeltaCoeffs().
Referenced by limitedSnGrad< Type >::limitedSnGrad().
corrected()
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from snGradScheme< Type >.
Definition at line 163 of file limitedSnGrad.H.
References limitedSnGrad< Type >::correction().
correction()
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the explicit correction to the limitedSnGrad.
for the given field
Reimplemented from snGradScheme< Type >.
Definition at line 54 of file limitedSnGrad.C.
References Foam::average(), Foam::correction(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimless, Foam::endl(), InfoInFunction, Foam::MULES::limiter(), Foam::mag(), Foam::max(), Foam::min(), and GeometricField< Type, PatchField, GeoMesh >::primitiveField().
Referenced by limitedSnGrad< Type >::corrected(), and limitedSnGrad< Type >::~limitedSnGrad().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/limitedSnGrad/limitedSnGrad.H
src/finiteVolume/finiteVolume/snGradSchemes/limitedSnGrad/limitedSnGrad.C