OpenFOAM: extendedCellToFaceStencil Class Reference
extendedCellToFaceStencil Class Reference
Calculates/constains the extended cell-to-face stencil.
Public Member Functions
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type >> &stencilFld)
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Static Public Member Functions
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T >> &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Sum vol field contributions to create face values.
Static Protected Member Functions
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Write some statistics about stencil.
Protected Attributes
const polyMesh & mesh_
Detailed Description
Calculates/constains the extended cell-to-face stencil.
The stencil is a list of indices into either cells or boundary faces in a compact way. (element 0 is owner, 1 is neighbour). The index numbering is
cells first
then all (non-empty patch) boundary faces
When used in evaluation is a two stage process:
collect the data (cell data and non-empty boundaries) into a single field
(parallel) distribute the field
sum the weights*field.
Source files
extendedCellToFaceStencil.H
extendedCellToFaceStencil.C
extendedCellToFaceStencilTemplates.C
Definition at line 65 of file extendedCellToFaceStencil.H.
Constructor & Destructor Documentation
extendedCellToFaceStencil()
extendedCellToFaceStencil (const polyMesh & mesh) explicit
Construct from mesh.
Definition at line 100 of file extendedCellToFaceStencil.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, patchIdentifier::name(), coupledPolyPatch::parallel(), patches, patchi, and coupledPolyPatch::separated().
Member Function Documentation
writeStencilStats()
void writeStencilStats (Ostream & os, const labelListList & stencil, const mapDistribute & map) static protected
Write some statistics about stencil.
Definition at line 42 of file extendedCellToFaceStencil.C.
References Foam::endl(), forAll, Foam::labelMax, Foam::labelMin, Foam::max(), Foam::min(), UPstream::myProcNo(), Foam::nl, Foam::reduce(), Foam::returnReduce(), List< T >::size(), and mapDistributeBase::subMap().
Referenced by centredCECCellToFaceStencilObject::centredCECCellToFaceStencilObject(), centredCFCCellToFaceStencilObject::centredCFCCellToFaceStencilObject(), centredCPCCellToFaceStencilObject::centredCPCCellToFaceStencilObject(), centredFECCellToFaceStencilObject::centredFECCellToFaceStencilObject(), pureUpwindCFCCellToFaceStencilObject::pureUpwindCFCCellToFaceStencilObject(), upwindCECCellToFaceStencilObject::upwindCECCellToFaceStencilObject(), upwindCFCCellToFaceStencilObject::upwindCFCCellToFaceStencilObject(), upwindCPCCellToFaceStencilObject::upwindCPCCellToFaceStencilObject(), and upwindFECCellToFaceStencilObject::upwindFECCellToFaceStencilObject().
ClassName()
ClassName ("extendedCellToFaceStencil")
collectData() [1/2]
static void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< T, fvPatchField, volMesh > & fld, List< List< T >> & stencilFld) static
Use map to get the data into stencil order.
Referenced by extendedCentredCellToFaceStencil::collectData(), extendedCentredCellToCellStencil::collectData(), and extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil().
weightedSum() [1/2]
static tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar >> & stencilWeights) static
Sum vol field contributions to create face values.
Referenced by extendedCellToFaceStencil::collectData(), and extendedCentredCellToFaceStencil::weightedSum().
collectData() [2/2]
void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, List< List< Type >> & stencilFld)
Definition at line 32 of file extendedCellToFaceStencilTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mapDistributeBase::constructSize(), mapDistribute::distribute(), forAll, DimensionedField< Type, GeoMesh >::mesh(), fvPatchField< Type >::patch(), patchi, List< T >::setSize(), List< T >::size(), extendedCellToFaceStencil::weightedSum(), and Foam::Zero.
weightedSum() [2/2]
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar >> & stencilWeights)
Definition at line 86 of file extendedCellToFaceStencilTemplates.C.
References fvsPatchField< Type >::coupled(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), primitiveMesh::nInternalFaces(), fvsPatchField< Type >::patch(), patchi, sf(), fvMesh::time(), Time::timeName(), and Foam::Zero.
Member Data Documentation
mesh_
const polyMesh& mesh_ protected
Definition at line 71 of file extendedCellToFaceStencil.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCellToFaceStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCellToFaceStencil.C
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCellToFaceStencilTemplates.C