OpenFOAM: fvMatrix< Type >::fvSolver Class Reference
fvMatrix< Type >::fvSolver Class Reference
Solver class returned by the solver function.
Public Member Functions
fvSolver (fvMatrix< Type > &fvMat, autoPtr< lduMatrix::solver > sol)
SolverPerformance< Type > solve (const dictionary &)
Solve returning the solution statistics.
SolverPerformance< Type > solve ()
Solve returning the solution statistics.
template<>
Foam::solverPerformance solve (const dictionary &solverControls)
template<>
solverPerformance solve (const dictionary &)
Detailed Description
template<class Type>
class Foam::fvMatrix< Type >::fvSolver
Solver class returned by the solver function.
used for systems in which it is useful to cache the solver for reuse e.g. if the solver is potentially expensive to construct (AMG) and can be used several times (PISO)
Definition at line 220 of file fvMatrix.H.
Constructor & Destructor Documentation
fvSolver()
fvSolver (fvMatrix< Type > & fvMat, autoPtr< lduMatrix::solver > sol) inline
Definition at line 230 of file fvMatrix.H.
References fvMatrix< Type >::ClassName(), fvMatrix< Type >::fvMatrix(), fvMatrix< Type >::fvSolver::solve(), and fvMatrix< Type >::~fvMatrix().
Member Function Documentation
solve() [1/4]
SolverPerformance<Type> solve (const dictionary &)
Solve returning the solution statistics.
Use the given solver controls
solve() [2/4]
Foam::SolverPerformance< Type > solve ()
Solve returning the solution statistics.
Solver controls read from fvSolution
Definition at line 297 of file fvMatrixSolve.C.
Referenced by fvMatrix< Type >::faceFluxCorrectionPtr(), fvMatrix< Type >::fvSolver::fvSolver(), fvMatrix< Type >::solve(), and fvMatrix< Type >::solver().
solve() [3/4]
Foam::solverPerformance solve (const dictionary & solverControls)
Definition at line 98 of file fvScalarMatrix.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::Info, messageStream::masterStream(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), SolverPerformance< Type >::print(), psi, and fvMatrix< Type >::solveSegregated().
solve() [4/4]
solverPerformance solve (const dictionary &)
The documentation for this class was generated from the following files:
src/finiteVolume/fvMatrices/fvMatrix/fvMatrix.H
src/finiteVolume/fvMatrices/fvMatrix/fvMatrixSolve.C