OpenFOAM: snGradScheme< Type > Class Template Reference
snGradScheme< Type > Class Template Reference abstract
Abstract base class for snGrad schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~snGradScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const =0
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the snGrad.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the snGrad of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the snGrad of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
Return the snGrad of the given cell field with the given deltaCoeffs.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Return the sndGrad of the given cell field.
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::fv::snGradScheme< Type >
Abstract base class for snGrad schemes.
Source files
snGradScheme.H
snGradScheme.C
Definition at line 60 of file snGradScheme.H.
Constructor & Destructor Documentation
snGradScheme()
snGradScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 100 of file snGradScheme.H.
References snGradScheme< Type >::New(), and snGradScheme< Type >::~snGradScheme().
~snGradScheme()
~snGradScheme () virtual
Destructor.
Definition at line 92 of file snGradScheme.C.
References snGradScheme< Type >::snGrad().
Referenced by snGradScheme< Type >::snGradScheme().
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (tmp , snGradScheme< Type > , Mesh , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
New()
tmp< snGradScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return new tmp interpolation scheme.
Definition at line 46 of file snGradScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, and Foam::nl.
Referenced by laplacianScheme< Type, GType >::laplacianScheme(), Foam::fvc::snGrad(), and snGradScheme< Type >::snGradScheme().
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 123 of file snGradScheme.H.
References snGradScheme< Type >::deltaCoeffs(), snGradScheme< Type >::sndGrad(), and snGradScheme< Type >::snGrad().
Referenced by CentredFitSnGradScheme< Type, Polynomial, Stencil >::correction(), uncorrectedSnGrad< Type >::deltaCoeffs(), orthogonalSnGrad< Type >::deltaCoeffs(), faceCorrectedSnGrad< Type >::deltaCoeffs(), correctedSnGrad< Type >::deltaCoeffs(), CentredFitSnGradScheme< Type, Polynomial, Stencil >::deltaCoeffs(), and limitedSnGrad< Type >::deltaCoeffs().
snGrad() [1/3]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tdeltaCoeffs, const word & snGradName = "snGrad") static
Return the snGrad of the given cell field with the given deltaCoeffs.
Definition at line 101 of file snGradScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), fvPatchField< Type >::coupled(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), patchi, tmp< T >::ref(), snGradScheme< Type >::sndGrad(), and fvPatchField< Type >::snGrad().
Referenced by snGradScheme< Type >::correction(), snGradScheme< Type >::mesh(), snGradScheme< Type >::sndGrad(), snGradScheme< Type >::snGrad(), and snGradScheme< Type >::~snGradScheme().
sndGrad()
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & snGradName = "sndGrad") static
Return the sndGrad of the given cell field.
Definition at line 165 of file snGradScheme.C.
References DimensionedField< Type, GeoMesh >::mesh(), Foam::fvc::snGrad(), and snGradScheme< Type >::snGrad().
Referenced by snGradScheme< Type >::mesh(), and snGradScheme< Type >::snGrad().
deltaCoeffs()
virtual tmp<surfaceScalarField> deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Return the interpolation weighting factors for the given field.
Implemented in limitedSnGrad< Type >, CentredFitSnGradScheme< Type, Polynomial, Stencil >, correctedSnGrad< Type >, faceCorrectedSnGrad< Type >, orthogonalSnGrad< Type >, and uncorrectedSnGrad< Type >.
Referenced by snGradScheme< Type >::mesh().
corrected()
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented in limitedSnGrad< Type >, CentredFitSnGradScheme< Type, Polynomial, Stencil >, correctedSnGrad< Type >, faceCorrectedSnGrad< Type >, orthogonalSnGrad< Type >, and uncorrectedSnGrad< Type >.
Definition at line 153 of file snGradScheme.H.
correction()
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the explicit correction to the snGrad.
for the given field
Reimplemented in limitedSnGrad< Type >, correctedSnGrad< Type >, faceCorrectedSnGrad< Type >, CentredFitSnGradScheme< Type, Polynomial, Stencil >, orthogonalSnGrad< Type >, and uncorrectedSnGrad< Type >.
Definition at line 161 of file snGradScheme.H.
References snGradScheme< Type >::snGrad().
snGrad() [2/3]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the snGrad of the given cell field.
with explicit correction
Definition at line 177 of file snGradScheme.C.
References Foam::correction(), tmp< T >::ref(), Foam::fvc::snGrad(), and snGradScheme< Type >::snGrad().
snGrad() [3/3]
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf) const
Return the snGrad of the given tmp cell field.
with explicit correction
Definition at line 198 of file snGradScheme.C.
References tmp< T >::clear(), and Foam::fvc::snGrad().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/snGradScheme/snGradScheme.H
src/finiteVolume/finiteVolume/snGradSchemes/snGradScheme/snGradScheme.C