OpenFOAM: fvBoundaryMesh Class Reference
fvBoundaryMesh Class Reference
Foam::fvBoundaryMesh.
Public Member Functions
fvBoundaryMesh (const fvMesh &)
Construct with zero size.
fvBoundaryMesh (const fvMesh &, const polyBoundaryMesh &)
Construct from polyBoundaryMesh.
const fvMesh & mesh () const
Return the mesh reference.
lduInterfacePtrsList interfaces () const
Return a list of pointers for each patch.
label findPatchID (const word &patchName) const
Find patch index given a name.
labelList findIndices (const keyType &, const bool useGroups) const
Find patch indices given a name.
void movePoints ()
Correct patches after moving points.
const fvPatch & operator[] (const word &) const
Return const reference to fvPatch by name.
fvPatch & operator[] (const word &)
Return reference to fvPatch by name.
Public Member Functions inherited from PtrList< T >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< T > &)
Copy constructor.
template<class CloneArg >
PtrList (const PtrList< T > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< T >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &)
Construct as copy of SLPtrList<T>
template<class INew >
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (T *)
Append an element at the end of the list.
void append (const autoPtr< T > &)
void append (const tmp< T > &)
void transfer (PtrList< T > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< T > set (const label, T *)
Set element to given T* and return old element (can be nullptr)
autoPtr< T > set (const label, const autoPtr< T > &)
Set element to given autoPtr<T> and return old element.
autoPtr< T > set (const label, const tmp< T > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< T > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Member Functions
void readUpdate (const polyBoundaryMesh &)
Update boundary based on new polyBoundaryMesh.
Protected Member Functions inherited from PtrList< T >
template<class INew >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Friends
class fvMesh
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Detailed Description
Foam::fvBoundaryMesh.
Source files
fvBoundaryMesh.H
fvBoundaryMesh.C
Definition at line 52 of file fvBoundaryMesh.H.
Constructor & Destructor Documentation
fvBoundaryMesh() [1/2]
fvBoundaryMesh (const fvMesh & m)
Construct with zero size.
Definition at line 49 of file fvBoundaryMesh.C.
fvBoundaryMesh() [2/2]
fvBoundaryMesh (const fvMesh & m, const polyBoundaryMesh & basicBdry)
Construct from polyBoundaryMesh.
Definition at line 59 of file fvBoundaryMesh.C.
Member Function Documentation
readUpdate()
void readUpdate (const polyBoundaryMesh & basicBdry) protected
Update boundary based on new polyBoundaryMesh.
Definition at line 134 of file fvBoundaryMesh.C.
References PtrList< T >::clear(), and UPtrList< T >::operator.
Referenced by fvMesh::readUpdate().
mesh()
const fvMesh& mesh () const inline
Return the mesh reference.
Definition at line 99 of file fvBoundaryMesh.H.
References fvBoundaryMesh::findIndices(), fvBoundaryMesh::findPatchID(), fvBoundaryMesh::interfaces(), fvBoundaryMesh::movePoints(), UPtrList< T >::operator, and fvBoundaryMesh::operator[]().
Referenced by fvPatch::Cf(), fvPatch::Cn(), fvPatch::deltaCoeffs(), fvBoundaryMesh::findIndices(), fvPatch::magSf(), regionCoupledBaseFvPatch::nbrFvMesh(), regionCoupledBaseFvPatch::nbrMesh(), fvPatch::Sf(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), and fvPatch::weights().
interfaces()
Foam::lduInterfacePtrsList interfaces () const
Return a list of pointers for each patch.
with only those pointing to interfaces being set
Definition at line 114 of file fvBoundaryMesh.C.
References forAll, patchi, UPtrList< T >::set(), and UPtrList< T >::size().
Referenced by fvBoundaryMesh::mesh(), and fvMesh::thisDb().
findPatchID()
Foam::label findPatchID (const word & patchName) const
Find patch index given a name.
Definition at line 73 of file fvBoundaryMesh.C.
References fvBoundaryMesh::findIndices(), forAll, Foam::name(), patches, and patchi.
Referenced by fvBoundaryMesh::mesh(), and fvBoundaryMesh::operator[]().
findIndices()
Foam::labelList findIndices (const keyType & key, const bool useGroups) const
Find patch indices given a name.
Definition at line 91 of file fvBoundaryMesh.C.
References polyMesh::boundaryMesh(), polyBoundaryMesh::findIndices(), and fvBoundaryMesh::mesh().
Referenced by fvBoundaryMesh::findPatchID(), and fvBoundaryMesh::mesh().
movePoints()
void movePoints ()
Correct patches after moving points.
Definition at line 100 of file fvBoundaryMesh.C.
References forAll, fvPatch::initMovePoints(), fvPatch::movePoints(), fvBoundaryMesh::operator[](), and patchi.
Referenced by fvBoundaryMesh::mesh(), and fvMesh::movePoints().
operator[]() [1/2]
const Foam::fvPatch & operator[] (const word & patchName) const
Return const reference to fvPatch by name.
Definition at line 144 of file fvBoundaryMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, fvBoundaryMesh::findPatchID(), Foam::nl, UPtrList< T >::operator, and patchi.
Referenced by fvBoundaryMesh::mesh(), fvBoundaryMesh::movePoints(), and fvBoundaryMesh::operator[]().
operator[]() [2/2]
Foam::fvPatch & operator[] (const word & patchName)
Return reference to fvPatch by name.
Definition at line 162 of file fvBoundaryMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, fvBoundaryMesh::findPatchID(), Foam::nl, fvBoundaryMesh::operator[](), and patchi.
Friends And Related Function Documentation
fvMesh
friend class fvMesh friend
Definition at line 82 of file fvBoundaryMesh.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvBoundaryMesh/fvBoundaryMesh.H
src/finiteVolume/fvMesh/fvBoundaryMesh/fvBoundaryMesh.C