OpenFOAM: fvSurfaceMapper Class Reference
fvSurfaceMapper Class Reference
FV surface mapper.
Public Member Functions
fvSurfaceMapper (const fvMesh &mesh, const faceMapper &fMapper)
Construct from components.
virtual ~fvSurfaceMapper ()
Destructor.
virtual label size () const
Return size.
virtual label sizeBeforeMapping () const
Return size of field before mapping.
virtual bool direct () const
Is the mapping direct.
virtual bool hasUnmapped () const
Has unmapped elements.
virtual const labelUList & directAddressing () const
Return direct addressing.
virtual const labelListList & addressing () const
Return interpolated addressing.
virtual const scalarListList & weights () const
Return interpolaion weights.
virtual bool insertedObjects () const
Are there any inserted faces.
virtual const labelList & insertedObjectLabels () const
Return list of inserted faces.
const labelHashSet & flipFaceFlux () const
Return flux flip map.
Public Member Functions inherited from morphFieldMapper
morphFieldMapper ()
Null constructor.
virtual ~morphFieldMapper ()
Destructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
FV surface mapper.
Source files
fvSurfaceMapper.H
fvSurfaceMapper.C
Definition at line 54 of file fvSurfaceMapper.H.
Constructor & Destructor Documentation
fvSurfaceMapper()
fvSurfaceMapper (const fvMesh & mesh, const faceMapper & fMapper)
Construct from components.
Definition at line 148 of file fvSurfaceMapper.C.
~fvSurfaceMapper()
~fvSurfaceMapper () virtual
Destructor.
Definition at line 164 of file fvSurfaceMapper.C.
Member Function Documentation
size()
virtual label size () const inline virtual
Return size.
Implements FieldMapper.
Definition at line 118 of file fvSurfaceMapper.H.
References primitiveMesh::nInternalFaces().
sizeBeforeMapping()
virtual label sizeBeforeMapping () const inline virtual
Return size of field before mapping.
Implements morphFieldMapper.
Definition at line 124 of file fvSurfaceMapper.H.
References faceMapper::internalSizeBeforeMapping().
direct()
virtual bool direct () const inline virtual
Is the mapping direct.
Implements FieldMapper.
Definition at line 130 of file fvSurfaceMapper.H.
References faceMapper::direct().
Referenced by fvSurfaceMapper::addressing(), fvSurfaceMapper::directAddressing(), and fvSurfaceMapper::weights().
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Has unmapped elements.
Implements FieldMapper.
Definition at line 136 of file fvSurfaceMapper.H.
References fvSurfaceMapper::addressing(), fvSurfaceMapper::directAddressing(), fvSurfaceMapper::insertedObjects(), and fvSurfaceMapper::weights().
directAddressing()
const Foam::labelUList & directAddressing () const virtual
Return direct addressing.
Reimplemented from FieldMapper.
Definition at line 172 of file fvSurfaceMapper.C.
References Foam::abort(), fvSurfaceMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by fvSurfaceMapper::hasUnmapped().
addressing()
const Foam::labelListList & addressing () const virtual
Return interpolated addressing.
Reimplemented from FieldMapper.
Definition at line 190 of file fvSurfaceMapper.C.
References Foam::abort(), fvSurfaceMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by fvSurfaceMapper::hasUnmapped().
weights()
const Foam::scalarListList & weights () const virtual
Return interpolaion weights.
Reimplemented from FieldMapper.
Definition at line 208 of file fvSurfaceMapper.C.
References Foam::abort(), fvSurfaceMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by fvSurfaceMapper::hasUnmapped().
insertedObjects()
virtual bool insertedObjects () const inline virtual
Are there any inserted faces.
Implements morphFieldMapper.
Definition at line 151 of file fvSurfaceMapper.H.
References fvSurfaceMapper::insertedObjectLabels(), and faceMapper::insertedObjects().
Referenced by fvSurfaceMapper::hasUnmapped().
insertedObjectLabels()
const Foam::labelList & insertedObjectLabels () const virtual
Return list of inserted faces.
Implements morphFieldMapper.
Definition at line 226 of file fvSurfaceMapper.C.
Referenced by fvSurfaceMapper::insertedObjects().
flipFaceFlux()
const labelHashSet& flipFaceFlux () const inline
Return flux flip map.
Definition at line 160 of file fvSurfaceMapper.H.
References faceMapper::flipFaceFlux().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvMeshMapper/fvSurfaceMapper.H
src/finiteVolume/fvMesh/fvMeshMapper/fvSurfaceMapper.C