OpenFOAM: cyclicFvPatch Class Reference
cyclicFvPatch Class Reference
Cyclic-plane patch.
Public Member Functions
TypeName (cyclicPolyPatch::typeName_())
Runtime type information.
cyclicFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from polyPatch.
const cyclicPolyPatch & cyclicPatch () const
Return local reference cast into the cyclic patch.
virtual label neighbPatchID () const
Return neighbour.
virtual bool owner () const
virtual const cyclicFvPatch & neighbPatch () const
Return processor number.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
const cyclicFvPatch & neighbFvPatch () const
virtual tmp< vectorField > delta () const
Return delta (P to N) vectors across coupled patch.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
Return neighbour field.
Public Member Functions inherited from coupledFvPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from polyPatch.
virtual ~coupledFvPatch ()
Destructor.
virtual bool coupled () const
Return true because this patch is coupled.
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
Initialise neighbour field transfer.
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
Public Member Functions inherited from fvPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
Construct from polyPatch and fvBoundaryMesh.
virtual ~fvPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
const word & name () const
Return name.
label start () const
Return start label of this patch in the polyMesh face list.
virtual label size () const
Return size.
label index () const
Return the index of this patch in the fvBoundaryMesh.
const fvBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
const vectorField & Cf () const
Return face centres.
tmp< vectorField > Cn () const
Return neighbour cell centres.
const vectorField & Sf () const
Return face area vectors.
const scalarField & magSf () const
Return face area magnitudes.
tmp< vectorField > nf () const
Return face normals.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return the face - cell distance coeffient.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class Type >
void patchInternalField (const UList< Type > &, Field< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::Patch & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const Type *=nullptr) const
Lookup and return the patchField of the named field from the.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Public Member Functions inherited from cyclicLduInterface
TypeName ("cyclicLduInterface")
Runtime type information.
virtual ~cyclicLduInterface ()
Destructor.
Protected Member Functions
void makeWeights (scalarField &) const
Make patch weighting factors.
Protected Member Functions inherited from fvPatch
virtual void initMovePoints ()
Initialise the patches for moving points.
virtual void movePoints ()
Correct patches after moving points.
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Detailed Description
Cyclic-plane patch.
Source files
cyclicFvPatch.H
cyclicFvPatch.C
Definition at line 51 of file cyclicFvPatch.H.
Constructor & Destructor Documentation
cyclicFvPatch()
cyclicFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Construct from polyPatch.
Definition at line 78 of file cyclicFvPatch.H.
Member Function Documentation
makeWeights()
void makeWeights (scalarField & w) const protected virtual
Make patch weighting factors.
Implements coupledFvPatch.
Definition at line 42 of file cyclicFvPatch.C.
References coupledFvPatch::delta(), forAll, and fvPatch::nf().
TypeName()
TypeName (cyclicPolyPatch::typeName_())
Runtime type information.
cyclicPatch()
const cyclicPolyPatch& cyclicPatch () const inline
Return local reference cast into the cyclic patch.
Definition at line 90 of file cyclicFvPatch.H.
neighbPatchID()
virtual label neighbPatchID () const inline virtual
Return neighbour.
Implements cyclicLduInterface.
Definition at line 96 of file cyclicFvPatch.H.
References cyclicPolyPatch::neighbPatchID().
owner()
virtual bool owner () const inline virtual
Implements cyclicLduInterface.
Definition at line 101 of file cyclicFvPatch.H.
References cyclicPolyPatch::owner().
neighbPatch()
virtual const cyclicFvPatch& neighbPatch () const inline virtual
Return processor number.
Implements cyclicLduInterface.
Definition at line 107 of file cyclicFvPatch.H.
References fvPatch::boundaryMesh(), and cyclicPolyPatch::neighbPatchID().
parallel()
virtual bool parallel () const inline virtual
Are the cyclic planes parallel.
Implements coupledFvPatch.
Definition at line 116 of file cyclicFvPatch.H.
References coupledPolyPatch::parallel().
Referenced by cyclicFvPatchField< Type >::doTransform().
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements coupledFvPatch.
Definition at line 122 of file cyclicFvPatch.H.
References coupledPolyPatch::forwardT().
Referenced by cyclicFvPatchField< Type >::forwardT().
reverseT()
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Implements coupledFvPatch.
Definition at line 128 of file cyclicFvPatch.H.
References coupledPolyPatch::reverseT().
Referenced by cyclicFvPatchField< Type >::reverseT().
neighbFvPatch()
const cyclicFvPatch& neighbFvPatch () const inline
Definition at line 133 of file cyclicFvPatch.H.
References fvPatch::boundaryMesh(), cyclicFvPatch::delta(), cyclicFvPatch::interfaceInternalField(), cyclicFvPatch::internalFieldTransfer(), and cyclicPolyPatch::neighbPatchID().
delta()
Foam::tmp< Foam::vectorField > delta () const virtual
Return delta (P to N) vectors across coupled patch.
Implements coupledFvPatch.
Definition at line 59 of file cyclicFvPatch.C.
References coupledFvPatch::delta(), forAll, cyclicFvPatch::interfaceInternalField(), tmp< T >::ref(), List< T >::size(), and Foam::transform().
Referenced by cyclicFvPatch::neighbFvPatch().
interfaceInternalField()
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements coupledFvPatch.
Definition at line 94 of file cyclicFvPatch.C.
References cyclicFvPatch::internalFieldTransfer().
Referenced by cyclicFvPatch::delta(), and cyclicFvPatch::neighbFvPatch().
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Return neighbour field.
Implements coupledFvPatch.
Definition at line 103 of file cyclicFvPatch.C.
Referenced by cyclicFvPatch::interfaceInternalField(), and cyclicFvPatch::neighbFvPatch().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/constraint/cyclic/cyclicFvPatch.H
src/finiteVolume/fvMesh/fvPatches/constraint/cyclic/cyclicFvPatch.C