OpenFOAM: coupledFvPatch Class Reference
coupledFvPatch Class Reference abstract
An abstract base class for patches that couple regions of the computational domain e.g. cyclic and processor-processor links.
Public Member Functions
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from polyPatch.
virtual ~coupledFvPatch ()
Destructor.
virtual bool coupled () const
Return true because this patch is coupled.
virtual bool parallel () const =0
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const =0
Return face transformation tensor.
virtual const tensorField & reverseT () const =0
Return neighbour-cell transformation tensor.
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual tmp< vectorField > delta () const =0
Return delta (P to N) vectors across coupled patch.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const =0
Return the values of the given internal data adjacent to.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
Initialise neighbour field transfer.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const =0
Return neighbour field.
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
Public Member Functions inherited from fvPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
Construct from polyPatch and fvBoundaryMesh.
virtual ~fvPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
const word & name () const
Return name.
label start () const
Return start label of this patch in the polyMesh face list.
virtual label size () const
Return size.
label index () const
Return the index of this patch in the fvBoundaryMesh.
const fvBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
const vectorField & Cf () const
Return face centres.
tmp< vectorField > Cn () const
Return neighbour cell centres.
const vectorField & Sf () const
Return face area vectors.
const scalarField & magSf () const
Return face area magnitudes.
tmp< vectorField > nf () const
Return face normals.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return the face - cell distance coeffient.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class Type >
void patchInternalField (const UList< Type > &, Field< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::Patch & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const Type *=nullptr) const
Lookup and return the patchField of the named field from the.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Protected Member Functions
virtual void makeWeights (scalarField &) const =0
Make patch weighting factors.
Protected Member Functions inherited from fvPatch
virtual void initMovePoints ()
Initialise the patches for moving points.
virtual void movePoints ()
Correct patches after moving points.
Friends
class surfaceInterpolation
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Detailed Description
An abstract base class for patches that couple regions of the computational domain e.g. cyclic and processor-processor links.
Source files
coupledFvPatch.H
coupledFvPatch.C
Definition at line 51 of file coupledFvPatch.H.
Constructor & Destructor Documentation
coupledFvPatch()
coupledFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Construct from polyPatch.
Definition at line 81 of file coupledFvPatch.H.
References coupledFvPatch::~coupledFvPatch().
~coupledFvPatch()
~coupledFvPatch () virtual
Destructor.
Definition at line 38 of file coupledFvPatch.C.
Referenced by coupledFvPatch::coupledFvPatch().
Member Function Documentation
makeWeights()
virtual void makeWeights (scalarField &) const protected pure virtual
Make patch weighting factors.
Reimplemented from fvPatch.
Implemented in cyclicACMIFvPatch, cyclicFvPatch, cyclicAMIFvPatch, and processorFvPatch.
TypeName()
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupled()
virtual bool coupled () const inline virtual
Return true because this patch is coupled.
Reimplemented from fvPatch.
Reimplemented in cyclicACMIFvPatch, cyclicAMIFvPatch, and processorFvPatch.
Definition at line 97 of file coupledFvPatch.H.
References coupledPolyPatch::coupled(), coupledFvPatch::forwardT(), coupledFvPatch::parallel(), and coupledFvPatch::reverseT().
parallel()
virtual bool parallel () const pure virtual
Are the cyclic planes parallel.
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, cyclicFvPatch, and processorCyclicFvPatch.
Referenced by coupledFvPatch::coupled().
forwardT()
virtual const tensorField& forwardT () const pure virtual
Return face transformation tensor.
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, cyclicFvPatch, and processorCyclicFvPatch.
Referenced by coupledFvPatch::coupled().
reverseT()
virtual const tensorField& reverseT () const pure virtual
Return neighbour-cell transformation tensor.
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, cyclicFvPatch, and processorCyclicFvPatch.
Referenced by coupledFvPatch::coupled().
faceCells()
virtual const labelUList& faceCells () const inline virtual
Return faceCell addressing.
Reimplemented from fvPatch.
Definition at line 112 of file coupledFvPatch.H.
References coupledFvPatch::delta(), fvPatch::faceCells(), lduInterface::initInternalFieldTransfer(), coupledFvPatch::initInternalFieldTransfer(), and coupledFvPatch::interfaceInternalField().
delta()
Foam::tmp< Foam::vectorField > delta () const pure virtual
Return delta (P to N) vectors across coupled patch.
Reimplemented from fvPatch.
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, and cyclicFvPatch.
Definition at line 44 of file coupledFvPatch.C.
Referenced by cyclicFvPatch::delta(), processorFvPatch::delta(), cyclicAMIFvPatch::delta(), cyclicACMIFvPatch::delta(), coupledFvPatch::faceCells(), processorFvPatch::makeWeights(), cyclicFvPatch::makeWeights(), cyclicAMIFvPatch::makeWeights(), and cyclicACMIFvPatch::makeWeights().
interfaceInternalField()
virtual tmp<labelField> interfaceInternalField (const labelUList & internalData) const pure virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements lduInterface.
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, and cyclicFvPatch.
Referenced by coupledFvPatch::faceCells().
initInternalFieldTransfer()
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList & iF) const inline virtual
Initialise neighbour field transfer.
Definition at line 135 of file coupledFvPatch.H.
References coupledFvPatch::internalFieldTransfer().
Referenced by coupledFvPatch::faceCells(), and processorFvPatch::reverseT().
internalFieldTransfer()
virtual tmp<labelField> internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const pure virtual
Return neighbour field.
Implements lduInterface.
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, and cyclicFvPatch.
Referenced by coupledFvPatch::initInternalFieldTransfer().
Friends And Related Function Documentation
surfaceInterpolation
friend class surfaceInterpolation friend
Definition at line 71 of file coupledFvPatch.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/basic/coupled/coupledFvPatch.H
src/finiteVolume/fvMesh/fvPatches/basic/coupled/coupledFvPatch.C