OpenFOAM: processorFvPatch Class Reference
processorFvPatch Class Reference
Processor patch.
Public Member Functions
TypeName (processorPolyPatch::typeName_())
Runtime type information.
processorFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from components.
virtual label comm () const
Return communicator used for comms.
virtual int myProcNo () const
Return processor number.
virtual int neighbProcNo () const
Return neigbour processor number.
virtual int tag () const
Return message tag used for sending.
virtual bool coupled () const
Return true if running parallel.
const processorPolyPatch & procPolyPatch () const
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual tmp< vectorField > delta () const
Return delta (P to N) vectors across coupled patch.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
Initialise neighbour field transfer.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
Return neighbour field.
Public Member Functions inherited from coupledFvPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from polyPatch.
virtual ~coupledFvPatch ()
Destructor.
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
Initialise neighbour field transfer.
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
Public Member Functions inherited from fvPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
Construct from polyPatch and fvBoundaryMesh.
virtual ~fvPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
const word & name () const
Return name.
label start () const
Return start label of this patch in the polyMesh face list.
virtual label size () const
Return size.
label index () const
Return the index of this patch in the fvBoundaryMesh.
const fvBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
const vectorField & Cf () const
Return face centres.
tmp< vectorField > Cn () const
Return neighbour cell centres.
const vectorField & Sf () const
Return face area vectors.
const scalarField & magSf () const
Return face area magnitudes.
tmp< vectorField > nf () const
Return face normals.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return the face - cell distance coeffient.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class Type >
void patchInternalField (const UList< Type > &, Field< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::Patch & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const Type *=nullptr) const
Lookup and return the patchField of the named field from the.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Public Member Functions inherited from processorLduInterface
TypeName ("processorLduInterface")
Runtime type information.
processorLduInterface ()
Construct null.
virtual ~processorLduInterface ()
Destructor.
template<class Type >
void send (const Pstream::commsTypes commsType, const UList< Type > &) const
Raw send function.
template<class Type >
void receive (const Pstream::commsTypes commsType, UList< Type > &) const
Raw field receive function.
template<class Type >
tmp< Field< Type > > receive (const Pstream::commsTypes commsType, const label size) const
Raw field receive function returning field.
template<class Type >
void compressedSend (const Pstream::commsTypes commsType, const UList< Type > &) const
Raw field send function with data compression.
template<class Type >
void compressedReceive (const Pstream::commsTypes commsType, UList< Type > &) const
Raw field receive function with data compression.
template<class Type >
tmp< Field< Type > > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Raw field receive function with data compression returning field.
template<class Type >
Foam::tmp< Foam::Field< Type > > receive (const Pstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Protected Member Functions
void makeWeights (scalarField &) const
Make patch weighting factors.
Protected Member Functions inherited from fvPatch
virtual void initMovePoints ()
Initialise the patches for moving points.
virtual void movePoints ()
Correct patches after moving points.
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Detailed Description
Processor patch.
Source files
processorFvPatch.H
processorFvPatch.C
Definition at line 50 of file processorFvPatch.H.
Constructor & Destructor Documentation
processorFvPatch()
processorFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Construct from components.
Definition at line 77 of file processorFvPatch.H.
Member Function Documentation
makeWeights()
void makeWeights (scalarField & w) const protected virtual
Make patch weighting factors.
Implements coupledFvPatch.
Definition at line 41 of file processorFvPatch.C.
References coupledFvPatch::delta(), Foam::mag(), and UPstream::parRun().
TypeName()
TypeName (processorPolyPatch::typeName_())
Runtime type information.
comm()
virtual label comm () const inline virtual
Return communicator used for comms.
Implements processorLduInterface.
Definition at line 87 of file processorFvPatch.H.
References processorPolyPatch::comm().
Referenced by processorFvPatchField< Type >::comm().
myProcNo()
virtual int myProcNo () const inline virtual
Return processor number.
Implements processorLduInterface.
Definition at line 93 of file processorFvPatch.H.
References processorPolyPatch::myProcNo().
Referenced by processorFvPatchField< Type >::myProcNo().
neighbProcNo()
virtual int neighbProcNo () const inline virtual
Return neigbour processor number.
Implements processorLduInterface.
Definition at line 99 of file processorFvPatch.H.
References processorPolyPatch::neighbProcNo().
Referenced by processorFvPatchField< Type >::neighbProcNo().
tag()
virtual int tag () const inline virtual
Return message tag used for sending.
Implements processorLduInterface.
Reimplemented in processorCyclicFvPatch.
Definition at line 105 of file processorFvPatch.H.
References UPstream::msgType().
coupled()
virtual bool coupled () const inline virtual
Return true if running parallel.
Reimplemented from coupledFvPatch.
Definition at line 111 of file processorFvPatch.H.
References UPstream::parRun().
procPolyPatch()
const processorPolyPatch& procPolyPatch () const inline
Definition at line 123 of file processorFvPatch.H.
parallel()
virtual bool parallel () const inline virtual
Are the cyclic planes parallel.
Implements coupledFvPatch.
Reimplemented in processorCyclicFvPatch.
Definition at line 129 of file processorFvPatch.H.
References coupledPolyPatch::parallel().
Referenced by processorFvPatchField< Type >::doTransform().
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements coupledFvPatch.
Reimplemented in processorCyclicFvPatch.
Definition at line 135 of file processorFvPatch.H.
References coupledPolyPatch::forwardT().
Referenced by processorFvPatchField< Type >::forwardT().
reverseT()
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Implements coupledFvPatch.
Reimplemented in processorCyclicFvPatch.
Definition at line 141 of file processorFvPatch.H.
References processorFvPatch::delta(), coupledFvPatch::initInternalFieldTransfer(), processorFvPatch::initInternalFieldTransfer(), processorFvPatch::interfaceInternalField(), processorFvPatch::internalFieldTransfer(), and coupledPolyPatch::reverseT().
delta()
Foam::tmp< Foam::vectorField > delta () const virtual
Return delta (P to N) vectors across coupled patch.
Implements coupledFvPatch.
Definition at line 67 of file processorFvPatch.C.
References coupledFvPatch::delta(), processorFvPatch::interfaceInternalField(), UPstream::parRun(), and Foam::transform().
Referenced by processorFvPatch::reverseT().
interfaceInternalField()
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements coupledFvPatch.
Definition at line 103 of file processorFvPatch.C.
References processorFvPatch::initInternalFieldTransfer().
Referenced by processorFvPatch::delta(), and processorFvPatch::reverseT().
initInternalFieldTransfer()
void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Initialise neighbour field transfer.
Reimplemented from lduInterface.
Definition at line 112 of file processorFvPatch.C.
References processorFvPatch::internalFieldTransfer().
Referenced by processorFvPatch::interfaceInternalField(), and processorFvPatch::reverseT().
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Return neighbour field.
Implements coupledFvPatch.
Definition at line 122 of file processorFvPatch.C.
Referenced by processorFvPatch::initInternalFieldTransfer(), and processorFvPatch::reverseT().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/constraint/processor/processorFvPatch.H
src/finiteVolume/fvMesh/fvPatches/constraint/processor/processorFvPatch.C