OpenFOAM: interpolationCellPatchConstrained< Type > Class Template Reference
interpolationCellPatchConstrained< Type > Class Template Reference
Uses the cell value for any point in the cell apart from a boundary face where it uses the boundary value directly. Note: will not work on an empty patch.
Public Member Functions
TypeName ("cellPatchConstrained")
Runtime type information.
interpolationCellPatchConstrained (const GeometricField< Type, fvPatchField, volMesh > &psi)
Construct from components.
Type interpolate (const vector &position, const label celli, const label facei=-1) const
Interpolate field to the given point in the given cell.
Public Member Functions inherited from interpolation< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interpolation, dictionary,(const GeometricField< Type, fvPatchField, volMesh > &psi),(psi))
interpolation (const GeometricField< Type, fvPatchField, volMesh > &psi)
Construct from components.
virtual ~interpolation ()
Destructor.
const GeometricField< Type, fvPatchField, volMesh > & psi () const
Return the field to be interpolated.
virtual Type interpolate (const vector &position, const tetIndices &tetIs, const label facei=-1) const
Interpolate field to the given point in the tetrahedron.
Additional Inherited Members
Static Public Member Functions inherited from interpolation< Type >
static autoPtr< interpolation< Type > > New (const word &interpolationType, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the specified interpolation scheme.
static autoPtr< interpolation< Type > > New (const dictionary &interpolationSchemes, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the selected interpolation scheme.
Protected Attributes inherited from interpolation< Type >
const GeometricField< Type, fvPatchField, volMesh > & psi_
const polyMesh & pMesh_
const vectorField & pMeshPoints_
const faceList & pMeshFaces_
const vectorField & pMeshFaceCentres_
const vectorField & pMeshFaceAreas_
Detailed Description
template<class Type>
class Foam::interpolationCellPatchConstrained< Type >
Uses the cell value for any point in the cell apart from a boundary face where it uses the boundary value directly. Note: will not work on an empty patch.
Definition at line 50 of file interpolationCellPatchConstrained.H.
Constructor & Destructor Documentation
interpolationCellPatchConstrained()
interpolationCellPatchConstrained (const GeometricField< Type, fvPatchField, volMesh > & psi)
Construct from components.
Definition at line 33 of file interpolationCellPatchConstrained.C.
References interpolationCellPatchConstrained< Type >::interpolate().
Member Function Documentation
TypeName()
TypeName ("cellPatchConstrained")
Runtime type information.
interpolate()
Type interpolate (const vector & position, const label celli, const label facei = -1) const virtual
Interpolate field to the given point in the given cell.
Implements interpolation< Type >.
Definition at line 45 of file interpolationCellPatchConstrained.C.
References polyMesh::boundaryMesh(), polyBoundaryMesh::mesh(), patchi, and polyBoundaryMesh::patchID().
Referenced by interpolationCellPatchConstrained< Type >::interpolationCellPatchConstrained().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationCellPatchConstrained/interpolationCellPatchConstrained.H
src/finiteVolume/interpolation/interpolation/interpolationCellPatchConstrained/interpolationCellPatchConstrained.C