OpenFOAM: nearWallDist Class Reference
nearWallDist Class Reference
Distance calculation for cells with face on a wall. Searches pointNeighbours to find closest.
Public Member Functions
nearWallDist (const fvMesh &mesh)
Construct from components.
virtual ~nearWallDist ()
Destructor.
const volScalarField::Boundary & y () const
virtual void correct ()
Correct for mesh geom/topo changes.
Detailed Description
Distance calculation for cells with face on a wall. Searches pointNeighbours to find closest.
Source files
nearWallDist.H
nearWallDist.C
Definition at line 51 of file nearWallDist.H.
Constructor & Destructor Documentation
nearWallDist()
nearWallDist (const fvMesh & mesh)
Construct from components.
Definition at line 94 of file nearWallDist.C.
~nearWallDist()
~nearWallDist () virtual
Destructor.
Definition at line 110 of file nearWallDist.C.
Member Function Documentation
y()
const volScalarField::Boundary& y () const inline
Definition at line 87 of file nearWallDist.H.
References nearWallDist::correct().
correct()
void correct () virtual
Correct for mesh geom/topo changes.
Definition at line 116 of file nearWallDist.C.
References fvMesh::boundary(), forAll, fvPatchField< Type >::New(), patchi, setSize(), UPtrList< T >::size(), polyMesh::topoChanging(), and fvMesh::V().
Referenced by nearWallDist::y().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/nearWallDist/nearWallDist.H
src/finiteVolume/fvMesh/wallDist/nearWallDist/nearWallDist.C