OpenFOAM: patchDistMethod Class Reference
patchDistMethod Class Reference abstract
Specialisation of patchDist for wall distance calculation.
Public Member Functions
TypeName ("patchDistMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, patchDistMethod, dictionary,(const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs),(dict, mesh, patchIDs))
patchDistMethod (const fvMesh &mesh, const labelHashSet &patchIDs)
Construct from mesh and patch ID set.
virtual ~patchDistMethod ()
Destructor.
const labelHashSet & patchIDs () const
Return the patchIDs.
virtual bool movePoints ()
Update cached geometry when the mesh moves.
virtual void updateMesh (const mapPolyMesh &)
Update cached topology and geometry when the mesh changes.
virtual bool correct (volScalarField &y)=0
Correct the given distance-to-patch field.
virtual bool correct (volScalarField &y, volVectorField &n)=0
Correct the given distance-to-patch and normal-to-patch fields.
template<class Type >
Foam::wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Static Public Member Functions
static autoPtr< patchDistMethod > New (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
template<class Type >
static wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Return the patch types for y and n.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh.
const labelHashSet patchIDs_
Set of patch IDs.
Detailed Description
Specialisation of patchDist for wall distance calculation.
Source files
patchDistMethod.H
patchDistMethod.C
Definition at line 56 of file patchDistMethod.H.
Constructor & Destructor Documentation
patchDistMethod()
patchDistMethod (const fvMesh & mesh, const labelHashSet & patchIDs)
Construct from mesh and patch ID set.
Definition at line 40 of file patchDistMethod.C.
References patchDistMethod::New().
~patchDistMethod()
~patchDistMethod () virtual
Destructor.
Definition at line 82 of file patchDistMethod.C.
Member Function Documentation
TypeName()
TypeName ("patchDistMethod")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , patchDistMethod , dictionary , (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs) , (dict, mesh, patchIDs))
New()
Foam::autoPtr< Foam::patchDistMethod > New (const dictionary & dict, const fvMesh & mesh, const labelHashSet & patchIDs) static
Definition at line 53 of file patchDistMethod.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and mesh.
Referenced by patchDistMethod::patchDistMethod().
patchTypes() [1/2]
static wordList patchTypes (const fvMesh & mesh, const labelHashSet & patchIDs) static
Return the patch types for y and n.
These are fixedValue for the set provided otherwise zero-gradient
patchIDs()
const labelHashSet& patchIDs () const inline
Return the patchIDs.
Definition at line 140 of file patchDistMethod.H.
References patchDistMethod::patchIDs_.
movePoints()
virtual bool movePoints () inline virtual
Update cached geometry when the mesh moves.
Definition at line 146 of file patchDistMethod.H.
updateMesh()
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update cached topology and geometry when the mesh changes.
Definition at line 152 of file patchDistMethod.H.
References patchDistMethod::correct(), n, and y.
correct() [1/2]
virtual bool correct (volScalarField & y) pure virtual
Correct the given distance-to-patch field.
Implemented in advectionDiffusion, Poisson, and meshWave.
Referenced by patchDistMethod::updateMesh().
correct() [2/2]
virtual bool correct (volScalarField & y, volVectorField & n) pure virtual
Correct the given distance-to-patch and normal-to-patch fields.
Implemented in advectionDiffusion, Poisson, and meshWave.
patchTypes() [2/2]
Foam::wordList patchTypes (const fvMesh & mesh, const labelHashSet & patchIDs)
Definition at line 32 of file patchDistMethodTemplates.C.
References fvMesh::boundary(), forAllConstIter(), and UPtrList< T >::size().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Reference to the mesh.
Definition at line 64 of file patchDistMethod.H.
patchIDs_
const labelHashSet patchIDs_ protected
Set of patch IDs.
Definition at line 67 of file patchDistMethod.H.
Referenced by patchDistMethod::patchIDs().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/patchDistMethods/patchDistMethod/patchDistMethod.H
src/finiteVolume/fvMesh/wallDist/patchDistMethods/patchDistMethod/patchDistMethod.C
src/finiteVolume/fvMesh/wallDist/patchDistMethods/patchDistMethod/patchDistMethodTemplates.C