OpenFOAM: meshWave Class Reference
meshWave Class Reference
Fast topological mesh-wave method for calculating the distance to nearest patch for all cells and boundary.
Public Member Functions
TypeName ("meshWave")
Runtime type information.
meshWave (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
Construct from coefficients dictionary, mesh.
meshWave (const fvMesh &mesh, const labelHashSet &patchIDs, const bool correctWalls=true)
Construct from mesh, fixed-value patch set and flag specifying.
label nUnset () const
virtual bool correct (volScalarField &y)
Correct the given distance-to-patch field.
virtual bool correct (volScalarField &y, volVectorField &n)
Correct the given distance-to-patch and normal-to-patch fields.
Public Member Functions inherited from patchDistMethod
TypeName ("patchDistMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, patchDistMethod, dictionary,(const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs),(dict, mesh, patchIDs))
patchDistMethod (const fvMesh &mesh, const labelHashSet &patchIDs)
Construct from mesh and patch ID set.
virtual ~patchDistMethod ()
Destructor.
const labelHashSet & patchIDs () const
Return the patchIDs.
virtual bool movePoints ()
Update cached geometry when the mesh moves.
virtual void updateMesh (const mapPolyMesh &)
Update cached topology and geometry when the mesh changes.
template<class Type >
Foam::wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Additional Inherited Members
Static Public Member Functions inherited from patchDistMethod
static autoPtr< patchDistMethod > New (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
template<class Type >
static wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Return the patch types for y and n.
Protected Attributes inherited from patchDistMethod
const fvMesh & mesh_
Reference to the mesh.
const labelHashSet patchIDs_
Set of patch IDs.
Detailed Description
Fast topological mesh-wave method for calculating the distance to nearest patch for all cells and boundary.
For regular/un-distorted meshes this method is accurate but for skewed, non-orthogonal meshes it is approximate with the error increasing with the degree of mesh distortion. The distance from the near-wall cells to the boundary may optionally be corrected for mesh distortion by setting correctWalls = true.
Example of the wallDist specification in fvSchemes:
    wallDist
    {
        method meshWave;
        // Optional entry enabling the calculation
        // of the normal-to-wall field
        nRequired false;
    }
See also
Foam::patchDistMethod::Poisson Foam::wallDist
Source files
meshWavePatchDistMethod.H
meshWavePatchDistMethod.C
Definition at line 73 of file meshWavePatchDistMethod.H.
Constructor & Destructor Documentation
meshWave() [1/2]
meshWave (const dictionary & dict, const fvMesh & mesh, const labelHashSet & patchIDs)
Construct from coefficients dictionary, mesh.
and fixed-value patch set
Definition at line 49 of file meshWavePatchDistMethod.C.
meshWave() [2/2]
meshWave (const fvMesh & mesh, const labelHashSet & patchIDs, const bool correctWalls = true)
Construct from mesh, fixed-value patch set and flag specifying.
whether or not to correct wall. Calculate for all cells. correctWalls : correct wall (face&point) cells for correct distance, searching neighbours.
Definition at line 62 of file meshWavePatchDistMethod.C.
Member Function Documentation
TypeName()
TypeName ("meshWave")
Runtime type information.
nUnset()
label nUnset () const inline
Definition at line 126 of file meshWavePatchDistMethod.H.
References meshWave::correct(), n, and y.
correct() [1/2]
bool correct (volScalarField & y) virtual
Correct the given distance-to-patch field.
Implements patchDistMethod.
Definition at line 76 of file meshWavePatchDistMethod.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::dimLength, patchWave::distance(), forAll, patchWave::nUnset(), patchWave::patchDistance(), patchi, and List< T >::transfer().
Referenced by meshWave::nUnset().
correct() [2/2]
bool correct (volScalarField & y, volVectorField & n) virtual
Correct the given distance-to-patch and normal-to-patch fields.
Implements patchDistMethod.
Definition at line 107 of file meshWavePatchDistMethod.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), patchDataWave< TransferType >::cellData(), Foam::dimLength, patchDataWave< TransferType >::distance(), forAll, patchDataWave< TransferType >::nUnset(), patchDataWave< TransferType >::patchData(), patchDataWave< TransferType >::patchDistance(), patchi, UPtrList< T >::transfer(), and List< T >::transfer().
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/patchDistMethods/meshWave/meshWavePatchDistMethod.H
src/finiteVolume/fvMesh/wallDist/patchDistMethods/meshWave/meshWavePatchDistMethod.C