OpenFOAM: pointPatchField< Type > Class Template Reference
pointPatchField< Type > Class Template Reference abstract
Abstract base class for point-mesh patch fields.
Public Types
typedef pointPatch Patch
typedef calculatedPointPatchField< Type > Calculated
Public Member Functions
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType &>(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
virtual autoPtr< pointPatchField< Type > > clone () const =0
Construct and return a clone.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const =0
Construct and return a clone setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type, pointMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
virtual void write (Ostream &) const
Write.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Static Public Member Functions
static autoPtr< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new calculatedPointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Attributes
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Friends
Ostream & operator (Ostream &, const pointPatchField< Type > &)
Detailed Description
template<class Type>
class Foam::pointPatchField< Type >
Abstract base class for point-mesh patch fields.
The base-field does not store values as they are part of the "internal field". There are derived classes to store constraint values e.g. fixedValuePointPatchField derived from the generic valuePointPatchField which ensures the values in the "internal field" are reset to the fixed-values by applying the stored values.
Source files
pointPatchField.H
pointPatchField.C
newPointPatchField.C
Definition at line 58 of file pointMVCWeight.H.
Member Typedef Documentation
Patch
typedef pointPatch Patch
Definition at line 103 of file pointPatchField.H.
Calculated
typedef calculatedPointPatchField<Type> Calculated
Definition at line 104 of file pointPatchField.H.
Constructor & Destructor Documentation
pointPatchField() [1/5]
pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 34 of file pointPatchField.C.
Referenced by pointPatchField< vector >::pointPatchField().
pointPatchField() [2/5]
pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 48 of file pointPatchField.C.
pointPatchField() [3/5]
pointPatchField (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
Definition at line 63 of file pointPatchField.C.
pointPatchField() [4/5]
pointPatchField (const pointPatchField< Type > & ptf)
Construct as copy.
Definition at line 79 of file pointPatchField.C.
pointPatchField() [5/5]
pointPatchField (const pointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 92 of file pointPatchField.C.
~pointPatchField()
virtual ~pointPatchField () inline virtual
Destructor.
Definition at line 256 of file pointPatchField.H.
Member Function Documentation
TypeName()
TypeName ("pointPatchField< Type >")
Runtime type information.
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , pointPatch , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF) , (p, iF))
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , patchMapper , (const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m) , (dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (autoPtr , pointPatchField< Type > , dictionary , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict) , (p, iF, dict))
clone() [1/2]
virtual autoPtr<pointPatchField<Type> > clone () const pure virtual
Construct and return a clone.
Implemented in codedFixedValuePointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, zeroFixedValuePointPatchField< Type >, genericPointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, processorCyclicPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, valuePointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, valuePointPatchField< vector >, waveDisplacementPointPatchVectorField, processorPointPatchField< Type >, oscillatingDisplacementPointPatchVectorField, coupledPointPatchField< Type >, fixedValuePointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, wedgePointPatchField< Type >, fixedValuePointPatchField< vector >, calculatedPointPatchField< Type >, zeroGradientPointPatchField< Type >, slipPointPatchField< Type >, and basicSymmetryPointPatchField< Type >.
clone() [2/2]
virtual autoPtr<pointPatchField<Type> > clone (const DimensionedField< Type, pointMesh > & iF) const pure virtual
Construct and return a clone setting internal field reference.
Implemented in codedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, zeroFixedValuePointPatchField< Type >, genericPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, processorCyclicPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, valuePointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, valuePointPatchField< vector >, waveDisplacementPointPatchVectorField, processorPointPatchField< Type >, oscillatingDisplacementPointPatchVectorField, calculatedPointPatchField< Type >, fixedValuePointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, wedgePointPatchField< Type >, fixedValuePointPatchField< vector >, zeroGradientPointPatchField< Type >, slipPointPatchField< Type >, basicSymmetryPointPatchField< Type >, and coupledPointPatchField< Type >.
New() [1/4]
Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values)
Definition at line 97 of file pointPatchFieldNew.C.
Referenced by pointPatchField< vector >::New().
New() [2/4]
Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const word & actualPatchType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values). Allows override of constraint type
Definition at line 32 of file pointPatchFieldNew.C.
New() [3/4]
Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & pfMapper) static
Return a pointer to a new patchField created on freestore from.
a given pointPatchField mapped onto a new patch
Definition at line 186 of file pointPatchFieldNew.C.
New() [4/4]
Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict) static
Return a pointer to a new patchField created on freestore.
from dictionary
Definition at line 109 of file pointPatchFieldNew.C.
NewCalculatedType() [1/2]
static autoPtr<pointPatchField<Type> > NewCalculatedType (const pointPatchField< Type2 > &) static
Return a pointer to a new calculatedPointPatchField created on.
freestore without setting patchField values
Referenced by calculatedPointPatchField< Type >::calculatedPointPatchField().
db()
const Foam::objectRegistry & db () const
Return local objectRegistry.
Definition at line 107 of file pointPatchField.C.
Referenced by surfaceSlipDisplacementPointPatchVectorField::surfaces(), and pointPatchField< vector >::~pointPatchField().
size()
label size () const inline
Return size.
Definition at line 268 of file pointPatchField.H.
Referenced by valuePointPatchField< vector >::valuePointPatchField().
patch()
const pointPatch& patch () const inline
Return patch.
Definition at line 274 of file pointPatchField.H.
Referenced by NamedEnum< directionType, 3 >::names(), pointPatchField< vector >::NewCalculatedType(), and pointPatchField< vector >::size().
internalField()
const DimensionedField<Type, pointMesh>& internalField () const inline
Return dimensioned internal field reference.
Definition at line 281 of file pointPatchField.H.
primitiveField()
const Field<Type>& primitiveField () const inline
Return internal field reference.
Definition at line 287 of file pointPatchField.H.
Referenced by surfaceSlipDisplacementPointPatchVectorField::evaluate().
patchType() [1/2]
const word& patchType () const inline
Optional patch type.
Definition at line 293 of file pointPatchField.H.
patchType() [2/2]
word& patchType () inline
Optional patch type.
Definition at line 299 of file pointPatchField.H.
fixesValue()
virtual bool fixesValue () const inline virtual
Return true if this patch field fixes a value.
Reimplemented in fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 305 of file pointPatchField.H.
coupled()
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in processorCyclicPointPatchField< Type >, processorPointPatchField< Type >, and coupledPointPatchField< Type >.
Definition at line 311 of file pointPatchField.H.
updated()
bool updated () const inline
Return true if the boundary condition has already been updated.
Definition at line 317 of file pointPatchField.H.
patchInternalField() [1/5]
Foam::tmp< Foam::Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
Definition at line 145 of file pointPatchField.C.
Referenced by surfaceSlipDisplacementPointPatchVectorField::evaluate(), pointPatchField< vector >::patchInternalField(), pointConstraints::setPatchFields(), and pointPatchField< vector >::updated().
patchInternalField() [2/5]
tmp<Field<Type1> > patchInternalField (const Field< Type1 > & iF) const
Return field created from appropriate internal field values.
given internal field reference
patchInternalField() [3/5]
tmp<Field<Type1> > patchInternalField (const Field< Type1 > & iF, const labelList & meshPoints) const
Return field created from selected internal field values.
given internal field reference
addToInternalField() [1/2]
void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Given the internal field and a patch field,.
add the patch field to the internal field
Definition at line 189 of file pointPatchField.C.
Referenced by pointPatchField< vector >::addToInternalField(), pointPatchField< vector >::patchInternalField(), and pointPatchField< vector >::updated().
addToInternalField() [2/2]
void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelList & points) const
Given the internal field and a patch field,.
add selected elements of the patch field to the internal field
Definition at line 226 of file pointPatchField.C.
setInInternalField() [1/2]
void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelList & meshPoints) const
Given the internal field and a patch field,.
set the patch field in the internal field
Definition at line 265 of file pointPatchField.C.
Referenced by pointPatchField< vector >::addToInternalField(), surfaceSlipDisplacementPointPatchVectorField::evaluate(), pointPatchField< vector >::setInInternalField(), and pointPatchField< vector >::updated().
setInInternalField() [2/2]
void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Given the internal field and a patch field,.
set the patch field in the internal field
Definition at line 300 of file pointPatchField.C.
calculatedType()
const Foam::word & calculatedType () static
Return the type of the calculated form of pointPatchField.
Definition at line 31 of file calculatedPointPatchField.C.
Referenced by pointPatchField< vector >::updated().
constraintType()
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatchField implements.
Reimplemented in cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, processorPointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, emptyPointPatchField< Type >, wedgePointPatchField< Type >, and symmetryPointPatchField< Type >.
Definition at line 384 of file pointPatchField.H.
autoMap()
virtual void autoMap (const pointPatchFieldMapper &) inline virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, genericPointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, and oscillatingVelocityPointPatchVectorField.
Definition at line 394 of file pointPatchField.H.
Referenced by pointPatchField< vector >::constraintType().
rmap()
virtual void rmap (const pointPatchField< Type > & , const labelList &) inline virtual
Reverse map the given pointPatchField onto this pointPatchField.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, genericPointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, and oscillatingVelocityPointPatchVectorField.
Definition at line 401 of file pointPatchField.H.
Referenced by pointPatchField< vector >::autoMap().
updateCoeffs()
virtual void updateCoeffs () inline virtual
Update the coefficients associated with the patch field.
Sets Updated to true
Reimplemented in codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformInterpolatedDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, timeVaryingUniformFixedValuePointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 412 of file pointPatchField.H.
Referenced by pointPatchField< vector >::rmap().
initEvaluate()
virtual void initEvaluate (const Pstream::commsTypes commsType = Pstream::blocking) inline virtual
Initialise evaluation of the patch field (do nothing)
Definition at line 419 of file pointPatchField.H.
Referenced by pointPatchField< vector >::rmap().
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Evaluate the patch field.
Reimplemented in codedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, processorPointPatchField< Type >, processorCyclicPointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, cyclicPointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, symmetryPlanePointPatchField< Type >, wedgePointPatchField< Type >, cyclicSlipPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, basicSymmetryPointPatchField< Type >, and coupledPointPatchField< Type >.
Definition at line 310 of file pointPatchField.C.
Referenced by pointPatchField< vector >::initEvaluate().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in codedFixedValuePointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformInterpolatedDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, uniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, genericPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, fixedNormalSlipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 114 of file pointPatchField.C.
Referenced by pointPatchField< vector >::evaluate(), pointPatchField< vector >::initEvaluate(), oscillatingDisplacementPointPatchVectorField::write(), waveDisplacementPointPatchVectorField::write(), oscillatingVelocityPointPatchVectorField::write(), angularOscillatingVelocityPointPatchVectorField::write(), angularOscillatingDisplacementPointPatchVectorField::write(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write(), uniformInterpolatedDisplacementPointPatchVectorField::write(), and sixDoFRigidBodyDisplacementPointPatchVectorField::write().
writeEntryIfDifferent()
void writeEntryIfDifferent (Ostream & os, const word & entryName, const EntryType & value1, const EntryType & value2) const
Helper function to write the keyword and entry only if the.
values are not equal. The value is then output as value2
Definition at line 129 of file pointPatchField.C.
Referenced by pointPatchField< vector >::initEvaluate(), and pointPatchField< vector >::write().
operator=() [1/3]
virtual void operator= (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 450 of file pointPatchField.H.
operator+=() [1/3]
virtual void operator+= (const pointPatchField< Type > &) inline virtual
Definition at line 451 of file pointPatchField.H.
operator-=() [1/3]
virtual void operator-= (const pointPatchField< Type > &) inline virtual
Definition at line 452 of file pointPatchField.H.
operator*=() [1/3]
virtual void operator*= (const pointPatchField< scalar > &) inline virtual
Definition at line 453 of file pointPatchField.H.
operator/=() [1/3]
virtual void operator/= (const pointPatchField< scalar > &) inline virtual
Definition at line 454 of file pointPatchField.H.
operator=() [2/3]
virtual void operator= (const Field< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, valuePointPatchField< vector >, fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 456 of file pointPatchField.H.
operator+=() [2/3]
virtual void operator+= (const Field< Type > &) inline virtual
Definition at line 457 of file pointPatchField.H.
operator-=() [2/3]
virtual void operator-= (const Field< Type > &) inline virtual
Definition at line 458 of file pointPatchField.H.
operator*=() [2/3]
virtual void operator*= (const Field< scalar > &) inline virtual
Definition at line 460 of file pointPatchField.H.
operator/=() [2/3]
virtual void operator/= (const Field< scalar > &) inline virtual
Definition at line 461 of file pointPatchField.H.
operator=() [3/3]
virtual void operator= (const Type &) inline virtual
Reimplemented in valuePointPatchField< Type >, valuePointPatchField< vector >, fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 463 of file pointPatchField.H.
operator+=() [3/3]
virtual void operator+= (const Type &) inline virtual
Definition at line 464 of file pointPatchField.H.
operator-=() [3/3]
virtual void operator-= (const Type &) inline virtual
Definition at line 465 of file pointPatchField.H.
operator*=() [3/3]
virtual void operator*= (const scalar) inline virtual
Definition at line 466 of file pointPatchField.H.
operator/=() [3/3]
virtual void operator/= (const scalar) inline virtual
Definition at line 467 of file pointPatchField.H.
operator==() [1/3]
virtual void operator== (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 474 of file pointPatchField.H.
operator==() [2/3]
virtual void operator== (const Field< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 475 of file pointPatchField.H.
operator==() [3/3]
virtual void operator== (const Type &) inline virtual
Reimplemented in valuePointPatchField< Type >, and valuePointPatchField< vector >.
Definition at line 476 of file pointPatchField.H.
NewCalculatedType() [2/2]
Foam::autoPtr<Foam::pointPatchField<Type> > NewCalculatedType (const pointPatchField< Type2 > & pf)
Definition at line 90 of file calculatedPointPatchField.C.
patchInternalField() [4/5]
Foam::tmp<Foam::Field<Type1> > patchInternalField (const Field< Type1 > & iF, const labelList & meshPoints) const
Definition at line 155 of file pointPatchField.C.
patchInternalField() [5/5]
Foam::tmp<Foam::Field<Type1> > patchInternalField (const Field< Type1 > & iF) const
Definition at line 178 of file pointPatchField.C.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const pointPatchField< Type > &) friend
Member Data Documentation
disallowGenericPointPatchField
int disallowGenericPointPatchField static
Debug switch to disallow the use of genericPointPatchField.
Definition at line 111 of file pointPatchField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeight.H
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.H
src/OpenFOAM/fields/pointPatchFields/basic/calculated/calculatedPointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFieldNew.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFields.C