OpenFOAM: filteredLinearLimiter< LimiterFunc > Class Template Reference
filteredLinearLimiter< LimiterFunc > Class Template Reference
Class to generate weighting factors for the filteredLinear differencing scheme.
Public Member Functions
filteredLinearLimiter (Istream &)
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType &phiP, const typename LimiterFunc::phiType &phiN, const typename LimiterFunc::gradPhiType &gradcP, const typename LimiterFunc::gradPhiType &gradcN, const vector &d) const
Detailed Description
template<class LimiterFunc>
class Foam::filteredLinearLimiter< LimiterFunc >
Class to generate weighting factors for the filteredLinear differencing scheme.
The aim is to remove high-frequency modes with "staggering" characteristics by comparing the face gradient relative to the background distribution represented by the neighbouring cell gradients with those gradients and introduce small amounts of upwind in order to damp these modes.
Used in conjunction with the template class LimitedScheme.
Source files
filteredLinear.H
filteredLinear.C
Definition at line 58 of file filteredLinear.H.
Constructor & Destructor Documentation
filteredLinearLimiter()
filteredLinearLimiter (Istream &) inline
Definition at line 65 of file filteredLinear.H.
References filteredLinearLimiter< LimiterFunc >::limiter().
Member Function Documentation
limiter()
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType & phiP, const typename LimiterFunc::phiType & phiN, const typename LimiterFunc::gradPhiType & gradcP, const typename LimiterFunc::gradPhiType & gradcN, const vector & d) const inline
Definition at line 69 of file filteredLinear.H.
References Foam::mag(), Foam::max(), and Foam::min().
Referenced by filteredLinearLimiter< LimiterFunc >::filteredLinearLimiter().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/filteredLinear/filteredLinear.H