OpenFOAM: advectionDiffusion Class Reference
advectionDiffusion Class Reference
Calculation of approximate distance to nearest patch for all cells and boundary by solving the Eikonal equation in advection form with diffusion smoothing.
Public Member Functions
TypeName ("advectionDiffusion")
Runtime type information.
advectionDiffusion (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
Construct from coefficients dictionary, mesh.
virtual bool correct (volScalarField &y)
Correct the given distance-to-patch field.
virtual bool correct (volScalarField &y, volVectorField &n)
Correct the given distance-to-patch and normal-to-patch fields.
Public Member Functions inherited from patchDistMethod
TypeName ("patchDistMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, patchDistMethod, dictionary,(const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs),(dict, mesh, patchIDs))
patchDistMethod (const fvMesh &mesh, const labelHashSet &patchIDs)
Construct from mesh and patch ID set.
virtual ~patchDistMethod ()
Destructor.
const labelHashSet & patchIDs () const
Return the patchIDs.
virtual bool movePoints ()
Update cached geometry when the mesh moves.
virtual void updateMesh (const mapPolyMesh &)
Update cached topology and geometry when the mesh changes.
template<class Type >
Foam::wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Additional Inherited Members
Static Public Member Functions inherited from patchDistMethod
static autoPtr< patchDistMethod > New (const dictionary &dict, const fvMesh &mesh, const labelHashSet &patchIDs)
template<class Type >
static wordList patchTypes (const fvMesh &mesh, const labelHashSet &patchIDs)
Return the patch types for y and n.
Protected Attributes inherited from patchDistMethod
const fvMesh & mesh_
Reference to the mesh.
const labelHashSet patchIDs_
Set of patch IDs.
Detailed Description
Calculation of approximate distance to nearest patch for all cells and boundary by solving the Eikonal equation in advection form with diffusion smoothing.
If the diffusion coefficient is set to 0 this method is exact in principle but the numerical schemes used are not rendering the scheme approximate, but more accurate than the Poisson method. Also many models relying on the distance to the wall benefit from this field being smooth and monotonic so the addition of diffusion smoothing improves both the convergence and stability of the solution of the Eikonal equation and the behavior of the models using the distance field generated. However, it is not clear what the optimum value for the diffusion coefficient epsilon should be; a default value of 0.1 is provided but higher values may be preferable under some circumstances.
Convergence is accelerated by first generating an approximate solution using one of the simpler methods, e.g. Poisson. The method used for this prediction step is specified in the 'advectionDiffusionCoeffs' sub-dictionary, see below.
References:
    P.G. Tucker, C.L. Rumsey, R.E. Bartels, R.T. Biedron,
    "Transport equation based wall distance computations aimed at flows
     with time-dependent geometry",
    NASA/TM-2003-212680, December 2003.
Example of the wallDist specification in fvSchemes:
    laplacianSchemes
    {
        .
        .
        laplacian(yPsi) Gauss linear corrected;
        laplacian(yWall) Gauss linear corrected;
        .
        .
    }
    wallDist
    {
        method advectionDiffusion;
        // Optional entry enabling the calculation
        // of the normal-to-wall field
        nRequired false;
        advectionDiffusionCoeffs
        {
            method    Poisson;
            epsilon   0.1;
            tolerance 1e-3;
            maxIter   10;
        }
    }
Also the solver specification for yWall is required in fvSolution, e.g. for simple cases:
    yPsi
    {
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-4;
        relTol          0;
    }
    yWall
    {
        solver          PBiCG;
        preconditioner  DILU;
        tolerance       1e-4;
        relTol          0;
    }
    relaxationFactors
    {
        equations
        {
            .
            .
            yWall           1;
            .
            .
        }
    }
or for more complex cases:
    yPsi
    {
        solver          GAMG;
        smoother        GaussSeidel;
        cacheAgglomeration true;
        nCellsInCoarsestLevel 10;
        agglomerator    faceAreaPair;
        mergeLevels     1;
        tolerance       1e-4;
        relTol          0;
    }
    yWall
    {
        solver          GAMG;
        smoother        symGaussSeidel;
        cacheAgglomeration true;
        nCellsInCoarsestLevel 10;
        agglomerator    faceAreaPair;
        mergeLevels     1;
        tolerance       1e-4;
        relTol          0;
    }
    relaxationFactors
    {
        equations
        {
            .
            .
            yWall           0.7;
            .
            .
        }
    }
See also
Foam::patchDistMethod::Poisson Foam::patchDistMethod::meshWave Foam::wallDist
Source files
advectionDiffusionPatchDistMethod.H
advectionDiffusionPatchDistMethod.C
Definition at line 180 of file advectionDiffusionPatchDistMethod.H.
Constructor & Destructor Documentation
advectionDiffusion()
advectionDiffusion (const dictionary & dict, const fvMesh & mesh, const labelHashSet & patchIDs)
Construct from coefficients dictionary, mesh.
and fixed-value patch set
Definition at line 52 of file advectionDiffusionPatchDistMethod.C.
Member Function Documentation
TypeName()
TypeName ("advectionDiffusion")
Runtime type information.
correct() [1/2]
bool correct (volScalarField & y) virtual
Correct the given distance-to-patch field.
Implements patchDistMethod.
Definition at line 78 of file advectionDiffusionPatchDistMethod.C.
References correct, and GeometricField< vector, fvPatchField, volMesh >::null().
correct() [2/2]
bool correct (volScalarField & y, volVectorField & n) virtual
Correct the given distance-to-patch and normal-to-patch fields.
Implements patchDistMethod.
Definition at line 85 of file advectionDiffusionPatchDistMethod.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::dimless, Foam::fvm::div(), Foam::fvc::div(), forAllConstIter(), Foam::fvc::grad(), Foam::fvc::interpolate(), Foam::fvm::laplacian(), Foam::mag(), IOobject::NO_READ, IOobject::NO_WRITE, Foam::notNull(), patches, patchi, Foam::fvm::Sp(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/wallDist/patchDistMethods/advectionDiffusion/advectionDiffusionPatchDistMethod.H
src/finiteVolume/fvMesh/wallDist/patchDistMethods/advectionDiffusion/advectionDiffusionPatchDistMethod.C