OpenFOAM: MUSCLLimiter< LimiterFunc > Class Template Reference
MUSCLLimiter< LimiterFunc > Class Template Reference
Class with limiter function which returns the limiter for the van Leer's MUSCL differencing scheme.
Public Member Functions
MUSCLLimiter (Istream &)
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType &phiP, const typename LimiterFunc::phiType &phiN, const typename LimiterFunc::gradPhiType &gradcP, const typename LimiterFunc::gradPhiType &gradcN, const vector &d) const
Detailed Description
template<class LimiterFunc>
class Foam::MUSCLLimiter< LimiterFunc >
Class with limiter function which returns the limiter for the van Leer's MUSCL differencing scheme.
Used in conjunction with the template class LimitedScheme.
Source files
MUSCL.H
MUSCL.C
Definition at line 52 of file MUSCL.H.
Constructor & Destructor Documentation
MUSCLLimiter()
MUSCLLimiter (Istream &) inline
Definition at line 59 of file MUSCL.H.
References MUSCLLimiter< LimiterFunc >::limiter().
Member Function Documentation
limiter()
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType & phiP, const typename LimiterFunc::phiType & phiN, const typename LimiterFunc::gradPhiType & gradcP, const typename LimiterFunc::gradPhiType & gradcN, const vector & d) const inline
Definition at line 63 of file MUSCL.H.
References Foam::max(), and Foam::min().
Referenced by MUSCLLimiter< LimiterFunc >::MUSCLLimiter().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/MUSCL/MUSCL.H