OpenFOAM: limitedSurfaceInterpolationScheme< Type > Class Template Reference
limitedSurfaceInterpolationScheme< Type > Class Template Reference abstract
Abstract base class for limited surface interpolation schemes.
Public Member Functions
TypeName ("limitedSurfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
limitedSurfaceInterpolationScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from mesh and faceFlux.
limitedSurfaceInterpolationScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual ~limitedSurfaceInterpolationScheme ()
Destructor.
virtual tmp< surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > &) const =0
Return the interpolation weighting factors.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &, const surfaceScalarField &CDweights, tmp< surfaceScalarField > tLimiter) const
Return the interpolation weighting factors for the given field,.
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors for the given field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Attributes
const surfaceScalarField & faceFlux_
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::limitedSurfaceInterpolationScheme< Type >
Abstract base class for limited surface interpolation schemes.
Source files
limitedSurfaceInterpolationScheme.H
limitedSurfaceInterpolationScheme.C
Definition at line 49 of file limitedSurfaceInterpolationScheme.H.
Constructor & Destructor Documentation
limitedSurfaceInterpolationScheme() [1/2]
limitedSurfaceInterpolationScheme (const fvMesh & mesh, const surfaceScalarField & faceFlux) inline
Construct from mesh and faceFlux.
Definition at line 110 of file limitedSurfaceInterpolationScheme.H.
limitedSurfaceInterpolationScheme() [2/2]
limitedSurfaceInterpolationScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 124 of file limitedSurfaceInterpolationScheme.H.
References limitedSurfaceInterpolationScheme< Type >::flux(), limitedSurfaceInterpolationScheme< Type >::limiter(), limitedSurfaceInterpolationScheme< Type >::New(), limitedSurfaceInterpolationScheme< Type >::weights(), and limitedSurfaceInterpolationScheme< Type >::~limitedSurfaceInterpolationScheme().
~limitedSurfaceInterpolationScheme()
~limitedSurfaceInterpolationScheme () virtual
Destructor.
Definition at line 133 of file limitedSurfaceInterpolationScheme.C.
References limitedSurfaceInterpolationScheme< Type >::weights().
Referenced by limitedSurfaceInterpolationScheme< Type >::limitedSurfaceInterpolationScheme(), and limitedSurfaceInterpolationScheme< Type >::New().
Member Function Documentation
TypeName()
TypeName ("limitedSurfaceInterpolationScheme< Type >")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (tmp , limitedSurfaceInterpolationScheme< Type > , Mesh , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (tmp , limitedSurfaceInterpolationScheme< Type > , MeshFlux , (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
New() [1/2]
Foam::tmp< Foam::limitedSurfaceInterpolationScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return new tmp interpolation scheme.
Definition at line 36 of file limitedSurfaceInterpolationScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, and Foam::nl.
Referenced by limitedSurfaceInterpolationScheme< Type >::limitedSurfaceInterpolationScheme().
New() [2/2]
Foam::tmp< Foam::limitedSurfaceInterpolationScheme< Type > > New (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) static
Return new tmp interpolation scheme.
Definition at line 83 of file limitedSurfaceInterpolationScheme.C.
References Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, Foam::nl, and limitedSurfaceInterpolationScheme< Type >::~limitedSurfaceInterpolationScheme().
limiter()
virtual tmp<surfaceScalarField> limiter (const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Return the interpolation weighting factors.
Implemented in blended< Type >, LimitedScheme< Type, Limiter, LimitFunc >, PhiScheme< Type, PhiLimiter >, and upwind< Type >.
Referenced by limitedSurfaceInterpolationScheme< Type >::limitedSurfaceInterpolationScheme(), and multivariateSelectionScheme< Type >::multivariateSelectionScheme().
weights() [1/2]
Foam::tmp< Foam::surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > & phi, const surfaceScalarField & CDweights, tmp< surfaceScalarField > tLimiter) const
Return the interpolation weighting factors for the given field,.
by limiting the given weights with the given limiter
Definition at line 142 of file limitedSurfaceInterpolationScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, patchi, Foam::pos(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and tmp< T >::ref().
Referenced by limitedSurfaceInterpolationScheme< Type >::limitedSurfaceInterpolationScheme(), and limitedSurfaceInterpolationScheme< Type >::~limitedSurfaceInterpolationScheme().
weights() [2/2]
Foam::tmp< Foam::surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > & phi) const virtual
Return the interpolation weighting factors for the given field.
Implements surfaceInterpolationScheme< Type >.
Reimplemented in blended< Type >, upwind< Type >, and LUST< Type >.
Definition at line 185 of file limitedSurfaceInterpolationScheme.C.
References limitedSurfaceInterpolationScheme< Type >::flux(), Foam::MULES::limiter(), and mesh.
flux()
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > & phi) const virtual
Return the interpolation weighting factors.
Definition at line 200 of file limitedSurfaceInterpolationScheme.C.
References Foam::MULES::interpolate().
Referenced by limitedSurfaceInterpolationScheme< Type >::limitedSurfaceInterpolationScheme(), and limitedSurfaceInterpolationScheme< Type >::weights().
Member Data Documentation
faceFlux_
const surfaceScalarField& faceFlux_ protected
Definition at line 69 of file limitedSurfaceInterpolationScheme.H.
Referenced by PureUpwindFitScheme< Type, Polynomial, Stencil >::correction(), upwind< Type >::weights(), and blended< Type >::weights().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/limitedSurfaceInterpolationScheme/limitedSurfaceInterpolationScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/limitedSurfaceInterpolationScheme/limitedSurfaceInterpolationScheme.C