OpenFOAM: multivariateSurfaceInterpolationScheme< Type > Class Template Reference
multivariateSurfaceInterpolationScheme< Type > Class Template Reference abstract
Abstract base class for multi-variate surface interpolation schemes.
Classes
class fieldScheme
surfaceInterpolationScheme sub-class returned by operator(field)
class fieldTable
fieldTable
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, multivariateSurfaceInterpolationScheme, Istream,(const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &is),(mesh, fields, faceFlux, is))
multivariateSurfaceInterpolationScheme (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Construct for interpolating given field.
virtual ~multivariateSurfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
const fieldTable & fields () const
Return fields to be interpolated.
virtual tmp< surfaceInterpolationScheme< Type > > operator() (const GeometricField< Type, fvPatchField, volMesh > &field) const =0
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static tmp< multivariateSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::multivariateSurfaceInterpolationScheme< Type >
Abstract base class for multi-variate surface interpolation schemes.
Source files
multivariateSurfaceInterpolationScheme.H
multivariateSurfaceInterpolationScheme.C
Definition at line 50 of file multivariateSurfaceInterpolationScheme.H.
Constructor & Destructor Documentation
multivariateSurfaceInterpolationScheme()
multivariateSurfaceInterpolationScheme (const fvMesh & mesh, const fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData)
Construct for interpolating given field.
~multivariateSurfaceInterpolationScheme()
~multivariateSurfaceInterpolationScheme () virtual
Destructor.
Definition at line 93 of file multivariateSurfaceInterpolationScheme.C.
Referenced by multivariateSurfaceInterpolationScheme< Type >::fieldTable::add(), and multivariateSurfaceInterpolationScheme< Type >::New().
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
Referenced by multivariateSurfaceInterpolationScheme< Type >::fieldTable::add().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (tmp , multivariateSurfaceInterpolationScheme< Type > , Istream , (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &is) , (mesh, fields, faceFlux, is))
Referenced by multivariateSurfaceInterpolationScheme< Type >::fieldTable::add().
New()
Foam::tmp< Foam::multivariateSurfaceInterpolationScheme< Type > > New (const fvMesh & mesh, const fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData) static
Return a pointer to a new gradScheme created on freestore.
Definition at line 56 of file multivariateSurfaceInterpolationScheme.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, mesh, Foam::nl, and multivariateSurfaceInterpolationScheme< Type >::~multivariateSurfaceInterpolationScheme().
Referenced by multivariateSurfaceInterpolationScheme< Type >::fieldTable::add().
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 151 of file multivariateSurfaceInterpolationScheme.H.
Referenced by multivariateSurfaceInterpolationScheme< Type >::fieldTable::add().
fields()
const fieldTable& fields () const inline
Return fields to be interpolated.
Definition at line 157 of file multivariateSurfaceInterpolationScheme.H.
Referenced by multivariateSurfaceInterpolationScheme< Type >::fieldTable::add().
operator()()
virtual tmp<surfaceInterpolationScheme<Type> > operator() (const GeometricField< Type, fvPatchField, volMesh > & field) const pure virtual
Implemented in multivariateUpwind< Type >, multivariateScheme< Type, Scheme >, multivariateSelectionScheme< Type >, and multivariateIndependentScheme< Type >.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateSurfaceInterpolationScheme/multivariateSurfaceInterpolationScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateSurfaceInterpolationScheme/multivariateSurfaceInterpolationScheme.C