OpenFOAM: biLinearFitPolynomial Class Reference
biLinearFitPolynomial Class Reference
BiLinear polynomial for interpolation fitting.
Static Public Member Functions
static label nTerms (const direction dim)
static void addCoeffs (scalar *coeffs, const vector &d, const scalar weight, const direction dim)
Detailed Description
BiLinear polynomial for interpolation fitting.
Can be used with the CentredFit scheme to create a biLinear surface interpolation scheme
Definition at line 48 of file biLinearFitPolynomial.H.
Member Function Documentation
nTerms()
static label nTerms (const direction dim) inline static
Definition at line 54 of file biLinearFitPolynomial.H.
References biLinearFitPolynomial::addCoeffs().
addCoeffs()
static void addCoeffs (scalar * coeffs, const vector & d, const scalar weight, const direction dim) inline static
Definition at line 65 of file biLinearFitPolynomial.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by biLinearFitPolynomial::nTerms().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/biLinearFit/biLinearFitPolynomial.H