OpenFOAM: downwind< Type > Class Template Reference
downwind< Type > Class Template Reference
Downwind differencing scheme class.
Public Member Functions
TypeName ("downwind")
Runtime type information.
downwind (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from faceFlux.
downwind (const fvMesh &mesh, Istream &is)
Construct from Istream.
downwind (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &)
Construct from faceFlux and Istream.
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::downwind< Type >
Downwind differencing scheme class.
Source files
downwind.H
downwind.C
Definition at line 51 of file downwind.H.
Constructor & Destructor Documentation
downwind() [1/3]
downwind (const fvMesh & mesh, const surfaceScalarField & faceFlux) inline
Construct from faceFlux.
Definition at line 76 of file downwind.H.
Referenced by downwind< Type >::downwind().
downwind() [2/3]
downwind (const fvMesh & mesh, Istream & is) inline
Construct from Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 89 of file downwind.H.
References downwind< Type >::downwind().
downwind() [3/3]
downwind (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream &) inline
Construct from faceFlux and Istream.
Definition at line 106 of file downwind.H.
References downwind< Type >::weights().
Member Function Documentation
TypeName()
TypeName ("downwind< Type >")
Runtime type information.
weights()
virtual tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 121 of file downwind.H.
References Foam::neg().
Referenced by downwind< Type >::downwind().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/downwind/downwind.H