OpenFOAM: multivariateScheme< Type, Scheme >::fieldScheme Class Reference
multivariateScheme< Type, Scheme >::fieldScheme Class Reference
surfaceInterpolationScheme sub-class returned by operator(field)
Public Member Functions
fieldScheme (const GeometricField< Type, fvPatchField, volMesh > &field, const surfaceScalarField &weights)
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Detailed Description
template<class Type, class Scheme>
class Foam::multivariateScheme< Type, Scheme >::fieldScheme
surfaceInterpolationScheme sub-class returned by operator(field)
which is used as the interpolation scheme for the field
Definition at line 94 of file multivariateScheme.H.
Constructor & Destructor Documentation
fieldScheme()
fieldScheme (const GeometricField< Type, fvPatchField, volMesh > & field, const surfaceScalarField & weights) inline
Definition at line 108 of file multivariateScheme.H.
References multivariateScheme< Type, Scheme >::fieldScheme::weights().
Referenced by multivariateScheme< Type, Scheme >::operator()().
Member Function Documentation
weights()
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline
Return the interpolation weighting factors.
Definition at line 123 of file multivariateScheme.H.
Referenced by multivariateScheme< Type, Scheme >::fieldScheme::fieldScheme().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateScheme/multivariateScheme.H