OpenFOAM: vanAlbadaLimiter< LimiterFunc > Class Template Reference
vanAlbadaLimiter< LimiterFunc > Class Template Reference
Class with limiter function which returns the limiter for the vanAlbada differencing scheme based on r obtained from the LimiterFunc class.
Public Member Functions
vanAlbadaLimiter (Istream &)
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType &phiP, const typename LimiterFunc::phiType &phiN, const typename LimiterFunc::gradPhiType &gradcP, const typename LimiterFunc::gradPhiType &gradcN, const vector &d) const
Detailed Description
template<class LimiterFunc>
class Foam::vanAlbadaLimiter< LimiterFunc >
Class with limiter function which returns the limiter for the vanAlbada differencing scheme based on r obtained from the LimiterFunc class.
Used in conjunction with the template class LimitedScheme.
Source files
vanAlbada.H
vanAlbada.C
Definition at line 53 of file vanAlbada.H.
Constructor & Destructor Documentation
vanAlbadaLimiter()
vanAlbadaLimiter (Istream &) inline
Definition at line 60 of file vanAlbada.H.
References vanAlbadaLimiter< LimiterFunc >::limiter().
Member Function Documentation
limiter()
scalar limiter (const scalar cdWeight, const scalar faceFlux, const typename LimiterFunc::phiType & phiP, const typename LimiterFunc::phiType & phiN, const typename LimiterFunc::gradPhiType & gradcP, const typename LimiterFunc::gradPhiType & gradcN, const vector & d) const inline
Definition at line 64 of file vanAlbada.H.
References Foam::sqr().
Referenced by vanAlbadaLimiter< LimiterFunc >::vanAlbadaLimiter().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/vanAlbada/vanAlbada.H