OpenFOAM: cellCoBlended< Type > Class Template Reference
cellCoBlended< Type > Class Template Reference
Two-scheme cell-based Courant number based blending differencing scheme.
Public Member Functions
TypeName ("cellCoBlended")
Runtime type information.
cellCoBlended (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
cellCoBlended (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from mesh, faceFlux and Istream.
virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-based blending factor.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the interpolation weighting factors.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from blendedSchemeBase< Type >
blendedSchemeBase ()
Constructor.
virtual ~blendedSchemeBase ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::cellCoBlended< Type >
Two-scheme cell-based Courant number based blending differencing scheme.
This scheme is equivalent to the CoBlended scheme except that the Courant number is evaluated for cells using the same approach as use in the finite-volume solvers and then interpolated to the faces rather than being estimated directly at the faces based on the flux. This is a more consistent method for evaluating the Courant number but suffers from the need to interpolate which introduces a degree of freedom. However, the interpolation scheme for "Co" is run-time selected and may be specified in "interpolationSchemes" and "localMax" might be most appropriate.
Example of the cellCoBlended scheme specification using LUST for Courant numbers less than 1 and linearUpwind for Courant numbers greater than 10:
divSchemes
{
    .
    .
    div(phi,U)  Gauss cellCoBlended 1 LUST grad(U) 10 linearUpwind grad(U);
    .
    .
}
interpolationSchemes
{
    .
    .
    interpolate(Co) localMax;
    .
    .
}
See also
Foam::CoBlended Foam::localBlended
Source files
cellCoBlended.H
cellCoBlended.C
Definition at line 88 of file cellCoBlended.H.
Constructor & Destructor Documentation
cellCoBlended() [1/2]
cellCoBlended (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 132 of file cellCoBlended.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
cellCoBlended() [2/2]
cellCoBlended (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from mesh, faceFlux and Istream.
Definition at line 165 of file cellCoBlended.H.
References cellCoBlended< Type >::blendingFactor(), Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
Member Function Documentation
TypeName()
TypeName ("cellCoBlended< Type >")
Runtime type information.
blendingFactor()
virtual tmp<surfaceScalarField> blendingFactor (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the face-based blending factor.
Implements blendedSchemeBase< Type >.
Definition at line 198 of file cellCoBlended.H.
References TimeState::deltaTValue(), Foam::dimArea, Foam::dimDensity, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimless, Foam::dimVelocity, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::fvc::interpolate(), Foam::mag(), Foam::max(), surfaceInterpolationScheme< Type >::mesh(), Foam::min(), IOobject::name(), rho, Foam::fvc::surfaceSum(), fvMesh::time(), Time::timeName(), fvMesh::V(), and cellCoBlended< Type >::weights().
Referenced by cellCoBlended< Type >::cellCoBlended(), cellCoBlended< Type >::correction(), cellCoBlended< Type >::interpolate(), and cellCoBlended< Type >::weights().
weights()
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 267 of file cellCoBlended.H.
References cellCoBlended< Type >::blendingFactor(), and cellCoBlended< Type >::interpolate().
Referenced by cellCoBlended< Type >::blendingFactor().
interpolate()
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the face-interpolate of the given cell field.
with explicit correction
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 283 of file cellCoBlended.H.
References cellCoBlended< Type >::blendingFactor().
Referenced by cellCoBlended< Type >::weights().
corrected()
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 296 of file cellCoBlended.H.
References cellCoBlended< Type >::correction().
Referenced by cellCoBlended< Type >::correction().
correction()
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the explicit correction to the face-interpolate.
for the given field
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 306 of file cellCoBlended.H.
References cellCoBlended< Type >::blendingFactor(), and cellCoBlended< Type >::corrected().
Referenced by cellCoBlended< Type >::corrected().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/cellCoBlended/cellCoBlended.H