OpenFOAM: vanLeerLimiter< LimiterFunc > Class Template Reference
vanLeerLimiter< LimiterFunc > Class Template Reference
Class with limiter function which returns the limiter for the vanLeer differencing scheme based on r obtained from the LimiterFunc class.
Public Member Functions
vanLeerLimiter (Istream &)
scalar limiter (const scalar, const scalar faceFlux, const typename LimiterFunc::phiType &phiP, const typename LimiterFunc::phiType &phiN, const typename LimiterFunc::gradPhiType &gradcP, const typename LimiterFunc::gradPhiType &gradcN, const vector &d) const
Detailed Description
template<class LimiterFunc>
class Foam::vanLeerLimiter< LimiterFunc >
Class with limiter function which returns the limiter for the vanLeer differencing scheme based on r obtained from the LimiterFunc class.
Used in conjunction with the template class LimitedScheme.
Source files
vanLeer.H
vanLeer.C
Definition at line 53 of file vanLeer.H.
Constructor & Destructor Documentation
vanLeerLimiter()
vanLeerLimiter (Istream &) inline
Definition at line 60 of file vanLeer.H.
References vanLeerLimiter< LimiterFunc >::limiter().
Member Function Documentation
limiter()
scalar limiter (const scalar , const scalar faceFlux, const typename LimiterFunc::phiType & phiP, const typename LimiterFunc::phiType & phiN, const typename LimiterFunc::gradPhiType & gradcP, const typename LimiterFunc::gradPhiType & gradcN, const vector & d) const inline
Definition at line 64 of file vanLeer.H.
References Foam::mag().
Referenced by vanLeerLimiter< LimiterFunc >::vanLeerLimiter().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/limitedSchemes/vanLeer/vanLeer.H