OpenFOAM: multivariateSelectionScheme< Type >::fieldScheme Class Reference
multivariateSelectionScheme< Type >::fieldScheme Class Reference
surfaceInterpolationScheme sub-class returned by operator(field)
Public Member Functions
fieldScheme (const GeometricField< Type, fvPatchField, volMesh > &field, const surfaceScalarField &weights)
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from multivariateSurfaceInterpolationScheme< Type >::fieldScheme
fieldScheme (const GeometricField< Type, fvPatchField, volMesh > &field)
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::multivariateSelectionScheme< Type >::fieldScheme
surfaceInterpolationScheme sub-class returned by operator(field)
which is used as the interpolation scheme for the field
Definition at line 94 of file multivariateSelectionScheme.H.
Constructor & Destructor Documentation
fieldScheme()
fieldScheme (const GeometricField< Type, fvPatchField, volMesh > & field, const surfaceScalarField & weights) inline
Definition at line 107 of file multivariateSelectionScheme.H.
References multivariateSelectionScheme< Type >::fieldScheme::weights().
Referenced by multivariateSelectionScheme< Type >::operator()().
Member Function Documentation
weights()
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Implements multivariateSurfaceInterpolationScheme< Type >::fieldScheme.
Definition at line 122 of file multivariateSelectionScheme.H.
Referenced by multivariateSelectionScheme< Type >::fieldScheme::fieldScheme().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateSelectionScheme/multivariateSelectionScheme.H