OpenFOAM: midPoint< Type > Class Template Reference
midPoint< Type > Class Template Reference
Mid-point interpolation (weighting factors = 0.5) scheme class.
Public Member Functions
TypeName ("midPoint")
Runtime type information.
midPoint (const fvMesh &mesh)
Construct from mesh.
midPoint (const fvMesh &mesh, Istream &)
Construct from Istream.
midPoint (const fvMesh &mesh, const surfaceScalarField &, Istream &)
Construct from faceFlux and Istream.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
template<class Type>
class Foam::midPoint< Type >
Mid-point interpolation (weighting factors = 0.5) scheme class.
Source files
midPoint.H
midPoint.C
Definition at line 50 of file midPoint.H.
Constructor & Destructor Documentation
midPoint() [1/3]
midPoint (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 69 of file midPoint.H.
Referenced by midPoint< Type >::midPoint().
midPoint() [2/3]
midPoint (const fvMesh & mesh, Istream &) inline
Construct from Istream.
Definition at line 75 of file midPoint.H.
References midPoint< Type >::midPoint().
midPoint() [3/3]
midPoint (const fvMesh & mesh, const surfaceScalarField & , Istream &) inline
Construct from faceFlux and Istream.
Definition at line 82 of file midPoint.H.
References midPoint< Type >::weights().
Member Function Documentation
TypeName()
TypeName ("midPoint< Type >")
Runtime type information.
weights()
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 96 of file midPoint.H.
References Foam::dimless, forAll, surfaceInterpolationScheme< Type >::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, patchi, tmp< T >::ref(), and timeName.
Referenced by midPoint< Type >::midPoint().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/midPoint/midPoint.H