OpenFOAM: linearUpwindV< Type > Class Template Reference
linearUpwindV< Type > Class Template Reference
linearUpwindV interpolation scheme class derived from upwind and returns upwind weighting factors but also applies an explicit correction.
Public Member Functions
TypeName ("linearUpwindV")
Runtime type information.
linearUpwindV (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from faceFlux.
linearUpwindV (const fvMesh &mesh, Istream &schemeData)
Construct from Istream.
linearUpwindV (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Construct from faceFlux and Istream.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from upwind< Type >
TypeName ("upwind")
Runtime type information.
upwind (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from faceFlux.
upwind (const fvMesh &mesh, Istream &is)
Construct from Istream.
upwind (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &)
Construct from faceFlux and Istream.
virtual tmp< surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation limiter.
tmp< surfaceScalarField > weights () const
Return the interpolation weighting factors.
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
TypeName ("limitedSurfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
limitedSurfaceInterpolationScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from mesh and faceFlux.
limitedSurfaceInterpolationScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual ~limitedSurfaceInterpolationScheme ()
Destructor.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &, const surfaceScalarField &CDweights, tmp< surfaceScalarField > tLimiter) const
Return the interpolation weighting factors for the given field,.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename innerProduct< vector, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< limitedSurfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< surfaceInterpolationScheme< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField< typename innerProduct< typename SFType::value_type, Type >::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes inherited from limitedSurfaceInterpolationScheme< Type >
const surfaceScalarField & faceFlux_
Detailed Description
template<class Type>
class Foam::linearUpwindV< Type >
linearUpwindV interpolation scheme class derived from upwind and returns upwind weighting factors but also applies an explicit correction.
Source files
linearUpwindV.H
linearUpwindV.C
Definition at line 51 of file linearUpwindV.H.
Constructor & Destructor Documentation
linearUpwindV() [1/3]
linearUpwindV (const fvMesh & mesh, const surfaceScalarField & faceFlux) inline
Construct from faceFlux.
Definition at line 80 of file linearUpwindV.H.
linearUpwindV() [2/3]
linearUpwindV (const fvMesh & mesh, Istream & schemeData) inline
Construct from Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 97 of file linearUpwindV.H.
linearUpwindV() [3/3]
linearUpwindV (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) inline
Construct from faceFlux and Istream.
Definition at line 116 of file linearUpwindV.H.
Member Function Documentation
TypeName()
TypeName ("linearUpwindV< Type >")
Runtime type information.
corrected()
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 138 of file linearUpwindV.H.
References linearUpwindV< Type >::correction().
correction()
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the explicit correction to the face-interpolate.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 36 of file linearUpwindV.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvMesh::Cf(), fvsPatchField< Type >::coupled(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, Foam::magSqr(), makelimitedSurfaceInterpolationTypeScheme, mesh, IOobject::name(), fvMesh::neighbour(), fvMesh::owner(), patchi, GeometricField< Type, PatchField, GeoMesh >::ref(), fvMesh::time(), Time::timeName(), surfaceInterpolation::weights(), and Foam::Zero.
Referenced by linearUpwindV< Type >::corrected().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/linearUpwind/linearUpwindV.H
src/finiteVolume/interpolation/surfaceInterpolation/schemes/linearUpwind/linearUpwindV.C