OpenFOAM: surfaceInterpolation Class Reference
surfaceInterpolation Class Reference
Cell to surface interpolation scheme. Included in fvMesh.
Public Member Functions
ClassName ("surfaceInterpolation")
surfaceInterpolation (const fvMesh &)
Construct given an fvMesh.
~surfaceInterpolation ()
Destructor.
const surfaceScalarField & weights () const
Return reference to linear difference weighting factors.
const surfaceScalarField & deltaCoeffs () const
Return reference to cell-centre difference coefficients.
const surfaceScalarField & nonOrthDeltaCoeffs () const
Return reference to non-orthogonal cell-centre difference.
const surfaceVectorField & nonOrthCorrectionVectors () const
Return reference to non-orthogonality correction vectors.
bool movePoints ()
Do what is neccessary if the mesh has moved.
Protected Member Functions
void clearOut ()
Clear all geometry and addressing.
Detailed Description
Cell to surface interpolation scheme. Included in fvMesh.
Source files
surfaceInterpolation.H
surfaceInterpolation.C
Definition at line 52 of file surfaceInterpolation.H.
Constructor & Destructor Documentation
surfaceInterpolation()
surfaceInterpolation (const fvMesh & fvm) explicit
Construct given an fvMesh.
Definition at line 56 of file surfaceInterpolation.C.
~surfaceInterpolation()
~surfaceInterpolation ()
Destructor.
Definition at line 68 of file surfaceInterpolation.C.
References surfaceInterpolation::clearOut().
Member Function Documentation
clearOut()
void clearOut () protected
Clear all geometry and addressing.
Definition at line 45 of file surfaceInterpolation.C.
References Foam::deleteDemandDrivenData().
Referenced by fvMesh::clearOut(), fvMesh::updateMesh(), and surfaceInterpolation::~surfaceInterpolation().
ClassName()
ClassName ("surfaceInterpolation")
weights()
const Foam::surfaceScalarField & weights () const
Return reference to linear difference weighting factors.
Definition at line 77 of file surfaceInterpolation.C.
Referenced by isoSurface::adaptPatchFields(), cubic< Type >::correction(), pointLinear< Type >::correction(), linearUpwindV< Type >::correction(), surfaceInterpolation::movePoints(), and fvPatch::weights().
deltaCoeffs()
const Foam::surfaceScalarField & deltaCoeffs () const
Return reference to cell-centre difference coefficients.
Definition at line 89 of file surfaceInterpolation.C.
Referenced by CoBlended< Type >::blendingFactor(), contactAngleForce::correct(), orthogonalSnGrad< Type >::deltaCoeffs(), fvPatch::deltaCoeffs(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), surfaceInterpolation::movePoints(), reactingOneDim::solidRegionDiffNo(), and skewCorrectionVectors::~skewCorrectionVectors().
nonOrthDeltaCoeffs()
const Foam::surfaceScalarField & nonOrthDeltaCoeffs () const
Return reference to non-orthogonal cell-centre difference.
coefficients
Definition at line 101 of file surfaceInterpolation.C.
Referenced by CentredFitSnGradData< Polynomial >::calcFit(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), correctedSnGrad< Type >::deltaCoeffs(), uncorrectedSnGrad< Type >::deltaCoeffs(), faceCorrectedSnGrad< Type >::deltaCoeffs(), CentredFitSnGradScheme< Type, Polynomial, Stencil >::deltaCoeffs(), limitedSnGrad< Type >::deltaCoeffs(), faceCorrectedSnGrad< Type >::fullGradCorrection(), and surfaceInterpolation::movePoints().
nonOrthCorrectionVectors()
const Foam::surfaceVectorField & nonOrthCorrectionVectors () const
Return reference to non-orthogonality correction vectors.
Definition at line 113 of file surfaceInterpolation.C.
Referenced by correctedSnGrad< Type >::fullGradCorrection().
movePoints()
bool movePoints ()
Do what is neccessary if the mesh has moved.
Definition at line 124 of file surfaceInterpolation.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), fvMesh::C(), primitiveMesh::cellCentres(), fvsPatchField< Type >::coupled(), Foam::deleteDemandDrivenData(), delta, surfaceInterpolation::deltaCoeffs(), Foam::dimLength, Foam::dimless, Foam::endl(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), forAll, Foam::mag(), fvMesh::magSf(), Foam::max(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, surfaceInterpolation::nonOrthDeltaCoeffs(), fvMesh::owner(), p, fvsPatchField< Type >::patch(), patchi, polyMesh::pointsInstance(), Foam::Pout, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), fvMesh::Sf(), surfaceInterpolation::weights(), and Foam::Zero.
Referenced by layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), fvMesh::movePoints(), fvMesh::neighbour(), dynamicMotionSolverFvMesh::update(), rawTopoChangerFvMesh::update(), dynamicInkJetFvMesh::update(), multiSolidBodyMotionFvMesh::update(), linearValveFvMesh::update(), linearValveLayersFvMesh::update(), solidBodyMotionFvMesh::update(), and movingConeTopoFvMesh::update().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolation/surfaceInterpolation.H
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolation/surfaceInterpolation.C