OpenFOAM: fieldMinMax Class Reference
fieldMinMax Class Reference
FunctionObjects » Field function objects
Calculates the value and location of scalar minimim and maximum for a list of user-specified fields.
Public Types
enum modeType { mdMag, mdCmpt }
Public Member Functions
TypeName ("fieldMinMax")
Runtime type information.
fieldMinMax (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~fieldMinMax ()
Destructor.
virtual bool read (const dictionary &)
Read the field min/max data.
virtual bool execute ()
Execute, currently does nothing.
virtual bool write ()
Write the fieldMinMax.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from logFiles
logFiles (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
virtual ~logFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file ()
Return access to the file (if only 1)
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
~writeFile ()
Destructor.
void initStream (Ostream &os) const
Initialise the output stream for writing.
fileName baseFileDir () const
Return the base directory for output.
fileName baseTimeDir () const
Return the base directory for the current time value.
Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Protected Member Functions
template<class Type >
void output (const word &fieldName, const word &outputName, const vector &minC, const vector &maxC, const label minProci, const label maxProci, const Type &minValue, const Type &maxValue)
Helper function to write the output.
fieldMinMax (const fieldMinMax &)
Disallow default bitwise copy construct.
void operator= (const fieldMinMax &)
Disallow default bitwise assignment.
template<class Type >
void calcMinMaxFields (const word &fieldName, const modeType &mode)
Calculate the field min/max.
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Member Functions inherited from logFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
Protected Attributes
Switch location_
Switch to write location of min/max values.
modeType mode_
Mode for min/max - only applicable for ranks > 0.
wordList fieldSet_
Fields to assess min/max.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Protected Attributes inherited from logFiles
wordList names_
File names.
PtrList< OFstream > filePtrs_
File pointer.
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
Reference to the region objectRegistry.
const word prefix_
Prefix.
Static Protected Attributes
static const NamedEnum< modeType, 2 > modeTypeNames_
Mode type names.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Detailed Description
Calculates the value and location of scalar minimim and maximum for a list of user-specified fields.
For variables with a rank greater than zero, either the min/max of a component value or the magnitude is reported. When operating in parallel, the processor owning the value is also given.
Example of function object specification:
fieldMinMax1
{
    type        fieldMinMax;
    libs        ("libfieldFunctionObjects.so");
    ...
    write       yes;
    log         yes;
    location    yes;
    mode        magnitude;
    fields
    (
        U
        p
    );
}
Usage
Property Description Required Default value
type type name: fieldMinMax yes
write write min/max data to file no yes
log write min/max data to standard output no no
location write location of the min/max value no yes
mode calculation mode: magnitude or component no magnitude
Output data is written to the file <timeDir>/fieldMinMax.dat
See also
Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::logFiles
Source files
fieldMinMax.H
fieldMinMax.C
Definition at line 125 of file fieldMinMax.H.
Member Enumeration Documentation
modeType
enum modeType
Enumerator
mdMag
mdCmpt
Definition at line 132 of file fieldMinMax.H.
Constructor & Destructor Documentation
fieldMinMax() [1/2]
fieldMinMax (const fieldMinMax &) protected
Disallow default bitwise copy construct.
Referenced by fieldMinMax::writeFileHeader().
fieldMinMax() [2/2]
fieldMinMax (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 100 of file fieldMinMax.C.
References Foam::read().
~fieldMinMax()
~fieldMinMax () virtual
Destructor.
Definition at line 119 of file fieldMinMax.C.
Member Function Documentation
output()
void output (const word & fieldName, const word & outputName, const vector & minC, const vector & maxC, const label minProci, const label maxProci, const Type & minValue, const Type & maxValue) protected
Helper function to write the output.
Definition at line 33 of file fieldMinMaxTemplates.C.
References fieldMinMax::calcMinMaxFields(), Foam::endl(), Log, maxValue, and Foam::nl.
operator=()
void operator= (const fieldMinMax &) protected
Disallow default bitwise assignment.
calcMinMaxFields()
void calcMinMaxFields (const word & fieldName, const modeType & mode) protected
Calculate the field min/max.
Definition at line 100 of file fieldMinMaxTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findMax(), Foam::findMin(), forAll, Foam::mag(), patchi, List< T >::size(), and List< Type >::size().
Referenced by fieldMinMax::output().
writeFileHeader()
void writeFileHeader (const label i) protected virtual
Output file header information.
Implements logFiles.
Definition at line 57 of file fieldMinMax.C.
References Foam::endl(), fieldMinMax::fieldMinMax(), forAll, and UPstream::parRun().
TypeName()
TypeName ("fieldMinMax")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the field min/max data.
Reimplemented from regionFunctionObject.
Definition at line 125 of file fieldMinMax.C.
References dictionary::lookup(), dictionary::lookupOrDefault(), and regionFunctionObject::read().
execute()
bool execute () virtual
Execute, currently does nothing.
Implements functionObject.
Definition at line 138 of file fieldMinMax.C.
write()
bool write () virtual
Write the fieldMinMax.
Reimplemented from logFiles.
Definition at line 144 of file fieldMinMax.C.
References Foam::endl(), forAll, Log, Foam::name(), Foam::nl, Foam::type(), and logFiles::write().
Member Data Documentation
modeTypeNames_
const Foam::NamedEnum< Foam::functionObjects::fieldMinMax::modeType, 2 > modeTypeNames_ static protected
Mode type names.
Definition at line 143 of file fieldMinMax.H.
Referenced by NamedEnum< directionType, 3 >::names().
location_
Switch location_ protected
Switch to write location of min/max values.
Definition at line 146 of file fieldMinMax.H.
mode_
modeType mode_ protected
Mode for min/max - only applicable for ranks > 0.
Definition at line 149 of file fieldMinMax.H.
fieldSet_
wordList fieldSet_ protected
Fields to assess min/max.
Definition at line 152 of file fieldMinMax.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldMinMax/fieldMinMax.H
src/functionObjects/field/fieldMinMax/fieldMinMax.C
src/functionObjects/field/fieldMinMax/fieldMinMaxTemplates.C