OpenFOAM: fieldAverage Class Reference
fieldAverage Class Reference
FunctionObjects » Field function objects
Calculates average quantities for a user-specified selection of volumetric and surface fields.
Public Member Functions
TypeName ("fieldAverage")
Runtime type information.
fieldAverage (const word &name, const Time &runTime, const dictionary &)
Construct from Time and dictionary.
virtual ~fieldAverage ()
Destructor.
virtual bool read (const dictionary &)
Read the field average data.
virtual bool execute ()
Calculate the field averages.
virtual bool write ()
Write the field averages.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
void resetFields ()
Checkout fields (causes deletion) from the database.
void initialize ()
Reset lists (clear existing values) and initialize averaging.
void restart ()
Restart averaging for restartOnOutput.
template<class Type >
void addMeanFieldType (const label fieldi)
Add mean average field to database.
template<class Type >
void addMeanField (const label fieldi)
Add mean average field to database.
template<class Type1 , class Type2 >
void addPrime2MeanFieldType (const label fieldi)
Add prime-squared average field to database.
template<class Type1 , class Type2 >
void addPrime2MeanField (const label fieldi)
Add prime-squared average field to database.
virtual void calcAverages ()
Main calculation routine.
template<class Type >
void calculateMeanFieldType (const label fieldi) const
Calculate mean average fields.
template<class Type >
void calculateMeanFields () const
Calculate mean average fields.
template<class Type1 , class Type2 >
void calculatePrime2MeanFieldType (const label fieldi) const
Calculate prime-squared average fields.
template<class Type1 , class Type2 >
void calculatePrime2MeanFields () const
Calculate prime-squared average fields.
template<class Type1 , class Type2 >
void addMeanSqrToPrime2MeanType (const label fieldi) const
Add mean-squared field value to prime-squared mean field.
template<class Type1 , class Type2 >
void addMeanSqrToPrime2Mean () const
Add mean-squared field value to prime-squared mean field.
virtual void writeAverages () const
Write averages.
template<class Type >
void writeFieldType (const word &fieldName) const
Write fields.
template<class Type >
void writeFields () const
Write fields.
void writeAveragingProperties () const
Write averaging properties - steps and time.
void readAveragingProperties ()
Read averaging properties - steps and time.
fieldAverage (const fieldAverage &)
Disallow default bitwise copy construct.
void operator= (const fieldAverage &)
Disallow default bitwise assignment.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
label prevTimeIndex_
Time at last call, prevents repeated averaging.
Switch restartOnRestart_
Restart the averaging process on restart.
Switch restartOnOutput_
Restart the averaging process on output.
Switch periodicRestart_
Periodically restart the averaging process.
scalar restartPeriod_
Restart period.
bool initialised_
Initialised flag.
List< fieldAverageItem > faItems_
List of field average items, describing what averages to be.
List< label > totalIter_
Iteration steps counter.
List< scalar > totalTime_
Total time counter.
label periodIndex_
Index for periodic restart.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Calculates average quantities for a user-specified selection of volumetric and surface fields.
Fields are entered as a list of sub-dictionaries, which indicate the type of averages to perform, and can be updated during the calculation. The current options include:
mean: arithmetic mean:
prime2Mean: prime-squared mean
base: average over 'time', or 'iteration' (in the above)
window: optional averaging window, specified in 'base' units
Average field names are constructed by concatenating the base field with the averaging type, e.g. when averaging field 'U', the resultant fields are:
arithmetic mean field, UMean
prime-squared field, UPrime2Mean
Information regarding the number of averaging steps, and total averaging time are written on a per-field basis to the "<functionObject name>Properties" dictionary, located in <time>/uniform
When restarting form a previous calculation, the averaging is continuous or may be restarted using the restartOnRestart option.
The averaging process may be restarted after each calculation output time using the restartOnOutput option or restarted periodically using the periodicRestart option and setting restartPeriod to the required averaging period.
Example of function object specification:
fieldAverage1
{
    type                fieldAverage;
    libs                ("libfieldFunctionObjects.so");
    writeControl    writeTime;
    restartOnRestart    false;
    restartOnOutput     false;
    periodicRestart     false;
    restartPeriod       0.002;
    fields
    (
        U
        {
            mean            on;
            prime2Mean      on;
            base            time;
            window          10.0;
            windowName      w1;
        }
        p
        {
            mean            on;
            prime2Mean      on;
            base            time;
        }
    );
}
Usage
Property Description Required Default value
type type name: fieldAverage yes
restartOnRestart Restart the averaging on restart no no
restartOnOutput Restart the averaging on output no no
periodicRestart Periodically restart the averaging no no
restartPeriod Periodic restart period conditional
fields list of fields and averaging options yes
Note
To employ the prime2Mean option, the mean option must be selecetd.
See also
Foam::functionObjects::fvMeshFunctionObject Foam::functionObject
Source files
fieldAverage.H
fieldAverage.C
fieldAverageTemplates.C
fieldAverageItem.C
Definition at line 180 of file fieldAverage.H.
Constructor & Destructor Documentation
fieldAverage() [1/2]
fieldAverage (const fieldAverage &) protected
Disallow default bitwise copy construct.
Referenced by fieldAverage::readAveragingProperties().
fieldAverage() [2/2]
fieldAverage (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 269 of file fieldAverage.C.
References Foam::read().
~fieldAverage()
~fieldAverage () virtual
Destructor.
Definition at line 293 of file fieldAverage.C.
Member Function Documentation
resetFields()
void resetFields () protected
Checkout fields (causes deletion) from the database.
and reset lists
Definition at line 45 of file fieldAverage.C.
References forAll.
initialize()
void initialize () protected
Reset lists (clear existing values) and initialize averaging.
Check requested field averages are valid, populate field lists
Definition at line 68 of file fieldAverage.C.
References forAll.
restart()
void restart () protected
Restart averaging for restartOnOutput.
Definition at line 96 of file fieldAverage.C.
References Foam::endl(), Log, and Foam::nl.
addMeanFieldType()
void addMeanFieldType (const label fieldi) protected
Add mean average field to database.
Definition at line 34 of file fieldAverageTemplates.C.
References Foam::endl(), fieldAverage::faItems_, HashTable< T, Key, Hash >::found(), objectRegistry::foundObject(), Log, objectRegistry::lookupObject(), IOobject::NO_READ, IOobject::NO_WRITE, regionFunctionObject::obr_, IOobject::READ_IF_PRESENT, fieldAverage::restartOnOutput_, Time::startTime(), regIOobject::store(), objectRegistry::time(), Time::timeName(), and dimensioned< Type >::value().
addMeanField()
void addMeanField (const label fieldi) protected
Add mean average field to database.
Definition at line 80 of file fieldAverageTemplates.C.
References fieldAverage::addPrime2MeanFieldType(), fieldAverage::faItems_, objectRegistry::foundObject(), and regionFunctionObject::obr_.
addPrime2MeanFieldType()
void addPrime2MeanFieldType (const label fieldi) protected
Add prime-squared average field to database.
Definition at line 106 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, HashTable< T, Key, Hash >::found(), objectRegistry::foundObject(), Log, objectRegistry::lookupObject(), Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, regionFunctionObject::obr_, IOobject::READ_IF_PRESENT, fieldAverage::restartOnOutput_, Foam::sqr(), Time::startTime(), regIOobject::store(), objectRegistry::time(), Time::timeName(), and dimensioned< Type >::value().
Referenced by fieldAverage::addMeanField().
addPrime2MeanField()
void addPrime2MeanField (const label fieldi) protected
Add prime-squared average field to database.
Definition at line 156 of file fieldAverageTemplates.C.
References fieldAverage::calculateMeanFieldType(), Foam::exit(), fieldAverage::faItems_, Foam::FatalError, FatalErrorInFunction, objectRegistry::foundObject(), Foam::nl, and regionFunctionObject::obr_.
calcAverages()
void calcAverages () protected virtual
Main calculation routine.
Definition at line 112 of file fieldAverage.C.
References Foam::endl(), forAll, Log, Foam::name(), Foam::nl, and Foam::type().
calculateMeanFieldType()
void calculateMeanFieldType (const label fieldi) const protected
Calculate mean average fields.
Definition at line 193 of file fieldAverageTemplates.C.
References Foam::constant::atomic::alpha, beta(), TimeState::deltaTValue(), fieldAverage::faItems_, objectRegistry::foundObject(), objectRegistry::lookupObject(), regionFunctionObject::obr_, objectRegistry::time(), fieldAverage::totalIter_, and fieldAverage::totalTime_.
Referenced by fieldAverage::addPrime2MeanField().
calculateMeanFields()
void calculateMeanFields () const protected
Calculate mean average fields.
Definition at line 237 of file fieldAverageTemplates.C.
References fieldAverage::calculatePrime2MeanFieldType(), fieldAverage::faItems_, and forAll.
calculatePrime2MeanFieldType()
void calculatePrime2MeanFieldType (const label fieldi) const protected
Calculate prime-squared average fields.
Definition at line 255 of file fieldAverageTemplates.C.
References Foam::constant::atomic::alpha, beta(), TimeState::deltaTValue(), fieldAverage::faItems_, objectRegistry::foundObject(), objectRegistry::lookupObject(), regionFunctionObject::obr_, Foam::sqr(), objectRegistry::time(), fieldAverage::totalIter_, and fieldAverage::totalTime_.
Referenced by fieldAverage::calculateMeanFields().
calculatePrime2MeanFields()
void calculatePrime2MeanFields () const protected
Calculate prime-squared average fields.
Definition at line 304 of file fieldAverageTemplates.C.
References fieldAverage::addMeanSqrToPrime2MeanType(), fieldAverage::faItems_, and forAll.
addMeanSqrToPrime2MeanType()
void addMeanSqrToPrime2MeanType (const label fieldi) const protected
Add mean-squared field value to prime-squared mean field.
Definition at line 332 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, objectRegistry::foundObject(), objectRegistry::lookupObject(), regionFunctionObject::obr_, and Foam::sqr().
Referenced by fieldAverage::calculatePrime2MeanFields().
addMeanSqrToPrime2Mean()
void addMeanSqrToPrime2Mean () const protected
Add mean-squared field value to prime-squared mean field.
Definition at line 354 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, forAll, and fieldAverage::writeFieldType().
writeAverages()
void writeAverages () const protected virtual
Write averages.
Definition at line 163 of file fieldAverage.C.
References Foam::endl(), and Log.
writeFieldType()
void writeFieldType (const word & fieldName) const protected
Write fields.
Definition at line 375 of file fieldAverageTemplates.C.
References f(), objectRegistry::foundObject(), objectRegistry::lookupObject(), and regionFunctionObject::obr_.
Referenced by fieldAverage::addMeanSqrToPrime2Mean().
writeFields()
void writeFields () const protected
Write fields.
Definition at line 388 of file fieldAverageTemplates.C.
References fieldAverage::faItems_, and forAll.
writeAveragingProperties()
void writeAveragingProperties () const protected
Write averaging properties - steps and time.
Definition at line 177 of file fieldAverage.C.
References dictionary::add(), Foam::endl(), forAll, Log, Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, propsDict(), and dictionary::subDict().
readAveragingProperties()
void readAveragingProperties () protected
Read averaging properties - steps and time.
Definition at line 207 of file fieldAverage.C.
References fieldAverage::fieldAverage(), forAll, dictionary::found(), IOobject::headerOk(), Foam::Info, Foam::log(), Log, IOobject::MUST_READ_IF_MODIFIED, Foam::name(), Foam::nl, IOobject::NO_WRITE, propsDict(), Foam::readLabel(), Foam::readScalar(), and dictionary::subDict().
operator=()
void operator= (const fieldAverage &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("fieldAverage")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the field average data.
Reimplemented from regionFunctionObject.
Definition at line 299 of file fieldAverage.C.
References Foam::endl(), Log, dictionary::lookup(), Foam::name(), Foam::nl, regionFunctionObject::read(), dictionary::readIfPresent(), and Foam::type().
execute()
bool execute () virtual
Calculate the field averages.
Implements functionObject.
Definition at line 325 of file fieldAverage.C.
write()
bool write () virtual
Write the field averages.
Implements functionObject.
Definition at line 333 of file fieldAverage.C.
Member Data Documentation
prevTimeIndex_
label prevTimeIndex_ protected
Time at last call, prevents repeated averaging.
Definition at line 189 of file fieldAverage.H.
restartOnRestart_
Switch restartOnRestart_ protected
Restart the averaging process on restart.
Definition at line 192 of file fieldAverage.H.
restartOnOutput_
Switch restartOnOutput_ protected
Restart the averaging process on output.
Definition at line 195 of file fieldAverage.H.
Referenced by fieldAverage::addMeanFieldType(), and fieldAverage::addPrime2MeanFieldType().
periodicRestart_
Switch periodicRestart_ protected
Periodically restart the averaging process.
Definition at line 198 of file fieldAverage.H.
restartPeriod_
scalar restartPeriod_ protected
Restart period.
Definition at line 201 of file fieldAverage.H.
initialised_
bool initialised_ protected
Initialised flag.
Definition at line 204 of file fieldAverage.H.
faItems_
List<fieldAverageItem> faItems_ protected
List of field average items, describing what averages to be.
calculated and output
Definition at line 208 of file fieldAverage.H.
Referenced by fieldAverage::addMeanField(), fieldAverage::addMeanFieldType(), fieldAverage::addMeanSqrToPrime2Mean(), fieldAverage::addMeanSqrToPrime2MeanType(), fieldAverage::addPrime2MeanField(), fieldAverage::addPrime2MeanFieldType(), fieldAverage::calculateMeanFields(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFields(), fieldAverage::calculatePrime2MeanFieldType(), and fieldAverage::writeFields().
totalIter_
List<label> totalIter_ protected
Iteration steps counter.
Definition at line 213 of file fieldAverage.H.
Referenced by fieldAverage::calculateMeanFieldType(), and fieldAverage::calculatePrime2MeanFieldType().
totalTime_
List<scalar> totalTime_ protected
Total time counter.
Definition at line 216 of file fieldAverage.H.
Referenced by fieldAverage::calculateMeanFieldType(), and fieldAverage::calculatePrime2MeanFieldType().
periodIndex_
label periodIndex_ protected
Index for periodic restart.
Definition at line 219 of file fieldAverage.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldAverage/fieldAverage.H
src/functionObjects/field/fieldAverage/fieldAverage.C
src/functionObjects/field/fieldAverage/fieldAverageTemplates.C