OpenFOAM: surfaceFieldValue Class Reference
surfaceFieldValue Class Reference
FunctionObjects » Field function objects
Provides a 'face regionType' variant of the fieldValues function object.
Public Types
enum regionTypes { stFaceZone, stPatch, stSampledSurface }
region type enumeration
enum operationType {
opNone, opSum, opSumMag, opSumDirection,
opSumDirectionBalance, opAverage, opWeightedAverage, opAreaAverage,
opWeightedAreaAverage, opAreaIntegrate, opMin, opMax,
opCoV, opAreaNormalAverage, opAreaNormalIntegrate
}
Operation type enumeration.
Public Member Functions
TypeName ("surfaceFieldValue")
Run-time type information.
surfaceFieldValue (const word &name, const Time &runTime, const dictionary &dict)
Construct from name, Time and dictionary.
surfaceFieldValue (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from name, objectRegistry and dictionary.
virtual ~surfaceFieldValue ()
Destructor.
const regionTypes & regionType () const
Return the region type.
const labelList & faceId () const
Return the local list of face IDs.
const labelList & facePatch () const
Return the local list of patch ID per face.
const labelList & faceSign () const
Return the list of +1/-1 representing face flip map.
fileName outputDir () const
Return the output directory.
template<class Type >
bool writeValues (const word &fieldName, const scalarField &weightField, const bool orient)
Templated helper function to output field values.
template<class Type >
tmp< Field< Type > > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field, const bool applyOrientation) const
Filter a surface field according to faceIds.
template<class Type >
tmp< Field< Type > > filterField (const GeometricField< Type, fvPatchField, volMesh > &field, const bool applyOrientation) const
Filter a volume field according to faceIds.
virtual bool read (const dictionary &)
Read from dictionary.
virtual bool write ()
Calculate and write.
template<>
Foam::scalar processValues (const Field< scalar > &values, const vectorField &Sf, const scalarField &weightField) const
template<>
Foam::vector processValues (const Field< vector > &values, const vectorField &Sf, const scalarField &weightField) const
template<>
scalar processValues (const Field< scalar > &values, const vectorField &Sf, const scalarField &weightField) const
Specialisation for scalar.
template<>
vector processValues (const Field< vector > &values, const vectorField &Sf, const scalarField &weightField) const
Specialisation for vector.
template<class Type >
Foam::tmp< Foam::Field< Type > > getFieldValues (const word &fieldName, const bool mustGet, const bool applyOrientation) const
template<class Type >
Foam::tmp< Foam::Field< Type > > filterField (const GeometricField< Type, fvPatchField, volMesh > &field, const bool applyOrientation) const
template<class Type >
Foam::tmp< Foam::Field< Type > > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field, const bool applyOrientation) const
Public Member Functions inherited from fieldValue
TypeName ("fieldValue")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, fieldValue, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict),(name, obr, dict))
fieldValue (const word &name, const Time &runTime, const dictionary &dict, const word &valueType)
Construct from Time and dictionary.
fieldValue (const word &name, const objectRegistry &obr, const dictionary &dict, const word &valueType)
Construct from objectRegistry and dictionary.
virtual ~fieldValue ()
Destructor.
const dictionary & dict () const
Return the reference to the construction dictionary.
const word & regionName () const
Return the region name.
const wordList & fields () const
Return the list of field names.
const Switch & writeFields () const
Return the output field values flag.
const dictionary & resultDict () const
Return access to the latest set of results.
virtual bool execute ()
Execute.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from logFiles
logFiles (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
virtual ~logFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file ()
Return access to the file (if only 1)
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
~writeFile ()
Destructor.
void initStream (Ostream &os) const
Initialise the output stream for writing.
fileName baseFileDir () const
Return the base directory for output.
fileName baseTimeDir () const
Return the base directory for the current time value.
Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Attributes
static const NamedEnum< regionTypes, 3 > regionTypeNames_
region type names
static const NamedEnum< operationType, 15 > operationTypeNames_
Operation type names.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Member Functions
void initialise (const dictionary &dict)
Initialise, e.g. face addressing.
template<class Type >
bool validField (const word &fieldName) const
Return true if the field name is valid.
template<class Type >
tmp< Field< Type > > getFieldValues (const word &fieldName, const bool mustGet=false, const bool applyOrientation=false) const
Return field values by looking up field name.
template<class Type >
Type processSameTypeValues (const Field< Type > &values, const vectorField &Sf, const scalarField &weightField) const
Apply the 'operation' to the values. Operation has to.
template<class Type >
Type processValues (const Field< Type > &values, const vectorField &Sf, const scalarField &weightField) const
Apply the 'operation' to the values. Wrapper around.
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from fieldValue
template<class Type >
void combineFields (Field< Type > &field)
Combine fields from all processor domains into single field.
template<class Type >
void combineFields (tmp< Field< Type >> &)
Combine fields from all processor domains into single field.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Member Functions inherited from logFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
Protected Attributes
autoPtr< surfaceWriter > surfaceWriterPtr_
Surface writer.
regionTypes regionType_
region type
operationType operation_
Operation to apply to values.
word weightFieldName_
Weight field name - optional.
bool orientWeightField_
Flag to indicate if flipMap should be applied to the weight field.
label orientedFieldsStart_
Start index of fields that require application of flipMap.
scalar scaleFactor_
Scale factor - optional.
scalar totalArea_
Total area of the surfaceFieldValue.
bool writeArea_
Optionally write the area of the surfaceFieldValue.
label nFaces_
Global number of faces.
labelList faceId_
Local list of face IDs.
labelList facePatchId_
Local list of patch ID per face.
labelList faceSign_
List of +1/-1 representing face flip map.
autoPtr< sampledSurface > surfacePtr_
Underlying sampledSurface.
Protected Attributes inherited from fieldValue
dictionary dict_
Construction dictionary.
word regionName_
Name of region (patch, zone, etc.)
wordList fields_
List of field names to operate on.
Switch writeFields_
Output field values flag.
dictionary resultDict_
Results dictionary for external access of results.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Protected Attributes inherited from logFiles
wordList names_
File names.
PtrList< OFstream > filePtrs_
File pointer.
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
Reference to the region objectRegistry.
const word prefix_
Prefix.
Additional Inherited Members
Static Public Member Functions inherited from fieldValue
static autoPtr< fieldValue > New (const word &name, const objectRegistry &obr, const dictionary &dict, const bool output=true)
Return a reference to the selected fieldValue.
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Detailed Description
Provides a 'face regionType' variant of the fieldValues function object.
Given a list of user-specified fields and a selection of mesh (or general surface) faces, a number of operations can be performed, such as sums, averages and integrations.
For example, to calculate the volumetric or mass flux across a patch, apply the 'sum' operator to the flux field (typically phi)
Examples of function object specification:
movingWallPatch
{
    type            surfaceFieldValue;
    libs            ("libfieldFunctionObjects.so");
    log             true;
    writeControl    writeTime;
    writeFields     true;
    regionType      patch;
    name            movingWall;
    operation       areaAverage;
    fields
    (
        p
        phi
        U
    );
}
surfaceFieldValue1
{
    type            surfaceFieldValue;
    libs            ("libfieldFunctionObjects.so");
    log             true;
    writeControl    writeTime;
    writeFields     true;
    surfaceFormat   none;
    regionType      faceZone;
    name            f0;
    operation       sum;
    weightField     alpha1;
    fields
    (
        p
        phi
        U
    );
}
Usage
Property Description Required Default value
type type name: surfaceFieldValue yes
log write data to standard output no no
writeFields Write the region field values yes
writeArea Write the area of the surfaceFieldValue no
surfaceFormat output value format no
regionType face regionType: see below yes
name name of face regionType if required no
operation operation to perform yes
weightField name of field to apply weighting no
orientedWeightField name of oriented field to apply weighting no
scaleFactor scale factor no 1
fields list of fields to operate on yes
orientedFields list of oriented fields to operate on no
Where regionType is defined by
faceZone : requires a 'name' entry to specify the faceZone
patch : requires a 'name' entry to specify the patch
sampledSurface : requires a 'sampledSurfaceDict' sub-dictionary
The operation is one of:
none : no operation
sum : sum
sumMag : sum of component magnitudes
sumDirection : sum values which are positive in given direction
sumDirectionBalance : sum of balance of values in given direction
average : ensemble average
weightedAverage : weighted average
areaAverage : area weighted average
weightedAreaAverage : weighted area average
areaIntegrate : area integral
min : minimum
max : maximum
CoV : coefficient of variation: standard deviation/mean
areaNormalAverage : area weighted average in face normal direction
areaNormalIntegrate : area weighted integral in face normal directon
Note
The values reported by the areaNormalAverage and areaNormalIntegrate operations are written as the first component of a field with the same rank as the input field.
faces on empty patches get ignored
if the field is a volField the faceZone can only consist of boundary faces
the `oriented' entries relate to mesh-oriented fields, such as the flux, phi. These fields will be oriented according to the face normals.
using sampledSurface:
not available for surface fields
if interpolate=true they use interpolationCellPoint otherwise they use cell values
each triangle in sampledSurface is logically only in one cell so interpolation will be wrong when triangles are larger than cells. This can only happen for sampling on a triSurfaceMesh
take care when using isoSurfaces - these might have duplicate triangles and so integration might be wrong
See also
Foam::fieldValues Foam::functionObject
Source files
surfaceFieldValue.H
surfaceFieldValue.C
surfaceFieldValueTemplates.C
Definition at line 327 of file surfaceFieldValue.H.
Member Enumeration Documentation
regionTypes
enum regionTypes
region type enumeration
Enumerator
stFaceZone
stPatch
stSampledSurface
Definition at line 337 of file surfaceFieldValue.H.
operationType
enum operationType
Operation type enumeration.
Enumerator
opNone
opSum
opSumMag
opSumDirection
opSumDirectionBalance
opAverage
opWeightedAverage
opAreaAverage
opWeightedAreaAverage
opAreaIntegrate
opMin
opMax
opCoV
opAreaNormalAverage
opAreaNormalIntegrate
Definition at line 349 of file surfaceFieldValue.H.
Constructor & Destructor Documentation
surfaceFieldValue() [1/2]
surfaceFieldValue (const word & name, const Time & runTime, const dictionary & dict)
Construct from name, Time and dictionary.
Definition at line 650 of file surfaceFieldValue.C.
References Foam::read().
Referenced by surfaceFieldValue::processValues().
surfaceFieldValue() [2/2]
surfaceFieldValue (const word & name, const objectRegistry & obr, const dictionary & dict)
Construct from name, objectRegistry and dictionary.
Definition at line 674 of file surfaceFieldValue.C.
References Foam::read().
~surfaceFieldValue()
~surfaceFieldValue () virtual
Destructor.
Definition at line 700 of file surfaceFieldValue.C.
References surfaceFieldValue::read().
Member Function Documentation
initialise()
void initialise (const dictionary & dict) protected
Initialise, e.g. face addressing.
Definition at line 423 of file surfaceFieldValue.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), Foam::Info, dictionary::lookup(), Foam::name(), surfaceWriter::New(), Foam::nl, dictionary::readIfPresent(), List< T >::size(), dictionary::subOrEmptyDict(), Foam::type(), and surfaceFieldValue::writeFileHeader().
Referenced by NamedEnum< directionType, 3 >::names().
validField()
bool validField (const word & fieldName) const protected
Return true if the field name is valid.
Definition at line 37 of file surfaceFieldValueTemplates.C.
References surfaceFieldValue::getFieldValues(), and sf().
getFieldValues() [1/2]
tmp<Field<Type> > getFieldValues (const word & fieldName, const bool mustGet = false, const bool applyOrientation = false) const protected
Return field values by looking up field name.
Referenced by surfaceFieldValue::validField().
processSameTypeValues()
Type processSameTypeValues (const Field< Type > & values, const vectorField & Sf, const scalarField & weightField) const protected
Apply the 'operation' to the values. Operation has to.
preserve Type.
Definition at line 130 of file surfaceFieldValueTemplates.C.
References Foam::cmptMag(), Foam::component(), Field< Type >::component(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), Foam::max(), Foam::min(), surfaceFieldValue::processValues(), Foam::setComponent(), List< T >::size(), List< Type >::size(), Foam::sqr(), Foam::sqrt(), Foam::sum(), and Foam::Zero.
Referenced by surfaceFieldValue::getFieldValues().
processValues() [1/5]
Type processValues (const Field< Type > & values, const vectorField & Sf, const scalarField & weightField) const protected
Apply the 'operation' to the values. Wrapper around.
processSameTypeValues. See also template specialisation below.
Definition at line 259 of file surfaceFieldValueTemplates.C.
References surfaceFieldValue::writeValues().
Referenced by surfaceFieldValue::processSameTypeValues(), surfaceFieldValue::processValues(), and surfaceFieldValue::writeFileHeader().
writeFileHeader()
void writeFileHeader (const label i) protected virtual
Output file header information.
Implements logFiles.
Definition at line 538 of file surfaceFieldValue.C.
References Foam::endl(), forAll, surfaceFieldValue::processValues(), and Foam::tab.
Referenced by surfaceFieldValue::initialise().
TypeName()
TypeName ("surfaceFieldValue")
Run-time type information.
regionType()
const Foam::functionObjects::fieldValues::surfaceFieldValue::regionTypes & regionType () const inline
Return the region type.
Definition at line 31 of file surfaceFieldValueI.H.
References surfaceFieldValue::regionType_.
faceId()
const Foam::labelList & faceId () const inline
Return the local list of face IDs.
Definition at line 38 of file surfaceFieldValueI.H.
References surfaceFieldValue::faceId_.
facePatch()
const Foam::labelList & facePatch () const inline
Return the local list of patch ID per face.
Definition at line 45 of file surfaceFieldValueI.H.
References surfaceFieldValue::facePatchId_.
faceSign()
const Foam::labelList & faceSign () const inline
Return the list of +1/-1 representing face flip map.
Definition at line 52 of file surfaceFieldValueI.H.
References surfaceFieldValue::faceSign_.
outputDir()
Foam::fileName outputDir () const inline
Return the output directory.
Definition at line 59 of file surfaceFieldValueI.H.
References writeFile::baseFileDir(), functionObject::name(), regionFunctionObject::obr_, objectRegistry::time(), and Time::timeName().
writeValues()
bool writeValues (const word & fieldName, const scalarField & weightField, const bool orient)
Templated helper function to output field values.
Definition at line 274 of file surfaceFieldValueTemplates.C.
References Foam::endl(), surfaceFieldValue::filterField(), Log, points, and Foam::tab.
Referenced by surfaceFieldValue::processValues().
filterField() [1/4]
tmp<Field<Type> > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field, const bool applyOrientation) const
Filter a surface field according to faceIds.
Referenced by surfaceFieldValue::filterField(), and surfaceFieldValue::writeValues().
filterField() [2/4]
tmp<Field<Type> > filterField (const GeometricField< Type, fvPatchField, volMesh > & field, const bool applyOrientation) const
Filter a volume field according to faceIds.
read()
bool read (const dictionary & dict) virtual
Read from dictionary.
Reimplemented from fieldValue.
Definition at line 707 of file surfaceFieldValue.C.
References fieldValue::read().
Referenced by surfaceFieldValue::~surfaceFieldValue().
write()
bool write () virtual
Calculate and write.
Reimplemented from fieldValue.
Definition at line 718 of file surfaceFieldValue.C.
References Foam::endl(), forAll, Log, UPstream::master(), points, Foam::tab, WarningInFunction, and fieldValue::write().
processValues() [2/5]
Foam::scalar processValues (const Field< scalar > & values, const vectorField & Sf, const scalarField & weightField) const
Definition at line 572 of file surfaceFieldValue.C.
References Foam::mag(), n, Foam::neg(), Foam::pos(), surfaceFieldValue::processValues(), and Foam::sum().
processValues() [3/5]
Foam::vector processValues (const Field< vector > & values, const vectorField & Sf, const scalarField & weightField) const
Definition at line 604 of file surfaceFieldValue.C.
References Foam::mag(), n, Foam::pos(), Foam::sum(), and surfaceFieldValue::surfaceFieldValue().
processValues() [4/5]
scalar processValues (const Field< scalar > & values, const vectorField & Sf, const scalarField & weightField) const
Specialisation for scalar.
processValues() [5/5]
vector processValues (const Field< vector > & values, const vectorField & Sf, const scalarField & weightField) const
Specialisation for vector.
getFieldValues() [2/2]
Foam::tmp<Foam::Field<Type> > getFieldValues (const word & fieldName, const bool mustGet, const bool applyOrientation) const
Definition at line 60 of file surfaceFieldValueTemplates.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, fld(), forAll, Foam::MULES::interpolate(), surfaceFieldValue::processSameTypeValues(), tmp< T >::ref(), sf(), List< T >::size(), and Foam::Zero.
filterField() [3/4]
Foam::tmp<Foam::Field<Type> > filterField (const GeometricField< Type, fvPatchField, volMesh > & field, const bool applyOrientation) const
Definition at line 360 of file surfaceFieldValueTemplates.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::FatalError, FatalErrorInFunction, surfaceFieldValue::filterField(), forAll, Foam::name(), IOobject::name(), Foam::nl, patchi, tmp< T >::ref(), and Foam::type().
filterField() [4/4]
Foam::tmp<Foam::Field<Type> > filterField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field, const bool applyOrientation) const
Definition at line 402 of file surfaceFieldValueTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, patchi, and tmp< T >::ref().
Member Data Documentation
regionTypeNames_
const Foam::NamedEnum< Foam::functionObjects::fieldValues::surfaceFieldValue::regionTypes, 3 > regionTypeNames_ static
region type names
Definition at line 345 of file surfaceFieldValue.H.
Referenced by NamedEnum< directionType, 3 >::names().
operationTypeNames_
const Foam::NamedEnum< Foam::functionObjects::fieldValues::surfaceFieldValue::operationType, 15 > operationTypeNames_ static
Operation type names.
Definition at line 369 of file surfaceFieldValue.H.
Referenced by NamedEnum< directionType, 3 >::names().
surfaceWriterPtr_
autoPtr<surfaceWriter> surfaceWriterPtr_ protected
Surface writer.
Definition at line 408 of file surfaceFieldValue.H.
regionType_
regionTypes regionType_ protected
region type
Definition at line 411 of file surfaceFieldValue.H.
Referenced by surfaceFieldValue::regionType().
operation_
operationType operation_ protected
Operation to apply to values.
Definition at line 414 of file surfaceFieldValue.H.
weightFieldName_
word weightFieldName_ protected
Weight field name - optional.
Definition at line 417 of file surfaceFieldValue.H.
orientWeightField_
bool orientWeightField_ protected
Flag to indicate if flipMap should be applied to the weight field.
Definition at line 420 of file surfaceFieldValue.H.
orientedFieldsStart_
label orientedFieldsStart_ protected
Start index of fields that require application of flipMap.
Definition at line 423 of file surfaceFieldValue.H.
scaleFactor_
scalar scaleFactor_ protected
Scale factor - optional.
Definition at line 426 of file surfaceFieldValue.H.
totalArea_
scalar totalArea_ protected
Total area of the surfaceFieldValue.
Definition at line 429 of file surfaceFieldValue.H.
writeArea_
bool writeArea_ protected
Optionally write the area of the surfaceFieldValue.
Definition at line 432 of file surfaceFieldValue.H.
nFaces_
label nFaces_ protected
Global number of faces.
Definition at line 435 of file surfaceFieldValue.H.
faceId_
labelList faceId_ protected
Local list of face IDs.
Definition at line 441 of file surfaceFieldValue.H.
Referenced by surfaceFieldValue::faceId().
facePatchId_
labelList facePatchId_ protected
Local list of patch ID per face.
Definition at line 444 of file surfaceFieldValue.H.
Referenced by surfaceFieldValue::facePatch().
faceSign_
labelList faceSign_ protected
List of +1/-1 representing face flip map.
(1 use as is, -1 negate)
Definition at line 448 of file surfaceFieldValue.H.
Referenced by surfaceFieldValue::faceSign().
surfacePtr_
autoPtr<sampledSurface> surfacePtr_ protected
Underlying sampledSurface.
Definition at line 454 of file surfaceFieldValue.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldValues/surfaceFieldValue/surfaceFieldValue.H
src/functionObjects/field/fieldValues/surfaceFieldValue/surfaceFieldValue.C
src/functionObjects/field/fieldValues/surfaceFieldValue/surfaceFieldValueI.H
src/functionObjects/field/fieldValues/surfaceFieldValue/surfaceFieldValueTemplates.C