OpenFOAM: fieldAverageItem Class Reference
fieldAverageItem Class Reference
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the form:
Public Types
enum baseType { ITER, TIME }
Enumeration defining the averaging base type.
Public Member Functions
fieldAverageItem ()
Construct null.
fieldAverageItem (Istream &)
Construct from Istream.
fieldAverageItem (const fieldAverageItem &)
Construct as copy.
~fieldAverageItem ()
Destructor.
const word & fieldName () const
Return const access to the field name.
const Switch & mean () const
Return const access to the mean flag.
Switch & mean ()
Return non-const access to the mean flag.
const word & meanFieldName () const
Return const access to the mean field name.
const Switch & prime2Mean () const
Return const access to the prime-squared mean flag.
Switch & prime2Mean ()
Return non-const access to the prime-squared mean flag.
const word & prime2MeanFieldName () const
Return const access to the prime-squared mean field name.
const word base () const
Return averaging base type name.
Switch iterBase () const
Return true if base is ITER.
Switch timeBase () const
Return true if base is time.
scalar window () const
const word & windowName () const
void operator= (const fieldAverageItem &)
Static Public Attributes
static const word EXT_MEAN
Mean average.
static const word EXT_PRIME2MEAN
Prime-squared average.
Friends
bool operator== (const fieldAverageItem &a, const fieldAverageItem &b)
bool operator!= (const fieldAverageItem &a, const fieldAverageItem &b)
Istream & operator>> (Istream &, fieldAverageItem &)
Ostream & operator<< (Ostream &, const fieldAverageItem &)
Detailed Description
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the form:
{
    mean            on;
    prime2Mean      on;
    base            time; // iteration
    window          200;  // optional averaging window
    windowName      w1;   // optional window name (default = "")
}
The averaging window corresponds to the averaging interval (iters or time) If not specified, the averaging is over 'all iters/time'
Source files
fieldAverageItem.H
fieldAverageItem.C
fieldAverageItemIO.C
Definition at line 76 of file fieldAverageItem.H.
Member Enumeration Documentation
baseType
enum baseType
Enumeration defining the averaging base type.
Enumerator
ITER
TIME
Definition at line 91 of file fieldAverageItem.H.
Constructor & Destructor Documentation
fieldAverageItem() [1/3]
fieldAverageItem ()
Construct null.
Definition at line 56 of file fieldAverageItem.C.
fieldAverageItem() [2/3]
fieldAverageItem (Istream & is)
Construct from Istream.
Definition at line 32 of file fieldAverageItemIO.C.
References IOstream::check(), fieldAverageItem::EXT_MEAN, fieldAverageItem::EXT_PRIME2MEAN, entry::keyword(), dictionary::lookup(), dictionary::lookupOrDefault(), and dictionary::null.
fieldAverageItem() [3/3]
fieldAverageItem (const fieldAverageItem & faItem)
Construct as copy.
Definition at line 70 of file fieldAverageItem.C.
~fieldAverageItem()
~fieldAverageItem ()
Destructor.
Definition at line 87 of file fieldAverageItem.C.
Member Function Documentation
fieldName()
const word& fieldName () const inline
Return const access to the field name.
Definition at line 153 of file fieldAverageItem.H.
mean() [1/2]
const Switch& mean () const inline
Return const access to the mean flag.
Definition at line 159 of file fieldAverageItem.H.
mean() [2/2]
Switch& mean () inline
Return non-const access to the mean flag.
Definition at line 165 of file fieldAverageItem.H.
meanFieldName()
const word& meanFieldName () const inline
Return const access to the mean field name.
Definition at line 171 of file fieldAverageItem.H.
prime2Mean() [1/2]
const Switch& prime2Mean () const inline
Return const access to the prime-squared mean flag.
Definition at line 177 of file fieldAverageItem.H.
prime2Mean() [2/2]
Switch& prime2Mean () inline
Return non-const access to the prime-squared mean flag.
Definition at line 183 of file fieldAverageItem.H.
prime2MeanFieldName()
const word& prime2MeanFieldName () const inline
Return const access to the prime-squared mean field name.
Definition at line 189 of file fieldAverageItem.H.
base()
const word base () const inline
Return averaging base type name.
Definition at line 195 of file fieldAverageItem.H.
iterBase()
Switch iterBase () const inline
Return true if base is ITER.
Definition at line 201 of file fieldAverageItem.H.
References fieldAverageItem::ITER.
timeBase()
Switch timeBase () const inline
Return true if base is time.
Definition at line 207 of file fieldAverageItem.H.
References fieldAverageItem::TIME.
window()
scalar window () const inline
Definition at line 212 of file fieldAverageItem.H.
windowName()
const word& windowName () const inline
Definition at line 217 of file fieldAverageItem.H.
References fieldAverageItem::operator=().
operator=()
void operator= (const fieldAverageItem & rhs)
Definition at line 94 of file fieldAverageItem.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by fieldAverageItem::windowName().
Friends And Related Function Documentation
operator==
bool operator== (const fieldAverageItem & a, const fieldAverageItem & b) friend
Definition at line 231 of file fieldAverageItem.H.
operator!=
bool operator!= (const fieldAverageItem & a, const fieldAverageItem & b) friend
Definition at line 248 of file fieldAverageItem.H.
operator>>
Istream& operator>> (Istream & , fieldAverageItem &) friend
operator<<
Ostream& operator<< (Ostream & , const fieldAverageItem &) friend
Member Data Documentation
EXT_MEAN
const Foam::word EXT_MEAN static
Mean average.
Definition at line 85 of file fieldAverageItem.H.
Referenced by fieldAverageItem::fieldAverageItem(), and Foam::functionObjects::operator>>().
EXT_PRIME2MEAN
const Foam::word EXT_PRIME2MEAN static
Prime-squared average.
Definition at line 88 of file fieldAverageItem.H.
Referenced by fieldAverageItem::fieldAverageItem(), and Foam::functionObjects::operator>>().
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItem.H
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItem.C
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItemIO.C