OpenFOAM: regionSizeDistribution Class Reference
regionSizeDistribution Class Reference
FunctionObjects » Field function objects
Creates a size distribution via interrogating a continuous phase fraction field.
Public Member Functions
TypeName ("regionSizeDistribution")
Runtime type information.
regionSizeDistribution (const word &name, const Time &runTime, const dictionary &)
Construct for given objectRegistry and dictionary.
virtual ~regionSizeDistribution ()
virtual bool read (const dictionary &)
Read the regionSizeDistribution data.
virtual bool execute ()
Do nothing.
virtual bool write ()
Calculate the regionSizeDistribution and write.
template<class Type >
Foam::Map< Type > regionSum (const regionSplit &regions, const Field< Type > &fld) const
template<class Type >
Foam::List< Type > extractData (const UList< label > &keys, const Map< Type > &regionData) const
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Detailed Description
Creates a size distribution via interrogating a continuous phase fraction field.
Looks up a phase-fraction (alpha) field and splits the mesh into regions based on where the field is below the threshold value. These regions ("droplets") can now be analysed.
Regions:
print the regions connected to a user-defined set of patches. (in spray calculation these form the liquid core)
print the regions with too large volume. These are the 'background' regions.
(debug) write regions as a volScalarField
(debug) print for all regions the sum of volume and alpha*volume
Output (volume scalar) fields include:
alpha_liquidCore : alpha with outside liquid core set to 0
alpha_background : alpha with outside background set to 0.
Histogram:
determine histogram of diameter (given minDiameter, maxDiameter, nBins)
write graph of number of droplets per bin
write graph of sum, average and deviation of droplet volume per bin
write graph of sum, average and deviation of user-defined fields. For volVectorFields these are those of the 3 components and the magnitude.
Example of function object specification:
regionSizeDistribution1
{
    type            regionSizeDistribution;
    libs            ("libfieldFunctionObjects.so");
    ...
    field           alpha;
    patches         (inlet);
    threshold       0.4;
    fields          (p U);
    nBins           100;
    maxDiameter     0.5e-4;
    minDiameter     0;
    setFormat       gnuplot;
    coordinateSystem
    {
        type            cartesian;
        origin          (0 0 0);
        e3              (0 1 1);
        e1              (1 0 0);
    }
}
Usage
Property Description Required Default value
type type name: regionSizeDistribution yes
field phase field to interrogate yes
patches patches from which the liquid core is identified yes
threshold phase fraction applied to delimit regions yes
fields fields to sample yes
nBins number of bins for histogram yes
maxDiameter maximum region equivalent diameter yes
minDiameter minimum region equivalent diameter no 0
setFormat writing format yes
coordinateSystem transformation for vector fields no
See also
Foam::functionObject Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::writeFile
Source files
regionSizeDistribution.H
regionSizeDistribution.C
Definition at line 187 of file regionSizeDistribution.H.
Constructor & Destructor Documentation
regionSizeDistribution()
regionSizeDistribution (const word & name, const Time & runTime, const dictionary & dict)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 326 of file regionSizeDistribution.C.
References Foam::read().
~regionSizeDistribution()
~regionSizeDistribution () virtual
Definition at line 343 of file regionSizeDistribution.C.
Member Function Documentation
TypeName()
TypeName ("regionSizeDistribution")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the regionSizeDistribution data.
Reimplemented from regionFunctionObject.
Definition at line 349 of file regionSizeDistribution.C.
References Foam::endl(), format(), dictionary::found(), Foam::Info, dictionary::lookup(), writer< Type >::New(), and dictionary::readIfPresent().
execute()
bool execute () virtual
Do nothing.
Implements functionObject.
Definition at line 375 of file regionSizeDistribution.C.
write()
bool write () virtual
Calculate the regionSizeDistribution and write.
Implements functionObject.
Definition at line 381 of file regionSizeDistribution.C.
References alphaPtr, HashTable< T, Key, Hash >::begin(), HashTable< T, label, Hash< label > >::begin(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::cbrt(), Field< Type >::component(), VectorSpace< Vector< scalar >, scalar, 3 >::componentNames, fvPatchField< Type >::coupled(), delta, Foam::dimless, Foam::fvc::domainIntegrate(), HashTableCore::end(), Foam::endl(), HashTable< T, label, Hash< label > >::erase(), HashTable< T, Key, Hash >::erase(), Foam::findStrings(), fld(), forAll, forAllConstIter(), forAllIter, HashTable< T, Key, Hash >::found(), Foam::gSum(), Foam::Info, HashTable< T, Key, Hash >::iteratorBase::key(), Foam::mag(), UPstream::master(), IOobject::MUST_READ, Foam::name(), IOobject::name(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, regionSplit::nRegions(), fvPatch::patch(), fvPatchField< Type >::patch(), patchi, fvPatchField< Type >::patchInternalField(), fvPatchField< Type >::patchNeighbourField(), Foam::constant::mathematical::pi(), Foam::pow(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), autoPtr< T >::reset(), List< T >::size(), HashTable< T, label, Hash< label > >::sortedToc(), polyPatch::start(), token::TAB, Foam::type(), Field< Type >::typeName, autoPtr< T >::valid(), regIOobject::write(), and x.
regionSum()
Foam::Map<Type> regionSum (const regionSplit & regions, const Field< Type > & fld) const
Definition at line 34 of file regionSizeDistributionTemplates.C.
References forAll, and regionSplit::nRegions().
extractData()
Foam::List<Type> extractData (const UList< label > & keys, const Map< Type > & regionData) const
Definition at line 65 of file regionSizeDistributionTemplates.C.
References forAll, and UList< T >::size().
The documentation for this class was generated from the following files:
src/functionObjects/field/regionSizeDistribution/regionSizeDistribution.H
src/functionObjects/field/regionSizeDistribution/regionSizeDistribution.C
src/functionObjects/field/regionSizeDistribution/regionSizeDistributionTemplates.C