OpenFOAM: surfaceInterpolate Class Reference
surfaceInterpolate Class Reference
Public Member Functions
TypeName ("surfaceInterpolate")
Runtime type information.
surfaceInterpolate (const word &name, const Time &runTime, const dictionary &dict)
Construct for given objectRegistry and dictionary.
virtual ~surfaceInterpolate ()
Destructor.
virtual bool read (const dictionary &)
Read the controls.
virtual bool execute ()
Calculate the interpolated fields.
virtual bool write ()
Write the interpolated fields.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
template<class Type >
void interpolateFields (PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &) const
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
List< Tuple2< word, word > > fieldSet_
Fields to process.
PtrList< surfaceScalarField > ssf_
Locally constructed fields.
PtrList< surfaceVectorField > svf_
PtrList< surfaceSphericalTensorField > sSpheretf_
PtrList< surfaceSymmTensorField > sSymmtf_
PtrList< surfaceTensorField > stf_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Definition at line 106 of file surfaceInterpolate.H.
Constructor & Destructor Documentation
surfaceInterpolate()
surfaceInterpolate (const word & name, const Time & runTime, const dictionary & dict)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 51 of file surfaceInterpolate.C.
References Foam::read().
~surfaceInterpolate()
~surfaceInterpolate () virtual
Destructor.
Definition at line 66 of file surfaceInterpolate.C.
References surfaceInterpolate::read().
Member Function Documentation
interpolateFields()
void interpolateFields (PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> & sflds) const protected
Definition at line 34 of file surfaceInterpolateTemplates.C.
References Foam::endl(), fld(), forAll, forAllConstIter(), Foam::Info, and Foam::linearInterpolate().
TypeName()
TypeName ("surfaceInterpolate")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the controls.
Reimplemented from regionFunctionObject.
Definition at line 73 of file surfaceInterpolate.C.
References dictionary::lookup().
Referenced by surfaceInterpolate::~surfaceInterpolate().
execute()
bool execute () virtual
Calculate the interpolated fields.
Implements functionObject.
Definition at line 83 of file surfaceInterpolate.C.
References Foam::endl(), Foam::Info, Foam::name(), Foam::nl, and Foam::type().
write()
bool write () virtual
Write the interpolated fields.
Implements functionObject.
Definition at line 106 of file surfaceInterpolate.C.
References Foam::endl(), forAll, Foam::Info, Foam::name(), Foam::nl, and Foam::type().
Member Data Documentation
fieldSet_
List<Tuple2<word, word> > fieldSet_ protected
Fields to process.
Definition at line 115 of file surfaceInterpolate.H.
ssf_
PtrList<surfaceScalarField> ssf_ protected
Locally constructed fields.
Definition at line 118 of file surfaceInterpolate.H.
svf_
PtrList<surfaceVectorField> svf_ protected
Definition at line 119 of file surfaceInterpolate.H.
sSpheretf_
PtrList<surfaceSphericalTensorField> sSpheretf_ protected
Definition at line 120 of file surfaceInterpolate.H.
sSymmtf_
PtrList<surfaceSymmTensorField> sSymmtf_ protected
Definition at line 121 of file surfaceInterpolate.H.
stf_
PtrList<surfaceTensorField> stf_ protected
Definition at line 122 of file surfaceInterpolate.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/surfaceInterpolate/surfaceInterpolate.H
src/functionObjects/field/surfaceInterpolate/surfaceInterpolate.C
src/functionObjects/field/surfaceInterpolate/surfaceInterpolateTemplates.C