OpenFOAM: turbulenceFields Class Reference
turbulenceFields Class Reference
FunctionObjects » Field function objects
Stores turbulence fields on the mesh database for further manipulation.
Public Types
enum compressibleField {
cfK, cfEpsilon, cfOmega, cfMut,
cfMuEff, cfAlphat, cfAlphaEff, cfR,
cfDevRhoReff
}
enum incompressibleField {
ifK, ifEpsilon, ifOmega, ifNut,
ifNuEff, ifR, ifDevReff
}
Public Member Functions
TypeName ("turbulenceFields")
Runtime type information.
turbulenceFields (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~turbulenceFields ()
Destructor.
virtual bool read (const dictionary &)
Read the controls.
virtual bool execute ()
Calculate turbulence fields.
virtual bool write ()
Do nothing.
template<class Model >
Foam::tmp< Foam::volScalarField > omega (const Model &model) const
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Static Public Attributes
static const NamedEnum< compressibleField, 9 > compressibleFieldNames_
static const NamedEnum< incompressibleField, 7 > incompressibleFieldNames_
static const word modelName
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Protected Member Functions
bool compressible ()
Return true if compressible turbulence model is identified.
template<class Type >
void processField (const word &fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvalue)
Process the turbulence field.
template<class Model >
tmp< volScalarField > omega (const Model &model) const
Return omega calculated from k and epsilon.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
wordHashSet fieldSet_
Fields to load.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Detailed Description
Stores turbulence fields on the mesh database for further manipulation.
Fields are stored as copies of the original, with the prefix "tubulenceModel:", e.g.:
turbulenceModel:R
Example of function object specification:
turbulenceFields1
{
    type        turbulenceFields;
    libs        ("libfieldFunctionObjects.so");
    ...
    fields
    (
        R
        devRhoReff
    );
}
Usage
Property Description Required Default value
type type name: processorField yes
fields fields to store (see below) yes
Where fields can include:
k : turbulence kinetic energy
epsilon : turbulence kinetic energy dissipation rate
omega : turbulence specific dissipation rate
nut : turbulence viscosity (incompressible)
nuEff : effective turbulence viscosity (incompressible)
mut : turbulence viscosity (compressible)
muEff : effective turbulence viscosity (compressible)
alphat : turbulence thermal diffusivity (compressible)
alphaEff : effective turbulence thermal diffusivity (compressible)
R : Reynolds stress tensor
devReff : Deviatoric part of the effective Reynolds stress
devRhoReff : Divergence of the Reynolds stress
See also
Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::timeControl
Source files
turbulenceFields.H
turbulenceFields.C
Definition at line 168 of file turbulenceFields.H.
Member Enumeration Documentation
compressibleField
enum compressibleField
Enumerator
cfK
cfEpsilon
cfOmega
cfMut
cfMuEff
cfAlphat
cfAlphaEff
cfR
cfDevRhoReff
Definition at line 174 of file turbulenceFields.H.
incompressibleField
enum incompressibleField
Enumerator
ifK
ifEpsilon
ifOmega
ifNut
ifNuEff
ifR
ifDevReff
Definition at line 188 of file turbulenceFields.H.
Constructor & Destructor Documentation
turbulenceFields()
turbulenceFields (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 126 of file turbulenceFields.C.
References Foam::read().
~turbulenceFields()
~turbulenceFields () virtual
Destructor.
Definition at line 141 of file turbulenceFields.C.
Member Function Documentation
compressible()
bool compressible () protected
Return true if compressible turbulence model is identified.
Definition at line 102 of file turbulenceFields.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
processField()
void processField (const word & fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvalue) protected
Process the turbulence field.
Definition at line 32 of file turbulenceFieldsTemplates.C.
References Foam::endl(), fld(), Foam::nl, turbulenceFields::omega(), and WarningInFunction.
omega() [1/2]
tmp<volScalarField> omega (const Model & model) const protected
Return omega calculated from k and epsilon.
Referenced by turbulenceFields::processField().
TypeName()
TypeName ("turbulenceFields")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the controls.
Reimplemented from regionFunctionObject.
Definition at line 147 of file turbulenceFields.C.
References Foam::endl(), forAllConstIter(), dictionary::found(), Foam::Info, dictionary::lookup(), Foam::name(), Foam::nl, and Foam::type().
execute()
bool execute () virtual
Calculate turbulence fields.
Implements functionObject.
Definition at line 177 of file turbulenceFields.C.
References Foam::abort(), ThermalDiffusivity< BasicTurbulenceModel >::alphaEff(), ThermalDiffusivity< BasicTurbulenceModel >::alphat(), compressible, IncompressibleTurbulenceModel< TransportModel >::devReff(), turbulenceModel::epsilon(), f(), Foam::FatalError, FatalErrorInFunction, forAllConstIter(), turbulenceModel::k(), turbulenceModel::nuEff(), turbulenceModel::nut(), and turbulenceModel::R().
write()
bool write () virtual
Do nothing.
The turbulence fields are registered and written automatically
Implements functionObject.
Definition at line 302 of file turbulenceFields.C.
References forAllConstIter().
omega() [2/2]
Foam::tmp<Foam::volScalarField> omega (const Model & model) const
Definition at line 78 of file turbulenceFieldsTemplates.C.
References epsilon, and k.
Member Data Documentation
compressibleFieldNames_
const Foam::NamedEnum< Foam::functionObjects::turbulenceFields::compressibleField, 9 > compressibleFieldNames_ static
Definition at line 186 of file turbulenceFields.H.
Referenced by NamedEnum< directionType, 3 >::names().
incompressibleFieldNames_
const Foam::NamedEnum< Foam::functionObjects::turbulenceFields::incompressibleField, 7 > incompressibleFieldNames_ static
Definition at line 198 of file turbulenceFields.H.
Referenced by NamedEnum< directionType, 3 >::names().
modelName
const Foam::word modelName static
Definition at line 200 of file turbulenceFields.H.
Referenced by NamedEnum< directionType, 3 >::names().
fieldSet_
wordHashSet fieldSet_ protected
Fields to load.
Definition at line 208 of file turbulenceFields.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/turbulenceFields/turbulenceFields.H
src/functionObjects/field/turbulenceFields/turbulenceFields.C
src/functionObjects/field/turbulenceFields/turbulenceFieldsTemplates.C