OpenFOAM: nearWallFields Class Reference
nearWallFields Class Reference
FunctionObjects » Field function objects
Samples near-patch volume fields.
Public Member Functions
TypeName ("nearWallFields")
Runtime type information.
nearWallFields (const word &name, const Time &runTime, const dictionary &dict)
Construct for given objectRegistry and dictionary.
virtual ~nearWallFields ()
Destructor.
virtual bool read (const dictionary &)
Read the controls.
virtual bool execute ()
Calculate the near-wall fields.
virtual bool write ()
Write the near-wall fields.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
void calcAddressing ()
Calculate addressing from cells back to patch faces.
template<class Type >
void createFields (PtrList< GeometricField< Type, fvPatchField, volMesh >> &) const
template<class Type >
void sampleBoundaryField (const interpolationCellPoint< Type > &interpolator, GeometricField< Type, fvPatchField, volMesh > &fld) const
Override boundary fields with sampled values.
template<class Type >
void sampleFields (PtrList< GeometricField< Type, fvPatchField, volMesh >> &) const
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes
List< Tuple2< word, word > > fieldSet_
Fields to process.
labelHashSet patchSet_
Patches to sample.
scalar distance_
Distance away from wall.
HashTable< word > fieldMap_
From original field to sampled result.
HashTable< word > reverseFieldMap_
From resulting back to original field.
labelListList cellToWalls_
From cell to seed patch faces.
List< List< point > > cellToSamples_
From cell to tracked end point.
autoPtr< mapDistribute > getPatchDataMapPtr_
Map from cell based data back to patch based data.
PtrList< volScalarField > vsf_
PtrList< volVectorField > vvf_
PtrList< volSphericalTensorField > vSpheretf_
PtrList< volSymmTensorField > vSymmtf_
PtrList< volTensorField > vtf_
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Samples near-patch volume fields.
Fields are stored
every time step the field is updated with new values
at output it writes the fields
This functionObject can either be used
to calculate a new field as a post-processing step or
since the fields are registered, used in another functionObject
Example of function object specification:
nearWallFields1
{
    type        nearWallFields;
    libs        ("libfieldFunctionObjects.so");
    writeControl writeTime;
    fields
    (
        (p pNear)
        (U UNear)
    );
    patches     (movingWall);
    distance    0.13;
}
Usage
Property Description Required Default value
type type name: nearWallFields yes
fields list of fields with correspoding output field names yes
patches list of patches to sample yes
distance distance from patch to sample yes
See also
Foam::functionObjects::fvMeshFunctionObject
Source files
nearWallFields.H
nearWallFields.C
Definition at line 122 of file nearWallFields.H.
Constructor & Destructor Documentation
nearWallFields()
nearWallFields (const word & name, const Time & runTime, const dictionary & dict)
Construct for given objectRegistry and dictionary.
Allow the possibility to load fields from files
Definition at line 227 of file nearWallFields.C.
References Foam::read().
~nearWallFields()
~nearWallFields () virtual
Destructor.
Definition at line 242 of file nearWallFields.C.
References DebugInFunction, and Foam::endl().
Member Function Documentation
calcAddressing()
void calcAddressing () protected
Calculate addressing from cells back to patch faces.
Definition at line 47 of file nearWallFields.C.
References Cloud< ParticleType >::addParticle(), DebugInFunction, cloud::defaultName, findCellParticle::end(), Foam::endl(), polyMesh::FACE_DIAG_TRIS, polyPatch::faceCellCentres(), mappedPatchBase::facePoint(), forAll, forAllConstIter(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), InfoInFunction, Cloud< ParticleType >::move(), fvPatch::nf(), fvPatch::patch(), patchi, particle< Type >::position(), List< T >::setSize(), globalIndex::size(), fvPatch::start(), and globalIndex::toGlobal().
createFields()
void createFields (PtrList< GeometricField< Type, fvPatchField, volMesh >> & sflds) const protected
Definition at line 32 of file nearWallFieldsTemplates.C.
References Foam::endl(), fld(), forAllConstIter(), Log, IOobject::readOpt(), IOobject::rename(), nearWallFields::sampleBoundaryField(), and IOobject::writeOpt().
sampleBoundaryField()
void sampleBoundaryField (const interpolationCellPoint< Type > & interpolator, GeometricField< Type, fvPatchField, volMesh > & fld) const protected
Override boundary fields with sampled values.
Definition at line 76 of file nearWallFieldsTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, forAllConstIter(), interpolationCellPoint< Type >::interpolate(), patchi, nearWallFields::sampleFields(), and List< Type >::size().
Referenced by nearWallFields::createFields().
sampleFields()
void sampleFields (PtrList< GeometricField< Type, fvPatchField, volMesh >> & sflds) const protected
Definition at line 126 of file nearWallFieldsTemplates.C.
References fld(), and forAll.
Referenced by nearWallFields::sampleBoundaryField().
TypeName()
TypeName ("nearWallFields")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the controls.
Reimplemented from regionFunctionObject.
Definition at line 250 of file nearWallFields.C.
References Foam::endl(), forAll, Log, dictionary::lookup(), Foam::name(), regionFunctionObject::read(), Foam::readScalar(), and Foam::type().
execute()
bool execute () virtual
Calculate the near-wall fields.
Implements functionObject.
Definition at line 294 of file nearWallFields.C.
References DebugInFunction, Foam::endl(), Log, Foam::name(), Foam::nl, and Foam::type().
write()
bool write () virtual
Write the near-wall fields.
Implements functionObject.
Definition at line 335 of file nearWallFields.C.
References DebugInFunction, Foam::endl(), forAll, and Log.
Member Data Documentation
fieldSet_
List<Tuple2<word, word> > fieldSet_ protected
Fields to process.
Definition at line 133 of file nearWallFields.H.
patchSet_
labelHashSet patchSet_ protected
Patches to sample.
Definition at line 136 of file nearWallFields.H.
distance_
scalar distance_ protected
Distance away from wall.
Definition at line 139 of file nearWallFields.H.
fieldMap_
HashTable<word> fieldMap_ protected
From original field to sampled result.
Definition at line 142 of file nearWallFields.H.
reverseFieldMap_
HashTable<word> reverseFieldMap_ protected
From resulting back to original field.
Definition at line 145 of file nearWallFields.H.
cellToWalls_
labelListList cellToWalls_ protected
From cell to seed patch faces.
Definition at line 151 of file nearWallFields.H.
cellToSamples_
List<List<point> > cellToSamples_ protected
From cell to tracked end point.
Definition at line 154 of file nearWallFields.H.
getPatchDataMapPtr_
autoPtr<mapDistribute> getPatchDataMapPtr_ protected
Map from cell based data back to patch based data.
Definition at line 157 of file nearWallFields.H.
vsf_
PtrList<volScalarField> vsf_ protected
Definition at line 162 of file nearWallFields.H.
vvf_
PtrList<volVectorField> vvf_ protected
Definition at line 163 of file nearWallFields.H.
vSpheretf_
PtrList<volSphericalTensorField> vSpheretf_ protected
Definition at line 164 of file nearWallFields.H.
vSymmtf_
PtrList<volSymmTensorField> vSymmtf_ protected
Definition at line 165 of file nearWallFields.H.
vtf_
PtrList<volTensorField> vtf_ protected
Definition at line 166 of file nearWallFields.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/nearWallFields/nearWallFields.H
src/functionObjects/field/nearWallFields/nearWallFields.C
src/functionObjects/field/nearWallFields/nearWallFieldsTemplates.C