OpenFOAM: findCellParticle::trackingData Class Reference
findCellParticle::trackingData Class Reference
Class used to pass tracking data to the trackToFace function.
Public Member Functions
trackingData (Cloud< findCellParticle > &cloud, labelListList &cellToData, List< List< point >> &cellToEnd)
labelListList & cellToData ()
List< List< point > > & cellToEnd ()
Public Member Functions inherited from particle< Type >::TrackingData< Cloud< findCellParticle > >
TrackingData (Cloud< findCellParticle > &cloud)
Cloud< findCellParticle > & cloud ()
Return a reference to the cloud.
Additional Inherited Members
Public Types inherited from particle< Type >::TrackingData< Cloud< findCellParticle > >
typedef Cloud< findCellParticle > cloudType
Public Attributes inherited from particle< Type >::TrackingData< Cloud< findCellParticle > >
bool switchProcessor
Flag to switch processor.
bool keepParticle
Flag to indicate whether to keep particle (false = delete)
Detailed Description
Class used to pass tracking data to the trackToFace function.
Definition at line 77 of file findCellParticle.H.
Constructor & Destructor Documentation
trackingData()
trackingData (Cloud< findCellParticle > & cloud, labelListList & cellToData, List< List< point >> & cellToEnd) inline
Definition at line 89 of file findCellParticle.H.
Member Function Documentation
cellToData()
labelListList& cellToData () inline
Definition at line 103 of file findCellParticle.H.
Referenced by findCellParticle::move().
cellToEnd()
List<List<point> >& cellToEnd () inline
Definition at line 108 of file findCellParticle.H.
References findCellParticle::end(), findCellParticle::findCellParticle(), particle< Type >::mesh(), particle< Type >::position(), and particle< Type >::readFields().
Referenced by findCellParticle::move().
The documentation for this class was generated from the following file:
src/functionObjects/field/nearWallFields/findCellParticle.H