OpenFOAM: wallBoundedStreamLine Class Reference
wallBoundedStreamLine Class Reference
FunctionObjects » Field function objects
Generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
Public Member Functions
TypeName ("wallBoundedStreamLine")
Runtime type information.
wallBoundedStreamLine (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~wallBoundedStreamLine ()
Destructor.
virtual bool read (const dictionary &)
Read the field average data.
virtual bool execute ()
Do nothing.
virtual bool write ()
Calculate and write the wall-bounded streamlines.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for mesh point-motion.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Detailed Description
Generates streamline data by sampling a set of user-specified fields along a particle track, transported by a user-specified velocity field, constrained to a patch.
Example of function object specification:
wallBoundedStreamLine1
{
    type            wallBoundedStreamLine;
    libs            ("libfieldFunctionObjects.so");
    writeControl    writeTime;
    setFormat       vtk;
    U               UNear;
    trackForward    yes;
    fields
    (
        UNear
        p
    );
    lifeTime        10000;
    trackLength     1e-3;
    nSubCycle       5;
    cloudName       particleTracks;
    seedSampleSet   patchSeed;
    patchSeedCoeffs
    {
        type        patchSeed;
        patches     (wall);
        axis        x;
        maxPoints   20000;
    }
}
Usage
Property Description Required Default value
type Type name: wallBoundedStreamLine yes
setFormat Output data type yes
U Tracking velocity field name yes
fields Fields to sample yes
lifetime Maximum number of particle tracking steps yes
trackLength Tracking segment length no
nSubCycle Number of tracking steps per cell no
cloudName Cloud name to use yes
seedSampleSet Seeding method (see below) yes
Where seedSampleSet is typically one of
uniform : uniform particle seeding
cloud : cloud of points
patchSeed : seeding via patch faces
triSurfaceMeshPointSet : points according to a tri-surface mesh
Note
When specifying the track resolution, the trackLength OR nSubCycle option should be used
See also
Foam::fvMeshFunctionObject Foam::functionObjects::timeControl Foam::sampledSet Foam::streamLine
Source files
wallBoundedStreamLine.H
wallBoundedStreamLine.C
Definition at line 200 of file wallBoundedStreamLine.H.
Constructor & Destructor Documentation
wallBoundedStreamLine()
wallBoundedStreamLine (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 399 of file wallBoundedStreamLine.C.
References Foam::read().
~wallBoundedStreamLine()
~wallBoundedStreamLine () virtual
Destructor.
Definition at line 414 of file wallBoundedStreamLine.C.
Member Function Documentation
TypeName()
TypeName ("wallBoundedStreamLine")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the field average data.
Reimplemented from regionFunctionObject.
Definition at line 420 of file wallBoundedStreamLine.C.
References Foam::abort(), polyMeshTetDecomposition::checkFaceTets(), HashTable< T, Key, Hash >::clear(), dict, Foam::e, HashTableCore::end(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInFunction, HashTable< T, Key, Hash >::find(), Foam::findIndex(), forAll, forAllConstIter(), dictionary::found(), Foam::Info, HashTable< T, Key, Hash >::insert(), IOWarningInFunction, dictionary::lookup(), dictionary::lookupOrDefault(), polyMeshTetDecomposition::minTetQuality, Foam::name(), MeshObject< polyMesh, GeometricMeshObject, meshSearchMeshObject >::New(), writer< Type >::New(), sampledSet::New(), face::nextLabel(), Foam::nl, Foam::returnReduce(), dictionary::subDict(), Foam::type(), and WarningInFunction.
execute()
bool execute () virtual
Do nothing.
Implements functionObject.
Definition at line 575 of file wallBoundedStreamLine.C.
write()
bool write () virtual
Calculate and write the wall-bounded streamlines.
Implements functionObject.
Definition at line 581 of file wallBoundedStreamLine.C.
References polyMesh::defaultRegion, mapDistributeBase::distribute(), Foam::endl(), forAll, Foam::Info, UPstream::master(), Foam::mkDir(), n, fileName::name(), Foam::name(), Foam::nl, UPstream::nProcs(), UPstream::parRun(), fileName::path(), Time::path(), UPstream::scheduled, DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::setSize(), List< T >::size(), objectRegistry::time(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer(), wallBoundedStreamLine::updateMesh(), Ostream::write(), and List< T >::xfer().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Reimplemented from functionObject.
Definition at line 820 of file wallBoundedStreamLine.C.
References mapPolyMesh::mesh(), wallBoundedStreamLine::movePoints(), and Foam::read().
Referenced by wallBoundedStreamLine::write().
movePoints()
void movePoints (const polyMesh & mesh) virtual
Update for mesh point-motion.
Reimplemented from functionObject.
Definition at line 832 of file wallBoundedStreamLine.C.
References Foam::read().
Referenced by wallBoundedStreamLine::updateMesh().
The documentation for this class was generated from the following files:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLine.H
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLine.C