OpenFOAM: codedFunctionObject Class Reference
codedFunctionObject Class Reference
FunctionObjects » Utility function objects
Provides a general interface to enable dynamic code compilation.
Public Member Functions
TypeName ("coded")
Runtime type information.
codedFunctionObject (const word &name, const Time &time, const dictionary &dict)
Construct from Time and dictionary.
virtual ~codedFunctionObject ()
Destructor.
functionObject & redirectFunctionObject () const
Dynamically compiled functionObject.
virtual bool execute ()
Called at each ++ or += of the time-loop.
virtual bool write ()
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool read (const dictionary &)
Read and set the function object if its data have changed.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from codedBase
ClassName ("codedBase")
Runtime type information.
codedBase ()
Construct null.
virtual ~codedBase ()
Destructor.
Protected Member Functions
virtual dlLibraryTable & libs () const
Get the loaded dynamic libraries.
virtual void prepare (dynamicCode &, const dynamicCodeContext &) const
Adapt the context for the current object.
virtual string description () const
virtual void clearRedirect () const
virtual const dictionary & codeDict () const
Protected Member Functions inherited from codedBase
void updateLibrary (const word &name) const
Update library as required.
Protected Attributes
const Time & time_
Reference to the time database.
dictionary dict_
Input dictionary.
word name_
string codeData_
string codeRead_
string codeExecute_
string codeWrite_
string codeEnd_
autoPtr< functionObject > redirectFunctionObjectPtr_
Underlying functionObject.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Provides a general interface to enable dynamic code compilation.
The entries are codeInclude : include files codeOptions : include paths; inserted into EXE_INC in Make/options codeLibs : link line; inserted into LIB_LIBS in Make/options codeData : c++; local member data (null constructed); localCode : c++; local static functions codeRead : c++; upon functionObject::read(); codeExecute : c++;upon functionObject::execute(); codeWrite : c++; upon functionObject::write() codeEnd : c++; upon functionObject::end();
Example of function object specification:
difference
{
    libs        ("libutilityFunctionObjects.so");
    type coded;
    // Name of on-the-fly generated functionObject
    name writeMagU;
    codeWrite
    #{
        // Lookup U
        const volVectorField& U = mesh().lookupObject<volVectorField>("U");
        // Write
        mag(U).write();
    }
}
See also
Foam::functionObject Foam::codedBase
Source files
codedFunctionObject.H
codedFunctionObject.C
Definition at line 87 of file codedFunctionObject.H.
Constructor & Destructor Documentation
codedFunctionObject()
codedFunctionObject (const word & name, const Time & time, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 120 of file codedFunctionObject.C.
References Foam::read().
~codedFunctionObject()
~codedFunctionObject () virtual
Destructor.
Definition at line 140 of file codedFunctionObject.C.
Member Function Documentation
libs()
Foam::dlLibraryTable & libs () const protected virtual
Get the loaded dynamic libraries.
Implements codedBase.
Definition at line 93 of file codedFunctionObject.C.
prepare()
void prepare (dynamicCode & dynCode, const dynamicCodeContext & context) const protected virtual
Adapt the context for the current object.
Implements codedBase.
Definition at line 53 of file codedFunctionObject.C.
References dynamicCode::addCompileFile(), dynamicCode::addCopyFile(), dynamicCodeContext::libs(), dynamicCodeContext::options(), dynamicCode::setFilterVariable(), and dynamicCode::setMakeOptions().
description()
Foam::string description () const protected virtual
Implements codedBase.
Definition at line 99 of file codedFunctionObject.C.
References Foam::name().
clearRedirect()
void clearRedirect () const protected virtual
Implements codedBase.
Definition at line 105 of file codedFunctionObject.C.
codeDict()
const Foam::dictionary & codeDict () const protected virtual
Implements codedBase.
Definition at line 111 of file codedFunctionObject.C.
TypeName()
TypeName ("coded")
Runtime type information.
redirectFunctionObject()
Foam::functionObject & redirectFunctionObject () const
Dynamically compiled functionObject.
Definition at line 146 of file codedFunctionObject.C.
References functionObject::New(), and dictionary::set().
execute()
bool execute () virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual executeControl behaviour and forces execution (used in post-processing mode)
Implements functionObject.
Definition at line 164 of file codedFunctionObject.C.
write()
bool write () virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual writeControl behaviour and forces writing always (used in post-processing mode)
Implements functionObject.
Definition at line 171 of file codedFunctionObject.C.
end()
bool end () virtual
Called when Time::run() determines that the time-loop exits.
By default it simply calls execute().
Reimplemented from functionObject.
Definition at line 178 of file codedFunctionObject.C.
read()
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Reimplemented from functionObject.
Definition at line 185 of file codedFunctionObject.C.
References dynamicCodeContext::addLineDirective(), dictionary::found(), Foam::stringOps::inplaceExpand(), dictionary::lookup(), dictionary::lookupEntryPtr(), dictionaryName::name(), entry::startLineNumber(), entry::stream(), and Foam::stringOps::trim().
Member Data Documentation
time_
const Time& time_ protected
Reference to the time database.
Definition at line 97 of file codedFunctionObject.H.
dict_
dictionary dict_ protected
Input dictionary.
Definition at line 100 of file codedFunctionObject.H.
name_
word name_ protected
Definition at line 102 of file codedFunctionObject.H.
codeData_
string codeData_ protected
Definition at line 104 of file codedFunctionObject.H.
codeRead_
string codeRead_ protected
Definition at line 105 of file codedFunctionObject.H.
codeExecute_
string codeExecute_ protected
Definition at line 106 of file codedFunctionObject.H.
codeWrite_
string codeWrite_ protected
Definition at line 107 of file codedFunctionObject.H.
codeEnd_
string codeEnd_ protected
Definition at line 108 of file codedFunctionObject.H.
redirectFunctionObjectPtr_
autoPtr<functionObject> redirectFunctionObjectPtr_ mutable protected
Underlying functionObject.
Definition at line 111 of file codedFunctionObject.H.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/codedFunctionObject/codedFunctionObject.H
src/functionObjects/utilities/codedFunctionObject/codedFunctionObject.C