OpenFOAM: wallBoundedParticle Class Reference
wallBoundedParticle Class Reference
Particle class that tracks on triangles of boundary faces. Use trackToEdge similar to trackToFace on particle.
Classes
class iNew
Factory class to read-construct particles used for.
class TrackingData
Class used to pass tracking data to the trackToFace function.
Public Member Functions
wallBoundedParticle (const polyMesh &c, const vector &position, const label celli, const label tetFacei, const label tetPtI, const label meshEdgeStart, const label diagEdge)
Construct from components.
wallBoundedParticle (const polyMesh &c, Istream &is, bool readFields=true)
Construct from Istream.
wallBoundedParticle (const wallBoundedParticle &p)
Construct copy.
autoPtr< particle > clone () const
Construct and return a clone.
label meshEdgeStart () const
-1 or label of mesh edge
label diagEdge () const
-1 or diagonal edge
template<class TrackData >
scalar trackToEdge (TrackData &td, const vector &endPosition)
Equivalent of trackToFace.
InfoProxy< wallBoundedParticle > info () const
Return info proxy.
template<class TrackData >
Foam::scalar trackToEdge (TrackData &td, const vector &endPosition)
Public Member Functions inherited from particle< Type >
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label celli, bool doCellFacePt=true)
Construct from components, tetFacei_ and tetPti_ are not.
particle (const polyMesh &mesh, Istream &, bool readFields=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with refernce to a new mesh.
virtual ~particle ()
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const vector & position () const
Return current particle position.
vector & position ()
Return current particle position.
label & cell ()
Return current cell particle is in.
label cell () const
Return current cell particle is in.
label & tetFace ()
Return current tet face particle is in.
label tetFace () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in.
label tetPt () const
Return current tet face particle is in.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
tetPointRef currentTet () const
Return the geometry of the current tet that the.
vector normal () const
Return the normal of the tri on tetFacei_ for the.
vector oldNormal () const
Return the normal of the tri on tetFacei_ for the.
label & face ()
Return current face particle is on otherwise -1.
label face () const
Return current face particle is on otherwise -1.
bool softImpact () const
Return the impact model to be used, soft or hard (default).
scalar currentTime () const
Return the particle current time.
void initCellFacePt ()
Check the stored cell value (setting if necessary) and.
bool onBoundary () const
Is the particle on the boundary/(or outside the domain)?
bool internalFace (const label facei) const
Is this global face an internal face?
bool boundaryFace (const label facei) const
Is this global face a boundary face?
label patch (const label facei) const
Which patch is particle on.
label patchFace (const label patchi, const label facei) const
Which face of this patch is this particle on.
scalar & stepFraction ()
Return the fraction of time-step completed.
scalar stepFraction () const
Return the fraction of time-step completed.
label origProc () const
Return const access to the originating processor id.
label & origProc ()
Return the originating processor id for manipulation.
label origId () const
Return const access to the particle id on originating processor.
label & origId ()
Return the particle id on originating processor for manipulation.
template<class TrackData >
label track (const vector &endPosition, TrackData &td)
Track particle to end of trajectory.
template<class TrackData >
scalar trackToFace (const vector &endPosition, TrackData &td)
Track particle to a given position and returns 1.0 if the.
label faceInterpolation () const
Return the index of the face to be used in the interpolation.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
virtual scalar wallImpactDistance (const vector &n) const
The nearest distance to a wall that.
template<class TrackData >
void prepareForParallelTransfer (const label patchi, TrackData &td)
Convert global addressing to the processor patch.
template<class TrackData >
void correctAfterParallelTransfer (const label patchi, TrackData &td)
Convert processor patch addressing to the global equivalents.
void writePosition (Ostream &) const
Write the particle position and cell.
template<class TrackData >
Foam::label track (const vector &endPosition, TrackData &td)
template<class TrackData >
Foam::scalar trackToFace (const vector &endPosition, TrackData &td)
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &)
Read.
template<class CloudType >
static void writeFields (const CloudType &)
Write.
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class CloudType >
static void readFields (CloudType &c)
Read the fields associated with the owner cloud.
template<class CloudType >
static void writeFields (const CloudType &c)
Write the fields associated with the owner cloud.
Protected Member Functions
edge currentEdge () const
Construct current edge.
void crossEdgeConnectedFace (const edge &meshEdge)
Check if inside current tet.
void crossDiagonalEdge ()
Cross diagonal edge into different triangle on same face,cell.
scalar trackFaceTri (const vector &endPosition, label &minEdgeI)
Track through single triangle.
bool isTriAlongTrack (const point &endPosition) const
Is current triangle in the track direction.
template<class TrackData >
void patchInteraction (TrackData &td, const scalar trackFraction)
Do all patch interaction.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchi, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a patch.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedge.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclic.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a polyPatch.
Protected Member Functions inherited from particle< Type >
void findTris (const vector &position, DynamicList< label > &faceList, const tetPointRef &tet, const FixedList< vector, 4 > &tetAreas, const FixedList< label, 4 > &tetPlaneBasePtIs, const scalar tol) const
Find the tet tri faces between position and tet centre.
scalar tetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label celli, const label tetFacei, const label tetPti, const scalar tol) const
Find the lambda value for the line to-from across the.
scalar movingTetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label celli, const label tetFacei, const label tetPti, const scalar tol) const
Find the lambda value for a moving tri face.
void tetNeighbour (label triI)
Modify the tet owner data by crossing triI.
void crossEdgeConnectedFace (const label &celli, label &tetFacei, label &tetPti, const edge &e)
Cross the from the given face across the given edge of the.
template<class CloudType >
void hitWallFaces (const CloudType &td, const vector &from, const vector &to, scalar &lambdaMin, tetIndices &closestTetIs)
template<class TrackData >
void hitFace (TrackData &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchi, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackData >
void hitCyclicAMIPatch (const cyclicAMIPolyPatch &, TrackData &td, const vector &direction)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &tetIs)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
Protected Attributes
label meshEdgeStart_
Particle is on mesh edge:
label diagEdge_
Particle is on diagonal edge:
Protected Attributes inherited from particle< Type >
const polyMesh & mesh_
Reference to the polyMesh database.
vector position_
Position of particle.
label celli_
Index of the cell it is in.
label facei_
Face index if the particle is on a face otherwise -1.
scalar stepFraction_
Fraction of time-step completed.
label tetFacei_
Index of the face that owns the decomposed tet that the.
label tetPti_
Index of the point on the face that defines the decomposed.
label origProc_
Originating processor id.
label origId_
Local particle id on originating processor.
Friends
Ostream & operator<< (Ostream &, const wallBoundedParticle &)
Ostream & operator<< (Ostream &, const InfoProxy< wallBoundedParticle > &)
Additional Inherited Members
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provode unique ID.
static const scalar trackingCorrectionTol = 1e-5
Fraction of distance to tet centre to move a particle to.
static const scalar lambdaDistanceToleranceCoeff = 1e3*SMALL
Fraction of the cell volume to use in determining tolerance values.
static const scalar minStepFractionTol = 1e5*SMALL
Minimum stepFraction tolerance.
Detailed Description
Particle class that tracks on triangles of boundary faces. Use trackToEdge similar to trackToFace on particle.
Source files
wallBoundedParticle.H
wallBoundedParticle.C
wallBoundedParticleTemplates.C
Definition at line 60 of file wallBoundedParticle.H.
Constructor & Destructor Documentation
wallBoundedParticle() [1/3]
wallBoundedParticle (const polyMesh & c, const vector & position, const label celli, const label tetFacei, const label tetPtI, const label meshEdgeStart, const label diagEdge)
Construct from components.
Definition at line 302 of file wallBoundedParticle.C.
Referenced by wallBoundedParticle::clone(), wallBoundedParticle::isTriAlongTrack(), wallBoundedParticle::iNew::operator()(), wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData(), and wallBoundedParticle::wallBoundedParticle().
wallBoundedParticle() [2/3]
wallBoundedParticle (const polyMesh & c, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 319 of file wallBoundedParticle.C.
References IOstream::ASCII, IOstream::check(), wallBoundedParticle::diagEdge_, IOstream::format(), wallBoundedParticle::meshEdgeStart_, Istream::read(), and wallBoundedParticle::wallBoundedParticle().
wallBoundedParticle() [3/3]
wallBoundedParticle (const wallBoundedParticle & p)
Construct copy.
Definition at line 354 of file wallBoundedParticle.C.
Member Function Documentation
currentEdge()
Foam::edge currentEdge () const protected
Construct current edge.
Definition at line 38 of file wallBoundedParticle.C.
References Foam::abort(), wallBoundedParticle::crossEdgeConnectedFace(), wallBoundedParticle::diagEdge_, f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, wallBoundedParticle::info(), particle< Type >::mesh_, wallBoundedParticle::meshEdgeStart_, face::nextLabel(), List< T >::size(), polyMesh::tetBasePtIs(), and particle< Type >::tetFace().
Referenced by wallBoundedParticle::isTriAlongTrack(), wallBoundedParticle::trackFaceTri(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
crossEdgeConnectedFace()
void crossEdgeConnectedFace (const edge & meshEdge) protected
Check if inside current tet.
void checkInside() const;Check if on current edge
void checkOnEdge() const;Check if point on triangle
void checkOnTriangle(const point&) const;Cross mesh edge into different face on same cell
Definition at line 68 of file wallBoundedParticle.C.
References Foam::abort(), particle< Type >::cell(), particle< Type >::crossEdgeConnectedFace(), wallBoundedParticle::diagEdge_, f(), particle< Type >::face(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), wallBoundedParticle::info(), particle< Type >::mesh_, wallBoundedParticle::meshEdgeStart_, face::nextLabel(), UList< T >::rcIndex(), particle< Type >::tetFace(), and particle< Type >::tetPt().
Referenced by wallBoundedParticle::currentEdge(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
crossDiagonalEdge()
void crossDiagonalEdge () protected
Cross diagonal edge into different triangle on same face,cell.
Definition at line 119 of file wallBoundedParticle.C.
References Foam::abort(), wallBoundedParticle::diagEdge_, f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), wallBoundedParticle::info(), particle< Type >::mesh_, wallBoundedParticle::meshEdgeStart_, UList< T >::rcIndex(), particle< Type >::tetFace(), particle< Type >::tetPt(), and wallBoundedParticle::trackFaceTri().
Referenced by wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
trackFaceTri()
Foam::scalar trackFaceTri (const vector & endPosition, label & minEdgeI) protected
Track through single triangle.
Definition at line 166 of file wallBoundedParticle.C.
References wallBoundedParticle::currentEdge(), particle< Type >::currentTetIndices(), wallBoundedParticle::diagEdge_, FixedList< T, Size >::fcIndex(), forAll, wallBoundedParticle::isTriAlongTrack(), Foam::mag(), particle< Type >::mesh_, wallBoundedParticle::meshEdgeStart_, n, triFace::normal(), polyMesh::points(), particle< Type >::position(), and s().
Referenced by wallBoundedParticle::crossDiagonalEdge(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
isTriAlongTrack()
bool isTriAlongTrack (const point & endPosition) const protected
Is current triangle in the track direction.
Definition at line 249 of file wallBoundedParticle.C.
References Foam::abort(), wallBoundedParticle::currentEdge(), particle< Type >::currentTetIndices(), Foam::FatalError, FatalErrorInFunction, FixedList< T, Size >::fcIndex(), Foam::findIndex(), forAll, wallBoundedParticle::info(), Foam::mag(), particle< Type >::mesh_, n, triFace::normal(), polyMesh::points(), particle< Type >::position(), and wallBoundedParticle::wallBoundedParticle().
Referenced by wallBoundedParticle::trackFaceTri(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
patchInteraction()
void patchInteraction (TrackData & td, const scalar trackFraction) protected
Do all patch interaction.
Definition at line 32 of file wallBoundedParticleTemplates.C.
References polyPatch::boundaryMesh(), p, patchi, and wallBoundedParticle::trackToEdge().
Referenced by wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
hitPatch() [1/2]
bool hitPatch (const polyPatch & , TrackData & td, const label patchi, const scalar trackFraction, const tetIndices & tetIs) protected
Overridable function to handle the particle hitting a patch.
Executed before other patch-hitting functions
Definition at line 385 of file wallBoundedParticleTemplates.C.
References wallBoundedParticle::hitWedgePatch().
Referenced by wallBoundedParticle::hitWallPatch(), wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData(), and wallBoundedParticle::trackToEdge().
hitWedgePatch()
void hitWedgePatch (const wedgePolyPatch & pp, TrackData & td) protected
Overridable function to handle the particle hitting a wedge.
Definition at line 400 of file wallBoundedParticleTemplates.C.
References wallBoundedParticle::hitSymmetryPlanePatch().
Referenced by wallBoundedParticle::hitPatch(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
hitSymmetryPlanePatch()
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch & pp, TrackData & td) protected
Overridable function to handle the particle hitting a.
symmetry plane
Definition at line 412 of file wallBoundedParticleTemplates.C.
References wallBoundedParticle::hitSymmetryPatch().
Referenced by wallBoundedParticle::hitWedgePatch(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
hitSymmetryPatch()
void hitSymmetryPatch (const symmetryPolyPatch & pp, TrackData & td) protected
Overridable function to handle the particle hitting a.
symmetry patch
Definition at line 424 of file wallBoundedParticleTemplates.C.
References wallBoundedParticle::hitCyclicPatch().
Referenced by wallBoundedParticle::hitSymmetryPlanePatch(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
hitCyclicPatch()
void hitCyclicPatch (const cyclicPolyPatch & pp, TrackData & td) protected
Overridable function to handle the particle hitting a cyclic.
Definition at line 436 of file wallBoundedParticleTemplates.C.
References wallBoundedParticle::hitProcessorPatch().
Referenced by wallBoundedParticle::hitSymmetryPatch(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
hitProcessorPatch()
void hitProcessorPatch (const processorPolyPatch & pp, TrackData & td) protected
Overridable function to handle the particle hitting a processorPatch
Definition at line 448 of file wallBoundedParticleTemplates.C.
References f(), wallBoundedParticle::hitWallPatch(), and List< T >::size().
Referenced by wallBoundedParticle::hitCyclicPatch(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
hitWallPatch()
void hitWallPatch (const wallPolyPatch & wpp, TrackData & td, const tetIndices &) protected
Overridable function to handle the particle hitting a wallPatch.
Definition at line 477 of file wallBoundedParticleTemplates.C.
References wallBoundedParticle::hitPatch().
Referenced by wallBoundedParticle::hitProcessorPatch(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
hitPatch() [2/2]
void hitPatch (const polyPatch & wpp, TrackData & td) protected
Overridable function to handle the particle hitting a polyPatch.
Definition at line 487 of file wallBoundedParticleTemplates.C.
clone()
autoPtr<particle> clone () const inline virtual
Construct and return a clone.
Reimplemented from particle< Type >.
Reimplemented in wallBoundedStreamLineParticle.
Definition at line 253 of file wallBoundedParticle.H.
References particle< Type >::mesh_, and wallBoundedParticle::wallBoundedParticle().
meshEdgeStart()
label meshEdgeStart () const inline
-1 or label of mesh edge
Definition at line 289 of file wallBoundedParticle.H.
References wallBoundedParticle::meshEdgeStart_.
Referenced by wallBoundedParticle::readFields(), wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData(), wallBoundedStreamLineParticle::trackingData::trackingData(), and wallBoundedParticle::writeFields().
diagEdge()
label diagEdge () const inline
-1 or diagonal edge
Definition at line 295 of file wallBoundedParticle.H.
References wallBoundedParticle::diagEdge_, wallBoundedParticle::info(), wallBoundedParticle::readFields(), wallBoundedParticle::trackToEdge(), and wallBoundedParticle::writeFields().
Referenced by wallBoundedParticle::readFields(), wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData(), wallBoundedStreamLineParticle::trackingData::trackingData(), and wallBoundedParticle::writeFields().
trackToEdge() [1/2]
scalar trackToEdge (TrackData & td, const vector & endPosition)
Equivalent of trackToFace.
Referenced by wallBoundedParticle::diagEdge(), wallBoundedStreamLineParticle::move(), and wallBoundedParticle::patchInteraction().
info()
InfoProxy<wallBoundedParticle> info () const inline
Return info proxy.
Used to print particle information to a stream
Definition at line 316 of file wallBoundedParticle.H.
Referenced by wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), wallBoundedParticle::currentEdge(), wallBoundedParticle::diagEdge(), and wallBoundedParticle::isTriAlongTrack().
readFields()
void readFields (CloudType & c) static
Read.
Definition at line 498 of file wallBoundedParticleTemplates.C.
References Cloud< ParticleType >::checkFieldIOobject(), wallBoundedParticle::diagEdge(), Cloud< ParticleType >::fieldIOobject(), forAllIter, wallBoundedParticle::meshEdgeStart(), IOobject::MUST_READ, particle< Type >::readFields(), and Cloud< ParticleType >::size().
Referenced by wallBoundedParticle::diagEdge(), wallBoundedStreamLineParticle::readFields(), and wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData().
writeFields()
void writeFields (const CloudType & c) static
Write.
Definition at line 529 of file wallBoundedParticleTemplates.C.
References wallBoundedParticle::diagEdge(), Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), wallBoundedParticle::meshEdgeStart(), IOobject::NO_READ, Cloud< ParticleType >::size(), and particle< Type >::writeFields().
Referenced by wallBoundedParticle::diagEdge(), and wallBoundedStreamLineParticle::writeFields().
trackToEdge() [2/2]
Foam::scalar trackToEdge (TrackData & td, const vector & endPosition)
Definition at line 130 of file wallBoundedParticleTemplates.C.
References Foam::abort(), f(), tetIndices::face(), tetIndices::faceBasePt(), tetIndices::facePtA(), tetIndices::facePtB(), tetIndices::faceTri(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), wallBoundedParticle::hitPatch(), Foam::mag(), n, triFace::normal(), triangle< Point, PointRef >::normal(), UList< T >::rcIndex(), and List< T >::size().
Friends And Related Function Documentation
operator<< [1/2]
Ostream& operator<< (Ostream & , const wallBoundedParticle &) friend
operator<< [2/2]
Ostream& operator<< (Ostream & , const InfoProxy< wallBoundedParticle > &) friend
Member Data Documentation
meshEdgeStart_
label meshEdgeStart_ protected
Particle is on mesh edge:
const face& f = mesh.faces()[tetFace()] const edge e(f[meshEdgeStart_], f.nextLabel(meshEdgeStart_)); Note that this real edge is also one of the edges of the face-triangle (from tetFace()+tetPt()).
Definition at line 110 of file wallBoundedParticle.H.
Referenced by wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), wallBoundedParticle::currentEdge(), wallBoundedParticle::meshEdgeStart(), Foam::operator<<(), wallBoundedParticle::trackFaceTri(), wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData(), and wallBoundedParticle::wallBoundedParticle().
diagEdge_
label diagEdge_ protected
Particle is on diagonal edge:
const face& f = mesh.faces()[tetFace()] label faceBasePtI = mesh.tetBasePtIs()[facei]; label diagPtI = (faceBasePtI+diagEdge_)f.size(); const edge e(f[faceBasePtI], f[diagPtI]);
Definition at line 117 of file wallBoundedParticle.H.
Referenced by wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), wallBoundedParticle::currentEdge(), wallBoundedParticle::diagEdge(), Foam::operator<<(), wallBoundedParticle::trackFaceTri(), wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData(), and wallBoundedParticle::wallBoundedParticle().
The documentation for this class was generated from the following files:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticle.H
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticle.C
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticleTemplates.C