OpenFOAM: forceCoeffs Class Reference
forceCoeffs Class Reference
FunctionObjects » Forces function objects
Extends the forces functionObject by providing lift, drag and moment coefficients. The data can optionally be output into bins, defined in a given direction.
Public Member Functions
TypeName ("forceCoeffs")
Runtime type information.
forceCoeffs (const word &name, const Time &runTime, const dictionary &)
Construct from Time and dictionary.
virtual ~forceCoeffs ()
Destructor.
virtual bool read (const dictionary &)
Read the forces data.
virtual bool execute ()
Execute, currently does nothing.
virtual bool write ()
Write the forces.
Public Member Functions inherited from forces
TypeName ("forces")
Runtime type information.
forces (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
forces (const word &name, const objectRegistry &obr, const dictionary &)
Construct from objectRegistry and dictionary.
virtual ~forces ()
Destructor.
virtual void calcForcesMoment ()
Calculate the forces and moments.
virtual vector forceEff () const
Return the total force.
virtual vector momentEff () const
Return the total moment.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()
Destructor.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from logFiles
logFiles (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
virtual ~logFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file ()
Return access to the file (if only 1)
OFstream & file (const label i)
Return file 'i'.
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
~writeFile ()
Destructor.
void initStream (Ostream &os) const
Initialise the output stream for writing.
fileName baseFileDir () const
Return the base directory for output.
fileName baseTimeDir () const
Return the base directory for the current time value.
Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Protected Member Functions
virtual void writeFileHeader (const label i)
Output file header information.
Protected Member Functions inherited from forces
wordList createFileNames (const dictionary &dict) const
Create file names for forces and bins.
void initialise ()
Initialise the fields.
tmp< volSymmTensorField > devRhoReff () const
Return the effective viscous stress (laminar + turbulent).
tmp< volScalarField > mu () const
Dynamic viscosity field.
tmp< volScalarField > rho () const
Return rho if specified otherwise rhoRef.
scalar rho (const volScalarField &p) const
Return rhoRef if the pressure field is dynamic, i.e. p/rho.
void applyBins (const vectorField &Md, const vectorField &fN, const vectorField &fT, const vectorField &fP, const vectorField &d)
Accumulate bin data.
void writeForces ()
Helper function to write force data.
void writeBins ()
Helper function to write bin data.
forces (const forces &)
Disallow default bitwise copy construct.
void operator= (const forces &)
Disallow default bitwise assignment.
Protected Member Functions inherited from regionFunctionObject
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find field in the objectRegistry.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup field from the objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the given field in the objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the objectRegistry if present.
Protected Member Functions inherited from logFiles
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Types inherited from forces
enum fileID { MAIN_FILE = 0, BINS_FILE = 1 }
Enumeration for ensuring the right file is accessed.
Protected Attributes inherited from forces
List< Field< vector > > force_
Pressure, viscous and porous force per bin.
List< Field< vector > > moment_
Pressure, viscous and porous moment per bin.
labelHashSet patchSet_
Patches to integrate forces over.
word pName_
Name of pressure field.
word UName_
Name of velocity field.
word rhoName_
Name of density field (optional)
Switch directForceDensity_
Is the force density being supplied directly?
word fDName_
The name of the force density (fD) field.
scalar rhoRef_
Reference density needed for incompressible calculations.
scalar pRef_
Reference pressure.
coordinateSystem coordSys_
Coordinate system used when evaluting forces/moments.
bool localSystem_
Flag to indicate whether we are using a local co-ordinate sys.
bool porosity_
Flag to include porosity effects.
label nBin_
Number of bins.
vector binDir_
Direction used to determine bin orientation.
scalar binDx_
Distance between bin divisions.
scalar binMin_
Minimum bin bounds.
List< point > binPoints_
Bin positions along binDir.
bool binCumulative_
Should bin data be cumulative?
bool initialised_
Initialised flag.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
const Time & time_
Reference to the Time.
const objectRegistry & obr_
Reference to the region objectRegistry.
Protected Attributes inherited from logFiles
wordList names_
File names.
PtrList< OFstream > filePtrs_
File pointer.
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
Reference to the region objectRegistry.
const word prefix_
Prefix.
Detailed Description
Extends the forces functionObject by providing lift, drag and moment coefficients. The data can optionally be output into bins, defined in a given direction.
Example of function object specification:
forceCoeffs1
{
    type        forceCoeffs;
    libs        ("libforces.so");
    ...
    log         yes;
    patches     (walls);
    liftDir     (0 1 0);
    dragDir     (-1 0 0);
    pitchAxis   (0 0 1);
    magUInf     100;
    lRef        3.5;
    Aref        2.2;
    binData
    {
        nBin        20;
        direction   (1 0 0);
        cumulative  yes;
    }
}
Usage
Property Description Required Default value
type type name: forces yes
log write force data to standard output no no
patches patches included in the forces calculation yes
liftDir lift direction yes
dragDir drag direction yes
pitchAxis picth axis yes
magUInf free stream velocity magnitude yes
lRef reference length scale for moment calculations yes
Aref reference area yes
Bin data is optional, but if the dictionary is present, the entries must be defined according o
nBin number of data bins yes
direction direction along which bins are defined yes
cumulative bin data accumulated with incresing distance yes
See also
Foam::functionObject Foam::functionObjects::timeControl Foam::functionObjects::forces
Source files
forceCoeffs.H
forceCoeffs.C
Definition at line 172 of file forceCoeffs.H.
Constructor & Destructor Documentation
forceCoeffs()
forceCoeffs (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 128 of file forceCoeffs.C.
References Foam::read().
~forceCoeffs()
~forceCoeffs () virtual
Destructor.
Definition at line 148 of file forceCoeffs.C.
Member Function Documentation
writeFileHeader()
void writeFileHeader (const label i) protected virtual
Output file header information.
Reimplemented from forces.
Definition at line 43 of file forceCoeffs.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::jn(), Foam::name(), Foam::nl, and Foam::tab.
TypeName()
TypeName ("forceCoeffs")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the forces data.
Reimplemented from forces.
Definition at line 154 of file forceCoeffs.C.
References dictionary::lookup(), and forces::read().
execute()
bool execute () virtual
Execute, currently does nothing.
Reimplemented from forces.
Definition at line 174 of file forceCoeffs.C.
write()
bool write () virtual
Write the forces.
Reimplemented from forces.
Definition at line 180 of file forceCoeffs.C.
References forces::calcForcesMoment(), Foam::endl(), forAll, Log, UPstream::master(), Foam::name(), Foam::nl, pDyn(), List< T >::setSize(), List< T >::size(), Foam::sum(), Foam::tab, Foam::type(), and logFiles::write().
The documentation for this class was generated from the following files:
src/functionObjects/forces/forceCoeffs/forceCoeffs.H
src/functionObjects/forces/forceCoeffs/forceCoeffs.C