OpenFOAM: wallBoundedStreamLineParticle Class Reference
wallBoundedStreamLineParticle Class Reference
Particle class that samples fields as it passes through. Used in streamline calculation.
Classes
class iNew
Factory class to read-construct particles used for.
class trackingData
Class used to pass tracking data to the trackToEdge function.
Public Member Functions
wallBoundedStreamLineParticle (const polyMesh &c, const vector &position, const label celli, const label tetFacei, const label tetPtI, const label meshEdgeStart, const label diagEdge, const label lifeTime)
Construct from components.
wallBoundedStreamLineParticle (const polyMesh &c, Istream &is, bool readFields=true)
Construct from Istream.
wallBoundedStreamLineParticle (const wallBoundedStreamLineParticle &p)
Construct copy.
autoPtr< particle > clone () const
Construct and return a clone.
bool move (trackingData &, const scalar trackTime)
Track all particles to their end point.
Public Member Functions inherited from wallBoundedParticle
wallBoundedParticle (const polyMesh &c, const vector &position, const label celli, const label tetFacei, const label tetPtI, const label meshEdgeStart, const label diagEdge)
Construct from components.
wallBoundedParticle (const polyMesh &c, Istream &is, bool readFields=true)
Construct from Istream.
wallBoundedParticle (const wallBoundedParticle &p)
Construct copy.
label meshEdgeStart () const
-1 or label of mesh edge
label diagEdge () const
-1 or diagonal edge
template<class TrackData >
scalar trackToEdge (TrackData &td, const vector &endPosition)
Equivalent of trackToFace.
InfoProxy< wallBoundedParticle > info () const
Return info proxy.
template<class TrackData >
Foam::scalar trackToEdge (TrackData &td, const vector &endPosition)
Public Member Functions inherited from particle< Type >
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label celli, bool doCellFacePt=true)
Construct from components, tetFacei_ and tetPti_ are not.
particle (const polyMesh &mesh, Istream &, bool readFields=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with refernce to a new mesh.
virtual ~particle ()
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const vector & position () const
Return current particle position.
vector & position ()
Return current particle position.
label & cell ()
Return current cell particle is in.
label cell () const
Return current cell particle is in.
label & tetFace ()
Return current tet face particle is in.
label tetFace () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in.
label tetPt () const
Return current tet face particle is in.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
tetPointRef currentTet () const
Return the geometry of the current tet that the.
vector normal () const
Return the normal of the tri on tetFacei_ for the.
vector oldNormal () const
Return the normal of the tri on tetFacei_ for the.
label & face ()
Return current face particle is on otherwise -1.
label face () const
Return current face particle is on otherwise -1.
bool softImpact () const
Return the impact model to be used, soft or hard (default).
scalar currentTime () const
Return the particle current time.
void initCellFacePt ()
Check the stored cell value (setting if necessary) and.
bool onBoundary () const
Is the particle on the boundary/(or outside the domain)?
bool internalFace (const label facei) const
Is this global face an internal face?
bool boundaryFace (const label facei) const
Is this global face a boundary face?
label patch (const label facei) const
Which patch is particle on.
label patchFace (const label patchi, const label facei) const
Which face of this patch is this particle on.
scalar & stepFraction ()
Return the fraction of time-step completed.
scalar stepFraction () const
Return the fraction of time-step completed.
label origProc () const
Return const access to the originating processor id.
label & origProc ()
Return the originating processor id for manipulation.
label origId () const
Return const access to the particle id on originating processor.
label & origId ()
Return the particle id on originating processor for manipulation.
template<class TrackData >
label track (const vector &endPosition, TrackData &td)
Track particle to end of trajectory.
template<class TrackData >
scalar trackToFace (const vector &endPosition, TrackData &td)
Track particle to a given position and returns 1.0 if the.
label faceInterpolation () const
Return the index of the face to be used in the interpolation.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
virtual scalar wallImpactDistance (const vector &n) const
The nearest distance to a wall that.
template<class TrackData >
void prepareForParallelTransfer (const label patchi, TrackData &td)
Convert global addressing to the processor patch.
template<class TrackData >
void correctAfterParallelTransfer (const label patchi, TrackData &td)
Convert processor patch addressing to the global equivalents.
void writePosition (Ostream &) const
Write the particle position and cell.
template<class TrackData >
Foam::label track (const vector &endPosition, TrackData &td)
template<class TrackData >
Foam::scalar trackToFace (const vector &endPosition, TrackData &td)
Static Public Member Functions
static void readFields (Cloud< wallBoundedStreamLineParticle > &)
Read.
static void writeFields (const Cloud< wallBoundedStreamLineParticle > &)
Write.
Static Public Member Functions inherited from wallBoundedParticle
template<class CloudType >
static void readFields (CloudType &)
Read.
template<class CloudType >
static void writeFields (const CloudType &)
Write.
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class CloudType >
static void readFields (CloudType &c)
Read the fields associated with the owner cloud.
template<class CloudType >
static void writeFields (const CloudType &c)
Write the fields associated with the owner cloud.
Friends
Ostream & operator<< (Ostream &, const wallBoundedStreamLineParticle &)
Additional Inherited Members
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provode unique ID.
static const scalar trackingCorrectionTol = 1e-5
Fraction of distance to tet centre to move a particle to.
static const scalar lambdaDistanceToleranceCoeff = 1e3*SMALL
Fraction of the cell volume to use in determining tolerance values.
static const scalar minStepFractionTol = 1e5*SMALL
Minimum stepFraction tolerance.
Protected Member Functions inherited from wallBoundedParticle
edge currentEdge () const
Construct current edge.
void crossEdgeConnectedFace (const edge &meshEdge)
Check if inside current tet.
void crossDiagonalEdge ()
Cross diagonal edge into different triangle on same face,cell.
scalar trackFaceTri (const vector &endPosition, label &minEdgeI)
Track through single triangle.
bool isTriAlongTrack (const point &endPosition) const
Is current triangle in the track direction.
template<class TrackData >
void patchInteraction (TrackData &td, const scalar trackFraction)
Do all patch interaction.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchi, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a patch.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedge.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclic.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a polyPatch.
Protected Member Functions inherited from particle< Type >
void findTris (const vector &position, DynamicList< label > &faceList, const tetPointRef &tet, const FixedList< vector, 4 > &tetAreas, const FixedList< label, 4 > &tetPlaneBasePtIs, const scalar tol) const
Find the tet tri faces between position and tet centre.
scalar tetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label celli, const label tetFacei, const label tetPti, const scalar tol) const
Find the lambda value for the line to-from across the.
scalar movingTetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label celli, const label tetFacei, const label tetPti, const scalar tol) const
Find the lambda value for a moving tri face.
void tetNeighbour (label triI)
Modify the tet owner data by crossing triI.
void crossEdgeConnectedFace (const label &celli, label &tetFacei, label &tetPti, const edge &e)
Cross the from the given face across the given edge of the.
template<class CloudType >
void hitWallFaces (const CloudType &td, const vector &from, const vector &to, scalar &lambdaMin, tetIndices &closestTetIs)
template<class TrackData >
void hitFace (TrackData &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchi, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackData >
void hitCyclicAMIPatch (const cyclicAMIPolyPatch &, TrackData &td, const vector &direction)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &tetIs)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
Protected Attributes inherited from wallBoundedParticle
label meshEdgeStart_
Particle is on mesh edge:
label diagEdge_
Particle is on diagonal edge:
Protected Attributes inherited from particle< Type >
const polyMesh & mesh_
Reference to the polyMesh database.
vector position_
Position of particle.
label celli_
Index of the cell it is in.
label facei_
Face index if the particle is on a face otherwise -1.
scalar stepFraction_
Fraction of time-step completed.
label tetFacei_
Index of the face that owns the decomposed tet that the.
label tetPti_
Index of the point on the face that defines the decomposed.
label origProc_
Originating processor id.
label origId_
Local particle id on originating processor.
Detailed Description
Particle class that samples fields as it passes through. Used in streamline calculation.
Source files
wallBoundedStreamLineParticle.H
wallBoundedStreamLineParticle.C
Definition at line 63 of file wallBoundedStreamLineParticle.H.
Constructor & Destructor Documentation
wallBoundedStreamLineParticle() [1/3]
wallBoundedStreamLineParticle (const polyMesh & c, const vector & position, const label celli, const label tetFacei, const label tetPtI, const label meshEdgeStart, const label diagEdge, const label lifeTime)
Construct from components.
Definition at line 134 of file wallBoundedStreamLineParticle.C.
Referenced by wallBoundedStreamLineParticle::clone(), wallBoundedStreamLineParticle::iNew::operator()(), wallBoundedStreamLineParticle::trackingData::trackingData(), and wallBoundedStreamLineParticle::wallBoundedStreamLineParticle().
wallBoundedStreamLineParticle() [2/3]
wallBoundedStreamLineParticle (const polyMesh & c, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 160 of file wallBoundedStreamLineParticle.C.
References IOstream::check(), forAll, List< T >::size(), and wallBoundedStreamLineParticle::wallBoundedStreamLineParticle().
wallBoundedStreamLineParticle() [3/3]
wallBoundedStreamLineParticle (const wallBoundedStreamLineParticle & p)
Construct copy.
Definition at line 198 of file wallBoundedStreamLineParticle.C.
References wallBoundedStreamLineParticle::move().
Member Function Documentation
clone()
autoPtr<particle> clone () const inline virtual
Construct and return a clone.
Reimplemented from wallBoundedParticle.
Definition at line 190 of file wallBoundedStreamLineParticle.H.
References particle< Type >::mesh_, and wallBoundedStreamLineParticle::wallBoundedStreamLineParticle().
move()
bool move (trackingData & td, const scalar trackTime)
Track all particles to their end point.
Definition at line 213 of file wallBoundedStreamLineParticle.C.
References wallBoundedStreamLineParticle::trackingData::allPositions_, wallBoundedStreamLineParticle::trackingData::allScalars_, wallBoundedStreamLineParticle::trackingData::allVectors_, polyMesh::bounds(), Foam::endl(), forAll, particle< Type >::TrackingData< CloudType >::keepParticle, boundBox::mag(), particle< Type >::mesh_, particle< Type >::position(), Foam::Pout, wallBoundedStreamLineParticle::readFields(), particle< Type >::stepFraction(), particle< Type >::TrackingData< CloudType >::switchProcessor, wallBoundedStreamLineParticle::trackingData::trackLength_, wallBoundedParticle::trackToEdge(), and List< T >::transfer().
Referenced by wallBoundedStreamLineParticle::iNew::operator()(), and wallBoundedStreamLineParticle::wallBoundedStreamLineParticle().
readFields()
void readFields (Cloud< wallBoundedStreamLineParticle > & c) static
Read.
Definition at line 345 of file wallBoundedStreamLineParticle.C.
References Cloud< ParticleType >::checkFieldIOobject(), Cloud< ParticleType >::fieldIOobject(), forAllIter, IOobject::MUST_READ, wallBoundedParticle::readFields(), Cloud< ParticleType >::size(), and wallBoundedStreamLineParticle::writeFields().
Referenced by wallBoundedStreamLineParticle::move(), wallBoundedStreamLineParticle::iNew::operator()(), wallBoundedStreamLineParticle::trackingData::trackingData(), and wallBoundedStreamLineParticleCloud::wallBoundedStreamLineParticleCloud().
writeFields()
void writeFields (const Cloud< wallBoundedStreamLineParticle > & c) static
Write.
Definition at line 379 of file wallBoundedStreamLineParticle.C.
References Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), IOobject::NO_READ, Cloud< ParticleType >::size(), regIOobject::write(), and wallBoundedParticle::writeFields().
Referenced by wallBoundedStreamLineParticle::iNew::operator()(), and wallBoundedStreamLineParticle::readFields().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const wallBoundedStreamLineParticle &) friend
The documentation for this class was generated from the following files:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLineParticle.H
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLineParticle.C