OpenFOAM: writeObjects Class Reference
writeObjects Class Reference
FunctionObjects » Utility function objects
Allows specification of different writing frequency of objects registered to the database.
Public Types
enum writeOption { AUTO_WRITE, NO_WRITE, ANY_WRITE }
Re-enumeration defining the write options, based on the original.
Public Member Functions
TypeName ("writeObjects")
Runtime type information.
writeObjects (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~writeObjects ()
Destructor.
virtual bool read (const dictionary &)
Read the writeObjects data.
virtual bool execute ()
Do nothing.
virtual bool write ()
Write the registered objects.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Static Public Attributes
static const NamedEnum< writeOption, 3 > writeOptionNames_
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Detailed Description
Allows specification of different writing frequency of objects registered to the database.
It has similar functionality as the main time database through the writeControl setting:
timeStep
writeTime
adjustableRunTime
runTime
clockTime
cpuTime
It also has the ability to write the selected objects that were defined with the respective write mode for the requested writeOption, namely:
= objects set to write at output time
= objects set to not write by default
= any option of the previous two
Example of function object specification:
    writeObjects1
    {
        type        writeObjects;
        libs        ("libutilityFunctionObjects.so");
        ...
        objects     (obj1 obj2);
        writeOption anyWrite;
    }
Usage
Property Description Required Default value
type type name: writeObjects yes
objects objects to write yes
writeOption only those with this write option no anyWrite
Note: Regular expressions can also be used in objects.
See also
Foam::functionObject Foam::functionObjects::timeControl
Source files
writeObjects.H
writeObjects.C
Definition at line 135 of file writeObjects.H.
Member Enumeration Documentation
writeOption
enum writeOption
Re-enumeration defining the write options, based on the original.
ones at IOobject::writeOption
Enumerator
AUTO_WRITE
NO_WRITE
ANY_WRITE
Definition at line 145 of file writeObjects.H.
Constructor & Destructor Documentation
writeObjects()
writeObjects (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 70 of file writeObjects.C.
References Foam::read().
~writeObjects()
~writeObjects () virtual
Destructor.
Definition at line 93 of file writeObjects.C.
Member Function Documentation
TypeName()
TypeName ("writeObjects")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the writeObjects data.
Reimplemented from functionObject.
Definition at line 99 of file writeObjects.C.
References dictionary::found(), dictionary::lookup(), and ITstream::read().
execute()
bool execute () virtual
Do nothing.
Implements functionObject.
Definition at line 128 of file writeObjects.C.
write()
bool write () virtual
Write the registered objects.
Implements functionObject.
Definition at line 134 of file writeObjects.C.
References IOobject::AUTO_WRITE, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::name(), IOobject::name(), Foam::nl, IOobject::NO_WRITE, List< T >::size(), Foam::type(), WarningInFunction, regIOobject::write(), and IOobject::writeOpt().
Member Data Documentation
writeOptionNames_
const Foam::NamedEnum< Foam::functionObjects::writeObjects::writeOption, 3 > writeOptionNames_ static
Definition at line 152 of file writeObjects.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/functionObjects/utilities/writeObjects/writeObjects.H
src/functionObjects/utilities/writeObjects/writeObjects.C