OpenFOAM: pointEdgeStructuredWalk Class Reference
pointEdgeStructuredWalk Class Reference
Determines length of string of edges walked to point.
Public Member Functions
pointEdgeStructuredWalk ()
Construct null.
pointEdgeStructuredWalk (const point &, const point &, const scalar, const vector &)
Construct from components.
bool inZone () const
scalar dist () const
const vector & data () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const pointEdgeStructuredWalk &, const scalar tol, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
Convert origin to relative vector to leaving point.
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
Convert relative origin to absolute by adding entering point.
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to origin.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const pointEdgeStructuredWalk &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on point.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const pointEdgeStructuredWalk &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updatePoint (const pointEdgeStructuredWalk &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const pointEdgeStructuredWalk &pointInfo, const scalar tol, TrackingData &td)
Influence of point on edge.
template<class TrackingData >
bool equal (const pointEdgeStructuredWalk &, TrackingData &) const
Same (like operator==)
bool operator== (const pointEdgeStructuredWalk &) const
bool operator!= (const pointEdgeStructuredWalk &) const
Friends
Ostream & operator<< (Ostream &, const pointEdgeStructuredWalk &)
Istream & operator>> (Istream &, pointEdgeStructuredWalk &)
Detailed Description
Determines length of string of edges walked to point.
Source files
pointEdgeStructuredWalk.H
pointEdgeStructuredWalkI.H
pointEdgeStructuredWalk.C
Definition at line 63 of file pointEdgeStructuredWalk.H.
Constructor & Destructor Documentation
pointEdgeStructuredWalk() [1/2]
pointEdgeStructuredWalk () inline
Construct null.
Definition at line 59 of file pointEdgeStructuredWalkI.H.
pointEdgeStructuredWalk() [2/2]
pointEdgeStructuredWalk (const point & point0, const point & previousPoint, const scalar dist, const vector & data) inline
Construct from components.
Definition at line 70 of file pointEdgeStructuredWalkI.H.
Member Function Documentation
inZone()
bool inZone () const inline
Definition at line 86 of file pointEdgeStructuredWalkI.H.
References VectorSpace< Vector< scalar >, scalar, 3 >::max.
Referenced by pointEdgeStructuredWalk::updateEdge(), and pointEdgeStructuredWalk::updatePoint().
dist()
Foam::scalar dist () const inline
Definition at line 98 of file pointEdgeStructuredWalkI.H.
Referenced by pointEdgeStructuredWalk::sameGeometry().
data()
const Foam::vector & data () const inline
Definition at line 104 of file pointEdgeStructuredWalkI.H.
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 111 of file pointEdgeStructuredWalkI.H.
References VectorSpace< Vector< scalar >, scalar, 3 >::max, and pointEdgeStructuredWalk::sameGeometry().
sameGeometry()
bool sameGeometry (const pointEdgeStructuredWalk & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 120 of file pointEdgeStructuredWalkI.H.
References Foam::diff(), pointEdgeStructuredWalk::dist(), pointEdgeStructuredWalk::leaveDomain(), and Foam::mag().
Referenced by pointEdgeStructuredWalk::valid().
leaveDomain()
void leaveDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Convert origin to relative vector to leaving point.
(= point coordinate)
Definition at line 148 of file pointEdgeStructuredWalkI.H.
References pointEdgeStructuredWalk::transform().
Referenced by pointEdgeStructuredWalk::sameGeometry().
enterDomain()
void enterDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Convert relative origin to absolute by adding entering point.
Definition at line 174 of file pointEdgeStructuredWalkI.H.
References pointEdgeStructuredWalk::updatePoint().
Referenced by pointEdgeStructuredWalk::transform().
transform()
void transform (const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to origin.
Definition at line 161 of file pointEdgeStructuredWalkI.H.
References pointEdgeStructuredWalk::enterDomain(), and Foam::transform().
Referenced by pointEdgeStructuredWalk::leaveDomain().
updatePoint() [1/3]
bool updatePoint (const polyMesh & mesh, const label pointi, const label edgeI, const pointEdgeStructuredWalk & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on point.
Definition at line 189 of file pointEdgeStructuredWalkI.H.
References pointEdgeStructuredWalk::inZone().
Referenced by pointEdgeStructuredWalk::enterDomain(), and pointEdgeStructuredWalk::updatePoint().
updatePoint() [2/3]
bool updatePoint (const polyMesh & mesh, const label pointi, const pointEdgeStructuredWalk & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
Merge new and old info.
Definition at line 212 of file pointEdgeStructuredWalkI.H.
References pointEdgeStructuredWalk::inZone(), and pointEdgeStructuredWalk::updatePoint().
updatePoint() [3/3]
bool updatePoint (const pointEdgeStructuredWalk & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
No information about current position whatsoever.
Definition at line 234 of file pointEdgeStructuredWalkI.H.
References pointEdgeStructuredWalk::updateEdge().
updateEdge()
bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointi, const pointEdgeStructuredWalk & pointInfo, const scalar tol, TrackingData & td) inline
Influence of point on edge.
Definition at line 247 of file pointEdgeStructuredWalkI.H.
References pointEdgeStructuredWalk::equal(), and pointEdgeStructuredWalk::inZone().
Referenced by pointEdgeStructuredWalk::updatePoint().
equal()
bool equal (const pointEdgeStructuredWalk & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 269 of file pointEdgeStructuredWalkI.H.
References pointEdgeStructuredWalk::operator==().
Referenced by pointEdgeStructuredWalk::updateEdge().
operator==()
bool operator== (const pointEdgeStructuredWalk & rhs) const inline
Definition at line 281 of file pointEdgeStructuredWalkI.H.
Referenced by pointEdgeStructuredWalk::equal().
operator!=()
bool operator!= (const pointEdgeStructuredWalk & rhs) const inline
Definition at line 290 of file pointEdgeStructuredWalkI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const pointEdgeStructuredWalk &) friend
operator>>
Istream& operator>> (Istream & , pointEdgeStructuredWalk &) friend
The documentation for this class was generated from the following files:
src/fvMotionSolver/fvMotionSolvers/displacement/layeredSolver/pointEdgeStructuredWalk.H
src/fvMotionSolver/fvMotionSolvers/displacement/layeredSolver/pointEdgeStructuredWalkI.H