OpenFOAM: systemCall Class Reference
systemCall Class Reference
FunctionObjects » Utility function objects
Executes system calls, entered in the form of a string lists.
Public Member Functions
TypeName ("systemCall")
Runtime type information.
systemCall (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~systemCall ()
Destructor.
virtual bool read (const dictionary &)
Read the system calls.
virtual bool execute ()
Execute the "executeCalls" at each time-step.
virtual bool end ()
Execute the "endCalls" at the final time-loop.
virtual bool write ()
Write, execute the "writeCalls".
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Attributes
stringList executeCalls_
List of calls to execute - every step.
stringList endCalls_
List of calls to execute when exiting the time-loop.
stringList writeCalls_
List of calls to execute - write steps.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Executes system calls, entered in the form of a string lists.
Calls can be made at the following points in the calculation:
every time step
every output time
end of the calculation
Example of function object specification:
systemCall1
{
    type        systemCall;
    libs        ("libutilityFunctionObjects.so");
    ...
    executeCalls
    (
        "echo execute"
    );
    writeCalls
    (
        "echo \*\*\* writing data \*\*\*"
    );
    endCalls
    (
        "echo \*\*\* writing .bashrc \*\*\*"
        "cat ~/.bashrc"
        "echo \*\*\* done \*\*\*"
    );
}
Usage
Property Description Required Default value
type type name: systemCall yes
executeCalls list of calls on execute yes
writeCalls list of calls on write yes
endCalls list of calls on end yes
Note
Since this function object executes system calls, there is a potential security risk. In order to use the systemCall function object, the allowSystemOperations must be set to '1'; otherwise, system calls will not be allowed.
See also
Foam::functionObject Foam::functionObjects::timeControl
Source files
systemCall.H
systemCall.C
Definition at line 127 of file systemCall.H.
Constructor & Destructor Documentation
systemCall()
systemCall (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 52 of file systemCall.C.
References Foam::read().
~systemCall()
~systemCall () virtual
Destructor.
Definition at line 69 of file systemCall.C.
Member Function Documentation
TypeName()
TypeName ("systemCall")
Runtime type information.
read()
bool read (const dictionary & dict) virtual
Read the system calls.
Reimplemented from functionObject.
Definition at line 75 of file systemCall.C.
References dynamicCode::allowSystemOperations, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, dictionary::readIfPresent(), and WarningInFunction.
execute()
bool execute () virtual
Execute the "executeCalls" at each time-step.
Implements functionObject.
Definition at line 108 of file systemCall.C.
References forAll, and Foam::system().
end()
bool end () virtual
Execute the "endCalls" at the final time-loop.
Reimplemented from functionObject.
Definition at line 119 of file systemCall.C.
References forAll, and Foam::system().
write()
bool write () virtual
Write, execute the "writeCalls".
Implements functionObject.
Definition at line 130 of file systemCall.C.
References forAll, and Foam::system().
Member Data Documentation
executeCalls_
stringList executeCalls_ protected
List of calls to execute - every step.
Definition at line 136 of file systemCall.H.
endCalls_
stringList endCalls_ protected
List of calls to execute when exiting the time-loop.
Definition at line 139 of file systemCall.H.
writeCalls_
stringList writeCalls_ protected
List of calls to execute - write steps.
Definition at line 142 of file systemCall.H.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/systemCall/systemCall.H
src/functionObjects/utilities/systemCall/systemCall.C