OpenFOAM: pairPatchAgglomeration Class Reference
pairPatchAgglomeration Class Reference
Primitive patch pair agglomerate method.
Public Member Functions
pairPatchAgglomeration (const polyPatch &patch, const dictionary &controlDict, const bool additionalWeights=false)
Construct given mesh and controls.
~pairPatchAgglomeration ()
void agglomerate ()
Agglomerate patch.
label size () const
Return size.
const labelList & restrictTopBottomAddressing () const
Return restriction from top level to bottom level.
const bPatch & patchLevel (const label leveli) const
Return primitivePatch of given level.
const labelField & restrictAddressing (const label leveli) const
Return cell restrict addressing of given level.
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex) const
Restrict (integrate by summation) cell field.
template<class Type >
void prolongField (Field< Type > &ff, const Field< Type > &cf, const label coarseLevelIndex) const
Prolong (interpolate by injection) cell field.
Protected Attributes
label mergeLevels_
Number of levels to merge, 1 = don't merge, 2 = merge pairs etc.
label maxLevels_
Max number of levels.
label nFacesInCoarsestLevel_
Number of faces in coarsest level.
scalar featureAngle_
Feature angle.
labelList nFaces_
The number of faces in each level.
PtrList< labelField > restrictAddressing_
Cell restriction addressing array.
labelList restrictTopBottomAddressing_
Maps from finest to coarsest.
PtrList< bPatch > patchLevels_
Hierarchy of patch addressing.
EdgeMap< scalar > facePairWeight_
Edge weights.
Detailed Description
Primitive patch pair agglomerate method.
Source files
pairPatchAgglomeration.H
pairPatchAgglomeration.C
Definition at line 57 of file pairPatchAgglomeration.H.
Constructor & Destructor Documentation
pairPatchAgglomeration()
pairPatchAgglomeration (const polyPatch & patch, const dictionary & controlDict, const bool additionalWeights = false)
Construct given mesh and controls.
Definition at line 190 of file pairPatchAgglomeration.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), pairPatchAgglomeration::nFaces_, and pairPatchAgglomeration::patchLevels_.
~pairPatchAgglomeration()
~pairPatchAgglomeration ()
Definition at line 236 of file pairPatchAgglomeration.C.
References pairPatchAgglomeration::patchLevel().
Member Function Documentation
agglomerate()
void agglomerate ()
Agglomerate patch.
Definition at line 354 of file pairPatchAgglomeration.C.
References Foam::exit(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceFaces(), pairPatchAgglomeration::facePairWeight_, Foam::FatalError, FatalErrorInFunction, forAll, pairPatchAgglomeration::maxLevels_, pairPatchAgglomeration::mergeLevels_, pairPatchAgglomeration::nFaces_, pairPatchAgglomeration::patchLevels_, Foam::reduce(), tmp< T >::ref(), and pairPatchAgglomeration::restrictAddressing_.
size()
label size () const inline
Return size.
Definition at line 162 of file pairPatchAgglomeration.H.
References UPtrList< T >::size().
restrictTopBottomAddressing()
const labelList& restrictTopBottomAddressing () const inline
Return restriction from top level to bottom level.
Definition at line 168 of file pairPatchAgglomeration.H.
References pairPatchAgglomeration::patchLevel(), and pairPatchAgglomeration::restrictTopBottomAddressing_.
patchLevel()
const Foam::bPatch & patchLevel (const label leveli) const
Return primitivePatch of given level.
Definition at line 243 of file pairPatchAgglomeration.C.
References Foam::abort(), Foam::e, Foam::endl(), Foam::exit(), pairPatchAgglomeration::facePairWeight_, Foam::FatalError, FatalErrorInFunction, forAll, Foam::invertOneToMany(), Foam::max(), Foam::min(), pairPatchAgglomeration::patchLevels_, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::renumber(), pairPatchAgglomeration::restrictAddressing_, pairPatchAgglomeration::restrictTopBottomAddressing_, and List< T >::size().
Referenced by pairPatchAgglomeration::restrictTopBottomAddressing(), and pairPatchAgglomeration::~pairPatchAgglomeration().
restrictAddressing()
const labelField& restrictAddressing (const label leveli) const inline
Return cell restrict addressing of given level.
Definition at line 177 of file pairPatchAgglomeration.H.
References Foam::fv::ff(), pairPatchAgglomeration::prolongField(), and pairPatchAgglomeration::restrictField().
restrictField()
void restrictField (Field< Type > & cf, const Field< Type > & ff, const label fineLevelIndex) const
Restrict (integrate by summation) cell field.
Definition at line 32 of file pairPatchAgglomerationTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, pairPatchAgglomeration::prolongField(), List< Type >::size(), List< T >::size(), and Foam::Zero.
Referenced by pairPatchAgglomeration::restrictAddressing().
prolongField()
void prolongField (Field< Type > & ff, const Field< Type > & cf, const label coarseLevelIndex) const
Prolong (interpolate by injection) cell field.
Definition at line 60 of file pairPatchAgglomerationTemplates.C.
References forAll.
Referenced by pairPatchAgglomeration::restrictAddressing(), and pairPatchAgglomeration::restrictField().
Member Data Documentation
mergeLevels_
label mergeLevels_ protected
Number of levels to merge, 1 = don't merge, 2 = merge pairs etc.
Definition at line 64 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::agglomerate().
maxLevels_
label maxLevels_ protected
Max number of levels.
Definition at line 67 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::agglomerate().
nFacesInCoarsestLevel_
label nFacesInCoarsestLevel_ protected
Number of faces in coarsest level.
Definition at line 70 of file pairPatchAgglomeration.H.
featureAngle_
scalar featureAngle_ protected
Feature angle.
Definition at line 73 of file pairPatchAgglomeration.H.
nFaces_
labelList nFaces_ protected
The number of faces in each level.
Definition at line 76 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::agglomerate(), and pairPatchAgglomeration::pairPatchAgglomeration().
restrictAddressing_
PtrList<labelField> restrictAddressing_ protected
Cell restriction addressing array.
Maps from the finer to coarse level
Definition at line 80 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::agglomerate(), and pairPatchAgglomeration::patchLevel().
restrictTopBottomAddressing_
labelList restrictTopBottomAddressing_ protected
Maps from finest to coarsest.
Definition at line 83 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::patchLevel(), and pairPatchAgglomeration::restrictTopBottomAddressing().
patchLevels_
PtrList<bPatch> patchLevels_ protected
Hierarchy of patch addressing.
Definition at line 86 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::agglomerate(), pairPatchAgglomeration::pairPatchAgglomeration(), and pairPatchAgglomeration::patchLevel().
facePairWeight_
EdgeMap<scalar> facePairWeight_ protected
Edge weights.
Definition at line 89 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::agglomerate(), and pairPatchAgglomeration::patchLevel().
The documentation for this class was generated from the following files:
src/fvAgglomerationMethods/pairPatchAgglomeration/pairPatchAgglomeration.H
src/fvAgglomerationMethods/pairPatchAgglomeration/pairPatchAgglomeration.C
src/fvAgglomerationMethods/pairPatchAgglomeration/pairPatchAgglomerationTemplates.C