OpenFOAM: surfaceDisplacementPointPatchVectorField Class Reference
surfaceDisplacementPointPatchVectorField Class Reference
Displacement fixed by projection onto triSurface. Use in a displacementMotionSolver as a bc on the pointDisplacement field.
Public Types
enum projectMode { NEAREST, POINTNORMAL, FIXEDNORMAL }
Public Member Functions
TypeName ("surfaceDisplacement")
Runtime type information.
surfaceDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &)
Construct from patch and internal field.
surfaceDisplacementPointPatchVectorField (const pointPatch &, const DimensionedField< vector, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField &, const pointPatch &, const DimensionedField< vector, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<vector> onto a new patch.
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField &)
Construct as copy.
virtual autoPtr< pointPatchVectorField > clone () const
Construct and return a clone.
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField &, const DimensionedField< vector, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchVectorField > clone (const DimensionedField< vector, pointMesh > &iF) const
Construct and return a clone setting internal field reference.
const searchableSurfaces & surfaces () const
Surface to follow. Demand loads surfaceNames.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Displacement fixed by projection onto triSurface. Use in a displacementMotionSolver as a bc on the pointDisplacement field.
Calculates the projection onto the surface according to the projectMode
NEAREST : nearest
POINTNORMAL : intersection with point normal
FIXEDNORMAL : intersection with fixed vector
This displacement is then clipped with the specified velocity * deltaT.
Optionally (intersection only) removes a component ("wedgePlane") to stay in 2D.
Needs:
geometry : dictionary with searchableSurfaces. (usually triSurfaceMeshes in constant/triSurface)
projectMode : see above
projectDirection : if projectMode = fixedNormal
wedgePlane : -1 or component to knock out of intersection normal
frozenPointsZone : empty or name of pointZone containing points that do not move
Source files
surfaceDisplacementPointPatchVectorField.H
surfaceDisplacementPointPatchVectorField.C
Definition at line 73 of file surfaceDisplacementPointPatchVectorField.H.
Member Enumeration Documentation
projectMode
enum projectMode
Enumerator
NEAREST
POINTNORMAL
FIXEDNORMAL
Definition at line 82 of file surfaceDisplacementPointPatchVectorField.H.
Constructor & Destructor Documentation
surfaceDisplacementPointPatchVectorField() [1/5]
surfaceDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 305 of file surfaceDisplacementPointPatchVectorField.C.
Referenced by surfaceDisplacementPointPatchVectorField::clone(), NamedEnum< directionType, 3 >::names(), and surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField().
surfaceDisplacementPointPatchVectorField() [2/5]
surfaceDisplacementPointPatchVectorField (const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 320 of file surfaceDisplacementPointPatchVectorField.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
surfaceDisplacementPointPatchVectorField() [3/5]
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField & ppf, const pointPatch & p, const DimensionedField< vector, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Construct by mapping given patchField<vector> onto a new patch.
Definition at line 347 of file surfaceDisplacementPointPatchVectorField.C.
References surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField().
surfaceDisplacementPointPatchVectorField() [4/5]
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField & ppf)
Construct as copy.
Definition at line 366 of file surfaceDisplacementPointPatchVectorField.C.
References surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField().
surfaceDisplacementPointPatchVectorField() [5/5]
surfaceDisplacementPointPatchVectorField (const surfaceDisplacementPointPatchVectorField & ppf, const DimensionedField< vector, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 382 of file surfaceDisplacementPointPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("surfaceDisplacement")
Runtime type information.
clone() [1/2]
virtual autoPtr<pointPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 166 of file surfaceDisplacementPointPatchVectorField.H.
References surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField().
clone() [2/2]
virtual autoPtr<pointPatchVectorField> clone (const DimensionedField< vector, pointMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 186 of file surfaceDisplacementPointPatchVectorField.H.
References surfaceDisplacementPointPatchVectorField::surfaceDisplacementPointPatchVectorField(), surfaceDisplacementPointPatchVectorField::surfaces(), surfaceDisplacementPointPatchVectorField::updateCoeffs(), and surfaceDisplacementPointPatchVectorField::write().
surfaces()
const searchableSurfaces & surfaces () const
Surface to follow. Demand loads surfaceNames.
Definition at line 400 of file surfaceDisplacementPointPatchVectorField.C.
References IOobject::MUST_READ, and IOobject::NO_WRITE.
Referenced by surfaceDisplacementPointPatchVectorField::clone(), and NamedEnum< directionType, 3 >::names().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 426 of file surfaceDisplacementPointPatchVectorField.C.
References TimeState::deltaTValue(), forAll, Foam::max(), mesh, Foam::min(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, Foam::operator==(), and objectRegistry::time().
Referenced by surfaceDisplacementPointPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 472 of file surfaceDisplacementPointPatchVectorField.C.
References token::END_STATEMENT, Foam::makePointPatchTypeField(), Foam::nl, word::null, write(), and Ostream::writeKeyword().
Referenced by surfaceDisplacementPointPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/fvMotionSolver/pointPatchFields/derived/surfaceDisplacement/surfaceDisplacementPointPatchVectorField.H
src/fvMotionSolver/pointPatchFields/derived/surfaceDisplacement/surfaceDisplacementPointPatchVectorField.C