OpenFOAM: cellSetOption Class Reference
cellSetOption Class Reference
Cell-set options abtract base class. Provides a base set of controls, e.g.:
Public Types
enum selectionModeType { smPoints, smCellSet, smCellZone, smAll }
Enumeration for selection mode types.
Public Member Functions
TypeName ("cellSetOption")
Runtime type information.
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~cellSetOption ()
Destructor.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const labelList & cells () const
Return const access to the cell set.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
virtual bool read (const dictionary &dict)
Read source dictionary.
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldi)
Set the applied flag to true for field index fieldi.
Switch & active ()
Return access to the source active flag.
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Static Public Attributes
static const NamedEnum< selectionModeType, 4 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Member Functions
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Protected Attributes
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Detailed Description
Cell-set options abtract base class. Provides a base set of controls, e.g.:
    type            scalarExplicitSource    // Source type
    active          on;                     // on/off switch
    scalarExplicitSourceCoeffs
    {
        timeStart       0.0;        // Start time
        duration        1000.0;     // Duration
        selectionMode   cellSet;    // cellSet, points, cellZone
        .
        .
        .
    }
Note
Source/sink options are to be added to the equation R.H.S.
Source files
cellSetOption.H
cellSetOption.C
cellSetOptionIO.C
Definition at line 72 of file cellSetOption.H.
Member Enumeration Documentation
selectionModeType
enum selectionModeType
Enumeration for selection mode types.
Enumerator
smPoints
smCellSet
smCellZone
smAll
Definition at line 81 of file cellSetOption.H.
Constructor & Destructor Documentation
cellSetOption()
cellSetOption (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 185 of file cellSetOption.C.
References Foam::decrIndent(), Foam::incrIndent(), Foam::Info, and Foam::read().
Referenced by cellSetOption::setCellSet().
~cellSetOption()
~cellSetOption () virtual
Destructor.
Definition at line 212 of file cellSetOption.C.
Member Function Documentation
setSelection()
void setSelection (const dictionary & dict) protected
Set the cellSet or points selection.
Definition at line 57 of file cellSetOption.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and dictionary::lookup().
setCellSet()
void setCellSet () protected
Set the cell set based on the user input selection mode.
Definition at line 92 of file cellSetOption.C.
References cellSetOption::cellSetOption(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::identity(), Foam::indent(), Foam::Info, HashSet< Key, Hash >::insert(), Foam::reduce(), Foam::returnReduce(), HashTable< T, Key, Hash >::toc(), and WarningInFunction.
TypeName()
TypeName ("cellSetOption")
Runtime type information.
timeStart() [1/2]
Foam::scalar timeStart () const inline
Return const access to the time start.
Definition at line 28 of file cellSetOptionI.H.
References cellSetOption::timeStart_.
duration() [1/2]
Foam::scalar duration () const inline
Return const access to the duration.
Definition at line 34 of file cellSetOptionI.H.
References cellSetOption::duration_.
inTimeLimits()
bool inTimeLimits (const scalar time) const inline
Return true if within time limits.
Definition at line 40 of file cellSetOptionI.H.
References cellSetOption::duration_, option::mesh_, fvMesh::time(), cellSetOption::timeStart_, and dimensioned< Type >::value().
selectionMode()
const Foam::fv::cellSetOption::selectionModeType & selectionMode () const inline
Return const access to the cell selection mode.
Definition at line 55 of file cellSetOptionI.H.
References cellSetOption::selectionMode_.
cellSetName()
const Foam::word & cellSetName () const inline
Return const access to the name of cell set for "cellSet".
selectionMode
Definition at line 61 of file cellSetOptionI.H.
References cellSetOption::cellSetName_.
V()
Foam::scalar V () const inline
Return const access to the total cell volume.
Definition at line 67 of file cellSetOptionI.H.
References cellSetOption::V_.
cells()
const Foam::labelList & cells () const inline
Return const access to the cell set.
Definition at line 73 of file cellSetOptionI.H.
References cellSetOption::cells_.
timeStart() [2/2]
Foam::scalar & timeStart () inline
Return access to the time start.
Definition at line 79 of file cellSetOptionI.H.
References cellSetOption::timeStart_.
duration() [2/2]
Foam::scalar & duration () inline
Return access to the duration.
Definition at line 85 of file cellSetOptionI.H.
References cellSetOption::duration_.
isActive()
bool isActive () virtual
Is the source active?
Reimplemented from option.
Definition at line 218 of file cellSetOption.C.
References option::isActive().
read()
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented from option.
Reimplemented in solidificationMeltingSource, rotorDiskSource, effectivenessHeatExchangerSource, CodedSource< Type >, actuationDiskSource, SemiImplicitSource< Type >, radialActuationDiskSource, meanVelocityForce, explicitPorositySource, fixedTemperatureConstraint, limitTemperature, limitVelocity, and FixedValueConstraint< Type >.
Definition at line 30 of file cellSetOptionIO.C.
References option::coeffs_, cellSetOption::duration_, dictionary::lookup(), option::read(), dictionary::readIfPresent(), and cellSetOption::timeStart_.
Referenced by limitVelocity::read(), limitTemperature::read(), fixedTemperatureConstraint::read(), explicitPorositySource::read(), actuationDiskSource::read(), effectivenessHeatExchangerSource::read(), and solidificationMeltingSource::read().
Member Data Documentation
selectionModeTypeNames_
const NamedEnum< fv::cellSetOption::selectionModeType, 4 > selectionModeTypeNames_ static
Word list of selection mode type names.
Definition at line 91 of file cellSetOption.H.
Referenced by NamedEnum< directionType, 3 >::names().
timeStart_
scalar timeStart_ protected
Time start.
Definition at line 99 of file cellSetOption.H.
Referenced by cellSetOption::inTimeLimits(), cellSetOption::read(), and cellSetOption::timeStart().
duration_
scalar duration_ protected
Duration.
Definition at line 102 of file cellSetOption.H.
Referenced by cellSetOption::duration(), cellSetOption::inTimeLimits(), and cellSetOption::read().
selectionMode_
selectionModeType selectionMode_ protected
Cell selection mode.
Definition at line 105 of file cellSetOption.H.
Referenced by cellSetOption::selectionMode().
cellSetName_
word cellSetName_ protected
Name of cell set for "cellSet" and "cellZone" selectionMode.
Definition at line 108 of file cellSetOption.H.
Referenced by cellSetOption::cellSetName().
points_
List<point> points_ protected
List of points for "points" selectionMode.
Definition at line 111 of file cellSetOption.H.
cells_
labelList cells_ protected
Set of cells to apply source to.
Definition at line 114 of file cellSetOption.H.
Referenced by cellSetOption::cells().
V_
scalar V_ protected
Sum of cell volumes.
Definition at line 117 of file cellSetOption.H.
Referenced by cellSetOption::V().
The documentation for this class was generated from the following files:
src/fvOptions/cellSetOption/cellSetOption.H
src/fvOptions/cellSetOption/cellSetOption.C
src/fvOptions/cellSetOption/cellSetOptionI.H
src/fvOptions/cellSetOption/cellSetOptionIO.C