OpenFOAM: buoyancyForce Class Reference
buoyancyForce Class Reference
Calculates and applies the buoyancy force rho*g to the momentum equation corresponding to the specified velocity field.
Public Member Functions
TypeName ("buoyancyForce")
Runtime type information.
buoyancyForce (const word &sourceName, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from explicit source name and mesh.
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
Add explicit contribution to compressible momentum equation.
virtual bool read (const dictionary &dict)
Read source dictionary.
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldi)
Set the applied flag to true for field index fieldi.
Switch & active ()
Return access to the source active flag.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Detailed Description
Calculates and applies the buoyancy force rho*g to the momentum equation corresponding to the specified velocity field.
Usage
Example usage:
buoyancyForceCoeffs
{
    fieldNames      (U);                    // Name of velocity field
}
Source files
buoyancyForce.H
buoyancyForce.C
Definition at line 61 of file buoyancyForce.H.
Constructor & Destructor Documentation
buoyancyForce()
buoyancyForce (const word & sourceName, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from explicit source name and mesh.
Definition at line 51 of file buoyancyForce.C.
References buoyancyForce::addSup(), Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Member Function Documentation
TypeName()
TypeName ("buoyancyForce")
Runtime type information.
addSup()
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Add explicit contribution to compressible momentum equation.
Reimplemented from option.
Definition at line 86 of file buoyancyForce.C.
Referenced by buoyancyForce::buoyancyForce().
read()
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented from option.
Definition at line 30 of file buoyancyForceIO.C.
References NotImplemented.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/buoyancyForce/buoyancyForce.H
src/fvOptions/sources/derived/buoyancyForce/buoyancyForce.C
src/fvOptions/sources/derived/buoyancyForce/buoyancyForceIO.C