OpenFOAM: genericPointPatchField< Type > Class Template Reference
genericPointPatchField< Type > Class Template Reference
A generic version of calculatedPointPatchField, useful as a fallback for handling unknown patch types.
Public Member Functions
TypeName ("generic")
Runtime type information.
genericPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
genericPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
genericPointPatchField (const genericPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
virtual autoPtr< pointPatchField< Type > > clone () const
Construct and return a clone.
genericPointPatchField (const genericPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from calculatedPointPatchField< Type >
TypeName ("calculated")
Runtime type information.
calculatedPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
calculatedPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
calculatedPointPatchField (const calculatedPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
calculatedPointPatchField (const calculatedPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
Public Member Functions inherited from pointPatchField< Type >
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType &>(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type, pointMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Additional Inherited Members
Public Types inherited from pointPatchField< Type >
typedef pointPatch Patch
typedef calculatedPointPatchField< Type > Calculated
Static Public Member Functions inherited from pointPatchField< Type >
static autoPtr< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new calculatedPointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Attributes inherited from pointPatchField< Type >
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Detailed Description
template<class Type>
class Foam::genericPointPatchField< Type >
A generic version of calculatedPointPatchField, useful as a fallback for handling unknown patch types.
Source files
genericPointPatchField.H
genericPointPatchField.C
Definition at line 51 of file genericPointPatchField.H.
Constructor & Destructor Documentation
genericPointPatchField() [1/4]
genericPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 33 of file genericPointPatchField.C.
References NotImplemented.
Referenced by genericPointPatchField< Type >::clone(), and genericPointPatchField< Type >::genericPointPatchField().
genericPointPatchField() [2/4]
genericPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 46 of file genericPointPatchField.C.
References token::compoundToken(), Foam::dynamicCast(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAllConstIter(), genericPointPatchField< Type >::genericPointPatchField(), token::isCompound(), token::isLabel(), token::isWord(), token::labelToken(), scalarField(), List< T >::size(), List< T >::transfer(), token::transferCompoundToken(), vectorField(), and token::wordToken().
genericPointPatchField() [3/4]
genericPointPatchField (const genericPointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Construct by mapping given patchField<Type> onto a new patch.
Definition at line 307 of file genericPointPatchField.C.
References forAllConstIter(), genericPointPatchField< Type >::genericPointPatchField(), scalarField(), and vectorField().
genericPointPatchField() [4/4]
genericPointPatchField (const genericPointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 392 of file genericPointPatchField.C.
References genericPointPatchField< Type >::autoMap().
Member Function Documentation
TypeName()
TypeName ("generic")
Runtime type information.
clone() [1/2]
virtual autoPtr<pointPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from calculatedPointPatchField< Type >.
Definition at line 100 of file genericPointPatchField.H.
References genericPointPatchField< Type >::genericPointPatchField().
clone() [2/2]
virtual autoPtr<pointPatchField<Type> > clone (const DimensionedField< Type, pointMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from calculatedPointPatchField< Type >.
Definition at line 120 of file genericPointPatchField.H.
References genericPointPatchField< Type >::autoMap(), genericPointPatchField< Type >::rmap(), and genericPointPatchField< Type >::write().
autoMap()
void autoMap (const pointPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented from pointPatchField< Type >.
Definition at line 412 of file genericPointPatchField.C.
References forAllIter, and genericPointPatchField< Type >::rmap().
Referenced by genericPointPatchField< Type >::clone(), and genericPointPatchField< Type >::genericPointPatchField().
rmap()
void rmap (const pointPatchField< Type > & ptf, const labelList & addr) virtual
Reverse map the given pointPatchField onto this pointPatchField.
Reimplemented from pointPatchField< Type >.
Definition at line 470 of file genericPointPatchField.C.
References forAllIter.
Referenced by genericPointPatchField< Type >::autoMap(), and genericPointPatchField< Type >::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from pointPatchField< Type >.
Definition at line 561 of file genericPointPatchField.C.
References forAllConstIter(), Foam::nl, and Ostream::writeKeyword().
Referenced by genericPointPatchField< Type >::clone().
The documentation for this class was generated from the following files:
src/genericPatchFields/genericPointPatchField/genericPointPatchField.H
src/genericPatchFields/genericPointPatchField/genericPointPatchField.C