OpenFOAM: SemiImplicitSource< Type > Class Template Reference
SemiImplicitSource< Type > Class Template Reference
Semi-implicit source, described using an input dictionary. The injection rate coefficients are specified as pairs of Su-Sp coefficients, i.e.
Public Types
enum volumeModeType { vmAbsolute, vmSpecific }
Enumeration for volume types.
Public Types inherited from cellSetOption
enum selectionModeType { smPoints, smCellSet, smCellZone, smAll }
Enumeration for selection mode types.
Public Member Functions
TypeName ("SemiImplicitSource")
Runtime type information.
SemiImplicitSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
const volumeModeType & volumeMode () const
Return const access to the volume mode.
const List< Tuple2< Type, scalar > > & injectionRate () const
Return const access to the source field values.
volumeModeType & volumeMode ()
Return access to the volume mode.
List< Tuple2< Type, scalar > > & injectionRate ()
Return access to the source field values.
virtual void addSup (fvMatrix< Type > &eqn, const label fieldi)
Add explicit contribution to equation.
virtual void addSup (const volScalarField &rho, fvMatrix< Type > &eqn, const label fieldi)
Add explicit contribution to compressible equation.
virtual bool read (const dictionary &dict)
Read source dictionary.
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
Runtime type information.
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~cellSetOption ()
Destructor.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const labelList & cells () const
Return const access to the cell set.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldi)
Set the applied flag to true for field index fieldi.
Switch & active ()
Return access to the source active flag.
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Static Public Attributes
static const wordList volumeModeTypeNames_
Word list of volume mode type names.
Static Public Attributes inherited from cellSetOption
static const NamedEnum< selectionModeType, 4 > selectionModeTypeNames_
Word list of selection mode type names.
Protected Member Functions
volumeModeType wordToVolumeModeType (const word &vtName) const
Helper function to convert from a word to a volumeModeType.
word volumeModeTypeToWord (const volumeModeType &vtType) const
Helper function to convert from a volumeModeType to a word.
void setFieldData (const dictionary &dict)
Set the local field data.
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
Protected Attributes
volumeModeType volumeMode_
Volume mode.
scalar VDash_
Volume normalisation.
List< Tuple2< Type, scalar > > injectionRate_
Source field values.
Protected Attributes inherited from cellSetOption
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of cell set for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Detailed Description
template<class Type>
class Foam::fv::SemiImplicitSource< Type >
Semi-implicit source, described using an input dictionary. The injection rate coefficients are specified as pairs of Su-Sp coefficients, i.e.
where
= net source for field 'x'
= explicit source contribution
= linearised implicit contribution
Example of the source specification:
    <Type>SemiImplicitSourceCoeffs
    {
        volumeMode      absolute; // specific
        injectionRateSuSp
        {
            k           (30.7 0);
            epsilon     (1.5  0);
        }
    }
Valid options for the volumeMode entry include:
absolute: values are given as <quantity>
specific: values are given as <quantity>/m3
See also
Foam::fvOption
Source files
SemiImplicitSource.H
SemiImplicitSource.C
Definition at line 95 of file SemiImplicitSource.H.
Member Enumeration Documentation
volumeModeType
enum volumeModeType
Enumeration for volume types.
Enumerator
vmAbsolute
vmSpecific
Definition at line 122 of file SemiImplicitSource.H.
Constructor & Destructor Documentation
SemiImplicitSource()
SemiImplicitSource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 111 of file SemiImplicitSource.C.
References SemiImplicitSource< Type >::addSup(), and Foam::read().
Referenced by SemiImplicitSource< Type >::setFieldData().
Member Function Documentation
wordToVolumeModeType()
Foam::fv::SemiImplicitSource< Type >::volumeModeType wordToVolumeModeType (const word & vtName) const protected
Helper function to convert from a word to a volumeModeType.
Definition at line 45 of file SemiImplicitSource.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, and SemiImplicitSource< Type >::volumeModeTypeToWord().
volumeModeTypeToWord()
Foam::word volumeModeTypeToWord (const volumeModeType & vtType) const protected
Helper function to convert from a volumeModeType to a word.
Definition at line 68 of file SemiImplicitSource.C.
Referenced by SemiImplicitSource< Type >::wordToVolumeModeType().
setFieldData()
void setFieldData (const dictionary & dict) protected
Set the local field data.
Definition at line 84 of file SemiImplicitSource.C.
References forAllConstIter(), dictionary::lookup(), SemiImplicitSource< Type >::SemiImplicitSource(), List< T >::size(), and dictionary::toc().
TypeName()
TypeName ("SemiImplicitSource< Type >")
Runtime type information.
volumeMode() [1/2]
const Foam::fv::SemiImplicitSource< Type >::volumeModeType & volumeMode () const inline
Return const access to the volume mode.
Definition at line 32 of file SemiImplicitSourceI.H.
injectionRate() [1/2]
const Foam::List< Foam::Tuple2< Type, Foam::scalar > > & injectionRate () const inline
Return const access to the source field values.
Definition at line 40 of file SemiImplicitSourceI.H.
volumeMode() [2/2]
Foam::fv::SemiImplicitSource< Type >::volumeModeType & volumeMode () inline
Return access to the volume mode.
Definition at line 48 of file SemiImplicitSourceI.H.
injectionRate() [2/2]
Foam::List< Foam::Tuple2< Type, Foam::scalar > > & injectionRate () inline
Return access to the source field values.
Definition at line 56 of file SemiImplicitSourceI.H.
addSup() [1/2]
void addSup (fvMatrix< Type > & eqn, const label fieldi) virtual
Add explicit contribution to equation.
Definition at line 131 of file SemiImplicitSource.C.
References DimensionedField< Type, GeoMesh >::dimensions(), fvMatrix< Type >::dimensions(), Foam::dimVolume, Foam::endl(), Foam::Info, psi, fvMatrix< Type >::psi(), Foam::fvc::Sp(), Foam::fvc::Su(), Foam::fvc::SuSp(), and Foam::Zero.
Referenced by SemiImplicitSource< Type >::SemiImplicitSource().
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< Type > & eqn, const label fieldi) virtual
Add explicit contribution to compressible equation.
Definition at line 194 of file SemiImplicitSource.C.
References SemiImplicitSource< Type >::addSup(), Foam::endl(), and Foam::Info.
Referenced by SemiImplicitSource< Type >::addSup().
read()
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented from cellSetOption.
Definition at line 31 of file SemiImplicitSourceIO.C.
References Foam::read().
Member Data Documentation
volumeModeTypeNames_
const Foam::wordList volumeModeTypeNames_ static
Word list of volume mode type names.
Definition at line 129 of file SemiImplicitSource.H.
volumeMode_
volumeModeType volumeMode_ protected
Volume mode.
Definition at line 137 of file SemiImplicitSource.H.
VDash_
scalar VDash_ protected
Volume normalisation.
Definition at line 140 of file SemiImplicitSource.H.
injectionRate_
List<Tuple2<Type, scalar> > injectionRate_ protected
Source field values.
Definition at line 143 of file SemiImplicitSource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/general/semiImplicitSource/SemiImplicitSource.H
src/fvOptions/sources/general/semiImplicitSource/SemiImplicitSource.C
src/fvOptions/sources/general/semiImplicitSource/SemiImplicitSourceI.H
src/fvOptions/sources/general/semiImplicitSource/SemiImplicitSourceIO.C