OpenFOAM: tabulated6DoFAcceleration Class Reference
tabulated6DoFAcceleration Class Reference
Tabulated 6DoF acceleration.
Public Member Functions
TypeName ("tabulated6DoFAcceleration")
Runtime type information.
tabulated6DoFAcceleration (const dictionary &accelerationCoeffs, const Time &runTime)
Construct from components.
virtual ~tabulated6DoFAcceleration ()
Destructor.
virtual Vector< vector > acceleration () const
Return the solid-body accelerations.
virtual bool read (const dictionary &accelerationCoeffs)
Update properties from given dictionary.
Detailed Description
Tabulated 6DoF acceleration.
Obtained by interpolating tabulated data for linear acceleration, angular velocity and angular acceleration.
Source files
tabulated6DoFAcceleration.H
tabulated6DoFAcceleration.C
Definition at line 53 of file tabulated6DoFAcceleration.H.
Constructor & Destructor Documentation
tabulated6DoFAcceleration()
tabulated6DoFAcceleration (const dictionary & accelerationCoeffs, const Time & runTime)
Construct from components.
Definition at line 42 of file tabulated6DoFAcceleration.C.
References Foam::read().
~tabulated6DoFAcceleration()
~tabulated6DoFAcceleration () virtual
Destructor.
Definition at line 56 of file tabulated6DoFAcceleration.C.
Member Function Documentation
TypeName()
TypeName ("tabulated6DoFAcceleration")
Runtime type information.
acceleration()
Foam::tabulated6DoFAcceleration::accelerationVectors acceleration () const virtual
Return the solid-body accelerations.
Definition at line 63 of file tabulated6DoFAcceleration.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, Foam::interpolateSplineXY(), and tabulated6DoFAcceleration::read().
read()
bool read (const dictionary & accelerationCoeffs) virtual
Update properties from given dictionary.
Definition at line 100 of file tabulated6DoFAcceleration.C.
References Foam::exit(), Foam::stringOps::expand(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), forAll, IOstream::good(), and List< T >::size().
Referenced by tabulated6DoFAcceleration::acceleration().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/tabulatedAccelerationSource/tabulated6DoFAcceleration/tabulated6DoFAcceleration.H
src/fvOptions/sources/derived/tabulatedAccelerationSource/tabulated6DoFAcceleration/tabulated6DoFAcceleration.C