OpenFOAM: bladeModel Class Reference
bladeModel Class Reference
Blade model class calculates: Linear interpolated blade twist and chord based on radial position Interpolation factor (for interpolating profile performance)
Public Member Functions
bladeModel (const dictionary &dict)
Constructor.
virtual ~bladeModel ()
Destructor.
const List< word > & profileName () const
Return const access to the profile name list.
const List< label > & profileID () const
Return const access to the profile ID list.
const List< scalar > & radius () const
Return const access to the radius list.
const List< scalar > & twist () const
Return const access to the twist list.
const List< scalar > & chord () const
Return const access to the chord list.
List< label > & profileID ()
Return non-const access to the profile ID list.
virtual void interpolate (const scalar radius, scalar &twist, scalar &chord, label &i1, label &i2, scalar &invDr) const
Return the twist and chord for a given radius.
Protected Member Functions
bool readFromFile () const
Return ture if file name is set.
void interpolateWeights (const scalar &xIn, const List< scalar > &values, label &i1, label &i2, scalar &ddx) const
Return the interpolation indices and gradient.
Protected Attributes
List< word > profileName_
Corresponding profile name per section.
List< label > profileID_
Corresponding profile ID per section.
List< scalar > radius_
Radius [m].
List< scalar > twist_
Twist [deg] on input, converted to [rad].
List< scalar > chord_
Chord [m].
fileName fName_
File name (optional)
Detailed Description
Blade model class calculates: Linear interpolated blade twist and chord based on radial position Interpolation factor (for interpolating profile performance)
Input in list format:
data ((profile1 (radius1 twist1 chord1)) (profile1 (radius2 twist2 chord2)));
where: radius [m] twist [deg], converted to [rad] internally chord [m]
Source files
bladeModel.H
bladeModel.C
Definition at line 64 of file bladeModel.H.
Constructor & Destructor Documentation
bladeModel()
bladeModel (const dictionary & dict)
Constructor.
Definition at line 89 of file bladeModel.C.
References bladeModel::chord_, Foam::degToRad(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), bladeModel::fName_, forAll, dictionary::lookup(), bladeModel::profileID_, bladeModel::profileName_, bladeModel::radius_, bladeModel::readFromFile(), List< T >::setSize(), List< T >::size(), and bladeModel::twist_.
~bladeModel()
~bladeModel () virtual
Destructor.
Definition at line 135 of file bladeModel.C.
Member Function Documentation
readFromFile()
bool readFromFile () const protected
Return ture if file name is set.
Definition at line 34 of file bladeModel.C.
References bladeModel::fName_, bladeModel::interpolateWeights(), and fileName::null.
Referenced by bladeModel::bladeModel().
interpolateWeights()
void interpolateWeights (const scalar & xIn, const List< scalar > & values, label & i1, label & i2, scalar & ddx) const protected
Return the interpolation indices and gradient.
Definition at line 41 of file bladeModel.C.
References List< T >::size().
Referenced by bladeModel::interpolate(), and bladeModel::readFromFile().
profileName()
const Foam::List< Foam::word > & profileName () const
Return const access to the profile name list.
Definition at line 141 of file bladeModel.C.
References bladeModel::profileName_.
profileID() [1/2]
const Foam::List< Foam::label > & profileID () const
Return const access to the profile ID list.
Definition at line 147 of file bladeModel.C.
References bladeModel::profileID_.
radius()
const Foam::List< Foam::scalar > & radius () const
Return const access to the radius list.
Definition at line 153 of file bladeModel.C.
References bladeModel::radius_.
twist()
const Foam::List< Foam::scalar > & twist () const
Return const access to the twist list.
Definition at line 159 of file bladeModel.C.
References bladeModel::twist_.
chord()
const Foam::List< Foam::scalar > & chord () const
Return const access to the chord list.
Definition at line 165 of file bladeModel.C.
References bladeModel::chord_.
profileID() [2/2]
Foam::List< Foam::label > & profileID ()
Return non-const access to the profile ID list.
Definition at line 171 of file bladeModel.C.
References bladeModel::interpolate(), and bladeModel::profileID_.
interpolate()
void interpolate (const scalar radius, scalar & twist, scalar & chord, label & i1, label & i2, scalar & invDr) const virtual
Return the twist and chord for a given radius.
Definition at line 178 of file bladeModel.C.
References bladeModel::chord_, bladeModel::interpolateWeights(), bladeModel::radius_, and bladeModel::twist_.
Referenced by bladeModel::profileID().
Member Data Documentation
profileName_
List<word> profileName_ protected
Corresponding profile name per section.
Definition at line 72 of file bladeModel.H.
Referenced by bladeModel::bladeModel(), and bladeModel::profileName().
profileID_
List<label> profileID_ protected
Corresponding profile ID per section.
Definition at line 75 of file bladeModel.H.
Referenced by bladeModel::bladeModel(), and bladeModel::profileID().
radius_
List<scalar> radius_ protected
Radius [m].
Definition at line 78 of file bladeModel.H.
Referenced by bladeModel::bladeModel(), bladeModel::interpolate(), and bladeModel::radius().
twist_
List<scalar> twist_ protected
Twist [deg] on input, converted to [rad].
Definition at line 81 of file bladeModel.H.
Referenced by bladeModel::bladeModel(), bladeModel::interpolate(), and bladeModel::twist().
chord_
List<scalar> chord_ protected
Chord [m].
Definition at line 84 of file bladeModel.H.
Referenced by bladeModel::bladeModel(), bladeModel::chord(), and bladeModel::interpolate().
fName_
fileName fName_ protected
File name (optional)
Definition at line 87 of file bladeModel.H.
Referenced by bladeModel::bladeModel(), and bladeModel::readFromFile().
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/bladeModel/bladeModel.H
src/fvOptions/sources/derived/rotorDiskSource/bladeModel/bladeModel.C