OpenFOAM: interRegionHeatTransferModel Class Reference
interRegionHeatTransferModel Class Reference abstract
Base class for inter region heat exchange. The derived classes must provide the heat transfer coeffisine (htc) which is used as follows in the energy equation.
Public Member Functions
TypeName ("interRegionHeatTransferModel")
Runtime type information.
interRegionHeatTransferModel (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from dictionary.
virtual ~interRegionHeatTransferModel ()
Destructor.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
const volScalarField & htc () const
Return the heat transfer coefficient.
const interRegionHeatTransferModel & nbrModel () const
Return const access to the neighbour model.
interRegionHeatTransferModel & nbrModel ()
Return access to the neighbour model.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
Source term to energy equation.
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
Source term to compressible energy equation.
virtual void calculateHtc ()=0
Calculate heat transfer coefficient.
virtual bool read (const dictionary &dict)
Read dictionary.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &field) const
Public Member Functions inherited from interRegionOption
TypeName ("interRegionOption")
Runtime type information.
interRegionOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from dictionary.
virtual ~interRegionOption ()
Destructor.
const word & nbrRegionName () const
Return const access to the neighbour region name.
const meshToMesh & meshInterp () const
Return const access to the mapToMap pointer.
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldi)
Set the applied flag to true for field index fieldi.
Switch & active ()
Return access to the source active flag.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Protected Member Functions
void setNbrModel ()
Set the neighbour interRegionHeatTransferModel.
void correct ()
Correct to calculate the inter-region heat transfer coefficient.
template<class Type >
tmp< Field< Type > > interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field) const
Interpolate field with nbrModel specified.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &field) const
Interpolate field without nbrModel specified.
template<class Type >
void interpolate (const interRegionHeatTransferModel &nbrModel, const Field< Type > &field, Field< Type > &result) const
Interpolate field with nbrModel specified.
template<class Type >
void interpolate (const Field< Type > &field, Field< Type > &result) const
Interpolate field without nbrModel specified.
Protected Member Functions inherited from interRegionOption
void setMapper ()
Set the mesh to mesh interpolation object.
Protected Attributes
word nbrModelName_
Name of the model in the neighbour mesh.
interRegionHeatTransferModel * nbrModel_
Pointer to neighbour interRegionHeatTransferModel.
bool firstIter_
First iteration.
label timeIndex_
Time index - used for updating htc.
volScalarField htc_
Heat transfer coefficient [W/m2/k] times area/volume [1/m].
bool semiImplicit_
Flag to activate semi-implicit coupling.
word TName_
Name of temperature field; default = "T".
word TNbrName_
Name of neighbour temperature field; default = "T".
Protected Attributes inherited from interRegionOption
bool master_
Master or slave region.
word nbrRegionName_
Name of the neighbour region to map.
autoPtr< meshToMesh > meshInterpPtr_
Mesh to mesh interpolation object.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Detailed Description
Base class for inter region heat exchange. The derived classes must provide the heat transfer coeffisine (htc) which is used as follows in the energy equation.
Definition at line 54 of file interRegionHeatTransferModel.H.
Constructor & Destructor Documentation
interRegionHeatTransferModel()
interRegionHeatTransferModel (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from dictionary.
Definition at line 108 of file interRegionHeatTransferModel.C.
Referenced by interRegionHeatTransferModel::correct().
~interRegionHeatTransferModel()
~interRegionHeatTransferModel () virtual
Destructor.
Definition at line 161 of file interRegionHeatTransferModel.C.
References interRegionHeatTransferModel::addSup().
Member Function Documentation
setNbrModel()
void setNbrModel () protected
Set the neighbour interRegionHeatTransferModel.
Definition at line 46 of file interRegionHeatTransferModel.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, fvOptions, objectRegistry::lookupObject(), Foam::name(), fvMesh::name(), Foam::nl, and fvMesh::time().
correct()
void correct () protected
Correct to calculate the inter-region heat transfer coefficient.
Definition at line 87 of file interRegionHeatTransferModel.C.
References Foam::interpolate(), and interRegionHeatTransferModel::interRegionHeatTransferModel().
interpolate() [1/6]
tmp<Field<Type> > interpolate (const interRegionHeatTransferModel & nbrModel, const Field< Type > & field) const protected
Interpolate field with nbrModel specified.
Referenced by interRegionHeatTransferModel::interpolate().
interpolate() [2/6]
tmp<Field<Type> > interpolate (const Field< Type > & field) const protected
Interpolate field without nbrModel specified.
interpolate() [3/6]
void interpolate (const interRegionHeatTransferModel & nbrModel, const Field< Type > & field, Field< Type > & result) const protected
Interpolate field with nbrModel specified.
Definition at line 58 of file interRegionHeatTransferModelTemplates.C.
References interRegionHeatTransferModel::interpolate(), meshToMesh::mapSrcToTgt(), and interRegionHeatTransferModel::meshInterp().
interpolate() [4/6]
void interpolate (const Field< Type > & field, Field< Type > & result) const protected
Interpolate field without nbrModel specified.
Definition at line 77 of file interRegionHeatTransferModelTemplates.C.
References Foam::MULES::interpolate().
TypeName()
TypeName ("interRegionHeatTransferModel")
Runtime type information.
nbrRegionName()
const Foam::word & nbrRegionName () const inline
Return const access to the neighbour region name.
Definition at line 29 of file interRegionHeatTransferModelI.H.
References interRegionOption::nbrRegionName_.
meshInterp()
const Foam::meshToMesh & meshInterp () const inline
Return const access to the mapToMap pointer.
Definition at line 36 of file interRegionHeatTransferModelI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and interRegionOption::meshInterpPtr_.
Referenced by interRegionHeatTransferModel::interpolate().
htc()
const Foam::volScalarField & htc () const inline
Return the heat transfer coefficient.
Definition at line 50 of file interRegionHeatTransferModelI.H.
References interRegionHeatTransferModel::htc_.
nbrModel() [1/2]
const Foam::fv::interRegionHeatTransferModel & nbrModel () const inline
Return const access to the neighbour model.
Definition at line 57 of file interRegionHeatTransferModelI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and interRegionHeatTransferModel::nbrModel_.
nbrModel() [2/2]
Foam::fv::interRegionHeatTransferModel & nbrModel () inline
Return access to the neighbour model.
Definition at line 71 of file interRegionHeatTransferModelI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and interRegionHeatTransferModel::nbrModel_.
addSup() [1/2]
void addSup (fvMatrix< scalar > & eqn, const label fieldi) virtual
Source term to energy equation.
Reimplemented from option.
Definition at line 168 of file interRegionHeatTransferModel.C.
References correct, basicThermo::Cp(), basicThermo::Cpv(), dictionaryName::dictName(), Foam::dimEnergy, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimMass, Foam::dimTemperature, Foam::fvc::domainIntegrate(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, he, Foam::Info, Foam::interpolate(), objectRegistry::lookupObject(), fvMesh::name(), IOobject::NO_READ, IOobject::NO_WRITE, fvMatrix< Type >::psi(), GeometricField< Type, PatchField, GeoMesh >::ref(), Foam::fvm::Sp(), Foam::T(), fvMesh::time(), Foam::type(), dimensioned< Type >::value(), and Ostream::write().
Referenced by interRegionHeatTransferModel::~interRegionHeatTransferModel().
addSup() [2/2]
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Source term to compressible energy equation.
Reimplemented from option.
Definition at line 265 of file interRegionHeatTransferModel.C.
calculateHtc()
virtual void calculateHtc () pure virtual
Calculate heat transfer coefficient.
Implemented in variableHeatTransfer, tabulatedHeatTransfer, and constantHeatTransfer.
read()
bool read (const dictionary & dict) virtual
Read dictionary.
Reimplemented from interRegionOption.
Reimplemented in variableHeatTransfer, tabulatedHeatTransfer, and constantHeatTransfer.
Definition at line 30 of file interRegionHeatTransferModelIO.C.
References interRegionOption::read().
Referenced by constantHeatTransfer::read(), tabulatedHeatTransfer::read(), and variableHeatTransfer::read().
interpolate() [5/6]
Foam::tmp<Foam::Field<Type> > interpolate (const interRegionHeatTransferModel & nbrModel, const Field< Type > & field) const
Definition at line 29 of file interRegionHeatTransferModelTemplates.C.
References interRegionHeatTransferModel::interpolate(), meshToMesh::mapSrcToTgt(), and interRegionHeatTransferModel::meshInterp().
interpolate() [6/6]
Foam::tmp<Foam::Field<Type> > interpolate (const Field< Type > & field) const
Definition at line 48 of file interRegionHeatTransferModelTemplates.C.
References Foam::MULES::interpolate(), and interRegionHeatTransferModel::interpolate().
Member Data Documentation
nbrModelName_
word nbrModelName_ protected
Name of the model in the neighbour mesh.
Definition at line 63 of file interRegionHeatTransferModel.H.
nbrModel_
interRegionHeatTransferModel* nbrModel_ protected
Pointer to neighbour interRegionHeatTransferModel.
Definition at line 66 of file interRegionHeatTransferModel.H.
Referenced by interRegionHeatTransferModel::nbrModel().
firstIter_
bool firstIter_ protected
First iteration.
Definition at line 69 of file interRegionHeatTransferModel.H.
timeIndex_
label timeIndex_ protected
Time index - used for updating htc.
Definition at line 72 of file interRegionHeatTransferModel.H.
htc_
volScalarField htc_ protected
Heat transfer coefficient [W/m2/k] times area/volume [1/m].
Definition at line 75 of file interRegionHeatTransferModel.H.
Referenced by interRegionHeatTransferModel::htc().
semiImplicit_
bool semiImplicit_ protected
Flag to activate semi-implicit coupling.
Definition at line 78 of file interRegionHeatTransferModel.H.
TName_
word TName_ protected
Name of temperature field; default = "T".
Definition at line 81 of file interRegionHeatTransferModel.H.
TNbrName_
word TNbrName_ protected
Name of neighbour temperature field; default = "T".
Definition at line 84 of file interRegionHeatTransferModel.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/interRegion/interRegionHeatTransfer/interRegionHeatTransferModel/interRegionHeatTransferModel.H
src/fvOptions/sources/interRegion/interRegionHeatTransfer/interRegionHeatTransferModel/interRegionHeatTransferModel.C
src/fvOptions/sources/interRegion/interRegionHeatTransfer/interRegionHeatTransferModel/interRegionHeatTransferModelI.H
src/fvOptions/sources/interRegion/interRegionHeatTransfer/interRegionHeatTransferModel/interRegionHeatTransferModelIO.C
src/fvOptions/sources/interRegion/interRegionHeatTransfer/interRegionHeatTransferModel/interRegionHeatTransferModelTemplates.C