OpenFOAM: trimModel Class Reference
trimModel Class Reference abstract
Trim model base class.
Public Member Functions
TypeName ("trimModel")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, trimModel, dictionary,(const fv::rotorDiskSource &rotor, const dictionary &dict),(rotor, dict))
trimModel (const fv::rotorDiskSource &rotor, const dictionary &dict, const word &name)
Construct from components.
virtual ~trimModel ()
Destructor.
virtual void read (const dictionary &dict)
Read.
virtual tmp< scalarField > thetag () const =0
Return the geometric angle of attack [rad].
virtual void correct (const vectorField &U, vectorField &force)=0
Correct the model.
virtual void correct (const volScalarField rho, const vectorField &U, vectorField &force)=0
Correct the model for compressible flow.
Static Public Member Functions
static autoPtr< trimModel > New (const fv::rotorDiskSource &rotor, const dictionary &dict)
Return a reference to the selected trim model.
Protected Attributes
const fv::rotorDiskSource & rotor_
Reference to the rotor source model.
const word name_
Name of model.
dictionary coeffs_
Coefficients dictionary.
Detailed Description
Trim model base class.
Source files
trimModel.H
trimModel.C
Definition at line 50 of file trimModel.H.
Constructor & Destructor Documentation
trimModel()
trimModel (const fv::rotorDiskSource & rotor, const dictionary & dict, const word & name)
Construct from components.
Definition at line 40 of file trimModel.C.
References Foam::read().
~trimModel()
~trimModel () virtual
Destructor.
Definition at line 55 of file trimModel.C.
Member Function Documentation
TypeName()
TypeName ("trimModel")
Run-time type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , trimModel , dictionary , (const fv::rotorDiskSource &rotor, const dictionary &dict) , (rotor, dict))
New()
Foam::autoPtr< Foam::trimModel > New (const fv::rotorDiskSource & rotor, const dictionary & dict) static
Return a reference to the selected trim model.
Definition at line 31 of file trimModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
read()
void read (const dictionary & dict) virtual
Read.
Reimplemented in targetCoeffTrim, and fixedTrim.
Definition at line 61 of file trimModel.C.
References dictionary::subDict().
Referenced by fixedTrim::read(), and targetCoeffTrim::read().
thetag()
virtual tmp<scalarField> thetag () const pure virtual
Return the geometric angle of attack [rad].
Implemented in targetCoeffTrim, and fixedTrim.
correct() [1/2]
virtual void correct (const vectorField & U, vectorField & force) pure virtual
Correct the model.
Implemented in targetCoeffTrim, and fixedTrim.
correct() [2/2]
virtual void correct (const volScalarField rho, const vectorField & U, vectorField & force) pure virtual
Correct the model for compressible flow.
Implemented in targetCoeffTrim, and fixedTrim.
Member Data Documentation
rotor_
const fv::rotorDiskSource& rotor_ protected
Reference to the rotor source model.
Definition at line 58 of file trimModel.H.
name_
const word name_ protected
Name of model.
Definition at line 61 of file trimModel.H.
coeffs_
dictionary coeffs_ protected
Coefficients dictionary.
Definition at line 64 of file trimModel.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/trimModel/trimModel/trimModel.H
src/fvOptions/sources/derived/rotorDiskSource/trimModel/trimModel/trimModel.C
src/fvOptions/sources/derived/rotorDiskSource/trimModel/trimModel/trimModelNew.C