OpenFOAM: distributionModel Class Reference
distributionModel Class Reference abstract
Public Member Functions
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, cachedRandom &rndGen),(dict, rndGen))
Declare runtime constructor selection table.
distributionModel (const word &name, const dictionary &dict, cachedRandom &rndGen)
Construct from dictionary.
distributionModel (const distributionModel &p)
Construct copy.
virtual autoPtr< distributionModel > clone () const =0
Construct and return a clone.
virtual ~distributionModel ()
Destructor.
virtual scalar sample () const =0
Sample the distributionModel.
virtual scalar minValue () const =0
Return the minimum value.
virtual scalar maxValue () const =0
Return the maximum value.
virtual scalar meanValue () const =0
Return the maximum value.
Static Public Member Functions
static autoPtr< distributionModel > New (const dictionary &dict, cachedRandom &rndGen)
Selector.
Protected Member Functions
virtual void check () const
Check that the distribution model is valid.
Protected Attributes
const dictionary distributionModelDict_
Coefficients dictionary.
cachedRandom & rndGen_
Reference to the random number generator.
Detailed Description
Definition at line 69 of file distributionModel.H.
Constructor & Destructor Documentation
distributionModel() [1/2]
distributionModel (const word & name, const dictionary & dict, cachedRandom & rndGen)
Construct from dictionary.
Definition at line 66 of file distributionModel.C.
Referenced by distributionModel::check().
distributionModel() [2/2]
distributionModel (const distributionModel & p)
Construct copy.
Definition at line 78 of file distributionModel.C.
~distributionModel()
~distributionModel () virtual
Destructor.
Definition at line 89 of file distributionModel.C.
Member Function Documentation
check()
void check () const protected virtual
Check that the distribution model is valid.
Definition at line 42 of file distributionModel.C.
References Foam::abort(), distributionModel::distributionModel(), Foam::FatalError, FatalErrorInFunction, maxValue, minValue, Foam::nl, and Foam::type().
TypeName()
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , distributionModel , dictionary , (const dictionary &dict, cachedRandom &rndGen) , (dict, rndGen))
Declare runtime constructor selection table.
clone()
virtual autoPtr<distributionModel> clone () const pure virtual
Construct and return a clone.
Implemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
New()
Foam::autoPtr< Foam::distributionModels::distributionModel > New (const dictionary & dict, cachedRandom & rndGen) static
Selector.
Definition at line 32 of file distributionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), Foam::nl, and rndGen().
sample()
virtual scalar sample () const pure virtual
Sample the distributionModel.
Implemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
minValue()
virtual scalar minValue () const pure virtual
Return the minimum value.
Implemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
maxValue()
virtual scalar maxValue () const pure virtual
Return the maximum value.
Implemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
meanValue()
virtual scalar meanValue () const pure virtual
Return the maximum value.
Implemented in multiNormal, normal, RosinRammler, general, exponential, uniform, and fixedValue.
Member Data Documentation
distributionModelDict_
const dictionary distributionModelDict_ protected
Coefficients dictionary.
Definition at line 77 of file distributionModel.H.
rndGen_
cachedRandom& rndGen_ protected
Reference to the random number generator.
Definition at line 80 of file distributionModel.H.
Referenced by uniform::sample(), exponential::sample(), general::sample(), RosinRammler::sample(), multiNormal::sample(), and normal::sample().
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/distributionModel/distributionModel.H
src/lagrangian/distributionModels/distributionModel/distributionModel.C
src/lagrangian/distributionModels/distributionModel/distributionModelNew.C