OpenFOAM: particle< Type > Class Template Reference
particle< Type > Class Template Reference
Base particle class.
Classes
class iNew
Factory class to read-construct particles used for.
class TrackingData
Public Member Functions
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label celli, bool doCellFacePt=true)
Construct from components, tetFacei_ and tetPti_ are not.
particle (const polyMesh &mesh, Istream &, bool readFields=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with refernce to a new mesh.
virtual autoPtr< particle > clone () const
Construct a clone.
virtual ~particle ()
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const vector & position () const
Return current particle position.
vector & position ()
Return current particle position.
label & cell ()
Return current cell particle is in.
label cell () const
Return current cell particle is in.
label & tetFace ()
Return current tet face particle is in.
label tetFace () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in.
label tetPt () const
Return current tet face particle is in.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
tetPointRef currentTet () const
Return the geometry of the current tet that the.
vector normal () const
Return the normal of the tri on tetFacei_ for the.
vector oldNormal () const
Return the normal of the tri on tetFacei_ for the.
label & face ()
Return current face particle is on otherwise -1.
label face () const
Return current face particle is on otherwise -1.
bool softImpact () const
Return the impact model to be used, soft or hard (default).
scalar currentTime () const
Return the particle current time.
void initCellFacePt ()
Check the stored cell value (setting if necessary) and.
bool onBoundary () const
Is the particle on the boundary/(or outside the domain)?
bool internalFace (const label facei) const
Is this global face an internal face?
bool boundaryFace (const label facei) const
Is this global face a boundary face?
label patch (const label facei) const
Which patch is particle on.
label patchFace (const label patchi, const label facei) const
Which face of this patch is this particle on.
scalar & stepFraction ()
Return the fraction of time-step completed.
scalar stepFraction () const
Return the fraction of time-step completed.
label origProc () const
Return const access to the originating processor id.
label & origProc ()
Return the originating processor id for manipulation.
label origId () const
Return const access to the particle id on originating processor.
label & origId ()
Return the particle id on originating processor for manipulation.
template<class TrackData >
label track (const vector &endPosition, TrackData &td)
Track particle to end of trajectory.
template<class TrackData >
scalar trackToFace (const vector &endPosition, TrackData &td)
Track particle to a given position and returns 1.0 if the.
label faceInterpolation () const
Return the index of the face to be used in the interpolation.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
virtual scalar wallImpactDistance (const vector &n) const
The nearest distance to a wall that.
template<class TrackData >
void prepareForParallelTransfer (const label patchi, TrackData &td)
Convert global addressing to the processor patch.
template<class TrackData >
void correctAfterParallelTransfer (const label patchi, TrackData &td)
Convert processor patch addressing to the global equivalents.
void writePosition (Ostream &) const
Write the particle position and cell.
template<class TrackData >
Foam::label track (const vector &endPosition, TrackData &td)
template<class TrackData >
Foam::scalar trackToFace (const vector &endPosition, TrackData &td)
Static Public Member Functions
static string propertyList ()
template<class CloudType >
static void readFields (CloudType &c)
Read the fields associated with the owner cloud.
template<class CloudType >
static void writeFields (const CloudType &c)
Write the fields associated with the owner cloud.
Static Public Attributes
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provode unique ID.
static const scalar trackingCorrectionTol = 1e-5
Fraction of distance to tet centre to move a particle to.
static const scalar lambdaDistanceToleranceCoeff = 1e3*SMALL
Fraction of the cell volume to use in determining tolerance values.
static const scalar minStepFractionTol = 1e5*SMALL
Minimum stepFraction tolerance.
Protected Member Functions
void findTris (const vector &position, DynamicList< label > &faceList, const tetPointRef &tet, const FixedList< vector, 4 > &tetAreas, const FixedList< label, 4 > &tetPlaneBasePtIs, const scalar tol) const
Find the tet tri faces between position and tet centre.
scalar tetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label celli, const label tetFacei, const label tetPti, const scalar tol) const
Find the lambda value for the line to-from across the.
scalar movingTetLambda (const vector &from, const vector &to, const label triI, const vector &tetArea, const label tetPlaneBasePtI, const label celli, const label tetFacei, const label tetPti, const scalar tol) const
Find the lambda value for a moving tri face.
void tetNeighbour (label triI)
Modify the tet owner data by crossing triI.
void crossEdgeConnectedFace (const label &celli, label &tetFacei, label &tetPti, const edge &e)
Cross the from the given face across the given edge of the.
template<class CloudType >
void hitWallFaces (const CloudType &td, const vector &from, const vector &to, scalar &lambdaMin, tetIndices &closestTetIs)
template<class TrackData >
void hitFace (TrackData &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
bool hitPatch (const polyPatch &, TrackData &td, const label patchi, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWedgePatch (const wedgePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackData >
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitSymmetryPatch (const symmetryPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitCyclicPatch (const cyclicPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackData >
void hitCyclicAMIPatch (const cyclicAMIPolyPatch &, TrackData &td, const vector &direction)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &tetIs)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
Protected Attributes
const polyMesh & mesh_
Reference to the polyMesh database.
vector position_
Position of particle.
label celli_
Index of the cell it is in.
label facei_
Face index if the particle is on a face otherwise -1.
scalar stepFraction_
Fraction of time-step completed.
label tetFacei_
Index of the face that owns the decomposed tet that the.
label tetPti_
Index of the point on the face that defines the decomposed.
label origProc_
Originating processor id.
label origId_
Local particle id on originating processor.
Friends
Ostream & operator<< (Ostream &, const particle &)
bool operator== (const particle &pA, const particle &pB)
bool operator!= (const particle &pA, const particle &pB)
Detailed Description
template<class Type>
class Foam::particle< Type >
Base particle class.
Definition at line 78 of file particle.H.
Constructor & Destructor Documentation
particle() [1/5]
particle (const polyMesh & mesh, const vector & position, const label celli, const label tetFacei, const label tetPti)
Construct from components.
Definition at line 48 of file particle.C.
Referenced by particle< Type >::clone(), and particle< Type >::iNew::operator()().
particle() [2/5]
particle (const polyMesh & mesh, const vector & position, const label celli, bool doCellFacePt = true)
Construct from components, tetFacei_ and tetPti_ are not.
supplied so they will be deduced by a search
Definition at line 69 of file particle.C.
particle() [3/5]
particle (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 46 of file particleIO.C.
References IOstream::ASCII, particle< Type >::celli_, IOstream::check(), particle< Type >::facei_, IOstream::format(), particle< Type >::origId_, particle< Type >::origProc_, particle< Type >::position_, Istream::read(), particle< Type >::stepFraction_, particle< Type >::tetFacei_, and particle< Type >::tetPti_.
particle() [4/5]
particle (const particle< Type > & p)
Construct as a copy.
Definition at line 93 of file particle.C.
particle() [5/5]
particle (const particle< Type > & p, const polyMesh & mesh)
Construct as a copy with refernce to a new mesh.
Definition at line 107 of file particle.C.
~particle()
virtual ~particle () inline virtual
Destructor.
Definition at line 394 of file particle.H.
References particle< Type >::boundaryFace(), Foam::constant::universal::c, particle< Type >::cell(), particle< Type >::correctAfterParallelTransfer(), particle< Type >::currentTet(), particle< Type >::currentTetIndices(), particle< Type >::currentTime(), particle< Type >::face(), particle< Type >::faceInterpolation(), particle< Type >::getNewParticleID(), particle< Type >::initCellFacePt(), particle< Type >::internalFace(), particle< Type >::mesh(), n, particle< Type >::normal(), particle< Type >::oldNormal(), particle< Type >::onBoundary(), particle< Type >::operator!=, particle< Type >::operator<<, particle< Type >::operator==, particle< Type >::origId(), particle< Type >::origProc(), particle< Type >::patch(), particle< Type >::patchFace(), patchi, particle< Type >::position(), particle< Type >::prepareForParallelTransfer(), particle< Type >::readFields(), particle< Type >::softImpact(), particle< Type >::stepFraction(), Foam::T(), particle< Type >::tetFace(), particle< Type >::tetPt(), particle< Type >::track(), particle< Type >::trackToFace(), particle< Type >::transformProperties(), particle< Type >::wallImpactDistance(), particle< Type >::writeFields(), and particle< Type >::writePosition().
Member Function Documentation
findTris()
void findTris (const vector & position, DynamicList< label > & faceList, const tetPointRef & tet, const FixedList< vector, 4 > & tetAreas, const FixedList< label, 4 > & tetPlaneBasePtIs, const scalar tol) const inline protected
Find the tet tri faces between position and tet centre.
Definition at line 32 of file particleI.H.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), tetrahedron< Point, PointRef >::centre(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), lambda(), and particle< Type >::tetLambda().
Referenced by particle< Type >::trackToFace().
tetLambda()
Foam::scalar tetLambda (const vector & from, const vector & to, const label triI, const vector & tetArea, const label tetPlaneBasePtI, const label celli, const label tetFacei, const label tetPti, const scalar tol) const inline protected
Find the lambda value for the line to-from across the.
given tri face, where p = from + lambda*(to - from)
Definition at line 69 of file particleI.H.
References Foam::mag(), particle< Type >::movingTetLambda(), and Foam::sign().
Referenced by particle< Type >::findTris(), particle< Type >::hitWallFaces(), and particle< Type >::trackToFace().
movingTetLambda()
Foam::scalar movingTetLambda (const vector & from, const vector & to, const label triI, const vector & tetArea, const label tetPlaneBasePtI, const label celli, const label tetFacei, const label tetPti, const scalar tol) const inline protected
Find the lambda value for a moving tri face.
Definition at line 141 of file particleI.H.
References tetrahedron< Point, PointRef >::a(), Foam::constant::physicoChemical::b, tetrahedron< Point, PointRef >::b(), Foam::constant::universal::c, tetrahedron< Point, PointRef >::c(), tetrahedron< Point, PointRef >::d(), Foam::mag(), n, tetIndices::oldTet(), Foam::sign(), Foam::sqr(), Foam::sqrt(), tetIndices::tet(), and Foam::Zero.
Referenced by particle< Type >::tetLambda().
tetNeighbour()
void tetNeighbour (label triI) inline protected
Modify the tet owner data by crossing triI.
Definition at line 321 of file particleI.H.
References Foam::abort(), particle< Type >::celli_, particle< Type >::crossEdgeConnectedFace(), f(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), particle< Type >::mesh_, pFaces, UList< T >::rcIndex(), List< T >::size(), polyMesh::tetBasePtIs(), particle< Type >::tetFacei_, and particle< Type >::tetPti_.
Referenced by particle< Type >::trackToFace().
crossEdgeConnectedFace()
void crossEdgeConnectedFace (const label & celli, label & tetFacei, label & tetPti, const edge & e) inline protected
Cross the from the given face across the given edge of the.
given cell to find the resulting face and tetPti
Definition at line 458 of file particleI.H.
References Foam::abort(), primitiveMesh::cells(), face::edgeDirection(), edge::end(), f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), forAll, particle< Type >::mesh_, Foam::neg(), Foam::meshTools::otherFace(), pFaces, List< T >::size(), edge::start(), and polyMesh::tetBasePtIs().
Referenced by wallBoundedParticle::crossEdgeConnectedFace(), and particle< Type >::tetNeighbour().
hitWallFaces()
void hitWallFaces (const CloudType & td, const vector & from, const vector & to, scalar & lambdaMin, tetIndices & closestTetIs) inline protected
Hit wall faces in the current cell if the wallImpactDistance is non-zero. They may not be in Different tets to the current.
Definition at line 717 of file particleTemplates.C.
References triangle< Point, PointRef >::a(), triangle< Point, PointRef >::b(), polyMesh::boundaryMesh(), triangle< Point, PointRef >::c(), Cloud< ParticleType >::cellHasWallFaces(), particle< Type >::celli_, primitiveMesh::cells(), primitiveMesh::cellVolumes(), tetrahedron< Point, PointRef >::centre(), f(), tetIndices::faceBasePt(), particle< Type >::facei_, polyMesh::faces(), polyMeshTetDecomposition::faceTetIndices(), tetIndices::faceTri(), forAll, intersection::FULL_RAY, Cloud< ParticleType >::hasWallImpactDistance(), particle< Type >::internalFace(), triangle< Point, PointRef >::intersection(), lambda(), particle< Type >::lambdaDistanceToleranceCoeff, Foam::mag(), Foam::max(), particle< Type >::mesh_, Foam::min(), polyMesh::moving(), n, primitiveMesh::nInternalFaces(), triangle< Point, PointRef >::normal(), tetIndices::oldFaceTri(), p, patches, polyBoundaryMesh::patchID(), pFaces, particle< Type >::stepFraction_, tetIndices::tet(), particle< Type >::tetLambda(), tetIndices::tetPt(), and Foam::Zero.
Referenced by particle< Type >::trackToFace().
hitFace()
void hitFace (TrackData & td) protected
Overridable function to handle the particle hitting a face.
Definition at line 926 of file particleTemplates.C.
References particle< Type >::hitPatch().
hitPatch() [1/2]
bool hitPatch (const polyPatch & , TrackData & td, const label patchi, const scalar trackFraction, const tetIndices & tetIs) protected
Overridable function to handle the particle hitting a.
patch. Executed before other patch-hitting functions. trackFraction is passed in to allow mesh motion to interpolate in time to the correct face state.
Definition at line 932 of file particleTemplates.C.
References particle< Type >::hitWedgePatch().
Referenced by particle< Type >::hitFace().
hitWedgePatch()
void hitWedgePatch (const wedgePolyPatch & wpp, TrackData & td) protected
Overridable function to handle the particle hitting a wedgePatch.
Definition at line 946 of file particleTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, particle< Type >::hitSymmetryPlanePatch(), Foam::I, Foam::mag(), particle< Type >::normal(), and particle< Type >::transformProperties().
Referenced by particle< Type >::hitPatch().
hitSymmetryPlanePatch()
void hitSymmetryPlanePatch (const symmetryPlanePolyPatch & spp, TrackData & td) protected
Overridable function to handle the particle hitting a.
symmetryPlanePatch
Definition at line 964 of file particleTemplates.C.
References particle< Type >::hitSymmetryPatch(), Foam::I, Foam::mag(), particle< Type >::normal(), and particle< Type >::transformProperties().
Referenced by particle< Type >::hitWedgePatch().
hitSymmetryPatch()
void hitSymmetryPatch (const symmetryPolyPatch & spp, TrackData & td) protected
Overridable function to handle the particle hitting a.
symmetryPatch
Definition at line 978 of file particleTemplates.C.
References particle< Type >::hitCyclicPatch(), Foam::I, Foam::mag(), particle< Type >::normal(), and particle< Type >::transformProperties().
Referenced by particle< Type >::hitSymmetryPlanePatch().
hitCyclicPatch()
void hitCyclicPatch (const cyclicPolyPatch & cpp, TrackData & td) protected
Overridable function to handle the particle hitting a cyclicPatch.
Definition at line 992 of file particleTemplates.C.
References particle< Type >::celli_, particle< Type >::facei_, polyMesh::faceOwner(), polyMesh::faces(), coupledPolyPatch::forwardT(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::mesh_, cyclicPolyPatch::neighbPatch(), coupledPolyPatch::parallel(), particle< Type >::position_, s(), coupledPolyPatch::separated(), coupledPolyPatch::separation(), List< T >::size(), Foam::T(), particle< Type >::tetFacei_, particle< Type >::tetPti_, cyclicPolyPatch::transformGlobalFace(), cyclicPolyPatch::transformPosition(), particle< Type >::transformProperties(), and polyPatch::whichFace().
Referenced by particle< Type >::hitSymmetryPatch().
hitCyclicAMIPatch()
void hitCyclicAMIPatch (const cyclicAMIPolyPatch & cpp, TrackData & td, const vector & direction) protected
Overridable function to handle the particle hitting a cyclicAMIPatch.
Definition at line 1040 of file particleTemplates.C.
References particle< Type >::celli_, Foam::endl(), particle< Type >::facei_, polyMesh::faceOwner(), polyMesh::faces(), coupledPolyPatch::forwardT(), particle< Type >::mesh_, patchIdentifier::name(), cyclicAMIPolyPatch::neighbPatch(), coupledPolyPatch::parallel(), cyclicAMIPolyPatch::pointFace(), particle< Type >::position_, s(), coupledPolyPatch::separated(), coupledPolyPatch::separation(), List< T >::size(), polyPatch::start(), Foam::T(), particle< Type >::tetFacei_, particle< Type >::tetPti_, particle< Type >::transformProperties(), and WarningInFunction.
Referenced by particle< Type >::hitCyclicPatch().
hitProcessorPatch()
void hitProcessorPatch (const processorPolyPatch & , TrackData & td) protected
Overridable function to handle the particle hitting a.
processorPatch
Definition at line 1104 of file particleTemplates.C.
References particle< Type >::hitWallPatch().
hitWallPatch()
void hitWallPatch (const wallPolyPatch & , TrackData & td, const tetIndices & tetIs) protected
Overridable function to handle the particle hitting a wallPatch.
Definition at line 1110 of file particleTemplates.C.
Referenced by particle< Type >::hitProcessorPatch().
hitPatch() [2/2]
void hitPatch (const polyPatch & , TrackData & td) protected
Overridable function to handle the particle hitting a.
general patch
Definition at line 1119 of file particleTemplates.C.
TypeName()
TypeName ("particle< Type >")
Runtime type information.
propertyList()
static string propertyList () inline static
Definition at line 319 of file particle.H.
clone()
virtual autoPtr<particle> clone () const inline virtual
Construct a clone.
Reimplemented in molecule, wallBoundedParticle, streamLineParticle, wallBoundedStreamLineParticle, solidParticle, trackedParticle, findCellParticle, indexedParticle, and passiveParticle.
Definition at line 368 of file particle.H.
References particle< Type >::mesh_, and particle< Type >::particle().
getNewParticleID()
Foam::label getNewParticleID () const inline
Get unique particle creation id.
Definition at line 566 of file particleI.H.
References Foam::endl(), Foam::labelMax, particle< Type >::particleCount_, and WarningInFunction.
Referenced by particle< Type >::~particle().
mesh()
const Foam::polyMesh & mesh () const inline
Return the mesh database.
Definition at line 580 of file particleI.H.
References particle< Type >::mesh_.
Referenced by findCellParticle::trackingData::cellToEnd(), trackedParticle::trackingData::trackingData(), and particle< Type >::~particle().
position() [1/2]
const Foam::vector & position () const inline
Return current particle position.
Definition at line 586 of file particleI.H.
References particle< Type >::position_.
Referenced by nearWallFields::calcAddressing(), findCellParticle::trackingData::cellToEnd(), wallBoundedParticle::isTriAlongTrack(), streamLineParticle::move(), wallBoundedStreamLineParticle::move(), molecule::move(), Foam::operator<<(), Foam::reconstructLagrangianPositions(), wallBoundedParticle::trackFaceTri(), wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData(), streamLineParticle::trackingData::trackingData(), wallBoundedStreamLineParticle::trackingData::trackingData(), trackedParticle::trackingData::trackingData(), particle< Type >::trackToFace(), and particle< Type >::~particle().
position() [2/2]
Foam::vector & position () inline
Return current particle position.
Definition at line 592 of file particleI.H.
References particle< Type >::position_.
cell() [1/2]
Foam::label & cell () inline
Return current cell particle is in.
Definition at line 604 of file particleI.H.
References particle< Type >::celli_.
Referenced by wallBoundedParticle::crossEdgeConnectedFace(), Foam::reconstructLagrangianPositions(), and particle< Type >::~particle().
cell() [2/2]
Foam::label cell () const inline
Return current cell particle is in.
Definition at line 598 of file particleI.H.
References particle< Type >::celli_.
tetFace() [1/2]
Foam::label & tetFace () inline
Return current tet face particle is in.
Definition at line 616 of file particleI.H.
References particle< Type >::tetFacei_.
Referenced by wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), wallBoundedParticle::currentEdge(), and particle< Type >::~particle().
tetFace() [2/2]
Foam::label tetFace () const inline
Return current tet face particle is in.
Definition at line 610 of file particleI.H.
References particle< Type >::tetFacei_.
tetPt() [1/2]
Foam::label & tetPt () inline
Return current tet face particle is in.
Definition at line 628 of file particleI.H.
References particle< Type >::tetPti_.
Referenced by wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), and particle< Type >::~particle().
tetPt() [2/2]
Foam::label tetPt () const inline
Return current tet face particle is in.
Definition at line 622 of file particleI.H.
References particle< Type >::tetPti_.
currentTetIndices()
Foam::tetIndices currentTetIndices () const inline
Return the indices of the current tet that the.
particle occupies.
Definition at line 634 of file particleI.H.
References particle< Type >::celli_, particle< Type >::mesh_, particle< Type >::tetFacei_, and particle< Type >::tetPti_.
Referenced by particle< Type >::currentTet(), wallBoundedParticle::isTriAlongTrack(), particle< Type >::normal(), particle< Type >::oldNormal(), wallBoundedParticle::trackFaceTri(), and particle< Type >::~particle().
currentTet()
Foam::tetPointRef currentTet () const inline
Return the geometry of the current tet that the.
particle occupies.
Definition at line 640 of file particleI.H.
References particle< Type >::currentTetIndices(), particle< Type >::mesh_, and tetIndices::tet().
Referenced by Foam::operator<<(), particle< Type >::trackToFace(), and particle< Type >::~particle().
normal()
Foam::vector normal () const inline
Return the normal of the tri on tetFacei_ for the.
current tet.
Definition at line 646 of file particleI.H.
References particle< Type >::currentTetIndices(), tetIndices::faceTri(), particle< Type >::mesh_, and triangle< Point, PointRef >::normal().
Referenced by particle< Type >::hitSymmetryPatch(), particle< Type >::hitSymmetryPlanePatch(), molecule::hitWallPatch(), particle< Type >::hitWedgePatch(), and particle< Type >::~particle().
oldNormal()
Foam::vector oldNormal () const inline
Return the normal of the tri on tetFacei_ for the.
current tet at the start of the timestep, i.e. based on oldPoints
Definition at line 652 of file particleI.H.
References particle< Type >::currentTetIndices(), particle< Type >::mesh_, triangle< Point, PointRef >::normal(), and tetIndices::oldFaceTri().
Referenced by particle< Type >::~particle().
face() [1/2]
Foam::label & face () inline
Return current face particle is on otherwise -1.
Definition at line 664 of file particleI.H.
References particle< Type >::facei_.
Referenced by wallBoundedParticle::crossEdgeConnectedFace(), and particle< Type >::~particle().
face() [2/2]
Foam::label face () const inline
Return current face particle is on otherwise -1.
Definition at line 658 of file particleI.H.
References particle< Type >::facei_.
softImpact()
bool softImpact () const inline
Return the impact model to be used, soft or hard (default).
Definition at line 855 of file particleI.H.
Referenced by particle< Type >::~particle().
currentTime()
Foam::scalar currentTime () const inline
Return the particle current time.
Definition at line 861 of file particleI.H.
References TimeState::deltaTValue(), particle< Type >::mesh_, particle< Type >::stepFraction_, objectRegistry::time(), and dimensioned< Type >::value().
Referenced by particle< Type >::~particle().
initCellFacePt()
void initCellFacePt () inline
Check the stored cell value (setting if necessary) and.
initialise the tetFace and tetPt values
Definition at line 670 of file particleI.H.
References Foam::abort(), primitiveMesh::cellCentres(), particle< Type >::celli_, Foam::endl(), Foam::FatalError, FatalErrorInFunction, polyMesh::findCellFacePt(), polyMesh::findTetFacePt(), Foam::mag(), particle< Type >::mesh_, Foam::nl, primitiveMesh::pointInCellBB(), particle< Type >::position_, particle< Type >::tetFacei_, particle< Type >::tetPti_, particle< Type >::trackingCorrectionTol, and WarningInFunction.
Referenced by particle< Type >::~particle().
onBoundary()
bool onBoundary () const inline
Is the particle on the boundary/(or outside the domain)?
Definition at line 813 of file particleI.H.
References particle< Type >::facei_, particle< Type >::mesh_, and primitiveMesh::nInternalFaces().
Referenced by particle< Type >::track(), and particle< Type >::~particle().
internalFace()
bool internalFace (const label facei) const inline
Is this global face an internal face?
Definition at line 869 of file particleI.H.
References primitiveMesh::isInternalFace(), and particle< Type >::mesh_.
Referenced by particle< Type >::boundaryFace(), particle< Type >::hitWallFaces(), particle< Type >::trackToFace(), and particle< Type >::~particle().
boundaryFace()
bool boundaryFace (const label facei) const inline
Is this global face a boundary face?
Definition at line 875 of file particleI.H.
References particle< Type >::internalFace().
Referenced by particle< Type >::~particle().
patch()
Foam::label patch (const label facei) const inline
Which patch is particle on.
Definition at line 881 of file particleI.H.
References polyMesh::boundaryMesh(), particle< Type >::mesh_, particle< Type >::patchFace(), and polyBoundaryMesh::whichPatch().
Referenced by particle< Type >::trackToFace(), and particle< Type >::~particle().
patchFace()
Foam::label patchFace (const label patchi, const label facei) const inline
Which face of this patch is this particle on.
Definition at line 888 of file particleI.H.
References polyMesh::boundaryMesh(), particle< Type >::mesh_, and patchi.
Referenced by particle< Type >::patch(), and particle< Type >::~particle().
stepFraction() [1/2]
Foam::scalar & stepFraction () inline
Return the fraction of time-step completed.
Definition at line 819 of file particleI.H.
References particle< Type >::stepFraction_.
Referenced by wallBoundedStreamLineParticle::move(), molecule::move(), and particle< Type >::~particle().
stepFraction() [2/2]
Foam::scalar stepFraction () const inline
Return the fraction of time-step completed.
Definition at line 825 of file particleI.H.
References particle< Type >::stepFraction_.
origProc() [1/2]
Foam::label origProc () const inline
Return const access to the originating processor id.
Definition at line 831 of file particleI.H.
References particle< Type >::origProc_.
Referenced by Foam::operator==(), particle< Type >::writeFields(), and particle< Type >::~particle().
origProc() [2/2]
Foam::label & origProc () inline
Return the originating processor id for manipulation.
Definition at line 837 of file particleI.H.
References particle< Type >::origProc_.
origId() [1/2]
Foam::label origId () const inline
Return const access to the particle id on originating processor.
Definition at line 843 of file particleI.H.
References particle< Type >::origId_.
Referenced by Foam::operator==(), particle< Type >::readFields(), particle< Type >::writeFields(), and particle< Type >::~particle().
origId() [2/2]
Foam::label & origId () inline
Return the particle id on originating processor for manipulation.
Definition at line 849 of file particleI.H.
References particle< Type >::origId_.
track() [1/2]
label track (const vector & endPosition, TrackData & td)
Track particle to end of trajectory.
or until it hits the boundary. On entry 'stepFraction()' should be set to the fraction of the time-step at which the tracking starts and on exit it contains the fraction of the time-step completed. Returns the boundary face index if the track stops at the boundary, -1 otherwise.
Referenced by particle< Type >::~particle().
trackToFace() [1/2]
scalar trackToFace (const vector & endPosition, TrackData & td)
Track particle to a given position and returns 1.0 if the.
trajectory is completed without hitting a face otherwise stops at the face and returns the fraction of the trajectory completed. on entry 'stepFraction()' should be set to the fraction of the time-step at which the tracking starts.
Referenced by molecule::move(), particle< Type >::track(), and particle< Type >::~particle().
faceInterpolation()
Foam::label faceInterpolation () const inline
Return the index of the face to be used in the interpolation.
routine
Definition at line 897 of file particleI.H.
References particle< Type >::facei_.
Referenced by particle< Type >::~particle().
transformProperties() [1/2]
void transformProperties (const tensor & T) virtual
Transform the physical properties of the particle.
according to the given transformation tensor
Reimplemented in molecule, and solidParticle.
Definition at line 123 of file particle.C.
Referenced by particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), particle< Type >::hitSymmetryPatch(), particle< Type >::hitSymmetryPlanePatch(), particle< Type >::hitWedgePatch(), solidParticle::transformProperties(), molecule::transformProperties(), and particle< Type >::~particle().
transformProperties() [2/2]
void transformProperties (const vector & separation) virtual
Transform the physical properties of the particle.
according to the given separation vector
Reimplemented in molecule, and solidParticle.
Definition at line 127 of file particle.C.
wallImpactDistance()
Foam::scalar wallImpactDistance (const vector & n) const virtual
The nearest distance to a wall that.
the particle can be in the n direction
Reimplemented in solidParticle.
Definition at line 131 of file particle.C.
Referenced by particle< Type >::~particle().
prepareForParallelTransfer()
void prepareForParallelTransfer (const label patchi, TrackData & td)
Convert global addressing to the processor patch.
local equivalents
Definition at line 41 of file particleTemplates.C.
References particle< Type >::correctAfterParallelTransfer().
Referenced by particle< Type >::~particle().
correctAfterParallelTransfer()
void correctAfterParallelTransfer (const label patchi, TrackData & td)
Convert processor patch addressing to the global equivalents.
and set the celli to the face-neighbour
Definition at line 53 of file particleTemplates.C.
References polyPatch::faceCells(), coupledPolyPatch::forwardT(), coupledPolyPatch::parallel(), patchi, s(), coupledPolyPatch::separated(), coupledPolyPatch::separation(), List< T >::size(), polyPatch::start(), T, and coupledPolyPatch::transformPosition().
Referenced by particle< Type >::prepareForParallelTransfer(), and particle< Type >::~particle().
readFields()
void readFields (CloudType & c) static
Read the fields associated with the owner cloud.
Definition at line 129 of file particleTemplates.C.
References Cloud< ParticleType >::checkFieldIOobject(), Cloud< ParticleType >::fieldIOobject(), forAllIter, IOobject::MUST_READ, particle< Type >::origId(), particle< Type >::origId_, particle< Type >::origProc_, p, and Cloud< ParticleType >::size().
Referenced by findCellParticle::trackingData::cellToEnd(), indexedParticleCloud::indexedParticleCloud(), passiveParticleCloud::passiveParticleCloud(), solidParticle::readFields(), streamLineParticle::readFields(), wallBoundedParticle::readFields(), molecule::readFields(), trackedParticle::trackingData::trackingData(), and particle< Type >::~particle().
writeFields()
void writeFields (const CloudType & c) static
Write the fields associated with the owner cloud.
Definition at line 159 of file particleTemplates.C.
References Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), IOobject::NO_READ, particle< Type >::origId(), particle< Type >::origProc(), Cloud< ParticleType >::size(), and IOPosition< CloudType >::write().
Referenced by solidParticle::writeFields(), streamLineParticle::writeFields(), wallBoundedParticle::writeFields(), molecule::writeFields(), and particle< Type >::~particle().
writePosition()
void writePosition (Ostream & os) const
Write the particle position and cell.
Definition at line 89 of file particleIO.C.
References IOstream::ASCII, particle< Type >::celli_, IOstream::check(), IOstream::format(), particle< Type >::position_, token::SPACE, and Ostream::write().
Referenced by particle< Type >::~particle().
track() [2/2]
Foam::label track (const vector & endPosition, TrackData & td)
Definition at line 188 of file particleTemplates.C.
References particle< Type >::facei_, particle< Type >::onBoundary(), particle< Type >::stepFraction_, and particle< Type >::trackToFace().
trackToFace() [2/2]
Foam::scalar trackToFace (const vector & endPosition, TrackData & td)
Definition at line 204 of file particleTemplates.C.
References Foam::abort(), polyMesh::boundaryMesh(), tetIndices::cell(), primitiveMesh::cellCentres(), particle< Type >::celli_, primitiveMesh::cellVolumes(), tetrahedron< Point, PointRef >::centre(), particle< Type >::currentTet(), UList< T >::empty(), Foam::endl(), f(), tetIndices::face(), particle< Type >::facei_, polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), tetIndices::faceTri(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), particle< Type >::findTris(), forAll, particle< Type >::hitWallFaces(), particle< Type >::internalFace(), particle< Type >::lambdaDistanceToleranceCoeff, Foam::mag(), particle< Type >::mesh_, polyMesh::moving(), primitiveMesh::nInternalFaces(), triangle< Point, PointRef >::normal(), p, particle< Type >::patch(), patches, patchi, polyBoundaryMesh::patchID(), pFaces, polyMesh::points(), particle< Type >::position(), particle< Type >::position_, Foam::Pout, tetrahedron< Point, PointRef >::Sa(), tetrahedron< Point, PointRef >::Sb(), tetrahedron< Point, PointRef >::Sc(), tetrahedron< Point, PointRef >::Sd(), List< T >::size(), tetIndices::tet(), polyMesh::tetBasePtIs(), particle< Type >::tetFacei_, particle< Type >::tetLambda(), particle< Type >::tetNeighbour(), particle< Type >::tetPti_, and particle< Type >::trackingCorrectionTol.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const particle< Type > &) friend
Referenced by particle< Type >::~particle().
operator==
bool operator== (const particle< Type > & pA, const particle< Type > & pB) friend
Referenced by particle< Type >::~particle().
operator!=
bool operator!= (const particle< Type > & pA, const particle< Type > & pB) friend
Referenced by particle< Type >::~particle().
Member Data Documentation
mesh_
const polyMesh& mesh_ protected
Reference to the polyMesh database.
Definition at line 137 of file particle.H.
Referenced by findCellParticle::clone(), trackedParticle::clone(), solidParticle::clone(), wallBoundedStreamLineParticle::clone(), streamLineParticle::clone(), wallBoundedParticle::clone(), molecule::clone(), particle< Type >::clone(), wallBoundedParticle::crossDiagonalEdge(), wallBoundedParticle::crossEdgeConnectedFace(), particle< Type >::crossEdgeConnectedFace(), wallBoundedParticle::currentEdge(), particle< Type >::currentTet(), particle< Type >::currentTetIndices(), particle< Type >::currentTime(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), particle< Type >::hitWallFaces(), particle< Type >::initCellFacePt(), particle< Type >::internalFace(), wallBoundedParticle::isTriAlongTrack(), particle< Type >::mesh(), wallBoundedStreamLineParticle::move(), particle< Type >::normal(), particle< Type >::oldNormal(), particle< Type >::onBoundary(), wallBoundedStreamLineParticle::iNew::operator()(), wallBoundedParticle::iNew::operator()(), particle< Type >::patch(), particle< Type >::patchFace(), particle< Type >::tetNeighbour(), wallBoundedParticle::trackFaceTri(), and particle< Type >::trackToFace().
position_
vector position_ protected
Position of particle.
Definition at line 140 of file particle.H.
Referenced by particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), particle< Type >::initCellFacePt(), Foam::operator<<(), particle< Type >::particle(), particle< Type >::position(), molecule::setSitePositions(), particle< Type >::trackToFace(), molecule::transformProperties(), and particle< Type >::writePosition().
celli_
label celli_ protected
Index of the cell it is in.
Definition at line 143 of file particle.H.
Referenced by particle< Type >::cell(), particle< Type >::currentTetIndices(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), particle< Type >::hitWallFaces(), particle< Type >::initCellFacePt(), Foam::operator<<(), particle< Type >::particle(), particle< Type >::tetNeighbour(), particle< Type >::trackToFace(), and particle< Type >::writePosition().
facei_
label facei_ protected
Face index if the particle is on a face otherwise -1.
Definition at line 146 of file particle.H.
Referenced by particle< Type >::face(), particle< Type >::faceInterpolation(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), particle< Type >::hitWallFaces(), particle< Type >::onBoundary(), Foam::operator<<(), particle< Type >::particle(), particle< Type >::track(), and particle< Type >::trackToFace().
stepFraction_
scalar stepFraction_ protected
Fraction of time-step completed.
Definition at line 149 of file particle.H.
Referenced by particle< Type >::currentTime(), particle< Type >::hitWallFaces(), Foam::operator<<(), particle< Type >::particle(), particle< Type >::stepFraction(), and particle< Type >::track().
tetFacei_
label tetFacei_ protected
Index of the face that owns the decomposed tet that the.
particle is in
Definition at line 153 of file particle.H.
Referenced by particle< Type >::currentTetIndices(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), particle< Type >::initCellFacePt(), Foam::operator<<(), particle< Type >::particle(), particle< Type >::tetFace(), particle< Type >::tetNeighbour(), and particle< Type >::trackToFace().
tetPti_
label tetPti_ protected
Index of the point on the face that defines the decomposed.
tet that the particle is in. Relative to the face base point.
Definition at line 158 of file particle.H.
Referenced by particle< Type >::currentTetIndices(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), particle< Type >::initCellFacePt(), Foam::operator<<(), particle< Type >::particle(), particle< Type >::tetNeighbour(), particle< Type >::tetPt(), and particle< Type >::trackToFace().
origProc_
label origProc_ protected
Originating processor id.
Definition at line 161 of file particle.H.
Referenced by Foam::operator<<(), particle< Type >::origProc(), particle< Type >::particle(), and particle< Type >::readFields().
origId_
label origId_ protected
Local particle id on originating processor.
Definition at line 164 of file particle.H.
Referenced by Foam::operator<<(), particle< Type >::origId(), particle< Type >::particle(), and particle< Type >::readFields().
propertyList_
Foam::string propertyList_ = Foam::particle::propertyList() static
String representation of properties.
Definition at line 319 of file particle.H.
particleCount_
Foam::label particleCount_ = 0 static
Cumulative particle counter - used to provode unique ID.
Definition at line 319 of file particle.H.
Referenced by particle< Type >::getNewParticleID().
trackingCorrectionTol
const Foam::scalar trackingCorrectionTol = 1e-5 static
Fraction of distance to tet centre to move a particle to.
'rescue' it from a tracking problem
Definition at line 326 of file particle.H.
Referenced by particle< Type >::initCellFacePt(), sampledSet::pushIn(), and particle< Type >::trackToFace().
lambdaDistanceToleranceCoeff
const Foam::scalar lambdaDistanceToleranceCoeff = 1e3*SMALL static
Fraction of the cell volume to use in determining tolerance values.
for the denominator and numerator of lambda
Definition at line 330 of file particle.H.
Referenced by particle< Type >::hitWallFaces(), and particle< Type >::trackToFace().
minStepFractionTol
const Foam::scalar minStepFractionTol = 1e5*SMALL static
Minimum stepFraction tolerance.
Definition at line 333 of file particle.H.
The documentation for this class was generated from the following files:
src/lagrangian/basic/particle/particle.H
src/lagrangian/basic/particle/particle.C
src/lagrangian/basic/particle/particleI.H
src/lagrangian/basic/particle/particleIO.C
src/lagrangian/basic/particle/particleTemplates.C