OpenFOAM: multiNormal Class Reference
multiNormal Class Reference
Public Member Functions
TypeName ("multiNormal")
Runtime type information.
multiNormal (const dictionary &dict, cachedRandom &rndGen)
Construct from components.
multiNormal (const multiNormal &p)
Construct copy.
virtual autoPtr< distributionModel > clone () const
Construct and return a clone.
virtual ~multiNormal ()
Destructor.
virtual scalar sample () const
Sample the distributionModel.
virtual scalar minValue () const
Return the minimum value.
virtual scalar maxValue () const
Return the maximum value.
virtual scalar meanValue () const
Return the mean value.
Public Member Functions inherited from distributionModel
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, cachedRandom &rndGen),(dict, rndGen))
Declare runtime constructor selection table.
distributionModel (const word &name, const dictionary &dict, cachedRandom &rndGen)
Construct from dictionary.
distributionModel (const distributionModel &p)
Construct copy.
virtual ~distributionModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from distributionModel
static autoPtr< distributionModel > New (const dictionary &dict, cachedRandom &rndGen)
Selector.
Protected Member Functions inherited from distributionModel
virtual void check () const
Check that the distribution model is valid.
Protected Attributes inherited from distributionModel
const dictionary distributionModelDict_
Coefficients dictionary.
cachedRandom & rndGen_
Reference to the random number generator.
Detailed Description
Definition at line 55 of file multiNormal.H.
Constructor & Destructor Documentation
multiNormal() [1/2]
multiNormal (const dictionary & dict, cachedRandom & rndGen)
Construct from components.
Definition at line 43 of file multiNormal.C.
References Foam::exp(), Foam::max(), n, s(), x, and y.
Referenced by multiNormal::clone().
multiNormal() [2/2]
multiNormal (const multiNormal & p)
Construct copy.
Definition at line 84 of file multiNormal.C.
~multiNormal()
~multiNormal () virtual
Destructor.
Definition at line 98 of file multiNormal.C.
Referenced by multiNormal::clone().
Member Function Documentation
TypeName()
TypeName ("multiNormal")
Runtime type information.
clone()
virtual autoPtr<distributionModel> clone () const inline virtual
Construct and return a clone.
Implements distributionModel.
Definition at line 93 of file multiNormal.H.
References multiNormal::maxValue(), multiNormal::meanValue(), multiNormal::minValue(), multiNormal::multiNormal(), multiNormal::sample(), and multiNormal::~multiNormal().
sample()
Foam::scalar sample () const virtual
Sample the distributionModel.
Implements distributionModel.
Definition at line 104 of file multiNormal.C.
References Foam::exp(), n, nu, p, distributionModel::rndGen_, s(), cachedRandom::sample01(), Foam::constant::physicoChemical::sigma, List< T >::size(), success, x, and y.
Referenced by multiNormal::clone().
minValue()
Foam::scalar minValue () const virtual
Return the minimum value.
Implements distributionModel.
Definition at line 136 of file multiNormal.C.
Referenced by multiNormal::clone().
maxValue()
Foam::scalar maxValue () const virtual
Return the maximum value.
Implements distributionModel.
Definition at line 142 of file multiNormal.C.
Referenced by multiNormal::clone().
meanValue()
Foam::scalar meanValue () const virtual
Return the mean value.
Implements distributionModel.
Definition at line 148 of file multiNormal.C.
References forAll.
Referenced by multiNormal::clone().
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/multiNormal/multiNormal.H
src/lagrangian/distributionModels/multiNormal/multiNormal.C