OpenFOAM: coalCloudList Class Reference
coalCloudList Class Reference
Public Member Functions
coalCloudList (const volScalarField &rho, const volVectorField &U, const dimensionedVector &g, const SLGThermo &slgThermo)
void evolve ()
Evolve the cloud collection.
tmp< volVectorField::Internal > UTrans () const
Return const reference to momentum source.
tmp< fvVectorMatrix > SU (volVectorField &U) const
Return tmp momentum source term.
tmp< volScalarField::Internal > hsTrans () const
Sensible enthalpy transfer [J/kg].
tmp< fvScalarMatrix > Sh (volScalarField &hs) const
Return sensible enthalpy source term [J/kg/m3/s].
tmp< fvScalarMatrix > SYi (const label i, volScalarField &Yi) const
Return mass source term for specie i - specie eqn.
tmp< volScalarField::Internal > rhoTrans () const
Return total mass transfer [kg/m3].
tmp< volScalarField::Internal > Srho () const
Return tmp total mass source for carrier phase.
tmp< volScalarField::Internal > Srho (const label i) const
Return tmp total mass source for carrier phase specie i.
tmp< fvScalarMatrix > Srho (volScalarField &rho) const
Return total mass source term [kg/m3/s].
Public Member Functions inherited from PtrList< coalCloud >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< coalCloud > &)
Copy constructor.
PtrList (const PtrList< coalCloud > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< coalCloud >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< coalCloud > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< coalCloud > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (coalCloud *)
Append an element at the end of the list.
void append (const autoPtr< coalCloud > &)
void append (const tmp< coalCloud > &)
void transfer (PtrList< coalCloud > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< coalCloud > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< coalCloud > set (const label, coalCloud *)
Set element to given T* and return old element (can be nullptr)
autoPtr< coalCloud > set (const label, const autoPtr< coalCloud > &)
Set element to given autoPtr<T> and return old element.
autoPtr< coalCloud > set (const label, const tmp< coalCloud > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< coalCloud > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< coalCloud >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Definition at line 42 of file coalCloudList.H.
Constructor & Destructor Documentation
coalCloudList()
coalCloudList (const volScalarField & rho, const volVectorField & U, const dimensionedVector & g, const SLGThermo & slgThermo)
Definition at line 31 of file coalCloudList.C.
References Foam::endl(), forAllConstIter(), Foam::Info, dictionary::lookup(), Foam::name(), setSize(), and HashTable< T, Key, Hash >::size().
Member Function Documentation
evolve()
void evolve ()
Evolve the cloud collection.
Definition at line 83 of file coalCloudList.C.
References forAll, and UPtrList< T >::operator[]().
UTrans()
Foam::tmp< Foam::DimensionedField< Foam::vector, Foam::volMesh > > UTrans () const inline
Return const reference to momentum source.
Definition at line 31 of file coalCloudListI.H.
References Foam::dimMass, Foam::dimVelocity, fld(), forAll, IOobject::NO_READ, IOobject::NO_WRITE, UPtrList< T >::operator[](), tmp< T >::ref(), coalCloudList::SU(), fvMesh::time(), Time::timeName(), and Foam::Zero.
SU()
Foam::tmp< Foam::fvVectorMatrix > SU (volVectorField & U) const inline
Return tmp momentum source term.
Definition at line 62 of file coalCloudListI.H.
References Foam::dimForce, forAll, UPtrList< T >::operator[](), and tmp< T >::ref().
Referenced by coalCloudList::UTrans().
hsTrans()
Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > hsTrans () const inline
Sensible enthalpy transfer [J/kg].
Definition at line 79 of file coalCloudListI.H.
References Foam::dimEnergy, fld(), forAll, IOobject::NO_READ, IOobject::NO_WRITE, UPtrList< T >::operator[](), tmp< T >::ref(), coalCloudList::Sh(), fvMesh::time(), and Time::timeName().
Sh()
Foam::tmp< Foam::fvScalarMatrix > Sh (volScalarField & hs) const inline
Return sensible enthalpy source term [J/kg/m3/s].
Definition at line 110 of file coalCloudListI.H.
References Foam::dimEnergy, Foam::dimTime, forAll, UPtrList< T >::operator[](), tmp< T >::ref(), and coalCloudList::SYi().
Referenced by coalCloudList::hsTrans().
SYi()
Foam::tmp< Foam::fvScalarMatrix > SYi (const label i, volScalarField & Yi) const inline
Return mass source term for specie i - specie eqn.
Definition at line 127 of file coalCloudListI.H.
References Foam::dimMass, Foam::dimTime, forAll, UPtrList< T >::operator[](), and tmp< T >::ref().
Referenced by coalCloudList::Sh().
rhoTrans()
Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > rhoTrans () const inline
Return total mass transfer [kg/m3].
Definition at line 145 of file coalCloudListI.H.
References Foam::dimMass, fld(), forAll, IOobject::NO_READ, IOobject::NO_WRITE, UPtrList< T >::operator[](), tmp< T >::ref(), fvMesh::time(), and Time::timeName().
Srho() [1/3]
Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > Srho () const inline
Return tmp total mass source for carrier phase.
fully explicit
Definition at line 181 of file coalCloudListI.H.
References Foam::dimDensity, Foam::dimTime, fld(), forAll, IOobject::NO_READ, IOobject::NO_WRITE, UPtrList< T >::operator[](), tmp< T >::ref(), fvMesh::time(), and Time::timeName().
Referenced by coalCloudList::Srho().
Srho() [2/3]
Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > Srho (const label i) const inline
Return tmp total mass source for carrier phase specie i.
fully explicit
Definition at line 213 of file coalCloudListI.H.
References Foam::dimDensity, Foam::dimTime, fld(), forAll, IOobject::NO_READ, IOobject::NO_WRITE, UPtrList< T >::operator[](), tmp< T >::ref(), coalCloudList::Srho(), fvMesh::time(), and Time::timeName().
Srho() [3/3]
Foam::tmp< Foam::fvScalarMatrix > Srho (volScalarField & rho) const inline
Return total mass source term [kg/m3/s].
Definition at line 246 of file coalCloudListI.H.
References Foam::dimMass, Foam::dimTime, forAll, UPtrList< T >::operator[](), and tmp< T >::ref().
The documentation for this class was generated from the following files:
src/lagrangian/coalCombustion/coalCloudList/coalCloudList.H
src/lagrangian/coalCombustion/coalCloudList/coalCloudList.C
src/lagrangian/coalCombustion/coalCloudList/coalCloudListI.H