OpenFOAM: COxidationIntrinsicRate< CloudType > Class Template Reference
COxidationIntrinsicRate< CloudType > Class Template Reference
Intrinsic char surface reaction mndel.
Public Member Functions
TypeName ("COxidationIntrinsicRate")
Runtime type information.
COxidationIntrinsicRate (const dictionary &dict, CloudType &owner)
Construct from dictionary.
COxidationIntrinsicRate (const COxidationIntrinsicRate< CloudType > &srm)
Construct copy.
virtual autoPtr< SurfaceReactionModel< CloudType > > clone () const
Construct and return a clone.
virtual ~COxidationIntrinsicRate ()
Destructor.
virtual scalar calculate (const scalar dt, const label celli, const scalar d, const scalar T, const scalar Tc, const scalar pc, const scalar rhoc, const scalar mass, const scalarField &YGas, const scalarField &YLiquid, const scalarField &YSolid, const scalarField &YMixture, const scalar N, scalarField &dMassGas, scalarField &dMassLiquid, scalarField &dMassSolid, scalarField &dMassSRCarrier) const
Update surface reactions.
Public Member Functions inherited from SurfaceReactionModel< CloudType >
TypeName ("surfaceReactionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, SurfaceReactionModel, dictionary,(const dictionary &dict, CloudType &cloud),(dict, cloud))
Declare runtime constructor selection table.
SurfaceReactionModel (CloudType &owner)
Construct null from owner.
SurfaceReactionModel (const dictionary &dict, CloudType &cloud, const word &type)
Construct from dictionary.
SurfaceReactionModel (const SurfaceReactionModel< CloudType > &srm)
Construct copy.
virtual ~SurfaceReactionModel ()
Destructor.
void addToSurfaceReactionMass (const scalar dMass)
Add to devolatilisation mass.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from SurfaceReactionModel< CloudType >
static autoPtr< SurfaceReactionModel< CloudType > > New (const dictionary &dict, CloudType &cloud)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from SurfaceReactionModel< CloudType >
scalar dMass_
Mass of lagrangian phase converted.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::COxidationIntrinsicRate< CloudType >
Intrinsic char surface reaction mndel.
C(s) + Sb*O2 -> CO2
where Sb is the stoichiometry of the reaction
Definition at line 49 of file COxidationIntrinsicRate.H.
Constructor & Destructor Documentation
COxidationIntrinsicRate() [1/2]
COxidationIntrinsicRate (const dictionary & dict, CloudType & owner)
Construct from dictionary.
Definition at line 35 of file COxidationIntrinsicRate.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, and Foam::nl.
COxidationIntrinsicRate() [2/2]
COxidationIntrinsicRate (const COxidationIntrinsicRate< CloudType > & srm)
Construct copy.
Definition at line 82 of file COxidationIntrinsicRate.C.
References COxidationIntrinsicRate< CloudType >::~COxidationIntrinsicRate().
~COxidationIntrinsicRate()
~COxidationIntrinsicRate () virtual
Destructor.
Definition at line 108 of file COxidationIntrinsicRate.C.
References COxidationIntrinsicRate< CloudType >::calculate().
Referenced by COxidationIntrinsicRate< CloudType >::clone(), and COxidationIntrinsicRate< CloudType >::COxidationIntrinsicRate().
Member Function Documentation
TypeName()
TypeName ("COxidationIntrinsicRate< CloudType >")
Runtime type information.
clone()
virtual autoPtr<SurfaceReactionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements SurfaceReactionModel< CloudType >.
Definition at line 135 of file COxidationIntrinsicRate.H.
References COxidationIntrinsicRate< CloudType >::calculate(), N, Foam::T(), and COxidationIntrinsicRate< CloudType >::~COxidationIntrinsicRate().
calculate()
Foam::scalar calculate (const scalar dt, const label celli, const scalar d, const scalar T, const scalar Tc, const scalar pc, const scalar rhoc, const scalar mass, const scalarField & YGas, const scalarField & YLiquid, const scalarField & YSolid, const scalarField & YMixture, const scalar N, scalarField & dMassGas, scalarField & dMassLiquid, scalarField & dMassSolid, scalarField & dMassSRCarrier) const virtual
Update surface reactions.
Implements SurfaceReactionModel< CloudType >.
Definition at line 116 of file COxidationIntrinsicRate.C.
References SLGThermo::carrier(), Foam::exp(), Foam::max(), Foam::min(), phi, Foam::constant::mathematical::pi(), Foam::pow(), Foam::pow3(), solidMixtureProperties::properties(), R, Foam::constant::thermodynamic::RR, SLGThermo::solids(), Foam::sqr(), Foam::sqrt(), Foam::tanh(), and basicMultiComponentMixture::Y().
Referenced by COxidationIntrinsicRate< CloudType >::clone(), and COxidationIntrinsicRate< CloudType >::~COxidationIntrinsicRate().
The documentation for this class was generated from the following files:
src/lagrangian/coalCombustion/submodels/surfaceReactionModel/COxidationIntrinsicRate/COxidationIntrinsicRate.H
src/lagrangian/coalCombustion/submodels/surfaceReactionModel/COxidationIntrinsicRate/COxidationIntrinsicRate.C