OpenFOAM: SpecularReflection< CloudType > Class Template Reference
SpecularReflection< CloudType > Class Template Reference
Reversing the wall-normal component of the particle velocity.
Public Member Functions
TypeName ("SpecularReflection")
Runtime type information.
SpecularReflection (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
virtual ~SpecularReflection ()
Destructor.
virtual void correct (typename CloudType::parcelType &p, const wallPolyPatch &wpp)
Apply wall correction.
Public Member Functions inherited from WallInteractionModel< CloudType >
TypeName ("WallInteractionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, WallInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
WallInteractionModel (CloudType &owner)
Construct null from owner.
WallInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~WallInteractionModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
CloudType & owner ()
Return non-const access to the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from WallInteractionModel< CloudType >
static autoPtr< WallInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::SpecularReflection< CloudType >
Reversing the wall-normal component of the particle velocity.
Definition at line 45 of file SpecularReflection.H.
Constructor & Destructor Documentation
SpecularReflection()
SpecularReflection (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 34 of file SpecularReflection.C.
~SpecularReflection()
~SpecularReflection () virtual
Destructor.
Definition at line 46 of file SpecularReflection.C.
References SpecularReflection< CloudType >::correct().
Member Function Documentation
TypeName()
TypeName ("SpecularReflection< CloudType >")
Runtime type information.
correct()
void correct (typename CloudType::parcelType & p, const wallPolyPatch & wpp) virtual
Apply wall correction.
Implements WallInteractionModel< CloudType >.
Definition at line 54 of file SpecularReflection.C.
References Foam::mag(), nw, and U.
Referenced by SpecularReflection< CloudType >::~SpecularReflection().
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/submodels/WallInteractionModel/SpecularReflection/SpecularReflection.H
src/lagrangian/DSMC/submodels/WallInteractionModel/SpecularReflection/SpecularReflection.C