OpenFOAM: DSMCParcel< ParcelType >::iNew Class Reference
DSMCParcel< ParcelType >::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< DSMCParcel< ParcelType > > operator() (Istream &is) const
Detailed Description
template<class ParcelType>
class Foam::DSMCParcel< ParcelType >::iNew
Factory class to read-construct particles used for.
parallel transfer
Definition at line 205 of file DSMCParcel.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 211 of file DSMCParcel.H.
Member Function Documentation
operator()()
autoPtr<DSMCParcel<ParcelType> > operator() (Istream & is) const inline
Definition at line 216 of file DSMCParcel.H.
References Foam::constant::universal::c, DSMCParcel< ParcelType >::Ei(), DSMCParcel< ParcelType >::hitPatch(), DSMCParcel< ParcelType >::hitProcessorPatch(), DSMCParcel< ParcelType >::hitWallPatch(), DSMCParcel< ParcelType >::move(), patchi, DSMCParcel< ParcelType >::readFields(), Foam::T(), DSMCParcel< ParcelType >::transformProperties(), DSMCParcel< ParcelType >::typeId(), DSMCParcel< ParcelType >::U(), and DSMCParcel< ParcelType >::writeFields().
The documentation for this class was generated from the following file:
src/lagrangian/DSMC/parcels/Templates/DSMCParcel/DSMCParcel.H