OpenFOAM: FreeStream< CloudType > Class Template Reference
FreeStream< CloudType > Class Template Reference
Inserting new particles across the faces of a all patched of type "patch" for a free stream. Uniform values number density, temperature and velocity sourced face-by-face from the boundaryT and boundaryU fields of the cloud.
Public Member Functions
TypeName ("FreeStream")
Runtime type information.
FreeStream (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
virtual ~FreeStream ()
Destructor.
virtual void autoMap (const mapPolyMesh &)
Remap the particles to the correct cells following mesh change.
virtual void inflow ()
Introduce particles.
Public Member Functions inherited from InflowBoundaryModel< CloudType >
TypeName ("InflowBoundaryModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, InflowBoundaryModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
InflowBoundaryModel (CloudType &owner)
Construct null from owner.
InflowBoundaryModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
virtual ~InflowBoundaryModel ()
Destructor.
const CloudType & owner () const
Return const access the owner cloud object.
CloudType & owner ()
Return non-const access the owner cloud object for manipulation.
const dictionary & dict () const
Return the owner cloud dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from InflowBoundaryModel< CloudType >
static autoPtr< InflowBoundaryModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::FreeStream< CloudType >
Inserting new particles across the faces of a all patched of type "patch" for a free stream. Uniform values number density, temperature and velocity sourced face-by-face from the boundaryT and boundaryU fields of the cloud.
Definition at line 49 of file FreeStream.H.
Constructor & Destructor Documentation
FreeStream()
FreeStream (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 37 of file FreeStream.C.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), forAll, dictionary::lookup(), Foam::nl, p, patches, Foam::readScalar(), List< T >::setSize(), and dictionary::toc().
~FreeStream()
~FreeStream () virtual
Destructor.
Definition at line 114 of file FreeStream.C.
Member Function Documentation
TypeName()
TypeName ("FreeStream< CloudType >")
Runtime type information.
autoMap()
void autoMap (const mapPolyMesh & mapper) virtual
Remap the particles to the correct cells following mesh change.
Reimplemented from InflowBoundaryModel< CloudType >.
Definition at line 121 of file FreeStream.C.
References forAll, mesh, DSMCCloud< ParcelType >::mesh(), p, patchi, and List< T >::setSize().
inflow()
void inflow () virtual
Introduce particles.
Implements InflowBoundaryModel< CloudType >.
Definition at line 142 of file FreeStream.C.
References Foam::abort(), DSMCCloud< ParcelType >::addNewParcel(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DSMCCloud< ParcelType >::boundaryT(), DSMCCloud< ParcelType >::boundaryU(), DSMCCloud< ParcelType >::constProps(), Foam::endl(), DSMCCloud< ParcelType >::equipartitionInternalEnergy(), Foam::erf(), Foam::exp(), f(), polyPatch::faceAreas(), polyPatch::faceCentres(), polyMeshTetDecomposition::faceTetIndices(), tetIndices::faceTri(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, Foam::constant::physicoChemical::k, UList< T >::last(), triangle< Point, PointRef >::mag(), Foam::mag(), Foam::max(), DSMCCloud< ParcelType >::maxwellianMostProbableSpeed(), mesh, DSMCCloud< ParcelType >::mesh(), Foam::min(), n, Foam::nl, p, patchi, Foam::constant::mathematical::pi(), triangle< Point, PointRef >::randomPoint(), Foam::reduce(), rndGen(), DSMCCloud< ParcelType >::rndGen(), Foam::sqr(), Foam::sqrt(), polyPatch::start(), tetIndices::tetPt(), and U.
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/submodels/InflowBoundaryModel/FreeStream/FreeStream.H
src/lagrangian/DSMC/submodels/InflowBoundaryModel/FreeStream/FreeStream.C