OpenFOAM: MixedDiffuseSpecular< CloudType > Class Template Reference
MixedDiffuseSpecular< CloudType > Class Template Reference
Wall interaction setting microscopic velocity to a random one drawn from a Maxwellian distribution corresponding to a specified temperature for a specified fraction of collisions, and reversing the wall-normal component of the particle velocity for the remainder.
Public Member Functions
TypeName ("MixedDiffuseSpecular")
Runtime type information.
MixedDiffuseSpecular (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
virtual ~MixedDiffuseSpecular ()
Destructor.
virtual void correct (typename CloudType::parcelType &p, const wallPolyPatch &wpp)
Apply wall correction.
Public Member Functions inherited from WallInteractionModel< CloudType >
TypeName ("WallInteractionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, WallInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
WallInteractionModel (CloudType &owner)
Construct null from owner.
WallInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~WallInteractionModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
CloudType & owner ()
Return non-const access to the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from WallInteractionModel< CloudType >
static autoPtr< WallInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::MixedDiffuseSpecular< CloudType >
Wall interaction setting microscopic velocity to a random one drawn from a Maxwellian distribution corresponding to a specified temperature for a specified fraction of collisions, and reversing the wall-normal component of the particle velocity for the remainder.
Definition at line 49 of file MixedDiffuseSpecular.H.
Constructor & Destructor Documentation
MixedDiffuseSpecular()
MixedDiffuseSpecular (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 32 of file MixedDiffuseSpecular.C.
~MixedDiffuseSpecular()
~MixedDiffuseSpecular () virtual
Destructor.
Definition at line 45 of file MixedDiffuseSpecular.C.
References MixedDiffuseSpecular< CloudType >::correct().
Member Function Documentation
TypeName()
TypeName ("MixedDiffuseSpecular< CloudType >")
Runtime type information.
correct()
void correct (typename CloudType::parcelType & p, const wallPolyPatch & wpp) virtual
Apply wall correction.
Implements WallInteractionModel< CloudType >.
Definition at line 53 of file MixedDiffuseSpecular.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DSMCCloud< ParcelType >::boundaryT(), DSMCCloud< ParcelType >::boundaryU(), DSMCCloud< ParcelType >::constProps(), DSMCCloud< ParcelType >::equipartitionInternalEnergy(), patchIdentifier::index(), k, Foam::log(), Foam::mag(), Foam::max(), nw, rndGen(), DSMCCloud< ParcelType >::rndGen(), Foam::sqrt(), T, U, polyPatch::whichFace(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by MixedDiffuseSpecular< CloudType >::~MixedDiffuseSpecular().
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/submodels/WallInteractionModel/MixedDiffuseSpecular/MixedDiffuseSpecular.H
src/lagrangian/DSMC/submodels/WallInteractionModel/MixedDiffuseSpecular/MixedDiffuseSpecular.C