OpenFOAM: kinematicCloud Class Reference
kinematicCloud Class Reference abstract
Virtual abstract base class for templated KinematicCloud.
Public Member Functions
TypeName ("kinematicCloud")
Runtime type information.
kinematicCloud ()
Null constructor.
virtual label nParcels () const =0
Number of parcels.
virtual scalar massInSystem () const =0
Total mass in system.
virtual vector linearMomentumOfSystem () const =0
Total linear momentum of the system.
virtual scalar linearKineticEnergyOfSystem () const =0
Total linear kinetic energy in the system.
virtual scalar Dij (const label i, const label j) const =0
Mean diameter Dij.
virtual scalar Dmax () const =0
Max diameter.
virtual const tmp< volScalarField > vDotSweep () const =0
Volume swept rate of parcels per cell.
virtual const tmp< volScalarField > theta () const =0
Return the particle volume fraction field.
virtual const tmp< volScalarField > alpha () const =0
Return the particle mass fraction field.
virtual const tmp< volScalarField > rhoEff () const =0
Return the particle effective density field.
virtual ~kinematicCloud ()
Destructor.
Detailed Description
Virtual abstract base class for templated KinematicCloud.
Source files
kinematicCloud.H
kinematicCloud.H
Definition at line 49 of file kinematicCloud.H.
Constructor & Destructor Documentation
kinematicCloud()
kinematicCloud ()
Null constructor.
Definition at line 38 of file kinematicCloud.C.
~kinematicCloud()
~kinematicCloud () virtual
Destructor.
Definition at line 44 of file kinematicCloud.C.
Member Function Documentation
TypeName()
TypeName ("kinematicCloud")
Runtime type information.
nParcels()
virtual label nParcels () const pure virtual
Number of parcels.
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
Referenced by cloudInfo::write().
massInSystem()
virtual scalar massInSystem () const pure virtual
Total mass in system.
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
Referenced by cloudInfo::write().
linearMomentumOfSystem()
virtual vector linearMomentumOfSystem () const pure virtual
Total linear momentum of the system.
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
linearKineticEnergyOfSystem()
virtual scalar linearKineticEnergyOfSystem () const pure virtual
Total linear kinetic energy in the system.
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
Dij()
virtual scalar Dij (const label i, const label j) const pure virtual
Mean diameter Dij.
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
Dmax()
virtual scalar Dmax () const pure virtual
Max diameter.
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
vDotSweep()
virtual const tmp<volScalarField> vDotSweep () const pure virtual
Volume swept rate of parcels per cell.
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
Referenced by SuppressionCollision< CloudType >::collide().
theta()
virtual const tmp<volScalarField> theta () const pure virtual
Return the particle volume fraction field.
Note: for particles belonging to this cloud only
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
alpha()
virtual const tmp<volScalarField> alpha () const pure virtual
Return the particle mass fraction field.
Note: for particles belonging to this cloud only
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
rhoEff()
virtual const tmp<volScalarField> rhoEff () const pure virtual
Return the particle effective density field.
Note: for particles belonging to this cloud only
Implemented in KinematicCloud< CloudType >, KinematicCloud< Foam::DSMCCloud >, and KinematicCloud< Cloud< basicKinematicCollidingParcel > >.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/baseClasses/kinematicCloud/kinematicCloud.H
src/lagrangian/intermediate/clouds/baseClasses/kinematicCloud/kinematicCloud.C