OpenFOAM: DSMCParcel< ParcelType >::constantProperties Class Reference
DSMCParcel< ParcelType >::constantProperties Class Reference
Class to hold DSMC particle constant properties.
Public Member Functions
constantProperties ()
Null constructor, allows List of constantProperties to be.
constantProperties (const dictionary &dict)
Constructor from dictionary.
scalar mass () const
Return const access to the particle mass [kg].
scalar d () const
Return const access to the hard sphere diameter [m].
scalar sigmaT () const
Return the reference total collision cross section.
direction internalDegreesOfFreedom () const
Return the internalDegreesOfFreedom.
scalar omega () const
Return the viscosity index.
Detailed Description
template<class ParcelType>
class Foam::DSMCParcel< ParcelType >::constantProperties
Class to hold DSMC particle constant properties.
Definition at line 80 of file DSMCParcel.H.
Constructor & Destructor Documentation
constantProperties() [1/2]
constantProperties () inline
Null constructor, allows List of constantProperties to be.
created before the contents is initialised
Definition at line 31 of file DSMCParcelI.H.
constantProperties() [2/2]
constantProperties (const dictionary & dict) inline
Constructor from dictionary.
Definition at line 40 of file DSMCParcelI.H.
References DSMCParcel< ParcelType >::DSMCParcel().
Member Function Documentation
mass()
Foam::scalar mass () const inline
Return const access to the particle mass [kg].
Definition at line 78 of file DSMCParcelI.H.
Referenced by DSMCParcel< ParcelType >::hitWallPatch().
d()
Foam::scalar d () const inline
Return const access to the hard sphere diameter [m].
Definition at line 85 of file DSMCParcelI.H.
sigmaT()
Foam::scalar sigmaT () const inline
Return the reference total collision cross section.
Definition at line 93 of file DSMCParcelI.H.
References Foam::constant::mathematical::pi().
internalDegreesOfFreedom()
Foam::direction internalDegreesOfFreedom () const inline
Return the internalDegreesOfFreedom.
Definition at line 101 of file DSMCParcelI.H.
omega()
Foam::scalar omega () const inline
Return the viscosity index.
Definition at line 110 of file DSMCParcelI.H.
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/parcels/Templates/DSMCParcel/DSMCParcel.H
src/lagrangian/DSMC/parcels/Templates/DSMCParcel/DSMCParcelI.H