OpenFOAM: cloudSolution Class Reference
cloudSolution Class Reference
Stores all relevant solution info for cloud.
Public Member Functions
cloudSolution (const fvMesh &mesh)
Construct null from mesh reference.
cloudSolution (const fvMesh &mesh, const dictionary &dict)
Construct from mesh and dictionary.
cloudSolution (const cloudSolution &cs)
Construct copy.
virtual ~cloudSolution ()
Destructor.
void read ()
Read properties from dictionary.
scalar relaxCoeff (const word &fieldName) const
Return relaxation coefficient for field.
bool semiImplicit (const word &fieldName) const
Return semi-implicit flag coefficient for field.
const fvMesh & mesh () const
Return reference to the mesh.
const dictionary & dict () const
Return const access to the dictionary.
const Switch active () const
Return the active flag.
const Switch transient () const
Return const access to the transient flag.
const Switch steadyState () const
Return const access to the steady flag.
label calcFrequency () const
Return const access to the calculation frequency.
scalar maxCo () const
Return const access to the max particle Courant number.
label iter () const
Return const access to the current cloud iteration.
label nextIter ()
Increment and return iter counter.
scalar trackTime () const
Return the particle track time.
const Switch coupled () const
Return const access to the coupled flag.
Switch & coupled ()
Return non-const access to the coupled flag.
const Switch cellValueSourceCorrection () const
Return const access to the cell value correction flag.
scalar maxTrackTime () const
Return const access to the particle track time.
const Switch resetSourcesOnStartup () const
Return const access to the reset sources flag.
const dictionary & sourceTermDict () const
Source terms dictionary.
const dictionary & interpolationSchemes () const
Interpolation schemes dictionary.
const dictionary & integrationSchemes () const
Integration schemes dictionary.
bool solveThisStep () const
Returns true if performing a cloud iteration this calc step.
bool canEvolve ()
Returns true if possible to evolve the cloud and sets timestep.
bool output () const
Returns true if writing this step.
Detailed Description
Stores all relevant solution info for cloud.
Source files
cloudSolution.H
cloudSolutionI.H
cloudSolution.C
Definition at line 51 of file cloudSolution.H.
Constructor & Destructor Documentation
cloudSolution() [1/3]
cloudSolution (const fvMesh & mesh)
Construct null from mesh reference.
Definition at line 80 of file cloudSolution.C.
Referenced by cloudSolution::cloudSolution().
cloudSolution() [2/3]
cloudSolution (const fvMesh & mesh, const dictionary & dict)
Construct from mesh and dictionary.
Definition at line 32 of file cloudSolution.C.
References cloudSolution::cloudSolution(), and Foam::read().
cloudSolution() [3/3]
cloudSolution (const cloudSolution & cs)
Construct copy.
Definition at line 59 of file cloudSolution.C.
References cloudSolution::cloudSolution().
~cloudSolution()
~cloudSolution () virtual
Destructor.
Definition at line 102 of file cloudSolution.C.
Member Function Documentation
read()
void read ()
Read properties from dictionary.
Definition at line 108 of file cloudSolution.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, dictionary::lookup(), dictionary::readIfPresent(), Foam::fvc::scheme(), cloudSolution::steadyState(), and dictionary::subDict().
relaxCoeff()
Foam::scalar relaxCoeff (const word & fieldName) const
Return relaxation coefficient for field.
Definition at line 164 of file cloudSolution.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and forAll.
semiImplicit()
bool semiImplicit (const word & fieldName) const
Return semi-implicit flag coefficient for field.
Definition at line 182 of file cloudSolution.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and forAll.
mesh()
const Foam::fvMesh & mesh () const inline
Return reference to the mesh.
Definition at line 26 of file cloudSolutionI.H.
dict()
const Foam::dictionary & dict () const inline
Return const access to the dictionary.
Definition at line 32 of file cloudSolutionI.H.
active()
const Foam::Switch active () const inline
Return the active flag.
Definition at line 38 of file cloudSolutionI.H.
transient()
const Foam::Switch transient () const inline
Return const access to the transient flag.
Definition at line 62 of file cloudSolutionI.H.
steadyState()
const Foam::Switch steadyState () const inline
Return const access to the steady flag.
Definition at line 68 of file cloudSolutionI.H.
Referenced by cloudSolution::read().
calcFrequency()
Foam::label calcFrequency () const inline
Return const access to the calculation frequency.
Definition at line 74 of file cloudSolutionI.H.
maxCo()
Foam::scalar maxCo () const inline
Return const access to the max particle Courant number.
Definition at line 80 of file cloudSolutionI.H.
iter()
Foam::label iter () const inline
Return const access to the current cloud iteration.
Definition at line 86 of file cloudSolutionI.H.
nextIter()
Foam::label nextIter () inline
Increment and return iter counter.
Definition at line 92 of file cloudSolutionI.H.
trackTime()
Foam::scalar trackTime () const inline
Return the particle track time.
Definition at line 98 of file cloudSolutionI.H.
coupled() [1/2]
const Foam::Switch coupled () const inline
Return const access to the coupled flag.
Definition at line 110 of file cloudSolutionI.H.
coupled() [2/2]
Foam::Switch & coupled () inline
Return non-const access to the coupled flag.
Definition at line 104 of file cloudSolutionI.H.
cellValueSourceCorrection()
const Foam::Switch cellValueSourceCorrection () const inline
Return const access to the cell value correction flag.
Definition at line 116 of file cloudSolutionI.H.
maxTrackTime()
Foam::scalar maxTrackTime () const inline
Return const access to the particle track time.
Definition at line 122 of file cloudSolutionI.H.
resetSourcesOnStartup()
const Foam::Switch resetSourcesOnStartup () const inline
Return const access to the reset sources flag.
Definition at line 128 of file cloudSolutionI.H.
sourceTermDict()
const Foam::dictionary & sourceTermDict () const inline
Source terms dictionary.
Definition at line 44 of file cloudSolutionI.H.
References dictionary::subDict().
interpolationSchemes()
const Foam::dictionary & interpolationSchemes () const inline
Interpolation schemes dictionary.
Definition at line 50 of file cloudSolutionI.H.
References dictionary::subDict().
integrationSchemes()
const Foam::dictionary & integrationSchemes () const inline
Integration schemes dictionary.
Definition at line 56 of file cloudSolutionI.H.
References dictionary::subDict().
solveThisStep()
bool solveThisStep () const
Returns true if performing a cloud iteration this calc step.
Definition at line 200 of file cloudSolution.C.
References fvMesh::time(), TimeState::timeIndex(), and TimeState::writeTime().
Referenced by cloudSolution::canEvolve().
canEvolve()
bool canEvolve ()
Returns true if possible to evolve the cloud and sets timestep.
parameters
Definition at line 211 of file cloudSolution.C.
References TimeState::deltaTValue(), cloudSolution::solveThisStep(), and fvMesh::time().
output()
bool output () const
Returns true if writing this step.
Definition at line 226 of file cloudSolution.C.
References fvMesh::time(), and TimeState::writeTime().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/cloudSolution/cloudSolution.H
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/cloudSolution/cloudSolution.C
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/cloudSolution/cloudSolutionI.H