OpenFOAM: VariableHardSphere< CloudType > Class Template Reference
VariableHardSphere< CloudType > Class Template Reference
Variable Hard Sphere BinaryCollision Model.
Public Member Functions
TypeName ("VariableHardSphere")
Runtime type information.
VariableHardSphere (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
virtual ~VariableHardSphere ()
Destructor.
virtual bool active () const
Flag to indicate whether model activates collision model.
virtual scalar sigmaTcR (const typename CloudType::parcelType &pP, const typename CloudType::parcelType &pQ) const
Return the collision cross section * relative velocity product.
virtual void collide (typename CloudType::parcelType &pP, typename CloudType::parcelType &pQ)
Apply collision.
Public Member Functions inherited from BinaryCollisionModel< CloudType >
TypeName ("BinaryCollisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, BinaryCollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
BinaryCollisionModel (CloudType &owner)
Construct null from owner.
BinaryCollisionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~BinaryCollisionModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
CloudType & owner ()
Return non-const access to the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from BinaryCollisionModel< CloudType >
static autoPtr< BinaryCollisionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::VariableHardSphere< CloudType >
Variable Hard Sphere BinaryCollision Model.
Definition at line 45 of file VariableHardSphere.H.
Constructor & Destructor Documentation
VariableHardSphere()
VariableHardSphere (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 35 of file VariableHardSphere.C.
~VariableHardSphere()
~VariableHardSphere () virtual
Destructor.
Definition at line 48 of file VariableHardSphere.C.
Member Function Documentation
TypeName()
TypeName ("VariableHardSphere< CloudType >")
Runtime type information.
active()
bool active () const virtual
Flag to indicate whether model activates collision model.
Implements BinaryCollisionModel< CloudType >.
Definition at line 55 of file VariableHardSphere.C.
References VariableHardSphere< CloudType >::sigmaTcR().
sigmaTcR()
Foam::scalar sigmaTcR (const typename CloudType::parcelType & pP, const typename CloudType::parcelType & pQ) const virtual
Return the collision cross section * relative velocity product.
Implements BinaryCollisionModel< CloudType >.
Definition at line 63 of file VariableHardSphere.C.
References VariableHardSphere< CloudType >::collide(), DSMCCloud< ParcelType >::constProps(), Foam::exp(), Foam::constant::physicoChemical::k, Foam::lgamma(), Foam::mag(), Foam::constant::mathematical::pi(), and Foam::pow().
Referenced by VariableHardSphere< CloudType >::active().
collide()
void collide (typename CloudType::parcelType & pP, typename CloudType::parcelType & pQ) virtual
Apply collision.
Implements BinaryCollisionModel< CloudType >.
Definition at line 112 of file VariableHardSphere.C.
References DSMCCloud< ParcelType >::constProps(), Foam::cos(), Foam::mag(), phi, rndGen(), DSMCCloud< ParcelType >::rndGen(), Foam::sin(), Foam::sqrt(), and Foam::constant::mathematical::twoPi().
Referenced by VariableHardSphere< CloudType >::sigmaTcR().
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/submodels/BinaryCollisionModel/VariableHardSphere/VariableHardSphere.H
src/lagrangian/DSMC/submodels/BinaryCollisionModel/VariableHardSphere/VariableHardSphere.C