OpenFOAM: CollidingParcel< ParcelType >::iNew Class Reference
CollidingParcel< ParcelType >::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< CollidingParcel< ParcelType > > operator() (Istream &is) const
Detailed Description
template<class ParcelType>
class Foam::CollidingParcel< ParcelType >::iNew
Factory class to read-construct particles used for.
parallel transfer
Definition at line 223 of file CollidingParcel.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 229 of file CollidingParcel.H.
Member Function Documentation
operator()()
autoPtr<CollidingParcel<ParcelType> > operator() (Istream & is) const inline
Definition at line 234 of file CollidingParcel.H.
References CollidingParcel< ParcelType >::angularMomentum(), Foam::constant::universal::c, CollidingParcel< ParcelType >::collisionRecords(), CollidingParcel< ParcelType >::f(), CollidingParcel< ParcelType >::move(), CollidingParcel< ParcelType >::omega(), CollidingParcel< ParcelType >::readFields(), Foam::T(), CollidingParcel< ParcelType >::torque(), CollidingParcel< ParcelType >::transformProperties(), and CollidingParcel< ParcelType >::writeFields().
The documentation for this class was generated from the following file:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcel.H