OpenFOAM: PatchInteractionModel< CloudType > Class Template Reference
PatchInteractionModel< CloudType > Class Template Reference abstract
Templated patch interaction model class.
Public Types
enum interactionType { itRebound, itStick, itEscape, itOther }
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Public Member Functions
TypeName ("patchInteractionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, PatchInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
PatchInteractionModel (CloudType &owner)
Construct null from owner.
PatchInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
PatchInteractionModel (const PatchInteractionModel< CloudType > &pim)
Construct copy.
virtual autoPtr< PatchInteractionModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~PatchInteractionModel ()
Destructor.
const word & UName () const
Return name of velocity field.
virtual bool correct (typename CloudType::parcelType &p, const polyPatch &pp, bool &keepParticle, const scalar trackFraction, const tetIndices &tetIs)=0
Apply velocity correction.
virtual void info (Ostream &os)
Write patch interaction info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr< PatchInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
static word interactionTypeToWord (const interactionType &itEnum)
Convert interaction result to word.
static interactionType wordToInteractionType (const word &itWord)
Convert word to interaction result.
Static Public Attributes
static wordList interactionTypeNames_
Additional Inherited Members
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::PatchInteractionModel< CloudType >
Templated patch interaction model class.
Source files
PatchInteractionModel.H
PatchInteractionModel.C
PatchInteractionModelNew.C
Definition at line 82 of file KinematicCloud.H.
Member Enumeration Documentation
interactionType
enum interactionType
Enumerator
itRebound
itStick
itEscape
itOther
Definition at line 65 of file PatchInteractionModel.H.
Constructor & Destructor Documentation
PatchInteractionModel() [1/3]
PatchInteractionModel (CloudType & owner)
Construct null from owner.
Definition at line 108 of file PatchInteractionModel.C.
Referenced by PatchInteractionModel< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::PatchInteractionModel(), and PatchInteractionModel< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::wordToInteractionType().
PatchInteractionModel() [2/3]
PatchInteractionModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from components.
Definition at line 119 of file PatchInteractionModel.C.
PatchInteractionModel() [3/3]
PatchInteractionModel (const PatchInteractionModel< CloudType > & pim)
Construct copy.
Definition at line 132 of file PatchInteractionModel.C.
~PatchInteractionModel()
~PatchInteractionModel () virtual
Destructor.
Definition at line 144 of file PatchInteractionModel.C.
Member Function Documentation
TypeName()
TypeName ("patchInteractionModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , PatchInteractionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
clone()
virtual autoPtr<PatchInteractionModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in MultiInteraction< CloudType >, StandardWallInteraction< CloudType >, LocalInteraction< CloudType >, Rebound< CloudType >, and NoInteraction< CloudType >.
New()
Foam::autoPtr< Foam::PatchInteractionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 33 of file PatchInteractionModelNew.C.
UName()
const Foam::word & UName () const
Return name of velocity field.
Definition at line 151 of file PatchInteractionModel.C.
interactionTypeToWord()
Foam::word interactionTypeToWord (const interactionType & itEnum) static
Convert interaction result to word.
Definition at line 46 of file PatchInteractionModel.C.
wordToInteractionType()
Foam::PatchInteractionModel< CloudType >::interactionType wordToInteractionType (const word & itWord) static
Convert word to interaction result.
Definition at line 81 of file PatchInteractionModel.C.
Referenced by PatchInteractionModel< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::interactionTypeToWord().
correct()
virtual bool correct (typename CloudType::parcelType & p, const polyPatch & pp, bool & keepParticle, const scalar trackFraction, const tetIndices & tetIs) pure virtual
Apply velocity correction.
Returns true if particle remains in same cell
Implemented in MultiInteraction< CloudType >, StandardWallInteraction< CloudType >, LocalInteraction< CloudType >, Rebound< CloudType >, and NoInteraction< CloudType >.
info()
void info (Ostream & os) virtual
Write patch interaction info to stream.
Reimplemented in StandardWallInteraction< CloudType >, and LocalInteraction< CloudType >.
Definition at line 158 of file PatchInteractionModel.C.
Member Data Documentation
interactionTypeNames_
Foam::wordList interactionTypeNames_ static
Definition at line 73 of file PatchInteractionModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/KinematicCloud.H
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/PatchInteractionModel/PatchInteractionModel.H
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/PatchInteractionModel/PatchInteractionModel.C
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/PatchInteractionModel/PatchInteractionModelNew.C