OpenFOAM: IntegrationScheme< Type >::integrationResult Class Reference
IntegrationScheme< Type >::integrationResult Class Reference
Helper class to supply results of integration.
Public Member Functions
integrationResult ()
Constructor.
Type value () const
Return const access to the value.
Type average () const
Return const access to the average.
Type & value ()
Return access to the value for changing.
Type & average ()
Return access to the average for changing.
Detailed Description
template<class Type>
class Foam::IntegrationScheme< Type >::integrationResult
Helper class to supply results of integration.
Definition at line 57 of file IntegrationScheme.H.
Constructor & Destructor Documentation
integrationResult()
integrationResult () inline
Constructor.
Definition at line 69 of file IntegrationScheme.H.
Member Function Documentation
value() [1/2]
Type value () const inline
Return const access to the value.
Definition at line 81 of file IntegrationScheme.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), Euler< Type >::integrate(), and Analytical< Type >::integrate().
average() [1/2]
Type average () const inline
Return const access to the average.
Definition at line 87 of file IntegrationScheme.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), Euler< Type >::integrate(), and Analytical< Type >::integrate().
value() [2/2]
Type& value () inline
Return access to the value for changing.
Definition at line 96 of file IntegrationScheme.H.
average() [2/2]
Type& average () inline
Return access to the average for changing.
Definition at line 102 of file IntegrationScheme.H.
References beta(), IntegrationScheme< Type >::clone(), IntegrationScheme< Type >::declareRunTimeSelectionTable(), dict, IntegrationScheme< Type >::integrate(), IntegrationScheme< Type >::IntegrationScheme(), IntegrationScheme< Type >::New(), phi, IntegrationScheme< Type >::TypeName(), and IntegrationScheme< Type >::~IntegrationScheme().
The documentation for this class was generated from the following file:
src/lagrangian/intermediate/IntegrationScheme/IntegrationScheme/IntegrationScheme.H