OpenFOAM: CollidingParcel< ParcelType >::constantProperties Class Reference
CollidingParcel< ParcelType >::constantProperties Class Reference
Class to hold thermo particle constant properties.
Public Member Functions
constantProperties ()
Null constructor.
constantProperties (const constantProperties &cp)
Copy constructor.
constantProperties (const dictionary &parentDict)
Construct from dictionary.
scalar youngsModulus () const
Return const access to Young's Modulus.
scalar poissonsRatio () const
Return const access to Poisson's ratio.
Detailed Description
template<class ParcelType>
class Foam::CollidingParcel< ParcelType >::constantProperties
Class to hold thermo particle constant properties.
Definition at line 83 of file CollidingParcel.H.
Constructor & Destructor Documentation
constantProperties() [1/3]
constantProperties () inline
Null constructor.
Definition at line 30 of file CollidingParcelI.H.
Referenced by CollidingParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [2/3]
constantProperties (const constantProperties & cp) inline
Copy constructor.
Definition at line 40 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [3/3]
constantProperties (const dictionary & parentDict) inline
Construct from dictionary.
Definition at line 52 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::CollidingParcel().
Member Function Documentation
youngsModulus()
Foam::scalar youngsModulus () const inline
Return const access to Young's Modulus.
Definition at line 124 of file CollidingParcelI.H.
References demandDrivenEntry< Type >::value().
poissonsRatio()
Foam::scalar poissonsRatio () const inline
Return const access to Poisson's ratio.
Definition at line 132 of file CollidingParcelI.H.
References demandDrivenEntry< Type >::value().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcel.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcelI.H