OpenFOAM: CollisionRecordList< PairType, WallType > Class Template Reference
CollisionRecordList< PairType, WallType > Class Template Reference
Public Member Functions
CollisionRecordList ()
Construct null.
CollisionRecordList (Istream &)
Construct from Istream.
CollisionRecordList (const labelField &pairAccessed, const labelField &pairOrigProcOfOther, const labelField &pairOrigIdOfOther, const Field< PairType > &pairData, const labelField &wallAccessed, const vectorField &wallPRel, const Field< WallType > &wallData)
Construct from component fields (for IO)
~CollisionRecordList ()
Destructor.
const DynamicList< PairCollisionRecord< PairType > > & pairRecords () const
Return the active pair collisions.
const DynamicList< WallCollisionRecord< WallType > > & wallRecords () const
Return the active wall collisions.
labelField pairAccessed () const
Return field of pair accessed from each record, used for.
labelField pairOrigProcOfOther () const
Return field of pair origProcOfOther from each record,.
labelField pairOrigIdOfOther () const
Return field of pair origIdOfOther from each record, used.
Field< PairType > pairData () const
Return field of pair data from each record, used for field IO.
labelField wallAccessed () const
Return field of wall accessed from each record, used for field IO.
vectorField wallPRel () const
Return field of wall pRel from each record, used for field IO.
Field< WallType > wallData () const
Return field of wall data from each record, used for field IO.
PairCollisionRecord< PairType > & matchPairRecord (label origProcOfOther, label origIdOfOther)
Enquires if the proc and id pair of the other particle are.
bool checkPairRecord (label origProcOfOther, label origIdOfOther)
Enquire if the specified record exists without modifying.
WallCollisionRecord< WallType > & matchWallRecord (const vector &pRel, scalar radius)
Enquires if the position of wall impact relative to the.
bool checkWallRecord (const vector &pRel, scalar radius)
Enquire if the specified record exists without modifying.
void update ()
Update the collision records, deleting any records not.
void operator= (const CollisionRecordList &)
Friends
bool operator== (const CollisionRecordList< PairType, WallType > &, const CollisionRecordList< PairType, WallType > &)
bool operator!= (const CollisionRecordList< PairType, WallType > &, const CollisionRecordList< PairType, WallType > &)
Istream & operator>> (Istream &, CollisionRecordList< PairType, WallType > &)
Ostream & operator (Ostream &, const CollisionRecordList< PairType, WallType > &)
Detailed Description
template<class PairType, class WallType>
class Foam::CollisionRecordList< PairType, WallType >
Source files
CollisionRecordList.H
CollisionRecordListI.H
CollisionRecordList.C
CollisionRecordListIO.C
Definition at line 49 of file CollisionRecordList.H.
Constructor & Destructor Documentation
CollisionRecordList() [1/3]
CollisionRecordList ()
Construct null.
Definition at line 32 of file CollisionRecordList.C.
Referenced by CollisionRecordList< vector, vector >::CollisionRecordList().
CollisionRecordList() [2/3]
CollisionRecordList (Istream & is)
Construct from Istream.
Definition at line 40 of file CollisionRecordList.C.
CollisionRecordList() [3/3]
CollisionRecordList (const labelField & pairAccessed, const labelField & pairOrigProcOfOther, const labelField & pairOrigIdOfOther, const Field< PairType > & pairData, const labelField & wallAccessed, const vectorField & wallPRel, const Field< WallType > & wallData)
Construct from component fields (for IO)
Definition at line 56 of file CollisionRecordList.C.
~CollisionRecordList()
~CollisionRecordList ()
Destructor.
Definition at line 131 of file CollisionRecordList.C.
Member Function Documentation
pairRecords()
const Foam::DynamicList< Foam::PairCollisionRecord< PairType > > & pairRecords () const inline
Return the active pair collisions.
Definition at line 32 of file CollisionRecordListI.H.
wallRecords()
const Foam::DynamicList< Foam::WallCollisionRecord< WallType > > & wallRecords () const inline
Return the active wall collisions.
Definition at line 40 of file CollisionRecordListI.H.
pairAccessed()
Foam::labelField pairAccessed () const
Return field of pair accessed from each record, used for.
field IO
Definition at line 139 of file CollisionRecordList.C.
pairOrigProcOfOther()
Foam::labelField pairOrigProcOfOther () const
Return field of pair origProcOfOther from each record,.
used for field IO
Definition at line 154 of file CollisionRecordList.C.
pairOrigIdOfOther()
Foam::labelField pairOrigIdOfOther () const
Return field of pair origIdOfOther from each record, used.
for field IO
Definition at line 169 of file CollisionRecordList.C.
pairData()
Foam::Field< PairType > pairData () const
Return field of pair data from each record, used for field IO.
Definition at line 184 of file CollisionRecordList.C.
wallAccessed()
Foam::labelField wallAccessed () const
Return field of wall accessed from each record, used for field IO.
Definition at line 199 of file CollisionRecordList.C.
wallPRel()
Foam::vectorField wallPRel () const
Return field of wall pRel from each record, used for field IO.
Definition at line 214 of file CollisionRecordList.C.
wallData()
Foam::Field< WallType > wallData () const
Return field of wall data from each record, used for field IO.
Definition at line 229 of file CollisionRecordList.C.
matchPairRecord()
Foam::PairCollisionRecord< PairType > & matchPairRecord (label origProcOfOther, label origIdOfOther)
Enquires if the proc and id pair of the other particle are.
present in the records. If so, return non-const access to the PairCollisionRecord (hence the data) and mark the PairCollisionRecord as accessed this step, if not, create the record and return access to it.
Definition at line 245 of file CollisionRecordList.C.
Referenced by CollisionRecordList< vector, vector >::wallData().
checkPairRecord()
bool checkPairRecord (label origProcOfOther, label origIdOfOther)
Enquire if the specified record exists without modifying.
its accessed status
Definition at line 281 of file CollisionRecordList.C.
Referenced by CollisionRecordList< vector, vector >::matchPairRecord().
matchWallRecord()
Foam::WallCollisionRecord< WallType > & matchWallRecord (const vector & pRel, scalar radius)
Enquires if the position of wall impact relative to the.
particle centre is present in the records. If so, return access to the WallCollisionRecord (hence the data) and mark the WallCollisionRecord as accesses this step, if not, create the record and return access to it.
Definition at line 303 of file CollisionRecordList.C.
Referenced by CollisionRecordList< vector, vector >::checkPairRecord().
checkWallRecord()
bool checkWallRecord (const vector & pRel, scalar radius)
Enquire if the specified record exists without modifying.
its accessed status
Definition at line 335 of file CollisionRecordList.C.
Referenced by CollisionRecordList< vector, vector >::matchWallRecord().
update()
void update ()
Update the collision records, deleting any records not.
marked as having been accessed, then mark all records as not accessed ready for the next evaluation
Definition at line 355 of file CollisionRecordList.C.
operator=()
void operator= (const CollisionRecordList< PairType, WallType > &)
Definition at line 395 of file CollisionRecordList.C.
Friends And Related Function Documentation
operator==
bool operator== (const CollisionRecordList< PairType, WallType > & , const CollisionRecordList< PairType, WallType > &) friend
operator!=
bool operator!= (const CollisionRecordList< PairType, WallType > & , const CollisionRecordList< PairType, WallType > &) friend
operator>>
Istream& operator>> (Istream & , CollisionRecordList< PairType, WallType > &) friend
operator
Ostream& operator (Ostream & , const CollisionRecordList< PairType, WallType > &) friend
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/CollisionRecordList.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/CollisionRecordList.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/CollisionRecordListI.H