OpenFOAM: CollidingParcel< ParcelType > Class Template Reference
CollidingParcel< ParcelType > Class Template Reference
Wrapper around kinematic parcel types to add collision modelling.
Classes
class constantProperties
Class to hold thermo particle constant properties.
class iNew
Factory class to read-construct particles used for.
Public Member Functions
TypeName ("CollidingParcel")
Runtime type information.
AddToPropertyList (ParcelType, " (fx fy fz)"+" (angularMomentumx angularMomentumy angularMomentumz)"+" (torquex torquey torquez)"+" collisionRecordsPairAccessed"+" collisionRecordsPairOrigProcOfOther"+" collisionRecordsPairOrigIdOfOther"+" (collisionRecordsPairData)"+" collisionRecordsWallAccessed"+" collisionRecordsWallPRel"+" (collisionRecordsWallData)")
String representation of properties.
CollidingParcel (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti)
Construct from owner, position, and cloud owner.
CollidingParcel (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const typename ParcelType::constantProperties &constProps)
Construct from components.
CollidingParcel (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
CollidingParcel (const CollidingParcel &p)
Construct as a copy.
CollidingParcel (const CollidingParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
const vector & f () const
Return const access to force.
const vector & angularMomentum () const
Return const access to angular momentum.
const vector & torque () const
Return const access to torque.
const collisionRecordList & collisionRecords () const
Return const access to the collision records.
vector & f ()
Return access to force.
vector & angularMomentum ()
Return access to angular momentum.
vector & torque ()
Return access to torque.
collisionRecordList & collisionRecords ()
Return access to collision records.
vector omega () const
Particle angular velocity.
template<class TrackData >
bool move (TrackData &td, const scalar trackTime)
Move the parcel.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &c)
Read.
template<class CloudType >
static void writeFields (const CloudType &c)
Write.
Protected Attributes
vector f_
Force on particle due to collisions [N].
vector angularMomentum_
Angular momentum of Parcel in global reference frame [kg m2/s].
vector torque_
Torque on particle due to collisions in global.
collisionRecordList collisionRecords_
Particle collision records.
Friends
Ostream & operator (Ostream &, const CollidingParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::CollidingParcel< ParcelType >
Wrapper around kinematic parcel types to add collision modelling.
Source files
CollidingParcel.H
CollidingParcelI.H
CollidingParcel.C
CollidingParcelIO.C
Definition at line 54 of file CollidingParcel.H.
Constructor & Destructor Documentation
CollidingParcel() [1/5]
CollidingParcel (const polyMesh & mesh, const vector & position, const label celli, const label tetFacei, const label tetPti) inline
Construct from owner, position, and cloud owner.
Other properties initialised as null
Definition at line 64 of file CollidingParcelI.H.
Referenced by CollidingParcel< ParcelType >::clone(), and CollidingParcel< ParcelType >::constantProperties::constantProperties().
CollidingParcel() [2/5]
CollidingParcel (const polyMesh & mesh, const vector & position, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const typename ParcelType::constantProperties & constProps) inline
Construct from components.
Definition at line 82 of file CollidingParcelI.H.
CollidingParcel() [3/5]
CollidingParcel (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 48 of file CollidingParcelIO.C.
References IOstream::check(), IOstream::format(), and Istream::read().
CollidingParcel() [4/5]
CollidingParcel (const CollidingParcel< ParcelType > & p)
Construct as a copy.
CollidingParcel() [5/5]
CollidingParcel (const CollidingParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
TypeName()
TypeName ("CollidingParcel< ParcelType >")
Runtime type information.
AddToPropertyList()
AddToPropertyList (ParcelType , " (fx fy fz)"+" (angularMomentumx angularMomentumy angularMomentumz)"+" (torquex torquey torquez)"+" collisionRecordsPairAccessed"+" collisionRecordsPairOrigProcOfOther"+" collisionRecordsPairOrigIdOfOther"+" (collisionRecordsPairData)"+" collisionRecordsWallAccessed"+" collisionRecordsWallPRel"+" (collisionRecordsWallData)")
String representation of properties.
clone() [1/2]
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 210 of file CollidingParcel.H.
References CollidingParcel< ParcelType >::CollidingParcel().
clone() [2/2]
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 216 of file CollidingParcel.H.
References CollidingParcel< ParcelType >::CollidingParcel().
f() [1/2]
const Foam::vector & f () const inline
Return const access to force.
Definition at line 141 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::f_.
Referenced by CollidingParcel< ParcelType >::iNew::operator()(), and CollidingParcel< ParcelType >::writeFields().
angularMomentum() [1/2]
const Foam::vector & angularMomentum () const inline
Return const access to angular momentum.
Definition at line 149 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::angularMomentum_.
Referenced by CollidingParcel< ParcelType >::iNew::operator()(), and CollidingParcel< ParcelType >::writeFields().
torque() [1/2]
const Foam::vector & torque () const inline
Return const access to torque.
Definition at line 156 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::torque_.
Referenced by CollidingParcel< ParcelType >::iNew::operator()(), and CollidingParcel< ParcelType >::writeFields().
collisionRecords() [1/2]
const Foam::collisionRecordList & collisionRecords () const inline
Return const access to the collision records.
Definition at line 164 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::collisionRecords_.
Referenced by CollidingParcel< ParcelType >::iNew::operator()(), and CollidingParcel< ParcelType >::writeFields().
f() [2/2]
Foam::vector & f () inline
Return access to force.
Definition at line 171 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::f_.
angularMomentum() [2/2]
Foam::vector & angularMomentum () inline
Return access to angular momentum.
Definition at line 178 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::angularMomentum_.
torque() [2/2]
Foam::vector & torque () inline
Return access to torque.
Definition at line 185 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::torque_.
collisionRecords() [2/2]
Foam::collisionRecordList & collisionRecords () inline
Return access to collision records.
Definition at line 193 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::collisionRecords_.
omega()
Foam::vector omega () const inline
Particle angular velocity.
Definition at line 200 of file CollidingParcelI.H.
References CollidingParcel< ParcelType >::angularMomentum_.
Referenced by CollidingParcel< ParcelType >::iNew::operator()().
move()
bool move (TrackData & td, const scalar trackTime)
Move the parcel.
Definition at line 64 of file CollidingParcel.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, NotImplemented, and p.
Referenced by CollidingParcel< ParcelType >::iNew::operator()().
transformProperties() [1/2]
void transformProperties (const tensor & T) virtual
Transform the physical properties of the particle.
according to the given transformation tensor
Definition at line 115 of file CollidingParcel.C.
References Foam::transform().
Referenced by CollidingParcel< ParcelType >::iNew::operator()().
transformProperties() [2/2]
void transformProperties (const vector & separation) virtual
Transform the physical properties of the particle.
according to the given separation vector
Definition at line 129 of file CollidingParcel.C.
readFields()
void readFields (CloudType & c) static
Read.
Definition at line 87 of file CollidingParcelIO.C.
References CollidingParcel< ParcelType >::angularMomentum_, Cloud< ParticleType >::checkFieldFieldIOobject(), Cloud< ParticleType >::checkFieldIOobject(), CollidingParcel< ParcelType >::collisionRecords_, f(), CollidingParcel< ParcelType >::f_, Cloud< ParticleType >::fieldIOobject(), forAllIter, p, Foam::readFields(), Cloud< ParticleType >::size(), and CollidingParcel< ParcelType >::torque_.
Referenced by CollidingParcel< ParcelType >::iNew::operator()().
writeFields()
void writeFields (const CloudType & c) static
Write.
Definition at line 186 of file CollidingParcelIO.C.
References CollidingParcel< ParcelType >::angularMomentum(), CollidingParcel< ParcelType >::collisionRecords(), f(), CollidingParcel< ParcelType >::f(), Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), p, Cloud< ParticleType >::size(), and CollidingParcel< ParcelType >::torque().
Referenced by CollidingParcel< ParcelType >::iNew::operator()().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const CollidingParcel< ParcelType > &) friend
Member Data Documentation
f_
vector f_ protected
Force on particle due to collisions [N].
Definition at line 126 of file CollidingParcel.H.
Referenced by CollidingParcel< ParcelType >::f(), and CollidingParcel< ParcelType >::readFields().
angularMomentum_
vector angularMomentum_ protected
Angular momentum of Parcel in global reference frame [kg m2/s].
Definition at line 129 of file CollidingParcel.H.
Referenced by CollidingParcel< ParcelType >::angularMomentum(), CollidingParcel< ParcelType >::omega(), and CollidingParcel< ParcelType >::readFields().
torque_
vector torque_ protected
Torque on particle due to collisions in global.
reference frame [Nm]
Definition at line 133 of file CollidingParcel.H.
Referenced by CollidingParcel< ParcelType >::readFields(), and CollidingParcel< ParcelType >::torque().
collisionRecords_
collisionRecordList collisionRecords_ protected
Particle collision records.
Definition at line 136 of file CollidingParcel.H.
Referenced by CollidingParcel< ParcelType >::collisionRecords(), and CollidingParcel< ParcelType >::readFields().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcel.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcel.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcelI.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollidingParcelIO.C