OpenFOAM: ThermoParcel< ParcelType >::iNew Class Reference
ThermoParcel< ParcelType >::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< ThermoParcel< ParcelType > > operator() (Istream &is) const
Detailed Description
template<class ParcelType>
class Foam::ThermoParcel< ParcelType >::iNew
Factory class to read-construct particles used for.
parallel transfer
Definition at line 340 of file ThermoParcel.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 346 of file ThermoParcel.H.
Member Function Documentation
operator()()
autoPtr<ThermoParcel<ParcelType> > operator() (Istream & is) const inline
Definition at line 351 of file ThermoParcel.H.
References Foam::constant::universal::c, ThermoParcel< ParcelType >::calc(), ThermoParcel< ParcelType >::calcSurfaceValues(), ThermoParcel< ParcelType >::cellValueSourceCorrection(), ThermoParcel< ParcelType >::Cp(), ThermoParcel< ParcelType >::Cpc(), ThermoParcel< ParcelType >::hs(), Pr(), ThermoParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::setCellValues(), ThermoParcel< ParcelType >::T(), ThermoParcel< ParcelType >::Tc(), and ThermoParcel< ParcelType >::writeFields().
The documentation for this class was generated from the following file:
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcel.H