OpenFOAM: KinematicParcel< ParcelType >::constantProperties Class Reference
KinematicParcel< ParcelType >::constantProperties Class Reference
Class to hold kinematic particle constant properties.
Public Member Functions
constantProperties ()
Null constructor.
constantProperties (const constantProperties &cp)
Copy constructor.
constantProperties (const dictionary &parentDict)
Construct from dictionary.
const dictionary & dict () const
Return const access to the constant properties dictionary.
label parcelTypeId () const
Return const access to the parcel type id.
scalar rhoMin () const
Return const access to the minimum density.
scalar rho0 () const
Return const access to the particle density.
scalar minParcelMass () const
Return const access to the minimum parcel mass.
Protected Attributes
const dictionary dict_
Constant properties dictionary.
Detailed Description
template<class ParcelType>
class Foam::KinematicParcel< ParcelType >::constantProperties
Class to hold kinematic particle constant properties.
Definition at line 92 of file KinematicParcel.H.
Constructor & Destructor Documentation
constantProperties() [1/3]
constantProperties () inline
Null constructor.
Definition at line 34 of file KinematicParcelI.H.
Referenced by KinematicParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [2/3]
constantProperties (const constantProperties & cp) inline
Copy constructor.
Definition at line 46 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [3/3]
constantProperties (const dictionary & parentDict) inline
Construct from dictionary.
Definition at line 60 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::KinematicParcel().
Member Function Documentation
dict()
const Foam::dictionary & dict () const inline
Return const access to the constant properties dictionary.
Definition at line 136 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::constantProperties::dict_.
parcelTypeId()
Foam::label parcelTypeId () const inline
Return const access to the parcel type id.
Definition at line 144 of file KinematicParcelI.H.
References demandDrivenEntry< Type >::value().
rhoMin()
Foam::scalar rhoMin () const inline
Return const access to the minimum density.
Definition at line 152 of file KinematicParcelI.H.
References demandDrivenEntry< Type >::value().
rho0()
Foam::scalar rho0 () const inline
Return const access to the particle density.
Definition at line 160 of file KinematicParcelI.H.
References demandDrivenEntry< Type >::value().
minParcelMass()
Foam::scalar minParcelMass () const inline
Return const access to the minimum parcel mass.
Definition at line 168 of file KinematicParcelI.H.
References demandDrivenEntry< Type >::value().
Member Data Documentation
dict_
const dictionary dict_ protected
Constant properties dictionary.
Definition at line 99 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::constantProperties::dict().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.H
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcelI.H