OpenFOAM: ReactingParcel< ParcelType >::constantProperties Class Reference
ReactingParcel< ParcelType >::constantProperties Class Reference
Class to hold reacting parcel constant properties.
Public Member Functions
constantProperties ()
Null constructor.
constantProperties (const constantProperties &cp)
Copy constructor.
constantProperties (const dictionary &parentDict)
Construct from dictionary.
scalar pMin () const
Return const access to the minimum pressure.
bool constantVolume () const
Return const access to the constant volume flag.
Detailed Description
template<class ParcelType>
class Foam::ReactingParcel< ParcelType >::constantProperties
Class to hold reacting parcel constant properties.
Definition at line 78 of file ReactingParcel.H.
Constructor & Destructor Documentation
constantProperties() [1/3]
constantProperties () inline
Null constructor.
Definition at line 30 of file ReactingParcelI.H.
Referenced by ReactingParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [2/3]
constantProperties (const constantProperties & cp) inline
Copy constructor.
Definition at line 40 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [3/3]
constantProperties (const dictionary & parentDict) inline
Construct from dictionary.
Definition at line 52 of file ReactingParcelI.H.
References ReactingParcel< ParcelType >::ReactingParcel().
Member Function Documentation
pMin()
Foam::scalar pMin () const inline
Return const access to the minimum pressure.
Definition at line 129 of file ReactingParcelI.H.
References demandDrivenEntry< Type >::value().
constantVolume()
bool constantVolume () const inline
Return const access to the constant volume flag.
Definition at line 137 of file ReactingParcelI.H.
References demandDrivenEntry< Type >::value().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcelI.H