OpenFOAM: ReactingMultiphaseParcel< ParcelType > Class Template Reference
ReactingMultiphaseParcel< ParcelType > Class Template Reference
Multiphase variant of the reacting parcel class with one/two-way coupling with the continuous phase.
Classes
class constantProperties
Class to hold reacting multiphase particle constant properties.
class iNew
Factory class to read-construct particles used for.
Public Member Functions
TypeName ("ReactingMultiphaseParcel")
Runtime type information.
AddToPropertyList (ParcelType, " nGas(Y1..YN)"+" nLiquid(Y1..YN)"+" nSolid(Y1..YN)")
String representation of properties.
ReactingMultiphaseParcel (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti)
Construct from owner, position, and cloud owner.
ReactingMultiphaseParcel (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y0, const scalarField &YGas0, const scalarField &YLiquid0, const scalarField &YSolid0, const constantProperties &constProps)
Construct from components.
ReactingMultiphaseParcel (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
ReactingMultiphaseParcel (const ReactingMultiphaseParcel &p)
Construct as a copy.
ReactingMultiphaseParcel (const ReactingMultiphaseParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
const scalarField & YGas () const
Return const access to mass fractions of gases.
const scalarField & YLiquid () const
Return const access to mass fractions of liquids.
const scalarField & YSolid () const
Return const access to mass fractions of solids.
label canCombust () const
Return const access to the canCombust flag.
scalarField & YGas ()
Return access to mass fractions of gases.
scalarField & YLiquid ()
Return access to mass fractions of liquids.
scalarField & YSolid ()
Return access to mass fractions of solids.
label & canCombust ()
Return access to the canCombust flag.
template<class TrackData >
void setCellValues (TrackData &td, const scalar dt, const label celli)
Set cell values.
template<class TrackData >
void cellValueSourceCorrection (TrackData &td, const scalar dt, const label celli)
Correct cell values using latest transfer information.
template<class TrackData >
void calc (TrackData &td, const scalar dt, const label celli)
Update parcel properties over the time interval.
template<class TrackData >
Foam::scalar CpEff (TrackData &td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
template<class TrackData >
Foam::scalar HsEff (TrackData &td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
template<class TrackData >
Foam::scalar LEff (TrackData &td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
Read.
template<class CloudType >
static void readFields (CloudType &c)
Read - no composition.
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
Write.
template<class CloudType >
static void writeFields (const CloudType &c)
Read - composition supplied.
Static Public Attributes
static const label GAS
static const label LIQ
static const label SLD
Protected Member Functions
template<class TrackData >
void calcDevolatilisation (TrackData &td, const scalar dt, const scalar age, const scalar Ts, const scalar d, const scalar T, const scalar mass, const scalar mass0, const scalarField &YGasEff, const scalarField &YLiquidEff, const scalarField &YSolidEff, label &canCombust, scalarField &dMassDV, scalar &Sh, scalar &N, scalar &NCpW, scalarField &Cs) const
Calculate Devolatilisation.
template<class TrackData >
void calcSurfaceReactions (TrackData &td, const scalar dt, const label celli, const scalar d, const scalar T, const scalar mass, const label canCombust, const scalar N, const scalarField &YMix, const scalarField &YGas, const scalarField &YLiquid, const scalarField &YSolid, scalarField &dMassSRGas, scalarField &dMassSRLiquid, scalarField &dMassSRSolid, scalarField &dMassSRCarrier, scalar &Sh, scalar &dhsTrans) const
Calculate surface reactions.
Protected Attributes
scalarField YGas_
Mass fractions of gases [].
scalarField YLiquid_
Mass fractions of liquids [].
scalarField YSolid_
Mass fractions of solids [].
label canCombust_
Flag to identify if the particle can devolatilise and combust.
Friends
Ostream & operator (Ostream &, const ReactingMultiphaseParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ReactingMultiphaseParcel< ParcelType >
Multiphase variant of the reacting parcel class with one/two-way coupling with the continuous phase.
Source files
ReactingMultiphaseParcel.H
ReactingMultiphaseParcelI.H
ReactingMultiphaseParcel.C
ReactingMultiphaseParcelIO.C
Definition at line 50 of file ReactingMultiphaseParcel.H.
Constructor & Destructor Documentation
ReactingMultiphaseParcel() [1/5]
ReactingMultiphaseParcel (const polyMesh & mesh, const vector & position, const label celli, const label tetFacei, const label tetPti) inline
Construct from owner, position, and cloud owner.
Other properties initialised as null
Definition at line 69 of file ReactingMultiphaseParcelI.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), ReactingMultiphaseParcel< ParcelType >::clone(), and ReactingMultiphaseParcel< ParcelType >::constantProperties::constantProperties().
ReactingMultiphaseParcel() [2/5]
ReactingMultiphaseParcel (const polyMesh & mesh, const vector & position, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y0, const scalarField & YGas0, const scalarField & YLiquid0, const scalarField & YSolid0, const constantProperties & constProps) inline
Construct from components.
Definition at line 87 of file ReactingMultiphaseParcelI.H.
ReactingMultiphaseParcel() [3/5]
ReactingMultiphaseParcel (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 46 of file ReactingMultiphaseParcelIO.C.
References IOstream::check(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer().
ReactingMultiphaseParcel() [4/5]
ReactingMultiphaseParcel (const ReactingMultiphaseParcel< ParcelType > & p)
Construct as a copy.
ReactingMultiphaseParcel() [5/5]
ReactingMultiphaseParcel (const ReactingMultiphaseParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
calcDevolatilisation()
void calcDevolatilisation (TrackData & td, const scalar dt, const scalar age, const scalar Ts, const scalar d, const scalar T, const scalar mass, const scalar mass0, const scalarField & YGasEff, const scalarField & YLiquidEff, const scalarField & YSolidEff, label & canCombust, scalarField & dMassDV, scalar & Sh, scalar & N, scalar & NCpW, scalarField & Cs) const protected
Calculate Devolatilisation.
Definition at line 493 of file ReactingMultiphaseParcel.C.
References beta(), ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), CompositionModel< CloudType >::carrier(), Foam::cbrt(), composition, forAll, CompositionModel< CloudType >::localToCarrierId(), Foam::max(), Foam::pow(), Foam::constant::thermodynamic::RR, Foam::sqr(), Foam::sqrt(), and Foam::sum().
Referenced by ReactingMultiphaseParcel< ParcelType >::calc().
calcSurfaceReactions()
void calcSurfaceReactions (TrackData & td, const scalar dt, const label celli, const scalar d, const scalar T, const scalar mass, const label canCombust, const scalar N, const scalarField & YMix, const scalarField & YGas, const scalarField & YLiquid, const scalarField & YSolid, scalarField & dMassSRGas, scalarField & dMassSRLiquid, scalarField & dMassSRSolid, scalarField & dMassSRCarrier, scalar & Sh, scalar & dhsTrans) const protected
Calculate surface reactions.
Definition at line 594 of file ReactingMultiphaseParcel.C.
References ReactingMultiphaseParcel< ParcelType >::canCombust_, mesh, Foam::min(), ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel(), Foam::sum(), ReactingMultiphaseParcel< ParcelType >::YGas_, ReactingMultiphaseParcel< ParcelType >::YLiquid_, and ReactingMultiphaseParcel< ParcelType >::YSolid_.
Referenced by ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation().
TypeName()
TypeName ("ReactingMultiphaseParcel< ParcelType >")
Runtime type information.
AddToPropertyList()
AddToPropertyList (ParcelType , " nGas(Y1..YN)"+" nLiquid(Y1..YN)"+" nSolid(Y1..YN)")
String representation of properties.
clone() [1/2]
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 326 of file ReactingMultiphaseParcel.H.
References ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel().
clone() [2/2]
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 332 of file ReactingMultiphaseParcel.H.
References ReactingMultiphaseParcel< ParcelType >::ReactingMultiphaseParcel().
YGas() [1/2]
const Foam::scalarField & YGas () const inline
Return const access to mass fractions of gases.
Definition at line 173 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YGas_, and ReactingMultiphaseParcel< ParcelType >::YLiquid().
Referenced by ReactingMultiphaseParcel< ParcelType >::constantProperties::hRetentionCoeff(), ReactingMultiphaseParcel< ParcelType >::iNew::operator()(), and ReactingMultiphaseParcel< ParcelType >::writeFields().
YLiquid() [1/2]
const Foam::scalarField & YLiquid () const inline
Return const access to mass fractions of liquids.
Definition at line 181 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YLiquid_, and ReactingMultiphaseParcel< ParcelType >::YSolid().
Referenced by ReactingMultiphaseParcel< ParcelType >::iNew::operator()(), ReactingMultiphaseParcel< ParcelType >::writeFields(), and ReactingMultiphaseParcel< ParcelType >::YGas().
YSolid() [1/2]
const Foam::scalarField & YSolid () const inline
Return const access to mass fractions of solids.
Definition at line 189 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YSolid_.
Referenced by ReactingMultiphaseParcel< ParcelType >::iNew::operator()(), ReactingMultiphaseParcel< ParcelType >::writeFields(), and ReactingMultiphaseParcel< ParcelType >::YLiquid().
canCombust() [1/2]
Foam::label canCombust () const inline
Return const access to the canCombust flag.
Definition at line 197 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::canCombust_.
Referenced by ReactingMultiphaseParcel< ParcelType >::iNew::operator()().
YGas() [2/2]
Foam::scalarField & YGas () inline
Return access to mass fractions of gases.
Definition at line 204 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YGas_.
YLiquid() [2/2]
Foam::scalarField & YLiquid () inline
Return access to mass fractions of liquids.
Definition at line 211 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YLiquid_.
YSolid() [2/2]
Foam::scalarField & YSolid () inline
Return access to mass fractions of solids.
Definition at line 218 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YSolid_.
canCombust() [2/2]
Foam::label & canCombust () inline
Return access to the canCombust flag.
Definition at line 225 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::canCombust_.
setCellValues()
void setCellValues (TrackData & td, const scalar dt, const label celli)
Set cell values.
Definition at line 135 of file ReactingMultiphaseParcel.C.
References ReactingMultiphaseParcel< ParcelType >::cellValueSourceCorrection().
Referenced by ReactingMultiphaseParcel< ParcelType >::LEff(), and ReactingMultiphaseParcel< ParcelType >::iNew::operator()().
cellValueSourceCorrection()
void cellValueSourceCorrection (TrackData & td, const scalar dt, const label celli)
Correct cell values using latest transfer information.
Definition at line 148 of file ReactingMultiphaseParcel.C.
References ReactingMultiphaseParcel< ParcelType >::calc().
Referenced by ReactingMultiphaseParcel< ParcelType >::iNew::operator()(), and ReactingMultiphaseParcel< ParcelType >::setCellValues().
calc()
void calc (TrackData & td, const scalar dt, const label celli)
Update parcel properties over the time interval.
Definition at line 162 of file ReactingMultiphaseParcel.C.
References ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), CompositionModel< CloudType >::carrier(), Foam::cbrt(), composition, forAll, CompositionModel< CloudType >::idGas(), CompositionModel< CloudType >::idLiquid(), CompositionModel< CloudType >::idSolid(), CompositionModel< CloudType >::localToCarrierId(), Foam::constant::mathematical::pi(), Foam::pow4(), Foam::Re(), Sh, Foam::fvc::Su(), and Foam::Zero.
Referenced by ReactingMultiphaseParcel< ParcelType >::cellValueSourceCorrection(), and ReactingMultiphaseParcel< ParcelType >::iNew::operator()().
readFields() [1/2]
void readFields (CloudType & c, const CompositionType & compModel) static
Read.
Definition at line 106 of file ReactingMultiphaseParcelIO.C.
References Cloud< ParticleType >::fieldIOobject(), forAll, forAllIter, p, Foam::readFields(), List< T >::size(), Cloud< ParticleType >::size(), ReactingMultiphaseParcel< ParcelType >::YGas_, ReactingMultiphaseParcel< ParcelType >::YLiquid_, and ReactingMultiphaseParcel< ParcelType >::YSolid_.
Referenced by ReactingMultiphaseParcel< ParcelType >::iNew::operator()(), and ReactingMultiphaseParcel< ParcelType >::readFields().
readFields() [2/2]
void readFields (CloudType & c) static
Read - no composition.
Definition at line 92 of file ReactingMultiphaseParcelIO.C.
References Foam::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), and Cloud< ParticleType >::size().
writeFields() [1/2]
void writeFields (const CloudType & c, const CompositionType & compModel) static
Write.
Definition at line 222 of file ReactingMultiphaseParcelIO.C.
References Cloud< ParticleType >::fieldIOobject(), forAll, forAllConstIter(), p, Cloud< ParticleType >::size(), ReactingMultiphaseParcel< ParcelType >::YGas(), ReactingMultiphaseParcel< ParcelType >::YLiquid(), and ReactingMultiphaseParcel< ParcelType >::YSolid().
Referenced by ReactingMultiphaseParcel< ParcelType >::iNew::operator()(), and ReactingMultiphaseParcel< ParcelType >::writeFields().
writeFields() [2/2]
void writeFields (const CloudType & c) static
Read - composition supplied.
Definition at line 213 of file ReactingMultiphaseParcelIO.C.
References ReactingMultiphaseParcel< ParcelType >::writeFields().
CpEff()
Foam::scalar CpEff (TrackData & td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Definition at line 48 of file ReactingMultiphaseParcel.C.
HsEff()
Foam::scalar HsEff (TrackData & td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Definition at line 67 of file ReactingMultiphaseParcel.C.
LEff()
Foam::scalar LEff (TrackData & td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Definition at line 86 of file ReactingMultiphaseParcel.C.
References Foam::max(), and ReactingMultiphaseParcel< ParcelType >::setCellValues().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const ReactingMultiphaseParcel< ParcelType > &) friend
Referenced by ReactingMultiphaseParcel< ParcelType >::iNew::iNew().
Member Data Documentation
GAS
const Foam::label GAS static
Definition at line 78 of file ReactingMultiphaseParcel.H.
LIQ
const Foam::label LIQ static
Definition at line 79 of file ReactingMultiphaseParcel.H.
SLD
const Foam::label SLD static
Definition at line 80 of file ReactingMultiphaseParcel.H.
YGas_
scalarField YGas_ protected
Mass fractions of gases [].
Definition at line 186 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), ReactingMultiphaseParcel< ParcelType >::readFields(), and ReactingMultiphaseParcel< ParcelType >::YGas().
YLiquid_
scalarField YLiquid_ protected
Mass fractions of liquids [].
Definition at line 189 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), ReactingMultiphaseParcel< ParcelType >::readFields(), and ReactingMultiphaseParcel< ParcelType >::YLiquid().
YSolid_
scalarField YSolid_ protected
Mass fractions of solids [].
Definition at line 192 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), ReactingMultiphaseParcel< ParcelType >::readFields(), and ReactingMultiphaseParcel< ParcelType >::YSolid().
canCombust_
label canCombust_ protected
Flag to identify if the particle can devolatilise and combust.
Combustion possible only after volatile content falls below threshold value. States include: 0 = can devolatilise, cannot combust but can change 1 = can devolatilise, can combust -1 = cannot devolatilise or combust, and cannot change
Definition at line 200 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::calcSurfaceReactions(), and ReactingMultiphaseParcel< ParcelType >::canCombust().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcel.C
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcelI.H
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcelIO.C