OpenFOAM: ThermoParcel< ParcelType >::constantProperties Class Reference
ThermoParcel< ParcelType >::constantProperties Class Reference
Class to hold thermo particle constant properties.
Public Member Functions
constantProperties ()
Null constructor.
constantProperties (const constantProperties &cp)
Copy constructor.
constantProperties (const dictionary &parentDict)
Construct from dictionary.
scalar T0 () const
Return const access to the particle initial temperature [K].
scalar TMin () const
Return const access to minimum temperature [K].
scalar TMax () const
Return const access to maximum temperature [K].
void setTMax (const scalar TMax)
Set the maximum temperature [K].
scalar Cp0 () const
Return const access to the particle specific heat capacity.
scalar epsilon0 () const
Return const access to the particle emissivity [].
scalar f0 () const
Return const access to the particle scattering factor [].
Detailed Description
template<class ParcelType>
class Foam::ThermoParcel< ParcelType >::constantProperties
Class to hold thermo particle constant properties.
Definition at line 78 of file ThermoParcel.H.
Constructor & Destructor Documentation
constantProperties() [1/3]
constantProperties () inline
Null constructor.
Definition at line 29 of file ThermoParcelI.H.
Referenced by ThermoParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [2/3]
constantProperties (const constantProperties & cp) inline
Copy constructor.
Definition at line 43 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [3/3]
constantProperties (const dictionary & parentDict) inline
Construct from dictionary.
Definition at line 59 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::ThermoParcel().
Member Function Documentation
T0()
Foam::scalar T0 () const inline
Return const access to the particle initial temperature [K].
Definition at line 138 of file ThermoParcelI.H.
References demandDrivenEntry< Type >::value().
TMin()
Foam::scalar TMin () const inline
Return const access to minimum temperature [K].
Definition at line 146 of file ThermoParcelI.H.
References demandDrivenEntry< Type >::value().
TMax()
Foam::scalar TMax () const inline
Return const access to maximum temperature [K].
Definition at line 154 of file ThermoParcelI.H.
References demandDrivenEntry< Type >::value().
setTMax()
void setTMax (const scalar TMax) inline
Set the maximum temperature [K].
Definition at line 162 of file ThermoParcelI.H.
References demandDrivenEntry< Type >::setValue().
Cp0()
Foam::scalar Cp0 () const inline
Return const access to the particle specific heat capacity.
[J/(kg.K)]
Definition at line 170 of file ThermoParcelI.H.
References demandDrivenEntry< Type >::value().
epsilon0()
Foam::scalar epsilon0 () const inline
Return const access to the particle emissivity [].
Active for radiation only
Definition at line 178 of file ThermoParcelI.H.
References demandDrivenEntry< Type >::value().
f0()
Foam::scalar f0 () const inline
Return const access to the particle scattering factor [].
Active for radiation only
Definition at line 186 of file ThermoParcelI.H.
References demandDrivenEntry< Type >::value().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcel.H
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcelI.H