OpenFOAM: KinematicParcel< ParcelType > Class Template Reference
KinematicParcel< ParcelType > Class Template Reference
Kinematic parcel class with rotational motion (as spherical particles only) and one/two-way coupling with the continuous phase.
Classes
class constantProperties
Class to hold kinematic particle constant properties.
class iNew
Factory class to read-construct particles used for.
class TrackingData
Public Member Functions
TypeName ("KinematicParcel")
Runtime type information.
AddToPropertyList (ParcelType, " active"+" typeId"+" nParticle"+" d"+" dTarget "+" (Ux Uy Uz)"+" rho"+" age"+" tTurb"+" (UTurbx UTurby UTurbz)")
String representation of properties.
KinematicParcel (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti)
Construct from owner, position, and cloud owner.
KinematicParcel (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &torque0, const constantProperties &constProps)
Construct from components.
KinematicParcel (const polyMesh &mesh, Istream &is, bool readFields=true)
Construct from Istream.
KinematicParcel (const KinematicParcel &p)
Construct as a copy.
KinematicParcel (const KinematicParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
bool active () const
Return const access to active flag.
label typeId () const
Return const access to type id.
scalar nParticle () const
Return const access to number of particles.
scalar d () const
Return const access to diameter.
scalar dTarget () const
Return const access to target diameter.
const vector & U () const
Return const access to velocity.
scalar rho () const
Return const access to density.
scalar age () const
Return const access to the age.
scalar tTurb () const
Return const access to time spent in turbulent eddy.
const vector & UTurb () const
Return const access to turbulent velocity fluctuation.
scalar rhoc () const
Return const access to carrier density [kg/m3].
const vector & Uc () const
Return const access to carrier velocity [m/s].
scalar muc () const
Return const access to carrier viscosity [Pa.s].
bool & active ()
Return const access to active flag.
label & typeId ()
Return access to type id.
scalar & nParticle ()
Return access to number of particles.
scalar & d ()
Return access to diameter.
scalar & dTarget ()
Return access to target diameter.
vector & U ()
Return access to velocity.
scalar & rho ()
Return access to density.
scalar & age ()
Return access to the age.
scalar & tTurb ()
Return access to time spent in turbulent eddy.
vector & UTurb ()
Return access to turbulent velocity fluctuation.
label faceInterpolation () const
Return the index of the face used in the interpolation routine.
scalar massCell (const label celli) const
Cell owner mass.
scalar mass () const
Particle mass.
scalar momentOfInertia () const
Particle moment of inertia around diameter axis.
scalar volume () const
Particle volume.
scalar areaP () const
Particle projected area.
scalar areaS () const
Particle surface area.
scalar Re (const vector &U, const scalar d, const scalar rhoc, const scalar muc) const
Reynolds number.
scalar We (const vector &U, const scalar d, const scalar rhoc, const scalar sigma) const
Weber number.
scalar Eo (const vector &a, const scalar d, const scalar sigma) const
Eotvos number.
template<class TrackData >
void setCellValues (TrackData &td, const scalar dt, const label celli)
Set cell values.
template<class TrackData >
void cellValueSourceCorrection (TrackData &td, const scalar dt, const label celli)
Correct cell values using latest transfer information.
template<class TrackData >
void calc (TrackData &td, const scalar dt, const label celli)
Update parcel properties over the time interval.
template<class TrackData >
bool move (TrackData &td, const scalar trackTime)
Move the parcel.
void hitFace (int &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
void hitFace (TrackData &td)
Overridable function to handle the particle hitting a face.
template<class TrackData >
bool hitPatch (const polyPatch &p, TrackData &td, const label patchi, const scalar trackFraction, const tetIndices &tetIs)
Overridable function to handle the particle hitting a patch.
template<class TrackData >
void hitProcessorPatch (const processorPolyPatch &, TrackData &td)
Overridable function to handle the particle hitting a.
template<class TrackData >
void hitWallPatch (const wallPolyPatch &, TrackData &td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
template<class TrackData >
void hitPatch (const polyPatch &, TrackData &td)
Overridable function to handle the particle hitting a polyPatch.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
virtual scalar wallImpactDistance (const vector &n) const
The nearest distance to a wall that the particle can be.
template<class TrackData >
const Foam::vector calcVelocity (TrackData &td, const scalar dt, const label celli, const scalar Re, const scalar mu, const scalar mass, const vector &Su, vector &dUTrans, scalar &Spu) const
Static Public Member Functions
static scalar volume (const scalar d)
Particle volume for a given diameter.
static scalar areaP (const scalar d)
Projected area for given diameter.
static scalar areaS (const scalar d)
Surface area for given diameter.
template<class CloudType >
static void readFields (CloudType &c)
Read.
template<class CloudType >
static void writeFields (const CloudType &c)
Write.
Protected Member Functions
template<class TrackData >
const vector calcVelocity (TrackData &td, const scalar dt, const label celli, const scalar Re, const scalar mu, const scalar mass, const vector &Su, vector &dUTrans, scalar &Spu) const
Calculate new particle velocity.
Protected Attributes
bool active_
Active flag - tracking inactive when active = false.
label typeId_
Parcel type id.
scalar nParticle_
Number of particles in Parcel.
scalar d_
Diameter [m].
scalar dTarget_
Target diameter [m].
vector U_
Velocity of Parcel [m/s].
scalar rho_
Density [kg/m3].
scalar age_
Age [s].
scalar tTurb_
Time spent in turbulent eddy [s].
vector UTurb_
Turbulent velocity fluctuation [m/s].
scalar rhoc_
Density [kg/m3].
vector Uc_
Velocity [m/s].
scalar muc_
Viscosity [Pa.s].
Friends
Ostream & operator (Ostream &, const KinematicParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::KinematicParcel< ParcelType >
Kinematic parcel class with rotational motion (as spherical particles only) and one/two-way coupling with the continuous phase.
Sub-models include:
drag
turbulent dispersion
wall interactions
Source files
KinematicParcel.H
KinematicParcelI.H
KinematicParcel.C
KinematicParcelIO.C
Definition at line 60 of file KinematicParcel.H.
Constructor & Destructor Documentation
KinematicParcel() [1/5]
KinematicParcel (const polyMesh & mesh, const vector & position, const label celli, const label tetFacei, const label tetPti) inline
Construct from owner, position, and cloud owner.
Other properties initialised as null
Definition at line 74 of file KinematicParcelI.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::clone(), and KinematicParcel< ParcelType >::constantProperties::constantProperties().
KinematicParcel() [2/5]
KinematicParcel (const polyMesh & mesh, const vector & position, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & torque0, const constantProperties & constProps) inline
Construct from components.
Definition at line 101 of file KinematicParcelI.H.
KinematicParcel() [3/5]
KinematicParcel (const polyMesh & mesh, Istream & is, bool readFields = true)
Construct from Istream.
Definition at line 49 of file KinematicParcelIO.C.
References IOstream::check(), IOstream::format(), Istream::read(), Foam::readBool(), Foam::readLabel(), and readScalar.
KinematicParcel() [4/5]
KinematicParcel (const KinematicParcel< ParcelType > & p)
Construct as a copy.
KinematicParcel() [5/5]
KinematicParcel (const KinematicParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
calcVelocity() [1/2]
const vector calcVelocity (TrackData & td, const scalar dt, const label celli, const scalar Re, const scalar mu, const scalar mass, const vector & Su, vector & dUTrans, scalar & Spu) const protected
Calculate new particle velocity.
Referenced by KinematicParcel< ParcelType >::calc().
TypeName()
TypeName ("KinematicParcel< ParcelType >")
Runtime type information.
AddToPropertyList()
AddToPropertyList (ParcelType , " active"+" typeId"+" nParticle"+" d"+" dTarget "+" (Ux Uy Uz)"+" rho"+" age"+" tTurb"+" (UTurbx UTurby UTurbz)")
String representation of properties.
clone() [1/2]
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 364 of file KinematicParcel.H.
References KinematicParcel< ParcelType >::KinematicParcel().
clone() [2/2]
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 370 of file KinematicParcel.H.
References KinematicParcel< ParcelType >::KinematicParcel().
active() [1/2]
bool active () const inline
Return const access to active flag.
Definition at line 177 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::active_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
typeId() [1/2]
Foam::label typeId () const inline
Return const access to type id.
Definition at line 184 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::typeId_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
nParticle() [1/2]
Foam::scalar nParticle () const inline
Return const access to number of particles.
Definition at line 191 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::nParticle_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
d() [1/2]
Foam::scalar d () const inline
Return const access to diameter.
Definition at line 198 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::d_.
Referenced by KinematicParcel< ParcelType >::areaS(), KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
dTarget() [1/2]
Foam::scalar dTarget () const inline
Return const access to target diameter.
Definition at line 205 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::dTarget_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
U() [1/2]
const Foam::vector & U () const inline
Return const access to velocity.
Definition at line 212 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::U_.
Referenced by MPPICParcel< ParcelType >::move(), KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
rho() [1/2]
Foam::scalar rho () const inline
Return const access to density.
Definition at line 219 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::rho_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
age() [1/2]
Foam::scalar age () const inline
Return const access to the age.
Definition at line 226 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::age_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
tTurb() [1/2]
Foam::scalar tTurb () const inline
Return const access to time spent in turbulent eddy.
Definition at line 233 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::tTurb_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
UTurb() [1/2]
const Foam::vector & UTurb () const inline
Return const access to turbulent velocity fluctuation.
Definition at line 240 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::UTurb_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::writeFields().
rhoc()
Foam::scalar rhoc () const inline
Return const access to carrier density [kg/m3].
Definition at line 247 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::rhoc_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
Uc()
const Foam::vector & Uc () const inline
Return const access to carrier velocity [m/s].
Definition at line 254 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::Uc_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
muc()
Foam::scalar muc () const inline
Return const access to carrier viscosity [Pa.s].
Definition at line 261 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::muc_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
active() [2/2]
bool & active () inline
Return const access to active flag.
Definition at line 268 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::active_.
typeId() [2/2]
Foam::label & typeId () inline
Return access to type id.
Definition at line 275 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::typeId_.
nParticle() [2/2]
Foam::scalar & nParticle () inline
Return access to number of particles.
Definition at line 282 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::nParticle_.
d() [2/2]
Foam::scalar & d () inline
Return access to diameter.
Definition at line 289 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::d_.
dTarget() [2/2]
Foam::scalar & dTarget () inline
Return access to target diameter.
Definition at line 296 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::dTarget_.
U() [2/2]
Foam::vector & U () inline
Return access to velocity.
Definition at line 303 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::U_.
rho() [2/2]
Foam::scalar & rho () inline
Return access to density.
Definition at line 310 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::rho_.
age() [2/2]
Foam::scalar & age () inline
Return access to the age.
Definition at line 317 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::age_.
tTurb() [2/2]
Foam::scalar & tTurb () inline
Return access to time spent in turbulent eddy.
Definition at line 324 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::tTurb_.
UTurb() [2/2]
Foam::vector & UTurb () inline
Return access to turbulent velocity fluctuation.
Definition at line 331 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::UTurb_.
faceInterpolation()
Foam::label faceInterpolation () const inline
Return the index of the face used in the interpolation routine.
Definition at line 338 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::massCell().
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
massCell()
Foam::scalar massCell (const label celli) const inline
Cell owner mass.
Definition at line 354 of file KinematicParcelI.H.
References mesh, and KinematicParcel< ParcelType >::rhoc_.
Referenced by KinematicParcel< ParcelType >::faceInterpolation(), and KinematicParcel< ParcelType >::iNew::operator()().
mass()
Foam::scalar mass () const inline
Particle mass.
Definition at line 363 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::rho_, and KinematicParcel< ParcelType >::volume().
Referenced by KinematicParcel< ParcelType >::momentOfInertia(), and KinematicParcel< ParcelType >::iNew::operator()().
momentOfInertia()
Foam::scalar momentOfInertia () const inline
Particle moment of inertia around diameter axis.
Definition at line 370 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::d_, KinematicParcel< ParcelType >::mass(), and Foam::sqr().
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
volume() [1/2]
Foam::scalar volume () const inline
Particle volume.
Definition at line 377 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::d_.
Referenced by KinematicParcel< ParcelType >::mass(), and KinematicParcel< ParcelType >::iNew::operator()().
volume() [2/2]
Foam::scalar volume (const scalar d) inline static
Particle volume for a given diameter.
Definition at line 384 of file KinematicParcelI.H.
References Foam::constant::mathematical::pi(), and Foam::pow3().
areaP() [1/2]
Foam::scalar areaP () const inline
Particle projected area.
Definition at line 391 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::d_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
areaP() [2/2]
Foam::scalar areaP (const scalar d) inline static
Projected area for given diameter.
Definition at line 398 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::areaS().
areaS() [1/2]
Foam::scalar areaS () const inline
Particle surface area.
Definition at line 405 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::d_.
Referenced by KinematicParcel< ParcelType >::areaP(), and KinematicParcel< ParcelType >::iNew::operator()().
areaS() [2/2]
Foam::scalar areaS (const scalar d) inline static
Surface area for given diameter.
Definition at line 412 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::d(), Foam::constant::mathematical::pi(), and KinematicParcel< ParcelType >::Re().
Re()
Foam::scalar Re (const vector & U, const scalar d, const scalar rhoc, const scalar muc) const inline
Reynolds number.
Definition at line 420 of file KinematicParcelI.H.
References Foam::mag(), KinematicParcel< ParcelType >::Uc_, and KinematicParcel< ParcelType >::We().
Referenced by KinematicParcel< ParcelType >::areaS(), and KinematicParcel< ParcelType >::iNew::operator()().
We()
Foam::scalar We (const vector & U, const scalar d, const scalar rhoc, const scalar sigma) const inline
Weber number.
Definition at line 433 of file KinematicParcelI.H.
References KinematicParcel< ParcelType >::Eo(), Foam::magSqr(), and KinematicParcel< ParcelType >::Uc_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::Re().
Eo()
Foam::scalar Eo (const vector & a, const scalar d, const scalar sigma) const inline
Eotvos number.
Definition at line 446 of file KinematicParcelI.H.
References Foam::mag(), KinematicParcel< ParcelType >::rho_, KinematicParcel< ParcelType >::rhoc_, Foam::sqr(), and KinematicParcel< ParcelType >::U_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::We().
setCellValues()
void setCellValues (TrackData & td, const scalar dt, const label celli)
Set cell values.
Definition at line 42 of file KinematicParcel.C.
References KinematicParcel< ParcelType >::cellValueSourceCorrection(), Foam::endl(), Foam::nl, and WarningInFunction.
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
cellValueSourceCorrection()
void cellValueSourceCorrection (TrackData & td, const scalar dt, const label celli)
Correct cell values using latest transfer information.
Definition at line 84 of file KinematicParcel.C.
References KinematicParcel< ParcelType >::calc().
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::setCellValues().
calc()
void calc (TrackData & td, const scalar dt, const label celli)
Update parcel properties over the time interval.
Definition at line 97 of file KinematicParcel.C.
References KinematicParcel< ParcelType >::calcVelocity(), Foam::Re(), Foam::fvc::Su(), and Foam::Zero.
Referenced by KinematicParcel< ParcelType >::cellValueSourceCorrection(), and KinematicParcel< ParcelType >::iNew::operator()().
move()
bool move (TrackData & td, const scalar trackTime)
Move the parcel.
Definition at line 254 of file KinematicParcel.C.
References polyMesh::boundaryMesh(), Foam::meshTools::constrainToMeshCentre(), Foam::mag(), maxCo, and Foam::min().
Referenced by KinematicParcel< ParcelType >::calcVelocity(), and KinematicParcel< ParcelType >::iNew::operator()().
hitFace() [1/2]
void hitFace (int & td)
Overridable function to handle the particle hitting a face.
without trackData
Definition at line 379 of file KinematicParcel.C.
References KinematicParcel< ParcelType >::hitPatch().
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
hitFace() [2/2]
void hitFace (TrackData & td)
Overridable function to handle the particle hitting a face.
Definition at line 369 of file KinematicParcel.C.
hitPatch() [1/2]
bool hitPatch (const polyPatch & p, TrackData & td, const label patchi, const scalar trackFraction, const tetIndices & tetIs)
Overridable function to handle the particle hitting a patch.
Executed before other patch-hitting functions
Definition at line 386 of file KinematicParcel.C.
References KinematicParcel< ParcelType >::hitProcessorPatch().
Referenced by KinematicParcel< ParcelType >::hitFace(), KinematicParcel< ParcelType >::hitWallPatch(), and KinematicParcel< ParcelType >::iNew::operator()().
hitProcessorPatch()
void hitProcessorPatch (const processorPolyPatch & , TrackData & td)
Overridable function to handle the particle hitting a.
processorPatch
Definition at line 431 of file KinematicParcel.C.
References KinematicParcel< ParcelType >::hitWallPatch().
Referenced by KinematicParcel< ParcelType >::hitPatch(), and KinematicParcel< ParcelType >::iNew::operator()().
hitWallPatch()
void hitWallPatch (const wallPolyPatch & wpp, TrackData & td, const tetIndices &)
Overridable function to handle the particle hitting a wallPatch.
Definition at line 443 of file KinematicParcel.C.
References KinematicParcel< ParcelType >::hitPatch().
Referenced by KinematicParcel< ParcelType >::hitProcessorPatch(), and KinematicParcel< ParcelType >::iNew::operator()().
hitPatch() [2/2]
void hitPatch (const polyPatch & , TrackData & td)
Overridable function to handle the particle hitting a polyPatch.
Definition at line 456 of file KinematicParcel.C.
transformProperties() [1/2]
void transformProperties (const tensor & T) virtual
Transform the physical properties of the particle.
according to the given transformation tensor
Definition at line 466 of file KinematicParcel.C.
References Foam::transform().
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
transformProperties() [2/2]
void transformProperties (const vector & separation) virtual
Transform the physical properties of the particle.
according to the given separation vector
Definition at line 476 of file KinematicParcel.C.
References KinematicParcel< ParcelType >::wallImpactDistance().
wallImpactDistance()
Foam::scalar wallImpactDistance (const vector & n) const virtual
The nearest distance to a wall that the particle can be.
in the n direction
Definition at line 486 of file KinematicParcel.C.
Referenced by KinematicParcel< ParcelType >::iNew::operator()(), and KinematicParcel< ParcelType >::transformProperties().
readFields()
void readFields (CloudType & c) static
Read.
Definition at line 102 of file KinematicParcelIO.C.
References KinematicParcel< ParcelType >::active_, KinematicParcel< ParcelType >::age_, Cloud< ParticleType >::checkFieldIOobject(), KinematicParcel< ParcelType >::d_, KinematicParcel< ParcelType >::dTarget_, Cloud< ParticleType >::fieldIOobject(), forAllIter, KinematicParcel< ParcelType >::nParticle_, p, Foam::readFields(), rho, KinematicParcel< ParcelType >::rho_, Cloud< ParticleType >::size(), KinematicParcel< ParcelType >::tTurb_, KinematicParcel< ParcelType >::typeId_, U, KinematicParcel< ParcelType >::U_, and KinematicParcel< ParcelType >::UTurb_.
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
writeFields()
void writeFields (const CloudType & c) static
Write.
Definition at line 166 of file KinematicParcelIO.C.
References KinematicParcel< ParcelType >::active(), KinematicParcel< ParcelType >::age(), KinematicParcel< ParcelType >::d(), KinematicParcel< ParcelType >::dTarget(), Cloud< ParticleType >::fieldIOobject(), forAllConstIter(), KinematicParcel< ParcelType >::nParticle(), p, rho, KinematicParcel< ParcelType >::rho(), Cloud< ParticleType >::size(), KinematicParcel< ParcelType >::tTurb(), KinematicParcel< ParcelType >::typeId(), U, KinematicParcel< ParcelType >::U(), KinematicParcel< ParcelType >::UTurb(), and regIOobject::write().
Referenced by KinematicParcel< ParcelType >::iNew::operator()().
calcVelocity() [2/2]
const Foam::vector calcVelocity (TrackData & td, const scalar dt, const label celli, const scalar Re, const scalar mu, const scalar mass, const vector & Su, vector & dUTrans, scalar & Spu) const
Definition at line 148 of file KinematicParcel.C.
References KinematicParcel< ParcelType >::active_, KinematicParcel< ParcelType >::age_, IntegrationScheme< Type >::integrationResult::average(), Foam::meshTools::constrainDirection(), KinematicParcel< ParcelType >::d_, KinematicParcel< ParcelType >::dTarget_, KinematicParcel< ParcelType >::KinematicParcel(), mesh, KinematicParcel< ParcelType >::move(), KinematicParcel< ParcelType >::muc_, KinematicParcel< ParcelType >::nParticle_, p, KinematicParcel< ParcelType >::rho_, KinematicParcel< ParcelType >::rhoc_, forceSuSp::Sp(), Foam::fvc::Su(), forceSuSp::Su(), KinematicParcel< ParcelType >::tTurb_, KinematicParcel< ParcelType >::typeId_, KinematicParcel< ParcelType >::U_, KinematicParcel< ParcelType >::Uc_, KinematicParcel< ParcelType >::UTurb_, and IntegrationScheme< Type >::integrationResult::value().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const KinematicParcel< ParcelType > &) friend
Member Data Documentation
active_
bool active_ protected
Active flag - tracking inactive when active = false.
Definition at line 236 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::active(), KinematicParcel< ParcelType >::calcVelocity(), and KinematicParcel< ParcelType >::readFields().
typeId_
label typeId_ protected
Parcel type id.
Definition at line 239 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::readFields(), and KinematicParcel< ParcelType >::typeId().
nParticle_
scalar nParticle_ protected
Number of particles in Parcel.
Definition at line 242 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::nParticle(), and KinematicParcel< ParcelType >::readFields().
d_
scalar d_ protected
Diameter [m].
Definition at line 245 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::areaP(), KinematicParcel< ParcelType >::areaS(), KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::d(), KinematicParcel< ParcelType >::momentOfInertia(), KinematicParcel< ParcelType >::readFields(), and KinematicParcel< ParcelType >::volume().
dTarget_
scalar dTarget_ protected
Target diameter [m].
Definition at line 248 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::dTarget(), and KinematicParcel< ParcelType >::readFields().
U_
vector U_ protected
Velocity of Parcel [m/s].
Definition at line 251 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::Eo(), KinematicParcel< ParcelType >::readFields(), and KinematicParcel< ParcelType >::U().
rho_
scalar rho_ protected
Density [kg/m3].
Definition at line 254 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::Eo(), KinematicParcel< ParcelType >::mass(), KinematicParcel< ParcelType >::readFields(), and KinematicParcel< ParcelType >::rho().
age_
scalar age_ protected
Age [s].
Definition at line 257 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::age(), KinematicParcel< ParcelType >::calcVelocity(), and KinematicParcel< ParcelType >::readFields().
tTurb_
scalar tTurb_ protected
Time spent in turbulent eddy [s].
Definition at line 260 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::readFields(), and KinematicParcel< ParcelType >::tTurb().
UTurb_
vector UTurb_ protected
Turbulent velocity fluctuation [m/s].
Definition at line 263 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::readFields(), and KinematicParcel< ParcelType >::UTurb().
rhoc_
scalar rhoc_ protected
Density [kg/m3].
Definition at line 269 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::Eo(), KinematicParcel< ParcelType >::massCell(), and KinematicParcel< ParcelType >::rhoc().
Uc_
vector Uc_ protected
Velocity [m/s].
Definition at line 272 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), KinematicParcel< ParcelType >::Re(), KinematicParcel< ParcelType >::Uc(), and KinematicParcel< ParcelType >::We().
muc_
scalar muc_ protected
Viscosity [Pa.s].
Definition at line 275 of file KinematicParcel.H.
Referenced by KinematicParcel< ParcelType >::calcVelocity(), and KinematicParcel< ParcelType >::muc().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.H
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.C
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcelI.H
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcelIO.C