OpenFOAM: MPPICParcel< ParcelType >::TrackingData< CloudType > Class Template Reference
MPPICParcel< ParcelType >::TrackingData< CloudType > Class Template Reference
Public Types
enum trackPart { tpLinearTrack, tpDampingNoTrack, tpPackingNoTrack, tpCorrectTrack }
Public Member Functions
TrackingData (CloudType &cloud, trackPart part=tpLinearTrack)
Constructors.
void updateAverages (CloudType &cloud)
Update the MPPIC averages.
trackPart part () const
Access.
trackPart & part ()
Non const access to the tracking part label.
Detailed Description
template<class ParcelType>
template<class CloudType>
class Foam::MPPICParcel< ParcelType >::TrackingData< CloudType >
Definition at line 84 of file MPPICParcel.H.
Member Enumeration Documentation
trackPart
enum trackPart
Enumerator
tpLinearTrack
tpDampingNoTrack
tpPackingNoTrack
tpCorrectTrack
Definition at line 91 of file MPPICParcel.H.
Constructor & Destructor Documentation
TrackingData()
TrackingData (CloudType & cloud, trackPart part = tpLinearTrack) inline
Constructors.
Construct from components
Definition at line 33 of file MPPICParcelTrackingDataI.H.
Member Function Documentation
updateAverages()
void updateAverages (CloudType & cloud) inline
Update the MPPIC averages.
Definition at line 145 of file MPPICParcelTrackingDataI.H.
References AveragingMethod< Type >::add(), AveragingMethod< Type >::average(), IOobject::db(), f(), forAllConstIter(), Foam::mag(), Foam::magSqr(), DSMCCloud< ParcelType >::mesh(), IOobject::name(), p, Foam::pow(), Foam::pow3(), Foam::sqr(), objectRegistry::time(), Time::timeName(), and Foam::Zero.
part() [1/2]
Foam::MPPICParcel< ParcelType >::template TrackingData< CloudType >::trackPart part () const inline
Access.
Const access to the tracking part label
Definition at line 253 of file MPPICParcelTrackingDataI.H.
part() [2/2]
Foam::MPPICParcel< ParcelType >::template TrackingData< CloudType >::trackPart & part () inline
Non const access to the tracking part label.
Definition at line 263 of file MPPICParcelTrackingDataI.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcel.H
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcelTrackingDataI.H