OpenFOAM: cloudAbsorptionEmission Class Reference
cloudAbsorptionEmission Class Reference
Retrieves absorption/emission data from a cloud object.
Public Member Functions
TypeName ("cloudAbsorptionEmission")
Runtime type information.
cloudAbsorptionEmission (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~cloudAbsorptionEmission ()
Destructor.
virtual tmp< volScalarField > aDisp (const label bandI=0) const
Absorption coefficient for dispersed phase.
virtual tmp< volScalarField > eDisp (const label bandI=0) const
Emission coefficient for dispersed phase.
virtual tmp< volScalarField > EDisp (const label bandI=0) const
Return emission contribution for dispersed phase.
Public Member Functions inherited from absorptionEmissionModel
TypeName ("absorptionEmissionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
Declare runtime constructor selection table.
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~absorptionEmissionModel ()
Destructor.
const fvMesh & mesh () const
Reference to the mesh.
const dictionary & dict () const
Reference to the dictionary.
virtual tmp< volScalarField > a (const label bandI=0) const
Absorption coefficient (net)
virtual tmp< volScalarField > aCont (const label bandI=0) const
Absorption coefficient for continuous phase.
virtual tmp< volScalarField > e (const label bandI=0) const
Emission coefficient (net)
virtual tmp< volScalarField > eCont (const label bandI=0) const
Return emission coefficient for continuous phase.
virtual tmp< volScalarField > E (const label bandI=0) const
Emission contribution (net)
virtual tmp< volScalarField > ECont (const label bandI=0) const
Emission contribution for continuous phase.
virtual label nBands () const
Const access to the number of bands - defaults to 1 for grey.
virtual const Vector2D< scalar > & bands (const label n) const
Const access to the bands - defaults to Vector2D::one for grey.
virtual bool isGrey () const
Flag for whether the absorption/emission is for a grey gas.
virtual void correct (volScalarField &a, PtrList< volScalarField > &aj) const
Correct absorption coefficients.
Additional Inherited Members
Static Public Member Functions inherited from absorptionEmissionModel
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Selector.
Protected Attributes inherited from absorptionEmissionModel
const dictionary dict_
Radiation model dictionary.
const fvMesh & mesh_
Reference to the fvMesh.
Detailed Description
Retrieves absorption/emission data from a cloud object.
Source files
cloudAbsorptionEmission.H
cloudAbsorptionEmission.C
Definition at line 50 of file cloudAbsorptionEmission.H.
Constructor & Destructor Documentation
cloudAbsorptionEmission()
cloudAbsorptionEmission (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 51 of file cloudAbsorptionEmission.C.
~cloudAbsorptionEmission()
~cloudAbsorptionEmission () virtual
Destructor.
Definition at line 64 of file cloudAbsorptionEmission.C.
Member Function Documentation
TypeName()
TypeName ("cloudAbsorptionEmission")
Runtime type information.
aDisp()
Foam::tmp< Foam::volScalarField > aDisp (const label bandI = 0) const virtual
Absorption coefficient for dispersed phase.
Reimplemented from absorptionEmissionModel.
Definition at line 71 of file cloudAbsorptionEmission.C.
References thermoCloud::ap(), Foam::dimLength, Foam::dimless, forAll, IOobject::NO_READ, IOobject::NO_WRITE, and tmp< T >::ref().
eDisp()
Foam::tmp< Foam::volScalarField > eDisp (const label bandI = 0) const virtual
Emission coefficient for dispersed phase.
Reimplemented from absorptionEmissionModel.
Definition at line 106 of file cloudAbsorptionEmission.C.
References Foam::dimLength, Foam::dimless, IOobject::NO_READ, and IOobject::NO_WRITE.
EDisp()
Foam::tmp< Foam::volScalarField > EDisp (const label bandI = 0) const virtual
Return emission contribution for dispersed phase.
Reimplemented from absorptionEmissionModel.
Definition at line 131 of file cloudAbsorptionEmission.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, thermoCloud::Ep(), forAll, IOobject::NO_READ, IOobject::NO_WRITE, Foam::pow3(), and tmp< T >::ref().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/addOns/radiation/absorptionEmission/cloudAbsorptionEmission/cloudAbsorptionEmission.H
src/lagrangian/intermediate/submodels/addOns/radiation/absorptionEmission/cloudAbsorptionEmission/cloudAbsorptionEmission.C