OpenFOAM: WallCollisionRecord< Type > Class Template Reference
WallCollisionRecord< Type > Class Template Reference
Record of a collision between the particle holding the record and a wall face at the position relative to the centre of the particle.
Public Member Functions
WallCollisionRecord ()
Construct null.
WallCollisionRecord (bool accessed, const vector &pRel, const Type &data=pTraits< Type >::zero)
Construct from components.
WallCollisionRecord (Istream &)
Construct from Istream.
WallCollisionRecord (const WallCollisionRecord &)
Construct as copy.
~WallCollisionRecord ()
Destructor.
const vector & pRel () const
Return the pRel data.
const Type & collisionData () const
Return access to the collision data.
Type & collisionData ()
Return access to the collision data.
bool match (const vector &pRel, scalar radius)
bool accessed () const
Return the accessed status of the record.
void setAccessed ()
Set the accessed property of the record to accessed.
void setUnaccessed ()
Set the accessed property of the record to unaccessed.
void operator= (const WallCollisionRecord &)
Static Public Attributes
static const scalar errorCosAngle
Tolerance for detecting seriously erroneous wall matches.
Friends
bool operator== (const WallCollisionRecord< Type > &, const WallCollisionRecord< Type > &)
bool operator!= (const WallCollisionRecord< Type > &, const WallCollisionRecord< Type > &)
Istream & operator>> (Istream &, WallCollisionRecord< Type > &)
Ostream & operator (Ostream &, const WallCollisionRecord< Type > &)
Detailed Description
template<class Type>
class Foam::WallCollisionRecord< Type >
Record of a collision between the particle holding the record and a wall face at the position relative to the centre of the particle.
Source files
WallCollisionRecord.H
WallCollisionRecordI.H
WallCollisionRecord.C
WallCollisionRecordIO.C
Definition at line 49 of file WallCollisionRecord.H.
Constructor & Destructor Documentation
WallCollisionRecord() [1/4]
WallCollisionRecord ()
Construct null.
Definition at line 37 of file WallCollisionRecord.C.
Referenced by WallCollisionRecord< Type >::WallCollisionRecord().
WallCollisionRecord() [2/4]
WallCollisionRecord (bool accessed, const vector & pRel, const Type & data = pTraits<Type>::zero)
Construct from components.
Definition at line 47 of file WallCollisionRecord.C.
References WallCollisionRecord< Type >::WallCollisionRecord().
WallCollisionRecord() [3/4]
WallCollisionRecord (Istream & is)
Construct from Istream.
Definition at line 32 of file WallCollisionRecordIO.C.
References IOstream::check(), Foam::operator>>(), and token::SPACE.
WallCollisionRecord() [4/4]
WallCollisionRecord (const WallCollisionRecord< Type > &)
Construct as copy.
~WallCollisionRecord()
~WallCollisionRecord ()
Destructor.
Definition at line 74 of file WallCollisionRecord.C.
Member Function Documentation
pRel()
const Foam::vector & pRel () const inline
Return the pRel data.
Definition at line 73 of file WallCollisionRecordI.H.
collisionData() [1/2]
const Type & collisionData () const inline
Return access to the collision data.
Definition at line 81 of file WallCollisionRecordI.H.
collisionData() [2/2]
Type & collisionData () inline
Return access to the collision data.
Definition at line 88 of file WallCollisionRecordI.H.
match()
bool match (const vector & pRel, scalar radius) inline
Definition at line 30 of file WallCollisionRecordI.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::mag(), and Foam::nl.
Referenced by CollisionRecordList< vector, vector >::checkWallRecord(), and CollisionRecordList< vector, vector >::matchWallRecord().
accessed()
bool accessed () const inline
Return the accessed status of the record.
Definition at line 95 of file WallCollisionRecordI.H.
setAccessed()
void setAccessed () inline
Set the accessed property of the record to accessed.
Definition at line 102 of file WallCollisionRecordI.H.
Referenced by CollisionRecordList< vector, vector >::matchWallRecord().
setUnaccessed()
void setUnaccessed () inline
Set the accessed property of the record to unaccessed.
Definition at line 109 of file WallCollisionRecordI.H.
operator=()
void operator= (const WallCollisionRecord< Type > &)
Definition at line 82 of file WallCollisionRecord.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Friends And Related Function Documentation
operator==
bool operator== (const WallCollisionRecord< Type > & , const WallCollisionRecord< Type > &) friend
operator!=
bool operator!= (const WallCollisionRecord< Type > & , const WallCollisionRecord< Type > &) friend
operator>>
Istream& operator>> (Istream & , WallCollisionRecord< Type > &) friend
operator
Ostream& operator (Ostream & , const WallCollisionRecord< Type > &) friend
Member Data Documentation
errorCosAngle
const Foam::scalar errorCosAngle static
Tolerance for detecting seriously erroneous wall matches.
Definition at line 97 of file WallCollisionRecord.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecord.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecord.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecordI.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecordIO.C