OpenFOAM: ReactingParcel< ParcelType >::iNew Class Reference
ReactingParcel< ParcelType >::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< ReactingParcel< ParcelType > > operator() (Istream &is) const
Detailed Description
template<class ParcelType>
class Foam::ReactingParcel< ParcelType >::iNew
Factory class to read-construct particles used for.
parallel transfer
Definition at line 292 of file ReactingParcel.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 298 of file ReactingParcel.H.
Member Function Documentation
operator()()
autoPtr<ReactingParcel<ParcelType> > operator() (Istream & is) const inline
Definition at line 303 of file ReactingParcel.H.
References Foam::constant::universal::c, ReactingParcel< ParcelType >::calc(), ReactingParcel< ParcelType >::cellValueSourceCorrection(), ReactingParcel< ParcelType >::correctSurfaceValues(), ReactingParcel< ParcelType >::mass0(), ReactingParcel< ParcelType >::pc(), ReactingParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::setCellValues(), Foam::T(), ReactingParcel< ParcelType >::writeFields(), and ReactingParcel< ParcelType >::Y().
The documentation for this class was generated from the following file:
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcel.H