OpenFOAM: KinematicParcel< ParcelType >::iNew Class Reference
KinematicParcel< ParcelType >::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< KinematicParcel< ParcelType > > operator() (Istream &is) const
Detailed Description
template<class ParcelType>
class Foam::KinematicParcel< ParcelType >::iNew
Factory class to read-construct particles used for.
parallel transfer
Definition at line 377 of file KinematicParcel.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 383 of file KinematicParcel.H.
Member Function Documentation
operator()()
autoPtr<KinematicParcel<ParcelType> > operator() (Istream & is) const inline
Definition at line 388 of file KinematicParcel.H.
References KinematicParcel< ParcelType >::active(), KinematicParcel< ParcelType >::age(), KinematicParcel< ParcelType >::areaP(), KinematicParcel< ParcelType >::areaS(), Foam::constant::universal::c, KinematicParcel< ParcelType >::calc(), KinematicParcel< ParcelType >::cellValueSourceCorrection(), KinematicParcel< ParcelType >::d(), KinematicParcel< ParcelType >::dTarget(), KinematicParcel< ParcelType >::Eo(), KinematicParcel< ParcelType >::faceInterpolation(), KinematicParcel< ParcelType >::hitFace(), KinematicParcel< ParcelType >::hitPatch(), KinematicParcel< ParcelType >::hitProcessorPatch(), KinematicParcel< ParcelType >::hitWallPatch(), KinematicParcel< ParcelType >::mass(), KinematicParcel< ParcelType >::massCell(), KinematicParcel< ParcelType >::momentOfInertia(), KinematicParcel< ParcelType >::move(), KinematicParcel< ParcelType >::muc(), n, KinematicParcel< ParcelType >::nParticle(), p, patchi, KinematicParcel< ParcelType >::Re(), KinematicParcel< ParcelType >::readFields(), KinematicParcel< ParcelType >::rho(), KinematicParcel< ParcelType >::rhoc(), KinematicParcel< ParcelType >::setCellValues(), Foam::constant::physicoChemical::sigma, Foam::T(), KinematicParcel< ParcelType >::transformProperties(), KinematicParcel< ParcelType >::tTurb(), KinematicParcel< ParcelType >::typeId(), KinematicParcel< ParcelType >::U(), KinematicParcel< ParcelType >::Uc(), KinematicParcel< ParcelType >::UTurb(), KinematicParcel< ParcelType >::volume(), KinematicParcel< ParcelType >::wallImpactDistance(), KinematicParcel< ParcelType >::We(), and KinematicParcel< ParcelType >::writeFields().
The documentation for this class was generated from the following file:
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.H