OpenFOAM: phaseProperties Class Reference
phaseProperties Class Reference
Helper class to manage multi-specie phase properties.
Public Types
enum phaseType { GAS, LIQUID, SOLID, UNKNOWN }
Phase type enumeration.
Public Member Functions
phaseProperties ()
Null constructor.
phaseProperties (Istream &)
Construct from Istream.
phaseProperties (const phaseProperties &)
Construct as copy.
~phaseProperties ()
Destructor.
void reorder (const wordList &gasNames, const wordList &liquidNames, const wordList &solidNames)
Reorder species to be consistent with the corresponding.
phaseType phase () const
Return const access to the phase type.
const word & stateLabel () const
Return const access to the phase state label.
word phaseTypeName () const
Return word representation of the phase type.
const List< word > & names () const
Return the list of specie names.
const word & name (const label speciei) const
Return const access to a specie name.
const scalarField & Y () const
Return const access to all specie mass fractions.
scalar & Y (const label speciei)
Return non-const access to a specie mass fraction.
const labelList & carrierIds () const
Return const access to the map to the carrier ids.
label id (const word &specieName) const
Return the id of a specie in the local list by name.
Static Public Attributes
static const NamedEnum< phaseType, 4 > phaseTypeNames
Corresponding word representations for phase type enumerations.
Friends
Istream & operator>> (Istream &, phaseProperties &)
Ostream & operator<< (Ostream &, const phaseProperties &)
Detailed Description
Helper class to manage multi-specie phase properties.
Source files
phaseProperties.H
phaseProperties.C
phasePropertiesIO.C
Definition at line 60 of file phaseProperties.H.
Member Enumeration Documentation
phaseType
enum phaseType
Phase type enumeration.
Enumerator
GAS
LIQUID
SOLID
UNKNOWN
Definition at line 67 of file phaseProperties.H.
Constructor & Destructor Documentation
phaseProperties() [1/3]
phaseProperties ()
Null constructor.
Definition at line 186 of file phaseProperties.C.
phaseProperties() [2/3]
phaseProperties (Istream & is)
Construct from Istream.
Definition at line 31 of file phasePropertiesIO.C.
References IOstream::check(), forAllConstIter(), entry::keyword(), dictionary::lookup(), dictionary::null, phaseProperties::phaseTypeNames, Foam::readScalar(), and List< T >::setSize().
phaseProperties() [3/3]
phaseProperties (const phaseProperties & pp)
Construct as copy.
Definition at line 196 of file phaseProperties.C.
~phaseProperties()
~phaseProperties ()
Destructor.
Definition at line 208 of file phaseProperties.C.
Member Function Documentation
reorder()
void reorder (const wordList & gasNames, const wordList & liquidNames, const wordList & solidNames)
Reorder species to be consistent with the corresponding.
phase specie name list
Definition at line 215 of file phaseProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, phaseProperties::GAS, phaseProperties::LIQUID, Foam::nl, phaseProperties::phaseTypeNames, and phaseProperties::SOLID.
phase()
Foam::phaseProperties::phaseType phase () const
Return const access to the phase type.
Definition at line 261 of file phaseProperties.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Cp(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::H(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hc(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hs(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::L(), and CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::X().
stateLabel()
const Foam::word & stateLabel () const
Return const access to the phase state label.
Definition at line 267 of file phaseProperties.C.
phaseTypeName()
Foam::word phaseTypeName () const
Return word representation of the phase type.
Definition at line 273 of file phaseProperties.C.
References phaseProperties::phaseTypeNames.
names()
const Foam::List< Foam::word > & names () const
Return the list of specie names.
Definition at line 279 of file phaseProperties.C.
name()
const Foam::word & name (const label speciei) const
Return const access to a specie name.
Definition at line 285 of file phaseProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and List< T >::size().
Y() [1/2]
const Foam::scalarField & Y () const
Return const access to all specie mass fractions.
Definition at line 299 of file phaseProperties.C.
Y() [2/2]
Foam::scalar & Y (const label speciei)
Return non-const access to a specie mass fraction.
Definition at line 305 of file phaseProperties.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and List< T >::size().
carrierIds()
const Foam::labelList & carrierIds () const
Return const access to the map to the carrier ids.
Definition at line 319 of file phaseProperties.C.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Cp(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::H(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hc(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hs(), and CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::X().
id()
Foam::label id (const word & specieName) const
Return the id of a specie in the local list by name.
Returns -1 if not found
Definition at line 325 of file phaseProperties.C.
References forAll.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , phaseProperties &) friend
operator<<
Ostream& operator<< (Ostream & , const phaseProperties &) friend
Member Data Documentation
phaseTypeNames
const Foam::NamedEnum< Foam::phaseProperties::phaseType, 4 > phaseTypeNames static
Corresponding word representations for phase type enumerations.
Definition at line 76 of file phaseProperties.H.
Referenced by NamedEnum< directionType, 3 >::names(), Foam::operator<<(), Foam::operator>>(), phaseProperties::phaseProperties(), phaseProperties::phaseTypeName(), and phaseProperties::reorder().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/phaseProperties/phaseProperties/phaseProperties.H
src/lagrangian/intermediate/phaseProperties/phaseProperties/phaseProperties.C
src/lagrangian/intermediate/phaseProperties/phaseProperties/phasePropertiesIO.C