OpenFOAM: NoCollision< CloudType > Class Template Reference
NoCollision< CloudType > Class Template Reference
Place holder for 'none' option.
Public Member Functions
TypeName ("none")
Runtime type information.
NoCollision (const dictionary &dict, CloudType &owner)
Construct from components.
NoCollision (const NoCollision< CloudType > &cm)
Construct copy.
virtual autoPtr< CollisionModel< CloudType > > clone () const
Construct and return a clone.
virtual ~NoCollision ()
Destructor.
virtual label nSubCycles () const
Return the number of times to subcycle the current.
virtual bool active () const
Flag to indicate whether model activates collision model.
virtual bool controlsWallInteraction () const
Indicates whether model determines wall collisions or not,.
virtual void collide ()
Public Member Functions inherited from CollisionModel< CloudType >
TypeName ("collisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
CollisionModel (CloudType &owner)
Construct null from owner.
CollisionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
CollisionModel (const CollisionModel< CloudType > &cm)
Construct copy.
virtual ~CollisionModel ()
Destructor.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from CollisionModel< CloudType >
static autoPtr< CollisionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::NoCollision< CloudType >
Place holder for 'none' option.
Source files
NoCollision.H
NoCollision.C
Definition at line 49 of file NoCollision.H.
Constructor & Destructor Documentation
NoCollision() [1/2]
NoCollision (const dictionary & dict, CloudType & owner)
Construct from components.
Definition at line 32 of file NoCollision.C.
NoCollision() [2/2]
NoCollision (const NoCollision< CloudType > & cm)
Construct copy.
Definition at line 43 of file NoCollision.C.
~NoCollision()
~NoCollision () virtual
Destructor.
Definition at line 54 of file NoCollision.C.
Referenced by NoCollision< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("none")
Runtime type information.
clone()
virtual autoPtr<CollisionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements CollisionModel< CloudType >.
Definition at line 69 of file NoCollision.H.
References NoCollision< CloudType >::active(), NoCollision< CloudType >::collide(), NoCollision< CloudType >::controlsWallInteraction(), NoCollision< CloudType >::nSubCycles(), and NoCollision< CloudType >::~NoCollision().
nSubCycles()
Foam::label nSubCycles () const virtual
Return the number of times to subcycle the current.
timestep to meet the criteria of the collision model. For this model this will always be 1.
Implements CollisionModel< CloudType >.
Definition at line 61 of file NoCollision.C.
Referenced by NoCollision< CloudType >::clone().
active()
bool active () const virtual
Flag to indicate whether model activates collision model.
Reimplemented from subModelBase.
Definition at line 68 of file NoCollision.C.
Referenced by NoCollision< CloudType >::clone().
controlsWallInteraction()
bool controlsWallInteraction () const virtual
Indicates whether model determines wall collisions or not,.
used to determine what value to use for wallImpactDistance
Implements CollisionModel< CloudType >.
Definition at line 75 of file NoCollision.C.
Referenced by NoCollision< CloudType >::clone().
collide()
void collide () virtual
Implements CollisionModel< CloudType >.
Definition at line 82 of file NoCollision.C.
Referenced by NoCollision< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/NoCollision/NoCollision.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/NoCollision/NoCollision.C