OpenFOAM: TimeFunction1< Type > Class Template Reference
TimeFunction1< Type > Class Template Reference
Light wrapper around Function1 to provide a mechanism to update time-based entries.
Public Member Functions
TimeFunction1 (const Time &t, const word &name, const dictionary &dict)
Construct from entry name.
TimeFunction1 (const Time &t, const word &entryName)
Construct null from entry name.
TimeFunction1 (const TimeFunction1< Type > &tde)
Copy constructor.
virtual ~TimeFunction1 ()
Destructor.
void reset (const dictionary &dict)
Reset entry by re-reading from dictionary.
const word & name () const
Return the name of the entry.
virtual Type value (const scalar x) const
Return value as a function of (scalar) independent variable.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Protected Attributes
const Time & time_
Reference to the time database.
const word name_
Name of the data entry.
autoPtr< Function1< Type > > entry_
The underlying Function1.
Friends
Ostream & operator (Ostream &os, const TimeFunction1< Type > &de)
Ostream Operator.
Detailed Description
template<class Type>
class Foam::TimeFunction1< Type >
Light wrapper around Function1 to provide a mechanism to update time-based entries.
Source files
TimeFunction1.H
TimeFunction1.C
Definition at line 73 of file ConeNozzleInjection.H.
Constructor & Destructor Documentation
TimeFunction1() [1/3]
TimeFunction1 (const Time & t, const word & name, const dictionary & dict)
Construct from entry name.
Definition at line 32 of file TimeFunction1.C.
Referenced by TimeFunction1< scalar >::TimeFunction1().
TimeFunction1() [2/3]
TimeFunction1 (const Time & t, const word & entryName)
Construct null from entry name.
Definition at line 47 of file TimeFunction1.C.
TimeFunction1() [3/3]
TimeFunction1 (const TimeFunction1< Type > & tde)
Copy constructor.
Definition at line 57 of file TimeFunction1.C.
~TimeFunction1()
~TimeFunction1 () virtual
Destructor.
Definition at line 75 of file TimeFunction1.C.
Member Function Documentation
reset()
void reset (const dictionary & dict)
Reset entry by re-reading from dictionary.
Definition at line 82 of file TimeFunction1.C.
Referenced by InjectionModel< CloudType >::InjectionModel().
name()
const Foam::word & name () const
Return the name of the entry.
Definition at line 98 of file TimeFunction1.C.
value()
Type value (const scalar x) const virtual
Return value as a function of (scalar) independent variable.
Definition at line 105 of file TimeFunction1.C.
Referenced by InjectionModel< CloudType >::InjectionModel(), and InjectionModel< CloudType >::injectSteadyState().
integrate()
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Definition at line 113 of file TimeFunction1.C.
Referenced by TimeFunction1< scalar >::value().
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Definition at line 136 of file TimeFunction1.C.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & os, const TimeFunction1< Type > & de) friend
Ostream Operator.
Member Data Documentation
time_
const Time& time_ protected
Reference to the time database.
Definition at line 68 of file TimeFunction1.H.
name_
const word name_ protected
Name of the data entry.
Definition at line 71 of file TimeFunction1.H.
entry_
autoPtr<Function1<Type> > entry_ protected
The underlying Function1.
Definition at line 74 of file TimeFunction1.H.
Referenced by TimeFunction1< scalar >::TimeFunction1().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/ConeNozzleInjection/ConeNozzleInjection.H
src/OpenFOAM/primitives/functions/TimeFunction1/TimeFunction1.H
src/OpenFOAM/primitives/functions/TimeFunction1/TimeFunction1.C