OpenFOAM: VoidFraction< CloudType > Class Template Reference
VoidFraction< CloudType > Class Template Reference
Creates particle void fraction field on carrier phase.
Public Member Functions
TypeName ("voidFraction")
Runtime type information.
VoidFraction (const dictionary &dict, CloudType &owner, const word &modelName)
Construct from dictionary.
VoidFraction (const VoidFraction< CloudType > &vf)
Construct copy.
virtual autoPtr< CloudFunctionObject< CloudType > > clone () const
Construct and return a clone.
virtual ~VoidFraction ()
Destructor.
virtual void preEvolve ()
Pre-evolve hook.
virtual void postEvolve ()
Post-evolve hook.
virtual void postMove (parcelType &p, const label celli, const scalar dt, const point &position0, bool &keepParticle)
Post-move hook.
Public Member Functions inherited from CloudFunctionObject< CloudType >
TypeName ("cloudFunctionObject")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CloudFunctionObject, dictionary,(const dictionary &dict, CloudType &owner, const word &modelName),(dict, owner, modelName))
Declare runtime constructor selection table.
CloudFunctionObject (CloudType &owner)
Construct null from owner.
CloudFunctionObject (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Construct from dictionary.
CloudFunctionObject (const CloudFunctionObject< CloudType > &ppm)
Construct copy.
virtual ~CloudFunctionObject ()
Destructor.
virtual void postPatch (const typename CloudType::parcelType &p, const polyPatch &pp, const scalar trackFraction, const tetIndices &testIs, bool &keepParticle)
Post-patch hook.
virtual void postFace (const typename CloudType::parcelType &p, const label facei, bool &keepParticle)
Post-face hook.
const fileName & outputDir () const
Return the output path.
fileName writeTimeDir () const
Return the output time path.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Member Functions
virtual void write ()
Write post-processing info.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from CloudFunctionObject< CloudType >
static autoPtr< CloudFunctionObject< CloudType > > New (const dictionary &dict, CloudType &owner, const word &objectType, const word &modelName)
Selector.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::VoidFraction< CloudType >
Creates particle void fraction field on carrier phase.
Source files
VoidFraction.H
VoidFraction.C
Definition at line 50 of file VoidFraction.H.
Constructor & Destructor Documentation
VoidFraction() [1/2]
VoidFraction (const dictionary & dict, CloudType & owner, const word & modelName)
Construct from dictionary.
Definition at line 49 of file VoidFraction.C.
Referenced by VoidFraction< CloudType >::write().
VoidFraction() [2/2]
VoidFraction (const VoidFraction< CloudType > & vf)
Construct copy.
Definition at line 62 of file VoidFraction.C.
~VoidFraction()
~VoidFraction () virtual
Destructor.
Definition at line 74 of file VoidFraction.C.
Referenced by VoidFraction< CloudType >::clone().
Member Function Documentation
write()
void write () protected virtual
Write post-processing info.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 31 of file VoidFraction.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and VoidFraction< CloudType >::VoidFraction().
TypeName()
TypeName ("voidFraction")
Runtime type information.
clone()
virtual autoPtr<CloudFunctionObject<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 94 of file VoidFraction.H.
References p, VoidFraction< CloudType >::postEvolve(), VoidFraction< CloudType >::postMove(), VoidFraction< CloudType >::preEvolve(), and VoidFraction< CloudType >::~VoidFraction().
preEvolve()
void preEvolve () virtual
Pre-evolve hook.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 81 of file VoidFraction.C.
References Foam::dimless, mesh, Foam::name(), fvMesh::time(), and Time::timeName().
Referenced by VoidFraction< CloudType >::clone().
postEvolve()
void postEvolve () virtual
Post-evolve hook.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 112 of file VoidFraction.C.
References TimeState::deltaTValue(), mesh, VoidFraction< CloudType >::postMove(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), fvMesh::time(), and fvMesh::V().
Referenced by VoidFraction< CloudType >::clone().
postMove()
void postMove (parcelType & p, const label celli, const scalar dt, const point & position0, bool & keepParticle) virtual
Post-move hook.
Reimplemented from CloudFunctionObject< CloudType >.
Definition at line 126 of file VoidFraction.C.
Referenced by VoidFraction< CloudType >::clone(), and VoidFraction< CloudType >::postEvolve().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/CloudFunctionObjects/VoidFraction/VoidFraction.H
src/lagrangian/intermediate/submodels/CloudFunctionObjects/VoidFraction/VoidFraction.C