OpenFOAM: ParticleForceList< CloudType > Class Template Reference
ParticleForceList< CloudType > Class Template Reference
List of particle forces.
Public Member Functions
ParticleForceList (CloudType &owner, const fvMesh &mesh)
Null constructor.
ParticleForceList (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const bool readFields)
Construct from mesh.
ParticleForceList (const ParticleForceList &pfl)
Construct copy.
virtual ~ParticleForceList ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & dict () const
Return the forces dictionary.
void setCalcCoupled (bool flag)
Set the calcCoupled flag.
void setCalcNonCoupled (bool flag)
Set the calcNonCoupled flag.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massEff (const typename CloudType::parcelType &p, const scalar mass) const
Return the effective mass.
Public Member Functions inherited from PtrList< ParticleForce< CloudType > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< ParticleForce< CloudType > > &)
Copy constructor.
PtrList (const PtrList< ParticleForce< CloudType > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< ParticleForce< CloudType > >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< ParticleForce< CloudType > > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< ParticleForce< CloudType > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (ParticleForce< CloudType > *)
Append an element at the end of the list.
void append (const autoPtr< ParticleForce< CloudType > > &)
void append (const tmp< ParticleForce< CloudType > > &)
void transfer (PtrList< ParticleForce< CloudType > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< ParticleForce< CloudType > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< ParticleForce< CloudType > > set (const label, ParticleForce< CloudType > *)
Set element to given T* and return old element (can be nullptr)
autoPtr< ParticleForce< CloudType > > set (const label, const autoPtr< ParticleForce< CloudType > > &)
Set element to given autoPtr<T> and return old element.
autoPtr< ParticleForce< CloudType > > set (const label, const tmp< ParticleForce< CloudType > > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< ParticleForce< CloudType > > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< ParticleForce< CloudType > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
template<class CloudType>
class Foam::ParticleForceList< CloudType >
List of particle forces.
Source files
ParticleForceList.H
ParticleForceListI.H
ParticleForceList.C
Definition at line 51 of file ParticleForceList.H.
Constructor & Destructor Documentation
ParticleForceList() [1/3]
ParticleForceList (CloudType & owner, const fvMesh & mesh)
Null constructor.
Definition at line 33 of file ParticleForceList.C.
Referenced by ParticleForceList< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::ParticleForceList().
ParticleForceList() [2/3]
ParticleForceList (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const bool readFields)
Construct from mesh.
Definition at line 49 of file ParticleForceList.C.
ParticleForceList() [3/3]
ParticleForceList (const ParticleForceList< CloudType > & pfl)
Construct copy.
Definition at line 117 of file ParticleForceList.C.
~ParticleForceList()
~ParticleForceList () virtual
Destructor.
Definition at line 131 of file ParticleForceList.C.
Member Function Documentation
owner() [1/2]
const CloudType & owner () const inline
Return const access to the cloud owner.
Definition at line 29 of file ParticleForceListI.H.
owner() [2/2]
CloudType & owner () inline
Return refernce to the cloud owner.
Definition at line 36 of file ParticleForceListI.H.
mesh()
const Foam::fvMesh & mesh () const inline
Return the mesh database.
Definition at line 43 of file ParticleForceListI.H.
dict()
const Foam::dictionary & dict () const inline
Return the forces dictionary.
Definition at line 50 of file ParticleForceListI.H.
setCalcCoupled()
void setCalcCoupled (bool flag) inline
Set the calcCoupled flag.
Definition at line 57 of file ParticleForceListI.H.
setCalcNonCoupled()
void setCalcNonCoupled (bool flag) inline
Set the calcNonCoupled flag.
Definition at line 64 of file ParticleForceListI.H.
cacheFields()
void cacheFields (const bool store) virtual
Cache fields.
Definition at line 138 of file ParticleForceList.C.
calcCoupled()
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the coupled force.
Definition at line 149 of file ParticleForceList.C.
Referenced by ParticleForceList< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::cacheFields().
calcNonCoupled()
Foam::forceSuSp calcNonCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the non-coupled force.
Definition at line 173 of file ParticleForceList.C.
Referenced by ParticleForceList< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::calcCoupled().
massEff()
Foam::scalar massEff (const typename CloudType::parcelType & p, const scalar mass) const virtual
Return the effective mass.
Definition at line 197 of file ParticleForceList.C.
Referenced by ParticleForceList< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::calcNonCoupled().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/ForceTypes/ParticleForceList/ParticleForceList.H
src/lagrangian/intermediate/submodels/ForceTypes/ParticleForceList/ParticleForceList.C
src/lagrangian/intermediate/submodels/ForceTypes/ParticleForceList/ParticleForceListI.H