OpenFOAM: WallLocalSpringSliderDashpot< CloudType > Class Template Reference
WallLocalSpringSliderDashpot< CloudType > Class Template Reference
Forces between particles and walls, interacting with a spring, slider, damper model.
Public Member Functions
TypeName ("wallLocalSpringSliderDashpot")
Runtime type information.
WallLocalSpringSliderDashpot (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
virtual ~WallLocalSpringSliderDashpot ()
Destructor.
scalar volumeFactor () const
Return the volumeFactor.
virtual scalar pREff (const typename CloudType::parcelType &p) const
Return the effective radius for a particle for the model.
virtual bool controlsTimestep () const
Whether the WallModel has a timestep limit that will.
virtual label nSubCycles () const
For WallModels that control the timestep, calculate the.
virtual void evaluateWall (typename CloudType::parcelType &p, const List< point > &flatSitePoints, const List< WallSiteData< vector >> &flatSiteData, const List< point > &sharpSitePoints, const List< WallSiteData< vector >> &sharpSiteData) const
Calculate the wall interaction for a parcel.
Public Member Functions inherited from WallModel< CloudType >
TypeName ("wallModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, WallModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
WallModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~WallModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
CloudType & owner ()
Return non-const access to the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from WallModel< CloudType >
static autoPtr< WallModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::WallLocalSpringSliderDashpot< CloudType >
Forces between particles and walls, interacting with a spring, slider, damper model.
Definition at line 46 of file WallLocalSpringSliderDashpot.H.
Constructor & Destructor Documentation
WallLocalSpringSliderDashpot()
WallLocalSpringSliderDashpot (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 175 of file WallLocalSpringSliderDashpot.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), polyMesh::boundaryMesh(), forAll, lookup(), dictionary::lookup(), Foam::mag(), mesh, Foam::name(), nu, patchi, readScalar, PtrList< T >::setSize(), List< T >::size(), UPtrList< T >::size(), and Foam::sqr().
~WallLocalSpringSliderDashpot()
~WallLocalSpringSliderDashpot () virtual
Destructor.
Definition at line 280 of file WallLocalSpringSliderDashpot.C.
References WallLocalSpringSliderDashpot< CloudType >::pREff().
Member Function Documentation
TypeName()
TypeName ("wallLocalSpringSliderDashpot")
Runtime type information.
volumeFactor()
scalar volumeFactor () const inline
Return the volumeFactor.
Definition at line 147 of file WallLocalSpringSliderDashpot.H.
References WallLocalSpringSliderDashpot< CloudType >::controlsTimestep(), WallLocalSpringSliderDashpot< CloudType >::nSubCycles(), and WallLocalSpringSliderDashpot< CloudType >::pREff().
pREff()
Foam::scalar pREff (const typename CloudType::parcelType & p) const virtual
Return the effective radius for a particle for the model.
Implements WallModel< CloudType >.
Definition at line 288 of file WallLocalSpringSliderDashpot.C.
References Foam::cbrt().
Referenced by WallLocalSpringSliderDashpot< CloudType >::volumeFactor(), and WallLocalSpringSliderDashpot< CloudType >::~WallLocalSpringSliderDashpot().
controlsTimestep()
bool controlsTimestep () const virtual
Whether the WallModel has a timestep limit that will.
require subCycling
Implements WallModel< CloudType >.
Definition at line 304 of file WallLocalSpringSliderDashpot.C.
Referenced by WallLocalSpringSliderDashpot< CloudType >::volumeFactor().
nSubCycles()
Foam::label nSubCycles () const virtual
For WallModels that control the timestep, calculate the.
number of subCycles needed to satisfy the minimum allowable timestep
Implements WallModel< CloudType >.
Definition at line 311 of file WallLocalSpringSliderDashpot.C.
References Foam::pow(), rhoMax(), and Foam::sqrt().
Referenced by WallLocalSpringSliderDashpot< CloudType >::volumeFactor().
evaluateWall()
void evaluateWall (typename CloudType::parcelType & p, const List< point > & flatSitePoints, const List< WallSiteData< vector >> & flatSiteData, const List< point > & sharpSitePoints, const List< WallSiteData< vector >> & sharpSiteData) const virtual
Calculate the wall interaction for a parcel.
Implements WallModel< CloudType >.
Definition at line 337 of file WallLocalSpringSliderDashpot.C.
References forAll.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallLocalSpringSliderDashpot/WallLocalSpringSliderDashpot.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/WallModel/WallLocalSpringSliderDashpot/WallLocalSpringSliderDashpot.C