OpenFOAM: PairSpringSliderDashpot< CloudType > Class Template Reference
PairSpringSliderDashpot< CloudType > Class Template Reference
Pair forces between particles colliding with a spring, slider, damper model.
Public Member Functions
TypeName ("pairSpringSliderDashpot")
Runtime type information.
PairSpringSliderDashpot (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
virtual ~PairSpringSliderDashpot ()
Destructor.
scalar volumeFactor () const
Return the volumeFactor.
scalar overlapArea (scalar rA, scalar rB, scalar rAB) const
virtual bool controlsTimestep () const
Whether the PairModel has a timestep limit that will.
virtual label nSubCycles () const
For PairModels that control the timestep, calculate the.
virtual void evaluatePair (typename CloudType::parcelType &pA, typename CloudType::parcelType &pB) const
Calculate the pair interaction between parcels.
Public Member Functions inherited from PairModel< CloudType >
TypeName ("pairModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, PairModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
PairModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~PairModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from PairModel< CloudType >
static autoPtr< PairModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::PairSpringSliderDashpot< CloudType >
Pair forces between particles colliding with a spring, slider, damper model.
Definition at line 47 of file PairSpringSliderDashpot.H.
Constructor & Destructor Documentation
PairSpringSliderDashpot()
PairSpringSliderDashpot (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 84 of file PairSpringSliderDashpot.C.
References Foam::constant::universal::G, lookup(), Foam::mag(), nu, readScalar, and Foam::sqr().
~PairSpringSliderDashpot()
~PairSpringSliderDashpot () virtual
Destructor.
Definition at line 129 of file PairSpringSliderDashpot.C.
Member Function Documentation
TypeName()
TypeName ("pairSpringSliderDashpot")
Runtime type information.
volumeFactor()
scalar volumeFactor () const inline
Return the volumeFactor.
Definition at line 133 of file PairSpringSliderDashpot.H.
overlapArea()
scalar overlapArea (scalar rA, scalar rB, scalar rAB) const inline
Definition at line 140 of file PairSpringSliderDashpot.H.
References PairSpringSliderDashpot< CloudType >::controlsTimestep(), PairSpringSliderDashpot< CloudType >::evaluatePair(), PairSpringSliderDashpot< CloudType >::nSubCycles(), Foam::constant::mathematical::pi(), and Foam::sqr().
controlsTimestep()
bool controlsTimestep () const virtual
Whether the PairModel has a timestep limit that will.
require subCycling
Implements PairModel< CloudType >.
Definition at line 136 of file PairSpringSliderDashpot.C.
Referenced by PairSpringSliderDashpot< CloudType >::overlapArea().
nSubCycles()
Foam::label nSubCycles () const virtual
For PairModels that control the timestep, calculate the.
number of subCycles needed to satisfy the minimum allowable timestep
Implements PairModel< CloudType >.
Definition at line 143 of file PairSpringSliderDashpot.C.
References PairSpringSliderDashpot< CloudType >::evaluatePair(), Foam::pow(), rhoMax(), and Foam::sqrt().
Referenced by PairSpringSliderDashpot< CloudType >::overlapArea().
evaluatePair()
void evaluatePair (typename CloudType::parcelType & pA, typename CloudType::parcelType & pB) const virtual
Calculate the pair interaction between parcels.
Implements PairModel< CloudType >.
Definition at line 169 of file PairSpringSliderDashpot.C.
References Foam::cbrt(), M, Foam::mag(), Foam::pow(), Foam::pow025(), R, Foam::sqrt(), and Foam::Zero.
Referenced by PairSpringSliderDashpot< CloudType >::nSubCycles(), and PairSpringSliderDashpot< CloudType >::overlapArea().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairModel/PairSpringSliderDashpot/PairSpringSliderDashpot.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairModel/PairSpringSliderDashpot/PairSpringSliderDashpot.C