OpenFOAM: forceSuSp Class Reference
forceSuSp Class Reference
Helper container for force Su and Sp terms.
Public Member Functions
forceSuSp ()
Construct null.
forceSuSp (const Tuple2< vector, scalar > &susp)
Construct given Tuple2.
forceSuSp (const vector &Su, const scalar Sp)
Construct given two components.
forceSuSp (Istream &)
Construct from Istream.
const vector & Su () const
Return const access to the explicit contribution [kg.m/s2].
scalar Sp () const
Return const access to the implicit coefficient [kg/s].
vector & Su ()
Return reference to the explicit contribution.
scalar & Sp ()
Return reference to the implicit coefficient.
void operator= (const forceSuSp &susp)
Assignment.
void operator+= (const forceSuSp &susp)
Addition.
void operator-= (const forceSuSp &susp)
Subtraction.
Public Member Functions inherited from Tuple2< vector, scalar >
Tuple2 ()
Null constructor for lists.
Tuple2 (const vector &f, const scalar &s)
Construct from components.
Tuple2 (Istream &is)
Construct from Istream.
const vector & first () const
Return first.
vector & first ()
Return first.
const scalar & second () const
Return second.
scalar & second ()
Return second.
Friends
forceSuSp operator* (const forceSuSp &susp1, const forceSuSp &susp2)
Addition.
forceSuSp operator* (const scalar s, const forceSuSp &susp)
Multiplication.
Detailed Description
Helper container for force Su and Sp terms.
F = Sp(U - Up) + Su
Explicit contribution, Su specified as a force Implicit coefficient, Sp specified as force/velocity
Source files
forceSuSp.H
forceSuSpI.H
Definition at line 61 of file forceSuSp.H.
Constructor & Destructor Documentation
forceSuSp() [1/4]
forceSuSp () inline
Construct null.
Definition at line 28 of file forceSuSpI.H.
Referenced by Foam::operator*(), and Foam::operator+().
forceSuSp() [2/4]
forceSuSp (const Tuple2< vector, scalar > & susp) inline
Construct given Tuple2.
Definition at line 33 of file forceSuSpI.H.
forceSuSp() [3/4]
forceSuSp (const vector & Su, const scalar Sp) inline
Construct given two components.
Definition at line 41 of file forceSuSpI.H.
References Tuple2< vector, scalar >::first(), Tuple2< vector, scalar >::second(), forceSuSp::Sp(), and forceSuSp::Su().
forceSuSp() [4/4]
forceSuSp (Istream & is) inline
Construct from Istream.
Definition at line 48 of file forceSuSpI.H.
Member Function Documentation
Su() [1/2]
const Foam::vector & Su () const inline
Return const access to the explicit contribution [kg.m/s2].
Definition at line 56 of file forceSuSpI.H.
References Tuple2< vector, scalar >::first().
Referenced by VirtualMassForce< CloudType >::calcCoupled(), PressureGradientForce< CloudType >::calcCoupled(), LiftForce< CloudType >::calcCoupled(), BrownianMotionForce< CloudType >::calcCoupled(), ParticleForce< CloudType >::calcCoupled(), SRFForce< CloudType >::calcNonCoupled(), GravityForce< CloudType >::calcNonCoupled(), ParamagneticForce< CloudType >::calcNonCoupled(), NonInertialFrameForce< CloudType >::calcNonCoupled(), ParticleForce< CloudType >::calcNonCoupled(), KinematicParcel< ParcelType >::calcVelocity(), and forceSuSp::forceSuSp().
Sp() [1/2]
Foam::scalar Sp () const inline
Return const access to the implicit coefficient [kg/s].
Definition at line 62 of file forceSuSpI.H.
References Tuple2< vector, scalar >::second().
Referenced by SprayParcel< ParcelType >::calcBreakup(), SphereDragForce< CloudType >::calcCoupled(), DistortedSphereDragForce< CloudType >::calcCoupled(), NonSphereDragForce< CloudType >::calcCoupled(), ParticleForce< CloudType >::calcCoupled(), ParticleForce< CloudType >::calcNonCoupled(), KinematicParcel< ParcelType >::calcVelocity(), and forceSuSp::forceSuSp().
Su() [2/2]
Foam::vector & Su () inline
Return reference to the explicit contribution.
Definition at line 68 of file forceSuSpI.H.
References Tuple2< vector, scalar >::first().
Sp() [2/2]
Foam::scalar & Sp () inline
Return reference to the implicit coefficient.
Definition at line 74 of file forceSuSpI.H.
References Tuple2< vector, scalar >::second().
operator=()
void operator= (const forceSuSp & susp) inline
Assignment.
Definition at line 82 of file forceSuSpI.H.
References Tuple2< vector, scalar >::first(), Tuple2< Type1, Type2 >::first(), Tuple2< vector, scalar >::second(), and Tuple2< Type1, Type2 >::second().
operator+=()
void operator+= (const forceSuSp & susp) inline
Addition.
Definition at line 89 of file forceSuSpI.H.
References Tuple2< vector, scalar >::first(), Tuple2< Type1, Type2 >::first(), Tuple2< vector, scalar >::second(), and Tuple2< Type1, Type2 >::second().
operator-=()
void operator-= (const forceSuSp & susp) inline
Subtraction.
Definition at line 96 of file forceSuSpI.H.
References Tuple2< vector, scalar >::first(), Tuple2< Type1, Type2 >::first(), Tuple2< vector, scalar >::second(), and Tuple2< Type1, Type2 >::second().
Friends And Related Function Documentation
operator* [1/2]
forceSuSp operator* (const forceSuSp & susp1, const forceSuSp & susp2) friend
Addition.
operator* [2/2]
forceSuSp operator* (const scalar s, const forceSuSp & susp) friend
Multiplication.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/forceSuSp/forceSuSp.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/forceSuSp/forceSuSpI.H