OpenFOAM: DistortedSphereDragForce< CloudType > Class Template Reference
DistortedSphereDragForce< CloudType > Class Template Reference
Drag model based on assumption of distorted spheres according to:
Public Member Functions
TypeName ("distortedSphereDrag")
Runtime type information.
DistortedSphereDragForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
Construct from mesh.
DistortedSphereDragForce (const DistortedSphereDragForce< CloudType > &df)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~DistortedSphereDragForce ()
Destructor.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::DistortedSphereDragForce< CloudType >
Drag model based on assumption of distorted spheres according to:
    "Effects of Drop Drag and Breakup on Fuel Sprays"
    Liu, A.B., Mather, D., Reitz, R.D.,
    SAE Paper 930072,
    SAE Transactions, Vol. 102, Section 3, Journal of Engines, 1993,
    pp. 63-95
Definition at line 53 of file DistortedSphereDragForce.H.
Constructor & Destructor Documentation
DistortedSphereDragForce() [1/2]
DistortedSphereDragForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Construct from mesh.
Definition at line 51 of file DistortedSphereDragForce.C.
DistortedSphereDragForce() [2/2]
DistortedSphereDragForce (const DistortedSphereDragForce< CloudType > & df)
Construct copy.
Definition at line 63 of file DistortedSphereDragForce.C.
~DistortedSphereDragForce()
~DistortedSphereDragForce () virtual
Destructor.
Definition at line 74 of file DistortedSphereDragForce.C.
References DistortedSphereDragForce< CloudType >::calcCoupled().
Referenced by DistortedSphereDragForce< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("distortedSphereDrag")
Runtime type information.
clone()
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from ParticleForce< CloudType >.
Definition at line 83 of file DistortedSphereDragForce.H.
References DistortedSphereDragForce< CloudType >::calcCoupled(), p, and DistortedSphereDragForce< CloudType >::~DistortedSphereDragForce().
calcCoupled()
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the coupled force.
Reimplemented from ParticleForce< CloudType >.
Definition at line 82 of file DistortedSphereDragForce.C.
References Foam::max(), Foam::min(), forceSuSp::Sp(), Foam::sqr(), y, and Foam::Zero.
Referenced by DistortedSphereDragForce< CloudType >::clone(), and DistortedSphereDragForce< CloudType >::~DistortedSphereDragForce().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/DistortedSphereDrag/DistortedSphereDragForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Drag/DistortedSphereDrag/DistortedSphereDragForce.C