OpenFOAM: ParamagneticForce< CloudType > Class Template Reference
ParamagneticForce< CloudType > Class Template Reference
Calculates particle paramagnetic (magnetic field) force.
Public Member Functions
TypeName ("paramagnetic")
Runtime type information.
ParamagneticForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
Construct from mesh.
ParamagneticForce (const ParamagneticForce &gf)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~ParamagneticForce ()
Destructor.
const word & HdotGradHName () const
Return the name of paramagnetic field strength field.
scalar magneticSusceptibility () const
Return the magnetic susceptibility of particle.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::ParamagneticForce< CloudType >
Calculates particle paramagnetic (magnetic field) force.
Source files
ParamagneticForce.H
ParamagneticForceI.H
ParamagneticForce.C
Definition at line 53 of file ParamagneticForce.H.
Constructor & Destructor Documentation
ParamagneticForce() [1/2]
ParamagneticForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Construct from mesh.
Definition at line 34 of file ParamagneticForce.C.
ParamagneticForce() [2/2]
ParamagneticForce (const ParamagneticForce< CloudType > & gf)
Construct copy.
Definition at line 55 of file ParamagneticForce.C.
~ParamagneticForce()
~ParamagneticForce () virtual
Destructor.
Definition at line 69 of file ParamagneticForce.C.
Referenced by ParamagneticForce< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("paramagnetic")
Runtime type information.
clone()
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from ParticleForce< CloudType >.
Definition at line 89 of file ParamagneticForce.H.
References ParamagneticForce< CloudType >::cacheFields(), ParamagneticForce< CloudType >::calcNonCoupled(), ParamagneticForce< CloudType >::HdotGradHName(), ParamagneticForce< CloudType >::magneticSusceptibility(), p, Foam::Re(), and ParamagneticForce< CloudType >::~ParamagneticForce().
HdotGradHName()
const Foam::word & HdotGradHName () const inline
Return the name of paramagnetic field strength field.
Definition at line 30 of file ParamagneticForceI.H.
Referenced by ParamagneticForce< CloudType >::clone().
magneticSusceptibility()
Foam::scalar magneticSusceptibility () const inline
Return the magnetic susceptibility of particle.
Definition at line 38 of file ParamagneticForceI.H.
Referenced by ParamagneticForce< CloudType >::clone().
cacheFields()
void cacheFields (const bool store) virtual
Cache fields.
Reimplemented from ParticleForce< CloudType >.
Definition at line 76 of file ParamagneticForce.C.
References ParamagneticForce< CloudType >::calcNonCoupled(), Foam::deleteDemandDrivenData(), mesh, and Foam::New().
Referenced by ParamagneticForce< CloudType >::clone().
calcNonCoupled()
Foam::forceSuSp calcNonCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the non-coupled force.
Reimplemented from ParticleForce< CloudType >.
Definition at line 98 of file ParamagneticForce.C.
References interpolation< Type >::interpolate(), Foam::constant::electromagnetic::mu0, forceSuSp::Su(), dimensioned< Type >::value(), and Foam::Zero.
Referenced by ParamagneticForce< CloudType >::cacheFields(), and ParamagneticForce< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Paramagnetic/ParamagneticForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Paramagnetic/ParamagneticForce.C
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/Paramagnetic/ParamagneticForceI.H