OpenFOAM: patchInjectionBase Class Reference
patchInjectionBase Class Reference
Public Member Functions
patchInjectionBase (const polyMesh &mesh, const word &patchName)
Construct from mesh and patch name.
patchInjectionBase (const patchInjectionBase &pib)
Copy constructor.
virtual ~patchInjectionBase ()
Destructor.
virtual void updateMesh (const polyMesh &mesh)
Update patch geometry and derived info for injection locations.
virtual void setPositionAndCell (const polyMesh &mesh, cachedRandom &rnd, vector &position, label &cellOwner, label &tetFacei, label &tetPti)
Set the injection position and owner cell, tetFace and tetPt.
Protected Attributes
const word patchName_
Patch name.
const label patchId_
Patch ID.
scalar patchArea_
Patch area - total across all processors.
vectorList patchNormal_
Patch face normal directions.
labelList cellOwners_
List of cell labels corresponding to injector positions.
faceList triFace_
Decomposed patch faces as a list of triangles.
labelList triToFace_
Addressing from per triangle to patch face.
scalarList triCumulativeMagSf_
Cumulative triangle area per triangle face.
scalarList sumTriMagSf_
Cumulative area fractions per processor.
Detailed Description
Definition at line 61 of file patchInjectionBase.H.
Constructor & Destructor Documentation
patchInjectionBase() [1/2]
patchInjectionBase (const polyMesh & mesh, const word & patchName)
Construct from mesh and patch name.
Definition at line 35 of file patchInjectionBase.C.
References polyMesh::boundaryMesh(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::names(), and Foam::nl.
patchInjectionBase() [2/2]
patchInjectionBase (const patchInjectionBase & pib)
Copy constructor.
Definition at line 62 of file patchInjectionBase.C.
~patchInjectionBase()
~patchInjectionBase () virtual
Destructor.
Definition at line 78 of file patchInjectionBase.C.
Member Function Documentation
updateMesh()
void updateMesh (const polyMesh & mesh) virtual
Update patch geometry and derived info for injection locations.
Definition at line 84 of file patchInjectionBase.C.
References polyMesh::boundaryMesh(), patchInjectionBase::cellOwners_, DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), f(), polyPatch::faceAreas(), polyPatch::faceCells(), forAll, Pstream::listCombineGather(), Pstream::listCombineScatter(), Foam::mag(), UPstream::myProcNo(), patchInjectionBase::patchArea_, patchInjectionBase::patchId_, patchInjectionBase::patchNormal_, points, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::reduce(), patchInjectionBase::setPositionAndCell(), List< T >::size(), Foam::sum(), patchInjectionBase::sumTriMagSf_, List< T >::transfer(), face::triangles(), patchInjectionBase::triCumulativeMagSf_, triFace(), patchInjectionBase::triFace_, and patchInjectionBase::triToFace_.
Referenced by PatchInjection< CloudType >::clone(), and PatchFlowRateInjection< CloudType >::clone().
setPositionAndCell()
void setPositionAndCell (const polyMesh & mesh, cachedRandom & rnd, vector & position, label & cellOwner, label & tetFacei, label & tetPti) virtual
Set the injection position and owner cell, tetFace and tetPt.
Definition at line 150 of file patchInjectionBase.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), patchInjectionBase::cellOwners_, primitiveMesh::cells(), forAllReverse, cachedRandom::globalPosition(), Foam::mag(), UPstream::myProcNo(), patchInjectionBase::patchArea_, patchInjectionBase::patchId_, patchInjectionBase::patchNormal_, points, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), cachedRandom::position(), triangle< Point, PointRef >::randomPoint(), List< T >::size(), patchInjectionBase::sumTriMagSf_, tf, patchInjectionBase::triCumulativeMagSf_, patchInjectionBase::triFace_, and patchInjectionBase::triToFace_.
Referenced by PatchInjection< CloudType >::clone(), PatchFlowRateInjection< CloudType >::clone(), and patchInjectionBase::updateMesh().
Member Data Documentation
patchName_
const word patchName_ protected
Patch name.
Definition at line 68 of file patchInjectionBase.H.
patchId_
const label patchId_ protected
Patch ID.
Definition at line 71 of file patchInjectionBase.H.
Referenced by patchInjectionBase::setPositionAndCell(), and patchInjectionBase::updateMesh().
patchArea_
scalar patchArea_ protected
Patch area - total across all processors.
Definition at line 74 of file patchInjectionBase.H.
Referenced by patchInjectionBase::setPositionAndCell(), and patchInjectionBase::updateMesh().
patchNormal_
vectorList patchNormal_ protected
Patch face normal directions.
Definition at line 77 of file patchInjectionBase.H.
Referenced by patchInjectionBase::setPositionAndCell(), and patchInjectionBase::updateMesh().
cellOwners_
labelList cellOwners_ protected
List of cell labels corresponding to injector positions.
Definition at line 80 of file patchInjectionBase.H.
Referenced by patchInjectionBase::setPositionAndCell(), and patchInjectionBase::updateMesh().
triFace_
faceList triFace_ protected
Decomposed patch faces as a list of triangles.
Definition at line 83 of file patchInjectionBase.H.
Referenced by patchInjectionBase::setPositionAndCell(), and patchInjectionBase::updateMesh().
triToFace_
labelList triToFace_ protected
Addressing from per triangle to patch face.
Definition at line 86 of file patchInjectionBase.H.
Referenced by patchInjectionBase::setPositionAndCell(), and patchInjectionBase::updateMesh().
triCumulativeMagSf_
scalarList triCumulativeMagSf_ protected
Cumulative triangle area per triangle face.
Definition at line 89 of file patchInjectionBase.H.
Referenced by patchInjectionBase::setPositionAndCell(), and patchInjectionBase::updateMesh().
sumTriMagSf_
scalarList sumTriMagSf_ protected
Cumulative area fractions per processor.
Definition at line 92 of file patchInjectionBase.H.
Referenced by patchInjectionBase::setPositionAndCell(), and patchInjectionBase::updateMesh().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/PatchInjection/patchInjectionBase.H
src/lagrangian/intermediate/submodels/Kinematic/InjectionModel/PatchInjection/patchInjectionBase.C