OpenFOAM: VirtualMassForce< CloudType > Class Template Reference
VirtualMassForce< CloudType > Class Template Reference
Calculates particle virtual mass force.
Public Member Functions
TypeName ("virtualMass")
Runtime type information.
VirtualMassForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType=typeName)
Construct from mesh.
VirtualMassForce (const VirtualMassForce &pgf)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~VirtualMassForce ()
Destructor.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Public Member Functions inherited from PressureGradientForce< CloudType >
TypeName ("pressureGradient")
Runtime type information.
PressureGradientForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType=typeName)
Construct from mesh.
PressureGradientForce (const PressureGradientForce &pgf)
Construct copy.
virtual ~PressureGradientForce ()
Destructor.
const interpolation< vector > & DUcDtInterp () const
Return the rate of change of carrier phase velocity interpolator.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Protected Attributes inherited from PressureGradientForce< CloudType >
const word UName_
Name of velocity field.
autoPtr< interpolation< vector > > DUcDtInterpPtr_
Rate of change of carrier phase velocity interpolator.
Detailed Description
template<class CloudType>
class Foam::VirtualMassForce< CloudType >
Calculates particle virtual mass force.
Source files
VirtualMassForce.H
VirtualMassForce.C
Definition at line 49 of file VirtualMassForce.H.
Constructor & Destructor Documentation
VirtualMassForce() [1/2]
VirtualMassForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const word & forceType = typeName)
Construct from mesh.
Definition at line 32 of file VirtualMassForce.C.
VirtualMassForce() [2/2]
VirtualMassForce (const VirtualMassForce< CloudType > & pgf)
Construct copy.
Definition at line 46 of file VirtualMassForce.C.
~VirtualMassForce()
~VirtualMassForce () virtual
Destructor.
Definition at line 58 of file VirtualMassForce.C.
Referenced by VirtualMassForce< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("virtualMass")
Runtime type information.
clone()
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from PressureGradientForce< CloudType >.
Definition at line 80 of file VirtualMassForce.H.
References VirtualMassForce< CloudType >::cacheFields(), VirtualMassForce< CloudType >::calcCoupled(), VirtualMassForce< CloudType >::massAdd(), p, Foam::Re(), and VirtualMassForce< CloudType >::~VirtualMassForce().
cacheFields()
void cacheFields (const bool store) virtual
Cache fields.
Reimplemented from PressureGradientForce< CloudType >.
Definition at line 65 of file VirtualMassForce.C.
References VirtualMassForce< CloudType >::calcCoupled().
Referenced by VirtualMassForce< CloudType >::clone().
calcCoupled()
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the non-coupled force.
Reimplemented from PressureGradientForce< CloudType >.
Definition at line 73 of file VirtualMassForce.C.
References VirtualMassForce< CloudType >::massAdd(), and forceSuSp::Su().
Referenced by VirtualMassForce< CloudType >::cacheFields(), and VirtualMassForce< CloudType >::clone().
massAdd()
Foam::scalar massAdd (const typename CloudType::parcelType & p, const scalar mass) const virtual
Return the added mass.
Reimplemented from PressureGradientForce< CloudType >.
Definition at line 92 of file VirtualMassForce.C.
Referenced by VirtualMassForce< CloudType >::calcCoupled(), and VirtualMassForce< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/VirtualMass/VirtualMassForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/VirtualMass/VirtualMassForce.C