OpenFOAM: ParticleForce< CloudType > Class Template Reference
ParticleForce< CloudType > Class Template Reference
Abstract base class for particle forces.
Public Types
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Public Member Functions
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Static Public Member Functions
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::ParticleForce< CloudType >
Abstract base class for particle forces.
Source files
ParticleForce.H
ParticleForceI.H
ParticleForce.C
ParticleForceNew.C
Definition at line 53 of file ParticleForce.H.
Member Typedef Documentation
returnType
typedef VectorSpace<Vector<vector>, vector, 2> returnType
Convenience typedef for return type.
Definition at line 88 of file ParticleForce.H.
Constructor & Destructor Documentation
ParticleForce() [1/2]
ParticleForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const word & forceType, const bool readCoeffs)
Construct from mesh.
Definition at line 32 of file ParticleForce.C.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
ParticleForce() [2/2]
ParticleForce (const ParticleForce< CloudType > & pf)
Construct copy.
Definition at line 56 of file ParticleForce.C.
~ParticleForce()
~ParticleForce () virtual
Destructor.
Definition at line 67 of file ParticleForce.C.
Referenced by ParticleForce< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , ParticleForce< CloudType > , dictionary , (CloudType &owner, const fvMesh &mesh, const dictionary &dict) , (owner, mesh, dict))
Declare runtime constructor selection table.
clone()
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented in NonSphereDragForce< CloudType >, BrownianMotionForce< CloudType >, NonInertialFrameForce< CloudType >, LiftForce< CloudType >, TomiyamaLiftForce< CloudType >, ParamagneticForce< CloudType >, SaffmanMeiLiftForce< CloudType >, PressureGradientForce< CloudType >, DistortedSphereDragForce< CloudType >, ErgunWenYuDragForce< CloudType >, PlessisMasliyahDragForce< CloudType >, WenYuDragForce< CloudType >, GravityForce< CloudType >, SRFForce< CloudType >, VirtualMassForce< CloudType >, and SphereDragForce< CloudType >.
Definition at line 107 of file ParticleForce.H.
References ParticleForce< CloudType >::cacheFields(), ParticleForce< CloudType >::calcCoupled(), ParticleForce< CloudType >::calcNonCoupled(), ParticleForce< CloudType >::coeffs(), ParticleForce< CloudType >::massAdd(), ParticleForce< CloudType >::mesh(), ParticleForce< CloudType >::New(), ParticleForce< CloudType >::owner(), p, Foam::Re(), and ParticleForce< CloudType >::~ParticleForce().
New()
Foam::autoPtr< Foam::ParticleForce< CloudType > > New (CloudType & owner, const fvMesh & mesh, const dictionary & dict, const word & forceType) static
Selector.
Definition at line 33 of file ParticleForceNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, mesh, and Foam::nl.
Referenced by ParticleForce< CloudType >::clone().
owner() [1/2]
const CloudType & owner () const inline
Return const access to the cloud owner.
Definition at line 29 of file ParticleForceI.H.
Referenced by LiftForce< CloudType >::cacheFields(), and ParticleForce< CloudType >::clone().
owner() [2/2]
CloudType & owner () inline
Return refernce to the cloud owner.
Definition at line 36 of file ParticleForceI.H.
mesh()
const Foam::fvMesh & mesh () const inline
Return the mesh database.
Definition at line 43 of file ParticleForceI.H.
Referenced by LiftForce< CloudType >::cacheFields(), and ParticleForce< CloudType >::clone().
coeffs()
const Foam::dictionary & coeffs () const inline
Return the force coefficients dictionary.
Definition at line 50 of file ParticleForceI.H.
Referenced by ParticleForce< CloudType >::clone().
cacheFields()
void cacheFields (const bool store) virtual
Cache fields.
Reimplemented in BrownianMotionForce< CloudType >, NonInertialFrameForce< CloudType >, LiftForce< CloudType >, ParamagneticForce< CloudType >, PressureGradientForce< CloudType >, SRFForce< CloudType >, and VirtualMassForce< CloudType >.
Definition at line 74 of file ParticleForce.C.
References ParticleForce< CloudType >::calcCoupled().
Referenced by ParticleForce< CloudType >::clone().
calcCoupled()
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the coupled force.
Reimplemented in NonSphereDragForce< CloudType >, BrownianMotionForce< CloudType >, LiftForce< CloudType >, PressureGradientForce< CloudType >, DistortedSphereDragForce< CloudType >, ErgunWenYuDragForce< CloudType >, PlessisMasliyahDragForce< CloudType >, WenYuDragForce< CloudType >, VirtualMassForce< CloudType >, and SphereDragForce< CloudType >.
Definition at line 80 of file ParticleForce.C.
References ParticleForce< CloudType >::calcNonCoupled(), forceSuSp::Sp(), forceSuSp::Su(), and Foam::Zero.
Referenced by ParticleForce< CloudType >::cacheFields(), and ParticleForce< CloudType >::clone().
calcNonCoupled()
Foam::forceSuSp calcNonCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the non-coupled force.
Reimplemented in NonInertialFrameForce< CloudType >, ParamagneticForce< CloudType >, GravityForce< CloudType >, and SRFForce< CloudType >.
Definition at line 98 of file ParticleForce.C.
References ParticleForce< CloudType >::massAdd(), forceSuSp::Sp(), forceSuSp::Su(), and Foam::Zero.
Referenced by ParticleForce< CloudType >::calcCoupled(), and ParticleForce< CloudType >::clone().
massAdd()
Foam::scalar massAdd (const typename CloudType::parcelType & p, const scalar mass) const virtual
Return the added mass.
Reimplemented in PressureGradientForce< CloudType >, and VirtualMassForce< CloudType >.
Definition at line 116 of file ParticleForce.C.
Referenced by ParticleForce< CloudType >::calcNonCoupled(), and ParticleForce< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/ParticleForce/ParticleForce.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/ParticleForce/ParticleForce.C
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/ParticleForce/ParticleForceI.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/ParticleForce/ParticleForceNew.C