OpenFOAM: StandardWallInteraction< CloudType > Class Template Reference
StandardWallInteraction< CloudType > Class Template Reference
Wall interaction model.
Public Member Functions
TypeName ("standardWallInteraction")
Runtime type information.
StandardWallInteraction (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
StandardWallInteraction (const StandardWallInteraction< CloudType > &pim)
Construct copy from owner cloud and patch interaction model.
virtual autoPtr< PatchInteractionModel< CloudType > > clone () const
Construct and return a clone using supplied owner cloud.
virtual ~StandardWallInteraction ()
Destructor.
virtual bool correct (typename CloudType::parcelType &p, const polyPatch &pp, bool &keepParticle, const scalar trackFraction, const tetIndices &tetIs)
Apply velocity correction.
virtual void info (Ostream &os)
Write patch interaction info to stream.
Public Member Functions inherited from PatchInteractionModel< CloudType >
TypeName ("patchInteractionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, PatchInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
PatchInteractionModel (CloudType &owner)
Construct null from owner.
PatchInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
PatchInteractionModel (const PatchInteractionModel< CloudType > &pim)
Construct copy.
virtual ~PatchInteractionModel ()
Destructor.
const word & UName () const
Return name of velocity field.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Attributes
PatchInteractionModel< CloudType >::interactionType interactionType_
Interaction type.
scalar e_
Elasticity coefficient.
scalar mu_
Restitution coefficient.
label nEscape_
Number of parcels escaped.
scalar massEscape_
Mass of parcels escaped.
label nStick_
Number of parcels stuck to patches.
scalar massStick_
Mass of parcels stuck to patches.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from PatchInteractionModel< CloudType >
enum interactionType { itRebound, itStick, itEscape, itOther }
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from PatchInteractionModel< CloudType >
static autoPtr< PatchInteractionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
static word interactionTypeToWord (const interactionType &itEnum)
Convert interaction result to word.
static interactionType wordToInteractionType (const word &itWord)
Convert word to interaction result.
Static Public Attributes inherited from PatchInteractionModel< CloudType >
static wordList interactionTypeNames_
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Detailed Description
template<class CloudType>
class Foam::StandardWallInteraction< CloudType >
Wall interaction model.
Three choices:
rebound - optionally specify elasticity and restitution coefficients
stick - particles assigned zero velocity
escape - remove particle from the domain
Example usage:
StandardWallInteractionCoeffs
{
    type        rebound; // stick, escape
    e           1;       // optional - elasticity coeff
    mu          0;       // optional - restitution coeff
}
Definition at line 60 of file StandardWallInteraction.H.
Constructor & Destructor Documentation
StandardWallInteraction() [1/2]
StandardWallInteraction (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 32 of file StandardWallInteraction.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and lookup().
StandardWallInteraction() [2/2]
StandardWallInteraction (const StandardWallInteraction< CloudType > & pim)
Construct copy from owner cloud and patch interaction model.
Definition at line 79 of file StandardWallInteraction.C.
~StandardWallInteraction()
~StandardWallInteraction () virtual
Destructor.
Definition at line 97 of file StandardWallInteraction.C.
References StandardWallInteraction< CloudType >::correct().
Referenced by StandardWallInteraction< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("standardWallInteraction")
Runtime type information.
clone()
virtual autoPtr<PatchInteractionModel<CloudType> > clone () const inline virtual
Construct and return a clone using supplied owner cloud.
Implements PatchInteractionModel< CloudType >.
Definition at line 109 of file StandardWallInteraction.H.
References StandardWallInteraction< CloudType >::correct(), StandardWallInteraction< CloudType >::info(), p, and StandardWallInteraction< CloudType >::~StandardWallInteraction().
correct()
bool correct (typename CloudType::parcelType & p, const polyPatch & pp, bool & keepParticle, const scalar trackFraction, const tetIndices & tetIs) virtual
Apply velocity correction.
Returns true if particle remains in same cell
Implements PatchInteractionModel< CloudType >.
Definition at line 105 of file StandardWallInteraction.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, nw, U, and Foam::Zero.
Referenced by StandardWallInteraction< CloudType >::clone(), and StandardWallInteraction< CloudType >::~StandardWallInteraction().
info()
void info (Ostream & os) virtual
Write patch interaction info to stream.
Reimplemented from PatchInteractionModel< CloudType >.
Definition at line 184 of file StandardWallInteraction.C.
References Foam::nl, and Foam::returnReduce().
Referenced by StandardWallInteraction< CloudType >::clone().
Member Data Documentation
interactionType_
PatchInteractionModel<CloudType>::interactionType interactionType_ protected
Interaction type.
Definition at line 70 of file StandardWallInteraction.H.
e_
scalar e_ protected
Elasticity coefficient.
Definition at line 73 of file StandardWallInteraction.H.
mu_
scalar mu_ protected
Restitution coefficient.
Definition at line 76 of file StandardWallInteraction.H.
nEscape_
label nEscape_ protected
Number of parcels escaped.
Definition at line 82 of file StandardWallInteraction.H.
massEscape_
scalar massEscape_ protected
Mass of parcels escaped.
Definition at line 85 of file StandardWallInteraction.H.
nStick_
label nStick_ protected
Number of parcels stuck to patches.
Definition at line 88 of file StandardWallInteraction.H.
massStick_
scalar massStick_ protected
Mass of parcels stuck to patches.
Definition at line 91 of file StandardWallInteraction.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/StandardWallInteraction/StandardWallInteraction.H
src/lagrangian/intermediate/submodels/Kinematic/PatchInteractionModel/StandardWallInteraction/StandardWallInteraction.C