OpenFOAM: noCorrectionLimiting Class Reference
noCorrectionLimiting Class Reference
Public Member Functions
TypeName ("none")
Runtime type information.
noCorrectionLimiting (const dictionary &dict)
Construct from components.
noCorrectionLimiting (const noCorrectionLimiting &cl)
Construct as copy.
virtual autoPtr< CorrectionLimitingMethod > clone () const
Construct and return a clone.
virtual ~noCorrectionLimiting ()
Destructor.
virtual vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const
Return the limited velocity.
Public Member Functions inherited from CorrectionLimitingMethod
TypeName ("correctionLimitingMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CorrectionLimitingMethod, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
CorrectionLimitingMethod (const dictionary &dict)
Construct from components.
CorrectionLimitingMethod (const CorrectionLimitingMethod &cl)
Construct as copy.
virtual ~CorrectionLimitingMethod ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from CorrectionLimitingMethod
static autoPtr< CorrectionLimitingMethod > New (const dictionary &dict)
Selector.
Detailed Description
Source files
noCorrectionLimiting.H
noCorrectionLimiting.C
Definition at line 49 of file noCorrectionLimiting.H.
Constructor & Destructor Documentation
noCorrectionLimiting() [1/2]
noCorrectionLimiting (const dictionary & dict)
Construct from components.
Definition at line 47 of file noCorrectionLimiting.C.
Referenced by noCorrectionLimiting::clone().
noCorrectionLimiting() [2/2]
noCorrectionLimiting (const noCorrectionLimiting & cl)
Construct as copy.
Definition at line 56 of file noCorrectionLimiting.C.
~noCorrectionLimiting()
~noCorrectionLimiting () virtual
Destructor.
Definition at line 66 of file noCorrectionLimiting.C.
References noCorrectionLimiting::limitedVelocity().
Referenced by noCorrectionLimiting::clone().
Member Function Documentation
TypeName()
TypeName ("none")
Runtime type information.
clone()
virtual autoPtr<CorrectionLimitingMethod> clone () const inline virtual
Construct and return a clone.
Implements CorrectionLimitingMethod.
Definition at line 68 of file noCorrectionLimiting.H.
References noCorrectionLimiting::limitedVelocity(), noCorrectionLimiting::noCorrectionLimiting(), and noCorrectionLimiting::~noCorrectionLimiting().
limitedVelocity()
Foam::vector limitedVelocity (const vector uP, const vector dU, const vector uMean) const virtual
Return the limited velocity.
Implements CorrectionLimitingMethod.
Definition at line 74 of file noCorrectionLimiting.C.
Referenced by noCorrectionLimiting::clone(), and noCorrectionLimiting::~noCorrectionLimiting().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/noCorrectionLimiting/noCorrectionLimiting.H
src/lagrangian/intermediate/submodels/MPPIC/CorrectionLimitingMethods/noCorrectionLimiting/noCorrectionLimiting.C