OpenFOAM: Dual< Type > Class Template Reference
Dual< Type > Class Template Reference
Dual-mesh lagrangian averaging procedure.
Public Types
typedef AveragingMethod< Type >::TypeGrad TypeGrad
Public typedefs.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from FieldField< Field, Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Public Member Functions
TypeName ("dual")
Runtime type information.
Dual (const IOobject &io, const dictionary &dict, const fvMesh &mesh)
Constructors.
Dual (const Dual< Type > &am)
Construct a copy.
virtual autoPtr< AveragingMethod< Type > > clone () const
Construct and return a clone.
virtual ~Dual ()
Destructor.
void add (const point position, const tetIndices &tetIs, const Type &value)
Member Functions.
Type interpolate (const point position, const tetIndices &tetIs) const
Interpolate.
TypeGrad interpolateGrad (const point position, const tetIndices &tetIs) const
Interpolate gradient.
void average ()
Calculate the average.
void average (const AveragingMethod< scalar > &weight)
tmp< Field< Type > > primitiveField () const
Return an internal field of the average.
tmp< Field< TypeGrad > > internalFieldGrad () const
Return an internal field of the gradient.
Public Member Functions inherited from AveragingMethod< Type >
TypeName ("averagingMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AveragingMethod, dictionary,(const IOobject &io, const dictionary &dict, const fvMesh &mesh),(io, dict, mesh))
Declare runtime constructor selection table.
AveragingMethod (const IOobject &io, const dictionary &dict, const fvMesh &mesh, const labelList &size)
Constructors.
AveragingMethod (const AveragingMethod< Type > &am)
Construct a copy.
virtual ~AveragingMethod ()
Destructor.
virtual bool writeData (Ostream &) const
Dummy write.
virtual bool write () const
Write using setting from DB.
void operator= (const AveragingMethod< Type > &x)
Assign to another average.
void operator= (const Type &x)
Assign to value.
void operator= (tmp< FieldField< Field, Type >> x)
Assign to tmp.
void operator+= (tmp< FieldField< Field, Type >> x)
Add-equal tmp.
void operator*= (tmp< FieldField< Field, Type >> x)
Multiply-equal tmp.
void operator/= (tmp< FieldField< Field, scalar >> x)
Divide-equal tmp.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from FieldField< Field, Type >
FieldField ()
Construct null.
FieldField (const label)
Construct given size.
FieldField (const word &, const FieldField< Field, Type > &)
Construct using the Field sizes from the given FieldField.
FieldField (const FieldField< Field, Type > &)
Construct as copy.
FieldField (FieldField< Field, Type > &, bool reuse)
Construct as copy or re-use as specified.
FieldField (const PtrList< Field< Type >> &)
Construct as copy of a PtrList<Field, Type>
FieldField (const tmp< FieldField< Field, Type >> &)
Construct as copy of tmp<FieldField>
FieldField (Istream &)
Construct from Istream.
tmp< FieldField< Field, Type > > clone () const
Clone.
void negate ()
Negate this field.
tmp< FieldField< Field, cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const FieldField< Field, cmptType > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< FieldField< Field, Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const FieldField< Field, Type > &)
void operator= (const tmp< FieldField< Field, Type >> &)
void operator= (const Type &)
void operator+= (const FieldField< Field, Type > &)
void operator+= (const tmp< FieldField< Field, Type >> &)
void operator-= (const FieldField< Field, Type > &)
void operator-= (const tmp< FieldField< Field, Type >> &)
void operator*= (const FieldField< Field, scalar > &)
void operator*= (const tmp< FieldField< Field, scalar >> &)
void operator/= (const FieldField< Field, scalar > &)
void operator/= (const tmp< FieldField< Field, scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from PtrList< Field< Type > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< Field< Type > > &)
Copy constructor.
PtrList (const PtrList< Field< Type > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< Field< Type > >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< Field< Type > > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< Field< Type > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (Field< Type > *)
Append an element at the end of the list.
void append (const autoPtr< Field< Type > > &)
void append (const tmp< Field< Type > > &)
void transfer (PtrList< Field< Type > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< Field< Type > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< Field< Type > > set (const label, Field< Type > *)
Set element to given T* and return old element (can be nullptr)
autoPtr< Field< Type > > set (const label, const autoPtr< Field< Type > > &)
Set element to given autoPtr<T> and return old element.
autoPtr< Field< Type > > set (const label, const tmp< Field< Type > > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< Field< Type > > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Static Public Member Functions inherited from AveragingMethod< Type >
static autoPtr< AveragingMethod< Type > > New (const IOobject &io, const dictionary &dict, const fvMesh &mesh)
Selector.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from FieldField< Field, Type >
template<class Type2 >
static tmp< FieldField< Field, Type > > NewCalculatedType (const FieldField< Field, Type2 > &ff)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Types inherited from AveragingMethod< Type >
typedef outerProduct< vector, Type >::type TypeGrad
Protected typedefs.
Protected Member Functions inherited from AveragingMethod< Type >
virtual void updateGrad ()
Protected member functions.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from PtrList< Field< Type > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Attributes inherited from AveragingMethod< Type >
const dictionary & dict_
Protected data.
const fvMesh & mesh_
The mesh on which the averaging is to be done.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Type>
class Foam::AveragingMethods::Dual< Type >
Dual-mesh lagrangian averaging procedure.
Point values are summed using the tetrahedral decomposition of the computational cells. Summation is done in the cells, and also in the terahedrons surrounding each point. The latter forms a type of dual mesh. The interpolation is weighted by proximity to the cell centre or point, as calculated by the barycentric coordinate within the tethrahedron.
Values are interpolated linearly across the tethrahedron. Gradients are calculated directly from the point values using a first order finite element basis. The computed gradient is assumed constant over the tethrahedron.
Source files
Dual.H
Dual.C
Definition at line 64 of file Dual.H.
Member Typedef Documentation
TypeGrad
typedef AveragingMethod<Type>::TypeGrad TypeGrad
Public typedefs.
Gradient type
Definition at line 73 of file Dual.H.
Constructor & Destructor Documentation
Dual() [1/2]
Dual (const IOobject & io, const dictionary & dict, const fvMesh & mesh)
Constructors.
Construct from components
Definition at line 48 of file Dual.C.
References f(), tetIndices::face(), tetIndices::faceBasePt(), tetIndices::facePtA(), tetIndices::facePtB(), forAll, tetrahedron< Point, PointRef >::mag(), and tetIndices::tet().
Dual() [2/2]
Dual (const Dual< Type > & am)
Construct a copy.
Definition at line 88 of file Dual.C.
~Dual()
~Dual () virtual
Destructor.
Definition at line 105 of file Dual.C.
References Dual< Type >::add(), tetrahedron< Point, PointRef >::barycentric(), f(), tetIndices::face(), tetIndices::faceBasePt(), tetIndices::facePtA(), tetIndices::facePtB(), Foam::max(), and tetIndices::tet().
Referenced by Dual< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("dual")
Runtime type information.
clone()
virtual autoPtr<AveragingMethod<Type> > clone () const inline virtual
Construct and return a clone.
Implements AveragingMethod< Type >.
Definition at line 138 of file Dual.H.
References Dual< Type >::add(), Dual< Type >::average(), Dual< Type >::internalFieldGrad(), Dual< Type >::interpolate(), Dual< Type >::interpolateGrad(), Dual< Type >::primitiveField(), and Dual< Type >::~Dual().
add()
void add (const point position, const tetIndices & tetIs, const Type & value) virtual
Member Functions.
Add point value to interpolation
Implements AveragingMethod< Type >.
Definition at line 146 of file Dual.C.
References tetIndices::cell(), and Dual< Type >::interpolate().
Referenced by Dual< Type >::clone(), and Dual< Type >::~Dual().
interpolate()
Type interpolate (const point position, const tetIndices & tetIs) const virtual
Interpolate.
Implements AveragingMethod< Type >.
Definition at line 169 of file Dual.C.
References tetIndices::cell(), and Dual< Type >::interpolateGrad().
Referenced by Dual< Type >::add(), and Dual< Type >::clone().
interpolateGrad()
Foam::AveragingMethods::Dual< Type >::TypeGrad interpolateGrad (const point position, const tetIndices & tetIs) const virtual
Interpolate gradient.
Implements AveragingMethod< Type >.
Definition at line 187 of file Dual.C.
References tetIndices::cell(), Foam::inv(), s(), and T.
Referenced by Dual< Type >::clone(), and Dual< Type >::interpolate().
average() [1/2]
void average () virtual
Calculate the average.
Reimplemented from AveragingMethod< Type >.
Definition at line 225 of file Dual.C.
References Foam::fvc::average().
Referenced by Dual< Type >::clone().
average() [2/2]
void average (const AveragingMethod< scalar > & weight) virtual
Reimplemented from AveragingMethod< Type >.
Definition at line 235 of file Dual.C.
References Foam::fvc::average().
primitiveField()
Foam::tmp< Foam::Field< Type > > primitiveField () const virtual
Return an internal field of the average.
Implements AveragingMethod< Type >.
Definition at line 247 of file Dual.C.
Referenced by Dual< Type >::clone().
internalFieldGrad()
tmp<Field<TypeGrad> > internalFieldGrad () const
Return an internal field of the gradient.
Referenced by Dual< Type >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/AveragingMethods/Dual/Dual.H
src/lagrangian/intermediate/submodels/MPPIC/AveragingMethods/Dual/Dual.C