OpenFOAM: Implicit< CloudType > Class Template Reference
Implicit< CloudType > Class Template Reference
Implicit model for applying an inter-particle stress to the particles.
Public Member Functions
TypeName ("implicit")
Runtime type information.
Implicit (const dictionary &dict, CloudType &owner)
Construct from components.
Implicit (const Implicit< CloudType > &cm)
Construct copy.
virtual autoPtr< PackingModel< CloudType > > clone () const
Construct and return a clone.
virtual ~Implicit ()
Destructor.
virtual void cacheFields (const bool store)
Calculate the inter particles stresses.
virtual vector velocityCorrection (typename CloudType::parcelType &p, const scalar deltaT) const
Calculate the velocity correction.
Public Member Functions inherited from PackingModel< CloudType >
TypeName ("packingModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, PackingModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
PackingModel (CloudType &owner)
Construct null from owner.
PackingModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
PackingModel (const PackingModel< CloudType > &cm)
Construct copy.
virtual ~PackingModel ()
Destructor.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from PackingModel< CloudType >
static autoPtr< PackingModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from PackingModel< CloudType >
autoPtr< ParticleStressModel > particleStressModel_
Protected data.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::PackingModels::Implicit< CloudType >
Implicit model for applying an inter-particle stress to the particles.
The time evolution of particulate volume fraction is solved for implicitly on the eulerian mesh. The computed flux is then applied to the lagrangian field. The gravity force can optionally be applied to the particles as part of this model, using the keyword "applyGravity".
Source files
Implicit.H
Implicit.C
Definition at line 56 of file Implicit.H.
Constructor & Destructor Documentation
Implicit() [1/2]
Implicit (const dictionary & dict, CloudType & owner)
Construct from components.
Definition at line 39 of file Implicit.C.
Implicit() [2/2]
Implicit (const Implicit< CloudType > & cm)
Construct copy.
Definition at line 73 of file Implicit.C.
~Implicit()
~Implicit () virtual
Destructor.
Definition at line 93 of file Implicit.C.
Referenced by Implicit< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("implicit")
Runtime type information.
clone()
virtual autoPtr<PackingModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements PackingModel< CloudType >.
Definition at line 98 of file Implicit.H.
References Implicit< CloudType >::cacheFields(), p, Implicit< CloudType >::velocityCorrection(), and Implicit< CloudType >::~Implicit().
cacheFields()
void cacheFields (const bool store) virtual
Calculate the inter particles stresses.
Reimplemented from subModelBase.
Definition at line 100 of file Implicit.C.
References tmp< T >::clear(), cloudName(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvc::ddt(), Foam::dimDensity, Foam::dimPressure, Foam::dimVelocity, Foam::fvc::div(), fvMatrix< Type >::flux(), forAll, g, Foam::MULES::interpolate(), Foam::fvc::laplacian(), Foam::linearInterpolate(), objectRegistry::lookupObject(), Foam::max(), mesh, Foam::min(), phi, AveragingMethod< Type >::primitiveField(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), Foam::fvc::reconstruct(), rho, fvSchemes::setFluxRequired(), fvMesh::Sf(), fvMatrix< Type >::solve(), timeName, U, Implicit< CloudType >::velocityCorrection(), and Foam::Zero.
Referenced by Implicit< CloudType >::clone().
velocityCorrection()
Foam::vector velocityCorrection (typename CloudType::parcelType & p, const scalar deltaT) const virtual
Calculate the velocity correction.
Implements PackingModel< CloudType >.
Definition at line 332 of file Implicit.C.
References polyMesh::boundaryMesh(), polyMesh::faces(), Foam::mag(), mesh, patchi, phi, polyMesh::points(), U, and polyBoundaryMesh::whichPatch().
Referenced by Implicit< CloudType >::cacheFields(), and Implicit< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/PackingModels/Implicit/Implicit.H
src/lagrangian/intermediate/submodels/MPPIC/PackingModels/Implicit/Implicit.C