OpenFOAM: NoSurfaceFilm< CloudType > Class Template Reference
NoSurfaceFilm< CloudType > Class Template Reference
Place holder for 'none' option.
Public Member Functions
TypeName ("none")
Runtime type information.
NoSurfaceFilm (const dictionary &, CloudType &)
Construct from dictionary.
NoSurfaceFilm (const NoSurfaceFilm< CloudType > &dm)
Construct copy.
virtual autoPtr< SurfaceFilmModel< CloudType > > clone () const
Construct and return a clone.
virtual ~NoSurfaceFilm ()
Destructor.
virtual bool active () const
Flag to indicate whether model activates the surface film model.
virtual bool transferParcel (parcelType &p, const polyPatch &pp, bool &keepParticle)
Transfer parcel from cloud to surface film.
virtual void setParcelProperties (parcelType &p, const label filmCelli) const
Set parcel properties.
virtual void info (Ostream &os)
Write surface film info to stream.
Public Member Functions inherited from SurfaceFilmModel< CloudType >
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, SurfaceFilmModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
SurfaceFilmModel (CloudType &owner)
Construct null from owner.
SurfaceFilmModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
SurfaceFilmModel (const SurfaceFilmModel< CloudType > &sfm)
Construct copy.
virtual ~SurfaceFilmModel ()
Destructor.
const dimensionedVector & g () const
Return gravitational acceleration constant.
label nParcelsTransferred () const
Return const access to the number of parcels transferred to the.
label & nParcelsTransferred ()
Return non-const access to the number of parcels transferred to.
label nParcelsInjected () const
Return const access to the number of parcels injected from the.
label & nParcelsInjected ()
Return non-const access to the number of parcels injected from.
template<class TrackData >
void inject (TrackData &td)
Inject parcels into the cloud.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Types
typedef CloudType::parcelType parcelType
Convenience typedef for parcel type.
Protected Types inherited from SurfaceFilmModel< CloudType >
typedef CloudType::parcelType parcelType
Convenience typedef to the cloud's parcel type.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from SurfaceFilmModel< CloudType >
static autoPtr< SurfaceFilmModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from SurfaceFilmModel< CloudType >
virtual void cacheFilmFields (const label filmPatchi, const label primaryPatchi, const regionModels::surfaceFilmModels::surfaceFilmModel &filmModel)
Cache the film fields in preparation for injection.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from SurfaceFilmModel< CloudType >
const dimensionedVector & g_
Gravitational acceleration constant.
label ejectedParcelType_
Ejected parcel type label - id assigned to identify parcel for.
scalarList massParcelPatch_
Parcel mass / patch face.
scalarList diameterParcelPatch_
Parcel diameter / patch face.
List< vector > UFilmPatch_
Film velocity / patch face.
scalarList rhoFilmPatch_
Film density / patch face.
scalarListList deltaFilmPatch_
Film height of all film patches / patch face.
label nParcelsTransferred_
Number of parcels transferred to the film model.
label nParcelsInjected_
Number of parcels injected from the film model.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::NoSurfaceFilm< CloudType >
Place holder for 'none' option.
Source files
NoSurfaceFilm.H
NoSurfaceFilm.C
Definition at line 49 of file NoSurfaceFilm.H.
Member Typedef Documentation
parcelType
typedef CloudType::parcelType parcelType protected
Convenience typedef for parcel type.
Definition at line 58 of file NoSurfaceFilm.H.
Constructor & Destructor Documentation
NoSurfaceFilm() [1/2]
NoSurfaceFilm (const dictionary & , CloudType & owner)
Construct from dictionary.
Definition at line 33 of file NoSurfaceFilm.C.
NoSurfaceFilm() [2/2]
NoSurfaceFilm (const NoSurfaceFilm< CloudType > & dm)
Construct copy.
Definition at line 44 of file NoSurfaceFilm.C.
~NoSurfaceFilm()
~NoSurfaceFilm () virtual
Destructor.
Definition at line 55 of file NoSurfaceFilm.C.
Referenced by NoSurfaceFilm< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("none")
Runtime type information.
clone()
virtual autoPtr<SurfaceFilmModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements SurfaceFilmModel< CloudType >.
Definition at line 76 of file NoSurfaceFilm.H.
References NoSurfaceFilm< CloudType >::active(), NoSurfaceFilm< CloudType >::info(), p, NoSurfaceFilm< CloudType >::setParcelProperties(), NoSurfaceFilm< CloudType >::transferParcel(), and NoSurfaceFilm< CloudType >::~NoSurfaceFilm().
active()
bool active () const virtual
Flag to indicate whether model activates the surface film model.
Reimplemented from subModelBase.
Definition at line 62 of file NoSurfaceFilm.C.
References NoSurfaceFilm< CloudType >::transferParcel().
Referenced by NoSurfaceFilm< CloudType >::clone().
transferParcel()
bool transferParcel (parcelType & p, const polyPatch & pp, bool & keepParticle) virtual
Transfer parcel from cloud to surface film.
Returns true if parcel is to be transferred
Implements SurfaceFilmModel< CloudType >.
Definition at line 70 of file NoSurfaceFilm.C.
References NoSurfaceFilm< CloudType >::setParcelProperties().
Referenced by NoSurfaceFilm< CloudType >::active(), and NoSurfaceFilm< CloudType >::clone().
setParcelProperties()
void setParcelProperties (parcelType & p, const label filmCelli) const virtual
Set parcel properties.
Reimplemented from SurfaceFilmModel< CloudType >.
Definition at line 82 of file NoSurfaceFilm.C.
Referenced by NoSurfaceFilm< CloudType >::clone(), and NoSurfaceFilm< CloudType >::transferParcel().
info()
void info (Ostream & os) virtual
Write surface film info to stream.
Reimplemented from SurfaceFilmModel< CloudType >.
Definition at line 90 of file NoSurfaceFilm.C.
Referenced by NoSurfaceFilm< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/NoSurfaceFilm/NoSurfaceFilm.H
src/lagrangian/intermediate/submodels/Kinematic/SurfaceFilmModel/NoSurfaceFilm/NoSurfaceFilm.C