OpenFOAM: SingleKineticRateDevolatilisation< CloudType > Class Template Reference
SingleKineticRateDevolatilisation< CloudType > Class Template Reference
Single kinetic rate devolatisation model.
Public Member Functions
TypeName ("singleKineticRateDevolatilisation")
Runtime type information.
SingleKineticRateDevolatilisation (const dictionary &dict, CloudType &owner)
Construct from dictionary.
SingleKineticRateDevolatilisation (const SingleKineticRateDevolatilisation< CloudType > &dm)
Construct copy.
virtual autoPtr< DevolatilisationModel< CloudType > > clone () const
Construct and return a clone.
virtual ~SingleKineticRateDevolatilisation ()
Destructor.
virtual void calculate (const scalar dt, const scalar age, const scalar mass0, const scalar mass, const scalar T, const scalarField &YGasEff, const scalarField &YLiquidEff, const scalarField &YSolidEff, label &canCombust, scalarField &dMassDV) const
Update model.
Public Member Functions inherited from DevolatilisationModel< CloudType >
TypeName ("devolatilisationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DevolatilisationModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
DevolatilisationModel (CloudType &owner)
Construct null from owner.
DevolatilisationModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
DevolatilisationModel (const DevolatilisationModel< CloudType > &dm)
Construct copy.
virtual ~DevolatilisationModel ()
Destructor.
void addToDevolatilisationMass (const scalar dMass)
Add to devolatilisation mass.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from DevolatilisationModel< CloudType >
static autoPtr< DevolatilisationModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from DevolatilisationModel< CloudType >
scalar dMass_
Mass of lagrangian phase converted.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::SingleKineticRateDevolatilisation< CloudType >
Single kinetic rate devolatisation model.
- acts on a per-specie basis
Rate given by Arrhenius eqn
kappa = A1.exp(- E/R.T)
Where: kappa = rate constant A1 = activation energy (user input) E = pre-exponential factor (user input) R = universal gas constant T = temperature
Usage:
SingleKineticRateDevolatilisationCoeffs { volatileData ((CH4 12 0.5) // (name A1 E) (CO2 12 0.5) // (name A1 E));
volatileResidualCoeff 1e-6; }
Definition at line 69 of file SingleKineticRateDevolatilisation.H.
Constructor & Destructor Documentation
SingleKineticRateDevolatilisation() [1/2]
SingleKineticRateDevolatilisation (const dictionary & dict, CloudType & owner)
Construct from dictionary.
Definition at line 33 of file SingleKineticRateDevolatilisation.C.
References Foam::endl(), forAll, Foam::Info, Foam::nl, and WarningInFunction.
SingleKineticRateDevolatilisation() [2/2]
SingleKineticRateDevolatilisation (const SingleKineticRateDevolatilisation< CloudType > & dm)
Construct copy.
Definition at line 75 of file SingleKineticRateDevolatilisation.C.
References SingleKineticRateDevolatilisation< CloudType >::~SingleKineticRateDevolatilisation().
~SingleKineticRateDevolatilisation()
~SingleKineticRateDevolatilisation () virtual
Destructor.
Definition at line 91 of file SingleKineticRateDevolatilisation.C.
References SingleKineticRateDevolatilisation< CloudType >::calculate().
Referenced by SingleKineticRateDevolatilisation< CloudType >::clone(), and SingleKineticRateDevolatilisation< CloudType >::SingleKineticRateDevolatilisation().
Member Function Documentation
TypeName()
TypeName ("singleKineticRateDevolatilisation")
Runtime type information.
clone()
virtual autoPtr<DevolatilisationModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements DevolatilisationModel< CloudType >.
Definition at line 212 of file SingleKineticRateDevolatilisation.H.
References SingleKineticRateDevolatilisation< CloudType >::calculate(), Foam::T(), and SingleKineticRateDevolatilisation< CloudType >::~SingleKineticRateDevolatilisation().
calculate()
void calculate (const scalar dt, const scalar age, const scalar mass0, const scalar mass, const scalar T, const scalarField & YGasEff, const scalarField & YLiquidEff, const scalarField & YSolidEff, label & canCombust, scalarField & dMassDV) const virtual
Update model.
Implements DevolatilisationModel< CloudType >.
Definition at line 99 of file SingleKineticRateDevolatilisation.C.
References Foam::exp(), forAll, Foam::constant::electromagnetic::kappa, Foam::min(), and Foam::constant::thermodynamic::RR.
Referenced by SingleKineticRateDevolatilisation< CloudType >::clone(), and SingleKineticRateDevolatilisation< CloudType >::~SingleKineticRateDevolatilisation().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/ReactingMultiphase/DevolatilisationModel/SingleKineticRateDevolatilisation/SingleKineticRateDevolatilisation.H
src/lagrangian/intermediate/submodels/ReactingMultiphase/DevolatilisationModel/SingleKineticRateDevolatilisation/SingleKineticRateDevolatilisation.C