OpenFOAM: LiquidEvaporation< CloudType > Class Template Reference
LiquidEvaporation< CloudType > Class Template Reference
Liquid evaporation model.
Public Member Functions
TypeName ("liquidEvaporation")
Runtime type information.
LiquidEvaporation (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
LiquidEvaporation (const LiquidEvaporation< CloudType > &pcm)
Construct copy.
virtual autoPtr< PhaseChangeModel< CloudType > > clone () const
Construct and return a clone.
virtual ~LiquidEvaporation ()
Destructor.
virtual void calculate (const scalar dt, const label celli, const scalar Re, const scalar Pr, const scalar d, const scalar nu, const scalar T, const scalar Ts, const scalar pc, const scalar Tc, const scalarField &X, scalarField &dMassPC) const
Update model.
virtual scalar dh (const label idc, const label idl, const scalar p, const scalar T) const
Return the enthalpy per unit mass.
virtual scalar Tvap (const scalarField &X) const
Return vapourisation temperature.
virtual scalar TMax (const scalar p, const scalarField &X) const
Return maximum/limiting temperature.
Public Member Functions inherited from PhaseChangeModel< CloudType >
TypeName ("phaseChangeModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, PhaseChangeModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
PhaseChangeModel (CloudType &owner)
Construct null from owner.
PhaseChangeModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
PhaseChangeModel (const PhaseChangeModel< CloudType > &pcm)
Construct copy.
virtual ~PhaseChangeModel ()
Destructor.
const enthalpyTransferType & enthalpyTransfer () const
Return the enthalpy transfer type enumeration.
void addToPhaseChangeMass (const scalar dMass)
Add to phase change mass.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Member Functions
scalar Sh (const scalar Re, const scalar Sc) const
Sherwood number as a function of Reynolds and Schmidt numbers.
tmp< scalarField > calcXc (const label celli) const
Calculate the carrier phase component volume fractions at celli.
Protected Member Functions inherited from PhaseChangeModel< CloudType >
enthalpyTransferType wordToEnthalpyTransfer (const word &etName) const
Convert word to enthalpy transfer type.
scalar Sh () const
Sherwood number.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
const liquidMixtureProperties & liquids_
Global liquid properties data.
List< word > activeLiquids_
List of active liquid names.
List< label > liqToCarrierMap_
Mapping between liquid and carrier species.
List< label > liqToLiqMap_
Mapping between local and global liquid species.
Protected Attributes inherited from PhaseChangeModel< CloudType >
enthalpyTransferType enthalpyTransfer_
Enthalpy transfer type enumeration.
scalar dMass_
Mass of lagrangian phase converted.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from PhaseChangeModel< CloudType >
enum enthalpyTransferType { etLatentHeat, etEnthalpyDifference }
Enthalpy transfer type.
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from PhaseChangeModel< CloudType >
static autoPtr< PhaseChangeModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Static Public Attributes inherited from PhaseChangeModel< CloudType >
static const Foam::wordList enthalpyTransferTypeNames
Name representations of enthalpy transfer types.
Detailed Description
template<class CloudType>
class Foam::LiquidEvaporation< CloudType >
Liquid evaporation model.
- uses ideal gas assumption
Definition at line 47 of file LiquidEvaporation.H.
Constructor & Destructor Documentation
LiquidEvaporation() [1/2]
LiquidEvaporation (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 68 of file LiquidEvaporation.C.
References Foam::endl(), forAll, Foam::Info, Foam::nl, and WarningInFunction.
Referenced by LiquidEvaporation< CloudType >::Sh().
LiquidEvaporation() [2/2]
LiquidEvaporation (const LiquidEvaporation< CloudType > & pcm)
Construct copy.
Definition at line 110 of file LiquidEvaporation.C.
~LiquidEvaporation()
~LiquidEvaporation () virtual
Destructor.
Definition at line 125 of file LiquidEvaporation.C.
References LiquidEvaporation< CloudType >::calculate().
Referenced by LiquidEvaporation< CloudType >::clone().
Member Function Documentation
Sh()
Foam::scalar Sh (const scalar Re, const scalar Sc) const protected
Sherwood number as a function of Reynolds and Schmidt numbers.
Definition at line 55 of file LiquidEvaporation.C.
References Foam::cbrt(), LiquidEvaporation< CloudType >::LiquidEvaporation(), and Foam::sqrt().
calcXc()
Foam::tmp< Foam::scalarField > calcXc (const label celli) const protected
Calculate the carrier phase component volume fractions at celli.
Definition at line 36 of file LiquidEvaporation.C.
References forAll, PhaseChangeModel< CloudType >::Sh(), Foam::sum(), thermo, and Y.
TypeName()
TypeName ("liquidEvaporation")
Runtime type information.
clone()
virtual autoPtr<PhaseChangeModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements PhaseChangeModel< CloudType >.
Definition at line 92 of file LiquidEvaporation.H.
References LiquidEvaporation< CloudType >::calculate(), LiquidEvaporation< CloudType >::dh(), nu, p, Pr(), Foam::Re(), Foam::T(), LiquidEvaporation< CloudType >::TMax(), LiquidEvaporation< CloudType >::Tvap(), and LiquidEvaporation< CloudType >::~LiquidEvaporation().
calculate()
void calculate (const scalar dt, const label celli, const scalar Re, const scalar Pr, const scalar d, const scalar nu, const scalar T, const scalar Ts, const scalar pc, const scalar Tc, const scalarField & X, scalarField & dMassPC) const virtual
Update model.
Implements PhaseChangeModel< CloudType >.
Definition at line 133 of file LiquidEvaporation.C.
References LiquidEvaporation< CloudType >::dh(), Foam::endl(), forAll, Foam::max(), Foam::constant::mathematical::pi(), Foam::constant::thermodynamic::RR, Sh, Foam::sqr(), Foam::T(), and WarningInFunction.
Referenced by LiquidEvaporation< CloudType >::clone(), and LiquidEvaporation< CloudType >::~LiquidEvaporation().
dh()
Foam::scalar dh (const label idc, const label idl, const scalar p, const scalar T) const virtual
Return the enthalpy per unit mass.
Reimplemented from PhaseChangeModel< CloudType >.
Definition at line 213 of file LiquidEvaporation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, subModelBase::properties(), and LiquidEvaporation< CloudType >::Tvap().
Referenced by LiquidEvaporation< CloudType >::calculate(), and LiquidEvaporation< CloudType >::clone().
Tvap()
Foam::scalar Tvap (const scalarField & X) const virtual
Return vapourisation temperature.
Reimplemented from PhaseChangeModel< CloudType >.
Definition at line 251 of file LiquidEvaporation.C.
References LiquidEvaporation< CloudType >::TMax().
Referenced by LiquidEvaporation< CloudType >::clone(), and LiquidEvaporation< CloudType >::dh().
TMax()
Foam::scalar TMax (const scalar p, const scalarField & X) const virtual
Return maximum/limiting temperature.
Reimplemented from PhaseChangeModel< CloudType >.
Definition at line 261 of file LiquidEvaporation.C.
Referenced by LiquidEvaporation< CloudType >::clone(), and LiquidEvaporation< CloudType >::Tvap().
Member Data Documentation
liquids_
const liquidMixtureProperties& liquids_ protected
Global liquid properties data.
Definition at line 56 of file LiquidEvaporation.H.
activeLiquids_
List<word> activeLiquids_ protected
List of active liquid names.
Definition at line 59 of file LiquidEvaporation.H.
liqToCarrierMap_
List<label> liqToCarrierMap_ protected
Mapping between liquid and carrier species.
Definition at line 62 of file LiquidEvaporation.H.
liqToLiqMap_
List<label> liqToLiqMap_ protected
Mapping between local and global liquid species.
Definition at line 65 of file LiquidEvaporation.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Reacting/PhaseChangeModel/LiquidEvaporation/LiquidEvaporation.H
src/lagrangian/intermediate/submodels/Reacting/PhaseChangeModel/LiquidEvaporation/LiquidEvaporation.C