OpenFOAM: equilibrium Class Reference
equilibrium Class Reference
Equlibrium model for the time scale over which properties of a dispersed phase tend towards the mean value.
Public Member Functions
TypeName ("equilibrium")
Runtime type information.
equilibrium (const dictionary &dict)
Constructors.
equilibrium (const equilibrium &hc)
Construct a copy.
virtual autoPtr< TimeScaleModel > clone () const
Construct and return a clone.
virtual ~equilibrium ()
Destructor.
tmp< FieldField< Field, scalar > > oneByTau (const FieldField< Field, scalar > &alpha, const FieldField< Field, scalar > &r32, const FieldField< Field, scalar > &uSqr, const FieldField< Field, scalar > &f) const
Member Functions.
Public Member Functions inherited from TimeScaleModel
TypeName ("timeScaleModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, TimeScaleModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
TimeScaleModel (const dictionary &dict)
Constructors.
TimeScaleModel (const TimeScaleModel &sm)
Construct a copy.
virtual ~TimeScaleModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from TimeScaleModel
static autoPtr< TimeScaleModel > New (const dictionary &dict)
Selector.
Protected Attributes inherited from TimeScaleModel
scalar alphaPacked_
Close pack volume fraction.
scalar e_
Coefficient of restitution.
Detailed Description
Equlibrium model for the time scale over which properties of a dispersed phase tend towards the mean value.
Reference:
    "A model for collisional exchange in gas/liquid/solid fluidized beds"
    P O'Rourke, P Zhao and D Snider
    Chemical Engineering Science
    Volume 64, Issue 8, Pages 1784-1797, April 2009
Source files
equilibrium.H
equilibrium.C
Definition at line 59 of file equilibrium.H.
Constructor & Destructor Documentation
equilibrium() [1/2]
equilibrium (const dictionary & dict)
Constructors.
Construct from components
Definition at line 50 of file equilibrium.C.
Referenced by equilibrium::clone().
equilibrium() [2/2]
equilibrium (const equilibrium & hc)
Construct a copy.
Definition at line 59 of file equilibrium.C.
~equilibrium()
~equilibrium () virtual
Destructor.
Definition at line 69 of file equilibrium.C.
References equilibrium::oneByTau().
Referenced by equilibrium::clone().
Member Function Documentation
TypeName()
TypeName ("equilibrium")
Runtime type information.
clone()
virtual autoPtr<TimeScaleModel> clone () const inline virtual
Construct and return a clone.
Implements TimeScaleModel.
Definition at line 78 of file equilibrium.H.
References Foam::constant::atomic::alpha, equilibrium::equilibrium(), f(), equilibrium::oneByTau(), and equilibrium::~equilibrium().
oneByTau()
Foam::tmp< Foam::FieldField< Foam::Field, Foam::scalar > > oneByTau (const FieldField< Field, scalar > & alpha, const FieldField< Field, scalar > & r32, const FieldField< Field, scalar > & uSqr, const FieldField< Field, scalar > & f) const virtual
Member Functions.
Time scale
Implements TimeScaleModel.
Definition at line 77 of file equilibrium.C.
References Foam::max(), Foam::constant::mathematical::pi(), and Foam::sqrt().
Referenced by equilibrium::clone(), and equilibrium::~equilibrium().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/equilibrium/equilibrium.H
src/lagrangian/intermediate/submodels/MPPIC/TimeScaleModels/equilibrium/equilibrium.C