OpenFOAM: SuppressionCollision< CloudType > Class Template Reference
SuppressionCollision< CloudType > Class Template Reference
Inter-cloud collision model, whereby the canReact flag can be used to inhibit devolatilisation and surface reactions.
Public Member Functions
TypeName ("suppressionCollision")
Runtime type information.
SuppressionCollision (const dictionary &dict, CloudType &owner)
Construct from dictionary.
SuppressionCollision (const SuppressionCollision< CloudType > &cm)
Construct copy.
virtual autoPtr< StochasticCollisionModel< CloudType > > clone () const
Construct and return a clone.
virtual ~SuppressionCollision ()
Destructor.
Public Member Functions inherited from StochasticCollisionModel< CloudType >
TypeName ("collisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, StochasticCollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
StochasticCollisionModel (CloudType &owner)
Construct null from owner.
StochasticCollisionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
StochasticCollisionModel (const StochasticCollisionModel< CloudType > &cm)
Construct copy.
virtual ~StochasticCollisionModel ()
Destructor.
void update (const scalar dt)
Update the model.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Member Functions
virtual void collide (const scalar dt)
Update the model.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
const word suppressionCloud_
Name of cloud used for suppression.
const label suppressedParcelType_
Suppressed parcel type - optional.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from StochasticCollisionModel< CloudType >
static autoPtr< StochasticCollisionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::SuppressionCollision< CloudType >
Inter-cloud collision model, whereby the canReact flag can be used to inhibit devolatilisation and surface reactions.
Definition at line 46 of file SuppressionCollision.H.
Constructor & Destructor Documentation
SuppressionCollision() [1/2]
SuppressionCollision (const dictionary & dict, CloudType & owner)
Construct from dictionary.
Definition at line 63 of file SuppressionCollision.C.
Referenced by SuppressionCollision< CloudType >::collide().
SuppressionCollision() [2/2]
SuppressionCollision (const SuppressionCollision< CloudType > & cm)
Construct copy.
Definition at line 79 of file SuppressionCollision.C.
~SuppressionCollision()
~SuppressionCollision () virtual
Destructor.
Definition at line 92 of file SuppressionCollision.C.
Referenced by SuppressionCollision< CloudType >::clone().
Member Function Documentation
collide()
void collide (const scalar dt) protected virtual
Update the model.
Implements StochasticCollisionModel< CloudType >.
Definition at line 32 of file SuppressionCollision.C.
References Foam::dimTime, Foam::exp(), forAllIter, Foam::max(), p, SuppressionCollision< CloudType >::SuppressionCollision(), Foam::type(), and kinematicCloud::vDotSweep().
TypeName()
TypeName ("suppressionCollision")
Runtime type information.
clone()
virtual autoPtr<StochasticCollisionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements StochasticCollisionModel< CloudType >.
Definition at line 82 of file SuppressionCollision.H.
References SuppressionCollision< CloudType >::~SuppressionCollision().
Member Data Documentation
suppressionCloud_
const word suppressionCloud_ protected
Name of cloud used for suppression.
Definition at line 55 of file SuppressionCollision.H.
suppressedParcelType_
const label suppressedParcelType_ protected
Suppressed parcel type - optional.
Definition at line 58 of file SuppressionCollision.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/ReactingMultiphase/StochasticCollision/SuppressionCollision/SuppressionCollision.H
src/lagrangian/intermediate/submodels/ReactingMultiphase/StochasticCollision/SuppressionCollision/SuppressionCollision.C