OpenFOAM: correlationFunction< Type > Class Template Reference
correlationFunction< Type > Class Template Reference
Public Types
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from bufferedAccumulator< scalar >
typedef pTraits< scalar >::cmptType cmptType
Component type.
Public Types inherited from List< Field< scalar > >
typedef SubList< Field< scalar > > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
correlationFunction (const polyMesh &, const dictionary &, const label tZeroBufferSize)
Construct from dictionary.
correlationFunction (const polyMesh &, const label tZeroBufferSize, const scalar duration, const scalar sampleInterval, const scalar averagingInterval)
Construct from components.
~correlationFunction ()
Destructor.
void calculateCorrelationFunction (const Field< Type > &)
void calculateCorrelationFunction (const Type &)
scalar integral () const
bool writeAveraged (Ostream &) const
const Field< Field< Type > > & tZeroBuffers () const
scalar duration () const
scalar sampleInterval () const
scalar averagingInterval () const
label sampleSteps () const
label measurandFieldSize () const
Public Member Functions inherited from bufferedAccumulator< scalar >
bufferedAccumulator ()
Construct null.
bufferedAccumulator (const label nBuffers, const label bufferLength, const label bufferingInterval)
Construct from components.
bufferedAccumulator (const bufferedAccumulator< scalar > &)
Construct as copy.
~bufferedAccumulator ()
Destructor.
label addToBuffers (const List< scalar > &valuesToAdd)
Field< scalar > averaged () const
void resetAveraging ()
label averagesTaken () const
label nBuffers () const
label bufferLength () const
const List< label > & bufferOffsets () const
void setSizes (const label nBuffers, const label bufferLength, const label bufferingInterval)
void operator= (const bufferedAccumulator< scalar > &)
Public Member Functions inherited from List< Field< scalar > >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Field< scalar > &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Field< scalar > > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< Field< scalar > >> &)
Construct by transferring the parameter contents.
List (List< Field< scalar > > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Field< scalar > > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Field< scalar >, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Field< scalar > > &)
Construct as copy of PtrList<T>
List (const SLList< Field< scalar > > &)
Construct as copy of SLList<T>
List (const UIndirectList< Field< scalar > > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Field< scalar > > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< Field< scalar > >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< Field< scalar > > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Field< scalar > &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Field< scalar > &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Field< scalar > &)
Append an element at the end of the list.
void append (const UList< Field< scalar > > &)
Append a List at the end of this list.
void append (const UIndirectList< Field< scalar > > &)
Append a UIndirectList at the end of this list.
void transfer (List< Field< scalar > > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Field< scalar >, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Field< scalar > > &)
Transfer the contents of the argument List into this list.
Xfer< List< Field< scalar > > > xfer ()
Transfer contents to the Xfer container.
Field< scalar > & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Field< scalar > > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Field< scalar > > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< Field< scalar > > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Field< scalar > > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< Field< scalar > > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Field< scalar > > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< Field< scalar > >)
Assignment to an initializer list.
void operator= (const Field< scalar > &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Attributes
static const char *const typeName
Static Public Attributes inherited from bufferedAccumulator< scalar >
static const char *const typeName
Friends
Ostream & operator (Ostream &, const correlationFunction< Type > &)
Additional Inherited Members
Static Public Member Functions inherited from List< Field< scalar > >
static const List< Field< scalar > > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< Field< scalar > >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::correlationFunction< Type >
Source files
correlationFunction.H
correlationFunctionI.H
correlationFunction.C
correlationFunctionIO.C
Definition at line 47 of file correlationFunction.H.
Member Typedef Documentation
cmptType
typedef pTraits<Type>::cmptType cmptType
Component type.
Definition at line 92 of file correlationFunction.H.
Constructor & Destructor Documentation
correlationFunction() [1/2]
correlationFunction (const polyMesh & mesh, const dictionary & cfDict, const label tZeroBufferSize)
Construct from dictionary.
Definition at line 81 of file correlationFunction.C.
References dictionary::lookup(), and readScalar.
correlationFunction() [2/2]
correlationFunction (const polyMesh & mesh, const label tZeroBufferSize, const scalar duration, const scalar sampleInterval, const scalar averagingInterval)
Construct from components.
Definition at line 102 of file correlationFunction.C.
~correlationFunction()
~correlationFunction ()
Destructor.
Definition at line 123 of file correlationFunction.C.
References correlationFunction< Type >::calculateCorrelationFunction().
Member Function Documentation
calculateCorrelationFunction() [1/2]
void calculateCorrelationFunction (const Field< Type > & currentValues)
Definition at line 131 of file correlationFunction.C.
References Foam::abort(), Foam::component(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, and List< Type >::size().
Referenced by correlationFunction< Type >::~correlationFunction().
calculateCorrelationFunction() [2/2]
void calculateCorrelationFunction (const Type & currentValue)
Definition at line 183 of file correlationFunction.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
integral()
Foam::scalar integral () const
Definition at line 201 of file correlationFunction.C.
References List< T >::size().
writeAveraged()
bool writeAveraged (Ostream & os) const
Definition at line 30 of file correlationFunctionIO.C.
References forAll, IOstream::good(), and Foam::nl.
tZeroBuffers()
const Foam::Field< Foam::Field< Type > > & tZeroBuffers () const inline
Definition at line 28 of file correlationFunctionI.H.
duration()
Foam::scalar duration () const inline
Definition at line 35 of file correlationFunctionI.H.
sampleInterval()
Foam::scalar sampleInterval () const inline
Definition at line 42 of file correlationFunctionI.H.
averagingInterval()
Foam::scalar averagingInterval () const inline
Definition at line 49 of file correlationFunctionI.H.
sampleSteps()
Foam::label sampleSteps () const inline
Definition at line 56 of file correlationFunctionI.H.
measurandFieldSize()
Foam::label measurandFieldSize () const inline
Definition at line 63 of file correlationFunctionI.H.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const correlationFunction< Type > &) friend
Member Data Documentation
typeName
const char *const typeName static
Definition at line 97 of file correlationFunction.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecularMeasurements/correlationFunction/correlationFunction.H
src/lagrangian/molecularDynamics/molecularMeasurements/correlationFunction/correlationFunction.C
src/lagrangian/molecularDynamics/molecularMeasurements/correlationFunction/correlationFunctionI.H
src/lagrangian/molecularDynamics/molecularMeasurements/correlationFunction/correlationFunctionIO.C