OpenFOAM: distribution Class Reference
distribution Class Reference
Accumulating histogram of values. Specified bin resolution automatic generation of bins.
Public Member Functions
TypeName ("distribution")
Runtime type information.
distribution ()
Construct null.
distribution (const scalar binWidth)
Construct from binWidth.
distribution (const distribution &)
Construct as copy.
virtual ~distribution ()
Destructor.
label totalEntries () const
scalar approxTotalEntries () const
scalar mean () const
scalar median ()
void add (const scalar valueToAdd)
Add a value to the appropriate bin of the distribution.
void add (const label valueToAdd)
void insertMissingKeys ()
List< Pair< scalar > > normalised ()
List< Pair< scalar > > normalisedMinusMean ()
List< Pair< scalar > > normalisedShifted (scalar shiftValue)
List< Pair< scalar > > raw ()
scalar binWidth () const
void operator= (const distribution &)
Public Member Functions inherited from Map< label >
Map (const label size=128)
Construct given initial size.
Map (Istream &is)
Construct from Istream.
Map (const Map< label > &map)
Construct as copy.
Map (const Xfer< Map< label >> &map)
Construct by transferring the parameter contents.
Map (const Xfer< HashTable< label, label, Hash< label >>> &map)
Construct by transferring the parameter contents.
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< T, Key, Hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< T, Key, Hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< Key, T >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const Key &) const
Return true if hashedEntry is found in table.
iterator find (const Key &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const Key &) const
Find and return an const_iterator set at the hashedEntry.
List< Key > toc () const
Return the table of contents.
List< Key > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const Key &, const T &newElmt)
Insert a new hashedEntry.
bool set (const Key &, const T &newElmt)
Assign a new hashedEntry, overwriting existing entries.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const Key &)
Erase a hashedEntry specified by the given key.
label erase (const UList< Key > &)
Remove entries given by the listed keys from this HashTable.
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< T, Key, Hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< T, Key, Hash > > xfer ()
Transfer contents to the Xfer container.
T & operator[] (const Key &)
Find and return a hashedEntry.
const T & operator[] (const Key &) const
Find and return a hashedEntry.
T & operator() (const Key &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< T, Key, Hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< Key, T >>)
Assignment to an initializer list.
bool operator== (const HashTable< T, Key, Hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< T, Key, Hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &rhs)
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Static Public Member Functions
static void write (const fileName &file, const List< Pair< scalar >> &pairs)
Write to file.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Friends
Ostream & operator<< (Ostream &, const distribution &)
Additional Inherited Members
Public Types inherited from Map< label >
typedef HashTable< label, label, Hash< label > >::iterator iterator
typedef HashTable< label, label, Hash< label > >::const_iterator const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef T value_type
Type of values the HashTable contains.
typedef T & reference
Type that can be used for storing into HashTable::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Detailed Description
Accumulating histogram of values. Specified bin resolution automatic generation of bins.
Source files
distribution.H
distributionI.H
distribution.C
Definition at line 58 of file distribution.H.
Constructor & Destructor Documentation
distribution() [1/3]
distribution ()
Construct null.
Definition at line 55 of file distribution.C.
distribution() [2/3]
distribution (const scalar binWidth)
Construct from binWidth.
Definition at line 62 of file distribution.C.
distribution() [3/3]
distribution (const distribution & d)
Construct as copy.
Definition at line 69 of file distribution.C.
~distribution()
~distribution () virtual
Destructor.
Definition at line 78 of file distribution.C.
Member Function Documentation
TypeName()
TypeName ("distribution")
Runtime type information.
write()
void write (const fileName & file, const List< Pair< scalar >> & pairs) static
Write to file.
Definition at line 39 of file distribution.C.
References forAll, and Foam::nl.
totalEntries()
Foam::label totalEntries () const
Definition at line 84 of file distribution.C.
References Foam::endl(), forAllConstIter(), and WarningInFunction.
approxTotalEntries()
Foam::scalar approxTotalEntries () const
Definition at line 112 of file distribution.C.
References forAllConstIter().
Referenced by distribution::mean(), and distribution::normalised().
mean()
Foam::scalar mean () const
Definition at line 125 of file distribution.C.
References distribution::approxTotalEntries(), forAll, k, and HashTable< T, Key, Hash >::toc().
Referenced by distribution::normalisedMinusMean().
median()
Foam::scalar median ()
Definition at line 148 of file distribution.C.
References UList< T >::first(), forAll, distribution::normalised(), and List< T >::size().
add() [1/2]
void add (const scalar valueToAdd)
Add a value to the appropriate bin of the distribution.
Definition at line 212 of file distribution.C.
References Foam::abort(), HashTable< T, Key, Hash >::begin(), HashTableCore::end(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), HashTable< T, Key, Hash >::insert(), n, and Foam::neg().
Referenced by distribution::add().
add() [2/2]
void add (const label valueToAdd)
Definition at line 242 of file distribution.C.
References distribution::add().
insertMissingKeys()
void insertMissingKeys ()
Definition at line 248 of file distribution.C.
References HashTable< T, Key, Hash >::begin(), HashTableCore::end(), HashTable< T, Key, Hash >::find(), HashTable< T, Key, Hash >::insert(), k, UList< T >::last(), List< T >::size(), Foam::sort(), and HashTable< T, Key, Hash >::toc().
Referenced by distribution::normalised(), and distribution::raw().
normalised()
Foam::List< Foam::Pair< Foam::scalar > > normalised ()
Definition at line 271 of file distribution.C.
References distribution::approxTotalEntries(), Foam::endl(), UList< T >::first(), forAll, Foam::Info, distribution::insertMissingKeys(), k, HashTable< T, Key, Hash >::size(), Foam::sort(), and HashTable< T, Key, Hash >::toc().
Referenced by distribution::median(), and distribution::normalisedShifted().
normalisedMinusMean()
Foam::List< Foam::Pair< Foam::scalar > > normalisedMinusMean ()
Definition at line 301 of file distribution.C.
References distribution::mean(), and distribution::normalisedShifted().
normalisedShifted()
Foam::List< Foam::Pair< Foam::scalar > > normalisedShifted (scalar shiftValue)
Definition at line 308 of file distribution.C.
References Foam::endl(), UList< T >::first(), forAll, Foam::Info, Foam::nl, distribution::normalised(), Foam::sign(), and List< T >::size().
Referenced by distribution::normalisedMinusMean().
raw()
Foam::List< Foam::Pair< Foam::scalar > > raw ()
Definition at line 419 of file distribution.C.
References UList< T >::first(), forAll, distribution::insertMissingKeys(), k, HashTable< T, Key, Hash >::size(), Foam::sort(), and HashTable< T, Key, Hash >::toc().
binWidth()
Foam::scalar binWidth () const inline
Definition at line 28 of file distributionI.H.
Referenced by distribution::operator=().
operator=()
void operator= (const distribution & rhs)
Definition at line 444 of file distribution.C.
References Foam::abort(), distribution::binWidth(), Foam::FatalError, FatalErrorInFunction, and HashTable< T, label, Hash< label > >::operator=().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const distribution &) friend
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecularMeasurements/distribution/distribution.H
src/lagrangian/molecularDynamics/molecularMeasurements/distribution/distribution.C
src/lagrangian/molecularDynamics/molecularMeasurements/distribution/distributionI.H