OpenFOAM: reducedUnits Class Reference
reducedUnits Class Reference
Public Member Functions
reducedUnits ()
Construct with no argument, uses default values:
reducedUnits (scalar refLength, scalar refTime, scalar refMass)
Construct from components.
reducedUnits (const IOdictionary &reducedUnitsDict)
Construct from dictionary.
~reducedUnits ()
Destructor.
void setRefValues (scalar refLength, scalar refTime, scalar refMass)
void setRefValues (const IOdictionary &reducedUnitsDict)
scalar refLength () const
scalar refTime () const
scalar refMass () const
scalar refTemp () const
scalar refEnergy () const
scalar refForce () const
scalar refVelocity () const
scalar refVolume () const
scalar refPressure () const
scalar refMassDensity () const
scalar refNumberDensity () const
Static Public Attributes
static const scalar kb = 1.3806504e-23
Static data someStaticData.
Friends
Ostream & operator<< (Ostream &, const reducedUnits &)
Detailed Description
Source files
reducedUnits.H
reducedUnitsI.H
reducedUnits.C
reducedUnitsIO.C
Definition at line 57 of file reducedUnits.H.
Constructor & Destructor Documentation
reducedUnits() [1/3]
reducedUnits ()
Construct with no argument, uses default values:
length = 1nm mass = 1.660538782e-27kg (unified atomic mass unit) temperature = 1K (therefore, energy = 1*kb)
Definition at line 73 of file reducedUnits.C.
reducedUnits() [2/3]
reducedUnits (scalar refLength, scalar refTime, scalar refMass)
Construct from components.
Definition at line 84 of file reducedUnits.C.
reducedUnits() [3/3]
reducedUnits (const IOdictionary & reducedUnitsDict)
Construct from dictionary.
Definition at line 98 of file reducedUnits.C.
References reducedUnits::setRefValues().
~reducedUnits()
~reducedUnits ()
Destructor.
Definition at line 110 of file reducedUnits.C.
References reducedUnits::setRefValues().
Member Function Documentation
setRefValues() [1/2]
void setRefValues (scalar refLength, scalar refTime, scalar refMass)
Definition at line 117 of file reducedUnits.C.
References reducedUnits::refLength(), reducedUnits::refMass(), and reducedUnits::refTime().
Referenced by reducedUnits::reducedUnits(), and reducedUnits::~reducedUnits().
setRefValues() [2/2]
void setRefValues (const IOdictionary & reducedUnitsDict)
Definition at line 134 of file reducedUnits.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), and Foam::readScalar().
refLength()
Foam::scalar refLength () const inline
Definition at line 28 of file reducedUnitsI.H.
Referenced by Foam::operator<<(), and reducedUnits::setRefValues().
refTime()
Foam::scalar refTime () const inline
Definition at line 34 of file reducedUnitsI.H.
Referenced by Foam::operator<<(), and reducedUnits::setRefValues().
refMass()
Foam::scalar refMass () const inline
Definition at line 40 of file reducedUnitsI.H.
Referenced by Foam::operator<<(), and reducedUnits::setRefValues().
refTemp()
Foam::scalar refTemp () const inline
Definition at line 46 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
refEnergy()
Foam::scalar refEnergy () const inline
Definition at line 52 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
refForce()
Foam::scalar refForce () const inline
Definition at line 58 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
refVelocity()
Foam::scalar refVelocity () const inline
Definition at line 64 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
refVolume()
Foam::scalar refVolume () const inline
Definition at line 70 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
refPressure()
Foam::scalar refPressure () const inline
Definition at line 76 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
refMassDensity()
Foam::scalar refMassDensity () const inline
Definition at line 82 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
refNumberDensity()
Foam::scalar refNumberDensity () const inline
Definition at line 88 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const reducedUnits &) friend
Member Data Documentation
kb
const Foam::scalar kb = 1.3806504e-23 static
Static data someStaticData.
Definition at line 106 of file reducedUnits.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecule/reducedUnits/reducedUnits.H
src/lagrangian/molecularDynamics/molecule/reducedUnits/reducedUnits.C
src/lagrangian/molecularDynamics/molecule/reducedUnits/reducedUnitsI.H