OpenFOAM: lennardJones Class Reference
lennardJones Class Reference
Public Member Functions
TypeName ("lennardJones")
Runtime type information.
lennardJones (const word &name, const dictionary &pairPotentialProperties)
Construct from components.
~lennardJones ()
Destructor.
scalar unscaledEnergy (const scalar r) const
bool read (const dictionary &pairPotentialProperties)
Read dictionary.
Public Member Functions inherited from pairPotential
TypeName ("pairPotential")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pairPotential, dictionary,(const word &name, const dictionary &pairPotentialProperties),(name, pairPotentialProperties))
pairPotential (const word &name, const dictionary &pairPotentialProperties)
Construct from components.
virtual ~pairPotential ()
Destructor.
void setLookupTables ()
scalar rMin () const
scalar dr () const
scalar rCut () const
scalar rCutSqr () const
scalar energy (const scalar r) const
scalar force (const scalar r) const
List< Pair< scalar > > energyTable () const
List< Pair< scalar > > forceTable () const
bool writeTables () const
scalar scaledEnergy (const scalar r) const
scalar energyDerivative (const scalar r, const bool scaledEnergyDerivative=true) const
const dictionary & pairPotentialProperties () const
bool writeEnergyAndForceTables (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from pairPotential
static autoPtr< pairPotential > New (const word &name, const dictionary &pairPotentialProperties)
Return a reference to the selected viscosity model.
Protected Member Functions inherited from pairPotential
void scaleEnergy (scalar &e, const scalar r) const
pairPotential (const pairPotential &)
Disallow copy construct.
void operator= (const pairPotential &)
Disallow default bitwise assignment.
Protected Attributes inherited from pairPotential
word name_
dictionary pairPotentialProperties_
scalar rCut_
scalar rCutSqr_
scalar rMin_
scalar dr_
List< scalar > forceLookup_
List< scalar > energyLookup_
energyScalingFunction * esfPtr_
bool writeTables_
Detailed Description
Source files
lennardJones.H
lennardJones.C
Definition at line 50 of file lennardJones.H.
Constructor & Destructor Documentation
lennardJones()
lennardJones (const word & name, const dictionary & pairPotentialProperties)
Construct from components.
Definition at line 51 of file lennardJones.C.
~lennardJones()
~lennardJones () inline
Destructor.
Definition at line 79 of file lennardJones.H.
References lennardJones::read(), and lennardJones::unscaledEnergy().
Member Function Documentation
TypeName()
TypeName ("lennardJones")
Runtime type information.
unscaledEnergy()
scalar unscaledEnergy (const scalar r) const virtual
Implements pairPotential.
Definition at line 67 of file lennardJones.C.
Referenced by lennardJones::~lennardJones().
read()
bool read (const dictionary & pairPotentialProperties) virtual
Read dictionary.
Implements pairPotential.
Definition at line 79 of file lennardJones.C.
References dictionary::lookup(), pairPotential::read(), and dictionary::subDict().
Referenced by lennardJones::~lennardJones().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/pairPotential/derived/lennardJones/lennardJones.H
src/lagrangian/molecularDynamics/potential/pairPotential/derived/lennardJones/lennardJones.C