OpenFOAM: noScaling Class Reference
noScaling Class Reference
Public Member Functions
TypeName ("noScaling")
Runtime type information.
noScaling (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Construct from components.
~noScaling ()
Destructor.
void scaleEnergy (scalar &e, const scalar r) const
bool read (const dictionary &energyScalingFunctionProperties)
Read dictionary.
Public Member Functions inherited from energyScalingFunction
TypeName ("energyScalingFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, energyScalingFunction, dictionary,(const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot),(name, energyScalingFunctionProperties, pairPot))
energyScalingFunction (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Construct from components.
virtual ~energyScalingFunction ()
Destructor.
const dictionary & energyScalingFunctionProperties () const
Additional Inherited Members
Static Public Member Functions inherited from energyScalingFunction
static autoPtr< energyScalingFunction > New (const word &name, const dictionary &energyScalingFunctionProperties, const pairPotential &pairPot)
Return a reference to the selected viscosity model.
Protected Member Functions inherited from energyScalingFunction
energyScalingFunction (const energyScalingFunction &)
Disallow copy construct.
void operator= (const energyScalingFunction &)
Disallow default bitwise assignment.
Protected Attributes inherited from energyScalingFunction
word name_
dictionary energyScalingFunctionProperties_
const pairPotential & pairPot_
Detailed Description
Source files
noScaling.H
noScaling.C
Definition at line 50 of file noScaling.H.
Constructor & Destructor Documentation
noScaling()
noScaling (const word & name, const dictionary & energyScalingFunctionProperties, const pairPotential & pairPot)
Construct from components.
Definition at line 51 of file noScaling.C.
~noScaling()
~noScaling () inline
Destructor.
Definition at line 73 of file noScaling.H.
References Foam::e, noScaling::read(), and noScaling::scaleEnergy().
Member Function Documentation
TypeName()
TypeName ("noScaling")
Runtime type information.
scaleEnergy()
void scaleEnergy (scalar & e, const scalar r) const virtual
Implements energyScalingFunction.
Definition at line 63 of file noScaling.C.
Referenced by noScaling::~noScaling().
read()
bool read (const dictionary & energyScalingFunctionProperties) virtual
Read dictionary.
Implements energyScalingFunction.
Definition at line 67 of file noScaling.C.
References energyScalingFunction::read().
Referenced by noScaling::~noScaling().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/energyScalingFunction/derived/noScaling/noScaling.H
src/lagrangian/molecularDynamics/potential/energyScalingFunction/derived/noScaling/noScaling.C