OpenFOAM: molecule::iNew Class Reference
molecule::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< molecule > operator() (Istream &is) const
Detailed Description
Factory class to read-construct particles used for.
parallel transfer
Definition at line 272 of file molecule.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 278 of file molecule.H.
Member Function Documentation
operator()()
autoPtr<molecule> operator() (Istream & is) const inline
Definition at line 283 of file molecule.H.
References molecule::a(), molecule::hitPatch(), molecule::hitProcessorPatch(), molecule::hitWallPatch(), molecule::id(), molecule::molecule(), molecule::move(), molecule::operator<<, patchi, molecule::pi(), molecule::potentialEnergy(), molecule::Q(), molecule::readFields(), molecule::rf(), molecule::setSitePositions(), molecule::setSiteSizes(), molecule::siteForces(), molecule::sitePositions(), molecule::special(), molecule::specialPosition(), Foam::T(), molecule::tau(), molecule::tethered(), molecule::transformProperties(), molecule::v(), and molecule::writeFields().
The documentation for this class was generated from the following file:
src/lagrangian/molecularDynamics/molecule/molecule/molecule.H