OpenFOAM: moleculeCloud Class Reference
moleculeCloud Class Reference
Public Member Functions
moleculeCloud (const polyMesh &mesh, const potential &pot, bool readFields=true)
Construct given mesh and potential references.
moleculeCloud (const polyMesh &mesh, const potential &pot, const IOdictionary &mdInitialiseDict, bool readFields=true)
Construct given mesh, potential and mdInitialiseDict.
void evolve ()
Evolve the molecules (move, calculate forces, control state etc)
void calculateForce ()
void applyConstraintsAndThermostats (const scalar targetTemperature, const scalar measuredTemperature)
const polyMesh & mesh () const
const potential & pot () const
const List< DynamicList< molecule * > > & cellOccupancy () const
const InteractionLists< molecule > & il () const
const List< molecule::constantProperties > constProps () const
const molecule::constantProperties & constProps (label id) const
Random & rndGen ()
void writeXYZ (const fileName &fName) const
Write molecule sites in XYZ format.
Public Member Functions inherited from Cloud< ParticleType >
TypeName ("Cloud")
Runtime type information.
Cloud (const polyMesh &mesh, const word &cloudName, const IDLList< ParticleType > &particles)
Construct from mesh and a list of particles.
Cloud (const polyMesh &pMesh, const word &cloudName, const bool checkClass=true)
Construct from mesh by reading from file with given cloud instance.
const polyMesh & pMesh () const
Return the polyMesh reference.
label size () const
DynamicList< label > & labels ()
label nTrackingRescues () const
Return nTrackingRescues.
void trackingRescue () const
Increment the nTrackingRescues counter.
const PackedBoolList & cellHasWallFaces () const
Whether each cell has any wall faces (demand driven data)
bool hasWallImpactDistance () const
Switch to specify if particles of the cloud can return.
const const_iterator begin () const
const const_iterator cbegin () const
const const_iterator end () const
const const_iterator cend () const
iterator begin ()
iterator end ()
void clear ()
void addParticle (ParticleType *pPtr)
Transfer particle to cloud.
void deleteParticle (ParticleType &)
Remove particle from cloud and delete.
void deleteLostParticles ()
Remove lost particles from cloud and delete.
void cloudReset (const Cloud< ParticleType > &c)
Reset the particles.
template<class TrackData >
void move (TrackData &td, const scalar trackTime)
Move the particles.
template<class TrackData >
void autoMap (TrackData &td, const mapPolyMesh &)
Remap the cells of particles corresponding to the.
IOobject fieldIOobject (const word &fieldName, const IOobject::readOption r) const
Helper to construct IOobject for field and current time.
template<class DataType >
void checkFieldIOobject (const Cloud< ParticleType > &c, const IOField< DataType > &data) const
Check lagrangian data field.
template<class DataType >
void checkFieldFieldIOobject (const Cloud< ParticleType > &c, const CompactIOField< Field< DataType >, DataType > &data) const
Check lagrangian data fieldfield.
virtual void writeFields () const
Write the field data for the cloud of particles Dummy at.
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write using given format, version and compression.
void writePositions () const
Write positions to <cloudName>_positions.obj file.
Public Member Functions inherited from cloud
TypeName ("cloud")
Runtime type information.
cloud (const objectRegistry &, const word &cloudName=defaultName)
Construct for the given objectRegistry and named cloud instance.
virtual ~cloud ()
Destructor.
virtual void autoMap (const mapPolyMesh &)
Remap the cells of particles corresponding to the.
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject *>
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< word, regIOobject * >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Foam::label erase (const HashTable< AnyType, word, AnyHash > &rhs)
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< word, regIOobject * >>)
Assignment to an initializer list.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from ILList< LListBase, T >
ILList ()
Null construct.
ILList (T *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< LListBase, T > &)
Construct as copy.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
template<class INew >
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< LListBase, T > &)
Assignment operator.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()
Null construct.
UILList (T *a)
Construct given initial T.
UILList (const UILList< LListBase, T > &)
Construct as copy.
T * first ()
Return the first entry.
const T * first () const
Return the first entry.
T * last ()
Return the last entry.
const T * last () const
Return the last entry.
T * removeHead ()
Remove and return head.
T * remove (T *p)
Remove and return element.
T * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< LListBase, T > &)
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< LListBase, T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< LListBase, T > &) const
The opposite of the equality operation. Takes linear time.
Additional Inherited Members
Public Types inherited from Cloud< ParticleType >
typedef ParticleType particleType
typedef IDLList< ParticleType >::iterator iterator
typedef IDLList< ParticleType >::const_iterator const_iterator
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject *>
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values the DLList contains.
typedef T & reference
Type that can be used for storing into DLList::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from Cloud< ParticleType >
static word cloudPropertiesName
Name of cloud properties dictionary.
Static Public Attributes inherited from cloud
static const word prefix
The prefix to local: lagrangian.
static word defaultName
The default cloud name: defaultCloud.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Source files
moleculeCloud.H
moleculeCloudI.H
moleculeCloud.C
Definition at line 56 of file moleculeCloud.H.
Constructor & Destructor Documentation
moleculeCloud() [1/2]
moleculeCloud (const polyMesh & mesh, const potential & pot, bool readFields = true)
Construct given mesh and potential references.
Definition at line 1103 of file moleculeCloud.C.
References molecule::readFields().
moleculeCloud() [2/2]
moleculeCloud (const polyMesh & mesh, const potential & pot, const IOdictionary & mdInitialiseDict, bool readFields = true)
Construct given mesh, potential and mdInitialiseDict.
Definition at line 1133 of file moleculeCloud.C.
References clear(), and molecule::readFields().
Member Function Documentation
evolve()
void evolve ()
Evolve the molecules (move, calculate forces, control state etc)
Definition at line 1162 of file moleculeCloud.C.
References Cloud< ParticleType >::move(), and objectRegistry::time().
calculateForce()
void calculateForce ()
Definition at line 1180 of file moleculeCloud.C.
References moleculeCloud::applyConstraintsAndThermostats(), forAllIter, and Foam::Zero.
applyConstraintsAndThermostats()
void applyConstraintsAndThermostats (const scalar targetTemperature, const scalar measuredTemperature)
Definition at line 1203 of file moleculeCloud.C.
References Foam::endl(), forAllIter, Foam::Info, Foam::max(), and Foam::sqrt().
Referenced by moleculeCloud::calculateForce().
mesh()
const Foam::polyMesh & mesh () const inline
Definition at line 344 of file moleculeCloudI.H.
Referenced by molecule::writeFields().
pot()
const Foam::potential & pot () const inline
Definition at line 350 of file moleculeCloudI.H.
cellOccupancy()
const Foam::List< Foam::DynamicList< Foam::molecule * > > & cellOccupancy () const inline
Definition at line 357 of file moleculeCloudI.H.
il()
const Foam::InteractionLists< Foam::molecule > & il () const inline
Definition at line 364 of file moleculeCloudI.H.
constProps() [1/2]
const Foam::List< Foam::molecule::constantProperties > constProps () const inline
Definition at line 371 of file moleculeCloudI.H.
Referenced by molecule::move().
constProps() [2/2]
const Foam::molecule::constantProperties & constProps (label id) const inline
Definition at line 378 of file moleculeCloudI.H.
rndGen()
Foam::Random & rndGen () inline
Definition at line 384 of file moleculeCloudI.H.
writeXYZ()
void writeXYZ (const fileName & fName) const
Write molecule sites in XYZ format.
Definition at line 1231 of file moleculeCloud.C.
References forAll, forAllConstIter(), Foam::nl, molecule::constantProperties::siteIds(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by molecule::writeFields().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecule/moleculeCloud/moleculeCloud.H
src/lagrangian/molecularDynamics/molecule/moleculeCloud/moleculeCloud.C
src/lagrangian/molecularDynamics/molecule/moleculeCloud/moleculeCloudI.H