OpenFOAM: harmonicSpring Class Reference
harmonicSpring Class Reference
Public Member Functions
TypeName ("harmonicSpring")
Runtime type information.
harmonicSpring (const word &name, const dictionary &tetherPotentialProperties)
Construct from components.
~harmonicSpring ()
Destructor.
scalar energy (const vector r) const
vector force (const vector r) const
bool read (const dictionary &tetherPotentialProperties)
Read dictionary.
Public Member Functions inherited from tetherPotential
TypeName ("tetherPotential")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, tetherPotential, dictionary,(const word &name, const dictionary &tetherPotentialProperties),(name, tetherPotentialProperties))
tetherPotential (const word &name, const dictionary &tetherPotentialProperties)
Construct from components.
virtual ~tetherPotential ()
Destructor.
const dictionary & tetherPotentialProperties () const
Additional Inherited Members
Static Public Member Functions inherited from tetherPotential
static autoPtr< tetherPotential > New (const word &name, const dictionary &tetherPotentialProperties)
Return a reference to the selected viscosity model.
Protected Member Functions inherited from tetherPotential
tetherPotential (const tetherPotential &)
Disallow copy construct.
void operator= (const tetherPotential &)
Disallow default bitwise assignment.
Protected Attributes inherited from tetherPotential
word name_
dictionary tetherPotentialProperties_
Detailed Description
Source files
harmonicSpring.H
harmonicSpring.C
Definition at line 50 of file harmonicSpring.H.
Constructor & Destructor Documentation
harmonicSpring()
harmonicSpring (const word & name, const dictionary & tetherPotentialProperties)
Construct from components.
Definition at line 51 of file harmonicSpring.C.
~harmonicSpring()
~harmonicSpring () inline
Destructor.
Definition at line 78 of file harmonicSpring.H.
References harmonicSpring::energy(), harmonicSpring::force(), and harmonicSpring::read().
Member Function Documentation
TypeName()
TypeName ("harmonicSpring")
Runtime type information.
energy()
scalar energy (const vector r) const virtual
Implements tetherPotential.
Definition at line 67 of file harmonicSpring.C.
References Foam::magSqr().
Referenced by harmonicSpring::~harmonicSpring().
force()
vector force (const vector r) const virtual
Implements tetherPotential.
Definition at line 73 of file harmonicSpring.C.
Referenced by harmonicSpring::~harmonicSpring().
read()
bool read (const dictionary & tetherPotentialProperties) virtual
Read dictionary.
Implements tetherPotential.
Definition at line 79 of file harmonicSpring.C.
References dictionary::lookup(), tetherPotential::read(), and dictionary::subDict().
Referenced by harmonicSpring::~harmonicSpring().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/tetherPotential/derived/harmonicSpring/harmonicSpring.H
src/lagrangian/molecularDynamics/potential/tetherPotential/derived/harmonicSpring/harmonicSpring.C