OpenFOAM: SprayParcel< ParcelType >::constantProperties Class Reference
SprayParcel< ParcelType >::constantProperties Class Reference
Class to hold reacting particle constant properties.
Public Member Functions
constantProperties ()
Null constructor.
constantProperties (const constantProperties &cp)
Copy constructor.
constantProperties (const dictionary &parentDict)
Construct from dictionary.
constantProperties (const label parcelTypeId, const scalar rhoMin, const scalar rho0, const scalar minParcelMass, const scalar youngsModulus, const scalar poissonsRatio, const scalar T0, const scalar TMin, const scalar TMax, const scalar Cp0, const scalar epsilon0, const scalar f0, const scalar Pr, const scalar pMin, const Switch &constantVolume, const scalar sigma0, const scalar mu0)
Construct from components.
scalar sigma0 () const
Return const access to the initial surface tension.
scalar mu0 () const
Return const access to the initial dynamic viscosity.
Detailed Description
template<class ParcelType>
class Foam::SprayParcel< ParcelType >::constantProperties
Class to hold reacting particle constant properties.
Definition at line 70 of file SprayParcel.H.
Constructor & Destructor Documentation
constantProperties() [1/4]
constantProperties () inline
Null constructor.
Definition at line 29 of file SprayParcelI.H.
Referenced by SprayParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [2/4]
constantProperties (const constantProperties & cp) inline
Copy constructor.
Definition at line 39 of file SprayParcelI.H.
References SprayParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [3/4]
constantProperties (const dictionary & parentDict) inline
Construct from dictionary.
Definition at line 51 of file SprayParcelI.H.
References SprayParcel< ParcelType >::constantProperties::constantProperties().
constantProperties() [4/4]
constantProperties (const label parcelTypeId, const scalar rhoMin, const scalar rho0, const scalar minParcelMass, const scalar youngsModulus, const scalar poissonsRatio, const scalar T0, const scalar TMin, const scalar TMax, const scalar Cp0, const scalar epsilon0, const scalar f0, const scalar Pr, const scalar pMin, const Switch & constantVolume, const scalar sigma0, const scalar mu0) inline
Construct from components.
Definition at line 63 of file SprayParcelI.H.
References SprayParcel< ParcelType >::SprayParcel().
Member Function Documentation
sigma0()
Foam::scalar sigma0 () const inline
Return const access to the initial surface tension.
Definition at line 200 of file SprayParcelI.H.
References demandDrivenEntry< Type >::value().
mu0()
Foam::scalar mu0 () const inline
Return const access to the initial dynamic viscosity.
Definition at line 208 of file SprayParcelI.H.
References demandDrivenEntry< Type >::value().
The documentation for this class was generated from the following files:
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcel.H
src/lagrangian/spray/parcels/Templates/SprayParcel/SprayParcelI.H