OpenFOAM: BlobsSheetAtomization< CloudType > Class Template Reference
BlobsSheetAtomization< CloudType > Class Template Reference
Primary Breakup Model for pressure swirl atomizers.
Public Member Functions
TypeName ("blobsSheetAtomization")
Runtime type information.
BlobsSheetAtomization (const dictionary &dict, CloudType &cloud)
Construct from dictionary.
BlobsSheetAtomization (const BlobsSheetAtomization< CloudType > &am)
Construct copy.
virtual autoPtr< AtomizationModel< CloudType > > clone () const
Construct and return a clone.
virtual ~BlobsSheetAtomization ()
Destructor.
virtual scalar initLiquidCore () const
Initial value of liquidCore.
virtual bool calcChi () const
Flag to indicate if chi needs to be calculated.
virtual void update (const scalar dt, scalar &d, scalar &liquidCore, scalar &tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector &pos, const vector &injectionPos, const scalar pAmbient, const scalar chi, cachedRandom &rndGen) const
Public Member Functions inherited from AtomizationModel< CloudType >
TypeName ("atomizationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AtomizationModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
AtomizationModel (CloudType &owner)
Construct null from owner.
AtomizationModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
AtomizationModel (const AtomizationModel< CloudType > &am)
Construct copy.
virtual ~AtomizationModel ()
Destructor.
scalar Taverage (const scalar &Tliq, const scalar &Tc) const
Average temperature calculation.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from AtomizationModel< CloudType >
static autoPtr< AtomizationModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::BlobsSheetAtomization< CloudType >
Primary Breakup Model for pressure swirl atomizers.
Accurate description in
Z. Han, S. Parrish, P.V. Farrell, R.D. Reitz
"Modeling Atomization Processes Of Pressure Swirl Hollow-Cone Fuel Sprays"
Atomization and Sprays, vol. 7, pp. 663-684, 1997
and
L. Allocca, G. Bella, A. De Vita, L. Di Angelo
"Experimental Validation of a GDI Spray Model"
SAE Technical Paper Series, 2002-01-1137
Definition at line 59 of file BlobsSheetAtomization.H.
Constructor & Destructor Documentation
BlobsSheetAtomization() [1/2]
BlobsSheetAtomization (const dictionary & dict, CloudType & cloud)
Construct from dictionary.
Definition at line 32 of file BlobsSheetAtomization.C.
BlobsSheetAtomization() [2/2]
BlobsSheetAtomization (const BlobsSheetAtomization< CloudType > & am)
Construct copy.
Definition at line 45 of file BlobsSheetAtomization.C.
~BlobsSheetAtomization()
~BlobsSheetAtomization () virtual
Destructor.
Definition at line 58 of file BlobsSheetAtomization.C.
Referenced by BlobsSheetAtomization< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("blobsSheetAtomization")
Runtime type information.
clone()
virtual autoPtr<AtomizationModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements AtomizationModel< CloudType >.
Definition at line 84 of file BlobsSheetAtomization.H.
References BlobsSheetAtomization< CloudType >::calcChi(), BlobsSheetAtomization< CloudType >::initLiquidCore(), Foam::constant::physicoChemical::mu, Foam::pos(), rho, rndGen(), Foam::constant::physicoChemical::sigma, BlobsSheetAtomization< CloudType >::update(), Urel, and BlobsSheetAtomization< CloudType >::~BlobsSheetAtomization().
initLiquidCore()
Foam::scalar initLiquidCore () const virtual
Initial value of liquidCore.
Implements AtomizationModel< CloudType >.
Definition at line 65 of file BlobsSheetAtomization.C.
Referenced by BlobsSheetAtomization< CloudType >::clone().
calcChi()
bool calcChi () const virtual
Flag to indicate if chi needs to be calculated.
Implements AtomizationModel< CloudType >.
Definition at line 72 of file BlobsSheetAtomization.C.
References BlobsSheetAtomization< CloudType >::update().
Referenced by BlobsSheetAtomization< CloudType >::clone().
update()
void update (const scalar dt, scalar & d, scalar & liquidCore, scalar & tc, const scalar rho, const scalar mu, const scalar sigma, const scalar volFlowRate, const scalar rhoAv, const scalar Urel, const vector & pos, const vector & injectionPos, const scalar pAmbient, const scalar chi, cachedRandom & rndGen) const virtual
Implements AtomizationModel< CloudType >.
Definition at line 80 of file BlobsSheetAtomization.C.
References Foam::cos(), Foam::mag(), Foam::constant::mathematical::pi(), Foam::sqr(), and Foam::sqrt().
Referenced by BlobsSheetAtomization< CloudType >::calcChi(), and BlobsSheetAtomization< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/spray/submodels/AtomizationModel/BlobsSheetAtomization/BlobsSheetAtomization.H
src/lagrangian/spray/submodels/AtomizationModel/BlobsSheetAtomization/BlobsSheetAtomization.C