OpenFOAM: tetherPotentialList Class Reference
tetherPotentialList Class Reference
Public Member Functions
tetherPotentialList ()
tetherPotentialList (const List< word > &siteIdList, const dictionary &tetherPotentialDict, const List< word > &tetherSiteIdList)
Construct from siteIdList and potental dictionaries.
~tetherPotentialList ()
Destructor.
void buildPotentials (const List< word > &siteIdList, const dictionary &tetherPotentialDict, const List< word > &tetherSiteIdList)
const List< word > & idMap () const
const tetherPotential & tetherPotentialFunction (const label a) const
vector force (const label a, const vector rIT) const
scalar energy (const label a, const vector rIT) const
Public Member Functions inherited from PtrList< tetherPotential >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< tetherPotential > &)
Copy constructor.
PtrList (const PtrList< tetherPotential > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< tetherPotential >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< tetherPotential > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< tetherPotential > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (tetherPotential *)
Append an element at the end of the list.
void append (const autoPtr< tetherPotential > &)
void append (const tmp< tetherPotential > &)
void transfer (PtrList< tetherPotential > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< tetherPotential > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< tetherPotential > set (const label, tetherPotential *)
Set element to given T* and return old element (can be nullptr)
autoPtr< tetherPotential > set (const label, const autoPtr< tetherPotential > &)
Set element to given autoPtr<T> and return old element.
autoPtr< tetherPotential > set (const label, const tmp< tetherPotential > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< tetherPotential > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< tetherPotential >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Source files
tetherPotentialList.H
tetherPotentialList.C
Definition at line 50 of file tetherPotentialList.H.
Constructor & Destructor Documentation
tetherPotentialList() [1/2]
tetherPotentialList ()
Definition at line 87 of file tetherPotentialList.C.
tetherPotentialList() [2/2]
tetherPotentialList (const List< word > & siteIdList, const dictionary & tetherPotentialDict, const List< word > & tetherSiteIdList)
Construct from siteIdList and potental dictionaries.
Definition at line 95 of file tetherPotentialList.C.
References tetherPotentialList::buildPotentials().
~tetherPotentialList()
~tetherPotentialList ()
Destructor.
Definition at line 110 of file tetherPotentialList.C.
References tetherPotentialList::buildPotentials().
Member Function Documentation
buildPotentials()
void buildPotentials (const List< word > & siteIdList, const dictionary & tetherPotentialDict, const List< word > & tetherSiteIdList)
Definition at line 117 of file tetherPotentialList.C.
References PtrList< tetherPotential >::setSize(), List< T >::size(), and tetherPotentialList::tetherPotentialFunction().
Referenced by tetherPotentialList::tetherPotentialList(), and tetherPotentialList::~tetherPotentialList().
idMap()
const List<word>& idMap () const inline
tetherPotentialFunction()
const Foam::tetherPotential & tetherPotentialFunction (const label a) const
Definition at line 130 of file tetherPotentialList.C.
References tetherPotentialList::force().
Referenced by tetherPotentialList::buildPotentials().
force()
Foam::vector force (const label a, const vector rIT) const
Definition at line 139 of file tetherPotentialList.C.
References tetherPotentialList::energy().
Referenced by tetherPotentialList::tetherPotentialFunction().
energy()
Foam::scalar energy (const label a, const vector rIT) const
Definition at line 149 of file tetherPotentialList.C.
Referenced by tetherPotentialList::force().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/tetherPotential/tetherPotentialList/tetherPotentialList.H
src/lagrangian/molecularDynamics/potential/tetherPotential/tetherPotentialList/tetherPotentialList.C
src/lagrangian/molecularDynamics/potential/tetherPotential/tetherPotentialList/tetherPotentialListI.H