OpenFOAM: solidParticle::iNew Class Reference
solidParticle::iNew Class Reference
Factory class to read-construct particles used for.
Public Member Functions
iNew (const polyMesh &mesh)
autoPtr< solidParticle > operator() (Istream &is) const
Detailed Description
Factory class to read-construct particles used for.
parallel transfer
Definition at line 156 of file solidParticle.H.
Constructor & Destructor Documentation
iNew()
iNew (const polyMesh & mesh) inline
Definition at line 162 of file solidParticle.H.
Member Function Documentation
operator()()
autoPtr<solidParticle> operator() (Istream & is) const inline
Definition at line 167 of file solidParticle.H.
References Foam::constant::universal::c, solidParticle::d(), solidParticle::hitPatch(), solidParticle::hitProcessorPatch(), solidParticle::hitWallPatch(), solidParticle::move(), n, solidParticle::operator<<, patchi, solidParticle::readFields(), solidParticle::solidParticle(), Foam::T(), solidParticle::transformProperties(), solidParticle::U(), solidParticle::wallImpactDistance(), and solidParticle::writeFields().
The documentation for this class was generated from the following file:
src/lagrangian/solidParticle/solidParticle.H