OpenFOAM: restrainedHarmonicSpring Class Reference
restrainedHarmonicSpring Class Reference
Public Member Functions
TypeName ("restrainedHarmonicSpring")
Runtime type information.
restrainedHarmonicSpring (const word &name, const dictionary &tetherPotentialProperties)
Construct from components.
~restrainedHarmonicSpring ()
Destructor.
scalar energy (const vector r) const
vector force (const vector r) const
bool read (const dictionary &tetherPotentialProperties)
Read dictionary.
Public Member Functions inherited from tetherPotential
TypeName ("tetherPotential")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, tetherPotential, dictionary,(const word &name, const dictionary &tetherPotentialProperties),(name, tetherPotentialProperties))
tetherPotential (const word &name, const dictionary &tetherPotentialProperties)
Construct from components.
virtual ~tetherPotential ()
Destructor.
const dictionary & tetherPotentialProperties () const
Additional Inherited Members
Static Public Member Functions inherited from tetherPotential
static autoPtr< tetherPotential > New (const word &name, const dictionary &tetherPotentialProperties)
Return a reference to the selected viscosity model.
Protected Member Functions inherited from tetherPotential
tetherPotential (const tetherPotential &)
Disallow copy construct.
void operator= (const tetherPotential &)
Disallow default bitwise assignment.
Protected Attributes inherited from tetherPotential
word name_
dictionary tetherPotentialProperties_
Detailed Description
Source files
restrainedHarmonicSpring.H
restrainedHarmonicSpring.C
Definition at line 50 of file restrainedHarmonicSpring.H.
Constructor & Destructor Documentation
restrainedHarmonicSpring()
restrainedHarmonicSpring (const word & name, const dictionary & tetherPotentialProperties)
Construct from components.
Definition at line 51 of file restrainedHarmonicSpring.C.
~restrainedHarmonicSpring()
~restrainedHarmonicSpring () inline
Destructor.
Definition at line 80 of file restrainedHarmonicSpring.H.
References restrainedHarmonicSpring::energy(), restrainedHarmonicSpring::force(), and restrainedHarmonicSpring::read().
Member Function Documentation
TypeName()
TypeName ("restrainedHarmonicSpring")
Runtime type information.
energy()
scalar energy (const vector r) const virtual
Implements tetherPotential.
Definition at line 73 of file restrainedHarmonicSpring.C.
References Foam::mag(), and Foam::magSqr().
Referenced by restrainedHarmonicSpring::~restrainedHarmonicSpring().
force()
vector force (const vector r) const virtual
Implements tetherPotential.
Definition at line 89 of file restrainedHarmonicSpring.C.
References Foam::mag(), and restrainedHarmonicSpring::read().
Referenced by restrainedHarmonicSpring::~restrainedHarmonicSpring().
read()
bool read (const dictionary & tetherPotentialProperties) virtual
Read dictionary.
Implements tetherPotential.
Definition at line 105 of file restrainedHarmonicSpring.C.
References dictionary::lookup(), tetherPotential::read(), and dictionary::subDict().
Referenced by restrainedHarmonicSpring::force(), and restrainedHarmonicSpring::~restrainedHarmonicSpring().
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/tetherPotential/derived/restrainedHarmonicSpring/restrainedHarmonicSpring.H
src/lagrangian/molecularDynamics/potential/tetherPotential/derived/restrainedHarmonicSpring/restrainedHarmonicSpring.C