OpenFOAM: pairPotentialList Class Reference
pairPotentialList Class Reference
Public Member Functions
pairPotentialList ()
pairPotentialList (const List< word > &idList, const dictionary &pairPotentialDict, const polyMesh &mesh)
Construct from idList and potental dictionaries.
~pairPotentialList ()
Destructor.
void buildPotentials (const List< word > &idList, const dictionary &pairPotentialDict, const polyMesh &mesh)
scalar rCutMax () const
scalar rCutMaxSqr () const
bool rCutMaxSqr (scalar rIJMagSqr) const
const pairPotential & pairPotentialFunction (const label a, const label b) const
bool rCutSqr (const label a, const label b, const scalar rIJMagSqr) const
scalar rMin (const label a, const label b) const
scalar dr (const label a, const label b) const
scalar rCutSqr (const label a, const label b) const
scalar rCut (const label a, const label b) const
scalar force (const label a, const label b, const scalar rIJMag) const
scalar energy (const label a, const label b, const scalar rIJMag) const
const pairPotential & electrostatic () const
Public Member Functions inherited from PtrList< pairPotential >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< pairPotential > &)
Copy constructor.
PtrList (const PtrList< pairPotential > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< pairPotential >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< pairPotential > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< pairPotential > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (pairPotential *)
Append an element at the end of the list.
void append (const autoPtr< pairPotential > &)
void append (const tmp< pairPotential > &)
void transfer (PtrList< pairPotential > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< pairPotential > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< pairPotential > set (const label, pairPotential *)
Set element to given T* and return old element (can be nullptr)
autoPtr< pairPotential > set (const label, const autoPtr< pairPotential > &)
Set element to given autoPtr<T> and return old element.
autoPtr< pairPotential > set (const label, const tmp< pairPotential > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< pairPotential > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< pairPotential >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Source files
pairPotentialList.H
pairPotentialListI.H
pairPotentialList.C
Definition at line 51 of file pairPotentialList.H.
Constructor & Destructor Documentation
pairPotentialList() [1/2]
pairPotentialList ()
Definition at line 175 of file pairPotentialList.C.
pairPotentialList() [2/2]
pairPotentialList (const List< word > & idList, const dictionary & pairPotentialDict, const polyMesh & mesh)
Construct from idList and potental dictionaries.
Definition at line 182 of file pairPotentialList.C.
References pairPotentialList::buildPotentials().
~pairPotentialList()
~pairPotentialList ()
Destructor.
Definition at line 196 of file pairPotentialList.C.
References pairPotentialList::buildPotentials().
Member Function Documentation
buildPotentials()
void buildPotentials (const List< word > & idList, const dictionary & pairPotentialDict, const polyMesh & mesh)
Definition at line 203 of file pairPotentialList.C.
References pairPotentialList::pairPotentialFunction(), PtrList< pairPotential >::setSize(), and List< T >::size().
Referenced by pairPotentialList::pairPotentialList(), and pairPotentialList::~pairPotentialList().
rCutMax()
Foam::scalar rCutMax () const inline
Definition at line 61 of file pairPotentialListI.H.
rCutMaxSqr() [1/2]
Foam::scalar rCutMaxSqr () const inline
Definition at line 67 of file pairPotentialListI.H.
rCutMaxSqr() [2/2]
bool rCutMaxSqr (scalar rIJMagSqr) const
Definition at line 227 of file pairPotentialList.C.
References pairPotentialList::rCutSqr().
pairPotentialFunction()
const Foam::pairPotential & pairPotentialFunction (const label a, const label b) const
Definition at line 218 of file pairPotentialList.C.
Referenced by pairPotentialList::buildPotentials().
rCutSqr() [1/2]
bool rCutSqr (const label a, const label b, const scalar rIJMagSqr) const
Definition at line 241 of file pairPotentialList.C.
References pairPotentialList::rMin().
Referenced by pairPotentialList::dr(), and pairPotentialList::rCutMaxSqr().
rMin()
Foam::scalar rMin (const label a, const label b) const
Definition at line 259 of file pairPotentialList.C.
References pairPotentialList::dr().
Referenced by pairPotentialList::rCutSqr().
dr()
Foam::scalar dr (const label a, const label b) const
Definition at line 269 of file pairPotentialList.C.
References pairPotentialList::rCutSqr().
Referenced by pairPotentialList::rMin().
rCutSqr() [2/2]
Foam::scalar rCutSqr (const label a, const label b) const
Definition at line 279 of file pairPotentialList.C.
References pairPotentialList::rCut().
rCut()
Foam::scalar rCut (const label a, const label b) const
Definition at line 289 of file pairPotentialList.C.
References pairPotentialList::force().
Referenced by pairPotentialList::rCutSqr().
force()
Foam::scalar force (const label a, const label b, const scalar rIJMag) const
Definition at line 299 of file pairPotentialList.C.
References pairPotentialList::energy(), and f().
Referenced by pairPotentialList::rCut().
energy()
Foam::scalar energy (const label a, const label b, const scalar rIJMag) const
Definition at line 312 of file pairPotentialList.C.
References Foam::e.
Referenced by pairPotentialList::force().
electrostatic()
const Foam::pairPotential & electrostatic () const inline
Definition at line 73 of file pairPotentialListI.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/pairPotential/pairPotentialList/pairPotentialList.H
src/lagrangian/molecularDynamics/potential/pairPotential/pairPotentialList/pairPotentialList.C
src/lagrangian/molecularDynamics/potential/pairPotential/pairPotentialList/pairPotentialListI.H