OpenFOAM: DispersionRASModel< CloudType > Class Template Reference
DispersionRASModel< CloudType > Class Template Reference abstract
Base class for particle dispersion models based on RAS turbulence.
Public Member Functions
TypeName ("dispersionRASModel")
Runtime type information.
DispersionRASModel (const dictionary &dict, CloudType &owner)
Construct from components.
DispersionRASModel (const DispersionRASModel< CloudType > &dm)
Construct copy.
virtual autoPtr< DispersionModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~DispersionRASModel ()
Destructor.
virtual vector update (const scalar dt, const label celli, const vector &U, const vector &Uc, vector &UTurb, scalar &tTurb)=0
Update (disperse particles)
virtual void cacheFields (const bool store)
Cache carrier fields.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from DispersionModel< CloudType >
TypeName ("dispersionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DispersionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
DispersionModel (CloudType &owner)
Construct null from owner.
DispersionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
DispersionModel (const DispersionModel< CloudType > &dm)
Construct copy.
virtual ~DispersionModel ()
Destructor.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Member Functions
tmp< volScalarField > kModel () const
Return the k field from the turbulence model.
tmp< volScalarField > epsilonModel () const
Return the epsilon field from the turbulence model.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
const volScalarField * kPtr_
Turbulence k.
bool ownK_
Take ownership of the k field.
const volScalarField * epsilonPtr_
Turbulence epsilon.
bool ownEpsilon_
Take ownership of the epsilon field.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from DispersionModel< CloudType >
static autoPtr< DispersionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::DispersionRASModel< CloudType >
Base class for particle dispersion models based on RAS turbulence.
Definition at line 47 of file DispersionRASModel.H.
Constructor & Destructor Documentation
DispersionRASModel() [1/2]
DispersionRASModel (const dictionary & dict, CloudType & owner)
Construct from components.
Definition at line 96 of file DispersionRASModel.C.
Referenced by DispersionRASModel< CloudType >::epsilonModel().
DispersionRASModel() [2/2]
DispersionRASModel (const DispersionRASModel< CloudType > & dm)
Construct copy.
Definition at line 111 of file DispersionRASModel.C.
References DispersionRASModel< CloudType >::ownEpsilon_, and DispersionRASModel< CloudType >::ownK_.
~DispersionRASModel()
~DispersionRASModel () virtual
Destructor.
Definition at line 129 of file DispersionRASModel.C.
Member Function Documentation
kModel()
Foam::tmp< Foam::volScalarField > kModel () const protected
Return the k field from the turbulence model.
Definition at line 34 of file DispersionRASModel.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, objectRegistry::foundObject(), Foam::constant::atomic::group, turbulenceModel::k(), objectRegistry::lookupObject(), Foam::nl, HashTable< T, Key, Hash >::sortedToc(), and U.
epsilonModel()
Foam::tmp< Foam::volScalarField > epsilonModel () const protected
Return the epsilon field from the turbulence model.
Definition at line 64 of file DispersionRASModel.C.
References Foam::abort(), DispersionRASModel< CloudType >::DispersionRASModel(), turbulenceModel::epsilon(), Foam::FatalError, FatalErrorInFunction, objectRegistry::foundObject(), Foam::constant::atomic::group, objectRegistry::lookupObject(), Foam::nl, HashTable< T, Key, Hash >::sortedToc(), and U.
TypeName()
TypeName ("dispersionRASModel")
Runtime type information.
clone()
virtual autoPtr<DispersionModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implements DispersionModel< CloudType >.
Implemented in GradientDispersionRAS< CloudType >, and StochasticDispersionRAS< CloudType >.
update()
virtual vector update (const scalar dt, const label celli, const vector & U, const vector & Uc, vector & UTurb, scalar & tTurb) pure virtual
Update (disperse particles)
Implements DispersionModel< CloudType >.
Implemented in GradientDispersionRAS< CloudType >, and StochasticDispersionRAS< CloudType >.
cacheFields()
void cacheFields (const bool store) virtual
Cache carrier fields.
Reimplemented from subModelBase.
Reimplemented in GradientDispersionRAS< CloudType >.
Definition at line 138 of file DispersionRASModel.C.
References Foam::deleteDemandDrivenData(), tmp< T >::isTmp(), and tmp< T >::ptr().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from CloudSubModelBase< CloudType >.
Definition at line 183 of file DispersionRASModel.C.
References Foam::endl(), write(), and Ostream::writeKeyword().
Member Data Documentation
kPtr_
const volScalarField* kPtr_ protected
Turbulence k.
Definition at line 58 of file DispersionRASModel.H.
ownK_
bool ownK_ mutable protected
Take ownership of the k field.
Definition at line 61 of file DispersionRASModel.H.
Referenced by DispersionRASModel< CloudType >::DispersionRASModel().
epsilonPtr_
const volScalarField* epsilonPtr_ protected
Turbulence epsilon.
Definition at line 64 of file DispersionRASModel.H.
ownEpsilon_
bool ownEpsilon_ mutable protected
Take ownership of the epsilon field.
Definition at line 67 of file DispersionRASModel.H.
Referenced by DispersionRASModel< CloudType >::DispersionRASModel().
The documentation for this class was generated from the following files:
src/lagrangian/turbulence/submodels/Kinematic/DispersionModel/DispersionRASModel/DispersionRASModel.H
src/lagrangian/turbulence/submodels/Kinematic/DispersionModel/DispersionRASModel/DispersionRASModel.C