OpenFOAM: gradingDescriptors Class Reference
gradingDescriptors Class Reference
List of gradingDescriptor for the sections of a block with additional IO functionality.
Public Member Functions
gradingDescriptors ()
Default constructor.
gradingDescriptors (const gradingDescriptor &gd)
Construct from a gradingDescriptor.
gradingDescriptors inv () const
Return the inverse gradingDescriptors with 1/expansionRatio.
Public Member Functions inherited from List< gradingDescriptor >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const gradingDescriptor &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< gradingDescriptor > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< gradingDescriptor >> &)
Construct by transferring the parameter contents.
List (List< gradingDescriptor > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< gradingDescriptor > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< gradingDescriptor, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< gradingDescriptor > &)
Construct as copy of PtrList<T>
List (const SLList< gradingDescriptor > &)
Construct as copy of SLList<T>
List (const UIndirectList< gradingDescriptor > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< gradingDescriptor > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< gradingDescriptor >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< gradingDescriptor > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const gradingDescriptor &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const gradingDescriptor &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const gradingDescriptor &)
Append an element at the end of the list.
void append (const UList< gradingDescriptor > &)
Append a List at the end of this list.
void append (const UIndirectList< gradingDescriptor > &)
Append a UIndirectList at the end of this list.
void transfer (List< gradingDescriptor > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< gradingDescriptor, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< gradingDescriptor > &)
Transfer the contents of the argument List into this list.
Xfer< List< gradingDescriptor > > xfer ()
Transfer contents to the Xfer container.
gradingDescriptor & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< gradingDescriptor > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< gradingDescriptor > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< gradingDescriptor > &)
Assignment operator. Takes linear time.
void operator= (const SLList< gradingDescriptor > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< gradingDescriptor > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< gradingDescriptor > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< gradingDescriptor >)
Assignment to an initializer list.
void operator= (const gradingDescriptor &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Friends
Istream & operator>> (Istream &, gradingDescriptors &)
Additional Inherited Members
Public Types inherited from List< gradingDescriptor >
typedef SubList< gradingDescriptor > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from List< gradingDescriptor >
static const List< gradingDescriptor > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< gradingDescriptor >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
List of gradingDescriptor for the sections of a block with additional IO functionality.
Source files
gradingDescriptors.H
gradingDescriptors.C
Definition at line 57 of file gradingDescriptors.H.
Constructor & Destructor Documentation
gradingDescriptors() [1/2]
gradingDescriptors ()
Default constructor.
Definition at line 30 of file gradingDescriptors.C.
Referenced by Foam::operator>>().
gradingDescriptors() [2/2]
gradingDescriptors (const gradingDescriptor & gd)
Construct from a gradingDescriptor.
Definition at line 36 of file gradingDescriptors.C.
Member Function Documentation
inv()
Foam::gradingDescriptors inv () const
Return the inverse gradingDescriptors with 1/expansionRatio.
Definition at line 44 of file gradingDescriptors.C.
References forAll, UList< T >::operator[](), and List< T >::size().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , gradingDescriptors &) friend
The documentation for this class was generated from the following files:
src/mesh/blockMesh/gradingDescriptor/gradingDescriptors.H
src/mesh/blockMesh/gradingDescriptor/gradingDescriptors.C