OpenFOAM: gradingDescriptor Class Reference
gradingDescriptor Class Reference
Handles the specification for grading within a section of a block.
Public Member Functions
gradingDescriptor ()
Default constructor.
gradingDescriptor (const scalar blockFraction, const scalar nDivFraction, const scalar expansionRatio)
Construct from components.
gradingDescriptor (const scalar expansionRatio)
Construct from expansionRatio.
gradingDescriptor (Istream &)
Construct from Istream.
~gradingDescriptor ()
Destructor.
scalar blockFraction () const
scalar nDivFraction () const
scalar expansionRatio () const
gradingDescriptor inv () const
Return the inverse gradingDescriptor with 1/expansionRatio.
bool operator== (const gradingDescriptor &) const
bool operator!= (const gradingDescriptor &) const
Friends
class gradingDescriptors
Istream & operator>> (Istream &, gradingDescriptor &)
Ostream & operator<< (Ostream &, const gradingDescriptor &)
Istream & operator>> (Istream &, gradingDescriptors &)
Detailed Description
Handles the specification for grading within a section of a block.
blockFraction: the fraction of the block the section occupies
nDivFraction: the fraction of the divisions of the block allocated to the section
expansionRatio: the expansions ratio for the grading with the section of block defined as the ratio of the size of the division at either and of the section.
Source files
gradingDescriptor.H
gradingDescriptor.C
Definition at line 66 of file gradingDescriptor.H.
Constructor & Destructor Documentation
gradingDescriptor() [1/4]
gradingDescriptor ()
Default constructor.
Definition at line 32 of file gradingDescriptor.C.
Referenced by gradingDescriptor::gradingDescriptor(), and gradingDescriptor::inv().
gradingDescriptor() [2/4]
gradingDescriptor (const scalar blockFraction, const scalar nDivFraction, const scalar expansionRatio)
Construct from components.
Definition at line 41 of file gradingDescriptor.C.
References gradingDescriptor::gradingDescriptor().
gradingDescriptor() [3/4]
gradingDescriptor (const scalar expansionRatio)
Construct from expansionRatio.
Definition at line 54 of file gradingDescriptor.C.
gradingDescriptor() [4/4]
gradingDescriptor (Istream & is)
Construct from Istream.
Definition at line 64 of file gradingDescriptor.C.
~gradingDescriptor()
~gradingDescriptor ()
Destructor.
Definition at line 72 of file gradingDescriptor.C.
Member Function Documentation
blockFraction()
scalar blockFraction () const inline
Definition at line 111 of file gradingDescriptor.H.
nDivFraction()
scalar nDivFraction () const inline
Definition at line 116 of file gradingDescriptor.H.
expansionRatio()
scalar expansionRatio () const inline
Definition at line 121 of file gradingDescriptor.H.
References gradingDescriptor::inv(), gradingDescriptor::operator!=(), gradingDescriptor::operator<<, gradingDescriptor::operator==(), and gradingDescriptor::operator>>.
inv()
Foam::gradingDescriptor inv () const
Return the inverse gradingDescriptor with 1/expansionRatio.
Definition at line 78 of file gradingDescriptor.C.
References gradingDescriptor::gradingDescriptor().
Referenced by gradingDescriptor::expansionRatio().
operator==()
bool operator== (const gradingDescriptor & gd) const
Definition at line 91 of file gradingDescriptor.C.
References Foam::equal().
Referenced by gradingDescriptor::expansionRatio(), and gradingDescriptor::operator!=().
operator!=()
bool operator!= (const gradingDescriptor & gd) const
Definition at line 100 of file gradingDescriptor.C.
References gradingDescriptor::operator==().
Referenced by gradingDescriptor::expansionRatio().
Friends And Related Function Documentation
gradingDescriptors
friend class gradingDescriptors friend
Definition at line 77 of file gradingDescriptor.H.
operator>> [1/2]
Istream& operator>> (Istream & , gradingDescriptor &) friend
Referenced by gradingDescriptor::expansionRatio().
operator<<
Ostream& operator<< (Ostream & , const gradingDescriptor &) friend
Referenced by gradingDescriptor::expansionRatio().
operator>> [2/2]
Istream& operator>> (Istream & , gradingDescriptors &) friend
The documentation for this class was generated from the following files:
src/mesh/blockMesh/gradingDescriptor/gradingDescriptor.H
src/mesh/blockMesh/gradingDescriptor/gradingDescriptor.C