OpenFOAM: BrownianMotionForce< CloudType > Class Template Reference
BrownianMotionForce< CloudType > Class Template Reference
Calculates particle Brownian motion force.
Public Member Functions
TypeName ("BrownianMotion")
Runtime type information.
BrownianMotionForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict)
Construct from mesh.
BrownianMotionForce (const BrownianMotionForce &bmf)
Construct copy.
virtual autoPtr< ParticleForce< CloudType > > clone () const
Construct and return a clone.
virtual ~BrownianMotionForce ()
Destructor.
scalar lambda () const
Return const access to the molecular free path length [m].
bool turbulence () const
Return const access to the turbulence flag.
virtual void cacheFields (const bool store)
Cache fields.
virtual forceSuSp calcCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the coupled force.
Public Member Functions inherited from ParticleForce< CloudType >
TypeName ("particleForce")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ParticleForce, dictionary,(CloudType &owner, const fvMesh &mesh, const dictionary &dict),(owner, mesh, dict))
Declare runtime constructor selection table.
ParticleForce (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType, const bool readCoeffs)
Construct from mesh.
ParticleForce (const ParticleForce &pf)
Construct copy.
virtual ~ParticleForce ()
Destructor.
const CloudType & owner () const
Return const access to the cloud owner.
CloudType & owner ()
Return refernce to the cloud owner.
const fvMesh & mesh () const
Return the mesh database.
const dictionary & coeffs () const
Return the force coefficients dictionary.
virtual forceSuSp calcNonCoupled (const typename CloudType::parcelType &p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const
Calculate the non-coupled force.
virtual scalar massAdd (const typename CloudType::parcelType &p, const scalar mass) const
Return the added mass.
Additional Inherited Members
Public Types inherited from ParticleForce< CloudType >
typedef VectorSpace< Vector< vector >, vector, 2 > returnType
Convenience typedef for return type.
Static Public Member Functions inherited from ParticleForce< CloudType >
static autoPtr< ParticleForce< CloudType > > New (CloudType &owner, const fvMesh &mesh, const dictionary &dict, const word &forceType)
Selector.
Detailed Description
template<class CloudType>
class Foam::BrownianMotionForce< CloudType >
Calculates particle Brownian motion force.
Reference:
    Li, A., & Ahmadi, G. (1992).
    Dispersion and deposition of spherical particles from point sources
    in a turbulent channel flow.
    Aerosol science and technology,
    16(4), 209-226.
Source files
BrownianMotionForce.H
BrownianMotionForceI.H
BrownianMotionForce.C
Definition at line 60 of file BrownianMotionForce.H.
Constructor & Destructor Documentation
BrownianMotionForce() [1/2]
BrownianMotionForce (CloudType & owner, const fvMesh & mesh, const dictionary & dict)
Construct from mesh.
Definition at line 89 of file BrownianMotionForce.C.
BrownianMotionForce() [2/2]
BrownianMotionForce (const BrownianMotionForce< CloudType > & bmf)
Construct copy.
Definition at line 106 of file BrownianMotionForce.C.
~BrownianMotionForce()
~BrownianMotionForce () virtual
Destructor.
Definition at line 122 of file BrownianMotionForce.C.
Referenced by BrownianMotionForce< CloudType >::clone().
Member Function Documentation
TypeName()
TypeName ("BrownianMotion")
Runtime type information.
clone()
virtual autoPtr<ParticleForce<CloudType> > clone () const inline virtual
Construct and return a clone.
Reimplemented from ParticleForce< CloudType >.
Definition at line 111 of file BrownianMotionForce.H.
References BrownianMotionForce< CloudType >::cacheFields(), BrownianMotionForce< CloudType >::calcCoupled(), BrownianMotionForce< CloudType >::lambda(), p, Foam::Re(), BrownianMotionForce< CloudType >::turbulence(), and BrownianMotionForce< CloudType >::~BrownianMotionForce().
lambda()
Foam::scalar lambda () const inline
Return const access to the molecular free path length [m].
Definition at line 29 of file BrownianMotionForceI.H.
Referenced by BrownianMotionForce< CloudType >::clone().
turbulence()
bool turbulence () const inline
Return const access to the turbulence flag.
Definition at line 36 of file BrownianMotionForceI.H.
Referenced by BrownianMotionForce< CloudType >::clone().
cacheFields()
void cacheFields (const bool store) virtual
Cache fields.
Reimplemented from ParticleForce< CloudType >.
Definition at line 129 of file BrownianMotionForce.C.
References BrownianMotionForce< CloudType >::calcCoupled(), Foam::deleteDemandDrivenData(), tmp< T >::isTmp(), and tmp< T >::ptr().
Referenced by BrownianMotionForce< CloudType >::clone().
calcCoupled()
Foam::forceSuSp calcCoupled (const typename CloudType::parcelType & p, const scalar dt, const scalar mass, const scalar Re, const scalar muc) const virtual
Calculate the coupled force.
Reimplemented from ParticleForce< CloudType >.
Definition at line 161 of file BrownianMotionForce.C.
References Foam::constant::atomic::alpha, Foam::cos(), Foam::exp(), f(), cachedRandom::GaussNormal(), Foam::constant::physicoChemical::k, Foam::mag(), Foam::constant::mathematical::pi(), Foam::pow5(), cachedRandom::sample01(), Foam::sin(), Foam::sqr(), Foam::sqrt(), forceSuSp::Su(), Foam::constant::mathematical::twoPi(), dimensioned< Type >::value(), and Foam::Zero.
Referenced by BrownianMotionForce< CloudType >::cacheFields(), and BrownianMotionForce< CloudType >::clone().
The documentation for this class was generated from the following files:
src/lagrangian/turbulence/submodels/Thermodynamic/ParticleForces/BrownianMotion/BrownianMotionForce.H
src/lagrangian/turbulence/submodels/Thermodynamic/ParticleForces/BrownianMotion/BrownianMotionForce.C
src/lagrangian/turbulence/submodels/Thermodynamic/ParticleForces/BrownianMotion/BrownianMotionForceI.H