OpenFOAM: curvedEdge Class Reference
curvedEdge Class Reference abstract
Define a curved edge that is parameterized for 0<lambda<1 between the start and end point.
Public Member Functions
TypeName ("curvedEdge")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, curvedEdge, Istream,(const pointField &points, Istream &is),(points, is))
curvedEdge (const pointField &points, const label start, const label end)
Construct from components.
curvedEdge (const pointField &, Istream &)
Construct from Istream setting pointsList.
curvedEdge (const curvedEdge &)
Copy construct.
virtual autoPtr< curvedEdge > clone () const
Clone function.
virtual ~curvedEdge ()
Destructor.
label start () const
Return label of start point.
label end () const
Return label of end point.
int compare (const curvedEdge &) const
Compare the given start and end points with this curve.
int compare (const edge &) const
Compare the given start and end points with this curve.
int compare (const label start, const label end) const
Compare the given start and end points with this curve.
virtual point position (const scalar) const =0
Return the point position corresponding to the curve parameter.
virtual scalar length () const =0
Return the length of the curve.
void operator= (const curvedEdge &)
Static Public Member Functions
static autoPtr< curvedEdge > New (const pointField &, Istream &)
New function which constructs and returns pointer to a curvedEdge.
Static Protected Member Functions
static pointField appendEndPoints (const pointField &, const label start, const label end, const pointField &otherKnots)
Return a complete point field by appending the start/end points.
Protected Attributes
const pointField & points_
const label start_
const label end_
Friends
Ostream & operator<< (Ostream &, const curvedEdge &)
Detailed Description
Define a curved edge that is parameterized for 0<lambda<1 between the start and end point.
Source files
curvedEdge.H
curvedEdge.C
Definition at line 60 of file curvedEdge.H.
Constructor & Destructor Documentation
curvedEdge() [1/3]
curvedEdge (const pointField & points, const label start, const label end)
Construct from components.
Definition at line 41 of file curvedEdge.C.
curvedEdge() [2/3]
curvedEdge (const pointField & points, Istream & is)
Construct from Istream setting pointsList.
Definition at line 53 of file curvedEdge.C.
curvedEdge() [3/3]
curvedEdge (const curvedEdge & c)
Copy construct.
Definition at line 61 of file curvedEdge.C.
~curvedEdge()
virtual ~curvedEdge () inline virtual
Destructor.
Definition at line 127 of file curvedEdge.H.
References curvedEdge::compare(), curvedEdge::end(), curvedEdge::length(), curvedEdge::operator<<, curvedEdge::operator=(), curvedEdge::position(), and curvedEdge::start().
Member Function Documentation
appendEndPoints()
Foam::pointField appendEndPoints (const pointField & points, const label start, const label end, const pointField & otherKnots) static protected
Return a complete point field by appending the start/end points.
to the given list
Definition at line 109 of file curvedEdge.C.
References curvedEdge::end(), forAll, List< T >::size(), and curvedEdge::start().
Referenced by curvedEdge::New().
TypeName()
TypeName ("curvedEdge")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , curvedEdge , Istream , (const pointField &points, Istream &is) , (points, is))
clone()
Foam::autoPtr< Foam::curvedEdge > clone () const virtual
Clone function.
Definition at line 69 of file curvedEdge.C.
References curvedEdge::New(), and NotImplemented.
New()
Foam::autoPtr< Foam::curvedEdge > New (const pointField & points, Istream & is) static
New function which constructs and returns pointer to a curvedEdge.
Definition at line 77 of file curvedEdge.C.
References Foam::abort(), curvedEdge::appendEndPoints(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, Foam::nl, and points.
Referenced by curvedEdge::clone().
start()
Foam::label start () const inline
Return label of start point.
Definition at line 28 of file curvedEdgeI.H.
References curvedEdge::start_.
Referenced by curvedEdge::appendEndPoints(), curvedEdge::compare(), and curvedEdge::~curvedEdge().
end()
Foam::label end () const inline
Return label of end point.
Definition at line 34 of file curvedEdgeI.H.
References curvedEdge::end_.
Referenced by curvedEdge::appendEndPoints(), curvedEdge::compare(), and curvedEdge::~curvedEdge().
compare() [1/3]
int compare (const curvedEdge & e) const inline
Compare the given start and end points with this curve.
Return:
0: different
+1: identical
-1: same edge, but different orientation
Definition at line 57 of file curvedEdgeI.H.
References curvedEdge::end(), and curvedEdge::start().
Referenced by curvedEdge::compare(), and curvedEdge::~curvedEdge().
compare() [2/3]
int compare (const edge & e) const inline
Compare the given start and end points with this curve.
Return:
0: different
+1: identical
-1: same edge, but different orientation
Definition at line 63 of file curvedEdgeI.H.
References curvedEdge::compare(), edge::end(), and edge::start().
compare() [3/3]
int compare (const label start, const label end) const inline
Compare the given start and end points with this curve.
Return:
0: different
+1: identical
-1: same edge, but different orientation
Definition at line 40 of file curvedEdgeI.H.
References curvedEdge::end_, and curvedEdge::start_.
position()
virtual point position (const scalar) const pure virtual
Return the point position corresponding to the curve parameter.
0 <= lambda <= 1
Implemented in arcEdge, BSplineEdge, polyLineEdge, splineEdge, and lineEdge.
Referenced by lineDivide::lineDivide(), and curvedEdge::~curvedEdge().
length()
virtual scalar length () const pure virtual
Return the length of the curve.
Implemented in arcEdge, BSplineEdge, polyLineEdge, splineEdge, and lineEdge.
Referenced by curvedEdge::~curvedEdge().
operator=()
void operator= (const curvedEdge &)
Definition at line 134 of file curvedEdge.C.
References NotImplemented.
Referenced by curvedEdge::~curvedEdge().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const curvedEdge &) friend
Referenced by curvedEdge::~curvedEdge().
Member Data Documentation
points_
const pointField& points_ protected
Definition at line 66 of file curvedEdge.H.
Referenced by lineEdge::length(), and lineEdge::position().
start_
const label start_ protected
Definition at line 67 of file curvedEdge.H.
Referenced by curvedEdge::compare(), lineEdge::length(), Foam::operator<<(), lineEdge::position(), and curvedEdge::start().
end_
const label end_ protected
Definition at line 68 of file curvedEdge.H.
Referenced by curvedEdge::compare(), curvedEdge::end(), lineEdge::length(), Foam::operator<<(), and lineEdge::position().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/curvedEdges/curvedEdge.H
src/mesh/blockMesh/curvedEdges/curvedEdge.C
src/mesh/blockMesh/curvedEdges/curvedEdgeI.H