OpenFOAM: blockDescriptor Class Reference
blockDescriptor Class Reference
Takes the description of the block and the list of curved edges and creates a list of points on edges together with the weighting factors.
Public Member Functions
blockDescriptor (const cellShape &, const pointField &blockPointField, const curvedEdgeList &, const Vector< label > &meshDensity, const UList< gradingDescriptors > &expand, const word &zoneName="")
Construct from components. Optional cellSet/zone name.
blockDescriptor (const pointField &blockPointField, const curvedEdgeList &, Istream &)
Construct from Istream.
autoPtr< blockDescriptor > clone () const
Clone.
~blockDescriptor ()
Destructor.
const Vector< label > & density () const
Return the number of cells in the i,j,k directions.
const pointField & blockPointField () const
Reference to point field defining the block mesh.
const cellShape & blockShape () const
Return the block shape.
const List< List< point > > & blockEdgePoints () const
Return the block points along each edge.
const scalarListList & blockEdgeWeights () const
Return the weightings along each edge.
const Vector< label > & meshDensity () const
Return the mesh density (number of cells) in the i,j,k directions.
const word & zoneName () const
Return the (optional) zone name.
label nPoints () const
Return the number of points.
label nCells () const
Return the number of cells.
const point & blockPoint (const label i) const
Return block point at local label i.
Friends
Ostream & operator<< (Ostream &, const blockDescriptor &)
Detailed Description
Takes the description of the block and the list of curved edges and creates a list of points on edges together with the weighting factors.
For a given block, the correspondence between the ordering of vertex labels and face labels is shown below. For vertex numbering in the sequence 0 to 7 (block, centre): faces 0 (f0) and 1 are left and right, respectively; faces 2 and 3 are bottom and top; and faces 4 and 5 are front the back:
         4 ---- 5
    f3   |\     |\   f5
     |   | 7 ---- 6    \
     |   0 |--- 1 |     \
     |    \|     \|      f4
    f2     3 ---- 2
         f0 ----- f1
Source files
blockDescriptor.H
blockDescriptor.C
blockDescriptorEdges.C
Definition at line 76 of file blockDescriptor.H.
Constructor & Destructor Documentation
blockDescriptor() [1/2]
blockDescriptor (const cellShape & bshape, const pointField & blockPointField, const curvedEdgeList & edges, const Vector< label > & meshDensity, const UList< gradingDescriptors > & expand, const word & zoneName = "")
Construct from components. Optional cellSet/zone name.
Definition at line 108 of file blockDescriptor.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
blockDescriptor() [2/2]
blockDescriptor (const pointField & blockPointField, const curvedEdgeList & edges, Istream & is)
Construct from Istream.
Definition at line 139 of file blockDescriptor.C.
References token::BEGIN_LIST, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, token::info(), token::isPunctuation(), token::isWord(), token::pToken(), Istream::putBack(), List< T >::size(), token::wordToken(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
~blockDescriptor()
~blockDescriptor ()
Destructor.
Definition at line 249 of file blockDescriptor.C.
Referenced by blockDescriptor::clone().
Member Function Documentation
clone()
autoPtr<blockDescriptor> clone () const inline
Clone.
Definition at line 147 of file blockDescriptor.H.
References NotImplemented, and blockDescriptor::~blockDescriptor().
density()
const Vector<label>& density () const inline
Return the number of cells in the i,j,k directions.
Definition at line 163 of file blockDescriptor.H.
References blockDescriptor::blockEdgePoints(), blockDescriptor::blockEdgeWeights(), blockDescriptor::blockPoint(), blockDescriptor::blockPointField(), blockDescriptor::blockShape(), blockDescriptor::meshDensity(), blockDescriptor::nCells(), blockDescriptor::nPoints(), blockDescriptor::operator<<, and blockDescriptor::zoneName().
blockPointField()
const Foam::pointField & blockPointField () const
Reference to point field defining the block mesh.
Definition at line 255 of file blockDescriptor.C.
Referenced by blockDescriptor::density().
blockShape()
const Foam::cellShape & blockShape () const
Return the block shape.
Definition at line 261 of file blockDescriptor.C.
Referenced by blockDescriptor::density(), and Foam::operator<<().
blockEdgePoints()
const Foam::List< Foam::List< Foam::point > > & blockEdgePoints () const
Return the block points along each edge.
Definition at line 268 of file blockDescriptor.C.
Referenced by blockDescriptor::density().
blockEdgeWeights()
const Foam::scalarListList & blockEdgeWeights () const
Return the weightings along each edge.
Definition at line 274 of file blockDescriptor.C.
Referenced by blockDescriptor::density().
meshDensity()
const Foam::Vector< Foam::label > & meshDensity () const
Return the mesh density (number of cells) in the i,j,k directions.
Definition at line 280 of file blockDescriptor.C.
Referenced by blockDescriptor::density(), Foam::faceNij(), Foam::facePoint(), Foam::facePointN(), Foam::operator<<(), and block::vtxLabel().
zoneName()
const Foam::word & zoneName () const
Return the (optional) zone name.
Definition at line 286 of file blockDescriptor.C.
Referenced by blockDescriptor::density(), and Foam::operator<<().
nPoints()
Foam::label nPoints () const
Return the number of points.
Definition at line 292 of file blockDescriptor.C.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by blockDescriptor::density().
nCells()
Foam::label nCells () const
Return the number of cells.
Definition at line 303 of file blockDescriptor.C.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by blockDescriptor::density().
blockPoint()
const Foam::point & blockPoint (const label i) const
Return block point at local label i.
Definition at line 314 of file blockDescriptor.C.
Referenced by blockDescriptor::density().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const blockDescriptor &) friend
Referenced by blockDescriptor::density().
The documentation for this class was generated from the following files:
src/mesh/blockMesh/blockDescriptor/blockDescriptor.H
src/mesh/blockMesh/blockDescriptor/blockDescriptor.C
src/mesh/blockMesh/blockDescriptor/blockDescriptorEdges.C