OpenFOAM: layerParameters Class Reference
layerParameters Class Reference
Simple container to keep together layer specific information.
Public Types
enum layerSpecification {
ILLEGAL, FIRST_AND_TOTAL, FIRST_AND_EXPANSION, FINAL_AND_TOTAL,
FINAL_AND_EXPANSION, TOTAL_AND_EXPANSION
}
Enumeration defining the layer specification:
Public Member Functions
layerParameters (const dictionary &dict, const polyBoundaryMesh &)
Construct from dictionary.
const dictionary & dict () const
const labelList & numLayers () const
How many layers to add:
bool relativeSizes () const
Are size parameters relative to inner cell size or.
const scalarField & expansionRatio () const
const scalarField & finalLayerThickness () const
Wanted thickness of the layer furthest away.
const scalarField & firstLayerThickness () const
Wanted thickness of the layer nearest to the wall.
const scalarField & thickness () const
Wanted overall thickness of all layers.
const scalarField & minThickness () const
Minimum overall thickness of cell layer. If for any reason layer.
label nLayerIter () const
Number of overall layer addition iterations.
label nRelaxedIter () const
Number of iterations after which relaxed motion rules.
scalar featureAngle () const
scalar concaveAngle () const
label nGrow () const
If points get not extruded do nGrow layers of connected faces.
scalar maxFaceThicknessRatio () const
Stop layer growth on highly warped cells.
label nBufferCellsNoExtrude () const
Create buffer region for new layer terminations.
const Switch & additionalReporting () const
const word & meshShrinker () const
Type of mesh shrinker.
scalar layerThickness (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine overall thickness. Uses two of the four parameters.
scalar layerExpansionRatio (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine expansion ratio. Uses two of the four parameters.
scalar firstLayerThickness (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine first layer (near-wall) thickness. Uses two of the.
scalar finalLayerThicknessRatio (const label nLayers, const scalar expansionRatio) const
Determine ratio of final layer thickness to.
Detailed Description
Simple container to keep together layer specific information.
Source files
layerParameters.H
layerParameters.C
Definition at line 55 of file layerParameters.H.
Member Enumeration Documentation
layerSpecification
enum layerSpecification
Enumeration defining the layer specification:
first and total thickness specified
first and expansion ratio specified
final and total thickness specified
final and expansion ratio specified
total thickness and expansion ratio specified
Enumerator
ILLEGAL
FIRST_AND_TOTAL
FIRST_AND_EXPANSION
FINAL_AND_TOTAL
FINAL_AND_EXPANSION
TOTAL_AND_EXPANSION
Definition at line 68 of file layerParameters.H.
Constructor & Destructor Documentation
layerParameters()
layerParameters (const dictionary & dict, const polyBoundaryMesh & boundaryMesh)
Construct from dictionary.
Definition at line 97 of file layerParameters.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, layerParameters::FINAL_AND_EXPANSION, layerParameters::FINAL_AND_TOTAL, layerParameters::FIRST_AND_EXPANSION, layerParameters::FIRST_AND_TOTAL, forAllConstIter(), dictionary::found(), layerParameters::ILLEGAL, Foam::Info, IOWarningInFunction, layerParameters::layerThickness(), dictionary::lookup(), polyBoundaryMesh::names(), Foam::nl, patchi, polyBoundaryMesh::patchSet(), dictionary::readIfPresent(), Foam::readLabel(), Foam::readScalar(), UPtrList< T >::size(), dictionary::subDict(), and layerParameters::TOTAL_AND_EXPANSION.
Member Function Documentation
dict()
const dictionary& dict () const inline
Definition at line 161 of file layerParameters.H.
References layerParameters::numLayers(), and layerParameters::relativeSizes().
Referenced by snappyLayerDriver::addLayers().
numLayers()
const labelList& numLayers () const inline
How many layers to add:
-1 : no specification. Assume 0 layers but allow sliding to make layers
0 : specified to have 0 layers. No sliding allowed.
>0 : number of layers
Definition at line 175 of file layerParameters.H.
Referenced by snappyLayerDriver::addLayers(), layerParameters::dict(), and snappyLayerDriver::doLayers().
relativeSizes()
bool relativeSizes () const inline
Are size parameters relative to inner cell size or.
absolute distances.
Definition at line 182 of file layerParameters.H.
Referenced by snappyLayerDriver::addLayers(), and layerParameters::dict().
expansionRatio()
const scalarField& expansionRatio () const inline
Definition at line 188 of file layerParameters.H.
References layerParameters::finalLayerThickness(), layerParameters::firstLayerThickness(), layerParameters::minThickness(), and layerParameters::thickness().
Referenced by layerParameters::finalLayerThicknessRatio(), layerParameters::layerExpansionRatio(), layerParameters::layerThickness(), and layerParameters::meshShrinker().
finalLayerThickness()
const scalarField& finalLayerThickness () const inline
Wanted thickness of the layer furthest away.
from the wall (i.e. nearest the original mesh). If relativeSize() this number is relative to undistorted size of the cell outside layer.
Definition at line 197 of file layerParameters.H.
Referenced by layerParameters::expansionRatio().
firstLayerThickness() [1/2]
const scalarField& firstLayerThickness () const inline
Wanted thickness of the layer nearest to the wall.
If relativeSize() this number is relative to undistorted size of the cell outside layer.
Definition at line 205 of file layerParameters.H.
Referenced by layerParameters::expansionRatio(), layerParameters::layerExpansionRatio(), and layerParameters::meshShrinker().
thickness()
const scalarField& thickness () const inline
Wanted overall thickness of all layers.
If relativeSize() this number is relative to undistorted size of the cell outside layer.
Definition at line 213 of file layerParameters.H.
Referenced by layerParameters::expansionRatio().
minThickness()
const scalarField& minThickness () const inline
Minimum overall thickness of cell layer. If for any reason layer.
cannot be above minThickness do not add layer. If relativeSize() this number is relative to undistorted size of the cell outside layer.
Definition at line 222 of file layerParameters.H.
Referenced by layerParameters::expansionRatio().
nLayerIter()
label nLayerIter () const inline
Number of overall layer addition iterations.
Definition at line 231 of file layerParameters.H.
References layerParameters::nRelaxedIter().
Referenced by snappyLayerDriver::addLayers().
nRelaxedIter()
label nRelaxedIter () const inline
Number of iterations after which relaxed motion rules.
are to be used.
Definition at line 238 of file layerParameters.H.
Referenced by snappyLayerDriver::addLayers(), and layerParameters::nLayerIter().
featureAngle()
scalar featureAngle () const inline
Definition at line 246 of file layerParameters.H.
Referenced by snappyLayerDriver::addLayers(), and snappyLayerDriver::mergePatchFacesUndo().
concaveAngle()
scalar concaveAngle () const inline
Definition at line 251 of file layerParameters.H.
References layerParameters::nGrow().
Referenced by snappyLayerDriver::mergePatchFacesUndo().
nGrow()
label nGrow () const inline
If points get not extruded do nGrow layers of connected faces.
that are not grown. Is used to not do layers at all close to features.
Definition at line 259 of file layerParameters.H.
Referenced by snappyLayerDriver::addLayers(), and layerParameters::concaveAngle().
maxFaceThicknessRatio()
scalar maxFaceThicknessRatio () const inline
Stop layer growth on highly warped cells.
Definition at line 265 of file layerParameters.H.
Referenced by snappyLayerDriver::addLayers().
nBufferCellsNoExtrude()
label nBufferCellsNoExtrude () const inline
Create buffer region for new layer terminations.
Definition at line 271 of file layerParameters.H.
Referenced by snappyLayerDriver::addLayers().
additionalReporting()
const Switch& additionalReporting () const inline
Definition at line 276 of file layerParameters.H.
Referenced by snappyLayerDriver::addLayers().
meshShrinker()
const word& meshShrinker () const inline
Type of mesh shrinker.
Definition at line 282 of file layerParameters.H.
References layerParameters::expansionRatio(), layerParameters::finalLayerThicknessRatio(), layerParameters::firstLayerThickness(), and layerParameters::layerThickness().
Referenced by snappyLayerDriver::addLayers().
layerThickness()
Foam::scalar layerThickness (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine overall thickness. Uses two of the four parameters.
according to the layerSpecification
Definition at line 372 of file layerParameters.C.
References Foam::exit(), layerParameters::expansionRatio(), Foam::FatalError, FatalErrorInFunction, layerParameters::FINAL_AND_EXPANSION, layerParameters::FINAL_AND_TOTAL, layerParameters::FIRST_AND_EXPANSION, layerParameters::FIRST_AND_TOTAL, Foam::mag(), Foam::pow(), and layerParameters::TOTAL_AND_EXPANSION.
Referenced by layerParameters::layerParameters(), and layerParameters::meshShrinker().
layerExpansionRatio()
Foam::scalar layerExpansionRatio (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine expansion ratio. Uses two of the four parameters.
according to the layerSpecification
Definition at line 432 of file layerParameters.C.
References Foam::exit(), layerParameters::expansionRatio(), Foam::FatalError, FatalErrorInFunction, layerParameters::FINAL_AND_EXPANSION, layerParameters::FINAL_AND_TOTAL, layerParameters::FIRST_AND_EXPANSION, layerParameters::FIRST_AND_TOTAL, layerParameters::firstLayerThickness(), and layerParameters::TOTAL_AND_EXPANSION.
firstLayerThickness() [2/2]
Foam::scalar firstLayerThickness (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine first layer (near-wall) thickness. Uses two of the.
four parameters according to the layerSpecification
Definition at line 483 of file layerParameters.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, layerParameters::FINAL_AND_EXPANSION, layerParameters::FINAL_AND_TOTAL, layerParameters::finalLayerThicknessRatio(), layerParameters::FIRST_AND_EXPANSION, layerParameters::FIRST_AND_TOTAL, Foam::pow(), and layerParameters::TOTAL_AND_EXPANSION.
finalLayerThicknessRatio()
Foam::scalar finalLayerThicknessRatio (const label nLayers, const scalar expansionRatio) const
Determine ratio of final layer thickness to.
overall layer thickness
Definition at line 542 of file layerParameters.C.
References layerParameters::expansionRatio(), Foam::mag(), and Foam::pow().
Referenced by snappyLayerDriver::addLayers(), layerParameters::firstLayerThickness(), and layerParameters::meshShrinker().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/layerParameters/layerParameters.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/layerParameters/layerParameters.C