OpenFOAM: surfaceZonesInfo Class Reference
surfaceZonesInfo Class Reference
Public Types
enum areaSelectionAlgo { INSIDE, OUTSIDE, INSIDEPOINT, NONE }
Types of selection of area.
enum faceZoneType { INTERNAL, BAFFLE, BOUNDARY }
What to do with faceZone faces.
Public Member Functions
surfaceZonesInfo (const searchableSurface &surface, const dictionary &surfacesDict)
Construct from surfaces and dictionary.
surfaceZonesInfo (const word &faceZoneNames, const word &cellZoneNames, const areaSelectionAlgo &zoneInside, const point &zoneInsidePoints, const faceZoneType &faceType)
Construct from components.
surfaceZonesInfo (const surfaceZonesInfo &)
Copy constructor.
autoPtr< surfaceZonesInfo > clone () const
Return clone.
const word & faceZoneName () const
Per 'interface' surface : empty or name of faceZone to put.
const word & cellZoneName () const
Per 'interface' surface : empty or name of cellZone to put.
const areaSelectionAlgo & zoneInside () const
const point & zoneInsidePoint () const
Get specified inside locations for surfaces with a cellZone.
const faceZoneType & faceType () const
How to handle face of surfaces with a faceZone.
Static Public Member Functions
static labelList getUnnamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
Get indices of unnamed surfaces (surfaces without faceZoneName)
static labelList getNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
Get indices of named surfaces (surfaces with faceZoneName)
static labelList getClosedNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList, const searchableSurfaces &allGeometry, const labelList &surfaces)
Get indices of surfaces with a cellZone that are closed and.
static labelList getUnclosedNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList, const searchableSurfaces &allGeometry, const labelList &surfaces)
Get indices of surfaces with a cellZone that are unclosed.
static labelList getAllClosedNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList, const searchableSurfaces &allGeometry, const labelList &surfaces)
Get indices of surfaces with a cellZone that are closed.
static labelList getInsidePointNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
Get indices of surfaces with a cellZone that have 'insidePoint'.
static labelList addCellZonesToMesh (const PtrList< surfaceZonesInfo > &surfList, const labelList &namedSurfaces, polyMesh &mesh)
static labelList addFaceZonesToMesh (const PtrList< surfaceZonesInfo > &surfList, const labelList &namedSurfaces, polyMesh &mesh)
Static Public Attributes
static const NamedEnum< areaSelectionAlgo, 4 > areaSelectionAlgoNames
static const NamedEnum< faceZoneType, 3 > faceZoneTypeNames
Detailed Description
Source files
surfaceZonesInfo.H
surfaceZonesInfo.C
Definition at line 56 of file surfaceZonesInfo.H.
Member Enumeration Documentation
areaSelectionAlgo
enum areaSelectionAlgo
Types of selection of area.
Enumerator
INSIDE
OUTSIDE
INSIDEPOINT
NONE
Definition at line 61 of file surfaceZonesInfo.H.
faceZoneType
enum faceZoneType
What to do with faceZone faces.
Enumerator
INTERNAL
BAFFLE
BOUNDARY
Definition at line 72 of file surfaceZonesInfo.H.
Constructor & Destructor Documentation
surfaceZonesInfo() [1/3]
surfaceZonesInfo (const searchableSurface & surface, const dictionary & surfacesDict)
Construct from surfaces and dictionary.
Definition at line 74 of file surfaceZonesInfo.C.
References Foam::endl(), searchableSurface::hasVolumeType(), IOWarningInFunction, dictionary::lookup(), and dictionary::readIfPresent().
Referenced by surfaceZonesInfo::clone(), and NamedEnum< directionType, 3 >::names().
surfaceZonesInfo() [2/3]
surfaceZonesInfo (const word & faceZoneNames, const word & cellZoneNames, const areaSelectionAlgo & zoneInside, const point & zoneInsidePoints, const faceZoneType & faceType)
Construct from components.
Definition at line 157 of file surfaceZonesInfo.C.
surfaceZonesInfo() [3/3]
surfaceZonesInfo (const surfaceZonesInfo & surfZone)
Copy constructor.
Definition at line 173 of file surfaceZonesInfo.C.
References surfaceZonesInfo::getUnnamedSurfaces().
Member Function Documentation
clone()
autoPtr<surfaceZonesInfo> clone () const inline
Return clone.
Definition at line 136 of file surfaceZonesInfo.H.
References surfaceZonesInfo::cellZoneName(), surfaceZonesInfo::faceZoneName(), and surfaceZonesInfo::surfaceZonesInfo().
faceZoneName()
const word& faceZoneName () const inline
Per 'interface' surface : empty or name of faceZone to put.
faces into
Definition at line 148 of file surfaceZonesInfo.H.
Referenced by surfaceZonesInfo::clone(), and surfaceZonesInfo::getUnnamedSurfaces().
cellZoneName()
const word& cellZoneName () const inline
Per 'interface' surface : empty or name of cellZone to put.
cells into
Definition at line 155 of file surfaceZonesInfo.H.
Referenced by surfaceZonesInfo::clone().
zoneInside()
const areaSelectionAlgo& zoneInside () const inline
Definition at line 160 of file surfaceZonesInfo.H.
zoneInsidePoint()
const point& zoneInsidePoint () const inline
Get specified inside locations for surfaces with a cellZone.
Definition at line 166 of file surfaceZonesInfo.H.
faceType()
const faceZoneType& faceType () const inline
How to handle face of surfaces with a faceZone.
Definition at line 172 of file surfaceZonesInfo.H.
References surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), surfaceZonesInfo::getAllClosedNamedSurfaces(), surfaceZonesInfo::getClosedNamedSurfaces(), surfaceZonesInfo::getInsidePointNamedSurfaces(), surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnclosedNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), and mesh.
getUnnamedSurfaces()
Foam::labelList getUnnamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Get indices of unnamed surfaces (surfaces without faceZoneName)
Definition at line 184 of file surfaceZonesInfo.C.
References surfaceZonesInfo::faceZoneName(), forAll, surfaceZonesInfo::getNamedSurfaces(), and UPtrList< T >::size().
Referenced by snappySnapDriver::calcNearestSurface(), snappySnapDriver::detectNearSurfaces(), surfaceZonesInfo::faceType(), listPlusEqOp< T >::operator()(), snappySnapDriver::repatchToSurface(), and surfaceZonesInfo::surfaceZonesInfo().
getNamedSurfaces()
Foam::labelList getNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Get indices of named surfaces (surfaces with faceZoneName)
Definition at line 205 of file surfaceZonesInfo.C.
References forAll, surfaceZonesInfo::getClosedNamedSurfaces(), PtrList< T >::set(), and UPtrList< T >::size().
Referenced by snappySnapDriver::calcNearestSurface(), meshRefinement::createZoneBaffles(), snappySnapDriver::detectNearSurfaces(), surfaceZonesInfo::faceType(), surfaceZonesInfo::getUnnamedSurfaces(), snappySnapDriver::mergeZoneBaffles(), listPlusEqOp< T >::operator()(), snappySnapDriver::repatchToSurface(), snappyRefineDriver::snappyRefineDriver(), and meshRefinement::zonify().
getClosedNamedSurfaces()
Foam::labelList getClosedNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList, const searchableSurfaces & allGeometry, const labelList & surfaces) static
Get indices of surfaces with a cellZone that are closed and.
have 'inside' or 'outside' selection.
Definition at line 230 of file surfaceZonesInfo.C.
References forAll, surfaceZonesInfo::getUnclosedNamedSurfaces(), surfaceZonesInfo::INSIDE, surfaceZonesInfo::OUTSIDE, PtrList< T >::set(), and UPtrList< T >::size().
Referenced by surfaceZonesInfo::faceType(), surfaceZonesInfo::getNamedSurfaces(), and meshRefinement::zonify().
getUnclosedNamedSurfaces()
Foam::labelList getUnclosedNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList, const searchableSurfaces & allGeometry, const labelList & surfaces) static
Get indices of surfaces with a cellZone that are unclosed.
Definition at line 262 of file surfaceZonesInfo.C.
References forAll, surfaceZonesInfo::getAllClosedNamedSurfaces(), PtrList< T >::set(), and UPtrList< T >::size().
Referenced by surfaceZonesInfo::faceType(), and surfaceZonesInfo::getClosedNamedSurfaces().
getAllClosedNamedSurfaces()
Foam::labelList getAllClosedNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList, const searchableSurfaces & allGeometry, const labelList & surfaces) static
Get indices of surfaces with a cellZone that are closed.
Definition at line 289 of file surfaceZonesInfo.C.
References forAll, surfaceZonesInfo::getInsidePointNamedSurfaces(), PtrList< T >::set(), and UPtrList< T >::size().
Referenced by surfaceZonesInfo::faceType(), and surfaceZonesInfo::getUnclosedNamedSurfaces().
getInsidePointNamedSurfaces()
Foam::labelList getInsidePointNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Get indices of surfaces with a cellZone that have 'insidePoint'.
section.
Definition at line 317 of file surfaceZonesInfo.C.
References surfaceZonesInfo::addCellZonesToMesh(), forAll, surfaceZonesInfo::INSIDEPOINT, PtrList< T >::set(), and UPtrList< T >::size().
Referenced by surfaceZonesInfo::faceType(), surfaceZonesInfo::getAllClosedNamedSurfaces(), and meshRefinement::zonify().
addCellZonesToMesh()
Foam::labelList addCellZonesToMesh (const PtrList< surfaceZonesInfo > & surfList, const labelList & namedSurfaces, polyMesh & mesh) static
Definition at line 343 of file surfaceZonesInfo.C.
References surfaceZonesInfo::addFaceZonesToMesh(), polyMesh::cellZones(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Pstream::gatherList(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), word::null, Pstream::scatterList(), List< T >::size(), and UPtrList< T >::size().
Referenced by surfaceZonesInfo::faceType(), surfaceZonesInfo::getInsidePointNamedSurfaces(), and meshRefinement::zonify().
addFaceZonesToMesh()
Foam::labelList addFaceZonesToMesh (const PtrList< surfaceZonesInfo > & surfList, const labelList & namedSurfaces, polyMesh & mesh) static
Definition at line 408 of file surfaceZonesInfo.C.
References Foam::exit(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, forAll, Pstream::gatherList(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), Pstream::scatterList(), List< T >::size(), and UPtrList< T >::size().
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::faceType(), and meshRefinement::zonify().
Member Data Documentation
areaSelectionAlgoNames
const Foam::NamedEnum< Foam::surfaceZonesInfo::areaSelectionAlgo, 4 > areaSelectionAlgoNames static
Definition at line 69 of file surfaceZonesInfo.H.
Referenced by NamedEnum< directionType, 3 >::names().
faceZoneTypeNames
const Foam::NamedEnum< Foam::surfaceZonesInfo::faceZoneType, 3 > faceZoneTypeNames static
Definition at line 79 of file surfaceZonesInfo.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/refinementSurfaces/surfaceZonesInfo.H
src/mesh/snappyHexMesh/refinementSurfaces/surfaceZonesInfo.C