OpenFOAM: refinementFeatures Class Reference
refinementFeatures Class Reference
Encapsulates queries for features.
Public Member Functions
refinementFeatures (const objectRegistry &io, const PtrList< dictionary > &featDicts)
Construct from description.
const labelListList & levels () const
Per featureEdgeMesh the list of level.
const List< scalarField > & distances () const
Per featureEdgeMesh the list of ranges.
scalar maxDistance () const
Highest distance of all features.
void findNearestEdge (const pointField &samples, const scalarField &nearestDistSqr, labelList &nearFeature, List< pointIndexHit > &nearInfo, vectorField &nearNormal) const
Find nearest point on nearest feature edge. Sets:
void findNearestRegionEdge (const pointField &samples, const scalarField &nearestDistSqr, labelList &nearFeature, List< pointIndexHit > &nearInfo, vectorField &nearNormal) const
Find nearest point on nearest region edge. Sets:
void findNearestPoint (const pointField &samples, const scalarField &nearestDistSqr, labelList &nearFeature, List< pointIndexHit > &nearInfo) const
Find nearest feature point. Sets:
void findHigherLevel (const pointField &pt, const labelList &ptLevel, labelList &maxLevel) const
Find shell level higher than ptLevel.
Public Member Functions inherited from PtrList< extendedFeatureEdgeMesh >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< extendedFeatureEdgeMesh > &)
Copy constructor.
PtrList (const PtrList< extendedFeatureEdgeMesh > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< extendedFeatureEdgeMesh >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< extendedFeatureEdgeMesh > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< extendedFeatureEdgeMesh > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (extendedFeatureEdgeMesh *)
Append an element at the end of the list.
void append (const autoPtr< extendedFeatureEdgeMesh > &)
void append (const tmp< extendedFeatureEdgeMesh > &)
void transfer (PtrList< extendedFeatureEdgeMesh > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< extendedFeatureEdgeMesh > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< extendedFeatureEdgeMesh > set (const label, extendedFeatureEdgeMesh *)
Set element to given T* and return old element (can be nullptr)
autoPtr< extendedFeatureEdgeMesh > set (const label, const autoPtr< extendedFeatureEdgeMesh > &)
Set element to given autoPtr<T> and return old element.
autoPtr< extendedFeatureEdgeMesh > set (const label, const tmp< extendedFeatureEdgeMesh > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< extendedFeatureEdgeMesh > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Member Functions
const PtrList< indexedOctree< treeDataEdge > > & edgeTrees () const
const PtrList< indexedOctree< treeDataPoint > > & pointTrees () const
const PtrList< indexedOctree< treeDataEdge > > & regionEdgeTrees () const
Protected Member Functions inherited from PtrList< extendedFeatureEdgeMesh >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Detailed Description
Encapsulates queries for features.
Source files
refinementFeatures.H
refinementFeatures.C
Definition at line 51 of file refinementFeatures.H.
Constructor & Destructor Documentation
refinementFeatures()
refinementFeatures (const objectRegistry & io, const PtrList< dictionary > & featDicts)
Construct from description.
Definition at line 430 of file refinementFeatures.C.
References refinementFeatures::findNearestEdge(), and forAll.
Referenced by refinementFeatures::pointTrees(), and refinementFeatures::regionEdgeTrees().
Member Function Documentation
edgeTrees()
const PtrList<indexedOctree<treeDataEdge> >& edgeTrees () const inline protected
Definition at line 95 of file refinementFeatures.H.
pointTrees()
const PtrList<indexedOctree<treeDataPoint> >& pointTrees () const inline protected
Definition at line 100 of file refinementFeatures.H.
References refinementFeatures::refinementFeatures(), and refinementFeatures::regionEdgeTrees().
regionEdgeTrees()
const Foam::PtrList< Foam::indexedOctree< Foam::treeDataEdge > > & regionEdgeTrees () const protected
Definition at line 302 of file refinementFeatures.C.
References refinementFeatures::distances(), Foam::e, edgeMesh::edges(), treeBoundBox::extend(), Foam::findLower(), forAll, forAllReverse, refinementFeatures::levels(), Foam::mag(), boundBox::max(), boundBox::min(), UPtrList< T >::operator[](), edgeMesh::points(), refinementFeatures::refinementFeatures(), extendedEdgeMesh::regionEdges(), rndGen(), PtrList< T >::set(), List< T >::size(), UPtrList< T >::size(), and Foam::sqr().
Referenced by refinementFeatures::findNearestRegionEdge(), and refinementFeatures::pointTrees().
levels()
const labelListList& levels () const inline
Per featureEdgeMesh the list of level.
Definition at line 125 of file refinementFeatures.H.
Referenced by refinementFeatures::regionEdgeTrees().
distances()
const List<scalarField>& distances () const inline
Per featureEdgeMesh the list of ranges.
Definition at line 131 of file refinementFeatures.H.
References refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), refinementFeatures::maxDistance(), and samples().
Referenced by refinementFeatures::regionEdgeTrees().
maxDistance()
Foam::scalar maxDistance () const
Highest distance of all features.
Definition at line 766 of file refinementFeatures.C.
References forAll, and Foam::max().
Referenced by refinementFeatures::distances().
findNearestEdge()
void findNearestEdge (const pointField & samples, const scalarField & nearestDistSqr, labelList & nearFeature, List< pointIndexHit > & nearInfo, vectorField & nearNormal) const
Find nearest point on nearest feature edge. Sets:
nearFeature: index of feature mesh
nearInfo : location on feature edge and edge index (note: not feature edge index but index into edges() directly)
nearNormal : local feature edge normal
Definition at line 525 of file refinementFeatures.C.
References Foam::e, refinementFeatures::findNearestRegionEdge(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), Foam::mag(), Foam::magSqr(), List< T >::setSize(), indexedOctree< Type >::shapes(), List< T >::size(), edge::vec(), and Foam::Zero.
Referenced by refinementFeatures::distances(), listPlusEqOp< T >::operator()(), and refinementFeatures::refinementFeatures().
findNearestRegionEdge()
void findNearestRegionEdge (const pointField & samples, const scalarField & nearestDistSqr, labelList & nearFeature, List< pointIndexHit > & nearInfo, vectorField & nearNormal) const
Find nearest point on nearest region edge. Sets:
nearFeature: index of feature mesh
nearInfo : location on feature edge and edge index (note: not feature edge index but index into edges() directly)
nearNormal : local feature edge normal
Definition at line 584 of file refinementFeatures.C.
References Foam::e, treeDataEdge::edges(), refinementFeatures::findNearestPoint(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), Foam::mag(), Foam::magSqr(), treeDataEdge::points(), refinementFeatures::regionEdgeTrees(), List< T >::setSize(), indexedOctree< Type >::shapes(), List< T >::size(), and Foam::Zero.
Referenced by refinementFeatures::distances(), refinementFeatures::findNearestEdge(), and listPlusEqOp< T >::operator()().
findNearestPoint()
void findNearestPoint (const pointField & samples, const scalarField & nearestDistSqr, labelList & nearFeature, List< pointIndexHit > & nearInfo) const
Find nearest feature point. Sets:
nearFeature: index of feature mesh
nearInfo : location on feature point and point index. (note: not index into shapes().pointLabels() but index into points() directly)
Definition at line 699 of file refinementFeatures.C.
References forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), Foam::magSqr(), List< T >::setSize(), indexedOctree< Type >::shapes(), and List< T >::size().
Referenced by refinementFeatures::distances(), refinementFeatures::findNearestRegionEdge(), and listPlusEqOp< T >::operator()().
findHigherLevel()
void findHigherLevel (const pointField & pt, const labelList & ptLevel, labelList & maxLevel) const
Find shell level higher than ptLevel.
Definition at line 750 of file refinementFeatures.C.
References forAll.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/refinementFeatures/refinementFeatures.H
src/mesh/snappyHexMesh/refinementFeatures/refinementFeatures.C