OpenFOAM: extrudeModel Class Reference
extrudeModel Class Reference abstract
Top level extrusion model class.
Public Member Functions
TypeName ("extrudeModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, extrudeModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
extrudeModel (const word &modelType, const dictionary &)
Construct from dictionary.
virtual ~extrudeModel ()
Destructor.
label nLayers () const
scalar expansionRatio () const
scalar sumThickness (const label layer) const
Helper: calculate cumulative relative thickness for layer.
virtual point operator() (const point &surfacePoint, const vector &surfaceNormal, const label layer) const =0
Static Public Member Functions
static autoPtr< extrudeModel > New (const dictionary &)
Select null constructed.
Protected Member Functions
extrudeModel (const extrudeModel &)
Disallow default bitwise copy construct.
void operator= (const extrudeModel &)
Disallow default bitwise assignment.
Protected Attributes
label nLayers_
const scalar expansionRatio_
const dictionary & dict_
const dictionary & coeffDict_
Detailed Description
Top level extrusion model class.
Source files
extrudeModel.H
extrudeModel.C
Definition at line 51 of file extrudeModel.H.
Constructor & Destructor Documentation
extrudeModel() [1/2]
extrudeModel (const extrudeModel &) protected
Disallow default bitwise copy construct.
extrudeModel() [2/2]
extrudeModel (const word & modelType, const dictionary & dict)
Construct from dictionary.
Definition at line 39 of file extrudeModel.C.
~extrudeModel()
~extrudeModel () virtual
Destructor.
Definition at line 53 of file extrudeModel.C.
Member Function Documentation
operator=()
void operator= (const extrudeModel &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("extrudeModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , extrudeModel , dictionary , (const dictionary &dict) , (dict))
Declare runtime constructor selection table.
New()
Foam::autoPtr< Foam::extrudeModel > New (const dictionary & dict) static
Select null constructed.
Definition at line 31 of file extrudeModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
Referenced by extrudePatchMesh::extrudePatchMesh().
nLayers()
Foam::label nLayers () const
Definition at line 59 of file extrudeModel.C.
expansionRatio()
Foam::scalar expansionRatio () const
Definition at line 65 of file extrudeModel.C.
Referenced by sigmaRadial::sigmaRadial().
sumThickness()
Foam::scalar sumThickness (const label layer) const
Helper: calculate cumulative relative thickness for layer.
(layer=0 -> 0; layer=nLayers -> 1)
Definition at line 71 of file extrudeModel.C.
References Foam::mag(), and Foam::pow().
Referenced by linearNormal::linearNormal(), linearRadial::operator()(), linearDirection::operator()(), and sector::operator()().
operator()()
virtual point operator() (const point & surfacePoint, const vector & surfaceNormal, const label layer) const pure virtual
Implemented in sector, linearNormal, linearDirection, sigmaRadial, linearRadial, and radial.
Member Data Documentation
nLayers_
label nLayers_ protected
Definition at line 57 of file extrudeModel.H.
Referenced by linearNormal::linearNormal(), sigmaRadial::operator()(), sector::operator()(), plane::plane(), and wedge::wedge().
expansionRatio_
const scalar expansionRatio_ protected
Definition at line 59 of file extrudeModel.H.
dict_
const dictionary& dict_ protected
Definition at line 61 of file extrudeModel.H.
coeffDict_
const dictionary& coeffDict_ protected
Definition at line 63 of file extrudeModel.H.
Referenced by linearNormal::linearNormal().
The documentation for this class was generated from the following files:
src/mesh/extrudeModel/extrudeModel/extrudeModel.H
src/mesh/extrudeModel/extrudeModel/extrudeModel.C
src/mesh/extrudeModel/extrudeModel/extrudeModelNew.C