OpenFOAM: pointData Class Reference
pointData Class Reference
Variant of pointEdgePoint with some transported additional data. WIP - should be templated on data like wallDistData. Passive vector v_ is not a coordinate (so no enterDomain/leaveDomain transformation needed)
Public Member Functions
pointData ()
Construct null.
pointData (const point &origin, const scalar distSqr, const scalar s, const vector &v)
Construct from origin, distance.
pointData (const pointData &)
Construct as copy.
scalar s () const
const vector & v () const
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to origin.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const pointData &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on point.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const pointData &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updatePoint (const pointData &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const pointData &pointInfo, const scalar tol, TrackingData &td)
Influence of point on edge.
bool operator== (const pointData &) const
bool operator!= (const pointData &) const
Public Member Functions inherited from pointEdgePoint
pointEdgePoint ()
Construct null.
pointEdgePoint (const point &, const scalar)
Construct from origin, distance.
pointEdgePoint (const pointEdgePoint &)
Construct as copy.
const point & origin () const
scalar distSqr () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const pointEdgePoint &, const scalar tol, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
Convert origin to relative vector to leaving point.
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
Convert relative origin to absolute by adding entering point.
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to origin.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const pointEdgePoint &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on point.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updatePoint (const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const pointEdgePoint &pointInfo, const scalar tol, TrackingData &td)
Influence of point on edge.
template<class TrackingData >
bool equal (const pointEdgePoint &, TrackingData &td) const
Same (like operator==)
bool operator== (const pointEdgePoint &) const
bool operator!= (const pointEdgePoint &) const
Friends
Ostream & operator<< (Ostream &, const pointData &)
Istream & operator>> (Istream &, pointData &)
Detailed Description
Variant of pointEdgePoint with some transported additional data. WIP - should be templated on data like wallDistData. Passive vector v_ is not a coordinate (so no enterDomain/leaveDomain transformation needed)
Source files
pointData.H
pointDataI.H
pointData.C
Definition at line 61 of file pointData.H.
Constructor & Destructor Documentation
pointData() [1/3]
pointData () inline
Construct null.
Definition at line 32 of file pointDataI.H.
pointData() [2/3]
pointData (const point & origin, const scalar distSqr, const scalar s, const vector & v) inline
Construct from origin, distance.
Definition at line 42 of file pointDataI.H.
pointData() [3/3]
pointData (const pointData & wpt) inline
Construct as copy.
Definition at line 56 of file pointDataI.H.
Member Function Documentation
s()
Foam::scalar s () const inline
Definition at line 66 of file pointDataI.H.
Referenced by Foam::operator<<(), and pointData::operator==().
v()
const Foam::vector & v () const inline
Definition at line 72 of file pointDataI.H.
References pointData::transform().
Referenced by Foam::operator<<(), and pointData::operator==().
transform()
void transform (const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to origin.
Definition at line 80 of file pointDataI.H.
References Foam::transform(), pointEdgePoint::transform(), and pointData::updatePoint().
Referenced by pointData::v().
updatePoint() [1/3]
bool updatePoint (const polyMesh & mesh, const label pointi, const label edgeI, const pointData & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on point.
Definition at line 93 of file pointDataI.H.
References pointEdgePoint::updatePoint().
Referenced by pointData::transform(), and pointData::updatePoint().
updatePoint() [2/3]
bool updatePoint (const polyMesh & mesh, const label pointi, const pointData & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
Merge new and old info.
Definition at line 128 of file pointDataI.H.
References pointData::updatePoint(), and pointEdgePoint::updatePoint().
updatePoint() [3/3]
bool updatePoint (const pointData & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
No information about current position whatsoever.
Definition at line 162 of file pointDataI.H.
References pointData::updateEdge(), and pointEdgePoint::updatePoint().
updateEdge()
bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointi, const pointData & pointInfo, const scalar tol, TrackingData & td) inline
Influence of point on edge.
Definition at line 184 of file pointDataI.H.
References pointEdgePoint::updateEdge().
Referenced by pointData::updatePoint().
operator==()
bool operator== (const pointData & rhs) const inline
Definition at line 220 of file pointDataI.H.
References pointEdgePoint::operator==(), pointData::s(), and pointData::v().
operator!=()
bool operator!= (const pointData & rhs) const inline
Definition at line 230 of file pointDataI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const pointData &) friend
operator>>
Istream& operator>> (Istream & , pointData &) friend
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/pointData/pointData.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/pointData/pointDataI.H