OpenFOAM: transformOp< PrimitivePatchType, Type, TrackingData > Class Template Reference
transformOp< PrimitivePatchType, Type, TrackingData > Class Template Reference
Transform operation.
Public Member Functions
transformOp (const polyMesh &mesh, const PrimitivePatchType &patch, const scalar tol, TrackingData &td)
void operator() (const vectorTensorTransform &vt, const bool forward, List< Type > &fld) const
Detailed Description
template<class PrimitivePatchType, class Type, class TrackingData = int>
class Foam::transformOp< PrimitivePatchType, Type, TrackingData >
Transform operation.
Definition at line 307 of file PatchEdgeFaceWave.H.
Constructor & Destructor Documentation
transformOp()
transformOp (const polyMesh & mesh, const PrimitivePatchType & patch, const scalar tol, TrackingData & td) inline
Definition at line 317 of file PatchEdgeFaceWave.H.
Member Function Documentation
operator()()
void operator() (const vectorTensorTransform & vt, const bool forward, List< Type > & fld) const inline
Definition at line 331 of file PatchEdgeFaceWave.H.
References fld(), forAll, vectorTensorTransform::R(), and Tensor< Cmpt >::T().
The documentation for this class was generated from the following file:
src/meshTools/algorithms/PatchEdgeFaceWave/PatchEdgeFaceWave.H