OpenFOAM: FaceCellWave< Type, TrackingData > Class Template Reference
FaceCellWave< Type, TrackingData > Class Template Reference
Wave propagation of information through grid. Every iteration information goes through one layer of cells. Templated on information that is transferred.
Public Member Functions
FaceCellWave (const polyMesh &, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, TrackingData &td=dummyTrackData_)
FaceCellWave (const polyMesh &, const labelList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
FaceCellWave (const polyMesh &, const labelPairList &explicitConnections, const bool handleCyclicAMI, const labelList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh and explicitly connected boundary faces.
virtual ~FaceCellWave ()
Destructor.
UList< Type > & allFaceInfo ()
Access allFaceInfo.
UList< Type > & allCellInfo ()
Access allCellInfo.
const TrackingData & data () const
Additional data to be passed into container.
const polyMesh & mesh () const
Access mesh.
label getUnsetCells () const
Get number of unvisited cells, i.e. cells that were not (yet)
label getUnsetFaces () const
Get number of unvisited faces.
void setFaceInfo (const labelList &changedFaces, const List< Type > &changedFacesInfo)
Set initial changed faces.
virtual label faceToCell ()
Propagate from face to cell. Returns total number of cells.
virtual label cellToFace ()
Propagate from cell to face. Returns total number of faces.
virtual label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
Static Public Member Functions
static scalar propagationTol ()
Access to tolerance.
static void setPropagationTol (const scalar tol)
Change tolerance.
Protected Member Functions
bool updateCell (const label celli, const label neighbourFacei, const Type &neighbourInfo, const scalar tol, Type &cellInfo)
Updates cellInfo with information from neighbour. Updates all.
bool updateFace (const label facei, const label neighbourCelli, const Type &neighbourInfo, const scalar tol, Type &faceInfo)
Updates faceInfo with information from neighbour. Updates all.
bool updateFace (const label facei, const Type &neighbourInfo, const scalar tol, Type &faceInfo)
Updates faceInfo with information from same face. Updates all.
void checkCyclic (const polyPatch &pPatch) const
Debugging: check info on both sides of cyclic.
template<class PatchType >
bool hasPatch () const
Has cyclic patch?
void mergeFaceInfo (const polyPatch &patch, const label nFaces, const labelList &, const List< Type > &)
Merge received patch data into global data.
label getChangedPatchFaces (const polyPatch &patch, const label startFacei, const label nFaces, labelList &changedPatchFaces, List< Type > &changedPatchFacesInfo) const
Extract info for single patch only.
void leaveDomain (const polyPatch &patch, const label nFaces, const labelList &faceLabels, List< Type > &faceInfo) const
Handle leaving domain. Implementation referred to Type.
void enterDomain (const polyPatch &patch, const label nFaces, const labelList &faceLabels, List< Type > &faceInfo) const
Handle leaving domain. Implementation referred to Type.
void transform (const tensorField &rotTensor, const label nFaces, List< Type > &faceInfo)
Apply transformation to Type.
void handleProcPatches ()
Merge data from across processor boundaries.
void handleCyclicPatches ()
Merge data from across cyclics.
void handleAMICyclicPatches ()
Merge data from across AMI cyclics.
void handleExplicitConnections ()
Merge data across explicitly provided local connections (usually.
Static Protected Member Functions
static void offset (const polyPatch &patch, const label off, const label nFaces, labelList &faces)
Offset face labels by constant value.
Protected Attributes
const polyMesh & mesh_
Reference to mesh.
const labelPairList explicitConnections_
Optional boundary faces that information should travel through.
UList< Type > & allFaceInfo_
Information for all faces.
UList< Type > & allCellInfo_
Information for all cells.
TrackingData & td_
Additional data to be passed into container.
PackedBoolList changedFace_
Has face changed.
DynamicList< label > changedFaces_
List of changed faces.
PackedBoolList changedCell_
Has cell changed.
DynamicList< label > changedCells_
const bool hasCyclicPatches_
Contains cyclics.
const bool hasCyclicAMIPatches_
Contains cyclicAMI.
label nEvals_
Number of evaluations.
label nUnvisitedCells_
Number of unvisited cells/faces.
label nUnvisitedFaces_
Static Protected Attributes
static const scalar geomTol_ = 1e-6
static scalar propagationTol_ = 0.01
static int dummyTrackData_ = 12345
Used as default trackdata value to satisfy default template.
Detailed Description
template<class Type, class TrackingData = int>
class Foam::FaceCellWave< Type, TrackingData >
Wave propagation of information through grid. Every iteration information goes through one layer of cells. Templated on information that is transferred.
Handles parallel and cyclics and non-parallel cyclics.
Note: whether to propagate depends on the return value of Type::update which returns true (i.e. propagate) if the value changes by more than a certain tolerance. This tolerance can be very strict for normal face-cell and parallel cyclics (we use a value of 0.01 just to limit propagation of small changes) but for non-parallel cyclics this tolerance can be critical and if chosen too small can lead to non-convergence.
Source files
FaceCellWave.H
FaceCellWave.C
Definition at line 75 of file FaceCellWave.H.
Constructor & Destructor Documentation
FaceCellWave() [1/3]
FaceCellWave (const polyMesh & mesh, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, TrackingData & td = dummyTrackData_)
Definition at line 893 of file FaceCellWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UList< T >::size().
FaceCellWave() [2/3]
FaceCellWave (const polyMesh & mesh, const labelList & initialChangedFaces, const List< Type > & changedFacesInfo, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
for these faces. Iterates until nothing changes or maxIter reached. (maxIter can be 0)
Definition at line 938 of file FaceCellWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UList< T >::size().
FaceCellWave() [3/3]
FaceCellWave (const polyMesh & mesh, const labelPairList & explicitConnections, const bool handleCyclicAMI, const labelList & initialChangedFaces, const List< Type > & changedFacesInfo, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from mesh and explicitly connected boundary faces.
and list of changed faces with the Type for these faces. Iterates until nothing changes or maxIter reached. (maxIter can be 0)
Definition at line 1002 of file FaceCellWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UList< T >::size().
~FaceCellWave()
virtual ~FaceCellWave () inline virtual
Destructor.
Definition at line 318 of file FaceCellWave.H.
Member Function Documentation
updateCell()
bool updateCell (const label celli, const label neighbourFacei, const Type & neighbourInfo, const scalar tol, Type & cellInfo) protected
Updates cellInfo with information from neighbour. Updates all.
statistics.
Definition at line 111 of file FaceCellWave.C.
References FaceCellWave< Type, TrackingData >::updateFace().
Referenced by combine< Type, TrackingData >::operator()().
updateFace() [1/2]
bool updateFace (const label facei, const label neighbourCelli, const Type & neighbourInfo, const scalar tol, Type & faceInfo) protected
Updates faceInfo with information from neighbour. Updates all.
statistics.
Definition at line 160 of file FaceCellWave.C.
Referenced by FaceCellWave< Type, TrackingData >::updateCell().
updateFace() [2/2]
bool updateFace (const label facei, const Type & neighbourInfo, const scalar tol, Type & faceInfo) protected
Updates faceInfo with information from same face. Updates all.
statistics.
Definition at line 209 of file FaceCellWave.C.
References FaceCellWave< Type, TrackingData >::checkCyclic().
checkCyclic()
void checkCyclic (const polyPatch & pPatch) const protected
Debugging: check info on both sides of cyclic.
Definition at line 256 of file FaceCellWave.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and polyPatch::start().
Referenced by FaceCellWave< Type, TrackingData >::updateFace().
hasPatch()
bool hasPatch () const protected
Has cyclic patch?
Definition at line 302 of file FaceCellWave.C.
References forAll, patchi, and FaceCellWave< Type, TrackingData >::setFaceInfo().
mergeFaceInfo()
void mergeFaceInfo (const polyPatch & patch, const label nFaces, const labelList & changedFaces, const List< Type > & changedFacesInfo) protected
Merge received patch data into global data.
Definition at line 347 of file FaceCellWave.C.
References FaceCellWave< Type, TrackingData >::getChangedPatchFaces(), and polyPatch::start().
Referenced by FaceCellWave< Type, TrackingData >::setFaceInfo().
getChangedPatchFaces()
Foam::label getChangedPatchFaces (const polyPatch & patch, const label startFacei, const label nFaces, labelList & changedPatchFaces, List< Type > & changedPatchFacesInfo) const protected
Extract info for single patch only.
Definition at line 381 of file FaceCellWave.C.
References FaceCellWave< Type, TrackingData >::leaveDomain(), and polyPatch::start().
Referenced by FaceCellWave< Type, TrackingData >::mergeFaceInfo().
leaveDomain()
void leaveDomain (const polyPatch & patch, const label nFaces, const labelList & faceLabels, List< Type > & faceInfo) const protected
Handle leaving domain. Implementation referred to Type.
Definition at line 413 of file FaceCellWave.C.
References FaceCellWave< Type, TrackingData >::enterDomain(), and polyPatch::start().
Referenced by FaceCellWave< Type, TrackingData >::getChangedPatchFaces().
enterDomain()
void enterDomain (const polyPatch & patch, const label nFaces, const labelList & faceLabels, List< Type > & faceInfo) const protected
Handle leaving domain. Implementation referred to Type.
Definition at line 436 of file FaceCellWave.C.
References polyPatch::start(), and FaceCellWave< Type, TrackingData >::transform().
Referenced by FaceCellWave< Type, TrackingData >::leaveDomain().
offset()
void offset (const polyPatch & patch, const label off, const label nFaces, labelList & faces) static protected
Offset face labels by constant value.
Definition at line 488 of file FaceCellWave.C.
Referenced by FaceCellWave< Type, TrackingData >::transform().
transform()
void transform (const tensorField & rotTensor, const label nFaces, List< Type > & faceInfo) protected
Apply transformation to Type.
Definition at line 459 of file FaceCellWave.C.
References FaceCellWave< Type, TrackingData >::offset(), List< T >::size(), and Foam::T().
Referenced by FaceCellWave< Type, TrackingData >::enterDomain().
handleProcPatches()
void handleProcPatches () protected
Merge data from across processor boundaries.
Definition at line 506 of file FaceCellWave.C.
References Foam::endl(), PstreamBuffers::finishedSends(), forAll, coupledPolyPatch::forwardT(), patchIdentifier::name(), processorPolyPatch::neighbProcNo(), UPstream::nonBlocking, coupledPolyPatch::parallel(), patchi, Foam::Pout, globalMeshData::processorPatches(), List< T >::size(), and Foam::transform().
handleCyclicPatches()
void handleCyclicPatches () protected
Merge data from across cyclics.
Definition at line 626 of file FaceCellWave.C.
References polyPatch::boundaryMesh(), Foam::endl(), forAll, coupledPolyPatch::forwardT(), patchIdentifier::name(), coupledPolyPatch::parallel(), patchi, Foam::Pout, and Foam::transform().
handleAMICyclicPatches()
void handleAMICyclicPatches () protected
Merge data from across AMI cyclics.
Definition at line 712 of file FaceCellWave.C.
References cyclicAMIPolyPatch::applyLowWeightCorrection(), polyPatch::boundaryMesh(), polyPatch::faceCentres(), forAll, coupledPolyPatch::forwardT(), cyclicAMIPolyPatch::interpolate(), coupledPolyPatch::parallel(), patchi, polyPatch::patchInternalList(), polyPatch::patchSlice(), coupledPolyPatch::separated(), List< T >::size(), polyPatch::start(), and Foam::transform().
handleExplicitConnections()
void handleExplicitConnections () protected
Merge data across explicitly provided local connections (usually.
baffles)
Definition at line 817 of file FaceCellWave.C.
References f1, and forAll.
propagationTol()
static scalar propagationTol () inline static
Access to tolerance.
Definition at line 261 of file FaceCellWave.H.
References FaceCellWave< Type, TrackingData >::propagationTol_.
Referenced by combine< Type, TrackingData >::operator()().
setPropagationTol()
static void setPropagationTol (const scalar tol) inline static
Change tolerance.
Definition at line 267 of file FaceCellWave.H.
References FaceCellWave< Type, TrackingData >::allCellInfo(), and FaceCellWave< Type, TrackingData >::allFaceInfo().
allFaceInfo()
UList<Type>& allFaceInfo () inline
Access allFaceInfo.
Definition at line 327 of file FaceCellWave.H.
References FaceCellWave< Type, TrackingData >::allFaceInfo_.
Referenced by FaceCellWave< Type, TrackingData >::setPropagationTol().
allCellInfo()
UList<Type>& allCellInfo () inline
Access allCellInfo.
Definition at line 333 of file FaceCellWave.H.
References FaceCellWave< Type, TrackingData >::allCellInfo_.
Referenced by FaceCellWave< Type, TrackingData >::setPropagationTol().
data()
const TrackingData& data () const inline
Additional data to be passed into container.
Definition at line 339 of file FaceCellWave.H.
References FaceCellWave< Type, TrackingData >::td_.
Referenced by MeshWave< Type, TrackingData >::data(), structuredDecomp::decompose(), combine< Type, TrackingData >::operator()(), and Foam::fvc::sweep().
mesh()
const polyMesh& mesh () const inline
Access mesh.
Definition at line 345 of file FaceCellWave.H.
References FaceCellWave< Type, TrackingData >::cellToFace(), FaceCellWave< Type, TrackingData >::faceToCell(), FaceCellWave< Type, TrackingData >::getUnsetCells(), FaceCellWave< Type, TrackingData >::getUnsetFaces(), FaceCellWave< Type, TrackingData >::iterate(), FaceCellWave< Type, TrackingData >::mesh_, and FaceCellWave< Type, TrackingData >::setFaceInfo().
Referenced by combine< Type, TrackingData >::operator()().
getUnsetCells()
Foam::label getUnsetCells () const
Get number of unvisited cells, i.e. cells that were not (yet)
reached from walking across mesh. This can happen from
not enough iterations done
a disconnected mesh
a mesh without walls in it
Definition at line 1070 of file FaceCellWave.C.
Referenced by MeshWave< Type, TrackingData >::data(), and FaceCellWave< Type, TrackingData >::mesh().
getUnsetFaces()
Foam::label getUnsetFaces () const
Get number of unvisited faces.
Definition at line 1077 of file FaceCellWave.C.
Referenced by MeshWave< Type, TrackingData >::getUnsetFaces(), and FaceCellWave< Type, TrackingData >::mesh().
setFaceInfo()
void setFaceInfo (const labelList & changedFaces, const List< Type > & changedFacesInfo)
Set initial changed faces.
Definition at line 317 of file FaceCellWave.C.
References List< T >::append(), forAll, and FaceCellWave< Type, TrackingData >::mergeFaceInfo().
Referenced by hexRef8::consistentSlowRefinement(), FaceCellWave< Type, TrackingData >::hasPatch(), FaceCellWave< Type, TrackingData >::mesh(), Foam::fvc::spread(), and Foam::fvc::sweep().
faceToCell()
Foam::label faceToCell () virtual
Propagate from face to cell. Returns total number of cells.
(over all processors) changed.
Reimplemented in OppositeFaceCellWave< Type, TrackingData >.
Definition at line 1084 of file FaceCellWave.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, and Foam::reduce().
Referenced by FaceCellWave< Type, TrackingData >::mesh().
cellToFace()
Foam::label cellToFace () virtual
Propagate from cell to face. Returns total number of faces.
(over all processors) changed. (Faces on processorpatches are counted double)
Reimplemented in OppositeFaceCellWave< Type, TrackingData >.
Definition at line 1165 of file FaceCellWave.C.
References Foam::abort(), cells, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::parRun(), Foam::Pout, and Foam::reduce().
Referenced by FaceCellWave< Type, TrackingData >::mesh().
iterate()
Foam::label iterate (const label maxIter) virtual
Iterate until no changes or maxIter reached. Returns actual.
number of iterations.
Definition at line 1248 of file FaceCellWave.C.
References Foam::endl(), Foam::Info, Foam::nl, and UPstream::parRun().
Referenced by hexRef8::consistentSlowRefinement(), MeshWave< Type, TrackingData >::data(), FaceCellWave< Type, TrackingData >::mesh(), Foam::fvc::spread(), and Foam::fvc::sweep().
Member Data Documentation
mesh_
const polyMesh& mesh_ protected
Reference to mesh.
Definition at line 95 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::mesh().
explicitConnections_
const labelPairList explicitConnections_ protected
Optional boundary faces that information should travel through.
Definition at line 98 of file FaceCellWave.H.
allFaceInfo_
UList<Type>& allFaceInfo_ protected
Information for all faces.
Definition at line 101 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::allFaceInfo().
allCellInfo_
UList<Type>& allCellInfo_ protected
Information for all cells.
Definition at line 104 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::allCellInfo().
td_
TrackingData& td_ protected
Additional data to be passed into container.
Definition at line 107 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::data().
changedFace_
PackedBoolList changedFace_ protected
Has face changed.
Definition at line 110 of file FaceCellWave.H.
changedFaces_
DynamicList<label> changedFaces_ protected
List of changed faces.
Definition at line 113 of file FaceCellWave.H.
changedCell_
PackedBoolList changedCell_ protected
Has cell changed.
Definition at line 116 of file FaceCellWave.H.
changedCells_
DynamicList<label> changedCells_ protected
Definition at line 119 of file FaceCellWave.H.
hasCyclicPatches_
const bool hasCyclicPatches_ protected
Contains cyclics.
Definition at line 123 of file FaceCellWave.H.
hasCyclicAMIPatches_
const bool hasCyclicAMIPatches_ protected
Contains cyclicAMI.
Definition at line 126 of file FaceCellWave.H.
nEvals_
label nEvals_ protected
Number of evaluations.
Definition at line 129 of file FaceCellWave.H.
nUnvisitedCells_
label nUnvisitedCells_ protected
Number of unvisited cells/faces.
Definition at line 132 of file FaceCellWave.H.
nUnvisitedFaces_
label nUnvisitedFaces_ protected
Definition at line 133 of file FaceCellWave.H.
geomTol_
const Foam::scalar geomTol_ = 1e-6 static protected
Definition at line 248 of file FaceCellWave.H.
propagationTol_
Foam::scalar propagationTol_ = 0.01 static protected
Definition at line 249 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::propagationTol().
dummyTrackData_
int dummyTrackData_ = 12345 static protected
Used as default trackdata value to satisfy default template.
argument.
Definition at line 253 of file FaceCellWave.H.
The documentation for this class was generated from the following files:
src/meshTools/algorithms/MeshWave/FaceCellWave.H
src/meshTools/algorithms/MeshWave/FaceCellWave.C