OpenFOAM: refinementParameters Class Reference
refinementParameters Class Reference
Simple container to keep together refinement specific information.
Public Member Functions
refinementParameters (const dictionary &dict)
Construct from dictionary - new syntax.
label maxGlobalCells () const
Total number of cells.
label maxLocalCells () const
Per processor max number of cells.
label minRefineCells () const
When to stop refining.
scalar curvature () const
Curvature.
scalar planarAngle () const
Angle when two intersections are considered to be planar.
label nBufferLayers () const
Number of layers between different refinement levels.
const pointField & keepPoints () const
Areas to keep.
bool allowFreeStandingZoneFaces () const
Are zone faces allowed only inbetween different cell zones.
bool useTopologicalSnapDetection () const
Use old topology based problem-cell removal.
scalar maxLoadUnbalance () const
Allowed load unbalance.
bool handleSnapProblems () const
labelList findCells (const polyMesh &) const
Checks that cells are in mesh. Returns cells they are in.
Detailed Description
Simple container to keep together refinement specific information.
Source files
refinementParameters.H
refinementParameters.C
Definition at line 53 of file refinementParameters.H.
Constructor & Destructor Documentation
refinementParameters()
refinementParameters (const dictionary & dict)
Construct from dictionary - new syntax.
Definition at line 33 of file refinementParameters.C.
References Foam::cos(), Foam::degToRad(), dictionary::lookup(), and Foam::readScalar().
Member Function Documentation
maxGlobalCells()
label maxGlobalCells () const inline
Total number of cells.
Definition at line 113 of file refinementParameters.H.
Referenced by snappyRefineDriver::snappyRefineDriver().
maxLocalCells()
label maxLocalCells () const inline
Per processor max number of cells.
Definition at line 119 of file refinementParameters.H.
Referenced by snappyRefineDriver::snappyRefineDriver().
minRefineCells()
label minRefineCells () const inline
When to stop refining.
Definition at line 125 of file refinementParameters.H.
Referenced by snappyRefineDriver::snappyRefineDriver().
curvature()
scalar curvature () const inline
Curvature.
Definition at line 131 of file refinementParameters.H.
Referenced by snappyRefineDriver::snappyRefineDriver().
planarAngle()
scalar planarAngle () const inline
Angle when two intersections are considered to be planar.
Definition at line 137 of file refinementParameters.H.
Referenced by snappyRefineDriver::snappyRefineDriver().
nBufferLayers()
label nBufferLayers () const inline
Number of layers between different refinement levels.
Definition at line 143 of file refinementParameters.H.
Referenced by snappyRefineDriver::snappyRefineDriver().
keepPoints()
const pointField& keepPoints () const inline
Areas to keep.
Definition at line 149 of file refinementParameters.H.
References refinementParameters::allowFreeStandingZoneFaces(), and refinementParameters::useTopologicalSnapDetection().
Referenced by snappyRefineDriver::snappyRefineDriver().
allowFreeStandingZoneFaces()
bool allowFreeStandingZoneFaces () const inline
Are zone faces allowed only inbetween different cell zones.
or also just free standing?
Definition at line 156 of file refinementParameters.H.
Referenced by refinementParameters::keepPoints(), and snappyRefineDriver::snappyRefineDriver().
useTopologicalSnapDetection()
bool useTopologicalSnapDetection () const inline
Use old topology based problem-cell removal.
(cells with 8 points on surface)
Definition at line 163 of file refinementParameters.H.
Referenced by refinementParameters::keepPoints(), and snappyRefineDriver::snappyRefineDriver().
maxLoadUnbalance()
scalar maxLoadUnbalance () const inline
Allowed load unbalance.
Definition at line 169 of file refinementParameters.H.
Referenced by snappyRefineDriver::snappyRefineDriver().
handleSnapProblems()
bool handleSnapProblems () const inline
Definition at line 174 of file refinementParameters.H.
References refinementParameters::findCells().
findCells()
Foam::labelList findCells (const polyMesh & mesh) const
Checks that cells are in mesh. Returns cells they are in.
Definition at line 74 of file refinementParameters.C.
References polyMesh::bounds(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyMesh::findCell(), forAll, Foam::Info, primitiveMesh::nCells(), Foam::nl, Foam::reduce(), List< T >::size(), and polyMesh::tetBasePtIs().
Referenced by snappyRefineDriver::doRefine(), and refinementParameters::handleSnapProblems().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/refinementParameters/refinementParameters.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/refinementParameters/refinementParameters.C