OpenFOAM: trackedParticle::trackingData Class Reference
trackedParticle::trackingData Class Reference
Class used to pass tracking data to the trackToFace function.
Public Member Functions
trackingData (Cloud< trackedParticle > &cloud, labelList &maxLevel, List< PackedBoolList > &featureEdgeVisited)
Public Member Functions inherited from particle< Type >::TrackingData< Cloud< trackedParticle > >
TrackingData (Cloud< trackedParticle > &cloud)
Cloud< trackedParticle > & cloud ()
Return a reference to the cloud.
Public Attributes
labelList & maxLevel_
List< PackedBoolList > & featureEdgeVisited_
Public Attributes inherited from particle< Type >::TrackingData< Cloud< trackedParticle > >
bool switchProcessor
Flag to switch processor.
bool keepParticle
Flag to indicate whether to keep particle (false = delete)
Additional Inherited Members
Public Types inherited from particle< Type >::TrackingData< Cloud< trackedParticle > >
typedef Cloud< trackedParticle > cloudType
Detailed Description
Class used to pass tracking data to the trackToFace function.
Definition at line 87 of file trackedParticle.H.
Constructor & Destructor Documentation
trackingData()
trackingData (Cloud< trackedParticle > & cloud, labelList & maxLevel, List< PackedBoolList > & featureEdgeVisited) inline
Definition at line 101 of file trackedParticle.H.
References trackedParticle::end(), trackedParticle::i(), trackedParticle::j(), trackedParticle::k(), particle< Type >::mesh(), particle< Type >::position(), particle< Type >::readFields(), and trackedParticle::trackedParticle().
Member Data Documentation
maxLevel_
labelList& maxLevel_
Definition at line 93 of file trackedParticle.H.
Referenced by trackedParticle::move().
featureEdgeVisited_
List<PackedBoolList>& featureEdgeVisited_
Definition at line 95 of file trackedParticle.H.
Referenced by trackedParticle::correctAfterParallelTransfer().
The documentation for this class was generated from the following file:
src/mesh/snappyHexMesh/trackedParticle/trackedParticle.H