OpenFOAM: patchEdgeFaceRegions Class Reference
patchEdgeFaceRegions Class Reference
Transport of regions for use in PatchEdgeFaceWave.
Public Member Functions
patchEdgeFaceRegions ()
Construct null.
patchEdgeFaceRegions (const labelList &)
Construct from regions.
patchEdgeFaceRegions (const labelPair &)
Construct from regions (on edge)
const labelList & regions () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class Patch , class TrackingData >
void transform (const polyMesh &mesh, const Patch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
Apply rotation matrix.
template<class Patch , class TrackingData >
bool updateEdge (const polyMesh &mesh, const Patch &patch, const label edgeI, const label facei, const patchEdgeFaceRegions &faceInfo, const scalar tol, TrackingData &td)
Influence of face on edge.
template<class Patch , class TrackingData >
bool updateEdge (const polyMesh &mesh, const Patch &patch, const patchEdgeFaceRegions &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
New information for edge (from e.g. coupled edge)
template<class Patch , class TrackingData >
bool updateFace (const polyMesh &mesh, const Patch &patch, const label facei, const label edgeI, const patchEdgeFaceRegions &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on face.
template<class TrackingData >
bool equal (const patchEdgeFaceRegions &, TrackingData &) const
Same (like operator==)
bool operator== (const patchEdgeFaceRegions &) const
bool operator!= (const patchEdgeFaceRegions &) const
Friends
Ostream & operator<< (Ostream &, const patchEdgeFaceRegions &)
Istream & operator>> (Istream &, patchEdgeFaceRegions &)
Detailed Description
Transport of regions for use in PatchEdgeFaceWave.
Set element to -1 to denote blocked.
Source files
patchEdgeFaceRegions.H
patchEdgeFaceRegionsI.H
patchEdgeFaceRegions.C
Definition at line 66 of file patchEdgeFaceRegions.H.
Constructor & Destructor Documentation
patchEdgeFaceRegions() [1/3]
patchEdgeFaceRegions () inline
Construct null.
Definition at line 30 of file patchEdgeFaceRegionsI.H.
Referenced by patchEdgeFaceRegions::patchEdgeFaceRegions().
patchEdgeFaceRegions() [2/3]
patchEdgeFaceRegions (const labelList & regions) inline
Construct from regions.
Definition at line 35 of file patchEdgeFaceRegionsI.H.
References patchEdgeFaceRegions::patchEdgeFaceRegions().
patchEdgeFaceRegions() [3/3]
patchEdgeFaceRegions (const labelPair & regions) inline
Construct from regions (on edge)
Definition at line 44 of file patchEdgeFaceRegionsI.H.
Member Function Documentation
regions()
const Foam::labelList & regions () const inline
Definition at line 57 of file patchEdgeFaceRegionsI.H.
Referenced by patchEdgeFaceRegions::operator==().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 64 of file patchEdgeFaceRegionsI.H.
References Foam::findIndex(), Foam::labelMax, List< T >::size(), and patchEdgeFaceRegions::transform().
Referenced by patchEdgeFaceRegions::updateEdge(), and patchEdgeFaceRegions::updateFace().
transform()
void transform (const polyMesh & mesh, const Patch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Apply rotation matrix.
Definition at line 72 of file patchEdgeFaceRegionsI.H.
References patchEdgeFaceRegions::updateEdge().
Referenced by patchEdgeFaceRegions::valid().
updateEdge() [1/2]
bool updateEdge (const polyMesh & mesh, const Patch & patch, const label edgeI, const label facei, const patchEdgeFaceRegions & faceInfo, const scalar tol, TrackingData & td) inline
Influence of face on edge.
Definition at line 84 of file patchEdgeFaceRegionsI.H.
References Foam::abort(), Foam::e, f(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), Foam::findIndex(), edge::flip(), forAll, Foam::labelMax, List< T >::setSize(), edge::start(), and patchEdgeFaceRegions::valid().
Referenced by patchEdgeFaceRegions::transform().
updateEdge() [2/2]
bool updateEdge (const polyMesh & mesh, const Patch & patch, const patchEdgeFaceRegions & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
New information for edge (from e.g. coupled edge)
Definition at line 141 of file patchEdgeFaceRegionsI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), edge::flip(), forAll, Foam::labelMax, List< T >::setSize(), FixedList< T, Size >::size(), patchEdgeFaceRegions::updateFace(), and patchEdgeFaceRegions::valid().
updateFace()
bool updateFace (const polyMesh & mesh, const Patch & patch, const label facei, const label edgeI, const patchEdgeFaceRegions & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on face.
Definition at line 188 of file patchEdgeFaceRegionsI.H.
References Foam::abort(), Foam::e, patchEdgeFaceRegions::equal(), f(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), Foam::findIndex(), edge::flip(), Foam::labelMax, List< T >::setSize(), List< T >::size(), edge::start(), and patchEdgeFaceRegions::valid().
Referenced by patchEdgeFaceRegions::updateEdge().
equal()
bool equal (const patchEdgeFaceRegions & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 253 of file patchEdgeFaceRegionsI.H.
References patchEdgeFaceRegions::operator==().
Referenced by patchEdgeFaceRegions::updateFace().
operator==()
bool operator== (const patchEdgeFaceRegions & rhs) const inline
Definition at line 265 of file patchEdgeFaceRegionsI.H.
References patchEdgeFaceRegions::regions().
Referenced by patchEdgeFaceRegions::equal().
operator!=()
bool operator!= (const patchEdgeFaceRegions & rhs) const inline
Definition at line 274 of file patchEdgeFaceRegionsI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const patchEdgeFaceRegions &) friend
operator>>
Istream& operator>> (Istream & , patchEdgeFaceRegions &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegions.H
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegionsI.H