OpenFOAM: combine< Type, TrackingData > Class Template Reference
combine< Type, TrackingData > Class Template Reference
Public Member Functions
combine (FaceCellWave< Type, TrackingData > &solver, const cyclicAMIPolyPatch &patch)
void operator() (Type &x, const label facei, const Type &y, const scalar weight) const
Detailed Description
template<class Type, class TrackingData>
class Foam::combine< Type, TrackingData >
Definition at line 53 of file FaceCellWave.C.
Constructor & Destructor Documentation
combine()
combine (FaceCellWave< Type, TrackingData > & solver, const cyclicAMIPolyPatch & patch) inline
Definition at line 64 of file FaceCellWave.C.
Member Function Documentation
operator()()
void operator() (Type & x, const label facei, const Type & y, const scalar weight) const inline
Definition at line 75 of file FaceCellWave.C.
References FaceCellWave< Type, TrackingData >::data(), FaceCellWave< Type, TrackingData >::mesh(), cyclicAMIPolyPatch::neighbPatch(), cyclicAMIPolyPatch::owner(), FaceCellWave< Type, TrackingData >::propagationTol(), polyPatch::start(), FaceCellWave< Type, TrackingData >::updateCell(), and y.
The documentation for this class was generated from the following file:
src/meshTools/algorithms/MeshWave/FaceCellWave.C