OpenFOAM: snappyLayerDriver Class Reference
snappyLayerDriver Class Reference
All to do with adding layers.
Public Types
enum extrudeMode { NOEXTRUDE, EXTRUDE, EXTRUDEREMOVE }
Extrusion controls.
Public Member Functions
ClassName ("snappyLayerDriver")
Runtime type information.
snappyLayerDriver (meshRefinement &meshRefiner, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch)
Construct from components.
void mergePatchFacesUndo (const layerParameters &layerParams, const dictionary &motionDict)
Merge patch faces on same cell.
void addLayers (const layerParameters &layerParams, const dictionary &motionDict, const labelList &patchIDs, const label nAllowableErrors, decompositionMethod &decomposer, fvMeshDistribute &distributor)
Add cell layers.
void doLayers (const dictionary &shrinkDict, const dictionary &motionDict, const layerParameters &layerParams, const bool preBalance, decompositionMethod &decomposer, fvMeshDistribute &distributor)
Add layers according to the dictionary settings.
Detailed Description
All to do with adding layers.
Source files
snappyLayerDriver.H
snappyLayerDriver.C
Definition at line 57 of file snappyLayerDriver.H.
Member Enumeration Documentation
extrudeMode
enum extrudeMode
Extrusion controls.
Enumerator
NOEXTRUDE
Do not extrude. No layers added.
EXTRUDE
Extrude.
EXTRUDEREMOVE
Extrude but afterwards remove added faces locally
Definition at line 64 of file snappyLayerDriver.H.
Constructor & Destructor Documentation
snappyLayerDriver()
snappyLayerDriver (meshRefinement & meshRefiner, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch)
Construct from components.
Definition at line 2791 of file snappyLayerDriver.C.
References snappyLayerDriver::mergePatchFacesUndo().
Member Function Documentation
ClassName()
ClassName ("snappyLayerDriver")
Runtime type information.
mergePatchFacesUndo()
void mergePatchFacesUndo (const layerParameters & layerParams, const dictionary & motionDict)
Merge patch faces on same cell.
Definition at line 2806 of file snappyLayerDriver.C.
References snappyLayerDriver::addLayers(), layerParameters::concaveAngle(), Foam::cos(), Foam::degToRad(), Foam::endl(), layerParameters::featureAngle(), localPointRegion::findDuplicateFacePairs(), forAll, Foam::Info, and primitiveMesh::nFaces().
Referenced by snappyLayerDriver::snappyLayerDriver().
addLayers()
void addLayers (const layerParameters & layerParams, const dictionary & motionDict, const labelList & patchIDs, const label nAllowableErrors, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Add cell layers.
Definition at line 2858 of file snappyLayerDriver.C.
References layerParameters::additionalReporting(), polyMesh::boundaryMesh(), fvMesh::clearOut(), Foam::degToRad(), layerParameters::dict(), snappyLayerDriver::doLayers(), primitiveMesh::edges(), Foam::endl(), Foam::faceMap(), layerParameters::featureAngle(), layerParameters::finalLayerThicknessRatio(), forAll, addPatchCellLayer::globalEdgeFaces(), Foam::identity(), Foam::Info, Foam::inplaceReorder(), HashSet< Key, Hash >::insert(), IOobject::instance(), meshRefinement::LAYERINFO, Foam::mag(), polyTopoChange::makeMesh(), meshRefinement::makePatch(), layerParameters::maxFaceThicknessRatio(), dictionary::merge(), mesh, layerParameters::meshShrinker(), fvMesh::movePoints(), fvMesh::name(), IOobject::name(), layerParameters::nBufferCellsNoExtrude(), primitiveMesh::nCells(), MeshObject< polyMesh, UpdateableMeshObject, pointMesh >::New(), externalDisplacementMeshMover::New(), primitiveMesh::nFaces(), layerParameters::nGrow(), primitiveMesh::nInternalFaces(), layerParameters::nLayerIter(), IOobject::NO_READ, nPoints, layerParameters::nRelaxedIter(), layerParameters::numLayers(), VectorSpace< Vector< scalar >, scalar, 3 >::one, p, UPstream::parRun(), Time::path(), primitiveMesh::pointEdges(), polyMesh::points(), layerParameters::relativeSizes(), Foam::returnReduce(), motionSmootherAlgo::setDisplacement(), polyMesh::setInstance(), addPatchCellLayer::setRefinement(), List< T >::size(), UPtrList< T >::size(), HashTable< T, Key, Hash >::size(), dictionary::subDict(), fvMesh::time(), meshRefinement::updateList(), fvMesh::updateMesh(), addPatchCellLayer::updateMesh(), Ostream::write(), regIOobject::write(), fvMesh::write(), meshRefinement::writeLevel(), meshRefinement::WRITEMESH, and Foam::Zero.
Referenced by snappyLayerDriver::mergePatchFacesUndo().
doLayers()
void doLayers (const dictionary & shrinkDict, const dictionary & motionDict, const layerParameters & layerParams, const bool preBalance, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Add layers according to the dictionary settings.
Definition at line 3600 of file snappyLayerDriver.C.
References List< T >::append(), polyMesh::boundaryMesh(), motionSmootherAlgo::checkMesh(), polyPatch::coupled(), Foam::endl(), polyPatch::faceCells(), forAll, Foam::Info, patchIdentifier::name(), primitiveMesh::nCells(), primitiveMesh::nFaces(), layerParameters::numLayers(), UPstream::parRun(), patchi, Foam::returnReduce(), List< T >::size(), UPtrList< T >::size(), and WarningInFunction.
Referenced by snappyLayerDriver::addLayers().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyLayerDriver.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyLayerDriver.C
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyLayerDriverShrink.C
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyLayerDriverTemplates.C