OpenFOAM: combineEqOp< Type, TrackingData > Class Template Reference
combineEqOp< Type, TrackingData > Class Template Reference
Reduction class. If x and y are not equal assign value.
Public Member Functions
combineEqOp (TrackingData &td)
void operator() (Type &x, const Type &y) const
Detailed Description
template<class Type, class TrackingData>
class Foam::combineEqOp< Type, TrackingData >
Reduction class. If x and y are not equal assign value.
Definition at line 50 of file PointEdgeWave.C.
Constructor & Destructor Documentation
combineEqOp()
combineEqOp (TrackingData & td) inline
Definition at line 55 of file PointEdgeWave.C.
Member Function Documentation
operator()()
void operator() (Type & x, const Type & y) const inline
Definition at line 60 of file PointEdgeWave.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), patchIdentifier::name(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), List< T >::size(), Foam::T(), and y.
The documentation for this class was generated from the following file:
src/meshTools/algorithms/PointEdgeWave/PointEdgeWave.C