OpenFOAM: patchEdgeFaceInfo Class Reference
patchEdgeFaceInfo Class Reference
Public Member Functions
patchEdgeFaceInfo ()
Construct null.
patchEdgeFaceInfo (const point &, const scalar)
Construct from origin, distance.
patchEdgeFaceInfo (const patchEdgeFaceInfo &)
Construct as copy.
const point & origin () const
scalar distSqr () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
void transform (const polyMesh &mesh, const primitivePatch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
Apply rotation matrix.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const primitivePatch &patch, const label edgeI, const label facei, const patchEdgeFaceInfo &faceInfo, const scalar tol, TrackingData &td)
Influence of face on edge.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const primitivePatch &patch, const patchEdgeFaceInfo &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
New information for edge (from e.g. coupled edge)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const primitivePatch &patch, const label facei, const label edgeI, const patchEdgeFaceInfo &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on face.
template<class TrackingData >
bool equal (const patchEdgeFaceInfo &, TrackingData &td) const
Same (like operator==)
bool operator== (const patchEdgeFaceInfo &) const
bool operator!= (const patchEdgeFaceInfo &) const
Friends
Ostream & operator<< (Ostream &, const patchEdgeFaceInfo &)
Istream & operator>> (Istream &, patchEdgeFaceInfo &)
Detailed Description
Source files
patchEdgeFaceInfo.H
patchEdgeFaceInfoI.H
patchEdgeFaceInfo.C
Definition at line 67 of file patchEdgeFaceInfo.H.
Constructor & Destructor Documentation
patchEdgeFaceInfo() [1/3]
patchEdgeFaceInfo () inline
Construct null.
Definition at line 121 of file patchEdgeFaceInfoI.H.
patchEdgeFaceInfo() [2/3]
patchEdgeFaceInfo (const point & origin, const scalar distSqr) inline
Construct from origin, distance.
Definition at line 130 of file patchEdgeFaceInfoI.H.
patchEdgeFaceInfo() [3/3]
patchEdgeFaceInfo (const patchEdgeFaceInfo & wpt) inline
Construct as copy.
Definition at line 141 of file patchEdgeFaceInfoI.H.
Member Function Documentation
origin()
const Foam::point & origin () const inline
Definition at line 150 of file patchEdgeFaceInfoI.H.
Referenced by patchEdgeFaceInfo::operator==().
distSqr()
Foam::scalar distSqr () const inline
Definition at line 156 of file patchEdgeFaceInfoI.H.
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 163 of file patchEdgeFaceInfoI.H.
References VectorSpace< Vector< scalar >, scalar, 3 >::max, and patchEdgeFaceInfo::transform().
transform()
void transform (const polyMesh & mesh, const primitivePatch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Apply rotation matrix.
Definition at line 171 of file patchEdgeFaceInfoI.H.
References Foam::transform(), and patchEdgeFaceInfo::updateEdge().
Referenced by patchEdgeFaceInfo::valid().
updateEdge() [1/2]
bool updateEdge (const polyMesh & mesh, const primitivePatch & patch, const label edgeI, const label facei, const patchEdgeFaceInfo & faceInfo, const scalar tol, TrackingData & td) inline
Influence of face on edge.
Definition at line 185 of file patchEdgeFaceInfoI.H.
References Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), and PrimitivePatch< Face, FaceList, PointField, PointType >::points().
Referenced by patchEdgeFaceInfo::transform().
updateEdge() [2/2]
bool updateEdge (const polyMesh & mesh, const primitivePatch & patch, const patchEdgeFaceInfo & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
New information for edge (from e.g. coupled edge)
Definition at line 208 of file patchEdgeFaceInfoI.H.
References patchEdgeFaceInfo::updateFace().
updateFace()
bool updateFace (const polyMesh & mesh, const primitivePatch & patch, const label facei, const label edgeI, const patchEdgeFaceInfo & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on face.
Definition at line 223 of file patchEdgeFaceInfoI.H.
References patchEdgeFaceInfo::equal(), and PrimitivePatch< Face, FaceList, PointField, PointType >::faceCentres().
Referenced by patchEdgeFaceInfo::updateEdge().
equal()
bool equal (const patchEdgeFaceInfo & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 239 of file patchEdgeFaceInfoI.H.
References patchEdgeFaceInfo::operator==().
Referenced by patchEdgeFaceInfo::updateFace().
operator==()
bool operator== (const patchEdgeFaceInfo & rhs) const inline
Definition at line 251 of file patchEdgeFaceInfoI.H.
References patchEdgeFaceInfo::origin().
Referenced by patchEdgeFaceInfo::equal().
operator!=()
bool operator!= (const patchEdgeFaceInfo & rhs) const inline
Definition at line 260 of file patchEdgeFaceInfoI.H.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const patchEdgeFaceInfo &) friend
operator>>
Istream& operator>> (Istream & , patchEdgeFaceInfo &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceInfo.H
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceInfoI.H