OpenFOAM: snappyRefineDriver Class Reference
snappyRefineDriver Class Reference
Public Member Functions
ClassName ("snappyRefineDriver")
Runtime type information.
snappyRefineDriver (meshRefinement &meshRefiner, decompositionMethod &decomposer, fvMeshDistribute &distributor, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch)
Construct from components.
void doRefine (const dictionary &refineDict, const refinementParameters &refineParams, const snapParameters &snapParams, const bool prepareForSnapping, const dictionary &motionDict)
Do all the refinement.
Detailed Description
Source files
snappyRefineDriver.H
snappyRefineDriver.C
Definition at line 55 of file snappyRefineDriver.H.
Constructor & Destructor Documentation
snappyRefineDriver()
snappyRefineDriver (meshRefinement & meshRefiner, decompositionMethod & decomposer, fvMeshDistribute & distributor, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch)
Construct from components.
Definition at line 55 of file snappyRefineDriver.C.
References refinementParameters::allowFreeStandingZoneFaces(), polyMesh::boundaryMesh(), Foam::constant::universal::c, cells, primitiveMesh::cells(), meshRefinement::checkCoupledFaceZones(), HashTable< T, Key, Hash >::clear(), Foam::cos(), cpuTime::cpuTimeIncrement(), refinementParameters::curvature(), Foam::degToRad(), snappyRefineDriver::doRefine(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), localPointRegion::findDuplicateFacePairs(), Foam::findIndices(), UILList< LListBase, T >::first(), forAll, surfaceZonesInfo::getNamedSurfaces(), polyMesh::globalData(), Foam::Info, IOobject::instance(), refinementParameters::keepPoints(), Foam::max(), refinementParameters::maxGlobalCells(), refinementParameters::maxLoadUnbalance(), refinementParameters::maxLocalCells(), mesh, meshRefinement::MESH, refinementParameters::minRefineCells(), n, Foam::name(), refinementParameters::nBufferLayers(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, globalMeshData::nTotalCells(), patchi, polyBoundaryMesh::patchID(), Time::path(), refinementParameters::planarAngle(), Foam::Pout, Foam::reduce(), meshRefinement::REMOVE, Foam::returnReduce(), List< T >::setSize(), List< T >::size(), syncTools::swapBoundaryCellList(), fvMesh::time(), List< T >::transfer(), refinementParameters::useTopologicalSnapDetection(), Ostream::write(), regIOobject::write(), meshRefinement::writeLevel(), and meshRefinement::WRITEMESH.
Member Function Documentation
ClassName()
ClassName ("snappyRefineDriver")
Runtime type information.
doRefine()
void doRefine (const dictionary & refineDict, const refinementParameters & refineParams, const snapParameters & snapParams, const bool prepareForSnapping, const dictionary & motionDict)
Do all the refinement.
Definition at line 1132 of file snappyRefineDriver.C.
References Foam::endl(), refinementParameters::findCells(), Foam::Info, mesh, primitiveMesh::nCells(), Foam::nl, and UPstream::parRun().
Referenced by snappyRefineDriver::snappyRefineDriver().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyRefineDriver.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappyRefineDriver.C