OpenFOAM: AMIInterpolation< SourcePatch, TargetPatch > Class Template Reference
AMIInterpolation< SourcePatch, TargetPatch > Class Template Reference
Interpolation class dealing with transfer of data between two primitive patches with an arbitrary mesh interface (AMI).
Public Types
enum interpolationMethod { imDirect, imMapNearest, imFaceAreaWeight, imPartialFaceAreaWeight }
Enumeration specifying interpolation method.
typedef SourcePatch sourcePatchType
typedef TargetPatch targetPatchType
Public Member Functions
AMIInterpolation (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const faceAreaIntersect::triangulationMode &triMode, const bool requireMatch=true, const interpolationMethod &method=imFaceAreaWeight, const scalar lowWeightCorrection=-1, const bool reverseTarget=false)
Construct from components.
AMIInterpolation (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const faceAreaIntersect::triangulationMode &triMode, const bool requireMatch=true, const word &methodName=interpolationMethodToWord(imFaceAreaWeight), const scalar lowWeightCorrection=-1, const bool reverseTarget=false)
Construct from components.
AMIInterpolation (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const autoPtr< searchableSurface > &surf, const faceAreaIntersect::triangulationMode &triMode, const bool requireMatch=true, const interpolationMethod &method=imFaceAreaWeight, const scalar lowWeightCorrection=-1, const bool reverseTarget=false)
Construct from components, with projection surface.
AMIInterpolation (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const autoPtr< searchableSurface > &surf, const faceAreaIntersect::triangulationMode &triMode, const bool requireMatch=true, const word &methodName=interpolationMethodToWord(imFaceAreaWeight), const scalar lowWeightCorrection=-1, const bool reverseTarget=false)
Construct from components, with projection surface.
AMIInterpolation (const AMIInterpolation< SourcePatch, TargetPatch > &fineAMI, const labelList &sourceRestrictAddressing, const labelList &neighbourRestrictAddressing)
Construct from agglomeration of AMIInterpolation. Agglomeration.
~AMIInterpolation ()
Destructor.
label singlePatchProc () const
Set to -1, or the processor holding all faces (both sides) of.
scalar lowWeightCorrection () const
Threshold weight below which interpolation is deactivated.
bool applyLowWeightCorrection () const
Return true if employing a 'lowWeightCorrection'.
const scalarField & srcMagSf () const
Return const access to source patch face areas.
const labelListList & srcAddress () const
Return const access to source patch addressing.
const scalarListList & srcWeights () const
Return const access to source patch weights.
scalarListList & srcWeights ()
Return access to source patch weights.
const scalarField & srcWeightsSum () const
Return const access to normalisation factor of source.
scalarField & srcWeightsSum ()
Return access to normalisation factor of source.
const mapDistribute & srcMap () const
Source map pointer - valid only if singlePatchProc = -1.
const scalarField & tgtMagSf () const
Return const access to target patch face areas.
const labelListList & tgtAddress () const
Return const access to target patch addressing.
const scalarListList & tgtWeights () const
Return const access to target patch weights.
scalarListList & tgtWeights ()
Return access to target patch weights.
const scalarField & tgtWeightsSum () const
Return const access to normalisation factor of target.
scalarField & tgtWeightsSum ()
Return access to normalisation factor of target.
const mapDistribute & tgtMap () const
Target map pointer - valid only if singlePatchProc=-1.
void update (const SourcePatch &srcPatch, const TargetPatch &tgtPatch)
Update addressing and weights.
template<class Type , class CombineOp >
void interpolateToSource (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target to source with supplied op.
template<class Type , class CombineOp >
void interpolateToTarget (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source to target with supplied op.
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target to source with supplied op.
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type >> &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target tmp field to source with supplied op.
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source to target with supplied op.
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type >> &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source tmp field to target with supplied op.
template<class Type >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target to source.
template<class Type >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target tmp field.
template<class Type >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source to target.
template<class Type >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source tmp field.
label srcPointFace (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const vector &n, const label tgtFacei, point &tgtPoint) const
Return source patch face index of point on target patch face.
label tgtPointFace (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const vector &n, const label srcFacei, point &srcPoint) const
Return target patch face index of point on source patch face.
void writeFaceConnectivity (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const labelListList &srcAddress) const
Write face connectivity as OBJ file.
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type >> &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type >> &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues) const
Static Public Member Functions
static word interpolationMethodToWord (const interpolationMethod &method)
Convert interpolationMethod to word representation.
static interpolationMethod wordTointerpolationMethod (const word &method)
Convert word to interpolationMethod.
Detailed Description
template<class SourcePatch, class TargetPatch>
class Foam::AMIInterpolation< SourcePatch, TargetPatch >
Interpolation class dealing with transfer of data between two primitive patches with an arbitrary mesh interface (AMI).
Based on the algorithm given in:
Conservative interpolation between volume meshes by local Galerkin projection, Farrell PE and Maddison JR, 2011, Comput. Methods Appl. Mech Engrg, Volume 200, Issues 1-4, pp 89-100
Interpolation requires that the two patches should have opposite orientations (opposite normals). The 'reverseTarget' flag can be used to reverse the orientation of the target patch.
Source files
AMIInterpolation.H
AMIInterpolation.C
AMIInterpolationName.C
AMIInterpolationParallelOps.C
Definition at line 77 of file AMIInterpolation.H.
Member Typedef Documentation
sourcePatchType
typedef SourcePatch sourcePatchType
Definition at line 348 of file AMIInterpolation.H.
targetPatchType
typedef TargetPatch targetPatchType
Definition at line 351 of file AMIInterpolation.H.
Member Enumeration Documentation
interpolationMethod
enum interpolationMethod
Enumeration specifying interpolation method.
Enumerator
imDirect
imMapNearest
imFaceAreaWeight
imPartialFaceAreaWeight
Definition at line 86 of file AMIInterpolation.H.
Constructor & Destructor Documentation
AMIInterpolation() [1/5]
AMIInterpolation (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const faceAreaIntersect::triangulationMode & triMode, const bool requireMatch = true, const interpolationMethod & method = imFaceAreaWeight, const scalar lowWeightCorrection = -1, const bool reverseTarget = false)
Construct from components.
Definition at line 588 of file AMIInterpolation.C.
AMIInterpolation() [2/5]
AMIInterpolation (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const faceAreaIntersect::triangulationMode & triMode, const bool requireMatch = true, const word & methodName = interpolationMethodToWord(imFaceAreaWeight), const scalar lowWeightCorrection = -1, const bool reverseTarget = false)
Construct from components.
Definition at line 619 of file AMIInterpolation.C.
AMIInterpolation() [3/5]
AMIInterpolation (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const autoPtr< searchableSurface > & surf, const faceAreaIntersect::triangulationMode & triMode, const bool requireMatch = true, const interpolationMethod & method = imFaceAreaWeight, const scalar lowWeightCorrection = -1, const bool reverseTarget = false)
Construct from components, with projection surface.
Definition at line 650 of file AMIInterpolation.C.
AMIInterpolation() [4/5]
AMIInterpolation (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const autoPtr< searchableSurface > & surf, const faceAreaIntersect::triangulationMode & triMode, const bool requireMatch = true, const word & methodName = interpolationMethodToWord(imFaceAreaWeight), const scalar lowWeightCorrection = -1, const bool reverseTarget = false)
Construct from components, with projection surface.
Definition at line 682 of file AMIInterpolation.C.
AMIInterpolation() [5/5]
AMIInterpolation (const AMIInterpolation< SourcePatch, TargetPatch > & fineAMI, const labelList & sourceRestrictAddressing, const labelList & neighbourRestrictAddressing)
Construct from agglomeration of AMIInterpolation. Agglomeration.
passed in as new coarse size and addressing from fine from coarse
Definition at line 714 of file AMIInterpolation.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), Foam::nl, Foam::Pout, List< T >::size(), AMIInterpolation< SourcePatch, TargetPatch >::srcAddress(), AMIInterpolation< SourcePatch, TargetPatch >::srcMagSf(), AMIInterpolation< SourcePatch, TargetPatch >::srcWeights(), AMIInterpolation< SourcePatch, TargetPatch >::tgtAddress(), AMIInterpolation< SourcePatch, TargetPatch >::tgtMagSf(), and AMIInterpolation< SourcePatch, TargetPatch >::tgtWeights().
~AMIInterpolation()
~AMIInterpolation ()
Destructor.
Definition at line 818 of file AMIInterpolation.C.
References AMIInterpolation< SourcePatch, TargetPatch >::update().
Member Function Documentation
interpolationMethodToWord()
Foam::word interpolationMethodToWord (const interpolationMethod & method) static
Convert interpolationMethod to word representation.
Definition at line 37 of file AMIInterpolation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod().
Referenced by meshToMesh::meshToMesh().
wordTointerpolationMethod()
Foam::AMIInterpolation< SourcePatch, TargetPatch >::interpolationMethod wordTointerpolationMethod (const word & method) static
Convert word to interpolationMethod.
Definition at line 80 of file AMIInterpolation.C.
References Foam::abort(), List< T >::append(), mapDistributeBase::constructMap(), mapDistributeBase::constructSize(), mapDistribute::distribute(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), searchableSurface::findNearest(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), Foam::identity(), Foam::indent(), Foam::Info, Foam::labelMin, Foam::max(), Foam::constant::mathematical::pi(), autoPtr< T >::reset(), Foam::returnReduce(), s(), scalarField(), List< T >::setSize(), List< T >::size(), mapDistributeBase::subMap(), Foam::sum(), autoPtr< T >::valid(), Foam::meshTools::writeOBJ(), and List< T >::xfer().
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::interpolationMethodToWord().
singlePatchProc()
Foam::label singlePatchProc () const inline
Set to -1, or the processor holding all faces (both sides) of.
the AMI
Definition at line 28 of file AMIInterpolationI.H.
lowWeightCorrection()
Foam::scalar lowWeightCorrection () const inline
Threshold weight below which interpolation is deactivated.
Definition at line 36 of file AMIInterpolationI.H.
References AMIInterpolation< SourcePatch, TargetPatch >::applyLowWeightCorrection().
applyLowWeightCorrection()
bool applyLowWeightCorrection () const inline
Return true if employing a 'lowWeightCorrection'.
Definition at line 45 of file AMIInterpolationI.H.
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::lowWeightCorrection().
srcMagSf()
const Foam::scalarField & srcMagSf () const inline
Return const access to source patch face areas.
Definition at line 53 of file AMIInterpolationI.H.
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::AMIInterpolation().
srcAddress()
const Foam::labelListList & srcAddress () const inline
Return const access to source patch addressing.
Definition at line 61 of file AMIInterpolationI.H.
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::AMIInterpolation().
srcWeights() [1/2]
const Foam::scalarListList & srcWeights () const inline
Return const access to source patch weights.
Definition at line 69 of file AMIInterpolationI.H.
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::AMIInterpolation(), and cyclicACMIPolyPatch::resetAMI().
srcWeights() [2/2]
Foam::scalarListList & srcWeights () inline
Return access to source patch weights.
Definition at line 77 of file AMIInterpolationI.H.
srcWeightsSum() [1/2]
const Foam::scalarField & srcWeightsSum () const inline
Return const access to normalisation factor of source.
patch weights (i.e. the sum before normalisation)
Definition at line 85 of file AMIInterpolationI.H.
Referenced by cyclicACMIPolyPatch::resetAMI().
srcWeightsSum() [2/2]
Foam::scalarField & srcWeightsSum () inline
Return access to normalisation factor of source.
patch weights (i.e. the sum before normalisation)
Definition at line 93 of file AMIInterpolationI.H.
srcMap()
const Foam::mapDistribute & srcMap () const inline
Source map pointer - valid only if singlePatchProc = -1.
This gets source data into a form to be consumed by tgtAddress, tgtWeights
Definition at line 101 of file AMIInterpolationI.H.
tgtMagSf()
const Foam::scalarField & tgtMagSf () const inline
Return const access to target patch face areas.
Definition at line 109 of file AMIInterpolationI.H.
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::AMIInterpolation().
tgtAddress()
const Foam::labelListList & tgtAddress () const inline
Return const access to target patch addressing.
Definition at line 117 of file AMIInterpolationI.H.
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::AMIInterpolation().
tgtWeights() [1/2]
const Foam::scalarListList & tgtWeights () const inline
Return const access to target patch weights.
Definition at line 125 of file AMIInterpolationI.H.
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::AMIInterpolation(), and cyclicACMIPolyPatch::resetAMI().
tgtWeights() [2/2]
Foam::scalarListList & tgtWeights () inline
Return access to target patch weights.
Definition at line 133 of file AMIInterpolationI.H.
tgtWeightsSum() [1/2]
const Foam::scalarField & tgtWeightsSum () const inline
Return const access to normalisation factor of target.
patch weights (i.e. the sum before normalisation)
Definition at line 141 of file AMIInterpolationI.H.
Referenced by cyclicACMIPolyPatch::resetAMI().
tgtWeightsSum() [2/2]
Foam::scalarField & tgtWeightsSum () inline
Return access to normalisation factor of target.
patch weights (i.e. the sum before normalisation)
Definition at line 149 of file AMIInterpolationI.H.
tgtMap()
const Foam::mapDistribute & tgtMap () const inline
Target map pointer - valid only if singlePatchProc=-1.
This gets target data into a form to be consumed by srcAddress, srcWeights
Definition at line 157 of file AMIInterpolationI.H.
update()
void update (const SourcePatch & srcPatch, const TargetPatch & tgtPatch)
Update addressing and weights.
Definition at line 826 of file AMIInterpolation.C.
References mapDistributeBase::constructMap(), Foam::endl(), forAll, Foam::gSum(), Foam::indent(), Foam::Info, AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), Foam::nl, Foam::returnReduce(), List< T >::size(), and mapDistributeBase::subMap().
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::~AMIInterpolation().
interpolateToSource() [1/9]
void interpolateToSource (const UList< Type > & fld, const CombineOp & cop, List< Type > & result, const UList< Type > & defaultValues = UList<Type>::null()) const
Interpolate from target to source with supplied op.
to combine existing value with remote value and weight
Definition at line 1180 of file AMIInterpolation.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, List< T >::setSize(), and UList< T >::size().
Referenced by mappedPatchBase::distribute(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), and meshToMesh::mapSrcToTgt().
interpolateToTarget() [1/9]
void interpolateToTarget (const UList< Type > & fld, const CombineOp & cop, List< Type > & result, const UList< Type > & defaultValues = UList<Type>::null()) const
Interpolate from source to target with supplied op.
to combine existing value with remote value and weight
Definition at line 1095 of file AMIInterpolation.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), Foam::nl, List< T >::setSize(), and UList< T >::size().
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), meshToMesh::mapTgtToSrc(), mappedPatchBase::reverseDistribute(), and AMIInterpolation< SourcePatch, TargetPatch >::update().
interpolateToSource() [2/9]
tmp<Field<Type> > interpolateToSource (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from target to source with supplied op.
interpolateToSource() [3/9]
tmp<Field<Type> > interpolateToSource (const tmp< Field< Type >> & tFld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from target tmp field to source with supplied op.
interpolateToTarget() [2/9]
tmp<Field<Type> > interpolateToTarget (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from source to target with supplied op.
interpolateToTarget() [3/9]
tmp<Field<Type> > interpolateToTarget (const tmp< Field< Type >> & tFld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from source tmp field to target with supplied op.
interpolateToSource() [4/9]
tmp<Field<Type> > interpolateToSource (const Field< Type > & fld, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from target to source.
interpolateToSource() [5/9]
tmp<Field<Type> > interpolateToSource (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from target tmp field.
interpolateToTarget() [4/9]
tmp<Field<Type> > interpolateToTarget (const Field< Type > & fld, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from source to target.
interpolateToTarget() [5/9]
tmp<Field<Type> > interpolateToTarget (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from source tmp field.
srcPointFace()
Foam::label srcPointFace (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const vector & n, const label tgtFacei, point & tgtPoint) const
Return source patch face index of point on target patch face.
Definition at line 1406 of file AMIInterpolation.C.
References PointHit< Point >::distance(), PointHit< Point >::eligibleMiss(), f(), forAll, PointHit< Point >::hit(), face::ray(), PointHit< Point >::setDistance(), and AMIInterpolation< SourcePatch, TargetPatch >::tgtPointFace().
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget().
tgtPointFace()
Foam::label tgtPointFace (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const vector & n, const label srcFacei, point & srcPoint) const
Return target patch face index of point on source patch face.
Definition at line 1455 of file AMIInterpolation.C.
References PointHit< Point >::distance(), PointHit< Point >::eligibleMiss(), f(), forAll, PointHit< Point >::hit(), face::ray(), PointHit< Point >::setDistance(), and AMIInterpolation< SourcePatch, TargetPatch >::writeFaceConnectivity().
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::srcPointFace().
writeFaceConnectivity()
void writeFaceConnectivity (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const labelListList & srcAddress) const
Write face connectivity as OBJ file.
Definition at line 1504 of file AMIInterpolation.C.
References Foam::endl(), forAll, Foam::name(), and Foam::meshTools::writeOBJ().
Referenced by AMIInterpolation< SourcePatch, TargetPatch >::tgtPointFace().
interpolateToSource() [6/9]
Foam::tmp<Foam::Field<Type> > interpolateToSource (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 1266 of file AMIInterpolation.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), tmp< T >::ref(), and Foam::Zero.
interpolateToSource() [7/9]
Foam::tmp<Foam::Field<Type> > interpolateToSource (const tmp< Field< Type >> & tFld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 1297 of file AMIInterpolation.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget().
interpolateToTarget() [6/9]
Foam::tmp<Foam::Field<Type> > interpolateToTarget (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 1311 of file AMIInterpolation.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), tmp< T >::ref(), and Foam::Zero.
interpolateToTarget() [7/9]
Foam::tmp<Foam::Field<Type> > interpolateToTarget (const tmp< Field< Type >> & tFld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 1342 of file AMIInterpolation.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource().
interpolateToSource() [8/9]
Foam::tmp<Foam::Field<Type> > interpolateToSource (const Field< Type > & fld, const UList< Type > & defaultValues) const
Definition at line 1356 of file AMIInterpolation.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource().
interpolateToSource() [9/9]
Foam::tmp<Foam::Field<Type> > interpolateToSource (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues) const
Definition at line 1369 of file AMIInterpolation.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget().
interpolateToTarget() [8/9]
Foam::tmp<Foam::Field<Type> > interpolateToTarget (const Field< Type > & fld, const UList< Type > & defaultValues) const
Definition at line 1382 of file AMIInterpolation.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget().
interpolateToTarget() [9/9]
Foam::tmp<Foam::Field<Type> > interpolateToTarget (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues) const
Definition at line 1395 of file AMIInterpolation.C.
References AMIInterpolation< SourcePatch, TargetPatch >::srcPointFace().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolation.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolation.C
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolationI.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolationParallelOps.C