OpenFOAM: PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData > Class Template Reference
PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData > Class Template Reference
Wave propagation of information along patch. Every iteration information goes through one layer of faces. Templated on information that is transferred.
Public Member Functions
PatchEdgeFaceWave (const polyMesh &mesh, const PrimitivePatchType &patch, const labelList &initialEdges, const List< Type > &initialEdgesInfo, UList< Type > &allEdgeInfo, UList< Type > &allFaceInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from patch, list of changed edges with the Type.
PatchEdgeFaceWave (const polyMesh &mesh, const PrimitivePatchType &patch, UList< Type > &allEdgeInfo, UList< Type > &allFaceInfo, TrackingData &td=dummyTrackData_)
Construct from patch. Use setEdgeInfo and iterate() to do.
UList< Type > & allEdgeInfo () const
Access allEdgeInfo.
UList< Type > & allFaceInfo () const
Access allFaceInfo.
const TrackingData & data () const
Additional data to be passed into container.
label getUnsetFaces () const
Get number of unvisited faces, i.e. faces that were not (yet)
label getUnsetEdges () const
void setEdgeInfo (const labelList &changedEdges, const List< Type > &changedEdgesInfo)
Copy initial data into allEdgeInfo_.
label edgeToFace ()
Propagate from edge to face. Returns total number of faces.
label faceToEdge ()
Propagate from face to edge. Returns total number of edges.
label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
Static Public Member Functions
static scalar propagationTol ()
Access to tolerance.
static void setPropagationTol (const scalar tol)
Change tolerance.
Detailed Description
template<class PrimitivePatchType, class Type, class TrackingData = label>
class Foam::PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >
Wave propagation of information along patch. Every iteration information goes through one layer of faces. Templated on information that is transferred.
Source files
PatchEdgeFaceWave.H
PatchEdgeFaceWave.C
Definition at line 69 of file PatchEdgeFaceWave.H.
Constructor & Destructor Documentation
PatchEdgeFaceWave() [1/2]
PatchEdgeFaceWave (const polyMesh & mesh, const PrimitivePatchType & patch, const labelList & initialEdges, const List< Type > & initialEdgesInfo, UList< Type > & allEdgeInfo, UList< Type > & allFaceInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from patch, list of changed edges with the Type.
for these edges. Gets work arrays to operate on, one of size number of patch edges, the other number of patch faces. Iterates until nothing changes or maxIter reached. (maxIter can be 0)
Definition at line 290 of file PatchEdgeFaceWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::Pout.
PatchEdgeFaceWave() [2/2]
PatchEdgeFaceWave (const polyMesh & mesh, const PrimitivePatchType & patch, UList< Type > & allEdgeInfo, UList< Type > & allFaceInfo, TrackingData & td = dummyTrackData_)
Construct from patch. Use setEdgeInfo and iterate() to do.
actual calculation
Definition at line 380 of file PatchEdgeFaceWave.C.
References PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::getUnsetEdges().
Member Function Documentation
propagationTol()
static scalar propagationTol () inline static
Access to tolerance.
Definition at line 165 of file PatchEdgeFaceWave.H.
setPropagationTol()
static void setPropagationTol (const scalar tol) inline static
Change tolerance.
Definition at line 171 of file PatchEdgeFaceWave.H.
References PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::allEdgeInfo(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::allFaceInfo(), and mesh.
allEdgeInfo()
UList<Type>& allEdgeInfo () const inline
Access allEdgeInfo.
Definition at line 211 of file PatchEdgeFaceWave.H.
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setPropagationTol().
allFaceInfo()
UList<Type>& allFaceInfo () const inline
Access allFaceInfo.
Definition at line 217 of file PatchEdgeFaceWave.H.
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setPropagationTol().
data()
const TrackingData& data () const inline
Additional data to be passed into container.
Definition at line 223 of file PatchEdgeFaceWave.H.
References PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::edgeToFace(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::faceToEdge(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::getUnsetEdges(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::getUnsetFaces(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::iterate(), and PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setEdgeInfo().
getUnsetFaces()
Foam::label getUnsetFaces () const
Get number of unvisited faces, i.e. faces that were not (yet)
reached from walking across patch. This can happen from
not enough iterations done
a disconnected patch
a patch without walls in it
Definition at line 437 of file PatchEdgeFaceWave.C.
References PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setEdgeInfo().
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::data(), and PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::getUnsetEdges().
getUnsetEdges()
Foam::label getUnsetEdges () const
Definition at line 424 of file PatchEdgeFaceWave.C.
References PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::getUnsetFaces().
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::data(), and PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::PatchEdgeFaceWave().
setEdgeInfo()
void setEdgeInfo (const labelList & changedEdges, const List< Type > & changedEdgesInfo)
Copy initial data into allEdgeInfo_.
Definition at line 452 of file PatchEdgeFaceWave.C.
References List< T >::append(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::faceToEdge(), and forAll.
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::data(), and PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::getUnsetFaces().
edgeToFace()
Foam::label edgeToFace ()
Propagate from edge to face. Returns total number of faces.
(over all processors) changed.
Definition at line 554 of file PatchEdgeFaceWave.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::iterate(), Foam::nl, Foam::Pout, and Foam::returnReduce().
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::data(), and PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::faceToEdge().
faceToEdge()
Foam::label faceToEdge ()
Propagate from face to edge. Returns total number of edges.
(over all processors) changed.
Definition at line 491 of file PatchEdgeFaceWave.C.
References Foam::abort(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::edgeToFace(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, Foam::Pout, and Foam::returnReduce().
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::data(), and PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setEdgeInfo().
iterate()
Foam::label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
number of iterations.
Definition at line 616 of file PatchEdgeFaceWave.C.
References Foam::endl(), Foam::nl, and Foam::Pout.
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::data(), and PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::edgeToFace().
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/PatchEdgeFaceWave.H
src/meshTools/algorithms/PatchEdgeFaceWave/PatchEdgeFaceWave.C