OpenFOAM: cellClassification Class Reference
cellClassification Class Reference
'Cuts' a mesh with a surface.
Public Types
enum cType { NOTSET, INSIDE, OUTSIDE, CUT }
Type of cell.
enum pointStatus { UNSET, MESH, NONMESH, MIXED }
Enumeration defining the whether points are use by cells of.
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
ClassName ("cellClassification")
cellClassification (const polyMesh &mesh, const meshSearch &meshQuery, const triSurfaceSearch &surfQuery, const pointField &outsidePoints)
Construct from mesh and surface and point(s) on outside.
cellClassification (const polyMesh &mesh, const labelList &cellType)
Construct from mesh and type for every cell.
cellClassification (const cellClassification &)
Construct as copy.
const polyMesh & mesh () const
label trimCutCells (const label nLayers, const label meshType, const label fillType)
label growSurface (const label meshType, const label fillType)
Sets vertex neighbours of meshType cells to fillType.
label fillHangingCells (const label meshType, const label fillType, const label maxIter)
Find hanging cells (cells with all points on outside) and set their.
label fillRegionEdges (const label meshType, const label fillType, const label maxIter)
Find regionEdges and fill one neighbour. Iterate until nothing.
label fillRegionPoints (const label meshType, const label fillType, const label maxIter)
Find regionPoints and fill all neighbours. Iterate until nothing.
void writeStats (Ostream &os) const
Write statistics on cell types to Ostream.
void operator= (const cellClassification &)
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Additional Inherited Members
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
'Cuts' a mesh with a surface.
Divides cells into three types
cut, i.e. any of the edges of the cell is split or any edge of the surface pierces any of the faces of the cell.
outside: cell can be reached by Meshwave from any of the supplied outside points (without crossing any cut cell)
inside: all other.
Used in various meshing programs.
Has various utility functions to deal with 'features' on this level where the mesh still has all inside and outside cells.
Concepts
point classification:
point used by meshType cells only
point used by non-meshType cells only
point used by both types ('mixed')
hanging cells: meshType cells using mixed points only. These cells would have all their vertices on the surface when extracting the meshType cells.
regionEdges: edges where the cells using it are of mixed type. Or more precise when walking around the edge and looking at the different types of the cells there are more than two regions with same type.
Seen from above:
Ok:
     A | A
       |
     --+---
       |
     B | B
Not ok:
     A | B
       |
    ---+---
       |
     B | A
because this latter situation would cause the surface after subsetting type A or B to be multiply connected across this edge. And also when snapping the edge end points to the surface it might cause some twisted faces if the surface is normal to the edge (and smoothing the surface would not help since the points on the edge would be 'pulled' from two different sides)
regionPoints: like regionEdges but now for points. Points where subsetting the mesh would cause a multiply connected outside surface (connected across point, not edge)
Source files
cellClassification.H
cellClassification.C
Definition at line 115 of file cellClassification.H.
Member Enumeration Documentation
cType
enum cType
Type of cell.
Enumerator
NOTSET
INSIDE
OUTSIDE
CUT
Definition at line 125 of file cellClassification.H.
pointStatus
enum pointStatus
Enumeration defining the whether points are use by cells of.
a certain type.
Enumerator
UNSET
MESH
NONMESH
MIXED
Definition at line 136 of file cellClassification.H.
Constructor & Destructor Documentation
cellClassification() [1/3]
cellClassification (const polyMesh & mesh, const meshSearch & meshQuery, const triSurfaceSearch & surfQuery, const pointField & outsidePoints)
Construct from mesh and surface and point(s) on outside.
Definition at line 482 of file cellClassification.C.
cellClassification() [2/3]
cellClassification (const polyMesh & mesh, const labelList & cellType)
Construct from mesh and type for every cell.
Used to be able to reuse filling routines below.
Definition at line 503 of file cellClassification.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
cellClassification() [3/3]
cellClassification (const cellClassification & cType)
Construct as copy.
Definition at line 521 of file cellClassification.C.
References cellClassification::trimCutCells().
Member Function Documentation
ClassName()
ClassName ("cellClassification")
mesh()
const polyMesh& mesh () const inline
Definition at line 218 of file cellClassification.H.
References cellClassification::fillHangingCells(), cellClassification::fillRegionEdges(), cellClassification::fillRegionPoints(), cellClassification::growSurface(), cellClassification::operator=(), cellClassification::trimCutCells(), and cellClassification::writeStats().
trimCutCells()
Foam::label trimCutCells (const label nLayers, const label meshType, const label fillType)
Definition at line 534 of file cellClassification.C.
References cellClassification::CUT, forAll, cellClassification::growSurface(), cellClassification::MIXED, primitiveMesh::nPoints(), UList< T >::operator[](), and primitiveMesh::pointCells().
Referenced by cellClassification::cellClassification(), surfaceSets::getSurfaceSets(), and cellClassification::mesh().
growSurface()
Foam::label growSurface (const label meshType, const label fillType)
Sets vertex neighbours of meshType cells to fillType.
Definition at line 620 of file cellClassification.C.
References cellClassification::fillHangingCells(), forAll, primitiveMesh::nPoints(), UList< T >::operator[](), and primitiveMesh::pointCells().
Referenced by cellClassification::mesh(), and cellClassification::trimCutCells().
fillHangingCells()
Foam::label fillHangingCells (const label meshType, const label fillType, const label maxIter)
Find hanging cells (cells with all points on outside) and set their.
type to fillType. Iterate until nothing changed. Returns total number of cells changed (in all iterations)
Definition at line 677 of file cellClassification.C.
References Foam::endl(), cellClassification::fillRegionEdges(), forAll, cellClassification::MIXED, primitiveMesh::nPoints(), UList< T >::operator[](), primitiveMesh::pointCells(), and Foam::Pout.
Referenced by cellClassification::growSurface(), and cellClassification::mesh().
fillRegionEdges()
Foam::label fillRegionEdges (const label meshType, const label fillType, const label maxIter)
Find regionEdges and fill one neighbour. Iterate until nothing.
changes. Returns total number of cells changed.
Definition at line 734 of file cellClassification.C.
References Foam::endl(), cellClassification::fillRegionPoints(), forAll, UList< T >::operator[](), polyMesh::points(), Foam::Pout, and List< T >::size().
Referenced by cellClassification::fillHangingCells(), and cellClassification::mesh().
fillRegionPoints()
Foam::label fillRegionPoints (const label meshType, const label fillType, const label maxIter)
Find regionPoints and fill all neighbours. Iterate until nothing.
changes. Returns total number of cells changed.
Definition at line 803 of file cellClassification.C.
References Foam::endl(), forAll, forAllConstIter(), UList< T >::operator[](), pFaces, polyMesh::points(), and Foam::Pout.
Referenced by cellClassification::fillRegionEdges(), and cellClassification::mesh().
writeStats()
void writeStats (Ostream & os) const
Write statistics on cell types to Ostream.
Definition at line 872 of file cellClassification.C.
References cellClassification::CUT, Foam::endl(), cellClassification::INSIDE, cellClassification::NOTSET, cellClassification::OUTSIDE, and List< T >::size().
Referenced by cellClassification::mesh().
operator=()
void operator= (const cellClassification & rhs)
Definition at line 884 of file cellClassification.C.
References List< label >::operator=().
Referenced by cellClassification::mesh().
The documentation for this class was generated from the following files:
src/meshTools/cellClassification/cellClassification.H
src/meshTools/cellClassification/cellClassification.C