OpenFOAM: cyclicACMIGAMGInterface Class Reference
cyclicACMIGAMGInterface Class Reference
GAMG agglomerated cyclic ACMI interface.
Public Member Functions
TypeName ("cyclicACMI")
Runtime type information.
cyclicACMIGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &restrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Construct from fine level interface,.
virtual ~cyclicACMIGAMGInterface ()
Destructor.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Transfer and return internal field adjacent to the interface.
virtual label neighbPatchID () const
Cyclic interface functions.
virtual bool owner () const
virtual const cyclicACMIGAMGInterface & neighbPatch () const
Return processor number.
virtual const AMIPatchToPatchInterpolation & AMI () const
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual void write (Ostream &) const
Write to stream.
Public Member Functions inherited from GAMGInterface
TypeName ("GAMGInterface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterface, lduInterface,(const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm),(index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr, GAMGInterface, Istream,(const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is),(index, coarseInterfaces, is))
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces)
Construct from interfaces, restrict addressing set later on.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddressing)
Construct from interfaces and restrict addressing.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Construct from Istream.
virtual label size () const
Return size.
virtual label index () const
virtual const lduInterfacePtrsList & coarseInterfaces () const
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual const labelList & faceRestrictAddressing () const
Return (local)face restrict addressing.
virtual labelList & faceRestrictAddressing ()
Return non-const access to face restrict addressing.
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData) const
Return the interface internal field of the given field.
template<class Type >
void interfaceInternalField (const UList< Type > &internalData, List< Type > &) const
Get the interface internal field of the given field.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
void combine (const GAMGInterface &)
Merge the next level with this level.
virtual tmp< scalarField > agglomerateCoeffs (const scalarField &fineCoeffs) const
Agglomerating the given fine-level coefficients and return.
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF) const
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
Public Member Functions inherited from cyclicACMILduInterface
TypeName ("cyclicACMILduInterface")
Runtime type information.
cyclicACMILduInterface ()
Construct null.
virtual ~cyclicACMILduInterface ()
Destructor.
Public Member Functions inherited from cyclicAMILduInterface
TypeName ("cyclicAMILduInterface")
Runtime type information.
cyclicAMILduInterface ()
Construct null.
virtual ~cyclicAMILduInterface ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterface
static autoPtr< GAMGInterface > New (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterface > New (const word &coupleType, const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Return a pointer to a new interface created on freestore given.
Protected Attributes inherited from GAMGInterface
const label index_
My index in coarseInterfaces.
const lduInterfacePtrsList & coarseInterfaces_
All interfaces.
labelList faceCells_
Face-cell addressing.
labelList faceRestrictAddressing_
Face restrict addressing.
Detailed Description
GAMG agglomerated cyclic ACMI interface.
Source files
cyclicACMIGAMGInterface.H
cyclicACMIGAMGInterface.C
Definition at line 49 of file cyclicACMIGAMGInterface.H.
Constructor & Destructor Documentation
cyclicACMIGAMGInterface()
cyclicACMIGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const lduInterface & fineInterface, const labelField & restrictAddressing, const labelField & neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Construct from fine level interface,.
local and neighbour restrict addressing
Definition at line 48 of file cyclicACMIGAMGInterface.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::find(), forAll, List< T >::size(), and List< T >::transfer().
~cyclicACMIGAMGInterface()
~cyclicACMIGAMGInterface () virtual
Destructor.
Definition at line 169 of file cyclicACMIGAMGInterface.C.
References cyclicACMIGAMGInterface::internalFieldTransfer().
Member Function Documentation
TypeName()
TypeName ("cyclicACMI")
Runtime type information.
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Transfer and return internal field adjacent to the interface.
Implements lduInterface.
Definition at line 177 of file cyclicACMIGAMGInterface.C.
References GAMGInterface::faceCells(), forAll, tmp< T >::ref(), and UList< T >::size().
Referenced by cyclicACMIGAMGInterface::~cyclicACMIGAMGInterface().
neighbPatchID()
virtual label neighbPatchID () const inline virtual
Cyclic interface functions.
Return neigbour processor number
Implements cyclicAMILduInterface.
Definition at line 114 of file cyclicACMIGAMGInterface.H.
References cyclicAMILduInterface::neighbPatchID().
Referenced by cyclicACMIGAMGInterface::neighbPatch().
owner()
virtual bool owner () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 119 of file cyclicACMIGAMGInterface.H.
References cyclicAMILduInterface::owner().
neighbPatch()
virtual const cyclicACMIGAMGInterface& neighbPatch () const inline virtual
Return processor number.
Implements cyclicAMILduInterface.
Definition at line 124 of file cyclicACMIGAMGInterface.H.
References GAMGInterface::coarseInterfaces_, and cyclicACMIGAMGInterface::neighbPatchID().
AMI()
virtual const AMIPatchToPatchInterpolation& AMI () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 132 of file cyclicACMIGAMGInterface.H.
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements cyclicAMILduInterface.
Definition at line 138 of file cyclicACMIGAMGInterface.H.
References cyclicAMILduInterface::forwardT().
Referenced by cyclicACMIGAMGInterfaceField::forwardT().
reverseT()
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Implements cyclicAMILduInterface.
Definition at line 144 of file cyclicACMIGAMGInterface.H.
References cyclicAMILduInterface::reverseT().
Referenced by cyclicACMIGAMGInterfaceField::reverseT().
write()
virtual void write (Ostream &) const inline virtual
Write to stream.
Implements GAMGInterface.
Definition at line 153 of file cyclicACMIGAMGInterface.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/GAMG/interfaces/cyclicACMIGAMGInterface/cyclicACMIGAMGInterface.H
src/meshTools/AMIInterpolation/GAMG/interfaces/cyclicACMIGAMGInterface/cyclicACMIGAMGInterface.C