OpenFOAM: AMIMethod< SourcePatch, TargetPatch > Class Template Reference
AMIMethod< SourcePatch, TargetPatch > Class Template Reference abstract
Base class for Arbitrary Mesh Interface (AMI) methods.
Public Member Functions
TypeName ("AMIMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AMIMethod, components,(const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch),(srcPatch, tgtPatch, srcMagSf, tgtMagSf, triMode, reverseTarget, requireMatch))
Declare runtime constructor selection table.
AMIMethod (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Construct from components.
virtual ~AMIMethod ()
Destructor.
const labelList & srcNonOverlap () const
Labels of faces that are not overlapped by any target faces.
virtual bool conformal () const
Flag to indicate that interpolation patches are conformal.
virtual void calculate (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label srcFacei=-1, label tgtFacei=-1)=0
Update addressing and weights.
Static Public Member Functions
static autoPtr< AMIMethod > New (const word &methodName, const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Selector.
Protected Types
typedef treeDataPrimitivePatch< TargetPatch > treeType
Local typedef to octree tree-type.
Protected Member Functions
void checkPatches () const
Check AMI patch coupling.
bool initialise (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label &srcFacei, label &tgtFacei)
Initialise and return true if all ok.
void writeIntersectionOBJ (const scalar area, const face &f1, const face &f2, const pointField &f1Points, const pointField &f2Points) const
Write triangle intersection to OBJ file.
void resetTree ()
Reset the octree for the target patch face search.
label findTargetFace (const label srcFacei) const
Find face on target patch that overlaps source face.
void appendNbrFaces (const label facei, const TargetPatch &patch, const DynamicList< label > &visitedFaces, DynamicList< label > &faceIDs) const
Add faces neighbouring facei to the ID list.
Protected Attributes
const SourcePatch & srcPatch_
Reference to source patch.
const TargetPatch & tgtPatch_
Reference to target patch.
const bool reverseTarget_
Flag to indicate that the two patches are co-directional and.
const bool requireMatch_
Flag to indicate that the two patches must be matched/an overlap.
const scalarField & srcMagSf_
Source face areas.
const scalarField & tgtMagSf_
Target face areas.
labelList srcNonOverlap_
Labels of faces that are not overlapped by any target faces.
autoPtr< indexedOctree< treeType > > treePtr_
Octree used to find face seeds.
const faceAreaIntersect::triangulationMode triMode_
Face triangulation mode.
Detailed Description
template<class SourcePatch, class TargetPatch>
class Foam::AMIMethod< SourcePatch, TargetPatch >
Base class for Arbitrary Mesh Interface (AMI) methods.
Source files
AMIMethod.H
AMIMethod.C
Definition at line 55 of file AMIMethod.H.
Member Typedef Documentation
treeType
typedef treeDataPrimitivePatch<TargetPatch> treeType protected
Local typedef to octree tree-type.
Definition at line 72 of file AMIMethod.H.
Constructor & Destructor Documentation
AMIMethod()
AMIMethod (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const scalarField & srcMagSf, const scalarField & tgtMagSf, const faceAreaIntersect::triangulationMode & triMode, const bool reverseTarget, const bool requireMatch)
Construct from components.
Definition at line 317 of file AMIMethod.C.
~AMIMethod()
~AMIMethod () virtual
Destructor.
Definition at line 341 of file AMIMethod.C.
Member Function Documentation
checkPatches()
void checkPatches () const protected
Check AMI patch coupling.
Definition at line 34 of file AMIMethod.C.
References Foam::endl(), AMIMethod< SourcePatch, TargetPatch >::initialise(), Foam::nl, Foam::Pout, and WarningInFunction.
initialise()
bool initialise (labelListList & srcAddress, scalarListList & srcWeights, labelListList & tgtAddress, scalarListList & tgtWeights, label & srcFacei, label & tgtFacei) protected
Initialise and return true if all ok.
Definition at line 72 of file AMIMethod.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, List< T >::setSize(), WarningInFunction, and AMIMethod< SourcePatch, TargetPatch >::writeIntersectionOBJ().
Referenced by AMIMethod< SourcePatch, TargetPatch >::checkPatches().
writeIntersectionOBJ()
void writeIntersectionOBJ (const scalar area, const face & f1, const face & f2, const pointField & f1Points, const pointField & f2Points) const protected
Write triangle intersection to OBJ file.
Definition at line 147 of file AMIMethod.C.
References Foam::endl(), forAll, Foam::name(), Foam::nl, face::points(), Foam::Pout, List< T >::size(), and Foam::meshTools::writeOBJ().
Referenced by AMIMethod< SourcePatch, TargetPatch >::initialise().
resetTree()
void resetTree () protected
Reset the octree for the target patch face search.
Definition at line 198 of file AMIMethod.C.
References AMIMethod< SourcePatch, TargetPatch >::findTargetFace(), and boundBox::inflate().
findTargetFace()
Foam::label findTargetFace (const label srcFacei) const protected
Find face on target patch that overlaps source face.
Definition at line 230 of file AMIMethod.C.
References AMIMethod< SourcePatch, TargetPatch >::appendNbrFaces(), face::centre(), Foam::endl(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), and Foam::Pout.
Referenced by AMIMethod< SourcePatch, TargetPatch >::resetTree().
appendNbrFaces()
void appendNbrFaces (const label facei, const TargetPatch & patch, const DynamicList< label > & visitedFaces, DynamicList< label > & faceIDs) const protected
Add faces neighbouring facei to the ID list.
Definition at line 261 of file AMIMethod.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::cos(), Foam::degToRad(), and forAll.
Referenced by AMIMethod< SourcePatch, TargetPatch >::findTargetFace().
TypeName()
TypeName ("AMIMethod< SourcePatch, TargetPatch >")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , AMIMethod< SourcePatch, TargetPatch > , components , (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch) , (srcPatch, tgtPatch, srcMagSf, tgtMagSf, triMode, reverseTarget, requireMatch))
Declare runtime constructor selection table.
New()
Foam::autoPtr< Foam::AMIMethod< SourcePatch, TargetPatch > > New (const word & methodName, const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const scalarField & srcMagSf, const scalarField & tgtMagSf, const faceAreaIntersect::triangulationMode & triMode, const bool reverseTarget, const bool requireMatch) static
Selector.
Definition at line 31 of file AMIMethodNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, and Foam::nl.
srcNonOverlap()
const Foam::labelList & srcNonOverlap () const inline
Labels of faces that are not overlapped by any target faces.
Note: this should be empty for correct functioning
Definition at line 28 of file AMIMethodI.H.
conformal()
bool conformal () const virtual
Flag to indicate that interpolation patches are conformal.
Reimplemented in partialFaceAreaWeightAMI< SourcePatch, TargetPatch >.
Definition at line 348 of file AMIMethod.C.
calculate()
virtual void calculate (labelListList & srcAddress, scalarListList & srcWeights, labelListList & tgtAddress, scalarListList & tgtWeights, label srcFacei = -1, label tgtFacei = -1) pure virtual
Update addressing and weights.
Implemented in faceAreaWeightAMI< SourcePatch, TargetPatch >, mapNearestAMI< SourcePatch, TargetPatch >, directAMI< SourcePatch, TargetPatch >, and partialFaceAreaWeightAMI< SourcePatch, TargetPatch >.
Member Data Documentation
srcPatch_
const SourcePatch& srcPatch_ protected
Reference to source patch.
Definition at line 78 of file AMIMethod.H.
tgtPatch_
const TargetPatch& tgtPatch_ protected
Reference to target patch.
Definition at line 81 of file AMIMethod.H.
reverseTarget_
const bool reverseTarget_ protected
Flag to indicate that the two patches are co-directional and.
that the orientation of the target patch should be reversed
Definition at line 85 of file AMIMethod.H.
requireMatch_
const bool requireMatch_ protected
Flag to indicate that the two patches must be matched/an overlap.
exists between them
Definition at line 89 of file AMIMethod.H.
srcMagSf_
const scalarField& srcMagSf_ protected
Source face areas.
Definition at line 92 of file AMIMethod.H.
tgtMagSf_
const scalarField& tgtMagSf_ protected
Target face areas.
Definition at line 95 of file AMIMethod.H.
srcNonOverlap_
labelList srcNonOverlap_ protected
Labels of faces that are not overlapped by any target faces.
(should be empty for correct functioning)
Definition at line 99 of file AMIMethod.H.
treePtr_
autoPtr<indexedOctree<treeType> > treePtr_ protected
Octree used to find face seeds.
Definition at line 102 of file AMIMethod.H.
triMode_
const faceAreaIntersect::triangulationMode triMode_ protected
Face triangulation mode.
Definition at line 105 of file AMIMethod.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/AMIMethod/AMIMethod.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/AMIMethod/AMIMethod.C
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/AMIMethod/AMIMethodI.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/AMIMethod/AMIMethodNew.C