OpenFOAM: faceAreaWeightAMI< SourcePatch, TargetPatch > Class Template Reference
faceAreaWeightAMI< SourcePatch, TargetPatch > Class Template Reference
Face area weighted Arbitrary Mesh Interface (AMI) method.
Public Member Functions
TypeName ("faceAreaWeightAMI")
Runtime type information.
faceAreaWeightAMI (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget=false, const bool requireMatch=true, const bool restartUncoveredSourceFace=true)
Construct from components.
virtual ~faceAreaWeightAMI ()
Destructor.
virtual void calculate (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label srcFacei=-1, label tgtFacei=-1)
Update addressing and weights.
Public Member Functions inherited from AMIMethod< SourcePatch, TargetPatch >
TypeName ("AMIMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AMIMethod, components,(const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch),(srcPatch, tgtPatch, srcMagSf, tgtMagSf, triMode, reverseTarget, requireMatch))
Declare runtime constructor selection table.
AMIMethod (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Construct from components.
virtual ~AMIMethod ()
Destructor.
const labelList & srcNonOverlap () const
Labels of faces that are not overlapped by any target faces.
virtual bool conformal () const
Flag to indicate that interpolation patches are conformal.
Protected Member Functions
faceAreaWeightAMI (const faceAreaWeightAMI &)
Disallow default bitwise copy construct.
void operator= (const faceAreaWeightAMI &)
Disallow default bitwise assignment.
virtual void calcAddressing (List< DynamicList< label >> &srcAddress, List< DynamicList< scalar >> &srcWeights, List< DynamicList< label >> &tgtAddress, List< DynamicList< scalar >> &tgtWeights, label srcFacei, label tgtFacei)
Calculate addressing and weights using temporary storage.
virtual bool processSourceFace (const label srcFacei, const label tgtStartFacei, DynamicList< label > &nbrFaces, DynamicList< label > &visitedFaces, List< DynamicList< label >> &srcAddr, List< DynamicList< scalar >> &srcWght, List< DynamicList< label >> &tgtAddr, List< DynamicList< scalar >> &tgtWght)
Determine overlap contributions for source face srcFacei.
virtual void restartUncoveredSourceFace (List< DynamicList< label >> &srcAddr, List< DynamicList< scalar >> &srcWght, List< DynamicList< label >> &tgtAddr, List< DynamicList< scalar >> &tgtWght)
Attempt to re-evaluate source faces that have not been included.
virtual void setNextFaces (label &startSeedI, label &srcFacei, label &tgtFacei, const boolList &mapFlag, labelList &seedFaces, const DynamicList< label > &visitedFaces, bool errorOnNotFound=true) const
Set the source and target seed faces.
virtual scalar interArea (const label srcFacei, const label tgtFacei) const
Area of intersection between source and target faces.
Protected Member Functions inherited from AMIMethod< SourcePatch, TargetPatch >
void checkPatches () const
Check AMI patch coupling.
bool initialise (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label &srcFacei, label &tgtFacei)
Initialise and return true if all ok.
void writeIntersectionOBJ (const scalar area, const face &f1, const face &f2, const pointField &f1Points, const pointField &f2Points) const
Write triangle intersection to OBJ file.
void resetTree ()
Reset the octree for the target patch face search.
label findTargetFace (const label srcFacei) const
Find face on target patch that overlaps source face.
void appendNbrFaces (const label facei, const TargetPatch &patch, const DynamicList< label > &visitedFaces, DynamicList< label > &faceIDs) const
Add faces neighbouring facei to the ID list.
Additional Inherited Members
Static Public Member Functions inherited from AMIMethod< SourcePatch, TargetPatch >
static autoPtr< AMIMethod > New (const word &methodName, const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Selector.
Protected Types inherited from AMIMethod< SourcePatch, TargetPatch >
typedef treeDataPrimitivePatch< TargetPatch > treeType
Local typedef to octree tree-type.
Protected Attributes inherited from AMIMethod< SourcePatch, TargetPatch >
const SourcePatch & srcPatch_
Reference to source patch.
const TargetPatch & tgtPatch_
Reference to target patch.
const bool reverseTarget_
Flag to indicate that the two patches are co-directional and.
const bool requireMatch_
Flag to indicate that the two patches must be matched/an overlap.
const scalarField & srcMagSf_
Source face areas.
const scalarField & tgtMagSf_
Target face areas.
labelList srcNonOverlap_
Labels of faces that are not overlapped by any target faces.
autoPtr< indexedOctree< treeType > > treePtr_
Octree used to find face seeds.
const faceAreaIntersect::triangulationMode triMode_
Face triangulation mode.
Detailed Description
template<class SourcePatch, class TargetPatch>
class Foam::faceAreaWeightAMI< SourcePatch, TargetPatch >
Face area weighted Arbitrary Mesh Interface (AMI) method.
Source files
faceAreaWeightAMI.H
faceAreaWeightAMI.C
Definition at line 49 of file faceAreaWeightAMI.H.
Constructor & Destructor Documentation
faceAreaWeightAMI() [1/2]
faceAreaWeightAMI (const faceAreaWeightAMI< SourcePatch, TargetPatch > &) protected
Disallow default bitwise copy construct.
Referenced by faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace().
faceAreaWeightAMI() [2/2]
faceAreaWeightAMI (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const scalarField & srcMagSf, const scalarField & tgtMagSf, const faceAreaIntersect::triangulationMode & triMode, const bool reverseTarget = false, const bool requireMatch = true, const bool restartUncoveredSourceFace = true)
Construct from components.
Definition at line 459 of file faceAreaWeightAMI.C.
~faceAreaWeightAMI()
~faceAreaWeightAMI () virtual
Destructor.
Definition at line 487 of file faceAreaWeightAMI.C.
References faceAreaWeightAMI< SourcePatch, TargetPatch >::calculate().
Member Function Documentation
operator=()
void operator= (const faceAreaWeightAMI< SourcePatch, TargetPatch > &) protected
Disallow default bitwise assignment.
calcAddressing()
void calcAddressing (List< DynamicList< label >> & srcAddress, List< DynamicList< scalar >> & srcWeights, List< DynamicList< label >> & tgtAddress, List< DynamicList< scalar >> & tgtWeights, label srcFacei, label tgtFacei) protected virtual
Calculate addressing and weights using temporary storage.
Definition at line 32 of file faceAreaWeightAMI.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), and faceAreaWeightAMI< SourcePatch, TargetPatch >::processSourceFace().
processSourceFace()
bool processSourceFace (const label srcFacei, const label tgtStartFacei, DynamicList< label > & nbrFaces, DynamicList< label > & visitedFaces, List< DynamicList< label >> & srcAddr, List< DynamicList< scalar >> & srcWght, List< DynamicList< label >> & tgtAddr, List< DynamicList< scalar >> & tgtWght) protected virtual
Determine overlap contributions for source face srcFacei.
Definition at line 110 of file faceAreaWeightAMI.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove(), faceAreaWeightAMI< SourcePatch, TargetPatch >::setNextFaces(), and List< T >::size().
Referenced by faceAreaWeightAMI< SourcePatch, TargetPatch >::calcAddressing().
restartUncoveredSourceFace()
void restartUncoveredSourceFace (List< DynamicList< label >> & srcAddr, List< DynamicList< scalar >> & srcWght, List< DynamicList< label >> & tgtAddr, List< DynamicList< scalar >> & tgtWght) protected virtual
Attempt to re-evaluate source faces that have not been included.
Definition at line 360 of file faceAreaWeightAMI.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), Foam::endl(), faceAreaWeightAMI< SourcePatch, TargetPatch >::faceAreaWeightAMI(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::found(), HashSet< Key, Hash >::insert(), Foam::Pout, s(), List< T >::size(), HashTable< T, Key, Hash >::size(), Foam::sum(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer().
Referenced by faceAreaWeightAMI< SourcePatch, TargetPatch >::interArea().
setNextFaces()
void setNextFaces (label & startSeedI, label & srcFacei, label & tgtFacei, const boolList & mapFlag, labelList & seedFaces, const DynamicList< label > & visitedFaces, bool errorOnNotFound = true) const protected virtual
Set the source and target seed faces.
Definition at line 181 of file faceAreaWeightAMI.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, faceAreaWeightAMI< SourcePatch, TargetPatch >::interArea(), Foam::Pout, and List< T >::size().
Referenced by faceAreaWeightAMI< SourcePatch, TargetPatch >::processSourceFace().
interArea()
Foam::scalar interArea (const label srcFacei, const label tgtFacei) const protected virtual
Area of intersection between source and target faces.
Definition at line 296 of file faceAreaWeightAMI.C.
References faceAreaIntersect::calc(), Foam::endl(), face::mag(), Foam::mag(), n, faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), and WarningInFunction.
Referenced by faceAreaWeightAMI< SourcePatch, TargetPatch >::setNextFaces().
TypeName()
TypeName ("faceAreaWeightAMI< SourcePatch, TargetPatch >")
Runtime type information.
calculate()
void calculate (labelListList & srcAddress, scalarListList & srcWeights, labelListList & tgtAddress, scalarListList & tgtWeights, label srcFacei = -1, label tgtFacei = -1) virtual
Update addressing and weights.
Implements AMIMethod< SourcePatch, TargetPatch >.
Reimplemented in partialFaceAreaWeightAMI< SourcePatch, TargetPatch >.
Definition at line 495 of file faceAreaWeightAMI.C.
References Foam::endl(), forAll, Foam::Pout, and List< T >::transfer().
Referenced by faceAreaWeightAMI< SourcePatch, TargetPatch >::~faceAreaWeightAMI().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/faceAreaWeightAMI/faceAreaWeightAMI.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/faceAreaWeightAMI/faceAreaWeightAMI.C