OpenFOAM: mapNearestAMI< SourcePatch, TargetPatch > Class Template Reference
mapNearestAMI< SourcePatch, TargetPatch > Class Template Reference
Nearest-mapping Arbitrary Mesh Interface (AMI) method.
Public Member Functions
TypeName ("mapNearestAMI")
Runtime type information.
mapNearestAMI (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget=false, const bool requireMatch=true)
Construct from components.
virtual ~mapNearestAMI ()
Destructor.
virtual void calculate (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label srcFacei=-1, label tgtFacei=-1)
Update addressing and weights.
Public Member Functions inherited from AMIMethod< SourcePatch, TargetPatch >
TypeName ("AMIMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AMIMethod, components,(const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch),(srcPatch, tgtPatch, srcMagSf, tgtMagSf, triMode, reverseTarget, requireMatch))
Declare runtime constructor selection table.
AMIMethod (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Construct from components.
virtual ~AMIMethod ()
Destructor.
const labelList & srcNonOverlap () const
Labels of faces that are not overlapped by any target faces.
virtual bool conformal () const
Flag to indicate that interpolation patches are conformal.
Additional Inherited Members
Static Public Member Functions inherited from AMIMethod< SourcePatch, TargetPatch >
static autoPtr< AMIMethod > New (const word &methodName, const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Selector.
Protected Types inherited from AMIMethod< SourcePatch, TargetPatch >
typedef treeDataPrimitivePatch< TargetPatch > treeType
Local typedef to octree tree-type.
Protected Member Functions inherited from AMIMethod< SourcePatch, TargetPatch >
void checkPatches () const
Check AMI patch coupling.
bool initialise (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label &srcFacei, label &tgtFacei)
Initialise and return true if all ok.
void writeIntersectionOBJ (const scalar area, const face &f1, const face &f2, const pointField &f1Points, const pointField &f2Points) const
Write triangle intersection to OBJ file.
void resetTree ()
Reset the octree for the target patch face search.
label findTargetFace (const label srcFacei) const
Find face on target patch that overlaps source face.
void appendNbrFaces (const label facei, const TargetPatch &patch, const DynamicList< label > &visitedFaces, DynamicList< label > &faceIDs) const
Add faces neighbouring facei to the ID list.
Protected Attributes inherited from AMIMethod< SourcePatch, TargetPatch >
const SourcePatch & srcPatch_
Reference to source patch.
const TargetPatch & tgtPatch_
Reference to target patch.
const bool reverseTarget_
Flag to indicate that the two patches are co-directional and.
const bool requireMatch_
Flag to indicate that the two patches must be matched/an overlap.
const scalarField & srcMagSf_
Source face areas.
const scalarField & tgtMagSf_
Target face areas.
labelList srcNonOverlap_
Labels of faces that are not overlapped by any target faces.
autoPtr< indexedOctree< treeType > > treePtr_
Octree used to find face seeds.
const faceAreaIntersect::triangulationMode triMode_
Face triangulation mode.
Detailed Description
template<class SourcePatch, class TargetPatch>
class Foam::mapNearestAMI< SourcePatch, TargetPatch >
Nearest-mapping Arbitrary Mesh Interface (AMI) method.
Source files
mapNearestAMI.H
mapNearestAMI.C
Definition at line 49 of file mapNearestAMI.H.
Constructor & Destructor Documentation
mapNearestAMI()
mapNearestAMI (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const scalarField & srcMagSf, const scalarField & tgtMagSf, const faceAreaIntersect::triangulationMode & triMode, const bool reverseTarget = false, const bool requireMatch = true)
Construct from components.
Definition at line 172 of file mapNearestAMI.C.
~mapNearestAMI()
~mapNearestAMI () virtual
Destructor.
Definition at line 198 of file mapNearestAMI.C.
References mapNearestAMI< SourcePatch, TargetPatch >::calculate().
Member Function Documentation
TypeName()
TypeName ("mapNearestAMI< SourcePatch, TargetPatch >")
Runtime type information.
calculate()
void calculate (labelListList & srcAddress, scalarListList & srcWeights, labelListList & tgtAddress, scalarListList & tgtWeights, label srcFacei = -1, label tgtFacei = -1) virtual
Update addressing and weights.
Implements AMIMethod< SourcePatch, TargetPatch >.
Definition at line 206 of file mapNearestAMI.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), forAll, Foam::magSqr(), List< T >::size(), and List< T >::transfer().
Referenced by mapNearestAMI< SourcePatch, TargetPatch >::~mapNearestAMI().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/mapNearestAMI/mapNearestAMI.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/mapNearestAMI/mapNearestAMI.C