OpenFOAM: faceAreaIntersect Class Reference
faceAreaIntersect Class Reference
Face intersection class.
Public Types
enum triangulationMode { tmFan, tmMesh }
typedef FixedList< point, 3 > triPoints
Public Member Functions
faceAreaIntersect (const pointField &pointsA, const pointField &pointsB, const bool reverseB=false)
Construct from components.
scalar calc (const face &faceA, const face &faceB, const vector &n, const triangulationMode &triMode)
Return area of intersection of faceA with faceB.
Static Public Member Functions
static scalar & tolerance ()
Fraction of local length scale to use as intersection tolerance.
Static Public Attributes
static const NamedEnum< triangulationMode, 2 > triangulationModeNames_
Detailed Description
Face intersection class.
- calculates intersection area by sub-dividing face into triangles and cutting
Source files
faceAreaIntersect.H
faceAreaIntersect.C
Definition at line 54 of file faceAreaIntersect.H.
Member Typedef Documentation
triPoints
typedef FixedList<point, 3> triPoints
Definition at line 58 of file faceAreaIntersect.H.
Member Enumeration Documentation
triangulationMode
enum triangulationMode
Enumerator
tmFan
tmMesh
Definition at line 60 of file faceAreaIntersect.H.
Constructor & Destructor Documentation
faceAreaIntersect()
faceAreaIntersect (const pointField & pointsA, const pointField & pointsB, const bool reverseB = false)
Construct from components.
Definition at line 314 of file faceAreaIntersect.C.
References faceAreaIntersect::calc().
Referenced by NamedEnum< directionType, 3 >::names().
Member Function Documentation
tolerance()
Foam::scalar & tolerance () inline static
Fraction of local length scale to use as intersection tolerance.
Definition at line 113 of file faceAreaIntersectI.H.
calc()
Foam::scalar calc (const face & faceA, const face & faceB, const vector & n, const triangulationMode & triMode)
Return area of intersection of faceA with faceB.
Definition at line 329 of file faceAreaIntersect.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, and face::triangles().
Referenced by faceAreaIntersect::faceAreaIntersect(), and faceAreaWeightAMI< SourcePatch, TargetPatch >::interArea().
Member Data Documentation
triangulationModeNames_
const Foam::NamedEnum< Foam::faceAreaIntersect::triangulationMode, 2 > triangulationModeNames_ static
Definition at line 66 of file faceAreaIntersect.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/faceAreaIntersect/faceAreaIntersect.H
src/meshTools/AMIInterpolation/faceAreaIntersect/faceAreaIntersect.C
src/meshTools/AMIInterpolation/faceAreaIntersect/faceAreaIntersectI.H