OpenFOAM: partialFaceAreaWeightAMI< SourcePatch, TargetPatch > Class Template Reference
partialFaceAreaWeightAMI< SourcePatch, TargetPatch > Class Template Reference
Partial face area weighted Arbitrary Mesh Interface (AMI) method.
Public Member Functions
TypeName ("partialFaceAreaWeightAMI")
Runtime type information.
partialFaceAreaWeightAMI (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget=false, const bool requireMatch=true)
Construct from components.
virtual ~partialFaceAreaWeightAMI ()
Destructor.
virtual bool conformal () const
Flag to indicate that interpolation patches are conformal.
virtual void calculate (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label srcFacei=-1, label tgtFacei=-1)
Update addressing and weights.
Public Member Functions inherited from faceAreaWeightAMI< SourcePatch, TargetPatch >
TypeName ("faceAreaWeightAMI")
Runtime type information.
faceAreaWeightAMI (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget=false, const bool requireMatch=true, const bool restartUncoveredSourceFace=true)
Construct from components.
virtual ~faceAreaWeightAMI ()
Destructor.
Public Member Functions inherited from AMIMethod< SourcePatch, TargetPatch >
TypeName ("AMIMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AMIMethod, components,(const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch),(srcPatch, tgtPatch, srcMagSf, tgtMagSf, triMode, reverseTarget, requireMatch))
Declare runtime constructor selection table.
AMIMethod (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Construct from components.
virtual ~AMIMethod ()
Destructor.
const labelList & srcNonOverlap () const
Labels of faces that are not overlapped by any target faces.
Additional Inherited Members
Static Public Member Functions inherited from AMIMethod< SourcePatch, TargetPatch >
static autoPtr< AMIMethod > New (const word &methodName, const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const scalarField &srcMagSf, const scalarField &tgtMagSf, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Selector.
Protected Types inherited from AMIMethod< SourcePatch, TargetPatch >
typedef treeDataPrimitivePatch< TargetPatch > treeType
Local typedef to octree tree-type.
Protected Member Functions inherited from faceAreaWeightAMI< SourcePatch, TargetPatch >
faceAreaWeightAMI (const faceAreaWeightAMI &)
Disallow default bitwise copy construct.
void operator= (const faceAreaWeightAMI &)
Disallow default bitwise assignment.
virtual void calcAddressing (List< DynamicList< label >> &srcAddress, List< DynamicList< scalar >> &srcWeights, List< DynamicList< label >> &tgtAddress, List< DynamicList< scalar >> &tgtWeights, label srcFacei, label tgtFacei)
Calculate addressing and weights using temporary storage.
virtual bool processSourceFace (const label srcFacei, const label tgtStartFacei, DynamicList< label > &nbrFaces, DynamicList< label > &visitedFaces, List< DynamicList< label >> &srcAddr, List< DynamicList< scalar >> &srcWght, List< DynamicList< label >> &tgtAddr, List< DynamicList< scalar >> &tgtWght)
Determine overlap contributions for source face srcFacei.
virtual void restartUncoveredSourceFace (List< DynamicList< label >> &srcAddr, List< DynamicList< scalar >> &srcWght, List< DynamicList< label >> &tgtAddr, List< DynamicList< scalar >> &tgtWght)
Attempt to re-evaluate source faces that have not been included.
virtual scalar interArea (const label srcFacei, const label tgtFacei) const
Area of intersection between source and target faces.
Protected Member Functions inherited from AMIMethod< SourcePatch, TargetPatch >
void checkPatches () const
Check AMI patch coupling.
bool initialise (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label &srcFacei, label &tgtFacei)
Initialise and return true if all ok.
void writeIntersectionOBJ (const scalar area, const face &f1, const face &f2, const pointField &f1Points, const pointField &f2Points) const
Write triangle intersection to OBJ file.
void resetTree ()
Reset the octree for the target patch face search.
label findTargetFace (const label srcFacei) const
Find face on target patch that overlaps source face.
void appendNbrFaces (const label facei, const TargetPatch &patch, const DynamicList< label > &visitedFaces, DynamicList< label > &faceIDs) const
Add faces neighbouring facei to the ID list.
Protected Attributes inherited from AMIMethod< SourcePatch, TargetPatch >
const SourcePatch & srcPatch_
Reference to source patch.
const TargetPatch & tgtPatch_
Reference to target patch.
const bool reverseTarget_
Flag to indicate that the two patches are co-directional and.
const bool requireMatch_
Flag to indicate that the two patches must be matched/an overlap.
const scalarField & srcMagSf_
Source face areas.
const scalarField & tgtMagSf_
Target face areas.
labelList srcNonOverlap_
Labels of faces that are not overlapped by any target faces.
autoPtr< indexedOctree< treeType > > treePtr_
Octree used to find face seeds.
const faceAreaIntersect::triangulationMode triMode_
Face triangulation mode.
Detailed Description
template<class SourcePatch, class TargetPatch>
class Foam::partialFaceAreaWeightAMI< SourcePatch, TargetPatch >
Partial face area weighted Arbitrary Mesh Interface (AMI) method.
Source files
partialFaceAreaWeightAMI.H
partialFaceAreaWeightAMI.C
Definition at line 49 of file partialFaceAreaWeightAMI.H.
Constructor & Destructor Documentation
partialFaceAreaWeightAMI()
partialFaceAreaWeightAMI (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const scalarField & srcMagSf, const scalarField & tgtMagSf, const faceAreaIntersect::triangulationMode & triMode, const bool reverseTarget = false, const bool requireMatch = true)
Construct from components.
Definition at line 60 of file partialFaceAreaWeightAMI.C.
References partialFaceAreaWeightAMI< SourcePatch, TargetPatch >::~partialFaceAreaWeightAMI().
~partialFaceAreaWeightAMI()
~partialFaceAreaWeightAMI () virtual
Destructor.
Definition at line 87 of file partialFaceAreaWeightAMI.C.
Referenced by partialFaceAreaWeightAMI< SourcePatch, TargetPatch >::partialFaceAreaWeightAMI().
Member Function Documentation
TypeName()
TypeName ("partialFaceAreaWeightAMI< SourcePatch, TargetPatch >")
Runtime type information.
conformal()
bool conformal () const virtual
Flag to indicate that interpolation patches are conformal.
Reimplemented from AMIMethod< SourcePatch, TargetPatch >.
Definition at line 94 of file partialFaceAreaWeightAMI.C.
References partialFaceAreaWeightAMI< SourcePatch, TargetPatch >::calculate().
calculate()
void calculate (labelListList & srcAddress, scalarListList & srcWeights, labelListList & tgtAddress, scalarListList & tgtWeights, label srcFacei = -1, label tgtFacei = -1) virtual
Update addressing and weights.
Reimplemented from faceAreaWeightAMI< SourcePatch, TargetPatch >.
Definition at line 102 of file partialFaceAreaWeightAMI.C.
References forAll, and List< T >::transfer().
Referenced by partialFaceAreaWeightAMI< SourcePatch, TargetPatch >::conformal().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/partialFaceAreaWeightAMI/partialFaceAreaWeightAMI.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/partialFaceAreaWeightAMI/partialFaceAreaWeightAMI.C