OpenFOAM: cyclicAMIPolyPatch Class Reference
cyclicAMIPolyPatch Class Reference
Cyclic patch for Arbitrary Mesh Interface (AMI)
Public Member Functions
TypeName ("cyclicAMI")
Runtime type information.
cyclicAMIPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN)
Construct from (base couped patch) components.
cyclicAMIPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &nbrPatchName)
Construct given the original patch and resetting the.
cyclicAMIPolyPatch (const cyclicAMIPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~cyclicAMIPolyPatch ()
Destructor.
virtual bool coupled () const
Is patch 'coupled'. Note that on AMI the geometry is not.
const word & neighbPatchName () const
Neighbour patch name.
virtual label neighbPatchID () const
Neighbour patch ID.
virtual bool owner () const
Does this side own the patch?
virtual const cyclicAMIPolyPatch & neighbPatch () const
Return a reference to the neighbour patch.
const autoPtr< searchableSurface > & surfPtr () const
Return a reference to the projection surface.
const AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
bool applyLowWeightCorrection () const
Return true if applying the low weight correction.
const vector & rotationAxis () const
Axis of rotation for rotational cyclic AMI.
const point & rotationCentre () const
Point on axis of rotation for rotational cyclic AMI.
const vector & separationVector () const
Translation vector for translational cyclic AMI.
virtual void transformPosition (pointField &) const
Transform patch-based positions from nbr side to this side.
virtual void transformPosition (point &l, const label facei) const
Transform a patch-based position from nbr side to this side.
virtual void reverseTransformPosition (point &l, const label facei) const
Transform a patch-based position from this side to nbr side.
virtual void reverseTransformDirection (vector &d, const label facei) const
Transform a patch-based direction from this side to nbr side.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >()) const
Interpolate field.
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues=UList< Type >()) const
Interpolate tmp field.
template<class Type , class CombineOp >
void interpolate (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >()) const
Low-level interpolate List.
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
Calculate the patch geometry.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
label pointFace (const label facei, const vector &n, point &p) const
Return face index on neighbour patch which shares point p.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues) const
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
virtual bool neighbour () const
Does the coupled side own the patch ?
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Protected Member Functions
virtual void resetAMI (const AMIPatchToPatchInterpolation::interpolationMethod &AMIMethod=AMIPatchToPatchInterpolation::imFaceAreaWeight) const
Reset the AMI interpolator.
virtual void calcTransforms ()
Recalculate the transformation tensors.
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &pBufs, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &pBufs, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
virtual void clearGeom ()
Clear geometry.
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
Protected Attributes
word nbrPatchName_
Name of other half.
const coupleGroupIdentifier coupleGroup_
Optional patchGroup to find neighbPatch.
label nbrPatchID_
Index of other half.
vector rotationAxis_
Axis of rotation for rotational cyclics.
point rotationCentre_
Point on axis of rotation for rotational cyclics.
bool rotationAngleDefined_
Flag to show whether the rotation angle is defined.
scalar rotationAngle_
Rotation angle.
vector separationVector_
Translation vector.
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
AMI interpolation class.
const bool AMIReverse_
Flag to indicate that slave patch should be reversed for AMI.
bool AMIRequireMatch_
Flag to indicate that patches should match/overlap.
const scalar AMILowWeightCorrection_
Low weight correction threshold for AMI.
autoPtr< searchableSurface > surfPtr_
Projection surface.
const dictionary surfDict_
Dictionary used during projection surface construction.
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes inherited from coupledPolyPatch
static const NamedEnum< transformType, 5 > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Detailed Description
Cyclic patch for Arbitrary Mesh Interface (AMI)
Source files
cyclicAMIPolyPatch.H
cyclicAMIPolyPatch.C
Definition at line 51 of file cyclicAMIPolyPatch.H.
Constructor & Destructor Documentation
cyclicAMIPolyPatch() [1/5]
cyclicAMIPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform = UNKNOWN)
Construct from (base couped patch) components.
Definition at line 475 of file cyclicAMIPolyPatch.C.
Referenced by cyclicAMIPolyPatch::clearGeom(), cyclicAMIPolyPatch::clone(), and cyclicAMIPolyPatch::cyclicAMIPolyPatch().
cyclicAMIPolyPatch() [2/5]
cyclicAMIPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 506 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::cyclicAMIPolyPatch(), Foam::degToRad(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::Info, dictionary::lookup(), Foam::mag(), word::null, dictionary::readIfPresent(), Foam::transform(), and word::valid().
cyclicAMIPolyPatch() [3/5]
cyclicAMIPolyPatch (const cyclicAMIPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 598 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::cyclicAMIPolyPatch().
cyclicAMIPolyPatch() [4/5]
cyclicAMIPolyPatch (const cyclicAMIPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & nbrPatchName)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 625 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::cyclicAMIPolyPatch(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::name().
cyclicAMIPolyPatch() [5/5]
cyclicAMIPolyPatch (const cyclicAMIPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 664 of file cyclicAMIPolyPatch.C.
~cyclicAMIPolyPatch()
~cyclicAMIPolyPatch () virtual
Destructor.
Definition at line 692 of file cyclicAMIPolyPatch.C.
Referenced by cyclicAMIPolyPatch::clone().
Member Function Documentation
resetAMI()
void resetAMI (const AMIPatchToPatchInterpolation::interpolationMethod & AMIMethod = AMIPatchToPatchInterpolation::imFaceAreaWeight) const protected virtual
Reset the AMI interpolator.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 325 of file cyclicAMIPolyPatch.C.
References Foam::endl(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), mesh, boundaryMesh::mesh(), Foam::name(), Foam::nl, Time::path(), points, Foam::Pout, faceAreaIntersect::tmMesh, and Foam::meshTools::writeOBJ().
Referenced by cyclicAMIPolyPatch::calcTransforms(), and cyclicACMIPolyPatch::resetAMI().
calcTransforms()
void calcTransforms () protected virtual
Recalculate the transformation tensors.
Definition at line 72 of file cyclicAMIPolyPatch.C.
References Foam::acos(), clear(), Foam::cos(), Foam::endl(), Foam::exit(), polyPatch::faceCentres(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::gSum(), Tensor< scalar >::I, Foam::mag(), Foam::min(), Foam::name(), Foam::nl, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::Pout, Foam::radToDeg(), Foam::reduce(), cyclicAMIPolyPatch::resetAMI(), setSize(), Foam::sin(), List< T >::size(), Foam::T(), Tensor< Cmpt >::T(), Foam::transform(), WarningInFunction, and Foam::Zero.
initGeometry()
void initGeometry (PstreamBuffers & pBufs) protected virtual
Initialise the calculation of the patch geometry.
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 398 of file cyclicAMIPolyPatch.C.
References polyPatch::initGeometry().
Referenced by cyclicACMIPolyPatch::initGeometry().
calcGeometry() [1/2]
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Calculate the patch geometry.
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 407 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::initMovePoints().
Referenced by cyclicACMIPolyPatch::calcGeometry(), cyclicAMIPolyPatch::clone(), and cyclicAMIPolyPatch::reverseTransformDirection().
initMovePoints()
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Initialise the patches for moving points.
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 423 of file cyclicAMIPolyPatch.C.
References polyPatch::initMovePoints(), cyclicAMIPolyPatch::movePoints(), and PrimitivePatch< Face, FaceList, PointField, PointType >::movePoints().
Referenced by cyclicAMIPolyPatch::calcGeometry(), and cyclicACMIPolyPatch::initMovePoints().
movePoints()
void movePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Correct patches after moving points.
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 439 of file cyclicAMIPolyPatch.C.
References polyPatch::movePoints().
Referenced by cyclicAMIPolyPatch::initMovePoints(), and cyclicACMIPolyPatch::movePoints().
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 450 of file cyclicAMIPolyPatch.C.
References polyPatch::initUpdateMesh().
Referenced by cyclicACMIPolyPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Update of the patch topology.
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 459 of file cyclicAMIPolyPatch.C.
References polyPatch::updateMesh().
Referenced by cyclicACMIPolyPatch::updateMesh().
clearGeom()
void clearGeom () protected virtual
Clear geometry.
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 465 of file cyclicAMIPolyPatch.C.
References polyPatch::clearGeom(), and cyclicAMIPolyPatch::cyclicAMIPolyPatch().
Referenced by cyclicACMIPolyPatch::clearGeom().
TypeName()
TypeName ("cyclicAMI")
Runtime type information.
clone() [1/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 220 of file cyclicAMIPolyPatch.H.
References cyclicAMIPolyPatch::cyclicAMIPolyPatch().
Referenced by cyclicAMIPolyPatch::clone().
clone() [2/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 228 of file cyclicAMIPolyPatch.H.
References cyclicAMIPolyPatch::clone(), and cyclicAMIPolyPatch::cyclicAMIPolyPatch().
clone() [3/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from polyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 252 of file cyclicAMIPolyPatch.H.
References cyclicAMIPolyPatch::AMI(), cyclicAMIPolyPatch::applyLowWeightCorrection(), cyclicAMIPolyPatch::calcGeometry(), cyclicAMIPolyPatch::coupled(), cyclicAMIPolyPatch::cyclicAMIPolyPatch(), Foam::faceMap(), fld(), cyclicAMIPolyPatch::initOrder(), cyclicAMIPolyPatch::interpolate(), n, cyclicAMIPolyPatch::neighbPatch(), cyclicAMIPolyPatch::neighbPatchID(), cyclicAMIPolyPatch::neighbPatchName(), cyclicAMIPolyPatch::order(), cyclicAMIPolyPatch::owner(), p, cyclicAMIPolyPatch::pointFace(), cyclicAMIPolyPatch::reverseTransformDirection(), cyclicAMIPolyPatch::reverseTransformPosition(), cyclicAMIPolyPatch::rotationAxis(), cyclicAMIPolyPatch::rotationCentre(), cyclicAMIPolyPatch::separationVector(), cyclicAMIPolyPatch::surfPtr(), cyclicAMIPolyPatch::transformPosition(), cyclicAMIPolyPatch::write(), and cyclicAMIPolyPatch::~cyclicAMIPolyPatch().
coupled()
virtual bool coupled () const inline virtual
Is patch 'coupled'. Note that on AMI the geometry is not.
coupled but the fields are!
Reimplemented from coupledPolyPatch.
Definition at line 283 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::clone().
neighbPatchName()
const Foam::word & neighbPatchName () const inline
Neighbour patch name.
Definition at line 28 of file cyclicAMIPolyPatchI.H.
References polyPatch::boundaryMesh(), cyclicAMIPolyPatch::coupleGroup_, IOobject::name(), and cyclicAMIPolyPatch::nbrPatchName_.
Referenced by cyclicACMIPolyPatch::clone(), cyclicAMIPolyPatch::clone(), and cyclicAMIPolyPatch::neighbPatchID().
neighbPatchID()
Foam::label neighbPatchID () const virtual
Neighbour patch ID.
Definition at line 698 of file cyclicAMIPolyPatch.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::name(), cyclicAMIPolyPatch::neighbPatchName(), Foam::nl, and WarningInFunction.
Referenced by cyclicAMIPolyPatch::clone(), cyclicAMIFvPatch::neighbFvPatch(), cyclicACMIFvPatch::neighbFvPatch(), cyclicAMIFvPatch::neighbPatch(), cyclicACMIFvPatch::neighbPatch(), cyclicAMIPointPatch::neighbPatch(), cyclicACMIPointPatch::neighbPatch(), cyclicAMIFvPatch::neighbPatchID(), and cyclicACMIFvPatch::neighbPatchID().
owner()
bool owner () const virtual
Does this side own the patch?
Implements coupledPolyPatch.
Definition at line 734 of file cyclicAMIPolyPatch.C.
Referenced by cyclicAMIPolyPatch::clone(), cyclicACMIPolyPatch::mask(), combine< Type, TrackingData >::operator()(), cyclicAMIFvPatch::owner(), and cyclicACMIFvPatch::owner().
neighbPatch()
const Foam::cyclicAMIPolyPatch & neighbPatch () const virtual
Return a reference to the neighbour patch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 740 of file cyclicAMIPolyPatch.C.
Referenced by cyclicAMIPolyPatch::clone(), particle< Type >::hitCyclicAMIPatch(), combine< Type, TrackingData >::operator()(), and cyclicACMIPointPatchField< Type >::swapAddSeparated().
surfPtr()
const Foam::autoPtr< Foam::searchableSurface > & surfPtr () const
Return a reference to the projection surface.
Definition at line 748 of file cyclicAMIPolyPatch.C.
References mesh, boundaryMesh::mesh(), IOobject::MUST_READ, searchableSurface::New(), and IOobject::NO_WRITE.
Referenced by cyclicAMIPolyPatch::clone().
AMI()
const Foam::AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
Definition at line 779 of file cyclicAMIPolyPatch.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by cyclicAMIFvPatch::AMI(), cyclicACMIFvPatch::AMI(), and cyclicAMIPolyPatch::clone().
applyLowWeightCorrection()
bool applyLowWeightCorrection () const
Return true if applying the low weight correction.
Definition at line 797 of file cyclicAMIPolyPatch.C.
Referenced by cyclicAMIFvPatch::applyLowWeightCorrection(), cyclicAMIPolyPatch::clone(), and FaceCellWave< Type, TrackingData >::handleAMICyclicPatches().
rotationAxis()
const Foam::vector & rotationAxis () const inline
Axis of rotation for rotational cyclic AMI.
Definition at line 41 of file cyclicAMIPolyPatchI.H.
References cyclicAMIPolyPatch::rotationAxis_.
Referenced by cyclicAMIPolyPatch::clone().
rotationCentre()
const Foam::point & rotationCentre () const inline
Point on axis of rotation for rotational cyclic AMI.
Definition at line 47 of file cyclicAMIPolyPatchI.H.
References cyclicAMIPolyPatch::rotationCentre_.
Referenced by cyclicAMIPolyPatch::clone().
separationVector()
const Foam::vector & separationVector () const inline
Translation vector for translational cyclic AMI.
Definition at line 53 of file cyclicAMIPolyPatchI.H.
References cyclicAMIPolyPatch::separationVector_.
Referenced by cyclicAMIPolyPatch::clone().
transformPosition() [1/2]
void transformPosition (pointField & l) const virtual
Transform patch-based positions from nbr side to this side.
Implements coupledPolyPatch.
Definition at line 810 of file cyclicAMIPolyPatch.C.
References forAll, s(), List< T >::size(), and Foam::transform().
Referenced by cyclicAMIPolyPatch::clone().
transformPosition() [2/2]
void transformPosition (point & l, const label facei) const virtual
Transform a patch-based position from nbr side to this side.
Implements coupledPolyPatch.
Definition at line 846 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::reverseTransformPosition(), s(), Foam::T(), and Foam::transform().
reverseTransformPosition()
void reverseTransformPosition (point & l, const label facei) const virtual
Transform a patch-based position from this side to nbr side.
Definition at line 884 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::reverseTransformDirection(), s(), Foam::T(), and Foam::transform().
Referenced by cyclicAMIPolyPatch::clone(), and cyclicAMIPolyPatch::transformPosition().
reverseTransformDirection()
void reverseTransformDirection (vector & d, const label facei) const virtual
Transform a patch-based direction from this side to nbr side.
Definition at line 922 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::calcGeometry(), Foam::T(), and Foam::transform().
Referenced by cyclicAMIPolyPatch::clone(), and cyclicAMIPolyPatch::reverseTransformPosition().
interpolate() [1/5]
tmp<Field<Type> > interpolate (const Field< Type > & fld, const UList< Type > & defaultValues = UList< Type >()) const
Interpolate field.
Referenced by cyclicAMIPolyPatch::clone(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), cyclicAMIPolyPatch::interpolate(), cyclicAMIFvPatch::interpolate(), and cyclicACMIPointPatchField< Type >::swapAddSeparated().
interpolate() [2/5]
tmp<Field<Type> > interpolate (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues = UList< Type >()) const
Interpolate tmp field.
interpolate() [3/5]
void interpolate (const UList< Type > & fld, const CombineOp & cop, List< Type > & result, const UList< Type > & defaultValues = UList<Type>()) const
Low-level interpolate List.
Definition at line 59 of file cyclicAMIPolyPatchTemplates.C.
calcGeometry() [2/2]
void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) virtual
Calculate the patch geometry.
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 942 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::initOrder().
initOrder()
void initOrder (PstreamBuffers & pBufs, const primitivePatch & pp) const virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 964 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::order().
Referenced by cyclicAMIPolyPatch::calcGeometry(), cyclicAMIPolyPatch::clone(), and cyclicACMIPolyPatch::initOrder().
order()
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Implements coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 972 of file cyclicAMIPolyPatch.C.
References cyclicAMIPolyPatch::pointFace(), and List< T >::setSize().
Referenced by cyclicAMIPolyPatch::clone(), cyclicAMIPolyPatch::initOrder(), and cyclicACMIPolyPatch::order().
pointFace()
Foam::label pointFace (const label facei, const vector & n, point & p) const
Return face index on neighbour patch which shares point p.
following trajectory vector n
Definition at line 990 of file cyclicAMIPolyPatch.C.
Referenced by cyclicAMIPolyPatch::clone(), particle< Type >::hitCyclicAMIPatch(), and cyclicAMIPolyPatch::order().
write()
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from coupledPolyPatch.
Reimplemented in cyclicACMIPolyPatch.
Definition at line 1036 of file cyclicAMIPolyPatch.C.
References token::END_STATEMENT, Foam::nl, Foam::radToDeg(), Foam::transform(), coupledPolyPatch::write(), and Ostream::writeKeyword().
Referenced by cyclicAMIPolyPatch::clone(), and cyclicACMIPolyPatch::write().
interpolate() [4/5]
Foam::tmp<Foam::Field<Type> > interpolate (const Field< Type > & fld, const UList< Type > & defaultValues) const
Definition at line 30 of file cyclicAMIPolyPatchTemplates.C.
References cyclicAMIPolyPatch::interpolate().
interpolate() [5/5]
Foam::tmp<Foam::Field<Type> > interpolate (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues) const
Definition at line 48 of file cyclicAMIPolyPatchTemplates.C.
References Foam::MULES::interpolate(), and cyclicAMIPolyPatch::interpolate().
Member Data Documentation
nbrPatchName_
word nbrPatchName_ mutable protected
Name of other half.
Definition at line 78 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::neighbPatchName().
coupleGroup_
const coupleGroupIdentifier coupleGroup_ protected
Optional patchGroup to find neighbPatch.
Definition at line 81 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::neighbPatchName().
nbrPatchID_
label nbrPatchID_ mutable protected
Index of other half.
Definition at line 84 of file cyclicAMIPolyPatch.H.
rotationAxis_
vector rotationAxis_ protected
Axis of rotation for rotational cyclics.
Definition at line 92 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::rotationAxis().
rotationCentre_
point rotationCentre_ protected
Point on axis of rotation for rotational cyclics.
Definition at line 95 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::rotationCentre().
rotationAngleDefined_
bool rotationAngleDefined_ protected
Flag to show whether the rotation angle is defined.
Definition at line 98 of file cyclicAMIPolyPatch.H.
rotationAngle_
scalar rotationAngle_ protected
Rotation angle.
Definition at line 101 of file cyclicAMIPolyPatch.H.
separationVector_
vector separationVector_ protected
Translation vector.
Definition at line 107 of file cyclicAMIPolyPatch.H.
Referenced by cyclicAMIPolyPatch::separationVector().
AMIPtr_
autoPtr<AMIPatchToPatchInterpolation> AMIPtr_ mutable protected
AMI interpolation class.
Definition at line 111 of file cyclicAMIPolyPatch.H.
AMIReverse_
const bool AMIReverse_ protected
Flag to indicate that slave patch should be reversed for AMI.
Definition at line 114 of file cyclicAMIPolyPatch.H.
AMIRequireMatch_
bool AMIRequireMatch_ protected
Flag to indicate that patches should match/overlap.
Definition at line 117 of file cyclicAMIPolyPatch.H.
AMILowWeightCorrection_
const scalar AMILowWeightCorrection_ protected
Low weight correction threshold for AMI.
Definition at line 120 of file cyclicAMIPolyPatch.H.
surfPtr_
autoPtr<searchableSurface> surfPtr_ mutable protected
Projection surface.
Definition at line 123 of file cyclicAMIPolyPatch.H.
surfDict_
const dictionary surfDict_ protected
Dictionary used during projection surface construction.
Definition at line 126 of file cyclicAMIPolyPatch.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch/cyclicAMIPolyPatch.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch/cyclicAMIPolyPatch.C
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch/cyclicAMIPolyPatchI.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPolyPatch/cyclicAMIPolyPatchTemplates.C