OpenFOAM: cyclicAMIGAMGInterfaceField Class Reference
cyclicAMIGAMGInterfaceField Class Reference
GAMG agglomerated cyclic interface field.
Public Member Functions
TypeName ("cyclicAMI")
Runtime type information.
cyclicAMIGAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterfaceField)
Construct from GAMG interface and fine level interface field.
cyclicAMIGAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
virtual ~cyclicAMIGAMGInterfaceField ()
Destructor.
label size () const
Return size.
virtual void updateInterfaceMatrix (scalarField &result, const scalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
Update result field based on interface functionality.
virtual bool doTransform () const
Cyclic interface functions.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual int rank () const
Return rank of component for transform.
Public Member Functions inherited from GAMGInterfaceField
TypeName ("GAMGInterfaceField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterfaceField,(const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface),(GAMGCp, fineInterface))
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterface,(const GAMGInterface &GAMGCp, const bool doTransform, const int rank),(GAMGCp, doTransform, rank))
GAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &)
Construct from GAMG interface and fine level interface field.
GAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
const GAMGInterface & interface () const
Return interface.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
Public Member Functions inherited from cyclicAMILduInterfaceField
TypeName ("cyclicAMILduInterfaceField")
Runtime type information.
cyclicAMILduInterfaceField ()
Construct null.
virtual ~cyclicAMILduInterfaceField ()
Destructor.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &psiInternal, const direction cmpt) const
Transform given patch internal field.
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterfaceField
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Return a pointer to a new interface created on freestore given.
Detailed Description
GAMG agglomerated cyclic interface field.
Source files
cyclicAMIGAMGInterfaceField.H
cyclicAMIGAMGInterfaceField.C
Definition at line 50 of file cyclicAMIGAMGInterfaceField.H.
Constructor & Destructor Documentation
cyclicAMIGAMGInterfaceField() [1/2]
cyclicAMIGAMGInterfaceField (const GAMGInterface & GAMGCp, const lduInterfaceField & fineInterfaceField)
Construct from GAMG interface and fine level interface field.
Definition at line 53 of file cyclicAMIGAMGInterfaceField.C.
References cyclicAMILduInterfaceField::doTransform(), p, and cyclicAMILduInterfaceField::rank().
cyclicAMIGAMGInterfaceField() [2/2]
cyclicAMIGAMGInterfaceField (const GAMGInterface & GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
Definition at line 72 of file cyclicAMIGAMGInterfaceField.C.
~cyclicAMIGAMGInterfaceField()
~cyclicAMIGAMGInterfaceField () virtual
Destructor.
Definition at line 87 of file cyclicAMIGAMGInterfaceField.C.
References cyclicAMIGAMGInterfaceField::updateInterfaceMatrix().
Member Function Documentation
TypeName()
TypeName ("cyclicAMI")
Runtime type information.
size()
label size () const inline
Return size.
Definition at line 109 of file cyclicAMIGAMGInterfaceField.H.
References GAMGInterface::size(), and cyclicAMIGAMGInterfaceField::updateInterfaceMatrix().
updateInterfaceMatrix()
void updateInterfaceMatrix (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Update result field based on interface functionality.
Implements lduInterfaceField.
Definition at line 94 of file cyclicAMIGAMGInterfaceField.C.
References forAll.
Referenced by cyclicAMIGAMGInterfaceField::size(), and cyclicAMIGAMGInterfaceField::~cyclicAMIGAMGInterfaceField().
doTransform()
virtual bool doTransform () const inline virtual
Cyclic interface functions.
Does the interface field perform the transfromation
Implements cyclicAMILduInterfaceField.
Definition at line 131 of file cyclicAMIGAMGInterfaceField.H.
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements cyclicAMILduInterfaceField.
Definition at line 137 of file cyclicAMIGAMGInterfaceField.H.
References cyclicAMIGAMGInterface::forwardT().
reverseT()
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Implements cyclicAMILduInterfaceField.
Definition at line 143 of file cyclicAMIGAMGInterfaceField.H.
References cyclicAMIGAMGInterface::reverseT().
rank()
virtual int rank () const inline virtual
Return rank of component for transform.
Implements cyclicAMILduInterfaceField.
Definition at line 149 of file cyclicAMIGAMGInterfaceField.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/GAMG/interfaceFields/cyclicAMIGAMGInterfaceField/cyclicAMIGAMGInterfaceField.H
src/meshTools/AMIInterpolation/GAMG/interfaceFields/cyclicAMIGAMGInterfaceField/cyclicAMIGAMGInterfaceField.C