OpenFOAM: patchDataWave< TransferType > Class Template Reference
patchDataWave< TransferType > Class Template Reference
Takes a set of patches to start MeshWave from.
Public Member Functions
patchDataWave (const polyMesh &mesh, const labelHashSet &patchIDs, const UPtrList< Field< Type >> &initialPatchValuePtrs, bool correctWalls=true)
Construct from mesh, information on patches to initialize and flag.
virtual ~patchDataWave ()
Destructor.
virtual void correct ()
Correct for mesh geom/topo changes.
const scalarField & distance () const
scalarField & distance ()
Non const access so we can 'transfer' contents for efficiency.
const FieldField< Field, scalar > & patchDistance () const
FieldField< Field, scalar > & patchDistance ()
const Field< Type > & cellData () const
Field< Type > & cellData ()
const FieldField< Field, Type > & patchData () const
FieldField< Field, Type > & patchData ()
label nUnset () const
Public Member Functions inherited from cellDistFuncs
ClassName ("cellDistFuncs")
cellDistFuncs (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
Access mesh.
labelHashSet getPatchIDs (const wordReList &patchNames) const
Return the set of patch IDs corresponding to the given names.
template<class Type >
labelHashSet getPatchIDs () const
Get patchIDs of/derived off certain type (e.g. 'processorPolyPatch')
scalar smallestDist (const point &p, const polyPatch &patch, const label nWallFaces, const labelList &wallFaces, label &meshFacei) const
Calculate smallest true distance (and face index)
label getPointNeighbours (const primitivePatch &, const label patchFacei, labelList &) const
Get faces sharing point with face on patch.
label maxPatchSize (const labelHashSet &patchIDs) const
Size of largest patch (out of supplied subset of patches)
label sumPatchSize (const labelHashSet &patchIDs) const
Sum of patch sizes (out of supplied subset of patches).
void correctBoundaryFaceCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
Correct all cells connected to boundary (via face). Sets values in.
void correctBoundaryPointCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
Correct all cells connected to wall (via point). Sets values in.
template<class Type >
Foam::labelHashSet getPatchIDs () const
Detailed Description
template<class TransferType>
class Foam::patchDataWave< TransferType >
Takes a set of patches to start MeshWave from.
Holds after construction distance at cells and distance at patches (like patchWave), but also additional transported data. It is used, for example, in the y+ calculation.
See also
The patchWave class.
Source files
patchDataWave.H
patchDataWave.C
Definition at line 63 of file patchDataWave.H.
Constructor & Destructor Documentation
patchDataWave()
patchDataWave (const polyMesh & mesh, const labelHashSet & patchIDs, const UPtrList< Field< Type >> & initialPatchValuePtrs, bool correctWalls = true)
Construct from mesh, information on patches to initialize and flag.
whether or not to correct wall. Calculate for all cells. correctWalls : correct wall (face&point) cells for correct distance, searching neighbours.
Definition at line 172 of file patchDataWave.C.
References correct.
~patchDataWave()
~patchDataWave () virtual
Destructor.
Definition at line 196 of file patchDataWave.C.
Member Function Documentation
correct()
void correct () virtual
Correct for mesh geom/topo changes.
Definition at line 204 of file patchDataWave.C.
References MeshWave< Type, TrackingData >::allFaceInfo(), UList< T >::data(), forAll, mesh, and HashTable< T, Key, Hash >::toc().
distance() [1/2]
const scalarField& distance () const inline
Definition at line 145 of file patchDataWave.H.
Referenced by wallDistData< TransferType >::correct(), and meshWave::correct().
distance() [2/2]
scalarField& distance () inline
Non const access so we can 'transfer' contents for efficiency.
Definition at line 151 of file patchDataWave.H.
patchDistance() [1/2]
const FieldField<Field, scalar>& patchDistance () const inline
Definition at line 156 of file patchDataWave.H.
Referenced by wallDistData< TransferType >::correct(), and meshWave::correct().
patchDistance() [2/2]
FieldField<Field, scalar>& patchDistance () inline
Definition at line 161 of file patchDataWave.H.
cellData() [1/2]
const Field<Type>& cellData () const inline
Definition at line 166 of file patchDataWave.H.
Referenced by wallDistData< TransferType >::correct(), and meshWave::correct().
cellData() [2/2]
Field<Type>& cellData () inline
Definition at line 171 of file patchDataWave.H.
patchData() [1/2]
const FieldField<Field, Type>& patchData () const inline
Definition at line 176 of file patchDataWave.H.
Referenced by wallDistData< TransferType >::correct(), and meshWave::correct().
patchData() [2/2]
FieldField<Field, Type>& patchData () inline
Definition at line 181 of file patchDataWave.H.
nUnset()
label nUnset () const inline
Definition at line 186 of file patchDataWave.H.
Referenced by wallDistData< TransferType >::correct(), and meshWave::correct().
The documentation for this class was generated from the following files:
src/meshTools/cellDist/patchWave/patchDataWave.H
src/meshTools/cellDist/patchWave/patchDataWave.C