OpenFOAM: cyclicAMIPointPatch Class Reference
cyclicAMIPointPatch Class Reference
Cyclic AMI point patch - place holder only.
Public Member Functions
TypeName (cyclicAMIPolyPatch::typeName_())
Runtime type information.
cyclicAMIPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from components.
virtual ~cyclicAMIPointPatch ()
Destructor.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
const cyclicAMIPolyPatch & cyclicAMIPatch () const
Return the underlying cyclicAMIPolyPatch.
const cyclicAMIPointPatch & neighbPatch () const
Return neighbour point patch.
bool parallel () const
Are the cyclic planes parallel.
const tensorField & forwardT () const
Return face transformation tensor.
const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
Public Member Functions inherited from coupledFacePointPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFacePointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from components.
virtual ~coupledFacePointPatch ()
Destructor.
Public Member Functions inherited from facePointPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &, const pointBoundaryMesh &)
Construct from polyPatch.
virtual ~facePointPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label size () const
Return size.
virtual label index () const
Return the index of this patch in the pointBoundaryMesh.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const
Return mesh points.
virtual const pointField & localPoints () const
Return pointField of points in patch.
virtual const vectorField & pointNormals () const
Return point unit normals.
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()
Destructor.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Public Member Functions inherited from coupledPointPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledPointPatch (const pointBoundaryMesh &bm)
Construct from components.
virtual ~coupledPointPatch ()
Destructor.
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Additional Inherited Members
Static Public Member Functions inherited from facePointPatch
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
Protected Attributes inherited from facePointPatch
const polyPatch & polyPatch_
Reference to the underlying polyPatch.
Detailed Description
Cyclic AMI point patch - place holder only.
Source files
cyclicAMIPointPatch.H
cyclicAMIPointPatch.C
Definition at line 50 of file cyclicAMIPointPatch.H.
Constructor & Destructor Documentation
cyclicAMIPointPatch()
cyclicAMIPointPatch (const polyPatch & patch, const pointBoundaryMesh & bm)
Construct from components.
Definition at line 83 of file cyclicAMIPointPatch.C.
~cyclicAMIPointPatch()
~cyclicAMIPointPatch () virtual
Destructor.
Definition at line 95 of file cyclicAMIPointPatch.C.
Member Function Documentation
initGeometry()
void initGeometry (PstreamBuffers &) protected virtual
Initialise the calculation of the patch geometry.
Implements coupledPointPatch.
Definition at line 46 of file cyclicAMIPointPatch.C.
calcGeometry()
void calcGeometry (PstreamBuffers &) protected virtual
Calculate the patch geometry.
Implements coupledFacePointPatch.
Definition at line 50 of file cyclicAMIPointPatch.C.
References cyclicAMIPointPatch::initMovePoints().
initMovePoints()
void initMovePoints (PstreamBuffers & , const pointField &) protected virtual
Initialise the patches for moving points.
Implements coupledPointPatch.
Definition at line 55 of file cyclicAMIPointPatch.C.
Referenced by cyclicAMIPointPatch::calcGeometry().
movePoints()
void movePoints (PstreamBuffers & , const pointField &) protected virtual
Correct patches after moving points.
Implements coupledPointPatch.
Definition at line 62 of file cyclicAMIPointPatch.C.
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Implements coupledPointPatch.
Definition at line 66 of file cyclicAMIPointPatch.C.
References facePointPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Update of the patch topology.
Implements coupledPointPatch.
Definition at line 73 of file cyclicAMIPointPatch.C.
References facePointPatch::updateMesh().
TypeName()
TypeName (cyclicAMIPolyPatch::typeName_())
Runtime type information.
constraintType()
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatch implements.
Reimplemented from pointPatch.
Definition at line 115 of file cyclicAMIPointPatch.H.
References Foam::type().
cyclicAMIPatch()
const cyclicAMIPolyPatch& cyclicAMIPatch () const inline
Return the underlying cyclicAMIPolyPatch.
Definition at line 121 of file cyclicAMIPointPatch.H.
neighbPatch()
const cyclicAMIPointPatch& neighbPatch () const inline
Return neighbour point patch.
Definition at line 127 of file cyclicAMIPointPatch.H.
References pointPatch::boundaryMesh(), cyclicAMIPolyPatch::neighbPatchID(), and patchi.
Referenced by cyclicAMIPointPatchField< Type >::swapAddSeparated().
parallel()
bool parallel () const inline
Are the cyclic planes parallel.
Definition at line 135 of file cyclicAMIPointPatch.H.
References coupledPolyPatch::parallel().
Referenced by cyclicAMIPointPatchField< Type >::doTransform().
forwardT()
const tensorField& forwardT () const inline
Return face transformation tensor.
Definition at line 141 of file cyclicAMIPointPatch.H.
References coupledPolyPatch::forwardT().
Referenced by cyclicAMIPointPatchField< Type >::forwardT().
reverseT()
const tensorField& reverseT () const inline
Return neighbour-cell transformation tensor.
Definition at line 147 of file cyclicAMIPointPatch.H.
References coupledPolyPatch::reverseT().
Referenced by cyclicAMIPointPatchField< Type >::reverseT().
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatch/cyclicAMIPointPatch.H
src/meshTools/AMIInterpolation/patches/cyclicAMI/cyclicAMIPointPatch/cyclicAMIPointPatch.C