OpenFOAM: EulerCoordinateRotation Class Reference
EulerCoordinateRotation Class Reference
A coordinateRotation defined in the z-x-y Euler convention.
Public Member Functions
TypeName ("EulerRotation")
Runtime type information.
EulerCoordinateRotation ()
Construct null.
EulerCoordinateRotation (const vector &phiThetaPsi, const bool inDegrees=true)
Construct from rotation vector.
EulerCoordinateRotation (const scalar phiAngle, const scalar thetaAngle, const scalar psiAngle, const bool inDegrees=true)
Construct from components of rotation vector.
EulerCoordinateRotation (const dictionary &)
Construct from dictionary.
EulerCoordinateRotation (const dictionary &, const objectRegistry &)
Construct from dictionary and mesh.
virtual void clear ()
Reset rotation to an identity rotation.
virtual void updateCells (const polyMesh &, const labelList &)
Update the rotation for a list of cells.
virtual const tensor & R () const
Return local-to-global transformation tensor.
virtual const tensor & Rtr () const
Return global-to-local transformation tensor.
virtual const vector e1 () const
Return local Cartesian x-axis in global coordinates.
virtual const vector e2 () const
Return local Cartesian y-axis in global coordinates.
virtual const vector e3 () const
Return local Cartesian z-axis in global coordinates.
virtual const tensorField & Tr () const
Return transformation tensor field.
virtual tmp< vectorField > transform (const vectorField &st) const
Transform vectorField using transformation tensor field.
virtual vector transform (const vector &st) const
Transform vector using transformation tensor.
virtual tmp< vectorField > invTransform (const vectorField &st) const
Inverse transform vectorField using transformation tensor field.
virtual vector invTransform (const vector &st) const
Inverse transform vector using transformation tensor.
virtual tmp< tensorField > transformTensor (const tensorField &st) const
Transform tensor field using transformation tensorField.
virtual tensor transformTensor (const tensor &st) const
Transform tensor using transformation tensorField.
virtual tmp< tensorField > transformTensor (const tensorField &st, const labelList &cellMap) const
Transform tensor sub-field using transformation tensorField.
virtual tmp< symmTensorField > transformVector (const vectorField &st) const
Transform vectorField using transformation tensorField and return.
virtual symmTensor transformVector (const vector &st) const
Transform vector using transformation tensor and return.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from coordinateRotation
TypeName ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, coordinateRotation, objectRegistry,(const dictionary &dict, const objectRegistry &obr),(dict, obr))
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()
Destructor.
virtual bool uniform () const
Return true if the rotation tensor is uniform.
Additional Inherited Members
Static Public Member Functions inherited from coordinateRotation
static autoPtr< coordinateRotation > New (const dictionary &dict, const objectRegistry &obr)
Select constructed from dictionary and objectRegistry.
static autoPtr< coordinateRotation > New (const dictionary &dict)
Select constructed from dictionary.
Protected Member Functions inherited from coordinateRotation
symmTensor transformPrincipal (const tensor &, const vector &) const
Transform principal.
Detailed Description
A coordinateRotation defined in the z-x-y Euler convention.
The 3 rotations are defined in the Euler convention (around Z, around X' and around Z'). For reference and illustration, see http://mathworld.wolfram.com/EulerAngles.html Note, however, that it is the reverse transformation (local->global) that is defined here.
the rotation angles are in degrees, unless otherwise explicitly specified:
coordinateRotation
{
    type        EulerRotation;
    degrees     false;
    rotation    (0 0 3.141592654);
}
Source files
EulerCoordinateRotation.H
EulerCoordinateRotation.C
Definition at line 66 of file EulerCoordinateRotation.H.
Constructor & Destructor Documentation
EulerCoordinateRotation() [1/5]
EulerCoordinateRotation ()
Construct null.
Definition at line 195 of file EulerCoordinateRotation.C.
Referenced by EulerCoordinateRotation::EulerCoordinateRotation().
EulerCoordinateRotation() [2/5]
EulerCoordinateRotation (const vector & phiThetaPsi, const bool inDegrees = true)
Construct from rotation vector.
Definition at line 203 of file EulerCoordinateRotation.C.
References VectorSpace< Form, Cmpt, Ncmpts >::component(), EulerCoordinateRotation::EulerCoordinateRotation(), Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
EulerCoordinateRotation() [3/5]
EulerCoordinateRotation (const scalar phiAngle, const scalar thetaAngle, const scalar psiAngle, const bool inDegrees = true)
Construct from components of rotation vector.
Definition at line 222 of file EulerCoordinateRotation.C.
References EulerCoordinateRotation::EulerCoordinateRotation().
EulerCoordinateRotation() [4/5]
EulerCoordinateRotation (const dictionary & dict)
Construct from dictionary.
Definition at line 237 of file EulerCoordinateRotation.C.
References EulerCoordinateRotation::EulerCoordinateRotation(), dictionary::lookup(), dictionary::lookupOrDefault(), Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
EulerCoordinateRotation() [5/5]
EulerCoordinateRotation (const dictionary & dict, const objectRegistry &)
Construct from dictionary and mesh.
Definition at line 257 of file EulerCoordinateRotation.C.
References dictionary::lookup(), dictionary::lookupOrDefault(), Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
Member Function Documentation
TypeName()
TypeName ("EulerRotation")
Runtime type information.
clear()
virtual void clear () inline virtual
Reset rotation to an identity rotation.
Implements coordinateRotation.
Definition at line 129 of file EulerCoordinateRotation.H.
References SphericalTensor< Cmpt >::I.
updateCells()
virtual void updateCells (const polyMesh & , const labelList &) inline virtual
Update the rotation for a list of cells.
Implements coordinateRotation.
Definition at line 136 of file EulerCoordinateRotation.H.
R()
virtual const tensor& R () const inline virtual
Return local-to-global transformation tensor.
Implements coordinateRotation.
Definition at line 142 of file EulerCoordinateRotation.H.
Rtr()
virtual const tensor& Rtr () const inline virtual
Return global-to-local transformation tensor.
Implements coordinateRotation.
Definition at line 148 of file EulerCoordinateRotation.H.
e1()
virtual const vector e1 () const inline virtual
Return local Cartesian x-axis in global coordinates.
Implements coordinateRotation.
Definition at line 154 of file EulerCoordinateRotation.H.
References Tensor< Cmpt >::x().
Referenced by EulerCoordinateRotation::write().
e2()
virtual const vector e2 () const inline virtual
Return local Cartesian y-axis in global coordinates.
Implements coordinateRotation.
Definition at line 160 of file EulerCoordinateRotation.H.
References Tensor< Cmpt >::y().
Referenced by EulerCoordinateRotation::write().
e3()
virtual const vector e3 () const inline virtual
Return local Cartesian z-axis in global coordinates.
Implements coordinateRotation.
Definition at line 166 of file EulerCoordinateRotation.H.
References EulerCoordinateRotation::invTransform(), EulerCoordinateRotation::Tr(), EulerCoordinateRotation::transform(), EulerCoordinateRotation::transformTensor(), EulerCoordinateRotation::transformVector(), EulerCoordinateRotation::write(), and Tensor< Cmpt >::z().
Referenced by EulerCoordinateRotation::write().
Tr()
const Foam::tensorField & Tr () const virtual
Return transformation tensor field.
Implements coordinateRotation.
Definition at line 87 of file EulerCoordinateRotation.C.
References NotImplemented, and EulerCoordinateRotation::transformTensor().
Referenced by EulerCoordinateRotation::e3().
transform() [1/2]
Foam::tmp< Foam::vectorField > transform (const vectorField & st) const virtual
Transform vectorField using transformation tensor field.
Implements coordinateRotation.
Definition at line 68 of file EulerCoordinateRotation.C.
References EulerCoordinateRotation::invTransform(), and NotImplemented.
Referenced by EulerCoordinateRotation::e3(), and EulerCoordinateRotation::invTransform().
transform() [2/2]
Foam::vector transform (const vector & st) const virtual
Transform vector using transformation tensor.
Implements coordinateRotation.
Definition at line 52 of file EulerCoordinateRotation.C.
References EulerCoordinateRotation::invTransform().
invTransform() [1/2]
Foam::tmp< Foam::vectorField > invTransform (const vectorField & st) const virtual
Inverse transform vectorField using transformation tensor field.
Implements coordinateRotation.
Definition at line 78 of file EulerCoordinateRotation.C.
References NotImplemented.
Referenced by EulerCoordinateRotation::e3(), and EulerCoordinateRotation::transform().
invTransform() [2/2]
Foam::vector invTransform (const vector & st) const virtual
Inverse transform vector using transformation tensor.
Implements coordinateRotation.
Definition at line 59 of file EulerCoordinateRotation.C.
References EulerCoordinateRotation::transform().
transformTensor() [1/3]
Foam::tmp< Foam::tensorField > transformTensor (const tensorField & st) const virtual
Transform tensor field using transformation tensorField.
Implements coordinateRotation.
Definition at line 95 of file EulerCoordinateRotation.C.
References NotImplemented.
Referenced by EulerCoordinateRotation::e3(), EulerCoordinateRotation::Tr(), and EulerCoordinateRotation::transformTensor().
transformTensor() [2/3]
Foam::tensor transformTensor (const tensor & st) const virtual
Transform tensor using transformation tensorField.
Implements coordinateRotation.
Definition at line 105 of file EulerCoordinateRotation.C.
References EulerCoordinateRotation::transformTensor().
transformTensor() [3/3]
Foam::tmp< Foam::tensorField > transformTensor (const tensorField & st, const labelList & cellMap) const virtual
Transform tensor sub-field using transformation tensorField.
Implements coordinateRotation.
Definition at line 114 of file EulerCoordinateRotation.C.
References NotImplemented, and EulerCoordinateRotation::transformVector().
transformVector() [1/2]
Foam::tmp< Foam::symmTensorField > transformVector (const vectorField & st) const virtual
Transform vectorField using transformation tensorField and return.
symmetrical tensorField
Implements coordinateRotation.
Definition at line 126 of file EulerCoordinateRotation.C.
References fld(), forAll, tmp< T >::ref(), and List< T >::size().
Referenced by EulerCoordinateRotation::e3(), and EulerCoordinateRotation::transformTensor().
transformVector() [2/2]
Foam::symmTensor transformVector (const vector & st) const virtual
Transform vector using transformation tensor and return.
symmetrical tensor
Implements coordinateRotation.
Definition at line 142 of file EulerCoordinateRotation.C.
References Foam::cos(), phi, Foam::constant::mathematical::pi(), psi, and Foam::sin().
write()
void write (Ostream & os) const virtual
Write.
Implements coordinateRotation.
Definition at line 277 of file EulerCoordinateRotation.C.
References EulerCoordinateRotation::e1(), EulerCoordinateRotation::e2(), EulerCoordinateRotation::e3(), token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by EulerCoordinateRotation::e3().
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/coordinateRotation/EulerCoordinateRotation.H
src/meshTools/coordinateSystems/coordinateRotation/EulerCoordinateRotation.C