OpenFOAM: cartesianCS Class Reference
cartesianCS Class Reference
Cylindrical coordinate system.
Public Member Functions
TypeName ("cartesian")
Runtime type information.
cartesianCS ()
Construct null.
cartesianCS (const coordinateSystem &)
Construct copy.
cartesianCS (const word &name, const coordinateSystem &)
Construct copy with a different name.
cartesianCS (const word &name, const point &origin, const coordinateRotation &)
Construct from origin and rotation.
cartesianCS (const word &name, const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
cartesianCS (const word &, const dictionary &)
Construct from dictionary.
cartesianCS (const objectRegistry &, const dictionary &)
Construct from dictionary and objectRegistry.
virtual ~cartesianCS ()
Destructor.
Public Member Functions inherited from coordinateSystem
TypeName ("coordinateSystem")
Runtime type information.
coordinateSystem ()
Construct null. This is equivalent to an identity coordinateSystem.
coordinateSystem (const word &name, const coordinateSystem &)
Construct copy with a different name.
coordinateSystem (const word &name, const point &origin, const coordinateRotation &)
Construct from origin and rotation.
coordinateSystem (const word &name, const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
coordinateSystem (const word &name, const dictionary &)
Construct from dictionary with a given name.
coordinateSystem (const dictionary &)
Construct from dictionary with default name.
coordinateSystem (const objectRegistry &, const dictionary &)
Construct from dictionary (default name)
coordinateSystem (Istream &)
Construct from Istream.
autoPtr< coordinateSystem > clone () const
Return clone.
declareRunTimeSelectionTable (autoPtr, coordinateSystem, dictionary,(const objectRegistry &obr, const dictionary &dict),(obr, dict))
virtual ~coordinateSystem ()
Destructor.
const word & name () const
Return name.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
const point & origin () const
Return origin.
const coordinateRotation & R () const
Return const reference to co-ordinate rotation.
coordinateRotation & R ()
Return non const reference to co-ordinate rotation.
const coordinateRotation & R (const polyMesh &mesh, const labelList &cells)
Update and return the co-ordinate roation for a list of cells.
virtual dictionary dict (bool ignoreType=false) const
Return as dictionary of entries.
void rename (const word &newName)
Rename.
point & origin ()
Edit access to origin.
virtual void clear ()
Reset origin and rotation to an identity coordinateSystem.
virtual void write (Ostream &) const
Write.
void writeDict (Ostream &, bool subDict=true) const
Write dictionary.
point globalPosition (const point &local) const
Convert from position in local coordinate system to global.
tmp< pointField > globalPosition (const pointField &local) const
Convert from position in local coordinate system to global.
vector globalVector (const vector &local) const
Convert from vector components in local coordinate system to.
tmp< vectorField > globalVector (const vectorField &local) const
Convert from vector components in local coordinate system to.
point localPosition (const point &global) const
Convert from global Cartesian position to position in local.
tmp< pointField > localPosition (const pointField &global) const
Convert from global Cartesian position to position in local.
vector localVector (const vector &global) const
Convert from global Cartesian vector to components in local.
tmp< vectorField > localVector (const vectorField &global) const
Convert from global Cartesian vector to components in local.
Protected Member Functions
virtual vector localToGlobal (const vector &, bool translate) const
Convert from local coordinate system to the global Cartesian system.
virtual tmp< vectorField > localToGlobal (const vectorField &, bool translate) const
Convert from local coordinate system to the global Cartesian system.
virtual vector globalToLocal (const vector &, bool translate) const
Convert from global Cartesian system to the local coordinate system.
virtual tmp< vectorField > globalToLocal (const vectorField &, bool translate) const
Convert from global Cartesian system to the local coordinate system.
Protected Member Functions inherited from coordinateSystem
void init (const dictionary &)
Init from dict and obr.
void init (const dictionary &, const objectRegistry &)
Init from dictionary.
Additional Inherited Members
Static Public Member Functions inherited from coordinateSystem
static autoPtr< coordinateSystem > New (const objectRegistry &obr, const dictionary &dict)
Select constructed from dictionary and objectRegistry.
static autoPtr< coordinateSystem > New (const dictionary &dict)
Select constructed from dictionary.
static autoPtr< coordinateSystem > New (Istream &is)
Select constructed from Istream.
Detailed Description
Cylindrical coordinate system.
Source files
cartesianCS.H
cartesianCS.C
Definition at line 49 of file cartesianCS.H.
Constructor & Destructor Documentation
cartesianCS() [1/7]
cartesianCS ()
Construct null.
Definition at line 43 of file cartesianCS.C.
Referenced by cartesianCS::cartesianCS().
cartesianCS() [2/7]
cartesianCS (const coordinateSystem & cs)
Construct copy.
Definition at line 50 of file cartesianCS.C.
References cartesianCS::cartesianCS().
cartesianCS() [3/7]
cartesianCS (const word & name, const coordinateSystem & cs)
Construct copy with a different name.
Definition at line 59 of file cartesianCS.C.
References cartesianCS::cartesianCS().
cartesianCS() [4/7]
cartesianCS (const word & name, const point & origin, const coordinateRotation & cr)
Construct from origin and rotation.
Definition at line 69 of file cartesianCS.C.
References cartesianCS::cartesianCS().
cartesianCS() [5/7]
cartesianCS (const word & name, const point & origin, const vector & axis, const vector & dirn)
Construct from origin and 2 axes.
Definition at line 80 of file cartesianCS.C.
References cartesianCS::cartesianCS().
cartesianCS() [6/7]
cartesianCS (const word & name, const dictionary & dict)
Construct from dictionary.
Definition at line 92 of file cartesianCS.C.
References cartesianCS::cartesianCS().
cartesianCS() [7/7]
cartesianCS (const objectRegistry & obr, const dictionary & dict)
Construct from dictionary and objectRegistry.
Definition at line 102 of file cartesianCS.C.
~cartesianCS()
~cartesianCS () virtual
Destructor.
Definition at line 113 of file cartesianCS.C.
References cartesianCS::localToGlobal().
Member Function Documentation
localToGlobal() [1/2]
Foam::vector localToGlobal (const vector & local, bool translate) const protected virtual
Convert from local coordinate system to the global Cartesian system.
with optional translation for the origin
Reimplemented from coordinateSystem.
Definition at line 121 of file cartesianCS.C.
References coordinateSystem::localToGlobal().
Referenced by cartesianCS::~cartesianCS().
localToGlobal() [2/2]
Foam::tmp< Foam::vectorField > localToGlobal (const vectorField & local, bool translate) const protected virtual
Convert from local coordinate system to the global Cartesian system.
with optional translation for the origin
Reimplemented from coordinateSystem.
Definition at line 131 of file cartesianCS.C.
References cartesianCS::globalToLocal(), and coordinateSystem::localToGlobal().
globalToLocal() [1/2]
Foam::vector globalToLocal (const vector & global, bool translate) const protected virtual
Convert from global Cartesian system to the local coordinate system.
with optional translation for the origin
Reimplemented from coordinateSystem.
Definition at line 141 of file cartesianCS.C.
References coordinateSystem::globalToLocal().
Referenced by cartesianCS::localToGlobal().
globalToLocal() [2/2]
Foam::tmp< Foam::vectorField > globalToLocal (const vectorField & global, bool translate) const protected virtual
Convert from global Cartesian system to the local coordinate system.
with optional translation for the origin
Reimplemented from coordinateSystem.
Definition at line 151 of file cartesianCS.C.
References coordinateSystem::globalToLocal().
TypeName()
TypeName ("cartesian")
Runtime type information.
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/cartesianCS.H
src/meshTools/coordinateSystems/cartesianCS.C