OpenFOAM: edgeFaceCirculator Class Reference
edgeFaceCirculator Class Reference
Walks from starting face around edge.
Public Member Functions
edgeFaceCirculator (const primitiveMesh &mesh, const label faceLabel, const bool ownerSide, const label index, const bool isBoundaryEdge)
Construct from components.
edgeFaceCirculator (const edgeFaceCirculator &)
Construct as copy.
label faceLabel () const
bool ownerSide () const
label index () const
label cellLabel () const
Helper: get the neighbouring cell according to the ownerSide.
bool sameOrder (const label v0, const label v1) const
Helper: return true if normal of generated face points along.
void setCanonical ()
Set edge to a unique state so different ones can be compared.
void operator= (const edgeFaceCirculator &iter)
bool operator== (const edgeFaceCirculator &iter) const
bool operator!= (const edgeFaceCirculator &iter) const
edgeFaceCirculator & operator++ ()
Step to next face. Uses no edge addressing!
edgeFaceCirculator begin () const
Iterator set to the beginning face. For internal edges this is.
edgeFaceCirculator cbegin () const
const edgeFaceCirculator & end () const
Iterator set to beyond the end of the walk.
const edgeFaceCirculator & cend () const
Static Public Member Functions
static label getMinIndex (const face &f, const label v0, const label v1)
Helper: find index in face of edge or -1. Index is such that edge is.
Detailed Description
Walks from starting face around edge.
Implicit description of edge:
face
index in face. edge is always between f[index] and f[index+1]
direction (cell to walk into)
Use in-place:
edgeFaceCirculator circ(..);
// Optionally rotate to beginning: circ.setCanonical();
// Walk
do
{
    Info<< "face:" << circ.face() << endl;
    ++circ;
}
while (circ != circ.end());
Use like STL iterator:
edgeFaceCirculator circ(..);
for
(
    edgeFaceCirculator iter = circ.begin();
    iter != circ.end();
    ++iter
)
{
    Info<< "face:" << iter.face() << endl;
}
Source files
edgeFaceCirculator.H
edgeFaceCirculator.C
Definition at line 86 of file edgeFaceCirculator.H.
Constructor & Destructor Documentation
edgeFaceCirculator() [1/2]
edgeFaceCirculator (const primitiveMesh & mesh, const label faceLabel, const bool ownerSide, const label index, const bool isBoundaryEdge) inline
Construct from components.
Definition at line 93 of file edgeFaceCirculatorI.H.
edgeFaceCirculator() [2/2]
edgeFaceCirculator (const edgeFaceCirculator & circ) inline
Construct as copy.
Construct copy.
Definition at line 111 of file edgeFaceCirculatorI.H.
References edgeFaceCirculator::getMinIndex().
Member Function Documentation
getMinIndex()
Foam::label getMinIndex (const face & f, const label v0, const label v1) inline static
Helper: find index in face of edge or -1. Index is such that edge is.
between f[index] and f[index+1]
Definition at line 125 of file edgeFaceCirculatorI.H.
References UList< T >::fcIndex(), Foam::findIndex(), and UList< T >::rcIndex().
Referenced by edgeFaceCirculator::edgeFaceCirculator(), and edgeFaceCirculator::sameOrder().
faceLabel()
Foam::label faceLabel () const inline
Definition at line 155 of file edgeFaceCirculatorI.H.
ownerSide()
bool ownerSide () const inline
Definition at line 161 of file edgeFaceCirculatorI.H.
index()
Foam::label index () const inline
Definition at line 167 of file edgeFaceCirculatorI.H.
cellLabel()
Foam::label cellLabel () const inline
Helper: get the neighbouring cell according to the ownerSide.
Returns -1 if on neighbourside of boundary face.
Definition at line 173 of file edgeFaceCirculatorI.H.
References primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), and primitiveMesh::isInternalFace().
sameOrder()
bool sameOrder (const label v0, const label v1) const inline
Helper: return true if normal of generated face points along.
edge from v0 to v1. (v0 and v1 have to be on edge)
Definition at line 190 of file edgeFaceCirculatorI.H.
References Foam::abort(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, and edgeFaceCirculator::getMinIndex().
setCanonical()
void setCanonical () inline
Set edge to a unique state so different ones can be compared.
Internal edge: minimum face index. Boundary edge: walk back until boundary face.
Definition at line 210 of file edgeFaceCirculatorI.H.
References Foam::abort(), edgeFaceCirculator::end(), Foam::endl(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::isInternalFace(), face::nextLabel(), edgeFaceCirculator::operator++(), and primitiveMesh::points().
Referenced by edgeFaceCirculator::begin(), and edgeFaceCirculator::cbegin().
operator=()
void operator= (const edgeFaceCirculator & iter) inline
Definition at line 314 of file edgeFaceCirculatorI.H.
operator==()
bool operator== (const edgeFaceCirculator & iter) const inline
Definition at line 324 of file edgeFaceCirculatorI.H.
operator!=()
bool operator!= (const edgeFaceCirculator & iter) const inline
Definition at line 344 of file edgeFaceCirculatorI.H.
operator++()
Foam::edgeFaceCirculator & operator++ () inline
Step to next face. Uses no edge addressing!
Step to next face.
Definition at line 352 of file edgeFaceCirculatorI.H.
References Foam::abort(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), Foam::FatalError, FatalErrorInFunction, and primitiveMesh::isInternalFace().
Referenced by edgeFaceCirculator::setCanonical().
begin()
Foam::edgeFaceCirculator begin () const inline
Iterator set to the beginning face. For internal edges this is.
the current face. For boundary edges this is the first boundary face reached from walking back (i.e. in opposite direction to ++)
Definition at line 398 of file edgeFaceCirculatorI.H.
References edgeFaceCirculator::setCanonical().
cbegin()
Foam::edgeFaceCirculator cbegin () const inline
Definition at line 417 of file edgeFaceCirculatorI.H.
References edgeFaceCirculator::setCanonical().
end()
const Foam::edgeFaceCirculator & end () const inline
Iterator set to beyond the end of the walk.
Definition at line 436 of file edgeFaceCirculatorI.H.
Referenced by edgeFaceCirculator::setCanonical().
cend()
const Foam::edgeFaceCirculator & cend () const inline
Definition at line 441 of file edgeFaceCirculatorI.H.
The documentation for this class was generated from the following files:
src/meshTools/edgeFaceCirculator/edgeFaceCirculator.H
src/meshTools/edgeFaceCirculator/edgeFaceCirculatorI.H