OpenFOAM: treeDataPrimitivePatch< PatchType > Class Template Reference
treeDataPrimitivePatch< PatchType > Class Template Reference
Encapsulation of data needed to search on PrimitivePatches.
Classes
class findAllIntersectOp
class findIntersectOp
class findNearestOp
class findSelfIntersectOp
Public Member Functions
treeDataPrimitivePatch (const bool cacheBb, const PatchType &, const scalar planarTol)
Construct from patch.
label size () const
pointField shapePoints () const
Get representative point cloud for all shapes inside.
const PatchType & patch () const
Return access to the underlying patch.
volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< PatchType >> &, const point &) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
bool overlaps (const label index, const treeBoundBox &sampleBb) const
Does shape at index overlap bb.
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
Does shape at index overlap sphere.
template<>
Foam::volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface >> &oc, const point &sample) const
template<>
volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface >> &oc, const point &sample) const
Template specialisation of getVolumeType for treeDataTriSurface.
Static Public Member Functions
static bool findIntersection (const indexedOctree< treeDataPrimitivePatch< PatchType >> &tree, const label index, const point &start, const point &end, point &intersectionPoint)
Helper: find intersection of line with shapes.
Detailed Description
template<class PatchType>
class Foam::treeDataPrimitivePatch< PatchType >
Encapsulation of data needed to search on PrimitivePatches.
Source files
treeDataPrimitivePatch.H
treeDataPrimitivePatch.C
Definition at line 61 of file treeDataPrimitivePatch.H.
Constructor & Destructor Documentation
treeDataPrimitivePatch()
treeDataPrimitivePatch (const bool cacheBb, const PatchType & patch, const scalar planarTol)
Construct from patch.
Definition at line 74 of file treeDataPrimitivePatch.C.
References treeDataPrimitivePatch< PatchType >::findNearestOp::findNearestOp().
Member Function Documentation
size()
label size () const inline
Definition at line 212 of file treeDataPrimitivePatch.H.
References treeDataPrimitivePatch< PatchType >::shapePoints().
shapePoints()
Foam::pointField shapePoints () const
Get representative point cloud for all shapes inside.
(one point per shape)
Definition at line 136 of file treeDataPrimitivePatch.C.
References forAll, and treeDataPrimitivePatch< PatchType >::getVolumeType().
Referenced by treeDataPrimitivePatch< PatchType >::size().
patch()
const PatchType& patch () const inline
Return access to the underlying patch.
Definition at line 222 of file treeDataPrimitivePatch.H.
References treeDataPrimitivePatch< PatchType >::findIntersection(), treeDataPrimitivePatch< PatchType >::getVolumeType(), and treeDataPrimitivePatch< PatchType >::overlaps().
Referenced by treeDataPrimitivePatch< PatchType >::findIntersection(), treeDataPrimitivePatch< PatchType >::findNearestOp::operator()(), and treeDataPrimitivePatch< PatchType >::findSelfIntersectOp::operator()().
getVolumeType() [1/3]
Foam::volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< PatchType >> & oc, const point & sample) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
Only makes sense for closed surfaces.
Definition at line 151 of file treeDataPrimitivePatch.C.
References Foam::abort(), Foam::constant::electromagnetic::e, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, PointHit< Point >::hit(), PointIndexHit< Point >::index(), edge::line(), Foam::mag(), Foam::magSqr(), line< Point, PointRef >::nearestDist(), treeDataPrimitivePatch< PatchType >::overlaps(), Foam::Pout, PointHit< Point >::rawPoint(), Foam::sqr(), and Foam::Zero.
Referenced by treeDataPrimitivePatch< PatchType >::patch(), and treeDataPrimitivePatch< PatchType >::shapePoints().
overlaps() [1/2]
bool overlaps (const label index, const treeBoundBox & sampleBb) const
Does shape at index overlap bb.
Definition at line 384 of file treeDataPrimitivePatch.C.
References Vector< Cmpt >::centre(), boundBox::containsAny(), forAll, and boundBox::overlaps().
Referenced by treeDataPrimitivePatch< PatchType >::getVolumeType(), and treeDataPrimitivePatch< PatchType >::patch().
overlaps() [2/2]
bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Does shape at index overlap sphere.
Definition at line 456 of file treeDataPrimitivePatch.C.
References PointHit< Point >::distance(), face::nearestPoint(), and Foam::sqr().
findIntersection()
bool findIntersection (const indexedOctree< treeDataPrimitivePatch< PatchType >> & tree, const label index, const point & start, const point & end, point & intersectionPoint) static
Helper: find intersection of line with shapes.
Definition at line 611 of file treeDataPrimitivePatch.C.
References PointHit< Point >::distance(), PointHit< Point >::hit(), PointHit< Point >::hitPoint(), treeDataPrimitivePatch< PatchType >::patch(), and treeBoundBox::posBits().
Referenced by treeDataPrimitivePatch< PatchType >::findSelfIntersectOp::operator()(), and treeDataPrimitivePatch< PatchType >::patch().
getVolumeType() [2/3]
Foam::volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface >> & oc, const point & sample) const
Definition at line 33 of file treeDataTriSurface.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, PointIndexHit< Point >::index(), and Foam::sqr().
getVolumeType() [3/3]
volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface >> & oc, const point & sample) const
Template specialisation of getVolumeType for treeDataTriSurface.
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataPrimitivePatch.H
src/meshTools/indexedOctree/treeDataPrimitivePatch.C