OpenFOAM: axesRotation Class Reference
axesRotation Class Reference
A coordinate rotation specified using global axis.
Public Member Functions
TypeName ("axesRotation")
Runtime type information.
axesRotation ()
Construct null.
axesRotation (const vector &axis, const vector &dir)
Construct from 2 axes.
axesRotation (const dictionary &)
Construct from dictionary.
axesRotation (const tensor &R)
Construct from components.
axesRotation (const dictionary &, const objectRegistry &)
Construct from dictionary and mesh.
autoPtr< axesRotation > clone () const
Return clone.
virtual ~axesRotation ()
Destructor.
virtual void clear ()
Reset rotation to an identity rotation.
virtual void updateCells (const polyMesh &, const labelList &)
Update the rotation for a list of cells.
virtual const tensor & R () const
Return local-to-global transformation tensor.
virtual const tensor & Rtr () const
Return global-to-local transformation tensor.
virtual const vector e1 () const
Return local Cartesian x-axis in global coordinates.
virtual const vector e2 () const
Return local Cartesian y-axis in global coordinates.
virtual const vector e3 () const
Return local Cartesian z-axis in global coordinates.
virtual const tensorField & Tr () const
Return transformation tensor field.
virtual tmp< vectorField > transform (const vectorField &st) const
Transform vectorField using transformation tensor field.
virtual vector transform (const vector &st) const
Transform vector using transformation tensor.
virtual tmp< vectorField > invTransform (const vectorField &st) const
Inverse transform vectorField using transformation tensor field.
virtual vector invTransform (const vector &st) const
Inverse transform vector using transformation tensor.
virtual tmp< tensorField > transformTensor (const tensorField &st) const
Transform tensor field using transformation tensorField.
virtual tensor transformTensor (const tensor &st) const
Transform tensor using transformation tensorField.
virtual tmp< tensorField > transformTensor (const tensorField &st, const labelList &cellMap) const
Transform tensor sub-field using transformation tensorField.
virtual tmp< symmTensorField > transformVector (const vectorField &st) const
Transform vectorField using transformation tensorField and return.
virtual symmTensor transformVector (const vector &st) const
Transform vector using transformation tensor and return.
void operator= (const dictionary &)
Assign from dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from coordinateRotation
TypeName ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, coordinateRotation, objectRegistry,(const dictionary &dict, const objectRegistry &obr),(dict, obr))
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()
Destructor.
virtual bool uniform () const
Return true if the rotation tensor is uniform.
Additional Inherited Members
Static Public Member Functions inherited from coordinateRotation
static autoPtr< coordinateRotation > New (const dictionary &dict, const objectRegistry &obr)
Select constructed from dictionary and objectRegistry.
static autoPtr< coordinateRotation > New (const dictionary &dict)
Select constructed from dictionary.
Protected Member Functions inherited from coordinateRotation
symmTensor transformPrincipal (const tensor &, const vector &) const
Transform principal.
Detailed Description
A coordinate rotation specified using global axis.
The rotation is defined by a combination of vectors (e1/e2), (e2/e3) or (e3/e1). Any nonorthogonality will be absorbed into the second vector.
axesRotation
{
    type        axesRotation;
    e1          (1 0 0);
    e2          (0 1 0);
}
Source files
axesRotation.H
axesRotation.C
Definition at line 64 of file axesRotation.H.
Constructor & Destructor Documentation
axesRotation() [1/5]
axesRotation ()
Construct null.
Definition at line 108 of file axesRotation.C.
Referenced by axesRotation::axesRotation(), and axesRotation::clone().
axesRotation() [2/5]
axesRotation (const vector & axis, const vector & dir)
Construct from 2 axes.
Definition at line 116 of file axesRotation.C.
References axesRotation::axesRotation().
axesRotation() [3/5]
axesRotation (const dictionary & dict)
Construct from dictionary.
Definition at line 129 of file axesRotation.C.
References axesRotation::axesRotation(), and axesRotation::operator=().
axesRotation() [4/5]
axesRotation (const tensor & R)
Construct from components.
Definition at line 153 of file axesRotation.C.
axesRotation() [5/5]
axesRotation (const dictionary & dict, const objectRegistry & obr)
Construct from dictionary and mesh.
Definition at line 141 of file axesRotation.C.
References axesRotation::operator=().
~axesRotation()
virtual ~axesRotation () inline virtual
Destructor.
Definition at line 125 of file axesRotation.H.
Member Function Documentation
TypeName()
TypeName ("axesRotation")
Runtime type information.
clone()
autoPtr<axesRotation> clone () const inline
Return clone.
Definition at line 118 of file axesRotation.H.
References axesRotation::axesRotation().
clear()
virtual void clear () inline virtual
Reset rotation to an identity rotation.
Implements coordinateRotation.
Definition at line 132 of file axesRotation.H.
References SphericalTensor< Cmpt >::I.
updateCells()
virtual void updateCells (const polyMesh & , const labelList &) inline virtual
Update the rotation for a list of cells.
Implements coordinateRotation.
Definition at line 139 of file axesRotation.H.
R()
virtual const tensor& R () const inline virtual
Return local-to-global transformation tensor.
Implements coordinateRotation.
Definition at line 145 of file axesRotation.H.
Referenced by cylindrical::updateCells().
Rtr()
virtual const tensor& Rtr () const inline virtual
Return global-to-local transformation tensor.
Implements coordinateRotation.
Definition at line 151 of file axesRotation.H.
e1()
virtual const vector e1 () const inline virtual
Return local Cartesian x-axis in global coordinates.
Implements coordinateRotation.
Definition at line 157 of file axesRotation.H.
References Tensor< Cmpt >::x().
Referenced by axesRotation::write().
e2()
virtual const vector e2 () const inline virtual
Return local Cartesian y-axis in global coordinates.
Implements coordinateRotation.
Definition at line 163 of file axesRotation.H.
References Tensor< Cmpt >::y().
Referenced by axesRotation::write().
e3()
virtual const vector e3 () const inline virtual
Return local Cartesian z-axis in global coordinates.
Implements coordinateRotation.
Definition at line 169 of file axesRotation.H.
References axesRotation::invTransform(), axesRotation::operator=(), axesRotation::Tr(), axesRotation::transform(), axesRotation::transformTensor(), axesRotation::transformVector(), axesRotation::write(), and Tensor< Cmpt >::z().
Referenced by axesRotation::write().
Tr()
const Foam::tensorField & Tr () const virtual
Return transformation tensor field.
Implements coordinateRotation.
Definition at line 162 of file axesRotation.C.
References NotImplemented, and axesRotation::transform().
Referenced by axesRotation::e3().
transform() [1/2]
Foam::tmp< Foam::vectorField > transform (const vectorField & st) const virtual
Transform vectorField using transformation tensor field.
Implements coordinateRotation.
Definition at line 170 of file axesRotation.C.
Referenced by axesRotation::e3(), and axesRotation::Tr().
transform() [2/2]
Foam::vector transform (const vector & st) const virtual
Transform vector using transformation tensor.
Implements coordinateRotation.
Definition at line 178 of file axesRotation.C.
References axesRotation::invTransform().
invTransform() [1/2]
Foam::tmp< Foam::vectorField > invTransform (const vectorField & st) const virtual
Inverse transform vectorField using transformation tensor field.
Implements coordinateRotation.
Definition at line 185 of file axesRotation.C.
Referenced by axesRotation::e3(), and axesRotation::transform().
invTransform() [2/2]
Foam::vector invTransform (const vector & st) const virtual
Inverse transform vector using transformation tensor.
Implements coordinateRotation.
Definition at line 193 of file axesRotation.C.
References axesRotation::transformTensor().
transformTensor() [1/3]
Foam::tmp< Foam::tensorField > transformTensor (const tensorField & st) const virtual
Transform tensor field using transformation tensorField.
Implements coordinateRotation.
Definition at line 200 of file axesRotation.C.
References NotImplemented.
Referenced by axesRotation::e3(), axesRotation::invTransform(), and axesRotation::transformTensor().
transformTensor() [2/3]
Foam::tensor transformTensor (const tensor & st) const virtual
Transform tensor using transformation tensorField.
Implements coordinateRotation.
Definition at line 210 of file axesRotation.C.
References axesRotation::transformTensor().
transformTensor() [3/3]
Foam::tmp< Foam::tensorField > transformTensor (const tensorField & st, const labelList & cellMap) const virtual
Transform tensor sub-field using transformation tensorField.
Implements coordinateRotation.
Definition at line 219 of file axesRotation.C.
References NotImplemented, and axesRotation::transformVector().
transformVector() [1/2]
Foam::tmp< Foam::symmTensorField > transformVector (const vectorField & st) const virtual
Transform vectorField using transformation tensorField and return.
symmetric tensorField
Implements coordinateRotation.
Definition at line 230 of file axesRotation.C.
References fld(), forAll, tmp< T >::ref(), List< T >::size(), and coordinateRotation::transformPrincipal().
Referenced by axesRotation::e3(), and axesRotation::transformTensor().
transformVector() [2/2]
Foam::symmTensor transformVector (const vector & st) const virtual
Transform vector using transformation tensor and return.
symmetric tensor
Implements coordinateRotation.
Definition at line 246 of file axesRotation.C.
References coordinateRotation::transformPrincipal().
operator=()
void operator= (const dictionary & dict)
Assign from dictionary.
Definition at line 256 of file axesRotation.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::found(), dictionary::lookup(), Foam::Pout, and dictionary::readIfPresent().
Referenced by axesRotation::axesRotation(), and axesRotation::e3().
write()
void write (Ostream & os) const virtual
Write.
Implements coordinateRotation.
Definition at line 299 of file axesRotation.C.
References axesRotation::e1(), axesRotation::e2(), axesRotation::e3(), token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by axesRotation::e3().
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/coordinateRotation/axesRotation.H
src/meshTools/coordinateSystems/coordinateRotation/axesRotation.C