OpenFOAM: treeDataEdge::findNearestOp Class Reference
treeDataEdge::findNearestOp Class Reference
Public Member Functions
findNearestOp (const indexedOctree< treeDataEdge > &tree)
void operator() (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &minIndex, point &nearestPoint) const
void operator() (const labelUList &indices, const linePointRef &ln, treeBoundBox &tightest, label &minIndex, point &linePoint, point &nearestPoint) const
Detailed Description
Definition at line 90 of file treeDataEdge.H.
Constructor & Destructor Documentation
findNearestOp()
findNearestOp (const indexedOctree< treeDataEdge > & tree)
Definition at line 100 of file treeDataEdge.C.
References treeDataEdge::findIntersectOp::findIntersectOp().
Referenced by treeDataEdge::treeDataEdge().
Member Function Documentation
operator()() [1/2]
void operator() (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & minIndex, point & nearestPoint) const
Definition at line 181 of file treeDataEdge.C.
References PointHit< Point >::distance(), treeDataEdge::edgeLabels(), treeDataEdge::edges(), forAll, edge::line(), treeDataEdge::points(), PointHit< Point >::rawPoint(), and Foam::sqr().
operator()() [2/2]
void operator() (const labelUList & indices, const linePointRef & ln, treeBoundBox & tightest, label & minIndex, point & linePoint, point & nearestPoint) const
Definition at line 213 of file treeDataEdge.C.
References treeDataEdge::edgeLabels(), treeDataEdge::edges(), forAll, edge::line(), Foam::magSqr(), VectorSpace< Form, Cmpt, Ncmpts >::max, Foam::max(), VectorSpace< Form, Cmpt, Ncmpts >::min, Foam::min(), treeDataEdge::points(), Foam::sqr(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataEdge.H
src/meshTools/indexedOctree/treeDataEdge.C