OpenFOAM: cylindricalCS Class Reference
cylindricalCS Class Reference
Cylindrical coordinate system.
Public Member Functions
cylindricalCS (const bool inDegrees=true)
Construct null.
cylindricalCS (const coordinateSystem &, const bool inDegrees=true)
Construct copy.
cylindricalCS (const word &name, const coordinateSystem &, const bool inDegrees=true)
Construct copy with a different name.
cylindricalCS (const word &name, const point &origin, const coordinateRotation &, const bool inDegrees=true)
Construct from origin and rotation.
cylindricalCS (const word &name, const point &origin, const vector &axis, const vector &dirn, const bool inDegrees=true)
Construct from origin and 2 axes.
cylindricalCS (const word &, const dictionary &)
Construct from dictionary and name.
cylindricalCS (const objectRegistry &, const dictionary &)
Construct from dictionary and objectRegistry.
virtual ~cylindricalCS ()
Destructor.
bool inDegrees () const
Are angles in degrees?
bool & inDegrees ()
Non-const access to inDegrees.
Public Member Functions inherited from coordinateSystem
TypeName ("coordinateSystem")
Runtime type information.
coordinateSystem ()
Construct null. This is equivalent to an identity coordinateSystem.
coordinateSystem (const word &name, const coordinateSystem &)
Construct copy with a different name.
coordinateSystem (const word &name, const point &origin, const coordinateRotation &)
Construct from origin and rotation.
coordinateSystem (const word &name, const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
coordinateSystem (const word &name, const dictionary &)
Construct from dictionary with a given name.
coordinateSystem (const dictionary &)
Construct from dictionary with default name.
coordinateSystem (const objectRegistry &, const dictionary &)
Construct from dictionary (default name)
coordinateSystem (Istream &)
Construct from Istream.
autoPtr< coordinateSystem > clone () const
Return clone.
declareRunTimeSelectionTable (autoPtr, coordinateSystem, dictionary,(const objectRegistry &obr, const dictionary &dict),(obr, dict))
virtual ~coordinateSystem ()
Destructor.
const word & name () const
Return name.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
const point & origin () const
Return origin.
const coordinateRotation & R () const
Return const reference to co-ordinate rotation.
coordinateRotation & R ()
Return non const reference to co-ordinate rotation.
const coordinateRotation & R (const polyMesh &mesh, const labelList &cells)
Update and return the co-ordinate roation for a list of cells.
virtual dictionary dict (bool ignoreType=false) const
Return as dictionary of entries.
void rename (const word &newName)
Rename.
point & origin ()
Edit access to origin.
virtual void clear ()
Reset origin and rotation to an identity coordinateSystem.
virtual void write (Ostream &) const
Write.
void writeDict (Ostream &, bool subDict=true) const
Write dictionary.
point globalPosition (const point &local) const
Convert from position in local coordinate system to global.
tmp< pointField > globalPosition (const pointField &local) const
Convert from position in local coordinate system to global.
vector globalVector (const vector &local) const
Convert from vector components in local coordinate system to.
tmp< vectorField > globalVector (const vectorField &local) const
Convert from vector components in local coordinate system to.
point localPosition (const point &global) const
Convert from global Cartesian position to position in local.
tmp< pointField > localPosition (const pointField &global) const
Convert from global Cartesian position to position in local.
vector localVector (const vector &global) const
Convert from global Cartesian vector to components in local.
tmp< vectorField > localVector (const vectorField &global) const
Convert from global Cartesian vector to components in local.
Protected Member Functions
virtual vector localToGlobal (const vector &, bool translate) const
Convert from local coordinate system to the global Cartesian system.
virtual tmp< vectorField > localToGlobal (const vectorField &, bool translate) const
Convert from local coordinate system to the global Cartesian system.
virtual vector globalToLocal (const vector &, bool translate) const
Convert from global Cartesian system to the local coordinate system.
virtual tmp< vectorField > globalToLocal (const vectorField &, bool translate) const
Convert from global Cartesian system to the local coordinate system.
Protected Member Functions inherited from coordinateSystem
void init (const dictionary &)
Init from dict and obr.
void init (const dictionary &, const objectRegistry &)
Init from dictionary.
Additional Inherited Members
Static Public Member Functions inherited from coordinateSystem
static autoPtr< coordinateSystem > New (const objectRegistry &obr, const dictionary &dict)
Select constructed from dictionary and objectRegistry.
static autoPtr< coordinateSystem > New (const dictionary &dict)
Select constructed from dictionary.
static autoPtr< coordinateSystem > New (Istream &is)
Select constructed from Istream.
Detailed Description
Cylindrical coordinate system.
Source files
cylindricalCS.H
cylindricalCS.C
Definition at line 48 of file cylindricalCS.H.
Constructor & Destructor Documentation
cylindricalCS() [1/7]
cylindricalCS (const bool inDegrees = true)
Construct null.
Definition at line 35 of file cylindricalCS.C.
Referenced by cylindricalCS::cylindricalCS().
cylindricalCS() [2/7]
cylindricalCS (const coordinateSystem & cs, const bool inDegrees = true)
Construct copy.
Definition at line 43 of file cylindricalCS.C.
References cylindricalCS::cylindricalCS().
cylindricalCS() [3/7]
cylindricalCS (const word & name, const coordinateSystem & cs, const bool inDegrees = true)
Construct copy with a different name.
Definition at line 54 of file cylindricalCS.C.
References cylindricalCS::cylindricalCS().
cylindricalCS() [4/7]
cylindricalCS (const word & name, const point & origin, const coordinateRotation & cr, const bool inDegrees = true)
Construct from origin and rotation.
Definition at line 66 of file cylindricalCS.C.
References cylindricalCS::cylindricalCS().
cylindricalCS() [5/7]
cylindricalCS (const word & name, const point & origin, const vector & axis, const vector & dirn, const bool inDegrees = true)
Construct from origin and 2 axes.
Definition at line 79 of file cylindricalCS.C.
References cylindricalCS::cylindricalCS().
cylindricalCS() [6/7]
cylindricalCS (const word & name, const dictionary & dict)
Construct from dictionary and name.
Definition at line 93 of file cylindricalCS.C.
References cylindricalCS::cylindricalCS().
cylindricalCS() [7/7]
cylindricalCS (const objectRegistry & obr, const dictionary & dict)
Construct from dictionary and objectRegistry.
Definition at line 104 of file cylindricalCS.C.
~cylindricalCS()
~cylindricalCS () virtual
Destructor.
Definition at line 116 of file cylindricalCS.C.
Member Function Documentation
localToGlobal() [1/2]
Foam::vector localToGlobal (const vector & local, bool translate) const protected virtual
Convert from local coordinate system to the global Cartesian system.
with optional translation for the origin
Reimplemented from coordinateSystem.
Definition at line 135 of file cylindricalCS.C.
References Foam::cos(), coordinateSystem::localToGlobal(), Foam::constant::mathematical::pi(), Foam::sin(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by cylindricalCS::inDegrees().
localToGlobal() [2/2]
Foam::tmp< Foam::vectorField > localToGlobal (const vectorField & local, bool translate) const protected virtual
Convert from local coordinate system to the global Cartesian system.
with optional translation for the origin
Reimplemented from coordinateSystem.
Definition at line 154 of file cylindricalCS.C.
References Field< Type >::component(), Foam::cos(), cylindricalCS::globalToLocal(), coordinateSystem::localToGlobal(), Foam::constant::mathematical::pi(), Field< Type >::replace(), Foam::sin(), List< T >::size(), Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
globalToLocal() [1/2]
Foam::vector globalToLocal (const vector & global, bool translate) const protected virtual
Convert from global Cartesian system to the local coordinate system.
with optional translation for the origin
Reimplemented from coordinateSystem.
Definition at line 176 of file cylindricalCS.C.
References Foam::atan2(), coordinateSystem::globalToLocal(), Foam::constant::mathematical::pi(), Foam::sqr(), Foam::sqrt(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by cylindricalCS::localToGlobal().
globalToLocal() [2/2]
Foam::tmp< Foam::vectorField > globalToLocal (const vectorField & global, bool translate) const protected virtual
Convert from global Cartesian system to the local coordinate system.
with optional translation for the origin
Reimplemented from coordinateSystem.
Definition at line 200 of file cylindricalCS.C.
References Foam::atan2(), Field< Type >::component(), coordinateSystem::globalToLocal(), Foam::constant::mathematical::pi(), tmp< T >::ref(), Field< Type >::replace(), List< T >::size(), Foam::sqr(), Foam::sqrt(), Vector< scalar >::X, Vector< scalar >::Y, and Vector< scalar >::Z.
inDegrees() [1/2]
bool inDegrees () const
Are angles in degrees?
Definition at line 122 of file cylindricalCS.C.
inDegrees() [2/2]
bool & inDegrees ()
Non-const access to inDegrees.
Definition at line 128 of file cylindricalCS.C.
References cylindricalCS::localToGlobal().
The documentation for this class was generated from the following files:
src/meshTools/coordinateSystems/cylindricalCS.H
src/meshTools/coordinateSystems/cylindricalCS.C