OpenFOAM: cellQuality Class Reference
cellQuality Class Reference
Class calculates cell quality measures.
Public Member Functions
cellQuality (const polyMesh &mesh)
Construct from mesh.
tmp< scalarField > nonOrthogonality () const
Return cell non-orthogonality.
tmp< scalarField > skewness () const
Return cell skewness.
tmp< scalarField > faceNonOrthogonality () const
Return face non-orthogonality.
tmp< scalarField > faceSkewness () const
Return face skewness.
Detailed Description
Class calculates cell quality measures.
Source files
cellQuality.H
cellQuality.C
Definition at line 49 of file cellQuality.H.
Constructor & Destructor Documentation
cellQuality()
cellQuality (const polyMesh & mesh)
Construct from mesh.
Definition at line 32 of file cellQuality.C.
Member Function Documentation
nonOrthogonality()
Foam::tmp< Foam::scalarField > nonOrthogonality () const
Return cell non-orthogonality.
Definition at line 40 of file cellQuality.C.
References Foam::acos(), polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), primitiveMesh::faceAreas(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::mag(), Foam::max(), Foam::min(), primitiveMesh::nCells(), patchi, Foam::radToDeg(), tmp< T >::ref(), and s().
skewness()
Foam::tmp< Foam::scalarField > skewness () const
Return cell skewness.
Definition at line 102 of file cellQuality.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::mag(), Foam::max(), n, primitiveMesh::nCells(), patchi, and tmp< T >::ref().
faceNonOrthogonality()
Foam::tmp< Foam::scalarField > faceNonOrthogonality () const
Return face non-orthogonality.
Definition at line 181 of file cellQuality.C.
References Foam::acos(), polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), primitiveMesh::faceAreas(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::mag(), Foam::min(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, Foam::radToDeg(), tmp< T >::ref(), and s().
faceSkewness()
Foam::tmp< Foam::scalarField > faceSkewness () const
Return face skewness.
Definition at line 241 of file cellQuality.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::mag(), n, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, and tmp< T >::ref().
The documentation for this class was generated from the following files:
src/meshTools/cellQuality/cellQuality.H
src/meshTools/cellQuality/cellQuality.C