OpenFOAM: indexedOctree< Type > Class Template Reference
indexedOctree< Type > Class Template Reference
Non-pointer based hierarchical recursive searching.
Classes
class node
Tree node. Has up pointer and down pointers.
Public Member Functions
indexedOctree (const Type &shapes)
Construct null.
indexedOctree (const Type &shapes, const List< node > &nodes, const labelListList &contents)
Construct from components.
indexedOctree (const Type &shapes, const treeBoundBox &bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
indexedOctree (const Type &shapes, Istream &is)
Construct from Istream.
autoPtr< indexedOctree< Type > > clone () const
Clone.
const Type & shapes () const
Reference to shape.
const List< node > & nodes () const
List of all nodes.
const labelListList & contents () const
List of all contents (referenced by those nodes that are.
const treeBoundBox & bb () const
Top bounding box.
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
template<class FindNearestOp >
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr, const FindNearestOp &fnOp) const
Calculate nearest point on nearest shape.
template<class FindNearestOp >
void findNearest (const label nodeI, const point &, scalar &nearestDistSqr, label &nearestShapeI, point &nearestPoint, const FindNearestOp &fnOp) const
Low level: calculate nearest starting from subnode.
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
Find nearest to line.
template<class FindNearestOp >
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint, const FindNearestOp &fnOp) const
pointIndexHit findLine (const point &start, const point &end) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point &start, const point &end) const
Find any intersection of line between start and end.
template<class FindIntersectOp >
pointIndexHit findLine (const point &start, const point &end, const FindIntersectOp &fiOp) const
Find nearest intersection of line between start and end.
template<class FindIntersectOp >
pointIndexHit findLineAny (const point &start, const point &end, const FindIntersectOp &fiOp) const
Find any intersection of line between start and end.
labelList findBox (const treeBoundBox &bb) const
Find (in no particular order) indices of all shapes inside or.
labelList findSphere (const point &centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
labelBits findNode (const label nodeI, const point &) const
Find deepest node (as parent+octant) containing point. Starts.
label findInside (const point &) const
Find shape containing point. Only implemented for certain.
const labelList & findIndices (const point &) const
Find the shape indices that occupy the result of findNode.
volumeType getVolumeType (const point &) const
Determine type (inside/outside/mixed) for point. unknown if.
template<class CompareOp >
void findNear (const scalar nearDist, const indexedOctree< Type > &tree2, CompareOp &cop) const
Find near pairs and apply CompareOp to them.
void print (prefixOSstream &, const bool printContents, const label) const
Print tree. Either print all indices (printContent = true) or.
bool write (Ostream &os) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const bool findAny, const point &treeStart, const point &treeEnd, const label startNodeI, const direction startOctant, const FindIntersectOp &fiOp, const bool verbose) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const bool findAny, const point &start, const point &end, const FindIntersectOp &fiOp) const
template<class FindNearestOp >
Foam::pointIndexHit findNearest (const point &sample, const scalar startDistSqr, const FindNearestOp &fnOp) const
template<class FindNearestOp >
Foam::pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint, const FindNearestOp &fnOp) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const point &start, const point &end, const FindIntersectOp &fiOp) const
template<class FindIntersectOp >
Foam::pointIndexHit findLineAny (const point &start, const point &end, const FindIntersectOp &fiOp) const
Static Public Member Functions
static scalar & perturbTol ()
Get the perturbation tolerance.
static bool isContent (const labelBits i)
static bool isEmpty (const labelBits i)
static bool isNode (const labelBits i)
static label getContent (const labelBits i)
static label getNode (const labelBits i)
static direction getOctant (const labelBits i)
static volumeType getSide (const vector &outsideNormal, const vector &vec)
Helper function to return the side. Returns outside if.
static bool overlaps (const point &bbMin, const point &bbMax, const scalar nearestDistSqr, const point &sample)
Helper: does bb intersect a sphere around sample? Or is any.
Friends
Ostream & operator (Ostream &, const indexedOctree< Type > &)
Detailed Description
template<class Type>
class Foam::indexedOctree< Type >
Non-pointer based hierarchical recursive searching.
Source files
indexedOctree.H
indexedOctree.C
Definition at line 47 of file treeDataEdge.H.
Constructor & Destructor Documentation
indexedOctree() [1/4]
indexedOctree (const Type & shapes)
Construct null.
Definition at line 2114 of file indexedOctree.C.
Referenced by indexedOctree< Foam::treeDataFace >::indexedOctree().
indexedOctree() [2/4]
indexedOctree (const Type & shapes, const List< node > & nodes, const labelListList & contents)
Construct from components.
Definition at line 2125 of file indexedOctree.C.
indexedOctree() [3/4]
indexedOctree (const Type & shapes, const treeBoundBox & bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
Definition at line 2140 of file indexedOctree.C.
indexedOctree() [4/4]
indexedOctree (const Type & shapes, Istream & is)
Construct from Istream.
Definition at line 2304 of file indexedOctree.C.
Member Function Documentation
perturbTol()
Foam::scalar & perturbTol () static
Get the perturbation tolerance.
Definition at line 2319 of file indexedOctree.C.
Referenced by triSurfaceMesh::edgeTree(), triSurfaceSearch::findLine(), triSurfaceSearch::findLineAll(), triSurfaceSearch::findLineAny(), triSurfaceRegionSearch::findNearest(), triSurfaceSearch::findNearest(), triSurfaceMesh::getVolumeType(), triSurfaceSearch::tree(), and triSurfaceRegionSearch::treeByRegion().
clone()
autoPtr<indexedOctree<Type> > clone () const inline
Clone.
Definition at line 432 of file indexedOctree.H.
shapes()
const Type& shapes () const inline
Reference to shape.
Definition at line 445 of file indexedOctree.H.
Referenced by patchProbes::findElements(), indexedOctree< Foam::treeDataFace >::findLine(), meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestEdge(), refinementFeatures::findNearestPoint(), refinementFeatures::findNearestRegionEdge(), surfaceFeatures::nearestEdges(), listPlusEqOp< T >::operator()(), and nearestEqOp::operator()().
nodes()
const List<node>& nodes () const inline
List of all nodes.
Definition at line 451 of file indexedOctree.H.
Referenced by indexedOctree< Foam::treeDataFace >::findLine().
contents()
const labelListList& contents () const inline
List of all contents (referenced by those nodes that are.
contents)
Definition at line 458 of file indexedOctree.H.
Referenced by indexedOctree< Foam::treeDataFace >::findLine(), and indexedOctree< Foam::treeDataFace >::nodes().
bb()
const treeBoundBox& bb () const inline
Top bounding box.
Definition at line 464 of file indexedOctree.H.
Referenced by patchProbes::findElements(), indexedOctree< Foam::treeDataFace >::findNear(), meshSearch::findNearestBoundaryFace(), surfaceFeatures::nearestSamples(), and nearestEqOp::operator()().
isContent()
static bool isContent (const labelBits i) inline static
Definition at line 477 of file indexedOctree.H.
Referenced by indexedOctree< Foam::treeDataFace >::findLine(), and indexedOctree< Foam::treeDataFace >::getContent().
isEmpty()
static bool isEmpty (const labelBits i) inline static
Definition at line 482 of file indexedOctree.H.
isNode()
static bool isNode (const labelBits i) inline static
Definition at line 487 of file indexedOctree.H.
Referenced by indexedOctree< Foam::treeDataFace >::findLine(), and indexedOctree< Foam::treeDataFace >::getNode().
getContent()
static label getContent (const labelBits i) inline static
Definition at line 492 of file indexedOctree.H.
Referenced by indexedOctree< Foam::treeDataFace >::findLine().
getNode()
static label getNode (const labelBits i) inline static
Definition at line 502 of file indexedOctree.H.
Referenced by indexedOctree< Foam::treeDataFace >::findLine().
getOctant()
static direction getOctant (const labelBits i) inline static
Definition at line 512 of file indexedOctree.H.
findNearest() [1/7]
Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Definition at line 2327 of file indexedOctree.C.
findNearest() [2/7]
pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr, const FindNearestOp & fnOp) const
Calculate nearest point on nearest shape.
Returns
bool : any point found nearer than nearestDistSqr
label: index in shapes
point: actual nearest point found
findNearest() [3/7]
void findNearest (const label nodeI, const point & sample, scalar & nearestDistSqr, label & nearestShapeI, point & nearestPoint, const FindNearestOp & fnOp) const
Low level: calculate nearest starting from subnode.
Definition at line 490 of file indexedOctree.C.
findNearest() [4/7]
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Find nearest to line.
Returns
bool : any point found?
label: index in shapes
point: actual nearest point found sets:
linePoint : corresponding nearest point on line
Definition at line 2376 of file indexedOctree.C.
findNearest() [5/7]
pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint, const FindNearestOp & fnOp) const
findLine() [1/5]
Foam::pointIndexHit findLine (const point & start, const point & end) const
Find nearest intersection of line between start and end.
Definition at line 2428 of file indexedOctree.C.
findLineAny() [1/3]
Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Find any intersection of line between start and end.
Definition at line 2445 of file indexedOctree.C.
Referenced by indexedOctree< Foam::treeDataFace >::findLine(), triSurfaceSearch::findLineAny(), indexedOctree< Foam::treeDataFace >::getOctant(), and NamedEnum< directionType, 3 >::names().
findLine() [2/5]
pointIndexHit findLine (const point & start, const point & end, const FindIntersectOp & fiOp) const
Find nearest intersection of line between start and end.
findLineAny() [2/3]
pointIndexHit findLineAny (const point & start, const point & end, const FindIntersectOp & fiOp) const
Find any intersection of line between start and end.
findBox()
Foam::labelList findBox (const treeBoundBox & bb) const
Find (in no particular order) indices of all shapes inside or.
overlapping bounding box (i.e. all shapes not outside box)
Definition at line 2488 of file indexedOctree.C.
findSphere()
Foam::labelList findSphere (const point & centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
overlapping a bounding sphere (i.e. all shapes not outside sphere)
Definition at line 2506 of file indexedOctree.C.
findNode()
Foam::labelBits findNode (const label nodeI, const point & sample) const
Find deepest node (as parent+octant) containing point. Starts.
off from starting index in nodes_ (use 0 to start from top) Use getNode and getOctant to extract info, or call findIndices.
Definition at line 2525 of file indexedOctree.C.
Referenced by indexedOctree< Foam::treeDataFace >::findSphere(), and indexedOctree< Foam::treeDataFace >::getOctant().
findInside()
Foam::label findInside (const point & sample) const
Find shape containing point. Only implemented for certain.
shapes.
Definition at line 2571 of file indexedOctree.C.
Referenced by polyMesh::findCellFacePt(), mappedPatchBase::findSamples(), indexedOctree< Foam::treeDataFace >::getOctant(), and nearestEqOp::operator()().
findIndices()
const Foam::labelList & findIndices (const point & sample) const
Find the shape indices that occupy the result of findNode.
Definition at line 2601 of file indexedOctree.C.
Referenced by indexedOctree< Foam::treeDataFace >::findInside(), and indexedOctree< Foam::treeDataFace >::getOctant().
getVolumeType()
Foam::volumeType getVolumeType (const point & sample) const
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Definition at line 2625 of file indexedOctree.C.
getSide()
Foam::volumeType getSide (const vector & outsideNormal, const vector & vec) static
Helper function to return the side. Returns outside if.
outsideNormal&vec >= 0, inside otherwise
Definition at line 471 of file indexedOctree.C.
Referenced by indexedOctree< Foam::treeDataFace >::getOctant(), treeDataFace::getVolumeType(), and indexedOctree< Foam::treeDataFace >::overlaps().
overlaps()
bool overlaps (const point & bbMin, const point & bbMax, const scalar nearestDistSqr, const point & sample) static
Helper: does bb intersect a sphere around sample? Or is any.
corner point of bb closer than nearestDistSqr to sample.
Definition at line 42 of file indexedOctree.C.
findNear()
void findNear (const scalar nearDist, const indexedOctree< Type > & tree2, CompareOp & cop) const
Find near pairs and apply CompareOp to them.
tree2 can be *this or different tree.
Definition at line 2695 of file indexedOctree.C.
print()
void print (prefixOSstream & os, const bool printContents, const label nodeI) const
Print tree. Either print all indices (printContent = true) or.
just size of contents nodes.
Definition at line 2718 of file indexedOctree.C.
Referenced by indexedOctree< Foam::treeDataFace >::findNear(), and indexedOctree< Foam::treeDataFace >::getOctant().
write()
bool write (Ostream & os) const
Definition at line 2790 of file indexedOctree.C.
Referenced by indexedOctree< Foam::treeDataFace >::getOctant().
findLine() [3/5]
Foam::pointIndexHit findLine (const bool findAny, const point & treeStart, const point & treeEnd, const label startNodeI, const direction startOctant, const FindIntersectOp & fiOp, const bool verbose) const
Definition at line 1499 of file indexedOctree.C.
findLine() [4/5]
Foam::pointIndexHit findLine (const bool findAny, const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 1691 of file indexedOctree.C.
findNearest() [6/7]
Foam::pointIndexHit findNearest (const point & sample, const scalar startDistSqr, const FindNearestOp & fnOp) const
Definition at line 2344 of file indexedOctree.C.
findNearest() [7/7]
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint, const FindNearestOp & fnOp) const
Definition at line 2395 of file indexedOctree.C.
findLine() [5/5]
Foam::pointIndexHit findLine (const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 2463 of file indexedOctree.C.
findLineAny() [3/3]
Foam::pointIndexHit findLineAny (const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 2476 of file indexedOctree.C.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const indexedOctree< Type > &) friend
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataEdge.H
src/OpenFOAM/algorithms/indexedOctree/indexedOctree.H
src/OpenFOAM/algorithms/indexedOctree/indexedOctree.C