OpenFOAM: mappedPatchBase Class Reference
mappedPatchBase Class Reference
Determines a mapping between patch face centres and mesh cell or face centres and processors they're on.
Classes
class maxProcEqOp
class nearestEqOp
Public Types
enum sampleMode {
NEARESTCELL, NEARESTPATCHFACE, NEARESTPATCHFACEAMI, NEARESTPATCHPOINT,
NEARESTFACE, NEARESTONLYCELL
}
Mesh items to sample.
enum offsetMode { UNIFORM, NONUNIFORM, NORMAL }
How to project face centres.
typedef Tuple2< pointIndexHit, Tuple2< scalar, label > > nearInfo
Helper class for finding nearest.
Public Member Functions
TypeName ("mappedPatchBase")
Runtime type information.
mappedPatchBase (const polyPatch &)
Construct from patch.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
Construct with offsetMode=non-uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &offset)
Construct from offsetMode=uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar distance)
Construct from offsetMode=normal and distance.
mappedPatchBase (const polyPatch &, const dictionary &)
Construct from dictionary.
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
Construct from dictionary and (collocated) sample mode.
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
Construct as copy, resetting patch.
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
Construct as copy, resetting patch, map original data.
virtual ~mappedPatchBase ()
Destructor.
void clearOut ()
const sampleMode & mode () const
What to sample.
const word & sampleRegion () const
Region to sample.
const word & samplePatch () const
Patch (only if NEARESTPATCHFACE)
const word & coupleGroup () const
PatchGroup (only if NEARESTPATCHFACE)
label sampleSize () const
Return size of mapped mesh/patch/boundary.
const vector & offset () const
Offset vector (from patch faces to destination mesh objects)
const vectorField & offsets () const
Offset vector (from patch faces to destination mesh objects)
bool sameRegion () const
Cached sampleRegion != mesh.name()
const mapDistribute & map () const
Return reference to the parallel distribution map.
const AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
Return reference to the AMI interpolator.
const autoPtr< Foam::searchableSurface > & surfPtr () const
Return a pointer to the AMI projection surface.
const polyMesh & sampleMesh () const
Get the region mesh.
const polyPatch & samplePolyPatch () const
Get the patch on the region.
tmp< pointField > samplePoints () const
Get the sample points.
template<class Type >
void distribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
template<class Type >
void reverseDistribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
virtual void write (Ostream &) const
Write as a dictionary.
Static Public Member Functions
static pointIndexHit facePoint (const polyMesh &, const label facei, const polyMesh::cellDecomposition)
Get a point on the face given a face decomposition method:
Static Public Attributes
static const NamedEnum< sampleMode, 6 > sampleModeNames_
static const NamedEnum< offsetMode, 3 > offsetModeNames_
Protected Member Functions
tmp< pointField > facePoints (const polyPatch &) const
Get the points from face-centre-decomposition face centres.
void collectSamples (const pointField &facePoints, pointField &, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
Collect single list of samples and originating processor+face.
void findSamples (const sampleMode mode, const pointField &, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
Find cells/faces containing samples.
tmp< pointField > samplePoints (const pointField &) const
Get the sample points given the face points.
void calcMapping () const
Calculate mapping.
void calcAMI () const
Calculate AMI interpolator.
Static Protected Member Functions
static tmp< pointField > readListOrField (const word &keyword, const dictionary &dict, const label size)
Helper to read field or non-uniform list from dictionary.
Protected Attributes
const polyPatch & patch_
Patch to sample.
word sampleRegion_
Region to sample.
const sampleMode mode_
What to sample.
word samplePatch_
Patch (if in sampleMode NEARESTPATCH*)
const coupleGroupIdentifier coupleGroup_
PatchGroup (if in sampleMode NEARESTPATCH*)
offsetMode offsetMode_
How to obtain samples.
vector offset_
Offset vector (uniform)
vectorField offsets_
Offset vector (nonuniform)
scalar distance_
Offset distance (normal)
bool sameRegion_
Same region.
autoPtr< mapDistribute > mapPtr_
Communication schedule:
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
Pointer to AMI interpolator.
const bool AMIReverse_
Flag to indicate that slave patch should be reversed for AMI.
autoPtr< searchableSurface > surfPtr_
Pointer to projection surface employed by AMI interpolator.
dictionary surfDict_
Dictionary storing projection surface description.
Detailed Description
Determines a mapping between patch face centres and mesh cell or face centres and processors they're on.
If constructed from dictionary:
    // Region to sample (default is region0)
    sampleRegion region0;
    // What to sample:
    // - nearestCell         : sample cell containing point
    // - nearestOnlyCell     : nearest sample cell (even if not containing
    //                         point)
    // - nearestPatchFace    : nearest face on selected patch
    // - nearestPatchFaceAMI : nearest face on selected patch
                               - patches need not conform
                               - uses AMI interpolation
    // - nearestFace         : nearest boundary face on any patch
    // - nearestPatchPoint   : nearest patch point (for coupled points
    //                         this might be any of the points so you have
    //                         to guarantee the point data is synchronised
    //                         beforehand)
    sampleMode nearestCell;
    // If sampleMode is nearestPatchFace : patch to find faces of
    samplePatch movingWall;
    // If sampleMode is nearestPatchFace : specify patchgroup to find
    // samplePatch and sampleRegion (if not provided)
    coupleGroup baffleGroup;
    // How to supply offset (w.r.t. my patch face centres):
    // - uniform : single offset vector
    // - nonuniform : per-face offset vector
    // - normal : using supplied distance and face normal
    offsetMode uniform;
    // According to offsetMode (see above) supply one of
    // offset, offsets or distance
    offset  (1 0 0);
Note: if offsetMode is normal it uses outwards pointing normals. So supply a negative distance if sampling inside the domain.
Note
Storage is not optimal. It temporary collects all (patch)face centres on all processors to keep the addressing calculation simple.
Source files
mappedPatchBase.H
mappedPatchBase.C
Definition at line 103 of file mappedPatchBase.H.
Member Typedef Documentation
nearInfo
typedef Tuple2<pointIndexHit, Tuple2<scalar, label> > nearInfo
Helper class for finding nearest.
Nearest:
point+local index
sqr(distance)
processor
Definition at line 139 of file mappedPatchBase.H.
Member Enumeration Documentation
sampleMode
enum sampleMode
Mesh items to sample.
Enumerator
NEARESTCELL
NEARESTPATCHFACE
NEARESTPATCHFACEAMI
NEARESTPATCHPOINT
NEARESTFACE
NEARESTONLYCELL
Definition at line 111 of file mappedPatchBase.H.
offsetMode
enum offsetMode
How to project face centres.
Enumerator
UNIFORM
NONUNIFORM
NORMAL
Definition at line 122 of file mappedPatchBase.H.
Constructor & Destructor Documentation
mappedPatchBase() [1/8]
mappedPatchBase (const polyPatch & pp)
Construct from patch.
Definition at line 932 of file mappedPatchBase.C.
Referenced by mappedPatchBase::mappedPatchBase(), and mappedPatchBase::readListOrField().
mappedPatchBase() [2/8]
mappedPatchBase (const polyPatch & pp, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const vectorField & offsets)
Construct with offsetMode=non-uniform.
Definition at line 955 of file mappedPatchBase.C.
References mappedPatchBase::mappedPatchBase().
mappedPatchBase() [3/8]
mappedPatchBase (const polyPatch & pp, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const vector & offset)
Construct from offsetMode=uniform.
Definition at line 982 of file mappedPatchBase.C.
References mappedPatchBase::mappedPatchBase().
mappedPatchBase() [4/8]
mappedPatchBase (const polyPatch & pp, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const scalar distance)
Construct from offsetMode=normal and distance.
Definition at line 1009 of file mappedPatchBase.C.
References mappedPatchBase::mappedPatchBase().
mappedPatchBase() [5/8]
mappedPatchBase (const polyPatch & pp, const dictionary & dict)
Construct from dictionary.
Definition at line 1036 of file mappedPatchBase.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), dictionary::lookup(), mappedPatchBase::mappedPatchBase(), Foam::readScalar(), and NamedEnum< Enum, nEnum >::words().
mappedPatchBase() [6/8]
mappedPatchBase (const polyPatch & pp, const sampleMode mode, const dictionary & dict)
Construct from dictionary and (collocated) sample mode.
(only for nearestPatchFace, nearestPatchFaceAMI, nearestPatchPoint) Assumes zero offset.
Definition at line 1117 of file mappedPatchBase.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and mappedPatchBase::mappedPatchBase().
mappedPatchBase() [7/8]
mappedPatchBase (const polyPatch & pp, const mappedPatchBase & mpb)
Construct as copy, resetting patch.
Definition at line 1165 of file mappedPatchBase.C.
References mappedPatchBase::mappedPatchBase().
mappedPatchBase() [8/8]
mappedPatchBase (const polyPatch & pp, const mappedPatchBase & mpb, const labelUList & mapAddressing)
Construct as copy, resetting patch, map original data.
Definition at line 1189 of file mappedPatchBase.C.
~mappedPatchBase()
~mappedPatchBase () virtual
Destructor.
Definition at line 1220 of file mappedPatchBase.C.
Member Function Documentation
facePoints()
Foam::tmp< Foam::pointField > facePoints (const polyPatch & pp) const protected
Get the points from face-centre-decomposition face centres.
and project them onto the face-diagonal-decomposition triangles.
Definition at line 91 of file mappedPatchBase.C.
References polyPatch::boundaryMesh(), mappedPatchBase::collectSamples(), polyMesh::FACE_DIAG_TRIS, Foam::facePoint(), forAll, mesh, polyBoundaryMesh::mesh(), tmp< T >::ref(), polyPatch::start(), and polyMesh::tetBasePtIs().
Referenced by NamedEnum< directionType, 3 >::names().
collectSamples()
void collectSamples (const pointField & facePoints, pointField & samples, labelList & patchFaceProcs, labelList & patchFaces, pointField & patchFc) const protected
Collect single list of samples and originating processor+face.
Definition at line 119 of file mappedPatchBase.C.
References mappedPatchBase::findSamples(), forAll, Pstream::gatherList(), Foam::identity(), UPstream::myProcNo(), UPstream::nProcs(), Pstream::scatterList(), List< T >::setSize(), and List< T >::size().
Referenced by mappedPatchBase::facePoints().
findSamples()
void findSamples (const sampleMode mode, const pointField & samples, labelList & sampleProcs, labelList & sampleIndices, pointField & sampleLocations) const protected
Find cells/faces containing samples.
Note: face-diagonal decomposition
Note: face-diagonal decomposition
Note: face-diagonal decomposition
Definition at line 191 of file mappedPatchBase.C.
References Foam::abort(), primitiveMesh::cellCentres(), polyMesh::cellTree(), Foam::e, Foam::endl(), Foam::exit(), primitiveMesh::faceCentres(), Foam::FatalError, FatalErrorInFunction, indexedOctree< Type >::findInside(), meshSearch::findNearestFace(), Tuple2< Type1, Type2 >::first(), UList< T >::first(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), Foam::identity(), PointIndexHit< Point >::index(), Foam::Info, InfoInFunction, Pstream::listCombineGather(), Pstream::listCombineScatter(), Foam::magSqr(), VectorSpace< Vector< scalar >, scalar, 3 >::max, mesh, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), boundBox::min(), Foam::mode(), UPstream::myProcNo(), MeshObject< polyMesh, GeometricMeshObject, meshSearchMeshObject >::New(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), polyMesh::points(), rndGen(), PointIndexHit< Point >::setPoint(), List< T >::setSize(), List< T >::size(), Foam::sqr(), and polyPatch::start().
Referenced by mappedPatchBase::collectSamples().
samplePoints() [1/2]
Foam::tmp< Foam::pointField > samplePoints (const pointField & fc) const protected
Get the sample points given the face points.
Definition at line 1265 of file mappedPatchBase.C.
References fld(), Foam::mag(), n, and tmp< T >::ref().
calcMapping()
void calcMapping () const protected
Calculate mapping.
Definition at line 520 of file mappedPatchBase.C.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::gAverage(), Foam::mag(), UPstream::master(), OSstream::name(), IOstream::name(), Foam::nl, Foam::Pout, Foam::reduce(), samples(), UIndirectList< T >::size(), List< T >::size(), Foam::type(), WarningInFunction, and Foam::meshTools::writeOBJ().
Referenced by mappedPatchBase::map().
calcAMI()
void calcAMI () const protected
Calculate AMI interpolator.
Definition at line 804 of file mappedPatchBase.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, AMIInterpolation< SourcePatch, TargetPatch >::imFaceAreaWeight, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), mappedPatchBase::readListOrField(), faceAreaIntersect::tmMesh, and Foam::meshTools::writeOBJ().
Referenced by mappedPatchBase::AMI().
readListOrField()
Foam::tmp< Foam::pointField > readListOrField (const word & keyword, const dictionary & dict, const label size) static protected
Helper to read field or non-uniform list from dictionary.
Definition at line 863 of file mappedPatchBase.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, fld(), IOWarningInFunction, token::isWord(), dictionary::lookup(), mappedPatchBase::mappedPatchBase(), Istream::putBack(), tmp< T >::ref(), List< T >::setSize(), List< T >::size(), IOstream::version(), and token::wordToken().
Referenced by mappedPatchBase::calcAMI().
TypeName()
TypeName ("mappedPatchBase")
Runtime type information.
clearOut()
void clearOut ()
Definition at line 1226 of file mappedPatchBase.C.
Referenced by mappedPolyPatch::calcGeometry(), mappedWallPolyPatch::calcGeometry(), mappedWallPolyPatch::movePoints(), mappedPolyPatch::movePoints(), mappedPolyPatch::updateMesh(), mappedWallPolyPatch::updateMesh(), mappedPolyPatch::~mappedPolyPatch(), and mappedWallPolyPatch::~mappedWallPolyPatch().
mode()
const Foam::mappedPatchBase::sampleMode & mode () const inline
What to sample.
Definition at line 27 of file mappedPatchBaseI.H.
References mappedPatchBase::mode_.
Referenced by mappedVelocityFluxFixedValueFvPatchField::mappedVelocityFluxFixedValueFvPatchField(), thermalBaffleFvPatchScalarField::rmap(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), and mappedFixedInternalValueFvPatchField< Type >::updateCoeffs().
sampleRegion()
const Foam::word & sampleRegion () const inline
Region to sample.
Definition at line 33 of file mappedPatchBaseI.H.
References polyPatch::boundaryMesh(), polyMesh::boundaryMesh(), mappedPatchBase::coupleGroup_, Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::mesh(), patchIdentifier::name(), IOobject::name(), mappedPatchBase::patch_, mappedPatchBase::sampleMesh(), mappedPatchBase::samplePatch_, mappedPatchBase::sampleRegion_, and coupleGroupIdentifier::valid().
samplePatch()
const Foam::word & samplePatch () const inline
Patch (only if NEARESTPATCHFACE)
Definition at line 59 of file mappedPatchBaseI.H.
References polyPatch::boundaryMesh(), polyMesh::boundaryMesh(), mappedPatchBase::coupleGroup_, Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::mesh(), patchIdentifier::name(), IOobject::name(), mappedPatchBase::patch_, mappedPatchBase::sampleMesh(), mappedPatchBase::samplePatch_, mappedPatchBase::sampleRegion_, and coupleGroupIdentifier::valid().
Referenced by regionModel::nbrCoupledPatchID(), and mappedVelocityFluxFixedValueFvPatchField::updateCoeffs().
coupleGroup()
const Foam::word & coupleGroup () const inline
PatchGroup (only if NEARESTPATCHFACE)
Definition at line 85 of file mappedPatchBaseI.H.
References mappedPatchBase::coupleGroup_, and coupleGroupIdentifier::name().
Referenced by thermalBaffleFvPatchScalarField::rmap().
sampleSize()
Foam::label sampleSize () const inline
Return size of mapped mesh/patch/boundary.
Definition at line 91 of file mappedPatchBaseI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, mesh, mappedPatchBase::mode_, primitiveMesh::nCells(), mappedPatchBase::NEARESTCELL, mappedPatchBase::NEARESTFACE, mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, mappedPatchBase::NEARESTPATCHPOINT, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), mappedPatchBase::sampleMesh(), and mappedPatchBase::samplePolyPatch().
Referenced by mappedPatchBase::reverseDistribute().
offset()
const Foam::vector & offset () const inline
Offset vector (from patch faces to destination mesh objects)
Definition at line 126 of file mappedPatchBaseI.H.
References mappedPatchBase::offset_.
offsets()
const Foam::vectorField & offsets () const inline
Offset vector (from patch faces to destination mesh objects)
Definition at line 132 of file mappedPatchBaseI.H.
References mappedPatchBase::offsets_.
sameRegion()
bool sameRegion () const inline
Cached sampleRegion != mesh.name()
Definition at line 138 of file mappedPatchBaseI.H.
References mappedPatchBase::sameRegion_.
map()
const Foam::mapDistribute & map () const inline
Return reference to the parallel distribution map.
Definition at line 144 of file mappedPatchBaseI.H.
References mappedPatchBase::AMI(), mappedPatchBase::calcMapping(), and mappedPatchBase::mapPtr_.
Referenced by mappedPatchBase::distribute(), mappedPatchBase::reverseDistribute(), thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField(), and thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs().
AMI()
const Foam::AMIPatchToPatchInterpolation & AMI (const bool forceUpdate = false) const inline
Return reference to the AMI interpolator.
Definition at line 156 of file mappedPatchBaseI.H.
References mappedPatchBase::AMIPtr_, and mappedPatchBase::calcAMI().
Referenced by mappedPatchBase::distribute(), mappedPatchBase::map(), and mappedPatchBase::reverseDistribute().
surfPtr()
const Foam::autoPtr< Foam::searchableSurface > & surfPtr () const
Return a pointer to the AMI projection surface.
Definition at line 772 of file mappedPatchBase.C.
References polyMesh::boundaryMesh(), TimePaths::constant(), mesh, polyBoundaryMesh::mesh(), IOobject::MUST_READ, searchableSurface::New(), IOobject::NO_WRITE, and objectRegistry::time().
sampleMesh()
const Foam::polyMesh & sampleMesh () const
Get the region mesh.
Definition at line 1236 of file mappedPatchBase.C.
References polyMesh::boundaryMesh(), objectRegistry::lookupObject(), polyBoundaryMesh::mesh(), and objectRegistry::time().
Referenced by radiationCoupledBase::emissivity(), mappedPatchBase::samplePatch(), mappedPatchBase::sampleRegion(), mappedPatchBase::sampleSize(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
samplePolyPatch()
const Foam::polyPatch & samplePolyPatch () const
Get the patch on the region.
Definition at line 1245 of file mappedPatchBase.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::findPatchID(), polyBoundaryMesh::names(), patchi, and mappedPatchBase::samplePoints().
Referenced by radiationCoupledBase::emissivity(), mappedPatchBase::sampleSize(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
samplePoints() [2/2]
Foam::tmp< Foam::pointField > samplePoints () const
Get the sample points.
Definition at line 1299 of file mappedPatchBase.C.
References mappedPatchBase::facePoint().
Referenced by mappedPatchBase::samplePolyPatch().
facePoint()
Foam::pointIndexHit facePoint (const polyMesh & mesh, const label facei, const polyMesh::cellDecomposition decompMode) static
Get a point on the face given a face decomposition method:
face-centre-tet : face centre. Returns index of face. face-planes : face centre. Returns index of face. face-diagonal : intersection of ray from cellcentre to facecentre with any of the triangles. Returns index (0..size-2) of triangle.
Definition at line 1306 of file mappedPatchBase.C.
References Foam::abort(), polyMesh::CELL_TETS, primitiveMesh::cellCentres(), PointHit< Point >::distance(), f(), polyMesh::FACE_CENTRE_TRIS, polyMesh::FACE_DIAG_TRIS, polyMesh::FACE_PLANES, primitiveMesh::faceCentres(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), intersection::HALF_RAY, PointHit< Point >::hit(), PointHit< Point >::hitPoint(), triangle< Point, PointRef >::intersection(), p, polyMesh::points(), List< T >::size(), and polyMesh::tetBasePtIs().
Referenced by nearWallFields::calcAddressing(), and mappedPatchBase::samplePoints().
distribute() [1/2]
void distribute (List< Type > & lst) const
Wrapper around map/interpolate data distribution.
Definition at line 27 of file mappedPatchBaseTemplates.C.
References mappedPatchBase::AMI(), mapDistribute::distribute(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), mappedPatchBase::map(), mappedPatchBase::mode_, mappedPatchBase::NEARESTPATCHFACEAMI, and List< T >::xfer().
Referenced by radiationCoupledBase::emissivity(), regionModel::toRegion(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), mappedFixedInternalValueFvPatchField< Type >::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
distribute() [2/2]
void distribute (List< Type > & lst, const CombineOp & cop) const
Wrapper around map/interpolate data distribution with operation.
Definition at line 46 of file mappedPatchBaseTemplates.C.
References mappedPatchBase::AMI(), UPstream::defaultCommsType, mapDistributeBase::distribute(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), mappedPatchBase::map(), mappedPatchBase::mode_, mappedPatchBase::NEARESTPATCHFACEAMI, List< T >::xfer(), and Foam::Zero.
reverseDistribute() [1/2]
void reverseDistribute (List< Type > & lst) const
Wrapper around map/interpolate data distribution.
Definition at line 84 of file mappedPatchBaseTemplates.C.
References mappedPatchBase::AMI(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), mappedPatchBase::map(), mappedPatchBase::mode_, mappedPatchBase::NEARESTPATCHFACEAMI, mapDistribute::reverseDistribute(), mappedPatchBase::sampleSize(), and List< T >::xfer().
Referenced by regionModel::toPrimary().
reverseDistribute() [2/2]
void reverseDistribute (List< Type > & lst, const CombineOp & cop) const
Wrapper around map/interpolate data distribution with operation.
Definition at line 104 of file mappedPatchBaseTemplates.C.
References mappedPatchBase::AMI(), UPstream::defaultCommsType, mapDistributeBase::distribute(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), mappedPatchBase::map(), mappedPatchBase::mode_, mappedPatchBase::NEARESTPATCHFACEAMI, mappedPatchBase::sampleSize(), List< T >::xfer(), and Foam::Zero.
write()
void write (Ostream & os) const virtual
Write as a dictionary.
Reimplemented in thermalBaffle1DFvPatchScalarField< solidType >, mappedWallPolyPatch, mappedVariableThicknessWallPolyPatch, mappedFieldFvPatchField< Type >, and mappedPolyPatch.
Definition at line 1386 of file mappedPatchBase.C.
References token::END_STATEMENT, Foam::nl, Ostream::writeKeyword(), and VectorSpace< Vector< scalar >, scalar, 3 >::zero.
Referenced by mappedPolyPatch::write(), mappedWallPolyPatch::write(), and thermalBaffle1DFvPatchScalarField< solidType >::write().
Member Data Documentation
sampleModeNames_
const Foam::NamedEnum< Foam::mappedPatchBase::sampleMode, 6 > sampleModeNames_ static
Definition at line 129 of file mappedPatchBase.H.
Referenced by NamedEnum< directionType, 3 >::names(), and thermalBaffleFvPatchScalarField::rmap().
offsetModeNames_
const Foam::NamedEnum< Foam::mappedPatchBase::offsetMode, 3 > offsetModeNames_ static
Definition at line 131 of file mappedPatchBase.H.
Referenced by NamedEnum< directionType, 3 >::names(), and sampledPatchInternalField::sampledPatchInternalField().
patch_
const polyPatch& patch_ protected
Patch to sample.
Definition at line 189 of file mappedPatchBase.H.
Referenced by mappedPatchBase::samplePatch(), and mappedPatchBase::sampleRegion().
sampleRegion_
word sampleRegion_ mutable protected
Region to sample.
Definition at line 192 of file mappedPatchBase.H.
Referenced by mappedPatchBase::samplePatch(), and mappedPatchBase::sampleRegion().
mode_
const sampleMode mode_ protected
What to sample.
Definition at line 195 of file mappedPatchBase.H.
Referenced by mappedPatchBase::distribute(), mappedPatchBase::mode(), mappedPatchBase::reverseDistribute(), and mappedPatchBase::sampleSize().
samplePatch_
word samplePatch_ mutable protected
Patch (if in sampleMode NEARESTPATCH*)
Definition at line 198 of file mappedPatchBase.H.
Referenced by mappedPatchBase::samplePatch(), and mappedPatchBase::sampleRegion().
coupleGroup_
const coupleGroupIdentifier coupleGroup_ protected
PatchGroup (if in sampleMode NEARESTPATCH*)
Definition at line 201 of file mappedPatchBase.H.
Referenced by mappedPatchBase::coupleGroup(), mappedPatchBase::samplePatch(), and mappedPatchBase::sampleRegion().
offsetMode_
offsetMode offsetMode_ protected
How to obtain samples.
Definition at line 204 of file mappedPatchBase.H.
offset_
vector offset_ protected
Offset vector (uniform)
Definition at line 207 of file mappedPatchBase.H.
Referenced by mappedPatchBase::offset().
offsets_
vectorField offsets_ protected
Offset vector (nonuniform)
Definition at line 210 of file mappedPatchBase.H.
Referenced by mappedPatchBase::offsets().
distance_
scalar distance_ protected
Offset distance (normal)
Definition at line 213 of file mappedPatchBase.H.
sameRegion_
bool sameRegion_ mutable protected
Same region.
Definition at line 216 of file mappedPatchBase.H.
Referenced by mappedPatchBase::sameRegion().
mapPtr_
autoPtr<mapDistribute> mapPtr_ mutable protected
Communication schedule:
Cells/faces to sample per processor
Patch faces to receive per processor
schedule
Definition at line 226 of file mappedPatchBase.H.
Referenced by mappedPatchBase::map().
AMIPtr_
autoPtr<AMIPatchToPatchInterpolation> AMIPtr_ mutable protected
Pointer to AMI interpolator.
Definition at line 232 of file mappedPatchBase.H.
Referenced by mappedPatchBase::AMI().
AMIReverse_
const bool AMIReverse_ protected
Flag to indicate that slave patch should be reversed for AMI.
Definition at line 235 of file mappedPatchBase.H.
surfPtr_
autoPtr<searchableSurface> surfPtr_ mutable protected
Pointer to projection surface employed by AMI interpolator.
Definition at line 238 of file mappedPatchBase.H.
surfDict_
dictionary surfDict_ protected
Dictionary storing projection surface description.
Definition at line 241 of file mappedPatchBase.H.
The documentation for this class was generated from the following files:
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBase.H
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBase.C
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBaseI.H
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBaseTemplates.C