OpenFOAM: topoDistanceData Class Reference
topoDistanceData Class Reference
For use with FaceCellWave. Determines topological distance to starting faces.
Public Member Functions
topoDistanceData ()
Construct null.
topoDistanceData (const label data, const label distance)
Construct from count.
label data () const
label distance () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const topoDistanceData &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const topoDistanceData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const topoDistanceData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const topoDistanceData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const topoDistanceData &, TrackingData &td) const
Same (like operator==)
bool operator== (const topoDistanceData &) const
bool operator!= (const topoDistanceData &) const
Friends
Ostream & operator<< (Ostream &, const topoDistanceData &)
Istream & operator>> (Istream &, topoDistanceData &)
Detailed Description
For use with FaceCellWave. Determines topological distance to starting faces.
Source files
topoDistanceData.H
topoDistanceDataI.H
topoDistanceData.C
Definition at line 62 of file topoDistanceData.H.
Constructor & Destructor Documentation
topoDistanceData() [1/2]
topoDistanceData () inline
Construct null.
Definition at line 34 of file topoDistanceDataI.H.
topoDistanceData() [2/2]
topoDistanceData (const label data, const label distance) inline
Construct from count.
Definition at line 43 of file topoDistanceDataI.H.
Member Function Documentation
data()
label data () const inline
Definition at line 93 of file topoDistanceData.H.
Referenced by structuredRenumber::layerLess::operator()(), and topoDistanceData::operator==().
distance()
label distance () const inline
Definition at line 97 of file topoDistanceData.H.
References topoDistanceData::enterDomain(), topoDistanceData::equal(), topoDistanceData::leaveDomain(), topoDistanceData::operator!=(), topoDistanceData::operator<<, topoDistanceData::operator==(), topoDistanceData::operator>>, topoDistanceData::sameGeometry(), topoDistanceData::transform(), topoDistanceData::updateCell(), topoDistanceData::updateFace(), and topoDistanceData::valid().
Referenced by structuredRenumber::layerLess::operator()(), and topoDistanceData::operator==().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 56 of file topoDistanceDataI.H.
References topoDistanceData::sameGeometry().
Referenced by topoDistanceData::distance(), and structuredRenumber::layerLess::operator()().
sameGeometry()
bool sameGeometry (const polyMesh & , const topoDistanceData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 65 of file topoDistanceDataI.H.
References topoDistanceData::leaveDomain().
Referenced by topoDistanceData::distance(), and topoDistanceData::valid().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 79 of file topoDistanceDataI.H.
References topoDistanceData::transform().
Referenced by topoDistanceData::distance(), and topoDistanceData::sameGeometry().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 103 of file topoDistanceDataI.H.
References topoDistanceData::updateCell().
Referenced by topoDistanceData::distance(), and topoDistanceData::transform().
transform()
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 92 of file topoDistanceDataI.H.
References topoDistanceData::enterDomain().
Referenced by topoDistanceData::distance(), and topoDistanceData::leaveDomain().
updateCell()
bool updateCell (const polyMesh & , const label thisCelli, const label neighbourFacei, const topoDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 116 of file topoDistanceDataI.H.
References topoDistanceData::updateFace().
Referenced by topoDistanceData::distance(), and topoDistanceData::enterDomain().
updateFace() [1/2]
bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const topoDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 140 of file topoDistanceDataI.H.
Referenced by topoDistanceData::distance(), and topoDistanceData::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & , const label thisFacei, const topoDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 167 of file topoDistanceDataI.H.
References topoDistanceData::equal().
equal()
bool equal (const topoDistanceData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 190 of file topoDistanceDataI.H.
References topoDistanceData::operator==().
Referenced by topoDistanceData::distance(), and topoDistanceData::updateFace().
operator==()
bool operator== (const topoDistanceData & rhs) const inline
Definition at line 202 of file topoDistanceDataI.H.
References topoDistanceData::data(), and topoDistanceData::distance().
Referenced by topoDistanceData::distance(), and topoDistanceData::equal().
operator!=()
bool operator!= (const topoDistanceData & rhs) const inline
Definition at line 211 of file topoDistanceDataI.H.
Referenced by topoDistanceData::distance().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const topoDistanceData &) friend
Referenced by topoDistanceData::distance().
operator>>
Istream& operator>> (Istream & , topoDistanceData &) friend
Referenced by topoDistanceData::distance().
The documentation for this class was generated from the following files:
src/meshTools/meshStructure/topoDistanceData.H
src/meshTools/meshStructure/topoDistanceDataI.H