OpenFOAM: treeDataPrimitivePatch< PatchType >::findSelfIntersectOp Class Reference
treeDataPrimitivePatch< PatchType >::findSelfIntersectOp Class Reference
Public Member Functions
findSelfIntersectOp (const indexedOctree< treeDataPrimitivePatch > &tree, const label edgeID)
bool operator() (const label index, const point &start, const point &end, point &intersectionPoint) const
Calculate intersection of face with edge of patch. Excludes.
Detailed Description
template<class PatchType>
class Foam::treeDataPrimitivePatch< PatchType >::findSelfIntersectOp
Definition at line 171 of file treeDataPrimitivePatch.H.
Constructor & Destructor Documentation
findSelfIntersectOp()
findSelfIntersectOp (const indexedOctree< treeDataPrimitivePatch > & tree, const label edgeID)
Definition at line 123 of file treeDataPrimitivePatch.C.
Referenced by treeDataPrimitivePatch< PatchType >::findAllIntersectOp::findAllIntersectOp().
Member Function Documentation
operator()()
bool operator() (const label index, const point & start, const point & end, point & intersectionPoint) const
Calculate intersection of face with edge of patch. Excludes.
faces that use edgeID. Used to find self intersection.
Definition at line 577 of file treeDataPrimitivePatch.C.
References Foam::constant::electromagnetic::e, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), treeDataPrimitivePatch< PatchType >::findIntersection(), and treeDataPrimitivePatch< PatchType >::patch().
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataPrimitivePatch.H
src/meshTools/indexedOctree/treeDataPrimitivePatch.C