OpenFOAM: momentOfInertia Class Reference
momentOfInertia Class Reference
Calculates the inertia tensor and principal axes and moments of a polyhedra/cells/triSurfaces. Inertia can either be of the solid body or of a thin shell.
Static Public Member Functions
static void massPropertiesSolid (const pointField &pts, const triFaceList &triFaces, scalar density, scalar &mass, vector &cM, tensor &J)
static void massPropertiesShell (const pointField &pts, const triFaceList &triFaces, scalar density, scalar &mass, vector &cM, tensor &J)
static void massPropertiesSolid (const triSurface &surf, scalar density, scalar &mass, vector &cM, tensor &J)
static void massPropertiesShell (const triSurface &surf, scalar density, scalar &mass, vector &cM, tensor &J)
static tensor applyParallelAxisTheorem (scalar mass, const vector &cM, const tensor &J, const vector &refPt)
static tmp< tensorField > meshInertia (const polyMesh &mesh)
static tensor meshInertia (const polyMesh &mesh, label celli)
Detailed Description
Calculates the inertia tensor and principal axes and moments of a polyhedra/cells/triSurfaces. Inertia can either be of the solid body or of a thin shell.
Source files
momentOfInertia.H
momentOfInertia.H
Definition at line 52 of file momentOfInertia.H.
Member Function Documentation
massPropertiesSolid() [1/2]
void massPropertiesSolid (const pointField & pts, const triFaceList & triFaces, scalar density, scalar & mass, vector & cM, tensor & J) static
Definition at line 32 of file momentOfInertia.C.
References forAll, Foam::I, momentOfInertia::massPropertiesShell(), n, Vector< Cmpt >::x(), Tensor< Cmpt >::xx(), Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), Vector< Cmpt >::y(), Tensor< Cmpt >::yx(), Tensor< Cmpt >::yy(), Tensor< Cmpt >::yz(), Vector< Cmpt >::z(), Tensor< Cmpt >::zx(), Tensor< Cmpt >::zy(), and Tensor< Cmpt >::zz().
Referenced by momentOfInertia::massPropertiesShell().
massPropertiesShell() [1/2]
void massPropertiesShell (const pointField & pts, const triFaceList & triFaces, scalar density, scalar & mass, vector & cM, tensor & J) static
Definition at line 189 of file momentOfInertia.C.
References triangle< Point, PointRef >::centre(), forAll, triangle< Point, PointRef >::mag(), momentOfInertia::massPropertiesSolid(), and Foam::Zero.
Referenced by momentOfInertia::massPropertiesSolid().
massPropertiesSolid() [2/2]
void massPropertiesSolid (const triSurface & surf, scalar density, scalar & mass, vector & cM, tensor & J) static
Definition at line 245 of file momentOfInertia.C.
References forAll, momentOfInertia::massPropertiesShell(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), List< T >::size(), and triFace().
massPropertiesShell() [2/2]
void massPropertiesShell (const triSurface & surf, scalar density, scalar & mass, vector & cM, tensor & J) static
Definition at line 265 of file momentOfInertia.C.
References momentOfInertia::applyParallelAxisTheorem(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), List< T >::size(), and triFace().
applyParallelAxisTheorem()
Foam::tensor applyParallelAxisTheorem (scalar mass, const vector & cM, const tensor & J, const vector & refPt) static
Definition at line 285 of file momentOfInertia.C.
References Foam::I, and momentOfInertia::meshInertia().
Referenced by momentOfInertia::massPropertiesShell().
meshInertia() [1/2]
Foam::tmp< Foam::tensorField > meshInertia (const polyMesh & mesh) static
Definition at line 303 of file momentOfInertia.C.
References forAll, primitiveMesh::nCells(), tmp< T >::ref(), and tf.
Referenced by momentOfInertia::applyParallelAxisTheorem().
meshInertia() [2/2]
Foam::tensor meshInertia (const polyMesh & mesh, label celli) static
Definition at line 321 of file momentOfInertia.C.
References forAll, polyMesh::points(), List< T >::size(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/meshTools/momentOfInertia/momentOfInertia.H
src/meshTools/momentOfInertia/momentOfInertia.C