OpenFOAM: primitiveMeshGeometry Class Reference
primitiveMeshGeometry Class Reference
Updateable mesh geometry + checking routines.
Public Member Functions
ClassName ("primitiveMeshGeometry")
primitiveMeshGeometry (const primitiveMesh &)
Construct from mesh.
const primitiveMesh & mesh () const
const vectorField & faceAreas () const
const vectorField & faceCentres () const
const vectorField & cellCentres () const
const scalarField & cellVolumes () const
void correct ()
Take over properties from mesh.
void correct (const pointField &p, const labelList &changedFaces)
Recalculate on selected faces. Recalculates cell properties.
labelList affectedCells (const labelList &changedFaces) const
Helper function: get affected cells from faces.
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceArea (const bool report, const scalar minArea, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr) const
Static Public Member Functions
static bool checkFaceDotProduct (const bool report, const scalar orthWarn, const primitiveMesh &, const vectorField &cellCentres, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFacePyramids (const bool report, const scalar minPyrVol, const primitiveMesh &, const vectorField &cellCentres, const pointField &p, const labelList &checkFaces, labelHashSet *)
static bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const primitiveMesh &mesh, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceWeights (const bool report, const scalar warnWeight, const primitiveMesh &mesh, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceAngles (const bool report, const scalar maxDeg, const primitiveMesh &mesh, const vectorField &faceAreas, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceTwist (const bool report, const scalar minTwist, const primitiveMesh &, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceArea (const bool report, const scalar minArea, const primitiveMesh &, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkCellDeterminant (const bool report, const scalar minDet, const primitiveMesh &, const vectorField &faceAreas, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr)
Detailed Description
Updateable mesh geometry + checking routines.
Source files
primitiveMeshGeometry.H
primitiveMeshGeometry.C
Definition at line 49 of file primitiveMeshGeometry.H.
Constructor & Destructor Documentation
primitiveMeshGeometry()
primitiveMeshGeometry (const primitiveMesh & mesh)
Construct from mesh.
Definition at line 218 of file primitiveMeshGeometry.C.
References correct.
Referenced by primitiveMeshGeometry::affectedCells().
Member Function Documentation
ClassName()
ClassName ("primitiveMeshGeometry")
mesh()
const primitiveMesh& mesh () const inline
Definition at line 98 of file primitiveMeshGeometry.H.
Referenced by primitiveMeshGeometry::cellVolumes().
faceAreas()
const vectorField& faceAreas () const inline
Definition at line 103 of file primitiveMeshGeometry.H.
Referenced by primitiveMeshGeometry::cellVolumes().
faceCentres()
const vectorField& faceCentres () const inline
Definition at line 107 of file primitiveMeshGeometry.H.
Referenced by primitiveMeshGeometry::cellVolumes().
cellCentres()
const vectorField& cellCentres () const inline
Definition at line 111 of file primitiveMeshGeometry.H.
Referenced by primitiveMeshGeometry::cellVolumes().
cellVolumes()
const scalarField& cellVolumes () const inline
Definition at line 115 of file primitiveMeshGeometry.H.
References primitiveMeshGeometry::affectedCells(), primitiveMeshGeometry::cellCentres(), primitiveMeshGeometry::checkCellDeterminant(), primitiveMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFaceArea(), primitiveMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFaceSkewness(), primitiveMeshGeometry::checkFaceTwist(), primitiveMeshGeometry::checkFaceWeights(), primitiveMeshGeometry::correct(), primitiveMeshGeometry::faceAreas(), primitiveMeshGeometry::faceCentres(), and primitiveMeshGeometry::mesh().
correct() [1/2]
void correct ()
Take over properties from mesh.
Definition at line 233 of file primitiveMeshGeometry.C.
Referenced by primitiveMeshGeometry::cellVolumes().
correct() [2/2]
void correct (const pointField & p, const labelList & changedFaces)
Recalculate on selected faces. Recalculates cell properties.
on owner and neighbour of these cells.
Definition at line 243 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkFaceDotProduct().
affectedCells()
Foam::labelList affectedCells (const labelList & changedFaces) const
Helper function: get affected cells from faces.
Definition at line 189 of file primitiveMeshGeometry.C.
References forAll, primitiveMeshGeometry::primitiveMeshGeometry(), and List< T >::size().
Referenced by primitiveMeshGeometry::cellVolumes().
checkFaceDotProduct() [1/2]
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const primitiveMesh & mesh, const vectorField & cellCentres, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 256 of file primitiveMeshGeometry.C.
References Foam::acos(), primitiveMeshGeometry::checkFacePyramids(), Foam::cos(), Foam::degToRad(), Foam::endl(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), Foam::mag(), Foam::Pout, Foam::radToDeg(), Foam::reduce(), s(), SeriousErrorInFunction, List< T >::size(), and WarningInFunction.
Referenced by primitiveMeshGeometry::cellVolumes(), primitiveMeshGeometry::checkCellDeterminant(), and primitiveMeshGeometry::correct().
checkFacePyramids() [1/2]
bool checkFacePyramids (const bool report, const scalar minPyrVol, const primitiveMesh & mesh, const vectorField & cellCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 399 of file primitiveMeshGeometry.C.
References primitiveMesh::cells(), primitiveMeshGeometry::checkFaceSkewness(), Foam::endl(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), primitiveMesh::faces(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), Foam::Pout, Foam::reduce(), and SeriousErrorInFunction.
Referenced by primitiveMeshGeometry::cellVolumes(), and primitiveMeshGeometry::checkFaceDotProduct().
checkFaceSkewness() [1/2]
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const primitiveMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 511 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkFaceWeights(), Foam::endl(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), Foam::mag(), Foam::nl, Foam::Pout, Foam::reduce(), and WarningInFunction.
Referenced by primitiveMeshGeometry::cellVolumes(), and primitiveMeshGeometry::checkFacePyramids().
checkFaceWeights() [1/2]
bool checkFaceWeights (const bool report, const scalar warnWeight, const primitiveMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 651 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkFaceAngles(), Foam::endl(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), primitiveMesh::isInternalFace(), Foam::mag(), Foam::min(), Foam::nl, Foam::Pout, Foam::reduce(), and WarningInFunction.
Referenced by primitiveMeshGeometry::cellVolumes(), and primitiveMeshGeometry::checkFaceSkewness().
checkFaceAngles() [1/2]
bool checkFaceAngles (const bool report, const scalar maxDeg, const primitiveMesh & mesh, const vectorField & faceAreas, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 737 of file primitiveMeshGeometry.C.
References Foam::abort(), Foam::asin(), primitiveMeshGeometry::checkFaceTwist(), Foam::degToRad(), Foam::endl(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), UList< T >::first(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), UList< T >::last(), Foam::mag(), Foam::max(), Foam::min(), Foam::radToDeg(), Foam::reduce(), Foam::sin(), and WarningInFunction.
Referenced by primitiveMeshGeometry::cellVolumes(), and primitiveMeshGeometry::checkFaceWeights().
checkFaceTwist() [1/2]
bool checkFaceTwist (const bool report, const scalar minTwist, const primitiveMesh & mesh, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 1000 of file primitiveMeshGeometry.C.
References Foam::abort(), primitiveMeshGeometry::checkFaceArea(), Foam::endl(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), face::nextLabel(), Foam::nl, Foam::reduce(), List< T >::size(), and WarningInFunction.
Referenced by primitiveMeshGeometry::cellVolumes(), and primitiveMeshGeometry::checkFaceAngles().
checkFaceArea() [1/2]
bool checkFaceArea (const bool report, const scalar minArea, const primitiveMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 1108 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkCellDeterminant(), Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::nl, Foam::reduce(), and WarningInFunction.
Referenced by primitiveMeshGeometry::cellVolumes(), and primitiveMeshGeometry::checkFaceTwist().
checkCellDeterminant() [1/2]
bool checkCellDeterminant (const bool report, const scalar minDet, const primitiveMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) static
Definition at line 1169 of file primitiveMeshGeometry.C.
References cells, primitiveMesh::cells(), primitiveMeshGeometry::checkFaceDotProduct(), Foam::det(), Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::min(), Foam::nl, Foam::reduce(), WarningInFunction, and Foam::Zero.
Referenced by primitiveMeshGeometry::cellVolumes(), and primitiveMeshGeometry::checkFaceArea().
checkFaceDotProduct() [2/2]
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1270 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkFacePyramids().
checkFacePyramids() [2/2]
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1291 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkFaceSkewness().
checkFaceSkewness() [2/2]
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1313 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkFaceWeights().
checkFaceWeights() [2/2]
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1337 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkFaceAngles().
checkFaceAngles() [2/2]
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1359 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkFaceTwist().
checkFaceTwist() [2/2]
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1404 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkFaceArea().
checkFaceArea() [2/2]
bool checkFaceArea (const bool report, const scalar minArea, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1427 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::checkCellDeterminant().
checkCellDeterminant() [2/2]
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) const
Definition at line 1447 of file primitiveMeshGeometry.C.
The documentation for this class was generated from the following files:
src/meshTools/primitiveMeshGeometry/primitiveMeshGeometry.H
src/meshTools/primitiveMeshGeometry/primitiveMeshGeometry.C