OpenFOAM: treeDataPrimitivePatch< PatchType >::findNearestOp Class Reference
treeDataPrimitivePatch< PatchType >::findNearestOp Class Reference
Public Member Functions
findNearestOp (const indexedOctree< treeDataPrimitivePatch > &tree)
void operator() (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &minIndex, point &nearestPoint) const
void operator() (const labelUList &indices, const linePointRef &ln, treeBoundBox &tightest, label &minIndex, point &linePoint, point &nearestPoint) const
Calculates nearest (to line) point in shape.
Detailed Description
template<class PatchType>
class Foam::treeDataPrimitivePatch< PatchType >::findNearestOp
Definition at line 92 of file treeDataPrimitivePatch.H.
Constructor & Destructor Documentation
findNearestOp()
findNearestOp (const indexedOctree< treeDataPrimitivePatch > & tree)
Definition at line 90 of file treeDataPrimitivePatch.C.
References treeDataPrimitivePatch< PatchType >::findIntersectOp::findIntersectOp().
Referenced by treeDataPrimitivePatch< PatchType >::treeDataPrimitivePatch().
Member Function Documentation
operator()() [1/2]
void operator() (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & minIndex, point & nearestPoint) const
Definition at line 496 of file treeDataPrimitivePatch.C.
References PointHit< Point >::distance(), forAll, treeDataPrimitivePatch< PatchType >::patch(), PointHit< Point >::rawPoint(), and Foam::sqr().
operator()() [2/2]
void operator() (const labelUList & indices, const linePointRef & ln, treeBoundBox & tightest, label & minIndex, point & linePoint, point & nearestPoint) const
Calculates nearest (to line) point in shape.
Returns point and distance (squared)
Definition at line 530 of file treeDataPrimitivePatch.C.
References NotImplemented.
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataPrimitivePatch.H
src/meshTools/indexedOctree/treeDataPrimitivePatch.C