OpenFOAM: regionCoupledGAMGInterfaceField Class Reference
regionCoupledGAMGInterfaceField Class Reference
GAMG agglomerated region coupled interface field.
Public Member Functions
TypeName ("regionCoupled")
Runtime type information.
regionCoupledGAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterfaceField)
Construct from GAMG interface and fine level interface field.
regionCoupledGAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
virtual ~regionCoupledGAMGInterfaceField ()
Destructor.
label size () const
Return size.
virtual void updateInterfaceMatrix (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Interface matrix update.
Public Member Functions inherited from GAMGInterfaceField
TypeName ("GAMGInterfaceField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterfaceField,(const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface),(GAMGCp, fineInterface))
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterface,(const GAMGInterface &GAMGCp, const bool doTransform, const int rank),(GAMGCp, doTransform, rank))
GAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &)
Construct from GAMG interface and fine level interface field.
GAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
const GAMGInterface & interface () const
Return interface.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterfaceField
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Return a pointer to a new interface created on freestore given.
Detailed Description
GAMG agglomerated region coupled interface field.
Source files
regionCoupledGAMGInterfaceField.H
regionCoupledGAMGInterfaceField.C
Definition at line 50 of file regionCoupledGAMGInterfaceField.H.
Constructor & Destructor Documentation
regionCoupledGAMGInterfaceField() [1/2]
regionCoupledGAMGInterfaceField (const GAMGInterface & GAMGCp, const lduInterfaceField & fineInterfaceField)
Construct from GAMG interface and fine level interface field.
Definition at line 53 of file regionCoupledGAMGInterfaceField.C.
regionCoupledGAMGInterfaceField() [2/2]
regionCoupledGAMGInterfaceField (const GAMGInterface & GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
Definition at line 67 of file regionCoupledGAMGInterfaceField.C.
~regionCoupledGAMGInterfaceField()
~regionCoupledGAMGInterfaceField () virtual
Destructor.
Definition at line 83 of file regionCoupledGAMGInterfaceField.C.
Member Function Documentation
TypeName()
TypeName ("regionCoupled")
Runtime type information.
size()
label size () const inline
Return size.
Definition at line 104 of file regionCoupledGAMGInterfaceField.H.
References GAMGInterface::size(), and regionCoupledGAMGInterfaceField::updateInterfaceMatrix().
updateInterfaceMatrix()
virtual void updateInterfaceMatrix (scalarField & , const scalarField & , const scalarField & , const direction , const Pstream::commsTypes commsType) const inline virtual
Interface matrix update.
Implements lduInterfaceField.
Definition at line 112 of file regionCoupledGAMGInterfaceField.H.
Referenced by regionCoupledGAMGInterfaceField::size().
The documentation for this class was generated from the following files:
src/meshTools/regionCoupled/GAMG/interfaceFields/regionCoupledGAMGInterfaceField/regionCoupledGAMGInterfaceField.H
src/meshTools/regionCoupled/GAMG/interfaceFields/regionCoupledGAMGInterfaceField/regionCoupledGAMGInterfaceField.C