OpenFOAM: regionCoupledWallPolyPatch Class Reference
regionCoupledWallPolyPatch Class Reference
regionCoupledWall
Public Member Functions
TypeName ("regionCoupledWall")
Runtime type information.
regionCoupledWallPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
regionCoupledWallPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
regionCoupledWallPolyPatch (const regionCoupledWallPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
regionCoupledWallPolyPatch (const regionCoupledWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
regionCoupledWallPolyPatch (const regionCoupledWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< wallPolyPatch::polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< wallPolyPatch::polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~regionCoupledWallPolyPatch ()
Destructor.
virtual const word & regionCoupleType () const
Return the type.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from wallPolyPatch
TypeName ("wall")
Runtime type information.
wallPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
wallPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
wallPolyPatch (const wallPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
wallPolyPatch (const wallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
wallPolyPatch (const wallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual bool coupled () const
Return true if this patch is geometrically coupled (i.e. faces and.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from regionCoupledBase
TypeName ("regionCoupledBase")
Runtime type information.
regionCoupledBase (const polyPatch &)
Construct from patch.
regionCoupledBase (const polyPatch &, const dictionary &)
Construct from dictionary.
regionCoupledBase (const polyPatch &, const regionCoupledBase &)
Construct as copy, resetting patch.
virtual ~regionCoupledBase ()
Destructor.
const word & nbrPatchName () const
Neighbour patch name.
const word & nbrRegionName () const
Neighbour region name.
bool sameRegion () const
Cached sampleRegion != mesh.name()
label neighbPatchID () const
Neighbour patch ID.
bool owner () const
Does this side own the patch?
const regionCoupledBase & neighbPatch () const
Return a reference to the neighbour patch.
const autoPtr< searchableSurface > & surfPtr () const
Return a reference to the projection surface.
const AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fld) const
Interpolate field.
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type >> &tFld) const
Interpolate tmp field.
template<class Type , class BinaryOp >
void interpolate (const UList< Type > &fld, const BinaryOp &bop, List< Type > &result) const
Low-level interpolate List.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &fld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type >> &tFld) const
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Protected Member Functions inherited from regionCoupledBase
virtual void clearGeom ()
Clear geometry.
Additional Inherited Members
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Detailed Description
regionCoupledWall
Source files
regionCoupledWallPolyPatch.H
regionCoupledWallPolyPatch.C
Definition at line 52 of file regionCoupledWallPolyPatch.H.
Constructor & Destructor Documentation
regionCoupledWallPolyPatch() [1/5]
regionCoupledWallPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from components.
Definition at line 49 of file regionCoupledWallPolyPatch.C.
Referenced by regionCoupledWallPolyPatch::clone(), and regionCoupledWallPolyPatch::regionCoupledWallPolyPatch().
regionCoupledWallPolyPatch() [2/5]
regionCoupledWallPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 64 of file regionCoupledWallPolyPatch.C.
References regionCoupledWallPolyPatch::regionCoupledWallPolyPatch().
regionCoupledWallPolyPatch() [3/5]
regionCoupledWallPolyPatch (const regionCoupledWallPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 78 of file regionCoupledWallPolyPatch.C.
References regionCoupledWallPolyPatch::regionCoupledWallPolyPatch().
regionCoupledWallPolyPatch() [4/5]
regionCoupledWallPolyPatch (const regionCoupledWallPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 89 of file regionCoupledWallPolyPatch.C.
References regionCoupledWallPolyPatch::regionCoupledWallPolyPatch().
regionCoupledWallPolyPatch() [5/5]
regionCoupledWallPolyPatch (const regionCoupledWallPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 103 of file regionCoupledWallPolyPatch.C.
~regionCoupledWallPolyPatch()
~regionCoupledWallPolyPatch () virtual
Destructor.
Definition at line 118 of file regionCoupledWallPolyPatch.C.
References regionCoupledBase::clearGeom().
Referenced by regionCoupledWallPolyPatch::clone().
Member Function Documentation
initGeometry()
void initGeometry (PstreamBuffers & pBufs) protected virtual
Initialise the calculation of the patch geometry.
Reimplemented from polyPatch.
Definition at line 126 of file regionCoupledWallPolyPatch.C.
References polyPatch::initGeometry().
calcGeometry()
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Calculate the patch geometry.
Reimplemented from polyPatch.
Definition at line 132 of file regionCoupledWallPolyPatch.C.
References polyPatch::calcGeometry(), regionCoupledBase::clearGeom(), and regionCoupledWallPolyPatch::initMovePoints().
initMovePoints()
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Initialise the patches for moving points.
Reimplemented from polyPatch.
Definition at line 140 of file regionCoupledWallPolyPatch.C.
References polyPatch::initMovePoints(), and regionCoupledWallPolyPatch::movePoints().
Referenced by regionCoupledWallPolyPatch::calcGeometry().
movePoints()
void movePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Correct patches after moving points.
Reimplemented from polyPatch.
Definition at line 150 of file regionCoupledWallPolyPatch.C.
References regionCoupledBase::clearGeom(), and polyPatch::movePoints().
Referenced by regionCoupledWallPolyPatch::initMovePoints().
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Reimplemented from polyPatch.
Definition at line 160 of file regionCoupledWallPolyPatch.C.
References polyPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Update of the patch topology.
Reimplemented from polyPatch.
Definition at line 166 of file regionCoupledWallPolyPatch.C.
References regionCoupledBase::clearGeom(), and polyPatch::updateMesh().
TypeName()
TypeName ("regionCoupledWall")
Runtime type information.
clone() [1/3]
virtual autoPtr<wallPolyPatch::polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from wallPolyPatch.
Definition at line 139 of file regionCoupledWallPolyPatch.H.
References regionCoupledWallPolyPatch::regionCoupledWallPolyPatch().
Referenced by regionCoupledWallPolyPatch::clone().
clone() [2/3]
virtual autoPtr<wallPolyPatch::polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from wallPolyPatch.
Definition at line 152 of file regionCoupledWallPolyPatch.H.
References regionCoupledWallPolyPatch::clone(), and regionCoupledWallPolyPatch::regionCoupledWallPolyPatch().
clone() [3/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from wallPolyPatch.
Definition at line 175 of file regionCoupledWallPolyPatch.H.
References regionCoupledWallPolyPatch::regionCoupledWallPolyPatch(), and regionCoupledWallPolyPatch::~regionCoupledWallPolyPatch().
regionCoupleType()
virtual const word& regionCoupleType () const inline virtual
Return the type.
Implements regionCoupledBase.
Definition at line 203 of file regionCoupledWallPolyPatch.H.
References Foam::type(), and regionCoupledWallPolyPatch::write().
write()
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from regionCoupledBase.
Definition at line 173 of file regionCoupledWallPolyPatch.C.
References regionCoupledBase::write(), and polyPatch::write().
Referenced by regionCoupledWallPolyPatch::regionCoupleType().
The documentation for this class was generated from the following files:
src/meshTools/regionCoupled/patches/regionCoupledPolyPatch/regionCoupledWallPolyPatch.H
src/meshTools/regionCoupled/patches/regionCoupledPolyPatch/regionCoupledWallPolyPatch.C