OpenFOAM: localPointRegion Class Reference
localPointRegion Class Reference
Takes mesh with 'baffles' (= boundary faces sharing points). Determines for selected points on boundary faces the 'point region' it is connected to. Each region can be visited by a cell-face-cell walk. Used in duplicating points after splitting baffles.
Public Member Functions
ClassName ("localPointRegion")
Runtime type information.
localPointRegion (const polyMesh &mesh)
Construct from mesh. Assumes all non-coupled boundary points.
localPointRegion (const polyMesh &mesh, const labelList &candidatePoints)
Construct from mesh and candidate points for duplication.
const Map< label > & meshPointMap () const
Per point that is to be duplicated the local index.
const labelListList & pointRegions () const
Per local point the regions it is in.
const Map< label > & meshFaceMap () const
Per face that uses a duplicated point the local index.
const faceList & faceRegions () const
Per face the region of its points.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
Static Public Member Functions
static labelList findDuplicateFaces (const primitiveMesh &, const labelList &)
Helper routine to find baffles (two boundary faces using the.
static labelPairList findDuplicateFacePairs (const polyMesh &)
Helper routine to find all baffles (two boundary faces.
Detailed Description
Takes mesh with 'baffles' (= boundary faces sharing points). Determines for selected points on boundary faces the 'point region' it is connected to. Each region can be visited by a cell-face-cell walk. Used in duplicating points after splitting baffles.
Regions are not consecutive per processor. They will be -1..nRegions_.
Note: coupled boundaries (cyclics, parallel) not fully tested.
Source files
localPointRegion.H
localPointRegion.C
Definition at line 67 of file localPointRegion.H.
Constructor & Destructor Documentation
localPointRegion() [1/2]
localPointRegion (const polyMesh & mesh)
Construct from mesh. Assumes all non-coupled boundary points.
are candidates for duplication
Definition at line 446 of file localPointRegion.C.
References polyMesh::boundaryMesh(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), primitiveMesh::nPoints(), patches, and patchi.
localPointRegion() [2/2]
localPointRegion (const polyMesh & mesh, const labelList & candidatePoints)
Construct from mesh and candidate points for duplication.
Definition at line 477 of file localPointRegion.C.
References localPointRegion::findDuplicateFaces(), forAll, and primitiveMesh::nPoints().
Member Function Documentation
ClassName()
ClassName ("localPointRegion")
Runtime type information.
findDuplicateFaces()
Foam::labelList findDuplicateFaces (const primitiveMesh & mesh, const labelList & boundaryFaces) static
Helper routine to find baffles (two boundary faces using the.
same points but in reverse order) Gets list of (boundary!) faces to check. Returns labelList of same size as the input list with -1 or index of other face in the input list. Does not handle duplicate faces on both sides of processor patch
Definition at line 504 of file localPointRegion.C.
References Foam::abort(), f(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, localPointRegion::findDuplicateFacePairs(), forAll, primitiveMesh::nInternalFaces(), Foam::nl, pFaces, and primitiveMesh::points().
Referenced by meshRefinement::checkData(), localPointRegion::findDuplicateFacePairs(), and localPointRegion::localPointRegion().
findDuplicateFacePairs()
Foam::List< Foam::labelPair > findDuplicateFacePairs (const polyMesh & mesh) static
Helper routine to find all baffles (two boundary faces.
using the same points but in reverse order)
Definition at line 583 of file localPointRegion.C.
References Foam::abort(), polyMesh::boundaryMesh(), Foam::FatalError, FatalErrorInFunction, localPointRegion::findDuplicateFaces(), forAll, Foam::identity(), IOobject::name(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, patches, and polyBoundaryMesh::whichPatch().
Referenced by preserveBafflesConstraint::add(), preserveBafflesConstraint::apply(), meshRefinement::baffleAndSplitMesh(), meshRefinement::balance(), localPointRegion::findDuplicateFaces(), snappyLayerDriver::mergePatchFacesUndo(), displacementMeshMoverMotionSolver::meshMover(), and snappyRefineDriver::snappyRefineDriver().
meshPointMap()
const Map<label>& meshPointMap () const inline
Per point that is to be duplicated the local index.
Definition at line 165 of file localPointRegion.H.
Referenced by meshRefinement::dupNonManifoldPoints(), and duplicatePoints::setRefinement().
pointRegions()
const labelListList& pointRegions () const inline
Per local point the regions it is in.
Definition at line 171 of file localPointRegion.H.
Referenced by duplicatePoints::setRefinement().
meshFaceMap()
const Map<label>& meshFaceMap () const inline
Per face that uses a duplicated point the local index.
Definition at line 177 of file localPointRegion.H.
Referenced by duplicatePoints::setRefinement().
faceRegions()
const faceList& faceRegions () const inline
Per face the region of its points.
Definition at line 183 of file localPointRegion.H.
References localPointRegion::updateMesh().
Referenced by duplicatePoints::setRefinement().
updateMesh()
void updateMesh (const mapPolyMesh & map)
Force recalculation of locally stored data on topological change.
Definition at line 639 of file localPointRegion.C.
References forAllConstIter(), newPointi, mapPolyMesh::reverseFaceMap(), mapPolyMesh::reversePointMap(), HashTable< T, Key, Hash >::size(), and HashTable< T, Key, Hash >::transfer().
Referenced by localPointRegion::faceRegions().
The documentation for this class was generated from the following files:
src/meshTools/regionSplit/localPointRegion.H
src/meshTools/regionSplit/localPointRegion.C