OpenFOAM: searchablePlane Class Reference
searchablePlane Class Reference
Searching on (infinite) plane. See plane.H.
Public Member Functions
TypeName ("searchablePlane")
Runtime type information.
searchablePlane (const IOobject &io, const point &basePoint, const vector &normal)
Construct from components.
searchablePlane (const IOobject &io, const dictionary &dict)
Construct from dictionary (used by searchableSurface)
virtual ~searchablePlane ()
Destructor.
virtual const wordList & regions () const
Names of regions.
virtual bool hasVolumeType () const
Whether supports volume type below.
virtual label size () const
Range of local indices that can be returned.
virtual tmp< pointField > coordinates () const
Get representative set of element coordinates.
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const
Get bounding spheres (centre and radius squared), one per element.
virtual tmp< pointField > points () const
Get the points that define the surface.
virtual bool overlaps (const boundBox &bb) const
Does any part of the surface overlap the supplied bound box?
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &) const
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Find first intersection on segment from start to end.
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Return any intersection on segment from start to end.
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit >> &) const
Get all intersections in order from start to end.
virtual void getRegion (const List< pointIndexHit > &, labelList &region) const
From a set of points and indices get the region.
virtual void getNormal (const List< pointIndexHit > &, vectorField &normal) const
From a set of points and indices get the normal.
virtual void getVolumeType (const pointField &, List< volumeType > &) const
Determine type (inside/outside/mixed) for point. unknown if.
bool writeData (Ostream &) const
Pure virtual writaData function.
Public Member Functions inherited from searchableSurface
TypeName ("searchableSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr< searchableSurface > clone () const
Clone.
virtual ~searchableSurface ()
Destructor.
const boundBox & bounds () const
Return const reference to boundBox.
boundBox & bounds ()
Return non-const access to the boundBox to allow it to be set.
virtual label globalSize () const
Range of global indices that can be returned.
virtual void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
Find the nearest locations for the supplied points to a.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &, vectorField &normal, labelList &region) const
Find nearest, normal and region. Can be overridden with.
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
Set bounds of surface. Bounds currently set as list of.
virtual void setField (const labelList &values)
WIP. Store element-wise field.
virtual void getField (const List< pointIndexHit > &, labelList &values) const
WIP. From a set of hits (points and.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from plane
plane (const vector &normalVector)
Construct from normal vector through the origin.
plane (const point &basePoint, const vector &normalVector)
Construct from normal vector and point in plane.
plane (const point &point1, const point &point2, const point &point3)
Construct from three points in plane.
plane (const scalarList &C)
Construct from coefficients for the.
plane (const dictionary &planeDict)
Construct from dictionary.
plane (Istream &is)
Construct from Istream. Assumes the base + normal notation.
const vector & normal () const
Return plane normal.
const point & refPoint () const
Return or return plane base point.
FixedList< scalar, 4 > planeCoeffs () const
Return coefficients for the.
point nearestPoint (const point &p) const
Return nearest point in the plane for the given point.
scalar distance (const point &p) const
Return distance from the given point to the plane.
scalar normalIntersect (const point &pnt0, const vector &dir) const
Return cut coefficient for plane and line defined by.
scalar normalIntersect (const ray &r) const
Return cut coefficient for plane and ray.
template<class Point , class PointRef >
scalar lineIntersect (const line< Point, PointRef > &l) const
Return the cutting point between the plane and.
ray planeIntersect (const plane &) const
Return the cutting line between this plane and another.
point planePlaneIntersect (const plane &, const plane &) const
Return the cutting point between this plane and two other planes.
side sideOfPlane (const point &p) const
Return the side of the plane that the point is on.
point mirror (const point &p) const
Mirror the supplied point in the plane. Return the mirrored point.
void writeDict (Ostream &) const
Write to dictionary.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from plane
enum side { NORMAL, FLIP }
Side of the plane.
Static Public Member Functions inherited from searchableSurface
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Return a reference to the selected searchableSurface.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Searching on (infinite) plane. See plane.H.
Source files
searchablePlane.H
searchablePlane.C
Definition at line 51 of file searchablePlane.H.
Constructor & Destructor Documentation
searchablePlane() [1/2]
searchablePlane (const IOobject & io, const point & basePoint, const vector & normal)
Construct from components.
Definition at line 92 of file searchablePlane.C.
searchablePlane() [2/2]
searchablePlane (const IOobject & io, const dictionary & dict)
Construct from dictionary (used by searchableSurface)
Definition at line 106 of file searchablePlane.C.
~searchablePlane()
~searchablePlane () virtual
Destructor.
Definition at line 120 of file searchablePlane.C.
Member Function Documentation
TypeName()
TypeName ("searchablePlane")
Runtime type information.
regions()
const Foam::wordList & regions () const virtual
Names of regions.
Implements searchableSurface.
Definition at line 126 of file searchablePlane.C.
References searchablePlane::boundingSpheres(), and List< T >::setSize().
hasVolumeType()
virtual bool hasVolumeType () const inline virtual
Whether supports volume type below.
Implements searchableSurface.
Definition at line 113 of file searchablePlane.H.
size()
virtual label size () const inline virtual
Range of local indices that can be returned.
Implements searchableSurface.
Definition at line 119 of file searchablePlane.H.
References searchablePlane::boundingSpheres(), searchablePlane::coordinates(), and plane::refPoint().
coordinates()
virtual tmp<pointField> coordinates () const inline virtual
Get representative set of element coordinates.
Usually the element centres (should be of length size()).
Implements searchableSurface.
Definition at line 126 of file searchablePlane.H.
Referenced by searchablePlane::points(), and searchablePlane::size().
boundingSpheres()
void boundingSpheres (pointField & centres, scalarField & radiusSqr) const virtual
Get bounding spheres (centre and radius squared), one per element.
Any point on element is guaranteed to be inside. Note: radius limited to sqr(GREAT)
Implements searchableSurface.
Definition at line 138 of file searchablePlane.C.
References searchablePlane::findNearest(), List< T >::setSize(), and Foam::sqr().
Referenced by searchablePlane::regions(), and searchablePlane::size().
points()
virtual tmp<pointField> points () const inline virtual
Get the points that define the surface.
Implements searchableSurface.
Definition at line 142 of file searchablePlane.H.
References searchablePlane::coordinates().
overlaps()
virtual bool overlaps (const boundBox & bb) const inline virtual
Does any part of the surface overlap the supplied bound box?
Implements searchableSurface.
Definition at line 148 of file searchablePlane.H.
References searchablePlane::findLineAll(), searchablePlane::findLineAny(), searchablePlane::findNearest(), searchablePlane::getNormal(), searchablePlane::getRegion(), searchablePlane::getVolumeType(), and NotImplemented.
findNearest()
void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info) const virtual
Implements searchableSurface.
Definition at line 152 of file searchablePlane.C.
References forAll, Foam::magSqr(), List< T >::setSize(), and List< T >::size().
Referenced by searchablePlane::boundingSpheres(), and searchablePlane::overlaps().
findLine()
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Find first intersection on segment from start to end.
Note: searchableSurfacesQueries expects no intersection to be found if start==end. Is problem?
Implements searchableSurface.
Definition at line 179 of file searchablePlane.C.
References searchablePlane::findLineAny(), forAll, List< T >::setSize(), and List< T >::size().
findLineAny()
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Return any intersection on segment from start to end.
Implements searchableSurface.
Definition at line 195 of file searchablePlane.C.
References searchablePlane::findLineAll().
Referenced by searchablePlane::findLine(), and searchablePlane::overlaps().
findLineAll()
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit >> & info) const virtual
Get all intersections in order from start to end.
Implements searchableSurface.
Definition at line 206 of file searchablePlane.C.
References List< T >::clear(), forAll, searchablePlane::getRegion(), List< T >::setSize(), and List< T >::size().
Referenced by searchablePlane::findLineAny(), and searchablePlane::overlaps().
getRegion()
void getRegion (const List< pointIndexHit > & info, labelList & region) const virtual
From a set of points and indices get the region.
Implements searchableSurface.
Definition at line 232 of file searchablePlane.C.
References searchablePlane::getNormal(), List< T >::setSize(), and List< T >::size().
Referenced by searchablePlane::findLineAll(), and searchablePlane::overlaps().
getNormal()
void getNormal (const List< pointIndexHit > & info, vectorField & normal) const virtual
From a set of points and indices get the normal.
Implements searchableSurface.
Definition at line 243 of file searchablePlane.C.
References searchablePlane::getVolumeType(), List< T >::setSize(), and List< T >::size().
Referenced by searchablePlane::getRegion(), and searchablePlane::overlaps().
getVolumeType()
void getVolumeType (const pointField & points, List< volumeType > & volType) const virtual
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Implements searchableSurface.
Definition at line 254 of file searchablePlane.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by searchablePlane::getNormal(), and searchablePlane::overlaps().
writeData()
bool writeData (Ostream &) const inline virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 212 of file searchablePlane.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurface/searchablePlane.H
src/meshTools/searchableSurface/searchablePlane.C