OpenFOAM: searchableSurfaces Class Reference
searchableSurfaces Class Reference
Container for searchableSurfaces.
Public Member Functions
ClassName ("searchableSurfaces")
searchableSurfaces (const label)
Construct with length specified. Fill later.
searchableSurfaces (const IOobject &, const dictionary &, const bool singleRegionName)
Construct from dictionary and whether to construct names always.
const wordList & names () const
wordList & names ()
const List< wordList > & regionNames () const
List< wordList > & regionNames ()
label findSurfaceID (const word &name) const
Find index of surface. Return -1 if not found.
label findSurfaceRegionID (const word &surfaceName, const word &regionName) const
void findAnyIntersection (const pointField &start, const pointField &end, labelList &surfaces, List< pointIndexHit > &) const
Find any intersection. Return hit point information and.
void findAllIntersections (const pointField &start, const pointField &end, labelListList &surfaces, List< List< pointIndexHit >> &) const
Find all intersections in order from start to end. Returns for.
void findNearestIntersection (const pointField &start, const pointField &end, labelList &surface1, List< pointIndexHit > &hit1, labelList &surface2, List< pointIndexHit > &hit2) const
void findNearest (const pointField &, const scalarField &nearestDistSqr, labelList &surfaces, List< pointIndexHit > &) const
Find nearest. Return -1 (and a miss()) or surface and nearest.
void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, labelList &nearestSurfaces, List< pointIndexHit > &nearestInfo) const
boundBox bounds () const
Calculate bounding box.
pointIndexHit facesIntersection (const scalar initialDistSqr, const scalar convergenceDistSqr, const point &start) const
Calculate point which is on a set of surfaces.
bool checkClosed (const bool report) const
Are all surfaces closed and manifold.
bool checkNormalOrientation (const bool report) const
Are all (triangulated) surfaces consistent normal orientation.
bool checkSizes (const scalar maxRatio, const bool report) const
Are all bounding boxes of similar size.
bool checkIntersection (const scalar tol, const autoPtr< writer< scalar >> &, const bool report) const
Do surfaces self-intersect or intersect others.
bool checkQuality (const scalar minQuality, const bool report) const
Check triangle quality.
label checkTopology (const bool report) const
All topological checks. Return number of failed checks.
label checkGeometry (const scalar maxRatio, const scalar tolerance, const autoPtr< writer< scalar >> &setWriter, const scalar minQuality, const bool report) const
All geometric checks. Return number of failed checks.
void writeStats (const List< wordList > &, Ostream &) const
Write some stats.
const searchableSurface & operator[] (const word &) const
Return const reference to searchableSurface by name.
searchableSurface & operator[] (const word &)
Return reference to searchableSurface by name.
Public Member Functions inherited from PtrList< searchableSurface >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< searchableSurface > &)
Copy constructor.
PtrList (const PtrList< searchableSurface > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< searchableSurface >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< searchableSurface > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< searchableSurface > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (searchableSurface *)
Append an element at the end of the list.
void append (const autoPtr< searchableSurface > &)
void append (const tmp< searchableSurface > &)
void transfer (PtrList< searchableSurface > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< searchableSurface > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< searchableSurface > set (const label, searchableSurface *)
Set element to given T* and return old element (can be nullptr)
autoPtr< searchableSurface > set (const label, const autoPtr< searchableSurface > &)
Set element to given autoPtr<T> and return old element.
autoPtr< searchableSurface > set (const label, const tmp< searchableSurface > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< searchableSurface > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< searchableSurface >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Container for searchableSurfaces.
Source files
searchableSurfaces.H
searchableSurfaces.C
Definition at line 53 of file searchableSurfaces.H.
Constructor & Destructor Documentation
searchableSurfaces() [1/2]
searchableSurfaces (const label size) explicit
Construct with length specified. Fill later.
Definition at line 69 of file searchableSurfaces.C.
searchableSurfaces() [2/2]
searchableSurfaces (const IOobject & io, const dictionary & topDict, const bool singleRegionName)
Construct from dictionary and whether to construct names always.
as surfaceName "_" regionName (singleRegionName false) or for single region surfaces as surfaceName only (singleRegionName true)
Definition at line 170 of file searchableSurfaces.C.
References IOobject::clone(), dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), searchableSurfaces::findSurfaceID(), forAll, forAllConstIter(), dictionary::found(), dictionary::isDict(), dictionary::lookup(), IOobject::name(), searchableSurface::New(), searchableSurfaces::operator[](), dictionary::readIfPresent(), searchableSurface::regions(), PtrList< T >::setSize(), List< T >::setSize(), List< T >::size(), and dictionary::subDict().
Member Function Documentation
ClassName()
ClassName ("searchableSurfaces")
names() [1/2]
const wordList& names () const inline
Definition at line 117 of file searchableSurfaces.H.
Referenced by searchableSurfaces::checkClosed(), searchableSurfaces::checkIntersection(), searchableSurfaces::checkNormalOrientation(), searchableSurfaces::checkQuality(), searchableSurfaces::checkSizes(), shellSurfaces::shellSurfaces(), and searchableSurfaces::writeStats().
names() [2/2]
wordList& names () inline
Definition at line 121 of file searchableSurfaces.H.
regionNames() [1/2]
const List<wordList>& regionNames () const inline
Definition at line 126 of file searchableSurfaces.H.
regionNames() [2/2]
List<wordList>& regionNames () inline
Definition at line 130 of file searchableSurfaces.H.
References searchableSurfaces::bounds(), searchableSurfaces::checkClosed(), searchableSurfaces::checkGeometry(), searchableSurfaces::checkIntersection(), searchableSurfaces::checkNormalOrientation(), searchableSurfaces::checkQuality(), searchableSurfaces::checkSizes(), searchableSurfaces::checkTopology(), UPtrList< T >::end(), searchableSurfaces::facesIntersection(), searchableSurfaces::findAllIntersections(), searchableSurfaces::findAnyIntersection(), searchableSurfaces::findNearest(), searchableSurfaces::findNearestIntersection(), searchableSurfaces::findSurfaceID(), searchableSurfaces::findSurfaceRegionID(), Foam::name(), searchableSurfaces::operator[](), regionName, samples(), and searchableSurfaces::writeStats().
findSurfaceID()
Foam::label findSurfaceID (const word & name) const
Find index of surface. Return -1 if not found.
Definition at line 284 of file searchableSurfaces.C.
References Foam::findIndex(), and searchableSurfaces::findSurfaceRegionID().
Referenced by searchableSurfaces::findSurfaceRegionID(), searchableSurfaces::operator[](), searchableSurfaces::regionNames(), and searchableSurfaces::searchableSurfaces().
findSurfaceRegionID()
Foam::label findSurfaceRegionID (const word & surfaceName, const word & regionName) const
Definition at line 293 of file searchableSurfaces.C.
References searchableSurfaces::findAnyIntersection(), Foam::findIndex(), and searchableSurfaces::findSurfaceID().
Referenced by searchableSurfaces::findSurfaceID(), and searchableSurfaces::regionNames().
findAnyIntersection()
void findAnyIntersection (const pointField & start, const pointField & end, labelList & surfaces, List< pointIndexHit > & hitInfo) const
Find any intersection. Return hit point information and.
surface number. If multiple surfaces hit the first surface is returned, not necessarily the nearest (to start).
Definition at line 306 of file searchableSurfaces.C.
References searchableSurfaces::findAllIntersections(), and searchableSurfacesQueries::findAnyIntersection().
Referenced by searchableSurfaces::findSurfaceRegionID(), NamedEnum< directionType, 3 >::names(), and searchableSurfaces::regionNames().
findAllIntersections()
void findAllIntersections (const pointField & start, const pointField & end, labelListList & surfaces, List< List< pointIndexHit >> & hitInfo) const
Find all intersections in order from start to end. Returns for.
every hit the surface and the hit info.
Definition at line 326 of file searchableSurfaces.C.
References searchableSurfacesQueries::findAllIntersections(), and searchableSurfaces::findNearestIntersection().
Referenced by searchableSurfaces::findAnyIntersection(), and searchableSurfaces::regionNames().
findNearestIntersection()
void findNearestIntersection (const pointField & start, const pointField & end, labelList & surface1, List< pointIndexHit > & hit1, labelList & surface2, List< pointIndexHit > & hit2) const
Definition at line 347 of file searchableSurfaces.C.
References searchableSurfaces::findNearest(), and searchableSurfacesQueries::findNearestIntersection().
Referenced by searchableSurfaces::findAllIntersections(), and searchableSurfaces::regionNames().
findNearest() [1/2]
void findNearest (const pointField & samples, const scalarField & nearestDistSqr, labelList & surfaces, List< pointIndexHit > & nearestInfo) const
Find nearest. Return -1 (and a miss()) or surface and nearest.
point.
Definition at line 371 of file searchableSurfaces.C.
References searchableSurfacesQueries::findNearest().
Referenced by searchableSurfaces::findNearestIntersection(), NamedEnum< directionType, 3 >::names(), and searchableSurfaces::regionNames().
findNearest() [2/2]
void findNearest (const pointField & samples, const scalarField & nearestDistSqr, const labelList & regionIndices, labelList & nearestSurfaces, List< pointIndexHit > & nearestInfo) const
Definition at line 391 of file searchableSurfaces.C.
References searchableSurfacesQueries::findNearest().
bounds()
Foam::boundBox bounds () const
Calculate bounding box.
Definition at line 412 of file searchableSurfaces.C.
References searchableSurfacesQueries::bounds(), and searchableSurfaces::facesIntersection().
Referenced by searchableSurfaces::regionNames().
facesIntersection()
Foam::pointIndexHit facesIntersection (const scalar initialDistSqr, const scalar convergenceDistSqr, const point & start) const
Calculate point which is on a set of surfaces.
Definition at line 423 of file searchableSurfaces.C.
References searchableSurfacesQueries::facesIntersection().
Referenced by searchableSurfaces::bounds(), and searchableSurfaces::regionNames().
checkClosed()
bool checkClosed (const bool report) const
Are all surfaces closed and manifold.
Definition at line 440 of file searchableSurfaces.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), Foam::endl(), forAll, Foam::Info, searchableSurfaces::names(), Foam::nl, searchableSurfaces::operator[](), Foam::returnReduce(), and UPtrList< T >::size().
Referenced by searchableSurfaces::checkTopology(), and searchableSurfaces::regionNames().
checkNormalOrientation()
bool checkNormalOrientation (const bool report) const
Are all (triangulated) surfaces consistent normal orientation.
Definition at line 507 of file searchableSurfaces.C.
References PatchTools::checkOrientation(), searchableSurfaces::checkSizes(), Foam::endl(), forAll, Foam::Info, PatchTools::markZones(), searchableSurfaces::names(), searchableSurfaces::operator[](), Foam::returnReduce(), and List< T >::size().
Referenced by searchableSurfaces::checkTopology(), and searchableSurfaces::regionNames().
checkSizes()
bool checkSizes (const scalar maxRatio, const bool report) const
Are all bounding boxes of similar size.
Definition at line 554 of file searchableSurfaces.C.
References searchableSurface::bounds(), searchableSurfaces::checkIntersection(), Foam::endl(), forAll, Foam::Info, boundBox::mag(), searchableSurfaces::names(), Foam::nl, searchableSurfaces::operator[](), Foam::returnReduce(), and UPtrList< T >::size().
Referenced by searchableSurfaces::checkGeometry(), searchableSurfaces::checkNormalOrientation(), and searchableSurfaces::regionNames().
checkIntersection()
bool checkIntersection (const scalar tol, const autoPtr< writer< scalar >> & setWriter, const bool report) const
Do surfaces self-intersect or intersect others.
Definition at line 602 of file searchableSurfaces.C.
References searchableSurfaces::checkQuality(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), UPtrList< T >::end(), Foam::endl(), searchableSurface::findLineAny(), forAll, Foam::Info, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), Foam::max(), searchableSurfaces::names(), searchableSurfaces::operator[](), IOobject::path(), Foam::returnReduce(), List< T >::size(), triSurfaceSearch::tolerance(), OSstream::write(), and List< T >::xfer().
Referenced by searchableSurfaces::checkGeometry(), searchableSurfaces::checkSizes(), and searchableSurfaces::regionNames().
checkQuality()
bool checkQuality (const scalar minQuality, const bool report) const
Check triangle quality.
Definition at line 744 of file searchableSurfaces.C.
References searchableSurfaces::checkTopology(), Foam::endl(), f(), forAll, Foam::Info, searchableSurfaces::names(), searchableSurfaces::operator[](), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), and Foam::returnReduce().
Referenced by searchableSurfaces::checkGeometry(), searchableSurfaces::checkIntersection(), and searchableSurfaces::regionNames().
checkTopology()
Foam::label checkTopology (const bool report) const
All topological checks. Return number of failed checks.
Definition at line 809 of file searchableSurfaces.C.
References searchableSurfaces::checkClosed(), searchableSurfaces::checkGeometry(), and searchableSurfaces::checkNormalOrientation().
Referenced by searchableSurfaces::checkQuality(), and searchableSurfaces::regionNames().
checkGeometry()
Foam::label checkGeometry (const scalar maxRatio, const scalar tolerance, const autoPtr< writer< scalar >> & setWriter, const scalar minQuality, const bool report) const
All geometric checks. Return number of failed checks.
Definition at line 829 of file searchableSurfaces.C.
References searchableSurfaces::checkIntersection(), searchableSurfaces::checkQuality(), searchableSurfaces::checkSizes(), and searchableSurfaces::writeStats().
Referenced by searchableSurfaces::checkTopology(), and searchableSurfaces::regionNames().
writeStats()
void writeStats (const List< wordList > & patchTypes, Ostream & os) const
Write some stats.
Definition at line 859 of file searchableSurfaces.C.
References searchableSurface::bounds(), Foam::endl(), forAll, searchableSurface::globalSize(), searchableSurface::hasVolumeType(), Foam::Info, searchableSurfaces::names(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), Foam::nl, UPtrList< T >::operator, searchableSurfaces::operator[](), triSurfaceMesh::points(), s(), List< T >::size(), and UPtrList< T >::size().
Referenced by searchableSurfaces::checkGeometry(), and searchableSurfaces::regionNames().
operator[]() [1/2]
const Foam::searchableSurface & operator[] (const word & surfName) const
Return const reference to searchableSurface by name.
Definition at line 904 of file searchableSurfaces.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, searchableSurfaces::findSurfaceID(), Foam::nl, and UPtrList< T >::operator.
Referenced by searchableSurfaces::checkClosed(), searchableSurfaces::checkIntersection(), searchableSurfaces::checkNormalOrientation(), searchableSurfaces::checkQuality(), searchableSurfaces::checkSizes(), searchableSurfaces::operator[](), searchableSurfaces::regionNames(), searchableSurfaces::searchableSurfaces(), and searchableSurfaces::writeStats().
operator[]() [2/2]
Foam::searchableSurface & operator[] (const word & surfName)
Return reference to searchableSurface by name.
Definition at line 923 of file searchableSurfaces.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, searchableSurfaces::findSurfaceID(), Foam::nl, and searchableSurfaces::operator[]().
The documentation for this class was generated from the following files:
src/meshTools/searchableSurface/searchableSurfaces.H
src/meshTools/searchableSurface/searchableSurfaces.C