OpenFOAM: regionCoupledBase Class Reference
regionCoupledBase Class Reference abstract
Base class with common functinality for regionCoupled polyPatch. It includes AMI.
Public Member Functions
TypeName ("regionCoupledBase")
Runtime type information.
regionCoupledBase (const polyPatch &)
Construct from patch.
regionCoupledBase (const polyPatch &, const dictionary &)
Construct from dictionary.
regionCoupledBase (const polyPatch &, const regionCoupledBase &)
Construct as copy, resetting patch.
virtual ~regionCoupledBase ()
Destructor.
const word & nbrPatchName () const
Neighbour patch name.
const word & nbrRegionName () const
Neighbour region name.
bool sameRegion () const
Cached sampleRegion != mesh.name()
label neighbPatchID () const
Neighbour patch ID.
bool owner () const
Does this side own the patch?
const regionCoupledBase & neighbPatch () const
Return a reference to the neighbour patch.
const autoPtr< searchableSurface > & surfPtr () const
Return a reference to the projection surface.
const AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fld) const
Interpolate field.
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type >> &tFld) const
Interpolate tmp field.
template<class Type , class BinaryOp >
void interpolate (const UList< Type > &fld, const BinaryOp &bop, List< Type > &result) const
Low-level interpolate List.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
virtual const word & regionCoupleType () const =0
Return the type.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &fld) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const tmp< Field< Type >> &tFld) const
Protected Member Functions
virtual void clearGeom ()
Clear geometry.
Detailed Description
Base class with common functinality for regionCoupled polyPatch. It includes AMI.
Source files
regionCoupledBase.H
regionCoupledBase.C
Definition at line 51 of file regionCoupledBase.H.
Constructor & Destructor Documentation
regionCoupledBase() [1/3]
regionCoupledBase (const polyPatch & pp)
Construct from patch.
Definition at line 126 of file regionCoupledBase.C.
Referenced by regionCoupledBase::clearGeom(), and regionCoupledBase::regionCoupledBase().
regionCoupledBase() [2/3]
regionCoupledBase (const polyPatch & pp, const dictionary & dict)
Construct from dictionary.
Definition at line 143 of file regionCoupledBase.C.
References regionCoupledBase::regionCoupledBase().
regionCoupledBase() [3/3]
regionCoupledBase (const polyPatch & pp, const regionCoupledBase & mpb)
Construct as copy, resetting patch.
Definition at line 161 of file regionCoupledBase.C.
~regionCoupledBase()
~regionCoupledBase () virtual
Destructor.
Definition at line 180 of file regionCoupledBase.C.
Member Function Documentation
clearGeom()
void clearGeom () protected virtual
Clear geometry.
Definition at line 116 of file regionCoupledBase.C.
References regionCoupledBase::regionCoupledBase().
Referenced by regionCoupledWallPolyPatch::calcGeometry(), regionCoupledPolyPatch::movePoints(), regionCoupledWallPolyPatch::movePoints(), regionCoupledPolyPatch::updateMesh(), regionCoupledWallPolyPatch::updateMesh(), regionCoupledPolyPatch::~regionCoupledPolyPatch(), and regionCoupledWallPolyPatch::~regionCoupledWallPolyPatch().
TypeName()
TypeName ("regionCoupledBase")
Runtime type information.
nbrPatchName()
const word& nbrPatchName () const inline
Neighbour patch name.
Definition at line 126 of file regionCoupledBase.H.
Referenced by regionCoupledBase::neighbPatchID().
nbrRegionName()
const word& nbrRegionName () const inline
Neighbour region name.
Definition at line 132 of file regionCoupledBase.H.
Referenced by regionCoupledBaseFvPatch::nbrFvMesh(), and regionCoupledBaseFvPatch::nbrMesh().
sameRegion()
bool sameRegion () const inline
Cached sampleRegion != mesh.name()
Definition at line 138 of file regionCoupledBase.H.
References regionCoupledBase::AMI(), Foam::faceMap(), fld(), regionCoupledBase::interpolate(), regionCoupledBase::neighbPatch(), regionCoupledBase::neighbPatchID(), regionCoupledBase::order(), regionCoupledBase::owner(), regionCoupledBase::regionCoupleType(), regionCoupledBase::surfPtr(), and regionCoupledBase::write().
Referenced by regionCoupledBaseFvPatch::sameRegion().
neighbPatchID()
Foam::label neighbPatchID () const
Neighbour patch ID.
Definition at line 186 of file regionCoupledBase.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::findPatchID(), objectRegistry::lookupObject(), mesh, polyBoundaryMesh::mesh(), polyBoundaryMesh::names(), regionCoupledBase::nbrPatchName(), Foam::nl, objectRegistry::time(), and WarningInFunction.
Referenced by regionCoupledBaseFvPatch::neighbFvPatch(), regionCoupledBaseFvPatch::neighbPatch(), regionCoupledBaseFvPatch::neighbPatchID(), and regionCoupledBase::sameRegion().
owner()
bool owner () const
Does this side own the patch?
Definition at line 237 of file regionCoupledBase.C.
References regionCoupledBase::surfPtr().
Referenced by regionCoupledBaseFvPatch::owner(), and regionCoupledBase::sameRegion().
neighbPatch()
const Foam::regionCoupledBase & neighbPatch () const
Return a reference to the neighbour patch.
Definition at line 301 of file regionCoupledBase.C.
References polyMesh::boundaryMesh(), objectRegistry::lookupObject(), mesh, polyBoundaryMesh::mesh(), regionCoupledBase::order(), and objectRegistry::time().
Referenced by regionCoupledBase::sameRegion().
surfPtr()
const Foam::autoPtr< Foam::searchableSurface > & surfPtr () const
Return a reference to the projection surface.
Definition at line 251 of file regionCoupledBase.C.
References polyMesh::boundaryMesh(), TimePaths::constant(), mesh, polyBoundaryMesh::mesh(), IOobject::MUST_READ, searchableSurface::New(), IOobject::NO_WRITE, and objectRegistry::time().
Referenced by regionCoupledBase::owner(), and regionCoupledBase::sameRegion().
AMI()
const Foam::AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
Definition at line 282 of file regionCoupledBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by regionCoupledBaseFvPatch::AMI(), and regionCoupledBase::sameRegion().
interpolate() [1/5]
tmp<Field<Type> > interpolate (const Field< Type > & fld) const
Interpolate field.
Referenced by regionCoupledBase::interpolate(), and regionCoupledBase::sameRegion().
interpolate() [2/5]
tmp<Field<Type> > interpolate (const tmp< Field< Type >> & tFld) const
Interpolate tmp field.
interpolate() [3/5]
void interpolate (const UList< Type > & fld, const BinaryOp & bop, List< Type > & result) const
Low-level interpolate List.
Definition at line 64 of file regionCoupledBaseTemplates.C.
order()
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Definition at line 315 of file regionCoupledBase.C.
References List< T >::setSize().
Referenced by regionCoupledBase::neighbPatch(), and regionCoupledBase::sameRegion().
regionCoupleType()
virtual const word& regionCoupleType () const pure virtual
Return the type.
Implemented in regionCoupledPolyPatch, and regionCoupledWallPolyPatch.
Referenced by regionCoupledBaseFvPatch::regionCoupleType(), and regionCoupledBase::sameRegion().
write()
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented in regionCoupledPolyPatch, and regionCoupledWallPolyPatch.
Definition at line 333 of file regionCoupledBase.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by regionCoupledBase::sameRegion(), regionCoupledWallPolyPatch::write(), and regionCoupledPolyPatch::write().
interpolate() [4/5]
Foam::tmp<Foam::Field<Type> > interpolate (const Field< Type > & fld) const
Definition at line 30 of file regionCoupledBaseTemplates.C.
References regionCoupledBase::interpolate().
interpolate() [5/5]
Foam::tmp<Foam::Field<Type> > interpolate (const tmp< Field< Type >> & tFld) const
Definition at line 47 of file regionCoupledBaseTemplates.C.
References regionCoupledBase::interpolate().
The documentation for this class was generated from the following files:
src/meshTools/regionCoupled/patches/regionCoupledPolyPatch/regionCoupledBase.H
src/meshTools/regionCoupled/patches/regionCoupledPolyPatch/regionCoupledBase.C
src/meshTools/regionCoupled/patches/regionCoupledPolyPatch/regionCoupledBaseTemplates.C