OpenFOAM: searchableSurface Class Reference
searchableSurface Class Reference abstract
Base class of (analytical or triangulated) surface. Encapsulates all the search routines. WIP.
Classes
class iNew
Class used for the read-construction of.
Public Member Functions
TypeName ("searchableSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr< searchableSurface > clone () const
Clone.
virtual ~searchableSurface ()
Destructor.
const boundBox & bounds () const
Return const reference to boundBox.
boundBox & bounds ()
Return non-const access to the boundBox to allow it to be set.
virtual const wordList & regions () const =0
Names of regions.
virtual bool hasVolumeType () const =0
Whether supports volume type below.
virtual label size () const =0
Range of local indices that can be returned.
virtual label globalSize () const
Range of global indices that can be returned.
virtual tmp< pointField > coordinates () const =0
Get representative set of element coordinates.
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const =0
Get bounding spheres (centre and radius squared), one per element.
virtual tmp< pointField > points () const =0
Get the points that define the surface.
virtual bool overlaps (const boundBox &bb) const =0
Does any part of the surface overlap the supplied bound box?
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &) const =0
virtual void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
Find the nearest locations for the supplied points to a.
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const =0
Find first intersection on segment from start to end.
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const =0
Return any intersection on segment from start to end.
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit >> &) const =0
Get all intersections in order from start to end.
virtual void getRegion (const List< pointIndexHit > &, labelList &region) const =0
From a set of points and indices get the region.
virtual void getNormal (const List< pointIndexHit > &, vectorField &normal) const =0
From a set of points and indices get the normal.
virtual void getVolumeType (const pointField &, List< volumeType > &) const =0
Determine type (inside/outside) for point. unknown if.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &, vectorField &normal, labelList &region) const
Find nearest, normal and region. Can be overridden with.
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
Set bounds of surface. Bounds currently set as list of.
virtual void setField (const labelList &values)
WIP. Store element-wise field.
virtual void getField (const List< pointIndexHit > &, labelList &values) const
WIP. From a set of hits (points and.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeData (Ostream &) const =0
Pure virtual writaData function.
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Return a reference to the selected searchableSurface.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Base class of (analytical or triangulated) surface. Encapsulates all the search routines. WIP.
Information returned is usually a pointIndexHit:
bool : was intersection/nearest found?
point : intersection point or nearest point
index : unique index on surface (e.g. triangle for triSurfaceMesh)
Source files
searchableSurface.H
searchableSurface.C
Definition at line 66 of file searchableSurface.H.
Constructor & Destructor Documentation
searchableSurface()
searchableSurface (const IOobject & io)
Definition at line 65 of file searchableSurface.C.
~searchableSurface()
~searchableSurface () virtual
Destructor.
Definition at line 73 of file searchableSurface.C.
References searchableSurface::findNearest().
Referenced by searchableSurface::clone().
Member Function Documentation
TypeName()
TypeName ("searchableSurface")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , searchableSurface , dict , (const IOobject &io, const dictionary &dict) , (io, dict))
clone()
virtual autoPtr<searchableSurface> clone () const inline virtual
Clone.
Definition at line 137 of file searchableSurface.H.
References searchableSurface::New(), NotImplemented, and searchableSurface::~searchableSurface().
New()
Foam::autoPtr< Foam::searchableSurface > New (const word & surfaceType, const IOobject & io, const dictionary & dict) static
Return a reference to the selected searchableSurface.
Definition at line 40 of file searchableSurface.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by searchableSurface::clone(), searchableSurface::iNew::operator()(), searchableSurfaces::searchableSurfaces(), regionCoupledBase::surfPtr(), cyclicAMIPolyPatch::surfPtr(), and mappedPatchBase::surfPtr().
bounds() [1/2]
const boundBox& bounds () const inline
Return const reference to boundBox.
Definition at line 162 of file searchableSurface.H.
Referenced by searchableSurfacesQueries::bounds(), searchableSurfaces::checkSizes(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), triSurfaceMesh::triSurfaceMesh(), and searchableSurfaces::writeStats().
bounds() [2/2]
boundBox& bounds () inline
Return non-const access to the boundBox to allow it to be set.
Definition at line 168 of file searchableSurface.H.
References searchableSurface::hasVolumeType(), searchableSurface::regions(), and searchableSurface::size().
regions()
virtual const wordList& regions () const pure virtual
Names of regions.
Implemented in triSurfaceMesh, searchableSurfaceCollection, searchableCylinder, searchablePlate, searchableSurfaceWithGaps, searchableDisk, searchableSphere, searchableBox, and searchablePlane.
Referenced by searchableSurface::bounds(), refinementSurfaces::findHigherIntersection(), refinementSurfaces::refinementSurfaces(), searchableSurfaceWithGaps::regions(), searchableSurfaces::searchableSurfaces(), and refinementSurfaces::setMinLevelFields().
hasVolumeType()
virtual bool hasVolumeType () const pure virtual
Whether supports volume type below.
Implemented in distributedTriSurfaceMesh, triSurfaceMesh, searchableSurfaceCollection, searchableCylinder, searchableSurfaceWithGaps, searchablePlate, searchableDisk, searchableSphere, searchableBox, searchablePlane, and closedTriSurfaceMesh.
Referenced by searchableSurface::bounds(), refinementSurfaces::findInside(), searchableSurfaceWithGaps::hasVolumeType(), surfaceZonesInfo::surfaceZonesInfo(), and searchableSurfaces::writeStats().
size()
virtual label size () const pure virtual
Range of local indices that can be returned.
Implemented in triSurfaceMesh, searchableSurfaceCollection, searchableCylinder, searchableSurfaceWithGaps, searchablePlate, searchableDisk, searchableSphere, searchableBox, and searchablePlane.
Referenced by searchableSurface::bounds(), searchableSurface::globalSize(), and searchableSurfaceWithGaps::size().
globalSize()
virtual label globalSize () const inline virtual
Range of global indices that can be returned.
Reimplemented in distributedTriSurfaceMesh.
Definition at line 183 of file searchableSurface.H.
References searchableSurface::boundingSpheres(), searchableSurface::coordinates(), searchableSurface::findNearest(), searchableSurface::overlaps(), searchableSurface::points(), and searchableSurface::size().
Referenced by refinementSurfaces::setMinLevelFields(), and searchableSurfaces::writeStats().
coordinates()
virtual tmp<pointField> coordinates () const pure virtual
Get representative set of element coordinates.
Usually the element centres (should be of length size()).
Implemented in triSurfaceMesh, searchableSurfaceCollection, searchableCylinder, searchableSurfaceWithGaps, searchablePlate, searchableDisk, searchableSphere, searchableBox, and searchablePlane.
Referenced by searchableSurface::globalSize(), and searchableSurfaceWithGaps::size().
boundingSpheres()
virtual void boundingSpheres (pointField & centres, scalarField & radiusSqr) const pure virtual
Get bounding spheres (centre and radius squared), one per element.
Any point on element is guaranteed to be inside.
Implemented in triSurfaceMesh, searchableSurfaceCollection, searchableCylinder, searchableSurfaceWithGaps, searchablePlate, searchableDisk, searchableSphere, searchableBox, and searchablePlane.
Referenced by searchableSurfaceWithGaps::boundingSpheres(), searchableSurface::globalSize(), and refinementSurfaces::setMinLevelFields().
points()
virtual tmp<pointField> points () const pure virtual
Get the points that define the surface.
Implemented in triSurfaceMesh, searchableSurfaceCollection, searchableSurfaceWithGaps, searchableCylinder, searchablePlate, searchableDisk, searchableSphere, searchableBox, and searchablePlane.
Referenced by searchablePlateFeatures::features(), searchableSurface::globalSize(), and searchableSurfaceWithGaps::points().
overlaps()
virtual bool overlaps (const boundBox & bb) const pure virtual
Does any part of the surface overlap the supplied bound box?
Implemented in triSurfaceMesh, searchableSurfaceCollection, searchableSurfaceWithGaps, searchableCylinder, searchableDisk, searchablePlate, searchableSphere, searchablePlane, and searchableBox.
Referenced by searchableSurface::globalSize(), and searchableSurfaceWithGaps::points().
findNearest() [1/3]
virtual void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > &) const pure virtual
Implemented in distributedTriSurfaceMesh, searchableBox, triSurfaceMesh, searchableSurfaceCollection, searchableSurfaceWithGaps, searchableCylinder, searchableDisk, searchablePlate, searchableSphere, and searchablePlane.
Referenced by searchableSurfaceWithGaps::findNearest(), searchableSurface::findNearest(), searchableSurface::globalSize(), refinementSurfaces::setMinLevelFields(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), and searchableSurface::~searchableSurface().
findNearest() [2/3]
virtual void findNearest (const pointField & samples, const scalarField & nearestDistSqr, const labelList & regionIndices, List< pointIndexHit > & info) const inline virtual
Find the nearest locations for the supplied points to a.
particular region in the searchable surface.
Reimplemented in triSurfaceMesh.
Definition at line 273 of file searchableSurface.H.
References searchableSurface::distribute(), searchableSurface::findLine(), searchableSurface::findLineAll(), searchableSurface::findLineAny(), searchableSurface::findNearest(), searchableSurface::getNormal(), searchableSurface::getRegion(), and searchableSurface::getVolumeType().
findLine()
virtual void findLine (const pointField & start, const pointField & end, List< pointIndexHit > &) const pure virtual
Find first intersection on segment from start to end.
Note: searchableSurfacesQueries expects no intersection to be found if start==end. Is problem?
Implemented in distributedTriSurfaceMesh, triSurfaceMesh, searchableBox, searchableSurfaceCollection, searchableSurfaceWithGaps, searchableCylinder, searchableDisk, searchablePlate, searchableSphere, and searchablePlane.
Referenced by searchableSurface::findNearest(), and refinementSurfaces::findNearestIntersection().
findLineAny()
virtual void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > &) const pure virtual
Return any intersection on segment from start to end.
Implemented in distributedTriSurfaceMesh, triSurfaceMesh, searchableBox, searchableSurfaceCollection, searchableSurfaceWithGaps, searchableCylinder, searchableDisk, searchablePlate, searchableSphere, and searchablePlane.
Referenced by searchableSurfaces::checkIntersection(), refinementSurfaces::findHigherIntersection(), and searchableSurface::findNearest().
findLineAll()
virtual void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit >> &) const pure virtual
Get all intersections in order from start to end.
Implemented in distributedTriSurfaceMesh, triSurfaceMesh, searchableBox, searchableSurfaceCollection, searchableSurfaceWithGaps, searchableCylinder, searchableDisk, searchablePlate, searchableSphere, and searchablePlane.
Referenced by refinementSurfaces::findAllHigherIntersections(), and searchableSurface::findNearest().
getRegion()
virtual void getRegion (const List< pointIndexHit > & , labelList & region) const pure virtual
From a set of points and indices get the region.
Implemented in distributedTriSurfaceMesh, triSurfaceMesh, searchableBox, searchableSurfaceCollection, searchableSurfaceWithGaps, searchableCylinder, searchableDisk, searchablePlate, searchableSphere, and searchablePlane.
Referenced by refinementSurfaces::findAllHigherIntersections(), searchableSurface::findNearest(), refinementSurfaces::findNearestIntersection(), searchableSurfaceWithGaps::getRegion(), and refinementSurfaces::setMinLevelFields().
getNormal()
virtual void getNormal (const List< pointIndexHit > & , vectorField & normal) const pure virtual
From a set of points and indices get the normal.
Implemented in distributedTriSurfaceMesh, triSurfaceMesh, searchableBox, searchableSurfaceCollection, searchableSurfaceWithGaps, searchableCylinder, searchableDisk, searchablePlate, searchableSphere, and searchablePlane.
Referenced by searchablePlateFeatures::features(), refinementSurfaces::findAllHigherIntersections(), searchableSurface::findNearest(), refinementSurfaces::findNearestIntersection(), and searchableSurfaceWithGaps::getNormal().
getVolumeType()
virtual void getVolumeType (const pointField & , List< volumeType > &) const pure virtual
Determine type (inside/outside) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Implemented in distributedTriSurfaceMesh, triSurfaceMesh, searchableBox, searchableSurfaceCollection, searchableSurfaceWithGaps, searchableCylinder, searchableDisk, searchablePlate, searchableSphere, and searchablePlane.
Referenced by refinementSurfaces::findInside(), searchableSurface::findNearest(), and searchableSurfaceWithGaps::getVolumeType().
findNearest() [3/3]
void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info, vectorField & normal, labelList & region) const virtual
Find nearest, normal and region. Can be overridden with.
optimised implementation
Definition at line 80 of file searchableSurface.C.
References searchableSurface::findNearest(), searchableSurface::getNormal(), and searchableSurface::getRegion().
distribute()
virtual void distribute (const List< treeBoundBox > & , const bool keepNonLocal, autoPtr< mapDistribute > & faceMap, autoPtr< mapDistribute > & pointMap) inline virtual
Set bounds of surface. Bounds currently set as list of.
bounding boxes. The bounds are hints to the surface as for the range of queries it can expect. faceMap/pointMap can be set if the surface has done any redistribution.
Reimplemented in distributedTriSurfaceMesh, and searchableSurfaceCollection.
Definition at line 350 of file searchableSurface.H.
Referenced by searchableSurface::findNearest().
setField()
virtual void setField (const labelList & values) inline virtual
WIP. Store element-wise field.
Reimplemented in searchableSurfaceWithGaps, searchableSurfaceCollection, and triSurfaceMesh.
Definition at line 359 of file searchableSurface.H.
References List< T >::clear(), and searchableSurface::getField().
getField()
virtual void getField (const List< pointIndexHit > & , labelList & values) const inline virtual
WIP. From a set of hits (points and.
indices) get the specified field. Misses do not get set. Return empty field if not supported.
Reimplemented in distributedTriSurfaceMesh, searchableSurfaceWithGaps, searchableSurfaceCollection, and triSurfaceMesh.
Definition at line 365 of file searchableSurface.H.
Referenced by refinementSurfaces::findHigherIntersection(), searchableSurfaceWithGaps::getField(), and searchableSurface::setField().
The documentation for this class was generated from the following files:
src/meshTools/searchableSurface/searchableSurface.H
src/meshTools/searchableSurface/searchableSurface.C