OpenFOAM: searchableBox Class Reference
searchableBox Class Reference
Searching on bounding box.
Public Member Functions
TypeName ("searchableBox")
Runtime type information.
searchableBox (const IOobject &io, const treeBoundBox &bb)
Construct from components.
searchableBox (const IOobject &io, const dictionary &dict)
Construct from dictionary (used by searchableSurface)
virtual ~searchableBox ()
Destructor.
virtual const wordList & regions () const
Names of regions.
virtual bool hasVolumeType () const
Whether supports volume type below.
virtual label size () const
Range of local indices that can be returned.
virtual tmp< pointField > coordinates () const
Get representative set of element coordinates.
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const
Get bounding spheres (centre and radius squared), one per element.
virtual tmp< pointField > points () const
Get the points that define the surface.
virtual bool overlaps (const boundBox &bb) const
Does any part of the surface overlap the supplied bound box?
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
Calculate nearest point on surface.
pointIndexHit findNearestOnEdge (const point &sample, const scalar nearestDistSqr) const
Calculate nearest point on edge.
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
Find nearest to segment.
pointIndexHit findLine (const point &start, const point &end) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point &start, const point &end) const
Find any intersection of line between start and end.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &) const
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Find first intersection on segment from start to end.
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Return any intersection on segment from start to end.
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit >> &) const
Get all intersections in order from start to end.
virtual void getRegion (const List< pointIndexHit > &, labelList &region) const
From a set of points and indices get the region.
virtual void getNormal (const List< pointIndexHit > &, vectorField &normal) const
From a set of points and indices get the normal.
virtual void getVolumeType (const pointField &, List< volumeType > &) const
Determine type (inside/outside/mixed) for point. unknown if.
bool writeData (Ostream &) const
Pure virtual writaData function.
Public Member Functions inherited from searchableSurface
TypeName ("searchableSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr< searchableSurface > clone () const
Clone.
virtual ~searchableSurface ()
Destructor.
const boundBox & bounds () const
Return const reference to boundBox.
boundBox & bounds ()
Return non-const access to the boundBox to allow it to be set.
virtual label globalSize () const
Range of global indices that can be returned.
virtual void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
Find the nearest locations for the supplied points to a.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &, vectorField &normal, labelList &region) const
Find nearest, normal and region. Can be overridden with.
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
Set bounds of surface. Bounds currently set as list of.
virtual void setField (const labelList &values)
WIP. Store element-wise field.
virtual void getField (const List< pointIndexHit > &, labelList &values) const
WIP. From a set of hits (points and.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from treeBoundBox
treeBoundBox ()
Construct null setting points to zero.
treeBoundBox (const boundBox &bb)
Construct from a boundBox.
treeBoundBox (const point &min, const point &max)
Construct from components.
treeBoundBox (const UList< point > &)
Construct as the bounding box of the given pointField.
treeBoundBox (const UList< point > &, const labelUList &indices)
Construct as subset of points.
template<unsigned Size>
treeBoundBox (const UList< point > &, const FixedList< label, Size > &indices)
Construct as subset of points.
treeBoundBox (Istream &)
Construct from Istream.
scalar typDim () const
Typical dimension length,height,width.
tmp< pointField > points () const
Vertex coordinates. In octant coding.
point corner (const direction) const
Corner point given octant.
treeBoundBox subBbox (const direction) const
Sub box given by octant number. Midpoint calculated.
treeBoundBox subBbox (const point &mid, const direction) const
Sub box given by octant number. Midpoint provided.
direction subOctant (const point &pt) const
Returns octant number given point and the calculated midpoint.
direction subOctant (const point &pt, bool &onEdge) const
Returns octant number given point and the calculated midpoint.
void searchOrder (const point &pt, FixedList< direction, 8 > &octantOrder) const
Calculates optimal order to look for nearest to point.
bool intersects (const point &overallStart, const vector &overallVec, const point &start, const point &end, point &pt, direction &ptBits) const
Intersects segment; set point to intersection position and face,.
bool intersects (const point &start, const point &end, point &pt) const
Like above but does not return faces point is on.
bool contains (const vector &dir, const point &) const
Contains point (inside or on edge) and moving in direction.
direction faceBits (const point &) const
Code position of point on bounding box faces.
direction posBits (const point &) const
Position of point relative to bounding box.
void calcExtremities (const point &pt, point &nearest, point &furthest) const
Calculate nearest and furthest (to point) vertex coords of.
scalar maxDist (const point &) const
Returns distance point to furthest away corner.
label distanceCmp (const point &, const treeBoundBox &other) const
Compare distance to point with other bounding box.
treeBoundBox extend (Random &, const scalar s) const
Return slightly wider bounding box.
Public Member Functions inherited from boundBox
boundBox ()
Construct null, setting points to zero.
boundBox (const point &min, const point &max)
Construct from components.
boundBox (const UList< point > &, const bool doReduce=true)
Construct as the bounding box of the given points.
boundBox (const tmp< pointField > &, const bool doReduce=true)
Construct as the bounding box of the given temporary pointField.
boundBox (const UList< point > &, const labelUList &indices, const bool doReduce=true)
Construct bounding box as subset of the pointField.
template<unsigned Size>
boundBox (const UList< point > &, const FixedList< label, Size > &indices, const bool doReduce=true)
Construct bounding box as subset of the pointField.
boundBox (Istream &)
Construct from Istream.
const point & min () const
Minimum describing the bounding box.
const point & max () const
Maximum describing the bounding box.
point & min ()
Minimum describing the bounding box, non-const access.
point & max ()
Maximum describing the bounding box, non-const access.
point midpoint () const
The midpoint of the bounding box.
vector span () const
The bounding box span (from minimum to maximum)
scalar mag () const
The magnitude of the bounding box span.
scalar volume () const
The volume of the bound box.
scalar minDim () const
Smallest length/height/width dimension.
scalar maxDim () const
Largest length/height/width dimension.
scalar avgDim () const
Average length/height/width dimension.
tmp< pointField > points () const
Return corner points in an order corresponding to a 'hex' cell.
void inflate (const scalar s)
Inflate box by factor*mag(span) in all dimensions.
bool overlaps (const boundBox &) const
Overlaps/touches boundingBox?
bool overlaps (const point &, const scalar radiusSqr) const
Overlaps boundingSphere (centre + sqr(radius))?
bool contains (const point &) const
Contains point? (inside or on edge)
bool contains (const boundBox &) const
Fully contains other boundingBox?
bool containsInside (const point &) const
Contains point? (inside only)
bool contains (const UList< point > &) const
Contains all of the points? (inside or on edge)
bool contains (const UList< point > &, const labelUList &indices) const
Contains all of the points? (inside or on edge)
template<unsigned Size>
bool contains (const UList< point > &, const FixedList< label, Size > &indices) const
Contains all of the points? (inside or on edge)
bool containsAny (const UList< point > &) const
Contains any of the points? (inside or on edge)
bool containsAny (const UList< point > &, const labelUList &indices) const
Contains any of the points? (inside or on edge)
template<unsigned Size>
bool containsAny (const UList< point > &, const FixedList< label, Size > &indices) const
Contains any of the points? (inside or on edge)
point nearest (const point &) const
Return the nearest point on the boundBox to the supplied point.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from treeBoundBox
enum octantBit { RIGHTHALF = 0x1 << 0, TOPHALF = 0x1 << 1, FRONTHALF = 0x1 << 2 }
Bits used for octant/point coding.
enum faceId {
LEFT = 0, RIGHT = 1, BOTTOM = 2, TOP = 3,
BACK = 4, FRONT = 5
}
Face codes.
enum faceBit {
NOFACE = 0, LEFTBIT = 0x1 << LEFT, RIGHTBIT = 0x1 << RIGHT, BOTTOMBIT = 0x1 << BOTTOM,
TOPBIT = 0x1 << TOP, BACKBIT = 0x1 << BACK, FRONTBIT = 0x1 << FRONT
}
Bits used for face coding.
enum edgeId {
E01 = 0, E13 = 1, E23 = 2, E02 = 3,
E45 = 4, E57 = 5, E67 = 6, E46 = 7,
E04 = 8, E15 = 9, E37 = 10, E26 = 11
}
Edges codes.
Static Public Member Functions inherited from searchableSurface
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Return a reference to the selected searchableSurface.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from treeBoundBox
static direction subOctant (const point &mid, const point &pt)
Returns octant number given point and midpoint.
static direction subOctant (const point &mid, const point &pt, bool &onEdge)
Returns octant number given point and midpoint.
static direction subOctant (const point &mid, const vector &dir, const point &pt, bool &onEdge)
Returns octant number given intersection and midpoint.
Static Public Member Functions inherited from boundBox
static faceList faces ()
Return faces with correct point order.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from treeBoundBox
static const scalar great
The great value used for greatBox and invertedBox.
static const treeBoundBox greatBox
As per boundBox::greatBox, but with GREAT instead of VGREAT.
static const treeBoundBox invertedBox
As per boundBox::invertedBox, but with GREAT instead of VGREAT.
static const faceList faces
Face to point addressing.
static const edgeList edges
Edge to point addressing.
static const FixedList< vector, 6 > faceNormals
Per face the unit normal.
Static Public Attributes inherited from boundBox
static const scalar great
The great value used for greatBox and invertedBox.
static const boundBox greatBox
A very large boundBox: min/max == -/+ VGREAT.
static const boundBox invertedBox
A very large inverted boundBox: min/max == +/- VGREAT.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Searching on bounding box.
Source files
searchableBox.H
searchableBox.C
Definition at line 51 of file searchableBox.H.
Constructor & Destructor Documentation
searchableBox() [1/2]
searchableBox (const IOobject & io, const treeBoundBox & bb)
Construct from components.
Definition at line 165 of file searchableBox.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
searchableBox() [2/2]
searchableBox (const IOobject & io, const dictionary & dict)
Construct from dictionary (used by searchableSurface)
Definition at line 185 of file searchableBox.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
~searchableBox()
~searchableBox () virtual
Destructor.
Definition at line 206 of file searchableBox.C.
Member Function Documentation
TypeName()
TypeName ("searchableBox")
Runtime type information.
regions()
const Foam::wordList & regions () const virtual
Names of regions.
Implements searchableSurface.
Definition at line 212 of file searchableBox.C.
References List< T >::setSize().
hasVolumeType()
virtual bool hasVolumeType () const inline virtual
Whether supports volume type below.
Implements searchableSurface.
Definition at line 119 of file searchableBox.H.
size()
virtual label size () const inline virtual
Range of local indices that can be returned.
Implements searchableSurface.
Definition at line 125 of file searchableBox.H.
References searchableBox::boundingSpheres(), searchableBox::coordinates(), and searchableBox::points().
coordinates()
Foam::tmp< Foam::pointField > coordinates () const virtual
Get representative set of element coordinates.
Usually the element centres (should be of length size()).
Implements searchableSurface.
Definition at line 223 of file searchableBox.C.
References searchableBox::boundingSpheres(), boundBox::faces(), forAll, treeBoundBox::points(), and tmp< T >::ref().
Referenced by searchableBox::size().
boundingSpheres()
void boundingSpheres (pointField & centres, scalarField & radiusSqr) const virtual
Get bounding spheres (centre and radius squared), one per element.
Any point on element is guaranteed to be inside.
Implements searchableSurface.
Definition at line 241 of file searchableBox.C.
References face::centre(), f(), boundBox::faces(), forAll, Foam::magSqr(), Foam::max(), treeBoundBox::points(), List< T >::setSize(), and Foam::sqr().
Referenced by searchableBox::coordinates(), and searchableBox::size().
points()
Foam::tmp< Foam::pointField > points () const virtual
Get the points that define the surface.
Implements searchableSurface.
Definition at line 275 of file searchableBox.C.
References treeBoundBox::points().
Referenced by searchableBox::size().
overlaps()
virtual bool overlaps (const boundBox & bb) const inline virtual
Does any part of the surface overlap the supplied bound box?
Implements searchableSurface.
Definition at line 146 of file searchableBox.H.
References searchableBox::findLine(), searchableBox::findLineAll(), searchableBox::findLineAny(), searchableBox::findNearestOnEdge(), searchableBox::getNormal(), searchableBox::getRegion(), searchableBox::getVolumeType(), Foam::ln(), and boundBox::overlaps().
findNearest() [1/3]
Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Calculate nearest point on surface.
Returns
bool : any point found nearer than nearestDistSqr
label: relevant index in surface (=face 0..5)
point: actual nearest point found
Definition at line 282 of file searchableBox.C.
References searchableBox::findNearestOnEdge().
findNearestOnEdge()
Foam::pointIndexHit findNearestOnEdge (const point & sample, const scalar nearestDistSqr) const
Calculate nearest point on edge.
Returns
bool : any point found nearer than nearestDistSqr
label: relevant index in surface(=?)
point: actual nearest point found
Definition at line 292 of file searchableBox.C.
References Foam::cmptMag(), SortableList< T >::indices(), Foam::magSqr(), Foam::max(), Foam::min(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, PointIndexHit< Point >::rawPoint(), PointIndexHit< Point >::setIndex(), PointIndexHit< Point >::setMiss(), and SortableList< T >::sort().
Referenced by searchableBox::findNearest(), and searchableBox::overlaps().
findNearest() [2/3]
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Find nearest to segment.
Returns
bool : any point found?
label: relevant index in shapes (=face 0..5)
point: actual nearest point found sets:
tightest : bounding box
linePoint : corresponding nearest point on line
Definition at line 362 of file searchableBox.C.
References searchableBox::findLine(), and NotImplemented.
findLine() [1/2]
Foam::pointIndexHit findLine (const point & start, const point & end) const
Find nearest intersection of line between start and end.
Definition at line 374 of file searchableBox.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, searchableBox::findLineAny(), PointIndexHit< Point >::index(), Foam::max(), Foam::min(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, PointIndexHit< Point >::rawPoint(), PointIndexHit< Point >::setHit(), and PointIndexHit< Point >::setIndex().
Referenced by searchableBox::findNearest(), and searchableBox::overlaps().
findLineAny() [1/2]
Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Find any intersection of line between start and end.
Definition at line 437 of file searchableBox.C.
Referenced by searchableBox::findLine(), and searchableBox::overlaps().
findNearest() [3/3]
void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info) const virtual
Implements searchableSurface.
Definition at line 447 of file searchableBox.C.
References searchableBox::findLine(), forAll, List< T >::setSize(), and List< T >::size().
findLine() [2/2]
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Find first intersection on segment from start to end.
Note: searchableSurfacesQueries expects no intersection to be found if start==end. Is problem?
Implements searchableSurface.
Definition at line 465 of file searchableBox.C.
References searchableBox::findLineAny(), forAll, List< T >::setSize(), and List< T >::size().
findLineAny() [2/2]
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Return any intersection on segment from start to end.
Implements searchableSurface.
Definition at line 481 of file searchableBox.C.
References searchableBox::findLineAll(), forAll, List< T >::setSize(), and List< T >::size().
findLineAll()
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit >> & info) const virtual
Get all intersections in order from start to end.
Implements searchableSurface.
Definition at line 497 of file searchableBox.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), List< T >::clear(), forAll, searchableBox::getRegion(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), UList< T >::last(), Foam::magSqr(), List< T >::setSize(), List< T >::size(), and List< T >::transfer().
Referenced by searchableBox::findLineAny(), and searchableBox::overlaps().
getRegion()
void getRegion (const List< pointIndexHit > & info, labelList & region) const virtual
From a set of points and indices get the region.
Implements searchableSurface.
Definition at line 565 of file searchableBox.C.
References searchableBox::getNormal(), List< T >::setSize(), and List< T >::size().
Referenced by searchableBox::findLineAll(), and searchableBox::overlaps().
getNormal()
void getNormal (const List< pointIndexHit > & info, vectorField & normal) const virtual
From a set of points and indices get the normal.
Implements searchableSurface.
Definition at line 576 of file searchableBox.C.
References treeBoundBox::faceNormals, forAll, searchableBox::getVolumeType(), List< T >::setSize(), List< T >::size(), and Foam::Zero.
Referenced by searchableBox::getRegion(), and searchableBox::overlaps().
getVolumeType()
void getVolumeType (const pointField & points, List< volumeType > & volType) const virtual
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Implements searchableSurface.
Definition at line 599 of file searchableBox.C.
References forAll, volumeType::INSIDE, Foam::max(), Foam::min(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, volumeType::OUTSIDE, List< T >::setSize(), and List< T >::size().
Referenced by searchableBox::getNormal(), and searchableBox::overlaps().
writeData()
bool writeData (Ostream &) const inline virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 261 of file searchableBox.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurface/searchableBox.H
src/meshTools/searchableSurface/searchableBox.C