OpenFOAM: surfaceToCell Class Reference
surfaceToCell Class Reference
A topoSetSource to select cells based on relation to surface.
Public Member Functions
TypeName ("surfaceToCell")
Runtime type information.
surfaceToCell (const polyMesh &mesh, const fileName &surfName, const pointField &outsidePoints, const bool includeCut, const bool includeInside, const bool includeOutside, const bool useSurfaceOrientation, const scalar nearDist, const scalar curvature)
Construct from components.
surfaceToCell (const polyMesh &mesh, const fileName &surfName, const triSurface &surf, const triSurfaceSearch &querySurf, const pointField &outsidePoints, const bool includeCut, const bool includeInside, const bool includeOutside, const bool useSurfaceOrientation, const scalar nearDist, const scalar curvature)
Construct from components (supplied surface, surfaceSearch)
surfaceToCell (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
surfaceToCell (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~surfaceToCell ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label celli, const bool) const
Add (if bool) celli to set or delete celli from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = nullptr
A table of usage strings.
Detailed Description
A topoSetSource to select cells based on relation to surface.
Selects:
all cells inside/outside/cut by surface
all cells inside/outside surface ('useSurfaceOrientation', requires closed surface)
cells with centre nearer than XXX to surface
cells with centre nearer than XXX to surface and with normal at nearest point to centre and cell-corners differing by more than YYY (i.e., point of high curvature)
Source files
surfaceToCell.H
surfaceToCell.C
Definition at line 60 of file surfaceToCell.H.
Constructor & Destructor Documentation
surfaceToCell() [1/4]
surfaceToCell (const polyMesh & mesh, const fileName & surfName, const pointField & outsidePoints, const bool includeCut, const bool includeInside, const bool includeOutside, const bool useSurfaceOrientation, const scalar nearDist, const scalar curvature)
Construct from components.
Definition at line 359 of file surfaceToCell.C.
Referenced by surfaceToCell::surfaceToCell().
surfaceToCell() [2/4]
surfaceToCell (const polyMesh & mesh, const fileName & surfName, const triSurface & surf, const triSurfaceSearch & querySurf, const pointField & outsidePoints, const bool includeCut, const bool includeInside, const bool includeOutside, const bool useSurfaceOrientation, const scalar nearDist, const scalar curvature)
Construct from components (supplied surface, surfaceSearch)
Definition at line 389 of file surfaceToCell.C.
References surfaceToCell::surfaceToCell().
surfaceToCell() [3/4]
surfaceToCell (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 421 of file surfaceToCell.C.
References surfaceToCell::surfaceToCell().
surfaceToCell() [4/4]
surfaceToCell (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 447 of file surfaceToCell.C.
~surfaceToCell()
~surfaceToCell () virtual
Destructor.
Definition at line 471 of file surfaceToCell.C.
References surfaceToCell::applyToSet(), and Foam::deleteDemandDrivenData().
Member Function Documentation
TypeName()
TypeName ("surfaceToCell")
Runtime type information.
setType()
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 205 of file surfaceToCell.H.
References surfaceToCell::applyToSet(), and topoSetSource::CELLSETSOURCE.
applyToSet()
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 484 of file surfaceToCell.C.
References topoSetSource::ADD, Foam::ListListOps::combine(), topoSetSource::DELETE, Foam::endl(), Foam::Info, and topoSetSource::NEW.
Referenced by surfaceToCell::setType(), and surfaceToCell::~surfaceToCell().
The documentation for this class was generated from the following files:
src/meshTools/sets/cellSources/surfaceToCell/surfaceToCell.H
src/meshTools/sets/cellSources/surfaceToCell/surfaceToCell.C