OpenFOAM: faceZoneSet Class Reference
faceZoneSet Class Reference
Like faceSet but updates faceZone when writing.
Public Member Functions
TypeName ("faceZoneSet")
Runtime type information.
faceZoneSet (const polyMesh &mesh, const word &name, readOption r=MUST_READ, writeOption w=NO_WRITE)
Construct from objectRegistry and name.
faceZoneSet (const polyMesh &mesh, const word &name, const label, writeOption w=NO_WRITE)
Construct from additional size of labelHashSet.
faceZoneSet (const polyMesh &mesh, const word &name, const topoSet &, writeOption w=NO_WRITE)
Construct from existing set.
virtual ~faceZoneSet ()
Destructor.
const labelList & addressing () const
labelList & addressing ()
const boolList & flipMap () const
boolList & flipMap ()
void updateSet ()
Sort addressing and make faceSet part consistent with addressing.
virtual void invert (const label maxLen)
Invert contents. (insert all members 0..maxLen-1 which were not in.
virtual void subset (const topoSet &set)
Subset contents. Only elements present in both sets remain.
virtual void addSet (const topoSet &set)
Add elements present in set.
virtual void deleteSet (const topoSet &set)
Delete elements present in set.
virtual void sync (const polyMesh &mesh)
Sync faceZoneSet across coupled patches.
virtual void writeDebug (Ostream &os, const primitiveMesh &, const label maxLen) const
Write maxLen items with label and coordinates.
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write faceZone.
virtual void updateMesh (const mapPolyMesh &morphMap)
Update any stored data for new labels.
virtual label maxSize (const polyMesh &mesh) const
Return max index+1.
Public Member Functions inherited from faceSet
TypeName ("faceSet")
Runtime type information.
faceSet (const IOobject &obj)
Construct from IOobject.
faceSet (const polyMesh &mesh, const word &name, readOption r=MUST_READ, writeOption w=NO_WRITE)
Construct from objectRegistry and name.
faceSet (const polyMesh &mesh, const word &name, const label, writeOption w=NO_WRITE)
Construct from additional size of labelHashSet.
faceSet (const polyMesh &mesh, const word &name, const topoSet &, writeOption w=NO_WRITE)
Construct from existing set.
faceSet (const polyMesh &mesh, const word &name, const labelHashSet &, writeOption w=NO_WRITE)
Construct from additional labelHashSet.
virtual ~faceSet ()
Destructor.
Public Member Functions inherited from topoSet
TypeName ("topoSet")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSet, word,(const polyMesh &mesh, const word &name, readOption r, writeOption w),(mesh, name, r, w))
declareRunTimeSelectionTable (autoPtr, topoSet, size,(const polyMesh &mesh, const word &name, const label size, writeOption w),(mesh, name, size, w))
declareRunTimeSelectionTable (autoPtr, topoSet, set,(const polyMesh &mesh, const word &name, const topoSet &set, writeOption w),(mesh, name, set, w))
topoSet (const IOobject &, const word &wantedType)
Construct from IOobject as explicitly passed type.
topoSet (const polyMesh &mesh, const word &wantedType, const word &name, readOption r=MUST_READ, writeOption w=NO_WRITE)
Construct from polyMesh and name. Searches for a polyMesh/sets.
topoSet (const polyMesh &mesh, const word &name, const label, writeOption w=NO_WRITE)
Construct empty from additional size of labelHashSet.
topoSet (const polyMesh &mesh, const word &name, const labelHashSet &, writeOption w=NO_WRITE)
Construct empty from additional labelHashSet.
topoSet (const IOobject &, const label size)
Construct empty from IOobject and size.
topoSet (const IOobject &, const labelHashSet &)
Construct from IOobject and labelHashSet.
autoPtr< topoSet > clone () const
Clone.
virtual ~topoSet ()
Destructor.
virtual void writeDebug (Ostream &os, const label maxLen) const
Write labels columnwise to os. Truncate to maxLen.
virtual bool writeData (Ostream &) const
Write contents.
void operator= (const topoSet &)
Copy labelHashSet part only.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashSet< label, Hash< label > >
HashSet (const label size=128)
Construct given initial size.
HashSet (Istream &is)
Construct from Istream.
HashSet (const UList< label > &)
Construct from UList of Key.
HashSet (const HashSet< label, Hash< label > > &hs)
Construct as copy.
HashSet (const Xfer< HashSet< label, Hash< label > >> &hs)
Construct by transferring the parameter contents.
HashSet (const Xfer< HashTable< nil, label, Hash< label > >> &hs)
Construct by transferring the parameter contents.
HashSet (const HashTable< AnyType, label, AnyHash > &)
Construct from the keys of another HashTable,.
bool insert (const label &key)
Insert a new entry.
label insert (const UList< label > &)
Insert keys from a UList of Key.
bool set (const label &key)
Same as insert (cannot overwrite nil content)
label set (const UList< label > &lst)
Same as insert (cannot overwrite nil content)
bool unset (const label &key)
Unset the specified key - same as erase.
bool operator[] (const label &) const
Return true if the entry exists, same as found()
bool operator== (const HashSet< label, Hash< label > > &) const
Equality. Two hashtables are equal when their contents are equal.
bool operator!= (const HashSet< label, Hash< label > > &) const
The opposite of the equality operation.
void operator|= (const HashSet< label, Hash< label > > &)
Combine entries from HashSets.
void operator&= (const HashSet< label, Hash< label > > &)
Only retain entries found in both HashSets.
void operator^= (const HashSet< label, Hash< label > > &)
Only retain unique entries (xor)
void operator+= (const HashSet< label, Hash< label > > &rhs)
Add entries listed in the given HashSet to this HashSet.
void operator-= (const HashSet< label, Hash< label > > &)
Remove entries listed in the given HashSet from this HashSet.
Public Member Functions inherited from HashTable< nil, label, Hash< label > >
bool set (const label &, const nil &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< nil, label, Hash< label > > &)
Construct as copy.
HashTable (const Xfer< HashTable< nil, label, Hash< label > >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< label, nil >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const label &) const
Return true if hashedEntry is found in table.
iterator find (const label &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const label &) const
Find and return an const_iterator set at the hashedEntry.
List< label > toc () const
Return the table of contents.
List< label > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const label &, const nil &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const label &)
Erase a hashedEntry specified by the given key.
label erase (const UList< label > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, label, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Foam::label erase (const HashTable< AnyType, label, AnyHash > &rhs)
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< nil, label, Hash< label > > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< nil, label, Hash< label > > > xfer ()
Transfer contents to the Xfer container.
nil & operator[] (const label &)
Find and return a hashedEntry.
const nil & operator[] (const label &) const
Find and return a hashedEntry.
nil & operator() (const label &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< nil, label, Hash< label > > &)
Assignment.
void operator= (std::initializer_list< Tuple2< label, nil >>)
Assignment to an initializer list.
bool operator== (const HashTable< nil, label, Hash< label > > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< nil, label, Hash< label > > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashSet< label, Hash< label > >
typedef HashTable< nil, label, Hash< label > >::iterator iterator
typedef HashTable< nil, label, Hash< label > >::const_iterator const_iterator
Public Types inherited from HashTable< nil, label, Hash< label > >
typedef nil value_type
Type of values the HashTable contains.
typedef nil & reference
Type that can be used for storing into HashTable::value_type.
typedef const nil & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Static Public Member Functions inherited from topoSet
static fileName localPath (const polyMesh &mesh, const word &name)
Name of file set will use.
static autoPtr< topoSet > New (const word &setType, const polyMesh &mesh, const word &name, readOption r=MUST_READ, writeOption w=NO_WRITE)
Return a pointer to a toposet read from file.
static autoPtr< topoSet > New (const word &setType, const polyMesh &mesh, const word &name, const label size, writeOption w=NO_WRITE)
Return a pointer to a new toposet of given size.
static autoPtr< topoSet > New (const word &setType, const polyMesh &mesh, const word &name, const topoSet &set, writeOption w=NO_WRITE)
Return a pointer to a new toposet as copy of another toposet.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Protected Member Functions inherited from topoSet
void updateLabels (const labelList &map)
Update map from map. Used to update cell/face labels.
void check (const label maxLabel)
Check validity of contents.
void writeDebug (Ostream &os, const label maxElem, topoSet::const_iterator &iter, label &elemI) const
Write part of contents nicely formatted. Prints labels only.
void writeDebug (Ostream &os, const pointField &coords, const label maxElem, topoSet::const_iterator &iter, label &elemI) const
Write part of contents nicely formatted. Prints label.
void writeDebug (Ostream &os, const pointField &coords, const label maxLen) const
Write labels and coordinates columnwise to os. Truncate to maxLen.
topoSet (const topoSet &)
Disallow default bitwise copy construct.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Like faceSet but updates faceZone when writing.
Source files
faceZoneSet.H
faceZone.C
Definition at line 49 of file faceZoneSet.H.
Constructor & Destructor Documentation
faceZoneSet() [1/3]
faceZoneSet (const polyMesh & mesh, const word & name, readOption r = MUST_READ, writeOption w = NO_WRITE)
Construct from objectRegistry and name.
Definition at line 67 of file faceZoneSet.C.
References topoSet::check(), polyMesh::faceZones(), ZoneMesh< ZoneType, MeshType >::findZoneID(), faceZone::flipMap(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, primitiveMesh::nFaces(), IOobject::READ_IF_PRESENT, and faceZoneSet::updateSet().
Referenced by faceZoneSet::faceZoneSet(), and faceZoneSet::updateSet().
faceZoneSet() [2/3]
faceZoneSet (const polyMesh & mesh, const word & name, const label size, writeOption w = NO_WRITE)
Construct from additional size of labelHashSet.
Definition at line 101 of file faceZoneSet.C.
References faceZoneSet::faceZoneSet(), and faceZoneSet::updateSet().
faceZoneSet() [3/3]
faceZoneSet (const polyMesh & mesh, const word & name, const topoSet & set, writeOption w = NO_WRITE)
Construct from existing set.
Definition at line 118 of file faceZoneSet.C.
References faceZoneSet::updateSet().
~faceZoneSet()
~faceZoneSet () virtual
Destructor.
Definition at line 136 of file faceZoneSet.C.
Member Function Documentation
TypeName()
TypeName ("faceZoneSet")
Runtime type information.
addressing() [1/2]
const labelList& addressing () const inline
Definition at line 107 of file faceZoneSet.H.
Referenced by faceZoneSet::addSet(), searchableSurfaceToFaceZone::applyToSet(), faceZoneToFaceZone::applyToSet(), setToFaceZone::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), and faceZoneSet::subset().
addressing() [2/2]
labelList& addressing () inline
Definition at line 112 of file faceZoneSet.H.
flipMap() [1/2]
const boolList& flipMap () const inline
Definition at line 118 of file faceZoneSet.H.
Referenced by faceZoneSet::addSet(), searchableSurfaceToFaceZone::applyToSet(), faceZoneToFaceZone::applyToSet(), setToFaceZone::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), and faceZoneSet::subset().
flipMap() [2/2]
boolList& flipMap () inline
Definition at line 123 of file faceZoneSet.H.
References faceZoneSet::addSet(), faceZoneSet::deleteSet(), faceZoneSet::invert(), faceZoneSet::maxSize(), faceZoneSet::subset(), faceZoneSet::sync(), faceZoneSet::updateMesh(), faceZoneSet::updateSet(), faceZoneSet::writeDebug(), and faceZoneSet::writeObject().
updateSet()
void updateSet ()
Sort addressing and make faceSet part consistent with addressing.
Definition at line 48 of file faceZoneSet.C.
References HashTable< nil, label, Hash< label > >::clearStorage(), faceZoneSet::faceZoneSet(), forAll, HashSet< label, Hash< label > >::insert(), HashTable< nil, label, Hash< label > >::resize(), UIndirectList< T >::size(), and Foam::sortedOrder().
Referenced by faceZoneSet::addSet(), searchableSurfaceToFaceZone::applyToSet(), faceZoneToFaceZone::applyToSet(), setToFaceZone::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), faceZoneSet::deleteSet(), faceZoneSet::faceZoneSet(), faceZoneSet::flipMap(), faceZoneSet::invert(), faceZoneSet::subset(), and faceZoneSet::updateMesh().
invert()
void invert (const label maxLen) virtual
Invert contents. (insert all members 0..maxLen-1 which were not in.
set)
Reimplemented from topoSet.
Definition at line 142 of file faceZoneSet.C.
References HashTable< nil, label, Hash< label > >::found(), n, List< T >::setSize(), and faceZoneSet::updateSet().
Referenced by faceZoneSet::flipMap().
subset()
void subset (const topoSet & set) virtual
Subset contents. Only elements present in both sets remain.
Reimplemented from topoSet.
Definition at line 173 of file faceZoneSet.C.
References faceZoneSet::addressing(), HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::find(), faceZoneSet::flipMap(), forAll, IOobject::name(), List< T >::size(), List< T >::transfer(), faceZoneSet::updateSet(), and WarningInFunction.
Referenced by faceZoneSet::flipMap().
addSet()
void addSet (const topoSet & set) virtual
Add elements present in set.
Reimplemented from topoSet.
Definition at line 221 of file faceZoneSet.C.
References faceZoneSet::addressing(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::find(), faceZoneSet::flipMap(), forAll, IOobject::name(), List< T >::size(), List< T >::transfer(), faceZoneSet::updateSet(), and WarningInFunction.
Referenced by faceZoneSet::flipMap().
deleteSet()
void deleteSet (const topoSet & set) virtual
Delete elements present in set.
Reimplemented from topoSet.
Definition at line 272 of file faceZoneSet.C.
References HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, IOobject::name(), List< T >::size(), List< T >::transfer(), faceZoneSet::updateSet(), and WarningInFunction.
Referenced by faceZoneSet::flipMap().
sync()
void sync (const polyMesh & mesh) virtual
Sync faceZoneSet across coupled patches.
Reimplemented from faceSet.
Definition at line 324 of file faceZoneSet.C.
Referenced by faceZoneSet::flipMap().
writeDebug()
void writeDebug (Ostream & os, const primitiveMesh & mesh, const label maxLen) const virtual
Write maxLen items with label and coordinates.
Reimplemented from faceSet.
Definition at line 408 of file faceZoneSet.C.
References faceSet::writeDebug().
Referenced by faceZoneSet::flipMap(), and faceZoneSet::updateMesh().
writeObject()
bool writeObject (IOstream::streamFormat s, IOstream::versionNumber v, IOstream::compressionType c) const virtual
Write faceZone.
Reimplemented from regIOobject.
Definition at line 335 of file faceZoneSet.C.
References ZoneMesh< ZoneType, MeshType >::clearAddressing(), ZoneMesh< ZoneType, MeshType >::findZoneID(), IOobject::name(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), Foam::type(), regIOobject::write(), and regIOobject::writeObject().
Referenced by faceZoneSet::flipMap(), and faceZoneSet::maxSize().
updateMesh()
void updateMesh (const mapPolyMesh & morphMap) virtual
Update any stored data for new labels.
Reimplemented from faceSet.
Definition at line 379 of file faceZoneSet.C.
References forAll, n, mapPolyMesh::reverseFaceMap(), List< T >::setSize(), List< T >::size(), List< T >::transfer(), faceZoneSet::updateSet(), and faceZoneSet::writeDebug().
Referenced by faceZoneSet::flipMap().
maxSize()
label maxSize (const polyMesh & mesh) const virtual
Return max index+1.
Reimplemented from faceSet.
Definition at line 328 of file faceZoneSet.C.
References primitiveMesh::nFaces(), and faceZoneSet::writeObject().
Referenced by faceZoneSet::flipMap().
The documentation for this class was generated from the following files:
src/meshTools/sets/topoSets/faceZoneSet.H
src/meshTools/sets/topoSets/faceZoneSet.C