OpenFOAM: nearestToPoint Class Reference
nearestToPoint Class Reference
A topoSetSource to select points nearest to points.
Public Member Functions
TypeName ("nearestToPoint")
Runtime type information.
nearestToPoint (const polyMesh &mesh, const pointField &points)
Construct from components.
nearestToPoint (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
nearestToPoint (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~nearestToPoint ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label celli, const bool) const
Add (if bool) celli to set or delete celli from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = nullptr
A table of usage strings.
Detailed Description
A topoSetSource to select points nearest to points.
Source files
nearestToPoint.H
nearestToPoint.C
Definition at line 48 of file nearestToPoint.H.
Constructor & Destructor Documentation
nearestToPoint() [1/3]
nearestToPoint (const polyMesh & mesh, const pointField & points)
Construct from components.
Definition at line 88 of file nearestToPoint.C.
Referenced by nearestToPoint::nearestToPoint().
nearestToPoint() [2/3]
nearestToPoint (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 100 of file nearestToPoint.C.
References nearestToPoint::nearestToPoint().
nearestToPoint() [3/3]
nearestToPoint (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 112 of file nearestToPoint.C.
~nearestToPoint()
~nearestToPoint () virtual
Destructor.
Definition at line 124 of file nearestToPoint.C.
References nearestToPoint::applyToSet().
Member Function Documentation
TypeName()
TypeName ("nearestToPoint")
Runtime type information.
setType()
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 102 of file nearestToPoint.H.
References nearestToPoint::applyToSet(), and topoSetSource::POINTSETSOURCE.
applyToSet()
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 131 of file nearestToPoint.C.
References topoSetSource::ADD, Foam::ListListOps::combine(), topoSetSource::DELETE, Foam::endl(), Foam::Info, and topoSetSource::NEW.
Referenced by nearestToPoint::setType(), and nearestToPoint::~nearestToPoint().
The documentation for this class was generated from the following files:
src/meshTools/sets/pointSources/nearestToPoint/nearestToPoint.H
src/meshTools/sets/pointSources/nearestToPoint/nearestToPoint.C