OpenFOAM: setsToFaceZone Class Reference
setsToFaceZone Class Reference
A topoSetSource to select faces based on usage in a faceSet and cellSet.
Public Member Functions
TypeName ("setsToFaceZone")
Runtime type information.
setsToFaceZone (const polyMesh &mesh, const word &faceSetName, const word &cellSetName, const Switch &flip)
Construct from components.
setsToFaceZone (const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
setsToFaceZone (const polyMesh &mesh, Istream &)
Construct from Istream.
virtual ~setsToFaceZone ()
Destructor.
virtual sourceType setType () const
virtual void applyToSet (const topoSetSource::setAction action, topoSet &) const
Public Member Functions inherited from topoSetSource
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
Additional Inherited Members
Public Types inherited from topoSetSource
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Static Public Member Functions inherited from topoSetSource
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions inherited from topoSetSource
void addOrDelete (topoSet &set, const label celli, const bool) const
Add (if bool) celli to set or delete celli from set.
Protected Attributes inherited from topoSetSource
const polyMesh & mesh_
Static Protected Attributes inherited from topoSetSource
static HashTable< string > * usageTablePtr_ = nullptr
A table of usage strings.
Detailed Description
A topoSetSource to select faces based on usage in a faceSet and cellSet.
Source files
setsToFaceZone.H
setsToFaceZone.C
Definition at line 49 of file setsToFaceZone.H.
Constructor & Destructor Documentation
setsToFaceZone() [1/3]
setsToFaceZone (const polyMesh & mesh, const word & faceSetName, const word & cellSetName, const Switch & flip)
Construct from components.
Definition at line 56 of file setsToFaceZone.C.
Referenced by setsToFaceZone::setsToFaceZone().
setsToFaceZone() [2/3]
setsToFaceZone (const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 72 of file setsToFaceZone.C.
References setsToFaceZone::setsToFaceZone().
setsToFaceZone() [3/3]
setsToFaceZone (const polyMesh & mesh, Istream & is)
Construct from Istream.
Definition at line 86 of file setsToFaceZone.C.
~setsToFaceZone()
~setsToFaceZone () virtual
Destructor.
Definition at line 100 of file setsToFaceZone.C.
References setsToFaceZone::applyToSet().
Member Function Documentation
TypeName()
TypeName ("setsToFaceZone")
Runtime type information.
setType()
virtual sourceType setType () const inline virtual
Implements topoSetSource.
Definition at line 104 of file setsToFaceZone.H.
References setsToFaceZone::applyToSet(), and topoSetSource::FACEZONESOURCE.
applyToSet()
void applyToSet (const topoSetSource::setAction action, topoSet & set) const virtual
Implements topoSetSource.
Definition at line 107 of file setsToFaceZone.C.
References topoSetSource::ADD, faceZoneSet::addressing(), topoSetSource::DELETE, Foam::endl(), faceZoneSet::flipMap(), forAll, forAllConstIter(), HashTable< T, Key, Hash >::found(), Foam::Info, IOobject::name(), topoSetSource::NEW, List< T >::size(), List< T >::transfer(), faceZoneSet::updateSet(), and WarningInFunction.
Referenced by setsToFaceZone::setType(), and setsToFaceZone::~setsToFaceZone().
The documentation for this class was generated from the following files:
src/meshTools/sets/faceZoneSources/setsToFaceZone/setsToFaceZone.H
src/meshTools/sets/faceZoneSources/setsToFaceZone/setsToFaceZone.C