OpenFOAM: triSurfaceTools Class Reference
triSurfaceTools Class Reference
A collection of tools for triSurface.
Public Types
enum sideType { UNKNOWN, INSIDE, OUTSIDE }
On which side of surface.
Public Member Functions
triSurface triangulateFaceCentre (const polyBoundaryMesh &mBesh, const labelHashSet &includePatches, const bool verbose=false)
Face-centre triangulation of (selected patches of) boundaryMesh.
Static Public Member Functions
static void writeOBJ (const fileName &fName, const pointField &pts)
Write pointField to OBJ format file.
static void writeOBJ (const triSurface &surf, const fileName &fName, const boolList &markedVerts)
Write vertex subset to OBJ format file.
static void getVertexTriangles (const triSurface &surf, const label edgeI, labelList &edgeTris)
Get all triangles using edge endpoint.
static labelList getVertexVertices (const triSurface &surf, const edge &e)
Get all vertices (local numbering) connected to vertices of edge.
static label otherFace (const triSurface &surf, const label facei, const label edgeI)
Get face connected to edge not facei.
static void otherEdges (const triSurface &surf, const label facei, const label edgeI, label &e1, label &e2)
Get the two edges on facei counterclockwise after edgeI.
static void otherVertices (const triSurface &surf, const label facei, const label vertI, label &vert1I, label &vert2I)
Get the two vertices (local numbering) on facei counterclockwise.
static label oppositeEdge (const triSurface &surf, const label facei, const label vertI)
Get edge opposite vertex (local numbering)
static label oppositeVertex (const triSurface &surf, const label facei, const label edgeI)
Get vertex (local numbering) opposite edge.
static label getEdge (const triSurface &surf, const label vert1I, const label vert2I)
Returns edge label connecting v1, v2 (local numbering)
static label getTriangle (const triSurface &surf, const label e0I, const label e1I, const label e2I)
Return index of triangle (or -1) using all three edges.
static triSurface collapseEdges (const triSurface &surf, const labelList &collapsableEdges)
Create new triSurface by collapsing edges to edge mids.
static triSurface collapseEdges (const triSurface &surf, const labelList &collapsableEdges, const pointField &edgeMids, labelList &faceStatus)
Create new triSurface by collapsing edges to specified.
static triSurface greenRefine (const triSurface &surf, const labelList &refineEdges)
Refine edges by splitting to opposite vertex.
static triSurface redGreenRefine (const triSurface &surf, const labelList &refineFaces)
Refine face by splitting all edges. Neighbouring face is.
static label minEdge (const triSurface &surf, const labelList &edgeIndices)
Returns element in edgeIndices with minimum length.
static label maxEdge (const triSurface &surf, const labelList &edgeIndices)
Returns element in edgeIndices with minimum length.
static triSurface mergePoints (const triSurface &surf, const scalar mergeTol)
Merge points within distance.
static vector surfaceNormal (const triSurface &surf, const label nearestFacei, const point &nearestPt)
Triangle (unit) normal. If nearest point to triangle on edge use.
static sideType edgeSide (const triSurface &surf, const point &sample, const point &nearestPoint, const label edgeI)
If nearest point is on edgeI, determine on which side of surface.
static sideType surfaceSide (const triSurface &surf, const point &sample, const label nearestFacei)
Given nearest point (to sample) on surface determines which side.
static triSurface triangulate (const polyBoundaryMesh &mBesh, const labelHashSet &includePatches, const bool verbose=false)
Simple triangulation of (selected patches of) boundaryMesh. Needs.
static void calcInterpolationWeights (const triPointRef &, const point &, FixedList< scalar, 3 > &weights)
Calculate linear interpolation weights for point (guaranteed to be.
static void calcInterpolationWeights (const triSurface &s, const pointField &samplePts, List< FixedList< label, 3 >> &verts, List< FixedList< scalar, 3 >> &weights)
static triSurface delaunay2D (const List< vector2D > &)
Do unconstrained Delaunay of points. Returns triSurface with 3D.
static surfaceLocation classify (const triSurface &, const label triI, const point &trianglePoint)
Test point on plane of triangle to see if on edge or point or inside.
static surfaceLocation trackToEdge (const triSurface &, const surfaceLocation &start, const surfaceLocation &end, const plane &cutPlane)
Track on surface to get closer to point.
static void track (const triSurface &, const surfaceLocation &endInfo, const plane &cutPlane, surfaceLocation &hitInfo)
Track from edge to edge across surface. Uses trackToEdge.
Static Public Attributes
static const label ANYEDGE = -1
Face collapse status.
static const label NOEDGE = -2
static const label COLLAPSED = -3
Detailed Description
A collection of tools for triSurface.
Source files
triSurfaceTools.H
triSurfaceTools.C
Definition at line 62 of file triSurfaceTools.H.
Member Enumeration Documentation
sideType
enum sideType
On which side of surface.
Enumerator
UNKNOWN
INSIDE
OUTSIDE
Definition at line 436 of file triSurfaceTools.H.
Member Function Documentation
writeOBJ() [1/2]
void writeOBJ (const fileName & fName, const pointField & pts) static
Write pointField to OBJ format file.
Definition at line 1251 of file triSurfaceTools.C.
References Foam::endl(), forAll, Foam::Pout, List< T >::size(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
writeOBJ() [2/2]
void writeOBJ (const triSurface & surf, const fileName & fName, const boolList & markedVerts) static
Write vertex subset to OBJ format file.
Definition at line 1270 of file triSurfaceTools.C.
References Foam::endl(), forAll, triSurfaceTools::getVertexTriangles(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::Pout, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
getVertexTriangles()
void getVertexTriangles (const triSurface & surf, const label edgeI, labelList & edgeTris) static
Get all triangles using edge endpoint.
Definition at line 1300 of file triSurfaceTools.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), forAll, triSurfaceTools::getVertexVertices(), PrimitivePatch< Face, FaceList, PointField, PointType >::pointFaces(), List< T >::setSize(), List< T >::size(), and edge::start().
Referenced by triSurfaceTools::writeOBJ().
getVertexVertices()
Foam::labelList getVertexVertices (const triSurface & surf, const edge & e) static
Get all vertices (local numbering) connected to vertices of edge.
Definition at line 1343 of file triSurfaceTools.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), forAll, HashSet< Key, Hash >::insert(), triSurfaceTools::otherFace(), edge::otherVertex(), PrimitivePatch< Face, FaceList, PointField, PointType >::pointEdges(), edge::start(), and HashTable< T, Key, Hash >::toc().
Referenced by triSurfaceTools::getVertexTriangles().
otherFace()
Foam::label otherFace (const triSurface & surf, const label facei, const label edgeI) static
Get face connected to edge not facei.
Definition at line 1428 of file triSurfaceTools.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), triSurfaceTools::otherEdges(), and List< T >::size().
Referenced by triSurfaceTools::getVertexVertices().
otherEdges()
void otherEdges (const triSurface & surf, const label facei, const label edgeI, label & e1, label & e2) static
Get the two edges on facei counterclockwise after edgeI.
Definition at line 1456 of file triSurfaceTools.C.
References Foam::abort(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), Foam::findIndex(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), and triSurfaceTools::otherVertices().
Referenced by triSurfaceTools::otherFace().
otherVertices()
void otherVertices (const triSurface & surf, const label facei, const label vertI, label & vert1I, label & vert2I) static
Get the two vertices (local numbering) on facei counterclockwise.
vertI
Definition at line 1485 of file triSurfaceTools.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), and triSurfaceTools::oppositeEdge().
Referenced by triSurfaceTools::otherEdges().
oppositeEdge()
Foam::label oppositeEdge (const triSurface & surf, const label facei, const label vertI) static
Get edge opposite vertex (local numbering)
Definition at line 1520 of file triSurfaceTools.C.
References Foam::abort(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), Foam::FatalError, FatalErrorInFunction, forAll, triSurfaceTools::oppositeVertex(), and edge::start().
Referenced by triSurfaceTools::otherVertices().
oppositeVertex()
Foam::label oppositeVertex (const triSurface & surf, const label facei, const label edgeI) static
Get vertex (local numbering) opposite edge.
Definition at line 1550 of file triSurfaceTools.C.
References Foam::abort(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), Foam::FatalError, FatalErrorInFunction, forAll, triSurfaceTools::getEdge(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), and edge::start().
Referenced by triSurfaceTools::collapseEdges(), and triSurfaceTools::oppositeEdge().
getEdge()
Foam::label getEdge (const triSurface & surf, const label vert1I, const label vert2I) static
Returns edge label connecting v1, v2 (local numbering)
Definition at line 1579 of file triSurfaceTools.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), forAll, triSurfaceTools::getTriangle(), PrimitivePatch< Face, FaceList, PointField, PointType >::pointEdges(), and edge::start().
Referenced by triSurfaceTools::oppositeVertex().
getTriangle()
Foam::label getTriangle (const triSurface & surf, const label e0I, const label e1I, const label e2I) static
Return index of triangle (or -1) using all three edges.
Definition at line 1603 of file triSurfaceTools.C.
References Foam::abort(), triSurfaceTools::collapseEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), Foam::FatalError, FatalErrorInFunction, and forAll.
Referenced by triSurfaceTools::getEdge().
collapseEdges() [1/2]
Foam::triSurface collapseEdges (const triSurface & surf, const labelList & collapsableEdges) static
Create new triSurface by collapsing edges to edge mids.
Definition at line 1650 of file triSurfaceTools.C.
References triSurfaceTools::ANYEDGE, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), List< T >::size(), and edge::start().
Referenced by triSurfaceTools::getTriangle().
collapseEdges() [2/2]
Foam::triSurface collapseEdges (const triSurface & surf, const labelList & collapsableEdges, const pointField & edgeMids, labelList & faceStatus) static
Create new triSurface by collapsing edges to specified.
positions. faceStatus allows explicit control over which faces need to be protected (see above). faceStatus gets updated to protect collapsing already collapsed faces.
Definition at line 1703 of file triSurfaceTools.C.
References Foam::abort(), triSurfaceTools::ANYEDGE, Foam::constant::physicoChemical::b, Foam::constant::universal::c, triSurfaceTools::COLLAPSED, PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::min(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), triSurfaceTools::oppositeVertex(), triSurface::patches(), triSurfaceTools::redGreenRefine(), FixedList< T, Size >::setSize(), List< T >::size(), edge::start(), and HashTable< T, Key, Hash >::toc().
greenRefine()
Foam::triSurface greenRefine (const triSurface & surf, const labelList & refineEdges) static
Refine edges by splitting to opposite vertex.
Definition at line 1884 of file triSurfaceTools.C.
References List< T >::append(), PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), triSurfaceTools::minEdge(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), newPointi, PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), triSurface::patches(), List< T >::setSize(), List< T >::size(), and edge::start().
redGreenRefine()
Foam::triSurface redGreenRefine (const triSurface & surf, const labelList & refineFaces) static
Refine face by splitting all edges. Neighbouring face is.
greenRefine'd.
Definition at line 1865 of file triSurfaceTools.C.
References forAll, and List< T >::size().
Referenced by triSurfaceTools::collapseEdges().
minEdge()
Foam::label minEdge (const triSurface & surf, const labelList & edgeIndices) static
Returns element in edgeIndices with minimum length.
Definition at line 1976 of file triSurfaceTools.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), triSurfaceTools::maxEdge(), and edge::start().
Referenced by triSurfaceTools::greenRefine().
maxEdge()
Foam::label maxEdge (const triSurface & surf, const labelList & edgeIndices) static
Returns element in edgeIndices with minimum length.
Definition at line 2006 of file triSurfaceTools.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), triSurfaceTools::mergePoints(), and edge::start().
Referenced by triSurfaceTools::minEdge().
mergePoints()
Foam::triSurface mergePoints (const triSurface & surf, const scalar mergeTol) static
Merge points within distance.
Definition at line 2036 of file triSurfaceTools.C.
References forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mergePoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), triSurface::patches(), FixedList< T, Size >::setSize(), List< T >::size(), and triSurfaceTools::surfaceNormal().
Referenced by triSurfaceTools::maxEdge().
surfaceNormal()
Foam::vector surfaceNormal (const triSurface & surf, const label nearestFacei, const point & nearestPt) static
Triangle (unit) normal. If nearest point to triangle on edge use.
edge normal (calculated on the fly); if on vertex use vertex normal. Uses planarTol.
Definition at line 2095 of file triSurfaceTools.C.
References triangle< Point, PointRef >::EDGE, PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), triSurfaceTools::edgeSide(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), Foam::mag(), triFace::nearestPointClassify(), triangle< Point, PointRef >::NONE, PrimitivePatch< Face, FaceList, PointField, PointType >::pointNormals(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), and Foam::Zero.
Referenced by triSurfaceTools::mergePoints().
edgeSide()
Foam::triSurfaceTools::sideType edgeSide (const triSurface & surf, const point & sample, const point & nearestPoint, const label edgeI) static
If nearest point is on edgeI, determine on which side of surface.
sample is.
Definition at line 2139 of file triSurfaceTools.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), triSurfaceTools::INSIDE, n, triSurfaceTools::OUTSIDE, List< T >::size(), triSurfaceTools::surfaceSide(), and triSurfaceTools::UNKNOWN.
Referenced by triSurfaceTools::surfaceNormal(), and triSurfaceTools::surfaceSide().
surfaceSide()
Foam::triSurfaceTools::sideType surfaceSide (const triSurface & surf, const point & sample, const label nearestFacei) static
Given nearest point (to sample) on surface determines which side.
sample is. Uses either face normal, edge normal or point normal (non-trivial). Uses triangle::classify.
Definition at line 2176 of file triSurfaceTools.C.
References Foam::abort(), Foam::constant::universal::c, triangle< Point, PointRef >::EDGE, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), triSurfaceTools::edgeSide(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), Foam::FatalError, FatalErrorInFunction, forAll, triSurfaceTools::INSIDE, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), Foam::magSqr(), triFace::nearestPointClassify(), triangle< Point, PointRef >::NONE, edge::otherVertex(), triSurfaceTools::OUTSIDE, PrimitivePatch< Face, FaceList, PointField, PointType >::pointEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), PointHit< Point >::rawPoint(), Foam::sqr(), and triSurfaceTools::triangulate().
Referenced by triSurfaceTools::edgeSide().
triangulate()
Foam::triSurface triangulate (const polyBoundaryMesh & mBesh, const labelHashSet & includePatches, const bool verbose = false) static
Simple triangulation of (selected patches of) boundaryMesh. Needs.
polyMesh (or polyBoundaryMesh) since only at this level are the triangles on neighbouring patches connected.
Definition at line 2333 of file triSurfaceTools.C.
References List< T >::append(), Foam::endl(), forAll, forAllConstIter(), mesh, polyBoundaryMesh::mesh(), patchIdentifier::name(), IOobject::name(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), face::nTriangles(), triSurface::patches(), patchi, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), polyMesh::points(), Foam::Pout, List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), face::triangles(), and triSurfaceTools::triangulateFaceCentre().
Referenced by triSurfaceTools::surfaceSide().
triangulateFaceCentre()
Foam::triSurface triangulateFaceCentre (const polyBoundaryMesh & mBesh, const labelHashSet & includePatches, const bool verbose = false)
Face-centre triangulation of (selected patches of) boundaryMesh.
Needs polyMesh (or polyBoundaryMesh) since only at this level are the triangles on neighbouring patches connected.
Definition at line 2420 of file triSurfaceTools.C.
References Foam::endl(), primitiveMesh::faceCentres(), UList< T >::fcIndex(), forAll, forAllConstIter(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), mesh, polyBoundaryMesh::mesh(), patchIdentifier::name(), IOobject::name(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), triSurface::patches(), patchi, polyMesh::points(), Foam::Pout, List< T >::setSize(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), List< T >::size(), and polyPatch::start().
Referenced by triSurfaceTools::triangulate().
calcInterpolationWeights() [1/2]
void calcInterpolationWeights (const triPointRef & tri, const point & p, FixedList< scalar, 3 > & weights) static
Calculate linear interpolation weights for point (guaranteed to be.
inside triangle)
Definition at line 2587 of file triSurfaceTools.C.
References triangle< Point, PointRef >::a(), triangle< Point, PointRef >::b(), triangle< Point, PointRef >::c(), Foam::mag(), and Foam::max().
Referenced by triSurfaceTools::calcInterpolationWeights(), and triSurfaceTools::delaunay2D().
calcInterpolationWeights() [2/2]
void calcInterpolationWeights (const triSurface & s, const pointField & samplePts, List< FixedList< label, 3 >> & verts, List< FixedList< scalar, 3 >> & weights) static
Definition at line 2619 of file triSurfaceTools.C.
References triSurfaceTools::calcInterpolationWeights(), triSurfaceTools::classify(), PointHit< Point >::distance(), triangle< Point, PointRef >::EDGE, FixedList< T, Size >::fcIndex(), forAll, PointHit< Point >::hit(), Foam::mag(), Foam::max(), Foam::min(), triangle< Point, PointRef >::nearestPointClassify(), triangle< Point, PointRef >::POINT, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), PointHit< Point >::rawPoint(), s(), List< T >::size(), and triFace::tri().
delaunay2D()
Foam::triSurface delaunay2D (const List< vector2D > & pts) static
Do unconstrained Delaunay of points. Returns triSurface with 3D.
points with z=0. All triangles in region 0.
Definition at line 2521 of file triSurfaceTools.C.
References Foam::abort(), UList< T >::begin(), triSurfaceTools::calcInterpolationWeights(), dtris2(), Foam::FatalError, FatalErrorInFunction, forAll, points, and List< T >::size().
classify()
Foam::surfaceLocation classify (const triSurface & s, const label triI, const point & trianglePoint) static
Test point on plane of triangle to see if on edge or point or inside.
Definition at line 2751 of file triSurfaceTools.C.
References triangle< Point, PointRef >::EDGE, surfaceLocation::elementType(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), triangle< Point, PointRef >::NONE, triangle< Point, PointRef >::POINT, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), PointIndexHit< Point >::setHit(), PointIndexHit< Point >::setIndex(), PointIndexHit< Point >::setMiss(), PointIndexHit< Point >::setPoint(), and triSurfaceTools::trackToEdge().
Referenced by triSurfaceTools::calcInterpolationWeights().
trackToEdge()
Foam::surfaceLocation trackToEdge (const triSurface & s, const surfaceLocation & start, const surfaceLocation & end, const plane & cutPlane) static
Track on surface to get closer to point.
Possible situations:
1. reached endpoint
2. reached edge (normal situation)
3. reached end of surface (edge on single face) Input:
starting position+triangle/edge/point (so has to be on surface!)
(optional) previous position+triangle/edge/point to prevent going back. Set index (of triangle/edge/point) to -1 if not used.
end position+triangle/edge/point (so has to be on surface!)
plane to follow. Has to go through end point! Returns:
true if end point reached (situation 1)
new position+triangle/edge/point Caller has to check for situation 3 by checking that triangle() is not set.
Definition at line 2795 of file triSurfaceTools.C.
References triangle< Point, PointRef >::EDGE, PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), surfaceLocation::elementType(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), triangle< Point, PointRef >::NONE, pFaces, PrimitivePatch< Face, FaceList, PointField, PointType >::pointFaces(), PointIndexHit< Point >::rawPoint(), PointIndexHit< Point >::setMiss(), triSurfaceTools::track(), and surfaceLocation::triangle().
Referenced by triSurfaceTools::classify(), and triSurfaceTools::track().
track()
void track (const triSurface & s, const surfaceLocation & endInfo, const plane & cutPlane, surfaceLocation & hitInfo) static
Track from edge to edge across surface. Uses trackToEdge.
Not really useful by itself, more example of how to use trackToEdge. endInfo should be location on surface. hitInfo should be initialised to starting location (on surface as well). Upon return is set to end location.
Definition at line 2873 of file triSurfaceTools.C.
References PointIndexHit< Point >::hit(), triSurfaceTools::trackToEdge(), and surfaceLocation::triangle().
Referenced by triSurfaceTools::trackToEdge().
Member Data Documentation
ANYEDGE
const Foam::label ANYEDGE = -1 static
Face collapse status.
anyEdge: any edge can be collapsed noEdge: no edge can be collapsed collapsed: already collapsed >0: edge label that can be collapsed
Definition at line 366 of file triSurfaceTools.H.
Referenced by triSurfaceTools::collapseEdges().
NOEDGE
const Foam::label NOEDGE = -2 static
Definition at line 367 of file triSurfaceTools.H.
COLLAPSED
const Foam::label COLLAPSED = -3 static
Definition at line 368 of file triSurfaceTools.H.
Referenced by triSurfaceTools::collapseEdges().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triSurfaceTools/triSurfaceTools.H
src/meshTools/triSurface/triSurfaceTools/triSurfaceTools.C