OpenFOAM: edgeSurface Class Reference
edgeSurface Class Reference
Description of surface in form of 'cloud of edges'.
Public Member Functions
ClassName ("edgeSurface")
edgeSurface (const triSurface &surf, const bool isFirstSurface, const surfaceIntersection &inter)
Construct from surface and intersection description.
const pointField & points () const
label nSurfacePoints () const
const edgeList & edges () const
label nSurfaceEdges () const
bool isSurfaceEdge (const label edgeI) const
label parentEdge (const label edgeI) const
Parent edge (original surface edge this edge came from).
const labelListList & faceEdges () const
From face to our edges_.
const labelListList & pointEdges () const
Point to edge addressing.
void addIntersectionEdges (const label facei, const edgeList &)
Add intersection edges to a face. Used for connecting.
Detailed Description
Description of surface in form of 'cloud of edges'.
The 'cloud of edges':
points
edges
faceEdges
parentEdge (edge on surface this edge originates from) and nothing more.
(pointEdges constructed from above data)
Constructed from triSurface and surfaceIntersection. (uses localPoints of surface of course)
Used to easily insert cuts and split faces.
Note
points with surface (local)points first, intersection points last
edges with (split) surface edges first, intersection edges last.
Source files
edgeSurface.H
edgeSurface.C
Definition at line 73 of file edgeSurface.H.
Constructor & Destructor Documentation
edgeSurface()
edgeSurface (const triSurface & surf, const bool isFirstSurface, const surfaceIntersection & inter)
Construct from surface and intersection description.
Definition at line 128 of file edgeSurface.C.
References edgeSurface::addIntersectionEdges(), List< T >::append(), surfaceIntersection::cutEdges(), surfaceIntersection::cutPoints(), surfaceIntersection::edgeCuts(), PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), UList< T >::empty(), edge::end(), Foam::endl(), surfaceIntersection::facePairToEdge(), forAll, forAllConstIter(), UList< T >::last(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::name(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), Foam::Pout, List< T >::size(), edge::start(), FixedList< T, Size >::transfer(), and Foam::meshTools::writeOBJ().
Member Function Documentation
ClassName()
ClassName ("edgeSurface")
points()
const pointField& points () const inline
Definition at line 137 of file edgeSurface.H.
Referenced by intersectedSurface::intersectedSurface().
nSurfacePoints()
label nSurfacePoints () const inline
Definition at line 142 of file edgeSurface.H.
Referenced by intersectedSurface::intersectedSurface().
edges()
const edgeList& edges () const inline
Definition at line 147 of file edgeSurface.H.
Referenced by intersectedSurface::intersectedSurface().
nSurfaceEdges()
label nSurfaceEdges () const inline
Definition at line 152 of file edgeSurface.H.
Referenced by intersectedSurface::intersectedSurface().
isSurfaceEdge()
bool isSurfaceEdge (const label edgeI) const inline
Definition at line 157 of file edgeSurface.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and edgeSurface::parentEdge().
parentEdge()
label parentEdge (const label edgeI) const inline
Parent edge (original surface edge this edge came from).
Valid only for edgeI < nSurfaceEdges_.
Definition at line 164 of file edgeSurface.H.
Referenced by edgeSurface::isSurfaceEdge().
faceEdges()
const labelListList& faceEdges () const inline
From face to our edges_.
Definition at line 181 of file edgeSurface.H.
Referenced by intersectedSurface::intersectedSurface().
pointEdges()
const labelListList& pointEdges () const inline
Point to edge addressing.
Definition at line 187 of file edgeSurface.H.
References edgeSurface::addIntersectionEdges().
addIntersectionEdges()
void addIntersectionEdges (const label facei, const edgeList & additionalEdges)
Add intersection edges to a face. Used for connecting.
floating intersection on face to rest of face.
Definition at line 343 of file edgeSurface.C.
References edge::end(), Foam::endl(), forAll, Foam::Pout, List< T >::setSize(), List< T >::size(), and edge::start().
Referenced by edgeSurface::edgeSurface(), and edgeSurface::pointEdges().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/booleanOps/intersectedSurface/edgeSurface.H
src/meshTools/triSurface/booleanOps/intersectedSurface/edgeSurface.C