OpenFOAM: topoSetSource Class Reference
topoSetSource Class Reference abstract
Base class of a source for a topoSet.
Classes
class addToUsageTable
Class with constructor to add usage string to table.
class iNew
Class used for the read-construction of.
Public Types
enum sourceType {
CELLSETSOURCE, FACESETSOURCE, POINTSETSOURCE, CELLZONESOURCE,
FACEZONESOURCE, POINTZONESOURCE
}
Enumeration defining the types of sources.
enum setAction {
CLEAR, NEW, INVERT, ADD,
DELETE, SUBSET, LIST, REMOVE
}
Enumeration defining the valid actions.
Public Member Functions
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone.
virtual ~topoSetSource ()
Destructor.
const polyMesh & mesh () const
virtual sourceType setType () const =0
virtual void applyToSet (const setAction action, topoSet &) const =0
Static Public Member Functions
static setAction toAction (const word &actionName)
Convert string to action.
static Istream & checkIs (Istream &is)
Check state of stream.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
Protected Member Functions
void addOrDelete (topoSet &set, const label celli, const bool) const
Add (if bool) celli to set or delete celli from set.
Protected Attributes
const polyMesh & mesh_
Static Protected Attributes
static HashTable< string > * usageTablePtr_ = nullptr
A table of usage strings.
Detailed Description
Base class of a source for a topoSet.
Implementer has to modify the given set (see applyToSet) according to its function and the setAction (one of add/delete/new)
Source files
topoSetSource.H
topoSetSource.C
Definition at line 63 of file topoSetSource.H.
Member Enumeration Documentation
sourceType
enum sourceType
Enumeration defining the types of sources.
Enumerator
CELLSETSOURCE
FACESETSOURCE
POINTSETSOURCE
CELLZONESOURCE
FACEZONESOURCE
POINTZONESOURCE
Definition at line 70 of file topoSetSource.H.
setAction
enum setAction
Enumeration defining the valid actions.
Enumerator
CLEAR
NEW
INVERT
ADD
DELETE
SUBSET
LIST
REMOVE
Definition at line 82 of file topoSetSource.H.
Constructor & Destructor Documentation
topoSetSource()
topoSetSource (const polyMesh & mesh)
Construct from components.
Definition at line 159 of file topoSetSource.C.
~topoSetSource()
~topoSetSource () virtual
Destructor.
Definition at line 167 of file topoSetSource.C.
Referenced by topoSetSource::clone().
Member Function Documentation
addOrDelete()
void addOrDelete (topoSet & set, const label celli, const bool add) const protected
Add (if bool) celli to set or delete celli from set.
Definition at line 140 of file topoSetSource.C.
Referenced by topoSetSource::checkIs().
TypeName()
TypeName ("topoSetSource")
Runtime type information.
toAction()
static setAction toAction (const word & actionName) inline static
Convert string to action.
Definition at line 157 of file topoSetSource.H.
References topoSetSource::checkIs(), topoSetSource::declareRunTimeSelectionTable(), dict, topoSetSource::mesh(), and topoSetSource::mesh_.
checkIs()
Foam::Istream & checkIs (Istream & is) static
Check state of stream.
Definition at line 121 of file topoSetSource.C.
References topoSetSource::addOrDelete(), IOstream::eof(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and IOstream::good().
Referenced by topoSetSource::toAction().
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , topoSetSource , word , (const polyMesh &mesh, const dictionary &dict) , (mesh, dict))
Referenced by topoSetSource::toAction().
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , topoSetSource , istream , (const polyMesh &mesh, Istream &is) , (mesh, is))
usage()
static const string& usage (const word & name) inline static
Definition at line 216 of file topoSetSource.H.
References HashTable< T, Key, Hash >::found(), Foam::name(), and topoSetSource::usageTablePtr_.
clone()
autoPtr<topoSetSource> clone () const inline
Clone.
Definition at line 242 of file topoSetSource.H.
References topoSetSource::New(), NotImplemented, and topoSetSource::~topoSetSource().
New() [1/2]
Foam::autoPtr< Foam::topoSetSource > New (const word & topoSetSourceType, const polyMesh & mesh, const dictionary & dict) static
Return a reference to the selected topoSetSource.
Definition at line 74 of file topoSetSource.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and mesh.
Referenced by topoSetSource::clone(), NamedEnum< directionType, 3 >::names(), and topoSetSource::iNew::operator()().
New() [2/2]
Foam::autoPtr< Foam::topoSetSource > New (const word & topoSetSourceType, const polyMesh & mesh, Istream & is) static
Return a reference to the selected topoSetSource.
Definition at line 98 of file topoSetSource.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and mesh.
mesh()
const polyMesh& mesh () const inline
Definition at line 274 of file topoSetSource.H.
References topoSetSource::applyToSet(), topoSetSource::mesh_, and topoSetSource::setType().
Referenced by topoSetSource::toAction().
setType()
virtual sourceType setType () const pure virtual
Implemented in surfaceToCell, regionToCell, surfaceToPoint, cellToFace, faceToCell, pointToFace, targetVolumeToCell, faceZoneToCell, pointToCell, fieldToCell, cellToPoint, faceToPoint, regionToFace, cylinderAnnulusToCell, rotatedBoxToCell, cylinderToCell, shapeToCell, sphereToCell, boxToCell, setsToFaceZone, nbrToCell, zoneToCell, boxToFace, patchToFace, zoneToFace, boxToPoint, zoneToPoint, labelToCell, nearestToCell, labelToFace, labelToPoint, nearestToPoint, setAndNormalToFaceZone, normalToFace, badQualityToCell, badQualityToFace, setToFaceZone, cellToCell, setToCellZone, faceToFace, faceZoneToFaceZone, pointToPoint, setToPointZone, boundaryToFace, and searchableSurfaceToFaceZone.
Referenced by topoSetSource::mesh().
applyToSet()
virtual void applyToSet (const setAction action, topoSet &) const pure virtual
Implemented in surfaceToCell, regionToCell, surfaceToPoint, cellToFace, faceToCell, pointToFace, targetVolumeToCell, faceZoneToCell, pointToCell, fieldToCell, cellToPoint, faceToPoint, regionToFace, cylinderAnnulusToCell, rotatedBoxToCell, cylinderToCell, shapeToCell, sphereToCell, boxToCell, setsToFaceZone, nbrToCell, zoneToCell, boxToFace, patchToFace, zoneToFace, boxToPoint, zoneToPoint, labelToCell, nearestToCell, labelToFace, labelToPoint, nearestToPoint, setAndNormalToFaceZone, normalToFace, badQualityToCell, badQualityToFace, setToFaceZone, cellToCell, setToCellZone, faceToFace, faceZoneToFaceZone, pointToPoint, setToPointZone, boundaryToFace, and searchableSurfaceToFaceZone.
Referenced by topoSetSource::mesh().
Member Data Documentation
usageTablePtr_
Foam::HashTable< Foam::string > * usageTablePtr_ = nullptr static protected
A table of usage strings.
Definition at line 97 of file topoSetSource.H.
Referenced by NamedEnum< directionType, 3 >::names(), topoSetSource::usage(), and topoSetSource::addToUsageTable::~addToUsageTable().
mesh_
const polyMesh& mesh_ protected
Definition at line 126 of file topoSetSource.H.
Referenced by normalToFace::applyToSet(), topoSetSource::mesh(), and topoSetSource::toAction().
The documentation for this class was generated from the following files:
src/meshTools/sets/topoSetSource/topoSetSource.H
src/meshTools/sets/topoSetSource/topoSetSource.C