OpenFOAM: edgeIntersections Class Reference
edgeIntersections Class Reference
Holder of intersections of edges of a surface with another surface. Optionally shuffles around points on surface to resolve any 'conflicts' (edge hitting triangle edge, edge hitting point etc.).
Public Member Functions
ClassName ("edgeIntersections")
edgeIntersections ()
Construct null.
edgeIntersections (const triSurface &surf1, const triSurfaceSearch &query2, const scalarField &surf1PointTol)
Construct from surface and tolerance.
edgeIntersections (const List< List< pointIndexHit >> &, const labelListList &)
Construct from components.
const labelListList & classification () const
For every intersection the classification status.
label removeDegenerates (const label nIters, const triSurface &surf1, const triSurfaceSearch &query2, const scalarField &surf1PointTol, pointField &points1)
Resolve ties. Shuffles points so all edge - face intersections.
void merge (const edgeIntersections &, const labelList &edgeMap, const labelList &faceMap, const bool merge=true)
Merge (or override) edge intersection for a subset.
Public Member Functions inherited from List< List< pointIndexHit > >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const List< pointIndexHit > &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< List< pointIndexHit > > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< List< pointIndexHit > >> &)
Construct by transferring the parameter contents.
List (List< List< pointIndexHit > > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< List< pointIndexHit > > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< List< pointIndexHit >, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< List< pointIndexHit > > &)
Construct as copy of PtrList<T>
List (const SLList< List< pointIndexHit > > &)
Construct as copy of SLList<T>
List (const UIndirectList< List< pointIndexHit > > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< List< pointIndexHit > > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< List< pointIndexHit > >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< List< pointIndexHit > > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const List< pointIndexHit > &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const List< pointIndexHit > &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const List< pointIndexHit > &)
Append an element at the end of the list.
void append (const UList< List< pointIndexHit > > &)
Append a List at the end of this list.
void append (const UIndirectList< List< pointIndexHit > > &)
Append a UIndirectList at the end of this list.
void transfer (List< List< pointIndexHit > > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< List< pointIndexHit >, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< List< pointIndexHit > > &)
Transfer the contents of the argument List into this list.
Xfer< List< List< pointIndexHit > > > xfer ()
Transfer contents to the Xfer container.
List< pointIndexHit > & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< List< pointIndexHit > > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< List< pointIndexHit > > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< List< pointIndexHit > > &)
Assignment operator. Takes linear time.
void operator= (const SLList< List< pointIndexHit > > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< List< pointIndexHit > > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< List< pointIndexHit > > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< List< pointIndexHit > >)
Assignment to an initializer list.
void operator= (const List< pointIndexHit > &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static scalarField minEdgeLength (const triSurface &surf)
Calculate min edge length for every surface point.
Static Public Member Functions inherited from List< List< pointIndexHit > >
static const List< List< pointIndexHit > > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes
static scalar alignedCos_ = cos(degToRad(89.0))
Cosine between edge and face normal when considered parallel.
Additional Inherited Members
Public Types inherited from List< List< pointIndexHit > >
typedef SubList< List< pointIndexHit > > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Protected Member Functions inherited from List< List< pointIndexHit > >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
Holder of intersections of edges of a surface with another surface. Optionally shuffles around points on surface to resolve any 'conflicts' (edge hitting triangle edge, edge hitting point etc.).
Source files
edgeIntersections.H
edgeIntersections.C
Definition at line 60 of file edgeIntersections.H.
Constructor & Destructor Documentation
edgeIntersections() [1/3]
edgeIntersections ()
Construct null.
Definition at line 458 of file edgeIntersections.C.
Referenced by edgeIntersections::edgeIntersections().
edgeIntersections() [2/3]
edgeIntersections (const triSurface & surf1, const triSurfaceSearch & query2, const scalarField & surf1PointTol)
Construct from surface and tolerance.
Definition at line 467 of file edgeIntersections.C.
References edgeIntersections::edgeIntersections(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), and triSurfaceSearch::surface().
edgeIntersections() [3/3]
edgeIntersections (const List< List< pointIndexHit >> & intersections, const labelListList & classification)
Construct from components.
Definition at line 502 of file edgeIntersections.C.
Member Function Documentation
ClassName()
ClassName ("edgeIntersections")
minEdgeLength()
Foam::scalarField minEdgeLength (const triSurface & surf) static
Calculate min edge length for every surface point.
Definition at line 514 of file edgeIntersections.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), Foam::min(), PrimitivePatch< Face, FaceList, PointField, PointType >::pointEdges(), edgeIntersections::removeDegenerates(), and List< T >::size().
classification()
const labelListList& classification () const inline
For every intersection the classification status.
Definition at line 178 of file edgeIntersections.H.
References Foam::faceMap(), edgeIntersections::merge(), and edgeIntersections::removeDegenerates().
Referenced by edgeIntersections::merge().
removeDegenerates()
Foam::label removeDegenerates (const label nIters, const triSurface & surf1, const triSurfaceSearch & query2, const scalarField & surf1PointTol, pointField & points1)
Resolve ties. Shuffles points so all edge - face intersections.
will be on the face interior. Points will be the new surface points. Returns number of iterations needed. (= nIters if still has degenerate cuts)
Definition at line 542 of file edgeIntersections.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, edgeIntersections::merge(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), Foam::nl, Foam::Pout, rndGen(), and triSurfaceSearch::surface().
Referenced by edgeIntersections::classification(), and edgeIntersections::minEdgeLength().
merge()
void merge (const edgeIntersections & subInfo, const labelList & edgeMap, const labelList & faceMap, const bool merge = true)
Merge (or override) edge intersection for a subset.
(given as edge map and face map - for face indices stored in pointIndexHit.index())
Definition at line 700 of file edgeIntersections.C.
References edgeIntersections::classification(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), UList< T >::operator[](), PointIndexHit< Point >::rawPoint(), List< T >::setSize(), and List< T >::size().
Referenced by edgeIntersections::classification(), and edgeIntersections::removeDegenerates().
Member Data Documentation
alignedCos_
scalar alignedCos_ = cos(degToRad(89.0)) static
Cosine between edge and face normal when considered parallel.
(note: should be private and make access- and set- function)
Definition at line 142 of file edgeIntersections.H.
The documentation for this class was generated from the following files:
src/meshTools/triSurface/booleanOps/surfaceIntersection/edgeIntersections.H
src/meshTools/triSurface/booleanOps/surfaceIntersection/edgeIntersections.C