OpenFOAM: surfaceFeatures Class Reference
surfaceFeatures Class Reference
Holds feature edges/points of surface.
Public Types
enum edgeStatus { NONE, REGION, EXTERNAL, INTERNAL }
Public Member Functions
ClassName ("surfaceFeatures")
surfaceFeatures (const triSurface &)
Construct from surface.
surfaceFeatures (const triSurface &, const labelList &featurePoints, const labelList &featureEdges, const label externalStart, const label internalStart)
Construct from components.
surfaceFeatures (const triSurface &, const scalar includedAngle, const scalar minLen=0, const label minElems=0, const bool geometricTestOnly=false)
Construct from surface, angle and min cumulative length and/or.
surfaceFeatures (const triSurface &, const dictionary &dict)
Construct from dictionary.
surfaceFeatures (const triSurface &, const fileName &fName)
Construct from file.
surfaceFeatures (const triSurface &, const pointField &points, const edgeList &edges, const scalar mergeTol=1e-6, const bool geometricTestOnly=false)
Construct from pointField and edgeList (edgeMesh)
surfaceFeatures (const surfaceFeatures &)
Construct as copy.
const triSurface & surface () const
const labelList & featurePoints () const
Return feature point list.
const labelList & featureEdges () const
Return feature edge list.
label externalStart () const
Start of external edges.
label internalStart () const
Start of internal edges.
label nRegionEdges () const
Return number of region edges.
label nExternalEdges () const
Return number of external edges.
label nInternalEdges () const
Return number of internal edges.
labelList selectFeatureEdges (const bool regionEdges, const bool externalEdges, const bool internalEdges) const
Helper function: select a subset of featureEdges_.
void findFeatures (const scalar includedAngle, const bool geometricTestOnly)
Find feature edges using provided included angle.
labelList trimFeatures (const scalar minLen, const label minElems, const scalar includedAngle)
Delete small sets of edges. Edges are stringed up and any.
List< edgeStatus > toStatus () const
From member feature edges to status per edge.
void setFromStatus (const List< edgeStatus > &edgeStat, const scalar includedAngle)
Set from status per edge.
Map< label > nearestSamples (const labelList &selectedPoints, const pointField &samples, const scalarField &maxDistSqr) const
Find nearest sample for selected surface points.
Map< label > nearestSamples (const labelList &selectedEdges, const pointField &samples, const scalarField &sampleDist, const scalarField &maxDistSqr, const scalar minSampleDist=0.1) const
Find nearest sample for regularly sampled points along.
Map< pointIndexHit > nearestEdges (const labelList &selectedEdges, const edgeList &sampleEdges, const labelList &selectedSampleEdges, const pointField &samplePoints, const scalarField &sampleDist, const scalarField &maxDistSqr, const scalar minSampleDist=0.1) const
Like nearestSamples but now gets nearest point on.
void nearestSurfEdge (const labelList &selectedEdges, const pointField &samples, scalar searchSpanSqr, labelList &edgeLabel, labelList &edgeEndPoint, pointField &edgePoint) const
Find nearest surface edge (out of selectedEdges) for.
void nearestSurfEdge (const labelList &selectedEdges, const edgeList &sampleEdges, const labelList &selectedSampleEdges, const pointField &samplePoints, const vector &searchSpan, labelList &edgeLabel, pointField &pointOnEdge, pointField &pointOnFeature) const
Find nearest surface edge (out of selectedEdges) for each.
void nearestFeatEdge (const edgeList &edges, const pointField &points, scalar searchSpanSqr, labelList &edgeLabel) const
Find nearest feature edge to each surface edge. Uses the.
void writeDict (Ostream &) const
Write as dictionary.
void write (const fileName &fName) const
Write as dictionary to file.
void writeObj (const fileName &prefix) const
Write to separate OBJ files (region, external, internal edges,.
void operator= (const surfaceFeatures &)
Detailed Description
Holds feature edges/points of surface.
Feature edges are stored in one list and sorted: 0 .. externalStart_-1 : region edges externalStart_ .. internalStart_-1 : external edges internalStart_ .. size-1 : internal edges
NOTE: angle is included angle, not feature angle and is in degrees. The included angle is the smallest angle between two planes. For coplanar faces it is 180, for straight angles it is 90. To pick up straight edges only use included angle of 91 degrees
Source files
surfaceFeatures.H
surfaceFeatures.C
Definition at line 68 of file surfaceFeatures.H.
Member Enumeration Documentation
edgeStatus
enum edgeStatus
Enumerator
NONE
REGION
EXTERNAL
INTERNAL
Definition at line 72 of file surfaceFeatures.H.
Constructor & Destructor Documentation
surfaceFeatures() [1/7]
surfaceFeatures (const triSurface & surf)
Construct from surface.
Definition at line 447 of file surfaceFeatures.C.
Referenced by surfaceFeatures::surfaceFeatures().
surfaceFeatures() [2/7]
surfaceFeatures (const triSurface & surf, const labelList & featurePoints, const labelList & featureEdges, const label externalStart, const label internalStart)
Construct from components.
Definition at line 459 of file surfaceFeatures.C.
References surfaceFeatures::surfaceFeatures().
surfaceFeatures() [3/7]
surfaceFeatures (const triSurface & surf, const scalar includedAngle, const scalar minLen = 0, const label minElems = 0, const bool geometricTestOnly = false)
Construct from surface, angle and min cumulative length and/or.
number of elements. If geometric test only is true, then region information is ignored and features are only assigned based on the geometric criteria
Definition at line 477 of file surfaceFeatures.C.
References surfaceFeatures::findFeatures(), surfaceFeatures::surfaceFeatures(), and surfaceFeatures::trimFeatures().
surfaceFeatures() [4/7]
surfaceFeatures (const triSurface & surf, const dictionary & dict)
Construct from dictionary.
Definition at line 501 of file surfaceFeatures.C.
References surfaceFeatures::surfaceFeatures().
surfaceFeatures() [5/7]
surfaceFeatures (const triSurface & surf, const fileName & fName)
Construct from file.
Definition at line 515 of file surfaceFeatures.C.
References dictionary::lookup(), Foam::readLabel(), and surfaceFeatures::surfaceFeatures().
surfaceFeatures() [6/7]
surfaceFeatures (const triSurface & surf, const pointField & points, const edgeList & edges, const scalar mergeTol = 1e-6, const bool geometricTestOnly = false)
Construct from pointField and edgeList (edgeMesh)
Definition at line 538 of file surfaceFeatures.C.
References List< T >::clear(), PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), HashTableCore::end(), HashTable< T, Key, Hash >::find(), forAll, HashTable< T, edge, Hash< edge > >::insert(), surfaceFeatures::nearestFeatEdge(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), surfaceFeatures::NONE, surfaceFeatures::setFromStatus(), List< T >::size(), and Foam::sqr().
surfaceFeatures() [7/7]
surfaceFeatures (const surfaceFeatures & sf)
Construct as copy.
Definition at line 618 of file surfaceFeatures.C.
References surfaceFeatures::selectFeatureEdges().
Member Function Documentation
ClassName()
ClassName ("surfaceFeatures")
surface()
const triSurface& surface () const inline
Definition at line 227 of file surfaceFeatures.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and surfaceFeatures::operator=().
featurePoints()
const labelList& featurePoints () const inline
Return feature point list.
Definition at line 233 of file surfaceFeatures.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and surfaceFeatures::operator=().
featureEdges()
const labelList& featureEdges () const inline
Return feature edge list.
Definition at line 239 of file surfaceFeatures.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and surfaceFeatures::operator=().
externalStart()
label externalStart () const inline
Start of external edges.
Definition at line 245 of file surfaceFeatures.H.
Referenced by surfaceFeatures::operator=().
internalStart()
label internalStart () const inline
Start of internal edges.
Definition at line 251 of file surfaceFeatures.H.
Referenced by surfaceFeatures::operator=().
nRegionEdges()
label nRegionEdges () const inline
Return number of region edges.
Definition at line 257 of file surfaceFeatures.H.
Referenced by extendedEdgeMesh::extendedEdgeMesh(), and surfaceFeatures::selectFeatureEdges().
nExternalEdges()
label nExternalEdges () const inline
Return number of external edges.
Definition at line 263 of file surfaceFeatures.H.
Referenced by surfaceFeatures::selectFeatureEdges().
nInternalEdges()
label nInternalEdges () const inline
Return number of internal edges.
Definition at line 269 of file surfaceFeatures.H.
References surfaceFeatures::findFeatures(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), surfaceFeatures::operator=(), samples(), surfaceFeatures::selectFeatureEdges(), surfaceFeatures::setFromStatus(), List< T >::size(), surfaceFeatures::toStatus(), surfaceFeatures::trimFeatures(), surfaceFeatures::write(), surfaceFeatures::writeDict(), and surfaceFeatures::writeObj().
Referenced by surfaceFeatures::selectFeatureEdges().
selectFeatureEdges()
Foam::labelList selectFeatureEdges (const bool regionEdges, const bool externalEdges, const bool internalEdges) const
Helper function: select a subset of featureEdges_.
Definition at line 631 of file surfaceFeatures.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), surfaceFeatures::findFeatures(), surfaceFeatures::nExternalEdges(), surfaceFeatures::nInternalEdges(), surfaceFeatures::nRegionEdges(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), and List< T >::size().
Referenced by surfaceFeatures::nInternalEdges(), and surfaceFeatures::surfaceFeatures().
findFeatures()
void findFeatures (const scalar includedAngle, const bool geometricTestOnly)
Find feature edges using provided included angle.
Definition at line 674 of file surfaceFeatures.C.
References Foam::cos(), Foam::degToRad(), PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), surfaceFeatures::NONE, surfaceFeatures::setFromStatus(), and surfaceFeatures::trimFeatures().
Referenced by surfaceFeatures::nInternalEdges(), surfaceFeatures::selectFeatureEdges(), and surfaceFeatures::surfaceFeatures().
trimFeatures()
Foam::labelList trimFeatures (const scalar minLen, const label minElems, const scalar includedAngle)
Delete small sets of edges. Edges are stringed up and any.
string of length < minLen (or nElems < minElems) is deleted.
Definition at line 699 of file surfaceFeatures.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), edge::mag(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), surfaceFeatures::NONE, surfaceFeatures::setFromStatus(), List< T >::size(), and surfaceFeatures::toStatus().
Referenced by surfaceFeatures::findFeatures(), surfaceFeatures::nInternalEdges(), and surfaceFeatures::surfaceFeatures().
toStatus()
Foam::List< Foam::surfaceFeatures::edgeStatus > toStatus () const
From member feature edges to status per edge.
Definition at line 92 of file surfaceFeatures.C.
References surfaceFeatures::setFromStatus().
Referenced by surfaceFeatures::nInternalEdges(), and surfaceFeatures::trimFeatures().
setFromStatus()
void setFromStatus (const List< edgeStatus > & edgeStat, const scalar includedAngle)
Set from status per edge.
Definition at line 121 of file surfaceFeatures.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Vector< Cmpt >::centre(), Foam::cos(), Foam::degToRad(), Foam::e, Foam::endl(), Foam::findIndex(), forAll, UList< T >::last(), edge::mag(), Foam::mag(), Foam::nl, edge::otherVertex(), points, List< T >::size(), and Foam::Warning.
Referenced by surfaceFeatures::findFeatures(), surfaceFeatures::nInternalEdges(), surfaceFeatures::surfaceFeatures(), surfaceFeatures::toStatus(), and surfaceFeatures::trimFeatures().
nearestSamples() [1/2]
Foam::Map< Foam::label > nearestSamples (const labelList & selectedPoints, const pointField & samples, const scalarField & maxDistSqr) const
Find nearest sample for selected surface points.
(usually the set of featurePoints). Return map from index in samples to surface point. Do not include points that are further than maxDist away (separate maxDist for every sample). Supply maxDistSqr.
Definition at line 909 of file surfaceFeatures.C.
References Foam::abort(), indexedOctree< Type >::bb(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIter(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::magSqr(), Foam::Pout, List< T >::size(), and Foam::meshTools::writeOBJ().
Referenced by surfaceFeatures::nInternalEdges(), and surfaceFeatures::writeObj().
nearestSamples() [2/2]
Foam::Map< Foam::label > nearestSamples (const labelList & selectedEdges, const pointField & samples, const scalarField & sampleDist, const scalarField & maxDistSqr, const scalar minSampleDist = 0.1) const
Find nearest sample for regularly sampled points along.
the selected (surface) edges. Return map from sample to edge. maxDistSqr is distance squared below which gets snapped. Edge gets sampled at points sampleDist[sampleI] apart. (with a maximum of 10 samples per edge)
Definition at line 993 of file surfaceFeatures.C.
References Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), Foam::endl(), Foam::exit(), forAll, forAllConstIter(), edge::line(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), Foam::magSqr(), Foam::max(), line< Point, PointRef >::nearestDist(), surfaceFeatures::nearestEdges(), Foam::Pout, s(), List< T >::size(), edge::start(), edge::vec(), and Foam::meshTools::writeOBJ().
nearestEdges()
Foam::Map< Foam::pointIndexHit > nearestEdges (const labelList & selectedEdges, const edgeList & sampleEdges, const labelList & selectedSampleEdges, const pointField & samplePoints, const scalarField & sampleDist, const scalarField & maxDistSqr, const scalar minSampleDist = 0.1) const
Like nearestSamples but now gets nearest point on.
sample-edge instead of nearest sample-point itself. Return map from sample edge to feature edge.
Definition at line 1129 of file surfaceFeatures.C.
References edge::centre(), Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), Foam::endl(), Foam::exit(), forAll, forAllConstIter(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), Foam::magSqr(), Foam::max(), surfaceFeatures::nearestSurfEdge(), Foam::Pout, s(), indexedOctree< Type >::shapes(), List< T >::size(), edge::start(), edge::vec(), and Foam::meshTools::writeOBJ().
Referenced by surfaceFeatures::nearestSamples(), and surfaceFeatures::nInternalEdges().
nearestSurfEdge() [1/2]
void nearestSurfEdge (const labelList & selectedEdges, const pointField & samples, scalar searchSpanSqr, labelList & edgeLabel, labelList & edgeEndPoint, pointField & edgePoint) const
Find nearest surface edge (out of selectedEdges) for.
each sample point. Sets:
edgeLabel : label of surface edge.
edgePoint : exact position of nearest point on edge.
edgeEndPoint : -1, 0, 1 depending on whether edgePoint is on inside/start/end of edge
Definition at line 1280 of file surfaceFeatures.C.
References Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), edge::end(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), boundBox::inflate(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), PointIndexHit< Point >::rawPoint(), List< T >::setSize(), List< T >::size(), and edge::start().
Referenced by surfaceFeatures::nearestEdges(), and surfaceFeatures::nInternalEdges().
nearestSurfEdge() [2/2]
void nearestSurfEdge (const labelList & selectedEdges, const edgeList & sampleEdges, const labelList & selectedSampleEdges, const pointField & samplePoints, const vector & searchSpan, labelList & edgeLabel, pointField & pointOnEdge, pointField & pointOnFeature) const
Find nearest surface edge (out of selectedEdges) for each.
sample edge. Sets:
edgeLabel : label of surface edge.
pointOnEdge : exact position of nearest point on edge.
pointOnFeature : exact position on sample edge.
Definition at line 1350 of file surfaceFeatures.C.
References line< Point, PointRef >::centre(), Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), PointIndexHit< Point >::index(), edge::line(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), surfaceFeatures::nearestFeatEdge(), List< T >::setSize(), and List< T >::size().
nearestFeatEdge()
void nearestFeatEdge (const edgeList & edges, const pointField & points, scalar searchSpanSqr, labelList & edgeLabel) const
Find nearest feature edge to each surface edge. Uses the.
mid-point of the surface edges.
Definition at line 1416 of file surfaceFeatures.C.
References edge::centre(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), forAll, PointIndexHit< Point >::hit(), Foam::identity(), PointIndexHit< Point >::index(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), List< T >::size(), edge::start(), and edge::vec().
Referenced by surfaceFeatures::nearestSurfEdge(), surfaceFeatures::nInternalEdges(), and surfaceFeatures::surfaceFeatures().
writeDict()
void writeDict (Ostream & writeFile) const
Write as dictionary.
Definition at line 832 of file surfaceFeatures.C.
References dictionary::add(), and dictionary::write().
Referenced by surfaceFeatures::nInternalEdges(), and surfaceFeatures::write().
write()
void write (const fileName & fName) const
Write as dictionary to file.
Definition at line 845 of file surfaceFeatures.C.
References surfaceFeatures::writeDict().
Referenced by surfaceFeatures::nInternalEdges().
writeObj()
void writeObj (const fileName & prefix) const
Write to separate OBJ files (region, external, internal edges,.
feature points) for visualization
Definition at line 853 of file surfaceFeatures.C.
References Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), Foam::endl(), forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), OFstream::name(), surfaceFeatures::nearestSamples(), Foam::Pout, List< T >::size(), and Foam::meshTools::writeOBJ().
Referenced by surfaceFeatures::nInternalEdges().
operator=()
void operator= (const surfaceFeatures & rhs)
Definition at line 1478 of file surfaceFeatures.C.
References Foam::abort(), surfaceFeatures::externalStart(), Foam::FatalError, FatalErrorInFunction, surfaceFeatures::featureEdges(), surfaceFeatures::featurePoints(), surfaceFeatures::internalStart(), and surfaceFeatures::surface().
Referenced by surfaceFeatures::nInternalEdges().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/surfaceFeatures/surfaceFeatures.H
src/meshTools/triSurface/surfaceFeatures/surfaceFeatures.C