OpenFOAM: Rosenbrock34 Class Reference
Rosenbrock34 Class Reference
L-stable embedded Rosenbrock ODE solver of order (3)4.
Public Member Functions
TypeName ("Rosenbrock34")
Runtime type information.
Rosenbrock34 (const ODESystem &ode, const dictionary &dict)
Construct from ODESystem.
virtual ~Rosenbrock34 ()
Destructor.
virtual bool resize ()
Resize the ODE solver.
virtual scalar solve (const scalar x0, const scalarField &y0, const scalarField &dydx0, const scalar dx, scalarField &y) const
Solve a single step dx and return the error.
virtual void solve (scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system and the update the state.
Public Member Functions inherited from ODESolver
TypeName ("ODESolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
Construct for given ODESystem.
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
Construct for given ODESystem specifying tolerances.
virtual ~ODESolver ()
Destructor.
label nEqns () const
Return the number of equations to solve.
scalarField & absTol ()
Return access to the absolute tolerance field.
scalarField & relTol ()
Return access to the relative tolerance field.
template<class Type >
void resizeField (UList< Type > &f) const
void resizeMatrix (scalarSquareMatrix &m) const
virtual void solve (scalar &x, scalarField &y, stepState &step) const
Solve the ODE system as far as possible upto dxTry.
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Solve the ODE system from xStart to xEnd, update the state.
Public Member Functions inherited from adaptiveSolver
adaptiveSolver (const ODESystem &ode, const dictionary &dict)
Construct from ODESystem.
virtual ~adaptiveSolver ()
Destructor.
bool resize (const label n)
Resize the ODE solver.
void solve (const ODESystem &ode, scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system and the update the state.
Additional Inherited Members
Static Public Member Functions inherited from ODESolver
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
Select null constructed.
template<class Type >
static void resizeField (UList< Type > &f, const label n)
Protected Member Functions inherited from ODESolver
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
Return the nomalized scalar error.
ODESolver (const ODESolver &)
Disallow default bitwise copy construct.
void operator= (const ODESolver &)
Disallow default bitwise assignment.
Protected Attributes inherited from ODESolver
const ODESystem & odes_
Reference to ODESystem.
const label maxN_
Maximum size of the ODESystem.
label n_
Size of the ODESystem (adjustable)
scalarField absTol_
Absolute convergence tolerance per step.
scalarField relTol_
Relative convergence tolerance per step.
label maxSteps_
The maximum number of sub-steps allowed for the integration step.
Detailed Description
L-stable embedded Rosenbrock ODE solver of order (3)4.
    Hairer, E., Nørsett, S. P., & Wanner, G. (1996).
    Solving Ordinary Differential Equations II:
    Stiff and Differential-Algebraic Problems, second edition",
    Springer-Verlag, Berlin.
The default constants are from:
    Shampine, L. F. (1982).
    Implementation of Rosenbrock Methods.
    ACM Transactions on Mathematical Software, vol. 8, pp. 93–113.
with which the scheme is more accurate than with the L-Stable coefficients for small step-size but less stable for large step-size.
The L-Stable scheme constants are provided commented-out in Rosenbrock34.C
Source files
Rosenbrock34.H
Rosenbrock34.C
Definition at line 67 of file Rosenbrock34.H.
Constructor & Destructor Documentation
Rosenbrock34()
Rosenbrock34 (const ODESystem & ode, const dictionary & dict)
Construct from ODESystem.
Definition at line 108 of file Rosenbrock34.C.
~Rosenbrock34()
virtual ~Rosenbrock34 () inline virtual
Destructor.
Definition at line 109 of file Rosenbrock34.H.
References Rosenbrock34::resize(), Rosenbrock34::solve(), ODESolver::solve(), x, y, and Foam::y0().
Member Function Documentation
TypeName()
TypeName ("Rosenbrock34")
Runtime type information.
resize()
bool resize () virtual
Resize the ODE solver.
Implements ODESolver.
Definition at line 127 of file Rosenbrock34.C.
References ODESolver::n_, adaptiveSolver::resize(), ODESolver::resize(), ODESolver::resizeField(), ODESolver::resizeMatrix(), and Rosenbrock34::solve().
Referenced by Rosenbrock34::~Rosenbrock34().
solve() [1/2]
Foam::scalar solve (const scalar x0, const scalarField & y0, const scalarField & dydx0, const scalar dx, scalarField & y) const virtual
Solve a single step dx and return the error.
Implements adaptiveSolver.
Definition at line 154 of file Rosenbrock34.C.
References ODESystem::derivatives(), forAll, ODESystem::jacobian(), Foam::LUBacksubstitute(), Foam::LUDecompose(), ODESolver::n_, ODESolver::normalizeError(), and ODESolver::odes_.
Referenced by Rosenbrock34::resize(), and Rosenbrock34::~Rosenbrock34().
solve() [2/2]
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Solve the ODE system and the update the state.
Reimplemented from ODESolver.
Definition at line 235 of file Rosenbrock34.C.
References ODESolver::odes_, and adaptiveSolver::solve().
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/Rosenbrock34/Rosenbrock34.H
src/ODE/ODESolvers/Rosenbrock34/Rosenbrock34.C