OpenFOAM: treeDataCell::findIntersectOp Class Reference
treeDataCell::findIntersectOp Class Reference
Public Member Functions
findIntersectOp (const indexedOctree< treeDataCell > &tree)
bool operator() (const label index, const point &start, const point &end, point &intersectionPoint) const
Detailed Description
Definition at line 115 of file treeDataCell.H.
Constructor & Destructor Documentation
findIntersectOp()
findIntersectOp (const indexedOctree< treeDataCell > & tree)
Definition at line 146 of file treeDataCell.C.
Referenced by treeDataCell::findNearestOp::findNearestOp().
Member Function Documentation
operator()()
bool operator() (const label index, const point & start, const point & end, point & intersectionPoint) const
Definition at line 240 of file treeDataCell.C.
References primitiveMesh::cells(), PointHit< Point >::distance(), polyMesh::faces(), forAll, intersection::HALF_RAY, PointHit< Point >::hit(), PointHit< Point >::hitPoint(), Foam::magSqr(), polyMesh::points(), treeBoundBox::posBits(), face::ray(), intersection::setPlanarTol(), and Foam::sqr().
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.H
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.C