OpenFOAM: labelBits Class Reference
labelBits Class Reference
A 29bits label and 3bits direction packed into single label.
Public Member Functions
labelBits ()
Construct null.
labelBits (const label val, const direction bits)
Construct from components.
labelBits (Istream &is)
Construct from Istream.
label val () const
direction bits () const
void setVal (const label val)
void setBits (const direction bits)
Friends
bool operator== (const labelBits &a, const labelBits &b)
bool operator!= (const labelBits &a, const labelBits &b)
Istream & operator>> (Istream &is, labelBits &lb)
Ostream & operator<< (Ostream &os, const labelBits &lb)
Detailed Description
A 29bits label and 3bits direction packed into single label.
Source files
labelBits.H
Definition at line 51 of file labelBits.H.
Constructor & Destructor Documentation
labelBits() [1/3]
labelBits () inline
Construct null.
Definition at line 78 of file labelBits.H.
labelBits() [2/3]
labelBits (const label val, const direction bits) inline
Construct from components.
Definition at line 82 of file labelBits.H.
labelBits() [3/3]
labelBits (Istream & is) inline
Construct from Istream.
Definition at line 88 of file labelBits.H.
Member Function Documentation
val()
label val () const inline
Definition at line 97 of file labelBits.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getContent(), indexedOctree< Foam::treeDataFace >::getContent(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getNode(), indexedOctree< Foam::treeDataFace >::getNode(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::isContent(), indexedOctree< Foam::treeDataFace >::isContent(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::isEmpty(), indexedOctree< Foam::treeDataFace >::isEmpty(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::isNode(), indexedOctree< Foam::treeDataFace >::isNode(), and labelBits::setBits().
bits()
direction bits () const inline
Definition at line 102 of file labelBits.H.
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::getOctant(), indexedOctree< Foam::treeDataFace >::getOctant(), and labelBits::setVal().
setVal()
void setVal (const label val) inline
Definition at line 107 of file labelBits.H.
References labelBits::bits().
setBits()
void setBits (const direction bits) inline
Definition at line 112 of file labelBits.H.
References labelBits::val().
Friends And Related Function Documentation
operator==
bool operator== (const labelBits & a, const labelBits & b) friend
Definition at line 120 of file labelBits.H.
operator!=
bool operator!= (const labelBits & a, const labelBits & b) friend
Definition at line 125 of file labelBits.H.
operator>>
Istream& operator>> (Istream & is, labelBits & lb) friend
Definition at line 132 of file labelBits.H.
operator<<
Ostream& operator<< (Ostream & os, const labelBits & lb) friend
Definition at line 137 of file labelBits.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/algorithms/indexedOctree/labelBits.H