OpenFOAM: ODESystem Class Reference
ODESystem Class Reference abstract
Abstract base class for the systems of ordinary differential equations.
Public Member Functions
ODESystem ()
Construct null.
virtual ~ODESystem ()
Destructor.
virtual label nEqns () const =0
Return the number of equations in the system.
virtual void derivatives (const scalar x, const scalarField &y, scalarField &dydx) const =0
Calculate the derivatives in dydx.
virtual void jacobian (const scalar x, const scalarField &y, scalarField &dfdx, scalarSquareMatrix &dfdy) const =0
Calculate the Jacobian of the system.
Detailed Description
Abstract base class for the systems of ordinary differential equations.
Definition at line 46 of file ODESystem.H.
Constructor & Destructor Documentation
ODESystem()
ODESystem () inline
Construct null.
Definition at line 54 of file ODESystem.H.
~ODESystem()
virtual ~ODESystem () inline virtual
Destructor.
Definition at line 59 of file ODESystem.H.
References ODESystem::derivatives(), ODESystem::jacobian(), ODESystem::nEqns(), x, and y.
Member Function Documentation
nEqns()
virtual label nEqns () const pure virtual
Return the number of equations in the system.
Implemented in chemistryModel< CompType, ThermoType >, solidChemistryModel< CompType, SolidThermo >, and pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
Referenced by ODESolver::resize(), and ODESystem::~ODESystem().
derivatives()
virtual void derivatives (const scalar x, const scalarField & y, scalarField & dydx) const pure virtual
Calculate the derivatives in dydx.
Implemented in chemistryModel< CompType, ThermoType >, solidChemistryModel< CompType, SolidThermo >, pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >, and TDACChemistryModel< CompType, ThermoType >.
Referenced by seulex::seulex(), Trapezoid::solve(), adaptiveSolver::solve(), Rosenbrock12::solve(), Rosenbrock23::solve(), rodas23::solve(), RKCK45::solve(), rodas34::solve(), RKDP45::solve(), RKF45::solve(), Rosenbrock34::solve(), SIBS::solve(), and ODESystem::~ODESystem().
jacobian()
virtual void jacobian (const scalar x, const scalarField & y, scalarField & dfdx, scalarSquareMatrix & dfdy) const pure virtual
Calculate the Jacobian of the system.
Need by the stiff-system solvers
Implemented in chemistryModel< CompType, ThermoType >, solidChemistryModel< CompType, SolidThermo >, pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >, and TDACChemistryModel< CompType, ThermoType >.
Referenced by EulerSI::solve(), Rosenbrock12::solve(), rodas23::solve(), Rosenbrock23::solve(), rodas34::solve(), Rosenbrock34::solve(), SIBS::solve(), seulex::solve(), and ODESystem::~ODESystem().
The documentation for this class was generated from the following file:
src/ODE/ODESystem/ODESystem.H