OpenFOAM: treeDataCell::findNearestOp Class Reference
treeDataCell::findNearestOp Class Reference
Public Member Functions
findNearestOp (const indexedOctree< treeDataCell > &tree)
void operator() (const labelUList &indices, const point &sample, scalar &nearestDistSqr, label &minIndex, point &nearestPoint) const
void operator() (const labelUList &indices, const linePointRef &ln, treeBoundBox &tightest, label &minIndex, point &linePoint, point &nearestPoint) const
Detailed Description
Definition at line 84 of file treeDataCell.H.
Constructor & Destructor Documentation
findNearestOp()
findNearestOp (const indexedOctree< treeDataCell > & tree)
Definition at line 137 of file treeDataCell.C.
References treeDataCell::findIntersectOp::findIntersectOp().
Referenced by treeDataCell::treeDataCell().
Member Function Documentation
operator()() [1/2]
void operator() (const labelUList & indices, const point & sample, scalar & nearestDistSqr, label & minIndex, point & nearestPoint) const
Definition at line 197 of file treeDataCell.C.
References primitiveMesh::cellCentres(), treeDataCell::cellLabels(), forAll, Foam::magSqr(), and treeDataCell::mesh().
operator()() [2/2]
void operator() (const labelUList & indices, const linePointRef & ln, treeBoundBox & tightest, label & minIndex, point & linePoint, point & nearestPoint) const
Definition at line 225 of file treeDataCell.C.
References NotImplemented.
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.H
src/OpenFOAM/algorithms/indexedOctree/treeDataCell.C