OpenFOAM: List< T > Class Template Reference
List< T > Class Template Reference
A 1D array of objects of type <T>, where the size of the vector is known and used for subscript bounds checking, etc.
Inherits UList< T >.
Inherited by DynamicList< autoPtr< DynamicList< label > > >, DynamicList< fileState >, DynamicList< Foam::CompactSpatialTensor >, DynamicList< Foam::dynamicIndexedOctree::node >, DynamicList< Foam::fileName >, DynamicList< Foam::Foam::Vector >, DynamicList< Foam::List< Foam::UPstream::commsStruct > >, DynamicList< Foam::List< int > >, DynamicList< Foam::PairCollisionRecord< PairType > >, DynamicList< Foam::PairCollisionRecord< vector > >, DynamicList< Foam::refinementHistory::splitCell8 >, DynamicList< Foam::SpatialTensor >, DynamicList< Foam::Tuple2 >, DynamicList< Foam::WallCollisionRecord< vector > >, DynamicList< Foam::WallCollisionRecord< WallType > >, DynamicList< labelRange >, DynamicList< time_t >, DynamicList< void *>, Field< complexVector >, Field< DType >, Field< Foam::Field< Type > >, Field< Foam::SymmTensor >, Field< Foam::Vector2D >, Field< LUType >, Field< point >, Field< PointType >, Field< symmTensor >, Field< T >, Field< tensor >, Field< TypeGrad >, BinSum< IndexType, List, CombineOp >, cellClassification, cellToCellStencil, CompactIOList< T, BaseType >, DynamicList< T, SizeInc, SizeMult, SizeDiv >, faceToCellStencil, faceTriangulation, IOList< T >, ITstream, ProcessorTopology< Container, ProcPatch >, pTraits< List< T > >, SortableList< T >, surfacePatchIOList, surfZoneIOList, and zone.
Public Types
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions
void size (const label)
Override size to be inconsistent with allocated storage.
Friends
Istream & operator>> (Istream &, List< T > &)
Read List from Istream, discarding contents of existing List.
Detailed Description
template<class T>
class Foam::List< T >
A 1D array of objects of type <T>, where the size of the vector is known and used for subscript bounds checking, etc.
Storage is allocated on free-store during construction.
Source files
List.H
List.C
ListI.H
ListIO.C
Definition at line 60 of file HashTable.H.
Member Typedef Documentation
subList
typedef SubList<T> subList
Declare type of subList.
Definition at line 192 of file List.H.
Constructor & Destructor Documentation
List() [1/17]
List () inline
Null constructor.
Definition at line 103 of file ListI.H.
List() [2/17]
List (const label s) explicit
Construct with given size.
Definition at line 39 of file List.C.
List() [3/17]
List (const label s, const T & a)
Construct with given size and value for all elements.
Definition at line 55 of file List.C.
List() [4/17]
List (const label s, const zero)
Construct with given size initializing all elements to zero.
Definition at line 79 of file List.C.
List() [5/17]
List (const List< T > & a)
Copy constructor.
Definition at line 103 of file List.C.
List() [6/17]
List (const List< T2 > & a) explicit
Copy constructor from list containing another type.
Definition at line 131 of file List.C.
List() [7/17]
List (const Xfer< List< T >> & lst)
Construct by transferring the parameter contents.
Definition at line 149 of file List.C.
List() [8/17]
List (List< T > & a, bool reuse)
Construct as copy or re-use as specified.
Definition at line 156 of file List.C.
List() [9/17]
List (const UList< T > & a, const labelUList< T > & mapAddressing)
Construct as subset.
Definition at line 189 of file List.C.
List() [10/17]
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
Definition at line 209 of file List.C.
List() [11/17]
List (const FixedList< T, Size > & lst) explicit
Construct as copy of FixedList<T, Size>
Definition at line 217 of file List.C.
List() [12/17]
List (const PtrList< T > & lst) explicit
Construct as copy of PtrList<T>
Definition at line 226 of file List.C.
List() [13/17]
List (const SLList< T > & lst) explicit
Construct as copy of SLList<T>
Definition at line 235 of file List.C.
List() [14/17]
List (const UIndirectList< T > & lst) explicit
Construct as copy of UIndirectList<T>
Definition at line 242 of file List.C.
List() [15/17]
List (const BiIndirectList< T > & lst) explicit
Construct as copy of BiIndirectList<T>
Definition at line 251 of file List.C.
List() [16/17]
List (std::initializer_list< T > lst)
Construct from an initializer list.
Definition at line 260 of file List.C.
List() [17/17]
List (Istream & is)
Construct from Istream.
Definition at line 35 of file ListIO.C.
~List()
~List ()
Destructor.
Definition at line 269 of file List.C.
Member Function Documentation
size() [1/2]
void size (const label n) inline protected
Override size to be inconsistent with allocated storage.
Use with care
Definition at line 163 of file ListI.H.
Referenced by wideBandAbsorptionEmission::aCont(), isoSurface::adaptPatchFields(), preserveBafflesConstraint::add(), extendedEdgeMesh::add(), polyTopoChange::addCell(), cellTable::addCellZones(), surfaceZonesInfo::addCellZonesToMesh(), addPatchCellLayer::addedCells(), mapPatchChange::addedPatches(), surfaceZonesInfo::addFaceZonesToMesh(), edgeSurface::addIntersectionEdges(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), polyMesh::addPatches(), faceZoneSet::addSet(), interRegionExplicitPorositySource::addSup(), polyTopoChanger::addTopologyModifiers(), fileMonitor::addWatch(), fileMonitorWatcher::addWatch(), MeshedSurface< Foam::face >::addZones(), polyMesh::addZones(), primitiveMeshGeometry::affectedCells(), polyMeshGeometry::affectedCells(), singleCellFvMesh::agglomerate(), GAMGInterface::agglomerateCoeffs(), GAMGAgglomeration::agglomerateLduAddressing(), extendedEdgeMesh::allNearestFeaturePoints(), UPstream::allocateCommunicator(), AMIInterpolation< SourcePatch, TargetPatch >::AMIInterpolation(), curvedEdge::appendEndPoints(), directMethod::appendToDirectSeeds(), searchableSurfaceToFaceZone::applyToSet(), setToCellZone::applyToSet(), faceZoneToFaceZone::applyToSet(), setToPointZone::applyToSet(), setToFaceZone::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), face::areaInContact(), argList::argList(), pressureInletOutletVelocityFvPatchVectorField::autoMap(), Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), snappySnapDriver::avgCellCentres(), meshRefinement::baffleAndSplitMesh(), binaryTree< CompType, ThermoType >::balance(), meshRefinement::balance(), meshRefinement::balanceAndRefine(), Foam::bandCompression(), binaryTree< CompType, ThermoType >::binaryTreeSearch(), bladeModel::bladeModel(), blockDescriptor::blockDescriptor(), booleanSurface::booleanSurface(), GeometricField< Type, PatchField, GeoMesh >::Boundary::Boundary(), searchableSurfaceCollection::boundingSpheres(), searchableSurfacesQueries::bounds(), tetherPotentialList::buildPotentials(), pairPotentialList::buildPotentials(), cachedRandom::cachedRandom(), faceZone::calcCellLayers(), primitiveMesh::calcCells(), enrichedPatch::calcEnrichedFaces(), polyDualMesh::calcFeatures(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), fixedCoeff::calcForce(), powerLaw::calcForce(), DarcyForchheimer::calcForce(), forces::calcForcesMoment(), faceLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), triSurfaceSearch::calcInside(), triSurfaceTools::calcInterpolationWeights(), TDILUPreconditioner< Type, DType, LUType >::calcInvD(), cellMatcher::calcLocalFaces(), zone::calcLookupMap(), mappedPatchBase::calcMapping(), fieldMinMax::calcMinMaxFields(), snappySnapDriver::calcNearestSurface(), polyLine::calcParam(), primitiveMesh::calcPointOrder(), createShellMesh::calcPointRegions(), DICPreconditioner::calcReciprocalD(), DILUPreconditioner::calcReciprocalD(), addPatchCellLayer::calcSidePatch(), snappySnapDriver::calcSnapDistance(), fixedCoeff::calcTransformModelData(), DarcyForchheimer::calcTransformModelData(), cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), coupledPolyPatch::calcTransformTensors(), directAMI< SourcePatch, TargetPatch >::calculate(), mapNearestAMI< SourcePatch, TargetPatch >::calculate(), viewFactor::calculate(), mapNearestMethod::calculateAddressing(), meshRefinement::calculateEdgeWeights(), GAMGAgglomeration::calculateRegionMaster(), pointMVCWeight::calcWeights(), edgeMesh::canRead(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), hexRef8::cellShapes(), polyMeshTetDecomposition::cellTetIndices(), dynamicRefineFvMesh::cellToPoint(), cellModel::centre(), repatchPolyTopoChanger::changeAnchorPoint(), boundaryMesh::changeFaces(), polyTopoChange::changeMesh(), repatchPolyTopoChanger::changePatchID(), layerAdditionRemoval::changeTopology(), TableBase< Type >::check(), argList::check(), faceZone::checkAddressing(), primitiveMesh::checkCellsZipUp(), primitiveMesh::checkClosedBoundary(), primitiveMesh::checkCommonOrder(), primitiveMesh::checkDuplicateFaces(), triSurface::checkEdges(), primitiveMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceFlatness(), primitiveMesh::checkFaceOrthogonality(), MeshedSurface< Foam::face >::checkFaces(), primitiveMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceTwist(), primitiveMesh::checkFaceVertices(), searchableSurfaces::checkIntersection(), hexRef8::checkMesh(), edgeCollapser::checkMeshQuality(), searchableSurfaces::checkNormalOrientation(), PatchTools::checkOrientation(), ZoneMesh< cellZone, polyMesh >::checkParallelSync(), polyBoundaryMesh::checkParallelSync(), PrimitivePatch< Face, ::Foam::List, pointField, point >::checkPointManifold(), primitiveMesh::checkPointNearness(), hexRef8::checkRefinementLevels(), GAMGAgglomeration::checkRestriction(), ReactingCloud< Foam::DSMCCloud >::checkSuppliedComposition(), timeVaryingMappedFixedValueFvPatchField< Type >::checkTable(), PrimitivePatch< Face, ::Foam::List, pointField, point >::checkTopology(), triSurface::checkTriangles(), polyMeshGeometry::checkTriangleTwist(), primitiveMesh::checkUpperTriangular(), MeshedSurface< Foam::face >::checkZones(), surfMesh::checkZones(), ensightPartFaces::classify(), extendedEdgeMesh::classifyEdge(), extendedEdgeMesh::classifyFeaturePoint(), sampledSurface::clearGeom(), refinementHistory::clone(), cellShape::collapsedFaces(), triSurfaceTools::collapseEdges(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), mappedPatchBase::collectSamples(), CollisionRecordList< vector, vector >::CollisionRecordList(), commSchedule::commSchedule(), UPstream::commsStruct::commsStruct(), mapDistributeBase::compact(), refinementHistory::compact(), CompactListList< T, Container >::CompactListList(), face::compare(), removeFaces::compatibleRemoves(), edgeCollapser::consistentCollapse(), hexRef8::consistentSlowRefinement(), hexRef8::consistentSlowRefinement2(), molecule::constantProperties::constantProperties(), polyMeshFilter::copyMesh(), Foam::MULES::correct(), inversePointDistanceDiffusivity::correct(), patchInjection::correct(), limitTemperature::correct(), particle< Type >::correctAfterParallelTransfer(), cellDistFuncs::correctBoundaryPointCells(), ReactingParcel< ParcelType >::correctSurfaceValues(), removePoints::countPointUsage(), cyclicPolyPatch::coupledEdges(), globalMeshData::coupledPatchMeshEdgeMap(), cyclicPolyPatch::coupledPoints(), Foam::cp(), heThermo< BasicSolidThermo, MixtureType >::Cp(), heThermo< BasicSolidThermo, MixtureType >::CpByCpv(), heThermo< BasicSolidThermo, MixtureType >::Cpv(), meshRefinement::createBaffles(), Keyed< T >::createList(), createShellMesh::createShellMesh(), meshRefinement::createZoneBaffles(), particle< Type >::crossEdgeConnectedFace(), csvTableReader< Type >::csvTableReader(), STARCD::cullPoints(), displacementInterpolationMotionSolver::curPoints(), wallBoundedParticle::currentEdge(), curvatureSeparation::curvatureSeparation(), hexCellLooper::cut(), cuttingPlane::cut(), geomCellLooper::cut(), topoCellLooper::cut(), Foam::meshTools::cutDirToEdge(), heThermo< BasicSolidThermo, MixtureType >::Cv(), Foam::cwd(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), cyclicGAMGInterface::cyclicGAMGInterface(), noDecomp::decompose(), manualDecomp::decompose(), structuredDecomp::decompose(), simpleGeomDecomp::decompose(), multiLevelDecomp::decompose(), decompositionMethod::decompose(), hierarchGeomDecomp::decompose(), triSurfaceTools::delaunay2D(), cellZoneSet::deleteSet(), pointZoneSet::deleteSet(), faceZoneSet::deleteSet(), cyclicFvPatch::delta(), cyclicAMIFvPatch::delta(), cyclicACMIFvPatch::delta(), dimensionSets::dimensionSets(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), fvMeshDistribute::distribute(), refinementHistory::distribute(), mapDistributeBase::distribute(), distributedTriSurfaceMesh::distribute(), mapDistribute::distribute(), Foam::dlLoaded(), snappyLayerDriver::doLayers(), meshRefinement::doRemovePoints(), meshRefinement::doRestorePoints(), meshRefinement::dumpIntersections(), Foam::duplicateOrder(), dynamicRefineFvMesh::dynamicRefineFvMesh(), extendedEdgeMesh::edgeBaffles(), primitiveMesh::edgeFaces(), extendedEdgeMesh::edgeNormals(), PatchTools::edgeOwner(), cellModel::edges(), face::edges(), triSurfaceTools::edgeSide(), edgeSurface::edgeSurface(), directionInfo::edgeToFaceIndex(), triSurfaceMesh::edgeTree(), globalIndexAndTransform::encodeTransformIndex(), energyJumpAMIFvPatchScalarField::energyJumpAMIFvPatchScalarField(), energyJumpFvPatchScalarField::energyJumpFvPatchScalarField(), directionInfo::enterDomain(), StaticHashTable< T, Key, Hash >::erase(), dynamicRefineFvMesh::error(), mapDistributeBase::exchangeAddressing(), extendedEdgeMesh::extendedEdgeMesh(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extrudePatchMesh::extrudePatchMesh(), faceCoupleInfo::faceCoupleInfo(), primitiveMesh::faceEdges(), primitiveMeshTools::faceFlatness(), fvMeshSubset::faceFlipMap(), lduMatrix::faceH(), LduMatrix< Type, DType, LUType >::faceH(), hexRef8::faceLevel(), mappedPatchBase::facePoint(), FacePostProcessing< CloudType >::FacePostProcessing(), cellModel::faces(), sampledIsoSurfaceCell::faces(), sampledCuttingPlane::faces(), distanceSurface::faces(), sampledIsoSurface::faces(), searchableSurfacesQueries::facesIntersection(), hexMatcher::faceSizeMatch(), prismMatcher::faceSizeMatch(), pyrMatcher::faceSizeMatch(), tetMatcher::faceSizeMatch(), tetWedgeMatcher::faceSizeMatch(), wedgeMatcher::faceSizeMatch(), polyMeshTetDecomposition::faceTetIndices(), OppositeFaceCellWave< Type, TrackingData >::faceToCell(), PrimitivePatchInterpolation< Foam::PrimitivePatch >::faceToEdgeInterpolate(), featureEdgeMesh::featureEdgeMesh(), extendedEdgeMesh::featurePointNormals(), Foam::fftRenumberRecurse(), cellClassification::fillRegionEdges(), refinementSurfaces::findAllHigherIntersections(), searchableSurfacesQueries::findAllIntersections(), searchableSurfacesQueries::findAnyIntersection(), polyMeshTetDecomposition::findBasePoint(), refinementParameters::findCells(), Time::findClosestTime(), patchProbes::findElements(), Foam::findEtcFile(), polyMeshTetDecomposition::findFaceBasePts(), refinementSurfaces::findHigherIntersection(), cellVolumeWeightMethod::findInitialSeeds(), mapNearestMethod::findInitialSeeds(), directMethod::findInitialSeeds(), refinementSurfaces::findInside(), Time::findInstance(), triSurfaceSearch::findLine(), searchablePlane::findLine(), searchableSphere::findLine(), searchablePlate::findLine(), searchableDisk::findLine(), searchableCylinder::findLine(), searchableSurfaceWithGaps::findLine(), searchableSurfaceCollection::findLine(), searchableBox::findLine(), triSurfaceSearch::findLineAll(), searchablePlane::findLineAll(), searchableSphere::findLineAll(), searchablePlate::findLineAll(), searchableDisk::findLineAll(), searchableCylinder::findLineAll(), searchableSurfaceWithGaps::findLineAll(), searchableSurfaceCollection::findLineAll(), searchableBox::findLineAll(), distributedTriSurfaceMesh::findLineAll(), triSurfaceSearch::findLineAny(), searchableSphere::findLineAny(), searchableCylinder::findLineAny(), searchableBox::findLineAny(), mapNearestMethod::findMappedSrcCell(), triSurfaceRegionSearch::findNearest(), triSurfaceSearch::findNearest(), searchablePlane::findNearest(), searchableSphere::findNearest(), searchablePlate::findNearest(), searchableDisk::findNearest(), searchableSurfacesQueries::findNearest(), searchableCylinder::findNearest(), searchableBox::findNearest(), distributedTriSurfaceMesh::findNearest(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), mapNearestMethod::findNearestCell(), primitiveMesh::findNearestCell(), refinementFeatures::findNearestEdge(), searchableSurfacesQueries::findNearestIntersection(), refinementSurfaces::findNearestIntersection(), refinementFeatures::findNearestPoint(), refinementSurfaces::findNearestRegion(), refinementFeatures::findNearestRegionEdge(), mappedPatchBase::findSamples(), polyMeshTetDecomposition::findSharedBasePoint(), polyMeshAdder::findSharedPoints(), polyMeshTetDecomposition::findTet(), pointToPointPlanarInterpolation::findTime(), Time::findTimes(), extendedEdgeMesh::flipNormals(), faceCorrectedSnGrad< Type >::fullGradCorrection(), GAMGSolver::GAMGSolver(), heThermo< BasicSolidThermo, MixtureType >::gamma(), globalIndex::gather(), lduPrimitiveMesh::gather(), PatchTools::gatherAndMerge(), GAMGAgglomeration::gatherList(), Pstream::gatherList(), gaussConvectionScheme< Type >::gaussConvectionScheme(), isoSurface::generateFaceTriPoints(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), triSurfaceMesh::getField(), searchableSurfaceCollection::getField(), distributedTriSurfaceMesh::getField(), surfaceFieldValue::getFieldValues(), edgeMeshFormatsCore::getLineNoComment(), surfaceFormatsCore::getLineNoComment(), meshRefinement::getMasterEdges(), meshRefinement::getMasterPoints(), combineFaces::getMergeSets(), boundaryMesh::getNearest(), searchablePlane::getNormal(), searchableSphere::getNormal(), searchablePlate::getNormal(), searchableDisk::getNormal(), searchableCylinder::getNormal(), searchableSurfaceCollection::getNormal(), searchableBox::getNormal(), triSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getNormal(), combineFaces::getOutsideFace(), cellDistFuncs::getPointNeighbours(), triSurfaceMeshPointSet::getRefPoint(), searchablePlane::getRegion(), searchableSphere::getRegion(), searchablePlate::getRegion(), searchableDisk::getRegion(), searchableCylinder::getRegion(), searchableSurfaceCollection::getRegion(), searchableBox::getRegion(), triSurfaceMesh::getRegion(), distributedTriSurfaceMesh::getRegion(), coupledPolyPatch::getRotation(), hexRef8::getSplitPoints(), removePoints::getUnrefimentSet(), cellLooper::getVertEdgesNonFace(), triSurfaceTools::getVertexTriangles(), cellLooper::getVertFacesNonEdge(), searchableSphere::getVolumeType(), searchableCylinder::getVolumeType(), searchableBox::getVolumeType(), triSurfaceMesh::getVolumeType(), addPatchCellLayer::globalEdgeFaces(), cylindricalCS::globalToLocal(), triSurfaceTools::greenRefine(), chemPointISAT< CompType, ThermoType >::grow(), lduMatrix::H(), lduMatrix::H1(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), FaceCellWave< Type, TrackingData >::handleProcPatches(), mapPolyMesh::hasMotionPoints(), heThermo< BasicSolidThermo, MixtureType >::he(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), hexRef8::hexRef8(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), wallBoundedParticle::hitProcessorPatch(), if(), Distribution< Type >::index(), indexedOctree< Foam::treeDataFace >::indexedOctree(), injectionModelList::info(), surfaceFieldValue::initialise(), LduMatrix< Type, DType, LUType >::initMatrixInterfaces(), lduMatrix::initMatrixInterfaces(), processorPolyPatch::initOrder(), distribution::insertMissingKeys(), correlationFunction< Type >::integral(), Function1< Foam::Vector >::integrate(), TableBase< Type >::integrate(), polynomialFunction::integrate(), linearInterpolationWeights::integrationWeights(), interpolationCellPointFace< Type >::interpolate(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), Foam::interpolatePointToCell(), Foam::interpolateSplineXY(), lookupProfile::interpolateWeights(), bladeModel::interpolateWeights(), Foam::interpolateXY(), meshToMesh::interpolationMethodAMI(), intersectedSurface::intersectedSurface(), gradingDescriptors::inv(), hexMatcher::isA(), prismMatcher::isA(), pyrMatcher::isA(), tetMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), ensightPart::isFieldDefined(), meshRefinement::isNormalGap(), isoSurface::isoSurface(), isoSurfaceCell::isoSurfaceCell(), liquidMixtureProperties::K(), heSolidThermo< BasicSolidThermo, MixtureType >::Kappa(), Foam::kShellIntegration(), Foam::kShellMean(), cell::labels(), noiseFFT::Ldelta(), lduPrimitiveMesh::lduPrimitiveMesh(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), lineDivide::lineDivide(), Pstream::listCombineGather(), cylindricalCS::localToGlobal(), lookupProfile::lookupProfile(), cellCuts::loopPoints(), LUscalarMatrix::LUscalarMatrix(), cellModel::mag(), primitiveMesh::makeFaceCentresAndAreas(), faceCoupleInfo::makeMap(), epsilonWallFunctionFvPatchScalarField::manipulateMatrix(), omegaWallFunctionFvPatchScalarField::manipulateMatrix(), Field< Foam::Vector2D >::map(), meshToMesh::mapAndOpTgtToSrc(), mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), fvMesh::mapFields(), Foam::MapLagrangianFields(), mappedPatchFieldBase< Type >::mappedField(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), edgeCollapser::markMergeEdges(), PatchTools::markZone(), triSurface::markZone(), PatchTools::markZones(), triSurface::markZones(), meshToMeshMethod::maskCells(), momentOfInertia::massPropertiesShell(), momentOfInertia::massPropertiesSolid(), degenerateMatcher::match(), processorPolyPatch::matchFace(), Foam::matchPoints(), conformalVoronoiMesh::maxSurfaceProtrusion(), noiseFFT::meanPf(), distribution::median(), Distribution< Type >::median(), cellToCellStencil::merge(), cellToFaceStencil::merge(), edgeIntersections::merge(), meshRefinement::mergeBaffles(), edgeMesh::mergeEdges(), meshRefinement::mergeEdgesUndo(), edgeMesh::mergePoints(), triSurfaceTools::mergePoints(), globalMeshData::mergePoints(), snappySnapDriver::mergeZoneBaffles(), globalMeshData::mesh(), cellShape::meshEdges(), PrimitivePatch< Face, ::Foam::List, pointField, point >::meshEdges(), MeshedSurface< Foam::face >::MeshedSurface(), cellShape::meshFaces(), momentOfInertia::meshInertia(), meshTriangulation::meshTriangulation(), edgeIntersections::minEdgeLength(), SVD::minNonZeroS(), attachDetach::modifyMotionPoints(), slidingInterface::modifyMotionPoints(), molecule::molecule(), Cloud< streamLineParticle >::move(), regionModel1D::moveMesh(), polyTopoChange::movePoints(), primitiveMesh::movePoints(), Foam::multiply(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), phaseProperties::name(), NamedEnum< directionType, 3 >::names(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestFeatEdge(), extendedEdgeMesh::nearestFeatureEdge(), face::nearestPointClassify(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), cellModel::nEdges(), PrimitivePatch< Face, ::Foam::List, pointField, point >::nEdges(), primitiveMesh::nEdges(), polyBoundaryMesh::neighbourEdges(), basicChemistryModel::New(), cellModel::nFaces(), surfMesh::nFaces(), vtkMesh::nFieldCells(), vtkMesh::nFieldPoints(), potential::nIds(), surfaceFeatures::nInternalEdges(), noiseFFT::noiseFFT(), cellCuts::nonAnchorPoints(), nonBlockingGaussSeidelSmoother::nonBlockingGaussSeidelSmoother(), surfaceLocation::normal(), distribution::normalisedShifted(), surfMesh::nPoints(), PrimitivePatch< Face, ::Foam::List, pointField, point >::nPoints(), UPstream::nProcs(), refinementSurfaces::nRegions(), polyLine::nSegments(), molecule::constantProperties::nSites(), minEqOpFace::operator()(), listPlusEqOp< T >::operator()(), minEqOp< labelPair >::operator()(), ListPlusEqOp< T, Size >::operator()(), faceEqOp< T, CombineOp >::operator()(), combineEqOp< Type, TrackingData >::operator()(), nearestEqOp::operator()(), csvTableReader< Type >::operator()(), ListAppendEqOp< T >::operator()(), offsetOp< face >::operator()(), LduMatrix< Type, DType, LUType >::operator*=(), lduMatrix::operator*=(), labelRanges::const_iterator::operator++(), polynomialFunction::operator+=(), polynomialFunction::operator-=(), Foam::operator<<(), CompactIOField< T, BaseType >::operator=(), CompactIOList< face, label >::operator=(), cellTable::operator=(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::operator=(), Foam::operator==(), Foam::operator>>(), cell::opposingFace(), cell::opposingFaceLabel(), processorPolyPatch::order(), orientedSurface::orient(), triSurfaceTools::otherFace(), distributedTriSurfaceMesh::overlappingSurface(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::overlaps(), indexedOctree< Foam::treeDataFace >::overlaps(), argList::parse(), Foam::parseNASCoord(), ParticleCollector< CloudType >::ParticleCollector(), boundaryMesh::patchify(), patchInjection::patchInjectedMassTotals(), patchInteractionDataList::patchInteractionDataList(), pairPatchAgglomeration::patchLevel(), boundaryMesh::patchNames(), patchZones::patchZones(), noiseFFT::Pdelta(), SprayCloud< Foam::DSMCCloud >::penetration(), primitiveMesh::pointCells(), pointFieldReconstructor::pointFieldReconstructor(), polyMesh::pointInCell(), pointMVCWeight::pointMVCWeight(), PatchTools::pointNormals(), primitiveMesh::pointPoints(), cell::points(), PrimitivePatchInterpolation< Foam::PrimitivePatch >::pointToFaceInterpolate(), polyAddFace::polyAddFace(), polyMesh::polyMesh(), Foam::polyMeshZipUpCells(), polyModifyFace::polyModifyFace(), porousBafflePressureFvPatchField< Type >::porousBafflePressureFvPatchField(), noPreconditioner::precondition(), DICPreconditioner::precondition(), DILUPreconditioner::precondition(), GAMGPreconditioner::precondition(), diagonalPreconditioner::precondition(), FDICPreconditioner::precondition(), DILUPreconditioner::preconditionT(), Foam::preservePatchTypes(), pressureInletOutletVelocityFvPatchVectorField::pressureInletOutletVelocityFvPatchVectorField(), sampledPatchInternalField::print(), sampledPlane::print(), sampledCuttingPlane::print(), distanceSurface::print(), sampledPatch::print(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::print(), indexedOctree< Foam::treeDataFace >::print(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printFieldInfo(), vtkUnstructuredReader::printFieldStats(), fvMeshDistribute::printMeshInfo(), GAMGProcAgglomeration::printStats(), Foam::printTable(), GAMGAgglomeration::procAgglomerateRestrictAddressing(), processorGAMGInterface::processorGAMGInterface(), fvFieldDecomposer::processorVolPatchFieldDecomposer::processorVolPatchFieldDecomposer(), surfaceFieldValue::processSameTypeValues(), faceAreaWeightAMI< SourcePatch, TargetPatch >::processSourceFace(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectFaceCentres(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OBJedgeFormat::read(), VTKsurfaceFormat< Face >::read(), tabulated6DoFAcceleration::read(), VTKedgeFormat::read(), STARCDsurfaceFormat< Face >::read(), tabulated6DoFMotion::read(), STARCDedgeFormat::read(), boundaryMesh::read(), refinementHistory::read(), STARCD::readBoundary(), STARCD::readCells(), dynamicRefineFvMesh::readDict(), Foam::readDir(), ReactingParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), functionObjectList::readFunctionObject(), mappedPatchBase::readListOrField(), boundaryMesh::readTriSurface(), surfMesh::readUpdate(), polyMesh::readUpdate(), ensightParts::recalculate(), mapDistributeBase::receive(), InteractionLists< Foam::molecule >::receiveReferredData(), ensightPart::reconstruct(), processorMeshes::reconstructPoints(), triSurfaceTools::redGreenRefine(), PFA< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), referredWallFace::referredWallFace(), dynamicRefineFvMesh::refine(), refinementHistory::refinementHistory(), regionCoupledBaseGAMGInterface::regionCoupledBaseGAMGInterface(), refinementFeatures::regionEdgeTrees(), searchableSurfaceCollection::regions(), edgeMesh::regions(), fvMatrix< Type >::relax(), MeshedSurface< Foam::face >::remapFaces(), polyTopoChange::removeCell(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::removeIndex(), undoableMeshCutter::removeSplitFaces(), randomRenumber::renumber(), manualRenumber::renumber(), zoltanRenumber::renumber(), SloanRenumber::renumber(), springRenumber::renumber(), structuredRenumber::renumber(), renumberMethod::renumber(), snappySnapDriver::repatchToSurface(), cyclicACMIPolyPatch::resetAMI(), logFiles::resetNames(), polyMesh::resetPrimitives(), lduMatrix::residual(), refinementHistory::resize(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), GAMGAgglomeration::restrictFaceField(), pairPatchAgglomeration::restrictField(), GAMGAgglomeration::restrictField(), face::reverseFace(), pressureInletOutletVelocityFvPatchVectorField::rmap(), thermalBaffleFvPatchScalarField::rmap(), noiseFFT::RMSmeanPf(), face::sameVertices(), multiNormal::sample(), motionSmootherAlgo::scaleMesh(), globalIndex::scatter(), Pstream::scatterList(), mapDistributeBase::schedule(), searchableSurfaces::searchableSurfaces(), timeSelector::select(), scalarRanges::selected(), timeSelector::selected(), surfaceFeatures::selectFeatureEdges(), dynamicRefineFvMesh::selectRefineCells(), dynamicRefineFvMesh::selectUnrefinePoints(), mapDistributeBase::send(), InteractionLists< Foam::molecule >::sendReferredData(), coupledPolyPatch::separated(), Foam::setBlockFaceCorrespondence(), fvMeshSubset::setCellSubset(), Time::setControls(), repatchPolyTopoChanger::setFaceZone(), boundaryMesh::setFeatureEdges(), SemiImplicitSource< Type >::setFieldData(), surfaceFeatures::setFromStatus(), pointPatchField< vector >::setInInternalField(), hexRef8::setInstance(), fvMeshSubset::setLargeCellSubset(), refinementSurfaces::setMinLevelFields(), cellVolumeWeightMethod::setNextCells(), faceAreaWeightAMI< SourcePatch, TargetPatch >::setNextFaces(), mapNearestMethod::setNextNearestCells(), patchInjectionBase::setPositionAndCell(), removeCells::setRefinement(), duplicatePoints::setRefinement(), refinementIterator::setRefinement(), perfectInterface::setRefinement(), faceCollapser::setRefinement(), boundaryCutter::setRefinement(), removePoints::setRefinement(), combineFaces::setRefinement(), createShellMesh::setRefinement(), tetDecomposer::setRefinement(), removeFaces::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), edgeCollapser::setRefinement(), addPatchCellLayer::setRefinement(), hexRef8::setRefinement(), sampledSet::setSamples(), CompactListList< T, Container >::setSize(), data::setSolverPerformance(), removePoints::setUnrefinement(), combineFaces::setUnrefinement(), hexRef8::setUnrefinement(), UnsortedMeshedSurface< Face >::setZones(), globalMeshData::sharedPoints(), liquidMixtureProperties::sigma(), searchableSurfacesQueries::signedDistance(), triSurfaceGeoMesh::size(), triSurfacePointGeoMesh::size(), fvFieldDecomposer::patchFieldDecomposer::size(), dynamicTreeDataPoint::size(), pointFieldDecomposer::patchFieldDecomposer::size(), weightedFvPatchFieldMapper::size(), procLduMatrix::size(), distributedWeightedFvPatchFieldMapper::size(), pointMapper::size(), cellMapper::size(), singleCellFvMesh::agglomPatchFieldMapper::size(), fvFieldDecomposer::processorVolPatchFieldDecomposer::size(), solidMixtureProperties::size(), liquidMixtureProperties::size(), treeDataPoint::size(), facePointPatch::size(), fvFieldDecomposer::processorSurfacePatchFieldDecomposer::size(), treeDataEdge::size(), treeDataCell::size(), treeDataFace::size(), meshToMesh0::patchFieldInterpolator::size(), GAMGInterface::size(), argList::size(), CompactListList< T, Container >::sizes(), SLGThermo::SLGThermo(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), snappyRefineDriver::snappyRefineDriver(), basicSymmetryFvPatchField< Type >::snGradTransformDiag(), fixedNormalSlipFvPatchField< Type >::snGradTransformDiag(), partialSlipFvPatchField< Type >::snGradTransformDiag(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), solidMixtureProperties::solidMixtureProperties(), PCG::solve(), PBiCG::solve(), smoothSolver::solve(), PBiCGStab::solve(), GAMGSolver::solve(), TDACChemistryModel< CompType, ThermoType >::solve(), ParSortableList< Type >::sort(), PatchTools::sortedEdgeFaces(), Foam::sortedOrder(), PatchTools::sortedPointEdges(), UnsortedMeshedSurface< Face >::sortedZones(), MeshedSurface< Foam::face >::sortFacesAndStore(), extendedEdgeMesh::sortPointsAndEdges(), meshRefinement::splitFaces(), meshRefinement::splitMesh(), meshRefinement::splitMeshRegions(), Foam::stepBackwardsToNextPoint(), Foam::stepForwardsToNextPoint(), MeshedSurface< Foam::face >::stitchFaces(), hexRef8::storeData(), streamLineParticle::streamLineParticle(), cellZoneSet::subset(), pointZoneSet::subset(), faceZoneSet::subset(), refinementHistory::subset(), hexRef8::subset(), PatchTools::subsetMap(), UnsortedMeshedSurface< Face >::subsetMesh(), triSurface::subsetMesh(), MeshedSurface< Foam::face >::subsetMesh(), triSurface::subsetMeshMap(), Foam::ListListOps::subSizes(), surfaceFeatures::surfaceFeatures(), surfaceIntersection::surfaceIntersection(), PrimitivePatch< Face, ::Foam::List, pointField, point >::surfaceType(), globalMeshData::syncData(), syncTools::syncEdgeList(), syncTools::syncEdgeMap(), globalMeshData::syncPointData(), syncTools::syncPointList(), syncTools::syncPointMap(), meshRefinement::testSyncPointList(), tetIndices::tetIndices(), particle< Type >::tetNeighbour(), TGaussSeidelSmoother< Type, DType, LUType >::TGaussSeidelSmoother(), heThermo< BasicSolidThermo, MixtureType >::THE(), thermoSingleLayer::thermoSingleLayer(), targetCoeffTrim::thetag(), Time::Time(), pointToPointPlanarInterpolation::timeNames(), StaticHashTable< T, Key, Hash >::toc(), CV2D::toPoint2D(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::totalFlowRateAdvectiveDiffusiveFvPatchScalarField(), wallBoundedParticle::trackToEdge(), particle< Type >::trackToFace(), MeshedSurface< Foam::face >::transcribe(), DynamicList< Foam::Tensor >::transfer(), MeshedSurface< Foam::face >::transfer(), Foam::transform(), fft::transform(), cylindrical::transform(), FaceCellWave< Type, TrackingData >::transform(), Foam::transformList(), porosityModel::transformModelData(), globalIndexAndTransform::transformPatches(), Foam::transformPoints(), rigidBodyMotion::transformPoints(), cyclicAMIPolyPatch::transformPosition(), cyclicPolyPatch::transformPosition(), cylindrical::transformTensor(), STARCDCoordinateRotation::transformVector(), EulerCoordinateRotation::transformVector(), axesRotation::transformVector(), cylindrical::transformVector(), triSurfaceSearch::tree(), face::triangles(), polyMeshTetDecomposition::triangleTetIndices(), MeshedSurface< Foam::face >::triangulate(), triSurfaceTools::triangulateFaceCentre(), surfaceFeatures::trimFeatures(), triSurface::triSurfInstance(), uniformInterpolatedDisplacementPointPatchVectorField::uniformInterpolatedDisplacementPointPatchVectorField(), Foam::uniqueOrder(), Foam::unitSet(), dynamicRefineFvMesh::unrefine(), sampledSurfaces::update(), dynamicRefineFvMesh::update(), AMIInterpolation< SourcePatch, TargetPatch >::update(), directionInfo::updateCell(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), externalWallHeatFluxTemperatureFvPatchScalarField::updateCoeffs(), patchEdgeFaceRegions::updateFace(), processorGAMGInterfaceField::updateInterfaceMatrix(), topoSet::updateLabels(), meshRefinement::updateList(), LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), lduMatrix::updateMatrixInterfaces(), patchInjectionBase::updateMesh(), componentDisplacementMotionSolver::updateMesh(), processorPolyPatch::updateMesh(), CellZoneInjection< CloudType >::updateMesh(), displacementMotionSolver::updateMesh(), removePoints::updateMesh(), cellZoneSet::updateMesh(), pointZoneSet::updateMesh(), boundaryCutter::updateMesh(), faceZoneSet::updateMesh(), refinementHistory::updateMesh(), addPatchCellLayer::updateMesh(), hexRef8::updateMesh(), polyMesh::updateMesh(), meshRefinement::updateMesh(), cellZoneSet::updateSet(), pointZoneSet::updateSet(), fileMonitor::updateStates(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), PackedBoolList::used(), USERD_get_gold_variable_info(), USERD_set_filenames(), patchEdgeFaceRegions::valid(), Function1< Foam::Vector >::value(), TableBase< Type >::value(), polynomialFunction::value(), splineInterpolationWeights::valueWeights(), linearInterpolationWeights::valueWeights(), vtkInsertNextOpenFOAMPoint(), vtkUnstructuredReader::vtkUnstructuredReader(), wallBoundedStreamLineParticle::wallBoundedStreamLineParticle(), wallLayerCells::wallLayerCells(), WallLocalSpringSliderDashpot< CloudType >::WallLocalSpringSliderDashpot(), meshReader::warnDuplicates(), meshRefinement::weightedSum(), graph::wordify(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), vtkSetWriter< Type >::write(), ensightSetWriter< Type >::write(), X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), rawSetWriter< Type >::write(), gnuplotSetWriter< Type >::write(), xmgraceSetWriter< Type >::write(), SMESHsurfaceFormat< Face >::write(), foamSurfaceWriter::write(), OBJsurfaceFormat< Face >::write(), GTSsurfaceFormat< Face >::write(), thirdBodyEfficiencies::write(), csvSetWriter< Type >::write(), VTKsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OBJedgeFormat::write(), OFFsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), ensightBinaryStream::write(), STARCDsurfaceFormat< Face >::write(), rawSurfaceWriter::write(), OFSsurfaceFormat< Face >::write(), STARCDedgeFormat::write(), patchIdentifier::write(), OBJstream::write(), writer< Foam::SphericalTensor >::write(), primitiveEntry::write(), nastranSurfaceWriter::write(), solidReaction< ReactionThermo >::write(), writeObjects::write(), pressureInletOutletVelocityFvPatchVectorField::write(), ParticleCollector< CloudType >::write(), forceCoeffs::write(), streamLine::write(), regionSizeDistribution::write(), wallBoundedStreamLine::write(), STLsurfaceFormat< Face >::writeAscii(), STLsurfaceFormat< Face >::writeBinary(), forces::writeBins(), STARCDsurfaceFormatCore::writeCase(), STARCDedgeFormat::writeCase(), ensightPartFaces::writeConnectivity(), vtkSurfaceWriter::writeData(), dxSurfaceWriter::writeData(), triSurface::writeDX(), UList< Foam::wordRe >::writeEntry(), rotorDiskSource::writeField(), ensightPart::writeFieldList(), ReactingParcel< ParcelType >::writeFields(), fieldValueDelta::writeFileHeader(), WRLsurfaceFormatCore::writeHeader(), VTKsurfaceFormatCore::writeHeader(), VTKedgeFormat::writeHeader(), rawSurfaceWriter::writeHeader(), AMIMethod< SourcePatch, TargetPatch >::writeIntersectionOBJ(), Foam::meshTools::writeOBJ(), triSurfaceTools::writeOBJ(), surfaceFeatures::writeObj(), extendedEdgeMesh::writeObj(), ensightPart::writeScalarField(), edgeMesh::writeStats(), searchableSurfaces::writeStats(), extendedEdgeMesh::writeStats(), extendedCellToFaceStencil::writeStencilStats(), ensightPart::writeVectorField(), solidMixtureProperties::X(), TableBase< Type >::x(), liquidMixtureProperties::X(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::X(), interpolation2DTable< scalar >::Xi(), liquidMixtureProperties::Xs(), Foam::XstepForwardsToNextPoint(), TableBase< Type >::y(), phaseProperties::Y(), liquidMixtureProperties::Y(), meshRefinement::zonify(), csvTableReader< Type >::~csvTableReader(), ensightPartCells::~ensightPartCells(), ensightPartFaces::~ensightPartFaces(), ISAT< CompType, ThermoType >::~ISAT(), LeastSquaresVectors< Stencil >::~LeastSquaresVectors(), medialAxisMeshMover::~medialAxisMeshMover(), RaviPetersen::~RaviPetersen(), skewCorrectionVectors::~skewCorrectionVectors(), thermalBaffle::~thermalBaffle(), TRIsurfaceFormatCore::~TRIsurfaceFormatCore(), UIPstream::~UIPstream(), and UOPstream::~UOPstream().
null()
const Foam::List< T > & null () inline static
Return a null List.
Definition at line 117 of file ListI.H.
clone()
Foam::autoPtr< Foam::List< T > > clone () const inline
Clone.
Definition at line 108 of file ListI.H.
Referenced by pointZone::clone(), cellZone::clone(), and faceZone::clone().
size() [2/2]
Foam::label size () const inline
Return the number of elements in the UList.
Definition at line 170 of file ListI.H.
Referenced by labelRanges::add(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::append(), PackedList< 2 >::capacity(), ITstream::nRemainingTokens(), labelRanges::const_iterator::operator++(), ITstream::print(), ITstream::read(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::remove(), PackedList< 2 >::reserve(), SortableList< T >::reverseSort(), ITstream::rewind(), globalMeshData::sharedPointGlobalLabels(), PackedList< 2 >::shrink(), SortableList< T >::sort(), primitiveEntry::write(), and cellClassification::writeStats().
resize() [1/2]
void resize (const label newSize) inline
Alias for setSize(const label)
Definition at line 137 of file ListI.H.
Referenced by polyMeshFilter::filter(), polyMeshFilter::filterEdges(), minEqOpFace::operator()(), and dynamicRefineFvMesh::readDict().
resize() [2/2]
void resize (const label newSize, const T & a) inline
Alias for setSize(const label, const T&)
Definition at line 144 of file ListI.H.
setSize() [1/2]
void setSize (const label newSize)
Reset size of List.
Definition at line 281 of file List.C.
Referenced by preserveBafflesConstraint::add(), preserveFaceZonesConstraint::add(), preservePatchesConstraint::add(), singleProcessorFaceSetsConstraint::add(), refinementHistory::add(), cellTable::addCellZones(), addPatchCellLayer::addedCells(), lduPrimitiveMesh::addInterfaces(), edgeSurface::addIntersectionEdges(), interRegionExplicitPorositySource::addSup(), MeshedSurface< Foam::face >::addZones(), GAMGAgglomeration::agglomerateLduAddressing(), extendedEdgeMesh::allNearestFeatureEdges(), face::areaInContact(), argList::argList(), FreeStream< CloudType >::autoMap(), meshRefinement::balance(), triangle< Point, PointRef >::barycentric(), tetrahedron< Point, PointRef >::barycentric(), bladeModel::bladeModel(), booleanSurface::booleanSurface(), searchablePlane::boundingSpheres(), searchableBox::boundingSpheres(), searchableSphere::boundingSpheres(), searchableDisk::boundingSpheres(), searchablePlate::boundingSpheres(), searchableCylinder::boundingSpheres(), searchableSurfaceCollection::boundingSpheres(), triSurfaceMesh::boundingSpheres(), cachedRandom::cachedRandom(), nearWallFields::calcAddressing(), decompositionMethod::calcCellCells(), primitiveMesh::calcCells(), cellToFaceStencil::calcFaceStencil(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), polyLine::calcParam(), primitiveMesh::calcPointOrder(), createShellMesh::calcPointRegions(), addPatchCellLayer::calcSidePatch(), coupledPolyPatch::calcTransformTensors(), meshRefinement::calculateEdgeWeights(), GAMGAgglomeration::calculateRegionMaster(), pointMVCWeight::calcWeights(), primitiveMeshTools::cellClosedness(), cellMatcher::cellMatcher(), fvMotionSolverCore::cellMotionBoundaryTypes(), boundaryMesh::changeFaces(), MeshedSurface< Foam::face >::checkFaces(), edgeCollapser::checkMeshQuality(), GAMGAgglomeration::checkRestriction(), ensightPartFaces::classify(), polyMesh::clearPrimitives(), refinementHistory::clone(), cellShape::collapsedFaces(), extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), mappedPatchBase::collectSamples(), mapDistributeBase::compact(), removeFaces::compatibleRemoves(), fvPatch::constraintTypes(), polyPatch::constraintTypes(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), removePoints::countPointUsage(), cyclicPolyPatch::coupledPoints(), epsilonWallFunctionFvPatchScalarField::createAveragingWeights(), omegaWallFunctionFvPatchScalarField::createAveragingWeights(), meshRefinement::createZoneBaffles(), STARCD::cullPoints(), motionSmootherAlgo::curPoints(), hexCellLooper::cut(), geomCellLooper::cut(), Foam::cwd(), simpleGeomDecomp::decompose(), LUscalarMatrix::decompose(), mapPatchChange::deletedPatches(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), refinementHistory::distribute(), mapDistributeBase::distribute(), distributedTriSurfaceMesh::distribute(), snappySnapDriver::doSnap(), Foam::duplicateOrder(), cell::edges(), StaticHashTable< T, Key, Hash >::erase(), Pstream::exchange(), mapDistributeBase::exchangeAddressing(), Pstream::exchangeSizes(), extendedEdgeMesh::extendedEdgeMesh(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), extrudePatchMesh::extrudePatchMesh(), primitiveMesh::faceEdges(), primitiveMeshTools::facePyramidVolume(), cellModel::faces(), boundBox::faces(), faceTriangulation::faceTriangulation(), searchablePlateFeatures::features(), refinementSurfaces::findAllHigherIntersections(), searchableSurfacesQueries::findAllIntersections(), searchableSurfacesQueries::findAnyIntersection(), refinementSurfaces::findHigherIntersection(), coordinateSystems::findIndices(), ZoneMesh< cellZone, polyMesh >::findIndices(), refinementSurfaces::findInside(), triSurfaceSearch::findLine(), searchablePlane::findLine(), searchableSphere::findLine(), searchablePlate::findLine(), searchableDisk::findLine(), searchableCylinder::findLine(), searchableSurfaceWithGaps::findLine(), searchableSurfaceCollection::findLine(), searchableBox::findLine(), triSurfaceSearch::findLineAll(), searchablePlane::findLineAll(), searchableSphere::findLineAll(), searchablePlate::findLineAll(), searchableDisk::findLineAll(), searchableCylinder::findLineAll(), searchableSurfaceWithGaps::findLineAll(), searchableSurfaceCollection::findLineAll(), searchableBox::findLineAll(), distributedTriSurfaceMesh::findLineAll(), triSurfaceSearch::findLineAny(), searchableSphere::findLineAny(), searchableCylinder::findLineAny(), searchableBox::findLineAny(), triSurfaceRegionSearch::findNearest(), triSurfaceSearch::findNearest(), searchablePlane::findNearest(), searchableSphere::findNearest(), searchablePlate::findNearest(), searchableDisk::findNearest(), searchableSurfacesQueries::findNearest(), searchableCylinder::findNearest(), searchableBox::findNearest(), distributedTriSurfaceMesh::findNearest(), refinementFeatures::findNearestEdge(), searchableSurfacesQueries::findNearestIntersection(), refinementSurfaces::findNearestIntersection(), refinementFeatures::findNearestPoint(), refinementSurfaces::findNearestRegion(), refinementFeatures::findNearestRegionEdge(), mappedPatchBase::findSamples(), polyMeshAdder::findSharedPoints(), Time::findTimes(), FreeStream< CloudType >::FreeStream(), globalIndex::gather(), PatchTools::gatherAndMerge(), GAMGAgglomeration::gatherList(), triSurfaceMesh::getField(), searchableSurfaceCollection::getField(), distributedTriSurfaceMesh::getField(), combineFaces::getMergeSets(), searchablePlane::getNormal(), searchableSphere::getNormal(), searchablePlate::getNormal(), searchableDisk::getNormal(), searchableCylinder::getNormal(), searchableSurfaceCollection::getNormal(), searchableBox::getNormal(), triSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getNormal(), boundaryMesh::getNTris(), searchablePlane::getRegion(), searchableSphere::getRegion(), searchablePlate::getRegion(), searchableDisk::getRegion(), searchableCylinder::getRegion(), searchableSurfaceCollection::getRegion(), searchableBox::getRegion(), triSurfaceMesh::getRegion(), distributedTriSurfaceMesh::getRegion(), Foam::vtkPVReaders::getSelectedArrayEntries(), Foam::vtkPV3Readers::getSelectedArrayEntries(), removePoints::getUnrefimentSet(), cellLooper::getVertEdgesNonFace(), triSurfaceTools::getVertexTriangles(), cellLooper::getVertFacesNonEdge(), searchableSphere::getVolumeType(), searchableCylinder::getVolumeType(), searchableBox::getVolumeType(), triSurfaceMesh::getVolumeType(), addPatchCellLayer::globalEdgeFaces(), triSurfaceTools::greenRefine(), hashedWordList::hashedWordList(), Distribution< Type >::index(), sortLabelledTri::indices(), meshToMeshMethod::initialise(), AMIMethod< SourcePatch, TargetPatch >::initialise(), linearInterpolationWeights::integrationWeights(), GAMGInterface::interfaceInternalField(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), intersectedSurface::intersectedSurface(), cellZoneSet::invert(), pointZoneSet::invert(), faceZoneSet::invert(), Foam::invertManyToMany(), Foam::invertOneToMany(), isoSurface::isoSurface(), isoSurfaceCell::isoSurfaceCell(), dictionary::keys(), cell::labels(), noiseFFT::Ldelta(), lduPrimitiveMesh::lduPrimitiveMesh(), liquidMixtureProperties::liquidMixtureProperties(), List< Field< scalar > >::List(), lookupProfile::lookupProfile(), basicThermo::lookupThermo(), LUscalarMatrix::LUscalarMatrix(), mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), fvMesh::mapFields(), boundaryMesh::markFaces(), PatchTools::markZones(), triSurface::markZones(), PatchTools::matchEdges(), Foam::matchPoints(), PatchTools::matchPoints(), hexMatcher::matchShape(), prismMatcher::matchShape(), pyrMatcher::matchShape(), tetMatcher::matchShape(), tetWedgeMatcher::matchShape(), wedgeMatcher::matchShape(), cellToCellStencil::merge(), cellToFaceStencil::merge(), edgeIntersections::merge(), meshRefinement::mergeBaffles(), edgeMesh::mergeEdges(), Foam::mergePoints(), edgeMesh::mergePoints(), globalMeshData::mergePoints(), meshTriangulation::meshTriangulation(), molecule::molecule(), engineValve::movingPatchIDs(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), NamedEnum< directionType, 3 >::names(), IOobjectList::names(), objectRegistry::names(), extendedEdgeMesh::nearestFeatureEdge(), extendedEdgeMesh::nearestFeatureEdgeByType(), surfaceFeatures::nearestSurfEdge(), polyBoundaryMesh::neighbourEdges(), basicChemistryModel::New(), basicSolidChemistryModel::New(), cellCuts::nonAnchorPoints(), Distribution< Type >::normalised(), ListPlusEqOp< T, Size >::operator()(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), procLess::operator()(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), ListAppendEqOp< T >::operator()(), polynomialFunction::operator+=(), polynomialFunction::operator-=(), Foam::operator<<(), CompactIOField< T, BaseType >::operator=(), CompactIOList< face, label >::operator=(), Foam::operator>>(), regionCoupledBase::order(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), cyclicPolyPatch::order(), cyclicAMIPolyPatch::order(), indexedOctree< Foam::treeDataFace >::overlaps(), argList::parse(), ParticleCollector< CloudType >::ParticleCollector(), boundaryMesh::patchNames(), noiseFFT::Pdelta(), SprayCloud< Foam::DSMCCloud >::penetration(), phaseProperties::phaseProperties(), phasePropertiesList::phasePropertiesList(), pointFieldReconstructor::pointFieldReconstructor(), PatchTools::pointNormals(), Foam::polyMeshZipUpCells(), argList::postProcess(), snappySnapDriver::preSmoothPatch(), fvMeshDistribute::printCoupleInfo(), Foam::printTable(), Distribution< Type >::raw(), NASedgeFormat::read(), GTSsurfaceFormat< Face >::read(), FixedValueConstraint< Type >::read(), STARCDedgeFormat::read(), primitiveEntry::read(), functionObjectList::read(), boundaryMesh::read(), STARCD::readBoundary(), STARCD::readCells(), Foam::readDir(), mappedPatchBase::readListOrField(), STARCD::readPoints(), boundaryMesh::readTriSurface(), mapDistributeBase::receive(), ensightPart::reconstruct(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), meshRefinement::refineCandidates(), refinementHistory::refinementHistory(), searchablePlane::regions(), searchableBox::regions(), searchableSphere::regions(), searchableDisk::regions(), searchablePlate::regions(), searchableCylinder::regions(), searchableSurfaceCollection::regions(), triSurfaceMesh::regions(), edgeMesh::regions(), snappySnapDriver::repatchToSurface(), PackedList< 2 >::reserve(), refinementHistory::resize(), mapDistributeBase::schedule(), searchableSurfaces::searchableSurfaces(), PackedList< 2 >::setCapacity(), fvMeshSubset::setCellSubset(), decompositionMethod::setConstraints(), boundaryMesh::setFeatureEdges(), polyBoundaryMesh::setGroup(), fvMeshSubset::setLargeCellSubset(), UnsortedMeshedSurface< Face >::setOneZone(), duplicatePoints::setRefinement(), refinementIterator::setRefinement(), boundaryCutter::setRefinement(), removePoints::setRefinement(), tetDecomposer::setRefinement(), addPatchCellLayer::setRefinement(), hexRef8::setRefinement(), molecule::setSiteSizes(), cellSets::setSize(), SortableListEFA< Type >::setSize(), SortableListDRGEP< Type >::setSize(), CompactListList< T, Container >::setSize(), UnsortedMeshedSurface< Face >::setSize(), bufferedAccumulator< scalar >::setSizes(), data::setSolverPerformance(), removePoints::setUnrefinement(), UnsortedMeshedSurface< Face >::setZones(), PackedList< 2 >::shrink(), searchableSurfacesQueries::signedDistance(), snappyRefineDriver::snappyRefineDriver(), GAMGSolver::solve(), ParSortableList< Type >::sort(), Foam::sortedOrder(), UnsortedMeshedSurface< Face >::sortedZones(), extendedEdgeMesh::sortPointsAndEdges(), meshRefinement::splitFaces(), MeshedSurface< Foam::face >::stitchFaces(), streamLineParticle::streamLineParticle(), NamedEnum< directionType, 3 >::strings(), PatchTools::subsetMap(), triSurface::subsetMeshMap(), surfacePatchIOList::surfacePatchIOList(), surfZoneIOList::surfZoneIOList(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), StaticHashTable< T, Key, Hash >::toc(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), externalCoupledMixedFvPatchField< scalar >::transferData(), boundaryMesh::triangulate(), MeshedSurface< Foam::face >::triangulate(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), boundaryMesh::triangulateLocal(), Foam::uniqueOrder(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), patchEdgeFaceRegions::updateEdge(), patchEdgeFaceRegions::updateFace(), edgeVertex::updateLabels(), removePoints::updateMesh(), cellZoneSet::updateMesh(), boundaryCutter::updateMesh(), faceZoneSet::updateMesh(), faceZone::updateMesh(), addPatchCellLayer::updateMesh(), polyMesh::updateMesh(), PackedBoolList::used(), cellToFaceStencil::validBoundaryFaces(), cellToCellStencil::validBoundaryFaces(), splineInterpolationWeights::valueWeights(), linearInterpolationWeights::valueWeights(), vtkUnstructuredReader::vtkUnstructuredReader(), NamedEnum< directionType, 3 >::words(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), forceCoeffs::write(), streamLine::write(), and wallBoundedStreamLine::write().
setSize() [2/2]
void setSize (const label newSize, const T & a)
Reset size of List and value for new elements.
Definition at line 327 of file List.C.
clear()
void clear () inline
Clear the list, i.e. set size to zero.
Definition at line 124 of file ListI.H.
Referenced by Cloud< streamLineParticle >::autoMap(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::buildCellOccupancy(), cellVolumeWeightMethod::calculateAddressing(), edgeCollapser::checkMeshQuality(), hashedWordList::clear(), SortableList< T >::clear(), TRIsurfaceFormatCore::clear(), STLsurfaceFormatCore::clear(), MeshedSurfaceIOAllocator::clear(), CompactListList< T, Container >::clear(), edgeMesh::clear(), UnsortedMeshedSurface< Face >::clear(), extendedEdgeMesh::clear(), block::clearGeom(), PackedList< 2 >::clearStorage(), Foam::cmptAv(), Foam::cmptMag(), Foam::cmptMax(), Foam::cmptMin(), Poisson::correct(), removePoints::countPointUsage(), DimensionedField< Type, Foam::pointMesh >::DimensionedField(), Foam::duplicateOrder(), refinementSurfaces::findAllHigherIntersections(), searchablePlane::findLineAll(), searchableSphere::findLineAll(), searchablePlate::findLineAll(), searchableDisk::findLineAll(), searchableCylinder::findLineAll(), searchableSurfaceWithGaps::findLineAll(), searchableSurfaceCollection::findLineAll(), searchableBox::findLineAll(), distributedTriSurfaceMesh::findLineAll(), meshRefinement::isNormalGap(), Foam::mag(), Foam::magSqr(), Cloud< streamLineParticle >::move(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), SortableList< T >::operator=(), patchProbes::patchProbes(), Foam::pow(), STARCDsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), STARCD::readBoundary(), STARCD::readCells(), polyMesh::readUpdate(), ensightPart::reconstruct(), cuttingPlane::reCut(), surfMesh::removeZones(), logFiles::resetName(), logFiles::resetNames(), decompositionMethod::setConstraints(), searchableSurface::setField(), SortableList< T >::shrink(), Foam::sortedOrder(), MeshedSurface< Foam::face >::sortFacesAndStore(), Foam::sqr(), UnsortedMeshedSurface< Face >::subsetMesh(), surfaceFeatures::surfaceFeatures(), MeshedSurface< Foam::face >::transfer(), MeshedSurface< Foam::face >::triangulate(), vtkUnstructuredReader::vtkUnstructuredReader(), and meshReader::writeMesh().
append() [1/3]
void append (const T & t) inline
Append an element at the end of the list.
Definition at line 184 of file ListI.H.
Referenced by singleProcessorFaceSetsConstraint::add(), cellTable::addCellZones(), Foam::debug::addDebugObject(), Foam::debug::addDimensionedConstantObject(), Foam::debug::addDimensionSetObject(), Foam::debug::addInfoObject(), Foam::debug::addOptimisationObject(), hashedWordList::append(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::buildCellOccupancy(), createShellMesh::calcPointRegions(), cellVolumeWeightMethod::calculateAddressing(), directMethod::calculateAddressing(), GAMGAgglomeration::checkRestriction(), commSchedule::commSchedule(), removeFaces::compatibleRemoves(), hexRef8::consistentSlowRefinement(), hexRef8::consistentSlowRefinement2(), curvatureSeparation::curvatureSeparation(), decompositionMethod::decompositionMethod(), cellZoneSet::deleteSet(), pointZoneSet::deleteSet(), snappyLayerDriver::doLayers(), edgeSurface::edgeSurface(), Foam::findEtcDirs(), Foam::findEtcFiles(), removeCells::getExposedFaces(), triSurfaceTools::greenRefine(), meshToMesh::mapAndOpTgtToSrc(), PatchTools::markZone(), triSurface::markZone(), meshToMeshMethod::maskCells(), meshRefinement::mergeBaffles(), meshRefinement::meshedPatches(), findCellParticle::move(), Cloud< streamLineParticle >::move(), NamedEnum< directionType, 3 >::names(), minEqOpFace::operator()(), listPlusEqOp< T >::operator()(), indexedOctree< Foam::treeDataFace >::overlaps(), boundaryMesh::patchify(), VTKsurfaceFormat< Face >::read(), functionObjectList::readFunctionObject(), edgeMesh::regions(), logFiles::resetName(), logFiles::resetNames(), timeSelector::select0(), PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setEdgeInfo(), FaceCellWave< Type, TrackingData >::setFaceInfo(), polyBoundaryMesh::setGroup(), hexRef8::setInstance(), edgeCollapser::setRefinement(), hexRef8::setRefinement(), Foam::fvc::smooth(), meshRefinement::splitMeshRegions(), Foam::fvc::spread(), Foam::fvc::sweep(), triSurfaceTools::triangulate(), externalDisplacementMeshMover::updateMesh(), and AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod().
append() [2/3]
void append (const UList< T > & lst) inline
Append a List at the end of this list.
Definition at line 191 of file ListI.H.
append() [3/3]
void append (const UIndirectList< T > & lst) inline
Append a UIndirectList at the end of this list.
Definition at line 210 of file ListI.H.
transfer() [1/3]
void transfer (List< T > & a)
Transfer the contents of the argument List into this list.
and annul the argument list
Definition at line 342 of file List.C.
Referenced by extendedEdgeMesh::add(), cellZoneSet::addSet(), pointZoneSet::addSet(), faceZoneSet::addSet(), extendedEdgeMesh::allNearestFeatureEdges(), extendedEdgeMesh::allNearestFeaturePoints(), searchableSurfaceToFaceZone::applyToSet(), setToPointZone::applyToSet(), setToCellZone::applyToSet(), faceZoneToFaceZone::applyToSet(), setToFaceZone::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), polyDualMesh::calcFeatures(), createShellMesh::calcPointRegions(), partialFaceAreaWeightAMI< SourcePatch, TargetPatch >::calculate(), directAMI< SourcePatch, TargetPatch >::calculate(), mapNearestAMI< SourcePatch, TargetPatch >::calculate(), faceAreaWeightAMI< SourcePatch, TargetPatch >::calculate(), cellVolumeWeightMethod::calculateAddressing(), mapNearestMethod::calculateAddressing(), directMethod::calculateAddressing(), boundaryMesh::changeFaces(), mapDistributeBase::compact(), removeFaces::compatibleRemoves(), polyMeshFilter::copyMesh(), meshWave::correct(), geomCellLooper::cut(), topoCellLooper::cut(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), cellZoneSet::deleteSet(), pointZoneSet::deleteSet(), faceZoneSet::deleteSet(), fvMeshDistribute::distribute(), mapDistributeBase::distribute(), edgeMesh::edgeMesh(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), hexRef8::faceLevel(), triSurfaceSearch::findLineAll(), searchableBox::findLineAll(), extendedEdgeMesh::flipNormals(), globalIndex::gather(), PatchTools::gatherAndMerge(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), List< Field< scalar > >::List(), PatchTools::markZone(), triSurface::markZone(), polyBoundaryMesh::matchGroups(), cellToCellStencil::merge(), cellToFaceStencil::merge(), edgeMesh::mergePoints(), MeshedSurface< Foam::face >::MeshedSurface(), streamLineParticle::move(), wallBoundedStreamLineParticle::move(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), NamedEnum< directionType, 3 >::names(), cellCuts::nonAnchorPoints(), minEqOp< labelPair >::operator()(), ifEqEqOp< value >::operator()(), indexedOctree< Foam::treeDataFace >::overlaps(), patchInteractionDataList::patchInteractionDataList(), OBJedgeFormat::read(), STARCDedgeFormat::read(), STARCDCore::readPoints(), surfMesh::readUpdate(), polyMesh::readUpdate(), edgeMesh::regions(), UnsortedMeshedSurface< Face >::remapFaces(), cuttingPlane::remapFaces(), MeshedSurfaceIOAllocator::reset(), edgeMesh::reset(), UnsortedMeshedSurface< Face >::reset(), IndirectListAddressing::resetAddressing(), MeshedSurfaceIOAllocator::resetFaces(), polyMesh::resetPrimitives(), SortableList< T >::reverseSort(), boundaryMesh::setExtraEdges(), hexRef8::setInstance(), hexRef8::setRefinement(), snappyRefineDriver::snappyRefineDriver(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), SortableList< T >::sort(), SortableListEFA< Type >::sort(), SortableListDRGEP< Type >::sort(), extendedEdgeMesh::sortPointsAndEdges(), meshRefinement::splitMesh(), SortableListDRGEP< Type >::stableSort(), SortableListEFA< Type >::stableSort(), MeshedSurface< Foam::face >::stitchFaces(), cellZoneSet::subset(), pointZoneSet::subset(), faceZoneSet::subset(), refinementHistory::subset(), hexRef8::subset(), surfaceIntersection::surfaceIntersection(), hashedWordList::transfer(), CompactListList< T, Container >::transfer(), edgeMesh::transfer(), mapDistributePolyMesh::transfer(), surfMesh::transfer(), mapDistributeBase::transfer(), UnsortedMeshedSurface< Face >::transfer(), PackedList< 2 >::transfer(), mapDistribute::transfer(), extendedEdgeMesh::transfer(), MeshedSurface< Foam::face >::triangulate(), dynamicRefineFvMesh::update(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), meshRefinement::updateList(), patchInjectionBase::updateMesh(), cellZoneSet::updateMesh(), pointZoneSet::updateMesh(), faceZoneSet::updateMesh(), refinementHistory::updateMesh(), hexRef8::updateMesh(), meshRefinement::updateMesh(), UList< Foam::wordRe >::writeEntry(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
transfer() [2/3]
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > & a)
Transfer the contents of the argument List into this list.
and annul the argument list
Definition at line 355 of file List.C.
transfer() [3/3]
void transfer (SortableList< T > & a)
Transfer the contents of the argument List into this list.
and annul the argument list
Definition at line 365 of file List.C.
xfer()
Foam::Xfer< Foam::List< T > > xfer () inline
Transfer contents to the Xfer container.
Definition at line 177 of file ListI.H.
Referenced by extendedEdgeMesh::add(), searchableSurfaces::checkIntersection(), surfaceFormatsCore::checkSupport(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), mappedPatchBase::distribute(), extendedEdgeMesh::flipNormals(), NamedEnum< directionType, 3 >::names(), minEqOp< labelPair >::operator()(), OFFsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), STLsurfaceFormat< Face >::read(), STARCDCore::readPoints(), mappedPatchBase::reverseDistribute(), PackedBoolList::used(), PackedList< 2 >::values(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), streamLine::write(), and wallBoundedStreamLine::write().
newElmt()
T & newElmt (const label i) inline
Return subscript-checked element of UList.
Definition at line 151 of file ListI.H.
shallowCopy()
void shallowCopy (const UList< T > &) delete
Disallow implicit shallowCopy.
operator=() [1/8]
void operator= (const UList< T > & a)
Assignment to UList operator. Takes linear time.
Definition at line 376 of file List.C.
Referenced by hashedWordList::operator=(), SortableListDRGEP< Type >::operator=(), SortableListEFA< Type >::operator=(), SortableList< T >::operator=(), triSurface::operator=(), and PackedList< 2 >::reset().
operator=() [2/8]
void operator= (const List< T > & a)
Assignment operator. Takes linear time.
Definition at line 401 of file List.C.
operator=() [3/8]
void operator= (const SLList< T > & lst)
Assignment to SLList operator. Takes linear time.
Definition at line 415 of file List.C.
operator=() [4/8]
void operator= (const UIndirectList< T > & lst)
Assignment to UIndirectList operator. Takes linear time.
Definition at line 436 of file List.C.
operator=() [5/8]
void operator= (const BiIndirectList< T > & lst)
Assignment to BiIndirectList operator. Takes linear time.
Definition at line 444 of file List.C.
operator=() [6/8]
void operator= (std::initializer_list< T > lst)
Assignment to an initializer list.
Definition at line 452 of file List.C.
operator=() [7/8]
void operator= (const T & t) inline
Assignment of all entries to the given value.
Definition at line 225 of file ListI.H.
operator=() [8/8]
void operator= (const zero) inline
Assignment of all entries to zero.
Definition at line 232 of file ListI.H.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , List< T > &) friend
Read List from Istream, discarding contents of existing List.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/Lists/List/List.H
src/OpenFOAM/containers/Lists/List/List.C
src/OpenFOAM/containers/Lists/List/ListI.H
src/OpenFOAM/containers/Lists/List/ListIO.C