OpenFOAM: HashTable< T, Key, Hash >::iteratorBase Class Reference
HashTable< T, Key, Hash >::iteratorBase Class Reference
The iterator base for HashTable.
Public Member Functions
const Key & key () const
Return the Key corresponding to the iterator.
bool operator== (const iteratorBase &) const
Compare hashedEntry element pointers.
bool operator!= (const iteratorBase &) const
bool operator== (const iteratorEnd &unused) const
Compare hashedEntry to iteratorEnd pointers.
bool operator!= (const iteratorEnd &unused) const
Protected Member Functions
iteratorBase ()
Construct null - equivalent to an 'end' position.
iteratorBase (const HashTable< T, Key, Hash > *curHashTable)
Construct from hash table, moving to its 'begin' position.
iteratorBase (const HashTable< T, Key, Hash > *curHashTable, const hashedEntry *elmt, const label hashIndex)
Construct from hash table, element and hash index.
void increment ()
Increment to the next position.
bool erase ()
Erase the HashTable element at the current position.
T & object ()
Return non-const access to referenced object.
const T & cobject () const
Return const access to referenced object.
Detailed Description
template<class T, class Key = word, class Hash = string::hash>
class Foam::HashTable< T, Key, Hash >::iteratorBase
The iterator base for HashTable.
Note: data and functions are protected, to allow reuse by iterator and prevent most external usage. iterator and const_iterator have the same size, allowing us to reinterpret_cast between them (if desired)
Definition at line 354 of file HashTable.H.
Constructor & Destructor Documentation
iteratorBase() [1/3]
iteratorBase () inline protected
Construct null - equivalent to an 'end' position.
Definition at line 164 of file HashTableI.H.
Referenced by HashTable< T, Key, Hash >::const_iterator::const_iterator(), HashTable< T, Key, Hash >::iterator::iterator(), and HashTable< T, Key, Hash >::iteratorBase::iteratorBase().
iteratorBase() [2/3]
iteratorBase (const HashTable< T, Key, Hash > * curHashTable) inline explicit protected
Construct from hash table, moving to its 'begin' position.
Definition at line 174 of file HashTableI.H.
References HashTable< T, Key, Hash >::iteratorBase::iteratorBase().
iteratorBase() [3/3]
iteratorBase (const HashTable< T, Key, Hash > * curHashTable, const hashedEntry * elmt, const label hashIndex) inline protected
Construct from hash table, element and hash index.
Definition at line 204 of file HashTableI.H.
Member Function Documentation
increment()
void increment () inline protected
Increment to the next position.
Definition at line 218 of file HashTableI.H.
Referenced by HashTable< T, Key, Hash >::iterator::operator++(), and HashTable< T, Key, Hash >::const_iterator::operator++().
erase()
bool erase () protected
Erase the HashTable element at the current position.
Definition at line 309 of file HashTable.C.
object()
T & object () inline protected
Return non-const access to referenced object.
Definition at line 270 of file HashTableI.H.
References Foam::T().
Referenced by HashTable< T, Key, Hash >::iterator::operator()(), and HashTable< T, Key, Hash >::iterator::operator*().
cobject()
const T & cobject () const inline protected
Return const access to referenced object.
Definition at line 278 of file HashTableI.H.
Referenced by HashTable< T, Key, Hash >::iterator::operator()(), HashTable< T, Key, Hash >::const_iterator::operator()(), HashTable< T, Key, Hash >::iterator::operator*(), and HashTable< T, Key, Hash >::const_iterator::operator*().
key()
const Key & key () const inline
Return the Key corresponding to the iterator.
Definition at line 262 of file HashTableI.H.
References Foam::T().
Referenced by regionSizeDistribution::write().
operator==() [1/2]
bool operator== (const iteratorBase & iter) const inline
Compare hashedEntry element pointers.
Definition at line 286 of file HashTableI.H.
operator!=() [1/2]
bool operator!= (const iteratorBase & iter) const inline
Definition at line 296 of file HashTableI.H.
operator==() [2/2]
bool operator== (const iteratorEnd & unused) const inline
Compare hashedEntry to iteratorEnd pointers.
Definition at line 306 of file HashTableI.H.
operator!=() [2/2]
bool operator!= (const iteratorEnd & unused) const inline
Definition at line 316 of file HashTableI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/HashTables/HashTable/HashTable.C
src/OpenFOAM/containers/HashTables/HashTable/HashTableI.H