OpenFOAM: StaticHashTableCore Struct Reference
StaticHashTableCore Struct Reference
Template-invariant bits for StaticHashTable.
Classes
struct iteratorEnd
A zero-sized end iterator.
Public Member Functions
StaticHashTableCore ()
Construct null.
ClassName ("StaticHashTable")
Define template name and debug.
Static Public Member Functions
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
Detailed Description
Template-invariant bits for StaticHashTable.
Definition at line 78 of file StaticHashTable.H.
Constructor & Destructor Documentation
StaticHashTableCore()
StaticHashTableCore () inline
Construct null.
Definition at line 84 of file StaticHashTable.H.
References StaticHashTableCore::ClassName().
Member Function Documentation
canonicalSize()
Foam::label canonicalSize (const label size) static
Return a canonical (power-of-two) size.
Definition at line 35 of file StaticHashTable.C.
Referenced by StaticHashTableCore::iteratorEnd::iteratorEnd(), and StaticHashTable< T, Key, Hash >::resize().
ClassName()
ClassName ("StaticHashTable")
Define template name and debug.
Referenced by StaticHashTableCore::StaticHashTableCore().
The documentation for this struct was generated from the following files:
src/OpenFOAM/containers/HashTables/StaticHashTable/StaticHashTable.H
src/OpenFOAM/containers/HashTables/StaticHashTable/StaticHashTable.C