OpenFOAM: DictionaryBase< IDLListType, T > Class Template Reference
DictionaryBase< IDLListType, T > Class Template Reference
Base dictionary class templated on both the form of doubly-linked list it uses as well as the type it holds.
Public Member Functions
DictionaryBase (const label size=128)
Construct given initial table size.
DictionaryBase (const DictionaryBase &)
Copy construct.
template<class INew >
DictionaryBase (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
DictionaryBase (Istream &)
Construct from Istream using default Istream constructor class.
bool found (const word &) const
Search DictionaryBase for given keyword.
const T * lookupPtr (const word &) const
Find and return an entry if present, otherwise return nullptr.
T * lookupPtr (const word &)
Find and return an entry if present, otherwise return nullptr.
const T * lookup (const word &) const
Find and return entry.
T * lookup (const word &)
Find and return entry.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the table of contents as a sorted list.
void insert (const word &, T *)
Add at head of dictionary.
void append (const word &, T *)
Add at tail of dictionary.
T * remove (const word &)
Remove and return entry specified by keyword.
void clear ()
Clear the dictionary.
void transfer (DictionaryBase< IDLListType, T > &)
Transfer the contents of the argument into this DictionaryBase.
void operator= (const DictionaryBase &)
const T * operator[] (const word &key) const
Find and return entry.
T * operator[] (const word &key)
Find and return entry.
Protected Member Functions
void addEntries ()
Protected Attributes
HashTable< T * > hashedTs_
HashTable of the entries held on the IDLListType for quick lookup.
Friends
Ostream & operator (Ostream &, const DictionaryBase< IDLListType, T > &)
Detailed Description
template<class IDLListType, class T>
class Foam::DictionaryBase< IDLListType, T >
Base dictionary class templated on both the form of doubly-linked list it uses as well as the type it holds.
The double templating allows for the instantiation of forms with or without storage management.
Note
The IDLListType parameter should itself be a template but this confused gcc 2.95.2 so it has to be instantiated for T when an instantiation of DictionaryBase is requested
See also
Dictionary and UDictionary
Source files
DictionaryBase.H
DictionaryBase.C
DictionaryBaseIO.C
Definition at line 61 of file DictionaryBase.H.
Constructor & Destructor Documentation
DictionaryBase() [1/4]
DictionaryBase (const label size = 128)
Construct given initial table size.
Definition at line 48 of file DictionaryBase.C.
Referenced by DictionaryBase< DLPtrList< T >, T >::DictionaryBase().
DictionaryBase() [2/4]
DictionaryBase (const DictionaryBase< IDLListType, T > & dict)
Copy construct.
Definition at line 56 of file DictionaryBase.C.
DictionaryBase() [3/4]
DictionaryBase (Istream & is, const INew & iNew)
Construct from Istream using given Istream constructor class.
Definition at line 69 of file DictionaryBase.C.
DictionaryBase() [4/4]
DictionaryBase (Istream & is)
Construct from Istream using default Istream constructor class.
Definition at line 81 of file DictionaryBase.C.
Member Function Documentation
addEntries()
void addEntries () protected
Definition at line 31 of file DictionaryBase.C.
found()
bool found (const word & keyword) const
Search DictionaryBase for given keyword.
Definition at line 92 of file DictionaryBase.C.
lookupPtr() [1/2]
const T * lookupPtr (const word & keyword) const
Find and return an entry if present, otherwise return nullptr.
Definition at line 100 of file DictionaryBase.C.
Referenced by Foam::debug::addDebugObject(), Foam::debug::addDimensionedConstantObject(), Foam::debug::addDimensionSetObject(), Foam::debug::addInfoObject(), Foam::debug::addOptimisationObject(), DictionaryBase< DLPtrList< T >, T >::found(), and Time::readDict().
lookupPtr() [2/2]
T * lookupPtr (const word & keyword)
Find and return an entry if present, otherwise return nullptr.
Definition at line 118 of file DictionaryBase.C.
lookup() [1/2]
const T * lookup (const word & keyword) const
Find and return entry.
Definition at line 134 of file DictionaryBase.C.
Referenced by DictionaryBase< DLPtrList< T >, T >::operator[]().
lookup() [2/2]
T * lookup (const word & keyword)
Find and return entry.
Definition at line 150 of file DictionaryBase.C.
toc()
Foam::wordList toc () const
Return the table of contents.
Definition at line 166 of file DictionaryBase.C.
sortedToc()
Foam::wordList sortedToc () const
Return the table of contents as a sorted list.
Definition at line 186 of file DictionaryBase.C.
insert()
void insert (const word & keyword, T * tPtr)
Add at head of dictionary.
Definition at line 193 of file DictionaryBase.C.
append()
void append (const word & keyword, T * tPtr)
Add at tail of dictionary.
Definition at line 202 of file DictionaryBase.C.
Referenced by Foam::debug::addDebugObject(), Foam::debug::addDimensionedConstantObject(), Foam::debug::addDimensionSetObject(), Foam::debug::addInfoObject(), and Foam::debug::addOptimisationObject().
remove()
T * remove (const word & keyword)
Remove and return entry specified by keyword.
Return nullptr if the keyword was not found.
Definition at line 211 of file DictionaryBase.C.
clear()
void clear ()
Clear the dictionary.
Definition at line 229 of file DictionaryBase.C.
transfer()
void transfer (DictionaryBase< IDLListType, T > & dict)
Transfer the contents of the argument into this DictionaryBase.
and annul the argument.
Definition at line 238 of file DictionaryBase.C.
Referenced by DictionaryBase< DLPtrList< T >, T >::clear().
operator=()
void operator= (const DictionaryBase< IDLListType, T > &)
Definition at line 251 of file DictionaryBase.C.
operator[]() [1/2]
const T* operator[] (const word & key) const inline
Find and return entry.
Definition at line 159 of file DictionaryBase.H.
operator[]() [2/2]
T* operator[] (const word & key) inline
Find and return entry.
Definition at line 165 of file DictionaryBase.H.
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const DictionaryBase< IDLListType, T > &) friend
Member Data Documentation
hashedTs_
HashTable<T*> hashedTs_ protected
HashTable of the entries held on the IDLListType for quick lookup.
Definition at line 81 of file DictionaryBase.H.
Referenced by DictionaryBase< DLPtrList< T >, T >::transfer().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Dictionaries/DictionaryBase/DictionaryBase.H
src/OpenFOAM/containers/Dictionaries/DictionaryBase/DictionaryBase.C