OpenFOAM: StaticHashTable< T, Key, Hash > Class Template Reference
StaticHashTable< T, Key, Hash > Class Template Reference
STL conforming hash table.
Classes
class Iterator
An STL iterator.
Public Types
typedef Iterator< T &, StaticHashTable< T, Key, Hash > &> iterator
typedef Iterator< const T &, const StaticHashTable< T, Key, Hash > &> const_iterator
typedef T value_type
Type of values the StaticHashTable contains.
typedef T & reference
Type that can be used for storing into StaticHashTable::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a StaticHashTable.
Public Member Functions
StaticHashTable (const label size=128)
Construct given initial table size.
StaticHashTable (Istream &, const label size=128)
Construct from Istream.
StaticHashTable (const StaticHashTable< T, Key, Hash > &)
Construct as copy.
StaticHashTable (const Xfer< StaticHashTable< T, Key, Hash >> &)
Construct by transferring the parameter contents.
~StaticHashTable ()
Destructor.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const Key &key) const
Return true if hashed entry is found in table.
iterator find (const Key &key)
Find and return an iterator set at the hashed entry.
const_iterator find (const Key &key) const
Find and return an const_iterator set at the hashed entry.
List< Key > toc () const
Return the table of contents.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const Key &key, const T &newElmt)
Insert a new hashed entry.
bool set (const Key &, const T &newElmt)
Assign a new hashed entry, overwriting existing entries.
bool erase (const iterator &it)
Erase an hashed entry specified by given iterator.
bool erase (const Key &key)
Erase an hashed entry specified by given key if in table.
void resize (const label newSize)
Resize the hash table for efficiency.
label erase (const StaticHashTable< T, Key, Hash > &)
Remove entries in the given hash table from this hash table.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void transfer (StaticHashTable< T, Key, Hash > &)
Transfer the contents of the argument table into this table.
Xfer< StaticHashTable< T, Key, Hash > > xfer ()
Transfer contents to the Xfer container.
T & operator[] (const Key &)
Find and return an hashed entry.
const T & operator[] (const Key &) const
Find and return an hashed entry.
T & operator() (const Key &)
Find and return an hashed entry, create it null if not present.
void operator= (const StaticHashTable< T, Key, Hash > &)
Assignment.
bool operator== (const StaticHashTable< T, Key, Hash > &) const
Equality. Two hash tables are equal if all contents of first are.
bool operator!= (const StaticHashTable< T, Key, Hash > &) const
The opposite of the equality operation.
iterator begin ()
Iterator set to the beginning of the StaticHashTable.
const iterator & end ()
Iterator set to beyond the end of the StaticHashTable.
const_iterator cbegin () const
const_iterator set to the beginning of the StaticHashTable
const const_iterator & cend () const
const_iterator set to beyond the end of the StaticHashTable
const_iterator begin () const
const_iterator set to the beginning of the StaticHashTable
const const_iterator & end () const
const_iterator set to beyond the end of the StaticHashTable
Public Member Functions inherited from StaticHashTableCore
StaticHashTableCore ()
Construct null.
ClassName ("StaticHashTable")
Define template name and debug.
Friends
class Iterator< T &, StaticHashTable< T, Key, Hash > &>
class Iterator< const T &, const StaticHashTable< T, Key, Hash > &>
Istream & operator>> (Istream &, StaticHashTable< T, Key, Hash > &)
Ostream & operator (Ostream &, const StaticHashTable< T, Key, Hash > &)
Additional Inherited Members
Static Public Member Functions inherited from StaticHashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
Detailed Description
template<class T, class Key = word, class Hash = string::hash>
class Foam::StaticHashTable< T, Key, Hash >
STL conforming hash table.
Note
Uses straight lists as underlying type. Is slower to insert than the standard HashTable, but should be more memory efficient and faster to access.
Source files
StaticHashTable.H
StaticHashTableI.H
StaticHashTable.C
StaticHashTableIO.C
Definition at line 58 of file StaticHashTable.H.
Member Typedef Documentation
iterator
typedef Iterator< T&, StaticHashTable<T, Key, Hash>& > iterator
Definition at line 138 of file StaticHashTable.H.
const_iterator
typedef Iterator< const T&, const StaticHashTable<T, Key, Hash>& > const_iterator
Definition at line 150 of file StaticHashTable.H.
value_type
typedef T value_type
Type of values the StaticHashTable contains.
Definition at line 276 of file StaticHashTable.H.
reference
typedef T& reference
Type that can be used for storing into StaticHashTable::value_type.
objects. This type is usually List::value_type&.
Definition at line 280 of file StaticHashTable.H.
const_reference
typedef const T& const_reference
Type that can be used for storing into constant.
StaticHashTable::value_type objects. This type is usually const StaticHashTable::value_type&.
Definition at line 285 of file StaticHashTable.H.
size_type
typedef label size_type
The type that can represent the size of a StaticHashTable.
Definition at line 288 of file StaticHashTable.H.
Constructor & Destructor Documentation
StaticHashTable() [1/4]
StaticHashTable (const label size = 128)
Construct given initial table size.
Definition at line 62 of file StaticHashTable.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by StaticHashTable< T, Key, Hash >::StaticHashTable().
StaticHashTable() [2/4]
StaticHashTable (Istream & is, const label size = 128)
Construct from Istream.
Definition at line 34 of file StaticHashTableIO.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::operator>>().
StaticHashTable() [3/4]
StaticHashTable (const StaticHashTable< T, Key, Hash > & ht)
Construct as copy.
Definition at line 82 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::StaticHashTable().
StaticHashTable() [4/4]
StaticHashTable (const Xfer< StaticHashTable< T, Key, Hash >> & ht)
Construct by transferring the parameter contents.
Definition at line 97 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::transfer().
~StaticHashTable()
~StaticHashTable ()
Destructor.
Definition at line 115 of file StaticHashTable.C.
Member Function Documentation
size()
Foam::label size () const inline
Return number of elements in table.
Definition at line 45 of file StaticHashTableI.H.
Referenced by StaticHashTable< T, Key, Hash >::printInfo().
empty()
bool empty () const inline
Return true if the hash table is empty.
Definition at line 52 of file StaticHashTableI.H.
References StaticHashTable< T, Key, Hash >::insert().
found()
bool found (const Key & key) const
Return true if hashed entry is found in table.
Definition at line 122 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::find(), forAll, and InfoInFunction.
Referenced by StaticHashTable< T, Key, Hash >::erase().
find() [1/2]
Foam::StaticHashTable< T, Key, Hash >::iterator find (const Key & key)
Find and return an iterator set at the hashed entry.
If not found iterator = end()
Definition at line 152 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::end(), forAll, and InfoInFunction.
Referenced by StaticHashTable< T, Key, Hash >::erase(), StaticHashTable< T, Key, Hash >::found(), and StaticHashTable< T, Key, Hash >::operator==().
find() [2/2]
Foam::StaticHashTable< T, Key, Hash >::const_iterator find (const Key & key) const
Find and return an const_iterator set at the hashed entry.
If not found iterator = end()
Definition at line 184 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::cend(), forAll, and InfoInFunction.
toc()
Foam::List< Key > toc () const
Return the table of contents.
Definition at line 214 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::cbegin(), StaticHashTable< T, Key, Hash >::cend(), forAll, InfoInFunction, List< T >::setSize(), List< T >::size(), and Foam::T().
printInfo()
Foam::Ostream & printInfo (Ostream & os) const
Print information.
Definition at line 61 of file StaticHashTableIO.C.
References StaticHashTable< T, Key, Hash >::begin(), StaticHashTable< T, Key, Hash >::clear(), StaticHashTable< T, Key, Hash >::end(), Foam::endl(), Foam::exit(), IOstream::fatalCheck(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, token::info(), StaticHashTable< T, Key, Hash >::insert(), token::isLabel(), token::isPunctuation(), token::labelToken(), Foam::nl, Foam::operator>>(), token::pToken(), Istream::putBack(), Istream::readBeginList(), Istream::readEndList(), StaticHashTable< T, Key, Hash >::resize(), s(), StaticHashTable< T, Key, Hash >::size(), and T.
insert()
bool insert (const Key & key, const T & newElmt) inline
Insert a new hashed entry.
Definition at line 60 of file StaticHashTableI.H.
Referenced by StaticHashTable< T, Key, Hash >::empty(), StaticHashTable< T, Key, Hash >::operator=(), StaticHashTable< T, Key, Hash >::printInfo(), and StaticHashTable< T, Key, Hash >::resize().
set()
bool set (const Key & key, const T & newElmt) inline
Assign a new hashed entry, overwriting existing entries.
Definition at line 71 of file StaticHashTableI.H.
erase() [1/3]
bool erase (const iterator & it)
Erase an hashed entry specified by given iterator.
Definition at line 287 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::end(), InfoInFunction, List< T >::setSize(), and List< T >::size().
Referenced by StaticHashTable< T, Key, Hash >::erase().
erase() [2/3]
bool erase (const Key & key)
Erase an hashed entry specified by given key if in table.
Definition at line 342 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::end(), StaticHashTable< T, Key, Hash >::erase(), and StaticHashTable< T, Key, Hash >::find().
resize()
void resize (const label newSize)
Resize the hash table for efficiency.
Definition at line 380 of file StaticHashTable.C.
References Foam::abort(), StaticHashTableCore::canonicalSize(), StaticHashTable< T, Key, Hash >::cbegin(), StaticHashTable< T, Key, Hash >::cend(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, StaticHashTable< T, Key, Hash >::insert(), and StaticHashTable< T, Key, Hash >::transfer().
Referenced by StaticHashTable< T, Key, Hash >::clearStorage(), and StaticHashTable< T, Key, Hash >::printInfo().
erase() [3/3]
Foam::label erase (const StaticHashTable< T, Key, Hash > & rhs)
Remove entries in the given hash table from this hash table.
Return the number of elements removed
Definition at line 359 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::begin(), StaticHashTable< T, Key, Hash >::end(), StaticHashTable< T, Key, Hash >::erase(), and StaticHashTable< T, Key, Hash >::found().
clear()
void clear ()
Clear all entries from table.
Definition at line 420 of file StaticHashTable.C.
References forAll.
Referenced by StaticHashTable< T, Key, Hash >::clearStorage(), StaticHashTable< T, Key, Hash >::operator=(), StaticHashTable< T, Key, Hash >::printInfo(), and StaticHashTable< T, Key, Hash >::transfer().
clearStorage()
void clearStorage ()
Clear the table entries and the table itself.
Equivalent to clear() followed by resize(1)
Definition at line 433 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::clear(), StaticHashTable< T, Key, Hash >::resize(), and StaticHashTable< T, Key, Hash >::transfer().
transfer()
void transfer (StaticHashTable< T, Key, Hash > & ht)
Transfer the contents of the argument table into this table.
and annul the argument table.
Definition at line 442 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::clear().
Referenced by StaticHashTable< T, Key, Hash >::clearStorage(), StaticHashTable< T, Key, Hash >::resize(), and StaticHashTable< T, Key, Hash >::StaticHashTable().
xfer()
Foam::Xfer< Foam::StaticHashTable< T, Key, Hash > > xfer () inline
Transfer contents to the Xfer container.
Definition at line 82 of file StaticHashTableI.H.
References Foam::xferMove().
operator[]() [1/2]
T & operator[] (const Key & key) inline
Find and return an hashed entry.
Definition at line 91 of file StaticHashTableI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and T.
operator[]() [2/2]
const T & operator[] (const Key & key) const inline
Find and return an hashed entry.
Definition at line 108 of file StaticHashTableI.H.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
operator()()
T & operator() (const Key & key) inline
Find and return an hashed entry, create it null if not present.
Definition at line 126 of file StaticHashTableI.H.
References insert(), and T.
operator=()
void operator= (const StaticHashTable< T, Key, Hash > & rhs)
Assignment.
Definition at line 469 of file StaticHashTable.C.
References Foam::abort(), StaticHashTable< T, Key, Hash >::cbegin(), StaticHashTable< T, Key, Hash >::cend(), StaticHashTable< T, Key, Hash >::clear(), Foam::FatalError, FatalErrorInFunction, and StaticHashTable< T, Key, Hash >::insert().
operator==()
bool operator== (const StaticHashTable< T, Key, Hash > & rhs) const
Equality. Two hash tables are equal if all contents of first are.
also in second and vice versa.
Definition at line 507 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::cbegin(), StaticHashTable< T, Key, Hash >::cend(), and StaticHashTable< T, Key, Hash >::find().
Referenced by StaticHashTable< T, Key, Hash >::operator!=().
operator!=()
bool operator!= (const StaticHashTable< T, Key, Hash > & rhs) const
The opposite of the equality operation.
Definition at line 529 of file StaticHashTable.C.
References StaticHashTable< T, Key, Hash >::operator==().
begin() [1/2]
Foam::StaticHashTable< T, Key, Hash >::iterator begin () inline
Iterator set to the beginning of the StaticHashTable.
Definition at line 337 of file StaticHashTableI.H.
References forAll, and Foam::Info.
Referenced by StaticHashTable< T, Key, Hash >::erase(), and StaticHashTable< T, Key, Hash >::printInfo().
end() [1/2]
const Foam::StaticHashTable< T, Key, Hash >::iterator & end () inline
Iterator set to beyond the end of the StaticHashTable.
Definition at line 361 of file StaticHashTableI.H.
Referenced by StaticHashTable< T, Key, Hash >::erase(), StaticHashTable< T, Key, Hash >::find(), and StaticHashTable< T, Key, Hash >::printInfo().
cbegin()
Foam::StaticHashTable< T, Key, Hash >::const_iterator cbegin () const inline
const_iterator set to the beginning of the StaticHashTable
Definition at line 369 of file StaticHashTableI.H.
References forAll, and Foam::Info.
Referenced by StaticHashTable< T, Key, Hash >::operator=(), StaticHashTable< T, Key, Hash >::operator==(), StaticHashTable< T, Key, Hash >::resize(), and StaticHashTable< T, Key, Hash >::toc().
cend()
const Foam::StaticHashTable< T, Key, Hash >::const_iterator & cend () const inline
const_iterator set to beyond the end of the StaticHashTable
Definition at line 393 of file StaticHashTableI.H.
Referenced by StaticHashTable< T, Key, Hash >::find(), StaticHashTable< T, Key, Hash >::operator=(), StaticHashTable< T, Key, Hash >::operator==(), StaticHashTable< T, Key, Hash >::resize(), and StaticHashTable< T, Key, Hash >::toc().
begin() [2/2]
Foam::StaticHashTable< T, Key, Hash >::const_iterator begin () const inline
const_iterator set to the beginning of the StaticHashTable
Definition at line 401 of file StaticHashTableI.H.
end() [2/2]
const Foam::StaticHashTable< T, Key, Hash >::const_iterator & end () const inline
const_iterator set to beyond the end of the StaticHashTable
Definition at line 409 of file StaticHashTableI.H.
Friends And Related Function Documentation
Iterator< T &, StaticHashTable< T, Key, Hash > &>
friend class Iterator< T &, StaticHashTable< T, Key, Hash > & > friend
Definition at line 159 of file StaticHashTable.H.
Iterator< const T &, const StaticHashTable< T, Key, Hash > &>
friend class Iterator< const T &, const StaticHashTable< T, Key, Hash > & > friend
Definition at line 165 of file StaticHashTable.H.
operator>>
Istream& operator>> (Istream & , StaticHashTable< T, Key, Hash > &) friend
operator
Ostream& operator (Ostream & , const StaticHashTable< T, Key, Hash > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/StaticHashTable/StaticHashTable.H
src/OpenFOAM/containers/HashTables/StaticHashTable/StaticHashTable.C
src/OpenFOAM/containers/HashTables/StaticHashTable/StaticHashTableI.H
src/OpenFOAM/containers/HashTables/StaticHashTable/StaticHashTableIO.C