OpenFOAM: HashTable< T, Key, Hash > Class Template Reference
HashTable< T, Key, Hash > Class Template Reference
An STL-conforming hash table.
Inherits HashTableCore.
Inherited by EdgeMap< label >, EdgeMap< scalar >, HashPtrTable< curve >, HashPtrTable< dragModel, interfacePair, interfacePair::symmHash >, HashPtrTable< Foam::Field >, HashPtrTable< Foam::GeometricField, Foam::phasePairKey, Foam::phasePairKey::hash >, HashPtrTable< Foam::OFstream >, HashPtrTable< Foam::sutherlandTransport >, HashPtrTable< IOobject >, HashPtrTable< ReactionThermo >, HashPtrTable< T, label, Hash< label > >, HashPtrTable< ThermoType >, HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash >, Map< dictionary >, Map< Foam::edge >, Map< Foam::List >, Map< Foam::Pair< Foam::edge > >, Map< Foam::splitCell *>, Map< Foam::Vector >, and Map< label >.
Classes
class const_iterator
An STL-conforming const_iterator.
class iterator
An STL-conforming iterator.
class iteratorBase
The iterator base for HashTable.
Public Types
typedef T value_type
Type of values the HashTable contains.
typedef T & reference
Type that can be used for storing into HashTable::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Member Functions
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< T, Key, Hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< T, Key, Hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< Key, T >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const Key &) const
Return true if hashedEntry is found in table.
iterator find (const Key &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const Key &) const
Find and return an const_iterator set at the hashedEntry.
List< Key > toc () const
Return the table of contents.
List< Key > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const Key &, const T &newElmt)
Insert a new hashedEntry.
bool set (const Key &, const T &newElmt)
Assign a new hashedEntry, overwriting existing entries.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const Key &)
Erase a hashedEntry specified by the given key.
label erase (const UList< Key > &)
Remove entries given by the listed keys from this HashTable.
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< T, Key, Hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< T, Key, Hash > > xfer ()
Transfer contents to the Xfer container.
T & operator[] (const Key &)
Find and return a hashedEntry.
const T & operator[] (const Key &) const
Find and return a hashedEntry.
T & operator() (const Key &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< T, Key, Hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< Key, T >>)
Assignment to an initializer list.
bool operator== (const HashTable< T, Key, Hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< T, Key, Hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &rhs)
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Friends
template<class T2 , class Key2 , class Hash2 >
class HashPtrTable
Declare friendship with the HashPtrTable class.
class iteratorBase
Declare friendship with the iteratorBase.
class iterator
Declare friendship with the iterator.
class const_iterator
Declare friendship with the const_iterator.
Istream & operator>> (Istream &, HashTable< T, Key, Hash > &)
Ostream & operator (Ostream &, const HashTable< T, Key, Hash > &)
Additional Inherited Members
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Detailed Description
template<class T, class Key = word, class Hash = string::hash>
class Foam::HashTable< T, Key, Hash >
An STL-conforming hash table.
Note
Hashing index collisions are handled via chaining using a singly-linked list with the colliding entry being added to the head of the linked list. Thus copying the hash table (or indeed even resizing it) will often result in a different hash order. Use a sorted table-of-contents when the hash order is important.
Source files
HashTable.H
HashTableI.H
HashTable.C
HashTableIO.C
Definition at line 62 of file HashTable.H.
Member Typedef Documentation
value_type
typedef T value_type
Type of values the HashTable contains.
Definition at line 332 of file HashTable.H.
reference
typedef T& reference
Type that can be used for storing into HashTable::value_type.
objects. This type is usually List::value_type&.
Definition at line 336 of file HashTable.H.
const_reference
typedef const T& const_reference
Type that can be used for storing into constant.
HashTable::value_type objects. This type is usually const HashTable::value_type&.
Definition at line 341 of file HashTable.H.
size_type
typedef label size_type
The type that can represent the size of a HashTable.
Definition at line 344 of file HashTable.H.
Constructor & Destructor Documentation
HashTable() [1/5]
HashTable (const label size = 128)
Construct given initial table size.
Definition at line 36 of file HashTable.C.
Referenced by HashTable< Foam::phase *>::HashTable().
HashTable() [2/5]
HashTable (Istream & is, const label size = 128)
Construct from Istream.
Definition at line 33 of file HashTableIO.C.
HashTable() [3/5]
HashTable (const HashTable< T, Key, Hash > & ht)
Construct as copy.
Definition at line 56 of file HashTable.C.
HashTable() [4/5]
HashTable (const Xfer< HashTable< T, Key, Hash >> & ht)
Construct by transferring the parameter contents.
Definition at line 69 of file HashTable.C.
HashTable() [5/5]
HashTable (std::initializer_list< Tuple2< Key, T >> lst)
Construct from an initializer list.
Definition at line 84 of file HashTable.C.
~HashTable()
~HashTable ()
Destructor.
Definition at line 100 of file HashTable.C.
Member Function Documentation
capacity()
Foam::label capacity () const inline
The size of the underlying table.
Definition at line 58 of file HashTableI.H.
size()
Foam::label size () const inline
Return number of elements in table.
Definition at line 65 of file HashTableI.H.
Referenced by singleProcessorFaceSetsConstraint::add(), cellTable::addCellZones(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), cellToFaceStencil::calcFaceStencil(), pointMVCWeight::calcWeights(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), primitiveMesh::checkEdgeLength(), motionSmootherAlgo::checkMesh(), edgeCollapser::checkMeshQuality(), coalCloudList::coalCloudList(), hexRef8::consistentSlowRefinement2(), cyclicPolyPatch::coupledEdges(), meshRefinement::dupNonManifoldPoints(), surfaceSets::getHangingCells(), combineFaces::getMergeSets(), removePoints::getUnrefimentSet(), meshToMesh::interpolationMethodAMI(), topoSet::invert(), IOobjectList::lookup(), IOobjectList::lookupClass(), meshToMesh::mapAndOpTgtToSrc(), polyBoundaryMesh::matchGroups(), meshRefinement::mergePatchFacesUndo(), NamedEnum< directionType, 3 >::names(), IOobjectList::names(), polyBoundaryMesh::neighbourEdges(), distribution::normalised(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), HashTable< Foam::phase *>::operator==(), Foam::polyMeshZipUpCells(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printFieldInfo(), distribution::raw(), boundaryMesh::readTriSurface(), pointFieldReconstructor::reconstructFields(), fvFieldReconstructor::reconstructFvSurfaceFields(), fvFieldReconstructor::reconstructFvVolumeFields(), fvFieldReconstructor::reconstructFvVolumeInternalFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), structuredRenumber::renumber(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), motionSmootherAlgo::scaleMesh(), polyTopoChange::setCapacity(), fvMeshSubset::setCellSubset(), duplicatePoints::setRefinement(), removePoints::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), hexRef8::setUnrefinement(), UnsortedMeshedSurface< Face >::sortedZones(), topoSet::subset(), triSurfaceRegionSearch::treeByRegion(), edgeVertex::updateLabels(), boundaryCutter::updateMesh(), localPointRegion::updateMesh(), meshCutAndRemove::updateMesh(), meshCutter::updateMesh(), graph::y(), and inverseDistanceDiffusivity::~inverseDistanceDiffusivity().
empty()
bool empty () const inline
Return true if the hash table is empty.
Definition at line 72 of file HashTableI.H.
Referenced by forces::calcForcesMoment(), and globalIndexAndTransform::transformIndicesForPatches().
found()
bool found (const Key & key) const
Return true if hashedEntry is found in table.
Definition at line 113 of file HashTable.C.
Referenced by fieldAverage::addMeanFieldType(), fieldAverage::addPrime2MeanFieldType(), searchableSurfaceToFaceZone::applyToSet(), faceZoneToFaceZone::applyToSet(), setToPointZone::applyToSet(), setToCellZone::applyToSet(), setToFaceZone::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), addPatchCellLayer::calcSidePatch(), layerAdditionRemoval::changeTopology(), edgeCollapser::checkMeshQuality(), edgeMeshFormatsCore::checkSupport(), surfaceFormatsCore::checkSupport(), motionSmootherAlgo::correct(), motionSmootherAlgo::correctBoundaryConditions(), cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), geomCellLooper::cut(), HashTable< Foam::phase *>::erase(), cellFeatures::faceMap(), polyMeshFilter::filter(), surfaceSets::getHangingCells(), removePoints::getUnrefimentSet(), topoSet::invert(), fvMeshAdder::MapDimFields(), fvMeshAdder::MapSurfaceFields(), fvMeshAdder::MapVolFields(), cellDistFuncs::maxPatchSize(), NamedEnum< directionType, 3 >::names(), UnsortedMeshedSurface< Face >::New(), MeshedSurface< Foam::face >::New(), ListPlusEqOp< T, Size >::operator()(), InflationInjection< CloudType >::parcelsToInject(), fvMeshDistribute::printFieldInfo(), STARCD::readBoundary(), STARCD::readCells(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), fvMeshSubset::setCellSubset(), cellTable::setName(), boundaryCutter::setRefinement(), cellDistFuncs::sumPatchSize(), surfaceIntersection::surfaceIntersection(), topoSetSource::usage(), UnsortedMeshedSurface< Face >::write(), MeshedSurface< Foam::face >::write(), and regionSizeDistribution::write().
find() [1/2]
Foam::HashTable< T, Key, Hash >::iterator find (const Key & key)
Find and return an iterator set at the hashedEntry.
If not found iterator = end()
Definition at line 142 of file HashTable.C.
Referenced by distribution::add(), cellTable::addCellZones(), faceZoneSet::addSet(), enrichedPatch::calcEnrichedFaces(), cellMatcher::calcLocalFaces(), createShellMesh::calcPointRegions(), GAMGAgglomeration::calculateRegionMaster(), primitiveMesh::checkFaceFaces(), objectRegistry::checkOut(), probes::classifyFields(), patchPatchDist::correct(), cyclicPolyPatch::coupledEdges(), cyclicACMIGAMGInterface::cyclicACMIGAMGInterface(), cyclicAMIGAMGInterface::cyclicAMIGAMGInterface(), cyclicGAMGInterface::cyclicGAMGInterface(), faceZoneSet::deleteSet(), HashTable< Foam::phase *>::find(), HashTable< Foam::phase *>::found(), snappySnapDriver::getZoneSurfacePoints(), polyBoundaryMesh::groupPatchIDs(), Foam::stringOps::inplaceExpand(), distribution::insertMissingKeys(), fvMeshSubset::interpolate(), lduPrimitiveMesh::lduPrimitiveMesh(), zone::localID(), IOobjectList::lookup(), PatchTools::matchEdges(), PatchTools::matchPoints(), polyMeshAdder::mergePoints(), globalMeshData::mergePoints(), polyTopoChange::modifyFace(), attachDetach::modifyMotionPoints(), slidingInterface::modifyMotionPoints(), polyTopoChange::modifyPoint(), cellTable::name(), NamedEnum< directionType, 3 >::names(), polyBoundaryMesh::neighbourEdges(), GAMGAgglomeration::New(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), Foam::parseNASCoord(), PatchTools::pointNormals(), fvMeshDistribute::printCoupleInfo(), processorGAMGInterface::processorGAMGInterface(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), wallBoundedStreamLine::read(), STARCD::readBoundary(), regionCoupledBaseGAMGInterface::regionCoupledBaseGAMGInterface(), cellTable::setName(), duplicatePoints::setRefinement(), tetDecomposer::setRefinement(), edgeCollapser::setRefinement(), combineFaces::setUnrefinement(), UnsortedMeshedSurface< Face >::sortedZones(), faceZoneSet::subset(), surfaceFeatures::surfaceFeatures(), syncTools::syncEdgeList(), syncTools::syncEdgeMap(), syncTools::syncPointList(), hexRef8::updateMesh(), vtkUnstructuredReader::vtkUnstructuredReader(), meshReader::warnDuplicates(), PrimitivePatch< Face, ::Foam::List, pointField, point >::whichPoint(), ZoneMesh< cellZone, polyMesh >::whichZone(), meshRefinement::zonify(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
find() [2/2]
Foam::HashTable< T, Key, Hash >::const_iterator find (const Key & key) const
Find and return an const_iterator set at the hashedEntry.
If not found iterator = end()
Definition at line 173 of file HashTable.C.
toc()
Foam::List< Key > toc () const
Return the table of contents.
Definition at line 202 of file HashTable.C.
Referenced by cellToCellStencil::calcFaceCells(), cellToFaceStencil::calcFaceCells(), surfaceFormatsCore::checkSupport(), triSurfaceTools::collapseEdges(), patchDataWave< TransferType >::correct(), meshRefinement::createBaffles(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findBox(), indexedOctree< Foam::treeDataFace >::findBox(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findSphere(), indexedOctree< Foam::treeDataFace >::findSphere(), triSurfaceTools::getVertexVertices(), InflationInjection< CloudType >::InflationInjection(), distribution::insertMissingKeys(), Foam::MapConsistentSubMesh(), distribution::mean(), attachDetach::modifyMotionPoints(), objectRegistry::names(), distribution::normalised(), ParticleErosion< CloudType >::ParticleErosion(), PatchPostProcessing< CloudType >::PatchPostProcessing(), Foam::polyMeshZipUpCells(), distribution::raw(), cellSetOption::setCellSet(), fvMeshSubset::setCellSubset(), and uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
sortedToc()
Foam::List< Key > sortedToc () const
Return the table of contents as a sorted list.
Definition at line 217 of file HashTable.C.
Referenced by preservePatchesConstraint::add(), singleProcessorFaceSetsConstraint::add(), preservePatchesConstraint::apply(), regIOobject::checkIn(), edgeMeshFormatsCore::checkSupport(), DispersionRASModel< CloudType >::epsilonModel(), coupleGroupIdentifier::findOtherPatchID(), DispersionRASModel< CloudType >::kModel(), sampledPatch::patchIDs(), and objectRegistry::sortedNames().
printInfo()
Foam::Ostream & printInfo (Ostream & os) const
Print information.
Definition at line 58 of file HashTableIO.C.
insert()
bool insert (const Key & key, const T & newElmt) inline
Insert a new hashedEntry.
Definition at line 80 of file HashTableI.H.
Referenced by IOobjectList::add(), distribution::add(), polyTopoChange::addCell(), polyTopoChange::addFace(), polyTopoChange::addPoint(), topoSetSource::addToUsageTable::addToUsageTable(), boundaryRegion::append(), cellTable::append(), addPatchCellLayer::calcSidePatch(), primitiveMesh::checkFaceFaces(), objectRegistry::checkIn(), patchPatchDist::correct(), cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), cyclicPolyPatch::coupledEdges(), globalMeshData::coupledPatchMeshEdgeMap(), HashTable< Foam::phase *>::empty(), polyMeshAdder::findSharedPoints(), polyBoundaryMesh::groupPatchIDs(), HashSet< label, Hash< label > >::insert(), distribution::insertMissingKeys(), IOobjectList::IOobjectList(), IOobjectList::lookup(), objectRegistry::lookupClass(), IOobjectList::lookupClass(), Foam::MapConsistentSubMesh(), polyTopoChange::modifyFace(), polyTopoChange::modifyPoint(), polyBoundaryMesh::neighbourEdges(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), ListPlusEqOp< T, Size >::operator()(), ifEqEqOp< value >::operator()(), cellTable::operator=(), Foam::parseNASCoord(), pointMVCWeight::pointMVCWeight(), OBJsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), functionObjectList::read(), wallBoundedStreamLine::read(), STARCD::readBoundary(), boundaryMesh::readTriSurface(), HashTable< Foam::phase *>::resize(), fvMeshSubset::setCellSubset(), removePoints::setRefinement(), boundaryCutter::setRefinement(), combineFaces::setRefinement(), tetDecomposer::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), combineFaces::setUnrefinement(), UnsortedMeshedSurface< Face >::sortedZones(), hexRef8::storeData(), meshReader::warnDuplicates(), meshRefinement::zonify(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().
set()
bool set (const Key & key, const T & newElmt) inline
Assign a new hashedEntry, overwriting existing entries.
Definition at line 91 of file HashTableI.H.
erase() [1/5]
bool erase (const iterator & iter)
Erase a hashedEntry specified by given iterator.
This invalidates the iterator until the next operator++
Definition at line 371 of file HashTable.C.
Referenced by objectRegistry::checkOut(), cellTable::combine(), cyclicPolyPatch::coupledEdges(), HashTable< Foam::phase *>::erase(), polyBoundaryMesh::groupPatchIDs(), polyBoundaryMesh::matchGroups(), polyTopoChange::modifyFace(), polyTopoChange::modifyPoint(), polyBoundaryMesh::neighbourEdges(), probes::prepare(), polyTopoChange::removeCell(), polyTopoChange::removeFace(), polyTopoChange::removePoint(), HashSet< label, Hash< label > >::unset(), vtkUnstructuredReader::vtkUnstructuredReader(), and regionSizeDistribution::write().
erase() [2/5]
bool erase (const Key & key)
Erase a hashedEntry specified by the given key.
Definition at line 383 of file HashTable.C.
erase() [3/5]
Foam::label erase (const UList< Key > & keys)
Remove entries given by the listed keys from this HashTable.
Return the number of elements removed
Definition at line 390 of file HashTable.C.
erase() [4/5]
label erase (const HashTable< AnyType, Key, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Return the number of elements removed. The parameter HashTable needs the same type of key, but the type of values held and the hashing function are arbitrary.
resize()
void resize (const label newSize)
Resize the hash table for efficiency.
Definition at line 432 of file HashTable.C.
Referenced by polyTopoChange::addMesh(), fvMeshDistribute::distribute(), polyTopoChange::setCapacity(), boundaryCutter::setRefinement(), removePoints::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), and hexRef8::storeData().
clear()
void clear ()
Clear all entries from table.
Definition at line 468 of file HashTable.C.
Referenced by decompositionMethod::calcCellCells(), cellToCellStencil::calcFaceCells(), cellToFaceStencil::calcFaceCells(), cellToFaceStencil::calcFaceStencil(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), primitiveMesh::checkFaceFaces(), edgeCollapser::checkMeshQuality(), functionObjectList::clear(), primitiveMesh::faceEdges(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), cellTable::operator=(), functionObjectList::read(), wallBoundedStreamLine::read(), boundaryRegion::readDict(), cellTable::readDict(), boundaryCutter::setRefinement(), tetDecomposer::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), hexRef8::setRefinement(), and snappyRefineDriver::snappyRefineDriver().
clearStorage()
void clearStorage ()
Clear the table entries and the table itself.
Equivalent to clear() followed by resize(0)
Definition at line 492 of file HashTable.C.
Referenced by polyTopoChange::changeMesh(), polyTopoChange::clear(), and polyTopoChange::makeMesh().
shrink()
void shrink ()
Shrink the allocated table to approx. twice number of elements.
Definition at line 500 of file HashTable.C.
transfer()
void transfer (HashTable< T, Key, Hash > & ht)
Transfer the contents of the argument table into this table.
and annul the argument table.
Definition at line 513 of file HashTable.C.
Referenced by primitiveMesh::checkEdgeLength(), polyBoundaryMesh::matchGroups(), functionObjectList::read(), boundaryCutter::updateMesh(), localPointRegion::updateMesh(), meshCutAndRemove::updateMesh(), and meshCutter::updateMesh().
xfer()
Foam::Xfer< Foam::HashTable< T, Key, Hash > > xfer () inline
Transfer contents to the Xfer container.
Definition at line 102 of file HashTableI.H.
Referenced by fvMeshDistribute::distribute().
operator[]() [1/2]
T & operator[] (const Key & key) inline
Find and return a hashedEntry.
Definition at line 111 of file HashTableI.H.
Referenced by boundaryRegion::boundaryType(), cellTable::combine(), and boundaryRegion::rename().
operator[]() [2/2]
const T & operator[] (const Key & key) const inline
Find and return a hashedEntry.
Definition at line 128 of file HashTableI.H.
operator()()
T & operator() (const Key & key) inline
Find and return a hashedEntry, create it null if not present.
Definition at line 145 of file HashTableI.H.
operator=() [1/2]
void operator= (const HashTable< T, Key, Hash > & rhs)
Assignment.
Definition at line 537 of file HashTable.C.
operator=() [2/2]
void operator= (std::initializer_list< Tuple2< Key, T >> lst)
Assignment to an initializer list.
Definition at line 568 of file HashTable.C.
operator==()
bool operator== (const HashTable< T, Key, Hash > & rhs) const
Equality. Hash tables are equal if the keys and values are equal.
Independent of table storage size and table order.
Definition at line 591 of file HashTable.C.
operator!=()
bool operator!= (const HashTable< T, Key, Hash > & rhs) const
The opposite of the equality operation. Takes linear time.
Definition at line 617 of file HashTable.C.
begin() [1/2]
Foam::HashTable< T, Key, Hash >::iterator begin () inline
Iterator set to the beginning of the HashTable.
Definition at line 419 of file HashTableI.H.
Referenced by distribution::add(), distribution::insertMissingKeys(), Foam::kShellIntegration(), basicThermo::lookupThermo(), fvMeshAdder::MapDimFields(), Foam::MapGeometricFields(), fvMeshAdder::MapSurfaceFields(), fvMeshAdder::MapVolFields(), polyBoundaryMesh::matchGroups(), boundaryCutter::updateMesh(), regionSizeDistribution::write(), and graph::y().
cbegin()
Foam::HashTable< T, Key, Hash >::const_iterator cbegin () const inline
const_iterator set to the beginning of the HashTable
Definition at line 514 of file HashTableI.H.
Referenced by HashTable< Foam::phase *>::begin(), HashSet< label, Hash< label > >::HashSet(), HashTable< Foam::phase *>::HashTable(), HashTable< Foam::phase *>::operator=(), and HashTable< Foam::phase *>::operator==().
begin() [2/2]
Foam::HashTable< T, Key, Hash >::const_iterator begin () const inline
const_iterator set to the beginning of the HashTable
Definition at line 522 of file HashTableI.H.
erase() [5/5]
Foam::label erase (const HashTable< AnyType, Key, AnyHash > & rhs)
Definition at line 411 of file HashTable.C.
Friends And Related Function Documentation
HashPtrTable
friend class HashPtrTable friend
Declare friendship with the HashPtrTable class.
Definition at line 184 of file HashTable.H.
iteratorBase
friend class iteratorBase friend
Declare friendship with the iteratorBase.
Definition at line 191 of file HashTable.H.
iterator
friend class iterator friend
Declare friendship with the iterator.
Definition at line 194 of file HashTable.H.
const_iterator
friend class const_iterator friend
Declare friendship with the const_iterator.
Definition at line 197 of file HashTable.H.
operator>>
Istream& operator>> (Istream & , HashTable< T, Key, Hash > &) friend
operator
Ostream& operator (Ostream & , const HashTable< T, Key, Hash > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/HashTables/HashTable/HashTable.C
src/OpenFOAM/containers/HashTables/HashTable/HashTableI.H
src/OpenFOAM/containers/HashTables/HashTable/HashTableIO.C