OpenFOAM: LPtrList< LListBase, T >::iterator Class Reference
LPtrList< LListBase, T >::iterator Class Reference
An STL-conforming iterator.
Public Member Functions
iterator (LListBase_iterator baseIter)
Construct from base iterator.
T & operator* ()
T & operator() ()
Public Member Functions inherited from LList< LListBase, T >::iterator
iterator (LListBase_iterator baseIter)
Construct from base iterator.
T & operator* ()
T & operator() ()
iterator & operator++ ()
Detailed Description
template<class LListBase, class T>
class Foam::LPtrList< LListBase, T >::iterator
An STL-conforming iterator.
Definition at line 182 of file LPtrList.H.
Constructor & Destructor Documentation
iterator()
iterator (LListBase_iterator baseIter) inline
Construct from base iterator.
Definition at line 190 of file LPtrList.H.
Member Function Documentation
operator*()
T& operator* () inline
Definition at line 198 of file LPtrList.H.
References LList< LListBase, T >::iterator::operator*().
Referenced by LPtrList< LListBase, T >::iterator::operator()(), and LPtrList< LListBase, T >::const_iterator::operator()().
operator()()
T& operator() () inline
Definition at line 203 of file LPtrList.H.
References LPtrList< LListBase, T >::iterator::operator*().
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/LPtrList/LPtrList.H