OpenFOAM: FIFOStack< T > Class Template Reference
FIFOStack< T > Class Template Reference
A FIFO stack based on a singly-linked list.
Public Member Functions
T top () const
Return a copy of the top element.
T bottom () const
Return a copy of the bottom element.
void push (const T &a)
Push an element onto the stack.
T pop ()
Pop the bottom element off the stack.
Public Member Functions inherited from LList< LListBase, T >
LList ()
Null construct.
LList (T a)
Construct given initial T.
LList (Istream &)
Construct from Istream.
LList (const LList< LListBase, T > &)
Construct as copy.
LList (std::initializer_list< T >)
Construct from an initializer list.
~LList ()
Destructor.
T & first ()
Return the first entry added.
const T & first () const
Return const access to the first entry added.
T & last ()
Return the last entry added.
const T & last () const
Return const access to the last entry added.
void insert (const T &a)
Add at head of list.
void append (const T &a)
Add at tail of list.
T removeHead ()
Remove and return head.
T remove (link *l)
Remove and return element.
T remove (iterator &it)
Remove and return element specified by iterator.
void clear ()
Delete contents of list.
void transfer (LList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const LList< LListBase, T > &)
Assignment operator.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
Additional Inherited Members
Public Types inherited from LList< LListBase, T >
typedef T value_type
Type of values the LList contains.
typedef T & reference
Type that can be used for storing into value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a LList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Detailed Description
template<class T>
class Foam::FIFOStack< T >
A FIFO stack based on a singly-linked list.
Operations are push(), pop(), top(), bottom() and empty().
Source files
FIFOStack.H
FIFOStack.C
Definition at line 51 of file FIFOStack.H.
Member Function Documentation
top()
T top () const inline
Return a copy of the top element.
Definition at line 69 of file FIFOStack.H.
bottom()
T bottom () const inline
Return a copy of the bottom element.
Definition at line 75 of file FIFOStack.H.
push()
void push (const T & a) inline
Push an element onto the stack.
Definition at line 84 of file FIFOStack.H.
Referenced by PFA< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), and DRGEP< CompType, ThermoType >::reduceMechanism().
pop()
T pop () inline
Pop the bottom element off the stack.
Definition at line 90 of file FIFOStack.H.
Referenced by PFA< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), and DRGEP< CompType, ThermoType >::reduceMechanism().
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/user/FIFOStack.H