OpenFOAM: LList< LListBase, T >::link Struct Reference
LList< LListBase, T >::link Struct Reference
Link structure.
Public Member Functions
link (T a)
Construct given object.
Public Attributes
T obj_
Stored object.
Detailed Description
template<class LListBase, class T>
struct Foam::LList< LListBase, T >::link
Link structure.
Definition at line 90 of file LList.H.
Constructor & Destructor Documentation
link()
link (T a) inline
Construct given object.
Definition at line 98 of file LList.H.
Referenced by LList< Foam::chemPointISAT< CompType, ThermoType > *>::append(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::first(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::insert(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::last(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::remove(), and LList< Foam::chemPointISAT< CompType, ThermoType > *>::removeHead().
Member Data Documentation
obj_
T obj_
Stored object.
Definition at line 95 of file LList.H.
Referenced by LList< Foam::chemPointISAT< CompType, ThermoType > *>::first(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::last(), LList< LListBase, T >::iterator::operator*(), and LList< LListBase, T >::const_iterator::operator*().
The documentation for this struct was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LList.H