OpenFOAM: UILList< LListBase, T >::iterator Class Reference
UILList< LListBase, T >::iterator Class Reference
An STL-conforming iterator.
Public Member Functions
iterator (LListBase_iterator baseIter)
Construct from base iterator.
T & operator* ()
T & operator() ()
iterator & operator++ ()
Detailed Description
template<class LListBase, class T>
class Foam::UILList< LListBase, T >::iterator
An STL-conforming iterator.
Definition at line 178 of file UILList.H.
Constructor & Destructor Documentation
iterator()
iterator (LListBase_iterator baseIter) inline
Construct from base iterator.
Definition at line 186 of file UILList.H.
Member Function Documentation
operator*()
T& operator* () inline
Definition at line 194 of file UILList.H.
References Foam::operator*(), and Foam::T().
Referenced by UILList< LListBase, T >::iterator::operator()(), UILList< LListBase, T >::const_iterator::operator()(), and UILList< LListBase, T >::const_reverse_iterator::operator()().
operator()()
T& operator() () inline
Definition at line 199 of file UILList.H.
References UILList< LListBase, T >::iterator::operator*().
operator++()
iterator& operator++ () inline
Definition at line 204 of file UILList.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/UILList/UILList.H