OpenFOAM: UILList< LListBase, T >::const_iterator Class Reference
UILList< LListBase, T >::const_iterator Class Reference
An STL-conforming const_iterator.
Public Member Functions
const_iterator (LListBase_const_iterator baseIter)
Construct from base const_iterator.
const_iterator (LListBase_iterator baseIter)
Construct from base iterator.
const T & operator* ()
const T & operator() ()
const_iterator & operator++ ()
Detailed Description
template<class LListBase, class T>
class Foam::UILList< LListBase, T >::const_iterator
An STL-conforming const_iterator.
Definition at line 227 of file UILList.H.
Constructor & Destructor Documentation
const_iterator() [1/2]
const_iterator (LListBase_const_iterator baseIter) inline
Construct from base const_iterator.
Definition at line 235 of file UILList.H.
const_iterator() [2/2]
const_iterator (LListBase_iterator baseIter) inline
Construct from base iterator.
Definition at line 241 of file UILList.H.
Member Function Documentation
operator*()
const T& operator* () inline
Definition at line 249 of file UILList.H.
References Foam::operator*(), and Foam::T().
operator()()
const T& operator() () inline
Definition at line 256 of file UILList.H.
References UILList< LListBase, T >::iterator::operator*().
operator++()
const_iterator& operator++ () inline
Definition at line 261 of file UILList.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/UILList/UILList.H