OpenFOAM: LPtrList< LListBase, T > Class Template Reference
LPtrList< LListBase, T > Class Template Reference
Template class for non-intrusive linked PtrLists.
Classes
class const_iterator
An STL-conforming const_iterator.
class iterator
An STL-conforming iterator.
Public Types
typedef T & reference
Type that can be used for storing into LPtrList::value_type.
typedef T & const_reference
Type that can be used for storing into constant.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Public Types inherited from LList< LListBase, T *>
typedef T * value_type
Type of values the LList contains.
typedef T * & reference
Type that can be used for storing into value_type.
typedef const T * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a LList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Public Member Functions
LPtrList ()
Null construct.
LPtrList (T *a)
Construct given initial T.
template<class INew >
LPtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
LPtrList (Istream &)
Construct from Istream using default Istream constructor class.
LPtrList (const LPtrList &)
Construct as copy.
~LPtrList ()
Destructor.
T & first ()
Return the first entry added.
const T & first () const
Return const access to the first entry added.
T & last ()
Return the last entry added.
const T & last () const
Return const access to the last entry added.
bool eraseHead ()
Remove the head element from the list and delete the pointer.
void clear ()
Clear the contents of the list.
void transfer (LPtrList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const LPtrList< LListBase, T > &)
Assign copy.
Public Member Functions inherited from LList< LListBase, T *>
LList ()
Null construct.
LList (T * a)
Construct given initial T.
LList (Istream &)
Construct from Istream.
LList (const LList< LListBase, T * > &)
Construct as copy.
LList (std::initializer_list< T * >)
Construct from an initializer list.
~LList ()
Destructor.
T * & first ()
Return the first entry added.
const T * & first () const
Return const access to the first entry added.
T * & last ()
Return the last entry added.
const T * & last () const
Return const access to the last entry added.
void insert (const T * &a)
Add at head of list.
void append (const T * &a)
Add at tail of list.
T * removeHead ()
Remove and return head.
T * remove (link *l)
Remove and return element.
T * remove (iterator &it)
Remove and return element specified by iterator.
void clear ()
Delete contents of list.
void transfer (LList< LListBase, T * > &)
Transfer the contents of the argument into this List.
void operator= (const LList< LListBase, T * > &)
Assignment operator.
void operator= (std::initializer_list< T * >)
Assignment to an initializer list.
iterator begin ()
const_iterator begin () const
const iterator & end ()
const const_iterator & end () const
const_iterator cbegin () const
const const_iterator & cend () const
Friends
class iterator
class const_iterator
Istream & operator>> (Istream &, LPtrList< LListBase, T > &)
Ostream & operator (Ostream &, const LPtrList< LListBase, T > &)
Detailed Description
template<class LListBase, class T>
class Foam::LPtrList< LListBase, T >
Template class for non-intrusive linked PtrLists.
Source files
LPtrList.H
LPtrList.C
LPtrListIO.C
Definition at line 47 of file LPtrList.H.
Member Typedef Documentation
reference
typedef T& reference
Type that can be used for storing into LPtrList::value_type.
objects.
Definition at line 170 of file LPtrList.H.
const_reference
typedef T& const_reference
Type that can be used for storing into constant.
LPtrList::value_type objects.
Definition at line 174 of file LPtrList.H.
LListBase_iterator
typedef LListBase::iterator LListBase_iterator
Definition at line 179 of file LPtrList.H.
LListBase_const_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Definition at line 212 of file LPtrList.H.
Constructor & Destructor Documentation
LPtrList() [1/5]
LPtrList () inline
Null construct.
Definition at line 94 of file LPtrList.H.
Referenced by LPtrList< LListBase, T >::LPtrList().
LPtrList() [2/5]
LPtrList (T * a) inline
Construct given initial T.
Definition at line 98 of file LPtrList.H.
References LPtrList< LListBase, T >::LPtrList(), and LPtrList< LListBase, T >::~LPtrList().
LPtrList() [3/5]
LPtrList (Istream & is, const INew & iNew)
Construct from Istream using given Istream constructor class.
Definition at line 143 of file LPtrListIO.C.
References Foam::read().
LPtrList() [4/5]
LPtrList (Istream & is)
Construct from Istream using default Istream constructor class.
Definition at line 150 of file LPtrListIO.C.
References LPtrList< LListBase, T >::clear(), Foam::nl, Foam::operator>>(), and Foam::read().
LPtrList() [5/5]
LPtrList (const LPtrList< LListBase, T > &)
Construct as copy.
~LPtrList()
~LPtrList ()
Destructor.
Definition at line 45 of file LPtrList.C.
References clear().
Referenced by LPtrList< LListBase, T >::LPtrList().
Member Function Documentation
first() [1/2]
T& first () inline
Return the first entry added.
Definition at line 123 of file LPtrList.H.
References LList< LListBase, T >::first().
first() [2/2]
const T& first () const inline
Return const access to the first entry added.
Definition at line 129 of file LPtrList.H.
References LList< LListBase, T >::first().
last() [1/2]
T& last () inline
Return the last entry added.
Definition at line 135 of file LPtrList.H.
References LList< LListBase, T >::last().
last() [2/2]
const T& last () const inline
Return const access to the last entry added.
Definition at line 141 of file LPtrList.H.
References LPtrList< LListBase, T >::clear(), LPtrList< LListBase, T >::eraseHead(), LList< LListBase, T >::last(), LPtrList< LListBase, T >::operator=(), Foam::T(), and LPtrList< LListBase, T >::transfer().
eraseHead()
bool eraseHead ()
Remove the head element from the list and delete the pointer.
Definition at line 54 of file LPtrList.C.
References T.
Referenced by LPtrList< LListBase, T >::last().
clear()
void clear ()
Clear the contents of the list.
Definition at line 70 of file LPtrList.C.
References clear().
Referenced by LPtrList< LListBase, T >::last(), and LPtrList< LListBase, T >::LPtrList().
transfer()
void transfer (LPtrList< LListBase, T > & lst)
Transfer the contents of the argument into this List.
and annul the argument list.
Definition at line 83 of file LPtrList.C.
References clear().
Referenced by LPtrList< LListBase, T >::last().
operator=()
void operator= (const LPtrList< LListBase, T > & lst)
Assign copy.
Definition at line 93 of file LPtrList.C.
References LList< LListBase, T *>::begin(), clear(), and LList< LListBase, T *>::end().
Referenced by LPtrList< LListBase, T >::last().
Friends And Related Function Documentation
iterator
friend class iterator friend
Definition at line 84 of file LPtrList.H.
const_iterator
friend class const_iterator friend
Definition at line 87 of file LPtrList.H.
operator>>
Istream& operator>> (Istream & , LPtrList< LListBase, T > &) friend
operator
Ostream& operator (Ostream & , const LPtrList< LListBase, T > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/accessTypes/LPtrList/LPtrList.H
src/OpenFOAM/containers/LinkedLists/accessTypes/LPtrList/LPtrList.C
src/OpenFOAM/containers/LinkedLists/accessTypes/LPtrList/LPtrListIO.C