OpenFOAM: UILList< LListBase, T > Class Template Reference
UILList< LListBase, T > Class Template Reference
Template class for intrusive linked lists.
Classes
class const_iterator
An STL-conforming const_iterator.
class const_reverse_iterator
An STL-conforming const_reverse_iterator.
class iterator
An STL-conforming iterator.
Public Types
typedef T value_type
Type of values the DLList contains.
typedef T & reference
Type that can be used for storing into DLList::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Public Member Functions
UILList ()
Null construct.
UILList (T *a)
Construct given initial T.
UILList (const UILList< LListBase, T > &)
Construct as copy.
T * first ()
Return the first entry.
const T * first () const
Return the first entry.
T * last ()
Return the last entry.
const T * last () const
Return the last entry.
T * removeHead ()
Remove and return head.
T * remove (T *p)
Remove and return element.
T * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< LListBase, T > &)
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< LListBase, T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< LListBase, T > &) const
The opposite of the equality operation. Takes linear time.
Friends
class iterator
class const_iterator
class const_reverse_iterator
Ostream & operator (Ostream &, const UILList< LListBase, T > &)
Detailed Description
template<class LListBase, class T>
class Foam::UILList< LListBase, T >
Template class for intrusive linked lists.
Source files
UILList.H
UILList.C
UILListIO.C
Definition at line 51 of file UILList.H.
Member Typedef Documentation
value_type
typedef T value_type
Type of values the DLList contains.
Definition at line 159 of file UILList.H.
reference
typedef T& reference
Type that can be used for storing into DLList::value_type.
objects.
Definition at line 163 of file UILList.H.
const_reference
typedef const T& const_reference
Type that can be used for storing into constant.
DLList::value_type objects.
Definition at line 167 of file UILList.H.
size_type
typedef label size_type
The type that can represent the size of a DLList.
Definition at line 170 of file UILList.H.
LListBase_iterator
typedef LListBase::iterator LListBase_iterator
Definition at line 175 of file UILList.H.
LListBase_const_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Definition at line 224 of file UILList.H.
Constructor & Destructor Documentation
UILList() [1/3]
UILList () inline
Null construct.
Definition at line 88 of file UILList.H.
Referenced by UILList< LListBase, T >::UILList().
UILList() [2/3]
UILList (T * a) inline
Construct given initial T.
Definition at line 92 of file UILList.H.
References UILList< LListBase, T >::UILList().
UILList() [3/3]
UILList (const UILList< LListBase, T > & lst)
Construct as copy.
Definition at line 31 of file UILList.C.
References UILList< LListBase, T >::begin(), and UILList< LListBase, T >::end().
Member Function Documentation
first() [1/2]
T* first () inline
Return the first entry.
Definition at line 106 of file UILList.H.
References Foam::T().
Referenced by interpolation2DTable< scalar >::interpolation2DTable(), snappyRefineDriver::snappyRefineDriver(), dictionaryEntry::startLineNumber(), and dictionary::startLineNumber().
first() [2/2]
const T* first () const inline
Return the first entry.
Definition at line 112 of file UILList.H.
References Foam::T().
last() [1/2]
T* last () inline
Return the last entry.
Definition at line 118 of file UILList.H.
References Foam::T().
Referenced by dictionaryEntry::endLineNumber(), dictionary::endLineNumber(), interpolation2DTable< scalar >::interpolation2DTable(), and dictionary::write().
last() [2/2]
const T* last () const inline
Return the last entry.
Definition at line 124 of file UILList.H.
References Foam::T().
removeHead()
T* removeHead () inline
Remove and return head.
Definition at line 133 of file UILList.H.
References Foam::T().
Referenced by ILList< LListBase, T >::eraseHead().
remove() [1/2]
T* remove (T * p) inline
Remove and return element.
Definition at line 139 of file UILList.H.
References p, and Foam::T().
Referenced by dictionary::add(), Cloud< streamLineParticle >::move(), and dictionary::remove().
remove() [2/2]
T* remove (iterator & it) inline
Remove and return specified by iterator.
Definition at line 145 of file UILList.H.
References UILList< LListBase, T >::operator=(), and Foam::T().
operator=()
void operator= (const UILList< LListBase, T > & rhs)
Definition at line 43 of file UILList.C.
References UILList< LListBase, T >::begin(), clear(), and UILList< LListBase, T >::end().
Referenced by UILList< LListBase, T >::remove().
begin() [1/2]
iterator begin () inline
Definition at line 211 of file UILList.H.
Referenced by Cloud< streamLineParticle >::begin(), ILList< LListBase, T >::ILList(), ILList< LListBase, T >::operator=(), UILList< LListBase, T >::operator=(), and UILList< LListBase, T >::UILList().
end() [1/2]
const iterator& end () inline
Definition at line 216 of file UILList.H.
Referenced by Cloud< streamLineParticle >::end(), ILList< LListBase, T >::ILList(), ILList< LListBase, T >::operator=(), UILList< LListBase, T >::operator=(), and UILList< LListBase, T >::UILList().
cbegin()
const_iterator cbegin () const inline
Definition at line 268 of file UILList.H.
Referenced by Cloud< streamLineParticle >::cbegin().
cend()
const const_iterator& cend () const inline
Definition at line 273 of file UILList.H.
Referenced by Cloud< streamLineParticle >::cend().
begin() [2/2]
const_iterator begin () const inline
Definition at line 278 of file UILList.H.
end() [2/2]
const const_iterator& end () const inline
Definition at line 283 of file UILList.H.
crbegin()
const_reverse_iterator crbegin () const inline
Definition at line 330 of file UILList.H.
crend()
const const_reverse_iterator& crend () const inline
Definition at line 335 of file UILList.H.
rbegin()
const_reverse_iterator rbegin () const inline
Definition at line 342 of file UILList.H.
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::readField().
rend()
const const_reverse_iterator& rend () const inline
Definition at line 347 of file UILList.H.
References UILList< LListBase, T >::operator!=(), and UILList< LListBase, T >::operator==().
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::readField().
operator==()
bool operator== (const UILList< LListBase, T > & rhs) const
Equality operation on ULists of the same type.
Returns true when the ULists are element-wise equal (using UList::value_type::operator==). Takes linear time.
Definition at line 56 of file UILList.C.
References Foam::equal().
Referenced by UILList< LListBase, T >::rend().
operator!=()
bool operator!= (const UILList< LListBase, T > & rhs) const
The opposite of the equality operation. Takes linear time.
Definition at line 81 of file UILList.C.
References Foam::operator==().
Referenced by UILList< LListBase, T >::rend().
Friends And Related Function Documentation
iterator
friend class iterator friend
Definition at line 75 of file UILList.H.
const_iterator
friend class const_iterator friend
Definition at line 78 of file UILList.H.
const_reverse_iterator
friend class const_reverse_iterator friend
Definition at line 81 of file UILList.H.
operator
Ostream& operator (Ostream & , const UILList< LListBase, T > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/accessTypes/UILList/UILList.H
src/OpenFOAM/containers/LinkedLists/accessTypes/UILList/UILList.C