OpenFOAM: ILList< LListBase, T > Class Template Reference
ILList< LListBase, T > Class Template Reference
Template class for intrusive linked lists.
Public Member Functions
ILList ()
Null construct.
ILList (T *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< LListBase, T > &)
Construct as copy.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
template<class INew >
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< LListBase, T > &)
Assignment operator.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()
Null construct.
UILList (T *a)
Construct given initial T.
UILList (const UILList< LListBase, T > &)
Construct as copy.
T * first ()
Return the first entry.
const T * first () const
Return the first entry.
T * last ()
Return the last entry.
const T * last () const
Return the last entry.
T * removeHead ()
Remove and return head.
T * remove (T *p)
Remove and return element.
T * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< LListBase, T > &)
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< LListBase, T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< LListBase, T > &) const
The opposite of the equality operation. Takes linear time.
Friends
Istream & operator>> (Istream &, ILList< LListBase, T > &)
Read List from Istream, discarding contents of existing List.
Additional Inherited Members
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values the DLList contains.
typedef T & reference
Type that can be used for storing into DLList::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Detailed Description
template<class LListBase, class T>
class Foam::ILList< LListBase, T >
Template class for intrusive linked lists.
Source files
ILList.H
ILList.C
ILListIO.C
Definition at line 50 of file ILList.H.
Constructor & Destructor Documentation
ILList() [1/6]
ILList () inline
Null construct.
Definition at line 80 of file ILList.H.
Referenced by ILList< LListBase, T >::ILList().
ILList() [2/6]
ILList (T * a) inline
Construct given initial T.
Definition at line 84 of file ILList.H.
References ILList< LListBase, T >::clear(), ILList< LListBase, T >::erase(), ILList< LListBase, T >::eraseHead(), ILList< LListBase, T >::ILList(), ILList< LListBase, T >::operator=(), p, Foam::T(), ILList< LListBase, T >::transfer(), and ILList< LListBase, T >::~ILList().
ILList() [3/6]
ILList (Istream & is)
Construct from Istream.
Definition at line 138 of file ILListIO.C.
References ILList< LListBase, T >::clear(), Foam::operator>>(), and Foam::read().
ILList() [4/6]
ILList (const ILList< LListBase, T > & lst)
Construct as copy.
Definition at line 31 of file ILList.C.
References UILList< LListBase, T >::begin(), UILList< LListBase, T >::end(), and ILList< LListBase, T >::ILList().
ILList() [5/6]
ILList (const ILList< LListBase, T > & lst, const CloneArg & cloneArg)
Copy constructor with additional argument for clone.
Definition at line 50 of file ILList.C.
References UILList< LListBase, T >::begin(), and UILList< LListBase, T >::end().
ILList() [6/6]
ILList (Istream & is, const INew & iNew)
Construct from Istream using given Istream constructor class.
Definition at line 131 of file ILListIO.C.
References Foam::read().
~ILList()
~ILList ()
Destructor.
Definition at line 72 of file ILList.C.
References ILList< LListBase, T >::clear().
Referenced by ILList< LListBase, T >::ILList().
Member Function Documentation
eraseHead()
bool eraseHead ()
Remove the head element specified from the list and delete it.
Definition at line 81 of file ILList.C.
References UILList< LListBase, T >::removeHead(), and Foam::T().
Referenced by ILList< LListBase, T >::clear(), and ILList< LListBase, T >::ILList().
erase()
bool erase (T * p)
Remove the specified element from the list and delete it.
Definition at line 96 of file ILList.C.
References Foam::T().
Referenced by ILList< LListBase, T >::ILList(), refinementSurfaces::refinementSurfaces(), and shellSurfaces::shellSurfaces().
clear()
void clear ()
Clear the contents of the list.
Definition at line 112 of file ILList.C.
References clear(), and ILList< LListBase, T >::eraseHead().
Referenced by Cloud< streamLineParticle >::clear(), DSMCCloud< DSMCParcel< ParcelType > >::clear(), dictionary::clear(), ILList< LListBase, T >::ILList(), ILList< LListBase, T >::operator=(), ILList< LListBase, T >::transfer(), and ILList< LListBase, T >::~ILList().
transfer()
void transfer (ILList< LListBase, T > & lst)
Transfer the contents of the argument into this List.
and annul the argument list.
Definition at line 125 of file ILList.C.
References ILList< LListBase, T >::clear().
Referenced by ILList< LListBase, T >::ILList(), and dictionary::transfer().
operator=()
void operator= (const ILList< LListBase, T > & lst)
Assignment operator.
Definition at line 135 of file ILList.C.
References UILList< LListBase, T >::begin(), ILList< LListBase, T >::clear(), and UILList< LListBase, T >::end().
Referenced by ILList< LListBase, T >::ILList().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , ILList< LListBase, T > &) friend
Read List from Istream, discarding contents of existing List.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/accessTypes/ILList/ILList.H
src/OpenFOAM/containers/LinkedLists/accessTypes/ILList/ILList.C
src/OpenFOAM/containers/LinkedLists/accessTypes/ILList/ILListIO.C