OpenFOAM: PackedBoolList Class Reference
PackedBoolList Class Reference
A bit-packed bool list.
Public Member Functions
PackedBoolList ()
Construct null.
PackedBoolList (Istream &)
Construct from Istream.
PackedBoolList (const label size)
Construct with given size, initializes list to 0.
PackedBoolList (const label size, const bool val)
Construct with given size and value for all elements.
PackedBoolList (const PackedBoolList &)
Copy constructor.
PackedBoolList (const PackedList< 1 > &)
Copy constructor.
PackedBoolList (const Xfer< PackedBoolList > &)
Construct by transferring the parameter contents.
PackedBoolList (const Xfer< PackedList< 1 >> &)
Construct by transferring the parameter contents.
PackedBoolList (const Foam::UList< bool > &)
Construct from a list of bools.
PackedBoolList (const labelUList &indices)
Construct from a list of labels.
PackedBoolList (const UIndirectList< label > &indices)
Construct from a list of labels.
autoPtr< PackedBoolList > clone () const
Clone.
void set (const PackedList< 1 > &)
Set specified bits.
label set (const labelUList &indices)
Set the listed indices. Return number of elements changed.
label set (const UIndirectList< label > &indices)
Set the listed indices. Return number of elements changed.
void unset (const PackedList< 1 > &)
Unset specified bits.
label unset (const labelUList &indices)
Unset the listed indices. Return number of elements changed.
label unset (const UIndirectList< label > &indices)
Unset the listed indices. Return number of elements changed.
void subset (const PackedList< 1 > &)
Subset with the specified list.
label subset (const labelUList &indices)
Subset with the listed indices.
label subset (const UIndirectList< label > &indices)
Subset with the listed indices.
Xfer< labelList > used () const
Return indices of the used (true) elements as a list of labels.
void transfer (PackedBoolList &)
Transfer the contents of the argument list into this list.
void transfer (PackedList< 1 > &)
Transfer the contents of the argument list into this list.
Xfer< PackedBoolList > xfer ()
Transfer contents to the Xfer container.
void operator= (const bool val)
Assignment of all entries to the given value.
void operator= (const PackedBoolList &)
Assignment operator.
void operator= (const PackedList< 1 > &)
Assignment operator.
void operator= (const Foam::UList< bool > &)
Assignment operator.
void operator= (const labelUList &indices)
Assignment operator,.
void operator= (const UIndirectList< label > &)
Assignment operator,.
PackedBoolList operator~ () const
Complement operator.
PackedBoolList & operator &= (const PackedList< 1 > &)
And operator (lists may be dissimilar sizes)
PackedBoolList & operator &= (const labelUList &indices)
And operator (lists may be dissimilar sizes)
PackedBoolList & operator &= (const UIndirectList< label > &)
And operator (lists may be dissimilar sizes)
PackedBoolList & operator^= (const PackedList< 1 > &)
Xor operator (lists may be dissimilar sizes)
PackedBoolList & operator|= (const PackedList< 1 > &)
Or operator (lists may be dissimilar sizes)
PackedBoolList & operator|= (const labelUList &indices)
Or operator (lists may be dissimilar sizes),.
PackedBoolList & operator|= (const UIndirectList< label > &)
Or operator (lists may be dissimilar sizes),.
PackedBoolList & operator+= (const PackedList< 1 > &)
Add entries to this list, synonymous with the or operator.
PackedBoolList & operator+= (const labelUList &indices)
Add entries to this list, synonymous with the or operator.
PackedBoolList & operator+= (const UIndirectList< label > &)
Add entries to this list, synonymous with the or operator.
PackedBoolList & operator-= (const PackedList< 1 > &)
Remove entries from this list - unset the specified bits.
PackedBoolList & operator-= (const labelUList &indices)
Remove entries from this list - unset the specified bits.
PackedBoolList & operator-= (const UIndirectList< label > &)
Remove entries from this list - unset the specified bits.
template<class LabelListType >
Foam::label setIndices (const LabelListType &indices)
template<class LabelListType >
Foam::label unsetIndices (const LabelListType &indices)
template<class LabelListType >
Foam::label subsetIndices (const LabelListType &indices)
Public Member Functions inherited from PackedList< 1 >
label packedLength () const
The list length when packed.
PackedList ()
Null constructor.
PackedList (const label size)
Construct with given size, initializes list to 0.
PackedList (const label size, const unsigned val)
Construct with given size and value for all elements.
PackedList (Istream &)
Construct from Istream.
PackedList (const PackedList< nBits > &)
Copy constructor.
PackedList (const Xfer< PackedList< nBits >> &)
Construct by transferring the parameter contents.
PackedList (const labelUList &)
Construct from a list of labels.
PackedList (const UIndirectList< label > &)
Construct from an indirect list of labels.
autoPtr< PackedList< nBits > > clone () const
Clone.
label capacity () const
The number of elements that can be stored before reallocating.
label size () const
Number of entries.
bool empty () const
Return true if the list is empty (ie, size() is zero).
unsigned int get (const label) const
Get value at index I.
bool set (const label, const unsigned int val=~0u)
Set value at index I. Return true if value changed.
bool unset (const label)
Unset the entry at index I. Return true if value changed.
List< unsigned int > & storage ()
Return the underlying packed storage.
const List< unsigned int > & storage () const
Return the underlying packed storage.
std::streamsize byteSize () const
Return the binary size in number of characters.
unsigned int count () const
Count number of bits set, O(log(n))
Xfer< labelList > values () const
Return the values as a list of labels.
Ostream & printBits (Ostream &, const bool fullOutput=false) const
Print bit patterns, optionally output unused elements.
Ostream & printInfo (Ostream &, const bool fullOutput=false) const
Print information and bit patterns (with printBits)
bool trim ()
Trim any trailing zero elements.
void flip ()
Invert the bits in the addressable region.
void reset ()
Clear all bits.
void setCapacity (const label)
Alter the size of the underlying storage.
void resize (const label, const unsigned int &val=0u)
Reset addressable list size, does not shrink the allocated size.
void setSize (const label, const unsigned int &val=0u)
Alias for resize()
void reserve (const label)
Reserve allocation space for at least this size.
void clear ()
Clear the list, i.e. set addressable size to zero.
void clearStorage ()
Clear the list and delete storage.
void shrink ()
Shrink the allocated space to what is actually used.
void transfer (PackedList< nBits > &)
Transfer the contents of the argument list into this list.
Xfer< PackedList< nBits > > xfer ()
Transfer contents to the Xfer container.
Istream & read (Istream &)
Clear list and read from stream.
Ostream & write (Ostream &, const bool indexedOutput=false) const
Write, optionally with indexedOutput.
void writeEntry (Ostream &) const
Write as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write as a dictionary entry with keyword.
PackedList< nBits > & append (const unsigned int val)
Append a value at the end of the list.
unsigned int remove ()
Remove and return the last element.
unsigned int operator[] (const label) const
Get value at index I.
iteratorBase operator[] (const label)
Set value at index I.
void operator= (const unsigned int val)
Assignment of all entries to the given value. Takes linear time.
void operator= (const PackedList< nBits > &)
Assignment operator.
void operator= (const labelUList &)
Assignment operator.
void operator= (const UIndirectList< label > &)
Assignment operator.
iterator begin ()
Iterator set to the beginning of the PackedList.
const_iterator begin () const
const_iterator set to the beginning of the PackedList
iterator end ()
Iterator set to beyond the end of the PackedList.
const_iterator end () const
const_iterator set to beyond the end of the PackedList
const_iterator cbegin () const
const_iterator set to the beginning of the PackedList
const_iterator cend () const
const_iterator set to beyond the end of the PackedList
Public Member Functions inherited from PackedListCore
PackedListCore ()
Construct null.
ClassName ("PackedList")
Define template name and debug.
Additional Inherited Members
Static Public Member Functions inherited from PackedList< 1 >
static unsigned int max_bits ()
The max. number of bits that can be templated.
static unsigned int max_value ()
The max. value for an entry, which simultaneously the bit-mask.
static unsigned int packing ()
The number of entries per packed storage element.
static unsigned int maskLower (unsigned offset)
Masking for all bits below the offset.
Protected Types inherited from PackedList< 1 >
typedef unsigned int StorageType
typedef List< StorageType > StorageList
Protected Member Functions inherited from PackedList< 1 >
unsigned int readValue (Istream &is)
void setPair (Istream &)
Read an index/value pair and set accordingly.
void setPair (Istream &is)
Static Protected Member Functions inherited from PackedList< 1 >
static label packedLength (const label)
Calculate the list length when packed.
static unsigned int readValue (Istream &)
Read a list entry (allows for specialization)
Detailed Description
A bit-packed bool list.
In addition to the obvious memory advantage over using a List<bool>, this class also provides a number of bit-like operations.
Source files
PackedBoolList.H
PackedBoolListI.H
PackedBoolList.C
See also
Foam::PackedList
Definition at line 63 of file PackedBoolList.H.
Constructor & Destructor Documentation
PackedBoolList() [1/11]
PackedBoolList () inline
Construct null.
Definition at line 28 of file PackedBoolListI.H.
Referenced by PackedBoolList::clone(), and PackedBoolList::PackedBoolList().
PackedBoolList() [2/11]
PackedBoolList (Istream & is)
Construct from Istream.
Definition at line 159 of file PackedBoolList.C.
PackedBoolList() [3/11]
PackedBoolList (const label size) inline explicit
Construct with given size, initializes list to 0.
Definition at line 34 of file PackedBoolListI.H.
References PackedBoolList::PackedBoolList().
PackedBoolList() [4/11]
PackedBoolList (const label size, const bool val) inline
Construct with given size and value for all elements.
Definition at line 41 of file PackedBoolListI.H.
PackedBoolList() [5/11]
PackedBoolList (const PackedBoolList & lst) inline
Copy constructor.
Definition at line 50 of file PackedBoolListI.H.
PackedBoolList() [6/11]
PackedBoolList (const PackedList< 1 > & lst) inline explicit
Copy constructor.
Definition at line 56 of file PackedBoolListI.H.
PackedBoolList() [7/11]
PackedBoolList (const Xfer< PackedBoolList > & lst) inline
Construct by transferring the parameter contents.
Definition at line 62 of file PackedBoolListI.H.
References PackedBoolList::transfer().
PackedBoolList() [8/11]
PackedBoolList (const Xfer< PackedList< 1 >> & lst) inline
Construct by transferring the parameter contents.
Definition at line 70 of file PackedBoolListI.H.
PackedBoolList() [9/11]
PackedBoolList (const Foam::UList< bool > & lst) inline explicit
Construct from a list of bools.
Definition at line 76 of file PackedBoolListI.H.
References PackedBoolList::operator=().
PackedBoolList() [10/11]
PackedBoolList (const labelUList & indices) inline explicit
Construct from a list of labels.
using the labels as indices to indicate which bits are set
Definition at line 84 of file PackedBoolListI.H.
PackedBoolList() [11/11]
PackedBoolList (const UIndirectList< label > & indices) inline explicit
Construct from a list of labels.
using the labels as indices to indicate which bits are set
Definition at line 92 of file PackedBoolListI.H.
Member Function Documentation
clone()
Foam::autoPtr< Foam::PackedBoolList > clone () const inline
Clone.
Definition at line 101 of file PackedBoolListI.H.
References PackedBoolList::PackedBoolList().
set() [1/3]
void set (const PackedList< 1 > & lst)
Set specified bits.
Definition at line 169 of file PackedBoolList.C.
References PackedList< 1 >::storage(), PackedList< nBits >::storage(), and PackedList< 1 >::trim().
Referenced by dynamicRefineFvMesh::calculateProtectedCells(), dynamicRefineFvMesh::checkEightAnchorPoints(), hexRef8::consistentRefinement(), hexRef8::consistentSlowRefinement2(), dynamicRefineFvMesh::dynamicRefineFvMesh(), dynamicRefineFvMesh::extendMarkedCells(), hexRef8::faceLevel(), NASedgeFormat::read(), STARCDedgeFormat::read(), dynamicRefineFvMesh::refine(), dynamicRefineFvMesh::selectRefineCandidates(), PackedBoolList::subsetIndices(), dynamicRefineFvMesh::unrefine(), and triSurface::writeStats().
set() [2/3]
Foam::label set (const labelUList & indices)
Set the listed indices. Return number of elements changed.
Does auto-vivify for non-existent entries.
Definition at line 191 of file PackedBoolList.C.
set() [3/3]
Foam::label set (const UIndirectList< label > & indices)
Set the listed indices. Return number of elements changed.
Does auto-vivify for non-existent entries.
Definition at line 197 of file PackedBoolList.C.
unset() [1/3]
void unset (const PackedList< 1 > & lst)
Unset specified bits.
Definition at line 203 of file PackedBoolList.C.
References Foam::min(), PackedList< nBits >::packedLength(), PackedList< 1 >::packedLength(), PackedList< 1 >::storage(), and PackedList< nBits >::storage().
Referenced by hexRef8::faceLevel(), PackedBoolList::operator-=(), and PackedBoolList::unsetIndices().
unset() [2/3]
Foam::label unset (const labelUList & indices)
Unset the listed indices. Return number of elements changed.
Never auto-vivify entries.
Definition at line 219 of file PackedBoolList.C.
unset() [3/3]
Foam::label unset (const UIndirectList< label > & indices)
Unset the listed indices. Return number of elements changed.
Never auto-vivify entries.
Definition at line 225 of file PackedBoolList.C.
subset() [1/3]
void subset (const PackedList< 1 > & lst)
Subset with the specified list.
Definition at line 231 of file PackedBoolList.C.
References PackedList< 1 >::packedLength(), PackedList< 1 >::resize(), PackedList< nBits >::size(), PackedList< 1 >::size(), PackedList< 1 >::storage(), and PackedList< nBits >::storage().
Referenced by PackedBoolList::operator~().
subset() [2/3]
Foam::label subset (const labelUList & indices)
Subset with the listed indices.
Return number of elements subsetted.
Definition at line 252 of file PackedBoolList.C.
subset() [3/3]
Foam::label subset (const UIndirectList< label > & indices)
Subset with the listed indices.
Return number of elements subsetted.
Definition at line 258 of file PackedBoolList.C.
used()
Foam::Xfer< Foam::labelList > used () const
Return indices of the used (true) elements as a list of labels.
Definition at line 264 of file PackedBoolList.C.
References PackedList< 1 >::count(), forAll, List< T >::setSize(), List< T >::size(), and List< T >::xfer().
Referenced by sampledPlane::update().
transfer() [1/2]
void transfer (PackedBoolList & lst) inline
Transfer the contents of the argument list into this list.
and annul the argument list.
Definition at line 109 of file PackedBoolListI.H.
References PackedList< nBits >::transfer().
Referenced by PackedBoolList::PackedBoolList(), and PackedBoolList::subsetIndices().
transfer() [2/2]
void transfer (PackedList< 1 > & lst) inline
Transfer the contents of the argument list into this list.
and annul the argument list.
Definition at line 115 of file PackedBoolListI.H.
References PackedList< nBits >::transfer().
xfer()
Foam::Xfer< Foam::PackedBoolList > xfer () inline
Transfer contents to the Xfer container.
Definition at line 121 of file PackedBoolListI.H.
References Foam::xferMove().
operator=() [1/6]
void operator= (const bool val) inline
Assignment of all entries to the given value.
Definition at line 129 of file PackedBoolListI.H.
References PackedList< nBits >::operator=().
Referenced by PackedBoolList::PackedBoolList().
operator=() [2/6]
void operator= (const PackedBoolList & lst) inline
Assignment operator.
Definition at line 135 of file PackedBoolListI.H.
References PackedList< nBits >::operator=().
operator=() [3/6]
void operator= (const PackedList< 1 > & lst) inline
Assignment operator.
Definition at line 141 of file PackedBoolListI.H.
References PackedList< nBits >::operator=().
operator=() [4/6]
void operator= (const Foam::UList< bool > & lst)
Assignment operator.
Definition at line 289 of file PackedBoolList.C.
References forAll, PackedList< 1 >::setSize(), and UList< T >::size().
operator=() [5/6]
void operator= (const labelUList & indices) inline
Assignment operator,.
using the labels as indices to indicate which bits are set
Definition at line 147 of file PackedBoolListI.H.
References PackedList< 1 >::clear().
operator=() [6/6]
void operator= (const UIndirectList< label > & indices) inline
Assignment operator,.
using the labels as indices to indicate which bits are set
Definition at line 154 of file PackedBoolListI.H.
References PackedList< 1 >::clear().
operator~()
Foam::PackedBoolList operator~ () const inline
Complement operator.
Definition at line 162 of file PackedBoolListI.H.
References PackedList< nBits >::flip(), PackedBoolList::operator &=(), and PackedBoolList::subset().
operator &=() [1/3]
PackedBoolList& operator&= (const PackedList< 1 > &) inline
And operator (lists may be dissimilar sizes)
Referenced by PackedBoolList::operator~().
operator &=() [2/3]
PackedBoolList& operator&= (const labelUList & indices) inline
And operator (lists may be dissimilar sizes)
using the labels as indices to indicate which bits are set
operator &=() [3/3]
PackedBoolList& operator&= (const UIndirectList< label > &) inline
And operator (lists may be dissimilar sizes)
using the labels as indices to indicate which bits are set
operator^=()
Foam::PackedBoolList & operator^= (const PackedList< 1 > & lst)
Xor operator (lists may be dissimilar sizes)
Retains unique entries
Definition at line 302 of file PackedBoolList.C.
References PackedList< 1 >::storage(), PackedList< nBits >::storage(), PackedList< 1 >::trim(), and PackedList< nBits >::trim().
operator|=() [1/3]
Foam::PackedBoolList & operator|= (const PackedList< 1 > & lst) inline
Or operator (lists may be dissimilar sizes)
Definition at line 196 of file PackedBoolListI.H.
Referenced by PackedBoolList::operator+=().
operator|=() [2/3]
Foam::PackedBoolList & operator|= (const labelUList & indices) inline
Or operator (lists may be dissimilar sizes),.
using the labels as indices to indicate which bits are set
Definition at line 204 of file PackedBoolListI.H.
operator|=() [3/3]
Foam::PackedBoolList & operator|= (const UIndirectList< label > & indices) inline
Or operator (lists may be dissimilar sizes),.
using the labels as indices to indicate which bits are set
Definition at line 212 of file PackedBoolListI.H.
operator+=() [1/3]
Foam::PackedBoolList & operator+= (const PackedList< 1 > & lst) inline
Add entries to this list, synonymous with the or operator.
Definition at line 220 of file PackedBoolListI.H.
References PackedBoolList::operator|=().
operator+=() [2/3]
Foam::PackedBoolList & operator+= (const labelUList & indices) inline
Add entries to this list, synonymous with the or operator.
Definition at line 227 of file PackedBoolListI.H.
References PackedBoolList::operator|=().
operator+=() [3/3]
Foam::PackedBoolList & operator+= (const UIndirectList< label > & indices) inline
Add entries to this list, synonymous with the or operator.
Definition at line 234 of file PackedBoolListI.H.
References PackedBoolList::operator|=().
operator-=() [1/3]
Foam::PackedBoolList & operator-= (const PackedList< 1 > & lst) inline
Remove entries from this list - unset the specified bits.
Definition at line 241 of file PackedBoolListI.H.
References PackedBoolList::unset().
operator-=() [2/3]
Foam::PackedBoolList & operator-= (const labelUList & indices) inline
Remove entries from this list - unset the specified bits.
Definition at line 249 of file PackedBoolListI.H.
References PackedBoolList::unset().
operator-=() [3/3]
Foam::PackedBoolList & operator-= (const UIndirectList< label > & indices) inline
Remove entries from this list - unset the specified bits.
Definition at line 257 of file PackedBoolListI.H.
References PackedBoolList::unset().
setIndices()
Foam::label setIndices (const LabelListType & indices)
Definition at line 93 of file PackedBoolList.C.
References forAll, and PackedList< 1 >::reserve().
unsetIndices()
Foam::label unsetIndices (const LabelListType & indices)
Definition at line 112 of file PackedBoolList.C.
References forAll, and PackedBoolList::unset().
subsetIndices()
Foam::label subsetIndices (const LabelListType & indices)
Definition at line 128 of file PackedBoolList.C.
References PackedList< 1 >::clear(), PackedList< 1 >::empty(), forAll, PackedList< nBits >::reserve(), PackedBoolList::set(), PackedList< 1 >::size(), and PackedBoolList::transfer().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/PackedList/PackedBoolList.H
src/OpenFOAM/containers/Lists/PackedList/PackedBoolList.C
src/OpenFOAM/containers/Lists/PackedList/PackedBoolListI.H