OpenFOAM: FixedList< T, Size >::Hash< HashT > Class Template Reference
FixedList< T, Size >::Hash< HashT > Class Template Reference
Hashing function class.
Public Member Functions
Hash ()
unsigned operator() (const FixedList< T, Size > &, unsigned seed=0) const
Detailed Description
template<class T, unsigned Size>
template<class HashT = Hash<T>>
class Foam::FixedList< T, Size >::Hash< HashT >
Hashing function class.
Use Hasher directly for contiguous data. Otherwise hash incrementally.
Definition at line 93 of file FixedList.H.
Constructor & Destructor Documentation
Hash()
Hash () inline
Definition at line 96 of file FixedList.H.
References FixedList< T, Size >::cdata(), FixedList< T, Size >::checkIndex(), FixedList< T, Size >::checkSize(), FixedList< T, Size >::checkStart(), FixedList< T, Size >::clone(), FixedList< T, Size >::data(), FixedList< T, Size >::fcIndex(), FixedList< T, Size >::first(), FixedList< T, Size >::FixedList(), FixedList< T, Size >::last(), FixedList< T, Size >::null(), FixedList< T, Size >::operator, FixedList< T, Size >::operator=(), FixedList< T, Size >::operator[](), FixedList< T, Size >::rcIndex(), FixedList< T, Size >::resize(), FixedList< T, Size >::setSize(), FixedList< T, Size >::size(), Foam::T(), FixedList< T, Size >::transfer(), and FixedList< T, Size >::writeEntry().
Member Function Documentation
operator()()
unsigned operator() (const FixedList< T, Size > & lst, unsigned seed = 0) const inline
Definition at line 452 of file FixedListI.H.
References Foam::Hasher().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/FixedList/FixedList.H
src/OpenFOAM/containers/Lists/FixedList/FixedListI.H