OpenFOAM: dlLibraryTable Class Reference
dlLibraryTable Class Reference
A table of dynamically loaded libraries.
Public Member Functions
ClassName ("dlLibraryTable")
dlLibraryTable ()
Construct null.
dlLibraryTable (const dictionary &, const word &)
Construct from dictionary and name of 'libs' entry giving.
~dlLibraryTable ()
Destructor.
bool open (const fileName &name, const bool verbose=true)
Open the named library, optionally with warnings if problems occur.
bool close (const fileName &name, const bool verbose=true)
Close the named library, optionally with warnings if problems occur.
void * findLibrary (const fileName &name)
Find the handle of the named library.
bool open (const dictionary &, const word &libsEntry)
Open all the libraries listed in the 'libsEntry' entry in the.
template<class TablePtr >
bool open (const dictionary &, const word &libsEntry, const TablePtr &tablePtr)
Open all the libraries listed in the 'libsEntry' entry in the.
Detailed Description
A table of dynamically loaded libraries.
Source files
dlLibraryTable.H
dlLibraryTable.C
Definition at line 49 of file dlLibraryTable.H.
Constructor & Destructor Documentation
dlLibraryTable() [1/2]
dlLibraryTable ()
Construct null.
Definition at line 40 of file dlLibraryTable.C.
dlLibraryTable() [2/2]
dlLibraryTable (const dictionary & dict, const word & libsEntry)
Construct from dictionary and name of 'libs' entry giving.
the libraries to load
Definition at line 45 of file dlLibraryTable.C.
~dlLibraryTable()
~dlLibraryTable ()
Destructor.
Definition at line 56 of file dlLibraryTable.C.
References Foam::dlClose(), Foam::endl(), forAllReverse, InfoInFunction, and dlLibraryTable::open().
Member Function Documentation
ClassName()
ClassName ("dlLibraryTable")
open() [1/3]
bool open (const fileName & name, const bool verbose = true)
Open the named library, optionally with warnings if problems occur.
Definition at line 77 of file dlLibraryTable.C.
References dlLibraryTable::close(), Foam::dlOpen(), Foam::endl(), Foam::stringOps::expand(), InfoInFunction, and WarningInFunction.
Referenced by dlLibraryTable::findLibrary(), dlLibraryTable::open(), and dlLibraryTable::~dlLibraryTable().
close()
bool close (const fileName & name, const bool verbose = true)
Close the named library, optionally with warnings if problems occur.
Definition at line 123 of file dlLibraryTable.C.
References Foam::dlClose(), Foam::endl(), forAllReverse, InfoInFunction, fileName::null, and WarningInFunction.
Referenced by dlLibraryTable::open().
findLibrary()
void * findLibrary (const fileName & name)
Find the handle of the named library.
Definition at line 170 of file dlLibraryTable.C.
References forAllReverse, and dlLibraryTable::open().
open() [2/3]
bool open (const dictionary & dict, const word & libsEntry)
Open all the libraries listed in the 'libsEntry' entry in the.
given dictionary if present
Definition at line 191 of file dlLibraryTable.C.
References UList< T >::empty(), forAll, dictionary::found(), dictionary::lookup(), and dlLibraryTable::open().
open() [3/3]
bool open (const dictionary & dict, const word & libsEntry, const TablePtr & tablePtr)
Open all the libraries listed in the 'libsEntry' entry in the.
given dictionary if present and check the additions to the given constructor table
Definition at line 34 of file dlLibraryTableTemplates.C.
References Foam::endl(), forAll, dictionary::found(), dictionary::lookup(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/dlLibraryTable/dlLibraryTable.H
src/OpenFOAM/db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C
src/OpenFOAM/db/dynamicLibrary/dlLibraryTable/dlLibraryTableTemplates.C