OpenFOAM: functionEntry Class Reference
functionEntry Class Reference
A functionEntry causes entries to be added/manipulated on the specified dictionary given an input stream.
Public Member Functions
declareMemberFunctionSelectionTable (bool, functionEntry, execute, dictionaryIstream,(dictionary &parentDict, Istream &is),(parentDict, is))
declareMemberFunctionSelectionTable (bool, functionEntry, execute, primitiveEntryIstream,(const dictionary &parentDict, primitiveEntry &entry, Istream &is),(parentDict, entry, is))
Static Public Member Functions
static bool execute (const word &functionName, dictionary &parentDict, Istream &)
Execute the functionEntry in a sub-dict context.
static bool execute (const word &functionName, const dictionary &parentDict, primitiveEntry &, Istream &)
Execute the functionEntry in a primitiveEntry context.
Detailed Description
A functionEntry causes entries to be added/manipulated on the specified dictionary given an input stream.
In dictionaries, a '#' sigil is typically used for a functionEntry.
Source files
functionEntry.H
functionEntry.C
functionEntryIO.C
Definition at line 63 of file functionEntry.H.
Member Function Documentation
declareMemberFunctionSelectionTable() [1/2]
declareMemberFunctionSelectionTable (bool , functionEntry , execute , dictionaryIstream , (dictionary &parentDict, Istream &is) , (parentDict, is))
execute() [1/2]
bool execute (const word & functionName, dictionary & parentDict, Istream & is) static
Execute the functionEntry in a sub-dict context.
Definition at line 51 of file functionEntry.C.
References Foam::endl(), Foam::exit(), IOstream::fatalCheck(), Foam::FatalError, FatalErrorInFunction, IOstream::lineNumber(), IOstream::name(), and Foam::nl.
Referenced by entry::New().
declareMemberFunctionSelectionTable() [2/2]
declareMemberFunctionSelectionTable (bool , functionEntry , execute , primitiveEntryIstream , (const dictionary &parentDict, primitiveEntry &entry, Istream &is) , (parentDict, entry, is))
execute() [2/2]
bool execute (const word & functionName, const dictionary & parentDict, primitiveEntry & entry, Istream & is) static
Execute the functionEntry in a primitiveEntry context.
Definition at line 93 of file functionEntry.C.
References Foam::endl(), Foam::exit(), IOstream::fatalCheck(), Foam::FatalError, FatalErrorInFunction, IOstream::lineNumber(), IOstream::name(), and Foam::nl.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/functionEntries/functionEntry/functionEntry.H
src/OpenFOAM/db/dictionary/functionEntries/functionEntry/functionEntry.C