OpenFOAM: UPtrList< T >::const_iterator Class Reference
UPtrList< T >::const_iterator Class Reference
An STL-conforming const_iterator.
Public Types
typedef const T & Tref
Public Member Functions
const_iterator (const T *const *)
Construct for a given UPtrList entry.
const_iterator (const iterator &)
Construct from an iterator.
bool operator== (const const_iterator &) const
bool operator!= (const const_iterator &) const
Tref operator* ()
Tref operator() ()
const_iterator operator++ ()
const_iterator operator++ (int)
const_iterator operator-- ()
const_iterator operator-- (int)
const_iterator operator+= (label)
const_iterator operator-= (label)
const T & operator[] (label)
bool operator< (const const_iterator &) const
bool operator> (const const_iterator &) const
bool operator<= (const const_iterator &) const
bool operator>= (const const_iterator &) const
Friends
const_iterator operator+ (const const_iterator &, label)
const_iterator operator+ (label, const const_iterator &)
const_iterator operator- (const const_iterator &, label)
label operator- (const const_iterator &, const const_iterator &)
Detailed Description
template<class T>
class Foam::UPtrList< T >::const_iterator
An STL-conforming const_iterator.
Definition at line 302 of file UPtrList.H.
Member Typedef Documentation
Tref
typedef const T& Tref
Definition at line 320 of file UPtrList.H.
Constructor & Destructor Documentation
const_iterator() [1/2]
const_iterator (const T *const * ptr) inline
Construct for a given UPtrList entry.
Definition at line 305 of file UPtrListI.H.
const_iterator() [2/2]
const_iterator (const iterator & iter) inline
Construct from an iterator.
Definition at line 312 of file UPtrListI.H.
Member Function Documentation
operator==()
bool operator== (const const_iterator & iter) const inline
Definition at line 320 of file UPtrListI.H.
operator!=()
bool operator!= (const const_iterator & iter) const inline
Definition at line 330 of file UPtrListI.H.
operator*()
const T & operator* () inline
Definition at line 339 of file UPtrListI.H.
Referenced by UPtrList< T >::const_iterator::operator()().
operator()()
const T & operator() () inline
Definition at line 346 of file UPtrListI.H.
References UPtrList< T >::const_iterator::operator*().
operator++() [1/2]
Foam::UPtrList< T >::const_iterator operator++ () inline
Definition at line 354 of file UPtrListI.H.
operator++() [2/2]
Foam::UPtrList< T >::const_iterator operator++ (int) inline
Definition at line 363 of file UPtrListI.H.
operator--() [1/2]
Foam::UPtrList< T >::const_iterator operator-- () inline
Definition at line 373 of file UPtrListI.H.
operator--() [2/2]
Foam::UPtrList< T >::const_iterator operator-- (int) inline
Definition at line 382 of file UPtrListI.H.
operator+=()
Foam::UPtrList< T >::const_iterator operator+= (label n) inline
Definition at line 392 of file UPtrListI.H.
References n, and Foam::operator+().
operator-=()
Foam::UPtrList< T >::const_iterator operator-= (label n) inline
Definition at line 419 of file UPtrListI.H.
References n, Foam::operator-(), and Foam::T().
operator[]()
const T & operator[] (label n) inline
Definition at line 447 of file UPtrListI.H.
References n.
operator<()
bool operator< (const const_iterator & iter) const inline
Definition at line 455 of file UPtrListI.H.
operator>()
bool operator> (const const_iterator & iter) const inline
Definition at line 465 of file UPtrListI.H.
operator<=()
bool operator<= (const const_iterator & iter) const inline
Definition at line 475 of file UPtrListI.H.
operator>=()
bool operator>= (const const_iterator & iter) const inline
Definition at line 485 of file UPtrListI.H.
Friends And Related Function Documentation
operator+ [1/2]
const_iterator operator+ (const const_iterator & , label) friend
operator+ [2/2]
const_iterator operator+ (label , const const_iterator &) friend
operator- [1/2]
const_iterator operator- (const const_iterator & , label) friend
operator- [2/2]
label operator- (const const_iterator & , const const_iterator &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/UPtrList/UPtrList.H
src/OpenFOAM/containers/Lists/UPtrList/UPtrListI.H