OpenFOAM: NamedEnum< Enum, nEnum > Class Template Reference
NamedEnum< Enum, nEnum > Class Template Reference
Initialise the NamedEnum HashTable from the static list of names.
Inherits HashTable< int >.
Public Member Functions
NamedEnum ()
Construct from names.
Enum read (Istream &) const
Read a word from Istream and return the corresponding.
void write (const Enum e, Ostream &) const
Write the name representation of the enumeration to an Ostream.
const Enum operator[] (const char *name) const
Return the enumeration element corresponding to the given name.
const Enum operator[] (const word &name) const
Return the enumeration element corresponding to the given name.
const char * operator[] (const Enum e) const
Return the name of the given enumeration element.
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
template<>
const char * names []
Public Member Functions inherited from HashTable< int >
bool set (const word &, const int &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< int, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< int, word, string::hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< word, int >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const int &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Foam::label erase (const HashTable< AnyType, word, AnyHash > &rhs)
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< int, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< int, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
int & operator[] (const word &)
Find and return a hashedEntry.
const int & operator[] (const word &) const
Find and return a hashedEntry.
int & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< int, word, string::hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< word, int >>)
Assignment to an initializer list.
bool operator== (const HashTable< int, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< int, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Static Public Member Functions
static stringList strings ()
The set of names as a list of strings.
static wordList words ()
The set of names as a list of words.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes
static const char * names [nEnum]
The set of names corresponding to the enumeration Enum.
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Additional Inherited Members
Public Types inherited from HashTable< int >
typedef int value_type
Type of values the HashTable contains.
typedef int & reference
Type that can be used for storing into HashTable::value_type.
typedef const int & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Detailed Description
template<class Enum, int nEnum>
class Foam::NamedEnum< Enum, nEnum >
Initialise the NamedEnum HashTable from the static list of names.
Source files
NamedEnum.H
NamedEnum.C
Definition at line 52 of file NamedEnum.H.
Constructor & Destructor Documentation
NamedEnum()
NamedEnum ()
Construct from names.
Definition at line 31 of file NamedEnum.C.
Member Function Documentation
read()
Enum read (Istream & is) const
Read a word from Istream and return the corresponding.
enumeration element
Definition at line 61 of file NamedEnum.C.
Referenced by nastranSurfaceWriter::nastranSurfaceWriter(), solidificationMeltingSource::read(), addfileModificationCheckingToOpt::readData(), addcommsTypeToOpt::readData(), Time::readDict(), and sampledPatchInternalField::sampledPatchInternalField().
write()
void write (const Enum e, Ostream & os) const
Write the name representation of the enumeration to an Ostream.
Definition at line 79 of file NamedEnum.C.
strings()
Foam::stringList strings () static
The set of names as a list of strings.
Definition at line 86 of file NamedEnum.C.
words()
Foam::wordList words () static
The set of names as a list of words.
Definition at line 105 of file NamedEnum.C.
Referenced by mappedPatchBase::mappedPatchBase().
operator[]() [1/3]
const Enum operator[] (const char * name) const inline
Return the enumeration element corresponding to the given name.
Definition at line 101 of file NamedEnum.H.
operator[]() [2/3]
const Enum operator[] (const word & name) const inline
Return the enumeration element corresponding to the given name.
Definition at line 107 of file NamedEnum.H.
operator[]() [3/3]
const char* operator[] (const Enum e) const inline
Return the name of the given enumeration element.
Definition at line 113 of file NamedEnum.H.
names() [1/64]
const char * names ()
Definition at line 46 of file directions.C.
names() [2/64]
const char * names ()
Definition at line 41 of file tetDecomposer.C.
names() [3/64]
const char * names ()
Definition at line 54 of file slidingInterface.C.
names() [4/64]
const char * names ()
Definition at line 47 of file extendedEdgeMesh.C.
names() [5/64]
const char * names ()
Definition at line 60 of file extendedEdgeMesh.C.
names() [6/64]
const char * names ()
Definition at line 75 of file extendedEdgeMesh.C.
names() [7/64]
const char * names ()
Definition at line 37 of file coordSet.C.
names() [8/64]
const char * names ()
Definition at line 41 of file vtkUnstructuredReader.C.
names() [9/64]
const char * names ()
Definition at line 58 of file vtkUnstructuredReader.C.
names() [10/64]
const char * names ()
Definition at line 70 of file vtkUnstructuredReader.C.
names() [11/64]
const char * names ()
Definition at line 40 of file fanPressureFvPatchScalarField.C.
names() [12/64]
const char * names ()
Definition at line 45 of file waveSurfacePressureFvPatchScalarField.C.
names() [13/64]
const char * names ()
Definition at line 46 of file volRegion.C.
names() [14/64]
const char * names ()
Definition at line 45 of file fieldAverageItem.C.
names() [15/64]
const char * names ()
Definition at line 46 of file fieldMinMax.C.
names() [16/64]
const char * names ()
Definition at line 48 of file fieldValueDelta.C.
names() [17/64]
const char * names ()
Definition at line 57 of file surfaceFieldValue.C.
names() [18/64]
const char * names ()
Definition at line 69 of file surfaceFieldValue.C.
names() [19/64]
const char * names ()
Definition at line 52 of file volFieldValue.C.
names() [20/64]
const char * names ()
Definition at line 53 of file turbulenceFields.C.
names() [21/64]
const char * names ()
Definition at line 77 of file turbulenceFields.C.
names() [22/64]
const char * names ()
Definition at line 56 of file abort.C.
names() [23/64]
const char * names ()
Definition at line 53 of file writeObjects.C.
names() [24/64]
const char * names ()
Definition at line 44 of file surfaceDisplacementPointPatchVectorField.C.
names() [25/64]
const char * names ()
Definition at line 43 of file surfaceSlipDisplacementPointPatchVectorField.C.
names() [26/64]
const char * names ()
Definition at line 42 of file cellSetOption.C.
names() [27/64]
const char * names ()
Definition at line 44 of file solidificationMeltingSource.C.
names() [28/64]
const char * names ()
Definition at line 37 of file phaseProperties.C.
names() [29/64]
const char * names ()
Definition at line 70 of file meshRefinement.C.
names() [30/64]
const char * names ()
Definition at line 85 of file meshRefinement.C.
names() [31/64]
const char * names ()
Definition at line 95 of file meshRefinement.C.
names() [32/64]
const char * names ()
Definition at line 41 of file surfaceZonesInfo.C.
names() [33/64]
const char * names ()
Definition at line 60 of file surfaceZonesInfo.C.
names() [34/64]
const char * names ()
Definition at line 45 of file shellSurfaces.C.
names() [35/64]
const char * names ()
Definition at line 33 of file faceAreaIntersect.C.
names() [36/64]
const char * names ()
Definition at line 57 of file mappedPatchBase.C.
names() [37/64]
const char * names ()
Definition at line 72 of file mappedPatchBase.C.
names() [38/64]
const char * names ()
Definition at line 45 of file faceToCell.C.
names() [39/64]
const char * names ()
Definition at line 44 of file faceZoneToCell.C.
names() [40/64]
const char * names ()
Definition at line 45 of file pointToCell.C.
names() [41/64]
const char * names ()
Definition at line 46 of file cellToFace.C.
names() [42/64]
const char * names ()
Definition at line 45 of file pointToFace.C.
names() [43/64]
const char * names ()
Definition at line 45 of file cellToPoint.C.
names() [44/64]
const char * names ()
Definition at line 45 of file faceToPoint.C.
names() [45/64]
const char * names ()
Definition at line 43 of file topoSetSource.C.
names() [46/64]
const char * names ()
Definition at line 37 of file volumeType.C.
names() [47/64]
const char * names ()
Definition at line 43 of file UPstream.C.
names() [48/64]
const char * names ()
Definition at line 42 of file regIOobject.C.
names() [49/64]
const char * names ()
Definition at line 43 of file Time.C.
names() [50/64]
const char * names ()
Definition at line 56 of file Time.C.
names() [51/64]
const char * names ()
Definition at line 40 of file coupledPolyPatch.C.
names() [52/64]
const char * names ()
Definition at line 39 of file intersection.C.
names() [53/64]
const char * names ()
Definition at line 50 of file intersection.C.
names() [54/64]
const char * names ()
Definition at line 60 of file fileMonitor.C.
names() [55/64]
const char * names ()
Definition at line 59 of file distributedTriSurfaceMesh.C.
names() [56/64]
const char * names ()
Definition at line 40 of file energyRegionCoupledFvPatchScalarField.C.
names() [57/64]
const char * names ()
Definition at line 42 of file meshToMesh.C.
names() [58/64]
const char * names ()
Definition at line 49 of file sampledTriSurfaceMesh.C.
names() [59/64]
const char * names ()
Definition at line 42 of file nastranSurfaceWriter.C.
names() [60/64]
const char * names ()
Definition at line 48 of file radiationCoupledBase.C.
names() [61/64]
const char * names ()
Definition at line 42 of file alphaContactAngleFvPatchScalarField.C.
names() [62/64]
const char * names ()
Definition at line 42 of file externalWallHeatFluxTemperatureFvPatchScalarField.C.
names() [63/64]
const char * names ()
Definition at line 41 of file temperatureCoupledBase.C.
names() [64/64]
const char * names ()
Definition at line 43 of file turbulentHeatFluxTemperatureFvPatchScalarField.C.
Member Data Documentation
names
const char* names[nEnum] static
The set of names corresponding to the enumeration Enum.
Definition at line 73 of file NamedEnum.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/NamedEnum/NamedEnum.H
src/OpenFOAM/containers/NamedEnum/NamedEnum.C