OpenFOAM: primitiveEntry Class Reference
primitiveEntry Class Reference
A keyword and a list of tokens is a 'primitiveEntry'. An primitiveEntry can be read, written and printed, and the types and values of its tokens analysed.
Public Member Functions
primitiveEntry (const keyType &, Istream &)
Construct from keyword and a Istream.
primitiveEntry (const keyType &, const dictionary &parentDict, Istream &)
Construct from keyword, parent dictionary and Istream.
primitiveEntry (const keyType &, const ITstream &)
Construct from keyword and a ITstream.
primitiveEntry (const keyType &, const token &)
Construct from keyword and a single token.
primitiveEntry (const keyType &, const UList< token > &)
Construct from keyword and a list of tokens.
primitiveEntry (const keyType &, const Xfer< List< token >> &)
Construct from keyword and by transferring a list of tokens.
template<class T >
primitiveEntry (const keyType &, const T &)
Construct from keyword and a T.
autoPtr< entry > clone (const dictionary &) const
Construct on freestore as copy with reference to the.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
bool isStream () const
Return true because this entry is a stream.
ITstream & stream () const
Return token stream if this entry is a primitive entry.
const dictionary & dict () const
This entry is not a dictionary,.
dictionary & dict ()
This entry is not a dictionary,.
virtual bool read (const dictionary &, Istream &)
Read tokens from the given stream.
void write (Ostream &) const
Write.
void write (Ostream &, const bool contentsOnly) const
Write, optionally with contents only (no keyword, etc)
InfoProxy< primitiveEntry > info () const
Return info proxy.
Public Member Functions inherited from entry
entry (const keyType &)
Construct from keyword.
entry (const entry &)
Construct as copy.
virtual autoPtr< entry > clone () const
Construct on freestore as copy.
virtual ~entry ()
Destructor.
const keyType & keyword () const
Return keyword.
keyType & keyword ()
Return non-const access to keyword.
virtual bool isDict () const
Return true if this entry is a dictionary.
void operator= (const entry &)
bool operator== (const entry &) const
bool operator!= (const entry &) const
Public Member Functions inherited from ITstream
ITstream (const string &name, const UList< token > &tokens, streamFormat format=ASCII, versionNumber version=currentVersion)
Construct from components.
ITstream (const string &name, const Xfer< List< token >> &tokens, streamFormat format=ASCII, versionNumber version=currentVersion)
Construct from components, transferring the tokens.
ITstream (const ITstream &its)
Construct as copy.
virtual ~ITstream ()
Destructor.
const fileName & name () const
Return the name of the stream.
fileName & name ()
Return non-const access to the name of the stream.
label tokenIndex () const
Return the current token index.
label & tokenIndex ()
Return non-const access to the current token index.
label nRemainingTokens () const
Return the number of remaining tokens.
ios_base::fmtflags flags () const
Return flags of output stream.
virtual Istream & read (token &)
Return next token from stream.
virtual Istream & read (char &)
Read a character.
virtual Istream & read (word &)
Read a word.
virtual Istream & read (string &)
virtual Istream & read (label &)
Read a label.
virtual Istream & read (floatScalar &)
Read a floatScalar.
virtual Istream & read (doubleScalar &)
Read a doubleScalar.
virtual Istream & read (char *, std::streamsize)
Read binary block.
virtual Istream & rewind ()
Rewind and return the stream so that it may be read again.
ios_base::fmtflags flags (const ios_base::fmtflags)
Set flags of stream.
void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from Istream
Istream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Istream ()
Destructor.
void putBack (const token &)
Put back token.
bool getBack (token &)
Get the put back token if there is one and return true.
bool peekBack (token &)
Peek at the put back token without removing it.
Istream & readBegin (const char *funcName)
Istream & readEnd (const char *funcName)
Istream & readEndBegin (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Return a non-const reference to const Istream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from entry
static bool New (dictionary &parentDict, Istream &)
Construct from Istream and insert into dictionary.
static autoPtr< entry > New (Istream &is)
Construct on freestore from Istream and return.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes inherited from entry
static int disableFunctionEntries
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Attributes inherited from IOstream
label lineNumber_
Detailed Description
A keyword and a list of tokens is a 'primitiveEntry'. An primitiveEntry can be read, written and printed, and the types and values of its tokens analysed.
A primitiveEntry is a high-level building block for data description. It is a front-end for the token parser. A list of entries can be used as a set of keyword syntax elements, for example.
Source files
primitiveEntry.H
primitiveEntry.C
primitiveEntryIO.C
Definition at line 62 of file primitiveEntry.H.
Constructor & Destructor Documentation
primitiveEntry() [1/7]
primitiveEntry (const keyType & key, Istream & is)
Construct from keyword and a Istream.
Definition at line 216 of file primitiveEntryIO.C.
References dictionary::null.
Referenced by primitiveEntry::clone(), primitiveEntry::primitiveEntry(), and primitiveEntry::read().
primitiveEntry() [2/7]
primitiveEntry (const keyType & key, const dictionary & parentDict, Istream & is)
Construct from keyword, parent dictionary and Istream.
Definition at line 197 of file primitiveEntryIO.C.
primitiveEntry() [3/7]
primitiveEntry (const keyType & key, const ITstream & is)
Construct from keyword and a ITstream.
Definition at line 109 of file primitiveEntry.C.
References entry::keyword(), and primitiveEntry::name().
primitiveEntry() [4/7]
primitiveEntry (const keyType & key, const token & t)
Construct from keyword and a single token.
Definition at line 118 of file primitiveEntry.C.
References primitiveEntry::primitiveEntry().
primitiveEntry() [5/7]
primitiveEntry (const keyType & key, const UList< token > & tokens)
Construct from keyword and a list of tokens.
Definition at line 126 of file primitiveEntry.C.
References primitiveEntry::primitiveEntry().
primitiveEntry() [6/7]
primitiveEntry (const keyType & key, const Xfer< List< token >> & tokens)
Construct from keyword and by transferring a list of tokens.
Definition at line 137 of file primitiveEntry.C.
primitiveEntry() [7/7]
primitiveEntry (const keyType & key, const T & t)
Construct from keyword and a T.
Definition at line 32 of file primitiveEntryTemplates.C.
References token::END_STATEMENT, dictionary::null, and OStringStream::str().
Member Function Documentation
clone()
autoPtr<entry> clone (const dictionary & parentDict) const inline virtual
Construct on freestore as copy with reference to the.
dictionary the copy belongs to
Implements entry.
Definition at line 121 of file primitiveEntry.H.
References primitiveEntry::primitiveEntry(), and ITstream::read().
name() [1/2]
const fileName& name () const inline virtual
Return the dictionary name.
Implements entry.
Definition at line 133 of file primitiveEntry.H.
References ITstream::name().
Referenced by primitiveEntry::primitiveEntry().
name() [2/2]
fileName& name () inline virtual
Return the dictionary name.
Implements entry.
Definition at line 139 of file primitiveEntry.H.
References primitiveEntry::endLineNumber(), ITstream::name(), and primitiveEntry::startLineNumber().
startLineNumber()
Foam::label startLineNumber () const virtual
Return line number of first token in dictionary.
Implements entry.
Definition at line 149 of file primitiveEntry.C.
References UList< T >::empty(), and UList< T >::first().
Referenced by primitiveEntry::name().
endLineNumber()
Foam::label endLineNumber () const virtual
Return line number of last token in dictionary.
Implements entry.
Definition at line 164 of file primitiveEntry.C.
References UList< T >::empty(), and UList< T >::last().
Referenced by primitiveEntry::name().
isStream()
bool isStream () const inline virtual
Return true because this entry is a stream.
Reimplemented from entry.
Definition at line 151 of file primitiveEntry.H.
References primitiveEntry::dict(), primitiveEntry::info(), primitiveEntry::read(), primitiveEntry::stream(), and primitiveEntry::write().
stream()
Foam::ITstream & stream () const virtual
Return token stream if this entry is a primitive entry.
Implements entry.
Definition at line 179 of file primitiveEntry.C.
References ITstream::rewind().
Referenced by primitiveEntry::isStream().
dict() [1/2]
const Foam::dictionary & dict () const virtual
This entry is not a dictionary,.
calling this function generates a FatalError
Implements entry.
Definition at line 187 of file primitiveEntry.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, primitiveEntry::info(), and dictionary::null.
Referenced by primitiveEntry::isStream().
dict() [2/2]
Foam::dictionary & dict () virtual
This entry is not a dictionary,.
calling this function generates a FatalError
Implements entry.
Definition at line 198 of file primitiveEntry.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, primitiveEntry::info(), and dictionary::null.
read()
bool read (const dictionary & dict, Istream & is) virtual
Read tokens from the given stream.
Definition at line 95 of file primitiveEntryIO.C.
References IOstream::bad(), token::BEGIN_BLOCK, token::BEGIN_LIST, token::END_BLOCK, token::END_LIST, token::END_STATEMENT, IOstream::fatalCheck(), token::good(), entry::keyword(), IOstream::lineNumber(), primitiveEntry::primitiveEntry(), Istream::read(), SafeFatalIOErrorInFunction, List< T >::setSize(), and ITstream::tokenIndex().
Referenced by includeIfPresentEntry::execute(), calcEntry::execute(), includeEntry::execute(), includeEtcEntry::execute(), codeStream::execute(), and primitiveEntry::isStream().
write() [1/2]
void write (Ostream & os) const virtual
Write.
Implements entry.
Definition at line 267 of file primitiveEntryIO.C.
References Foam::e, Foam::endl(), primitiveEntry::info(), entry::keyword(), Foam::min(), Foam::nl, ITstream::print(), and List< T >::size().
Referenced by primitiveEntry::isStream().
write() [2/2]
void write (Ostream & os, const bool contentsOnly) const
Write, optionally with contents only (no keyword, etc)
Definition at line 233 of file primitiveEntryIO.C.
References token::END_STATEMENT, Foam::endl(), entry::keyword(), UList< T >::operator[](), List< T >::size(), token::SPACE, token::type(), token::VERBATIMSTRING, Ostream::write(), and Ostream::writeKeyword().
info()
InfoProxy<primitiveEntry> info () const inline
Return info proxy.
Used to print token information to a stream
Definition at line 178 of file primitiveEntry.H.
Referenced by primitiveEntry::dict(), primitiveEntry::isStream(), and primitiveEntry::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/primitiveEntry/primitiveEntry.H
src/OpenFOAM/db/dictionary/primitiveEntry/primitiveEntry.C
src/OpenFOAM/db/dictionary/primitiveEntry/primitiveEntryIO.C
src/OpenFOAM/db/dictionary/primitiveEntry/primitiveEntryTemplates.C