OpenFOAM: dynamicCode Class Reference
dynamicCode Class Reference
Tools for handling dynamic code compilation.
Public Types
typedef Tuple2< fileName, string > fileAndContent
Public Member Functions
dynamicCode (const word &codeName, const word &codeDirName="")
Construct for a specified code name and code directory name.
const word & codeName () const
Return the code-name.
const word & codeDirName () const
Return the code-dirname.
const fileName & codeRoot () const
Root for dynamic code compilation.
fileName libSubDir () const
Subdirectory name for loading libraries.
fileName codePath () const
Path for specified code name.
fileName libPath () const
Library path for specified code name.
fileName codeRelPath () const
Path for specified code name relative to $FOAM_CASE.
fileName libRelPath () const
Library path for specified code name relative to $FOAM_CASE.
fileName digestFile () const
Path for SHA1Digest.
void clear ()
Clear files and variables.
void reset (const dynamicCodeContext &)
Clear files and reset variables to specified context.
void addCompileFile (const fileName &name)
Add a file template name, which will be found and filtered.
void addCopyFile (const fileName &name)
Add a file template name, which will be found and filtered.
void addCreateFile (const fileName &name, const string &contents)
Add a file to create with its contents. Will not be filtered.
void setFilterContext (const dynamicCodeContext &)
Define filter variables for code, codeInclude, SHA1sum.
void setFilterVariable (const word &key, const std::string &value)
Define a filter variable.
void setMakeOptions (const std::string &content)
Define contents for Make/options.
bool upToDate (const dynamicCodeContext &context) const
Verify if the copied code is up-to-date, based on Make/SHA1Digest.
bool upToDate (const SHA1Digest &sha1) const
Verify if the copied code is up-to-date, based on Make/SHA1Digest.
bool copyOrCreateFiles (const bool verbose=false) const
Copy/create files prior to compilation.
bool wmakeLibso () const
Compile a libso.
Static Public Member Functions
static void checkSecurity (const char *title, const dictionary &)
Check security for creating dynamic code.
static word libraryBaseName (const fileName &libPath)
Return the library basename without leading 'lib' or trailing '.so'.
Static Public Attributes
static const word codeTemplateEnvName = "FOAM_CODE_TEMPLATES"
Name of the code template environment variable.
static const fileName codeTemplateDirName = "codeTemplates/dynamicCode"
Name of the code template sub-directory.
static int allowSystemOperations
Flag if system operations are allowed.
Protected Member Functions
bool writeCommentSHA1 (Ostream &) const
Write SHA1 value as C-comment.
bool createMakeFiles () const
Copy/create Make/files prior to compilation.
bool createMakeOptions () const
Copy/create Make/options prior to compilation.
bool writeDigest (const SHA1Digest &) const
Write digest to Make/SHA1Digest.
bool writeDigest (const std::string &) const
Write digest to Make/SHA1Digest.
Static Protected Member Functions
static void copyAndFilter (ISstream &, OSstream &, const HashTable< string > &mapping)
Copy lines while expanding variables.
static bool resolveTemplates (const UList< fileName > &templateNames, DynamicList< fileName > &resolvedFiles, DynamicList< fileName > &badFiles)
Resolve code-templates via the codeTemplateEnvName.
Static Protected Attributes
static const char *const libTargetRoot
Root of the LIB target for Make/files.
static const char *const topDirName = "dynamicCode"
Top-level directory name for copy/compiling.
Detailed Description
Tools for handling dynamic code compilation.
Source files
dynamicCode.H
dynamicCode.C
Definition at line 56 of file dynamicCode.H.
Member Typedef Documentation
fileAndContent
typedef Tuple2<fileName, string> fileAndContent
Definition at line 59 of file dynamicCode.H.
Constructor & Destructor Documentation
dynamicCode()
dynamicCode (const word & codeName, const word & codeDirName = "")
Construct for a specified code name and code directory name.
Defaults to using the code name for the code directory name
Definition at line 294 of file dynamicCode.C.
References dynamicCode::clear().
Member Function Documentation
copyAndFilter()
void copyAndFilter (ISstream & is, OSstream & os, const HashTable< string > & mapping) static protected
Copy lines while expanding variables.
Definition at line 105 of file dynamicCode.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, ISstream::getLine(), IOstream::good(), Foam::stringOps::inplaceExpand(), OSstream::name(), ISstream::name(), Foam::nl, dynamicCode::resolveTemplates(), and OSstream::writeQuoted().
Referenced by dynamicCode::copyOrCreateFiles(), and dynamicCode::libraryBaseName().
resolveTemplates()
bool resolveTemplates (const UList< fileName > & templateNames, DynamicList< fileName > & resolvedFiles, DynamicList< fileName > & badFiles) static protected
Resolve code-templates via the codeTemplateEnvName.
alternatively in the codeTemplateDirName via Foam::findEtcFile
Definition at line 142 of file dynamicCode.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), dynamicCode::codeTemplateDirName, dynamicCode::codeTemplateEnvName, Foam::findEtcFile(), forAll, Foam::getEnv(), Foam::isDir(), and Foam::isFile().
Referenced by dynamicCode::copyAndFilter(), and dynamicCode::copyOrCreateFiles().
writeCommentSHA1()
bool writeCommentSHA1 (Ostream & os) const protected
Write SHA1 value as C-comment.
Definition at line 187 of file dynamicCode.C.
References Ostream::writeQuoted().
Referenced by dynamicCode::createMakeFiles(), and dynamicCode::createMakeOptions().
createMakeFiles()
bool createMakeFiles () const protected
Copy/create Make/files prior to compilation.
Definition at line 201 of file dynamicCode.C.
References dynamicCode::codePath(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, dynamicCode::libTargetRoot, Foam::mkDir(), Foam::nl, fileName::path(), and dynamicCode::writeCommentSHA1().
Referenced by dynamicCode::copyOrCreateFiles().
createMakeOptions()
bool createMakeOptions () const protected
Copy/create Make/options prior to compilation.
Definition at line 238 of file dynamicCode.C.
References dynamicCode::codePath(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::mkDir(), Foam::nl, fileName::path(), and dynamicCode::writeCommentSHA1().
Referenced by dynamicCode::copyOrCreateFiles().
writeDigest() [1/2]
bool writeDigest (const SHA1Digest & sha1) const protected
Write digest to Make/SHA1Digest.
Definition at line 267 of file dynamicCode.C.
References dynamicCode::digestFile(), Foam::mkDir(), Foam::nl, fileName::path(), and SHA1Digest::write().
Referenced by dynamicCode::copyOrCreateFiles().
writeDigest() [2/2]
bool writeDigest (const std::string & sha1) const protected
Write digest to Make/SHA1Digest.
Definition at line 279 of file dynamicCode.C.
References dynamicCode::digestFile(), Foam::mkDir(), Foam::nl, and fileName::path().
checkSecurity()
void checkSecurity (const char * title, const dictionary & dict) static
Check security for creating dynamic code.
Definition at line 58 of file dynamicCode.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::isAdministrator(), and Foam::nl.
Referenced by calcEntry::execute(), codeStream::execute(), and codedBase::updateLibrary().
libraryBaseName()
Foam::word libraryBaseName (const fileName & libPath) static
Return the library basename without leading 'lib' or trailing '.so'.
Definition at line 93 of file dynamicCode.C.
References dynamicCode::copyAndFilter(), and fileName::name().
Referenced by codedBase::updateLibrary().
codeName()
const word& codeName () const inline
Return the code-name.
Definition at line 187 of file dynamicCode.H.
codeDirName()
const word& codeDirName () const inline
Return the code-dirname.
Definition at line 193 of file dynamicCode.H.
References dynamicCode::addCompileFile(), dynamicCode::addCopyFile(), dynamicCode::addCreateFile(), dynamicCode::clear(), dynamicCode::codePath(), dynamicCode::codeRelPath(), dynamicCode::codeRoot(), dynamicCode::copyOrCreateFiles(), dynamicCode::digestFile(), dynamicCode::libPath(), dynamicCode::libRelPath(), dynamicCode::libSubDir(), Foam::name(), dynamicCode::reset(), dynamicCode::setFilterContext(), dynamicCode::setFilterVariable(), dynamicCode::setMakeOptions(), dynamicCode::upToDate(), and dynamicCode::wmakeLibso().
codeRoot()
const fileName& codeRoot () const inline
Root for dynamic code compilation.
Expanded from $FOAM_CASE/dynamicCode
Definition at line 200 of file dynamicCode.H.
Referenced by dynamicCode::codeDirName().
libSubDir()
fileName libSubDir () const inline
Subdirectory name for loading libraries.
Expanded from platforms/$WM_OPTIONS/lib
Definition at line 207 of file dynamicCode.H.
Referenced by dynamicCode::codeDirName().
codePath()
fileName codePath () const inline
Path for specified code name.
Corresponds to codeRoot()/codeDirName()
Definition at line 214 of file dynamicCode.H.
Referenced by dynamicCode::codeDirName(), dynamicCode::copyOrCreateFiles(), dynamicCode::createMakeFiles(), dynamicCode::createMakeOptions(), and dynamicCode::wmakeLibso().
libPath()
fileName libPath () const inline
Library path for specified code name.
Corresponds to codeRoot()/libSubDir()/lib<codeName>.so
Definition at line 221 of file dynamicCode.H.
Referenced by dynamicCode::codeDirName().
codeRelPath()
Foam::fileName codeRelPath () const
Path for specified code name relative to $FOAM_CASE.
Corresponds to topDirName/codeDirName()
Definition at line 312 of file dynamicCode.C.
References dynamicCode::topDirName.
Referenced by dynamicCode::codeDirName(), and dynamicCode::libRelPath().
libRelPath()
Foam::fileName libRelPath () const
Library path for specified code name relative to $FOAM_CASE.
Corresponds to dynamicCode/codeDirName()/libSubDir()/lib<codeName>.so
Definition at line 318 of file dynamicCode.C.
References dynamicCode::codeRelPath().
Referenced by dynamicCode::codeDirName(), and dynamicCode::copyOrCreateFiles().
digestFile()
fileName digestFile () const inline
Path for SHA1Digest.
Corresponds to codePath()/Make/SHA1Digest
Definition at line 239 of file dynamicCode.H.
Referenced by dynamicCode::codeDirName(), dynamicCode::upToDate(), and dynamicCode::writeDigest().
clear()
void clear ()
Clear files and variables.
Definition at line 324 of file dynamicCode.C.
References dynamicCode::reset().
Referenced by dynamicCode::codeDirName(), dynamicCode::dynamicCode(), and dynamicCode::reset().
reset()
void reset (const dynamicCodeContext & context)
Clear files and reset variables to specified context.
Definition at line 341 of file dynamicCode.C.
References dynamicCode::clear(), and dynamicCode::setFilterContext().
Referenced by dynamicCode::clear(), and dynamicCode::codeDirName().
addCompileFile()
void addCompileFile (const fileName & name)
Add a file template name, which will be found and filtered.
Definition at line 350 of file dynamicCode.C.
Referenced by dynamicCode::codeDirName(), codedFunctionObject::prepare(), and CodedSource< Type >::prepare().
addCopyFile()
void addCopyFile (const fileName & name)
Add a file template name, which will be found and filtered.
Definition at line 356 of file dynamicCode.C.
References dynamicCode::addCreateFile().
Referenced by dynamicCode::codeDirName(), codedFunctionObject::prepare(), and CodedSource< Type >::prepare().
addCreateFile()
void addCreateFile (const fileName & name, const string & contents)
Add a file to create with its contents. Will not be filtered.
Definition at line 363 of file dynamicCode.C.
References dynamicCode::setFilterContext().
Referenced by dynamicCode::addCopyFile(), and dynamicCode::codeDirName().
setFilterContext()
void setFilterContext (const dynamicCodeContext & context)
Define filter variables for code, codeInclude, SHA1sum.
Definition at line 373 of file dynamicCode.C.
References dynamicCodeContext::code(), dynamicCodeContext::include(), dynamicCodeContext::localCode(), dynamicCode::setFilterVariable(), dynamicCodeContext::sha1(), and SHA1Digest::str().
Referenced by dynamicCode::addCreateFile(), dynamicCode::codeDirName(), and dynamicCode::reset().
setFilterVariable()
void setFilterVariable (const word & key, const std::string & value)
Define a filter variable.
Definition at line 385 of file dynamicCode.C.
Referenced by dynamicCode::codeDirName(), codedFunctionObject::prepare(), CodedSource< Type >::prepare(), and dynamicCode::setFilterContext().
setMakeOptions()
void setMakeOptions (const std::string & content)
Define contents for Make/options.
Definition at line 394 of file dynamicCode.C.
Referenced by dynamicCode::codeDirName(), codedFunctionObject::prepare(), and CodedSource< Type >::prepare().
upToDate() [1/2]
bool upToDate (const dynamicCodeContext & context) const
Verify if the copied code is up-to-date, based on Make/SHA1Digest.
Definition at line 524 of file dynamicCode.C.
References dynamicCodeContext::sha1().
Referenced by dynamicCode::codeDirName().
upToDate() [2/2]
bool upToDate (const SHA1Digest & sha1) const
Verify if the copied code is up-to-date, based on Make/SHA1Digest.
Definition at line 511 of file dynamicCode.C.
References dynamicCode::digestFile(), and Foam::exists().
copyOrCreateFiles()
bool copyOrCreateFiles (const bool verbose = false) const
Copy/create files prior to compilation.
Definition at line 400 of file dynamicCode.C.
References dynamicCode::codePath(), dynamicCode::codeTemplateDirName, dynamicCode::codeTemplateEnvName, dynamicCode::copyAndFilter(), dynamicCode::createMakeFiles(), dynamicCode::createMakeOptions(), UList< T >::empty(), Foam::endl(), Foam::exit(), Foam::stringOps::expand(), Foam::FatalError, FatalErrorInFunction, forAll, IOstream::good(), Foam::Info, dynamicCode::libRelPath(), Foam::mkDir(), fileName::name(), Foam::nl, fileName::path(), dynamicCode::resolveTemplates(), and dynamicCode::writeDigest().
Referenced by dynamicCode::codeDirName().
wmakeLibso()
bool wmakeLibso () const
Compile a libso.
Definition at line 495 of file dynamicCode.C.
References dynamicCode::codePath(), Foam::endl(), Foam::Info, and Foam::system().
Referenced by dynamicCode::codeDirName().
Member Data Documentation
libTargetRoot
const char *const libTargetRoot static protected
Initial value:
=
    "LIB = $(PWD)/../platforms/$(WM_OPTIONS)/lib/lib"
Root of the LIB target for Make/files.
Definition at line 106 of file dynamicCode.H.
Referenced by dynamicCode::createMakeFiles().
topDirName
const char *const topDirName = "dynamicCode" static protected
Top-level directory name for copy/compiling.
Definition at line 109 of file dynamicCode.H.
Referenced by dynamicCode::codeRelPath().
codeTemplateEnvName
const Foam::word codeTemplateEnvName = "FOAM_CODE_TEMPLATES" static
Name of the code template environment variable.
Used to located the codeTemplateName
Definition at line 154 of file dynamicCode.H.
Referenced by dynamicCode::copyOrCreateFiles(), and dynamicCode::resolveTemplates().
codeTemplateDirName
const Foam::fileName codeTemplateDirName = "codeTemplates/dynamicCode" static
Name of the code template sub-directory.
Used when locating the codeTemplateName via Foam::findEtcFile
Definition at line 158 of file dynamicCode.H.
Referenced by dynamicCode::copyOrCreateFiles(), and dynamicCode::resolveTemplates().
allowSystemOperations
int allowSystemOperations static
Flag if system operations are allowed.
Definition at line 161 of file dynamicCode.H.
Referenced by argList::parse(), and systemCall::read().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCode.H
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCode.C