OpenFOAM: dictionaryEntry Class Reference
dictionaryEntry Class Reference
A keyword and a list of tokens is a 'dictionaryEntry'.
Public Member Functions
dictionaryEntry (const dictionary &parentDict, Istream &)
Construct from the parent dictionary and Istream.
dictionaryEntry (const keyType &, const dictionary &parentDict, Istream &)
Construct from the keyword, parent dictionary and a Istream.
dictionaryEntry (const keyType &, const dictionary &parentDict, const dictionary &dict)
Construct from the keyword, parent dictionary and a dictionary.
dictionaryEntry (const dictionary &parentDict, const dictionaryEntry &)
Construct as copy for the given parent dictionary.
autoPtr< entry > clone (const dictionary &parentDict) const
Construct on freestore as copy with reference to the.
const word dictName () const
Return the local dictionary name (final part of scoped name)
const fileName & name () const
Return the dictionary name (scoped, e.g. dictA::dictB::dictC)
fileName & name ()
Return the dictionary name (scoped, e.g. dictA::dictB::dictC)
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
ITstream & stream () const
This entry is not a primitive,.
bool isDict () const
Return true because this entry is a dictionary.
const dictionary & dict () const
Return dictionary.
dictionary & dict ()
Return non-const access to dictionary.
void write (Ostream &) const
Write.
InfoProxy< dictionaryEntry > info () const
Return info proxy.
Public Member Functions inherited from entry
entry (const keyType &)
Construct from keyword.
entry (const entry &)
Construct as copy.
virtual autoPtr< entry > clone () const
Construct on freestore as copy.
virtual ~entry ()
Destructor.
const keyType & keyword () const
Return keyword.
keyType & keyword ()
Return non-const access to keyword.
virtual bool isStream () const
Return true if this entry is a stream.
void operator= (const entry &)
bool operator== (const entry &) const
bool operator!= (const entry &) const
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()
Null construct.
ILList (T *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< LListBase, T > &)
Construct as copy.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
template<class INew >
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< LListBase, T > &)
Assignment operator.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()
Null construct.
UILList (T *a)
Construct given initial T.
UILList (const UILList< LListBase, T > &)
Construct as copy.
T * first ()
Return the first entry.
const T * first () const
Return the first entry.
T * last ()
Return the last entry.
const T * last () const
Return the last entry.
T * removeHead ()
Remove and return head.
T * remove (T *p)
Remove and return element.
T * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< LListBase, T > &)
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< LListBase, T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< LListBase, T > &) const
The opposite of the equality operation. Takes linear time.
Friends
Ostream & operator<< (Ostream &, const dictionaryEntry &)
Additional Inherited Members
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values the DLList contains.
typedef T & reference
Type that can be used for storing into DLList::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Static Public Member Functions inherited from entry
static bool New (dictionary &parentDict, Istream &)
Construct from Istream and insert into dictionary.
static autoPtr< entry > New (Istream &is)
Construct on freestore from Istream and return.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Static Public Attributes inherited from entry
static int disableFunctionEntries
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Detailed Description
A keyword and a list of tokens is a 'dictionaryEntry'.
An dictionaryEntry can be read, written and printed, and the types and values of its tokens analysed. A dictionaryEntry is a high-level building block for data description. It is a front-end for the token parser. A list of entries can be used as a set of keyword syntax elements, for example.
Source files
dictionaryEntry.H
dictionaryEntry.C
dictionaryEntryIO.C
Definition at line 64 of file dictionaryEntry.H.
Constructor & Destructor Documentation
dictionaryEntry() [1/4]
dictionaryEntry (const dictionary & parentDict, Istream & is)
Construct from the parent dictionary and Istream.
Definition at line 33 of file dictionaryEntryIO.C.
References IOstream::fatalCheck().
dictionaryEntry() [2/4]
dictionaryEntry (const keyType & key, const dictionary & parentDict, Istream & is)
Construct from the keyword, parent dictionary and a Istream.
Definition at line 50 of file dictionaryEntryIO.C.
References IOstream::fatalCheck().
dictionaryEntry() [3/4]
dictionaryEntry (const keyType & key, const dictionary & parentDict, const dictionary & dict)
Construct from the keyword, parent dictionary and a dictionary.
Definition at line 31 of file dictionaryEntry.C.
dictionaryEntry() [4/4]
dictionaryEntry (const dictionary & parentDict, const dictionaryEntry & dictEnt)
Construct as copy for the given parent dictionary.
Definition at line 43 of file dictionaryEntry.C.
Member Function Documentation
clone()
autoPtr<entry> clone (const dictionary & parentDict) const inline virtual
Construct on freestore as copy with reference to the.
dictionary the copy belongs to
Implements entry.
Definition at line 107 of file dictionaryEntry.H.
dictName()
const word dictName () const inline
Return the local dictionary name (final part of scoped name)
Definition at line 116 of file dictionaryEntry.H.
References dictionaryName::dictName().
name() [1/2]
const fileName& name () const inline virtual
Return the dictionary name (scoped, e.g. dictA::dictB::dictC)
Implements entry.
Definition at line 122 of file dictionaryEntry.H.
References dictionaryName::name().
name() [2/2]
fileName& name () inline virtual
Return the dictionary name (scoped, e.g. dictA::dictB::dictC)
Implements entry.
Definition at line 128 of file dictionaryEntry.H.
References dictionaryEntry::endLineNumber(), dictionaryName::name(), dictionaryEntry::startLineNumber(), and dictionaryEntry::stream().
startLineNumber()
Foam::label startLineNumber () const virtual
Return line number of first token in dictionary.
Implements entry.
Definition at line 55 of file dictionaryEntry.C.
References UILList< LListBase, T >::first().
Referenced by dictionaryEntry::name().
endLineNumber()
Foam::label endLineNumber () const virtual
Return line number of last token in dictionary.
Implements entry.
Definition at line 68 of file dictionaryEntry.C.
References UILList< LListBase, T >::last().
Referenced by dictionaryEntry::name().
stream()
Foam::ITstream & stream () const virtual
This entry is not a primitive,.
calling this function generates a FatalError
Implements entry.
Definition at line 81 of file dictionaryEntry.C.
References Foam::abort(), Foam::FatalIOError, FatalIOErrorInFunction, and dictionary::lookup().
Referenced by dictionaryEntry::name().
isDict()
bool isDict () const inline virtual
Return true because this entry is a dictionary.
Reimplemented from entry.
Definition at line 144 of file dictionaryEntry.H.
References dictionaryEntry::dict(), dictionaryEntry::info(), dictionaryEntry::operator<<, and dictionaryEntry::write().
dict() [1/2]
const Foam::dictionary & dict () const virtual
Return dictionary.
Implements entry.
Definition at line 91 of file dictionaryEntry.C.
Referenced by dictionaryEntry::isDict().
dict() [2/2]
Foam::dictionary & dict () virtual
Return non-const access to dictionary.
Implements entry.
Definition at line 97 of file dictionaryEntry.C.
write()
void write (Ostream & os) const virtual
Write.
Implements entry.
Definition at line 69 of file dictionaryEntryIO.C.
References Ostream::indent(), entry::keyword(), Ostream::write(), and dictionary::write().
Referenced by dictionaryEntry::isDict(), and Foam::operator<<().
info()
InfoProxy<dictionaryEntry> info () const inline
Return info proxy.
Used to print token information to a stream
Definition at line 160 of file dictionaryEntry.H.
Referenced by dictionaryEntry::isDict().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const dictionaryEntry &) friend
Referenced by dictionaryEntry::isDict().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/dictionaryEntry/dictionaryEntry.H
src/OpenFOAM/db/dictionary/dictionaryEntry/dictionaryEntry.C
src/OpenFOAM/db/dictionary/dictionaryEntry/dictionaryEntryIO.C