OpenFOAM: IOobject Class Reference
IOobject Class Reference
IOobject defines the attributes of an object for which implicit objectRegistry management is supported, and provides the infrastructure for performing stream I/O.
Public Types
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Member Functions
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
virtual void rename (const word &newName)
Rename.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Protected Member Functions
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Detailed Description
IOobject defines the attributes of an object for which implicit objectRegistry management is supported, and provides the infrastructure for performing stream I/O.
An IOobject is constructed with an object name, a class name, an instance path, a reference to a objectRegistry, and parameters determining its storage status.
Read options
Define what is done on object construction and explicit reads:
MUST_READ
Object must be read from Istream on construction.
Error if Istream does not exist or can't be read. Does not check timestamp or re-read.
MUST_READ_IF_MODIFIED
Object must be read from Istream on construction.
Error if Istream does not exist or can't be read. If object is registered its timestamp will be checked every timestep and possibly re-read.
READ_IF_PRESENT
Read object from Istream if Istream exists, otherwise don't.
Error only if Istream exists but can't be read. Does not check timestamp or re-read.
NO_READ
Don't read
Write options
Define what is done on object destruction and explicit writes:
AUTO_WRITE
Object is written automatically when requested to by the objectRegistry.
NO_WRITE
No automatic write on destruction but can be written explicitly
Source files
IOobject.H
IOobject.C
IOobjectReadHeader.C
IOobjectWriteHeader.C
IOobjectPrint.C
Definition at line 91 of file IOobject.H.
Member Enumeration Documentation
objectState
enum objectState
Enumeration defining the valid states of an IOobject.
Enumerator
GOOD
BAD
Definition at line 99 of file IOobject.H.
readOption
enum readOption
Enumeration defining the read options.
Enumerator
MUST_READ
MUST_READ_IF_MODIFIED
READ_IF_PRESENT
NO_READ
Definition at line 106 of file IOobject.H.
writeOption
enum writeOption
Enumeration defining the write options.
Enumerator
AUTO_WRITE
NO_WRITE
Definition at line 115 of file IOobject.H.
Constructor & Destructor Documentation
IOobject() [1/3]
IOobject (const word & name, const fileName & instance, const objectRegistry & registry, readOption r = NO_READ, writeOption w = NO_WRITE, bool registerObject = true)
Construct from name, instance, registry, io options.
Definition at line 114 of file IOobject.C.
References Foam::endl(), and InfoInFunction.
Referenced by IOobject::clone(), IOobject::fileNameComponents(), fvMesh::fvMesh(), IOobject::IOobject(), and fvMesh::V00().
IOobject() [2/3]
IOobject (const word & name, const fileName & instance, const fileName & local, const objectRegistry & registry, readOption r = NO_READ, writeOption w = NO_WRITE, bool registerObject = true)
Construct from name, instance, local, registry, io options.
Definition at line 145 of file IOobject.C.
References Foam::endl(), InfoInFunction, and IOobject::IOobject().
IOobject() [3/3]
IOobject (const fileName & path, const objectRegistry & registry, readOption r = NO_READ, writeOption w = NO_WRITE, bool registerObject = true)
Construct from path, registry, io options.
Uses fileNameComponents() to split path into components.
Definition at line 177 of file IOobject.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and InfoInFunction.
~IOobject()
~IOobject () virtual
Destructor.
Definition at line 215 of file IOobject.C.
Referenced by IOobject::clone().
Member Function Documentation
objectStream() [1/2]
Foam::Istream * objectStream () protected
Construct and return an IFstream for the object.
The results is nullptr if the stream construction failed
Definition at line 371 of file IOobject.C.
objectStream() [2/2]
Foam::Istream * objectStream (const fileName & fName) protected
Construct and return an IFstream for the object given the.
exact file. The results is nullptr if the stream construction failed
Definition at line 377 of file IOobject.C.
References IOstream::good().
setBad()
void setBad (const string & s) protected
Set the object state to bad.
Definition at line 440 of file IOobject.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, and messageStream::level.
Referenced by IFstream::IFstream().
TypeName()
TypeName ("IOobject")
Runtime type information.
fileNameComponents()
bool fileNameComponents (const fileName & path, fileName & instance, fileName & local, word & name) static
Split path into instance, local, name components.
input IOobject(instance, local, name) ----- ------ "foo" ("", "", "foo") "foo/bar" ("foo", "", "bar") "/XXX/bar" ("/XXX", "", "bar") "foo/bar/" ERROR - no name "foo/xxx/bar" ("foo", "xxx", "bar") "foo/xxx/yyy/bar" ("foo", "xxx/yyy", "bar")
Definition at line 41 of file IOobject.C.
References Foam::endl(), IOobject::IOobject(), fileName::isAbsolute(), Foam::isDir(), Foam::name(), path(), and WarningInFunction.
groupName() [1/2]
static word groupName (Name name, const word & group) inline static
Referenced by basicMultiComponentMixture::basicMultiComponentMixture(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), DarcyForchheimer::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), Maxwell< BasicTurbulenceModel >::devRhoReff(), singleStepCombustion< CombThermoType, ThermoType >::dQ(), LESeddyViscosity< BasicTurbulenceModel >::epsilon(), Stokes< BasicTurbulenceModel >::epsilon(), DeardorffDiffStress< BasicTurbulenceModel >::epsilon(), kEqn< BasicTurbulenceModel >::epsilon(), WALE< BasicTurbulenceModel >::epsilon(), Smagorinsky< BasicTurbulenceModel >::epsilon(), dynamicKEqn< BasicTurbulenceModel >::epsilon(), kOmegaSSTLM< BasicTurbulenceModel >::Flength(), kOmegaSSTLM< BasicTurbulenceModel >::Fonset(), kOmegaSSTLM< BasicTurbulenceModel >::Fthetat(), WALE< BasicTurbulenceModel >::k(), Smagorinsky< BasicTurbulenceModel >::k(), Stokes< BasicTurbulenceModel >::k(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), polyBoundaryMesh::mesh(), Stokes< BasicTurbulenceModel >::nuEff(), continuousGasKEpsilon< BasicTurbulenceModel >::nuEff(), LESModel< BasicTurbulenceModel >::nuEff(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::nuEff(), Stokes< BasicTurbulenceModel >::nut(), basicThermo::phasePropertyName(), Stokes< BasicTurbulenceModel >::R(), continuousGasKEpsilon< BasicTurbulenceModel >::R(), SmagorinskyZhang< BasicTurbulenceModel >::read(), NicenoKEqn< BasicTurbulenceModel >::read(), LaheyKEpsilon< BasicTurbulenceModel >::read(), kOmegaSSTSato< BasicTurbulenceModel >::read(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetac(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0(), continuousGasKEpsilon< BasicTurbulenceModel >::rhoEff(), combustionModel::Sh(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), fixedShearStressFvPatchVectorField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), alphatWallFunctionFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), wallHeatTransferFvPatchScalarField::updateCoeffs(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs(), basicSpecieMixture::W(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), nutkFilmWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), and FSD< CombThermoType, ThermoType >::~FSD().
clone()
Foam::autoPtr<IOobject> clone () const inline
Clone.
Definition at line 239 of file IOobject.H.
References IOobject::db(), IOobject::IOobject(), IOobject::time(), and IOobject::~IOobject().
Referenced by attachPolyTopoChanger::attach(), refinementHistory::clone(), polyTopoChange::makeMesh(), searchableSurface::iNew::operator()(), refinementHistory::parentIndex(), polyMesh::readUpdate(), refinementHistory::refinementHistory(), searchableSurfaces::searchableSurfaces(), fvMeshSubset::setCellSubset(), and fvMeshSubset::setLargeCellSubset().
time()
const Foam::Time & time () const
Return time.
Definition at line 227 of file IOobject.C.
References objectRegistry::time().
Referenced by motionSmootherAlgo::avg(), regIOobject::checkIn(), regIOobject::checkOut(), IOobject::clone(), fixedTemperatureConstraint::constrain(), fvMeshSubset::interpolate(), Foam::fvm::laplacian(), simpleControl::loop(), Foam::MapGeometricFields(), regIOobject::modified(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), NamedEnum< directionType, 3 >::names(), engineMesh::New(), dynamicFvMesh::New(), laminarFlameSpeed::New(), SRFModel::New(), laminarModel< BasicTurbulenceModel >::New(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::New(), LESModel< BasicTurbulenceModel >::New(), radiationModel::New(), consumptionSpeed::omega0Sigma(), isNotEqOp< T >::operator()(), RaviPetersen::operator()(), continuousGasKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), continuousGasKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), NicenoKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), LaheyKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), regIOobject::readIfModified(), pointFieldReconstructor::reconstructField(), rigidBodyMeshMotionSolver::solve(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), plenumPressureFvPatchScalarField::updateCoeffs(), regIOobject::write(), meshRefinement::write(), Foam::writeCellGraph(), rigidBodyMeshMotionSolver::writeObject(), Foam::writePatchGraph(), FSD< CombThermoType, ThermoType >::~FSD(), Gulders::~Gulders(), GuldersEGR::~GuldersEGR(), and subCycleField< GeometricField >::~subCycleField().
db()
const Foam::objectRegistry & db () const
Return the local objectRegistry.
Definition at line 221 of file IOobject.C.
Referenced by isoSurface::adaptPatchFields(), refinementHistory::add(), refinementHistory::apply(), Foam::atan2(), motionSmootherAlgo::avg(), regIOobject::checkIn(), regIOobject::checkOut(), IOobject::clone(), Foam::cmptAv(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), refinementHistory::distribute(), hexRef8Data::hexRef8Data(), InjectionModel< CloudType >::inject(), surfaceInterpolationScheme< GType >::interpolate(), volPointInterpolation::interpolate(), PhiScheme< Type, PhiLimiter >::limiter(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), Foam::mag(), Foam::magSqr(), Foam::New(), reuseTmpDimensionedField< TypeR, Type1, GeoMesh >::New(), engineMesh::New(), chemistryTabulationMethod< CompType, ThermoType >::New(), reuseTmpDimensionedField< TypeR, TypeR, GeoMesh >::New(), dynamicFvMesh::New(), laminarFlameSpeed::New(), chemistryReductionMethod< CompType, ThermoType >::New(), reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh >::New(), SRFModel::New(), laminarModel< BasicTurbulenceModel >::New(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, Type2, GeoMesh >::New(), LESModel< BasicTurbulenceModel >::New(), reuseTmpGeometricField< TypeR, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, Type2, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh >::New(), consumptionSpeed::omega0Sigma(), RaviPetersen::operator()(), sampledSurface::pointAverage(), Foam::pow(), SmagorinskyZhang< BasicTurbulenceModel >::read(), NicenoKEqn< BasicTurbulenceModel >::read(), LaheyKEpsilon< BasicTurbulenceModel >::read(), kOmegaSSTSato< BasicTurbulenceModel >::read(), Foam::readFields(), Foam::readUniformFields(), refinementHistory::refinementHistory(), surfMesh::removeFiles(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), decompositionModel::selectIO(), motionSmootherAlgo::setDisplacementPatchFields(), regIOobject::setUpToDate(), rigidBodyMeshMotionSolver::solve(), Foam::sqr(), Foam::stabilise(), surfMesh::surfMesh(), hexRef8Data::sync(), Foam::transform(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), IOobject::writeHeader(), FSD< CombThermoType, ThermoType >::~FSD(), Gulders::~Gulders(), and GuldersEGR::~GuldersEGR().
name()
const word& name () const inline
Return name.
Definition at line 260 of file IOobject.H.
Referenced by isoSurface::adaptPatchFields(), multivariateSurfaceInterpolationScheme< Type >::fieldTable::add(), IOobjectList::add(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), faceZoneSet::addSet(), solidificationMeltingSource::addSup(), setsToFaceZone::applyToSet(), Foam::atan2(), attachPolyTopoChanger::attach(), Foam::fvc::average(), motionSmootherAlgo::avg(), writeFile::baseFileDir(), blended< Type >::blendingFactor(), localBlended< Type >::blendingFactor(), CoBlended< Type >::blendingFactor(), cellCoBlended< Type >::blendingFactor(), Foam::bound(), faceLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkDefinition(), Cloud< streamLineParticle >::checkFieldFieldIOobject(), Cloud< streamLineParticle >::checkFieldIOobject(), regIOobject::checkIn(), objectRegistry::checkIn(), Foam::checkMethod(), objectRegistry::checkOut(), polyBoundaryMesh::checkParallelSync(), faceZone::checkParallelSync(), meshRefinement::checkZoneFaces(), meshObject::clear(), meshObject::clearUpto(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), Foam::cmptAv(), Foam::MULES::correct(), optionList::correct(), cubic< Type >::correction(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), linearUpwind< Type >::correction(), linearUpwindV< Type >::correction(), localBlended< Type >::correction(), Foam::fvc::curl(), Foam::fvc::d2dt2(), Foam::fvm::d2dt2(), objectRegistry::dbDir(), Foam::fvm::ddt(), Foam::fvc::ddt(), Foam::fvc::ddtCorr(), fvFieldDecomposer::decomposeField(), faceZoneSet::deleteSet(), Foam::fvc::div(), Foam::fvm::div(), Foam::fvc::domainIntegrate(), dynamicRefineFvMesh::dynamicRefineFvMesh(), effectivenessHeatExchangerSource::effectivenessHeatExchangerSource(), removeRegisteredObject::execute(), Foam::MULES::explicitSolve(), surfaceFieldValue::filterField(), localPointRegion::findDuplicateFacePairs(), coordinateSystems::findIndex(), coordinateSystems::findIndices(), refinementSurfaces::findInside(), polyTopoChanger::findModifierID(), coupleGroupIdentifier::findOtherPatchID(), fixedTemperatureConstraint::fixedTemperatureConstraint(), Foam::fvc::flux(), objectRegistry::foundObject(), correctedSnGrad< Type >::fullGradCorrection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), steadyStateD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), CoEulerDdtScheme< Type >::fvcDdt(), SLTSDdtScheme< Type >::fvcDdt(), localEulerDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), steadyStateDdtScheme< Type >::fvcDdtPhiCorr(), EulerDdtScheme< Type >::fvcDdtPhiCorr(), backwardDdtScheme< Type >::fvcDdtPhiCorr(), CoEulerDdtScheme< Type >::fvcDdtPhiCorr(), SLTSDdtScheme< Type >::fvcDdtPhiCorr(), localEulerDdtScheme< Type >::fvcDdtPhiCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtPhiCorr(), steadyStateDdtScheme< Type >::fvcDdtUfCorr(), EulerDdtScheme< Type >::fvcDdtUfCorr(), backwardDdtScheme< Type >::fvcDdtUfCorr(), CoEulerDdtScheme< Type >::fvcDdtUfCorr(), SLTSDdtScheme< Type >::fvcDdtUfCorr(), localEulerDdtScheme< Type >::fvcDdtUfCorr(), CrankNicolsonDdtScheme< Type >::fvcDdtUfCorr(), gaussConvectionScheme< Type >::fvcDiv(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), CrankNicolsonDdtScheme< Type >::fvmDdt(), gaussLaplacianScheme< Type, GType >::fvmLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), GeometricField< vector, pointPatchField, pointMesh >::GeometricField(), globalIndexAndTransform::globalIndexAndTransform(), Foam::fvc::grad(), IOobject::groupName(), polyBoundaryMesh::groupPatchIDs(), hexRef8Data::hexRef8Data(), thermoSingleLayer::hs(), Foam::MULES::implicitSolve(), injectionModelList::info(), Foam::interpolate(), localMax< Type >::interpolate(), localMin< Type >::interpolate(), surfaceInterpolationScheme< GType >::interpolate(), localBlended< Type >::interpolate(), singleCellFvMesh::interpolate(), fvMeshSubset::interpolate(), volPointInterpolation::interpolate(), meshToMesh0::interpolate(), IOmapDistribute::IOmapDistribute(), isoSurface::isoSurface(), Foam::fvm::laplacian(), Foam::fvc::laplacian(), Foam::MULES::limiter(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), Foam::MULES::limiterCorr(), limitTemperature::limitTemperature(), objectRegistry::lookupClass(), objectRegistry::lookupObject(), Foam::mag(), Foam::magSqr(), Foam::makeGraph(), Foam::MapConsistentSubMesh(), Foam::MapGeometricFields(), mappedFixedValueFvPatchField< Type >::mapper(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), fvMeshAdder::MapVolFields(), Foam::fvc::meshPhi(), meshObject::movePoints(), IOdictionary::name(), NamedEnum< directionType, 3 >::names(), cyclicAMIPolyPatch::neighbPatchName(), interpolation< Foam::Vector >::New(), dynamicFvMesh::New(), IOobject::objectPath(), isNotEqOp< T >::operator()(), optionList::operator()(), patchInjection::patchInjection(), pointConstraints::pointConstraints(), pointMesh::pointMesh(), polyMesh::polyMesh(), Foam::pow(), fvMeshDistribute::printCoupleInfo(), interfaceProperties::read(), wallHeatFlux::read(), wallShearStress::read(), regIOobject::read(), Foam::readFields(), IOobject::readHeader(), regIOobject::readIfModified(), regIOobject::readStream(), Foam::readUniformFields(), surfMesh::readUpdate(), polyMesh::readUpdate(), Foam::fvc::reconstruct(), pointFieldReconstructor::reconstructField(), fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvVolumeField(), fvFieldReconstructor::reconstructFvVolumeInternalField(), Foam::fvc::reconstructMag(), IOobjectList::remove(), sampledPatchInternalField::sampledPatchInternalField(), mappedPatchBase::samplePatch(), mappedPatchBase::sampleRegion(), searchableSurfaces::searchableSurfaces(), Foam::setRefCell(), removeCells::setRefinement(), removeFaces::setRefinement(), skewCorrected< Type >::skewCorrection(), Foam::fvc::snGrad(), snGradScheme< Type >::snGrad(), solidificationMeltingSource::solidificationMeltingSource(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solveSegregated(), kinematicSingleLayer::solveThickness(), Foam::sqr(), Foam::stabilise(), faceZoneSet::subset(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), surfMesh::surfMesh(), thermoSingleLayer::T(), fvMesh::thisDb(), Foam::transform(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), triSurfaceMesh::triSurfaceMesh(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), waveSurfacePressureFvPatchScalarField::updateCoeffs(), meshObject::updateMesh(), motionSmootherAlgo::updateMesh(), basicThermo::validate(), meshReader::warnDuplicates(), extendedUpwindCellToFaceStencil::weightedSum(), extendedFaceToCellStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), localBlended< Type >::weights(), PatchPostProcessing< CloudType >::write(), FacePostProcessing< CloudType >::write(), yPlus::write(), writeCellVolumes::write(), XiReactionRate::write(), wallHeatFlux::write(), MeshedSurfaceProxy< Face >::write(), wallShearStress::write(), histogram::write(), writeObjects::write(), regionSizeDistribution::write(), Foam::writeCellGraph(), meshToMeshMethod::writeConnectivity(), boundaryRegion::writeDict(), cellTable::writeDict(), molecule::writeFields(), IOobject::writeHeader(), regionFunctionObject::writeObject(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), Foam::writePatchGraph(), gradScheme< Type >::~gradScheme(), and regIOobject::~regIOobject().
headerClassName()
const word& headerClassName () const inline
Return name of the class name read from header.
Definition at line 266 of file IOobject.H.
Referenced by fieldToCell::applyToSet(), regIOobject::read(), and regIOobject::readStream().
note() [1/2]
string& note () inline
Return non-constant access to the optional note.
Definition at line 272 of file IOobject.H.
Referenced by regIOobject::read(), meshReader::warnDuplicates(), edgeMeshFormat::write(), boundaryRegion::writeDict(), cellTable::writeDict(), and IOobject::writeHeader().
note() [2/2]
const string& note () const inline
Return the optional note.
Definition at line 278 of file IOobject.H.
rename()
virtual void rename (const word & newName) inline virtual
Rename.
Reimplemented in regIOobject, and objectRegistry.
Definition at line 284 of file IOobject.H.
Referenced by nearWallFields::createFields(), hexRef8Data::hexRef8Data(), regIOobject::rename(), and hexRef8Data::sync().
registerObject() [1/2]
bool& registerObject () inline
Register object created from this IOobject with registry if true.
Definition at line 290 of file IOobject.H.
Referenced by regIOobject::operator=(), regIOobject::regIOobject(), regIOobject::rename(), and decompositionModel::selectIO().
registerObject() [2/2]
bool registerObject () const inline
Register object created from this IOobject with registry if true.
Definition at line 296 of file IOobject.H.
readOpt() [1/2]
readOption readOpt () const inline
Definition at line 304 of file IOobject.H.
Referenced by regIOobject::checkIn(), CompactIOField< T, BaseType >::CompactIOField(), CompactIOList< face, label >::CompactIOList(), nearWallFields::createFields(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), fvSchemes::fvSchemes(), hexRef8::hexRef8(), IOdictionary::IOdictionary(), IOField< vector >::IOField(), IOList< labelList >::IOList(), IOMap< T >::IOMap(), IOmapDistribute::IOmapDistribute(), IOPtrList< coordinateSystem >::IOPtrList(), polyTopoChange::makeMesh(), radiationModel::radiationModel(), radiativeIntensityRay::radiativeIntensityRay(), refinementHistory::refinementHistory(), decompositionModel::selectIO(), hexRef8Data::sync(), topoSet::topoSet(), and UniformDimensionedField< vector >::UniformDimensionedField().
readOpt() [2/2]
readOption& readOpt () inline
Definition at line 309 of file IOobject.H.
writeOpt() [1/2]
writeOption writeOpt () const inline
Definition at line 314 of file IOobject.H.
Referenced by cellTable::addCellZones(), polyTopoChanger::addTopologyModifiers(), polyMesh::addZones(), nearWallFields::createFields(), polyMesh::movePoints(), decompositionModel::selectIO(), surfMesh::setInstance(), polyMesh::setInstance(), polyTopoChanger::update(), and writeObjects::write().
writeOpt() [2/2]
writeOption& writeOpt () inline
Definition at line 319 of file IOobject.H.
References IOobject::caseName(), IOobject::group(), IOobject::member(), and IOobject::rootPath().
group()
Foam::word group () const
Return group (extension part of name)
Definition at line 239 of file IOobject.C.
References word::null.
Referenced by DarcyForchheimer::correct(), IOobject::groupName(), laminarModel< BasicTurbulenceModel >::New(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::New(), LESModel< BasicTurbulenceModel >::New(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), and IOobject::writeOpt().
member()
Foam::word member () const
Return member (name without the extension)
Definition at line 254 of file IOobject.C.
Referenced by singleStepCombustion< CombThermoType, ThermoType >::R(), laminar< Type >::R(), and IOobject::writeOpt().
rootPath()
const Foam::fileName & rootPath () const
Definition at line 269 of file IOobject.C.
Referenced by Foam::makeGraph(), and IOobject::writeOpt().
caseName()
const Foam::fileName & caseName () const
Definition at line 233 of file IOobject.C.
References fileName::caseName().
Referenced by Foam::makeGraph(), and IOobject::writeOpt().
instance() [1/2]
const fileName& instance () const inline
Definition at line 337 of file IOobject.H.
Referenced by isoSurface::adaptPatchFields(), snappyLayerDriver::addLayers(), Foam::atan2(), Foam::fvc::average(), Foam::checkMethod(), Foam::cmptAv(), correctedSnGrad< Type >::correction(), faceCorrectedSnGrad< Type >::correction(), directions::directions(), surfMesh::facesInstance(), polyMesh::facesInstance(), faceCorrectedSnGrad< Type >::fullGradCorrection(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), surfaceInterpolationScheme< GType >::interpolate(), volPointInterpolation::interpolate(), Foam::fvc::laplacian(), Foam::fvm::laplacian(), IOobject::local(), Foam::mag(), Foam::magSqr(), Foam::makeGraph(), Foam::MapGeometricFields(), meshRefinement::mergePatchFacesUndo(), polyMesh::movePoints(), Foam::New(), reuseTmpDimensionedField< TypeR, Type1, GeoMesh >::New(), reuseTmpDimensionedField< TypeR, TypeR, GeoMesh >::New(), reuseTmpGeometricField< TypeR, Type1, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, Type2, GeoMesh >::New(), reuseTmpGeometricField< TypeR, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, Type2, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh >::New(), surfMesh::pointsInstance(), polyMesh::pointsInstance(), polyMesh::polyMesh(), Foam::pow(), Foam::readFields(), Foam::readUniformFields(), surfMesh::readUpdate(), polyMesh::readUpdate(), Foam::fvc::reconstruct(), Foam::fvc::reconstructMag(), surfMesh::removeFiles(), polyMesh::removeFiles(), surfMesh::setInstance(), polyMesh::setInstance(), snappyRefineDriver::snappyRefineDriver(), snGradScheme< Type >::snGrad(), Foam::sqr(), Foam::stabilise(), Foam::fvc::surfaceIntegrate(), Foam::fvc::surfaceSum(), surfMesh::surfMesh(), Foam::transform(), polyTopoChanger::update(), meshRefinement::write(), IOobject::writeHeader(), regIOobject::writeObject(), and distributedTriSurfaceMesh::writeObject().
instance() [2/2]
fileName& instance () inline
Definition at line 342 of file IOobject.H.
local()
const fileName& local () const inline
Definition at line 347 of file IOobject.H.
References IOobject::instance(), and IOobject::path().
Referenced by Foam::readFields(), Foam::readUniformFields(), surfMesh::surfMesh(), and IOobject::writeHeader().
path() [1/2]
Foam::fileName path () const
Return complete path.
Definition at line 275 of file IOobject.C.
Referenced by searchableSurfaces::checkIntersection(), IOobjectList::IOobjectList(), IOobject::local(), IOobject::objectPath(), surfMesh::removeFiles(), motionSmootherAlgo::setDisplacementPatchFields(), surfMesh::surfMesh(), Time::writeObject(), and regIOobject::~regIOobject().
path() [2/2]
Foam::fileName path (const word & instance, const fileName & local = "") const
Return complete path with alternative instance and local.
Definition at line 289 of file IOobject.C.
objectPath()
fileName objectPath () const inline
Return complete path + object name.
Definition at line 363 of file IOobject.H.
References IOobject::filePath(), IOobject::headerOk(), IOobject::name(), IOobject::path(), IOobject::readHeader(), IOobject::writeBanner(), IOobject::writeDivider(), IOobject::writeEndDivider(), and IOobject::writeHeader().
Referenced by regIOobject::checkIn(), hexRef8::consistentSlowRefinement2(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), hexRef8::hexRef8(), IOdictionary::IOdictionary(), mappedFixedValueFvPatchField< Type >::mapper(), meshRefinement::mergePatchFacesUndo(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), polyMesh::polyMesh(), IOdictionary::readData(), regIOobject::readStream(), polyMesh::readUpdate(), hexRef8::setUnrefinement(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), surfacePatchIOList::surfacePatchIOList(), surfZoneIOList::surfZoneIOList(), meshReader::warnDuplicates(), boundaryRegion::writeDict(), cellTable::writeDict(), triSurfaceMesh::writeObject(), and distributedTriSurfaceMesh::writeObject().
filePath()
Foam::fileName filePath () const
Return complete path + object name if the file exists.
either in the case/processor or case otherwise null
Definition at line 299 of file IOobject.C.
References Foam::isDir(), Foam::isFile(), Foam::name(), fileName::null, path(), and Foam::system().
Referenced by fieldToCell::applyToSet(), regIOobject::checkIn(), regIOobject::close(), displacementMotionSolver::displacementMotionSolver(), IOobject::objectPath(), extendedEdgeMeshFormat::read(), and edgeMeshFormat::read().
readHeader()
bool readHeader (Istream & is)
Read header.
Definition at line 31 of file IOobjectReadHeader.C.
References IOobject::BAD, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOstream::format(), IOobject::GOOD, IOstream::good(), Foam::Info, InfoInFunction, IOWarningInFunction, token::isWord(), IOstream::lineNumber(), dictionary::lookup(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, IOobject::name(), IOstream::name(), Foam::nl, dictionary::readIfPresent(), SeriousIOErrorInFunction, IOstream::version(), token::wordToken(), and IOobject::writeHeader().
Referenced by IOobject::objectPath(), extendedEdgeMeshFormat::read(), and edgeMeshFormat::read().
headerOk()
bool headerOk ()
Read and check header info.
Definition at line 400 of file IOobject.C.
References Foam::endl(), InfoInFunction, and IOWarningInFunction.
Referenced by fieldToCell::applyToSet(), CompactIOField< T, BaseType >::CompactIOField(), extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), Time::findInstance(), fvSchemes::fvSchemes(), hexRef8::hexRef8(), hexRef8Data::hexRef8Data(), IOdictionary::IOdictionary(), IOMap< T >::IOMap(), IOmapDistribute::IOmapDistribute(), IOobjectList::IOobjectList(), IOobject::objectPath(), displacementMotionSolver::points0IO(), Foam::preservePatchTypes(), extendedEdgeMeshFormat::read(), edgeMeshFormat::read(), fieldAverage::readAveragingProperties(), boundaryRegion::readDict(), cellTable::readDict(), refinementHistory::refinementHistory(), topoSet::topoSet(), and uniformInterpolatedDisplacementPointPatchVectorField::uniformInterpolatedDisplacementPointPatchVectorField().
writeBanner()
Stream & writeBanner (Stream & os, bool noHint = false) inline static
Write the standard OpenFOAM file/dictionary banner.
Optionally without -*- C++ -*- editor hint (eg, for logs)
Definition at line 45 of file IOobjectI.H.
References Foam::FOAMversion.
Referenced by IOobject::objectPath(), argList::parse(), and IOobject::writeHeader().
writeDivider()
Stream & writeDivider (Stream & os) inline static
Write the standard file section divider.
Definition at line 98 of file IOobjectI.H.
Referenced by IOobject::objectPath(), argList::parse(), writeDictionary::write(), and IOobject::writeHeader().
writeEndDivider()
Stream & writeEndDivider (Stream & os) inline static
Write the standard end file divider.
Definition at line 108 of file IOobjectI.H.
Referenced by IOobject::objectPath(), meshReader::warnDuplicates(), and MeshedSurfaceProxy< Face >::write().
writeHeader() [1/2]
bool writeHeader (Ostream & os) const
Write header.
Definition at line 67 of file IOobjectWriteHeader.C.
References Foam::type().
Referenced by IOobject::objectPath(), IOdictionary::readData(), IOobject::readHeader(), meshReader::warnDuplicates(), edgeMeshFormat::write(), interpolationLookUpTable< scalar >::write(), MeshedSurfaceProxy< Face >::write(), boundaryRegion::writeDict(), and cellTable::writeDict().
writeHeader() [2/2]
bool writeHeader (Ostream & os, const word & objectType) const
Write header. Allow override of type.
Definition at line 35 of file IOobjectWriteHeader.C.
References IOobject::db(), objectRegistry::dbDir(), Foam::endl(), IOstream::format(), IOstream::good(), IOstream::info(), InfoInFunction, IOobject::instance(), IOobject::local(), IOobject::name(), Foam::nl, IOobject::note(), IOstream::version(), IOobject::writeBanner(), and IOobject::writeDivider().
good()
bool good () const inline
Definition at line 406 of file IOobject.H.
References IOobject::GOOD.
Referenced by IFstream::IFstream(), IFstream::operator()(), topoSet::topoSet(), and CompactIOField< T, BaseType >::writeObject().
bad()
bool bad () const inline
Definition at line 411 of file IOobject.H.
References IOobject::BAD, IOobject::info(), and IOobject::operator=().
info()
InfoProxy<IOobject> info () const inline
Return info proxy.
Used to print token information to a stream
Definition at line 421 of file IOobject.H.
Referenced by IOobject::bad(), and IFstream::IFstream().
operator=()
void operator= (const IOobject & io)
Definition at line 459 of file IOobject.C.
Referenced by IOobject::bad(), and regIOobject::operator=().
groupName() [2/2]
Foam::word groupName (Name name, const word & group) inline
Definition at line 31 of file IOobjectI.H.
References IOobject::group(), IOobject::name(), and word::null.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOobject/IOobject.H
src/OpenFOAM/db/IOobject/IOobject.C
src/OpenFOAM/db/IOobject/IOobjectI.H
src/OpenFOAM/db/IOobject/IOobjectReadHeader.C
src/OpenFOAM/db/IOobject/IOobjectWriteHeader.C