OpenFOAM: functionObject Class Reference
functionObject Class Reference abstract
Abstract base-class for Time/database function objects.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool read (const dictionary &)
Read and set the function object if its data have changed.
virtual bool execute ()=0
Called at each ++ or += of the time-loop.
virtual bool write ()=0
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Static Public Member Functions
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes
Switch log
Switch write log to Info.
Static Public Attributes
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Abstract base-class for Time/database function objects.
See also
Foam::functionObjectList Foam::functionObjects::timeControl
Source files
functionObject.H
functionObject.C
Definition at line 209 of file functionObject.H.
Constructor & Destructor Documentation
functionObject()
functionObject (const word & name)
Construct from components.
Definition at line 44 of file functionObject.C.
References functionObject::New().
~functionObject()
~functionObject () virtual
Destructor.
Definition at line 114 of file functionObject.C.
Referenced by functionObject::clone().
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
Referenced by probes::classifyFields().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , functionObject , dictionary , (const word &name, const Time &runTime, const dictionary &dict) , (name, runTime, dict))
clone()
autoPtr<functionObject> clone () const inline
Return clone.
Definition at line 258 of file functionObject.H.
References functionObject::adjustTimeStep(), functionObject::end(), functionObject::execute(), mesh, functionObject::movePoints(), functionObject::name(), functionObject::New(), NotImplemented, functionObject::read(), functionObject::updateMesh(), functionObject::write(), and functionObject::~functionObject().
New()
Foam::autoPtr< Foam::functionObject > New (const word & name, const Time & runTime, const dictionary & dict) static
Select from dictionary, based on its "type" entry.
Definition at line 54 of file functionObject.C.
References functionObject::debug, dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::found(), Foam::Info, dictionary::lookup(), functionObject::name(), and Foam::nl.
Referenced by functionObject::clone(), functionObject::functionObject(), functionObjectList::read(), and codedFunctionObject::redirectFunctionObject().
name()
const Foam::word & name () const
Return the name of this functionObject.
Definition at line 120 of file functionObject.C.
Referenced by functionObject::clone(), functionObject::New(), and surfaceFieldValue::outputDir().
read()
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Reimplemented in surfaceFieldValue, forces, pressure, fieldAverage, volFieldValue, regionSizeDistribution, wallBoundedStreamLine, streamLine, sampledSets, turbulenceFields, probes, forceCoeffs, nearWallFields, sampledSurfaces, fieldMinMax, fieldValueDelta, writeObjects, histogram, codedFunctionObject, wallShearStress, systemCall, icoUncoupledKinematicCloud, fieldValue, surfaceInterpolate, readFields, fieldCoordinateSystemTransform, wallHeatFlux, timeControl, patchProbes, cloudInfo, regionFunctionObject, writeVTK, residuals, removeRegisteredObject, scalarTransport, timeActivatedFileUpdate, abort, writeDictionary, processorField, moleFractions< ThermoType >, fieldExpression, yPlus, setTimeStepFunctionObject, CourantNo, specieReactionRates< ChemistryModelType >, blendingFactor, randomise, and dsmcFields.
Definition at line 126 of file functionObject.C.
References functionObject::log, dictionary::lookupOrDefault(), and functionObject::postProcess.
Referenced by functionObject::clone(), regionFunctionObject::read(), and functionObjectList::read().
execute()
virtual bool execute () pure virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual executeControl behaviour and forces execution (used in post-processing mode)
Implemented in forces, fieldAverage, regionSizeDistribution, wallBoundedStreamLine, streamLine, sampledSets, turbulenceFields, probes, forceCoeffs, nearWallFields, sampledSurfaces, fieldMinMax, fieldValueDelta, writeObjects, histogram, wallShearStress, systemCall, icoUncoupledKinematicCloud, fieldValue, surfaceInterpolate, readFields, codedFunctionObject, fieldCoordinateSystemTransform, wallHeatFlux, cloudInfo, timeControl, writeVTK, residuals, removeRegisteredObject, scalarTransport, timeActivatedFileUpdate, abort, writeDictionary, processorField, moleFractions< ThermoType >, writeCellCentres, XiReactionRate, writeCellVolumes, fieldExpression, yPlus, setTimeStepFunctionObject, specieReactionRates< ChemistryModelType >, and dsmcFields.
Referenced by functionObject::clone().
write()
virtual bool write () pure virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual writeControl behaviour and forces writing always (used in post-processing mode)
Implemented in surfaceFieldValue, forces, fieldAverage, volFieldValue, regionSizeDistribution, wallBoundedStreamLine, streamLine, sampledSets, turbulenceFields, probes, forceCoeffs, nearWallFields, sampledSurfaces, fieldMinMax, fieldValueDelta, writeObjects, histogram, systemCall, wallShearStress, icoUncoupledKinematicCloud, fieldValue, surfaceInterpolate, codedFunctionObject, readFields, fieldCoordinateSystemTransform, wallHeatFlux, cloudInfo, patchProbes, timeControl, writeVTK, residuals, removeRegisteredObject, scalarTransport, timeActivatedFileUpdate, abort, writeDictionary, processorField, moleFractions< ThermoType >, writeCellCentres, XiReactionRate, writeCellVolumes, fieldExpression, yPlus, setTimeStepFunctionObject, specieReactionRates< ChemistryModelType >, components, and dsmcFields.
Referenced by functionObject::clone().
end()
bool end () virtual
Called when Time::run() determines that the time-loop exits.
By default it simply calls execute().
Reimplemented in systemCall, codedFunctionObject, timeControl, and abort.
Definition at line 137 of file functionObject.C.
Referenced by functionObject::clone().
adjustTimeStep()
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Reimplemented in timeControl, and setTimeStepFunctionObject.
Definition at line 143 of file functionObject.C.
Referenced by functionObject::clone().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Reimplemented in wallBoundedStreamLine, streamLine, sampledSets, probes, sampledSurfaces, and timeControl.
Definition at line 149 of file functionObject.C.
Referenced by functionObject::clone().
movePoints()
void movePoints (const polyMesh & mesh) virtual
Update for changes of mesh.
Reimplemented in wallBoundedStreamLine, streamLine, sampledSets, probes, sampledSurfaces, and timeControl.
Definition at line 153 of file functionObject.C.
Referenced by functionObject::clone().
Member Data Documentation
debug
int debug static
Definition at line 231 of file functionObject.H.
Referenced by functionObject::New().
postProcess
bool postProcess static
Global post-processing mode switch.
Definition at line 234 of file functionObject.H.
Referenced by functionObject::read().
log
Switch log
Switch write log to Info.
Definition at line 237 of file functionObject.H.
Referenced by functionObject::read().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObject/functionObject.H
src/OpenFOAM/db/functionObjects/functionObject/functionObject.C