OpenFOAM: messageStream Class Reference
messageStream Class Reference
Class to handle messaging in a simple, consistent stream-based manner.
Public Types
enum errorSeverity { INFO, WARNING, SERIOUS, FATAL }
Severity flags.
Public Member Functions
messageStream (const string &title, errorSeverity, const int maxErrors=0)
Construct from components.
messageStream (const dictionary &)
Construct from dictionary.
const string & title () const
Return the title of this error type.
int maxErrors () const
Return the maximum number of errors before program termination.
int & maxErrors ()
Return non-const access to the maximum number of errors before.
OSstream & masterStream (const label communicator)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &)
Convert to OSstream.
operator OSstream & ()
Convert to OSstream for << operations.
OSstream & operator() ()
Explicitly convert to OSstream for << operations.
Static Public Attributes
static int level
Protected Attributes
string title_
errorSeverity severity_
int maxErrors_
int errorCount_
Detailed Description
Class to handle messaging in a simple, consistent stream-based manner.
The messageStream class is globaly instantiated with a title string a given severity, which controls the program termination, and a number of errors before termination. Errors, messages and other data are piped to the messageStream class in the standard manner.
Usage
messageStream
    << "message1" << "message2" << FoamDataType << endl;
Source files
messageStream.H
messageStream.C
Definition at line 68 of file messageStream.H.
Member Enumeration Documentation
errorSeverity
enum errorSeverity
Severity flags.
Enumerator
INFO
WARNING
SERIOUS
FATAL
Definition at line 74 of file messageStream.H.
Constructor & Destructor Documentation
messageStream() [1/2]
messageStream (const string & title, errorSeverity sev, const int maxErrors = 0)
Construct from components.
Definition at line 37 of file messageStream.C.
messageStream() [2/2]
messageStream (const dictionary & dict)
Construct from dictionary.
Definition at line 50 of file messageStream.C.
Member Function Documentation
title()
const string& title () const inline
Return the title of this error type.
Definition at line 118 of file messageStream.H.
References messageStream::title_.
Referenced by messageStream::operator()(), and Foam::operator<<().
maxErrors() [1/2]
int maxErrors () const inline
Return the maximum number of errors before program termination.
Definition at line 124 of file messageStream.H.
References messageStream::masterStream(), and messageStream::maxErrors_.
maxErrors() [2/2]
int& maxErrors () inline
Return non-const access to the maximum number of errors before.
program termination to enable user to reset it
Definition at line 131 of file messageStream.H.
masterStream()
Foam::OSstream & masterStream (const label communicator)
Convert to OSstream.
Prints to Pout for the master stream
Definition at line 59 of file messageStream.C.
References Foam::endl(), UPstream::master(), messageStream::operator()(), Foam::Pout, error::printStack(), Foam::Snull, UPstream::warnComm, and UPstream::worldComm.
Referenced by messageStream::maxErrors(), smoothSolver::solve(), fvMatrix< Type >::fvSolver::solve(), GAMGSolver::solve(), fvMatrix< Type >::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solver(), and fvMatrix< Type >::solveSegregated().
operator()() [1/6]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 80 of file messageStream.C.
References Foam::endl().
operator()() [2/6]
Foam::OSstream & operator() (const string & functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 99 of file messageStream.C.
operator()() [3/6]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const string & ioFileName, const label ioStartLineNumber = -1, const label ioEndLineNumber = -1)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 115 of file messageStream.C.
References Foam::endl().
operator()() [4/6]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const IOstream & ioStream)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 149 of file messageStream.C.
operator()() [5/6]
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const dictionary & dict)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 169 of file messageStream.C.
References Foam::abort(), dict, messageStream::errorCount_, Foam::FatalError, FatalErrorInFunction, messageStream::INFO, Foam::Info, messageStream::level, UPstream::master(), messageStream::maxErrors_, UPstream::parRun(), Foam::Pout, messageStream::SERIOUS, Foam::SeriousError, messageStream::severity_, Foam::Snull, Foam::Sout, messageStream::title(), messageStream::WARNING, and Foam::Warning.
operator OSstream &()
operator OSstream & ()
Convert to OSstream for << operations.
operator()() [6/6]
OSstream& operator() () inline
Explicitly convert to OSstream for << operations.
Definition at line 195 of file messageStream.H.
References Foam::Info, Foam::SeriousError, and Foam::Warning.
Referenced by messageStream::masterStream().
Member Data Documentation
title_
string title_ protected
Definition at line 87 of file messageStream.H.
Referenced by messageStream::title().
severity_
errorSeverity severity_ protected
Definition at line 88 of file messageStream.H.
Referenced by messageStream::operator()().
maxErrors_
int maxErrors_ protected
Definition at line 89 of file messageStream.H.
Referenced by messageStream::maxErrors(), and messageStream::operator()().
errorCount_
int errorCount_ protected
Definition at line 90 of file messageStream.H.
Referenced by messageStream::operator()().
level
int level static
Definition at line 97 of file messageStream.H.
Referenced by messageStream::operator()(), Foam::operator<<(), and IOobject::setBad().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/error/messageStream.H
src/OpenFOAM/db/error/messageStream.C