OpenFOAM: writeFile Class Reference
writeFile Class Reference
functionObject base class for writing single files
Public Member Functions
writeFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
~writeFile ()
Destructor.
void initStream (Ostream &os) const
Initialise the output stream for writing.
fileName baseFileDir () const
Return the base directory for output.
fileName baseTimeDir () const
Return the base directory for the current time value.
Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Static Public Attributes
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Protected Attributes
const objectRegistry & fileObr_
Reference to the region objectRegistry.
const word prefix_
Prefix.
Detailed Description
functionObject base class for writing single files
See also
Foam::functionObject Foam::functionObjects::logFiles
Source files
writeFile.H
writeFile.C
Definition at line 55 of file writeFile.H.
Constructor & Destructor Documentation
writeFile()
writeFile (const objectRegistry & obr, const word & prefix)
Construct from objectRegistry and prefix.
Definition at line 96 of file writeFile.C.
~writeFile()
~writeFile ()
Destructor.
Definition at line 108 of file writeFile.C.
Member Function Documentation
initStream()
void initStream (Ostream & os) const
Initialise the output stream for writing.
Definition at line 42 of file writeFile.C.
References writeFile::charWidth(), Foam::scientific(), IOstream::setf(), and Ostream::width().
Referenced by logFiles::createFiles().
baseFileDir()
Foam::fileName baseFileDir () const
Return the base directory for output.
Definition at line 49 of file writeFile.C.
References polyMesh::defaultRegion, writeFile::fileObr_, mesh, IOobject::name(), writeFile::outputPrefix, UPstream::parRun(), Time::path(), and objectRegistry::time().
Referenced by writeFile::baseTimeDir(), logFiles::createFiles(), and surfaceFieldValue::outputDir().
baseTimeDir()
Foam::fileName baseTimeDir () const
Return the base directory for the current time value.
Definition at line 78 of file writeFile.C.
References writeFile::baseFileDir(), writeFile::fileObr_, writeFile::prefix_, objectRegistry::time(), Time::timeName(), and writeFile::valueWidth().
valueWidth()
Foam::Omanip< int > valueWidth (const label offset = 0) const
Return the value width when writing to stream with optional offset.
Definition at line 85 of file writeFile.C.
References writeFile::addChars, IOstream::defaultPrecision(), and Foam::setw().
Referenced by writeFile::baseTimeDir().
writeCommented()
void writeCommented (Ostream & os, const string & str) const
Write a commented string to stream.
Definition at line 121 of file writeFile.C.
References writeFile::charWidth(), Foam::setf(), Foam::setw(), and writeFile::writeTabbed().
Referenced by writeFile::charWidth(), and volRegion::writeFileHeader().
writeTabbed()
void writeTabbed (Ostream & os, const string & str) const
Write a tabbed string to stream.
Definition at line 132 of file writeFile.C.
References writeFile::charWidth(), Foam::setw(), Foam::tab, and writeFile::writeHeader().
Referenced by writeFile::writeCommented(), and residuals::writeFileHeader().
writeHeader()
void writeHeader (Ostream & os, const string & str) const
Write a commented header to stream.
Definition at line 142 of file writeFile.C.
References writeFile::charWidth(), Foam::nl, Foam::setf(), and Foam::setw().
Referenced by writeFile::writeTabbed().
writeTime()
void writeTime (Ostream & os) const
Write the current time to stream.
Definition at line 152 of file writeFile.C.
References writeFile::charWidth(), writeFile::fileObr_, Foam::setw(), objectRegistry::time(), and Time::timeName().
writeHeaderValue()
void writeHeaderValue (Ostream & os, const string & property, const Type & value) const
Write a (commented) header property and value pair.
Definition at line 30 of file writeFileTemplates.C.
References Foam::nl, Foam::setf(), and Foam::setw().
Referenced by volRegion::writeFileHeader().
charWidth()
Foam::label charWidth () const
Return width of character stream output.
Definition at line 114 of file writeFile.C.
References writeFile::addChars, IOstream::defaultPrecision(), and writeFile::writeCommented().
Referenced by writeFile::initStream(), writeFile::writeCommented(), writeFile::writeHeader(), writeFile::writeTabbed(), and writeFile::writeTime().
Member Data Documentation
fileObr_
const objectRegistry& fileObr_ protected
Reference to the region objectRegistry.
Definition at line 63 of file writeFile.H.
Referenced by writeFile::baseFileDir(), writeFile::baseTimeDir(), logFiles::createFiles(), and writeFile::writeTime().
prefix_
const word prefix_ protected
Prefix.
Definition at line 66 of file writeFile.H.
Referenced by writeFile::baseTimeDir(), and logFiles::createFiles().
outputPrefix
const Foam::word outputPrefix static
Directory prefix.
Definition at line 83 of file writeFile.H.
Referenced by writeFile::baseFileDir().
addChars
Foam::label addChars = 7 static
Additional characters for writing.
Definition at line 86 of file writeFile.H.
Referenced by writeFile::charWidth(), and writeFile::valueWidth().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/writeFile/writeFile.H
src/OpenFOAM/db/functionObjects/writeFile/writeFile.C
src/OpenFOAM/db/functionObjects/writeFile/writeFileTemplates.C