OpenFOAM: IOobjectList Class Reference
IOobjectList Class Reference
List of IOobjects with searching and retrieving facilities.
Public Member Functions
IOobjectList (const label nIoObjects=128)
Construct given an initial estimate for the number of entries.
IOobjectList (const objectRegistry &db, const fileName &instance, const fileName &local="", IOobject::readOption r=IOobject::MUST_READ, IOobject::writeOption w=IOobject::NO_WRITE, bool registerObject=true)
Construct from objectRegistry and instance path.
IOobjectList (const IOobjectList &)
Construct as copy.
~IOobjectList ()
Destructor.
bool add (IOobject &)
Add an IOobject to the list.
bool remove (IOobject &)
Remove an IOobject from the list.
IOobject * lookup (const word &name) const
Lookup a given name and return IOobject ptr if found else nullptr.
IOobjectList lookup (const wordRe &name) const
Return the list for all IOobects whose name matches name.
IOobjectList lookup (const wordReList &patterns) const
Return the list for all IOobects whose name matches name.
IOobjectList lookupClass (const word &className) const
Return the list for all IOobjects of a given class.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of the IOobjects of given class.
wordList sortedNames (const word &className) const
Return the sorted list of names of the IOobjects of given class.
Public Member Functions inherited from HashPtrTable< IOobject >
HashPtrTable (const label size=128)
Construct given initial table size.
HashPtrTable (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
HashPtrTable (Istream &)
Construct from Istream using default Istream constructor class.
HashPtrTable (const dictionary &)
Construct from dictionary using default dictionary constructor.
HashPtrTable (const HashPtrTable< IOobject, word, string::hash > &)
Construct as copy.
~HashPtrTable ()
Destructor.
IOobject * remove (iterator &)
Remove and return the pointer specified by given iterator.
bool erase (iterator &)
Erase an hashedEntry specified by given iterator.
void clear ()
Clear all entries from table.
void write (Ostream &os) const
Write.
void operator= (const HashPtrTable< IOobject, word, string::hash > &)
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< T, Key, Hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< T, Key, Hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< Key, T >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const Key &) const
Return true if hashedEntry is found in table.
iterator find (const Key &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const Key &) const
Find and return an const_iterator set at the hashedEntry.
List< Key > toc () const
Return the table of contents.
List< Key > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const Key &, const T &newElmt)
Insert a new hashedEntry.
bool set (const Key &, const T &newElmt)
Assign a new hashedEntry, overwriting existing entries.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const Key &)
Erase a hashedEntry specified by the given key.
label erase (const UList< Key > &)
Remove entries given by the listed keys from this HashTable.
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< T, Key, Hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< T, Key, Hash > > xfer ()
Transfer contents to the Xfer container.
T & operator[] (const Key &)
Find and return a hashedEntry.
const T & operator[] (const Key &) const
Find and return a hashedEntry.
T & operator() (const Key &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< T, Key, Hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< Key, T >>)
Assignment to an initializer list.
bool operator== (const HashTable< T, Key, Hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< T, Key, Hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &rhs)
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Public Types inherited from HashPtrTable< IOobject >
typedef HashTable< IOobject *, word, string::hash >::iterator iterator
typedef HashTable< IOobject *, word, string::hash >::const_iterator const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef T value_type
Type of values the HashTable contains.
typedef T & reference
Type that can be used for storing into HashTable::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Detailed Description
List of IOobjects with searching and retrieving facilities.
Source files
IOobjectList.H
IOobjectList.C
Definition at line 50 of file IOobjectList.H.
Constructor & Destructor Documentation
IOobjectList() [1/3]
IOobjectList (const label nIoObjects = 128) explicit
Construct given an initial estimate for the number of entries.
Definition at line 33 of file IOobjectList.C.
IOobjectList() [2/3]
IOobjectList (const objectRegistry & db, const fileName & instance, const fileName & local = "", IOobject::readOption r = IOobject::MUST_READ, IOobject::writeOption w = IOobject::NO_WRITE, bool registerObject = true)
Construct from objectRegistry and instance path.
Definition at line 40 of file IOobjectList.C.
References objectRegistry::dbDir(), fileName::FILE, Time::findInstancePath(), forAll, IOobject::headerOk(), HashTable< T, Key, Hash >::insert(), Foam::isDir(), IOobject::path(), Foam::readDir(), and objectRegistry::time().
IOobjectList() [3/3]
IOobjectList (const IOobjectList & ioOL)
Construct as copy.
Definition at line 92 of file IOobjectList.C.
~IOobjectList()
~IOobjectList ()
Destructor.
Definition at line 100 of file IOobjectList.C.
Member Function Documentation
add()
bool add (IOobject & io)
Add an IOobject to the list.
Definition at line 106 of file IOobjectList.C.
References HashTable< T, Key, Hash >::insert(), and IOobject::name().
remove()
bool remove (IOobject & io)
Remove an IOobject from the list.
Definition at line 112 of file IOobjectList.C.
References HashTableCore::end(), HashPtrTable< IOobject >::erase(), HashTable< T *, Key, Hash >::find(), and IOobject::name().
lookup() [1/3]
Foam::IOobject * lookup (const word & name) const
Lookup a given name and return IOobject ptr if found else nullptr.
Definition at line 128 of file IOobjectList.C.
References HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::find(), and InfoInFunction.
lookup() [2/3]
Foam::IOobjectList lookup (const wordRe & name) const
Return the list for all IOobects whose name matches name.
Definition at line 153 of file IOobjectList.C.
References Foam::endl(), forAllConstIter(), InfoInFunction, HashTable< T, Key, Hash >::insert(), wordRe::match(), Foam::name(), and HashTable< T, Key, Hash >::size().
lookup() [3/3]
Foam::IOobjectList lookup (const wordReList & patterns) const
Return the list for all IOobects whose name matches name.
Definition at line 174 of file IOobjectList.C.
References Foam::endl(), forAllConstIter(), InfoInFunction, HashTable< T, Key, Hash >::insert(), wordReListMatcher::match(), Foam::name(), IOobjectList::names(), and HashTable< T, Key, Hash >::size().
lookupClass()
Foam::IOobjectList lookupClass (const word & className) const
Return the list for all IOobjects of a given class.
Definition at line 197 of file IOobjectList.C.
References Foam::endl(), forAllConstIter(), InfoInFunction, HashTable< T, Key, Hash >::insert(), and HashTable< T, Key, Hash >::size().
Referenced by Foam::MapConsistentVolFields(), Foam::MapLagrangianFields(), Foam::MapVolFields(), Foam::readFields(), Foam::readUniformFields(), pointFieldReconstructor::reconstructFields(), fvFieldReconstructor::reconstructFvSurfaceFields(), fvFieldReconstructor::reconstructFvVolumeFields(), fvFieldReconstructor::reconstructFvVolumeInternalFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), and Foam::UnMapped().
names() [1/2]
Foam::wordList names () const
Return the list of names of the IOobjects.
Definition at line 218 of file IOobjectList.C.
References HashTable< T *, Key, Hash >::toc().
Referenced by vtkPV3Foam::addToSelection(), vtkPVFoam::addToSelection(), IOobjectList::lookup(), and IOobjectList::sortedNames().
sortedNames() [1/2]
Foam::wordList sortedNames () const
Return the sorted list of names of the IOobjects.
Definition at line 224 of file IOobjectList.C.
References HashTable< T *, Key, Hash >::sortedToc().
names() [2/2]
Foam::wordList names (const word & className) const
Return the list of names of the IOobjects of given class.
Definition at line 230 of file IOobjectList.C.
References forAllConstIter(), List< T >::setSize(), and HashTable< T, Key, Hash >::size().
sortedNames() [2/2]
Foam::wordList sortedNames (const word & className) const
Return the sorted list of names of the IOobjects of given class.
Definition at line 249 of file IOobjectList.C.
References IOobjectList::names(), and Foam::sort().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOobjectList/IOobjectList.H
src/OpenFOAM/db/IOobjectList/IOobjectList.C