OpenFOAM: CompactIOField< T, BaseType > Class Template Reference
CompactIOField< T, BaseType > Class Template Reference
A Field of objects of type <T> with automated input and output using a compact storage. Behaves like IOField except when binary output in case it writes a CompactListList.
Public Member Functions
TypeName ("FieldField")
Runtime type information.
CompactIOField (const IOobject &)
Construct from IOobject.
CompactIOField (const IOobject &, const label)
Construct from IOobject and size.
CompactIOField (const IOobject &, const Field< T > &)
Construct from IOobject and a Field.
CompactIOField (const IOobject &, const Xfer< Field< T >> &)
Construct by transferring the Field contents.
virtual ~CompactIOField ()
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool writeData (Ostream &) const
Pure virtual writaData function.
void operator= (const CompactIOField< T, BaseType > &)
void operator= (const Field< T > &)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from Field< T >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const T &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< T > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< T >> &)
Construct by transferring the List contents.
Field (const UList< T > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< T >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< T > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< T >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< T > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< T > &mapF, const FieldMapper &map, const T &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< T > &mapF, const FieldMapper &map, const UList< T > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< T >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< T >> &tmapF, const FieldMapper &map, const T &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< T >> &tmapF, const FieldMapper &map, const UList< T > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< T > &)
Construct as copy.
Field (Field< T > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< T >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< T >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< T > > clone () const
Clone.
void map (const UList< T > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< T >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< T > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< T >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< T > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< T >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< T > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< T >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< T > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< T >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
VSForm block (const label start) const
tmp< Field< T > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< T > &)
void operator= (const UList< T > &)
void operator= (const SubField< T > &)
void operator= (const tmp< Field< T >> &)
void operator= (const T &)
void operator= (const zero)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator= (const tmp< Field > &rhs)
void operator+= (const UList< T > &)
void operator+= (const tmp< Field< T >> &)
void operator+= (const T &)
void operator-= (const UList< T > &)
void operator-= (const tmp< Field< T >> &)
void operator-= (const T &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator*= (const scalar &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from Field< T >
typedef pTraits< T >::cmptType cmptType
Component type.
typedef SubField< T > subField
Declare type of subField.
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from Field< T >
static const Field< T > & null ()
Return a null field.
static tmp< Field< T > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from Field< T >
static const char *const typeName
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class T, class BaseType>
class Foam::CompactIOField< T, BaseType >
A Field of objects of type <T> with automated input and output using a compact storage. Behaves like IOField except when binary output in case it writes a CompactListList.
Useful for fields of small subfields e.g. in lagrangian
Source files
CompactIOField.H
CompactIOField.C
Definition at line 50 of file CompactIOField.H.
Constructor & Destructor Documentation
CompactIOField() [1/4]
CompactIOField (const IOobject & io)
Construct from IOobject.
Definition at line 63 of file CompactIOField.C.
References IOobject::headerOk(), IOobject::MUST_READ, IOobject::READ_IF_PRESENT, and IOobject::readOpt().
Referenced by CompactIOField< T, BaseType >::CompactIOField().
CompactIOField() [2/4]
CompactIOField (const IOobject & io, const label size)
Construct from IOobject and size.
Definition at line 80 of file CompactIOField.C.
References CompactIOField< T, BaseType >::CompactIOField(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::READ_IF_PRESENT, IOobject::readOpt(), and List< Type >::setSize().
CompactIOField() [3/4]
CompactIOField (const IOobject & io, const Field< T > & list)
Construct from IOobject and a Field.
Definition at line 104 of file CompactIOField.C.
References CompactIOField< T, BaseType >::CompactIOField(), IOobject::headerOk(), IOobject::MUST_READ, Field< Type >::operator=(), IOobject::READ_IF_PRESENT, and IOobject::readOpt().
CompactIOField() [4/4]
CompactIOField (const IOobject & io, const Xfer< Field< T >> & list)
Construct by transferring the Field contents.
Definition at line 128 of file CompactIOField.C.
References IOobject::headerOk(), IOobject::MUST_READ, IOobject::READ_IF_PRESENT, IOobject::readOpt(), and List< Type >::transfer().
~CompactIOField()
~CompactIOField () virtual
Definition at line 151 of file CompactIOField.C.
References CompactIOField< T, BaseType >::writeObject().
Member Function Documentation
TypeName()
TypeName ("FieldField")
Runtime type information.
writeObject()
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const virtual
Write using given format, version and compression.
Reimplemented from regIOobject.
Definition at line 160 of file CompactIOField.C.
References IOstream::ASCII, IOobject::good(), Field< T >::typeName, and regIOobject::writeObject().
Referenced by CompactIOField< T, BaseType >::~CompactIOField().
writeData()
bool writeData (Ostream &) const virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 188 of file CompactIOField.C.
operator=() [1/2]
void operator= (const CompactIOField< T, BaseType > & rhs)
Definition at line 198 of file CompactIOField.C.
References Field< Type >::operator=().
operator=() [2/2]
void operator= (const Field< T > & rhs)
Definition at line 207 of file CompactIOField.C.
References IOstream::ASCII, forAll, Field< Type >::operator=(), List< T >::setSize(), List< T >::size(), and Field< T >::T().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOobjects/CompactIOField/CompactIOField.H
src/OpenFOAM/db/IOobjects/CompactIOField/CompactIOField.C