OpenFOAM: IFstream Class Reference
IFstream Class Reference
Input from file stream.
Public Member Functions
ClassName ("IFstream")
IFstream (const fileName &pathname, streamFormat format=ASCII, versionNumber version=currentVersion)
Construct from pathname.
~IFstream ()
Destructor.
const fileName & name () const
Return the name of the stream.
fileName & name ()
Return non-const access to the name of the stream.
virtual istream & stdStream ()
Access to underlying std::istream.
virtual const istream & stdStream () const
Const access to underlying std::istream.
virtual void print (Ostream &) const
Print description of IOstream to Ostream.
IFstream & operator() () const
Return a non-const reference to const IFstream.
Public Member Functions inherited from ISstream
ISstream (istream &is, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct as wrapper around istream.
virtual ~ISstream ()
Destructor.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
ISstream & get (char &)
Raw, low-level get character function.
int peek ()
Raw, low-level peek function.
ISstream & getLine (string &)
Raw, low-level getline into a string function.
ISstream & putback (const char &)
Raw, low-level putback character function.
virtual Istream & read (token &)
Return next token from stream.
virtual Istream & read (char &)
Read a character.
virtual Istream & read (word &)
Read a word.
virtual Istream & read (string &)
Read a string (including enclosing double-quotes).
virtual Istream & read (label &)
Read a label.
virtual Istream & read (floatScalar &)
Read a floatScalar.
virtual Istream & read (doubleScalar &)
Read a doubleScalar.
virtual Istream & read (char *, std::streamsize)
Read binary block.
virtual Istream & rewind ()
Rewind and return the stream so that it may be read again.
virtual ios_base::fmtflags flags (const ios_base::fmtflags flags)
Set flags of output stream.
Public Member Functions inherited from Istream
Istream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Istream ()
Destructor.
void putBack (const token &)
Put back token.
bool getBack (token &)
Get the put back token if there is one and return true.
bool peekBack (token &)
Peek at the put back token without removing it.
Istream & readBegin (const char *funcName)
Istream & readEnd (const char *funcName)
Istream & readEndBegin (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Return a non-const reference to const Istream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from IOstream
label lineNumber_
Detailed Description
Input from file stream.
Source files
IFstream.H
IFstream.C
Definition at line 81 of file IFstream.H.
Constructor & Destructor Documentation
IFstream()
IFstream (const fileName & pathname, streamFormat format = ASCII, versionNumber version = currentVersion)
Construct from pathname.
Definition at line 84 of file IFstream.C.
References Foam::endl(), IOobject::good(), IOobject::info(), InfoInFunction, and IOobject::setBad().
~IFstream()
~IFstream ()
Destructor.
Definition at line 126 of file IFstream.C.
Member Function Documentation
ClassName()
ClassName ("IFstream")
name() [1/2]
const fileName& name () const inline virtual
Return the name of the stream.
Reimplemented from ISstream.
Definition at line 116 of file IFstream.H.
Referenced by includeEntry::execute(), includeEtcEntry::execute(), argList::parse(), Foam::parseNASCoord(), NASedgeFormat::read(), NASsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), externalCoupledMixedFvPatchField< scalar >::readData(), STARCDCore::readHeader(), STARCD::readHeader(), and STARCDCore::readPoints().
name() [2/2]
fileName& name () inline virtual
Return non-const access to the name of the stream.
Reimplemented from ISstream.
Definition at line 122 of file IFstream.H.
stdStream() [1/2]
std::istream & stdStream () virtual
Access to underlying std::istream.
Reimplemented from ISstream.
Definition at line 132 of file IFstream.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
stdStream() [2/2]
const std::istream & stdStream () const virtual
Const access to underlying std::istream.
Reimplemented from ISstream.
Definition at line 143 of file IFstream.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
print()
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from ISstream.
Definition at line 154 of file IFstream.C.
References ISstream::print().
operator()()
Foam::IFstream & operator() () const
Return a non-const reference to const IFstream.
Needed for read-constructors where the stream argument is temporary: e.g. thing thisThing(IFstream("thingFileName")());
Definition at line 164 of file IFstream.C.
References Foam::exit(), IOerror::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOobject::good(), and Foam::isFile().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Fstreams/IFstream.H
src/OpenFOAM/db/IOstreams/Fstreams/IFstream.C