OpenFOAM: logFiles Class Reference
logFiles Class Reference abstract
functionObject base class for creating, maintaining and writing log files e.g. integrated of averaged field data vs time.
Public Member Functions
logFiles (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
virtual ~logFiles ()
Destructor.
const wordList & names () const
Return const access to the names.
PtrList< OFstream > & files ()
Return access to the files.
OFstream & file ()
Return access to the file (if only 1)
OFstream & file (const label i)
Return file 'i'.
virtual bool write ()
Write function.
Public Member Functions inherited from writeFile
writeFile (const objectRegistry &obr, const word &prefix)
Construct from objectRegistry and prefix.
~writeFile ()
Destructor.
void initStream (Ostream &os) const
Initialise the output stream for writing.
fileName baseFileDir () const
Return the base directory for output.
fileName baseTimeDir () const
Return the base directory for the current time value.
Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
void writeTime (Ostream &os) const
Write the current time to stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
label charWidth () const
Return width of character stream output.
Protected Member Functions
virtual void createFiles ()
Create the output file.
virtual void resetNames (const wordList &names)
Reset the list of names from a wordList.
virtual void resetName (const word &name)
Reset the list of names to a single name entry.
virtual void writeFileHeader (const label i=0)=0
File header information.
Protected Attributes
wordList names_
File names.
PtrList< OFstream > filePtrs_
File pointer.
Protected Attributes inherited from writeFile
const objectRegistry & fileObr_
Reference to the region objectRegistry.
const word prefix_
Prefix.
Additional Inherited Members
Static Public Attributes inherited from writeFile
static const word outputPrefix
Directory prefix.
static label addChars = 7
Additional characters for writing.
Detailed Description
functionObject base class for creating, maintaining and writing log files e.g. integrated of averaged field data vs time.
See also
Foam::functionObject Foam::functionObjects::writeFile
Source files
logFiles.H
logFiles.C
Definition at line 57 of file logFiles.H.
Constructor & Destructor Documentation
logFiles()
logFiles (const objectRegistry & obr, const word & prefix)
Construct from objectRegistry and prefix.
Definition at line 95 of file logFiles.C.
~logFiles()
~logFiles () virtual
Destructor.
Definition at line 108 of file logFiles.C.
Member Function Documentation
createFiles()
void createFiles () protected virtual
Create the output file.
Definition at line 32 of file logFiles.C.
References writeFile::baseFileDir(), writeFile::fileObr_, logFiles::filePtrs_, forAll, IOstream::good(), writeFile::initStream(), UPstream::master(), Foam::mkDir(), logFiles::names_, writeFile::prefix_, Time::startTime(), objectRegistry::time(), Time::timeName(), dimensioned< Type >::value(), and logFiles::writeFileHeader().
Referenced by logFiles::write().
resetNames()
void resetNames (const wordList & names) protected virtual
Reset the list of names from a wordList.
Definition at line 66 of file logFiles.C.
References List< T >::append(), List< T >::clear(), logFiles::filePtrs_, UPstream::master(), logFiles::names_, and List< T >::size().
Referenced by cloudInfo::read().
resetName()
void resetName (const word & name) protected virtual
Reset the list of names to a single name entry.
Definition at line 79 of file logFiles.C.
References List< T >::append(), List< T >::clear(), logFiles::filePtrs_, UPstream::master(), and logFiles::names_.
writeFileHeader()
virtual void writeFileHeader (const label i = 0) protected pure virtual
File header information.
Implemented in surfaceFieldValue, forces, volFieldValue, forceCoeffs, fieldMinMax, fieldValueDelta, wallShearStress, wallHeatFlux, cloudInfo, and residuals.
Referenced by logFiles::createFiles().
names()
const Foam::wordList & names () const
Return const access to the names.
Definition at line 114 of file logFiles.C.
References logFiles::names_.
files()
Foam::PtrList< Foam::OFstream > & files ()
Return access to the files.
Definition at line 147 of file logFiles.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, logFiles::filePtrs_, and UPstream::master().
file() [1/2]
Foam::OFstream & file ()
Return access to the file (if only 1)
Definition at line 120 of file logFiles.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, logFiles::filePtrs_, UPstream::master(), and WarningInFunction.
Referenced by residuals::writeFileHeader(), and residuals::writeResidual().
file() [2/2]
Foam::OFstream & file (const label i)
Return file 'i'.
Definition at line 160 of file logFiles.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, logFiles::filePtrs_, and UPstream::master().
write()
bool write () virtual
Write function.
Reimplemented in surfaceFieldValue, forces, volFieldValue, forceCoeffs, fieldMinMax, fieldValueDelta, wallShearStress, fieldValue, wallHeatFlux, cloudInfo, residuals, yPlus, and specieReactionRates< ChemistryModelType >.
Definition at line 180 of file logFiles.C.
References logFiles::createFiles().
Referenced by yPlus::write(), residuals::write(), cloudInfo::write(), wallHeatFlux::write(), fieldValue::write(), wallShearStress::write(), fieldValueDelta::write(), fieldMinMax::write(), forceCoeffs::write(), and forces::write().
Member Data Documentation
names_
wordList names_ protected
File names.
Definition at line 67 of file logFiles.H.
Referenced by logFiles::createFiles(), logFiles::names(), logFiles::resetName(), and logFiles::resetNames().
filePtrs_
PtrList<OFstream> filePtrs_ protected
File pointer.
Definition at line 70 of file logFiles.H.
Referenced by logFiles::createFiles(), logFiles::file(), logFiles::files(), logFiles::resetName(), and logFiles::resetNames().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/logFiles/logFiles.H
src/OpenFOAM/db/functionObjects/logFiles/logFiles.C