OpenFOAM: timeControl Class Reference
timeControl Class Reference
Public Member Functions
TypeName ("timeControl")
Runtime type information.
timeControl (const word &name, const Time &, const dictionary &)
Construct from components.
const Time & time () const
Return time database.
const dictionary & dict () const
Return the input dictionary.
const Foam::timeControl & executeControl () const
Return the execute control object.
const Foam::timeControl & writeControl () const
Return the write control object.
const functionObject & filter () const
Return the functionObject filter.
virtual bool execute ()
Called at each ++ or += of the time-loop.
virtual bool write ()
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool read (const dictionary &)
Read and set the function object if its data have changed.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Detailed Description
Note
Since the timeIndex is used directly from Foam::Time, it is unaffected by user-time conversions. For example, Foam::engineTime might cause writeInterval to be degrees crank angle, but the functionObject execution interval would still be in timestep.
Source files
timeControlFunctionObject.H
timeControlFunctionObject.C
Definition at line 57 of file timeControlFunctionObject.H.
Constructor & Destructor Documentation
timeControl()
timeControl (const word & name, const Time & t, const dictionary & dict)
Construct from components.
Definition at line 63 of file timeControlFunctionObject.C.
Member Function Documentation
TypeName()
TypeName ("timeControl")
Runtime type information.
time()
const Foam::Time & time () const inline
Return time database.
Definition at line 28 of file timeControlFunctionObjectI.H.
dict()
const Foam::dictionary & dict () const inline
Return the input dictionary.
Definition at line 34 of file timeControlFunctionObjectI.H.
executeControl()
const Foam::timeControl & executeControl () const inline
Return the execute control object.
Definition at line 41 of file timeControlFunctionObjectI.H.
writeControl()
const Foam::timeControl & writeControl () const inline
Return the write control object.
Definition at line 48 of file timeControlFunctionObjectI.H.
filter()
const Foam::functionObject & filter () const inline
Return the functionObject filter.
Definition at line 55 of file timeControlFunctionObjectI.H.
execute()
bool execute () virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual executeControl behaviour and forces execution (used in post-processing mode)
Implements functionObject.
Definition at line 88 of file timeControlFunctionObject.C.
write()
bool write () virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual writeControl behaviour and forces writing (used in post-processing mode)
Implements functionObject.
Definition at line 99 of file timeControlFunctionObject.C.
end()
bool end () virtual
Called when Time::run() determines that the time-loop exits.
Reimplemented from functionObject.
Definition at line 110 of file timeControlFunctionObject.C.
adjustTimeStep()
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Reimplemented from functionObject.
Definition at line 122 of file timeControlFunctionObject.C.
References Foam::max(), timeControl::ocAdjustableRunTime, and timeControl::read().
read()
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Reimplemented from functionObject.
Definition at line 168 of file timeControlFunctionObject.C.
References dict, and timeControl::updateMesh().
Referenced by timeControl::adjustTimeStep().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Reimplemented from functionObject.
Definition at line 190 of file timeControlFunctionObject.C.
References timeControl::movePoints().
Referenced by timeControl::read().
movePoints()
void movePoints (const polyMesh & mesh) virtual
Update for changes of mesh.
Reimplemented from functionObject.
Definition at line 202 of file timeControlFunctionObject.C.
Referenced by timeControl::updateMesh().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/timeControl/timeControlFunctionObject.H
src/OpenFOAM/db/functionObjects/timeControl/timeControlFunctionObject.C
src/OpenFOAM/db/functionObjects/timeControl/timeControlFunctionObjectI.H