OpenFOAM: UPstream Class Reference
UPstream Class Reference
Inter-processor communications stream.
Classes
class commsStruct
Structure for communicating between processors.
class communicator
Helper class for allocating/freeing communicators.
class listEq
combineReduce operator for lists. Used for counting.
Public Types
enum commsTypes { blocking, scheduled, nonBlocking }
Types of communications.
Public Member Functions
ClassName ("UPstream")
UPstream (const commsTypes commsType)
Construct given optional buffer size.
commsTypes commsType () const
Get the communications type of the stream.
commsTypes commsType (const commsTypes ct)
Set the communications type of the stream.
Static Public Member Functions
static label allocateCommunicator (const label parent, const labelList &subRanks, const bool doPstream=true)
Allocate a new communicator.
static void freeCommunicator (const label communicator, const bool doPstream=true)
Free a previously allocated communicator.
static void freeCommunicators (const bool doPstream)
Free all communicators.
static int baseProcNo (const label myComm, const int procID)
Return physical processor number (i.e. processor number in.
static label procNo (const label comm, const int baseProcID)
Return processor number in communicator (given physical processor.
static label procNo (const label myComm, const label currentComm, const int currentProcID)
Return processor number in communicator (given processor number.
static void addValidParOptions (HashTable< string > &validParOptions)
Add the valid option this type of communications library.
static bool init (int &argc, char **&argv)
Initialisation function called from main.
static label nRequests ()
Get number of outstanding requests.
static void resetRequests (const label sz)
Truncate number of outstanding requests.
static void waitRequests (const label start=0)
Wait until all requests (from start onwards) have finished.
static void waitRequest (const label i)
Wait until request i has finished.
static bool finishedRequest (const label i)
Non-blocking comms: has request i finished?
static int allocateTag (const char *)
static int allocateTag (const word &)
static void freeTag (const char *, const int tag)
static void freeTag (const word &, const int tag)
static bool & parRun ()
Is this a parallel run?
static label nProcs (const label communicator=0)
Number of processes in parallel run.
static int masterNo ()
Process index of the master.
static bool master (const label communicator=0)
Am I the master process.
static int myProcNo (const label communicator=0)
Number of this process (starting from masterNo() = 0)
static label parent (const label communicator)
static List< int > & procID (label communicator)
Process ID of given process index.
static int firstSlave ()
Process index of first slave.
static int lastSlave (const label communicator=0)
Process index of last slave.
static const List< commsStruct > & linearCommunication (const label communicator=0)
Communication schedule for linear all-to-master (proc 0)
static const List< commsStruct > & treeCommunication (const label communicator=0)
Communication schedule for tree all-to-master (proc 0)
static int & msgType ()
Message tag of standard messages.
static void exit (int errnum=1)
Exit program.
static void abort ()
Abort program.
static void allToAll (const labelUList &sendData, labelUList &recvData, const label communicator=0)
Exchange label with all processors (in the communicator).
Static Public Attributes
static const NamedEnum< commsTypes, 3 > commsTypeNames
static bool floatTransfer
Should compact transfer be used in which floats replace doubles.
static int nProcsSimpleSum
Number of processors at which the sum algorithm changes from linear.
static commsTypes defaultCommsType
Default commsType.
static int nPollProcInterfaces
Number of polling cycles in processor updates.
static label worldComm
Default communicator (all processors)
static label warnComm
Debugging: warn for use of any communicator differing from warnComm.
Protected Attributes
commsTypes commsType_
Communications type of this stream.
Detailed Description
Inter-processor communications stream.
Source files
UPstream.H
UPstream.C
UPstreamCommsStruct.C
gatherScatter.C
combineGatherScatter.C
gatherScatterList.C
Definition at line 58 of file UPstream.H.
Member Enumeration Documentation
commsTypes
enum commsTypes
Types of communications.
Enumerator
blocking
scheduled
nonBlocking
Definition at line 64 of file UPstream.H.
Constructor & Destructor Documentation
UPstream()
UPstream (const commsTypes commsType) inline
Construct given optional buffer size.
Definition at line 283 of file UPstream.H.
References UPstream::allocateCommunicator(), UPstream::freeCommunicator(), UPstream::freeCommunicators(), and UPstream::parent().
Member Function Documentation
ClassName()
ClassName ("UPstream")
allocateCommunicator()
Foam::label allocateCommunicator (const label parent, const labelList & subRanks, const bool doPstream = true) static
Allocate a new communicator.
Definition at line 250 of file UPstream.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::freeCommunicator(), Foam::Pout, and List< T >::size().
Referenced by masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), NamedEnum< directionType, 3 >::names(), globalMeshData::updateMesh(), and UPstream::UPstream().
freeCommunicator()
void freeCommunicator (const label communicator, const bool doPstream = true) static
Free a previously allocated communicator.
Definition at line 316 of file UPstream.C.
References Foam::endl(), and Foam::Pout.
Referenced by UPstream::allocateCommunicator(), globalMeshData::updateMesh(), UPstream::UPstream(), UPstream::communicator::~communicator(), eagerGAMGProcAgglomeration::~eagerGAMGProcAgglomeration(), manualGAMGProcAgglomeration::~manualGAMGProcAgglomeration(), masterCoarsestGAMGProcAgglomeration::~masterCoarsestGAMGProcAgglomeration(), and procFacesGAMGProcAgglomeration::~procFacesGAMGProcAgglomeration().
freeCommunicators()
void freeCommunicators (const bool doPstream) static
Free all communicators.
Definition at line 343 of file UPstream.C.
References forAll.
Referenced by UPstream::UPstream().
baseProcNo()
int baseProcNo (const label myComm, const int procID) static
Return physical processor number (i.e. processor number in.
worldComm) given communicator and procssor
Definition at line 355 of file UPstream.C.
References UPstream::parent(), and UPstream::procID().
Referenced by UPstream::communicator::operator label(), and UPstream::procNo().
procNo() [1/2]
Foam::label procNo (const label comm, const int baseProcID) static
Return processor number in communicator (given physical processor.
number) (= reverse of baseProcNo)
Definition at line 371 of file UPstream.C.
References Foam::findIndex().
Referenced by UPstream::communicator::operator label().
procNo() [2/2]
Foam::label procNo (const label myComm, const label currentComm, const int currentProcID) static
Return processor number in communicator (given processor number.
and communicator)
Definition at line 389 of file UPstream.C.
References UPstream::baseProcNo(), UPstream::defaultCommsType, UPstream::floatTransfer, dictionary::lookup(), UPstream::nProcsSimpleSum, Foam::debug::optimisationSwitch(), Foam::debug::optimisationSwitches(), registerOptSwitch(), and serialComm.
addValidParOptions()
void addValidParOptions (HashTable< string > & validParOptions) static
Add the valid option this type of communications library.
adds/requires on the command line
Definition at line 31 of file UPstream.C.
Referenced by UPstream::communicator::operator label().
init()
bool init (int & argc, char **& argv) static
Initialisation function called from main.
Spawns slave processes and initialises inter-communication
Definition at line 35 of file UPstream.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
Referenced by UPstream::communicator::operator label(), and ParRunControl::runPar().
nRequests()
Foam::label nRequests () static
Get number of outstanding requests.
Definition at line 107 of file UPstream.C.
Referenced by mapDistributeBase::compact(), GeometricField< Type, PatchField, GeoMesh >::Boundary::evaluate(), Foam::evaluateConstraintTypes(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), UPstream::communicator::operator label(), processorFvPatchField< Type >::updateInterfaceMatrix(), and processorGAMGInterfaceField::updateInterfaceMatrix().
resetRequests()
void resetRequests (const label sz) static
Truncate number of outstanding requests.
Definition at line 113 of file UPstream.C.
Referenced by UPstream::communicator::operator label().
waitRequests()
void waitRequests (const label start = 0) static
Wait until all requests (from start onwards) have finished.
Definition at line 117 of file UPstream.C.
Referenced by mapDistributeBase::compact(), GeometricField< Type, PatchField, GeoMesh >::Boundary::evaluate(), Foam::evaluateConstraintTypes(), GAMGProcAgglomeration::globalCellCells(), and UPstream::communicator::operator label().
waitRequest()
void waitRequest (const label i) static
Wait until request i has finished.
Definition at line 121 of file UPstream.C.
Referenced by UPstream::communicator::operator label(), processorFvPatchField< Type >::updateInterfaceMatrix(), and processorGAMGInterfaceField::updateInterfaceMatrix().
finishedRequest()
bool finishedRequest (const label i) static
Non-blocking comms: has request i finished?
Definition at line 125 of file UPstream.C.
References NotImplemented.
Referenced by UPstream::communicator::operator label().
allocateTag() [1/2]
int allocateTag (const char * s) static
Definition at line 597 of file UPstream.C.
References Foam::endl(), Foam::PstreamGlobals::freedTags_, Foam::PstreamGlobals::nTags_, Foam::Pout, and DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove().
Referenced by UPstream::communicator::operator label().
allocateTag() [2/2]
int allocateTag (const word & s) static
Definition at line 626 of file UPstream.C.
References Foam::endl(), Foam::PstreamGlobals::freedTags_, Foam::PstreamGlobals::nTags_, Foam::Pout, and DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove().
freeTag() [1/2]
void freeTag (const char * s, const int tag) static
Definition at line 655 of file UPstream.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), Foam::PstreamGlobals::freedTags_, and Foam::Pout.
Referenced by UPstream::communicator::operator label().
freeTag() [2/2]
void freeTag (const word & s, const int tag) static
Definition at line 671 of file UPstream.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), Foam::PstreamGlobals::freedTags_, and Foam::Pout.
parRun()
static bool& parRun () inline static
Is this a parallel run?
Definition at line 393 of file UPstream.H.
Referenced by error::abort(), IOerror::abort(), snappyLayerDriver::addLayers(), meshRefinement::balance(), writeFile::baseFileDir(), boundBox::boundBox(), processorCyclicPolyPatch::calcGeometry(), processorPolyPatch::calcGeometry(), FaceCellWave< Type, TrackingData >::cellToFace(), polyBoundaryMesh::checkParallelSync(), CloudFunctionObject< CloudType >::CloudFunctionObject(), mapDistributeBase::compact(), processorFvPatch::coupled(), processorPointPatchField< Type >::coupled(), processorCyclicPointPatchField< Type >::coupled(), processorFvsPatchField< Type >::coupled(), processorCyclicFvsPatchField< Type >::coupled(), cyclicAMIFvPatch::coupled(), cyclicACMIFvPatch::coupled(), processorFvPatchField< Type >::coupled(), processorPolyPatch::coupled(), simpleGeomDecomp::decompose(), decompositionMethod::decompose(), conformalVoronoiMesh::decomposition(), processorFvPatch::delta(), fvMeshDistribute::distribute(), refinementHistory::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), snappyLayerDriver::doLayers(), snappyRefineDriver::doRefine(), PointEdgeWave< Type, TrackingData >::edgeToPoint(), GeometricField< Type, PatchField, GeoMesh >::Boundary::evaluate(), Foam::evaluateConstraintTypes(), error::exit(), IOerror::exit(), sampledSurfaces::expire(), polyMesh::findCell(), distributedTriSurfaceMesh::findNearest(), Pstream::gather(), Pstream::gatherList(), distributedTriSurfaceMesh::getField(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), GAMGProcAgglomeration::globalCellCells(), InflationInjection< CloudType >::InflationInjection(), processorPolyPatch::initGeometry(), processorPolyPatch::initOrder(), processorPolyPatch::initUpdateMesh(), PointEdgeWave< Type, TrackingData >::iterate(), FaceCellWave< Type, TrackingData >::iterate(), LUscalarMatrix::LUscalarMatrix(), patchMeanVelocityForce::magUbarAve(), processorFvPatch::makeWeights(), NamedEnum< directionType, 3 >::names(), polyBoundaryMesh::neighbourEdges(), minEqOp< labelPair >::operator()(), messageStream::operator()(), processorPolyPatch::order(), InflationInjection< CloudType >::parcelsToInject(), probes::prepare(), sampledSurfaces::read(), regIOobject::read(), Time::readModifiedObjects(), sampledSets::sampledSets(), sampledSurfaces::sampledSurfaces(), Pstream::scatter(), Pstream::scatterList(), Time::setControls(), fvMeshSubset::setLargeCellSubset(), syncTools::syncEdgeMap(), syncTools::syncEdgePositions(), syncTools::syncPointMap(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), sampledSurfaces::update(), processorPolyPatch::updateMesh(), streamLine::write(), wallBoundedStreamLine::write(), meshToMeshMethod::writeConnectivity(), and fieldMinMax::writeFileHeader().
nProcs()
static label nProcs (const label communicator = 0) inline static
Number of processes in parallel run.
Definition at line 399 of file UPstream.H.
References List< T >::size().
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), meshRefinement::balanceAndRefine(), mapDistributeBase::calcCompactAddressing(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkParallelSync(), mappedPatchBase::collectSamples(), fieldValue::combineFields(), Foam::combineReduce(), mapDistributeBase::compact(), GAMGAgglomeration::continueAgglomerating(), fvMeshDistribute::countCells(), simpleGeomDecomp::decompose(), fvMeshDistribute::distribute(), refinementHistory::distribute(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), mapDistributeBase::exchangeAddressing(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), distributedTriSurfaceMesh::findNearest(), Pstream::gather(), Pstream::gatherList(), globalIndex::globalIndex(), UPstream::lastSlave(), LUscalarMatrix::LUscalarMatrix(), mapDistributeBase::mapDistributeBase(), NamedEnum< directionType, 3 >::names(), minEqOp< labelPair >::operator()(), lessProcPatches::operator()(), UPstream::listEq::operator()(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), fvMeshDistribute::printCoupleInfo(), mapDistributeBase::printLayout(), regIOobject::read(), mapDistributeBase::receive(), Foam::reduce(), meshRefinement::refineAndBalance(), meshRefinement::refineCandidates(), Foam::returnReduce(), Pstream::scatter(), Pstream::scatterList(), mapDistributeBase::schedule(), mapDistributeBase::send(), Time::setControls(), fvMeshSubset::setLargeCellSubset(), ParSortableList< Type >::sort(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), globalMeshData::updateMesh(), streamLine::write(), and wallBoundedStreamLine::write().
masterNo()
static int masterNo () inline static
Process index of the master.
Definition at line 405 of file UPstream.H.
Referenced by simpleGeomDecomp::decompose(), LUscalarMatrix::LUscalarMatrix(), UPstream::master(), minEqOp< labelPair >::operator()(), argList::parse(), mapDistributeBase::schedule(), globalMeshData::sharedPoints(), syncTools::syncEdgeMap(), and syncTools::syncPointMap().
master()
static bool master (const label communicator = 0) inline static
Am I the master process.
Definition at line 411 of file UPstream.H.
References UPstream::masterNo().
Referenced by effectivenessHeatExchangerSource::addSup(), mappedPatchBase::calcMapping(), viewFactor::calculate(), argList::check(), polyBoundaryMesh::checkParallelSync(), argList::checkRootCase(), fieldValue::combineFields(), commSchedule::commSchedule(), logFiles::createFiles(), simpleGeomDecomp::decompose(), logFiles::file(), logFiles::files(), probes::findElements(), cachedRandom::globalGaussNormal(), cachedRandom::globalPosition(), cachedRandom::globalRandomise01(), cachedRandom::globalSample01(), IOdictionary::IOdictionary(), JobInfo::JobInfo(), LUscalarMatrix::LUscalarMatrix(), messageStream::masterStream(), NamedEnum< directionType, 3 >::names(), isNotEqOp< T >::operator()(), minEqOp< labelPair >::operator()(), ListPlusEqOp< T, Size >::operator()(), messageStream::operator()(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), porosityModel::porosityModel(), probes::prepare(), sampledSurfaces::read(), regIOobject::read(), sampledSets::read(), IOdictionary::readData(), logFiles::resetName(), logFiles::resetNames(), mapDistributeBase::schedule(), globalMeshData::sharedPoints(), JobInfo::signalEnd(), rigidBodyMeshMotionSolver::solve(), rigidBodyMeshMotion::solve(), rigidBodyMotion::solve(), ParSortableList< Type >::sort(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), sampledSurfaces::update(), sixDoFRigidBodyMotion::update(), fileMonitor::updateStates(), solution::upgradeSolverDict(), JobInfo::write(), yPlus::write(), residuals::write(), cloudInfo::write(), wallHeatFlux::write(), wallShearStress::write(), histogram::write(), fieldValueDelta::write(), sampledSurfaces::write(), forceCoeffs::write(), sampledSets::write(), streamLine::write(), wallBoundedStreamLine::write(), regionSizeDistribution::write(), volFieldValue::write(), forces::write(), surfaceFieldValue::write(), residuals::writeFileHeader(), and JobInfo::~JobInfo().
myProcNo()
static int myProcNo (const label communicator = 0) inline static
Number of this process (starting from masterNo() = 0)
Definition at line 417 of file UPstream.H.
Referenced by surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZonesToMesh(), GAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), mapDistributeBase::calcCompactAddressing(), viewFactor::calculate(), GAMGAgglomeration::calculateRegionMaster(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkParallelSync(), mappedPatchBase::collectSamples(), fieldValue::combineFields(), mapDistributeBase::compact(), noDecomp::decompose(), fvMeshDistribute::distribute(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), mapDistributeBase::exchangeAddressing(), processorField::execute(), InjectionModel< CloudType >::findCellAtPosition(), probes::findElements(), patchProbes::findElements(), distributedTriSurfaceMesh::findNearest(), mappedPatchBase::findSamples(), Pstream::gather(), lduPrimitiveMesh::gather(), Pstream::gatherList(), GAMGProcAgglomeration::globalCellCells(), globalIndex::globalIndex(), globalIndex::isLocal(), lduPrimitiveMesh::lduPrimitiveMesh(), globalIndex::localSize(), meshToMesh::mapAndOpTgtToSrc(), mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), conformalVoronoiMesh::maxSurfaceProtrusion(), meshRefinement::mergeBaffles(), NamedEnum< directionType, 3 >::names(), regionSplit::nLocalRegions(), minEqOp< labelPair >::operator()(), ListPlusEqOp< T, Size >::operator()(), lessProcPatches::operator()(), InflationInjection< CloudType >::parcelsToInject(), argList::parse(), UOPstream::print(), fvMeshDistribute::printCoupleInfo(), mapDistributeBase::printLayout(), backgroundMeshDecomposition::procBounds(), regIOobject::read(), indexedVertex< Gt, Vb >::referred(), Pstream::scatter(), Pstream::scatterList(), mapDistributeBase::schedule(), Time::setControls(), fvMeshSubset::setLargeCellSubset(), patchInjectionBase::setPositionAndCell(), ParSortableList< Type >::sort(), ThermoSurfaceFilm< CloudType >::splashInteraction(), refinementHistory::subset(), globalIndex::toGlobal(), globalIndex::toLocal(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), patchInjectionBase::updateMesh(), meshToMeshMethod::writeConnectivity(), and extendedCellToFaceStencil::writeStencilStats().
parent()
static label parent (const label communicator) inline static
Definition at line 422 of file UPstream.H.
Referenced by UPstream::baseProcNo(), and UPstream::UPstream().
procID()
static List<int>& procID (label communicator) inline static
Process ID of given process index.
Definition at line 428 of file UPstream.H.
Referenced by UPstream::baseProcNo(), and UPstream::listEq::operator()().
firstSlave()
static int firstSlave () inline static
Process index of first slave.
Definition at line 434 of file UPstream.H.
Referenced by LUscalarMatrix::LUscalarMatrix(), minEqOp< labelPair >::operator()(), argList::parse(), mapDistributeBase::schedule(), globalMeshData::sharedPoints(), syncTools::syncEdgeMap(), and syncTools::syncPointMap().
lastSlave()
static int lastSlave (const label communicator = 0) inline static
Process index of last slave.
Definition at line 440 of file UPstream.H.
References UPstream::linearCommunication(), and UPstream::nProcs().
Referenced by LUscalarMatrix::LUscalarMatrix(), minEqOp< labelPair >::operator()(), argList::parse(), mapDistributeBase::schedule(), globalMeshData::sharedPoints(), syncTools::syncEdgeMap(), and syncTools::syncPointMap().
linearCommunication()
static const List<commsStruct>& linearCommunication (const label communicator = 0) inline static
Communication schedule for linear all-to-master (proc 0)
Definition at line 447 of file UPstream.H.
References UPstream::treeCommunication().
Referenced by Foam::combineReduce(), Pstream::gather(), Pstream::gatherList(), UPstream::lastSlave(), regIOobject::read(), Foam::reduce(), Foam::returnReduce(), Pstream::scatter(), and Pstream::scatterList().
treeCommunication()
static const List<commsStruct>& treeCommunication (const label communicator = 0) inline static
Communication schedule for tree all-to-master (proc 0)
Definition at line 456 of file UPstream.H.
Referenced by Foam::combineReduce(), Pstream::gather(), Pstream::gatherList(), UPstream::linearCommunication(), regIOobject::read(), Foam::reduce(), Foam::returnReduce(), Pstream::scatter(), and Pstream::scatterList().
msgType()
static int& msgType () inline static
Message tag of standard messages.
Definition at line 464 of file UPstream.H.
Referenced by decompositionMethod::calcCellCells(), extendedCentredCellToFaceStencil::compact(), extendedCentredFaceToCellStencil::compact(), extendedCentredCellToCellStencil::compact(), mapDistributeBase::constructHasFlip(), UOPstream::flags(), UIPstream::flags(), globalIndex::gather(), lduPrimitiveMesh::gather(), Foam::gAverage(), GAMGProcAgglomeration::globalCellCells(), globalIndex::globalIndex(), Foam::gSumCmptProd(), Foam::gSumProd(), regionModel::interRegionAMI(), lduPrimitiveMesh::lduPrimitiveMesh(), LUscalarMatrix::LUscalarMatrix(), mappedPatchFieldBase< Type >::mappedField(), mapDistribute::transformPosition::operator()(), Pstream::Pstream(), regIOobject::read(), Foam::reduce(), fvMatrix< Type >::relax(), mapDistributeBase::schedule(), processorFvPatch::tag(), processorCyclicPolyPatch::tag(), processorPolyPatch::tag(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), mapDistribute::transformStart(), mappedVelocityFluxFixedValueFvPatchField::updateCoeffs(), wideBandDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), filmPyrolysisTemperatureCoupledFvPatchScalarField::updateCoeffs(), filmPyrolysisVelocityCoupledFvPatchVectorField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), MarshakRadiationFvPatchScalarField::updateCoeffs(), MarshakRadiationFixedTemperatureFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), and globalMeshData::updateMesh().
commsType() [1/2]
commsTypes commsType () const inline
Get the communications type of the stream.
Definition at line 471 of file UPstream.H.
References UPstream::commsType_.
commsType() [2/2]
commsTypes commsType (const commsTypes ct) inline
Set the communications type of the stream.
Definition at line 477 of file UPstream.H.
References UPstream::abort(), UPstream::allToAll(), UPstream::commsType_, UPstream::exit(), and UPstream::commsStruct::operator<<.
exit()
void exit (int errnum = 1) static
Exit program.
Definition at line 46 of file UPstream.C.
References NotImplemented.
Referenced by UPstream::commsType(), error::exit(), IOerror::exit(), ParRunControl::runPar(), and ParRunControl::~ParRunControl().
abort()
void abort () static
Abort program.
Definition at line 52 of file UPstream.C.
References NotImplemented.
Referenced by error::abort(), IOerror::abort(), and UPstream::commsType().
allToAll()
void allToAll (const labelUList & sendData, labelUList & recvData, const label communicator = 0) static
Exchange label with all processors (in the communicator).
sendData[proci] is the label to send to proci. After return recvData contains the data from the other processors.
Definition at line 85 of file UPstream.C.
References UList< T >::deepCopy().
Referenced by UPstream::commsType(), and Foam::reduce().
Member Data Documentation
commsTypeNames
const Foam::NamedEnum< Foam::UPstream::commsTypes, 3 > commsTypeNames static
Definition at line 71 of file UPstream.H.
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::evaluate(), PstreamBuffers::finishedSends(), NamedEnum< directionType, 3 >::names(), argList::parse(), addcommsTypeToOpt::readData(), and addcommsTypeToOpt::writeData().
commsType_
commsTypes commsType_ protected
Communications type of this stream.
Definition at line 248 of file UPstream.H.
Referenced by UPstream::commsType(), and UOPstream::~UOPstream().
floatTransfer
bool floatTransfer static
Should compact transfer be used in which floats replace doubles.
reducing the bandwidth requirement at the expense of some loss in accuracy
Definition at line 261 of file UPstream.H.
Referenced by processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), argList::parse(), UPstream::procNo(), processorFvPatchField< Type >::updateInterfaceMatrix(), and processorGAMGInterfaceField::updateInterfaceMatrix().
nProcsSimpleSum
int nProcsSimpleSum static
Number of processors at which the sum algorithm changes from linear.
to tree
Definition at line 265 of file UPstream.H.
Referenced by Foam::combineReduce(), Pstream::gather(), Pstream::gatherList(), argList::parse(), UPstream::procNo(), regIOobject::read(), Foam::reduce(), Foam::returnReduce(), Pstream::scatter(), and Pstream::scatterList().
defaultCommsType
Foam::UPstream::commsTypes defaultCommsType static
Default commsType.
Definition at line 268 of file UPstream.H.
Referenced by polyBoundaryMesh::clearAddressing(), mapDistributeBase::distribute(), mappedPatchBase::distribute(), GeometricField< Type, PatchField, GeoMesh >::Boundary::evaluate(), Foam::evaluateConstraintTypes(), pointBoundaryMesh::findIndices(), pointBoundaryMesh::movePoints(), polyBoundaryMesh::movePoints(), argList::parse(), UPstream::procNo(), addcommsTypeToOpt::readData(), mapDistributeBase::reverseDistribute(), mappedPatchBase::reverseDistribute(), pointBoundaryMesh::updateMesh(), polyBoundaryMesh::updateMesh(), and addcommsTypeToOpt::writeData().
nPollProcInterfaces
int nPollProcInterfaces static
Number of polling cycles in processor updates.
Definition at line 271 of file UPstream.H.
Referenced by argList::parse(), and addcommsTypeToOpt::writeData().
worldComm
Foam::label worldComm static
Default communicator (all processors)
Definition at line 274 of file UPstream.H.
Referenced by decompositionMethod::calcCellCells(), mapDistributeBase::exchangeAddressing(), messageStream::masterStream(), NamedEnum< directionType, 3 >::names(), Pstream::Pstream(), regIOobject::read(), Foam::reduce(), globalMeshData::updateMesh(), and addcommsTypeToOpt::writeData().
warnComm
Foam::label warnComm static
Debugging: warn for use of any communicator differing from warnComm.
Definition at line 277 of file UPstream.H.
Referenced by GAMGSolver::GAMGSolver(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), processorGAMGInterface::initInternalFieldTransfer(), processorGAMGInterface::internalFieldTransfer(), messageStream::masterStream(), Foam::reduce(), GAMGSolver::solve(), processorGAMGInterfaceField::updateInterfaceMatrix(), and addcommsTypeToOpt::writeData().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.C