OpenFOAM: addcommsTypeToOpt Class Reference
addcommsTypeToOpt Class Reference
Public Member Functions
addcommsTypeToOpt (const char *name)
virtual ~addcommsTypeToOpt ()
virtual void readData (Foam::Istream &is)
Read.
virtual void writeData (Foam::Ostream &os) const
Write.
Public Member Functions inherited from simpleRegIOobject
simpleRegIOobject (void(*fn)(const char *name, simpleRegIOobject *), const char *name)
Construct from objectregistry inserter and name.
virtual ~simpleRegIOobject ()
Destructor.
Detailed Description
Definition at line 462 of file UPstream.C.
Constructor & Destructor Documentation
addcommsTypeToOpt()
addcommsTypeToOpt (const char * name) inline
Definition at line 468 of file UPstream.C.
~addcommsTypeToOpt()
virtual ~addcommsTypeToOpt () inline virtual
Definition at line 473 of file UPstream.C.
Member Function Documentation
readData()
virtual void readData (Foam::Istream &) inline virtual
Read.
Implements simpleRegIOobject.
Definition at line 476 of file UPstream.C.
References UPstream::commsTypeNames, UPstream::defaultCommsType, and NamedEnum< Enum, nEnum >::read().
writeData()
virtual void writeData (Foam::Ostream &) const inline virtual
Write.
Implements simpleRegIOobject.
Definition at line 484 of file UPstream.C.
References Foam::addcommsTypeToOpt_, UPstream::commsTypeNames, UPstream::defaultCommsType, UPstream::nPollProcInterfaces, Foam::debug::optimisationSwitch(), registerOptSwitch(), UPstream::warnComm, and UPstream::worldComm.
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.C