OpenFOAM: UIPstream Class Reference
UIPstream Class Reference
Input inter-processor communications stream operating on external buffer.
Public Member Functions
UIPstream (const commsTypes commsType, const int fromProcNo, DynamicList< char > &externalBuf, label &externalBufPosition, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool clearAtEnd=false, streamFormat format=BINARY, versionNumber version=currentVersion)
Construct given process index to read from and optional buffer size,.
UIPstream (const int fromProcNo, PstreamBuffers &)
Construct given buffers.
~UIPstream ()
Destructor.
ios_base::fmtflags flags () const
Return flags of output stream.
Istream & read (token &)
Return next token from stream.
Istream & read (char &)
Read a character.
Istream & read (word &)
Read a word.
Istream & read (string &)
Istream & read (label &)
Read a label.
Istream & read (floatScalar &)
Read a floatScalar.
Istream & read (doubleScalar &)
Read a doubleScalar.
Istream & read (char *, std::streamsize)
Read binary block.
Istream & rewind ()
Rewind and return the stream so that it may be read again.
ios_base::fmtflags flags (const ios_base::fmtflags)
Set flags of stream.
void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from UPstream
ClassName ("UPstream")
UPstream (const commsTypes commsType)
Construct given optional buffer size.
commsTypes commsType () const
Get the communications type of the stream.
commsTypes commsType (const commsTypes ct)
Set the communications type of the stream.
Public Member Functions inherited from Istream
Istream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Istream ()
Destructor.
void putBack (const token &)
Put back token.
bool getBack (token &)
Get the put back token if there is one and return true.
bool peekBack (token &)
Peek at the put back token without removing it.
Istream & readBegin (const char *funcName)
Istream & readEnd (const char *funcName)
Istream & readEndBegin (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Return a non-const reference to const Istream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Static Public Member Functions
static label read (const commsTypes commsType, const int fromProcNo, char *buf, const std::streamsize bufSize, const int tag=UPstream::msgType(), const label communicator=0)
Read into given buffer from given processor and return the.
Static Public Member Functions inherited from UPstream
static label allocateCommunicator (const label parent, const labelList &subRanks, const bool doPstream=true)
Allocate a new communicator.
static void freeCommunicator (const label communicator, const bool doPstream=true)
Free a previously allocated communicator.
static void freeCommunicators (const bool doPstream)
Free all communicators.
static int baseProcNo (const label myComm, const int procID)
Return physical processor number (i.e. processor number in.
static label procNo (const label comm, const int baseProcID)
Return processor number in communicator (given physical processor.
static label procNo (const label myComm, const label currentComm, const int currentProcID)
Return processor number in communicator (given processor number.
static void addValidParOptions (HashTable< string > &validParOptions)
Add the valid option this type of communications library.
static bool init (int &argc, char **&argv)
Initialisation function called from main.
static label nRequests ()
Get number of outstanding requests.
static void resetRequests (const label sz)
Truncate number of outstanding requests.
static void waitRequests (const label start=0)
Wait until all requests (from start onwards) have finished.
static void waitRequest (const label i)
Wait until request i has finished.
static bool finishedRequest (const label i)
Non-blocking comms: has request i finished?
static int allocateTag (const char *)
static int allocateTag (const word &)
static void freeTag (const char *, const int tag)
static void freeTag (const word &, const int tag)
static bool & parRun ()
Is this a parallel run?
static label nProcs (const label communicator=0)
Number of processes in parallel run.
static int masterNo ()
Process index of the master.
static bool master (const label communicator=0)
Am I the master process.
static int myProcNo (const label communicator=0)
Number of this process (starting from masterNo() = 0)
static label parent (const label communicator)
static List< int > & procID (label communicator)
Process ID of given process index.
static int firstSlave ()
Process index of first slave.
static int lastSlave (const label communicator=0)
Process index of last slave.
static const List< commsStruct > & linearCommunication (const label communicator=0)
Communication schedule for linear all-to-master (proc 0)
static const List< commsStruct > & treeCommunication (const label communicator=0)
Communication schedule for tree all-to-master (proc 0)
static int & msgType ()
Message tag of standard messages.
static void exit (int errnum=1)
Exit program.
static void abort ()
Abort program.
static void allToAll (const labelUList &sendData, labelUList &recvData, const label communicator=0)
Exchange label with all processors (in the communicator).
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Additional Inherited Members
Public Types inherited from UPstream
enum commsTypes { blocking, scheduled, nonBlocking }
Types of communications.
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Attributes inherited from UPstream
static const NamedEnum< commsTypes, 3 > commsTypeNames
static bool floatTransfer
Should compact transfer be used in which floats replace doubles.
static int nProcsSimpleSum
Number of processors at which the sum algorithm changes from linear.
static commsTypes defaultCommsType
Default commsType.
static int nPollProcInterfaces
Number of polling cycles in processor updates.
static label worldComm
Default communicator (all processors)
static label warnComm
Debugging: warn for use of any communicator differing from warnComm.
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from UPstream
commsTypes commsType_
Communications type of this stream.
Protected Attributes inherited from IOstream
label lineNumber_
Detailed Description
Input inter-processor communications stream operating on external buffer.
Source files
UIPstream.H
UIPstream.C
Definition at line 53 of file UIPstream.H.
Constructor & Destructor Documentation
UIPstream() [1/2]
UIPstream (const commsTypes commsType, const int fromProcNo, DynamicList< char > & externalBuf, label & externalBufPosition, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool clearAtEnd = false, streamFormat format = BINARY, versionNumber version = currentVersion)
Construct given process index to read from and optional buffer size,.
read format and IO version
Definition at line 34 of file UIPread.C.
References NotImplemented.
UIPstream() [2/2]
UIPstream (const int fromProcNo, PstreamBuffers & buffers)
Construct given buffers.
Definition at line 60 of file UIPread.C.
References NotImplemented, and UIPstream::read().
~UIPstream()
~UIPstream ()
Destructor.
Definition at line 81 of file UIPstream.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::clearStorage(), Foam::endl(), IOstream::eof(), Foam::Pout, and List< T >::size().
Member Function Documentation
flags() [1/2]
ios_base::fmtflags flags () const inline virtual
Return flags of output stream.
Implements IOstream.
Definition at line 120 of file UIPstream.H.
References UPstream::msgType(), UIPstream::read(), and UIPstream::rewind().
read() [1/9]
Foam::label read (const commsTypes commsType, const int fromProcNo, char * buf, const std::streamsize bufSize, const int tag = UPstream::msgType(), const label communicator = 0) static
Read into given buffer from given processor and return the.
message size
Definition at line 79 of file UIPread.C.
References NotImplemented.
Referenced by mapDistributeBase::compact(), UIPstream::flags(), Pstream::gather(), Pstream::gatherList(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::initInterfaceMatrixUpdate(), UIPstream::read(), Pstream::scatter(), Pstream::scatterList(), and UIPstream::UIPstream().
read() [2/9]
Foam::Istream & read (token & t) virtual
Return next token from stream.
Implements Istream.
Definition at line 100 of file UIPstream.C.
References token::ADD, token::ASSIGN, token::BEGIN_BLOCK, token::BEGIN_LIST, token::BEGIN_SQR, Foam::constant::universal::c, token::COLON, token::COMMA, token::DIVIDE, token::DOUBLE_SCALAR, token::END_BLOCK, token::END_LIST, token::END_SQR, token::END_STATEMENT, token::FLOAT_SCALAR, Istream::getBack(), token::compound::isCompound(), token::LABEL, token::lineNumber(), IOstream::lineNumber(), token::MULTIPLY, token::compound::New(), UIPstream::read(), token::setBad(), IOstream::setBad(), token::STRING, token::SUBTRACT, token::type(), token::VARIABLE, token::VERBATIMSTRING, and token::WORD.
read() [3/9]
Foam::Istream & read (char & c) virtual
Read a character.
Implements Istream.
Definition at line 264 of file UIPstream.C.
read() [4/9]
Foam::Istream & read (word & str) virtual
Read a word.
Implements Istream.
Definition at line 273 of file UIPstream.C.
read() [5/9]
Foam::Istream & read (string & str) virtual
Implements Istream.
Definition at line 284 of file UIPstream.C.
read() [6/9]
Foam::Istream & read (label & val) virtual
Read a label.
Implements Istream.
Definition at line 295 of file UIPstream.C.
read() [7/9]
Foam::Istream & read (floatScalar & val) virtual
Read a floatScalar.
Implements Istream.
Definition at line 302 of file UIPstream.C.
read() [8/9]
Foam::Istream & read (doubleScalar & val) virtual
Read a doubleScalar.
Implements Istream.
Definition at line 309 of file UIPstream.C.
read() [9/9]
Foam::Istream & read (char * data, std::streamsize count) virtual
Read binary block.
Implements Istream.
Definition at line 316 of file UIPstream.C.
References Foam::abort(), IOstream::BINARY, Foam::FatalError, FatalErrorInFunction, and IOstream::format().
rewind()
Foam::Istream & rewind () virtual
Rewind and return the stream so that it may be read again.
Implements Istream.
Definition at line 330 of file UIPstream.C.
Referenced by UIPstream::flags().
flags() [2/2]
ios_base::fmtflags flags (const ios_base::fmtflags) inline virtual
Set flags of stream.
Implements IOstream.
Definition at line 171 of file UIPstream.H.
References UIPstream::print().
print()
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from IOstream.
Definition at line 337 of file UIPstream.C.
References Foam::endl().
Referenced by UIPstream::flags().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UIPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UIPstream.C
src/Pstream/dummy/UIPread.C