OpenFOAM: INew< T > Class Template Reference
INew< T > Class Template Reference
A helper class when constructing from an Istream or dictionary.
Public Member Functions
INew ()
Construct null.
autoPtr< T > operator() (Istream &is) const
Construct from Istream.
autoPtr< T > operator() (const word &, Istream &is) const
Construct from word and Istream.
autoPtr< T > operator() (const dictionary &dict) const
Construct from dictionary.
autoPtr< T > operator() (const word &, const dictionary &dict) const
Construct from word and dictionary.
Detailed Description
template<class T>
class Foam::INew< T >
A helper class when constructing from an Istream or dictionary.
Definition at line 49 of file INew.H.
Constructor & Destructor Documentation
INew()
INew () inline
Construct null.
Definition at line 55 of file INew.H.
Member Function Documentation
operator()() [1/4]
autoPtr<T> operator() (Istream & is) const inline
Construct from Istream.
Definition at line 59 of file INew.H.
References Foam::New().
operator()() [2/4]
autoPtr<T> operator() (const word & , Istream & is) const inline
Construct from word and Istream.
Definition at line 65 of file INew.H.
References Foam::New().
operator()() [3/4]
autoPtr<T> operator() (const dictionary & dict) const inline
Construct from dictionary.
Definition at line 71 of file INew.H.
References Foam::New().
operator()() [4/4]
autoPtr<T> operator() (const word & , const dictionary & dict) const inline
Construct from word and dictionary.
Definition at line 77 of file INew.H.
References Foam::New().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/IOstreams/INew.H