OpenFOAM: OSstream Class Reference
OSstream Class Reference
Generic output stream.
Public Member Functions
OSstream (ostream &os, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
virtual Ostream & write (const token &)
Write next token to stream.
virtual Ostream & write (const char)
Write character.
virtual Ostream & write (const char *)
Write character string.
virtual Ostream & write (const word &)
Write word.
virtual Ostream & write (const string &)
Write string.
virtual Ostream & writeQuoted (const std::string &, const bool quoted=true)
Write std::string surrounded by quotes.
virtual Ostream & write (const int32_t)
Write int32_t.
virtual Ostream & write (const int64_t)
Write int64_t.
virtual Ostream & write (const floatScalar)
Write floatScalar.
virtual Ostream & write (const doubleScalar)
Write doubleScalar.
virtual Ostream & write (const char *, std::streamsize)
Write binary block.
virtual void indent ()
Add indentation characters.
virtual ios_base::fmtflags flags (const ios_base::fmtflags flags)
Set flags of output stream.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual int width () const
Get width of output field.
virtual int width (const int)
Set width of output field (and return old width)
virtual int precision () const
Get precision of output field.
virtual int precision (const int)
Set precision of output field (and return old precision)
virtual ostream & stdStream ()
Access to underlying std::ostream.
virtual const ostream & stdStream () const
Const access to underlying std::ostream.
virtual void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Ostream ()
Destructor.
virtual Ostream & write (const keyType &)
Write keyType.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Incrememt the indent level.
void decrIndent ()
Decrememt the indent level.
Ostream & writeKeyword (const keyType &)
Write the keyword followed by an appropriate indentation.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from Ostream
unsigned short indentLevel_
Current indent level.
Protected Attributes inherited from IOstream
label lineNumber_
Static Protected Attributes inherited from Ostream
static const unsigned short indentSize_ = 4
Number of spaces per indent level.
static const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Detailed Description
Generic output stream.
Source files
OSstream.H
OSstreamI.H
OSstream.C
Definition at line 51 of file OSstream.H.
Constructor & Destructor Documentation
OSstream()
OSstream (ostream & os, const string & name, streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED) inline
Set stream status.
Definition at line 31 of file OSstreamI.H.
Member Function Documentation
name() [1/2]
virtual const fileName& name () const inline virtual
Return the name of the stream.
Useful for Fstream to return the filename
Reimplemented from IOstream.
Reimplemented in OFstream.
Definition at line 88 of file OSstream.H.
Referenced by mappedPatchBase::calcMapping(), cyclicPolyPatch::calcTransforms(), fvMotionSolverCore::cellMotionBoundaryTypes(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), timeVaryingMappedFixedValueFvPatchField< Type >::checkTable(), meshObject::clear(), meshObject::clearUpto(), dynamicCode::copyAndFilter(), meshToMesh::mapAndOpTgtToSrc(), fvMeshAdder::MapDimFields(), fvMeshAdder::MapSurfaceFields(), fvMeshAdder::MapVolFields(), meshObject::movePoints(), MeshObject< fvMesh, MoveableMeshObject, CentredFitSnGradData< Polynomial > >::New(), ifEqEqOp< value >::operator()(), oldCyclicPolyPatch::order(), processorPolyPatch::order(), cyclicPolyPatch::order(), motionSmootherAlgo::setDisplacementPatchFields(), removeFaces::setRefinement(), hexRef8::setRefinement(), triSurface::triSurfInstance(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValueFvPatchField< Type >::updateCoeffs(), and meshObject::updateMesh().
name() [2/2]
virtual fileName& name () inline virtual
Return non-const access to the name of the stream.
Useful to alter the stream name
Reimplemented from IOstream.
Reimplemented in OFstream.
Definition at line 95 of file OSstream.H.
flags() [1/2]
std::ios_base::fmtflags flags () const virtual
Return flags of output stream.
Implements IOstream.
Definition at line 259 of file OSstream.C.
write() [1/10]
Foam::Ostream & write (const token & t) virtual
Write next token to stream.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 32 of file OSstream.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::HASH, token::stringToken(), token::type(), token::VARIABLE, token::VERBATIMSTRING, and OSstream::writeQuoted().
Referenced by searchableSurfaces::checkIntersection(), OSstream::endl(), prefixOSstream::write(), OBJstream::write(), and OBJstream::writeQuoted().
write() [2/10]
Foam::Ostream & write (const char c) virtual
Write character.
Implements Ostream.
Reimplemented in OBJstream, and prefixOSstream.
Definition at line 50 of file OSstream.C.
References Foam::constant::universal::c, IOstream::lineNumber_, token::NL, and IOstream::setState().
write() [3/10]
Foam::Ostream & write (const char * str) virtual
Write character string.
Implements Ostream.
Reimplemented in ensightFile, OBJstream, and prefixOSstream.
Definition at line 62 of file OSstream.C.
References string::count(), IOstream::lineNumber_, token::NL, and IOstream::setState().
write() [4/10]
Foam::Ostream & write (const word & str) virtual
Write word.
Implements Ostream.
Reimplemented in OBJstream, and prefixOSstream.
Definition at line 71 of file OSstream.C.
References IOstream::setState().
write() [5/10]
Foam::Ostream & write (const string & str) virtual
Write string.
In the rare case that the string contains a final trailing backslash, it will be dropped to the appearance of an escaped double-quote.
Implements Ostream.
Reimplemented in ensightFile, OBJstream, and prefixOSstream.
Definition at line 79 of file OSstream.C.
References token::BEGIN_STRING, Foam::constant::universal::c, token::END_STRING, IOstream::lineNumber_, token::NL, IOstream::setState(), and OSstream::writeQuoted().
writeQuoted()
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Implements Ostream.
Reimplemented in OBJstream, and prefixOSstream.
Definition at line 125 of file OSstream.C.
References token::BEGIN_STRING, Foam::constant::universal::c, string::count(), token::END_STRING, IOstream::lineNumber_, token::NL, and IOstream::setState().
Referenced by dynamicCode::copyAndFilter(), OSstream::write(), and prefixOSstream::writeQuoted().
write() [6/10]
Foam::Ostream & write (const int32_t val) virtual
Write int32_t.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 186 of file OSstream.C.
References IOstream::setState().
write() [7/10]
Foam::Ostream & write (const int64_t val) virtual
Write int64_t.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 194 of file OSstream.C.
References IOstream::setState().
write() [8/10]
Foam::Ostream & write (const floatScalar val) virtual
Write floatScalar.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 202 of file OSstream.C.
References IOstream::setState().
write() [9/10]
Foam::Ostream & write (const doubleScalar val) virtual
Write doubleScalar.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 210 of file OSstream.C.
References IOstream::setState().
write() [10/10]
Foam::Ostream & write (const char * buf, std::streamsize count) virtual
Write binary block.
Implements Ostream.
Reimplemented in prefixOSstream, and ensightFile.
Definition at line 218 of file OSstream.C.
References Foam::abort(), token::BEGIN_LIST, IOstream::BINARY, token::END_LIST, Foam::FatalIOError, FatalIOErrorInFunction, IOstream::format(), and IOstream::setState().
indent()
void indent () virtual
Add indentation characters.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 237 of file OSstream.C.
References Ostream::indentLevel_, and Ostream::indentSize_.
Referenced by prefixOSstream::indent().
flags() [2/2]
std::ios_base::fmtflags flags (const ios_base::fmtflags flags) virtual
Set flags of output stream.
Implements IOstream.
Definition at line 265 of file OSstream.C.
flush()
void flush () virtual
Flush stream.
Implements Ostream.
Definition at line 246 of file OSstream.C.
Referenced by DSMCCloud< DSMCParcel< ParcelType > >::dumpParticlePositions(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), externalCoupledMixedFvPatchField< scalar >::transferData(), and Cloud< streamLineParticle >::writePositions().
endl()
void endl () virtual
Add newline and flush stream.
Implements Ostream.
Definition at line 252 of file OSstream.C.
References OSstream::write().
width() [1/2]
int width () const virtual
Get width of output field.
Implements Ostream.
Definition at line 273 of file OSstream.C.
width() [2/2]
int width (const int w) virtual
Set width of output field (and return old width)
Implements Ostream.
Definition at line 279 of file OSstream.C.
precision() [1/2]
int precision () const virtual
Get precision of output field.
Implements Ostream.
Definition at line 285 of file OSstream.C.
Referenced by ensightAsciiStream::ensightAsciiStream(), ensightFile::ensightFile(), Foam::stringOps::getVariable(), Foam::stringOps::inplaceExpand(), NamedEnum< directionType, 3 >::names(), Time::readDict(), and ensightSetWriter< Type >::write().
precision() [2/2]
int precision (const int p) virtual
Set precision of output field (and return old precision)
Implements Ostream.
Definition at line 291 of file OSstream.C.
stdStream() [1/2]
virtual ostream& stdStream () inline virtual
Access to underlying std::ostream.
Reimplemented in OFstream.
Definition at line 178 of file OSstream.H.
Referenced by OStringStream::rewind(), OStringStream::str(), and OStringStream::~OStringStream().
stdStream() [2/2]
virtual const ostream& stdStream () const inline virtual
Const access to underlying std::ostream.
Reimplemented in OFstream.
Definition at line 184 of file OSstream.H.
References OSstream::print().
print()
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from IOstream.
Reimplemented in prefixOSstream, OFstream, and OStringStream.
Definition at line 43 of file SstreamsPrint.C.
References ISstream::name(), and IOstream::print().
Referenced by OStringStream::print(), OFstream::print(), prefixOSstream::print(), and OSstream::stdStream().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Sstreams/OSstream.H
src/OpenFOAM/db/IOstreams/Sstreams/OSstream.C
src/OpenFOAM/db/IOstreams/Sstreams/OSstreamI.H
src/OpenFOAM/db/IOstreams/Sstreams/SstreamsPrint.C