OpenFOAM: PstreamBuffers Class Reference
PstreamBuffers Class Reference
Buffers for inter-processor communications streams (UOPstream, UIPstream).
Public Member Functions
PstreamBuffers (const UPstream::commsTypes commsType, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, IOstream::streamFormat format=IOstream::BINARY, IOstream::versionNumber version=IOstream::currentVersion)
Construct given comms type,.
~PstreamBuffers ()
Destructor.
int tag () const
void finishedSends (const bool block=true)
Mark all sends as having been done. This will start receives.
void finishedSends (labelList &recvSizes, const bool block=true)
Mark all sends as having been done. Same as above but also returns.
void clear ()
Clear storage and reset.
Static Public Attributes
static DynamicList< char > nullBuf
Friends
class UOPstream
class UIPstream
Detailed Description
Buffers for inter-processor communications streams (UOPstream, UIPstream).
Use UOPstream to stream data into buffers, call finishedSends() to notify that data is in buffers and then use IUPstream to get data out of received buffers. Works with both blocking and nonBlocking. Does not make much sense with scheduled since there you would not need these explicit buffers.
Example usage:
PstreamBuffers pBuffers(Pstream::nonBlocking);
for (label proci = 0; proci < Pstream::nProcs(); proci++) { if (proci != Pstream::myProcNo()) { someObject vals;
UOPstream str(proci, pBuffers); str << vals; } }
pBuffers.finishedSends(); // no-op for blocking
for (label proci = 0; proci < Pstream::nProcs(); proci++) { if (proci != Pstream::myProcNo()) { UIPstream str(proci, pBuffers); someObject vals(str); } }
Source files
PstreamBuffers.H
PstreamBuffers.C
Definition at line 85 of file PstreamBuffers.H.
Constructor & Destructor Documentation
PstreamBuffers()
PstreamBuffers (const UPstream::commsTypes commsType, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, IOstream::streamFormat format = IOstream::BINARY, IOstream::versionNumber version = IOstream::currentVersion)
Construct given comms type,.
write format and IO version
Definition at line 40 of file PstreamBuffers.C.
~PstreamBuffers()
~PstreamBuffers ()
Destructor.
Definition at line 62 of file PstreamBuffers.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and forAll.
Member Function Documentation
tag()
int tag () const inline
Definition at line 140 of file PstreamBuffers.H.
References PstreamBuffers::clear(), and PstreamBuffers::finishedSends().
finishedSends() [1/2]
void finishedSends (const bool block = true)
Mark all sends as having been done. This will start receives.
in non-blocking mode. If block will wait for all transfers to finish (only relevant for nonBlocking mode)
Definition at line 82 of file PstreamBuffers.C.
References UPstream::nonBlocking.
Referenced by polyBoundaryMesh::clearAddressing(), PointEdgeWave< Type, TrackingData >::countPatchType(), fvMeshDistribute::distribute(), mapDistributeBase::distribute(), pointBoundaryMesh::findIndices(), FaceCellWave< Type, TrackingData >::handleProcPatches(), pointBoundaryMesh::movePoints(), polyBoundaryMesh::movePoints(), minEqOp< labelPair >::operator()(), mapDistributeBase::send(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncPointMap(), PstreamBuffers::tag(), pointBoundaryMesh::updateMesh(), and polyBoundaryMesh::updateMesh().
finishedSends() [2/2]
void finishedSends (labelList & recvSizes, const bool block = true)
Mark all sends as having been done. Same as above but also returns.
sizes (bytes) received. Note:currently only valid for non-blocking.
Definition at line 100 of file PstreamBuffers.C.
References UPstream::commsTypeNames, Foam::endl(), Pstream::exchangeSizes(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UPstream::nonBlocking.
clear()
void clear ()
Clear storage and reset.
Definition at line 132 of file PstreamBuffers.C.
References forAll.
Referenced by PstreamBuffers::tag().
Friends And Related Function Documentation
UOPstream
friend class UOPstream friend
Definition at line 87 of file PstreamBuffers.H.
UIPstream
friend class UIPstream friend
Definition at line 88 of file PstreamBuffers.H.
Member Data Documentation
nullBuf
DynamicList< char > nullBuf static
Definition at line 118 of file PstreamBuffers.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/PstreamBuffers.H
src/OpenFOAM/db/IOstreams/Pstreams/PstreamBuffers.C