OpenFOAM: TimePaths Class Reference
TimePaths Class Reference
A class for addressing time paths without using the Time class.
Public Member Functions
TimePaths (const fileName &rootPath, const fileName &caseName, const word &systemName, const word &constantName)
Construct given database name, rootPath and casePath.
TimePaths (const bool processorCase, const fileName &rootPath, const fileName &globalCaseName, const fileName &caseName, const word &systemName, const word &constantName)
Construct given database name, rootPath and casePath.
bool processorCase () const
Return true if this is a processor case.
const fileName & rootPath () const
Return root path.
const fileName & globalCaseName () const
Return global case name.
const fileName & caseName () const
Return case name.
const word & system () const
Return system name.
fileName caseSystem () const
Return system name for the case.
const word & constant () const
Return constant name.
fileName caseConstant () const
Return constant name for the case.
fileName path () const
Return path.
fileName systemPath () const
Return system path.
fileName constantPath () const
Return constant path.
Detailed Description
A class for addressing time paths without using the Time class.
Source files
TimePaths.H
TimePaths.C
Definition at line 49 of file TimePaths.H.
Constructor & Destructor Documentation
TimePaths() [1/2]
TimePaths (const fileName & rootPath, const fileName & caseName, const word & systemName, const word & constantName)
Construct given database name, rootPath and casePath.
Definition at line 32 of file TimePaths.C.
References Foam::pos().
TimePaths() [2/2]
TimePaths (const bool processorCase, const fileName & rootPath, const fileName & globalCaseName, const fileName & caseName, const word & systemName, const word & constantName)
Construct given database name, rootPath and casePath.
Definition at line 68 of file TimePaths.C.
References Foam::pos().
Member Function Documentation
processorCase()
bool processorCase () const inline
Return true if this is a processor case.
Definition at line 90 of file TimePaths.H.
rootPath()
const fileName& rootPath () const inline
Return root path.
Definition at line 96 of file TimePaths.H.
Referenced by TimePaths::path(), and Time::rootPath().
globalCaseName()
const fileName& globalCaseName () const inline
Return global case name.
Definition at line 102 of file TimePaths.H.
caseName()
const fileName& caseName () const inline
Return case name.
Definition at line 108 of file TimePaths.H.
Referenced by Time::caseName(), and TimePaths::path().
system()
const word& system () const inline
Return system name.
Definition at line 114 of file TimePaths.H.
References TimePaths::caseSystem().
Referenced by TimePaths::caseSystem(), TimePaths::systemPath(), and meshRefinement::write().
caseSystem()
Foam::fileName caseSystem () const
Return system name for the case.
which for parallel runs returns ../system()
Definition at line 110 of file TimePaths.C.
References TimePaths::system().
Referenced by TimePaths::system(), and meshRefinement::write().
constant()
const word& constant () const inline
Return constant name.
Definition at line 124 of file TimePaths.H.
References TimePaths::caseConstant().
Referenced by basicMultiComponentMixture::basicMultiComponentMixture(), TimePaths::caseConstant(), componentDisplacementMotionSolver::componentDisplacementMotionSolver(), TimePaths::constantPath(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), edgeMeshFormatsCore::getLineNoComment(), surfaceFormatsCore::getLineNoComment(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), meshReader::mesh(), basicChemistryModel::New(), motionSolver::New(), basicSolidChemistryModel::New(), psiCombustionModel::New(), rhoCombustionModel::New(), engineMesh::New(), chemistryTabulationMethod< CompType, ThermoType >::New(), coordinateSystems::New(), dynamicFvMesh::New(), laminarFlameSpeed::New(), chemistryReductionMethod< CompType, ThermoType >::New(), surfaceFilmModel::New(), SRFModel::New(), laminarModel< BasicTurbulenceModel >::New(), basicThermo::New(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::New(), thermalBaffleModel::New(), LESModel< BasicTurbulenceModel >::New(), pyrolysisModel::New(), radiationModel::New(), pyrolysisModelCollection::pyrolysisModelCollection(), timeSelector::select0(), regionCoupledBase::surfPtr(), mappedPatchBase::surfPtr(), triSurfaceMeshPointSet::triSurfaceMeshPointSet(), triSurface::triSurfInstance(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), meshReader::warnDuplicates(), STARCD::write(), and meshRefinement::write().
caseConstant()
Foam::fileName caseConstant () const
Return constant name for the case.
which for parallel runs returns ../constant()
Definition at line 123 of file TimePaths.C.
References TimePaths::constant().
Referenced by TimePaths::constant(), and meshRefinement::write().
path()
fileName path () const inline
Return path.
Definition at line 134 of file TimePaths.H.
References TimePaths::caseName(), and TimePaths::rootPath().
Referenced by TimePaths::constantPath(), and TimePaths::systemPath().
systemPath()
fileName systemPath () const inline
Return system path.
Definition at line 140 of file TimePaths.H.
References TimePaths::path(), and TimePaths::system().
constantPath()
fileName constantPath () const inline
Return constant path.
Definition at line 146 of file TimePaths.H.
References TimePaths::constant(), and TimePaths::path().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/TimePaths.H
src/OpenFOAM/db/Time/TimePaths.C