OpenFOAM: token::compound Class Reference
token::compound Class Reference abstract
Abstract base class for complex tokens.
Public Member Functions
TypeName ("compound")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, compound, Istream,(Istream &is),(is))
Declare run-time constructor selection table.
compound ()
Construct null.
virtual ~compound ()
Destructor.
bool empty () const
bool & empty ()
virtual label size () const =0
virtual void write (Ostream &) const =0
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Static Public Member Functions
static autoPtr< compound > New (const word &type, Istream &)
Select null constructed.
static bool isCompound (const word &name)
Return true if name is a compound type.
Friends
Ostream & operator<< (Ostream &, const compound &)
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Detailed Description
Abstract base class for complex tokens.
Definition at line 124 of file token.H.
Constructor & Destructor Documentation
compound()
compound () inline
Construct null.
Definition at line 162 of file token.H.
References token::compound::isCompound(), Foam::name(), token::compound::New(), token::type(), and token::compound::~compound().
~compound()
~compound () virtual
Destructor.
Definition at line 53 of file token.C.
References token::compound::New().
Referenced by token::compound::compound().
Member Function Documentation
TypeName()
TypeName ("compound")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , compound , Istream , (Istream &is) , (is))
Declare run-time constructor selection table.
New()
Foam::autoPtr< Foam::token::compound > New (const word & type, Istream & is) static
Select null constructed.
Definition at line 60 of file token.C.
References Foam::abort(), Foam::endl(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
Referenced by token::compound::compound(), UIPstream::read(), and token::compound::~compound().
isCompound()
bool isCompound (const word & name) static
Return true if name is a compound type.
Definition at line 83 of file token.C.
Referenced by token::compound::compound(), and UIPstream::read().
empty() [1/2]
bool empty () const inline
Definition at line 185 of file token.H.
Referenced by Foam::operator<<().
empty() [2/2]
bool& empty () inline
Definition at line 190 of file token.H.
References token::compound::operator<<, token::compound::size(), and token::compound::write().
size()
virtual label size () const pure virtual
Implemented in token::Compound< T >.
Referenced by token::compound::empty().
write()
virtual void write (Ostream &) const pure virtual
Implemented in token::Compound< T >.
Referenced by token::compound::empty(), and Foam::operator<<().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const compound &) friend
Referenced by token::compound::empty().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/token/token.H
src/OpenFOAM/db/IOstreams/token/token.C