OpenFOAM: dimensionSet Class Reference
dimensionSet Class Reference
Dimension set for the base types.
Public Types
enum { nDimensions = 7 }
enum dimensionType {
MASS, LENGTH, TIME, TEMPERATURE,
MOLES, CURRENT, LUMINOUS_INTENSITY
}
Define an enumeration for the names of the dimension exponents.
Public Member Functions
ClassName ("dimensionSet")
dimensionSet (const scalar mass, const scalar length, const scalar time, const scalar temperature, const scalar moles, const scalar current, const scalar luminousIntensity)
Construct given individual dimension exponents for all.
dimensionSet (const scalar mass, const scalar length, const scalar time, const scalar temperature, const scalar moles)
Construct given individual dimension exponents for first.
dimensionSet (const dimensionSet &ds)
Copy constructor.
autoPtr< dimensionSet > clone () const
Construct and return a clone.
dimensionSet (Istream &)
Construct from Istream.
bool dimensionless () const
Return true if it is dimensionless.
void reset (const dimensionSet &)
Istream & read (Istream &is, scalar &multiplier, const dictionary &)
Read using provided units. Used only in initial parsing.
Istream & read (Istream &is, scalar &multiplier, const HashTable< dimensionedScalar > &)
Read using provided units.
Istream & read (Istream &is, scalar &multiplier)
Read using system units.
Ostream & write (Ostream &os, scalar &multiplier, const dimensionSets &) const
Write using provided units.
Ostream & write (Ostream &os, scalar &multiplier) const
Write using system units.
scalar operator[] (const dimensionType) const
scalar & operator[] (const dimensionType)
scalar operator[] (const label) const
scalar & operator[] (const label)
bool operator== (const dimensionSet &) const
bool operator!= (const dimensionSet &) const
bool operator= (const dimensionSet &) const
bool operator+= (const dimensionSet &) const
bool operator-= (const dimensionSet &) const
bool operator*= (const dimensionSet &)
bool operator/= (const dimensionSet &)
Static Public Attributes
static const scalar smallExponent = SMALL
Friends
dimensionSet max (const dimensionSet &, const dimensionSet &)
dimensionSet min (const dimensionSet &, const dimensionSet &)
dimensionSet cmptMultiply (const dimensionSet &, const dimensionSet &)
dimensionSet cmptDivide (const dimensionSet &, const dimensionSet &)
dimensionSet pow (const dimensionSet &, const scalar)
dimensionSet pow (const dimensionSet &, const dimensionedScalar &)
dimensionSet pow (const dimensionedScalar &, const dimensionSet &)
dimensionSet sqr (const dimensionSet &)
dimensionSet pow3 (const dimensionSet &)
dimensionSet pow4 (const dimensionSet &)
dimensionSet pow5 (const dimensionSet &)
dimensionSet pow6 (const dimensionSet &)
dimensionSet pow025 (const dimensionSet &)
dimensionSet sqrt (const dimensionSet &)
dimensionSet magSqr (const dimensionSet &)
dimensionSet mag (const dimensionSet &)
dimensionSet sign (const dimensionSet &)
dimensionSet pos (const dimensionSet &)
dimensionSet neg (const dimensionSet &)
dimensionSet inv (const dimensionSet &)
dimensionSet trans (const dimensionSet &)
Function to check the argument is dimensionless.
dimensionSet atan2 (const dimensionSet &, const dimensionSet &)
dimensionSet transform (const dimensionSet &)
Return the argument; transformations do not change the dimensions.
dimensionSet operator- (const dimensionSet &)
dimensionSet operator+ (const dimensionSet &, const dimensionSet &)
dimensionSet operator- (const dimensionSet &, const dimensionSet &)
dimensionSet operator* (const dimensionSet &, const dimensionSet &)
dimensionSet operator/ (const dimensionSet &, const dimensionSet &)
dimensionSet operator & (const dimensionSet &, const dimensionSet &)
dimensionSet operator^ (const dimensionSet &, const dimensionSet &)
dimensionSet operator && (const dimensionSet &, const dimensionSet &)
Istream & operator>> (Istream &, dimensionSet &)
Ostream & operator<< (Ostream &, const dimensionSet &)
Detailed Description
Dimension set for the base types.
This type may be used to implement rigorous dimension checking for algebraic manipulation.
Source files
dimensionSet.H
dimensionSet.C
dimensionSetIO.C
dimensionSets.C
Definition at line 118 of file dimensionSet.H.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
nDimensions
Definition at line 125 of file dimensionSet.H.
dimensionType
enum dimensionType
Define an enumeration for the names of the dimension exponents.
Enumerator
MASS
LENGTH
TIME
TEMPERATURE
MOLES
CURRENT
LUMINOUS_INTENSITY
Definition at line 131 of file dimensionSet.H.
Constructor & Destructor Documentation
dimensionSet() [1/4]
dimensionSet (const scalar mass, const scalar length, const scalar time, const scalar temperature, const scalar moles, const scalar current, const scalar luminousIntensity)
Construct given individual dimension exponents for all.
seven dimensions
Definition at line 42 of file dimensionSet.C.
Referenced by dimensionSet::clone().
dimensionSet() [2/4]
dimensionSet (const scalar mass, const scalar length, const scalar time, const scalar temperature, const scalar moles)
Construct given individual dimension exponents for first.
five dimensions
Definition at line 63 of file dimensionSet.C.
dimensionSet() [3/4]
dimensionSet (const dimensionSet & ds)
Copy constructor.
Definition at line 81 of file dimensionSet.C.
dimensionSet() [4/4]
dimensionSet (Istream & is)
Construct from Istream.
Definition at line 33 of file dimensionSetIO.C.
References token::BEGIN_LIST, token::BEGIN_SQR, Foam::constant::universal::c, dimensioned< Type >::dimensions(), Foam::dimless, token::DIVIDE, token::END_LIST, token::END_SQR, Foam::exit(), Foam::exp(), Foam::FatalIOError, FatalIOErrorInFunction, token::good(), token::isPunctuation(), Foam::isspace(), token::isWord(), dimensionSet::mag, token::MULTIPLY, dimensionSet::nDimensions, Foam::pow(), dimensionSet::pow, token::pToken(), dimensionSet::read(), Foam::readScalar(), dimensionSet::reset(), dimensionSet::smallExponent, token::SPACE, token::SUBTRACT, dimensioned< Type >::value(), and token::wordToken().
Member Function Documentation
ClassName()
ClassName ("dimensionSet")
clone()
autoPtr<dimensionSet> clone () const inline
Construct and return a clone.
Definition at line 255 of file dimensionSet.H.
References dimensionSet::atan2, dimensionSet::cmptDivide, dimensionSet::cmptMultiply, dimensionSet::dimensionless(), dimensionSet::dimensionSet(), dimensionSet::inv, dimensionSet::mag, dimensionSet::magSqr, dimensionSet::max, dimensionSet::min, dimensionSet::neg, dimensionSet::operator!=(), dimensionSet::operator*=(), dimensionSet::operator+=(), dimensionSet::operator-, dimensionSet::operator-=(), dimensionSet::operator/=(), dimensionSet::operator<<, dimensionSet::operator=(), dimensionSet::operator==(), dimensionSet::operator>>, dimensionSet::operator[](), dimensionSet::pos, dimensionSet::pow, dimensionSet::pow025, dimensionSet::pow3, dimensionSet::pow4, dimensionSet::pow5, dimensionSet::pow6, dimensionSet::read(), dimensionSet::reset(), dimensionSet::sign, dimensionSet::sqr, dimensionSet::sqrt, dimensionSet::trans, dimensionSet::transform, and dimensionSet::write().
dimensionless()
bool dimensionless () const
Return true if it is dimensionless.
Definition at line 89 of file dimensionSet.C.
Referenced by dimensionSet::clone(), Foam::pow(), and Foam::trans().
reset()
void reset (const dimensionSet & ds)
Definition at line 108 of file dimensionSet.C.
Referenced by wallShearStress::calcShearStress(), dimensionSet::clone(), dimensionSet::dimensionSet(), Foam::New(), and dimensionSet::read().
read() [1/3]
Foam::Istream & read (Istream & is, scalar & multiplier, const dictionary & readSet)
Read using provided units. Used only in initial parsing.
Definition at line 498 of file dimensionSetIO.C.
References token::BEGIN_SQR, IOstream::check(), dimensionSet::CURRENT, dimensioned< Type >::dimensions(), Foam::dimless, token::END_SQR, Foam::endl(), Foam::exit(), Foam::exp(), Foam::FatalIOError, FatalIOErrorInFunction, IOstream::info(), token::isNumber(), token::isWord(), dimensionSet::LUMINOUS_INTENSITY, dimensionSet::MASS, dimensionSet::nDimensions, token::number(), Foam::pow(), dimensionSet::pow, dimensioned< Type >::read(), Foam::readScalar(), dimensionSet::reset(), s(), dimensionSet::smallExponent, dimensioned< Type >::value(), token::wordToken(), and dimensionSet::write().
Referenced by dimensionSet::clone(), dimensionSet::dimensionSet(), Foam::operator>>(), and dimensionSet::read().
read() [2/3]
Foam::Istream & read (Istream & is, scalar & multiplier, const HashTable< dimensionedScalar > & readSet)
Read using provided units.
Definition at line 403 of file dimensionSetIO.C.
References token::BEGIN_SQR, IOstream::check(), dimensionSet::CURRENT, dimensioned< Type >::dimensions(), token::END_SQR, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOstream::info(), token::isNumber(), dimensionSet::LUMINOUS_INTENSITY, dimensionSet::MASS, dimensionSet::nDimensions, token::number(), Istream::putBack(), dimensionSet::read(), and dimensioned< Type >::value().
read() [3/3]
Foam::Istream & read (Istream & is, scalar & multiplier)
Read using system units.
Definition at line 488 of file dimensionSetIO.C.
References dimensionSet::read(), and Foam::unitSet().
write() [1/2]
Foam::Ostream & write (Ostream & os, scalar & multiplier, const dimensionSets & writeUnits) const
Write using provided units.
Definition at line 628 of file dimensionSetIO.C.
References IOstream::ASCII, token::BEGIN_SQR, IOstream::check(), dimensionSets::coefficients(), token::END_SQR, forAll, IOstream::format(), dimensionSet::mag, dimensioned< Type >::name(), dimensionSet::nDimensions, Foam::pow(), Ostream::precision(), dimensionSet::smallExponent, token::SPACE, dimensionSets::units(), dimensionSets::valid(), and dimensioned< Type >::value().
Referenced by dimensionSet::clone(), Foam::operator<<(), dimensionSet::read(), and dimensionSet::write().
write() [2/2]
Foam::Ostream & write (Ostream & os, scalar & multiplier) const
Write using system units.
Definition at line 702 of file dimensionSetIO.C.
References dimensionSet::write(), and Foam::writeUnitSet().
operator[]() [1/4]
Foam::scalar operator[] (const dimensionType type) const
Definition at line 119 of file dimensionSet.C.
References Foam::type().
Referenced by dimensionSet::clone().
operator[]() [2/4]
Foam::scalar & operator[] (const dimensionType type)
Definition at line 125 of file dimensionSet.C.
References Foam::type().
operator[]() [3/4]
Foam::scalar operator[] (const label type) const
Definition at line 131 of file dimensionSet.C.
References Foam::type().
operator[]() [4/4]
Foam::scalar & operator[] (const label type)
Definition at line 137 of file dimensionSet.C.
References Foam::type().
operator==()
bool operator== (const dimensionSet & ds) const
Definition at line 143 of file dimensionSet.C.
References Foam::mag().
Referenced by dimensionSet::clone().
operator!=()
bool operator!= (const dimensionSet & ds) const
Definition at line 161 of file dimensionSet.C.
References Foam::operator==().
Referenced by dimensionSet::clone().
operator=()
bool operator= (const dimensionSet & ds) const
Definition at line 167 of file dimensionSet.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
Referenced by dimensionSet::clone().
operator+=()
bool operator+= (const dimensionSet & ds) const
Definition at line 181 of file dimensionSet.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
Referenced by dimensionSet::clone().
operator-=()
bool operator-= (const dimensionSet & ds) const
Definition at line 195 of file dimensionSet.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
Referenced by dimensionSet::clone().
operator*=()
bool operator*= (const dimensionSet & ds)
Definition at line 209 of file dimensionSet.C.
Referenced by dimensionSet::clone().
operator/=()
bool operator/= (const dimensionSet & ds)
Definition at line 217 of file dimensionSet.C.
Referenced by dimensionSet::clone().
Friends And Related Function Documentation
max
dimensionSet max (const dimensionSet & , const dimensionSet &) friend
Referenced by dimensionSet::clone().
min
dimensionSet min (const dimensionSet & , const dimensionSet &) friend
Referenced by dimensionSet::clone().
cmptMultiply
dimensionSet cmptMultiply (const dimensionSet & , const dimensionSet &) friend
Referenced by dimensionSet::clone().
cmptDivide
dimensionSet cmptDivide (const dimensionSet & , const dimensionSet &) friend
Referenced by dimensionSet::clone().
pow [1/3]
dimensionSet pow (const dimensionSet & , const scalar) friend
Referenced by dimensionSet::clone(), dimensionSet::dimensionSet(), and dimensionSet::read().
pow [2/3]
dimensionSet pow (const dimensionSet & , const dimensionedScalar &) friend
pow [3/3]
dimensionSet pow (const dimensionedScalar & , const dimensionSet &) friend
sqr
dimensionSet sqr (const dimensionSet &) friend
Referenced by dimensionSet::clone().
pow3
dimensionSet pow3 (const dimensionSet &) friend
Referenced by dimensionSet::clone().
pow4
dimensionSet pow4 (const dimensionSet &) friend
Referenced by dimensionSet::clone().
pow5
dimensionSet pow5 (const dimensionSet &) friend
Referenced by dimensionSet::clone().
pow6
dimensionSet pow6 (const dimensionSet &) friend
Referenced by dimensionSet::clone().
pow025
dimensionSet pow025 (const dimensionSet &) friend
Referenced by dimensionSet::clone().
sqrt
dimensionSet sqrt (const dimensionSet &) friend
Referenced by dimensionSet::clone().
magSqr
dimensionSet magSqr (const dimensionSet &) friend
Referenced by dimensionSet::clone().
mag
dimensionSet mag (const dimensionSet &) friend
Referenced by dimensionSet::clone(), dimensionSet::dimensionSet(), Foam::operator>>(), and dimensionSet::write().
sign
dimensionSet sign (const dimensionSet &) friend
Referenced by dimensionSet::clone().
pos
dimensionSet pos (const dimensionSet &) friend
Referenced by dimensionSet::clone().
neg
dimensionSet neg (const dimensionSet &) friend
Referenced by dimensionSet::clone().
inv
dimensionSet inv (const dimensionSet &) friend
Referenced by dimensionSet::clone().
trans
dimensionSet trans (const dimensionSet &) friend
Function to check the argument is dimensionless.
for transcendental functions
Referenced by dimensionSet::clone().
atan2
dimensionSet atan2 (const dimensionSet & , const dimensionSet &) friend
Referenced by dimensionSet::clone().
transform
dimensionSet transform (const dimensionSet &) friend
Return the argument; transformations do not change the dimensions.
Referenced by dimensionSet::clone().
operator- [1/2]
dimensionSet operator- (const dimensionSet &) friend
Referenced by dimensionSet::clone().
operator+
dimensionSet operator+ (const dimensionSet & , const dimensionSet &) friend
operator- [2/2]
dimensionSet operator- (const dimensionSet & , const dimensionSet &) friend
operator*
dimensionSet operator* (const dimensionSet & , const dimensionSet &) friend
operator/
dimensionSet operator/ (const dimensionSet & , const dimensionSet &) friend
operator &
dimensionSet operator& (const dimensionSet & , const dimensionSet &) friend
operator^
dimensionSet operator^ (const dimensionSet & , const dimensionSet &) friend
operator &&
dimensionSet operator&& (const dimensionSet & , const dimensionSet &) friend
operator>>
Istream& operator>> (Istream & , dimensionSet &) friend
Referenced by dimensionSet::clone().
operator<<
Ostream& operator<< (Ostream & , const dimensionSet &) friend
Referenced by dimensionSet::clone().
Member Data Documentation
smallExponent
const scalar smallExponent = SMALL static
Definition at line 145 of file dimensionSet.H.
Referenced by dimensionSet::dimensionSet(), Foam::operator>>(), dimensionSet::read(), and dimensionSet::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/dimensionSet/dimensionSet.H
src/OpenFOAM/dimensionSet/dimensionSet.C
src/OpenFOAM/dimensionSet/dimensionSetIO.C