OpenFOAM: objectRegistry Class Reference
objectRegistry Class Reference
Registry of regIOobjects.
Public Member Functions
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write the objects.
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject *>
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< word, regIOobject * >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Foam::label erase (const HashTable< AnyType, word, AnyHash > &rhs)
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< word, regIOobject * >>)
Assignment to an initializer list.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject *>
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Registry of regIOobjects.
Source files
objectRegistry.H
objectRegistry.C
Definition at line 50 of file objectRegistry.H.
Constructor & Destructor Documentation
objectRegistry() [1/2]
objectRegistry (const Time & db, const label nIoObjects = 128) explicit
Construct the time objectRegistry given an initial estimate.
for the number of entries
Definition at line 48 of file objectRegistry.C.
objectRegistry() [2/2]
objectRegistry (const IOobject & io, const label nIoObjects = 128) explicit
Construct a sub-registry given an IObject to describe the registry.
and an initial estimate for the number of entries
Definition at line 75 of file objectRegistry.C.
References IOobject::AUTO_WRITE.
~objectRegistry()
~objectRegistry () virtual
Destructor.
Definition at line 93 of file objectRegistry.C.
Member Function Documentation
TypeName()
TypeName ("objectRegistry")
Declare type name for this IOobject.
time()
const Time& time () const inline
Return time.
Definition at line 117 of file objectRegistry.H.
Referenced by fieldAverage::addMeanFieldType(), fieldAverage::addPrime2MeanFieldType(), writeFile::baseFileDir(), writeFile::baseTimeDir(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), layerAdditionRemoval::changeTopology(), componentDisplacementMotionSolver::componentDisplacementMotionSolver(), logFiles::createFiles(), particle< Type >::currentTime(), displacementInterpolationMotionSolver::displacementInterpolationMotionSolver(), moleculeCloud::evolve(), coupleGroupIdentifier::findOtherPatchID(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), IOobjectList::IOobjectList(), meshRefinement::makeDisplacementField(), Foam::MapLagrangianFields(), Foam::MapMesh(), meshReader::mesh(), polyMesh::movePoints(), regionCoupledBase::neighbPatch(), regionCoupledBase::neighbPatchID(), motionSolver::New(), chemistryTabulationMethod< CompType, ThermoType >::New(), coordinateSystems::New(), chemistryReductionMethod< CompType, ThermoType >::New(), GAMGAgglomeration::New(), polyMesh::oldPoints(), surfaceFieldValue::outputDir(), polyMesh::polyMesh(), Foam::polyMeshZipUpCells(), surfMesh::readUpdate(), polyMesh::readUpdate(), polyMesh::removeFiles(), polyMesh::resetPrimitives(), mappedPatchBase::sampleMesh(), triSurfaceMesh::setField(), duplicatePoints::setRefinement(), rigidBodyMeshMotionSolver::solve(), regionCoupledBase::surfPtr(), mappedPatchBase::surfPtr(), fvMesh::time(), IOobject::time(), triSurfaceMeshPointSet::triSurfaceMeshPointSet(), polyTopoChanger::update(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), oscillatingDisplacementPointPatchVectorField::updateCoeffs(), waveDisplacementPointPatchVectorField::updateCoeffs(), oscillatingVelocityPointPatchVectorField::updateCoeffs(), angularOscillatingDisplacementPointPatchVectorField::updateCoeffs(), angularOscillatingVelocityPointPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), surfaceDisplacementPointPatchVectorField::updateCoeffs(), polyMesh::updateMesh(), meshReader::warnDuplicates(), STARCD::write(), streamLine::write(), wallBoundedStreamLine::write(), molecule::writeFields(), writeFile::writeTime(), and CloudFunctionObject< CloudType >::writeTimeDir().
parent()
const objectRegistry& parent () const inline
Return the parent objectRegistry.
Definition at line 123 of file objectRegistry.H.
Referenced by polyMesh::dbDir().
dbDir()
virtual const fileName& dbDir () const inline virtual
Local directory path of this objectRegistry relative to the time.
Reimplemented in polyMesh, and Time.
Definition at line 129 of file objectRegistry.H.
References regIOobject::checkIn(), regIOobject::checkOut(), objectRegistry::foundObject(), objectRegistry::getEvent(), objectRegistry::lookupClass(), objectRegistry::lookupObject(), objectRegistry::modified(), IOobject::name(), objectRegistry::names(), NotImplemented, objectRegistry::readIfModified(), objectRegistry::readModifiedObjects(), objectRegistry::rename(), objectRegistry::sortedNames(), objectRegistry::subRegistry(), objectRegistry::writeData(), and objectRegistry::writeObject().
Referenced by polyMesh::dbDir(), IOobjectList::IOobjectList(), surfMesh::meshDir(), surfMesh::surfMesh(), and IOobject::writeHeader().
names() [1/8]
Foam::wordList names () const
Return the list of names of the IOobjects.
Definition at line 115 of file objectRegistry.C.
References HashTable< T, Key, Hash >::toc().
Referenced by objectRegistry::dbDir(), fvMeshDistribute::distribute(), objectRegistry::names(), and vtkUnstructuredReader::printFieldStats().
sortedNames() [1/2]
Foam::wordList sortedNames () const
Return the sorted list of names of the IOobjects.
Definition at line 121 of file objectRegistry.C.
References HashTable< T, Key, Hash >::sortedToc().
Referenced by probes::classifyFields(), and objectRegistry::dbDir().
names() [2/8]
Foam::wordList names (const word & className) const
Return the list of names of IOobjects of given class name.
Definition at line 127 of file objectRegistry.C.
References ClassName, and List< T >::setSize().
sortedNames() [2/2]
Foam::wordList sortedNames (const word & className) const
Return the sorted list of names of IOobjects of given class name.
Definition at line 146 of file objectRegistry.C.
References Foam::sort(), and objectRegistry::subRegistry().
names() [3/8]
wordList names () const
Return the list of names of the IOobjects of given type.
names() [4/8]
wordList names (const wordRe & name) const
Return the list of objects whose name matches the input regExp.
names() [5/8]
wordList names (const wordReList & name) const
Return the list of objects whose name matches the input regExp.
subRegistry()
const Foam::objectRegistry & subRegistry (const word & name, const bool forceCreate = false) const
Lookup and return a const sub-objectRegistry. Optionally create.
it if it does not exist.
Definition at line 156 of file objectRegistry.C.
References Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, and regIOobject::store().
Referenced by objectRegistry::dbDir(), objectRegistry::sortedNames(), and uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs().
lookupClass() [1/4]
HashTable<const Type*> lookupClass (const bool strict = false) const
Lookup and return all objects of the given Type.
Referenced by meshObject::clear(), meshObject::clearUpto(), objectRegistry::dbDir(), coupleGroupIdentifier::findOtherPatchID(), objectRegistry::lookupClass(), basicThermo::lookupThermo(), meshObject::movePoints(), objectRegistry::names(), and meshObject::updateMesh().
lookupClass() [2/4]
HashTable<Type*> lookupClass (const bool strict = false)
Lookup and return all objects of the given Type.
foundObject()
bool foundObject (const word & name) const
Is the named Type found?
Definition at line 142 of file objectRegistryTemplates.C.
References HashTable< regIOobject *>::const_iterator, HashTableCore::end(), HashTable< regIOobject *>::find(), objectRegistry::foundObject(), and IOobject::name().
Referenced by refinementHistoryConstraint::add(), fieldAverage::addMeanField(), fieldAverage::addMeanFieldType(), fieldAverage::addMeanSqrToPrime2MeanType(), fieldAverage::addPrime2MeanField(), fieldAverage::addPrime2MeanFieldType(), refinementHistoryConstraint::apply(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), objectRegistry::dbDir(), DispersionRASModel< CloudType >::epsilonModel(), objectRegistry::foundObject(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), liquidFilmThermo::initLiquid(), temperatureCoupledBase::kappa(), DispersionRASModel< CloudType >::kModel(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), basicThermo::lookupThermo(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), options::New(), coordinateSystems::New(), GAMGAgglomeration::New(), VTKsurfaceFormat< Face >::read(), regionModel::regionMesh(), tabulatedAccelerationSource::tabulatedAccelerationSource(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), triSurfaceMeshPointSet::triSurfaceMeshPointSet(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), fieldAverage::writeFieldType(), residuals::writeFileHeader(), and residuals::writeResidual().
lookupObject()
const Type & lookupObject (const word & name) const
Lookup and return the object of the given Type.
Definition at line 165 of file objectRegistryTemplates.C.
References Foam::abort(), HashTable< regIOobject *>::const_iterator, HashTableCore::end(), Foam::FatalError, FatalErrorInFunction, HashTable< regIOobject *>::find(), objectRegistry::lookupObject(), IOobject::name(), and Foam::nl.
Referenced by refinementHistoryConstraint::add(), fieldAverage::addMeanFieldType(), fieldAverage::addMeanSqrToPrime2MeanType(), fieldAverage::addPrime2MeanFieldType(), interRegionExplicitPorositySource::addSup(), interRegionHeatTransferModel::addSup(), refinementHistoryConstraint::apply(), Relaxation< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), Explicit< CloudType >::cacheFields(), Stochastic< CloudType >::calculate(), tabulatedHeatTransfer::calculateHtc(), variableHeatTransfer::calculateHtc(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), motionDirectionalDiffusivity::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), objectRegistry::dbDir(), DispersionRASModel< CloudType >::epsilonModel(), PatchFlowRateInjection< CloudType >::flowRate(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), interRegionExplicitPorositySource::initialise(), liquidFilmThermo::initLiquid(), temperatureCoupledBase::kappa(), DispersionRASModel< CloudType >::kModel(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), objectRegistry::lookupObject(), basicThermo::lookupThermo(), mappedVariableThicknessWallFvPatch::makeDeltaCoeffs(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), solidParticleCloud::move(), medialAxisMeshMover::move(), NamedEnum< directionType, 3 >::names(), regionCoupledBaseFvPatch::nbrFvMesh(), regionCoupledBaseGAMGInterface::nbrLduInterface(), regionCoupledBaseFvPatch::nbrMesh(), regionCoupledBase::neighbPatch(), regionCoupledBase::neighbPatchID(), options::New(), coordinateSystems::New(), GAMGAgglomeration::New(), ParticleTrap< CloudType >::preEvolve(), fvMeshDistribute::printFieldInfo(), vtkUnstructuredReader::printFieldStats(), VTKsurfaceFormat< Face >::read(), SmagorinskyZhang< BasicTurbulenceModel >::read(), NicenoKEqn< BasicTurbulenceModel >::read(), LaheyKEpsilon< BasicTurbulenceModel >::read(), kOmegaSSTSato< BasicTurbulenceModel >::read(), regionModel::regionMesh(), patchProbes::sample(), mappedPatchBase::sampleMesh(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaceWithGaps::searchableSurfaceWithGaps(), interRegionOption::setMapper(), interRegionHeatTransferModel::setNbrModel(), rigidBodyMeshMotionSolver::solve(), tabulatedAccelerationSource::tabulatedAccelerationSource(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), triSurfaceMeshPointSet::triSurfaceMeshPointSet(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), cloudInfo::write(), fieldAverage::writeFieldType(), and FSD< CombThermoType, ThermoType >::~FSD().
getEvent()
Foam::label getEvent () const
Return new event number.
Definition at line 180 of file objectRegistry.C.
References Foam::endl(), regIOobject::eventNo(), Foam::labelMax, Foam::nl, Foam::Pout, and WarningInFunction.
Referenced by objectRegistry::dbDir(), polyMesh::movePoints(), and regIOobject::setUpToDate().
rename()
void rename (const word & newName) virtual
Rename.
Reimplemented from regIOobject.
Definition at line 287 of file objectRegistry.C.
References regIOobject::rename(), and string::replace().
Referenced by objectRegistry::dbDir().
checkIn()
bool checkIn (regIOobject & io) const
Add an regIOobject to registry.
Definition at line 219 of file objectRegistry.C.
References Foam::endl(), HashTable< T, Key, Hash >::insert(), Foam::name(), IOobject::name(), and Foam::Pout.
Referenced by regIOobject::checkIn().
checkOut()
bool checkOut (regIOobject & io) const
Remove an regIOobject from registry.
Definition at line 233 of file objectRegistry.C.
References Foam::endl(), HashTable< T, Key, Hash >::erase(), HashTable< T, Key, Hash >::find(), Foam::name(), IOobject::name(), regIOobject::ownedByRegistry(), Foam::Pout, and WarningInFunction.
Referenced by regIOobject::checkOut(), meshObject::clear(), meshObject::clearUpto(), meshObject::movePoints(), and meshObject::updateMesh().
modified()
bool modified () const virtual
Return true if any of the object's files have been modified.
Reimplemented from regIOobject.
Definition at line 305 of file objectRegistry.C.
References forAllConstIter().
Referenced by objectRegistry::dbDir(), and Time::readModifiedObjects().
readModifiedObjects()
void readModifiedObjects ()
Read the objects that have been modified.
Definition at line 319 of file objectRegistry.C.
References Foam::endl(), Foam::name(), and Foam::Pout.
Referenced by objectRegistry::dbDir(), and Time::readModifiedObjects().
readIfModified()
bool readIfModified () virtual
Read object if modified.
Reimplemented from regIOobject.
Definition at line 335 of file objectRegistry.C.
References objectRegistry::writeObject().
Referenced by objectRegistry::dbDir().
writeData()
virtual bool writeData (Ostream &) const inline virtual
writeData function required by regIOobject but not used
for this class, write is used instead
Implements regIOobject.
Reimplemented in triSurfaceMesh.
Definition at line 213 of file objectRegistry.H.
Referenced by objectRegistry::dbDir().
writeObject()
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const virtual
Write the objects.
Reimplemented from regIOobject.
Reimplemented in distributedTriSurfaceMesh, Time, fvMesh, Cloud< ParticleType >, Cloud< Foam::passiveParticle >, Cloud< wallBoundedStreamLineParticle >, Cloud< findCellParticle >, Cloud< indexedParticle >, Cloud< basicKinematicCollidingParcel >, Cloud< typename Foam::DSMCCloud::parcelType >, Cloud< trackedParticle >, Cloud< ParcelType >, Cloud< Foam::molecule >, Cloud< solidParticle >, Cloud< parcelType >, Cloud< molecule >, Cloud< DSMCParcel< ParcelType > >, Cloud< passiveParticle >, Cloud< streamLineParticle >, triSurfaceMesh, and dynamicRefineFvMesh.
Definition at line 343 of file objectRegistry.C.
References Foam::endl(), forAllConstIter(), Foam::name(), and Foam::Pout.
Referenced by objectRegistry::dbDir(), objectRegistry::readIfModified(), meshReader::writeMesh(), fvMesh::writeObject(), and Time::writeObject().
names() [6/8]
Foam::wordList names () const
Definition at line 32 of file objectRegistryTemplates.C.
References forAllConstIter(), List< T >::setSize(), and HashTable< regIOobject *>::size().
names() [7/8]
Foam::wordList names (const wordRe & name) const
Definition at line 52 of file objectRegistryTemplates.C.
References forAllConstIter(), wordRe::match(), List< T >::setSize(), and HashTable< regIOobject *>::size().
names() [8/8]
Foam::wordList names (const wordReList & patterns) const
Definition at line 77 of file objectRegistryTemplates.C.
References Foam::findStrings(), objectRegistry::lookupClass(), and objectRegistry::names().
lookupClass() [3/4]
Foam::HashTable<const Type*> lookupClass (const bool strict) const
Definition at line 87 of file objectRegistryTemplates.C.
References forAllConstIter(), HashTable< T, Key, Hash >::insert(), objectRegistry::lookupClass(), IOobject::name(), and HashTable< regIOobject *>::size().
lookupClass() [4/4]
Foam::HashTable<Type*> lookupClass (const bool strict)
Definition at line 115 of file objectRegistryTemplates.C.
References forAllIter, HashTable< T, Key, Hash >::insert(), IOobject::name(), and HashTable< regIOobject *>::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/objectRegistry/objectRegistry.H
src/OpenFOAM/db/objectRegistry/objectRegistry.C
src/OpenFOAM/db/objectRegistry/objectRegistryTemplates.C