OpenFOAM: regIOobject Class Reference
regIOobject Class Reference abstract
regIOobject is an abstract class derived from IOobject to handle automatic object registration with the objectRegistry.
Inherits IOobject.
Inherited by AveragingMethod< Foam::Vector >, AveragingMethod< scalar >, CompactIOList< face, label >, DimensionedField< scalar, Foam::volMesh >, DimensionedField< scalar, triSurfacePointGeoMesh >, DimensionedField< Type, Foam::pointMesh >, DimensionedField< Type, Foam::surfaceMesh >, DimensionedField< Type, Foam::volMesh >, DimensionedField< vector, Foam::pointMesh >, AveragingMethod< Type >, CompactIOField< T, BaseType >, CompactIOList< T, BaseType >, DimensionedField< Type, GeoMesh >, dragModel, dragModel, extendedFeatureEdgeMesh, featureEdgeMesh, fieldDictionary, IOdictionary, IOField< Type >, IOList< T >, IOMap< T >, IOmapDistribute, IOPosition< CloudType >, IOPtrList< T >, meshObject, objectRegistry, PDRDragModel, polyBoundaryMesh, polyBoundaryMeshEntries, polyTopoChanger, porosityModel, refinementHistory, searchableSurface, SLGThermo, SubDimensionedField< Type, GeoMesh >, surfacePatchIOList, surfaceTensionModel, surfZoneIOList, topoSet, UniformDimensionedField< Type >, virtualMassModel, virtualMassModel, ZoneMesh< ZoneType, MeshType >, IOField< vector >, IOList< kinematicParcelInjectionData >, IOList< label >, IOList< labelList >, IOList< reactingMultiphaseParcelInjectionData >, IOList< reactingParcelInjectionData >, IOPtrList< coordinateSystem >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, ZoneMesh< cellZone, polyMesh >, ZoneMesh< faceZone, polyMesh >, and ZoneMesh< pointZone, polyMesh >.
Public Types
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Member Functions
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeData (Ostream &) const =0
Pure virtual writaData function.
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Protected Attributes
static bool masterOnlyReading = false
To flag master-only reading of objects.
Friends
class functionEntries::codeStream
Declare friendship with any classes that need access to.
Additional Inherited Members
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Detailed Description
regIOobject is an abstract class derived from IOobject to handle automatic object registration with the objectRegistry.
Source files
regIOobject.H
regIOobject.C
regIOobjectRead.C
regIOobjectWrite.C
Definition at line 60 of file regIOobject.H.
Member Enumeration Documentation
fileCheckTypes
enum fileCheckTypes
Types of communications.
Enumerator
timeStamp
timeStampMaster
inotify
inotifyMaster
Definition at line 68 of file regIOobject.H.
Constructor & Destructor Documentation
regIOobject() [1/5]
regIOobject (const IOobject & io, const bool isTime = false)
Construct from IOobject. Optional flag for if IOobject is the.
top level regIOobject.
Definition at line 119 of file regIOobject.C.
References regIOobject::checkIn(), and IOobject::registerObject().
Referenced by regIOobject::regIOobject().
regIOobject() [2/5]
regIOobject (const regIOobject & rio)
Construct as copy.
Definition at line 141 of file regIOobject.C.
regIOobject() [3/5]
regIOobject (const regIOobject & rio, bool registerCopy)
Construct as copy, transferring registry registration to copy.
if registerCopy is true
Definition at line 154 of file regIOobject.C.
References regIOobject::checkIn(), regIOobject::checkOut(), and regIOobject::regIOobject().
regIOobject() [4/5]
regIOobject (const word & newName, const regIOobject & rio, bool registerCopy)
Construct as copy with new name, transfering registry registration.
to copy as specified
Definition at line 172 of file regIOobject.C.
References regIOobject::checkIn(), and regIOobject::regIOobject().
regIOobject() [5/5]
regIOobject (const IOobject & io, const regIOobject & rio)
Construct as copy with new IO parameters.
Definition at line 193 of file regIOobject.C.
References regIOobject::checkIn(), and IOobject::registerObject().
~regIOobject()
~regIOobject () virtual
Destructor.
Definition at line 214 of file regIOobject.C.
References regIOobject::checkOut(), Foam::endl(), Foam::Info, IOobject::name(), IOobject::path(), and Foam::type().
Member Function Documentation
TypeName()
TypeName ("regIOobject")
Runtime type information.
checkIn()
bool checkIn ()
Add object to registry.
Definition at line 241 of file regIOobject.C.
References Foam::abort(), Time::addWatch(), objectRegistry::checkIn(), IOobject::db(), polyMesh::defaultRegion, Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, IOobject::filePath(), IOobject::MUST_READ_IF_MODIFIED, IOobject::name(), IOobject::objectPath(), IOobject::readOpt(), HashTable< T, Key, Hash >::sortedToc(), IOobject::time(), and WarningInFunction.
Referenced by objectRegistry::dbDir(), regIOobject::operator=(), regIOobject::regIOobject(), and regIOobject::rename().
checkOut()
bool checkOut ()
Remove object from registry.
Definition at line 302 of file regIOobject.C.
References objectRegistry::checkOut(), IOobject::db(), Time::removeWatch(), and IOobject::time().
Referenced by objectRegistry::dbDir(), regIOobject::operator=(), regIOobject::regIOobject(), regIOobject::rename(), and regIOobject::~regIOobject().
ownedByRegistry()
bool ownedByRegistry () const inline
Is this object owned by the registry?
Definition at line 28 of file regIOobjectI.H.
Referenced by objectRegistry::checkOut(), regionFunctionObject::clearObject(), and removeRegisteredObject::execute().
store() [1/3]
void store () inline
Transfer ownership of this object to its registry.
Definition at line 34 of file regIOobjectI.H.
Referenced by fieldAverage::addMeanFieldType(), fieldAverage::addPrime2MeanFieldType(), volPointInterpolation::interpolate(), basicThermo::lookupOrConstruct(), NamedEnum< directionType, 3 >::names(), options::New(), coordinateSystems::New(), objectRegistry::subRegistry(), and vtkUnstructuredReader::vtkUnstructuredReader().
store() [2/3]
Type & store (Type * tPtr) inline static
Transfer ownership of the given object pointer to its registry.
and return reference to object.
Definition at line 41 of file regIOobjectI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
store() [3/3]
Type & store (autoPtr< Type > & atPtr) inline static
Transfer ownership of the given object pointer to its registry.
and return reference to object.
Definition at line 57 of file regIOobjectI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and autoPtr< T >::ptr().
release()
void release () inline
Release ownership of this object from its registry.
Definition at line 74 of file regIOobjectI.H.
eventNo() [1/2]
Foam::label eventNo () const inline
Event number at last update.
Definition at line 80 of file regIOobjectI.H.
Referenced by fvMatrix< Type >::fvMatrix(), objectRegistry::getEvent(), polyMesh::movePoints(), polyMesh::setUpToDatePoints(), and regIOobject::upToDate().
eventNo() [2/2]
Foam::label & eventNo () inline
Event number at last update.
Definition at line 85 of file regIOobjectI.H.
upToDate() [1/4]
bool upToDate (const regIOobject & a) const
Return true if up-to-date with respect to given object.
otherwise false
Definition at line 320 of file regIOobject.C.
References regIOobject::eventNo().
Referenced by regIOobject::upToDate(), and polyMesh::upToDatePoints().
upToDate() [2/4]
bool upToDate (const regIOobject & a, const regIOobject & b) const
Return true if up-to-date with respect to given objects.
otherwise false
Definition at line 334 of file regIOobject.C.
References regIOobject::eventNo(), and regIOobject::upToDate().
upToDate() [3/4]
bool upToDate (const regIOobject & a, const regIOobject & b, const regIOobject & c) const
Return true if up-to-date with respect to given objects.
otherwise false
Definition at line 355 of file regIOobject.C.
References regIOobject::eventNo(), and regIOobject::upToDate().
upToDate() [4/4]
bool upToDate (const regIOobject & a, const regIOobject & b, const regIOobject & c, const regIOobject & d) const
Return true if up-to-date with respect to given objects.
otherwise false
Definition at line 378 of file regIOobject.C.
References regIOobject::eventNo().
setUpToDate()
void setUpToDate ()
Set up to date (obviously)
Definition at line 402 of file regIOobject.C.
References IOobject::db(), and objectRegistry::getEvent().
rename()
void rename (const word & newName) virtual
Rename.
Reimplemented from IOobject.
Reimplemented in objectRegistry.
Definition at line 408 of file regIOobject.C.
References regIOobject::checkIn(), regIOobject::checkOut(), IOobject::registerObject(), and IOobject::rename().
Referenced by heThermo< BasicSolidThermo, MixtureType >::alphaEff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::k(), heThermo< BasicSolidThermo, MixtureType >::kappa(), heThermo< BasicSolidThermo, MixtureType >::kappaEff(), Foam::New(), reuseTmpDimensionedField< TypeR, TypeR, GeoMesh >::New(), reuseTmpGeometricField< TypeR, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, Type1, Type12, TypeR, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, Type2, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, Type1, Type12, TypeR, PatchField, GeoMesh >::New(), reuseTmpTmpDimensionedField< TypeR, TypeR, TypeR, TypeR, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, Type2, PatchField, GeoMesh >::New(), reuseTmpTmpGeometricField< TypeR, TypeR, TypeR, TypeR, PatchField, GeoMesh >::New(), and objectRegistry::rename().
readStream()
Foam::Istream & readStream (const word & expectName)
Return Istream and check object type against that given.
Definition at line 110 of file regIOobjectRead.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOobject::headerClassName(), InfoInFunction, IOobject::name(), and IOobject::objectPath().
Referenced by extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), fieldDictionary::fieldDictionary(), IOMap< T >::IOMap(), IOmapDistribute::IOmapDistribute(), polyBoundaryMeshEntries::polyBoundaryMeshEntries(), refinementHistory::read(), IOPosition< CloudType >::readData(), refinementHistory::refinementHistory(), and topoSet::topoSet().
close()
void close ()
Close Istream.
Definition at line 147 of file regIOobjectRead.C.
References Foam::endl(), IOobject::filePath(), and InfoInFunction.
Referenced by extendedFeatureEdgeMesh::extendedFeatureEdgeMesh(), featureEdgeMesh::featureEdgeMesh(), fieldDictionary::fieldDictionary(), IOMap< T >::IOMap(), IOmapDistribute::IOmapDistribute(), polyBoundaryMeshEntries::polyBoundaryMeshEntries(), regIOobject::read(), refinementHistory::read(), refinementHistory::refinementHistory(), and topoSet::topoSet().
readData()
bool readData (Istream &) virtual
Virtual readData function.
Must be defined in derived types for which re-reading is required
Reimplemented in refinementHistory, extendedFeatureEdgeMesh, IOdictionary, featureEdgeMesh, and IOmapDistribute.
Definition at line 164 of file regIOobjectRead.C.
Referenced by regIOobject::read(), and IOPosition< CloudType >::type().
read()
bool read () virtual
Read object.
Reimplemented in basicThermo, refinementHistory, phaseSystem, phaseModel, Time, multiphaseSystem, multiphaseMixture, kinematicSingleLayer, incompressibleThreePhaseMixture, radiationModel, phaseModel, engineTime, thermoSingleLayer, incompressibleTwoPhaseInteractingMixture, kineticTheoryModel, kineticTheoryModel, twoPhaseSystem, fvDOM, rigidBodyMeshMotion, RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > >, RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >, rigidBodyMeshMotionSolver, solidThermo, reactingOneDim, motionSolver, incompressibleTwoPhaseMixture, viewFactor, phaseChangeTwoPhaseMixture, fvSchemes, combustionModel, SRFModel, solution, phasePressureModel, sixDoFRigidBodyMotionSolver, regionModel, phasePressureModel, rhoCombustionModel, psiCombustionModel, SchnerrSauer, IOOutputFilter< OutputFilter >, turbulenceModel, Kunz, P1, thermalBaffle, Merkle, singlePhaseTransportModel, regionModel1D, EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, IOMRFZoneList, options, thermalBaffleModel, singleLayerRegion, opaqueSolid, rpm, noRadiation, tolerances, surfaceFilmModel, pyrolysisModel, linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, IOporosityModelList, immiscibleIncompressibleTwoPhaseMixture, noPyrolysis, noThermo, and noFilm.
Definition at line 170 of file regIOobjectRead.C.
References UPstream::commsStruct::above(), IOstream::ASCII, UPstream::commsStruct::below(), regIOobject::close(), Foam::endl(), regIOobject::fileModificationChecking, forAllReverse, IOobject::headerClassName(), regIOobject::inotifyMaster, UPstream::linearCommunication(), UPstream::master(), regIOobject::masterOnlyReading, UPstream::msgType(), UPstream::myProcNo(), IOobject::name(), IOobject::note(), UPstream::nProcs(), UPstream::nProcsSimpleSum, UPstream::parRun(), Foam::Pout, regIOobject::readData(), Pstream::scatter(), UPstream::scheduled, regIOobject::timeStampMaster, UPstream::treeCommunication(), Foam::type(), UPstream::worldComm, and regIOobject::writeData().
Referenced by phaseModel::alphaPhi(), PDRDragModel::on(), porosityModel::iNew::operator()(), IOporosityModelList::read(), tolerances::read(), IOMRFZoneList::read(), singlePhaseTransportModel::read(), turbulenceModel::read(), regionModel::read(), SRFModel::read(), solution::read(), combustionModel::read(), fvSchemes::read(), motionSolver::read(), incompressibleTwoPhaseMixture::read(), solidThermo::read(), radiationModel::read(), basicThermo::read(), regIOobject::readIfModified(), and phase::rho().
watchIndex() [1/2]
Foam::label watchIndex () const inline
Return file-monitoring handle.
Definition at line 91 of file regIOobjectI.H.
Referenced by Time::readDict().
watchIndex() [2/2]
Foam::label & watchIndex () inline
Return file-monitoring handle.
Definition at line 97 of file regIOobjectI.H.
modified()
bool modified () const virtual
Return true if the object's file (or files for objectRegistry)
have been modified. (modified state is cached by Time)
Reimplemented in objectRegistry.
Definition at line 271 of file regIOobjectRead.C.
References Time::getState(), IOobject::time(), and fileMonitor::UNMODIFIED.
Referenced by regIOobject::readIfModified().
readIfModified()
bool readIfModified () virtual
Read object if modified (as set by call to modified)
Reimplemented in objectRegistry.
Definition at line 284 of file regIOobjectRead.C.
References Foam::endl(), Time::getFile(), InfoInFunction, regIOobject::modified(), IOobject::name(), Foam::nl, regIOobject::read(), and IOobject::time().
Referenced by Time::readModifiedObjects().
writeData()
virtual bool writeData (Ostream &) const pure virtual
Pure virtual writaData function.
Must be defined in derived types
Implemented in GeometricField< Type, PatchField, GeoMesh >, GeometricField< Type, Foam::pointPatchField, Foam::pointMesh >, GeometricField< Type, Foam::fvPatchField, Foam::volMesh >, GeometricField< scalar, Foam::fvPatchField, Foam::volMesh >, GeometricField< symmTensor, fvPatchField, volMesh >, GeometricField< tensor, fvPatchField, volMesh >, GeometricField< vector, fvsPatchField, surfaceMesh >, GeometricField< scalar, fvPatchField, volMesh >, GeometricField< scalar, fvsPatchField, surfaceMesh >, GeometricField< Foam::Vector, Foam::pointPatchField, Foam::pointMesh >, GeometricField< scalar, pointPatchField, pointMesh >, GeometricField< vector, fvPatchField, volMesh >, GeometricField< scalar, Foam::pointPatchField, Foam::pointMesh >, GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricField< Foam::Vector, Foam::fvPatchField, Foam::volMesh >, GeometricField< vector, pointPatchField, pointMesh >, refinementHistory, DimensionedField< Type, GeoMesh >, DimensionedField< scalar, Foam::volMesh >, DimensionedField< scalar, triSurfacePointGeoMesh >, DimensionedField< Type, Foam::surfaceMesh >, DimensionedField< Type, Foam::volMesh >, DimensionedField< vector, Foam::pointMesh >, DimensionedField< Type, Foam::pointMesh >, searchableSurfaceWithGaps, topoSet, searchableSurfaceCollection, triSurfaceMesh, searchableBox, porosityModel, searchableCylinder, polyBoundaryMesh, searchableDisk, searchablePlate, searchableSphere, objectRegistry, searchablePlane, DarcyForchheimer, ZoneMesh< ZoneType, MeshType >, ZoneMesh< faceZone, polyMesh >, ZoneMesh< pointZone, polyMesh >, ZoneMesh< cellZone, polyMesh >, powerLaw, PDRDragModel, AveragingMethod< Type >, AveragingMethod< scalar >, AveragingMethod< Foam::Vector >, fixedCoeff, MeshObject< fvMesh, MoveableMeshObject, FitDataType >, MeshObject< polyMesh, GeometricMeshObject, meshSearchMeshObject >, MeshObject< polyMesh, UpdateableMeshObject, decompositionModel >, MeshObject< fvMesh, MoveableMeshObject, CentredFitData< Polynomial > >, MeshObject< fvMesh, TopologicalMeshObject, centredCPCCellToFaceStencilObject >, MeshObject< polyMesh, UpdateableMeshObject, twoDPointCorrector >, MeshObject< fvMesh, UpdateableMeshObject, wallDist >, MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >, MeshObject< fvMesh, TopologicalMeshObject, centredCPCCellToCellStencilObject >, MeshObject< fvMesh, TopologicalMeshObject, centredCECCellToCellStencilObject >, MeshObject< polyMesh, GeometricMeshObject, meshSearchFACE_CENTRE_TRISMeshObject >, MeshObject< fvMesh, TopologicalMeshObject, centredCFCFaceToCellStencilObject >, MeshObject< fvMesh, TopologicalMeshObject, upwindFECCellToFaceStencilObject >, MeshObject< fvMesh, MoveableMeshObject, LeastSquaresVectors< Stencil > >, MeshObject< fvMesh, TopologicalMeshObject, centredCFCCellToCellStencilObject >, MeshObject< fvMesh, MoveableMeshObject, leastSquaresVectors >, MeshObject< fvMesh, TopologicalMeshObject, upwindCECCellToFaceStencilObject >, MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >, MeshObject< fvMesh, TopologicalMeshObject, upwindCFCCellToFaceStencilObject >, MeshObject< fvMesh, TopologicalMeshObject, upwindCPCCellToFaceStencilObject >, MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >, MeshObject< fvMesh, TopologicalMeshObject, pureUpwindCFCCellToFaceStencilObject >, MeshObject< fvMesh, TopologicalMeshObject, centredCECCellToFaceStencilObject >, MeshObject< fvMesh, MoveableMeshObject, UpwindFitData< Polynomial > >, MeshObject< polyMesh, TopologicalMeshObject, regionSplit >, MeshObject< fvMesh, MoveableMeshObject, skewCorrectionVectors >, MeshObject< polyMesh, UpdateableMeshObject, pointMesh >, MeshObject< fvMesh, TopologicalMeshObject, centredCFCCellToFaceStencilObject >, MeshObject< fvMesh, TopologicalMeshObject, centredFECCellToFaceStencilObject >, MeshObject< fvMesh, MoveableMeshObject, CentredFitSnGradData< Polynomial > >, SLGThermo, polyTopoChanger, dragModel, dragModel, virtualMassModel, virtualMassModel, extendedFeatureEdgeMesh, coordinateSystems, surfaceTensionModel, CompactIOList< T, BaseType >, CompactIOList< face, label >, CompactIOField< T, BaseType >, IOdictionary, surfacePatchIOList, surfZoneIOList, UniformDimensionedField< Type >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, IOPtrList< T >, IOPtrList< coordinateSystem >, featureEdgeMesh, IOPosition< CloudType >, IOmapDistribute, IOList< T >, IOMap< T >, IOList< label >, IOList< reactingParcelInjectionData >, IOList< reactingMultiphaseParcelInjectionData >, IOList< kinematicParcelInjectionData >, IOList< labelList >, IOField< Type >, IOField< vector >, fieldDictionary, and polyBoundaryMeshEntries.
Referenced by regIOobject::read(), and searchableSurfaceWithGaps::writeData().
writeObject()
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const virtual
Write using given format, version and compression.
Reimplemented in distributedTriSurfaceMesh, Time, fvMesh, Cloud< ParticleType >, Cloud< Foam::passiveParticle >, Cloud< wallBoundedStreamLineParticle >, Cloud< findCellParticle >, Cloud< indexedParticle >, Cloud< basicKinematicCollidingParcel >, Cloud< typename Foam::DSMCCloud::parcelType >, Cloud< trackedParticle >, Cloud< ParcelType >, Cloud< Foam::molecule >, Cloud< solidParticle >, Cloud< parcelType >, Cloud< molecule >, Cloud< DSMCParcel< ParcelType > >, Cloud< passiveParticle >, Cloud< streamLineParticle >, triSurfaceMesh, dynamicRefineFvMesh, polyBoundaryMesh, objectRegistry, rigidBodyMeshMotion, faceZoneSet, rigidBodyMeshMotionSolver, motionSolver, pointZoneSet, cellZoneSet, sixDoFRigidBodyMotionSolver, CompactIOList< T, BaseType >, CompactIOList< face, label >, and CompactIOField< T, BaseType >.
Definition at line 37 of file regIOobjectWrite.C.
References Foam::endl(), IOstream::good(), Foam::Info, InfoInFunction, IOobject::instance(), Foam::mkDir(), Foam::name(), path(), SeriousErrorInFunction, Foam::system(), timeName, and writeData().
Referenced by meshReader::warnDuplicates(), regIOobject::write(), CompactIOField< T, BaseType >::writeObject(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), polyBoundaryMesh::writeObject(), and distributedTriSurfaceMesh::writeObject().
write()
bool write () const virtual
Write using setting from DB.
Reimplemented in fvMesh, AveragingMethod< Type >, AveragingMethod< scalar >, AveragingMethod< Foam::Vector >, and IOPosition< CloudType >.
Definition at line 125 of file regIOobjectWrite.C.
References IOstream::currentVersion, IOobject::time(), and regIOobject::writeObject().
Referenced by snappyLayerDriver::addLayers(), rotorDiskSource::addSup(), hexRef8::consistentSlowRefinement2(), thixotropicViscosity::correct(), snappySnapDriver::doSnap(), dynamicRefineFvMesh::dynamicRefineFvMesh(), if(), Foam::MapConsistentVolFields(), Foam::MapLagrangianFields(), Foam::MapVolFields(), meshRefinement::mergePatchFacesUndo(), polyMesh::movePoints(), polyMesh::polyMesh(), snappySnapDriver::scaleMesh(), removeFaces::setRefinement(), hexRef8::setUnrefinement(), snappyRefineDriver::snappyRefineDriver(), surfMesh::surfZones(), IOPosition< CloudType >::write(), dsmcFields::write(), yPlus::write(), writeCellVolumes::write(), XiReactionRate::write(), processorField::write(), AveragingMethod< Foam::Vector >::write(), wallHeatFlux::write(), wallShearStress::write(), writeObjects::write(), surfMesh::write(), regionSizeDistribution::write(), fvMesh::write(), hexRef8::write(), meshRefinement::write(), wallBoundedStreamLineParticle::writeFields(), MPPICParcel< ParcelType >::writeFields(), streamLineParticle::writeFields(), SprayParcel< ParcelType >::writeFields(), KinematicParcel< ParcelType >::writeFields(), Time::writeNow(), regionFunctionObject::writeObject(), cellZoneSet::writeObject(), pointZoneSet::writeObject(), faceZoneSet::writeObject(), dynamicRefineFvMesh::writeObject(), fvMesh::writeObject(), and volFieldValue::writeValues().
operator=()
void operator= (const IOobject & io)
Definition at line 423 of file regIOobject.C.
References regIOobject::checkIn(), regIOobject::checkOut(), IOobject::operator=(), and IOobject::registerObject().
Friends And Related Function Documentation
functionEntries::codeStream
friend class functionEntries::codeStream friend
Declare friendship with any classes that need access to.
masterOnlyReading
Definition at line 118 of file regIOobject.H.
Member Data Documentation
fileCheckTypesNames
const Foam::NamedEnum< Foam::regIOobject::fileCheckTypes, 4 > fileCheckTypesNames static
Definition at line 76 of file regIOobject.H.
Referenced by NamedEnum< directionType, 3 >::names(), argList::parse(), addfileModificationCheckingToOpt::readData(), and addfileModificationCheckingToOpt::writeData().
masterOnlyReading
bool masterOnlyReading = false static protected
To flag master-only reading of objects.
Definition at line 82 of file regIOobject.H.
Referenced by regIOobject::read(), and addfileModificationCheckingToOpt::writeData().
fileModificationSkew
int fileModificationSkew static
Definition at line 126 of file regIOobject.H.
Referenced by NamedEnum< directionType, 3 >::names(), and fileMonitorWatcher::removeWatch().
fileModificationChecking
Foam::regIOobject::fileCheckTypes fileModificationChecking static
Definition at line 128 of file regIOobject.H.
Referenced by distributedTriSurfaceMesh::distributedTriSurfaceMesh(), hexRef8::hexRef8(), IOdictionary::IOdictionary(), NamedEnum< directionType, 3 >::names(), argList::parse(), regIOobject::read(), addfileModificationCheckingToOpt::readData(), Time::readModifiedObjects(), Time::Time(), and addfileModificationCheckingToOpt::writeData().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/regIOobject/regIOobject.H
src/OpenFOAM/db/regIOobject/regIOobject.C
src/OpenFOAM/db/regIOobject/regIOobjectI.H
src/OpenFOAM/db/regIOobject/regIOobjectRead.C
src/OpenFOAM/db/regIOobject/regIOobjectWrite.C