OpenFOAM: instant Class Reference
instant Class Reference
An instant of time. Contains the time value and name.
Classes
class less
Less function class used in sorting instants.
Public Member Functions
instant ()
Construct null.
instant (const scalar, const word &)
Construct from components.
instant (const scalar)
Construct from time value.
instant (const word &)
Construct from word.
scalar value () const
Value (const access)
scalar & value ()
Value (non-const access)
const word & name () const
Name (const access)
word & name ()
Name (non-const access)
bool equal (const scalar) const
Comparison used for instants to be equal.
Static Public Attributes
static const char *const typeName = "instant"
Friends
bool operator== (const instant &, const instant &)
bool operator!= (const instant &, const instant &)
Istream & operator>> (Istream &, instant &)
Ostream & operator<< (Ostream &, const instant &)
Detailed Description
An instant of time. Contains the time value and name.
Source files
instant.H
instant.C
Definition at line 64 of file instant.H.
Constructor & Destructor Documentation
instant() [1/4]
instant ()
Construct null.
Definition at line 35 of file instant.C.
instant() [2/4]
instant (const scalar val, const word & tname)
Construct from components.
Definition at line 38 of file instant.C.
instant() [3/4]
instant (const scalar val) explicit
Construct from time value.
Definition at line 44 of file instant.C.
instant() [4/4]
instant (const word & tname) explicit
Construct from word.
Definition at line 50 of file instant.C.
Member Function Documentation
value() [1/2]
scalar value () const inline
Value (const access)
Definition at line 112 of file instant.H.
Referenced by instant::less::operator()(), timeSelector::selected(), and Time::setTime().
value() [2/2]
scalar& value () inline
Value (non-const access)
Definition at line 118 of file instant.H.
name() [1/2]
const word& name () const inline
Name (const access)
Definition at line 124 of file instant.H.
Referenced by Time::setTime().
name() [2/2]
word& name () inline
Name (non-const access)
Definition at line 130 of file instant.H.
References instant::equal(), instant::operator!=, instant::operator<<, instant::operator==, and instant::operator>>.
equal()
bool equal (const scalar b) const
Comparison used for instants to be equal.
Definition at line 59 of file instant.C.
Referenced by Time::findInstancePath(), instant::name(), and Foam::operator==().
Friends And Related Function Documentation
operator==
bool operator== (const instant & , const instant &) friend
Referenced by instant::name(), and Foam::operator!=().
operator!=
bool operator!= (const instant & , const instant &) friend
Referenced by instant::name().
operator>>
Istream& operator>> (Istream & , instant &) friend
Referenced by instant::name().
operator<<
Ostream& operator<< (Ostream & , const instant &) friend
Referenced by instant::name().
Member Data Documentation
typeName
const char *const typeName = "instant" static
Definition at line 89 of file instant.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/instant/instant.H
src/OpenFOAM/db/Time/instant/instant.C