OpenFOAM: ITstream Class Reference
ITstream Class Reference
Input token stream.
Public Member Functions
ITstream (const string &name, const UList< token > &tokens, streamFormat format=ASCII, versionNumber version=currentVersion)
Construct from components.
ITstream (const string &name, const Xfer< List< token >> &tokens, streamFormat format=ASCII, versionNumber version=currentVersion)
Construct from components, transferring the tokens.
ITstream (const ITstream &its)
Construct as copy.
virtual ~ITstream ()
Destructor.
const fileName & name () const
Return the name of the stream.
fileName & name ()
Return non-const access to the name of the stream.
label tokenIndex () const
Return the current token index.
label & tokenIndex ()
Return non-const access to the current token index.
label nRemainingTokens () const
Return the number of remaining tokens.
ios_base::fmtflags flags () const
Return flags of output stream.
virtual Istream & read (token &)
Return next token from stream.
virtual Istream & read (char &)
Read a character.
virtual Istream & read (word &)
Read a word.
virtual Istream & read (string &)
virtual Istream & read (label &)
Read a label.
virtual Istream & read (floatScalar &)
Read a floatScalar.
virtual Istream & read (doubleScalar &)
Read a doubleScalar.
virtual Istream & read (char *, std::streamsize)
Read binary block.
virtual Istream & rewind ()
Rewind and return the stream so that it may be read again.
ios_base::fmtflags flags (const ios_base::fmtflags)
Set flags of stream.
void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from Istream
Istream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Istream ()
Destructor.
void putBack (const token &)
Put back token.
bool getBack (token &)
Get the put back token if there is one and return true.
bool peekBack (token &)
Peek at the put back token without removing it.
Istream & readBegin (const char *funcName)
Istream & readEnd (const char *funcName)
Istream & readEndBegin (const char *funcName)
char readBeginList (const char *funcName)
char readEndList (const char *funcName)
Istream & operator() () const
Return a non-const reference to const Istream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Attributes inherited from IOstream
label lineNumber_
Detailed Description
Input token stream.
Source files
ITstream.H
ITstream.C
Definition at line 49 of file ITstream.H.
Constructor & Destructor Documentation
ITstream() [1/3]
ITstream (const string & name, const UList< token > & tokens, streamFormat format = ASCII, versionNumber version = currentVersion) inline
Construct from components.
Definition at line 69 of file ITstream.H.
References IOstream::setGood(), and IOstream::setOpened().
ITstream() [2/3]
ITstream (const string & name, const Xfer< List< token >> & tokens, streamFormat format = ASCII, versionNumber version = currentVersion) inline
Construct from components, transferring the tokens.
Definition at line 88 of file ITstream.H.
References IOstream::setGood(), and IOstream::setOpened().
ITstream() [3/3]
ITstream (const ITstream & its) inline
Construct as copy.
Definition at line 106 of file ITstream.H.
References IOstream::setGood(), and IOstream::setOpened().
~ITstream()
virtual ~ITstream () inline virtual
Destructor.
Definition at line 119 of file ITstream.H.
Member Function Documentation
name() [1/2]
const fileName& name () const inline virtual
Return the name of the stream.
Reimplemented from IOstream.
Definition at line 128 of file ITstream.H.
Referenced by primitiveEntry::name().
name() [2/2]
fileName& name () inline virtual
Return non-const access to the name of the stream.
Reimplemented from IOstream.
Definition at line 134 of file ITstream.H.
tokenIndex() [1/2]
label tokenIndex () const inline
Return the current token index.
Definition at line 140 of file ITstream.H.
Referenced by primitiveEntry::read().
tokenIndex() [2/2]
label& tokenIndex () inline
Return non-const access to the current token index.
Definition at line 146 of file ITstream.H.
nRemainingTokens()
label nRemainingTokens () const inline
Return the number of remaining tokens.
Definition at line 152 of file ITstream.H.
References List< T >::size().
flags() [1/2]
ios_base::fmtflags flags () const inline virtual
Return flags of output stream.
Implements IOstream.
Definition at line 158 of file ITstream.H.
References ITstream::read(), and ITstream::rewind().
read() [1/8]
Foam::Istream & read (token & t) virtual
Return next token from stream.
Implements Istream.
Definition at line 56 of file ITstream.C.
References IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Istream::getBack(), UList< T >::last(), token::lineNumber(), IOstream::lineNumber(), IOstream::lineNumber_, UList< T >::operator[](), IOstream::setBad(), IOstream::setEof(), List< T >::size(), and token::undefinedToken.
Referenced by primitiveEntry::clone(), ITstream::flags(), relaxation::read(), and writeObjects::read().
read() [2/8]
Foam::Istream & read (char &) virtual
Read a character.
Implements Istream.
Definition at line 108 of file ITstream.C.
References NotImplemented.
read() [3/8]
Foam::Istream & read (word &) virtual
Read a word.
Implements Istream.
Definition at line 115 of file ITstream.C.
References NotImplemented.
read() [4/8]
Foam::Istream & read (string &) virtual
Implements Istream.
Definition at line 122 of file ITstream.C.
References NotImplemented.
read() [5/8]
Foam::Istream & read (label &) virtual
Read a label.
Implements Istream.
Definition at line 129 of file ITstream.C.
References NotImplemented.
read() [6/8]
Foam::Istream & read (floatScalar &) virtual
Read a floatScalar.
Implements Istream.
Definition at line 136 of file ITstream.C.
References NotImplemented.
read() [7/8]
Foam::Istream & read (doubleScalar &) virtual
Read a doubleScalar.
Implements Istream.
Definition at line 143 of file ITstream.C.
References NotImplemented.
read() [8/8]
Foam::Istream & read (char * , std::streamsize) virtual
Read binary block.
Implements Istream.
Definition at line 150 of file ITstream.C.
References NotImplemented.
rewind()
Foam::Istream & rewind () virtual
Rewind and return the stream so that it may be read again.
Implements Istream.
Definition at line 157 of file ITstream.C.
References UList< T >::first(), IOstream::lineNumber_, IOstream::setGood(), and List< T >::size().
Referenced by ITstream::flags(), and primitiveEntry::stream().
flags() [2/2]
ios_base::fmtflags flags (const ios_base::fmtflags) inline virtual
Set flags of stream.
Implements IOstream.
Definition at line 197 of file ITstream.H.
References ITstream::print().
print()
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from IOstream.
Definition at line 31 of file ITstream.C.
References UList< T >::begin(), IOstream::lineNumber(), IOstream::print(), UList< T >::rbegin(), and List< T >::size().
Referenced by ITstream::flags(), and primitiveEntry::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Tstreams/ITstream.H
src/OpenFOAM/db/IOstreams/Tstreams/ITstream.C