OpenFOAM: subCycleTime Class Reference
subCycleTime Class Reference
A class for managing sub-cycling times.
Public Member Functions
subCycleTime (Time &, const label nSubCycles)
Construct from original time and number of sub-cycles.
~subCycleTime ()
Destructor.
bool end () const
Return true if the number of sub-cycles has been reached.
void endSubCycle ()
End the sub-cycling and reset the time-state.
label nSubCycles () const
Return the total number of sub-cycles.
label index () const
Return the current sub-cycle index.
subCycleTime & operator++ ()
Prefix increment.
subCycleTime & operator++ (int)
Postfix increment.
Detailed Description
A class for managing sub-cycling times.
Source files
subCycleTime.H
subCycleTime.C
Definition at line 48 of file subCycleTime.H.
Constructor & Destructor Documentation
subCycleTime()
subCycleTime (Time & t, const label nSubCycles)
Construct from original time and number of sub-cycles.
Definition at line 30 of file subCycleTime.C.
References Time::subCycle().
~subCycleTime()
~subCycleTime ()
Destructor.
Definition at line 42 of file subCycleTime.C.
References subCycleTime::endSubCycle().
Member Function Documentation
end()
bool end () const
Return true if the number of sub-cycles has been reached.
Definition at line 50 of file subCycleTime.C.
endSubCycle()
void endSubCycle ()
End the sub-cycling and reset the time-state.
Definition at line 56 of file subCycleTime.C.
References Time::endSubCycle().
Referenced by CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::motion(), and subCycleTime::~subCycleTime().
nSubCycles()
label nSubCycles () const inline
Return the total number of sub-cycles.
Definition at line 78 of file subCycleTime.H.
index()
label index () const inline
Return the current sub-cycle index.
Definition at line 84 of file subCycleTime.H.
References subCycleTime::operator++().
operator++() [1/2]
Foam::subCycleTime & operator++ ()
Prefix increment.
Definition at line 64 of file subCycleTime.C.
Referenced by subCycleTime::index(), and subCycleTime::operator++().
operator++() [2/2]
Foam::subCycleTime & operator++ (int)
Postfix increment.
Definition at line 72 of file subCycleTime.C.
References subCycleTime::operator++().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/subCycleTime.H
src/OpenFOAM/db/Time/subCycleTime.C