OpenFOAM: FieldMapper Class Reference
FieldMapper Class Reference abstract
Abstract base class to hold the Field mapping addressing and weights.
Public Member Functions
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual label size () const =0
virtual bool direct () const =0
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
virtual bool hasUnmapped () const =0
Are there unmapped values? I.e. do all size() elements get.
virtual const labelUList & directAddressing () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
Abstract base class to hold the Field mapping addressing and weights.
Definition at line 45 of file FieldMapper.H.
Constructor & Destructor Documentation
FieldMapper()
FieldMapper () inline
Null constructor.
Definition at line 53 of file FieldMapper.H.
~FieldMapper()
virtual ~FieldMapper () inline virtual
Destructor.
Definition at line 58 of file FieldMapper.H.
References FieldMapper::direct(), and FieldMapper::size().
Member Function Documentation
size()
virtual label size () const pure virtual
Implemented in meshToMesh0::patchFieldInterpolator, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, fvPatchMapper, singleCellFvMesh::agglomPatchFieldMapper, faceMapper, cellMapper, pointMapper, fvSurfaceMapper, fvFieldReconstructor::fvPatchFieldReconstructor, distributedWeightedFvPatchFieldMapper, pointFieldReconstructor::pointPatchFieldReconstructor, weightedFvPatchFieldMapper, pointFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, fvFieldDecomposer::patchFieldDecomposer, and directFieldMapper.
Referenced by Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), Field< Foam::Vector2D >::map(), and FieldMapper::~FieldMapper().
direct()
virtual bool direct () const pure virtual
Implemented in meshToMesh0::patchFieldInterpolator, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, fvPatchMapper, faceMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, fvSurfaceMapper, singleCellFvMesh::agglomPatchFieldMapper, cellMapper, pointMapper, distributedWeightedFvPatchFieldMapper, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, weightedFvPatchFieldMapper, pointFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, fvFieldDecomposer::patchFieldDecomposer, and directFieldMapper.
Referenced by Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), pointPatchMapper::direct(), Field< Foam::Vector2D >::map(), and FieldMapper::~FieldMapper().
distributed()
virtual bool distributed () const inline virtual
Reimplemented in distributedWeightedFvPatchFieldMapper.
Definition at line 68 of file FieldMapper.H.
Referenced by Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), and Field< Foam::Vector2D >::map().
distributeMap()
virtual const mapDistributeBase& distributeMap () const inline virtual
Reimplemented in distributedWeightedFvPatchFieldMapper.
Definition at line 73 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and FieldMapper::hasUnmapped().
Referenced by Field< Foam::Vector2D >::autoMap(), and Field< Foam::Vector2D >::map().
hasUnmapped()
virtual bool hasUnmapped () const pure virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implemented in meshToMesh0::patchFieldInterpolator, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, distributedWeightedFvPatchFieldMapper, fvPatchMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, fvSurfaceMapper, faceMapper, pointPatchMapper, singleCellFvMesh::agglomPatchFieldMapper, pointMapper, cellMapper, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, weightedFvPatchFieldMapper, pointFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, and directFieldMapper.
Referenced by fvPatchField< Type >::autoMap(), directionMixedFvPatchField< Type >::directionMixedFvPatchField(), FieldMapper::distributeMap(), fixedGradientFvPatchField< Type >::fixedGradientFvPatchField(), fixedValueFvPatchField< scalar >::fixedValueFvPatchField(), fvPatchField< Type >::fvPatchField(), and mixedFvPatchField< scalar >::mixedFvPatchField().
directAddressing()
virtual const labelUList& directAddressing () const inline virtual
Reimplemented in meshToMesh0::patchFieldInterpolator, pointPatchMapper, fvPatchMapper, fvSurfaceMapper, faceMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, pointMapper, cellMapper, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, pointFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, and directFieldMapper.
Definition at line 85 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UList< T >::null().
Referenced by Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), and Field< Foam::Vector2D >::map().
addressing()
virtual const labelListList& addressing () const inline virtual
Reimplemented in fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, fvPatchMapper, distributedWeightedFvPatchFieldMapper, fvSurfaceMapper, faceMapper, pointMapper, cellMapper, singleCellFvMesh::agglomPatchFieldMapper, and weightedFvPatchFieldMapper.
Definition at line 94 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< labelList >::null().
Referenced by Field< Foam::Vector2D >::autoMap(), fvPatchField< Type >::autoMap(), and Field< Foam::Vector2D >::map().
weights()
virtual const scalarListList& weights () const inline virtual
Reimplemented in fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, fvPatchMapper, distributedWeightedFvPatchFieldMapper, fvSurfaceMapper, faceMapper, pointMapper, cellMapper, singleCellFvMesh::agglomPatchFieldMapper, and weightedFvPatchFieldMapper.
Definition at line 103 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< scalarList >::null().
Referenced by Field< Foam::Vector2D >::map(), and meshToMesh0::V().
operator()()
tmp<Field<Type> > operator() (const Field< Type > & f) const inline
Definition at line 116 of file FieldMapper.H.
References f().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/Fields/Field/FieldMapper.H