OpenFOAM: DynamicField< T, SizeInc, SizeMult, SizeDiv > Class Template Reference
DynamicField< T, SizeInc, SizeMult, SizeDiv > Class Template Reference
Dynamically sized Field.
Public Member Functions
DynamicField ()
Construct null.
DynamicField (const label)
Construct given size.
DynamicField (const UList< T > &)
Construct from UList. Size set to UList size.
DynamicField (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
DynamicField (const UList< T > &mapF, const labelList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
DynamicField (const UList< T > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
DynamicField (const UList< T > &mapF, const FieldMapper &map)
Construct by mapping from the given field.
DynamicField (const DynamicField< T, SizeInc, SizeMult, SizeDiv > &)
Construct copy.
DynamicField (const Xfer< DynamicField< T, SizeInc, SizeMult, SizeDiv >> &)
Construct by transferring the Field contents.
DynamicField (Istream &)
Construct from Istream. Size set to size of list read.
tmp< DynamicField< T, SizeInc, SizeMult, SizeDiv > > clone () const
Clone.
label capacity () const
Size of the underlying storage.
void setCapacity (const label)
Alter the size of the underlying storage.
void setSize (const label)
Alter the addressed list size.
void setSize (const label, const T &)
Alter the addressed list size and fill new space with a.
void resize (const label)
Alter the addressed list size.
void resize (const label, const T &)
Alter the addressed list size and fill new space with a.
void reserve (const label)
Reserve allocation space for at least this size.
void clear ()
Clear the addressed list, i.e. set the size to zero.
void clearStorage ()
Clear the list and delete storage.
DynamicField< T, SizeInc, SizeMult, SizeDiv > & shrink ()
Shrink the allocated space to the number of elements used.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container as a plain List.
DynamicField< T, SizeInc, SizeMult, SizeDiv > & append (const T &)
Append an element at the end of the list.
DynamicField< T, SizeInc, SizeMult, SizeDiv > & append (const UList< T > &)
Append a List at the end of this list.
T remove ()
Remove and return the top element.
T & operator() (const label)
Return non-const access to an element, resizing list if.
void operator= (const T &)
Assignment of all addressed entries to the given value.
void operator= (const DynamicField< T, SizeInc, SizeMult, SizeDiv > &)
Assignment to DynamicField.
void operator= (const UList< T > &)
Assignment to UList.
Public Member Functions inherited from Field< T >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const T &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< T > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< T >> &)
Construct by transferring the List contents.
Field (const UList< T > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< T >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< T > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< T >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< T > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< T > &mapF, const FieldMapper &map, const T &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< T > &mapF, const FieldMapper &map, const UList< T > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< T >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< T >> &tmapF, const FieldMapper &map, const T &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< T >> &tmapF, const FieldMapper &map, const UList< T > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< T > &)
Construct as copy.
Field (Field< T > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< T >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< T >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< T > > clone () const
Clone.
void map (const UList< T > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< T >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< T > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< T >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< T > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< T >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< T > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< T >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< T > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< T >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
VSForm block (const label start) const
tmp< Field< T > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< T > &)
void operator= (const UList< T > &)
void operator= (const SubField< T > &)
void operator= (const tmp< Field< T >> &)
void operator= (const T &)
void operator= (const zero)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator= (const tmp< Field > &rhs)
void operator+= (const UList< T > &)
void operator+= (const tmp< Field< T >> &)
void operator+= (const T &)
void operator-= (const UList< T > &)
void operator-= (const tmp< Field< T >> &)
void operator-= (const T &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator*= (const scalar &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static const DynamicField< T, SizeInc, SizeMult, SizeDiv > & null ()
Return a null field.
Static Public Member Functions inherited from Field< T >
static const Field< T > & null ()
Return a null field.
static tmp< Field< T > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Additional Inherited Members
Public Types inherited from Field< T >
typedef pTraits< T >::cmptType cmptType
Component type.
typedef SubField< T > subField
Declare type of subField.
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Attributes inherited from Field< T >
static const char *const typeName
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class T, unsigned SizeInc = 0, unsigned SizeMult = 2, unsigned SizeDiv = 1>
class Foam::DynamicField< T, SizeInc, SizeMult, SizeDiv >
Dynamically sized Field.
Source files
DynamicField.H
DynamicFieldI.H
DynamicField.C
Definition at line 49 of file DynamicField.H.
Constructor & Destructor Documentation
DynamicField() [1/10]
DynamicField () inline
Construct null.
Definition at line 29 of file DynamicFieldI.H.
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::DynamicField(), and DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
DynamicField() [2/10]
DynamicField (const label nElem) inline explicit
Construct given size.
Definition at line 38 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::DynamicField(), and List< Type >::size().
DynamicField() [3/10]
DynamicField (const UList< T > & lst) inline explicit
Construct from UList. Size set to UList size.
Also constructs from DynamicField with different sizing parameters.
Definition at line 52 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::DynamicField().
DynamicField() [4/10]
DynamicField (const Xfer< List< T >> & lst) inline explicit
Construct by transferring the parameter contents.
Definition at line 63 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::DynamicField().
DynamicField() [5/10]
DynamicField (const UList< T > & mapF, const labelList & mapAddressing) inline
Construct by 1 to 1 mapping from the given field.
Definition at line 74 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::DynamicField().
DynamicField() [6/10]
DynamicField (const UList< T > & mapF, const labelListList & mapAddressing, const scalarListList & weights) inline
Construct by interpolative mapping from the given field.
Definition at line 86 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::DynamicField().
DynamicField() [7/10]
DynamicField (const UList< T > & mapF, const FieldMapper & map) inline
Construct by mapping from the given field.
Definition at line 100 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::DynamicField().
DynamicField() [8/10]
DynamicField (const DynamicField< T, SizeInc, SizeMult, SizeDiv > & lst) inline
Construct copy.
Definition at line 112 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::DynamicField().
DynamicField() [9/10]
DynamicField (const Xfer< DynamicField< T, SizeInc, SizeMult, SizeDiv >> & lst) inline
Construct by transferring the Field contents.
Definition at line 123 of file DynamicFieldI.H.
DynamicField() [10/10]
DynamicField (Istream & is) explicit
Construct from Istream. Size set to size of list read.
Definition at line 31 of file DynamicField.C.
Member Function Documentation
null()
static const DynamicField<T, SizeInc, SizeMult, SizeDiv>& null () inline static
Return a null field.
Definition at line 92 of file DynamicField.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::capacity(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::clear(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::clearStorage(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::clone(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::DynamicField(), Field< T >::map(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::operator()(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::operator=(), reinterpret_cast(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::reserve(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::resize(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::shrink(), Field< T >::T(), and DynamicField< T, SizeInc, SizeMult, SizeDiv >::xfer().
clone()
Foam::tmp< Foam::DynamicField< T, SizeInc, SizeMult, SizeDiv > > clone () const
Clone.
Definition at line 40 of file DynamicField.C.
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
capacity()
Foam::label capacity () const inline
Size of the underlying storage.
Definition at line 135 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::setCapacity().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
setCapacity()
void setCapacity (const label nElem) inline
Alter the size of the underlying storage.
The addressed size will be truncated if needed to fit, but will remain otherwise untouched. Use this or reserve() in combination with append().
Definition at line 144 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::reserve(), List< Type >::setSize(), and List< Type >::size().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::capacity(), and DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
setSize() [1/2]
void setSize (const label nElem) inline
Alter the addressed list size.
New space will be allocated if required. Use this to resize the list prior to using the operator[] for setting values (as per List usage).
Definition at line 202 of file DynamicFieldI.H.
References Foam::max(), List< Type >::setSize(), and List< Type >::size().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::null(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::operator()(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::reserve(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::resize(), and DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize().
setSize() [2/2]
void setSize (const label nElem, const T & t) inline
Alter the addressed list size and fill new space with a.
constant.
Definition at line 239 of file DynamicFieldI.H.
References UList< T >::operator[](), DynamicField< T, SizeInc, SizeMult, SizeDiv >::resize(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize(), and List< Type >::size().
resize() [1/2]
void resize (const label nElem) inline
Alter the addressed list size.
New space will be allocated if required. Use this to resize the list prior to using the operator[] for setting values (as per List usage).
Definition at line 257 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null(), and DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize().
resize() [2/2]
void resize (const label nElem, const T & t) inline
Alter the addressed list size and fill new space with a.
constant.
Definition at line 267 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize().
reserve()
void reserve (const label nElem) inline
Reserve allocation space for at least this size.
Never shrinks the allocated size, use setCapacity() for that.
Definition at line 165 of file DynamicFieldI.H.
References Foam::max(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< Type >::setSize(), and List< Type >::size().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null(), and DynamicField< T, SizeInc, SizeMult, SizeDiv >::setCapacity().
clear()
void clear () inline
Clear the addressed list, i.e. set the size to zero.
Allocated size does not change
Definition at line 277 of file DynamicFieldI.H.
References List< Type >::size().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
clearStorage()
void clearStorage () inline
Clear the list and delete storage.
Definition at line 284 of file DynamicFieldI.H.
References List< Type >::clear().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
shrink()
Foam::DynamicField< T, SizeInc, SizeMult, SizeDiv > & shrink () inline
Shrink the allocated space to the number of elements used.
Returns a reference to the DynamicField.
Definition at line 293 of file DynamicFieldI.H.
References List< Type >::setSize(), and List< Type >::size().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
xfer()
Foam::Xfer< Foam::List< T > > xfer () inline
Transfer contents to the Xfer container as a plain List.
Definition at line 312 of file DynamicFieldI.H.
References DynamicField< T, SizeInc, SizeMult, SizeDiv >::append().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
append() [1/2]
Foam::DynamicField< T, SizeInc, SizeMult, SizeDiv > & append (const T & t) inline
Append an element at the end of the list.
Definition at line 321 of file DynamicFieldI.H.
References UList< T >::operator[](), DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize(), and List< T >::size().
Referenced by extendedEdgeMesh::add(), mappedPatchBase::calcMapping(), DynamicField< T, SizeInc, SizeMult, SizeDiv >::null(), and DynamicField< T, SizeInc, SizeMult, SizeDiv >::xfer().
append() [2/2]
Foam::DynamicField< T, SizeInc, SizeMult, SizeDiv > & append (const UList< T > & lst) inline
Append a List at the end of this list.
Definition at line 336 of file DynamicFieldI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, UList< T >::operator[](), DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::size(), and UList< T >::size().
remove()
T remove () inline
Remove and return the top element.
Definition at line 358 of file DynamicFieldI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Field< T >::operator, UList< T >::operator[](), List< T >::size(), and Field< T >::T().
operator()()
T & operator() (const label elemI) inline
Return non-const access to an element, resizing list if.
necessary
Definition at line 380 of file DynamicFieldI.H.
References UList< T >::operator[](), and DynamicField< T, SizeInc, SizeMult, SizeDiv >::setSize().
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
operator=() [1/3]
void operator= (const T & t) inline
Assignment of all addressed entries to the given value.
Definition at line 395 of file DynamicFieldI.H.
Referenced by DynamicField< T, SizeInc, SizeMult, SizeDiv >::null().
operator=() [2/3]
void operator= (const DynamicField< T, SizeInc, SizeMult, SizeDiv > & lst) inline
Assignment to DynamicField.
Definition at line 405 of file DynamicFieldI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Field< Type >::operator=(), List< T >::size(), and List< Type >::size().
operator=() [3/3]
void operator= (const UList< T > & lst) inline
Assignment to UList.
Definition at line 434 of file DynamicFieldI.H.
References Field< Type >::operator=(), List< T >::size(), and List< Type >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/Fields/DynamicField/DynamicField.H
src/OpenFOAM/fields/Fields/DynamicField/DynamicField.C
src/OpenFOAM/fields/Fields/DynamicField/DynamicFieldI.H