OpenFOAM: FieldField< Field, Type > Class Template Reference
FieldField< Field, Type > Class Template Reference
Generic field type.
Public Types
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Public Member Functions
FieldField ()
Construct null.
FieldField (const label)
Construct given size.
FieldField (const word &, const FieldField< Field, Type > &)
Construct using the Field sizes from the given FieldField.
FieldField (const FieldField< Field, Type > &)
Construct as copy.
FieldField (FieldField< Field, Type > &, bool reuse)
Construct as copy or re-use as specified.
FieldField (const PtrList< Field< Type >> &)
Construct as copy of a PtrList<Field, Type>
FieldField (const tmp< FieldField< Field, Type >> &)
Construct as copy of tmp<FieldField>
FieldField (Istream &)
Construct from Istream.
tmp< FieldField< Field, Type > > clone () const
Clone.
void negate ()
Negate this field.
tmp< FieldField< Field, cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const FieldField< Field, cmptType > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< FieldField< Field, Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const FieldField< Field, Type > &)
void operator= (const tmp< FieldField< Field, Type >> &)
void operator= (const Type &)
void operator+= (const FieldField< Field, Type > &)
void operator+= (const tmp< FieldField< Field, Type >> &)
void operator-= (const FieldField< Field, Type > &)
void operator-= (const tmp< FieldField< Field, Type >> &)
void operator*= (const FieldField< Field, scalar > &)
void operator*= (const tmp< FieldField< Field, scalar >> &)
void operator/= (const FieldField< Field, scalar > &)
void operator/= (const tmp< FieldField< Field, scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from PtrList< Field< Type > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< Field< Type > > &)
Copy constructor.
PtrList (const PtrList< Field< Type > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< Field< Type > >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< Field< Type > > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< Field< Type > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (Field< Type > *)
Append an element at the end of the list.
void append (const autoPtr< Field< Type > > &)
void append (const tmp< Field< Type > > &)
void transfer (PtrList< Field< Type > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< Field< Type > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< Field< Type > > set (const label, Field< Type > *)
Set element to given T* and return old element (can be nullptr)
autoPtr< Field< Type > > set (const label, const autoPtr< Field< Type > > &)
Set element to given autoPtr<T> and return old element.
autoPtr< Field< Type > > set (const label, const tmp< Field< Type > > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< Field< Type > > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Static Public Member Functions
template<class Type2 >
static tmp< FieldField< Field, Type > > NewCalculatedType (const FieldField< Field, Type2 > &ff)
Return a pointer to a new calculatedFvPatchFieldField created on.
Friends
Ostream & operator (Ostream &, const FieldField< Field, Type > &)
Ostream & operator (Ostream &, const tmp< FieldField< Field, Type >> &)
Additional Inherited Members
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from PtrList< Field< Type > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
template<template< class > class Field, class Type>
class Foam::FieldField< Field, Type >
Generic field type.
Source files
FieldField.H
FieldField.C
Definition at line 51 of file FieldField.H.
Member Typedef Documentation
cmptType
typedef pTraits<Type>::cmptType cmptType
Component type.
Definition at line 82 of file FieldField.H.
Constructor & Destructor Documentation
FieldField() [1/8]
FieldField ()
Construct null.
Used for temporary fields which are initialised after construction
Definition at line 108 of file FieldField.C.
FieldField() [2/8]
FieldField (const label size) explicit
Construct given size.
Used for temporary fields which are initialised after construction
Definition at line 115 of file FieldField.C.
FieldField() [3/8]
FieldField (const word & type, const FieldField< Field, Type > & ff)
Construct using the Field sizes from the given FieldField.
and the given Field type. Used for temporary fields which are initialised after construction
Definition at line 123 of file FieldField.C.
FieldField() [4/8]
FieldField (const FieldField< Field, Type > & f)
Construct as copy.
Definition at line 138 of file FieldField.C.
FieldField() [5/8]
FieldField (FieldField< Field, Type > & f, bool reuse)
Construct as copy or re-use as specified.
Definition at line 146 of file FieldField.C.
FieldField() [6/8]
FieldField (const PtrList< Field< Type >> & tl)
Construct as copy of a PtrList<Field, Type>
Definition at line 153 of file FieldField.C.
FieldField() [7/8]
FieldField (const tmp< FieldField< Field, Type >> & tf)
Construct as copy of tmp<FieldField>
Definition at line 161 of file FieldField.C.
FieldField() [8/8]
FieldField (Istream & is)
Construct from Istream.
Definition at line 175 of file FieldField.C.
Member Function Documentation
clone()
tmp< FieldField< Field, Type > > clone () const
Clone.
Definition at line 182 of file FieldField.C.
NewCalculatedType()
tmp< FieldField< Field, Type > > NewCalculatedType (const FieldField< Field, Type2 > & ff) static
Return a pointer to a new calculatedFvPatchFieldField created on.
freestore without setting patchField values
Definition at line 191 of file FieldField.C.
Referenced by reuseTmpFieldField< Field, TypeR, Type1 >::New(), reuseTmpFieldField< Field, TypeR, TypeR >::New(), reuseTmpTmpFieldField< Field, TypeR, Type1, Type12, Type2 >::New(), reuseTmpTmpFieldField< Field, TypeR, Type1, Type12, TypeR >::New(), reuseTmpTmpFieldField< Field, TypeR, TypeR, TypeR, Type2 >::New(), and reuseTmpTmpFieldField< Field, TypeR, TypeR, TypeR, TypeR >::New().
negate()
void negate ()
Negate this field.
Definition at line 212 of file FieldField.C.
Referenced by GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), and nonBlockingGaussSeidelSmoother::smooth().
component()
tmp< FieldField< Field, typename FieldField< Field, Type >::cmptType > > component (const direction d) const
Return a component field of the field.
Definition at line 224 of file FieldField.C.
replace() [1/2]
void replace (const direction d, const FieldField< Field, cmptType > & sf)
Replace a component field of the field.
Definition at line 242 of file FieldField.C.
replace() [2/2]
void replace (const direction d, const cmptType & s)
Replace a component field of the field.
Definition at line 256 of file FieldField.C.
T()
tmp< FieldField< Field, Type > > T () const
Return the field transpose (only defined for second rank tensors)
Definition at line 269 of file FieldField.C.
operator=() [1/3]
void operator= (const FieldField< Field, Type > & f)
Definition at line 284 of file FieldField.C.
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::operator=(), and GeometricField< Type, PatchField, GeoMesh >::Boundary::writeEntry().
operator=() [2/3]
void operator= (const tmp< FieldField< Field, Type >> &)
operator=() [3/3]
void operator= (const Type & t)
Definition at line 318 of file FieldField.C.
operator+=() [1/3]
void operator+= (const FieldField< Field, Type > & f)
Definition at line 357 of file FieldField.C.
operator+=() [2/3]
void operator+= (const tmp< FieldField< Field, Type >> & tf)
Definition at line 357 of file FieldField.C.
operator-=() [1/3]
void operator-= (const FieldField< Field, Type > & f)
Definition at line 358 of file FieldField.C.
operator-=() [2/3]
void operator-= (const tmp< FieldField< Field, Type >> & tf)
Definition at line 358 of file FieldField.C.
operator*=() [1/3]
void operator*= (const FieldField< Field, scalar > & f)
Definition at line 359 of file FieldField.C.
operator*=() [2/3]
void operator*= (const tmp< FieldField< Field, scalar >> & tf)
Definition at line 359 of file FieldField.C.
operator/=() [1/3]
void operator/= (const FieldField< Field, scalar > & f)
Definition at line 360 of file FieldField.C.
operator/=() [2/3]
void operator/= (const tmp< FieldField< Field, scalar >> & tf)
Definition at line 360 of file FieldField.C.
operator+=() [3/3]
void operator+= (const Type & t)
Definition at line 357 of file FieldField.C.
operator-=() [3/3]
void operator-= (const Type & t)
Definition at line 358 of file FieldField.C.
operator*=() [3/3]
void operator*= (const scalar & t)
Definition at line 359 of file FieldField.C.
operator/=() [3/3]
void operator/= (const scalar & t)
Definition at line 360 of file FieldField.C.
Friends And Related Function Documentation
operator [1/2]
Ostream& operator (Ostream & , const FieldField< Field, Type > &) friend
operator [2/2]
Ostream& operator (Ostream & , const tmp< FieldField< Field, Type >> &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/FieldFields/FieldField/FieldField.H
src/OpenFOAM/fields/FieldFields/FieldField/FieldField.C