OpenFOAM: reuseTmpDimensionedField< TypeR, TypeR, GeoMesh > Class Template Reference
reuseTmpDimensionedField< TypeR, TypeR, GeoMesh > Class Template Reference
Static Public Member Functions
static tmp< DimensionedField< TypeR, GeoMesh > > New (const tmp< DimensionedField< TypeR, GeoMesh >> &tdf1, const word &name, const dimensionSet &dimensions)
Detailed Description
template<class TypeR, class GeoMesh>
class Foam::reuseTmpDimensionedField< TypeR, TypeR, GeoMesh >
Definition at line 106 of file DimensionedFieldReuseFunctions.H.
Member Function Documentation
New()
static tmp<DimensionedField<TypeR, GeoMesh> > New (const tmp< DimensionedField< TypeR, GeoMesh >> & tdf1, const word & name, const dimensionSet & dimensions) inline static
Definition at line 111 of file DimensionedFieldReuseFunctions.H.
References IOobject::db(), DimensionedField< Type, GeoMesh >::dimensions(), IOobject::instance(), DimensionedField< Type, GeoMesh >::mesh(), and regIOobject::rename().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedFieldReuseFunctions.H