OpenFOAM: directFieldMapper Class Reference
directFieldMapper Class Reference
FieldMapper with direct mapping.
Public Member Functions
patchFieldSubset (const labelUList &directAddressing)
Construct given addressing.
virtual ~directFieldMapper ()
Destructor.
label size () const
bool direct () const
bool hasUnmapped () const
Are there unmapped values? I.e. do all size() elements get.
const labelUList & directAddressing () const
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
FieldMapper with direct mapping.
Definition at line 43 of file directFieldMapper.H.
Constructor & Destructor Documentation
~directFieldMapper()
virtual ~directFieldMapper () inline virtual
Destructor.
Definition at line 68 of file directFieldMapper.H.
Member Function Documentation
patchFieldSubset()
patchFieldSubset (const labelUList & directAddressing) inline
Construct given addressing.
Definition at line 56 of file directFieldMapper.H.
References Foam::min(), and UList< T >::size().
size()
label size () const inline virtual
Implements FieldMapper.
Definition at line 74 of file directFieldMapper.H.
References UList< T >::size().
direct()
bool direct () const inline virtual
Implements FieldMapper.
Definition at line 79 of file directFieldMapper.H.
hasUnmapped()
bool hasUnmapped () const inline virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implements FieldMapper.
Definition at line 84 of file directFieldMapper.H.
directAddressing()
const labelUList& directAddressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 89 of file directFieldMapper.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/Fields/Field/directFieldMapper.H