OpenFOAM: SubDimensionedField< Type, GeoMesh > Class Template Reference
SubDimensionedField< Type, GeoMesh > Class Template Reference
SubDimensionedField is a DimensionedField obtained as a section of another DimensionedField.
Public Types
typedef GeoMesh::Mesh Mesh
typedef Field< Type >::cmptType cmptType
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from SubField< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
SubDimensionedField (const SubField< Type > &slist)
Construct from a SubField.
SubDimensionedField (const UList< Type > &list, const label subSize)
Construct from a UList and size.
SubDimensionedField (const UList< Type > &list, const label subSize, const label startIndex)
Construct from a UList start and end indices.
SubDimensionedField (const SubDimensionedField< cmptType, GeoMesh > &sfield)
Construct as copy.
tmp< DimensionedField< cmptType, GeoMesh > > component (const direction) const
Return a component field of the field.
tmp< DimensionedField< Type, GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const SubDimensionedField< Type, GeoMesh > &)
Assignment.
operator const DimensionedField< Type, GeoMesh > & () const
Allow cast to a const DimensionedField<Type, GeoMesh>&.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeData (Ostream &) const =0
Pure virtual writaData function.
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from SubField< Type >
SubField (const SubList< Type > &)
Construct from a SubList.
SubField (const UList< Type > &)
Construct from a UList<Type>, using the entire size.
SubField (const UList< Type > &list, const label subSize)
Construct from a UList<Type> with a given size.
SubField (const UList< Type > &list, const label subSize, const label startIndex)
Construct from a UList<Type> with a given size and start index.
SubField (const SubField< Type > &)
Construct as copy.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const SubField< Type > &)
Assignment via UList operator. Takes linear time.
void operator= (const Field< Type > &)
Assignment via UList operator. Takes linear time.
template<class Form , direction Ncmpts>
void operator= (const VectorSpace< Form, Type, Ncmpts > &)
Assignment via UList operator. Takes linear time.
operator const Field< Type > & () const
Allow cast to a const Field<Type>&.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from SubList< Type >
SubList (const UList< Type > &list, const label subSize)
Construct from UList and sub-list size.
SubList (const UList< Type > &list, const label subSize, const label startIndex)
Construct from UList, sub-list size and start index.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
void operator= (const SubList< Type > &)
Assignment of all entries to the given sub-list.
void operator= (const UList< Type > &)
Assignment of all entries to the given list.
void operator= (const Type &)
Assignment of all entries to the given value.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static const SubDimensionedField< Type, GeoMesh > & null ()
Return a null SubDimensionedField.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from SubField< Type >
static const SubField< Type > & null ()
Return a null SubField.
Static Public Member Functions inherited from SubList< Type >
static const SubList< Type > & null ()
Return a null SubList.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Additional Inherited Members
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Type, class GeoMesh>
class Foam::SubDimensionedField< Type, GeoMesh >
SubDimensionedField is a DimensionedField obtained as a section of another DimensionedField.
Thus it is itself unallocated so that no storage is allocated or deallocated during its use. To achieve this behaviour, SubDimensionedField is derived from SubField rather than Field.
Source files
SubDimensionedField.H
SubDimensionedFieldI.H
Definition at line 55 of file SubDimensionedField.H.
Member Typedef Documentation
Mesh
typedef GeoMesh::Mesh Mesh
Definition at line 65 of file SubDimensionedField.H.
cmptType
typedef Field<Type>::cmptType cmptType
Definition at line 66 of file SubDimensionedField.H.
Constructor & Destructor Documentation
SubDimensionedField() [1/4]
SubDimensionedField (const SubField< Type > & slist) inline
Construct from a SubField.
Definition at line 30 of file SubDimensionedFieldI.H.
Referenced by SubDimensionedField< Type, GeoMesh >::SubDimensionedField().
SubDimensionedField() [2/4]
SubDimensionedField (const UList< Type > & list, const label subSize) inline
Construct from a UList and size.
Definition at line 39 of file SubDimensionedFieldI.H.
References SubDimensionedField< Type, GeoMesh >::SubDimensionedField().
SubDimensionedField() [3/4]
SubDimensionedField (const UList< Type > & list, const label subSize, const label startIndex) inline
Construct from a UList start and end indices.
Definition at line 50 of file SubDimensionedFieldI.H.
References SubDimensionedField< Type, GeoMesh >::SubDimensionedField().
SubDimensionedField() [4/4]
SubDimensionedField (const SubDimensionedField< cmptType, GeoMesh > & sfield) inline
Construct as copy.
Member Function Documentation
null()
const Foam::SubDimensionedField< Type, GeoMesh > & null () inline static
Return a null SubDimensionedField.
Definition at line 75 of file SubDimensionedFieldI.H.
References SubDimensionedField< Type, GeoMesh >::component().
component()
tmp<DimensionedField<cmptType, GeoMesh> > component (const direction) const inline
Return a component field of the field.
Referenced by SubDimensionedField< Type, GeoMesh >::null().
T()
Foam::tmp< Foam::DimensionedField< Type, GeoMesh > > T () const inline
Return the field transpose (only defined for second rank tensors)
Definition at line 101 of file SubDimensionedFieldI.H.
operator=()
void operator= (const SubDimensionedField< Type, GeoMesh > & rhs) inline
Assignment.
Definition at line 114 of file SubDimensionedFieldI.H.
operator const DimensionedField< Type, GeoMesh > &()
operator const DimensionedField< Type, GeoMesh > & () const inline
Allow cast to a const DimensionedField<Type, GeoMesh>&.
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/DimensionedFields/DimensionedField/SubDimensionedField.H
src/OpenFOAM/fields/DimensionedFields/DimensionedField/SubDimensionedFieldI.H