OpenFOAM: geometricZeroField Class Reference
geometricZeroField Class Reference
A class representing the concept of a GeometricField of 1 used to avoid unnecessary manipulations for objects which are known to be zero at compile-time.
Public Member Functions
geometricZeroField ()
Construct null.
const dimensionSet & dimensions () const
scalar operator[] (const label) const
zeroField field () const
zeroField oldTime () const
zeroFieldField boundaryField () const
Public Member Functions inherited from zero
zero ()
Construct null.
operator bool () const
Return 0 for bool.
operator label () const
Return 0 for label.
operator float () const
Return 0 for float.
operator double () const
Return 0 for double.
Additional Inherited Members
Public Types inherited from zero
typedef zero value_type
Detailed Description
A class representing the concept of a GeometricField of 1 used to avoid unnecessary manipulations for objects which are known to be zero at compile-time.
Used for example as the density argument to a function written for compressible to be used for incompressible flow.
Definition at line 52 of file geometricZeroField.H.
Constructor & Destructor Documentation
geometricZeroField()
geometricZeroField () inline
Construct null.
Definition at line 62 of file geometricZeroField.H.
References geometricZeroField::boundaryField(), geometricZeroField::dimensions(), geometricZeroField::field(), geometricZeroField::oldTime(), and geometricZeroField::operator[]().
Member Function Documentation
dimensions()
const Foam::dimensionSet & dimensions () const inline
Definition at line 30 of file geometricZeroFieldI.H.
References Foam::dimless.
Referenced by geometricZeroField::geometricZeroField().
operator[]()
Foam::scalar operator[] (const label) const inline
Definition at line 35 of file geometricZeroFieldI.H.
Referenced by geometricZeroField::geometricZeroField().
field()
Foam::zeroField field () const inline
Definition at line 40 of file geometricZeroFieldI.H.
Referenced by geometricZeroField::geometricZeroField().
oldTime()
Foam::zeroField oldTime () const inline
Definition at line 45 of file geometricZeroFieldI.H.
Referenced by geometricZeroField::geometricZeroField().
boundaryField()
Foam::zeroFieldField boundaryField () const inline
Definition at line 50 of file geometricZeroFieldI.H.
Referenced by geometricZeroField::geometricZeroField().
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/GeometricFields/geometricZeroField/geometricZeroField.H
src/OpenFOAM/fields/GeometricFields/geometricZeroField/geometricZeroFieldI.H