OpenFOAM: geometricOneField Class Reference
geometricOneField Class Reference
A class representing the concept of a GeometricField of 1 used to avoid unnecessary manipulations for objects which are known to be one at compile-time.
Public Types
typedef oneField Internal
typedef oneField Patch
typedef oneFieldField Boundary
typedef one cmptType
Public Types inherited from one
typedef one value_type
Public Member Functions
geometricOneField ()
Construct null.
const dimensionSet & dimensions () const
one operator[] (const label) const
oneField field () const
oneField oldTime () const
Internal operator() () const
Internal v () const
Internal::FieldType primitiveField () const
Boundary boundaryField () const
Public Member Functions inherited from one
one ()
Construct null.
operator label () const
Return 1 for label.
operator float () const
Return 1 for float.
operator double () const
Return 1 for double.
Detailed Description
A class representing the concept of a GeometricField of 1 used to avoid unnecessary manipulations for objects which are known to be one at compile-time.
Used for example as the density argument to a function written for compressible to be used for incompressible flow.
Definition at line 52 of file geometricOneField.H.
Member Typedef Documentation
Internal
typedef oneField Internal
Definition at line 61 of file geometricOneField.H.
Patch
typedef oneField Patch
Definition at line 62 of file geometricOneField.H.
Boundary
typedef oneFieldField Boundary
Definition at line 63 of file geometricOneField.H.
cmptType
typedef one cmptType
Definition at line 64 of file geometricOneField.H.
Constructor & Destructor Documentation
geometricOneField()
geometricOneField () inline
Construct null.
Definition at line 69 of file geometricOneField.H.
References geometricOneField::boundaryField(), geometricOneField::dimensions(), geometricOneField::field(), geometricOneField::oldTime(), geometricOneField::operator()(), geometricOneField::operator[](), geometricOneField::primitiveField(), and geometricOneField::v().
Member Function Documentation
dimensions()
const Foam::dimensionSet & dimensions () const inline
Definition at line 30 of file geometricOneFieldI.H.
References Foam::dimless.
Referenced by geometricOneField::geometricOneField().
operator[]()
Foam::one operator[] (const label) const inline
Definition at line 36 of file geometricOneFieldI.H.
References one::one().
Referenced by geometricOneField::geometricOneField().
field()
Foam::oneField field () const inline
Definition at line 42 of file geometricOneFieldI.H.
Referenced by geometricOneField::geometricOneField().
oldTime()
Foam::oneField oldTime () const inline
Definition at line 48 of file geometricOneFieldI.H.
Referenced by geometricOneField::geometricOneField().
operator()()
Foam::geometricOneField::Internal operator() () const inline
Definition at line 55 of file geometricOneFieldI.H.
Referenced by geometricOneField::geometricOneField().
v()
Foam::geometricOneField::Internal v () const inline
Definition at line 62 of file geometricOneFieldI.H.
Referenced by geometricOneField::geometricOneField().
primitiveField()
Foam::geometricOneField::Internal::FieldType primitiveField () const inline
Definition at line 69 of file geometricOneFieldI.H.
Referenced by geometricOneField::geometricOneField().
boundaryField()
Foam::geometricOneField::Boundary boundaryField () const inline
Definition at line 76 of file geometricOneFieldI.H.
Referenced by geometricOneField::geometricOneField().
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/GeometricFields/geometricOneField/geometricOneField.H
src/OpenFOAM/fields/GeometricFields/geometricOneField/geometricOneFieldI.H