OpenFOAM: basicSymmetryPointPatchField< Type > Class Template Reference
basicSymmetryPointPatchField< Type > Class Template Reference
A Symmetry boundary condition for pointField.
Public Member Functions
basicSymmetryPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
basicSymmetryPointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
basicSymmetryPointPatchField (const basicSymmetryPointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
virtual autoPtr< pointPatchField< Type > > clone () const
Construct and return a clone.
basicSymmetryPointPatchField (const basicSymmetryPointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Update the patch field.
Public Member Functions inherited from pointPatchField< Type >
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType &>(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual ~pointPatchField ()
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type, pointMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void write (Ostream &) const
Write.
template<class EntryType >
void writeEntryIfDifferent (Ostream &os, const word &entryName, const EntryType &value1, const EntryType &value2) const
Helper function to write the keyword and entry only if the.
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
template<class Type2 >
Foam::autoPtr< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Additional Inherited Members
Public Types inherited from pointPatchField< Type >
typedef pointPatch Patch
typedef calculatedPointPatchField< Type > Calculated
Static Public Member Functions inherited from pointPatchField< Type >
static autoPtr< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
template<class Type2 >
static autoPtr< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new calculatedPointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Attributes inherited from pointPatchField< Type >
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Detailed Description
template<class Type>
class Foam::basicSymmetryPointPatchField< Type >
A Symmetry boundary condition for pointField.
Source files
basicSymmetryPointPatchField.H
basicsymmetryPointPatchField.C
Definition at line 50 of file basicSymmetryPointPatchField.H.
Constructor & Destructor Documentation
basicSymmetryPointPatchField() [1/4]
basicSymmetryPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file basicSymmetryPointPatchField.C.
Referenced by basicSymmetryPointPatchField< Type >::basicSymmetryPointPatchField(), and basicSymmetryPointPatchField< Type >::clone().
basicSymmetryPointPatchField() [2/4]
basicSymmetryPointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 46 of file basicSymmetryPointPatchField.C.
References basicSymmetryPointPatchField< Type >::basicSymmetryPointPatchField().
basicSymmetryPointPatchField() [3/4]
basicSymmetryPointPatchField (const basicSymmetryPointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & mapper)
Construct by mapping given patchField<Type> onto a new patch.
Definition at line 58 of file basicSymmetryPointPatchField.C.
References basicSymmetryPointPatchField< Type >::basicSymmetryPointPatchField().
basicSymmetryPointPatchField() [4/4]
basicSymmetryPointPatchField (const basicSymmetryPointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 71 of file basicSymmetryPointPatchField.C.
References basicSymmetryPointPatchField< Type >::evaluate().
Member Function Documentation
clone() [1/2]
virtual autoPtr<pointPatchField<Type> > clone () const inline virtual
Construct and return a clone.
Implements pointPatchField< Type >.
Reimplemented in fixedNormalSlipPointPatchField< Type >, symmetryPlanePointPatchField< Type >, symmetryPointPatchField< Type >, and slipPointPatchField< Type >.
Definition at line 84 of file basicSymmetryPointPatchField.H.
References basicSymmetryPointPatchField< Type >::basicSymmetryPointPatchField().
clone() [2/2]
virtual autoPtr<pointPatchField<Type> > clone (const DimensionedField< Type, pointMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Implements pointPatchField< Type >.
Reimplemented in fixedNormalSlipPointPatchField< Type >, symmetryPlanePointPatchField< Type >, symmetryPointPatchField< Type >, and slipPointPatchField< Type >.
Definition at line 104 of file basicSymmetryPointPatchField.H.
References UPstream::blocking, and basicSymmetryPointPatchField< Type >::evaluate().
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Update the patch field.
Reimplemented from pointPatchField< Type >.
Reimplemented in fixedNormalSlipPointPatchField< Type >, and symmetryPlanePointPatchField< Type >.
Definition at line 84 of file basicSymmetryPointPatchField.C.
References Foam::I, Foam::sqr(), and Foam::transform().
Referenced by basicSymmetryPointPatchField< Type >::basicSymmetryPointPatchField(), and basicSymmetryPointPatchField< Type >::clone().
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/pointPatchFields/basic/basicSymmetry/basicSymmetryPointPatchField.H
src/OpenFOAM/fields/pointPatchFields/basic/basicSymmetry/basicSymmetryPointPatchField.C