OpenFOAM: oneField Class Reference
oneField Class Reference
A class representing the concept of a field of 1 used to avoid unnecessary manipulations for objects which are known to be one at compile-time.
Public Types
typedef oneField FieldType
Public Types inherited from one
typedef one value_type
Public Member Functions
oneField ()
Construct null.
one operator[] (const label) const
oneField field () const
Public Member Functions inherited from one
one ()
Construct null.
operator label () const
Return 1 for label.
operator float () const
Return 1 for float.
operator double () const
Return 1 for double.
Detailed Description
A class representing the concept of a field of 1 used to avoid unnecessary manipulations for objects which are known to be one at compile-time.
Used for example as the density argument to a function written for compressible to be used for incompressible flow.
Definition at line 50 of file oneField.H.
Member Typedef Documentation
FieldType
typedef oneField FieldType
Definition at line 59 of file oneField.H.
Constructor & Destructor Documentation
oneField()
oneField () inline
Construct null.
Definition at line 65 of file oneField.H.
References oneField::field(), Foam::operator*(), Foam::operator/(), and oneField::operator[]().
Referenced by oneField::field().
Member Function Documentation
operator[]()
Foam::one operator[] (const label) const inline
Definition at line 30 of file oneFieldI.H.
References one::one().
Referenced by oneField::oneField().
field()
Foam::oneField field () const inline
Definition at line 36 of file oneFieldI.H.
References oneField::oneField().
Referenced by oneField::oneField().
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/Fields/oneField/oneField.H
src/OpenFOAM/fields/Fields/oneField/oneFieldI.H