OpenFOAM: GeometricField< Type, PatchField, GeoMesh >::Boundary Class Reference
GeometricField< Type, PatchField, GeoMesh >::Boundary Class Reference
Public Member Functions
Boundary (const BoundaryMesh &)
Construct from a BoundaryMesh.
Boundary (const BoundaryMesh &, const Internal &, const word &)
Construct from a BoundaryMesh,.
Boundary (const BoundaryMesh &, const Internal &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Construct from a BoundaryMesh,.
Boundary (const BoundaryMesh &, const Internal &, const PtrList< PatchField< Type >> &)
Construct from a BoundaryMesh,.
Boundary (const Internal &, const Boundary &)
Construct as copy setting the reference to the internal field.
Boundary (const Boundary &)
Construct as copy.
Boundary (const BoundaryMesh &, const Internal &, const dictionary &)
Construct from dictionary.
void readField (const Internal &field, const dictionary &dict)
Read the boundary field.
void updateCoeffs ()
Update the boundary condition coefficients.
void evaluate ()
Evaluate boundary conditions.
wordList types () const
Return a list of the patch types.
Boundary boundaryInternalField () const
Return BoundaryField of the cell values neighbouring.
LduInterfaceFieldPtrsList< Type > interfaces () const
Return a list of pointers for each patch field with only those.
lduInterfaceFieldPtrsList scalarInterfaces () const
Return a list of pointers for each patch field with only those.
void writeEntry (const word &keyword, Ostream &os) const
Write boundary field as dictionary entry.
void operator= (const Boundary &)
Assignment to BoundaryField<Type, PatchField, BoundaryMesh>
void operator= (const FieldField< PatchField, Type > &)
Assignment to FieldField<PatchField, Type>
void operator= (const Type &)
Assignment to Type.
void operator== (const Boundary &)
Forced assignment to.
void operator== (const FieldField< PatchField, Type > &)
Forced assignment to FieldField<PatchField, Type>
void operator== (const Type &)
Forced assignment to Type.
Public Member Functions inherited from FieldField< PatchField, Type >
FieldField ()
Construct null.
FieldField (const label)
Construct given size.
FieldField (const word &, const FieldField< PatchField, Type > &)
Construct using the Field sizes from the given FieldField.
FieldField (const FieldField< PatchField, Type > &)
Construct as copy.
FieldField (FieldField< PatchField, Type > &, bool reuse)
Construct as copy or re-use as specified.
FieldField (const PtrList< PatchField< Type >> &)
Construct as copy of a PtrList<Field, Type>
FieldField (const tmp< FieldField< PatchField, Type >> &)
Construct as copy of tmp<FieldField>
FieldField (Istream &)
Construct from Istream.
tmp< FieldField< PatchField, Type > > clone () const
Clone.
void negate ()
Negate this field.
tmp< FieldField< PatchField, cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const FieldField< PatchField, cmptType > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< FieldField< PatchField, Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const FieldField< PatchField, Type > &)
void operator= (const tmp< FieldField< PatchField, Type >> &)
void operator= (const Type &)
void operator+= (const FieldField< PatchField, Type > &)
void operator+= (const tmp< FieldField< PatchField, Type >> &)
void operator+= (const Type &)
void operator-= (const FieldField< PatchField, Type > &)
void operator-= (const tmp< FieldField< PatchField, Type >> &)
void operator-= (const Type &)
void operator*= (const FieldField< PatchField, scalar > &)
void operator*= (const tmp< FieldField< PatchField, scalar >> &)
void operator*= (const scalar &)
void operator/= (const FieldField< PatchField, scalar > &)
void operator/= (const tmp< FieldField< PatchField, scalar >> &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from PtrList< PatchField< Type > >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< PatchField< Type > > &)
Copy constructor.
PtrList (const PtrList< PatchField< Type > > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< PatchField< Type > >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< PatchField< Type > > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< PatchField< Type > > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (PatchField< Type > *)
Append an element at the end of the list.
void append (const autoPtr< PatchField< Type > > &)
void append (const tmp< PatchField< Type > > &)
void transfer (PtrList< PatchField< Type > > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< PatchField< Type > > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< PatchField< Type > > set (const label, PatchField< Type > *)
Set element to given T* and return old element (can be nullptr)
autoPtr< PatchField< Type > > set (const label, const autoPtr< PatchField< Type > > &)
Set element to given autoPtr<T> and return old element.
autoPtr< PatchField< Type > > set (const label, const tmp< PatchField< Type > > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< PatchField< Type > > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from FieldField< PatchField, Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Static Public Member Functions inherited from FieldField< PatchField, Type >
static tmp< FieldField< PatchField, Type > > NewCalculatedType (const FieldField< PatchField, Type2 > &ff)
Return a pointer to a new calculatedFvPatchFieldField created on.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from PtrList< PatchField< Type > >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
template<class Type, template< class > class PatchField, class GeoMesh>
class Foam::GeometricField< Type, PatchField, GeoMesh >::Boundary
Definition at line 112 of file GeometricField.H.
Constructor & Destructor Documentation
Boundary() [1/7]
Boundary (const BoundaryMesh & bmesh)
Construct from a BoundaryMesh.
Definition at line 204 of file GeometricBoundaryField.C.
References Foam::abort(), DimensionedField< Type, GeoMesh >::clone(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, InfoInFunction, Foam::New(), Foam::nl, patchi, List< T >::size(), List< Type >::size(), and GeometricField< Type, PatchField, GeoMesh >::Boundary::updateCoeffs().
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::readField().
Boundary() [2/7]
Boundary (const BoundaryMesh & , const Internal & , const word &)
Construct from a BoundaryMesh,.
reference to the internal field and a patch type
Boundary() [3/7]
Boundary (const BoundaryMesh & , const Internal & , const wordList & wantedPatchTypes, const wordList & actualPatchTypes = wordList())
Construct from a BoundaryMesh,.
reference to the internal field and a wordList of patch types and optional the actual patch types (to override constraint patches)
Boundary() [4/7]
Boundary (const BoundaryMesh & , const Internal & , const PtrList< PatchField< Type >> &)
Construct from a BoundaryMesh,.
reference to the internal field and a PtrList<PatchField<Type>>
Boundary() [5/7]
Boundary (const Internal & , const Boundary &)
Construct as copy setting the reference to the internal field.
Boundary() [6/7]
Boundary (const Boundary &)
Construct as copy.
Dangerous because Field may be set to a field which gets deleted Need new type of BoundaryField, one which is part of a geometric field for which snGrad etc. may be called and a free standing BoundaryField for which such operations are unavailable.
Boundary() [7/7]
Boundary (const BoundaryMesh & , const Internal & , const dictionary &)
Construct from dictionary.
Member Function Documentation
readField()
void readField (const Internal & field, const dictionary & dict)
Read the boundary field.
Definition at line 34 of file GeometricBoundaryField.C.
References GeometricField< Type, PatchField, GeoMesh >::Boundary::Boundary(), clear(), dict, entry::dict(), Foam::constant::electromagnetic::e, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, forAllConstIter(), found, dictionary::found(), InfoInFunction, entry::isDict(), keyType::isPattern(), entry::keyword(), Foam::name(), Foam::New(), patchi, UILList< LListBase, T >::rbegin(), UILList< LListBase, T >::rend(), setSize(), dictionary::subDict(), and Foam::type().
updateCoeffs()
void updateCoeffs ()
Update the boundary condition coefficients.
Definition at line 400 of file GeometricBoundaryField.C.
References Foam::endl(), GeometricField< Type, PatchField, GeoMesh >::Boundary::evaluate(), forAll, InfoInFunction, UPtrList< T >::operator[](), and patchi.
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::Boundary().
evaluate()
void evaluate ()
Evaluate boundary conditions.
Definition at line 416 of file GeometricBoundaryField.C.
References UPstream::blocking, UPstream::commsTypeNames, UPstream::defaultCommsType, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, InfoInFunction, UPstream::nonBlocking, UPstream::nRequests(), UPtrList< T >::operator[](), UPstream::parRun(), patchi, UPstream::scheduled, GeometricField< Type, PatchField, GeoMesh >::Boundary::types(), and UPstream::waitRequests().
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::updateCoeffs().
types()
Foam::wordList types () const
Return a list of the patch types.
Definition at line 483 of file GeometricBoundaryField.C.
References GeometricField< Type, PatchField, GeoMesh >::Boundary::boundaryInternalField(), forAll, patchi, and UPtrList< T >::size().
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::evaluate().
boundaryInternalField()
Foam::GeometricField< Type, PatchField, GeoMesh >::Boundary boundaryInternalField () const
Return BoundaryField of the cell values neighbouring.
the boundary
Definition at line 501 of file GeometricBoundaryField.C.
References forAll, GeometricField< Type, PatchField, GeoMesh >::Boundary::interfaces(), UPtrList< T >::operator[](), and patchi.
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::types().
interfaces()
Foam::LduInterfaceFieldPtrsList< Type > interfaces () const
Return a list of pointers for each patch field with only those.
pointing to interfaces being set
Definition at line 519 of file GeometricBoundaryField.C.
References forAll, Foam::isA(), patchi, Foam::refCast(), GeometricField< Type, PatchField, GeoMesh >::Boundary::scalarInterfaces(), UPtrList< const LduInterfaceField< Type > >::set(), and UPtrList< T >::size().
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::boundaryInternalField(), and GeometricField< Type, PatchField, GeoMesh >::Boundary::scalarInterfaces().
scalarInterfaces()
Foam::lduInterfaceFieldPtrsList scalarInterfaces () const
Return a list of pointers for each patch field with only those.
pointing to interfaces being set
Definition at line 545 of file GeometricBoundaryField.C.
References forAll, GeometricField< Type, PatchField, GeoMesh >::Boundary::interfaces(), patchi, UPtrList< T >::set(), UPtrList< T >::size(), and GeometricField< Type, PatchField, GeoMesh >::Boundary::writeEntry().
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::interfaces().
writeEntry()
void writeEntry (const word & keyword, Ostream & os) const
Write boundary field as dictionary entry.
Definition at line 570 of file GeometricBoundaryField.C.
References token::BEGIN_BLOCK, IOstream::check(), Foam::decrIndent(), token::END_BLOCK, Foam::endl(), forAll, Foam::incrIndent(), Foam::indent(), Foam::nl, FieldField< PatchField, Type >::operator, FieldField< Field, Type >::operator=(), UPtrList< T >::operator[](), and patchi.
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::scalarInterfaces().
operator=() [1/3]
void operator= (const Boundary &)
Assignment to BoundaryField<Type, PatchField, BoundaryMesh>
operator=() [2/3]
void operator= (const FieldField< PatchField, Type > & ptff)
Assignment to FieldField<PatchField, Type>
Definition at line 610 of file GeometricBoundaryField.C.
References FieldField< PatchField, Type >::operator, and FieldField< Field, Type >::operator=().
operator=() [3/3]
void operator= (const Type & t)
Assignment to Type.
Definition at line 621 of file GeometricBoundaryField.C.
References forAll, FieldField< PatchField, Type >::operator, FieldField< Field, Type >::operator=(), UPtrList< T >::operator[](), and patchi.
operator==() [1/3]
void operator== (const Boundary &)
Forced assignment to.
BoundaryField<Type, PatchField, BoundaryMesh>
operator==() [2/3]
void operator== (const FieldField< PatchField, Type > & ptff)
Forced assignment to FieldField<PatchField, Type>
Definition at line 647 of file GeometricBoundaryField.C.
References forAll, FieldField< PatchField, Type >::operator, UPtrList< T >::operator[](), and patchi.
operator==() [3/3]
void operator== (const Type & t)
Forced assignment to Type.
Definition at line 661 of file GeometricBoundaryField.C.
References forAll, UPtrList< T >::operator[](), and patchi.
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricField.H
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricBoundaryField.C