OpenFOAM: simpleRegIOobject Class Reference
simpleRegIOobject Class Reference abstract
Abstract base class for registered object with I/O. Used in debug symbol registration.
Public Member Functions
simpleRegIOobject (void(*fn)(const char *name, simpleRegIOobject *), const char *name)
Construct from objectregistry inserter and name.
virtual ~simpleRegIOobject ()
Destructor.
virtual void readData (Istream &)=0
Read.
virtual void writeData (Ostream &) const =0
Write.
Detailed Description
Abstract base class for registered object with I/O. Used in debug symbol registration.
Source files
simpleRegIOobject.H
Definition at line 50 of file simpleRegIOobject.H.
Constructor & Destructor Documentation
simpleRegIOobject()
simpleRegIOobject (void(*)(const char *name, simpleRegIOobject *) fn, const char * name) inline
Construct from objectregistry inserter and name.
Definition at line 58 of file simpleRegIOobject.H.
References Foam::name().
~simpleRegIOobject()
virtual ~simpleRegIOobject () inline virtual
Destructor.
Definition at line 68 of file simpleRegIOobject.H.
References simpleRegIOobject::readData(), and simpleRegIOobject::writeData().
Member Function Documentation
readData()
virtual void readData (Istream &) pure virtual
Read.
Implemented in addcommsTypeToOpt, addfileModificationCheckingToOpt, RegisterSwitch< Type >, addDimensionSetsToDebug, RegisterDebugSwitch< Type >, addstopAtWriteNowSignalToOpt, and addwriteNowSignalToOpt.
Referenced by simpleRegIOobject::~simpleRegIOobject().
writeData()
virtual void writeData (Ostream &) const pure virtual
Write.
Implemented in addcommsTypeToOpt, addfileModificationCheckingToOpt, RegisterSwitch< Type >, addDimensionSetsToDebug, RegisterDebugSwitch< Type >, addstopAtWriteNowSignalToOpt, and addwriteNowSignalToOpt.
Referenced by simpleRegIOobject::~simpleRegIOobject().
The documentation for this class was generated from the following file:
src/OpenFOAM/global/debug/simpleRegIOobject.H