OpenFOAM: argList Class Reference
argList Class Reference
Extract command arguments and options from the supplied argc and argv parameters.
Public Member Functions
argList (int &argc, char **&argv, bool checkArgs=true, bool checkOpts=true, bool initialise=true)
Construct from argc and argv.
argList (const argList &args, const HashTable< string > &options, bool checkArgs=true, bool checkOpts=true, bool initialise=true)
Construct copy with new options.
virtual ~argList ()
Destructor.
void parse (bool checkArgs, bool checkOpts, bool initialise)
Parse.
const word & executable () const
Name of executable without the path.
const fileName & rootPath () const
Return root path.
const fileName & caseName () const
Return case name (parallel run) or global case (serial run)
const fileName & globalCaseName () const
Return case name.
const ParRunControl & parRunControl () const
Return parRunControl.
fileName path () const
Return the path to the caseName.
const stringList & args () const
Return arguments.
stringList & args ()
Return non-const access to arguments.
const string & arg (const label index) const
Return the argument corresponding to index.
label size () const
Return the number of arguments.
template<class T >
T argRead (const label index) const
Read a value from the argument at index.
const Foam::HashTable< string > & options () const
Return options.
Foam::HashTable< string > & options ()
Return non-const access to options.
const string & option (const word &opt) const
Return the argument string associated with the named option.
bool optionFound (const word &opt) const
Return true if the named option is found.
IStringStream optionLookup (const word &opt) const
Return an IStringStream from the named option.
template<class T >
T optionRead (const word &opt) const
Read a value from the named option.
template<class T >
bool optionReadIfPresent (const word &opt, T &) const
Read a value from the named option if present.
template<class T >
bool optionReadIfPresent (const word &opt, T &, const T &deflt) const
Read a value from the named option if present.
template<class T >
T optionLookupOrDefault (const word &opt, const T &deflt) const
Read a value from the named option if present.
template<class T >
List< T > optionReadList (const word &opt) const
Read a List of values from the named option.
const string & operator[] (const label index) const
Return the argument corresponding to index.
const string & operator[] (const word &opt) const
Return the argument string associated with the named option.
bool setOption (const word &opt, const string &param="")
Set option directly (use with caution)
bool unsetOption (const word &opt)
Unset option directly (use with caution)
void printNotes () const
Print notes (if any)
void printUsage () const
Print usage.
void displayDoc (bool source=false) const
Display documentation in browser.
bool check (bool checkArgs=true, bool checkOpts=true) const
Check argument list.
bool checkRootCase () const
Check root path and case path.
Static Public Member Functions
static void addBoolOption (const word &opt, const string &usage="")
Add to a bool option to validOptions with usage information.
static void addOption (const word &opt, const string &param="", const string &usage="")
Add to an option to validOptions with usage information.
static void addUsage (const word &opt, const string &usage)
Add option usage information to optionUsage.
static void addNote (const string &)
Add extra notes for the usage information.
static void removeOption (const word &opt)
Remove option from validOptions and from optionUsage.
static void noBanner ()
Disable emitting the banner information.
static void noParallel ()
Remove the parallel options.
static bool postProcess (int argc, char *argv[])
Return true if the post-processing option is specified.
Static Public Attributes
static SLList< string > validArgs
A list of valid (mandatory) arguments.
static HashTable< string > validOptions
A list of valid options.
static HashTable< string > validParOptions
A list of valid parallel options.
static HashTable< string > optionUsage
Short usage information for validOptions.
static SLList< string > notes
Additional notes for usage.
static string::size_type usageMin = 20
Min offset for displaying usage (default: 20)
static string::size_type usageMax = 80
Max screen width for displaying usage (default: 80)
static word postProcessOptionName
Standard name for the post-processing option.
Detailed Description
Extract command arguments and options from the supplied argc and argv parameters.
Sequences with "(" ... ")" are transformed into a stringList. For example,
    program -listFiles \( *.txt \)
would create a stringList:
    ( "file1.txt" "file2.txt" ... "fileN.txt" )
The backslash-escaping is required to avoid interpretation by the shell.
Default command-line options:
-case <dir>
Select a case directory instead of the current working directory
-parallel
Specify case as a parallel job
-doc
Display the documentation in browser
-srcDoc
Display the source documentation in browser
-help
Print the usage
The environment variable FOAM_CASE is set to the path of the global case (same for serial and parallel jobs). The environment variable FOAM_CASENAME is set to the name of the global case.
Note
The document browser used is defined by the FOAM_DOC_BROWSER environment variable or the Documentation/docBrowser entry in the ~OpenFOAM/controlDict file. The %f token is used as a placeholder for the file name.
The valid (mandatory) arguments can be adjusted by directly manipulating the argList::validArgs static member.
The valid options can be adjusted via the addOption/removeOption static methods instead of directly manipulating the argList::validOptions static member.
Source files
argList.H
argList.C
argListI.H
Definition at line 102 of file argList.H.
Constructor & Destructor Documentation
argList() [1/2]
argList (int & argc, char **& argv, bool checkArgs = true, bool checkOpts = true, bool initialise = true)
Construct from argc and argv.
checking the arguments and options as requested
Definition at line 386 of file argList.C.
References Foam::endl(), error::exit(), Foam::FatalError, fileName::name(), argList::parse(), argList::printUsage(), ParRunControl::runPar(), List< T >::setSize(), List< T >::size(), argList::validOptions, and argList::validParOptions.
Referenced by argList::postProcess().
argList() [2/2]
argList (const argList & args, const HashTable< string > & options, bool checkArgs = true, bool checkOpts = true, bool initialise = true)
Construct copy with new options.
Definition at line 482 of file argList.C.
References argList::parse().
~argList()
~argList () virtual
Destructor.
Definition at line 901 of file argList.C.
References Foam::jobInfo.
Member Function Documentation
parse()
void parse (bool checkArgs, bool checkOpts, bool initialise)
Parse.
Definition at line 504 of file argList.C.
References dictionary::add(), dynamicCode::allowSystemOperations, argList::check(), clock::clockTime(), UPstream::commsTypeNames, Foam::cwd(), clock::date(), UPstream::defaultCommsType, argList::displayDoc(), Foam::endl(), argList::executable(), Foam::exit(), error::exit(), Foam::FatalError, FatalErrorIn, regIOobject::fileCheckTypesNames, regIOobject::fileModificationChecking, UPstream::firstSlave(), UPstream::floatTransfer, Foam::FOAMbuild, Foam::FOAMversion, forAll, found, IOstream::good(), Foam::hostName(), Foam::Info, Foam::isDir(), Foam::jobInfo, UPstream::lastSlave(), dictionary::lookup(), dictionary::lookupOrDefault(), UPstream::master(), UPstream::masterNo(), UPstream::myProcNo(), IFstream::name(), Foam::name(), Foam::nl, UPstream::nPollProcInterfaces, UPstream::nProcs(), UPstream::nProcsSimpleSum, ParRunControl::parRun(), Foam::pgid(), Foam::pid(), Foam::ppid(), argList::printUsage(), Foam::readLabel(), UPstream::scheduled, sigInt::set(), sigSegv::set(), sigQuit::set(), sigFpe::set(), List< T >::setSize(), List< T >::size(), Foam::userName(), IOobject::writeBanner(), and IOobject::writeDivider().
Referenced by argList::argList().
executable()
const Foam::word & executable () const inline
Name of executable without the path.
Definition at line 30 of file argListI.H.
Referenced by forAll(), if(), and argList::parse().
rootPath()
const Foam::fileName & rootPath () const inline
Return root path.
Definition at line 36 of file argListI.H.
Referenced by argList::checkRootCase(), and argList::path().
caseName()
const Foam::fileName & caseName () const inline
Return case name (parallel run) or global case (serial run)
Definition at line 42 of file argListI.H.
Referenced by argList::path().
globalCaseName()
const Foam::fileName & globalCaseName () const inline
Return case name.
Definition at line 48 of file argListI.H.
parRunControl()
const Foam::ParRunControl & parRunControl () const inline
Return parRunControl.
Definition at line 54 of file argListI.H.
path()
Foam::fileName path () const inline
Return the path to the caseName.
Definition at line 60 of file argListI.H.
References argList::caseName(), and argList::rootPath().
Referenced by argList::checkRootCase().
args() [1/2]
const Foam::stringList & args () const inline
Return arguments.
Definition at line 66 of file argListI.H.
args() [2/2]
Foam::stringList & args () inline
Return non-const access to arguments.
Definition at line 72 of file argListI.H.
arg()
const Foam::string & arg (const label index) const inline
Return the argument corresponding to index.
Definition at line 78 of file argListI.H.
size()
Foam::label size () const inline
Return the number of arguments.
Definition at line 84 of file argListI.H.
References List< T >::size().
Referenced by argList::printUsage().
argRead()
T argRead (const label index) const inline
Read a value from the argument at index.
Index 0 corresponds to the name of the executable. Index 1 corresponds to the first argument.
Definition at line 177 of file argListI.H.
References Foam::T().
options() [1/2]
const Foam::HashTable< Foam::string > & options () const inline
Return options.
Definition at line 90 of file argListI.H.
options() [2/2]
Foam::HashTable< Foam::string > & options () inline
Return non-const access to options.
Definition at line 96 of file argListI.H.
option()
const Foam::string & option (const word & opt) const inline
Return the argument string associated with the named option.
Definition at line 102 of file argListI.H.
optionFound()
bool optionFound (const word & opt) const inline
Return true if the named option is found.
Definition at line 108 of file argListI.H.
Referenced by if(), functionObjectList::New(), argList::optionLookupOrDefault(), argList::optionReadIfPresent(), timeSelector::select(), and timeSelector::selectIfPresent().
optionLookup()
Foam::IStringStream optionLookup (const word & opt) const inline
Return an IStringStream from the named option.
Definition at line 114 of file argListI.H.
Referenced by functionObjectList::New(), argList::optionRead(), argList::optionReadList(), and timeSelector::select().
optionRead()
T optionRead (const word & opt) const inline
Read a value from the named option.
Definition at line 187 of file argListI.H.
References argList::optionLookup(), argList::optionReadIfPresent(), and Foam::T().
Referenced by if().
optionReadIfPresent() [1/2]
bool optionReadIfPresent (const word & opt, T & val) const inline
Read a value from the named option if present.
Return true if the named option was found.
Definition at line 198 of file argListI.H.
References argList::optionFound().
Referenced by argList::optionRead().
optionReadIfPresent() [2/2]
bool optionReadIfPresent (const word & opt, T & val, const T & deflt) const inline
Read a value from the named option if present.
Return true if the named option was found, otherwise use the supplied default and return false.
Definition at line 217 of file argListI.H.
References argList::optionLookupOrDefault(), and Foam::T().
optionLookupOrDefault()
T optionLookupOrDefault (const word & opt, const T & deflt) const inline
Read a value from the named option if present.
Return supplied default otherwise.
Definition at line 237 of file argListI.H.
References argList::optionFound().
Referenced by argList::optionReadIfPresent().
optionReadList()
List<T> optionReadList (const word & opt) const inline
Read a List of values from the named option.
Definition at line 310 of file argList.H.
References argList::addBoolOption(), argList::addNote(), argList::addOption(), argList::addUsage(), argList::check(), argList::checkRootCase(), argList::displayDoc(), argList::noBanner(), argList::noParallel(), argList::operator[](), argList::optionLookup(), argList::postProcess(), argList::printNotes(), argList::printUsage(), argList::removeOption(), argList::setOption(), and argList::unsetOption().
operator[]() [1/2]
const Foam::string & operator[] (const label index) const inline
Return the argument corresponding to index.
Index 0 corresponds to the name of the executable. Index 1 corresponds to the first argument.
Definition at line 255 of file argListI.H.
Referenced by argList::optionReadList().
operator[]() [2/2]
const Foam::string & operator[] (const word & opt) const inline
Return the argument string associated with the named option.
See also
option()
Definition at line 261 of file argListI.H.
addBoolOption()
addBoolOption (const word & opt, const string & usage = "") static
Add to a bool option to validOptions with usage information.
Definition at line 83 of file argList.C.
References argList::addOption().
Referenced by timeSelector::addOptions(), and argList::optionReadList().
addOption()
addOption (const word & opt, const string & param = "", const string & usage = "") static
Add to an option to validOptions with usage information.
An option with an empty param is a bool option
Definition at line 93 of file argList.C.
References argList::addUsage().
Referenced by argList::addBoolOption(), timeSelector::addOptions(), and argList::optionReadList().
addUsage()
void addUsage (const word & opt, const string & usage) static
Add option usage information to optionUsage.
Definition at line 108 of file argList.C.
Referenced by argList::addOption(), and argList::optionReadList().
addNote()
void addNote (const string & note) static
Add extra notes for the usage information.
This string is used "as-is" without additional formatting
Definition at line 124 of file argList.C.
References argList::notes.
Referenced by argList::optionReadList().
removeOption()
void removeOption (const word & opt) static
Remove option from validOptions and from optionUsage.
Definition at line 133 of file argList.C.
References argList::optionUsage, and argList::validOptions.
Referenced by argList::noParallel(), and argList::optionReadList().
noBanner()
void noBanner () static
Disable emitting the banner information.
Definition at line 140 of file argList.C.
Referenced by argList::optionReadList().
noParallel()
void noParallel () static
Remove the parallel options.
Definition at line 146 of file argList.C.
References Foam::Info, Foam::isspace(), Foam::nl, Foam::pos(), argList::removeOption(), argList::usageMax, argList::usageMin, and argList::validParOptions.
Referenced by argList::optionReadList().
postProcess()
bool postProcess (int argc, char * argv[]) static
Return true if the post-processing option is specified.
Definition at line 254 of file argList.C.
References argList::argList(), fileName::clean(), Foam::cwd(), fileName::isAbsolute(), fileName::name(), fileName::path(), argList::postProcessOptionName, Foam::setEnv(), and List< T >::setSize().
Referenced by argList::optionReadList().
setOption()
bool setOption (const word & opt, const string & param = "")
Set option directly (use with caution)
An option with an empty param is a bool option. Not all valid options can also be set: eg, -case, -roots, ... Return true if the existing option value needed changing, or if the option did not previously exist.
Definition at line 909 of file argList.C.
References Foam::endl(), error::exit(), Foam::FatalError, Foam::nl, and argList::validOptions.
Referenced by argList::optionReadList().
unsetOption()
bool unsetOption (const word & opt)
Unset option directly (use with caution)
Not all valid options can also be unset: eg, -case, -roots ... Return true if the option existed before being unset.
Definition at line 984 of file argList.C.
References Foam::endl(), error::exit(), Foam::FatalError, Foam::nl, and argList::validOptions.
Referenced by argList::optionReadList().
printNotes()
void printNotes () const
Print notes (if any)
Definition at line 1019 of file argList.C.
References forAllConstIter(), Foam::Info, Foam::nl, and argList::notes.
Referenced by argList::optionReadList(), and argList::printUsage().
printUsage()
void printUsage () const
Print usage.
Definition at line 1033 of file argList.C.
References Foam::endl(), Foam::FOAMbuild, Foam::FOAMversion, forAll, forAllConstIter(), Foam::Info, Foam::nl, argList::optionUsage, argList::printNotes(), argList::size(), argList::validArgs, and argList::validOptions.
Referenced by argList::argList(), argList::check(), argList::optionReadList(), and argList::parse().
displayDoc()
void displayDoc (bool source = false) const
Display documentation in browser.
Optionally display the application source code
Definition at line 1110 of file argList.C.
References Foam::debug::controlDict(), Foam::endl(), string::expand(), forAll, found, Foam::getEnv(), Foam::Info, Foam::isFile(), dictionary::lookup(), Foam::nl, string::replaceAll(), dictionary::subDict(), and Foam::system().
Referenced by argList::optionReadList(), and argList::parse().
check()
bool check (bool checkArgs = true, bool checkOpts = true) const
Check argument list.
Definition at line 1170 of file argList.C.
References Foam::endl(), Foam::FatalError, forAllConstIter(), UPstream::master(), argList::printUsage(), List< T >::size(), argList::validArgs, argList::validOptions, and argList::validParOptions.
Referenced by argList::optionReadList(), and argList::parse().
checkRootCase()
bool checkRootCase () const
Check root path and case path.
Definition at line 1211 of file argList.C.
References Foam::endl(), Foam::FatalError, Foam::isDir(), UPstream::master(), argList::path(), and argList::rootPath().
Referenced by argList::optionReadList().
Member Data Documentation
validArgs
Foam::SLList< Foam::string > validArgs static
A list of valid (mandatory) arguments.
Definition at line 154 of file argList.H.
Referenced by argList::check(), and argList::printUsage().
validOptions
Foam::HashTable< Foam::string > validOptions static
A list of valid options.
Definition at line 157 of file argList.H.
Referenced by argList::argList(), argList::check(), argList::printUsage(), argList::removeOption(), timeSelector::select(), argList::setOption(), and argList::unsetOption().
validParOptions
Foam::HashTable< Foam::string > validParOptions static
A list of valid parallel options.
Definition at line 160 of file argList.H.
Referenced by argList::argList(), argList::check(), and argList::noParallel().
optionUsage
Foam::HashTable< Foam::string > optionUsage static
Short usage information for validOptions.
Definition at line 163 of file argList.H.
Referenced by argList::printUsage(), and argList::removeOption().
notes
Foam::SLList< Foam::string > notes static
Additional notes for usage.
Definition at line 166 of file argList.H.
Referenced by argList::addNote(), and argList::printNotes().
usageMin
Foam::string::size_type usageMin = 20 static
Min offset for displaying usage (default: 20)
Definition at line 169 of file argList.H.
Referenced by argList::noParallel().
usageMax
Foam::string::size_type usageMax = 80 static
Max screen width for displaying usage (default: 80)
Definition at line 172 of file argList.H.
Referenced by argList::noParallel().
postProcessOptionName
Foam::word postProcessOptionName static
Standard name for the post-processing option.
Definition at line 175 of file argList.H.
Referenced by argList::postProcess().
The documentation for this class was generated from the following files:
src/OpenFOAM/global/argList/argList.H
src/OpenFOAM/db/functionObjects/functionObjectList/postProcess.H
src/OpenFOAM/global/argList/argList.C
src/OpenFOAM/global/argList/argListI.H
src/OpenFOAM/include/addDictOption.H
src/OpenFOAM/include/addFunctionObjectOptions.H
src/OpenFOAM/include/addOverwriteOption.H
src/OpenFOAM/include/addRegionOption.H
src/OpenFOAM/include/addTimeOptions.H