OpenFOAM: ParRunControl Class Reference
ParRunControl Class Reference
Helper class for initializing parallel jobs from the command arguments.
Public Member Functions
ParRunControl ()
~ParRunControl ()
void runPar (int &argc, char **&argv)
bool parRun () const
Detailed Description
Helper class for initializing parallel jobs from the command arguments.
Definition at line 46 of file parRun.H.
Constructor & Destructor Documentation
ParRunControl()
ParRunControl () inline
Definition at line 52 of file parRun.H.
~ParRunControl()
~ParRunControl () inline
Definition at line 57 of file parRun.H.
References Foam::endl(), UPstream::exit(), and Foam::Info.
Member Function Documentation
runPar()
void runPar (int & argc, char **& argv) inline
Definition at line 66 of file parRun.H.
References Foam::endl(), UPstream::exit(), Foam::Info, and UPstream::init().
Referenced by argList::argList().
parRun()
bool parRun () const inline
Definition at line 77 of file parRun.H.
Referenced by argList::parse().
The documentation for this class was generated from the following file:
src/OpenFOAM/global/argList/parRun.H