OpenFOAM: PatchToPatchInterpolation< FromPatch, ToPatch > Class Template Reference
PatchToPatchInterpolation< FromPatch, ToPatch > Class Template Reference
Interpolation class dealing with transfer of data between two primitivePatches.
Public Member Functions
PatchToPatchInterpolation (const FromPatch &fromPatch, const ToPatch &toPatch, const intersection::algorithm alg=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR)
Construct from components.
~PatchToPatchInterpolation ()
Destructor.
intersection::algorithm projectionAlgo () const
Return ype of intersection algorithm to use in projection.
intersection::direction projectionDir () const
Return direction projection to use in projection.
const scalarField & pointDistanceToIntersection () const
Return distance to intersection for patch points.
const scalarField & faceDistanceToIntersection () const
Return distance to intersection for patch face centres.
bool movePoints ()
Correct weighting factors for moving mesh.
template<class Type >
tmp< Field< Type > > pointInterpolate (const Field< Type > &pf) const
Interpolate point field.
template<class Type >
tmp< Field< Type > > pointInterpolate (const tmp< Field< Type >> &tpf) const
template<class Type >
tmp< Field< Type > > faceInterpolate (const Field< Type > &pf) const
Interpolate face field.
template<class Type >
tmp< Field< Type > > faceInterpolate (const tmp< Field< Type >> &tpf) const
Static Public Member Functions
static scalar setProjectionTol (const scalar t)
Set the projection tolerance, returning the previous value.
Detailed Description
template<class FromPatch, class ToPatch>
class Foam::PatchToPatchInterpolation< FromPatch, ToPatch >
Interpolation class dealing with transfer of data between two primitivePatches.
Source files
PatchToPatchInterpolation.H
PatchToPatchInterpolation.C
PatchToPatchInterpolate.C
CalcPatchToPatchWeights.C
Definition at line 65 of file PatchToPatchInterpolation.H.
Constructor & Destructor Documentation
PatchToPatchInterpolation()
PatchToPatchInterpolation (const FromPatch & fromPatch, const ToPatch & toPatch, const intersection::algorithm alg = intersection::FULL_RAY, const intersection::direction dir = intersection::VECTOR)
Construct from components.
Definition at line 110 of file PatchToPatchInterpolation.C.
~PatchToPatchInterpolation()
~PatchToPatchInterpolation ()
Destructor.
Definition at line 133 of file PatchToPatchInterpolation.C.
References PatchToPatchInterpolation< FromPatch, ToPatch >::pointDistanceToIntersection().
Member Function Documentation
setProjectionTol()
static scalar setProjectionTol (const scalar t) inline static
Set the projection tolerance, returning the previous value.
Definition at line 172 of file PatchToPatchInterpolation.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
projectionAlgo()
intersection::algorithm projectionAlgo () const inline
Return ype of intersection algorithm to use in projection.
Definition at line 187 of file PatchToPatchInterpolation.H.
projectionDir()
intersection::direction projectionDir () const inline
Return direction projection to use in projection.
Definition at line 193 of file PatchToPatchInterpolation.H.
References PatchToPatchInterpolation< FromPatch, ToPatch >::faceDistanceToIntersection(), PatchToPatchInterpolation< FromPatch, ToPatch >::faceInterpolate(), PatchToPatchInterpolation< FromPatch, ToPatch >::movePoints(), PatchToPatchInterpolation< FromPatch, ToPatch >::pointDistanceToIntersection(), and PatchToPatchInterpolation< FromPatch, ToPatch >::pointInterpolate().
pointDistanceToIntersection()
const scalarField & pointDistanceToIntersection () const
Return distance to intersection for patch points.
Definition at line 144 of file PatchToPatchInterpolation.C.
References PatchToPatchInterpolation< FromPatch, ToPatch >::faceDistanceToIntersection().
Referenced by PatchToPatchInterpolation< FromPatch, ToPatch >::projectionDir(), and PatchToPatchInterpolation< FromPatch, ToPatch >::~PatchToPatchInterpolation().
faceDistanceToIntersection()
const scalarField & faceDistanceToIntersection () const
Return distance to intersection for patch face centres.
Definition at line 158 of file PatchToPatchInterpolation.C.
Referenced by PatchToPatchInterpolation< FromPatch, ToPatch >::pointDistanceToIntersection(), and PatchToPatchInterpolation< FromPatch, ToPatch >::projectionDir().
movePoints()
bool movePoints ()
Correct weighting factors for moving mesh.
Definition at line 170 of file PatchToPatchInterpolation.C.
Referenced by PatchToPatchInterpolation< FromPatch, ToPatch >::projectionDir().
pointInterpolate() [1/2]
tmp< Field< Type > > pointInterpolate (const Field< Type > & pf) const
Interpolate point field.
Definition at line 40 of file PatchToPatchInterpolate.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, tmp< T >::ref(), List< Type >::size(), and Foam::Zero.
Referenced by PatchToPatchInterpolation< FromPatch, ToPatch >::projectionDir().
pointInterpolate() [2/2]
tmp< Field< Type > > pointInterpolate (const tmp< Field< Type >> & tpf) const
Definition at line 90 of file PatchToPatchInterpolate.C.
References tmp< T >::clear(), and PatchToPatchInterpolation< FromPatch, ToPatch >::faceInterpolate().
faceInterpolate() [1/2]
tmp< Field< Type > > faceInterpolate (const Field< Type > & pf) const
Interpolate face field.
Definition at line 104 of file PatchToPatchInterpolate.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, tmp< T >::ref(), List< Type >::size(), and Foam::Zero.
Referenced by PatchToPatchInterpolation< FromPatch, ToPatch >::pointInterpolate(), and PatchToPatchInterpolation< FromPatch, ToPatch >::projectionDir().
faceInterpolate() [2/2]
tmp< Field< Type > > faceInterpolate (const tmp< Field< Type >> & tpf) const
Definition at line 156 of file PatchToPatchInterpolate.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/patchToPatchInterpolation/PatchToPatchInterpolation.H
src/OpenFOAM/interpolations/patchToPatchInterpolation/CalcPatchToPatchWeights.C
src/OpenFOAM/interpolations/patchToPatchInterpolation/PatchToPatchInterpolate.C
src/OpenFOAM/interpolations/patchToPatchInterpolation/PatchToPatchInterpolation.C