OpenFOAM: uniformInterpolationTable< Type > Class Template Reference
uniformInterpolationTable< Type > Class Template Reference
Table with uniform interval in independant variable, with linear interpolation.
Public Member Functions
uniformInterpolationTable (const IOobject &, const bool readFields)
Construct from IOobject and readFields flag.
uniformInterpolationTable (const word &tableName, const objectRegistry &, const dictionary &, const bool initialiseOnly=false)
Construct from name, objectRegistry and dictionary.
uniformInterpolationTable (const uniformInterpolationTable &)
Construct as copy.
~uniformInterpolationTable ()
Destructor.
scalar x0 () const
Return the lower limit.
scalar dx () const
Return the fixed interval.
const Switch & log10 () const
Return the log10(x) flag.
const Switch & bound () const
Return the bound flag.
scalar & x0 ()
Return the lower limit.
scalar & dx ()
Return the fixed interval.
Switch & log10 ()
Return the log10(x) flag.
Switch & bound ()
Return the bound flag.
scalar xMin () const
Return the minimum x value.
scalar xMax () const
Return the maximum x value.
Type interpolate (scalar x) const
Interpolate.
Type interpolateLog10 (scalar x) const
Interpolate - takes log10 flag into account.
void write () const
Write.
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
virtual void rename (const word &newName)
Rename.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from List< Type >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< Type >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< Type >)
Assignment to an initializer list.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Additional Inherited Members
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
template<class Type>
class Foam::uniformInterpolationTable< Type >
Table with uniform interval in independant variable, with linear interpolation.
Example usage (scalar): values specified within a dictionary:
{
    x0          0;          // lower limit
    dx          0.2;        // fixed interval
    log10       true;       // take log(10) when interpolating?
    data                    // list of dependent data values
    (
        7870                // value at x0
        7870                // value at x0 + dx
        ...
        7870                // value at x0 + n*dx
    );
}
Source files
uniformInterpolationTable.H
uniformInterpolationTable.C
Definition at line 70 of file uniformInterpolationTable.H.
Constructor & Destructor Documentation
uniformInterpolationTable() [1/3]
uniformInterpolationTable (const IOobject & io, const bool readFields)
Construct from IOobject and readFields flag.
Creates a null object if readFields = false
Definition at line 49 of file uniformInterpolationTable.C.
Referenced by uniformInterpolationTable< scalar >::uniformInterpolationTable().
uniformInterpolationTable() [2/3]
uniformInterpolationTable (const word & tableName, const objectRegistry & db, const dictionary & dict, const bool initialiseOnly = false)
Construct from name, objectRegistry and dictionary.
If initialiseOnly flag is set, control parameters are read from the dictionary, but not the data table
Definition at line 78 of file uniformInterpolationTable.C.
uniformInterpolationTable() [3/3]
uniformInterpolationTable (const uniformInterpolationTable< Type > & uit)
Construct as copy.
Definition at line 117 of file uniformInterpolationTable.C.
~uniformInterpolationTable()
~uniformInterpolationTable ()
Destructor.
Definition at line 135 of file uniformInterpolationTable.C.
Member Function Documentation
x0() [1/2]
Foam::scalar x0 () const inline
Return the lower limit.
Definition at line 28 of file uniformInterpolationTable.H.
dx() [1/2]
Foam::scalar dx () const inline
Return the fixed interval.
Definition at line 35 of file uniformInterpolationTable.H.
log10() [1/2]
const Foam::Switch & log10 () const inline
Return the log10(x) flag.
Definition at line 42 of file uniformInterpolationTable.H.
bound() [1/2]
const Foam::Switch & bound () const inline
Return the bound flag.
Definition at line 49 of file uniformInterpolationTable.H.
x0() [2/2]
Foam::scalar & x0 () inline
Return the lower limit.
Definition at line 56 of file uniformInterpolationTable.H.
dx() [2/2]
Foam::scalar & dx () inline
Return the fixed interval.
Definition at line 63 of file uniformInterpolationTable.H.
log10() [2/2]
Foam::Switch & log10 () inline
Return the log10(x) flag.
Definition at line 70 of file uniformInterpolationTable.H.
bound() [2/2]
Foam::Switch & bound () inline
Return the bound flag.
Definition at line 77 of file uniformInterpolationTable.H.
xMin()
Foam::scalar xMin () const inline
Return the minimum x value.
Definition at line 84 of file uniformInterpolationTable.H.
xMax()
Foam::scalar xMax () const inline
Return the maximum x value.
Definition at line 91 of file uniformInterpolationTable.H.
interpolate()
Type interpolate (scalar x) const
Interpolate.
Definition at line 142 of file uniformInterpolationTable.C.
interpolateLog10()
Type interpolateLog10 (scalar x) const
Interpolate - takes log10 flag into account.
Definition at line 187 of file uniformInterpolationTable.C.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus(), and uniformInterpolationTable< scalar >::interpolate().
write()
void write () const
Write.
Definition at line 215 of file uniformInterpolationTable.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/uniformInterpolationTable/uniformInterpolationTable.H
src/OpenFOAM/interpolations/uniformInterpolationTable/uniformInterpolationTable.C
src/OpenFOAM/interpolations/uniformInterpolationTable/uniformInterpolationTableI.H