OpenFOAM: graph Class Reference
graph Class Reference
Class to create, store and output qgraph files.
Classes
class writer
Abstract base class for a graph writer.
Public Member Functions
graph (const string &title, const string &xName, const string &yName, const scalarField &x)
Construct from title and labels (no curves)
graph (const string &title, const string &xName, const string &yName, const scalarField &x, const scalarField &y)
Construct from title, labels and y data for 1 curve.
graph (const string &title, const string &xName, const string &yName, Istream &is)
Construct from Istream given title and labels.
graph (Istream &is)
Construct from Istream.
const string & title () const
const string & xName () const
const string & yName () const
const scalarField & x () const
scalarField & x ()
const scalarField & y () const
scalarField & y ()
void writeTable (Ostream &) const
Write out graph data as a simple table.
void write (Ostream &, const word &format) const
Write graph to stream in given format.
void write (const fileName &pName, const word &format) const
Write graph to file in given path-name and format.
void write (const fileName &path, const word &name, const word &format) const
Write graph to file in given path, name and format.
Public Member Functions inherited from HashPtrTable< curve >
HashPtrTable (const label size=128)
Construct given initial table size.
HashPtrTable (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
HashPtrTable (Istream &)
Construct from Istream using default Istream constructor class.
HashPtrTable (const dictionary &)
Construct from dictionary using default dictionary constructor.
HashPtrTable (const HashPtrTable< curve, word, string::hash > &)
Construct as copy.
~HashPtrTable ()
Destructor.
curve * remove (iterator &)
Remove and return the pointer specified by given iterator.
bool erase (iterator &)
Erase an hashedEntry specified by given iterator.
void clear ()
Clear all entries from table.
void write (Ostream &os) const
Write.
void operator= (const HashPtrTable< curve, word, string::hash > &)
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< T, Key, Hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< T, Key, Hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< Key, T >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const Key &) const
Return true if hashedEntry is found in table.
iterator find (const Key &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const Key &) const
Find and return an const_iterator set at the hashedEntry.
List< Key > toc () const
Return the table of contents.
List< Key > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const Key &, const T &newElmt)
Insert a new hashedEntry.
bool set (const Key &, const T &newElmt)
Assign a new hashedEntry, overwriting existing entries.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const Key &)
Erase a hashedEntry specified by the given key.
label erase (const UList< Key > &)
Remove entries given by the listed keys from this HashTable.
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &)
Remove entries given by the given keys from this HashTable.
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< T, Key, Hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< T, Key, Hash > > xfer ()
Transfer contents to the Xfer container.
T & operator[] (const Key &)
Find and return a hashedEntry.
const T & operator[] (const Key &) const
Find and return a hashedEntry.
T & operator() (const Key &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< T, Key, Hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< Key, T >>)
Assignment to an initializer list.
bool operator== (const HashTable< T, Key, Hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< T, Key, Hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
template<class AnyType , class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &rhs)
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Static Public Member Functions
static word wordify (const string &sname)
Helper function to convert string name into appropriate word.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Friends
Ostream & operator<< (Ostream &, const graph &)
Ostream Operator.
Additional Inherited Members
Public Types inherited from HashPtrTable< curve >
typedef HashTable< curve *, word, string::hash >::iterator iterator
typedef HashTable< curve *, word, string::hash >::const_iterator const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef T value_type
Type of values the HashTable contains.
typedef T & reference
Type that can be used for storing into HashTable::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Detailed Description
Class to create, store and output qgraph files.
Source files
graph.H
graph.C
Definition at line 58 of file graph.H.
Constructor & Destructor Documentation
graph() [1/4]
graph (const string & title, const string & xName, const string & yName, const scalarField & x)
Construct from title and labels (no curves)
Definition at line 79 of file graph.C.
Referenced by graph::graph(), and graph::wordify().
graph() [2/4]
graph (const string & title, const string & xName, const string & yName, const scalarField & x, const scalarField & y)
Construct from title, labels and y data for 1 curve.
Definition at line 94 of file graph.C.
References curve::curveStyle::CONTINUOUS, graph::graph(), and insert().
graph() [3/4]
graph (const string & title, const string & xName, const string & yName, Istream & is)
Construct from Istream given title and labels.
Definition at line 112 of file graph.C.
graph() [4/4]
graph (Istream & is)
Construct from Istream.
Definition at line 127 of file graph.C.
Member Function Documentation
title()
const string& title () const inline
Definition at line 149 of file graph.H.
Referenced by gnuplotGraph::write(), and xmgrGraph::write().
xName()
const string& xName () const inline
Definition at line 154 of file graph.H.
Referenced by gnuplotGraph::write(), jplotGraph::write(), and xmgrGraph::write().
yName()
const string& yName () const inline
Definition at line 159 of file graph.H.
Referenced by gnuplotGraph::write(), and xmgrGraph::write().
x() [1/2]
const scalarField& x () const inline
Definition at line 165 of file graph.H.
Referenced by Foam::kShellIntegration(), noiseFFT::Ldelta(), noiseFFT::Lf(), engineValve::lift(), noiseFFT::Pdelta(), gnuplotGraph::write(), and xmgrGraph::write().
x() [2/2]
scalarField& x () inline
Definition at line 170 of file graph.H.
References graph::y().
y() [1/2]
const Foam::scalarField & y () const
Definition at line 137 of file graph.C.
References HashTable< T, Key, Hash >::begin(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and HashTable< T, Key, Hash >::size().
Referenced by noiseFFT::Ldelta(), noiseFFT::Lf(), engineValve::lift(), noiseFFT::Lsum(), noiseFFT::Pdelta(), and graph::x().
y() [2/2]
Foam::scalarField & y ()
Definition at line 150 of file graph.C.
References HashTable< T, Key, Hash >::begin(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, graph::writer::New(), and HashTable< T, Key, Hash >::size().
writeTable()
void writeTable (Ostream & os) const
Write out graph data as a simple table.
Definition at line 206 of file graph.C.
References Foam::endl(), forAll, forAllConstIter(), Foam::setw(), and token::SPACE.
Referenced by Foam::operator<<(), rawGraph::write(), jplotGraph::write(), and graph::writer::~writer().
write() [1/3]
void write (Ostream & os, const word & format) const
Write graph to stream in given format.
Definition at line 221 of file graph.C.
References graph::writer::New().
Referenced by Foam::makeGraph(), graph::write(), and graph::writer::~writer().
write() [2/3]
void write (const fileName & pName, const word & format) const
Write graph to file in given path-name and format.
Definition at line 227 of file graph.C.
References Foam::endl(), IOstream::good(), OFstream::name(), graph::writer::New(), WarningInFunction, and graph::write().
write() [3/3]
void write (const fileName & path, const word & name, const word & format) const
Write graph to file in given path, name and format.
Definition at line 247 of file graph.C.
References Foam::mkDir(), and graph::write().
wordify()
Foam::word wordify (const string & sname) static
Helper function to convert string name into appropriate word.
Definition at line 44 of file graph.C.
References curve::curveStyle::CONTINUOUS, forAll, graph::graph(), insert(), string::replace(), List< T >::size(), and y.
Referenced by graph::writer::~writer().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const graph &) friend
Ostream Operator.
Referenced by graph::writer::~writer().
The documentation for this class was generated from the following files:
src/OpenFOAM/graph/graph.H
src/OpenFOAM/graph/graph.C