OpenFOAM: lduMatrix::preconditioner Class Reference
lduMatrix::preconditioner Class Reference abstract
Abstract base-class for lduMatrix preconditioners.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
preconditioner (const solver &sol)
virtual ~preconditioner ()
Destructor.
virtual void read (const dictionary &)
Read and reset the preconditioner parameters.
virtual void precondition (scalarField &wA, const scalarField &rA, const direction cmpt=0) const =0
Return wA the preconditioned form of residual rA.
virtual void preconditionT (scalarField &wT, const scalarField &rT, const direction cmpt=0) const
Return wT the transpose-matrix preconditioned form of.
Static Public Member Functions
static word getName (const dictionary &)
Find the preconditioner name (directly or from a sub-dictionary)
static autoPtr< preconditioner > New (const solver &sol, const dictionary &solverControls)
Return a new preconditioner.
Protected Attributes
const solver & solver_
Reference to the base-solver this preconditioner is used with.
Detailed Description
Abstract base-class for lduMatrix preconditioners.
Definition at line 407 of file lduMatrix.H.
Constructor & Destructor Documentation
preconditioner()
preconditioner (const solver & sol) inline
Definition at line 456 of file lduMatrix.H.
References lduMatrix::solver::New().
~preconditioner()
virtual ~preconditioner () inline virtual
Destructor.
Definition at line 475 of file lduMatrix.H.
References lduMatrix::solver::read().
Member Function Documentation
getName()
Foam::word getName (const dictionary & solverControls) static
Find the preconditioner name (directly or from a sub-dictionary)
Definition at line 40 of file lduMatrixPreconditioner.C.
References entry::dict(), Foam::e, entry::isDict(), dictionary::lookup(), dictionary::lookupEntry(), Foam::name(), lduMatrix::preconditioner::New(), and entry::stream().
Referenced by PBiCG::solve(), PCG::solve(), and PBiCGStab::solve().
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , preconditioner , symMatrix , (const solver &sol, const dictionary &solverControls) , (sol, solverControls))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , preconditioner , asymMatrix , (const solver &sol, const dictionary &solverControls) , (sol, solverControls))
New()
Foam::autoPtr< Foam::lduMatrix::preconditioner > New (const solver & sol, const dictionary & solverControls) static
Return a new preconditioner.
Definition at line 63 of file lduMatrixPreconditioner.C.
References lduMatrix::asymmetric(), entry::dict(), Foam::e, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, entry::isDict(), dictionary::lookup(), dictionary::lookupEntry(), lduMatrix::solver::matrix(), Foam::name(), Foam::nl, dictionary::null, entry::stream(), and lduMatrix::symmetric().
Referenced by lduMatrix::preconditioner::getName(), PCG::solve(), PBiCG::solve(), and PBiCGStab::solve().
read()
virtual void read (const dictionary &) inline virtual
Read and reset the preconditioner parameters.
from the given stream
Definition at line 483 of file lduMatrix.H.
precondition()
virtual void precondition (scalarField & wA, const scalarField & rA, const direction cmpt = 0) const pure virtual
Return wA the preconditioned form of residual rA.
Implemented in FDICPreconditioner, diagonalPreconditioner, GAMGPreconditioner, DICPreconditioner, DILUPreconditioner, and noPreconditioner.
preconditionT()
virtual void preconditionT (scalarField & wT, const scalarField & rT, const direction cmpt = 0) const inline virtual
Return wT the transpose-matrix preconditioned form of.
residual rT. This is only required for preconditioning asymmetric matrices.
Reimplemented in diagonalPreconditioner, DILUPreconditioner, and noPreconditioner.
Definition at line 498 of file lduMatrix.H.
References lduMatrix::ClassName(), lduMatrix::lduMatrix(), NotImplemented, and lduMatrix::~lduMatrix().
Member Data Documentation
solver_
const solver& solver_ protected
Reference to the base-solver this preconditioner is used with.
Definition at line 414 of file lduMatrix.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrix.H
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixPreconditioner.C