OpenFOAM: lduMatrix Class Reference
lduMatrix Class Reference
lduMatrix is a general matrix class in which the coefficients are stored as three arrays, one for the upper triangle, one for the lower triangle and a third for the diagonal.
Classes
class preconditioner
Abstract base-class for lduMatrix preconditioners.
class smoother
Abstract base-class for lduMatrix smoothers.
class solver
Abstract base-class for lduMatrix solvers.
Public Member Functions
ClassName ("lduMatrix")
lduMatrix (const lduMesh &)
Construct given an LDU addressed mesh.
lduMatrix (const lduMatrix &)
Construct as copy.
lduMatrix (lduMatrix &, bool reuse)
Construct as copy or re-use as specified.
lduMatrix (const lduMesh &, Istream &)
Construct given an LDU addressed mesh and an Istream.
~lduMatrix ()
Destructor.
const lduMesh & mesh () const
Return the LDU mesh from which the addressing is obtained.
const lduAddressing & lduAddr () const
Return the LDU addressing.
const lduSchedule & patchSchedule () const
Return the patch evaluation schedule.
scalarField & lower ()
scalarField & diag ()
scalarField & upper ()
scalarField & lower (const label size)
scalarField & diag (const label nCoeffs)
scalarField & upper (const label nCoeffs)
const scalarField & lower () const
const scalarField & diag () const
const scalarField & upper () const
bool hasDiag () const
bool hasUpper () const
bool hasLower () const
bool diagonal () const
bool symmetric () const
bool asymmetric () const
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (scalarField &sumOff) const
void Amul (scalarField &, const tmp< scalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix multiplication with updated interfaces.
void Tmul (scalarField &, const tmp< scalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix transpose multiplication with updated interfaces.
void sumA (scalarField &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &) const
Sum the coefficients on each row of the matrix.
void residual (scalarField &rA, const scalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
tmp< scalarField > residual (const scalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
void initMatrixInterfaces (const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const scalarField &psiif, scalarField &result, const direction cmpt) const
Initialise the update of interfaced interfaces.
void updateMatrixInterfaces (const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const scalarField &psiif, scalarField &result, const direction cmpt) const
Update interfaced interfaces for matrix operations.
template<class Type >
tmp< Field< Type > > H (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > H (const tmp< Field< Type >> &) const
tmp< scalarField > H1 () const
template<class Type >
tmp< Field< Type > > faceH (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > faceH (const tmp< Field< Type >> &) const
InfoProxy< lduMatrix > info () const
Return info proxy.
void operator= (const lduMatrix &)
void negate ()
void operator+= (const lduMatrix &)
void operator-= (const lduMatrix &)
void operator*= (const scalarField &)
void operator*= (scalar)
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type >> &tpsi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type >> &tpsi) const
Friends
Ostream & operator<< (Ostream &, const lduMatrix &)
Ostream & operator<< (Ostream &, const InfoProxy< lduMatrix > &)
Detailed Description
lduMatrix is a general matrix class in which the coefficients are stored as three arrays, one for the upper triangle, one for the lower triangle and a third for the diagonal.
Addressing arrays must be supplied for the upper and lower triangles.
It might be better if this class were organised as a hierachy starting from an empty matrix, then deriving diagonal, symmetric and asymmetric matrices.
Source files
lduMatrix.H
lduMatrixATmul.C
lduMatrix.C
lduMatrixTemplates.C
lduMatrixOperations.C
lduMatrixSolver.C
lduMatrixPreconditioner.C
lduMatrixTests.C
lduMatrixUpdateMatrixInterfaces.C
Definition at line 79 of file lduMatrix.H.
Constructor & Destructor Documentation
lduMatrix() [1/4]
lduMatrix (const lduMesh & mesh)
Construct given an LDU addressed mesh.
The coefficients are initially empty for subsequent setting.
Definition at line 40 of file lduMatrix.C.
Referenced by lduMatrix::preconditioner::preconditionT().
lduMatrix() [2/4]
lduMatrix (const lduMatrix & A)
Construct as copy.
Definition at line 49 of file lduMatrix.C.
lduMatrix() [3/4]
lduMatrix (lduMatrix & A, bool reuse)
Construct as copy or re-use as specified.
Definition at line 73 of file lduMatrix.C.
lduMatrix() [4/4]
lduMatrix (const lduMesh & mesh, Istream & is)
Construct given an LDU addressed mesh and an Istream.
from which the coefficients are read
Definition at line 120 of file lduMatrix.C.
References lduMatrix::hasDiag().
~lduMatrix()
~lduMatrix ()
Destructor.
Definition at line 146 of file lduMatrix.C.
Referenced by lduMatrix::preconditioner::preconditionT().
Member Function Documentation
ClassName()
ClassName ("lduMatrix")
Referenced by lduMatrix::preconditioner::preconditionT().
mesh()
const lduMesh& mesh () const inline
Return the LDU mesh from which the addressing is obtained.
Definition at line 541 of file lduMatrix.H.
Referenced by algebraicPairGAMGAgglomeration::algebraicPairGAMGAgglomeration(), GAMGAgglomeration::New(), PCG::solve(), PBiCG::solve(), smoothSolver::solve(), and PBiCGStab::solve().
lduAddr()
const lduAddressing& lduAddr () const inline
Return the LDU addressing.
Definition at line 547 of file lduMatrix.H.
References lduMesh::lduAddr().
Referenced by DICPreconditioner::calcReciprocalD(), DILUPreconditioner::calcReciprocalD(), fvMatrix< Type >::DD(), lduMatrix::diag(), lduMatrix::faceH(), lduMatrix::H(), fvMatrix< Type >::H1(), lduMatrix::H1(), lduMatrix::lower(), LUscalarMatrix::LUscalarMatrix(), lduMatrix::negSumDiag(), lduMatrix::operator*=(), lduMatrix::patchSchedule(), fvMatrix< Type >::relax(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), lduMatrix::sumDiag(), lduMatrix::sumMagOffDiag(), and lduMatrix::upper().
patchSchedule()
const lduSchedule& patchSchedule () const inline
Return the patch evaluation schedule.
Definition at line 553 of file lduMatrix.H.
References lduMatrix::diag(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::patchSchedule(), and lduMatrix::upper().
lower() [1/3]
Foam::scalarField & lower ()
Definition at line 165 of file lduMatrix.C.
References lduMatrix::lduAddr().
Referenced by algebraicPairGAMGAgglomeration::algebraicPairGAMGAgglomeration(), DILUPreconditioner::calcReciprocalD(), lduMatrix::faceH(), gaussConvectionScheme< Type >::fvmDiv(), GAMGSolver::GAMGSolver(), lduMatrix::H(), lduMatrix::H1(), LUscalarMatrix::LUscalarMatrix(), lduMatrix::negSumDiag(), lduMatrix::operator*=(), lduMatrix::operator+=(), lduMatrix::operator-=(), Foam::operator<<(), lduMatrix::operator=(), lduMatrix::patchSchedule(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), lduMatrix::sumDiag(), and lduMatrix::sumMagOffDiag().
diag() [1/3]
Foam::scalarField & diag ()
Definition at line 183 of file lduMatrix.C.
References lduMatrix::lduAddr().
Referenced by interRegionExplicitPorositySource::addSup(), solidificationMeltingSource::addSup(), fixedCoeff::correct(), powerLaw::correct(), DarcyForchheimer::correct(), fvMatrix< Type >::D(), fvMatrix< Type >::DD(), EulerD2dt2Scheme< Type >::fvmD2dt2(), EulerDdtScheme< Type >::fvmDdt(), backwardDdtScheme< Type >::fvmDdt(), CoEulerDdtScheme< Type >::fvmDdt(), SLTSDdtScheme< Type >::fvmDdt(), localEulerDdtScheme< Type >::fvmDdt(), CrankNicolsonDdtScheme< Type >::fvmDdt(), GAMGSolver::GAMGSolver(), LUscalarMatrix::LUscalarMatrix(), lduMatrix::negSumDiag(), nonBlockingGaussSeidelSmoother::nonBlockingGaussSeidelSmoother(), lduMatrix::operator+=(), lduMatrix::operator-=(), Foam::operator<<(), lduMatrix::operator=(), lduMatrix::patchSchedule(), fvMatrix< Type >::relax(), fvMatrix< Type >::setReference(), GaussSeidelSmoother::smooth(), symGaussSeidelSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), GAMGSolver::solve(), and lduMatrix::sumDiag().
upper() [1/3]
Foam::scalarField & upper ()
Definition at line 194 of file lduMatrix.C.
References lduMatrix::lduAddr().
Referenced by algebraicPairGAMGAgglomeration::algebraicPairGAMGAgglomeration(), DICPreconditioner::calcReciprocalD(), DILUPreconditioner::calcReciprocalD(), lduMatrix::faceH(), gaussConvectionScheme< Type >::fvmDiv(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), lduMatrix::H(), lduMatrix::H1(), LUscalarMatrix::LUscalarMatrix(), lduMatrix::negSumDiag(), lduMatrix::operator*=(), lduMatrix::operator+=(), lduMatrix::operator-=(), Foam::operator<<(), lduMatrix::operator=(), lduMatrix::patchSchedule(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), nonBlockingGaussSeidelSmoother::smooth(), lduMatrix::sumDiag(), and lduMatrix::sumMagOffDiag().
lower() [2/3]
Foam::scalarField & lower (const label size)
Definition at line 212 of file lduMatrix.C.
diag() [2/3]
Foam::scalarField & diag (const label nCoeffs)
Definition at line 230 of file lduMatrix.C.
upper() [2/3]
Foam::scalarField & upper (const label nCoeffs)
Definition at line 241 of file lduMatrix.C.
lower() [3/3]
const Foam::scalarField & lower () const
Definition at line 259 of file lduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
diag() [3/3]
const Foam::scalarField & diag () const
Definition at line 279 of file lduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
upper() [3/3]
const Foam::scalarField & upper () const
Definition at line 292 of file lduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
hasDiag()
bool hasDiag () const inline
Definition at line 577 of file lduMatrix.H.
Referenced by lduMatrix::lduMatrix(), and Foam::operator<<().
hasUpper()
bool hasUpper () const inline
Definition at line 582 of file lduMatrix.H.
Referenced by Foam::checkMethod(), and Foam::operator<<().
hasLower()
bool hasLower () const inline
Definition at line 587 of file lduMatrix.H.
Referenced by algebraicPairGAMGAgglomeration::algebraicPairGAMGAgglomeration(), Foam::checkMethod(), and Foam::operator<<().
diagonal()
bool diagonal () const inline
Definition at line 592 of file lduMatrix.H.
Referenced by lduMatrix::solver::New(), lduMatrix::operator+=(), and lduMatrix::operator-=().
symmetric()
bool symmetric () const inline
Definition at line 597 of file lduMatrix.H.
Referenced by lduMatrix::solver::New(), lduMatrix::smoother::New(), lduMatrix::preconditioner::New(), lduMatrix::operator*=(), lduMatrix::operator+=(), and lduMatrix::operator-=().
asymmetric()
bool asymmetric () const inline
Definition at line 602 of file lduMatrix.H.
References lduMatrix::Amul(), lduMatrix::faceH(), lduMatrix::H(), lduMatrix::H1(), lduMatrix::info(), lduMatrix::initMatrixInterfaces(), lduMatrix::negate(), lduMatrix::negSumDiag(), lduMatrix::operator*=(), lduMatrix::operator+=(), lduMatrix::operator-=(), lduMatrix::operator<<, lduMatrix::operator=(), psi, lduMatrix::residual(), lduMatrix::sumA(), lduMatrix::sumDiag(), lduMatrix::sumMagOffDiag(), lduMatrix::Tmul(), and lduMatrix::updateMatrixInterfaces().
Referenced by lduMatrix::solver::New(), lduMatrix::smoother::New(), lduMatrix::preconditioner::New(), lduMatrix::operator*=(), lduMatrix::operator+=(), and lduMatrix::operator-=().
sumDiag()
void sumDiag ()
Definition at line 33 of file lduMatrixOperations.C.
References lduMatrix::diag(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), UList< T >::size(), lduMatrix::upper(), and lduAddressing::upperAddr().
Referenced by lduMatrix::asymmetric().
negSumDiag()
void negSumDiag ()
Definition at line 50 of file lduMatrixOperations.C.
References lduMatrix::diag(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), UList< T >::size(), lduMatrix::sumMagOffDiag(), lduMatrix::upper(), and lduAddressing::upperAddr().
Referenced by lduMatrix::asymmetric(), gaussConvectionScheme< Type >::fvmDiv(), and gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected().
sumMagOffDiag()
void sumMagOffDiag (scalarField & sumOff) const
Definition at line 68 of file lduMatrixOperations.C.
References lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), Foam::mag(), UList< T >::size(), lduMatrix::upper(), and lduAddressing::upperAddr().
Referenced by lduMatrix::asymmetric(), lduMatrix::negSumDiag(), and fvMatrix< Type >::relax().
Amul()
void Amul (scalarField & Apsi, const tmp< scalarField > & tpsi, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt) const
Matrix multiplication with updated interfaces.
Definition at line 35 of file lduMatrixATmul.C.
References UList< T >::begin(), tmp< T >::clear(), Foam::diag(), psi, and lduMatrix::Tmul().
Referenced by lduMatrix::asymmetric().
Tmul()
void Tmul (scalarField & Tpsi, const tmp< scalarField > & tpsi, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt) const
Matrix transpose multiplication with updated interfaces.
Definition at line 96 of file lduMatrixATmul.C.
References UList< T >::begin(), tmp< T >::clear(), Foam::diag(), psi, and lduMatrix::sumA().
Referenced by lduMatrix::Amul(), and lduMatrix::asymmetric().
sumA()
void sumA (scalarField & sumA, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces) const
Sum the coefficients on each row of the matrix.
Definition at line 155 of file lduMatrixATmul.C.
References UList< T >::begin(), Foam::diag(), forAll, patchi, lduMatrix::residual(), and UPtrList< T >::set().
Referenced by lduMatrix::asymmetric(), and lduMatrix::Tmul().
residual() [1/2]
void residual (scalarField & rA, const scalarField & psi, const scalarField & source, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt) const
Definition at line 204 of file lduMatrixATmul.C.
References UList< T >::begin(), Foam::diag(), forAll, patchi, UPtrList< T >::set(), and UPtrList< T >::size().
Referenced by lduMatrix::asymmetric(), fvMatrix< Type >::residual(), and lduMatrix::sumA().
residual() [2/2]
Foam::tmp< Foam::scalarField > residual (const scalarField & psi, const scalarField & source, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt) const
Definition at line 284 of file lduMatrixATmul.C.
References psi, tmp< T >::ref(), scalarField(), and List< T >::size().
initMatrixInterfaces()
void initMatrixInterfaces (const FieldField< Field, scalar > & interfaceCoeffs, const lduInterfaceFieldPtrsList & interfaces, const scalarField & psiif, scalarField & result, const direction cmpt) const
Initialise the update of interfaced interfaces.
for matrix operations
Definition at line 31 of file lduMatrixUpdateMatrixInterfaces.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::set(), List< T >::size(), UPtrList< T >::size(), and lduMatrix::updateMatrixInterfaces().
Referenced by lduMatrix::asymmetric(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), and nonBlockingGaussSeidelSmoother::smooth().
updateMatrixInterfaces()
void updateMatrixInterfaces (const FieldField< Field, scalar > & interfaceCoeffs, const lduInterfaceFieldPtrsList & interfaces, const scalarField & psiif, scalarField & result, const direction cmpt) const
Update interfaced interfaces for matrix operations.
Definition at line 97 of file lduMatrixUpdateMatrixInterfaces.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPtrList< T >::set(), List< T >::size(), and UPtrList< T >::size().
Referenced by lduMatrix::asymmetric(), lduMatrix::initMatrixInterfaces(), symGaussSeidelSmoother::smooth(), GaussSeidelSmoother::smooth(), and nonBlockingGaussSeidelSmoother::smooth().
H() [1/4]
tmp<Field<Type> > H (const Field< Type > &) const
Referenced by lduMatrix::asymmetric(), lduMatrix::H(), and fvMatrix< Type >::H().
H() [2/4]
tmp<Field<Type> > H (const tmp< Field< Type >> &) const
H1()
Foam::tmp< Foam::scalarField > H1 () const
Definition at line 298 of file lduMatrixATmul.C.
References UList< T >::begin(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), tmp< T >::ref(), List< T >::size(), lduMatrix::upper(), and lduAddressing::upperAddr().
Referenced by lduMatrix::asymmetric(), and fvMatrix< Type >::H1().
faceH() [1/4]
tmp<Field<Type> > faceH (const Field< Type > &) const
Referenced by lduMatrix::asymmetric(), lduMatrix::faceH(), and fvMatrix< Type >::flux().
faceH() [2/4]
tmp<Field<Type> > faceH (const tmp< Field< Type >> &) const
info()
InfoProxy<lduMatrix> info () const inline
Return info proxy.
Used to print matrix information to a stream
Definition at line 706 of file lduMatrix.H.
Referenced by lduMatrix::asymmetric().
operator=()
void operator= (const lduMatrix & A)
Definition at line 88 of file lduMatrixOperations.C.
References Foam::abort(), lduMatrix::diag(), Foam::FatalError, lduMatrix::lower(), and lduMatrix::upper().
Referenced by lduMatrix::asymmetric(), and fvMatrix< Type >::operator=().
negate()
void negate ()
Definition at line 125 of file lduMatrixOperations.C.
References Field< Type >::negate().
Referenced by lduMatrix::asymmetric(), and fvMatrix< Type >::negate().
operator+=()
void operator+= (const lduMatrix & A)
Definition at line 144 of file lduMatrixOperations.C.
References lduMatrix::asymmetric(), lduMatrix::diag(), lduMatrix::diagonal(), Foam::endl(), lduMatrix::lower(), Foam::nl, lduMatrix::symmetric(), lduMatrix::upper(), and WarningInFunction.
Referenced by lduMatrix::asymmetric(), and fvMatrix< Type >::operator+=().
operator-=()
void operator-= (const lduMatrix & A)
Definition at line 223 of file lduMatrixOperations.C.
References lduMatrix::asymmetric(), lduMatrix::diag(), lduMatrix::diagonal(), Foam::endl(), lduMatrix::lower(), Foam::nl, lduMatrix::symmetric(), lduMatrix::upper(), and WarningInFunction.
Referenced by lduMatrix::asymmetric(), and fvMatrix< Type >::operator-=().
operator*=() [1/2]
void operator*= (const scalarField & sf)
Definition at line 302 of file lduMatrixOperations.C.
References lduMatrix::asymmetric(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), sf(), List< T >::size(), lduMatrix::symmetric(), lduMatrix::upper(), and lduAddressing::upperAddr().
Referenced by lduMatrix::asymmetric(), and fvMatrix< Type >::operator*=().
operator*=() [2/2]
void operator*= (scalar s)
Definition at line 332 of file lduMatrixOperations.C.
References s().
H() [3/4]
Foam::tmp<Foam::Field<Type> > H (const Field< Type > & psi) const
Definition at line 34 of file lduMatrixTemplates.C.
References UList< Type >::begin(), UList< T >::begin(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), tmp< T >::ref(), List< T >::size(), lduMatrix::upper(), lduAddressing::upperAddr(), and Foam::Zero.
H() [4/4]
Foam::tmp<Foam::Field<Type> > H (const tmp< Field< Type >> & tpsi) const
Definition at line 69 of file lduMatrixTemplates.C.
References lduMatrix::H().
faceH() [3/4]
Foam::tmp<Foam::Field<Type> > faceH (const Field< Type > & psi) const
Definition at line 79 of file lduMatrixTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), tmp< T >::ref(), List< T >::size(), UList< T >::size(), lduMatrix::upper(), and lduAddressing::upperAddr().
faceH() [4/4]
Foam::tmp<Foam::Field<Type> > faceH (const tmp< Field< Type >> & tpsi) const
Definition at line 115 of file lduMatrixTemplates.C.
References lduMatrix::faceH().
Friends And Related Function Documentation
operator<< [1/2]
Ostream& operator<< (Ostream & , const lduMatrix &) friend
Referenced by lduMatrix::asymmetric().
operator<< [2/2]
Ostream& operator<< (Ostream & , const InfoProxy< lduMatrix > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrix.H
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrix.C
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixATmul.C
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixOperations.C
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixTemplates.C
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixUpdateMatrixInterfaces.C