OpenFOAM: DILUSmoother Class Reference
DILUSmoother Class Reference
Simplified diagonal-based incomplete LU smoother for asymmetric matrices.
Public Member Functions
TypeName ("DILU")
Runtime type information.
DILUSmoother (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces)
Construct from matrix components.
void smooth (scalarField &psi, const scalarField &source, const direction cmpt, const label nSweeps) const
Smooth the solution for a given number of sweeps.
Public Member Functions inherited from lduMatrix::smoother
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, smoother, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
declareRunTimeSelectionTable (autoPtr, smoother, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces))
smoother (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces)
virtual ~smoother ()
Destructor.
const word & fieldName () const
const lduMatrix & matrix () const
const FieldField< Field, scalar > & interfaceBouCoeffs () const
const FieldField< Field, scalar > & interfaceIntCoeffs () const
const lduInterfaceFieldPtrsList & interfaces () const
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::smoother
static word getName (const dictionary &)
Find the smoother name (directly or from a sub-dictionary)
static autoPtr< smoother > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Return a new smoother.
Protected Attributes inherited from lduMatrix::smoother
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
const lduInterfaceFieldPtrsList & interfaces_
Detailed Description
Simplified diagonal-based incomplete LU smoother for asymmetric matrices.
Source files
DILUSmoother.H
DILUSmoother.C
Definition at line 48 of file DILUSmoother.H.
Constructor & Destructor Documentation
DILUSmoother()
DILUSmoother (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces)
Construct from matrix components.
Definition at line 43 of file DILUSmoother.C.
References DILUPreconditioner::calcReciprocalD(), and DILUSmoother::smooth().
Member Function Documentation
TypeName()
TypeName ("DILU")
Runtime type information.
smooth()
void smooth (scalarField & psi, const scalarField & source, const direction cmpt, const label nSweeps) const virtual
Smooth the solution for a given number of sweeps.
Implements lduMatrix::smoother.
Definition at line 68 of file DILUSmoother.C.
References UList< T >::begin(), and Foam::fvc::sweep().
Referenced by DILUSmoother::DILUSmoother().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/smoothers/DILU/DILUSmoother.H
src/OpenFOAM/matrices/lduMatrix/smoothers/DILU/DILUSmoother.C