OpenFOAM: processorLduInterface Class Reference
processorLduInterface Class Reference abstract
An abstract base class for processor coupled interfaces.
Public Member Functions
TypeName ("processorLduInterface")
Runtime type information.
processorLduInterface ()
Construct null.
virtual ~processorLduInterface ()
Destructor.
virtual label comm () const =0
Return communicator used for parallel communication.
virtual int myProcNo () const =0
Return processor number (rank in communicator)
virtual int neighbProcNo () const =0
Return neigbour processor number (rank in communicator)
virtual const tensorField & forwardT () const =0
Return face transformation tensor.
virtual int tag () const =0
Return message tag used for sending.
template<class Type >
void send (const Pstream::commsTypes commsType, const UList< Type > &) const
Raw send function.
template<class Type >
void receive (const Pstream::commsTypes commsType, UList< Type > &) const
Raw field receive function.
template<class Type >
tmp< Field< Type > > receive (const Pstream::commsTypes commsType, const label size) const
Raw field receive function returning field.
template<class Type >
void compressedSend (const Pstream::commsTypes commsType, const UList< Type > &) const
Raw field send function with data compression.
template<class Type >
void compressedReceive (const Pstream::commsTypes commsType, UList< Type > &) const
Raw field receive function with data compression.
template<class Type >
tmp< Field< Type > > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Raw field receive function with data compression returning field.
template<class Type >
Foam::tmp< Foam::Field< Type > > receive (const Pstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Detailed Description
An abstract base class for processor coupled interfaces.
Source files
processorLduInterface.H
processorLduInterface.C
processorLduInterfaceTemplates.C
Definition at line 50 of file processorLduInterface.H.
Constructor & Destructor Documentation
processorLduInterface()
processorLduInterface ()
Construct null.
Definition at line 53 of file processorLduInterface.C.
~processorLduInterface()
~processorLduInterface () virtual
Destructor.
Definition at line 62 of file processorLduInterface.C.
Member Function Documentation
TypeName()
TypeName ("processorLduInterface")
Runtime type information.
comm()
virtual label comm () const pure virtual
Return communicator used for parallel communication.
Implemented in processorGAMGInterface, and processorFvPatch.
Referenced by Foam::operator<<(), and procLduInterface::procLduInterface().
myProcNo()
virtual int myProcNo () const pure virtual
Return processor number (rank in communicator)
Implemented in processorGAMGInterface, and processorFvPatch.
Referenced by lduPrimitiveMesh::lduPrimitiveMesh(), Foam::operator<<(), and procLduInterface::procLduInterface().
neighbProcNo()
virtual int neighbProcNo () const pure virtual
Return neigbour processor number (rank in communicator)
Implemented in processorGAMGInterface, and processorFvPatch.
Referenced by lduPrimitiveMesh::lduPrimitiveMesh(), Foam::operator<<(), and procLduInterface::procLduInterface().
forwardT()
virtual const tensorField& forwardT () const pure virtual
Return face transformation tensor.
Implemented in processorGAMGInterface, processorFvPatch, and processorCyclicFvPatch.
tag()
virtual int tag () const pure virtual
Return message tag used for sending.
Implemented in processorGAMGInterface, processorFvPatch, and processorCyclicFvPatch.
Referenced by procLduInterface::procLduInterface().
send()
void send (const Pstream::commsTypes commsType, const UList< Type > & f) const
Raw send function.
Definition at line 34 of file processorLduInterfaceTemplates.C.
References UList< T >::begin(), UList< T >::byteSize(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::read(), processorLduInterface::receive(), and write().
receive() [1/3]
void receive (const Pstream::commsTypes commsType, UList< Type > & f) const
Raw field receive function.
Definition at line 91 of file processorLduInterfaceTemplates.C.
References UList< T >::begin(), UList< T >::byteSize(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::read().
Referenced by processorLduInterface::send().
receive() [2/3]
tmp<Field<Type> > receive (const Pstream::commsTypes commsType, const label size) const
Raw field receive function returning field.
compressedSend()
void compressedSend (const Pstream::commsTypes commsType, const UList< Type > & f) const
Raw field send function with data compression.
Definition at line 136 of file processorLduInterfaceTemplates.C.
References UList< T >::begin(), processorLduInterface::compressedReceive(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::last(), Foam::read(), UList< T >::size(), and write().
Referenced by processorLduInterface::receive().
compressedReceive() [1/3]
void compressedReceive (const Pstream::commsTypes commsType, UList< Type > & f) const
Raw field receive function with data compression.
Definition at line 212 of file processorLduInterfaceTemplates.C.
References UList< T >::begin(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, UList< T >::last(), Foam::read(), and UList< T >::size().
Referenced by processorLduInterface::compressedSend().
compressedReceive() [2/3]
tmp<Field<Type> > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Raw field receive function with data compression returning field.
receive() [3/3]
Foam::tmp<Foam::Field<Type> > receive (const Pstream::commsTypes commsType, const label size) const
Definition at line 123 of file processorLduInterfaceTemplates.C.
References processorLduInterface::compressedSend(), tmp< T >::ref(), and tf.
compressedReceive() [3/3]
Foam::tmp<Foam::Field<Type> > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Definition at line 265 of file processorLduInterfaceTemplates.C.
References tmp< T >::ref(), and tf.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/processorLduInterface.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/processorLduInterface.C
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/processorLduInterfaceTemplates.C