OpenFOAM: cyclicLduInterfaceField Class Reference
cyclicLduInterfaceField Class Reference abstract
Abstract base class for cyclic coupled interfaces.
Public Member Functions
TypeName ("cyclicLduInterfaceField")
Runtime type information.
cyclicLduInterfaceField ()
Construct given coupled patch.
virtual ~cyclicLduInterfaceField ()
Destructor.
virtual bool doTransform () const =0
Is the transform required.
virtual const tensorField & forwardT () const =0
Return face transformation tensor.
virtual const tensorField & reverseT () const =0
Return neighbour-cell transformation tensor.
virtual int rank () const =0
Return rank of component for transform.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &f, const direction cmpt) const
Transform given patch component field.
Detailed Description
Abstract base class for cyclic coupled interfaces.
Source files
cyclicLduInterfaceField.H
cyclicLduInterfaceField.C
Definition at line 49 of file cyclicLduInterfaceField.H.
Constructor & Destructor Documentation
cyclicLduInterfaceField()
cyclicLduInterfaceField () inline
Construct given coupled patch.
Definition at line 61 of file cyclicLduInterfaceField.H.
References cyclicLduInterfaceField::doTransform(), f(), cyclicLduInterfaceField::forwardT(), cyclicLduInterfaceField::rank(), cyclicLduInterfaceField::reverseT(), cyclicLduInterfaceField::transformCoupleField(), and cyclicLduInterfaceField::~cyclicLduInterfaceField().
~cyclicLduInterfaceField()
~cyclicLduInterfaceField () virtual
Destructor.
Definition at line 39 of file cyclicLduInterfaceField.C.
References cyclicLduInterfaceField::transformCoupleField().
Referenced by cyclicLduInterfaceField::cyclicLduInterfaceField().
Member Function Documentation
TypeName()
TypeName ("cyclicLduInterfaceField")
Runtime type information.
doTransform()
virtual bool doTransform () const pure virtual
Is the transform required.
Implemented in cyclicFvPatchField< Type >, and cyclicGAMGInterfaceField.
Referenced by cyclicGAMGInterfaceField::cyclicGAMGInterfaceField(), cyclicLduInterfaceField::cyclicLduInterfaceField(), and cyclicLduInterfaceField::transformCoupleField().
forwardT()
virtual const tensorField& forwardT () const pure virtual
Return face transformation tensor.
Implemented in cyclicFvPatchField< Type >, and cyclicGAMGInterfaceField.
Referenced by cyclicLduInterfaceField::cyclicLduInterfaceField(), and cyclicLduInterfaceField::transformCoupleField().
reverseT()
virtual const tensorField& reverseT () const pure virtual
Return neighbour-cell transformation tensor.
Implemented in cyclicFvPatchField< Type >, and cyclicGAMGInterfaceField.
Referenced by cyclicLduInterfaceField::cyclicLduInterfaceField().
rank()
virtual int rank () const pure virtual
Return rank of component for transform.
Implemented in cyclicFvPatchField< Type >, and cyclicGAMGInterfaceField.
Referenced by cyclicGAMGInterfaceField::cyclicGAMGInterfaceField(), and cyclicLduInterfaceField::cyclicLduInterfaceField().
transformCoupleField() [1/2]
void transformCoupleField (Field< Type > & f) const
Transform given patch field.
Definition at line 109 of file cyclicLduInterfaceField.H.
References cyclicLduInterfaceField::doTransform(), cyclicLduInterfaceField::forwardT(), and Foam::transform().
Referenced by cyclicLduInterfaceField::cyclicLduInterfaceField(), and cyclicLduInterfaceField::~cyclicLduInterfaceField().
transformCoupleField() [2/2]
void transformCoupleField (scalarField & f, const direction cmpt) const
Transform given patch component field.
Definition at line 46 of file cyclicLduInterfaceField.C.
References Foam::component(), Foam::diag(), and Foam::pow().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/cyclicLduInterfaceField/cyclicLduInterfaceField.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/cyclicLduInterfaceField/cyclicLduInterfaceField.C