OpenFOAM: noPreconditioner Class Reference
noPreconditioner Class Reference
Null preconditioner for both symmetric and asymmetric matrices.
Public Member Functions
TypeName ("none")
Runtime type information.
noPreconditioner (const lduMatrix::solver &, const dictionary &solverControlsUnused)
Construct from matrix components and preconditioner solver controls.
virtual ~noPreconditioner ()
Destructor.
virtual void precondition (scalarField &wA, const scalarField &rA, const direction cmpt=0) const
Return wA the preconditioned form of residual rA.
virtual void preconditionT (scalarField &wT, const scalarField &rT, const direction cmpt=0) const
Return wT the transpose-matrix preconditioned form of residual rT.
Public Member Functions inherited from lduMatrix::preconditioner
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
preconditioner (const solver &sol)
virtual ~preconditioner ()
Destructor.
virtual void read (const dictionary &)
Read and reset the preconditioner parameters.
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::preconditioner
static word getName (const dictionary &)
Find the preconditioner name (directly or from a sub-dictionary)
static autoPtr< preconditioner > New (const solver &sol, const dictionary &solverControls)
Return a new preconditioner.
Protected Attributes inherited from lduMatrix::preconditioner
const solver & solver_
Reference to the base-solver this preconditioner is used with.
Detailed Description
Null preconditioner for both symmetric and asymmetric matrices.
Source files
noPreconditioner.H
noPreconditioner.C
Definition at line 48 of file noPreconditioner.H.
Constructor & Destructor Documentation
noPreconditioner()
noPreconditioner (const lduMatrix::solver & sol, const dictionary & solverControlsUnused)
Construct from matrix components and preconditioner solver controls.
Definition at line 47 of file noPreconditioner.C.
References noPreconditioner::precondition().
~noPreconditioner()
virtual ~noPreconditioner () inline virtual
Destructor.
Definition at line 78 of file noPreconditioner.H.
References noPreconditioner::precondition(), and noPreconditioner::preconditionT().
Member Function Documentation
TypeName()
TypeName ("none")
Runtime type information.
precondition()
void precondition (scalarField & wA, const scalarField & rA, const direction cmpt = 0) const virtual
Return wA the preconditioned form of residual rA.
Implements lduMatrix::preconditioner.
Definition at line 59 of file noPreconditioner.C.
References UList< T >::begin(), and List< T >::size().
Referenced by noPreconditioner::noPreconditioner(), noPreconditioner::preconditionT(), and noPreconditioner::~noPreconditioner().
preconditionT()
virtual void preconditionT (scalarField & wT, const scalarField & rT, const direction cmpt = 0) const inline virtual
Return wT the transpose-matrix preconditioned form of residual rT.
Reimplemented from lduMatrix::preconditioner.
Definition at line 94 of file noPreconditioner.H.
References noPreconditioner::precondition().
Referenced by noPreconditioner::~noPreconditioner().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/preconditioners/noPreconditioner/noPreconditioner.H
src/OpenFOAM/matrices/lduMatrix/preconditioners/noPreconditioner/noPreconditioner.C