OpenFOAM: lduInterface Class Reference
lduInterface Class Reference abstract
An abstract base class for implicitly-coupled interfaces e.g. processor and cyclic patches.
Public Member Functions
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
virtual const labelUList & faceCells () const =0
Return faceCell addressing.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const =0
Return the values of the given internal data adjacent to.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const =0
Transfer and return internal field adjacent to the interface.
Detailed Description
An abstract base class for implicitly-coupled interfaces e.g. processor and cyclic patches.
Source files
lduInterface.H
lduInterface.C
Definition at line 53 of file lduInterface.H.
Constructor & Destructor Documentation
lduInterface()
lduInterface () inline
Construct null.
Definition at line 73 of file lduInterface.H.
References lduInterface::faceCells(), lduInterface::initInternalFieldTransfer(), lduInterface::interfaceInternalField(), and lduInterface::~lduInterface().
~lduInterface()
~lduInterface () virtual
Destructor.
Definition at line 38 of file lduInterface.C.
Referenced by lduInterface::lduInterface().
Member Function Documentation
TypeName()
TypeName ("lduInterface")
Runtime type information.
faceCells()
virtual const labelUList& faceCells () const pure virtual
Return faceCell addressing.
Implemented in GAMGInterface, regionCoupledWallFvPatch, regionCoupledFvPatch, and coupledFvPatch.
Referenced by lduInterface::lduInterface(), and lduPrimitiveMesh::lduPrimitiveMesh().
interfaceInternalField()
virtual tmp<labelField> interfaceInternalField (const labelUList & internalData) const pure virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implemented in GAMGInterface, cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, cyclicFvPatch, regionCoupledWallFvPatch, regionCoupledFvPatch, and coupledFvPatch.
Referenced by lduInterface::lduInterface().
initInternalFieldTransfer()
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const inline virtual
Initialise transfer of internal field adjacent to the interface.
Reimplemented in processorFvPatch, and processorGAMGInterface.
Definition at line 100 of file lduInterface.H.
References lduInterface::internalFieldTransfer().
Referenced by regionCoupledFvPatch::coupled(), regionCoupledWallFvPatch::coupled(), coupledFvPatch::faceCells(), and lduInterface::lduInterface().
internalFieldTransfer()
virtual tmp<labelField> internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const pure virtual
Transfer and return internal field adjacent to the interface.
Implemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, cyclicFvPatch, regionCoupledWallFvPatch, regionCoupledFvPatch, coupledFvPatch, processorGAMGInterface, cyclicGAMGInterface, cyclicACMIGAMGInterface, cyclicAMIGAMGInterface, and regionCoupledBaseGAMGInterface.
Referenced by lduInterface::initInternalFieldTransfer().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/lduInterface.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterface/lduInterface.C