OpenFOAM: diagonalPreconditioner Class Reference
diagonalPreconditioner Class Reference
Diagonal preconditioner for both symmetric and asymmetric matrices.
Public Member Functions
TypeName ("diagonal")
Runtime type information.
diagonalPreconditioner (const lduMatrix::solver &, const dictionary &solverControlsUnused)
Construct from matrix components and preconditioner solver controls.
virtual ~diagonalPreconditioner ()
Destructor.
virtual void precondition (scalarField &wA, const scalarField &rA, const direction cmpt=0) const
Return wA the preconditioned form of residual rA.
virtual void preconditionT (scalarField &wT, const scalarField &rT, const direction cmpt=0) const
Return wT the transpose-matrix preconditioned form of residual rT.
Public Member Functions inherited from lduMatrix::preconditioner
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
preconditioner (const solver &sol)
virtual ~preconditioner ()
Destructor.
virtual void read (const dictionary &)
Read and reset the preconditioner parameters.
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::preconditioner
static word getName (const dictionary &)
Find the preconditioner name (directly or from a sub-dictionary)
static autoPtr< preconditioner > New (const solver &sol, const dictionary &solverControls)
Return a new preconditioner.
Protected Attributes inherited from lduMatrix::preconditioner
const solver & solver_
Reference to the base-solver this preconditioner is used with.
Detailed Description
Diagonal preconditioner for both symmetric and asymmetric matrices.
The reciprocal of the diagonal is calculated and stored for reuse because on most systems '*' is faster than '/'.
Source files
diagonalPreconditioner.H
diagonalPreconditioner.C
Definition at line 51 of file diagonalPreconditioner.H.
Constructor & Destructor Documentation
diagonalPreconditioner()
diagonalPreconditioner (const lduMatrix::solver & sol, const dictionary & solverControlsUnused)
Construct from matrix components and preconditioner solver controls.
Definition at line 47 of file diagonalPreconditioner.C.
References diagonalPreconditioner::precondition().
~diagonalPreconditioner()
virtual ~diagonalPreconditioner () inline virtual
Destructor.
Definition at line 87 of file diagonalPreconditioner.H.
References diagonalPreconditioner::precondition(), and diagonalPreconditioner::preconditionT().
Member Function Documentation
TypeName()
TypeName ("diagonal")
Runtime type information.
precondition()
void precondition (scalarField & wA, const scalarField & rA, const direction cmpt = 0) const virtual
Return wA the preconditioned form of residual rA.
Implements lduMatrix::preconditioner.
Definition at line 71 of file diagonalPreconditioner.C.
References UList< T >::begin(), and List< T >::size().
Referenced by diagonalPreconditioner::diagonalPreconditioner(), diagonalPreconditioner::preconditionT(), and diagonalPreconditioner::~diagonalPreconditioner().
preconditionT()
virtual void preconditionT (scalarField & wT, const scalarField & rT, const direction cmpt = 0) const inline virtual
Return wT the transpose-matrix preconditioned form of residual rT.
Reimplemented from lduMatrix::preconditioner.
Definition at line 103 of file diagonalPreconditioner.H.
References diagonalPreconditioner::precondition().
Referenced by diagonalPreconditioner::~diagonalPreconditioner().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/preconditioners/diagonalPreconditioner/diagonalPreconditioner.H
src/OpenFOAM/matrices/lduMatrix/preconditioners/diagonalPreconditioner/diagonalPreconditioner.C