OpenFOAM: lduInterfaceField Class Reference
lduInterfaceField Class Reference abstract
An abstract base class for implicitly-coupled interface fields e.g. processor and cyclic patch fields.
Public Member Functions
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
virtual void updateInterfaceMatrix (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const =0
Update result field based on interface functionality.
Detailed Description
An abstract base class for implicitly-coupled interface fields e.g. processor and cyclic patch fields.
Source files
lduInterfaceField.H
lduInterfaceField.C
Definition at line 55 of file lduInterfaceField.H.
Constructor & Destructor Documentation
lduInterfaceField()
lduInterfaceField (const lduInterface & patch) inline
Construct given coupled patch.
Definition at line 85 of file lduInterfaceField.H.
References lduInterfaceField::~lduInterfaceField().
~lduInterfaceField()
~lduInterfaceField () virtual
Destructor.
Definition at line 38 of file lduInterfaceField.C.
Referenced by lduInterfaceField::lduInterfaceField().
Member Function Documentation
TypeName()
TypeName ("lduInterfaceField")
Runtime type information.
interface()
const lduInterface& interface () const inline
Return the interface.
Definition at line 101 of file lduInterfaceField.H.
Referenced by procLduInterface::procLduInterface().
interfaceFieldType()
virtual const word& interfaceFieldType () const inline virtual
Return the interface type.
Reimplemented in energyRegionCoupledFvPatchScalarField, jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
Definition at line 107 of file lduInterfaceField.H.
References Foam::type().
Referenced by GAMGInterfaceField::New().
updatedMatrix() [1/2]
bool updatedMatrix () const inline
Whether matrix has been updated.
Definition at line 116 of file lduInterfaceField.H.
Referenced by processorGAMGInterfaceField::initInterfaceMatrixUpdate(), processorFvPatchField< Type >::initInterfaceMatrixUpdate(), processorGAMGInterfaceField::updateInterfaceMatrix(), and processorFvPatchField< Type >::updateInterfaceMatrix().
updatedMatrix() [2/2]
bool& updatedMatrix () inline
Whether matrix has been updated.
Definition at line 122 of file lduInterfaceField.H.
ready()
virtual bool ready () const inline virtual
Is all data available.
Reimplemented in processorFvPatchField< Type >.
Definition at line 128 of file lduInterfaceField.H.
References lduInterfaceField::initInterfaceMatrixUpdate().
Referenced by processorFvPatchField< Type >::processorFvPatchField().
initInterfaceMatrixUpdate()
virtual void initInterfaceMatrixUpdate (scalarField & , const scalarField & , const scalarField & , const direction , const Pstream::commsTypes commsType) const inline virtual
Initialise neighbour matrix update.
Reimplemented in processorFvPatchField< Type >, processorGAMGInterfaceField, processorFvPatchField< Type >, and processorFvPatchField< Type >.
Definition at line 135 of file lduInterfaceField.H.
References lduInterfaceField::updateInterfaceMatrix().
Referenced by LduInterfaceField< Type >::LduInterfaceField(), and lduInterfaceField::ready().
updateInterfaceMatrix()
virtual void updateInterfaceMatrix (scalarField & , const scalarField & , const scalarField & , const direction , const Pstream::commsTypes commsType) const pure virtual
Update result field based on interface functionality.
Implemented in energyRegionCoupledFvPatchScalarField, processorFvPatchField< Type >, coupledFvPatchField< Type >, coupledFvPatchField< scalar >, cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, jumpCyclicFvPatchField< Type >, cyclicGAMGInterfaceField, processorGAMGInterfaceField, jumpCyclicAMIFvPatchField< Type >, jumpCyclicFvPatchField< Type >, cyclicACMIGAMGInterfaceField, cyclicAMIGAMGInterfaceField, regionCoupledWallGAMGInterfaceField, regionCoupledGAMGInterfaceField, processorFvPatchField< Type >, processorFvPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
Referenced by LduInterfaceField< Type >::initInterfaceMatrixUpdate(), and lduInterfaceField::initInterfaceMatrixUpdate().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/lduInterfaceField/lduInterfaceField.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/lduInterfaceField/lduInterfaceField.C