OpenFOAM: FDICPreconditioner Class Reference
FDICPreconditioner Class Reference
Faster version of the DICPreconditioner diagonal-based incomplete Cholesky preconditioner for symmetric matrices (symmetric equivalent of DILU) in which the the reciprocal of the preconditioned diagonal and the upper coefficients divided by the diagonal are calculated and stored.
Public Member Functions
TypeName ("FDIC")
Runtime type information.
FDICPreconditioner (const lduMatrix::solver &, const dictionary &solverControlsUnused)
Construct from matrix components and preconditioner solver controls.
virtual ~FDICPreconditioner ()
Destructor.
virtual void precondition (scalarField &wA, const scalarField &rA, const direction cmpt=0) const
Return wA the preconditioned form of residual rA.
Public Member Functions inherited from lduMatrix::preconditioner
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &solverControls),(sol, solverControls))
preconditioner (const solver &sol)
virtual ~preconditioner ()
Destructor.
virtual void read (const dictionary &)
Read and reset the preconditioner parameters.
virtual void preconditionT (scalarField &wT, const scalarField &rT, const direction cmpt=0) const
Return wT the transpose-matrix preconditioned form of.
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::preconditioner
static word getName (const dictionary &)
Find the preconditioner name (directly or from a sub-dictionary)
static autoPtr< preconditioner > New (const solver &sol, const dictionary &solverControls)
Return a new preconditioner.
Protected Attributes inherited from lduMatrix::preconditioner
const solver & solver_
Reference to the base-solver this preconditioner is used with.
Detailed Description
Faster version of the DICPreconditioner diagonal-based incomplete Cholesky preconditioner for symmetric matrices (symmetric equivalent of DILU) in which the the reciprocal of the preconditioned diagonal and the upper coefficients divided by the diagonal are calculated and stored.
Source files
FDICPreconditioner.H
FDICPreconditioner.C
Definition at line 52 of file FDICPreconditioner.H.
Constructor & Destructor Documentation
FDICPreconditioner()
FDICPreconditioner (const lduMatrix::solver & sol, const dictionary & solverControlsUnused)
Construct from matrix components and preconditioner solver controls.
Definition at line 43 of file FDICPreconditioner.C.
References FDICPreconditioner::precondition(), and Foam::sqr().
~FDICPreconditioner()
virtual ~FDICPreconditioner () inline virtual
Destructor.
Definition at line 90 of file FDICPreconditioner.H.
References FDICPreconditioner::precondition().
Member Function Documentation
TypeName()
TypeName ("FDIC")
Runtime type information.
precondition()
void precondition (scalarField & wA, const scalarField & rA, const direction cmpt = 0) const virtual
Return wA the preconditioned form of residual rA.
Implements lduMatrix::preconditioner.
Definition at line 89 of file FDICPreconditioner.C.
References UList< T >::begin(), and List< T >::size().
Referenced by FDICPreconditioner::FDICPreconditioner(), and FDICPreconditioner::~FDICPreconditioner().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/preconditioners/FDICPreconditioner/FDICPreconditioner.H
src/OpenFOAM/matrices/lduMatrix/preconditioners/FDICPreconditioner/FDICPreconditioner.C