OpenFOAM: GAMGInterface Class Reference
GAMGInterface Class Reference abstract
Abstract base class for GAMG agglomerated interfaces.
Public Member Functions
TypeName ("GAMGInterface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterface, lduInterface,(const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm),(index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr, GAMGInterface, Istream,(const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is),(index, coarseInterfaces, is))
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces)
Construct from interfaces, restrict addressing set later on.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddressing)
Construct from interfaces and restrict addressing.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Construct from Istream.
virtual label size () const
Return size.
virtual label index () const
virtual const lduInterfacePtrsList & coarseInterfaces () const
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual const labelList & faceRestrictAddressing () const
Return (local)face restrict addressing.
virtual labelList & faceRestrictAddressing ()
Return non-const access to face restrict addressing.
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData) const
Return the interface internal field of the given field.
template<class Type >
void interfaceInternalField (const UList< Type > &internalData, List< Type > &) const
Get the interface internal field of the given field.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
void combine (const GAMGInterface &)
Merge the next level with this level.
virtual tmp< scalarField > agglomerateCoeffs (const scalarField &fineCoeffs) const
Agglomerating the given fine-level coefficients and return.
virtual void write (Ostream &) const =0
Write to stream.
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF) const
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const =0
Transfer and return internal field adjacent to the interface.
Static Public Member Functions
static autoPtr< GAMGInterface > New (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterface > New (const word &coupleType, const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Return a pointer to a new interface created on freestore given.
Protected Attributes
const label index_
My index in coarseInterfaces.
const lduInterfacePtrsList & coarseInterfaces_
All interfaces.
labelList faceCells_
Face-cell addressing.
labelList faceRestrictAddressing_
Face restrict addressing.
Detailed Description
Abstract base class for GAMG agglomerated interfaces.
Source files
GAMGInterface.H
GAMGInterface.C
newAmgInterface.C
Definition at line 51 of file GAMGInterface.H.
Constructor & Destructor Documentation
GAMGInterface() [1/3]
GAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces) inline
Construct from interfaces, restrict addressing set later on.
Definition at line 165 of file GAMGInterface.H.
GAMGInterface() [2/3]
GAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const labelUList & faceCells, const labelUList & faceRestrictAddressing) inline
Construct from interfaces and restrict addressing.
Definition at line 177 of file GAMGInterface.H.
GAMGInterface() [3/3]
GAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, Istream & is)
Construct from Istream.
Definition at line 41 of file GAMGInterface.C.
Member Function Documentation
TypeName()
TypeName ("GAMGInterface")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , GAMGInterface , lduInterface , (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm) , (index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , GAMGInterface , Istream , (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is) , (index, coarseInterfaces, is))
New() [1/2]
Foam::autoPtr< Foam::GAMGInterface > New (const label index, const lduInterfacePtrsList & coarseInterfaces, const lduInterface & fineInterface, const labelField & localRestrictAddressing, const labelField & neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm) static
Return a pointer to a new interface created on freestore given.
the fine interface
Definition at line 34 of file GAMGInterfaceNew.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by GAMGSolver::GAMGSolver(), and lduPrimitiveMesh::gather().
New() [2/2]
Foam::autoPtr< Foam::GAMGInterface > New (const word & coupleType, const label index, const lduInterfacePtrsList & coarseInterfaces, Istream & is) static
Return a pointer to a new interface created on freestore given.
the fine interface
Definition at line 75 of file GAMGInterfaceNew.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
size()
virtual label size () const inline virtual
Return size.
Definition at line 205 of file GAMGInterface.H.
References List< T >::size().
Referenced by regionCoupledGAMGInterfaceField::size(), regionCoupledWallGAMGInterfaceField::size(), cyclicGAMGInterfaceField::size(), cyclicAMIGAMGInterfaceField::size(), cyclicACMIGAMGInterfaceField::size(), and processorGAMGInterfaceField::size().
index()
virtual label index () const inline virtual
Definition at line 210 of file GAMGInterface.H.
References GAMGInterface::index_.
Referenced by regionCoupledBaseGAMGInterface::nbrLduInterface().
coarseInterfaces()
virtual const lduInterfacePtrsList& coarseInterfaces () const inline virtual
Definition at line 215 of file GAMGInterface.H.
References GAMGInterface::coarseInterfaces_.
faceCells()
virtual const labelUList& faceCells () const inline virtual
Return faceCell addressing.
Implements lduInterface.
Definition at line 221 of file GAMGInterface.H.
References GAMGInterface::faceCells_.
Referenced by cyclicACMIGAMGInterface::internalFieldTransfer(), cyclicAMIGAMGInterface::internalFieldTransfer(), and cyclicGAMGInterface::internalFieldTransfer().
faceRestrictAddressing() [1/2]
virtual const labelList& faceRestrictAddressing () const inline virtual
Return (local)face restrict addressing.
Definition at line 227 of file GAMGInterface.H.
References GAMGInterface::faceRestrictAddressing_.
faceRestrictAddressing() [2/2]
virtual labelList& faceRestrictAddressing () inline virtual
Return non-const access to face restrict addressing.
Definition at line 233 of file GAMGInterface.H.
References GAMGInterface::agglomerateCoeffs(), GAMGInterface::combine(), GAMGInterface::faceRestrictAddressing_, GAMGInterface::interfaceInternalField(), and GAMGInterface::write().
interfaceInternalField() [1/4]
tmp<Field<Type> > interfaceInternalField (const UList< Type > & internalData) const
Return the interface internal field of the given field.
Referenced by GAMGInterface::combine(), GAMGInterface::faceRestrictAddressing(), and GAMGInterface::interfaceInternalField().
interfaceInternalField() [2/4]
void interfaceInternalField (const UList< Type > & internalData, List< Type > & result) const
Get the interface internal field of the given field.
Definition at line 44 of file GAMGInterfaceTemplates.C.
References forAll, and List< T >::setSize().
interfaceInternalField() [3/4]
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements lduInterface.
Definition at line 70 of file GAMGInterface.C.
References GAMGInterface::agglomerateCoeffs().
combine()
void combine (const GAMGInterface & coarseGi)
Merge the next level with this level.
combining the face-restrict addressing and copying the face-cell addressing
Definition at line 56 of file GAMGInterface.C.
References GAMGInterface::faceCells_, GAMGInterface::faceRestrictAddressing_, forAll, and GAMGInterface::interfaceInternalField().
Referenced by GAMGAgglomeration::combineLevels(), and GAMGInterface::faceRestrictAddressing().
agglomerateCoeffs()
Foam::tmp< Foam::scalarField > agglomerateCoeffs (const scalarField & fineCoeffs) const virtual
Agglomerating the given fine-level coefficients and return.
Definition at line 79 of file GAMGInterface.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), tmp< T >::ref(), and List< T >::size().
Referenced by GAMGInterface::faceRestrictAddressing(), and GAMGInterface::interfaceInternalField().
write()
void write (Ostream & os) const pure virtual
Write to stream.
Implemented in processorGAMGInterface, cyclicGAMGInterface, cyclicACMIGAMGInterface, cyclicAMIGAMGInterface, regionCoupledWallGAMGInterface, and regionCoupledGAMGInterface.
Definition at line 112 of file GAMGInterface.C.
References token::SPACE.
Referenced by GAMGInterface::faceRestrictAddressing(), cyclicGAMGInterface::write(), and processorGAMGInterface::write().
interfaceInternalField() [4/4]
Foam::tmp<Foam::Field<Type> > interfaceInternalField (const UList< Type > & iF) const
Definition at line 32 of file GAMGInterfaceTemplates.C.
References GAMGInterface::interfaceInternalField(), and tmp< T >::ref().
Member Data Documentation
index_
const label index_ protected
My index in coarseInterfaces.
Definition at line 61 of file GAMGInterface.H.
Referenced by GAMGInterface::index().
coarseInterfaces_
const lduInterfacePtrsList& coarseInterfaces_ protected
All interfaces.
Definition at line 64 of file GAMGInterface.H.
Referenced by GAMGInterface::coarseInterfaces(), cyclicAMIGAMGInterface::neighbPatch(), cyclicACMIGAMGInterface::neighbPatch(), and cyclicGAMGInterface::neighbPatch().
faceCells_
labelList faceCells_ protected
Face-cell addressing.
Definition at line 67 of file GAMGInterface.H.
Referenced by GAMGInterface::combine(), and GAMGInterface::faceCells().
faceRestrictAddressing_
labelList faceRestrictAddressing_ protected
Face restrict addressing.
Definition at line 70 of file GAMGInterface.H.
Referenced by GAMGInterface::combine(), and GAMGInterface::faceRestrictAddressing().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterface.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterface.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterfaceNew.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterfaceTemplates.C