OpenFOAM: processorGAMGInterfaceField Class Reference
processorGAMGInterfaceField Class Reference
GAMG agglomerated processor interface field.
Public Member Functions
TypeName ("processor")
Runtime type information.
processorGAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
Construct from GAMG interface and fine level interface field.
processorGAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
virtual ~processorGAMGInterfaceField ()
Destructor.
label size () const
Return size.
virtual void initInterfaceMatrixUpdate (scalarField &result, const scalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
virtual void updateInterfaceMatrix (scalarField &result, const scalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
Update result field based on interface functionality.
virtual label comm () const
Processor interface functions.
virtual int myProcNo () const
Return processor number.
virtual int neighbProcNo () const
Return neigbour processor number.
virtual bool doTransform () const
Does the interface field perform the transfromation.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual int rank () const
Return rank of component for transform.
Public Member Functions inherited from GAMGInterfaceField
TypeName ("GAMGInterfaceField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterfaceField,(const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface),(GAMGCp, fineInterface))
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterface,(const GAMGInterface &GAMGCp, const bool doTransform, const int rank),(GAMGCp, doTransform, rank))
GAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &)
Construct from GAMG interface and fine level interface field.
GAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
const GAMGInterface & interface () const
Return interface.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
Public Member Functions inherited from processorLduInterfaceField
TypeName ("processorLduInterfaceField")
Runtime type information.
processorLduInterfaceField ()
Construct given coupled patch.
virtual ~processorLduInterfaceField ()
Destructor.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &f, const direction cmpt) const
Transform given patch component field.
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterfaceField
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Return a pointer to a new interface created on freestore given.
Detailed Description
GAMG agglomerated processor interface field.
Source files
processorGAMGInterfaceField.H
processorGAMGInterfaceField.C
Definition at line 50 of file processorGAMGInterfaceField.H.
Constructor & Destructor Documentation
processorGAMGInterfaceField() [1/2]
processorGAMGInterfaceField (const GAMGInterface & GAMGCp, const lduInterfaceField & fineInterface)
Construct from GAMG interface and fine level interface field.
Definition at line 53 of file processorGAMGInterfaceField.C.
References processorLduInterfaceField::doTransform(), p, and processorLduInterfaceField::rank().
processorGAMGInterfaceField() [2/2]
processorGAMGInterfaceField (const GAMGInterface & GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
Definition at line 72 of file processorGAMGInterfaceField.C.
~processorGAMGInterfaceField()
~processorGAMGInterfaceField () virtual
Destructor.
Definition at line 87 of file processorGAMGInterfaceField.C.
References processorGAMGInterfaceField::initInterfaceMatrixUpdate().
Member Function Documentation
TypeName()
TypeName ("processor")
Runtime type information.
size()
label size () const inline
Return size.
Definition at line 125 of file processorGAMGInterfaceField.H.
References processorGAMGInterfaceField::initInterfaceMatrixUpdate(), GAMGInterface::size(), and processorGAMGInterfaceField::updateInterfaceMatrix().
initInterfaceMatrixUpdate()
void initInterfaceMatrixUpdate (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Initialise neighbour matrix update.
Reimplemented from lduInterfaceField.
Definition at line 94 of file processorGAMGInterfaceField.C.
References UPstream::floatTransfer, UPstream::nonBlocking, UPstream::nRequests(), UIPstream::read(), lduInterfaceField::updatedMatrix(), processorGAMGInterfaceField::updateInterfaceMatrix(), UPstream::warnComm, and UOPstream::write().
Referenced by processorGAMGInterfaceField::size(), and processorGAMGInterfaceField::~processorGAMGInterfaceField().
updateInterfaceMatrix()
void updateInterfaceMatrix (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Update result field based on interface functionality.
Implements lduInterfaceField.
Definition at line 145 of file processorGAMGInterfaceField.C.
References UPstream::floatTransfer, forAll, UPstream::nonBlocking, UPstream::nRequests(), List< T >::size(), lduInterfaceField::updatedMatrix(), UPstream::waitRequest(), and UPstream::warnComm.
Referenced by processorGAMGInterfaceField::initInterfaceMatrixUpdate(), and processorGAMGInterfaceField::size().
comm()
virtual label comm () const inline virtual
Processor interface functions.
Return communicator used for comms
Implements processorLduInterfaceField.
Definition at line 157 of file processorGAMGInterfaceField.H.
References processorGAMGInterface::comm().
myProcNo()
virtual int myProcNo () const inline virtual
Return processor number.
Implements processorLduInterfaceField.
Definition at line 163 of file processorGAMGInterfaceField.H.
References processorGAMGInterface::myProcNo().
neighbProcNo()
virtual int neighbProcNo () const inline virtual
Return neigbour processor number.
Implements processorLduInterfaceField.
Definition at line 169 of file processorGAMGInterfaceField.H.
References processorGAMGInterface::neighbProcNo().
doTransform()
virtual bool doTransform () const inline virtual
Does the interface field perform the transfromation.
Implements processorLduInterfaceField.
Definition at line 175 of file processorGAMGInterfaceField.H.
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements processorLduInterfaceField.
Definition at line 181 of file processorGAMGInterfaceField.H.
References processorGAMGInterface::forwardT().
rank()
virtual int rank () const inline virtual
Return rank of component for transform.
Implements processorLduInterfaceField.
Definition at line 187 of file processorGAMGInterfaceField.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaceFields/processorGAMGInterfaceField/processorGAMGInterfaceField.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaceFields/processorGAMGInterfaceField/processorGAMGInterfaceField.C