OpenFOAM: LduInterfaceField< Type > Class Template Reference
LduInterfaceField< Type > Class Template Reference abstract
An abstract base class for implicitly-coupled interface fields e.g. processor and cyclic patch fields.
Public Member Functions
TypeName ("LduInterfaceField")
Runtime type information.
LduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~LduInterfaceField ()
Destructor.
virtual void initInterfaceMatrixUpdate (Field< Type > &, const Field< Type > &, const scalarField &, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
virtual void updateInterfaceMatrix (Field< Type > &, const Field< Type > &, const scalarField &, const Pstream::commsTypes commsType) const =0
Update result field based on interface functionality.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
virtual void updateInterfaceMatrix (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const =0
Update result field based on interface functionality.
Detailed Description
template<class Type>
class Foam::LduInterfaceField< Type >
An abstract base class for implicitly-coupled interface fields e.g. processor and cyclic patch fields.
Source files
LduInterfaceField.H
LduInterfaceField.C
Definition at line 56 of file LduInterfaceField.H.
Constructor & Destructor Documentation
LduInterfaceField()
LduInterfaceField (const lduInterface & patch) inline
Construct given coupled patch.
Definition at line 78 of file LduInterfaceField.H.
References LduInterfaceField< Type >::initInterfaceMatrixUpdate(), lduInterfaceField::initInterfaceMatrixUpdate(), and LduInterfaceField< Type >::~LduInterfaceField().
~LduInterfaceField()
~LduInterfaceField () virtual
Destructor.
Definition at line 29 of file LduInterfaceField.C.
Referenced by LduInterfaceField< Type >::LduInterfaceField().
Member Function Documentation
TypeName()
TypeName ("LduInterfaceField< Type >")
Runtime type information.
initInterfaceMatrixUpdate()
virtual void initInterfaceMatrixUpdate (Field< Type > & , const Field< Type > & , const scalarField & , const Pstream::commsTypes commsType) const inline virtual
Initialise neighbour matrix update.
Reimplemented in processorFvPatchField< Type >.
Definition at line 97 of file LduInterfaceField.H.
References LduInterfaceField< Type >::updateInterfaceMatrix(), and lduInterfaceField::updateInterfaceMatrix().
Referenced by LduInterfaceField< Type >::LduInterfaceField().
updateInterfaceMatrix()
virtual void updateInterfaceMatrix (Field< Type > & , const Field< Type > & , const scalarField & , const Pstream::commsTypes commsType) const pure virtual
Update result field based on interface functionality.
Implemented in processorFvPatchField< Type >, coupledFvPatchField< Type >, cyclicACMIFvPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
Referenced by LduInterfaceField< Type >::initInterfaceMatrixUpdate().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduInterfaceField/LduInterfaceField.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduInterfaceField/LduInterfaceField.C