OpenFOAM: manualGAMGProcAgglomeration Class Reference
manualGAMGProcAgglomeration Class Reference
Manual processor agglomeration of GAMGAgglomerations.
Public Member Functions
TypeName ("manual")
Runtime type information.
manualGAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
Construct given agglomerator and controls.
virtual ~manualGAMGProcAgglomeration ()
Destructor.
virtual bool agglomerate ()
Modify agglomeration. Return true if modified.
Public Member Functions inherited from GAMGProcAgglomeration
TypeName ("GAMGProcAgglomeration")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGProcAgglomeration, GAMGAgglomeration,(GAMGAgglomeration &agglom, const dictionary &controlDict),(agglom, controlDict))
Runtime selection table for pure geometric agglomerators.
GAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
Construct given agglomerator and controls.
virtual ~GAMGProcAgglomeration ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from GAMGProcAgglomeration
static autoPtr< GAMGProcAgglomeration > New (const word &type, GAMGAgglomeration &agglom, const dictionary &controlDict)
Return the selected agglomerator.
Protected Member Functions inherited from GAMGProcAgglomeration
void printStats (Ostream &os, GAMGAgglomeration &agglom) const
Debug: write agglomeration info.
bool agglomerate (const label fineLevelIndex, const labelList &procAgglomMap, const labelList &masterProcs, const List< label > &agglomProcIDs, const label procAgglomComm)
Agglomerate a level. Return true if anything has changed.
Static Protected Member Functions inherited from GAMGProcAgglomeration
static labelListList globalCellCells (const lduMesh &)
Debug: calculate global cell-cells.
Protected Attributes inherited from GAMGProcAgglomeration
GAMGAgglomeration & agglom_
Reference to agglomeration.
Detailed Description
Manual processor agglomeration of GAMGAgglomerations.
In the GAMG control dictionary:
processorAgglomerator manual; List of level+procagglomeration where procagglomeration is a set of labelLists. Each labelList is a cluster of processor which gets combined onto the first element in the list. processorAgglomeration ((3 //at level 3 ((0 1) //coarse 0 from 0,1 (and moved onto 0) (3 2) //coarse 1 from 2,3 (and moved onto 3))) (6 //at level6 ((0 1) //coarse 0 from 0,1 (and moved onto 0))));
Source files
manualGAMGProcAgglomeration.H
manualGAMGProcAgglomeration.C
Definition at line 76 of file manualGAMGProcAgglomeration.H.
Constructor & Destructor Documentation
manualGAMGProcAgglomeration()
manualGAMGProcAgglomeration (GAMGAgglomeration & agglom, const dictionary & controlDict)
Construct given agglomerator and controls.
Definition at line 51 of file manualGAMGProcAgglomeration.C.
References manualGAMGProcAgglomeration::~manualGAMGProcAgglomeration().
~manualGAMGProcAgglomeration()
~manualGAMGProcAgglomeration () virtual
Destructor.
Definition at line 64 of file manualGAMGProcAgglomeration.C.
References forAllReverse, and UPstream::freeCommunicator().
Referenced by manualGAMGProcAgglomeration::manualGAMGProcAgglomeration().
Member Function Documentation
TypeName()
TypeName ("manual")
Runtime type information.
agglomerate()
bool agglomerate () virtual
Modify agglomeration. Return true if modified.
Implements GAMGProcAgglomeration.
Definition at line 78 of file manualGAMGProcAgglomeration.C.
References GAMGProcAgglomeration::agglomerate(), UPstream::allocateCommunicator(), lduMesh::comm(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), forAll, UList< T >::last(), UPstream::myProcNo(), Foam::nl, UPstream::nProcs(), Foam::Pout, Foam::Swap(), and WarningInFunction.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/manualGAMGProcAgglomeration/manualGAMGProcAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/manualGAMGProcAgglomeration/manualGAMGProcAgglomeration.C