OpenFOAM: cyclicGAMGInterfaceField Class Reference
cyclicGAMGInterfaceField Class Reference
GAMG agglomerated cyclic interface field.
Public Member Functions
TypeName ("cyclic")
Runtime type information.
cyclicGAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterfaceField)
Construct from GAMG interface and fine level interface field.
cyclicGAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
virtual ~cyclicGAMGInterfaceField ()
Destructor.
label size () const
Return size.
virtual bool doTransform () const
Cyclic interface functions.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual int rank () const
Return rank of component for transform.
virtual void updateInterfaceMatrix (scalarField &result, const scalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
Update result field based on interface functionality.
Public Member Functions inherited from GAMGInterfaceField
TypeName ("GAMGInterfaceField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterfaceField,(const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface),(GAMGCp, fineInterface))
declareRunTimeSelectionTable (autoPtr, GAMGInterfaceField, lduInterface,(const GAMGInterface &GAMGCp, const bool doTransform, const int rank),(GAMGCp, doTransform, rank))
GAMGInterfaceField (const GAMGInterface &GAMGCp, const lduInterfaceField &)
Construct from GAMG interface and fine level interface field.
GAMGInterfaceField (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
const GAMGInterface & interface () const
Return interface.
Public Member Functions inherited from lduInterfaceField
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (scalarField &, const scalarField &, const scalarField &, const direction, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update.
Public Member Functions inherited from cyclicLduInterfaceField
TypeName ("cyclicLduInterfaceField")
Runtime type information.
cyclicLduInterfaceField ()
Construct given coupled patch.
virtual ~cyclicLduInterfaceField ()
Destructor.
template<class Type >
void transformCoupleField (Field< Type > &f) const
Transform given patch field.
void transformCoupleField (scalarField &f, const direction cmpt) const
Transform given patch component field.
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterfaceField
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const lduInterfaceField &fineInterface)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterfaceField > New (const GAMGInterface &GAMGCp, const bool doTransform, const int rank)
Return a pointer to a new interface created on freestore given.
Detailed Description
GAMG agglomerated cyclic interface field.
Source files
cyclicGAMGInterfaceField.H
cyclicGAMGInterfaceField.C
Definition at line 50 of file cyclicGAMGInterfaceField.H.
Constructor & Destructor Documentation
cyclicGAMGInterfaceField() [1/2]
cyclicGAMGInterfaceField (const GAMGInterface & GAMGCp, const lduInterfaceField & fineInterfaceField)
Construct from GAMG interface and fine level interface field.
Definition at line 69 of file cyclicGAMGInterfaceField.C.
References cyclicLduInterfaceField::doTransform(), p, and cyclicLduInterfaceField::rank().
cyclicGAMGInterfaceField() [2/2]
cyclicGAMGInterfaceField (const GAMGInterface & GAMGCp, const bool doTransform, const int rank)
Construct from GAMG interface and fine level interface field.
Definition at line 88 of file cyclicGAMGInterfaceField.C.
~cyclicGAMGInterfaceField()
~cyclicGAMGInterfaceField () virtual
Destructor.
Definition at line 103 of file cyclicGAMGInterfaceField.C.
References cyclicGAMGInterfaceField::updateInterfaceMatrix().
Member Function Documentation
TypeName()
TypeName ("cyclic")
Runtime type information.
size()
label size () const inline
Return size.
Definition at line 109 of file cyclicGAMGInterfaceField.H.
References GAMGInterface::size().
doTransform()
virtual bool doTransform () const inline virtual
Cyclic interface functions.
Does the interface field perform the transfromation
Implements cyclicLduInterfaceField.
Definition at line 118 of file cyclicGAMGInterfaceField.H.
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements cyclicLduInterfaceField.
Definition at line 124 of file cyclicGAMGInterfaceField.H.
References cyclicGAMGInterface::forwardT().
reverseT()
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Implements cyclicLduInterfaceField.
Definition at line 130 of file cyclicGAMGInterfaceField.H.
References cyclicGAMGInterface::reverseT().
rank()
virtual int rank () const inline virtual
Return rank of component for transform.
Implements cyclicLduInterfaceField.
Definition at line 136 of file cyclicGAMGInterfaceField.H.
References cyclicGAMGInterfaceField::updateInterfaceMatrix().
updateInterfaceMatrix()
void updateInterfaceMatrix (scalarField & result, const scalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const virtual
Update result field based on interface functionality.
Implements lduInterfaceField.
Definition at line 110 of file cyclicGAMGInterfaceField.C.
References forAll.
Referenced by cyclicGAMGInterfaceField::rank(), and cyclicGAMGInterfaceField::~cyclicGAMGInterfaceField().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaceFields/cyclicGAMGInterfaceField/cyclicGAMGInterfaceField.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaceFields/cyclicGAMGInterfaceField/cyclicGAMGInterfaceField.C