OpenFOAM: GAMGSolver Class Reference
GAMGSolver Class Reference
Geometric agglomerated algebraic multigrid solver.
Public Member Functions
TypeName ("GAMG")
Runtime type information.
GAMGSolver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Construct from lduMatrix and solver controls.
virtual ~GAMGSolver ()
Destructor.
virtual solverPerformance solve (scalarField &psi, const scalarField &source, const direction cmpt=0) const
Solve.
Public Member Functions inherited from lduMatrix::solver
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls),(fieldName, matrix, interfaceBouCoeffs, interfaceIntCoeffs, interfaces, solverControls))
solver (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
virtual ~solver ()
Destructor.
const word & fieldName () const
const lduMatrix & matrix () const
const FieldField< Field, scalar > & interfaceBouCoeffs () const
const FieldField< Field, scalar > & interfaceIntCoeffs () const
const lduInterfaceFieldPtrsList & interfaces () const
virtual void read (const dictionary &)
Read and reset the solver parameters from the given stream.
scalar normFactor (const scalarField &psi, const scalarField &source, const scalarField &Apsi, scalarField &tmpField) const
Return the matrix norm used to normalise the residual for the.
Friends
class GAMGPreconditioner
Additional Inherited Members
Static Public Member Functions inherited from lduMatrix::solver
static autoPtr< solver > New (const word &fieldName, const lduMatrix &matrix, const FieldField< Field, scalar > &interfaceBouCoeffs, const FieldField< Field, scalar > &interfaceIntCoeffs, const lduInterfaceFieldPtrsList &interfaces, const dictionary &solverControls)
Return a new solver.
Protected Attributes inherited from lduMatrix::solver
word fieldName_
const lduMatrix & matrix_
const FieldField< Field, scalar > & interfaceBouCoeffs_
const FieldField< Field, scalar > & interfaceIntCoeffs_
lduInterfaceFieldPtrsList interfaces_
dictionary controlDict_
Dictionary of controls.
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
scalar tolerance_
Final convergence tolerance.
scalar relTol_
Convergence tolerance relative to the initial.
Detailed Description
Geometric agglomerated algebraic multigrid solver.
Characteristics:
Requires positive definite, diagonally dominant matrix.
Agglomeration algorithm: selectable and optionally cached.
Restriction operator: summation.
Prolongation operator: injection.
Smoother: Gauss-Seidel.
Coarse matrix creation: central coefficient: summation of fine grid central coefficients with the removal of intra-cluster face; off-diagonal coefficient: summation of off-diagonal faces.
Coarse matrix scaling: performed by correction scaling, using steepest descent optimisation.
Type of cycle: V-cycle with optional pre-smoothing.
Coarsest-level matrix solved using PCG or PBiCGStab.
Source files
GAMGSolver.H
GAMGSolver.C
GAMGSolverAgglomerateMatrix.C
GAMGSolverInterpolate.C
GAMGSolverScale.C
GAMGSolverSolve.C
Definition at line 70 of file GAMGSolver.H.
Constructor & Destructor Documentation
GAMGSolver()
GAMGSolver (const word & fieldName, const lduMatrix & matrix, const FieldField< Field, scalar > & interfaceBouCoeffs, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const dictionary & solverControls)
Construct from lduMatrix and solver controls.
Definition at line 46 of file GAMGSolver.C.
References lduMesh::comm(), lduMatrix::diag(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, lduMatrix::lower(), GAMGInterface::New(), Foam::nl, Foam::Pout, UPtrList< T >::set(), List< T >::size(), UPtrList< T >::size(), OStringStream::str(), Foam::type(), UPstream::warnComm, and write().
~GAMGSolver()
~GAMGSolver () virtual
Destructor.
Definition at line 291 of file GAMGSolver.C.
References Foam::endl(), Foam::Pout, and lduMatrix::solver::readControls().
Member Function Documentation
TypeName()
TypeName ("GAMG")
Runtime type information.
solve()
Foam::solverPerformance solve (scalarField & psi, const scalarField & source, const direction cmpt = 0) const virtual
Solve.
Implements lduMatrix::solver.
Definition at line 34 of file GAMGSolverSolve.C.
References dictionary::add(), SolverPerformance< Type >::checkConvergence(), lduMatrix::solver::controlDict_, lduMatrix::diag(), dict, Foam::endl(), lduMatrix::solver::fieldName_, SolverPerformance< Type >::finalResidual(), forAll, Foam::gSumMag(), Foam::Info, SolverPerformance< Type >::initialResidual(), lduMatrix::solver::interfaceBouCoeffs_, lduMatrix::solver::interfaceIntCoeffs_, lduMatrix::solver::interfaces_, Foam::MULES::interpolate(), messageStream::masterStream(), lduMatrix::solver::matrix_, Foam::max(), mesh, Foam::min(), GAMGAgglomeration::nCells(), lduMatrix::smoother::New(), SolverPerformance< Type >::nIterations(), Foam::Pout, SolverPerformance< Type >::print(), GAMGAgglomeration::prolongField(), lduMatrix::solver::relTol_, GAMGAgglomeration::restrictAddressing(), GAMGAgglomeration::restrictField(), PtrList< T >::set(), PtrList< T >::setSize(), List< T >::setSize(), List< T >::size(), PCG::solve(), PBiCGStab::solve(), lduMatrix::solver::tolerance_, and UPstream::warnComm.
Friends And Related Function Documentation
GAMGPreconditioner
friend class GAMGPreconditioner friend
Definition at line 320 of file GAMGSolver.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolver.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolver.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolverAgglomerateMatrix.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolverInterpolate.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolverScale.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGSolverSolve.C