OpenFOAM: procFacesGAMGProcAgglomeration Class Reference
procFacesGAMGProcAgglomeration Class Reference
Processor agglomeration of GAMGAgglomerations. Needs nAgglomeratingCells which is when to start agglomerating processors. Processors get agglomerated by constructing a single cell mesh for each processor with each processor interface a face. This then gets agglomerated using the pairGAMGAgglomeration algorithm with the number of faces on the original processor interface as face weight.
Public Member Functions
TypeName ("procFaces")
Runtime type information.
procFacesGAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
Construct given agglomerator and controls.
virtual ~procFacesGAMGProcAgglomeration ()
Destructor.
virtual bool agglomerate ()
Modify agglomeration. Return true if modified.
Public Member Functions inherited from GAMGProcAgglomeration
TypeName ("GAMGProcAgglomeration")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGProcAgglomeration, GAMGAgglomeration,(GAMGAgglomeration &agglom, const dictionary &controlDict),(agglom, controlDict))
Runtime selection table for pure geometric agglomerators.
GAMGProcAgglomeration (GAMGAgglomeration &agglom, const dictionary &controlDict)
Construct given agglomerator and controls.
virtual ~GAMGProcAgglomeration ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from GAMGProcAgglomeration
static autoPtr< GAMGProcAgglomeration > New (const word &type, GAMGAgglomeration &agglom, const dictionary &controlDict)
Return the selected agglomerator.
Protected Member Functions inherited from GAMGProcAgglomeration
void printStats (Ostream &os, GAMGAgglomeration &agglom) const
Debug: write agglomeration info.
bool agglomerate (const label fineLevelIndex, const labelList &procAgglomMap, const labelList &masterProcs, const List< label > &agglomProcIDs, const label procAgglomComm)
Agglomerate a level. Return true if anything has changed.
Static Protected Member Functions inherited from GAMGProcAgglomeration
static labelListList globalCellCells (const lduMesh &)
Debug: calculate global cell-cells.
Protected Attributes inherited from GAMGProcAgglomeration
GAMGAgglomeration & agglom_
Reference to agglomeration.
Detailed Description
Processor agglomeration of GAMGAgglomerations. Needs nAgglomeratingCells which is when to start agglomerating processors. Processors get agglomerated by constructing a single cell mesh for each processor with each processor interface a face. This then gets agglomerated using the pairGAMGAgglomeration algorithm with the number of faces on the original processor interface as face weight.
Source files
procFacesGAMGProcAgglomeration.H
procFacesGAMGProcAgglomeration.C
Definition at line 59 of file procFacesGAMGProcAgglomeration.H.
Constructor & Destructor Documentation
procFacesGAMGProcAgglomeration()
procFacesGAMGProcAgglomeration (GAMGAgglomeration & agglom, const dictionary & controlDict)
Construct given agglomerator and controls.
Definition at line 220 of file procFacesGAMGProcAgglomeration.C.
~procFacesGAMGProcAgglomeration()
~procFacesGAMGProcAgglomeration () virtual
Destructor.
Definition at line 232 of file procFacesGAMGProcAgglomeration.C.
References forAllReverse, and UPstream::freeCommunicator().
Member Function Documentation
TypeName()
TypeName ("procFaces")
Runtime type information.
agglomerate()
bool agglomerate () virtual
Modify agglomeration. Return true if modified.
Implements GAMGProcAgglomeration.
Definition at line 246 of file procFacesGAMGProcAgglomeration.C.
References GAMGProcAgglomeration::agglomerate(), UPstream::allocateCommunicator(), GAMGAgglomeration::calculateRegionMaster(), lduMesh::comm(), Foam::endl(), UList< T >::last(), Foam::nl, UPstream::nProcs(), Foam::Pout, and rndGen().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/procFacesGAMGProcAgglomeration/procFacesGAMGProcAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGProcAgglomerations/procFacesGAMGProcAgglomeration/procFacesGAMGProcAgglomeration.C