OpenFOAM: GAMGAgglomeration Class Reference
GAMGAgglomeration Class Reference
Geometric agglomerated algebraic multigrid agglomeration class.
Public Member Functions
TypeName ("GAMGAgglomeration")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, lduMesh,(const lduMesh &mesh, const dictionary &controlDict),(mesh, controlDict))
Runtime selection table for pure geometric agglomerators.
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, lduMatrix,(const lduMatrix &matrix, const dictionary &controlDict),(matrix, controlDict))
Runtime selection table for matrix or mixed geometric/matrix.
declareRunTimeSelectionTable (autoPtr, GAMGAgglomeration, geometry,(const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict),(mesh, cellVolumes, faceAreas, controlDict))
Runtime selection table for matrix or mixed geometric/matrix.
GAMGAgglomeration (const lduMesh &mesh, const dictionary &controlDict)
Construct given mesh and controls.
~GAMGAgglomeration ()
Destructor.
label size () const
const lduMesh & meshLevel (const label leveli) const
Return LDU mesh of given level.
bool hasMeshLevel (const label leveli) const
Do we have mesh for given level?
const lduInterfacePtrsList & interfaceLevel (const label leveli) const
Return LDU interface addressing of given level.
const labelField & restrictAddressing (const label leveli) const
Return cell restrict addressing of given level.
const labelList & faceRestrictAddressing (const label leveli) const
Return face restrict addressing of given level.
const labelListList & patchFaceRestrictAddressing (const label leveli) const
const boolList & faceFlipMap (const label leveli) const
Return face flip map of given level.
label nCells (const label leveli) const
Return number of coarse cells (before processor agglomeration)
label nFaces (const label leveli) const
Return number of coarse faces (before processor agglomeration)
const labelList & nPatchFaces (const label leveli) const
Return number of coarse patch faces (before processor.
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex, const bool procAgglom) const
Restrict (integrate by summation) cell field.
template<class Type >
void restrictFaceField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex) const
Restrict (integrate by summation) face field.
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const labelList &fineToCoarse) const
Restrict (integrate by summation) cell field.
template<class Type >
void prolongField (Field< Type > &ff, const Field< Type > &cf, const label coarseLevelIndex, const bool procAgglom) const
Prolong (interpolate by injection) cell field.
bool processorAgglomerate () const
Whether to agglomerate across processors.
const labelList & procAgglomMap (const label fineLeveli) const
Mapping from processor to agglomerated processor (global, all.
const labelList & agglomProcIDs (const label fineLeveli) const
Set of processors to agglomerate. Element 0 is the.
bool hasProcMesh (const label fineLeveli) const
Check that level has combined mesh.
label procCommunicator (const label fineLeveli) const
Communicator for current level or -1.
const labelList & cellOffsets (const label fineLeveli) const
Mapping from processor to procMesh cells.
const labelListList & faceMap (const label fineLeveli) const
Mapping from processor to procMesh face.
const labelListList & boundaryMap (const label fineLeveli) const
Mapping from processor to procMesh boundary.
const labelListListList & boundaryFaceMap (const label fineLeveli) const
Mapping from processor to procMesh boundary face.
Public Member Functions inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
MeshObject (const lduMesh &mesh)
virtual ~MeshObject ()
const lduMesh & mesh () const
virtual bool writeData (Foam::Ostream &) const
Public Member Functions inherited from GeometricMeshObject< lduMesh >
GeometricMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from TopologicalMeshObject< lduMesh >
TopologicalMeshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from meshObject
ClassName ("meshObject")
meshObject (const word &typeName, const objectRegistry &obr)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Static Public Member Functions
static const GAMGAgglomeration & New (const lduMesh &mesh, const dictionary &controlDict)
Return the selected geometric agglomerator.
static const GAMGAgglomeration & New (const lduMatrix &matrix, const dictionary &controlDict)
Return the selected matrix agglomerator.
static autoPtr< GAMGAgglomeration > New (const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict)
Return the selected geometric agglomerator.
static void calculateRegionMaster (const label comm, const labelList &procAgglomMap, labelList &masterProcs, List< label > &agglomProcIDs)
Given fine to coarse processor map determine:
static bool checkRestriction (labelList &newRestrict, label &nNewCoarse, const lduAddressing &fineAddressing, const labelUList &restrict, const label nCoarse)
Given restriction determines if coarse cells are connected.
Static Public Member Functions inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
static const GAMGAgglomeration & New (const lduMesh &mesh)
static const GAMGAgglomeration & New (const lduMesh &mesh, const Data1 &d)
static const GAMGAgglomeration & New (const lduMesh &mesh, const Data1 &, const Data2 &)
static const GAMGAgglomeration & New (const lduMesh &mesh, const Data1 &, const Data2 &, const Data3 &)
static const GAMGAgglomeration & New (const lduMesh &mesh, const Data1 &, const Data2 &, const Data3 &, const Data4 &)
static bool Delete (const lduMesh &mesh)
Static Public Member Functions inherited from meshObject
template<class Mesh >
static void movePoints (objectRegistry &)
template<class Mesh >
static void updateMesh (objectRegistry &, const mapPolyMesh &)
template<class Mesh , template< class > class MeshObjectType>
static void clear (objectRegistry &)
template<class Mesh , template< class > class FromType, template< class > class ToType>
static void clearUpto (objectRegistry &)
Clear all meshObject derived from FromType up to (but not including)
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Protected Member Functions
void agglomerateLduAddressing (const label fineLevelIndex)
Assemble coarse mesh addressing.
void combineLevels (const label curLevel)
Combine a level with the previous one.
void compactLevels (const label nCreatedLevels)
Shrink the number of levels to that specified.
bool continueAgglomerating (const label nCells, const label nCoarseCells) const
Check the need for further agglomeration.
void clearLevel (const label leveli)
void procAgglomerateLduAddressing (const label comm, const labelList &procAgglomMap, const labelList &procIDs, const label allMeshComm, const label levelIndex)
Collect and combine processor meshes into allMesh:
void procAgglomerateRestrictAddressing (const label comm, const labelList &procIDs, const label levelIndex)
Collect and combine basic restriction addressing:
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Member Functions
template<class Type >
static void gatherList (const label comm, const labelList &procIDs, const Type &myVal, List< Type > &allVals, const int tag=Pstream::msgType())
Gather value from all procIDs onto procIDs[0].
Protected Attributes
const label maxLevels_
Max number of levels.
const label nCellsInCoarsestLevel_
Number of cells in coarsest level.
const lduInterfacePtrsList meshInterfaces_
Cached mesh interfaces.
autoPtr< GAMGProcAgglomeration > procAgglomeratorPtr_
labelList nCells_
The number of cells in each level.
PtrList< labelField > restrictAddressing_
Cell restriction addressing array.
labelList nFaces_
The number of (coarse) faces in each level.
PtrList< labelList > faceRestrictAddressing_
Face restriction addressing array.
PtrList< boolList > faceFlipMap_
Face flip: for faces mapped to internal faces stores whether.
PtrList< labelList > nPatchFaces_
The number of (coarse) patch faces in each level.
PtrList< labelListList > patchFaceRestrictAddressing_
Patch-local face restriction addressing array.
PtrList< lduPrimitiveMesh > meshLevels_
Hierarchy of mesh addressing.
PtrList< labelList > procAgglomMap_
Per level, per processor the processor it agglomerates into.
PtrList< labelList > agglomProcIDs_
Per level the set of processors to agglomerate. Element 0 is.
labelList procCommunicator_
Communicator for given level.
PtrList< labelList > procCellOffsets_
Mapping from processor to procMeshLevel cells.
PtrList< labelListList > procFaceMap_
Mapping from processor to procMeshLevel face.
PtrList< labelListList > procBoundaryMap_
Mapping from processor to procMeshLevel boundary.
PtrList< labelListListList > procBoundaryFaceMap_
Mapping from processor to procMeshLevel boundary face.
Protected Attributes inherited from MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >
const lduMesh & mesh_
Friends
class GAMGProcAgglomeration
Declare friendship with GAMGProcAgglomeration.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Geometric agglomerated algebraic multigrid agglomeration class.
Source files
GAMGAgglomeration.H
GAMGAgglomeration.C
GAMGAgglomerationTemplates.C
GAMGAgglomerateLduAddressing.C
Definition at line 61 of file GAMGAgglomeration.H.
Constructor & Destructor Documentation
GAMGAgglomeration()
GAMGAgglomeration (const lduMesh & mesh, const dictionary & controlDict)
Construct given mesh and controls.
Definition at line 229 of file GAMGAgglomeration.C.
References GAMGAgglomeration::New().
~GAMGAgglomeration()
~GAMGAgglomeration ()
Destructor.
Definition at line 436 of file GAMGAgglomeration.C.
References GAMGAgglomeration::meshLevel().
Member Function Documentation
agglomerateLduAddressing()
void agglomerateLduAddressing (const label fineLevelIndex) protected
Assemble coarse mesh addressing.
Definition at line 33 of file GAMGAgglomerateLduAddressing.C.
References Foam::abort(), lduMesh::comm(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, forAllReverse, lduMesh::lduAddr(), lduAddressing::lowerAddr(), Foam::min(), Foam::New(), Foam::Pout, GAMGAgglomeration::procAgglomerateLduAddressing(), UPtrList< T >::set(), List< T >::setSize(), List< T >::size(), UPtrList< T >::size(), lduAddressing::size(), UList< T >::size(), and lduAddressing::upperAddr().
combineLevels()
void combineLevels (const label curLevel) protected
Combine a level with the previous one.
Definition at line 528 of file GAMGAgglomerateLduAddressing.C.
References GAMGAgglomeration::calculateRegionMaster(), GAMGInterface::combine(), GAMGAgglomeration::faceFlipMap_, GAMGAgglomeration::faceRestrictAddressing_, forAll, GAMGAgglomeration::meshLevels_, GAMGAgglomeration::nCells_, GAMGAgglomeration::nFaces_, GAMGAgglomeration::nPatchFaces_, GAMGAgglomeration::patchFaceRestrictAddressing_, GAMGAgglomeration::restrictAddressing_, and UPtrList< T >::set().
compactLevels()
void compactLevels (const label nCreatedLevels) protected
Shrink the number of levels to that specified.
Definition at line 48 of file GAMGAgglomeration.C.
References lduAddressing::band(), GAMGAgglomeration::continueAgglomerating(), Foam::endl(), forAll, Foam::Info, lduMesh::interfaces(), lduMesh::lduAddr(), lduAddressing::lowerAddr(), Foam::nl, Foam::returnReduce(), Foam::setw(), lduAddressing::size(), UList< T >::size(), and Foam::type().
continueAgglomerating()
bool continueAgglomerating (const label nCells, const label nCoarseCells) const protected
Check the need for further agglomeration.
Definition at line 208 of file GAMGAgglomeration.C.
References UPstream::nProcs(), and Foam::returnReduce().
Referenced by GAMGAgglomeration::compactLevels().
gatherList()
void gatherList (const label comm, const labelList & procIDs, const Type & myVal, List< Type > & allVals, const int tag = Pstream::msgType()) static protected
Gather value from all procIDs onto procIDs[0].
Definition at line 34 of file GAMGAgglomerationTemplates.C.
References GAMGAgglomeration::restrictField(), List< T >::setSize(), and List< T >::size().
clearLevel()
void clearLevel (const label leveli) protected
Definition at line 487 of file GAMGAgglomeration.C.
References GAMGAgglomeration::procAgglomMap().
procAgglomerateLduAddressing()
void procAgglomerateLduAddressing (const label comm, const labelList & procAgglomMap, const labelList & procIDs, const label allMeshComm, const label levelIndex) protected
Collect and combine processor meshes into allMesh:
allMeshComm : communicator for combined mesh.
procAgglomMap : per processor the new agglomerated processor (rank in allMeshComm!). Global information.
procIDs : local information: same for all in agglomerated processor.
Definition at line 365 of file GAMGAgglomerateLduAddressing.C.
References GAMGAgglomeration::procAgglomerateRestrictAddressing().
Referenced by GAMGAgglomeration::agglomerateLduAddressing().
procAgglomerateRestrictAddressing()
void procAgglomerateRestrictAddressing (const label comm, const labelList & procIDs, const label levelIndex) protected
Collect and combine basic restriction addressing:
nCells_
restrictAddressing_
Definition at line 444 of file GAMGAgglomerateLduAddressing.C.
References forAll, globalIndex::gather(), UList< T >::last(), and List< T >::size().
Referenced by GAMGAgglomeration::procAgglomerateLduAddressing().
TypeName()
TypeName ("GAMGAgglomeration")
Runtime type information.
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (autoPtr , GAMGAgglomeration , lduMesh , (const lduMesh &mesh, const dictionary &controlDict) , (mesh, controlDict))
Runtime selection table for pure geometric agglomerators.
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (autoPtr , GAMGAgglomeration , lduMatrix , (const lduMatrix &matrix, const dictionary &controlDict) , (matrix, controlDict))
Runtime selection table for matrix or mixed geometric/matrix.
agglomerators
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (autoPtr , GAMGAgglomeration , geometry , (const lduMesh &mesh, const scalarField &cellVolumes, const vectorField &faceAreas, const dictionary &controlDict) , (mesh, cellVolumes, faceAreas, controlDict))
Runtime selection table for matrix or mixed geometric/matrix.
agglomerators
New() [1/3]
const Foam::GAMGAgglomeration & New (const lduMesh & mesh, const dictionary & controlDict) static
Return the selected geometric agglomerator.
Definition at line 282 of file GAMGAgglomeration.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), objectRegistry::foundObject(), objectRegistry::lookupObject(), dictionary::lookupOrDefault(), lduMesh::thisDb(), and objectRegistry::time().
Referenced by GAMGAgglomeration::GAMGAgglomeration(), and GAMGAgglomeration::New().
New() [2/3]
const Foam::GAMGAgglomeration & New (const lduMatrix & matrix, const dictionary & controlDict) static
Return the selected matrix agglomerator.
Definition at line 335 of file GAMGAgglomeration.C.
References objectRegistry::foundObject(), objectRegistry::lookupObject(), dictionary::lookupOrDefault(), lduMatrix::mesh(), Foam::New(), GAMGAgglomeration::New(), lduMesh::thisDb(), and objectRegistry::time().
New() [3/3]
Foam::autoPtr< Foam::GAMGAgglomeration > New (const lduMesh & mesh, const scalarField & cellVolumes, const vectorField & faceAreas, const dictionary & controlDict) static
Return the selected geometric agglomerator.
Definition at line 389 of file GAMGAgglomeration.C.
References controlDict(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), dictionary::lookupOrDefault(), mesh, lduMesh::thisDb(), and objectRegistry::time().
size()
label size () const inline
Definition at line 326 of file GAMGAgglomeration.H.
References GAMGAgglomeration::hasMeshLevel(), GAMGAgglomeration::interfaceLevel(), GAMGAgglomeration::meshLevel(), and UPtrList< T >::size().
Referenced by GAMGProcAgglomeration::printStats().
meshLevel()
const Foam::lduMesh & meshLevel (const label leveli) const
Return LDU mesh of given level.
Definition at line 443 of file GAMGAgglomeration.C.
Referenced by regionCoupledBaseGAMGInterface::nbrLduInterface(), GAMGProcAgglomeration::printStats(), GAMGAgglomeration::size(), and GAMGAgglomeration::~GAMGAgglomeration().
hasMeshLevel()
bool hasMeshLevel (const label leveli) const
Do we have mesh for given level?
Definition at line 458 of file GAMGAgglomeration.C.
References GAMGAgglomeration::interfaceLevel().
Referenced by GAMGProcAgglomeration::printStats(), and GAMGAgglomeration::size().
interfaceLevel()
const Foam::lduInterfacePtrsList & interfaceLevel (const label leveli) const
Return LDU interface addressing of given level.
Definition at line 472 of file GAMGAgglomeration.C.
Referenced by GAMGAgglomeration::hasMeshLevel(), and GAMGAgglomeration::size().
restrictAddressing()
const labelField& restrictAddressing (const label leveli) const inline
Return cell restrict addressing of given level.
Definition at line 344 of file GAMGAgglomeration.H.
Referenced by GAMGProcAgglomeration::printStats(), and GAMGSolver::solve().
faceRestrictAddressing()
const labelList& faceRestrictAddressing (const label leveli) const inline
Return face restrict addressing of given level.
Definition at line 350 of file GAMGAgglomeration.H.
Referenced by GAMGProcAgglomeration::printStats().
patchFaceRestrictAddressing()
const labelListList& patchFaceRestrictAddressing (const label leveli) const inline
Definition at line 355 of file GAMGAgglomeration.H.
Referenced by GAMGProcAgglomeration::printStats().
faceFlipMap()
const boolList& faceFlipMap (const label leveli) const inline
Return face flip map of given level.
Definition at line 362 of file GAMGAgglomeration.H.
nCells()
label nCells (const label leveli) const inline
Return number of coarse cells (before processor agglomeration)
Definition at line 368 of file GAMGAgglomeration.H.
Referenced by GAMGProcAgglomeration::printStats(), and GAMGSolver::solve().
nFaces()
label nFaces (const label leveli) const inline
Return number of coarse faces (before processor agglomeration)
Definition at line 374 of file GAMGAgglomeration.H.
References GAMGAgglomeration::agglomProcIDs(), GAMGAgglomeration::calculateRegionMaster(), Foam::fv::ff(), GAMGAgglomeration::nPatchFaces(), GAMGAgglomeration::procAgglomMap(), GAMGAgglomeration::prolongField(), GAMGAgglomeration::restrictFaceField(), and GAMGAgglomeration::restrictField().
Referenced by GAMGProcAgglomeration::printStats().
nPatchFaces()
const labelList& nPatchFaces (const label leveli) const inline
Return number of coarse patch faces (before processor.
agglomeration)
Definition at line 381 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::nFaces().
restrictField() [1/2]
void restrictField (Field< Type > & cf, const Field< Type > & ff, const label fineLevelIndex, const bool procAgglom) const
Restrict (integrate by summation) cell field.
Definition at line 95 of file GAMGAgglomerationTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, GAMGAgglomeration::restrictFaceField(), List< T >::size(), and List< Type >::size().
Referenced by GAMGAgglomeration::gatherList(), GAMGAgglomeration::nFaces(), GAMGAgglomeration::restrictField(), and GAMGSolver::solve().
restrictFaceField()
void restrictFaceField (Field< Type > & cf, const Field< Type > & ff, const label fineLevelIndex) const
Restrict (integrate by summation) face field.
Definition at line 139 of file GAMGAgglomerationTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, GAMGAgglomeration::prolongField(), List< Type >::size(), List< T >::size(), and Foam::Zero.
Referenced by GAMGAgglomeration::nFaces(), and GAMGAgglomeration::restrictField().
restrictField() [2/2]
void restrictField (Field< Type > & cf, const Field< Type > & ff, const labelList & fineToCoarse) const
Restrict (integrate by summation) cell field.
Definition at line 78 of file GAMGAgglomerationTemplates.C.
References forAll, GAMGAgglomeration::restrictField(), and Foam::Zero.
prolongField()
void prolongField (Field< Type > & ff, const Field< Type > & cf, const label coarseLevelIndex, const bool procAgglom) const
Prolong (interpolate by injection) cell field.
Definition at line 172 of file GAMGAgglomerationTemplates.C.
References forAll.
Referenced by GAMGAgglomeration::nFaces(), GAMGAgglomeration::restrictFaceField(), and GAMGSolver::solve().
calculateRegionMaster()
void calculateRegionMaster (const label comm, const labelList & procAgglomMap, labelList & masterProcs, List< label > & agglomProcIDs) static
Given fine to coarse processor map determine:
for each coarse processor a master (minimum of the fine processors)
for each coarse processor the set of fine processors (element 0 is the master processor)
Definition at line 673 of file GAMGAgglomerateLduAddressing.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::find(), Foam::findIndex(), Foam::findIndices(), forAll, forAllConstIter(), Foam::min(), UPstream::myProcNo(), List< T >::setSize(), List< T >::size(), and Foam::Swap().
Referenced by masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), GAMGAgglomeration::combineLevels(), and GAMGAgglomeration::nFaces().
processorAgglomerate()
bool processorAgglomerate () const inline
Whether to agglomerate across processors.
Definition at line 448 of file GAMGAgglomeration.H.
References GAMGAgglomeration::agglomProcIDs(), GAMGAgglomeration::boundaryFaceMap(), GAMGAgglomeration::boundaryMap(), GAMGAgglomeration::cellOffsets(), GAMGAgglomeration::checkRestriction(), GAMGAgglomeration::faceMap(), GAMGAgglomeration::hasProcMesh(), GAMGAgglomeration::procAgglomMap(), GAMGAgglomeration::procCommunicator(), and autoPtr< T >::valid().
procAgglomMap()
const Foam::labelList & procAgglomMap (const label fineLeveli) const
Mapping from processor to agglomerated processor (global, all.
processors have the same information). Note that level is the fine, not the coarse, level index. This is to be consistent with the way the restriction is stored
Definition at line 508 of file GAMGAgglomeration.C.
References GAMGAgglomeration::agglomProcIDs().
Referenced by GAMGAgglomeration::clearLevel(), GAMGAgglomeration::nFaces(), and GAMGAgglomeration::processorAgglomerate().
agglomProcIDs()
const Foam::labelList & agglomProcIDs (const label fineLeveli) const
Set of processors to agglomerate. Element 0 is the.
master processor. (local, same only on those processors that agglomerate)
Definition at line 517 of file GAMGAgglomeration.C.
Referenced by GAMGAgglomeration::nFaces(), GAMGAgglomeration::procAgglomMap(), and GAMGAgglomeration::processorAgglomerate().
hasProcMesh()
bool hasProcMesh (const label fineLeveli) const
Check that level has combined mesh.
Definition at line 525 of file GAMGAgglomeration.C.
Referenced by GAMGAgglomeration::processorAgglomerate().
procCommunicator()
Foam::label procCommunicator (const label fineLeveli) const
Communicator for current level or -1.
Definition at line 531 of file GAMGAgglomeration.C.
References GAMGAgglomeration::cellOffsets().
Referenced by GAMGAgglomeration::processorAgglomerate().
cellOffsets()
const Foam::labelList & cellOffsets (const label fineLeveli) const
Mapping from processor to procMesh cells.
Definition at line 538 of file GAMGAgglomeration.C.
References GAMGAgglomeration::faceMap().
Referenced by GAMGAgglomeration::procCommunicator(), and GAMGAgglomeration::processorAgglomerate().
faceMap()
const Foam::labelListList & faceMap (const label fineLeveli) const
Mapping from processor to procMesh face.
Definition at line 547 of file GAMGAgglomeration.C.
References GAMGAgglomeration::boundaryMap().
Referenced by GAMGAgglomeration::cellOffsets(), and GAMGAgglomeration::processorAgglomerate().
boundaryMap()
const Foam::labelListList & boundaryMap (const label fineLeveli) const
Mapping from processor to procMesh boundary.
Definition at line 556 of file GAMGAgglomeration.C.
References GAMGAgglomeration::boundaryFaceMap().
Referenced by GAMGAgglomeration::faceMap(), and GAMGAgglomeration::processorAgglomerate().
boundaryFaceMap()
const Foam::labelListListList & boundaryFaceMap (const label fineLeveli) const
Mapping from processor to procMesh boundary face.
Definition at line 565 of file GAMGAgglomeration.C.
References GAMGAgglomeration::checkRestriction().
Referenced by GAMGAgglomeration::boundaryMap(), and GAMGAgglomeration::processorAgglomerate().
checkRestriction()
bool checkRestriction (labelList & newRestrict, label & nNewCoarse, const lduAddressing & fineAddressing, const labelUList & restrict, const label nCoarse) static
Given restriction determines if coarse cells are connected.
Return ok is so, otherwise creates new restriction that is
Definition at line 574 of file GAMGAgglomeration.C.
References Foam::abort(), List< T >::append(), Foam::FatalError, FatalErrorInFunction, Foam::findIndex(), forAll, Foam::identity(), lduAddressing::lowerAddr(), Foam::reduce(), List< T >::setSize(), List< T >::size(), lduAddressing::size(), UList< T >::size(), and lduAddressing::upperAddr().
Referenced by GAMGAgglomeration::boundaryFaceMap(), and GAMGAgglomeration::processorAgglomerate().
Friends And Related Function Documentation
GAMGProcAgglomeration
friend class GAMGProcAgglomeration friend
Declare friendship with GAMGProcAgglomeration.
Definition at line 219 of file GAMGAgglomeration.H.
Member Data Documentation
maxLevels_
const label maxLevels_ protected
Max number of levels.
Definition at line 70 of file GAMGAgglomeration.H.
nCellsInCoarsestLevel_
const label nCellsInCoarsestLevel_ protected
Number of cells in coarsest level.
Definition at line 73 of file GAMGAgglomeration.H.
meshInterfaces_
const lduInterfacePtrsList meshInterfaces_ protected
Cached mesh interfaces.
Definition at line 76 of file GAMGAgglomeration.H.
procAgglomeratorPtr_
autoPtr<GAMGProcAgglomeration> procAgglomeratorPtr_ protected
Definition at line 78 of file GAMGAgglomeration.H.
nCells_
labelList nCells_ protected
The number of cells in each level.
Definition at line 81 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::combineLevels().
restrictAddressing_
PtrList<labelField> restrictAddressing_ protected
Cell restriction addressing array.
Maps from the finer to the coarser level.
Definition at line 85 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::combineLevels(), and GAMGProcAgglomeration::printStats().
nFaces_
labelList nFaces_ protected
The number of (coarse) faces in each level.
max(faceRestrictAddressing)+1.
Definition at line 89 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::combineLevels().
faceRestrictAddressing_
PtrList<labelList> faceRestrictAddressing_ protected
Face restriction addressing array.
Maps from the finer to the coarser level. Positive indices map the finer faces which form part of the boundary of the coarser cells to the corresponding coarser cell face. Negative indices map the finer faces which are internal to the coarser cells to minus the corresponding coarser cell index minus 1.
Definition at line 97 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::combineLevels().
faceFlipMap_
PtrList<boolList> faceFlipMap_ protected
Face flip: for faces mapped to internal faces stores whether.
the face is reversed or not. This is used to avoid having to access the coarse mesh at all when mapping
Definition at line 102 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::combineLevels().
nPatchFaces_
PtrList<labelList> nPatchFaces_ protected
The number of (coarse) patch faces in each level.
max(patchFaceRestrictAddressing_)+1.
Definition at line 106 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::combineLevels().
patchFaceRestrictAddressing_
PtrList<labelListList> patchFaceRestrictAddressing_ protected
Patch-local face restriction addressing array.
Maps from the finer to the coarser level. Always positive. Extracted from GAMGInterfaces after agglomeration.
Definition at line 111 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::combineLevels().
meshLevels_
PtrList<lduPrimitiveMesh> meshLevels_ protected
Hierarchy of mesh addressing.
Definition at line 114 of file GAMGAgglomeration.H.
Referenced by GAMGAgglomeration::combineLevels().
procAgglomMap_
PtrList<labelList> procAgglomMap_ mutable protected
Per level, per processor the processor it agglomerates into.
Definition at line 120 of file GAMGAgglomeration.H.
Referenced by GAMGProcAgglomeration::printStats().
agglomProcIDs_
PtrList<labelList> agglomProcIDs_ mutable protected
Per level the set of processors to agglomerate. Element 0 is.
the 'master' of the cluster.
Definition at line 124 of file GAMGAgglomeration.H.
Referenced by GAMGProcAgglomeration::printStats().
procCommunicator_
labelList procCommunicator_ mutable protected
Communicator for given level.
Definition at line 127 of file GAMGAgglomeration.H.
Referenced by GAMGProcAgglomeration::printStats().
procCellOffsets_
PtrList<labelList> procCellOffsets_ mutable protected
Mapping from processor to procMeshLevel cells.
Definition at line 130 of file GAMGAgglomeration.H.
Referenced by GAMGProcAgglomeration::printStats().
procFaceMap_
PtrList<labelListList> procFaceMap_ mutable protected
Mapping from processor to procMeshLevel face.
Definition at line 133 of file GAMGAgglomeration.H.
procBoundaryMap_
PtrList<labelListList> procBoundaryMap_ mutable protected
Mapping from processor to procMeshLevel boundary.
Definition at line 136 of file GAMGAgglomeration.H.
procBoundaryFaceMap_
PtrList<labelListListList> procBoundaryFaceMap_ mutable protected
Mapping from processor to procMeshLevel boundary face.
Definition at line 139 of file GAMGAgglomeration.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/GAMGAgglomeration/GAMGAgglomeration.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/GAMGAgglomeration/GAMGAgglomerateLduAddressing.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/GAMGAgglomeration/GAMGAgglomeration.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/GAMGAgglomerations/GAMGAgglomeration/GAMGAgglomerationTemplates.C