OpenFOAM: cyclicGAMGInterface Class Reference
cyclicGAMGInterface Class Reference
GAMG agglomerated cyclic interface.
Public Member Functions
TypeName ("cyclic")
Runtime type information.
cyclicGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &restrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Construct from fine level interface,.
cyclicGAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Construct from Istream.
virtual ~cyclicGAMGInterface ()
Destructor.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Transfer and return internal field adjacent to the interface.
virtual label neighbPatchID () const
Cyclic interface functions.
virtual bool owner () const
virtual const cyclicGAMGInterface & neighbPatch () const
Return processor number.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual void write (Ostream &) const
Write to stream.
Public Member Functions inherited from GAMGInterface
TypeName ("GAMGInterface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterface, lduInterface,(const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm),(index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr, GAMGInterface, Istream,(const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is),(index, coarseInterfaces, is))
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces)
Construct from interfaces, restrict addressing set later on.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddressing)
Construct from interfaces and restrict addressing.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Construct from Istream.
virtual label size () const
Return size.
virtual label index () const
virtual const lduInterfacePtrsList & coarseInterfaces () const
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual const labelList & faceRestrictAddressing () const
Return (local)face restrict addressing.
virtual labelList & faceRestrictAddressing ()
Return non-const access to face restrict addressing.
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData) const
Return the interface internal field of the given field.
template<class Type >
void interfaceInternalField (const UList< Type > &internalData, List< Type > &) const
Get the interface internal field of the given field.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
void combine (const GAMGInterface &)
Merge the next level with this level.
virtual tmp< scalarField > agglomerateCoeffs (const scalarField &fineCoeffs) const
Agglomerating the given fine-level coefficients and return.
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF) const
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()
Construct null.
virtual ~lduInterface ()
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
Public Member Functions inherited from cyclicLduInterface
TypeName ("cyclicLduInterface")
Runtime type information.
virtual ~cyclicLduInterface ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from GAMGInterface
static autoPtr< GAMGInterface > New (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterface > New (const word &coupleType, const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Return a pointer to a new interface created on freestore given.
Protected Attributes inherited from GAMGInterface
const label index_
My index in coarseInterfaces.
const lduInterfacePtrsList & coarseInterfaces_
All interfaces.
labelList faceCells_
Face-cell addressing.
labelList faceRestrictAddressing_
Face restrict addressing.
Detailed Description
GAMG agglomerated cyclic interface.
Source files
cyclicGAMGInterface.H
cyclicGAMGInterface.C
Definition at line 49 of file cyclicGAMGInterface.H.
Constructor & Destructor Documentation
cyclicGAMGInterface() [1/2]
cyclicGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const lduInterface & fineInterface, const labelField & restrictAddressing, const labelField & neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Construct from fine level interface,.
local and neighbour restrict addressing
Definition at line 71 of file cyclicGAMGInterface.C.
References HashTableCore::end(), HashTable< T, Key, Hash >::find(), forAll, and List< T >::size().
cyclicGAMGInterface() [2/2]
cyclicGAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, Istream & is)
Construct from Istream.
Definition at line 153 of file cyclicGAMGInterface.C.
~cyclicGAMGInterface()
~cyclicGAMGInterface () virtual
Destructor.
Definition at line 169 of file cyclicGAMGInterface.C.
References cyclicGAMGInterface::internalFieldTransfer().
Member Function Documentation
TypeName()
TypeName ("cyclic")
Runtime type information.
internalFieldTransfer()
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Transfer and return internal field adjacent to the interface.
Implements lduInterface.
Definition at line 176 of file cyclicGAMGInterface.C.
References GAMGInterface::faceCells(), forAll, and tmp< T >::ref().
Referenced by cyclicGAMGInterface::~cyclicGAMGInterface().
neighbPatchID()
virtual label neighbPatchID () const inline virtual
Cyclic interface functions.
Return neigbour processor number
Implements cyclicLduInterface.
Definition at line 127 of file cyclicGAMGInterface.H.
Referenced by cyclicGAMGInterface::neighbPatch().
owner()
virtual bool owner () const inline virtual
Implements cyclicLduInterface.
Definition at line 132 of file cyclicGAMGInterface.H.
neighbPatch()
virtual const cyclicGAMGInterface& neighbPatch () const inline virtual
Return processor number.
Implements cyclicLduInterface.
Definition at line 137 of file cyclicGAMGInterface.H.
References GAMGInterface::coarseInterfaces_, and cyclicGAMGInterface::neighbPatchID().
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements cyclicLduInterface.
Definition at line 146 of file cyclicGAMGInterface.H.
Referenced by cyclicGAMGInterfaceField::forwardT().
reverseT()
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Implements cyclicLduInterface.
Definition at line 152 of file cyclicGAMGInterface.H.
References cyclicGAMGInterface::write().
Referenced by cyclicGAMGInterfaceField::reverseT().
write()
void write (Ostream & os) const virtual
Write to stream.
Implements GAMGInterface.
Definition at line 196 of file cyclicGAMGInterface.C.
References token::SPACE, and GAMGInterface::write().
Referenced by cyclicGAMGInterface::reverseT().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/cyclicGAMGInterface/cyclicGAMGInterface.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/cyclicGAMGInterface/cyclicGAMGInterface.C