OpenFOAM: LLTMatrix< Type > Class Template Reference
LLTMatrix< Type > Class Template Reference
Templated class to perform the Cholesky decomposition on a symmetric positive-definite matrix.
Public Member Functions
LLTMatrix ()
Construct null.
LLTMatrix (const SquareMatrix< Type > &M)
Construct from a square matrix and perform the decomposition.
void decompose (const SquareMatrix< Type > &M)
Perform the Cholesky decomposition of the matrix.
void solve (Field< Type > &x, const Field< Type > &source) const
Solve the linear system with the given source.
tmp< Field< Type > > solve (const Field< Type > &source) const
Solve the linear system with the given source.
Public Member Functions inherited from SquareMatrix< Type >
SquareMatrix ()
Null constructor.
SquareMatrix (const label n)
Construct given number of rows/columns.
template<class MatrixType >
SquareMatrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
template<class MatrixType >
SquareMatrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
SquareMatrix (const label n, const zero)
Construct given number of rows/columns.
SquareMatrix (const label m, const label n, const zero)
Construct given number of rows and columns (checked to be equal)
SquareMatrix (const label n, const Identity< Type >)
Construct given number of rows/columns.
SquareMatrix (const label n, const Type &)
Construct with given number of rows and rows.
SquareMatrix (const RectangularMatrix< Type > &)
Construct as copy of a RectangularMatrix.
SquareMatrix (Istream &)
Construct from Istream.
autoPtr< SquareMatrix< Type > > clone () const
Clone.
void setSize (const label m)
Resize the matrix preserving the elements.
void shallowResize (const label m)
Resize the matrix without reallocating storage (unsafe)
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Identity< Type >)
Assignment elements to the.
Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label m, const label n)
Construct given number of rows and columns.
Matrix (const label m, const label n, const zero)
Construct with given number of rows and columns.
Matrix (const label m, const label n, const Type &)
Construct with given number of rows and columns.
Matrix (const mType &)
Copy constructor.
Matrix (const Matrix< Form2, Type > &)
Copy constructor from matrix of a different form.
Matrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (Istream &)
Construct from Istream.
autoPtr< mType > clone () const
Clone.
~Matrix ()
Destructor.
label m () const
Return the number of rows.
label n () const
Return the number of columns.
label size () const
Return the number of elements in matrix (m*n)
const Type * v () const
Return element vector of the constant Matrix.
Type * v ()
Return element vector of the Matrix.
ConstMatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart) const
ConstMatrixBlock< mType > block (const label mStart, const label nStart) const
MatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart)
MatrixBlock< mType > block (const label mStart, const label nStart)
Foam::ConstMatrixBlock< Foam::Matrix< SquareMatrix< Type >, Type > > block (const label mStart, const label nStart) const
Foam::MatrixBlock< Foam::Matrix< SquareMatrix< Type >, Type > > block (const label mStart, const label nStart)
ConstMatrixBlock< mType > col (const label m, const label rowStart) const
ConstMatrixBlock< mType > col (const label m, const label mStart, const label nStart) const
MatrixBlock< mType > col (const label m, const label rowStart)
MatrixBlock< mType > col (const label m, const label mStart, const label nStart)
void checki (const label i) const
Check index i is within valid range (0 ... m-1).
void checkj (const label j) const
Check index j is within valid range (0 ... n-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (mType &)
Transfer the contents of the argument Matrix into this Matrix.
void setSize (const label m, const label n)
Resize the matrix preserving the elements.
void shallowResize (const label m, const label n)
Resize the matrix without reallocating storage (unsafe)
SquareMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
const Type & operator() (const label i, const label j) const
(i, j) const element access operator
Type & operator() (const label i, const label j)
(i, j) element access operator
void operator= (const mType &)
Assignment operator. Takes linear time.
void operator= (const ConstMatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const MatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Type &)
Assignment of all elements to the given value.
Additional Inherited Members
Public Types inherited from Matrix< SquareMatrix< Type >, Type >
typedef Matrix< SquareMatrix< Type >, Type > mType
Matrix type.
typedef Type cmptType
Component type.
Static Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
static const mType & null ()
Return a null Matrix.
Detailed Description
template<class Type>
class Foam::LLTMatrix< Type >
Templated class to perform the Cholesky decomposition on a symmetric positive-definite matrix.
Member functions are provided to solve linear systems using the LLT decomposition.
Source files
LLTMatrix.H
LLTMatrix.C
Definition at line 54 of file LLTMatrix.H.
Constructor & Destructor Documentation
LLTMatrix() [1/2]
LLTMatrix ()
Construct null.
Definition at line 31 of file LLTMatrix.C.
LLTMatrix() [2/2]
LLTMatrix (const SquareMatrix< Type > & M)
Construct from a square matrix and perform the decomposition.
Definition at line 36 of file LLTMatrix.C.
Member Function Documentation
decompose()
void decompose (const SquareMatrix< Type > & M)
Perform the Cholesky decomposition of the matrix.
Definition at line 45 of file LLTMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, k, Matrix< SquareMatrix< Type >, Type >::m(), M, LLTMatrix< Type >::solve(), Foam::sqrt(), Foam::sum(), and Foam::Zero.
solve() [1/2]
void solve (Field< Type > & x, const Field< Type > & source) const
Solve the linear system with the given source.
and returning the solution in the Field argument x. This function may be called with the same field for x and source.
Definition at line 93 of file LLTMatrix.C.
References Matrix< SquareMatrix< Type >, Type >::m(), and Foam::sum().
Referenced by LLTMatrix< Type >::decompose().
solve() [2/2]
Foam::tmp< Foam::Field< Type > > solve (const Field< Type > & source) const
Solve the linear system with the given source.
returning the solution
Definition at line 136 of file LLTMatrix.C.
References tmp< T >::ref(), and solve().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LLTMatrix/LLTMatrix.H
src/OpenFOAM/matrices/LLTMatrix/LLTMatrix.C