OpenFOAM: procLduInterface Class Reference
procLduInterface Class Reference
IO interface for processorLduInterface.
Public Member Functions
procLduInterface (const lduInterfaceField &interface, const scalarField &coeffs)
procLduInterface (Istream &is)
autoPtr< procLduInterface > clone ()
Static Public Member Functions
static autoPtr< procLduInterface > New (Istream &is)
Friends
class LUscalarMatrix
Ostream & operator<< (Ostream &, const procLduInterface &)
Detailed Description
IO interface for processorLduInterface.
Source files
procLduInterface.H
procLduInterface.C
Definition at line 59 of file procLduInterface.H.
Constructor & Destructor Documentation
procLduInterface() [1/2]
procLduInterface (const lduInterfaceField & interface, const scalarField & coeffs)
Definition at line 34 of file procLduInterface.C.
References processorLduInterface::comm(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, lduInterfaceField::interface(), processorLduInterface::myProcNo(), processorLduInterface::neighbProcNo(), and processorLduInterface::tag().
procLduInterface() [2/2]
procLduInterface (Istream & is)
Definition at line 69 of file procLduInterface.C.
Member Function Documentation
clone()
autoPtr<procLduInterface> clone () inline
Definition at line 92 of file procLduInterface.H.
References NotImplemented.
New()
static autoPtr<procLduInterface> New (Istream & is) inline static
Definition at line 98 of file procLduInterface.H.
References procLduInterface::operator<<.
Friends And Related Function Documentation
LUscalarMatrix
friend class LUscalarMatrix friend
Definition at line 79 of file procLduInterface.H.
operator<<
Ostream& operator<< (Ostream & , const procLduInterface &) friend
Referenced by procLduInterface::New().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LUscalarMatrix/procLduInterface.H
src/OpenFOAM/matrices/LUscalarMatrix/procLduInterface.C