OpenFOAM: NoPreconditioner< Type, DType, LUType > Class Template Reference
NoPreconditioner< Type, DType, LUType > Class Template Reference
Null preconditioner for both symmetric and asymmetric matrices.
Public Member Functions
TypeName ("none")
Runtime type information.
NoPreconditioner (const typename LduMatrix< Type, DType, LUType >::solver &sol, const dictionary &preconditionerDict)
Construct from matrix components and preconditioner data dictionary.
virtual ~NoPreconditioner ()
virtual void read (const dictionary &preconditionerDict)
Read and reset the preconditioner parameters from the given.
virtual void precondition (Field< Type > &wA, const Field< Type > &rA) const
Return wA the preconditioned form of residual rA.
virtual void preconditionT (Field< Type > &wT, const Field< Type > &rT) const
Return wT the transpose-matrix preconditioned form of.
Public Member Functions inherited from LduMatrix< Type, DType, LUType >::preconditioner
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, preconditioner, symMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
declareRunTimeSelectionTable (autoPtr, preconditioner, asymMatrix,(const solver &sol, const dictionary &preconditionerDict),(sol, preconditionerDict))
preconditioner (const solver &sol)
virtual ~preconditioner ()
Additional Inherited Members
Static Public Member Functions inherited from LduMatrix< Type, DType, LUType >::preconditioner
static autoPtr< preconditioner > New (const solver &sol, const dictionary &preconditionerDict)
Return a new preconditioner.
Protected Attributes inherited from LduMatrix< Type, DType, LUType >::preconditioner
const solver & solver_
Reference to the base-solver this preconditioner is used with.
Detailed Description
template<class Type, class DType, class LUType>
class Foam::NoPreconditioner< Type, DType, LUType >
Null preconditioner for both symmetric and asymmetric matrices.
Source files
NoPreconditioner.H
NoPreconditioner.C
Definition at line 49 of file NoPreconditioner.H.
Constructor & Destructor Documentation
NoPreconditioner()
NoPreconditioner (const typename LduMatrix< Type, DType, LUType >::solver & sol, const dictionary & preconditionerDict)
Construct from matrix components and preconditioner data dictionary.
Definition at line 32 of file NoPreconditioner.C.
~NoPreconditioner()
virtual ~NoPreconditioner () inline virtual
Definition at line 80 of file NoPreconditioner.H.
References NoPreconditioner< Type, DType, LUType >::precondition(), NoPreconditioner< Type, DType, LUType >::preconditionT(), and NoPreconditioner< Type, DType, LUType >::read().
Member Function Documentation
TypeName()
TypeName ("none")
Runtime type information.
read()
void read (const dictionary & preconditionerDict) virtual
Read and reset the preconditioner parameters from the given.
dictionary
Reimplemented from LduMatrix< Type, DType, LUType >::preconditioner.
Definition at line 44 of file NoPreconditioner.C.
References NoPreconditioner< Type, DType, LUType >::precondition().
Referenced by NoPreconditioner< Type, DType, LUType >::~NoPreconditioner().
precondition()
void precondition (Field< Type > & wA, const Field< Type > & rA) const virtual
Return wA the preconditioned form of residual rA.
Implements LduMatrix< Type, DType, LUType >::preconditioner.
Definition at line 50 of file NoPreconditioner.C.
Referenced by NoPreconditioner< Type, DType, LUType >::preconditionT(), NoPreconditioner< Type, DType, LUType >::read(), and NoPreconditioner< Type, DType, LUType >::~NoPreconditioner().
preconditionT()
virtual void preconditionT (Field< Type > & wT, const Field< Type > & rT) const inline virtual
Return wT the transpose-matrix preconditioned form of.
residual rT.
Reimplemented from LduMatrix< Type, DType, LUType >::preconditioner.
Definition at line 100 of file NoPreconditioner.H.
References NoPreconditioner< Type, DType, LUType >::precondition().
Referenced by NoPreconditioner< Type, DType, LUType >::~NoPreconditioner().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/Preconditioners/NoPreconditioner/NoPreconditioner.H
src/OpenFOAM/matrices/LduMatrix/Preconditioners/NoPreconditioner/NoPreconditioner.C