OpenFOAM: SmoothSolver< Type, DType, LUType > Class Template Reference
SmoothSolver< Type, DType, LUType > Class Template Reference
Iterative solver for symmetric and assymetric matrices which uses a run-time selected smoother e.g. GaussSeidel to converge the solution to the required tolerance. To improve efficiency, the residual is evaluated after every nSweeps smoothing iterations.
Public Member Functions
TypeName ("SmoothSolver")
Runtime type information.
SmoothSolver (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
Construct from matrix components and solver data dictionary.
virtual SolverPerformance< Type > solve (Field< Type > &psi) const
Solve the matrix with this solver.
Public Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
solver (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
virtual ~solver ()
const word & fieldName () const
const LduMatrix< Type, DType, LUType > & matrix () const
virtual void read (const dictionary &solverDict)
Read and reset the solver parameters from the given dictionary.
Type normFactor (const Field< Type > &psi, const Field< Type > &Apsi, Field< Type > &tmpField) const
Return the matrix norm used to normalise the residual for the.
Protected Member Functions
virtual void readControls ()
Read the control parameters from the controlDict_.
Protected Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
template<class T >
void readControl (const dictionary &controlDict, T &control, const word &controlName)
Read a control parameter from controlDict.
Protected Attributes
label nSweeps_
Number of sweeps before the evaluation of residual.
Protected Attributes inherited from LduMatrix< Type, DType, LUType >::solver
word fieldName_
const LduMatrix< Type, DType, LUType > & matrix_
dictionary controlDict_
Dictionary of controls.
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
Type tolerance_
Final convergence tolerance.
Type relTol_
Convergence tolerance relative to the initial.
Additional Inherited Members
Static Public Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
static autoPtr< solver > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
Return a new solver.
Detailed Description
template<class Type, class DType, class LUType>
class Foam::SmoothSolver< Type, DType, LUType >
Iterative solver for symmetric and assymetric matrices which uses a run-time selected smoother e.g. GaussSeidel to converge the solution to the required tolerance. To improve efficiency, the residual is evaluated after every nSweeps smoothing iterations.
Source files
SmoothSolver.H
SmoothSolver.C
Definition at line 52 of file SmoothSolver.H.
Constructor & Destructor Documentation
SmoothSolver()
SmoothSolver (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & solverDict)
Construct from matrix components and solver data dictionary.
Definition at line 32 of file SmoothSolver.C.
Member Function Documentation
readControls()
void readControls () protected virtual
Read the control parameters from the controlDict_.
Reimplemented from LduMatrix< Type, DType, LUType >::solver.
Definition at line 53 of file SmoothSolver.C.
TypeName()
TypeName ("SmoothSolver< Type, DType, LUType >")
Runtime type information.
solve()
Foam::SolverPerformance< Type > solve (Field< Type > & psi) const virtual
Solve the matrix with this solver.
Implements LduMatrix< Type, DType, LUType >::solver.
Definition at line 62 of file SmoothSolver.C.
References SolverPerformance< Type >::checkConvergence(), Foam::cmptDivide(), Foam::endl(), SolverPerformance< Type >::finalResidual(), Foam::gSumCmptMag(), Foam::Info, SolverPerformance< Type >::initialResidual(), Foam::New(), SolverPerformance< Type >::nIterations(), List< Type >::size(), and Foam::Zero.
Member Data Documentation
nSweeps_
label nSweeps_ protected
Number of sweeps before the evaluation of residual.
Definition at line 62 of file SmoothSolver.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/Solvers/SmoothSolver/SmoothSolver.H
src/OpenFOAM/matrices/LduMatrix/Solvers/SmoothSolver/SmoothSolver.C