OpenFOAM: LUscalarMatrix Class Reference
LUscalarMatrix Class Reference
Class to perform the LU decomposition on a symmetric matrix.
Public Member Functions
ClassName ("LUscalarMatrix")
LUscalarMatrix ()
Construct null.
LUscalarMatrix (const scalarSquareMatrix &M)
Construct from and perform LU decomposition of the matrix M.
LUscalarMatrix (const lduMatrix &, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces)
Construct from lduMatrix and perform LU decomposition.
void decompose (const scalarSquareMatrix &M)
Perform the LU decomposition of the matrix M.
template<class Type >
void solve (Field< Type > &x, const Field< Type > &source) const
Solve the linear system with the given source.
template<class Type >
tmp< Field< Type > > solve (const Field< Type > &source) const
Solve the linear system with the given source.
void inv (scalarSquareMatrix &M) const
Set M to the inverse of this square matrix.
template<class Type >
Foam::tmp< Foam::Field< Type > > solve (const Field< Type > &source) const
Public Member Functions inherited from SquareMatrix< Type >
SquareMatrix ()
Null constructor.
SquareMatrix (const label n)
Construct given number of rows/columns.
template<class MatrixType >
SquareMatrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
template<class MatrixType >
SquareMatrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
SquareMatrix (const label n, const zero)
Construct given number of rows/columns.
SquareMatrix (const label m, const label n, const zero)
Construct given number of rows and columns (checked to be equal)
SquareMatrix (const label n, const Identity< Type >)
Construct given number of rows/columns.
SquareMatrix (const label n, const Type &)
Construct with given number of rows and rows.
SquareMatrix (const RectangularMatrix< Type > &)
Construct as copy of a RectangularMatrix.
SquareMatrix (Istream &)
Construct from Istream.
autoPtr< SquareMatrix< Type > > clone () const
Clone.
void setSize (const label m)
Resize the matrix preserving the elements.
void shallowResize (const label m)
Resize the matrix without reallocating storage (unsafe)
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Identity< Type >)
Assignment elements to the.
Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label m, const label n)
Construct given number of rows and columns.
Matrix (const label m, const label n, const zero)
Construct with given number of rows and columns.
Matrix (const label m, const label n, const Type &)
Construct with given number of rows and columns.
Matrix (const mType &)
Copy constructor.
Matrix (const Matrix< Form2, Type > &)
Copy constructor from matrix of a different form.
Matrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (Istream &)
Construct from Istream.
autoPtr< mType > clone () const
Clone.
~Matrix ()
Destructor.
label m () const
Return the number of rows.
label n () const
Return the number of columns.
label size () const
Return the number of elements in matrix (m*n)
const Type * v () const
Return element vector of the constant Matrix.
Type * v ()
Return element vector of the Matrix.
ConstMatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart) const
ConstMatrixBlock< mType > block (const label mStart, const label nStart) const
MatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart)
MatrixBlock< mType > block (const label mStart, const label nStart)
Foam::ConstMatrixBlock< Foam::Matrix< SquareMatrix< Type >, Type > > block (const label mStart, const label nStart) const
Foam::MatrixBlock< Foam::Matrix< SquareMatrix< Type >, Type > > block (const label mStart, const label nStart)
ConstMatrixBlock< mType > col (const label m, const label rowStart) const
ConstMatrixBlock< mType > col (const label m, const label mStart, const label nStart) const
MatrixBlock< mType > col (const label m, const label rowStart)
MatrixBlock< mType > col (const label m, const label mStart, const label nStart)
void checki (const label i) const
Check index i is within valid range (0 ... m-1).
void checkj (const label j) const
Check index j is within valid range (0 ... n-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (mType &)
Transfer the contents of the argument Matrix into this Matrix.
void setSize (const label m, const label n)
Resize the matrix preserving the elements.
void shallowResize (const label m, const label n)
Resize the matrix without reallocating storage (unsafe)
SquareMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
const Type & operator() (const label i, const label j) const
(i, j) const element access operator
Type & operator() (const label i, const label j)
(i, j) element access operator
void operator= (const mType &)
Assignment operator. Takes linear time.
void operator= (const ConstMatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const MatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Type &)
Assignment of all elements to the given value.
Additional Inherited Members
Public Types inherited from Matrix< SquareMatrix< Type >, Type >
typedef Matrix< SquareMatrix< Type >, Type > mType
Matrix type.
typedef Type cmptType
Component type.
Static Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
static const mType & null ()
Return a null Matrix.
Detailed Description
Class to perform the LU decomposition on a symmetric matrix.
Source files
LUscalarMatrix.H
LUscalarMatrix.C
Definition at line 54 of file LUscalarMatrix.H.
Constructor & Destructor Documentation
LUscalarMatrix() [1/3]
LUscalarMatrix ()
Construct null.
Definition at line 42 of file LUscalarMatrix.C.
Referenced by LUscalarMatrix::LUscalarMatrix().
LUscalarMatrix() [2/3]
LUscalarMatrix (const scalarSquareMatrix & M)
Construct from and perform LU decomposition of the matrix M.
Definition at line 48 of file LUscalarMatrix.C.
References Foam::LUDecompose(), and LUscalarMatrix::LUscalarMatrix().
LUscalarMatrix() [3/3]
LUscalarMatrix (const lduMatrix & ldum, const FieldField< Field, scalar > & interfaceCoeffs, const lduInterfaceFieldPtrsList & interfaces)
Construct from lduMatrix and perform LU decomposition.
Definition at line 59 of file LUscalarMatrix.C.
References UList< T >::begin(), UPtrList< T >::begin(), lduMatrix::diag(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPstream::firstSlave(), forAll, Foam::Info, interface(), UPstream::lastSlave(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), Foam::LUDecompose(), Matrix< SquareMatrix< Type >, Type >::m(), Foam::mag(), UPstream::master(), UPstream::masterNo(), UPstream::msgType(), Matrix< SquareMatrix< Type >, Type >::n(), cyclicLduInterface::neighbPatchID(), UPstream::nProcs(), Matrix< SquareMatrix< Type >, Type >::operator[](), UPstream::parRun(), Foam::Pout, UPstream::scheduled, PtrList< T >::set(), UPtrList< T >::set(), List< T >::setSize(), procLduMatrix::size(), List< T >::size(), UPtrList< T >::size(), lduAddressing::size(), Foam::sum(), Matrix< SquareMatrix< Type >, Type >::transfer(), lduMatrix::upper(), and lduAddressing::upperAddr().
Member Function Documentation
ClassName()
ClassName ("LUscalarMatrix")
decompose()
void decompose (const scalarSquareMatrix & M)
Perform the LU decomposition of the matrix M.
Definition at line 407 of file LUscalarMatrix.C.
References Foam::LUDecompose(), Matrix< SquareMatrix< Type >, Type >::m(), SquareMatrix< scalar >::operator=(), and List< T >::setSize().
solve() [1/3]
void solve (Field< Type > & x, const Field< Type > & source) const
Solve the linear system with the given source.
and returning the solution in the Field argument x. This function may be called with the same field for x and source.
Definition at line 33 of file LUscalarMatrixTemplates.C.
References UList< Type >::begin(), UList< Type >::byteSize(), Foam::LUBacksubstitute(), Foam::read(), List< Type >::size(), and write().
solve() [2/3]
tmp<Field<Type> > solve (const Field< Type > & source) const
Solve the linear system with the given source.
returning the solution
inv()
void inv (scalarSquareMatrix & M) const
Set M to the inverse of this square matrix.
Definition at line 415 of file LUscalarMatrix.C.
References Foam::LUBacksubstitute(), Matrix< SquareMatrix< Type >, Type >::m(), M, and Foam::Zero.
Referenced by ISAT< CompType, ThermoType >::~ISAT().
solve() [3/3]
Foam::tmp<Foam::Field<Type> > solve (const Field< Type > & source) const
Definition at line 143 of file LUscalarMatrixTemplates.C.
References tmp< T >::ref(), and solve().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LUscalarMatrix/LUscalarMatrix.H
src/OpenFOAM/matrices/LUscalarMatrix/LUscalarMatrix.C
src/OpenFOAM/matrices/LUscalarMatrix/LUscalarMatrixTemplates.C