OpenFOAM: ConstMatrixBlock< MatrixType > Class Template Reference
ConstMatrixBlock< MatrixType > Class Template Reference
Public Types
typedef MatrixType::cmptType cmptType
Public Member Functions
ConstMatrixBlock (const MatrixType &matrix, const label m, const label n, const label mStart, const label nStart)
Construct block for matrix, size and location.
label m () const
Return the number of rows in the block.
label n () const
Return the number of columns in the block.
const cmptType & operator() (const label i, const label j) const
(i, j) const element access operator
operator Field< cmptType > () const
Convert a column of a matrix to a Field.
Detailed Description
template<class MatrixType>
class Foam::ConstMatrixBlock< MatrixType >
Definition at line 68 of file Matrix.H.
Member Typedef Documentation
cmptType
typedef MatrixType::cmptType cmptType
Definition at line 75 of file MatrixBlock.H.
Constructor & Destructor Documentation
ConstMatrixBlock()
ConstMatrixBlock (const MatrixType & matrix, const label m, const label n, const label mStart, const label nStart) inline
Construct block for matrix, size and location.
Definition at line 30 of file MatrixBlockI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and MatrixBlock< MatrixType >::MatrixBlock().
Member Function Documentation
m()
Foam::label m () const inline
Return the number of rows in the block.
Definition at line 93 of file MatrixBlockI.H.
n()
Foam::label n () const inline
Return the number of columns in the block.
Definition at line 100 of file MatrixBlockI.H.
operator()()
const MatrixType::cmptType & operator() (const label i, const label j) const inline
(i, j) const element access operator
Definition at line 125 of file MatrixBlockI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
operator Field< cmptType >()
operator Field< cmptType > () const
Convert a column of a matrix to a Field.
Definition at line 31 of file MatrixBlock.C.
References Foam::abort(), f(), Foam::FatalError, FatalErrorInFunction, and forAll.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/Matrix/Matrix.H
src/OpenFOAM/matrices/MatrixBlock/MatrixBlock.H
src/OpenFOAM/matrices/MatrixBlock/MatrixBlock.C
src/OpenFOAM/matrices/MatrixBlock/MatrixBlockI.H