OpenFOAM: TGaussSeidelSmoother< Type, DType, LUType > Class Template Reference
TGaussSeidelSmoother< Type, DType, LUType > Class Template Reference
Foam::TGaussSeidelSmoother.
Public Member Functions
TypeName ("GaussSeidel")
Runtime type information.
TGaussSeidelSmoother (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix)
Construct from components.
virtual void smooth (Field< Type > &psi, const label nSweeps) const
Smooth the solution for a given number of sweeps.
Public Member Functions inherited from LduMatrix< Type, DType, LUType >::smoother
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, smoother, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
declareRunTimeSelectionTable (autoPtr, smoother, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
smoother (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix)
virtual ~smoother ()
const word & fieldName () const
const LduMatrix< Type, DType, LUType > & matrix () const
Static Public Member Functions
static void smooth (const word &fieldName, Field< Type > &psi, const LduMatrix< Type, DType, LUType > &matrix, const Field< DType > &rD, const label nSweeps)
Smooth for the given number of sweeps.
Static Public Member Functions inherited from LduMatrix< Type, DType, LUType >::smoother
static autoPtr< smoother > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &smootherDict)
Return a new smoother.
Additional Inherited Members
Protected Attributes inherited from LduMatrix< Type, DType, LUType >::smoother
word fieldName_
const LduMatrix< Type, DType, LUType > & matrix_
Detailed Description
template<class Type, class DType, class LUType>
class Foam::TGaussSeidelSmoother< Type, DType, LUType >
Foam::TGaussSeidelSmoother.
Source files
TGaussSeidelSmoother.H
TGaussSeidelSmoother.C
Definition at line 49 of file TGaussSeidelSmoother.H.
Constructor & Destructor Documentation
TGaussSeidelSmoother()
TGaussSeidelSmoother (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix)
Construct from components.
Definition at line 32 of file TGaussSeidelSmoother.C.
References UList< T >::begin(), LduMatrix< Type, DType, LUType >::diag(), Foam::inv(), List< T >::size(), and TGaussSeidelSmoother< Type, DType, LUType >::smooth().
Member Function Documentation
TypeName()
TypeName ("GaussSeidel")
Runtime type information.
smooth() [1/2]
void smooth (const word & fieldName, Field< Type > & psi, const LduMatrix< Type, DType, LUType > & matrix, const Field< DType > & rD, const label nSweeps) static
Smooth for the given number of sweeps.
Definition at line 59 of file TGaussSeidelSmoother.C.
References UList< Type >::begin(), UList< T >::begin(), Foam::dot(), forAll, LduMatrix< Type, DType, LUType >::initMatrixInterfaces(), LduMatrix< Type, DType, LUType >::interfaces(), LduMatrix< Type, DType, LUType >::interfacesUpper(), LduMatrix< Type, DType, LUType >::lduAddr(), LduMatrix< Type, DType, LUType >::lower(), patchi, List< Type >::size(), LduMatrix< Type, DType, LUType >::source(), Foam::fvc::sweep(), LduMatrix< Type, DType, LUType >::updateMatrixInterfaces(), and LduMatrix< Type, DType, LUType >::upper().
Referenced by TGaussSeidelSmoother< Type, DType, LUType >::TGaussSeidelSmoother().
smooth() [2/2]
void smooth (Field< Type > & psi, const label nSweeps) const virtual
Smooth the solution for a given number of sweeps.
Implements LduMatrix< Type, DType, LUType >::smoother.
Definition at line 158 of file TGaussSeidelSmoother.C.
References Foam::fvc::smooth().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/Smoothers/GaussSeidel/TGaussSeidelSmoother.H
src/OpenFOAM/matrices/LduMatrix/Smoothers/GaussSeidel/TGaussSeidelSmoother.C