OpenFOAM: LduMatrix< Type, DType, LUType >::smoother Class Reference
LduMatrix< Type, DType, LUType >::smoother Class Reference abstract
Abstract base-class for LduMatrix smoothers.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, smoother, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
declareRunTimeSelectionTable (autoPtr, smoother, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
smoother (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix)
virtual ~smoother ()
const word & fieldName () const
const LduMatrix< Type, DType, LUType > & matrix () const
virtual void smooth (Field< Type > &psi, const label nSweeps) const =0
Smooth the solution for a given number of sweeps.
Static Public Member Functions
static autoPtr< smoother > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &smootherDict)
Return a new smoother.
Protected Attributes
word fieldName_
const LduMatrix< Type, DType, LUType > & matrix_
Detailed Description
template<class Type, class DType, class LUType>
class Foam::LduMatrix< Type, DType, LUType >::smoother
Abstract base-class for LduMatrix smoothers.
Definition at line 258 of file LduMatrix.H.
Constructor & Destructor Documentation
smoother()
smoother (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix)
Definition at line 107 of file LduMatrixSmoother.C.
Referenced by LduMatrix< Type, DType, LUType >::smoother::New().
~smoother()
virtual ~smoother () inline virtual
Definition at line 329 of file LduMatrix.H.
Member Function Documentation
type()
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , smoother , symMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix) , (fieldName, matrix))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , smoother , asymMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix) , (fieldName, matrix))
New()
Foam::autoPtr< typename Foam::LduMatrix< Type, DType, LUType >::smoother > New (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & smootherDict) static
Return a new smoother.
Definition at line 33 of file LduMatrixSmoother.C.
References LduMatrix< Type, DType, LUType >::asymmetric(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::lookup(), LduMatrix< Type, DType, LUType >::smoother::smoother(), and LduMatrix< Type, DType, LUType >::symmetric().
fieldName()
const word& fieldName () const inline
Definition at line 337 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::solver::fieldName_.
matrix()
const LduMatrix<Type, DType, LUType>& matrix () const inline
Definition at line 342 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::solver::matrix_, psi, and Foam::fvc::smooth().
smooth()
virtual void smooth (Field< Type > & psi, const label nSweeps) const pure virtual
Smooth the solution for a given number of sweeps.
Implemented in TGaussSeidelSmoother< Type, DType, LUType >.
Member Data Documentation
fieldName_
word fieldName_ protected
Definition at line 264 of file LduMatrix.H.
matrix_
const LduMatrix<Type, DType, LUType>& matrix_ protected
Definition at line 265 of file LduMatrix.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixSmoother.C