OpenFOAM: PBiCCCG< Type, DType, LUType > Class Template Reference
PBiCCCG< Type, DType, LUType > Class Template Reference
Preconditioned bi-conjugate gradient solver for asymmetric lduMatrices using a run-time selectable preconditioner.
Public Member Functions
TypeName ("PBiCCCG")
Runtime type information.
PBiCCCG (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
Construct from matrix components and solver data dictionary.
virtual ~PBiCCCG ()
virtual SolverPerformance< Type > solve (Field< Type > &psi) const
Solve the matrix with this solver.
Public Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
solver (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
virtual ~solver ()
const word & fieldName () const
const LduMatrix< Type, DType, LUType > & matrix () const
virtual void read (const dictionary &solverDict)
Read and reset the solver parameters from the given dictionary.
Type normFactor (const Field< Type > &psi, const Field< Type > &Apsi, Field< Type > &tmpField) const
Return the matrix norm used to normalise the residual for the.
Additional Inherited Members
Static Public Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
static autoPtr< solver > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
Return a new solver.
Protected Member Functions inherited from LduMatrix< Type, DType, LUType >::solver
template<class T >
void readControl (const dictionary &controlDict, T &control, const word &controlName)
Read a control parameter from controlDict.
virtual void readControls ()
Read the control parameters from the controlDict_.
Protected Attributes inherited from LduMatrix< Type, DType, LUType >::solver
word fieldName_
const LduMatrix< Type, DType, LUType > & matrix_
dictionary controlDict_
Dictionary of controls.
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
Type tolerance_
Final convergence tolerance.
Type relTol_
Convergence tolerance relative to the initial.
Detailed Description
template<class Type, class DType, class LUType>
class Foam::PBiCCCG< Type, DType, LUType >
Preconditioned bi-conjugate gradient solver for asymmetric lduMatrices using a run-time selectable preconditioner.
Source files
PBiCCCG.H
PBiCCCG.C
Definition at line 50 of file PBiCCCG.H.
Constructor & Destructor Documentation
PBiCCCG()
PBiCCCG (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & solverDict)
Construct from matrix components and solver data dictionary.
Definition at line 32 of file PBiCCCG.C.
References PBiCCCG< Type, DType, LUType >::solve().
~PBiCCCG()
virtual ~PBiCCCG () inline virtual
Definition at line 82 of file PBiCCCG.H.
References psi, and PBiCCCG< Type, DType, LUType >::solve().
Member Function Documentation
TypeName()
TypeName ("PBiCCCG< Type, DType, LUType >")
Runtime type information.
solve()
Foam::SolverPerformance< Type > solve (Field< Type > & psi) const virtual
Solve the matrix with this solver.
Implements LduMatrix< Type, DType, LUType >::solver.
Definition at line 52 of file PBiCCCG.C.
References Foam::constant::atomic::alpha, UList< T >::begin(), UList< Type >::begin(), beta(), Foam::cmptDivide(), Foam::endl(), Foam::gSumCmptMag(), Foam::gSumProd(), Foam::Info, Foam::mag(), Foam::New(), List< Type >::size(), and Foam::Zero.
Referenced by PBiCCCG< Type, DType, LUType >::PBiCCCG(), and PBiCCCG< Type, DType, LUType >::~PBiCCCG().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/Solvers/PBiCCCG/PBiCCCG.H
src/OpenFOAM/matrices/LduMatrix/Solvers/PBiCCCG/PBiCCCG.C