OpenFOAM: LduMatrix< Type, DType, LUType > Class Template Reference
LduMatrix< Type, DType, LUType > Class Template Reference
LduMatrix is a general matrix class in which the coefficients are stored as three arrays, one for the upper triangle, one for the lower triangle and a third for the diagonal.
Classes
class preconditioner
Abstract base-class for LduMatrix preconditioners.
class smoother
Abstract base-class for LduMatrix smoothers.
class solver
Abstract base-class for LduMatrix solvers.
Public Member Functions
ClassName ("LduMatrix")
LduMatrix (const lduMesh &)
Construct given an LDU addressed mesh.
LduMatrix (const LduMatrix< Type, DType, LUType > &)
Construct as copy.
LduMatrix (LduMatrix< Type, DType, LUType > &, bool reuse)
Construct as copy or re-use as specified.
LduMatrix (const lduMesh &, Istream &)
Construct given an LDU addressed mesh and an Istream.
~LduMatrix ()
const lduMesh & mesh () const
Return the LDU mesh from which the addressing is obtained.
const lduAddressing & lduAddr () const
Return the LDU addressing.
const lduSchedule & patchSchedule () const
Return the patch evaluation schedule.
const LduInterfaceFieldPtrsList< Type > & interfaces () const
Return interfaces.
LduInterfaceFieldPtrsList< Type > & interfaces ()
Return interfaces.
Field< DType > & diag ()
Field< LUType > & upper ()
Field< LUType > & lower ()
Field< Type > & source ()
FieldField< Field, LUType > & interfacesUpper ()
FieldField< Field, LUType > & interfacesLower ()
const Field< DType > & diag () const
const Field< LUType > & upper () const
const Field< LUType > & lower () const
const Field< Type > & source () const
const FieldField< Field, LUType > & interfacesUpper () const
const FieldField< Field, LUType > & interfacesLower () const
bool hasDiag () const
bool hasUpper () const
bool hasLower () const
bool hasSource () const
bool diagonal () const
bool symmetric () const
bool asymmetric () const
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (Field< LUType > &sumOff) const
void Amul (Field< Type > &, const tmp< Field< Type >> &) const
Matrix multiplication.
void Tmul (Field< Type > &, const tmp< Field< Type >> &) const
Matrix transpose multiplication.
void sumA (Field< Type > &) const
Sum the coefficients on each row of the matrix.
void residual (Field< Type > &rA, const Field< Type > &psi) const
tmp< Field< Type > > residual (const Field< Type > &psi) const
void initMatrixInterfaces (const FieldField< Field, LUType > &interfaceCoeffs, const Field< Type > &psiif, Field< Type > &result) const
Initialise the update of interfaced interfaces.
void updateMatrixInterfaces (const FieldField< Field, LUType > &interfaceCoeffs, const Field< Type > &psiif, Field< Type > &result) const
Update interfaced interfaces for matrix operations.
tmp< Field< Type > > H (const Field< Type > &) const
tmp< Field< Type > > H (const tmp< Field< Type >> &) const
tmp< Field< Type > > faceH (const Field< Type > &) const
tmp< Field< Type > > faceH (const tmp< Field< Type >> &) const
void operator= (const LduMatrix< Type, DType, LUType > &)
void negate ()
void operator+= (const LduMatrix< Type, DType, LUType > &)
void operator-= (const LduMatrix< Type, DType, LUType > &)
void operator*= (const scalarField &)
void operator*= (scalar)
Friends
class SolverPerformance< Type >
Ostream & operator (Ostream &, const LduMatrix< Type, DType, LUType > &)
Detailed Description
template<class Type, class DType, class LUType>
class Foam::LduMatrix< Type, DType, LUType >
LduMatrix is a general matrix class in which the coefficients are stored as three arrays, one for the upper triangle, one for the lower triangle and a third for the diagonal.
Addressing arrays must be supplied for the upper and lower triangles.
Note
It might be better if this class were organised as a hierachy starting from an empty matrix, then deriving diagonal, symmetric and asymmetric matrices.
Source files
LduMatrix.H
LduMatrixATmul.C
LduMatrix.C
LduMatrixOperations.C
LduMatrixSolver.C
LduMatrixPreconditioner.C
LduMatrixTests.C
LduMatrixUpdateMatrixInterfaces.C
Definition at line 69 of file LduMatrix.H.
Constructor & Destructor Documentation
LduMatrix() [1/4]
LduMatrix (const lduMesh & mesh)
Construct given an LDU addressed mesh.
The coefficients are initially empty for subsequent setting.
Definition at line 32 of file LduMatrix.C.
Referenced by LduMatrix< Type, DType, LUType >::preconditioner::preconditionT().
LduMatrix() [2/4]
LduMatrix (const LduMatrix< Type, DType, LUType > &)
Construct as copy.
LduMatrix() [3/4]
LduMatrix (LduMatrix< Type, DType, LUType > & , bool reuse)
Construct as copy or re-use as specified.
LduMatrix() [4/4]
LduMatrix (const lduMesh & mesh, Istream & is)
Construct given an LDU addressed mesh and an Istream.
from which the coefficients are read
Definition at line 144 of file LduMatrix.C.
~LduMatrix()
~LduMatrix ()
Definition at line 163 of file LduMatrix.C.
Referenced by LduMatrix< Type, DType, LUType >::preconditioner::preconditionT().
Member Function Documentation
ClassName()
ClassName ("LduMatrix< Type, DType, LUType >")
Referenced by LduMatrix< Type, DType, LUType >::preconditioner::preconditionT().
mesh()
const lduMesh& mesh () const inline
Return the LDU mesh from which the addressing is obtained.
Definition at line 489 of file LduMatrix.H.
lduAddr()
const lduAddressing& lduAddr () const inline
Return the LDU addressing.
Definition at line 495 of file LduMatrix.H.
Referenced by TDILUPreconditioner< Type, DType, LUType >::calcInvD(), LduMatrix< Type, DType, LUType >::diag(), LduMatrix< Type, DType, LUType >::lower(), LduMatrix< Type, DType, LUType >::patchSchedule(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), LduMatrix< Type, DType, LUType >::source(), and LduMatrix< Type, DType, LUType >::upper().
patchSchedule()
const lduSchedule& patchSchedule () const inline
Return the patch evaluation schedule.
Definition at line 501 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::lduAddr(), and lduAddressing::patchSchedule().
interfaces() [1/2]
const LduInterfaceFieldPtrsList<Type>& interfaces () const inline
Return interfaces.
Definition at line 507 of file LduMatrix.H.
Referenced by TGaussSeidelSmoother< Type, DType, LUType >::smooth().
interfaces() [2/2]
LduInterfaceFieldPtrsList<Type>& interfaces () inline
Return interfaces.
Definition at line 513 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::diag(), LduMatrix< Type, DType, LUType >::lower(), LduMatrix< Type, DType, LUType >::source(), and LduMatrix< Type, DType, LUType >::upper().
diag() [1/2]
Foam::Field< DType > & diag ()
Definition at line 190 of file LduMatrix.C.
References LduMatrix< Type, DType, LUType >::lduAddr(), lduAddressing::size(), and Foam::Zero.
Referenced by LduMatrix< Type, DType, LUType >::interfaces(), LduMatrix< Type, DType, LUType >::interfacesLower(), LduMatrix< Type, DType, LUType >::operator+=(), LduMatrix< Type, DType, LUType >::operator-=(), LduMatrix< Type, DType, LUType >::operator=(), fvMatrix< Type >::solveCoupled(), and TGaussSeidelSmoother< Type, DType, LUType >::TGaussSeidelSmoother().
upper() [1/2]
Foam::Field< LUType > & upper ()
Definition at line 202 of file LduMatrix.C.
References LduMatrix< Type, DType, LUType >::lduAddr(), lduAddressing::lowerAddr(), UList< T >::size(), and Foam::Zero.
Referenced by TDILUPreconditioner< Type, DType, LUType >::calcInvD(), LduMatrix< Type, DType, LUType >::faceH(), LduMatrix< Type, DType, LUType >::interfaces(), LduMatrix< Type, DType, LUType >::interfacesLower(), LduMatrix< Type, DType, LUType >::negSumDiag(), LduMatrix< Type, DType, LUType >::operator+=(), LduMatrix< Type, DType, LUType >::operator-=(), LduMatrix< Type, DType, LUType >::operator=(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), LduMatrix< Type, DType, LUType >::sumDiag(), and LduMatrix< Type, DType, LUType >::sumMagOffDiag().
lower() [1/2]
Foam::Field< LUType > & lower ()
Definition at line 225 of file LduMatrix.C.
References LduMatrix< Type, DType, LUType >::lduAddr(), lduAddressing::lowerAddr(), UList< T >::size(), and Foam::Zero.
Referenced by TDILUPreconditioner< Type, DType, LUType >::calcInvD(), LduMatrix< Type, DType, LUType >::faceH(), LduMatrix< Type, DType, LUType >::interfaces(), LduMatrix< Type, DType, LUType >::interfacesLower(), LduMatrix< Type, DType, LUType >::negSumDiag(), LduMatrix< Type, DType, LUType >::operator+=(), LduMatrix< Type, DType, LUType >::operator-=(), LduMatrix< Type, DType, LUType >::operator=(), TGaussSeidelSmoother< Type, DType, LUType >::smooth(), LduMatrix< Type, DType, LUType >::sumDiag(), and LduMatrix< Type, DType, LUType >::sumMagOffDiag().
source() [1/2]
Foam::Field< Type > & source ()
Definition at line 248 of file LduMatrix.C.
References LduMatrix< Type, DType, LUType >::lduAddr(), lduAddressing::size(), and Foam::Zero.
Referenced by LduMatrix< Type, DType, LUType >::interfaces(), LduMatrix< Type, DType, LUType >::interfacesLower(), LduMatrix< Type, DType, LUType >::operator+=(), LduMatrix< Type, DType, LUType >::operator-=(), LduMatrix< Type, DType, LUType >::operator=(), and TGaussSeidelSmoother< Type, DType, LUType >::smooth().
interfacesUpper() [1/2]
FieldField<Field, LUType>& interfacesUpper () inline
Definition at line 526 of file LduMatrix.H.
Referenced by TGaussSeidelSmoother< Type, DType, LUType >::smooth().
interfacesLower() [1/2]
FieldField<Field, LUType>& interfacesLower () inline
Definition at line 531 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::diag(), LduMatrix< Type, DType, LUType >::lower(), LduMatrix< Type, DType, LUType >::source(), and LduMatrix< Type, DType, LUType >::upper().
diag() [2/2]
const Foam::Field< DType > & diag () const
Definition at line 260 of file LduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
upper() [2/2]
const Foam::Field< LUType > & upper () const
Definition at line 274 of file LduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
lower() [2/2]
const Foam::Field< LUType > & lower () const
Definition at line 295 of file LduMatrix.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
source() [2/2]
const Foam::Field< Type > & source () const
Definition at line 316 of file LduMatrix.C.
References Foam::abort(), IOstream::check(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
interfacesUpper() [2/2]
const FieldField<Field, LUType>& interfacesUpper () const inline
Definition at line 542 of file LduMatrix.H.
interfacesLower() [2/2]
const FieldField<Field, LUType>& interfacesLower () const inline
Definition at line 547 of file LduMatrix.H.
hasDiag()
bool hasDiag () const inline
Definition at line 553 of file LduMatrix.H.
hasUpper()
bool hasUpper () const inline
Definition at line 558 of file LduMatrix.H.
hasLower()
bool hasLower () const inline
Definition at line 563 of file LduMatrix.H.
hasSource()
bool hasSource () const inline
Definition at line 568 of file LduMatrix.H.
diagonal()
bool diagonal () const inline
Definition at line 573 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::New(), LduMatrix< Type, DType, LUType >::operator+=(), and LduMatrix< Type, DType, LUType >::operator-=().
symmetric()
bool symmetric () const inline
Definition at line 578 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::New(), LduMatrix< Type, DType, LUType >::smoother::New(), LduMatrix< Type, DType, LUType >::operator+=(), and LduMatrix< Type, DType, LUType >::operator-=().
asymmetric()
bool asymmetric () const inline
Definition at line 583 of file LduMatrix.H.
References LduMatrix< Type, DType, LUType >::Amul(), LduMatrix< Type, DType, LUType >::faceH(), LduMatrix< Type, DType, LUType >::H(), LduMatrix< Type, DType, LUType >::initMatrixInterfaces(), LduMatrix< Type, DType, LUType >::negate(), LduMatrix< Type, DType, LUType >::negSumDiag(), LduMatrix< Type, DType, LUType >::operator*=(), LduMatrix< Type, DType, LUType >::operator+=(), LduMatrix< Type, DType, LUType >::operator-=(), LduMatrix< Type, DType, LUType >::operator=(), psi, LduMatrix< Type, DType, LUType >::residual(), LduMatrix< Type, DType, LUType >::sumA(), LduMatrix< Type, DType, LUType >::sumDiag(), LduMatrix< Type, DType, LUType >::sumMagOffDiag(), LduMatrix< Type, DType, LUType >::Tmul(), and LduMatrix< Type, DType, LUType >::updateMatrixInterfaces().
Referenced by LduMatrix< Type, DType, LUType >::solver::New(), LduMatrix< Type, DType, LUType >::smoother::New(), LduMatrix< Type, DType, LUType >::operator+=(), and LduMatrix< Type, DType, LUType >::operator-=().
sumDiag()
void sumDiag ()
Definition at line 31 of file LduMatrixOperations.C.
References Foam::diag(), LduMatrix< Type, DType, LUType >::lower(), UList< T >::size(), and LduMatrix< Type, DType, LUType >::upper().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric().
negSumDiag()
void negSumDiag ()
Definition at line 49 of file LduMatrixOperations.C.
References Foam::diag(), LduMatrix< Type, DType, LUType >::lower(), UList< T >::size(), LduMatrix< Type, DType, LUType >::sumMagOffDiag(), and LduMatrix< Type, DType, LUType >::upper().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric().
sumMagOffDiag()
void sumMagOffDiag (Field< LUType > & sumOff) const
Definition at line 68 of file LduMatrixOperations.C.
References Foam::cmptMag(), LduMatrix< Type, DType, LUType >::lower(), UList< T >::size(), and LduMatrix< Type, DType, LUType >::upper().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric(), and LduMatrix< Type, DType, LUType >::negSumDiag().
Amul()
void Amul (Field< Type > & Apsi, const tmp< Field< Type >> & tpsi) const
Matrix multiplication.
Definition at line 64 of file LduMatrixATmul.C.
References UList< Type >::begin(), Foam::diag(), Foam::dot(), psi, and LduMatrix< Type, DType, LUType >::Tmul().
Referenced by Amultiplier< Type, LUType >::addAmul(), and LduMatrix< Type, DType, LUType >::asymmetric().
Tmul()
void Tmul (Field< Type > & Tpsi, const tmp< Field< Type >> & tpsi) const
Matrix transpose multiplication.
Definition at line 118 of file LduMatrixATmul.C.
References UList< Type >::begin(), Foam::diag(), Foam::dot(), psi, and LduMatrix< Type, DType, LUType >::sumA().
Referenced by LduMatrix< Type, DType, LUType >::Amul(), and LduMatrix< Type, DType, LUType >::asymmetric().
sumA()
void sumA (Field< Type > & sumA) const
Sum the coefficients on each row of the matrix.
Definition at line 171 of file LduMatrixATmul.C.
References UList< Type >::begin(), Foam::diag(), Foam::dot(), forAll, patchi, and LduMatrix< Type, DType, LUType >::residual().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric(), and LduMatrix< Type, DType, LUType >::Tmul().
residual() [1/2]
void residual (Field< Type > & rA, const Field< Type > & psi) const
Definition at line 219 of file LduMatrixATmul.C.
References UList< Type >::begin(), Foam::diag(), Foam::dot(), forAll, and patchi.
Referenced by LduMatrix< Type, DType, LUType >::asymmetric(), and LduMatrix< Type, DType, LUType >::sumA().
residual() [2/2]
Foam::tmp< Foam::Field< Type > > residual (const Field< Type > & psi) const
Definition at line 284 of file LduMatrixATmul.C.
References psi, tmp< T >::ref(), and List< Type >::size().
initMatrixInterfaces()
void initMatrixInterfaces (const FieldField< Field, LUType > & interfaceCoeffs, const Field< Type > & psiif, Field< Type > & result) const
Initialise the update of interfaced interfaces.
for matrix operations
Definition at line 33 of file LduMatrixUpdateMatrixInterfaces.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, List< T >::size(), and LduMatrix< Type, DType, LUType >::updateMatrixInterfaces().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric(), and TGaussSeidelSmoother< Type, DType, LUType >::smooth().
updateMatrixInterfaces()
void updateMatrixInterfaces (const FieldField< Field, LUType > & interfaceCoeffs, const Field< Type > & psiif, Field< Type > & result) const
Update interfaced interfaces for matrix operations.
Definition at line 98 of file LduMatrixUpdateMatrixInterfaces.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, and List< T >::size().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric(), LduMatrix< Type, DType, LUType >::initMatrixInterfaces(), and TGaussSeidelSmoother< Type, DType, LUType >::smooth().
H() [1/2]
Foam::tmp< Foam::Field< Type > > H (const Field< Type > & psi) const
Definition at line 88 of file LduMatrixOperations.C.
References UList< Type >::begin(), and Foam::Zero.
Referenced by LduMatrix< Type, DType, LUType >::asymmetric().
H() [2/2]
Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type >> & tpsi) const
Definition at line 123 of file LduMatrixOperations.C.
faceH() [1/2]
Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > & psi) const
Definition at line 133 of file LduMatrixOperations.C.
References LduMatrix< Type, DType, LUType >::lower(), List< T >::size(), UList< T >::size(), and LduMatrix< Type, DType, LUType >::upper().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric().
faceH() [2/2]
Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type >> & tpsi) const
Definition at line 156 of file LduMatrixOperations.C.
operator=()
void operator= (const LduMatrix< Type, DType, LUType > &)
Definition at line 167 of file LduMatrixOperations.C.
References Foam::abort(), Foam::diag(), LduMatrix< Type, DType, LUType >::diag(), Foam::FatalError, FatalErrorInFunction, LduMatrix< Type, DType, LUType >::lower(), LduMatrix< Type, DType, LUType >::source(), and LduMatrix< Type, DType, LUType >::upper().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric().
negate()
void negate ()
Definition at line 212 of file LduMatrixOperations.C.
References Foam::negate().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric().
operator+=()
void operator+= (const LduMatrix< Type, DType, LUType > &)
Definition at line 240 of file LduMatrixOperations.C.
References Foam::abort(), LduMatrix< Type, DType, LUType >::asymmetric(), Foam::diag(), LduMatrix< Type, DType, LUType >::diag(), LduMatrix< Type, DType, LUType >::diagonal(), Foam::FatalError, FatalErrorInFunction, LduMatrix< Type, DType, LUType >::lower(), LduMatrix< Type, DType, LUType >::source(), LduMatrix< Type, DType, LUType >::symmetric(), and LduMatrix< Type, DType, LUType >::upper().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric().
operator-=()
void operator-= (const LduMatrix< Type, DType, LUType > &)
Definition at line 317 of file LduMatrixOperations.C.
References Foam::abort(), LduMatrix< Type, DType, LUType >::asymmetric(), Foam::diag(), LduMatrix< Type, DType, LUType >::diag(), LduMatrix< Type, DType, LUType >::diagonal(), Foam::FatalError, FatalErrorInFunction, LduMatrix< Type, DType, LUType >::lower(), LduMatrix< Type, DType, LUType >::source(), LduMatrix< Type, DType, LUType >::symmetric(), and LduMatrix< Type, DType, LUType >::upper().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric().
operator*=() [1/2]
void operator*= (const scalarField & sf)
Definition at line 395 of file LduMatrixOperations.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, sf(), and List< T >::size().
Referenced by LduMatrix< Type, DType, LUType >::asymmetric().
operator*=() [2/2]
void operator*= (scalar s)
Definition at line 442 of file LduMatrixOperations.C.
References s().
Friends And Related Function Documentation
SolverPerformance< Type >
friend class SolverPerformance< Type > friend
Definition at line 109 of file LduMatrix.H.
operator
Ostream& operator (Ostream & , const LduMatrix< Type, DType, LUType > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.C
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixATmul.C
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixOperations.C
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixUpdateMatrixInterfaces.C