OpenFOAM: simpleMatrix< Type > Class Template Reference
simpleMatrix< Type > Class Template Reference
A simple square matrix solver with scalar coefficients.
Public Member Functions
simpleMatrix (const label)
Construct given size.
simpleMatrix (const label, const scalar, const Type &)
Construct given size and initial values for coefficients and source.
simpleMatrix (const scalarSquareMatrix &, const Field< Type > &)
Construct from components.
simpleMatrix (Istream &)
Construct from Istream.
simpleMatrix (const simpleMatrix< Type > &)
Construct as copy.
Field< Type > & source ()
Return access to the source.
const Field< Type > & source () const
Return const-access to the source.
Field< Type > solve () const
Solve the matrix using Gaussian elimination with pivoting.
Field< Type > LUsolve () const
Solve the matrix using LU decomposition with pivoting.
void operator= (const simpleMatrix< Type > &)
Public Member Functions inherited from SquareMatrix< Type >
SquareMatrix ()
Null constructor.
SquareMatrix (const label n)
Construct given number of rows/columns.
template<class MatrixType >
SquareMatrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
template<class MatrixType >
SquareMatrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
SquareMatrix (const label n, const zero)
Construct given number of rows/columns.
SquareMatrix (const label m, const label n, const zero)
Construct given number of rows and columns (checked to be equal)
SquareMatrix (const label n, const Identity< Type >)
Construct given number of rows/columns.
SquareMatrix (const label n, const Type &)
Construct with given number of rows and rows.
SquareMatrix (const RectangularMatrix< Type > &)
Construct as copy of a RectangularMatrix.
SquareMatrix (Istream &)
Construct from Istream.
autoPtr< SquareMatrix< Type > > clone () const
Clone.
void setSize (const label m)
Resize the matrix preserving the elements.
void shallowResize (const label m)
Resize the matrix without reallocating storage (unsafe)
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Identity< Type >)
Assignment elements to the.
Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label m, const label n)
Construct given number of rows and columns.
Matrix (const label m, const label n, const zero)
Construct with given number of rows and columns.
Matrix (const label m, const label n, const Type &)
Construct with given number of rows and columns.
Matrix (const mType &)
Copy constructor.
Matrix (const Matrix< Form2, Type > &)
Copy constructor from matrix of a different form.
Matrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (Istream &)
Construct from Istream.
autoPtr< mType > clone () const
Clone.
~Matrix ()
Destructor.
label m () const
Return the number of rows.
label n () const
Return the number of columns.
label size () const
Return the number of elements in matrix (m*n)
const Type * v () const
Return element vector of the constant Matrix.
Type * v ()
Return element vector of the Matrix.
ConstMatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart) const
ConstMatrixBlock< mType > block (const label mStart, const label nStart) const
MatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart)
MatrixBlock< mType > block (const label mStart, const label nStart)
Foam::ConstMatrixBlock< Foam::Matrix< SquareMatrix< Type >, Type > > block (const label mStart, const label nStart) const
Foam::MatrixBlock< Foam::Matrix< SquareMatrix< Type >, Type > > block (const label mStart, const label nStart)
ConstMatrixBlock< mType > col (const label m, const label rowStart) const
ConstMatrixBlock< mType > col (const label m, const label mStart, const label nStart) const
MatrixBlock< mType > col (const label m, const label rowStart)
MatrixBlock< mType > col (const label m, const label mStart, const label nStart)
void checki (const label i) const
Check index i is within valid range (0 ... m-1).
void checkj (const label j) const
Check index j is within valid range (0 ... n-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (mType &)
Transfer the contents of the argument Matrix into this Matrix.
void setSize (const label m, const label n)
Resize the matrix preserving the elements.
void shallowResize (const label m, const label n)
Resize the matrix without reallocating storage (unsafe)
SquareMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
const Type & operator() (const label i, const label j) const
(i, j) const element access operator
Type & operator() (const label i, const label j)
(i, j) element access operator
void operator= (const mType &)
Assignment operator. Takes linear time.
void operator= (const ConstMatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const MatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Type &)
Assignment of all elements to the given value.
Friends
Ostream & operator (Ostream &, const simpleMatrix< Type > &)
Additional Inherited Members
Public Types inherited from Matrix< SquareMatrix< Type >, Type >
typedef Matrix< SquareMatrix< Type >, Type > mType
Matrix type.
typedef Type cmptType
Component type.
Static Public Member Functions inherited from Matrix< SquareMatrix< Type >, Type >
static const mType & null ()
Return a null Matrix.
Detailed Description
template<class Type>
class Foam::simpleMatrix< Type >
A simple square matrix solver with scalar coefficients.
Source files
simpleMatrix.H
simpleMatrix.C
Definition at line 47 of file simpleMatrix.H.
Constructor & Destructor Documentation
simpleMatrix() [1/5]
simpleMatrix (const label mSize)
Construct given size.
Note: this does not initialise the coefficients or the source.
Definition at line 31 of file simpleMatrix.C.
Referenced by simpleMatrix< Type >::simpleMatrix().
simpleMatrix() [2/5]
simpleMatrix (const label mSize, const scalar coeffVal, const Type & sourceVal)
Construct given size and initial values for coefficients and source.
Definition at line 40 of file simpleMatrix.C.
References simpleMatrix< Type >::simpleMatrix().
simpleMatrix() [3/5]
simpleMatrix (const scalarSquareMatrix & matrix, const Field< Type > & source)
Construct from components.
Definition at line 53 of file simpleMatrix.C.
simpleMatrix() [4/5]
simpleMatrix (Istream & is)
Construct from Istream.
Definition at line 64 of file simpleMatrix.C.
simpleMatrix() [5/5]
simpleMatrix (const simpleMatrix< Type > &)
Construct as copy.
Member Function Documentation
source() [1/2]
Field<Type>& source () inline
Return access to the source.
Definition at line 97 of file simpleMatrix.H.
Referenced by EulerImplicit< ChemistryModel >::solve().
source() [2/2]
const Field<Type>& source () const inline
Return const-access to the source.
Definition at line 103 of file simpleMatrix.H.
References simpleMatrix< Type >::LUsolve(), simpleMatrix< Type >::operator=(), and simpleMatrix< Type >::solve().
solve()
Foam::Field< Type > solve () const
Solve the matrix using Gaussian elimination with pivoting.
and return the solution
Definition at line 74 of file simpleMatrix.C.
References Foam::solve().
Referenced by simpleMatrix< Type >::source().
LUsolve()
Foam::Field< Type > LUsolve () const
Solve the matrix using LU decomposition with pivoting.
and return the solution
Definition at line 86 of file simpleMatrix.C.
References Foam::LUsolve().
Referenced by EulerImplicit< ChemistryModel >::solve(), and simpleMatrix< Type >::source().
operator=()
void operator= (const simpleMatrix< Type > & m)
Definition at line 100 of file simpleMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Matrix< SquareMatrix< Type >, Type >::m(), Foam::nl, SquareMatrix< scalar >::operator=(), and s().
Referenced by simpleMatrix< Type >::source().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const simpleMatrix< Type > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/simpleMatrix/simpleMatrix.H
src/OpenFOAM/matrices/simpleMatrix/simpleMatrix.C