OpenFOAM: SymmetricSquareMatrix< Type > Class Template Reference
SymmetricSquareMatrix< Type > Class Template Reference
A templated 2D square symmetric matrix of objects of <T>, where the n x n matrix dimension is known and used for subscript bounds checking, etc.
Public Member Functions
SymmetricSquareMatrix ()
Null constructor.
SymmetricSquareMatrix (const label n)
Construct given number of rows/columns.
SymmetricSquareMatrix (const label n, const zero)
Construct given number of rows/columns, initializing to zero.
SymmetricSquareMatrix (const label n, const Identity< Type >)
Construct given number of rows/columns,.
SymmetricSquareMatrix (const label n, const Type &)
Construct with given number of rows/columns.
SymmetricSquareMatrix (Istream &)
Construct from Istream.
autoPtr< SymmetricSquareMatrix< Type > > clone () const
Clone.
Public Member Functions inherited from Matrix< SymmetricSquareMatrix< Type >, Type >
Matrix ()
Null constructor.
Matrix (const label m, const label n)
Construct given number of rows and columns.
Matrix (const label m, const label n, const zero)
Construct with given number of rows and columns.
Matrix (const label m, const label n, const Type &)
Construct with given number of rows and columns.
Matrix (const mType &)
Copy constructor.
Matrix (const Matrix< Form2, Type > &)
Copy constructor from matrix of a different form.
Matrix (const ConstMatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (const MatrixBlock< MatrixType > &)
Construct from a block of another matrix.
Matrix (Istream &)
Construct from Istream.
autoPtr< mType > clone () const
Clone.
~Matrix ()
Destructor.
label m () const
Return the number of rows.
label n () const
Return the number of columns.
label size () const
Return the number of elements in matrix (m*n)
const Type * v () const
Return element vector of the constant Matrix.
Type * v ()
Return element vector of the Matrix.
ConstMatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart) const
ConstMatrixBlock< mType > block (const label mStart, const label nStart) const
MatrixBlock< mType > block (const label m, const label n, const label mStart, const label nStart)
MatrixBlock< mType > block (const label mStart, const label nStart)
Foam::ConstMatrixBlock< Foam::Matrix< SymmetricSquareMatrix< Type >, Type > > block (const label mStart, const label nStart) const
Foam::MatrixBlock< Foam::Matrix< SymmetricSquareMatrix< Type >, Type > > block (const label mStart, const label nStart)
ConstMatrixBlock< mType > col (const label m, const label rowStart) const
ConstMatrixBlock< mType > col (const label m, const label mStart, const label nStart) const
MatrixBlock< mType > col (const label m, const label rowStart)
MatrixBlock< mType > col (const label m, const label mStart, const label nStart)
void checki (const label i) const
Check index i is within valid range (0 ... m-1).
void checkj (const label j) const
Check index j is within valid range (0 ... n-1).
void clear ()
Clear the Matrix, i.e. set sizes to zero.
void transfer (mType &)
Transfer the contents of the argument Matrix into this Matrix.
void setSize (const label m, const label n)
Resize the matrix preserving the elements.
void shallowResize (const label m, const label n)
Resize the matrix without reallocating storage (unsafe)
SymmetricSquareMatrix< Type > T () const
Return the transpose of the matrix.
Type * operator[] (const label)
Return subscript-checked row of Matrix.
const Type * operator[] (const label) const
Return subscript-checked row of constant Matrix.
const Type & operator() (const label i, const label j) const
(i, j) const element access operator
Type & operator() (const label i, const label j)
(i, j) element access operator
void operator= (const mType &)
Assignment operator. Takes linear time.
void operator= (const ConstMatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const MatrixBlock< MatrixType > &)
Assignment to a block of another matrix.
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Type &)
Assignment of all elements to the given value.
Additional Inherited Members
Public Types inherited from Matrix< SymmetricSquareMatrix< Type >, Type >
typedef Matrix< SymmetricSquareMatrix< Type >, Type > mType
Matrix type.
typedef Type cmptType
Component type.
Static Public Member Functions inherited from Matrix< SymmetricSquareMatrix< Type >, Type >
static const mType & null ()
Return a null Matrix.
Detailed Description
template<class Type>
class Foam::SymmetricSquareMatrix< Type >
A templated 2D square symmetric matrix of objects of <T>, where the n x n matrix dimension is known and used for subscript bounds checking, etc.
Source files
SymmetricSquareMatrix.H
SymmetricSquareMatrixI.H
SymmetricSquareMatrix.C
Definition at line 52 of file SymmetricSquareMatrix.H.
Constructor & Destructor Documentation
SymmetricSquareMatrix() [1/6]
SymmetricSquareMatrix () inline
Null constructor.
Definition at line 29 of file SymmetricSquareMatrixI.H.
Referenced by SymmetricSquareMatrix< Type >::SymmetricSquareMatrix().
SymmetricSquareMatrix() [2/6]
SymmetricSquareMatrix (const label n) inline
Construct given number of rows/columns.
Definition at line 36 of file SymmetricSquareMatrixI.H.
References SymmetricSquareMatrix< Type >::SymmetricSquareMatrix().
SymmetricSquareMatrix() [3/6]
SymmetricSquareMatrix (const label n, const zero) inline
Construct given number of rows/columns, initializing to zero.
Definition at line 44 of file SymmetricSquareMatrixI.H.
References SymmetricSquareMatrix< Type >::SymmetricSquareMatrix().
SymmetricSquareMatrix() [4/6]
SymmetricSquareMatrix (const label n, const Identity< Type >) inline
Construct given number of rows/columns,.
Definition at line 55 of file SymmetricSquareMatrixI.H.
References Matrix< SymmetricSquareMatrix< Type >, Type >::n(), Matrix< SymmetricSquareMatrix< Type >, Type >::operator()(), and SymmetricSquareMatrix< Type >::SymmetricSquareMatrix().
SymmetricSquareMatrix() [5/6]
SymmetricSquareMatrix (const label n, const Type & t) inline
Construct with given number of rows/columns.
initializing all elements to the given value
Definition at line 71 of file SymmetricSquareMatrixI.H.
SymmetricSquareMatrix() [6/6]
SymmetricSquareMatrix (Istream & is) inline
Construct from Istream.
Definition at line 81 of file SymmetricSquareMatrixI.H.
Member Function Documentation
clone()
Foam::autoPtr< Foam::SymmetricSquareMatrix< Type > > clone () const inline
Clone.
Definition at line 89 of file SymmetricSquareMatrixI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/SymmetricSquareMatrix/SymmetricSquareMatrix.H
src/OpenFOAM/matrices/SymmetricSquareMatrix/SymmetricSquareMatrixI.H