OpenFOAM: SVD Class Reference
SVD Class Reference
Singular value decomposition of a rectangular matrix.
Public Member Functions
SVD (const scalarRectangularMatrix &A, const scalar minCondition=0)
Construct from a rectangular Matrix.
const scalarRectangularMatrix & U () const
Return U.
const scalarRectangularMatrix & V () const
Return the square matrix V.
const scalarDiagonalMatrix & S () const
Return the singular values.
bool converged () const
Return the minimum non-zero singular value.
label nZeros () const
Return the number of zero singular values.
scalar minNonZeroS () const
Return the minimum non-zero singular value.
scalarRectangularMatrix VSinvUt () const
Return the matrix product V S^(-1) U^T (the pseudo inverse)
Detailed Description
Singular value decomposition of a rectangular matrix.
Source files
SVD.H
SVDI.H
SVD.C
Definition at line 51 of file SVD.H.
Constructor & Destructor Documentation
SVD()
SVD (const scalarRectangularMatrix & A, const scalar minCondition = 0)
Construct from a rectangular Matrix.
Definition at line 33 of file SVD.C.
References Foam::constant::universal::c, f(), Foam::findMax(), forAll, g, h, k, Matrix< Form, Type >::m(), Foam::mag(), Foam::max(), Foam::min(), Matrix< Form, Type >::n(), s(), Foam::sqrt(), Foam::sqrtSumSqr(), x, and y.
Member Function Documentation
U()
const Foam::scalarRectangularMatrix & U () const inline
Return U.
Definition at line 38 of file SVDI.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT().
V()
const Foam::scalarRectangularMatrix & V () const inline
Return the square matrix V.
Definition at line 44 of file SVDI.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT().
S()
const Foam::scalarDiagonalMatrix & S () const inline
Return the singular values.
Definition at line 50 of file SVDI.H.
Referenced by CentredFitSnGradData< Polynomial >::calcFit(), and chemPointISAT< CompType, ThermoType >::chemPointISAT().
converged()
bool converged () const inline
Return the minimum non-zero singular value.
Definition at line 56 of file SVDI.H.
nZeros()
Foam::label nZeros () const inline
Return the number of zero singular values.
Definition at line 62 of file SVDI.H.
minNonZeroS()
Foam::scalar minNonZeroS () const inline
Return the minimum non-zero singular value.
Definition at line 68 of file SVDI.H.
References s(), and List< T >::size().
VSinvUt()
Foam::scalarRectangularMatrix VSinvUt () const
Return the matrix product V S^(-1) U^T (the pseudo inverse)
Definition at line 385 of file SVD.C.
References Foam::inv(), Foam::multiply(), and Matrix< Form, Type >::T().
Referenced by CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), and Foam::SVDinv().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/scalarMatrices/SVD/SVD.H
src/OpenFOAM/matrices/scalarMatrices/SVD/SVD.C
src/OpenFOAM/matrices/scalarMatrices/SVD/SVDI.H