OpenFOAM: lduMesh Class Reference
lduMesh Class Reference abstract
Abstract base class for meshes which provide LDU addressing for the construction of lduMatrix and LDU-solvers.
Public Member Functions
TypeName ("lduMesh")
Runtime type information.
virtual ~lduMesh ()
Destructor.
virtual const objectRegistry & thisDb () const
Return the object registry.
virtual const lduAddressing & lduAddr () const =0
Return ldu addressing.
virtual lduInterfacePtrsList interfaces () const =0
Return a list of pointers for each patch.
virtual label comm () const =0
Return communicator used for parallel communication.
template<class T , class BinaryOp >
void reduce (T &Value, const BinaryOp &bop) const
Helper: reduce with current communicator.
InfoProxy< lduMesh > info () const
Return info proxy.
Friends
Ostream & operator<< (Ostream &, const InfoProxy< lduMesh > &)
Detailed Description
Abstract base class for meshes which provide LDU addressing for the construction of lduMatrix and LDU-solvers.
Definition at line 59 of file lduMesh.H.
Constructor & Destructor Documentation
~lduMesh()
virtual ~lduMesh () inline virtual
Destructor.
Definition at line 71 of file lduMesh.H.
References lduMesh::comm(), lduMesh::info(), lduMesh::interfaces(), lduMesh::lduAddr(), lduMesh::reduce(), Foam::T(), and lduMesh::thisDb().
Member Function Documentation
TypeName()
TypeName ("lduMesh")
Runtime type information.
thisDb()
const Foam::objectRegistry & thisDb () const virtual
Return the object registry.
Reimplemented in fvMesh.
Definition at line 40 of file lduMesh.C.
References NotImplemented.
Referenced by GAMGAgglomeration::New(), and lduMesh::~lduMesh().
lduAddr()
virtual const lduAddressing& lduAddr () const pure virtual
Return ldu addressing.
Implemented in fvMesh, and lduPrimitiveMesh.
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), GAMGAgglomeration::compactLevels(), dummyAgglomeration::dummyAgglomeration(), lduPrimitiveMesh::gather(), GAMGProcAgglomeration::globalCellCells(), lduMatrix::lduAddr(), lduPrimitiveMesh::lduPrimitiveMesh(), MGridGenGAMGAgglomeration::MGridGenGAMGAgglomeration(), Foam::operator<<(), and lduMesh::~lduMesh().
interfaces()
virtual lduInterfacePtrsList interfaces () const pure virtual
Return a list of pointers for each patch.
with only those pointing to interfaces being set
Implemented in fvMesh, and lduPrimitiveMesh.
Referenced by GAMGAgglomeration::compactLevels(), lduPrimitiveMesh::gather(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::lduPrimitiveMesh(), MGridGenGAMGAgglomeration::MGridGenGAMGAgglomeration(), regionCoupledBaseGAMGInterface::nbrLduInterface(), Foam::operator<<(), and lduMesh::~lduMesh().
comm()
virtual label comm () const pure virtual
Return communicator used for parallel communication.
Implemented in fvMesh, and lduPrimitiveMesh.
Referenced by GAMGProcAgglomeration::agglomerate(), masterCoarsestGAMGProcAgglomeration::agglomerate(), eagerGAMGProcAgglomeration::agglomerate(), procFacesGAMGProcAgglomeration::agglomerate(), manualGAMGProcAgglomeration::agglomerate(), GAMGAgglomeration::agglomerateLduAddressing(), GAMGSolver::GAMGSolver(), GAMGProcAgglomeration::globalCellCells(), lduPrimitiveMesh::lduPrimitiveMesh(), Foam::operator<<(), smoothSolver::solve(), and lduMesh::~lduMesh().
reduce()
void reduce (T & Value, const BinaryOp & bop) const
Helper: reduce with current communicator.
Definition at line 32 of file lduMeshTemplates.C.
References Foam::reduce().
Referenced by engineMesh::engineMesh(), and lduMesh::~lduMesh().
info()
InfoProxy<lduMesh> info () const inline
Return info proxy.
Used to print mesh information to a stream
Definition at line 105 of file lduMesh.H.
Referenced by GAMGProcAgglomeration::printStats(), and lduMesh::~lduMesh().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const InfoProxy< lduMesh > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/lduMesh/lduMesh.H
src/OpenFOAM/meshes/lduMesh/lduMesh.C
src/OpenFOAM/meshes/lduMesh/lduMeshTemplates.C