OpenFOAM: tetCell Class Reference
tetCell Class Reference
A tetrahedral cell primitive.
Public Member Functions
tetCell ()
Construct null.
tetCell (const label a, const label b, const label c, const label d)
Construct from four points.
tetCell (const FixedList< label, 4 > &)
Construct from FixedList.
tetCell (Istream &)
Construct from Istream.
triFace face (const label facei) const
Return i-th face.
label edgeFace (const label edgeI) const
Return first face adjacent to the given edge.
label edgeAdjacentFace (const label edgeI, const label facei) const
Return face adjacent to the given face sharing the same edge.
edge tetEdge (const label edgeI) const
Return i-th edge.
cellShape tetCellShape () const
Return tet shape cell.
tetPointRef tet (const pointField &) const
Return the tetrahedron.
Public Member Functions inherited from FixedList< label, 4 >
FixedList ()
Null constructor.
FixedList (const label &)
Construct from value.
FixedList (const label v[Size])
Construct from C-array.
FixedList (InputIterator first, InputIterator last)
Construct given start and end iterators.
FixedList (std::initializer_list< label >)
Construct from an initializer list.
FixedList (const UList< label > &)
Construct from UList.
FixedList (const SLList< label > &)
Construct from SLList.
FixedList (const FixedList< label, Size > &)
Copy constructor.
FixedList (Istream &)
Construct from Istream.
autoPtr< FixedList< label, Size > > clone () const
Clone.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
const label * cdata () const
Return a const pointer to the first data element,.
label * data ()
Return a pointer to the first data element,.
label & first ()
Return the first element of the list.
const label & first () const
Return first element of the list.
label & last ()
Return the last element of the list.
const label & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void resize (const label)
Dummy resize function.
void setSize (const label)
Dummy setSize function.
void transfer (const FixedList< label, Size > &)
Copy (not transfer) the argument contents.
void writeEntry (Ostream &) const
Write the FixedList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the FixedList as a dictionary entry with keyword.
label & operator[] (const label)
Return element of FixedList.
const label & operator[] (const label) const
Return element of constant FixedList.
void operator= (const label v[Size])
Assignment to array operator. Takes linear time.
void operator= (const UList< label > &)
Assignment to UList operator. Takes linear time.
void operator= (const SLList< label > &)
Assignment to SLList operator. Takes linear time.
void operator= (std::initializer_list< label >)
Assignment to an initializer list. Takes linear time.
void operator= (const label &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the FixedList.
const_iterator begin () const
Return const_iterator to begin traversing the constant FixedList.
iterator end ()
Return an iterator to end traversing the FixedList.
const_iterator end () const
Return const_iterator to end traversing the constant FixedList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant FixedList.
const_iterator cend () const
Return const_iterator to end traversing the constant FixedList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the FixedList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the FixedList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing FixedList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing FixedList.
label size () const
Return the number of elements in the FixedList.
label max_size () const
Return size of the largest possible FixedList.
bool empty () const
Return true if the FixedList is empty (ie, size() is zero)
void swap (FixedList< label, Size > &)
Swap two FixedLists of the same type in constant time.
bool operator== (const FixedList< label, Size > &) const
Equality operation on FixedLists of the same type.
bool operator!= (const FixedList< label, Size > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const FixedList< label, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator> (const FixedList< label, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator<= (const FixedList< label, Size > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const FixedList< label, Size > &) const
Return true if !(a < b). Takes linear time.
Additional Inherited Members
Public Types inherited from FixedList< label, 4 >
typedef label value_type
Type of values the FixedList contains.
typedef label & reference
Type that can be used for storing into.
typedef const label & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a FixedList.
typedef label * iterator
Random access iterator for traversing FixedList.
typedef const label * const_iterator
Random access iterator for traversing FixedList.
typedef label * reverse_iterator
Reverse iterator for reverse traversal of FixedList.
typedef const label * const_reverse_iterator
Reverse iterator for reverse traversal of constant FixedList.
Static Public Member Functions inherited from FixedList< label, 4 >
static const FixedList< label, Size > & null ()
Return a null FixedList.
Detailed Description
A tetrahedral cell primitive.
It is important that the ordering of edges is the same for a tetrahedron class, a tetrahedron cell shape model and a tetCell
Source files
tetCell.H
tetCell.C
tetCellI.H
Definition at line 58 of file tetCell.H.
Constructor & Destructor Documentation
tetCell() [1/4]
tetCell () inline
Construct null.
Definition at line 32 of file tetCellI.H.
tetCell() [2/4]
tetCell (const label a, const label b, const label c, const label d) inline
Construct from four points.
Definition at line 37 of file tetCellI.H.
References Foam::constant::physicoChemical::b, Foam::constant::universal::c, and FixedList< label, 4 >::operator[]().
tetCell() [3/4]
tetCell (const FixedList< label, 4 > & lst) inline
Construct from FixedList.
Definition at line 51 of file tetCellI.H.
tetCell() [4/4]
tetCell (Istream & is) inline
Construct from Istream.
Definition at line 57 of file tetCellI.H.
Member Function Documentation
face()
Foam::triFace face (const label facei) const inline
Return i-th face.
Definition at line 65 of file tetCellI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and triFace().
edgeFace()
Foam::label edgeFace (const label edgeI) const inline
Return first face adjacent to the given edge.
Definition at line 91 of file tetCellI.H.
References Foam::abort(), tetCell::edgeAdjacentFace(), Foam::FatalError, and FatalErrorInFunction.
edgeAdjacentFace()
Foam::label edgeAdjacentFace (const label edgeI, const label facei) const inline
Return face adjacent to the given face sharing the same edge.
Definition at line 112 of file tetCellI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by tetCell::edgeFace().
tetEdge()
Foam::edge tetEdge (const label edgeI) const inline
Return i-th edge.
Definition at line 149 of file tetCellI.H.
References Foam::abort(), FixedList< label, 4 >::end(), Foam::FatalError, and FatalErrorInFunction.
tetCellShape()
Foam::cellShape tetCellShape () const
Return tet shape cell.
Definition at line 33 of file tetCell.C.
References cellModeller::lookup(), and tetCell::tet().
tet()
Foam::tetPointRef tet (const pointField & points) const inline
Return the tetrahedron.
Definition at line 170 of file tetCellI.H.
Referenced by tetCell::tetCellShape().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/tetCell/tetCell.H
src/OpenFOAM/meshes/meshShapes/tetCell/tetCell.C
src/OpenFOAM/meshes/meshShapes/tetCell/tetCellI.H