OpenFOAM: edge Class Reference
edge Class Reference
An edge is a list of two point labels. The functionality it provides supports the discretisation on a 2-D flat mesh.
Public Member Functions
edge ()
Null constructor for lists.
edge (const label a, const label b)
Construct from components.
edge (const FixedList< label, 2 > &)
Construct from FixedList.
edge (Istream &)
Construct from Istream.
label start () const
Return start vertex label.
label & start ()
Return start vertex label.
label end () const
Return end vertex label.
label & end ()
Return end vertex label.
label otherVertex (const label a) const
Given one vertex, return the other.
label commonVertex (const edge &a) const
Return common vertex.
void flip ()
Flip the edge in-place.
edge reverseEdge () const
Return reverse edge.
point centre (const pointField &) const
Return centre (centroid)
vector vec (const pointField &) const
Return the vector (end - start)
scalar mag (const pointField &) const
Return scalar magnitude.
linePointRef line (const pointField &) const
Return edge line.
Public Member Functions inherited from FixedList< label, 2 >
FixedList ()
Null constructor.
FixedList (const label &)
Construct from value.
FixedList (const label v[Size])
Construct from C-array.
FixedList (InputIterator first, InputIterator last)
Construct given start and end iterators.
FixedList (std::initializer_list< label >)
Construct from an initializer list.
FixedList (const UList< label > &)
Construct from UList.
FixedList (const SLList< label > &)
Construct from SLList.
FixedList (const FixedList< label, Size > &)
Copy constructor.
FixedList (Istream &)
Construct from Istream.
autoPtr< FixedList< label, Size > > clone () const
Clone.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
const label * cdata () const
Return a const pointer to the first data element,.
label * data ()
Return a pointer to the first data element,.
label & first ()
Return the first element of the list.
const label & first () const
Return first element of the list.
label & last ()
Return the last element of the list.
const label & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void resize (const label)
Dummy resize function.
void setSize (const label)
Dummy setSize function.
void transfer (const FixedList< label, Size > &)
Copy (not transfer) the argument contents.
void writeEntry (Ostream &) const
Write the FixedList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the FixedList as a dictionary entry with keyword.
label & operator[] (const label)
Return element of FixedList.
const label & operator[] (const label) const
Return element of constant FixedList.
void operator= (const label v[Size])
Assignment to array operator. Takes linear time.
void operator= (const UList< label > &)
Assignment to UList operator. Takes linear time.
void operator= (const SLList< label > &)
Assignment to SLList operator. Takes linear time.
void operator= (std::initializer_list< label >)
Assignment to an initializer list. Takes linear time.
void operator= (const label &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the FixedList.
const_iterator begin () const
Return const_iterator to begin traversing the constant FixedList.
iterator end ()
Return an iterator to end traversing the FixedList.
const_iterator end () const
Return const_iterator to end traversing the constant FixedList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant FixedList.
const_iterator cend () const
Return const_iterator to end traversing the constant FixedList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the FixedList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the FixedList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing FixedList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing FixedList.
label size () const
Return the number of elements in the FixedList.
label max_size () const
Return size of the largest possible FixedList.
bool empty () const
Return true if the FixedList is empty (ie, size() is zero)
void swap (FixedList< label, Size > &)
Swap two FixedLists of the same type in constant time.
bool operator== (const FixedList< label, Size > &) const
Equality operation on FixedLists of the same type.
bool operator!= (const FixedList< label, Size > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const FixedList< label, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator> (const FixedList< label, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator<= (const FixedList< label, Size > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const FixedList< label, Size > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static int compare (const edge &, const edge &)
Compare edges.
Static Public Member Functions inherited from FixedList< label, 2 >
static const FixedList< label, Size > & null ()
Return a null FixedList.
Static Public Attributes
static const char *const typeName = "edge"
Friends
bool operator== (const edge &a, const edge &b)
bool operator!= (const edge &a, const edge &b)
Additional Inherited Members
Public Types inherited from FixedList< label, 2 >
typedef label value_type
Type of values the FixedList contains.
typedef label & reference
Type that can be used for storing into.
typedef const label & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a FixedList.
typedef label * iterator
Random access iterator for traversing FixedList.
typedef const label * const_iterator
Random access iterator for traversing FixedList.
typedef label * reverse_iterator
Reverse iterator for reverse traversal of FixedList.
typedef const label * const_reverse_iterator
Reverse iterator for reverse traversal of constant FixedList.
Detailed Description
An edge is a list of two point labels. The functionality it provides supports the discretisation on a 2-D flat mesh.
Source files
edge.H
edgeI.H
Definition at line 58 of file edge.H.
Constructor & Destructor Documentation
edge() [1/4]
edge () inline
Null constructor for lists.
Definition at line 55 of file edgeI.H.
Referenced by edge::reverseEdge().
edge() [2/4]
edge (const label a, const label b) inline
Construct from components.
Definition at line 59 of file edgeI.H.
References Foam::constant::physicoChemical::b, edge::end(), and edge::start().
edge() [3/4]
edge (const FixedList< label, 2 > & a) inline
Construct from FixedList.
Definition at line 66 of file edgeI.H.
References edge::end(), and edge::start().
edge() [4/4]
edge (Istream & is) inline
Construct from Istream.
Definition at line 73 of file edgeI.H.
Member Function Documentation
start() [1/2]
Foam::label start () const inline
Return start vertex label.
Definition at line 81 of file edgeI.H.
References FixedList< label, 2 >::operator[]().
Referenced by edgeSurface::addIntersectionEdges(), edge::centre(), edgeCollapser::checkMeshQuality(), PatchTools::checkOrientation(), PrimitivePatch< Face, ::Foam::List, pointField, point >::checkTopology(), triSurfaceTools::collapseEdges(), edge::commonVertex(), curvedEdge::compare(), edgeVertex::coord(), polyMeshFilter::copyMesh(), twoDPointCorrector::correctDisplacement(), particle< Type >::crossEdgeConnectedFace(), geomCellLooper::cut(), edge::edge(), triFace::edgeDirection(), face::edgeDirection(), extendedEdgeMesh::edgeDirection(), edgeSurface::edgeSurface(), directionInfo::edgeToFaceIndex(), searchablePlateFeatures::features(), Foam::meshTools::findEdge(), triSurfaceTools::getEdge(), cellLooper::getFirstVertEdge(), triSurfaceTools::getVertexTriangles(), triSurfaceTools::getVertexVertices(), treeDataFace::getVolumeType(), triSurfaceTools::greenRefine(), intersectedSurface::intersectedSurface(), cellFeatures::isFeaturePoint(), edge::line(), edgeCollapser::markSmallEdges(), triSurfaceTools::maxEdge(), triSurfaceTools::minEdge(), slidingInterface::modifyMotionPoints(), motionSmootherAlgo::modifyMotionPoints(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), cellCuts::nonAnchorPoints(), triSurfaceTools::oppositeEdge(), triSurfaceTools::oppositeVertex(), Foam::meshTools::otherEdge(), edge::otherVertex(), treeDataEdge::overlaps(), Foam::polyMeshZipUpCells(), edge::reverseEdge(), boundaryMesh::setFeatureEdges(), faceCollapser::setRefinement(), boundaryCutter::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), PatchTools::sortedEdgeFaces(), PatchTools::sortedPointEdges(), extendedEdgeMesh::sortPointsAndEdges(), surfaceIntersection::surfaceIntersection(), directionInfo::updateCell(), patchEdgeFaceRegions::updateEdge(), patchEdgeFaceRegions::updateFace(), boundaryCutter::updateMesh(), meshCutAndRemove::updateMesh(), meshCutter::updateMesh(), edge::vec(), PrimitivePatch< Face, ::Foam::List, pointField, point >::whichEdge(), extendedEdgeMesh::writeObj(), and blockMesh::writeTopology().
start() [2/2]
Foam::label & start () inline
Return start vertex label.
Definition at line 86 of file edgeI.H.
References FixedList< label, 2 >::operator[]().
end() [1/2]
Foam::label end () const inline
Return end vertex label.
Definition at line 92 of file edgeI.H.
References FixedList< label, 2 >::operator[]().
Referenced by edgeSurface::addIntersectionEdges(), edge::centre(), edgeCollapser::checkMeshQuality(), PatchTools::checkOrientation(), PrimitivePatch< Face, ::Foam::List, pointField, point >::checkTopology(), triSurfaceTools::collapseEdges(), edge::commonVertex(), curvedEdge::compare(), edgeVertex::coord(), polyMeshFilter::copyMesh(), twoDPointCorrector::correctDisplacement(), particle< Type >::crossEdgeConnectedFace(), geomCellLooper::cut(), edge::edge(), triFace::edgeDirection(), face::edgeDirection(), extendedEdgeMesh::edgeDirection(), edgeSurface::edgeSurface(), directionInfo::edgeToFaceIndex(), searchablePlateFeatures::features(), Foam::meshTools::findEdge(), triSurfaceTools::getEdge(), cellLooper::getFirstVertEdge(), triSurfaceTools::getVertexTriangles(), triSurfaceTools::getVertexVertices(), treeDataFace::getVolumeType(), triSurfaceTools::greenRefine(), intersectedSurface::intersectedSurface(), cellFeatures::isFeaturePoint(), edge::line(), edgeCollapser::markSmallEdges(), triSurfaceTools::maxEdge(), triSurfaceTools::minEdge(), slidingInterface::modifyMotionPoints(), motionSmootherAlgo::modifyMotionPoints(), surfaceFeatures::nearestSurfEdge(), cellCuts::nonAnchorPoints(), triSurfaceTools::oppositeEdge(), triSurfaceTools::oppositeVertex(), Foam::meshTools::otherEdge(), edge::otherVertex(), treeDataEdge::overlaps(), Foam::polyMeshZipUpCells(), edge::reverseEdge(), boundaryMesh::setFeatureEdges(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), PatchTools::sortedPointEdges(), extendedEdgeMesh::sortPointsAndEdges(), surfaceIntersection::surfaceIntersection(), boundaryCutter::updateMesh(), meshCutAndRemove::updateMesh(), meshCutter::updateMesh(), edge::vec(), and blockMesh::writeTopology().
end() [2/2]
Foam::label & end () inline
Return end vertex label.
Definition at line 97 of file edgeI.H.
References FixedList< label, 2 >::operator[]().
otherVertex()
Foam::label otherVertex (const label a) const inline
Given one vertex, return the other.
Definition at line 103 of file edgeI.H.
References edge::end(), and edge::start().
Referenced by edgeCollapser::checkMeshQuality(), removePoints::countPointUsage(), hexRef8::faceLevel(), triSurfaceTools::getVertexVertices(), listPlusEqOp< T >::operator()(), GTSsurfaceFormat< Face >::read(), surfaceFeatures::setFromStatus(), and triSurfaceTools::surfaceSide().
commonVertex()
Foam::label commonVertex (const edge & a) const inline
Return common vertex.
Definition at line 121 of file edgeI.H.
References edge::end(), and edge::start().
Referenced by removePoints::countPointUsage(), and GTSsurfaceFormat< Face >::read().
flip()
void flip () inline
Flip the edge in-place.
Definition at line 139 of file edgeI.H.
References Foam::Swap().
Referenced by patchEdgeFaceRegions::updateEdge(), and patchEdgeFaceRegions::updateFace().
reverseEdge()
Foam::edge reverseEdge () const inline
Return reverse edge.
Definition at line 145 of file edgeI.H.
References edge::edge(), edge::end(), and edge::start().
centre()
Foam::point centre (const pointField & p) const inline
Return centre (centroid)
Definition at line 151 of file edgeI.H.
References edge::end(), and edge::start().
Referenced by surfaceFeatures::nearestEdges(), surfaceFeatures::nearestFeatEdge(), hexRef8::setRefinement(), treeDataEdge::shapePoints(), pointEdgePoint::updateEdge(), and externalPointEdgePoint::updateEdge().
vec()
Foam::vector vec (const pointField & p) const inline
Return the vector (end - start)
Definition at line 157 of file edgeI.H.
References edge::end(), and edge::start().
Referenced by refinementFeatures::findNearestEdge(), cellFeatures::isFeaturePoint(), edge::mag(), slidingInterface::modifyMotionPoints(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), ifEqEqOp< value >::operator()(), PatchTools::sortedEdgeFaces(), and extendedEdgeMesh::sortPointsAndEdges().
mag()
Foam::scalar mag (const pointField & p) const inline
Return scalar magnitude.
Definition at line 163 of file edgeI.H.
References Foam::mag(), and edge::vec().
Referenced by snappySnapDriver::calcSnapDistance(), layerAdditionRemoval::changeTopology(), edgeCollapser::markSmallEdges(), surfaceFeatures::setFromStatus(), surfaceIntersection::surfaceIntersection(), and surfaceFeatures::trimFeatures().
line()
Foam::linePointRef line (const pointField & p) const inline
Return edge line.
Definition at line 169 of file edgeI.H.
References edge::end(), and edge::start().
Referenced by extendedEdgeMesh::allNearestFeatureEdges(), treeDataPrimitivePatch< PatchType >::getVolumeType(), slidingInterface::modifyMotionPoints(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), treeDataEdge::findNearestOp::operator()(), treeDataEdge::overlaps(), addPatchCellLayer::setRefinement(), and surfaceLocation::write().
compare()
int compare (const edge & a, const edge & b) inline static
Compare edges.
Returns:
0: different
+1: identical
-1: same edge, but different orientation
Definition at line 36 of file edgeI.H.
Referenced by Foam::operator!=(), and Foam::operator==().
Friends And Related Function Documentation
operator==
bool operator== (const edge & a, const edge & b) friend
operator!=
bool operator!= (const edge & a, const edge & b) friend
Member Data Documentation
typeName
const char *const typeName = "edge" static
Definition at line 67 of file edge.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/edge/edge.H
src/OpenFOAM/meshes/meshShapes/edge/edge.C
src/OpenFOAM/meshes/meshShapes/edge/edgeI.H