OpenFOAM: face Class Reference
face Class Reference
A face is a list of labels corresponding to mesh vertices.
Public Types
enum proxType { NONE, POINT, EDGE }
Return types for classify.
Public Types inherited from List< label >
typedef SubList< label > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
face ()
Construct null.
face (label)
Construct given size.
face (const labelUList &)
Construct from list of labels.
face (const labelList &)
Construct from list of labels.
face (const Xfer< labelList > &)
Construct by transferring the parameter contents.
face (const triFace &)
Copy construct from triFace.
face (Istream &)
Construct from Istream.
label collapse ()
Collapse face by removing duplicate point labels.
void flip ()
Flip the face in-place.
pointField points (const pointField &) const
Return the points corresponding to this face.
point centre (const pointField &) const
Centre point of face.
template<class Type >
Type average (const pointField &, const Field< Type > &) const
Calculate average value at centroid of face.
scalar mag (const pointField &) const
Magnitude of face area.
vector normal (const pointField &) const
Vector normal; magnitude is equal to area of face.
face reverseFace () const
Return face with reverse direction.
label which (const label globalIndex) const
Navigation through face vertices.
label nextLabel (const label i) const
Next vertex on face.
label prevLabel (const label i) const
Previous vertex on face.
scalar sweptVol (const pointField &oldPoints, const pointField &newPoints) const
Return the volume swept out by the face when its points move.
tensor inertia (const pointField &, const point &refPt=vector::zero, scalar density=1.0) const
Return the inertia tensor, with optional reference.
pointHit ray (const point &p, const vector &n, const pointField &, const intersection::algorithm alg=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR) const
Return potential intersection with face with a ray starting.
pointHit intersection (const point &p, const vector &q, const point &ctr, const pointField &, const intersection::algorithm alg, const scalar tol=0.0) const
Fast intersection with a ray.
pointHit nearestPoint (const point &p, const pointField &) const
Return nearest point to face.
pointHit nearestPointClassify (const point &p, const pointField &, label &nearType, label &nearLabel) const
Return nearest point to face and classify it:
scalar contactSphereDiameter (const point &p, const vector &n, const pointField &) const
Return contact sphere diameter.
scalar areaInContact (const pointField &, const scalarField &v) const
Return area in contact, given the displacement in vertices.
label nEdges () const
Return number of edges.
edgeList edges () const
Return edges in face point ordering,.
edge faceEdge (const label n) const
Return n-th face edge.
int edgeDirection (const edge &) const
Return the edge direction on the face.
label nTriangles () const
Number of triangles after splitting.
label nTriangles (const pointField &points) const
Number of triangles after splitting.
label triangles (const pointField &points, label &triI, faceList &triFaces) const
Split into triangles using existing points.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
label triangles (const pointField &points, DynamicList< face, SizeInc, SizeMult, SizeDiv > &triFaces) const
Split into triangles using existing points.
label nTrianglesQuads (const pointField &points, label &nTris, label &nQuads) const
Number of triangles and quads after splitting.
label trianglesQuads (const pointField &points, label &triI, label &quadI, faceList &triFaces, faceList &quadFaces) const
Split into triangles and quads.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
Foam::label triangles (const pointField &points, DynamicList< face, SizeInc, SizeMult, SizeDiv > &triFaces) const
Public Member Functions inherited from List< label >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const label &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< label > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< label >> &)
Construct by transferring the parameter contents.
List (List< label > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< label > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< label, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< label > &)
Construct as copy of PtrList<T>
List (const SLList< label > &)
Construct as copy of SLList<T>
List (const UIndirectList< label > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< label > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< label >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< label > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const label &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const label &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const label &)
Append an element at the end of the list.
void append (const UList< label > &)
Append a List at the end of this list.
void append (const UIndirectList< label > &)
Append a UIndirectList at the end of this list.
void transfer (List< label > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< label, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< label > &)
Transfer the contents of the argument List into this list.
Xfer< List< label > > xfer ()
Transfer contents to the Xfer container.
label & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< label > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< label > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< label > &)
Assignment operator. Takes linear time.
void operator= (const SLList< label > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< label > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< label > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< label >)
Assignment to an initializer list.
void operator= (const label &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static int compare (const face &, const face &)
Compare faces.
static bool sameVertices (const face &, const face &)
Return true if the faces have the same vertices.
Static Public Member Functions inherited from List< label >
static const List< label > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes
static const char *const typeName = "face"
Friends
bool operator== (const face &a, const face &b)
bool operator!= (const face &a, const face &b)
Istream & operator>> (Istream &, face &)
Additional Inherited Members
Protected Member Functions inherited from List< label >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
A face is a list of labels corresponding to mesh vertices.
See also
Foam::triFace
Source files
face.H
faceI.H
face.C
faceIntersection.C
faceContactSphere.C
faceAreaInContact.C
faceTemplates.C
Definition at line 75 of file face.H.
Member Enumeration Documentation
proxType
enum proxType
Return types for classify.
Enumerator
NONE
POINT
EDGE
Definition at line 134 of file face.H.
Constructor & Destructor Documentation
face() [1/7]
face () inline
Construct null.
Definition at line 44 of file faceI.H.
Referenced by face::reverseFace().
face() [2/7]
face (label s) inline explicit
Construct given size.
Definition at line 48 of file faceI.H.
face() [3/7]
face (const labelUList & lst) inline explicit
Construct from list of labels.
Definition at line 54 of file faceI.H.
face() [4/7]
face (const labelList & lst) inline explicit
Construct from list of labels.
Definition at line 60 of file faceI.H.
face() [5/7]
face (const Xfer< labelList > & lst) inline explicit
Construct by transferring the parameter contents.
Definition at line 66 of file faceI.H.
face() [6/7]
face (const triFace & f)
Copy construct from triFace.
Definition at line 290 of file face.C.
face() [7/7]
face (Istream & is) inline
Construct from Istream.
Definition at line 72 of file faceI.H.
Member Function Documentation
collapse()
Foam::label collapse ()
Collapse face by removing duplicate point labels.
return the collapsed size
Definition at line 449 of file face.C.
References UList< T >::operator[](), List< label >::setSize(), and List< label >::size().
Referenced by STARCD::readCells().
flip()
void flip ()
Flip the face in-place.
The starting points of the original and flipped face are identical.
Definition at line 474 of file face.C.
References n, List< label >::size(), and Foam::Swap().
Referenced by hexRef8::faceLevel().
points()
Foam::pointField points (const pointField & meshPoints) const inline
Return the points corresponding to this face.
Definition at line 80 of file faceI.H.
References forAll, UList< T >::operator[](), p, and List< label >::size().
Referenced by AMIMethod< SourcePatch, TargetPatch >::writeIntersectionOBJ().
centre()
Foam::point centre (const pointField & points) const
Centre point of face.
Definition at line 488 of file face.C.
References Foam::mag(), nPoints, UList< T >::operator[](), List< label >::size(), and Foam::Zero.
Referenced by searchableBox::boundingSpheres(), edgeCollapser::checkMeshQuality(), hexRef8::faceLevel(), AMIMethod< SourcePatch, TargetPatch >::findTargetFace(), face::inertia(), cellCuts::nonAnchorPoints(), and face::sweptVol().
average()
Type average (const pointField & meshPoints, const Field< Type > & fld) const
Calculate average value at centroid of face.
Definition at line 51 of file faceTemplates.C.
References Foam::mag(), nPoints, and Foam::Zero.
Referenced by face::triangles().
mag()
Foam::scalar mag (const pointField & p) const inline
Magnitude of face area.
Definition at line 97 of file faceI.H.
References Foam::mag(), and face::normal().
Referenced by face::areaInContact(), edgeCollapser::checkMeshQuality(), faceAreaWeightAMI< SourcePatch, TargetPatch >::interArea(), and listPlusEqOp< T >::operator()().
normal()
Foam::vector normal (const pointField & p) const
Vector normal; magnitude is equal to area of face.
Definition at line 552 of file face.C.
References n, nPoints, UList< T >::operator[](), List< label >::size(), and Foam::Zero.
Referenced by hexRef8::faceLevel(), faceTriangulation::faceTriangulation(), face::mag(), cellCuts::nonAnchorPoints(), and snappySnapDriver::repatchToSurface().
reverseFace()
Foam::face reverseFace () const
Return face with reverse direction.
The starting points of the original and reverse face are identical.
Definition at line 611 of file face.C.
References f(), face::face(), List< T >::size(), List< label >::size(), and Foam::xferMove().
Referenced by NamedEnum< directionType, 3 >::names(), ifEqEqOp< value >::operator()(), hexRef8::setInstance(), removeCells::setRefinement(), and createShellMesh::setRefinement().
which()
Foam::label which (const label globalIndex) const
Navigation through face vertices.
Which vertex on face (face index given a global index)
returns -1 if not found
Definition at line 630 of file face.C.
References f(), forAll, and face::sweptVol().
nextLabel()
Foam::label nextLabel (const label i) const inline
Next vertex on face.
Definition at line 117 of file faceI.H.
References UList< T >::fcIndex(), and UList< T >::operator[]().
Referenced by polyMeshGeometry::affectedCells(), polyMeshGeometry::checkFaceFlatness(), polyMeshTetDecomposition::checkFaceTets(), primitiveMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkTriangleTwist(), wallBoundedParticle::crossEdgeConnectedFace(), wallBoundedParticle::currentEdge(), primitiveMesh::faceEdges(), combineFaces::getOutsideFace(), meshTriangulation::meshTriangulation(), NamedEnum< directionType, 3 >::names(), polyMesh::pointInCell(), wallBoundedStreamLine::read(), edgeFaceCirculator::setCanonical(), boundaryCutter::setRefinement(), and tetDecomposer::setRefinement().
prevLabel()
Foam::label prevLabel (const label i) const inline
Previous vertex on face.
Definition at line 124 of file faceI.H.
References UList< T >::operator[](), and UList< T >::rcIndex().
Referenced by edgeCollapser::checkMeshQuality(), and tetDecomposer::setRefinement().
sweptVol()
Foam::scalar sweptVol (const pointField & oldPoints, const pointField & newPoints) const
Return the volume swept out by the face when its points move.
Definition at line 647 of file face.C.
References face::centre(), face::inertia(), nPoints, Foam::constant::mathematical::pi(), and List< label >::size().
Referenced by face::which().
inertia()
Foam::tensor inertia (const pointField & p, const point & refPt = vector::zero, scalar density = 1.0) const
Return the inertia tensor, with optional reference.
point and density specification
Definition at line 726 of file face.C.
References face::centre(), UList< T >::fcIndex(), forAll, List< label >::size(), and Foam::Zero.
Referenced by edgeCollapser::checkMeshQuality(), and face::sweptVol().
ray()
Foam::pointHit ray (const point & p, const vector & n, const pointField & meshPoints, const intersection::algorithm alg = intersection::FULL_RAY, const intersection::direction dir = intersection::VECTOR) const
Return potential intersection with face with a ray starting.
at p, direction n (does not need to be normalized) Does face-centre decomposition and returns triangle intersection point closest to p. Face-centre is calculated from point average. For a hit, the distance is signed. Positive number represents the point in front of triangle In case of miss the point is the nearest point on the face and the distance is the distance between the intersection point and the original point. The half-ray or full-ray intersection and the contact sphere adjustment of the projection vector is set by the intersection parameters
Definition at line 34 of file faceIntersection.C.
References Foam::average(), PointHit< Point >::distance(), PointHit< Point >::eligibleMiss(), f(), PointHit< Point >::hit(), PointHit< Point >::hitPoint(), face::intersection(), Foam::mag(), PointHit< Point >::missPoint(), nPoints, points, PointHit< Point >::setDistance(), PointHit< Point >::setHit(), PointHit< Point >::setMiss(), and PointHit< Point >::setPoint().
Referenced by treeDataCell::findIntersectOp::operator()(), AMIInterpolation< SourcePatch, TargetPatch >::srcPointFace(), and AMIInterpolation< SourcePatch, TargetPatch >::tgtPointFace().
intersection()
Foam::pointHit intersection (const point & p, const vector & q, const point & ctr, const pointField & meshPoints, const intersection::algorithm alg, const scalar tol = 0.0) const
Fast intersection with a ray.
Does face-centre decomposition and returns triangle intersection point closest to p. See triangle::intersection for details.
Definition at line 141 of file faceIntersection.C.
References PointHit< Point >::distance(), f(), forAll, PointHit< Point >::hit(), PointHit< Point >::hitPoint(), Foam::mag(), face::nearestPoint(), PointHit< Point >::setDistance(), PointHit< Point >::setHit(), and PointHit< Point >::setPoint().
Referenced by face::ray().
nearestPoint()
Foam::pointHit nearestPoint (const point & p, const pointField & meshPoints) const
Return nearest point to face.
Definition at line 199 of file faceIntersection.C.
References face::nearestPointClassify().
Referenced by meshSearch::findNearestBoundaryFace(), sampledSet::findNearFace(), treeDataFace::getVolumeType(), face::intersection(), nearestEqOp::operator()(), treeDataFace::findNearestOp::operator()(), and treeDataPrimitivePatch< PatchType >::overlaps().
nearestPointClassify()
Foam::pointHit nearestPointClassify (const point & p, const pointField & meshPoints, label & nearType, label & nearLabel) const
Return nearest point to face and classify it:
+ near point (nearType=POINT, nearLabel=0, 1, 2) + near edge (nearType=EDGE, nearLabel=0, 1, 2) Note: edges are counted from starting vertex so e.g. edge n is from f[n] to f[0], where the face has n + 1 points
Definition at line 213 of file faceIntersection.C.
References PointHit< Point >::distance(), f(), PointHit< Point >::hit(), PointHit< Point >::hitPoint(), Foam::mag(), PointHit< Point >::missPoint(), triangle< Point, PointRef >::nearestPointClassify(), nPoints, PointHit< Point >::setDistance(), PointHit< Point >::setHit(), PointHit< Point >::setMiss(), PointHit< Point >::setPoint(), and List< T >::size().
Referenced by face::nearestPoint().
contactSphereDiameter()
Foam::scalar contactSphereDiameter (const point & p, const vector & n, const pointField & meshPoints) const
Return contact sphere diameter.
Definition at line 34 of file faceContactSphere.C.
References Foam::mag(), and p.
areaInContact()
Foam::scalar areaInContact (const pointField & meshPoints, const scalarField & v) const
Return area in contact, given the displacement in vertices.
Definition at line 33 of file faceAreaInContact.C.
References forAll, face::mag(), Foam::mag(), List< T >::setSize(), and List< T >::size().
nEdges()
Foam::label nEdges () const inline
Return number of edges.
Definition at line 103 of file faceI.H.
References List< label >::size().
edges()
Foam::edgeList edges () const
Return edges in face point ordering,.
i.e. edges()[0] is edge between [0] and [1]
Definition at line 761 of file face.C.
References Foam::e, UList< T >::last(), and List< T >::size().
Referenced by edgeCollapser::checkMeshQuality(), Foam::longestEdge(), and Foam::polyMeshZipUpCells().
faceEdge()
Foam::edge faceEdge (const label n) const inline
Return n-th face edge.
Definition at line 110 of file faceI.H.
References UList< T >::fcIndex().
edgeDirection()
int edgeDirection (const edge & e) const
Return the edge direction on the face.
Returns:
0: edge not found on the face
+1: forward (counter-clockwise) on the face
-1: reverse (clockwise) on the face
Definition at line 779 of file face.C.
References edge::end(), UList< T >::fcIndex(), forAll, UList< T >::rcIndex(), and edge::start().
Referenced by particle< Type >::crossEdgeConnectedFace(), patchFaceOrientation::updateEdge(), and patchFaceOrientation::updateFace().
nTriangles() [1/2]
Foam::label nTriangles () const inline
Number of triangles after splitting.
Definition at line 130 of file faceI.H.
References List< label >::size().
Referenced by boundaryMesh::getNTris(), face::nTriangles(), STARCDsurfaceFormat< Face >::read(), boundaryMesh::triangulate(), triSurfaceTools::triangulate(), and boundaryMesh::triangulateLocal().
nTriangles() [2/2]
Foam::label nTriangles (const pointField & points) const
Number of triangles after splitting.
Definition at line 822 of file face.C.
References face::nTriangles(), and face::triangles().
triangles() [1/3]
Foam::label triangles (const pointField & points, label & triI, faceList & triFaces) const
Split into triangles using existing points.
Result in triFaces[triI..triI+nTri]. Splits intelligently to maximize triangle quality. Returns number of faces created.
Definition at line 829 of file face.C.
References face::nTrianglesQuads().
Referenced by faceAreaIntersect::calc(), NamedEnum< directionType, 3 >::names(), face::nTriangles(), STARCDsurfaceFormat< Face >::read(), boundaryMesh::triangulate(), MeshedSurface< Foam::face >::triangulate(), triSurfaceTools::triangulate(), boundaryMesh::triangulateLocal(), and patchInjectionBase::updateMesh().
triangles() [2/3]
label triangles (const pointField & points, DynamicList< face, SizeInc, SizeMult, SizeDiv > & triFaces) const
Split into triangles using existing points.
Append to DynamicList. Returns number of faces created.
nTrianglesQuads()
Foam::label nTrianglesQuads (const pointField & points, label & nTris, label & nQuads) const
Number of triangles and quads after splitting.
Returns the sum of both
Definition at line 843 of file face.C.
References face::trianglesQuads().
Referenced by face::triangles().
trianglesQuads()
Foam::label trianglesQuads (const pointField & points, label & triI, label & quadI, faceList & triFaces, faceList & quadFaces) const
Split into triangles and quads.
Results in triFaces (starting at triI) and quadFaces (starting at quadI). Returns number of new faces created.
Definition at line 857 of file face.C.
Referenced by face::nTrianglesQuads().
compare()
int compare (const face & a, const face & b) static
Compare faces.
0: different +1: identical -1: same face, but different orientation
Definition at line 298 of file face.C.
References CirculatorBase::ANTICLOCKWISE, ConstCirculator< ContainerType >::circulate(), CirculatorBase::CLOCKWISE, ConstCirculator< ContainerType >::setFulcrumToIterator(), ConstCirculator< ContainerType >::setIteratorToFulcrum(), and List< T >::size().
Referenced by Foam::operator!=(), and Foam::operator==().
sameVertices()
bool sameVertices (const face & a, const face & b) static
Return true if the faces have the same vertices.
Definition at line 400 of file face.C.
References forAll, and List< T >::size().
triangles() [3/3]
Foam::label triangles (const pointField & points, DynamicList< face, SizeInc, SizeMult, SizeDiv > & triFaces) const
Definition at line 33 of file faceTemplates.C.
References face::average(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), and List< T >::size().
Friends And Related Function Documentation
operator==
bool operator== (const face & a, const face & b) friend
operator!=
bool operator!= (const face & a, const face & b) friend
operator>>
Istream& operator>> (Istream & , face &) friend
Member Data Documentation
typeName
const char *const typeName = "face" static
Definition at line 143 of file face.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/face/face.H
src/OpenFOAM/meshes/meshShapes/face/face.C
src/OpenFOAM/meshes/meshShapes/face/faceAreaInContact.C
src/OpenFOAM/meshes/meshShapes/face/faceContactSphere.C
src/OpenFOAM/meshes/meshShapes/face/faceI.H
src/OpenFOAM/meshes/meshShapes/face/faceIntersection.C
src/OpenFOAM/meshes/meshShapes/face/faceTemplates.C