OpenFOAM: triFace Class Reference
triFace Class Reference
A triangular face using a FixedList of labels corresponding to mesh vertices.
Public Member Functions
triFace ()
Construct null.
triFace (const label a, const label b, const label c)
Construct from three point labels.
triFace (const labelUList &)
Construct from a list of labels.
triFace (Istream &)
Construct from Istream.
label collapse ()
Collapse face by removing duplicate point labels.
void flip ()
Flip the face in-place.
pointField points (const pointField &) const
Return the points corresponding to this face.
face triFaceFace () const
Return triangle as a face.
triPointRef tri (const pointField &) const
Return the triangle.
point centre (const pointField &) const
Return centre (centroid)
template<class Type >
Type average (const pointField &, const Field< Type > &) const
Calculate average value at centroid of face.
scalar mag (const pointField &) const
Magnitude of face area.
vector normal (const pointField &) const
Vector normal; magnitude is equal to area of face.
label nTriangles () const
Number of triangles after splitting.
triFace reverseFace () const
Return face with reverse direction.
scalar sweptVol (const pointField &oldPoints, const pointField &newPoints) const
Return swept-volume.
tensor inertia (const pointField &, const point &refPt=vector::zero, scalar density=1.0) const
Return the inertia tensor, with optional reference.
pointHit ray (const point &p, const vector &q, const pointField &points, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR) const
Return point intersection with a ray starting at p,.
pointHit intersection (const point &p, const vector &q, const pointField &points, const intersection::algorithm alg, const scalar tol=0.0) const
Fast intersection with a ray.
pointHit intersection (const point &p, const vector &q, const point &ctr, const pointField &points, const intersection::algorithm alg, const scalar tol=0.0) const
pointHit nearestPoint (const point &p, const pointField &points) const
Return nearest point to face.
pointHit nearestPointClassify (const point &p, const pointField &points, label &nearType, label &nearLabel) const
Return nearest point to face and classify it:
label nEdges () const
Return number of edges.
edgeList edges () const
Return edges in face point ordering,.
edge faceEdge (const label n) const
Return n-th face edge.
int edgeDirection (const edge &) const
Return the edge direction on the face.
Public Member Functions inherited from FixedList< label, 3 >
FixedList ()
Null constructor.
FixedList (const label &)
Construct from value.
FixedList (const label v[Size])
Construct from C-array.
FixedList (InputIterator first, InputIterator last)
Construct given start and end iterators.
FixedList (std::initializer_list< label >)
Construct from an initializer list.
FixedList (const UList< label > &)
Construct from UList.
FixedList (const SLList< label > &)
Construct from SLList.
FixedList (const FixedList< label, Size > &)
Copy constructor.
FixedList (Istream &)
Construct from Istream.
autoPtr< FixedList< label, Size > > clone () const
Clone.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
const label * cdata () const
Return a const pointer to the first data element,.
label * data ()
Return a pointer to the first data element,.
label & first ()
Return the first element of the list.
const label & first () const
Return first element of the list.
label & last ()
Return the last element of the list.
const label & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void resize (const label)
Dummy resize function.
void setSize (const label)
Dummy setSize function.
void transfer (const FixedList< label, Size > &)
Copy (not transfer) the argument contents.
void writeEntry (Ostream &) const
Write the FixedList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the FixedList as a dictionary entry with keyword.
label & operator[] (const label)
Return element of FixedList.
const label & operator[] (const label) const
Return element of constant FixedList.
void operator= (const label v[Size])
Assignment to array operator. Takes linear time.
void operator= (const UList< label > &)
Assignment to UList operator. Takes linear time.
void operator= (const SLList< label > &)
Assignment to SLList operator. Takes linear time.
void operator= (std::initializer_list< label >)
Assignment to an initializer list. Takes linear time.
void operator= (const label &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the FixedList.
const_iterator begin () const
Return const_iterator to begin traversing the constant FixedList.
iterator end ()
Return an iterator to end traversing the FixedList.
const_iterator end () const
Return const_iterator to end traversing the constant FixedList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant FixedList.
const_iterator cend () const
Return const_iterator to end traversing the constant FixedList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the FixedList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the FixedList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing FixedList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing FixedList.
label size () const
Return the number of elements in the FixedList.
label max_size () const
Return size of the largest possible FixedList.
bool empty () const
Return true if the FixedList is empty (ie, size() is zero)
void swap (FixedList< label, Size > &)
Swap two FixedLists of the same type in constant time.
bool operator== (const FixedList< label, Size > &) const
Equality operation on FixedLists of the same type.
bool operator!= (const FixedList< label, Size > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const FixedList< label, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator> (const FixedList< label, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator<= (const FixedList< label, Size > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const FixedList< label, Size > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static int compare (const triFace &, const triFace &)
Compare triFaces.
Static Public Member Functions inherited from FixedList< label, 3 >
static const FixedList< label, Size > & null ()
Return a null FixedList.
Friends
bool operator== (const triFace &, const triFace &)
bool operator!= (const triFace &, const triFace &)
Additional Inherited Members
Public Types inherited from FixedList< label, 3 >
typedef label value_type
Type of values the FixedList contains.
typedef label & reference
Type that can be used for storing into.
typedef const label & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a FixedList.
typedef label * iterator
Random access iterator for traversing FixedList.
typedef const label * const_iterator
Random access iterator for traversing FixedList.
typedef label * reverse_iterator
Reverse iterator for reverse traversal of FixedList.
typedef const label * const_reverse_iterator
Reverse iterator for reverse traversal of constant FixedList.
Detailed Description
A triangular face using a FixedList of labels corresponding to mesh vertices.
See also
Foam::face, Foam::triangle
Source files
triFace.H
triFaceI.H
triFaceTemplates.C
Definition at line 68 of file triFace.H.
Constructor & Destructor Documentation
triFace() [1/4]
triFace () inline
Construct null.
Definition at line 64 of file triFaceI.H.
Referenced by triFace::reverseFace().
triFace() [2/4]
triFace (const label a, const label b, const label c) inline
Construct from three point labels.
Definition at line 69 of file triFaceI.H.
References Foam::constant::physicoChemical::b, Foam::constant::universal::c, and FixedList< label, 3 >::operator[]().
triFace() [3/4]
triFace (const labelUList & lst) inline explicit
Construct from a list of labels.
Definition at line 81 of file triFaceI.H.
triFace() [4/4]
triFace (Istream & is) inline
Construct from Istream.
Definition at line 87 of file triFaceI.H.
Member Function Documentation
collapse()
Foam::label collapse () inline
Collapse face by removing duplicate point labels.
return the collapsed size, set collapsed point labels to -1
Definition at line 95 of file triFaceI.H.
References n, and FixedList< label, 3 >::operator[]().
flip()
void flip () inline
Flip the face in-place.
The starting points of the original and flipped face are identical.
Definition at line 122 of file triFaceI.H.
References Foam::Swap().
points()
Foam::pointField points (const pointField & points) const inline
Return the points corresponding to this face.
Definition at line 128 of file triFaceI.H.
References FixedList< label, 3 >::operator[](), and p.
triFaceFace()
Foam::face triFaceFace () const inline
Return triangle as a face.
Definition at line 140 of file triFaceI.H.
References f(), and FixedList< label, 3 >::operator[]().
Referenced by nearestEqOp::operator()().
tri()
Foam::triPointRef tri (const pointField & points) const inline
Return the triangle.
Definition at line 152 of file triFaceI.H.
Referenced by triSurfaceTools::calcInterpolationWeights(), triFace::inertia(), triFace::intersection(), triFace::nearestPoint(), triFace::nearestPointClassify(), and triFace::ray().
centre()
Foam::point centre (const pointField & points) const inline
Return centre (centroid)
Definition at line 163 of file triFaceI.H.
References FixedList< label, 3 >::operator[]().
average()
Type average (const pointField & meshPoints, const Field< Type > & fld) const
Calculate average value at centroid of face.
Definition at line 32 of file triFaceTemplates.C.
mag()
Foam::scalar mag (const pointField & points) const inline
Magnitude of face area.
Definition at line 174 of file triFaceI.H.
References Foam::mag(), and triFace::normal().
normal()
Foam::vector normal (const pointField & points) const inline
Vector normal; magnitude is equal to area of face.
Definition at line 181 of file triFaceI.H.
References FixedList< label, 3 >::operator[]().
Referenced by wallBoundedParticle::isTriAlongTrack(), triFace::mag(), wallBoundedParticle::trackFaceTri(), and wallBoundedParticle::trackToEdge().
nTriangles()
Foam::label nTriangles () const inline
Number of triangles after splitting.
Definition at line 191 of file triFaceI.H.
reverseFace()
Foam::triFace reverseFace () const inline
Return face with reverse direction.
The starting points of the original and reverse face are identical.
Definition at line 197 of file triFaceI.H.
References triFace::sweptVol(), and triFace::triFace().
sweptVol()
Foam::scalar sweptVol (const pointField & oldPoints, const pointField & newPoints) const inline
Return swept-volume.
Definition at line 205 of file triFaceI.H.
References triFace::inertia(), and FixedList< label, 3 >::operator[]().
Referenced by triFace::reverseFace().
inertia()
Foam::tensor inertia (const pointField & points, const point & refPt = vector::zero, scalar density = 1.0) const inline
Return the inertia tensor, with optional reference.
point and density specification
Definition at line 238 of file triFaceI.H.
References triangle< Point, PointRef >::inertia(), triFace::ray(), and triFace::tri().
Referenced by triFace::sweptVol().
ray()
Foam::pointHit ray (const point & p, const vector & q, const pointField & points, const intersection::algorithm alg = intersection::FULL_RAY, const intersection::direction dir = intersection::VECTOR) const inline
Return point intersection with a ray starting at p,.
with direction q.
Definition at line 250 of file triFaceI.H.
References triFace::intersection(), triangle< Point, PointRef >::ray(), and triFace::tri().
Referenced by triFace::inertia().
intersection() [1/2]
Foam::pointHit intersection (const point & p, const vector & q, const pointField & points, const intersection::algorithm alg, const scalar tol = 0.0) const inline
Fast intersection with a ray.
Definition at line 264 of file triFaceI.H.
References triangle< Point, PointRef >::intersection(), and triFace::tri().
Referenced by triFace::intersection(), and triFace::ray().
intersection() [2/2]
Foam::pointHit intersection (const point & p, const vector & q, const point & ctr, const pointField & points, const intersection::algorithm alg, const scalar tol = 0.0) const inline
Definition at line 277 of file triFaceI.H.
References triFace::intersection(), and triFace::nearestPoint().
nearestPoint()
Foam::pointHit nearestPoint (const point & p, const pointField & points) const inline
Return nearest point to face.
Definition at line 291 of file triFaceI.H.
References triangle< Point, PointRef >::nearestPoint(), triFace::nearestPointClassify(), and triFace::tri().
Referenced by triFace::intersection().
nearestPointClassify()
Foam::pointHit nearestPointClassify (const point & p, const pointField & points, label & nearType, label & nearLabel) const inline
Return nearest point to face and classify it:
+ near point (nearType=POINT, nearLabel=0, 1, 2) + near edge (nearType=EDGE, nearLabel=0, 1, 2) Note: edges are counted from starting vertex so e.g. edge n is from f[n] to f[0], where the face has n + 1 points
Definition at line 301 of file triFaceI.H.
References triangle< Point, PointRef >::nearestPointClassify(), and triFace::tri().
Referenced by triFace::nearestPoint(), triSurfaceTools::surfaceNormal(), and triSurfaceTools::surfaceSide().
nEdges()
Foam::label nEdges () const inline
Return number of edges.
Definition at line 312 of file triFaceI.H.
edges()
Foam::edgeList edges () const inline
Return edges in face point ordering,.
i.e. edges()[0] is edge between [0] and [1]
Definition at line 318 of file triFaceI.H.
References Foam::e, UList< T >::end(), and FixedList< label, 3 >::operator[]().
faceEdge()
Foam::edge faceEdge (const label n) const inline
Return n-th face edge.
Definition at line 335 of file triFaceI.H.
References FixedList< label, 3 >::fcIndex().
edgeDirection()
int edgeDirection (const edge & e) const inline
Return the edge direction on the face.
Returns:
+1: forward (counter-clockwise) on the face
-1: reverse (clockwise) on the face
0: edge not found on the face
Definition at line 345 of file triFaceI.H.
References edge::end(), FixedList< label, 3 >::operator[](), and edge::start().
compare()
int compare (const triFace & a, const triFace & b) inline static
Compare triFaces.
Returns:
0: different
+1: identical
-1: same face, but different orientation
Definition at line 33 of file triFaceI.H.
Referenced by Foam::operator!=(), and Foam::operator==().
Friends And Related Function Documentation
operator==
bool operator== (const triFace & , const triFace &) friend
operator!=
bool operator!= (const triFace & , const triFace &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/triFace/triFace.H
src/OpenFOAM/meshes/meshShapes/triFace/triFaceI.H
src/OpenFOAM/meshes/meshShapes/triFace/triFaceTemplates.C