OpenFOAM: pointPatchMapper Class Reference
pointPatchMapper Class Reference
Mapping class for a pointPatchField.
Public Member Functions
pointPatchMapper (const pointPatch &patch, const pointMapper &pointMap, const mapPolyMesh &mpm)
Construct from mappers.
virtual ~pointPatchMapper ()
Destructor.
virtual label size () const
Return size.
virtual bool hasUnmapped () const
Are there unmapped values? I.e. do all size() elements get.
virtual label sizeBeforeMapping () const
Return size of field before mapping.
virtual bool direct () const
Is the mapping direct.
virtual const labelUList & directAddressing () const
Return direct addressing.
virtual const labelListList & addressing () const
Return interpolated addressing.
virtual const scalarListList & weights () const
Return interpolaion weights.
Public Member Functions inherited from pointPatchFieldMapper
pointPatchFieldMapper ()
Null constructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
Mapping class for a pointPatchField.
Source files
pointPatchMapper.H
pointPatchMapper.C
Definition at line 55 of file pointPatchMapper.H.
Constructor & Destructor Documentation
pointPatchMapper()
pointPatchMapper (const pointPatch & patch, const pointMapper & pointMap, const mapPolyMesh & mpm)
Construct from mappers.
Definition at line 113 of file pointPatchMapper.C.
~pointPatchMapper()
~pointPatchMapper () virtual
Destructor.
Definition at line 138 of file pointPatchMapper.C.
Member Function Documentation
size()
virtual label size () const inline virtual
Return size.
Implements FieldMapper.
Definition at line 129 of file pointPatchMapper.H.
References pointPatch::size().
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implements FieldMapper.
Definition at line 134 of file pointPatchMapper.H.
sizeBeforeMapping()
virtual label sizeBeforeMapping () const inline virtual
Return size of field before mapping.
Definition at line 140 of file pointPatchMapper.H.
direct()
virtual bool direct () const inline virtual
Is the mapping direct.
Implements FieldMapper.
Definition at line 146 of file pointPatchMapper.H.
References pointPatchMapper::addressing(), FieldMapper::direct(), pointPatchMapper::directAddressing(), and pointPatchMapper::weights().
Referenced by pointPatchMapper::addressing(), pointPatchMapper::directAddressing(), and pointPatchMapper::weights().
directAddressing()
const Foam::labelUList & directAddressing () const virtual
Return direct addressing.
Reimplemented from FieldMapper.
Definition at line 146 of file pointPatchMapper.C.
References Foam::abort(), pointPatchMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by pointPatchMapper::direct().
addressing()
const Foam::labelListList & addressing () const virtual
Return interpolated addressing.
Reimplemented from FieldMapper.
Definition at line 164 of file pointPatchMapper.C.
References Foam::abort(), pointPatchMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by pointPatchMapper::direct().
weights()
const Foam::scalarListList & weights () const virtual
Return interpolaion weights.
Reimplemented from FieldMapper.
Definition at line 182 of file pointPatchMapper.C.
References Foam::abort(), pointPatchMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by pointPatchMapper::direct().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointMeshMapper/pointPatchMapper.H
src/OpenFOAM/meshes/pointMesh/pointMeshMapper/pointPatchMapper.C