OpenFOAM: symmetryPointPatch Class Reference
symmetryPointPatch Class Reference
Symmetry patch for non-planar or multi-plane patches.
Public Member Functions
TypeName (symmetryPolyPatch::typeName_())
Runtime type information.
symmetryPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from polyPatch.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Public Member Functions inherited from facePointPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &, const pointBoundaryMesh &)
Construct from polyPatch.
virtual ~facePointPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label size () const
Return size.
virtual label index () const
Return the index of this patch in the pointBoundaryMesh.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const
Return mesh points.
virtual const pointField & localPoints () const
Return pointField of points in patch.
virtual const vectorField & pointNormals () const
Return point unit normals.
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
virtual ~pointPatch ()
Destructor.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
Additional Inherited Members
Static Public Member Functions inherited from facePointPatch
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
Protected Member Functions inherited from facePointPatch
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Attributes inherited from facePointPatch
const polyPatch & polyPatch_
Reference to the underlying polyPatch.
Detailed Description
Symmetry patch for non-planar or multi-plane patches.
Source files
symmetryPointPatch.H
symmetryPointPatch.C
See also
symmetryPlanePointPatch
Definition at line 52 of file symmetryPointPatch.H.
Constructor & Destructor Documentation
symmetryPointPatch()
symmetryPointPatch (const polyPatch & patch, const pointBoundaryMesh & bm) inline
Construct from polyPatch.
Definition at line 67 of file symmetryPointPatch.H.
Member Function Documentation
TypeName()
TypeName (symmetryPolyPatch::typeName_())
Runtime type information.
constraintType()
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatch implements.
Reimplemented from pointPatch.
Definition at line 79 of file symmetryPointPatch.H.
References symmetryPointPatch::applyConstraint(), and Foam::type().
applyConstraint()
void applyConstraint (const label pointi, pointConstraint & pc) const virtual
Accumulate the effect of constraint direction of this patch.
Reimplemented from pointPatch.
Definition at line 51 of file symmetryPointPatch.C.
References pointConstraint::applyConstraint().
Referenced by symmetryPointPatch::constraintType().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/symmetry/symmetryPointPatch.H
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/symmetry/symmetryPointPatch.C