OpenFOAM: cellMapper Class Reference
cellMapper Class Reference
This object provides mapping and fill-in information for cell data between the two meshes after the topological change. It is constructed from mapPolyMesh.
Public Member Functions
cellMapper (const mapPolyMesh &mpm)
Construct from mapPolyMesh.
virtual ~cellMapper ()
Destructor.
virtual label size () const
Return size.
virtual label sizeBeforeMapping () const
Return size before mapping.
virtual bool direct () const
Is the mapping direct.
virtual bool hasUnmapped () const
Are there unmapped values? I.e. do all size() elements get.
virtual const labelUList & directAddressing () const
Return direct addressing.
virtual const labelListList & addressing () const
Return interpolated addressing.
virtual const scalarListList & weights () const
Return interpolaion weights.
virtual bool insertedObjects () const
Are there any inserted cells.
virtual const labelList & insertedObjectLabels () const
Return list of inserted cells.
Public Member Functions inherited from morphFieldMapper
morphFieldMapper ()
Null constructor.
virtual ~morphFieldMapper ()
Destructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
This object provides mapping and fill-in information for cell data between the two meshes after the topological change. It is constructed from mapPolyMesh.
Source files
cellMapper.H
cellMapper.C
Definition at line 54 of file cellMapper.H.
Constructor & Destructor Documentation
cellMapper()
cellMapper (const mapPolyMesh & mpm)
Construct from mapPolyMesh.
Definition at line 289 of file cellMapper.C.
References mapPolyMesh::cellMap(), mapPolyMesh::cellsFromCellsMap(), mapPolyMesh::cellsFromEdgesMap(), mapPolyMesh::cellsFromFacesMap(), mapPolyMesh::cellsFromPointsMap(), UList< T >::empty(), forAll, Foam::min(), and primitiveMesh::nCells().
~cellMapper()
~cellMapper () virtual
Destructor.
Definition at line 368 of file cellMapper.C.
Member Function Documentation
size()
Foam::label size () const virtual
Return size.
Implements FieldMapper.
Definition at line 376 of file cellMapper.C.
References mapPolyMesh::cellMap(), and List< T >::size().
sizeBeforeMapping()
Foam::label sizeBeforeMapping () const virtual
Return size before mapping.
Implements morphFieldMapper.
Definition at line 382 of file cellMapper.C.
References mapPolyMesh::nOldCells().
direct()
virtual bool direct () const inline virtual
Is the mapping direct.
Implements FieldMapper.
Definition at line 127 of file cellMapper.H.
Referenced by cellMapper::addressing(), cellMapper::directAddressing(), and cellMapper::weights().
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implements FieldMapper.
Definition at line 132 of file cellMapper.H.
References cellMapper::addressing(), cellMapper::directAddressing(), cellMapper::insertedObjects(), and cellMapper::weights().
directAddressing()
const Foam::labelUList & directAddressing () const virtual
Return direct addressing.
Reimplemented from FieldMapper.
Definition at line 388 of file cellMapper.C.
References Foam::abort(), mapPolyMesh::cellMap(), cellMapper::direct(), Foam::FatalError, FatalErrorInFunction, and cellMapper::insertedObjects().
Referenced by cellMapper::hasUnmapped().
addressing()
const Foam::labelListList & addressing () const virtual
Return interpolated addressing.
Reimplemented from FieldMapper.
Definition at line 414 of file cellMapper.C.
References Foam::abort(), cellMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by cellMapper::hasUnmapped().
weights()
const Foam::scalarListList & weights () const virtual
Return interpolaion weights.
Reimplemented from FieldMapper.
Definition at line 432 of file cellMapper.C.
References Foam::abort(), cellMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by cellMapper::hasUnmapped().
insertedObjects()
virtual bool insertedObjects () const inline virtual
Are there any inserted cells.
Implements morphFieldMapper.
Definition at line 147 of file cellMapper.H.
References cellMapper::insertedObjectLabels().
Referenced by cellMapper::directAddressing(), cellMapper::hasUnmapped(), and cellMapper::insertedObjectLabels().
insertedObjectLabels()
const Foam::labelList & insertedObjectLabels () const virtual
Return list of inserted cells.
Implements morphFieldMapper.
Definition at line 450 of file cellMapper.C.
References cellMapper::insertedObjects().
Referenced by cellMapper::insertedObjects().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/cellMapper/cellMapper.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/cellMapper/cellMapper.C