OpenFOAM: pointMapper Class Reference
pointMapper Class Reference
This object provides mapping and fill-in information for point data between the two meshes after the topological change. It is constructed from mapPolyMesh.
Public Member Functions
pointMapper (const pointMesh &, const mapPolyMesh &mpm)
Construct from mapPolyMesh.
virtual ~pointMapper ()
Destructor.
virtual label size () const
Return size.
virtual label sizeBeforeMapping () const
Return size before mapping.
virtual bool direct () const
Is the mapping direct.
virtual bool hasUnmapped () const
Are there unmapped values? I.e. do all size() elements get.
virtual const labelUList & directAddressing () const
Return direct addressing.
virtual const labelListList & addressing () const
Return interpolated addressing.
virtual const scalarListList & weights () const
Return interpolaion weights.
bool insertedObjects () const
Are there any inserted points.
const labelList & insertedObjectLabels () const
Return list of inserted points.
Public Member Functions inherited from morphFieldMapper
morphFieldMapper ()
Null constructor.
virtual ~morphFieldMapper ()
Destructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
This object provides mapping and fill-in information for point data between the two meshes after the topological change. It is constructed from mapPolyMesh.
Source files
pointMapper.H
pointMapper.C
Definition at line 55 of file pointMapper.H.
Constructor & Destructor Documentation
pointMapper()
pointMapper (const pointMesh & pMesh, const mapPolyMesh & mpm)
Construct from mapPolyMesh.
Definition at line 161 of file pointMapper.C.
References UList< T >::empty(), forAll, Foam::min(), mapPolyMesh::pointMap(), mapPolyMesh::pointsFromPointsMap(), and pointMesh::size().
~pointMapper()
~pointMapper () virtual
Destructor.
Definition at line 212 of file pointMapper.C.
Member Function Documentation
size()
Foam::label size () const virtual
Return size.
Implements FieldMapper.
Definition at line 220 of file pointMapper.C.
References mapPolyMesh::pointMap(), and List< T >::size().
sizeBeforeMapping()
Foam::label sizeBeforeMapping () const virtual
Return size before mapping.
Implements morphFieldMapper.
Definition at line 226 of file pointMapper.C.
References mapPolyMesh::nOldPoints().
direct()
virtual bool direct () const inline virtual
Is the mapping direct.
Implements FieldMapper.
Definition at line 126 of file pointMapper.H.
References pointMapper::addressing(), pointMapper::directAddressing(), pointMapper::hasUnmapped(), pointMapper::insertedObjects(), and pointMapper::weights().
Referenced by pointMapper::addressing(), pointMapper::directAddressing(), and pointMapper::weights().
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implements FieldMapper.
Definition at line 133 of file pointMapper.H.
Referenced by pointMapper::direct().
directAddressing()
const Foam::labelUList & directAddressing () const virtual
Return direct addressing.
Reimplemented from FieldMapper.
Definition at line 232 of file pointMapper.C.
References Foam::abort(), pointMapper::direct(), Foam::FatalError, FatalErrorInFunction, pointMapper::insertedObjects(), and mapPolyMesh::pointMap().
Referenced by pointMapper::direct().
addressing()
const Foam::labelListList & addressing () const virtual
Return interpolated addressing.
Reimplemented from FieldMapper.
Definition at line 258 of file pointMapper.C.
References Foam::abort(), pointMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by pointMapper::direct().
weights()
const Foam::scalarListList & weights () const virtual
Return interpolaion weights.
Reimplemented from FieldMapper.
Definition at line 276 of file pointMapper.C.
References Foam::abort(), pointMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by pointMapper::direct().
insertedObjects()
bool insertedObjects () const inline virtual
Are there any inserted points.
Implements morphFieldMapper.
Definition at line 148 of file pointMapper.H.
References pointMapper::insertedObjectLabels().
Referenced by pointMapper::direct(), pointMapper::directAddressing(), and pointMapper::insertedObjectLabels().
insertedObjectLabels()
const Foam::labelList & insertedObjectLabels () const virtual
Return list of inserted points.
Implements morphFieldMapper.
Definition at line 294 of file pointMapper.C.
References pointMapper::insertedObjects().
Referenced by pointMapper::insertedObjects().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointMeshMapper/pointMapper.H
src/OpenFOAM/meshes/pointMesh/pointMeshMapper/pointMapper.C