OpenFOAM: globalMeshData Class Reference
globalMeshData Class Reference
Various mesh related information for a parallel run. Upon construction, constructs all info using parallel communication.
Classes
class ListPlusEqOp
Public Member Functions
ClassName ("globalMeshData")
Runtime type information.
globalMeshData (const polyMesh &mesh)
Construct from mesh, derive rest (does parallel communication!)
~globalMeshData ()
Destructor.
void clearOut ()
Remove all demand driven data.
const polyMesh & mesh () const
Return the mesh reference.
bool parallel () const
Does the mesh contain processor patches? (also valid when.
label nTotalPoints () const
Return total number of points in decomposed mesh. Not.
label nTotalFaces () const
Return total number of faces in decomposed mesh. Not.
label nTotalCells () const
Return total number of cells in decomposed mesh.
const labelList & processorPatches () const
Return list of processor patch labels.
const labelList & processorPatchIndices () const
Return list of indices into processorPatches_ for each patch.
const labelList & processorPatchNeighbours () const
Return processorPatchIndices of the neighbours.
label nGlobalPoints () const
Return number of globally shared points.
const labelList & sharedPointLabels () const
Return indices of local points that are globally shared.
const labelList & sharedPointAddr () const
Return addressing into the complete globally shared points.
const labelList & sharedPointGlobalLabels () const
Return shared point global labels. Tries to read.
pointField sharedPoints () const
Collect coordinates of shared points on all processors.
pointField geometricSharedPoints () const
Like sharedPoints but keeps cyclic points separate.
label nGlobalEdges () const
Return number of globally shared edges. Demand-driven.
const labelList & sharedEdgeLabels () const
Return indices of local edges that are globally shared.
const labelList & sharedEdgeAddr () const
Return addressing into the complete globally shared edge.
const indirectPrimitivePatch & coupledPatch () const
Return patch of all coupled faces.
const labelList & coupledPatchMeshEdges () const
Return map from coupledPatch edges to mesh edges.
const Map< label > & coupledPatchMeshEdgeMap () const
Return map from mesh edges to coupledPatch edges.
const globalIndexAndTransform & globalTransforms () const
Global transforms numbering.
const globalIndex & globalPointNumbering () const
Numbering of coupled points is according to coupledPatch.
const labelListList & globalPointSlaves () const
const labelListList & globalPointTransformedSlaves () const
const mapDistribute & globalPointSlavesMap () const
template<class Type , class CombineOp , class TransformOp >
void syncPointData (List< Type > &pointData, const CombineOp &cop, const TransformOp &top) const
Helper to synchronise coupled patch point data.
const globalIndex & globalEdgeNumbering () const
const labelListList & globalEdgeSlaves () const
const labelListList & globalEdgeTransformedSlaves () const
const mapDistribute & globalEdgeSlavesMap () const
const PackedBoolList & globalEdgeOrientation () const
Is my edge same orientation as master edge.
const labelListList & globalCoPointSlaves () const
const mapDistribute & globalCoPointSlavesMap () const
const globalIndex & globalBoundaryFaceNumbering () const
Numbering of boundary faces is face-mesh.nInternalFaces()
const labelListList & globalPointBoundaryFaces () const
const labelListList & globalPointTransformedBoundaryFaces () const
const mapDistribute & globalPointBoundaryFacesMap () const
const labelList & boundaryCells () const
From boundary cell to mesh cell.
const globalIndex & globalBoundaryCellNumbering () const
Numbering of boundary cells is according to boundaryCells()
const labelListList & globalPointBoundaryCells () const
const labelListList & globalPointTransformedBoundaryCells () const
const mapDistribute & globalPointBoundaryCellsMap () const
autoPtr< globalIndex > mergePoints (labelList &pointToGlobal, labelList &uniquePoints) const
Helper for merging (collocated!) mesh point data.
autoPtr< globalIndex > mergePoints (const labelList &meshPoints, const Map< label > &meshPointMap, labelList &pointToGlobal, labelList &uniqueMeshPoints) const
Helper for merging (collocated!) patch point data.
void movePoints (const pointField &newPoints)
Update for moving points.
void updateMesh ()
Change global mesh data given a topological change. Does a.
Public Member Functions inherited from ProcessorTopology< Container, ProcPatch >
ProcessorTopology (const Container &patches, const label comm)
Construct from boundaryMesh.
const labelList & procPatchMap () const
From neighbour processor to index in boundaryMesh. Local information.
const lduSchedule & patchSchedule () const
Order in which the patches should be initialised/evaluated.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
template<class Type , class CombineOp , class TransformOp >
static void syncData (List< Type > &pointData, const labelListList &slaves, const labelListList &transformedSlaves, const mapDistribute &slavesMap, const globalIndexAndTransform &, const CombineOp &cop, const TransformOp &top)
Helper: synchronise data with transforms.
template<class Type , class CombineOp >
static void syncData (List< Type > &pointData, const labelListList &slaves, const labelListList &transformedSlaves, const mapDistribute &slavesMap, const CombineOp &cop)
Helper: synchronise data without transforms.
Static Public Member Functions inherited from ProcessorTopology< Container, ProcPatch >
static lduSchedule nonBlockingSchedule (const Container &patches)
Calculate non-blocking (i.e. unscheduled) schedule.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes
static const Foam::scalar matchTol_ = 1e-8
Geometric tolerance (fraction of bounding box)
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
Various mesh related information for a parallel run. Upon construction, constructs all info using parallel communication.
Requires:
all processor patches to have correct ordering.
all processorPatches to have their transforms set.
The shared point and edge addressing calculates addressing for points and edges on coupled patches. In the 'old' way a distinction was made between points/edges that are only on two processors and those that are on multiple processors. The problem is that those on multiple processors do not allow any transformations and require a global reduction on the master processor.
The alternative is to have an exchange schedule (through a 'mapDistribute') which sends all point/edge data (no distinction is made between those on two and those on more than two coupled patches) to the local 'master'. This master then does any calculation and sends the result back to the 'slave' points/edges. This only needs to be done on points on coupled faces. Any transformation is done using a predetermined set of transformations - since transformations have to be space filling only a certain number of transformation is supported.
The exchange needs
a field of data
a mapDistribute which does all parallel exchange and transformations This appends remote data to the end of the field.
a set of indices which indicate where to get untransformed data in the field
a set of indices which indicate where to get transformed data in the field
Note
compared to 17x nTotalFaces, nTotalPoints do not compensate for shared points since this would trigger full connectivity analysis
most calculation is demand driven and uses parallel communication so make sure to invoke on all processors at the same time
old sharedEdge calculation: currently an edge is considered shared if it uses two shared points and is used more than once. This is not correct on processor patches but it only slightly overestimates the number of shared edges. Doing full analysis of how many patches use the edge would be too complicated
See also
mapDistribute globalIndexAndTransform
Source files
globalMeshData.H
globalMeshData.C
globalMeshDataTemplates.C
Definition at line 105 of file globalMeshData.H.
Constructor & Destructor Documentation
globalMeshData()
globalMeshData (const polyMesh & mesh)
Construct from mesh, derive rest (does parallel communication!)
Definition at line 1763 of file globalMeshData.C.
References globalMeshData::updateMesh().
~globalMeshData()
~globalMeshData ()
Destructor.
Definition at line 1787 of file globalMeshData.C.
References globalMeshData::clearOut().
Member Function Documentation
ClassName()
ClassName ("globalMeshData")
Runtime type information.
Referenced by globalMeshData::ListPlusEqOp< T >::operator()().
clearOut()
void clearOut ()
Remove all demand driven data.
Definition at line 1793 of file globalMeshData.C.
Referenced by globalMeshData::updateMesh(), and globalMeshData::~globalMeshData().
mesh()
const polyMesh& mesh () const inline
Return the mesh reference.
Definition at line 366 of file globalMeshData.H.
References globalMeshData::nTotalFaces(), globalMeshData::nTotalPoints(), globalMeshData::parallel(), and List< T >::size().
parallel()
bool parallel () const inline
Does the mesh contain processor patches? (also valid when.
not running parallel)
Definition at line 373 of file globalMeshData.H.
Referenced by globalMeshData::mesh().
nTotalPoints()
label nTotalPoints () const inline
Return total number of points in decomposed mesh. Not.
compensated for duplicate points!
Definition at line 380 of file globalMeshData.H.
Referenced by meshRefinement::dupNonManifoldPoints(), globalMeshData::mesh(), and medialAxisMeshMover::~medialAxisMeshMover().
nTotalFaces()
label nTotalFaces () const inline
Return total number of faces in decomposed mesh. Not.
compensated for duplicate faces!
Definition at line 387 of file globalMeshData.H.
Referenced by globalMeshData::mesh().
nTotalCells()
label nTotalCells () const inline
Return total number of cells in decomposed mesh.
Definition at line 393 of file globalMeshData.H.
References globalMeshData::boundaryCells(), globalMeshData::coupledPatch(), globalMeshData::coupledPatchMeshEdgeMap(), globalMeshData::coupledPatchMeshEdges(), globalMeshData::geometricSharedPoints(), globalMeshData::globalBoundaryCellNumbering(), globalMeshData::globalBoundaryFaceNumbering(), globalMeshData::globalCoPointSlaves(), globalMeshData::globalCoPointSlavesMap(), globalMeshData::globalEdgeNumbering(), globalMeshData::globalEdgeOrientation(), globalMeshData::globalEdgeSlaves(), globalMeshData::globalEdgeSlavesMap(), globalMeshData::globalEdgeTransformedSlaves(), globalMeshData::globalPointBoundaryCells(), globalMeshData::globalPointBoundaryCellsMap(), globalMeshData::globalPointBoundaryFaces(), globalMeshData::globalPointBoundaryFacesMap(), globalMeshData::globalPointNumbering(), globalMeshData::globalPointSlaves(), globalMeshData::globalPointSlavesMap(), globalMeshData::globalPointTransformedBoundaryCells(), globalMeshData::globalPointTransformedBoundaryFaces(), globalMeshData::globalPointTransformedSlaves(), globalMeshData::globalTransforms(), globalMeshData::mergePoints(), globalMeshData::movePoints(), globalMeshData::nGlobalEdges(), globalMeshData::nGlobalPoints(), globalMeshData::processorPatches(), globalMeshData::processorPatchIndices(), globalMeshData::processorPatchNeighbours(), globalMeshData::sharedEdgeAddr(), globalMeshData::sharedEdgeLabels(), globalMeshData::sharedPointAddr(), globalMeshData::sharedPointGlobalLabels(), globalMeshData::sharedPointLabels(), globalMeshData::sharedPoints(), globalMeshData::syncData(), globalMeshData::syncPointData(), and globalMeshData::updateMesh().
Referenced by structuredDecomp::decompose(), decompositionMethod::decompose(), NamedEnum< directionType, 3 >::names(), meshRefinement::printMeshInfo(), zoltanRenumber::renumber(), structuredRenumber::renumber(), Foam::fvc::smooth(), and snappyRefineDriver::snappyRefineDriver().
processorPatches()
const labelList& processorPatches () const inline
Return list of processor patch labels.
(size of list = number of processor patches)
Definition at line 403 of file globalMeshData.H.
Referenced by FaceCellWave< Type, TrackingData >::handleProcPatches(), Cloud< streamLineParticle >::move(), and globalMeshData::nTotalCells().
processorPatchIndices()
const labelList& processorPatchIndices () const inline
Return list of indices into processorPatches_ for each patch.
Index = -1 for non-processor parches. (size of list = number of patches)
Definition at line 411 of file globalMeshData.H.
Referenced by Cloud< streamLineParticle >::move(), and globalMeshData::nTotalCells().
processorPatchNeighbours()
const labelList& processorPatchNeighbours () const inline
Return processorPatchIndices of the neighbours.
processor patches. -1 if not running parallel.
Definition at line 418 of file globalMeshData.H.
Referenced by Cloud< streamLineParticle >::move(), and globalMeshData::nTotalCells().
nGlobalPoints()
Foam::label nGlobalPoints () const
Return number of globally shared points.
Definition at line 2005 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells(), globalMeshData::sharedPoints(), and syncTools::syncPointMap().
sharedPointLabels()
const Foam::labelList & sharedPointLabels () const
Return indices of local points that are globally shared.
Definition at line 2015 of file globalMeshData.C.
Referenced by polyMeshAdder::findSharedPoints(), globalMeshData::geometricSharedPoints(), globalMeshData::nTotalCells(), globalMeshData::sharedPointGlobalLabels(), globalMeshData::sharedPoints(), syncTools::syncEdgeMap(), and syncTools::syncPointMap().
sharedPointAddr()
const Foam::labelList & sharedPointAddr () const
Return addressing into the complete globally shared points.
list Note: It is assumed that a (never constructed) complete list of globally shared points exists. The set of shared points on the current processor is a subset of all shared points. Shared point addressing gives the index in the list of all globally shared points for each of the locally shared points.
Definition at line 2025 of file globalMeshData.C.
Referenced by polyMeshAdder::findSharedPoints(), globalMeshData::nTotalCells(), globalMeshData::sharedPoints(), syncTools::syncEdgeMap(), and syncTools::syncPointMap().
sharedPointGlobalLabels()
const Foam::labelList & sharedPointGlobalLabels () const
Return shared point global labels. Tries to read.
'pointProcAddressing' and returns list or -1 if none available.
Definition at line 1845 of file globalMeshData.C.
References Foam::endl(), polyMesh::facesInstance(), forAll, polyMesh::meshSubDir, IOobject::MUST_READ, pointLabels(), Foam::Pout, globalMeshData::sharedPointLabels(), and List< T >::size().
Referenced by globalMeshData::nTotalCells().
sharedPoints()
Foam::pointField sharedPoints () const
Collect coordinates of shared points on all processors.
(does parallel communication!) Note: not valid for cyclicParallel since shared cyclic points are merged into single global point. (use geometricSharedPoints instead)
Definition at line 1895 of file globalMeshData.C.
References UPstream::blocking, UPstream::firstSlave(), forAll, UPstream::lastSlave(), UPstream::master(), UPstream::masterNo(), globalMeshData::nGlobalPoints(), pointLabels(), polyMesh::points(), globalMeshData::sharedPointAddr(), globalMeshData::sharedPointLabels(), List< T >::size(), and Foam::Zero.
Referenced by globalMeshData::geometricSharedPoints(), and globalMeshData::nTotalCells().
geometricSharedPoints()
Foam::pointField geometricSharedPoints () const
Like sharedPoints but keeps cyclic points separate.
(does geometric merging; uses matchTol_*bb as merging tolerance) Use sharedPoints() instead.
Definition at line 1977 of file globalMeshData.C.
References polyMesh::bounds(), Foam::combineReduce(), boundBox::mag(), globalMeshData::matchTol_, Foam::mergePoints(), polyMesh::points(), globalMeshData::sharedPointLabels(), and globalMeshData::sharedPoints().
Referenced by globalMeshData::nTotalCells().
nGlobalEdges()
Foam::label nGlobalEdges () const
Return number of globally shared edges. Demand-driven.
calculation so call needs to be synchronous among processors!
Definition at line 2035 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
sharedEdgeLabels()
const Foam::labelList & sharedEdgeLabels () const
Return indices of local edges that are globally shared.
Demand-driven calculation so call needs to be synchronous among processors!
Definition at line 2045 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
sharedEdgeAddr()
const Foam::labelList & sharedEdgeAddr () const
Return addressing into the complete globally shared edge.
list. The set of shared edges on the current processor is a subset of all shared edges. Shared edge addressing gives the index in the list of all globally shared edges for each of the locally shared edges. Demand-driven calculation so call needs to be synchronous among processors!
Definition at line 2055 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
coupledPatch()
const Foam::indirectPrimitivePatch & coupledPatch () const
Return patch of all coupled faces.
Definition at line 2065 of file globalMeshData.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), Foam::endl(), polyMesh::faces(), forAll, patchi, polyMesh::points(), Foam::Pout, and polyPatch::start().
Referenced by createShellMesh::calcPointRegions(), PointEdgeWave< Type, TrackingData >::countPatchType(), globalMeshData::coupledPatchMeshEdges(), globalMeshData::globalEdgeNumbering(), globalIndexAndTransform::globalIndexAndTransform(), globalMeshData::globalPointNumbering(), globalMeshData::mergePoints(), globalMeshData::nTotalCells(), PatchTools::pointNormals(), motionSmootherAlgo::setDisplacementPatchFields(), syncTools::syncEdgeList(), syncTools::syncPointList(), and pointConstraints::syncUntransformedData().
coupledPatchMeshEdges()
const Foam::labelList & coupledPatchMeshEdges () const
Return map from coupledPatch edges to mesh edges.
Definition at line 2126 of file globalMeshData.C.
References globalMeshData::coupledPatch(), primitiveMesh::edges(), and primitiveMesh::pointEdges().
Referenced by globalMeshData::coupledPatchMeshEdgeMap(), globalMeshData::nTotalCells(), and syncTools::syncEdgeList().
coupledPatchMeshEdgeMap()
const Foam::Map< Foam::label > & coupledPatchMeshEdgeMap () const
Return map from mesh edges to coupledPatch edges.
Definition at line 2146 of file globalMeshData.C.
References globalMeshData::coupledPatchMeshEdges(), forAll, HashTable< T, Key, Hash >::insert(), Foam::constant::atomic::me, and List< T >::size().
Referenced by globalMeshData::nTotalCells(), and syncTools::syncEdgeList().
globalTransforms()
const Foam::globalIndexAndTransform & globalTransforms () const
Global transforms numbering.
Definition at line 2179 of file globalMeshData.C.
Referenced by PatchTools::edgeNormals(), globalMeshData::nTotalCells(), PatchTools::pointNormals(), syncTools::syncEdgeList(), and syncTools::syncPointList().
syncData() [1/2]
void syncData (List< Type > & pointData, const labelListList & slaves, const labelListList & transformedSlaves, const mapDistribute & slavesMap, const globalIndexAndTransform & transforms, const CombineOp & cop, const TransformOp & top) static
Helper: synchronise data with transforms.
Definition at line 34 of file globalMeshDataTemplates.C.
References mapDistribute::distribute(), forAll, mapDistribute::reverseDistribute(), and List< T >::size().
Referenced by PatchTools::edgeNormals(), globalMeshData::mergePoints(), globalMeshData::nTotalCells(), minEqOp< labelPair >::operator()(), syncTools::syncEdgeList(), and syncTools::syncPointList().
syncData() [2/2]
void syncData (List< Type > & pointData, const labelListList & slaves, const labelListList & transformedSlaves, const mapDistribute & slavesMap, const CombineOp & cop) static
Helper: synchronise data without transforms.
Definition at line 107 of file globalMeshDataTemplates.C.
References mapDistribute::distribute(), forAll, mapDistribute::reverseDistribute(), List< T >::size(), and globalMeshData::syncPointData().
globalPointNumbering()
const Foam::globalIndex & globalPointNumbering () const
Numbering of coupled points is according to coupledPatch.
Definition at line 2165 of file globalMeshData.C.
References globalMeshData::coupledPatch(), and nPoints.
Referenced by globalMeshData::mergePoints(), and globalMeshData::nTotalCells().
globalPointSlaves()
const Foam::labelListList & globalPointSlaves () const
Definition at line 2189 of file globalMeshData.C.
Referenced by PointEdgeWave< Type, TrackingData >::countPatchType(), globalMeshData::nTotalCells(), PatchTools::pointNormals(), and syncTools::syncPointList().
globalPointTransformedSlaves()
const Foam::labelListList & globalPointTransformedSlaves () const
Definition at line 2199 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells(), PatchTools::pointNormals(), and syncTools::syncPointList().
globalPointSlavesMap()
const Foam::mapDistribute & globalPointSlavesMap () const
Definition at line 2210 of file globalMeshData.C.
Referenced by PointEdgeWave< Type, TrackingData >::countPatchType(), globalMeshData::nTotalCells(), PatchTools::pointNormals(), and syncTools::syncPointList().
syncPointData()
void syncPointData (List< Type > & pointData, const CombineOp & cop, const TransformOp & top) const
Helper to synchronise coupled patch point data.
Definition at line 172 of file globalMeshDataTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), and List< T >::size().
Referenced by globalMeshData::nTotalCells(), globalMeshData::syncData(), and syncTools::syncPointList().
globalEdgeNumbering()
const Foam::globalIndex & globalEdgeNumbering () const
Definition at line 2220 of file globalMeshData.C.
References globalMeshData::coupledPatch().
Referenced by globalMeshData::nTotalCells().
globalEdgeSlaves()
const Foam::labelListList & globalEdgeSlaves () const
Definition at line 2233 of file globalMeshData.C.
Referenced by PatchTools::edgeNormals(), globalMeshData::nTotalCells(), minEqOp< labelPair >::operator()(), and syncTools::syncEdgeList().
globalEdgeTransformedSlaves()
const Foam::labelListList & globalEdgeTransformedSlaves () const
Definition at line 2243 of file globalMeshData.C.
Referenced by PatchTools::edgeNormals(), globalMeshData::nTotalCells(), minEqOp< labelPair >::operator()(), and syncTools::syncEdgeList().
globalEdgeSlavesMap()
const Foam::mapDistribute & globalEdgeSlavesMap () const
Definition at line 2264 of file globalMeshData.C.
Referenced by PatchTools::edgeNormals(), globalMeshData::nTotalCells(), minEqOp< labelPair >::operator()(), and syncTools::syncEdgeList().
globalEdgeOrientation()
const Foam::PackedBoolList & globalEdgeOrientation () const
Is my edge same orientation as master edge.
Definition at line 2254 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells(), and minEqOp< labelPair >::operator()().
globalCoPointSlaves()
const Foam::labelListList & globalCoPointSlaves () const
Definition at line 2372 of file globalMeshData.C.
Referenced by globalIndexAndTransform::globalIndexAndTransform(), globalMeshData::mergePoints(), globalMeshData::nTotalCells(), and pointConstraints::syncUntransformedData().
globalCoPointSlavesMap()
const Foam::mapDistribute & globalCoPointSlavesMap () const
Definition at line 2382 of file globalMeshData.C.
References globalMeshData::mergePoints().
Referenced by globalIndexAndTransform::globalIndexAndTransform(), globalMeshData::mergePoints(), globalMeshData::nTotalCells(), and pointConstraints::syncUntransformedData().
globalBoundaryFaceNumbering()
const Foam::globalIndex & globalBoundaryFaceNumbering () const
Numbering of boundary faces is face-mesh.nInternalFaces()
Definition at line 2274 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
globalPointBoundaryFaces()
const Foam::labelListList & globalPointBoundaryFaces () const
Definition at line 2285 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
globalPointTransformedBoundaryFaces()
const Foam::labelListList & globalPointTransformedBoundaryFaces () const
Definition at line 2297 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
globalPointBoundaryFacesMap()
const Foam::mapDistribute & globalPointBoundaryFacesMap () const
Definition at line 2307 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
boundaryCells()
const Foam::labelList & boundaryCells () const
From boundary cell to mesh cell.
Definition at line 2318 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
globalBoundaryCellNumbering()
const Foam::globalIndex & globalBoundaryCellNumbering () const
Numbering of boundary cells is according to boundaryCells()
Definition at line 2328 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
globalPointBoundaryCells()
const Foam::labelListList & globalPointBoundaryCells () const
Definition at line 2339 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
globalPointTransformedBoundaryCells()
const Foam::labelListList & globalPointTransformedBoundaryCells () const
Definition at line 2351 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
globalPointBoundaryCellsMap()
const Foam::mapDistribute & globalPointBoundaryCellsMap () const
Definition at line 2361 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
mergePoints() [1/2]
Foam::autoPtr< Foam::globalIndex > mergePoints (labelList & pointToGlobal, labelList & uniquePoints) const
Helper for merging (collocated!) mesh point data.
Determines:
my unique indices
global numbering over all unique indices
the global number for all local points (so this will be local for my unique points)
Definition at line 2393 of file globalMeshData.C.
References mapDistributeBase::constructSize(), globalMeshData::coupledPatch(), forAll, globalMeshData::globalCoPointSlaves(), globalMeshData::globalCoPointSlavesMap(), globalMeshData::globalPointNumbering(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), primitiveMesh::nPoints(), mapDistribute::reverseDistribute(), List< T >::setSize(), List< T >::size(), globalMeshData::syncData(), and globalIndex::toGlobal().
Referenced by PatchTools::gatherAndMerge(), globalMeshData::globalCoPointSlavesMap(), globalMeshData::nTotalCells(), and FacePostProcessing< CloudType >::write().
mergePoints() [2/2]
Foam::autoPtr< Foam::globalIndex > mergePoints (const labelList & meshPoints, const Map< label > & meshPointMap, labelList & pointToGlobal, labelList & uniqueMeshPoints) const
Helper for merging (collocated!) patch point data.
Takes maps from: local points to/from mesh. Determines
my unique points. These are mesh point indices, not patch point indices.
global numbering over all unique indices.
the global number for all local points.
Definition at line 2527 of file globalMeshData.C.
References mapDistributeBase::constructSize(), globalMeshData::coupledPatch(), mapDistribute::distribute(), HashTableCore::end(), HashTable< T, Key, Hash >::find(), forAll, globalMeshData::globalCoPointSlaves(), globalMeshData::globalCoPointSlavesMap(), Foam::labelMax, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPointMap(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), mapDistribute::reverseDistribute(), List< T >::setSize(), List< T >::size(), and globalMeshData::syncData().
movePoints()
void movePoints (const pointField & newPoints)
Update for moving points.
Definition at line 2741 of file globalMeshData.C.
Referenced by globalMeshData::nTotalCells().
updateMesh()
void updateMesh ()
Change global mesh data given a topological change. Does a.
full parallel analysis to determine shared points and boundaries.
Definition at line 2750 of file globalMeshData.C.
References UPstream::allocateCommunicator(), polyMesh::bounds(), globalMeshData::clearOut(), Foam::endl(), UPstream::freeCommunicator(), Foam::identity(), boundBox::mag(), globalMeshData::matchTol_, UPstream::msgType(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nPoints(), UPstream::nProcs(), Foam::Pout, Foam::returnReduce(), and UPstream::worldComm.
Referenced by globalMeshData::globalMeshData(), and globalMeshData::nTotalCells().
Member Data Documentation
matchTol_
const scalar matchTol_ = 1e-8 static
Geometric tolerance (fraction of bounding box)
Definition at line 345 of file globalMeshData.H.
Referenced by globalMeshData::geometricSharedPoints(), and globalMeshData::updateMesh().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalMeshData.H
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalMeshData.C
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalMeshDataTemplates.C