OpenFOAM: globalIndex Class Reference
globalIndex Class Reference
Calculates a unique integer (label so might not have enough room - 2G max) for processor + local index. E.g.
Public Member Functions
globalIndex ()
Construct null.
globalIndex (const label localSize)
Construct from local max size. Does communication with default.
globalIndex (const label localSize, const int tag, const label comm, const bool parallel)
Construct from local max size. Does communication with given.
globalIndex (const labelList &offsets)
Construct from components.
globalIndex (const Xfer< labelList > &offsets)
Construct from components.
globalIndex (Istream &is)
Construct from Istream.
labelList & offsets ()
Change after construction.
label localSize () const
My local size.
label toGlobal (const label i) const
From local to global.
bool isLocal (const label i) const
Is on local processor.
label toLocal (const label i) const
From global to local on current processor.
label size () const
Global sum of localSizes.
label localSize (const label proci) const
Size of proci data.
label toGlobal (const label proci, const label i) const
From local to global on proci.
bool isLocal (const label proci, const label i) const
Is on processor proci.
label toLocal (const label proci, const label i) const
From global to local on proci.
label whichProcID (const label i) const
Which processor does global come from? Binary search.
label offset (const label proci) const
Start of proci data.
template<class Type >
void gather (const label comm, const labelList &procIDs, const UList< Type > &fld, List< Type > &allFld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::nonBlocking) const
Collect data in processor order on master (== procIDs[0]).
template<class Type >
void gather (const label comm, const labelList &procIDs, List< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::nonBlocking) const
Inplace collect data in processor order on master.
template<class Type >
void scatter (const label comm, const labelList &procIDs, const UList< Type > &allFld, UList< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::nonBlocking) const
Distribute data in processor order. Requires fld to be sized!
Static Public Member Functions
template<class Type >
static void gather (const labelUList &offsets, const label comm, const labelList &procIDs, const UList< Type > &fld, List< Type > &allFld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::nonBlocking)
Collect data in processor order on master (== procIDs[0]).
template<class Type >
static void gather (const labelUList &offsets, const label comm, const labelList &procIDs, List< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::nonBlocking)
Inplace collect data in processor order on master.
template<class Type >
static void scatter (const labelUList &offsets, const label comm, const labelList &procIDs, const UList< Type > &allFld, UList< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::nonBlocking)
Distribute data in processor order. Requires fld to be sized!
Friends
Istream & operator>> (Istream &is, globalIndex &gi)
Ostream & operator<< (Ostream &os, const globalIndex &gi)
Detailed Description
Calculates a unique integer (label so might not have enough room - 2G max) for processor + local index. E.g.
globalIndex globalFaces(mesh.nFaces()); label globalFacei = globalFaces.toGlobal(facei);
Source files
globalIndex.H
globalIndexI.H
globalIndex.C
globalIndexTemplates.C
Definition at line 63 of file globalIndex.H.
Constructor & Destructor Documentation
globalIndex() [1/6]
globalIndex () inline
Construct null.
Definition at line 30 of file globalIndexI.H.
globalIndex() [2/6]
globalIndex (const label localSize)
Construct from local max size. Does communication with default.
communicator and message tag.
Definition at line 68 of file globalIndex.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Pstream::gatherList(), Foam::labelMax, globalIndex::localSize(), UPstream::msgType(), UPstream::myProcNo(), UPstream::nProcs(), globalIndex::offset(), and Pstream::scatterList().
globalIndex() [3/6]
globalIndex (const label localSize, const int tag, const label comm, const bool parallel)
Construct from local max size. Does communication with given.
communicator and message tag
Definition at line 31 of file globalIndex.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::labelMax.
globalIndex() [4/6]
globalIndex (const labelList & offsets)
Construct from components.
Definition at line 97 of file globalIndex.C.
globalIndex() [5/6]
globalIndex (const Xfer< labelList > & offsets) inline
Construct from components.
Definition at line 34 of file globalIndexI.H.
globalIndex() [6/6]
globalIndex (Istream & is)
Construct from Istream.
Definition at line 103 of file globalIndex.C.
Member Function Documentation
offsets()
Foam::labelList & offsets () inline
Change after construction.
Definition at line 42 of file globalIndexI.H.
localSize() [1/2]
Foam::label localSize () const inline
My local size.
Definition at line 60 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by createShellMesh::calcPointRegions(), mapDistributeBase::exchangeAddressing(), globalIndex::globalIndex(), regionSplit::nLocalRegions(), minEqOp< labelPair >::operator()(), and SprayCloud< Foam::DSMCCloud >::penetration().
toGlobal() [1/2]
Foam::label toGlobal (const label i) const inline
From local to global.
Definition at line 82 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by nearWallFields::calcAddressing(), decompositionMethod::calcCellCells(), createShellMesh::calcPointRegions(), viewFactor::calculate(), edgeCollapser::checkMeshQuality(), distributedTriSurfaceMesh::findNearest(), addPatchCellLayer::globalEdgeFaces(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), globalMeshData::mergePoints(), MGridGenGAMGAgglomeration::MGridGenGAMGAgglomeration(), NamedEnum< directionType, 3 >::names(), minEqOp< labelPair >::operator()(), viewFactor::read(), addPatchCellLayer::setRefinement(), and globalIndex::size().
isLocal() [1/2]
bool isLocal (const label i) const inline
Is on local processor.
Definition at line 95 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by decompositionMethod::calcCellCells(), mapDistributeBase::calcCompactAddressing(), addPatchCellLayer::calcSidePatch(), and mapDistributeBase::renumber().
toLocal() [1/2]
Foam::label toLocal (const label i) const inline
From global to local on current processor.
FatalError if not on local processor.
Definition at line 117 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by decompositionMethod::calcCellCells(), mapDistributeBase::calcCompactAddressing(), NamedEnum< directionType, 3 >::names(), minEqOp< labelPair >::operator()(), and mapDistributeBase::renumber().
size()
Foam::label size () const inline
Global sum of localSizes.
Definition at line 66 of file globalIndexI.H.
References UList< T >::last(), and globalIndex::toGlobal().
Referenced by nearWallFields::calcAddressing(), distributedTriSurfaceMesh::globalSize(), regionSplit::nRegions(), minEqOp< labelPair >::operator()(), SprayCloud< Foam::DSMCCloud >::penetration(), and globalIndex::whichProcID().
localSize() [2/2]
Foam::label localSize (const label proci) const inline
Size of proci data.
Definition at line 54 of file globalIndexI.H.
toGlobal() [2/2]
Foam::label toGlobal (const label proci, const label i) const inline
From local to global on proci.
Definition at line 73 of file globalIndexI.H.
isLocal() [2/2]
bool isLocal (const label proci, const label i) const inline
Is on processor proci.
Is on local processor.
Definition at line 89 of file globalIndexI.H.
toLocal() [2/2]
Foam::label toLocal (const label proci, const label i) const inline
From global to local on proci.
Definition at line 101 of file globalIndexI.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
whichProcID()
Foam::label whichProcID (const label i) const inline
Which processor does global come from? Binary search.
Definition at line 123 of file globalIndexI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::findLower(), and globalIndex::size().
Referenced by mapDistributeBase::calcCompactAddressing(), addPatchCellLayer::calcSidePatch(), NamedEnum< directionType, 3 >::names(), minEqOp< labelPair >::operator()(), and mapDistributeBase::renumber().
offset()
Foam::label offset (const label proci) const inline
Start of proci data.
Definition at line 48 of file globalIndexI.H.
Referenced by globalIndex::globalIndex(), and SprayCloud< Foam::DSMCCloud >::penetration().
gather() [1/4]
void gather (const labelUList & offsets, const label comm, const labelList & procIDs, const UList< Type > & fld, List< Type > & allFld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::nonBlocking) static
Collect data in processor order on master (== procIDs[0]).
Needs offsets only on master.
Definition at line 32 of file globalIndexTemplates.C.
References UList< T >::begin(), UList< T >::byteSize(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), UList< T >::last(), Foam::read(), List< T >::setSize(), List< T >::size(), UList< T >::size(), and write().
Referenced by globalIndex::gather(), and GAMGAgglomeration::procAgglomerateRestrictAddressing().
gather() [2/4]
void gather (const label comm, const labelList & procIDs, const UList< Type > & fld, List< Type > & allFld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::nonBlocking) const inline
Collect data in processor order on master (== procIDs[0]).
Needs offsets only on master.
Definition at line 170 of file globalIndex.H.
References globalIndex::gather(), UPstream::msgType(), and UPstream::nonBlocking.
gather() [3/4]
void gather (const labelUList & offsets, const label comm, const labelList & procIDs, List< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::nonBlocking) static
Inplace collect data in processor order on master.
(== procIDs[0]). Needs offsets only on master.
Definition at line 176 of file globalIndexTemplates.C.
References globalIndex::scatter(), and List< T >::transfer().
gather() [4/4]
void gather (const label comm, const labelList & procIDs, List< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::nonBlocking) const inline
Inplace collect data in processor order on master.
(== procIDs[0]). Needs offsets only on master.
Definition at line 199 of file globalIndex.H.
References globalIndex::gather(), UPstream::msgType(), UPstream::nonBlocking, and globalIndex::scatter().
scatter() [1/2]
void scatter (const labelUList & offsets, const label comm, const labelList & procIDs, const UList< Type > & allFld, UList< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::nonBlocking) static
Distribute data in processor order. Requires fld to be sized!
Definition at line 198 of file globalIndexTemplates.C.
References UList< T >::begin(), UList< T >::byteSize(), UList< T >::deepCopy(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld(), Foam::read(), List< T >::size(), and write().
Referenced by globalIndex::gather(), and globalIndex::scatter().
scatter() [2/2]
void scatter (const label comm, const labelList & procIDs, const UList< Type > & allFld, UList< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::nonBlocking) const inline
Distribute data in processor order. Requires fld to be sized!
Definition at line 226 of file globalIndex.H.
References globalIndex::operator<<, globalIndex::operator>>, and globalIndex::scatter().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & is, globalIndex & gi) friend
Referenced by globalIndex::scatter().
operator<<
Ostream& operator<< (Ostream & os, const globalIndex & gi) friend
Referenced by globalIndex::scatter().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalIndex.H
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalIndex.C
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalIndexI.H
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalIndexTemplates.C