OpenFOAM: mapDistributePolyMesh Class Reference
mapDistributePolyMesh Class Reference
Class containing mesh-to-mesh mapping information after a mesh distribution where we send parts of meshes (using subsetting) to other processors and receive and reconstruct mesh.
Public Member Functions
mapDistributePolyMesh ()
Construct null.
mapDistributePolyMesh (const polyMesh &mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, const Xfer< labelList > &oldPatchStarts, const Xfer< labelList > &oldPatchNMeshPoints, const Xfer< labelListList > &subPointMap, const Xfer< labelListList > &subFaceMap, const Xfer< labelListList > &subCellMap, const Xfer< labelListList > &subPatchMap, const Xfer< labelListList > &constructPointMap, const Xfer< labelListList > &constructFaceMap, const Xfer< labelListList > &constructCellMap, const Xfer< labelListList > &constructPatchMap, const bool subFaceHasFlip=false, const bool constructFaceHasFlip=false)
Construct from components. Note that mesh has to be changed already.
mapDistributePolyMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, const Xfer< labelList > &oldPatchStarts, const Xfer< labelList > &oldPatchNMeshPoints, const Xfer< mapDistribute > &pointMap, const Xfer< mapDistribute > &faceMap, const Xfer< mapDistribute > &cellMap, const Xfer< mapDistribute > &patchMap)
Construct from components.
mapDistributePolyMesh (const Xfer< mapDistributePolyMesh > &)
Construct by transferring parameter content.
mapDistributePolyMesh (Istream &)
Construct from Istream.
label nOldPoints () const
Number of points in mesh before distribution.
label nOldFaces () const
Number of faces in mesh before distribution.
label nOldCells () const
Number of cells in mesh before distribution.
const labelList & oldPatchSizes () const
List of the old patch sizes.
const labelList & oldPatchStarts () const
List of the old patch start labels.
const labelList & oldPatchNMeshPoints () const
List of numbers of mesh points per old patch.
const mapDistribute & pointMap () const
Point distribute map.
const mapDistribute & faceMap () const
Face distribute map.
const mapDistribute & cellMap () const
Cell distribute map.
const mapDistribute & patchMap () const
Patch distribute map.
void transfer (mapDistributePolyMesh &)
Transfer the contents of the argument and annul the argument.
Xfer< mapDistributePolyMesh > xfer ()
Transfer contents to the Xfer container.
template<class T >
void distributePointData (List< T > &lst) const
Distribute list of point data.
template<class T >
void distributeFaceData (List< T > &lst) const
Distribute list of face data.
template<class T >
void distributeCellData (List< T > &lst) const
Distribute list of cell data.
template<class T >
void distributePatchData (List< T > &lst) const
Distribute list of patch data.
void distributePointIndices (labelList &pointIDs) const
Distribute list of point/face/cell/patch indices.
void distributeFaceIndices (labelList &faceIDs) const
void distributeCellIndices (labelList &cellIDs) const
void distributePatchIndices (labelList &patchIDs) const
void updateMesh (const mapPolyMesh &)
Correct for topo change.
void operator= (const mapDistributePolyMesh &)
Friends
Istream & operator>> (Istream &, mapDistributePolyMesh &)
Read dictionary from Istream.
Ostream & operator<< (Ostream &, const mapDistributePolyMesh &)
Write dictionary to Ostream.
Detailed Description
Class containing mesh-to-mesh mapping information after a mesh distribution where we send parts of meshes (using subsetting) to other processors and receive and reconstruct mesh.
We store mapping from the bits-to-send to the complete starting mesh (subXXXMap) and from the received bits to their location in the new mesh (constructXXXMap).
Source files
mapDistributePolyMesh.H
mapDistributePolyMesh.C
Definition at line 66 of file mapDistributePolyMesh.H.
Constructor & Destructor Documentation
mapDistributePolyMesh() [1/5]
mapDistributePolyMesh ()
Construct null.
Definition at line 62 of file mapDistributePolyMesh.C.
Referenced by mapDistributePolyMesh::mapDistributePolyMesh().
mapDistributePolyMesh() [2/5]
mapDistributePolyMesh (const polyMesh & mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, const Xfer< labelList > & oldPatchStarts, const Xfer< labelList > & oldPatchNMeshPoints, const Xfer< labelListList > & subPointMap, const Xfer< labelListList > & subFaceMap, const Xfer< labelListList > & subCellMap, const Xfer< labelListList > & subPatchMap, const Xfer< labelListList > & constructPointMap, const Xfer< labelListList > & constructFaceMap, const Xfer< labelListList > & constructCellMap, const Xfer< labelListList > & constructPatchMap, const bool subFaceHasFlip = false, const bool constructFaceHasFlip = false)
Construct from components. Note that mesh has to be changed already.
since uses mesh.nPoints etc as the new size.
Definition at line 78 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::mapDistributePolyMesh().
mapDistributePolyMesh() [3/5]
mapDistributePolyMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, const Xfer< labelList > & oldPatchStarts, const Xfer< labelList > & oldPatchNMeshPoints, const Xfer< mapDistribute > & pointMap, const Xfer< mapDistribute > & faceMap, const Xfer< mapDistribute > & cellMap, const Xfer< mapDistribute > & patchMap)
Construct from components.
Definition at line 127 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::mapDistributePolyMesh().
mapDistributePolyMesh() [4/5]
mapDistributePolyMesh (const Xfer< mapDistributePolyMesh > & map)
Construct by transferring parameter content.
Definition at line 158 of file mapDistributePolyMesh.C.
mapDistributePolyMesh() [5/5]
mapDistributePolyMesh (Istream & is)
Construct from Istream.
Definition at line 175 of file mapDistributePolyMesh.C.
Member Function Documentation
nOldPoints()
label nOldPoints () const inline
Number of points in mesh before distribution.
Definition at line 175 of file mapDistributePolyMesh.H.
Referenced by mapDistributePolyMesh::distributePointIndices().
nOldFaces()
label nOldFaces () const inline
Number of faces in mesh before distribution.
Definition at line 181 of file mapDistributePolyMesh.H.
Referenced by mapDistributePolyMesh::distributeFaceIndices().
nOldCells()
label nOldCells () const inline
Number of cells in mesh before distribution.
Definition at line 187 of file mapDistributePolyMesh.H.
Referenced by mapDistributePolyMesh::distributeCellIndices().
oldPatchSizes()
const labelList& oldPatchSizes () const inline
List of the old patch sizes.
Definition at line 193 of file mapDistributePolyMesh.H.
oldPatchStarts()
const labelList& oldPatchStarts () const inline
List of the old patch start labels.
Definition at line 199 of file mapDistributePolyMesh.H.
Referenced by mapDistributePolyMesh::distributePatchIndices().
oldPatchNMeshPoints()
const labelList& oldPatchNMeshPoints () const inline
List of numbers of mesh points per old patch.
Definition at line 205 of file mapDistributePolyMesh.H.
pointMap()
const mapDistribute& pointMap () const inline
Point distribute map.
Definition at line 211 of file mapDistributePolyMesh.H.
Referenced by hexRef8Data::distribute().
faceMap()
const mapDistribute& faceMap () const inline
Face distribute map.
Definition at line 217 of file mapDistributePolyMesh.H.
cellMap()
const mapDistribute& cellMap () const inline
Cell distribute map.
Definition at line 223 of file mapDistributePolyMesh.H.
Referenced by hexRef8Data::distribute(), and refinementHistory::distribute().
patchMap()
const mapDistribute& patchMap () const inline
Patch distribute map.
Definition at line 229 of file mapDistributePolyMesh.H.
References mapDistributePolyMesh::transfer(), and mapDistributePolyMesh::xfer().
transfer()
void transfer (mapDistributePolyMesh & rhs)
Transfer the contents of the argument and annul the argument.
Definition at line 183 of file mapDistributePolyMesh.C.
References List< T >::transfer(), and mapDistribute::transfer().
Referenced by mapDistributePolyMesh::patchMap().
xfer()
Foam::Xfer< Foam::mapDistributePolyMesh > xfer ()
Transfer contents to the Xfer container.
Definition at line 198 of file mapDistributePolyMesh.C.
References Foam::xferMove().
Referenced by mapDistributePolyMesh::patchMap().
distributePointData()
void distributePointData (List< T > & lst) const inline
Distribute list of point data.
Definition at line 245 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
Referenced by hexRef8::distribute(), and mapDistributePolyMesh::distributePointIndices().
distributeFaceData()
void distributeFaceData (List< T > & lst) const inline
Distribute list of face data.
Definition at line 252 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
Referenced by meshRefinement::distribute(), and mapDistributePolyMesh::distributeFaceIndices().
distributeCellData()
void distributeCellData (List< T > & lst) const inline
Distribute list of cell data.
Definition at line 259 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
Referenced by hexRef8::distribute(), and mapDistributePolyMesh::distributeCellIndices().
distributePatchData()
void distributePatchData (List< T > & lst) const inline
Distribute list of patch data.
Definition at line 266 of file mapDistributePolyMesh.H.
References mapDistribute::distribute(), mapDistributePolyMesh::distributeCellIndices(), mapDistributePolyMesh::distributeFaceIndices(), mapDistributePolyMesh::distributePatchIndices(), and mapDistributePolyMesh::distributePointIndices().
Referenced by mapDistributePolyMesh::distributePatchIndices().
distributePointIndices()
void distributePointIndices (labelList & pointIDs) const
Distribute list of point/face/cell/patch indices.
(Converts to boolList, distributes boolList and reconstructs)
Definition at line 204 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::distributePointData(), Foam::findIndices(), and mapDistributePolyMesh::nOldPoints().
Referenced by mapDistributePolyMesh::distributePatchData().
distributeFaceIndices()
void distributeFaceIndices (labelList & faceIDs) const
Definition at line 226 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::distributeFaceData(), Foam::findIndices(), and mapDistributePolyMesh::nOldFaces().
Referenced by mapDistributePolyMesh::distributePatchData().
distributeCellIndices()
void distributeCellIndices (labelList & cellIDs) const
Definition at line 248 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::distributeCellData(), Foam::findIndices(), and mapDistributePolyMesh::nOldCells().
Referenced by mapDistributePolyMesh::distributePatchData().
distributePatchIndices()
void distributePatchIndices (labelList & patchIDs) const
Definition at line 270 of file mapDistributePolyMesh.C.
References mapDistributePolyMesh::distributePatchData(), Foam::findIndices(), and mapDistributePolyMesh::oldPatchStarts().
Referenced by mapDistributePolyMesh::distributePatchData().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Correct for topo change.
Definition at line 282 of file mapDistributePolyMesh.H.
References NotImplemented, mapDistributePolyMesh::operator<<, mapDistributePolyMesh::operator=(), and mapDistributePolyMesh::operator>>.
operator=()
void operator= (const mapDistributePolyMesh & rhs)
Definition at line 294 of file mapDistributePolyMesh.C.
Referenced by mapDistributePolyMesh::updateMesh().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , mapDistributePolyMesh &) friend
Read dictionary from Istream.
Referenced by mapDistributePolyMesh::updateMesh().
operator<<
Ostream& operator<< (Ostream & , const mapDistributePolyMesh &) friend
Write dictionary to Ostream.
Referenced by mapDistributePolyMesh::updateMesh().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributePolyMesh.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributePolyMesh.C