OpenFOAM: polyMeshTools Class Reference
polyMeshTools Class Reference
Static Public Member Functions
static tmp< scalarField > faceOrthogonality (const polyMesh &mesh, const vectorField &fAreas, const vectorField &cellCtrs)
Generate orthogonality field. (1 for fully orthogonal, < 1 for.
static tmp< scalarField > faceSkewness (const polyMesh &mesh, const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs)
Generate skewness field.
static tmp< scalarField > faceWeights (const polyMesh &mesh, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs)
Generate interpolation factors field.
static tmp< scalarField > volRatio (const polyMesh &mesh, const scalarField &vol)
Generate volume ratio field.
Static Public Member Functions inherited from primitiveMeshTools
static tmp< scalarField > faceOrthogonality (const primitiveMesh &mesh, const vectorField &fAreas, const vectorField &cellCtrs)
Generate non-orthogonality field (internal faces only)
static void facePyramidVolume (const primitiveMesh &mesh, const pointField &points, const vectorField &cellCtrs, scalarField &ownPyrVol, scalarField &neiPyrVol)
Generate face pyramid volume fields.
static tmp< scalarField > faceSkewness (const primitiveMesh &mesh, const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs)
Generate skewness field.
static void cellClosedness (const primitiveMesh &mesh, const Vector< label > &meshD, const vectorField &areas, const scalarField &vols, scalarField &openness, scalarField &aratio)
Generate cell openness and cell ascpect ratio field.
static tmp< scalarField > faceConcavity (const scalar maxSin, const primitiveMesh &mesh, const pointField &p, const vectorField &faceAreas)
Generate face concavity field. Returns per face the (sin of the)
static tmp< scalarField > faceFlatness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &faceAreas)
Generate face flatness field. Compares the individual triangles'.
static tmp< scalarField > edgeAlignment (const primitiveMesh &mesh, const Vector< label > &directions, const pointField &p)
Generate edge alignment field. Is per face the minimum aligned edge.
static tmp< scalarField > cellDeterminant (const primitiveMesh &mesh, const Vector< label > &directions, const vectorField &faceAreas, const PackedBoolList &internalOrCoupledFace)
Generate cell determinant field.
static scalar faceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc, const point &neiCc)
Skewness of single face.
static scalar boundaryFaceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc)
Skewness of single boundary face.
static scalar faceOrthogonality (const point &ownCc, const point &neiCc, const vector &s)
Orthogonality of single face.
Detailed Description
Definition at line 50 of file polyMeshTools.H.
Member Function Documentation
faceOrthogonality()
Foam::tmp< Foam::scalarField > faceOrthogonality (const polyMesh & mesh, const vectorField & fAreas, const vectorField & cellCtrs) static
Generate orthogonality field. (1 for fully orthogonal, < 1 for.
non-orthogonal)
Definition at line 35 of file polyMeshTools.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMeshTools::faceSkewness(), forAll, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, scalarField(), and polyPatch::start().
faceSkewness()
Foam::tmp< Foam::scalarField > faceSkewness (const polyMesh & mesh, const pointField & points, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs) static
Generate skewness field.
Definition at line 90 of file polyMeshTools.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMeshTools::faceWeights(), forAll, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, tmp< T >::ref(), scalarField(), Foam::skew(), and polyPatch::start().
Referenced by polyMeshTools::faceOrthogonality().
faceWeights()
Foam::tmp< Foam::scalarField > faceWeights (const polyMesh & mesh, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs) static
Generate interpolation factors field.
Definition at line 175 of file polyMeshTools.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::mag(), Foam::min(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, scalarField(), polyPatch::start(), and polyMeshTools::volRatio().
Referenced by polyMeshTools::faceSkewness().
volRatio()
Foam::tmp< Foam::scalarField > volRatio (const polyMesh & mesh, const scalarField & vol) static
Generate volume ratio field.
Definition at line 233 of file polyMeshTools.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::max(), Foam::min(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, scalarField(), and polyPatch::start().
Referenced by polyMeshTools::faceWeights().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyMeshCheck/polyMeshTools.H
src/OpenFOAM/meshes/polyMesh/polyMeshCheck/polyMeshTools.C