OpenFOAM: mapDistributeBase Class Reference
mapDistributeBase Class Reference
Class containing processor-to-processor mapping information.
Public Member Functions
ClassName ("mapDistributeBase")
mapDistributeBase ()
Construct null.
mapDistributeBase (const label constructSize, const Xfer< labelListList > &subMap, const Xfer< labelListList > &constructMap, const bool subHasFlip=false, const bool constructHasFlip=false)
Construct from components.
mapDistributeBase (const labelList &sendProcs, const labelList &recvProcs)
Construct from reverse addressing: per data item the send.
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex.
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Special variant that works with the info sorted into bins.
mapDistributeBase (const Xfer< mapDistributeBase > &)
Construct by transferring parameter content.
mapDistributeBase (const mapDistributeBase &)
Construct copy.
mapDistributeBase (Istream &)
Construct from Istream.
label constructSize () const
Constructed data size.
label & constructSize ()
Constructed data size.
const labelListList & subMap () const
From subsetted data back to original data.
labelListList & subMap ()
From subsetted data back to original data.
const labelListList & constructMap () const
From subsetted data to new reconstructed data.
labelListList & constructMap ()
From subsetted data to new reconstructed data.
bool subHasFlip () const
Does subMap include a sign.
bool & subHasFlip ()
Does subMap include a sign.
bool constructHasFlip () const
Does constructMap include a sign.
bool & constructHasFlip ()
Does constructMap include a sign.
const List< labelPair > & schedule () const
Return a schedule. Demand driven. See above.
void transfer (mapDistributeBase &)
Transfer the contents of the argument and annul the argument.
Xfer< mapDistributeBase > xfer ()
Transfer contents to the Xfer container.
void compact (const boolList &elemIsUsed, const int tag=UPstream::msgType())
Compact maps. Gets per field a bool whether it is used (locally)
void compact (const boolList &elemIsUsed, const label localSize, labelList &oldToNewSub, labelList &oldToNewConstruct, const int tag=UPstream::msgType())
Compact all maps and layout. Returns compaction maps for.
template<class T >
void distribute (List< T > &fld, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T , class negateOp >
void distribute (List< T > &fld, const negateOp &negOp, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void distribute (DynamicList< T > &fld, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, List< T > &, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &fld, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void send (PstreamBuffers &, const List< T > &) const
Do all sends using PstreamBuffers.
template<class T >
void receive (PstreamBuffers &, List< T > &) const
Do all receives using PstreamBuffers.
void printLayout (Ostream &os) const
Debug: print layout. Can only be used on maps with sorted.
void updateMesh (const mapPolyMesh &)
Correct for topo change.
void operator= (const mapDistributeBase &)
Static Public Member Functions
static List< labelPair > schedule (const labelListList &subMap, const labelListList &constructMap, const int tag)
Calculate a schedule. See above.
static label renumber (const globalIndex &, const List< Map< label >> &compactMap, const label globalElement)
Helper for construct from globalIndex. Renumbers element.
template<class T , class negateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &, const negateOp &negOp, const int tag=UPstream::msgType())
Distribute data. Note:schedule only used for Pstream::scheduled.
template<class T , class CombineOp , class negateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &, const CombineOp &cop, const negateOp &negOp, const T &nullValue, const int tag=UPstream::msgType())
Distribute data. If multiple processors writing to same.
Protected Member Functions
void calcCompactAddressing (const globalIndex &globalNumbering, const labelList &elements, List< Map< label >> &compactMap) const
Construct per processor compact addressing of the global elements.
void calcCompactAddressing (const globalIndex &globalNumbering, const labelListList &elements, List< Map< label >> &compactMap) const
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelList &elements, List< Map< label >> &compactMap, labelList &compactStart)
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelListList &elements, List< Map< label >> &compactMap, labelList &compactStart)
Static Protected Member Functions
static void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize)
template<class T , class CombineOp , class negateOp >
static void flipAndCombine (const UList< label > &map, const bool hasFlip, const UList< T > &rhs, const CombineOp &cop, const negateOp &negOp, List< T > &lhs)
template<class T , class negateOp >
static T accessAndFlip (const UList< T > &fld, const label index, const bool hasFlip, const negateOp &negOp)
Protected Attributes
label constructSize_
Size of reconstructed data.
labelListList subMap_
Maps from subsetted data back to original data.
labelListList constructMap_
Maps from subsetted data to new reconstructed data.
bool subHasFlip_
Whether subMap includes flip or not.
bool constructHasFlip_
Whether constructMap includes flip or not.
autoPtr< List< labelPair > > schedulePtr_
Schedule.
Friends
Istream & operator>> (Istream &, mapDistributeBase &)
Read dictionary from Istream.
Ostream & operator<< (Ostream &, const mapDistributeBase &)
Write dictionary to Ostream.
Detailed Description
Class containing processor-to-processor mapping information.
We store mapping from the bits-to-send to the complete starting list (subXXXMap) and from the received bits to their location in the new list (constructXXXMap).
Note: Schedule is a list of processor pairs (one send, one receive. One of them will be myself) which forms a scheduled (i.e. non-buffered) exchange. See distribute on how to use it. Note2: number of items sent on one processor have to equal the number of items received on the other processor.
To aid constructing these maps there are the constructors from global numbering, either with or without transforms.
Constructors using compact numbering: layout is
all my own elements first (whether used or not)
followed by used-only remote elements sorted by remote processor. So e.g 4 procs and on proc 1 the compact table will first have all globalIndex.localSize() elements from proc1 followed by used-only elements of proc0, proc2, proc3. The constructed mapDistributeBase sends the local elements from and receives the remote elements into their compact position. compactMap[proci] is the position of elements from proci in the compact map. compactMap[myProcNo()] is empty since trivial addressing.
It rewrites the input global indices into indices into the constructed data.
When constructing from components optionally a 'flip' on the maps can be specified. This will interpret the map values as index+flip, similar to e.g. faceProcAddressing. The flip will only be applied to fieldTypes (scalar, vector, .. triad)
Source files
mapDistributeBase.H
mapDistributeBase.C
mapDistributeBaseTemplates.C
Definition at line 100 of file mapDistributeBase.H.
Constructor & Destructor Documentation
mapDistributeBase() [1/8]
mapDistributeBase ()
Construct null.
Definition at line 547 of file mapDistributeBase.C.
Referenced by mapDistributeBase::mapDistributeBase().
mapDistributeBase() [2/8]
mapDistributeBase (const label constructSize, const Xfer< labelListList > & subMap, const Xfer< labelListList > & constructMap, const bool subHasFlip = false, const bool constructHasFlip = false)
Construct from components.
Definition at line 557 of file mapDistributeBase.C.
References mapDistributeBase::mapDistributeBase().
mapDistributeBase() [3/8]
mapDistributeBase (const labelList & sendProcs, const labelList & recvProcs)
Construct from reverse addressing: per data item the send.
processor and the receive processor. (note: data is not stored sorted per processor so cannot use printLayout).
Definition at line 575 of file mapDistributeBase.C.
References Foam::abort(), mapDistributeBase::constructMap_, mapDistributeBase::constructSize_, Foam::FatalError, FatalErrorInFunction, forAll, mapDistributeBase::mapDistributeBase(), UPstream::myProcNo(), UPstream::nProcs(), List< T >::setSize(), List< T >::size(), and mapDistributeBase::subMap_.
mapDistributeBase() [4/8]
mapDistributeBase (const globalIndex & globalNumbering, labelList & elements, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex.
numbering (or -1). Determines compact numbering (see above) and distribute map to get data into this ordering and renumbers the elements to be in compact numbering.
Definition at line 649 of file mapDistributeBase.C.
References mapDistributeBase::calcCompactAddressing(), mapDistributeBase::exchangeAddressing(), mapDistributeBase::mapDistributeBase(), Foam::Pout, and mapDistributeBase::printLayout().
mapDistributeBase() [5/8]
mapDistributeBase (const globalIndex & globalNumbering, labelListList & cellCells, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Special variant that works with the info sorted into bins.
according to local indices. E.g. think cellCells where cellCells[localCellI] is a list of global cells
Definition at line 709 of file mapDistributeBase.C.
References mapDistributeBase::calcCompactAddressing(), mapDistributeBase::exchangeAddressing(), Foam::Pout, and mapDistributeBase::printLayout().
mapDistributeBase() [6/8]
mapDistributeBase (const Xfer< mapDistributeBase > & map)
Construct by transferring parameter content.
Definition at line 779 of file mapDistributeBase.C.
mapDistributeBase() [7/8]
mapDistributeBase (const mapDistributeBase & map)
Construct copy.
Definition at line 768 of file mapDistributeBase.C.
mapDistributeBase() [8/8]
mapDistributeBase (Istream & is)
Construct from Istream.
Definition at line 790 of file mapDistributeBase.C.
Member Function Documentation
checkReceivedSize()
void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize) static protected
Definition at line 185 of file mapDistributeBase.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by mapDistributeBase::schedule().
calcCompactAddressing() [1/2]
void calcCompactAddressing (const globalIndex & globalNumbering, const labelList & elements, List< Map< label >> & compactMap) const protected
Construct per processor compact addressing of the global elements.
needed. The ones from the local processor are not included since these are always all needed.
Definition at line 277 of file mapDistributeBase.C.
References forAll, globalIndex::isLocal(), UPstream::myProcNo(), UPstream::nProcs(), globalIndex::toLocal(), and globalIndex::whichProcID().
Referenced by mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), and mapDistributeBase::printLayout().
calcCompactAddressing() [2/2]
void calcCompactAddressing (const globalIndex & globalNumbering, const labelListList & elements, List< Map< label >> & compactMap) const protected
Definition at line 326 of file mapDistributeBase.C.
References mapDistributeBase::exchangeAddressing(), forAll, globalIndex::isLocal(), UPstream::myProcNo(), UPstream::nProcs(), globalIndex::toLocal(), and globalIndex::whichProcID().
exchangeAddressing() [1/2]
void exchangeAddressing (const int tag, const globalIndex & globalNumbering, labelList & elements, List< Map< label >> & compactMap, labelList & compactStart) protected
Definition at line 385 of file mapDistributeBase.C.
References forAll, forAllIter, Foam::identity(), globalIndex::localSize(), UPstream::myProcNo(), UPstream::nProcs(), Foam::renumber(), List< T >::setSize(), List< T >::size(), and UPstream::worldComm.
Referenced by mapDistributeBase::calcCompactAddressing(), mapDistribute::mapDistribute(), and mapDistributeBase::mapDistributeBase().
exchangeAddressing() [2/2]
void exchangeAddressing (const int tag, const globalIndex & globalNumbering, labelListList & elements, List< Map< label >> & compactMap, labelList & compactStart) protected
Definition at line 463 of file mapDistributeBase.C.
References forAll, forAllIter, Foam::identity(), globalIndex::localSize(), UPstream::myProcNo(), UPstream::nProcs(), Foam::renumber(), List< T >::setSize(), List< T >::size(), and UPstream::worldComm.
flipAndCombine()
void flipAndCombine (const UList< label > & map, const bool hasFlip, const UList< T > & rhs, const CombineOp & cop, const negateOp & negOp, List< T > & lhs) static protected
Definition at line 35 of file mapDistributeBaseTemplates.C.
References mapDistributeBase::accessAndFlip(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UList< T >::size(), and T.
Referenced by mapDistributeBase::receive().
accessAndFlip()
T accessAndFlip (const UList< T > & fld, const label index, const bool hasFlip, const negateOp & negOp) static protected
Definition at line 80 of file mapDistributeBaseTemplates.C.
References mapDistributeBase::distribute(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::size(), and T.
Referenced by mapDistributeBase::compact(), mapDistributeBase::flipAndCombine(), and mapDistributeBase::send().
ClassName()
ClassName ("mapDistributeBase")
constructSize() [1/2]
label constructSize () const inline
Constructed data size.
Definition at line 257 of file mapDistributeBase.H.
References mapDistributeBase::constructSize_.
Referenced by extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), mapDistributeBase::constructHasFlip(), PointEdgeWave< Type, TrackingData >::countPatchType(), PatchTools::edgeNormals(), globalIndexAndTransform::globalIndexAndTransform(), globalMeshData::mergePoints(), minEqOp< labelPair >::operator()(), mapDistribute::transformPosition::operator()(), PatchTools::pointNormals(), distributedWeightedFvPatchFieldMapper::size(), syncTools::syncEdgeList(), syncTools::syncPointList(), pointConstraints::syncUntransformedData(), mapDistribute::transformStart(), and AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod().
constructSize() [2/2]
label& constructSize () inline
Constructed data size.
Definition at line 263 of file mapDistributeBase.H.
References mapDistributeBase::constructSize_.
subMap() [1/2]
const labelListList& subMap () const inline
From subsetted data back to original data.
Definition at line 269 of file mapDistributeBase.H.
References mapDistributeBase::subMap_.
Referenced by mapDistributeBase::constructHasFlip(), refinementHistory::distribute(), meshToMesh::mapAndOpTgtToSrc(), mapDistribute::transformPosition::operator()(), AMIInterpolation< SourcePatch, TargetPatch >::update(), AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod(), and extendedCellToFaceStencil::writeStencilStats().
subMap() [2/2]
labelListList& subMap () inline
From subsetted data back to original data.
Definition at line 275 of file mapDistributeBase.H.
References mapDistributeBase::subMap_.
constructMap() [1/2]
const labelListList& constructMap () const inline
From subsetted data to new reconstructed data.
Definition at line 281 of file mapDistributeBase.H.
References mapDistributeBase::constructMap_.
Referenced by mapDistributeBase::constructHasFlip(), refinementHistory::distribute(), meshToMesh::mapAndOpTgtToSrc(), mapDistribute::transformPosition::operator()(), AMIInterpolation< SourcePatch, TargetPatch >::update(), and AMIInterpolation< SourcePatch, TargetPatch >::wordTointerpolationMethod().
constructMap() [2/2]
labelListList& constructMap () inline
From subsetted data to new reconstructed data.
Definition at line 287 of file mapDistributeBase.H.
References mapDistributeBase::constructMap_.
subHasFlip() [1/2]
bool subHasFlip () const inline
Does subMap include a sign.
Definition at line 293 of file mapDistributeBase.H.
References mapDistributeBase::subHasFlip_.
Referenced by mapDistributeBase::constructHasFlip(), and mapDistribute::transformPosition::operator()().
subHasFlip() [2/2]
bool& subHasFlip () inline
Does subMap include a sign.
Definition at line 299 of file mapDistributeBase.H.
References mapDistributeBase::subHasFlip_.
constructHasFlip() [1/2]
bool constructHasFlip () const inline
Does constructMap include a sign.
Definition at line 305 of file mapDistributeBase.H.
References mapDistributeBase::constructHasFlip_.
Referenced by mapDistributeBase::constructHasFlip(), and mapDistribute::transformPosition::operator()().
constructHasFlip() [2/2]
bool& constructHasFlip () inline
Does constructMap include a sign.
Definition at line 311 of file mapDistributeBase.H.
References mapDistributeBase::compact(), mapDistributeBase::constructHasFlip(), mapDistributeBase::constructHasFlip_, mapDistributeBase::constructMap(), mapDistributeBase::constructSize(), mapDistributeBase::distribute(), fld(), UPstream::msgType(), mapDistributeBase::printLayout(), mapDistributeBase::receive(), mapDistributeBase::renumber(), mapDistributeBase::reverseDistribute(), mapDistributeBase::schedule(), mapDistributeBase::send(), mapDistributeBase::subHasFlip(), mapDistributeBase::subMap(), Foam::T(), mapDistributeBase::transfer(), and mapDistributeBase::xfer().
schedule() [1/2]
Foam::List< Foam::labelPair > schedule (const labelListList & subMap, const labelListList & constructMap, const int tag) static
Calculate a schedule. See above.
Definition at line 43 of file mapDistributeBase.C.
References Foam::findIndex(), UPstream::firstSlave(), forAll, HashSet< Key, Hash >::insert(), UPstream::lastSlave(), UPstream::master(), UPstream::masterNo(), UPstream::myProcNo(), UPstream::nProcs(), UPstream::scheduled, List< T >::setSize(), List< T >::size(), and HashTable< nil, Key, Hash >::toc().
schedule() [2/2]
const Foam::List< Foam::labelPair > & schedule () const
Return a schedule. Demand driven. See above.
Definition at line 168 of file mapDistributeBase.C.
References mapDistributeBase::checkReceivedSize(), and UPstream::msgType().
Referenced by mapDistributeBase::constructHasFlip(), mapDistributeBase::distribute(), and mapDistributeBase::reverseDistribute().
transfer()
void transfer (mapDistributeBase & rhs)
Transfer the contents of the argument and annul the argument.
Definition at line 798 of file mapDistributeBase.C.
References mapDistributeBase::constructHasFlip_, mapDistributeBase::constructMap_, mapDistributeBase::constructSize_, mapDistributeBase::schedulePtr_, mapDistributeBase::subHasFlip_, mapDistributeBase::subMap_, and List< T >::transfer().
Referenced by mapDistributeBase::constructHasFlip(), and mapDistribute::transfer().
xfer()
Foam::Xfer< Foam::mapDistributeBase > xfer ()
Transfer contents to the Xfer container.
Definition at line 809 of file mapDistributeBase.C.
References mapDistributeBase::renumber(), and Foam::xferMove().
Referenced by mapDistributeBase::constructHasFlip().
renumber()
Foam::label renumber (const globalIndex & globalNumbering, const List< Map< label >> & compactMap, const label globalElement) static
Helper for construct from globalIndex. Renumbers element.
(in globalIndex numbering) into compact indices.
Definition at line 816 of file mapDistributeBase.C.
References globalIndex::isLocal(), globalIndex::toLocal(), and globalIndex::whichProcID().
Referenced by mapDistributeBase::constructHasFlip(), and mapDistributeBase::xfer().
compact() [1/2]
void compact (const boolList & elemIsUsed, const int tag = UPstream::msgType())
Compact maps. Gets per field a bool whether it is used (locally)
and works out itself what this side and sender side can remove from maps. Only compacts non-local elements (i.e. the stuff that gets sent over), does not change the local layout
Definition at line 839 of file mapDistributeBase.C.
References mapDistributeBase::accessAndFlip(), UList< T >::begin(), mapDistributeBase::constructHasFlip_, mapDistributeBase::constructMap_, mapDistributeBase::constructSize_, forAll, Foam::mag(), Foam::max(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UPstream::parRun(), UIPstream::read(), mapDistributeBase::schedulePtr_, List< T >::setSize(), List< T >::size(), mapDistributeBase::subMap_, List< T >::transfer(), UPstream::waitRequests(), and UOPstream::write().
Referenced by mapDistributeBase::constructHasFlip().
compact() [2/2]
void compact (const boolList & elemIsUsed, const label localSize, labelList & oldToNewSub, labelList & oldToNewConstruct, const int tag = UPstream::msgType())
Compact all maps and layout. Returns compaction maps for.
subMap and constructMap
Definition at line 1000 of file mapDistributeBase.C.
References UList< T >::begin(), mapDistributeBase::constructHasFlip_, mapDistributeBase::constructMap_, mapDistributeBase::constructSize_, forAll, Foam::mag(), UPstream::myProcNo(), UPstream::nonBlocking, UPstream::nProcs(), UPstream::nRequests(), UPstream::parRun(), UIPstream::read(), List< T >::setSize(), Foam::sign(), List< T >::size(), mapDistributeBase::subHasFlip_, mapDistributeBase::subMap_, List< T >::transfer(), UPstream::waitRequests(), and UOPstream::write().
distribute() [1/5]
void distribute (const Pstream::commsTypes commsType, const List< labelPair > & schedule, const label constructSize, const labelListList & subMap, const bool subHasFlip, const labelListList & constructMap, const bool constructHasFlip, List< T > & field, const negateOp & negOp, const int tag = UPstream::msgType()) static
Distribute data. Note:schedule only used for Pstream::scheduled.
for now, all others just use send-to-all, receive-from-all.
Definition at line 119 of file mapDistributeBaseTemplates.C.
References Foam::abort(), UList< T >::begin(), UList< T >::byteSize(), Foam::FatalError, FatalErrorInFunction, PstreamBuffers::finishedSends(), forAll, Foam::read(), List< T >::setSize(), List< T >::size(), List< T >::transfer(), and write().
Referenced by mapDistributeBase::accessAndFlip(), Field< Foam::Vector2D >::autoMap(), mapDistributeBase::constructHasFlip(), mapDistributeBase::distribute(), mappedPatchBase::distribute(), mapDistribute::distribute(), Field< Foam::Vector2D >::map(), meshToMesh::mapAndOpTgtToSrc(), mapDistributeBase::receive(), mapDistributeBase::reverseDistribute(), mappedPatchBase::reverseDistribute(), streamLine::write(), and wallBoundedStreamLine::write().
distribute() [2/5]
void distribute (const Pstream::commsTypes commsType, const List< labelPair > & schedule, const label constructSize, const labelListList & subMap, const bool subHasFlip, const labelListList & constructMap, const bool constructHasFlip, List< T > & field, const CombineOp & cop, const negateOp & negOp, const T & nullValue, const int tag = UPstream::msgType()) static
Distribute data. If multiple processors writing to same.
position adds contributions using cop.
Definition at line 603 of file mapDistributeBaseTemplates.C.
References Foam::abort(), UList< T >::begin(), Foam::FatalError, FatalErrorInFunction, PstreamBuffers::finishedSends(), forAll, Foam::read(), List< T >::setSize(), List< T >::size(), T, List< T >::transfer(), and write().
distribute() [3/5]
void distribute (List< T > & fld, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 1212 of file mapDistributeBaseTemplates.C.
References mapDistributeBase::distribute().
distribute() [4/5]
void distribute (List< T > & fld, const negateOp & negOp, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 1152 of file mapDistributeBaseTemplates.C.
References UPstream::blocking, mapDistributeBase::constructHasFlip_, mapDistributeBase::constructMap_, mapDistributeBase::constructSize_, UPstream::defaultCommsType, mapDistributeBase::distribute(), UPstream::nonBlocking, mapDistributeBase::schedule(), UPstream::scheduled, mapDistributeBase::subHasFlip_, and mapDistributeBase::subMap_.
distribute() [5/5]
void distribute (DynamicList< T > & fld, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 1224 of file mapDistributeBaseTemplates.C.
References mapDistributeBase::distribute(), fld(), mapDistributeBase::reverseDistribute(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink(), and List< T >::size().
reverseDistribute() [1/2]
void reverseDistribute (const label constructSize, List< T > & fld, const int tag = UPstream::msgType()) const
Reverse distribute data using default commsType.
Definition at line 1242 of file mapDistributeBaseTemplates.C.
References UPstream::blocking, mapDistributeBase::constructHasFlip_, mapDistributeBase::constructMap_, UPstream::defaultCommsType, mapDistributeBase::distribute(), UPstream::nonBlocking, mapDistributeBase::schedule(), UPstream::scheduled, mapDistributeBase::subHasFlip_, and mapDistributeBase::subMap_.
Referenced by mapDistributeBase::constructHasFlip(), mapDistributeBase::distribute(), and mapDistribute::reverseDistribute().
reverseDistribute() [2/2]
void reverseDistribute (const label constructSize, const T & nullValue, List< T > & fld, const int tag = UPstream::msgType()) const
Reverse distribute data using default commsType.
Since constructSize might be larger than supplied size supply a nullValue
Definition at line 1304 of file mapDistributeBaseTemplates.C.
References UPstream::blocking, mapDistributeBase::constructHasFlip_, mapDistributeBase::constructMap_, UPstream::defaultCommsType, mapDistributeBase::distribute(), UPstream::nonBlocking, mapDistributeBase::schedule(), UPstream::scheduled, mapDistributeBase::subHasFlip_, and mapDistributeBase::subMap_.
send()
void send (PstreamBuffers & pBufs, const List< T > & field) const
Do all sends using PstreamBuffers.
Definition at line 1077 of file mapDistributeBaseTemplates.C.
References mapDistributeBase::accessAndFlip(), PstreamBuffers::finishedSends(), forAll, UPstream::nProcs(), List< T >::size(), mapDistributeBase::subHasFlip_, and mapDistributeBase::subMap_.
Referenced by mapDistributeBase::constructHasFlip().
receive()
void receive (PstreamBuffers & pBufs, List< T > & field) const
Do all receives using PstreamBuffers.
Definition at line 1111 of file mapDistributeBaseTemplates.C.
References Foam::abort(), mapDistributeBase::constructHasFlip_, mapDistributeBase::constructMap_, mapDistributeBase::constructSize_, mapDistributeBase::distribute(), Foam::FatalError, FatalErrorInFunction, mapDistributeBase::flipAndCombine(), UPstream::nProcs(), List< T >::setSize(), and List< T >::size().
Referenced by mapDistributeBase::constructHasFlip().
printLayout()
void printLayout (Ostream & os) const
Debug: print layout. Can only be used on maps with sorted.
storage (local data first, then non-local data)
Definition at line 202 of file mapDistributeBase.C.
References Foam::abort(), mapDistributeBase::calcCompactAddressing(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::labelMax, Foam::labelMin, Foam::mag(), Foam::max(), Foam::min(), UPstream::myProcNo(), and UPstream::nProcs().
Referenced by mapDistributeBase::constructHasFlip(), mapDistributeBase::mapDistributeBase(), and mapDistribute::printLayout().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Correct for topo change.
Definition at line 460 of file mapDistributeBase.H.
References NotImplemented, mapDistributeBase::operator<<, mapDistributeBase::operator=(), and mapDistributeBase::operator>>.
operator=()
void operator= (const mapDistributeBase & rhs)
Definition at line 1223 of file mapDistributeBase.C.
References Foam::abort(), mapDistributeBase::constructHasFlip_, mapDistributeBase::constructMap_, mapDistributeBase::constructSize_, Foam::FatalError, FatalErrorInFunction, mapDistributeBase::schedulePtr_, mapDistributeBase::subHasFlip_, and mapDistributeBase::subMap_.
Referenced by mapDistribute::operator=(), and mapDistributeBase::updateMesh().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , mapDistributeBase &) friend
Read dictionary from Istream.
Referenced by mapDistributeBase::updateMesh().
operator<<
Ostream& operator<< (Ostream & , const mapDistributeBase &) friend
Write dictionary to Ostream.
Referenced by mapDistributeBase::updateMesh().
Member Data Documentation
constructSize_
label constructSize_ protected
Size of reconstructed data.
Definition at line 107 of file mapDistributeBase.H.
Referenced by mapDistributeBase::compact(), mapDistributeBase::constructSize(), mapDistributeBase::distribute(), mapDistribute::mapDistribute(), mapDistributeBase::mapDistributeBase(), Foam::operator<<(), mapDistributeBase::operator=(), Foam::operator>>(), mapDistributeBase::receive(), and mapDistributeBase::transfer().
subMap_
labelListList subMap_ protected
Maps from subsetted data back to original data.
Definition at line 110 of file mapDistributeBase.H.
Referenced by mapDistributeBase::compact(), mapDistributeBase::distribute(), mapDistributeBase::mapDistributeBase(), Foam::operator<<(), mapDistributeBase::operator=(), Foam::operator>>(), mapDistributeBase::reverseDistribute(), mapDistributeBase::send(), mapDistributeBase::subMap(), and mapDistributeBase::transfer().
constructMap_
labelListList constructMap_ protected
Maps from subsetted data to new reconstructed data.
Definition at line 113 of file mapDistributeBase.H.
Referenced by mapDistributeBase::compact(), mapDistributeBase::constructMap(), mapDistributeBase::distribute(), mapDistributeBase::mapDistributeBase(), Foam::operator<<(), mapDistributeBase::operator=(), Foam::operator>>(), mapDistributeBase::receive(), mapDistributeBase::reverseDistribute(), and mapDistributeBase::transfer().
subHasFlip_
bool subHasFlip_ protected
Whether subMap includes flip or not.
Definition at line 116 of file mapDistributeBase.H.
Referenced by mapDistributeBase::compact(), mapDistributeBase::distribute(), Foam::operator<<(), mapDistributeBase::operator=(), Foam::operator>>(), mapDistributeBase::reverseDistribute(), mapDistributeBase::send(), mapDistributeBase::subHasFlip(), and mapDistributeBase::transfer().
constructHasFlip_
bool constructHasFlip_ protected
Whether constructMap includes flip or not.
Definition at line 119 of file mapDistributeBase.H.
Referenced by mapDistributeBase::compact(), mapDistributeBase::constructHasFlip(), mapDistributeBase::distribute(), Foam::operator<<(), mapDistributeBase::operator=(), Foam::operator>>(), mapDistributeBase::receive(), mapDistributeBase::reverseDistribute(), and mapDistributeBase::transfer().
schedulePtr_
autoPtr<List<labelPair> > schedulePtr_ mutable protected
Schedule.
Definition at line 123 of file mapDistributeBase.H.
Referenced by mapDistributeBase::compact(), mapDistributeBase::operator=(), and mapDistributeBase::transfer().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBase.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBase.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBaseTemplates.C