OpenFOAM: cyclicSlipPolyPatch Class Reference
cyclicSlipPolyPatch Class Reference
Copy of cyclicSlip - used to be able to instantiate cyclicSlip pointPatch which is cyclicSlip with slip constraints.
Public Member Functions
TypeName ("cyclicSlip")
Runtime type information.
cyclicSlipPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN)
Construct from components.
cyclicSlipPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
cyclicSlipPolyPatch (const cyclicSlipPolyPatch &pp, const polyBoundaryMesh &bm)
Construct as copy, resetting the boundary mesh.
cyclicSlipPolyPatch (const cyclicSlipPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &neighbPatchName)
Construct given the original patch and resetting the.
cyclicSlipPolyPatch (const cyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~cyclicSlipPolyPatch ()
Public Member Functions inherited from cyclicPolyPatch
TypeName ("cyclic")
Runtime type information.
cyclicPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN)
Construct from components.
cyclicPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &neighbPatchName, const transformType transform, const vector &rotationAxis, const point &rotationCentre, const vector &separationVector)
Construct from components.
cyclicPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
cyclicPolyPatch (const cyclicPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
cyclicPolyPatch (const cyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &neighbPatchName)
Construct given the original patch and resetting the.
cyclicPolyPatch (const cyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~cyclicPolyPatch ()
Destructor.
const word & neighbPatchName () const
Neighbour patch name.
virtual label neighbPatchID () const
Neighbour patchID.
virtual bool owner () const
Does this side own the patch ?
virtual bool neighbour () const
Does the coupled side own the patch ?
const cyclicPolyPatch & neighbPatch () const
const edgeList & coupledPoints () const
Return connected points (from patch local to neighbour patch local)
const edgeList & coupledEdges () const
Return connected edges (from patch local to neighbour patch local).
virtual void transformPosition (pointField &l) const
Transform a patch-based position from other side to this side.
virtual void transformPosition (point &, const label facei) const
Transform a patch-based position from other side to this side.
label transformGlobalFace (const label facei) const
const vector & rotationAxis () const
Axis of rotation for rotational cyclics.
const point & rotationCentre () const
Point on axis of rotation for rotational cyclics.
const vector & separationVector () const
Translation vector for translational cyclics.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
virtual bool coupled () const
Return true because this patch is coupled.
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes inherited from coupledPolyPatch
static const NamedEnum< transformType, 5 > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Protected Member Functions inherited from cyclicPolyPatch
virtual void calcTransforms ()
Recalculate the transformation tensors.
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void initGeometry (const primitivePatch &referPatch, pointField &nbrCtrs, vectorField &nbrAreas, pointField &nbrCc)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Detailed Description
Copy of cyclicSlip - used to be able to instantiate cyclicSlip pointPatch which is cyclicSlip with slip constraints.
Source files
cyclicSlipPolyPatch.H
cyclicSlipPolyPatch.C
Definition at line 49 of file cyclicSlipPolyPatch.H.
Constructor & Destructor Documentation
cyclicSlipPolyPatch() [1/5]
cyclicSlipPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform = UNKNOWN) inline
Construct from components.
Definition at line 64 of file cyclicSlipPolyPatch.H.
Referenced by cyclicSlipPolyPatch::clone(), and cyclicSlipPolyPatch::cyclicSlipPolyPatch().
cyclicSlipPolyPatch() [2/5]
cyclicSlipPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType) inline
Construct from dictionary.
Definition at line 79 of file cyclicSlipPolyPatch.H.
References cyclicSlipPolyPatch::cyclicSlipPolyPatch().
cyclicSlipPolyPatch() [3/5]
cyclicSlipPolyPatch (const cyclicSlipPolyPatch & pp, const polyBoundaryMesh & bm) inline
Construct as copy, resetting the boundary mesh.
Definition at line 92 of file cyclicSlipPolyPatch.H.
References cyclicSlipPolyPatch::cyclicSlipPolyPatch().
cyclicSlipPolyPatch() [4/5]
cyclicSlipPolyPatch (const cyclicSlipPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & neighbPatchName) inline
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 103 of file cyclicSlipPolyPatch.H.
References cyclicSlipPolyPatch::cyclicSlipPolyPatch().
cyclicSlipPolyPatch() [5/5]
cyclicSlipPolyPatch (const cyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) inline
Construct given the original patch and a map.
Definition at line 118 of file cyclicSlipPolyPatch.H.
~cyclicSlipPolyPatch()
virtual ~cyclicSlipPolyPatch () inline virtual
Definition at line 186 of file cyclicSlipPolyPatch.H.
Member Function Documentation
TypeName()
TypeName ("cyclicSlip")
Runtime type information.
clone() [1/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from cyclicPolyPatch.
Definition at line 131 of file cyclicSlipPolyPatch.H.
References cyclicSlipPolyPatch::cyclicSlipPolyPatch().
Referenced by cyclicSlipPolyPatch::clone().
clone() [2/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from cyclicPolyPatch.
Definition at line 139 of file cyclicSlipPolyPatch.H.
References cyclicSlipPolyPatch::clone(), cyclicSlipPolyPatch::cyclicSlipPolyPatch(), and cyclicPolyPatch::neighbPatchName().
clone() [3/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from cyclicPolyPatch.
Definition at line 163 of file cyclicSlipPolyPatch.H.
References cyclicSlipPolyPatch::cyclicSlipPolyPatch().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/cyclicSlip/cyclicSlipPolyPatch.H