OpenFOAM: faceMapper Class Reference
faceMapper Class Reference
This object provides mapping and fill-in information for face data between the two meshes after the topological change. It is constructed from mapPolyMesh.
Public Member Functions
faceMapper (const mapPolyMesh &mpm)
Construct from mapPolyMesh.
virtual ~faceMapper ()
Destructor.
virtual label size () const
Return size.
virtual label sizeBeforeMapping () const
Return size of field before mapping.
virtual label internalSizeBeforeMapping () const
Return number of internal faces before mapping.
virtual bool direct () const
Is the mapping direct.
virtual bool hasUnmapped () const
Are there unmapped values? I.e. do all size() elements get.
virtual const labelUList & directAddressing () const
Return direct addressing.
virtual const labelListList & addressing () const
Return interpolated addressing.
virtual const scalarListList & weights () const
Return interpolaion weights.
virtual const labelHashSet & flipFaceFlux () const
Return flux flip map.
virtual label nOldInternalFaces () const
Return number of old internalFaces.
virtual const labelList & oldPatchStarts () const
Return old patch starts.
virtual const labelList & oldPatchSizes () const
Return old patch sizes.
virtual bool insertedObjects () const
Are there any inserted faces.
virtual const labelList & insertedObjectLabels () const
Return list of inserted faces.
Public Member Functions inherited from morphFieldMapper
morphFieldMapper ()
Null constructor.
virtual ~morphFieldMapper ()
Destructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
This object provides mapping and fill-in information for face data between the two meshes after the topological change. It is constructed from mapPolyMesh.
Source files
faceMapper.H
faceMapper.C
Definition at line 55 of file faceMapper.H.
Constructor & Destructor Documentation
faceMapper()
faceMapper (const mapPolyMesh & mpm)
Construct from mapPolyMesh.
Definition at line 204 of file faceMapper.C.
References UList< T >::empty(), mapPolyMesh::faceMap(), mapPolyMesh::facesFromEdgesMap(), mapPolyMesh::facesFromFacesMap(), mapPolyMesh::facesFromPointsMap(), forAll, Foam::min(), and primitiveMesh::nFaces().
~faceMapper()
~faceMapper () virtual
Destructor.
Definition at line 275 of file faceMapper.C.
Member Function Documentation
size()
Foam::label size () const virtual
Return size.
Implements FieldMapper.
Definition at line 283 of file faceMapper.C.
References primitiveMesh::nFaces().
sizeBeforeMapping()
Foam::label sizeBeforeMapping () const virtual
Return size of field before mapping.
Implements morphFieldMapper.
Definition at line 289 of file faceMapper.C.
References mapPolyMesh::nOldFaces().
internalSizeBeforeMapping()
Foam::label internalSizeBeforeMapping () const virtual
Return number of internal faces before mapping.
Definition at line 295 of file faceMapper.C.
References mapPolyMesh::nOldInternalFaces().
Referenced by fvSurfaceMapper::sizeBeforeMapping().
direct()
virtual bool direct () const inline virtual
Is the mapping direct.
Implements FieldMapper.
Definition at line 131 of file faceMapper.H.
Referenced by faceMapper::addressing(), fvSurfaceMapper::direct(), fvPatchMapper::direct(), faceMapper::directAddressing(), and faceMapper::weights().
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implements FieldMapper.
Definition at line 136 of file faceMapper.H.
References faceMapper::addressing(), faceMapper::directAddressing(), faceMapper::flipFaceFlux(), faceMapper::insertedObjects(), faceMapper::nOldInternalFaces(), faceMapper::oldPatchSizes(), faceMapper::oldPatchStarts(), and faceMapper::weights().
directAddressing()
const Foam::labelUList & directAddressing () const virtual
Return direct addressing.
Reimplemented from FieldMapper.
Definition at line 301 of file faceMapper.C.
References Foam::abort(), faceMapper::direct(), mapPolyMesh::faceMap(), Foam::FatalError, FatalErrorInFunction, and faceMapper::insertedObjects().
Referenced by faceMapper::hasUnmapped().
addressing()
const Foam::labelListList & addressing () const virtual
Return interpolated addressing.
Reimplemented from FieldMapper.
Definition at line 327 of file faceMapper.C.
References Foam::abort(), faceMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by faceMapper::hasUnmapped().
weights()
const Foam::scalarListList & weights () const virtual
Return interpolaion weights.
Reimplemented from FieldMapper.
Definition at line 345 of file faceMapper.C.
References Foam::abort(), faceMapper::direct(), Foam::FatalError, and FatalErrorInFunction.
Referenced by faceMapper::hasUnmapped().
flipFaceFlux()
const Foam::labelHashSet & flipFaceFlux () const virtual
Return flux flip map.
Definition at line 382 of file faceMapper.C.
References mapPolyMesh::flipFaceFlux().
Referenced by fvSurfaceMapper::flipFaceFlux(), and faceMapper::hasUnmapped().
nOldInternalFaces()
Foam::label nOldInternalFaces () const virtual
Return number of old internalFaces.
Definition at line 388 of file faceMapper.C.
References mapPolyMesh::nOldInternalFaces().
Referenced by faceMapper::hasUnmapped().
oldPatchStarts()
const Foam::labelList & oldPatchStarts () const virtual
Return old patch starts.
Definition at line 394 of file faceMapper.C.
References mapPolyMesh::oldPatchStarts().
Referenced by faceMapper::hasUnmapped().
oldPatchSizes()
const Foam::labelList & oldPatchSizes () const virtual
Return old patch sizes.
Definition at line 400 of file faceMapper.C.
References mapPolyMesh::oldPatchSizes().
Referenced by faceMapper::hasUnmapped().
insertedObjects()
virtual bool insertedObjects () const inline virtual
Are there any inserted faces.
Implements morphFieldMapper.
Definition at line 163 of file faceMapper.H.
References faceMapper::insertedObjectLabels().
Referenced by faceMapper::directAddressing(), faceMapper::hasUnmapped(), faceMapper::insertedObjectLabels(), and fvSurfaceMapper::insertedObjects().
insertedObjectLabels()
const Foam::labelList & insertedObjectLabels () const virtual
Return list of inserted faces.
Implements morphFieldMapper.
Definition at line 363 of file faceMapper.C.
References faceMapper::insertedObjects().
Referenced by faceMapper::insertedObjects().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/faceMapper/faceMapper.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/faceMapper/faceMapper.C