OpenFOAM: mapDistribute::transform Class Reference
mapDistribute::transform Class Reference
Default transformation behaviour.
Public Member Functions
template<class Type >
void operator() (const vectorTensorTransform &vt, const bool forward, List< Type > &fld) const
template<class Type >
void operator() (const vectorTensorTransform &vt, const bool forward, List< List< Type >> &flds) const
template<class Type >
void operator() (const coupledPolyPatch &cpp, UList< Type > &fld) const
Transform patch-based field.
template<class Type , template< class > class Container>
void operator() (const coupledPolyPatch &cpp, Container< Type > &map) const
Transform sparse field.
template<>
void operator() (const vectorTensorTransform &, const bool, List< label > &) const
template<>
void operator() (const coupledPolyPatch &, UList< label > &) const
template<>
void operator() (const coupledPolyPatch &, Map< label > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< label > &) const
template<>
void operator() (const vectorTensorTransform &, const bool, List< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, UList< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, Map< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< scalar > &) const
template<>
void operator() (const vectorTensorTransform &, const bool, List< bool > &) const
template<>
void operator() (const coupledPolyPatch &, UList< bool > &) const
template<>
void operator() (const coupledPolyPatch &, Map< bool > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< bool > &) const
Detailed Description
Default transformation behaviour.
Definition at line 204 of file mapDistribute.H.
Member Function Documentation
operator()() [1/16]
void operator() (const vectorTensorTransform & vt, const bool forward, List< Type > & fld) const inline
Definition at line 210 of file mapDistribute.H.
References fld(), vectorTensorTransform::R(), Foam::T(), Tensor< Cmpt >::T(), and Foam::transformList().
Referenced by mapDistribute::transform::operator()(), and mapDistribute::transformPosition::operator()().
operator()() [2/16]
void operator() (const vectorTensorTransform & vt, const bool forward, List< List< Type >> & flds) const inline
Definition at line 222 of file mapDistribute.H.
References forAll, and mapDistribute::transform::operator()().
operator()() [3/16]
void operator() (const coupledPolyPatch & cpp, UList< Type > & fld) const inline
Transform patch-based field.
Definition at line 236 of file mapDistribute.H.
References fld(), coupledPolyPatch::forwardT(), coupledPolyPatch::parallel(), and Foam::transformList().
operator()() [4/16]
void operator() (const coupledPolyPatch & cpp, Container< Type > & map) const inline
Transform sparse field.
Definition at line 246 of file mapDistribute.H.
References coupledPolyPatch::forwardT(), coupledPolyPatch::parallel(), and Foam::transformList().
operator()() [5/16]
void operator() (const vectorTensorTransform & , const bool , List< label > &) const
Definition at line 41 of file mapDistribute.C.
operator()() [6/16]
void operator() (const coupledPolyPatch & , UList< label > &) const
Definition at line 49 of file mapDistribute.C.
operator()() [7/16]
void operator() (const coupledPolyPatch & , Map< label > &) const
Definition at line 56 of file mapDistribute.C.
operator()() [8/16]
void operator() (const coupledPolyPatch & , EdgeMap< label > &) const
Definition at line 63 of file mapDistribute.C.
operator()() [9/16]
void operator() (const vectorTensorTransform & , const bool , List< scalar > &) const
Definition at line 72 of file mapDistribute.C.
operator()() [10/16]
void operator() (const coupledPolyPatch & , UList< scalar > &) const
Definition at line 80 of file mapDistribute.C.
operator()() [11/16]
void operator() (const coupledPolyPatch & , Map< scalar > &) const
Definition at line 87 of file mapDistribute.C.
operator()() [12/16]
void operator() (const coupledPolyPatch & , EdgeMap< scalar > &) const
Definition at line 94 of file mapDistribute.C.
operator()() [13/16]
void operator() (const vectorTensorTransform & , const bool , List< bool > &) const
Definition at line 103 of file mapDistribute.C.
operator()() [14/16]
void operator() (const coupledPolyPatch & , UList< bool > &) const
Definition at line 111 of file mapDistribute.C.
operator()() [15/16]
void operator() (const coupledPolyPatch & , Map< bool > &) const
Definition at line 118 of file mapDistribute.C.
operator()() [16/16]
void operator() (const coupledPolyPatch & , EdgeMap< bool > &) const
Definition at line 125 of file mapDistribute.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.C