OpenFOAM: morphFieldMapper Class Reference
morphFieldMapper Class Reference abstract
Abstract base class to hold the Field mapping for mesh morphs.
Public Member Functions
morphFieldMapper ()
Null constructor.
virtual ~morphFieldMapper ()
Destructor.
virtual label sizeBeforeMapping () const =0
Return size of field before mapping.
virtual bool insertedObjects () const =0
Are there any inserted objects.
virtual const labelList & insertedObjectLabels () const =0
Return list of inserted objects.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual label size () const =0
virtual bool direct () const =0
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
virtual bool hasUnmapped () const =0
Are there unmapped values? I.e. do all size() elements get.
virtual const labelUList & directAddressing () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
Abstract base class to hold the Field mapping for mesh morphs.
Definition at line 46 of file morphFieldMapper.H.
Constructor & Destructor Documentation
morphFieldMapper()
morphFieldMapper () inline
Null constructor.
Definition at line 56 of file morphFieldMapper.H.
~morphFieldMapper()
virtual ~morphFieldMapper () inline virtual
Destructor.
Definition at line 61 of file morphFieldMapper.H.
References morphFieldMapper::insertedObjectLabels(), morphFieldMapper::insertedObjects(), and morphFieldMapper::sizeBeforeMapping().
Member Function Documentation
sizeBeforeMapping()
virtual label sizeBeforeMapping () const pure virtual
Return size of field before mapping.
Implemented in faceMapper, fvSurfaceMapper, cellMapper, and pointMapper.
Referenced by morphFieldMapper::~morphFieldMapper().
insertedObjects()
virtual bool insertedObjects () const pure virtual
Are there any inserted objects.
Implemented in faceMapper, fvSurfaceMapper, pointMapper, and cellMapper.
Referenced by morphFieldMapper::~morphFieldMapper().
insertedObjectLabels()
virtual const labelList& insertedObjectLabels () const pure virtual
Return list of inserted objects.
Implemented in faceMapper, fvSurfaceMapper, pointMapper, and cellMapper.
Referenced by morphFieldMapper::~morphFieldMapper().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/morphFieldMapper.H