OpenFOAM: cyclicPolyPatch Class Reference
cyclicPolyPatch Class Reference
Cyclic plane patch.
Public Member Functions
TypeName ("cyclic")
Runtime type information.
cyclicPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform=UNKNOWN)
Construct from components.
cyclicPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &neighbPatchName, const transformType transform, const vector &rotationAxis, const point &rotationCentre, const vector &separationVector)
Construct from components.
cyclicPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
cyclicPolyPatch (const cyclicPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
cyclicPolyPatch (const cyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &neighbPatchName)
Construct given the original patch and resetting the.
cyclicPolyPatch (const cyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~cyclicPolyPatch ()
Destructor.
const word & neighbPatchName () const
Neighbour patch name.
virtual label neighbPatchID () const
Neighbour patchID.
virtual bool owner () const
Does this side own the patch ?
virtual bool neighbour () const
Does the coupled side own the patch ?
const cyclicPolyPatch & neighbPatch () const
const edgeList & coupledPoints () const
Return connected points (from patch local to neighbour patch local)
const edgeList & coupledEdges () const
Return connected edges (from patch local to neighbour patch local).
virtual void transformPosition (pointField &l) const
Transform a patch-based position from other side to this side.
virtual void transformPosition (point &, const label facei) const
Transform a patch-based position from other side to this side.
label transformGlobalFace (const label facei) const
const vector & rotationAxis () const
Axis of rotation for rotational cyclics.
const point & rotationCentre () const
Point on axis of rotation for rotational cyclics.
const vector & separationVector () const
Translation vector for translational cyclics.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
virtual bool coupled () const
Return true because this patch is coupled.
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Protected Member Functions
virtual void calcTransforms ()
Recalculate the transformation tensors.
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void initGeometry (const primitivePatch &referPatch, pointField &nbrCtrs, vectorField &nbrAreas, pointField &nbrCc)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Friends
class processorCyclicPolyPatch
Declare friendship with processorCyclicPolyPatch.
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes inherited from coupledPolyPatch
static const NamedEnum< transformType, 5 > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Detailed Description
Cyclic plane patch.
Note: morph patch face ordering uses geometric matching so with the following restrictions: -coupled patches should be flat planes. -no rotation in patch plane
Uses coupledPolyPatch::calcFaceTol to calculate tolerance per face which might need tweaking.
Switch on 'cyclicPolyPatch' debug flag to write .obj files to show the matching.
Source files
cyclicPolyPatch.H
cyclicPolyPatch.C
Definition at line 63 of file cyclicPolyPatch.H.
Constructor & Destructor Documentation
cyclicPolyPatch() [1/6]
cyclicPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform = UNKNOWN)
Construct from components.
Definition at line 595 of file cyclicPolyPatch.C.
Referenced by cyclicPolyPatch::calcTransforms(), cyclicPolyPatch::clone(), and cyclicPolyPatch::cyclicPolyPatch().
cyclicPolyPatch() [2/6]
cyclicPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & neighbPatchName, const transformType transform, const vector & rotationAxis, const point & rotationCentre, const vector & separationVector)
Construct from components.
Definition at line 620 of file cyclicPolyPatch.C.
References cyclicPolyPatch::cyclicPolyPatch().
cyclicPolyPatch() [3/6]
cyclicPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 648 of file cyclicPolyPatch.C.
References cyclicPolyPatch::cyclicPolyPatch(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::lookup(), Foam::mag(), word::null, Foam::transform(), and word::valid().
cyclicPolyPatch() [4/6]
cyclicPolyPatch (const cyclicPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 721 of file cyclicPolyPatch.C.
References cyclicPolyPatch::cyclicPolyPatch().
cyclicPolyPatch() [5/6]
cyclicPolyPatch (const cyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & neighbPatchName)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 742 of file cyclicPolyPatch.C.
References cyclicPolyPatch::cyclicPolyPatch(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and Foam::name().
cyclicPolyPatch() [6/6]
cyclicPolyPatch (const cyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 775 of file cyclicPolyPatch.C.
~cyclicPolyPatch()
~cyclicPolyPatch () virtual
Destructor.
Definition at line 797 of file cyclicPolyPatch.C.
References Foam::deleteDemandDrivenData().
Referenced by cyclicPolyPatch::clone().
Member Function Documentation
calcTransforms()
void calcTransforms () protected virtual
Recalculate the transformation tensors.
Definition at line 75 of file cyclicPolyPatch.C.
References Foam::acos(), Foam::average(), clear(), cyclicPolyPatch::cyclicPolyPatch(), Foam::endl(), Foam::exit(), polyPatch::faceCentres(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceCentres(), Foam::FatalError, FatalErrorInFunction, Foam::findMax(), forAll, Foam::gAverage(), Foam::Info, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), Foam::mag(), Foam::magSqr(), mesh, n, OSstream::name(), fileName::name(), Foam::name(), Foam::nl, PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), path(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::Pout, Foam::radToDeg(), Foam::rotationTensor(), setSize(), List< T >::size(), Foam::sqrt(), Foam::sum(), Tensor< Cmpt >::T(), Foam::transform(), WarningInFunction, Foam::meshTools::writeOBJ(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
initGeometry() [1/2]
void initGeometry (PstreamBuffers & pBufs) protected virtual
Initialise the calculation of the patch geometry.
Implements coupledPolyPatch.
Definition at line 924 of file cyclicPolyPatch.C.
References polyPatch::initGeometry().
initGeometry() [2/2]
void initGeometry (const primitivePatch & referPatch, pointField & nbrCtrs, vectorField & nbrAreas, pointField & nbrCc) protected virtual
Initialise the calculation of the patch geometry.
Definition at line 931 of file cyclicPolyPatch.C.
References cyclicPolyPatch::calcGeometry().
calcGeometry() [1/2]
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Calculate the patch geometry.
Implements coupledPolyPatch.
Definition at line 962 of file cyclicPolyPatch.C.
References cyclicPolyPatch::initMovePoints().
Referenced by cyclicPolyPatch::initGeometry().
calcGeometry() [2/2]
void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) protected virtual
Calculate the patch geometry.
Implements coupledPolyPatch.
Definition at line 941 of file cyclicPolyPatch.C.
initMovePoints()
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Initialise the patches for moving points.
Implements coupledPolyPatch.
Definition at line 978 of file cyclicPolyPatch.C.
References polyPatch::initMovePoints(), and cyclicPolyPatch::movePoints().
Referenced by cyclicPolyPatch::calcGeometry().
movePoints()
void movePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Correct patches after moving points.
Implements coupledPolyPatch.
Definition at line 988 of file cyclicPolyPatch.C.
References polyPatch::movePoints().
Referenced by cyclicPolyPatch::initMovePoints().
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Implements coupledPolyPatch.
Definition at line 998 of file cyclicPolyPatch.C.
References polyPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Update of the patch topology.
Implements coupledPolyPatch.
Definition at line 1004 of file cyclicPolyPatch.C.
References Foam::deleteDemandDrivenData(), and polyPatch::updateMesh().
TypeName()
TypeName ("cyclic")
Runtime type information.
clone() [1/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from polyPatch.
Reimplemented in cyclicSlipPolyPatch, and nonuniformTransformCyclicPolyPatch.
Definition at line 260 of file cyclicPolyPatch.H.
References cyclicPolyPatch::cyclicPolyPatch().
Referenced by cyclicPolyPatch::clone().
clone() [2/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from polyPatch.
Reimplemented in nonuniformTransformCyclicPolyPatch, and cyclicSlipPolyPatch.
Definition at line 268 of file cyclicPolyPatch.H.
References cyclicPolyPatch::clone(), and cyclicPolyPatch::cyclicPolyPatch().
clone() [3/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from polyPatch.
Reimplemented in nonuniformTransformCyclicPolyPatch, and cyclicSlipPolyPatch.
Definition at line 292 of file cyclicPolyPatch.H.
References cyclicPolyPatch::cyclicPolyPatch(), cyclicPolyPatch::neighbPatchID(), cyclicPolyPatch::neighbPatchName(), and cyclicPolyPatch::~cyclicPolyPatch().
neighbPatchName()
const Foam::word & neighbPatchName () const
Neighbour patch name.
Definition at line 806 of file cyclicPolyPatch.C.
Referenced by cyclicSlipPolyPatch::clone(), nonuniformTransformCyclicPolyPatch::clone(), cyclicPolyPatch::clone(), and cyclicPolyPatch::neighbPatchID().
neighbPatchID()
Foam::label neighbPatchID () const virtual
Neighbour patchID.
Definition at line 819 of file cyclicPolyPatch.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::name(), cyclicPolyPatch::neighbPatchName(), and WarningInFunction.
Referenced by cyclicPolyPatch::clone(), cyclicFvPatch::neighbFvPatch(), cyclicFvPatch::neighbPatch(), cyclicPointPatch::neighbPatch(), cyclicPolyPatch::neighbPatch(), cyclicFvPatch::neighbPatchID(), and cyclicPolyPatch::owner().
owner()
virtual bool owner () const inline virtual
Does this side own the patch ?
Implements coupledPolyPatch.
Definition at line 318 of file cyclicPolyPatch.H.
References patchIdentifier::index(), and cyclicPolyPatch::neighbPatchID().
Referenced by cyclicPolyPatch::neighbour(), cyclicFvPatch::owner(), fvMeshDistribute::printCoupleInfo(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), and syncTools::syncPointMap().
neighbour()
virtual bool neighbour () const inline virtual
Does the coupled side own the patch ?
Reimplemented from coupledPolyPatch.
Definition at line 323 of file cyclicPolyPatch.H.
References cyclicPolyPatch::owner().
neighbPatch()
const cyclicPolyPatch& neighbPatch () const inline
Definition at line 328 of file cyclicPolyPatch.H.
References polyPatch::boundaryMesh(), cyclicPolyPatch::coupledEdges(), cyclicPolyPatch::coupledPoints(), cyclicPolyPatch::neighbPatchID(), and cyclicPolyPatch::transformPosition().
Referenced by processorCyclicPolyPatch::calcGeometry(), PointEdgeWave< Type, TrackingData >::countPatchType(), particle< Type >::hitCyclicPatch(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncPointMap(), processorCyclicPolyPatch::tag(), and cyclicPolyPatch::transformGlobalFace().
coupledPoints()
const Foam::edgeList & coupledPoints () const
Return connected points (from patch local to neighbour patch local)
Demand driven calculation. Does primitivePatch::clearOut after calculation!
Definition at line 1012 of file cyclicPolyPatch.C.
References Foam::constant::physicoChemical::b, Foam::endl(), forAll, mesh, OFstream::name(), Foam::name(), Foam::nl, nPoints, path(), points, Foam::Pout, List< T >::setSize(), List< T >::size(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by PointEdgeWave< Type, TrackingData >::countPatchType(), cyclicPolyPatch::neighbPatch(), and syncTools::syncPointMap().
coupledEdges()
const Foam::edgeList & coupledEdges () const
Return connected edges (from patch local to neighbour patch local).
Demand driven calculation. Does primitivePatch::clearOut after calculation!
Definition at line 1093 of file cyclicPolyPatch.C.
References Foam::abort(), Foam::constant::physicoChemical::b, Vector< Cmpt >::centre(), Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::erase(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), forAll, cyclicPolyPatch::initOrder(), HashTable< T, Key, Hash >::insert(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), mesh, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), Foam::constant::atomic::mp, OFstream::name(), Foam::name(), Foam::nl, path(), Foam::Pout, List< T >::size(), HashTable< T, Key, Hash >::size(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by cyclicPolyPatch::neighbPatch(), and syncTools::syncEdgeMap().
transformPosition() [1/2]
void transformPosition (pointField & l) const virtual
Transform a patch-based position from other side to this side.
Implements coupledPolyPatch.
Definition at line 854 of file cyclicPolyPatch.C.
References forAll, s(), List< T >::size(), and Foam::transform().
Referenced by particle< Type >::hitCyclicPatch(), and cyclicPolyPatch::neighbPatch().
transformPosition() [2/2]
void transformPosition (point & l, const label facei) const virtual
Transform a patch-based position from other side to this side.
Implements coupledPolyPatch.
Definition at line 890 of file cyclicPolyPatch.C.
References s(), Foam::T(), and Foam::transform().
transformGlobalFace()
label transformGlobalFace (const label facei) const inline
Definition at line 353 of file cyclicPolyPatch.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, patchIdentifier::name(), cyclicPolyPatch::neighbPatch(), and polyPatch::start().
Referenced by particle< Type >::hitCyclicPatch().
rotationAxis()
const vector& rotationAxis () const inline
Axis of rotation for rotational cyclics.
Definition at line 372 of file cyclicPolyPatch.H.
rotationCentre()
const point& rotationCentre () const inline
Point on axis of rotation for rotational cyclics.
Definition at line 378 of file cyclicPolyPatch.H.
separationVector()
const vector& separationVector () const inline
Translation vector for translational cyclics.
Definition at line 384 of file cyclicPolyPatch.H.
References Foam::faceMap(), cyclicPolyPatch::initOrder(), cyclicPolyPatch::order(), and cyclicPolyPatch::write().
initOrder()
void initOrder (PstreamBuffers & , const primitivePatch & pp) const virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Implements coupledPolyPatch.
Definition at line 1233 of file cyclicPolyPatch.C.
References cyclicPolyPatch::order(), and PrimitivePatch< Face, FaceList, PointField, PointType >::points().
Referenced by cyclicPolyPatch::coupledEdges(), and cyclicPolyPatch::separationVector().
order()
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Implements coupledPolyPatch.
Definition at line 1255 of file cyclicPolyPatch.C.
References Foam::constant::physicoChemical::c1, Foam::endl(), forAll, Foam::gAverage(), Foam::matchPoints(), mesh, OSstream::name(), Foam::name(), Foam::nl, path(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::Pout, SeriousErrorInFunction, List< T >::setSize(), Foam::transform(), and Foam::meshTools::writeOBJ().
Referenced by cyclicPolyPatch::initOrder(), and cyclicPolyPatch::separationVector().
write()
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from coupledPolyPatch.
Definition at line 1445 of file cyclicPolyPatch.C.
References token::END_STATEMENT, Foam::nl, Foam::transform(), coupledPolyPatch::write(), and Ostream::writeKeyword().
Referenced by cyclicPolyPatch::separationVector().
Friends And Related Function Documentation
processorCyclicPolyPatch
friend class processorCyclicPolyPatch friend
Declare friendship with processorCyclicPolyPatch.
Definition at line 188 of file cyclicPolyPatch.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/cyclic/cyclicPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/cyclic/cyclicPolyPatch.C