OpenFOAM: IOmapDistribute Class Reference
IOmapDistribute Class Reference
IOmapDistribute is derived from mapDistribute and IOobject to give the mapDistribute automatic IO functionality via the objectRegistry.
Public Member Functions
TypeName ("mapDistribute")
Runtime type information.
IOmapDistribute (const IOobject &)
Construct given an IOobject.
IOmapDistribute (const IOobject &, const mapDistribute &)
Construct given an IOobject and mapDistribute.
IOmapDistribute (const IOobject &, const Xfer< mapDistribute > &)
Construct by transferring the mapDistribute contents.
virtual ~IOmapDistribute ()
Destructor.
virtual bool readData (Istream &)
ReadData function required for regIOobject read operation.
virtual bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from mapDistribute
ClassName ("mapDistribute")
mapDistribute ()
Construct null.
mapDistribute (const label constructSize, const Xfer< labelListList > &subMap, const Xfer< labelListList > &constructMap, const bool subHasFlip=false, const bool constructHasFlip=false)
Construct from components.
mapDistribute (const label constructSize, const Xfer< labelListList > &subMap, const Xfer< labelListList > &constructMap, const Xfer< labelListList > &transformElements, const Xfer< labelList > &transformStart, const bool subHasFlip=false, const bool constructHasFlip=false)
Construct from components.
mapDistribute (const labelList &sendProcs, const labelList &recvProcs)
Construct from reverse addressing: per data item the send.
mapDistribute (const globalIndex &, labelList &elements, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex.
mapDistribute (const globalIndex &, labelListList &cellCells, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Special variant that works with the info sorted into bins.
mapDistribute (const globalIndex &, labelList &untransformedElements, const globalIndexAndTransform &, const labelPairList &transformedElements, labelList &transformedIndices, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly remote) untransformed elements.
mapDistribute (const globalIndex &, labelListList &cellCells, const globalIndexAndTransform &, const List< labelPairList > &transformedElements, labelListList &transformedIndices, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
As above but with ListLists.
mapDistribute (const Xfer< mapDistribute > &)
Construct by transferring parameter content.
mapDistribute (const mapDistribute &)
Construct copy.
mapDistribute (Istream &)
Construct from Istream.
autoPtr< mapDistribute > clone () const
Clone.
virtual ~mapDistribute ()
Destructor.
const labelListList & transformElements () const
For every globalIndexAndTransform::transformPermutations.
const labelList & transformStart () const
Destination in constructMap for transformed elements.
label whichTransform (const label index) const
Find transform from transformElements.
void transfer (mapDistribute &)
Transfer the contents of the argument and annul the argument.
Xfer< mapDistribute > xfer ()
Transfer contents to the Xfer container.
template<class T >
void distribute (List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T , class negateOp >
void distribute (List< T > &fld, const negateOp &negOp, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void distribute (DynamicList< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, List< T > &, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T , class TransformOp >
void distribute (const globalIndexAndTransform &, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
Distribute with transforms.
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
Reverse distribute with transforms.
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, const T &nullValue, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
Reverse distribute with transforms.
void printLayout (Ostream &os) const
Debug: print layout. Can only be used on maps with sorted.
void updateMesh (const mapPolyMesh &)
Correct for topo change.
void operator= (const mapDistribute &)
Public Member Functions inherited from mapDistributeBase
ClassName ("mapDistributeBase")
mapDistributeBase ()
Construct null.
mapDistributeBase (const label constructSize, const Xfer< labelListList > &subMap, const Xfer< labelListList > &constructMap, const bool subHasFlip=false, const bool constructHasFlip=false)
Construct from components.
mapDistributeBase (const labelList &sendProcs, const labelList &recvProcs)
Construct from reverse addressing: per data item the send.
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex.
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Special variant that works with the info sorted into bins.
mapDistributeBase (const Xfer< mapDistributeBase > &)
Construct by transferring parameter content.
mapDistributeBase (const mapDistributeBase &)
Construct copy.
mapDistributeBase (Istream &)
Construct from Istream.
label constructSize () const
Constructed data size.
label & constructSize ()
Constructed data size.
const labelListList & subMap () const
From subsetted data back to original data.
labelListList & subMap ()
From subsetted data back to original data.
const labelListList & constructMap () const
From subsetted data to new reconstructed data.
labelListList & constructMap ()
From subsetted data to new reconstructed data.
bool subHasFlip () const
Does subMap include a sign.
bool & subHasFlip ()
Does subMap include a sign.
bool constructHasFlip () const
Does constructMap include a sign.
bool & constructHasFlip ()
Does constructMap include a sign.
const List< labelPair > & schedule () const
Return a schedule. Demand driven. See above.
void transfer (mapDistributeBase &)
Transfer the contents of the argument and annul the argument.
Xfer< mapDistributeBase > xfer ()
Transfer contents to the Xfer container.
void compact (const boolList &elemIsUsed, const int tag=UPstream::msgType())
Compact maps. Gets per field a bool whether it is used (locally)
void compact (const boolList &elemIsUsed, const label localSize, labelList &oldToNewSub, labelList &oldToNewConstruct, const int tag=UPstream::msgType())
Compact all maps and layout. Returns compaction maps for.
template<class T >
void distribute (List< T > &fld, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T , class negateOp >
void distribute (List< T > &fld, const negateOp &negOp, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void distribute (DynamicList< T > &fld, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, List< T > &, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &fld, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void send (PstreamBuffers &, const List< T > &) const
Do all sends using PstreamBuffers.
template<class T >
void receive (PstreamBuffers &, List< T > &) const
Do all receives using PstreamBuffers.
void printLayout (Ostream &os) const
Debug: print layout. Can only be used on maps with sorted.
void updateMesh (const mapPolyMesh &)
Correct for topo change.
void operator= (const mapDistributeBase &)
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from mapDistributeBase
static List< labelPair > schedule (const labelListList &subMap, const labelListList &constructMap, const int tag)
Calculate a schedule. See above.
static label renumber (const globalIndex &, const List< Map< label >> &compactMap, const label globalElement)
Helper for construct from globalIndex. Renumbers element.
template<class T , class negateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &, const negateOp &negOp, const int tag=UPstream::msgType())
Distribute data. Note:schedule only used for Pstream::scheduled.
template<class T , class CombineOp , class negateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &, const CombineOp &cop, const negateOp &negOp, const T &nullValue, const int tag=UPstream::msgType())
Distribute data. If multiple processors writing to same.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from mapDistributeBase
void calcCompactAddressing (const globalIndex &globalNumbering, const labelList &elements, List< Map< label >> &compactMap) const
Construct per processor compact addressing of the global elements.
void calcCompactAddressing (const globalIndex &globalNumbering, const labelListList &elements, List< Map< label >> &compactMap) const
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelList &elements, List< Map< label >> &compactMap, labelList &compactStart)
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelListList &elements, List< Map< label >> &compactMap, labelList &compactStart)
Static Protected Member Functions inherited from mapDistributeBase
static void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize)
template<class T , class CombineOp , class negateOp >
static void flipAndCombine (const UList< label > &map, const bool hasFlip, const UList< T > &rhs, const CombineOp &cop, const negateOp &negOp, List< T > &lhs)
template<class T , class negateOp >
static T accessAndFlip (const UList< T > &fld, const label index, const bool hasFlip, const negateOp &negOp)
Protected Attributes inherited from mapDistributeBase
label constructSize_
Size of reconstructed data.
labelListList subMap_
Maps from subsetted data back to original data.
labelListList constructMap_
Maps from subsetted data to new reconstructed data.
bool subHasFlip_
Whether subMap includes flip or not.
bool constructHasFlip_
Whether constructMap includes flip or not.
autoPtr< List< labelPair > > schedulePtr_
Schedule.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
IOmapDistribute is derived from mapDistribute and IOobject to give the mapDistribute automatic IO functionality via the objectRegistry.
Source files
IOmapDistribute.H
IOmapDistribute.C
Definition at line 51 of file IOmapDistribute.H.
Constructor & Destructor Documentation
IOmapDistribute() [1/3]
IOmapDistribute (const IOobject & io)
Construct given an IOobject.
Definition at line 38 of file IOmapDistribute.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, IOobject::name(), IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), and WarningInFunction.
Referenced by IOmapDistribute::IOmapDistribute().
IOmapDistribute() [2/3]
IOmapDistribute (const IOobject & io, const mapDistribute & map)
Construct given an IOobject and mapDistribute.
Definition at line 68 of file IOmapDistribute.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOmapDistribute::IOmapDistribute(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, IOobject::name(), mapDistribute::operator=(), IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), and WarningInFunction.
IOmapDistribute() [3/3]
IOmapDistribute (const IOobject & io, const Xfer< mapDistribute > & map)
Construct by transferring the mapDistribute contents.
Definition at line 105 of file IOmapDistribute.C.
References regIOobject::close(), Foam::endl(), IOobject::headerOk(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, IOobject::name(), IOobject::READ_IF_PRESENT, IOobject::readOpt(), regIOobject::readStream(), mapDistribute::transfer(), and WarningInFunction.
~IOmapDistribute()
~IOmapDistribute () virtual
Destructor.
Definition at line 141 of file IOmapDistribute.C.
Member Function Documentation
TypeName()
TypeName ("mapDistribute")
Runtime type information.
readData()
bool readData (Istream & is) virtual
ReadData function required for regIOobject read operation.
Reimplemented from regIOobject.
Definition at line 147 of file IOmapDistribute.C.
writeData()
bool writeData (Ostream & os) const virtual
WriteData function required for regIOobject write operation.
Implements regIOobject.
Definition at line 153 of file IOmapDistribute.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/IOmapDistribute.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/IOmapDistribute.C