OpenFOAM: polyBoundaryMesh Class Reference
polyBoundaryMesh Class Reference
Foam::polyBoundaryMesh.
Public Member Functions
TypeName ("polyBoundaryMesh")
Runtime type information.
polyBoundaryMesh (const IOobject &, const polyMesh &)
Read constructor given IOobject and a polyMesh reference.
polyBoundaryMesh (const IOobject &, const polyMesh &, const label size)
Construct given size.
polyBoundaryMesh (const IOobject &, const polyMesh &, const polyPatchList &)
Construct given polyPatchList.
~polyBoundaryMesh ()
Destructor.
void clearGeom ()
Clear geometry at this level and at patches.
void clearAddressing ()
Clear addressing at this level and at patches.
const polyMesh & mesh () const
Return the mesh reference.
const List< labelPairList > & neighbourEdges () const
Per patch the edges on the neighbouring patch. Is for every external.
wordList names () const
Return a list of patch names.
wordList types () const
Return a list of patch types.
wordList physicalTypes () const
Return a list of physical types.
labelList findIndices (const keyType &, const bool usePatchGroups=true) const
Return patch indices for all matches. Optionally matches patchGroups.
label findIndex (const keyType &) const
Return patch index for the first match, return -1 if not found.
label findPatchID (const word &patchName) const
Find patch index given a name.
template<class Type >
labelHashSet findPatchIDs () const
Find patch indices for a given polyPatch type.
label whichPatch (const label faceIndex) const
Return patch index for a given face label.
const labelList & patchID () const
Per boundary face label the patch index.
const HashTable< labelList, word > & groupPatchIDs () const
Per patch group the patch indices.
void setGroup (const word &groupName, const labelList &patchIDs)
Set/add group with patches.
labelHashSet patchSet (const UList< wordRe > &patchNames, const bool warnNotFound=true, const bool usePatchGroups=true) const
Return the set of patch IDs corresponding to the given names.
void matchGroups (const labelUList &patchIDs, wordList &groups, labelHashSet &nonGroupPatches) const
Match the patches to groups. Returns all the (fully matched) groups.
bool checkParallelSync (const bool report=false) const
Check whether all procs have all patches and in same order. Return.
bool checkDefinition (const bool report=false) const
Check boundary definition. Return true if in error.
void movePoints (const pointField &)
Correct polyBoundaryMesh after moving points.
void updateMesh ()
Correct polyBoundaryMesh after topology update.
void reorder (const labelUList &, const bool validBoundary)
Reorders patches. Ordering does not have to be done in.
bool writeData (Ostream &) const
writeData member function required by regIOobject
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write using given format, version and form uncompression.
const polyPatch & operator[] (const word &) const
Return const reference to polyPatch by name.
polyPatch & operator[] (const word &)
Return reference to polyPatch by name.
template<class Type >
Foam::labelHashSet findPatchIDs () const
Public Member Functions inherited from PtrList< T >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< T > &)
Copy constructor.
template<class CloneArg >
PtrList (const PtrList< T > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< T >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &)
Construct as copy of SLPtrList<T>
template<class INew >
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (T *)
Append an element at the end of the list.
void append (const autoPtr< T > &)
void append (const tmp< T > &)
void transfer (PtrList< T > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< T > set (const label, T *)
Set element to given T* and return old element (can be nullptr)
autoPtr< T > set (const label, const autoPtr< T > &)
Set element to given autoPtr<T> and return old element.
autoPtr< T > set (const label, const tmp< T > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< T > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Friends
class polyMesh
Declare friendship with polyMesh.
Ostream & operator<< (Ostream &, const polyBoundaryMesh &)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from PtrList< T >
template<class INew >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Foam::polyBoundaryMesh.
Source files
polyBoundaryMesh.H
polyBoundaryMesh.C
Definition at line 60 of file polyBoundaryMesh.H.
Constructor & Destructor Documentation
polyBoundaryMesh() [1/3]
polyBoundaryMesh (const IOobject & io, const polyMesh & mesh)
Read constructor given IOobject and a polyMesh reference.
Note point pointers are unset, only used in copying meshes
Definition at line 47 of file polyBoundaryMesh.C.
References IOstream::check(), dict, Foam::endl(), forAll, IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, polyPatch::New(), patches, patchi, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), and WarningInFunction.
polyBoundaryMesh() [2/3]
polyBoundaryMesh (const IOobject & io, const polyMesh & pm, const label size)
Construct given size.
Definition at line 107 of file polyBoundaryMesh.C.
polyBoundaryMesh() [3/3]
polyBoundaryMesh (const IOobject & io, const polyMesh & pm, const polyPatchList & ppl)
Construct given polyPatchList.
Definition at line 120 of file polyBoundaryMesh.C.
References IOstream::check(), dict, Foam::endl(), forAll, IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, polyPatch::New(), patches, patchi, IOobject::READ_IF_PRESENT, PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), and WarningInFunction.
~polyBoundaryMesh()
~polyBoundaryMesh ()
Destructor.
Definition at line 192 of file polyBoundaryMesh.C.
Member Function Documentation
TypeName()
TypeName ("polyBoundaryMesh")
Runtime type information.
clearGeom()
void clearGeom ()
Clear geometry at this level and at patches.
Definition at line 196 of file polyBoundaryMesh.C.
References forAll, and patchi.
Referenced by polyMesh::clearGeom().
clearAddressing()
void clearAddressing ()
Clear addressing at this level and at patches.
Definition at line 205 of file polyBoundaryMesh.C.
References UPstream::blocking, UPstream::defaultCommsType, PstreamBuffers::finishedSends(), forAll, polyMesh::globalData(), mesh, UPstream::nonBlocking, patchi, ProcessorTopology< Container, ProcPatch >::patchSchedule(), and UPstream::scheduled.
mesh()
const polyMesh& mesh () const inline
Return the mesh reference.
Definition at line 140 of file polyBoundaryMesh.H.
References polyBoundaryMesh::checkDefinition(), polyBoundaryMesh::checkParallelSync(), polyBoundaryMesh::findIndex(), polyBoundaryMesh::findIndices(), polyBoundaryMesh::findPatchID(), polyBoundaryMesh::findPatchIDs(), IOobject::groupName(), polyBoundaryMesh::groupPatchIDs(), polyBoundaryMesh::matchGroups(), polyBoundaryMesh::movePoints(), polyBoundaryMesh::names(), polyBoundaryMesh::neighbourEdges(), UPtrList< T >::operator, polyBoundaryMesh::operator<<, polyBoundaryMesh::operator[](), polyBoundaryMesh::patchID(), patchNames(), polyBoundaryMesh::patchSet(), polyBoundaryMesh::physicalTypes(), polyBoundaryMesh::reorder(), polyBoundaryMesh::setGroup(), polyBoundaryMesh::types(), polyBoundaryMesh::updateMesh(), polyBoundaryMesh::whichPatch(), polyBoundaryMesh::writeData(), and polyBoundaryMesh::writeObject().
Referenced by timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), processorPolyPatch::comm(), patchPatchDist::correct(), polyPatch::faceCellCentres(), mappedPatchBase::facePoints(), coupleGroupIdentifier::findOtherPatchID(), interpolationCellPatchConstrained< Type >::interpolate(), temperatureCoupledBase::kappa(), mappedPatchFieldBase< Type >::mappedField(), MeshedSurface< Foam::face >::MeshedSurface(), regionCoupledBase::neighbPatch(), regionCoupledBase::neighbPatchID(), thermalBaffleFvPatchScalarField::rmap(), mappedPatchFieldBase< Type >::sampleField(), mappedPatchBase::sampleMesh(), mappedPatchBase::samplePatch(), mappedPatchBase::sampleRegion(), regionCoupledBase::surfPtr(), mappedPatchBase::surfPtr(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), thermalBaffleFvPatchScalarField::updateCoeffs(), and thermalBaffleFvPatchScalarField::write().
neighbourEdges()
const Foam::List< Foam::labelPairList > & neighbourEdges () const
Per patch the edges on the neighbouring patch. Is for every external.
edge the neighbouring patch and neighbouring (external) patch edge label. Note that edge indices are offset by nInternalEdges to keep it as much as possible consistent with coupled patch addressing (where coupling is by local patch face index). Only valid for singly connected polyBoundaryMesh and not parallel
Definition at line 267 of file polyBoundaryMesh.C.
References Foam::abort(), Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::erase(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), forAll, HashTable< T, Key, Hash >::insert(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), patchIdentifier::name(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::nInternalEdges(), Foam::nl, UPstream::parRun(), patchi, List< T >::setSize(), List< T >::size(), HashTable< T, Key, Hash >::size(), and WarningInFunction.
Referenced by polyBoundaryMesh::mesh().
names()
Foam::wordList names () const
Return a list of patch names.
Definition at line 531 of file polyBoundaryMesh.C.
References forAll, patches, patchi, and UPtrList< T >::size().
Referenced by curvatureSeparation::curvatureSeparation(), fvMeshDistribute::distribute(), meshToMesh::interpolationMethodAMI(), layerParameters::layerParameters(), polyBoundaryMesh::mesh(), meshRefinement::meshedPatches(), regionCoupledBase::neighbPatchID(), patchInjectionBase::patchInjectionBase(), patchInteractionDataList::patchInteractionDataList(), blockMesh::patchNames(), fvMeshDistribute::printCoupleInfo(), polyMesh::readUpdate(), processorCyclicPolyPatch::referPatchID(), sampledCuttingPlane::sampledCuttingPlane(), sampledIsoSurface::sampledIsoSurface(), mappedPatchBase::samplePolyPatch(), and fvMeshSubset::setLargeCellSubset().
types()
Foam::wordList types () const
Return a list of patch types.
Definition at line 546 of file polyBoundaryMesh.C.
References forAll, patches, patchi, and UPtrList< T >::size().
Referenced by polyBoundaryMesh::mesh(), and polyMesh::readUpdate().
physicalTypes()
Foam::wordList physicalTypes () const
Return a list of physical types.
Definition at line 561 of file polyBoundaryMesh.C.
References polyBoundaryMesh::findIndices(), forAll, patches, patchi, and UPtrList< T >::size().
Referenced by polyBoundaryMesh::mesh().
findIndices()
Foam::labelList findIndices (const keyType & key, const bool usePatchGroups = true) const
Return patch indices for all matches. Optionally matches patchGroups.
Definition at line 577 of file polyBoundaryMesh.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::findStrings(), forAll, HashSet< Key, Hash >::insert(), keyType::isPattern(), Foam::name(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity().
Referenced by fvBoundaryMesh::findIndices(), polyBoundaryMesh::mesh(), processorCyclicPolyPatch::patchIDs(), and polyBoundaryMesh::physicalTypes().
findIndex()
Foam::label findIndex (const keyType & key) const
Return patch index for the first match, return -1 if not found.
Definition at line 651 of file polyBoundaryMesh.C.
References UList< T >::empty(), Foam::findIndices(), forAll, keyType::isPattern(), and Foam::name().
Referenced by polyBoundaryMesh::mesh().
findPatchID()
Foam::label findPatchID (const word & patchName) const
Find patch index given a name.
Definition at line 682 of file polyBoundaryMesh.C.
References Foam::endl(), forAll, Foam::name(), patches, patchi, and Foam::Pout.
Referenced by fvMeshTools::addPatch(), meshRefinement::addPatch(), inverseFaceDistanceDiffusivity::correct(), directions::directions(), patchProbes::findElements(), meshToMesh::interpolationMethodAMI(), mappedPatchFieldBase< Type >::mappedField(), polyBoundaryMesh::mesh(), meshRefinement::meshedPatches(), regionCoupledBase::neighbPatchID(), processorCyclicPolyPatch::referPatchID(), sampledCuttingPlane::sampledCuttingPlane(), sampledIsoSurface::sampledIsoSurface(), mappedPatchBase::samplePolyPatch(), fvMeshSubset::setCellSubset(), fvMeshSubset::setLargeCellSubset(), and outletMappedUniformInletFvPatchField< Type >::updateCoeffs().
findPatchIDs() [1/2]
labelHashSet findPatchIDs () const
Find patch indices for a given polyPatch type.
Referenced by polyBoundaryMesh::mesh().
whichPatch()
Foam::label whichPatch (const label faceIndex) const
Return patch index for a given face label.
Definition at line 707 of file polyBoundaryMesh.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, mesh, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, patchi, polyBoundaryMesh::patchSet(), and polyPatch::start().
Referenced by meshRefinement::balance(), addPatchCellLayer::calcSidePatch(), cellPointWeightWallModified::cellPointWeightWallModified(), repatchPolyTopoChanger::changeAnchorPoint(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), meshRefinement::createBaffles(), meshRefinement::createZoneBaffles(), localPointRegion::findDuplicateFacePairs(), patchProbes::findElements(), interpolationCellPointWallModified< Type >::interpolate(), meshRefinement::mergeBaffles(), polyMeshAdder::mergePoints(), polyBoundaryMesh::mesh(), meshTriangulation::meshTriangulation(), Cloud< streamLineParticle >::move(), particle< Type >::patch(), patchProbes::sample(), fvMeshSubset::setCellSubset(), repatchPolyTopoChanger::setFaceZone(), duplicatePoints::setRefinement(), perfectInterface::setRefinement(), combineFaces::setRefinement(), tetDecomposer::setRefinement(), removeFaces::setRefinement(), meshCutAndRemove::setRefinement(), edgeCollapser::setRefinement(), addPatchCellLayer::setRefinement(), fvMatrix< Type >::setValuesFromList(), and Implicit< CloudType >::velocityCorrection().
patchID()
const Foam::labelList & patchID () const
Per boundary face label the patch index.
Definition at line 399 of file polyBoundaryMesh.C.
References forAll, and patchi.
Referenced by polyMeshTetDecomposition::checkFaceTets(), FacePostProcessing< CloudType >::FacePostProcessing(), polyMeshTetDecomposition::findFaceBasePts(), particle< Type >::hitWallFaces(), interpolationCellPatchConstrained< Type >::interpolate(), polyBoundaryMesh::mesh(), listPlusEqOp< T >::operator()(), snappyRefineDriver::snappyRefineDriver(), and particle< Type >::trackToFace().
groupPatchIDs()
const Foam::HashTable< Foam::labelList, Foam::word > & groupPatchIDs () const
Per patch group the patch indices.
Definition at line 429 of file polyBoundaryMesh.C.
References HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::erase(), HashTable< T, Key, Hash >::find(), forAll, HashTable< T, Key, Hash >::insert(), Foam::name(), IOobject::name(), patchi, polyBoundaryMesh::setGroup(), and WarningInFunction.
Referenced by polyBoundaryMesh::mesh().
setGroup()
void setGroup (const word & groupName, const labelList & patchIDs)
Set/add group with patches.
Definition at line 481 of file polyBoundaryMesh.C.
References List< T >::append(), forAll, patchIdentifier::inGroup(), patchIdentifier::inGroups(), patches, patchi, List< T >::setSize(), and UPtrList< T >::size().
Referenced by polyBoundaryMesh::groupPatchIDs(), and polyBoundaryMesh::mesh().
patchSet()
Foam::labelHashSet patchSet (const UList< wordRe > & patchNames, const bool warnNotFound = true, const bool usePatchGroups = true) const
Return the set of patch IDs corresponding to the given names.
By default warns if given names are not found. Optionally matches to patchGroups as well as patchNames
Definition at line 754 of file polyBoundaryMesh.C.
References UList< T >::empty(), Foam::endl(), Foam::findStrings(), forAll, HashSet< Key, Hash >::insert(), polyBoundaryMesh::matchGroups(), Foam::name(), and WarningInFunction.
Referenced by preservePatchesConstraint::add(), preservePatchesConstraint::apply(), inversePointDistanceDiffusivity::correct(), structuredDecomp::decompose(), cellDistFuncs::getPatchIDs(), layerParameters::layerParameters(), polyBoundaryMesh::mesh(), sampledPatch::patchIDs(), patchInjection::patchInjection(), wallHeatFlux::read(), wallShearStress::read(), forces::read(), structuredRenumber::renumber(), and polyBoundaryMesh::whichPatch().
matchGroups()
void matchGroups (const labelUList & patchIDs, wordList & groups, labelHashSet & nonGroupPatches) const
Match the patches to groups. Returns all the (fully matched) groups.
and any remaining unmatched patches.
Definition at line 818 of file polyBoundaryMesh.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), HashTable< T, Key, Hash >::begin(), HashTableCore::end(), HashTable< T, Key, Hash >::erase(), HashTable< T, Key, Hash >::size(), List< T >::transfer(), and HashTable< T, Key, Hash >::transfer().
Referenced by polyBoundaryMesh::mesh(), and polyBoundaryMesh::patchSet().
checkParallelSync()
bool checkParallelSync (const bool report = false) const
Check whether all procs have all patches and in same order. Return.
true if in error.
Definition at line 863 of file polyBoundaryMesh.C.
References Foam::endl(), forAll, Pstream::gatherList(), Foam::Info, UPstream::master(), UPstream::myProcNo(), IOobject::name(), UPstream::nProcs(), UPstream::parRun(), patchi, Foam::Pout, Pstream::scatterList(), PtrList< T >::setSize(), List< T >::size(), and UPtrList< T >::size().
Referenced by fvMeshDistribute::distribute(), and polyBoundaryMesh::mesh().
checkDefinition()
bool checkDefinition (const bool report = false) const
Check boundary definition. Return true if in error.
Definition at line 950 of file polyBoundaryMesh.C.
References Foam::endl(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), mesh, IOobject::name(), primitiveMesh::nInternalFaces(), patchi, patchNames(), Foam::Pout, Foam::reduce(), and UPtrList< T >::size().
Referenced by polyMesh::addPatches(), and polyBoundaryMesh::mesh().
movePoints()
void movePoints (const pointField & p)
Correct polyBoundaryMesh after moving points.
Definition at line 1007 of file polyBoundaryMesh.C.
References UPstream::blocking, UPstream::defaultCommsType, PstreamBuffers::finishedSends(), forAll, polyMesh::globalData(), mesh, UPstream::nonBlocking, patchi, ProcessorTopology< Container, ProcPatch >::patchSchedule(), and UPstream::scheduled.
Referenced by polyBoundaryMesh::mesh(), and polyMesh::movePoints().
updateMesh()
void updateMesh ()
Correct polyBoundaryMesh after topology update.
Definition at line 1053 of file polyBoundaryMesh.C.
References UPstream::blocking, UPstream::defaultCommsType, PstreamBuffers::finishedSends(), forAll, polyMesh::globalData(), mesh, UPstream::nonBlocking, patchi, ProcessorTopology< Container, ProcPatch >::patchSchedule(), polyBoundaryMesh::reorder(), and UPstream::scheduled.
Referenced by polyMesh::addPatches(), polyBoundaryMesh::mesh(), polyMesh::polyMesh(), polyMesh::readUpdate(), polyMesh::resetPrimitives(), and polyMesh::updateMesh().
reorder()
void reorder (const labelUList & oldToNew, const bool validBoundary)
Reorders patches. Ordering does not have to be done in.
ascending or descending order. Reordering has to be unique. (is shuffle) If validBoundary calls updateMesh() after reordering to recalculate data (so call needs to be parallel sync in that case)
Definition at line 1104 of file polyBoundaryMesh.C.
References forAll, patches, patchi, and PtrList< T >::reorder().
Referenced by fvMeshTools::addPatch(), meshRefinement::addPatch(), polyBoundaryMesh::mesh(), fvMeshTools::reorderPatches(), and polyBoundaryMesh::updateMesh().
writeData()
bool writeData (Ostream & os) const virtual
writeData member function required by regIOobject
Implements regIOobject.
Definition at line 1127 of file polyBoundaryMesh.C.
References token::BEGIN_BLOCK, token::BEGIN_LIST, IOstream::check(), Foam::decrIndent(), token::END_BLOCK, token::END_LIST, Foam::endl(), forAll, IOstream::good(), Foam::incrIndent(), Foam::indent(), Foam::nl, patches, patchi, UPtrList< T >::size(), and polyBoundaryMesh::writeObject().
Referenced by polyBoundaryMesh::mesh(), and Foam::operator<<().
writeObject()
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const virtual
Write using given format, version and form uncompression.
Reimplemented from regIOobject.
Definition at line 1151 of file polyBoundaryMesh.C.
References UPtrList< T >::operator, IOstream::UNCOMPRESSED, and regIOobject::writeObject().
Referenced by polyBoundaryMesh::mesh(), and polyBoundaryMesh::writeData().
operator[]() [1/2]
const Foam::polyPatch & operator[] (const word & patchName) const
Return const reference to polyPatch by name.
Definition at line 1163 of file polyBoundaryMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::nl, UPtrList< T >::operator, and patchi.
Referenced by polyBoundaryMesh::mesh().
operator[]() [2/2]
Foam::polyPatch & operator[] (const word & patchName)
Return reference to polyPatch by name.
Definition at line 1182 of file polyBoundaryMesh.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and patchi.
findPatchIDs() [2/2]
Foam::labelHashSet findPatchIDs () const
Definition at line 29 of file polyBoundaryMeshTemplates.C.
References forAll, patchi, and UPtrList< T >::size().
Friends And Related Function Documentation
polyMesh
friend class polyMesh friend
Declare friendship with polyMesh.
Definition at line 93 of file polyBoundaryMesh.H.
operator<<
Ostream& operator<< (Ostream & , const polyBoundaryMesh &) friend
Referenced by polyBoundaryMesh::mesh().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyBoundaryMesh/polyBoundaryMesh.H
src/OpenFOAM/meshes/polyMesh/polyBoundaryMesh/polyBoundaryMesh.C
src/OpenFOAM/meshes/polyMesh/polyBoundaryMesh/polyBoundaryMeshTemplates.C