OpenFOAM: mapDistribute::transformPosition Class Reference
mapDistribute::transformPosition Class Reference
Default transformation behaviour for position.
Public Member Functions
void operator() (const vectorTensorTransform &vt, const bool forward, List< point > &fld) const
void operator() (const vectorTensorTransform &vt, const bool forward, List< List< point >> &flds) const
void operator() (const coupledPolyPatch &cpp, pointField &fld) const
Transform patch-based field.
template<template< class > class Container>
void operator() (const coupledPolyPatch &cpp, Container< point > &map) const
Detailed Description
Default transformation behaviour for position.
Definition at line 257 of file mapDistribute.H.
Member Function Documentation
operator()() [1/4]
void operator() (const vectorTensorTransform & vt, const bool forward, List< point > & fld) const inline
Definition at line 262 of file mapDistribute.H.
References fld(), vectorTensorTransform::invTransformPosition(), and vectorTensorTransform::transformPosition().
operator()() [2/4]
void operator() (const vectorTensorTransform & vt, const bool forward, List< List< point >> & flds) const inline
Definition at line 279 of file mapDistribute.H.
References forAll, and mapDistribute::transform::operator()().
operator()() [3/4]
void operator() (const coupledPolyPatch & cpp, pointField & fld) const inline
Transform patch-based field.
Definition at line 291 of file mapDistribute.H.
References coupledPolyPatch::transformPosition().
operator()() [4/4]
void operator() (const coupledPolyPatch & cpp, Container< point > & map) const inline
Definition at line 296 of file mapDistribute.H.
References mapDistribute::ClassName(), mapDistribute::clone(), mapDistributeBase::constructHasFlip(), mapDistributeBase::constructMap(), mapDistributeBase::constructSize(), fld(), forAllConstIter(), forAllIter, mapDistribute::mapDistribute(), UPstream::msgType(), mapDistributeBase::subHasFlip(), mapDistributeBase::subMap(), mapDistribute::transformElements(), coupledPolyPatch::transformPosition(), and mapDistribute::transformStart().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H