OpenFOAM: coupledPolyPatch Class Reference
coupledPolyPatch Class Reference abstract
The coupledPolyPatch is an abstract base class for patches that couple regions of the computational domain e.g. cyclic and processor-processor links.
Public Types
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Public Member Functions
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
virtual bool coupled () const
Return true because this patch is coupled.
virtual bool owner () const =0
Does this side own the patch ?
virtual bool neighbour () const
Does the coupled side own the patch ?
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual void transformPosition (pointField &) const =0
Transform a patch-based position from other side to this side.
virtual void transformPosition (point &, const label facei) const =0
Transform a patch-based position from other side to this side.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
scalar matchTolerance () const
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)=0
Calculate the patch geometry.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const =0
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const =0
Return new ordering for primitivePatch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Static Public Member Functions
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes
static const NamedEnum< transformType, 5 > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Protected Member Functions
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
virtual void initGeometry (PstreamBuffers &)=0
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)=0
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)=0
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)=0
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)=0
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)=0
Update of the patch topology.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Static Protected Member Functions
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Detailed Description
The coupledPolyPatch is an abstract base class for patches that couple regions of the computational domain e.g. cyclic and processor-processor links.
Source files
coupledPolyPatch.H
coupledPolyPatch.C
Definition at line 51 of file coupledPolyPatch.H.
Member Enumeration Documentation
transformType
enum transformType
Enumerator
UNKNOWN
ROTATIONAL
TRANSLATIONAL
COINCIDENTFULLMATCH
NOORDERING
Definition at line 57 of file coupledPolyPatch.H.
Constructor & Destructor Documentation
coupledPolyPatch() [1/5]
coupledPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform)
Construct from components.
Definition at line 474 of file coupledPolyPatch.C.
Referenced by coupledPolyPatch::calcTransformTensors(), and coupledPolyPatch::coupledPolyPatch().
coupledPolyPatch() [2/5]
coupledPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 491 of file coupledPolyPatch.C.
References coupledPolyPatch::coupledPolyPatch().
coupledPolyPatch() [3/5]
coupledPolyPatch (const coupledPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 511 of file coupledPolyPatch.C.
References coupledPolyPatch::coupledPolyPatch().
coupledPolyPatch() [4/5]
coupledPolyPatch (const coupledPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 523 of file coupledPolyPatch.C.
References coupledPolyPatch::coupledPolyPatch().
coupledPolyPatch() [5/5]
coupledPolyPatch (const coupledPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 538 of file coupledPolyPatch.C.
~coupledPolyPatch()
~coupledPolyPatch () virtual
Destructor.
Definition at line 554 of file coupledPolyPatch.C.
Member Function Documentation
calcTransformTensors()
void calcTransformTensors (const vectorField & Cf, const vectorField & Cr, const vectorField & nf, const vectorField & nr, const scalarField & smallDist, const scalar absTol, const transformType transform = UNKNOWN) const protected
Calculate the transformation tensors.
smallDist : matching distance per face absTol : absolute error in normal if transformType = unknown it first tries rotational, then translational transform
Definition at line 293 of file coupledPolyPatch.C.
References coupledPolyPatch::coupledPolyPatch(), Foam::endl(), forAll, Foam::mag(), Foam::magSqr(), Foam::max(), Foam::min(), Foam::name(), Foam::nl, Foam::Pout, Foam::rotationTensor(), List< T >::setSize(), List< T >::size(), Foam::sqr(), Foam::sqrt(), Foam::sum(), and Foam::transform().
Referenced by coupledPolyPatch::getRotation().
initGeometry()
virtual void initGeometry (PstreamBuffers &) protected pure virtual
Initialise the calculation of the patch geometry.
Reimplemented from polyPatch.
Implemented in oldCyclicPolyPatch, cyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
calcGeometry() [1/2]
virtual void calcGeometry (PstreamBuffers &) protected pure virtual
Calculate the patch geometry.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
Referenced by processorCyclicPolyPatch::calcGeometry(), and coupledPolyPatch::matchTolerance().
initMovePoints()
virtual void initMovePoints (PstreamBuffers & , const pointField &) protected pure virtual
Initialise the patches for moving points.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
movePoints()
virtual void movePoints (PstreamBuffers & , const pointField &) protected pure virtual
Correct patches after moving points.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
initUpdateMesh()
virtual void initUpdateMesh (PstreamBuffers &) protected pure virtual
Initialise the update of the patch topology.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
updateMesh()
virtual void updateMesh (PstreamBuffers &) protected pure virtual
Update of the patch topology.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
writeOBJ() [1/4]
void writeOBJ (Ostream & os, const point & pt) static protected
Write point in OBJ format.
Definition at line 56 of file coupledPolyPatch.C.
References Foam::endl(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by coupledPolyPatch::writeOBJ().
writeOBJ() [2/4]
void writeOBJ (Ostream & os, const pointField & points, const labelList & pointLabels) static protected
Write selected points in OBJ format.
Definition at line 63 of file coupledPolyPatch.C.
References forAll, Foam::meshTools::writeOBJ(), and coupledPolyPatch::writeOBJ().
writeOBJ() [3/4]
void writeOBJ (const fileName & fName, const UList< face > & faces, const pointField & points) static protected
Write patch.
Definition at line 95 of file coupledPolyPatch.C.
References f(), forAll, coupledPolyPatch::getAnchorPoints(), Foam::nl, UList< T >::size(), and Foam::meshTools::writeOBJ().
writeOBJ() [4/4]
void writeOBJ (Ostream & os, const point & p0, const point & p1, label & vertI) static protected
Write edge in OBJ format.
Definition at line 77 of file coupledPolyPatch.C.
References Foam::nl, Foam::meshTools::writeOBJ(), and coupledPolyPatch::writeOBJ().
getAnchorPoints()
Foam::pointField getAnchorPoints (const UList< face > & faces, const pointField & points, const transformType transform) static protected
Get a unique anchor point for all faces.
Definition at line 131 of file coupledPolyPatch.C.
References coupledPolyPatch::calcFaceTol(), f(), forAll, and UList< T >::size().
Referenced by coupledPolyPatch::writeOBJ().
getRotation()
Foam::label getRotation (const pointField & points, const face & f, const point & anchor, const scalar tol) static protected
Get the number of vertices face f needs to be rotated such that.
its f[0] point aligns with given anchor (within tol).
Definition at line 239 of file coupledPolyPatch.C.
References coupledPolyPatch::calcTransformTensors(), Foam::endl(), f(), forAll, Foam::magSqr(), Foam::nl, points, List< T >::size(), Foam::sqrt(), and WarningInFunction.
Referenced by coupledPolyPatch::calcFaceTol().
TypeName()
TypeName ("coupled")
Runtime type information.
coupled()
virtual bool coupled () const inline virtual
Return true because this patch is coupled.
Reimplemented from polyPatch.
Reimplemented in cyclicAMIPolyPatch, and processorPolyPatch.
Definition at line 241 of file coupledPolyPatch.H.
References coupledPolyPatch::owner().
Referenced by coupledFvPatch::coupled().
owner()
virtual bool owner () const pure virtual
Does this side own the patch ?
Implemented in cyclicPolyPatch, processorCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, and oldCyclicPolyPatch.
Referenced by coupledPolyPatch::coupled(), polyMeshTetDecomposition::findFaceBasePts(), syncTools::getMasterFaces(), coupledPolyPatch::neighbour(), and processorCyclicPolyPatch::owner().
neighbour()
virtual bool neighbour () const inline virtual
Does the coupled side own the patch ?
Reimplemented in cyclicPolyPatch, and processorPolyPatch.
Definition at line 250 of file coupledPolyPatch.H.
References coupledPolyPatch::owner().
transform() [1/2]
virtual transformType transform () const inline virtual
Type of transform.
Reimplemented in processorCyclicPolyPatch.
Definition at line 256 of file coupledPolyPatch.H.
References coupledPolyPatch::transformPosition().
Referenced by processorPolyPatch::calcGeometry(), fvMeshDistribute::printCoupleInfo(), and processorCyclicPolyPatch::transform().
transform() [2/2]
virtual transformType& transform () inline virtual
Type of transform.
This is currently only for use when collapsing generated meshes that can have zero area faces.
Reimplemented in processorCyclicPolyPatch.
Definition at line 264 of file coupledPolyPatch.H.
transformPosition() [1/2]
virtual void transformPosition (pointField &) const pure virtual
Transform a patch-based position from other side to this side.
Implemented in cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicAMIPolyPatch, and oldCyclicPolyPatch.
Referenced by particle< Type >::correctAfterParallelTransfer(), mapDistribute::transformPosition::operator()(), coupledPolyPatch::transform(), and processorCyclicPolyPatch::transformPosition().
transformPosition() [2/2]
virtual void transformPosition (point & , const label facei) const pure virtual
Transform a patch-based position from other side to this side.
Implemented in cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicAMIPolyPatch, and oldCyclicPolyPatch.
separated()
virtual bool separated () const inline virtual
Are the planes separated.
Reimplemented in processorCyclicPolyPatch.
Definition at line 276 of file coupledPolyPatch.H.
References List< T >::size().
Referenced by particle< Type >::correctAfterParallelTransfer(), extendedCellToCellStencil::extendedCellToCellStencil(), extendedCellToFaceStencil::extendedCellToFaceStencil(), extendedFaceToCellStencil::extendedFaceToCellStencil(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), motionSmootherAlgo::scaleMesh(), meshRefinement::selectSeparatedCoupledFaces(), and processorCyclicPolyPatch::separated().
separation()
virtual const vectorField& separation () const inline virtual
If the planes are separated the separation vector.
Reimplemented in processorCyclicPolyPatch.
Definition at line 282 of file coupledPolyPatch.H.
Referenced by particle< Type >::correctAfterParallelTransfer(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), and processorCyclicPolyPatch::separation().
parallel()
virtual bool parallel () const inline virtual
Are the cyclic planes parallel.
Reimplemented in processorCyclicPolyPatch.
Definition at line 288 of file coupledPolyPatch.H.
References UList< T >::empty().
Referenced by particle< Type >::correctAfterParallelTransfer(), PointEdgeWave< Type, TrackingData >::countPatchType(), processorPointPatchField< Type >::doTransform(), processorCyclicPointPatchField< Type >::doTransform(), extendedCellToCellStencil::extendedCellToCellStencil(), extendedCellToFaceStencil::extendedCellToFaceStencil(), extendedFaceToCellStencil::extendedFaceToCellStencil(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), FaceCellWave< Type, TrackingData >::handleCyclicPatches(), FaceCellWave< Type, TrackingData >::handleProcPatches(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), mapDistribute::transform::operator()(), cyclicFvPatch::parallel(), processorFvPatch::parallel(), cyclicAMIFvPatch::parallel(), cyclicPointPatch::parallel(), cyclicAMIPointPatch::parallel(), cyclicACMIPointPatch::parallel(), cyclicACMIFvPatch::parallel(), processorCyclicPolyPatch::parallel(), motionSmootherAlgo::scaleMesh(), and meshRefinement::selectSeparatedCoupledFaces().
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Reimplemented in processorCyclicPolyPatch.
Definition at line 294 of file coupledPolyPatch.H.
Referenced by particle< Type >::correctAfterParallelTransfer(), PointEdgeWave< Type, TrackingData >::countPatchType(), cyclicFvPatch::forwardT(), processorFvPatch::forwardT(), cyclicAMIFvPatch::forwardT(), cyclicAMIPointPatch::forwardT(), cyclicPointPatch::forwardT(), cyclicACMIPointPatch::forwardT(), cyclicACMIFvPatch::forwardT(), processorCyclicPolyPatch::forwardT(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), FaceCellWave< Type, TrackingData >::handleCyclicPatches(), FaceCellWave< Type, TrackingData >::handleProcPatches(), particle< Type >::hitCyclicAMIPatch(), particle< Type >::hitCyclicPatch(), mapDistribute::transform::operator()(), and motionSmootherAlgo::scaleMesh().
reverseT()
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Reimplemented in processorCyclicPolyPatch.
Definition at line 300 of file coupledPolyPatch.H.
Referenced by cyclicFvPatch::reverseT(), processorFvPatch::reverseT(), cyclicAMIFvPatch::reverseT(), cyclicAMIPointPatch::reverseT(), cyclicPointPatch::reverseT(), cyclicACMIPointPatch::reverseT(), cyclicACMIFvPatch::reverseT(), and processorCyclicPolyPatch::reverseT().
collocated()
virtual const boolList& collocated () const inline virtual
Are faces collocated. Either size 0,1 or length of patch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 306 of file coupledPolyPatch.H.
Referenced by processorCyclicPolyPatch::collocated().
matchTolerance()
scalar matchTolerance () const inline
Definition at line 311 of file coupledPolyPatch.H.
References coupledPolyPatch::calcFaceTol(), coupledPolyPatch::calcGeometry(), polyPatch::faceCentres(), Foam::faceMap(), coupledPolyPatch::initOrder(), coupledPolyPatch::order(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), and coupledPolyPatch::write().
calcGeometry() [2/2]
virtual void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) pure virtual
Calculate the patch geometry.
Implemented in cyclicAMIPolyPatch, cyclicACMIPolyPatch, oldCyclicPolyPatch, cyclicPolyPatch, processorPolyPatch, and processorCyclicPolyPatch.
initOrder()
virtual void initOrder (PstreamBuffers & , const primitivePatch &) const pure virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, cyclicAMIPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and oldCyclicPolyPatch.
Referenced by coupledPolyPatch::matchTolerance().
order()
virtual bool order (PstreamBuffers & , const primitivePatch & , labelList & faceMap, labelList & rotation) const pure virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Reimplemented from polyPatch.
Implemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and oldCyclicPolyPatch.
Referenced by coupledPolyPatch::matchTolerance().
calcFaceTol()
Foam::scalarField calcFaceTol (const UList< face > & faces, const pointField & points, const pointField & faceCentres) static
Calculate typical tolerance per face. Is currently max distance.
from face centre to any of the face vertices.
Definition at line 199 of file coupledPolyPatch.C.
References Foam::cmptMag(), Foam::cmptMax(), f(), forAll, coupledPolyPatch::getRotation(), Foam::magSqr(), Foam::max(), UList< T >::size(), and Foam::sqrt().
Referenced by coupledPolyPatch::getAnchorPoints(), and coupledPolyPatch::matchTolerance().
write()
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from polyPatch.
Reimplemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and oldCyclicPolyPatch.
Definition at line 560 of file coupledPolyPatch.C.
References token::END_STATEMENT, Foam::nl, polyPatch::write(), and Ostream::writeKeyword().
Referenced by coupledPolyPatch::matchTolerance(), processorPolyPatch::write(), cyclicPolyPatch::write(), and cyclicAMIPolyPatch::write().
Member Data Documentation
transformTypeNames
const NamedEnum< coupledPolyPatch::transformType, 5 > transformTypeNames static
Definition at line 67 of file coupledPolyPatch.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/basic/coupled/coupledPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/basic/coupled/coupledPolyPatch.C