OpenFOAM: mapAddedPolyMesh Class Reference
mapAddedPolyMesh Class Reference
Class containing mesh-to-mesh mapping information after a mesh addition where we add a mesh ('added mesh') to an old mesh, creating a new mesh.
Public Member Functions
mapAddedPolyMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, const label nAddedPoints, const label nAddedFaces, const label nAddedCells, const labelList &oldPointMap, const labelList &oldFaceMap, const labelList &oldCellMap, const labelList &addedPointMap, const labelList &addedFaceMap, const labelList &addedCellMap, const labelList &oldPatchMap, const labelList &addedPatchMap, const labelList &oldPatchSizes, const labelList &oldPatchStarts)
Construct from components.
label nOldPoints () const
label nOldFaces () const
label nOldCells () const
const labelList & oldPointMap () const
From old mesh point/face/cell to new mesh point/face/cell.
const labelList & oldFaceMap () const
const labelList & oldCellMap () const
const labelList & oldPatchMap () const
From old patch index to new patch index or -1 if patch.
const labelList & oldPatchSizes () const
Return list of the old patch sizes.
const labelList & oldPatchStarts () const
Return list of the old patch start labels.
label nOldInternalFaces () const
Number of old internal faces.
label nAddedPoints () const
label nAddedFaces () const
label nAddedCells () const
const labelList & addedPointMap () const
From added mesh point/face/cell to new mesh point/face/cell.
const labelList & addedFaceMap () const
const labelList & addedCellMap () const
const labelList & addedPatchMap () const
From added mesh patch index to new patch index or -1 if.
void updateMesh (const mapPolyMesh &)
Detailed Description
Class containing mesh-to-mesh mapping information after a mesh addition where we add a mesh ('added mesh') to an old mesh, creating a new mesh.
We store mapping from the old to the new mesh and from the added mesh to the new mesh.
Note: Might need some more access functions or maybe some zone maps?
Source files
mapAddedPolyMesh.H
mapAddedPolyMesh.C
Definition at line 56 of file mapAddedPolyMesh.H.
Constructor & Destructor Documentation
mapAddedPolyMesh()
mapAddedPolyMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, const label nAddedPoints, const label nAddedFaces, const label nAddedCells, const labelList & oldPointMap, const labelList & oldFaceMap, const labelList & oldCellMap, const labelList & addedPointMap, const labelList & addedFaceMap, const labelList & addedCellMap, const labelList & oldPatchMap, const labelList & addedPatchMap, const labelList & oldPatchSizes, const labelList & oldPatchStarts)
Construct from components.
Definition at line 34 of file mapAddedPolyMesh.C.
Member Function Documentation
nOldPoints()
label nOldPoints () const inline
Definition at line 132 of file mapAddedPolyMesh.H.
nOldFaces()
label nOldFaces () const inline
Definition at line 137 of file mapAddedPolyMesh.H.
nOldCells()
label nOldCells () const inline
Definition at line 142 of file mapAddedPolyMesh.H.
oldPointMap()
const labelList& oldPointMap () const inline
From old mesh point/face/cell to new mesh point/face/cell.
Definition at line 149 of file mapAddedPolyMesh.H.
oldFaceMap()
const labelList& oldFaceMap () const inline
Definition at line 153 of file mapAddedPolyMesh.H.
Referenced by fvMeshAdder::MapVolFields(), and fvMeshDistribute::printCoupleInfo().
oldCellMap()
const labelList& oldCellMap () const inline
Definition at line 157 of file mapAddedPolyMesh.H.
References mapAddedPolyMesh::oldPatchMap().
Referenced by fvMeshAdder::MapSurfaceFields().
oldPatchMap()
const labelList& oldPatchMap () const inline
From old patch index to new patch index or -1 if patch.
not present (since 0 size)
Definition at line 164 of file mapAddedPolyMesh.H.
Referenced by fvMeshAdder::MapVolFields(), and mapAddedPolyMesh::oldCellMap().
oldPatchSizes()
const labelList& oldPatchSizes () const inline
Return list of the old patch sizes.
Definition at line 170 of file mapAddedPolyMesh.H.
Referenced by fvMeshAdder::MapVolFields().
oldPatchStarts()
const labelList& oldPatchStarts () const inline
Return list of the old patch start labels.
Definition at line 176 of file mapAddedPolyMesh.H.
Referenced by fvMeshAdder::MapVolFields().
nOldInternalFaces()
label nOldInternalFaces () const inline
Number of old internal faces.
Definition at line 182 of file mapAddedPolyMesh.H.
Referenced by fvMeshDistribute::printCoupleInfo().
nAddedPoints()
label nAddedPoints () const inline
Definition at line 190 of file mapAddedPolyMesh.H.
nAddedFaces()
label nAddedFaces () const inline
Definition at line 195 of file mapAddedPolyMesh.H.
nAddedCells()
label nAddedCells () const inline
Definition at line 200 of file mapAddedPolyMesh.H.
addedPointMap()
const labelList& addedPointMap () const inline
From added mesh point/face/cell to new mesh point/face/cell.
Definition at line 206 of file mapAddedPolyMesh.H.
addedFaceMap()
const labelList& addedFaceMap () const inline
Definition at line 210 of file mapAddedPolyMesh.H.
Referenced by fvMeshAdder::MapVolFields(), and fvMeshDistribute::printCoupleInfo().
addedCellMap()
const labelList& addedCellMap () const inline
Definition at line 214 of file mapAddedPolyMesh.H.
References mapAddedPolyMesh::addedPatchMap().
Referenced by fvMeshAdder::MapSurfaceFields().
addedPatchMap()
const labelList& addedPatchMap () const inline
From added mesh patch index to new patch index or -1 if.
patch not present (since 0 size)
Definition at line 221 of file mapAddedPolyMesh.H.
Referenced by mapAddedPolyMesh::addedCellMap(), and fvMeshAdder::MapVolFields().
updateMesh()
void updateMesh (const mapPolyMesh &) inline
Definition at line 229 of file mapAddedPolyMesh.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapAddedPolyMesh.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapAddedPolyMesh.C