OpenFOAM: pointZone Class Reference
pointZone Class Reference
A subset of mesh points. The labels of points in the zone can be obtained from the addressing() list.
Public Member Functions
TypeName ("pointZone")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointZone, dictionary,(const word &name, const dictionary &dict, const label index, const pointZoneMesh &zm),(name, dict, index, zm))
pointZone (const word &name, const labelUList &addr, const label index, const pointZoneMesh &)
Construct from components.
pointZone (const word &name, const Xfer< labelList > &addr, const label index, const pointZoneMesh &)
Construct from components, transferring contents.
pointZone (const word &name, const dictionary &, const label index, const pointZoneMesh &)
Construct from dictionary.
pointZone (const pointZone &, const labelUList &addr, const label index, const pointZoneMesh &)
Construct given the original zone and resetting the.
pointZone (const pointZone &, const Xfer< labelList > &addr, const label index, const pointZoneMesh &)
Construct given the original zone, resetting the.
virtual autoPtr< pointZone > clone (const pointZoneMesh &zm) const
Construct and return a clone, resetting the zone mesh.
virtual autoPtr< pointZone > clone (const pointZoneMesh &zm, const label index, const labelUList &addr) const
Construct and return a clone, resetting the point list.
virtual ~pointZone ()
Destructor.
const pointZoneMesh & zoneMesh () const
Return zoneMesh reference.
label whichPoint (const label globalPointID) const
Helper function to re-direct to zone::localID(...)
virtual bool checkDefinition (const bool report=false) const
Check zone definition. Return true if in error.
virtual bool checkParallelSync (const bool report=false) const
Check whether zone is synchronised across coupled boundaries. Return.
virtual void movePoints (const pointField &)
Correct patch after moving points.
virtual void writeDict (Ostream &) const
Write dictionary.
void operator= (const pointZone &)
Assign to zone, clearing demand-driven data.
void operator= (const labelUList &)
Assign addressing, clearing demand-driven data.
void operator= (const Xfer< labelList > &)
Assign addressing, clearing demand-driven data.
Public Member Functions inherited from zone
TypeName ("zone")
Runtime type information.
zone (const word &name, const labelUList &addr, const label index)
Construct from components.
zone (const word &name, const Xfer< labelList > &addr, const label index)
Construct from components, transferring contents.
zone (const word &name, const dictionary &, const word &labelsName, const label index)
Construct from dictionary.
zone (const zone &, const labelUList &addr, const label index)
Construct given the original zone and resetting the.
zone (const zone &, const Xfer< labelList > &addr, const label index)
Construct given the original zone, resetting the.
virtual ~zone ()
Destructor.
const word & name () const
Return name.
label localID (const label globalID) const
Map storing the local index for every global index. Used to find.
label index () const
Return the index of this zone in zone list.
virtual void clearAddressing ()
Clear addressing.
virtual bool checkDefinition (const label maxSize, const bool report=false) const
Check zone definition with max size given. Return true if in error.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static autoPtr< pointZone > New (const word &name, const dictionary &, const label index, const pointZoneMesh &)
Return a pointer to a new point zone.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes
static const char *const labelsName = "pointLabels"
The name associated with the zone-labels dictionary entry.
Protected Member Functions
pointZone (const pointZone &)
Disallow default bitwise copy construct.
Protected Member Functions inherited from zone
const Map< label > & lookupMap () const
Return a reference to the look-up map.
void calcLookupMap () const
Construct the look-up map.
zone (const zone &)
Disallow default bitwise copy construct.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Attributes
const pointZoneMesh & zoneMesh_
Reference to zone list.
Protected Attributes inherited from zone
word name_
Name of zone.
label index_
Index of zone.
Map< label > * lookupMapPtr_
Map of labels in zone for fast location lookup.
Friends
Ostream & operator<< (Ostream &, const pointZone &)
Ostream Operator.
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Detailed Description
A subset of mesh points. The labels of points in the zone can be obtained from the addressing() list.
For quick check whether a point belongs to the zone use the lookup mechanism in pointZoneMesh, where all the zoned points are registered with their zone number.
Source files
pointZone.H
pointZone.C
pointZoneNew.C
Definition at line 62 of file pointZone.H.
Constructor & Destructor Documentation
pointZone() [1/6]
pointZone (const pointZone &) protected
Disallow default bitwise copy construct.
Referenced by pointZone::clone(), and pointZone::pointZone().
pointZone() [2/6]
pointZone (const word & name, const labelUList & addr, const label index, const pointZoneMesh & zm)
Construct from components.
Definition at line 48 of file pointZone.C.
References pointZone::pointZone().
pointZone() [3/6]
pointZone (const word & name, const Xfer< labelList > & addr, const label index, const pointZoneMesh & zm)
Construct from components, transferring contents.
Definition at line 61 of file pointZone.C.
References pointZone::pointZone().
pointZone() [4/6]
pointZone (const word & name, const dictionary & dict, const label index, const pointZoneMesh & zm)
Construct from dictionary.
Definition at line 74 of file pointZone.C.
References pointZone::pointZone().
pointZone() [5/6]
pointZone (const pointZone & pz, const labelUList & addr, const label index, const pointZoneMesh & zm)
Construct given the original zone and resetting the.
point list and zone mesh information
Definition at line 87 of file pointZone.C.
References pointZone::pointZone().
pointZone() [6/6]
pointZone (const pointZone & pz, const Xfer< labelList > & addr, const label index, const pointZoneMesh & zm)
Construct given the original zone, resetting the.
face list and zone mesh information
Definition at line 100 of file pointZone.C.
~pointZone()
~pointZone () virtual
Destructor.
Definition at line 114 of file pointZone.C.
Referenced by pointZone::clone().
Member Function Documentation
TypeName()
TypeName ("pointZone")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , pointZone , dictionary , (const word &name, const dictionary &dict, const label index, const pointZoneMesh &zm) , (name, dict, index, zm))
clone() [1/2]
virtual autoPtr<pointZone> clone (const pointZoneMesh & zm) const inline virtual
Construct and return a clone, resetting the zone mesh.
Definition at line 158 of file pointZone.H.
References List< T >::clone(), zone::index(), and pointZone::pointZone().
clone() [2/2]
virtual autoPtr<pointZone> clone (const pointZoneMesh & zm, const label index, const labelUList & addr) const inline virtual
Construct and return a clone, resetting the point list.
and zone mesh
Definition at line 169 of file pointZone.H.
References pointZone::checkDefinition(), pointZone::checkParallelSync(), pointZone::New(), pointZone::pointZone(), pointZone::whichPoint(), pointZone::zoneMesh(), and pointZone::~pointZone().
New()
Foam::autoPtr< Foam::pointZone > New (const word & name, const dictionary & dict, const label index, const pointZoneMesh & zm) static
Return a pointer to a new point zone.
created on freestore from dictionary
Definition at line 32 of file pointZoneNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, dictionary::lookup(), Foam::name(), and Foam::nl.
Referenced by pointZone::clone().
zoneMesh()
const Foam::pointZoneMesh & zoneMesh () const
Return zoneMesh reference.
Definition at line 120 of file pointZone.C.
Referenced by pointZone::clone().
whichPoint()
Foam::label whichPoint (const label globalPointID) const
Helper function to re-direct to zone::localID(...)
Definition at line 126 of file pointZone.C.
References zone::localID().
Referenced by pointZone::clone(), and NamedEnum< directionType, 3 >::names().
checkDefinition()
bool checkDefinition (const bool report = false) const virtual
Check zone definition. Return true if in error.
Implements zone.
Definition at line 132 of file pointZone.C.
References zone::checkDefinition().
Referenced by pointZone::clone().
checkParallelSync()
bool checkParallelSync (const bool report = false) const virtual
Check whether zone is synchronised across coupled boundaries. Return.
true if in error.
Definition at line 138 of file pointZone.C.
References Foam::endl(), forAll, Foam::Info, Foam::labelMax, mesh, Foam::name(), Foam::nl, primitiveMesh::nPoints(), polyMesh::points(), and syncTools::syncPointList().
Referenced by pointZone::clone().
movePoints()
virtual void movePoints (const pointField &) inline virtual
Correct patch after moving points.
Reimplemented from zone.
Definition at line 215 of file pointZone.H.
References pointZone::operator<<, pointZone::operator=(), and pointZone::writeDict().
writeDict()
void writeDict (Ostream & os) const virtual
Write dictionary.
Implements zone.
Definition at line 189 of file pointZone.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::nl, and Foam::type().
Referenced by pointZone::movePoints().
operator=() [1/3]
void operator= (const pointZone & zn)
Assign to zone, clearing demand-driven data.
Definition at line 202 of file pointZone.C.
References List< label >::operator=().
Referenced by pointZone::movePoints().
operator=() [2/3]
void operator= (const labelUList & addr)
Assign addressing, clearing demand-driven data.
Definition at line 209 of file pointZone.C.
References List< label >::operator=().
operator=() [3/3]
void operator= (const Xfer< labelList > & addr)
Assign addressing, clearing demand-driven data.
Definition at line 216 of file pointZone.C.
References List< label >::operator=().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const pointZone &) friend
Ostream Operator.
Referenced by pointZone::movePoints().
Member Data Documentation
zoneMesh_
const pointZoneMesh& zoneMesh_ protected
Reference to zone list.
Definition at line 72 of file pointZone.H.
labelsName
const char *const labelsName = "pointLabels" static
The name associated with the zone-labels dictionary entry.
Definition at line 84 of file pointZone.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/zones/pointZone/pointZone.H
src/OpenFOAM/meshes/polyMesh/zones/pointZone/pointZone.C
src/OpenFOAM/meshes/polyMesh/zones/pointZone/pointZoneNew.C