OpenFOAM: primitiveMesh Class Reference
primitiveMesh Class Reference abstract
Cell-face mesh analysis engine.
Public Member Functions
ClassName ("primitiveMesh")
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Construct from components.
virtual ~primitiveMesh ()
Destructor.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Reset this primitiveMesh given the primitive array sizes.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList &cells)
Reset this primitiveMesh given the primitive array sizes and cells.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, const Xfer< cellList > &cells)
Reset this primitiveMesh given the primitive array sizes and cells.
label nPoints () const
label nEdges () const
label nInternalFaces () const
label nFaces () const
label nCells () const
label nInternalPoints () const
Points not on boundary.
label nInternal0Edges () const
Internal edges (i.e. not on boundary face) using.
label nInternal1Edges () const
Internal edges using 0 or 1 boundary point.
label nInternalEdges () const
Internal edges using 0,1 or 2 boundary points.
virtual const pointField & points () const =0
Return mesh points.
virtual const faceList & faces () const =0
Return faces.
virtual const labelList & faceOwner () const =0
Face face-owner addresing.
virtual const labelList & faceNeighbour () const =0
Face face-neighbour addressing.
virtual const pointField & oldPoints () const =0
Return old points for mesh motion.
const cellShapeList & cellShapes () const
Return cell shapes.
const edgeList & edges () const
Return mesh edges. Uses calcEdges.
const labelListList & cellCells () const
const labelListList & edgeCells () const
const labelListList & pointCells () const
const cellList & cells () const
const labelListList & edgeFaces () const
const labelListList & pointFaces () const
const labelListList & cellEdges () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointPoints () const
const labelListList & cellPoints () const
const vectorField & cellCentres () const
const vectorField & faceCentres () const
const scalarField & cellVolumes () const
const vectorField & faceAreas () const
tmp< scalarField > movePoints (const pointField &p, const pointField &oldP)
Move points, returns volumes swept by faces in motion.
bool isInternalFace (const label faceIndex) const
Return true if given face label is internal to the mesh.
virtual bool checkUpperTriangular (const bool report=false, labelHashSet *setPtr=nullptr) const
Check face ordering.
virtual bool checkCellsZipUp (const bool report=false, labelHashSet *setPtr=nullptr) const
Check cell zip-up.
virtual bool checkFaceVertices (const bool report=false, labelHashSet *setPtr=nullptr) const
Check uniqueness of face vertices.
virtual bool checkPoints (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for unused points.
virtual bool checkFaceFaces (const bool report=false, labelHashSet *setPtr=nullptr) const
Check face-face connectivity.
virtual bool checkClosedBoundary (const bool report=false) const
Check boundary for closedness.
virtual bool checkClosedCells (const bool report=false, labelHashSet *setPtr=nullptr, labelHashSet *highAspectSetPtr=nullptr, const Vector< label > &solutionD=Vector< label >::one) const
Check cells for closedness.
virtual bool checkFaceAreas (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for negative face areas.
virtual bool checkCellVolumes (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for negative cell volumes.
virtual bool checkFaceOrthogonality (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for non-orthogonality.
virtual bool checkFacePyramids (const bool report=false, const scalar minPyrVol=-SMALL, labelHashSet *setPtr=nullptr) const
Check face pyramid volume.
virtual bool checkFaceSkewness (const bool report=false, labelHashSet *setPtr=nullptr) const
Check face skewness.
virtual bool checkFaceAngles (const bool report=false, const scalar maxSin=10, labelHashSet *setPtr=nullptr) const
Check face angles.
virtual bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage: decompose face and check ratio between.
virtual bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet *setPtr=nullptr) const
Check for point-point-nearness,.
virtual bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet *setPtr=nullptr) const
Check edge length.
virtual bool checkConcaveCells (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for concave cells by the planes of faces.
virtual bool checkTopology (const bool report=false) const
Check mesh topology for correctness.
virtual bool checkGeometry (const bool report=false) const
Check mesh geometry (& implicitly topology) for correctness.
virtual bool checkMesh (const bool report=false) const
Check mesh for correctness. Returns false for no error.
bool pointInCellBB (const point &p, label celli, scalar inflationFraction=0) const
Return true if the point in the cell bounding box.
bool pointInCell (const point &p, label celli) const
Return true if the point is in the cell.
label findNearestCell (const point &location) const
Find the cell with the nearest cell centre to location.
label findCell (const point &location) const
Find cell enclosing this location (-1 if not in mesh)
void printAllocated () const
Print a list of all the currently allocated mesh data.
bool hasCellShapes () const
bool hasEdges () const
bool hasCellCells () const
bool hasEdgeCells () const
bool hasPointCells () const
bool hasCells () const
bool hasEdgeFaces () const
bool hasPointFaces () const
bool hasCellEdges () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointPoints () const
bool hasCellPoints () const
bool hasCellCentres () const
bool hasFaceCentres () const
bool hasCellVolumes () const
bool hasFaceAreas () const
const labelList & cellCells (const label celli, DynamicList< label > &) const
cellCells using cells.
const labelList & cellCells (const label celli) const
const labelList & cellPoints (const label celli, DynamicList< label > &) const
cellPoints using cells
const labelList & cellPoints (const label celli) const
const labelList & pointCells (const label pointi, DynamicList< label > &) const
pointCells using pointFaces
const labelList & pointCells (const label pointi) const
const labelList & pointPoints (const label pointi, DynamicList< label > &) const
pointPoints using edges, pointEdges
const labelList & pointPoints (const label pointi) const
const labelList & faceEdges (const label facei, DynamicList< label > &) const
faceEdges using pointFaces, edges, pointEdges
const labelList & faceEdges (const label facei) const
const labelList & edgeFaces (const label edgeI, DynamicList< label > &) const
edgeFaces using pointFaces, edges, pointEdges
const labelList & edgeFaces (const label edgeI) const
const labelList & edgeCells (const label edgeI, DynamicList< label > &) const
edgeCells using pointFaces, edges, pointEdges
const labelList & edgeCells (const label edgeI) const
const labelList & cellEdges (const label celli, DynamicList< label > &) const
cellEdges using cells, pointFaces, edges, pointEdges
const labelList & cellEdges (const label celli) const
void clearGeom ()
Clear geometry.
void clearAddressing ()
Clear topological data.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Static Public Member Functions
static void calcCells (cellList &, const labelUList &own, const labelUList &nei, const label nCells=-1)
Helper function to calculate cell-face addressing from.
static bool calcPointOrder (label &nInternalPoints, labelList &pointMap, const faceList &, const label nInternalFaces, const label nPoints)
Helper function to calculate point ordering. Returns true.
static scalar setClosedThreshold (const scalar)
Set the closedness ratio warning threshold.
static scalar setAspectThreshold (const scalar)
Set the aspect ratio warning threshold.
static scalar setNonOrthThreshold (const scalar)
Set the non-orthogonality warning threshold in degrees.
static scalar setSkewThreshold (const scalar)
Set the skewness warning threshold as percentage.
Static Public Attributes
static const unsigned cellsPerEdge_ = 4
Estimated number of cells per edge.
static const unsigned cellsPerPoint_ = 8
Estimated number of cells per point.
static const unsigned facesPerCell_ = 6
Estimated number of faces per cell.
static const unsigned facesPerEdge_ = 4
Estimated number of faces per edge.
static const unsigned facesPerPoint_ = 12
Estimated number of faces per point.
static const unsigned edgesPerCell_ = 12
Estimated number of edges per cell.
static const unsigned edgesPerFace_ = 4
Estimated number of edges per cell.
static const unsigned edgesPerPoint_ = 6
Estimated number of edges per point.
static const unsigned pointsPerCell_ = 8
Estimated number of points per cell.
static const unsigned pointsPerFace_ = 4
Estimated number of points per face.
Protected Member Functions
void calcFaceCentresAndAreas () const
Calculate face centres and areas.
void makeFaceCentresAndAreas (const pointField &p, vectorField &fCtrs, vectorField &fAreas) const
void calcCellCentresAndVols () const
Calculate cell centres and volumes.
void makeCellCentresAndVols (const vectorField &fCtrs, const vectorField &fAreas, vectorField &cellCtrs, scalarField &cellVols) const
void calcEdgeVectors () const
Calculate edge vectors.
bool checkDuplicateFaces (const label, const Map< label > &, label &nBaffleFaces, labelHashSet *) const
Check if all points on face are shared with another face.
bool checkCommonOrder (const label, const Map< label > &, labelHashSet *) const
Check that shared points are in consecutive order.
bool checkClosedBoundary (const vectorField &, const bool, const PackedBoolList &) const
Check boundary for closedness.
bool checkClosedCells (const vectorField &faceAreas, const scalarField &cellVolumes, const bool report, labelHashSet *setPtr, labelHashSet *aspectSetPtr, const Vector< label > &meshD) const
Check cells for closedness.
bool checkFaceAreas (const vectorField &faceAreas, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative face areas.
bool checkCellVolumes (const scalarField &vols, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative cell volumes.
bool checkFaceOrthogonality (const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check for non-orthogonality.
bool checkFacePyramids (const pointField &points, const vectorField &ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet *setPtr) const
Check face pyramid volume.
bool checkFaceSkewness (const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check face skewness.
bool checkFaceAngles (const pointField &points, const vectorField &faceAreas, const bool report, const scalar maxDeg, labelHashSet *setPtr) const
Check face angles.
bool checkFaceFlatness (const pointField &points, const vectorField &faceCentres, const vectorField &faceAreas, const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage.
bool checkConcaveCells (const vectorField &fAreas, const pointField &fCentres, const bool report, labelHashSet *setPtr) const
Check for concave cells by the planes of faces.
primitiveMesh ()
Construct null.
Static Protected Attributes
static scalar closedThreshold_ = 1.0e-6
Static data to control mesh checking.
static scalar aspectThreshold_ = 1000
Aspect ratio warning threshold.
static scalar nonOrthThreshold_ = 70
Non-orthogonality warning threshold in deg.
static scalar skewThreshold_ = 4
Skewness warning threshold.
static scalar planarCosAngle_ = 1.0e-6
Threshold where faces are considered coplanar.
Detailed Description
Cell-face mesh analysis engine.
Source files
primitiveMesh.H
primitiveMeshI.H
primitiveMesh.C
primitiveMeshClear.C
primitiveMeshCellCells.C
primitiveMeshEdgeCells.C
primitiveMeshPointCells.C
primitiveMeshCells.C
primitiveMeshEdgeFaces.C
primitiveMeshPointFaces.C
primitiveMeshCellEdges.C
primitiveMeshPointEdges.C
primitiveMeshPointPoints.C
primitiveMeshEdges.C
primitiveMeshCellCentresAndVols.C
primitiveMeshFaceCentresAndAreas.C
primitiveMeshFindCell.C
Definition at line 74 of file primitiveMesh.H.
Constructor & Destructor Documentation
primitiveMesh() [1/2]
primitiveMesh () protected
Construct null.
Definition at line 39 of file primitiveMesh.C.
primitiveMesh() [2/2]
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Construct from components.
Definition at line 77 of file primitiveMesh.C.
~primitiveMesh()
~primitiveMesh () virtual
Destructor.
Definition at line 118 of file primitiveMesh.C.
References primitiveMesh::calcPointOrder(), and primitiveMesh::clearOut().
Member Function Documentation
calcFaceCentresAndAreas()
void calcFaceCentresAndAreas () const protected
Calculate face centres and areas.
Definition at line 38 of file primitiveMeshFaceCentresAndAreas.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::makeFaceCentresAndAreas(), primitiveMesh::nFaces(), primitiveMesh::points(), and Foam::Pout.
Referenced by primitiveMesh::faceAreas(), and primitiveMesh::faceCentres().
makeFaceCentresAndAreas()
void makeFaceCentresAndAreas (const pointField & p, vectorField & fCtrs, vectorField & fAreas) const protected
Definition at line 74 of file primitiveMeshFaceCentresAndAreas.C.
References Foam::constant::universal::c, f(), primitiveMesh::faces(), forAll, Foam::mag(), n, primitiveMesh::nPoints(), Foam::constant::mathematical::pi(), List< T >::size(), and Foam::Zero.
Referenced by primitiveMesh::calcFaceCentresAndAreas(), and polyMesh::checkMeshMotion().
calcCellCentresAndVols()
void calcCellCentresAndVols () const protected
Calculate cell centres and volumes.
Definition at line 34 of file primitiveMeshCellCentresAndVols.C.
References Foam::abort(), cellVols, Foam::endl(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::makeCellCentresAndVols(), primitiveMesh::nCells(), and Foam::Pout.
Referenced by primitiveMesh::cellCentres(), and primitiveMesh::cellVolumes().
makeCellCentresAndVols()
void makeCellCentresAndVols (const vectorField & fCtrs, const vectorField & fAreas, vectorField & cellCtrs, scalarField & cellVols) const protected
Definition at line 73 of file primitiveMeshCellCentresAndVols.C.
References primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), forAll, Foam::mag(), primitiveMesh::nCells(), and Foam::Zero.
Referenced by primitiveMesh::calcCellCentresAndVols(), and polyMesh::checkMeshMotion().
calcEdgeVectors()
void calcEdgeVectors () const protected
Calculate edge vectors.
checkDuplicateFaces()
bool checkDuplicateFaces (const label facei, const Map< label > & nCommonPoints, label & nBaffleFaces, labelHashSet * setPtr) const protected
Check if all points on face are shared with another face.
Definition at line 1372 of file primitiveMeshCheck.C.
References primitiveMesh::checkCommonOrder(), forAllConstIter(), HashSet< Key, Hash >::insert(), and List< T >::size().
Referenced by primitiveMesh::checkPoints().
checkCommonOrder()
bool checkCommonOrder (const label facei, const Map< label > & nCommonPoints, labelHashSet * setPtr) const protected
Check that shared points are in consecutive order.
Definition at line 1413 of file primitiveMeshCheck.C.
References primitiveMesh::checkFaceFaces(), UList< T >::fcIndex(), Foam::findIndex(), forAll, forAllConstIter(), HashSet< Key, Hash >::insert(), Foam::labelMax, UList< T >::rcIndex(), and List< T >::size().
Referenced by primitiveMesh::checkDuplicateFaces().
checkClosedBoundary() [1/2]
bool checkClosedBoundary (const vectorField & areas, const bool report, const PackedBoolList & internalOrCoupledFaces) const protected
Check boundary for closedness.
Definition at line 46 of file primitiveMeshCheck.C.
References primitiveMesh::checkClosedCells(), Foam::cmptMag(), Foam::cmptMax(), Foam::endl(), Foam::Info, InfoInFunction, Foam::mag(), Foam::reduce(), List< T >::size(), PackedList< nBits >::size(), and Foam::Zero.
Referenced by primitiveMesh::checkClosedBoundary(), and primitiveMesh::checkGeometry().
checkClosedCells() [1/2]
bool checkClosedCells (const vectorField & faceAreas, const scalarField & cellVolumes, const bool report, labelHashSet * setPtr, labelHashSet * aspectSetPtr, const Vector< label > & meshD) const protected
Check cells for closedness.
Definition at line 103 of file primitiveMeshCheck.C.
References Foam::constant::universal::c, cells, primitiveMesh::checkFaceAreas(), Foam::endl(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::max(), Foam::min(), Foam::nl, and Foam::reduce().
Referenced by primitiveMesh::checkClosedBoundary(), primitiveMesh::checkClosedCells(), and primitiveMesh::checkGeometry().
checkFaceAreas() [1/2]
bool checkFaceAreas (const vectorField & faceAreas, const bool report, const bool detailedReport, labelHashSet * setPtr) const protected
Check for negative face areas.
Definition at line 235 of file primitiveMeshCheck.C.
References primitiveMesh::checkCellVolumes(), Foam::endl(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::max(), Foam::min(), Foam::Pout, and Foam::reduce().
Referenced by primitiveMesh::checkClosedCells(), primitiveMesh::checkFaceAreas(), primitiveMesh::checkGeometry(), and polyMesh::checkMeshMotion().
checkCellVolumes() [1/2]
bool checkCellVolumes (const scalarField & vols, const bool report, const bool detailedReport, labelHashSet * setPtr) const protected
Check for negative cell volumes.
Definition at line 313 of file primitiveMeshCheck.C.
References primitiveMesh::checkFaceOrthogonality(), Foam::endl(), forAll, Foam::gSum(), Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::max(), Foam::min(), Foam::Pout, and Foam::reduce().
Referenced by primitiveMesh::checkCellVolumes(), primitiveMesh::checkFaceAreas(), primitiveMesh::checkGeometry(), and polyMesh::checkMeshMotion().
checkFaceOrthogonality() [1/2]
bool checkFaceOrthogonality (const vectorField & fAreas, const vectorField & cellCtrs, const bool report, labelHashSet * setPtr) const protected
Check for non-orthogonality.
Definition at line 383 of file primitiveMeshCheck.C.
References Foam::acos(), primitiveMesh::checkFacePyramids(), Foam::cos(), Foam::degToRad(), Foam::endl(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::min(), Foam::radToDeg(), Foam::reduce(), List< T >::size(), and Foam::sum().
Referenced by primitiveMesh::checkCellVolumes(), primitiveMesh::checkFaceOrthogonality(), and primitiveMesh::checkGeometry().
checkFacePyramids() [1/2]
bool checkFacePyramids (const pointField & points, const vectorField & ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet * setPtr) const protected
Check face pyramid volume.
Definition at line 493 of file primitiveMeshCheck.C.
References cells, primitiveMesh::checkFaceSkewness(), Foam::endl(), f(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::nl, Foam::Pout, and Foam::reduce().
Referenced by primitiveMesh::checkFaceOrthogonality(), primitiveMesh::checkFacePyramids(), primitiveMesh::checkGeometry(), and polyMesh::checkMeshMotion().
checkFaceSkewness() [1/2]
bool checkFaceSkewness (const pointField & points, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs, const bool report, labelHashSet * setPtr) const protected
Check face skewness.
Definition at line 595 of file primitiveMeshCheck.C.
References primitiveMesh::checkFaceAngles(), Foam::endl(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::max(), and Foam::reduce().
Referenced by primitiveMesh::checkFacePyramids(), primitiveMesh::checkFaceSkewness(), and primitiveMesh::checkGeometry().
checkFaceAngles() [1/2]
bool checkFaceAngles (const pointField & points, const vectorField & faceAreas, const bool report, const scalar maxDeg, labelHashSet * setPtr) const protected
Check face angles.
Allows a slight non-convexity. E.g. maxDeg = 10 allows for angles < 190 (or 10 degrees concavity) (if truly concave and points not visible from face centre the face-pyramid check in checkMesh will fail)
Definition at line 668 of file primitiveMeshCheck.C.
References Foam::asin(), primitiveMesh::checkFaceFlatness(), Foam::degToRad(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::max(), Foam::min(), Foam::radToDeg(), Foam::reduce(), and Foam::sin().
Referenced by primitiveMesh::checkFaceAngles(), and primitiveMesh::checkFaceSkewness().
checkFaceFlatness() [1/2]
bool checkFaceFlatness (const pointField & points, const vectorField & faceCentres, const vectorField & faceAreas, const bool report, const scalar warnFlatness, labelHashSet * setPtr) const protected
Check face warpage.
Definition at line 748 of file primitiveMeshCheck.C.
References primitiveMesh::checkConcaveCells(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::min(), and Foam::reduce().
Referenced by primitiveMesh::checkFaceAngles(), and primitiveMesh::checkFaceFlatness().
checkConcaveCells() [1/2]
bool checkConcaveCells (const vectorField & fAreas, const pointField & fCentres, const bool report, labelHashSet * setPtr) const protected
Check for concave cells by the planes of faces.
Definition at line 853 of file primitiveMeshCheck.C.
References Foam::constant::universal::c, cells, primitiveMesh::checkUpperTriangular(), Foam::endl(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::mag(), Foam::max(), and Foam::reduce().
Referenced by primitiveMesh::checkConcaveCells(), and primitiveMesh::checkFaceFlatness().
ClassName()
ClassName ("primitiveMesh")
reset() [1/3]
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Reset this primitiveMesh given the primitive array sizes.
Definition at line 206 of file primitiveMesh.C.
References primitiveMesh::calcPointOrder(), primitiveMesh::clearOut(), Foam::endl(), primitiveMesh::faces(), primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), primitiveMesh::nInternalPoints(), primitiveMesh::nPoints(), and Foam::Pout.
Referenced by primitiveMesh::calcPointOrder(), and primitiveMesh::reset().
reset() [2/3]
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList & cells)
Reset this primitiveMesh given the primitive array sizes and cells.
Definition at line 262 of file primitiveMesh.C.
References primitiveMesh::reset().
reset() [3/3]
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, const Xfer< cellList > & cells)
Reset this primitiveMesh given the primitive array sizes and cells.
Definition at line 283 of file primitiveMesh.C.
References primitiveMesh::movePoints(), and primitiveMesh::reset().
nPoints()
label nPoints () const inline
Definition at line 41 of file primitiveMeshI.H.
Referenced by singleProcessorFaceSetsConstraint::add(), polyMeshAdder::add(), polyTopoChange::addMesh(), singleProcessorFaceSetsConstraint::apply(), motionSmootherAlgo::avg(), polyTopoChange::changeMesh(), pointZone::checkParallelSync(), componentDisplacementMotionSolver::componentDisplacementMotionSolver(), edgeCollapser::consistentCollapse(), polyMeshFilter::copyMesh(), displacementInterpolationMotionSolver::curPoints(), displacementMotionSolver::displacementMotionSolver(), fvMeshDistribute::distribute(), snappySnapDriver::doSnap(), edgeVertex::edgeToEVert(), cellClassification::fillHangingCells(), polyMeshFilter::filterEdges(), isoSurface::generateFaceTriPoints(), edgeVertex::getEdge(), surfaceSets::getHangingCells(), syncTools::getMasterPoints(), globalIndexAndTransform::globalIndexAndTransform(), cellClassification::growSurface(), hexRef8::hexRef8(), hexRef8Data::hexRef8Data(), isoSurfaceCell::interpolate(), isoSurface::interpolate(), edgeVertex::isEdge(), cellFeatures::isFeatureVertex(), localPointRegion::localPointRegion(), primitiveMesh::makeFaceCentresAndAreas(), polyTopoChange::makeMesh(), pointSet::maxSize(), pointZoneSet::maxSize(), globalMeshData::mergePoints(), meshTriangulation::meshTriangulation(), primitiveMesh::movePoints(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), vtkMesh::nFieldPoints(), minEqOpFace::operator()(), sampledSurface::pointAverage(), primitiveMesh::pointFaces(), pointSet::pointSet(), pointZoneSet::pointZoneSet(), polyMesh::polyMesh(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), processorMeshes::reconstructPoints(), primitiveMesh::reset(), polyMesh::resetPrimitives(), edgeCollapser::setRefinement(), pointMesh::size(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotionSolver::solve(), meshRefinement::splitMesh(), pointSet::sync(), hexRef8Data::sync(), syncTools::syncPointList(), meshRefinement::testSyncPointList(), cellClassification::trimCutCells(), globalMeshData::updateMesh(), and edgeVertex::vertToEVert().
nEdges()
label nEdges () const inline
Definition at line 71 of file primitiveMeshI.H.
References primitiveMesh::edges(), and List< T >::size().
Referenced by edgeCollapser::consistentCollapse(), polyMeshFilter::copyMesh(), meshRefinement::createZoneBaffles(), primitiveMesh::edgeCells(), primitiveMesh::edgeFaces(), edgeVertex::edgeToEVert(), directionInfo::edgeToFaceIndex(), polyMeshFilter::filter(), polyMeshFilter::filterEdges(), syncTools::getMasterEdges(), addPatchCellLayer::globalEdgeFaces(), edgeVertex::isEdge(), cellFeatures::isFeaturePoint(), primitiveMesh::nInternal0Edges(), primitiveMesh::nInternal1Edges(), primitiveMesh::nInternalEdges(), and syncTools::syncEdgeList().
nInternalFaces()
label nInternalFaces () const inline
Definition at line 82 of file primitiveMeshI.H.
Referenced by snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), preserveFaceZonesConstraint::apply(), preservePatchesConstraint::apply(), meshRefinement::baffleAndSplitMesh(), decompositionMethod::calcCellCells(), cellToFaceStencil::calcFaceStencil(), polyDualMesh::calcFeatures(), CentredFitSnGradData< Polynomial >::calcFit(), primitiveMesh::calcPointOrder(), primitiveMesh::cellCells(), CentredFitData< Polynomial >::CentredFitData(), meshRefinement::checkCoupledFaceZones(), polyBoundaryMesh::checkDefinition(), polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), decompositionMethod::decompose(), fvMeshDistribute::distribute(), dynamicRefineFvMesh::dynamicRefineFvMesh(), faceCoupleInfo::faceCoupleInfo(), fvMeshSubset::faceFlipMap(), cellQuality::faceNonOrthogonality(), primitiveMeshTools::faceOrthogonality(), polyMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), cellQuality::faceSkewness(), polyMeshTools::faceWeights(), localPointRegion::findDuplicateFacePairs(), localPointRegion::findDuplicateFaces(), polyMeshTetDecomposition::findFaceBasePts(), volPointInterpolation::flatBoundaryField(), isoSurface::generateFaceTriPoints(), boundaryMesh::getNearest(), particle< Type >::hitWallFaces(), cellToCellStencil::insertFaceCells(), cellToFaceStencil::insertFaceCells(), fvMeshSubset::interpolate(), primitiveMesh::isInternalFace(), fvMeshAdder::MapVolFields(), meshRefinement::mergeBaffles(), MeshedSurface< Foam::face >::MeshedSurface(), Cloud< streamLineParticle >::move(), fvMesh::movePoints(), particle< Type >::onBoundary(), minEqOpFace::operator()(), listPlusEqOp< T >::operator()(), boundaryMesh::patchify(), primitiveMesh::pointCells(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), boundaryMesh::read(), SloanRenumber::renumber(), primitiveMesh::reset(), mappedPatchBase::sampleSize(), fvMeshSubset::setLargeCellSubset(), tetDecomposer::setRefinement(), surfaceMesh::size(), fvSurfaceMapper::size(), snappyRefineDriver::snappyRefineDriver(), meshRefinement::splitMesh(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), syncTools::swapFaceList(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncFacePositions(), particle< Type >::trackToFace(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), rawTopoChangerFvMesh::update(), UpwindFitData< Polynomial >::UpwindFitData(), cellToFaceStencil::validBoundaryFaces(), cellToCellStencil::validBoundaryFaces(), polyMeshTools::volRatio(), extendedUpwindCellToFaceStencil::weightedSum(), extendedCellToFaceStencil::weightedSum(), polyBoundaryMesh::whichPatch(), and meshRefinement::zonify().
nFaces()
label nFaces () const inline
Definition at line 88 of file primitiveMeshI.H.
Referenced by preserveBafflesConstraint::add(), preserveFaceZonesConstraint::add(), preservePatchesConstraint::add(), singleProcessorFaceSetsConstraint::add(), polyMeshAdder::add(), refinementHistory::add(), snappyLayerDriver::addLayers(), fvMeshTools::addPatch(), meshRefinement::addPatch(), preserveFaceZonesConstraint::apply(), preservePatchesConstraint::apply(), meshRefinement::baffleAndSplitMesh(), decompositionMethod::calcCellCells(), primitiveMesh::calcFaceCentresAndAreas(), cellToFaceStencil::calcFaceStencil(), polyDualMesh::calcFeatures(), CentredFitSnGradData< Polynomial >::calcFit(), CentredFitData< Polynomial >::CentredFitData(), polyTopoChange::changeMesh(), edgeCollapser::checkBadFaces(), meshRefinement::checkCoupledFaceZones(), polyMeshGeometry::checkFaceDotProduct(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), motionSmootherAlgo::checkMesh(), polyMesh::checkMeshMotion(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), edgeCollapser::consistentCollapse(), polyMeshFilter::copyMesh(), meshRefinement::createBaffles(), meshRefinement::createZoneBaffles(), structuredDecomp::decompose(), decompositionMethod::decompose(), fvMeshDistribute::distribute(), snappyLayerDriver::doLayers(), snappySnapDriver::doSnap(), dynamicRefineFvMesh::dynamicRefineFvMesh(), primitiveMeshTools::faceConcavity(), primitiveMeshTools::faceFlatness(), faceMapper::faceMapper(), cellQuality::faceNonOrthogonality(), polyMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), faceSet::faceSet(), polyMeshTools::faceSkewness(), primitiveMeshTools::faceSkewness(), cellQuality::faceSkewness(), polyMeshTools::faceWeights(), faceZoneSet::faceZoneSet(), polyMeshFilter::filter(), localPointRegion::findDuplicateFacePairs(), polyMeshTetDecomposition::findFaceBasePts(), volPointInterpolation::flatBoundaryField(), fvFieldReconstructor::fvFieldReconstructor(), isoSurface::generateFaceTriPoints(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), boundaryMesh::getNearest(), Foam::MULES::implicitSolve(), cellFeatures::isFeatureVertex(), Foam::MULES::limit(), Foam::MULES::limitCorr(), polyTopoChange::makeMesh(), fvMesh::mapFields(), mappedPatchFieldBase< Type >::mappedField(), faceSet::maxSize(), faceZoneSet::maxSize(), meshRefinement::mergeBaffles(), snappyLayerDriver::mergePatchFacesUndo(), MeshedSurface< Foam::face >::MeshedSurface(), minEqOpFace::operator()(), listPlusEqOp< T >::operator()(), boundaryMesh::patchify(), polyMesh::polyMesh(), snappySnapDriver::preSmoothPatch(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), boundaryMesh::read(), SloanRenumber::renumber(), structuredRenumber::renumber(), snappySnapDriver::repatchToSurface(), primitiveMesh::reset(), mappedPatchBase::sampleSize(), snappySnapDriver::scaleMesh(), decompositionMethod::setConstraints(), boundaryCutter::setRefinement(), tetDecomposer::setRefinement(), edgeCollapser::setRefinement(), faceMapper::size(), Foam::fvc::smooth(), snappyRefineDriver::snappyRefineDriver(), meshRefinement::splitMesh(), Foam::fvc::spread(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), syncTools::swapFaceList(), Foam::fvc::sweep(), faceSet::sync(), syncTools::syncBoundaryFaceList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), syncTools::syncFacePositions(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), rawTopoChangerFvMesh::update(), globalMeshData::updateMesh(), UpwindFitData< Polynomial >::UpwindFitData(), polyMeshTools::volRatio(), polyBoundaryMesh::whichPatch(), and meshRefinement::zonify().
nCells()
label nCells () const inline
Definition at line 94 of file primitiveMeshI.H.
Referenced by polyMeshAdder::add(), snappyLayerDriver::addLayers(), polyTopoChange::addMesh(), primitiveMesh::calcCellCentresAndVols(), primitiveMesh::calcCells(), curvatureSeparation::calcCosAngle(), primitiveMeshTools::cellClosedness(), cellCuts::cellCuts(), primitiveMeshTools::cellDeterminant(), cellMapper::cellMapper(), primitiveMesh::cellPoints(), cellSet::cellSet(), cellZoneSet::cellZoneSet(), polyTopoChange::changeMesh(), polyMesh::checkMeshMotion(), drippingInjection::correct(), structuredDecomp::decompose(), decompositionMethod::decompose(), fvMeshDistribute::distribute(), refinementHistory::distribute(), snappyLayerDriver::doLayers(), snappyRefineDriver::doRefine(), dynamicRefineFvMesh::dynamicRefineFvMesh(), polyMesh::findCell(), primitiveMesh::findCell(), refinementParameters::findCells(), fvFieldReconstructor::fvFieldReconstructor(), isoSurface::generateFaceTriPoints(), get_edge_list(), get_geom_list(), get_num_edges_list(), get_number_of_vertices(), get_vertex_list(), surfaceSets::getHangingCells(), hexRef8::hexRef8(), hexRef8Data::hexRef8Data(), isoSurfaceCell::interpolate(), isoSurface::interpolate(), Kmesh::Kmesh(), primitiveMesh::makeCellCentresAndVols(), polyTopoChange::makeMesh(), fvMesh::mapFields(), mappedPatchFieldBase< Type >::mappedField(), meshToMesh::mapSrcToTgt(), fvMeshAdder::MapSurfaceFields(), meshToMesh::mapTgtToSrc(), cellSet::maxSize(), cellZoneSet::maxSize(), momentOfInertia::meshInertia(), cellQuality::nonOrthogonality(), minEqOpFace::operator()(), cellTable::operator=(), sampledSurface::pointAverage(), polyMesh::polyMesh(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), ensightParts::recalculate(), refinementHistory::refinementHistory(), CuthillMcKeeRenumber::renumber(), zoltanRenumber::renumber(), SloanRenumber::renumber(), springRenumber::renumber(), renumberMethod::renumber(), structuredRenumber::renumber(), primitiveMesh::reset(), polyMesh::resetPrimitives(), mappedPatchBase::sampleSize(), tetDecomposer::setRefinement(), edgeCollapser::setRefinement(), volMesh::size(), cellQuality::skewness(), Foam::fvc::smooth(), snappyRefineDriver::snappyRefineDriver(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), meshRefinement::splitMesh(), Foam::fvc::spread(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), Foam::fvc::sweep(), hexRef8Data::sync(), dynamicRefineFvMesh::update(), globalMeshData::updateMesh(), meshToMeshMethod::writeConnectivity(), meshRefinement::zonify(), and leastSquaresVectors::~leastSquaresVectors().
nInternalPoints()
label nInternalPoints () const inline
Points not on boundary.
Definition at line 35 of file primitiveMeshI.H.
Referenced by primitiveMesh::calcPointOrder(), and primitiveMesh::reset().
nInternal0Edges()
label nInternal0Edges () const inline
Internal edges (i.e. not on boundary face) using.
no boundary point
Definition at line 47 of file primitiveMeshI.H.
References primitiveMesh::nEdges().
nInternal1Edges()
label nInternal1Edges () const inline
Internal edges using 0 or 1 boundary point.
Definition at line 55 of file primitiveMeshI.H.
References primitiveMesh::nEdges().
nInternalEdges()
label nInternalEdges () const inline
Internal edges using 0,1 or 2 boundary points.
Definition at line 63 of file primitiveMeshI.H.
References primitiveMesh::nEdges().
points()
virtual const pointField& points () const pure virtual
Return mesh points.
Implemented in polyMesh.
Referenced by primitiveMesh::calcFaceCentresAndAreas(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), primitiveMesh::checkFaceAngles(), primitiveMesh::checkFaceFlatness(), primitiveMesh::checkFacePyramids(), primitiveMesh::checkFaceSkewness(), edgeVertex::coord(), localPointRegion::findDuplicateFaces(), boundaryMesh::getNearest(), cellFeatures::isFeaturePoint(), Foam::meshTools::normEdgeVec(), treeDataFace::findNearestOp::operator()(), treeDataFace::findIntersectOp::operator()(), cuttingPlane::reCut(), edgeFaceCirculator::setCanonical(), and pointSet::writeDebug().
faces()
virtual const faceList& faces () const pure virtual
Return faces.
Implemented in polyMesh.
Referenced by primitiveMeshTools::boundaryFaceSkewness(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), primitiveMesh::cellPoints(), primitiveMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFaceTwist(), directionInfo::edgeToFaceIndex(), primitiveMeshTools::faceConcavity(), primitiveMesh::faceEdges(), primitiveMeshTools::faceFlatness(), primitiveMeshTools::facePyramidVolume(), primitiveMeshTools::faceSkewness(), localPointRegion::findDuplicateFaces(), surfaceSets::getHangingCells(), boundaryMesh::getNearest(), Foam::interpolatePointToCell(), hexMatcher::isA(), prismMatcher::isA(), pyrMatcher::isA(), tetMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), cellFeatures::isFeatureVertex(), primitiveMesh::makeFaceCentresAndAreas(), degenerateMatcher::match(), wedgeMatcher::matches(), tetWedgeMatcher::matches(), prismMatcher::matches(), pyrMatcher::matches(), hexMatcher::matches(), tetMatcher::matches(), primitiveMesh::movePoints(), treeDataFace::findNearestOp::operator()(), treeDataFace::findIntersectOp::operator()(), primitiveMesh::pointFaces(), primitiveMesh::reset(), edgeFaceCirculator::sameOrder(), and edgeFaceCirculator::setCanonical().
faceOwner()
virtual const labelList& faceOwner () const pure virtual
Face face-owner addresing.
Implemented in polyMesh.
Referenced by primitiveMesh::calcCells(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), primitiveMesh::cellCells(), primitiveMeshTools::cellClosedness(), edgeFaceCirculator::cellLabel(), primitiveMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFaceSkewness(), primitiveMeshGeometry::checkFaceWeights(), primitiveMesh::edgeCells(), Foam::meshTools::faceOnCell(), primitiveMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), primitiveMeshTools::faceSkewness(), Foam::meshTools::getSharedFace(), pyrMatcher::isA(), tetMatcher::isA(), tetWedgeMatcher::isA(), prismMatcher::isA(), wedgeMatcher::isA(), hexMatcher::isA(), primitiveMesh::makeCellCentresAndVols(), degenerateMatcher::match(), prismMatcher::matches(), tetMatcher::matches(), pyrMatcher::matches(), wedgeMatcher::matches(), tetWedgeMatcher::matches(), hexMatcher::matches(), edgeFaceCirculator::operator++(), Foam::meshTools::otherCell(), primitiveMesh::pointCells(), primitiveMesh::pointInCell(), and edgeFaceCirculator::setCanonical().
faceNeighbour()
virtual const labelList& faceNeighbour () const pure virtual
Face face-neighbour addressing.
Implemented in polyMesh.
Referenced by primitiveMesh::calcCells(), primitiveMesh::cellCells(), primitiveMeshTools::cellClosedness(), edgeFaceCirculator::cellLabel(), primitiveMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFaceSkewness(), primitiveMeshGeometry::checkFaceWeights(), primitiveMesh::edgeCells(), Foam::meshTools::faceOnCell(), primitiveMeshTools::faceOrthogonality(), primitiveMeshTools::facePyramidVolume(), primitiveMeshTools::faceSkewness(), Foam::meshTools::getSharedFace(), primitiveMesh::makeCellCentresAndVols(), edgeFaceCirculator::operator++(), Foam::meshTools::otherCell(), primitiveMesh::pointCells(), and edgeFaceCirculator::setCanonical().
oldPoints()
virtual const pointField& oldPoints () const pure virtual
Return old points for mesh motion.
Implemented in polyMesh.
cellShapes()
const Foam::cellShapeList & cellShapes () const
Return cell shapes.
Definition at line 335 of file primitiveMesh.C.
Referenced by ensightPartCells::~ensightPartCells().
edges()
const Foam::edgeList & edges () const
Return mesh edges. Uses calcEdges.
Definition at line 495 of file primitiveMeshEdges.C.
Referenced by snappyLayerDriver::addLayers(), motionSmootherAlgo::avg(), polyDualMesh::calcFeatures(), addPatchCellLayer::calcSidePatch(), edgeCollapser::consistentCollapse(), edgeVertex::coord(), polyMeshFilter::copyMesh(), twoDPointCorrector::correctDisplacement(), twoDPointCorrector::correctPoints(), globalMeshData::coupledPatchMeshEdges(), geomCellLooper::cut(), topoCellLooper::cut(), primitiveMesh::edgeFaces(), Foam::meshTools::edgeToCutDir(), directionInfo::edgeToFaceIndex(), primitiveMesh::faceEdges(), Foam::meshTools::findEdge(), Foam::meshTools::getEdgeFaces(), cellLooper::getFirstVertEdge(), Foam::meshTools::getParallelEdges(), addPatchCellLayer::globalEdgeFaces(), cellFeatures::isFeaturePoint(), edgeCollapser::markMergeEdges(), edgeCollapser::markSmallEdges(), meshRefinement::mergeBaffles(), primitiveMesh::nEdges(), cellCuts::nonAnchorPoints(), Foam::meshTools::normEdgeVec(), listPlusEqOp< T >::operator()(), Foam::meshTools::otherEdge(), primitiveMesh::pointPoints(), faceCollapser::setRefinement(), boundaryCutter::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), directionInfo::updateCell(), pointEdgePoint::updateEdge(), externalPointEdgePoint::updateEdge(), Foam::meshTools::walkFace(), and blockMesh::writeTopology().
calcCells()
void calcCells (cellList & cellFaceAddr, const labelUList & own, const labelUList & nei, const label nCells = -1) static
Helper function to calculate cell-face addressing from.
face-cell addressing. If nCells is not provided it will scan for the maximum.
Definition at line 31 of file primitiveMeshCells.C.
References Foam::abort(), Foam::endl(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::max(), primitiveMesh::nCells(), Foam::Pout, List< T >::setSize(), and List< T >::size().
calcPointOrder()
bool calcPointOrder (label & nInternalPoints, labelList & pointMap, const faceList & faces, const label nInternalFaces, const label nPoints) static
Helper function to calculate point ordering. Returns true.
if points already ordered, false and fills pointMap (old to new). Map splits points into those not used by any boundary face and those that are.
Definition at line 127 of file primitiveMesh.C.
References f(), forAll, primitiveMesh::nInternalFaces(), primitiveMesh::nInternalPoints(), primitiveMesh::reset(), List< T >::setSize(), and List< T >::size().
Referenced by primitiveMesh::reset(), and primitiveMesh::~primitiveMesh().
cellCells() [1/3]
const Foam::labelListList & cellCells () const
Definition at line 100 of file primitiveMeshCellCells.C.
Referenced by meshToMeshMethod::appendNbrCells(), primitiveMesh::cellCells(), and NamedEnum< directionType, 3 >::names().
edgeCells() [1/3]
const Foam::labelListList & edgeCells () const
Definition at line 32 of file primitiveMeshEdgeCells.C.
References Foam::abort(), primitiveMesh::cellEdges(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nEdges(), and Foam::Pout.
Referenced by primitiveMesh::edgeCells(), and Foam::meshTools::edgeOnCell().
pointCells() [1/3]
const Foam::labelListList & pointCells () const
Definition at line 108 of file primitiveMeshPointCells.C.
Referenced by primitiveMesh::cellPoints(), cellDistFuncs::correctBoundaryPointCells(), dynamicRefineFvMesh::dynamicRefineFvMesh(), cellClassification::fillHangingCells(), cellClassification::growSurface(), sampledSurface::pointAverage(), primitiveMesh::pointCells(), and cellClassification::trimCutCells().
cells()
const Foam::cellList & cells () const
Definition at line 136 of file primitiveMeshCells.C.
Referenced by pointMVCWeight::calcWeights(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), primitiveMesh::cellCells(), primitiveMeshTools::cellDeterminant(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), polyMeshTetDecomposition::cellTetIndices(), layerAdditionRemoval::changeTopology(), primitiveMeshGeometry::checkCellDeterminant(), polyMeshGeometry::checkCellDeterminant(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFacePyramids(), edgeCollapser::consistentCollapse(), inversePointDistanceDiffusivity::correct(), outletStabilised< Type >::correction(), meshRefinement::createBaffles(), particle< Type >::crossEdgeConnectedFace(), geomCellLooper::cut(), topoCellLooper::cut(), dynamicRefineFvMesh::dynamicRefineFvMesh(), probes::findElements(), sampledSet::findNearFace(), polyMeshTetDecomposition::findTet(), get_edge_list(), get_num_edges_list(), surfaceSets::getHangingCells(), Foam::meshTools::getSharedFace(), particle< Type >::hitWallFaces(), Foam::interpolatePointToCell(), hexMatcher::isA(), prismMatcher::isA(), pyrMatcher::isA(), tetMatcher::isA(), tetWedgeMatcher::isA(), wedgeMatcher::isA(), meshToMesh::mapAndOpTgtToSrc(), degenerateMatcher::match(), tetMatcher::matches(), hexMatcher::matches(), prismMatcher::matches(), pyrMatcher::matches(), tetWedgeMatcher::matches(), wedgeMatcher::matches(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), cellCuts::nonAnchorPoints(), tetIndices::oldTet(), minEqOpFace::operator()(), treeDataCell::findIntersectOp::operator()(), polyMesh::pointInCell(), primitiveMesh::pointInCell(), polyMesh::polyMesh(), Foam::polyMeshZipUpCells(), polyMesh::readUpdate(), fvMeshSubset::setCellSubset(), fvMeshSubset::setLargeCellSubset(), patchInjectionBase::setPositionAndCell(), tetDecomposer::setRefinement(), meshCutter::setRefinement(), edgeCollapser::setRefinement(), fvMatrix< Type >::setValuesFromList(), snappyRefineDriver::snappyRefineDriver(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), meshRefinement::splitMesh(), outletStabilised< Type >::weights(), meshToMeshMethod::writeConnectivity(), and ensightPartCells::~ensightPartCells().
edgeFaces() [1/3]
const Foam::labelListList & edgeFaces () const
Definition at line 31 of file primitiveMeshEdgeFaces.C.
References Foam::abort(), Foam::endl(), primitiveMesh::faceEdges(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nEdges(), and Foam::Pout.
Referenced by polyDualMesh::calcFeatures(), addPatchCellLayer::calcSidePatch(), primitiveMesh::edgeCells(), primitiveMesh::edgeFaces(), Foam::meshTools::getEdgeFaces(), cellCuts::nonAnchorPoints(), boundaryMesh::patchNames(), faceCollapser::setRefinement(), boundaryCutter::setRefinement(), meshCutAndRemove::setRefinement(), and meshCutter::setRefinement().
pointFaces()
const Foam::labelListList & pointFaces () const
Definition at line 32 of file primitiveMeshPointFaces.C.
References Foam::endl(), primitiveMesh::faces(), Foam::invertManyToMany(), primitiveMesh::nPoints(), and Foam::Pout.
Referenced by singleProcessorFaceSetsConstraint::add(), singleProcessorFaceSetsConstraint::apply(), decompositionMethod::decompose(), primitiveMesh::edgeFaces(), cellLooper::getVertFacesNonEdge(), cellCuts::nonAnchorPoints(), listPlusEqOp< T >::operator()(), primitiveMesh::pointCells(), Foam::polyMeshZipUpCells(), perfectInterface::setRefinement(), edgeCollapser::setRefinement(), and meshRefinement::splitMesh().
cellEdges() [1/3]
const Foam::labelListList & cellEdges () const
Definition at line 118 of file primitiveMeshCellEdges.C.
Referenced by polyDualMesh::calcFeatures(), primitiveMesh::cellEdges(), cellFeatures::cellFeatures(), geomCellLooper::cut(), Foam::meshTools::cutDirToEdge(), primitiveMesh::edgeCells(), primitiveMesh::faceEdges(), cellLooper::getMisAlignedEdge(), and cellCuts::nonAnchorPoints().
faceEdges() [1/3]
const Foam::labelListList & faceEdges () const
Definition at line 518 of file primitiveMeshEdges.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), HashTable< T, Key, Hash >::clear(), Foam::deleteDemandDrivenData(), primitiveMesh::edges(), Foam::endl(), primitiveMesh::faces(), UList< T >::fcIndex(), forAll, primitiveMesh::pointEdges(), Foam::Pout, List< T >::setSize(), and List< T >::size().
Referenced by primitiveMesh::cellEdges(), edgeCollapser::consistentCollapse(), meshRefinement::createZoneBaffles(), primitiveMesh::edgeFaces(), Foam::meshTools::edgeOnFace(), primitiveMesh::faceEdges(), cellLooper::getFirstVertEdge(), Foam::meshTools::getSharedEdge(), cellLooper::getVertEdgesNonFace(), cellCuts::nonAnchorPoints(), boundaryMesh::patchNames(), faceCollapser::setRefinement(), directionInfo::updateCell(), and Foam::meshTools::walkFace().
pointEdges()
const Foam::labelListList & pointEdges () const
Definition at line 506 of file primitiveMeshEdges.C.
Referenced by snappyLayerDriver::addLayers(), polyDualMesh::calcFeatures(), addPatchCellLayer::calcSidePatch(), edgeCollapser::consistentCollapse(), globalMeshData::coupledPatchMeshEdges(), primitiveMesh::faceEdges(), Foam::meshTools::findEdge(), cellLooper::getVertEdgesNonFace(), addPatchCellLayer::globalEdgeFaces(), cellFeatures::isFeatureVertex(), edgeCollapser::markMergeEdges(), meshRefinement::mergeBaffles(), cellCuts::nonAnchorPoints(), listPlusEqOp< T >::operator()(), and primitiveMesh::pointPoints().
pointPoints() [1/3]
const Foam::labelListList & pointPoints () const
Definition at line 91 of file primitiveMeshPointPoints.C.
Referenced by primitiveMesh::pointPoints().
cellPoints() [1/3]
const Foam::labelListList & cellPoints () const
Definition at line 31 of file primitiveMeshCellPoints.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nCells(), primitiveMesh::pointCells(), and Foam::Pout.
Referenced by primitiveMesh::cellPoints(), cellCuts::nonAnchorPoints(), tetOverlapVolume::overlappingCells(), pointMVCWeight::pointMVCWeight(), and meshCutAndRemove::setRefinement().
cellCentres()
const Foam::vectorField & cellCentres () const
Definition at line 160 of file primitiveMeshCellCentresAndVols.C.
References primitiveMesh::calcCellCentresAndVols().
Referenced by polyTopoChange::addMesh(), snappySnapDriver::avgCellCentres(), tetOverlapVolume::cellCellOverlapMinDecomp(), tetOverlapVolume::cellCellOverlapVolumeMinDecomp(), polyMesh::checkFaceOrthogonality(), primitiveMesh::checkFaceOrthogonality(), primitiveMesh::checkFacePyramids(), polyMesh::checkFaceSkewness(), primitiveMesh::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMesh::checkFaceWeight(), motionSmootherAlgo::checkMesh(), fvPatch::Cn(), polyMeshGeometry::correct(), cellDistFuncs::correctBoundaryFaceCells(), cellDistFuncs::correctBoundaryPointCells(), meshRefinement::createZoneBaffles(), structuredDecomp::decompose(), decompositionMethod::decompose(), polyPatch::faceCellCentres(), cellQuality::faceNonOrthogonality(), mappedPatchBase::facePoint(), cellQuality::faceSkewness(), polyMeshTetDecomposition::findBasePoint(), probes::findElements(), polyMeshTetDecomposition::findFaceBasePts(), mapNearestMethod::findNearestCell(), primitiveMesh::findNearestCell(), mappedPatchBase::findSamples(), polyMeshTetDecomposition::findSharedBasePoint(), get_geom_list(), particle< Type >::initCellFacePt(), meshRefinement::mergeBaffles(), surfaceInterpolation::movePoints(), NamedEnum< directionType, 3 >::names(), cellQuality::nonOrthogonality(), treeDataCell::findNearestOp::operator()(), InflationInjection< CloudType >::parcelsToInject(), sampledSet::pushIn(), patchInjectionBase::setPositionAndCell(), tetDecomposer::setRefinement(), cellQuality::skewness(), tetIndices::tet(), particle< Type >::trackToFace(), sweepData::updateCell(), wallPoint::updateCell(), refinementDistanceData::updateCell(), cylindrical::updateCells(), reactingOneDim::updateQr(), meshToMeshMethod::writeConnectivity(), cellSet::writeDebug(), and meshRefinement::zonify().
faceCentres()
const Foam::vectorField & faceCentres () const
Definition at line 140 of file primitiveMeshFaceCentresAndAreas.C.
References primitiveMesh::calcFaceCentresAndAreas().
Referenced by preserveBafflesConstraint::add(), primitiveMesh::calcCellCentresAndVols(), sampledSet::calcSign(), primitiveMesh::checkConcaveCells(), primitiveMesh::checkFaceFlatness(), polyMesh::checkFaceSkewness(), primitiveMesh::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMesh::checkFaceWeight(), motionSmootherAlgo::checkMesh(), polyMeshGeometry::correct(), meshRefinement::createBaffles(), decompositionMethod::decompose(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), mappedPatchBase::facePoint(), cellQuality::faceSkewness(), probes::findElements(), patchProbes::findElements(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::findFaceDirs(), mappedPatchBase::findSamples(), boundaryMesh::getNearest(), meshRefinement::mergeBaffles(), meshTriangulation::meshTriangulation(), surfaceInterpolation::movePoints(), minEqOpFace::operator()(), listPlusEqOp< T >::operator()(), treeDataFace::findIntersectOp::operator()(), polyMesh::pointInCell(), primitiveMesh::pointInCell(), fvMeshDistribute::printCoupleInfo(), sampledSet::pushIn(), snappySnapDriver::repatchToSurface(), boundaryCutter::setRefinement(), tetDecomposer::setRefinement(), cellQuality::skewness(), meshRefinement::splitMesh(), Foam::fvc::sweep(), triSurfaceTools::triangulateFaceCentre(), wallPointYPlus::updateFace(), wallPointData< scalar >::updateFace(), sweepData::updateFace(), wallPoint::updateFace(), refinementDistanceData::updateFace(), and faceSet::writeDebug().
cellVolumes()
const Foam::scalarField & cellVolumes () const
Definition at line 171 of file primitiveMeshCellCentresAndVols.C.
References primitiveMesh::calcCellCentresAndVols().
Referenced by polyTopoChange::changeMesh(), layerAdditionRemoval::changeTopology(), primitiveMesh::checkCellVolumes(), primitiveMesh::checkClosedCells(), motionSmootherAlgo::checkMesh(), polyMesh::checkVolRatio(), polyMeshGeometry::correct(), cellPointWeight::findTetrahedron(), particle< Type >::hitWallFaces(), polyTopoChange::makeMesh(), particle< Type >::trackToFace(), and fvMesh::V().
faceAreas()
const Foam::vectorField & faceAreas () const
Definition at line 151 of file primitiveMeshFaceCentresAndAreas.C.
References primitiveMesh::calcFaceCentresAndAreas().
Referenced by normalToFace::applyToSet(), decompositionMethod::calcCellCells(), primitiveMesh::calcCellCentresAndVols(), sampledSet::calcSign(), layerAdditionRemoval::changeTopology(), edgeCollapser::checkBadFaces(), polyMesh::checkCellDeterminant(), primitiveMesh::checkClosedBoundary(), primitiveMesh::checkClosedCells(), primitiveMesh::checkConcaveCells(), primitiveMesh::checkFaceAngles(), primitiveMesh::checkFaceAreas(), primitiveMesh::checkFaceFlatness(), polyMesh::checkFaceOrthogonality(), primitiveMesh::checkFaceOrthogonality(), polyMesh::checkFaceSkewness(), primitiveMesh::checkFaceSkewness(), polyMesh::checkFaceWeight(), motionSmootherAlgo::checkMesh(), polyMeshGeometry::correct(), extendedUpwindCellToFaceStencil::extendedUpwindCellToFaceStencil(), cellQuality::faceNonOrthogonality(), cellQuality::faceSkewness(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::findFaceDirs(), cellPointWeight::findTriangle(), boundaryMesh::getNearest(), surfaceInterpolation::movePoints(), cellQuality::nonOrthogonality(), listPlusEqOp< T >::operator()(), primitiveMesh::pointInCell(), cellQuality::skewness(), and meshRefinement::zonify().
movePoints()
Foam::tmp< Foam::scalarField > movePoints (const pointField & p, const pointField & oldP)
Move points, returns volumes swept by faces in motion.
Definition at line 304 of file primitiveMesh.C.
References Foam::abort(), primitiveMesh::clearGeom(), f(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, primitiveMesh::nPoints(), tmp< T >::ref(), and List< T >::size().
Referenced by polyMesh::movePoints(), and primitiveMesh::reset().
isInternalFace()
bool isInternalFace (const label faceIndex) const inline
Return true if given face label is internal to the mesh.
Definition at line 100 of file primitiveMeshI.H.
References primitiveMesh::nInternalFaces().
Referenced by polyMeshGeometry::affectedCells(), preserveBafflesConstraint::apply(), preserveFaceZonesConstraint::apply(), singleProcessorFaceSetsConstraint::apply(), addPatchCellLayer::calcSidePatch(), edgeFaceCirculator::cellLabel(), repatchPolyTopoChanger::changePatchID(), primitiveMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceDotProduct(), primitiveMeshGeometry::checkFacePyramids(), polyMeshGeometry::checkFacePyramids(), primitiveMeshGeometry::checkFaceSkewness(), polyMeshGeometry::checkFaceSkewness(), polyMeshTetDecomposition::checkFaceTets(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), primitiveMeshGeometry::checkFaceWeights(), polyMeshGeometry::checkFaceWeights(), faceZone::checkParallelSync(), polyMeshGeometry::checkVolRatio(), outletStabilised< Type >::correction(), decompositionMethod::decompose(), primitiveMesh::edgeCells(), Foam::meshTools::faceOnCell(), primitiveMeshTools::facePyramidVolume(), get_edge_list(), get_num_edges_list(), Foam::meshTools::getSharedFace(), particle< Type >::internalFace(), meshRefinement::mergeBaffles(), meshTriangulation::meshTriangulation(), minEqOpFace::operator()(), listPlusEqOp< T >::operator()(), edgeFaceCirculator::operator++(), Foam::meshTools::otherCell(), edgeFaceCirculator::setCanonical(), fvMeshSubset::setCellSubset(), fvMeshSubset::setLargeCellSubset(), duplicatePoints::setRefinement(), perfectInterface::setRefinement(), boundaryCutter::setRefinement(), edgeCollapser::setRefinement(), fvMatrix< Type >::setValuesFromList(), meshRefinement::splitMesh(), outletStabilised< Type >::weights(), and meshRefinement::zonify().
checkUpperTriangular()
bool checkUpperTriangular (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check face ordering.
Definition at line 966 of file primitiveMeshCheck.C.
References Foam::constant::universal::c, cells, primitiveMesh::checkCellsZipUp(), Foam::endl(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::labelMax, Foam::reduce(), and List< T >::size().
Referenced by primitiveMesh::checkConcaveCells(), and primitiveMesh::checkTopology().
checkCellsZipUp()
bool checkCellsZipUp (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check cell zip-up.
Definition at line 1129 of file primitiveMeshCheck.C.
References Foam::constant::universal::c, cells, primitiveMesh::checkFaceVertices(), Foam::endl(), f(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::reduce(), and List< T >::size().
Referenced by primitiveMesh::checkTopology(), and primitiveMesh::checkUpperTriangular().
checkFaceVertices()
bool checkFaceVertices (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check uniqueness of face vertices.
Definition at line 1227 of file primitiveMeshCheck.C.
References primitiveMesh::checkPoints(), Foam::endl(), f(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), Foam::max(), Foam::min(), nPoints, Foam::reduce(), and List< T >::size().
Referenced by primitiveMesh::checkCellsZipUp(), and primitiveMesh::checkTopology().
checkPoints()
bool checkPoints (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for unused points.
Definition at line 1300 of file primitiveMeshCheck.C.
References primitiveMesh::checkDuplicateFaces(), UList< T >::empty(), Foam::endl(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), and Foam::reduce().
Referenced by primitiveMesh::checkFaceVertices(), and primitiveMesh::checkTopology().
checkFaceFaces()
bool checkFaceFaces (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check face-face connectivity.
Definition at line 1574 of file primitiveMeshCheck.C.
References HashTable< T, Key, Hash >::clear(), HashTableCore::end(), Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, Foam::Info, InfoInFunction, HashTable< T, Key, Hash >::insert(), and Foam::reduce().
Referenced by primitiveMesh::checkCommonOrder(), and primitiveMesh::checkTopology().
checkClosedBoundary() [2/2]
bool checkClosedBoundary (const bool report = false) const virtual
Check boundary for closedness.
Definition at line 1685 of file primitiveMeshCheck.C.
References primitiveMesh::checkClosedBoundary(), primitiveMesh::checkClosedCells(), and primitiveMesh::faceAreas().
checkClosedCells() [2/2]
bool checkClosedCells (const bool report = false, labelHashSet * setPtr = nullptr, labelHashSet * highAspectSetPtr = nullptr, const Vector< label > & solutionD = Vector<label>::one) const virtual
Check cells for closedness.
Definition at line 1692 of file primitiveMeshCheck.C.
References primitiveMesh::cellVolumes(), primitiveMesh::checkClosedCells(), primitiveMesh::checkFaceAreas(), and primitiveMesh::faceAreas().
checkFaceAreas() [2/2]
bool checkFaceAreas (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for negative face areas.
Definition at line 1712 of file primitiveMeshCheck.C.
References primitiveMesh::checkCellVolumes(), primitiveMesh::checkFaceAreas(), and primitiveMesh::faceAreas().
checkCellVolumes() [2/2]
bool checkCellVolumes (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for negative cell volumes.
Definition at line 1728 of file primitiveMeshCheck.C.
References primitiveMesh::cellVolumes(), primitiveMesh::checkCellVolumes(), and primitiveMesh::checkFaceOrthogonality().
checkFaceOrthogonality() [2/2]
bool checkFaceOrthogonality (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for non-orthogonality.
Reimplemented in polyMesh.
Definition at line 1744 of file primitiveMeshCheck.C.
References primitiveMesh::cellCentres(), primitiveMesh::checkFaceOrthogonality(), primitiveMesh::checkFacePyramids(), and primitiveMesh::faceAreas().
checkFacePyramids() [2/2]
bool checkFacePyramids (const bool report = false, const scalar minPyrVol = -SMALL, labelHashSet * setPtr = nullptr) const virtual
Check face pyramid volume.
Definition at line 1760 of file primitiveMeshCheck.C.
References primitiveMesh::cellCentres(), primitiveMesh::checkFacePyramids(), primitiveMesh::checkFaceSkewness(), and primitiveMesh::points().
checkFaceSkewness() [2/2]
bool checkFaceSkewness (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check face skewness.
Reimplemented in polyMesh.
Definition at line 1779 of file primitiveMeshCheck.C.
References primitiveMesh::cellCentres(), primitiveMesh::checkFaceAngles(), primitiveMesh::checkFaceSkewness(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), and primitiveMesh::points().
checkFaceAngles() [2/2]
bool checkFaceAngles (const bool report = false, const scalar maxSin = 10, labelHashSet * setPtr = nullptr) const virtual
Check face angles.
Definition at line 1797 of file primitiveMeshCheck.C.
References primitiveMesh::checkFaceAngles(), primitiveMesh::checkFaceFlatness(), primitiveMesh::faceAreas(), and primitiveMesh::points().
checkFaceFlatness() [2/2]
bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet * setPtr) const virtual
Check face warpage: decompose face and check ratio between.
magnitude of sum of triangle areas and sum of magnitude of triangle areas.
Definition at line 1815 of file primitiveMeshCheck.C.
References primitiveMesh::checkConcaveCells(), primitiveMesh::checkFaceFlatness(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), and primitiveMesh::points().
checkPointNearness()
bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet * setPtr = nullptr) const virtual
Check for point-point-nearness,.
e.g. colocated points which may be part of baffles.
Definition at line 32 of file primitiveMeshCheckPointNearness.C.
References Foam::endl(), SortableList< T >::indices(), Foam::Info, HashSet< Key, Hash >::insert(), Foam::magSqr(), points, Foam::reduce(), List< T >::size(), and Foam::sqrt().
checkEdgeLength()
bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet * setPtr = nullptr) const virtual
Check edge length.
Definition at line 31 of file primitiveMeshCheckEdgeLength.C.
References Foam::endl(), f(), UList< T >::fcIndex(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::magSqr(), Foam::max(), Foam::min(), nPoints, points, Foam::reduce(), HashTable< T, Key, Hash >::size(), Foam::sqr(), Foam::sqrt(), and HashTable< T, Key, Hash >::transfer().
checkConcaveCells() [2/2]
bool checkConcaveCells (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for concave cells by the planes of faces.
Definition at line 1834 of file primitiveMeshCheck.C.
References primitiveMesh::checkConcaveCells(), primitiveMesh::faceAreas(), and primitiveMesh::faceCentres().
checkTopology()
bool checkTopology (const bool report = false) const virtual
Check mesh topology for correctness.
Returns false for no error.
Definition at line 1849 of file primitiveMeshCheck.C.
References primitiveMesh::checkCellsZipUp(), primitiveMesh::checkFaceFaces(), primitiveMesh::checkFaceVertices(), primitiveMesh::checkPoints(), primitiveMesh::checkUpperTriangular(), Foam::endl(), and Foam::Info.
Referenced by primitiveMesh::checkMesh().
checkGeometry()
bool checkGeometry (const bool report = false) const virtual
Check mesh geometry (& implicitly topology) for correctness.
Returns false for no error.
Definition at line 1881 of file primitiveMeshCheck.C.
References primitiveMesh::checkCellVolumes(), primitiveMesh::checkClosedBoundary(), primitiveMesh::checkClosedCells(), primitiveMesh::checkFaceAreas(), primitiveMesh::checkFaceOrthogonality(), primitiveMesh::checkFacePyramids(), primitiveMesh::checkFaceSkewness(), Foam::endl(), and Foam::Info.
Referenced by primitiveMesh::checkMesh().
checkMesh()
bool checkMesh (const bool report = false) const virtual
Check mesh for correctness. Returns false for no error.
Definition at line 1914 of file primitiveMeshCheck.C.
References primitiveMesh::checkGeometry(), primitiveMesh::checkTopology(), Foam::endl(), Foam::Info, and InfoInFunction.
Referenced by attachPolyTopoChanger::attach(), and polyMesh::polyMesh().
setClosedThreshold()
Foam::scalar setClosedThreshold (const scalar val) static
Set the closedness ratio warning threshold.
Definition at line 1945 of file primitiveMeshCheck.C.
References primitiveMesh::closedThreshold_.
setAspectThreshold()
Foam::scalar setAspectThreshold (const scalar val) static
Set the aspect ratio warning threshold.
Definition at line 1954 of file primitiveMeshCheck.C.
References primitiveMesh::aspectThreshold_.
setNonOrthThreshold()
Foam::scalar setNonOrthThreshold (const scalar val) static
Set the non-orthogonality warning threshold in degrees.
Definition at line 1963 of file primitiveMeshCheck.C.
References primitiveMesh::nonOrthThreshold_.
setSkewThreshold()
Foam::scalar setSkewThreshold (const scalar val) static
Set the skewness warning threshold as percentage.
of the face area vector
Definition at line 1972 of file primitiveMeshCheck.C.
References primitiveMesh::skewThreshold_.
pointInCellBB()
bool pointInCellBB (const point & p, label celli, scalar inflationFraction = 0) const
Return true if the point in the cell bounding box.
The bounding box may be isotropically inflated by the fraction inflationFraction
Definition at line 33 of file primitiveMeshFindCell.C.
References cells, boundBox::contains(), Foam::mag(), VectorSpace< Form, Cmpt, Ncmpts >::max, points, and boundBox::span().
Referenced by particle< Type >::initCellFacePt().
pointInCell()
bool pointInCell (const point & p, label celli) const
Return true if the point is in the cell.
Definition at line 59 of file primitiveMeshFindCell.C.
References primitiveMesh::cells(), f(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), primitiveMesh::faceOwner(), and forAll.
Referenced by primitiveMesh::findCell(), and polyMesh::pointInCell().
findNearestCell()
Foam::label findNearestCell (const point & location) const
Find the cell with the nearest cell centre to location.
Definition at line 86 of file primitiveMeshFindCell.C.
References primitiveMesh::cellCentres(), Foam::magSqr(), and List< T >::size().
Referenced by polyMesh::findCell(), and primitiveMesh::findCell().
findCell()
Foam::label findCell (const point & location) const
Find cell enclosing this location (-1 if not in mesh)
Definition at line 108 of file primitiveMeshFindCell.C.
References primitiveMesh::findNearestCell(), n, primitiveMesh::nCells(), and primitiveMesh::pointInCell().
printAllocated()
void printAllocated () const
Print a list of all the currently allocated mesh data.
Definition at line 31 of file primitiveMeshClear.C.
References Foam::endl(), and Foam::Pout.
hasCellShapes()
bool hasCellShapes () const inline
Definition at line 106 of file primitiveMeshI.H.
hasEdges()
bool hasEdges () const inline
Definition at line 112 of file primitiveMeshI.H.
hasCellCells()
bool hasCellCells () const inline
Definition at line 118 of file primitiveMeshI.H.
Referenced by primitiveMesh::cellCells().
hasEdgeCells()
bool hasEdgeCells () const inline
Definition at line 124 of file primitiveMeshI.H.
Referenced by primitiveMesh::edgeCells().
hasPointCells()
bool hasPointCells () const inline
Definition at line 130 of file primitiveMeshI.H.
Referenced by primitiveMesh::pointCells().
hasCells()
bool hasCells () const inline
Definition at line 136 of file primitiveMeshI.H.
hasEdgeFaces()
bool hasEdgeFaces () const inline
Definition at line 142 of file primitiveMeshI.H.
Referenced by primitiveMesh::edgeFaces().
hasPointFaces()
bool hasPointFaces () const inline
Definition at line 148 of file primitiveMeshI.H.
hasCellEdges()
bool hasCellEdges () const inline
Definition at line 154 of file primitiveMeshI.H.
Referenced by primitiveMesh::cellEdges().
hasFaceEdges()
bool hasFaceEdges () const inline
Definition at line 160 of file primitiveMeshI.H.
Referenced by primitiveMesh::faceEdges().
hasPointEdges()
bool hasPointEdges () const inline
Definition at line 166 of file primitiveMeshI.H.
hasPointPoints()
bool hasPointPoints () const inline
Definition at line 172 of file primitiveMeshI.H.
Referenced by primitiveMesh::pointPoints().
hasCellPoints()
bool hasCellPoints () const inline
Definition at line 178 of file primitiveMeshI.H.
Referenced by primitiveMesh::cellPoints().
hasCellCentres()
bool hasCellCentres () const inline
Definition at line 184 of file primitiveMeshI.H.
hasFaceCentres()
bool hasFaceCentres () const inline
Definition at line 190 of file primitiveMeshI.H.
hasCellVolumes()
bool hasCellVolumes () const inline
Definition at line 196 of file primitiveMeshI.H.
hasFaceAreas()
bool hasFaceAreas () const inline
Definition at line 202 of file primitiveMeshI.H.
cellCells() [2/3]
const Foam::labelList & cellCells (const label celli, DynamicList< label > & storage) const
cellCells using cells.
Definition at line 112 of file primitiveMeshCellCells.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), primitiveMesh::cellCells(), primitiveMesh::cells(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), forAll, primitiveMesh::hasCellCells(), and primitiveMesh::nInternalFaces().
cellCells() [3/3]
const Foam::labelList & cellCells (const label celli) const
Definition at line 151 of file primitiveMeshCellCells.C.
References primitiveMesh::cellCells().
cellPoints() [2/3]
const Foam::labelList & cellPoints (const label celli, DynamicList< label > & storage) const
cellPoints using cells
Definition at line 59 of file primitiveMeshCellPoints.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::capacity(), primitiveMesh::cellPoints(), primitiveMesh::cells(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), HashTable< T, Key, Hash >::clear(), f(), primitiveMesh::faces(), forAll, forAllConstIter(), primitiveMesh::hasCellPoints(), HashSet< Key, Hash >::insert(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), and HashTable< T, Key, Hash >::size().
cellPoints() [3/3]
const Foam::labelList & cellPoints (const label celli) const
Definition at line 101 of file primitiveMeshCellPoints.C.
References primitiveMesh::cellPoints().
pointCells() [2/3]
const Foam::labelList & pointCells (const label pointi, DynamicList< label > & storage) const
pointCells using pointFaces
Definition at line 120 of file primitiveMeshPointCells.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), forAll, primitiveMesh::hasPointCells(), n, primitiveMesh::nInternalFaces(), pFaces, primitiveMesh::pointCells(), primitiveMesh::pointFaces(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::size(), and Foam::sort().
pointCells() [3/3]
const Foam::labelList & pointCells (const label pointi) const
Definition at line 174 of file primitiveMeshPointCells.C.
References primitiveMesh::pointCells().
pointPoints() [2/3]
const Foam::labelList & pointPoints (const label pointi, DynamicList< label > & storage) const
pointPoints using edges, pointEdges
Definition at line 103 of file primitiveMeshPointPoints.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::capacity(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), primitiveMesh::edges(), forAll, primitiveMesh::hasPointPoints(), primitiveMesh::pointEdges(), primitiveMesh::pointPoints(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), and List< T >::size().
pointPoints() [3/3]
const Foam::labelList & pointPoints (const label pointi) const
Definition at line 135 of file primitiveMeshPointPoints.C.
References primitiveMesh::pointPoints().
faceEdges() [2/3]
const Foam::labelList & faceEdges (const label facei, DynamicList< label > & storage) const
faceEdges using pointFaces, edges, pointEdges
Definition at line 580 of file primitiveMeshEdges.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::capacity(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), primitiveMesh::faceEdges(), primitiveMesh::faces(), forAll, primitiveMesh::hasFaceEdges(), face::nextLabel(), primitiveMesh::pointEdges(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), and List< T >::size().
faceEdges() [3/3]
const Foam::labelList & faceEdges (const label facei) const
Definition at line 617 of file primitiveMeshEdges.C.
References primitiveMesh::cellEdges(), and primitiveMesh::faceEdges().
edgeFaces() [2/3]
const Foam::labelList & edgeFaces (const label edgeI, DynamicList< label > & storage) const
edgeFaces using pointFaces, edges, pointEdges
Definition at line 58 of file primitiveMeshEdgeFaces.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), Foam::e, primitiveMesh::edgeFaces(), primitiveMesh::edges(), primitiveMesh::hasEdgeFaces(), primitiveMesh::pointFaces(), and List< T >::size().
edgeFaces() [3/3]
const Foam::labelList & edgeFaces (const label edgeI) const
Definition at line 103 of file primitiveMeshEdgeFaces.C.
References primitiveMesh::edgeFaces().
edgeCells() [2/3]
const Foam::labelList & edgeCells (const label edgeI, DynamicList< label > & storage) const
edgeCells using pointFaces, edges, pointEdges
Definition at line 58 of file primitiveMeshEdgeCells.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), primitiveMesh::edgeCells(), primitiveMesh::edgeFaces(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), forAll, primitiveMesh::hasEdgeCells(), and primitiveMesh::isInternalFace().
edgeCells() [3/3]
const Foam::labelList & edgeCells (const label edgeI) const
Definition at line 127 of file primitiveMeshEdgeCells.C.
References primitiveMesh::edgeCells().
cellEdges() [2/3]
const Foam::labelList & cellEdges (const label celli, DynamicList< label > & storage) const
cellEdges using cells, pointFaces, edges, pointEdges
Definition at line 624 of file primitiveMeshEdges.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::capacity(), primitiveMesh::cellEdges(), primitiveMesh::cells(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), HashTable< T, Key, Hash >::clear(), primitiveMesh::faceEdges(), forAll, forAllConstIter(), primitiveMesh::hasCellEdges(), HashSet< Key, Hash >::insert(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setCapacity(), and HashTable< T, Key, Hash >::size().
cellEdges() [3/3]
const Foam::labelList & cellEdges (const label celli) const
Definition at line 666 of file primitiveMeshEdges.C.
References primitiveMesh::cellEdges().
clearGeom()
void clearGeom ()
Clear geometry.
Definition at line 125 of file primitiveMeshClear.C.
References Foam::deleteDemandDrivenData(), Foam::endl(), and Foam::Pout.
Referenced by polyMesh::clearGeom(), primitiveMesh::clearOut(), primitiveMesh::movePoints(), and cyclicACMIPolyPatch::resetAMI().
clearAddressing()
void clearAddressing ()
Clear topological data.
Definition at line 141 of file primitiveMeshClear.C.
References Foam::deleteDemandDrivenData(), Foam::endl(), and Foam::Pout.
Referenced by polyMesh::cellZones(), polyMesh::clearAddressing(), polyMesh::clearOut(), primitiveMesh::clearOut(), polyMesh::resetPrimitives(), and fvMesh::updateMesh().
clearOut()
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Definition at line 170 of file primitiveMeshClear.C.
References primitiveMesh::clearAddressing(), and primitiveMesh::clearGeom().
Referenced by primitiveMesh::reset(), and primitiveMesh::~primitiveMesh().
Member Data Documentation
closedThreshold_
Foam::scalar closedThreshold_ = 1.0e-6 static protected
Static data to control mesh checking.
Cell closedness warning threshold
set as the fraction of un-closed area to closed area
Definition at line 234 of file primitiveMesh.H.
Referenced by primitiveMesh::setClosedThreshold().
aspectThreshold_
Foam::scalar aspectThreshold_ = 1000 static protected
Aspect ratio warning threshold.
Definition at line 237 of file primitiveMesh.H.
Referenced by primitiveMesh::setAspectThreshold().
nonOrthThreshold_
Foam::scalar nonOrthThreshold_ = 70 static protected
Non-orthogonality warning threshold in deg.
Definition at line 240 of file primitiveMesh.H.
Referenced by primitiveMesh::setNonOrthThreshold().
skewThreshold_
Foam::scalar skewThreshold_ = 4 static protected
Skewness warning threshold.
Definition at line 243 of file primitiveMesh.H.
Referenced by primitiveMesh::setSkewThreshold().
planarCosAngle_
Foam::scalar planarCosAngle_ = 1.0e-6 static protected
Threshold where faces are considered coplanar.
Definition at line 246 of file primitiveMesh.H.
cellsPerEdge_
const unsigned cellsPerEdge_ = 4 static
Estimated number of cells per edge.
Definition at line 407 of file primitiveMesh.H.
cellsPerPoint_
const unsigned cellsPerPoint_ = 8 static
Estimated number of cells per point.
Definition at line 410 of file primitiveMesh.H.
facesPerCell_
const unsigned facesPerCell_ = 6 static
Estimated number of faces per cell.
Definition at line 413 of file primitiveMesh.H.
facesPerEdge_
const unsigned facesPerEdge_ = 4 static
Estimated number of faces per edge.
Definition at line 416 of file primitiveMesh.H.
facesPerPoint_
const unsigned facesPerPoint_ = 12 static
Estimated number of faces per point.
Definition at line 419 of file primitiveMesh.H.
edgesPerCell_
const unsigned edgesPerCell_ = 12 static
Estimated number of edges per cell.
Definition at line 422 of file primitiveMesh.H.
edgesPerFace_
const unsigned edgesPerFace_ = 4 static
Estimated number of edges per cell.
Definition at line 425 of file primitiveMesh.H.
edgesPerPoint_
const unsigned edgesPerPoint_ = 6 static
Estimated number of edges per point.
Definition at line 428 of file primitiveMesh.H.
pointsPerCell_
const unsigned pointsPerCell_ = 8 static
Estimated number of points per cell.
Definition at line 431 of file primitiveMesh.H.
pointsPerFace_
const unsigned pointsPerFace_ = 4 static
Estimated number of points per face.
Definition at line 434 of file primitiveMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/primitiveMesh.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMesh.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCalcCellShapes.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellCentresAndVols.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellEdges.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellPoints.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheck.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheckEdgeLength.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheckPointNearness.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshClear.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdgeCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdgeFaces.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdges.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshFaceCentresAndAreas.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshFindCell.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshI.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointFaces.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointPoints.C