OpenFOAM: polyPatch Class Reference
polyPatch Class Reference
A patch is a list of labels that address the faces in the global face list.
Public Member Functions
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual bool coupled () const
Return true if this patch is geometrically coupled (i.e. faces and.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Static Public Member Functions
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &p)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
virtual void clearGeom ()
Clear geometry.
Friends
class polyBoundaryMesh
Ostream & operator<< (Ostream &, const polyPatch &)
Additional Inherited Members
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Detailed Description
A patch is a list of labels that address the faces in the global face list.
The patch can calculate its own edges based on the global faces. Patch also contains all addressing between the faces.
Source files
polyPatch.H
polyPatch.C
polyPatchNew.C
Definition at line 66 of file polyPatch.H.
Constructor & Destructor Documentation
polyPatch() [1/6]
polyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from components.
Definition at line 78 of file polyPatch.C.
References Foam::findIndex(), and word::null.
Referenced by polyPatch::clearGeom(), polyPatch::clone(), and polyPatch::polyPatch().
polyPatch() [2/6]
polyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 111 of file polyPatch.C.
References Foam::findIndex(), word::null, and polyPatch::polyPatch().
polyPatch() [3/6]
polyPatch (const polyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 148 of file polyPatch.C.
References polyPatch::polyPatch().
polyPatch() [4/6]
polyPatch (const polyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 172 of file polyPatch.C.
References polyPatch::polyPatch().
polyPatch() [5/6]
polyPatch (const polyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 199 of file polyPatch.C.
polyPatch() [6/6]
polyPatch (const polyPatch & p)
Construct as copy.
Definition at line 225 of file polyPatch.C.
~polyPatch()
~polyPatch () virtual
Destructor.
Definition at line 238 of file polyPatch.C.
References polyPatch::clearAddressing().
Referenced by polyPatch::clone().
Member Function Documentation
initGeometry()
virtual void initGeometry (PstreamBuffers &) inline protected virtual
Initialise the calculation of the patch geometry.
Reimplemented in oldCyclicPolyPatch, cyclicPolyPatch, cyclicAMIPolyPatch, coupledPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, regionCoupledPolyPatch, and regionCoupledWallPolyPatch.
Definition at line 100 of file polyPatch.H.
Referenced by regionCoupledPolyPatch::initGeometry(), regionCoupledWallPolyPatch::initGeometry(), mappedPolyPatch::initGeometry(), mappedWallPolyPatch::initGeometry(), cyclicAMIPolyPatch::initGeometry(), cyclicPolyPatch::initGeometry(), and oldCyclicPolyPatch::initGeometry().
calcGeometry()
virtual void calcGeometry (PstreamBuffers &) inline protected virtual
Calculate the patch geometry.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, coupledPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, wedgePolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, regionCoupledWallPolyPatch, and symmetryPlanePolyPatch.
Definition at line 104 of file polyPatch.H.
Referenced by regionCoupledWallPolyPatch::calcGeometry(), mappedPolyPatch::calcGeometry(), and mappedWallPolyPatch::calcGeometry().
initMovePoints()
virtual void initMovePoints (PstreamBuffers & , const pointField &) inline protected virtual
Initialise the patches for moving points.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, regionCoupledWallPolyPatch, and regionCoupledPolyPatch.
Definition at line 108 of file polyPatch.H.
References polyPatch::movePoints(), and p.
Referenced by regionCoupledPolyPatch::initMovePoints(), regionCoupledWallPolyPatch::initMovePoints(), mappedPolyPatch::initMovePoints(), mappedWallPolyPatch::initMovePoints(), cyclicAMIPolyPatch::initMovePoints(), oldCyclicPolyPatch::initMovePoints(), and cyclicPolyPatch::initMovePoints().
movePoints()
void movePoints (PstreamBuffers & , const pointField & p) protected virtual
Correct patches after moving points.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, regionCoupledWallPolyPatch, and regionCoupledPolyPatch.
Definition at line 57 of file polyPatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::movePoints().
Referenced by polyPatch::initMovePoints(), processorPolyPatch::initMovePoints(), regionCoupledPolyPatch::movePoints(), regionCoupledWallPolyPatch::movePoints(), mappedPolyPatch::movePoints(), mappedWallPolyPatch::movePoints(), cyclicAMIPolyPatch::movePoints(), oldCyclicPolyPatch::movePoints(), and cyclicPolyPatch::movePoints().
initUpdateMesh()
virtual void initUpdateMesh (PstreamBuffers &) inline protected virtual
Initialise the update of the patch topology.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, regionCoupledWallPolyPatch, and regionCoupledPolyPatch.
Definition at line 115 of file polyPatch.H.
References polyPatch::clearGeom(), polyPatch::TypeName(), and polyPatch::updateMesh().
Referenced by regionCoupledPolyPatch::initUpdateMesh(), regionCoupledWallPolyPatch::initUpdateMesh(), mappedPolyPatch::initUpdateMesh(), mappedWallPolyPatch::initUpdateMesh(), processorPolyPatch::initUpdateMesh(), cyclicAMIPolyPatch::initUpdateMesh(), oldCyclicPolyPatch::initUpdateMesh(), and cyclicPolyPatch::initUpdateMesh().
updateMesh()
void updateMesh (PstreamBuffers &) protected virtual
Update of the patch topology.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, regionCoupledWallPolyPatch, and regionCoupledPolyPatch.
Definition at line 62 of file polyPatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::clearGeom().
Referenced by polyPatch::initUpdateMesh(), regionCoupledPolyPatch::updateMesh(), regionCoupledWallPolyPatch::updateMesh(), mappedPolyPatch::updateMesh(), mappedWallPolyPatch::updateMesh(), processorPolyPatch::updateMesh(), cyclicAMIPolyPatch::updateMesh(), oldCyclicPolyPatch::updateMesh(), and cyclicPolyPatch::updateMesh().
clearGeom()
void clearGeom () protected virtual
Clear geometry.
Reimplemented in cyclicAMIPolyPatch, and cyclicACMIPolyPatch.
Definition at line 69 of file polyPatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::clearGeom(), and polyPatch::polyPatch().
Referenced by cyclicAMIPolyPatch::clearGeom(), and polyPatch::initUpdateMesh().
TypeName()
TypeName ("patch")
Runtime type information.
Referenced by polyPatch::initUpdateMesh().
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , polyPatch , word , (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType) , (name, size, start, index, bm, patchType))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , polyPatch , dictionary , (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType) , (name, dict, index, bm, patchType))
clone() [1/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented in cyclicPolyPatch, cyclicAMIPolyPatch, oldCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, mappedVariableThicknessWallPolyPatch, regionCoupledWallPolyPatch, regionCoupledPolyPatch, wedgePolyPatch, cyclicSlipPolyPatch, nonuniformTransformCyclicPolyPatch, symmetryPlanePolyPatch, genericPolyPatch, symmetryPolyPatch, emptyPolyPatch, and wallPolyPatch.
Definition at line 219 of file polyPatch.H.
References polyPatch::polyPatch().
Referenced by fvMeshTools::addPatch(), polyPatch::clone(), and boundaryMesh::patchify().
clone() [2/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented in cyclicPolyPatch, cyclicAMIPolyPatch, oldCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, mappedVariableThicknessWallPolyPatch, regionCoupledWallPolyPatch, regionCoupledPolyPatch, wedgePolyPatch, nonuniformTransformCyclicPolyPatch, cyclicSlipPolyPatch, symmetryPlanePolyPatch, genericPolyPatch, symmetryPolyPatch, emptyPolyPatch, and wallPolyPatch.
Definition at line 227 of file polyPatch.H.
References polyPatch::clone(), and polyPatch::polyPatch().
clone() [3/3]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented in cyclicPolyPatch, cyclicAMIPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, mappedWallPolyPatch, mappedPolyPatch, mappedVariableThicknessWallPolyPatch, regionCoupledWallPolyPatch, regionCoupledPolyPatch, nonuniformTransformCyclicPolyPatch, cyclicSlipPolyPatch, wedgePolyPatch, symmetryPlanePolyPatch, genericPolyPatch, symmetryPolyPatch, emptyPolyPatch, and wallPolyPatch.
Definition at line 243 of file polyPatch.H.
References polyPatch::New(), polyPatch::polyPatch(), and polyPatch::~polyPatch().
New() [1/3]
Foam::autoPtr< Foam::polyPatch > New (const word & patchType, const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from.
components
Definition at line 32 of file polyPatchNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, Foam::name(), and Foam::nl.
Referenced by meshRefinement::appendPatch(), polyPatch::clone(), extrudePatchMesh::extrudePatchMesh(), polyPatch::New(), boundaryMesh::patchify(), polyBoundaryMesh::polyBoundaryMesh(), polyMesh::polyMesh(), fvMeshDistribute::printCoupleInfo(), and thermalBaffleFvPatchScalarField::rmap().
New() [2/3]
Foam::autoPtr< Foam::polyPatch > New (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from.
dictionary
Definition at line 75 of file polyPatchNew.C.
References Foam::endl(), InfoInFunction, dictionary::lookup(), Foam::New(), polyPatch::New(), and dictionary::readIfPresent().
New() [3/3]
Foam::autoPtr< Foam::polyPatch > New (const word & patchType, const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from.
dictionary
Definition at line 95 of file polyPatchNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, Foam::name(), and Foam::nl.
start()
label start () const inline
Return start label of this patch in the polyMesh face list.
Definition at line 300 of file polyPatch.H.
References polyPatch::boundaryMesh(), polyPatch::constraintType(), polyPatch::constraintTypes(), polyPatch::coupled(), and polyPatch::patchInternalList().
Referenced by preservePatchesConstraint::add(), polyTopoChange::addMesh(), fvMeshTools::addPatch(), meshRefinement::addPatch(), cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), preserveFaceZonesConstraint::apply(), preservePatchesConstraint::apply(), searchableSurfaceToFaceZone::applyToSet(), decompositionMethod::calcCellCells(), cellToFaceStencil::calcFaceStencil(), polyDualMesh::calcFeatures(), processorCyclicPolyPatch::calcGeometry(), FaceCellWave< Type, TrackingData >::checkCyclic(), hexRef8::checkMesh(), edgeCollapser::checkMeshQuality(), meshRefinement::checkZoneFaces(), inverseFaceDistanceDiffusivity::correct(), particle< Type >::correctAfterParallelTransfer(), cellDistFuncs::correctBoundaryFaceCells(), globalMeshData::coupledPatch(), meshRefinement::createZoneBaffles(), structuredDecomp::decompose(), decompositionMethod::decompose(), ensightPartFaces::ensightPartFaces(), FaceCellWave< Type, TrackingData >::enterDomain(), faceCoupleInfo::faceLabels(), polyMeshTools::faceOrthogonality(), mappedPatchBase::facePoints(), polyMeshTools::faceSkewness(), polyMeshTools::faceWeights(), patchProbes::findElements(), mappedPatchBase::findSamples(), isoSurface::generateFaceTriPoints(), FaceCellWave< Type, TrackingData >::getChangedPatchFaces(), removeCells::getExposedFaces(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterFaces(), combineFaces::getMergeSets(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), particle< Type >::hitCyclicAMIPatch(), FreeStream< CloudType >::inflow(), sampledPatchInternalField::interpolateField(), sampledPatch::interpolateField(), isoSurface::isoSurface(), FaceCellWave< Type, TrackingData >::leaveDomain(), meshRefinement::makePatch(), fvMeshAdder::MapVolFields(), meshRefinement::mergeBaffles(), FaceCellWave< Type, TrackingData >::mergeFaceInfo(), meshRefinement::mergePatchFacesUndo(), NamedEnum< directionType, 3 >::names(), minEqOp< labelPair >::operator()(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), combine< Type, TrackingData >::operator()(), boundaryMesh::patchify(), boundaryMesh::patchNames(), fvMeshDistribute::printCoupleInfo(), fvMeshDistribute::printMeshInfo(), thermalBaffleModel::read(), boundaryMesh::read(), structuredRenumber::renumber(), snappySnapDriver::repatchToSurface(), meshRefinement::selectSeparatedCoupledFaces(), rotorDiskSource::setFaceArea(), fvMeshSubset::setLargeCellSubset(), removeCells::setRefinement(), perfectInterface::setRefinement(), removeFaces::setRefinement(), cellDistFuncs::smallestDist(), Foam::fvc::smooth(), Foam::fvc::spread(), fvPatch::start(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), Foam::fvc::sweep(), syncTools::syncBoundaryFaceList(), syncTools::syncFaceList(), meshRefinement::testSyncBoundaryFaceList(), cyclicPolyPatch::transformGlobalFace(), triSurfaceTools::triangulateFaceCentre(), sampledPatch::update(), cellToFaceStencil::validBoundaryFaces(), cellToCellStencil::validBoundaryFaces(), polyMeshTools::volRatio(), wallLayerCells::wallLayerCells(), polyBoundaryMesh::whichPatch(), regionSizeDistribution::write(), polyPatch::write(), and meshRefinement::zonify().
boundaryMesh()
const Foam::polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
Definition at line 278 of file polyPatch.C.
Referenced by processorPolyPatch::comm(), patchPatchDist::correct(), PointEdgeWave< Type, TrackingData >::countPatchType(), polyPatch::faceAreas(), polyPatch::faceCells(), polyPatch::faceCentres(), mappedPatchBase::facePoints(), coupleGroupIdentifier::findOtherPatchID(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), FaceCellWave< Type, TrackingData >::handleCyclicPatches(), meshToMesh::interpolationMethodAMI(), regionModel::interRegionAMI(), polyPatch::meshEdges(), NamedEnum< directionType, 3 >::names(), regionModel::nbrCoupledPatchID(), cyclicPolyPatch::neighbPatch(), cyclicAMIPolyPatch::neighbPatchName(), cyclicACMIPolyPatch::nonOverlapPatch(), ListPlusEqOp< T, Size >::operator()(), wallBoundedParticle::patchInteraction(), fvMeshDistribute::printCoupleInfo(), processorCyclicPolyPatch::referPatch(), processorCyclicPolyPatch::referPatchID(), mappedPatchBase::samplePatch(), mappedPatchBase::sampleRegion(), polyPatch::start(), outletMappedUniformInletFvPatchField< Type >::updateCoeffs(), and dsmcFields::write().
coupled()
virtual bool coupled () const inline virtual
Return true if this patch is geometrically coupled (i.e. faces and.
points correspondence)
Reimplemented in cyclicAMIPolyPatch, processorPolyPatch, coupledPolyPatch, and regionCoupledPolyPatch.
Definition at line 310 of file polyPatch.H.
Referenced by cellToCellStencil::allCoupledFacesPatch(), cellToFaceStencil::allCoupledFacesPatch(), searchableSurfaceToFaceZone::applyToSet(), decompositionMethod::calcCellCells(), cellToFaceStencil::calcFaceStencil(), hexRef8::checkMesh(), edgeCollapser::checkMeshQuality(), regionCoupledWallFvPatch::coupled(), fvPatch::coupled(), facePointPatch::coupled(), globalMeshData::coupledPatch(), meshRefinement::createZoneBaffles(), decompositionMethod::decompose(), snappyLayerDriver::doLayers(), polyMeshTools::faceOrthogonality(), polyMeshTools::faceSkewness(), polyMeshTools::faceWeights(), isoSurface::generateFaceTriPoints(), removeCells::getExposedFaces(), syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), combineFaces::getMergeSets(), isoSurface::isoSurface(), meshRefinement::mergeBaffles(), meshRefinement::mergePatchFacesUndo(), NamedEnum< directionType, 3 >::names(), minEqOp< labelPair >::operator()(), listPlusEqOp< T >::operator()(), nearestEqOp::operator()(), patchInteractionDataList::patchInteractionDataList(), fvMeshDistribute::printCoupleInfo(), rotorDiskSource::setFaceArea(), removeCells::setRefinement(), Foam::fvc::smooth(), Foam::fvc::spread(), polyPatch::start(), Foam::fvc::sweep(), cellToCellStencil::validBoundaryFaces(), cellToFaceStencil::validBoundaryFaces(), polyMeshTools::volRatio(), and meshRefinement::zonify().
constraintType()
bool constraintType (const word & pt) static
Return true if the given type is a constraint type.
Definition at line 246 of file polyPatch.C.
Referenced by polyPatch::constraintTypes(), Foam::evaluateConstraintTypes(), meshRefinement::meshedPatches(), Foam::reusable(), and polyPatch::start().
constraintTypes()
Foam::wordList constraintTypes () static
Return a list of all the constraint patch types.
Definition at line 252 of file polyPatch.C.
References polyPatch::constraintType(), and List< T >::setSize().
Referenced by polyPatch::start().
patchInternalList()
const UIndirectList<T> patchInternalList (const UList< T > & internalValues) const inline
Extract face cell data.
Definition at line 324 of file polyPatch.H.
References polyPatch::faceCells().
Referenced by FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), and polyPatch::start().
patchSlice() [1/2]
const List<T>::subList patchSlice (const UList< T > & l) const inline
Slice list to patch.
Definition at line 333 of file polyPatch.H.
Referenced by polyPatch::faceAreas(), polyPatch::faceCells(), polyPatch::faceCentres(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), and isoSurface::isoSurface().
patchSlice() [2/2]
const Field<T>::subField patchSlice (const Field< T > & l) const inline
Slice Field to patch.
Definition at line 340 of file polyPatch.H.
References polyPatch::clearAddressing(), polyPatch::faceAreas(), polyPatch::faceCellCentres(), polyPatch::faceCells(), polyPatch::faceCentres(), polyPatch::meshEdges(), and polyPatch::write().
write()
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, oldCyclicPolyPatch, mappedWallPolyPatch, mappedVariableThicknessWallPolyPatch, mappedPolyPatch, regionCoupledPolyPatch, regionCoupledWallPolyPatch, and genericPolyPatch.
Definition at line 357 of file polyPatch.C.
References token::END_STATEMENT, Foam::nl, polyPatch::start(), Foam::type(), patchIdentifier::write(), and Ostream::writeKeyword().
Referenced by Foam::operator<<(), polyPatch::patchSlice(), regionCoupledWallPolyPatch::write(), regionCoupledPolyPatch::write(), mappedPolyPatch::write(), mappedWallPolyPatch::write(), and coupledPolyPatch::write().
faceCentres()
const Foam::vectorField::subField faceCentres () const
Return face centres.
Definition at line 284 of file polyPatch.C.
References polyPatch::boundaryMesh(), mesh, and polyPatch::patchSlice().
Referenced by cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), inverseFaceDistanceDiffusivity::correct(), FaceCellWave< Type, TrackingData >::handleAMICyclicPatches(), FreeStream< CloudType >::inflow(), coupledPolyPatch::matchTolerance(), NamedEnum< directionType, 3 >::names(), polyPatch::patchSlice(), forces::read(), and movingWallVelocityFvPatchVectorField::updateCoeffs().
faceAreas()
const Foam::vectorField::subField faceAreas () const
Return face normals.
Definition at line 290 of file polyPatch.C.
References polyPatch::boundaryMesh(), mesh, and polyPatch::patchSlice().
Referenced by DSMCParcel< ParcelType >::hitWallPatch(), FreeStream< CloudType >::inflow(), regionModel1D::moveMesh(), NamedEnum< directionType, 3 >::names(), cyclicACMIPolyPatch::nonOverlapPatchID(), polyPatch::patchSlice(), cyclicACMIPolyPatch::resetAMI(), cyclicACMIFvPatch::updateAreas(), patchInjectionBase::updateMesh(), and dsmcFields::write().
faceCellCentres()
Foam::tmp< Foam::vectorField > faceCellCentres () const
Return face cell centres.
Definition at line 296 of file polyPatch.C.
References primitiveMesh::cellCentres(), polyPatch::faceCells(), forAll, polyBoundaryMesh::mesh(), and tmp< T >::ref().
Referenced by nearWallFields::calcAddressing(), and polyPatch::patchSlice().
faceCells()
const Foam::labelUList & faceCells () const
Return face-cell addressing.
Definition at line 315 of file polyPatch.C.
References polyPatch::boundaryMesh(), mesh, and polyPatch::patchSlice().
Referenced by preserveFaceZonesConstraint::apply(), preservePatchesConstraint::apply(), edgeCollapser::checkMeshQuality(), patchInjection::correct(), particle< Type >::correctAfterParallelTransfer(), structuredDecomp::decompose(), snappyLayerDriver::doLayers(), polyPatch::faceCellCentres(), fvPatch::faceCells(), NamedEnum< directionType, 3 >::names(), ListPlusEqOp< T, Size >::operator()(), polyPatch::patchInternalList(), cyclicACMIFvPatchField< Type >::patchNeighbourField(), polyPatch::patchSlice(), fvMeshDistribute::printCoupleInfo(), structuredRenumber::renumber(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), cyclicACMIFvPatchField< Type >::updateInterfaceMatrix(), patchInjectionBase::updateMesh(), thermoSingleLayer::updateSurfaceTemperatures(), kinematicSingleLayer::updateSurfaceVelocities(), and leastSquaresVectors::~leastSquaresVectors().
meshEdges()
const Foam::labelList & meshEdges () const
Return global edge index for local edges.
Definition at line 329 of file polyPatch.C.
References polyPatch::boundaryMesh(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), mesh, PrimitivePatch< Face, FaceList, PointField, PointType >::meshEdges(), and PrimitivePatch< Face, FaceList, PointField, PointType >::pointEdges().
Referenced by polyPatch::patchSlice().
clearAddressing()
void clearAddressing () virtual
Clear addressing.
Definition at line 348 of file polyPatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::clearPatchMeshAddr(), PrimitivePatch< Face, FaceList, PointField, PointType >::clearTopology(), and Foam::deleteDemandDrivenData().
Referenced by polyPatch::operator=(), polyPatch::patchSlice(), and polyPatch::~polyPatch().
whichFace()
label whichFace (const label l) const inline
Return label of face in patch from global face label.
Definition at line 377 of file polyPatch.H.
References Foam::faceMap(), polyPatch::initOrder(), polyPatch::operator<<, polyPatch::operator=(), and polyPatch::order().
Referenced by MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), LocalInteraction< CloudType >::correct(), FacePostProcessing< CloudType >::FacePostProcessing(), particle< Type >::hitCyclicPatch(), DSMCParcel< ParcelType >::hitWallPatch(), fvMeshSubset::interpolate(), NamedEnum< directionType, 3 >::names(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::patchData(), ParticleErosion< CloudType >::postPatch(), and ThermoSurfaceFilm< CloudType >::transferParcel().
initOrder()
void initOrder (PstreamBuffers & , const primitivePatch &) const virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Reimplemented in cyclicPolyPatch, cyclicAMIPolyPatch, processorCyclicPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, and oldCyclicPolyPatch.
Definition at line 366 of file polyPatch.C.
References polyPatch::order().
Referenced by polyPatch::whichFace().
order()
bool order (PstreamBuffers & , const primitivePatch & , labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Reimplemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, and oldCyclicPolyPatch.
Definition at line 371 of file polyPatch.C.
Referenced by polyPatch::initOrder(), and polyPatch::whichFace().
operator=()
void operator= (const polyPatch & p)
Assignment.
Definition at line 385 of file polyPatch.C.
References polyPatch::clearAddressing(), and PrimitivePatch< Face, FaceList, PointField, PointType >::operator=().
Referenced by polyPatch::whichFace().
Friends And Related Function Documentation
polyBoundaryMesh
friend class polyBoundaryMesh friend
Definition at line 97 of file polyPatch.H.
operator<<
Ostream& operator<< (Ostream & , const polyPatch &) friend
Referenced by polyPatch::whichFace().
Member Data Documentation
disallowGenericPolyPatch
int disallowGenericPolyPatch static
Debug switch to disallow the use of genericPolyPatch.
Definition at line 131 of file polyPatch.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/polyPatch/polyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/polyPatch/polyPatch.C
src/OpenFOAM/meshes/polyMesh/polyPatches/polyPatch/polyPatchNew.C