OpenFOAM: faceZone Class Reference
faceZone Class Reference
A subset of mesh faces organised as a primitive patch.
Public Member Functions
TypeName ("faceZone")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, faceZone, dictionary,(const word &name, const dictionary &dict, const label index, const faceZoneMesh &zm),(name, dict, index, zm))
faceZone (const word &name, const labelUList &addr, const boolList &fm, const label index, const faceZoneMesh &zm)
Construct from components.
faceZone (const word &name, const Xfer< labelList > &addr, const Xfer< boolList > &fm, const label index, const faceZoneMesh &)
Construct from components, transferring contents.
faceZone (const word &name, const dictionary &, const label index, const faceZoneMesh &)
Construct from dictionary.
faceZone (const faceZone &, const labelUList &addr, const boolList &fm, const label index, const faceZoneMesh &)
Construct given the original zone and resetting the.
faceZone (const faceZone &, const Xfer< labelList > &addr, const Xfer< boolList > &fm, const label index, const faceZoneMesh &)
Construct given the original zone, resetting the.
virtual autoPtr< faceZone > clone (const faceZoneMesh &zm) const
Construct and return a clone, resetting the zone mesh.
virtual autoPtr< faceZone > clone (const labelUList &addr, const boolList &fm, const label index, const faceZoneMesh &zm) const
Construct and return a clone, resetting the face list.
virtual ~faceZone ()
Destructor.
const boolList & flipMap () const
Return face flip map.
label whichFace (const label globalCellID) const
Helper function to re-direct to zone::localID(...)
const primitiveFacePatch & operator() () const
Return reference to primitive patch.
const faceZoneMesh & zoneMesh () const
Return zoneMesh reference.
const labelList & masterCells () const
Return labels of master cells (cells next to the master face.
const labelList & slaveCells () const
Return labels of slave cells.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
virtual void resetAddressing (const labelUList &, const boolList &)
Reset addressing and flip map (clearing demand-driven data)
virtual bool checkDefinition (const bool report=false) const
Check zone definition. Return true if in error.
virtual bool checkParallelSync (const bool report=false) const
Check whether all procs have faces synchronised. Return.
virtual void movePoints (const pointField &)
Correct patch after moving points.
virtual void updateMesh (const mapPolyMesh &)
Update for changes in topology.
virtual void write (Ostream &) const
Write.
virtual void writeDict (Ostream &) const
Write dictionary.
Public Member Functions inherited from zone
TypeName ("zone")
Runtime type information.
zone (const word &name, const labelUList &addr, const label index)
Construct from components.
zone (const word &name, const Xfer< labelList > &addr, const label index)
Construct from components, transferring contents.
zone (const word &name, const dictionary &, const word &labelsName, const label index)
Construct from dictionary.
zone (const zone &, const labelUList &addr, const label index)
Construct given the original zone and resetting the.
zone (const zone &, const Xfer< labelList > &addr, const label index)
Construct given the original zone, resetting the.
virtual ~zone ()
Destructor.
const word & name () const
Return name.
label localID (const label globalID) const
Map storing the local index for every global index. Used to find.
label index () const
Return the index of this zone in zone list.
virtual bool checkDefinition (const label maxSize, const bool report=false) const
Check zone definition with max size given. Return true if in error.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static autoPtr< faceZone > New (const word &name, const dictionary &, const label index, const faceZoneMesh &)
Return a pointer to a new face zone.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes
static const char *const labelsName = "faceLabels"
The name associated with the zone-labels dictionary entry.
Protected Member Functions
void calcFaceZonePatch () const
Build primitive patch.
const Map< label > & faceLookupMap () const
Return map of local face indices.
void calcCellLayers () const
Calculate master and slave face layer.
void checkAddressing () const
Check addressing.
Protected Member Functions inherited from zone
const Map< label > & lookupMap () const
Return a reference to the look-up map.
void calcLookupMap () const
Construct the look-up map.
zone (const zone &)
Disallow default bitwise copy construct.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Attributes
boolList flipMap_
Flip map for all faces in the zone. Set to true if the.
const faceZoneMesh & zoneMesh_
Reference to zone list.
primitiveFacePatch * patchPtr_
Primitive patch made out of correctly flipped faces.
labelList * masterCellsPtr_
Master cell layer.
labelList * slaveCellsPtr_
Slave cell layer.
labelList * mePtr_
Global edge addressing.
Protected Attributes inherited from zone
word name_
Name of zone.
label index_
Index of zone.
Map< label > * lookupMapPtr_
Map of labels in zone for fast location lookup.
Friends
Ostream & operator<< (Ostream &, const faceZone &)
Ostream Operator.
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Detailed Description
A subset of mesh faces organised as a primitive patch.
For quick check whether a face belongs to the zone use the lookup mechanism in faceZoneMesh, where all the zoned faces are registered with their zone number.
Source files
faceZone.H
faceZone.C
faceZoneNew.C
Definition at line 64 of file faceZone.H.
Constructor & Destructor Documentation
faceZone() [1/5]
faceZone (const word & name, const labelUList & addr, const boolList & fm, const label index, const faceZoneMesh & zm)
Construct from components.
Definition at line 186 of file faceZone.C.
faceZone() [2/5]
faceZone (const word & name, const Xfer< labelList > & addr, const Xfer< boolList > & fm, const label index, const faceZoneMesh & zm)
Construct from components, transferring contents.
Definition at line 207 of file faceZone.C.
faceZone() [3/5]
faceZone (const word & name, const dictionary & dict, const label index, const faceZoneMesh & zm)
Construct from dictionary.
Definition at line 228 of file faceZone.C.
faceZone() [4/5]
faceZone (const faceZone & fz, const labelUList & addr, const boolList & fm, const label index, const faceZoneMesh & zm)
Construct given the original zone and resetting the.
face list and zone mesh information
Definition at line 248 of file faceZone.C.
faceZone() [5/5]
faceZone (const faceZone & fz, const Xfer< labelList > & addr, const Xfer< boolList > & fm, const label index, const faceZoneMesh & zm)
Construct given the original zone, resetting the.
face list and zone mesh information
Definition at line 269 of file faceZone.C.
~faceZone()
~faceZone () virtual
Destructor.
Definition at line 291 of file faceZone.C.
Referenced by faceZone::clone().
Member Function Documentation
calcFaceZonePatch()
void calcFaceZonePatch () const protected
Build primitive patch.
Definition at line 48 of file faceZone.C.
References Foam::abort(), Foam::endl(), f(), Foam::FatalError, FatalErrorInFunction, forAll, InfoInFunction, mesh, and points.
faceLookupMap()
const Map<label>& faceLookupMap () const protected
Return map of local face indices.
calcCellLayers()
void calcCellLayers () const protected
Calculate master and slave face layer.
Definition at line 95 of file faceZone.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, InfoInFunction, and List< T >::size().
checkAddressing()
void checkAddressing () const protected
Check addressing.
Definition at line 154 of file faceZone.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, List< T >::size(), and WarningInFunction.
TypeName()
TypeName ("faceZone")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , faceZone , dictionary , (const word &name, const dictionary &dict, const label index, const faceZoneMesh &zm) , (name, dict, index, zm))
clone() [1/2]
virtual autoPtr<faceZone> clone (const faceZoneMesh & zm) const inline virtual
Construct and return a clone, resetting the zone mesh.
Definition at line 208 of file faceZone.H.
References List< T >::clone(), faceZone::flipMap(), and zone::index().
clone() [2/2]
virtual autoPtr<faceZone> clone (const labelUList & addr, const boolList & fm, const label index, const faceZoneMesh & zm) const inline virtual
Construct and return a clone, resetting the face list.
and zone mesh
Definition at line 219 of file faceZone.H.
References faceZone::New(), and faceZone::~faceZone().
New()
Foam::autoPtr< Foam::faceZone > New (const word & name, const dictionary & dict, const label index, const faceZoneMesh & zm) static
Return a pointer to a new face zone.
created on freestore from dictionary
Definition at line 32 of file faceZoneNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, dictionary::lookup(), Foam::name(), and Foam::nl.
Referenced by faceZone::clone().
flipMap()
const boolList& flipMap () const inline
Return face flip map.
Definition at line 253 of file faceZone.H.
References faceZone::checkDefinition(), faceZone::checkParallelSync(), faceZone::clearAddressing(), faceZone::flipMap_, faceZone::masterCells(), faceZone::meshEdges(), faceZone::movePoints(), faceZone::operator()(), faceZone::operator<<, faceZone::resetAddressing(), faceZone::slaveCells(), faceZone::updateMesh(), faceZone::whichFace(), faceZone::write(), faceZone::writeDict(), and faceZone::zoneMesh().
Referenced by repatchPolyTopoChanger::changeAnchorPoint(), repatchPolyTopoChanger::changePatchID(), faceZone::clone(), faceZoneSet::faceZoneSet(), meshRefinement::mergeBaffles(), polyMeshAdder::mergePoints(), NamedEnum< directionType, 3 >::names(), faceEqOp< T, CombineOp >::operator()(), ifEqEqOp< value >::operator()(), fvMeshDistribute::printCoupleInfo(), removeCells::setRefinement(), duplicatePoints::setRefinement(), perfectInterface::setRefinement(), combineFaces::setRefinement(), tetDecomposer::setRefinement(), edgeCollapser::setRefinement(), addPatchCellLayer::setRefinement(), combineFaces::setUnrefinement(), and meshRefinement::splitFaces().
whichFace()
Foam::label whichFace (const label globalCellID) const
Helper function to re-direct to zone::localID(...)
Definition at line 305 of file faceZone.C.
References zone::localID().
Referenced by repatchPolyTopoChanger::changeAnchorPoint(), repatchPolyTopoChanger::changePatchID(), faceZone::flipMap(), edgeCollapser::markFaceZoneEdges(), meshRefinement::mergeBaffles(), polyMeshAdder::mergePoints(), faceEqOp< T, CombineOp >::operator()(), ifEqEqOp< value >::operator()(), fvMeshDistribute::printCoupleInfo(), removeCells::setRefinement(), duplicatePoints::setRefinement(), perfectInterface::setRefinement(), combineFaces::setRefinement(), tetDecomposer::setRefinement(), edgeCollapser::setRefinement(), addPatchCellLayer::setRefinement(), combineFaces::setUnrefinement(), and meshRefinement::splitFaces().
operator()()
const Foam::primitiveFacePatch & operator() () const
Return reference to primitive patch.
Definition at line 311 of file faceZone.C.
Referenced by faceZone::flipMap().
zoneMesh()
const Foam::faceZoneMesh & zoneMesh () const
Return zoneMesh reference.
Definition at line 299 of file faceZone.C.
Referenced by faceZone::flipMap().
masterCells()
const Foam::labelList & masterCells () const
Return labels of master cells (cells next to the master face.
zone in the prescribed direction)
Definition at line 322 of file faceZone.C.
Referenced by layerAdditionRemoval::changeTopology(), faceZone::flipMap(), and NamedEnum< directionType, 3 >::names().
slaveCells()
const Foam::labelList & slaveCells () const
Return labels of slave cells.
Definition at line 333 of file faceZone.C.
Referenced by faceZone::flipMap(), and NamedEnum< directionType, 3 >::names().
meshEdges()
const Foam::labelList & meshEdges () const
Return global edge index for local edges.
Definition at line 344 of file faceZone.C.
References mesh.
Referenced by faceZone::flipMap().
clearAddressing()
void clearAddressing () virtual
Clear addressing.
Reimplemented from zone.
Definition at line 363 of file faceZone.C.
References zone::clearAddressing(), Foam::deleteDemandDrivenData(), and faceZone::resetAddressing().
Referenced by faceZone::flipMap().
resetAddressing()
void resetAddressing (const labelUList & addr, const boolList & flipMap) virtual
Reset addressing and flip map (clearing demand-driven data)
Definition at line 377 of file faceZone.C.
References List< label >::operator=().
Referenced by faceZone::clearAddressing(), and faceZone::flipMap().
checkDefinition()
bool checkDefinition (const bool report = false) const virtual
Check zone definition. Return true if in error.
Implements zone.
Definition at line 418 of file faceZone.C.
References zone::checkDefinition(), and mesh.
Referenced by faceZone::flipMap().
checkParallelSync()
bool checkParallelSync (const bool report = false) const virtual
Check whether all procs have faces synchronised. Return.
true if in error.
Definition at line 424 of file faceZone.C.
References polyMesh::boundaryMesh(), Foam::endl(), forAll, primitiveMesh::isInternalFace(), mesh, Foam::name(), IOobject::name(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patchi, Foam::Pout, Foam::returnReduce(), syncTools::swapBoundaryFaceList(), and polyBoundaryMesh::whichPatch().
Referenced by faceZone::flipMap().
movePoints()
void movePoints (const pointField & p) virtual
Correct patch after moving points.
Reimplemented from zone.
Definition at line 513 of file faceZone.C.
Referenced by faceZone::flipMap().
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes in topology.
Definition at line 388 of file faceZone.C.
References Foam::faceMap(), forAll, mapPolyMesh::reverseFaceMap(), and List< T >::setSize().
Referenced by faceZone::flipMap().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from zone.
Definition at line 521 of file faceZone.C.
References Foam::name(), and Foam::nl.
Referenced by faceZone::flipMap(), and Foam::operator<<().
writeDict()
void writeDict (Ostream & os) const virtual
Write dictionary.
Implements zone.
Definition at line 529 of file faceZone.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::name(), Foam::nl, Foam::type(), and UList< T >::writeEntry().
Referenced by faceZone::flipMap().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const faceZone &) friend
Ostream Operator.
Referenced by faceZone::flipMap().
Member Data Documentation
flipMap_
boolList flipMap_ protected
Flip map for all faces in the zone. Set to true if the.
face needs to be flipped to achieve the correct orientation.
Definition at line 89 of file faceZone.H.
Referenced by faceZone::flipMap().
zoneMesh_
const faceZoneMesh& zoneMesh_ protected
Reference to zone list.
Definition at line 92 of file faceZone.H.
patchPtr_
primitiveFacePatch* patchPtr_ mutable protected
Primitive patch made out of correctly flipped faces.
Definition at line 98 of file faceZone.H.
masterCellsPtr_
labelList* masterCellsPtr_ mutable protected
Master cell layer.
Definition at line 101 of file faceZone.H.
slaveCellsPtr_
labelList* slaveCellsPtr_ mutable protected
Slave cell layer.
Definition at line 104 of file faceZone.H.
mePtr_
labelList* mePtr_ mutable protected
Global edge addressing.
Definition at line 107 of file faceZone.H.
labelsName
const char *const labelsName = "faceLabels" static
The name associated with the zone-labels dictionary entry.
Definition at line 130 of file faceZone.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/zones/faceZone/faceZone.H
src/OpenFOAM/meshes/polyMesh/zones/faceZone/faceZone.C
src/OpenFOAM/meshes/polyMesh/zones/faceZone/faceZoneNew.C