OpenFOAM: processorCyclicPolyPatch Class Reference
processorCyclicPolyPatch Class Reference
Neighbour processor patch.
Public Member Functions
TypeName ("processorCyclic")
Runtime type information.
processorCyclicPolyPatch (const label size, const label start, const label index, const polyBoundaryMesh &bm, const int myProcNo, const int neighbProcNo, const word &referPatchName, const transformType transform=UNKNOWN, const word &patchType=typeName)
Construct from components.
processorCyclicPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &, const word &patchType)
Construct from dictionary.
processorCyclicPolyPatch (const processorCyclicPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
processorCyclicPolyPatch (const processorCyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct as given the original patch and resetting the.
processorCyclicPolyPatch (const processorCyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &referPatchName)
Construct as given the original patch and resetting the.
processorCyclicPolyPatch (const processorCyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &referPatchName) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~processorCyclicPolyPatch ()
const word & referPatchName () const
Return name of originating cyclicPolyPatch patch.
label referPatchID () const
Referring patchID.
const coupledPolyPatch & referPatch () const
virtual int tag () const
Return message tag to use for communication.
virtual bool owner () const
Does this side own the patch ?
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual void transformPosition (pointField &l) const
Transform a patch-based position from other side to this side.
virtual void transformPosition (point &l, const label facei) const
Transform a patch-based position from other side to this side.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from processorPolyPatch
TypeName ("processor")
Runtime type information.
processorPolyPatch (const label size, const label start, const label index, const polyBoundaryMesh &bm, const int myProcNo, const int neighbProcNo, const transformType transform=UNKNOWN, const word &patchType=typeName)
Construct from components with automatically generated standard name.
processorPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &, const word &patchType)
Construct from dictionary.
processorPolyPatch (const processorPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
processorPolyPatch (const processorPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct as given the original patch and resetting the.
processorPolyPatch (const processorPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~processorPolyPatch ()
Destructor.
virtual bool coupled () const
Return true only if this is a parallel run.
int myProcNo () const
Return processor number.
int neighbProcNo () const
Return neigbour processor number.
bool neighbour () const
Is the processor the patch neighbour ?
const vectorField & neighbFaceCentres () const
Return processor-neighbbour patch face centres.
const vectorField & neighbFaceAreas () const
Return processor-neighbbour patch face areas.
const vectorField & neighbFaceCellCentres () const
Return processor-neighbbour patch neighbour cell centres.
const labelList & neighbPoints () const
Return neighbour point labels. WIP.
const labelList & neighbEdges () const
Return neighbour edge labels. WIP.
virtual label comm () const
Return communicator used for communication.
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label start () const
Return start label of this patch in the polyMesh face list.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &, const label index)
Construct from geometric patch, resetting the index.
virtual ~patchIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & physicalType () const
Return the optional physical type of the patch.
word & physicalType ()
Return the optional physical type of the patch for modification.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh for modification.
const wordList & inGroups () const
Return the optional groups patch belongs to.
wordList & inGroups ()
Return the optional groups patch belongs to for modification.
bool inGroup (const word &) const
Test if in group.
void write (Ostream &) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Static Public Member Functions
static word newName (const word &cyclicPolyPatchName, const label myProcNo, const label neighbProcNo)
Return the name of a processorCyclicPolyPatch.
static labelList patchIDs (const word &cyclicPolyPatchName, const polyBoundaryMesh &bm)
Return the indices of a processorCyclicPolyPatchs.
Static Public Member Functions inherited from processorPolyPatch
static word newName (const label myProcNo, const label neighbProcNo)
Return the name of a processorPolyPatch.
static label matchFace (const face &localFace, const pointField &localPts, const face &masterFace, const pointField &masterPts, const bool sameOrientation, const scalar absTolSqr, scalar &matchDistSqr)
Returns rotation.
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Protected Member Functions
void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
Calculate the patch geometry with externally.
void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Member Functions inherited from processorPolyPatch
processorPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const int myProcNo, const int neighbProcNo, const transformType transform=UNKNOWN, const word &patchType=typeName)
Construct from components with specified name.
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Attributes inherited from coupledPolyPatch
static const NamedEnum< transformType, 5 > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Detailed Description
Neighbour processor patch.
Note: morph patch face ordering is geometric.
Source files
processorCyclicPolyPatch.H
processorCyclicPolyPatch.C
Definition at line 50 of file processorCyclicPolyPatch.H.
Constructor & Destructor Documentation
processorCyclicPolyPatch() [1/6]
processorCyclicPolyPatch (const label size, const label start, const label index, const polyBoundaryMesh & bm, const int myProcNo, const int neighbProcNo, const word & referPatchName, const transformType transform = UNKNOWN, const word & patchType = typeName)
Construct from components.
Definition at line 43 of file processorCyclicPolyPatch.C.
Referenced by processorCyclicPolyPatch::calcGeometry(), processorCyclicPolyPatch::clone(), and processorCyclicPolyPatch::processorCyclicPolyPatch().
processorCyclicPolyPatch() [2/6]
processorCyclicPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 74 of file processorCyclicPolyPatch.C.
References processorCyclicPolyPatch::processorCyclicPolyPatch().
processorCyclicPolyPatch() [3/6]
processorCyclicPolyPatch (const processorCyclicPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 90 of file processorCyclicPolyPatch.C.
References processorCyclicPolyPatch::processorCyclicPolyPatch().
processorCyclicPolyPatch() [4/6]
processorCyclicPolyPatch (const processorCyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct as given the original patch and resetting the.
face list and boundary mesh information
Definition at line 103 of file processorCyclicPolyPatch.C.
References processorCyclicPolyPatch::processorCyclicPolyPatch().
processorCyclicPolyPatch() [5/6]
processorCyclicPolyPatch (const processorCyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & referPatchName)
Construct as given the original patch and resetting the.
face list, boundary mesh information and referPatch
Definition at line 119 of file processorCyclicPolyPatch.C.
References processorCyclicPolyPatch::processorCyclicPolyPatch().
processorCyclicPolyPatch() [6/6]
processorCyclicPolyPatch (const processorCyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 136 of file processorCyclicPolyPatch.C.
~processorCyclicPolyPatch()
~processorCyclicPolyPatch () virtual
Definition at line 153 of file processorCyclicPolyPatch.C.
References processorCyclicPolyPatch::newName().
Referenced by processorCyclicPolyPatch::clone().
Member Function Documentation
initGeometry()
void initGeometry (PstreamBuffers & pBufs) protected virtual
Initialise the calculation of the patch geometry.
Reimplemented from processorPolyPatch.
Definition at line 226 of file processorCyclicPolyPatch.C.
References processorPolyPatch::initGeometry().
calcGeometry() [1/2]
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Calculate the patch geometry.
Reimplemented from processorPolyPatch.
Definition at line 233 of file processorCyclicPolyPatch.C.
References processorPolyPatch::calcGeometry(), coupledPolyPatch::calcGeometry(), processorCyclicPolyPatch::initMovePoints(), cyclicPolyPatch::neighbPatch(), and UPstream::parRun().
calcGeometry() [2/2]
virtual void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) inline protected virtual
Calculate the patch geometry with externally.
provided geometry
Reimplemented from processorPolyPatch.
Definition at line 79 of file processorCyclicPolyPatch.H.
References dict, patchIdentifier::index(), processorCyclicPolyPatch::initMovePoints(), processorCyclicPolyPatch::initUpdateMesh(), processorCyclicPolyPatch::movePoints(), processorPolyPatch::myProcNo(), patchIdentifier::name(), processorPolyPatch::neighbProcNo(), NotImplemented, processorCyclicPolyPatch::processorCyclicPolyPatch(), processorCyclicPolyPatch::referPatchName(), polyPatch::start(), processorCyclicPolyPatch::transform(), processorCyclicPolyPatch::TypeName(), coupledPolyPatch::UNKNOWN, and processorCyclicPolyPatch::updateMesh().
initMovePoints()
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Initialise the patches for moving points.
Reimplemented from processorPolyPatch.
Definition at line 280 of file processorCyclicPolyPatch.C.
References processorCyclicPolyPatch::movePoints().
Referenced by processorCyclicPolyPatch::calcGeometry().
movePoints()
void movePoints (PstreamBuffers & pBufs, const pointField &) protected virtual
Correct patches after moving points.
Reimplemented from processorPolyPatch.
Definition at line 291 of file processorCyclicPolyPatch.C.
Referenced by processorCyclicPolyPatch::calcGeometry(), and processorCyclicPolyPatch::initMovePoints().
initUpdateMesh()
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Reimplemented from processorPolyPatch.
Definition at line 300 of file processorCyclicPolyPatch.C.
References processorPolyPatch::initUpdateMesh().
Referenced by processorCyclicPolyPatch::calcGeometry().
updateMesh()
void updateMesh (PstreamBuffers & pBufs) protected virtual
Update of the patch topology.
Reimplemented from processorPolyPatch.
Definition at line 306 of file processorCyclicPolyPatch.C.
References processorCyclicPolyPatch::initOrder(), and processorPolyPatch::updateMesh().
Referenced by processorCyclicPolyPatch::calcGeometry().
TypeName()
TypeName ("processorCyclic")
Runtime type information.
Referenced by processorCyclicPolyPatch::calcGeometry().
clone() [1/4]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from processorPolyPatch.
Definition at line 179 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::processorCyclicPolyPatch().
Referenced by processorCyclicPolyPatch::clone().
clone() [2/4]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from processorPolyPatch.
Definition at line 187 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::clone(), and processorCyclicPolyPatch::processorCyclicPolyPatch().
clone() [3/4]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & referPatchName) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Definition at line 210 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::clone(), and processorCyclicPolyPatch::processorCyclicPolyPatch().
clone() [4/4]
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from processorPolyPatch.
Definition at line 235 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::processorCyclicPolyPatch(), and processorCyclicPolyPatch::~processorCyclicPolyPatch().
referPatchName()
const word& referPatchName () const inline
Return name of originating cyclicPolyPatch patch.
Definition at line 263 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::newName(), and processorCyclicPolyPatch::patchIDs().
Referenced by processorCyclicPolyPatch::calcGeometry().
newName()
Foam::word newName (const word & cyclicPolyPatchName, const label myProcNo, const label neighbProcNo) static
Return the name of a processorCyclicPolyPatch.
constructed from cyclicPolyPatch name and the processor IDs
Definition at line 160 of file processorCyclicPolyPatch.C.
References processorPolyPatch::newName(), and processorCyclicPolyPatch::patchIDs().
Referenced by processorCyclicPolyPatch::referPatchName(), and processorCyclicPolyPatch::~processorCyclicPolyPatch().
patchIDs()
Foam::labelList patchIDs (const word & cyclicPolyPatchName, const polyBoundaryMesh & bm) static
Return the indices of a processorCyclicPolyPatchs.
constructed from the given cyclicPolyPatch
Definition at line 174 of file processorCyclicPolyPatch.C.
References polyBoundaryMesh::findIndices().
Referenced by patchMeanVelocityForce::magUbarAve(), processorCyclicPolyPatch::newName(), and processorCyclicPolyPatch::referPatchName().
referPatchID()
label referPatchID () const inline
Referring patchID.
Definition at line 286 of file processorCyclicPolyPatch.H.
References polyPatch::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::findPatchID(), and polyBoundaryMesh::names().
Referenced by processorCyclicPolyPatch::referPatch().
referPatch()
const coupledPolyPatch& referPatch () const inline
Definition at line 306 of file processorCyclicPolyPatch.H.
References polyPatch::boundaryMesh(), processorCyclicPolyPatch::referPatchID(), and processorCyclicPolyPatch::tag().
Referenced by processorCyclicPolyPatch::collocated(), processorCyclicPolyPatch::forwardT(), processorCyclicPolyPatch::owner(), processorCyclicPolyPatch::parallel(), processorCyclicPolyPatch::reverseT(), processorCyclicPolyPatch::separated(), processorCyclicPolyPatch::separation(), processorCyclicPolyPatch::transform(), and processorCyclicPolyPatch::transformPosition().
tag()
int tag () const virtual
Return message tag to use for communication.
Reimplemented from processorPolyPatch.
Definition at line 186 of file processorCyclicPolyPatch.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UPstream::msgType(), patchIdentifier::name(), Foam::name(), cyclicPolyPatch::neighbPatch(), Foam::nl, and Foam::Pout.
Referenced by processorCyclicPolyPatch::referPatch(), processorCyclicFvPatch::tag(), and processorCyclicPointPatch::tag().
owner()
virtual bool owner () const inline virtual
Does this side own the patch ?
Reimplemented from processorPolyPatch.
Definition at line 316 of file processorCyclicPolyPatch.H.
References coupledPolyPatch::owner(), and processorCyclicPolyPatch::referPatch().
transform() [1/2]
virtual transformType transform () const inline virtual
Type of transform.
Reimplemented from coupledPolyPatch.
Definition at line 322 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::referPatch(), and coupledPolyPatch::transform().
Referenced by processorCyclicPolyPatch::calcGeometry().
transform() [2/2]
virtual transformType& transform () inline virtual
Type of transform.
This is currently only for use when collapsing generated meshes that can have zero area faces.
Reimplemented from coupledPolyPatch.
Definition at line 330 of file processorCyclicPolyPatch.H.
transformPosition() [1/2]
virtual void transformPosition (pointField & l) const inline virtual
Transform a patch-based position from other side to this side.
Reimplemented from processorPolyPatch.
Definition at line 336 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::referPatch(), and coupledPolyPatch::transformPosition().
transformPosition() [2/2]
virtual void transformPosition (point & l, const label facei) const inline virtual
Transform a patch-based position from other side to this side.
Reimplemented from processorPolyPatch.
Definition at line 342 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::referPatch(), and coupledPolyPatch::transformPosition().
separated()
virtual bool separated () const inline virtual
Are the planes separated.
Reimplemented from coupledPolyPatch.
Definition at line 348 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::referPatch(), and coupledPolyPatch::separated().
separation()
virtual const vectorField& separation () const inline virtual
If the planes are separated the separation vector.
Reimplemented from coupledPolyPatch.
Definition at line 354 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::referPatch(), and coupledPolyPatch::separation().
parallel()
virtual bool parallel () const inline virtual
Are the cyclic planes parallel.
Reimplemented from coupledPolyPatch.
Definition at line 360 of file processorCyclicPolyPatch.H.
References coupledPolyPatch::parallel(), and processorCyclicPolyPatch::referPatch().
Referenced by processorCyclicFvPatch::parallel().
forwardT()
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Reimplemented from coupledPolyPatch.
Definition at line 366 of file processorCyclicPolyPatch.H.
References coupledPolyPatch::forwardT(), and processorCyclicPolyPatch::referPatch().
Referenced by processorCyclicFvPatch::forwardT(), and processorCyclicPointPatchField< Type >::swapAddSeparated().
reverseT()
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Reimplemented from coupledPolyPatch.
Definition at line 372 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::referPatch(), and coupledPolyPatch::reverseT().
Referenced by processorCyclicFvPatch::reverseT().
collocated()
virtual const boolList& collocated () const inline virtual
Are faces collocated. Either size 0,1 or length of patch.
Reimplemented from coupledPolyPatch.
Definition at line 378 of file processorCyclicPolyPatch.H.
References coupledPolyPatch::collocated(), Foam::faceMap(), processorCyclicPolyPatch::initOrder(), processorCyclicPolyPatch::order(), processorCyclicPolyPatch::referPatch(), and processorCyclicPolyPatch::write().
initOrder()
void initOrder (PstreamBuffers & pBufs, const primitivePatch & pp) const virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Reimplemented from processorPolyPatch.
Definition at line 314 of file processorCyclicPolyPatch.C.
References processorPolyPatch::initOrder(), and processorCyclicPolyPatch::order().
Referenced by processorCyclicPolyPatch::collocated(), and processorCyclicPolyPatch::updateMesh().
order()
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Reimplemented from processorPolyPatch.
Definition at line 325 of file processorCyclicPolyPatch.C.
References processorPolyPatch::order().
Referenced by processorCyclicPolyPatch::collocated(), and processorCyclicPolyPatch::initOrder().
write()
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from processorPolyPatch.
Definition at line 337 of file processorCyclicPolyPatch.C.
References token::END_STATEMENT, Foam::nl, processorPolyPatch::write(), and Ostream::writeKeyword().
Referenced by processorCyclicPolyPatch::collocated().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/processorCyclic/processorCyclicPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/processorCyclic/processorCyclicPolyPatch.C