OpenFOAM: primitiveMeshTools Class Reference
primitiveMeshTools Class Reference
Static Public Member Functions
static tmp< scalarField > faceOrthogonality (const primitiveMesh &mesh, const vectorField &fAreas, const vectorField &cellCtrs)
Generate non-orthogonality field (internal faces only)
static void facePyramidVolume (const primitiveMesh &mesh, const pointField &points, const vectorField &cellCtrs, scalarField &ownPyrVol, scalarField &neiPyrVol)
Generate face pyramid volume fields.
static tmp< scalarField > faceSkewness (const primitiveMesh &mesh, const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs)
Generate skewness field.
static void cellClosedness (const primitiveMesh &mesh, const Vector< label > &meshD, const vectorField &areas, const scalarField &vols, scalarField &openness, scalarField &aratio)
Generate cell openness and cell ascpect ratio field.
static tmp< scalarField > faceConcavity (const scalar maxSin, const primitiveMesh &mesh, const pointField &p, const vectorField &faceAreas)
Generate face concavity field. Returns per face the (sin of the)
static tmp< scalarField > faceFlatness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &faceAreas)
Generate face flatness field. Compares the individual triangles'.
static tmp< scalarField > edgeAlignment (const primitiveMesh &mesh, const Vector< label > &directions, const pointField &p)
Generate edge alignment field. Is per face the minimum aligned edge.
static tmp< scalarField > cellDeterminant (const primitiveMesh &mesh, const Vector< label > &directions, const vectorField &faceAreas, const PackedBoolList &internalOrCoupledFace)
Generate cell determinant field.
static scalar faceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc, const point &neiCc)
Skewness of single face.
static scalar boundaryFaceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc)
Skewness of single boundary face.
static scalar faceOrthogonality (const point &ownCc, const point &neiCc, const vector &s)
Orthogonality of single face.
Detailed Description
Definition at line 49 of file primitiveMeshTools.H.
Member Function Documentation
faceOrthogonality() [1/2]
Foam::tmp< Foam::scalarField > faceOrthogonality (const primitiveMesh & mesh, const vectorField & fAreas, const vectorField & cellCtrs) static
Generate non-orthogonality field (internal faces only)
Definition at line 123 of file primitiveMeshTools.C.
References primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), primitiveMeshTools::faceSkewness(), forAll, primitiveMesh::nInternalFaces(), tmp< T >::ref(), and scalarField().
Referenced by primitiveMeshTools::boundaryFaceSkewness(), and primitiveMeshTools::faceOrthogonality().
facePyramidVolume()
void facePyramidVolume (const primitiveMesh & mesh, const pointField & points, const vectorField & cellCtrs, scalarField & ownPyrVol, scalarField & neiPyrVol) static
Generate face pyramid volume fields.
Definition at line 202 of file primitiveMeshTools.C.
References primitiveMeshTools::cellClosedness(), f(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), primitiveMesh::faces(), forAll, primitiveMesh::isInternalFace(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), and List< T >::setSize().
Referenced by primitiveMeshTools::faceSkewness().
faceSkewness() [1/2]
Foam::tmp< Foam::scalarField > faceSkewness (const primitiveMesh & mesh, const pointField & points, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs) static
Generate skewness field.
Definition at line 151 of file primitiveMeshTools.C.
References primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), primitiveMeshTools::facePyramidVolume(), forAll, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), tmp< T >::ref(), scalarField(), and Foam::skew().
Referenced by polyMeshGeometry::checkFaceSkewness(), and primitiveMeshTools::faceOrthogonality().
cellClosedness()
void cellClosedness (const primitiveMesh & mesh, const Vector< label > & meshD, const vectorField & areas, const scalarField & vols, scalarField & openness, scalarField & aratio) static
Generate cell openness and cell ascpect ratio field.
Definition at line 241 of file primitiveMeshTools.C.
References Foam::cmptMag(), Foam::cmptSum(), primitiveMeshTools::faceConcavity(), primitiveMesh::faceNeighbour(), primitiveMesh::faceOwner(), forAll, Foam::mag(), Foam::max(), Foam::min(), primitiveMesh::nCells(), Foam::pow(), List< T >::setSize(), and Foam::Zero.
Referenced by primitiveMeshTools::facePyramidVolume().
faceConcavity()
Foam::tmp< Foam::scalarField > faceConcavity (const scalar maxSin, const primitiveMesh & mesh, const pointField & p, const vectorField & faceAreas) static
Generate face concavity field. Returns per face the (sin of the)
most concave angle between two consecutive edges
Definition at line 335 of file primitiveMeshTools.C.
References f(), primitiveMeshTools::faceFlatness(), primitiveMesh::faces(), UList< T >::fcIndex(), UList< T >::first(), forAll, UList< T >::last(), Foam::mag(), Foam::max(), primitiveMesh::nFaces(), tmp< T >::ref(), and scalarField().
Referenced by primitiveMeshTools::cellClosedness().
faceFlatness()
Foam::tmp< Foam::scalarField > faceFlatness (const primitiveMesh & mesh, const pointField & p, const vectorField & fCtrs, const vectorField & faceAreas) static
Generate face flatness field. Compares the individual triangles'.
normals against the face average normal. Between 0 (fully warped) and 1 (fully flat)
Definition at line 405 of file primitiveMeshTools.C.
References primitiveMeshTools::cellDeterminant(), f(), primitiveMesh::faces(), forAll, Foam::mag(), n, primitiveMesh::nFaces(), scalarField(), and List< T >::size().
Referenced by primitiveMeshTools::faceConcavity().
edgeAlignment()
static tmp<scalarField> edgeAlignment (const primitiveMesh & mesh, const Vector< label > & directions, const pointField & p) static
Generate edge alignment field. Is per face the minimum aligned edge.
(does not use edge addressing)
cellDeterminant()
Foam::tmp< Foam::scalarField > cellDeterminant (const primitiveMesh & mesh, const Vector< label > & directions, const vectorField & faceAreas, const PackedBoolList & internalOrCoupledFace) static
Generate cell determinant field.
Definition at line 454 of file primitiveMeshTools.C.
References Foam::constant::universal::c, primitiveMesh::cells(), Foam::det(), forAll, Foam::mag(), primitiveMesh::nCells(), tmp< T >::ref(), scalarField(), Foam::sqr(), SymmTensor< Cmpt >::xx(), SymmTensor< Cmpt >::yy(), Foam::Zero, and SymmTensor< Cmpt >::zz().
Referenced by primitiveMeshTools::faceFlatness().
faceSkewness() [2/2]
Foam::scalar faceSkewness (const primitiveMesh & mesh, const pointField & p, const vectorField & fCtrs, const vectorField & fAreas, const label facei, const point & ownCc, const point & neiCc) static
Skewness of single face.
Definition at line 33 of file primitiveMeshTools.C.
References primitiveMeshTools::boundaryFaceSkewness(), f(), primitiveMesh::faces(), forAll, Foam::mag(), Foam::max(), and Foam::constant::mathematical::pi().
boundaryFaceSkewness()
Foam::scalar boundaryFaceSkewness (const primitiveMesh & mesh, const pointField & p, const vectorField & fCtrs, const vectorField & fAreas, const label facei, const point & ownCc) static
Skewness of single boundary face.
Definition at line 69 of file primitiveMeshTools.C.
References f(), primitiveMeshTools::faceOrthogonality(), primitiveMesh::faces(), forAll, Foam::mag(), Foam::max(), and Foam::constant::mathematical::pi().
Referenced by polyMeshGeometry::checkFaceSkewness(), and primitiveMeshTools::faceSkewness().
faceOrthogonality() [2/2]
Foam::scalar faceOrthogonality (const point & ownCc, const point & neiCc, const vector & s) static
Orthogonality of single face.
Definition at line 108 of file primitiveMeshTools.C.
References primitiveMeshTools::faceOrthogonality(), and Foam::mag().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshTools.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshTools.C