OpenFOAM: syncTools Class Reference
syncTools Class Reference
Various tools to aid synchronizing lists across coupled patches. WIP.
Static Public Member Functions
template<class T , class CombineOp , class TransformOp >
static void syncPointMap (const polyMesh &, Map< T > &pointValues, const CombineOp &cop, const TransformOp &top)
Synchronize values on selected points.
template<class T , class CombineOp , class TransformOp >
static void syncEdgeMap (const polyMesh &, EdgeMap< T > &edgeValues, const CombineOp &cop, const TransformOp &top)
Synchronize values on selected edges.
template<class T , class CombineOp , class TransformOp >
static void syncPointList (const polyMesh &, List< T > &, const CombineOp &cop, const T &nullValue, const TransformOp &top)
Synchronize values on all mesh points.
template<class T , class CombineOp , class TransformOp >
static void syncPointList (const polyMesh &, const labelList &meshPoints, List< T > &, const CombineOp &cop, const T &nullValue, const TransformOp &top)
Synchronize values on selected mesh points.
template<class T , class CombineOp , class TransformOp >
static void syncEdgeList (const polyMesh &, List< T > &, const CombineOp &cop, const T &nullValue, const TransformOp &top)
Synchronize values on all mesh edges.
template<class T , class CombineOp , class TransformOp >
static void syncEdgeList (const polyMesh &, const labelList &meshEdges, List< T > &, const CombineOp &cop, const T &nullValue, const TransformOp &top)
Synchronize values on selected mesh edges.
template<class T , class CombineOp , class TransformOp >
static void syncBoundaryFaceList (const polyMesh &, UList< T > &, const CombineOp &cop, const TransformOp &top, const bool parRun=Pstream::parRun())
Synchronize values on boundary faces only.
template<class T , class CombineOp >
static void syncPointList (const polyMesh &mesh, List< T > &l, const CombineOp &cop, const T &nullValue)
Synchronize values on all mesh points.
template<class CombineOp >
static void syncPointPositions (const polyMesh &mesh, List< point > &l, const CombineOp &cop, const point &nullValue)
Synchronize locations on all mesh points.
template<class T , class CombineOp >
static void syncPointList (const polyMesh &mesh, const labelList &meshPoints, List< T > &l, const CombineOp &cop, const T &nullValue)
Synchronize values on selected mesh points.
template<class CombineOp >
static void syncPointPositions (const polyMesh &mesh, const labelList &meshPoints, List< point > &l, const CombineOp &cop, const point &nullValue)
Synchronize locations on selected mesh points.
template<class T , class CombineOp >
static void syncEdgeList (const polyMesh &mesh, List< T > &l, const CombineOp &cop, const T &nullValue)
Synchronize values on all mesh edges.
template<class CombineOp >
static void syncEdgePositions (const polyMesh &mesh, List< point > &l, const CombineOp &cop, const point &nullValue)
Synchronize locations on all mesh edges.
template<class T , class CombineOp >
static void syncEdgeList (const polyMesh &mesh, const labelList &meshEdges, List< T > &l, const CombineOp &cop, const T &nullValue)
Synchronize values on selected mesh edges.
template<class CombineOp >
static void syncEdgePositions (const polyMesh &mesh, const labelList &meshEdges, List< point > &l, const CombineOp &cop, const point &nullValue)
Synchronize locations on selected mesh edges.
template<class T , class CombineOp >
static void syncBoundaryFaceList (const polyMesh &mesh, UList< T > &l, const CombineOp &cop)
Synchronize values on boundary faces only.
template<class CombineOp >
static void syncBoundaryFacePositions (const polyMesh &mesh, UList< point > &l, const CombineOp &cop)
Synchronize locations on boundary faces only.
template<class T , class CombineOp >
static void syncFaceList (const polyMesh &mesh, UList< T > &l, const CombineOp &cop)
Synchronize values on all mesh faces.
template<class CombineOp >
static void syncFacePositions (const polyMesh &mesh, UList< point > &l, const CombineOp &cop)
Synchronize locations on all mesh faces.
template<class T >
static void swapBoundaryFaceList (const polyMesh &mesh, UList< T > &l)
Swap coupled boundary face values.
static void swapBoundaryFacePositions (const polyMesh &mesh, UList< point > &l)
Swap coupled positions.
template<class T >
static void swapFaceList (const polyMesh &mesh, UList< T > &l)
Swap coupled face values.
template<class T >
static void swapBoundaryCellList (const polyMesh &mesh, const UList< T > &cellData, List< T > &neighbourCellData)
Swap to obtain neighbour cell values for all boundary faces.
static void swapBoundaryCellPositions (const polyMesh &mesh, const UList< point > &cellData, List< point > &neighbourCellData)
Swap to obtain neighbour cell positions for all boundary faces.
template<class T , class CombineOp >
static void syncPointMap (const polyMesh &mesh, Map< T > &l, const CombineOp &cop)
Synchronize values on selected points.
template<class CombineOp >
static void syncPointPositions (const polyMesh &mesh, Map< point > &l, const CombineOp &cop)
Synchronize locations on selected points.
template<class T , class CombineOp >
static void syncEdgeMap (const polyMesh &mesh, EdgeMap< T > &l, const CombineOp &cop)
Synchronize values on selected edges. Edges are represented.
template<class CombineOp >
static void syncEdgePositions (const polyMesh &mesh, EdgeMap< point > &l, const CombineOp &cop)
Synchronize locations on selected edges.
template<unsigned nBits, class CombineOp >
static void syncFaceList (const polyMesh &mesh, PackedList< nBits > &faceValues, const CombineOp &cop, const bool parRun=Pstream::parRun())
template<unsigned nBits>
static void swapFaceList (const polyMesh &mesh, PackedList< nBits > &faceValues)
template<unsigned nBits, class CombineOp >
static void syncPointList (const polyMesh &mesh, PackedList< nBits > &pointValues, const CombineOp &cop, const unsigned int nullValue)
template<unsigned nBits, class CombineOp >
static void syncEdgeList (const polyMesh &mesh, PackedList< nBits > &edgeValues, const CombineOp &cop, const unsigned int nullValue)
static PackedBoolList getMasterPoints (const polyMesh &)
Get per point whether it is uncoupled or a master of a.
static PackedBoolList getMasterEdges (const polyMesh &)
Get per edge whether it is uncoupled or a master of a.
static PackedBoolList getMasterFaces (const polyMesh &)
Get per face whether it is uncoupled or a master of a.
static PackedBoolList getInternalOrMasterFaces (const polyMesh &)
Get per face whether it is internal or a master of a.
static PackedBoolList getInternalOrCoupledFaces (const polyMesh &)
Get per face whether it is internal or coupled.
Detailed Description
Various tools to aid synchronizing lists across coupled patches. WIP.
Require
combineOperator (e.g. sumEqOp - not sumOp!) that is defined for the type and combineReduce(UList<T>, combineOperator) should be defined.
null value which gets overridden by any valid value.
transform function
Source files
syncTools.H
syncTools.C
syncToolsTemplates.C
Definition at line 62 of file syncTools.H.
Member Function Documentation
syncPointMap() [1/2]
void syncPointMap (const polyMesh & mesh, Map< T > & pointValues, const CombineOp & cop, const TransformOp & top) static
Synchronize values on selected points.
Definition at line 84 of file syncToolsTemplates.C.
References polyMesh::boundaryMesh(), cyclicPolyPatch::coupledPoints(), Foam::e, HashTableCore::end(), HashTable< T, label, Hash< label > >::find(), PstreamBuffers::finishedSends(), UPstream::firstSlave(), forAll, forAllConstIter(), polyMesh::globalData(), UPstream::lastSlave(), UPstream::master(), UPstream::masterNo(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), cyclicPolyPatch::neighbPatch(), processorPolyPatch::neighbPoints(), processorPolyPatch::neighbProcNo(), globalMeshData::nGlobalPoints(), UPstream::nonBlocking, nPoints, cyclicPolyPatch::owner(), UPstream::parRun(), patches, patchi, HashTable< T, label, Hash< label > >::resize(), UPstream::scheduled, HashTable< T, label, Hash< label > >::set(), globalMeshData::sharedPointAddr(), globalMeshData::sharedPointLabels(), List< T >::size(), and syncTools::syncEdgeMap().
Referenced by syncTools::swapFaceList(), syncTools::syncPointMap(), and syncTools::syncPointPositions().
syncEdgeMap() [1/2]
void syncEdgeMap (const polyMesh & mesh, EdgeMap< T > & edgeValues, const CombineOp & cop, const TransformOp & top) static
Synchronize values on selected edges.
Definition at line 389 of file syncToolsTemplates.C.
References polyMesh::boundaryMesh(), cyclicPolyPatch::coupledEdges(), Foam::e, PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), HashTableCore::end(), f(), polyMesh::faces(), UList< T >::fcIndex(), HashTable< T, edge, Hash< edge > >::find(), HashTable< T, Key, Hash >::find(), PstreamBuffers::finishedSends(), UPstream::firstSlave(), forAll, forAllConstIter(), polyMesh::globalData(), UPstream::lastSlave(), UPstream::master(), UPstream::masterNo(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), cyclicPolyPatch::neighbPatch(), processorPolyPatch::neighbPoints(), processorPolyPatch::neighbProcNo(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), UPstream::nonBlocking, cyclicPolyPatch::owner(), UPstream::parRun(), patches, patchi, UPstream::scheduled, globalMeshData::sharedPointAddr(), globalMeshData::sharedPointLabels(), List< T >::size(), and syncTools::syncPointList().
Referenced by patchPatchDist::correct(), syncTools::syncEdgeMap(), syncTools::syncEdgePositions(), syncTools::syncPointMap(), and syncTools::syncPointPositions().
syncPointList() [1/5]
void syncPointList (const polyMesh & mesh, List< T > & pointValues, const CombineOp & cop, const T & nullValue, const TransformOp & top) static
Synchronize values on all mesh points.
Definition at line 982 of file syncToolsTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, polyMesh::globalData(), primitiveMesh::nPoints(), List< T >::size(), and globalMeshData::syncPointData().
Referenced by singleProcessorFaceSetsConstraint::add(), singleProcessorFaceSetsConstraint::apply(), motionSmootherAlgo::avg(), snappySnapDriver::avgCellCentres(), snappySnapDriver::calcNearestSurface(), snappySnapDriver::calcSnapDistance(), edgeCollapser::checkMeshQuality(), pointZone::checkParallelSync(), hexRef8::checkRefinementLevels(), edgeCollapser::consistentCollapse(), hexRef8::consistentSlowRefinement(), polyMeshFilter::copyMesh(), motionSmootherAlgo::correctBoundaryConditions(), removePoints::countPointUsage(), snappySnapDriver::doSnap(), meshRefinement::getMasterPoints(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), minEqOpFace::operator()(), listPlusEqOp< T >::operator()(), motionSmootherAlgo::scaleMesh(), motionSmootherAlgo::setDisplacementPatchFields(), combineFaces::setRefinement(), removeFaces::setRefinement(), addPatchCellLayer::setRefinement(), motionSmootherAlgo::smooth(), solidBodyMotionFvMesh::solidBodyMotionFvMesh(), meshRefinement::splitMesh(), syncTools::swapFaceList(), pointSet::sync(), syncTools::syncEdgeMap(), syncTools::syncEdgePositions(), syncTools::syncPointList(), syncTools::syncPointPositions(), meshRefinement::testSyncPointList(), and meshRefinement::weightedSum().
syncPointList() [2/5]
void syncPointList (const polyMesh & mesh, const labelList & meshPoints, List< T > & pointValues, const CombineOp & cop, const T & nullValue, const TransformOp & top) static
Synchronize values on selected mesh points.
Definition at line 1025 of file syncToolsTemplates.C.
References Foam::abort(), globalMeshData::coupledPatch(), HashTableCore::end(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), forAll, polyMesh::globalData(), globalMeshData::globalPointSlaves(), globalMeshData::globalPointSlavesMap(), globalMeshData::globalPointTransformedSlaves(), globalMeshData::globalTransforms(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPointMap(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), List< T >::size(), globalMeshData::syncData(), and syncTools::syncEdgeList().
syncEdgeList() [1/5]
void syncEdgeList (const polyMesh & mesh, List< T > & edgeValues, const CombineOp & cop, const T & nullValue, const TransformOp & top) static
Synchronize values on all mesh edges.
Definition at line 1139 of file syncToolsTemplates.C.
References Foam::abort(), globalMeshData::coupledPatchMeshEdges(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), globalMeshData::globalEdgeSlaves(), globalMeshData::globalEdgeSlavesMap(), globalMeshData::globalEdgeTransformedSlaves(), globalMeshData::globalTransforms(), primitiveMesh::nEdges(), List< T >::size(), and globalMeshData::syncData().
Referenced by edgeCollapser::consistentCollapse(), polyMeshFilter::copyMesh(), meshRefinement::createZoneBaffles(), meshRefinement::getMasterEdges(), addPatchCellLayer::globalEdgeFaces(), meshRefinement::mergeBaffles(), listPlusEqOp< T >::operator()(), ifEqEqOp< value >::operator()(), removeFaces::setRefinement(), addPatchCellLayer::setRefinement(), hexRef8::setRefinement(), syncTools::syncEdgeList(), syncTools::syncEdgePositions(), syncTools::syncPointList(), and syncTools::syncPointPositions().
syncEdgeList() [2/5]
void syncEdgeList (const polyMesh & mesh, const labelList & meshEdges, List< T > & edgeValues, const CombineOp & cop, const T & nullValue, const TransformOp & top) static
Synchronize values on selected mesh edges.
Definition at line 1227 of file syncToolsTemplates.C.
References Foam::abort(), globalMeshData::coupledPatch(), globalMeshData::coupledPatchMeshEdgeMap(), HashTableCore::end(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), forAll, polyMesh::globalData(), globalMeshData::globalEdgeSlaves(), globalMeshData::globalEdgeSlavesMap(), globalMeshData::globalEdgeTransformedSlaves(), globalMeshData::globalTransforms(), PrimitivePatch< Face, FaceList, PointField, PointType >::nEdges(), List< T >::size(), syncTools::syncBoundaryFaceList(), and globalMeshData::syncData().
syncBoundaryFaceList() [1/2]
void syncBoundaryFaceList (const polyMesh & mesh, UList< T > & faceValues, const CombineOp & cop, const TransformOp & top, const bool parRun = Pstream::parRun()) static
Synchronize values on boundary faces only.
Definition at line 1283 of file syncToolsTemplates.C.
References Foam::abort(), polyMesh::boundaryMesh(), Foam::FatalError, FatalErrorInFunction, PstreamBuffers::finishedSends(), forAll, cyclicPolyPatch::neighbPatch(), processorPolyPatch::neighbProcNo(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), UPstream::nonBlocking, cyclicPolyPatch::owner(), patches, patchi, UList< T >::size(), polyPatch::start(), and syncTools::syncFaceList().
Referenced by preserveFaceZonesConstraint::apply(), preservePatchesConstraint::apply(), cellToFaceStencil::calcFaceStencil(), removePoints::getUnrefimentSet(), minEqOpFace::operator()(), syncTools::swapBoundaryFaceList(), syncTools::swapBoundaryFacePositions(), syncTools::swapFaceList(), syncTools::syncBoundaryFaceList(), syncTools::syncBoundaryFacePositions(), syncTools::syncEdgeList(), syncTools::syncEdgePositions(), syncTools::syncFaceList(), and syncTools::syncFacePositions().
syncPointList() [3/5]
static void syncPointList (const polyMesh & mesh, List< T > & l, const CombineOp & cop, const T & nullValue) inline static
Synchronize values on all mesh points.
Definition at line 176 of file syncTools.H.
References syncTools::syncPointList(), and syncTools::syncPointPositions().
syncPointPositions() [1/3]
static void syncPointPositions (const polyMesh & mesh, List< point > & l, const CombineOp & cop, const point & nullValue) inline static
Synchronize locations on all mesh points.
Definition at line 196 of file syncTools.H.
References syncTools::syncPointList().
Referenced by syncTools::syncPointList(), and syncTools::syncPointMap().
syncPointList() [4/5]
static void syncPointList (const polyMesh & mesh, const labelList & meshPoints, List< T > & l, const CombineOp & cop, const T & nullValue) inline static
Synchronize values on selected mesh points.
Definition at line 216 of file syncTools.H.
References syncTools::syncPointList(), and syncTools::syncPointPositions().
syncPointPositions() [2/3]
static void syncPointPositions (const polyMesh & mesh, const labelList & meshPoints, List< point > & l, const CombineOp & cop, const point & nullValue) inline static
Synchronize locations on selected mesh points.
Definition at line 238 of file syncTools.H.
References syncTools::syncEdgeList(), and syncTools::syncPointList().
syncEdgeList() [3/5]
static void syncEdgeList (const polyMesh & mesh, List< T > & l, const CombineOp & cop, const T & nullValue) inline static
Synchronize values on all mesh edges.
Definition at line 263 of file syncTools.H.
References syncTools::syncEdgeList(), and syncTools::syncEdgePositions().
syncEdgePositions() [1/3]
static void syncEdgePositions (const polyMesh & mesh, List< point > & l, const CombineOp & cop, const point & nullValue) inline static
Synchronize locations on all mesh edges.
Definition at line 283 of file syncTools.H.
References syncTools::syncEdgeList().
Referenced by hexRef8::setRefinement(), syncTools::syncEdgeList(), and syncTools::syncEdgeMap().
syncEdgeList() [4/5]
static void syncEdgeList (const polyMesh & mesh, const labelList & meshEdges, List< T > & l, const CombineOp & cop, const T & nullValue) inline static
Synchronize values on selected mesh edges.
Definition at line 303 of file syncTools.H.
References syncTools::syncEdgeList(), and syncTools::syncEdgePositions().
syncEdgePositions() [2/3]
static void syncEdgePositions (const polyMesh & mesh, const labelList & meshEdges, List< point > & l, const CombineOp & cop, const point & nullValue) inline static
Synchronize locations on selected mesh edges.
Definition at line 325 of file syncTools.H.
References syncTools::syncBoundaryFaceList(), and syncTools::syncEdgeList().
syncBoundaryFaceList() [2/2]
static void syncBoundaryFaceList (const polyMesh & mesh, UList< T > & l, const CombineOp & cop) inline static
Synchronize values on boundary faces only.
Definition at line 351 of file syncTools.H.
References syncTools::syncBoundaryFaceList(), and syncTools::syncBoundaryFacePositions().
syncBoundaryFacePositions()
static void syncBoundaryFacePositions (const polyMesh & mesh, UList< point > & l, const CombineOp & cop) inline static
Synchronize locations on boundary faces only.
Definition at line 363 of file syncTools.H.
References syncTools::syncBoundaryFaceList(), and syncTools::syncFaceList().
Referenced by meshRefinement::checkData(), hexRef8::setRefinement(), and syncTools::syncBoundaryFaceList().
syncFaceList() [1/2]
static void syncFaceList (const polyMesh & mesh, UList< T > & l, const CombineOp & cop) inline static
Synchronize values on all mesh faces.
Definition at line 381 of file syncTools.H.
References primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), syncTools::syncBoundaryFaceList(), and syncTools::syncFacePositions().
Referenced by preserveBafflesConstraint::add(), preserveFaceZonesConstraint::add(), preservePatchesConstraint::add(), singleProcessorFaceSetsConstraint::add(), refinementHistory::add(), meshRefinement::balance(), dynamicRefineFvMesh::calculateProtectedCells(), polyMeshFilter::copyMesh(), meshRefinement::createBaffles(), snappySnapDriver::doSnap(), dynamicRefineFvMesh::dynamicRefineFvMesh(), dynamicRefineFvMesh::extendMarkedCells(), removeCells::getExposedFaces(), meshRefinement::mergeBaffles(), NamedEnum< directionType, 3 >::names(), hexRef8::setRefinement(), meshRefinement::splitMesh(), syncTools::swapFaceList(), faceSet::sync(), syncTools::syncBoundaryFaceList(), syncTools::syncBoundaryFacePositions(), syncTools::syncEdgePositions(), and meshRefinement::zonify().
syncFacePositions()
static void syncFacePositions (const polyMesh & mesh, UList< point > & l, const CombineOp & cop) inline static
Synchronize locations on all mesh faces.
Definition at line 406 of file syncTools.H.
References primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), syncTools::swapBoundaryFaceList(), and syncTools::syncBoundaryFaceList().
Referenced by syncTools::syncFaceList().
swapBoundaryFaceList()
static void swapBoundaryFaceList (const polyMesh & mesh, UList< T > & l) inline static
Swap coupled boundary face values.
Definition at line 430 of file syncTools.H.
References syncTools::swapBoundaryFacePositions(), and syncTools::syncBoundaryFaceList().
Referenced by decompositionMethod::calcCellCells(), dynamicRefineFvMesh::calculateProtectedCells(), meshRefinement::checkCoupledFaceZones(), meshRefinement::checkData(), hexRef8::checkMesh(), edgeCollapser::checkMeshQuality(), faceZone::checkParallelSync(), hexRef8::checkRefinementLevels(), polyMeshGeometry::checkVolRatio(), hexRef8::consistentSlowRefinement(), hexRef8::consistentUnrefinement(), hexRef8::faceLevel(), isoSurface::generateFaceTriPoints(), meshRefinement::isNormalGap(), meshRefinement::mergeBaffles(), NamedEnum< directionType, 3 >::names(), fvMeshDistribute::printCoupleInfo(), SloanRenumber::renumber(), rotorDiskSource::setFaceArea(), hexRef8::setRefinement(), syncTools::swapBoundaryCellList(), and syncTools::syncFacePositions().
swapBoundaryFacePositions()
static void swapBoundaryFacePositions (const polyMesh & mesh, UList< point > & l) inline static
Swap coupled positions.
Definition at line 446 of file syncTools.H.
References syncTools::swapFaceList(), and syncTools::syncBoundaryFaceList().
Referenced by polyMeshGeometry::checkFaceDotProduct(), polyMeshGeometry::checkFaceTets(), polyMeshGeometry::checkFaceTwist(), polyMeshGeometry::checkFaceWeights(), NamedEnum< directionType, 3 >::names(), and syncTools::swapBoundaryFaceList().
swapFaceList() [1/2]
static void swapFaceList (const polyMesh & mesh, UList< T > & l) inline static
Swap coupled face values.
Definition at line 463 of file syncTools.H.
References primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryCellPositions(), syncTools::syncBoundaryFaceList(), and syncTools::syncPointMap().
Referenced by dynamicRefineFvMesh::dynamicRefineFvMesh(), removeFaces::setRefinement(), syncTools::swapBoundaryCellList(), syncTools::swapBoundaryFacePositions(), and syncTools::syncEdgePositions().
swapBoundaryCellList()
void swapBoundaryCellList (const polyMesh & mesh, const UList< T > & cellData, List< T > & neighbourCellData) static
Swap to obtain neighbour cell values for all boundary faces.
Definition at line 1521 of file syncToolsTemplates.C.
References Foam::abort(), polyMesh::boundaryMesh(), polyPatch::faceCells(), Foam::FatalError, FatalErrorInFunction, forAll, primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patches, patchi, List< T >::setSize(), UList< T >::size(), polyPatch::start(), syncTools::swapBoundaryFaceList(), and syncTools::swapFaceList().
Referenced by decompositionMethod::decompose(), snappyRefineDriver::snappyRefineDriver(), syncTools::swapFaceList(), syncTools::syncFaceList(), and meshRefinement::zonify().
swapBoundaryCellPositions()
void swapBoundaryCellPositions (const polyMesh & mesh, const UList< point > & cellData, List< point > & neighbourCellData) static
Swap to obtain neighbour cell positions for all boundary faces.
Definition at line 31 of file syncTools.C.
References Foam::abort(), polyMesh::boundaryMesh(), polyPatch::faceCells(), Foam::FatalError, FatalErrorInFunction, forAll, primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), patches, patchi, List< T >::setSize(), UList< T >::size(), and polyPatch::start().
Referenced by searchableSurfaceToFaceZone::applyToSet(), polyMeshGeometry::checkFaceSkewness(), and syncTools::swapFaceList().
syncPointMap() [2/2]
static void syncPointMap (const polyMesh & mesh, Map< T > & l, const CombineOp & cop) inline static
Synchronize values on selected points.
Definition at line 505 of file syncTools.H.
References syncTools::syncPointMap(), and syncTools::syncPointPositions().
syncPointPositions() [3/3]
static void syncPointPositions (const polyMesh & mesh, Map< point > & l, const CombineOp & cop) inline static
Synchronize locations on selected points.
Definition at line 517 of file syncTools.H.
References syncTools::syncEdgeMap(), and syncTools::syncPointMap().
syncEdgeMap() [2/2]
static void syncEdgeMap (const polyMesh & mesh, EdgeMap< T > & l, const CombineOp & cop) inline static
Synchronize values on selected edges. Edges are represented.
by the two vertices that make it up so global edges never get constructed.
Definition at line 531 of file syncTools.H.
References syncTools::syncEdgeMap(), and syncTools::syncEdgePositions().
syncEdgePositions() [3/3]
static void syncEdgePositions (const polyMesh & mesh, EdgeMap< point > & l, const CombineOp & cop) inline static
Synchronize locations on selected edges.
Definition at line 543 of file syncTools.H.
References syncTools::getInternalOrCoupledFaces(), syncTools::getInternalOrMasterFaces(), syncTools::getMasterEdges(), syncTools::getMasterFaces(), syncTools::getMasterPoints(), UPstream::parRun(), syncTools::swapFaceList(), syncTools::syncEdgeList(), syncTools::syncEdgeMap(), syncTools::syncFaceList(), and syncTools::syncPointList().
syncFaceList() [2/2]
void syncFaceList (const polyMesh & mesh, PackedList< nBits > & faceValues, const CombineOp & cop, const bool parRun = Pstream::parRun()) static
Definition at line 1406 of file syncToolsTemplates.C.
References Foam::abort(), polyMesh::boundaryMesh(), Foam::FatalError, FatalErrorInFunction, PstreamBuffers::finishedSends(), forAll, cyclicPolyPatch::neighbPatch(), processorPolyPatch::neighbProcNo(), primitiveMesh::nFaces(), UPstream::nonBlocking, cyclicPolyPatch::owner(), patches, patchi, PackedList< nBits >::size(), polyPatch::start(), and syncTools::swapBoundaryCellList().
swapFaceList() [2/2]
void swapFaceList (const polyMesh & mesh, PackedList< nBits > & faceValues) static
Definition at line 1557 of file syncToolsTemplates.C.
References syncTools::syncFaceList(), and syncTools::syncPointList().
syncPointList() [5/5]
void syncPointList (const polyMesh & mesh, PackedList< nBits > & pointValues, const CombineOp & cop, const unsigned int nullValue) static
Definition at line 1568 of file syncToolsTemplates.C.
References Foam::abort(), mapDistributeBase::constructSize(), globalMeshData::coupledPatch(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), globalMeshData::globalPointSlaves(), globalMeshData::globalPointSlavesMap(), globalMeshData::globalPointTransformedSlaves(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), primitiveMesh::nPoints(), PackedList< nBits >::size(), globalMeshData::syncData(), and syncTools::syncEdgeList().
syncEdgeList() [5/5]
void syncEdgeList (const polyMesh & mesh, PackedList< nBits > & edgeValues, const CombineOp & cop, const unsigned int nullValue) static
Definition at line 1611 of file syncToolsTemplates.C.
References Foam::abort(), mapDistributeBase::constructSize(), globalMeshData::coupledPatchMeshEdges(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), globalMeshData::globalEdgeSlaves(), globalMeshData::globalEdgeSlavesMap(), globalMeshData::globalEdgeTransformedSlaves(), primitiveMesh::nEdges(), PackedList< nBits >::size(), and globalMeshData::syncData().
getMasterPoints()
Foam::PackedBoolList getMasterPoints (const polyMesh & mesh) static
Get per point whether it is uncoupled or a master of a.
coupled set of points
Definition at line 65 of file syncTools.C.
References forAll, polyMesh::globalData(), and primitiveMesh::nPoints().
Referenced by meshRefinement::printMeshInfo(), syncTools::syncEdgePositions(), and medialAxisMeshMover::~medialAxisMeshMover().
getMasterEdges()
Foam::PackedBoolList getMasterEdges (const polyMesh & mesh) static
Get per edge whether it is uncoupled or a master of a.
coupled set of edges
Definition at line 109 of file syncTools.C.
References forAll, polyMesh::globalData(), and primitiveMesh::nEdges().
Referenced by syncTools::syncEdgePositions(), motionSmootherAlgo::updateMesh(), and medialAxisMeshMover::~medialAxisMeshMover().
getMasterFaces()
Foam::PackedBoolList getMasterFaces (const polyMesh & mesh) static
Get per face whether it is uncoupled or a master of a.
coupled set of faces
Definition at line 153 of file syncTools.C.
References polyMesh::boundaryMesh(), forAll, syncTools::getInternalOrMasterFaces(), primitiveMesh::nFaces(), coupledPolyPatch::owner(), patches, patchi, and polyPatch::start().
Referenced by meshRefinement::countHits(), NamedEnum< directionType, 3 >::names(), listPlusEqOp< T >::operator()(), meshRefinement::printMeshInfo(), syncTools::syncEdgePositions(), and meshRefinement::zonify().
getInternalOrMasterFaces()
Foam::PackedBoolList getInternalOrMasterFaces (const polyMesh & mesh) static
Get per face whether it is internal or a master of a.
coupled set of faces
Definition at line 181 of file syncTools.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), forAll, syncTools::getInternalOrCoupledFaces(), primitiveMesh::nFaces(), patches, patchi, and polyPatch::start().
Referenced by syncTools::getMasterFaces(), and syncTools::syncEdgePositions().
getInternalOrCoupledFaces()
Foam::PackedBoolList getInternalOrCoupledFaces (const polyMesh & mesh) static
Get per face whether it is internal or coupled.
Definition at line 217 of file syncTools.C.
References polyMesh::boundaryMesh(), polyPatch::coupled(), forAll, primitiveMesh::nFaces(), patches, patchi, and polyPatch::start().
Referenced by syncTools::getInternalOrMasterFaces(), and syncTools::syncEdgePositions().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/syncTools/syncTools.H
src/OpenFOAM/meshes/polyMesh/syncTools/syncTools.C
src/OpenFOAM/meshes/polyMesh/syncTools/syncToolsTemplates.C