OpenFOAM: zone Class Reference
zone Class Reference abstract
Base class for zones.
Public Member Functions
TypeName ("zone")
Runtime type information.
zone (const word &name, const labelUList &addr, const label index)
Construct from components.
zone (const word &name, const Xfer< labelList > &addr, const label index)
Construct from components, transferring contents.
zone (const word &name, const dictionary &, const word &labelsName, const label index)
Construct from dictionary.
zone (const zone &, const labelUList &addr, const label index)
Construct given the original zone and resetting the.
zone (const zone &, const Xfer< labelList > &addr, const label index)
Construct given the original zone, resetting the.
virtual ~zone ()
Destructor.
const word & name () const
Return name.
label localID (const label globalID) const
Map storing the local index for every global index. Used to find.
label index () const
Return the index of this zone in zone list.
virtual void clearAddressing ()
Clear addressing.
virtual bool checkDefinition (const bool report=false) const =0
Check zone definition. Return true if in error.
virtual bool checkDefinition (const label maxSize, const bool report=false) const
Check zone definition with max size given. Return true if in error.
virtual void movePoints (const pointField &)
Correct patch after moving points.
virtual void write (Ostream &) const
Write.
virtual void writeDict (Ostream &) const =0
Write dictionary.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Protected Member Functions
const Map< label > & lookupMap () const
Return a reference to the look-up map.
void calcLookupMap () const
Construct the look-up map.
zone (const zone &)
Disallow default bitwise copy construct.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Protected Attributes
word name_
Name of zone.
label index_
Index of zone.
Map< label > * lookupMapPtr_
Map of labels in zone for fast location lookup.
Friends
Ostream & operator<< (Ostream &, const zone &)
Ostream Operator.
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Detailed Description
Base class for zones.
Source files
zone.H
zone.C
Definition at line 57 of file zone.H.
Constructor & Destructor Documentation
zone() [1/6]
zone (const zone &) protected
Disallow default bitwise copy construct.
Referenced by zone::calcLookupMap(), and zone::zone().
zone() [2/6]
zone (const word & name, const labelUList & addr, const label index)
Construct from components.
Definition at line 86 of file zone.C.
References zone::zone().
zone() [3/6]
zone (const word & name, const Xfer< labelList > & addr, const label index)
Construct from components, transferring contents.
Definition at line 100 of file zone.C.
References zone::zone().
zone() [4/6]
zone (const word & name, const dictionary & dict, const word & labelsName, const label index)
Construct from dictionary.
Definition at line 114 of file zone.C.
References zone::zone().
zone() [5/6]
zone (const zone & z, const labelUList & addr, const label index)
Construct given the original zone and resetting the.
cell list and zone mesh information
Definition at line 129 of file zone.C.
References zone::zone().
zone() [6/6]
zone (const zone & z, const Xfer< labelList > & addr, const label index)
Construct given the original zone, resetting the.
cell list and zone mesh information
Definition at line 143 of file zone.C.
~zone()
~zone () virtual
Destructor.
Definition at line 158 of file zone.C.
Member Function Documentation
lookupMap()
const Foam::Map< Foam::label > & lookupMap () const protected
Return a reference to the look-up map.
Definition at line 41 of file zone.C.
calcLookupMap()
void calcLookupMap () const protected
Construct the look-up map.
Definition at line 52 of file zone.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, InfoInFunction, HashTable< T, label, Hash< label > >::insert(), Foam::nl, List< T >::size(), and zone::zone().
TypeName()
TypeName ("zone")
Runtime type information.
name()
const word& name () const inline
Return name.
Definition at line 150 of file zone.H.
References zone::localID(), and zone::name_.
Referenced by meshRefinement::checkCoupledFaceZones(), NamedEnum< directionType, 3 >::names(), fvMeshDistribute::printMeshInfo(), FacePostProcessing< CloudType >::write(), and meshRefinement::zonify().
localID()
Foam::label localID (const label globalID) const
Map storing the local index for every global index. Used to find.
the index of the item in the zone from the known global index. If the item is not in the zone, returns -1
Definition at line 166 of file zone.C.
References HashTableCore::end(), and HashTable< T, Key, Hash >::find().
Referenced by zone::name(), cellZone::whichCell(), faceZone::whichFace(), and pointZone::whichPoint().
index()
label index () const inline
Return the index of this zone in zone list.
Definition at line 161 of file zone.H.
References zone::checkDefinition(), zone::clearAddressing(), and zone::index_.
Referenced by pointZone::clone(), cellZone::clone(), and faceZone::clone().
clearAddressing()
void clearAddressing () virtual
Clear addressing.
Reimplemented in faceZone.
Definition at line 183 of file zone.C.
References Foam::deleteDemandDrivenData().
Referenced by faceZone::clearAddressing(), and zone::index().
checkDefinition() [1/2]
virtual bool checkDefinition (const bool report = false) const pure virtual
Check zone definition. Return true if in error.
Implemented in faceZone, cellZone, and pointZone.
Referenced by pointZone::checkDefinition(), cellZone::checkDefinition(), faceZone::checkDefinition(), and zone::index().
checkDefinition() [2/2]
bool checkDefinition (const label maxSize, const bool report = false) const virtual
Check zone definition with max size given. Return true if in error.
Definition at line 189 of file zone.C.
References Foam::endl(), forAll, HashSet< Key, Hash >::insert(), Foam::nl, SeriousErrorInFunction, and WarningInFunction.
movePoints()
virtual void movePoints (const pointField &) inline virtual
Correct patch after moving points.
Reimplemented in faceZone, and pointZone.
Definition at line 180 of file zone.H.
References zone::operator<<, zone::write(), and zone::writeDict().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in faceZone.
Definition at line 233 of file zone.C.
References Foam::nl.
Referenced by zone::movePoints(), and Foam::operator<<().
writeDict()
virtual void writeDict (Ostream &) const pure virtual
Write dictionary.
Implemented in faceZone, cellZone, and pointZone.
Referenced by zone::movePoints().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const zone &) friend
Ostream Operator.
Referenced by zone::movePoints().
Member Data Documentation
name_
word name_ protected
Name of zone.
Definition at line 67 of file zone.H.
Referenced by zone::name().
index_
label index_ protected
Index of zone.
Definition at line 70 of file zone.H.
Referenced by zone::index().
lookupMapPtr_
Map<label>* lookupMapPtr_ mutable protected
Map of labels in zone for fast location lookup.
Definition at line 76 of file zone.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/zones/zone/zone.H
src/OpenFOAM/meshes/polyMesh/zones/zone/zone.C