OpenFOAM: cellZone Class Reference
cellZone Class Reference
A subset of mesh cells.
Public Member Functions
TypeName ("cellZone")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, cellZone, dictionary,(const word &name, const dictionary &dict, const label index, const cellZoneMesh &zm),(name, dict, index, zm))
cellZone (const word &name, const labelUList &addr, const label index, const cellZoneMesh &)
Construct from components.
cellZone (const word &name, const Xfer< labelList > &addr, const label index, const cellZoneMesh &)
Construct from components, transferring contents.
cellZone (const word &name, const dictionary &, const label index, const cellZoneMesh &)
Construct from dictionary.
cellZone (const cellZone &, const labelUList &addr, const label index, const cellZoneMesh &)
Construct given the original zone and resetting the.
cellZone (const cellZone &, const Xfer< labelList > &addr, const label index, const cellZoneMesh &)
Construct given the original zone, resetting the.
virtual autoPtr< cellZone > clone (const cellZoneMesh &zm) const
Construct and return a clone, resetting the zone mesh.
virtual autoPtr< cellZone > clone (const labelUList &addr, const label index, const cellZoneMesh &zm) const
Construct and return a clone, resetting the cell list.
virtual ~cellZone ()
Destructor.
label whichCell (const label globalCellID) const
Helper function to re-direct to zone::localID(...)
const cellZoneMesh & zoneMesh () const
Return zoneMesh reference.
virtual bool checkDefinition (const bool report=false) const
Check zone definition. Return true if in error.
virtual bool checkParallelSync (const bool report=false) const
Check whether zone is synchronised across coupled boundaries. Return.
virtual void writeDict (Ostream &) const
Write dictionary.
void operator= (const cellZone &)
Assign to zone, clearing demand-driven data.
void operator= (const labelUList &)
Assign addressing, clearing demand-driven data.
void operator= (const Xfer< labelList > &)
Assign addressing, clearing demand-driven data.
Public Member Functions inherited from zone
TypeName ("zone")
Runtime type information.
zone (const word &name, const labelUList &addr, const label index)
Construct from components.
zone (const word &name, const Xfer< labelList > &addr, const label index)
Construct from components, transferring contents.
zone (const word &name, const dictionary &, const word &labelsName, const label index)
Construct from dictionary.
zone (const zone &, const labelUList &addr, const label index)
Construct given the original zone and resetting the.
zone (const zone &, const Xfer< labelList > &addr, const label index)
Construct given the original zone, resetting the.
virtual ~zone ()
Destructor.
const word & name () const
Return name.
label localID (const label globalID) const
Map storing the local index for every global index. Used to find.
label index () const
Return the index of this zone in zone list.
virtual void clearAddressing ()
Clear addressing.
virtual bool checkDefinition (const label maxSize, const bool report=false) const
Check zone definition with max size given. Return true if in error.
virtual void movePoints (const pointField &)
Correct patch after moving points.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from List< T >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const T &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< T > &)
Copy constructor.
template<class T2 >
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< T >> &)
Construct by transferring the parameter contents.
List (List< T > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
template<unsigned Size>
List (const FixedList< T, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< T > &)
Construct as copy of PtrList<T>
List (const SLList< T > &)
Construct as copy of SLList<T>
List (const UIndirectList< T > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< T > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< T >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
label size () const
Return the number of elements in the UList.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const T &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const T &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &)
Append an element at the end of the list.
void append (const UList< T > &)
Append a List at the end of this list.
void append (const UIndirectList< T > &)
Append a UIndirectList at the end of this list.
void transfer (List< T > &)
Transfer the contents of the argument List into this list.
template<unsigned SizeInc, unsigned SizeMult, unsigned SizeDiv>
void transfer (DynamicList< T, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< T > &)
Transfer the contents of the argument List into this list.
Xfer< List< T > > xfer ()
Transfer contents to the Xfer container.
T & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< T > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< T > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< T > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< T > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< T >)
Assignment to an initializer list.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Member Functions
static autoPtr< cellZone > New (const word &name, const dictionary &, const label index, const cellZoneMesh &)
Return a pointer to a new cell zone.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes
static const char *const labelsName = "cellLabels"
The name associated with the zone-labels dictionary entry.
Protected Attributes
const cellZoneMesh & zoneMesh_
Reference to zone list.
Protected Attributes inherited from zone
word name_
Name of zone.
label index_
Index of zone.
Map< label > * lookupMapPtr_
Map of labels in zone for fast location lookup.
Friends
Ostream & operator<< (Ostream &, const cellZone &)
Ostream Operator.
Additional Inherited Members
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Protected Member Functions inherited from zone
const Map< label > & lookupMap () const
Return a reference to the look-up map.
void calcLookupMap () const
Construct the look-up map.
zone (const zone &)
Disallow default bitwise copy construct.
Protected Member Functions inherited from List< T >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
A subset of mesh cells.
Currently set up as an indirect list but will be extended to use a primitive mesh. For quick check whether a cell belongs to the zone use the lookup mechanism in cellZoneMesh, where all the zoned cells are registered with their zone number.
Source files
cellZone.H
cellZone.C
cellZoneNew.C
Definition at line 61 of file cellZone.H.
Constructor & Destructor Documentation
cellZone() [1/5]
cellZone (const word & name, const labelUList & addr, const label index, const cellZoneMesh & zm)
Construct from components.
Definition at line 48 of file cellZone.C.
cellZone() [2/5]
cellZone (const word & name, const Xfer< labelList > & addr, const label index, const cellZoneMesh & zm)
Construct from components, transferring contents.
Definition at line 61 of file cellZone.C.
cellZone() [3/5]
cellZone (const word & name, const dictionary & dict, const label index, const cellZoneMesh & zm)
Construct from dictionary.
Definition at line 74 of file cellZone.C.
cellZone() [4/5]
cellZone (const cellZone & cz, const labelUList & addr, const label index, const cellZoneMesh & zm)
Construct given the original zone and resetting the.
cell list and zone mesh information
Definition at line 87 of file cellZone.C.
cellZone() [5/5]
cellZone (const cellZone & cz, const Xfer< labelList > & addr, const label index, const cellZoneMesh & zm)
Construct given the original zone, resetting the.
cell list and zone mesh information
Definition at line 99 of file cellZone.C.
~cellZone()
~cellZone () virtual
Destructor.
Definition at line 113 of file cellZone.C.
Referenced by cellZone::clone().
Member Function Documentation
TypeName()
TypeName ("cellZone")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , cellZone , dictionary , (const word &name, const dictionary &dict, const label index, const cellZoneMesh &zm) , (name, dict, index, zm))
clone() [1/2]
virtual autoPtr<cellZone> clone (const cellZoneMesh & zm) const inline virtual
Construct and return a clone, resetting the zone mesh.
Definition at line 161 of file cellZone.H.
References List< T >::clone(), and zone::index().
clone() [2/2]
virtual autoPtr<cellZone> clone (const labelUList & addr, const label index, const cellZoneMesh & zm) const inline virtual
Construct and return a clone, resetting the cell list.
and zone mesh
Definition at line 172 of file cellZone.H.
References cellZone::checkDefinition(), cellZone::checkParallelSync(), cellZone::New(), cellZone::operator<<, cellZone::operator=(), cellZone::whichCell(), cellZone::writeDict(), cellZone::zoneMesh(), and cellZone::~cellZone().
New()
Foam::autoPtr< Foam::cellZone > New (const word & name, const dictionary & dict, const label index, const cellZoneMesh & zm) static
Return a pointer to a new cell zone.
created on freestore from dictionary
Definition at line 32 of file cellZoneNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, InfoInFunction, dictionary::lookup(), Foam::name(), and Foam::nl.
Referenced by cellZone::clone().
whichCell()
Foam::label whichCell (const label globalCellID) const
Helper function to re-direct to zone::localID(...)
Definition at line 119 of file cellZone.C.
References zone::localID().
Referenced by cellZone::clone().
zoneMesh()
const Foam::cellZoneMesh & zoneMesh () const
Return zoneMesh reference.
Definition at line 125 of file cellZone.C.
Referenced by cellZone::clone().
checkDefinition()
bool checkDefinition (const bool report = false) const virtual
Check zone definition. Return true if in error.
Implements zone.
Definition at line 131 of file cellZone.C.
References zone::checkDefinition().
Referenced by cellZone::clone().
checkParallelSync()
virtual bool checkParallelSync (const bool report = false) const inline virtual
Check whether zone is synchronised across coupled boundaries. Return.
true if in error.
Definition at line 215 of file cellZone.H.
Referenced by cellZone::clone().
writeDict()
void writeDict (Ostream & os) const virtual
Write dictionary.
Implements zone.
Definition at line 137 of file cellZone.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::name(), Foam::nl, and Foam::type().
Referenced by cellZone::clone().
operator=() [1/3]
void operator= (const cellZone & zn)
Assign to zone, clearing demand-driven data.
Definition at line 150 of file cellZone.C.
References List< label >::operator=().
Referenced by cellZone::clone().
operator=() [2/3]
void operator= (const labelUList & addr)
Assign addressing, clearing demand-driven data.
Definition at line 157 of file cellZone.C.
References List< label >::operator=().
operator=() [3/3]
void operator= (const Xfer< labelList > & addr)
Assign addressing, clearing demand-driven data.
Definition at line 164 of file cellZone.C.
References List< label >::operator=().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const cellZone &) friend
Ostream Operator.
Referenced by cellZone::clone().
Member Data Documentation
zoneMesh_
const cellZoneMesh& zoneMesh_ protected
Reference to zone list.
Definition at line 71 of file cellZone.H.
labelsName
const char *const labelsName = "cellLabels" static
The name associated with the zone-labels dictionary entry.
Definition at line 87 of file cellZone.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/zones/cellZone/cellZone.H
src/OpenFOAM/meshes/polyMesh/zones/cellZone/cellZone.C
src/OpenFOAM/meshes/polyMesh/zones/cellZone/cellZoneNew.C