OpenFOAM: pyramid< Point, PointRef, polygonRef > Class Template Reference
pyramid< Point, PointRef, polygonRef > Class Template Reference
A geometric pyramid primitive with a base of 'n' sides: i.e. a parametric pyramid. A pyramid is constructed from a base polygon and an apex point.
Public Member Functions
pyramid (polygonRef base, const Point &apex)
Construct from base polygon and apex point.
pyramid (Istream &)
Construct from Istream.
const Point & apex () const
Return apex point.
polygonRef base () const
Return base polygon.
Point centre (const pointField &points) const
Return centre (centroid)
vector height (const pointField &points) const
Return height vector.
scalar mag (const pointField &points) const
Return scalar magnitude - returns volume of pyramid.
Friends
Istream & operator>> (Istream &, pyramid &)
Ostream & operator (Ostream &, const pyramid &)
Detailed Description
template<class Point, class PointRef, class polygonRef>
class Foam::pyramid< Point, PointRef, polygonRef >
A geometric pyramid primitive with a base of 'n' sides: i.e. a parametric pyramid. A pyramid is constructed from a base polygon and an apex point.
Source files
pyramid.H
pyramidI.H
Definition at line 47 of file pyramid.H.
Constructor & Destructor Documentation
pyramid() [1/2]
pyramid (polygonRef base, const Point & apex) inline
Construct from base polygon and apex point.
Definition at line 34 of file pyramidI.H.
pyramid() [2/2]
pyramid (Istream & is) inline
Construct from Istream.
Definition at line 45 of file pyramidI.H.
References IOstream::check().
Member Function Documentation
apex()
const Point & apex () const inline
Return apex point.
Definition at line 55 of file pyramidI.H.
base()
polygonRef base () const inline
Return base polygon.
Definition at line 61 of file pyramidI.H.
References pyramid< Point, PointRef, polygonRef >::centre().
centre()
Point centre (const pointField & points) const inline
Return centre (centroid)
Definition at line 69 of file pyramidI.H.
References pyramid< Point, PointRef, polygonRef >::height().
Referenced by pyramid< Point, PointRef, polygonRef >::base().
height()
Foam::vector height (const pointField & points) const inline
Return height vector.
Definition at line 79 of file pyramidI.H.
References pyramid< Point, PointRef, polygonRef >::mag().
Referenced by pyramid< Point, PointRef, polygonRef >::centre().
mag()
Foam::scalar mag (const pointField & points) const inline
Return scalar magnitude - returns volume of pyramid.
Definition at line 90 of file pyramidI.H.
References Foam::nl, p, and Foam::tab.
Referenced by pyramid< Point, PointRef, polygonRef >::height().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , pyramid< Point, PointRef, polygonRef > &) friend
operator
Ostream& operator (Ostream & , const pyramid< Point, PointRef, polygonRef > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/pyramid/pyramid.H
src/OpenFOAM/meshes/primitiveShapes/pyramid/pyramidI.H