OpenFOAM: plane Class Reference
plane Class Reference
Geometric class that creates a 2D plane and can return the intersection point between a line and the plane.
Classes
class ray
A direction and a reference point.
Public Types
enum side { NORMAL, FLIP }
Side of the plane.
Public Member Functions
plane (const vector &normalVector)
Construct from normal vector through the origin.
plane (const point &basePoint, const vector &normalVector)
Construct from normal vector and point in plane.
plane (const point &point1, const point &point2, const point &point3)
Construct from three points in plane.
plane (const scalarList &C)
Construct from coefficients for the.
plane (const dictionary &planeDict)
Construct from dictionary.
plane (Istream &is)
Construct from Istream. Assumes the base + normal notation.
const vector & normal () const
Return plane normal.
const point & refPoint () const
Return or return plane base point.
FixedList< scalar, 4 > planeCoeffs () const
Return coefficients for the.
point nearestPoint (const point &p) const
Return nearest point in the plane for the given point.
scalar distance (const point &p) const
Return distance from the given point to the plane.
scalar normalIntersect (const point &pnt0, const vector &dir) const
Return cut coefficient for plane and line defined by.
scalar normalIntersect (const ray &r) const
Return cut coefficient for plane and ray.
template<class Point , class PointRef >
scalar lineIntersect (const line< Point, PointRef > &l) const
Return the cutting point between the plane and.
ray planeIntersect (const plane &) const
Return the cutting line between this plane and another.
point planePlaneIntersect (const plane &, const plane &) const
Return the cutting point between this plane and two other planes.
side sideOfPlane (const point &p) const
Return the side of the plane that the point is on.
point mirror (const point &p) const
Mirror the supplied point in the plane. Return the mirrored point.
void writeDict (Ostream &) const
Write to dictionary.
Friends
bool operator== (const plane &, const plane &)
bool operator!= (const plane &, const plane &)
Ostream & operator<< (Ostream &, const plane &)
Write plane properties.
Detailed Description
Geometric class that creates a 2D plane and can return the intersection point between a line and the plane.
Source files
plane.H
plane.C
Definition at line 60 of file plane.H.
Member Enumeration Documentation
side
enum side
Side of the plane.
Enumerator
NORMAL
FLIP
Definition at line 65 of file plane.H.
Constructor & Destructor Documentation
plane() [1/6]
plane (const vector & normalVector)
Construct from normal vector through the origin.
Definition at line 112 of file plane.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::mag().
Referenced by plane::ray::dir(), and plane::plane().
plane() [2/6]
plane (const point & basePoint, const vector & normalVector)
Construct from normal vector and point in plane.
Definition at line 132 of file plane.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::mag().
plane() [3/6]
plane (const point & point1, const point & point2, const point & point3)
Construct from three points in plane.
Definition at line 159 of file plane.C.
plane() [4/6]
plane (const scalarList & C)
Construct from coefficients for the.
plane equation: ax + by + cz + d = 0
Definition at line 152 of file plane.C.
References plane::plane().
plane() [5/6]
plane (const dictionary & planeDict)
Construct from dictionary.
Definition at line 169 of file plane.C.
References Foam::abort(), C, Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), dictionary::lookup(), Foam::mag(), Foam::nl, Foam::readScalar(), and dictionary::subDict().
plane() [6/6]
plane (Istream & is)
Construct from Istream. Assumes the base + normal notation.
Definition at line 226 of file plane.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and Foam::mag().
Member Function Documentation
normal()
const Foam::vector & normal () const
Return plane normal.
Definition at line 248 of file plane.C.
Referenced by geomCellLooper::cut(), plane::ray::dir(), plane::mirror(), NamedEnum< directionType, 3 >::names(), tetrahedron< Point, PointRef >::storeOp::operator()(), plane::planeIntersect(), and cuttingPlane::reCut().
refPoint()
const Foam::point & refPoint () const
Return or return plane base point.
Definition at line 254 of file plane.C.
Referenced by NamedEnum< directionType, 3 >::names(), tetrahedron< Point, PointRef >::storeOp::operator()(), plane::planeIntersect(), cuttingPlane::reCut(), and searchablePlane::size().
planeCoeffs()
Foam::FixedList< Foam::scalar, 4 > planeCoeffs () const
Return coefficients for the.
plane equation: ax + by + cz + d = 0
Definition at line 260 of file plane.C.
References C, Foam::mag(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by plane::ray::dir(), and plane::planePlaneIntersect().
nearestPoint()
Foam::point nearestPoint (const point & p) const
Return nearest point in the plane for the given point.
Definition at line 307 of file plane.C.
Referenced by plane::ray::dir(), and plane::mirror().
distance()
Foam::scalar distance (const point & p) const
Return distance from the given point to the plane.
Definition at line 313 of file plane.C.
References Foam::mag(), and plane::normalIntersect().
Referenced by geomCellLooper::cut(), plane::ray::dir(), and plane::mirror().
normalIntersect() [1/2]
Foam::scalar normalIntersect (const point & pnt0, const vector & dir) const
Return cut coefficient for plane and line defined by.
origin and direction
Definition at line 320 of file plane.C.
References Foam::stabilise().
Referenced by plane::ray::dir(), plane::distance(), plane::lineIntersect(), and plane::normalIntersect().
normalIntersect() [2/2]
scalar normalIntersect (const ray & r) const inline
Return cut coefficient for plane and ray.
Definition at line 170 of file plane.H.
References plane::ray::dir(), plane::normalIntersect(), and plane::ray::refPoint().
lineIntersect()
scalar lineIntersect (const line< Point, PointRef > & l) const inline
Return the cutting point between the plane and.
a line passing through the supplied points
Definition at line 178 of file plane.H.
References plane::mirror(), plane::normalIntersect(), plane::operator!=, plane::operator<<, plane::operator==, plane::planeIntersect(), plane::planePlaneIntersect(), plane::sideOfPlane(), line< Point, PointRef >::start(), line< Point, PointRef >::vec(), and plane::writeDict().
Referenced by slidingInterface::modifyMotionPoints().
planeIntersect()
Foam::plane::ray planeIntersect (const plane & plane2) const
Return the cutting line between this plane and another.
Returned as direction vector and point line goes through.
Definition at line 331 of file plane.C.
References Foam::mag(), plane::normal(), plane::planePlaneIntersect(), plane::refPoint(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by plane::lineIntersect(), and listPlusEqOp< T >::operator()().
planePlaneIntersect()
Foam::point planePlaneIntersect (const plane & plane2, const plane & plane3) const
Return the cutting point between this plane and two other planes.
Definition at line 399 of file plane.C.
References Foam::constant::physicoChemical::b, Foam::inv(), and plane::planeCoeffs().
Referenced by plane::lineIntersect(), listPlusEqOp< T >::operator()(), and plane::planeIntersect().
sideOfPlane()
Foam::plane::side sideOfPlane (const point & p) const
Return the side of the plane that the point is on.
If the point is on the plane, then returns NORMAL.
Definition at line 421 of file plane.C.
References plane::FLIP, and plane::NORMAL.
Referenced by plane::lineIntersect().
mirror()
Foam::point mirror (const point & p) const
Mirror the supplied point in the plane. Return the mirrored point.
Definition at line 429 of file plane.C.
References plane::distance(), plane::nearestPoint(), and plane::normal().
Referenced by plane::lineIntersect().
writeDict()
void writeDict (Ostream & os) const
Write to dictionary.
Definition at line 444 of file plane.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::nl, and Ostream::writeKeyword().
Referenced by plane::lineIntersect().
Friends And Related Function Documentation
operator==
bool operator== (const plane & , const plane &) friend
Referenced by plane::lineIntersect().
operator!=
bool operator!= (const plane & , const plane &) friend
Referenced by plane::lineIntersect().
operator<<
Ostream& operator<< (Ostream & , const plane &) friend
Write plane properties.
Referenced by plane::lineIntersect().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/plane/plane.H
src/OpenFOAM/meshes/primitiveShapes/plane/plane.C