OpenFOAM: tetrahedron< Point, PointRef >::storeOp Class Reference
tetrahedron< Point, PointRef >::storeOp Class Reference
Store resulting tets.
Public Member Functions
storeOp (tetIntersectionList &, label &)
void operator() (const tetPoints &)
Detailed Description
template<class Point, class PointRef>
class Foam::tetrahedron< Point, PointRef >::storeOp
Store resulting tets.
Definition at line 118 of file tetrahedron.H.
Constructor & Destructor Documentation
storeOp()
storeOp (tetIntersectionList & tets, label & nTets) inline
Definition at line 558 of file tetrahedronI.H.
Referenced by tetrahedron< Point, PointRef >::sumVolOp::operator()().
Member Function Documentation
operator()()
void operator() (const tetPoints & tet) inline
Definition at line 570 of file tetrahedronI.H.
References Foam::abort(), tetrahedron< Point, PointRef >::d(), Foam::FatalError, FatalErrorInFunction, FixedList< T, Size >::fcIndex(), forAll, plane::normal(), p, plane::refPoint(), and tetrahedron< Point, PointRef >::sliceWithPlane().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedron.H
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedronI.H