OpenFOAM: Pair< Type > Class Template Reference
Pair< Type > Class Template Reference
An ordered pair of two objects of type <T> with first() and second() elements.
Public Member Functions
Pair ()
Null constructor.
Pair (const Type &f, const Type &s)
Construct from components.
Pair (const FixedList< Type, 2 > &fl)
Construct from FixedList.
Pair (Istream &is)
Construct from Istream.
const Type & first () const
Return first.
Type & first ()
Return first.
const Type & second () const
Return second.
Type & second ()
Return second.
const Type & other (const Type &a) const
Return other.
Public Member Functions inherited from FixedList< Type, 2 >
FixedList ()
Null constructor.
FixedList (const Type &)
Construct from value.
FixedList (const Type v[Size])
Construct from C-array.
FixedList (InputIterator first, InputIterator last)
Construct given start and end iterators.
FixedList (std::initializer_list< Type >)
Construct from an initializer list.
FixedList (const UList< Type > &)
Construct from UList.
FixedList (const SLList< Type > &)
Construct from SLList.
FixedList (const FixedList< Type, Size > &)
Copy constructor.
FixedList (Istream &)
Construct from Istream.
autoPtr< FixedList< Type, Size > > clone () const
Clone.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void resize (const label)
Dummy resize function.
void setSize (const label)
Dummy setSize function.
void transfer (const FixedList< Type, Size > &)
Copy (not transfer) the argument contents.
void writeEntry (Ostream &) const
Write the FixedList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the FixedList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of FixedList.
const Type & operator[] (const label) const
Return element of constant FixedList.
void operator= (const Type v[Size])
Assignment to array operator. Takes linear time.
void operator= (const UList< Type > &)
Assignment to UList operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment to SLList operator. Takes linear time.
void operator= (std::initializer_list< Type >)
Assignment to an initializer list. Takes linear time.
void operator= (const Type &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the FixedList.
const_iterator begin () const
Return const_iterator to begin traversing the constant FixedList.
iterator end ()
Return an iterator to end traversing the FixedList.
const_iterator end () const
Return const_iterator to end traversing the constant FixedList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant FixedList.
const_iterator cend () const
Return const_iterator to end traversing the constant FixedList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the FixedList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the FixedList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing FixedList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing FixedList.
label size () const
Return the number of elements in the FixedList.
label max_size () const
Return size of the largest possible FixedList.
bool empty () const
Return true if the FixedList is empty (ie, size() is zero)
void swap (FixedList< Type, Size > &)
Swap two FixedLists of the same type in constant time.
bool operator== (const FixedList< Type, Size > &) const
Equality operation on FixedLists of the same type.
bool operator!= (const FixedList< Type, Size > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const FixedList< Type, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator> (const FixedList< Type, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator<= (const FixedList< Type, Size > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const FixedList< Type, Size > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static int compare (const Pair< Type > &a, const Pair< Type > &b)
Compare Pairs.
Static Public Member Functions inherited from FixedList< Type, 2 >
static const FixedList< Type, Size > & null ()
Return a null FixedList.
Additional Inherited Members
Public Types inherited from FixedList< Type, 2 >
typedef Type value_type
Type of values the FixedList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a FixedList.
typedef Type * iterator
Random access iterator for traversing FixedList.
typedef const Type * const_iterator
Random access iterator for traversing FixedList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of FixedList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant FixedList.
Detailed Description
template<class Type>
class Foam::Pair< Type >
An ordered pair of two objects of type <T> with first() and second() elements.
See also
Foam::Tuple2 for storing two objects of dissimilar types.
Definition at line 49 of file contiguous.H.
Constructor & Destructor Documentation
Pair() [1/4]
Pair () inline
Null constructor.
Definition at line 61 of file Pair.H.
Pair() [2/4]
Pair (const Type & f, const Type & s) inline
Construct from components.
Definition at line 65 of file Pair.H.
Pair() [3/4]
Pair (const FixedList< Type, 2 > & fl) inline
Construct from FixedList.
Definition at line 72 of file Pair.H.
Pair() [4/4]
Pair (Istream & is) inline
Construct from Istream.
Definition at line 78 of file Pair.H.
Member Function Documentation
first() [1/2]
const Type& first () const inline
Return first.
Definition at line 87 of file Pair.H.
Referenced by globalIndexAndTransform::addToTransformIndex(), preserveBafflesConstraint::apply(), meshRefinement::balance(), polyMeshFilter::copyMesh(), meshRefinement::createZoneBaffles(), decompositionMethod::decompose(), snappySnapDriver::doSnap(), Foam::faceNij(), Foam::facePointN(), globalIndexAndTransform::globalIndexAndTransform(), globalIndexAndTransform::index(), linearInterpolationWeights::integrationWeights(), Distribution< Type >::normalised(), multiphaseMixtureThermo::interfacePair::hash::operator()(), multiphaseMixture::interfacePair::hash::operator()(), multiphaseSystem::interfacePair::symmHash::operator()(), multiphaseSystem::interfacePair::hash::operator()(), Pair< word >::other(), Pair< word >::Pair(), Distribution< Type >::raw(), globalIndexAndTransform::transformIndicesForPatches(), and Distribution< Type >::validLimits().
first() [2/2]
Type& first () inline
Return first.
Definition at line 93 of file Pair.H.
second() [1/2]
const Type& second () const inline
Return second.
Definition at line 99 of file Pair.H.
Referenced by globalIndexAndTransform::addToTransformIndex(), preserveBafflesConstraint::apply(), meshRefinement::balance(), polyMeshFilter::copyMesh(), meshRefinement::createZoneBaffles(), decompositionMethod::decompose(), snappySnapDriver::doSnap(), Foam::faceNij(), Foam::facePointN(), linearInterpolationWeights::integrationWeights(), Distribution< Type >::normalised(), multiphaseMixtureThermo::interfacePair::hash::operator()(), multiphaseMixture::interfacePair::hash::operator()(), multiphaseSystem::interfacePair::symmHash::operator()(), multiphaseSystem::interfacePair::hash::operator()(), Pair< word >::other(), Pair< word >::Pair(), globalIndexAndTransform::processor(), Distribution< Type >::raw(), globalIndexAndTransform::transformIndex(), globalIndexAndTransform::transformIndicesForPatches(), and Distribution< Type >::validLimits().
second() [2/2]
Type& second () inline
Return second.
Definition at line 105 of file Pair.H.
other()
const Type& other (const Type & a) const inline
Return other.
Definition at line 111 of file Pair.H.
compare()
static int compare (const Pair< Type > & a, const Pair< Type > & b) inline static
Compare Pairs.
Returning:
0: different
+1: identical
-1: same pair, but reversed order
Definition at line 141 of file Pair.H.
Referenced by preserveBafflesConstraint::add(), minEqOp< labelPair >::operator()(), and Pair< word >::other().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/contiguous/contiguous.H
src/OpenFOAM/primitives/Pair/Pair.H