OpenFOAM: treeBoundBox Class Reference
treeBoundBox Class Reference
Standard boundBox + extra functionality for use in octree.
Public Types
enum octantBit { RIGHTHALF = 0x1 << 0, TOPHALF = 0x1 << 1, FRONTHALF = 0x1 << 2 }
Bits used for octant/point coding.
enum faceId {
LEFT = 0, RIGHT = 1, BOTTOM = 2, TOP = 3,
BACK = 4, FRONT = 5
}
Face codes.
enum faceBit {
NOFACE = 0, LEFTBIT = 0x1 << LEFT, RIGHTBIT = 0x1 << RIGHT, BOTTOMBIT = 0x1 << BOTTOM,
TOPBIT = 0x1 << TOP, BACKBIT = 0x1 << BACK, FRONTBIT = 0x1 << FRONT
}
Bits used for face coding.
enum edgeId {
E01 = 0, E13 = 1, E23 = 2, E02 = 3,
E45 = 4, E57 = 5, E67 = 6, E46 = 7,
E04 = 8, E15 = 9, E37 = 10, E26 = 11
}
Edges codes.
Public Member Functions
treeBoundBox ()
Construct null setting points to zero.
treeBoundBox (const boundBox &bb)
Construct from a boundBox.
treeBoundBox (const point &min, const point &max)
Construct from components.
treeBoundBox (const UList< point > &)
Construct as the bounding box of the given pointField.
treeBoundBox (const UList< point > &, const labelUList &indices)
Construct as subset of points.
template<unsigned Size>
treeBoundBox (const UList< point > &, const FixedList< label, Size > &indices)
Construct as subset of points.
treeBoundBox (Istream &)
Construct from Istream.
scalar typDim () const
Typical dimension length,height,width.
tmp< pointField > points () const
Vertex coordinates. In octant coding.
point corner (const direction) const
Corner point given octant.
treeBoundBox subBbox (const direction) const
Sub box given by octant number. Midpoint calculated.
treeBoundBox subBbox (const point &mid, const direction) const
Sub box given by octant number. Midpoint provided.
direction subOctant (const point &pt) const
Returns octant number given point and the calculated midpoint.
direction subOctant (const point &pt, bool &onEdge) const
Returns octant number given point and the calculated midpoint.
void searchOrder (const point &pt, FixedList< direction, 8 > &octantOrder) const
Calculates optimal order to look for nearest to point.
bool intersects (const point &overallStart, const vector &overallVec, const point &start, const point &end, point &pt, direction &ptBits) const
Intersects segment; set point to intersection position and face,.
bool intersects (const point &start, const point &end, point &pt) const
Like above but does not return faces point is on.
bool contains (const vector &dir, const point &) const
Contains point (inside or on edge) and moving in direction.
direction faceBits (const point &) const
Code position of point on bounding box faces.
direction posBits (const point &) const
Position of point relative to bounding box.
void calcExtremities (const point &pt, point &nearest, point &furthest) const
Calculate nearest and furthest (to point) vertex coords of.
scalar maxDist (const point &) const
Returns distance point to furthest away corner.
label distanceCmp (const point &, const treeBoundBox &other) const
Compare distance to point with other bounding box.
treeBoundBox extend (Random &, const scalar s) const
Return slightly wider bounding box.
Public Member Functions inherited from boundBox
boundBox ()
Construct null, setting points to zero.
boundBox (const point &min, const point &max)
Construct from components.
boundBox (const UList< point > &, const bool doReduce=true)
Construct as the bounding box of the given points.
boundBox (const tmp< pointField > &, const bool doReduce=true)
Construct as the bounding box of the given temporary pointField.
boundBox (const UList< point > &, const labelUList &indices, const bool doReduce=true)
Construct bounding box as subset of the pointField.
template<unsigned Size>
boundBox (const UList< point > &, const FixedList< label, Size > &indices, const bool doReduce=true)
Construct bounding box as subset of the pointField.
boundBox (Istream &)
Construct from Istream.
const point & min () const
Minimum describing the bounding box.
const point & max () const
Maximum describing the bounding box.
point & min ()
Minimum describing the bounding box, non-const access.
point & max ()
Maximum describing the bounding box, non-const access.
point midpoint () const
The midpoint of the bounding box.
vector span () const
The bounding box span (from minimum to maximum)
scalar mag () const
The magnitude of the bounding box span.
scalar volume () const
The volume of the bound box.
scalar minDim () const
Smallest length/height/width dimension.
scalar maxDim () const
Largest length/height/width dimension.
scalar avgDim () const
Average length/height/width dimension.
tmp< pointField > points () const
Return corner points in an order corresponding to a 'hex' cell.
void inflate (const scalar s)
Inflate box by factor*mag(span) in all dimensions.
bool overlaps (const boundBox &) const
Overlaps/touches boundingBox?
bool overlaps (const point &, const scalar radiusSqr) const
Overlaps boundingSphere (centre + sqr(radius))?
bool contains (const point &) const
Contains point? (inside or on edge)
bool contains (const boundBox &) const
Fully contains other boundingBox?
bool containsInside (const point &) const
Contains point? (inside only)
bool contains (const UList< point > &) const
Contains all of the points? (inside or on edge)
bool contains (const UList< point > &, const labelUList &indices) const
Contains all of the points? (inside or on edge)
template<unsigned Size>
bool contains (const UList< point > &, const FixedList< label, Size > &indices) const
Contains all of the points? (inside or on edge)
bool containsAny (const UList< point > &) const
Contains any of the points? (inside or on edge)
bool containsAny (const UList< point > &, const labelUList &indices) const
Contains any of the points? (inside or on edge)
template<unsigned Size>
bool containsAny (const UList< point > &, const FixedList< label, Size > &indices) const
Contains any of the points? (inside or on edge)
point nearest (const point &) const
Return the nearest point on the boundBox to the supplied point.
Static Public Member Functions
static direction subOctant (const point &mid, const point &pt)
Returns octant number given point and midpoint.
static direction subOctant (const point &mid, const point &pt, bool &onEdge)
Returns octant number given point and midpoint.
static direction subOctant (const point &mid, const vector &dir, const point &pt, bool &onEdge)
Returns octant number given intersection and midpoint.
Static Public Member Functions inherited from boundBox
static faceList faces ()
Return faces with correct point order.
Static Public Attributes
static const scalar great
The great value used for greatBox and invertedBox.
static const treeBoundBox greatBox
As per boundBox::greatBox, but with GREAT instead of VGREAT.
static const treeBoundBox invertedBox
As per boundBox::invertedBox, but with GREAT instead of VGREAT.
static const faceList faces
Face to point addressing.
static const edgeList edges
Edge to point addressing.
static const FixedList< vector, 6 > faceNormals
Per face the unit normal.
Static Public Attributes inherited from boundBox
static const scalar great
The great value used for greatBox and invertedBox.
static const boundBox greatBox
A very large boundBox: min/max == -/+ VGREAT.
static const boundBox invertedBox
A very large inverted boundBox: min/max == +/- VGREAT.
Friends
bool operator== (const treeBoundBox &, const treeBoundBox &)
bool operator!= (const treeBoundBox &, const treeBoundBox &)
Istream & operator>> (Istream &is, treeBoundBox &)
Ostream & operator<< (Ostream &os, const treeBoundBox &)
Detailed Description
Standard boundBox + extra functionality for use in octree.
Numbering of corner points is according to octant numbering.
On the back plane (z=0):
    Y
    ^
    |
    +--------+
    |2      3|
    |        |
    |        |
    |        |
    |0      1|
    +--------+->X
For the front plane add 4 to the point labels.
Source files
treeBoundBox.H
treeBoundBoxI.H
treeBoundBox.C
treeBoundBoxTemplates.C
Definition at line 87 of file treeBoundBox.H.
Member Enumeration Documentation
octantBit
enum octantBit
Bits used for octant/point coding.
Every octant/corner point is the combination of three faces.
Enumerator
RIGHTHALF
TOPHALF
FRONTHALF
Definition at line 115 of file treeBoundBox.H.
faceId
enum faceId
Face codes.
Enumerator
LEFT
RIGHT
BOTTOM
TOP
BACK
FRONT
Definition at line 123 of file treeBoundBox.H.
faceBit
enum faceBit
Bits used for face coding.
Enumerator
NOFACE
LEFTBIT
RIGHTBIT
BOTTOMBIT
TOPBIT
BACKBIT
FRONTBIT
Definition at line 134 of file treeBoundBox.H.
edgeId
enum edgeId
Edges codes.
E01 = edge between 0 and 1.
Enumerator
E01
E13
E23
E02
E45
E57
E67
E46
E04
E15
E37
E26
Definition at line 147 of file treeBoundBox.H.
Constructor & Destructor Documentation
treeBoundBox() [1/7]
treeBoundBox () inline
Construct null setting points to zero.
Definition at line 31 of file treeBoundBoxI.H.
Referenced by treeBoundBox::treeBoundBox().
treeBoundBox() [2/7]
treeBoundBox (const boundBox & bb) inline explicit
Construct from a boundBox.
Definition at line 43 of file treeBoundBoxI.H.
treeBoundBox() [3/7]
treeBoundBox (const point & min, const point & max) inline
Construct from components.
Definition at line 37 of file treeBoundBoxI.H.
treeBoundBox() [4/7]
treeBoundBox (const UList< point > & points) explicit
Construct as the bounding box of the given pointField.
Local processor domain only (no reduce as in boundBox)
Definition at line 129 of file treeBoundBox.C.
References UList< T >::empty(), Foam::endl(), treeBoundBox::treeBoundBox(), and WarningInFunction.
treeBoundBox() [5/7]
treeBoundBox (const UList< point > & points, const labelUList & indices)
Construct as subset of points.
Local processor domain only (no reduce as in boundBox)
Definition at line 145 of file treeBoundBox.C.
References UList< T >::empty(), Foam::endl(), and WarningInFunction.
treeBoundBox() [6/7]
treeBoundBox (const UList< point > & points, const FixedList< label, Size > & indices)
Construct as subset of points.
The indices could be from edge/triFace etc. Local processor domain only (no reduce as in boundBox)
Definition at line 35 of file treeBoundBoxTemplates.C.
References UList< T >::empty(), Foam::endl(), and WarningInFunction.
treeBoundBox() [7/7]
treeBoundBox (Istream & is) inline
Construct from Istream.
Definition at line 49 of file treeBoundBoxI.H.
Member Function Documentation
typDim()
Foam::scalar typDim () const inline
Typical dimension length,height,width.
Definition at line 57 of file treeBoundBoxI.H.
References boundBox::avgDim().
points()
Foam::tmp< Foam::pointField > points () const
Vertex coordinates. In octant coding.
Definition at line 165 of file treeBoundBox.C.
References treeBoundBox::corner(), forAll, and tmp< T >::ref().
Referenced by searchableBox::boundingSpheres(), searchableBox::coordinates(), indexedOctree< Foam::treeDataFace >::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), and searchableBox::points().
corner()
Foam::point corner (const direction octant) const inline
Corner point given octant.
Definition at line 63 of file treeBoundBoxI.H.
References treeBoundBox::FRONTHALF, boundBox::max(), boundBox::min(), treeBoundBox::RIGHTHALF, treeBoundBox::TOPHALF, x, and y.
Referenced by treeBoundBox::points().
subBbox() [1/2]
Foam::treeBoundBox subBbox (const direction octant) const
Sub box given by octant number. Midpoint calculated.
Definition at line 179 of file treeBoundBox.C.
References boundBox::midpoint().
Referenced by indexedOctree< Foam::treeDataFace >::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::insertIndex(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::overlaps(), indexedOctree< Foam::treeDataFace >::overlaps(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::print(), indexedOctree< Foam::treeDataFace >::print(), and dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::removeIndex().
subBbox() [2/2]
Foam::treeBoundBox subBbox (const point & mid, const direction octant) const
Sub box given by octant number. Midpoint provided.
Definition at line 186 of file treeBoundBox.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, treeBoundBox::FRONTHALF, treeBoundBox::intersects(), boundBox::max(), boundBox::min(), treeBoundBox::RIGHTHALF, treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
subOctant() [1/5]
Foam::direction subOctant (const point & pt) const inline
Returns octant number given point and the calculated midpoint.
Definition at line 75 of file treeBoundBoxI.H.
References boundBox::midpoint().
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::overlaps(), and treeBoundBox::subOctant().
subOctant() [2/5]
Foam::direction subOctant (const point & mid, const point & pt) inline static
Returns octant number given point and midpoint.
Definition at line 84 of file treeBoundBoxI.H.
References treeBoundBox::FRONTHALF, treeBoundBox::RIGHTHALF, treeBoundBox::subOctant(), treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
subOctant() [3/5]
Foam::direction subOctant (const point & pt, bool & onEdge) const inline
Returns octant number given point and the calculated midpoint.
onEdge set if the point is on edge of subOctant
Definition at line 113 of file treeBoundBoxI.H.
References boundBox::midpoint(), and treeBoundBox::subOctant().
subOctant() [4/5]
Foam::direction subOctant (const point & mid, const point & pt, bool & onEdge) inline static
Returns octant number given point and midpoint.
onEdge set if the point is on edge of subOctant
Definition at line 125 of file treeBoundBoxI.H.
References treeBoundBox::FRONTHALF, treeBoundBox::RIGHTHALF, treeBoundBox::subOctant(), treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
subOctant() [5/5]
Foam::direction subOctant (const point & mid, const vector & dir, const point & pt, bool & onEdge) inline static
Returns octant number given intersection and midpoint.
onEdge set if the point is on edge of subOctant If onEdge, the direction vector determines which octant to use (acc. to which octant the point would be if it were moved along dir)
Definition at line 170 of file treeBoundBoxI.H.
References treeBoundBox::FRONTHALF, treeBoundBox::RIGHTHALF, treeBoundBox::searchOrder(), treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
searchOrder()
void searchOrder (const point & pt, FixedList< direction, 8 > & octantOrder) const inline
Calculates optimal order to look for nearest to point.
First will be the octant containing the point, second the octant with boundary nearest to the point etc.
Definition at line 226 of file treeBoundBoxI.H.
References treeBoundBox::extend(), treeBoundBox::FRONTHALF, boundBox::max(), boundBox::midpoint(), boundBox::min(), treeBoundBox::RIGHTHALF, treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by treeBoundBox::subOctant().
intersects() [1/2]
bool intersects (const point & overallStart, const vector & overallVec, const point & start, const point & end, point & pt, direction & ptBits) const
Intersects segment; set point to intersection position and face,.
return true if intersection found. (pt argument used during calculation even if not intersecting). Calculates intersections from outside supplied vector (overallStart, overallVec). This is so when e.g. tracking through lots of consecutive boxes (typical octree) we're not accumulating truncation errors. Set to start, (end-start) if not used.
Definition at line 235 of file treeBoundBox.C.
References treeBoundBox::BACKBIT, treeBoundBox::BOTTOMBIT, treeBoundBox::faceBits(), treeBoundBox::FRONTBIT, treeBoundBox::LEFTBIT, Foam::mag(), boundBox::max(), boundBox::min(), treeBoundBox::posBits(), treeBoundBox::RIGHTBIT, s(), treeBoundBox::TOPBIT, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by indexedOctree< Foam::treeDataFace >::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), triangleFuncs::intersectBb(), treeBoundBox::intersects(), NamedEnum< directionType, 3 >::names(), treeDataEdge::overlaps(), and treeBoundBox::subBbox().
intersects() [2/2]
bool intersects (const point & start, const point & end, point & pt) const
Like above but does not return faces point is on.
Definition at line 382 of file treeBoundBox.C.
References treeBoundBox::intersects().
contains()
bool contains (const vector & dir, const point & pt) const
Contains point (inside or on edge) and moving in direction.
dir would cause it to go inside.
Definition at line 393 of file treeBoundBox.C.
References boundBox::max(), and boundBox::min().
Referenced by dynamicTreeDataPoint::findNearest(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), conformalVoronoiMesh::maxSurfaceProtrusion(), NamedEnum< directionType, 3 >::names(), dynamicTreeDataPoint::overlaps(), and treeDataPoint::overlaps().
faceBits()
Foam::direction faceBits (const point & pt) const
Code position of point on bounding box faces.
Definition at line 431 of file treeBoundBox.C.
References treeBoundBox::BACKBIT, treeBoundBox::BOTTOMBIT, treeBoundBox::FRONTBIT, treeBoundBox::LEFTBIT, boundBox::max(), boundBox::min(), treeBoundBox::RIGHTBIT, treeBoundBox::TOPBIT, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by indexedOctree< Foam::treeDataFace >::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), and treeBoundBox::intersects().
posBits()
Foam::direction posBits (const point & pt) const
Position of point relative to bounding box.
Definition at line 464 of file treeBoundBox.C.
References treeBoundBox::BACKBIT, treeBoundBox::BOTTOMBIT, treeBoundBox::calcExtremities(), treeBoundBox::FRONTBIT, treeBoundBox::LEFTBIT, boundBox::max(), boundBox::min(), treeBoundBox::RIGHTBIT, treeBoundBox::TOPBIT, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by treeDataPrimitivePatch< PatchType >::findIntersection(), indexedOctree< Foam::treeDataFace >::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), treeBoundBox::intersects(), treeDataCell::findIntersectOp::operator()(), and treeDataFace::findIntersectOp::operator()().
calcExtremities()
void calcExtremities (const point & pt, point & nearest, point & furthest) const
Calculate nearest and furthest (to point) vertex coords of.
bounding box
Definition at line 499 of file treeBoundBox.C.
References Foam::mag(), boundBox::max(), boundBox::min(), x, Vector< Cmpt >::x(), y, Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by treeBoundBox::distanceCmp(), treeBoundBox::maxDist(), and treeBoundBox::posBits().
maxDist()
Foam::scalar maxDist (const point & pt) const
Returns distance point to furthest away corner.
Definition at line 546 of file treeBoundBox.C.
References treeBoundBox::calcExtremities(), treeBoundBox::distanceCmp(), and Foam::mag().
distanceCmp()
Foam::label distanceCmp (const point & pt, const treeBoundBox & other) const
Compare distance to point with other bounding box.
return: -1 : all vertices of my bounding box are nearer than any of other +1 : all vertices of my bounding box are further away than any of other 0 : none of the above.
Definition at line 556 of file treeBoundBox.C.
References treeBoundBox::calcExtremities(), Foam::sqr(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by treeBoundBox::maxDist().
extend()
Foam::treeBoundBox extend (Random & rndGen, const scalar s) const inline
Return slightly wider bounding box.
Extends all dimensions with s*span*Random::scalar01() and guarantees in any direction s*mag(span) minimum width
Definition at line 317 of file treeBoundBoxI.H.
References Foam::cmptMultiply(), Foam::mag(), boundBox::max(), Foam::max(), boundBox::min(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, boundBox::span(), and Random::vector01().
Referenced by meshSearch::boundaryTree(), meshSearch::cellTree(), polyMesh::cellTree(), meshRefinement::distribute(), triSurfaceMesh::edgeTree(), nearestEqOp::operator()(), refinementFeatures::regionEdgeTrees(), treeBoundBox::searchOrder(), triSurfaceSearch::tree(), and triSurfaceRegionSearch::treeByRegion().
Friends And Related Function Documentation
operator==
bool operator== (const treeBoundBox & , const treeBoundBox &) friend
operator!=
bool operator!= (const treeBoundBox & , const treeBoundBox &) friend
operator>>
Istream& operator>> (Istream & is, treeBoundBox &) friend
operator<<
Ostream& operator<< (Ostream & os, const treeBoundBox &) friend
Member Data Documentation
great
const Foam::scalar great static
The great value used for greatBox and invertedBox.
Definition at line 105 of file treeBoundBox.H.
greatBox
const Foam::treeBoundBox greatBox static
As per boundBox::greatBox, but with GREAT instead of VGREAT.
Definition at line 108 of file treeBoundBox.H.
invertedBox
const Foam::treeBoundBox invertedBox static
As per boundBox::invertedBox, but with GREAT instead of VGREAT.
Definition at line 111 of file treeBoundBox.H.
faces
const Foam::faceList faces static
Face to point addressing.
Definition at line 166 of file treeBoundBox.H.
edges
const Foam::edgeList edges static
Edge to point addressing.
Definition at line 169 of file treeBoundBox.H.
faceNormals
const Foam::FixedList< Foam::vector, 6 > faceNormals static
Per face the unit normal.
Definition at line 172 of file treeBoundBox.H.
Referenced by searchableBox::getNormal().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/treeBoundBox/treeBoundBox.H
src/OpenFOAM/meshes/treeBoundBox/treeBoundBox.C
src/OpenFOAM/meshes/treeBoundBox/treeBoundBoxI.H
src/OpenFOAM/meshes/treeBoundBox/treeBoundBoxTemplates.C