OpenFOAM: plane::ray Class Reference
plane::ray Class Reference
A direction and a reference point.
Public Member Functions
ray (const point &refPoint, const vector &dir)
const point & refPoint () const
const vector & dir () const
Detailed Description
A direction and a reference point.
Definition at line 72 of file plane.H.
Constructor & Destructor Documentation
ray()
ray (const point & refPoint, const vector & dir) inline
Definition at line 79 of file plane.H.
Member Function Documentation
refPoint()
const point& refPoint () const inline
Definition at line 85 of file plane.H.
Referenced by plane::ray::dir(), and plane::normalIntersect().
dir()
const vector& dir () const inline
Definition at line 90 of file plane.H.
References plane::distance(), plane::nearestPoint(), plane::normal(), plane::normalIntersect(), p, plane::plane(), plane::planeCoeffs(), and plane::ray::refPoint().
Referenced by plane::normalIntersect().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/plane/plane.H