OpenFOAM: PointHit< Point > Class Template Reference
PointHit< Point > Class Template Reference
This class describes the interaction of a face and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
Public Member Functions
PointHit ()
Construct null.
PointHit (const bool hit, const Point &p, const scalar dist, const bool eligibleMiss)
Construct from components.
PointHit (const Point &p)
Construct from point. Hit and distance set later.
bool hit () const
Is there a hit.
const Point & hitPoint () const
Return hit point.
scalar distance () const
Return distance to hit.
const Point & missPoint () const
Return miss point.
const Point & rawPoint () const
Return point with no checking.
bool eligibleMiss () const
Is this an eligible miss.
void setHit ()
void setMiss (const bool eligible)
void setPoint (const Point &p)
void setDistance (const scalar d)
Friends
Ostream & operator (Ostream &os, const PointHit< Point > &b)
Detailed Description
template<class Point>
class Foam::PointHit< Point >
This class describes the interaction of a face and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
Definition at line 51 of file PointHit.H.
Constructor & Destructor Documentation
PointHit() [1/3]
PointHit () inline
Construct null.
Definition at line 84 of file PointHit.H.
Referenced by PointHit< point >::PointHit().
PointHit() [2/3]
PointHit (const bool hit, const Point & p, const scalar dist, const bool eligibleMiss) inline
Construct from components.
Definition at line 94 of file PointHit.H.
PointHit() [3/3]
PointHit (const Point & p) inline
Construct from point. Hit and distance set later.
Definition at line 108 of file PointHit.H.
Member Function Documentation
hit()
bool hit () const inline
Is there a hit.
Definition at line 120 of file PointHit.H.
Referenced by extendedEdgeMesh::allNearestFeatureEdges(), triSurfaceTools::calcInterpolationWeights(), mappedPatchBase::facePoint(), treeDataPrimitivePatch< PatchType >::findIntersection(), sampledSet::findNearFace(), treeDataFace::getVolumeType(), treeDataPrimitivePatch< PatchType >::getVolumeType(), face::intersection(), slidingInterface::modifyMotionPoints(), triangle< Point, PointRef >::nearestPoint(), face::nearestPointClassify(), treeDataCell::findIntersectOp::operator()(), treeDataFace::findIntersectOp::operator()(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectFaceCentres(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints(), triangle< Point, PointRef >::ray(), face::ray(), AMIInterpolation< SourcePatch, TargetPatch >::srcPointFace(), and AMIInterpolation< SourcePatch, TargetPatch >::tgtPointFace().
hitPoint()
const Point& hitPoint () const inline
Return hit point.
Definition at line 126 of file PointHit.H.
Referenced by mappedPatchBase::facePoint(), treeDataPrimitivePatch< PatchType >::findIntersection(), sampledSet::findNearFace(), face::intersection(), slidingInterface::modifyMotionPoints(), triangle< Point, PointRef >::nearestPoint(), face::nearestPointClassify(), treeDataCell::findIntersectOp::operator()(), treeDataFace::findIntersectOp::operator()(), and face::ray().
distance()
scalar distance () const inline
Return distance to hit.
Definition at line 139 of file PointHit.H.
Referenced by booleanSurface::booleanSurface(), triSurfaceTools::calcInterpolationWeights(), mappedPatchBase::facePoint(), treeDataPrimitivePatch< PatchType >::findIntersection(), dynamicTreeDataPoint::findNearest(), meshSearch::findNearestBoundaryFace(), cellPointWeight::findTetrahedron(), cellPointWeight::findTriangle(), face::intersection(), slidingInterface::modifyMotionPoints(), line< Point, PointRef >::nearestDist(), triangle< Point, PointRef >::nearestPoint(), tetrahedron< Point, PointRef >::nearestPoint(), face::nearestPointClassify(), nearestEqOp::operator()(), treeDataPoint::findNearestOp::operator()(), treeDataEdge::findNearestOp::operator()(), treeDataPrimitivePatch< PatchType >::findNearestOp::operator()(), treeDataFace::findNearestOp::operator()(), treeDataCell::findIntersectOp::operator()(), treeDataFace::findIntersectOp::operator()(), pointHitSort::operator<(), pointHitSort::operator==(), orientedSurface::orient(), treeDataEdge::overlaps(), treeDataPrimitivePatch< PatchType >::overlaps(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectFaceCentres(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints(), face::ray(), cellDistFuncs::smallestDist(), AMIInterpolation< SourcePatch, TargetPatch >::srcPointFace(), and AMIInterpolation< SourcePatch, TargetPatch >::tgtPointFace().
missPoint()
const Point& missPoint () const inline
Return miss point.
Definition at line 145 of file PointHit.H.
Referenced by sampledSet::findNearFace(), slidingInterface::modifyMotionPoints(), triangle< Point, PointRef >::nearestPoint(), face::nearestPointClassify(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectFaceCentres(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints(), and face::ray().
rawPoint()
const Point& rawPoint () const inline
Return point with no checking.
Definition at line 158 of file PointHit.H.
Referenced by extendedEdgeMesh::allNearestFeatureEdges(), booleanSurface::booleanSurface(), triSurfaceTools::calcInterpolationWeights(), tetrahedron< Point, PointRef >::containmentSphere(), dynamicTreeDataPoint::findNearest(), treeDataFace::getVolumeType(), treeDataPrimitivePatch< PatchType >::getVolumeType(), line< Point, PointRef >::nearestDist(), tetrahedron< Point, PointRef >::nearestPoint(), nearestEqOp::operator()(), treeDataPoint::findNearestOp::operator()(), treeDataEdge::findNearestOp::operator()(), treeDataPrimitivePatch< PatchType >::findNearestOp::operator()(), treeDataFace::findNearestOp::operator()(), orientedSurface::orient(), triangle< Point, PointRef >::ray(), faceCollapser::setRefinement(), and triSurfaceTools::surfaceSide().
eligibleMiss()
bool eligibleMiss () const inline
Is this an eligible miss.
Definition at line 164 of file PointHit.H.
Referenced by PrimitivePatch< Face, ::Foam::List, pointField, point >::projectFaceCentres(), PrimitivePatch< Face, ::Foam::List, pointField, point >::projectPoints(), face::ray(), AMIInterpolation< SourcePatch, TargetPatch >::srcPointFace(), and AMIInterpolation< SourcePatch, TargetPatch >::tgtPointFace().
setHit()
void setHit () inline
Definition at line 169 of file PointHit.H.
Referenced by tetrahedron< Point, PointRef >::containmentSphere(), triangle< Point, PointRef >::intersection(), face::intersection(), triangle< Point, PointRef >::nearestPoint(), face::nearestPointClassify(), triangle< Point, PointRef >::ray(), and face::ray().
setMiss()
void setMiss (const bool eligible) inline
Definition at line 175 of file PointHit.H.
Referenced by tetrahedron< Point, PointRef >::containmentSphere(), triangle< Point, PointRef >::nearestPoint(), face::nearestPointClassify(), triangle< Point, PointRef >::ray(), and face::ray().
setPoint()
void setPoint (const Point & p) inline
Definition at line 181 of file PointHit.H.
Referenced by tetrahedron< Point, PointRef >::containmentSphere(), triangle< Point, PointRef >::intersection(), face::intersection(), triangle< Point, PointRef >::nearestPoint(), face::nearestPointClassify(), triangle< Point, PointRef >::ray(), face::ray(), and faceCollapser::setRefinement().
setDistance()
void setDistance (const scalar d) inline
Definition at line 186 of file PointHit.H.
Referenced by tetrahedron< Point, PointRef >::containmentSphere(), triangle< Point, PointRef >::intersection(), face::intersection(), triangle< Point, PointRef >::nearestPoint(), face::nearestPointClassify(), triangle< Point, PointRef >::ray(), face::ray(), AMIInterpolation< SourcePatch, TargetPatch >::srcPointFace(), and AMIInterpolation< SourcePatch, TargetPatch >::tgtPointFace().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & os, const PointHit< Point > & b) friend
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/objectHit/PointHit.H