OpenFOAM: tetrahedron< Point, PointRef > Class Template Reference
tetrahedron< Point, PointRef > Class Template Reference
A tetrahedron primitive.
Classes
class dummyOp
Dummy.
class storeOp
Store resulting tets.
class sumVolOp
Sum resulting volumes.
Public Types
enum { nVertices = 4, nEdges = 6 }
typedef FixedList< tetPoints, 200 > tetIntersectionList
Storage type for tets originating from intersecting tets.
Public Member Functions
tetrahedron (const Point &a, const Point &b, const Point &c, const Point &d)
Construct from points.
tetrahedron (const UList< Point > &, const FixedList< label, 4 > &indices)
Construct from four points in the list of points.
tetrahedron (Istream &)
Construct from Istream.
const Point & a () const
Return vertices.
const Point & b () const
const Point & c () const
const Point & d () const
triPointRef tri (const label facei) const
Return i-th face.
vector Sa () const
Return face normal.
vector Sb () const
vector Sc () const
vector Sd () const
Point centre () const
Return centre (centroid)
scalar mag () const
Return volume.
Point circumCentre () const
Return circum-centre.
scalar circumRadius () const
Return circum-radius.
scalar quality () const
Return quality: Ratio of tetrahedron and circum-sphere.
Point randomPoint (Random &rndGen) const
Return a random point in the tetrahedron from a.
Point randomPoint (cachedRandom &rndGen) const
Return a random point in the tetrahedron from a.
scalar barycentric (const point &pt, List< scalar > &bary) const
Calculate the barycentric coordinates of the given.
pointHit nearestPoint (const point &p) const
Return nearest point to p on tetrahedron. Is p itself.
bool inside (const point &pt) const
Return true if point is inside tetrahedron.
template<class AboveTetOp , class BelowTetOp >
void sliceWithPlane (const plane &pl, AboveTetOp &aboveOp, BelowTetOp &belowOp) const
Decompose tet into tets above and below plane.
void tetOverlap (const tetrahedron< Point, PointRef > &tetB, tetIntersectionList &insideTets, label &nInside, tetIntersectionList &outsideTets, label &nOutside) const
Decompose tet into tets inside and outside other tet.
pointHit containmentSphere (const scalar tol) const
Return (min)containment sphere, i.e. the smallest sphere with.
void gradNiSquared (scalarField &buffer) const
Fill buffer with shape function products.
void gradNiDotGradNj (scalarField &buffer) const
void gradNiGradNi (tensorField &buffer) const
void gradNiGradNj (tensorField &buffer) const
Friends
Istream & operator>> (Istream &, tetrahedron &)
Ostream & operator (Ostream &, const tetrahedron &)
Detailed Description
template<class Point, class PointRef>
class Foam::tetrahedron< Point, PointRef >
A tetrahedron primitive.
Ordering of edges needs to be the same for a tetrahedron class, a tetrahedron cell shape model and a tetCell.
Source files
tetrahedron.H
tetrahedronI.H
tetrahedron.C
Definition at line 62 of file tetrahedron.H.
Member Typedef Documentation
tetIntersectionList
typedef FixedList<tetPoints, 200> tetIntersectionList
Storage type for tets originating from intersecting tets.
(can possibly be smaller than 200)
Definition at line 93 of file tetrahedron.H.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
nVertices
nEdges
Definition at line 164 of file tetrahedron.H.
Constructor & Destructor Documentation
tetrahedron() [1/3]
tetrahedron (const Point & a, const Point & b, const Point & c, const Point & d) inline
Construct from points.
Definition at line 35 of file tetrahedronI.H.
tetrahedron() [2/3]
tetrahedron (const UList< Point > & points, const FixedList< label, 4 > & indices) inline
Construct from four points in the list of points.
Definition at line 51 of file tetrahedronI.H.
tetrahedron() [3/3]
tetrahedron (Istream & is) inline
Construct from Istream.
Definition at line 64 of file tetrahedronI.H.
Member Function Documentation
a()
const Point & a () const inline
Return vertices.
Definition at line 73 of file tetrahedronI.H.
Referenced by particle< Type >::movingTetLambda().
b()
const Point & b () const inline
Definition at line 80 of file tetrahedronI.H.
Referenced by particle< Type >::movingTetLambda().
c()
const Point & c () const inline
Definition at line 87 of file tetrahedronI.H.
Referenced by particle< Type >::movingTetLambda().
d()
const Point & d () const inline
Definition at line 94 of file tetrahedronI.H.
References tetrahedron< Point, PointRef >::tri().
Referenced by particle< Type >::movingTetLambda(), and tetrahedron< Point, PointRef >::storeOp::operator()().
tri()
Foam::triPointRef tri (const label facei) const inline
Return i-th face.
Definition at line 102 of file tetrahedronI.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by tetrahedron< Point, PointRef >::d().
Sa()
Foam::vector Sa () const inline
Return face normal.
Definition at line 136 of file tetrahedronI.H.
Referenced by particle< Type >::trackToFace().
Sb()
Foam::vector Sb () const inline
Definition at line 143 of file tetrahedronI.H.
Referenced by particle< Type >::trackToFace().
Sc()
Foam::vector Sc () const inline
Definition at line 150 of file tetrahedronI.H.
Referenced by particle< Type >::trackToFace().
Sd()
Foam::vector Sd () const inline
Definition at line 157 of file tetrahedronI.H.
Referenced by particle< Type >::trackToFace().
centre()
Point centre () const inline
Return centre (centroid)
Definition at line 164 of file tetrahedronI.H.
Referenced by particle< Type >::findTris(), particle< Type >::hitWallFaces(), and particle< Type >::trackToFace().
mag()
Foam::scalar mag () const inline
Return volume.
Definition at line 171 of file tetrahedronI.H.
Referenced by Dual< Type >::Dual(), Moment< Type >::Moment(), tetOverlapVolume::tetOverlapVolume(), and AveragingMethod< Foam::Vector >::write().
circumCentre()
Point circumCentre () const inline
Return circum-centre.
Definition at line 178 of file tetrahedronI.H.
References Foam::constant::physicoChemical::b, Foam::constant::universal::c, lambda(), Foam::mag(), Foam::magSqr(), and Foam::constant::physicoChemical::mu.
circumRadius()
Foam::scalar circumRadius () const inline
Return circum-radius.
Definition at line 205 of file tetrahedronI.H.
References Foam::constant::physicoChemical::b, Foam::constant::universal::c, lambda(), Foam::mag(), Foam::magSqr(), and Foam::constant::physicoChemical::mu.
quality()
Foam::scalar quality () const inline
Return quality: Ratio of tetrahedron and circum-sphere.
volume, scaled so that a regular tetrahedron has a quality of 1
Definition at line 231 of file tetrahedronI.H.
References Foam::mag(), Foam::min(), Foam::pow3(), tetrahedron< Point, PointRef >::randomPoint(), and Foam::sqrt().
Referenced by polyMeshTetDecomposition::findBasePoint(), and polyMeshTetDecomposition::findSharedBasePoint().
randomPoint() [1/2]
Point randomPoint (Random & rndGen) const inline
Return a random point in the tetrahedron from a.
uniform distribution
Definition at line 245 of file tetrahedronI.H.
References s(), and Random::scalar01().
Referenced by tetrahedron< Point, PointRef >::quality().
randomPoint() [2/2]
Point randomPoint (cachedRandom & rndGen) const inline
Return a random point in the tetrahedron from a.
uniform distribution
Definition at line 281 of file tetrahedronI.H.
References tetrahedron< Point, PointRef >::barycentric(), s(), and cachedRandom::sample01().
barycentric()
Foam::scalar barycentric (const point & pt, List< scalar > & bary) const inline
Calculate the barycentric coordinates of the given.
point, in the same order as a, b, c, d. Returns the determinant of the solution.
Definition at line 317 of file tetrahedronI.H.
References Foam::det(), Foam::inv(), Foam::mag(), tetrahedron< Point, PointRef >::nearestPoint(), List< T >::setSize(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by cellPointWeight::findTetrahedron(), interpolationCellPoint< Foam::Vector >::interpolate(), tetrahedron< Point, PointRef >::randomPoint(), and Dual< Type >::~Dual().
nearestPoint()
Foam::pointHit nearestPoint (const point & p) const inline
Return nearest point to p on tetrahedron. Is p itself.
if inside.
Definition at line 362 of file tetrahedronI.H.
References PointHit< Point >::distance(), p, and PointHit< Point >::rawPoint().
Referenced by tetrahedron< Point, PointRef >::barycentric(), and cellPointWeight::findTetrahedron().
inside()
bool inside (const point & pt) const inline
Return true if point is inside tetrahedron.
Definition at line 456 of file tetrahedronI.H.
References Foam::mag(), n, and Foam::Zero.
Referenced by polyMeshTetDecomposition::findTet().
sliceWithPlane()
void sliceWithPlane (const plane & pl, AboveTetOp & aboveOp, BelowTetOp & belowOp) const inline
Decompose tet into tets above and below plane.
Definition at line 985 of file tetrahedronI.H.
References token::BEGIN_LIST, token::END_LIST, Foam::nl, Istream::readBegin(), and token::SPACE.
Referenced by tetrahedron< Point, PointRef >::storeOp::operator()(), and tetOverlapVolume::tetOverlapVolume().
tetOverlap()
void tetOverlap (const tetrahedron< Point, PointRef > & tetB, tetIntersectionList & insideTets, label & nInside, tetIntersectionList & outsideTets, label & nOutside) const inline
Decompose tet into tets inside and outside other tet.
Definition at line 34 of file tetrahedron.C.
References tetrahedron< Point, PointRef >::containmentSphere().
containmentSphere()
Foam::pointHit containmentSphere (const scalar tol) const
Return (min)containment sphere, i.e. the smallest sphere with.
all points inside. Returns pointHit with:
hit : if sphere is equal to circumsphere (biggest sphere)
point : centre of sphere
distance : radius of sphere
eligiblemiss: false Tol (small compared to 1, e.g. 1e-9) is used to determine whether point is inside: mag(pt - ctr) < (1+tol)*radius.
Definition at line 124 of file tetrahedron.C.
References tetrahedron< Point, PointRef >::gradNiSquared(), Foam::magSqr(), PointHit< Point >::rawPoint(), PointHit< Point >::setDistance(), PointHit< Point >::setHit(), PointHit< Point >::setMiss(), PointHit< Point >::setPoint(), and Foam::sqrt().
Referenced by tetrahedron< Point, PointRef >::tetOverlap().
gradNiSquared()
void gradNiSquared (scalarField & buffer) const
Fill buffer with shape function products.
Definition at line 336 of file tetrahedron.C.
References tetrahedron< Point, PointRef >::gradNiDotGradNj(), Foam::mag(), and Foam::magSqr().
Referenced by tetrahedron< Point, PointRef >::containmentSphere().
gradNiDotGradNj()
void gradNiDotGradNj (scalarField & buffer) const
Definition at line 357 of file tetrahedron.C.
References tetrahedron< Point, PointRef >::gradNiGradNi(), and Foam::mag().
Referenced by tetrahedron< Point, PointRef >::gradNiSquared().
gradNiGradNi()
void gradNiGradNi (tensorField & buffer) const
Definition at line 387 of file tetrahedron.C.
References tetrahedron< Point, PointRef >::gradNiGradNj(), Foam::mag(), and Foam::sqr().
Referenced by tetrahedron< Point, PointRef >::gradNiDotGradNj().
gradNiGradNj()
void gradNiGradNj (tensorField & buffer) const
Definition at line 405 of file tetrahedron.C.
References Foam::mag().
Referenced by tetrahedron< Point, PointRef >::gradNiGradNi().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , tetrahedron< Point, PointRef > &) friend
operator
Ostream& operator (Ostream & , const tetrahedron< Point, PointRef > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedron.H
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedron.C
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedronI.H