OpenFOAM: tetPoints Class Reference
tetPoints Class Reference
Tet storage. Null constructable (unfortunately tetrahedron<point, point> is not)
Public Member Functions
tetPoints ()
Construct null.
tetPoints (const point &a, const point &b, const point &c, const point &d)
Construct from four points.
tetPointRef tet () const
Return the tetrahedron.
treeBoundBox bounds () const
Calculate the bounding box.
Public Member Functions inherited from FixedList< point, 4 >
FixedList ()
Null constructor.
FixedList (const point &)
Construct from value.
FixedList (const point v[Size])
Construct from C-array.
FixedList (InputIterator first, InputIterator last)
Construct given start and end iterators.
FixedList (std::initializer_list< point >)
Construct from an initializer list.
FixedList (const UList< point > &)
Construct from UList.
FixedList (const SLList< point > &)
Construct from SLList.
FixedList (const FixedList< point, Size > &)
Copy constructor.
FixedList (Istream &)
Construct from Istream.
autoPtr< FixedList< point, Size > > clone () const
Clone.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
const point * cdata () const
Return a const pointer to the first data element,.
point * data ()
Return a pointer to the first data element,.
point & first ()
Return the first element of the list.
const point & first () const
Return first element of the list.
point & last ()
Return the last element of the list.
const point & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void resize (const label)
Dummy resize function.
void setSize (const label)
Dummy setSize function.
void transfer (const FixedList< point, Size > &)
Copy (not transfer) the argument contents.
void writeEntry (Ostream &) const
Write the FixedList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the FixedList as a dictionary entry with keyword.
point & operator[] (const label)
Return element of FixedList.
const point & operator[] (const label) const
Return element of constant FixedList.
void operator= (const point v[Size])
Assignment to array operator. Takes linear time.
void operator= (const UList< point > &)
Assignment to UList operator. Takes linear time.
void operator= (const SLList< point > &)
Assignment to SLList operator. Takes linear time.
void operator= (std::initializer_list< point >)
Assignment to an initializer list. Takes linear time.
void operator= (const point &)
Assignment of all entries to the given value.
iterator begin ()
Return an iterator to begin traversing the FixedList.
const_iterator begin () const
Return const_iterator to begin traversing the constant FixedList.
iterator end ()
Return an iterator to end traversing the FixedList.
const_iterator end () const
Return const_iterator to end traversing the constant FixedList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant FixedList.
const_iterator cend () const
Return const_iterator to end traversing the constant FixedList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the FixedList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the FixedList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing FixedList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing FixedList.
label size () const
Return the number of elements in the FixedList.
label max_size () const
Return size of the largest possible FixedList.
bool empty () const
Return true if the FixedList is empty (ie, size() is zero)
void swap (FixedList< point, Size > &)
Swap two FixedLists of the same type in constant time.
bool operator== (const FixedList< point, Size > &) const
Equality operation on FixedLists of the same type.
bool operator!= (const FixedList< point, Size > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const FixedList< point, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator> (const FixedList< point, Size > &) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator<= (const FixedList< point, Size > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const FixedList< point, Size > &) const
Return true if !(a < b). Takes linear time.
Additional Inherited Members
Public Types inherited from FixedList< point, 4 >
typedef point value_type
Type of values the FixedList contains.
typedef point & reference
Type that can be used for storing into.
typedef const point & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a FixedList.
typedef point * iterator
Random access iterator for traversing FixedList.
typedef const point * const_iterator
Random access iterator for traversing FixedList.
typedef point * reverse_iterator
Reverse iterator for reverse traversal of FixedList.
typedef const point * const_reverse_iterator
Reverse iterator for reverse traversal of constant FixedList.
Static Public Member Functions inherited from FixedList< point, 4 >
static const FixedList< point, Size > & null ()
Return a null FixedList.
Detailed Description
Tet storage. Null constructable (unfortunately tetrahedron<point, point> is not)
Source files
tetPoints.H
Definition at line 50 of file tetPoints.H.
Constructor & Destructor Documentation
tetPoints() [1/2]
tetPoints () inline
Construct null.
Definition at line 59 of file tetPoints.H.
tetPoints() [2/2]
tetPoints (const point & a, const point & b, const point & c, const point & d) inline
Construct from four points.
Definition at line 64 of file tetPoints.H.
References Foam::constant::physicoChemical::b, Foam::constant::universal::c, and FixedList< point, 4 >::operator[]().
Member Function Documentation
tet()
tetPointRef tet () const inline
Return the tetrahedron.
Definition at line 80 of file tetPoints.H.
Referenced by tetOverlapVolume::tetOverlapVolume().
bounds()
treeBoundBox bounds () const inline
Calculate the bounding box.
Definition at line 92 of file tetPoints.H.
References boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), FixedList< point, 4 >::operator[](), and FixedList< point, 4 >::size().
Referenced by tetOverlapVolume::cellCellOverlapMinDecomp(), and tetOverlapVolume::cellCellOverlapVolumeMinDecomp().
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetPoints.H