OpenFOAM: DiagTensor< Cmpt > Class Template Reference
DiagTensor< Cmpt > Class Template Reference
Templated 3D DiagTensor derived from VectorSpace.
Public Types
enum components { XX, YY, ZZ }
Component labeling enumeration.
typedef DiagTensor< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >
typedef VectorSpace< DiagTensor< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
Public Member Functions
DiagTensor ()
Construct null.
DiagTensor (const Foam::zero)
Construct initialized to zero.
template<class Cmpt2 >
DiagTensor (const VectorSpace< DiagTensor< Cmpt2 >, Cmpt2, 3 > &)
Construct given VectorSpace.
DiagTensor (const Cmpt &txx, const Cmpt &tyy, const Cmpt &tzz)
Construct given three components.
DiagTensor (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & yy () const
const Cmpt & zz () const
Cmpt & xx ()
Cmpt & yy ()
Cmpt & zz ()
Public Member Functions inherited from VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< DiagTensor< Cmpt >, Cmpt, Ncmpts > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const ConstBlock< SubVector, BStart > block () const
const VectorSpace< DiagTensor< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< DiagTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< DiagTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< DiagTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const direction rank = 2
Rank of DiagTensor is 2.
Static Public Attributes inherited from VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >
static const direction dim
Dimensionality of space.
static const direction nComponents
Number of components in this vector space.
static const direction mRows
static const direction nCols
static const char *const typeName
static const char *const componentNames []
static const DiagTensor< Cmpt > zero
static const DiagTensor< Cmpt > one
static const DiagTensor< Cmpt > max
static const DiagTensor< Cmpt > min
static const DiagTensor< Cmpt > rootMax
static const DiagTensor< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static DiagTensor< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< DiagTensor< Cmpt >, Cmpt, 3 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::DiagTensor< Cmpt >
Templated 3D DiagTensor derived from VectorSpace.
Adding construction from 3 components, element access using xx(), yy() and zz() member functions and the inner-product (dot-product) and outer-product operators.
Source files
DiagTensor.H
DiagTensorI.H
Definition at line 53 of file DiagTensor.H.
Member Typedef Documentation
labelType
typedef DiagTensor<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 61 of file DiagTensor.H.
Member Enumeration Documentation
components
enum components
Component labeling enumeration.
Enumerator
XX
YY
ZZ
Definition at line 71 of file DiagTensor.H.
Constructor & Destructor Documentation
DiagTensor() [1/5]
DiagTensor () inline
Construct null.
Definition at line 32 of file DiagTensorI.H.
Referenced by DiagTensor< scalar >::DiagTensor().
DiagTensor() [2/5]
DiagTensor (const Foam::zero) inline
Construct initialized to zero.
Definition at line 37 of file DiagTensorI.H.
DiagTensor() [3/5]
DiagTensor (const VectorSpace< DiagTensor< Cmpt2 >, Cmpt2, 3 > & vs) inline
Construct given VectorSpace.
Definition at line 46 of file DiagTensorI.H.
DiagTensor() [4/5]
DiagTensor (const Cmpt & txx, const Cmpt & tyy, const Cmpt & tzz) inline
Construct given three components.
Definition at line 56 of file DiagTensorI.H.
DiagTensor() [5/5]
DiagTensor (Istream & is) inline
Construct from Istream.
Definition at line 69 of file DiagTensorI.H.
Member Function Documentation
xx() [1/2]
const Cmpt & xx () const inline
Definition at line 78 of file DiagTensorI.H.
Referenced by Foam::det(), Foam::inv(), molecule::constantProperties::linearMolecule(), Foam::operator &(), Foam::operator+(), Foam::operator-(), Foam::operator/(), wedgeFvPatchField< Type >::snGradTransformDiag(), and Foam::tr().
yy() [1/2]
const Cmpt & yy () const inline
Definition at line 84 of file DiagTensorI.H.
Referenced by molecule::constantProperties::constantProperties(), Foam::det(), Foam::inv(), molecule::constantProperties::linearMolecule(), Foam::operator &(), Foam::operator+(), Foam::operator-(), Foam::operator/(), wedgeFvPatchField< Type >::snGradTransformDiag(), and Foam::tr().
zz() [1/2]
const Cmpt & zz () const inline
Definition at line 90 of file DiagTensorI.H.
Referenced by molecule::constantProperties::constantProperties(), Foam::det(), Foam::inv(), Foam::operator &(), Foam::operator+(), Foam::operator-(), Foam::operator/(), molecule::constantProperties::pointMolecule(), wedgeFvPatchField< Type >::snGradTransformDiag(), and Foam::tr().
xx() [2/2]
Cmpt & xx () inline
Definition at line 97 of file DiagTensorI.H.
yy() [2/2]
Cmpt & yy () inline
Definition at line 103 of file DiagTensorI.H.
zz() [2/2]
Cmpt & zz () inline
Definition at line 109 of file DiagTensorI.H.
Member Data Documentation
rank
const direction rank = 2 static
Rank of DiagTensor is 2.
Definition at line 67 of file DiagTensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/DiagTensor/DiagTensor.H
src/OpenFOAM/primitives/DiagTensor/DiagTensorI.H