OpenFOAM: Sine< Type > Class Template Reference
Sine< Type > Class Template Reference
Templated sine function with support for an offset level.
Public Member Functions
TypeName ("sine")
Sine (const word &entryName, const dictionary &dict, const word &ext="Coeffs")
Construct from entry name and dictionary.
Sine (const Sine< Type > &se)
Copy constructor.
virtual tmp< Function1< Type > > clone () const
Construct and return a clone.
virtual ~Sine ()
Destructor.
Type value (const scalar t) const
Return value for time t.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Runtime type information.
Function1 (const word &entryName)
Construct from entry name.
Function1 (const Function1< Type > &de)
Copy constructor.
virtual ~Function1 ()
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes inherited from Function1< Type >
const word name_
Name of entry.
Detailed Description
template<class Type>
class Foam::Function1Types::Sine< Type >
Templated sine function with support for an offset level.
where
= Description Data type
= Amplitude Function1<scalar>
= Frequency [1/s] Function1<scalar>
= Type scale factor Function1<Type>
= Type offset level Function1<Type>
= Start time [s] scalar
= Time [s] scalar
Example for a scalar:
        <entryName> sine;
        <entryName>Coeffs
        {
            frequency 10;
            amplitude 0.1;
            scale     2e-6;
            level     2e-6;
        }
Example for a vector:
        <entryName> sine;
        <entryName>Coeffs
        {
            frequency 10;
            amplitude 1;
            scale     (1 0.1 0);
            level     (10 1 0);
        }
Source files
Sine.H
Sine.C
Definition at line 126 of file Sine.H.
Constructor & Destructor Documentation
Sine() [1/2]
Sine (const word & entryName, const dictionary & dict, const word & ext = "Coeffs")
Construct from entry name and dictionary.
Definition at line 44 of file Sine.C.
References Foam::read(), and dictionary::subDict().
Sine() [2/2]
Sine (const Sine< Type > & se)
Copy constructor.
Definition at line 57 of file Sine.C.
~Sine()
~Sine () virtual
Destructor.
Definition at line 71 of file Sine.C.
Referenced by Sine< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("sine")
clone()
virtual tmp<Function1<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from Function1< Type >.
Definition at line 177 of file Sine.H.
References Sine< Type >::value(), Sine< Type >::writeData(), and Sine< Type >::~Sine().
value()
Type value (const scalar t) const virtual
Return value for time t.
Reimplemented from Function1< Type >.
Definition at line 78 of file Sine.C.
References Foam::sin(), and Foam::constant::mathematical::twoPi().
Referenced by Sine< Type >::clone().
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented from Function1< Type >.
Definition at line 89 of file Sine.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), Foam::incrIndent(), Foam::indent(), Function1< Type >::name(), Foam::nl, Function1< Type >::writeData(), and Ostream::writeKeyword().
Referenced by Sine< Type >::clone().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Sine/Sine.H
src/OpenFOAM/primitives/functions/Function1/Sine/Sine.C