OpenFOAM: globalIndexAndTransform::less Class Reference
globalIndexAndTransform::less Class Reference
Less function class used in sorting encoded transforms and indices.
Public Member Functions
less (const globalIndexAndTransform &gi)
bool operator() (const labelPair &, const labelPair &) const
Detailed Description
Less function class used in sorting encoded transforms and indices.
Minimum of:
processor
local index
transform
Definition at line 73 of file globalIndexAndTransform.H.
Constructor & Destructor Documentation
less()
less (const globalIndexAndTransform & gi) inline
Definition at line 79 of file globalIndexAndTransform.H.
References globalIndexAndTransform::addToTransformIndex(), globalIndexAndTransform::ClassName(), globalIndexAndTransform::decodeTransformIndex(), globalIndexAndTransform::encode(), globalIndexAndTransform::encodeTransformIndex(), globalIndexAndTransform::index(), globalIndexAndTransform::mergeTransformIndex(), mesh, globalIndexAndTransform::minimumTransformIndex(), globalIndexAndTransform::nIndependentTransforms(), globalIndexAndTransform::nullTransformIndex(), globalIndexAndTransform::less::operator()(), patchi, globalIndexAndTransform::patchTransformSign(), globalIndexAndTransform::processor(), globalIndexAndTransform::subtractTransformIndex(), globalIndexAndTransform::transform(), globalIndexAndTransform::transformIndex(), globalIndexAndTransform::transformIndicesForPatches(), globalIndexAndTransform::transformPatches(), globalIndexAndTransform::transformPermutations(), and globalIndexAndTransform::transforms().
Member Function Documentation
operator()()
bool operator() (const labelPair & a, const labelPair & b) const inline
Definition at line 31 of file globalIndexAndTransformI.H.
References Foam::constant::physicoChemical::b, and globalIndexAndTransform::encodeTransformIndex().
Referenced by globalIndexAndTransform::less::less().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/globalIndexAndTransform/globalIndexAndTransform.H
src/OpenFOAM/primitives/globalIndexAndTransform/globalIndexAndTransformI.H