OpenFOAM: SHA1 Class Reference
SHA1 Class Reference
Functions to compute SHA1 message digest according to the NIST specification FIPS-180-1.
Public Member Functions
SHA1 ()
Construct null.
SHA1 (const std::string &)
Construct null and append initial std::string.
SHA1 (const char *)
Construct null and append initial string.
void clear ()
Reset the hashed data before appending more.
SHA1 & append (const char *data, size_t len)
Append data for processing.
SHA1 & append (const std::string &)
Append string for processing.
SHA1 & append (const char *str)
Append string for processing.
bool finalize ()
Finalized the calculations (normally not needed directly).
SHA1Digest digest () const
Calculate current digest from appended data.
bool operator== (const SHA1 &) const
Equality operator, compares digests.
bool operator== (const SHA1Digest &) const
Compare digest.
bool operator== (const std::string &hexdigits) const
Compare digest to (40-byte) text representation (eg, from sha1sum)
bool operator== (const char *hexdigits) const
Compare digest to (40-byte) text representation (eg, from sha1sum)
bool operator!= (const SHA1 &) const
Inequality operator, compares digests.
bool operator!= (const SHA1Digest &) const
Inequality operator, compare digest.
bool operator!= (const std::string &hexdigits) const
Inequality operator, compares digests.
bool operator!= (const char *hexdigits) const
Inequality operator, compare digest.
operator SHA1Digest () const
Convert to a SHA1Digest,.
Friends
Ostream & operator<< (Ostream &, const SHA1 &)
Output the digest.
Detailed Description
Functions to compute SHA1 message digest according to the NIST specification FIPS-180-1.
Adapted from the gnulib implementation.
See also
Foam::SHA1Digest
Source files
SHA1.H
SHA1I.H
SHA1.C
Definition at line 68 of file SHA1.H.
Constructor & Destructor Documentation
SHA1() [1/3]
SHA1 () inline
Construct null.
Definition at line 31 of file SHA1I.H.
References SHA1::clear().
SHA1() [2/3]
SHA1 (const std::string & str) inline explicit
Construct null and append initial std::string.
Definition at line 37 of file SHA1I.H.
References SHA1::append(), and SHA1::clear().
SHA1() [3/3]
SHA1 (const char * str) inline explicit
Construct null and append initial string.
Definition at line 44 of file SHA1I.H.
References SHA1::append(), and SHA1::clear().
Member Function Documentation
clear()
void clear ()
Reset the hashed data before appending more.
Definition at line 339 of file SHA1.C.
Referenced by SHA1::SHA1().
append() [1/3]
Foam::SHA1 & append (const char * data, size_t len) inline
Append data for processing.
Definition at line 53 of file SHA1I.H.
Referenced by SHA1::SHA1(), and sha1streambuf::xsputn().
append() [2/3]
Foam::SHA1 & append (const std::string & str) inline
Append string for processing.
Definition at line 60 of file SHA1I.H.
append() [3/3]
Foam::SHA1 & append (const char * str) inline
Append string for processing.
Definition at line 67 of file SHA1I.H.
finalize()
bool finalize ()
Finalized the calculations (normally not needed directly).
Returns false if no bytes were passed for processing
Definition at line 354 of file SHA1.C.
Referenced by SHA1::digest().
digest()
Foam::SHA1Digest digest () const
Calculate current digest from appended data.
Definition at line 393 of file SHA1.C.
References SHA1::finalize().
Referenced by SHA1::operator!=(), Foam::operator<<(), and SHA1::operator==().
operator==() [1/4]
bool operator== (const SHA1 & rhs) const inline
Equality operator, compares digests.
Definition at line 79 of file SHA1I.H.
References SHA1::digest().
Referenced by SHA1::operator!=().
operator==() [2/4]
bool operator== (const SHA1Digest & rhs) const inline
Compare digest.
Definition at line 85 of file SHA1I.H.
References SHA1::digest().
operator==() [3/4]
bool operator== (const std::string & hexdigits) const inline
Compare digest to (40-byte) text representation (eg, from sha1sum)
An empty string is equivalent to "0000000000000000000000000000000000000000"
Definition at line 91 of file SHA1I.H.
References SHA1::digest().
operator==() [4/4]
bool operator== (const char * hexdigits) const inline
Compare digest to (40-byte) text representation (eg, from sha1sum)
A null or empty string is equivalent to "0000000000000000000000000000000000000000"
Definition at line 97 of file SHA1I.H.
References SHA1::digest().
operator!=() [1/4]
bool operator!= (const SHA1 & rhs) const inline
Inequality operator, compares digests.
Definition at line 103 of file SHA1I.H.
References SHA1::operator==().
operator!=() [2/4]
bool operator!= (const SHA1Digest & rhs) const inline
Inequality operator, compare digest.
Definition at line 109 of file SHA1I.H.
References SHA1::operator==().
operator!=() [3/4]
bool operator!= (const std::string & hexdigits) const inline
Inequality operator, compares digests.
Definition at line 115 of file SHA1I.H.
References SHA1::operator==().
operator!=() [4/4]
bool operator!= (const char * hexdigits) const inline
Inequality operator, compare digest.
Definition at line 121 of file SHA1I.H.
References SHA1::digest(), and SHA1::operator==().
operator SHA1Digest()
operator SHA1Digest () const inline
Convert to a SHA1Digest,.
calculate current digest from appended data
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const SHA1 &) friend
Output the digest.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/hashes/SHA1/SHA1.H
src/OpenFOAM/primitives/hashes/SHA1/SHA1.C
src/OpenFOAM/primitives/hashes/SHA1/SHA1I.H