OpenFOAM: TableBase< Type > Class Template Reference
TableBase< Type > Class Template Reference
Base class for table with bounds handling, interpolation and integration.
Public Types
enum boundsHandling { ERROR, WARN, CLAMP, REPEAT }
Enumeration for handling out-of-bound values.
Public Member Functions
TableBase (const word &name, const dictionary &dict)
Construct from dictionary - note table is not populated.
TableBase (const TableBase< Type > &tbl)
Copy constructor. Note: steals interpolator, tableSamples.
virtual ~TableBase ()
Destructor.
word boundsHandlingToWord (const boundsHandling &bound) const
Return the out-of-bounds handling as a word.
boundsHandling wordToBoundsHandling (const word &bound) const
Return the out-of-bounds handling as an enumeration.
boundsHandling outOfBounds (const boundsHandling &bound)
Set the out-of-bounds handling from enum, return previous setting.
void check () const
Check the table for size and consistency.
bool checkMinBounds (const scalar x, scalar &xDash) const
Check minimum table bounds.
bool checkMaxBounds (const scalar x, scalar &xDash) const
Check maximum table bounds.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return Table value.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual tmp< scalarField > x () const
Return the reference values.
virtual tmp< Field< Type > > y () const
Return the dependent values.
virtual void writeData (Ostream &os) const
Write all table data in dictionary format.
virtual void writeEntries (Ostream &os) const
Write keywords only in dictionary format. Used for non-inline.
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Runtime type information.
Function1 (const word &entryName)
Construct from entry name.
Function1 (const Function1< Type > &de)
Copy constructor.
virtual tmp< Function1< Type > > clone () const
Construct and return a clone.
virtual ~Function1 ()
Destructor.
const word & name () const
Return the name of the entry.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Protected Member Functions
const interpolationWeights & interpolator () const
Return (demand driven) interpolator.
void operator= (const TableBase< Type > &)
Disallow default bitwise assignment.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes
const word name_
Table name.
const boundsHandling boundsHandling_
Enumeration for handling out-of-bound values.
const word interpolationScheme_
Interpolation type.
List< Tuple2< scalar, Type > > table_
Table data.
autoPtr< scalarField > tableSamplesPtr_
Extracted values.
autoPtr< interpolationWeights > interpolatorPtr_
Interpolator method.
labelList currentIndices_
Cached indices and weights.
scalarField currentWeights_
Protected Attributes inherited from Function1< Type >
const word name_
Name of entry.
Additional Inherited Members
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Detailed Description
template<class Type>
class Foam::Function1Types::TableBase< Type >
Base class for table with bounds handling, interpolation and integration.
Source files
TableBase.H
TableBase.C
Definition at line 55 of file TableBase.H.
Member Enumeration Documentation
boundsHandling
enum boundsHandling
Enumeration for handling out-of-bound values.
Enumerator
ERROR
Exit with a FatalError.
WARN
Issue warning and clamp value (default)
CLAMP
Clamp value to the start/end value.
REPEAT
Treat as a repeating list.
Definition at line 64 of file TableBase.H.
Constructor & Destructor Documentation
TableBase() [1/2]
TableBase (const word & name, const dictionary & dict)
Construct from dictionary - note table is not populated.
Definition at line 60 of file TableBase.C.
Referenced by TableBase< Type >::interpolator().
TableBase() [2/2]
TableBase (const TableBase< Type > & tbl)
Copy constructor. Note: steals interpolator, tableSamples.
Definition at line 83 of file TableBase.C.
~TableBase()
~TableBase () virtual
Destructor.
Definition at line 98 of file TableBase.C.
References TableBase< Type >::boundsHandlingToWord().
Member Function Documentation
interpolator()
const Foam::interpolationWeights & interpolator () const protected
Return (demand driven) interpolator.
Definition at line 34 of file TableBase.C.
References UList< T >::first(), forAll, Foam::New(), scalarField(), and TableBase< Type >::TableBase().
Referenced by TableBase< Type >::integrate(), and TableBase< Type >::value().
operator=()
void operator= (const TableBase< Type > &) protected
Disallow default bitwise assignment.
boundsHandlingToWord()
Foam::word boundsHandlingToWord (const boundsHandling & bound) const
Return the out-of-bounds handling as a word.
Definition at line 106 of file TableBase.C.
References TableBase< Type >::CLAMP, TableBase< Type >::ERROR, TableBase< Type >::REPEAT, TableBase< Type >::WARN, and TableBase< Type >::wordToBoundsHandling().
Referenced by TableBase< Type >::writeEntries(), and TableBase< Type >::~TableBase().
wordToBoundsHandling()
Foam::Function1Types::TableBase< Type >::boundsHandling wordToBoundsHandling (const word & bound) const
Return the out-of-bounds handling as an enumeration.
Definition at line 143 of file TableBase.C.
References TableBase< Type >::CLAMP, Foam::endl(), TableBase< Type >::ERROR, TableBase< Type >::outOfBounds(), TableBase< Type >::REPEAT, TableBase< Type >::WARN, and WarningInFunction.
Referenced by TableBase< Type >::boundsHandlingToWord().
outOfBounds()
Foam::Function1Types::TableBase< Type >::boundsHandling outOfBounds (const boundsHandling & bound)
Set the out-of-bounds handling from enum, return previous setting.
Definition at line 177 of file TableBase.C.
References Foam::bound(), and TableBase< Type >::boundsHandling_.
Referenced by TableBase< Type >::wordToBoundsHandling().
check()
void check () const
Check the table for size and consistency.
Definition at line 189 of file TableBase.C.
References TableBase< Type >::checkMinBounds(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), n, TableBase< Type >::name_, Foam::nl, List< T >::size(), and TableBase< Type >::table_.
checkMinBounds()
bool checkMinBounds (const scalar x, scalar & xDash) const
Check minimum table bounds.
Definition at line 219 of file TableBase.C.
References TableBase< Type >::boundsHandling_, TableBase< Type >::checkMaxBounds(), TableBase< Type >::CLAMP, Foam::endl(), TableBase< Type >::ERROR, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), UList< T >::last(), Foam::nl, TableBase< Type >::REPEAT, TableBase< Type >::table_, TableBase< Type >::WARN, WarningInFunction, and TableBase< Type >::x().
Referenced by TableBase< Type >::check(), and TableBase< Type >::value().
checkMaxBounds()
bool checkMaxBounds (const scalar x, scalar & xDash) const
Check maximum table bounds.
Definition at line 269 of file TableBase.C.
References TableBase< Type >::boundsHandling_, TableBase< Type >::CLAMP, Foam::endl(), TableBase< Type >::ERROR, Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::first(), UList< T >::last(), Foam::nl, TableBase< Type >::REPEAT, TableBase< Type >::table_, TableBase< Type >::WARN, WarningInFunction, and TableBase< Type >::x().
Referenced by TableBase< Type >::checkMinBounds(), and TableBase< Type >::value().
convertTimeBase()
void convertTimeBase (const Time & t) virtual
Convert time.
Reimplemented from Function1< Type >.
Definition at line 318 of file TableBase.C.
References UList< T >::first(), forAll, TableBase< Type >::interpolatorPtr_, TableBase< Type >::table_, TableBase< Type >::tableSamplesPtr_, TimeState::userTimeToTime(), and TableBase< Type >::value().
value()
Type value (const scalar x) const virtual
Return Table value.
Reimplemented from Function1< Type >.
Definition at line 332 of file TableBase.C.
References TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), TableBase< Type >::currentIndices_, TableBase< Type >::currentWeights_, TableBase< Type >::integrate(), TableBase< Type >::interpolator(), UList< T >::last(), List< T >::size(), TableBase< Type >::table_, interpolationWeights::valueWeights(), and TableBase< Type >::x().
Referenced by TableBase< Type >::convertTimeBase(), and Function1< Foam::Vector >::value().
integrate()
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Reimplemented from Function1< Type >.
Definition at line 361 of file TableBase.C.
References TableBase< Type >::currentIndices_, TableBase< Type >::currentWeights_, interpolationWeights::integrationWeights(), TableBase< Type >::interpolator(), List< T >::size(), Foam::sum(), and TableBase< Type >::table_.
Referenced by Function1< Foam::Vector >::integrate(), and TableBase< Type >::value().
x()
Foam::tmp< Foam::scalarField > x () const virtual
Return the reference values.
Definition at line 380 of file TableBase.C.
References UList< T >::first(), fld(), forAll, List< T >::size(), and TableBase< Type >::table_.
Referenced by TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), and TableBase< Type >::value().
y()
Foam::tmp< Foam::Field< Type > > y () const virtual
Return the dependent values.
Definition at line 395 of file TableBase.C.
References fld(), forAll, tmp< T >::ref(), List< T >::size(), TableBase< Type >::table_, and Foam::Zero.
writeData()
void writeData (Ostream & os) const virtual
Write all table data in dictionary format.
Reimplemented from Function1< Type >.
Reimplemented in CSV< Type >, and TableFile< Type >.
Definition at line 426 of file TableBase.C.
References token::END_STATEMENT, Foam::indent(), Foam::nl, TableBase< Type >::table_, Function1< Type >::writeData(), and TableBase< Type >::writeEntries().
writeEntries()
void writeEntries (Ostream & os) const virtual
Write keywords only in dictionary format. Used for non-inline.
table types
Definition at line 410 of file TableBase.C.
References TableBase< Type >::boundsHandling_, TableBase< Type >::boundsHandlingToWord(), TableBase< Type >::CLAMP, token::END_STATEMENT, TableBase< Type >::interpolationScheme_, Foam::nl, and Ostream::writeKeyword().
Referenced by TableFile< Type >::writeData(), CSV< Type >::writeData(), and TableBase< Type >::writeData().
Member Data Documentation
name_
const word name_ protected
Table name.
Definition at line 78 of file TableBase.H.
Referenced by TableBase< Type >::check(), Function1< Foam::Vector >::name(), and Function1< Foam::Vector >::writeData().
boundsHandling_
const boundsHandling boundsHandling_ protected
Enumeration for handling out-of-bound values.
Definition at line 81 of file TableBase.H.
Referenced by TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), TableBase< Type >::outOfBounds(), and TableBase< Type >::writeEntries().
interpolationScheme_
const word interpolationScheme_ protected
Interpolation type.
Definition at line 84 of file TableBase.H.
Referenced by TableBase< Type >::writeEntries().
table_
List<Tuple2<scalar, Type> > table_ protected
Table data.
Definition at line 87 of file TableBase.H.
Referenced by TableBase< Type >::check(), TableBase< Type >::checkMaxBounds(), TableBase< Type >::checkMinBounds(), TableBase< Type >::convertTimeBase(), TableBase< Type >::integrate(), TableBase< Type >::value(), TableBase< Type >::writeData(), TableBase< Type >::x(), and TableBase< Type >::y().
tableSamplesPtr_
autoPtr<scalarField> tableSamplesPtr_ mutable protected
Extracted values.
Definition at line 90 of file TableBase.H.
Referenced by TableBase< Type >::convertTimeBase().
interpolatorPtr_
autoPtr<interpolationWeights> interpolatorPtr_ mutable protected
Interpolator method.
Definition at line 93 of file TableBase.H.
Referenced by TableBase< Type >::convertTimeBase().
currentIndices_
labelList currentIndices_ mutable protected
Cached indices and weights.
Definition at line 96 of file TableBase.H.
Referenced by TableBase< Type >::integrate(), and TableBase< Type >::value().
currentWeights_
scalarField currentWeights_ mutable protected
Definition at line 98 of file TableBase.H.
Referenced by TableBase< Type >::integrate(), and TableBase< Type >::value().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Table/TableBase.H
src/OpenFOAM/primitives/functions/Function1/Table/TableBase.C