OpenFOAM: Polynomial< Type > Class Template Reference
Polynomial< Type > Class Template Reference
Public Member Functions
TypeName ("polynomial")
Runtime type information.
Polynomial (const word &entryName, const dictionary &dict)
Polynomial (const word &entryName, const List< Tuple2< Type, Type >> &)
Construct from components.
Polynomial (const Polynomial &poly)
Copy constructor.
virtual tmp< Function1< Type > > clone () const
Construct and return a clone.
virtual ~Polynomial ()
Destructor.
virtual void convertTimeBase (const Time &t)
Convert time.
Type value (const scalar x) const
Return Polynomial value.
Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Runtime type information.
Function1 (const word &entryName)
Construct from entry name.
Function1 (const Function1< Type > &de)
Copy constructor.
virtual ~Function1 ()
Destructor.
const word & name () const
Return the name of the entry.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes inherited from Function1< Type >
const word name_
Name of entry.
Detailed Description
template<class Type>
class Foam::Function1Types::Polynomial< Type >
Definition at line 63 of file PolynomialEntry.H.
Constructor & Destructor Documentation
Polynomial() [1/3]
Polynomial (const word & entryName, const dictionary & dict)
Definition at line 32 of file PolynomialEntry.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, dictionary::lookup(), Foam::mag(), Foam::nl, and WarningInFunction.
Referenced by Polynomial< Type >::clone().
Polynomial() [2/3]
Polynomial (const word & entryName, const List< Tuple2< Type, Type >> & coeffs)
Construct from components.
Definition at line 76 of file PolynomialEntry.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::mag(), Foam::nl, and WarningInFunction.
Polynomial() [3/3]
Polynomial (const Polynomial< Type > & poly)
Copy constructor.
Definition at line 114 of file PolynomialEntry.C.
~Polynomial()
~Polynomial () virtual
Destructor.
Definition at line 125 of file PolynomialEntry.C.
Referenced by Polynomial< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("polynomial")
Runtime type information.
clone()
virtual tmp<Function1<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from Function1< Type >.
Definition at line 103 of file PolynomialEntry.H.
References Polynomial< Type >::convertTimeBase(), Polynomial< Type >::integrate(), Polynomial< Type >::Polynomial(), Polynomial< Type >::value(), Polynomial< Type >::writeData(), x, and Polynomial< Type >::~Polynomial().
convertTimeBase()
void convertTimeBase (const Time & t) virtual
Convert time.
Reimplemented from Function1< Type >.
Definition at line 132 of file PolynomialEntry.C.
References Foam::component(), forAll, Foam::setComponent(), TimeState::userTimeToTime(), and Polynomial< Type >::value().
Referenced by Polynomial< Type >::clone().
value()
Type value (const scalar x) const virtual
Return Polynomial value.
Reimplemented from Function1< Type >.
Definition at line 147 of file PolynomialEntry.C.
References Foam::cmptMultiply(), Foam::cmptPow(), forAll, Polynomial< Type >::integrate(), y, and Foam::Zero.
Referenced by Polynomial< Type >::clone(), and Polynomial< Type >::convertTimeBase().
integrate()
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Reimplemented from Function1< Type >.
Definition at line 165 of file PolynomialEntry.C.
References Foam::cmptDivide(), Foam::cmptMultiply(), Foam::cmptPow(), forAll, and Foam::Zero.
Referenced by Polynomial< Type >::clone(), and Polynomial< Type >::value().
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented from Function1< Type >.
Definition at line 202 of file PolynomialEntry.C.
References token::END_STATEMENT, Foam::indent(), Foam::nl, and Function1< Type >::writeData().
Referenced by Polynomial< Type >::clone().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/PolynomialEntry/PolynomialEntry.H
src/OpenFOAM/primitives/functions/Function1/PolynomialEntry/PolynomialEntry.C