OpenFOAM: Constant< Type > Class Template Reference
Constant< Type > Class Template Reference
Templated basic entry that holds a constant value.
Public Member Functions
TypeName ("constant")
Constant (const word &entryName, const Type &val)
Construct from entry name and value.
Constant (const word &entryName, const dictionary &dict)
Construct from entry name and dictionary.
Constant (const word &entryName, Istream &is)
Construct from entry name and Istream.
Constant (const Constant< Type > &cnst)
Copy constructor.
virtual tmp< Function1< Type > > clone () const
Construct and return a clone.
virtual ~Constant ()
Destructor.
Type value (const scalar) const
Return constant value.
Type integrate (const scalar x1, const scalar x2) const
Integrate between two values.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from Function1< Type >
TypeName ("Function1") declareRunTimeSelectionTable(autoPtr
Runtime type information.
Function1 (const word &entryName)
Construct from entry name.
Function1 (const Function1< Type > &de)
Copy constructor.
virtual ~Function1 ()
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict)
Selector.
Public Attributes inherited from Function1< Type >
Function1
dictionary
const word & entryName
const word const dictionary & dict
const word const dictionary entryName
const word const dictionary dict
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Attributes inherited from Function1< Type >
const word name_
Name of entry.
Detailed Description
template<class Type>
class Foam::Function1Types::Constant< Type >
Templated basic entry that holds a constant value.
Usage - for entry <entryName> having the value
:
    <entryName>    constant  <value>
Source files
Constant.H
Constant.C
Definition at line 56 of file Constant.H.
Constructor & Destructor Documentation
Constant() [1/4]
Constant (const word & entryName, const Type & val)
Construct from entry name and value.
Definition at line 32 of file Constant.C.
Referenced by Constant< Type >::Constant().
Constant() [2/4]
Constant (const word & entryName, const dictionary & dict)
Construct from entry name and dictionary.
Definition at line 44 of file Constant.C.
References Constant< Type >::Constant(), and dictionary::lookup().
Constant() [3/4]
Constant (const word & entryName, Istream & is)
Construct from entry name and Istream.
Reads the constant value without the Function1 type for backward compatibility
Definition at line 60 of file Constant.C.
Constant() [4/4]
Constant (const Constant< Type > & cnst)
Copy constructor.
Definition at line 71 of file Constant.C.
~Constant()
~Constant () virtual
Destructor.
Definition at line 81 of file Constant.C.
Referenced by Constant< Type >::clone().
Member Function Documentation
TypeName()
TypeName ("constant")
clone()
virtual tmp<Function1<Type> > clone () const inline virtual
Construct and return a clone.
Reimplemented from Function1< Type >.
Definition at line 95 of file Constant.H.
References Constant< Type >::integrate(), Constant< Type >::value(), Constant< Type >::writeData(), and Constant< Type >::~Constant().
value()
Type value (const scalar x) const virtual
Return constant value.
Reimplemented from Function1< Type >.
Definition at line 88 of file Constant.C.
References Constant< Type >::integrate().
Referenced by Constant< Type >::clone().
integrate()
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two values.
Reimplemented from Function1< Type >.
Definition at line 96 of file Constant.C.
Referenced by Constant< Type >::clone(), and Constant< Type >::value().
writeData()
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented from Function1< Type >.
Definition at line 106 of file Constant.C.
References token::END_STATEMENT, Foam::nl, token::SPACE, and Function1< Type >::writeData().
Referenced by Constant< Type >::clone().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Constant/Constant.H
src/OpenFOAM/primitives/functions/Function1/Constant/Constant.C