OpenFOAM: MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart > Class Template Reference
MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart > Class Template Reference
Sub-block type.
Public Member Functions
Block (msType &matrix)
Construct for the given matrix.
template<class Form2 >
void operator= (const MatrixSpace< Form2, Cmpt, SubTensor::mRows, SubTensor::nCols > &matrix)
Assignment to a matrix.
template<class VSForm >
void operator= (const VectorSpace< VSForm, Cmpt, SubTensor::mRows > &v)
Assignment to a column vector.
SubTensor operator() () const
Construct and return the sub-tensor corresponding to this block.
const Cmpt & operator() (const direction i, const direction j) const
(i, j) const element access operator
Cmpt & operator() (const direction i, const direction j)
(i, j) element access operator
Static Public Member Functions
static direction m ()
Return the number of rows in the block.
static direction n ()
Return the number of columns in the block.
Static Public Attributes
static const direction mRows = SubTensor::mRows
static const direction nCols = SubTensor::nCols
Detailed Description
template<class Form, class Cmpt, direction Mrows, direction Ncols>
template<class SubTensor, direction BRowStart, direction BColStart>
class Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >
Sub-block type.
Definition at line 138 of file MatrixSpace.H.
Constructor & Destructor Documentation
Block()
Block (msType & matrix) inline
Construct for the given matrix.
Definition at line 110 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::mRows, MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::mRows, MatrixSpace< Form, Cmpt, Mrows, Ncols >::nCols, and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::nCols.
Member Function Documentation
m()
static direction m () inline static
Return the number of rows in the block.
Definition at line 149 of file MatrixSpace.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::mRows.
n()
static direction n () inline static
Return the number of columns in the block.
Definition at line 155 of file MatrixSpace.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::block(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::elmt(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::MatrixSpace(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::nCols, VectorSpace< Form, Cmpt, Mrows *Ncols >::operator, MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::operator()(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator=(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::T(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::xx(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::xy(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::xz(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::yx(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::yy(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::yz(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::zx(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::zy(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::zz().
operator=() [1/2]
void operator= (const MatrixSpace< Form2, Cmpt, SubTensor::mRows, SubTensor::nCols > & matrix) inline
Assignment to a matrix.
Definition at line 493 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::mRows, MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::nCols, VectorSpace< Form, Cmpt, Mrows *Ncols >::operator, and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator()().
operator=() [2/2]
void operator= (const VectorSpace< VSForm, Cmpt, SubTensor::mRows > & v) inline
Assignment to a column vector.
Definition at line 514 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::nCols, MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator()(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::T().
operator()() [1/3]
SubTensor operator() () const inline
Construct and return the sub-tensor corresponding to this block.
Definition at line 405 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator()().
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=(), MatrixSpace< Tensor< scalar >, scalar, 3, 3 >::operator=(), and MatrixSpace< Tensor< scalar >, scalar, 3, 3 >::T().
operator()() [2/3]
const Cmpt & operator() (const direction i, const direction j) const inline
(i, j) const element access operator
Definition at line 426 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator()().
operator()() [3/3]
Cmpt & operator() (const direction i, const direction j) inline
(i, j) element access operator
Definition at line 437 of file MatrixSpaceI.H.
Member Data Documentation
mRows
const direction mRows = SubTensor::mRows static
Definition at line 145 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::Block(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=().
nCols
const direction nCols = SubTensor::nCols static
Definition at line 146 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::Block(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::operator=().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/MatrixSpace/MatrixSpace.H
src/OpenFOAM/primitives/MatrixSpace/MatrixSpaceI.H