OpenFOAM: MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart > Class Template Reference
MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart > Class Template Reference
Const sub-block type.
Public Member Functions
ConstBlock (const msType &matrix)
Construct for the given matrix.
SubTensor operator() () const
Construct and return the sub-ensor corresponding to this block.
const Cmpt & operator() (const direction i, const direction j) const
(i, j) const element access operator
Static Public Member Functions
static direction m ()
Return the number of rows in the block.
static direction n ()
Return the number of columns in the block.
Static Public Attributes
static const direction mRows = SubTensor::mRows
static const direction nCols = SubTensor::nCols
Detailed Description
template<class Form, class Cmpt, direction Mrows, direction Ncols>
template<class SubTensor, direction BRowStart, direction BColStart>
class Foam::MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >
Const sub-block type.
Definition at line 94 of file MatrixSpace.H.
Constructor & Destructor Documentation
ConstBlock()
ConstBlock (const msType & matrix) inline
Construct for the given matrix.
Definition at line 89 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::mRows, MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::mRows, MatrixSpace< Form, Cmpt, Mrows, Ncols >::nCols, and MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::nCols.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::n().
Member Function Documentation
m()
static direction m () inline static
Return the number of rows in the block.
Definition at line 105 of file MatrixSpace.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::mRows.
n()
static direction n () inline static
Return the number of columns in the block.
Definition at line 111 of file MatrixSpace.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::ConstBlock(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::nCols, VectorSpace< Form, Cmpt, Mrows *Ncols >::operator, and MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::operator()().
operator()() [1/2]
SubTensor operator() () const inline
Construct and return the sub-ensor corresponding to this block.
Definition at line 383 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator()().
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::n(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
operator()() [2/2]
const Cmpt & operator() (const direction i, const direction j) const inline
(i, j) const element access operator
Definition at line 394 of file MatrixSpaceI.H.
References MatrixSpace< Form, Cmpt, Mrows, Ncols >::operator()().
Member Data Documentation
mRows
const direction mRows = SubTensor::mRows static
Definition at line 101 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::ConstBlock(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::m(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::m().
nCols
const direction nCols = SubTensor::nCols static
Definition at line 102 of file MatrixSpace.H.
Referenced by MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::ConstBlock(), MatrixSpace< Form, Cmpt, Mrows, Ncols >::ConstBlock< SubTensor, BRowStart, BColStart >::n(), and MatrixSpace< Form, Cmpt, Mrows, Ncols >::Block< SubTensor, BRowStart, BColStart >::n().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/MatrixSpace/MatrixSpace.H
src/OpenFOAM/primitives/MatrixSpace/MatrixSpaceI.H