OpenFOAM: pTraits< Scalar > Class Template Reference
pTraits< Scalar > Class Template Reference
Public Types
typedef Scalar cmptType
Component type.
typedef label labelType
Equivalent type of labels used for valid component indexing.
Public Member Functions
pTraits (const Scalar &)
Construct from primitive.
pTraits (Istream &)
Construct from Istream.
operator Scalar () const
Access to the Scalar value.
operator Scalar & ()
Access to the Scalar value.
Static Public Attributes
static const direction dim = 3
Dimensionality of space.
static const direction rank = 0
Rank of Scalar is 0.
static const direction nComponents = 1
Number of components in Scalar is 1.
static const char *const typeName = "scalar"
static const char *const componentNames [] = { "" }
static const Scalar zero = 0.0
static const Scalar one = 1.0
static const Scalar max = ScalarVGREAT
static const Scalar min = -ScalarVGREAT
static const Scalar rootMax = ScalarROOTVGREAT
static const Scalar rootMin = -ScalarROOTVGREAT
Detailed Description
template<>
class Foam::pTraits< Scalar >
Definition at line 44 of file Scalar.H.
Member Typedef Documentation
cmptType
typedef Scalar cmptType
Component type.
Definition at line 51 of file Scalar.H.
labelType
typedef label labelType
Equivalent type of labels used for valid component indexing.
Definition at line 54 of file Scalar.H.
Constructor & Destructor Documentation
pTraits() [1/2]
pTraits (const Scalar & p) explicit
Construct from primitive.
Definition at line 43 of file Scalar.C.
pTraits() [2/2]
pTraits (Istream & is)
Construct from Istream.
Definition at line 49 of file Scalar.C.
Member Function Documentation
operator Scalar()
operator Scalar () const inline
Access to the Scalar value.
Definition at line 93 of file Scalar.H.
operator Scalar &()
operator Scalar & () inline
Access to the Scalar value.
Definition at line 99 of file Scalar.H.
References Foam::acos(), Foam::acosh(), Foam::asin(), Foam::asinh(), Foam::atan(), Foam::atanh(), Foam::cbrt(), Foam::cos(), Foam::cosh(), Foam::erf(), Foam::erfc(), Foam::exp(), Foam::j0(), Foam::j1(), Foam::lgamma(), Foam::log(), Foam::log10(), Foam::name(), s(), Scalar, Foam::setComponent(), Foam::sin(), Foam::sinh(), Foam::sqrt(), Foam::tan(), Foam::tanh(), Foam::transFunc(), Foam::y0(), and Foam::y1().
Member Data Documentation
dim
const direction dim = 3 static
Dimensionality of space.
Definition at line 60 of file Scalar.H.
rank
const direction rank = 0 static
Rank of Scalar is 0.
Definition at line 63 of file Scalar.H.
nComponents
const direction nComponents = 1 static
Number of components in Scalar is 1.
Definition at line 66 of file Scalar.H.
typeName
const char *const typeName = "scalar" static
Definition at line 71 of file Scalar.H.
componentNames
const char *const componentNames = { "" } static
Definition at line 72 of file Scalar.H.
zero
const Scalar zero = 0.0 static
Definition at line 73 of file Scalar.H.
one
const Scalar one = 1.0 static
Definition at line 74 of file Scalar.H.
max
const Scalar max = ScalarVGREAT static
Definition at line 75 of file Scalar.H.
min
const Scalar min = -ScalarVGREAT static
Definition at line 76 of file Scalar.H.
rootMax
const Scalar rootMax = ScalarROOTVGREAT static
Definition at line 77 of file Scalar.H.
rootMin
const Scalar rootMin = -ScalarROOTVGREAT static
Definition at line 78 of file Scalar.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/Scalar/Scalar.H
src/OpenFOAM/primitives/Scalar/Scalar.C