OpenFOAM: quaternion Class Reference
quaternion Class Reference
Quaternion class used to perform rotations in 3D space.
Public Types
enum rotationSequence {
ZYX, ZYZ, ZXY, ZXZ,
YXZ, YXY, YZX, YZY,
XYZ, XYX, XZY, XZX
}
Euler-angle rotation sequence.
typedef scalar cmptType
Component type.
Public Member Functions
quaternion ()
Construct null.
quaternion (const scalar w, const vector &v)
Construct given scalar and vector parts.
quaternion (const vector &d, const scalar theta)
Construct a rotation quaternion given the direction d.
quaternion (const vector &d, const scalar cosTheta, const bool normalized)
Construct a rotation quaternion given the direction d.
quaternion (const scalar w)
Construct a real from the given scalar part, the vector part = zero.
quaternion (const vector &v)
Construct a pure imaginary quaternion given the vector part,.
quaternion (const rotationSequence rs, const vector &angles)
Construct a quaternion given the three Euler angles.
quaternion (const tensor &rotationTensor)
Construct a quaternion from a rotation tensor.
quaternion (Istream &)
Construct from Istream.
scalar w () const
Scalar part of the quaternion (= cos(theta/2) for rotation)
const vector & v () const
Vector part of the quaternion (= axis of rotation)
tensor R () const
The rotation tensor corresponding the quaternion.
vector eulerAngles (const rotationSequence rs) const
Return a vector of euler angles corresponding to the.
quaternion normalized () const
scalar & w ()
Scalar part of the quaternion (= cos(theta/2) for rotation)
vector & v ()
Vector part of the quaternion (= axis of rotation)
void normalize ()
vector transform (const vector &v) const
Rotate the given vector.
vector invTransform (const vector &v) const
Rotate the given vector anti-clockwise.
quaternion transform (const quaternion &q) const
Rotate the given quaternion (and normalize)
quaternion invTransform (const quaternion &q) const
Rotate the given quaternion anti-clockwise (and normalize)
void operator= (const quaternion &)
void operator+= (const quaternion &)
void operator-= (const quaternion &)
void operator*= (const quaternion &)
void operator/= (const quaternion &)
void operator= (const scalar)
void operator= (const vector &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Member Functions
static quaternion unit (const vector &v)
Return the unit quaternion (versor) from the given vector.
Static Public Attributes
static const direction rank = 1
Rank of quaternion is 1.
static const char *const typeName = "quaternion"
static const quaternion zero
static const quaternion I
Friends
Istream & operator>> (Istream &is, quaternion &)
Ostream & operator<< (Ostream &os, const quaternion &C)
Detailed Description
Quaternion class used to perform rotations in 3D space.
Source files
quaternion.H
quaternionI.H
quaternion.C
Definition at line 60 of file quaternion.H.
Member Typedef Documentation
cmptType
typedef scalar cmptType
Component type.
Definition at line 98 of file quaternion.H.
Member Enumeration Documentation
rotationSequence
enum rotationSequence
Euler-angle rotation sequence.
Enumerator
ZYX
ZYZ
ZXY
ZXZ
YXZ
YXY
YZX
YZY
XYZ
XYX
XZY
XZX
Definition at line 101 of file quaternion.H.
Constructor & Destructor Documentation
quaternion() [1/9]
quaternion () inline
Construct null.
Definition at line 28 of file quaternionI.H.
Referenced by Foam::conjugate(), Foam::exp(), Foam::inv(), quaternion::normalize(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Foam::operator/(), quaternion::quaternion(), and quaternion::unit().
quaternion() [2/9]
quaternion (const scalar w, const vector & v) inline
Construct given scalar and vector parts.
Definition at line 32 of file quaternionI.H.
quaternion() [3/9]
quaternion (const vector & d, const scalar theta) inline
Construct a rotation quaternion given the direction d.
and angle theta
Definition at line 39 of file quaternionI.H.
References quaternion::quaternion().
quaternion() [4/9]
quaternion (const vector & d, const scalar cosTheta, const bool normalized) inline
Construct a rotation quaternion given the direction d.
and cosine angle cosTheta and a if d is normalized
Definition at line 47 of file quaternionI.H.
References Foam::mag(), and Foam::sqrt().
quaternion() [5/9]
quaternion (const scalar w) inline explicit
Construct a real from the given scalar part, the vector part = zero.
Definition at line 67 of file quaternionI.H.
quaternion() [6/9]
quaternion (const vector & v) inline explicit
Construct a pure imaginary quaternion given the vector part,.
the scalar part = 0
Definition at line 74 of file quaternionI.H.
quaternion() [7/9]
quaternion (const rotationSequence rs, const vector & angles) inline
Construct a quaternion given the three Euler angles.
Definition at line 88 of file quaternionI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, quaternion::operator*=(), quaternion::operator=(), quaternion::quaternion(), Vector< Cmpt >::x(), quaternion::XYX, quaternion::XYZ, quaternion::XZX, quaternion::XZY, Vector< Cmpt >::y(), quaternion::YXY, quaternion::YXZ, quaternion::YZX, quaternion::YZY, Vector< Cmpt >::z(), quaternion::ZXY, quaternion::ZXZ, quaternion::ZYX, and quaternion::ZYZ.
quaternion() [8/9]
quaternion (const tensor & rotationTensor) inline explicit
Construct a quaternion from a rotation tensor.
Definition at line 176 of file quaternionI.H.
References s(), Foam::sqrt(), Tensor< Cmpt >::xx(), Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), Tensor< Cmpt >::yx(), Tensor< Cmpt >::yy(), Tensor< Cmpt >::yz(), Tensor< Cmpt >::zx(), Tensor< Cmpt >::zy(), and Tensor< Cmpt >::zz().
quaternion() [9/9]
quaternion (Istream & is)
Construct from Istream.
Definition at line 38 of file quaternion.C.
Member Function Documentation
unit()
Foam::quaternion unit (const vector & v) inline static
Return the unit quaternion (versor) from the given vector.
(w = sqrt(1 - |sqr(v)|))
Definition at line 81 of file quaternionI.H.
References Foam::magSqr(), quaternion::quaternion(), and Foam::sqrt().
Referenced by joint::unitQuaternion().
w() [1/2]
Foam::scalar w () const inline
Scalar part of the quaternion (= cos(theta/2) for rotation)
Definition at line 254 of file quaternionI.H.
Referenced by Foam::conjugate(), quaternion::eulerAngles(), Foam::exp(), Foam::inv(), Foam::magSqr(), Foam::name(), quaternion::normalize(), Foam::operator*(), quaternion::operator*=(), Foam::operator+(), Foam::operator-(), Foam::operator/(), Foam::operator<<(), Foam::operator==(), Foam::operator>>(), Foam::pow(), and quaternion::R().
v() [1/2]
const Foam::vector & v () const inline
Vector part of the quaternion (= axis of rotation)
Definition at line 260 of file quaternionI.H.
Referenced by Foam::conjugate(), quaternion::eulerAngles(), Foam::exp(), Foam::inv(), quaternion::invTransform(), Foam::magSqr(), Foam::name(), quaternion::normalize(), Foam::operator*(), quaternion::operator*=(), Foam::operator+(), Foam::operator-(), Foam::operator/(), Foam::operator<<(), quaternion::operator=(), Foam::operator==(), Foam::operator>>(), Foam::pow(), quaternion::R(), and joint::unitQuaternion().
R()
Foam::tensor R () const inline
The rotation tensor corresponding the quaternion.
Definition at line 323 of file quaternionI.H.
References Foam::acos(), Foam::asin(), Foam::atan2(), Foam::constant::physicoChemical::c2, quaternion::eulerAngles(), Foam::sqr(), quaternion::v(), quaternion::w(), x, Vector< Cmpt >::x(), y, Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by Foam::transform(), Foam::transformPoints(), and triad::triad().
eulerAngles()
Foam::vector eulerAngles (const rotationSequence rs) const inline
Return a vector of euler angles corresponding to the.
specified rotation sequence
Definition at line 373 of file quaternionI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::sqr(), quaternion::v(), quaternion::w(), x, quaternion::XYX, quaternion::XYZ, quaternion::XZX, quaternion::XZY, y, quaternion::YXY, quaternion::YXZ, quaternion::YZX, quaternion::YZY, Foam::Zero, quaternion::ZXY, quaternion::ZXZ, quaternion::ZYX, and quaternion::ZYZ.
Referenced by quaternion::R().
normalized()
Foam::quaternion normalized () const inline
Definition at line 278 of file quaternionI.H.
References Foam::mag().
w() [2/2]
Foam::scalar & w () inline
Scalar part of the quaternion (= cos(theta/2) for rotation)
Definition at line 266 of file quaternionI.H.
v() [2/2]
Foam::vector & v () inline
Vector part of the quaternion (= axis of rotation)
Definition at line 272 of file quaternionI.H.
normalize()
void normalize () inline
Definition at line 284 of file quaternionI.H.
References Foam::mag(), quaternion::operator/=(), quaternion::quaternion(), quaternion::v(), and quaternion::w().
Referenced by Foam::average().
transform() [1/2]
Foam::vector transform (const vector & v) const inline
Rotate the given vector.
Definition at line 296 of file quaternionI.H.
References Foam::conjugate().
Referenced by Foam::inv(), Foam::operator*(), Foam::operator/(), septernion::operator/=(), and septernion::transformPoint().
invTransform() [1/2]
Foam::vector invTransform (const vector & v) const inline
Rotate the given vector anti-clockwise.
Definition at line 302 of file quaternionI.H.
References Foam::conjugate(), and quaternion::v().
Referenced by septernion::invTransformPoint(), Foam::operator*(), septernion::operator*=(), and quaternion::transform().
transform() [2/2]
Foam::quaternion transform (const quaternion & q) const inline
Rotate the given quaternion (and normalize)
Definition at line 308 of file quaternionI.H.
References quaternion::invTransform(), and Foam::normalize().
invTransform() [2/2]
Foam::quaternion invTransform (const quaternion & q) const inline
Rotate the given quaternion anti-clockwise (and normalize)
Definition at line 315 of file quaternionI.H.
References Foam::conjugate(), and Foam::normalize().
operator=() [1/3]
void operator= (const quaternion & q) inline
Definition at line 526 of file quaternionI.H.
Referenced by quaternion::quaternion().
operator+=()
void operator+= (const quaternion & q) inline
Definition at line 532 of file quaternionI.H.
operator-=()
void operator-= (const quaternion & q) inline
Definition at line 538 of file quaternionI.H.
operator*=() [1/2]
void operator*= (const quaternion & q) inline
Definition at line 544 of file quaternionI.H.
References quaternion::v(), and quaternion::w().
Referenced by quaternion::operator/=(), and quaternion::quaternion().
operator/=() [1/2]
void operator/= (const quaternion & q) inline
Definition at line 551 of file quaternionI.H.
References Foam::inv(), and quaternion::operator*=().
Referenced by quaternion::normalize().
operator=() [2/3]
void operator= (const scalar s) inline
Definition at line 557 of file quaternionI.H.
References s().
operator=() [3/3]
void operator= (const vector & v) inline
Definition at line 563 of file quaternionI.H.
References quaternion::v().
operator*=() [2/2]
void operator*= (const scalar s) inline
Definition at line 569 of file quaternionI.H.
References s().
operator/=() [2/2]
void operator/= (const scalar s) inline
Definition at line 575 of file quaternionI.H.
References s().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & is, quaternion &) friend
operator<<
Ostream& operator<< (Ostream & os, const quaternion & C) friend
Member Data Documentation
rank
const direction rank = 1 static
Rank of quaternion is 1.
Definition at line 110 of file quaternion.H.
typeName
const char *const typeName = "quaternion" static
Definition at line 115 of file quaternion.H.
zero
const Foam::quaternion zero static
Definition at line 117 of file quaternion.H.
I
const Foam::quaternion I static
Definition at line 118 of file quaternion.H.
Referenced by septernion::operator=().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/quaternion/quaternion.H
src/OpenFOAM/primitives/quaternion/quaternion.C
src/OpenFOAM/primitives/quaternion/quaternionI.H