OpenFOAM: scalarRange Class Reference
scalarRange Class Reference
A scalar range specifier.
Public Member Functions
scalarRange ()
Construct an empty range.
scalarRange (const scalar lower, const scalar upper)
Construct a range from lower to upper.
scalarRange (Istream &)
Construct from Istream.
bool empty () const
Is the range empty?
bool valid () const
Is the range non-empty?
bool isExact () const
Is the range 'EXACT'?
scalar value () const
The value constituting an 'EXACT' match.
scalar lower () const
The lower limit.
scalar upper () const
The upper limit.
bool selected (const scalar) const
Return true if the value is within the range.
bool operator== (const scalarRange &) const
bool operator!= (const scalarRange &) const
Static Public Attributes
static int debug
Friends
Istream & operator>> (Istream &, scalarRange &)
Ostream & operator<< (Ostream &, const scalarRange &)
Detailed Description
A scalar range specifier.
The range selector can be specified as an "LOWER:UPPER" range, as a "LOWER:" bound, as an ":UPPER" bound or simply as an "EXACT" value. The read constructor uses a colon (:) as a range marker and a comma (,) to delimit the next possible range selector.
Source files
scalarRange.H
scalarRange.C
Definition at line 62 of file scalarRange.H.
Constructor & Destructor Documentation
scalarRange() [1/3]
scalarRange ()
Construct an empty range.
Definition at line 36 of file scalarRange.C.
scalarRange() [2/3]
scalarRange (const scalar lower, const scalar upper)
Construct a range from lower to upper.
Definition at line 44 of file scalarRange.C.
scalarRange() [3/3]
scalarRange (Istream & is)
Construct from Istream.
Since commas can be used as list delimiters, leading and trailing commas are ignored.
Definition at line 59 of file scalarRange.C.
References scalarRange::debug, Foam::endl(), and Foam::Info.
Member Function Documentation
empty()
bool empty () const
Is the range empty?
Definition at line 76 of file scalarRange.C.
valid()
bool valid () const
Is the range non-empty?
Definition at line 82 of file scalarRange.C.
Referenced by scalarRanges::scalarRanges().
isExact()
bool isExact () const
Is the range 'EXACT'?
Definition at line 88 of file scalarRange.C.
value()
Foam::scalar value () const
The value constituting an 'EXACT' match.
or the values for 'UPPER' or 'LOWER' limits
Definition at line 94 of file scalarRange.C.
lower()
Foam::scalar lower () const
The lower limit.
Definition at line 100 of file scalarRange.C.
upper()
Foam::scalar upper () const
The upper limit.
Definition at line 112 of file scalarRange.C.
selected()
bool selected (const scalar value) const
Return true if the value is within the range.
Definition at line 131 of file scalarRange.C.
operator==()
bool operator== (const scalarRange & range) const
Definition at line 156 of file scalarRange.C.
Referenced by scalarRange::operator!=().
operator!=()
bool operator!= (const scalarRange & range) const
Definition at line 167 of file scalarRange.C.
References scalarRange::operator==().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , scalarRange &) friend
operator<<
Ostream& operator<< (Ostream & , const scalarRange &) friend
Member Data Documentation
debug
int debug static
Definition at line 84 of file scalarRange.H.
Referenced by Foam::operator>>(), and scalarRange::scalarRange().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/scalarRange/scalarRange.H
src/OpenFOAM/primitives/ranges/scalarRange/scalarRange.C