OpenFOAM: spatialTransform Class Reference
spatialTransform Class Reference
Compact representation of the Plücker spatial transformation tensor in terms of the rotation tensor E and translation vector r .
Classes
class dual
Wrapper-class to provide dual functions and operators.
class transpose
Wrapper-class to provide transpose functions and operators.
Public Member Functions
spatialTransform ()
Construct null.
spatialTransform (const tensor &E, const vector &r)
Construct from components.
spatialTransform (Istream &)
Construct from Istream.
const tensor & E () const
Return the rotation tensor.
tensor & E ()
Return non-const access to the rotation tensor.
const vector & r () const
Return the translation vector.
vector & r ()
Return non-const access to the translation vector.
transpose T () const
Return the transpose transformation tensor ^A{X^*}_B.
spatialTransform inv () const
Return the inverse transformation tensor: X^-1.
dual operator* () const
Return the dual transformation tensor ^B{X^*}_A.
operator spatialTensor () const
Return transformation tensor ^BX_A.
void operator &= (const spatialTransform &X)
Inner-product multiply with a transformation tensor.
spatialTransform operator & (const spatialTransform &X) const
Return the inner-product of two transformation tensors.
spatialVector operator & (const spatialVector &v) const
Transform v: ^BX_A . v.
vector transformPoint (const vector &p) const
Transform position p.
spatialVector operator && (const spatialVector &v) const
Transform position p.
Friends
Istream & operator>> (Istream &, spatialTransform &)
Ostream & operator<< (Ostream &, const spatialTransform &)
Detailed Description
Compact representation of the Plücker spatial transformation tensor in terms of the rotation tensor E and translation vector r .
See Chapter 2 and Appendix A in reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
Source files
spatialTransform.H
spatialTransformI.H
Definition at line 68 of file spatialTransform.H.
Constructor & Destructor Documentation
spatialTransform() [1/3]
spatialTransform () inline
Construct null.
Definition at line 38 of file spatialTransformI.H.
Referenced by spatialTransform::inv(), spatialTransform::operator spatialTensor(), Foam::Xr(), Foam::Xrx(), Foam::Xry(), Foam::Xrz(), and Foam::Xt().
spatialTransform() [2/3]
spatialTransform (const tensor & E, const vector & r) inline
Construct from components.
Definition at line 46 of file spatialTransformI.H.
spatialTransform() [3/3]
spatialTransform (Istream & is) inline
Construct from Istream.
Definition at line 56 of file spatialTransformI.H.
Member Function Documentation
E() [1/2]
const Foam::tensor & E () const inline
Return the rotation tensor.
Definition at line 77 of file spatialTransformI.H.
Referenced by Pxyz::jcalc(), Ryxz::jcalc(), Rzyx::jcalc(), Rxyz::jcalc(), Rs::jcalc(), spatialTransform::transpose::operator spatialTensor(), spatialTransform::dual::operator spatialTensor(), Foam::operator<<(), Foam::operator>>(), rigidBodyMotion::status(), and Foam::RBD::transform().
E() [2/2]
Foam::tensor & E () inline
Return non-const access to the rotation tensor.
Definition at line 82 of file spatialTransformI.H.
r() [1/2]
const Foam::vector & r () const inline
Return the translation vector.
Definition at line 87 of file spatialTransformI.H.
Referenced by Pxyz::jcalc(), Ryxz::jcalc(), Rzyx::jcalc(), Rxyz::jcalc(), Rs::jcalc(), spatialTransform::transpose::operator spatialTensor(), spatialTransform::dual::operator spatialTensor(), Foam::operator<<(), Foam::operator>>(), rigidBodyMotion::status(), and Foam::RBD::transform().
r() [2/2]
Foam::vector & r () inline
Return non-const access to the translation vector.
Definition at line 92 of file spatialTransformI.H.
T()
Foam::spatialTransform::transpose T () const inline
Return the transpose transformation tensor ^A{X^*}_B.
X^T
Definition at line 98 of file spatialTransformI.H.
inv()
Foam::spatialTransform inv () const inline
Return the inverse transformation tensor: X^-1.
X^-1 = (E^T, −E.r)
Definition at line 104 of file spatialTransformI.H.
References spatialTransform::spatialTransform().
operator*()
Foam::spatialTransform::dual operator* () const inline
Return the dual transformation tensor ^B{X^*}_A.
Definition at line 112 of file spatialTransformI.H.
References spatialTransform::dual::dual().
operator spatialTensor()
operator spatialTensor () const inline
Return transformation tensor ^BX_A.
X
Definition at line 118 of file spatialTransformI.H.
References spatialTransform::operator &=(), spatialTransform::spatialTransform(), spatialTransform::transformPoint(), and Foam::Zero.
operator &=()
void operator&= (const spatialTransform & X) inline
Inner-product multiply with a transformation tensor.
Referenced by spatialTransform::operator spatialTensor().
operator &() [1/2]
spatialTransform operator& (const spatialTransform & X) const inline
Return the inner-product of two transformation tensors.
operator &() [2/2]
spatialVector operator& (const spatialVector & v) const inline
Transform v: ^BX_A . v.
X.v = (E . vw, E . (vl - r^vw))
transformPoint()
Foam::vector transformPoint (const vector & p) const inline
Transform position p.
X:p = E . (pl - r)
Definition at line 171 of file spatialTransformI.H.
Referenced by spatialTransform::operator spatialTensor(), and rigidBodyMotion::transformPoints().
operator &&()
spatialVector operator&& (const spatialVector & v) const inline
Transform position p.
X:p = (E . pw, E . (vl - r))
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , spatialTransform &) friend
operator<<
Ostream& operator<< (Ostream & , const spatialTransform &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransform.H
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransformI.H