OpenFOAM: spatialTransform::transpose Class Reference
spatialTransform::transpose Class Reference
Wrapper-class to provide transpose functions and operators.
Public Member Functions
transpose (const spatialTransform &X)
Construct from a spatialTransform.
operator spatialTensor () const
Return the transpose transformation tensor ^A{X^*}_B.
spatialVector operator & (const spatialVector &f) const
Transpose transform dual f: ^A{X^*}_B & f.
Detailed Description
Wrapper-class to provide transpose functions and operators.
Definition at line 88 of file spatialTransform.H.
Constructor & Destructor Documentation
transpose()
transpose (const spatialTransform & X) inline
Construct from a spatialTransform.
Definition at line 63 of file spatialTransformI.H.
Member Function Documentation
operator spatialTensor()
operator spatialTensor () const inline
Return the transpose transformation tensor ^A{X^*}_B.
X^T
Definition at line 179 of file spatialTransformI.H.
References spatialTransform::E(), f(), spatialTransform::r(), Tensor< Cmpt >::T(), and Foam::Zero.
operator &()
spatialVector operator& (const spatialVector & f) const inline
Transpose transform dual f: ^A{X^*}_B & f.
X^T . f = (E^T . fl + r ^ E^T . fw, E^T . fl)
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransform.H
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransformI.H