OpenFOAM: SpatialTensor< Cmpt > Class Template Reference
SpatialTensor< Cmpt > Class Template Reference
Templated 3D spatial tensor derived from MatrixSpace used to represent transformations of spatial vectors and the angular and linear inertia of rigid bodies.
Public Member Functions
SpatialTensor ()
Construct null.
SpatialTensor (const Foam::zero)
Construct initialized to zero.
SpatialTensor (const typename SpatialTensor::msType &)
Construct given MatrixSpace of the same rank.
SpatialTensor (const Tensor< Cmpt > &t00, const Tensor< Cmpt > &t01, const Tensor< Cmpt > &t10, const Tensor< Cmpt > &t11)
Construct given 4 tensor blocks.
SpatialTensor (const Cmpt &t00, const Cmpt &t01, const Cmpt &t02, const Cmpt &t03, const Cmpt &t04, const Cmpt &t05, const Cmpt &t10, const Cmpt &t11, const Cmpt &t12, const Cmpt &t13, const Cmpt &t14, const Cmpt &t15, const Cmpt &t20, const Cmpt &t21, const Cmpt &t22, const Cmpt &t23, const Cmpt &t24, const Cmpt &t25, const Cmpt &t30, const Cmpt &t31, const Cmpt &t32, const Cmpt &t33, const Cmpt &t34, const Cmpt &t35, const Cmpt &t40, const Cmpt &t41, const Cmpt &t42, const Cmpt &t43, const Cmpt &t44, const Cmpt &t45, const Cmpt &t50, const Cmpt &t51, const Cmpt &t52, const Cmpt &t53, const Cmpt &t54, const Cmpt &t55)
Construct given 36 components.
SpatialTensor (Istream &)
Construct from Istream.
Public Member Functions inherited from MatrixSpace< SpatialTensor< Cmpt >, Cmpt, 6, 6 >
MatrixSpace ()
Construct null.
MatrixSpace (const Foam::zero)
Construct initialized to zero.
MatrixSpace (const VectorSpace< Form2, Cmpt2, Mrows *Ncols > &)
Construct as copy of a VectorSpace with the same size.
MatrixSpace (const Block2< SpatialTensor< Cmpt >, BRowStart, BColStart > &block)
Construct from a block of another matrix space.
MatrixSpace (Istream &)
Construct from Istream.
const Cmpt & elmt () const
Fast const element access using compile-time addressing.
Cmpt & elmt ()
Fast element access using compile-time addressing.
const Cmpt & xx () const
Cmpt & xx ()
const Cmpt & xy () const
Cmpt & xy ()
const Cmpt & xz () const
Cmpt & xz ()
const Cmpt & yx () const
Cmpt & yx ()
const Cmpt & yy () const
Cmpt & yy ()
const Cmpt & yz () const
Cmpt & yz ()
const Cmpt & zx () const
Cmpt & zx ()
const Cmpt & zy () const
Cmpt & zy ()
const Cmpt & zz () const
Cmpt & zz ()
typeOfTranspose< Cmpt, SpatialTensor< Cmpt > >::type T () const
Return the transpose of the matrix.
ConstBlock< SubTensor, BRowStart, BColStart > block () const
Return a const sub-block corresponding to the specified type.
Block< SubTensor, BRowStart, BColStart > block ()
Return a sub-block corresponding to the specified type.
Foam::MatrixSpace< SpatialTensor< Cmpt >, Cmpt, Mrows, Ncols >::template ConstBlock< SubTensor, BRowStart, BColStart > block () const
Foam::MatrixSpace< SpatialTensor< Cmpt >, Cmpt, Mrows, Ncols >::template Block< SubTensor, BRowStart, BColStart > block ()
const Cmpt & operator() (const direction &i, const direction &j) const
(i, j) const element access operator
Cmpt & operator() (const direction &i, const direction &j)
(i, j) element access operator
void operator= (const Foam::zero)
Assignment to zero.
void operator= (const Block2< SpatialTensor< Cmpt >, BRowStart, BColStart > &block)
Assignment to a block of another matrix space.
void operator&= (const MatrixSpace< SpatialTensor< Cmpt >, Cmpt, Ncols, Ncols > &matrix)
Inner product with a compatible square matrix.
Public Member Functions inherited from VectorSpace< SpatialTensor< Cmpt >, Cmpt, Mrows *Ncols >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< SpatialTensor< Cmpt >, Cmpt, Ncmpts > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const ConstBlock< SubVector, BStart > block () const
const VectorSpace< SpatialTensor< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SpatialTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SpatialTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SpatialTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const direction rank = 2
Rank of Tensor is 2.
static const SpatialTensor I
Identity matrix for square matrices.
Static Public Attributes inherited from MatrixSpace< SpatialTensor< Cmpt >, Cmpt, 6, 6 >
static const direction mRows
static const direction nCols
Static Public Attributes inherited from VectorSpace< SpatialTensor< Cmpt >, Cmpt, Mrows *Ncols >
static const direction dim
Dimensionality of space.
static const direction nComponents
Number of components in this vector space.
static const direction mRows
static const direction nCols
static const char *const typeName
static const char *const componentNames []
static const SpatialTensor< Cmpt > zero
static const SpatialTensor< Cmpt > one
static const SpatialTensor< Cmpt > max
static const SpatialTensor< Cmpt > min
static const SpatialTensor< Cmpt > rootMax
static const SpatialTensor< Cmpt > rootMin
Additional Inherited Members
Public Types inherited from MatrixSpace< SpatialTensor< Cmpt >, Cmpt, 6, 6 >
typedef MatrixSpace< SpatialTensor< Cmpt >, Cmpt, Mrows, Ncols > msType
MatrixSpace type.
Public Types inherited from VectorSpace< SpatialTensor< Cmpt >, Cmpt, Mrows *Ncols >
typedef VectorSpace< SpatialTensor< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
Static Public Member Functions inherited from MatrixSpace< SpatialTensor< Cmpt >, Cmpt, 6, 6 >
static direction m ()
Return the number of rows.
static direction n ()
Return the number of columns.
static msType identity ()
Return the identity matrix for square matrix spaces.
Static Public Member Functions inherited from VectorSpace< SpatialTensor< Cmpt >, Cmpt, Mrows *Ncols >
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static SpatialTensor< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< SpatialTensor< Cmpt >, Cmpt, Mrows *Ncols >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SpatialTensor< Cmpt >
Templated 3D spatial tensor derived from MatrixSpace used to represent transformations of spatial vectors and the angular and linear inertia of rigid bodies.
Reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
Source files
SpatialTensor.H
SpatialTensorI.H
See also
Foam::MatrixSpace Foam::Tensor Foam::SpatialVector
Definition at line 64 of file SpatialTensor.H.
Constructor & Destructor Documentation
SpatialTensor() [1/6]
SpatialTensor () inline
Construct null.
Definition at line 31 of file SpatialTensorI.H.
Referenced by SpatialTensor< Cmpt >::SpatialTensor().
SpatialTensor() [2/6]
SpatialTensor (const Foam::zero) inline
Construct initialized to zero.
Definition at line 36 of file SpatialTensorI.H.
References SpatialTensor< Cmpt >::SpatialTensor().
SpatialTensor() [3/6]
SpatialTensor (const typename SpatialTensor< Cmpt >::msType & ms) inline
Construct given MatrixSpace of the same rank.
Definition at line 44 of file SpatialTensorI.H.
References SpatialTensor< Cmpt >::SpatialTensor().
SpatialTensor() [4/6]
SpatialTensor (const Tensor< Cmpt > & t00, const Tensor< Cmpt > & t01, const Tensor< Cmpt > & t10, const Tensor< Cmpt > & t11) inline
Construct given 4 tensor blocks.
Definition at line 54 of file SpatialTensorI.H.
References SpatialTensor< Cmpt >::SpatialTensor(), VectorSpace< SpatialTensor< Cmpt >, Cmpt, Mrows *Ncols >::v_, Tensor< Cmpt >::xx(), Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), Tensor< Cmpt >::yx(), Tensor< Cmpt >::yy(), Tensor< Cmpt >::yz(), Tensor< Cmpt >::zx(), Tensor< Cmpt >::zy(), and Tensor< Cmpt >::zz().
SpatialTensor() [5/6]
SpatialTensor (const Cmpt & t00, const Cmpt & t01, const Cmpt & t02, const Cmpt & t03, const Cmpt & t04, const Cmpt & t05, const Cmpt & t10, const Cmpt & t11, const Cmpt & t12, const Cmpt & t13, const Cmpt & t14, const Cmpt & t15, const Cmpt & t20, const Cmpt & t21, const Cmpt & t22, const Cmpt & t23, const Cmpt & t24, const Cmpt & t25, const Cmpt & t30, const Cmpt & t31, const Cmpt & t32, const Cmpt & t33, const Cmpt & t34, const Cmpt & t35, const Cmpt & t40, const Cmpt & t41, const Cmpt & t42, const Cmpt & t43, const Cmpt & t44, const Cmpt & t45, const Cmpt & t50, const Cmpt & t51, const Cmpt & t52, const Cmpt & t53, const Cmpt & t54, const Cmpt & t55) inline
Construct given 36 components.
Definition at line 83 of file SpatialTensorI.H.
References VectorSpace< SpatialTensor< Cmpt >, Cmpt, Mrows *Ncols >::v_.
SpatialTensor() [6/6]
SpatialTensor (Istream & is) inline
Construct from Istream.
Definition at line 130 of file SpatialTensorI.H.
Member Data Documentation
rank
const direction rank = 2 static
Rank of Tensor is 2.
Definition at line 74 of file SpatialTensor.H.
I
const Foam::spatialTensor I static
Identity matrix for square matrices.
Definition at line 80 of file SpatialTensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/spatialVectorAlgebra/SpatialTensor/SpatialTensor.H
src/OpenFOAM/primitives/spatialVectorAlgebra/SpatialTensor/spatialTensor/spatialTensor.C
src/OpenFOAM/primitives/spatialVectorAlgebra/SpatialTensor/SpatialTensorI.H