OpenFOAM: spatialTransform::dual Class Reference
spatialTransform::dual Class Reference
Wrapper-class to provide dual functions and operators.
Public Member Functions
dual (const spatialTransform &X)
Construct from a spatialTransform.
operator spatialTensor () const
Return dual transformation tensor ^B{X^*}_A.
spatialVector operator & (const spatialVector &f) const
Transform dual f: ^B{X^*}_A & f.
Detailed Description
Wrapper-class to provide dual functions and operators.
Definition at line 108 of file spatialTransform.H.
Constructor & Destructor Documentation
dual()
dual (const spatialTransform & X) inline
Construct from a spatialTransform.
Definition at line 69 of file spatialTransformI.H.
Referenced by spatialTransform::operator*().
Member Function Documentation
operator spatialTensor()
operator spatialTensor () const inline
Return dual transformation tensor ^B{X^*}_A.
Definition at line 204 of file spatialTransformI.H.
References spatialTransform::E(), f(), spatialTransform::r(), and Foam::Zero.
operator &()
spatialVector operator& (const spatialVector & f) const inline
Transform dual f: ^B{X^*}_A & f.
X^* . f = (E . fw - r ^ fl, E . fl)
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransform.H
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransformI.H