OpenFOAM: septernion Class Reference
septernion Class Reference
Septernion class used to perform translations and rotations in 3D space.
Public Member Functions
septernion ()
Construct null.
septernion (const vector &t, const quaternion &r)
Construct given a translation vector and rotation quaternion.
septernion (const vector &t)
Construct a pure translation septernion given a translation vector.
septernion (const quaternion &r)
Construct a pure rotation septernion given a rotation quaternion.
septernion (const spatialTransform &st)
Construct a general septernion from the given spatialTransform.
septernion (Istream &)
Construct from Istream.
const vector & t () const
const quaternion & r () const
vector & t ()
quaternion & r ()
vector transformPoint (const vector &v) const
Transform the given coordinate point.
vector invTransformPoint (const vector &v) const
Inverse Transform the given coordinate point.
void operator= (const septernion &)
void operator*= (const septernion &)
void operator= (const vector &)
void operator+= (const vector &)
void operator-= (const vector &)
void operator= (const quaternion &)
void operator*= (const quaternion &)
void operator/= (const quaternion &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName = "septernion"
static const septernion zero
static const septernion I
Friends
Istream & operator>> (Istream &is, septernion &)
Ostream & operator<< (Ostream &os, const septernion &C)
Detailed Description
Septernion class used to perform translations and rotations in 3D space.
It is composed of a translation vector and rotation quaternion and as such has seven components hence the name "septernion" from the Latin to be consistent with quaternion rather than "hepternion" derived from the Greek.
Source files
septernion.H
septernionI.H
septernion.C
Definition at line 65 of file septernion.H.
Constructor & Destructor Documentation
septernion() [1/6]
septernion () inline
Construct null.
Definition at line 28 of file septernionI.H.
Referenced by Foam::inv(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Foam::operator/(), and Foam::slerp().
septernion() [2/6]
septernion (const vector & t, const quaternion & r) inline
Construct given a translation vector and rotation quaternion.
Definition at line 31 of file septernionI.H.
septernion() [3/6]
septernion (const vector & t) inline explicit
Construct a pure translation septernion given a translation vector.
Definition at line 37 of file septernionI.H.
septernion() [4/6]
septernion (const quaternion & r) inline explicit
Construct a pure rotation septernion given a rotation quaternion.
Definition at line 43 of file septernionI.H.
septernion() [5/6]
septernion (const spatialTransform & st) inline explicit
Construct a general septernion from the given spatialTransform.
Definition at line 49 of file septernionI.H.
septernion() [6/6]
septernion (Istream & is)
Construct from Istream.
Definition at line 46 of file septernion.C.
Member Function Documentation
t() [1/2]
const Foam::vector & t () const inline
Definition at line 58 of file septernionI.H.
Referenced by Foam::average(), Foam::contiguous< septernion >(), Foam::inv(), septernion::invTransformPoint(), Foam::name(), Foam::operator*(), septernion::operator*=(), Foam::operator+(), septernion::operator+=(), Foam::operator-(), septernion::operator-=(), Foam::operator/(), Foam::operator<<(), septernion::operator=(), Foam::operator==(), Foam::operator>>(), Foam::slerp(), septernion::transformPoint(), and Foam::transformPoints().
r() [1/2]
const Foam::quaternion & r () const inline
Definition at line 64 of file septernionI.H.
Referenced by Foam::average(), Foam::contiguous< septernion >(), Foam::inv(), septernion::invTransformPoint(), Foam::name(), Foam::operator*(), septernion::operator*=(), Foam::operator+(), Foam::operator-(), Foam::operator/(), septernion::operator/=(), Foam::operator<<(), septernion::operator=(), Foam::operator==(), Foam::operator>>(), Foam::slerp(), septernion::transformPoint(), and Foam::transformPoints().
t() [2/2]
Foam::vector & t () inline
Definition at line 70 of file septernionI.H.
r() [2/2]
Foam::quaternion & r () inline
Definition at line 76 of file septernionI.H.
transformPoint()
Foam::vector transformPoint (const vector & v) const inline
Transform the given coordinate point.
Definition at line 82 of file septernionI.H.
References septernion::r(), septernion::t(), and quaternion::transform().
invTransformPoint()
Foam::vector invTransformPoint (const vector & v) const inline
Inverse Transform the given coordinate point.
Definition at line 88 of file septernionI.H.
References quaternion::invTransform(), septernion::r(), and septernion::t().
Referenced by sixDoFRigidBodyMotion::transform().
operator=() [1/3]
void operator= (const septernion & tr) inline
Definition at line 96 of file septernionI.H.
operator*=() [1/3]
void operator*= (const septernion & tr) inline
Definition at line 102 of file septernionI.H.
References quaternion::invTransform(), septernion::r(), and septernion::t().
operator=() [2/3]
void operator= (const vector & t) inline
Definition at line 109 of file septernionI.H.
References quaternion::I, and septernion::t().
operator+=()
void operator+= (const vector & t) inline
Definition at line 115 of file septernionI.H.
References septernion::t().
operator-=()
void operator-= (const vector & t) inline
Definition at line 120 of file septernionI.H.
References septernion::t().
operator=() [3/3]
void operator= (const quaternion & r) inline
Definition at line 126 of file septernionI.H.
References septernion::r(), and Foam::Zero.
operator*=() [2/3]
void operator*= (const quaternion & r) inline
Definition at line 132 of file septernionI.H.
References quaternion::invTransform(), and septernion::r().
operator/=() [1/2]
void operator/= (const quaternion & r) inline
Definition at line 138 of file septernionI.H.
References septernion::r(), and quaternion::transform().
operator*=() [3/3]
void operator*= (const scalar s) inline
Definition at line 145 of file septernionI.H.
References s().
operator/=() [2/2]
void operator/= (const scalar s) inline
Definition at line 151 of file septernionI.H.
References s().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & is, septernion &) friend
operator<<
Ostream& operator<< (Ostream & os, const septernion & C) friend
Member Data Documentation
typeName
const char *const typeName = "septernion" static
Definition at line 80 of file septernion.H.
zero
const Foam::septernion zero static
Definition at line 82 of file septernion.H.
I
const Foam::septernion I static
Definition at line 83 of file septernion.H.
Referenced by sixDoFRigidBodyMotion::transform(), and rigidBodyMotion::transformPoints().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/septernion/septernion.H
src/OpenFOAM/primitives/septernion/septernion.C
src/OpenFOAM/primitives/septernion/septernionI.H