OpenFOAM: string Class Reference
string Class Reference
A class for handling character strings derived from std::string.
Classes
class hash
Hashing function class, shared by all the derived classes.
Public Member Functions
string ()
Construct null.
string (const std::string &)
Construct from std::string.
string (const char *)
Construct as copy of character array.
string (const char *, const size_type)
Construct as copy of specified number of characters.
string (const char)
Construct from a single character.
string (Istream &)
Construct from Istream.
size_type count (const char) const
Count and return the number of a given character in the string.
bool match (const std::string &) const
True when strings match literally.
string & replace (const string &oldStr, const string &newStr, size_type start=0)
Replace first occurence of sub-string oldStr with newStr.
string & replaceAll (const string &oldStr, const string &newStr, size_type start=0)
Replace all occurences of sub-string oldStr with newStr.
string & expand (const bool allowEmpty=false)
Expand initial tildes and all occurences of environment variables.
bool removeRepeated (const char)
Remove repeated characters returning true if string changed.
string removeRepeated (const char) const
Return string with repeated characters removed.
bool removeTrailing (const char)
Remove trailing character returning true if string changed.
string removeTrailing (const char) const
Return string with trailing character removed.
string operator() (const size_type i, const size_type n) const
Return the sub-string from the i-th character for n characters.
string operator() (const size_type n) const
Return the sub-string from the first character for n characters.
template<class String >
Foam::string quotemeta (const string &str, const char quote)
Static Public Member Functions
template<class String >
static bool valid (const string &)
Is this string type valid?
template<class String >
static bool meta (const string &, const char quote='\\')
Does this string have particular meta-characters?
template<class String >
static bool stripInvalid (string &)
Strip invalid characters from the given string.
template<class String >
static String validate (const string &)
Return a valid String from the given string.
template<class String >
static string quotemeta (const string &, const char quote='\\')
Return a String with quoted meta-characters from the given string.
Static Public Attributes
static const char *const typeName = "string"
static int debug
static const string null
An empty string.
Friends
Istream & operator>> (Istream &, string &)
Ostream & operator<< (Ostream &, const string &)
Detailed Description
A class for handling character strings derived from std::string.
Strings may contain any characters and therefore are delimited by quotes for IO : "any list of characters".
Used as a base class for word and fileName.
See also
Foam::findEtcFile() for information about the site/user OpenFOAM configuration directory
Source files
string.H
string.C
stringIO.C
Definition at line 74 of file string.H.
Constructor & Destructor Documentation
string() [1/6]
string () inline
Construct null.
Definition at line 30 of file stringI.H.
Referenced by fileName::caseName(), and string::hash::hash().
string() [2/6]
string (const std::string & str) inline
Construct from std::string.
Definition at line 34 of file stringI.H.
string() [3/6]
string (const char * str) inline
Construct as copy of character array.
Definition at line 41 of file stringI.H.
string() [4/6]
string (const char * str, const size_type len) inline
Construct as copy of specified number of characters.
Definition at line 48 of file stringI.H.
string() [5/6]
string (const char c) inline
Construct from a single character.
Definition at line 55 of file stringI.H.
string() [6/6]
string (Istream & is)
Construct from Istream.
Definition at line 31 of file stringIO.C.
Member Function Documentation
count()
Foam::string::size_type count (const char c) const
Count and return the number of a given character in the string.
Definition at line 39 of file string.C.
References string::replace().
Referenced by string::hash::hash(), OSstream::write(), and OSstream::writeQuoted().
valid()
bool valid (const string & str) inline static
Is this string type valid?
Definition at line 64 of file stringI.H.
Referenced by string::hash::hash().
meta()
bool meta (const string & str, const char quote = '\\') inline static
Does this string have particular meta-characters?
The meta characters can be optionally quoted.
Definition at line 112 of file stringI.H.
Referenced by string::hash::hash().
stripInvalid()
bool stripInvalid (string & str) inline static
Strip invalid characters from the given string.
Definition at line 78 of file stringI.H.
References Foam::constant::universal::c.
Referenced by string::hash::hash().
validate()
String validate (const string & str) inline static
Return a valid String from the given string.
Definition at line 172 of file stringI.H.
Referenced by string::hash::hash().
quotemeta() [1/2]
static string quotemeta (const string & , const char quote = '\\') inline static
Return a String with quoted meta-characters from the given string.
Referenced by string::hash::hash().
match()
bool match (const std::string & str) const inline
True when strings match literally.
Definition at line 179 of file stringI.H.
Referenced by solutionControl::applyToField(), and string::hash::hash().
replace()
Foam::string & replace (const string & oldStr, const string & newStr, size_type start = 0)
Replace first occurence of sub-string oldStr with newStr.
starting at start
Definition at line 56 of file string.C.
References string::replaceAll().
Referenced by fileName::caseName(), string::count(), string::hash::hash(), objectRegistry::rename(), cellMotionFvPatchField< Type >::updateCoeffs(), and graph::wordify().
replaceAll()
Foam::string & replaceAll (const string & oldStr, const string & newStr, size_type start = 0)
Replace all occurences of sub-string oldStr with newStr.
starting at start
Definition at line 74 of file string.C.
Referenced by argList::displayDoc(), string::hash::hash(), error::operator()(), Foam::printSourceFileAndLine(), and string::replace().
expand()
Foam::string & expand (const bool allowEmpty = false)
Expand initial tildes and all occurences of environment variables.
Expansion includes:
environment variables
"$VAR", "${VAR}"
current directory
leading "./" : the current directory
tilde expansion
leading "~/" : home directory
leading "~user" : home directory for specified user
leading "~OpenFOAM" : site/user OpenFOAM configuration directory
Any unknown entries are removed silently if allowEmpty is true
See also
Foam::findEtcFile
Definition at line 95 of file string.C.
References Foam::stringOps::inplaceExpand().
Referenced by argList::displayDoc(), string::hash::hash(), and TableFile< Type >::TableFile().
removeRepeated() [1/2]
bool removeRepeated (const char character)
Remove repeated characters returning true if string changed.
Definition at line 102 of file string.C.
References Foam::constant::universal::c, and resize().
Referenced by string::hash::hash(), and string::removeRepeated().
removeRepeated() [2/2]
Foam::string removeRepeated (const char character) const
Return string with repeated characters removed.
Definition at line 140 of file string.C.
References string::removeRepeated().
removeTrailing() [1/2]
bool removeTrailing (const char character)
Remove trailing character returning true if string changed.
Definition at line 148 of file string.C.
References resize().
Referenced by string::hash::hash(), and string::removeTrailing().
removeTrailing() [2/2]
Foam::string removeTrailing (const char character) const
Return string with trailing character removed.
Definition at line 163 of file string.C.
References string::removeTrailing().
operator()() [1/2]
Foam::string operator() (const size_type i, const size_type n) const inline
Return the sub-string from the i-th character for n characters.
Definition at line 189 of file stringI.H.
References n.
operator()() [2/2]
Foam::string operator() (const size_type n) const inline
Return the sub-string from the first character for n characters.
Definition at line 198 of file stringI.H.
quotemeta() [2/2]
Foam::string quotemeta (const string & str, const char quote) inline
Definition at line 136 of file stringI.H.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , string &) friend
Referenced by string::hash::hash().
operator<<
Ostream& operator<< (Ostream & , const string &) friend
Referenced by string::hash::hash().
Member Data Documentation
typeName
const char *const typeName = "string" static
Definition at line 82 of file string.H.
Referenced by token::stringToken().
debug
int debug static
Definition at line 83 of file string.H.
null
const Foam::string null static
An empty string.
Definition at line 86 of file string.H.
Referenced by Foam::domainName(), token::stringToken(), and Foam::userName().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/string/string.H
src/OpenFOAM/primitives/strings/string/string.C
src/OpenFOAM/primitives/strings/string/stringI.H
src/OpenFOAM/primitives/strings/string/stringIO.C