OpenFOAM: subModelBase Class Reference
subModelBase Class Reference
Base class for generic sub-models requiring to be read from dictionary. Provides a mechanism to read and write properties from a dictionary to enable clean re-starts. Used by, e.g. clou dsub-models.
Public Member Functions
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
virtual bool writeTime () const
Flag to indicate when to write a property.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Member Functions
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
Base class for generic sub-models requiring to be read from dictionary. Provides a mechanism to read and write properties from a dictionary to enable clean re-starts. Used by, e.g. clou dsub-models.
Base class for surface film sub-models.
Source files
subModelBase.H
subModelBase.C
Source files
filmSubModelBase.H
filmSubModelBaseI.H
filmSubModelBase.C
Definition at line 51 of file subModelBase.H.
Constructor & Destructor Documentation
subModelBase() [1/4]
subModelBase (dictionary & properties)
Construct null.
Definition at line 38 of file subModelBase.C.
Referenced by subModelBase::subModelBase().
subModelBase() [2/4]
subModelBase (dictionary & properties, const dictionary & dict, const word & baseName, const word & modelType, const word & dictExt = "Coeffs")
Construct from components without name.
Definition at line 50 of file subModelBase.C.
References subModelBase::subModelBase().
subModelBase() [3/4]
subModelBase (const word & modelName, dictionary & properties, const dictionary & dict, const word & baseName, const word & modelType)
Construct from components with name.
Definition at line 68 of file subModelBase.C.
subModelBase() [4/4]
subModelBase (const subModelBase & smb)
Construct as copy.
Definition at line 85 of file subModelBase.C.
~subModelBase()
~subModelBase () virtual
Destructor.
Definition at line 98 of file subModelBase.C.
Member Function Documentation
inLine()
bool inLine () const protected
Flag to indicate whether data is/was read in-line.
modelName()
const Foam::word & modelName () const
Return const access to the name of the sub-model.
Definition at line 104 of file subModelBase.C.
References subModelBase::modelName_.
Referenced by CloudFunctionObject< CloudType >::CloudFunctionObject(), and InjectionModel< CloudType >::info().
dict()
const Foam::dictionary & dict () const
Return const access to the cloud dictionary.
Definition at line 110 of file subModelBase.C.
References subModelBase::dict_.
Referenced by constantFilmThermo::thermoData::thermoData().
baseName()
const Foam::word & baseName () const
Return const access to the base name of the sub-model.
Definition at line 116 of file subModelBase.C.
References subModelBase::baseName_.
modelType()
const Foam::word & modelType () const
Return const access to the sub-model type.
Definition at line 122 of file subModelBase.C.
References subModelBase::modelType_.
Referenced by filmSubModelBase::filmType().
coeffDict()
const Foam::dictionary & coeffDict () const
Return const access to the coefficients dictionary.
Definition at line 128 of file subModelBase.C.
References subModelBase::coeffDict_.
Referenced by InjectionModel< CloudType >::InjectionModel().
properties()
const Foam::dictionary & properties () const
Return const access to the properties dictionary.
Definition at line 134 of file subModelBase.C.
References subModelBase::properties_.
Referenced by LiquidEvaporation< CloudType >::dh(), and LiquidEvaporationBoil< CloudType >::dh().
defaultCoeffs()
bool defaultCoeffs (const bool printMsg) const virtual
Returns true if defaultCoeffs is true and outputs on printMsg.
Definition at line 140 of file subModelBase.C.
References subModelBase::coeffDict_, Foam::decrIndent(), Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::Info, and dictionary::lookupOrDefault().
active()
bool active () const virtual
Return the model 'active' status - default active = true.
Reimplemented in MultiInteraction< CloudType >, NoSurfaceFilm< CloudType >, NoDamping< CloudType >, NoPacking< CloudType >, NoCollision< CloudType >, NoStochasticCollision< CloudType >, noPhaseChange, NoIsotropy< CloudType >, NoInjection< CloudType >, NoDispersion< CloudType >, NoInteraction< CloudType >, NoDevolatilisation< CloudType >, NoHeatTransfer< CloudType >, NoPhaseChange< CloudType >, NoSurfaceReaction< CloudType >, NoAtomization< CloudType >, and NoBreakup< CloudType >.
Definition at line 154 of file subModelBase.C.
Referenced by ReactingParcel< ParcelType >::calcPhaseChange(), phaseChangeModel::correct(), InjectionModel< CloudType >::inject(), InjectionModel< CloudType >::injectSteadyState(), filmSubModelBase::writeTime(), and subModelBase::writeTime().
cacheFields()
void cacheFields (const bool store) virtual
Cache dependant sub-model fields.
Reimplemented in Explicit< CloudType >, DispersionRASModel< CloudType >, Implicit< CloudType >, Relaxation< CloudType >, and GradientDispersionRAS< CloudType >.
Definition at line 160 of file subModelBase.C.
writeTime()
bool writeTime () const virtual
Flag to indicate when to write a property.
Reimplemented in CloudSubModelBase< CloudType >, CloudSubModelBase< Foam::DSMCCloud >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< CloudType > >, CloudSubModelBase< Foam::SprayCloud< CloudType > >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, CloudSubModelBase< Foam::MPPICCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingCloud< CloudType > >, CloudSubModelBase< Foam::ThermoCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::KinematicCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< CloudType > >, CloudSubModelBase< Foam::KinematicCloud< CloudType > >, CloudSubModelBase< Foam::MPPICCloud< CloudType > >, CloudSubModelBase< Foam::CollidingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::SprayCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< CloudType > >, CloudSubModelBase< Foam::ReactingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >, and filmSubModelBase.
Definition at line 164 of file subModelBase.C.
References subModelBase::active().
getBaseProperty() [1/2]
Type getBaseProperty (const word & entryName, const Type & defaultValue = pTraits<Type>::zero) const
Retrieve generic property from the base model.
Definition at line 30 of file subModelBaseTemplates.C.
References dictionary::readIfPresent(), and dictionary::subDict().
Referenced by injectionModelList::info().
getBaseProperty() [2/2]
void getBaseProperty (const word & entryName, Type & value) const
Retrieve generic property from the base model.
Definition at line 49 of file subModelBaseTemplates.C.
References dictionary::readIfPresent(), subModelBase::setBaseProperty(), and dictionary::subDict().
setBaseProperty()
void setBaseProperty (const word & entryName, const Type & value)
Add generic property to the base model.
Definition at line 64 of file subModelBaseTemplates.C.
References dictionary::add(), subModelBase::getModelProperty(), and dictionary::subDict().
Referenced by subModelBase::getBaseProperty(), and injectionModelList::info().
getModelProperty() [1/2]
void getModelProperty (const word & entryName, Type & value) const
Retrieve generic property from the sub-model.
Definition at line 84 of file subModelBaseTemplates.C.
References dictionary::found(), dictionary::readIfPresent(), and dictionary::subDict().
Referenced by subModelBase::setBaseProperty().
getModelProperty() [2/2]
Type getModelProperty (const word & entryName, const Type & defaultValue = pTraits<Type>::zero) const
Retrieve generic property from the sub-model.
Definition at line 107 of file subModelBaseTemplates.C.
References subModelBase::setModelProperty().
setModelProperty()
void setModelProperty (const word & entryName, const Type & value)
Add generic property to the sub-model.
Definition at line 120 of file subModelBaseTemplates.C.
References dictionary::add(), dictionary::found(), and dictionary::subDict().
Referenced by subModelBase::getModelProperty(), and InjectionModel< CloudType >::info().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in DispersionRASModel< CloudType >, CloudSubModelBase< CloudType >, CloudSubModelBase< Foam::DSMCCloud >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< CloudType > >, CloudSubModelBase< Foam::SprayCloud< CloudType > >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, CloudSubModelBase< Foam::MPPICCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingCloud< CloudType > >, CloudSubModelBase< Foam::ThermoCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::KinematicCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< CloudType > >, CloudSubModelBase< Foam::KinematicCloud< CloudType > >, CloudSubModelBase< Foam::MPPICCloud< CloudType > >, CloudSubModelBase< Foam::CollidingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::SprayCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< CloudType > >, CloudSubModelBase< Foam::ReactingCloud< Foam::DSMCCloud > >, and CloudSubModelBase< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >.
Definition at line 170 of file subModelBase.C.
References subModelBase::coeffDict_.
Member Data Documentation
modelName_
const word modelName_ protected
Name of the sub-model.
Definition at line 64 of file subModelBase.H.
Referenced by subModelBase::modelName().
properties_
dictionary& properties_ protected
Reference to properties dictionary e.g. for restart.
Definition at line 67 of file subModelBase.H.
Referenced by subModelBase::properties().
dict_
const dictionary dict_ protected
Copy of dictionary used during construction.
Definition at line 70 of file subModelBase.H.
Referenced by subModelBase::dict().
baseName_
const word baseName_ protected
Name of the sub-model base class.
Definition at line 73 of file subModelBase.H.
Referenced by subModelBase::baseName().
modelType_
const word modelType_ protected
Type of the sub-model.
Definition at line 76 of file subModelBase.H.
Referenced by subModelBase::modelType().
coeffDict_
const dictionary coeffDict_ protected
Coefficients dictionary.
Definition at line 79 of file subModelBase.H.
Referenced by subModelBase::coeffDict(), constantFilmThermo::Cp(), constantFilmThermo::D(), subModelBase::defaultCoeffs(), constantFilmThermo::hl(), constantFilmThermo::kappa(), liquidFilmThermo::liquidFilmThermo(), constantFilmThermo::mu(), constantFilmThermo::pv(), constantFilmThermo::rho(), constantFilmThermo::sigma(), constantFilmThermo::Tb(), constantFilmThermo::W(), and subModelBase::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/subModelBase/subModelBase.H
src/OpenFOAM/primitives/subModelBase/subModelBase.C
src/OpenFOAM/primitives/subModelBase/subModelBaseTemplates.C