OpenFOAM: wordRe Class Reference
wordRe Class Reference
A wordRe is a word, but can also have a regular expression for matching words.
Public Types
enum compOption {
LITERAL = 0, DETECT = 1, REGEXP = 2, NOCASE = 4,
DETECT_NOCASE = DETECT | NOCASE, REGEXP_NOCASE = REGEXP | NOCASE
}
Enumeration with compile options.
Public Member Functions
wordRe ()
Construct null.
wordRe (const wordRe &)
Construct as copy.
wordRe (const keyType &)
Construct from keyType.
wordRe (const keyType &, const compOption)
Construct from keyType.
wordRe (const word &)
Construct as copy of word.
wordRe (const char *, const compOption=LITERAL)
Construct as copy of character array.
wordRe (const string &, const compOption=LITERAL)
Construct as copy of string.
wordRe (const std::string &, const compOption=LITERAL)
Construct as copy of std::string.
wordRe (Istream &)
Construct from Istream.
bool isPattern () const
Should be treated as a match rather than a literal string?
bool compile () const
Compile the regular expression.
bool compile (const compOption) const
Possibly compile the regular expression, with greater control.
bool recompile () const
Recompile an existing regular expression.
void uncompile (const bool doStripInvalid=false) const
Frees precompiled regular expression, making wordRe a literal.
void set (const std::string &, const compOption=DETECT)
Copy string, auto-test for regular expression or other options.
void set (const char *, const compOption=DETECT)
Copy string, auto-test for regular expression or other options.
void clear ()
Clear string and precompiled regular expression.
bool match (const std::string &, bool literalMatch=false) const
Smart match as regular expression or as a string.
string quotemeta () const
Return a string with quoted meta-characters.
Ostream & info (Ostream &) const
Output some basic info.
void operator= (const wordRe &)
Assign copy.
void operator= (const word &)
Copy word, never a regular expression.
void operator= (const keyType &)
Copy keyType, auto-test for regular expression.
void operator= (const string &)
Copy string, auto-test for regular expression.
void operator= (const std::string &)
Copy string, auto-test for regular expression.
void operator= (const char *)
Copy string, auto-test for regular expression.
Public Member Functions inherited from word
word ()
Construct null.
word (const word &)
Construct as copy.
word (const char *, const bool doStripInvalid=true)
Construct as copy of character array.
word (const char *, const size_type, const bool doStripInvalid)
Construct as copy with a maximum number of characters.
word (const string &, const bool doStripInvalid=true)
Construct as copy of string.
word (const std::string &, const bool doStripInvalid=true)
Construct as copy of std::string.
word (Istream &)
Construct from Istream.
void operator= (const word &)
void operator= (const string &)
void operator= (const std::string &)
void operator= (const char *)
Public Member Functions inherited from string
string ()
Construct null.
string (const std::string &)
Construct from std::string.
string (const char *)
Construct as copy of character array.
string (const char *, const size_type)
Construct as copy of specified number of characters.
string (const char)
Construct from a single character.
string (Istream &)
Construct from Istream.
size_type count (const char) const
Count and return the number of a given character in the string.
bool match (const std::string &) const
True when strings match literally.
string & replace (const string &oldStr, const string &newStr, size_type start=0)
Replace first occurence of sub-string oldStr with newStr.
string & replaceAll (const string &oldStr, const string &newStr, size_type start=0)
Replace all occurences of sub-string oldStr with newStr.
string & expand (const bool allowEmpty=false)
Expand initial tildes and all occurences of environment variables.
bool removeRepeated (const char)
Remove repeated characters returning true if string changed.
string removeRepeated (const char) const
Return string with repeated characters removed.
bool removeTrailing (const char)
Remove trailing character returning true if string changed.
string removeTrailing (const char) const
Return string with trailing character removed.
string operator() (const size_type i, const size_type n) const
Return the sub-string from the i-th character for n characters.
string operator() (const size_type n) const
Return the sub-string from the first character for n characters.
template<class String >
Foam::string quotemeta (const string &str, const char quote)
Static Public Member Functions
static bool meta (char)
Is this a meta character?
static bool isPattern (const string &)
Test string for regular expression meta characters.
Static Public Member Functions inherited from word
static bool valid (char)
Is this character valid for a word.
Static Public Member Functions inherited from string
template<class String >
static bool valid (const string &)
Is this string type valid?
template<class String >
static bool meta (const string &, const char quote='\\')
Does this string have particular meta-characters?
template<class String >
static bool stripInvalid (string &)
Strip invalid characters from the given string.
template<class String >
static String validate (const string &)
Return a valid String from the given string.
template<class String >
static string quotemeta (const string &, const char quote='\\')
Return a String with quoted meta-characters from the given string.
Static Public Attributes
static const wordRe null
An empty wordRe.
Static Public Attributes inherited from word
static const char *const typeName = "word"
static int debug
static const word null
An empty word.
Static Public Attributes inherited from string
static const char *const typeName = "string"
static int debug
static const string null
An empty string.
Friends
Istream & operator>> (Istream &, wordRe &)
Ostream & operator<< (Ostream &, const wordRe &)
Detailed Description
A wordRe is a word, but can also have a regular expression for matching words.
By default the constructors will generally preserve the argument as a string literal and the assignment operators will use the wordRe::DETECT compOption to scan the string for regular expression meta characters and/or invalid word characters and react accordingly.
The exceptions are when constructing/assigning from another Foam::wordRe (preserve the same type) or from a Foam::word (always literal).
Note
If the string contents are changed - eg, by the operator+=() or by string::replace(), etc - it will be necessary to use compile() or recompile() to synchronize the regular expression.
Source files
wordRe.H
wordRe.C
Definition at line 74 of file wordRe.H.
Member Enumeration Documentation
compOption
enum compOption
Enumeration with compile options.
Note that 'REGEXP' is implicit if 'NOCASE' is specified alone.
Enumerator
LITERAL
treat as a string literal
DETECT
treat as regular expression
REGEXP
detect if the string contains meta-characters
NOCASE
ignore case in regular expression
DETECT_NOCASE
REGEXP_NOCASE
Definition at line 95 of file wordRe.H.
Constructor & Destructor Documentation
wordRe() [1/9]
wordRe () inline
Construct null.
Definition at line 42 of file wordReI.H.
wordRe() [2/9]
wordRe (const wordRe & str) inline
Construct as copy.
Definition at line 49 of file wordReI.H.
References wordRe::compile(), and wordRe::isPattern().
wordRe() [3/9]
wordRe (const keyType & str) inline explicit
Construct from keyType.
Definition at line 68 of file wordReI.H.
References wordRe::compile(), and keyType::isPattern().
wordRe() [4/9]
wordRe (const keyType & str, const compOption opt) inline
Construct from keyType.
Definition at line 80 of file wordReI.H.
References wordRe::compile(), and keyType::isPattern().
wordRe() [5/9]
wordRe (const word & str) inline explicit
Construct as copy of word.
Definition at line 61 of file wordReI.H.
wordRe() [6/9]
wordRe (const char * str, const compOption opt = LITERAL) inline explicit
Construct as copy of character array.
Optionally specify how it should be treated.
Definition at line 92 of file wordReI.H.
References wordRe::compile().
wordRe() [7/9]
wordRe (const string & str, const compOption opt = LITERAL) inline explicit
Construct as copy of string.
Optionally specify how it should be treated.
Definition at line 101 of file wordReI.H.
References wordRe::compile().
wordRe() [8/9]
wordRe (const std::string & str, const compOption opt = LITERAL) inline explicit
Construct as copy of std::string.
Optionally specify how it should be treated.
Definition at line 110 of file wordReI.H.
References wordRe::compile().
wordRe() [9/9]
wordRe (Istream & is)
Construct from Istream.
Words are treated as literals, strings with an auto-test
Definition at line 37 of file wordRe.C.
Member Function Documentation
meta()
bool meta (char c) inline static
Is this a meta character?
Definition at line 28 of file wordReI.H.
References regExp::meta().
isPattern() [1/2]
bool isPattern (const string & str) inline static
Test string for regular expression meta characters.
Definition at line 34 of file wordReI.H.
Referenced by Foam::operator<<(), wordRe::operator=(), and wordRe::wordRe().
isPattern() [2/2]
bool isPattern () const inline
Should be treated as a match rather than a literal string?
Definition at line 121 of file wordReI.H.
References regExp::exists().
Referenced by wordRe::info().
compile() [1/2]
bool compile () const inline
Compile the regular expression.
Definition at line 161 of file wordReI.H.
References regExp::exists().
Referenced by wordRe::operator=(), wordRe::set(), and wordRe::wordRe().
compile() [2/2]
bool compile (const compOption opt) const inline
Possibly compile the regular expression, with greater control.
Definition at line 127 of file wordReI.H.
References regExp::clear(), wordRe::DETECT, regExp::exists(), wordRe::NOCASE, wordRe::REGEXP, and regExp::set().
recompile()
bool recompile () const inline
Recompile an existing regular expression.
Definition at line 168 of file wordReI.H.
References regExp::exists().
uncompile()
void uncompile (const bool doStripInvalid = false) const inline
Frees precompiled regular expression, making wordRe a literal.
Optionally strips invalid word characters
Definition at line 179 of file wordReI.H.
References regExp::clear(), and word::debug.
set() [1/2]
void set (const std::string & str, const compOption opt = DETECT) inline
Copy string, auto-test for regular expression or other options.
Definition at line 223 of file wordReI.H.
References wordRe::compile().
set() [2/2]
void set (const char * str, const compOption opt = DETECT) inline
Copy string, auto-test for regular expression or other options.
Definition at line 230 of file wordReI.H.
References wordRe::compile().
clear()
void clear () inline
Clear string and precompiled regular expression.
Definition at line 195 of file wordReI.H.
References clear(), and regExp::clear().
match()
bool match (const std::string & str, bool literalMatch = false) const inline
Smart match as regular expression or as a string.
Optionally force a literal match only
Definition at line 202 of file wordReI.H.
References regExp::exists(), and regExp::match().
Referenced by IOobjectList::lookup(), and objectRegistry::names().
quotemeta()
Foam::string quotemeta () const inline
Return a string with quoted meta-characters.
Definition at line 217 of file wordReI.H.
info()
Foam::Ostream & info (Ostream & os) const
Output some basic info.
Definition at line 103 of file wordRe.C.
References Ostream::flush(), and wordRe::isPattern().
operator=() [1/6]
void operator= (const wordRe & str) inline
Assign copy.
Always case sensitive
Definition at line 239 of file wordReI.H.
References regExp::clear(), wordRe::compile(), and wordRe::isPattern().
operator=() [2/6]
void operator= (const word & str) inline
Copy word, never a regular expression.
Definition at line 254 of file wordReI.H.
References regExp::clear(), and word::operator=().
operator=() [3/6]
void operator= (const keyType & str) inline
Copy keyType, auto-test for regular expression.
Always case sensitive
Definition at line 261 of file wordReI.H.
References wordRe::compile(), and keyType::isPattern().
operator=() [4/6]
void operator= (const string & str) inline
Copy string, auto-test for regular expression.
Always case sensitive
Definition at line 271 of file wordReI.H.
References wordRe::compile(), and wordRe::DETECT.
operator=() [5/6]
void operator= (const std::string & str) inline
Copy string, auto-test for regular expression.
Always case sensitive
Definition at line 278 of file wordReI.H.
References wordRe::compile(), and wordRe::DETECT.
operator=() [6/6]
void operator= (const char * str) inline
Copy string, auto-test for regular expression.
Always case sensitive
Definition at line 285 of file wordReI.H.
References wordRe::compile(), and wordRe::DETECT.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , wordRe &) friend
operator<<
Ostream& operator<< (Ostream & , const wordRe &) friend
Member Data Documentation
null
const Foam::wordRe null static
An empty wordRe.
Definition at line 88 of file wordRe.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/wordRe/wordRe.H
src/OpenFOAM/primitives/strings/wordRe/wordRe.C
src/OpenFOAM/primitives/strings/wordRe/wordReI.H