OpenFOAM: fileName Class Reference
fileName Class Reference
A class for handling file names.
Public Types
enum Type { UNDEFINED, FILE, DIRECTORY, LINK }
Enumerations to handle file types and modes.
Public Member Functions
fileName ()
Construct null.
fileName (const fileName &)
Construct as copy.
fileName (const word &)
Construct as copy of word.
fileName (const string &)
Construct as copy of string.
fileName (const std::string &)
Construct as copy of std::string.
fileName (const char *)
Construct as copy of character array.
fileName (const wordList &)
Construct by concatenating elements of wordList separated by '/'.
fileName (Istream &)
Construct from Istream.
bool clean ()
Cleanup file name.
fileName clean () const
Cleanup file name.
Type type () const
Return the file type: FILE, DIRECTORY or UNDEFINED.
bool isAbsolute () const
Return true if file name is absolute.
fileName & toAbsolute ()
Convert from relative to absolute.
word name () const
Return file name (part beyond last /)
string caseName () const
Return file name (part beyond last /), subsitute for FOAM_CASE.
word name (const bool noExt) const
Return file name, optionally without extension.
fileName path () const
Return directory path name (part before last /)
fileName lessExt () const
Return file name without extension (part before last .)
word ext () const
Return file name extension (part after last .)
wordList components (const char delimiter='/') const
Return path components as wordList.
word component (const size_type, const char delimiter='/') const
Return a single component of the path.
void operator= (const fileName &)
void operator= (const word &)
void operator= (const string &)
void operator= (const std::string &)
void operator= (const char *)
Public Member Functions inherited from string
string ()
Construct null.
string (const std::string &)
Construct from std::string.
string (const char *)
Construct as copy of character array.
string (const char *, const size_type)
Construct as copy of specified number of characters.
string (const char)
Construct from a single character.
string (Istream &)
Construct from Istream.
size_type count (const char) const
Count and return the number of a given character in the string.
bool match (const std::string &) const
True when strings match literally.
string & replace (const string &oldStr, const string &newStr, size_type start=0)
Replace first occurence of sub-string oldStr with newStr.
string & replaceAll (const string &oldStr, const string &newStr, size_type start=0)
Replace all occurences of sub-string oldStr with newStr.
string & expand (const bool allowEmpty=false)
Expand initial tildes and all occurences of environment variables.
bool removeRepeated (const char)
Remove repeated characters returning true if string changed.
string removeRepeated (const char) const
Return string with repeated characters removed.
bool removeTrailing (const char)
Remove trailing character returning true if string changed.
string removeTrailing (const char) const
Return string with trailing character removed.
string operator() (const size_type i, const size_type n) const
Return the sub-string from the i-th character for n characters.
string operator() (const size_type n) const
Return the sub-string from the first character for n characters.
template<class String >
Foam::string quotemeta (const string &str, const char quote)
Static Public Member Functions
static bool valid (char)
Is this character valid for a fileName?
Static Public Member Functions inherited from string
template<class String >
static bool valid (const string &)
Is this string type valid?
template<class String >
static bool meta (const string &, const char quote='\\')
Does this string have particular meta-characters?
template<class String >
static bool stripInvalid (string &)
Strip invalid characters from the given string.
template<class String >
static String validate (const string &)
Return a valid String from the given string.
template<class String >
static string quotemeta (const string &, const char quote='\\')
Return a String with quoted meta-characters from the given string.
Static Public Attributes
static const char *const typeName = "fileName"
static int debug
static const fileName null
An empty fileName.
Static Public Attributes inherited from string
static const char *const typeName = "string"
static int debug
static const string null
An empty string.
Friends
Istream & operator>> (Istream &, fileName &)
Ostream & operator<< (Ostream &, const fileName &)
Detailed Description
A class for handling file names.
A fileName is a string of characters without whitespace or quotes. A fileName can be
constructed from a char*, a string or a word
concatenated by adding a '/' separator
decomposed into the path, name or component list
interrogated for type and access mode
The string::expand() method expands environment variables, etc,
Source files
fileName.H
fileName.C
fileNameIO.C
Definition at line 69 of file fileName.H.
Member Enumeration Documentation
Type
enum Type
Enumerations to handle file types and modes.
Enumerator
UNDEFINED
FILE
DIRECTORY
LINK
Definition at line 82 of file fileName.H.
Constructor & Destructor Documentation
fileName() [1/8]
fileName () inline
Construct null.
Definition at line 52 of file fileNameI.H.
Referenced by Foam::operator/().
fileName() [2/8]
fileName (const fileName & fn) inline
Construct as copy.
Definition at line 57 of file fileNameI.H.
fileName() [3/8]
fileName (const word & w) inline
Construct as copy of word.
Definition at line 62 of file fileNameI.H.
fileName() [4/8]
fileName (const string & str) inline
Construct as copy of string.
Definition at line 68 of file fileNameI.H.
fileName() [5/8]
fileName (const std::string & str) inline
Construct as copy of std::string.
Definition at line 76 of file fileNameI.H.
fileName() [6/8]
fileName (const char * str) inline
Construct as copy of character array.
Definition at line 84 of file fileNameI.H.
fileName() [7/8]
fileName (const wordList & lst) explicit
Construct by concatenating elements of wordList separated by '/'.
Definition at line 40 of file fileName.C.
References forAll, and fileName::operator=().
fileName() [8/8]
fileName (Istream & is)
Construct from Istream.
Definition at line 31 of file fileNameIO.C.
Member Function Documentation
valid()
bool valid (char c) inline static
Is this character valid for a fileName?
Definition at line 94 of file fileNameI.H.
References Foam::isspace().
clean() [1/2]
bool clean ()
Cleanup file name.
Removes repeated slashes /abc////def –> /abc/def
Removes '/./' /abc/def/./ghi/. –> /abc/def/./ghi abc/def/./ –> abc/def
Removes '/../' /abc/def/../ghi/jkl/nmo/.. –> /abc/ghi/jkl abc/../def/ghi/../jkl –> abc/../def/jkl
Removes trailing '/'
Definition at line 77 of file fileName.C.
References Foam::constant::universal::c, Foam::constant::physicoChemical::c1, and resize().
Referenced by fileName::clean(), argList::postProcess(), and fileName::toAbsolute().
clean() [2/2]
Foam::fileName clean () const
Cleanup file name.
eg, remove repeated slashes, etc.
Definition at line 171 of file fileName.C.
References fileName::clean().
type()
Foam::fileName::Type type () const
Return the file type: FILE, DIRECTORY or UNDEFINED.
Definition at line 51 of file fileName.C.
References Foam::type().
Referenced by Foam::cp(), Foam::mv(), and Foam::rmDir().
isAbsolute()
bool isAbsolute () const
Return true if file name is absolute.
Definition at line 57 of file fileName.C.
Referenced by chemkinReader::chemkinReader(), IOobject::fileNameComponents(), includeEntry::includeFileName(), Foam::ln(), argList::postProcess(), and fileName::toAbsolute().
toAbsolute()
Foam::fileName & toAbsolute ()
Convert from relative to absolute.
Definition at line 63 of file fileName.C.
References fileName::clean(), Foam::cwd(), f(), and fileName::isAbsolute().
name() [1/2]
Foam::word name () const
Return file name (part beyond last /)
Behaviour compared to /usr/bin/basename: Input name() basename ----- ------ -------- "foo" "foo" "foo" "/foo" "foo" "foo" "foo/bar" "bar" "bar" "/foo/bar" "bar" "bar" "/foo/bar/" "" "bar"
Definition at line 179 of file fileName.C.
Referenced by fileMonitorWatcher::addWatch(), argList::argList(), cyclicPolyPatch::calcTransforms(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), timeVaryingMappedFixedValueFvPatchField< Type >::checkTable(), dynamicCode::copyOrCreateFiles(), Foam::cp(), dictionaryName::dictName(), dynamicCode::libraryBaseName(), fvMeshAdder::MapDimFields(), fvMeshAdder::MapSurfaceFields(), Foam::mv(), fileName::name(), processorPolyPatch::order(), argList::postProcess(), probes::prepare(), extendedEdgeMeshFormat::read(), edgeMeshFormat::read(), triSurface::triSurfInstance(), timeVaryingMappedFixedValuePointPatchField< Type >::updateCoeffs(), timeVaryingMappedFixedValueFvPatchField< Type >::updateCoeffs(), ensightSetWriter< Type >::write(), OBJsurfaceFormat< Face >::write(), OBJedgeFormat::write(), ensightSurfaceWriter::write(), streamLine::write(), wallBoundedStreamLine::write(), STARCDsurfaceFormatCore::writeCase(), and STARCDedgeFormat::writeCase().
caseName()
Foam::string caseName () const
Return file name (part beyond last /), subsitute for FOAM_CASE.
Definition at line 194 of file fileName.C.
References Foam::getEnv(), string::replace(), and string::string().
Referenced by IOobject::caseName().
name() [2/2]
Foam::word name (const bool noExt) const
Return file name, optionally without extension.
Definition at line 213 of file fileName.C.
References Foam::dot(), and fileName::name().
path()
Foam::fileName path () const
Return directory path name (part before last /)
Behaviour compared to /usr/bin/dirname: input path() dirname ----- ------ ------- "foo" "." "." "/foo" "/" "foo" "foo/bar" "foo" "foo" "/foo/bar" "/foo" "/foo" "/foo/bar/" "/foo/bar/" "/foo"
Definition at line 249 of file fileName.C.
Referenced by fileMonitorWatcher::addWatch(), timeVaryingMappedFixedValuePointPatchField< Type >::checkTable(), timeVaryingMappedFixedValueFvPatchField< Type >::checkTable(), chemkinReader::chemkinReader(), dynamicCode::copyOrCreateFiles(), Foam::cp(), dynamicCode::createMakeFiles(), dynamicCode::createMakeOptions(), includeEntry::execute(), isoSurface::isoSurface(), Foam::mkDir(), argList::postProcess(), probes::prepare(), extendedEdgeMeshFormat::read(), edgeMeshFormat::read(), Foam::search(), streamLine::write(), wallBoundedStreamLine::write(), dynamicCode::writeDigest(), triSurfaceMesh::writeObject(), and distributedTriSurfaceMesh::writeObject().
lessExt()
Foam::fileName lessExt () const
Return file name without extension (part before last .)
Definition at line 268 of file fileName.C.
Referenced by edgeMesh::canRead(), UnsortedMeshedSurface< Face >::canRead(), MeshedSurface< Foam::face >::canRead(), extendedEdgeMesh::canRead(), triSurface::checkEdges(), edgeMesh::New(), UnsortedMeshedSurface< Face >::New(), MeshedSurface< Foam::face >::New(), extendedEdgeMesh::New(), STARCDsurfaceFormat< Face >::read(), STARCDedgeFormat::read(), edgeMesh::read(), UnsortedMeshedSurface< Face >::read(), MeshedSurface< Foam::face >::read(), extendedEdgeMesh::read(), Foam::readDir(), ensightSetWriter< Type >::write(), OBJsurfaceFormat< Face >::write(), OBJedgeFormat::write(), STARCDsurfaceFormat< Face >::write(), STARCDedgeFormat::write(), STARCDsurfaceFormatCore::writeCase(), and STARCDedgeFormat::writeCase().
ext()
Foam::word ext () const
Return file name extension (part after last .)
Definition at line 283 of file fileName.C.
References word::null.
Referenced by edgeMesh::canRead(), UnsortedMeshedSurface< Face >::canRead(), MeshedSurface< Foam::face >::canRead(), extendedEdgeMesh::canRead(), MeshedSurfaceProxy< Face >::canWriteType(), triSurface::checkEdges(), edgeMesh::New(), UnsortedMeshedSurface< Face >::New(), MeshedSurface< Foam::face >::New(), extendedEdgeMesh::New(), Foam::printSourceFileAndLine(), edgeMesh::read(), UnsortedMeshedSurface< Face >::read(), MeshedSurface< Foam::face >::read(), extendedEdgeMesh::read(), Foam::readDir(), triSurface::triSurface(), STLsurfaceFormat< Face >::write(), edgeMesh::write(), UnsortedMeshedSurface< Face >::write(), MeshedSurface< Foam::face >::write(), and triSurface::write().
components()
Foam::wordList components (const char delimiter = '/') const
Return path components as wordList.
Behaviour: Input components() ----- ------ "foo" 1("foo") "/foo" 1("foo") "foo/bar" 2("foo", "bar") "/foo/bar" 2("foo", "bar") "/foo/bar/" 2("foo", "bar")
Definition at line 298 of file fileName.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), fileName::component(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::xfer().
Referenced by fileName::component(), and Foam::cp().
component()
Foam::word component (const size_type cmpt, const char delimiter = '/') const
Return a single component of the path.
Definition at line 326 of file fileName.C.
References fileName::components().
Referenced by fileName::components(), and Foam::cp().
operator=() [1/5]
void operator= (const fileName & str)
Definition at line 337 of file fileName.C.
Referenced by fileName::fileName().
operator=() [2/5]
void operator= (const word & str)
Definition at line 343 of file fileName.C.
operator=() [3/5]
void operator= (const string & str)
Definition at line 349 of file fileName.C.
operator=() [4/5]
void operator= (const std::string & str)
Definition at line 356 of file fileName.C.
operator=() [5/5]
void operator= (const char * str)
Definition at line 363 of file fileName.C.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , fileName &) friend
operator<<
Ostream& operator<< (Ostream & , const fileName &) friend
Member Data Documentation
typeName
const char *const typeName = "fileName" static
Definition at line 93 of file fileName.H.
debug
int debug static
Definition at line 94 of file fileName.H.
null
const Foam::fileName null static
An empty fileName.
Definition at line 97 of file fileName.H.
Referenced by chemkinReader::chemkinReader(), dlLibraryTable::close(), Foam::cwd(), Time::dbDir(), IOobject::filePath(), functionObjectList::findDict(), Foam::home(), meshWriter::noBoundary(), profileModel::readFromFile(), bladeModel::readFromFile(), functionObjectList::readFunctionObject(), and Foam::search().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/fileName/fileName.H
src/OpenFOAM/primitives/strings/fileName/fileName.C
src/OpenFOAM/primitives/strings/fileName/fileNameI.H
src/OpenFOAM/primitives/strings/fileName/fileNameIO.C