OpenFOAM: SymmTensor2D< Cmpt > Class Template Reference
SymmTensor2D< Cmpt > Class Template Reference
Templated 2D symmetric tensor derived from VectorSpace adding construction from 4 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Public Types
enum components { XX, XY, YY }
Component labeling enumeration.
typedef SymmTensor2D< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
typedef VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
Public Member Functions
SymmTensor2D ()
Construct null.
SymmTensor2D (const Foam::zero)
Construct initialized to zero.
SymmTensor2D (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 > &)
Construct given VectorSpace.
SymmTensor2D (const SphericalTensor2D< Cmpt > &)
Construct given SphericalTensor.
SymmTensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyy)
Construct given the three components.
SymmTensor2D (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & yy () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & yy ()
const SymmTensor2D< Cmpt > & T () const
Transpose.
void operator= (const SphericalTensor2D< Cmpt > &)
Construct given SphericalTensor2D.
Public Member Functions inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const ConstBlock< SubVector, BStart > block () const
const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const direction rank = 2
Rank of SymmTensor2D is 2.
static const SymmTensor2D I
Static Public Attributes inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
static const direction dim
Dimensionality of space.
static const direction nComponents
Number of components in this vector space.
static const direction mRows
static const direction nCols
static const char *const typeName
static const char *const componentNames []
static const SymmTensor2D< Cmpt > zero
static const SymmTensor2D< Cmpt > one
static const SymmTensor2D< Cmpt > max
static const SymmTensor2D< Cmpt > min
static const SymmTensor2D< Cmpt > rootMax
static const SymmTensor2D< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static SymmTensor2D< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SymmTensor2D< Cmpt >
Templated 2D symmetric tensor derived from VectorSpace adding construction from 4 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Source files
SymmTensor2D.H
SymmTensor2DI.H
Definition at line 53 of file SymmTensor2D.H.
Member Typedef Documentation
labelType
typedef SymmTensor2D<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 61 of file SymmTensor2D.H.
Member Enumeration Documentation
components
enum components
Component labeling enumeration.
Enumerator
XX
XY
YY
Definition at line 76 of file SymmTensor2D.H.
Constructor & Destructor Documentation
SymmTensor2D() [1/6]
SymmTensor2D () inline
Construct null.
Definition at line 32 of file SymmTensor2DI.H.
Referenced by SymmTensor2D< Cmpt >::SymmTensor2D().
SymmTensor2D() [2/6]
SymmTensor2D (const Foam::zero) inline
Construct initialized to zero.
Definition at line 37 of file SymmTensor2DI.H.
References SymmTensor2D< Cmpt >::SymmTensor2D().
SymmTensor2D() [3/6]
SymmTensor2D (const VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 > & vs) inline
Construct given VectorSpace.
Definition at line 45 of file SymmTensor2DI.H.
SymmTensor2D() [4/6]
SymmTensor2D (const SphericalTensor2D< Cmpt > & st) inline
Construct given SphericalTensor.
Definition at line 54 of file SymmTensor2DI.H.
References SphericalTensor2D< Cmpt >::ii(), SymmTensor2D< Cmpt >::SymmTensor2D(), VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, SymmTensor2D< Cmpt >::XX, SymmTensor2D< Cmpt >::XY, and SymmTensor2D< Cmpt >::YY.
SymmTensor2D() [5/6]
SymmTensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyy) inline
Construct given the three components.
Definition at line 63 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, SymmTensor2D< Cmpt >::XX, SymmTensor2D< Cmpt >::XY, and SymmTensor2D< Cmpt >::YY.
SymmTensor2D() [6/6]
SymmTensor2D (Istream & is) inline
Construct from Istream.
Definition at line 74 of file SymmTensor2DI.H.
Member Function Documentation
xx() [1/2]
const Cmpt & xx () const inline
Definition at line 83 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XX.
Referenced by Foam::cof(), Foam::det(), Foam::innerSqr(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Tensor2D< Cmpt >::operator=(), Tensor2D< Cmpt >::Tensor2D(), and Foam::tr().
xy() [1/2]
const Cmpt & xy () const inline
Definition at line 89 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XY.
Referenced by Foam::cof(), Foam::det(), Foam::innerSqr(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Tensor2D< Cmpt >::operator=(), and Tensor2D< Cmpt >::Tensor2D().
yy() [1/2]
const Cmpt & yy () const inline
Definition at line 95 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::YY.
Referenced by Foam::cof(), Foam::det(), Foam::innerSqr(), Foam::invariantII(), Foam::magSqr(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Tensor2D< Cmpt >::operator=(), Tensor2D< Cmpt >::Tensor2D(), and Foam::tr().
xx() [2/2]
Cmpt & xx () inline
Definition at line 102 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XX.
xy() [2/2]
Cmpt & xy () inline
Definition at line 108 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::XY.
yy() [2/2]
Cmpt & yy () inline
Definition at line 114 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, and SymmTensor2D< Cmpt >::YY.
T()
const Foam::SymmTensor2D< Cmpt > & T () const inline
Transpose.
Definition at line 121 of file SymmTensor2DI.H.
operator=()
void operator= (const SphericalTensor2D< Cmpt > & st) inline
Construct given SphericalTensor2D.
Definition at line 131 of file SymmTensor2DI.H.
References VectorSpace< SymmTensor2D< Cmpt >, Cmpt, 3 >::v_, SymmTensor2D< Cmpt >::XX, SymmTensor2D< Cmpt >::XY, and SymmTensor2D< Cmpt >::YY.
Member Data Documentation
rank
const direction rank = 2 static
Rank of SymmTensor2D is 2.
Definition at line 67 of file SymmTensor2D.H.
I
const Foam::symmTensor2D I static
Definition at line 72 of file SymmTensor2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SymmTensor2D/SymmTensor2D.H
src/OpenFOAM/primitives/SymmTensor2D/symmTensor2D/symmTensor2D.C
src/OpenFOAM/primitives/SymmTensor2D/SymmTensor2DI.H