OpenFOAM: Tensor2D< Cmpt > Class Template Reference
Tensor2D< Cmpt > Class Template Reference
Templated 2D tensor derived from VectorSpace adding construction from 4 components, element access using xx(), xy(), yx() and yy() member functions and the iner-product (dot-product) and outer-product of two Vector2Ds (tensor-product) operators.
Public Types
enum components { XX, XY, YX, YY }
Component labeling enumeration.
typedef Tensor2D< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
typedef VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
Public Member Functions
Tensor2D ()
Construct null.
Tensor2D (const Foam::zero)
Construct initialized to zero.
Tensor2D (const VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 > &)
Construct given VectorSpace.
Tensor2D (const SymmTensor2D< Cmpt > &)
Construct given SymmTensor2D.
Tensor2D (const SphericalTensor2D< Cmpt > &)
Construct given SphericalTensor2D.
Tensor2D (const Vector2D< Cmpt > &x, const Vector2D< Cmpt > &y)
Construct given the two vectors.
Tensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyx, const Cmpt tyy)
Construct given the four components.
Tensor2D (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & yx () const
const Cmpt & yy () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & yx ()
Cmpt & yy ()
Vector2D< Cmpt > x () const
Vector2D< Cmpt > y () const
Tensor2D< Cmpt > T () const
Transpose.
void operator= (const SymmTensor2D< Cmpt > &)
Copy SymmTensor2D.
void operator= (const SphericalTensor2D< Cmpt > &)
Copy SphericalTensor2D.
Public Member Functions inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const ConstBlock< SubVector, BStart > block () const
const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const direction rank = 2
Rank of Tensor2D is 2.
static const Tensor2D I
Static Public Attributes inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
static const direction dim
Dimensionality of space.
static const direction nComponents
Number of components in this vector space.
static const direction mRows
static const direction nCols
static const char *const typeName
static const char *const componentNames []
static const Tensor2D< Cmpt > zero
static const Tensor2D< Cmpt > one
static const Tensor2D< Cmpt > max
static const Tensor2D< Cmpt > min
static const Tensor2D< Cmpt > rootMax
static const Tensor2D< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Tensor2D< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::Tensor2D< Cmpt >
Templated 2D tensor derived from VectorSpace adding construction from 4 components, element access using xx(), xy(), yx() and yy() member functions and the iner-product (dot-product) and outer-product of two Vector2Ds (tensor-product) operators.
Source files
Tensor2D.H
Tensor2DI.H
Definition at line 56 of file Tensor2D.H.
Member Typedef Documentation
labelType
typedef Tensor2D<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 64 of file Tensor2D.H.
Member Enumeration Documentation
components
enum components
Component labeling enumeration.
Enumerator
XX
XY
YX
YY
Definition at line 79 of file Tensor2D.H.
Constructor & Destructor Documentation
Tensor2D() [1/8]
Tensor2D () inline
Construct null.
Definition at line 29 of file Tensor2DI.H.
Referenced by Tensor2D< Cmpt >::Tensor2D().
Tensor2D() [2/8]
Tensor2D (const Foam::zero) inline
Construct initialized to zero.
Definition at line 34 of file Tensor2DI.H.
References Tensor2D< Cmpt >::Tensor2D().
Tensor2D() [3/8]
Tensor2D (const VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 > & vs) inline
Construct given VectorSpace.
Definition at line 42 of file Tensor2DI.H.
Tensor2D() [4/8]
Tensor2D (const SymmTensor2D< Cmpt > & st) inline
Construct given SymmTensor2D.
Definition at line 51 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, Tensor2D< Cmpt >::XX, SymmTensor2D< Cmpt >::xx(), Tensor2D< Cmpt >::XY, SymmTensor2D< Cmpt >::xy(), Tensor2D< Cmpt >::YX, Tensor2D< Cmpt >::YY, and SymmTensor2D< Cmpt >::yy().
Tensor2D() [5/8]
Tensor2D (const SphericalTensor2D< Cmpt > & st) inline
Construct given SphericalTensor2D.
Definition at line 59 of file Tensor2DI.H.
References SphericalTensor2D< Cmpt >::ii(), Tensor2D< Cmpt >::Tensor2D(), VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, Tensor2D< Cmpt >::XX, Tensor2D< Cmpt >::XY, Tensor2D< Cmpt >::YX, and Tensor2D< Cmpt >::YY.
Tensor2D() [6/8]
Tensor2D (const Vector2D< Cmpt > & x, const Vector2D< Cmpt > & y) inline
Construct given the two vectors.
Definition at line 68 of file Tensor2DI.H.
References Tensor2D< Cmpt >::Tensor2D(), VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, Vector2D< Cmpt >::x(), Tensor2D< Cmpt >::XX, Tensor2D< Cmpt >::XY, Vector2D< Cmpt >::y(), Tensor2D< Cmpt >::YX, and Tensor2D< Cmpt >::YY.
Tensor2D() [7/8]
Tensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyx, const Cmpt tyy) inline
Construct given the four components.
Definition at line 80 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, Tensor2D< Cmpt >::XX, Tensor2D< Cmpt >::XY, Tensor2D< Cmpt >::YX, and Tensor2D< Cmpt >::YY.
Tensor2D() [8/8]
Tensor2D (Istream & is) inline
Construct from Istream.
Definition at line 91 of file Tensor2DI.H.
Member Function Documentation
xx() [1/2]
const Cmpt & xx () const inline
Definition at line 113 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::XX.
Referenced by Foam::cof(), Foam::det(), Foam::invariantII(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Foam::symm(), Tensor2D< Cmpt >::T(), Foam::tr(), and Foam::twoSymm().
xy() [1/2]
const Cmpt & xy () const inline
Definition at line 119 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::XY.
Referenced by Foam::cof(), Foam::det(), Foam::invariantII(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Foam::skew(), Foam::symm(), Tensor2D< Cmpt >::T(), and Foam::twoSymm().
yx() [1/2]
const Cmpt & yx () const inline
Definition at line 125 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::YX.
Referenced by Foam::cof(), Foam::det(), Foam::invariantII(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Foam::skew(), Foam::symm(), Tensor2D< Cmpt >::T(), and Foam::twoSymm().
yy() [1/2]
const Cmpt & yy () const inline
Definition at line 131 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::YY.
Referenced by Foam::cof(), Foam::det(), Foam::invariantII(), Foam::operator &(), Foam::operator &&(), Foam::operator+(), Foam::operator-(), Foam::symm(), Tensor2D< Cmpt >::T(), Foam::tr(), and Foam::twoSymm().
xx() [2/2]
Cmpt & xx () inline
Definition at line 138 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::XX.
xy() [2/2]
Cmpt & xy () inline
Definition at line 144 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::XY.
yx() [2/2]
Cmpt & yx () inline
Definition at line 150 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::YX.
yy() [2/2]
Cmpt & yy () inline
Definition at line 156 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, and Tensor2D< Cmpt >::YY.
x()
Foam::Vector2D< Cmpt > x () const inline
Definition at line 100 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, Tensor2D< Cmpt >::XX, and Tensor2D< Cmpt >::XY.
y()
Foam::Vector2D< Cmpt > y () const inline
Definition at line 106 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, Tensor2D< Cmpt >::YX, and Tensor2D< Cmpt >::YY.
T()
Foam::Tensor2D< Cmpt > T () const inline
Transpose.
Definition at line 163 of file Tensor2DI.H.
References Tensor2D< Cmpt >::xx(), Tensor2D< Cmpt >::xy(), Tensor2D< Cmpt >::yx(), and Tensor2D< Cmpt >::yy().
operator=() [1/2]
void operator= (const SymmTensor2D< Cmpt > & st) inline
Copy SymmTensor2D.
Definition at line 176 of file Tensor2DI.H.
References VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, Tensor2D< Cmpt >::XX, SymmTensor2D< Cmpt >::xx(), Tensor2D< Cmpt >::XY, SymmTensor2D< Cmpt >::xy(), Tensor2D< Cmpt >::YX, Tensor2D< Cmpt >::YY, and SymmTensor2D< Cmpt >::yy().
operator=() [2/2]
void operator= (const SphericalTensor2D< Cmpt > & st) inline
Copy SphericalTensor2D.
Definition at line 184 of file Tensor2DI.H.
References SphericalTensor2D< Cmpt >::ii(), Foam::type(), VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >::v_, Tensor2D< Cmpt >::XX, Tensor2D< Cmpt >::XY, Tensor2D< Cmpt >::YX, and Tensor2D< Cmpt >::YY.
Member Data Documentation
rank
const direction rank = 2 static
Rank of Tensor2D is 2.
Definition at line 70 of file Tensor2D.H.
I
const Foam::tensor2D I static
Definition at line 75 of file Tensor2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/Tensor2D/Tensor2D.H
src/OpenFOAM/primitives/Tensor2D/tensor2D/tensor2D.C
src/OpenFOAM/primitives/Tensor2D/Tensor2DI.H