OpenFOAM: VectorSpace< Form, Cmpt, Ncmpts > Class Template Reference
VectorSpace< Form, Cmpt, Ncmpts > Class Template Reference
Templated vector space.
Classes
class ConstBlock
Const sub-block type.
Public Types
typedef VectorSpace< Form, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
Public Member Functions
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Form, Cmpt, Ncmpts > &)
Construct as copy.
template<class Form2 , class Cmpt2 >
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
template<class SubVector , direction BStart>
const ConstBlock< SubVector, BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator+= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator*= (const scalar)
void operator/= (const scalar)
template<class SubVector , direction BStart>
const VectorSpace< Form, Cmpt, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
Static Public Member Functions
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Form uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes
Cmpt v_ [Ncmpts]
The components of this vector space.
Static Public Attributes
static const direction dim = 3
Dimensionality of space.
static const direction nComponents = Ncmpts
Number of components in this vector space.
static const direction mRows = Ncmpts
static const direction nCols = 1
static const char *const typeName = "symmTensor"
static const char *const componentNames []
static const Form zero
static const Form one
static const Form max
static const Form min
static const Form rootMax
static const Form rootMin
Friends
Istream & operator>> (Istream &, VectorSpace< Form, Cmpt, Ncmpts > &)
Ostream & operator (Ostream &, const VectorSpace< Form, Cmpt, Ncmpts > &)
Detailed Description
template<class Form, class Cmpt, direction Ncmpts>
class Foam::VectorSpace< Form, Cmpt, Ncmpts >
Templated vector space.
Template arguments are the Form the vector space will be used to create, the type of the elements and the number of elements.
Source files
VectorSpace.H
VectorSpaceI.H
VectorSpace.C
Definition at line 53 of file VectorSpace.H.
Member Typedef Documentation
vsType
typedef VectorSpace<Form, Cmpt, Ncmpts> vsType
VectorSpace type.
Definition at line 84 of file VectorSpace.H.
cmptType
typedef Cmpt cmptType
Component type.
Definition at line 87 of file VectorSpace.H.
Constructor & Destructor Documentation
VectorSpace() [1/5]
VectorSpace () inline
Construct null.
Definition at line 40 of file VectorSpaceI.H.
Referenced by VectorSpace< Vector< vector >, vector, 3 >::VectorSpace().
VectorSpace() [2/5]
VectorSpace (const Foam::zero) inline
Construct initialized to zero.
Definition at line 45 of file VectorSpaceI.H.
VectorSpace() [3/5]
VectorSpace (Istream & is)
Construct from Istream.
Definition at line 35 of file VectorSpace.C.
VectorSpace() [4/5]
VectorSpace (const VectorSpace< Form, Cmpt, Ncmpts > & vs) inline
Construct as copy.
Definition at line 53 of file VectorSpaceI.H.
VectorSpace() [5/5]
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > & vs) inline explicit
Construct as copy of a VectorSpace with the same size.
Definition at line 64 of file VectorSpaceI.H.
Member Function Documentation
size()
direction size () inline static
Return the number of elements in the VectorSpace = Ncmpts.
Definition at line 93 of file VectorSpaceI.H.
Referenced by edgeCollapser::checkMeshQuality(), streamLineParticle::move(), and createShellMesh::setRefinement().
component() [1/3]
const Cmpt & component (const direction d) const inline
Definition at line 101 of file VectorSpaceI.H.
Referenced by VectorSpace< Vector< vector >, vector, 3 >::component(), Foam::component(), EulerCoordinateRotation::EulerCoordinateRotation(), cellMDLimitedGrad< Type >::limitFace(), Random::position(), Foam::setComponent(), VectorSpace< Vector< vector >, vector, 3 >::size(), STARCDCoordinateRotation::STARCDCoordinateRotation(), Random::symmTensor01(), Random::tensor01(), and Random::vector01().
component() [2/3]
Cmpt & component (const direction d) inline
Definition at line 120 of file VectorSpaceI.H.
component() [3/3]
void component (Cmpt & c, const direction d) const inline
Definition at line 139 of file VectorSpaceI.H.
replace()
void replace (const direction d, const Cmpt & c) inline
Definition at line 159 of file VectorSpaceI.H.
Referenced by VectorSpace< Vector< vector >, vector, 3 >::component().
uniform()
Form uniform (const Cmpt & s) inline static
Return a VectorSpace with all elements = s.
Definition at line 178 of file VectorSpaceI.H.
block() [1/2]
const ConstBlock<SubVector, BStart> block () const inline
operator[]() [1/2]
const Cmpt & operator[] (const direction d) const inline
Definition at line 200 of file VectorSpaceI.H.
operator[]() [2/2]
Cmpt & operator[] (const direction d) inline
Definition at line 219 of file VectorSpaceI.H.
operator=() [1/2]
void operator= (const VectorSpace< Form, Cmpt, Ncmpts > & vs) inline
Definition at line 290 of file VectorSpaceI.H.
Referenced by MatrixSpace< Tensor< scalar >, scalar, 3, 3 >::operator=().
operator+=()
void operator+= (const VectorSpace< Form, Cmpt, Ncmpts > & vs) inline
Definition at line 300 of file VectorSpaceI.H.
operator-=()
void operator-= (const VectorSpace< Form, Cmpt, Ncmpts > & vs) inline
Definition at line 310 of file VectorSpaceI.H.
operator=() [2/2]
void operator= (const Foam::zero) inline
Definition at line 319 of file VectorSpaceI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 327 of file VectorSpaceI.H.
operator/=()
void operator/= (const scalar s) inline
Definition at line 337 of file VectorSpaceI.H.
block() [2/2]
const VectorSpace<Form, Cmpt, Ncmpts>::template ConstBlock<SubVector, BStart> block () const inline
Definition at line 190 of file VectorSpaceI.H.
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , VectorSpace< Form, Cmpt, Ncmpts > &) friend
operator
Ostream& operator (Ostream & , const VectorSpace< Form, Cmpt, Ncmpts > &) friend
Referenced by VectorSpace< Form, Cmpt, Ncmpts >::ConstBlock< SubVector, BStart >::operator[]().
Member Data Documentation
v_
Cmpt v_[Ncmpts]
The components of this vector space.
Definition at line 81 of file VectorSpace.H.
Referenced by Foam::cmptMax(), Foam::cmptMin(), Foam::cmptProduct(), Foam::cmptSum(), Foam::magSqr(), Foam::operator &&(), Foam::operator<(), Foam::operator==(), Foam::operator>(), and VectorSpace< Vector< vector >, vector, 3 >::VectorSpace().
dim
const direction dim = 3 static
Dimensionality of space.
Definition at line 93 of file VectorSpace.H.
Referenced by Foam::cof(), and Foam::det().
nComponents
const direction nComponents = Ncmpts static
Number of components in this vector space.
Definition at line 96 of file VectorSpace.H.
Referenced by anisotropicFilter::operator()(), and Random::symmTensor01().
mRows
const direction mRows = Ncmpts static
Definition at line 102 of file VectorSpace.H.
nCols
const direction nCols = 1 static
Definition at line 103 of file VectorSpace.H.
typeName
const char *const typeName = "symmTensor" static
Definition at line 108 of file VectorSpace.H.
componentNames
const char *const componentNames static
Initial value:
=
{
    "xx", "xy", "xz",
          "yy", "yz",
                "zz"
}
Definition at line 109 of file VectorSpace.H.
zero
const Foam::symmTensor zero static
Definition at line 110 of file VectorSpace.H.
one
const Foam::symmTensor one static
Definition at line 111 of file VectorSpace.H.
max
const Foam::symmTensor max static
Definition at line 112 of file VectorSpace.H.
Referenced by NamedEnum< directionType, 3 >::names(), treeDataPoint::findNearestOp::operator()(), treeDataEdge::findNearestOp::operator()(), orientedSurface::orientedSurface(), distributedTriSurfaceMesh::overlappingSurface(), primitiveMesh::pointInCellBB(), and searchableDisk::searchableDisk().
min
const Foam::symmTensor min static
Definition at line 113 of file VectorSpace.H.
Referenced by NamedEnum< directionType, 3 >::names(), treeDataPoint::findNearestOp::operator()(), treeDataEdge::findNearestOp::operator()(), distributedTriSurfaceMesh::overlappingSurface(), searchableDisk::searchableDisk(), and searchableSurfaceCollection::searchableSurfaceCollection().
rootMax
const Foam::symmTensor rootMax static
Definition at line 114 of file VectorSpace.H.
rootMin
const Foam::symmTensor rootMin static
Definition at line 115 of file VectorSpace.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/VectorSpace/VectorSpace.H
src/OpenFOAM/primitives/SymmTensor/symmTensor/symmTensor.C
src/OpenFOAM/primitives/VectorSpace/VectorSpace.C
src/OpenFOAM/primitives/VectorSpace/VectorSpaceI.H