OpenFOAM: VectorSpaceOps< N, I > Class Template Reference
VectorSpaceOps< N, I > Class Template Reference
Operator functions for VectorSpace.
Static Public Member Functions
template<class V , class S , class EqOp >
static void eqOpS (V &vs, const S &s, EqOp eo)
template<class S , class V , class EqOp >
static void SeqOp (S &s, const V &vs, EqOp eo)
template<class V1 , class V2 , class EqOp >
static void eqOp (V1 &vs1, const V2 &vs2, EqOp eo)
template<class V , class V1 , class S , class Op >
static void opVS (V &vs, const V1 &vs1, const S &s, Op o)
template<class V , class S , class V1 , class Op >
static void opSV (V &vs, const S &s, const V1 &vs1, Op o)
template<class V , class V1 , class Op >
static void op (V &vs, const V1 &vs1, const V1 &vs2, Op o)
Static Public Attributes
static const int endLoop = (I < N-1) ? 1 : 0
Detailed Description
template<direction N, direction I>
class Foam::VectorSpaceOps< N, I >
Operator functions for VectorSpace.
Definition at line 42 of file VectorSpaceOps.H.
Member Function Documentation
eqOpS()
static void eqOpS (V & vs, const S & s, EqOp eo) inline static
Definition at line 49 of file VectorSpaceOps.H.
References Foam::I, and s().
Referenced by VectorSpace< Vector< vector >, vector, 3 >::operator*=(), VectorSpace< Vector< vector >, vector, 3 >::operator/=(), VectorSpace< Vector< vector >, vector, 3 >::operator=(), VectorSpace< Vector< vector >, vector, 3 >::uniform(), and VectorSpace< Vector< vector >, vector, 3 >::VectorSpace().
SeqOp()
static void SeqOp (S & s, const V & vs, EqOp eo) inline static
Definition at line 56 of file VectorSpaceOps.H.
References Foam::I, and s().
Referenced by Foam::cmptMax(), Foam::cmptMin(), Foam::cmptProduct(), Foam::cmptSum(), and Foam::magSqr().
eqOp()
static void eqOp (V1 & vs1, const V2 & vs2, EqOp eo) inline static
Definition at line 63 of file VectorSpaceOps.H.
References Foam::I.
Referenced by Foam::cmptMag(), VectorSpace< Vector< vector >, vector, 3 >::operator+=(), Foam::operator-(), VectorSpace< Vector< vector >, vector, 3 >::operator-=(), VectorSpace< Vector< vector >, vector, 3 >::operator=(), and VectorSpace< Vector< vector >, vector, 3 >::VectorSpace().
opVS()
static void opVS (V & vs, const V1 & vs1, const S & s, Op o) inline static
Definition at line 71 of file VectorSpaceOps.H.
References Foam::I, and s().
Referenced by Foam::operator*(), Foam::operator/(), and Foam::stabilise().
opSV()
static void opSV (V & vs, const S & s, const V1 & vs1, Op o) inline static
Definition at line 78 of file VectorSpaceOps.H.
References Foam::I, and s().
Referenced by Foam::operator*().
op()
static void op (V & vs, const V1 & vs1, const V1 & vs2, Op o) inline static
Definition at line 85 of file VectorSpaceOps.H.
References Foam::I.
Referenced by Foam::cmptDivide(), Foam::cmptMultiply(), Foam::cmptPow(), Foam::max(), Foam::min(), Foam::minMod(), Foam::operator+(), and Foam::operator-().
Member Data Documentation
endLoop
const int endLoop = (I < N-1) ? 1 : 0 static
Definition at line 46 of file VectorSpaceOps.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/primitives/VectorSpace/VectorSpaceOps.H