OpenFOAM: fileMonitor Class Reference
fileMonitor Class Reference
Checking for changes to files.
Public Types
enum fileState { UNMODIFIED = 0, MODIFIED = 1, DELETED = 2 }
Enumeration defining the file state.
Public Member Functions
ClassName ("fileMonitor")
fileMonitor (const bool useInotify)
Construct null.
~fileMonitor ()
Destructor.
label addWatch (const fileName &)
Add file to watch. Return watch descriptor.
bool removeWatch (const label watchFd)
Remove file to watch. Return true if successful.
const fileName & getFile (const label watchFd) const
Get name of file being watched.
fileState getState (const label watchFd) const
Check state using handle.
void updateStates (const bool masterOnly, const bool syncPar) const
Check state of all files. Updates state_.
void setUnmodified (const label watchFd)
Reset state (e.g. after having read it) using handle.
Static Public Attributes
static const NamedEnum< fileState, 3 > fileStateNames_
Detailed Description
Checking for changes to files.
Note
The default is to use stat to get the timestamp.
Compile with FOAM_USE_INOTIFY to use the inotify (Linux specific, since 2.6.13) framework. The problem is that inotify does not work on nfs3 mounted directories!!
Source files
fileMonitor.H
fileMonitor.C
Definition at line 61 of file fileMonitor.H.
Member Enumeration Documentation
fileState
enum fileState
Enumeration defining the file state.
Enumerator
UNMODIFIED
MODIFIED
DELETED
Definition at line 69 of file fileMonitor.H.
Constructor & Destructor Documentation
fileMonitor()
fileMonitor (const bool useInotify)
Construct null.
Definition at line 429 of file fileMonitor.C.
~fileMonitor()
~fileMonitor ()
Destructor.
Definition at line 442 of file fileMonitor.C.
Member Function Documentation
ClassName()
ClassName ("fileMonitor")
addWatch()
Foam::label addWatch (const fileName & fName)
Add file to watch. Return watch descriptor.
Definition at line 450 of file fileMonitor.C.
References Foam::endl(), Foam::Pout, DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::size(), fileMonitor::UNMODIFIED, and WarningInFunction.
removeWatch()
bool removeWatch (const label watchFd)
Remove file to watch. Return true if successful.
Definition at line 489 of file fileMonitor.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), and Foam::Pout.
getFile()
const Foam::fileName & getFile (const label watchFd) const
Get name of file being watched.
Definition at line 502 of file fileMonitor.C.
getState()
Foam::fileMonitor::fileState getState (const label watchFd) const
Check state using handle.
Definition at line 508 of file fileMonitor.C.
References fileMonitor::updateStates().
updateStates()
void updateStates (const bool masterOnly, const bool syncPar) const
Check state of all files. Updates state_.
Definition at line 516 of file fileMonitor.C.
References Foam::endl(), forAll, Pstream::listCombineGather(), Pstream::listCombineScatter(), UPstream::master(), fileMonitor::MODIFIED, Foam::Pout, Foam::reduce(), Pstream::scatter(), List< T >::size(), and WarningInFunction.
Referenced by fileMonitor::getState().
setUnmodified()
void setUnmodified (const label watchFd)
Reset state (e.g. after having read it) using handle.
Definition at line 611 of file fileMonitor.C.
References Foam::lastModified(), and fileMonitor::UNMODIFIED.
Member Data Documentation
fileStateNames_
const Foam::NamedEnum< Foam::fileMonitor::fileState, 3 > fileStateNames_ static
Definition at line 76 of file fileMonitor.H.
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/fileMonitor.H
src/OSspecific/POSIX/fileMonitor.C