OpenFOAM: cpuTime Class Reference
cpuTime Class Reference
Starts timing CPU usage and return elapsed time from start.
Public Member Functions
cpuTime ()
Construct with the current clock time.
double elapsedCpuTime () const
Return CPU time (in seconds) from the start.
double cpuTimeIncrement () const
Return CPU time (in seconds) since last call to cpuTimeIncrement()
Detailed Description
Starts timing CPU usage and return elapsed time from start.
See also
clockTime
Source files
cpuTime.H
cpuTime.C
Definition at line 52 of file cpuTime.H.
Constructor & Destructor Documentation
cpuTime()
cpuTime ()
Construct with the current clock time.
Definition at line 57 of file cpuTime.C.
Member Function Documentation
elapsedCpuTime()
double elapsedCpuTime () const
Return CPU time (in seconds) from the start.
Definition at line 67 of file cpuTime.C.
Referenced by JobInfo::write().
cpuTimeIncrement()
double cpuTimeIncrement () const
Return CPU time (in seconds) since last call to cpuTimeIncrement()
Definition at line 74 of file cpuTime.C.
Referenced by meshRefinement::baffleAndSplitMesh(), snappySnapDriver::calcNearestSurface(), meshRefinement::createZoneBaffles(), snappySnapDriver::doSnap(), meshRefinement::mergeBaffles(), snappySnapDriver::preSmoothPatch(), snappySnapDriver::repatchToSurface(), snappySnapDriver::scaleMesh(), snappySnapDriver::smoothDisplacement(), and snappyRefineDriver::snappyRefineDriver().
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/cpuTime/cpuTime.H
src/OSspecific/POSIX/cpuTime/cpuTime.C