OpenFOAM: sigFpe Class Reference
sigFpe Class Reference
Set up trapping for floating point exceptions (signal FPE).
Public Member Functions
sigFpe ()
Construct null.
~sigFpe ()
Destructor.
void set (const bool verbose)
Activate SIGFPE signal handler when FOAM_SIGFPE is set.
Static Public Member Functions
static void fillNan (UList< scalar > &)
Fill block of data with NaN.
Static Public Attributes
static bool mallocNanActive_ = false
Flag to indicate mallocNan is enabled.
Detailed Description
Set up trapping for floating point exceptions (signal FPE).
Controlled by two env vars:
FOAM_SIGFPE
Exception trapping
FOAM_SETNAN
Initialization of all malloced memory to NaN. If FOAM_SIGFPE also set, this will cause usage of uninitialized scalars to trigger an abort.
Source files
sigFpe.H
sigFpe.C
Definition at line 67 of file sigFpe.H.
Constructor & Destructor Documentation
sigFpe()
sigFpe ()
Construct null.
Definition at line 113 of file sigFpe.C.
~sigFpe()
~sigFpe ()
Destructor.
Definition at line 121 of file sigFpe.C.
References Foam::abort(), Foam::env(), Foam::FatalError, and FatalErrorInFunction.
Member Function Documentation
set()
void set (const bool verbose)
Activate SIGFPE signal handler when FOAM_SIGFPE is set.
Fill memory with NaN when FOAM_SETNAN is set
Definition at line 152 of file sigFpe.C.
References Foam::abort(), Foam::endl(), Foam::env(), Foam::FatalError, FatalErrorInFunction, and Foam::Info.
Referenced by argList::parse().
fillNan()
void fillNan (UList< scalar > & lst) static
Fill block of data with NaN.
Definition at line 48 of file sigFpe.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::jobInfo, sigFpe::mallocNanActive_, Foam::Perr, and JobInfo::signalEnd().
Referenced by dynamicRefineFvMesh::refine().
Member Data Documentation
mallocNanActive_
bool mallocNanActive_ = false static
Flag to indicate mallocNan is enabled.
Definition at line 103 of file sigFpe.H.
Referenced by sigFpe::fillNan().
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigFpe.H
src/OSspecific/POSIX/signals/sigFpe.C