OpenFOAM: addwriteNowSignalToOpt Class Reference
addwriteNowSignalToOpt Class Reference
Public Member Functions
addwriteNowSignalToOpt (const char *name)
virtual ~addwriteNowSignalToOpt ()
virtual void readData (Foam::Istream &is)
Read.
virtual void writeData (Foam::Ostream &os) const
Write.
Public Member Functions inherited from simpleRegIOobject
simpleRegIOobject (void(*fn)(const char *name, simpleRegIOobject *), const char *name)
Construct from objectregistry inserter and name.
virtual ~simpleRegIOobject ()
Destructor.
Detailed Description
Definition at line 44 of file sigWriteNow.C.
Constructor & Destructor Documentation
addwriteNowSignalToOpt()
addwriteNowSignalToOpt (const char * name) inline
Definition at line 51 of file sigWriteNow.C.
~addwriteNowSignalToOpt()
virtual ~addwriteNowSignalToOpt () inline virtual
Definition at line 56 of file sigWriteNow.C.
Member Function Documentation
readData()
virtual void readData (Foam::Istream &) inline virtual
Read.
Implements simpleRegIOobject.
Definition at line 59 of file sigWriteNow.C.
References Foam::readLabel(), and sigWriteNow::set().
writeData()
virtual void writeData (Foam::Ostream &) const inline virtual
Write.
Implements simpleRegIOobject.
Definition at line 65 of file sigWriteNow.C.
References Foam::addwriteNowSignalToOpt_, Foam::endl(), Foam::Info, and Foam::nl.
The documentation for this class was generated from the following file:
src/OSspecific/POSIX/signals/sigWriteNow.C