OpenFOAM: sigSegv Class Reference
sigSegv Class Reference
Signal handler for SEGV interupt.
Public Member Functions
sigSegv ()
Construct null.
~sigSegv ()
Destructor.
void set (const bool verbose)
Activate SIGSEGV signal handler.
Detailed Description
Signal handler for SEGV interupt.
The standard interupt handler is overridden to ensure that the runningJob file is removed.
See also
Foam::JobInfo
Source files
sigSegv.H
sigSegv.C
Definition at line 54 of file sigSegv.H.
Constructor & Destructor Documentation
sigSegv()
sigSegv ()
Construct null.
Definition at line 60 of file sigSegv.C.
~sigSegv()
~sigSegv ()
Destructor.
Definition at line 68 of file sigSegv.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Member Function Documentation
set()
void set (const bool verbose)
Activate SIGSEGV signal handler.
Definition at line 82 of file sigSegv.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by argList::parse().
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigSegv.H
src/OSspecific/POSIX/signals/sigSegv.C