OpenFOAM: preserveBafflesConstraint Class Reference
preserveBafflesConstraint Class Reference
Public Member Functions
TypeName ("preserveBaffles")
Runtime type information.
preserveBafflesConstraint (const dictionary &constraintsDict, const word &type)
Construct with generic dictionary with optional entry for type.
preserveBafflesConstraint ()
Construct from components.
virtual ~preserveBafflesConstraint ()
Destructor.
virtual void add (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
Add my constraints to list of constraints.
virtual void apply (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &decomposition) const
Apply any additional post-decomposition constraints.
Public Member Functions inherited from decompositionConstraint
TypeName ("decompositionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionConstraint, dictionary,(const dictionary &constraintsDict, const word &type),(constraintsDict, type))
decompositionConstraint (const dictionary &constraintsDict, const word &type)
Construct with generic dictionary with optional entry for type.
virtual ~decompositionConstraint ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from decompositionConstraint
static autoPtr< decompositionConstraint > New (const dictionary &constraintsDict, const word &type)
Return a reference to the selected decompositionConstraint.
Protected Attributes inherited from decompositionConstraint
dictionary coeffDict_
Model coefficients dictionary.
Detailed Description
Definition at line 51 of file preserveBafflesConstraint.H.
Constructor & Destructor Documentation
preserveBafflesConstraint() [1/2]
preserveBafflesConstraint (const dictionary & constraintsDict, const word & type)
Construct with generic dictionary with optional entry for type.
Definition at line 53 of file preserveBafflesConstraint.C.
References Foam::endl(), Foam::Info, preserveBafflesConstraint::preserveBafflesConstraint(), and Foam::type().
preserveBafflesConstraint() [2/2]
preserveBafflesConstraint ()
Construct from components.
Definition at line 70 of file preserveBafflesConstraint.C.
References preserveBafflesConstraint::add(), Foam::endl(), Foam::Info, and Foam::type().
Referenced by preserveBafflesConstraint::preserveBafflesConstraint().
~preserveBafflesConstraint()
virtual ~preserveBafflesConstraint () inline virtual
Destructor.
Definition at line 77 of file preserveBafflesConstraint.H.
References preserveBafflesConstraint::add(), preserveBafflesConstraint::apply(), and mesh.
Member Function Documentation
TypeName()
TypeName ("preserveBaffles")
Runtime type information.
add()
void add (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const virtual
Add my constraints to list of constraints.
Implements decompositionConstraint.
Definition at line 86 of file preserveBafflesConstraint.C.
References preserveBafflesConstraint::apply(), decompositionConstraint::coeffDict_, Pair< Type >::compare(), Foam::endl(), primitiveMesh::faceCentres(), localPointRegion::findDuplicateFacePairs(), UList< T >::first(), forAll, Foam::Info, IOWarningInFunction, n, primitiveMesh::nFaces(), p, Foam::returnReduce(), List< T >::setSize(), List< T >::size(), syncTools::syncFaceList(), and Foam::type().
Referenced by preserveBafflesConstraint::preserveBafflesConstraint(), and preserveBafflesConstraint::~preserveBafflesConstraint().
apply()
void apply (const polyMesh & mesh, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & decomposition) const virtual
Apply any additional post-decomposition constraints.
Reimplemented from decompositionConstraint.
Definition at line 184 of file preserveBafflesConstraint.C.
References Foam::endl(), f1, polyMesh::faceNeighbour(), polyMesh::faceOwner(), localPointRegion::findDuplicateFacePairs(), Pair< Type >::first(), forAll, Foam::Info, primitiveMesh::isInternalFace(), Foam::reduce(), Pair< Type >::second(), and Foam::type().
Referenced by preserveBafflesConstraint::add(), and preserveBafflesConstraint::~preserveBafflesConstraint().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionConstraints/preserveBaffles/preserveBafflesConstraint.H
src/parallel/decompose/decompositionMethods/decompositionConstraints/preserveBaffles/preserveBafflesConstraint.C