OpenFOAM: distributedTriSurfaceMesh Class Reference
distributedTriSurfaceMesh Class Reference
IOoject and searching on distributed triSurface. All processor hold (possibly overlapping) part of the overall surface. All queries are distributed to the processor that can answer it and the result sent back.
Public Types
enum distributionType { FOLLOW = 0, INDEPENDENT = 1, FROZEN = 2 }
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject *>
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Types inherited from triSurface
typedef bool BoundaryMesh
Placeholder only, but do not remove - it is needed for GeoMesh.
Public Types inherited from PrimitivePatch< labelledTri, ::Foam::List, pointField, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef labelledTri FaceType
typedef ::Foam::List< labelledTri > FaceListType
typedef pointField PointFieldType
Public Types inherited from List< labelledTri >
typedef SubList< labelledTri > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("distributedTriSurfaceMesh")
Runtime type information.
distributedTriSurfaceMesh (const IOobject &, const triSurface &, const dictionary &dict)
Construct from triSurface.
distributedTriSurfaceMesh (const IOobject &io)
Construct read. Does findInstance to find io.local().
distributedTriSurfaceMesh (const IOobject &io, const dictionary &dict)
Construct from dictionary (used by searchableSurface).
virtual ~distributedTriSurfaceMesh ()
Destructor.
void clearOut ()
Clear storage.
const globalIndex & globalTris () const
Triangle indexing (demand driven)
virtual bool hasVolumeType () const
Whether supports volume type below. I.e. whether is closed.
virtual label globalSize () const
Range of global indices that can be returned.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &) const
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Find first intersection on segment from start to end.
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Return any intersection on segment from start to end.
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit >> &) const
Get all intersections in order from start to end.
virtual void getRegion (const List< pointIndexHit > &, labelList &region) const
From a set of points and indices get the region.
virtual void getNormal (const List< pointIndexHit > &, vectorField &normal) const
From a set of points and indices get the normal.
virtual void getVolumeType (const pointField &, List< volumeType > &) const
Determine type (inside/outside/mixed) for point. unknown if.
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
Set bounds of surface. Bounds currently set as list of.
virtual void getField (const List< pointIndexHit > &, labelList &) const
WIP. From a set of hits (points and.
void writeStats (Ostream &os) const
Print some stats. Parallel aware version of.
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write using given format, version and compression.
Public Member Functions inherited from triSurfaceMesh
TypeName ("triSurfaceMesh")
Runtime type information.
triSurfaceMesh (const IOobject &, const triSurface &)
Construct from triSurface.
triSurfaceMesh (const IOobject &io)
Construct read.
triSurfaceMesh (const IOobject &io, const dictionary &dict)
Construct from IO and dictionary (used by searchableSurface).
virtual ~triSurfaceMesh ()
Destructor.
void clearOut ()
Clear storage.
virtual void movePoints (const pointField &)
Move points.
const indexedOctree< treeDataEdge > & edgeTree () const
Demand driven construction of octree for boundary edges.
virtual const wordList & regions () const
Names of regions.
virtual label size () const
Range of local indices that can be returned.
virtual tmp< pointField > coordinates () const
Get representative set of element coordinates.
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const
Get bounding spheres (centre and radius squared). Any point.
virtual tmp< pointField > points () const
Get the points that define the surface.
virtual bool overlaps (const boundBox &bb) const
Does any part of the surface overlap the supplied bound box?
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &) const
Find the nearest locations for the supplied points to a.
virtual void setField (const labelList &values)
WIP. Store element-wise field.
bool writeData (Ostream &) const
writeData function required by regIOobject but not used
Public Member Functions inherited from searchableSurface
TypeName ("searchableSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr< searchableSurface > clone () const
Clone.
virtual ~searchableSurface ()
Destructor.
const boundBox & bounds () const
Return const reference to boundBox.
boundBox & bounds ()
Return non-const access to the boundBox to allow it to be set.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &, vectorField &normal, labelList &region) const
Find nearest, normal and region. Can be overridden with.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from HashTable< regIOobject *>
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< word, regIOobject * >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Foam::label erase (const HashTable< AnyType, word, AnyHash > &rhs)
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< word, regIOobject * >>)
Assignment to an initializer list.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from triSurface
ClassName ("triSurface")
Runtime type information.
triSurface ()
Construct null.
triSurface (const List< labelledTri > &, const geometricSurfacePatchList &, const pointField &)
Construct from triangles, patches, points.
triSurface (List< labelledTri > &, const geometricSurfacePatchList &, pointField &, const bool reuse)
Construct from triangles, patches, points. Reuse storage.
triSurface (const Xfer< List< labelledTri >> &, const geometricSurfacePatchList &, const Xfer< List< point >> &)
Construct from triangles, patches, points.
triSurface (const List< labelledTri > &, const pointField &)
Construct from triangles, points. Set patchnames to default.
triSurface (const triFaceList &, const pointField &)
Construct from triangles, points. Set region to 0 and default.
triSurface (const fileName &)
Construct from file name (uses extension to determine type)
triSurface (Istream &)
Construct from Istream.
triSurface (const Time &d)
Construct from objectRegistry.
triSurface (const triSurface &)
Construct as copy.
~triSurface ()
Destructor.
void clearOut ()
void clearTopology ()
void clearPatchMeshAddr ()
const geometricSurfacePatchList & patches () const
geometricSurfacePatchList & patches ()
const labelListList & sortedEdgeFaces () const
Return edge-face addressing sorted (for edges with more than.
const labelList & edgeOwner () const
If 2 face neighbours: label of face where ordering of edge.
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
void checkTriangles (const bool verbose)
Check/remove duplicate/degenerate triangles.
void checkEdges (const bool verbose)
Check triply (or more) connected edges.
void cleanup (const bool verbose)
Remove non-valid triangles.
void markZone (const boolList &borderEdge, const label facei, const label currentZone, labelList &faceZone) const
Fill faceZone with currentZone for every face reachable.
label markZones (const boolList &borderEdge, labelList &faceZone) const
(size and) fills faceZone with zone of face. Zone is area
void subsetMeshMap (const boolList &include, labelList &pointMap, labelList &faceMap) const
'Create' sub mesh, including only faces for which
triSurface subsetMesh (const boolList &include, labelList &pointMap, labelList &faceMap) const
Return new surface. Returns pointMap, faceMap from.
void write (Ostream &) const
Write to Ostream in simple FOAM format.
void write (const fileName &, const bool sortByRegion=false) const
Generic write routine. Chooses writer based on extension.
void write (const Time &) const
Write to database.
void writeDX (const scalarField &, Ostream &) const
Write to Ostream in OpenDX format.
void writeDX (const vectorField &, Ostream &) const
void writeStats (Ostream &) const
Write some statistics.
void operator= (const triSurface &)
Public Member Functions inherited from PrimitivePatch< labelledTri, ::Foam::List, pointField, point >
PrimitivePatch (const ::Foam::List< labelledTri > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (const Xfer< ::Foam::List< labelledTri >> &faces, const Xfer< List< point >> &points)
Construct from components.
PrimitivePatch (::Foam::List< labelledTri > &faces, Field< point > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< labelledTri, ::Foam::List, pointField, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< labelledTri > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceNormals () const
Return face normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< labelledTri, ::Foam::List, pointField, point > &)
Assignment.
Public Member Functions inherited from List< labelledTri >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const labelledTri &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< labelledTri > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< labelledTri >> &)
Construct by transferring the parameter contents.
List (List< labelledTri > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< labelledTri > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< labelledTri, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< labelledTri > &)
Construct as copy of PtrList<T>
List (const SLList< labelledTri > &)
Construct as copy of SLList<T>
List (const UIndirectList< labelledTri > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< labelledTri > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< labelledTri >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< labelledTri > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const labelledTri &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const labelledTri &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const labelledTri &)
Append an element at the end of the list.
void append (const UList< labelledTri > &)
Append a List at the end of this list.
void append (const UIndirectList< labelledTri > &)
Append a UIndirectList at the end of this list.
void transfer (List< labelledTri > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< labelledTri, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< labelledTri > &)
Transfer the contents of the argument List into this list.
Xfer< List< labelledTri > > xfer ()
Transfer contents to the Xfer container.
labelledTri & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< labelledTri > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< labelledTri > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< labelledTri > &)
Assignment operator. Takes linear time.
void operator= (const SLList< labelledTri > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< labelledTri > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< labelledTri > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< labelledTri >)
Assignment to an initializer list.
void operator= (const labelledTri &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Public Member Functions inherited from triSurfaceRegionSearch
triSurfaceRegionSearch (const triSurface &)
Construct from surface. Holds reference to surface!
triSurfaceRegionSearch (const triSurface &, const dictionary &dict)
Construct from surface and dictionary. Holds reference to surface!
~triSurfaceRegionSearch ()
Destructor.
void clearOut ()
Clear storage.
const PtrList< treeType > & treeByRegion () const
Demand driven construction of octree for each region.
void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
Find the nearest point on the surface out of the regions.
Public Member Functions inherited from triSurfaceSearch
triSurfaceSearch (const triSurface &)
Construct from surface. Holds reference to surface!
triSurfaceSearch (const triSurface &, const dictionary &dict)
Construct from surface and dictionary.
triSurfaceSearch (const triSurface &surface, const scalar tolerance, const label maxTreeDepth)
Construct from components.
~triSurfaceSearch ()
Destructor.
void clearOut ()
Clear storage.
const indexedOctree< treeDataTriSurface > & tree () const
Demand driven construction of the octree.
const triSurface & surface () const
Return reference to the surface.
scalar tolerance () const
Return tolerance to use in searches.
label maxTreeDepth () const
Return max tree depth of octree.
boolList calcInside (const pointField &searchPoints) const
Calculate for each searchPoint inside/outside status.
void findNearest (const pointField &samples, const scalarField &nearestDistSqr, List< pointIndexHit > &info) const
pointIndexHit nearest (const point &, const vector &span) const
Calculate nearest point on surface for single searchPoint. Returns.
void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &info) const
void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &info) const
void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit >> &info) const
Calculate all intersections from start to end.
Static Public Member Functions
static triSurface overlappingSurface (const triSurface &, const List< treeBoundBox > &, labelList &subPointMap, labelList &subFaceMap)
Subset the part of surface that is overlapping bounds.
Static Public Member Functions inherited from searchableSurface
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Return a reference to the selected searchableSurface.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Member Functions inherited from triSurface
static fileName triSurfInstance (const Time &)
Name of triSurface directory to use.
Static Public Member Functions inherited from List< labelledTri >
static const List< labelledTri > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Static Public Attributes
static const NamedEnum< distributionType, 3 > distributionTypeNames_
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Additional Inherited Members
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from triSurface
pointField & storedPoints ()
Non-const access to global points.
List< Face > & storedFaces ()
Non-const access to the faces.
Protected Member Functions inherited from List< labelledTri >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
IOoject and searching on distributed triSurface. All processor hold (possibly overlapping) part of the overall surface. All queries are distributed to the processor that can answer it and the result sent back.
Can work in three modes:
follow : makes sure each processor has all the triangles inside the externally provided bounding box (usually the mesh bounding box). Guarantees minimum amount of communication since mesh-local queries should be answerable without any comms.
independent : surface is decomposed according to the triangle centres so the decomposition might be radically different from the mesh decomposition. Guarantees best memory balance but at the expense of more communication.
frozen : no change
Source files
distributedTriSurfaceMesh.H
distributedTriSurfaceMesh.C
Definition at line 73 of file distributedTriSurfaceMesh.H.
Member Enumeration Documentation
distributionType
enum distributionType
Enumerator
FOLLOW
INDEPENDENT
FROZEN
Definition at line 81 of file distributedTriSurfaceMesh.H.
Constructor & Destructor Documentation
distributedTriSurfaceMesh() [1/3]
distributedTriSurfaceMesh (const IOobject & io, const triSurface & s, const dictionary & dict)
Construct from triSurface.
Definition at line 1287 of file distributedTriSurfaceMesh.C.
References Foam::endl(), forAll, Pstream::gatherList(), Foam::Info, InfoInFunction, Foam::max(), Foam::min(), UPstream::myProcNo(), UPstream::nProcs(), Foam::read(), Foam::reduce(), Pstream::scatterList(), and List< labelledTri >::size().
distributedTriSurfaceMesh() [2/3]
distributedTriSurfaceMesh (const IOobject & io)
Construct read. Does findInstance to find io.local().
Definition at line 1335 of file distributedTriSurfaceMesh.C.
References searchableSurface::bounds(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, regIOobject::fileModificationChecking, forAll, Pstream::gatherList(), Foam::Info, InfoInFunction, regIOobject::inotifyMaster, Foam::max(), Foam::min(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, UPstream::myProcNo(), UPstream::nProcs(), IOobject::objectPath(), UPstream::parRun(), IOobject::readOpt(), Foam::reduce(), Pstream::scatterList(), List< labelledTri >::size(), regIOobject::timeStampMaster, and distributedTriSurfaceMesh::writeStats().
distributedTriSurfaceMesh() [3/3]
distributedTriSurfaceMesh (const IOobject & io, const dictionary & dict)
Construct from dictionary (used by searchableSurface).
Does read. Does findInstance to find io.local().
Definition at line 1414 of file distributedTriSurfaceMesh.C.
References searchableSurface::bounds(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, regIOobject::fileModificationChecking, forAll, Pstream::gatherList(), Foam::Info, InfoInFunction, regIOobject::inotifyMaster, Foam::max(), Foam::min(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, UPstream::myProcNo(), UPstream::nProcs(), IOobject::objectPath(), UPstream::parRun(), IOobject::readOpt(), Foam::reduce(), Pstream::scatterList(), List< labelledTri >::size(), regIOobject::timeStampMaster, and distributedTriSurfaceMesh::writeStats().
~distributedTriSurfaceMesh()
~distributedTriSurfaceMesh () virtual
Destructor.
Definition at line 1498 of file distributedTriSurfaceMesh.C.
References distributedTriSurfaceMesh::clearOut().
Member Function Documentation
TypeName()
TypeName ("distributedTriSurfaceMesh")
Runtime type information.
clearOut()
void clearOut ()
Clear storage.
Definition at line 1504 of file distributedTriSurfaceMesh.C.
References triSurfaceMesh::clearOut().
Referenced by distributedTriSurfaceMesh::distribute(), and distributedTriSurfaceMesh::~distributedTriSurfaceMesh().
globalTris()
const Foam::globalIndex & globalTris () const
Triangle indexing (demand driven)
Definition at line 1513 of file distributedTriSurfaceMesh.C.
References distributedTriSurfaceMesh::findNearest(), and List< labelledTri >::size().
Referenced by distributedTriSurfaceMesh::findNearest(), and distributedTriSurfaceMesh::globalSize().
hasVolumeType()
virtual bool hasVolumeType () const inline virtual
Whether supports volume type below. I.e. whether is closed.
Not supported.
Reimplemented from triSurfaceMesh.
Definition at line 343 of file distributedTriSurfaceMesh.H.
globalSize()
virtual label globalSize () const inline virtual
Range of global indices that can be returned.
Reimplemented from searchableSurface.
Definition at line 349 of file distributedTriSurfaceMesh.H.
References distributedTriSurfaceMesh::distribute(), HashTableCore::end(), Foam::faceMap(), distributedTriSurfaceMesh::findLineAll(), distributedTriSurfaceMesh::findLineAny(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::getField(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), distributedTriSurfaceMesh::getVolumeType(), distributedTriSurfaceMesh::globalTris(), distributedTriSurfaceMesh::overlappingSurface(), globalIndex::size(), distributedTriSurfaceMesh::writeObject(), and distributedTriSurfaceMesh::writeStats().
findNearest()
void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info) const virtual
Reimplemented from triSurfaceMesh.
Definition at line 1524 of file distributedTriSurfaceMesh.C.
References mapDistribute::distribute(), forAll, distributedTriSurfaceMesh::globalTris(), Foam::magSqr(), UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), Foam::returnReduce(), mapDistribute::reverseDistribute(), List< T >::setSize(), List< T >::size(), globalIndex::toGlobal(), and triSurfaceSearch::tree().
Referenced by distributedTriSurfaceMesh::globalSize(), and distributedTriSurfaceMesh::globalTris().
findLine()
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Find first intersection on segment from start to end.
Note: searchableSurfacesQueries expects no intersection to be found if start==end. Is problem?
Reimplemented from triSurfaceMesh.
Definition at line 1681 of file distributedTriSurfaceMesh.C.
References distributedTriSurfaceMesh::findLineAny().
findLineAny()
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Return any intersection on segment from start to end.
Reimplemented from triSurfaceMesh.
Definition at line 1698 of file distributedTriSurfaceMesh.C.
References distributedTriSurfaceMesh::findLineAll().
Referenced by distributedTriSurfaceMesh::findLine(), and distributedTriSurfaceMesh::globalSize().
findLineAll()
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit >> & info) const virtual
Get all intersections in order from start to end.
Reimplemented from triSurfaceMesh.
Definition at line 1715 of file distributedTriSurfaceMesh.C.
References List< T >::clear(), forAll, distributedTriSurfaceMesh::getRegion(), Foam::magSqr(), Foam::returnReduce(), List< T >::setSize(), and List< T >::size().
Referenced by distributedTriSurfaceMesh::findLineAny(), and distributedTriSurfaceMesh::globalSize().
getRegion()
void getRegion (const List< pointIndexHit > & info, labelList & region) const virtual
From a set of points and indices get the region.
Reimplemented from triSurfaceMesh.
Definition at line 1829 of file distributedTriSurfaceMesh.C.
References forAll, distributedTriSurfaceMesh::getNormal(), UList< T >::operator[](), UPstream::parRun(), mapDistribute::reverseDistribute(), List< T >::setSize(), and List< T >::size().
Referenced by distributedTriSurfaceMesh::findLineAll(), and distributedTriSurfaceMesh::globalSize().
getNormal()
void getNormal (const List< pointIndexHit > & info, vectorField & normal) const virtual
From a set of points and indices get the normal.
Reimplemented from triSurfaceMesh.
Definition at line 1889 of file distributedTriSurfaceMesh.C.
References forAll, distributedTriSurfaceMesh::getField(), triSurfaceMesh::getNormal(), Foam::mag(), UPstream::parRun(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), mapDistribute::reverseDistribute(), List< T >::setSize(), and List< T >::size().
Referenced by distributedTriSurfaceMesh::getRegion(), and distributedTriSurfaceMesh::globalSize().
getVolumeType()
void getVolumeType (const pointField & points, List< volumeType > & volType) const virtual
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Reimplemented from triSurfaceMesh.
Definition at line 1994 of file distributedTriSurfaceMesh.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and distributedTriSurfaceMesh::overlappingSurface().
Referenced by distributedTriSurfaceMesh::getField(), and distributedTriSurfaceMesh::globalSize().
distribute()
void distribute (const List< treeBoundBox > & bbs, const bool keepNonLocal, autoPtr< mapDistribute > & faceMap, autoPtr< mapDistribute > & pointMap) virtual
Set bounds of surface. Bounds currently set as list of.
bounding boxes. Will do redistribution of surface to locally have all triangles overlapping bounds. Larger bounds: more triangles (memory), more fully local tests (quick). keepNonLocal = true : keep triangles that do not overlap any processor bounds. Should really be split into a routine to determine decomposition and one that does actual distribution but determining decomposition with duplicate triangle merging requires same amount as work as actual distribution.
Reimplemented from searchableSurface.
Definition at line 2048 of file distributedTriSurfaceMesh.C.
References Foam::DelaunayMeshTools::allPoints(), UPstream::blocking, searchableSurface::bounds(), distributedTriSurfaceMesh::clearOut(), Foam::endl(), Foam::exit(), Foam::faceMap(), Foam::FatalError, FatalErrorInFunction, distributedTriSurfaceMesh::FOLLOW, forAll, distributedTriSurfaceMesh::FROZEN, Pstream::gatherList(), Foam::identity(), distributedTriSurfaceMesh::INDEPENDENT, Foam::Info, InfoInFunction, Foam::max(), Foam::min(), UPstream::myProcNo(), UPstream::nProcs(), triSurface::operator=(), distributedTriSurfaceMesh::overlappingSurface(), triSurface::patches(), triSurfaceMesh::points(), PrimitivePatch< Face, FaceList, PointField, PointType >::points(), Foam::reduce(), autoPtr< T >::reset(), Pstream::scatterList(), dictionary::set(), List< T >::setSize(), List< T >::size(), triSurfaceMesh::size(), List< labelledTri >::size(), triSurface::triSurface(), distributedTriSurfaceMesh::writeObject(), and List< T >::xfer().
Referenced by distributedTriSurfaceMesh::globalSize(), and distributedTriSurfaceMesh::overlappingSurface().
getField()
void getField (const List< pointIndexHit > & info, labelList & values) const virtual
WIP. From a set of hits (points and.
indices) get the specified field. Misses do not get set.
Reimplemented from triSurfaceMesh.
Definition at line 1939 of file distributedTriSurfaceMesh.C.
References fld(), forAll, triSurfaceMesh::getField(), distributedTriSurfaceMesh::getVolumeType(), UPstream::parRun(), mapDistribute::reverseDistribute(), List< T >::setSize(), and List< T >::size().
Referenced by distributedTriSurfaceMesh::getNormal(), and distributedTriSurfaceMesh::globalSize().
overlappingSurface()
Foam::triSurface overlappingSurface (const triSurface & s, const List< treeBoundBox > & bbs, labelList & subPointMap, labelList & subFaceMap) static
Subset the part of surface that is overlapping bounds.
Definition at line 2007 of file distributedTriSurfaceMesh.C.
References distributedTriSurfaceMesh::distribute(), f(), forAll, VectorSpace< Form, Cmpt, Ncmpts >::max, Foam::max(), VectorSpace< Form, Cmpt, Ncmpts >::min, PrimitivePatch< Face, FaceList, PointField, PointType >::points(), and List< T >::size().
Referenced by distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::getVolumeType(), and distributedTriSurfaceMesh::globalSize().
writeStats()
void writeStats (Ostream & os) const
Print some stats. Parallel aware version of.
triSurface::writeStats.
Definition at line 2410 of file distributedTriSurfaceMesh.C.
References PatchTools::calcBounds(), Foam::endl(), boundBox::max(), boundBox::min(), PrimitivePatch< labelledTri, ::Foam::List, pointField, point >::nPoints(), Foam::reduce(), Foam::returnReduce(), and List< labelledTri >::size().
Referenced by distributedTriSurfaceMesh::distributedTriSurfaceMesh(), and distributedTriSurfaceMesh::globalSize().
writeObject()
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const virtual
Write using given format, version and compression.
Do not use the triSurfaceMesh::writeObject since it would filter out empty regions. These need to be preserved in case we want to make decisions based on the number of regions.
Reimplemented from triSurfaceMesh.
Definition at line 2376 of file distributedTriSurfaceMesh.C.
References IOstream::ASCII, IOobject::instance(), Foam::isFile(), Foam::mkDir(), IOobject::objectPath(), fileName::path(), and regIOobject::writeObject().
Referenced by distributedTriSurfaceMesh::distribute(), and distributedTriSurfaceMesh::globalSize().
Member Data Documentation
distributionTypeNames_
const Foam::NamedEnum< Foam::distributedTriSurfaceMesh::distributionType, 3 > distributionTypeNames_ static
Definition at line 88 of file distributedTriSurfaceMesh.H.
Referenced by NamedEnum< directionType, 3 >::names().
The documentation for this class was generated from the following files:
src/parallel/distributed/distributedTriSurfaceMesh/distributedTriSurfaceMesh.H
src/parallel/distributed/distributedTriSurfaceMesh/distributedTriSurfaceMesh.C
src/parallel/distributed/distributedTriSurfaceMesh/distributedTriSurfaceMeshTemplates.C