OpenFOAM: ptscotchDecomp Class Reference
ptscotchDecomp Class Reference
PTScotch domain decomposition. For the main details about how to define the strategies, see scotchDecomp.
Public Member Functions
TypeName ("ptscotch")
Runtime type information.
ptscotchDecomp (const dictionary &decompositionDict)
Construct given the decomposition dictionary and mesh.
virtual ~ptscotchDecomp ()
Destructor.
virtual bool parallelAware () const
Is method parallel aware (i.e. does it synchronize domains across.
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const polyMesh &mesh, const labelList &agglom, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)
Return for every coordinate the wanted processor number. Explicitly.
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual labelList decompose (const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &, const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp)
Helper: apply constraints to a decomposition. This gives.
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Helper: determine (local or global) cellCells and face weights.
Protected Attributes inherited from decompositionMethod
const dictionary & decompositionDict_
label nProcessors_
PtrList< decompositionConstraint > constraints_
Optional constraints.
Detailed Description
PTScotch domain decomposition. For the main details about how to define the strategies, see scotchDecomp.
Nonetheless, when decomposing in parallel, using writeGraph=true will write out .dgr files for debugging. For example, use these files with dgpart as follows:
mpirun -np 4 dgpart 2 'region0_%r.dgr'
where:
r gets replaced by current processor rank
it will decompose into 2 domains
See also
Foam::scotchDecomp
Source files
ptscotchDecomp.H
ptscotchDecomp.C
Definition at line 62 of file ptscotchDecomp.H.
Constructor & Destructor Documentation
ptscotchDecomp()
ptscotchDecomp (const dictionary & decompositionDict)
Construct given the decomposition dictionary and mesh.
Definition at line 99 of file dummyPtscotchDecomp.C.
~ptscotchDecomp()
virtual ~ptscotchDecomp () inline virtual
Destructor.
Definition at line 111 of file ptscotchDecomp.H.
Member Function Documentation
TypeName()
TypeName ("ptscotch")
Runtime type information.
parallelAware()
virtual bool parallelAware () const inline virtual
Is method parallel aware (i.e. does it synchronize domains across.
proc boundaries)
Implements decompositionMethod.
Definition at line 117 of file ptscotchDecomp.H.
References decompositionMethod::decompose(), mesh, and points.
decompose() [1/3]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) virtual
Return for every coordinate the wanted processor number. Use the.
mesh connectivity (if needed). See note on weights in scotchDecomp.H
Implements decompositionMethod.
Definition at line 110 of file dummyPtscotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, notImplementedMessage, and List< label >::null().
decompose() [2/3]
Foam::labelList decompose (const polyMesh & mesh, const labelList & agglom, const pointField & regionPoints, const scalarField & regionWeights) virtual
Return for every coordinate the wanted processor number. Gets.
passed agglomeration map (from fine to coarse cells) and coarse cell location. Can be overridden by decomposers that provide this functionality natively. See note on weights in scotchDecomp.H
Reimplemented from decompositionMethod.
Definition at line 124 of file dummyPtscotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, notImplementedMessage, and List< label >::null().
decompose() [3/3]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) virtual
Return for every coordinate the wanted processor number. Explicitly.
provided mesh connectivity. The connectivity is equal to mesh.cellCells() except for
in parallel the cell numbers are global cell numbers (starting from 0 at processor0 and then incrementing all through the processors)
the connections are across coupled patches See note on weights in scotchDecomp.H
Implements decompositionMethod.
Definition at line 139 of file dummyPtscotchDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, notImplementedMessage, and List< label >::null().
The documentation for this class was generated from the following files:
src/parallel/decompose/ptscotchDecomp/ptscotchDecomp.H
src/dummyThirdParty/ptscotchDecomp/dummyPtscotchDecomp.C
src/parallel/decompose/ptscotchDecomp/ptscotchDecomp.C