OpenFOAM: fvFieldDecomposer::processorVolPatchFieldDecomposer Class Reference
fvFieldDecomposer::processorVolPatchFieldDecomposer Class Reference
Processor patch field decomposer class. Maps either owner or.
Public Member Functions
processorVolPatchFieldDecomposer (const fvMesh &mesh, const labelUList &addressingSlice)
Construct given addressing.
label size () const
bool direct () const
bool hasUnmapped () const
Are there unmapped values.
const labelUList & directAddressing () const
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()
Null constructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
Processor patch field decomposer class. Maps either owner or.
neighbour data (no interpolate anymore - processorFvPatchField holds neighbour data)
Definition at line 106 of file fvFieldDecomposer.H.
Constructor & Destructor Documentation
processorVolPatchFieldDecomposer()
processorVolPatchFieldDecomposer (const fvMesh & mesh, const labelUList & addressingSlice)
Construct given addressing.
Definition at line 49 of file fvFieldDecomposer.C.
References polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, Foam::mag(), fvFieldDecomposer::processorSurfacePatchFieldDecomposer::processorSurfacePatchFieldDecomposer(), and List< T >::size().
Referenced by fvFieldDecomposer::patchFieldDecomposer::patchFieldDecomposer().
Member Function Documentation
size()
label size () const inline virtual
Implements FieldMapper.
Definition at line 126 of file fvFieldDecomposer.H.
References List< T >::size().
direct()
bool direct () const inline virtual
Implements FieldMapper.
Definition at line 131 of file fvFieldDecomposer.H.
hasUnmapped()
bool hasUnmapped () const inline virtual
Are there unmapped values.
Implements FieldMapper.
Definition at line 137 of file fvFieldDecomposer.H.
directAddressing()
const labelUList& directAddressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 142 of file fvFieldDecomposer.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/fvFieldDecomposer.H
src/parallel/decompose/decompose/fvFieldDecomposer.C