OpenFOAM: singleProcessorFaceSetsConstraint Class Reference
singleProcessorFaceSetsConstraint Class Reference
Public Member Functions
TypeName ("singleProcessorFaceSets")
Runtime type information.
singleProcessorFaceSetsConstraint (const dictionary &constraintsDict, const word &type)
Construct with generic dictionary with optional entry for type.
singleProcessorFaceSetsConstraint (const List< Tuple2< word, label >> &setNameAndProcs)
Construct from components.
virtual ~singleProcessorFaceSetsConstraint ()
Destructor.
virtual void add (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
Add my constraints to list of constraints.
virtual void apply (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &decomposition) const
Apply any additional post-decomposition constraints.
Public Member Functions inherited from decompositionConstraint
TypeName ("decompositionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionConstraint, dictionary,(const dictionary &constraintsDict, const word &type),(constraintsDict, type))
decompositionConstraint (const dictionary &constraintsDict, const word &type)
Construct with generic dictionary with optional entry for type.
virtual ~decompositionConstraint ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from decompositionConstraint
static autoPtr< decompositionConstraint > New (const dictionary &constraintsDict, const word &type)
Return a reference to the selected decompositionConstraint.
Protected Attributes inherited from decompositionConstraint
dictionary coeffDict_
Model coefficients dictionary.
Detailed Description
Definition at line 53 of file singleProcessorFaceSetsConstraint.H.
Constructor & Destructor Documentation
singleProcessorFaceSetsConstraint() [1/2]
singleProcessorFaceSetsConstraint (const dictionary & constraintsDict, const word & type)
Construct with generic dictionary with optional entry for type.
Definition at line 53 of file singleProcessorFaceSetsConstraint.C.
References Foam::endl(), forAll, Foam::Info, and Foam::type().
singleProcessorFaceSetsConstraint() [2/2]
singleProcessorFaceSetsConstraint (const List< Tuple2< word, label >> & setNameAndProcs)
Construct from components.
Definition at line 78 of file singleProcessorFaceSetsConstraint.C.
References singleProcessorFaceSetsConstraint::add(), Foam::endl(), forAll, Foam::Info, and Foam::type().
~singleProcessorFaceSetsConstraint()
virtual ~singleProcessorFaceSetsConstraint () inline virtual
Destructor.
Definition at line 85 of file singleProcessorFaceSetsConstraint.H.
References singleProcessorFaceSetsConstraint::add(), singleProcessorFaceSetsConstraint::apply(), and mesh.
Member Function Documentation
TypeName()
TypeName ("singleProcessorFaceSets")
Runtime type information.
add()
void add (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const virtual
Add my constraints to list of constraints.
Implements decompositionConstraint.
Definition at line 103 of file singleProcessorFaceSetsConstraint.C.
References PtrList< T >::append(), List< T >::append(), singleProcessorFaceSetsConstraint::apply(), Foam::endl(), f(), polyMesh::faces(), forAll, forAllConstIter(), Foam::Info, primitiveMesh::nFaces(), primitiveMesh::nPoints(), pFaces, primitiveMesh::pointFaces(), Foam::reduce(), List< T >::setSize(), UPtrList< T >::size(), HashTable< T, Key, Hash >::size(), HashTable< T, Key, Hash >::sortedToc(), syncTools::syncFaceList(), syncTools::syncPointList(), and Foam::type().
Referenced by singleProcessorFaceSetsConstraint::singleProcessorFaceSetsConstraint(), and singleProcessorFaceSetsConstraint::~singleProcessorFaceSetsConstraint().
apply()
void apply (const polyMesh & mesh, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & decomposition) const virtual
Apply any additional post-decomposition constraints.
Reimplemented from decompositionConstraint.
Definition at line 227 of file singleProcessorFaceSetsConstraint.C.
References Foam::endl(), f(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), forAll, Foam::Info, primitiveMesh::isInternalFace(), primitiveMesh::nPoints(), pFaces, primitiveMesh::pointFaces(), Foam::reduce(), syncTools::syncPointList(), and Foam::type().
Referenced by singleProcessorFaceSetsConstraint::add(), and singleProcessorFaceSetsConstraint::~singleProcessorFaceSetsConstraint().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionConstraints/singleProcessorFaceSets/singleProcessorFaceSetsConstraint.H
src/parallel/decompose/decompositionMethods/decompositionConstraints/singleProcessorFaceSets/singleProcessorFaceSetsConstraint.C