OpenFOAM: decompositionConstraint Class Reference
decompositionConstraint Class Reference abstract
Public Member Functions
TypeName ("decompositionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionConstraint, dictionary,(const dictionary &constraintsDict, const word &type),(constraintsDict, type))
decompositionConstraint (const dictionary &constraintsDict, const word &type)
Construct with generic dictionary with optional entry for type.
virtual ~decompositionConstraint ()
Destructor.
virtual void add (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const =0
Add my constraints to list of constraints.
virtual void apply (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &decomposition) const
Apply any additional post-decomposition constraints. Usually no.
Static Public Member Functions
static autoPtr< decompositionConstraint > New (const dictionary &constraintsDict, const word &type)
Return a reference to the selected decompositionConstraint.
Protected Attributes
dictionary coeffDict_
Model coefficients dictionary.
Detailed Description
Source files
decompositionConstraint.H
decompositionConstraint.C
Definition at line 54 of file decompositionConstraint.H.
Constructor & Destructor Documentation
decompositionConstraint()
decompositionConstraint (const dictionary & constraintsDict, const word & type)
Construct with generic dictionary with optional entry for type.
Definition at line 39 of file decompositionConstraint.C.
References decompositionConstraint::New().
~decompositionConstraint()
~decompositionConstraint () virtual
Destructor.
Definition at line 82 of file decompositionConstraint.C.
Member Function Documentation
TypeName()
TypeName ("decompositionConstraint")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , decompositionConstraint , dictionary , (const dictionary &constraintsDict, const word &type) , (constraintsDict, type))
New()
Foam::autoPtr< Foam::decompositionConstraint > New (const dictionary & constraintsDict, const word & type) static
Return a reference to the selected decompositionConstraint.
Definition at line 53 of file decompositionConstraint.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::Info, and Foam::nl.
Referenced by decompositionConstraint::decompositionConstraint(), and decompositionMethod::decompositionMethod().
add()
virtual void add (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const pure virtual
Add my constraints to list of constraints.
Implemented in singleProcessorFaceSetsConstraint, preservePatchesConstraint, preserveFaceZonesConstraint, preserveBafflesConstraint, and refinementHistoryConstraint.
apply()
virtual void apply (const polyMesh & mesh, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & decomposition) const inline virtual
Apply any additional post-decomposition constraints. Usually no.
need to do anything since decomposition method should have already obeyed the constraints
Reimplemented in singleProcessorFaceSetsConstraint, preservePatchesConstraint, preserveFaceZonesConstraint, preserveBafflesConstraint, and refinementHistoryConstraint.
Definition at line 134 of file decompositionConstraint.H.
Member Data Documentation
coeffDict_
dictionary coeffDict_ protected
Model coefficients dictionary.
Definition at line 61 of file decompositionConstraint.H.
Referenced by preserveBafflesConstraint::add().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionConstraints/decompositionConstraint/decompositionConstraint.H
src/parallel/decompose/decompositionMethods/decompositionConstraints/decompositionConstraint/decompositionConstraint.C