OpenFOAM: structuredDecomp Class Reference
structuredDecomp Class Reference
Decomposition by walking out decomposition of patch cells mesh.
Public Member Functions
TypeName ("structured")
Runtime type information.
structuredDecomp (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~structuredDecomp ()
Destructor.
virtual bool parallelAware () const
Is method parallel aware (i.e. does it synchronize domains across.
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)
Return for every coordinate the wanted processor number. Explicitly.
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual labelList decompose (const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &, const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp)
Helper: apply constraints to a decomposition. This gives.
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Helper: determine (local or global) cellCells and face weights.
Protected Attributes inherited from decompositionMethod
const dictionary & decompositionDict_
label nProcessors_
PtrList< decompositionConstraint > constraints_
Optional constraints.
Detailed Description
Decomposition by walking out decomposition of patch cells mesh.
Source files
structuredDecomp.H
structuredDecomp.C
Definition at line 46 of file structuredDecomp.H.
Constructor & Destructor Documentation
structuredDecomp()
structuredDecomp (const dictionary & decompositionDict)
Construct given the decomposition dictionary.
Definition at line 49 of file structuredDecomp.C.
References decompositionMethod::nDomains(), decompositionMethod::New(), and dictionary::set().
~structuredDecomp()
virtual ~structuredDecomp () inline virtual
Destructor.
Definition at line 79 of file structuredDecomp.H.
References structuredDecomp::decompose(), mesh, structuredDecomp::parallelAware(), and points.
Member Function Documentation
TypeName()
TypeName ("structured")
Runtime type information.
parallelAware()
bool parallelAware () const virtual
Is method parallel aware (i.e. does it synchronize domains across.
proc boundaries)
Implements decompositionMethod.
Definition at line 62 of file structuredDecomp.C.
References structuredDecomp::decompose().
Referenced by structuredDecomp::~structuredDecomp().
decompose() [1/2]
Foam::labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) virtual
Return for every coordinate the wanted processor number. Use the.
mesh connectivity (if needed)
Implements decompositionMethod.
Definition at line 69 of file structuredDecomp.C.
References polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), fvMeshSubset::cellMap(), FaceCellWave< Type, TrackingData >::data(), Foam::endl(), polyPatch::faceCells(), forAll, forAllConstIter(), polyMesh::globalData(), HashSet< Key, Hash >::insert(), primitiveMesh::nCells(), primitiveMesh::nFaces(), globalMeshData::nTotalCells(), polyBoundaryMesh::patchSet(), fvMeshSubset::setLargeCellSubset(), List< T >::size(), UPtrList< T >::size(), polyPatch::start(), fvMeshSubset::subMesh(), and WarningInFunction.
Referenced by structuredDecomp::parallelAware(), and structuredDecomp::~structuredDecomp().
decompose() [2/2]
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) virtual
Return for every coordinate the wanted processor number. Explicitly.
provided connectivity - does not use mesh_.
Implements decompositionMethod.
Definition at line 171 of file structuredDecomp.C.
References NotImplemented, and List< label >::null().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/structuredDecomp/structuredDecomp.H
src/parallel/decompose/decompositionMethods/structuredDecomp/structuredDecomp.C