OpenFOAM: fvFieldDecomposer Class Reference
fvFieldDecomposer Class Reference
Finite Volume volume and surface field decomposer.
Classes
class patchFieldDecomposer
Patch field decomposer class.
class processorSurfacePatchFieldDecomposer
Processor patch field decomposer class. Surface field is assumed.
class processorVolPatchFieldDecomposer
Processor patch field decomposer class. Maps either owner or.
Public Member Functions
fvFieldDecomposer (const fvMesh &completeMesh, const fvMesh &procMesh, const labelList &faceAddressing, const labelList &cellAddressing, const labelList &boundaryAddressing)
Construct from components.
~fvFieldDecomposer ()
Destructor.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > decomposeField (const GeometricField< Type, fvPatchField, volMesh > &field, const bool allowUnknownPatchFields=false) const
Decompose volume field.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > decomposeField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field) const
Decompose surface field.
template<class GeoField >
void decomposeFields (const PtrList< GeoField > &fields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > decomposeField (const GeometricField< Type, fvPatchField, volMesh > &field, const bool allowUnknownPatchFields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > decomposeField (const GeometricField< Type, fvsPatchField, surfaceMesh > &field) const
Detailed Description
Finite Volume volume and surface field decomposer.
Source files
fvFieldDecomposer.H
fvFieldDecomposer.C
fvFieldDecomposerDecomposeFields.C
Definition at line 53 of file fvFieldDecomposer.H.
Constructor & Destructor Documentation
fvFieldDecomposer()
fvFieldDecomposer (const fvMesh & completeMesh, const fvMesh & procMesh, const labelList & faceAddressing, const labelList & cellAddressing, const labelList & boundaryAddressing)
Construct from components.
Definition at line 116 of file fvFieldDecomposer.C.
References fvMesh::boundary(), forAll, and patchi.
~fvFieldDecomposer()
~fvFieldDecomposer ()
Destructor.
Definition at line 189 of file fvFieldDecomposer.C.
References forAll, and patchi.
Referenced by fvFieldDecomposer::processorSurfacePatchFieldDecomposer::weights().
Member Function Documentation
decomposeField() [1/4]
tmp<GeometricField<Type, fvPatchField, volMesh> > decomposeField (const GeometricField< Type, fvPatchField, volMesh > & field, const bool allowUnknownPatchFields = false) const
Decompose volume field.
Referenced by fvFieldDecomposer::decomposeField(), and fvFieldDecomposer::processorSurfacePatchFieldDecomposer::weights().
decomposeField() [2/4]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > decomposeField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field) const
Decompose surface field.
decomposeFields()
void decomposeFields (const PtrList< GeoField > & fields) const
Definition at line 322 of file fvFieldDecomposerDecomposeFields.C.
References forAll, and write().
Referenced by fvFieldDecomposer::decomposeField(), and fvFieldDecomposer::processorSurfacePatchFieldDecomposer::weights().
decomposeField() [3/4]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > decomposeField (const GeometricField< Type, fvPatchField, volMesh > & field, const bool allowUnknownPatchFields) const
Definition at line 38 of file fvFieldDecomposerDecomposeFields.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvFieldDecomposer::decomposeField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::FatalError, FatalErrorInFunction, forAll, IOobject::name(), patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and GeometricField< Type, PatchField, GeoMesh >::ref().
decomposeField() [4/4]
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > decomposeField (const GeometricField< Type, fvsPatchField, surfaceMesh > & field) const
Definition at line 165 of file fvFieldDecomposerDecomposeFields.C.
References Foam::abort(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvFieldDecomposer::decomposeFields(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::FatalError, FatalErrorInFunction, forAll, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), p, patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and GeometricField< Type, PatchField, GeoMesh >::ref().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/fvFieldDecomposer.H
src/parallel/decompose/decompose/fvFieldDecomposer.C
src/parallel/decompose/decompose/fvFieldDecomposerDecomposeFields.C