OpenFOAM: simpleGeomDecomp Class Reference
simpleGeomDecomp Class Reference
Public Member Functions
TypeName ("simple")
Runtime type information.
simpleGeomDecomp (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~simpleGeomDecomp ()
Destructor.
virtual bool parallelAware () const
Is method parallel aware (i.e. does it synchronize domains across.
virtual labelList decompose (const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const pointField &, const scalarField &)
Return for every coordinate the wanted processor number.
virtual labelList decompose (const polyMesh &, const pointField &points)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &, const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)
Explicitly provided connectivity.
Public Member Functions inherited from geomDecomp
geomDecomp (const dictionary &decompositionDict, const word &derivedType)
Construct given the decomposition dictionary.
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp)
Helper: apply constraints to a decomposition. This gives.
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Helper: determine (local or global) cellCells and face weights.
Protected Attributes inherited from geomDecomp
const dictionary & geomDecomDict_
Vector< label > n_
scalar delta_
tensor rotDelta_
Protected Attributes inherited from decompositionMethod
const dictionary & decompositionDict_
label nProcessors_
PtrList< decompositionConstraint > constraints_
Optional constraints.
Detailed Description
Source files
simpleGeomDecomp.H
simpleGeomDecomp.C
Definition at line 45 of file simpleGeomDecomp.H.
Constructor & Destructor Documentation
simpleGeomDecomp()
simpleGeomDecomp (const dictionary & decompositionDict)
Construct given the decomposition dictionary.
Definition at line 300 of file simpleGeomDecomp.C.
References simpleGeomDecomp::decompose().
~simpleGeomDecomp()
virtual ~simpleGeomDecomp () inline virtual
Destructor.
Definition at line 88 of file simpleGeomDecomp.H.
Member Function Documentation
TypeName()
TypeName ("simple")
Runtime type information.
parallelAware()
virtual bool parallelAware () const inline virtual
Is method parallel aware (i.e. does it synchronize domains across.
proc boundaries)
Implements decompositionMethod.
Definition at line 94 of file simpleGeomDecomp.H.
References simpleGeomDecomp::decompose().
decompose() [1/5]
Foam::labelList decompose (const pointField &) virtual
Like decompose but with uniform weights on the points.
Implements geomDecomp.
Definition at line 309 of file simpleGeomDecomp.C.
References Foam::DelaunayMeshTools::allPoints(), UPstream::master(), UPstream::masterNo(), UPstream::nProcs(), UPstream::parRun(), points, UPstream::scheduled, List< T >::setSize(), and List< T >::size().
Referenced by simpleGeomDecomp::decompose(), simpleGeomDecomp::parallelAware(), and simpleGeomDecomp::simpleGeomDecomp().
decompose() [2/5]
Foam::labelList decompose (const pointField & points, const scalarField & pointWeights) virtual
Return for every coordinate the wanted processor number.
Implements geomDecomp.
Definition at line 383 of file simpleGeomDecomp.C.
References Foam::DelaunayMeshTools::allPoints(), UPstream::master(), UPstream::masterNo(), UPstream::nProcs(), UPstream::parRun(), UPstream::scheduled, List< T >::setSize(), and List< T >::size().
decompose() [3/5]
virtual labelList decompose (const polyMesh & mesh, const pointField & points) inline virtual
Like decompose but with uniform weights on the points.
Reimplemented from decompositionMethod.
Definition at line 105 of file simpleGeomDecomp.H.
References simpleGeomDecomp::decompose().
decompose() [4/5]
virtual labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) inline virtual
Return for every coordinate the wanted processor number. Use the.
mesh connectivity (if needed)
Implements decompositionMethod.
Definition at line 111 of file simpleGeomDecomp.H.
References simpleGeomDecomp::decompose().
decompose() [5/5]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) inline virtual
Explicitly provided connectivity.
Implements decompositionMethod.
Definition at line 122 of file simpleGeomDecomp.H.
References simpleGeomDecomp::decompose().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/simpleGeomDecomp/simpleGeomDecomp.H
src/parallel/decompose/decompositionMethods/simpleGeomDecomp/simpleGeomDecomp.C