OpenFOAM: geomDecomp Class Reference
geomDecomp Class Reference abstract
Geometrical domain decomposition.
Public Member Functions
geomDecomp (const dictionary &decompositionDict, const word &derivedType)
Construct given the decomposition dictionary.
virtual labelList decompose (const pointField &points, const scalarField &pointWeights)=0
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &)=0
Like decompose but with uniform weights on the points.
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual bool parallelAware () const =0
Is method parallel aware (i.e. does it synchronize domains across.
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights)=0
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const polyMesh &, const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)=0
Return for every coordinate the wanted processor number.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp)
Helper: apply constraints to a decomposition. This gives.
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Protected Attributes
const dictionary & geomDecomDict_
Vector< label > n_
scalar delta_
tensor rotDelta_
Protected Attributes inherited from decompositionMethod
const dictionary & decompositionDict_
label nProcessors_
PtrList< decompositionConstraint > constraints_
Optional constraints.
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Helper: determine (local or global) cellCells and face weights.
Detailed Description
Geometrical domain decomposition.
Source files
geomDecomp.H
geomDecomp.C
Definition at line 47 of file geomDecomp.H.
Constructor & Destructor Documentation
geomDecomp()
geomDecomp (const dictionary & decompositionDict, const word & derivedType)
Construct given the decomposition dictionary.
and the derived type name
Definition at line 31 of file geomDecomp.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and Foam::sqr().
Member Function Documentation
decompose() [1/2]
virtual labelList decompose (const pointField & points, const scalarField & pointWeights) pure virtual
Return for every coordinate the wanted processor number.
Reimplemented from decompositionMethod.
Implemented in hierarchGeomDecomp, and simpleGeomDecomp.
Referenced by NamedEnum< directionType, 3 >::names().
decompose() [2/2]
virtual labelList decompose (const pointField &) pure virtual
Like decompose but with uniform weights on the points.
Reimplemented from decompositionMethod.
Implemented in hierarchGeomDecomp, and simpleGeomDecomp.
Member Data Documentation
geomDecomDict_
const dictionary& geomDecomDict_ protected
Definition at line 56 of file geomDecomp.H.
n_
Vector<label> n_ protected
Definition at line 58 of file geomDecomp.H.
delta_
scalar delta_ protected
Definition at line 59 of file geomDecomp.H.
rotDelta_
tensor rotDelta_ protected
Definition at line 60 of file geomDecomp.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/geomDecomp/geomDecomp.H
src/parallel/decompose/decompositionMethods/geomDecomp/geomDecomp.C