OpenFOAM: manualDecomp Class Reference
manualDecomp Class Reference
Decomposition given a cell-to-processor association in a file.
Public Member Functions
TypeName ("manual")
Runtime type information.
manualDecomp (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~manualDecomp ()
Destructor.
virtual bool parallelAware () const
Manual decompose does not care about proc boundaries - is all.
virtual labelList decompose (const polyMesh &mesh, const pointField &cc, const scalarField &cWeights)
Return for every coordinate the wanted processor number. Use the.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights)
Return for every coordinate the wanted processor number. Explicitly.
Public Member Functions inherited from decompositionMethod
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompositionDict),(decompositionDict))
decompositionMethod (const dictionary &decompositionDict)
Construct given the decomposition dictionary.
virtual ~decompositionMethod ()
Destructor.
label nDomains () const
virtual labelList decompose (const pointField &points, const scalarField &pointWeights)
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &, const pointField &)
Like decompose but with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights)
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints)
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc)
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections)
Helper: extract constraints:
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp)
Helper: apply constraints to a decomposition. This gives.
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections)
labelList decompose (const polyMesh &mesh, const scalarField &cWeights)
Decompose a mesh. Apply all constraints from decomposeParDict.
Additional Inherited Members
Static Public Member Functions inherited from decompositionMethod
static autoPtr< decompositionMethod > New (const dictionary &decompositionDict)
Return a reference to the selected decomposition method.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Helper: determine (local or global) cellCells and face weights.
Protected Attributes inherited from decompositionMethod
const dictionary & decompositionDict_
label nProcessors_
PtrList< decompositionConstraint > constraints_
Optional constraints.
Detailed Description
Decomposition given a cell-to-processor association in a file.
Source files
manualDecomp.H
manualDecomp.C
Definition at line 46 of file manualDecomp.H.
Constructor & Destructor Documentation
manualDecomp()
manualDecomp (const dictionary & decompositionDict)
Construct given the decomposition dictionary.
Definition at line 51 of file manualDecomp.C.
References manualDecomp::decompose().
~manualDecomp()
virtual ~manualDecomp () inline virtual
Destructor.
Definition at line 74 of file manualDecomp.H.
References manualDecomp::decompose(), mesh, and manualDecomp::parallelAware().
Member Function Documentation
TypeName()
TypeName ("manual")
Runtime type information.
parallelAware()
virtual bool parallelAware () const inline virtual
Manual decompose does not care about proc boundaries - is all.
up to the user.
Implements decompositionMethod.
Definition at line 82 of file manualDecomp.H.
Referenced by manualDecomp::~manualDecomp().
decompose() [1/2]
Foam::labelList decompose (const polyMesh & mesh, const pointField & cc, const scalarField & cWeights) virtual
Return for every coordinate the wanted processor number. Use the.
mesh connectivity (if needed)
Implements decompositionMethod.
Definition at line 65 of file manualDecomp.C.
References IOobject::AUTO_WRITE, Foam::endl(), Foam::exit(), polyMesh::facesInstance(), Foam::FatalError, FatalErrorInFunction, Foam::max(), mesh, Foam::min(), IOobject::MUST_READ, decompositionMethod::nProcessors_, and List< T >::size().
Referenced by manualDecomp::manualDecomp(), and manualDecomp::~manualDecomp().
decompose() [2/2]
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) inline virtual
Return for every coordinate the wanted processor number. Explicitly.
provided connectivity - does not use mesh_. The connectivity is equal to mesh.cellCells() except for
in parallel the cell numbers are global cell numbers (starting from 0 at processor0 and then incrementing all through the processors)
the connections are across coupled patches
Implements decompositionMethod.
Definition at line 104 of file manualDecomp.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/manualDecomp/manualDecomp.H
src/parallel/decompose/decompositionMethods/manualDecomp/manualDecomp.C