OpenFOAM: refinementHistoryConstraint Class Reference
refinementHistoryConstraint Class Reference
Constraint to keep all cells originating from refining the same cell onto the same processor. Reads polyMesh/refinementHistory.
Public Member Functions
TypeName ("refinementHistory")
Runtime type information.
refinementHistoryConstraint (const dictionary &constraintsDict, const word &type)
Construct with generic dictionary with optional entry for type.
refinementHistoryConstraint ()
Construct from components.
virtual ~refinementHistoryConstraint ()
Destructor.
virtual void add (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
Add my constraints to list of constraints.
virtual void apply (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &decomposition) const
Apply any additional post-decomposition constraints.
Public Member Functions inherited from decompositionConstraint
TypeName ("decompositionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionConstraint, dictionary,(const dictionary &constraintsDict, const word &type),(constraintsDict, type))
decompositionConstraint (const dictionary &constraintsDict, const word &type)
Construct with generic dictionary with optional entry for type.
virtual ~decompositionConstraint ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from decompositionConstraint
static autoPtr< decompositionConstraint > New (const dictionary &constraintsDict, const word &type)
Return a reference to the selected decompositionConstraint.
Protected Attributes inherited from decompositionConstraint
dictionary coeffDict_
Model coefficients dictionary.
Detailed Description
Constraint to keep all cells originating from refining the same cell onto the same processor. Reads polyMesh/refinementHistory.
Source files
refinementHistoryConstraint.H
refinementHistoryConstraint.C
Definition at line 50 of file refinementHistoryConstraint.H.
Constructor & Destructor Documentation
refinementHistoryConstraint() [1/2]
refinementHistoryConstraint (const dictionary & constraintsDict, const word & type)
Construct with generic dictionary with optional entry for type.
Definition at line 49 of file refinementHistoryConstraint.C.
References Foam::endl(), Foam::Info, and Foam::type().
refinementHistoryConstraint() [2/2]
refinementHistoryConstraint ()
Construct from components.
Definition at line 64 of file refinementHistoryConstraint.C.
References refinementHistoryConstraint::add(), Foam::endl(), Foam::Info, and Foam::type().
~refinementHistoryConstraint()
virtual ~refinementHistoryConstraint () inline virtual
Destructor.
Definition at line 76 of file refinementHistoryConstraint.H.
References refinementHistoryConstraint::add(), refinementHistoryConstraint::apply(), and mesh.
Member Function Documentation
TypeName()
TypeName ("refinementHistory")
Runtime type information.
add()
void add (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const virtual
Add my constraints to list of constraints.
Implements decompositionConstraint.
Definition at line 79 of file refinementHistoryConstraint.C.
References refinementHistory::active(), refinementHistory::add(), refinementHistoryConstraint::apply(), Foam::endl(), polyMesh::facesInstance(), objectRegistry::foundObject(), Foam::Info, objectRegistry::lookupObject(), mesh, polyMesh::meshSubDir, IOobject::NO_WRITE, IOobject::READ_IF_PRESENT, autoPtr< T >::reset(), Foam::type(), and autoPtr< T >::valid().
Referenced by refinementHistoryConstraint::refinementHistoryConstraint(), and refinementHistoryConstraint::~refinementHistoryConstraint().
apply()
void apply (const polyMesh & mesh, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & decomposition) const virtual
Apply any additional post-decomposition constraints.
Reimplemented from decompositionConstraint.
Definition at line 145 of file refinementHistoryConstraint.C.
References refinementHistory::active(), refinementHistory::apply(), polyMesh::facesInstance(), objectRegistry::foundObject(), objectRegistry::lookupObject(), mesh, polyMesh::meshSubDir, IOobject::NO_WRITE, IOobject::READ_IF_PRESENT, autoPtr< T >::reset(), and autoPtr< T >::valid().
Referenced by refinementHistoryConstraint::add(), and refinementHistoryConstraint::~refinementHistoryConstraint().
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionConstraints/refinementHistory/refinementHistoryConstraint.H
src/parallel/decompose/decompositionMethods/decompositionConstraints/refinementHistory/refinementHistoryConstraint.C