OpenFOAM: fvFieldReconstructor Class Reference
fvFieldReconstructor Class Reference
Finite volume reconstructor for volume and surface fields.
Classes
class fvPatchFieldReconstructor
Mapper for sizing only - does not do any actual mapping.
Public Member Functions
fvFieldReconstructor (fvMesh &mesh, const PtrList< fvMesh > &procMeshes, const PtrList< labelIOList > &faceProcAddressing, const PtrList< labelIOList > &cellProcAddressing, const PtrList< labelIOList > &boundaryProcAddressing)
Construct from components.
label nReconstructed () const
Return number of fields reconstructed.
template<class Type >
tmp< DimensionedField< Type, volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject, const PtrList< DimensionedField< Type, volMesh >> &procFields) const
Reconstruct volume internal field.
template<class Type >
tmp< DimensionedField< Type, volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject) const
Read and reconstruct volume internal field.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh >> &) const
Reconstruct volume field.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject) const
Read and reconstruct volume field.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &) const
Reconstruct surface field.
template<class Type >
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject) const
Read and reconstruct surface field.
template<class Type >
void reconstructFvVolumeInternalFields (const IOobjectList &objects, const HashSet< word > &selectedFields)
Read, reconstruct and write all/selected volume internal fields.
template<class Type >
void reconstructFvVolumeFields (const IOobjectList &objects, const HashSet< word > &selectedFields)
Read, reconstruct and write all/selected volume fields.
template<class Type >
void reconstructFvSurfaceFields (const IOobjectList &objects, const HashSet< word > &selectedFields)
Read, reconstruct and write all/selected surface fields.
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject, const PtrList< DimensionedField< Type, volMesh >> &procFields) const
template<class Type >
Foam::tmp< Foam::DimensionedField< Type, Foam::volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh >> &procFields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &procFields) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject) const
Detailed Description
Finite volume reconstructor for volume and surface fields.
Source files
fvFieldReconstructor.H
fvFieldReconstructor.C
fvFieldReconstructorReconstructFields.C
Definition at line 54 of file fvFieldReconstructor.H.
Constructor & Destructor Documentation
fvFieldReconstructor()
fvFieldReconstructor (fvMesh & mesh, const PtrList< fvMesh > & procMeshes, const PtrList< labelIOList > & faceProcAddressing, const PtrList< labelIOList > & cellProcAddressing, const PtrList< labelIOList > & boundaryProcAddressing)
Construct from components.
Definition at line 31 of file fvFieldReconstructor.C.
References fvMesh::boundary(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, primitiveMesh::nCells(), primitiveMesh::nFaces(), and UPtrList< T >::size().
Member Function Documentation
nReconstructed()
label nReconstructed () const inline
Return number of fields reconstructed.
Definition at line 146 of file fvFieldReconstructor.H.
References fvFieldReconstructor::reconstructFvSurfaceField(), fvFieldReconstructor::reconstructFvSurfaceFields(), fvFieldReconstructor::reconstructFvVolumeField(), fvFieldReconstructor::reconstructFvVolumeFields(), fvFieldReconstructor::reconstructFvVolumeInternalField(), and fvFieldReconstructor::reconstructFvVolumeInternalFields().
reconstructFvVolumeInternalField() [1/4]
tmp<DimensionedField<Type, volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject, const PtrList< DimensionedField< Type, volMesh >> & procFields) const
Reconstruct volume internal field.
Referenced by fvFieldReconstructor::nReconstructed(), and fvFieldReconstructor::reconstructFvVolumeInternalField().
reconstructFvVolumeInternalField() [2/4]
tmp<DimensionedField<Type, volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject) const
Read and reconstruct volume internal field.
reconstructFvVolumeField() [1/4]
tmp<GeometricField<Type, fvPatchField, volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh >> &) const
Reconstruct volume field.
Referenced by fvFieldReconstructor::nReconstructed(), fvFieldReconstructor::reconstructFvVolumeField(), and fvFieldReconstructor::reconstructFvVolumeInternalField().
reconstructFvVolumeField() [2/4]
tmp<GeometricField<Type, fvPatchField, volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject) const
Read and reconstruct volume field.
reconstructFvSurfaceField() [1/4]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &) const
Reconstruct surface field.
Referenced by fvFieldReconstructor::nReconstructed(), fvFieldReconstructor::reconstructFvSurfaceField(), and fvFieldReconstructor::reconstructFvVolumeField().
reconstructFvSurfaceField() [2/4]
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject) const
Read and reconstruct surface field.
reconstructFvVolumeInternalFields()
void reconstructFvVolumeInternalFields (const IOobjectList & objects, const HashSet< word > & selectedFields)
Read, reconstruct and write all/selected volume internal fields.
Definition at line 590 of file fvFieldReconstructorReconstructFields.C.
References HashTable< nil, Key, Hash >::empty(), Foam::endl(), fields, forAllConstIter(), HashTable< nil, Key, Hash >::found(), Foam::Info, IOobjectList::lookupClass(), Foam::name(), fvFieldReconstructor::reconstructFvVolumeFields(), HashTable< T, Key, Hash >::size(), and Ostream::write().
Referenced by fvFieldReconstructor::nReconstructed(), and fvFieldReconstructor::reconstructFvSurfaceField().
reconstructFvVolumeFields()
void reconstructFvVolumeFields (const IOobjectList & objects, const HashSet< word > & selectedFields)
Read, reconstruct and write all/selected volume fields.
Definition at line 625 of file fvFieldReconstructorReconstructFields.C.
References HashTable< nil, Key, Hash >::empty(), Foam::endl(), fields, forAllConstIter(), HashTable< nil, Key, Hash >::found(), Foam::Info, IOobjectList::lookupClass(), Foam::name(), fvFieldReconstructor::reconstructFvSurfaceFields(), HashTable< T, Key, Hash >::size(), and Ostream::write().
Referenced by fvFieldReconstructor::nReconstructed(), and fvFieldReconstructor::reconstructFvVolumeInternalFields().
reconstructFvSurfaceFields()
void reconstructFvSurfaceFields (const IOobjectList & objects, const HashSet< word > & selectedFields)
Read, reconstruct and write all/selected surface fields.
Definition at line 661 of file fvFieldReconstructorReconstructFields.C.
References HashTable< nil, Key, Hash >::empty(), Foam::endl(), fields, forAllConstIter(), HashTable< nil, Key, Hash >::found(), Foam::Info, IOobjectList::lookupClass(), Foam::name(), HashTable< T, Key, Hash >::size(), and Ostream::write().
Referenced by fvFieldReconstructor::nReconstructed(), and fvFieldReconstructor::reconstructFvVolumeFields().
reconstructFvVolumeInternalField() [3/4]
Foam::tmp<Foam::DimensionedField<Type, Foam::volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject, const PtrList< DimensionedField< Type, volMesh >> & procFields) const
Definition at line 39 of file fvFieldReconstructorReconstructFields.C.
References DimensionedField< Type, GeoMesh >::field(), forAll, fvFieldReconstructor::reconstructFvVolumeInternalField(), and Field< Type >::rmap().
reconstructFvVolumeInternalField() [4/4]
Foam::tmp<Foam::DimensionedField<Type, Foam::volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject) const
Definition at line 75 of file fvFieldReconstructorReconstructFields.C.
References forAll, IOobject::name(), and fvFieldReconstructor::reconstructFvVolumeField().
reconstructFvVolumeField() [3/4]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh >> & procFields) const
Definition at line 124 of file fvFieldReconstructorReconstructFields.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cp, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, DimensionedField< Type, GeoMesh >::mesh(), patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), fvFieldReconstructor::reconstructFvVolumeField(), Field< Type >::rmap(), and UList< T >::size().
reconstructFvVolumeField() [4/4]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject) const
Definition at line 302 of file fvFieldReconstructorReconstructFields.C.
References forAll, IOobject::name(), and fvFieldReconstructor::reconstructFvSurfaceField().
reconstructFvSurfaceField() [3/4]
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> & procFields) const
Definition at line 350 of file fvFieldReconstructorReconstructFields.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cp, Foam::faceMap(), forAll, Foam::mag(), patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), fvFieldReconstructor::reconstructFvSurfaceField(), and UList< T >::size().
reconstructFvSurfaceField() [4/4]
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject) const
Definition at line 543 of file fvFieldReconstructorReconstructFields.C.
References forAll, IOobject::name(), and fvFieldReconstructor::reconstructFvVolumeInternalFields().
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/fvFieldReconstructor.H
src/parallel/reconstruct/reconstruct/fvFieldReconstructor.C
src/parallel/reconstruct/reconstruct/fvFieldReconstructorReconstructFields.C