OpenFOAM: fft Class Reference
fft Class Reference
Fast fourier transform derived from the Numerical Recipes in C routine.
Public Types
enum transformDirection { FORWARD_TRANSFORM = 1, REVERSE_TRANSFORM = -1 }
Static Public Member Functions
static void transform (complexField &field, const labelList &nn, transformDirection fftDirection)
static tmp< complexField > forwardTransform (const tmp< complexField > &field, const labelList &nn)
static tmp< complexField > reverseTransform (const tmp< complexField > &field, const labelList &nn)
static tmp< complexVectorField > forwardTransform (const tmp< complexVectorField > &field, const labelList &nn)
static tmp< complexVectorField > reverseTransform (const tmp< complexVectorField > &field, const labelList &nn)
Detailed Description
Fast fourier transform derived from the Numerical Recipes in C routine.
The complex transform field is returned in the field supplied. The direction of transform is supplied as an argument (1 = forward, -1 = reverse). The dimensionality and organisation of the array of values in space is supplied in the nn indexing array.
Source files
fft.H
fft.C
Definition at line 51 of file fft.H.
Member Enumeration Documentation
transformDirection
enum transformDirection
Enumerator
FORWARD_TRANSFORM
REVERSE_TRANSFORM
Definition at line 56 of file fft.H.
Member Function Documentation
transform()
void transform (complexField & field, const labelList & nn, transformDirection fftDirection) static
Definition at line 42 of file fft.C.
References Foam::abort(), UList< T >::begin(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::fftRenumber(), forAll, fft::forwardTransform(), n, Foam::sin(), List< T >::size(), Foam::sqrt(), SWAP, and TWOPI.
forwardTransform() [1/2]
tmp< complexField > forwardTransform (const tmp< complexField > & field, const labelList & nn) static
Definition at line 187 of file fft.C.
References tmp< T >::clear(), tmp< T >::ref(), fft::reverseTransform(), and Foam::transform().
Referenced by Foam::calcEk(), fft::reverseTransform(), and fft::transform().
reverseTransform() [1/2]
tmp< complexField > reverseTransform (const tmp< complexField > & field, const labelList & nn) static
Definition at line 203 of file fft.C.
References tmp< T >::clear(), fft::forwardTransform(), tmp< T >::ref(), and Foam::transform().
Referenced by fft::forwardTransform(), noiseFFT::Pf(), and turbGen::U().
forwardTransform() [2/2]
tmp< complexVectorField > forwardTransform (const tmp< complexVectorField > & field, const labelList & nn) static
Definition at line 219 of file fft.C.
References tmp< T >::clear(), Foam::component(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, tmp< T >::ref(), Field< Type >::replace(), and fft::reverseTransform().
reverseTransform() [2/2]
tmp< complexVectorField > reverseTransform (const tmp< complexVectorField > & field, const labelList & nn) static
Definition at line 248 of file fft.C.
References tmp< T >::clear(), Foam::component(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, tmp< T >::ref(), and Field< Type >::replace().
The documentation for this class was generated from the following files:
src/randomProcesses/fft/fft.H
src/randomProcesses/fft/fft.C