OpenFOAM: noiseFFT Class Reference
noiseFFT Class Reference
FFT of the pressure field.
Public Member Functions
noiseFFT (const scalar deltat, const scalarField &pressure)
Construct from pressure field.
noiseFFT (Istream &)
Construct from Istream.
noiseFFT (const fileName &pFileName, const label skip=0)
Construct from pressure field file name.
graph pt () const
Return the graph of p(t)
tmp< scalarField > window (const label N, const label n) const
Return the nth window.
tmp< scalarField > Hanning (const label N) const
Return the Hanning window function.
tmp< scalarField > Pf (const tmp< scalarField > &pn) const
Return the fft of the given pressure data.
graph meanPf (const label N, const label nw) const
Return the multi-window mean fft of the complete pressure data.
graph RMSmeanPf (const label N, const label nw) const
Return the multi-window RMS mean fft of the complete pressure data.
graph Lf (const graph &gPf) const
Return the narrow-band PFL (pressure-fluctuation level) spectrum.
graph Ldelta (const graph &gLf, const scalar f1, const scalar fU) const
Return the one-third-octave-band PFL spectrum.
graph Pdelta (const graph &gLf, const scalar f1, const scalar fU) const
Return the one-third-octave-band pressure spectrum.
scalar Lsum (const graph &gLf) const
Return the total PFL as the sum of Lf over all frequencies.
scalar dbToPa (const scalar db) const
Convert the db into Pa.
tmp< scalarField > dbToPa (const tmp< scalarField > &db) const
Convert the db-field into Pa.
Public Member Functions inherited from Field< scalar >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const scalar &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< scalar > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< scalar >> &)
Construct by transferring the List contents.
Field (const UList< scalar > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< scalar >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< scalar > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< scalar >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< scalar > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< scalar > &mapF, const FieldMapper &map, const scalar &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< scalar > &mapF, const FieldMapper &map, const UList< scalar > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< scalar >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< scalar >> &tmapF, const FieldMapper &map, const scalar &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< scalar >> &tmapF, const FieldMapper &map, const UList< scalar > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< scalar > &)
Construct as copy.
Field (Field< scalar > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< scalar >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< scalar >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< scalar > > clone () const
Clone.
void map (const UList< scalar > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< scalar >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< scalar > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< scalar >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< scalar > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< scalar >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< scalar > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< scalar >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< scalar > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< scalar >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
VSForm block (const label start) const
tmp< Field< scalar > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< scalar > &)
void operator= (const UList< scalar > &)
void operator= (const SubField< scalar > &)
void operator= (const tmp< Field< scalar >> &)
void operator= (const scalar &)
void operator= (const zero)
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator= (const tmp< Field > &rhs)
void operator+= (const UList< scalar > &)
void operator+= (const tmp< Field< scalar >> &)
void operator+= (const scalar &)
void operator-= (const UList< scalar > &)
void operator-= (const tmp< Field< scalar >> &)
void operator-= (const scalar &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator*= (const scalar &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< scalar >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const scalar &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< scalar > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< scalar >> &)
Construct by transferring the parameter contents.
List (List< scalar > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< scalar > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< scalar, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< scalar > &)
Construct as copy of PtrList<T>
List (const SLList< scalar > &)
Construct as copy of SLList<T>
List (const UIndirectList< scalar > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< scalar > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< scalar >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< scalar > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const scalar &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const scalar &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const scalar &)
Append an element at the end of the list.
void append (const UList< scalar > &)
Append a List at the end of this list.
void append (const UIndirectList< scalar > &)
Append a UIndirectList at the end of this list.
void transfer (List< scalar > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< scalar, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< scalar > &)
Transfer the contents of the argument List into this list.
Xfer< List< scalar > > xfer ()
Transfer contents to the Xfer container.
scalar & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< scalar > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< scalar > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< scalar > &)
Assignment operator. Takes linear time.
void operator= (const SLList< scalar > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< scalar > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< scalar > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< scalar >)
Assignment to an initializer list.
void operator= (const scalar &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< T >
UList ()
Null constructor.
UList (T *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const T * cdata () const
Return a const pointer to the first data element,.
T * data ()
Return a pointer to the first data element,.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< T > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
T & operator[] (const label)
Return element of UList.
const T & operator[] (const label) const
Return element of constant UList.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< T > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &) const
Return true if !(a < b). Takes linear time.
template<>
const bool & operator[] (const label i) const
Static Public Attributes
static scalar p0 = 2e-5
Reference pressure.
Static Public Attributes inherited from Field< scalar >
static const char *const typeName
Additional Inherited Members
Public Types inherited from Field< scalar >
typedef pTraits< scalar >::cmptType cmptType
Component type.
typedef SubField< scalar > subField
Declare type of subField.
Public Types inherited from List< scalar >
typedef SubList< scalar > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
Type of values the UList contains.
typedef T & reference
Type that can be used for storing into.
typedef const T & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef T * iterator
Random access iterator for traversing UList.
typedef const T * const_iterator
Random access iterator for traversing UList.
typedef T * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const T * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from Field< scalar >
static const Field< scalar > & null ()
Return a null field.
static tmp< Field< scalar > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< scalar >
static const List< scalar > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a null UList.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< scalar >
void size (const label)
Override size to be inconsistent with allocated storage.
Detailed Description
FFT of the pressure field.
Source files
noiseFFT.H
noiseFFT.C
Definition at line 49 of file noiseFFT.H.
Constructor & Destructor Documentation
noiseFFT() [1/3]
noiseFFT (const scalar deltat, const scalarField & pressure)
Construct from pressure field.
Definition at line 41 of file noiseFFT.C.
noiseFFT() [2/3]
noiseFFT (Istream &)
Construct from Istream.
noiseFFT() [3/3]
noiseFFT (const fileName & pFileName, const label skip = 0)
Construct from pressure field file name.
Definition at line 51 of file noiseFFT.C.
References IOstream::eof(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), List< T >::size(), Field< scalar >::T(), and List< scalar >::transfer().
Member Function Documentation
pt()
Foam::graph pt () const
Return the graph of p(t)
Definition at line 105 of file noiseFFT.C.
References forAll, List< scalar >::size(), and noiseFFT::window().
window()
Foam::tmp< Foam::scalarField > window (const label N, const label n) const
Return the nth window.
Definition at line 125 of file noiseFFT.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, N, UList< T >::operator[](), tmp< T >::ref(), and List< scalar >::size().
Referenced by noiseFFT::meanPf(), noiseFFT::pt(), and noiseFFT::RMSmeanPf().
Hanning()
Foam::tmp< Foam::scalarField > Hanning (const label N) const
Return the Hanning window function.
Definition at line 156 of file noiseFFT.C.
References Foam::cos(), forAll, noiseFFT::Pf(), Field< scalar >::T(), and Foam::constant::mathematical::twoPi().
Referenced by noiseFFT::meanPf(), and noiseFFT::RMSmeanPf().
Pf()
Foam::tmp< Foam::scalarField > Pf (const tmp< scalarField > & pn) const
Return the fft of the given pressure data.
Definition at line 171 of file noiseFFT.C.
References tmp< T >::clear(), Foam::mag(), noiseFFT::meanPf(), Foam::ReComplexField(), tmp< T >::ref(), fft::reverseTransform(), List< scalar >::size(), and Foam::sqrt().
Referenced by noiseFFT::Hanning(), noiseFFT::meanPf(), noiseFFT::Pdelta(), and noiseFFT::RMSmeanPf().
meanPf()
Foam::graph meanPf (const label N, const label nw) const
Return the multi-window mean fft of the complete pressure data.
Definition at line 206 of file noiseFFT.C.
References Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, forAll, noiseFFT::Hanning(), Foam::nl, nw, noiseFFT::Pf(), noiseFFT::RMSmeanPf(), List< T >::size(), List< scalar >::size(), and noiseFFT::window().
Referenced by noiseFFT::Pf().
RMSmeanPf()
Foam::graph RMSmeanPf (const label N, const label nw) const
Return the multi-window RMS mean fft of the complete pressure data.
Definition at line 252 of file noiseFFT.C.
References Foam::endl(), Foam::exit(), f(), Foam::FatalError, FatalErrorInFunction, forAll, noiseFFT::Hanning(), nw, noiseFFT::Pf(), List< T >::size(), List< scalar >::size(), Foam::sqr(), Foam::sqrt(), and noiseFFT::window().
Referenced by noiseFFT::meanPf().
Lf()
Foam::graph Lf (const graph & gPf) const
Return the narrow-band PFL (pressure-fluctuation level) spectrum.
Definition at line 297 of file noiseFFT.C.
References noiseFFT::Ldelta(), Foam::log10(), noiseFFT::p0, graph::x(), and graph::y().
Referenced by noiseFFT::Ldelta(), and noiseFFT::Lsum().
Ldelta()
Foam::graph Ldelta (const graph & gLf, const scalar f1, const scalar fU) const
Return the one-third-octave-band PFL spectrum.
starting at octave with mean frequency f1
Definition at line 311 of file noiseFFT.C.
References Foam::cbrt(), f(), noiseFFT::Lf(), Foam::log10(), noiseFFT::Pdelta(), Foam::pow(), List< T >::setSize(), List< T >::size(), Foam::sqrt(), graph::x(), and graph::y().
Referenced by noiseFFT::Lf().
Pdelta()
Foam::graph Pdelta (const graph & gLf, const scalar f1, const scalar fU) const
Return the one-third-octave-band pressure spectrum.
starting at octave with mean frequency f1
Definition at line 367 of file noiseFFT.C.
References Foam::cbrt(), f(), noiseFFT::Pf(), List< T >::setSize(), List< T >::size(), Foam::sqr(), Foam::sqrt(), graph::x(), and graph::y().
Referenced by noiseFFT::Ldelta().
Lsum()
Foam::scalar Lsum (const graph & gLf) const
Return the total PFL as the sum of Lf over all frequencies.
Definition at line 422 of file noiseFFT.C.
References forAll, noiseFFT::Lf(), Foam::log10(), Foam::pow(), and graph::y().
dbToPa() [1/2]
Foam::scalar dbToPa (const scalar db) const
Convert the db into Pa.
Definition at line 439 of file noiseFFT.C.
References noiseFFT::p0, and Foam::pow().
dbToPa() [2/2]
Foam::tmp< Foam::scalarField > dbToPa (const tmp< scalarField > & db) const
Convert the db-field into Pa.
Definition at line 446 of file noiseFFT.C.
References noiseFFT::p0, and Foam::pow().
Member Data Documentation
p0
Foam::scalar p0 = 2e-5 static
Reference pressure.
Definition at line 62 of file noiseFFT.H.
Referenced by noiseFFT::dbToPa(), and noiseFFT::Lf().
The documentation for this class was generated from the following files:
src/randomProcesses/noise/noiseFFT.H
src/randomProcesses/noise/noiseFFT.C