OpenFOAM: filmPyrolysisRadiativeCoupledMixedFvPatchScalarField Class Reference
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField Class Reference
Mixed boundary condition for temperature, to be used in the flow and pyrolysis regions when a film region model is used.
Public Types
typedef Foam::regionModels::surfaceFilmModels::thermoSingleLayer filmModelType
typedef Foam::regionModels::pyrolysisModels::pyrolysisModel pyrolysisModelType
Public Types inherited from temperatureCoupledBase
enum KMethodType { mtFluidThermo, mtSolidThermo, mtDirectionalSolidThermo, mtLookup }
Type of supplied Kappa.
Public Member Functions
TypeName ("filmPyrolysisRadiativeCoupledMixed")
Runtime type information.
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const filmPyrolysisRadiativeCoupledMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const filmPyrolysisRadiativeCoupledMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
tmp< scalarField > K () const
Get corresponding K field.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const word &calculationMethod, const word &kappaName, const word &alphaAniName)
Construct from patch and K name.
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
Construct from patch and temperatureCoupledBase.
word KMethod () const
Method to obtain K.
const word & kappaName () const
Name of thermal conductivity field.
tmp< scalarField > kappa (const scalarField &Tp) const
Given patch temperature calculate corresponding K field.
void write (Ostream &) const
Write.
Additional Inherited Members
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
Underlying patch.
const KMethodType method_
How to get K.
const word kappaName_
Name of thermal conductivity field (if looked up from database)
const word alphaAniName_
Name of the non-Isotropic alpha (default: Anialpha)
Static Protected Attributes inherited from temperatureCoupledBase
static const NamedEnum< KMethodType, 4 > KMethodTypeNames_
Detailed Description
Mixed boundary condition for temperature, to be used in the flow and pyrolysis regions when a film region model is used.
Example usage:
myInterfacePatchName
{
    type            filmPyrolysisRadiativeCoupledMixed;
    Tnbr            T;
    kappa           fluidThermo;
    Qr              Qr;
    kappaName       none;
    filmDeltaDry    0.0;
    filmDeltaWet    3e-4;
    value           $internalField;
}
Needs to be on underlying mapped(Wall)FvPatch. It calculates local field as:
    ratio = (filmDelta - filmDeltaDry)/(filmDeltaWet - filmDeltaDry)
when ratio = 1 is considered wet and the film temperature is fixed at the wall. If ratio = 0 (dry) it emulates the normal radiative solid BC.
In between ratio 0 and 1 the gradient and value contributions are weighted using the ratio field in the following way:
    qConv = ratio*htcwfilm*(Tfilm - *this);
    qRad = (1.0 - ratio)*Qr;
Then the solid can gain or loose energy through radiation or conduction towards the film.
Notes:
kappa and kappaName are inherited from temperatureCoupledBase.
Qr is the radiative flux defined in the radiation model.
See also
Foam::temperatureCoupledBase
Source files
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C
Definition at line 98 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
Member Typedef Documentation
filmModelType
typedef Foam::regionModels::surfaceFilmModels::thermoSingleLayer filmModelType
Definition at line 106 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
pyrolysisModelType
typedef Foam::regionModels::pyrolysisModels::pyrolysisModel pyrolysisModelType
Definition at line 109 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField() [1/4]
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 103 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::clone(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField().
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField() [2/4]
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 147 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), dictionary::found(), fvPatch::name(), fvPatchField< Type >::operator=(), and fvPatch::size().
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField() [3/4]
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const filmPyrolysisRadiativeCoupledMixedFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
turbulentTemperatureCoupledBaffleMixedFvPatchScalarField onto a new patch
Definition at line 126 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
References filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField().
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField() [4/4]
filmPyrolysisRadiativeCoupledMixedFvPatchScalarField (const filmPyrolysisRadiativeCoupledMixedFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 200 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("filmPyrolysisRadiativeCoupledMixed")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 180 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
References filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 200 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H.
References filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::filmPyrolysisRadiativeCoupledMixedFvPatchScalarField(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::K(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::write().
K()
tmp<scalarField> K () const
Get corresponding K field.
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::clone(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 219 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
References Foam::constant::atomic::alpha, boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvPatch::deltaCoeffs(), mappedPatchBase::distribute(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::gSum(), heatTransferModel::h(), thermoSingleLayer::htcw(), patchIdentifier::index(), fvPatch::index(), Foam::Info, filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::K(), temperatureCoupledBase::kappa(), fvPatch::lookupPatchField(), regionModel::mapRegionPatchField(), Foam::max(), mesh, Foam::min(), fvPatch::name(), fvMesh::name(), IOobject::name(), regionModel::nbrCoupledPatchID(), Foam::nl, patchi, regionModel::primaryMesh(), Foam::refCast(), mappedPatchBase::sampleMesh(), mappedPatchBase::samplePolyPatch(), regionModel::toPrimary(), thermoSingleLayer::Ts(), Foam::type(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::write().
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 382 of file filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C.
References token::END_STATEMENT, Foam::endl(), Foam::makePatchTypeField(), Foam::nl, write(), and temperatureCoupledBase::write().
Referenced by filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::clone(), and filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisRadiativeCoupledMixed/filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.H
src/regionModels/regionCoupling/derivedFvPatchFields/filmPyrolysisRadiativeCoupledMixed/filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.C