OpenFOAM: pyrolysisModelCollection Class Reference
pyrolysisModelCollection Class Reference
Public Member Functions
TypeName ("pyrolysisModelCollection")
pyrolysisModelCollection (const fvMesh &)
Construct from mesh.
virtual ~pyrolysisModelCollection ()
Destructor.
virtual void preEvolveRegion ()
Pre-evolve regions.
virtual void evolveRegion ()
Evolve the pyrolysis equation regions.
virtual void evolve ()
Evolve regions.
virtual void info ()
Provide some feedback from pyrolysis regions.
virtual scalar maxDiff () const
Return max diffusivity allowed in the solid.
virtual scalar solidRegionDiffNo () const
Mean diffusion number of the solid regions.
Public Member Functions inherited from PtrList< pyrolysisModel >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< pyrolysisModel > &)
Copy constructor.
PtrList (const PtrList< pyrolysisModel > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< pyrolysisModel >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< pyrolysisModel > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< pyrolysisModel > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (pyrolysisModel *)
Append an element at the end of the list.
void append (const autoPtr< pyrolysisModel > &)
void append (const tmp< pyrolysisModel > &)
void transfer (PtrList< pyrolysisModel > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< pyrolysisModel > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< pyrolysisModel > set (const label, pyrolysisModel *)
Set element to given T* and return old element (can be nullptr)
autoPtr< pyrolysisModel > set (const label, const autoPtr< pyrolysisModel > &)
Set element to given autoPtr<T> and return old element.
autoPtr< pyrolysisModel > set (const label, const tmp< pyrolysisModel > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< pyrolysisModel > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Protected Member Functions inherited from PtrList< pyrolysisModel >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Definition at line 60 of file pyrolysisModelCollection.H.
Constructor & Destructor Documentation
pyrolysisModelCollection()
pyrolysisModelCollection (const fvMesh & mesh)
Construct from mesh.
Definition at line 53 of file pyrolysisModelCollection.C.
References TimePaths::constant(), mesh, IOobject::MUST_READ, pyrolysisModel::New(), IOobject::NO_WRITE, PtrList< pyrolysisModel >::setSize(), dictionary::subDict(), fvMesh::time(), and dictionary::toc().
~pyrolysisModelCollection()
~pyrolysisModelCollection () virtual
Destructor.
Definition at line 92 of file pyrolysisModelCollection.C.
Member Function Documentation
TypeName()
TypeName ("pyrolysisModelCollection")
preEvolveRegion()
void preEvolveRegion () virtual
Pre-evolve regions.
Definition at line 99 of file pyrolysisModelCollection.C.
References forAll, and UPtrList< T >::operator[]().
evolveRegion()
void evolveRegion () virtual
Evolve the pyrolysis equation regions.
Definition at line 108 of file pyrolysisModelCollection.C.
References forAll, and UPtrList< T >::operator[]().
evolve()
void evolve () virtual
Evolve regions.
Definition at line 117 of file pyrolysisModelCollection.C.
References Foam::abort(), regionModel::active(), polyMesh::changing(), Foam::decrIndent(), Foam::endl(), regionModel::evolveRegion(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::incrIndent(), Foam::Info, regionModel::info(), regionModel::infoOutput(), regionModel::modelName(), Foam::nl, UPtrList< T >::operator[](), regionModel::preEvolveRegion(), and regionModel::primaryMesh().
info()
void info () virtual
Provide some feedback from pyrolysis regions.
Definition at line 151 of file pyrolysisModelCollection.C.
References forAll, and UPtrList< T >::operator[]().
maxDiff()
scalar maxDiff () const virtual
Return max diffusivity allowed in the solid.
Definition at line 160 of file pyrolysisModelCollection.C.
References forAll, and UPtrList< T >::operator[]().
solidRegionDiffNo()
scalar solidRegionDiffNo () const virtual
Mean diffusion number of the solid regions.
Definition at line 175 of file pyrolysisModelCollection.C.
References forAll, and UPtrList< T >::operator[]().
The documentation for this class was generated from the following files:
src/regionModels/pyrolysisModels/pyrolysisModel/pyrolysisModelCollection.H
src/regionModels/pyrolysisModels/pyrolysisModel/pyrolysisModelCollection.C