OpenFOAM: processorMeshes Class Reference
processorMeshes Class Reference
Container for processor mesh addressing.
Public Member Functions
processorMeshes (PtrList< Time > &databases, const word &meshName)
Construct from components.
fvMesh::readUpdateState readUpdate ()
Update the meshes based on the mesh files saved in time directories.
void reconstructPoints (fvMesh &)
Reconstruct point position after motion in parallel.
PtrList< fvMesh > & meshes ()
const PtrList< labelIOList > & pointProcAddressing () const
PtrList< labelIOList > & faceProcAddressing ()
const PtrList< labelIOList > & cellProcAddressing () const
const PtrList< labelIOList > & boundaryProcAddressing () const
Detailed Description
Container for processor mesh addressing.
Source files
processorMeshes.H
processorMeshes.C
Definition at line 52 of file processorMeshes.H.
Constructor & Destructor Documentation
processorMeshes()
processorMeshes (PtrList< Time > & databases, const word & meshName)
Construct from components.
Definition at line 135 of file processorMeshes.C.
Member Function Documentation
readUpdate()
Foam::fvMesh::readUpdateState readUpdate ()
Update the meshes based on the mesh files saved in time directories.
Definition at line 154 of file processorMeshes.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, polyMesh::TOPO_CHANGE, polyMesh::TOPO_PATCH_CHANGE, and polyMesh::UNCHANGED.
reconstructPoints()
void reconstructPoints (fvMesh & mesh)
Reconstruct point position after motion in parallel.
Definition at line 205 of file processorMeshes.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::meshSubDir, fvMesh::movePoints(), IOobject::MUST_READ, IOobject::NO_WRITE, primitiveMesh::nPoints(), List< T >::size(), timeName, and fvMesh::write().
meshes()
PtrList<fvMesh>& meshes () inline
Definition at line 105 of file processorMeshes.H.
pointProcAddressing()
const PtrList<labelIOList>& pointProcAddressing () const inline
Definition at line 110 of file processorMeshes.H.
faceProcAddressing()
PtrList<labelIOList>& faceProcAddressing () inline
Definition at line 115 of file processorMeshes.H.
cellProcAddressing()
const PtrList<labelIOList>& cellProcAddressing () const inline
Definition at line 120 of file processorMeshes.H.
boundaryProcAddressing()
const PtrList<labelIOList>& boundaryProcAddressing () const inline
Definition at line 125 of file processorMeshes.H.
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/processorMeshes.H
src/parallel/reconstruct/reconstruct/processorMeshes.C