OpenFOAM: filmHeightInletVelocityFvPatchVectorField Class Reference
filmHeightInletVelocityFvPatchVectorField Class Reference
Region boundary conditions » Surface film boundary conditions
This boundary condition is designed to be used in conjunction with surface film modelling. It provides a velocity inlet boundary condition for patches where the film height is specified. The inflow velocity is obtained from the flux with a direction normal to the patch faces using:
Public Member Functions
TypeName ("filmHeightInletVelocity")
Runtime type information.
filmHeightInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
filmHeightInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given filmHeightInletVelocityFvPatchVectorField.
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: this patch field is altered by assignment.
const word & phiName () const
Return the name of phi.
word & phiName ()
Return reference to the name of phi to allow adjustment.
const word & rhoName () const
Return the name of rho.
word & rhoName ()
Return reference to the name of rho to allow adjustment.
const word & deltafName () const
Return the name of deltaf.
word & deltafName ()
Return reference to the name of df to allow adjustment.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchField< vector > &pvf)
Detailed Description
This boundary condition is designed to be used in conjunction with surface film modelling. It provides a velocity inlet boundary condition for patches where the film height is specified. The inflow velocity is obtained from the flux with a direction normal to the patch faces using:
where
= patch velocity [m/s]
= patch normal vector
= mass flux [kg/s]
= density [kg/m3]
= patch face area vectors [m2]
= film height [m]
Usage
Property Description Required Default value
phi Flux field name no phi
rho density field name no rho
deltaf height field name no deltaf
Example of the boundary condition specification:
    <patchName>
    {
        type            filmHeightInletVelocity;
        phi             phi;
        rho             rho;
        deltaf          deltaf;
        value           uniform (0 0 0); // initial velocity / [m/s]
    }
See also
Foam::fixedValueFvPatchField
Source files
filmHeightInletVelocityFvPatchVectorField.H
filmHeightInletVelocityFvPatchVectorField.C
Definition at line 136 of file filmHeightInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
filmHeightInletVelocityFvPatchVectorField() [1/5]
filmHeightInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file filmHeightInletVelocityFvPatchVectorField.C.
Referenced by filmHeightInletVelocityFvPatchVectorField::clone(), and filmHeightInletVelocityFvPatchVectorField::filmHeightInletVelocityFvPatchVectorField().
filmHeightInletVelocityFvPatchVectorField() [2/5]
filmHeightInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 65 of file filmHeightInletVelocityFvPatchVectorField.C.
References filmHeightInletVelocityFvPatchVectorField::filmHeightInletVelocityFvPatchVectorField().
filmHeightInletVelocityFvPatchVectorField() [3/5]
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given filmHeightInletVelocityFvPatchVectorField.
onto a new patch
Definition at line 49 of file filmHeightInletVelocityFvPatchVectorField.C.
References filmHeightInletVelocityFvPatchVectorField::filmHeightInletVelocityFvPatchVectorField().
filmHeightInletVelocityFvPatchVectorField() [4/5]
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField & fhivpvf)
Construct as copy.
Definition at line 80 of file filmHeightInletVelocityFvPatchVectorField.C.
References filmHeightInletVelocityFvPatchVectorField::filmHeightInletVelocityFvPatchVectorField().
filmHeightInletVelocityFvPatchVectorField() [5/5]
filmHeightInletVelocityFvPatchVectorField (const filmHeightInletVelocityFvPatchVectorField & fhivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 93 of file filmHeightInletVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("filmHeightInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 192 of file filmHeightInletVelocityFvPatchVectorField.H.
References filmHeightInletVelocityFvPatchVectorField::filmHeightInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 209 of file filmHeightInletVelocityFvPatchVectorField.H.
References filmHeightInletVelocityFvPatchVectorField::filmHeightInletVelocityFvPatchVectorField().
assignable()
virtual bool assignable () const inline virtual
Return true: this patch field is altered by assignment.
Definition at line 225 of file filmHeightInletVelocityFvPatchVectorField.H.
phiName() [1/2]
const word& phiName () const inline
Return the name of phi.
Definition at line 234 of file filmHeightInletVelocityFvPatchVectorField.H.
phiName() [2/2]
word& phiName () inline
Return reference to the name of phi to allow adjustment.
Definition at line 240 of file filmHeightInletVelocityFvPatchVectorField.H.
rhoName() [1/2]
const word& rhoName () const inline
Return the name of rho.
Definition at line 246 of file filmHeightInletVelocityFvPatchVectorField.H.
rhoName() [2/2]
word& rhoName () inline
Return reference to the name of rho to allow adjustment.
Definition at line 252 of file filmHeightInletVelocityFvPatchVectorField.H.
deltafName() [1/2]
const word& deltafName () const inline
Return the name of deltaf.
Definition at line 258 of file filmHeightInletVelocityFvPatchVectorField.H.
deltafName() [2/2]
word& deltafName () inline
Return reference to the name of df to allow adjustment.
Definition at line 264 of file filmHeightInletVelocityFvPatchVectorField.H.
References filmHeightInletVelocityFvPatchVectorField::operator=(), filmHeightInletVelocityFvPatchVectorField::updateCoeffs(), and filmHeightInletVelocityFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 107 of file filmHeightInletVelocityFvPatchVectorField.C.
References n, and Foam::operator==().
Referenced by filmHeightInletVelocityFvPatchVectorField::deltafName().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 132 of file filmHeightInletVelocityFvPatchVectorField.C.
References fvPatchField< Type >::write().
Referenced by filmHeightInletVelocityFvPatchVectorField::deltafName().
operator=()
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 145 of file filmHeightInletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), and fvPatchField< Type >::operator=().
Referenced by filmHeightInletVelocityFvPatchVectorField::deltafName().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/derivedFvPatchFields/filmHeightInletVelocity/filmHeightInletVelocityFvPatchVectorField.H
src/regionModels/surfaceFilmModels/derivedFvPatchFields/filmHeightInletVelocity/filmHeightInletVelocityFvPatchVectorField.C