OpenFOAM: curvatureSeparation Class Reference
curvatureSeparation Class Reference
Public Member Functions
TypeName ("curvatureSeparation")
Runtime type information.
curvatureSeparation (surfaceFilmModel &owner, const dictionary &dict)
Construct from surface film model.
virtual ~curvatureSeparation ()
Destructor.
virtual void correct (scalarField &availableMass, scalarField &massToInject, scalarField &diameterToInject)
Correct.
Public Member Functions inherited from injectionModel
TypeName ("injectionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, injectionModel, dictionary,(surfaceFilmModel &owner, const dictionary &dict),(owner, dict))
injectionModel (surfaceFilmModel &owner)
Construct null.
injectionModel (const word &modelType, surfaceFilmModel &owner, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~injectionModel ()
Destructor.
virtual scalar injectedMassTotal () const
Return the total mass injected.
virtual void patchInjectedMassTotals (scalarField &patchMasses) const
Accumulate the total mass injected for the patches into the.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool writeTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Member Functions
tmp< volScalarField > calcInvR1 (const volVectorField &U) const
Calculate local (inverse) radius of curvature.
tmp< scalarField > calcCosAngle (const surfaceScalarField &phi) const
Calculate the cosine of the angle between gravity vector and.
Protected Member Functions inherited from injectionModel
void addToInjectedMass (const scalar dMass)
Add to injected mass.
void correct ()
Correct.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
volTensorField gradNHat_
Gradient of surface normals.
scalar deltaByR1Min_
Minimum gravity driven film thickness (non-dimensionalised delta/R1)
List< Tuple2< label, scalar > > definedPatchRadii_
List of radii for patches - if patch not defined, radius.
scalar magG_
Magnitude of gravity vector.
vector gHat_
Direction of gravity vector.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from injectionModel
static autoPtr< injectionModel > New (surfaceFilmModel &owner, const dictionary &dict, const word &mdoelType)
Return a reference to the selected injection model.
Detailed Description
Definition at line 66 of file curvatureSeparation.H.
Constructor & Destructor Documentation
curvatureSeparation()
curvatureSeparation (surfaceFilmModel & owner, const dictionary & dict)
Construct from surface film model.
Definition at line 222 of file curvatureSeparation.C.
References List< T >::append(), polyMesh::boundaryMesh(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::findStrings(), forAll, forAllReverse, surfaceFilmModel::g(), polyBoundaryMesh::names(), patchi, regionModel::regionMesh(), List< T >::size(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::transfer(), and dimensioned< Type >::value().
~curvatureSeparation()
~curvatureSeparation () virtual
Destructor.
Definition at line 273 of file curvatureSeparation.C.
References injectionModel::correct().
Member Function Documentation
calcInvR1()
tmp< volScalarField > calcInvR1 (const volVectorField & U) const protected
Calculate local (inverse) radius of curvature.
Definition at line 60 of file curvatureSeparation.C.
References polyMesh::boundaryMesh(), curvatureSeparation::calcCosAngle(), Foam::dimVelocity, Foam::e, forAll, Foam::mag(), Foam::max(), mesh, patchi, tmp< T >::ref(), fvMesh::time(), and TimeState::writeTime().
Referenced by curvatureSeparation::correct().
calcCosAngle()
tmp< scalarField > calcCosAngle (const surfaceScalarField & phi) const protected
Calculate the cosine of the angle between gravity vector and.
cell out flow direction
Definition at line 114 of file curvatureSeparation.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::dimless, fvPatch::faceCells(), forAll, fvMesh::magSf(), Foam::max(), mesh, Foam::min(), primitiveMesh::nCells(), fvMesh::neighbour(), fvPatch::nf(), IOobject::NO_READ, fvMesh::owner(), fvsPatchField< Type >::patch(), patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), fvMesh::Sf(), fvMesh::time(), Time::timeName(), and TimeState::writeTime().
Referenced by curvatureSeparation::calcInvR1(), and curvatureSeparation::correct().
TypeName()
TypeName ("curvatureSeparation")
Runtime type information.
correct()
void correct (scalarField & availableMass, scalarField & massToInject, scalarField & diameterToInject) virtual
Correct.
Implements injectionModel.
Definition at line 280 of file curvatureSeparation.C.
References injectionModel::addToInjectedMass(), curvatureSeparation::calcCosAngle(), curvatureSeparation::calcInvR1(), injectionModel::correct(), delta, kinematicSingleLayer::delta(), curvatureSeparation::deltaByR1Min_, Foam::dimForce, Foam::e, forAll, curvatureSeparation::magG_, Foam::magSqr(), mesh, IOobject::NO_READ, filmSubModelBase::owner(), kinematicSingleLayer::phi(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), regionModel::regionMesh(), rho, kinematicSingleLayer::rho(), Foam::constant::physicoChemical::sigma, kinematicSingleLayer::sigma(), Foam::sqr(), Foam::sum(), and kinematicSingleLayer::U().
Member Data Documentation
gradNHat_
volTensorField gradNHat_ protected
Gradient of surface normals.
Definition at line 86 of file curvatureSeparation.H.
deltaByR1Min_
scalar deltaByR1Min_ protected
Minimum gravity driven film thickness (non-dimensionalised delta/R1)
Definition at line 89 of file curvatureSeparation.H.
Referenced by curvatureSeparation::correct().
definedPatchRadii_
List<Tuple2<label, scalar> > definedPatchRadii_ protected
List of radii for patches - if patch not defined, radius.
calculated based on mesh geometry
Definition at line 93 of file curvatureSeparation.H.
magG_
scalar magG_ protected
Magnitude of gravity vector.
Definition at line 96 of file curvatureSeparation.H.
Referenced by curvatureSeparation::correct().
gHat_
vector gHat_ protected
Direction of gravity vector.
Definition at line 99 of file curvatureSeparation.H.
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/curvatureSeparation/curvatureSeparation.H
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/curvatureSeparation/curvatureSeparation.C