OpenFOAM: liquidFilmThermo Class Reference
liquidFilmThermo Class Reference
Public Member Functions
TypeName ("liquid")
Runtime type information.
liquidFilmThermo (surfaceFilmModel &owner, const dictionary &dict)
Construct from surface film model and dictionary.
virtual ~liquidFilmThermo ()
Destructor.
virtual const word & name () const
Return the specie name.
virtual scalar rho (const scalar p, const scalar T) const
Return density [kg/m3].
virtual scalar mu (const scalar p, const scalar T) const
Return dynamic viscosity [Pa.s].
virtual scalar sigma (const scalar p, const scalar T) const
Return surface tension [kg/s2].
virtual scalar Cp (const scalar p, const scalar T) const
Return specific heat capacity [J/kg/K].
virtual scalar kappa (const scalar p, const scalar T) const
Return thermal conductivity [W/m/K].
virtual scalar D (const scalar p, const scalar T) const
Return diffusivity [m2/s].
virtual scalar hl (const scalar p, const scalar T) const
Return latent heat [J/kg].
virtual scalar pv (const scalar p, const scalar T) const
Return vapour pressure [Pa].
virtual scalar W () const
Return molecular weight [kg/kmol].
virtual scalar Tb (const scalar p) const
Return boiling temperature [K].
virtual tmp< volScalarField > rho () const
Return density [kg/m3].
virtual tmp< volScalarField > mu () const
Return dynamic viscosity [Pa.s].
virtual tmp< volScalarField > sigma () const
Return surface tension [kg/s2].
virtual tmp< volScalarField > Cp () const
Return specific heat capacity [J/kg/K].
virtual tmp< volScalarField > kappa () const
Return thermal conductivity [W/m/K].
Public Member Functions inherited from filmThermoModel
TypeName ("filmThermoModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, filmThermoModel, dictionary,(surfaceFilmModel &owner, const dictionary &dict),(owner, dict))
filmThermoModel (surfaceFilmModel &owner)
Construct null.
filmThermoModel (const word &modelType, surfaceFilmModel &owner, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~filmThermoModel ()
Destructor.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool writeTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Member Functions
const thermoSingleLayer & thermoFilm () const
Return a reference to a thermo film.
void initLiquid (const dictionary &dict)
Initialise the liquid pointer.
liquidFilmThermo (const liquidFilmThermo &)
Disallow default bitwise copy construct.
void operator= (const liquidFilmThermo &)
Disallow default bitwise assignment.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
word name_
Liquid name.
const liquidProperties * liquidPtr_
Pointer to the liquid properties.
bool ownLiquid_
Flag to indicate that model owns the liquid object.
bool useReferenceValues_
Flag to indicate that reference values of p and T should be used.
scalar pRef_
Reference pressure [pa].
scalar TRef_
Reference temperature [K].
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from filmThermoModel
static autoPtr< filmThermoModel > New (surfaceFilmModel &owner, const dictionary &dict)
Return a reference to the selected phase change model.
Detailed Description
Definition at line 56 of file liquidFilmThermo.H.
Constructor & Destructor Documentation
liquidFilmThermo() [1/2]
liquidFilmThermo (const liquidFilmThermo &) protected
Disallow default bitwise copy construct.
Referenced by liquidFilmThermo::initLiquid().
liquidFilmThermo() [2/2]
liquidFilmThermo (surfaceFilmModel & owner, const dictionary & dict)
Construct from surface film model and dictionary.
Definition at line 104 of file liquidFilmThermo.C.
References subModelBase::coeffDict_, liquidFilmThermo::initLiquid(), dictionary::lookup(), liquidFilmThermo::pRef_, liquidFilmThermo::TRef_, and liquidFilmThermo::useReferenceValues_.
~liquidFilmThermo()
~liquidFilmThermo () virtual
Destructor.
Definition at line 129 of file liquidFilmThermo.C.
References Foam::deleteDemandDrivenData(), liquidFilmThermo::liquidPtr_, and liquidFilmThermo::ownLiquid_.
Member Function Documentation
thermoFilm()
const thermoSingleLayer & thermoFilm () const protected
Return a reference to a thermo film.
Definition at line 56 of file liquidFilmThermo.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, and filmSubModelBase::owner_.
Referenced by liquidFilmThermo::Cp(), liquidFilmThermo::kappa(), liquidFilmThermo::mu(), liquidFilmThermo::rho(), and liquidFilmThermo::sigma().
initLiquid()
void initLiquid (const dictionary & dict) protected
Initialise the liquid pointer.
Definition at line 72 of file liquidFilmThermo.C.
References objectRegistry::foundObject(), liquidFilmThermo::liquidFilmThermo(), SLGThermo::liquidId(), liquidFilmThermo::liquidPtr_, SLGThermo::liquids(), dictionary::lookup(), objectRegistry::lookupObject(), liquidFilmThermo::name_, filmSubModelBase::owner_, liquidFilmThermo::ownLiquid_, regionModel::primaryMesh(), liquidMixtureProperties::properties(), and dictionary::subDict().
Referenced by liquidFilmThermo::liquidFilmThermo().
operator=()
void operator= (const liquidFilmThermo &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("liquid")
Runtime type information.
name()
const word & name () const virtual
Return the specie name.
Implements filmThermoModel.
Definition at line 140 of file liquidFilmThermo.C.
References liquidFilmThermo::name_, and liquidFilmThermo::rho().
rho() [1/2]
scalar rho (const scalar p, const scalar T) const virtual
Return density [kg/m3].
Implements filmThermoModel.
Definition at line 147 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, liquidFilmThermo::mu(), and liquidProperties::rho().
mu() [1/2]
scalar mu (const scalar p, const scalar T) const virtual
Return dynamic viscosity [Pa.s].
Implements filmThermoModel.
Definition at line 157 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, liquidProperties::mu(), and liquidFilmThermo::sigma().
sigma() [1/2]
scalar sigma (const scalar p, const scalar T) const virtual
Return surface tension [kg/s2].
Implements filmThermoModel.
Definition at line 167 of file liquidFilmThermo.C.
References liquidFilmThermo::Cp(), liquidFilmThermo::liquidPtr_, and liquidProperties::sigma().
Cp() [1/2]
scalar Cp (const scalar p, const scalar T) const virtual
Return specific heat capacity [J/kg/K].
Implements filmThermoModel.
Definition at line 177 of file liquidFilmThermo.C.
References liquidProperties::Cp(), liquidFilmThermo::kappa(), and liquidFilmThermo::liquidPtr_.
kappa() [1/2]
scalar kappa (const scalar p, const scalar T) const virtual
Return thermal conductivity [W/m/K].
Implements filmThermoModel.
Definition at line 187 of file liquidFilmThermo.C.
References liquidFilmThermo::D(), liquidProperties::K(), and liquidFilmThermo::liquidPtr_.
D()
scalar D (const scalar p, const scalar T) const virtual
Return diffusivity [m2/s].
Implements filmThermoModel.
Definition at line 197 of file liquidFilmThermo.C.
References liquidProperties::D(), liquidFilmThermo::hl(), and liquidFilmThermo::liquidPtr_.
Referenced by liquidFilmThermo::kappa().
hl()
scalar hl (const scalar p, const scalar T) const virtual
Return latent heat [J/kg].
Implements filmThermoModel.
Definition at line 207 of file liquidFilmThermo.C.
References liquidProperties::hl(), liquidFilmThermo::liquidPtr_, and liquidFilmThermo::pv().
Referenced by liquidFilmThermo::D().
pv()
scalar pv (const scalar p, const scalar T) const virtual
Return vapour pressure [Pa].
Implements filmThermoModel.
Definition at line 217 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, and liquidProperties::pv().
Referenced by liquidFilmThermo::hl().
W()
scalar W () const virtual
Return molecular weight [kg/kmol].
Implements filmThermoModel.
Definition at line 226 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, and liquidProperties::W().
Tb()
scalar Tb (const scalar p) const virtual
Return boiling temperature [K].
Implements filmThermoModel.
Definition at line 232 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, and liquidProperties::pvInvert().
rho() [2/2]
tmp< volScalarField > rho () const virtual
Return density [kg/m3].
Implements filmThermoModel.
Definition at line 238 of file liquidFilmThermo.C.
References Foam::dimDensity, forAll, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), kinematicSingleLayer::pPrimary(), liquidFilmThermo::pRef_, tmp< T >::ref(), thermoSingleLayer::T(), liquidFilmThermo::thermoFilm(), timeName, liquidFilmThermo::TRef_, trho, Foam::type(), and liquidFilmThermo::useReferenceValues_.
Referenced by liquidFilmThermo::name().
mu() [2/2]
tmp< volScalarField > mu () const virtual
Return dynamic viscosity [Pa.s].
Implements filmThermoModel.
Definition at line 286 of file liquidFilmThermo.C.
References Foam::dimPressure, Foam::dimTime, forAll, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), kinematicSingleLayer::pPrimary(), liquidFilmThermo::pRef_, tmp< T >::ref(), thermoSingleLayer::T(), liquidFilmThermo::thermoFilm(), timeName, liquidFilmThermo::TRef_, Foam::type(), and liquidFilmThermo::useReferenceValues_.
Referenced by liquidFilmThermo::rho().
sigma() [2/2]
tmp< volScalarField > sigma () const virtual
Return surface tension [kg/s2].
Implements filmThermoModel.
Definition at line 334 of file liquidFilmThermo.C.
References Foam::dimMass, Foam::dimTime, forAll, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), kinematicSingleLayer::pPrimary(), liquidFilmThermo::pRef_, tmp< T >::ref(), Foam::sqr(), thermoSingleLayer::T(), liquidFilmThermo::thermoFilm(), timeName, liquidFilmThermo::TRef_, Foam::type(), and liquidFilmThermo::useReferenceValues_.
Referenced by liquidFilmThermo::mu().
Cp() [2/2]
tmp< volScalarField > Cp () const virtual
Return specific heat capacity [J/kg/K].
Implements filmThermoModel.
Definition at line 382 of file liquidFilmThermo.C.
References Foam::dimEnergy, Foam::dimMass, Foam::dimTemperature, forAll, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), kinematicSingleLayer::pPrimary(), liquidFilmThermo::pRef_, tmp< T >::ref(), thermoSingleLayer::T(), liquidFilmThermo::thermoFilm(), timeName, liquidFilmThermo::TRef_, Foam::type(), and liquidFilmThermo::useReferenceValues_.
Referenced by liquidFilmThermo::sigma().
kappa() [2/2]
tmp< volScalarField > kappa () const virtual
Return thermal conductivity [W/m/K].
Implements filmThermoModel.
Definition at line 430 of file liquidFilmThermo.C.
References Foam::dimLength, Foam::dimPower, Foam::dimTemperature, forAll, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner(), kinematicSingleLayer::pPrimary(), liquidFilmThermo::pRef_, tmp< T >::ref(), thermoSingleLayer::T(), liquidFilmThermo::thermoFilm(), timeName, liquidFilmThermo::TRef_, Foam::type(), and liquidFilmThermo::useReferenceValues_.
Referenced by liquidFilmThermo::Cp().
Member Data Documentation
name_
word name_ protected
Liquid name.
Definition at line 65 of file liquidFilmThermo.H.
Referenced by liquidFilmThermo::initLiquid(), and liquidFilmThermo::name().
liquidPtr_
const liquidProperties* liquidPtr_ protected
Pointer to the liquid properties.
Definition at line 68 of file liquidFilmThermo.H.
Referenced by liquidFilmThermo::Cp(), liquidFilmThermo::D(), liquidFilmThermo::hl(), liquidFilmThermo::initLiquid(), liquidFilmThermo::kappa(), liquidFilmThermo::mu(), liquidFilmThermo::pv(), liquidFilmThermo::rho(), liquidFilmThermo::sigma(), liquidFilmThermo::Tb(), liquidFilmThermo::W(), and liquidFilmThermo::~liquidFilmThermo().
ownLiquid_
bool ownLiquid_ protected
Flag to indicate that model owns the liquid object.
Definition at line 71 of file liquidFilmThermo.H.
Referenced by liquidFilmThermo::initLiquid(), and liquidFilmThermo::~liquidFilmThermo().
useReferenceValues_
bool useReferenceValues_ protected
Flag to indicate that reference values of p and T should be used.
Definition at line 74 of file liquidFilmThermo.H.
Referenced by liquidFilmThermo::Cp(), liquidFilmThermo::kappa(), liquidFilmThermo::liquidFilmThermo(), liquidFilmThermo::mu(), liquidFilmThermo::rho(), and liquidFilmThermo::sigma().
pRef_
scalar pRef_ protected
Reference pressure [pa].
Definition at line 77 of file liquidFilmThermo.H.
Referenced by liquidFilmThermo::Cp(), liquidFilmThermo::kappa(), liquidFilmThermo::liquidFilmThermo(), liquidFilmThermo::mu(), liquidFilmThermo::rho(), and liquidFilmThermo::sigma().
TRef_
scalar TRef_ protected
Reference temperature [K].
Definition at line 80 of file liquidFilmThermo.H.
Referenced by liquidFilmThermo::Cp(), liquidFilmThermo::kappa(), liquidFilmThermo::liquidFilmThermo(), liquidFilmThermo::mu(), liquidFilmThermo::rho(), and liquidFilmThermo::sigma().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/liquidFilmThermo/liquidFilmThermo.H
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/liquidFilmThermo/liquidFilmThermo.C