OpenFOAM: patchInjection Class Reference
patchInjection Class Reference
Remove and inject the mass in the film as it passes over the selected patches.
Public Member Functions
TypeName ("patchInjection")
Runtime type information.
patchInjection (surfaceFilmModel &owner, const dictionary &dict)
Construct from surface film model.
virtual ~patchInjection ()
Destructor.
virtual void correct (scalarField &availableMass, scalarField &massToInject, scalarField &diameterToInject)
Correct.
virtual void patchInjectedMassTotals (scalarField &patchMasses) const
Accumulate the total mass injected for the patches into the.
Public Member Functions inherited from injectionModel
TypeName ("injectionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, injectionModel, dictionary,(surfaceFilmModel &owner, const dictionary &dict),(owner, dict))
injectionModel (surfaceFilmModel &owner)
Construct null.
injectionModel (const word &modelType, surfaceFilmModel &owner, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~injectionModel ()
Destructor.
virtual scalar injectedMassTotal () const
Return the total mass injected.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool writeTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Attributes
scalar deltaStable_
Stable film thickness - mass only removed if thickness execeeds.
labelList patchIDs_
List of patch IDs at which the film is removed.
scalarField patchInjectedMasses_
Injected mass for each patch at which the film is removed.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from injectionModel
static autoPtr< injectionModel > New (surfaceFilmModel &owner, const dictionary &dict, const word &mdoelType)
Return a reference to the selected injection model.
Protected Member Functions inherited from injectionModel
void addToInjectedMass (const scalar dMass)
Add to injected mass.
void correct ()
Correct.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Detailed Description
Remove and inject the mass in the film as it passes over the selected patches.
Source files
patchInjection.H
patchInjection.C
Definition at line 53 of file patchInjection.H.
Constructor & Destructor Documentation
patchInjection()
patchInjection (surfaceFilmModel & owner, const dictionary & dict)
Construct from surface film model.
Definition at line 46 of file patchInjection.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIter(), Foam::Info, IOobject::name(), Foam::nl, patchi, patchNames(), polyBoundaryMesh::patchSet(), regionModel::regionMesh(), PtrList< T >::setSize(), and UPtrList< T >::size().
~patchInjection()
~patchInjection () virtual
Destructor.
Definition at line 97 of file patchInjection.C.
References injectionModel::correct().
Member Function Documentation
TypeName()
TypeName ("patchInjection")
Runtime type information.
correct()
void correct (scalarField & availableMass, scalarField & massToInject, scalarField & diameterToInject) virtual
Correct.
Implements injectionModel.
Definition at line 104 of file patchInjection.C.
References injectionModel::addToInjectedMass(), polyMesh::boundaryMesh(), injectionModel::correct(), delta, surfaceFilmModel::delta(), patchInjection::deltaStable_, polyPatch::faceCells(), forAll, Pstream::listCombineGather(), singleLayerRegion::magSf(), Foam::max(), filmSubModelBase::owner(), patchi, patchInjection::patchIDs_, patchInjection::patchInjectedMasses_, patchInjection::patchInjectedMassTotals(), regionModel::regionMesh(), rho, surfaceFilmModel::rho(), List< T >::size(), and filmSubModelBase::writeTime().
patchInjectedMassTotals()
void patchInjectedMassTotals (scalarField & patchMasses) const virtual
Accumulate the total mass injected for the patches into the.
scalarField provided
Reimplemented from injectionModel.
Definition at line 171 of file patchInjection.C.
References forAll, Pstream::listCombineGather(), patchi, patchInjection::patchIDs_, patchInjection::patchInjectedMasses_, and List< T >::size().
Referenced by patchInjection::correct().
Member Data Documentation
deltaStable_
scalar deltaStable_ protected
Stable film thickness - mass only removed if thickness execeeds.
this threhold value
Definition at line 70 of file patchInjection.H.
Referenced by patchInjection::correct().
patchIDs_
labelList patchIDs_ protected
List of patch IDs at which the film is removed.
Definition at line 73 of file patchInjection.H.
Referenced by patchInjection::correct(), and patchInjection::patchInjectedMassTotals().
patchInjectedMasses_
scalarField patchInjectedMasses_ protected
Injected mass for each patch at which the film is removed.
Definition at line 76 of file patchInjection.H.
Referenced by patchInjection::correct(), and patchInjection::patchInjectedMassTotals().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/patchInjection/patchInjection.H
src/regionModels/surfaceFilmModels/submodels/kinematic/injectionModel/patchInjection/patchInjection.C