OpenFOAM: filmSubModelBase Class Reference
filmSubModelBase Class Reference
Public Member Functions
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool writeTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Attributes
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Detailed Description
Definition at line 54 of file filmSubModelBase.H.
Constructor & Destructor Documentation
filmSubModelBase() [1/3]
filmSubModelBase (surfaceFilmModel & owner)
Construct null.
Definition at line 39 of file filmSubModelBase.C.
Referenced by filmSubModelBase::filmSubModelBase().
filmSubModelBase() [2/3]
filmSubModelBase (surfaceFilmModel & owner, const dictionary & dict, const word & baseName, const word & modelType, const word & dictExt = "Coeffs")
Construct from owner film wihout name.
Definition at line 47 of file filmSubModelBase.C.
References filmSubModelBase::filmSubModelBase().
filmSubModelBase() [3/3]
filmSubModelBase (const word & modelName, surfaceFilmModel & owner, const dictionary & dict, const word & baseName, const word & modelType)
Construct from owner film with name.
Definition at line 68 of file filmSubModelBase.C.
~filmSubModelBase()
~filmSubModelBase () virtual
Destructor.
Definition at line 90 of file filmSubModelBase.C.
Member Function Documentation
writeTime()
bool writeTime () const virtual
Flag to indicate when to write a property.
Reimplemented from subModelBase.
Definition at line 96 of file filmSubModelBase.C.
References subModelBase::active(), filmSubModelBase::owner_, regionModel::time(), and TimeState::writeTime().
Referenced by injectionModel::correct(), patchInjection::correct(), phaseChangeModel::correct(), and injectionModelList::info().
owner() [1/2]
const surfaceFilmModel & owner () const inline
Return const access to the owner surface film model.
Definition at line 37 of file filmSubModelBaseI.H.
References filmSubModelBase::owner_.
Referenced by patchInjection::correct(), injectionModelList::correct(), contactAngleForce::correct(), drippingInjection::correct(), BrunDrippingInjection::correct(), curvatureSeparation::correct(), thixotropicViscosity::correct(), liquidFilmThermo::Cp(), constantFilmThermo::Cp(), injectionModelList::info(), liquidFilmThermo::kappa(), constantFilmThermo::kappa(), liquidFilmThermo::mu(), constantFilmThermo::mu(), liquidFilmThermo::rho(), constantFilmThermo::rho(), noRadiation::Shs(), primaryRadiation::Shs(), standardRadiation::Shs(), constantRadiation::Shs(), liquidFilmThermo::sigma(), constantFilmThermo::sigma(), and constantFilmThermo::thermoData::thermoData().
owner() [2/2]
surfaceFilmModel & owner () inline
Return the reference to the owner surface film model.
Definition at line 43 of file filmSubModelBaseI.H.
References filmSubModelBase::owner_.
filmType()
const FilmType & filmType () const inline
Definition at line 36 of file filmSubModelBaseTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, subModelBase::modelType(), and filmSubModelBase::owner_.
Member Data Documentation
owner_
surfaceFilmModel& owner_ protected
Reference to the owner surface film model.
Definition at line 63 of file filmSubModelBase.H.
Referenced by thermocapillaryForce::correct(), contactAngleForce::correct(), solidification::correctModel(), filmSubModelBase::filmType(), constantHeatTransfer::h(), phaseChangeModel::info(), liquidFilmThermo::initLiquid(), laminar::mut(), filmSubModelBase::owner(), primaryRadiation::Shs(), standardRadiation::Shs(), constantRadiation::Shs(), laminar::Su(), liquidFilmThermo::thermoFilm(), laminar::Us(), and filmSubModelBase::writeTime().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/filmSubModelBase.H
src/regionModels/surfaceFilmModels/submodels/filmSubModelBase.C
src/regionModels/surfaceFilmModels/submodels/filmSubModelBaseI.H
src/regionModels/surfaceFilmModels/submodels/filmSubModelBaseTemplates.C