OpenFOAM: laminar Class Reference
laminar Class Reference
Film laminar turbulence model.
Public Member Functions
TypeName ("laminar")
Runtime type information.
laminar (surfaceFilmModel &owner, const dictionary &dict)
Construct from surface film model.
virtual ~laminar ()
Destructor.
virtual tmp< volVectorField > Us () const
Return the film surface velocity.
virtual tmp< volScalarField > mut () const
Return the film turbulence viscosity.
virtual void correct ()
Correct/update the model.
virtual tmp< fvVectorMatrix > Su (volVectorField &U) const
Return the source for the film momentum equation.
Public Member Functions inherited from filmTurbulenceModel
TypeName ("filmTurbulenceModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, filmTurbulenceModel, dictionary,(surfaceFilmModel &owner, const dictionary &dict),(owner, dict))
filmTurbulenceModel (surfaceFilmModel &owner)
Construct null.
filmTurbulenceModel (const word &modelType, surfaceFilmModel &owner, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~filmTurbulenceModel ()
Destructor.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool writeTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Additional Inherited Members
Static Public Member Functions inherited from filmTurbulenceModel
static autoPtr< filmTurbulenceModel > New (surfaceFilmModel &owner, const dictionary &dict)
Return a reference to the selected injection model.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
Film laminar turbulence model.
Source files
laminar.H
laminar.C
Definition at line 52 of file laminar.H.
Constructor & Destructor Documentation
laminar()
laminar (surfaceFilmModel & owner, const dictionary & dict)
Construct from surface film model.
Definition at line 53 of file laminar.C.
~laminar()
~laminar () virtual
Destructor.
Definition at line 65 of file laminar.C.
Member Function Documentation
TypeName()
TypeName ("laminar")
Runtime type information.
Us()
tmp< volVectorField > Us () const virtual
Return the film surface velocity.
Implements filmTurbulenceModel.
Definition at line 71 of file laminar.C.
References Foam::dimVelocity, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner_, tmp< T >::ref(), regionModel::regionMesh(), Foam::sqrt(), fvMesh::time(), Time::timeName(), surfaceFilmModel::U(), and Foam::Zero.
mut()
tmp< volScalarField > mut () const virtual
Return the film turbulence viscosity.
Implements filmTurbulenceModel.
Definition at line 99 of file laminar.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, IOobject::NO_READ, IOobject::NO_WRITE, filmSubModelBase::owner_, regionModel::regionMesh(), fvMesh::time(), and Time::timeName().
correct()
void correct () virtual
Correct/update the model.
Implements filmTurbulenceModel.
Definition at line 120 of file laminar.C.
Su()
tmp< fvVectorMatrix > Su (volVectorField & U) const virtual
Return the source for the film momentum equation.
Implements filmTurbulenceModel.
Definition at line 126 of file laminar.C.
References delta, kinematicSingleLayer::delta(), kinematicSingleLayer::deltaSmall(), Foam::mag(), GeometricField< Type, PatchField, GeoMesh >::min(), Foam::constant::physicoChemical::mu, kinematicSingleLayer::mu(), filmSubModelBase::owner_, kinematicSingleLayer::rhoPrimary(), Foam::fvm::Sp(), kinematicSingleLayer::UPrimary(), and kinematicSingleLayer::Uw().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/filmTurbulenceModel/laminar/laminar.H
src/regionModels/surfaceFilmModels/submodels/kinematic/filmTurbulenceModel/laminar/laminar.C