OpenFOAM: thermalBaffleFvPatchScalarField Class Reference
thermalBaffleFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditions
This boundary condition provides a coupled temperature condition between multiple mesh regions.
Public Member Functions
TypeName ("compressible::thermalBaffle")
Runtime type information.
thermalBaffleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
thermalBaffleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
thermalBaffleFvPatchScalarField (const thermalBaffleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
thermalBaffleFvPatchScalarField (const thermalBaffleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from turbulentTemperatureRadCoupledMixedFvPatchScalarField
TypeName ("compressible::turbulentTemperatureRadCoupledMixed")
Runtime type information.
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
turbulentTemperatureRadCoupledMixedFvPatchScalarField (const turbulentTemperatureRadCoupledMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Public Member Functions inherited from temperatureCoupledBase
temperatureCoupledBase (const fvPatch &patch, const word &calculationMethod, const word &kappaName, const word &alphaAniName)
Construct from patch and K name.
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
Construct from patch and temperatureCoupledBase.
word KMethod () const
Method to obtain K.
const word & kappaName () const
Name of thermal conductivity field.
tmp< scalarField > kappa (const scalarField &Tp) const
Given patch temperature calculate corresponding K field.
void write (Ostream &) const
Write.
Additional Inherited Members
Public Types inherited from temperatureCoupledBase
enum KMethodType { mtFluidThermo, mtSolidThermo, mtDirectionalSolidThermo, mtLookup }
Type of supplied Kappa.
Protected Attributes inherited from temperatureCoupledBase
const fvPatch & patch_
Underlying patch.
const KMethodType method_
How to get K.
const word kappaName_
Name of thermal conductivity field (if looked up from database)
const word alphaAniName_
Name of the non-Isotropic alpha (default: Anialpha)
Static Protected Attributes inherited from temperatureCoupledBase
static const NamedEnum< KMethodType, 4 > KMethodTypeNames_
Detailed Description
This boundary condition provides a coupled temperature condition between multiple mesh regions.
The regions are generally referred to as the:
primary region,
and baffle region.
The primary region creates the baffle region and evolves its energy equation either:
1-D, normal to each patch face
2-D, normal and tangential components
The thermodynamic properties of the baffle material are specified via dictionary entries on the master patch.
Usage
Example of the boundary condition specification:
<masterPatchName>
{
    type                compressible::thermalBaffle;
    // Underlaying coupled boundary condition
    Tnbr               T;
    kappa              fluidThermo; // or solidThermo
    KappaName          none;
    QrNbr              Qr;//or none.Name of Qr field on neighbourregion
    Qr                 none;// or none.Name of Qr field on localregion
    value              uniform 300;
    // Baffle region name
    regionName          baffleRegion;
    active              yes;
    // Solid thermo in solid region
    thermoType
    {
        type            heSolidThermo;
        mixture         pureMixture;
        transport       constIso;
        thermo          hConst;
        equationOfState rhoConst;
        specie          specie;
        energy          sensibleEnthalpy;
    }
    mixture
    {
        specie
        {
            nMoles          1;
            molWeight       20;
        }
        transport
        {
            kappa           0.01;
        }
        thermodynamics
        {
            Hf              0;
            Cp              15;
        }
        density
        {
            rho             80;
        }
    }
    radiation
    {
        radiationModel  opaqueSolid;
        absorptionEmissionModel none;
        scatterModel    none;
    }
    // Extrude model for new region
    extrudeModel        linearNormal;
    nLayers             50;
    expansionRatio      1;
    columnCells         false; //3D or 1D
    linearNormalCoeffs
    {
        thickness           0.02;
    }
}
Slave patch on primary region:
<slavePatchName>
{
    type                compressible::thermalBaffle;
    kappa               fluidThermo;
    kappaName           none;
    value               uniform 300;
Patches on baffle region:
bottom
{
    type                compressible::thermalBaffle;
    kappa               solidThermo;
    kappaName           none;
    value               uniform 300;
}
top
{
    type                compressible::thermalBaffle;
    kappa               solidThermo;
    kappaName           none;
    value               uniform 300;
}
See also
Foam::compressible::turbulentTemperatureCoupledBaffleMixedFvPatchScalarField Foam::regionModels::thermalBaffleModels::thermalBaffleModel
Source files
thermalBaffleFvPatchScalarField.H
thermalBaffleFvPatchScalarField.C
Definition at line 179 of file thermalBaffleFvPatchScalarField.H.
Constructor & Destructor Documentation
thermalBaffleFvPatchScalarField() [1/4]
thermalBaffleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 43 of file thermalBaffleFvPatchScalarField.C.
Referenced by thermalBaffleFvPatchScalarField::clone(), and thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField().
thermalBaffleFvPatchScalarField() [2/4]
thermalBaffleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 81 of file thermalBaffleFvPatchScalarField.C.
References polyMesh::boundaryMesh(), polyMesh::defaultRegion, objectRegistry::foundObject(), polyBoundaryMesh::mesh(), fvMesh::name(), Foam::New(), regionName, thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), and fvMesh::time().
thermalBaffleFvPatchScalarField() [3/4]
thermalBaffleFvPatchScalarField (const thermalBaffleFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
thermalBaffleFvPatchScalarField onto a new patch
Definition at line 58 of file thermalBaffleFvPatchScalarField.C.
References thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField().
thermalBaffleFvPatchScalarField() [4/4]
thermalBaffleFvPatchScalarField (const thermalBaffleFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 126 of file thermalBaffleFvPatchScalarField.C.
References thermalBaffleFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("compressible::thermalBaffle")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 246 of file thermalBaffleFvPatchScalarField.H.
References thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 263 of file thermalBaffleFvPatchScalarField.H.
References thermalBaffleFvPatchScalarField::autoMap(), thermalBaffleFvPatchScalarField::rmap(), thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField(), thermalBaffleFvPatchScalarField::updateCoeffs(), and thermalBaffleFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 143 of file thermalBaffleFvPatchScalarField.C.
References thermalBaffleFvPatchScalarField::rmap().
Referenced by thermalBaffleFvPatchScalarField::clone(), and thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 152 of file thermalBaffleFvPatchScalarField.C.
References polyMesh::boundaryMesh(), mappedPatchBase::coupleGroup(), Foam::endl(), forAll, dictionary::lookup(), polyBoundaryMesh::mesh(), mappedPatchBase::mode(), polyPatch::New(), patchi, patchNames(), patchTypes(), Foam::readBool(), regionName, mappedPatchBase::sampleModeNames_, dictionary::set(), List< T >::size(), and WarningInFunction.
Referenced by thermalBaffleFvPatchScalarField::autoMap(), and thermalBaffleFvPatchScalarField::clone().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 249 of file thermalBaffleFvPatchScalarField.C.
References polyMesh::boundaryMesh(), polyMesh::defaultRegion, polyBoundaryMesh::mesh(), fvMesh::name(), and turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs().
Referenced by thermalBaffleFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from turbulentTemperatureRadCoupledMixedFvPatchScalarField.
Definition at line 267 of file thermalBaffleFvPatchScalarField.C.
References polyMesh::boundaryMesh(), polyMesh::defaultRegion, token::END_STATEMENT, dictionary::lookup(), Foam::compressible::makePatchTypeField(), polyBoundaryMesh::mesh(), fvMesh::name(), Foam::nl, Foam::readBool(), Foam::readLabel(), Foam::readScalar(), regionName, dictionary::subDict(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), and Ostream::writeKeyword().
Referenced by thermalBaffleFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/regionModels/thermalBaffleModels/derivedFvPatchFields/thermalBaffle/thermalBaffleFvPatchScalarField.H
src/regionModels/thermalBaffleModels/derivedFvPatchFields/thermalBaffle/thermalBaffleFvPatchScalarField.C