OpenFOAM: ArrheniusViscosity Class Reference
ArrheniusViscosity Class Reference
Public Member Functions
TypeName ("Arrhenius")
Runtime type information.
ArrheniusViscosity (surfaceFilmModel &owner, const dictionary &dict, volScalarField &mu)
Construct from surface film model.
virtual ~ArrheniusViscosity ()
Destructor.
virtual void correct (const volScalarField &p, const volScalarField &T)
Correct.
Public Member Functions inherited from filmViscosityModel
TypeName ("filmViscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, filmViscosityModel, dictionary,(surfaceFilmModel &owner, const dictionary &dict, volScalarField &mu),(owner, dict, mu))
filmViscosityModel (const word &modelType, surfaceFilmModel &owner, const dictionary &dict, volScalarField &mu)
Construct from type name, dictionary and surface film model.
virtual ~filmViscosityModel ()
Destructor.
virtual void info (Ostream &os) const
Provide some feedback.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmModel &owner)
Construct null.
filmSubModelBase (surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner film wihout name.
filmSubModelBase (const word &modelName, surfaceFilmModel &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool writeTime () const
Flag to indicate when to write a property.
const surfaceFilmModel & owner () const
Return const access to the owner surface film model.
surfaceFilmModel & owner ()
Return the reference to the owner surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=pTraits< Type >::zero) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Attributes
autoPtr< filmViscosityModel > viscosity_
Base viscosity model.
dimensionedScalar k1_
Coefficient k1.
dimensionedScalar k2_
Coefficient k2.
dimensionedScalar Tref_
Reference temperature.
Protected Attributes inherited from filmViscosityModel
volScalarField & mu_
Reference to the viscosity field.
Protected Attributes inherited from filmSubModelBase
surfaceFilmModel & owner_
Reference to the owner surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from filmViscosityModel
static autoPtr< filmViscosityModel > New (surfaceFilmModel &owner, const dictionary &dict, volScalarField &mu)
Return a reference to the selected phase change model.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Detailed Description
Definition at line 61 of file ArrheniusViscosity.H.
Constructor & Destructor Documentation
ArrheniusViscosity()
ArrheniusViscosity (surfaceFilmModel & owner, const dictionary & dict, volScalarField & mu)
Construct from surface film model.
Definition at line 53 of file ArrheniusViscosity.C.
~ArrheniusViscosity()
~ArrheniusViscosity () virtual
Destructor.
Definition at line 69 of file ArrheniusViscosity.C.
References ArrheniusViscosity::correct().
Member Function Documentation
TypeName()
TypeName ("Arrhenius")
Runtime type information.
correct()
void correct (const volScalarField & p, const volScalarField & T) virtual
Correct.
Implements filmViscosityModel.
Definition at line 76 of file ArrheniusViscosity.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::exp(), ArrheniusViscosity::k1_, ArrheniusViscosity::k2_, filmViscosityModel::mu_, ArrheniusViscosity::Tref_, and ArrheniusViscosity::viscosity_.
Referenced by ArrheniusViscosity::~ArrheniusViscosity().
Member Data Documentation
viscosity_
autoPtr<filmViscosityModel> viscosity_ protected
Base viscosity model.
Definition at line 79 of file ArrheniusViscosity.H.
Referenced by ArrheniusViscosity::correct().
k1_
dimensionedScalar k1_ protected
Coefficient k1.
Definition at line 82 of file ArrheniusViscosity.H.
Referenced by ArrheniusViscosity::correct().
k2_
dimensionedScalar k2_ protected
Coefficient k2.
Definition at line 85 of file ArrheniusViscosity.H.
Referenced by ArrheniusViscosity::correct().
Tref_
dimensionedScalar Tref_ protected
Reference temperature.
Definition at line 88 of file ArrheniusViscosity.H.
Referenced by ArrheniusViscosity::correct().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/thermo/filmViscosityModel/ArrheniusViscosity/ArrheniusViscosity.H
src/regionModels/surfaceFilmModels/submodels/thermo/filmViscosityModel/ArrheniusViscosity/ArrheniusViscosity.C