OpenFOAM: renumberMethod Class Reference
renumberMethod Class Reference abstract
Abstract base class for renumbering.
Public Member Functions
TypeName ("renumberMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~renumberMethod ()
Destructor.
virtual labelList renumber (const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &, const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const labelListList &cellCells, const pointField &cc) const =0
Return the order in which cells need to be visited, i.e.
Static Public Member Functions
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Return a reference to the selected renumbering method.
Protected Attributes
const dictionary & renumberDict_
Detailed Description
Abstract base class for renumbering.
Source files
renumberMethod.H
renumberMethod.C
Definition at line 48 of file renumberMethod.H.
Constructor & Destructor Documentation
renumberMethod()
renumberMethod (const dictionary & renumberDict) inline
Construct given the renumber dictionary.
Definition at line 98 of file renumberMethod.H.
~renumberMethod()
virtual ~renumberMethod () inline virtual
Destructor.
Definition at line 105 of file renumberMethod.H.
References mesh, NotImplemented, and renumberMethod::renumber().
Member Function Documentation
TypeName()
TypeName ("renumberMethod")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , renumberMethod , dictionary , (const dictionary &renumberDict) , (renumberDict))
New()
Foam::autoPtr< Foam::renumberMethod > New (const dictionary & renumberDict) static
Return a reference to the selected renumbering method.
Definition at line 43 of file renumberMethod.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), Foam::nl, and renumberMethod::renumber().
renumber() [1/5]
virtual labelList renumber (const pointField &) const inline virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. This is only defined for geometric renumberMethods.
Reimplemented in structuredRenumber, springRenumber, SloanRenumber, CuthillMcKeeRenumber, zoltanRenumber, manualRenumber, and randomRenumber.
Definition at line 114 of file renumberMethod.H.
Referenced by renumberMethod::New(), renumberMethod::renumber(), and renumberMethod::~renumberMethod().
renumber() [2/5]
Foam::labelList renumber (const polyMesh & mesh, const pointField & points) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Use the mesh connectivity (if needed)
Reimplemented in structuredRenumber, springRenumber, SloanRenumber, CuthillMcKeeRenumber, zoltanRenumber, manualRenumber, and randomRenumber.
Definition at line 69 of file renumberMethod.C.
References decompositionMethod::calcCellCells(), Foam::identity(), primitiveMesh::nCells(), Foam::renumber(), and renumberMethod::renumber().
renumber() [3/5]
Foam::labelList renumber (const labelList & cellCells, const labelList & offsets, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Addresing in losort addressing (= neighbour + offsets into neighbour)
Reimplemented in CuthillMcKeeRenumber.
Definition at line 90 of file renumberMethod.C.
References NotImplemented, and renumberMethod::renumber().
renumber() [4/5]
Foam::labelList renumber (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Gets passed agglomeration map (from fine to coarse cells) and coarse cell location. Can be overridden by renumberMethods that provide this functionality natively. Coarse cells are local to the processor (if in parallel). If you want to have coarse cells spanning processors use the globalCellCells instead.
Definition at line 102 of file renumberMethod.C.
References decompositionMethod::calcCellCells(), forAll, Foam::renumber(), and List< T >::size().
renumber() [5/5]
virtual labelList renumber (const labelListList & cellCells, const pointField & cc) const pure virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. The connectivity is equal to mesh.cellCells() except
the connections are across coupled patches
Implemented in structuredRenumber, springRenumber, CuthillMcKeeRenumber, SloanRenumber, zoltanRenumber, manualRenumber, and randomRenumber.
Member Data Documentation
renumberDict_
const dictionary& renumberDict_ protected
Definition at line 55 of file renumberMethod.H.
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/renumberMethod/renumberMethod.H
src/renumber/renumberMethods/renumberMethod/renumberMethod.C