OpenFOAM: structuredRenumber::layerLess Class Reference
structuredRenumber::layerLess Class Reference
Less function class that can be used for sorting according to.
Public Member Functions
layerLess (const Switch depthFirst, const labelList &order, const List< topoDistanceData > &distance)
bool operator() (const label a, const label b)
Detailed Description
Less function class that can be used for sorting according to.
column and layer
Definition at line 63 of file structuredRenumber.H.
Constructor & Destructor Documentation
layerLess()
layerLess (const Switch depthFirst, const labelList & order, const List< topoDistanceData > & distance) inline
Definition at line 72 of file structuredRenumber.H.
References Foam::constant::physicoChemical::b, and structuredRenumber::layerLess::operator()().
Member Function Documentation
operator()()
bool operator() (const label a, const label b)
Definition at line 67 of file structuredRenumber.C.
References Foam::constant::physicoChemical::b, topoDistanceData::data(), topoDistanceData::distance(), structuredRenumber::renumber(), and topoDistanceData::valid().
Referenced by structuredRenumber::layerLess::layerLess().
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/structuredRenumber/structuredRenumber.H
src/renumber/renumberMethods/structuredRenumber/structuredRenumber.C