OpenFOAM: joint Class Reference
joint Class Reference abstract
Abstract base-class for all rigid-body joints.
Classes
class iNew
class XSvc
Joint state returned by jcalc.
Public Member Functions
TypeName ("joint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, joint, dictionary,(const dictionary &dict),(dict))
joint (const label nDoF)
Construct joint setting the size of the motion sub-space.
virtual autoPtr< joint > clone () const =0
Clone this joint (needed by PtrList)
virtual ~joint ()
Destructor.
label nDoF () const
Return the number of degrees of freedom in this joint.
virtual bool unitQuaternion () const
Return true if this joint describes rotation using a quaternion.
label index () const
Return the index of this joint in the model.
label qIndex () const
Return start index for the state variables for this joint.
const List< spatialVector > & S () const
Return the joint motion sub-space.
virtual void jcalc (XSvc &J, const scalarField &q, const scalarField &qDot) const =0
Update the rigidBodyModel state for the joint given.
virtual void write (Ostream &) const
Write.
quaternion unitQuaternion (const scalarField &q) const
Return the unit quaternion for this joint.
void unitQuaternion (const quaternion &quat, scalarField &q) const
Set the unit quaternion for this joint.
Static Public Member Functions
static autoPtr< joint > New (joint *jointPtr)
Simple selector to return an autoPtr<joint> of the given joint*.
static autoPtr< joint > New (const dictionary &dict)
Select from dictionary.
Protected Attributes
List< spatialVector > S_
Joint motion sub-space.
label index_
Index of this joint in the rigidBodyModel.
label qIndex_
Index of this joints data in the rigidBodyModel state.
Friends
class rigidBodyModel
Allow the rigidBodyModel class to set the joint indices.
Ostream & operator<< (Ostream &, const joint &)
Detailed Description
Abstract base-class for all rigid-body joints.
Reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
    Chapter 4.
Source files
joint.H
jointI.H
joint.C
Definition at line 79 of file joint.H.
Constructor & Destructor Documentation
joint()
joint (const label nDoF) inline
Construct joint setting the size of the motion sub-space.
to the given degrees of freedom of the joint
Definition at line 28 of file jointI.H.
Referenced by joint::XSvc::XSvc().
~joint()
~joint () virtual
Destructor.
Definition at line 75 of file joint.C.
Referenced by joint::iNew::iNew().
Member Function Documentation
TypeName()
TypeName ("joint")
Runtime type information.
Referenced by joint::XSvc::XSvc().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , joint , dictionary , (const dictionary &dict) , (dict))
Referenced by joint::XSvc::XSvc().
clone()
virtual autoPtr<joint> clone () const pure virtual
Clone this joint (needed by PtrList)
Implemented in composite, floating, Rs, Rxyz, Ryxz, Rzyx, null, Pa, Px, Pxyz, Py, Pz, Ra, Rx, Ry, and Rz.
Referenced by joint::XSvc::XSvc().
New() [1/2]
Foam::autoPtr< Foam::RBD::joint > New (joint * jointPtr) static
Simple selector to return an autoPtr<joint> of the given joint*.
Definition at line 43 of file joint.C.
Referenced by joint::iNew::iNew(), joint::iNew::operator()(), and rigidBodyModel::rigidBodyModel().
New() [2/2]
Foam::autoPtr< Foam::RBD::joint > New (const dictionary & dict) static
Select from dictionary.
Definition at line 50 of file joint.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), and Foam::nl.
nDoF()
Foam::label nDoF () const inline
Return the number of degrees of freedom in this joint.
Definition at line 38 of file jointI.H.
References joint::S_.
Referenced by rigidBodyModel::forwardDynamics(), rigidBodyModel::forwardDynamicsCorrection(), joint::iNew::iNew(), rigidBodyModel::join_(), and joint::XSvc::XSvc().
unitQuaternion() [1/3]
bool unitQuaternion () const inline virtual
Return true if this joint describes rotation using a quaternion.
Reimplemented in Rs.
Definition at line 43 of file jointI.H.
Referenced by joint::iNew::iNew(), Rs::jcalc(), rigidBodyModel::join_(), joint::S(), and joint::unitQuaternion().
index()
Foam::label index () const inline
Return the index of this joint in the model.
Definition at line 48 of file jointI.H.
References joint::index_.
qIndex()
Foam::label qIndex () const inline
Return start index for the state variables for this joint.
in the rigidBodyModel state fields
Definition at line 53 of file jointI.H.
References joint::qIndex_.
S()
const Foam::List< Foam::spatialVector > & S () const inline
Return the joint motion sub-space.
Definition at line 58 of file jointI.H.
References joint::S_, and joint::unitQuaternion().
jcalc()
virtual void jcalc (XSvc & J, const scalarField & q, const scalarField & qDot) const pure virtual
Update the rigidBodyModel state for the joint given.
the joint state q, w and velocity qDot
Implemented in composite, Rs, Rxyz, Ryxz, Rzyx, null, Pa, Px, Pxyz, Py, Pz, Ra, Rx, Ry, and Rz.
Referenced by rigidBodyModel::forwardDynamics(), rigidBodyModel::forwardDynamicsCorrection(), and joint::iNew::iNew().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in composite, Pa, Ra, and floating.
Definition at line 81 of file joint.C.
References token::END_STATEMENT, Foam::nl, Foam::type(), and Ostream::writeKeyword().
Referenced by joint::iNew::iNew(), Foam::RBD::operator<<(), floating::write(), Ra::write(), Pa::write(), and composite::write().
unitQuaternion() [2/3]
Foam::quaternion unitQuaternion (const scalarField & q) const inline
Return the unit quaternion for this joint.
if it uses a quaternion representation for rotation
Definition at line 67 of file jointI.H.
References Foam::abort(), Field< Type >::block(), Foam::FatalError, FatalErrorInFunction, joint::qIndex_, quaternion::unit(), and joint::unitQuaternion().
unitQuaternion() [3/3]
void unitQuaternion (const quaternion & quat, scalarField & q) const inline
Set the unit quaternion for this joint.
if it uses a quaternion representation for rotation
Definition at line 83 of file jointI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, joint::qIndex_, joint::unitQuaternion(), quaternion::v(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Friends And Related Function Documentation
rigidBodyModel
friend class rigidBodyModel friend
Allow the rigidBodyModel class to set the joint indices.
Definition at line 116 of file joint.H.
operator<<
Ostream& operator<< (Ostream & , const joint &) friend
Referenced by joint::iNew::iNew().
Member Data Documentation
S_
List<spatialVector> S_ protected
Joint motion sub-space.
Definition at line 87 of file joint.H.
Referenced by Pa::jcalc(), Py::jcalc(), Rx::jcalc(), Ry::jcalc(), Px::jcalc(), Pz::jcalc(), Rz::jcalc(), Ra::jcalc(), joint::nDoF(), Pa::Pa(), Px::Px(), Pxyz::Pxyz(), Py::Py(), Pz::Pz(), Ra::Ra(), Rs::Rs(), Rx::Rx(), Rxyz::Rxyz(), Ry::Ry(), Ryxz::Ryxz(), Rz::Rz(), Rzyx::Rzyx(), joint::S(), Ra::write(), and Pa::write().
index_
label index_ protected
Index of this joint in the rigidBodyModel.
Definition at line 90 of file joint.H.
Referenced by joint::index().
qIndex_
label qIndex_ protected
Index of this joints data in the rigidBodyModel state.
Definition at line 93 of file joint.H.
Referenced by Pa::jcalc(), Px::jcalc(), Rz::jcalc(), Ra::jcalc(), Pxyz::jcalc(), Rx::jcalc(), Py::jcalc(), Ry::jcalc(), Pz::jcalc(), Rxyz::jcalc(), Rzyx::jcalc(), Ryxz::jcalc(), Rs::jcalc(), joint::qIndex(), and joint::unitQuaternion().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/joints/joint/joint.H
src/rigidBodyDynamics/joints/joint/joint.C
src/rigidBodyDynamics/joints/joint/jointI.H