OpenFOAM: structuredRenumber Class Reference
structuredRenumber Class Reference
Renumbering according to mesh layers. depthFirst = true: first column gets ids 0..nLayer-1, second nLayers..2*nLayers-1 etc. depthFirst = false: first layer gets ids 0,1,2 etc.
Classes
class layerLess
Less function class that can be used for sorting according to.
Public Member Functions
void operator= (const structuredRenumber &)
Disallow default bitwise copy construct and assignment.
structuredRenumber (const structuredRenumber &)
TypeName ("structured")
Runtime type information.
structuredRenumber (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~structuredRenumber ()
Destructor.
virtual labelList renumber (const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const labelListList &cellCells, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~renumberMethod ()
Destructor.
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
Return the order in which cells need to be visited, i.e.
Public Attributes
const dictionary methodDict_
const wordReList patches_
const label nLayers_
const Switch depthFirst_
const autoPtr< renumberMethod > method_
const Switch reverse_
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Return a reference to the selected renumbering method.
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Renumbering according to mesh layers. depthFirst = true: first column gets ids 0..nLayer-1, second nLayers..2*nLayers-1 etc. depthFirst = false: first layer gets ids 0,1,2 etc.
Source files
structuredRenumber.H
structuredRenumber.C
Definition at line 53 of file structuredRenumber.H.
Constructor & Destructor Documentation
structuredRenumber() [1/2]
structuredRenumber (const structuredRenumber &)
structuredRenumber() [2/2]
structuredRenumber (const dictionary & renumberDict)
Construct given the renumber dictionary.
Definition at line 50 of file structuredRenumber.C.
~structuredRenumber()
virtual ~structuredRenumber () inline virtual
Destructor.
Definition at line 122 of file structuredRenumber.H.
References mesh, NotImplemented, and structuredRenumber::renumber().
Member Function Documentation
operator=()
void operator= (const structuredRenumber &)
Disallow default bitwise copy construct and assignment.
TypeName()
TypeName ("structured")
Runtime type information.
renumber() [1/3]
virtual labelList renumber (const pointField &) const inline virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. This is only defined for geometric renumberMethods.
Reimplemented from renumberMethod.
Definition at line 131 of file structuredRenumber.H.
Referenced by structuredRenumber::layerLess::operator()(), and structuredRenumber::~structuredRenumber().
renumber() [2/3]
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Use the mesh connectivity (if needed)
Reimplemented from renumberMethod.
Definition at line 136 of file structuredRenumber.C.
References polyMesh::boundaryMesh(), fvMeshSubset::cellMap(), Foam::endl(), Foam::exit(), polyPatch::faceCells(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIter(), polyMesh::globalData(), Foam::Info, HashSet< Key, Hash >::insert(), Foam::invert(), primitiveMesh::nCells(), primitiveMesh::nFaces(), Foam::nl, globalMeshData::nTotalCells(), polyBoundaryMesh::patchSet(), Foam::renumber(), Foam::returnReduce(), Foam::reverse(), fvMeshSubset::setLargeCellSubset(), List< T >::size(), UPtrList< T >::size(), HashTable< T, Key, Hash >::size(), Foam::sortedOrder(), polyPatch::start(), fvMeshSubset::subMesh(), and Foam::type().
renumber() [3/3]
virtual labelList renumber (const labelListList & cellCells, const pointField & cc) const inline virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. The connectivity is equal to mesh.cellCells() except
the connections are across coupled patches
Implements renumberMethod.
Definition at line 151 of file structuredRenumber.H.
References NotImplemented.
Member Data Documentation
methodDict_
const dictionary methodDict_
Definition at line 89 of file structuredRenumber.H.
patches_
const wordReList patches_
Definition at line 91 of file structuredRenumber.H.
nLayers_
const label nLayers_
Definition at line 93 of file structuredRenumber.H.
depthFirst_
const Switch depthFirst_
Definition at line 95 of file structuredRenumber.H.
method_
const autoPtr<renumberMethod> method_
Definition at line 97 of file structuredRenumber.H.
reverse_
const Switch reverse_
Definition at line 99 of file structuredRenumber.H.
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/structuredRenumber/structuredRenumber.H
src/renumber/renumberMethods/structuredRenumber/structuredRenumber.C