OpenFOAM: OppositeFaceCellWave< Type, TrackingData > Class Template Reference
OppositeFaceCellWave< Type, TrackingData > Class Template Reference
Version of FaceCellWave that walks through prismatic cells only.
Public Member Functions
OppositeFaceCellWave (const polyMesh &, const labelList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=FaceCellWave< Type, TrackingData >::dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
virtual ~OppositeFaceCellWave ()
Destructor.
virtual label faceToCell ()
Propagate from face to cell. Returns total number of cells.
virtual label cellToFace ()
Propagate from cell to face. Returns total number of faces.
Public Member Functions inherited from FaceCellWave< Type, TrackingData >
FaceCellWave (const polyMesh &, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, TrackingData &td=dummyTrackData_)
FaceCellWave (const polyMesh &, const labelList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
FaceCellWave (const polyMesh &, const labelPairList &explicitConnections, const bool handleCyclicAMI, const labelList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh and explicitly connected boundary faces.
virtual ~FaceCellWave ()
Destructor.
UList< Type > & allFaceInfo ()
Access allFaceInfo.
UList< Type > & allCellInfo ()
Access allCellInfo.
const TrackingData & data () const
Additional data to be passed into container.
const polyMesh & mesh () const
Access mesh.
label getUnsetCells () const
Get number of unvisited cells, i.e. cells that were not (yet)
label getUnsetFaces () const
Get number of unvisited faces.
void setFaceInfo (const labelList &changedFaces, const List< Type > &changedFacesInfo)
Set initial changed faces.
virtual label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
Protected Member Functions
void opposingFaceLabels (const label celli, const label facei, DynamicList< label > &) const
Determine 'opposite' faces (= faces not sharing a vertex) on cell.
Protected Member Functions inherited from FaceCellWave< Type, TrackingData >
bool updateCell (const label celli, const label neighbourFacei, const Type &neighbourInfo, const scalar tol, Type &cellInfo)
Updates cellInfo with information from neighbour. Updates all.
bool updateFace (const label facei, const label neighbourCelli, const Type &neighbourInfo, const scalar tol, Type &faceInfo)
Updates faceInfo with information from neighbour. Updates all.
bool updateFace (const label facei, const Type &neighbourInfo, const scalar tol, Type &faceInfo)
Updates faceInfo with information from same face. Updates all.
void checkCyclic (const polyPatch &pPatch) const
Debugging: check info on both sides of cyclic.
template<class PatchType >
bool hasPatch () const
Has cyclic patch?
void mergeFaceInfo (const polyPatch &patch, const label nFaces, const labelList &, const List< Type > &)
Merge received patch data into global data.
label getChangedPatchFaces (const polyPatch &patch, const label startFacei, const label nFaces, labelList &changedPatchFaces, List< Type > &changedPatchFacesInfo) const
Extract info for single patch only.
void leaveDomain (const polyPatch &patch, const label nFaces, const labelList &faceLabels, List< Type > &faceInfo) const
Handle leaving domain. Implementation referred to Type.
void enterDomain (const polyPatch &patch, const label nFaces, const labelList &faceLabels, List< Type > &faceInfo) const
Handle leaving domain. Implementation referred to Type.
void transform (const tensorField &rotTensor, const label nFaces, List< Type > &faceInfo)
Apply transformation to Type.
void handleProcPatches ()
Merge data from across processor boundaries.
void handleCyclicPatches ()
Merge data from across cyclics.
void handleAMICyclicPatches ()
Merge data from across AMI cyclics.
void handleExplicitConnections ()
Merge data across explicitly provided local connections (usually.
Protected Attributes
DynamicList< label > changedOppositeFaces_
For every entry in changedCells (i.e. the cell front) gives.
Protected Attributes inherited from FaceCellWave< Type, TrackingData >
const polyMesh & mesh_
Reference to mesh.
const labelPairList explicitConnections_
Optional boundary faces that information should travel through.
UList< Type > & allFaceInfo_
Information for all faces.
UList< Type > & allCellInfo_
Information for all cells.
TrackingData & td_
Additional data to be passed into container.
PackedBoolList changedFace_
Has face changed.
DynamicList< label > changedFaces_
List of changed faces.
PackedBoolList changedCell_
Has cell changed.
DynamicList< label > changedCells_
const bool hasCyclicPatches_
Contains cyclics.
const bool hasCyclicAMIPatches_
Contains cyclicAMI.
label nEvals_
Number of evaluations.
label nUnvisitedCells_
Number of unvisited cells/faces.
label nUnvisitedFaces_
Additional Inherited Members
Static Public Member Functions inherited from FaceCellWave< Type, TrackingData >
static scalar propagationTol ()
Access to tolerance.
static void setPropagationTol (const scalar tol)
Change tolerance.
Static Protected Member Functions inherited from FaceCellWave< Type, TrackingData >
static void offset (const polyPatch &patch, const label off, const label nFaces, labelList &faces)
Offset face labels by constant value.
Static Protected Attributes inherited from FaceCellWave< Type, TrackingData >
static const scalar geomTol_ = 1e-6
static scalar propagationTol_ = 0.01
static int dummyTrackData_ = 12345
Used as default trackdata value to satisfy default template.
Detailed Description
template<class Type, class TrackingData = int>
class Foam::OppositeFaceCellWave< Type, TrackingData >
Version of FaceCellWave that walks through prismatic cells only.
Used to determine mesh structure. In the front walking routines (faceToCell and faceToCell) it
walks across prismatic cells only
and only to a single opposite face
Notes: A cell with a split faces will be marked but not walked through (since there is no single opposite face.
Source files
OppositeFaceCellWave.H
OppositeFaceCellWave.C
Definition at line 65 of file OppositeFaceCellWave.H.
Constructor & Destructor Documentation
OppositeFaceCellWave()
OppositeFaceCellWave (const polyMesh & mesh, const labelList & initialChangedFaces, const List< Type > & changedFacesInfo, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, const label maxIter, TrackingData & td = FaceCellWave<Type, TrackingData>::dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
for these faces. Iterates until nothing changes or maxIter reached. (maxIter can be 0)
Definition at line 98 of file OppositeFaceCellWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorInFunction.
Referenced by OppositeFaceCellWave< Type, TrackingData >::opposingFaceLabels().
~OppositeFaceCellWave()
virtual ~OppositeFaceCellWave () inline virtual
Destructor.
Definition at line 110 of file OppositeFaceCellWave.H.
References OppositeFaceCellWave< Type, TrackingData >::cellToFace(), and OppositeFaceCellWave< Type, TrackingData >::faceToCell().
Member Function Documentation
opposingFaceLabels()
void opposingFaceLabels (const label celli, const label facei, DynamicList< label > & oppositeFaceLabels) const protected
Determine 'opposite' faces (= faces not sharing a vertex) on cell.
Definition at line 33 of file OppositeFaceCellWave.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), forAll, and OppositeFaceCellWave< Type, TrackingData >::OppositeFaceCellWave().
faceToCell()
Foam::label faceToCell () virtual
Propagate from face to cell. Returns total number of cells.
(over all processors) changed.
Reimplemented from FaceCellWave< Type, TrackingData >.
Definition at line 139 of file OppositeFaceCellWave.C.
References Foam::abort(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, Foam::reduce(), and List< T >::size().
Referenced by OppositeFaceCellWave< Type, TrackingData >::~OppositeFaceCellWave().
cellToFace()
Foam::label cellToFace () virtual
Propagate from cell to face. Returns total number of faces.
(over all processors) changed. (Faces on processorpatches are counted double)
Reimplemented from FaceCellWave< Type, TrackingData >.
Definition at line 256 of file OppositeFaceCellWave.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Pout, and Foam::reduce().
Referenced by OppositeFaceCellWave< Type, TrackingData >::~OppositeFaceCellWave().
Member Data Documentation
changedOppositeFaces_
DynamicList<label> changedOppositeFaces_ protected
For every entry in changedCells (i.e. the cell front) gives.
the face that it needs to transfer to
Definition at line 76 of file OppositeFaceCellWave.H.
The documentation for this class was generated from the following files:
src/renumber/renumberMethods/structuredRenumber/OppositeFaceCellWave.H
src/renumber/renumberMethods/structuredRenumber/OppositeFaceCellWave.C