OpenFOAM: subBody Class Reference
subBody Class Reference
Public Member Functions
subBody (const autoPtr< rigidBody > &bodyPtr, const word &masterName, const label masterID, const spatialTransform &masterXT)
Construct a merged version of the given rigidBody.
autoPtr< subBody > clone () const
Return clone of this subBody.
const rigidBody & body () const
Return the original body from which this sub-body was constructed.
const word & name () const
Return the body name.
const word & masterName () const
Return the master body name.
label masterID () const
Return the master body Id.
const spatialTransform & masterXT () const
Return the transform with respect to the master body.
void write (Ostream &) const
Write.
Detailed Description
Definition at line 52 of file subBody.H.
Constructor & Destructor Documentation
subBody()
subBody (const autoPtr< rigidBody > & bodyPtr, const word & masterName, const label masterID, const spatialTransform & masterXT) inline
Construct a merged version of the given rigidBody.
providing the ID of the master body to which this will be merged and the transform relative to the master
Definition at line 29 of file subBodyI.H.
Referenced by subBody::clone().
Member Function Documentation
clone()
Foam::autoPtr< Foam::RBD::subBody > clone () const inline
Return clone of this subBody.
Definition at line 43 of file subBodyI.H.
References subBody::subBody().
body()
const Foam::RBD::rigidBody & body () const inline
Return the original body from which this sub-body was constructed.
Definition at line 51 of file subBodyI.H.
Referenced by rigidBody::merge().
name()
const Foam::word & name () const inline
Return the body name.
Definition at line 57 of file subBodyI.H.
Referenced by rigidBodyModel::merge(), and rigidBodyModel::name().
masterName()
const Foam::word & masterName () const inline
Return the master body name.
Definition at line 63 of file subBodyI.H.
masterID()
Foam::label masterID () const inline
Return the master body Id.
Definition at line 69 of file subBodyI.H.
Referenced by rigidBodyModel::join_(), rigidBodyModel::master(), rigidBodyModel::merge(), rigidBodyModel::X0(), and rigidBodyMotion::X00().
masterXT()
const Foam::spatialTransform & masterXT () const inline
Return the transform with respect to the master body.
Definition at line 75 of file subBodyI.H.
Referenced by rigidBodyModel::join_(), rigidBody::merge(), rigidBodyModel::merge(), rigidBodyModel::X0(), and rigidBodyMotion::X00().
write()
void write (Ostream & os) const
Write.
Definition at line 30 of file subBody.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/bodies/subBody/subBody.H
src/rigidBodyDynamics/bodies/subBody/subBody.C
src/rigidBodyDynamics/bodies/subBody/subBodyI.H