OpenFOAM: zoltanRenumber Class Reference
zoltanRenumber Class Reference
Renumber using Zoltan.
Public Member Functions
TypeName ("zoltan")
Runtime type information.
zoltanRenumber (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~zoltanRenumber ()
Destructor.
virtual labelList renumber (const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const labelListList &cellCells, const pointField &cc) const
Return the order in which cells need to be visited, i.e.
Public Member Functions inherited from renumberMethod
TypeName ("renumberMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, renumberMethod, dictionary,(const dictionary &renumberDict),(renumberDict))
renumberMethod (const dictionary &renumberDict)
Construct given the renumber dictionary.
virtual ~renumberMethod ()
Destructor.
virtual labelList renumber (const labelList &cellCells, const labelList &offsets, const pointField &) const
Return the order in which cells need to be visited, i.e.
virtual labelList renumber (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
Return the order in which cells need to be visited, i.e.
Additional Inherited Members
Static Public Member Functions inherited from renumberMethod
static autoPtr< renumberMethod > New (const dictionary &renumberDict)
Return a reference to the selected renumbering method.
Protected Attributes inherited from renumberMethod
const dictionary & renumberDict_
Detailed Description
Renumber using Zoltan.
Use Zoltan.
Zoltan install:
in your ~/.bashrc: export ZOLTAN_ARCH_DIR=\ $WM_THIRD_PARTY_DIR/platforms/linux64Gcc/Zoltan_XXX
unpack into $WM_THIRD_PARTY_DIR
cd Zoltan_XXX
mkdir build
cd build
export CCFLAGS="-fPIC"
export CXXFLAGS="-fPIC"
export CFLAGS="-fPIC"
export LDFLAGS="-shared"
../configure \ –prefix=$ZOLTAN_ARCH_DIR \ –with-ccflags=-fPIC –with-cxxflags=-fPIC –with-ldflags=-shared
Source files
zoltanRenumber.C
zoltanRenumber.C
Source files
zoltanRenumber.H
zoltanRenumber.C
Definition at line 46 of file zoltanRenumber.H.
Constructor & Destructor Documentation
zoltanRenumber()
zoltanRenumber (const dictionary & renumberDict)
Construct given the renumber dictionary.
Definition at line 260 of file zoltanRenumber.C.
References zoltanRenumber::renumber().
~zoltanRenumber()
virtual ~zoltanRenumber () inline virtual
Destructor.
Definition at line 76 of file zoltanRenumber.H.
References mesh, NotImplemented, and zoltanRenumber::renumber().
Member Function Documentation
TypeName()
TypeName ("zoltan")
Runtime type information.
renumber() [1/3]
virtual labelList renumber (const pointField &) const inline virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. This is only defined for geometric renumberMethods.
Reimplemented from renumberMethod.
Definition at line 85 of file zoltanRenumber.H.
Referenced by zoltanRenumber::zoltanRenumber(), and zoltanRenumber::~zoltanRenumber().
renumber() [2/3]
Foam::labelList renumber (const polyMesh & mesh, const pointField & cc) const virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. Use the mesh connectivity (if needed)
Reimplemented from renumberMethod.
Definition at line 270 of file zoltanRenumber.C.
References args, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIter(), get_edge_list(), get_geom_list(), get_mesh_dim(), get_num_edges_list(), get_number_of_vertices(), get_vertex_list(), polyMesh::globalData(), Foam::Info, mesh, primitiveMesh::nCells(), globalMeshData::nTotalCells(), Foam::Pout, and List< T >::size().
renumber() [3/3]
virtual labelList renumber (const labelListList & cellCells, const pointField & cc) const inline virtual
Return the order in which cells need to be visited, i.e.
from ordered back to original cell label. The connectivity is equal to mesh.cellCells() except
the connections are across coupled patches
Implements renumberMethod.
Definition at line 105 of file zoltanRenumber.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/renumber/zoltanRenumber/zoltanRenumber.H
src/renumber/zoltanRenumber/zoltanRenumber.C