OpenFOAM: masslessBody Class Reference
masslessBody Class Reference
Public Member Functions
TypeName ("masslessBody")
Runtime type information.
masslessBody ()
Construct a massless body.
masslessBody (const word &name)
Construct a named massless body.
masslessBody (const word &name, const dictionary &dict)
Construct from dictionary.
virtual autoPtr< rigidBody > clone () const
Return clone of this masslessBody.
virtual ~masslessBody ()
Destructor.
virtual bool massless () const
Return true if this body is a massless component of a composite body.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from rigidBody
TypeName ("rigidBody")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, rigidBody, dictionary,(const word &name, const dictionary &dict),(name, dict))
rigidBody (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
Construct from mass, centre of mass and moment of inertia tensor.
rigidBody (const word &name, const rigidBodyInertia &rbi)
Construct from with the given rigidBodyInertia.
rigidBody (const word &name, const dictionary &dict)
Construct from dictionary.
virtual ~rigidBody ()
Destructor.
const word & name () const
Return name.
void merge (const subBody &)
Merge a body into this parent body.
Public Member Functions inherited from rigidBodyInertia
rigidBodyInertia ()
Null constructor, initializes to zero.
rigidBodyInertia (const scalar m, const vector &c, const symmTensor &Ic)
Construct from mass, centre of mass and moment of inertia tensor.
rigidBodyInertia (const dictionary &dict)
Construct from dictionary.
rigidBodyInertia (const spatialTensor &st)
Construct from the components of a spatial tensor.
rigidBodyInertia (Istream &is)
Construct from Istream.
scalar m () const
Return the mass of the rigid-body.
const vector & c () const
Return the centre of mass of the rigid-body.
const symmTensor & Ic () const
Return the inertia tensor of the rigid-body about the centre of mass.
symmTensor Ioc () const
Return the difference between the inertia tensor of the rigid-body.
symmTensor Icc (const vector &c) const
Return the difference between the inertia tensor of the rigid-body.
symmTensor Io () const
Return the inertia tensor of the rigid-body about the origin.
scalar kineticEnergy (const spatialVector &v)
Return the kinetic energy of the body with the given velocity.
operator spatialTensor () const
Conversion to spatial tensor.
void operator+= (const rigidBodyInertia &)
Additional Inherited Members
Static Public Member Functions inherited from rigidBody
static autoPtr< rigidBody > New (const word &name, const scalar &m, const vector &c, const symmTensor &Ic)
Select constructed from components.
static autoPtr< rigidBody > New (const word &name, const dictionary &dict)
Select constructed from name and dictionary.
Static Public Member Functions inherited from rigidBodyInertia
static symmTensor Ioc (const scalar m, const vector &c)
Return the difference between the inertia tensor of the rigid-body.
Detailed Description
Definition at line 50 of file masslessBody.H.
Constructor & Destructor Documentation
masslessBody() [1/3]
masslessBody () inline
Construct a massless body.
Definition at line 28 of file masslessBodyI.H.
Referenced by masslessBody::masslessBody().
masslessBody() [2/3]
masslessBody (const word & name) inline
Construct a named massless body.
Definition at line 34 of file masslessBodyI.H.
References masslessBody::masslessBody().
masslessBody() [3/3]
masslessBody (const word & name, const dictionary & dict) inline
Construct from dictionary.
Definition at line 41 of file masslessBodyI.H.
~masslessBody()
~masslessBody () virtual
Destructor.
Definition at line 57 of file masslessBody.C.
Member Function Documentation
TypeName()
TypeName ("masslessBody")
Runtime type information.
clone()
Foam::autoPtr< Foam::RBD::rigidBody > clone () const virtual
Return clone of this masslessBody.
Reimplemented from rigidBody.
Reimplemented in jointBody.
Definition at line 49 of file masslessBody.C.
massless()
bool massless () const virtual
Return true if this body is a massless component of a composite body.
Reimplemented from rigidBody.
Definition at line 63 of file masslessBody.C.
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from rigidBody.
Definition at line 69 of file masslessBody.C.
References token::END_STATEMENT, Foam::nl, Foam::type(), and Ostream::writeKeyword().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/bodies/masslessBody/masslessBody.H
src/rigidBodyDynamics/bodies/masslessBody/masslessBody.C
src/rigidBodyDynamics/bodies/masslessBody/masslessBodyI.H