OpenFOAM: composite Class Reference
composite Class Reference
Prismatic joint for translation along the specified arbitrary axis.
Public Member Functions
TypeName ("composite")
Runtime type information.
composite (const PtrList< joint > &joints)
Construct for given PtrList<joint>
composite (const dictionary &dict)
Construct for given model from dictionary.
virtual autoPtr< joint > clone () const
Clone this joint.
virtual ~composite ()
Destructor.
virtual void jcalc (joint::XSvc &J, const scalarField &q, const scalarField &qDot) const
Update the model state for this joint.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from PtrList< joint >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< joint > &)
Copy constructor.
PtrList (const PtrList< joint > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< joint >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< joint > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< joint > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (joint *)
Append an element at the end of the list.
void append (const autoPtr< joint > &)
void append (const tmp< joint > &)
void transfer (PtrList< joint > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< joint > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< joint > set (const label, joint *)
Set element to given T* and return old element (can be nullptr)
autoPtr< joint > set (const label, const autoPtr< joint > &)
Set element to given autoPtr<T> and return old element.
autoPtr< joint > set (const label, const tmp< joint > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< joint > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Public Member Functions inherited from joint
TypeName ("joint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, joint, dictionary,(const dictionary &dict),(dict))
joint (const label nDoF)
Construct joint setting the size of the motion sub-space.
virtual ~joint ()
Destructor.
label nDoF () const
Return the number of degrees of freedom in this joint.
virtual bool unitQuaternion () const
Return true if this joint describes rotation using a quaternion.
label index () const
Return the index of this joint in the model.
label qIndex () const
Return start index for the state variables for this joint.
const List< spatialVector > & S () const
Return the joint motion sub-space.
quaternion unitQuaternion (const scalarField &q) const
Return the unit quaternion for this joint.
void unitQuaternion (const quaternion &quat, scalarField &q) const
Set the unit quaternion for this joint.
Friends
class Foam::RBD::rigidBodyModel
Allow the rigidBodyModel class to set the last joint state.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Static Public Member Functions inherited from joint
static autoPtr< joint > New (joint *jointPtr)
Simple selector to return an autoPtr<joint> of the given joint*.
static autoPtr< joint > New (const dictionary &dict)
Select from dictionary.
Protected Member Functions inherited from PtrList< joint >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Protected Attributes inherited from joint
List< spatialVector > S_
Joint motion sub-space.
label index_
Index of this joint in the rigidBodyModel.
label qIndex_
Index of this joints data in the rigidBodyModel state.
Detailed Description
Prismatic joint for translation along the specified arbitrary axis.
Reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
    Chapter 4.
Source files
compositeJoint.H
composite.C
Definition at line 64 of file compositeJoint.H.
Constructor & Destructor Documentation
composite() [1/2]
composite (const PtrList< joint > & joints)
Construct for given PtrList<joint>
Definition at line 61 of file compositeJoint.C.
Referenced by composite::clone().
composite() [2/2]
composite (const dictionary & dict)
Construct for given model from dictionary.
Definition at line 68 of file compositeJoint.C.
~composite()
~composite () virtual
Destructor.
Definition at line 83 of file compositeJoint.C.
References composite::jcalc().
Member Function Documentation
TypeName()
TypeName ("composite")
Runtime type information.
clone()
Foam::autoPtr< Foam::RBD::joint > clone () const virtual
Clone this joint.
Implements joint.
Reimplemented in floating.
Definition at line 75 of file compositeJoint.C.
References composite::composite().
jcalc()
void jcalc (joint::XSvc & J, const scalarField & q, const scalarField & qDot) const virtual
Update the model state for this joint.
Implements joint.
Definition at line 90 of file compositeJoint.C.
References UPtrList< T >::last().
Referenced by composite::~composite().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from joint.
Reimplemented in floating.
Definition at line 100 of file compositeJoint.C.
References joint::write(), and Ostream::writeKeyword().
Friends And Related Function Documentation
Foam::RBD::rigidBodyModel
friend class Foam::RBD::rigidBodyModel friend
Allow the rigidBodyModel class to set the last joint state.
Definition at line 82 of file compositeJoint.H.
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/joints/composite/compositeJoint.H
src/rigidBodyDynamics/joints/composite/compositeJoint.C