OpenFOAM: rigidBodyModelState Class Reference
rigidBodyModelState Class Reference
Holds the motion state of rigid-body model.
Public Member Functions
rigidBodyModelState (const rigidBodyModel &model)
Construct for the given rigidBodyModel.
rigidBodyModelState (const rigidBodyModel &model, const dictionary &dict)
Construct from dictionary for the given rigidBodyModel.
const scalarField & q () const
Return access to the joint position and orientation.
const scalarField & qDot () const
Return access to the joint quaternion.
const scalarField & qDdot () const
Return access to the joint acceleration.
scalar deltaT () const
Return access to the time-step.
scalarField & q ()
Return access to the joint position and orientation.
scalarField & qDot ()
Return access to the joint quaternion.
scalarField & qDdot ()
Return access to the joint acceleration.
scalar & deltaT ()
Return access to the time-step.
void write (dictionary &dict) const
Write to dictionary.
void write (Ostream &) const
Write to stream.
Friends
Istream & operator>> (Istream &, rigidBodyModelState &)
Ostream & operator<< (Ostream &, const rigidBodyModelState &)
Detailed Description
Holds the motion state of rigid-body model.
Source files
rigidBodyModelState.H
rigidBodyModelStateI.H
rigidBodyModelState.C
rigidBodyModelStateIO.C
Definition at line 65 of file rigidBodyModelState.H.
Constructor & Destructor Documentation
rigidBodyModelState() [1/2]
rigidBodyModelState (const rigidBodyModel & model)
Construct for the given rigidBodyModel.
Definition at line 31 of file rigidBodyModelState.C.
rigidBodyModelState() [2/2]
rigidBodyModelState (const rigidBodyModel & model, const dictionary & dict)
Construct from dictionary for the given rigidBodyModel.
Definition at line 43 of file rigidBodyModelState.C.
Member Function Documentation
q() [1/2]
const Foam::scalarField & q () const inline
Return access to the joint position and orientation.
Definition at line 28 of file rigidBodyModelStateI.H.
Referenced by rigidBodyModel::forwardDynamics(), rigidBodyModel::forwardDynamicsCorrection(), rigidBodySolver::q(), and rigidBodySolver::q0().
qDot() [1/2]
const Foam::scalarField & qDot () const inline
Return access to the joint quaternion.
Return access to the joint velocity
Definition at line 34 of file rigidBodyModelStateI.H.
Referenced by rigidBodyModel::forwardDynamics(), rigidBodyModel::forwardDynamicsCorrection(), rigidBodySolver::qDot(), and rigidBodySolver::qDot0().
qDdot() [1/2]
const Foam::scalarField & qDdot () const inline
Return access to the joint acceleration.
Definition at line 40 of file rigidBodyModelStateI.H.
Referenced by rigidBodyMotion::forwardDynamics(), rigidBodyModel::forwardDynamics(), rigidBodyModel::forwardDynamicsCorrection(), rigidBodySolver::qDdot(), and rigidBodySolver::qDdot0().
deltaT() [1/2]
Foam::scalar deltaT () const inline
Return access to the time-step.
Definition at line 46 of file rigidBodyModelStateI.H.
Referenced by rigidBodySolver::deltaT(), rigidBodySolver::deltaT0(), and rigidBodyMotion::solve().
q() [2/2]
Foam::scalarField & q () inline
Return access to the joint position and orientation.
Definition at line 52 of file rigidBodyModelStateI.H.
qDot() [2/2]
Foam::scalarField & qDot () inline
Return access to the joint quaternion.
Return access to the joint velocity
Definition at line 58 of file rigidBodyModelStateI.H.
qDdot() [2/2]
Foam::scalarField & qDdot () inline
Return access to the joint acceleration.
Definition at line 64 of file rigidBodyModelStateI.H.
deltaT() [2/2]
Foam::scalar & deltaT () inline
Return access to the time-step.
Definition at line 70 of file rigidBodyModelStateI.H.
write() [1/2]
void write (dictionary & dict) const
Write to dictionary.
Definition at line 31 of file rigidBodyModelStateIO.C.
References dictionary::add().
Referenced by rigidBodyMeshMotionSolver::writeObject().
write() [2/2]
void write (Ostream & os) const
Write to stream.
Definition at line 40 of file rigidBodyModelStateIO.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , rigidBodyModelState &) friend
operator<<
Ostream& operator<< (Ostream & , const rigidBodyModelState &) friend
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodyModelState/rigidBodyModelState.H
src/rigidBodyDynamics/rigidBodyModelState/rigidBodyModelState.C
src/rigidBodyDynamics/rigidBodyModelState/rigidBodyModelStateI.H
src/rigidBodyDynamics/rigidBodyModelState/rigidBodyModelStateIO.C