OpenFOAM: rigidBodySolver Class Reference
rigidBodySolver Class Reference abstract
Public Member Functions
TypeName ("rigidBodySolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, rigidBodySolver, dictionary,(rigidBodyMotion &body, const dictionary &dict),(body, dict))
rigidBodySolver (rigidBodyMotion &body)
virtual ~rigidBodySolver ()
Destructor.
virtual void solve (const scalarField &tau, const Field< spatialVector > &fx)=0
Integrate the rigid-body motion for one time-step.
Static Public Member Functions
static autoPtr< rigidBodySolver > New (rigidBodyMotion &body, const dictionary &dict)
Protected Member Functions
rigidBodyModelState & state ()
Return the motion state.
scalarField & q ()
Return the current joint position and orientation.
scalarField & qDot ()
Return the current joint quaternion.
scalarField & qDdot ()
Return the current joint acceleration.
scalar deltaT () const
Return the current time-step.
const rigidBodyModelState & state0 () const
Return the previous motion state.
const scalarField & q0 () const
Return the current joint position and orientation.
const scalarField & qDot0 () const
Return the current joint quaternion.
const scalarField & qDdot0 () const
Return the current joint acceleration.
scalar deltaT0 () const
Return the previous time-step.
void correctQuaternionJoints ()
Correct the quaternion joints based on the current change in q.
Protected Attributes
rigidBodyMotion & model_
The rigid-body model.
Detailed Description
Source files
rigidBodySolver.H
rigidBodySolver.C
newSixDoFSolver.C
Definition at line 51 of file rigidBodySolver.H.
Constructor & Destructor Documentation
rigidBodySolver()
rigidBodySolver (rigidBodyMotion & body)
Definition at line 43 of file rigidBodySolver.C.
~rigidBodySolver()
~rigidBodySolver () virtual
Destructor.
Definition at line 51 of file rigidBodySolver.C.
Member Function Documentation
state()
Foam::RBD::rigidBodyModelState & state () inline protected
Return the motion state.
Definition at line 28 of file rigidBodySolverI.H.
References rigidBodySolver::model_.
Referenced by rigidBodySolver::q(), rigidBodySolver::qDdot(), and rigidBodySolver::qDot().
q()
Foam::scalarField & q () inline protected
Return the current joint position and orientation.
Definition at line 34 of file rigidBodySolverI.H.
References rigidBodyModelState::q(), and rigidBodySolver::state().
Referenced by rigidBodySolver::correctQuaternionJoints().
qDot()
Foam::scalarField & qDot () inline protected
Return the current joint quaternion.
Return the current joint velocity
Definition at line 40 of file rigidBodySolverI.H.
References rigidBodyModelState::qDot(), and rigidBodySolver::state().
qDdot()
Foam::scalarField & qDdot () inline protected
Return the current joint acceleration.
Definition at line 46 of file rigidBodySolverI.H.
References rigidBodyModelState::qDdot(), and rigidBodySolver::state().
deltaT()
Foam::scalar deltaT () const inline protected
Return the current time-step.
Definition at line 52 of file rigidBodySolverI.H.
References rigidBodyModelState::deltaT(), and rigidBodySolver::model_.
state0()
const Foam::RBD::rigidBodyModelState & state0 () const inline protected
Return the previous motion state.
Definition at line 59 of file rigidBodySolverI.H.
References rigidBodySolver::model_.
Referenced by rigidBodySolver::q0(), rigidBodySolver::qDdot0(), and rigidBodySolver::qDot0().
q0()
const Foam::scalarField & q0 () const inline protected
Return the current joint position and orientation.
Definition at line 64 of file rigidBodySolverI.H.
References rigidBodyModelState::q(), and rigidBodySolver::state0().
Referenced by rigidBodySolver::correctQuaternionJoints().
qDot0()
const Foam::scalarField & qDot0 () const inline protected
Return the current joint quaternion.
Return the current joint velocity
Definition at line 70 of file rigidBodySolverI.H.
References rigidBodyModelState::qDot(), and rigidBodySolver::state0().
qDdot0()
const Foam::scalarField & qDdot0 () const inline protected
Return the current joint acceleration.
Definition at line 76 of file rigidBodySolverI.H.
References rigidBodyModelState::qDdot(), and rigidBodySolver::state0().
deltaT0()
Foam::scalar deltaT0 () const inline protected
Return the previous time-step.
Definition at line 82 of file rigidBodySolverI.H.
References rigidBodyModelState::deltaT(), and rigidBodySolver::model_.
correctQuaternionJoints()
void correctQuaternionJoints () protected
Correct the quaternion joints based on the current change in q.
Definition at line 57 of file rigidBodySolver.C.
References Foam::cos(), forAll, rigidBodyModel::joints(), Foam::mag(), rigidBodySolver::model_, Foam::normalize(), rigidBodySolver::q(), rigidBodySolver::q0(), and rigidBodyModel::unitQuaternions().
TypeName()
TypeName ("rigidBodySolver")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , rigidBodySolver , dictionary , (rigidBodyMotion &body, const dictionary &dict) , (body, dict))
New()
Foam::autoPtr< Foam::RBD::rigidBodySolver > New (rigidBodyMotion & body, const dictionary & dict) static
Definition at line 31 of file newRigidBodySolver.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, and dictionary::lookup().
solve()
virtual void solve (const scalarField & tau, const Field< spatialVector > & fx) pure virtual
Integrate the rigid-body motion for one time-step.
Implemented in CrankNicolson, Newmark, and symplectic.
Member Data Documentation
model_
rigidBodyMotion& model_ protected
The rigid-body model.
Definition at line 58 of file rigidBodySolver.H.
Referenced by rigidBodySolver::correctQuaternionJoints(), rigidBodySolver::deltaT(), rigidBodySolver::deltaT0(), rigidBodySolver::state(), and rigidBodySolver::state0().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodySolvers/rigidBodySolver/rigidBodySolver.H
src/rigidBodyDynamics/rigidBodySolvers/rigidBodySolver/newRigidBodySolver.C
src/rigidBodyDynamics/rigidBodySolvers/rigidBodySolver/rigidBodySolver.C
src/rigidBodyDynamics/rigidBodySolvers/rigidBodySolver/rigidBodySolverI.H