OpenFOAM: rigidBodyMotion Class Reference
rigidBodyMotion Class Reference
Six degree of freedom motion for a rigid body.
Public Member Functions
rigidBodyMotion ()
Construct null.
rigidBodyMotion (const dictionary &dict)
Construct from dictionary.
rigidBodyMotion (const dictionary &dict, const dictionary &stateDict)
Construct from constant and state dictionaries.
~rigidBodyMotion ()
Destructor.
bool report () const
Return the report Switch.
const rigidBodyModelState & state () const
Return the motion state.
rigidBodyModelState & state ()
Return the motion state for modification.
spatialTransform X00 (const label bodyId) const
Return the initial transform to the global frame for the.
void newTime ()
Store the motion state at the beginning of the time-step.
void forwardDynamics (rigidBodyModelState &state, const scalarField &tau, const Field< spatialVector > &fx) const
Calculate and optionally relax the joint acceleration qDdot from.
void solve (scalar deltaT, const scalarField &tau, const Field< spatialVector > &fx)
Integrate velocities, orientation and position.
void status (const label bodyID) const
Report the status of the motion of the given body.
tmp< pointField > transformPoints (const label bodyID, const pointField &initialPoints) const
Transform the given initial pointField of the specified body.
tmp< pointField > transformPoints (const label bodyID, const scalarField &weight, const pointField &initialPoints) const
Transform the given initial pointField of the specified body.
tmp< pointField > transformPoints (const labelList &bodyIDs, const List< const scalarField *> &weights, const pointField &initialPoints) const
Transform the given initial pointField of the specified body.
void write (Ostream &) const
Write.
bool read (const dictionary &dict)
Read coefficients dictionary and update system parameters,.
Public Member Functions inherited from rigidBodyModel
TypeName ("rigidBodyModel")
Runtime type information.
rigidBodyModel ()
Null-constructor which adds the single root-body at the origin.
rigidBodyModel (const dictionary &dict)
Construct from dictionary.
virtual ~rigidBodyModel ()
Destructor.
label nBodies () const
Return the number of bodies in the model (bodies().size())
PtrList< rigidBody > bodies () const
Return the list of the bodies in the model.
const DynamicList< label > & lambda () const
List of indices of the parent of each body.
const PtrList< joint > & joints () const
Return the list of joints in the model.
label nDoF () const
Return the number of degrees of freedom of the model.
bool unitQuaternions () const
Return true if any of the joints using quaternions.
const vector & g () const
Return the acceleration due to gravity.
vector & g ()
Allow the acceleration due to gravity to be set.
const word & name (const label bodyID) const
Return the name of body with the given ID.
const rigidBodyInertia & I (const label i) const
Return the inertia of body i.
const spatialVector & v (const label i) const
Return the spatial velocity of the bodies.
virtual label join (const label parentID, const spatialTransform &XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
label join (const label parentID, const spatialTransform &XT, autoPtr< joints::composite > cJoint, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
label merge (const label parentID, const spatialTransform &X, autoPtr< rigidBody > bodyPtr)
Merge the given body with transform X into the parent with ID.
bool merged (label bodyID) const
Return true if the body with given ID has been merged with a parent.
label master (label bodyID) const
Return the ID of the master body for a sub-body otherwise.
label mergedBodyIndex (const label mergedBodyID) const
Return the index of the merged body in the mergedBody list.
label mergedBodyID (const label mergedBodyIndex) const
Return the merged body ID for the given merged body index.
const subBody & mergedBody (label mergedBodyID) const
Return the merged body for the given body ID.
label bodyID (const word &name) const
Return the ID of the body with the given name.
spatialTransform X0 (const label bodyId) const
Return the current transform to the global frame for the given body.
vector masterPoint (const label bodyID, const vector &p) const
spatialVector v (const label bodyID, const vector &p) const
Return the velocity of the given point on the given body.
void applyRestraints (scalarField &tau, Field< spatialVector > &fx) const
Apply the restraints and accumulate the internal joint forces.
void forwardDynamics (rigidBodyModelState &state, const scalarField &tau, const Field< spatialVector > &fx) const
Calculate the joint acceleration qDdot from the joint state q,.
void forwardDynamicsCorrection (const rigidBodyModelState &state) const
Correct the velocity and acceleration of the bodies in the model.
bool read (const dictionary &dict)
Read coefficients dictionary and update system parameters,.
Friends
class rigidBodySolver
Additional Inherited Members
Protected Member Functions inherited from rigidBodyModel
virtual label join_ (const label parentID, const spatialTransform &XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
Protected Attributes inherited from rigidBodyModel
PtrList< rigidBody > bodies_
List of the bodies.
PtrList< subBody > mergedBodies_
Bodies may be merged into existing bodies, the inertia of which is.
HashTable< label, word > bodyIDs_
Lookup-table of the IDs of the bodies.
DynamicList< label > lambda_
List of indices of the parent of each body.
PtrList< joint > joints_
Each body it attached with a joint which are held on this list.
DynamicList< spatialTransform > XT_
Transform from the parent body frame to the joint frame.
label nDoF_
The number of degrees of freedom of the model.
bool unitQuaternions_
True if any of the joints using quaternions.
PtrList< restraint > restraints_
Motion restraints.
vector g_
Acceleration due to gravity.
DynamicList< spatialTransform > Xlambda_
Transform from the parent body to the current body.
DynamicList< spatialTransform > X0_
Transform for external forces to the bodies reference frame.
DynamicList< spatialVector > v_
The spatial velocity of the bodies.
DynamicList< spatialVector > a_
The spatial acceleration of the bodies.
DynamicList< spatialVector > c_
The velocity dependent spatial acceleration of the joints.
DynamicList< spatialTensor > IA_
Velocity-product acceleration.
DynamicList< spatialVector > pA_
Articulated body bias force.
DynamicList< compactSpatialTensor > S_
Motion subspace for joints with 3 degrees of freedom.
DynamicList< spatialVector > S1_
Motion subspace for joints with 1 degrees of freedom.
DynamicList< compactSpatialTensor > U_
Sub-expression IA.S in the forward-dynamics algorithm.
DynamicList< spatialVector > U1_
Sub-expression IA.S1 in the forward-dynamics algorithm.
DynamicList< tensor > Dinv_
Sub-expression (S^T.U)^-1 in the forward-dynamics algorithm.
DynamicList< vector > u_
Sub-expression tau - S^T.pA in the forward-dynamics algorithm.
Detailed Description
Six degree of freedom motion for a rigid body.
Angular momentum stored in body fixed reference frame. Reference orientation of the body (where Q = I) must align with the cartesian axes such that the Inertia tensor is in principle component form. Can add restraints (e.g. a spring) and constraints (e.g. motion may only be on a plane).
The time-integrator for the motion is run-time selectable with options for symplectic (explicit), Crank-Nicolson and Newmark schemes.
Source files
rigidBodyMotion.H
rigidBodyMotionI.H
rigidBodyMotion.C
rigidBodyMotionIO.C
Definition at line 67 of file rigidBodyMotion.H.
Constructor & Destructor Documentation
rigidBodyMotion() [1/3]
rigidBodyMotion ()
Construct null.
Definition at line 45 of file rigidBodyMotion.C.
Referenced by rigidBodyMotion::rigidBodyMotion().
rigidBodyMotion() [2/3]
rigidBodyMotion (const dictionary & dict)
Construct from dictionary.
Definition at line 57 of file rigidBodyMotion.C.
References dictionary::found(), rigidBodyModel::g(), dictionary::lookup(), and rigidBodyMotion::rigidBodyMotion().
rigidBodyMotion() [3/3]
rigidBodyMotion (const dictionary & dict, const dictionary & stateDict)
Construct from constant and state dictionaries.
Definition at line 80 of file rigidBodyMotion.C.
References dictionary::found(), rigidBodyModel::g(), and dictionary::lookup().
~rigidBodyMotion()
~rigidBodyMotion ()
Destructor.
Definition at line 105 of file rigidBodyMotion.C.
References rigidBodyMotion::X00().
Member Function Documentation
report()
bool report () const inline
Return the report Switch.
Definition at line 28 of file rigidBodyMotionI.H.
Referenced by rigidBodyMeshMotionSolver::solve().
state() [1/2]
const Foam::RBD::rigidBodyModelState & state () const inline
Return the motion state.
Definition at line 35 of file rigidBodyMotionI.H.
Referenced by rigidBodyMeshMotionSolver::writeObject().
state() [2/2]
Foam::RBD::rigidBodyModelState & state () inline
Return the motion state for modification.
Definition at line 42 of file rigidBodyMotionI.H.
X00()
Foam::spatialTransform X00 (const label bodyId) const
Return the initial transform to the global frame for the.
given body
Definition at line 112 of file rigidBodyMotion.C.
References rigidBodyMotion::forwardDynamics(), subBody::masterID(), subBody::masterXT(), rigidBodyModel::merged(), and rigidBodyModel::mergedBody().
Referenced by rigidBodyMotion::transformPoints(), and rigidBodyMotion::~rigidBodyMotion().
newTime()
void newTime () inline
Store the motion state at the beginning of the time-step.
Definition at line 48 of file rigidBodyMotionI.H.
Referenced by rigidBodyMeshMotionSolver::solve().
forwardDynamics()
void forwardDynamics (rigidBodyModelState & state, const scalarField & tau, const Field< spatialVector > & fx) const
Calculate and optionally relax the joint acceleration qDdot from.
the joint state q, velocity qDot, internal force tau (in the joint frame) and external force fx (in the global frame)
Definition at line 129 of file rigidBodyMotion.C.
References rigidBodyModel::forwardDynamics(), rigidBodyModelState::qDdot(), and rigidBodyMotion::solve().
Referenced by rigidBodyMotion::X00().
solve()
void solve (scalar deltaT, const scalarField & tau, const Field< spatialVector > & fx)
Integrate velocities, orientation and position.
for the given time-step
Definition at line 142 of file rigidBodyMotion.C.
References rigidBodyModelState::deltaT(), rigidBodyModel::forwardDynamicsCorrection(), UPstream::master(), and Pstream::scatter().
Referenced by rigidBodyMotion::forwardDynamics(), and rigidBodyMeshMotionSolver::solve().
status()
void status (const label bodyID) const
Report the status of the motion of the given body.
Definition at line 167 of file rigidBodyMotion.C.
References spatialTransform::E(), Foam::endl(), Foam::Info, SpatialVector< Cmpt >::l(), rigidBodyModel::name(), Foam::nl, spatialTransform::r(), rigidBodyMotion::transformPoints(), rigidBodyModel::v(), SpatialVector< Cmpt >::w(), rigidBodyModel::X0(), and Foam::Zero.
Referenced by rigidBodyMeshMotionSolver::solve().
transformPoints() [1/3]
Foam::tmp< Foam::pointField > transformPoints (const label bodyID, const pointField & initialPoints) const
Transform the given initial pointField of the specified body.
to correspond to the current motion state
Definition at line 182 of file rigidBodyMotion.C.
References forAll, Foam::inv(), points, tmp< T >::ref(), List< T >::size(), spatialTransform::transformPoint(), rigidBodyModel::X0(), and rigidBodyMotion::X00().
Referenced by rigidBodyMeshMotionSolver::solve(), rigidBodyMotion::status(), and rigidBodyMotion::transformPoints().
transformPoints() [2/3]
Foam::tmp< Foam::pointField > transformPoints (const label bodyID, const scalarField & weight, const pointField & initialPoints) const
Transform the given initial pointField of the specified body.
to correspond to the current motion state scaled using 'slerp' interpolation
Definition at line 204 of file rigidBodyMotion.C.
References forAll, septernion::I, Foam::inv(), points, tmp< T >::ref(), s(), Foam::slerp(), spatialTransform::transformPoint(), rigidBodyMotion::transformPoints(), rigidBodyModel::X0(), and rigidBodyMotion::X00().
transformPoints() [3/3]
Foam::tmp< Foam::pointField > transformPoints (const labelList & bodyIDs, const List< const scalarField *> & weights, const pointField & initialPoints) const
Transform the given initial pointField of the specified body.
to correspond to the current motion state scaled using 'slerp' interpolation
Definition at line 246 of file rigidBodyMotion.C.
References Foam::average(), forAll, septernion::I, Foam::inv(), rigidBodyModel::lambda(), points, tmp< T >::ref(), List< T >::size(), rigidBodyModel::X0(), and rigidBodyMotion::X00().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from rigidBodyModel.
Definition at line 43 of file rigidBodyMotionIO.C.
References token::END_STATEMENT, Foam::nl, rigidBodyModel::write(), and Ostream::writeKeyword().
read()
bool read (const dictionary & dict)
Read coefficients dictionary and update system parameters,.
constraints and restraints but not the current state
Definition at line 31 of file rigidBodyMotionIO.C.
References dictionary::lookupOrDefault(), and rigidBodyModel::read().
Referenced by rigidBodyMeshMotionSolver::read().
Friends And Related Function Documentation
rigidBodySolver
friend class rigidBodySolver friend
Definition at line 71 of file rigidBodyMotion.H.
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodyMotion/rigidBodyMotion.H
src/rigidBodyDynamics/rigidBodyMotion/rigidBodyMotion.C
src/rigidBodyDynamics/rigidBodyMotion/rigidBodyMotionI.H
src/rigidBodyDynamics/rigidBodyMotion/rigidBodyMotionIO.C