OpenFOAM: Rx Class Reference
Rx Class Reference
Revolute joint for rotation about the x-axis.
Public Member Functions
TypeName ("Rx")
Runtime type information.
Rx ()
Construct for given model.
Rx (const dictionary &dict)
Construct for given model from dictionary.
virtual autoPtr< joint > clone () const
Clone this joint.
virtual ~Rx ()
Destructor.
virtual void jcalc (joint::XSvc &J, const scalarField &q, const scalarField &qDot) const
Update the model state for this joint.
Public Member Functions inherited from joint
TypeName ("joint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, joint, dictionary,(const dictionary &dict),(dict))
joint (const label nDoF)
Construct joint setting the size of the motion sub-space.
virtual ~joint ()
Destructor.
label nDoF () const
Return the number of degrees of freedom in this joint.
virtual bool unitQuaternion () const
Return true if this joint describes rotation using a quaternion.
label index () const
Return the index of this joint in the model.
label qIndex () const
Return start index for the state variables for this joint.
const List< spatialVector > & S () const
Return the joint motion sub-space.
virtual void write (Ostream &) const
Write.
quaternion unitQuaternion (const scalarField &q) const
Return the unit quaternion for this joint.
void unitQuaternion (const quaternion &quat, scalarField &q) const
Set the unit quaternion for this joint.
Additional Inherited Members
Static Public Member Functions inherited from joint
static autoPtr< joint > New (joint *jointPtr)
Simple selector to return an autoPtr<joint> of the given joint*.
static autoPtr< joint > New (const dictionary &dict)
Select from dictionary.
Protected Attributes inherited from joint
List< spatialVector > S_
Joint motion sub-space.
label index_
Index of this joint in the rigidBodyModel.
label qIndex_
Index of this joints data in the rigidBodyModel state.
Detailed Description
Revolute joint for rotation about the x-axis.
Reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
    Chapter 4.
Source files
Rx.H
Rx.C
Definition at line 60 of file Rx.H.
Constructor & Destructor Documentation
Rx() [1/2]
Rx ()
Construct for given model.
Definition at line 53 of file Rx.C.
References joint::S_.
Referenced by Rx::clone().
Rx() [2/2]
Rx (const dictionary & dict)
Construct for given model from dictionary.
Definition at line 61 of file Rx.C.
References joint::S_.
~Rx()
~Rx () virtual
Destructor.
Definition at line 77 of file Rx.C.
References Rx::jcalc().
Member Function Documentation
TypeName()
TypeName ("Rx")
Runtime type information.
clone()
Foam::autoPtr< Foam::RBD::joint > clone () const virtual
Clone this joint.
Implements joint.
Definition at line 69 of file Rx.C.
References Rx::Rx().
jcalc()
void jcalc (joint::XSvc & J, const scalarField & q, const scalarField & qDot) const virtual
Update the model state for this joint.
Implements joint.
Definition at line 84 of file Rx.C.
References joint::XSvc::c, joint::qIndex_, joint::XSvc::S1, joint::S_, joint::XSvc::v, SpatialVector< Cmpt >::wx(), joint::XSvc::X, Foam::Xrx(), and Foam::Zero.
Referenced by Rx::~Rx().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/joints/Rx/Rx.H
src/rigidBodyDynamics/joints/Rx/Rx.C