OpenFOAM: rigidBodyModel Class Reference
rigidBodyModel Class Reference
Basic rigid-body model representing a system of rigid-bodies connected by 1-6 DoF joints.
Public Member Functions
TypeName ("rigidBodyModel")
Runtime type information.
rigidBodyModel ()
Null-constructor which adds the single root-body at the origin.
rigidBodyModel (const dictionary &dict)
Construct from dictionary.
virtual ~rigidBodyModel ()
Destructor.
label nBodies () const
Return the number of bodies in the model (bodies().size())
PtrList< rigidBody > bodies () const
Return the list of the bodies in the model.
const DynamicList< label > & lambda () const
List of indices of the parent of each body.
const PtrList< joint > & joints () const
Return the list of joints in the model.
label nDoF () const
Return the number of degrees of freedom of the model.
bool unitQuaternions () const
Return true if any of the joints using quaternions.
const vector & g () const
Return the acceleration due to gravity.
vector & g ()
Allow the acceleration due to gravity to be set.
const word & name (const label bodyID) const
Return the name of body with the given ID.
const rigidBodyInertia & I (const label i) const
Return the inertia of body i.
const spatialVector & v (const label i) const
Return the spatial velocity of the bodies.
virtual label join (const label parentID, const spatialTransform &XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
label join (const label parentID, const spatialTransform &XT, autoPtr< joints::composite > cJoint, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
label merge (const label parentID, const spatialTransform &X, autoPtr< rigidBody > bodyPtr)
Merge the given body with transform X into the parent with ID.
bool merged (label bodyID) const
Return true if the body with given ID has been merged with a parent.
label master (label bodyID) const
Return the ID of the master body for a sub-body otherwise.
label mergedBodyIndex (const label mergedBodyID) const
Return the index of the merged body in the mergedBody list.
label mergedBodyID (const label mergedBodyIndex) const
Return the merged body ID for the given merged body index.
const subBody & mergedBody (label mergedBodyID) const
Return the merged body for the given body ID.
label bodyID (const word &name) const
Return the ID of the body with the given name.
spatialTransform X0 (const label bodyId) const
Return the current transform to the global frame for the given body.
vector masterPoint (const label bodyID, const vector &p) const
spatialVector v (const label bodyID, const vector &p) const
Return the velocity of the given point on the given body.
void applyRestraints (scalarField &tau, Field< spatialVector > &fx) const
Apply the restraints and accumulate the internal joint forces.
void forwardDynamics (rigidBodyModelState &state, const scalarField &tau, const Field< spatialVector > &fx) const
Calculate the joint acceleration qDdot from the joint state q,.
void forwardDynamicsCorrection (const rigidBodyModelState &state) const
Correct the velocity and acceleration of the bodies in the model.
virtual void write (Ostream &) const
Write.
bool read (const dictionary &dict)
Read coefficients dictionary and update system parameters,.
Protected Member Functions
virtual label join_ (const label parentID, const spatialTransform &XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
Protected Attributes
PtrList< rigidBody > bodies_
List of the bodies.
PtrList< subBody > mergedBodies_
Bodies may be merged into existing bodies, the inertia of which is.
HashTable< label, word > bodyIDs_
Lookup-table of the IDs of the bodies.
DynamicList< label > lambda_
List of indices of the parent of each body.
PtrList< joint > joints_
Each body it attached with a joint which are held on this list.
DynamicList< spatialTransform > XT_
Transform from the parent body frame to the joint frame.
label nDoF_
The number of degrees of freedom of the model.
bool unitQuaternions_
True if any of the joints using quaternions.
PtrList< restraint > restraints_
Motion restraints.
vector g_
Acceleration due to gravity.
DynamicList< spatialTransform > Xlambda_
Transform from the parent body to the current body.
DynamicList< spatialTransform > X0_
Transform for external forces to the bodies reference frame.
DynamicList< spatialVector > v_
The spatial velocity of the bodies.
DynamicList< spatialVector > a_
The spatial acceleration of the bodies.
DynamicList< spatialVector > c_
The velocity dependent spatial acceleration of the joints.
DynamicList< spatialTensor > IA_
Velocity-product acceleration.
DynamicList< spatialVector > pA_
Articulated body bias force.
DynamicList< compactSpatialTensor > S_
Motion subspace for joints with 3 degrees of freedom.
DynamicList< spatialVector > S1_
Motion subspace for joints with 1 degrees of freedom.
DynamicList< compactSpatialTensor > U_
Sub-expression IA.S in the forward-dynamics algorithm.
DynamicList< spatialVector > U1_
Sub-expression IA.S1 in the forward-dynamics algorithm.
DynamicList< tensor > Dinv_
Sub-expression (S^T.U)^-1 in the forward-dynamics algorithm.
DynamicList< vector > u_
Sub-expression tau - S^T.pA in the forward-dynamics algorithm.
Friends
Ostream & operator<< (Ostream &, const rigidBodyModel &)
Detailed Description
Basic rigid-body model representing a system of rigid-bodies connected by 1-6 DoF joints.
This class holds various body and joint state fields needed by the kinematics and forward-dynamics algorithms presented in
reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
    Chapter 4.
Source files
rigidBodyModel.H
rigidBodyModel.C
kinematics.C
forwardDynamics.C
Definition at line 76 of file rigidBodyModel.H.
Constructor & Destructor Documentation
rigidBodyModel() [1/2]
rigidBodyModel ()
Null-constructor which adds the single root-body at the origin.
Definition at line 119 of file rigidBodyModel.C.
rigidBodyModel() [2/2]
rigidBodyModel (const dictionary & dict)
Construct from dictionary.
Definition at line 127 of file rigidBodyModel.C.
References rigidBodyModel::bodyID(), forAllConstIter(), dictionary::found(), rigidBodyModel::join(), dictionary::lookup(), rigidBodyModel::merge(), rigidBody::New(), joint::New(), rigidBodyModel::read(), and dictionary::subDict().
~rigidBodyModel()
~rigidBodyModel () virtual
Destructor.
Definition at line 167 of file rigidBodyModel.C.
References rigidBodyModel::join_().
Member Function Documentation
join_()
Foam::label join_ (const label parentID, const spatialTransform & XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr) protected virtual
Join the given body to the parent with ID parentID via the given.
joint with transform from the parent frame to the joint frame XT.
Definition at line 174 of file rigidBodyModel.C.
References PtrList< T >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), rigidBodyModel::bodies_, rigidBodyModel::bodyID(), rigidBodyModel::bodyIDs_, rigidBodyModel::join(), rigidBodyModel::joints_, rigidBodyModel::lambda_, subBody::masterID(), subBody::masterXT(), rigidBodyModel::merged(), rigidBodyModel::mergedBody(), rigidBody::name(), rigidBodyModel::nBodies(), joint::nDoF(), rigidBodyModel::nDoF_, UPtrList< T >::size(), joint::unitQuaternion(), rigidBodyModel::unitQuaternions_, and rigidBodyModel::XT_.
Referenced by rigidBodyModel::join(), and rigidBodyModel::~rigidBodyModel().
TypeName()
TypeName ("rigidBodyModel")
Runtime type information.
nBodies()
Foam::label nBodies () const inline
Return the number of bodies in the model (bodies().size())
Definition at line 28 of file rigidBodyModelI.H.
References rigidBodyModel::bodies_.
Referenced by rigidBodyModel::join_(), rigidBodyMeshMotionSolver::solve(), and rigidBodyModel::write().
bodies()
Foam::PtrList< Foam::RBD::rigidBody > bodies () const inline
Return the list of the bodies in the model.
Definition at line 35 of file rigidBodyModelI.H.
References rigidBodyModel::bodies_.
lambda()
const Foam::DynamicList< Foam::label > & lambda () const inline
List of indices of the parent of each body.
Definition at line 42 of file rigidBodyModelI.H.
References rigidBodyModel::lambda_.
Referenced by rigidBodyMotion::transformPoints().
joints()
const Foam::PtrList< Foam::RBD::joint > & joints () const inline
Return the list of joints in the model.
Definition at line 49 of file rigidBodyModelI.H.
References rigidBodyModel::joints_.
Referenced by rigidBodySolver::correctQuaternionJoints().
nDoF()
Foam::label nDoF () const inline
Return the number of degrees of freedom of the model.
used to set the size of the of joint state fields q, qDot and qDdot.
Definition at line 55 of file rigidBodyModelI.H.
References rigidBodyModel::nDoF_.
Referenced by rigidBodyMeshMotionSolver::solve().
unitQuaternions()
bool unitQuaternions () const inline
Return true if any of the joints using quaternions.
Definition at line 61 of file rigidBodyModelI.H.
References rigidBodyModel::unitQuaternions_.
Referenced by rigidBodySolver::correctQuaternionJoints().
g() [1/2]
const Foam::vector & g () const inline
Return the acceleration due to gravity.
Definition at line 67 of file rigidBodyModelI.H.
References rigidBodyModel::g_.
Referenced by rigidBodyMotion::rigidBodyMotion(), and rigidBodyMeshMotionSolver::solve().
g() [2/2]
Foam::vector & g () inline
Allow the acceleration due to gravity to be set.
after model construction
Definition at line 73 of file rigidBodyModelI.H.
References rigidBodyModel::g_, and rigidBodyModel::name().
name()
const Foam::word & name (const label bodyID) const inline
Return the name of body with the given ID.
Definition at line 80 of file rigidBodyModelI.H.
References rigidBodyModel::bodies_, rigidBodyModel::bodyID(), rigidBodyModel::merged(), rigidBodyModel::mergedBody(), and subBody::name().
Referenced by rigidBodyModel::bodyID(), rigidBodyModel::g(), rigidBodyModel::merge(), and rigidBodyMotion::status().
I()
const Foam::RBD::rigidBodyInertia & I (const label i) const inline
Return the inertia of body i.
Definition at line 96 of file rigidBodyModelI.H.
References rigidBodyModel::bodies_.
v() [1/2]
const Foam::spatialVector & v (const label i) const inline
Return the spatial velocity of the bodies.
Definition at line 103 of file rigidBodyModelI.H.
References rigidBodyModel::v_.
Referenced by rigidBodyModel::masterPoint(), and rigidBodyMotion::status().
join() [1/2]
Foam::label join (const label parentID, const spatialTransform & XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr) virtual
Join the given body to the parent with ID parentID via the given.
joint with transform from the parent frame to the joint frame XT.
Definition at line 219 of file rigidBodyModel.C.
References rigidBodyModel::join_(), and autoPtr< T >::ptr().
Referenced by rigidBodyModel::join_(), and rigidBodyModel::rigidBodyModel().
join() [2/2]
Foam::label join (const label parentID, const spatialTransform & XT, autoPtr< joints::composite > cJoint, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
composite joint (specified as a list of co-located joints) with transform from the parent frame to the joint frame XT. Composite joins are useful to represent complex joints with degrees of freedom other than 1 or 3 which are directly supported.
Definition at line 253 of file rigidBodyModel.C.
References rigidBodyModel::bodies_, rigidBodyModel::bodyID(), rigidBodyModel::join_(), rigidBodyModel::merge(), autoPtr< T >::ptr(), and UPtrList< T >::size().
merge()
Foam::label merge (const label parentID, const spatialTransform & X, autoPtr< rigidBody > bodyPtr)
Merge the given body with transform X into the parent with ID.
parentID. The parent body assumes the properties of the combined body (inertia etc.) and the merged body is held on a separate list for reference.
Definition at line 311 of file rigidBodyModel.C.
References rigidBodyModel::bodies_, rigidBodyModel::bodyIDs_, subBody::masterID(), subBody::masterXT(), rigidBodyModel::merged(), rigidBodyModel::mergedBodies_, rigidBodyModel::mergedBody(), rigidBodyModel::mergedBodyID(), subBody::name(), rigidBodyModel::name(), autoPtr< T >::set(), and rigidBodyModel::X0().
Referenced by rigidBodyModel::join(), and rigidBodyModel::rigidBodyModel().
merged()
bool merged (label bodyID) const inline
Return true if the body with given ID has been merged with a parent.
Definition at line 109 of file rigidBodyModelI.H.
Referenced by rigidBodyModel::join_(), rigidBodyModel::masterPoint(), rigidBodyModel::merge(), rigidBodyModel::mergedBody(), rigidBodyModel::name(), rigidBodyModel::X0(), and rigidBodyMotion::X00().
master()
Foam::label master (label bodyID) const inline
Return the ID of the master body for a sub-body otherwise.
return the given body ID
Definition at line 115 of file rigidBodyModelI.H.
References rigidBodyModel::bodyID(), subBody::masterID(), and rigidBodyModel::mergedBody().
Referenced by rigidBodyModel::v().
mergedBodyIndex()
Foam::label mergedBodyIndex (const label mergedBodyID) const inline
Return the index of the merged body in the mergedBody list.
from the given body ID
Definition at line 136 of file rigidBodyModelI.H.
References rigidBodyModel::mergedBodyID().
Referenced by rigidBodyModel::mergedBody(), and rigidBodyModel::mergedBodyID().
mergedBodyID()
Foam::label mergedBodyID (const label mergedBodyIndex) const inline
Return the merged body ID for the given merged body index.
in the mergedBody list
Definition at line 129 of file rigidBodyModelI.H.
References rigidBodyModel::mergedBodyIndex().
Referenced by rigidBodyModel::merge(), and rigidBodyModel::mergedBodyIndex().
mergedBody()
const Foam::RBD::subBody & mergedBody (label mergedBodyID) const inline
Return the merged body for the given body ID.
Definition at line 143 of file rigidBodyModelI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, rigidBodyModel::merged(), rigidBodyModel::mergedBodies_, and rigidBodyModel::mergedBodyIndex().
Referenced by rigidBodyModel::join_(), rigidBodyModel::master(), rigidBodyModel::masterPoint(), rigidBodyModel::merge(), rigidBodyModel::name(), rigidBodyModel::X0(), and rigidBodyMotion::X00().
bodyID()
Foam::label bodyID (const word & name) const inline
Return the ID of the body with the given name.
Definition at line 156 of file rigidBodyModelI.H.
References rigidBodyModel::bodyIDs_, rigidBodyModel::masterPoint(), and rigidBodyModel::name().
Referenced by rigidBodyModel::join(), rigidBodyModel::join_(), rigidBodyModel::master(), rigidBodyModel::name(), rigidBodyMeshMotionSolver::rigidBodyMeshMotionSolver(), and rigidBodyModel::rigidBodyModel().
X0()
Foam::spatialTransform X0 (const label bodyId) const
Return the current transform to the global frame for the given body.
Definition at line 369 of file rigidBodyModel.C.
References subBody::masterID(), subBody::masterXT(), rigidBodyModel::merged(), rigidBodyModel::mergedBody(), and rigidBodyModel::X0_.
Referenced by rigidBodyModel::merge(), rigidBodyMotion::status(), and rigidBodyMotion::transformPoints().
masterPoint()
Foam::vector masterPoint (const label bodyID, const vector & p) const inline
Definition at line 163 of file rigidBodyModelI.H.
References Foam::inv(), rigidBodyModel::merged(), rigidBodyModel::mergedBody(), p, rigidBodyModel::v(), and Foam::Zero.
Referenced by rigidBodyModel::bodyID(), and rigidBodyModel::v().
v() [2/2]
Foam::spatialVector v (const label bodyID, const vector & p) const inline
Return the velocity of the given point on the given body.
Definition at line 184 of file rigidBodyModelI.H.
References rigidBodyModel::master(), rigidBodyModel::masterPoint(), Foam::T(), rigidBodyModel::v_, and rigidBodyModel::X0_.
applyRestraints()
void applyRestraints (scalarField & tau, Field< spatialVector > & fx) const
Apply the restraints and accumulate the internal joint forces.
into the tau field and external forces into the fx field
Definition at line 33 of file forwardDynamics.C.
References DebugInfo, forAll, and rigidBodyModel::forwardDynamics().
forwardDynamics()
void forwardDynamics (rigidBodyModelState & state, const scalarField & tau, const Field< spatialVector > & fx) const
Calculate the joint acceleration qDdot from the joint state q,.
velocity qDot, internal force tau (in the joint frame) and external force fx (in the global frame) using the articulated body algorithm (Section 7.3 and Table 7.1)
Definition at line 54 of file forwardDynamics.C.
References Field< Type >::block(), joint::XSvc::c, DebugInfo, DebugInFunction, Foam::endl(), rigidBodyModel::forwardDynamicsCorrection(), Foam::I, Foam::inv(), joint::jcalc(), joint::nDoF(), Foam::nl, rigidBodyModelState::q(), rigidBodyModelState::qDdot(), rigidBodyModelState::qDot(), joint::XSvc::S, joint::XSvc::S1, List< Type >::size(), T, joint::XSvc::v, x, Vector< Cmpt >::x(), joint::XSvc::X, Vector< Cmpt >::y(), Vector< Cmpt >::z(), and Foam::Zero.
Referenced by rigidBodyModel::applyRestraints(), and rigidBodyMotion::forwardDynamics().
forwardDynamicsCorrection()
void forwardDynamicsCorrection (const rigidBodyModelState & state) const
Correct the velocity and acceleration of the bodies in the model.
from the given joint state fields following an integration step of the forwardDynamics
Definition at line 207 of file forwardDynamics.C.
References Field< Type >::block(), joint::XSvc::c, DebugInfo, DebugInFunction, Foam::endl(), joint::jcalc(), joint::nDoF(), rigidBodyModelState::q(), rigidBodyModelState::qDdot(), rigidBodyModelState::qDot(), joint::XSvc::S, joint::XSvc::S1, joint::XSvc::v, joint::XSvc::X, and Foam::Zero.
Referenced by rigidBodyModel::forwardDynamics(), and rigidBodyMotion::solve().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in rigidBodyMotion.
Definition at line 385 of file rigidBodyModel.C.
References token::BEGIN_BLOCK, rigidBodyModel::bodies_, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), forAll, Foam::incrIndent(), Foam::indent(), rigidBodyModel::joints_, rigidBodyModel::lambda_, rigidBodyModel::mergedBodies_, rigidBodyModel::nBodies(), Foam::nl, rigidBodyModel::restraints_, Ostream::writeKeyword(), and rigidBodyModel::XT_.
Referenced by Foam::RBD::operator<<(), and rigidBodyMotion::write().
read()
bool read (const dictionary & dict)
Read coefficients dictionary and update system parameters,.
restraints but not the current state
Definition at line 456 of file rigidBodyModel.C.
References rigidBodyModel::restraints_.
Referenced by rigidBodyMotion::read(), and rigidBodyModel::rigidBodyModel().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const rigidBodyModel &) friend
Member Data Documentation
bodies_
PtrList<rigidBody> bodies_ protected
List of the bodies.
The 0'th body represents the fixed origin and is constructed automatically. The subsequent (moving) bodies are appended by the join member function.
Definition at line 101 of file rigidBodyModel.H.
Referenced by rigidBodyModel::bodies(), rigidBodyModel::I(), rigidBodyModel::join(), rigidBodyModel::join_(), rigidBodyModel::merge(), rigidBodyModel::name(), rigidBodyModel::nBodies(), and rigidBodyModel::write().
mergedBodies_
PtrList<subBody> mergedBodies_ protected
Bodies may be merged into existing bodies, the inertia of which is.
updated to represent the combined body which is more efficient than attaching them with fixed joints. These 'merged' bodies are held on this list.
Definition at line 107 of file rigidBodyModel.H.
Referenced by rigidBodyModel::merge(), rigidBodyModel::mergedBody(), and rigidBodyModel::write().
bodyIDs_
HashTable<label, word> bodyIDs_ protected
Lookup-table of the IDs of the bodies.
Definition at line 110 of file rigidBodyModel.H.
Referenced by rigidBodyModel::bodyID(), rigidBodyModel::join_(), and rigidBodyModel::merge().
lambda_
DynamicList<label> lambda_ protected
List of indices of the parent of each body.
Definition at line 113 of file rigidBodyModel.H.
Referenced by rigidBodyModel::join_(), rigidBodyModel::lambda(), and rigidBodyModel::write().
joints_
PtrList<joint> joints_ protected
Each body it attached with a joint which are held on this list.
Definition at line 116 of file rigidBodyModel.H.
Referenced by rigidBodyModel::join_(), rigidBodyModel::joints(), and rigidBodyModel::write().
XT_
DynamicList<spatialTransform> XT_ protected
Transform from the parent body frame to the joint frame.
Definition at line 119 of file rigidBodyModel.H.
Referenced by rigidBodyModel::join_(), and rigidBodyModel::write().
nDoF_
label nDoF_ protected
The number of degrees of freedom of the model.
used to set the size of the of joint state fields q, qDot and qDdot.
Definition at line 123 of file rigidBodyModel.H.
Referenced by rigidBodyModel::join_(), and rigidBodyModel::nDoF().
unitQuaternions_
bool unitQuaternions_ protected
True if any of the joints using quaternions.
Definition at line 126 of file rigidBodyModel.H.
Referenced by rigidBodyModel::join_(), and rigidBodyModel::unitQuaternions().
restraints_
PtrList<restraint> restraints_ protected
Motion restraints.
Definition at line 129 of file rigidBodyModel.H.
Referenced by rigidBodyModel::read(), and rigidBodyModel::write().
g_
vector g_ protected
Acceleration due to gravity.
Definition at line 135 of file rigidBodyModel.H.
Referenced by rigidBodyModel::g().
Xlambda_
DynamicList<spatialTransform> Xlambda_ mutable protected
Transform from the parent body to the current body.
Definition at line 141 of file rigidBodyModel.H.
X0_
DynamicList<spatialTransform> X0_ mutable protected
Transform for external forces to the bodies reference frame.
Definition at line 144 of file rigidBodyModel.H.
Referenced by rigidBodyModel::v(), and rigidBodyModel::X0().
v_
DynamicList<spatialVector> v_ mutable protected
The spatial velocity of the bodies.
Definition at line 150 of file rigidBodyModel.H.
Referenced by rigidBodyModel::v().
a_
DynamicList<spatialVector> a_ mutable protected
The spatial acceleration of the bodies.
Definition at line 153 of file rigidBodyModel.H.
c_
DynamicList<spatialVector> c_ mutable protected
The velocity dependent spatial acceleration of the joints.
Definition at line 156 of file rigidBodyModel.H.
IA_
DynamicList<spatialTensor> IA_ mutable protected
Velocity-product acceleration.
Articulated body inertia
Definition at line 164 of file rigidBodyModel.H.
pA_
DynamicList<spatialVector> pA_ mutable protected
Articulated body bias force.
Definition at line 167 of file rigidBodyModel.H.
S_
DynamicList<compactSpatialTensor> S_ mutable protected
Motion subspace for joints with 3 degrees of freedom.
Definition at line 173 of file rigidBodyModel.H.
S1_
DynamicList<spatialVector> S1_ mutable protected
Motion subspace for joints with 1 degrees of freedom.
Definition at line 176 of file rigidBodyModel.H.
U_
DynamicList<compactSpatialTensor> U_ mutable protected
Sub-expression IA.S in the forward-dynamics algorithm.
Definition at line 179 of file rigidBodyModel.H.
U1_
DynamicList<spatialVector> U1_ mutable protected
Sub-expression IA.S1 in the forward-dynamics algorithm.
Definition at line 182 of file rigidBodyModel.H.
Dinv_
DynamicList<tensor> Dinv_ mutable protected
Sub-expression (S^T.U)^-1 in the forward-dynamics algorithm.
Definition at line 185 of file rigidBodyModel.H.
u_
DynamicList<vector> u_ mutable protected
Sub-expression tau - S^T.pA in the forward-dynamics algorithm.
Definition at line 188 of file rigidBodyModel.H.
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodyModel/rigidBodyModel.H
src/rigidBodyDynamics/rigidBodyModel/forwardDynamics.C
src/rigidBodyDynamics/rigidBodyModel/rigidBodyModel.C
src/rigidBodyDynamics/rigidBodyModel/rigidBodyModelI.H