OpenFOAM: sphericalAngularDamper Class Reference
sphericalAngularDamper Class Reference
Spherical angular damper restraint. Operates in the local frame of the body.
Public Member Functions
TypeName ("sphericalAngularDamper")
Runtime type information.
sphericalAngularDamper (const word &name, const dictionary &dict, const rigidBodyModel &model)
Construct from components.
virtual autoPtr< restraint > clone () const
Construct and return a clone.
virtual ~sphericalAngularDamper ()
Destructor.
virtual void restrain (scalarField &tau, Field< spatialVector > &fx) const
Accumulate the retraint internal joint forces into the tau field and.
virtual bool read (const dictionary &dict)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from restraint
TypeName ("restraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, restraint, dictionary,(const word &name, const dictionary &dict, const rigidBodyModel &model),(name, dict, model))
restraint (const word &name, const dictionary &dict, const rigidBodyModel &model)
Construct from the dict dictionary and Time.
virtual ~restraint ()
Destructor.
const word & name () const
Return the name.
label bodyID () const
const dictionary & coeffDict () const
Return access to coeffs.
Additional Inherited Members
Static Public Member Functions inherited from restraint
static autoPtr< restraint > New (const word &name, const dictionary &dict, const rigidBodyModel &model)
Select constructed from the dict dictionary and Time.
Protected Member Functions inherited from restraint
point bodyPoint (const point &p) const
Transform the given point on the restrained body to the global frame.
spatialVector bodyPointVelocity (const point &p) const
Transform the velocity of the given point on the restrained body.
Protected Attributes inherited from restraint
word name_
Name of the restraint.
label bodyID_
ID of the body the restraint is applied to.
label bodyIndex_
Index of the body the force is applied to.
dictionary coeffs_
Restraint model specific coefficient dictionary.
const rigidBodyModel & model_
Reference to the model.
Detailed Description
Spherical angular damper restraint. Operates in the local frame of the body.
Source files
sphericalAngularDamper.H
sphericalAngularDamper.C
Definition at line 53 of file sphericalAngularDamper.H.
Constructor & Destructor Documentation
sphericalAngularDamper()
sphericalAngularDamper (const word & name, const dictionary & dict, const rigidBodyModel & model)
Construct from components.
Definition at line 54 of file sphericalAngularDamper.C.
References Foam::read().
Referenced by sphericalAngularDamper::clone().
~sphericalAngularDamper()
~sphericalAngularDamper () virtual
Destructor.
Definition at line 68 of file sphericalAngularDamper.C.
References sphericalAngularDamper::restrain().
Referenced by sphericalAngularDamper::clone().
Member Function Documentation
TypeName()
TypeName ("sphericalAngularDamper")
Runtime type information.
clone()
virtual autoPtr<restraint> clone () const inline virtual
Construct and return a clone.
Implements restraint.
Definition at line 80 of file sphericalAngularDamper.H.
References sphericalAngularDamper::read(), sphericalAngularDamper::restrain(), sphericalAngularDamper::sphericalAngularDamper(), sphericalAngularDamper::write(), and sphericalAngularDamper::~sphericalAngularDamper().
restrain()
void restrain (scalarField & tau, Field< spatialVector > & fx) const virtual
Accumulate the retraint internal joint forces into the tau field and.
external forces into the fx field
Implements restraint.
Definition at line 75 of file sphericalAngularDamper.C.
References Foam::endl(), Foam::Info, sphericalAngularDamper::read(), and Foam::Zero.
Referenced by sphericalAngularDamper::clone(), and sphericalAngularDamper::~sphericalAngularDamper().
read()
bool read (const dictionary & dict) virtual
Update properties from given dictionary.
Reimplemented from restraint.
Definition at line 93 of file sphericalAngularDamper.C.
References restraint::read(), and sphericalAngularDamper::write().
Referenced by sphericalAngularDamper::clone(), and sphericalAngularDamper::restrain().
write()
void write (Ostream & os) const virtual
Write.
Implements restraint.
Definition at line 106 of file sphericalAngularDamper.C.
References token::END_STATEMENT, Foam::nl, restraint::write(), and Ostream::writeKeyword().
Referenced by sphericalAngularDamper::clone(), and sphericalAngularDamper::read().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/restraints/sphericalAngularDamper/sphericalAngularDamper.H
src/rigidBodyDynamics/restraints/sphericalAngularDamper/sphericalAngularDamper.C