OpenFOAM: distributedWeightedFvPatchFieldMapper Class Reference
distributedWeightedFvPatchFieldMapper Class Reference
FieldMapper with weighted mapping from (optionally remote) quantities.
Public Member Functions
distributedWeightedFvPatchFieldMapper (const label singlePatchProc, const mapDistributeBase *distMapPtr, const labelListList &addressing, const scalarListList &weights)
Construct given addressing.
virtual ~distributedWeightedFvPatchFieldMapper ()
Destructor.
virtual label size () const
virtual bool direct () const
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
virtual bool hasUnmapped () const
Are there unmapped values? I.e. do all size() elements get.
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
Public Member Functions inherited from fvPatchFieldMapper
fvPatchFieldMapper ()
Null constructor.
Public Member Functions inherited from FieldMapper
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()
Destructor.
virtual const labelUList & directAddressing () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
FieldMapper with weighted mapping from (optionally remote) quantities.
Definition at line 46 of file distributedWeightedFvPatchFieldMapper.H.
Constructor & Destructor Documentation
distributedWeightedFvPatchFieldMapper()
distributedWeightedFvPatchFieldMapper (const label singlePatchProc, const mapDistributeBase * distMapPtr, const labelListList & addressing, const scalarListList & weights) inline
Construct given addressing.
Definition at line 66 of file distributedWeightedFvPatchFieldMapper.H.
References Foam::exit(), Foam::FatalError, FatalErrorIn, forAll, and distributedWeightedFvPatchFieldMapper::size().
~distributedWeightedFvPatchFieldMapper()
virtual ~distributedWeightedFvPatchFieldMapper () inline virtual
Destructor.
Definition at line 102 of file distributedWeightedFvPatchFieldMapper.H.
Member Function Documentation
size()
virtual label size () const inline virtual
Implements FieldMapper.
Definition at line 108 of file distributedWeightedFvPatchFieldMapper.H.
References distributedWeightedFvPatchFieldMapper::addressing(), mapDistributeBase::constructSize(), distributedWeightedFvPatchFieldMapper::distributed(), distributedWeightedFvPatchFieldMapper::distributeMap(), and List< T >::size().
Referenced by distributedWeightedFvPatchFieldMapper::distributedWeightedFvPatchFieldMapper().
direct()
virtual bool direct () const inline virtual
Implements FieldMapper.
Definition at line 120 of file distributedWeightedFvPatchFieldMapper.H.
distributed()
virtual bool distributed () const inline virtual
Reimplemented from FieldMapper.
Definition at line 125 of file distributedWeightedFvPatchFieldMapper.H.
Referenced by distributedWeightedFvPatchFieldMapper::size().
distributeMap()
virtual const mapDistributeBase& distributeMap () const inline virtual
Reimplemented from FieldMapper.
Definition at line 130 of file distributedWeightedFvPatchFieldMapper.H.
References Foam::exit(), Foam::FatalError, and FatalErrorIn.
Referenced by distributedWeightedFvPatchFieldMapper::size().
hasUnmapped()
virtual bool hasUnmapped () const inline virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implements FieldMapper.
Definition at line 144 of file distributedWeightedFvPatchFieldMapper.H.
addressing()
virtual const labelListList& addressing () const inline virtual
Reimplemented from FieldMapper.
Definition at line 149 of file distributedWeightedFvPatchFieldMapper.H.
Referenced by distributedWeightedFvPatchFieldMapper::size().
weights()
virtual const scalarListList& weights () const inline virtual
Reimplemented from FieldMapper.
Definition at line 154 of file distributedWeightedFvPatchFieldMapper.H.
The documentation for this class was generated from the following file:
src/sampling/meshToMesh/distributedWeightedFvPatchFieldMapper.H