OpenFOAM: meshToMesh0 Class Reference
meshToMesh0 Class Reference
mesh to mesh interpolation class.
Classes
class patchFieldInterpolator
Patch-field interpolation class.
Public Types
enum order { MAP, INTERPOLATE, CELL_POINT_INTERPOLATE, CELL_VOLUME_WEIGHT }
Enumeration specifying required accuracy.
Public Member Functions
ClassName ("meshToMesh0")
meshToMesh0 (const fvMesh &fromMesh, const fvMesh &toMesh, const HashTable< word > &patchMap, const wordList &cuttingPatchNames)
Construct from the two meshes, the patch name map for the patches.
meshToMesh0 (const fvMesh &fromMesh, const fvMesh &toMesh)
Construct from the two meshes assuming there is an exact mapping.
~meshToMesh0 ()
Destructor.
const fvMesh & fromMesh () const
const fvMesh & toMesh () const
const labelList & cellAddressing () const
From toMesh cells to fromMesh cells.
scalar V () const
Overlap volume.
template<class Type , class CombineOp >
void mapField (Field< Type > &, const Field< Type > &, const labelList &adr, const CombineOp &cop) const
Map field.
template<class Type , class CombineOp >
void interpolateField (Field< Type > &, const GeometricField< Type, fvPatchField, volMesh > &, const labelList &adr, const scalarListList &weights, const CombineOp &cop) const
Interpolate field using inverse-distance weights.
template<class Type , class CombineOp >
void interpolateField (Field< Type > &, const GeometricField< Type, fvPatchField, volMesh > &, const labelListList &adr, const scalarListList &weights, const CombineOp &cop) const
Interpolate field using inverse-volume weights.
template<class Type , class CombineOp >
void interpolateField (Field< Type > &, const GeometricField< Type, fvPatchField, volMesh > &, const labelList &adr, const vectorField &centres, const CombineOp &cop) const
Interpolate field using cell-point interpolation.
template<class Type , class CombineOp >
void interpolateInternalField (Field< Type > &, const GeometricField< Type, fvPatchField, volMesh > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
Interpolate internal volume field.
template<class Type , class CombineOp >
void interpolateInternalField (Field< Type > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
void interpolate (GeometricField< Type, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
Interpolate volume field.
template<class Type , class CombineOp >
void interpolate (GeometricField< Type, fvPatchField, volMesh > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
Interpolate volume field.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &fromVf, meshToMesh0::order ord, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfromVf, meshToMesh0::order ord, const CombineOp &cop) const
Detailed Description
mesh to mesh interpolation class.
Note
This class is due to be deprecated in favour of meshToMesh0New
Source files
meshToMesh0.H
meshToMesh0.C
calculateMeshToMesh0Addressing.C
calculateMeshToMesh0Weights.C
meshToMesh0Templates.C
Definition at line 63 of file meshToMesh0.H.
Member Enumeration Documentation
order
enum order
Enumeration specifying required accuracy.
Enumerator
MAP
INTERPOLATE
CELL_POINT_INTERPOLATE
CELL_VOLUME_WEIGHT
Definition at line 142 of file meshToMesh0.H.
Constructor & Destructor Documentation
meshToMesh0() [1/2]
meshToMesh0 (const fvMesh & fromMesh, const fvMesh & toMesh, const HashTable< word > & patchMap, const wordList & cuttingPatchNames)
Construct from the two meshes, the patch name map for the patches.
to be interpolated and the names of the toMesh-patches which cut the fromMesh
Definition at line 43 of file meshToMesh0.C.
References Foam::endl(), forAll, patchi, and WarningInFunction.
meshToMesh0() [2/2]
meshToMesh0 (const fvMesh & fromMesh, const fvMesh & toMesh)
Construct from the two meshes assuming there is an exact mapping.
between the patches
Definition at line 114 of file meshToMesh0.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, and patchi.
~meshToMesh0()
~meshToMesh0 ()
Destructor.
Definition at line 194 of file meshToMesh0.C.
References Foam::deleteDemandDrivenData().
Member Function Documentation
ClassName()
ClassName ("meshToMesh0")
fromMesh()
const fvMesh& fromMesh () const inline
Definition at line 229 of file meshToMesh0.H.
Referenced by Foam::MapConsistentVolFields(), and Foam::MapVolFields().
toMesh()
const fvMesh& toMesh () const inline
Definition at line 234 of file meshToMesh0.H.
Referenced by Foam::MapConsistentVolFields(), Foam::MapLagrangianFields(), and Foam::MapVolFields().
cellAddressing()
const labelList& cellAddressing () const inline
From toMesh cells to fromMesh cells.
Definition at line 240 of file meshToMesh0.H.
V()
scalar V () const inline
Overlap volume.
Definition at line 246 of file meshToMesh0.H.
References meshToMesh0::INTERPOLATE, meshToMesh0::interpolate(), meshToMesh0::interpolateField(), meshToMesh0::interpolateInternalField(), meshToMesh0::mapField(), and FieldMapper::weights().
mapField()
void mapField (Field< Type > & toF, const Field< Type > & fromVf, const labelList & adr, const CombineOp & cop) const
Map field.
Definition at line 36 of file meshToMesh0Templates.C.
References forAll, and meshToMesh0::interpolateField().
Referenced by meshToMesh0::V().
interpolateField() [1/3]
void interpolateField (Field< Type > & toF, const GeometricField< Type, fvPatchField, volMesh > & fromVf, const labelList & adr, const scalarListList & weights, const CombineOp & cop) const
Interpolate field using inverse-distance weights.
Definition at line 86 of file meshToMesh0Templates.C.
References f(), and forAll.
Referenced by meshToMesh0::interpolateField(), meshToMesh0::mapField(), and meshToMesh0::V().
interpolateField() [2/3]
void interpolateField (Field< Type > & toF, const GeometricField< Type, fvPatchField, volMesh > & fromVf, const labelListList & adr, const scalarListList & weights, const CombineOp & cop) const
Interpolate field using inverse-volume weights.
Definition at line 59 of file meshToMesh0Templates.C.
References f(), forAll, meshToMesh0::interpolateField(), and Foam::Zero.
interpolateField() [3/3]
void interpolateField (Field< Type > & toF, const GeometricField< Type, fvPatchField, volMesh > & fromVf, const labelList & adr, const vectorField & centres, const CombineOp & cop) const
Interpolate field using cell-point interpolation.
Definition at line 121 of file meshToMesh0Templates.C.
References forAll, interpolationCellPoint< Type >::interpolate(), and meshToMesh0::interpolateInternalField().
interpolateInternalField() [1/2]
void interpolateInternalField (Field< Type > & toF, const GeometricField< Type, fvPatchField, volMesh > & fromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Interpolate internal volume field.
Definition at line 152 of file meshToMesh0Templates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, DimensionedField< Type, GeoMesh >::mesh(), and List< Type >::size().
Referenced by meshToMesh0::interpolateField(), and meshToMesh0::V().
interpolateInternalField() [2/2]
void interpolateInternalField (Field< Type > & toF, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Definition at line 233 of file meshToMesh0Templates.C.
References meshToMesh0::interpolate().
interpolate() [1/6]
void interpolate (GeometricField< Type, fvPatchField, volMesh > & toVf, const GeometricField< Type, fvPatchField, volMesh > & fromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Interpolate volume field.
Definition at line 247 of file meshToMesh0Templates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), fvPatch::Cf(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::isA(), fvPatch::name(), and patchi.
Referenced by meshToMesh0::interpolate(), meshToMesh0::interpolateInternalField(), Foam::MapConsistentVolFields(), Foam::MapVolFields(), and meshToMesh0::V().
interpolate() [2/6]
void interpolate (GeometricField< Type, fvPatchField, volMesh > & toVf, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Definition at line 346 of file meshToMesh0Templates.C.
References Foam::MULES::interpolate(), and meshToMesh0::interpolate().
interpolate() [3/6]
tmp<GeometricField<Type, fvPatchField, volMesh> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & , order = INTERPOLATE, const CombineOp & cop = eqOp< Type >()) const
Interpolate volume field.
interpolate() [4/6]
tmp<GeometricField<Type, fvPatchField, volMesh> > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & , order = INTERPOLATE, const CombineOp & cop = eqOp< Type >()) const
interpolate() [5/6]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & fromVf, meshToMesh0::order ord, const CombineOp & cop) const
Definition at line 361 of file meshToMesh0Templates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, meshToMesh0::interpolate(), IOobject::name(), and patchi.
interpolate() [6/6]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfromVf, meshToMesh0::order ord, const CombineOp & cop) const
Definition at line 433 of file meshToMesh0Templates.C.
References Foam::MULES::interpolate().
The documentation for this class was generated from the following files:
src/sampling/meshToMesh0/meshToMesh0.H
src/sampling/meshToMesh0/calculateMeshToMesh0Addressing.C
src/sampling/meshToMesh0/calculateMeshToMesh0Weights.C
src/sampling/meshToMesh0/meshToMesh0.C
src/sampling/meshToMesh0/meshToMesh0Templates.C