OpenFOAM: meshToMesh Class Reference
meshToMesh Class Reference
Class to calculate the cell-addressing between two overlapping meshes.
Public Types
enum interpolationMethod { imDirect, imMapNearest, imCellVolumeWeight }
Enumeration specifying interpolation method.
Public Member Functions
TypeName ("meshToMesh")
Run-time type information.
meshToMesh (const polyMesh &src, const polyMesh &tgt, const interpolationMethod &method, const bool interpAllPatches=true)
Construct from source and target meshes.
meshToMesh (const polyMesh &src, const polyMesh &tgt, const word &methodName, const word &AMIMethodName, const bool interpAllPatches=true)
Construct from source and target meshes, generic mapping methods.
meshToMesh (const polyMesh &src, const polyMesh &tgt, const interpolationMethod &method, const HashTable< word > &patchMap, const wordList &cuttingPatches)
Construct from source and target meshes.
meshToMesh (const polyMesh &src, const polyMesh &tgt, const word &methodName, const word &AMIMethodName, const HashTable< word > &patchMap, const wordList &cuttingPatches)
Construct from source and target meshes, generic mapping methods.
virtual ~meshToMesh ()
Destructor.
const polyMesh & srcRegion () const
Return const access to the source mesh.
const polyMesh & tgtRegion () const
Return const access to the target mesh.
const labelListList & srcToTgtCellAddr () const
Return const access to the source to target cell addressing.
const labelListList & tgtToSrcCellAddr () const
Return const access to the target to source cell addressing.
const scalarListList & srcToTgtCellWght () const
Return const access to the source to target cell weights.
const scalarListList & tgtToSrcCellWght () const
Return const access to the target to source cell weights.
scalar V () const
Return const access to the overlap volume.
template<class Type , class CombineOp >
void mapSrcToTgt (const UList< Type > &srcFld, const CombineOp &cop, List< Type > &result) const
Map field from src to tgt mesh with defined operation.
template<class Type , class CombineOp >
tmp< Field< Type > > mapSrcToTgt (const Field< Type > &srcFld, const CombineOp &cop) const
Return the src field mapped to the tgt mesh with a defined.
template<class Type , class CombineOp >
tmp< Field< Type > > mapSrcToTgt (const tmp< Field< Type >> &tsrcFld, const CombineOp &cop) const
Convenience function to map a tmp field to the tgt mesh.
template<class Type >
tmp< Field< Type > > mapSrcToTgt (const Field< Type > &srcFld) const
Convenience function to map a field to the tgt mesh with a.
template<class Type >
tmp< Field< Type > > mapSrcToTgt (const tmp< Field< Type >> &tsrcFld) const
Convenience function to map a tmp field to the tgt mesh.
template<class Type , class CombineOp >
void mapTgtToSrc (const UList< Type > &tgtFld, const CombineOp &cop, List< Type > &result) const
Map field from tgt to src mesh with defined operation.
template<class Type , class CombineOp >
tmp< Field< Type > > mapTgtToSrc (const Field< Type > &tgtFld, const CombineOp &cop) const
Return the tgt field mapped to the src mesh with a defined.
template<class Type , class CombineOp >
tmp< Field< Type > > mapTgtToSrc (const tmp< Field< Type >> &ttgtFld, const CombineOp &cop) const
Convenience function to map a tmp field to the src mesh.
template<class Type >
tmp< Field< Type > > mapTgtToSrc (const Field< Type > &tgtFld) const
Convenience function to map a field to the src mesh with a.
template<class Type >
tmp< Field< Type > > mapTgtToSrc (const tmp< Field< Type >> &ttgtFld) const
Convenience function to map a tmp field to the src mesh.
template<class Type , class CombineOp >
void mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop, GeometricField< Type, fvPatchField, volMesh > &result) const
Interpolate a field with a defined operation. Values.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop) const
Interpolate a field with a defined operation. The initial.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfield, const CombineOp &cop) const
Interpolate a tmp field with a defined operation. The.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field) const
Convenience function to map a field with a default.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfield) const
Convenience function to map a tmp field with a default.
template<class Type , class CombineOp >
void mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop, GeometricField< Type, fvPatchField, volMesh > &result) const
Interpolate a field with a defined operation. Values.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop) const
Interpolate a field with a defined operation. The initial.
template<class Type , class CombineOp >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfield, const CombineOp &cop) const
Interpolate a tmp field with a defined operation. The.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field) const
Convenience function to map a field with a default.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfield) const
Convenience function to map a tmp field with a default.
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< scalar > &srcField, Field< scalar > &tgtField, const plusEqOp< scalar > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< vector > &srcField, Field< vector > &tgtField, const plusEqOp< vector > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< sphericalTensor > &srcField, Field< sphericalTensor > &tgtField, const plusEqOp< sphericalTensor > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< symmTensor > &srcField, Field< symmTensor > &tgtField, const plusEqOp< symmTensor > &cop) const
template<>
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation &AMI, const Field< tensor > &srcField, Field< tensor > &tgtField, const plusEqOp< tensor > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< scalar > &srcField, const Field< scalar > &tgtField, const plusEqOp< scalar > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< vector > &srcField, const Field< vector > &tgtField, const plusEqOp< vector > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< sphericalTensor > &srcField, const Field< sphericalTensor > &tgtField, const plusEqOp< sphericalTensor > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< symmTensor > &srcField, const Field< symmTensor > &tgtField, const plusEqOp< symmTensor > &cop) const
template<>
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation &AMI, Field< tensor > &srcField, const Field< tensor > &tgtField, const plusEqOp< tensor > &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const Field< Type > &srcField, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const tmp< Field< Type >> &tsrcField, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const Field< Type > &srcField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapSrcToTgt (const tmp< Field< Type >> &tsrcField) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const Field< Type > &tgtField, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const tmp< Field< Type >> &ttgtField, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const Field< Type > &tgtField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapTgtToSrc (const tmp< Field< Type >> &ttgtField) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfield, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfield) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfield, const CombineOp &cop) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfield) const
Static Public Member Functions
static AMIPatchToPatchInterpolation::interpolationMethod interpolationMethodAMI (const interpolationMethod method)
Conversion between mesh and patch interpolation methods.
Static Public Attributes
static const NamedEnum< interpolationMethod, 3 > interpolationMethodNames_
Detailed Description
Class to calculate the cell-addressing between two overlapping meshes.
Mapping is performed using a run-time selectable interpolation mothod
See also
meshToMeshMethod
Source files
meshToMesh.H
meshToMesh.C
meshToMeshParallelOps.C
meshToMeshTemplates.C
Definition at line 60 of file meshToMesh.H.
Member Enumeration Documentation
interpolationMethod
enum interpolationMethod
Enumeration specifying interpolation method.
Enumerator
imDirect
imMapNearest
imCellVolumeWeight
Definition at line 67 of file meshToMesh.H.
Constructor & Destructor Documentation
meshToMesh() [1/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const interpolationMethod & method, const bool interpAllPatches = true)
Construct from source and target meshes.
Definition at line 637 of file meshToMesh.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolationMethodToWord().
meshToMesh() [2/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const word & methodName, const word & AMIMethodName, const bool interpAllPatches = true)
Construct from source and target meshes, generic mapping methods.
Definition at line 672 of file meshToMesh.C.
meshToMesh() [3/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const interpolationMethod & method, const HashTable< word > & patchMap, const wordList & cuttingPatches)
Construct from source and target meshes.
Definition at line 700 of file meshToMesh.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolationMethodToWord().
meshToMesh() [4/4]
meshToMesh (const polyMesh & src, const polyMesh & tgt, const word & methodName, const word & AMIMethodName, const HashTable< word > & patchMap, const wordList & cuttingPatches)
Construct from source and target meshes, generic mapping methods.
Definition at line 737 of file meshToMesh.C.
~meshToMesh()
~meshToMesh () virtual
Destructor.
Definition at line 773 of file meshToMesh.C.
Member Function Documentation
TypeName()
TypeName ("meshToMesh")
Run-time type information.
srcRegion()
const Foam::polyMesh & srcRegion () const inline
Return const access to the source mesh.
Definition at line 30 of file meshToMeshI.H.
Referenced by Foam::MapMesh(), and Foam::MapVolFields().
tgtRegion()
const Foam::polyMesh & tgtRegion () const inline
Return const access to the target mesh.
Definition at line 36 of file meshToMeshI.H.
Referenced by Foam::MapMesh(), and Foam::MapVolFields().
srcToTgtCellAddr()
const Foam::labelListList & srcToTgtCellAddr () const inline
Return const access to the source to target cell addressing.
Definition at line 43 of file meshToMeshI.H.
tgtToSrcCellAddr()
const Foam::labelListList & tgtToSrcCellAddr () const inline
Return const access to the target to source cell addressing.
Definition at line 50 of file meshToMeshI.H.
srcToTgtCellWght()
const Foam::scalarListList & srcToTgtCellWght () const inline
Return const access to the source to target cell weights.
Definition at line 57 of file meshToMeshI.H.
tgtToSrcCellWght()
const Foam::scalarListList & tgtToSrcCellWght () const inline
Return const access to the target to source cell weights.
Definition at line 64 of file meshToMeshI.H.
V()
Foam::scalar V () const inline
Return const access to the overlap volume.
Definition at line 70 of file meshToMeshI.H.
interpolationMethodAMI()
Foam::AMIPatchToPatchInterpolation::interpolationMethod interpolationMethodAMI (const interpolationMethod method) static
Conversion between mesh and patch interpolation methods.
Definition at line 462 of file meshToMesh.C.
References Foam::abort(), PtrList< T >::append(), polyPatch::boundaryMesh(), Foam::decrIndent(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::findPatchID(), forAll, forAllConstIter(), AMIInterpolation< SourcePatch, TargetPatch >::imDirect, AMIInterpolation< SourcePatch, TargetPatch >::imFaceAreaWeight, AMIInterpolation< SourcePatch, TargetPatch >::imMapNearest, Foam::incrIndent(), patchIdentifier::index(), Foam::Info, patchIdentifier::name(), polyBoundaryMesh::names(), patchi, List< T >::size(), UPtrList< T >::size(), HashTable< T, Key, Hash >::size(), and faceAreaIntersect::tmMesh.
mapSrcToTgt() [1/18]
void mapSrcToTgt (const UList< Type > & srcFld, const CombineOp & cop, List< Type > & result) const
Map field from src to tgt mesh with defined operation.
Values passed in via 'result' are used to initialise the return value
Definition at line 82 of file meshToMeshTemplates.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, List< T >::size(), and Foam::sum().
Referenced by interRegionHeatTransferModel::interpolate(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), Foam::MapVolFields(), and ListPlusEqOp< T, Size >::operator()().
mapSrcToTgt() [2/18]
tmp<Field<Type> > mapSrcToTgt (const Field< Type > & srcFld, const CombineOp & cop) const
Return the src field mapped to the tgt mesh with a defined.
operation. Initial values of the result are set to zero
mapSrcToTgt() [3/18]
tmp<Field<Type> > mapSrcToTgt (const tmp< Field< Type >> & tsrcFld, const CombineOp & cop) const
Convenience function to map a tmp field to the tgt mesh.
with a defined operation
mapSrcToTgt() [4/18]
tmp<Field<Type> > mapSrcToTgt (const Field< Type > & srcFld) const
Convenience function to map a field to the tgt mesh with a.
default operation (plusEqOp)
mapSrcToTgt() [5/18]
tmp<Field<Type> > mapSrcToTgt (const tmp< Field< Type >> & tsrcFld) const
Convenience function to map a tmp field to the tgt mesh.
with a default operation (plusEqOp)
mapTgtToSrc() [1/18]
void mapTgtToSrc (const UList< Type > & tgtFld, const CombineOp & cop, List< Type > & result) const
Map field from tgt to src mesh with defined operation.
Values passed in via 'result' are used to initialise the return value
Definition at line 203 of file meshToMeshTemplates.C.
References Foam::abort(), mapDistribute::distribute(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, List< T >::size(), and Foam::sum().
Referenced by meshToMesh::mapSrcToTgt(), and meshToMesh::mapTgtToSrc().
mapTgtToSrc() [2/18]
tmp<Field<Type> > mapTgtToSrc (const Field< Type > & tgtFld, const CombineOp & cop) const
Return the tgt field mapped to the src mesh with a defined.
operation. Initial values of the result are set to zero
mapTgtToSrc() [3/18]
tmp<Field<Type> > mapTgtToSrc (const tmp< Field< Type >> & ttgtFld, const CombineOp & cop) const
Convenience function to map a tmp field to the src mesh.
with a defined operation
mapTgtToSrc() [4/18]
tmp<Field<Type> > mapTgtToSrc (const Field< Type > & tgtFld) const
Convenience function to map a field to the src mesh with a.
default operation (plusEqOp)
mapTgtToSrc() [5/18]
tmp<Field<Type> > mapTgtToSrc (const tmp< Field< Type >> & ttgtFld) const
Convenience function to map a tmp field to the src mesh.
with a default operation (plusEqOp)
mapSrcToTgt() [6/18]
void mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop, GeometricField< Type, fvPatchField, volMesh > & result) const
Interpolate a field with a defined operation. Values.
passed in via 'result' are used to initialise the return value
Definition at line 343 of file meshToMeshTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, Foam::identity(), meshToMesh::mapSrcToTgt(), fvPatchField< Type >::patch(), patchi, fvPatchField< Type >::patchInternalField(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), fvPatchField< Type >::rmap(), and List< Type >::size().
mapSrcToTgt() [7/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop) const
Interpolate a field with a defined operation. The initial.
values of the result are set to zero
mapSrcToTgt() [8/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfield, const CombineOp & cop) const
Interpolate a tmp field with a defined operation. The.
initial values of the result are set to zero
mapSrcToTgt() [9/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field) const
Convenience function to map a field with a default.
operation (plusEqOp)
mapSrcToTgt() [10/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfield) const
Convenience function to map a tmp field with a default.
operation (plusEqOp)
mapTgtToSrc() [6/18]
void mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop, GeometricField< Type, fvPatchField, volMesh > & result) const
Interpolate a field with a defined operation. Values.
passed in via 'result' are used to initialise the return value
Definition at line 551 of file meshToMeshTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, Foam::identity(), meshToMesh::mapTgtToSrc(), fvPatchField< Type >::patch(), patchi, fvPatchField< Type >::patchInternalField(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), fvPatchField< Type >::rmap(), and List< Type >::size().
mapTgtToSrc() [7/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop) const
Interpolate a field with a defined operation. The initial.
values of the result are set to zero
mapTgtToSrc() [8/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfield, const CombineOp & cop) const
Interpolate a tmp field with a defined operation. The.
initial values of the result are set to zero
mapTgtToSrc() [9/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field) const
Convenience function to map a field with a default.
operation (plusEqOp)
mapTgtToSrc() [10/18]
tmp<GeometricField<Type, fvPatchField, volMesh> > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfield) const
Convenience function to map a tmp field with a default.
operation (plusEqOp)
mapAndOpSrcToTgt() [1/5]
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< scalar > & srcField, Field< scalar > & tgtField, const plusEqOp< scalar > & cop) const
Definition at line 58 of file meshToMesh.C.
mapAndOpSrcToTgt() [2/5]
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< vector > & srcField, Field< vector > & tgtField, const plusEqOp< vector > & cop) const
Definition at line 69 of file meshToMesh.C.
mapAndOpSrcToTgt() [3/5]
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< sphericalTensor > & srcField, Field< sphericalTensor > & tgtField, const plusEqOp< sphericalTensor > & cop) const
Definition at line 80 of file meshToMesh.C.
mapAndOpSrcToTgt() [4/5]
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< symmTensor > & srcField, Field< symmTensor > & tgtField, const plusEqOp< symmTensor > & cop) const
Definition at line 91 of file meshToMesh.C.
mapAndOpSrcToTgt() [5/5]
void mapAndOpSrcToTgt (const AMIPatchToPatchInterpolation & AMI, const Field< tensor > & srcField, Field< tensor > & tgtField, const plusEqOp< tensor > & cop) const
Definition at line 102 of file meshToMesh.C.
mapAndOpTgtToSrc() [1/5]
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< scalar > & srcField, const Field< scalar > & tgtField, const plusEqOp< scalar > & cop) const
Definition at line 113 of file meshToMesh.C.
mapAndOpTgtToSrc() [2/5]
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< vector > & srcField, const Field< vector > & tgtField, const plusEqOp< vector > & cop) const
Definition at line 124 of file meshToMesh.C.
mapAndOpTgtToSrc() [3/5]
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< sphericalTensor > & srcField, const Field< sphericalTensor > & tgtField, const plusEqOp< sphericalTensor > & cop) const
Definition at line 135 of file meshToMesh.C.
mapAndOpTgtToSrc() [4/5]
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< symmTensor > & srcField, const Field< symmTensor > & tgtField, const plusEqOp< symmTensor > & cop) const
Definition at line 146 of file meshToMesh.C.
mapAndOpTgtToSrc() [5/5]
void mapAndOpTgtToSrc (const AMIPatchToPatchInterpolation & AMI, Field< tensor > & srcField, const Field< tensor > & tgtField, const plusEqOp< tensor > & cop) const
Definition at line 157 of file meshToMesh.C.
References List< T >::append(), polyMesh::bounds(), meshToMeshMethod::calculate(), cells, primitiveMesh::cells(), mapDistributeBase::constructMap(), mapDistributeBase::distribute(), Foam::endl(), polyMesh::faces(), forAll, boundBox::inflate(), Foam::Info, boundBox::max(), Foam::max(), boundBox::min(), Foam::min(), UPstream::myProcNo(), OSstream::name(), Foam::name(), meshToMeshMethod::New(), Foam::nl, IOobject::NO_READ, UPstream::nonBlocking, word::null, boundBox::overlaps(), patches, points, polyMesh::points(), Foam::Pout, Foam::reduce(), Foam::returnReduce(), s(), List< T >::size(), HashTable< T, Key, Hash >::size(), mapDistributeBase::subMap(), Foam::sum(), meshToMeshMethod::V(), Ostream::write(), meshToMeshMethod::writeConnectivity(), and Foam::xferMove().
mapSrcToTgt() [11/18]
Foam::tmp<Foam::Field<Type> > mapSrcToTgt (const Field< Type > & srcField, const CombineOp & cop) const
Definition at line 150 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt(), tmp< T >::ref(), and Foam::Zero.
mapSrcToTgt() [12/18]
Foam::tmp<Foam::Field<Type> > mapSrcToTgt (const tmp< Field< Type >> & tsrcField, const CombineOp & cop) const
Definition at line 172 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [13/18]
Foam::tmp<Foam::Field<Type> > mapSrcToTgt (const Field< Type > & srcField) const
Definition at line 183 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [14/18]
Foam::tmp<Foam::Field<Type> > mapSrcToTgt (const tmp< Field< Type >> & tsrcField) const
Definition at line 193 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [11/18]
Foam::tmp<Foam::Field<Type> > mapTgtToSrc (const Field< Type > & tgtField, const CombineOp & cop) const
Definition at line 269 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc(), tmp< T >::ref(), and Foam::Zero.
mapTgtToSrc() [12/18]
Foam::tmp<Foam::Field<Type> > mapTgtToSrc (const tmp< Field< Type >> & ttgtField, const CombineOp & cop) const
Definition at line 291 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [13/18]
Foam::tmp<Foam::Field<Type> > mapTgtToSrc (const Field< Type > & tgtField) const
Definition at line 302 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [14/18]
Foam::tmp<Foam::Field<Type> > mapTgtToSrc (const tmp< Field< Type >> & ttgtField) const
Definition at line 312 of file meshToMeshTemplates.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToTarget(), and meshToMesh::mapSrcToTgt().
mapSrcToTgt() [15/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop) const
Definition at line 407 of file meshToMeshTemplates.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, meshToMesh::mapSrcToTgt(), IOobject::name(), primitiveMesh::nCells(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::null(), GeometricField< Type, PatchField, GeoMesh >::ref(), UPtrList< T >::size(), fvMesh::time(), Time::timeName(), Foam::type(), and Foam::Zero.
mapSrcToTgt() [16/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfield, const CombineOp & cop) const
Definition at line 497 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [17/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapSrcToTgt (const GeometricField< Type, fvPatchField, volMesh > & field) const
Definition at line 509 of file meshToMeshTemplates.C.
References meshToMesh::mapSrcToTgt().
mapSrcToTgt() [18/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapSrcToTgt (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfield) const
Definition at line 520 of file meshToMeshTemplates.C.
References AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), and meshToMesh::mapTgtToSrc().
mapTgtToSrc() [15/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field, const CombineOp & cop) const
Definition at line 614 of file meshToMeshTemplates.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, meshToMesh::mapTgtToSrc(), IOobject::name(), primitiveMesh::nCells(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::null(), GeometricField< Type, PatchField, GeoMesh >::ref(), UPtrList< T >::size(), fvMesh::time(), Time::timeName(), Foam::type(), and Foam::Zero.
mapTgtToSrc() [16/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfield, const CombineOp & cop) const
Definition at line 704 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [17/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapTgtToSrc (const GeometricField< Type, fvPatchField, volMesh > & field) const
Definition at line 716 of file meshToMeshTemplates.C.
References meshToMesh::mapTgtToSrc().
mapTgtToSrc() [18/18]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > mapTgtToSrc (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfield) const
Definition at line 727 of file meshToMeshTemplates.C.
Member Data Documentation
interpolationMethodNames_
const NamedEnum< meshToMesh::interpolationMethod, 3 > interpolationMethodNames_ static
Definition at line 75 of file meshToMesh.H.
Referenced by NamedEnum< directionType, 3 >::names(), and interRegionOption::setMapper().
The documentation for this class was generated from the following files:
src/sampling/meshToMesh/meshToMesh.H
src/sampling/meshToMesh/meshToMesh.C
src/sampling/meshToMesh/meshToMeshI.H
src/sampling/meshToMesh/meshToMeshParallelOps.C
src/sampling/meshToMesh/meshToMeshTemplates.C