OpenFOAM: sampledSets Class Reference
sampledSets Class Reference
Set of sets to sample. Call sampledSets.write() to sample&write files.
Public Member Functions
TypeName ("sets")
Runtime type information.
sampledSets (const word &name, const Time &time, const dictionary &dict)
Construct from Time and dictionary.
sampledSets (const word &name, const objectRegistry &, const dictionary &, const bool loadFromFiles=false)
Construct for given objectRegistry and dictionary.
virtual ~sampledSets ()
Destructor.
void verbose (const bool verbosity=true)
Set verbosity level.
virtual bool read (const dictionary &)
Read the sampledSets.
virtual bool execute ()
Execute, currently does nothing.
virtual bool write ()
Sample and write.
void correct ()
Correct for mesh changes.
virtual void updateMesh (const mapPolyMesh &)
Update for changes of mesh.
virtual void movePoints (const polyMesh &)
Update for mesh point-motion.
virtual void readUpdate (const polyMesh::readUpdateState state)
Update for changes of mesh due to readUpdate.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Public Member Functions inherited from PtrList< sampledSet >
PtrList ()
Null Constructor.
PtrList (const label)
Construct with size specified.
PtrList (const PtrList< sampledSet > &)
Copy constructor.
PtrList (const PtrList< sampledSet > &, const CloneArg &)
Copy constructor with additional argument for clone.
PtrList (const Xfer< PtrList< sampledSet >> &)
Construct by transferring the parameter contents.
PtrList (PtrList< sampledSet > &, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< sampledSet > &)
Construct as copy of SLPtrList<T>
PtrList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
PtrList (Istream &)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
void setSize (const label)
Reset size of PtrList. If extending the PtrList, new entries are.
void resize (const label)
Alias for setSize(const label)
void clear ()
Clear the PtrList, i.e. set size to zero deleting all the.
void append (sampledSet *)
Append an element at the end of the list.
void append (const autoPtr< sampledSet > &)
void append (const tmp< sampledSet > &)
void transfer (PtrList< sampledSet > &)
Transfer the contents of the argument PtrList into this PtrList.
Xfer< PtrList< sampledSet > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
autoPtr< sampledSet > set (const label, sampledSet *)
Set element to given T* and return old element (can be nullptr)
autoPtr< sampledSet > set (const label, const autoPtr< sampledSet > &)
Set element to given autoPtr<T> and return old element.
autoPtr< sampledSet > set (const label, const tmp< sampledSet > &)
Set element to given tmp<T> and return old element.
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
void operator= (const PtrList< sampledSet > &)
Assignment.
Public Member Functions inherited from UPtrList< T >
UPtrList ()
Null Constructor.
UPtrList (const label)
Construct with size specified.
UPtrList (const Xfer< UPtrList< T >> &)
Construct by transferring the parameter contents.
UPtrList (UPtrList< T > &, bool reuse)
Construct as copy or re-use as specified.
label size () const
Return the number of elements in the UPtrList.
bool empty () const
Return true if the UPtrList is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void setSize (const label)
Reset size of UPtrList. This can only be used to set the size.
void resize (const label)
Reset size of UPtrList. This can only be used to set the size.
void clear ()
Clear the UPtrList, i.e. set size to zero.
void transfer (UPtrList< T > &)
Transfer the contents of the argument UPtrList into this.
Xfer< UPtrList< T > > xfer ()
Transfer contents to the Xfer container.
bool set (const label) const
Is element set.
T * set (const label, T *)
Set element. Return old element (can be nullptr).
void reorder (const labelUList &)
Reorders elements. Ordering does not have to be done in.
const T & operator[] (const label) const
Return element const reference.
T & operator[] (const label)
Return element reference.
const T * operator() (const label) const
Return element const pointer.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the UPtrList contains.
typedef T & reference
Type that can be used for storing into UPtrList::value_type objects.
typedef const T & const_reference
Type that can be used for storing into constant UPtrList::value_type.
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &, const dictionary &)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
Switch log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
Protected Member Functions inherited from PtrList< sampledSet >
void read (Istream &, const INew &inewt)
Read from Istream using given Istream constructor class.
Detailed Description
Set of sets to sample. Call sampledSets.write() to sample&write files.
Source files
sampledSets.H
sampledSets.C
Definition at line 62 of file sampledSets.H.
Constructor & Destructor Documentation
sampledSets() [1/2]
sampledSets (const word & name, const Time & time, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 142 of file sampledSets.C.
References polyMesh::defaultRegion, Foam::name(), UPstream::parRun(), and Foam::read().
sampledSets() [2/2]
sampledSets (const word & name, const objectRegistry & obr, const dictionary & dict, const bool loadFromFiles = false)
Construct for given objectRegistry and dictionary.
allow the possibility to load fields from files
Definition at line 184 of file sampledSets.C.
References polyMesh::defaultRegion, Foam::name(), UPstream::parRun(), and Foam::read().
~sampledSets()
~sampledSets () virtual
Destructor.
Definition at line 219 of file sampledSets.C.
Member Function Documentation
TypeName()
TypeName ("sets")
Runtime type information.
verbose()
void verbose (const bool verbosity = true)
Set verbosity level.
Definition at line 225 of file sampledSets.C.
read()
bool read (const dictionary & dict) virtual
Read the sampledSets.
Reimplemented from functionObject.
Definition at line 282 of file sampledSets.C.
References dict, Foam::endl(), forAll, dictionary::found(), Foam::Info, dictionary::lookup(), UPstream::master(), Foam::nl, and Foam::Pout.
execute()
bool execute () virtual
Execute, currently does nothing.
Implements functionObject.
Definition at line 231 of file sampledSets.C.
write()
bool write () virtual
Sample and write.
Implements functionObject.
Definition at line 237 of file sampledSets.C.
References Foam::endl(), UPstream::master(), Foam::mkDir(), Foam::nl, and Foam::Pout.
correct()
void correct ()
Correct for mesh changes.
Definition at line 330 of file sampledSets.C.
updateMesh()
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Reimplemented from functionObject.
Definition at line 348 of file sampledSets.C.
References correct, and mapPolyMesh::mesh().
movePoints()
void movePoints (const polyMesh & mesh) virtual
Update for mesh point-motion.
Reimplemented from functionObject.
Definition at line 357 of file sampledSets.C.
References correct.
readUpdate()
void readUpdate (const polyMesh::readUpdateState state) virtual
Update for changes of mesh due to readUpdate.
Definition at line 366 of file sampledSets.C.
References correct, and polyMesh::UNCHANGED.
The documentation for this class was generated from the following files:
src/sampling/sampledSet/sampledSets/sampledSets.H
src/sampling/sampledSet/sampledSets/sampledSets.C
src/sampling/sampledSet/sampledSets/sampledSetsGrouping.C
src/sampling/sampledSet/sampledSets/sampledSetsTemplates.C