OpenFOAM: sampledSurface Class Reference
sampledSurface Class Reference abstract
FunctionObjects » Utility function objects
An abstract class for surfaces with sampling.
Classes
class iNew
Class used for the PtrLists read-construction.
Public Member Functions
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &, const dictionary &)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor.
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool interpolate () const
Interpolation requested for surface.
virtual bool needsUpdate () const =0
Does the surface need an update?
virtual bool expire ()=0
Mark the surface as needing an update.
virtual bool update ()=0
Update the surface as required.
virtual const pointField & points () const =0
Points of surface.
virtual const faceList & faces () const =0
Faces of surface.
virtual const vectorField & Sf () const
Return face area vectors.
virtual const scalarField & magSf () const
Return face area magnitudes.
virtual const vectorField & Cf () const
Return face centres as vectorField.
scalar area () const
The total surface area.
template<class Type >
Type integrate (const Field< Type > &) const
Integration of a field across the surface.
template<class Type >
Type integrate (const tmp< Field< Type >> &) const
Integration of a field across the surface.
template<class Type >
Type average (const Field< Type > &) const
Area-averaged value of a field across the surface.
template<class Type >
Type average (const tmp< Field< Type >> &) const
Area-averaged value of a field across the surface.
tmp< Field< scalar > > project (const Field< scalar > &) const
Project field onto surface.
tmp< Field< scalar > > project (const Field< vector > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< sphericalTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< symmTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< tensor > &) const
Project field onto surface.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Interpolate from points to cell centre.
virtual tmp< scalarField > sample (const volScalarField &) const =0
Sample field on surface.
virtual tmp< vectorField > sample (const volVectorField &) const =0
Sample field on surface.
virtual tmp< sphericalTensorField > sample (const volSphericalTensorField &) const =0
Sample field on surface.
virtual tmp< symmTensorField > sample (const volSymmTensorField &) const =0
Sample field on surface.
virtual tmp< tensorField > sample (const volTensorField &) const =0
Sample field on surface.
virtual tmp< scalarField > sample (const surfaceScalarField &) const
Surface sample field on surface.
virtual tmp< vectorField > sample (const surfaceVectorField &) const
Surface Sample field on surface.
virtual tmp< sphericalTensorField > sample (const surfaceSphericalTensorField &) const
Surface sample field on surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &) const
Surface sample field on surface.
virtual tmp< tensorField > sample (const surfaceTensorField &) const
Surface sample field on surface.
virtual tmp< scalarField > interpolate (const interpolation< scalar > &) const =0
Interpolate field on surface.
virtual tmp< vectorField > interpolate (const interpolation< vector > &) const =0
Interpolate field on surface.
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &) const =0
Interpolate field on surface.
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &) const =0
Interpolate field on surface.
virtual tmp< tensorField > interpolate (const interpolation< tensor > &) const =0
Interpolate field on surface.
virtual void rename (const word &newName)
Rename.
virtual void print (Ostream &) const
Write.
template<class ReturnType , class Type >
Foam::tmp< Foam::Field< ReturnType > > project (const tmp< Field< Type >> &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Static Public Member Functions
static autoPtr< sampledSurface > New (const word &name, const polyMesh &, const dictionary &)
Return a reference to the selected surface.
Protected Member Functions
virtual void clearGeom () const
Friends
Ostream & operator<< (Ostream &, const sampledSurface &)
Ostream operator.
Detailed Description
An abstract class for surfaces with sampling.
The constructors for the derived classes should generally start in a 'expired' condition (ie, needsUpdate() == true) and rely on a subsequent call to the update() method to complete the initialization. Delaying the final construction as late as possible allows the construction of surfaces that may depend on intermediate calculation results (eg, iso-surfaces) and also avoids the unnecessary reconstruction of surfaces between sampling intervals.
It is the responsibility of the caller to ensure that the surface update() is called before the surface is used. The update() method implementation should do nothing when the surface is already up-to-date.
Source files
sampledSurface.H
sampledSurface.C
sampledSurfaceTemplates.C
Definition at line 84 of file sampledSurface.H.
Constructor & Destructor Documentation
sampledSurface() [1/2]
sampledSurface (const word & name, const polyMesh & mesh, const bool interpolate = false)
Construct from name, mesh.
Definition at line 150 of file sampledSurface.C.
Referenced by sampledSurface::New(), and sampledSurface::iNew::operator()().
sampledSurface() [2/2]
sampledSurface (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 167 of file sampledSurface.C.
References dictionary::readIfPresent().
~sampledSurface()
~sampledSurface () virtual
Destructor.
Definition at line 187 of file sampledSurface.C.
Referenced by sampledSurface::clone().
Member Function Documentation
clearGeom()
void clearGeom () const protected virtual
Definition at line 42 of file sampledSurface.C.
References Foam::abort(), Foam::deleteDemandDrivenData(), Foam::FatalError, FatalErrorInFunction, forAll, sampledSurface::New(), points, and List< T >::size().
Referenced by sampledPlane::expire(), sampledIsoSurfaceCell::expire(), sampledPatch::expire(), sampledTriSurfaceMesh::expire(), and sampledPlane::update().
TypeName()
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , sampledSurface , word , (const word &name, const polyMesh &mesh, const dictionary &dict) , (name, mesh, dict))
Declare run-time constructor selection table.
clone()
autoPtr<sampledSurface> clone () const inline
Clone.
Definition at line 224 of file sampledSurface.H.
References sampledSurface::New(), NotImplemented, and sampledSurface::~sampledSurface().
New()
Foam::autoPtr< Foam::sampledSurface > New (const word & name, const polyMesh & mesh, const dictionary & dict) static
Return a reference to the selected surface.
Definition at line 117 of file sampledSurface.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), mesh, Foam::name(), Foam::nl, and sampledSurface::sampledSurface().
Referenced by sampledSurface::clearGeom(), sampledSurface::clone(), NamedEnum< directionType, 3 >::names(), and sampledSurface::iNew::operator()().
mesh()
const polyMesh& mesh () const inline
Access to the underlying mesh.
Definition at line 251 of file sampledSurface.H.
Referenced by sampledPatch::patchFaceLabels(), and sampledSurface::pointAverage().
name()
const word& name () const inline
Name of surface.
Definition at line 257 of file sampledSurface.H.
Referenced by sampledSurface::iNew::operator()(), and sampledPatch::patchFaceLabels().
interpolate() [1/6]
bool interpolate () const inline
Interpolation requested for surface.
Definition at line 263 of file sampledSurface.H.
References sampledSurface::area(), sampledSurface::average(), sampledSurface::Cf(), sampledSurface::expire(), sampledSurface::faces(), sampledSurface::integrate(), sampledSurface::magSf(), sampledSurface::needsUpdate(), sampledSurface::pointAverage(), sampledSurface::points(), sampledSurface::sample(), sampledSurface::Sf(), and sampledSurface::update().
Referenced by sampledThresholdCellFaces::faces(), sampledIsoSurfaceCell::faces(), sampledPatch::faces(), sampledTriSurfaceMesh::faces(), sampledPatchInternalField::interpolate(), sampledThresholdCellFaces::interpolate(), sampledPlane::interpolate(), sampledIsoSurfaceCell::interpolate(), sampledCuttingPlane::interpolate(), distanceSurface::interpolate(), sampledIsoSurface::interpolate(), sampledPatch::interpolate(), sampledTriSurfaceMesh::interpolate(), sampledPlane::meshCells(), nearestEqOp::operator()(), sampledSurface::iNew::operator()(), sampledPatchInternalField::sample(), sampledThresholdCellFaces::sample(), sampledPlane::sample(), sampledIsoSurfaceCell::sample(), sampledCuttingPlane::sample(), distanceSurface::sample(), sampledIsoSurface::sample(), sampledPatch::sample(), sampledTriSurfaceMesh::sample(), sampledIsoSurface::sampledIsoSurface(), sampledCuttingPlane::surface(), distanceSurface::surface(), and sampledIsoSurface::surface().
needsUpdate()
virtual bool needsUpdate () const pure virtual
Does the surface need an update?
Implemented in sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, and sampledPlane.
Referenced by sampledSurface::interpolate().
expire()
virtual bool expire () pure virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implemented in sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, and sampledPlane.
Referenced by sampledSurface::interpolate().
update()
virtual bool update () pure virtual
Update the surface as required.
Do nothing (and return false) if no update was required
Implemented in sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, and sampledPlane.
Referenced by sampledSurface::interpolate(), and sampledSurfaces::update().
points()
virtual const pointField& points () const pure virtual
Points of surface.
Implemented in sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, and sampledPlane.
Referenced by sampledSurface::interpolate(), NamedEnum< directionType, 3 >::names(), and sampledSurfaces::update().
faces()
virtual const faceList& faces () const pure virtual
Faces of surface.
Implemented in sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, and sampledPlane.
Referenced by sampledSurface::interpolate(), NamedEnum< directionType, 3 >::names(), sampledSurface::project(), and sampledSurfaces::update().
Sf()
const Foam::vectorField & Sf () const virtual
Return face area vectors.
Definition at line 195 of file sampledSurface.C.
Referenced by sampledSurface::average(), and sampledSurface::interpolate().
magSf()
const Foam::scalarField & magSf () const virtual
Return face area magnitudes.
Definition at line 206 of file sampledSurface.C.
Referenced by sampledSurface::average(), sampledSurface::integrate(), and sampledSurface::interpolate().
Cf()
const Foam::vectorField & Cf () const virtual
Return face centres as vectorField.
Definition at line 217 of file sampledSurface.C.
Referenced by sampledSurface::interpolate().
area()
Foam::scalar area () const
The total surface area.
Definition at line 228 of file sampledSurface.C.
References Foam::reduce(), sampledSurface::sample(), and Foam::sum().
Referenced by sampledSurface::average(), and sampledSurface::interpolate().
integrate() [1/2]
Type integrate (const Field< Type > & field) const
Integration of a field across the surface.
Definition at line 50 of file sampledSurfaceTemplates.C.
References sampledSurface::magSf(), Foam::reduce(), Foam::sum(), and Foam::Zero.
Referenced by sampledSurface::integrate(), and sampledSurface::interpolate().
integrate() [2/2]
Type integrate (const tmp< Field< Type >> & field) const
Integration of a field across the surface.
Definition at line 65 of file sampledSurfaceTemplates.C.
References sampledSurface::integrate().
average() [1/2]
Type average (const Field< Type > & field) const
Area-averaged value of a field across the surface.
Definition at line 74 of file sampledSurfaceTemplates.C.
References sampledSurface::area(), sampledSurface::magSf(), Foam::reduce(), Foam::sum(), and Foam::Zero.
Referenced by sampledSurface::average(), and sampledSurface::interpolate().
average() [2/2]
Type average (const tmp< Field< Type >> & field) const
Area-averaged value of a field across the surface.
Definition at line 98 of file sampledSurfaceTemplates.C.
References sampledSurface::average(), List< Type >::clear(), forAll, Foam::mag(), and sampledSurface::Sf().
project() [1/6]
Foam::tmp< Foam::Field< Foam::scalar > > project (const Field< scalar > & field) const
Project field onto surface.
Definition at line 291 of file sampledSurface.C.
References forAll, and tmp< T >::ref().
project() [2/6]
Foam::tmp< Foam::Field< Foam::scalar > > project (const Field< vector > & field) const
Project field onto surface.
Definition at line 306 of file sampledSurface.C.
References tmp< T >::ref().
project() [3/6]
Foam::tmp< Foam::Field< Foam::vector > > project (const Field< sphericalTensor > & field) const
Project field onto surface.
Definition at line 315 of file sampledSurface.C.
References tmp< T >::ref().
project() [4/6]
Foam::tmp< Foam::Field< Foam::vector > > project (const Field< symmTensor > & field) const
Project field onto surface.
Definition at line 324 of file sampledSurface.C.
References tmp< T >::ref().
project() [5/6]
Foam::tmp< Foam::Field< Foam::vector > > project (const Field< tensor > & field) const
Project field onto surface.
Definition at line 333 of file sampledSurface.C.
References tmp< T >::ref().
pointAverage() [1/2]
tmp<GeometricField<Type, fvPatchField, volMesh> > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > & pfld) const
Interpolate from points to cell centre.
Referenced by sampledSurface::interpolate(), and sampledSurface::project().
sample() [1/10]
Foam::tmp< Foam::sphericalTensorField > sample (const volScalarField & sField) const pure virtual
Sample field on surface.
Implemented in sampledPatch, sampledPatch, sampledTriSurfaceMesh, sampledIsoSurface, distanceSurface, sampledPatch, sampledCuttingPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, sampledPlane, and sampledPatchInternalField.
Definition at line 251 of file sampledSurface.C.
References NotImplemented.
Referenced by sampledSurface::area(), sampledSurface::interpolate(), and sampledSurface::sample().
sample() [2/10]
virtual tmp<vectorField> sample (const volVectorField &) const pure virtual
Sample field on surface.
Implemented in sampledTriSurfaceMesh, sampledIsoSurface, distanceSurface, sampledPatch, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
sample() [3/10]
virtual tmp<sphericalTensorField> sample (const volSphericalTensorField &) const pure virtual
Sample field on surface.
Implemented in sampledTriSurfaceMesh, sampledIsoSurface, distanceSurface, sampledPatch, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
sample() [4/10]
virtual tmp<symmTensorField> sample (const volSymmTensorField &) const pure virtual
Sample field on surface.
Implemented in sampledTriSurfaceMesh, sampledIsoSurface, distanceSurface, sampledPatch, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
sample() [5/10]
virtual tmp<tensorField> sample (const volTensorField &) const pure virtual
Sample field on surface.
Implemented in sampledTriSurfaceMesh, sampledIsoSurface, distanceSurface, sampledPatch, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
sample() [6/10]
Foam::tmp< Foam::scalarField > sample (const surfaceScalarField & sField) const virtual
Surface sample field on surface.
Reimplemented in sampledPatch.
Definition at line 241 of file sampledSurface.C.
References NotImplemented, and sampledSurface::sample().
sample() [7/10]
virtual tmp<vectorField> sample (const surfaceVectorField &) const virtual
Surface Sample field on surface.
Reimplemented in sampledPatch, sampledPatch, sampledTriSurfaceMesh, sampledIsoSurface, distanceSurface, sampledPatch, sampledCuttingPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, sampledPlane, and sampledPatchInternalField.
sample() [8/10]
virtual tmp<sphericalTensorField> sample (const surfaceSphericalTensorField &) const virtual
Surface sample field on surface.
Reimplemented in sampledPatch, sampledPatch, sampledTriSurfaceMesh, sampledIsoSurface, distanceSurface, sampledPatch, sampledCuttingPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, sampledPlane, and sampledPatchInternalField.
sample() [9/10]
Foam::tmp< Foam::symmTensorField > sample (const surfaceSymmTensorField & sField) const virtual
Surface sample field on surface.
Reimplemented in sampledPatch.
Definition at line 271 of file sampledSurface.C.
References NotImplemented, and sampledSurface::sample().
sample() [10/10]
Foam::tmp< Foam::tensorField > sample (const surfaceTensorField & sField) const virtual
Surface sample field on surface.
Reimplemented in sampledPatch.
Definition at line 281 of file sampledSurface.C.
References NotImplemented.
interpolate() [2/6]
virtual tmp<scalarField> interpolate (const interpolation< scalar > &) const pure virtual
Interpolate field on surface.
Implemented in sampledTriSurfaceMesh, sampledPatch, sampledIsoSurface, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
interpolate() [3/6]
virtual tmp<vectorField> interpolate (const interpolation< vector > &) const pure virtual
Interpolate field on surface.
Implemented in sampledTriSurfaceMesh, sampledPatch, sampledIsoSurface, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
interpolate() [4/6]
virtual tmp<sphericalTensorField> interpolate (const interpolation< sphericalTensor > &) const pure virtual
Interpolate field on surface.
Implemented in sampledTriSurfaceMesh, sampledPatch, sampledIsoSurface, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
interpolate() [5/6]
virtual tmp<symmTensorField> interpolate (const interpolation< symmTensor > &) const pure virtual
Interpolate field on surface.
Implemented in sampledTriSurfaceMesh, sampledPatch, sampledIsoSurface, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
interpolate() [6/6]
virtual tmp<tensorField> interpolate (const interpolation< tensor > &) const pure virtual
Interpolate field on surface.
Implemented in sampledTriSurfaceMesh, sampledPatch, sampledIsoSurface, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
rename()
virtual void rename (const word & newName) inline virtual
Rename.
Definition at line 431 of file sampledSurface.H.
References sampledSurface::operator<<, and sampledSurface::print().
print()
void print (Ostream & os) const virtual
Write.
Reimplemented in sampledTriSurfaceMesh, sampledPatch, sampledIsoSurface, distanceSurface, sampledCuttingPlane, sampledIsoSurfaceCell, sampledPlane, sampledThresholdCellFaces, and sampledPatchInternalField.
Definition at line 341 of file sampledSurface.C.
References Foam::type().
Referenced by Foam::operator<<(), and sampledSurface::rename().
project() [6/6]
Foam::tmp<Foam::Field<ReturnType> > project (const tmp< Field< Type >> & field) const
Definition at line 144 of file sampledSurfaceTemplates.C.
References sampledSurface::faces(), and sampledSurface::pointAverage().
pointAverage() [2/2]
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > & pfld) const
Definition at line 157 of file sampledSurfaceTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), IOobject::db(), Foam::dimless, forAll, sampledSurface::mesh(), DimensionedField< Type, GeoMesh >::mesh(), primitiveMesh::nCells(), IOobject::NO_READ, IOobject::NO_WRITE, primitiveMesh::nPoints(), primitiveMesh::pointCells(), tmp< T >::ref(), fvMesh::time(), Time::timeName(), and Foam::Zero.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const sampledSurface &) friend
Ostream operator.
Referenced by sampledSurface::rename().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledSurface/sampledSurface.H
src/sampling/sampledSurface/sampledSurface/sampledSurface.C
src/sampling/sampledSurface/sampledSurface/sampledSurfaceTemplates.C