OpenFOAM: sampledIsoSurface Class Reference
sampledIsoSurface Class Reference
A sampledSurface defined by a surface of iso value. Always triangulated. To be used in sampleSurfaces / functionObjects. Recalculates iso surface only if time changes.
Public Member Functions
TypeName ("sampledIsoSurface")
Runtime type information.
sampledIsoSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
virtual ~sampledIsoSurface ()
Destructor.
virtual bool needsUpdate () const
Does the surface need an update?
virtual bool expire ()
Mark the surface as needing an update.
virtual bool update ()
Update the surface as required.
virtual const pointField & points () const
Points of surface.
virtual const faceList & faces () const
Faces of surface.
const isoSurface & surface () const
void getIsoField ()
Lookup or read isoField. Sets volFieldPtr_ and pointFieldPtr_.
virtual tmp< scalarField > sample (const volScalarField &) const
Sample field on surface.
virtual tmp< vectorField > sample (const volVectorField &) const
Sample field on surface.
virtual tmp< sphericalTensorField > sample (const volSphericalTensorField &) const
Sample field on surface.
virtual tmp< symmTensorField > sample (const volSymmTensorField &) const
Sample field on surface.
virtual tmp< tensorField > sample (const volTensorField &) const
Sample field on surface.
virtual tmp< scalarField > interpolate (const interpolation< scalar > &) const
Interpolate field on surface.
virtual tmp< vectorField > interpolate (const interpolation< vector > &) const
Interpolate field on surface.
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &) const
Interpolate field on surface.
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &) const
Interpolate field on surface.
virtual tmp< tensorField > interpolate (const interpolation< tensor > &) const
Interpolate field on surface.
virtual void print (Ostream &) const
Write.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleField (const GeometricField< Type, fvPatchField, volMesh > &vField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateField (const interpolation< Type > &interpolator) const
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &, const dictionary &)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor.
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool interpolate () const
Interpolation requested for surface.
virtual const vectorField & Sf () const
Return face area vectors.
virtual const scalarField & magSf () const
Return face area magnitudes.
virtual const vectorField & Cf () const
Return face centres as vectorField.
scalar area () const
The total surface area.
template<class Type >
Type integrate (const Field< Type > &) const
Integration of a field across the surface.
template<class Type >
Type integrate (const tmp< Field< Type >> &) const
Integration of a field across the surface.
template<class Type >
Type average (const Field< Type > &) const
Area-averaged value of a field across the surface.
template<class Type >
Type average (const tmp< Field< Type >> &) const
Area-averaged value of a field across the surface.
tmp< Field< scalar > > project (const Field< scalar > &) const
Project field onto surface.
tmp< Field< scalar > > project (const Field< vector > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< sphericalTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< symmTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< tensor > &) const
Project field onto surface.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Interpolate from points to cell centre.
virtual tmp< scalarField > sample (const surfaceScalarField &) const
Surface sample field on surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &) const
Surface sample field on surface.
virtual tmp< tensorField > sample (const surfaceTensorField &) const
Surface sample field on surface.
virtual void rename (const word &newName)
Rename.
template<class ReturnType , class Type >
Foam::tmp< Foam::Field< ReturnType > > project (const tmp< Field< Type >> &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Additional Inherited Members
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &, const dictionary &)
Return a reference to the selected surface.
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
Detailed Description
A sampledSurface defined by a surface of iso value. Always triangulated. To be used in sampleSurfaces / functionObjects. Recalculates iso surface only if time changes.
Source files
sampledIsoSurface.H
sampledIsoSurface.C
Definition at line 53 of file sampledIsoSurface.H.
Constructor & Destructor Documentation
sampledIsoSurface()
sampledIsoSurface (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 438 of file sampledIsoSurface.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, polyBoundaryMesh::findPatchID(), Foam::Info, sampledSurface::interpolate(), dictionary::lookup(), and polyBoundaryMesh::names().
~sampledIsoSurface()
~sampledIsoSurface () virtual
Destructor.
Definition at line 495 of file sampledIsoSurface.C.
Member Function Documentation
TypeName()
TypeName ("sampledIsoSurface")
Runtime type information.
needsUpdate()
bool needsUpdate () const virtual
Does the surface need an update?
Implements sampledSurface.
Definition at line 501 of file sampledIsoSurface.C.
References mesh, fvMesh::time(), and TimeState::timeIndex().
expire()
bool expire () virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implements sampledSurface.
Definition at line 509 of file sampledIsoSurface.C.
update()
bool update () virtual
Update the surface as required.
Do nothing (and return false) if no update was needed
Implements sampledSurface.
Definition at line 530 of file sampledIsoSurface.C.
References sampledIsoSurface::sample().
points()
virtual const pointField& points () const inline virtual
Points of surface.
Implements sampledSurface.
Definition at line 172 of file sampledIsoSurface.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::points(), and sampledIsoSurface::surface().
faces()
virtual const faceList& faces () const inline virtual
Faces of surface.
Implements sampledSurface.
Definition at line 178 of file sampledIsoSurface.H.
References autoPtr< T >::empty(), forAll, autoPtr< T >::reset(), s(), List< T >::size(), and sampledIsoSurface::surface().
surface()
const isoSurface& surface () const inline
Definition at line 195 of file sampledIsoSurface.H.
References sampledIsoSurface::getIsoField(), sampledSurface::interpolate(), sampledIsoSurface::print(), and sampledIsoSurface::sample().
Referenced by sampledIsoSurface::faces(), and sampledIsoSurface::points().
getIsoField()
void getIsoField ()
Lookup or read isoField. Sets volFieldPtr_ and pointFieldPtr_.
Referenced by sampledIsoSurface::surface().
sample() [1/5]
Foam::tmp< Foam::scalarField > sample (const volScalarField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 537 of file sampledIsoSurface.C.
Referenced by sampledIsoSurface::sample(), sampledIsoSurface::surface(), and sampledIsoSurface::update().
sample() [2/5]
Foam::tmp< Foam::vectorField > sample (const volVectorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 546 of file sampledIsoSurface.C.
References sampledIsoSurface::sample().
sample() [3/5]
Foam::tmp< Foam::sphericalTensorField > sample (const volSphericalTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 555 of file sampledIsoSurface.C.
References sampledIsoSurface::sample().
sample() [4/5]
Foam::tmp< Foam::symmTensorField > sample (const volSymmTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 564 of file sampledIsoSurface.C.
References sampledIsoSurface::sample().
sample() [5/5]
Foam::tmp< Foam::tensorField > sample (const volTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 573 of file sampledIsoSurface.C.
References sampledSurface::interpolate().
interpolate() [1/5]
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 582 of file sampledIsoSurface.C.
References sampledSurface::interpolate().
interpolate() [2/5]
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 591 of file sampledIsoSurface.C.
References sampledSurface::interpolate().
interpolate() [3/5]
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 599 of file sampledIsoSurface.C.
References sampledSurface::interpolate().
interpolate() [4/5]
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 608 of file sampledIsoSurface.C.
References sampledSurface::interpolate().
interpolate() [5/5]
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 617 of file sampledIsoSurface.C.
print()
void print (Ostream & os) const virtual
Write.
Reimplemented from sampledSurface.
Definition at line 625 of file sampledIsoSurface.C.
References Foam::name().
Referenced by sampledIsoSurface::surface().
sampleField()
Foam::tmp<Foam::Field<Type> > sampleField (const GeometricField< Type, fvPatchField, volMesh > & vField) const
Definition at line 36 of file sampledIsoSurfaceTemplates.C.
interpolateField()
Foam::tmp<Foam::Field<Type> > interpolateField (const interpolation< Type > & interpolator) const
Definition at line 50 of file sampledIsoSurfaceTemplates.C.
References Foam::MULES::interpolate(), DimensionedField< Type, GeoMesh >::mesh(), Foam::New(), and interpolation< Type >::psi().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/isoSurface/sampledIsoSurface.H
src/sampling/sampledSurface/isoSurface/sampledIsoSurface.C
src/sampling/sampledSurface/isoSurface/sampledIsoSurfaceTemplates.C