OpenFOAM: dxSurfaceWriter Class Reference
dxSurfaceWriter Class Reference
A surfaceWriter for OpenDX format.
Public Member Functions
TypeName ("dx")
Runtime type information.
dxSurfaceWriter ()
Construct null.
virtual ~dxSurfaceWriter ()
Destructor.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< scalar > &values, const bool isNodeValues, const bool verbose=false) const
Write scalarField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< vector > &values, const bool isNodeValues, const bool verbose=false) const
Write vectorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< sphericalTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write sphericalTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< symmTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write symmTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< tensor > &values, const bool isNodeValues, const bool verbose=false) const
Write tensorField for a single surface to file.
template<>
void writeData (Ostream &os, const Field< scalar > &values)
template<>
void writeData (Ostream &os, const Field< vector > &values)
template<>
void writeData (Ostream &os, const Field< sphericalTensor > &values)
template<>
void writeData (Ostream &os, const Field< symmTensor > &values)
template<>
void writeData (Ostream &os, const Field< tensor > &values)
Public Member Functions inherited from surfaceWriter
TypeName ("surfaceWriter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &optDict),(optDict))
surfaceWriter ()
Construct null.
virtual ~surfaceWriter ()
Destructor.
virtual bool separateGeometry ()
True if the surface format supports geometry in a separate file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const bool verbose=false) const
Write single surface geometry to file.
Additional Inherited Members
Static Public Member Functions inherited from surfaceWriter
static autoPtr< surfaceWriter > New (const word &writeType)
Return a reference to the selected surfaceWriter.
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Return a reference to the selected surfaceWriter.
Detailed Description
A surfaceWriter for OpenDX format.
Source files
dxSurfaceWriter.H
dxSurfaceWriter.C
Definition at line 48 of file dxSurfaceWriter.H.
Constructor & Destructor Documentation
dxSurfaceWriter()
dxSurfaceWriter ()
Construct null.
Definition at line 270 of file dxSurfaceWriter.C.
~dxSurfaceWriter()
~dxSurfaceWriter () virtual
Destructor.
Definition at line 278 of file dxSurfaceWriter.C.
References Foam::defineSurfaceWriterWriteFields().
Member Function Documentation
TypeName()
TypeName ("dx")
Runtime type information.
write() [1/5]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< scalar > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write scalarField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [2/5]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< vector > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write vectorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [3/5]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< sphericalTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write sphericalTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [4/5]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< symmTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write symmTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [5/5]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< tensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write tensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
writeData() [1/5]
void writeData (Ostream & os, const Field< scalar > & values)
Definition at line 119 of file dxSurfaceWriter.C.
References forAll, Foam::nl, and List< T >::size().
writeData() [2/5]
void writeData (Ostream & os, const Field< vector > & values)
Definition at line 136 of file dxSurfaceWriter.C.
References forAll, Foam::nl, List< T >::size(), x, and y.
writeData() [3/5]
void writeData (Ostream & os, const Field< sphericalTensor > & values)
Definition at line 155 of file dxSurfaceWriter.C.
References forAll, Foam::nl, and List< Type >::size().
writeData() [4/5]
void writeData (Ostream & os, const Field< symmTensor > & values)
Definition at line 172 of file dxSurfaceWriter.C.
References forAll, Foam::nl, List< T >::size(), SymmTensor< Cmpt >::xx(), SymmTensor< Cmpt >::xy(), SymmTensor< Cmpt >::xz(), SymmTensor< Cmpt >::yy(), SymmTensor< Cmpt >::yz(), and SymmTensor< Cmpt >::zz().
writeData() [5/5]
void writeData (Ostream & os, const Field< tensor > & values) inline
Definition at line 195 of file dxSurfaceWriter.C.
References Foam::endl(), forAll, Foam::Info, Foam::isDir(), Foam::mkDir(), OFstream::name(), Foam::nl, List< T >::size(), List< Type >::size(), writeData(), Tensor< Cmpt >::xx(), Tensor< Cmpt >::xy(), Tensor< Cmpt >::xz(), Tensor< Cmpt >::yx(), Tensor< Cmpt >::yy(), Tensor< Cmpt >::yz(), Tensor< Cmpt >::zx(), Tensor< Cmpt >::zy(), and Tensor< Cmpt >::zz().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/writers/dx/dxSurfaceWriter.H
src/sampling/sampledSurface/writers/dx/dxSurfaceWriter.C