OpenFOAM: sampledTriSurfaceMesh Class Reference
sampledTriSurfaceMesh Class Reference
A sampledSurface from a triSurfaceMesh. It samples on the points/triangles of the triSurface.
Public Types
enum samplingSource { cells, insideCells, boundaryFaces }
Types of communications.
Public Types inherited from MeshedSurface< face >
typedef face FaceType
Face type used.
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Public Member Functions
TypeName ("sampledTriSurfaceMesh")
Runtime type information.
sampledTriSurfaceMesh (const word &name, const polyMesh &mesh, const word &surfaceName, const samplingSource sampleSource)
Construct from components.
sampledTriSurfaceMesh (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
sampledTriSurfaceMesh (const word &name, const polyMesh &mesh, const triSurface &surface, const word &sampleSourceName)
Construct from triSurface.
virtual ~sampledTriSurfaceMesh ()
Destructor.
virtual bool needsUpdate () const
Does the surface need an update?
virtual bool expire ()
Mark the surface as needing an update.
virtual bool update ()
Update the surface as required.
bool update (const treeBoundBox &)
Update the surface using a bound box to limit the searching.
virtual const pointField & points () const
Points of surface.
virtual const faceList & faces () const
Faces of surface.
virtual tmp< scalarField > sample (const volScalarField &) const
Sample field on surface.
virtual tmp< vectorField > sample (const volVectorField &) const
Sample field on surface.
virtual tmp< sphericalTensorField > sample (const volSphericalTensorField &) const
Sample field on surface.
virtual tmp< symmTensorField > sample (const volSymmTensorField &) const
Sample field on surface.
virtual tmp< tensorField > sample (const volTensorField &) const
Sample field on surface.
virtual tmp< scalarField > interpolate (const interpolation< scalar > &) const
Interpolate field on surface.
virtual tmp< vectorField > interpolate (const interpolation< vector > &) const
Interpolate field on surface.
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &) const
Interpolate field on surface.
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &) const
Interpolate field on surface.
virtual tmp< tensorField > interpolate (const interpolation< tensor > &) const
Interpolate field on surface.
virtual void print (Ostream &) const
Write.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleField (const GeometricField< Type, fvPatchField, volMesh > &vField) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateField (const interpolation< Type > &interpolator) const
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &, const dictionary &)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor.
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool interpolate () const
Interpolation requested for surface.
virtual const vectorField & Sf () const
Return face area vectors.
virtual const scalarField & magSf () const
Return face area magnitudes.
virtual const vectorField & Cf () const
Return face centres as vectorField.
scalar area () const
The total surface area.
template<class Type >
Type integrate (const Field< Type > &) const
Integration of a field across the surface.
template<class Type >
Type integrate (const tmp< Field< Type >> &) const
Integration of a field across the surface.
template<class Type >
Type average (const Field< Type > &) const
Area-averaged value of a field across the surface.
template<class Type >
Type average (const tmp< Field< Type >> &) const
Area-averaged value of a field across the surface.
tmp< Field< scalar > > project (const Field< scalar > &) const
Project field onto surface.
tmp< Field< scalar > > project (const Field< vector > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< sphericalTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< symmTensor > &) const
Project field onto surface.
tmp< Field< vector > > project (const Field< tensor > &) const
Project field onto surface.
template<class Type >
tmp< GeometricField< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Interpolate from points to cell centre.
virtual tmp< scalarField > sample (const surfaceScalarField &) const
Surface sample field on surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &) const
Surface sample field on surface.
virtual tmp< tensorField > sample (const surfaceTensorField &) const
Surface sample field on surface.
virtual void rename (const word &newName)
Rename.
template<class ReturnType , class Type >
Foam::tmp< Foam::Field< ReturnType > > project (const tmp< Field< Type >> &field) const
template<class Type >
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld) const
Public Member Functions inherited from MeshedSurface< face >
MeshedSurface ()
Construct null.
MeshedSurface (const Xfer< pointField > &, const Xfer< List< face >> &, const Xfer< surfZoneList > &)
Construct by transferring components (points, faces, zones).
MeshedSurface (const Xfer< pointField > &, const Xfer< List< face >> &, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Construct by transferring components (points, faces).
MeshedSurface (const MeshedSurface &)
Construct as copy.
MeshedSurface (const UnsortedMeshedSurface< face > &)
Construct from a UnsortedMeshedSurface.
MeshedSurface (const polyBoundaryMesh &, const bool globalPoints=false)
Construct from a boundary mesh with local points/faces.
MeshedSurface (const surfMesh &)
Construct from a surfMesh.
MeshedSurface (const Xfer< UnsortedMeshedSurface< face >> &)
Construct by transferring the contents from a UnsortedMeshedSurface.
MeshedSurface (const Xfer< MeshedSurface< face >> &)
Construct by transferring the contents from a MeshedSurface.
MeshedSurface (const fileName &)
Construct from file name (uses extension to determine type)
MeshedSurface (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
MeshedSurface (const Time &, const word &surfName="")
Construct from database.
MeshedSurface (const MeshedSurface< face > &surf)
ClassName ("MeshedSurface")
Runtime type information.
bool isTri ()
Specialization for holding triangulated information.
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
Destructor.
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< face > &surf),(name, surf))
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void write (const Time &, const word &surfName="") const
Write to database.
label size () const
The surface size is the number of faces.
const List< face > & faces () const
Return const access to the faces.
const List< surfZone > & surfZones () const
Const access to the surface zones.
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
Add surface zones.
virtual void removeZones ()
Remove surface zones.
virtual void clear ()
Clear all storage.
virtual void movePoints (const pointField &)
Move points.
virtual void scalePoints (const scalar)
Scale points. A non-positive factor is ignored.
virtual void reset (const Xfer< pointField > &points, const Xfer< List< face >> &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void reset (const Xfer< List< point >> &points, const Xfer< List< face >> &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
virtual void cleanup (const bool verbose)
Remove invalid faces.
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label triangulate ()
Triangulate in-place, returning the number of triangles added.
virtual label triangulate (List< label > &faceMap)
Triangulate in-place, returning the number of triangles added.
label triangulate ()
Specialization for holding triangulated information.
label triangulate (List< label > &faceMap)
Specialization for holding triangulated information.
MeshedSurface subsetMesh (const labelHashSet &include, labelList &pointMap, labelList &faceMap) const
Return new surface.
MeshedSurface subsetMesh (const labelHashSet &include) const
Return new surface.
void transfer (MeshedSurface< face > &)
Transfer the contents of the argument and annul the argument.
void transfer (UnsortedMeshedSurface< face > &)
Transfer the contents of the argument and annul the argument.
Xfer< MeshedSurface< face > > xfer ()
Transfer contents to the Xfer container.
bool read (const fileName &, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &)
Read from file. Chooses reader based on detected extension.
void writeStats (Ostream &os) const
void operator= (const MeshedSurface< face > &)
operator MeshedSurfaceProxy< face > () const
Conversion operator to MeshedSurfaceProxy.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (const Xfer< FaceList< Face >> &faces, const Xfer< List< PointType >> &points)
Construct from components.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceNormals () const
Return face normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()
Construct null.
virtual ~surfaceFormatsCore ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &, const dictionary &)
Return a reference to the selected surface.
Static Public Member Functions inherited from MeshedSurface< face >
static bool isTri ()
Face storage only handles triangulated faces.
static bool canRead (const fileName &, const bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, const bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, const bool verbose=false)
Can we write this file format?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< MeshedSurface > New (const fileName &, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< MeshedSurface > New (const fileName &)
Select constructed from filename (implicit extension)
static void write (const fileName &, const MeshedSurface< face > &)
Write to file.
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
static fileName localMeshFileName (const word &surfName="")
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName="")
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName="")
Find mesh file with surfName.
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
Protected Member Functions inherited from MeshedSurface< face >
void transcribe (MeshedSurface< face > &)
Transfer points/zones and transcribe face -> triFace.
void transcribe (MeshedSurface< face > &surf)
void transcribe (MeshedSurface< face > &surf)
void checkZones ()
Basic sanity check on zones.
pointField & storedPoints ()
Non-const access to global points.
List< face > & storedFaces ()
Non-const access to the faces.
surfZoneList & storedZones ()
Non-const access to the zones.
void sortFacesAndStore (const Xfer< List< face >> &unsortedFaces, const Xfer< List< label >> &zoneIds, const bool sorted)
Sort faces by zones and store sorted faces.
virtual void remapFaces (const labelUList &faceMap)
Set new zones from faceMap.
Static Protected Member Functions inherited from surfaceFormatsCore
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a list with a single entry,.
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
A sampledSurface from a triSurfaceMesh. It samples on the points/triangles of the triSurface.
- it either samples cells or (non-coupled) boundary faces
6 different modes:
source=cells, interpolate=false: finds per triangle centre the nearest cell centre and uses its value
source=cells, interpolate=true finds per triangle centre the nearest cell centre. Per surface point checks if this nearest cell is the one containing point; otherwise projects the point onto the nearest point on the boundary of the cell (to make sure interpolateCellPoint gets a valid location)
source=insideCells, interpolate=false: finds per triangle centre the cell containing it and uses its value. Trims triangles outside mesh.
source=insideCells, interpolate=true Per surface point interpolate cell containing it.
source=boundaryFaces, interpolate=false: finds per triangle centre the nearest point on the boundary (uncoupled faces only) and uses the value (or 0 if the nearest is on an empty boundary)
source=boundaryFaces, interpolate=true: finds per triangle centre the nearest point on the boundary (uncoupled faces only). Per surface point projects the point onto this boundary face (to make sure interpolateCellPoint gets a valid location)
since it finds a nearest per triangle each triangle is guaranteed to be on one processor only. So after stitching (by sampledSurfaces) the original surface should be complete.
Source files
sampledTriSurfaceMesh.H
sampledTriSurfaceMesh.C
Definition at line 86 of file sampledTriSurfaceMesh.H.
Member Enumeration Documentation
samplingSource
enum samplingSource
Types of communications.
Enumerator
cells
insideCells
boundaryFaces
Definition at line 93 of file sampledTriSurfaceMesh.H.
Constructor & Destructor Documentation
sampledTriSurfaceMesh() [1/3]
sampledTriSurfaceMesh (const word & name, const polyMesh & mesh, const word & surfaceName, const samplingSource sampleSource)
Construct from components.
Definition at line 520 of file sampledTriSurfaceMesh.C.
Referenced by nearestEqOp::operator()(), and sampledTriSurfaceMesh::sampledTriSurfaceMesh().
sampledTriSurfaceMesh() [2/3]
sampledTriSurfaceMesh (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 549 of file sampledTriSurfaceMesh.C.
References sampledTriSurfaceMesh::sampledTriSurfaceMesh().
sampledTriSurfaceMesh() [3/3]
sampledTriSurfaceMesh (const word & name, const polyMesh & mesh, const triSurface & surface, const word & sampleSourceName)
Construct from triSurface.
Definition at line 577 of file sampledTriSurfaceMesh.C.
~sampledTriSurfaceMesh()
~sampledTriSurfaceMesh () virtual
Destructor.
Definition at line 608 of file sampledTriSurfaceMesh.C.
Member Function Documentation
TypeName()
TypeName ("sampledTriSurfaceMesh")
Runtime type information.
needsUpdate()
bool needsUpdate () const virtual
Does the surface need an update?
Implements sampledSurface.
Definition at line 614 of file sampledTriSurfaceMesh.C.
expire()
bool expire () virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implements sampledSurface.
Definition at line 620 of file sampledTriSurfaceMesh.C.
References clear(), and sampledSurface::clearGeom().
update() [1/2]
bool update () virtual
Update the surface as required.
Do nothing (and return false) if no update was needed
Implements sampledSurface.
Definition at line 640 of file sampledTriSurfaceMesh.C.
References polyMesh::FACE_PLANES, and mesh.
Referenced by nearestEqOp::operator()().
update() [2/2]
bool update (const treeBoundBox & bb)
Update the surface using a bound box to limit the searching.
For direct use, i.e. not through sample. Do nothing (and return false) if no update was needed
Definition at line 654 of file sampledTriSurfaceMesh.C.
References polyMesh::FACE_PLANES, mesh, and sampledTriSurfaceMesh::sample().
points()
virtual const pointField& points () const inline virtual
Points of surface.
Implements sampledSurface.
Definition at line 207 of file sampledTriSurfaceMesh.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::points().
faces()
virtual const faceList& faces () const inline virtual
Faces of surface.
Implements sampledSurface.
Definition at line 213 of file sampledTriSurfaceMesh.H.
References MeshedSurface< face >::faces(), sampledSurface::interpolate(), sampledTriSurfaceMesh::print(), and sampledTriSurfaceMesh::sample().
sample() [1/5]
Foam::tmp< Foam::scalarField > sample (const volScalarField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 669 of file sampledTriSurfaceMesh.C.
Referenced by sampledTriSurfaceMesh::faces(), sampledTriSurfaceMesh::sample(), and sampledTriSurfaceMesh::update().
sample() [2/5]
Foam::tmp< Foam::vectorField > sample (const volVectorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 678 of file sampledTriSurfaceMesh.C.
References sampledTriSurfaceMesh::sample().
sample() [3/5]
Foam::tmp< Foam::sphericalTensorField > sample (const volSphericalTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 686 of file sampledTriSurfaceMesh.C.
References sampledTriSurfaceMesh::sample().
sample() [4/5]
Foam::tmp< Foam::symmTensorField > sample (const volSymmTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 695 of file sampledTriSurfaceMesh.C.
References sampledTriSurfaceMesh::sample().
sample() [5/5]
Foam::tmp< Foam::tensorField > sample (const volTensorField & vField) const virtual
Sample field on surface.
Implements sampledSurface.
Definition at line 704 of file sampledTriSurfaceMesh.C.
References sampledSurface::interpolate().
interpolate() [1/5]
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 713 of file sampledTriSurfaceMesh.C.
References sampledSurface::interpolate().
interpolate() [2/5]
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 722 of file sampledTriSurfaceMesh.C.
References sampledSurface::interpolate().
interpolate() [3/5]
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 730 of file sampledTriSurfaceMesh.C.
References sampledSurface::interpolate().
interpolate() [4/5]
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 739 of file sampledTriSurfaceMesh.C.
References sampledSurface::interpolate().
interpolate() [5/5]
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
Interpolate field on surface.
Implements sampledSurface.
Definition at line 748 of file sampledTriSurfaceMesh.C.
print()
void print (Ostream & os) const virtual
Write.
Reimplemented from sampledSurface.
Definition at line 756 of file sampledTriSurfaceMesh.C.
References Foam::name(), and points.
Referenced by sampledTriSurfaceMesh::faces().
sampleField()
Foam::tmp<Foam::Field<Type> > sampleField (const GeometricField< Type, fvPatchField, volMesh > & vField) const
Definition at line 33 of file sampledTriSurfaceMeshTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), cells, forAll, mesh, patchi, tmp< T >::ref(), and Foam::Zero.
interpolateField()
Foam::tmp<Foam::Field<Type> > interpolateField (const interpolation< Type > & interpolator) const
Definition at line 89 of file sampledTriSurfaceMeshTemplates.C.
References cells, forAll, interpolation< Type >::interpolate(), mesh, and tmp< T >::ref().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledTriSurfaceMesh/sampledTriSurfaceMesh.H
src/sampling/sampledSurface/sampledTriSurfaceMesh/sampledTriSurfaceMesh.C
src/sampling/sampledSurface/sampledTriSurfaceMesh/sampledTriSurfaceMeshTemplates.C